### ISSUE TITLE
Bug: v8.0.0-rc.5 Culled containers are culled forever

### ISSUE THREAD

**Issue by davidye** [pixijs/pixi.js#10136]
### Current Behavior

Starting a new issue for clarity's sake.

When the scene is culled with Culler.shared.cull(), containers that are culled in prior calls are culled forever unless explicitly reset with container.visible = true.

See playground example: https://www.pixiplayground.com/#/edit/WhU7CVBPsqQn37HwXYpeL

### Expected Behavior

The playground example should render without the need to manually reset the 'visible' property.

### Steps to Reproduce

See playground

### Environment

See playground

**Comment by Zyie** [comment]
hey @davidye i've added a pr to add a new property so it no longer overrides visible. Let me know if this solves your issues
