### ISSUE TITLE
Bug: v8.0.0.rc-8 Texture.update() does not update when source is resized

### ISSUE THREAD

**Issue by davidye** [pixijs/pixi.js#10190]
### Current Behavior

Still running into issues with Texture.update(), see playground:

https://www.pixiplayground.com/#/edit/cJck-NGd-pxi-_WlEhJrh

It appears that resizing the canvas does not resize the texture even after calling update().

### Expected Behavior

Texture is resized properly

### Steps to Reproduce

See playground

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by GoodBoyDigital** [comment]
hey! this is fixed in the next release 👍 

![Image](https://github.com/pixijs/pixijs/assets/3112434/d32e8f56-c35a-40a6-bd22-078979b198e5)
