### ISSUE TITLE
Bug: removeChild() not working when using a container from pixi.stage

### ISSUE THREAD

**Issue by steven-twerdochlib** [pixijs/pixi.js#10709]
### Current Behavior

child is not removed.

### Expected Behavior

child to be removed

### Steps to Reproduce

`pixi.stage.removeChild(pixi.stage.children.filter(child =>
          child.name === '123'
        ));`

The above code doesn't remove the child. (I'm certain that the filter is returning one of the children)

### Environment

pixi.js` version: 7.4.2
Browser: Chrome
OS & Version: Windows 10

**Comment by bigtimebuddy** [comment]
Try this using the args spread `...` operator since removeChild doesn't accept an array:

```js
pixi.stage.removeChild(...pixi.stage.children.filter(child => child.name === '123' ));
```
Or alternatively use find for a single element:

```js
pixi.stage.removeChild(pixi.stage.children.find(child => child.name === '123' ));
```


See docs for removeChild:

https://pixijs.download/dev/docs/scene.Container.html#removeChild

**Comment by steven-twerdochlib** [comment]
Thanks for the quick response, this has solved my initial issue.

Follow up question though, my mouse listener is no longer working on the specified image after adding the child back in (it still works outside the image and on other images). Do you have any idea what has caused this?
I add the child back in later by storing the child before removal: 
`this.childRemoved = (pixi.stage.children.find(child => child.name === '123' ));
 pixi.stage.removeChild(pixi.stage.children.find(child => child.name === this.imageList[this.selectedImage].container.name ));;`
And adding it back in like so: 
`pixi.stage.addChild(this.childRemoved );`

My mouse listener is setup in mounted() like so:

```
pixi.stage.eventMode = 'static';
pixi.stage.hitArea = pixi.screen;
pixi.stage.on('mousedown', (event: any) => {
      console.log(2);
      this.leftMouseDown(event);
    });
```
