### ISSUE TITLE
arcTo, arc

### ISSUE THREAD

**Issue by NikkiKoole** [pixijs/pixi.js#1086]
Hi, first of all mucho mucho thanks for v2!, I am curious what goodies are upcoming seeing the speed and class of the development uptill now;)

I am playing with some arc drawing and I found one little regression I believe:

```
stage = null
renderer = null

makeExperiment = ->
    graphics = new PIXI.Graphics()
    graphics.lineStyle(10,0xff00ff)
    graphics.arc(100,100,200, 0, 2*Math.PI)
    stage.addChild graphics

window.onload = ->
    renderOptions =
        antialiasing:true
        transparent:false
        resolution:1
    renderer = new PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, renderOptions)
    document.body.appendChild renderer.view
    stage = new PIXI.Stage 0xe7e7e7
    makeExperiment()
    renderer.render(stage)
```

This crashes with a "Uncaught TypeError: Cannot read property 'shape' of null" in PIXI.Graphics.arc, on line var points = this.currentPath.shape.points;

In the former version this worked, and I think it should because the way the arc function works isn't using the last node in it's currentPath (unlike LineTo for example)

anyway getting rid of that error is dead simple by just doing a graphics.moveTo(100,100) in this case.

I have another question and that's todo with arcTo, 
Basically I don't see it's effect or can't get it doing anything, I would like some examples to take a look at actually, because I don't know if i am crazy or something is broken or something else.
I have this code:

```
    graphics = new PIXI.Graphics()
    graphics.lineStyle(10,0xff00ff)
    graphics.moveTo(200,200)
    graphics.lineTo(400,400)

    graphics.lineStyle(10,0xff0000)
    graphics.arcTo(200,200,400,400, 200)

    stage.addChild graphics
```

The pink straight lineTo is drawn from 200,200 to 400,400, but I just cannot get the arcTo to appear, I've fiddled around a little with it and found another little thing, when I put in 0 for the radius (it's not very logical for a curveTo, but might be handy in some dynamic ways) It errors with a "Uncaught TypeError: undefined is not a function " on `points.push(x1, y1);` in PIXI.Graphics.arcTo

but mostly though this whole post is me asking how I should use PIXI.Graphics.arcTo ;)

**Comment by Elyx0** [comment]
@GoodBoyDigital I came across a problem with making arcs with PIXI.Graphics, why only 40 segs ?

http://codepen.io/Elyx0/pen/VLLEVb

If I up this number in arc prototype, I get a much smoother rendering, could it be possible to make this var public to set it before drawing ?

**Comment by LeonardDrs** [comment]
+1
