### ISSUE TITLE
Bug: Incorrectly applied filter areas

### ISSUE THREAD

**Issue by dragonbaba** [pixijs/pixi.js#10921]
### Current Behavior

The filter area of the filter does not match the actual effect

### Expected Behavior

After modifying the filter area, it should take effect normally

### Steps to Reproduce

Here's a code sample for Pixi Playground, and if you look at it, you'll be able to see the problem

### Environment

- **`pixi.js` version**: *e.g. 8.4.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://www.pixiplayground.com/#/edit/2Q8r-VVCOSlH5NDeSFdYX/>*

### Possible Solution

I don't know how to fix it because I found that the filter's running logic is different from before

**Comment by GoodBoyDigital** [comment]
heya, one change we made in v8 is that the filter area has its container transform applied to it, so it is no longer in global space. Could this be the issue?
