### ISSUE TITLE
Feature Request: Allow filters that are applied to sprites to run their shaders in local coordinate space

### ISSUE THREAD

**Issue by gordyr** [pixijs/pixi.js#1092]
It would be great to have an option to run a filter in the local coordinate space of the sprite it is attached to.  So that it is applied to the local transform of the display object.

We have several filters that need to run on sprites and require being in the sprites local coordinate space.  We are now combining them into one mega shader and using the new sprite shader feature in version 2.0.

Although this works very well it is not as flexible and means that every feature inside this mega shader is being calculated every frame whether it is required or not (turning features on/off with if/else statements in the mega shader is not the answer as it is so expensive).

If this is not possible then an equally good solution would be to allow multiple shaders to be run on a sprite using the new sprite shader system.

**Comment by totty90** [comment]
Also waiting for this (: thanks +1

**Comment by englercj** [comment]
This is implemented now, you can use `calculateSpriteMatrix` from the filter manager. See the DisplacementFilter for an example.
