### ISSUE TITLE
Resolution change causes incorrect events (hitArea) handling

### ISSUE THREAD

**Issue by pavel-manylov** [pixijs/pixi.js#1094]
Resolution change after first rendering (with `resize` call) leads to correct re-rendering, but incorrect handling of events (like `click`), however if resolution will be changed back to initial value, events will be handled correctly.

I understand that resolution change is not so frequent action, but in multi-display situation it will be very useful: when I open browser on common display and move window to Retina display, I want to see crisp text and all that cool antialiasing. Currently I set resolution value at least to "2" (it also fixes blurred text rendering), but it's not so clever to render twice larger image (given my stage size is also really big) on not-so-fast devices with ordinary resolution.

Bug checked on Firefox & Safari (MacOS) with 2.0 release using CanvasRenderer, [jsFiddle](http://jsfiddle.net/pmanylov/gjLf6yb2/) available.

**Comment by wojciak** [comment]
Runned into this today :) There's a simple fix:
stage.interactionManager.resolution = renderer.resolution;

tada! :)
