### ISSUE TITLE
incorrect hit area on android chrome for interactive events

### ISSUE THREAD

**Issue by ourvice** [pixijs/pixi.js#1106]
Hiya!

Noticed the hit area of the event object ( this case a mask object ) is missregistered.

http://instrumentspeaks.weareinstrument.com/temp/

if you hit this on and android ( nexus 5 ) on chrome it misreads the hit.

scroll down on the phone, then click on a "tile"
the tile should expand full screen, but it miss elects tiles below it.

Thanks!

Destin

**Comment by ayamflow** [comment]
+1 on this issue, having this on Nexus 7 with Android 4.4.3, but not happening on a Nexus 4 with 5.0.2.
I'm drawing the hitArea of each object and they look OK but after a few scrolls the click is not recognized at the correct location.

**Comment by GoodBoyDigital** [comment]
assuming this is fixed now!
