### ISSUE TITLE
Bug: Particle Rendering Bug

### ISSUE THREAD

**Issue by dragonbaba** [pixijs/pixi.js#11082]
### Current Behavior

The particle container encountered an exception when updating particle properties. This exception only occurs in webgpu mode (in webgpu mode, setting vertex to true will cause rendering exceptions)

### Expected Behavior

Behaves normally in webgl mode

### Steps to Reproduce

I submitted a link to the playground code

### Environment

- **`pixi.js` version**: *e.g. 8.5.2*
- **Browser & Version**: *e.g. Chrome 131.0.2903.63*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://www.pixiplayground.com/#/edit/2Q8r-VVCOSlH5NDeSFdYX/>*

### Possible Solution

Not sure

**Comment by GoodBoyDigital** [comment]
thanks for flagging and providing an example! will take a looksi!
