### ISSUE TITLE
Pixi 2 width and height issues in Text and DisplayObjectContainer

### ISSUE THREAD

**Issue by adireddy** [pixijs/pixi.js#1135]
Issue 1:
With resolution applied to the renderer, When I tried to access width and height of Text, the text is getting blurred.

```
console.log(_label.height);
```

![screen shot 2014-11-11 at 09 24 34](https://cloud.githubusercontent.com/assets/4947424/4990832/931a20ea-6984-11e4-80c8-796694addeab.png)

Issue 2:
Similarly when I tried to trace width and height of DisplayObjectContainer in stage resize event I am seeing different values on each event trigger.

**Comment by mattosullivan** [comment]
I'm also noticing problems with dimensions when adding elements to a container.  Has anyone got a fix for this?

**Comment by englercj** [comment]
As long as you set the resolution properly in the text as well it should be fine.

**Comment by mattosullivan** [comment]
Sorrt, @englercj, I should've been more clear.  The dimensions of containers containing a mixture of text, sprites, and other containers are being reported incorrectly.

**Comment by englercj** [comment]
Please open a new issue with a running example.

**Comment by davidafeil** [comment]
I am also getting blurred text after accessing a width or height value of a PIXI.Text element as in the examples above. It seems like this was not resolved since the first report? Is there a workaround?

**Comment by ivanpopelyshev** [comment]
@davidafeil you have to make font size something about 0.5x-2x of what you actually want. For example if height is 100px, then font size must be about 50px-200px , otherwise it wont be that good.

**Comment by GoodBoyDigital** [comment]
This should be sorted in v4 now 👍
