### ISSUE TITLE
rope 'automasking?' bug in Canvas

### ISSUE THREAD

**Issue by NikkiKoole** [pixijs/pixi.js#1144]
Hiya, I can past more code if needed, but what I am basically doing is using the PIXI.Rope functionality.
And when I scale the object I change the texture.height variable of the rope.
The goal is to have a line thickness which stays the same while the shape itself scales. (like a vector image)

This works on webGL
![](http://i.gyazo.com/8d33a241994b05bbbc4f7c5c405a6317.gif)

but Canvas has this weird behaviour
![](http://i.gyazo.com/e52b7a7dde2f9069721605b84e5819ec.gif)

**Comment by GoodBoyDigital** [comment]
should be cool in v4 👍
