### ISSUE TITLE
RenderTexture not clearing correctly on CanvasRenderer

### ISSUE THREAD

**Issue by AndyHorns** [pixijs/pixi.js#1147]
I am using pixi 2.0, have a DisplayObject container with a number of Sprites in it that are moving, I then render the DisplayObjectContainer to texture and it doesnt seem to clear the previous frame correctly whether i call clear or pass clear through the render call. This is currently only happening on CanvasRenderer, Webgl seems fine. I have literally reproduced this using your example11 but instead of rendering the stage to texture i render the displayobject with the bunnies to texture forcing CanvasRenderer.

**Comment by tywang2006** [comment]
any suggestion on this issue on v4?

**Comment by ivanpopelyshev** [comment]
@tywang2006 do you have something that I can just copy&paste into http://pixijs.github.io/pixi-examples-v2/#/basics/basic.js and see that its not working properly? Not old v2 code, but new one?

We'll fix that issue anyway, but the time spent on it will depend on how much information you give us.

**Comment by tywang2006** [comment]
i will try to make an example in fiddler

**Comment by ivanpopelyshev** [comment]
You don't need fiddler or that. You can just edit some example and then paste code here. That way we'll be able to test it on different versions of pixi

**Comment by tywang2006** [comment]
`
PIXI.loader.add('../assets/icons/icons.json').load(onAssetLoaded);
function onAssetLoaded(loader:any, resource:any):void {
    let renderer:any = new PIXI.CanvasRenderer(600, 600);
    renderer.backgroundColor = 0x000000;
    window.document.body.appendChild(renderer.view);
    var sprite = new PIXI.Sprite(PIXI.Texture.fromFrame('icon0'));
    var spriteNew = new PIXI.Sprite();
    spriteNew.texture = PIXI.RenderTexture.create(sprite.width, sprite.height);
    var stage = new PIXI.Container();
    stage.addChild(spriteNew);
    function render() {
        spriteNew.x+=1;
        sprite.x+=0.1;
        renderer.render(sprite,spriteNew.texture);
        renderer.render(stage);
        requestAnimationFrame(render);
    }
    render();
}
`
if you use WebGLRenderer, it works,but chosen CanvasRenderer will cause issue. thanks

**Comment by tywang2006** [comment]
PIXI.loader.add('../assets/icons/icons.json').load(onAssetLoaded);
function onAssetLoaded(loader:any, resource:any):void {
    let renderer:any = new PIXI.CanvasRenderer(600, 600);
    renderer.backgroundColor = 0x000000;
    window.document.body.appendChild(renderer.view);
    var sprite = new PIXI.Sprite(PIXI.Texture.fromFrame('icon0'));
    var spriteNew = new PIXI.Sprite();
    spriteNew.texture = PIXI.RenderTexture.create(sprite.width, sprite.height);
    var stage = new PIXI.Container();
    stage.addChild(spriteNew);
    function render() {
        spriteNew.x+=1;
        sprite.x+=0.1;
        renderer.render(sprite,spriteNew.texture);
        renderer.render(stage);
        requestAnimationFrame(render);
    }
    render();
}

**Comment by tywang2006** [comment]
it is typescript

**Comment by acmoles** [comment]
+1 updating render texture persists sprites in PIXI canvas mode with transparent background. Sprites persist when removed from the stage and when opacity set to 0.

**Comment by staff0rd** [comment]
If this issue persists in v4, and someone can supply a [pen](https://codepen.io) that shows it against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js), I'll reopen it.

**Comment by hanesjw** [comment]
I've had similar problems getting a RenderTexture to update a child texture on the fly using canvas. Works great in WebGL. Here is some code you can paste into the pixijs example pages located [here](https://pixijs.github.io/examples/#/demos/interactivity.js)

Toggle the disabledWebGl variable and see what happens in canvas; the old texture does not get removed. This result is actually better than what I've been working with. Whenever I try to swap out a texture in a RenderTexture in canvas nothing happens. It doesn't even add the texture i'm trying to swap in. Anyways here is the code.

var disabledWebGl = true;

var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb}, disabledWebGl);
document.body.appendChild(app.view);
var woodTexture = PIXI.Texture.fromImage('required/assets/button.png');
var bunnyTexture = PIXI.Texture.fromImage('required/assets/basics/bunny.png');

var sprites = [];
var container = new PIXI.Container();
for (var i = 0; i < 2; i++) {
    var bunny = new PIXI.Sprite(woodTexture);    
    bunny.x = 60 * i;
    bunny.y = 60 * i;
    container.addChild(bunny);
  	sprites.push(bunny);
}

var brt = new PIXI.BaseRenderTexture(300, 300, PIXI.SCALE_MODES.LINEAR, 1);
var rt = new PIXI.RenderTexture(brt);

var spriteHolder = new PIXI.Sprite(rt);

spriteHolder.x = 100;
spriteHolder.y = 100;
app.stage.addChild(spriteHolder);

app.ticker.add(function() {
    app.renderer.render(container, rt);
  	sprites[0].texture = bunnyTexture;
});

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/canvas/CanvasRenderer.js#L223

```js
// else {
// TODO: implement background for CanvasRenderTarget or RenderTexture?
// }
```

So, who wants to implement it?

**Comment by hanesjw** [comment]
I thought this may have been an old closed issue so I added this one https://github.com/pixijs/pixi.js/issues/4085 

It seems to behave differently on 5.0 alpha than it does on the current version I am using (4.2 I believe). 5.0 simply doesn't show anything while 4.2 does refresh the modified texture.

**Comment by ivanpopelyshev** [comment]
That's because 5,0 broke the canvas renderer completely.

**Comment by hawk8** [comment]
Now it was my turn to get to that it does not clear the drawing area.
The definition to Render is:
render (displayObject, renderTexture, clear, transform, skipUpdateTransform)

Where the clear flag when set to true should clear. As indicated above by ivanpopelsyshev it is just that the implementation that is missing. I have played around some and I think the fix can be rather easy.

Code is:
        if (clear !== undefined ? clear : this.clearBeforeRender)
        {
            if (this.renderingToScreen)
            {
                if (this.transparent)
                {
                    context.clearRect(0, 0, this.width, this.height);
                }
                else
                {
                    context.fillStyle = this._backgroundColorString;
                    context.fillRect(0, 0, this.width, this.height);
                }
            } // else {
            // TODO: implement background for CanvasRenderTarget or RenderTexture?
            // }
        }
If that is changed to:

        if (clear !== undefined ? clear : this.clearBeforeRender)
        {
                if (this.transparent)
                {
                    context.clearRect(0, 0, this.width, this.height);
                }
                else
                {
                    context.fillStyle = this._backgroundColorString;
                    context.fillRect(0, 0, this.width, this.height);
                }
        }

That is basically to just do the job independently if it is rendering to screeen or not. At least my stuff works with this change, but I hope it can get into a proper release as well.

**Comment by hawk8** [comment]
This issue persist in v4, see pen https://codepen.io/hawk8/pen/VydbMy
