### ISSUE TITLE
Detect when WebGLRenderer canvas already has a wrong context.

### ISSUE THREAD

**Issue by bartvanheukelom** [pixijs/pixi.js#1182]
We've just spent a good deal of time trying to find out why masking wouldn't work in our game with the `WebGLRenderer`, though it worked fine in a separate experiment.
The problem was that we were passing an existing canvas to the renderer (as the `view` option), which shouldn't be a problem, but moreover, that this canvas already had a WebGL context, which was not created with `stencil: true`.

While this is obviously our own fault and Pixi can't be blamed, it would be very helpful if `WebGLRenderer` could check whether the context it "creates" does indeed have the options that were passed in (accessible via getContextAttributes()), and throw an error (or log a warning) if not.
Maybe more correct would be to check if the canvas already has a context before creating one yourself, but I don't know if that's possible.

**Comment by GoodBoyDigital** [comment]
Hey chaps! Just Made this PR - can;t think of anything else to check!

**Comment by GoodBoyDigital** [comment]
PR has been rolled in 👍
