### ISSUE TITLE
getBounds not correct before render

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#1196]
getBounds does not return the correct values before a render() has been called.

var stage = new PIXI.Stage(0x000000, true);
var renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, null);

var gfx = new PIXI.Graphics();
gfx.beginFill(0xff0000,1);
gfx.drawRect(0,0,10,10);
gfx.endFill();
stage.addChild(gfx);
gfx.position.set(-10,-20);

console.log(stage.getBounds()); // outputs  0,0,10,10     (x,y,w,h )

renderer.render(stage);
console.log(stage.getBounds()); // outputs -10,-20,10,10     <- this is the correct bounds.

I was making a little utility to draw bounding boxes on all my items on the stage when i stumbled upon this.   solved it by making a new renderer and rendering the stage once (not visible)  but thats kinda ugly...

**Comment by stbaer** [comment]
+1

Am also having trouble with getBounds() on a container that has a graphics child. The bounds
are correct sometimes but then randomly wrong again.

Was playing around with updateTransform, updateLocalBounds, dirty=true etc before calling 
getBounds() but it didn't help.

**Comment by GoodBoyDigital** [comment]
Fixed in v4 👍
