### ISSUE TITLE
draw directed arrow for graph

### ISSUE THREAD

**Issue by swapnil-rapidops** [pixijs/pixi.js#1214]
hi guys,
 i am using pixijs with ngraph but i am facing issue with creating directed arrow, can anyone guide me how i can create directed arrow using graphics or using sprite(we should be able to use sprite object with graphics object), i am able to create line this way :
code:
graphics.lineStyle(5, 0xcccccc, 1);
graphics.moveTo(150, 400);
graphics.lineTo(500, 400);
graphics.lineStyle(0);

but not able to create arrow heads, please help me out as soon as possible, thanks in advance.

**Comment by qtttttttttting** [comment]
As for my project, the amount of  nodes and links are huge. I think, to draw every triangle for every line is too complicated. Can you have any better ideas?

**Comment by bigtimebuddy** [comment]
I just did this in a project with many lines and make the arrow tip a Sprite. Worked well for me.
