### ISSUE TITLE
question about the 'roadmap'

### ISSUE THREAD

**Issue by NikkiKoole** [pixijs/pixi.js#1240]
Hi just a non issue related question here;
What is the roadmap of pixi.js? what new additions are in the making?
I've recently been playing with the Rope class for example, it's one of these nice things I wouldn't imagine, are there more things like that in the making?

btw: I've seen the roadmap header in the doc, but I have the *feeling* it's rather old ;)

**Comment by englercj** [comment]
We are going to use the "Projects" feature going forward which should provide a good roadmap!
