### ISSUE TITLE
How can I "offset" a texture being "drawn" to a sprite with a certain amount of pixels?

### ISSUE THREAD

**Issue by RubrikBonnier** [pixijs/pixi.js#1242]
To make a very long story short, I need to offset the image I'm "drawing" to a sprite. I'm currently doing this:

aTile.setTexture(preLoadedTileImages[tileNumber]);

That works in that it sets the entire "texture" for the sprite to that image. However, I need to "offset" it (after preferably "clearing" the existing texture with some flat color). Can this be done? I sure hope so.

**Comment by chinchang** [comment]
You can set the `frame` property on your texture:

```
texture.frame = new PIXI.Rectangle(1, 1, 58, 16);
```
