### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'baseTexture' of undefined"

### ISSUE THREAD

**Issue by RubrikBonnier** [pixijs/pixi.js#1244]
On this line in the Pixi.js source (not my code):    if(texture.baseTexture.hasLoaded)

I can't figure out what is causing this. Is there something obvious that could cause it?

**Comment by rknDA1337** [comment]
And here I came from Google and still clueless.. Blast

**Comment by RashadSaleh** [comment]
@RubrikBonnier Can you please explain how did you figure it out? Thanks.

**Comment by ivanpopelyshev** [comment]
@RashadSaleh dont do new PIXI.Sprite(); please give it a texture. At least, do new PIXI.Sprite(PIXI.Texture.EMPTY); and change texture after it

**Comment by fancyoung** [comment]
@ivanpopelyshev it's not working on v3.0.11. Because `PIXI.Texture.EMPTY.baseTexture` is null.
https://github.com/pixijs/pixi.js/blob/v3.0.11/src/core/sprites/Sprite.js#L167

**Comment by ivanpopelyshev** [comment]
Did you somehow destroy PIXI.Texture.EMPTY? Also it works in v4 (https://github.com/pixijs/pixi.js/tree/dev)

**Comment by fancyoung** [comment]
@ivanpopelyshev I find out it caused by this bug: https://github.com/pixijs/pixi.js/issues/2460 , it not fixed in 3.0.11

**Comment by ivanpopelyshev** [comment]
Yep, but it was fixed for v4. can you move to latest v4? :)

**Comment by steffomix** [comment]
Had the same error, but was my fault. Perhaps it helps you too:

```
// This causes the error
function AnyClass() {
    pixi.Sprite.call(this, pixi.Sprite.fromImage('whatever-image'));
}
AnyClass.prototype = Object.create(pixi.Sprite.prototype);

// This works
function AnyClass() {
    pixi.Sprite.call(this, pixi.Texture.fromImage('whatever-image'));
}
AnyClass.prototype = Object.create(pixi.Sprite.prototype);

// pixi.Sprite.call(this, pixi.Sprite.fromImage(...
// must be 
// pixi.Sprite.call(this, pixi.Texture.fromImage(...```
