### ISSUE TITLE
Can I turn off the color banner in the console that Pixi adds?

### ISSUE THREAD

**Issue by RubrikBonnier** [pixijs/pixi.js#1259]
That pink background and the red hearts were kind of funny the first time, but it's starting to become annoying. Can I turn it off somehow? I don't want it to advertise itself like that, especially not for distribution mode.

**Comment by artifex404** [comment]
I do not agree @photonstorm, Pixi is released under the MIT License, so as long you keep the copyright notices in the source code of the library you're free to modify the source. For example setting `PIXI.dontSayHello = true` by default in the source code.

**Comment by photonstorm** [comment]
@artifex404 why are you commenting on a 4 year old post? If you want to disable the banner, you know how. It's a trivial thing to add to your source. Don't be lazy.

**Comment by englercj** [comment]
@carlsmith Open a new issue please, this is a 5 year old unrelated issue.
