### ISSUE TITLE
WebGLRenderer copies SVGs loaded into sprites

### ISSUE THREAD

**Issue by konsumer** [pixijs/pixi.js#1287]
I want to use inkscape as a level-editor for a vector game. The idea is draw all the shapes on named layers, then turn all the top-level things in each layer into sprites with the correct initial position. The parsing works well, and I am generating data-url for all the individual elements, but when I make sprites, if the renderer is WebGL, it copies all of them into every sprite. It works as expected with canvas.

* [Here](http://konsumer.s3.amazonaws.com/svg_pixi/webgl.html) is the (broken) WebGL version
* [Here](http://konsumer.s3.amazonaws.com/svg_pixi/canvas.html) is the identical (working) Canvas version

I am guessing I am missing something with cached OpenGL buffers? I tried `preserveDrawingBuffer=false`, but it didn't seem to do anything.

**Comment by uZodiac** [comment]
I may have the same problem. Just adding that your two version work exactly the same in Firefox, the problem appears when I'm using Chrome. I'm trying to firgure out myself where it go wrong but got no luck. If someone have a clue it would be great.

**Comment by konsumer** [comment]
Yeh, I am also using chrome.

**Comment by vanillabass** [comment]
+1

**Comment by Shurikov** [comment]
+1

**Comment by zerovox** [comment]
I'm seeing this issue too, @englercj any idea why this may be occurring?

**Comment by zerovox** [comment]
[This chrome bug](https://code.google.com/p/chromium/issues/detail?id=500180) seems relevant

**Comment by konsumer** [comment]
I made a [demo using an intermediary canvas](http://konsumer.s3.amazonaws.com/svg_pixi/webgl2.html) and it worked fine. I can live with this, as a work-around.

**Comment by englercj** [comment]
Closing this since we have done some SVG improvements recently that may have caught this. Additionally that Chrome bug is fixed now.

**Comment by konsumer** [comment]
Sweet. Just realized I accidently took down my demos! I will see if I can find them and update the links.

**Comment by konsumer** [comment]
I can't seem to find the demos I made anywhere, but you can see an illustration of it working properly [here](http://notnullgames.github.io/circles/)
