### ISSUE TITLE
PIXI.AUTO_PREVENT_DEFAULT = false and mousedown events on mobile

### ISSUE THREAD

**Issue by Lochlan** [pixijs/pixi.js#1311]
### The issue
Setting `PIXI.AUTO_PREVENT_DEFAULT = false` seems to cause `mousedown` events to fire alongside touch events.

If you take a look at the console output of [this example I made](http://lochlan.github.io/pixijs-tap-mousedown-issue-demo/prevent-default-false.html) using a mobile device or equivalent you'll see that tapping on the canvas will produce output that looks something like this:

```
onTouchStart
onTouchEnd
onMouseDown
```

(Note that I added a couple console.logs to pixi.js to produce this output.)  If you look at [the sample example without that line](http://lochlan.github.io/pixijs-tap-mousedown-issue-demo/prevent-default-true.html) you'll see that this doesn't happen.

I'm seeing this issue in Chrome mobile emulation, the iOS simulator, and my Droid Mini running Android 4.4.4.

### Why this is a problem
I need to set `AUTO_PREVENT_DEFAULT` to `false` in order to enable scrolling while swiping on an interactive canvas, as [recommended elsewhere](https://github.com/GoodBoyDigital/pixi.js/issues/814).  The problem arises when I attach event handlers with something like `mysprite.click = mysprite.tap = someCallbackFunction`.  On desktop this works as-needed, but on mobile the unnecessarily triggered `mousedown` event can cause a second event callback to fire.  Any help with this would be greatly appreciated.

**Comment by Lochlan** [comment]
One of my coworkers pointed out that I can use [underscore](http://underscorejs.org/)'s [`_.throttle`](http://underscorejs.org/#throttle) or [`_.once`](http://underscorejs.org/#once) (since I'm also using underscore in my project) , which will work for now — although it would be great if this erroneous event would go away!

**Comment by englercj** [comment]
Note that we will be rewriting the interaction manager here soon, see #1296 and #241 for more info. We will keep these issues in mind when we get to that part.

**Comment by englercj** [comment]
Can you test this in v3 and see if this is still an issue?

**Comment by adamjacob** [comment]
Any update on this issue?  I'm having the same issue where I need to enable the default pan and zoom of the page.

**Comment by englercj** [comment]
See: #2071

**Comment by englercj** [comment]
This should be fixed in the latest `dev` branch.
