### ISSUE TITLE
Tint does not work on TilingSprite with Canvas renderer

### ISSUE THREAD

**Issue by shanemccartney** [pixijs/pixi.js#1339]
Not sure if this is intended that tint does not work with a TilingSprite on Canvas but is annoying that its does not work consistently.

**Comment by nextht** [comment]
PIXI.Graphics not support tint also in Canvas mode, but work on WebGL

**Comment by adelciotto** [comment]
@nextht Graphics object tinting with canvas has been fixed in: https://github.com/GoodBoyDigital/pixi.js/pull/1461
