### ISSUE TITLE
normalMapFilter will make everything white/transparent

### ISSUE THREAD

**Issue by bitplanets** [pixijs/pixi.js#1355]
The image is multiple of 2, 512x512px;

    var normalMap = PIXI.Texture.fromImage(require("assets/images/4141-normal.jpg"));
    normalMapFilter = new PIXI.NormalMapFilter(normalMap);
    myGroup.filters = [normalMapFilter]

With other filters works.

I've also put on phaser, but one of you can close this issue. https://github.com/photonstorm/phaser/issues/1545

Phaser 2.2.2; PIXI: 2.2.0; webgl

**Comment by GoodBoyDigital** [comment]
sure this is fixed in v4 👍
