### ISSUE TITLE
Double-click support

### ISSUE THREAD

**Issue by cmdelatorre** [pixijs/pixi.js#1386]
Hello,

I wanted to know if there is any plan to provide a dbl-click interaction.

Currently, I've implemented it outside of PIXI, roughly following http://stackoverflow.com/questions/6330431/jquery-bind-double-click-and-single-click-separately/7845282#7845282

But I think it'd be great if PIXI provided the capability to distinguish click/dbl-click events, maybe even with a configurable delay.

Any ideas?

**Comment by englercj** [comment]
Closing this since we decided not to do it.
