### ISSUE TITLE
bindBuffer warning with multiple renderers on a page

### ISSUE THREAD

**Issue by rachaels** [pixijs/pixi.js#1409]
I have two renderers on a page, each with one graphics object. After clearing one graphics object, I'm unable to draw to the second one, and I get the following warning:

```
WebGL: INVALID_OPERATION: bindBuffer: object not from this context
[.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
```

Here's the pared-down code:

```
function Obj() {
    var renderer = new PIXI.WebGLRenderer(400,400);
    document.body.appendChild(renderer.view);

    var stage = new PIXI.Stage;

    this.graphic = new PIXI.Graphics;
    this.graphic.beginFill(0x000000);
    stage.addChild(this.graphic);

    requestAnimationFrame(render);

    function render() {
        renderer.render(stage);
        requestAnimationFrame(render);
    }
}
```

With two objects on the page while animation is running, I draw to one, clear it, then try to draw to the second:

```
var a = new Obj();
var b = new Obj();

a.graphic.drawCircle(0,0,0);
a.graphic.clear();

b.graphic.drawCircle(0,0,0);
```

The graphics object here does get the shape added, but it fails to actually draw the object and throws the above WebGL bindBuffer warning.

**Comment by GoodBoyDigital** [comment]
Hi there! Just tested and this is working like a champ in v3 now. Thanks for sharing :+1:

**Comment by goldenratio** [comment]
@englercj this issue seems to be back in 4.3.0. Can you please check.
http://codepen.io/kuuuurija/pen/QdLjmW

**Comment by englercj** [comment]
@GoodBoyDigital Can you look at this? Possibly a Graphics issue.

**Comment by GoodBoyDigital** [comment]
roger!

**Comment by GoodBoyDigital** [comment]
Hello! Turned out to be a slightly different issue. Setting the radius of the circle to 0 is what causes the webGL issue. Just pushed a fix to catch it 👍
