### ISSUE TITLE
SVG with clipped bitmap in Safari

### ISSUE THREAD

**Issue by vass-david** [pixijs/pixi.js#1411]
I am trying to use svg image as sprite.

**Problem:**

When I use svg with bitmap in it, it will not load correctly in Safari. Other browsers are fine. Using SVG without bitmap in it work also fine in Safari. SVG is loaded from external source to Image object.

**Coffeescript code:**

      # loading svg
      sprite = new Image()
      sprite.src = sprite_url
      sprite.onload = ((sprite) ->
      
        # scale it to proper size
        sprite.height = Math.round(parseFloat(sprite.height) * @options.scale)
        sprite.width = Math.round(parseFloat(sprite.width) * @options.scale)
        $('body').append(sprite)

        # create pixi sprite
        obj = new PIXI.Sprite(
          new PIXI.Texture(
            new PIXI.BaseTexture(sprite),
            new PIXI.Rectangle(0, 0, sprite.width, sprite.height)
          )   
        )   
        $(sprite).remove()

        # add sprite to stage
        @stage.addChild obj

      )(sprite)

SVG is resized first, because pixi js will convert it to bitmap before adding to stage and scaling after that would degrate quality of image.

I thought there is problem with canvas or svg in Safari, but opening just SVG file in safari works fine. SVG file's mimetype is image/xml+svg and SVG is broken even in developer tools resources tab, so the problem is maybe loading via Image object. Is there any other way of importing preloaded SVG image than via Image object? 

I am pretty desperate with this issue and will gladly welcome any suggestions/help.

Thanx.

**Comment by englercj** [comment]
This may be fixed in the latest `dev` after all the recent SVG improvements.
