### ISSUE TITLE
multi-texturing?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#1456]
If I have 2 textures: 
 
1 - level background image
2 - light map image that I calculated for for my level geometry

I want to combine the lightmap image into my background image. I'm having trouble finding the right classes to do this from the API docs here: 

http://www.goodboydigital.com/pixijs/docs/

Any advice would be greatly appreciated! :)

**Comment by mreinstein** [comment]
by the way, I'd love to contribute to this project. Maybe docs are something I could start with? Are there any guides beyond http://www.pixijs.com/examples/  and http://www.pixijs.com/resources/ ?

**Comment by englercj** [comment]
To answer your original question there are no shipped classes to help with lighting. Mat wrote a christmas experiment that did lighting with normal maps, but you will have to do lighting in a custom shader/filter.

To contribute docs, feel free to send a PR to the `dev` branch (the v3 release) or the `v2.x` branch (v2 maintenance line). You can also contribute examples for v3 to: https://github.com/pixijs/examples

**Comment by woutercommandeur** [comment]
Would be awesome to have support for deferred lighting in v3 :)

**Comment by GoodBoyDigital** [comment]
i certainly would - the good news is its on the todo list :)  going to keep this open as a reminder.

**Comment by mreinstein** [comment]
Sorry, just saw that GoodBoyDigital wants to keep this open as a reminder, re-opening.

**Comment by englercj** [comment]
Closing this, no lighting in the main repo in the immediate future :)
