### ISSUE TITLE
Thoughts on Pixi v3 Filters/Shaders

### ISSUE THREAD

**Issue by mattdesl** [pixijs/pixi.js#1460]
Amazing progress on v3 :scream: 

Been poking around the [v3 filters](https://github.com/GoodBoyDigital/pixi.js/tree/dev/src/filters), thinking it would be cool to eventually align with the goals of [glslify](http://mattdesl.svbtle.com/glslify). This would help encourage more userland growth and variety (i.e. [glsl-film-grain](https://github.com/mattdesl/glsl-film-grain)) and could enable some awesome workflows like [live shader reloading](https://www.youtube.com/watch?v=Bbb2sFH5yf8).

This could be maintained outside of Pixi using a `pixi-glslify` bridge (like the [ThreeJS](https://www.npmjs.com/package/three-glslify) bridge).

Or, some changes could be made to Pixi's uniform naming/conventions to align with those in [glsl-extract](https://github.com/stackgl/glsl-extract/blob/c4fca972f620f77fd1b8b0a3df3913e725cf19b5/test/collect.js#L6-L31). This could lead to a pretty nice standardization of shaders across different render engines (like Pex, Pixi, stack.gl, etc) and would make it really easy to compose Pixi with existing modules. `brfs` could still be used for the "out of the box" filters if you wanted to keep things simple. 

To me it's a bit odd that some uniform data structures are objects, and others are arrays:

```js
            scale:            { type: '2f', value: { x: 15, y: 15 } },
            offset:           { type: '2f', value: { x: 0,  y: 0 } },
            mapDimensions:    { type: '2f', value: { x: 1,  y: 1 } },
            dimensions:       { type: '4f', value: [0, 0, 0, 0] },
```

I'm sure @chrisdickinson, @mikolalysenko and @hughsk can chime in if you have questions about glslify's roadpath. :+1:

**Comment by englercj** [comment]
Sounds like something to look into.

Fyi, if the uniforms you pasted are actually in source, then they are wrong. `#f` is an array, always. If you want to use objects it should be `v#`, just like three.js

**Comment by logan503k** [comment]
25 февр. 2015 г. 0:09 пользователь "Matt DesLauriers" <
notifications@github.com> написал:
>
> Amazing progress on v3
>
> Been poking around the v3 filters, thinking it would be cool to
eventually align with the goals of glslify. This would help encourage more
userland growth and variety (i.e. glsl-film-grain) and could enable some
awesome workflows like live shader reloading.
>
> This could be maintained outside of Pixi using a pixi-glslify bridge
(like the ThreeJS bridge).
>
> Or, some changes could be made to Pixi's uniform naming/conventions to
align with those in glsl-extract. This could lead to a pretty nice
standardization of shaders across different render engines (like Pex, Pixi,
stack.gl, etc) and would make it really easy to compose Pixi with existing
modules. brfs could still be used for the "out of the box" filters if you
wanted to keep things simple.
>
> To me it's a bit odd that some uniform data structures are objects, and
others are arrays:
>
>             scale:            { type: '2f', value: { x: 15, y: 15 } },
>             offset:           { type: '2f', value: { x: 0,  y: 0 } },
>             mapDimensions:    { type: '2f', value: { x: 1,  y: 1 } },
>             dimensions:       { type: '4f', value: [0, 0, 0, 0] },
>
> I'm sure @chrisdickinson, @mikolalysenko and @hughsk can chime in if you
have questions about glslify's roadpath.

**Comment by GoodBoyDigital** [comment]
Hey @mattdesl ! A good shout indeed. ```pixi-glslify``` sounds really interesting :+1: 
Once v3 has been launched definitely keen to investigate this..

**Comment by ayamflow** [comment]
It would be really nice to have a proper document on uniforms/attributes types and values, like the ThreeJS one: https://github.com/mrdoob/three.js/wiki/Uniforms-types

**Comment by mattdesl** [comment]
glslify@2 no longer has any direct ties to stackgl or gl-shader. Now it's more generally just a source transform (like brfs) that returns shader source, but also handles Node-style require/export statements in GLSL.

```js
var src = require('glslify')('./frag.glsl')
console.log(src)
```

frag.glsl:

```js
precision mediump float;
#pragma glslify: random = require('glsl-random')
void main() {
  float n = random(gl_FragCoord.xy);
  gl_FragColor = vec4(n);
}
```

After transform, the output from `console.log`:

```
#define GLSLIFY 1

precision mediump float;
highp float random_1_0(vec2 co)
{
    highp float a = 12.9898;
    highp float b = 78.233;
    highp float c = 43758.5453;
    highp float dt= dot(co.xy ,vec2(a,b));
    highp float sn= mod(dt,3.14);
    return fract(sin(sn) * c);
}

void main() {
  float n = random_1_0(gl_FragCoord.xy);
  gl_FragColor = vec4(n);
}
```

**Comment by englercj** [comment]
Neat, we can use that for the uniforms/attributes that pixi always exposed.

**Comment by GoodBoyDigital** [comment]
Better late than never! Pixi v4 uses glslify for shaders and filters now. Love it! :+1:
