### ISSUE TITLE
Video on iOS 6/7

### ISSUE THREAD

**Issue by adireddy** [pixijs/pixi.js#1485]
Hi guys, I am testing pixi video (streaming) and it only works on iOS 8 devices.

I did the same test using HTML5 video element and it works on all iOS 6+ versions.

So just want ask you guys if there are any known limitations?

**Comment by englercj** [comment]
Hmmm, I wish I had a device to test on. Are there any errors you get?

**Comment by adireddy** [comment]
I just connected iPad 2 with iOS 6 and there are no errors in the console. I can hear the audio playing in the background.

On iPad 4 with iOS 7, no errors and no audio as well.

**Comment by englercj** [comment]
does tapping the screen or doing some kind of interactivity help? IIRC iOS has some limitations like that...

@photonstorm You have a lot more experience than me in this area, thoughts on what this could be?

**Comment by adireddy** [comment]
It's working on iOS 8 by tapping/interactivity but not on anything below iOS 8. I will try this on different devices tomorrow and provide more information.

**Comment by adireddy** [comment]
Here is the URL I am testing. http://adireddy.github.io/demos/haxe-pixi/video.html

Tap on the screen to start the video.

**Comment by adireddy** [comment]
Just testing the same on pixi v3 and on iOS 8 and Android 5 I am seeing black rectange in place of video.

Fine on desktop.

**Comment by adireddy** [comment]
v3 sample url http://adireddy.github.io/demos/haxe-pixi/v3/video.html

**Comment by englercj** [comment]
WebGL video source has to be supported for video to work in WebGL, but it should work for canvas most everywhere.

Are you still getting this error in the latest release, and if so does iOS 6/7 support webgl video sources?

**Comment by photonstorm** [comment]
iOS 6/7 doesn't support WebGL at all, but it does support video sources rendered to canvas. As with all iOS devices the video must be touch unlocked first though before playback is allowed.

**Comment by englercj** [comment]
I have a feeling that this is a touch-lock issue, I can't think of any reason videos would work on iOS 8 but not 6/7 (in canvas).

**Comment by photonstorm** [comment]
Oh and for IE11 you cannot bind a video tag to a WebGL texture. I checked with the MS team and they confirmed this is fixed in Spartan, but won't be for IE11. They said the only workaround is to render the video to a canvas, and use the canvas as a WebGL texture. Lovely.

I'm not even going to start on the pain we had with Firefox video events :)

**Comment by englercj** [comment]
> Oh and for IE11 you cannot bind a video tag to a WebGL texture.

https://github.com/GoodBoyDigital/pixi.js/issues/1612

XD

**Comment by photonstorm** [comment]
Yeah :)

Firefox works though, not got any problems there. Although it has a lovely bug where in some versions (not super-current, but not THAT old) it returns NaN for the videoHeight. Which is fantastic. Thanks Firefox.

**Comment by englercj** [comment]
Ha! That is terrible, there always has to be something...

**Comment by GoodBoyDigital** [comment]
Seems like this is a safari setback rather than a pixi issue. Closing for now. Thanks all!
