### ISSUE TITLE
Bug Reminders

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#1536]
Going through the examples recently I noted a couple bugs I wanted to put down a reminder for:

- Bounds or FilterArea seems to grow/shrink on the blur example
- ~~ParticleContainer doesn't seem to honor transparent background of sprites, makes it black instead~~
- ~~ParticleContainer's second param needs to be an object instead of an array (easier to use)~~
- Displacement filter has a horizontal displace line, not sure if that supposed to be there...

**Comment by englercj** [comment]
Anthoner one:

- Graphics is missing a destroy method to cleanup GPU resources.

**Comment by GBagley** [comment]
+1 for me on the destroy() method for Graphics :+1:

**Comment by englercj** [comment]
Some loader parsers require the plugin they work for, this makes the loader plugin pull in other plugins that potentially might be ignored.

Loader parsers for specific plugins (spine, extras, etc) should be moved into their respective plugins and a registration system put into place for the pixi loader.

**Comment by tobireif** [comment]
Wuuld it be helpful to create separate issues? (eg for "ParticleContainer doesn't seem to honor transparent background of sprites, makes it black instead")

**Comment by englercj** [comment]
@tobireif We *could* but I don't think it would change anything.

**Comment by GoodBoyDigital** [comment]
i will fix the particle one today :+1: watch this space

**Comment by tobireif** [comment]
@GoodBoyDigital Sounds good - I will watch this space!

**Comment by GoodBoyDigital** [comment]
'ParticleContainer doesn't seem to honor transparent background of sprites, makes it black instead'

all fixed up now :+1:

**Comment by tobireif** [comment]
Great! Thanks! :+1:

And thanks for Pixi JS!

**Comment by englercj** [comment]
@GBagley Just implemented some destroy methods for particle container and graphics that should free up the gl buffers they create on destroy. Hope that works for you!

**Comment by GBagley** [comment]
Awesome -- thanks!

**Comment by GoodBoyDigital** [comment]
pretty sure the two remaining ones are nailed in v4 👍
