### ISSUE TITLE
support Graphics.{beginBitmapFill, lineBitmapStyle}

### ISSUE THREAD

**Issue by FlorianLudwig** [pixijs/pixi.js#1567]
API:

 * lineBitmapStyle(bitmap:BitmapData, matrix:Matrix = null, repeat:Boolean = true)
 * beginBitmapFill(bitmap:BitmapData, matrix:Matrix = null, repeat:Boolean = true)

as implemented in [flash](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Graphics.html)

Implementation is [WIP](https://github.com/GreyRook/pixi.js/tree/dev).

The GraphicsData class is growing quite a bit through this so we are going to introduce a `Brush` class.  Is this ok?

Adding everything to the constructor of GraphicsData we get:
```
function GraphicsData(lineWidth, lineColor, lineAlpha, lineBitmap, lineBitmapMatrix, lineBitmapRepeat, fillColor, fillAlpha, fillBitmap, fillBitmapMatrix, fillBitmapRepeat, fill, shape)
```
So we are looking to go for:
```
function GraphicsData(lineWidth, lineBrush, fillBrush, fill, shape)
```

with a new class `Brush` with the properties 
 * color
 * alpha
 * bitmap
 * bitmapMatrix
 * bitmapRepeat

And will grow further when we go for lineGradientStyle and beginGradientFill next ;)

*Edited* for clarification about the GraphicsData change and format fixed

**Comment by GoodBoyDigital** [comment]
this looks interesting!

**Comment by FlorianLudwig** [comment]
Implementation branch moved to [GreyRook:dev-bitmaps](https://github.com/GreyRook/pixi.js/tree/dev-bitmaps) based upon PR #1587 for refactoring `GraphicsData` with `Brush` classes.

**Comment by mattkenefick** [comment]
+1

**Comment by kasparsj** [comment]
+1

**Comment by englercj** [comment]
Closing in favor of the Brush Refactoring PR, which is serving as my reminder to do this in v5.
