### ISSUE TITLE
Sprites with textures from a spritesheet not working correctly as alpha masks in v3

### ISSUE THREAD

**Issue by baseten** [pixijs/pixi.js#1569]
This works fine:

```
var sprite = PIXI.Sprite.fromImage('path/to/img.png');
someDisplayObject.mask = sprite;
```

This seems to mess up the frame for the texture so the mask comes from other parts of the spritesheet:

```
var sprite = PIXI.Sprite.fromFrame('spriteSheetId');
someDisplayObject.mask = sprite;
```

I'll see if I can put a minimal example up somewhere

**Comment by GoodBoyDigital** [comment]
this does not work at the moment. Its planned but won't be for a while. Alpha Masks require a full texture to work correctly. :+1:

**Comment by hjujah** [comment]
+1

**Comment by veljamatic** [comment]
+1

**Comment by Shurikov** [comment]
+1

**Comment by GoodBoyDigital** [comment]
Hey @ivan, am i dreaming or did you add this in to v4?

**Comment by ivanpopelyshev** [comment]
Its fixed.
