### ISSUE TITLE
BitmapText and resolution property

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#1583]
Hello,

This is a feature request quick and easy to do. 

PIXI.Text has a "resolution" property, but PIXI.BitmapText does not. 

You can always use a bigger sized bitmap font, but so could you for a canvas Text and PIXI still manage canvas Text resolution.

We've implemented it for our needs this way : 

When we load a .fnt with a retina prefix, we devide the following lines by the resolution of the prefix : 
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/loaders/bitmapFontParser.js#L80

Our bitmapfont source image already has a retina prefix inside our .fnt so PIXI correctly loads the texture with a higher resolution.

The only thing left to do is to modify these lines : 
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/extras/BitmapText.js#L264
to divide once again the charDatas by the resolution of the baseTexture.

I did not propose a github pull request because first, I'm a newbie with github and I should really learn how to use it (I'm still an oldschool svn user), and second because I'm not sure if this is the best way to implement that feature and it is incomplete (you have to use a retina prefix, where it should be optional). 

The result is good but it is very different from Text.resolution property implementation.

**Comment by englercj** [comment]
Retina should work with the global RESOLUTION const, ideally Text wouldn't have its own specific one outside that either :)
