### ISSUE TITLE
Render the same stage on two canvases (WebGL)

### ISSUE THREAD

**Issue by jagi** [pixijs/pixi.js#1600]
Hello,
There was issue posted like 2 years ago about possibility to create two WebGL renderers on one page. The issue had been resolved but one error still is present. If you want to render **THE SAME STAGE** on two WebGL canvases it throws error. The error does not occur with CanvasRenderer.

I've prepared example: http://jsbin.com/duhacepira/2/edit?console,output

Could you confirm that it's a bug in PIXI and if you know about it? Do you have any plans to resolve it? Maybe I could help with that, but I need more information.

Someone may ask why the hell anyone would like to render the same stage on two canvases. I do :). I want to create double buffering. And to cut any comments about native support for double buffering in web canvas, I say it doesn't work in all situations. On low performance devices when frame doesn't finish rendering until next request animation frame it will flicker.

**Comment by englercj** [comment]
DO you experience this issue with the latest `dev` branch code?

**Comment by jagi** [comment]
Yes error still occurs with the `dev` branch code.

```
"TypeError: Cannot read property 'data' of undefined
    at r.render (<anonymous>:3:27060)
    at r._renderWebGL (<anonymous>:3:22874)
    at r.renderWebGL (<anonymous>:3:13904)
    at r.renderWebGL (<anonymous>:3:13972)
    at r.renderDisplayObject (<anonymous>:5:3780)
    at r.render (<anonymous>:5:3601)
    at render (vidini.js:52:8)
    at HTMLSelectElement.onchange (http://null.jsbin.com/runner:1:300247)"
```

**Comment by englercj** [comment]
Cool, I'll try to find some time to look into it this weekend.

**Comment by jagi** [comment]
Ok thanks :)

**Comment by woutercommandeur** [comment]
This is the exact same problem as #1635

**Comment by marksteve** [comment]
@englercj Any plans on working on this?
