### ISSUE TITLE
No pointer events in InteractionManager - and no mousewheel

### ISSUE THREAD

**Issue by Inateno** [pixijs/pixi.js#1605]
Hey guys,

I was checking the InteractionManager inside PIXI and didn't see pointer events registering as described here http://www.w3.org/Submission/pointer-events/

In my engine I was using handjs it's a polyfill for using only one event on your domElement.
=> https://handjs.codeplex.com/

Here is all events I was registering in my Inputs handler
```javascript
pointerdown
pointerup
pointerout
pointermove
DOMMouseScroll
mousewheel
```
Also I saw there is no "mouseWheel" support inside PIXI, is this planned or not ?

I'm asking before overwriting all InteractionManager ^^ I have to rework on my collision detection right now and I need this (I can do a pullRequest, but didn't change anything inside PIXI yet).

See ya

**Comment by drkibitz** [comment]
This seems like a good issue to give another plug for my ol' proposal for interactions ;)
https://github.com/GoodBoyDigital/pixi.js/issues/241

**Comment by Inateno** [comment]
Yeah, I saw this ticket before nice job :+1: 

I'm using almost all the time mouseWheel and this could be confusing to add it inside PIXI because a mouseWheel event isn't directly interacting with rendered objects (it's more like a key input), but maybe a handler binded on the canvas and user catch events ? It's more about avoiding add dom events on canvas while PIXI is doing it already.

About pointerdown/up, it for two reason, first doing sprite.onmousemove = sprite.ontouchmove = function() is boring (maybe this has change in V3 didn't check this yet..) and also I'm not sure that this is compatible on all ms device and soon all devices (because this is the new standard, why wait incompatibilities ?).

**Comment by tobireif** [comment]
(Some related discussion regarding "pointerup":
https://twitter.com/TobiReif/status/641559989857947649 )

**Comment by englercj** [comment]
Related to #2071

**Comment by themoonrat** [comment]
@englercj - Could be closed after https://github.com/pixijs/pixi.js/pull/2997 was merged? Still no mousewheel support, but if it's not planned..

**Comment by englercj** [comment]
I'd rather open a new issue related to the `wheel` event.
