### ISSUE TITLE
graphics lineStyle thickness bug

### ISSUE THREAD

**Issue by NikkiKoole** [pixijs/pixi.js#1620]
version : "3.0.0-rc4"

When I set the lineStyle smaller then 1 and then do a drawRect the outline isn't aligned properly to the shape fill:
![screen shot 2015-03-31 at 12 25 56 pm](https://cloud.githubusercontent.com/assets/453055/6917011/1b72840c-d7a1-11e4-9e59-310403e90689.png)
```
var thing = new PIXI.Graphics();
thing.lineStyle(.1, 0x000000);
thing.beginFill(0xffffff);
thing.drawRect(0,0,20,20);
stage.addChild(thing);
```

here's a fiddle showing the issue:
http://jsfiddle.net/332gdcna/8/

I've played around with that fiddle myself:
and separated the lineStyle and beginFill to different Graphics objects.
It looks like the fill part should be drawn at 0.5, 0.5 then the fill and outline parts do align properly.
http://jsfiddle.net/332gdcna/9/

**Comment by adelciotto** [comment]
Just thought I'd this bug only appears when using the WebGL renderer.

**Comment by NikkiKoole** [comment]
I've fiddled around a little more: http://jsfiddle.net/332gdcna/12/

actually it seems the fill part in the webgl is done properly, it looks like all the lines should be positioned += -0.5, -0.5.

**Comment by adelciotto** [comment]
ahhh ok, I get ya. so would simply adding to that if statement like so:

```javascript
if (graphicsData.lineWidth % 2 && graphicsData.lineWidth >= 1)
{
    ....
}
```

be appropriate ? Because % 2 with any floating point number would never return 0 anyway.

**Comment by NikkiKoole** [comment]
I've tried that, and also a third check to see if the lineWidth is an int to begin with:
```
if (graphicsData.lineWidth % 2 && graphicsData.lineWidth >= 1 && (graphics.lineWidth%1===0)) {...}
```
but I am not sure if the whole test should be there to begin with... ;) In my current project just commenting the whole lot out looks better ;)

**Comment by gaelduplessix** [comment]
I think this issue is related to #711

**Comment by englercj** [comment]
Just to confirm, does this issue still exist in the latest v3 release?

**Comment by gaelduplessix** [comment]
It probably does, since the condition is still present:
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/graphics/webgl/GraphicsRenderer.js#L583

**Comment by simonbw** [comment]
I still have this issue in version 3.0.6.

**Comment by dlindenkreuz** [comment]
+1 for v3.0.6

**Comment by hillaryan** [comment]
I'm having this issue as well in 3.0.7.

**Comment by Jacq** [comment]
Hit the bug today also in 3.0.6 :), it shows circle lines off and they don't contain the circle fill .
Cheers,

**Comment by chrispine** [comment]
I'm also having problems with this. I understand the desire was to align on pixels, but it's not adding 0.5 pixels on an line of odd-pixel thickness: it's add 0.5 *before scaling* (which could be hundreds of pixels), and it's doing it when it's not exactly an even integer thickness.

It was well-intentioned, but was a mistake. It also doesn't match Canvas renderer's behavior. Please just delete the offending code in `PIXI.WebGLGraphics.buildLine()`. *Please don't try to fix it!*

Just... let it go. :-)

**Comment by chrispine** [comment]
This is an opportunity for someone to fix two outstanding bugs (this one and https://github.com/pixijs/pixi.js/issues/711 ), and Do The Right Thing... simply by *deleting* 6 lines of code (and a comment, and a line of whitespace). :-)

**Comment by chrispine** [comment]
Also referenced here: http://www.html5gamedevs.com/topic/16521-possible-bug-in-phaser-v242/

**Comment by NikkiKoole** [comment]
ok I'll bite : https://github.com/pixijs/pixi.js/pull/2055

**Comment by englercj** [comment]
Looks like this was fixed a while ago.
