### ISSUE TITLE
Incorrect hitArea on some Android

### ISSUE THREAD

**Issue by ayamflow** [pixijs/pixi.js#1623]
This is basically the same as #1106 but on V3.

I'm drawing the hitArea of each object, as well as the stage, and they look OK but after a few scrolls the click is not recognized at the correct location. I'm testing with a `click` listener on stage, it works before scrolling but afterwards neither stage nor sprites emit events from the correct position (so either the click is emitted on the wrong element, or is not emitted at all).

Having this on Nexus 7 with Android 4.4.3, but not happening on a Nexus 4 with 5.0.2.
Will look deeper soon...

**Comment by ayamflow** [comment]
What I have found so far:
- Only happens on Android 4.4.3 (only device I have here with that is Nexus 7 - tested on Moto X, Nexus 4 and "old" Nexus 7 on 4.4.4, and iPhone 5 iOS8 and no problem)
- The touch events never trigger a hit though they have the correct coordinates
- The mouse events trigger a hit but the Y coordinate is offset by the scrollY of the page, so they don't trigger a hit after a few scroll (since the `event.clientY` is like 1532 but `innerHeight` is 800).

When I test, scrolling a bit then touching one of my sprite trigger these events, in the given order:
on working device: `touchstart`, `touchend` trigger with correct coordinates, click event is properly triggered.
on failing device: `touchstart`, `touchend`, with correct coordinates, then `mousemove`, `mousedown` with wrong Y coordinates, click event is not triggered.

Can't test on any 4.4.3 and don't want to spend too much time on that, so I'm going (again) with some monkey-patching:

```js
var PIXI = require('pixi.js');
PIXI.interactive.InteractionManager.prototype.mapPositionToPoint = function ( point, x, y )
{
    var rect = this.interactionDOMElement.getBoundingClientRect();
    if (y > window.innerHeight) y -= window.pageYOffset;

    point.x = ( ( x - rect.left ) * (this.interactionDOMElement.width  / rect.width  ) ) / this.resolution;
    point.y = ( ( y - rect.top  ) * (this.interactionDOMElement.height / rect.height ) ) / this.resolution;
};

```
(I'm using some cached values for innerHeight & pageYOffset of course).

**Comment by GoodBoyDigital** [comment]
I'm hoping Android browser has gone ahead fixed this one!
