### ISSUE TITLE
cacheAsBitmap and interactive issue

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#1629]
Hello,

When you set cacheAsBitmap to true, the interactive elements inside the cached displayobject are misplaced.

See the fiddle : http://jsfiddle.net/aazL3ytp/

comment or uncomment the last line (cacheAsBitmap =true) and try to click on the text.

It looks like the hit area is located in 0;0 or not using the scale of the container, I'm not sure.

Regards.

**Comment by GoodBoyDigital** [comment]
interesting stuff! I had not really considered interactive elements within a cached object! This one will take a little thinking as we would want to avoid unnecessarily updating the transform to get the correct cords for interactive elements.

Until theres a fix in place I would recommend not using cacheAsBitmap for interactive content at the mo

**Comment by JiDW** [comment]
Ok, thanks ! I guess I will have to find a temporary fix then, I can't really stop using cacheAsBitmap for my game, it's too much a performance enhancer.

**Comment by GoodBoyDigital** [comment]
haha, it is really handy for performance!

add this line ```doc.containerUpdateTransform();``` and it will force a transform update without rendering

http://jsfiddle.net/qykabs0L/

cheers!

**Comment by JiDW** [comment]
Thanks Mat !!

**Comment by GoodBoyDigital** [comment]
closing for now as this is a bit of an edge case and the above workaround should be enough for most! Let me know if I'm wrong :)
