### ISSUE TITLE
isometric land tile transformation

### ISSUE THREAD

**Issue by pinguini** [pixijs/pixi.js#1684]
i did start write an Isometric game on pixijs. 
and  have some issue with transformation tiles.
here some places of my map:
![map_z](https://cloud.githubusercontent.com/assets/5128663/7224868/3020fdb0-e751-11e4-9c9d-30dd0dbd44b7.png)

which instruments i need use to transform tiles? 
thanks

**Comment by englercj** [comment]
#1365?

**Comment by GoodBoyDigital** [comment]
Skews and Planes should offer a solution here! 👍
