### ISSUE TITLE
DisplayObject  getLocalBounds() & getBounds()

### ISSUE THREAD

**Issue by aholla** [pixijs/pixi.js#1698]
Once getLocalBounds is called, getBounds returns also returns the localBounds.

e.g.

```
// sprite nested within a container that is 200 px width and height and 100px in from x and y

getBounds() // return Rectangle( 100, 100,  200, 200 );
getLocalBounds() // return Rectangle( 0, 0,  200, 200 );

// now call getBounds again an it will be local.
getBounds() // return Rectangle( 0, 0,  200, 200 );

**Comment by englercj** [comment]
@GoodBoyDigital Told you this would come up :P

**Comment by GoodBoyDigital** [comment]
haha! smarty pants :P

Will look into this tomorrow :+1:

**Comment by englercj** [comment]
Ping @GoodBoyDigital, I know you're busy. I'm just going to keep pinging you until this is fixed :)

**Comment by staff0rd** [comment]
I used the above linked phaser fix [like this](https://github.com/staff0rd/pixi.js/commit/a5dc2d95f4aa0eaf55f177eaea16540c236e5b86#diff-487f466a18e6a27763221aad599ab7a6R484).  Dunno why it fixes it (hence no PR), but it does.

**Comment by ivanpopelyshev** [comment]
@staff0rd Look at #2654

**Comment by GoodBoyDigital** [comment]
Fixed :) 👍
