### ISSUE TITLE
scaleMode not honored when second, different, fromImage invocation is issued.

### ISSUE THREAD

**Issue by retrogradeorbit** [pixijs/pixi.js#1724]
Say you include a texture from a url and make it gl.NEAREST like this:

```
PIXI.Texture.fromImage("bunny.png", true, PIXI.scaleModes.NEAREST);
```

then pixi caches the texture against only the url, so further calls importing the same image from the same url but with a different scaleMode will be wrong:

```
PIXI.Texture.fromImage("bunny.png", true, PIXI.scaleModes.LINEAR);
// this texture is still in nearest mode
```

Whichever scaleMode the initial import is done with will last forever.

What's needed is either to cache them keyed against url *and* scaleMode, or to have some way of changing the scaleMode after the texture has been loaded.

I have searched for the latter and tried everything to no avail. If there is a way to regenerate a scaleMode on an existing texture, I would be most interested (tried unoloadFromGPU, destroy, dirty etc and failed....)

**Comment by englercj** [comment]
This happens because of how `.fromImage()` works. It caches textures it creates based on url, so everytime you pass the same url you get the same `Texture` object back.

Instead, create the image directly:

```js
var tx1 = new PIXI.Texture(PIXI.utils.BaseTextureCache['bunny.png'], true, PIXI.SCALE_MODES.NEAREST),
    tx2 = new PIXI.Texture(PIXI.utils.BaseTextureCache['bunny.png'], true, PIXI.SCALE_MODES.LINEAR);
```

That way you get two separate textures that share a base texture.

Also, it seems like you are using the v2 way of accessing the scale modes constants, above I used the v3 way of doing it. I suggest you migrate because the v2 methods may not exist forever.

**Comment by NikkiKoole** [comment]
I once had this https://github.com/GoodBoyDigital/pixi.js/issues/620 issue. Its about how to manually decide the names things in your TextureCache end up with, so you could perhaps use it to make a "bunny.png_NEAREST" and "bunny.png_LINEAR"

**Comment by englercj** [comment]
Imo, the *best* solution is to stop using the convience methods. Just use the constructors, if you need more than "put in string, get out texture, I don't care at all how it is made" you should use the constructors.

**Comment by GoodBoyDigital** [comment]
Closing this as it seems resolved. Thanks all! :+1:

**Comment by retrogradeorbit** [comment]
This does not seem to be fixed in Pixi V3.0.7

http://jsfiddle.net/j1ujh69e/3/

The texture cache is still getting in the way.

Now, the setting of the second texture filtering mode changes the mode on the first texture.

**Comment by GoodBoyDigital** [comment]
Hi @retrogradeorbit ,

This is intended functionality. The fromImage uses the texture cache. which returns the same texture each time you use it. This allows for much faster performance as it keeps the number of textures required on the GPU much lower.

What you are trying to do seems very edge case and so the you will need to create your texture in a slightly different way:

```
var smooth = new PIXI.Texture(new PIXI.BaseTexture('imageURL', PIXI.SCALE_MODES.LINEAR))
var nearestTexture = new PIXI.Texture(new PIXI.BaseTexture('imageURL', PIXI.SCALE_MODES.NEAREST))
```
thanks

**Comment by retrogradeorbit** [comment]
I wouldn't want to remove the cache.

That approach you post doesn't work for me. The textures don't load at all and I just get a blank screen.

http://jsfiddle.net/j1ujh69e/4/ 

Yes, it is very edge case.

**Comment by englercj** [comment]
@retrogradeorbit , all good. @GoodBoyDigital just made a typo. `PIXI.BaseTexture` takes a "source" as its first parameter (so an `Image` or `Canvas` object):

```js
var img = new Image();
img.src = 'imageUrl';

var smooth = new PIXI.Texture(new PIXI.BaseTexture(img, PIXI.SCALE_MODES.LINEAR))
var nearestTexture = new PIXI.Texture(new PIXI.BaseTexture(img, PIXI.SCALE_MODES.NEAREST))
```
