### ISSUE TITLE
Backmasking?

### ISSUE THREAD

**Issue by Shadowstep33** [pixijs/pixi.js#1729]
Does pixi v3 provide any way to backmask? I know it now allows sprite masking. Also, this is just a question not an issue, not used to Githubs forums - couldn't find out how to label it as a question

**Comment by SharpleafCC** [comment]
I, too, would like this feature.
To clarify what backmasking is to those that might not know what it means:
The current masking limits what you can see to the boundaries of the mask. Backmasking is basically the opposite.
A backmask would instead be a window through the sprite, in the shape of the mask.

**Comment by englercj** [comment]
Is sprite masking not good enough for this? I feel like you can do this effect with a sprite mask...

#1639

**Comment by Shadowstep33** [comment]
If I have a sprite that is a spotlight, and this spotlight is supposed to shine on a dude I think I need backmasking. I use a black overlay in order to give the rest of the scene darkness (I know I can use filters for this, but bare with me). If I want that spotlight to actually just be transparency in the black overlay, as far as I understand, I need backmasking. When I mask in this way, the opposite effect is achieved (i.e. the spotlight becomes a black overlay and the rest of the scene appears as normal.

**Comment by englercj** [comment]
@Shadowstep33 Correct, if you use a normal vector (Graphics) mask that is what will happen. With sprite masking the same effect would be to draw a white circle, and leave the rest of the sprite blank and use that as the mask.

To get a spotlight effect what you would do is draw the entire mask white, but leave the spotlight location transparent. That would mask the transparent part and draw all the outter things, creating the effect you want.

Get what I am saying?

**Comment by GoodBoyDigital** [comment]
Sprite Mask will work a treat in this situation!

**Comment by SharpleafCC** [comment]
Has something changed in regards to backmasking? Or was this closed as a cleanup?

**Comment by GoodBoyDigital** [comment]
Hello! This has been closed as we are confident sprite masking can be used to achieve effects like back masking.

**Comment by SharpleafCC** [comment]
I understand that the proposed solution was to basically create a sprite as large as the thing I'm masking and leave only the spot I want "see through" transparent. However, what if I want the "hole" to move?

I mocked up an example if what I'm talking about here https://youtu.be/foCL4GpYpWQ
It was done in Photoshop. Basically, the dark overlay would be one sprite and the "spotlight" would be a feathered circle mask that hides the portion of the dark overlay, wherever it is.

This is possible?

Thanks!

**Comment by englercj** [comment]
If the mask is a canvas, you can redraw it whenever you want.

**Comment by SharpleafCC** [comment]
so, use an off-screen rendered canvas to redraw a mask with updated positions, make a sprite out of it, and then apply it as a mask to my other sprite?
That sounds "expensive". Is it not?

**Comment by englercj** [comment]
You already created a canvas, and made it a mask. Just redraw that canvas you already have.

**Comment by SharpleafCC** [comment]
I don't follow.... When did I create a canvas?

There's some sort of disconnect between what you're saying and my understanding of the situation :)

**Comment by englercj** [comment]
> I understand that the proposed solution was to basically create a sprite as large as the thing I'm masking and leave only the spot I want "see through" transparent. 

```js
var canvas = document.createElement('canvas');
var ctx = canvas.getContext('2d');
var spriteMask = new PIXI.Sprite(PIXI.Texture.fromCanvas(canvas));

myOtherSprite.mask = spriteMask;

// draw mask
// ....

// update texture
```

You can call the draw mask and update texture parts repeatedly, you don't create a new canvas/sprite everytime.

**Comment by SharpleafCC** [comment]
I gotcha. Cool thanks :)

It would be nice if there was something as simple as .mask, but I see how it can be done now.

Thanks!

**Comment by englercj** [comment]
> I understand that the proposed solution was to basically create a sprite as large as the thing I'm masking and leave only the spot I want "see through" transparent. 

```js
var canvas = document.createElement('canvas');
var ctx = canvas.getContext('2d');
var spriteMask = new PIXI.Sprite(PIXI.Texture.fromCanvas(canvas));

myOtherSprite.mask = spriteMask;

// do the following whenever the hole moves:

// draw mask
// ....

// update texture
spriteMask.texture.update();
```

You can call the draw mask and update texture parts repeatedly, you don't create a new canvas/sprite everytime the hole moves.
