### ISSUE TITLE
Non-retina texture shows artifacts at borders when in retina render modus [v3]

### ISSUE THREAD

**Issue by naranjamecanica** [pixijs/pixi.js#1732]
I'm making an animated tiled background, is it possible to get rid of the gaps between the tiles. It only happens if the animation is not rounded on whole pixels.

See a demo on:
http://jsbin.com/vavoluxewa/5/edit?js,output

**Comment by naranjamecanica** [comment]
Update: I also see the gap when rounding pixels, but the resolution is at 2x.

Scenario: 
The background tiles are at 1x resolution, but i want the rest of the interface rendered at 2x

See an updated demo with rounded values on:
http://jsbin.com/zetenacuti/2/edit?js,output

Toggle the resolution between 1 and 2, at 1x everything looks fine at 2x small artifacts/gaps appear around the tiles. 

With version 2.x of the lib the rendering is fine:
http://jsbin.com/zetenacuti/3/edit?js,output

**Comment by naranjamecanica** [comment]
I see now that it's not a gap, but artifacts/noise at the border of the sprite texture. Is this because it's getting blown up? 

Can you give me a clue where in the source I can poke around to see if I can fix is, and do you know why this is not happening in v2?

**Comment by naranjamecanica** [comment]
I see that the last demo was not working, see:
http://jsbin.com/qucubaheka/1/edit?js,output

I've drawn a red box around the artefacts.

**Comment by naranjamecanica** [comment]
Ok I've found out that it's because the texture gl.TEXTURE_WRAP_S,  and  gl.TEXTURE_WRAP_T are set to repeat in combination with LINEAR filtering.

@englercj  Is this expected behaviour?  Then we can close this...

**Comment by englercj** [comment]
This can happen often when the texture is non-PoT. Is your texture a power of two in size?

Otherwise you will likely get rounding issues like this.

**Comment by naranjamecanica** [comment]
Yes it is, look at: http://studiokloek.nl/tmp/html-background/tile-1-1.jpg

Knowing nothing about WebGL it seams logical that filtering it with linear and making it repeat, gives an overlapping pixel on the edges because those get mixed in the filtering.

Is there an reason to make it REPEAT and not CLAMP?

**Comment by englercj** [comment]
It uses repeat for non-power-of-two textures, PoT tetures use CLAMP if I am not mistaking...

**Comment by naranjamecanica** [comment]
I don't think so, when i read it,  note the ! checking for a FALSE condition.
    
    if (!texture.isPowerOfTwo)
    {
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    }
    else
    {
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.REPEAT);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.REPEAT);
    }

**Comment by englercj** [comment]
Hmm, @GoodBoyDigital any ideas?

**Comment by naranjamecanica** [comment]
Could it be something to do with:
http://www.sjbaker.org/steve/omniv/tiling_textures.html

**Comment by englercj** [comment]
Is this still an issue in the latest `dev` branch?

**Comment by naranjamecanica** [comment]
Look like it! 👍 

v3.0.11 - http://jsbin.com/logiwucoxi/1/edit?html,js,console,output
v4.0.2 - http://jsbin.com/dezatutazu/1/edit?html,js,console,output

**Comment by englercj** [comment]
Sweet!
