### ISSUE TITLE
delete from texture cache should be in texture

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#1741]
Right now only destroying a base texture will remove it from the cache:

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/textures/BaseTexture.js#L319

But that can cause problems if you destroy a texture, then try to create one again with `.fromImage()` you will get a broken texture back out of the cache.

Texture should remove itself from the TextureCache and not rely on BaseTexture to do it.

**Comment by GoodBoyDigital** [comment]
added a little fix..
