### ISSUE TITLE
Text padding does increase text height, but not width

### ISSUE THREAD

**Issue by dcodeIO** [pixijs/pixi.js#1743]
I am not sure if I am doing something wrong, but Text#height includes the padding, while Text#width does not. (master branch)

**Comment by englercj** [comment]
This is true, because it only applies padding to the height. It is meant as a way to work around slightly off font height calculations.

Is there a reason you need it?

**Comment by dcodeIO** [comment]
No specific reason, just trying out pixi atm and noticed it. Really like it so far!

**Comment by englercj** [comment]
Awesome! The name is pretty ambiguous, so sorry about that.

I've updated the doc comments to be more clear about what will happen.

**Comment by AleBles** [comment]
I'd like to see this re-opened because I have some text cut off in the width on an Italic font

![pixi_text_cutoff](https://cloud.githubusercontent.com/assets/3883477/8672834/3df903fa-2a32-11e5-9759-2ed9883dea05.png)

```typescript
new PIXI.Text("Remove the 2"), <PIXI.TextStyle> {
            font: 'bold italic 14px "Montserrat"',
            fill:'black',
            align: "center"
        });
```

**Comment by dcodeIO** [comment]
What if text padding would become a CSS-like feature instead of just a workaround? Should still fix such issues and also make the API easier to understand.

**Comment by AleBles** [comment]
So like setting a single value will increase padding on all sides and supplying a array with 4 numeric values for top, right, down, left will change those?

**Comment by GoodBoyDigital** [comment]
Good shout! 👍

**Comment by GoodBoyDigital** [comment]
Padding now affects width also 👍
