### ISSUE TITLE
hitArea on masked DisplayObjectContainer not affecting children

### ISSUE THREAD

**Issue by plong0** [pixijs/pixi.js#1746]
I'm working on a scrollable panel where I've got a `var scrollable.area = new PIXI.DisplayObjectContainer();`  I've applied a simple rectangular mask to it `scrollable.area.mask = myMask;`
scrollable.area contains a list of interactive buttonMode sprites as its children.

The mask works great for rendering, but I am having troubles setting the hitArea correctly.  So even though the child sprites are outside of the masked area, mouse events are still registering on them.

I thought that setting `scrollable.area.hitArea = new PIXI.rectangle(0, 0, maskWidth, maskHeight);` would do the trick... but no dice.  The child sprites are still capturing the events.

**Comment by SirKnightDragoon** [comment]
Same bug for me... we cant interact with elements behind the mask. And for me, I can click through the mask...

**Comment by ivanpopelyshev** [comment]
that's not how hitArea works. Currently you cant create mask for interactionManager at all. You only can specify hitAreas for interactive objects that will receive events. There's no bubbling or proxying or other stuff. There's no clipping. We need to rewrite interactionManager to fix all those problems.

**Comment by andrevenancio** [comment]
I didnt want to open yet another hitArea Issue.
hitArea fails to get updated on custom classes extending PIXI.Sprite. even with the interactive flag on I can still access objects behind the sprite. It works well if I manually update the hitArea to be the same size of the children inside my sprite.

**Comment by GoodBoyDigital** [comment]
This issue has been addressed in v4 :+1:
