### ISSUE TITLE
Graphics mask and cacheAsBitmap

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#1750]
Hello,

When you create a container with a mask from a graphics you just created, setting cacheAsBitmap to true will render your container empty because the graphics isn't ready yet and need one render before it can works.

Besides correcting this inside PIXI, do you know a method to call before setting cacheAsbitmap to true to make it works ? Something like updateText() for a PIXI.Text.

I tried renderer.plugins.graphics.updateGraphics(myMask,renderer.gl); without success.

Thanks !

**Comment by JiDW** [comment]
By bad, I was doing something stupid. I was caching as a bitmap a masked container.

However there is still a bug when you do that, as it doesn't cache the correct bitmap (the mask is misplaced) but in my case, it wasn't even the correct way to do what I needed. I added a container masking the cached container and it works fine now.

See this video showing the bug but please ignore the intended result because it would not have work anyway even without this bug. It should have generated a bitmap of the masked container in is initial state.

http://gfycat.com/EmbellishedAbleKoodoo

**Comment by GoodBoyDigital** [comment]
nailed in v4 I believe 👍
