### ISSUE TITLE
Question: Prototype style

### ISSUE THREAD

**Issue by drkibitz** [pixijs/pixi.js#1754]
I was just wandering what people thought of using `Object.assign` to minimize code duplication with things like `Constructor.prototype` through out the code base.

I know minification is the least of the concerns for this library, but since we have an `Object.assign` polyfill available it can drastically reduce the final minimized size.
For example.

Current:

```js
// ...

/** docs */
DisplayObject.prototype.getBounds = function (matrix) // jshint unused:false
{
   // ... body
};

/** docs */
DisplayObject.prototype.getLocalBounds = function ()
{
   // ... body
};

// ...
```

Suggested:

```js
Object.assign(DisplayObject.prototype, /** @lends PIXI.DisplayObject# {
    // ...

    /** docs */
    getBounds: function (matrix) // jshint unused:false
    {
       // ... body
    },

    /** docs */
    getLocalBounds: function ()
    {
       // ... body
    }

    // ...
});
```

Thoughts?

**Comment by drkibitz** [comment]
3rd option that isn't necessarily great style, and is very specific to minification:

```js
/** @alias PIXI.DisplayObject# */
var DisplayObjectPrototype = DisplayObject.prototype;

// ...

/** docs */
DisplayObjectPrototype.getBounds = function (matrix) // jshint unused:false
{
    // ... body
};

/** docs */
DisplayObjectPrototype.getLocalBounds = function ()
{
   // ... body
};

// ...
```

**Comment by englercj** [comment]
I hate the second one, but using Object.assign is something that I am certainly open to. I think it is much cleaner!

What does the polyfill look like?

**Comment by drkibitz** [comment]
PIXI currently includes:

https://github.com/sindresorhus/object-assign/blob/master/index.js

---

Just to clarify the point in minification... UglifyJS does not mangle anything that is a property access, this includes the many many instances of `prototype` throughout pixi.js. I'm not certain how much a slight style switch would save, but ultimately I wanted to gauge the waters before any investigation.

**Comment by englercj** [comment]
I consider the minification improvement a positive sideeffect of us having potentially cleaner source code using `Object.assign()`. I'm not married to the current implementation, and I'm not passionate about the switch either.

Would be interested to see what the improvement turns out to be and what other think about the change.

**Comment by mattdesl** [comment]
TBH I've never been a fan of `Blah.prototype.foo`. It has caused bugs in the past (even in Pixi) where `Blah` is referring to the wrong class.

**Comment by GoodBoyDigital** [comment]
Object.assign <- i'm in for that! Great idea @drkibitz :+1:

**Comment by stbaer** [comment]
I started rewriting a couple of files using Object.assign, but the minified file size was actually growing instead of shrinking, so I reverted the changes.

**Comment by GoodBoyDigital** [comment]
Closing this for now. If someone would like to go through and refactor to the suggested setup it would be a welcome PR (i know its a huge ask, so not expecting it!)
