### ISSUE TITLE
Anonymous hole created inside rectangle

### ISSUE THREAD

**Issue by Priyank30** [pixijs/pixi.js#1755]
I want to add holes inside graphics object and I have tried several ways but still not getting how to do it. Meanwhile I found some strange behaviors and could not able to figure out.

            var renderer = PIXI.autoDetectRenderer(1200, 800);
			document.body.appendChild(renderer.view);
			
			// create the root of the scene graph
			var stage = new PIXI.Container();
			
			var graphicsObject1 = new PIXI.Graphics();
			graphicsObject1.beginFill(0X60b044);	
			graphicsObject1.drawRect(100, 100, 600, 600);  //Green rectangle
			graphicsObject1.endFill();			
			stage.addChild(graphicsObject1);
			
			//An overlapping graphics object with hole.
			var graphicsObject2 = new PIXI.Graphics();
			graphicsObject2.beginFill(0XF41A1A);		
			
			graphicsObject2.moveTo(0, 0); //Red rectangle
			graphicsObject2.lineTo(0, 600);
			graphicsObject2.lineTo(600, 600);			
			graphicsObject2.lineTo(600, 0);
			graphicsObject2.lineTo(0, 0);
			
            //Creates hole in object (Don't know how !!!)		
     		graphicsObject2.arc(120, 100, 25, 0, 2 * Math.PI);
			
			graphicsObject2.endFill();
			
			graphicsObject2.position.x = 80;
			graphicsObject2.position.y = 5;			
						
			stage.addChild(graphicsObject2);			
			
			renderer.render(stage);

Above is a simple test code which gives output as below:
![issue](https://cloud.githubusercontent.com/assets/2055200/7491827/3585916e-f40b-11e4-8f2f-488ae6e7fa2c.png)

As shown in output an arc creates a hole inside red rectangle but when I draw another counterclockwise rectangle inside red rectangle it fills out with black color but it suppose to create a hole. To proper simulate hole test I have created another green rectangle behind red rectangle.

**Comment by Priyank30** [comment]
@englercj 
I want to create a hole inside any 2d shape but wondering  how to do that. I have referred [1639](https://github.com/GoodBoyDigital/pixi.js/issues/1639) but not getting idea how to deal with 2d shapes. 
I have explained my situation in detail at [stackoverflow](http://stackoverflow.com/questions/30120352/pixijs-add-hole-into-graphics-object). Please help me out to move forward. I'm stuck at this point.

**Comment by englercj** [comment]
What are you stuck on about using a sprite mask? You can draw the 2d shape you want (a rectangle), then draw to a canvas whatever mask you want, use that canvas in a sprite, then use that sprite as a mask of your shape.

**Comment by englercj** [comment]
I also want to add native support for drawing a polygon with holes in an upcoming release. Merging #1772 helps a lot.

**Comment by Priyank30** [comment]
Its a good news about native support. 
Now the problem is  if I apply the scale factor on the Container of myGraphicsObject then mask area seems to be blurred. If I correct its just because drawn mask on canvas is without scale and its starched when we apply the mask from its generated sprite.
I tried to apply scale on canvas but then everything is changed. It's quite tricky to maintain mask on the original position.

**Comment by englercj** [comment]
Make the texture you are creating use NEAREST scaling instead of the default LINEAR and see if that helps.

**Comment by Priyank30** [comment]
@englercj 
Thanks for your help but I have made a fix for that using [earcut](https://github.com/mapbox/earcut) so no more masking and sprite to create holes.

```javascript

Graphics outer = Graphics.create();		
outer.beginFill(color);
//draw outer shape
outer.endFill();		
    
DisplayObjectContainer holes = DisplayObjectContainer.create();		
Graphics hole1= Graphics.create();
hole1.beginFill();
//create hole1
hole1.endFill();

Graphics hole2 = Graphics.create();
hole2.beginFill();
//create hole2
hole2.endFill();

//Add multiple holes to container object.
holes.add(hole1);     
holes.add(hole2);    

//DrawPolygon function returns a graphics objects containing holes
Graphics region = drawPolygon (outer, holes);

//And render region.

function drawPolygon (Graphics outer, DisplayObjectContainer holes) {
	var holeIndices = new Array();
    var lastHoleIndex = outer.graphicsData[0].shape.points.length/2;
    holeIndices.push(lastHoleIndex);
    
    var inputData = outer.graphicsData[0].shape.points; 
    for(var i = 0; i < holes.children.length; i++) {                
        if(i > 0) {
          holeIndices.push(lastHoleIndex += holes.children[i-1].graphicsData[0].shape.points.length/2);                                                        
        }
        inputData = inputData.concat(holes.children[i].graphicsData[0].shape.points);
    }
    
	//Use of earcut library
    var result = earcut(inputData, holeIndices);
		
    var triangles = [];
    var dim = 2;
    for (var i = 0; i < result.length; i++) {
        var index = result[i];
        triangles.push([inputData[index * dim], inputData[index * dim + 1]]);
    }
    
    var graphics = new PIXI.Graphics();
    graphics.beginFill(outer.graphicsData[0].fillColor);        
    for (var i = 0; triangles && i < triangles.length; i += 3) {
        drawPoly([triangles.slice(i, i + 3)]);
    }
    graphics.endFill();
  
    function drawPoly(rings) {
        for (var k = 0; k < rings.length; k++) {
            var points = rings[k];
            for (var i = 0; i < points.length; i++) {
                    var x = points[i][0],
                    y = points[i][1];
                    
                if (i === 0) graphics.moveTo(x, y);
                else graphics.lineTo(x, y);
            }
        }
    }
            
	return graphics;
}
```

**Comment by englercj** [comment]
Nice! Hopefully I can get hole support into Graphics for you when we do v3.1.0

**Comment by GoodBoyDigital** [comment]
holes added in dev branch! 👍
