### ISSUE TITLE
BlurFilter throwing an error when adding

### ISSUE THREAD

**Issue by Shadowstep33** [pixijs/pixi.js#1761]
I receive this error when I redraw a sprite onto a Container with blur on it:

Uncaught TypeError: Cannot read property 'activate' of null

I've noticed this bug includes a redrawSprite custom function call, which adds the sprite to container. The bug only happens when I add a sprite to the container with a blur on it.

**Comment by englercj** [comment]
Does this happen with 3.0.3? We reverted to the old Blur method in this release.

**Comment by Shadowstep33** [comment]
You know, I think I'm using 3.0.2 Let me try the newest build and I'll see what's up

**Comment by Shadowstep33** [comment]
Yes, it still happens using 3.0.3

**Comment by englercj** [comment]
Ok, will look into!

**Comment by englercj** [comment]
Just realized I'm not sure how to reproduce this! :P

Do you have a simple repro case? I'm not sure what "redrawSprite" is?

**Comment by GoodBoyDigital** [comment]
closing this for now, let me know if it is still an issue. :+1:
