### ISSUE TITLE
InteractiveManager - event propagation - bug or feature?

### ISSUE THREAD

**Issue by LuQano** [pixijs/pixi.js#1765]
https://jsfiddle.net/0Ljff0go/

Hi,
In one of your commits ("fixed interaction issue" from 4th of May, https://github.com/GoodBoyDigital/pixi.js/commit/682ae472889c1855c97d8252cd5dac550a77f99a) there were some changes that made clickable objects interraction diffrent. For example - when we create two buttons, and make them partially overlap with eachother, clicking in the place where one button is on top of the other activates both of them.
In the versions prior to the one mentioned when you clicked in the same spot, only the button on top was activated.  

Was this done intentionally or is this a bug?

**Comment by englercj** [comment]
@GoodBoyDigital I think this was on purpose, but seems like odd behavior.

**Comment by GoodBoyDigital** [comment]
thanks for sharing. Makes sense to me.. I will revert the fix as it seems it is the lesser of two evils! 
I initaly did this to solve another issue..

**Comment by GoodBoyDigital** [comment]
Finally got round to patching this issue in the dev branch! Works the same as the DOM now :+1:
