### ISSUE TITLE
WebGLRenderer: Only 4 blend modes implemented

### ISSUE THREAD

**Issue by saschagehlich** [pixijs/pixi.js#1775]
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/webgl/WebGLRenderer.js#L499:

```js
this.blendModes[CONST.BLEND_MODES.NORMAL]        = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.ADD]           = [gl.SRC_ALPHA, gl.DST_ALPHA];
this.blendModes[CONST.BLEND_MODES.MULTIPLY]      = [gl.DST_COLOR, gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.SCREEN]        = [gl.SRC_ALPHA, gl.ONE];
this.blendModes[CONST.BLEND_MODES.OVERLAY]       = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.DARKEN]        = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.LIGHTEN]       = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.COLOR_DODGE]   = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.COLOR_BURN]    = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.HARD_LIGHT]    = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.SOFT_LIGHT]    = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.DIFFERENCE]    = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.EXCLUSION]     = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.HUE]           = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.SATURATION]    = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.COLOR]         = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
this.blendModes[CONST.BLEND_MODES.LUMINOSITY]    = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];
```

Not all of these blend modes can be implemented using `glBlendFunc` only. What is your plan for this? Render to a FBO and draw the texture using a fragment shader that implements all these blend modes?

**Comment by englercj** [comment]
I don't think we have a plan for it unfortunately, but yes rendering to an FYI and using a shader to implement the different blend modes is something we have thought about.

**Comment by GoodBoyDigital** [comment]
Yes as @englercj this is a lot trickier than it seems and theres know way of doing this quickly. The main reason is that you not only do you need access to the pixels of the texture but also of the pixels of the surface you are drawing too. To get that access we would need to draw the whole scene to a framebuffer to get access to the them. We have got this working in the past but the performance was not great. This should be easier to do once WebGL 2 is ready...

**Comment by weepy** [comment]
I'm looking for some very cheap Wazzy effects. I was hoping to be able to do something like EXCLUSION, but I can see from this it's not really supported. I was wondering if it was possible to hack in some alternatives : 

```
E.g.
this.blendModes[CONST.BLEND_MODES.BLA]    = [gl.ZERO,       gl.ONE_MINUS_SRC_ALPHA];

**Comment by GoodBoyDigital** [comment]
hey @weepy. hacking in alternatives like the above is all cool! more advanced blendmodes are not currently supported. but we are working on it. :+1:

**Comment by weepy** [comment]
How will you try to get it to work given your previous reply ? Will it require Webgl 2?

**Comment by GoodBoyDigital** [comment]
WebGL 2 would be the best route - it can also be done using readPixels and an extra framebuffer. The last two methods would incur a heavy performance hit though when they are used.
