### ISSUE TITLE
Rendering issue with Firefox  39.0a2

### ISSUE THREAD

**Issue by kittykatattack** [pixijs/pixi.js#1776]
It seems like Firefox 39.0a2 produces a fixed sized rendering window no matter what `width` or `height` is specified.
```
var renderer = PIXI.autoDetectRenderer(256, 256, {antialiasing: false, transparent: false, resolution: 1});
document.body.appendChild(renderer.view);
```
![f02005](https://cloud.githubusercontent.com/assets/2936104/7556905/d0c0570a-f752-11e4-896e-fa41591df82b.jpg)

**Comment by englercj** [comment]
Is this a pixi bug, or an issue in Firefox?

Does this happen is native canvas? Did you happen to track down why this is happening in FF but not elsewhere?

**Comment by GoodBoyDigital** [comment]
Closing for now as seems to have gone quiet. :+1:
