### ISSUE TITLE
Memory leak when creating sprites w/o a texture

### ISSUE THREAD

**Issue by merixstudio** [pixijs/pixi.js#1779]
When creating a sprite without a texture:
```javascript
var sprite = new PIXI.Sprite();
```
The `PIXI.Texture.emptyTexture` is used, which is great, but `PIXI.Texture.emptyTexture.baseTexture.hasLoaded` is set to `false`, which means that the newly created sprite will try to subscribe for a texture loaded event:
```javascript
PIXI.Sprite = function(texture)
{
    ...
    this.texture = texture || PIXI.Texture.emptyTexture;

    ...   

    if(this.texture.baseTexture.hasLoaded)
    {
        this.onTextureUpdate();
    }
    else
    {
        // Here PIXI.Texture.emptyTexture accumulates listeners forever.
        this.texture.on( 'update', this.onTextureUpdate.bind(this) );
    }
};
```
Seen in v2.2.9.

**Comment by englercj** [comment]
This exists in v3 as well, nice catch!

**Comment by GoodBoyDigital** [comment]
this has been addressed in v4 👍
