### ISSUE TITLE
Mousedown triggers a single mousemove?

### ISSUE THREAD

**Issue by Shadowstep33** [pixijs/pixi.js#1780]
Is this intended behavior? I am trying to prevent a click from occurring when the user is moving their mouse (i.e. user drags map and doesnt want to click on a game object). Here is an example:

http://jsfiddle.net/q6Lxxexu/

You'll notice that stage.lastDelta alerts 1 when you do a click.

**Comment by georgiee** [comment]
This bugged me too.
I just implemented a local patch on top of PIXI to observe if it's behaving correctly.

This fixes your testcase and works like a charm in my current project where I have to drag a TilingSprite all the time.
http://jsfiddle.net/georgie/q6Lxxexu/2/

@englercj Do you see any problems with my full stop in processTouchEnd & processMouseUp
I'm feeling a little uncomfortable creating a PR without knowing better the rest of the interaction system.

```
  var original_processTouchEnd = PIXI.interaction.InteractionManager.prototype.processTouchEnd;
  var original_processMouseUp = PIXI.interaction.InteractionManager.prototype.processMouseUp;

  PIXI.interaction.InteractionManager.prototype.processTouchEnd = function ( displayObject, hit )
  {
      if(!displayObject._touchDown) {
        //full stop, this object was not touched before
        return;
      }

      //everything is fine call the real handler;
      original_processTouchEnd.apply(this, arguments);
  };

  PIXI.interaction.InteractionManager.prototype.processMouseUp = function ( displayObject, hit )
  {
      var e = this.mouse.originalEvent;

      var isRightButton = e.button === 2 || e.which === 3;
      var isDown =  isRightButton ? '_isRightDown' : '_isLeftDown';
      
      if(!displayObject[ isDown ]) {
        //full stop, this object had no mouse down before
        return;
      }

      //everything is fine call the real handler;
      original_processMouseUp.apply(this, arguments);
  };
```

**Comment by georgiee** [comment]
Btw, this is my related ticket: https://github.com/GoodBoyDigital/pixi.js/issues/1763. See my second post.

**Comment by endel** [comment]
@Shadowstep33 actually your jsfiddle now alerts `0`. Should this issue be closed?

**Comment by GoodBoyDigital** [comment]
nailed in v4 I believe 👍
