### ISSUE TITLE
Can't load Atlas in PIXI 3.0

### ISSUE THREAD

**Issue by jagi** [pixijs/pixi.js#1782]
Hi, I have problem with using PIXI 3.0 and spritesheets. My application on PIXI 2.0 worked well but after updating to 3.0 spritesheets does not load properly. I'm developing application for Tizen device. It says:

```
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/sit1
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/sit2
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/sit3
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/sit4
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/sit5
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/sit6
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/sit7
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run1
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run2
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run3
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run4
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run5
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run6
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run7
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run8
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run9
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run10
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run11
Failed to load resource: Error opening file: No such file or directory file:///opt/usr/apps/1odqznnIyl/res/wgt/run12
```

As you can see it tries to load sprite from the file named as a frame instead of a spritesheet. I also tried running it locally with Python simple http server and I get different error.

```
Uncaught TypeError: Cannot read property '_uvs' of undefined
```

Does something changed regarding spritesheets/atlases?

**Comment by englercj** [comment]
Lots of things changed with everything. If you are on the latest version (3.0.3) and this is happening, please provide a minimal reproduce case so we can investigate!

Thanks!

**Comment by wojciak** [comment]
Xhr won't work properly with the file:// protocol, you need to go over http:// or https:// (start a web server instead of launching from /opt/usr/apps...

**Comment by jagi** [comment]
It's not the problem with the file protocol. It's Tizen OS. Loading other files work properly. The only problem are spritesheets. I will prepare reproduction.

**Comment by naso** [comment]
I am getting the same issue. Wondering if I am implementing it the right way:

```javascript
loader = PIXI.loader.add(url)
loader.load(function(loader, result) {
   mc = new PIXI.extras.MovieClip([result[url].texture])
   @stage.addChild(mc)
})
```

**Comment by englercj** [comment]
> but I guess the MovieClip class expects a json file with the spritesheet details, right?

No it expects an array of texture objects.

If you load a spritesheet in the loader the resulting resource object will have a `textures` property that are all the frames loaded from that sheet, keyed like they were in the json file. (if you use json hash it is an object, if you use json array it is an array).

**Comment by naso** [comment]
Yeah, but in my case I want to load separately each frame (0.png, 1.png, 2.png) and then I was expecting to use it as MovieClip.

Similar to what's happening on the example given at https://pixijs.github.io/docs/PIXI.extras.MovieClip.html.

**Comment by englercj** [comment]
That's fine, you can load whatever you want. MovieClip doesn't care where it came from or what the textures are, it just takes in an array of textures and cycles through them.

**Comment by GoodBoyDigital** [comment]
closing for now, let me know if this is still a thing! ta!
