### ISSUE TITLE
TilingSprite incorrect repeat

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#1787]
Hi,

I have this bug since the new tilingsprite update, but I thought that it was on my side so I didn't report it sooner. 

Problem is I do not find where my error is. I made a test case here : http://www.celsius-heroes.com/SandboxPixi/bugPixi/testTiling/index.html

It looks like the repeated texture is not correctly positioned and is repeated always at the same y.
It may be on my side. This is an old code and I'm having a hard time trying to read it with a fresh eye.

**Comment by JiDW** [comment]
Just tested it with https://github.com/GoodBoyDigital/pixi.js/pull/1807/files but it didn't fix it (I updated the test case with a fresh build), my tilingscale was 0 anyway.)

Anyone ?

**Comment by JiDW** [comment]
I have narrowed the test case to a single call to tilingsprite, it may be easier to debug : 

http://www.celsius-heroes.com/SandboxPixi/bugPixi/testTiling/index.html

The tilingsprite has a height of 16px but the shader display the complete texture once (61px)

**Comment by JiDW** [comment]
Fixed ! Credit due to @greewi 

Will make a PR today

**Comment by JiDW** [comment]
There is still a gap with not rounded numbers (scaled container, for example) as the shader can only deal with pixels but we do not see a solution for this one.

If you are clever a see a way to deal with it, please let us know.

**Comment by JiDW** [comment]
At last \o/

Credit to @greewi for the final fix

**Comment by GoodBoyDigital** [comment]
well done chaps! 👍
