### ISSUE TITLE
Light properties in normal map filter

### ISSUE THREAD

**Issue by jscottmiller** [pixijs/pixi.js#1809]
Hello!

If I'm reading things correctly, lighting sources in the normal map filter appear to be restricted to a single source, with fixed values for the light an ambient color. Is that right or am I missing something?

I'd like to build a scene with multiple lights, varying their color and ambient intensity. The light sources would all use the same normal map. My temptation is to extend the normal map filter to support this. However, is there a way to achieve this by composing filters? I could add a filter for each light source, but this seems wasteful and still doesn't let me apply colored lighting or vary the ambient versus positional weighting.

Fantasitic library, btw. Thanks for making it public!

Scott

**Comment by englercj** [comment]
If @GoodBoyDigital ever gets a few minutes he should be working on two new plugins:

1) pixi-flip: Adds some 3d projection antics to pixi
2) pixi-lighting: Adds a full dynamic lighting system

We have prototypes of both, just haven't had time to make them super awesome yet. I want to have them for v3.1 so I'll add this to that milestone.

**Comment by jscottmiller** [comment]
Awesome, thanks! Are those prototypes in a public branch? I'd love to take a look at the shader fragments.

**Comment by englercj** [comment]
Nah I don't think so, and the lighting is a bit more than just some frags. In fact the frags are pretty similar to the normalMap filter.

Hopefully we can share something soon.

**Comment by GoodBoyDigital** [comment]
closing as this filter will be moved to pixi-filters 👍
