### ISSUE TITLE
Bug in InteractionManager.prototype.processInteractive

### ISSUE THREAD

**Issue by am3000** [pixijs/pixi.js#1817]
I´m getting an error when having a mousedown on a button and on mousedown removing various displayObjects

Uncaught TypeError: Cannot read property 'visible' of undefined 

It seems pixi is still looping through nulled(?) displayObjects.
So I suggest changing "if( !displayObject.visible)" to "if(!displayObject || !displayObject.visible)" here: 

```javascript
InteractionManager.prototype.processInteractive = function (point, displayObject, func, hitTest, interactive )
{
    if(!displayObject || !displayObject.visible)
    {
        return false;
    }
```
Here´s a testcase:
http://jsfiddle.net/Lsfkj1ng/7/

**Comment by JiDW** [comment]
Happened to me this morning too !

**Comment by nt-pch** [comment]
I'm getting this error also in v3.0.6.

**Comment by neonwarge04** [comment]
I am also having this problem. I set my texts into interactive mode and it seems to me, this only happen on object with interactivity on.

I am using PIXI v3.0.5.

Here is the code that I used when I encountered this problem:

// Setup
StartScene.prototype.setup = function()
{
	this.mStage = new PIXI.Container();
	this.mStyle = 
	{
		  font   : 'bold italic 36px Arial'
		, fill   : '#F7EDCA'
		, stroke : '#4a1850'
		, strokeThickness : 5
	}
	
	this.mTitleStyle = 
	{
		  font   : 'bold italic 62px Arial'
		, fill   : '#F7EDCA'
		, stroke : '#4a1850'
		, strokeThickness : 5
	}
	
	var centerPos = {x : this.mScreenSize.width / 2.0, y : this.mScreenSize.height / 2.0};
	
	this.mSnakeTitle = new PIXI.Text("Snaked!" , this.mTitleStyle);
	this.mSnakeTitle.anchor.x = 0.5;
	this.mSnakeTitle.anchor.y = 0.5;
	this.mSnakeTitle.position.x = centerPos.x;
	this.mSnakeTitle.position.y = centerPos.y - 90.0;
	
	this.mEasyText = new PIXI.Text('Easy' , this.mStyle);
	this.mEasyText.anchor.x = 0.5;
	this.mEasyText.anchor.y = 0.5;
	this.mEasyText.position.x = centerPos.x;
	this.mEasyText.position.y = this.mSnakeTitle.y + 70.0;
	this.mEasyText.interactive = true;
	this.mEasyText.click = (function(e)
		{
			console.log("Easy!");
			this.mOnFinishCallback(Difficulty.Easy);
		}).bind(this);
	
	this.mMediumText = new PIXI.Text('Medium' , this.mStyle);
	this.mMediumText.anchor.x = 0.5;
	this.mMediumText.anchor.y = 0.5;
	this.mMediumText.position.x = centerPos.x;
	this.mMediumText.position.y = this.mEasyText.y + 50.0;
	this.mMediumText.interactive = true;
	this.mMediumText.click = (function(e)
		{
			console.log("Medium!");
			this.mOnFinishCallback(Difficulty.Medium);
		}).bind(this);
	
	this.mHardText = new PIXI.Text('Hard' , this.mStyle);
	this.mHardText.anchor.x = 0.5;
	this.mHardText.anchor.y = 0.5;
	this.mHardText.position.x = centerPos.x;
	this.mHardText.position.y = this.mMediumText.y + 50.0;
	this.mHardText.interactive = true;
	this.mHardText.click = (function(e)
		{
			console.log("Hard!");
			this.mOnFinishCallback(Difficulty.Hard);
		}).bind(this);
	
	this.mStage.addChild(this.mSnakeTitle);
	this.mStage.addChild(this.mEasyText);
	this.mStage.addChild(this.mMediumText);
	this.mStage.addChild(this.mHardText);

	this.mRenderer.render(this.mStage);
}

//Callback
this.mOnFinishCallback = function(difficulty)
{
	this.mStage.visible = false;
		
	this.mStage.destroy(true);
				
	//new MainGameScene(this.mRenderer , this.mScreenSize , difficulty);
}

**Comment by mathieuanthoine** [comment]
Happened to me too !

**Comment by neonwarge04** [comment]
Hi is there any suggested fix for this? I tried to replicate this with the example provided from the site. my aim is to destroy all the sprite I have on the screen to make way with the new scene. 

When you add this line:
stage.destroy(true) or stage.destroy(false)

And you press the button, I am able to get the same error. I believe there is something wrong with what I am doing. That is, there must be another way on how to do screen transitions.

**Comment by formap** [comment]
Happened to me too in v3.0.7 when calling
```javascript
container.removeChildren();
```

**Comment by ahumphreys87** [comment]
@englercj do you know when the fix for this will be released? We have come across this as well, I can see it is in the dev branch but not master yet.

is is possible to release a patch update before 3.1?

**Comment by englercj** [comment]
@ahumphreys87 It is, but I'm pretty busy right now with other things. I opened #2071 as a way to try and make time for issues like this, but haven't seen much movement yet.
