### ISSUE TITLE
Movieclip and IE9

### ISSUE THREAD

**Issue by Manu33** [pixijs/pixi.js#1822]
For information :

I've still have a problem with IE9. It seems that when you use a gotoAndStop with a Movieclip, the frame id doesn't display. This occurs not all the time but its occurs sometimes. So for example, you call gotoAndStop(4) and pixi doesn't display the 4th image but the 1st image

Regards,

**Comment by englercj** [comment]
Can you put together a jsfiddle that reproduces the issue that we can investigate?

**Comment by Manu33** [comment]
I think i find the problem. This comes from the tint of the Sprite (Movieclip extend Sprite). On IE9 when you set a tint different of 0xFFFFFF, the gotoAndStop doesn't work. So to reproduce the bug :

Display a movieclip, set the tint to 0x999999 for example, make a gotoAndStop different for the current frame displayed and this doesn't change the display...so the same frame is displayed

**Comment by Manu33** [comment]
Have you test what i'm saying ? Thanks

**Comment by englercj** [comment]
I haven't I don't really get to work on Pixi throughout the week. I have to try and smash on the weekends.

**Comment by GoodBoyDigital** [comment]
Closing for now as this is an edge case of the canvas usage 👍
