### ISSUE TITLE
Unexpected extension of lines in acute angle polygon

### ISSUE THREAD

**Issue by jwdunn1** [pixijs/pixi.js#1823]
Take a look at the WebGL rendering in this fiddle: http://jsfiddle.net/intrinsica/L9z655jy/
Note the extension of the polygon beyond the 200px width it is defined to be.
For reference, the fiddle includes a PIXI Canvas rendering and a ProcessingJS rendering.

**Comment by mattdesl** [comment]
Leaving this here for reference:

Fixing this involves miter-limiting the join so that it falls back to bevel on harsh angles. There is a bit of discussion on it [here](http://labs.hyperandroid.com/efficient-webgl-stroking) and [here](http://mattdesl.svbtle.com/drawing-lines-is-hard).
