### ISSUE TITLE
Viewport-level interaction events

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#1825]
Right now the only way to get viewport-level interaction events is to create a dummy DO and force its width to the viewport size.

The interaction manager should handle this better.

**Comment by GoodBoyDigital** [comment]
:+1:  thats on my todo

**Comment by endel** [comment]
Hey guys! I would like to help you out with this. The idea here is to avoid computation of events outside the viewport?

**Comment by englercj** [comment]
No, the idea is that right now you can't handle interaction events across the entire viewport. In v2 you could listen to events on the stage and it would return all events across the entire viewport regardless of if something was there to be interacted with or not. Currently in v3 that is impossible.

**Comment by englercj** [comment]
Related to #2071

**Comment by carlosbaraza** [comment]
:+1:

**Comment by SamStonehouse** [comment]
Is this still the case with version 4?

**Comment by ivanpopelyshev** [comment]
Yes, its still the case. Right now the best way is to create a rectangle and update it on resize

```js
stage.hitArea = new Rectangle(0, 0, renderer.width/renderer.resolution, renderer.height/renderer.resolution);
```

**Comment by bigtimebuddy** [comment]
Global interaction events are available on the InteractionManager via #2658. This is in 4.0.0-rc3

**Comment by SamStonehouse** [comment]
Is there any information on how this works?

I seem to have got a basic implementation working by adding .on('mousedown'.. to a stage but it only fires when mousing down on a graphic inside the stage when I want it to fire anywhere on the stage. 

Is this because a stage has no real graphical representation and thus if you're not click on one of the stages/containers objects then you're not really clicking on the stage and I should do what ivanpopelyshev is suggesting?

**Comment by akbr** [comment]
@SamStonehouse: Does this help?

```js
let backdrop = new PIXI.Container();
backdrop.interactive = true;
backdrop.containsPoint = () => true;

// add backdrop to scene graph...
```

**Comment by SamStonehouse** [comment]
Having `interactive = false` may well have been the issue with the stage, I couldn't check it but it doesn't matter now as the interaction manager seems to do what I need, the only problem I have now is that right clicks are not being picked up because they open a context menu instead but that's unrelated to this PR.

**Comment by bigtimebuddy** [comment]
@SamStonehouse  something like this:
```js
var renderer = new PIXI.autoDetectRenderer();
renderer.plugins.interaction.on('mousedown', function(){
    console.log("Mouse is down");
});
```

**Comment by akbr** [comment]
Also note that #2658 only emits a subset of events (e.g., not `rightdown`).

**Comment by SamStonehouse** [comment]
Interesting @bigtimebuddy that works too, I don't know which the correct way would be.

`renderer.plugins` or through `new PIXI.interaction.InteractionManager` any idea?

**Comment by SamStonehouse** [comment]
@akbr I was under the assumption left/right/middle would be handled by the same mousedown event, the middle button seems to be

**Comment by bigtimebuddy** [comment]
@SamStonehouse While both work, I would recommend `renderer.plugins` since it's already created.

**Comment by SamStonehouse** [comment]
@bigtimebuddy Great thank you

I've also solved the right click issue, it is indeed another mouse event (which I would say is intuitive).

Thanks all

**Comment by wayspurrchen** [comment]
Hi, this is working pretty fantastically for implementing panning/zooming functionality with Pixi v4. However, `e.stopPropagation` does not seem to be working anymore for sprites inside the viewport. Is there a way to get viewport events functioning with event short-circuiting?

Alternatively, is there a way to implement a drag-and-pan functionality without using the `renderer.plugins.interaction`? Previously, I had my stage container set up with mouse events and a PIXI.Rectangle `hitArea` and was trying to provide the stage with a new one every time the user pans, but that seems not to be working for some reason - I cannot pan outside of the area the first hitArea was defined in, and occasionally the `mouseup` event is not registered.
