### ISSUE TITLE
touchmove always being triggered [V3]

### ISSUE THREAD

**Issue by shinybob** [pixijs/pixi.js#1837]
It seems all touchmove events are being triggered regardless of the touch position. In the below example the touchmove event is always being triggered for both boxes whenever and wherever a movement is made. 

https://jsfiddle.net/shinybob/hgk6469x/

**Comment by stephenweaver** [comment]
Why was this ticket closed? commit f7ccb8b was reverted as an invalid solution for this fix.

**Comment by GoodBoyDigital** [comment]
Hello! This ticket has been closed as it is not considered a bug. The current set up is much more flexable (and performant) with the bonus that the feature you need can easily be implemented by combining  a move with mousedown and mouseup.

Cheers!

**Comment by stephenweaver** [comment]
:+1:
