### ISSUE TITLE
Isomorphic code

### ISSUE THREAD

**Issue by drkibitz** [pixijs/pixi.js#1839]
I decided to open this issue to track what I'm up to. At the time of writing this I have not submitted a PR for the changes I'm working on, but it is close.

Basically, allowing for PIXI to be required as a standard node module is not too far off, and the benefit of this goes beyond just community usage. This will allow much easier automated functional testing. All we have to do is allow for dependency injection in key areas, e.g. a node-canvas implementation.

This work will most likely be ongoing, and encompass more this just this repo, but also dependencies as well, such as resource-loader.

**Comment by englercj** [comment]
I'm all for it as long as we don't have to make compromises on maintainability and performance! :)

**Comment by drkibitz** [comment]
@englercj should be fine with performance, and if we get cli rendering with better automated and functional testing to me === more maintainability && stability. 

How to get there...

- Make no assumptions about environment globals at module execution time.
    - e.g. No errors should occur by simply loading PIXI in said environment
- Move PIXI environment assumptions to a implementation that is exposed, and application level code can inject different implementations, e.g. test setup, node renderer, etc.

**Comment by GoodBoyDigital** [comment]
hello @drkibitz! hows this one going? thanks!
