### ISSUE TITLE
IE8 - even feasable?

### ISSUE THREAD

**Issue by ccoenen** [pixijs/pixi.js#184]
we noticed, that pixi isn't compatible with ie8 for various reasons. I'm trying to find out, how much work a patch (or addon) would involve.

Right now, i'm failing at basic Object.create() calls, where i could at least imagine working around that with a little more javascript.

What do you guys think? Is this possible at all, or can I just give up on ie8 completely?

**Comment by glebmachine** [comment]
Does anybody use flashcanvas with pixijs?
Or you have some other polyfill work properly with pixijs on ie8?

**Comment by ccoenen** [comment]
Back in 2013 this would not have worked.
https://github.com/GoodBoyDigital/pixi.js/issues/184#issuecomment-20332769

**Comment by glebmachine** [comment]
Yeah, i see(
I let you know if i will find some workaround, thank you!
