### ISSUE TITLE
Problem filling shape with two arcs

### ISSUE THREAD

**Issue by toblix** [pixijs/pixi.js#1844]
I'm trying to fill a shape with two arcs, one going counterclockwise, like in the image. As you can see, it seems to take a detour through the center of the arc origin before drawing the second arc. I've tried numerous combinations of moveTos, lineTos and switching the drawing order, but it seems doomed to fail. This happens on v3.0.6.

This bug seems related to issue #1594, but that's apparently fixed in this version, and wasn't sure if I should create a new issue or post in that one.

![image](https://cloud.githubusercontent.com/assets/1589739/7781112/cbb4706c-00e8-11e5-9ac5-c87123d54538.png)

```javascript
var renderer = new PIXI.CanvasRenderer(1024, 768);
document.getElementById(selector).appendChild(renderer.view);

var test = new PIXI.Graphics();
test.x = 300;
test.y = 300;

const angle1 = 0, angle2 = 2*Math.PI/3;
const outer = 200, inner = 150;

test.beginFill(0xFF0000, .25);
test.arc(0, 0, outer, angle1, angle2);
test.arc(0, 0, inner, angle2, angle1, true);
test.endFill();

renderer.render(test);
```

**Comment by toblix** [comment]
Well, I guess this explains what's going on:
```javascript
if (this.currentPath)
    {
        if (anticlockwise && this.filling)
        {
            this.currentPath.shape.points.push(cx, cy);
        }
        else
        {
            this.currentPath.shape.points.push(startX, startY);
        }
    }
    else
    {
        if (anticlockwise && this.filling)
        {

            this.moveTo(cx, cy);
        }
        else
        {
            this.moveTo(startX, startY);
        }
    }
```

It seems using a counterclockwise arc always includes the center, which is not what I want, and I don't see how to create the shape _without_ going counterclockwise at least once. Is this a bug, or am I doing something completely idiotic to fill my shape?

**Comment by toblix** [comment]
Sorry! I guess I don't know how to Github, and I thought the fix for #1594 had been included in v3.0.6 (the page with the changes had the v3.0.6 tag on it?), but apparently it had not.

**Comment by englercj** [comment]
The fix for #1594 was put in, the code you mention is what was added in to fix #1594 IIRC

**Comment by toblix** [comment]
I see. I looked at [this page](https://github.com/GoodBoyDigital/pixi.js/commit/605556023bcfbdaef2e77d0b2880c63d409e5525) and assumed the red was removed and green was added, but it's the other away around. That means the problem is still there, though, so I reopen?

**Comment by englercj** [comment]
The red *was* removed and the green *was* added. The top part you posted here was added later:

https://github.com/GoodBoyDigital/pixi.js/blame/master/src/core/graphics/Graphics.js#L486-L508

Just leave this open and I'll look into it when I get a chance.

**Comment by brean** [comment]
I have the same problem. The problem is that the first segment is not calculated correctly. So a very simple workaround is to start with the -1st segment, see my gist here (which works): https://gist.github.com/brean/d525e3562d5c58efed06

**Comment by brean** [comment]
I have a Bugfix for this issue now: just always use startX and startY instead of cx and cy.
