### ISSUE TITLE
DisplayObjectContainer or Graphics Pivot Rotate Issue

### ISSUE THREAD

**Issue by antoninlanglade** [pixijs/pixi.js#1846]
Hello,
// Pixi V2.2.9
When I set the pivot to (0.5,0.5) I think that the object should rotate around his center but it's not the case in the rendering

        this.container.pivot.set(0.5,0.5); // relative
        this.container.pivot.set(xPos,yPos); // or absolute
        this.container.rotation = Math.PI;

Instead of rotate around the center the rotation is done but with a translation on the square with opacity 0.5.

![capture d ecran 2015-05-23 a 16 44 49](https://cloud.githubusercontent.com/assets/1774288/7784586/37e05af8-016b-11e5-8373-b93b5763cd90.png)
![capture d ecran 2015-05-23 a 16 44 58](https://cloud.githubusercontent.com/assets/1774288/7784585/37dd6da2-016b-11e5-9d40-c47c7c8d9371.png)

Thanks

**Comment by englercj** [comment]
Does this problem exist in v3 as well? Do you have a running example that reproduces that I can debug?

**Comment by GoodBoyDigital** [comment]
Pivot does not work with relative valuse, only absolute. 

the below code would shift the container 0.5 pixels along the x and y coords.
```this.container.pivot.set(0.5,0.5); // relative```

Only sprites support this kind of behaviour via the ```anchor``` property (think of it as a 'texture anchor')
