### ISSUE TITLE
Touch Event After CSS transform rotate the <canvas> ?

### ISSUE THREAD

**Issue by tommyZZM** [pixijs/pixi.js#1848]
after i rotate the canvas i found that touch event not works well anymore

``` html
<div class="warpper" style ="transition-duration: 660ms; transform: rotate(-90deg);">
     <canvas> </canvas>
</div>
```

how can i fix this?

**Comment by ZebraRoy** [comment]
It seems that pixi doesn't support transform: rotate. May be you can try to use the rotation on the main stage

**Comment by GoodBoyDigital** [comment]
this would be handy! we are currently using ```getBoundingClientRect``` which does not seem to care too much about css translations...
