### ISSUE TITLE
Click after page reload has no effect

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#1851]
On eg http://tobireif.com/boomchat/ , when I click on the smiley button, the animation starts. But when I then leave the mouse pointer where it is and reload the page (on Mac OS using cmd-r), then click on the button again, nothing happens.

**Comment by englercj** [comment]
Likely due to the interaction manager using mousemove to track position and on click using that stored position.

**Comment by staff0rd** [comment]
Problem doesn't exist in latest; http://codepen.io/staff0rd/pen/XNZyrx?editors=0010
