### ISSUE TITLE
Gradient and stroke offset to PIXI.Text

### ISSUE THREAD

**Issue by cvissie** [pixijs/pixi.js#1852]
The PIXI.Text right now is plenty powerful. Especially with the resolution code in, you can pretty much have crisp beautiful fonts for all devices and resolutions.

The API as it stands however is a bit lacking in drawing beautiful looking text.

However with a minimal amount of tweaking to the API we can achieve much better looking text.

As an example, if we want to achieve this:

![image](https://cloud.githubusercontent.com/assets/571532/7834158/e9cf7e98-046c-11e5-9e2f-838474d8b6a6.png)

All we need to do is add the following to the style of the text:
```javascript
// keep as is
style.stroke = 0x360a00;
style.strokeThickness = 4;
style.fill = 0xff0000;
style.fill = "red";
// new
style.strokeOffsetX = 0.75;
style.strokeOffsetY = 0.75;
style.fill = {
type:'gradient',
stops:[
        [0.00, 0xfffcff],
        [0.45, 0xffe57a],
        [0.50, 0xffac5a],
        [0.60, 0xaa7122],
        [1.00, 0xffbf57]
]
};
```

I'm not yet fully comfortable collaborating using github. But if someone wants to implement it:

I've created a fiddle that I've hacked together from the PIXI code:
https://jsfiddle.net/m9gxjejb/

It can definitely be optimized - you don't want to be building a gradient everytime you repaint text.

**Comment by JiDW** [comment]
Oooh I like that ! Thanks for the share !

**Comment by cvissie** [comment]
Just a note... My implementation as it is doesn't support multi-line.

It is easy enough to change the code to support it however. Will take some time later and update the fiddle.

**Comment by GoodBoyDigital** [comment]
Think we have this in v4 now 👍
