### ISSUE TITLE
The prominently linked "getting started" is tad outdated

### ISSUE THREAD

**Issue by tstriker** [pixijs/pixi.js#1857]
In the resources page (http://www.pixijs.com/resources/) the "getting started" (
http://www.goodboydigital.com/pixi-js-tutorial-getting-started/) is fairly up in the list of resources but it seems to be outdated to the extent that it's not working - requestAnimFrame, for example has been renamed to requestAnimationFrame, and PIXI.Stage isn't necessary anymore.

I've found the examples section (http://pixijs.github.io/examples/index.html) an excellent help for getting started, and wonder if maybe instead of having resources and examples separate, it would be simpler to find stuff if examples would be simply listed under resources, together with the link to docus etc. and "getting started" could be either killed entirely or refreshed.

And thanks for pixi! :)

**Comment by GoodBoyDigital** [comment]
true enough! Good shout on that @tbaugis .

Will probably look to remove the getting started and add a link to the examples for now. One day we will have time to update the tutorial.. im sure of it!

Cheers!

**Comment by GoodBoyDigital** [comment]
New website with new links :) 

Heres a great tutorial we are sending people too as its very comprehensive!

https://github.com/kittykatattack/learningPixi

Cheers!
