### ISSUE TITLE
Pressing a button and tweening objects behind it.

### ISSUE THREAD

**Issue by aholla** [pixijs/pixi.js#1859]
Bit of a strange one but I have a scroller with arrows on the left and right and selectable items in the middle. When I click an arrow button, the selectable items slide out of view behind the arrow buttons.

Sometimes, after I have pressed on the arrow button (touch/mobile) and release, the items slide in and receive a touch event. 

I was wondering if they are perhaps receiving the arrow buttons event.

Does that sound like a thing?

[EDIT] Actually all the selectable items sometimes receive a "touchstart" when the arrow button is pressed...

**Comment by englercj** [comment]
This should be solvable with `stopPropagation` now.
