### ISSUE TITLE
Sprite.getBounds() does not take Sprite.scale into account before updateTransform is called

### ISSUE THREAD

**Issue by davidfig** [pixijs/pixi.js#1861]
This may be more of an FYI to save other people the hour it took me to figure this out, but after changing the scale of a Sprite, you need to call updateTransform (or render) for getBounds to be correct.

Here's an example: https://jsfiddle.net/davidfig/mb1s6Lv4/1/

**Comment by GoodBoyDigital** [comment]
Fixed in v4 👍
