### ISSUE TITLE
PIXI 3 - Texture does not represent dimensions correctly after baseTexture resolution change

### ISSUE THREAD

**Issue by legman** [pixijs/pixi.js#1867]
I have come across an issue with PIXI.Texture since moving across to version 3.  We need to support SD assets for our projects and one of the ways we go about this in the last few versions of PIXI is by simply adjusting the baseTexture resolution for each texture when requested.

var texture = PIXI.Texture.fromImage("image");    *// image is 1024x1024*
texture.baseTexture.resolution = 0.5;
texture.baseTexture.update();

**Example OLD**
console.log(texture.baseTexture.width);    *// 1024 correct* 
console.log(texture.baseTexture.realWidth);    *// 512 correct*
console.log(texture.width);    *// 1024 correct*

**Example CURRENT**
console.log(texture.baseTexture.width);    *// 1024 correct*
console.log(texture.baseTexture.realWidth);    *// 512 correct*
console.log(texture.width);    *// 512 wrong*

I am assuming this is a bug but if this IS desired behaviour can you point us in a better way of doing things - maybe?

Thanks

**Comment by GoodBoyDigital** [comment]
good shout! that should read 1024. Will add to our todo list. cheers!

**Comment by legman** [comment]
Were should I be looking so I can fix this temporarily, we desperately need this fixed for several projects we are working on.

Thanks

**Comment by GoodBoyDigital** [comment]
cool - a temp fix would be
````
var getRealWidth = function(texture)
{
     return texture.width / texture.baseTexture.resolution;
}
````

**Comment by legman** [comment]
Actually this wouldn't help this current situation - the main issue at the moment is that all the images are currently displaying too small as they are displayed using their realWidth, not realWidth * (1.0 / texture.baseTexture.resolution).  I am looking for more of an internal fix so the images are visually correct!

Thanks

**Comment by GoodBoyDigital** [comment]
is this canvas or webGL?

**Comment by legman** [comment]
WebGL

**Comment by GoodBoyDigital** [comment]
cool, do you have an minimal example? seems to work ok for us - (we load using the @x0.5 prefix)

**Comment by legman** [comment]
Actually we currently either load asset A or asset B based on the desired resolution - essentially bypassing the @x0.5 prefix method. Could you please explain the concept in a bit more detail as i am having trouble finding documentation on it!

Thanks

**Comment by GoodBoyDigital** [comment]
When you load a texture you can add a prefix to the file and it will set it to be that resolution:

myTexture.png <- resolution is 1 
myTexture@0.5x.png <- resolution is 0.5
myTexture@2x.png <- resolution is 2

**Comment by legman** [comment]
ok thanks for clearing that up, i will try that way of loading images along with me own again and compare the results - i will get back to you later with a demo!

**Comment by GoodBoyDigital** [comment]
awesome! :+1:

**Comment by legman** [comment]
http://jsfiddle.net/qhyh3otr/4/

change 'hd' variable to false to load in the sd assets!

- The first box is being loading in as an atlas
- The second box is being loaded as an individual texture

As you can see loading individual textures works perfectly, however atlases seem to be having a problem. Regarding the prefixing, we cannot use @ in filenames as we work for the BBC and they don't allow certain characters!

Hope this is helpful and let me know if there is anything else i can provide.

Thanks

**Comment by GoodBoyDigital** [comment]
i see! you can actually set the prefix to what ever you fancy:

```
PIXI.RETINA_PREFIX = 'whaeva'
```
by default its set to:
```
//example: '@2x',
RETINA_PREFIX: /@(.+)x/
```

could do the trick?

**Comment by legman** [comment]
ill have a chat with aholla - but that looks promising!

**Comment by englercj** [comment]
@GoodBoyDigital Did you ever get around to fixing this?

**Comment by GoodBoyDigital** [comment]
Looks fixed to me :+1:
