### ISSUE TITLE
Rotating a Texture from PIXI.Text.generateTexture() causes jaggies

### ISSUE THREAD

**Issue by sscholle** [pixijs/pixi.js#1881]
I have highlighted the issue here in the red text in jsfiddle:
http://jsfiddle.net/nutLmxqx/2/

We want to be able to rotate a generated texture without the jaggies.

**Comment by CoDEmanX** [comment]
Looks like the red text has no proper anti-aliasing (stencil alpha?)

**Comment by GoodBoyDigital** [comment]
Antialiasing is not supported on renderTextures as this is a WebGL limitation. WebGL2 will fix this :)
Closing as there is not much to be done :(
