### ISSUE TITLE
Spritesheet with Rotated frames do not display correctly

### ISSUE THREAD

**Issue by LEMinhViet** [pixijs/pixi.js#1882]
Hi,

I have a problem with my spritesheet created by TexturePacker. When I untick the checkbox "Allow Rotation" in TexturePacker, it works perfectly. But with the tag "rotated": true in json file, some frames seem to be wrongly positioned and the animation didn't display correctly. 

Thank you.

**Comment by RoryPicko** [comment]
I found this too, worked fine on all my testing devices except the iphone 4 where width/height were reported incorrectly.

**Comment by LEMinhViet** [comment]
It seems to be a problem with frame size. When I have an rotated image from a spritesheet and set interactive = true, then width and height of the hitArea are inverse with the size of image.

**Comment by endel** [comment]
Hey @LEMinhViet, can you provide a live example?

**Comment by LEMinhViet** [comment]
![d85fb7d9566274b63abc62fc137cdbf0](https://cloud.githubusercontent.com/assets/6697001/8102780/33ab2320-1023-11e5-9dd2-e9a2b2b0cc38.gif)

You can see that the smoke do not display correctly.

**Comment by englercj** [comment]
@LEMinhViet When we say live example, we mean a running code example. We need to debug the code and see what is happening.

Thanks!

**Comment by LEMinhViet** [comment]
sorry, that's the example 
http://jsfiddle.net/vietlm13/fm4ewufq/7/
It seems to be happen only with CanvasRender

**Comment by AdiNostromo** [comment]
Yes, the problem occurs when using the CanvasRenderer and displaying a Sprite that uses a rotated texture from a sprite sheet. Making a example now.

**Comment by AdiNostromo** [comment]
Made a test with a sprite. The WebGLRenderer will render correctly but the CanvasRenderer will not.

Download: https://www.dropbox.com/s/3vhu6no9g3hwaeu/PixiCanvasRendererBugTest.zip?dl=0

**Comment by GoodBoyDigital** [comment]
hello! this should be fixed now :+1:
