### ISSUE TITLE
Possible error in the Filter's dimensions uniform

### ISSUE THREAD

**Issue by jagi** [pixijs/pixi.js#1883]
Hi I think that there is an error in this line: https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/webgl/managers/FilterManager.js#L192

It should be changed from:

```js
filters[0].uniforms.dimensions.value[0] = this.renderer.width;
filters[0].uniforms.dimensions.value[1] = this.renderer.height;
filters[0].uniforms.dimensions.value[2] = this.quad.vertices[0];
filters[0].uniforms.dimensions.value[3] = this.quad.vertices[5];
```

to

```js
filters[0].uniforms.dimensions.value[0] = this.renderer.width;
filters[0].uniforms.dimensions.value[1] = this.renderer.height;
filters[0].uniforms.dimensions.value[2] = this.quad.vertices[4];
filters[0].uniforms.dimensions.value[3] = this.quad.vertices[5];
```

As far as I understand the dimensions' values under indexes 2 and 3 are the width and the height of the sprite. My sprite has the size 400 x 200 and my canvas has size 600 x 600 but in the dimensions array I get `[600, 600, 0, 200]`. I don't know exactly what values stores `this.quad.vertices` but after investigating its values I assume that there should be 4th index taken instead of 0.

Here is an example filter that I've made. And everything works but only in the Y axis not in the X axis, because of that error. The filter just offsets sprite's texture and wraps it around.

```js
function OffsetFilter() {
  var vertexShader = null;
  var fragmentShader = [
    'precision mediump float;',
    '',
    'varying vec2 vTextureCoord;',
    '',
    'uniform vec4 dimensions;',
    'uniform vec2 offset;',
    'uniform sampler2D uSampler;',
    '',
    'void main(void)',
    '{',
    '    vec2 pixelSize = vec2(1.0) / dimensions.xy;',
    '    vec2 spriteSize = dimensions.zw / dimensions.xy;',
    '    vec2 coord = vTextureCoord.xy - pixelSize.xy * offset;',
    '',
    '    if (coord.x < 0.0) {',
    '        coord.x = coord.x + spriteSize.x;',
    '    }',
    '',
    '    if (coord.y < 0.0) {',
    '        coord.y = coord.y + spriteSize.y;',
    '    ',
    '    }',
    '',
    '    gl_FragColor = texture2D(uSampler, coord);',
    '}'
  ].join('\n');

  PIXI.filters.AbstractFilter.call(this,
    null,
    fragmentShader,
    {
      dimensions: {
        type: '4fv',
        value: new Float32Array([0, 0, 0, 0])
      },
      offset: {
        type: 'v2',
        value: {
          x: 50,
          y: 50
        }
      }
    }
  );
}

OffsetFilter.prototype = Object.create(PIXI.filters.AbstractFilter.prototype);
OffsetFilter.prototype.constructor = OffsetFilter;

Object.defineProperties(OffsetFilter.prototype, {
  offset: {
    get: function() {
      return this.uniforms.offset.value;
    },
    set: function(value) {
      this.uniforms.offset.value = value;
    }
  }
});
```

**Comment by englercj** [comment]
@GoodBoyDigital I think I made an oopsie in the dimensions :P

**Comment by jagi** [comment]
I also noticed that my filter does not work when I'm rotating it. I thought about passing to the `dimensions` var not only width and height of the sprite but also information about rotation. As I've noticed that `this.quad.vertices` contains information about vertices after transformations I assume that `dimensions` array should have more information about the sprite. Of course I could create another `uniform` variable and pass info about rotation but what was the reason for making dimensions vec4 variable instead just vec2?

**Comment by englercj** [comment]
@jagi Rotation information is passed in the transform matrix, it shouldn't be in dimensions. The dimensions are not about the sprite but about geometry. Using a `vec4` means a single uniform upload instead of 2.

**Comment by englercj** [comment]
Now that I think about it I'm not sure what uploading the quad verts in this uniform was trying to accomplish. Not sure what only a single point of the quad verts would be useful for...I may just take it out.

**Comment by jagi** [comment]
Ok, so maybe it should be removed. However, I assume there was the reason for introducing it :)
Thanks for reply
