### ISSUE TITLE
mousemove fires on all children

### ISSUE THREAD

**Issue by PierBover** [pixijs/pixi.js#1884]
So I have a container with a bunch of children. I set the `mousemove` event on each children, and when the mouse moves over one of the children, the event is fired on all children.

Is this a bug?

**Comment by englercj** [comment]
Sounds like it!

**Comment by endel** [comment]
Maybe this is related with https://github.com/GoodBoyDigital/pixi.js/issues/1837

**Comment by PierBover** [comment]
Yes it sounds similar to #1837 

I'm using 3.0.6 with WebGL renderer.

**Comment by wojciak** [comment]
+1 for this ;]

**Comment by endel** [comment]
I'll try to figure out what is happening to fix this, ok?

**Comment by endel** [comment]
It was simpler than I thought. Here is a working example with the patch: https://jsfiddle.net/endel/upz3t2a0/1/

**Comment by pavan4** [comment]
This works great but when you have overlapping objects, event is fired only on the object on top. how can it made to fire on both the objects?

I opened an issue here at https://github.com/GoodBoyDigital/pixi.js/issues/1891 for this and could not solve it yet.

**Comment by stephenweaver** [comment]
added a comment to the PR https://github.com/pixijs/pixi.js/pull/1894
this issues is not resolved with that fix. I think if we can figure out why targetTouches includes all touches on the canvas rather than just the pixi object, the events will get sent to the correct objects. maybe?

**Comment by 6174** [comment]
@endel   when   use  mousemove event for drag , your patch cannot work, because mouse move is faster than rendering,  when mouse miss hit the drag element , drag can't work. 

here is the enhance code 

```javascript
  PIXI.interaction.InteractionManager.prototype.processMouseMove = function ( displayObject, hit )
  {
      if(hit || displayObject.isDragging )
      {
          this.dispatchEvent( displayObject, 'mousemove', this.eventData);
      }
      this.processMouseOverOut(displayObject, hit);
  }
```

**Comment by 6174** [comment]
@endel   when   use  mousemove event for drag , your patch cannot work, because mouse move is faster than rendering,  when mouse miss hit the drag element , drag can't work. 

here is the enhanced code 

```javascript
  PIXI.interaction.InteractionManager.prototype.processMouseMove = function ( displayObject, hit )
  {
      if(hit || displayObject.isDragging )
      {
          this.dispatchEvent( displayObject, 'mousemove', this.eventData);
      }
      this.processMouseOverOut(displayObject, hit);
  }
```

**Comment by dichev** [comment]
`renderer.plugins.interaction.moveWhenInside = true;`

should solve your troubles ;)
