### ISSUE TITLE
[3.0.0 - 3.0.6, webgl only] Weird behavior of TilingSprite with trimmed resources

### ISSUE THREAD

**Issue by georgiee** [pixijs/pixi.js#1895]
Ah sorry I just pressed enter too early, here my edit:
See this fiddle:
http://jsfiddle.net/georgie/qa5sxp6n/2/

Two identical sprites in two different sheets. The first is a trimmed version, the second one is not trimmed. Apart from this: identical.
The trimmed one never changes its total width and therefore we get a strange pattern, compared to the correct one below.
This happens only in webgl but with every PIXI v3 release.

See here with 3.0.0/3.0.1
http://jsfiddle.net/georgie/qa5sxp6n/3/

This one is 3.0.6 with disabled webgl:
http://jsfiddle.net/georgie/qa5sxp6n/4/

![screen shot 2015-06-13 at 20 40 45](https://cloud.githubusercontent.com/assets/1701755/8145544/83552ad4-120c-11e5-8e33-d31bfb51c6c3.png)
![screen shot 2015-06-13 at 20 40 51](https://cloud.githubusercontent.com/assets/1701755/8145543/8354f366-120c-11e5-8ded-1e08ce144ee4.png)

**Comment by GoodBoyDigital** [comment]
closing this as should be cool in v4 now..
