### ISSUE TITLE
Long delay when adding Sprite with huge texture

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#1899]
Cross posting this issue from:

http://www.html5gamedevs.com/topic/15056-freezing-on-new-object/

Running example:

https://dl.dropboxusercontent.com/u/90649252/pixiexample/index.html

Spritesheet used:

https://dl.dropboxusercontent.com/u/90649252/pixiexample/img/spritesheet.png

Initial profiles show that `texImage2D` may be causing the slow down which means there may be nothing we can do about it:

![image](https://cloud.githubusercontent.com/assets/944497/8170217/fad6aac6-1363-11e5-9fbe-9bd67a1dedf8.png)

**Comment by krzysztof-o** [comment]
It cause me headache also. Would be wonderful it there was some workaround.

**Comment by GoodBoyDigital** [comment]
Huge textures can take their sweet time when uploading to the GPU. Not much can be done about that i'm afraid. 

The best thing to do is upload the textures at a more convenient time (maybe during loading) rather than at the point its is added to the stage using the following:

```renderer.updateTexture(myMAssiveTexture);```

**Comment by mushtat** [comment]
Is there a possibility to know when huge texture already appended and became visible?

**Comment by SeminYun** [comment]
is this resolved?

because we have same issue during very long time.. 

and this is happening(i don't know about v4 becuase we are using v3.0.11 yet)

this is very critical ...

how is doing?

thx

**Comment by ivanpopelyshev** [comment]
@SeminYun there are too many things I have to do, including this plugin. Sorry, I'm just too busy.
