### ISSUE TITLE
closePath method in PIXI.Graphics

### ISSUE THREAD

**Issue by snowcxt** [pixijs/pixi.js#1905]
Do you have plan to provide closePath method to PIXI.Graphics? I need to create a path with holes.

**Comment by englercj** [comment]
Graphics doesn't have support for drawing polygons with holes yet.

**Comment by snowcxt** [comment]
Do you have plan to surpport that later?

**Comment by englercj** [comment]
https://github.com/GoodBoyDigital/pixi.js/issues/1755#issuecomment-101508599

:D

**Comment by GoodBoyDigital** [comment]
this is almost ready! (check out the graphics-hole)

**Comment by twhitbeck** [comment]
cool! I don't see the graphics-hole branch, though

**Comment by GoodBoyDigital** [comment]
We now have a closePath function in v4 (dev) 👍
