### ISSUE TITLE
Text doesn't wrap using "wordWrap : true" if the word is longer than the wordWrapWidth

### ISSUE THREAD

**Issue by doyintade** [pixijs/pixi.js#1906]
There is an issue when you set style of the textfield, using wordWrap and wordWrapWidth

If the characters in the word is longer the the word wrapWidth, it doesn't actually cut off the word to the next line

Sample here 

http://jsfiddle.net/dtads/c3aeahoo/1/

**Comment by englercj** [comment]
Correct, it wraps based on white-space so when there is none it doesn't break a word in half and split it across lines.

**Comment by RoryPicko** [comment]
I would expect that behaviour but maybe a 'break-word' bollean attribute would be a nice feature to add

**Comment by englercj** [comment]
Yeah that is likely a good way to go.

**Comment by dtads** [comment]
Thanks for the resposnse guys, yes I agree that would be a better way to go, but I would imagine by default it should break the word if the length is beyond the wordWrapWidth

**Comment by englercj** [comment]
@dtads That would be inconsistent with the way text works elsewhere in web. The default will likely stay the way it is.

**Comment by dtads** [comment]
@englercj cool thats a fair point

**Comment by spelltwister** [comment]
I'm not sure how to share this really, but I wrote a TypeScript helper to wrap text with the option of word breaks.  When word breaks are false, it behaves the same as current PIXI implementation (I just refactored what was there).

/**
 * Helps format strings with new lines based on word wrapping rules
 */
class TextWrapper {
    /**
     * Reformats an input string based on text wrapping rules
     * @param text The text to reformat based on text wrapping rules
     * @param wordWrapWidth The width of the text before wrapping should occur
     * @param renderingContext The rendering context used to determine the size of the text
     * @param wordBreak [Optional = false] If true, may break words to fit the specified space
     * @returns {string} A string representing the input text that includes new lines where needed to respect wrapping width
     */
    static wrapText(text: string, wordWrapWidth: number, renderingContext: CanvasRenderingContext2D /*| WebGLRenderingContext*/, wordBreak?: boolean) : string {
        wordBreak = wordBreak || false;

        var wordsToStringFn = wordBreak ? TextWrapper.addWordsWithBreak : TextWrapper.addWordsNoBreak;
        
        return text.split('\n')
                   .map(line => wordsToStringFn(line.split(' '), renderingContext, wordWrapWidth))
                   .join('\n');

        /*
        var lines = text.split('\n');
        var result = wordsToStringFn(lines[0].split(' '), renderingContext, wordWrapWidth);

        for (var i = 1; i < lines.length; i++) {
            var words = lines[i].split(' ');

            result += '\n';
            result += wordsToStringFn(words, renderingContext, wordWrapWidth);
        }        
        return result;
        */
    }

    /**
     * Adds the words in the array to a resulting string, possibly breaking the words to fit the word wrap width constraint
     * @param words The words to fit into a string
     * @param renderingContext The context used to determine the size of the text
     * @param wordWrapWidth The maximum width of the text before wrapping
     * @returns {string} 
     */
    static addWordsWithBreak(words: string[], renderingContext: CanvasRenderingContext2D, wordWrapWidth: number) : string {
        if (!words.length) {
            return '';
        }

        var contextSpaceWidth = renderingContext.measureText(' ').width; // measureText only exists on CanvasRenderingContext2D and not WebGLRenderingContext

        var brokenWordArr = TextWrapper.chunkByWidth(words[0], renderingContext, wordWrapWidth);
        var result = brokenWordArr.join('\n');
        if (words.length === 1) {
            return result;
        }

        var wordWidth = TextWrapper.getTextWidth(brokenWordArr[brokenWordArr.length - 1], renderingContext);
        var spaceLeft = wordWrapWidth - wordWidth;

        for (var j = 1; j < words.length; j++) {
            wordWidth = renderingContext.measureText(words[j]).width;
            var wordWidthWithSpace = wordWidth + contextSpaceWidth;
            if (wordWidthWithSpace > spaceLeft) { // doesn't fit on this line
                if (wordWidth <= wordWrapWidth) { // don't break; prefer a new line if it will fit
                    result += '\n';
                    result += words[j];
                    spaceLeft = wordWrapWidth - wordWidth;
                } else { // it doesn't fit anyway so break it
                    var firstPart = TextWrapper.getMaximumStringForWidth(' ' + words[j], spaceLeft, renderingContext);
                    if (!firstPart || !firstPart.length || firstPart === ' ') { // no part fits
                        result += '\n';
                        brokenWordArr = TextWrapper.chunkByWidth(words[j], renderingContext, wordWrapWidth);
                    } else { // part fits
                        result += firstPart;
                        result += '\n';
                        brokenWordArr = TextWrapper.chunkByWidth(words[j].substr(firstPart.length), renderingContext, wordWrapWidth);
                    }
                    result += brokenWordArr.join('\n');
                    wordWidth = TextWrapper.getTextWidth(brokenWordArr[brokenWordArr.length - 1], renderingContext);
                    spaceLeft = wordWrapWidth - wordWidth;
                }
            } else { // fits on this line
                spaceLeft -= wordWidthWithSpace;
                result += ' ' + words[j];
            }
        }

        return result;
    }

    /**
     * Adds the words in the array to a resulting string without breaking the word to respect the specified width; instead, the string will be split at the following space
     * @param words The words to fit into a string
     * @param renderingContext The context used to determine the size of the text
     * @param wordWrapWidth The maximum width of the text before wrapping
     * @returns {string} 
     */
    static addWordsNoBreak(words: string[], renderingContext: CanvasRenderingContext2D, wordWrapWidth: number): string {
        var contextSpaceWidth = renderingContext.measureText(' ').width; // measureText only exists on CanvasRenderingContext2D and not WebGLRenderingContext

        if (!words.length) {
            return '';
        }

        // always add the first word regardless of width
        var wordWidth = TextWrapper.getTextWidth(words[0], renderingContext);
        var result = words[0];
        var spaceLeft = wordWrapWidth - wordWidth;

        for (var j = 1; j < words.length; j++) {
            wordWidth = renderingContext.measureText(words[j]).width;
            var wordWidthWithSpace = wordWidth + contextSpaceWidth;
            if (wordWidthWithSpace > spaceLeft) {
                result += '\n';
                result += words[j];
                spaceLeft = wordWrapWidth - wordWidth;
            } else {
                result += ' ';
                result += words[j];
                spaceLeft -= wordWidthWithSpace;
            }
        }

        return result;
    }

    /**
     * Gets the width of the text when rendered using the specified context
     * @param text The text to measure
     * @param renderingContext The context used to measure the text
     * @returns {number} The width of the text when rendered using the specified context 
     */
    static getTextWidth(text: string, renderingContext: CanvasRenderingContext2D) : number {
        return renderingContext.measureText(text).width;
    }

    /**
     * Returns true if the specified text can fit in the given width when rendered using the provided context; otherwise, false
     * @param text The text to test for fit
     * @param width The width the text should fit in
     * @param renderingContext The contexted used to measure the text
     * @returns {boolean} True if the specified text fits in the given width when rendered using the provided context; otherwise, false 
     */
    static doesFit(text: string, width: number, renderingContext: CanvasRenderingContext2D) : boolean {
        return TextWrapper.getTextWidth(text, renderingContext) <= width;
    }

    /**
     * Breaks the given word into multiple parts so that each parts fits in the given width
     * @param word The word to break apart to fit in the given width
     * @param renderingContext the context used to measure the text
     * @param wordWrapWidth The width the of the blocks
     * @returns {string[]} An array of strings where the first n strings fit the provided space and the last string contains any remaining characters 
     */
    static chunkByWidth(word: string, renderingContext: CanvasRenderingContext2D, wordWrapWidth: number): string[] {
        var initialTest = TextWrapper.getMaximumStringForWidth(word, wordWrapWidth, renderingContext);

        if (initialTest === word) {
            return [word];
        }

        return [initialTest].concat(TextWrapper.chunkByWidth(word.substr(initialTest.length), renderingContext, wordWrapWidth));
    }

    /**
     * Gets the part of the word that is able to fit in the given width when rendered using the provided context
     * @param word The word from which to get a maximum substring that fits the specified width
     * @param width The available width for text
     * @param renderingContext The context used to measure the text
     * @returns {string} The maximum substring that fits the specified width 
     */
    static getMaximumStringForWidth(word: string, width: number, renderingContext: CanvasRenderingContext2D) : string {
        if (!word || !word.length || word.length === 1 || TextWrapper.doesFit(word, width, renderingContext)) {
            return word;
        }

        for (var i = word.length - 1; i > 0; i--) {
            var testWord = word.substr(0, i);
            if (TextWrapper.doesFit(testWord, width, renderingContext)) {
                return testWord;
            }
        }
        return word.substr(0, 1);
    }
}

**Comment by mattdesl** [comment]
@spelltwister nice! I also have an implementation here, I should add a demo with PIXI at some point:
https://github.com/mattdesl/word-wrapper

**Comment by dtads** [comment]
Hi Guys, is their any updates on this?

**Comment by shootingsyh** [comment]
Another problem is for asia languages. They don't use space to split words...

**Comment by GoodBoyDigital** [comment]
fixed 👍
