### ISSUE TITLE
[v3] ParticleContainer ignore children's visible property when using WebGLRenderer

### ISSUE THREAD

**Issue by ZebraRoy** [pixijs/pixi.js#1910]
ParticleContainer will render all children in the container even their visible=false if using WebGLRenderer.
I have try the same code using CanvasRenderer and it worked fine.

**Comment by pwolfert** [comment]
I have the same problem.

**Comment by pwolfert** [comment]
As an elite container class bred to render particles quickly, I would expect it to jump for joy when it comes across a particle that it doesn't even need to render at all :)

**Comment by englercj** [comment]
@pwolfert Well, the thing is that is gets speed from statically uploading properties of the object. Making properties dynamic reduces that speed benefit, which is why we only upload dynamically what you explicitly opt-in to needing (via the options to the ctor). Visible isn't one of those things right now.

You can always set `alpha` as dynamic and set that to 0 for sprites you don't want to show.

**Comment by pwolfert** [comment]
> You can always set alpha as dynamic and set that to 0 for sprites you don't want to show.

I was doing this as a temporary workaround, but it actually worked without setting alpha to true in the `ParticleContainer`'s constructor—before I read your reply and read about those constructor parameters.  Is it supposed to do that?

**Comment by englercj** [comment]
@pwolfert If you don't set it to true then it will only update on static uploads (changing children, constructing, etc). If you set it to dynamic it is uploaded every frame.

**Comment by bigbadwofl** [comment]
Quick question. Would setting the alpha to 0 actually result in a speed increase? I'm trying to add culling to sprites in the ParticleContainer by hiding offscreen sprites and setting the alpha seems to be the only way to hide them.

**Comment by englercj** [comment]
Best way to cull is to use `.visible = false`. That will skip transform updates and rendering.

**Comment by andrewstart** [comment]
ParticleContainer ignores .visible, so it won't allow you to visually cull sprites. If it still skips transform updates, that could still be useful though.

**Comment by englercj** [comment]
Sorry, to be clear particle container works different than everyone else. transform updates happen on the GPU for particle container (one reason it is so much faster).

I was answering the general question:

> Would setting the alpha to 0 actually result in a speed increase

But didn't catch the context of ParticleContainer. In that case, no changing neither `alpha` nor `visible` will affect perf.

**Comment by englercj** [comment]
Closing this since I don't see a need to implement `.visible` support in particle container (in-fact doing so would likely make it slower).
