### ISSUE TITLE
BitmapText.getLocalBounds does not always return 'pixel perfect' dimensions

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#1913]
There exists a case where bitmap text does not perfectly conform to the 'local bounds'.

I have implemented a better 'maxLineHeight' member to more accurately determine a 'height', especially useful to single-line use-cases.

see Pull request:
https://github.com/GoodBoyDigital/pixi.js/pull/1912

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
