### ISSUE TITLE
Multitouch Interaction Manager

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#1917]
I was under the impression that PIXI v3 was "multitouch ready". However looking at the InteractionManager, it seems that there's a single .eventData property that holds the state of the various touches. Its properties get overwritten when various touches get updated - meaning it's impossible to reason about the state of the touches.

It seems to me that to fix this we should make eventData an object using the key of each touch ? 
Does this seem like a sensible approach ? 
J

**Comment by RoryPicko** [comment]
I have managed a multitouch PinchGesture using e.data.originalEvent.touches within one touch 'touchstart' event on a Container, is this what you mean?

**Comment by weepy** [comment]
I mean that this.eventData is essentially the last touch event, but this isn't very useful if you want to process another touch that was previous to this.

I'm trying out a hack that swaps this.eventData to the current touch in each of the handlers like so :

```
this.eventData = this.eventDataObject[touchData.identifier] || this.createNewEventData()
```

I just wanted to see if this was a mad idea or not !

**Comment by RoryPicko** [comment]
ahh ok, i'll leave this to the experts then, I just use the touches array for each finger position etc... good luck

**Comment by weepy** [comment]
my hack seems to work ok - is it a good/bad idea ? @englercj ? @GoodBoyDigital ?

**Comment by UncleAcid** [comment]
I'm having an issue (#1979) that sounds like your hack would work but I can't figure out how to implement it, or if I did implement it properly it didn't work. Because I'm not sure if this will solve my issue, I'm not sure if I implemented it correctly. 

Do you have a jsfiddle or something with your fix in place ?

**Comment by weepy** [comment]
Yes my fix has been working for me. I can upload soon...

**Comment by UncleAcid** [comment]
That'd be awesome, I need to deliver an ALPHA and this is the only major issue right now.

Thanks a lot.

**Comment by weepy** [comment]
so I replaced :

```
    this.eventData = {
        stopped: false,
        target: null,
        type: null,
        data: this.mouse,
        stopPropagation:function(){
            this.stopped = true;
        }
    };

```

with 

```
    this.eventDataObject = {}
    this.createNewEventData = function() {
        return {
            stopped: false,
            target: null,
            type: null,
            data: this.mouse,
            stopPropagation:function(){
                this.stopped = true;
            }
        };
    }
    this.eventData = this.createNewEventData()
```

and added 
```
this.eventData = this.eventDataObject[touchData.identifier] = this.eventDataObject[touchData.identifier] || this.createNewEventData()
```

after each (3 of):
```
 touchData.originalEvent = event;
```

here's the latest version of pixi + my changes

https://gist.github.com/weepy/73354fb4e0022ce12939

**Comment by UncleAcid** [comment]
Thanks for posting, that's exactly what I had done when trying to implement this however there is no change to the behavior for me. 

I start dragging the joystick and all is well and then as soon as I touch anything else the joystick is now responding to that touch, and then whatever touch is the most recently updated ... I don't know what I'm missing here.

**Comment by weepy** [comment]
hmm sorry - I don't really now how to help further :(

**Comment by JaredSartin** [comment]
Thanks for the investigation/patch. Sucks that this isn't properly supported yet...

**Comment by SirKnightDragoon** [comment]
Actualy, you can do multitouch with Pixi v3, but you need to build your own EventManager to control the touches id in memory, the order to know the first, second touch etc.

My events tested:  start, move, end, endout, endorout, tap, doubletap, pinchstart, pinchmove, pinchend, holdlong, holdlong.

I'm working on a editor, with move, zoom, multitouch pinch like googlemap, so yes that's work !

You need:

e.data.originalEvent.timeStamp
e.data.originalEvent.touches
e.data.originalEvent.changedTouches
changedTouches[i].identifier (i == index)
changedTouches[i].clientX ... Y

With all these data, you should do it easily!

**Comment by Friksel** [comment]
Hum... I was hoping multitouch was working out of the box too. Any chance this will be implemented any time soon? Or will this work in v4?

**Comment by englercj** [comment]
Multitouch should work since we pass back the original event. There is a bug where we aren't properly passing back identifiers but that is tracked elsewhere.
