### ISSUE TITLE
TilingSprite texture quality reduces as it repeats (on mobile/retina screen)

### ISSUE THREAD

**Issue by alexfoxy** [pixijs/pixi.js#1922]
I'm using a tiling sprite and I'm encountering an odd problem where the quality of the texture I'm using seems to get worse as the tiles repeat. I have an image of the problem here:

![wwww](https://cloud.githubusercontent.com/assets/151772/8351605/91cd6f4a-1b26-11e5-98e6-cb6f4e1deb8f.png)

And a close up of the first and last tiles: 
![firstlat](https://cloud.githubusercontent.com/assets/151772/8351616/a3cf20c6-1b26-11e5-898a-c4444f5708dd.png)

I only seem to get this problem on mobile (which is key as I'm making an app!). I have a JS fiddle of my code here: https://jsfiddle.net/qu9gqbdp/5/

Any ideas?

**Comment by englercj** [comment]
I feel like this is the culprit...

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/extras/TilingSprite.js#L92

If you change it to `highp` in the vertex/fragment shaders do you get the same problem?

**Comment by alexfoxy** [comment]
Yes - fixes. I had to change line 66 and 92 to highp. How does this impact performance?

**Comment by englercj** [comment]
It isn't necessarily a performance issue as much as a compatibility issue. Some mobile devices have problems with `highp` (their GPU doesn't support it). On the other hand, lower precision results in rounding errors like the one you see above.

I'm of the opinion we should use `highp` until someone complains :) @GoodBoyDigital thoughts?

**Comment by JiDW** [comment]
mediump should be enough

**Comment by alexfoxy** [comment]
still get the problem with mediump. We're initially releasing on iPhone 5 so should be ok - cheers

**Comment by JiDW** [comment]
Could you try with the lastest dev branch please ? Because we modified the shader very recently.

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/extras/TilingSprite.js

**Comment by alexfoxy** [comment]
okay - I'll give it a shot

**Comment by alexfoxy** [comment]
Again - only using highd fixes my issue

**Comment by manelis** [comment]
Just tried running my project on a retina ipad and it is completely blurry, I was going to open a issue, but is this related?

**Comment by englercj** [comment]
@manelis Could be anything (including you not using hdpi texutres)

**Comment by manelis** [comment]
What do you mean hdpi textures? even the text is higly blurred by the way. Maybe I should get a pic.

Its a ipad 3 on safari.

**Comment by englercj** [comment]
@manelis I would post on the forums, I don't think this is a bug. Sounds like you just are not using the resolution property.

http://www.html5gamedevs.com/forum/15-pixijs/

**Comment by JiDW** [comment]
To get back on topic, we can test if highp is supported with getShaderPrecisionFormat() 

https://msdn.microsoft.com/en-us/library/dn302419(v=vs.85).aspx

gl.getShaderPrecisionFormat(gl.FRAGMENT_SHADER,gl.HIGH_FLOAT) !== gl.INVALID_ENUM

**Comment by englercj** [comment]
How is CocooJS support for that? They kind of messed with us last time with getContexAttributes support :/

**Comment by JiDW** [comment]
I works fine, I tested it right now.

**Comment by GoodBoyDigital** [comment]
dev branch now lets you define the precision of shaders. Yay!
