### ISSUE TITLE
can i change totalSegs???

### ISSUE THREAD

**Issue by monpy** [pixijs/pixi.js#1928]
Now big scale circle is not smoothly, because in build circle define `totalSegs = 40`.
I want to change this value on drawCircle Method.

**Comment by englercj** [comment]
Good call, that is currently not possible.

**Comment by aeauseth** [comment]
`totalSegs = Math.floor(30 * Math.sqrt(circleData.radius))` seems to work OK as a temporary fix. Got this idea from http://slabode.exofire.net/circle_draw.shtml.  I also noticed that under extreme zoom the ends of the circle don't meet up perfectly.
![capture](https://cloud.githubusercontent.com/assets/13549766/8950247/cbba8b5e-3573-11e5-9608-2ae87aa040e2.PNG)

**Comment by stbaer** [comment]
+1

**Comment by englercj** [comment]
Closing since the PR was merged.
