### ISSUE TITLE
getBoundingClientRect throws error in internet explorer.

### ISSUE THREAD

**Issue by charlieclark** [pixijs/pixi.js#1930]
When I run a Pixi project in IE, I get an error on every render loop from this function:

```
InteractionManager.prototype.mapPositionToPoint = function( point, x, y ) {
    var rect = this.interactionDOMElement.getBoundingClientRect();
    point.x = ( ( x - rect.left ) * ( this.interactionDOMElement.width / rect.width ) ) / this.resolution;
    point.y = ( ( y - rect.top ) * ( this.interactionDOMElement.height / rect.height ) ) / this.resolution;
};
```

**Comment by englercj** [comment]
What version of IE are you using? Do you have a test case that reproduces the problem? That method should be supported back to like IE 4.

**Comment by macguffin** [comment]
*Problem solved but posted in case anyone else has this issue:*
**Soloution:**
When I looked again at the content of the interactionDOMElement I found an empty canvas I had generated via javascript. This only had a width and height. Once I removed this canvas the original mapPositionToPoint worked fine.

Thanks


**Original problem:**
Hi I'm also getting this error in IE 11.0

If I trace:
this.interactionDOMElement and this.interactionDOMElement.getBoundingClientRect() I get the expected results along with the "Unspecified error".

![image](https://cloud.githubusercontent.com/assets/567652/9814201/0146c28c-5884-11e5-8558-cdc689355538.png)

It seems that for some reason this.interactionDOMElement.getBoundingClientRect(); throws an error I have got around it by replacing your function with:
```javascript
InteractionManager.prototype.mapPositionToPoint = function ( point, x, y )
{
	var el = document.getElementById(this.interactionDOMElement.id)
	if(el!==(undefined||null)){
	var rect=el.getBoundingClientRect();	
		//var rect = this.interactionDOMElement.getBoundingClientRect();
		// console.log('interactionDOMElement',this.interactionDOMElement)
	     point.x = ( ( x - rect.left ) * (this.interactionDOMElement.width  / rect.width  ) ) / this.resolution;
        point.y = ( ( y - rect.top  ) * (this.interactionDOMElement.height / rect.height ) ) / this.resolution;
	}
   
};
```

**Comment by englercj** [comment]
`if(el!==(undefined||null)){`

That isn't doing exactly what you think it is...

**Comment by macguffin** [comment]
opps corrected it thanks.

**Comment by mcnuttandrew** [comment]
This issue is the same as the one documented in #1963, which provides a few other details and different solution

**Comment by GoodBoyDigital** [comment]
pretty sure this works now :+1:

**Comment by hawk8** [comment]
I am using PIXI v.3.0.9, which has the code:

`InteractionManager.prototype.mapPositionToPoint = function( point, x, y ) {
    var rect = this.interactionDOMElement.getBoundingClientRect();
    point.x = ( ( x - rect.left ) * ( this.interactionDOMElement.width / rect.width ) ) / this.resolution;
    point.y = ( ( y - rect.top ) * ( this.interactionDOMElement.height / rect.height ) ) / this.resolution;
};`


**_In our case this generates a lot of exceptions_**. I changed PIXI to this:

`InteractionManager.prototype.mapPositionToPoint = function ( point, x, y )
{
    var rect = {'bottom':0,'height':0,'left':0,'right':0,'top':0,'width':0};

    if(!!this.interactionDOMElement.parentElement) {
        rect = this.interactionDOMElement.getBoundingClientRect();
    }

    point.x = ( ( x - rect.left ) * (this.interactionDOMElement.width  / rect.width  ) ) / this.resolution;
    point.y = ( ( y - rect.top  ) * (this.interactionDOMElement.height / rect.height ) ) / this.resolution;
};
`

The purpose is of course to not call getBoundingClientRect() if there are no parent element. With this change, our system works fine and gives **no exceptions** in IE. 

I can unfortunately not provide any example code since everything is built together in a rather complex system.
