### ISSUE TITLE
bitmapFontParser does not work with data urls

### ISSUE THREAD

**Issue by ryanfields** [pixijs/pixi.js#1931]
Given a data url like `data:application/xml;base64,XMLDATA` where XMLDATA is actual encoded data, the loader is unable to load an associated image file even when the associated image has already been previously loaded.
## Scenario 1

```
PIXI.loader.add('data:image/png;base64,PNGDATA');
PIXI.loader.add('data:application/xml;base64,XMLDATA');
PIXI.loader.load();
```

Fails because bitmapFontParser can't be told to use a specific image url.  The url is forced to be computed from the font.pages.page[0].name element of the font definition file, and that computed url won't match the loaded image data url.
## Scenario 2

Assumes 'font.png' is the filename in font.pages.page[0].name.

```
PIXI.loader.add('font.png', 'data:image/png;base64,PNGDATA');
PIXI.loader.add('font.xml', 'data:application/xml;base64,XMLDATA');
PIXI.loader.load();
```

Fails because bitmapFontParser goes looking for `data:application/font.png`.

There are two problems here.  First is that `data:application/` is being errantly prepended to the image url because bitmapFontParser is not aware of data urls.  Second, even if bitmapFontParser is fixed to resolve `font.png`, the load will fail because utils.TextureCache only stores the full `data:image/png;base64,PNGDATA` url as the key.  Since the `font.png` key will miss, bitmapFontParser will queue up a load request for `font.png` which doesn't exist.
## Resolution

Regardless of how this is resolved, bitmapFontParser needs to catch data urls and not prepend `data:application/` to the image url.

As for resolving the image lookup, it might be ideal to have a means of overriding the key that utils.TextureCache will use.  Something like:

```
PIXI.loader.add('font_image', 'data:image/png;base64,PNGDATA', {
  cacheAs: 'font.png'
});
PIXI.loader.add('font', 'data:application/xml;base64,XMLDATA');
```

I'd like to avoid having to pack the image data url into the XML file unless someone has already created a tool that will build bitmap fonts with embedded image data.  If that's ultimately the route I need to go, it's better than no solution.

**Comment by englercj** [comment]
Thanks for posting this, and for including this much context; it helps a lot when trying to decide how to fix the issue.

Ideally you would be able to use the key you loaded the image as (`font_image`) to force the bitmapFontLoader to use a specific image.

The big issue right now is that there is no way to pass parameters into middlewares with `resource-loader`. So first, we need to solve that problem in that lib.

After that I imagine it would look something like:

```js
PIXI.loader.add('font_image', 'data:image/png;base64,PNGDATA');
PIXI.loader.add('font', 'data:application/xml;base64,XMLDATA', { useImage: 'font_image' });
```

As far as what the TextureCache should cache it as is probably another param passing to middleware issue. Lets treat that as a separate problem for now.

Thanks again for this, hopefully I can get into it soon.

**Comment by sommerper** [comment]
What is the status on this? This is something I could really use since I am deserialising all my assets from a JSON file.

**Comment by englercj** [comment]
I think the functionality to pass extra params was added in the loader, but I had forgotten about this issue. I should look into it again.

**Comment by englercj** [comment]
The ability to implement this feature exists in resource-loader now, just a matter of adding the support for this specific request. Open to PRs.

**Comment by jrouault** [comment]
The scenario 2 described in the issue seems to be working now, tested on v4.7.1, as:
- `bitmapFontParser` is data-url aware
- the base64 image is stored in the `TextureCache` under those two keys:
   - name specified in the `add` method
   - its full data-url
