### ISSUE TITLE
Can't Draw Childs in PIXI.Rope  in V2.2.9

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#1934]
Hi.

This issue is for V2.2.9.

I didn't see Children on Screen when i add Children  like PIXI.Spirte or PIXI.Graphic into Object of PIXI.Rope.

"Following Sample Code"
```js
this.sprite = new PIXI.Sprite(PIXI.Texture.fromImage(file));
// build a rope!
    var segs = 20;
    var length = (85) / segs;
    var points = [];
    for (var i = 0; i < segs; i++) {
        points.push(new PIXI.Point((i) * length, 0));
    };
    this.rope = new PIXI.Rope(PIXI.Texture.fromImage(arrow), points);
   this.rope.addChild(this.sprite);;
```

and then i cound't Sprite IMAGE?

cound you tel l me what problems there? 

Thx..a lot always.

**Comment by englercj** [comment]
I'm not sure that children of Rope's are drawn in v2

**Comment by englercj** [comment]
Does this problem exist in v3 as well?
