### ISSUE TITLE
WebGL Context Lost

### ISSUE THREAD

**Issue by Euden** [pixijs/pixi.js#1937]
Occasionally, I've found that using the Pixi webGL Renderer can cause a context lost error after closing the browser and reopening it on an ipad but pixi does not recover from this and chrome in particular forces the user to reload the web page.

Not being entirely sure what's causing the problem it's very hard to reproduce as it'll sometimes just happen and force the browser to refresh. This happens on both v2.x and v3. 

Has anyone got any more information on this and how best to recover from a context lost situation?

**Comment by englercj** [comment]
I think pixi has faulty handling of context loss, thanks for opening this issue.

**Comment by GoodBoyDigital** [comment]
V4 should handle this pretty well. There are somethings we will not be able to recover though such as RenderTexture information. The best thing to do is listen for a 'context' event and run any set up / advanced restore code there.
