### ISSUE TITLE
ParticleContainer handles negative scale incorrectly (probably in webkit browsers only)

### ISSUE THREAD

**Issue by sergebat** [pixijs/pixi.js#1952]
If webgl is enabled, bunny sprite in ParticleContainer is shown upside down correctly, as scale x/y is set to -1:

WebGL: http://jsfiddle.net/sergebat/nj0ptqtz/1/

However, with the following fiddle I see bunny with its head up even though scale x/y is set to -1 in Chrome and Safari:

Canvas: http://jsfiddle.net/sergebat/z88xxgfb/

Chrome version 43.0.2357.130 (64-bit) on OSX 10.9.5 at least). Version/mode: Pixi.js 3.0.7 - ✰ Canvas ✰

Image of what I see in the Fiddle, in case this is limited to particular Chrome/OS version:
<img width="454" alt="screenshot 2015-07-05 23 49 55" src="https://cloud.githubusercontent.com/assets/5421460/8513199/b48f1704-2369-11e5-8354-7be804d898f0.png">

**Comment by sergebat** [comment]
I'd like to add that the same scenario fails completely on Firefox. 

Fiddle that proves that negative values for drawImage are indeed not working as expected neither in Firefox nor in other browsers now:
http://jsfiddle.net/53tm9pvk/1/

It seems that we need to add check for either negative x or y scale, in addition to rotation not null here:
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/particles/ParticleContainer.js#L234

**Comment by englercj** [comment]
Is this still active using the latest `dev` of v4?

**Comment by sergebat** [comment]
OK, after a couple of years I managed to test it out! :) 

Unfortunately, negative scale still does not work as of PIXI 4.7: http://jsfiddle.net/z88xxgfb/5/.

**Comment by ivanpopelyshev** [comment]
Its only for CanvasRenderer, right?

**Comment by sergebat** [comment]
Correct, WebGL renderer works fine.

**Comment by ivanpopelyshev** [comment]
I'm really busy, you have to wait while someone else takes that or make PR. You can also show me which line is wrong and I'll make PR myself, I just dont have time to investigate that thing.

**Comment by sergebat** [comment]
The problem is in the optimization path here:
https://github.com/pixijs/pixi.js/blob/dev/src/particles/ParticleContainer.js#L284

If I make rotation = 0.0001, all works fine. So I _think_ that only doing optimization if scales are > 0 should do the trick. But unfortunately I am too bit busy to test this hands on immediately, sorry. :)

**Comment by ivanpopelyshev** [comment]
Ok, I get it :) Will do PR shortly.
