### ISSUE TITLE
v3.0.7 mouse position desktop and mobile difference

### ISSUE THREAD

**Issue by donpark** [pixijs/pixi.js#1955]
Just an FYI issue to add another datapoint toward resolving v3 touch event mysteries.

I had drag handling code that used `renderer.plugins.interaction.mouse.global` which worked well on desktop Firefox. But when I tested the same code in mobile Safari, mouse position was always 0,0.

Switching to `mouseEvt.data.getLocalPosition` fixed the problem and works well on both desktop Firefox and mobile Safari.

**Comment by SirKnightDragoon** [comment]
If you want all the control, you can use "e.data.originalEvent.clientX" and "e.data.originalEvent.changedTouches[i].clientX".

**Comment by englercj** [comment]
This should be fixed now in latest v4.
