### ISSUE TITLE
Please support INPUT element and tween on webGL

### ISSUE THREAD

**Issue by Jaman1993** [pixijs/pixi.js#1961]
Hello.

Do you have plans supporting INPUT element and tween on webGL?
I want to use login forms in my HTML5 games working on smart phones and tablets.
But not pop-up a software keyboard without touching an INPUT element. 

If pixi.js becomes to control these functions, more people will use pixi.js.

Thank you.

**Comment by englercj** [comment]
There will never be a forms library in the core of pixi.js. I don't think there good reasons to even build a plugin for it either though.

Just put DOM on top of your canvas and you're done.

As far as tweens, there are tons of tweening libraries out there. Use any of them.

**Comment by JiDW** [comment]
You can already do it yourself, it's fairly easy to create an input text and display it on top of your webgl interface when the user click on your placeholder.

```javascript
//Function to get the top/left of a displayobject related to the canvas
PIXI.DisplayObject.prototype.absolute = function(x,y){
    var x = x ||0;
    var y = y ||0;

    x+=this.x;
    y+=this.y;

    if(this.parent !== null)
    {
        return this.parent.absolute(x,y);
    }
    else
    {
        return {x:x,y:y};
    }
};

var input  = document.createElement("input");
input.style.position = "absolute";
input.style.width = spriteInput.width + "px";
input.style.height = spriteInput.height + "px";

var position = spriteInput.absolute();
input.style.top = (position.y + canvas.style.left) + "px";
input.style.left = (position.x + canvas.style.top) + "px";

document.body.appendChild(input);
input.focus();
input.addEventListener("blur",function(){
	//whatever you want to do with the input value
});
```
