### ISSUE TITLE
Weird  DisplacementFilter.

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#1964]
Hi.

Thx first to delveloop pixi.js

DisplacementFileter set on Sprite and I  control scale and offset into uniforms

and than i can see DispalcementFilter Effect on my Screen;

this is normal. but when i move bg and than i can see not normal DIsplacementFileter

it seems like displacement unifrom changed.

i set like following 

```js
            var tex = PIXI.Texture.fromImage('./data/image/displacementMap.jpg');
            var ch = this.mapmgr.getMainCharacter();
            var spr = PIXI.Sprite.fromImage('./data/image/4065_6161.png');
            spr.position.set(4065,4771);
            this.displacement = new PIXI.DisplacementFilter(tex);
            this.displacement.uniforms.scale.value.x = 50;
            this.displacement.uniforms.scale.value.y = 20;
            spr.filters = [this.displacement];
            this.mapmgr.map.addChild(spr);
```

and update displacementFilter into update function like following

```js
if(this.displacement) {
        //this.displacement.uniforms.offset.value.x = this.displacement.uniforms.offset.value.y = getElapsedTimePhysics()*40;
        this.displacement.uniforms.offset.value.y = getElapsedTimePhysics()*80;
        this.displacement.uniforms.offset.value.x =getElapsedTimePhysics()*20
        //this.displacement.syncUniforms();
```

it's normal when i can't move my character..when i move my character, 
DIsplaceContainerObject of Map is moved when character move.

and than DisplacementFilter is's normal..

how can i fix issue..

thx a lot always...

**Comment by englercj** [comment]
Can you show me a running example of what is happening? I'm not sure I understand your problem.

**Comment by SeminYun** [comment]
Hi.

Following is example.
http://codepen.io/SeminYun/pen/mJLOxL/

i set 512x512 Texture of Sprite and displacementFilter's texture is same.

position of Sprite move.  and DisplacementFileter is changed

i think displacementFiltr Effect is changed when move offset or scale of uniforms

thx  a lot always

**Comment by englercj** [comment]
I think I understand now, I will try to look into it soon.

**Comment by englercj** [comment]
I think this should be fixed now since DisplacementFilter is in local coords.
