### ISSUE TITLE
Assigning to WebGLRenderer::resolution

### ISSUE THREAD

**Issue by nathan** [pixijs/pixi.js#1966]
Test case: http://jsfiddle.net/e4ogmrLd/2/ (reproducible in all browsers I have tested—Safari, Chrome, & Firefox on OS X)

If you assign to a WebGLRenderer's `resolution` property, everything appears to work until you add filters to a `DisplayObject`; then you get incorrect sizing behavior. The solution appears to be assigning the same value to `<renderer>.renderTarget.resolution`, but it seems like WebGLRenderer should do this for you.

**Comment by englercj** [comment]
Good shout, thanks for the test case!

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
