### ISSUE TITLE
Low definition lines in WebGL

### ISSUE THREAD

**Issue by fbrussa** [pixijs/pixi.js#1974]
Hi, I'm using pixi to draw shapes with graphics.
If I use CanvasRenderer this look good. But if I try to use WebGLRenderer, the lines are pixelated.

Any ideas?

http://jsfiddle.net/pbt67sv8/3/

**Comment by doskallemaskin** [comment]
Having the same issue, Using graphics in webgl looks much worse than canvas.

**Comment by englercj** [comment]
The stencil buffer has no AA support. The best we can do is FXAA afterwards, but it will not look as good as canvas which is AA.

If your shape doesn't change often you can generate a texture from it, and drawing that instead may look better.

**Comment by englercj** [comment]
Closing this since it seems answered.
