### ISSUE TITLE
Does VideoBaseTexture support transparency of video?

### ISSUE THREAD

**Issue by darting** [pixijs/pixi.js#1977]
Hi All,
Does VideoBaseTexture support transparency of video? 

Thanks.

**Comment by englercj** [comment]
Have you tried it? :)

**Comment by photonstorm** [comment]
It does. The question is, does your browser? :) Chrome is the only browser I know of that supports webm files with an alpha channel *right now*. Everything else just renders it opaque.

**Comment by englercj** [comment]
Closing this since it seems answered.

**Comment by games** [comment]
Hi guys, I have created a custom shader & sprite to supports transparency of video in my game. do you have any plan to support something like this?

the video file can download from:
https://jakearchibald.com/scratch/alphavid/compressed.mp4

VideoSprite
https://gist.github.com/games/855e22cb71d5f31b65bb

VideoShader
https://gist.github.com/games/3015a9194d3823654d7e

**Comment by PainKKKiller** [comment]
Is there any progress with transparency video? I have the same problem and so far as I understood I can do it only with webGL
