### ISSUE TITLE
Scaling masks

### ISSUE THREAD

**Issue by ryanfields** [pixijs/pixi.js#1978]
At the root of my scene is a PIXI.Container object.  When I change its scale, all items inside it scale with the exception of masks.  All masks retain their original size, causing more clipping than intended.

Is this intended, or is this a bug in the way masks are displayed?  Do I need to walk my whole scene graph searching for masks and manually scale them in proportion each time the Container changes scale?

**Comment by englercj** [comment]
> Is this intended, or is this a bug in the way masks are displayed

A bug, mask transforms are not updated which will cause this issue.

**Comment by GoodBoyDigital** [comment]
Hello! This is intended behaviour :)

Its a cool feature that means a mask does not need to be tied to the thing it is masking. To solve your issue you would simply need to add the mask to the object you are masking.

Forcing the mask to respect the transform of the object it is masking is quite restrictive. The current model is based on how flash does it - it is much more robust :)

**Comment by thesunlover** [comment]
Then how we can have a mask only on a single object, so they both can be scaled in sync with each other?
I was also curious about this.
Can we add a new property that determines single mask's behaviour?
And of course the default should be the flash-like one.

**Comment by englercj** [comment]
I'm confused how is the mask not acting with the parent transform more robust? It seems like it violates the principle of least suprise. I would expect a mask to act just like the parent unless I tell it not to.

**Comment by thesunlover** [comment]
I got a little bit confused too, so probably an example will be the best to illustrate what I mean.
I can open a new issue if you say.

**Comment by englercj** [comment]
Like @GoodBoyDigital mentioned, if you want it to scale and such with the object it is applied to, just also add it as as child:

```js
sprite.mask = maskObject;
sprite.addChild(maskObject);
```

Does that not accomplish what you want?

**Comment by ryanfields** [comment]
I'll confirm when I get a moment.  It's not very intuitive though, so adding this to the docs somewhere would be helpful.

**Comment by Bokos-** [comment]
Nice! Guys it would be nice if you put this non-intuitive idea to docs :).

**Comment by bigtimebuddy** [comment]
PR welcome to add a note about this
