### ISSUE TITLE
Multitouch (Joystick + Button) not working, only repsonding to latest touch

### ISSUE THREAD

**Issue by UncleAcid** [pixijs/pixi.js#1979]
v3's interaction manager is not allowing me to have a joystick with a button in my game (run and jump). I touch the joystick and it's fine, as soon as I touch anywhere else as well the joystick starts responding to where the latest moved touch is. 

Am I just missing something or is this a bug in the interaction manager ?

In my touch start I'm setting this.data = event.data and in my touch moved I'm using this.data.getLocalPosition ...

I am aware of #1917, but I can't figure out how to implement it (I've tried so many ways and nothing works), and I'm not even sure that will solve my problem because there's no demo or anything.

**Comment by englercj** [comment]
> or is this a bug in the interaction manager ?

That, multitouch support doesn't work in the current Interaction manager.

**Comment by UncleAcid** [comment]
Ah, lame. I'm just going to try @weepy's hack from #1917 once he posts it and see if that works for now.

You may want to remove the comment "This manager also supports multitouch." from the interaction manager's constructor for now (until it actually does support multitouch) as it's misleading.

**Comment by charlesbodman** [comment]
@UncleAcid Do your buttons listen for the "touchendoutside" event? Remove this and your problems will probably go away. 

I was having this exact same issue.

**Comment by GoodBoyDigital** [comment]
closing this as multitouch support is working in dev branch. (using ```data.identifier```) thanks!
