### ISSUE TITLE
Terrain painting (texture only)

### ISSUE THREAD

**Issue by bQvle** [pixijs/pixi.js#1981]
I'm not exactly going there yet, but (as you know) I'm building this editor, and at some point, I'll try to make some kind of terrain painting. 
Just for creating a flat terrian mesh with painted uv's mapped to different textures.

I would just like to hear your thoughts, what the right approach would be.

My thought so far would be to streatch a low-res texture onto the terrainMesh. (maybe 512x512). then paint that texture with Red, Green, and Blue. Maybe utilize the alpha channel aswell to make room for an extra texture. 

Then analyze the the colors of each pixel on that texture, and map it accordingly to the UV's of the mesh. I

Would that be the right approach? or does anyone have some insight/experience that would kick me in the right direction?

Thanks

**Comment by GoodBoyDigital** [comment]
this looks a bit old, sorry you did not get an answer @bQvle ! hopefully you found a way. Closing for now, unless you still require some info! :+1:
