### ISSUE TITLE
NormalMap and Displacement filters are not using offset uniform

### ISSUE THREAD

**Issue by jagi** [pixijs/pixi.js#1986]
Hi, looking at the NormalMapFilter, it has the `offset` uniform [defined](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/filters/normal/NormalMapFilter.js) however it's not used at all in the WebGL [fragment](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/filters/normal/normalMap.frag). I would be nice to have such feature.

On the other hand the DisplacementFilter filter used to have the `offset` uniform but now it does not. I have to move sprite.

**Comment by englercj** [comment]
What would you expect `offset` to do in the NormalMapFilter? The fact that it is there is just a typo, a copy-paste error.

DisplacementFilter has no offset anymore because you can just do that in the texture frame. No need to have an extra uniform as well.

Hope that makes sense.

**Comment by jagi** [comment]
Hi, I would like it to be possible to move a normal map like I'm moving displacement map in the DisplacementFilter. When you are simulating waves on the water (DisplacementFilter) you are moving a sprite with a texture. I would like the same to be possible but using NormalMapFilter.

**Comment by englercj** [comment]
Then move the texture frame the same way you do it in displacement filter.

**Comment by jagi** [comment]
But how to move texture? When using it with DisplacementFilter I move sprite but here I don't have sprite. You can't move texture alone, am I right?

**Comment by englercj** [comment]
You can move the frame of the texture around.

**Comment by jagi** [comment]
Changing `texture.frame` properties does not have any effect on the displacement map.

**Comment by englercj** [comment]
Do you mean the normal map?

This is getting very abstract and difficult to understand. If you could just post an example of what you are trying to do and explain specifically what you want to accomplish it may be easier.

**Comment by jagi** [comment]
Let's take this example http://www.goodboydigital.com/pixijs/examples/20/

When I try running this code in the console

```js
filter.uniforms.displacementMap.value.frame.x = 100;
```

nothing happens. Shader does not take frame position and size into account when drawing normal map.

**Comment by englercj** [comment]
That also is a completely different version of pixi and the filter itself.

**Comment by jagi** [comment]
The `mapDimensions` uniform is 2 dimensional and it contains only the width and height of the texture not the x and y position. I would like to move texture around (offset it) and wrap it. I would like to simulate flag distortion on the sprite. The displacement filter only distort texture and normal map filter put light and shadows on the texture, so I wanted to use both.

**Comment by englercj** [comment]
I see, your best bet is to write your own filter based on this one. Or for us to revamp it to be awesome. I'll leave this open for that reason.

**Comment by jagi** [comment]
Ok, I will try to improve it. However I don't feel very good in GLSL.
