### ISSUE TITLE
complex polys upside down when rendered to renderTexture in WebGL

### ISSUE THREAD

**Issue by wayfu** [pixijs/pixi.js#2002]
Please see here for a minimal repro in Phaser: https://github.com/photonstorm/phaser/issues/1942
http://jsfiddle.net/fb4vrnzb/

I know that's still pixi v2, but the buildComplexPoly function is essentially identical so perhaps it's still broken in v3; or else, you can tell me what I need to do to fix it in Phaser ;)

Also, it appears antialiasing is off in the renderTexture by default? Is there a way to turn it on?

**Comment by GoodBoyDigital** [comment]
this should be fixed in v3 / 4
