### ISSUE TITLE
when Container is flipped ( .scale.x = -1 ) Sprite.mask stops working

### ISSUE THREAD

**Issue by AndreasDilaveris** [pixijs/pixi.js#2005]
I attempt to flip the a PIXI.Container containing 2 PIXI.Sprites, one acting as a mask for the other.  When Container is flipped using  .scale.x = -1 sprite mask no longer works and both Sprites disappear.

```javascript
var stage = new PIXI.Container;

var box = new PIXI.Container;
var bg = new PIXI.Sprite.fromImage('portrait.jpg');
var imageMask =  new PIXI.Sprite.fromImage('blurwhite.png');

//flip the container
box.scale.x=-1;
box.position.x=1000;

stage.addChild(box).addChild(bg);

// toggle the mask
stage.interactive=true;
stage.on('mousedown',function(e){
(bg.mask == imageMask)? bg.mask = null : bg.mask = imageMask;
			})
```

example:
http://turnoffthe.tv/clients/pixi/error/

**Comment by englercj** [comment]
Hey @AndreasDilaveris thanks for the bug report, does this happen only in WebGL or in both Canvas and WebGL?

**Comment by AndreasDilaveris** [comment]
Hi @englercj 
Thanks for the amazing framework by the way

```javascript

//replaced the following:
//var renderer = PIXI.autoDetectRenderer( width, height, { backgroundColor : 0xc7b4a5 } );
// with this:

var renderer = new PIXI.CanvasRenderer( width, height, { backgroundColor : 0xc7b4a5 } );
```
this is the result:
http://turnoffthe.tv/clients/pixi/error/errorcanvas.html

which still doesn't seem to work correctly but in a somewhat different fashion.  This time bg sprite remains visible but the mask doesn't get applied.  This is also the case when the .scale.x is not set to -1

**Comment by GoodBoyDigital** [comment]
this should be fixed now. (related to a getBounds scaling issue). Thanks!
