### ISSUE TITLE
Canvas Renderer + Retina (resolution - 2) + Tint not working

### ISSUE THREAD

**Issue by adireddy** [pixijs/pixi.js#2006]
http://jsfiddle.net/adireddy/uf1zggL2/

When I tried to apply tint on a retina asset, the image is being cropped.

It works on non-retina asset.

**Comment by englercj** [comment]
Thanks @adireddy certainly looks like an issue, will look into it.

**Comment by alebianco** [comment]
it seems that on a mobile devices (tested ipad4 ios 6.1 so far)  it doesn't even render the first quarter of the sprite, it fully disappears

**Comment by alebianco** [comment]
I had a quick dig, in both cases it's because the CanvasTinter, when using tintWithPerPixel (mobile) or tintWithMultiply (desktop), does not consider the baseTexture.resolution
I need to do more tests but I could have a patch coming soon

**Comment by stbaer** [comment]
+1 for getting this fixed

**Comment by dohomi** [comment]
+1 for fixing
