### ISSUE TITLE
Is there a way to partition blendMode ?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#2007]
I have a simplistic particle engine for explosions, etc. which is a standard PIXI.Container object, containing a sprite for each particle.

Particles should additively blend into each other, but not with the rest of the scene. If I turn off additive blending I get nice crisp looking particle effects, but they don't look right because they're not being blended:

<img width="171" alt="screen shot 2015-07-28 at 8 59 17 am" src="https://cloud.githubusercontent.com/assets/718067/8936506/8c99193e-3507-11e5-9f16-7402a944f3ff.png">

If I turn on additive blending I get nice looking particles but they are washed out because they are blended into the underlying background tiles in my game:

<img width="183" alt="screen shot 2015-07-28 at 9 00 29 am" src="https://cloud.githubusercontent.com/assets/718067/8936526/ac3efd08-3507-11e5-8cf7-fb34e6adee5f.png">

Is there a way to have only my sprites in the particle container blend with each other, and *not* with the other stuff in the scene? Am I using the wrong blend mode to achieve this, or perhaps there's some way to partition these objects differently?

**Comment by englercj** [comment]
Render them to a RenderTexture so they are only additive with eachother, then render that to your scene with the proper scene blend mde.

**Comment by mreinstein** [comment]
> then render that to your scene with the proper scene blend mode.

It sounds like when I add the renderTexture to the scene, I should use the default blend mode (0) ?

**Comment by englercj** [comment]
Most likely, each of the particles should be ADD blend mode and drawn to the RenderTexture. Then the sprite of that RenderTexture should likely just use the default blend mode.

**Comment by mreinstein** [comment]
Cool, I'll give that a shot. thanks! 

I really need to start compiling these little nuggets into some kind of "pixi v3 cookbook".

**Comment by mreinstein** [comment]
Is it possible to attach a shader to renderTexture? My attempt, which doesn't work:

filter.frag
```
precision mediump float;

varying vec2 vTextureCoord;
uniform sampler2D uSampler;

void main(void) {
  gl_FragColor = texture2D(uSampler, vTextureCoord);

  if (gl_FragColor.r > 0.0 || gl_FragColor.g > 0.0 || gl_FragColor.b > 0.0) {
    gl_FragColor.rgb *= gl_FragColor.a;
    gl_FragColor.a = 1.0;
  } else {
    gl_FragColor.rgba = vec4(0.0);
  }
}
```

filter.coffee
```coffeescript
PIXI = require 'pixi.js'
fs   = require 'fs'

frag = fs.readFileSync __dirname + '/filter.frag', 'utf8'

class ParticlesFilter extends PIXI.AbstractFilter
  constructor: ->
    @uniforms = {}
    super null, frag, @uniforms

module.exports = ParticlesFilter
```

main.coffee
```cofffeescript
Filter       = require './filter'

container = new PIXI.Container()
ratio = window.devicePixelRatio or 1

opts = view: canvas, resolution: ratio
renderer = PIXI.autoDetectRenderer 1024, 1024, opts

renderTexture = new PIXI.RenderTexture renderer, 1024, 1024, PIXI.SCALE_MODES.NEAREST, ratio

f = new Filter()
container.filters = [ f ]

...

render = ->
  renderTexture.clear()
  if not mat
    mat = new PIXI.Matrix()
  else
    mat.identity()

  mat.translate scene.x, scene.y
  renderTexture.render container, mat
```

Is there a different way I should be setting up the shader and attaching it?

**Comment by englercj** [comment]
Put the filter on the sprite that displays the render texture, not the container it is rendering.

```js
var sprite = new PIXI.Sprite(renderTexture);
sprite.filters = [f];
```

**Comment by mreinstein** [comment]
that worked, thanks.
