### ISSUE TITLE
Question/Bug: Does PIXI 3.0.0 support IE9?

### ISSUE THREAD

**Issue by joeredfearn** [pixijs/pixi.js#2009]
I seem to be having trouble in the asset loading department using the new **resource-loader** which i discovered has IE 9 support in its todo-list.

We are being told this error is occurring at the very beginning of the web page loading.

```javascript
LOG: Pixi.js 3.0.0-rc4 - Canvas - http://www.pixijs.com/
SCRIPT5007: Unable to get value of the property 'status': object is null or undefined
SCRIPT5007: Unable to get value of the property 'status': object is null or undefined
```

Any help would be greatly appreciated!

Thanks

**Comment by englercj** [comment]
Yes, v3 should support IE9 (as should resource-loader) we have a few projects that are launched using both projects and work on IE9.

If the loader is giving you an error in IE9 please open an issue on the [resource-loader](https://github.com/englercj/resource-loader) repository with a running example that reproduces the issue.

Thanks!

**Comment by joeredfearn** [comment]
Actually I have tracked the issue down to the XHR object being null when it reaches PIXI.Resource - I will continue digging.

**Comment by englercj** [comment]
@joeandaverde Yes, that issue ws fixed quite some time ago. If you update it will be fine :)

**Comment by joeredfearn** [comment]
oh thats great news!

I will give it a shot mate, 3.0.7 right?

**Comment by englercj** [comment]
That is the latest pixi version, it uses v1.6.1 of the resource-loader. If you still have issues after upgrading then open an issue on the resource loader tracker.

**Comment by joeredfearn** [comment]
ok will do!

**Comment by joeredfearn** [comment]
that fixed the issue, thanks for the support!

**Comment by ex** [comment]
Was this really fixed?
I'm having random stalls on IE loading lots of PNG assets with the latest build and updated libraries.

**Comment by englercj** [comment]
Then I would open a new issues that includes a running example that shows your error. Pixi and resource-loader work well on IE9.
