### ISSUE TITLE
Dragmove in current dev

### ISSUE THREAD

**Issue by stbaer** [pixijs/pixi.js#2010]
Hi,

I'm developing with the current pixi.js dev build and having a hard time with dragmove because of #1894 - if the mouse moves too fast and leaves the hitarea, the object stops dragging.

I made a fiddle with an updated pixi.js dev build and the pixi dragging demo from the v3 examples: http://jsfiddle.net/8ey1r05d/

So far I already spent a couple of hours to make it work in my app again, I came up with 2 solutions which are working, but I don't like either of them too much:

1. on dragstart increase the hitarea enough to prevent the pointer from leaving it, on dragend set it back to normal. This works pretty good when using the mouse, but for some reason not at all with touch. 

2. override `InteractionManager.prototype.processMouseMove` and `...processTouchMove` to get the old behavior back.

Both doesn't feel right to me. If the change is going to stay, what is the recommended way to do drag and drop from now on?

**Comment by englercj** [comment]
How would you do it in DOM? IIRC you normally bind the event to a parent and move the child, right?

Have you tried that?

**Comment by stbaer** [comment]
You mean e.g. bind the event to the stage and then move all stage childs that have a dragging property set to true?

I thought about that, but in my case I'd probably go back to the window as a parent. And then, why not just stick to the old behavior and override the processMouseMove event?   This also solves the problem that DisplayObjects with higher index block the move events of childs that are behind (forgot to mention that in the first post, you can try it with the bunnies in the fiddle).

I'll figure it out but want to make sure first that the new behavior is wanted and going to stay. If yes this issue can probably be closed.

**Comment by englercj** [comment]
I'm not sure what you are getting at by saying it would be better to override the library behavior than to have an interaction simulation similar to DOM interaction events. When we change interaction behavior it almost always is to try and act like DOM. The idea being if you could implement the action in DOM, the pattern would be similar here.

Why is making use of the fact that events bubbles not a good idea? If the stage is the container for where the object can be dragged, then sure bind to the stage. Am I missing something about that being how it works elsewhere? I consider it a bug that worked differently before, and I would consider it a bug if we worked differently now.

**Comment by stbaer** [comment]
I think it's good that the event bubbles, but with this change a mousemoveoutside event might be helpful, it was discussed here #1564.
