### ISSUE TITLE
PIXI.loaders.Loader Docs

### ISSUE THREAD

**Issue by mjurczyk** [pixijs/pixi.js#2016]
Hey,

I've been playing with pixi.flip and sprite sheets yesterday, and I'd like to suggest a minor update for the `PIXI.loaders.Loader` docs ([docs](http://pixijs.github.io/docs/PIXI.loaders.Loader.html)). 
Reading the API docs right now suggests that the Loader is used for loading images. It might be a problem with my imagination, but it actually took quite a while and a bit of reading of pixi's source code to understand that the Loader is actually conveniently contextual:

``` js
Loader._pixiMiddleware = [
    // parse any blob into more usable objects (e.g. Image)
    ResourceLoader.middleware.parsing.blob,
    // parse any Image objects into textures
    textureParser,
    // parse any spritesheet data into multiple textures
    spritesheetParser,
    // parse any spritesheet data into multiple textures
    bitmapFontParser
];
```

Also the comment in the source is doubled wrongly ;P

**Comment by englercj** [comment]
The loader can load anything. Then for certain things we have parsers to make it handle certain things more gracefully. JSON files try to get parsed for spritesheets and automatically download the image file, XML files try to get parsed for bitmap fonts and automatically download the image file, etc.

Unfortunately there is no parser for video and fonts, yet but that doesn't stop you from being able to use the loader for them.

What was the hard part to wrap your head around? What comment in which source is wrong?

**Comment by mjurczyk** [comment]
@englercj sorry man, been a bit busy. Here are the answers right away:
1. Wrong comments in the source:
```js
// parse any spritesheet data into multiple textures
spritesheetParser,
// parse any spritesheet data into multiple 
bitmapFontParser
```
Second comment should be more like `// parse any bitmap font data`. But that's minor.

2. The reason for that issue was the docs itself. These docs: http://pixijs.github.io/docs/PIXI.loaders.Loader.html . They say nothing about the contextual nature of the Loader. From the docs I can read as much as that I can load images via the Loader.

Would be nice to add there that it is also possible to load spritesheets and fonts with that Loaders ;)
