### ISSUE TITLE
Build pixi not to show use the "require" methods?

### ISSUE THREAD

**Issue by doskallemaskin** [pixijs/pixi.js#2019]
I'm currently doing a project in typescript and it seems like using browserify to build it would be good for me, though when using browserify to require PIXI i get some errors, (it crashes and says it cannot require ./polyfills), 

This seems to be because PIXI still got the require method calls in the build version. Is there a way to build PIXI to remove these? I did a simple search and replace to confirm my theory and it worked.
My current browserify build command is 

    browserify -t debowerify -p [tsify --target es5] index.ts > bundle.js

**Comment by englercj** [comment]
You shouldn't be requiring the built version with browserify. You should be requiring pixi with just `require('pixi.js')` which will resolve to our `index.js` file in the source.

The way browserify works is by wrapping your modules so that your require calls work, not by replacing them and removing them from source.

**Comment by doskallemaskin** [comment]
This is what i am doing, with the bower package the built file seems to be used. Though, with the npm package the behaviour you state seems to happen. Is this the intention? It might be that debowerify asks the bower.json where the entry point is and it seems to point to the bin/pixi.js.

But i guess everything is working as intended then?

**Comment by englercj** [comment]
Yeah the bower main file is the built file because including the file from bower means you just want the file, not the npm ecosystem version. If you want to use the npm eco system you should just use npm :)

**Comment by doskallemaskin** [comment]
Yes i believe i wanted the bower system but the npm system should work just fine, and while i'm at it, i was thinking of trying to take full advantage of this, requiring only the modules which i need, though i'm not sure how to do this. I found this old page https://www.npmjs.com/package/pixi, it's outdated but since it stated it was intended for browserify i thought it should work. Though, i cannot get it to work properly.

I've tried 
    var container = require("pixi.js/display/Container");
but it does not work, i guess it thinks pixi here is a subfolder in my project root. Is this possible or what should be my direction here? You seem to have some idea about browserify, i just started using it some days ago :)

Thanks for your answer tho!

**Comment by englercj** [comment]
The format is `<module>[/file/path]`. So:

```js
require('pixi.js/src/core/display/Container');
```

**Comment by doskallemaskin** [comment]
Yes i know, i just stumbled upon that one, which gave me the idea, since i didn't see anything about this in the official pixi one. 
The syntax you posted is working correctly and i'm really glad for your help :) :+1:

**Comment by englercj** [comment]
Thanks man, let me know if you need anything else.
