### ISSUE TITLE
Character Movement - Stuttering and not fluent?

### ISSUE THREAD

**Issue by Z3roCoder** [pixijs/pixi.js#2026]
Hello there! I have recently been gaming around with PIXI.js and upon implementing stuff such as jumping and moving, I noticed that both do not look very fluid at all. Am I perhaps doing somethign wrong in terms of velocity, or is the speed just too fast or something? Because when looking at other 2D games, movement looks completely fluid.

To show what I am talking about, please go to "http://test.novalos.net/game" and see for yourself!

Is someone able to help me with this?

More Info:
This is happening on the latest of all Browsers for me currently, as well as friends and other People I know. 
Varies also from Windows 7, 8, 8.1 and 10
Steps to reproduce: Just game :P

**Comment by adelciotto** [comment]
Hey @Z3roCoder!

The demo runs perfectly smooth for me on my MBP retina 13" using Chrome version 44.0.2403.125 (64-bit); However this will vary greatly between browsers.

Now there are a few possible reasons that you are experiencing jittery movement. Rich, the creator of the Phaser framework outlines them perfectly in this [thread](http://www.html5gamedevs.com/topic/15998-animation-smoothness-problems/?p=90638).

I'd recommend perhaps using [Phaser](https://phaser.io/); along with the arcade physics system; as it handles the complexity of implementing an effective game loop and handling things such as integration and air drag etc. Furthermore; Phaser uses pixi internally for rendering anyway..

If you really just want to use Pixi; then you can take a look at [this](http://www.html5gamedevs.com/topic/8716-game-loop-fixed-timestep-variable-rendering/) very informative post. It shows a fixed step game loop using interpolation (the sprite's previous position plus its calculated velocity) to work out the rendered position. It is smooth at any frame-rate. I have also implemented this loop [here](http://codepen.io/anthdeldev/pen/OPZQjb).

I really hope this helped!

**Comment by Z3roCoder** [comment]
Thank you, @adelciotto. Your post sounds great, and I will totally look into Phaser as well, as I am only wanting to try out developing games anyway with my current knowledge. I am not perfect in coding, but I am learning. I have been interested into making games and thus wanted to try it out, so I am not onl restricting myself to a pure rendering engine, but I thought it would be a nice task to figure out how to do most of the game logics myself.

Thank you tough again for your post, I will look into both Phaser and the post with the fixed game loop.

I will update this post once it worked.

**Comment by Z3roCoder** [comment]
Also @adelciotto I have to add that it is less "lagging" or stuff but more "When I move my bunny, the textures get somehow unsharp" if you understand what I mean? Like when I constantly press Right, and the bunny moves to the right, the details are not there anymore in terms of, it is blurred!

Does this happen to you?

**Comment by englercj** [comment]
> When I move my bunny, the textures get somehow unsharp

This is likely due to you moving the object to non-integer coords. That will make the browser interpolate between pixels which will result in a blurry draw.

**Comment by adelciotto** [comment]
Oh @Z3roCoder ok I see what you mean, I thought you were talking about jittery or laggy animation. Yeah @englercj is correct here, you need to round your position values down to whole numbers before rendering. I think there is a roundPixels option in the renderer.

**Comment by Z3roCoder** [comment]
@englercj and @adelciotto - I am moving my bunny solely with integer coords.
I implemented my movement inside of a "movement.js" and it contains following code:

```
//Right
right.press = function () {
    rightpressed = true;
    bunny.vx = 5;
    //bunny.vy = 0;
};
right.release = function () {
    rightpressed = false;
    if (!left.isDown && bunny.vy === 0) {
        bunny.vx = 0;
    }
};
//Left
left.press = function () {
    leftpressed = true;
    bunny.vx = -5;
    //bunny.vy = 0;
};

left.release = function () {
    leftpressed = false;
    if (!right.isDown && bunny.vy === 0) {
        bunny.vx = 0;
    }
};
//Jumping
space.press = function () {
    jumpStart();
}

space.release = function () {
    jumpEnd();
}

function jumpStart() {
    bunny.vy = gameSettings["MaxJumpHeight"];
}

function jumpEnd() {
    if (bunny.vy < gameSettings["MinJumpHeight"])
        bunny.vy = gameSettings["MinJumpHeight"];
}

var maxgrav = gameSettings["maxGravity"];
var gravityconstant = gameSettings["Gravity_Constant"];
function jumpGravity() {
    if (bunny.y != 343){
    if (bunny.vy + gravityconstant <= maxgrav)
        bunny.vy += gravityconstant;
    else
        bunny.vy = maxgrav;
    }
}
```
Where as the function "jumpGravity" is called in my gameLoop per Frame.
maxGravity is currently set to infinite
Gravity_Constant is set to 0.7
MaxJumpHeight is set to -12
MinJumpHeight is set to -6

**Comment by englercj** [comment]
> Gravity_Constant is set to 0.7

> `bunny.vy += gravityconstant;`

That doesn't look like an int...

**Comment by Z3roCoder** [comment]
@englercj True that, but it also happens when just walking from left to right, but the gravityconstant only influences jumping and falling

**Comment by englercj** [comment]
Hmm, I looked at your linked example and it was smooth and crisp for me. No interpolating. I'm honestly not sure what the problem could be. Perhaps you have outdated drivers?

**Comment by Z3roCoder** [comment]
@englercj I have now updated my example with a bigger and a higher-quality sprite. You can clearly notice that the moment you start to move, the sprite's texture becomes clearly unsharp/blurred. When I as an example look at other 2D games like Flappy Bird, or even Angry Birds on my Phone and move things there, they dont get blurred and stay crisp upon movement. Even looking at Pixi sample games it doesnt happen.

Here are the Files I am using, maybe I have made a mistake in coding the stuff?
http://cloud.novalos.net/index.php/s/GhyBJC9PXpwTIEW

Thanks for any help guys! So much appreciated :D

**Comment by Z3roCoder** [comment]
@englercj - So I assume no one has really any help for me? I provided the Source as I said, maybe I am doing something wrong when changing coordinates or anything. If anyone could look over it that would be super helpful!

**Comment by whizzkid** [comment]
put console.log(bunny.position); in your play routine. you'll see that your bunny is actually NOT  rendering on rounded coordinates, because it seems to fall just a little bit.
y is  380  then 379.8,  380.5, 130.6,  131.29999    etc..

fix that first :)

**Comment by Z3roCoder** [comment]
@whizzkid - So I should just round the values onto the next lowest value? or round down when the commas are .0-.4 and up .5-.9?

Also, it happens as well when moving left and right so not only jumping/fallíng is he problem! :)

**Comment by whizzkid** [comment]
Well that probably won't work the way you expect it, 

you're performing your gravity(which uses float) and movement your position values directly
            bunny.x += bunny.vx;
            bunny.y += bunny.vy;

So if you round the x and y will probably mess things up.  you should use separate variables for  your bunnies position.   which are floats.   and round those to your position..

(dont forget to init your posX and posY otherwise you'll end up with NaN's)

bunny.posX += bunny.vx;
bunny.posY += bunny.vy;
bunny.x = Math.round(bunny.posX);
bunny.y = Math.round(bunny.posY);
