### ISSUE TITLE
is it acceptable to attach thousands of shader programs?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#2029]
This isn't so much a problem with PIXI, more a question about best practice.

I have a particle engine wherein each particle is a 1x1 px `PIXI.Sprite`, added to a `PIXI.Container`. Works great, even with large numbers of pixels thanks to object pooling. I'm considering delegating the particle coloring to a fragment shader rather then doing this on the cpu. The first notion that came to mind was to attach a fragment shader, and set it as a filter on each particle in the container. But this would mean thousands of filters (one per particle) each with its own set of uniforms. Is this reasonably performant or is there a better "PIXI way" to achieve this?

**Comment by GoodBoyDigital** [comment]
yo! You can set the ```tint``` property of the sprite for each particle. There is zero performance hit for using it in webGL :+1:

**Comment by englercj** [comment]
You should try to use tint, if that is insufficient you can create just 1 filter and assign it to the `.shader` property of your particles. If they are all siblings of eachother they will be batched together since they use the same shader.

Ideally though `tint` is the best option since it is basically free!

**Comment by mreinstein** [comment]
I'm currently using tint to color things, yes. Each particle also uses alpha transparency, and additive blending, which Is why I thought moving this to a shader *might* be more performant.

I'm assuming `PIXI.SpriteContainer` is not an option since I'm messing with the alpha of each particle?

**Comment by englercj** [comment]
> Each particle also uses alpha transparency, and additive blending, which Is why I thought moving this to a shader might be more performant.

They are drawn with a shader already, and it handles those things. And you will not be able to use ParticleContainer because of *tint*, alpha works fine in ParticleContainer (if you mark it as dynamic).

**Comment by mreinstein** [comment]
Ah ok. I guess I'm better off just leaving the rendering as-is then. Another question, earlier you mentioned  setting the `.shader` property on a given sprite. What's the different between `.filters` and `.shader` ?

**Comment by englercj** [comment]
`.shader` defines a custom shader to draw the sprite, `.filters` is an array of filters to apply to the sprite that are applied as multiple passes and can render multiple different passes and such.

Siblings with the same shader can be batched, when a shader is changed (like from the default to a custom one) the current batch is flushed.
