### ISSUE TITLE
DisplayContainerObject - width/height property

### ISSUE THREAD

**Issue by benny00100** [pixijs/pixi.js#203]
Request:
Please add the properties width/height to the display container. DisplayObjects in this container are going to be clipped if they coordinates are out the viewable rectangle of the DisplayContainerObject.

**Comment by kennardconsulting** [comment]
Hi there. Thanks for all your great work on Pixi!

The advice to "do clipping via the Masking API" seems at odds with the advice to "avoid Masking on mobile where possible" (see https://github.com/pixijs/pixi.js/issues/2163 and others). Even 3 years later (April 2016) masking seems to add a 10fps hit (per mask!) on an iPad Mini.

What is the advice to render a clipped container on a mobile device?
