### ISSUE TITLE
rotation can't rotate with 1/8 circle (45 degrees)

### ISSUE THREAD

**Issue by supermrji** [pixijs/pixi.js#2039]
Hello,
I have a rotation problem .

Here is my code 
https://jsfiddle.net/supermrji/mzupmrj6/1/

Set rotation to +=0.125 seems can't  rotate exact degrees . 
Does any method can do this thing ?

And does it provide any event to track degrees ?

**Comment by wayfu** [comment]
If you you radians values, it works:

```
var arc = Math.PI * 2 * 0.125;
```

**Comment by supermrji** [comment]
Thanks a lot .
It works !!!
