### ISSUE TITLE
loading the same named asset more than once throws an error

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#2043]
here is the code that gets invoked every time one of my monsters is instantiated:

```
loader = new PIXI.loaders.Loader()
loader.add 'spineSpider', 'assets/spine-spider/skeleton.json'
loader.load (loader, resources) ->
  animation = new spine.Spine resources.spineSpider.spineData
```

this works fine the first time, but subsequent instantiations generate this error:

```
Uncaught Error: Resource with name "spineSpider_atlas" already exists.
```

am I invoking the loader wrong? I've tried also adding a check before loading, to see if the resource is already loaded, but it doesnt seem to work:

```
loader = new PIXI.loaders.Loader()
if loader.resources.spineSpider
   animation = new spine.Spine loader.resources.spineSpider.spineData
else
  # load the animation via .load() ...
```

**Comment by englercj** [comment]
You cannot add a resource to the loader that is already in the loader. If you call `.add()` and the key already exists, it will throw an error.

The check you do should work fine, if not then there may be something going on with the Spine parser. What isn't working about the last code block you posted?

**Comment by mreinstein** [comment]
> What isn't working about the last code block you posted?

the fact that I'm instantiating a new loader each time, yet the error is saying the atlas already exists. maybe something is being cached in the `spine.Spine` object?

It would be really nice if `loader.add 'spineSpider', 'assets/spine-spider/skeleton.json'` did some sort of check of name/uri passed in, and simply load it's data from the cache it exists, rather than throwing an error. I guess that's basically a dumb caching layer, and is maybe more appropriate built on top?

**Comment by englercj** [comment]
> the fact that I'm instantiating a new loader each time, yet the error is saying the atlas already exists. maybe something is being cached in the spine.Spine object?

Oh weird, I didn't even notice you were creating a new loader each time! That is really weird...like...not possible. The error is thrown if the loader checks that `loader.resources[key]` already exists. Its almost like the middleware is running on the wrong instance or something...

Do you have a jsfiddle or such that reproduces?

> Maybe it's more appropriate to build the cache on top of this, but I wouldn't characterize getting an resource that's already loaded as an error.

That is the idea, the resource loader is meant to used to load stuff then be done. If you want to add things and load again you should do `loader.reset()` beforing using it again. You don't necessarily need to create a new one. Do you get the same error even when you do `.reset()`?

**Comment by mreinstein** [comment]
sorry for the reply delay. I've tried loader.reset() but still get an error. my setup code:

```coffeescript
loader = new PIXI.loaders.Loader()
    loader.reset()
    console.log 't1'
    loader.add 'spineSpider', uri
    console.log 't2'
    loader.load (loader, resources) =>
      console.log 't3'
```

Here's the output, after instantiating 2 spiders:

```
t1
t2
t3
t1
t2
Loader.js:236 Uncaught Error: Resource with name "spineSpider_atlas" already exists.Loader.add.Loader.enqueue @ Loader.js:236module.exports @ atlasParser.js:25(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146(anonymous function) @ async.js:157done @ async.js:132_toString @ async.js:32(anonymous function) @ atlasParser.js:42(anonymous function) @ async.js:122_each @ async.js:46async.each @ async.js:121(anonymous function) @ atlasParser.js:40emit @ index.js:89(anonymous function) @ Loader.js:424(anonymous function) @ async.js:154module.exports @ atlasParser.js:9(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146(anonymous function) @ async.js:157module.exports @ atlasParser.js:9(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146(anonymous function) @ async.js:157module.exports @ atlasParser.js:9(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146(anonymous function) @ async.js:157module.exports @ bitmapFontParser.js:67(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146(anonymous function) @ async.js:157module.exports @ spritesheetParser.js:12(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146(anonymous function) @ async.js:157module.exports @ textureParser.js:15(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146(anonymous function) @ async.js:157module.exports @ blob.js:55(anonymous function) @ Loader.js:447async.eachSeries.iterate @ async.js:146async.eachSeries @ async.js:162Loader._runMiddleware @ Loader.js:446Loader._onLoad @ Loader.js:423emit @ index.js:89Resource.complete @ Resource.js:236Resource._xhrOnLoad @ Resource.js:531
```

**Comment by mreinstein** [comment]
after taking some time to reflect on this, I'm not so sure the fact that the atlas already exists is really an error. If the URL and name are already set in the loader, why not just reuse it as-is? basically getting caching for free, with no API changes.

**Comment by englercj** [comment]
It already has caching for free, with no API changes :)

It is possibly true that the loader doesn't need to throw if a resource already is loaded, but it is there for things just like this. You are encountering some bug, that never would've been caught if it just failed to load silently.

I'll look into this soon.

**Comment by mreinstein** [comment]
no rush on my part; i was looking at the daunting list of open bugs on github and figured maybe this one could be closed. : )

**Comment by mreinstein** [comment]
@englercj this is still a problem for me. Do you think you'd have some time to take a look?

**Comment by mreinstein** [comment]
@englercj will you accept a bounty for this?

**Comment by mreinstein** [comment]
https://www.bountysource.com/issues/25657088-loading-the-same-named-asset-more-than-once-throws-an-error

**Comment by englercj** [comment]
Hey @mreinstein, if you can "take back" that bounty go ahead and do it. I owe you for making you wait so long on this one.

Do you have a running example that reproduces this issue?

**Comment by denim2x** [comment]
@mreinstein Please take a look at [this commit](https://github.com/denim2x/resource-loader/commit/818f5992be868e2ffaae27a5794dba5380906bd7) and let me know if it suits your requirements.

**Comment by mreinstein** [comment]
@englercj no worries on the bounty. I'm happy paying that to get the issue resolved, and help fund pixi in some small way. :)

> Do you have a running example that reproduces this issue?

the above setup code should reproduce it, but I can come up with a more complete example if that'd help.

@denim2x I can take a look but check with @englercj and see if this is what he has in mind. It's his module and whatever fix gets made has to be compatible with pixi. Assuming he thinks it's good and assuming it solves the problem I'm cool with releasing funds :)

**Comment by englercj** [comment]
Thanks all, I looked at the PR and I'm not sure it is the right way to solve this issue. It hides the symptom (the throw) but doesn't necessarily address why we are hitting that throw in the first place. If you call `.reset()`, then add a resource, and then immediately get a throw something is seriously broken and we should find out where that failure is.

It could possibly be something wrong in the spine parser, and if we remove the `throw` we will not find things like this in the future.

**Comment by denim2x** [comment]
@mreinstein Try something like this:
```js
require('pixi-spine').atlasParser.enableCaching = false;
```

**Comment by mreinstein** [comment]
@englercj I'm not sure why this problem seems to have vanished. I guess I'll close this for now.

**Comment by englercj** [comment]
Weird! If it comes up again don't hesitate to say something, good luck!

**Comment by mreinstein** [comment]
Yeah man I'm really sorry to waste your time with this crap. I wish I knew why it just stopped happening.

btw still happy to donate that $$ to pixi, what's the best venue to do that?

**Comment by englercj** [comment]
https://www.patreon.com/user?u=2384552&ty=h&u=2384552

Not sure we have a good one-time donation venue...Maybe we should set that up.
