### ISSUE TITLE
Question: Is there an oncomplete function for Sprite.fromImage()?

### ISSUE THREAD

**Issue by Shadowstep33** [pixijs/pixi.js#2044]
Hi, I was unable to find this on my own but perhaps I was just looking in the wrong places. Just as there is a complete event for loaders.Loader is there a way to find out when the image from Sprite.fromImage is loaded? Is there a way to tell when it is rendered?

**Comment by englercj** [comment]
You can monitor the base texture:

```js
var sprite = Sprite.fromImage('...');

if (!sprite.texture.baseTexture.hasLoaded) {
    sprite.texture.baseTexture.on('loaded', ready);
} else {
    ready();
}
```

**Comment by GoodBoyDigital** [comment]
closing as @englercj answer is spot on :+1:
