### ISSUE TITLE
Rendering transparent lines in WebGL Render creates modern art

### ISSUE THREAD

**Issue by BFriedrichs** [pixijs/pixi.js#2046]
```javascript
    var stage = new PIXI.Stage(0x66FF99);
    var renderer = new PIXI.WebGLRenderer(1500, 800);
    document.body.appendChild(renderer.view);
    var line = new PIXI.Graphics();
    line.lineStyle(100, 0x11aabb, 0.5);
    line.moveTo(50, 50);
    line.lineTo(500, 500);
    stage.addChild(line);
    renderer.render(stage);
```

![screenshot from 2015-08-13 14 41 47](https://cloud.githubusercontent.com/assets/2217052/9249916/766eafce-41c9-11e5-8bf6-ca2ef719bc7d.png)

**Comment by thesunlover** [comment]
http://jsfiddle.net/a2oar38g/3/
tested myself in PIXIjs  3.0.7

**Comment by GoodBoyDigital** [comment]
Beautiful, but weird! Does this issue exist in older versions of pixi?

**Comment by stbaer** [comment]
In 3.0.6 not yet:
http://jsfiddle.net/a2oar38g/4/

**Comment by englercj** [comment]
@GoodBoyDigital Didn't you change it to use the complex shader or something recently?

**Comment by stbaer** [comment]
Looks like it started with commit #1863 

Can be seen here: http://jsfiddle.net/a2oar38g/5/

**Comment by wayfu** [comment]
*sigh*

i told you i wasn't sure about committing that, now i feel awful since it seems to have broken ALL the things. exactaly what i *didn't* want to happen :(

**Comment by stbaer** [comment]
@wayfu - i think your commits just shows that there are still other parts of pixi that still need fixing. Would consider that a good thing :)

**Comment by wayfu** [comment]
perhaps :)

i did investigate further and my local copy draws open and closed paths correctly now. more info in this issue: https://github.com/pixijs/pixi.js/issues/1892

**Comment by stbaer** [comment]
+1 for another pull request.

**Comment by englercj** [comment]
> after the last one, i'm not touching the pull request button with a ten foot pole though

Don't say that, all your contributions are greatly appreciated and only serve to make pixi and the community better. Don't be afraid to make mistakes or to be wrong (though in this case you didn't make a mistake, and you were right :))

**Comment by GoodBoyDigital** [comment]
Oops! My bad there. A PR to fix this would be most welcome.

As @englercj says, never be afraid to make a mistake :)

If i had a penny for every one I've made with Pixi i would be a very rich man...

**Comment by wayfu** [comment]
github is currently LITERALLY sapping my will to live. how does anyone use this thing successfully? i am by no means a stupid person but i cannot figure out how to create this motherfucking pull request without including a thousand other changes. i've spent almost TWO HOURS trying to do this. this is not the first time i'm having these issues. *GITHUB I HATE YOU.*

**Comment by wayfu** [comment]
github is actively hostile toward contributing. it's amazing.

**Comment by wayfu** [comment]
this is definitely the last time i let myself be talked into using this pile of shit pull request system, sorry. the negative impact on my quality of life isn't worth it.

**Comment by FlorianLudwig** [comment]
@wayfu is the code somewhere to look at?

**Comment by wayfu** [comment]
#2056

**Comment by joeredfearn** [comment]
Could this be fixed please - we are going to have to sit with 3.0.6 until it is as I am currently working on a project that requires trail rendering :]

Appreciate the hard work!

**Comment by stbaer** [comment]
@joeredfearn - this should be fixed already in dev

**Comment by englercj** [comment]
This should be fixed in the latest dev I will try to get a release out soon.
