### ISSUE TITLE
Interaction documentation missing?

### ISSUE THREAD

**Issue by emilekberg** [pixijs/pixi.js#2048]
I'm looking through the documentation here http://pixijs.github.io/docs/
and i cannot seem to find what events are available for use with the "on" function, like

    var container = new PIXI.Container();
    container.interactive = container.buttonMode = true
    container.on('whatcanbeusedhere', function() { console.log("stuff); });

i don't see anything in container, displayobject, and the eventemitter does not seem to be documented. Am i missing something? 
the ones i've used are click and tap, but i'd like to see what else is available.

**Comment by englercj** [comment]
Sorry, haven't got around to documenting those apparently!

Here they are:

- mousedown
- rightdown
- mouseup
- rightup
- click
- rightclick
- mouseupoutside
- rightupoutside
- mousemove
- mouseover
- mouseout
- touchstart
- touchend
- tap
- touchendoutside
- touchmove

**Comment by englercj** [comment]
These should be good to go!
