### ISSUE TITLE
Removing childs onClick cause errors on the Interaction Manager

### ISSUE THREAD

**Issue by picanteverde** [pixijs/pixi.js#2050]
Consider that you have a group of sprites in a container and in the click handler of any of them you decide to remove the others, like this (not a working code)

```
var i, l =10, sprite,sprites = [],
  stage= new PIXI.Container(),
  texture = new PIXI.texture.fromImage('bunny.jpg'),
  renderer = new PIXI.autoDetectRenderer(),
  handleClick = function(sprite){
    return function(){
      var i,l;
      sprites.splice(sprite.idx,1);
      l = sprites.length;
      for(i = 0; i < l; i += 1){
        stage.removeChild(sprite);
      }
    };
  };

for(i = 0; i < l ; i += 1){
  sprite = new PIXI.Sprite(texture);
  sprite.buttonMode = true;
  sprite.interactive = true;
  sprite.idx = sprites.length;
  sprite.on('click', handleClick(sprite));
  sprites.push(sprite);
  stage.addChild(sprite);
}


```

the Interaction Manager will fail in the processInteractive Method (line: 347) because the displayObject parameter is undefined.
This is caused because in the same recursive method it is storing the value of the lenght of the childs in the container, instead of calculating the length on each step of the "for" (line:364)

```
for (var i = children.length-1; i >= 0; i--) 
```

so in this case one of the child will have the interaction to "remove" the other childs, but this "for" will continue even when the children.length was reduced to one

a posible solution might be to avoid the cache of the length property in the array of childrens

```
for (var i = 0; i < children.length; i += 1) 
```

but that will have a performance penalty for all the interactions that doesn't modify the children length
An alternative solution might be just to add a small check in the processInteractive Method 

```
if(!displayObject)
  {
    return false;
  }

```

**Comment by scottmcdonnell** [comment]
Did you ever come up with a solution?
As a workaround I have a `setTimeout(clickHandler, 0)` to delay the call of the handler until after the loop is completed.

**Comment by GoodBoyDigital** [comment]
Nice! My 2 pence.. lets add the ```if(displayObject){return false}```

**Comment by GoodBoyDigital** [comment]
fixed in dev branch :+1:
