### ISSUE TITLE
ButtonMode glitch

### ISSUE THREAD

**Issue by kittykatattack** [pixijs/pixi.js#2052]
If you mouse-over any interactive elements in the current version of Pixi, the mouse pointer changes to a hand ("pointer" style), and then, a moment later, back to an arrow ("auto" style)

http://pixijs.github.io/examples/index.html?s=demos&f=interactivity.js&title=Interactivity&v=dev

This happens on every browser I've tested: Safari, Firefox, and Chrome.

Is this a bug?

**Comment by brenwell** [comment]
I am having the same issue, I see this was closed, does that mean that there was a solution??

**Comment by kittykatattack** [comment]
Very weirdly, it seems to have been a Mac OS X bug!
After I rebooted my laptop the bug disappeared.... crazy!
