### ISSUE TITLE
V3 Interaction Manager Cursor

### ISSUE THREAD

**Issue by Barnzy** [pixijs/pixi.js#2053]
Hi,

I've been wrangling with the interaction manager and currentCursorStyle. Is the following correct?

```
var renderer = new PIXI.WebGLRenderer(500,500);
var im = new PIXI.interaction.InteractionManager(renderer);

var container = new PIXI.Container();
container.interactive = true;

container.mouseover = function(){
    im.currentCursorStyle = "cursor";
}
```

Doesn't seem to do the trick so thought I would post the question here. Any thoughts on what I'm doing wrong?

**Comment by stbaer** [comment]
This should work: 

```js
var renderer = new PIXI.WebGLRenderer(500,500);
var im = new PIXI.interaction.InteractionManager(renderer);

var container = new PIXI.Container();
container.interactive = true;
container.buttonMode = true;
container.defaultCursor = "move"; //or some othe css cursor style
```

**Comment by Barnzy** [comment]
@stbaer Thank you very much, that's been bugging me for a while now. `buttonMode` did the trick. :+1:

**Comment by xetra11** [comment]
> ```
> var renderer = new PIXI.WebGLRenderer(500,500);
> var im = new PIXI.interaction.InteractionManager(renderer);
> 
> var container = new PIXI.Container();
> container.interactive = true;
> 
> container.mouseover = function(){
>     im.currentCursorStyle = "cursor";
> }
> ```

Hey there,
You created a new instance of the InteractionManager. As I did this all my events were bound/registered twice and therefore were triggered twice. Did that not happen to you, too?
