### ISSUE TITLE
Create dozens of sprites from one image

### ISSUE THREAD

**Issue by Esshahn** [pixijs/pixi.js#2054]
I have a PNG that contains 256 characters, all 8x8, that I need to convert into sprites. Like a pixel font: http://style64.org/file/c64-truetype-v1.0--style.png

Is there a smart way to do this with pixi.js?

**Comment by JiDW** [comment]
Pixi can load bitmapfont generated with BMFont (http://www.angelcode.com/products/bmfont/) or Littera (http://kvazars.com/littera/).

You may want to look at the XML generated and create your own XML based on your PNG. Then use your newly created font like a text.

http://pixijs.github.io/docs/PIXI.extras.BitmapText.html

**Comment by JiDW** [comment]
Alternatively, if you need to use theses sprites more like a spritesheet than a font, you can follow the same idea but look at spritesheets (aka atlas).

Pixi can load Texture Packer json atlas : https://www.codeandweb.com/texturepacker

Once again, check the json of texture packer and create your own. You can then use PIXI.Sprite.fromFrame("nameoftheframe") in your code.

**Comment by englercj** [comment]
Pixi doesn't have any magic to do this for you, unless you use some other tool to generate a file that describes the image for you (like @JiDW mentioned). Otherwise just loop and create the sprite objects.

**Comment by Esshahn** [comment]
Thanks guys for your help.
I guess I might just stick with looping through the image then.
Since I'm a beginner in pixi, is this a right approach?

* load the image into a texture
* begin loop
* get x,y position of 1 char in the picture
* create a new 8x8 pixel texture
* place the big texture into the small texture and move it by the x and y position
* put this small texture onto a sprite
* end loop

**Comment by JiDW** [comment]
There's two things in PIXI : BaseTexture and Texture. One BaseTexture can produce multiple Texture object.

BaseTexture and Texture are cached inside PIXI.utils.BaseTextureCache and PIXI.utils.TextureCache.

You should load your image, you will get a BaseTexture (and a Texture, but whatever). You can then loop and create more Texture objects from your BaseTexture with the correct arguments to frame your  basetexture.

**Comment by JiDW** [comment]
I should add that to make it easier to use, you can then add your newly created texture to the PIXI cache thanks to PIXI.Texture.addTextureToCache(texture, id).

This will allow you to create a Sprite like this : var sprite = PIXI.Sprite.fromFrame("my_id_in_cache");

It is much easier than to manually keep references to your textures.

**Comment by Esshahn** [comment]
Thank you!
I guess I have to study documentation more as this doesn't make too much sense for me right now.

**Comment by GoodBoyDigital** [comment]
closing this for now as it seems to have run its corse :+1:
