### ISSUE TITLE
RenderTexture memory leak

### ISSUE THREAD

**Issue by alebianco** [pixijs/pixi.js#2058]
I spot a memory leak with the RenderTexture class (and possibly Texture class)

When destroying a texture generated through RenderTexture, directly or through cacheAsBitmap/tint/etc, a couple of listeners are left behind and they'll keep the detached canvas used for rendering in memory.

Also when changing the texture property of a Sprite, a listener for the update event (used internally) is left behind, leading to more leaks. This happens even when not using RenderTexture of course. (maybe I should file a separate issue?)

Here's a test showing the issue and my current workarounds https://jsfiddle.net/alebianco/8btvc0mL/

**Comment by GoodBoyDigital** [comment]
this is all good in v4 👍
