### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by FlamesoFF** [pixijs/pixi.js#2059]
Where is the actual documentation?
Because oficial documentation looks outdated. For example, I using PIXI.loaders.Resource. But nor here: http://pixijs.github.io/docs/PIXI.loaders.html, nor here: http://www.goodboydigital.com/pixijs/docs/modules/PIXI.html is no relevant documentation about loaders.
Where I can find normal documentation?

**Comment by englercj** [comment]
Because the loader is not implemented in pixi, it is an external library:

https://github.com/englercj/resource-loader

The latest pixi.js docs are here:

http://pixijs.github.io/docs/
