### ISSUE TITLE
Draw crashed image when use trim/crop Spine atlas

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#2061]
hi.

i'm using 2.2.9 usefully,  . thx a lot first;

i can see wired image of spine when  load from atlas for spine with packed images by crop/trim

wrong position,
wrong scale

it seems to be between  spine and pixi

what can i do for this?

thx a lot

**Comment by englercj** [comment]
Do you experience the same issues on v3? I want to say those issues have been fixed.

**Comment by SeminYun** [comment]
thx, 

i'm trying by v3..

but v3 hasn't Spine in v3 default lib

how can i add spine lib into v3

**Comment by SeminYun** [comment]
it looks same with v3 and pixi-spine rencenly version

**Comment by englercj** [comment]
Cool, I would post on the pixi-spine repository as it is likely an issue with that plugin.

Thanks for taking a look!

**Comment by SeminYun** [comment]
thx.

this is very important for performance.

result of test is improved 20-30% on FPS although sprites is broken.

my spine draw 30 sprite at once and texture has 1024*1024 if not use trim/crop

if use trim/crop ,it has 512*512 texture

if we can use trim/crop, we get good performance for using spine with v3 or other pixi

thx a lot always..

**Comment by englercj** [comment]
Yeah, should definitely be supported. Make sure to open an issue on the pixi-spine plugin repo:

https://github.com/pixijs/pixi-spine/issues

Thanks!

**Comment by seahorsevn** [comment]
I got the same problem. I tried to use the pixi-spine.js from pixi example. This issue has gone.
https://github.com/pixijs/examples/tree/gh-pages/_site/js/plugins
