### ISSUE TITLE
Documentation for npm install is incorrect

### ISSUE THREAD

**Issue by euangoddard** [pixijs/pixi.js#2063]
On the npm page for PIXI, it states:
```
var renderer = pixi.WebGLRenderer(800, 600);
```

This should be:

```
var renderer = new pixi.WebGLRenderer(800, 600);
```

It took me a while to diagnose why this code wasn't working. I can't obviously see where this example is generated from. If you can point me in the right direction I'll fix it and submit a pull request.

**Comment by stbaer** [comment]
I guess you went to the wrong pixi project on npm.

https://www.npmjs.com/package/pixi.js

**Comment by euangoddard** [comment]
My bad :( It would be helpful if the other could be removed, but I guess that out of your hands

**Comment by englercj** [comment]
@euangoddard Unfortunately the npm registry dsoesn't "remove" packages, even "unpublished" packages tend to show up.

It does say in the top of the `pixi` package that it is deprecated and you should use `pixi.js` though.

**Comment by euangoddard** [comment]
@englercj, thanks for the clarification. I noticed that when @stbaer pointed out my mistake. I was very keen to start using pixi.js and skipped ahead to the getting started as soon as I'd "found" the package on NPM. I don't think you could do much more to make it clear!

**Comment by englercj** [comment]
I also marked it as "deprecated" in the registry, so if you install now it will give you a warning saying to use "pixi.js" instead.

**Comment by euangoddard** [comment]
:+1:

**Comment by drkibitz** [comment]
Thanks @englercj :+1:
