### ISSUE TITLE
Possible Memory Leak with generateTexture

### ISSUE THREAD

**Issue by marteiro** [pixijs/pixi.js#2064]
Hi There,

I'm experiencing some memory leaks in 3.0.7 and i found that TextureCache and BaseTextureCache are accumulating textures. 

After some googling I've found that it is possible to destroy textures manually in booth cases and that seems to solve the issue. 

But considering that many of the textures are being generated dynamically using "generateTexture" i'm thinking that maybe i'm doing something wrong. 

The question is: Do I really need to keep track off all generated textures so i can destroy them manually, or do PIXI knows somehow what are the unreachable textures and should be destroyed?

I'm also noticing some Sprites that uses "gereneteTexture" as input are not destroying their relative texture even after they and it's parents are removed.... Is this the expected behavior?

Thanks in advance,

Marcelo

**Comment by alebianco** [comment]
FWIK, Pixi keeps track of the generated texture in case of a context loss, so it can re-upload your texture in the video memory, so yes, keeping track of it is necessary.
As such, the accumulation is not a leak per se. It's your duty to destroy the textures (don't forget text fields) you don't need anymore.
There's however a leak, check issue #2058

**Comment by photonstorm** [comment]
It's worth adding that if your game is running under Canvas that every single call to `generateTexture` will create a new canvas dom element (every single new Text object you create does the same too). 

These are not pooled or recycled by Pixi, and equally are not removed from the dom either should the BaseTexture be destroyed. So if you do it a _lot_ you'll see the dom node count go nuts over time.

We implemented a [PIXI.CanvasPool](https://github.com/photonstorm/phaser/blob/master/src/pixi/utils/CanvasPool.js) in Phaser in order to address this. It's not designed for Pixi 3 but the code is there and open if you want to take a look and maybe re-purpose it for yourself.

**Comment by alebianco** [comment]
beside pooling, which could be interesting to implement also on pixi3, i think the canvases are actually removed and disposed once the text/sprite is destroyed. Maybe not right now, because of the leak, but once that's patched they should go away nicely. I created a jsfiddle to test it http://jsfiddle.net/alebianco/8btvc0mL/

**Comment by englercj** [comment]
@alebianco PRs welcome :)

**Comment by alebianco** [comment]
@englercj one at the time :) i will possibly get round to work on this one as well, but i don't know all the systems that well yet

**Comment by photonstorm** [comment]
@alebianco like I said it only manifests in the Canvas renderer. Your test uses the WebGL renderer with a RenderTexture, which doesn't use an internal CanvasBuffer. If I profile a large volume of calls to `generateTexture` I can see the node count increase exponentially. If the Sprite is destroyed and the baseTexture with it, it mitigates it a bit (I can see sporadic gc clears flushing them out), but a common requirement is to not actually delete the Sprite but to keep re-generating a texture based on something (like a Graphics update) which is when it bites most.

Even so, it's unrelated to the memory leak and doesn't even happen in WebGL mode.

**Comment by marteiro** [comment]
Thanks for all the replies folks...

In this case we are using Cocoons and WebGL Renderer....

After reading PIXI's source code, i've found that when you "destroy(true)" a container it will also destroy all it's children:
```javascript
Container.prototype.destroy = function (destroyChildren)
{
    DisplayObject.prototype.destroy.call(this);

    if (destroyChildren)
    {
        for (var i = 0, j = this.children.length; i < j; ++i)
        {
            this.children[i].destroy(destroyChildren);
        }
    }

    this.removeChildren();

    this.children = null;
};
```
I imagined that this would be enough to get all sprites and it's textures destroyed because the destroy function in the Sprite class also destroys the base texture:

```javascript
Sprite.prototype.destroy = function (destroyTexture, destroyBaseTexture)
{
    Container.prototype.destroy.call(this);

    this.anchor = null;

    if (destroyTexture)
    {
        this._texture.destroy(destroyBaseTexture);
    }

    this._texture = null;
    this.shader = null;
};
```

However when i check PIXI.utils.PIXI.utils.TextureCache and PIXI.utils.BaseTextureCache i still can see that all textures are loaded....

I already managed to free a lot of memory by manually deleting textures from assets i've loaded... but there is always some memory leaking ....

I have many leves of containers inside each other ... what would be the proper way to clean everything from the top container?

Using Instruments i've also noticed that "All Heap & Anonymous VM" keeps increasing the number of object and memory event if the project only a empty PIXI project. There is no leak If i remove the render() function from the requestAnimationFrame() though...

thanks for your patience guys....

Marcelo

**Comment by marteiro** [comment]
To solve my particular problem here i've changed the source to feet my needs. Adding a second parameter to the destroy function of the Container class. So if it finds a Sprite, which receive two parameter, the second parameter should server to also destroy de baseTexture...

```javascript
Container.prototype.destroy = function (destroyChildren, segundo)
{
    DisplayObject.prototype.destroy.call(this);

    if (destroyChildren)
    {
        for (var i = 0, j = this.children.length; i < j; ++i)
        {
            this.children[i].destroy(destroyChildren, segundo);
        }
    }

    this.removeChildren();

    this.children = null;
};
```

It seems to work nice for this special case... 

Do you guys believe it would be considerable to have a features to destroy everything, including textures, from the top object?

Thanks again
Marcelo

**Comment by marteiro** [comment]
Anyone experiencing same thing with WebGl?

**Comment by erinnovations** [comment]
Yes, we are experiencing the same issue.

**Comment by GoodBoyDigital** [comment]
Think this is sorted in v4 - closing for now. If this is still an issue - a fiddle would be super handy. 👍
