### ISSUE TITLE
Cannot instantiate CanvasRenderer due to undefined initPlugins

### ISSUE THREAD

**Issue by heyscam** [pixijs/pixi.js#2065]
A super simple test case with Pixi 3.07 coming from cdnjs:

http://jsfiddle.net/Lcxehrza/

Instantiating a CanvasRenderer seems to result in an undefined function error for initPlugins. Tested in Safari and Chrome on OS X.

**Comment by stbaer** [comment]
Looks like you forgot *new*

http://jsfiddle.net/Lcxehrza/10/
