### ISSUE TITLE
clearBeforeRender has no effect in webgl?

### ISSUE THREAD

**Issue by earslap** [pixijs/pixi.js#2066]
Not sure I'm going the wrong way with this but it definitely works different compared to canvas renderer.

I want to stamp sprites to scene and want them to remain on the screen after I remove them from the scene graph. This works just fine with canvas renderer but webgl somehow cleans the screen each frame.

Demo:

Canvas (expected behaviour): https://jsfiddle.net/a2oar38g/6/
WebGL (everything clears at each frame): https://jsfiddle.net/a2oar38g/7/

**Comment by earslap** [comment]
Ok, what I found is that the flag must be set during renderer creation as an option, and you have to have preserveDrawingBuffer: true at the same time to get the same behaviour in webgl. See: https://jsfiddle.net/pf3gsecp/

This one behaves as expected.

**Comment by mreinstein** [comment]
@earslap can this issue be closed?

**Comment by englercj** [comment]
Adding a doc label, since we should update the docs with that info.

**Comment by mreinstein** [comment]
Oh maybe I misunderstood the ticket, sorry.  The docs for renderTexture http://pixijs.github.io/docs/PIXI.RenderTexture.html#render  has a `clear` argument, which sounds very similar.

Another issue with the docs is the example usage of renderTexture is wrong:

```javascript
var renderTexture = new PIXI.RenderTexture(800, 600);
```

doesn't pass in renderer as first argument.

**Comment by cawoodm** [comment]
I'm seeing no effect when I try to prevent PIXI from clearing the canvas:
```
renderer = new PIXI.CanvasRenderer(400, 400);
renderer.options.clearBeforeRender = false;
renderer.options.preserveDrawingBuffer  = true;
```
I draw some custom objects onto the canvas then call renderer.render() and it clears my stuff away.

**Comment by cawoodm** [comment]
I'm using the latest stable build of pixi.js from: https://pixijs.download/release/pixi.js and it's got this bug that the canvas is cleared even though renderer.clearBeforeRender = false and renderer.preserveDrawingBuffer  = true
When I use https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.5.5/pixi.js it works as expected though both files say they are 4.5.5

**Comment by ivanpopelyshev** [comment]
preserveDrawingBuffer does not change after renderer was created, that's webgl limitation. You have to pass it to constructor.

**Comment by cawoodm** [comment]
I think I was mistaken about the bug. I have it working now.
