### ISSUE TITLE
Uncaught TypeError: baseTexture.once is not a function

### ISSUE THREAD

**Issue by assertchris** [pixijs/pixi.js#2067]
<img width="633" alt="screen shot 2015-08-26 at 11 11 59 pm" src="https://cloud.githubusercontent.com/assets/200609/9492022/e4978f42-4c47-11e5-99bc-dd403e5442c8.png">

Steps to reproduce:

```js
"dependencies": {
    "pixi.js": "^3.0"
},
```

```js
var player_texture = new PIXI.Texture("img/player.png");
var barrel_texture = new PIXI.Texture("img/barrel.png");

var player_sprite = new PIXI.Sprite(player_texture);

var player = new Player(
    player_sprite,
    window.innerWidth * 2/4,
    200
);

var barrel_sprite1 = new PIXI.Sprite(barrel_texture);
var barrel_sprite2 = new PIXI.Sprite(barrel_texture);

var barrel1 = new Box(
    barrel_sprite1,
    window.innerWidth * 1/4,
    152
);

var barrel2 = new Box(
    barrel_sprite2,
    window.innerWidth * 3/4,
    248
);

stage.addChild(player_sprite);
stage.addChild(barrel_sprite1);
stage.addChild(barrel_sprite2);
```

**Comment by englercj** [comment]
`PIXI.Texture` does not take a string as the first parameter to its constructor, it takes a `PIXI.BaseTexture`.

http://pixijs.github.io/docs/PIXI.Texture.html

**Comment by assertchris** [comment]
Oh gosh, I am dumb. No idea where I got that idea from. Thanks for setting me straight.

**Comment by ogrotten** [comment]
> `PIXI.Texture` does not take a string as the first parameter to its constructor, it takes a `PIXI.BaseTexture`.
> 
> http://pixijs.github.io/docs/PIXI.Texture.html

Link is now broken. Where did the info go?
