### ISSUE TITLE
cacheAsBitmap fails on CanvasRenderer

### ISSUE THREAD

**Issue by xill** [pixijs/pixi.js#2068]
Not sure what goes wrong here, but cached sprite doesn't seem to be drawn at all when it is given a position and using the CanvasRenderer. Works fine on WebGL.

Here's something that reproduced it for me on pixi 3.0.6 and 3.0.7.
http://jsfiddle.net/cz985yax/

**Comment by davidfig** [comment]
Any update on this bug? I'm running into it as well when using the CanvasRenderer instead of the WebGLRenderer.

**Comment by GoodBoyDigital** [comment]
looks good to me now? Closing for now 👍
