### ISSUE TITLE
Rewrite Interaction Manager

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#2071]
I think it becoming aparant that the interaction manager is due for an update. There are many bugs and feature requests that need to be taken care of:

https://github.com/pixijs/pixi.js/issues?q=is%3Aopen+is%3Aissue+label%3A%22Interaction+Manager%22

This issue is to track completion of a new interaction manager that fixes all (or at least most) of these issues.

---

I'm pretty busy with work right now, but I have opened a bounty on this issue. If we reach the goal then I will make time to complete this feature. You can post to the bounty on [Bountysource](https://www.bountysource.com/issues/26281649-rewrite-interaction-manager).

**Comment by tobireif** [comment]
Just in case it's of potential use for the InteractionManager incl. Pointer Events incl. "pointerup":

Perhaps one of these libs could be used / forked / built on / looked at?

https://github.com/Deltakosh/handjs
https://twitter.com/Inateno/status/641677865038315520

https://github.com/Rapid-Application-Development-JS/Pointer

**Comment by drkibitz** [comment]
Where's this work being done? Fork, feature branch, privately?

**Comment by englercj** [comment]
It isn't being done, we haven't reached the goal I set or gotten close enough for me to have the time to start :)

**Comment by cvissie** [comment]
Also another thing we might need to add to this.

enabled=false

Our project has HTML interaction capabilities as well as PIXI interaction capabilities.

Sometimes I would like to disable PIXI interaction and re-enable it later.

The way I have implemented it is by simply adding a this.enabled=true field in InteractionManager and then checking for it in the update method as well as the processInteractive method.
