### ISSUE TITLE
Rendering to RenderTexture does omit sprite filter

### ISSUE THREAD

**Issue by pixartist** [pixijs/pixi.js#2074]
I'm rendering several (hundreds) of tiles to a RenderTexture. The sprite I'm using has a filter and I'm using a frame to select a tile on the sprite. For some reason, after a certain number of rendering operations the filter stops being used:
![bug](https://cloud.githubusercontent.com/assets/628738/9582678/1f3023f4-5007-11e5-8729-da4daaaa7bde.jpg)
Here I'm using desaturate with a ColorMatrix filter. As you can see, only the first row of tiles is rendered with the filter. When I redraw the sprites, none will make use of the filter.

Rendering code:

    var loc = tileSpriteLocations[type];
    this.tilemap.frame = { x: loc.x * tileSpriteSize, y: loc.y * tileSpriteSize, width: tileSpriteSize, height: tileSpriteSize };
    var mat = new PIXI.Matrix();
    mat.scale(this.tileSize / tileSpriteSize, this.tileSize / tileSpriteSize);
    mat.translate(x * this.tileSize, y * this.tileSize);
    this.tilemapSprite.filters[0].desaturate();
    this.tex.render(this.tilemapSprite, mat, false);

**Comment by englercj** [comment]
Can you share a running example? The code you posted isn't enough to see whats going on, looks like in that code you are rendering only a single sprite.

**Comment by pixartist** [comment]
hmm well, the code I have is integrated with a server and I can't really simply share all of that. I can add some of the code here though:

constructor:

    function World(index, requestFunc)
    {
    this.renderer = new PIXI.autoDetectRenderer(1, 1);
    this.renderer.backgroundColor = 0x000000;
    this.graphics = new PIXI.Graphics();
    this.tilemap = PIXI.Texture.fromImage('Images/tilemap.png');
    this.tilemapSprite = new PIXI.Sprite(this.tilemap);
    this.tilemapSprite.filters = [new PIXI.filters.ColorMatrixFilter()];
    this.tilemapSprite.anchor.set(0, 0);
    this.cameraHeight = 50;
    this.index = index;
    this.req = requestFunc;
    $('#content').append(this.renderer.view);
    this.handleResize();
    this.req("/worldSelect", 'GET', { world: this.index }, this.init.bind(this));
    document.onkeypress = this.handleKeys.bind(this);
    window.onresize = this.handleResize.bind(this);
    this.render();
    }

render loop:

    World.prototype.render = function()
    {
    this.renderer.render(this.texSprite);
    requestAnimationFrame(this.render.bind(this));
    }

draw to texture method:

    World.prototype.drawTileRect = function(type, x, y, tint)
    {
        //tint = tint || [1, 1, 1];
        //tint = PIXI.utils.rgb2hex(tint);
        var loc = tileSpriteLocations[type];
        this.tilemap.frame = { x: loc.x * tileSpriteSize, y: loc.y * tileSpriteSize, width: tileSpriteSize, height: tileSpriteSize };
        var mat = new PIXI.Matrix();
        mat.scale(this.tileSize / tileSpriteSize, this.tileSize / tileSpriteSize);
        mat.translate(x * this.tileSize, y * this.tileSize);
        this.tilemapSprite.filters[0].desaturate();
        this.tex.render(this.tilemapSprite, mat, false);
    }

Everything works fine, except the filter.

**Comment by englercj** [comment]
Oh I see, you are using a single sprite and repositioning it for each tile to be drawn to the texture. Hmmm, I'll look into this thanks for the info.

**Comment by pixartist** [comment]
Is there a better way to do this (working with texture tiles) ? ;)

**Comment by englercj** [comment]
I generally create a sprite per tile and stick them in a container, if it ever becomes a performance issue you can use `cacheAsBitmap`, but it rarely does since all those sprites are batched together into a single draw call anyway.

**Comment by pixartist** [comment]
hmmmm,,, I'll look into that.

**Comment by pixartist** [comment]
I don't understand how your method works with a tilemap. Since the frame is set on a per-texture basis, wouldn't I need to load the same texture hundreds of times ?

**Comment by englercj** [comment]
No, if they share a BaseTexture object they will all be in a single draw call. There is no texture swapping. You would create many textures and many sprites, but only 1 BaseTexture.

This also implies you need to put your tilesheet into a single image file.

**Comment by pixartist** [comment]
Solved it by using http://twgljs.org ...

**Comment by GoodBoyDigital** [comment]
looks resolved! 👍
