### ISSUE TITLE
Dropshadow filter broken (tested with Win7, WebGL, FF, Chrome, UC Browser)

### ISSUE THREAD

**Issue by X-PRESSIVE** [pixijs/pixi.js#2075]
Dropshadow filter has no effect when applied to a sprite. Tested on Win7 (WebGL) on Firefox, Chrome and UC Desktop browsers. None of them shows a drop shadow effect.

Same issue with a couple of other built-in filters. Only a few of them seem to work (blur filter works, for example -glow filter doesn't work).

Graphics card: Radeon HD 6800 Series. Pixi V3.

Code example: https://jsfiddle.net/5goztwcs/3/

**Comment by louisatome** [comment]
I had the same problem but I think the cause is that the drop shadow filter only works if there is something below to show the shadow. As your renderer is transparent, the shadow of your object cannot be rendered.

See : https://jsfiddle.net/dLt1Lrmd/1/

**Comment by GoodBoyDigital** [comment]
Moved filters to pixi-filters 👍
