### ISSUE TITLE
BitmapText getBounds is not refreshed if the text is changed

### ISSUE THREAD

**Issue by sergebat** [pixijs/pixi.js#2081]
```
var bitmapText = new PIXI.extras.BitmapText("text using a fancy font!", {font: "35px Desyrel", align: "right"});
bitmapText.text = "New text";
```

`bitmapText.getLocalBounds` after this will return correct value, but `bitmapText.getBounds` will not. 

Culprit is that getBounds base implementation, it seems, is not overwritten, and does not call `this.validate()`, while getLocalBounds does:
https://github.com/pixijs/pixi.js/blob/34cd01eb0f204848972de325b1b85c0b6f7b8c8e/src/extras/BitmapText.js#L351-L361

Base getBounds implementation is not relying on getLocalBounds, thus it still returns incorrect value:
https://github.com/pixijs/pixi.js/blob/34cd01eb0f204848972de325b1b85c0b6f7b8c8e/src/extras/BitmapText.js#L351-L361

Sorry, creating full-blown JSFiddle requires setting up bitmap font somewhere and bit hard :). Let me know if above is not sufficient to reproduce, and I'll create working example.

**Comment by sergebat** [comment]
I thought I'd chime in to confirm that the bug is still there in PIXI v3.0.8. Note that the width of getBounds() is different from getLocalBounds() of the unscaled text. 

![image](https://cloud.githubusercontent.com/assets/5421460/11474560/cc7b51d6-9789-11e5-9bbd-bc279758a1c6.png)

**Comment by GoodBoyDigital** [comment]
Fixed in v4 👍
