### ISSUE TITLE
Possible new way of treating anchor

### ISSUE THREAD

**Issue by m93a** [pixijs/pixi.js#2082]
I'm quite new to Pixi.js (I have to admit it's a pretty good library) and I was surprised that only sprites support the `anchor` property, so I wrote a little utility script – you can find it [here](https://gist.github.com/m93a/1dc1f46114c92664a7bc). When I finished it, I found out it behaves differently form the already existing `Sprite::anchor`.
That's because my version computes `pivot` from `anchor` and vice versa. Furthermore, it remembers the _default property_ (one of the pair `pivot, anchor`) which remains unchanged when you change the size of the `DisplayObject`. That means: if you set anchor to the centre, set it as default, and then resize the object, it still stays centred.

You shouldn't implement my code directly, because it's probably very slow – I use a lot of getters and setters – but it's the simplest way to do it without modifying the library itself. Or maybe you don't want to implement it at all because it's not really needed in the library. But I thought that it's worth publishing.

Regards,
m93a.

**Comment by GoodBoyDigital** [comment]
Anchor is basically for texture alignment. Adding anchors to objects like containers would be a feature we could add but would sit out of core pixi. A pixi-layout module or somthing like that. The reason we do not implement this in the core is that we would need to add lots of extra runtime checks. Hope that makes sense! :+1:
