### ISSUE TITLE
spine skeleton animation problem

### ISSUE THREAD

**Issue by yushli** [pixijs/pixi.js#2084]
When using spine skeleton animation, there is some noticeable space between two skeletons. 
![qq20150907170245](https://cloud.githubusercontent.com/assets/1681453/9713345/6f41b336-5583-11e5-849f-a0ce1cfba780.png)
![qq20150907170214](https://cloud.githubusercontent.com/assets/1681453/9713346/73f763d0-5583-11e5-89c7-7f6e81ad56db.png)
The following are the spine files:
{
"bones": [
	{ "name": "root" },
	{ "name": "bone", "parent": "root" },
	{ "name": "l_head", "parent": "bone" },
	{ "name": "r_head", "parent": "bone" }
],
"slots": [
	{ "name": "body", "bone": "bone", "attachment": "lose_chicken" },
	{ "name": "s_l_head", "bone": "l_head", "attachment": "lose__hand" },
	{ "name": "s_r_head", "bone": "r_head", "attachment": "lose__hand" }
],
"skins": {
	"default": {
		"body": {
			"lose_chicken": { "width": 58, "height": 57 }
		},
		"s_l_head": {
			"lose__hand": { "x": -47.99, "y": 7.99, "width": 59, "height": 54 }
		},
		"s_r_head": {
			"lose__hand": { "x": 40.99, "y": 18, "scaleX": -1, "width": 59, "height": 54 }
		}
	}
},
"animations": {
	"animation": {
		"bones": {
			"r_head": {
				"rotate": [
					{ "time": 0.1666, "angle": -22.58 },
					{ "time": 0.3333, "angle": 0 }
				]
			}
		}
	}
}
}

![skeleton](https://cloud.githubusercontent.com/assets/1681453/9713421/c8f4f1fe-5583-11e5-932a-f6369c61679e.png)

**Comment by ivanpopelyshev** [comment]
ok, next time post it here: https://github.com/pixijs/pixi-spine/issues . Thank you, I'll test it :)

**Comment by ivanpopelyshev** [comment]
Do you use pixiv2 or v3?

**Comment by ivanpopelyshev** [comment]
Can you please export "chicken.atlas" file too?

**Comment by yushli** [comment]
Thanks for the quick response. Next time I will post to pixi-spine. 

skeleton.png
format: RGBA8888
filter: Linear,Linear
repeat: none
lose__hand
  rotate: false
  xy: 54, 8
  size: 52, 47
  orig: 59, 54
  offset: 1, 4
  index: -1
lose_chicken
  rotate: false
  xy: 2, 2
  size: 50, 53
  orig: 58, 57
  offset: 3, 3
  index: -1

**Comment by yushli** [comment]
And I use pixiv3. pixiv2 also has this problem I think.

**Comment by ivanpopelyshev** [comment]
Yes, now I can reproduce it.

**Comment by yushli** [comment]
Good. Now look forward to your fix. :)

**Comment by ivanpopelyshev** [comment]
Can you give me .spine file too? I need to export it with different settings to determine whats wrong.

**Comment by ivanpopelyshev** [comment]
Ok, try pixi-spine 1.0.5. This one has fixed it: https://github.com/pixijs/pixi-spine/commit/a7a28e080db900ac909891c2266a48c94078f4d1
