### ISSUE TITLE
SpriteRenderer excepts on WebGLRenderer destruction

### ISSUE THREAD

**Issue by aschampion** [pixijs/pixi.js#2086]
`WebGLRenderer.prototype.destroy` calls `destroyPlugins`, which due to bc54b1b73ae8c2f09a1752bcb61201d1fcf5476a has  `SprireRenderer.prototype.destroy` call `ObjectRenderer`'s `destroy` method on itself, which is actually `WebGLManager.prototype.destroy`. This sets `renderer` to `null`, which causes an exception [here](https://github.com/pixijs/pixi.js/blob/f5abaa7060bd1347cfd0506ab2b60db9fc8c9f19/src/core/sprites/webgl/SpriteRenderer.js#L451).

[Simplified jsFiddle](http://jsfiddle.net/ho6qdzxk/3/) from #1968 with pixi compiled from f5abaa7060bd1347cfd0506ab2b60db9fc8c9f19.

I may take a stab at PRing fixes for this and #1968 because I need renderers to destroy cleanly.

**Comment by englercj** [comment]
Ah, nice catch; sorry about that. Thanks for the coming PR!
