### ISSUE TITLE
Batching PIXI.Graphics primitives?

### ISSUE THREAD

**Issue by redwoodfavorite** [pixijs/pixi.js#2090]
I am considering Pixi.js for some 2D visualization work I am doing and was curious about performance.  Its seems like 'smart-batching' is implemented for Sprites (which is awesome).  Is there any pathway to batching the PIXI.Graphics primitive shapes?

Maybe if there was a way to designate that a shape was static?  Is this something already implemented?  If not, I'd love to help on a feature like this.  Then you could potentially use PIXI as a renderer for some REALLY large datasets in D3!

**Comment by englercj** [comment]
You can use cacheAsBitmap, or renderTextures to cache static shapes to a texture so they don't have to be redrawn each time.

**Comment by GoodBoyDigital** [comment]
Hi there! static shapes are batched if they are in the same graphics object. In v4 rectangles are batched and graphics should be a little faster in general too.

As @englercj mentioned too, cacheAsBitmap could help you  out here too.
