### ISSUE TITLE
generateTexture with wrong frame?

### ISSUE THREAD

**Issue by ThomasDeutsch** [pixijs/pixi.js#2092]
generateTexture on a 1px Pixi.Graphics line - will result in a 2px line.

[see the jsfiddle](https://jsfiddle.net/cLgo0b7w/18/)

At the moment there are two solutions i have found:
1. setting the texture.frame manually by    texture.frame = new PIXI.Rectangle(0,0,200,1);
2. draw a line that is 0.9999999 px thick.

**Comment by GoodBoyDigital** [comment]
think this may be fixed in v4!
