### ISSUE TITLE
MovieClip destroy performance issue

### ISSUE THREAD

**Issue by kozakluke** [pixijs/pixi.js#2096]
hello,
clear situation... I have MovieClip, and try destroy it.. but when I try console.log update method in MovieClip i see this method is still update.. so I think method Ticker.prototype.remove don't work well... don't stop dispatch update callback..
How I can stop update MovieClip?
Luke.

**Comment by englercj** [comment]
I'm not sure what you mean, can you give me a running example?

**Comment by kozakluke** [comment]
Hello, I found problem.. I use eventemitter3  version ^0.1.6, this version have a bug..
now I use 1.1.1 version and works well.
Thanks!
