### ISSUE TITLE
PIXI.Graphic changes lineStyle on its own.

### ISSUE THREAD

**Issue by schoening** [pixijs/pixi.js#2105]
The line thickness changes without me changing it.. I find that very odd...

I have made an example:

http://jsfiddle.net/11mysh26/

I also don't understand why I have to set the thickness for every line, wouldn't it be more "canvas like" to safe those parameters?

There are some "debugging" circles added to the example because I am trying to figure out why the lines don't start at the start positions (green circles) but rather at the first update position (red circles).

**Comment by whizzkid** [comment]
The lineStyle isnt changing. you're drawing half of the outer line outside of your canvas.

change the first set of coordinates to:

{ x: 5, y: 5, start: true }, 
	{ x: 395, y: 5 }, 
	{ x: 395, y: 395 }, 
	{ x: 5, y:  395 }, 
	{ x: 5, y: 5, end: true },

And you'll see :)

**Comment by whizzkid** [comment]
and about the update bit.. you have 2 functions
onStart() which draws nothing..
onUpdate() which draws stuff

so the first time onStart gets called, (not onUpdate)  afterwards  onUpdate gets called 

you need to draw something in your onStart()  or call onStart AND on onUpdate when you begin.

I added this to your onStart() and it works like you were expecting:

blueprint.lineStyle(10, 0xffffff);
blueprint.lineTo( this.x, this.y );


So, no pixi errors here :)

**Comment by schoening** [comment]
wow that first one is a real groaner! Thank you so much for fixing that for me hahaha :)

And thanks for the second one too. I knew that wasnt a pixi error, I was kinda hoping someone more skilled would help me out there tho :D thank you!

**Comment by whizzkid** [comment]
No problem :)
