### ISSUE TITLE
is tint incompatible with blendMode?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#2108]
test code:

```coffeescript
  view = new PIXI.Container()
  block = PIXI.Sprite.fromImage 'assets/block.png'
  block2 = PIXI.Sprite.fromImage 'assets/block.png'
  block2.x = 20
  block2.y = 20
  block2.blendMode = PIXI.BLEND_MODES.ADD

  view.addChild block
  view.addChild block2
```

works as expected: 
<img width="220" alt="screen shot 2015-09-20 at 5 34 15 pm" src="https://cloud.githubusercontent.com/assets/718067/9983744/f5848934-5fbd-11e5-849a-9272e711d1f7.png">

however, when I set tint on either of the sprites:
```coffeescript
  view = new PIXI.Container()
  block = PIXI.Sprite.fromImage 'assets/block.png'
  block2 = PIXI.Sprite.fromImage 'assets/block.png'
  block2.x = 20
  block2.y = 20
  block2.tint = 0xFF0000
  block2.blendMode = PIXI.BLEND_MODES.ADD

  view.addChild block
  view.addChild block2
```

now additive blending doesn't seem to work:

<img width="214" alt="screen shot 2015-09-20 at 5 35 55 pm" src="https://cloud.githubusercontent.com/assets/718067/9983748/1fc19c5a-5fbe-11e5-989a-b1f958624140.png">

Have I stumbled upon a bug or is this an expected limitation of tint + additive blending?

**Comment by englercj** [comment]
Hey @mreinstein just got back from a conference. I'll try to look at this this weekend. Both should work fine.

**Comment by mreinstein** [comment]
Thanks man, I appreciate it!  I haven't given up on pixi and moved to flash yet.

**Comment by mreinstein** [comment]
@englercj do you think you'll have some time to look at this? I'm sorry to be a pest

**Comment by englercj** [comment]
Sorry @mreinstein with Blizzcon coming up I haven't had time to do anything more than just post replies.

@GoodBoyDigital Can you look into this @mreinstein has been waiting for a while.

**Comment by GoodBoyDigital** [comment]
interesting! Is this a canvas only issue? or webGL to?

cheers!

**Comment by mreinstein** [comment]
I've only tried it with webgl rendering

**Comment by mreinstein** [comment]
I just tried it with the canvas renderer and got the same result, so I'm guessing this affects both

**Comment by mreinstein** [comment]
this may not be a bug after all. I think I understand the source of my confusion and what's happening. 
Perhaps you can verify if this is right, and I'll close the ticket.

the texture I referenced is colored 0xFF44FF. 

I load `block`, and I don't set it's tint, so the tint defaults to 0xFFFFFF.

I load `block2` and set it's tint to 0xFF0000. tint is just multiplying the texture color by that mask for each pixel. Since the tint is pure red all the green and blue is masked to 0 by the tint, resulting in pure red.

when `block` and `block2` are additively blended each component is added together and each component is clamped. 0xFF44FF + 0xFF0000 = 0xFF44FF. that's why the overlapping area between the 2 blocks identical to `block`'s original color. 

I'm sorry to waste your time with this. :(

**Comment by GoodBoyDigital** [comment]
no worries man! glad you nailed it :+1:
