### ISSUE TITLE
When using GrayFilter lines are not antialiased anymore 

### ISSUE THREAD

**Issue by stbaer** [pixijs/pixi.js#2109]
Not sure if this only happens with GrayFilter, haven't tried other filters yet.

**Comment by stbaer** [comment]
Without filter:
![line_no_filter](https://cloud.githubusercontent.com/assets/4010327/9985552/8b6bcb36-6060-11e5-8e6c-58b328aa63ea.png)
GrayFilter:
![line_grayfilter](https://cloud.githubusercontent.com/assets/4010327/9985553/8b6d45ce-6060-11e5-9d78-4718d56dc1d8.png)

**Comment by GoodBoyDigital** [comment]
filters use framebuffers, antialiasing is not available when using them unfortunately. WebGL 2 will fix this :)
