### ISSUE TITLE
canvas with cleared area doesn't render correctly when used as mask in CanvasRenderer

### ISSUE THREAD

**Issue by AleBles** [pixijs/pixi.js#2110]
I created an overlay that has an area sliced out so you can see through. In the CanvasRenderer it is incorrectly drawn without the cleared area if you set the generated Sprite as a Mask.
I've created a fiddle to demonstrate what I mean:
http://jsfiddle.net/yxzpcsp9/3/

Test in Google Chrome version 45.0.2454.85 (64-bit) and FireFox 39 with PIXI v3.0.7

**Comment by englercj** [comment]
IIRC black/white colors are used for masking, not transparency. But I could be wrong...

**Comment by GoodBoyDigital** [comment]
Works like a champ! The missing ingredient  was that you did not add the mask to the stage.

http://jsfiddle.net/8ep8u5vn/

Boom! :)
