### ISSUE TITLE
Merging several bitmap fonts into single spritesheet

### ISSUE THREAD

**Issue by sergebat** [pixijs/pixi.js#2111]
I have a question on optimal handling of BitmapText in Pixijs. 

My game is relatively small, so all textures (game sprites) and bitmap fonts should fit 2048x2048 spritesheet.

Is there a recommended approach in pixi for this use case? I believe the easiest direction will be to embed entire PNG generated by bmfont into my main spritesheet? Is there an easy way for BitmapText to take region of this texture as an input? 

Maybe, at the very least, there is an easy way to merge all font PNGs together (I have normal/bold/outline versions of the same font, again they'll easily fit single texture). 

Any pointers are appreciated. I'll be glad to share working example for pixi collection, if we figure out how this can be supported in principle! Thanks!

**Comment by englercj** [comment]
BitmapText and Textures already have the idea of using regions of an image as the portion to use. Putting everything in a single PNG should work perfectly fine (and will be optimal).

**Comment by sergebat** [comment]
For the benefits of future readers, I'd like to confirm that integrating bitmap font into the app spritesheet was indeed easy. 

Currently bitmap font parser already performs the following check:
```
        var textureUrl = xmlUrl + resource.data.getElementsByTagName('page')[0].getAttribute('file');
        if (core.utils.TextureCache[textureUrl]) {
            //reuse existing texture
            parse(resource, core.utils.TextureCache[textureUrl]);
            next();
        }
```

Therefore, it is sufficient to make sure that you have Texture registered in TextureCache matching the image file name in your font file `<page id="0" file="heightFont.png"/>`. This works fine with textures loaded from spritesheet.  

Only thing to pay attention is that loader looks up texture using full path (with xml font file base portion). So either name texture accordingly in your spritesheet, or make a copy with the full path name it expects, e.g.:
```
PIXI.utils.TextureCache["assets/localized/en/font.png"] = PIXI.utils.TextureCache["FontSprite"];
```
