### ISSUE TITLE
Incorrect line breaking in BitmapText with set maxWidth

### ISSUE THREAD

**Issue by primozv** [pixijs/pixi.js#2113]
In version 3.0.7 in function BitmapText.prototype.updateText there is incorrect line breaking on spaces when maxWidth is set.
When writing out the text with BitmapText it happens that characters from words in the following line are written in the previous line.

Problem occurs because chars.splice( lastSpace, i - lastSpace ) uses lastSpace as position of last space which is incorrect. lastSpace refers to this.text attribute which can hold also new line characters (like \r and \n) which are not added to chars array. (Yes, new line character must exist in earlier line to cause the problem).

I suggest the fix as follows:
chars.splice( lastSpace-i+chars.length, i-lastSpace );
"-i+chars.length" correctly adds missing characters.

BR
Primoz

**Comment by englercj** [comment]
Thanks @primozv, would you mind putting in a PR for this?

**Comment by englercj** [comment]
This should be fixed now in the latest v4. Please reopen if it isn't.
