### ISSUE TITLE
Containers with cacheAsBitmap don't render negatively scaled child sprites

### ISSUE THREAD

**Issue by matthewvroman** [pixijs/pixi.js#2114]
If a Container sets 'cacheAsBitmap' to true, any child Sprite with a negative scale will disappear. 

Sample case here:
https://jsfiddle.net/cpy4azf7/

The fish disappears after 1 second, when its parent container sets 'cacheAsBitmap' to true. Setting 'cacheAsBitmap' on the child sprites, as opposed to the parent container, renders them correctly.

**Comment by englercj** [comment]
Thanks for bringing this up, I've seen some other "negative scale" bugs that I need to look into as well. i'll try to batch these up soon.

**Comment by GoodBoyDigital** [comment]
this should be fixed not in the dev branch :+1:
