### ISSUE TITLE
latest dev: getLocalPosition - 'worldTransform' of null

### ISSUE THREAD

**Issue by stbaer** [pixijs/pixi.js#2115]
When building the current dev getLocalPosition throws *Uncaught TypeError: Cannot read property 'worldTransform' of null* in some cases. Here are 2 fiddles with the same code but different pixi builds:

working: http://jsfiddle.net/s3ab3uf6/

broken: http://jsfiddle.net/s3ab3uf6/1/

Either it's a regression from commit 89594508b8f1b8dac105ce4e032410bb2fc025bc - or it has to be used differently now.

**Comment by englercj** [comment]
Thanks @stbaer I will try to look at this asap.

**Comment by stbaer** [comment]
Thanks @englercj, also ping @GoodBoyDigital.

**Comment by GoodBoyDigital** [comment]
Good catch @stbaer. All fixed now :)

**Comment by stbaer** [comment]
Cool, thank you GBD :+1:
