### ISSUE TITLE
Sprite.getBounds innacurate when sprite is scaled with negative values

### ISSUE THREAD

**Issue by DavidAPC** [pixijs/pixi.js#2117]
(posted this to Phaser: https://github.com/photonstorm/phaser/issues/2108 but more relevant here)

Say you've an image loaded, then run these commands from the browser Javascript console:

    var testSprite = game.add.sprite(200,0,"test")
    testSprite.getBounds()
    ---> Object { x: 200, y: 0, width: 300, height: 300, type: 22 }
    testSprite.scale.x = -1;
    testSprite.getBounds()
    ---> Object { x: 200, y: 0, width: 300, height: 300, type: 22 }

The getBounds() should be returning the x as being -100, since being scaled negatively should make 200 be the rightmost boundary of the sprite, not the leftmost boundary.

Fortunately, I found out how to fix this problem (I know I should be submitting a pull request but for now this works easier for me).

At the Sprite.prototype.getBounds line at 16877, replace:

        if (a < 0) a *= -1;

with:

        if (a < 0) {
            a *= -1;
            var temp = w0;
            w0 = -w1;
            w1 = -temp; 
        }

This updates the boundaries of sprite when the scaling flips the sprite horizontally so the correct bounds are calculated.

You'll also need to do the same for the vertical flipping. On the next line down from the above, replace:

        if (d < 0) d *= -1;

with:

        if (d < 0) {
            d *= -1;
            var temp = h0;
            h0 = -h1;
            h1 = -temp; 
        }
 
I did most of my testing with this via Phaser, but seems to work.

**Comment by englercj** [comment]
Interesting, thanks for the heads up I will look into this. (including removing `*= -1` in favor of the unary minus operator :P)

**Comment by GoodBoyDigital** [comment]
Hello! this should be fixed now in dev branch. I removed the 'optimised test' for now as it did not really offer much of a performance boost. Thanks for sharing the issue :+1:
