### ISSUE TITLE
containsPoint

### ISSUE THREAD

**Issue by acopalipsis** [pixijs/pixi.js#2119]
I guess yesterday I was too tired from the comparison pixi.js with flash :) But I was trying to compare the incomparable. After all pixi.js with dozens of times more primitive flash. And if this primitivism does pixi.js flash is much faster, it is even good.  
Also we want to comment on yesterday's "fairy tale". 
If you imagine that the boy is a container, I would like to ask him - have you eaten the Apple? Otherwise I'll have to investigate the contents of his stomach. Of course the boy may be an api that will encapsulate the logic of checking the contents of the stomach. But it complicates the design significantly and not in the spirit of flash.. And that's what I'm confused. After all, the author wrote on the main page pixi.js that your library is similar to flash.

 	
And yet... I'm developing a class of men and women. The man and the woman's people. For this I create a base class person.

```
class Person{
    head: Head;
    torso: Torso;
    hands: Hend;
}

class Man{
    foot: Foot;
}

class Woman {
    foot: Foot;
}
```

but this is not right! After all, man consists of hands, feet, torso and head. And getting a base type of Person I want to get all the basic functionality.

```
class Person{
    head: Head;
    torso: Torso;
    hands: Hend;
    foot: Foot;
}

class Man{

}

class Woman {
    
}
```

Now tell me, what is a display object? Why do You have - 
```
class DisplayObject {
    x: number;
    y: number
}

class Container extends DisplayObject {
    width: number;
    height: number;
}

class Graphics extends Container {
    width: number;
    height: number;
}
```
Because it turns out that the base type, and the display object is point-vector.

**Comment by GoodBoyDigital** [comment]
Ha! Im honestly a little confused by your tale :)

**Comment by dmmn** [comment]
![image](http://a.deviantart.net/avatars/s/u/supermindblownplz.gif)

**Comment by fusspawn** [comment]
I 'think' he wants a containsPoint method on containers to return true/false if a point is within container bounds?  

He could just be tripping tho. 

Drugs are bad. Stay in school kids.

**Comment by danhett** [comment]
Something to do with... if you have no jaw and ate an apple, you should be able to query containsPoint on a point inside a container? Inside a boy? 

WHAT DOES IT ALL MEAN

**Comment by DanielPettersson** [comment]
I totally get it. I also experienced this issue using pixi.js. Its kind of annoying, otherwise Pixi is really great!

**Comment by XerxesNoble** [comment]
I came here looking for answers for my containsPoint problem.. can we rename this issue to "Drugs are bad. Stay in school kids."

**Comment by ivanpopelyshev** [comment]
@XerxesNoble Labelz are better )

**Comment by englercj** [comment]
Lets try to remain professional and inclusive people, no need to be rude. Make sure that you are following our [Code of Conduct](https://github.com/pixijs/pixi.js/blob/master/CODE_OF_CONDUCT.md) when you post here.

I'm locking this issue.
