### ISSUE TITLE
pixi.js and React Native

### ISSUE THREAD

**Issue by nickdima** [pixijs/pixi.js#2120]
I was wondering about the possibility of using pixi.js in React Native by bridging it to native OpenGL ES on iOS and Android. Anyone familiar with the pixi.js source code has any idea how this could be achieved? 

Here's a simple example of example of OpenGL bridged to React Native: http://jlongster.com/First-Impressions-using-React-Native#An-OpenGL-App-with-R
And here's a library doing something similar but for OpenGL image effects: https://github.com/ProjectSeptemberInc/gl-react-native

**Comment by englercj** [comment]
I'm familiar with pixi, but not React Native :) Does it automatically bridge webgl to native gl?

**Comment by nickdima** [comment]
No, unfortunately there's no such bridge at the moment. I posted [here](https://github.com/ProjectSeptemberInc/gl-react-native/issues/13) a question about this and it seems that a lot of work would be involved in building it.

**Comment by englercj** [comment]
I figured as much, I was under the impression that the parts that were translated to gl were the react parts, not necessarily browser APIs. In that case there probably isn't anything you can do (that I can think of) easily.

**Comment by GoodBoyDigital** [comment]
closing this for now as it seems to have reached its end. thanks all
