### ISSUE TITLE
Graphics quadraticCurveTo issue

### ISSUE THREAD

**Issue by milkmidi** [pixijs/pixi.js#2121]
Graphics quadraticCurveTo issue in V3.0.7
this my code.
var shape = new PIXI.Graphics();  
    stage.mousemove = function  (e) {
        shape.clear();        
        shape.lineStyle(10, 0);          
        shape.drawCircle(300,300,10);
        shape.drawCircle(100,100,10);

        shape.lineStyle(10, 0xff0000);          
        shape.moveTo(100, 100);           

        var mouseX = e.data.global.x;
        var mouseY = e.data.global.y;
        shape.quadraticCurveTo( mouseX , mouseY ,300, 300);     
    }
line is over point?
![2015-09-25_114414](https://cloud.githubusercontent.com/assets/233023/10092595/c7cc6776-637a-11e5-8d4b-8ccd148a54c2.png)

line auto close?
![1](https://cloud.githubusercontent.com/assets/233023/10092604/ec6bd01c-637a-11e5-946d-99554669199e.png)

Thanks

**Comment by acopalipsis** [comment]
```
graphics.currentPath.shape.closed = false;
```

**Comment by milkmidi** [comment]
Thanks. It's work.

**Comment by acopalipsis** [comment]
Yes works, but it's still not right. The creators should fix this.

**Comment by stbaer** [comment]
See issue #1892, should be fixed in latest dev.

**Comment by englercj** [comment]
Yes this issue should be fixed in the latest develop version. Release coming soon, I just got back from being out of town and will look at release as soon as I can.
