### ISSUE TITLE
№189

### ISSUE THREAD

**Issue by acopalipsis** [pixijs/pixi.js#2125]
I found another bug. But I don't want to waste my time describing it. Because You ignored 188 requests. That's the lamest repository and a product that I have ever seen. I hope that at least this will Wake your senses. And no need to repeat a high-level api flash!  Inherit from DisplayObject string. 
And it's the least I can tell You, after weeks of wasted time. For the first time in several years I can say that the time spent in vain. I wish You to live until that time when Your product will be better than flash.

**Comment by mreinstein** [comment]
wow a flash troll. did I suddenly wake up to 2007?

**Comment by englercj** [comment]
I'm sorry you feel that way @acopalipsis, I try to spend what time I can on the product but I do have a full time job, life, and other side projects as well. Sometimes it is hard to put the time necessary to make this library great.

I assure you I read every bug that comes in, hopefully you will find the time to put in a proper bug.

Good Luck,

-Chad
