### ISSUE TITLE
Graphics lineTo disappearing

### ISSUE THREAD

**Issue by twhitbeck** [pixijs/pixi.js#2129]
With the latest dev build: observing strange behavior using Graphics `lineTo` and `arcTo`.

http://plnkr.co/edit/upa7iGpJQ1qVvjweJzt9?p=preview

Notice the first Graphics is missing the second `lineTo`. The second item uses the same commands except the final `arcTo` and it correctly displays the second `lineTo`.

This is only with `WebGLRenderer`. When passing `noWebGL` parameter to `autoDetectRenderer` everything looks fine.

**Comment by korbai** [comment]
I have a similar behaviour. I tested all 3.x versions and my result is the same.
I draw 2 lines, but only the second one seems on the screen
in WebGL mode, in Canvas mode both of them are displayed correctly.

[http://plnkr.co/edit/Wfan7kKg1wCpzPkcHby7?p=preview](http://plnkr.co/edit/Wfan7kKg1wCpzPkcHby7?p=preview)

**Comment by staff0rd** [comment]
Seems fixed in latest; https://codepen.io/staff0rd/pen/EZRZWq?editors=0010
