### ISSUE TITLE
PIXI.Graphics is a bad parent (it inerits from container but does not care about its children)

### ISSUE THREAD

**Issue by FlorianLudwig** [pixijs/pixi.js#2131]
PIXI.Graphics.{clone,generateTexture} and possible others don't take into account that Graphics can have children.  I think it should - or at least be documented.

**Comment by englercj** [comment]
I wonder how people feel about us making it inherit from DisplayObject instead of container...

**Comment by FlorianLudwig** [comment]
Seems to be a viable option that would clear things up - but it would break compatibility.  For example we make depend on it in our [svg renderer](https://github.com/GreyRook/pixi-svg-graphics).  So I guess its no option for a minor release.

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
