### ISSUE TITLE
Text on Safari doesn't render correctly

### ISSUE THREAD

**Issue by dimmdesign** [pixijs/pixi.js#2132]
This happens on Safari but not on Chrome. Any suggestions?
<img width="184" alt="screen shot 2015-09-30 at 00 31 43" src="https://cloud.githubusercontent.com/assets/886854/10179104/7f26a5dc-670c-11e5-9664-86e11ef472ae.png">

**Comment by englercj** [comment]
Likely due to FXAA being turned on. Do you see a warning in the console saying that you are using FXAA?

**Comment by dimmdesign** [comment]
No, just the output from Pixi.js with its version and renderer.

**Comment by dimmdesign** [comment]
ok, so I took another look at it and it seemed that the text was added twice in the stage... the render isn't smooth but its acceptable!

![screen shot 2015-09-30 at 11 22 53](https://cloud.githubusercontent.com/assets/886854/10188122/9ea977a0-6765-11e5-93dd-475cd14ff9ca.png)
