### ISSUE TITLE
roundPixels for WebGL Renderer

### ISSUE THREAD

**Issue by FlorianLudwig** [pixijs/pixi.js#2135]
what is the rational behind roundPixels being Canvas-only?

**Comment by adireddy** [comment]
I changed it and the pull request https://github.com/pixijs/pixi.js/pull/2112 was merged to dev.

**Comment by FlorianLudwig** [comment]
@adireddy good to know, thank you!

**Comment by englercj** [comment]
I'm reopening this, since that PR just adds the property not actually makes it supported in the WebGLRenderer.

**Comment by adireddy** [comment]
@englercj I tested this on WebGL and it worked because `SpriteRenderer` class is checking `roundPixels` property on the renderer. https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/webgl/SpriteRenderer.js#L217

Am I wrong?

**Comment by FlorianLudwig** [comment]
I did not check the code but checked in a project of us - using 3.0.7 - setting `renderer.roundPixels = true` does make a difference in the WebGL renderer.

**Comment by englercj** [comment]
@adireddy Oh shit, my bad you're 100% correct. Sorry so many things going on at once I got confused!
