### ISSUE TITLE
Text jumps / stretches right before a change

### ISSUE THREAD

**Issue by CoDEmanX** [pixijs/pixi.js#2136]
If you have a close look at http://www.goodboydigital.com/pixi-js-text/, you may notice that COUNT4EVER at the bottom seems to render twice sometimes (you'll see a small jitter).

I first thought it might occur when two digits change at the same time (e.g. 19 -> 20), but that's not actually the case. In a slowed down screen capture, you can see the text jump roughly one frame  **before** the change:

https://youtu.be/t5vK9own_MQ

If you compare frame by frame, you'll see that the text is **actually stretching**:

![pixi-jitter3](https://cloud.githubusercontent.com/assets/1309249/10201041/2e3dae92-67aa-11e5-95ef-1b7fd443b89a.gif)

Any idea why that happens?

There's also a secondary issue, the last digit is slightly cut off. Also see https://github.com/pixijs/pixi.js/issues/1743#issuecomment-121218025.

I'm running Chrome 47 on Windows 8.

**Comment by englercj** [comment]
Weird...thanks for bringing this up.

**Comment by GoodBoyDigital** [comment]
This looks like the texture is uploaded a frame after it was rendered. Good news is that the above code is pixi v1 so i am confident that the issue no longer exists in v3. :+1:
