### ISSUE TITLE
NormalMapFilter lack of documentation

### ISSUE THREAD

**Issue by kbkrisa3** [pixijs/pixi.js#2140]
Hi, 

I just began experimenting with PIXI's NormalMapFilter, because I think it's pretty dope, and I see potential in it for my game. 

My problem is, that I can't find it in the documentation, and so I don't know how the lightpos works for examle, because it's not translated to pixels, or how to set the scale of the texture/filter to match the parent sprites size. 

Thank you in advance!

**Comment by GoodBoyDigital** [comment]
this no longer exists in v4 - we will likely add a filter for this in the pixi-filters repo 👍
