### ISSUE TITLE
Getting my head around aTextureCoord when writing GLSL code.

### ISSUE THREAD

**Issue by wojciak** [pixijs/pixi.js#2142]
Hello :)

I was trying to implement a simple GLSL texture mapping shader - to create a sphere out of a simple rectangle texture. A simple approach is described here: 
view-source:http://z0b.kapsi.fi/webgl-sphere.html

I used the aTextureCoord attribute and pass it as a varying to the fragment shader. When doing a clean webGl/GLSL test the example works, when doing it in PIXI magic starts to happen.

All is good until I try to do some transformations in the fragment shader. I've tried to browse through PIXI filters code, and found out that I indeed need to do some pre-calculations to have a proper working coordinate system in GLSL (for example when I was reading the TilingSprite implementation), but I just can't seem to get my head around it.

Would it be possible to explain how I can achieve a "clean" textureCoord in the fragment shader - so that I can test-out all the nice examples that are out there? :)

**Comment by englercj** [comment]
@GoodBoyDigital This is all you :) Docs are fun!
