### ISSUE TITLE
Question regarding copyrights

### ISSUE THREAD

**Issue by CaitlinKIN** [pixijs/pixi.js#2143]
Hello. I work at a company that is making a software manual for a client. The manual will be made in Japanese then translated into English. Within the manual, there is a brief mention of "Pixi.js". For this reason, we would like to know if you require us to include a copyright phrase in our manual for your product. If so, could you please tell us what copyright phrase to use? (English only is fine.) Also, if you require some trademark attribution phrase ("Pixi.js   is a trademark of..."), please let us know. If you need more specific details, please email me at beggs@kinsha.co.jp. Thank you for your time!

**Comment by englercj** [comment]
Pixi.js is [copyrighted](https://github.com/pixijs/pixi.js/blob/master/LICENSE) by Mathew Groves. It is not trademarked.

**Comment by GoodBoyDigital** [comment]
looks all good here!
