### ISSUE TITLE
Issue with updating resolution parameter runtime

### ISSUE THREAD

**Issue by doskallemaskin** [pixijs/pixi.js#2144]
This may not be an intended feature of PIXI, but updating the resolution parameter runtime will not work well with PIXI.Text (may occur on other modules as well). 

The resolution parameter seem to be read once from the global PIXI.RESOLUTION parameter upon creation. 
Updating the resolution parameter after that point will not update the parameter of the PIXI.Text instance.

http://jsfiddle.net/mbqmmquk/

**Comment by englercj** [comment]
That is correct, you will need to change the resolution in the text object. You can't hold a reference to a basic type in js, only to objects.

**Comment by doskallemaskin** [comment]
Why wouldn't you use the global object to see what reference is stead instead of storing it? Just wondering, is there any practical reason behind the decision? :)

**Comment by GoodBoyDigital** [comment]
Hello! 

Its the way that text is stored. The text texture is only generated once each time the text/style changes for performance reasons (we leverage the canvas text rendering API). This means we need to know what the resolution of the texture needs to be at creation time. 

Modifying the resolution at runtime is considered edge case. I would be very interested to know the reason this feature is required for your app!

Thanks!

**Comment by englercj** [comment]
> Why wouldn't you use the global object to see what reference is stead instead of storing it? Just wondering, is there any practical reason behind the decision? :)

Because there is no "global object" until the library is compiled, and holding that ref wouldn't tell us when it changes anyway (like @GoodBoyDigital mentioned). ITs pretty edge to need to change resolution at runtime (since resolution is a device-level data-point). I too am curious what this case is!

**Comment by doskallemaskin** [comment]
Yeah what i was thinking was something like that, single constant. 
Short story, my idea was to have a canvas which the user can change size of runtime, though in my test i calculated the scale of the size of the window.innerWidths relation to a constant width (720 in this case). 

Then what the resolution would be to make the canvas fill the screen width, update it and call the resize parameter. The idea was to manage scaling by the resolution flag to use the same coordination system, and to get correct resolution of texts and such. Does it make sense?

Even with the addition of the single constant being used, (like PIXI.RESOLUTION) i would have to set every object, or at least the graphics and texts to dirty, right? Cause PIXI does not include a function to make all children dirty?

**Comment by englercj** [comment]
I would use scaling, just change the scale of your root container to match what you need. Resolution acts a bit differently than just resizing because it expect higher pixel density

**Comment by GoodBoyDigital** [comment]
closing this for now @englercj's answer is correct.
