### ISSUE TITLE
Rendering individual components

### ISSUE THREAD

**Issue by ahumphreys87** [pixijs/pixi.js#2145]
I'm busy looking at optimising the render cycle in an app I have built and was looking for a way to render certain components only to the canvas, rather than the whole stage.

So my app is broken up into components, some of these components are idle, some listen for input events and some animate when they receive certain events. Each component has a Pixi.Container, and I naively tried doing: `renderer.render(container)` in each component. Of course this just shows the last component to be rendered!

Is there a way to do what I want? if I could add conditionals to the rendering of components, it would optimise my apps a lot!

**Comment by englercj** [comment]
Have you tried using `.cacheAsBitmap` and/or render textures?

**Comment by ahumphreys87** [comment]
@englercj I haven't yet, could be a good shout. I've started experimenting with setting `clearBeforeRender ` to `false` on the renderer. The way im setup is I have a main RAF loop which is calling `render` on each of my components.

In the `render` methods I will conditionally render the components Pixi.Container. Actually seems to be working so far, I do need to make sure that static items are the lowest in the stack though, otherwise I get layering issues.

Are there any performance concerns with setting clearBeforeRender to false?

**Comment by englercj** [comment]
Not really, you just might get some unexpected results moving things around (like ghost trails).

**Comment by ahumphreys87** [comment]
Yeah ive hit that problem :disappointed: 

I actually found switching from Canvas to WebGL dropped CPU usage by 20%. Mobile was previously running at 80% now 60%. Still some way to go though. Gonna try out RenderTexture, any big wins for CPU usage that you use?

**Comment by englercj** [comment]
RenderTexture is good for things that don't update often, you can basically replace a scene with a single sprite on only update it when things change. If you have something that changes often you should try the example I just posted.

**Comment by ahumphreys87** [comment]
where did you post the example?

**Comment by englercj** [comment]
https://github.com/pixijs/pixi.js/issues/2145#issuecomment-146260254

Here it is again:

```js
var stage = new PIXI.Container();

stage.addChild(component1);
stage.addChild(component2);
stage.addChild(component3);
stage.addChild(component4);

component1.visible = !!(shouldShowComponentCondition);
// ...

renderer.render(stage);
```

**Comment by ahumphreys87** [comment]
oh sorry! that wasnt showing earlier. Thanks ill give it a try

**Comment by englercj** [comment]
No problem, let me know how it works out for you :)

**Comment by ahumphreys87** [comment]
@englercj implemented what you suggested, `cacheAsBitmap` for some elements and `RenderTexture`s. Seemed to have a nice effect.

The biggest boost I've got (particularly on mobile) was reducing the frameRate by skipping x animationFrames - our MovieClips are set to run at 24 (yes they should be a divisor of 60, I'm having words :smile: ) so targeting 60fps seems like a lot of overhead for little gain, we can barely notice the difference.

Its reduced CPU usage on mobile from 80% to around 20-30% which means users don't need to wear oven gloves anymore!

**Comment by LegitSoulja** [comment]
@englercj sorry this is an old post, but does the child containers auto render once the parent is rendered? 

I'm running into issues where it'll render once, but during the stage render it doesn't render.

**Comment by englercj** [comment]
All children of the container that you pass into `renderer.render()` are rendered, unless they have `renderable = false` or `visible = false`.

**Comment by LegitSoulja** [comment]
@englercj Ok I've figured. Thanks for the info

**Comment by ivanpopelyshev** [comment]
@LegitSoulja The pixi approach is "render whole stage at 60FPS frequency". You don't have to re-render every element you moved, because 60 times in second requestAnimationFrame does render on all things anyway

**Comment by ivanpopelyshev** [comment]
Also, if you render a parent and then a child, it doesn't mean that child will be rendered over itself, because when its considered root, its rendered at (0,0). You have to surpress transform updates when you do that kind of stuff
