### ISSUE TITLE
Update website with v3?

### ISSUE THREAD

**Issue by chikamichi** [pixijs/pixi.js#2146]
Hi,

I looked in the past issues and found no insight about that. Is v3 production-ready and if yes, when would it be advertised on the official http://www.pixijs.com website? npmjs.org has v3 published: https://www.npmjs.com/package/pixi.js

Thank you!

**Comment by englercj** [comment]
v3 is the only version now, older versions are deprecated; so yes it is production ready :)

The website should be updated but I don't have access to that, ping @GoodBoyDigital

**Comment by chikamichi** [comment]
Thank you for the feedback. Let's see what the housekeeper has to say on that :)

**Comment by chikamichi** [comment]
Hi! Any feedback from @GoodBoyDigital ?

**Comment by englercj** [comment]
I don't have access to the site, so he will have to update it.

**Comment by chikamichi** [comment]
Ok, we shall wait then. I'm a mentor at a bootcamp where many students use Pixi, and It's been confusing most of them. It's often a good idea having at least two trusted people being able to update/edit frontage :two_men_holding_hands:

**Comment by GoodBoyDigital** [comment]
hey peeps - Update the site to v3 a little while back? Did we miss something?

**Comment by chikamichi** [comment]
Hey @GoodBoyDigital, nice! I honestly didn't check the website when I made my comment earlier today. One thing that is not *obvious* to find, is the documentation itself. It's available under Resources, but looks like all the rest. It's so core to using the library though, that I wondered whether it could be promoted and have its own link in the main, top navigation… What do you think?

**Comment by englercj** [comment]
> have its own link in the main, top navigation

/agree

**Comment by GoodBoyDigital** [comment]
Good shout! Will add to the todos :+1:

**Comment by GoodBoyDigital** [comment]
done :)

**Comment by chikamichi** [comment]
Excellent! :cake:
