### ISSUE TITLE
lowp in the TextureShader makes old mobile devices to fail to render

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#2147]
Hello, 

I'm sorry for not pushing this change myself, not enough time to set up an up to date fork without messing with my files.

On https://github.com/pixijs/pixi.js/blob/master/src/core/renderers/webgl/shaders/TextureShader.js#L67

The lowp at line 67 produce bugs on some older android devices, preventing textures from showing up.

Changing it to a mediump fix the issue.

Regards.

**Comment by GoodBoyDigital** [comment]
I will make sure to make this adjustable in v4 :+1:

**Comment by GoodBoyDigital** [comment]
Hello! This is now a configurable property in dev branch ( ```PIXI.PRECISION```) 
The default has been changed to ```mediump``` too.
