### ISSUE TITLE
Rats! WebGL hit a snag...

### ISSUE THREAD

**Issue by daviestar** [pixijs/pixi.js#2148]
I'm nearing the end of a pixi.js project involving several (~50) Spine characters, creating a live music scene.  Pixi has been a pleasure to work with throughout, so thanks guys!!

I've been browser testing it across all the devices I can get my hands on, and I'm finding on Windows 8 laptops running Chrome, I am getting the "Rats! WebGL hit a snag..." error, although the page appears to render and animate fine.  

I've read about a few issues here, and on three.js and elsewhere about this error.  I'm especially interested in this: https://github.com/pixijs/pixi.js/issues/194#issuecomment-20772982

Should I have made all my Spine sprites dimensions power-of-2?  Even if it doesn't fix this issue, should changing this give me a substantial performance boost?

(As a side-issue, these same machines don't appear to render Sprite masks as described [here](http://www.goodboydigital.com/pixi-js-brings-canvas-and-webgl-masking/), although disabling the mask code doesn't remove the error),

Since the scene appears to run fine on these machines, I'm just looking for a way to sidestep the error if anyone can offer advice.  Thanks.

**Comment by englercj** [comment]
No issue unless you are getting PERFORMANCE WARNING logs from Chrome. The error is from Chrome having the render process crash. PRetty much anything can cause this issue, so i'm honestly not sure :(

**Comment by stbaer** [comment]
Also getting it all the time on Android. All seems to work fine but when opening the page in chrome this message appears.

**Comment by Zolmeister** [comment]
Has anyone found a workaround to avoid the popup?
Ideally it should fail silently and fall back to canvas rendering.

**Comment by ivanpopelyshev** [comment]
Please try pixi-spine gpu-patch, it can help: http://www.html5gamedevs.com/topic/18480-pixi-spine-plugin-wip-gpu-patch/ .

**Comment by jordansteeves** [comment]
I am also seeing the "Rats! WebGL hit a snag" error in my pixi project but after extensive testing, this appears not to be exclusive to pixi as it can be reproduced on other WebGL links. I have submitted an issue to Chromium here: https://code.google.com/p/chromium/issues/detail?id=586905. If anyone wants to add more details, please comment on the issue there to give it more visibility.

**Comment by daviestar** [comment]
@ivanpopelyshev apologies I just saw your comment.  I notice your plugin is called SkinnedMeshPatch. I don't have the PRO version of Spine, so am not using any Meshes.  Should the patch still be used?  Thanks.

**Comment by ivanpopelyshev** [comment]
@daviestar no, it wont. Default pixi renderer is optimal for large number of sprites, I cant beat it :)

**Comment by gregsidelnikov** [comment]
Not saying this is going to fix it, but this video helped me get familiar with Chrome settings, that eventually led to figuring it out: [Rats! WebGL hit a snag](https://www.youtube.com/watch?v=9L6BZNz3x9o)

**Comment by kaansoral** [comment]
I experienced this frequently when I had the memory leak I discovered at #2840 

On the side, I was also not .destroy'ing some completed Sprite's - which seems like a more likely cause

So after extended usage, the WebGL crashed, not sure whether memory is a cause, but since it causes slowdowns and instabilities, It might as well be
