### ISSUE TITLE
Slow performance with Firefox / Yosemite during first seconds

### ISSUE THREAD

**Issue by arthurmuchir** [pixijs/pixi.js#2149]
I have been using Pixi v3 for a while (I am very happy with it, thanks for your work !) and I am facing quite weird performance under Firefox with OSX (Yosemite).
With Chrome, Safari and Opera, I have a really smooth result. With Firefox, when page has loaded, I have to wait several seconds (it is quite random, sometimes 6 seconds, sometimes minutes) before everything goes as smooth as with other browsers. It does the same on multiple computers with same configuration.

At first sight, I thought it was a problem with my own project, maybe due to texture sizes. But I have the same result with examples provided on Pixi v3 pages. For example, here is a video record I made.
I am not telling that it does not work with Firefox, but just that the result is not very smooth during the first second.

Chrome : https://www.dropbox.com/s/5iv3u3htaeh3ddu/chrome.mov?dl=1
Firefox : https://www.dropbox.com/s/u9x2c95f6zjjwz4/firefox.mov?dl=1

If you look closer, you will see that the dragon beak is quite saccade (as the rest of the body).
If I wait a moment it will then go normal.

In my own project I only start the render animation when everything is loaded, so there are not any background processes running that may slow the animation. Moreover, I have a FPS stat utils that show that the animation is running 60fps at all time, as if there was not any image drop.

I am using a new Macbook pro 2.8Ghz i7 with 16Go DDR3 and a AMD Radeon R9 M370X 2048 Mo.
I test the same PIXI  example on a Windows platform with Firefox and everything goes well. So it might be a Firefox OS X issue, but my question is do you have any ideas on what could be done (on PIXI experience code side) to improve general performance with Firefox ? Do you have any ideas on what this delay before it goes well could be related to ?

**Comment by Jorisslagter** [comment]
I'am also having problems with performance on my project in Firefox. But also with the canvas renderer. The WebGL looks to deal way beter with more sprites.

**Comment by sokeroner** [comment]
+1

**Comment by mattstyles** [comment]
I have the same problems on a slightly older Retina MBP running the latest FF (41.0.2), OSX 10.10.5, fps drops to around 40.

Weird that it always speeds up after time and from then on even refreshing the page wont knock it from a solid 60 fps, so, is this something to do with getting on to the GPU? I'm not clear how that stuff works but given that a page refresh wont knock the fps back down again its gotta be more than _just_ code.

I see similar slowdown with the bunnymark, but far far less.

The profiler is telling me most time is spent in `WebGLRenderer.prototype.render` and in the shader `Shader.prototype.syncUniforms`, although, opening the profiler normally kicks everything into life and gets me the 60 fps.

Safari is also slow as hell for me, but the profiler is crashing, Version 9.0.1 (10601.2.7.2).

My test is just rendering a container with a few interactive graphics circles in, about 30, nothing spectacular. I'll try and create a gist that replicates it.

**Comment by sokeroner** [comment]
In my case, stats.js doesn't display the fps drop, but like in this example ( https://www.dropbox.com/s/u9x2c95f6zjjwz4/firefox.mov?dl=1 ) i can see slow performance with firefox.

**Comment by GoodBoyDigital** [comment]
Hello! This initial slow down caused when pixi first creates all its shaders / buffers and initially uploads textures to the GPU. 
@mattstyles if you could provide a gist or fiddle I will make sure to look into this. Thanks!

**Comment by mattstyles** [comment]
I was just looking at trying to simplify a project into a gist for you, but with 3.0.9 the `ParticleBuffer` does not seem to work very well for FF & Safari. Apologies if this has been reported elsewhere, this is the error log from Firefox

```
"Pixi.js 3.0.9 - WebGL - http://www.pixijs.com/" main.js:42729:13
TypeError: invalid arguments
[185]</ParticleBuffer.prototype.initBuffers()
ParticleBuffer()
[186]</ParticleRenderer.prototype.generateBuffers()
[186]</ParticleRenderer.prototype.render()
[184]</ParticleContainer.prototype.renderWebGL()
[169]</Container.prototype.renderWebGL()
[169]</Container.prototype.renderWebGL()
[194]</WebGLRenderer.prototype.renderDisplayObject()
[194]</WebGLRenderer.prototype.render()
Main/this.onRender()
emit()
Tick/<()
[468]</EventEmitter.prototype.emit()
iter()
```

It's this line inside `initBuffers`

```
this.dynamicData = new Float32Array( this.size * this.dynamicStride * 4);
```

Safari has the same issue but has slightly more helpful error details

```
TypeError: Invalid array length argument (fractional lengths not allowed)
```

Chrome doesnt seem to give a shit and ploughs on regardless.

Any ideas why the array size of stride is fractional?

Firefox version 43.0.4
Pixi version 3.0.9

Yeah, I tried Pixi 3.0.7 and that works, but at 35-45fps. [Project link](http://mattstyles.github.io/odyssey-nova/), not sure how useful that will be though, other than the profiler showing where the time is spent. Still want a gist from 3.0.7? I'm inclined to investigate the 3.0.9 particle buffer thang and then worry about perf issues.

**Comment by GoodBoyDigital** [comment]
should be all good in v4 :
