### ISSUE TITLE
Image sprite is blurry even with no dimension modifications.

### ISSUE THREAD

**Issue by ctrlplusb** [pixijs/pixi.js#2150]
This is absolutely killing me at the moment.

I have tried everything and have even boiled down to the most simple usage/example of mounting an image on my pixi stage.  

In my example I load the exact same image twice.  Firstly with a standard <img /> tag, and then using pixijs.  I do absolutely no changes to the dimensions of the image.  Despite this you will notice there is a definite blur on the pixijs render output compared to the standard image output.  I even tried switching off the webgl.  Also played with the pixel resolution settings, but you will still notice a definite difference in output quality.

http://jsfiddle.net/iAREsean/0qdn9zvz/

Have a very close look.  There is a definite blur on the pixi js output.

**Comment by wayfu** [comment]
There's something else going on on your system, these two are pixel-for-pixel identical here.

**Comment by ctrlplusb** [comment]
Please have a more careful look.  It's very subtle, but you will notice the pixijs render has a subtle blur. It's more noticeable on some of the comic covers compared to others.

I'll try and manufacture a more clear example later.

**Comment by ctrlplusb** [comment]
Here is another example: http://jsfiddle.net/iAREsean/dpLygcpn/
And here is one of the comics isolated: http://jsfiddle.net/iAREsean/au41nz4p/

Look at the fine detail.  There is a kind of blur/smoothing being applied, especially to the edges.  I would understand the difference if the dimensions/scale of the output was difference, but it's a 1:1 - surely I should expect the output to equal that of the original?

Disabling antialiasing and webgl also has no effect.

**Comment by JiDW** [comment]
Pixel perfect for me too.

Please take a screenshot of what you see and you should check your GPU drivers.

http://www.serenity-ff.com/images/screenshots/screenshot110319001.png

**Comment by ctrlplusb** [comment]
Ok, sorry, another update. 

I updated the fiddle to contain a native canvas render:
http://jsfiddle.net/iAREsean/qtyb2sn5/

It has the same quality output that pixijs produce.  

Doing more research, it appears that canvas that the issue lies in native canvas.  Some good reading on this: http://stackoverflow.com/questions/17861447/html5-canvas-drawimage-how-to-apply-antialiasing

**Comment by ctrlplusb** [comment]
For interest sake, here is what I see:

http://i.imgur.com/2fk1ujq.jpg

**Comment by wayfu** [comment]
Still looks like something local to you. The three are absolutely identical for me: http://i.imgur.com/94PcI6R.png

**Comment by wayfu** [comment]
Ahhh.. I just turned on browser zoom and that made it look like yours. 

Zoom to 100% my friend ;)
