### ISSUE TITLE
Efficient way to draw pixels on graphics element.

### ISSUE THREAD

**Issue by Darker** [pixijs/pixi.js#2151]
I think PIXI is missing really efficient way to render pixel data. On canvas, you can normally get canvas raw data and change pixels using a loop. I'd like to do exactly that. Here's what I do now:

              // No line
              gr.lineStyle(0, 0x0000FF, 1);
              gr.beginFill(PIXEL_COLOR, 1);
              // 1x1 rectangle
              gr.drawRect(x, y, 1, 1);

**Comment by englercj** [comment]
You can use a canvas as a texture, I would suggest doing that.

Honestly, the way to manipulate pixels effectively is using a fragment shader. But if you must support canvas, do whatever you want to a canvas and then use it as a texture.

**Comment by Darker** [comment]
No, I don't insist on canvas at all. But I created a simple game that really renders it's map as pixels, which may be subject to various changes. And I really appreciate the *right* way to render the pixels, I'll look up the fragment shader.

**Comment by GoodBoyDigital** [comment]
Hello! Best thing to do is use a canvas element. Build your map using setPixels and then once you are happy upload the canvas and use it a a pixi sprite texture.

Whilst you could use pixi graphics, it would be a lot slower than the first method. Pixel manipulation is generally one of the slowest things you can do with rendering. 

The exception to this rule is if you write a fragment shader and draw the element using a that. Unless your map changes ALL the time time (or you are curious about how shaders work), its probably not the best solution.

Hope that helps!

**Comment by Darker** [comment]
Yes I rewrite the map almost all the time, the pixels keep changing (they are being added) as the game goes on. I looked up fragment shader on google and I don't feel any wiser. I don't know how to create it, not mentioning how to make it render pixel data.
