### ISSUE TITLE
PIXI.ParticleContainer and unexpected interaction behavior from children

### ISSUE THREAD

**Issue by vicapow** [pixijs/pixi.js#2154]
If I create a particle container
```
var container = new PIXI.ParticleContainer(15000, {
  scale: true,
  position: true,
  rotation: true
});
// Instead of a regular container
// var particles = new PIXI.Container();
```

And set
```
container.interactiveChildren = true;
```

And also create a sprite:

```
function onMouseDown() {
  alert('on mouse down!');
}

sprite = new PIXI.Sprite.fromImage('zaku.gif');
sprite.scale.x = sprite.scale.y = Math.random() * 2 + 1;
sprite.position.x = width * Math.random();
sprite.position.y = height * Math.random();
sprite.rotation = Math.PI * 2 * Math.random();
sprite.interactive = true;
sprite.mousedown = onMouseDown;
container.addChild(sprite);
}
```

It will call the `onMouseDown()` callback only if you click in the top, left corner of the screen, no matter where the sprite is.

I would expect either interaction to not be supported for `PIXI.ParticleContainer` child sprites or for the `mousedown` callback to only fire when you actually click the sprite like a regular `PIXI.Container`.

**Comment by vicapow** [comment]
I thin this might have something to do with the child sprite's `worldTransform` not being updated which is necessarily for `containsPoint()` to be calculated correctly.

**Comment by englercj** [comment]
Interactions and other advanced features do not work on particle container children. All it does is draw, really fast.

**Comment by vicapow** [comment]
Makes sense. So I shouldn't have even set `interactive=true` for the Sprite. Any behavior observed after that is undefined. 👍
