### ISSUE TITLE
Circle not correctly displayed when using big sizes and small scale

### ISSUE THREAD

**Issue by ArThoX** [pixijs/pixi.js#2155]
Hi

Backend: 
* manipulates objects modeled with big dimensions / coordinates

Frontend (pixi):
* we try to do a simple display
* we keep initial dimensions an coordinates
* we apply a scale of 0.000001 to obtain the wanted size

Issue:
* simple draw function such as drawCircle do not result in the expected draw (only a part of the circle is displayed)
* similar issue when drawing a rectangle, where outline is not smooth

Code sample:
http://codepen.io/anon/pen/pjpJwZ?editors=101

Screenshot:
![download](https://cloud.githubusercontent.com/assets/551029/10592090/24dd531a-76ba-11e5-81dc-5c953aaa2dc2.png)

**Question:
 Is this a bug (circle not fully displayed, border not smooth)?
 Or is the approach of keeping big numbers wrong ?
 Any alternative ?**

Regards

**Comment by ArThoX** [comment]
Note: depending on the browser version, the triangle will not even be displayed (this is a case when I try with Chromium  46.0.2459.0 (64-bit))

**Comment by sokeroner** [comment]
Hi,

No idea about a bug with big number scale.
But, maybe you can draw directly in the right size.

```javascript
METER *= s;
```

http://codepen.io/anon/pen/wKpJGw?editors=101

**Comment by ArThoX** [comment]
@sokeroner thanks
I liked the idea of keeping original sizes and scaling, it's less work.
But you are right, if there is no way to make it work, directly applying scale to dimensions/sizes seems to be a valid alternative approach.

**Comment by englercj** [comment]
I think scaling the stage by such a huge amount is going to cause some serious floating point rounding issues. That is likely what is going on here.

**Comment by GoodBoyDigital** [comment]
@englercj is totally correct! thats a very small scale! :D
