### ISSUE TITLE
don't clear background every frame

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#2156]
Is it possible to tell PIXI not to clear the background every frame - aka like Canvas does ? 

I'm trying to efficiently create some trails in WebGL  --- see:  https://jsfiddle.net/03hLme9q for an example

**Comment by JiDW** [comment]
clearBeforeRender:false in the render options

http://pixijs.github.io/docs/PIXI.WebGLRenderer.html

**Comment by weepy** [comment]
RTFM 
DOH! 

thanks!

**Comment by weepy** [comment]
actually I think that's for the canvas element only. We need to use `preserveDrawingBuffer: true`

However that doesn't quite solve the problem - there's a solution here in three.js : 
http://stackoverflow.com/a/20643813/1379951

Is there an equivalent in PIXI ?

**Comment by englercj** [comment]
Have you tried doing something similar? All that is doing is having a big white semi-transparent square drawn behind the scene. I can think of one quick way to do that.

**Comment by weepy** [comment]
Hm so maybe I didn't quite understand the THREE example properly.  

What I'm trying to do is put these 'trails' over the top of other content, so really I need to be able to reduce the alpha channel of the previous buffer each frame. I don't know if this is possible.

This is the same effect in Canvas : http://jsfiddle.net/03hLme9q/   -- as you can see the canvas is transparent and the red html body is showing through.

**Comment by englercj** [comment]
You can do that with transparency but it will be more complex. You will need to manage a couple texture buffers and redraw the previous scene with less transparency each frame.

Basically draw the scene to a texture, and display that behind the actual scene. Each frame you redraw the backing texture with less transparency and then draw the current scene on top. Rinse repeat.

**Comment by weepy** [comment]
Sweet. So pretty much the same idea as in Canvas.

When you say "texture buffer" - do you mean a PIXI.RenderTexture ?

**Comment by englercj** [comment]
RenderTexture will work fine :)

**Comment by GoodBoyDigital** [comment]
closing as this looks nice and resolved :+1:
