### ISSUE TITLE
Texture doesn't display when set the trim before it loaded

### ISSUE THREAD

**Issue by feirlau** [pixijs/pixi.js#2157]
var img = new Image();
img.src = "00000.png";
var texture = new PIXI.Texture(new PIXI.BaseTexture(img));
texture.trim = new PIXI.Rectangle(40, 40, 100, 120);
var sp = new PIXI.Sprite(texture);
stage.addChild(sp);

if remove the line texture.trim, it will show correctly

**Comment by flgame** [comment]
help!!!!!

**Comment by ivanpopelyshev** [comment]
What are you trying to accomplish with using "trim" ?

**Comment by flgame** [comment]
@ivanpopelyshev move the texture to the position, and the texture is used by PIXI.extras.MovieClip.textures

**Comment by ivanpopelyshev** [comment]
that's not trim, that's frame.

```js
var texture = new PIXI.Texture(new PIXI.BaseTexture(img), new PIXI.Rectangle(40, 40, 100, 120));
```
```

**Comment by flgame** [comment]
@ivanpopelyshev thanks. 
not frame, frame is part of a big img, i just want to position the whole texture.

**Comment by ivanpopelyshev** [comment]
Which version of PIXI are you using? v3 and v4 have different API for that

**Comment by flgame** [comment]
@ivanpopelyshev 
pixi.js - v3.0.10
Compiled 2016-03-31T20:39:38.722Z

**Comment by ivanpopelyshev** [comment]
```js
var frame = new PIXI.Texture(0, 0, width, height);
var crop = new PIXI.Texture(0, 0, width, height);
var trim = new PIXI.Texture(offset_x, offset_y, BIG_WIDTH, BIG_HEIGHT);
var texture = new PIXI.Texture(baseTexture, frame, crop, trim);
```

**Comment by flgame** [comment]
@ivanpopelyshev thanks, but can't work

**Comment by ivanpopelyshev** [comment]
Can't help you, I still dont understand what do you want to do, you didnt even give me that image and didnt provide all the variables.

**Comment by GoodBoyDigital** [comment]
closing as sure this is fixed in v4 👍
