### ISSUE TITLE
Adding Float Point and Half Float Point texture support for GPU computing

### ISSUE THREAD

**Issue by edankwan** [pixijs/pixi.js#2158]
Most mobile devices support half float point and half float point linear filter. I think it can be very useful to use GPU to do some calculation.

**Comment by GoodBoyDigital** [comment]
good shout! v4 will have floating point textures for sure :+1:

**Comment by GoodBoyDigital** [comment]
v4 uses pixi-gl-core that has the ability to use floating point textures, great fun! :+1:
