### ISSUE TITLE
Sprite doesn't display after sprite.width = 0 and sprite.width = nonzero number

### ISSUE THREAD

**Issue by ayamada** [pixijs/pixi.js#2159]
See http://plnkr.co/edit/iuk2n6fSVmQsbokd1A4p?p=preview .

`sp.width = number` work well.
But, this code doesn't work after to run `sp.width = 0`.
`sp` is not display, if any i ran `sp.width = nonzero_number` !

Sorry for my poor english ...

**Comment by englercj** [comment]
https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/Sprite.js#L116

Because of this line. `sign(0) === 0` which causes it never to be a non-zero value. Thanks for bringing this up.

**Comment by englercj** [comment]
Closed by #2166.
