### ISSUE TITLE
Blend mode doesn't work if we set a mask on the sprite

### ISSUE THREAD

**Issue by arthurmuchir** [pixijs/pixi.js#2160]
If we apply a blendMode to a sprite and then set a mask to this sprite, the blendMode will not be applied anymore.

http://jsfiddle.net/avOff/qcgv8s30/3/

If you comment line 20, you will see the expected result (without the mask).

**Comment by GoodBoyDigital** [comment]
Howdy! 

Using a sprite mask is the same as using a filter. Filters and blend modes are currently in compatible as the content is rendered to a separate texture first. 

Best way round this is to use a graphics object for the mask instead: http://jsfiddle.net/j439aw7o/

Hope that helps!

**Comment by arthurmuchir** [comment]
Hi @GoodBoyDigital !

Thanks for your time and work, I did it with graphics.
