### ISSUE TITLE
Masks much slower than expected.

### ISSUE THREAD

**Issue by jordwalke** [pixijs/pixi.js#2163]
I tried an experiment where I had added masks to a majority of the views in my scene. The entire experience basically came to a stop (moving at about 5fps). I know that masks can be somewhat expensive, but I didn't expect them to be *this* expensive. For example, I also know that blending opacity could be expensive, so just to compare, I disabled all the masks and set everything in the experience to opacity 0.5. It was still butter smooth (just as a reference point for performance). My `DisplayObject` hierarchy is approximately 5 levels deep if that matters.

I was curious if you could give some general perspective on masking performance and if there's anything I can do to optimize this.

**Comment by GoodBoyDigital** [comment]
Hi Jordan, 

More info / an example we can debug would be really helpful. Currently there is not enough info to know what may be causing the issue. Are you using graphics masks or bitmap masks? Which browser are you running etc.

Opacity will always be a LOT faster than masking (opacity will have very little effect on performance). Masking can be a lot more complicated as it requires the use of a filter (if its sprite based) or the stencil buffer (if its graphic based).  Graphics masks tend to be a little cheaper.

Thanks!

**Comment by jordwalke** [comment]
I'll try to get a little sample (kind of difficult in this case), but in short, I was using a Graphics mask on iOS. I had a relatively deep Container graph with many of them having Graphics based masks (added as children so that their positions track with the container). Some of the container with Graphics masks had children that were also containers that had graphics based masks and so on.

Even an iPhone 6 was very slow. I opened up the iPhone simulator and all of these areas showed up as "blended layers" - you can toggle "Show Blended Layers" in the Simulator menu bar. If I removed all of the masking, then things got really fast.

Keep up the great work on this truly fantastic project. (Also, it's good to know about opacity being generally faster)

**Comment by GoodBoyDigital** [comment]
Ah! yes, I believe this is actually an IOS issue. I have two ipad Airs in the office. One is IOS8.1 and the other IOS9. Most content in webGL runs way faster on the IOS8 ipad :(

Something has changed in IOS to make masks run much slower. I think this is down to to the usage of the stencil buffer. It also seems waaay slower when it comes to texture uploads too. Either way it definitely needs further investigation as it may be a bug we will need to register with apple. 

As a result of this recent update my mrs' 4 year old HTC1 runs webGL faster than my on iphone 6 if masks are involved. This makes me sad :(

If you could find the time to create an example demoing the issue, I can then use it to debug and get to the root. 

Cheers!

**Comment by JiDW** [comment]
It's not just IOS, it's every mobile devices. Masks are indeed a performance bottleneck and you should avoid them as much as you can on a mobile device. Most things that we are used to do with a mask can be done another way, so just make sure than you can't do what you want to do without mask before using them.

**Comment by jordwalke** [comment]
To be clear, my issue was also on iOS 8.

@GoodBoyDigital: I'm curious what you did to reproduce the issue. If it's an issue with iOS, I can get an issue into Apple's issue tracking system ASAP (timing is really important to get fixes into various releases).

But you have to wonder - *tons* of UI elements (and all of webkit) uses clipping very liberally - so why isn't the issue surfacing in all of those other systems such as CoreAnimation/WebKit?

**Comment by jordwalke** [comment]
I'm working on getting a small reproducable example, but this is really interesting: I stopped adding all these graphics objects as masks, and merely kept them as children. The performance issues were still there!

**Comment by GoodBoyDigital** [comment]
Cool, this example will be really handy to test against!

With regards to the IOS specific issue - its more to do with the webGL implementation in webKit  rather than the OS itself.

**Comment by jordwalke** [comment]
Here is some results from the profile on device (iOS8):

- (`Container.prototype.renderWebGL`(line 7054) calls `SpriteRenderer.flush` 12 times in one frame.
-  Total time spent in `SpriteRenderer.flush` in that frame (all twelve together) is 24ms on device (profile mode).
- `SpriteRenderer.flush` eventually invokes `gl.bufferSubData` each of those twelve times totalling 14ms on device profile.
- `SpriteRenderer.flush` makes 56 subcalls to renderBatch which in total consume 6ms.


Does this sound reasonable to you that `SpriteRenderer.flush` should be called 12 times in one frame during an animation that is not allocating any new `Sprites/masks`(it is merely moving things on screen)? Does it sounds reasonable that this would take `24ms` to flush 12 sprites if masks are involved?

**Comment by GoodBoyDigital** [comment]
Hi there! the above looks correct, but an example so we can debug the above would be great. Are you using sprite sheets?

**Comment by jordwalke** [comment]
I am not using Sprite Sheets. It's really difficult to generate an example because I'm using Pixi in such a roundabout way. But the actual scene is fairly simple. A tree of about four clipped layers deep, fifty total display objects.

**Comment by GoodBoyDigital** [comment]
cool, without an example its very tricky do diagnose if there is an issue i'm afraid :/ If you could boil down what you have into an example we can take a look. The other thing I can recommend is It might be worth trying to use the v4.0.0 branch to see if perf is improved for your use case. (its almost ready for release!)

**Comment by GoodBoyDigital** [comment]
closing this for now. Do let me know how v4 works out! :+1:

**Comment by darting** [comment]
@GoodBoyDigital  cool, in my example, v4 will faster than v3 around 20fps for masking. when the v4 will release? any broken api?

device: iPhone6+IOS9

**Comment by jordwalke** [comment]
@darting Could you post an example of the slow masking (I am unable to, but it would be very helpful if you could). Did you say v4 is 20fps *faster* than in v3? So in v3 it was 40fps and in v4 it is 60fps?
