### ISSUE TITLE
Problems with generateTexture on Sprite Pixi.js 3.0.6

### ISSUE THREAD

**Issue by Cyberguille** [pixijs/pixi.js#2164]
If you use generateTexture() to get the texture of a Sprite and apply this texture to a Sprite them WebGL throws an warning and the effect does not work:

GroupMarkerNotSet(crbug.com/242999)!:94335106]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

Code Example:

```js
  var stage = new PIXI.Container();

    // create a renderer instance.
    var renderer = PIXI.autoDetectRenderer(867, 650);

    // add the renderer view element to the DOM
    document.body.appendChild(renderer.view);

   var img = place({content:"apple",style:"Number_Quiz",type:"img"})
   img.x=img.y= 200;
   stage.addChild(img);
  animate();
    function animate() {

        requestAnimationFrame(animate);
        renderer.render(stage);
    }
 function place(item){
                var result =  new PIXI.DisplayObjectContainer();       
                //image
                var img =  PIXI.Sprite.fromImage("media/ingles/resources/img/" + item.content + ".png");
                result.addChild(img);
                break;
               var sprite = new PIXI.Sprite(result.generateTexture(renderer))
               return sprite;
    }

  ```

**Comment by ivanpopelyshev** [comment]
That image is not pre-loaded, so its width/height is 0, so result width/height is also zero, so generateTexture creates texture of size 0. 

Look at how generateTexture() works, and how DisplayObjectContainer gets its width,height and localBounds.

**Comment by englercj** [comment]
Your generating a texture before the image is loaded, so it generates a teture of nothing because that is what there is so far.

Wait until the texture completes loading, or even better preload it first.

**Comment by Cyberguille** [comment]
Thanks, I had discovered, but anyway thanks for confirm it. Many times I have to use a flag with an timer or more elegant  with an event such as OnComplete.
