### ISSUE TITLE
I could't use WebGLRenderer

### ISSUE THREAD

**Issue by luozan** [pixijs/pixi.js#2165]
TypeError: undefined is not an object (evaluating 'this.handleContextLost.bind')
WebGLRendererWebGLRenderer.js:84
initmain.js:39
（匿名函数）main.js:89
emitindex.js:123
_onCompleteLoader.js:432
（匿名函数）Loader.js:457
（匿名函数）
（匿名函数）async.js:190
（匿名函数）pixi-tiled.js:504
emitindex.js:143
onloadBaseTexture.js:281
function.bind

CanvasRenderer is true

**Comment by englercj** [comment]
Please share the code you used. Most likely you forgot the `new` keyword.

**Comment by luozan** [comment]
thanks,
