### ISSUE TITLE
Incoherent docs for Texture .frame .crop .trim

### ISSUE THREAD

**Issue by yotamlaufer** [pixijs/pixi.js#2168]
Maybe it's me, but I cannot figure out the actual function of these properties.

In my use case, I have a large BaseTexture, say 1024 x 256, and I'd like to create a texture with the following new PIXI.Rectangle(256, 0, 256, 256)

I have tried many combinations of new PIXI.Texture(base, rect, rect, rect) and failed. Can you please clarify?

Thanks

**Comment by englercj** [comment]
All you need is `new PIXI.Texture(base, rect)` no need to use trim/crop.

**Comment by GoodBoyDigital** [comment]
cc @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
Fixed that in v4.

**Comment by GoodBoyDigital** [comment]
👍

**Comment by download13** [comment]
Where can we read this updated documentation? I would love to know what these mean.
