### ISSUE TITLE
is there a way to use gl framebuffer objects?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#2170]
I want to write some shader effects that do something like this:

read from texture 1
run fragment shader on it
send results to texture 2
swap texture 1 and texture 2
repeat

the idea being that some effects require persistence of state. webgl makes this fairly straightforward with the ability to bind framebuffers. I'm wondering if I can do this with pixi, or have I gone too far under the hood, where I'd be better off doing the rendering directly in webgl.

**Comment by englercj** [comment]
Check out the `BloomFilter` which has to make use of multiple passes and buffer. Also, `RenderTexture`s use framebuffers under the hood.

**Comment by GoodBoyDigital** [comment]
closing for now as this seems answered. for v4 this should be a little easier to get closer to WebGL like this.
