### ISSUE TITLE
use renderTexture to render a scaled container cause wrong hitarea

### ISSUE THREAD

**Issue by siehc** [pixijs/pixi.js#2172]
Here is the fiddle.
https://jsfiddle.net/yq8t1Lq6/

an scaled container
```
var stage = new PIXI.Container();
stage.scale.x = stage.scale.y = 0.5;
```

then just render it by renderTexture in animate function.
```
function animate() {
	requestAnimationFrame( animate );
	
	// render the stage   
	renderer.render(stage);
        
	//cause wrong hit area
	renderTexture.render(stage, null, true);
	mirrorRenderer.render(mirrorStage);
}
```

cause the bunny's hitarea at wrong position.

**Comment by siehc** [comment]
After doing some trace of code. The problem is at RenderTexture.render(). 
When RenderTexture.render() is invoked. It changed worldTransform matrix and recover it when render done. So, if I call renderTexture.render() in animate function, worldTransform is always changed and lead to Sprite.containsPoint always got an wrong result.

Is there other way to render a stage to another renderer?

**Comment by GoodBoyDigital** [comment]
this should work in v4 now 👍
