### ISSUE TITLE
unexpected click propagation behaviour with Graphics 

### ISSUE THREAD

**Issue by uorbe001** [pixijs/pixi.js#2173]
I have found a weird issue related to the Graphics class that I need some help with. We have a Graphics object (rectangle) as a background for a "dialog", which has buttons as children. 

What is happening, is that triggering a click on the button(s) make the `hit` variable [here](https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/interaction/InteractionManager.js#L371) go to true as expected, but then it gets to [this line](https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/interaction/InteractionManager.js#L394) and that returns false because `graphicsData` [here](https://github.com/pixijs/pixi.js/blob/master/src/core/graphics/Graphics.js#L927) has nothing inside it. 

This is causing the event propagation to keep going despite already having clicked the object that is on top. My issue is, I don't know if this is because we are using the Graphics object wrong and we are supposed to set the GraphicsData object manually, or this is a proper bug (because, well, I'd expect the hit to be returned as true if it gets [here](https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/interaction/InteractionManager.js#L386) with a child being hit).

Can anybody tell me if I'm right assuming this should return true when a child as returned true? Maybe there's a good reason against it that I fail to see. I'm happy to change it myself if that's the case.

**Comment by GoodBoyDigital** [comment]
should be cool in v4 👍
