### ISSUE TITLE
Anti-Aliasing Chrome vs Firefox

### ISSUE THREAD

**Issue by Mathieu-Martin** [pixijs/pixi.js#2174]
Hi;

I have a concern with the drawing of graphics here in an arc. The antialiasing under Firefox creates a deformed version compared with Chrome. It is a problem of the stencil buffer webgl? Needs that it passes by the render texture to avoid this problem?

( Anti-alising: True, FXAA: False)

CodePen: 
http://codepen.io/Mathieu-Martin/pen/yYvJBQ

Chrome 
![WebGl Chrome](http://imageshack.com/a/img907/8008/Ye6FSk.png)

FireFox 
![FireFox Chrome](http://imageshack.com/a/img633/5467/yCyt5A.png)

Thank you in advance!

**Comment by englercj** [comment]
Graphics objects are not anti-aliased because they are drawn with the stencil buffer. You will need to use the FXAA filter with them if you don't want them to be aliased.

**Comment by Mathieu-Martin** [comment]
I have the same problem when I force FXAA to true :/

**Comment by englercj** [comment]
antialias and forceFXAA need to both be true IIRC.

**Comment by Mathieu-Martin** [comment]
"FXAA antialiasing being used instead of native antialiasing" message in the console. But no affect on my graphics ? 

Do you have a exemple for use Fxaa filters ?

**Comment by Mathieu-Martin** [comment]
Hello, do you have a solution for this problem or exemple for use FXAA with graphics?

**Comment by englercj** [comment]
Just searching for "fxaa graphics" on the github issues real fast:

https://github.com/pixijs/pixi.js/issues/1566#issuecomment-84454085
https://github.com/pixijs/pixi.js/issues/1974#issuecomment-124918341

Either cache is as a texture, or apply FXAA to it.

**Comment by GoodBoyDigital** [comment]
FXAA has been removed as an automatic solution in v4 as it causes more issues than it solves. It will be available as a plugin soon.
