### ISSUE TITLE
DisplayObject.updateTransform() Edge-Case

### ISSUE THREAD

**Issue by maxattack** [pixijs/pixi.js#2175]
DisplayObject's updateTransform method sample's the parent's worldTransform field without validating that it's also correct, which can lead to incorrect results. I'm commonly seeing this in initialization code where children are being appended. My current workaround is to manually updateTransform on the whole chain, but that's kinda irritating.

**Comment by englercj** [comment]
the parent will be correct because the parent is what calls update transform (after updating its own).

If its incorrect then you might be doing something we haven't thought of. Do you have a code example that exhibits this behavior?

**Comment by GoodBoyDigital** [comment]
Hello! Closing this for now. @maxattack if this is still an issue for you please provide an example and we can reopen. cheers!
