### ISSUE TITLE
Please fix the WebGL typo.

### ISSUE THREAD

**Issue by dixiepixie** [pixijs/pixi.js#2178]
All over the website, in the documentation and source code, you have for some reason "webGL" instead of "WebGL", even though the latter is the official and only spelling. Why insist on "webGL"? It really bothers some of us. Why insist on incorrect terms?

**Comment by englercj** [comment]
We aren't insisting on anything, and I'm not sure why it bothers you so much that you have to create an entirely new account to complain about it after we muted you last round.

Same answer as before: If you are that upset about it, put in a PR that fixes it.

**Comment by englercj** [comment]
Searching the code I found only 6 places where this is true, feel free to fix them:

1. https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/renderers/webgl/WebGLRenderer.js#L14
2. https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/textures/RenderTexture.js#L123
3. https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/textures/Texture.js#L80
4. https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/display/DisplayObject.js#L241
5. https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/renderers/SystemRenderer.js#L7
6. https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/renderers/canvas/CanvasRenderer.js#L8

**Comment by photonstorm** [comment]
Damn you beat me to it @englercj :) I thought this nutjob troll had vanished. Sadly seem's to have come back again.
