### ISSUE TITLE
The best approach to color sprites?

### ISSUE THREAD

**Issue by RanzQ** [pixijs/pixi.js#2182]
I'm creating an UI for which I need to create sprites that can have all the the different hue degrees as their color (or at least 100 or something). I can't achieve the result I'm after neither by using tint or ColorMatrixFilter.

Here's the problem that I have with tint and filter. First one is the original sprite, second is tinted, third is modified using filter and the last one is the result I'd want (I just changed hue using photoshop):

http://codepen.io/anon/pen/vNaqgM

I also noticed that when I render 500+ sprites with all having their own filter, the render is very heavy. Using `cacheAsBitmap` for the container helped on that though.

I have my sprite images as SVG (I convert them using canvas) and I can easily color them by changing the svg fill. How should I create the textures and sprites in this situation?

**Comment by RanzQ** [comment]
Tint could be used if I create the sprites from two components like this:

![image](https://cloud.githubusercontent.com/assets/1150613/10933291/2e2a79ca-82e0-11e5-98f7-6309160eb687.png)

Would this be a good idea, tinting that base shape and applying a transparent sprite on top of it?

**Comment by englercj** [comment]
I wonder if you just used the gray image, and the tint feature if that could get you what you wanted? I think the main problem is that you aren't just tinting the image, you actually have a white overlay on an image you tint, maybe make the "glaze" a separate sprite that is a child?

> I also noticed that when I render 500+ sprites with all having their own filter, the render is very heavy. Using cacheAsBitmap for the container helped on that though.

Adding a filter to a sprite breaks the batch, so 500 filtered sprites is 500 draw calls instead of potentially being just one.

> I have my sprite images as SVG (I convert them using canvas) and I can easily color them by changing the svg fill. How should I create the textures and sprites in this situation?

You can create a texture from a canvas. I would suggest coloring and drawing all the options to a single canvas. Then use that canvas as the base texture for multiple textures/sprites. For example:

```js
//pretend "canvas" has all your arrows drawn to it:
var arrowBaseTexture = new PIXI.BaseTexture(canvas);
var arrowWidth = 100;
var arrowHeight = 100;


// the rectangle is the "frame" of the image to use for this texture, adjust to your size
var arrow1 = new PIXI.Texture(arrowBaseTexture, new PIXI.Rectangle(0, 0, arrowWidth, arrowHeight));
var arrow2 = new PIXI.Texture(arrowBaseTexture, new PIXI.Rectangle(100, 100, arrowWidth, arrowHeight));

//etc.
```

In that example they can all be different colors and such, but since they share a source base texture it will still be ~1 draw call.

**Comment by RanzQ** [comment]
@englercj Thanks for the tips, I'll do some tests. You said a filter breaks the batch, what about tint?

**Comment by englercj** [comment]
No, tint does not break the batch. It is included in the default shader, which is why it is so fast and is batching friendly.

**Comment by GoodBoyDigital** [comment]
hey all! Closing this for now as this seems resolved. thanks!

**Comment by jagi** [comment]
I had similar problem and I've came with a solution that is similar to how Photoshop's Photo Filter works with the Preserve Luminosity option turned on:
```js
var filter = new PIXI.filters.ColorMatrixFilter();
var color = PIXI.utils.hex2rgb(0x1496b4);
filter.matrix = [
  1.000 * color[0], 1 / 3 * color[0], 1 / 3 * color[0], 0, 0,
  1 / 3 * color[1], 1.000 * color[1], 1 / 3 * color[1], 0, 0,
  1 / 3 * color[2], 1 / 3 * color[2], 1.000 * color[2], 0, 0,
  0, 0, 0, 1, 0,
];
```
and Preserver Luminosity turned off:
```js
var filter = new PIXI.filters.ColorMatrixFilter();
var color = PIXI.utils.hex2rgb(0x1496b4);
filter.matrix = [
  1 / 3 * color[0], 1 / 3 * color[0], 1 / 3 * color[0], 0, 0,
  1 / 3 * color[1], 1 / 3 * color[1], 1 / 3 * color[1], 0, 0,
  1 / 3 * color[2], 1 / 3 * color[2], 1 / 3 * color[2], 0, 0,
  0, 0, 0, 1, 0,
];
```
I hope it will help
