### ISSUE TITLE
"roundPixels" incorrect on hiDPI screens

### ISSUE THREAD

**Issue by GordoRank** [pixijs/pixi.js#2185]
I don't have a hiDPI screen to hand so I suppose it is possible that what I am seeing is down to the Firefox HiDPI emulation.  But that said having peered through the source code of PIXI it does indeed appear to be a bug.

I have only tested this with the WebGL rendere.

Currently if you enable ```roundPixels``` and have a screen with a pixelRatio of ```2```, everything gets rounded to every full pixel.  When in fact you want everything to be rounding to every ```0.5 pixels```.  Or in otherwords, it should be rounding to the nearest pixel ```fraction``` of the screen.

e.g. On a screen with a pixelRatio of 3, it should round to every ```0.333333``` pixels.  PixelRatio of 4? round to ```0.25``` etc.

Assuming that I have not dramatically misunderstood something then the fix is really quite easy.

Just change the rounding in the Webgl renderer to account for the resolution, like so:

```

 if (this.renderer.roundPixels)
        {
            // xy
            positions[index] = Math.round((a * w1 + c * h1 + tx) * this.renderer.resolution)/this.renderer.resolution;
            positions[index+1] = Math.round((d * h1 + b * w1 + ty) * this.renderer.resolution)/this.renderer.resolution;

            // xy
            positions[index+5] = Math.round((a * w0 + c * h1 + tx) * this.renderer.resolution)/this.renderer.resolution;
            positions[index+6] = Math.round((d * h1 + b * w0 + ty) * this.renderer.resolution)/this.renderer.resolution;

            // xy
            positions[index+10] = Math.round((a * w0 + c * h0 + tx) * this.renderer.resolution)/this.renderer.resolution;
            positions[index+11] = Math.round((d * h0 + b * w0 + ty) * this.renderer.resolution)/this.renderer.resolution;

            // xy
            positions[index+15] = Math.round((a * w1 + c * h0 + tx) * this.renderer.resolution)/this.renderer.resolution;
            positions[index+16] = Math.round((d * h0 + b * w1 + ty) * this.renderer.resolution)/this.renderer.resolution;
        }
```

Changing to the above in the webGL render makes ```roundPixels``` snap properly, inline with the DPI of the screen.

Obviously the above is using ```Math.round``` which is slower than other forms of javascript rounding like bitwise operators etc.  But this was the quickest way to fix the issue.  I'm sure someone else will have a more performant method.

**Comment by GoodBoyDigital** [comment]
Great catch @GordoRank. Thanks for providing the solution too :)
I have just pushed the fix to the dev branch :+1:
