### ISSUE TITLE
Non-managed textures can crash the app after user destroys second renderer.

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2186]
Lets continue discussion: https://github.com/pixijs/pixi.js/pull/2089

```javascript
var myCanvas = document.createElement("canvas");
//draw something on canvas
var texture = new BaseTexture(myCanvas);
var renderer1=new WebGLRenderer();
var renderer2=new WebGLRenderer();
renderer1.updateTexture(texture);
renderer2.updateTexture(texture);
renderer2.destroy();
renderer1.updateTexture(texture);
```

at this point, texture will send event to renderer2 which will fall on trying to find "this.gl.id".

renderer2.destroy() unsubscribes only from managed textures, e.t.c. "BaseTexture.fromCanvas"
I call "BaseTexture.fromCanvas" managed, because they appear in the texture cache.

**Comment by englercj** [comment]
I just made a commit that should fix this up: 884ad5b578caf8173c1fed7c0e7b397e56937d06
