### ISSUE TITLE
PIXI.utils.canUseNewCanvasBlendModes() is unreliable on Chrome

### ISSUE THREAD

**Issue by dtinth** [pixijs/pixi.js#2188]
I found a problem on a game I’m developing using CanvasRenderer that sometimes blend mode works (in particular, the screen mode), sometimes it doesn’t.

Calling `PIXI.utils.canUseNewCanvasBlendModes()` on http://pixijs.github.io/examples/ (which is running Pixi.js 3.0.6) yields an unreliable result:

![screen shot 2015-11-08 at 21 53 56](https://cloud.githubusercontent.com/assets/193136/11020938/4451eb4e-8663-11e5-8d4b-21a6626fc7ce.png)

46.0.2490.80 (64-bit)
Mac OS X El Capitan

Since I don’t plan to support Internet Explorer right now, my workaround is to do this:

```js
function hackPIXIToForceNewBlendModes () {
  PIXI.utils.canUseNewCanvasBlendModes = () => true
}
```

I suspect that the problem may be that the `Image` is loaded asynchronously (i.e. in another thread) but sometimes it decodes fast enough to be used synchronously. Maybe, creating an image data from scratch instead of loading from PNG files may be able to fix this.

**Comment by ivanpopelyshev** [comment]
Its the same as https://github.com/pixijs/pixi.js/issues/2171 . Wait for next chrome update :)

**Comment by GoodBoyDigital** [comment]
fixed in v4 :+1:
