### ISSUE TITLE
Optimize GraphicsRenderer.prototype.buildLine

### ISSUE THREAD

**Issue by grovesNL** [pixijs/pixi.js#2189]
As the comment in the code indicates, there is some optimization left to be performed on `GraphicsRenderer.prototype.buildLine` which creates line vertices. I thought I would raise this issue to start the discussion and possibly contribute if possible.

Does the `TODO OPTIMISATION` suggest JavaScript optimizations or the algorithm itself? Which algorithm is currently used for line drawing (i.e. especially with regards to the steep angle approximation issue referenced in #1950)? Have alternatives been considered?

**Comment by ivanpopelyshev** [comment]
Wow, no one PR-ed that. Ok, lets fix this: https://github.com/pixijs/pixi.js/pull/2190

Lines still look like shit even with new WebGLRenderer(...{antialias:true }). Any ideas on how to fix that?

**Comment by grovesNL** [comment]
After digging into the source some more it appears Pixi used an approach influenced heavily by [this post](http://artgrammer.blogspot.co.uk/2011/07/drawing-polylines-by-tessellation.html).

There is a series of blog posts that compare Pixi's `buildLine` to an approach used in mapbox-gl-js and another library ([Pixi post](http://blog.sumbera.com/2014/10/23/webgl-polyline-tessellation-with-pixi-js/), [Mapbox-gl-js post](http://blog.sumbera.com/2014/10/27/webgl-polyline-tessellation-with-mapbox-gl-js/)). It may be good to compare the methodologies and and see if there is room for improvement. The blog post concluded that the Mapbox approach was superior. It would be interesting to compare performance and degenerate cases in each.

**Comment by GoodBoyDigital** [comment]
Closing this for now as we have many other line issues open. The solution to this i feel is to build a new line rendering system. Something a little more advanced..
