### ISSUE TITLE
MSPointer events are not implemented in the InteractionManager

### ISSUE THREAD

**Issue by stephenweaver** [pixijs/pixi.js#2191]
UPDATE: Just checked into the source code and I noticed that MSPointer events are not implemented. The issue name has been updated accordingly. Is this in the pipeline to be added?

**Comment by englercj** [comment]
Can you share [more information][guide] please?

- What browser/OS version?
- Create a reproduction case that we can view the error on and debug.

Just the bug title makes me confused what you expect PIXI to do. If IE is sending mouse events instead of touch events, what can we do about it?

[guide]:https://github.com/pixijs/pixi.js/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by stephenweaver** [comment]
Sure, I'm using windows 8 with IE 11. 

Reproduction example can be found here http://www.goodboydigital.com/pixijs/examples/8/.

The code that I'm using specifically contains this. When I use touch in IE, onMouseDown gets called instead of onTouchStart. 

function InteractiveObject() {
  PIXI.Container.call(this);

  this.on('mouseover', this.onMouseOver);
  this.on('mouseout', this.onMouseOut);
  this.on('mousedown', this.onMouseDown);
  this.on('mouseup', this.onMouseUp);
  this.on('mouseupoutside', this.onMouseUp);
  this.on('touchstart', this.onTouchStart);
  this.on('touchmove', this.onTouchMove);
  this.on('touchend', this.onTouchEnd);
  this.on('touchendoutside', this.onTouchEnd);
}

InteractiveObject.constructor = InteractiveObject;
InteractiveObject.prototype = Object.create(PIXI.Container.prototype);
module.exports = InteractiveObject;

**Comment by englercj** [comment]
So are you asking for pointer events so you don't have to bind both mouse and touch events?

**Comment by stephenweaver** [comment]
It's not that I don't want to bind to both mouse and touch events, because that is working just fine for chrome. Internet explore doesn't use touchdown.

Here's a quick jsfiddler https://jsfiddle.net/cLzz4e2x/ to try in IE and Chrome.

**Comment by englercj** [comment]
Ah, I see: http://caniuse.com/#feat=touch

I'll add this to the list of things to include in the IM rewrite: #2071

**Comment by stephenweaver** [comment]
Thanks!

**Comment by drkibitz** [comment]
Here's another :electric_plug:  for my opinion, that PIXI should not be in charge of listening to DOM events. This will be a constant struggle as we have already seen, and I believe is a perfect job for #2071. If we want to provide an interaction layer that does listen to dom events, it should at least be built around a solid public interface that dogfoods it's own virtual event abstraction.

**Comment by cvissie** [comment]
Is this still in the pipeline to be fixed?

Amazingly for the first time in our game's lifetime someone has complained that IE10 on Win7 he can't click on a button in our game (we of course advised to make use of Chrome instead) 

But as a precautionary measure anyway I decided to make use of a custom pixi build with the following code:

```javascript
    var evtMouseMove = 'mousemove';
    var evtMouseDown = 'mousedown';
    var evtMouseOut = 'mouseout';

    if (window.navigator.msPointerEnabled)
    {
        this.interactionDOMElement.style['-ms-content-zooming'] = 'none';
        this.interactionDOMElement.style['-ms-touch-action'] = 'none';

        evtMouseMove = "MSPointerMove";
        evtMouseOut = "MSPointerOut";
        evtMouseDown = "MSPointerDown";
    }

    window.document.addEventListener(evtMouseMove,    this.onMouseMove, true);
    this.interactionDOMElement.addEventListener(evtMouseDown,    this.onMouseDown, true);
    this.interactionDOMElement.addEventListener(evtMouseOut,     this.onMouseOut, true);
```

**Comment by themoonrat** [comment]
I have a PR which adds support for pointer events, as well as the ability to 'normalise' all events into a pointer event if it's not natively supported. This way you can do
`sprite.on( 'pointerdown', function(){ console.log('sprite pressed') } );
And not have to worry about whether that's from a mouse or from a touch. Even if the PR doesn't make it into PIXI, might be of use to know it's there and take what you need into your custom build :)

**Comment by GoodBoyDigital** [comment]
Nice! Yes this is definitely something that needs to be looked into.. I
will check out the PR soon. Pointers would be good :)

**Comment by themoonrat** [comment]
@englercj This can be closed down after https://github.com/pixijs/pixi.js/pull/2997 was merged
