### ISSUE TITLE
Pixi Cannot Render Emoji

### ISSUE THREAD

**Issue by KenPowers** [pixijs/pixi.js#2192]
Plain Canvas can render Emoji but Pixi can't. From what I can tell Pixi does text by drawing to a canvas which it then uses as a texture, so theoretically this should be possible unless I'm overlooking something.

See code here: https://gist.github.com/KenPowers/be39b6745dab4e9d5269

`npm run canvas`:

![image](https://cloud.githubusercontent.com/assets/174864/11160954/e7fa1cdc-8a3f-11e5-9be8-31bcb42fc217.png)

`npm run pixi`:

![image](https://cloud.githubusercontent.com/assets/174864/11160946/c18aa3a0-8a3f-11e5-8ad5-7a35c10fb7bc.png)

**Comment by KenPowers** [comment]
Verified in Chrome 46.0.2490.80 (64-bit) and Firefox 42.0 on Mac OS X 10.11.1.

Interestingly, Pixi can render Emoji in Safari 9.0.1 (11601.2.7.2):

![image](https://cloud.githubusercontent.com/assets/174864/11161159/6a619576-8a43-11e5-981b-be0f71a5b1c4.png)

**Comment by grovesNL** [comment]
It writes the text character (not colored) on Chrome 46.0.2490.86 m (64-bit) on Windows 10. This doesn't seem to be a PIXI issue because it is merely calling `canvas.fillText`. Instead it seems to be a [browser issue and operating system issue](http://caniemoji.com/).

**Comment by KenPowers** [comment]
It seems strange to me though because just calling `fillText` directly works but it doesn't work with Pixi.

**Comment by grovesNL** [comment]
I noticed you are not setting the font properties in the Pixi example (Pixi assumes a default), but they are being set in the Canvas example. There could be other properties on the default Text instance that cause it to fail as well. Can you check if http://jsfiddle.net/grovesNL/xsrLog4g/ works for you?

**Comment by KenPowers** [comment]
Seems to be a problem with the default font used by Pixi. I set the font to `10px sans-serif` (canvas context default). Strange that it works in Safari, but this doesn't seem like an issue with Pixi itself.
