### ISSUE TITLE
BitmapText without using the loader?

### ISSUE THREAD

**Issue by sommerper** [pixijs/pixi.js#2196]
I have the image cached as a texture and the .fnt data in a string (or alternatively XML) assigned to a variable.
How would I go about creating a BitmapText directly without relying on the loader?

Ideally I would like to call **parse()** in **bitmapFontParser.js** but unfortunately it is not exposed.

Alternatively I would do something like this
```
PIXI.loaders.bitmapFontParser(asset.fnt, PIXI.utils.BaseTextureCache[this.assetUrl(asset.name)]);
```

But it throws an error saying this.add doesn't exist because it's not being run in the context of the loader.

Is there a workaround for this?

Many thanks in advance for any advice you might have.

**Comment by englercj** [comment]
Good call, we should expose these parsers better. I'll think on that for a bit, thanks for bringing it up

**Comment by englercj** [comment]
Now the parse function is exposed as `PIXI.loaders.parseBitmapFontData` in the latest `dev` of v4. Note that it expects an object as the first param with a `data` property that is the XML, and will add a property to that object called `bitmapFont` that is the parsed data.
