### ISSUE TITLE
Text cacheAsBitmap on canvas working incorrectly.

### ISSUE THREAD

**Issue by Excaa** [pixijs/pixi.js#2197]
I have 2 texts positioned to 50, 50 and 50,200. One is styled one is not. Both display correctly in webgl with cacheAsBitmap. When swapped to canvas however, the first text is rendered where the second text is. Moving the last added text moves all texts in the container. Moving first text does nothing.

Examples can be found in the following links.
https://dl.dropboxusercontent.com/u/8932415/textCache/canvas_cache.html
https://dl.dropboxusercontent.com/u/8932415/textCache/webgl_cache.html

**Comment by ivanpopelyshev** [comment]
PR https://github.com/pixijs/pixi.js/pull/2199

**Comment by GoodBoyDigital** [comment]
all fixed thanks to @ivanpopelyshev :+1:
