### ISSUE TITLE
Setting text cacheAsBitmap to null before it has been set to true causes exception

### ISSUE THREAD

**Issue by Excaa** [pixijs/pixi.js#2198]
Not sure if this happens intentionally or not, but if text-objects cacheAsBitmap is set to null without first setting it to true then exception is thrown in containers updateTransform-function "Uncaught TypeError: this.children[i].updateTransform is not a function". Setting the cache to false works correctly (as the internal value seems to be false initially).

In documentation cacheAsBitmap is instructed to be set to null to remove cache.

Link to test: https://dl.dropboxusercontent.com/u/8932415/textCache/canvas_remove_cache.html

**Comment by englercj** [comment]
`cacheAsBitmap` is a boolean value. Setting it to anything besides `false` or `true` is an error.

**Comment by Excaa** [comment]
Shouldn't this be correctly in the documentation then? Documentation says:
"Set this to true if you want this display object to be cached as a bitmap. This basically takes a snap shot of the display object as it is at that moment. It can provide a performance benefit for complex static displayObjects. To remove simply set this property to 'null'"

**Comment by englercj** [comment]
Then it should be updated, feel free to put in a PR that changes the documentation comments!
