### ISSUE TITLE
mouseover is triggered after mouseout when cursor quits the browser's window

### ISSUE THREAD

**Issue by jberube** [pixijs/pixi.js#2201]
When hovering a container that has listeners for mouseover and mouseout, this strange sequence occurs:

- mouseover (while really mousing over the container)
- mouseout (when the cursor exits the borwser window)
- mouseover (*after* quitting the window or while above the scrollbar)

You can reproduce here, http://jsfiddle.net/mk41egbt/8/ .Resize the browser window so the canvas overflows the browser first.

Looks related to #2071 to me :/

**Comment by themoonrat** [comment]
@englercj This can be closed, https://github.com/pixijs/pixi.js/pull/2996 fixes this issue
