### ISSUE TITLE
Font weight not working?

### ISSUE THREAD

**Issue by JaredSartin** [pixijs/pixi.js#2202]
Looks like #1037 - but in 3.0

I cannot get:
```
new PIXI.Text("foo", {font: "900 72px Work Sans"});
new PIXI.Text("bar", {font: "bold 48px Work Sans"});
```
 to render in that font for the life of me. Just seems to choose a Sans-Serif default. I am properly adding the text blocks AND making sure the font is loaded prior to the instantiation. Include of font below.

```
<link href='https://fonts.googleapis.com/css?family=Work+Sans:900,800,400,700' rel='stylesheet' type='text/css'>
```

**Comment by englercj** [comment]
We pass the font directly into the canvas without modification:

https://github.com/pixijs/pixi.js/blob/master/src/core/text/Text.js#L295

Most likely the font name isn't setup properly, or the font isn't actually loaded *and ready* by time you draw the text. You can test by replacing all your pixi code with a simple canvas draw of the text. Though, like I mentioned that is all we do anyway.

**Comment by JaredSartin** [comment]
Cool, I will investigate my assumptions!

On Thu, Nov 19, 2015 at 7:13 PM Chad Engler <notifications@github.com>
wrote:

> We pass the font directly into the canvas without modification:
>
> https://github.com/pixijs/pixi.js/blob/master/src/core/text/Text.js#L295
>
> Most likely the font name isn't setup properly, or the font isn't actually
> loaded *and ready* by time you draw the text. You can test by replacing
> all your pixi code with a simple canvas draw of the text. Though, like I
> mentioned that is all we do anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi.js/issues/2202#issuecomment-158266609>.
>
-- 
Jared Sartin
*Mobile *(269) 364-1735 | *Twitter* @JaredSartin
<http://twitter.com/JaredSartin>
*Website* <http://jared.sart.in/>

**Comment by GoodBoyDigital** [comment]
closing this for now as seems to be a font set up issue. :+1:
