### ISSUE TITLE
TilingSprite does not tile properly

### ISSUE THREAD

**Issue by vargad** [pixijs/pixi.js#2206]
When tiling a texture it omits the first row and column and duplicates the second: http://jsfiddle.net/vargad88/p0q3c6o3/

I think that this bug is originated from this change: https://github.com/pixijs/pixi.js/commit/2ca0a31584891510c1932a17d5d0836478284cd4

When I remove the "coord = clamp(coord, uPixelSize, uFrame.zw - uPixelSize);" line from th GLSL script it works well. I'm not sure what was the original issue and how that change solved it, hope we can find a solution that solves both issues.

**Comment by fmd** [comment]
I'm also getting this issue. Kind of worried about this being open since Nov 2015. Is this still occuring in v4?

**Comment by englercj** [comment]
The fiddle looks correct to me? http://jsfiddle.net/p0q3c6o3/1/

**Comment by fmd** [comment]
see how the top left pink pixel in the sprite is missing from the
tiledsprites

**Comment by englercj** [comment]
> see how the top left pink pixel in the sprite is missing from the tiledsprites

No, it looks correct to me:

![image](https://cloud.githubusercontent.com/assets/944497/18921451/ae94891c-8559-11e6-92f3-4620703af809.png)

Zoomed in in photoshop:

![image](https://cloud.githubusercontent.com/assets/944497/18921600/4d8c1f12-855a-11e6-88f1-a98a83e5512b.png)

What browser are you using, and is this fiddle any different for you: https://jsfiddle.net/ewg0tdyu/

I think the fact that the top-left red-box looks like it is smaller is just an optical illusion from the colored lines. Examining the pixels on my screen shows they are all the same size.

**Comment by fmd** [comment]
current, updated google chrome, still looks weird to me

<img width="1180" alt="screen shot 2016-09-28 at 17 06 14" src="https://cloud.githubusercontent.com/assets/2799915/18921800/0e90b3f6-859e-11e6-9972-8bdcdc450e67.png">

**Comment by englercj** [comment]
Oh shit, you know what (I keep forgetting this) my GFX card got blacklisted recently so I must be on the canvas renderer! MY BAD!

**Comment by ivanpopelyshev** [comment]
clamp is wrong.

clamp(coord, uPixelSize, uFrame.zw - uPixelSize); =>

clamp(coord, 0, uFrame.zw - uPixelSize);

Gonna fix it!

**Comment by ivanpopelyshev** [comment]
Fixed in #3048
