### ISSUE TITLE
Text = "" returns one space

### ISSUE THREAD

**Issue by eliase** [pixijs/pixi.js#2207]
Hello I'm working with pixi.js and this bug is still left. When you set a pixi.text to "". That is an empty string, it will automatically set it to " ", a string with one space. Is this a known bug?

**Comment by grovesNL** [comment]
This seems to be done intentionally in [`text = text.toString() || ' ';`](https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/text/Text.js#L226). Perhaps somebody can clarify if this is actually a bug.

**Comment by englercj** [comment]
What is the issue that this causes for you?

**Comment by adelciotto** [comment]
what kind of functionality are you looking for @eliase ? By setting the text to "" would you want that text object to not be rendered at all ? (i.e visibility set to false etc). I think the current way it is being handled is  fine.

**Comment by GoodBoyDigital** [comment]
hey all! Closing this as it works as intended, @eliase and @grovesNL if you could let me know why this is causing issues for you I will be happy to take a look at refactoring. thanks!

**Comment by grovesNL** [comment]
@GoodBoyDigital: No issues here - just curious! I can see it being an issue when measuring text bounds or similar (i.e. 0 width would be expected), but I have no use case for that.
