### ISSUE TITLE
looking for a more performant tint adjustment

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#2210]
I'm currently using this function to take a pixi compatible tint (e.g., 0xFF0000 for red color) and a scale value from 0.0 -> 1.0:

```coffeescript
colorScale = (color, scale) ->
  r = Math.round(scale * ((color >> 16) & 0xFF))
  g = Math.round(scale * ((color >> 8) & 0xFF))
  b = Math.round(scale * (color & 0xFF))
  return (r << 16) + (g << 8) + b
```

This seems pretty awful though..lots of bitwise operations, multiplications, additions, and Math.round.

One thing I could do is keep the r,g,b representations which will simplify things, but I'm wondering if there's a more efficient strategy.

**Comment by mreinstein** [comment]
a bit more performant, color is now a 3 element array containing `[ r, g, b ]`

```coffeescript
colorScale = (color, scale) ->
  r = Math.round(scale * color[0])
  g = Math.round(scale * color[1])
  b = Math.round(scale * color[2])
  (r << 16) + (g << 8) + b
```

still wondering if there's a more performant way to do this thought

**Comment by englercj** [comment]
Without making assumptions about what "scale" will be, that is likely the best you will get. If you only want it darker/lighter by like 50% you can do some bit tricks:

```js
halfColor = (color) ->
  (color & 0xfefefe) >> 1 // halves the color
```

**Comment by mreinstein** [comment]
ok, thanks

**Comment by grovesNL** [comment]
Not sure how you are using this function, but it may be possible to perform this calculation directly in the shaders with GLSL (at least if it's only used for rendering)

**Comment by mreinstein** [comment]
hmmm that's an interesting idea. I guess I could attach a shader to each particle and just scale this in the shader as you suggested. :)

**Comment by englercj** [comment]
Good point @grovesNL, it may make sense to do it there. If you assign the same filter to the particles and they are in a container together they should all be batched so maybe that is the way to go.

**Comment by mreinstein** [comment]
cross linking with #2029 since it's related
