### ISSUE TITLE
interactiveChildren and processInteractive

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#2213]
First, big thanks for this great library!!! There are several issues regarding the *InteractionManager* and *interactiveChildren*. They can be fixed if you change the first line in the *processInteractive* function:

from:
```javascript
if(!displayObject || !displayObject.visible)
```

to:
```javascript
if(!displayObject || !displayObject.visible || (!displayObject.interactive && !displayObject.interactiveChildren))
```

Explanation: *interactiveChildren* is set to "*true*" by default. If someone set this DisplayObject value to "*false*", it can be processed like it's invisible.

**Comment by GoodBoyDigital** [comment]
This should be fixed now as the processInteractive was refactored a little. Thanks for sharing this issue!
