### ISSUE TITLE
PIXI.Text with strokeThickness greater than 1 or 2 renders incorrectly with letters "A", "M", "V", "W"

### ISSUE THREAD

**Issue by psyrendust** [pixijs/pixi.js#2215]
Text will render incorrectly with letters that have an angle at the top or bottom of the stroke.

![image](https://cloud.githubusercontent.com/assets/928502/11487880/33645284-9777-11e5-887e-e4b2167af0f3.png)

Here is a JSFiddle to reproduce the issue on PIXI.js `v3.0.8`.

http://jsfiddle.net/psyrendust/trqucfaz/

**Comment by GoodBoyDigital** [comment]
Hi! Setting the lineJoin style property to 'round' will make it look a little better. But ultimately as we use native canvas functions here the issue is outside of Pixi's control i'm afraid :/
