### ISSUE TITLE
Sprite gradients

### ISSUE THREAD

**Issue by basvanmeurs** [pixijs/pixi.js#2216]
Hi all,

I've written a small patch which enables the user to create gradient tinting when using the WebGLRenderer only. I use this together with the sprite of a 1x1 #ffffff pixel in order to create any linear gradient I want.

Usage is as follows:
var sprite = new PIXI.Sprite(...);
sprite.tintBottom = 0xffffff;
sprite.tintTopLeft = 0x00ff00;
sprite.tintTopRight = 0x0000ff;

When not using WebGLRenderer, the top left corner's tint value is being used.

A general tint value, such as 'sprite.tint = 0xffffff;' and 'console.log(sprite.tint)' continues to work as normal.

We could improve interoperability by providing a fallbackTint, which basically can be used to provide a general tint for CanvasRenderer if the user has no WebGL support.

How do you feel about this functionality? I've attached a patch with the code changes.

[Sprite_gradients.patch.txt](https://github.com/pixijs/pixi.js/files/48532/Sprite_gradients.patch.txt)

**Comment by GoodBoyDigital** [comment]
thanks for this @basvanmeurs, I will take a look soon

**Comment by GoodBoyDigital** [comment]
What do people think about adding this feature? cc @ivanpopelyshev @bigtimebuddy ?

**Comment by englercj** [comment]
Looks neat if you could make it backwards compatible with the current tinting. It would also be nice to have it in a PR if at all possible.

**Comment by GoodBoyDigital** [comment]
I would save this for the nxt version! new implementation of Sprite makes this much easier to do 👍

**Comment by alexfoxy** [comment]
Any chance this might be getting merged in soon? Would be pretty sweet!

**Comment by weepy** [comment]
I really need gradient tinting for a project I'm working on. I implemented it as a filter: 

http://codepen.io/anon/pen/VPMjJL

But it's way too slow on iOS. 

Is there a way of overriding the default shader for a sprite so I can write one with a shader ? The old pixi used to have a `shader` property but this seems to have been removed. 

Would it be faster like this ?

**Comment by weepy** [comment]
I've also tried writing as a plugin for v4:  
http://codepen.io/alexfoxy/pen/QdqEPO

But the performance isn't much better (on mobile). I'm not sure if I've made a poor attempt or whether it's something that's not realistically possible ?
