### ISSUE TITLE
dragon.json is what tools generate！

### ISSUE THREAD

**Issue by super2457** [pixijs/pixi.js#2217]
Thank you！

**Comment by englercj** [comment]
I have no idea what this request is, please provide more information.

**Comment by photonstorm** [comment]
Isn't it the Spine data file? (or Spriter? I forget :) )

**Comment by JiDW** [comment]
Yes, I think he's looking for this : http://esotericsoftware.com/

**Comment by super2457** [comment]
@JiDW Thank you！
