### ISSUE TITLE
Implement the rest of the blendModes in WebGL

### ISSUE THREAD

**Issue by GordoRank** [pixijs/pixi.js#2219]
I have several use cases for particular other blendModes (Particularly 'difference') in WebGl.  Not all of which are currently supported in PIXI.

I have come across a good resource, complete with a demo and full source code of the vertex/fragment shaders required to implement them and thought I would share it with you.

I would love to see these implemented.

http://www.nutty.ca/articles/blend_modes/

**Comment by englercj** [comment]
This has come up a few times, we don't use shaders to implement blending which is why not all modes are supported. We use native blending, which has a limited subset of blend modes that are supported.

**Comment by GordoRank** [comment]
Indeed.  I thought I would pass on the link regardless as it may ease the development of the feature for v4 since each required shader and algorithm is clearly listed.

**Comment by englercj** [comment]
Thanks for the info GordoRank, I'll look into this for v4.

**Comment by ivanpopelyshev** [comment]
Actually, I believe this one will work for exclusion:

```javascript
this.blendModes[CONST.BLEND_MODES.EXCLUSION]     = [gl.ONE_MINUS_DST_COLOR,       gl.ONE_MINUS_SRC_COLOR];
```

Everything else can be done only by filters. All these blendmodes appear in standart opengl, but not in opengl ES, its sad :(

**Comment by ivanpopelyshev** [comment]
Also, PR #2222 helps use basic blendModes (ADD, MULTIPLY, SCREEN) at the same time as filters.

**Comment by ivanpopelyshev** [comment]
And now I think that its actually possible with only one way: using readPixels to create texture from current frameBuffer.

**Comment by GoodBoyDigital** [comment]
thats a really interesting idea! how fast is readPixels?

**Comment by ivanpopelyshev** [comment]
If we already are inside the filter, we can use current renderTexture as a source for that emulation shader.

If not, readPixels are the only hope. If user doesnt care about antialiasing and doesnt want us to use extra readPixels, he can just put all screen in a filter.

Throughput is about 0.5 billion pixels per second in my comp: https://jsperf.com/upload-rgb-texture-with-teximage2d-as-rgb-or-rgba/2 , 125 operations per second for 2000x2000 textures.
