### ISSUE TITLE
Sprite size setters are not working with zero scale

### ISSUE THREAD

**Issue by KrysKruk** [pixijs/pixi.js#2221]
Hi!

Sprite [width](https://github.com/pixijs/pixi.js/blob/896789582b97bd423de9a3acb06ad7a078eb813a/src/core/sprites/Sprite.js#L116) and [height](https://github.com/pixijs/pixi.js/blob/896789582b97bd423de9a3acb06ad7a078eb813a/src/core/sprites/Sprite.js#L134) setters uses the `utils.sign()` to keep the same 'scale.x/y' sign.

When 'scale.x/y' is equal '0', these setters do nothing.

#### Steps to reproduce
```
var sprite = new PIXI.Sprite(PIXI.Texture.EMPTY);
sprite.width = 0;
sprite.width = 100;
console.log(sprite.width); // 0
```

When this bug will be confirmed, I can prepare a PR.
Thanks!

**Comment by drkibitz** [comment]
@KrysKruk Totally looks like a bug to me.

The setter in that logic seems like an optimization, the getter seems more suspect.
@GoodBoyDigital @englercj Shouldn't the getter just `return this._width`?

**Comment by drkibitz** [comment]
Actually, why would setting `width` need to touch scale at all? This just seems incorrect in general the more I look at it. width/height and scale.x/y should be independent of each other.

**Comment by GoodBoyDigital** [comment]
Hey all! 

Yes this certainly seems like a bug. 
Setting width should always return the correct value, I will aim to take a look at the sign issue.

With regards to the width modifying the scale, I feel this works really well as is. It is modeled on how flash deals with width and height which I really feel is a nice elegant solution. Adding extra _width / _height properties would increase the complexity of the code and also would force us to add addition checks in the the render loop to enforce width and height. 

Cheers!

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
