### ISSUE TITLE
Interaction Manager doesn't adhere to hitArea after the latest commit

### ISSUE THREAD

**Issue by stephenweaver** [pixijs/pixi.js#2228]
Interaction Manager doesn't adhere to hitArea after the latest commit.
Should line 402 be of the interaction manager (9a722a4) be?
`if(hitTest && !hit || hitTest && displayObject.hitArea)`

**Comment by GoodBoyDigital** [comment]
Hey @stephenweaver will take a look into the issue today, do you have a small fiddle demonstrating the issue? thanks!

**Comment by stephenweaver** [comment]
@GoodBoyDigital Sure, I can make one. Is there an updated pixi.js file I can reference? The one in the bin folder is kinda old.

**Comment by GoodBoyDigital** [comment]
Thanks man! I just published the pixi flles on the dev branch, so you should be able to use them now.

**Comment by stephenweaver** [comment]
Am I looking in the right spot? 

![devbin](https://cloud.githubusercontent.com/assets/5230027/11699014/ee4c2fd0-9e8f-11e5-98db-bc3f16c849a3.PNG)

**Comment by GoodBoyDigital** [comment]
try again, sorry my push failed!

On Wed, Dec 9, 2015 at 9:14 PM, stephenweaver <notifications@github.com>
wrote:

> Am I looking in the right spot?
>
> [image: devbin]
> <https://cloud.githubusercontent.com/assets/5230027/11699014/ee4c2fd0-9e8f-11e5-98db-bc3f16c849a3.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi.js/issues/2228#issuecomment-163393684>.
>



-- 
Mat Groves

*Technical Partner*


 Telephone: 07708 114496 :: www.goodboydigital.com
 First Floor, Unit 9B, Queens Yard, White Post Lane, London, E9 5EN
 goodboy©. All Rights Reserved.

**Comment by stephenweaver** [comment]
Sorry for delay, had some work I had to get done. https://jsfiddle.net/59tchdfj/

**Comment by GoodBoyDigital** [comment]
all fixed! :+1: 

Setting a hitArea no longer checks the children (unless it has interactive children..) 

Thanks for the fiddle man, made it really easy to debug :)

**Comment by stephenweaver** [comment]
Thank you
