### ISSUE TITLE
Rotated textures for spine atlases are wrong in both webgl and canvas

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2230]
That issue is not related to pixi-spine, but to atlases spine is generating. Users who bought Spine dont have to buy TexturePacker because spine already has its features.

[Thread at html5gamedevs](http://www.html5gamedevs.com/topic/19133-how-can-i-control-texturepack-with-rotation/)

[JsFiddle](http://jsfiddle.net/s7bj8y3x/8/)

Original images:

![Original](http://www.html5gamedevs.com/uploads/monthly_12_2015/post-10357-0-99868500-1449637680.png) ![](http://www.html5gamedevs.com/uploads/monthly_12_2015/post-10357-0-23680300-1449637685.png) ![](http://www.html5gamedevs.com/uploads/monthly_12_2015/post-10357-0-47577200-1449637689.png)

Packed images, first and second are rotated:

![Packed](http://www.html5gamedevs.com/uploads/monthly_12_2015/post-10357-0-52189400-1449637585.png)

UVs in webgl are wrong

![WebGL](https://monosnap.com/file/VgohThUjb4vnxF2Eeprja2fiNLlFU8.png)

Both UVs and anchors in canvas are wrong

![Canvas](https://monosnap.com/file/TO7tgOHCv20oiAN1vYzXo19iAzLE1G.png)

**Comment by ivanpopelyshev** [comment]
Classes:

1) [TextureUVs](https://github.com/pixijs/pixi.js/blob/master/src/core/textures/TextureUvs.js#L33)

2) [Sprite](https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/Sprite.js#L411)

**Comment by ivanpopelyshev** [comment]
Is that possible than spine atlas "rotate" differs from TexturePacker rotate?

**Comment by GoodBoyDigital** [comment]
Hmm.. looks like it may be the case?

**Comment by ivanpopelyshev** [comment]
However, TextureUVs and Sprite implementations are contradicting: TextureUVs use (frame.width, frame.height) while canvas uses (frame.height,frame.width) for dimensions. Im sure that there's a bug somewhere.

**Comment by GoodBoyDigital** [comment]
Cool, I did just push a fix for canvas rotated textures earlier this week. WebGL texture uvs are working ok though as far as i am aware? Let me know if you find anything!

**Comment by ivanpopelyshev** [comment]
Ok i see it: https://github.com/pixijs/pixi.js/commit/72b155ca34bbde4620b22ea3628ee0ca73e7a33f

But you didnt fix it in textureUVs. 

```javascript
TextureUvs.prototype.set = function (frame, baseFrame, rotate)
{
    var tw = baseFrame.width;
    var th = baseFrame.height;

    if(rotate)
    {
            this.x0 = frame.x / tw;
            this.y0 = (frame.y + frame.width) / th;

            this.x1 = frame.x / tw;
            this.y1 = frame.y / th;

            this.x2 = (frame.x + frame.height) / tw;
            this.y2 = frame.y / th;

            this.x3 = (frame.x + frame.height) / tw;
            this.y3 = (frame.y + frame.width) / th;
    }
    else
    {

        this.x0 = frame.x / tw;
        this.y0 = frame.y / th;

        this.x1 = (frame.x + frame.width) / tw;
        this.y1 = frame.y / th;

        this.x2 = (frame.x + frame.width) / tw;
        this.y2 = (frame.y + frame.height) / th;

        this.x3 = frame.x / tw;
        this.y3 = (frame.y + frame.height) / th;
    }
};
```

**Comment by GoodBoyDigital** [comment]
I see! The current version works well with texture packer as far as i am aware? do we have a texture packer example to test?

**Comment by ivanpopelyshev** [comment]
Yeah, now I see it, your version works, I was wrong. But for spine atlas we need to make new rotate value: -1. It uses other direction!

**Comment by GoodBoyDigital** [comment]
stoopid spine! we could refactor ```rotate``` to be a number?

**Comment by GoodBoyDigital** [comment]
that way we can cover all rotations

**Comment by ivanpopelyshev** [comment]
Yep , I think 0,1,2,3 will be awesome.

**Comment by GoodBoyDigital** [comment]
wicked, are you happy to take a look at that?

**Comment by ivanpopelyshev** [comment]
No, I just dont want to do my actual work right now :) its boring

**Comment by GoodBoyDigital** [comment]
lol, i know that feeling :)

**Comment by ivanpopelyshev** [comment]
I'll add mirroring too. Lets add all [D4 group](http://mathworld.wolfram.com/DihedralGroupD4.html) ! That will help so many projects, including my bomber :) Imagine that you can specify texture with rotate=6 instead of sprite.scale.x=-1

**Comment by GoodBoyDigital** [comment]
very nice! this will be ace!

**Comment by ivanpopelyshev** [comment]
Work in progress: ![WIP rotations](https://monosnap.com/file/GpW9b4CZdvyqXlu23dVo56IMoI3zIf.png)

**Comment by GoodBoyDigital** [comment]
:+1:

**Comment by ivanpopelyshev** [comment]
Look at updated WIP.

Odd rotations were used only internally, they differ in canvas and webgl mode, but I think its cool effect :)

**Comment by ivanpopelyshev** [comment]
PR #2237 , [demo](http://ivanpopelyshev.github.io/examples/index.html?s=demos&f=texture-rotate.js&title=Texture%20Rotate)

**Comment by GoodBoyDigital** [comment]
all fixed now thanks to @ivanpopelyshev  :+1:
