### ISSUE TITLE
How to make text and graphics clickable?

### ISSUE THREAD

**Issue by samuraiseoul** [pixijs/pixi.js#2231]
Hi there. I'm trying to make some text clickable, and upon reading discovered that PIXI.Text() doesn't extend displayObject so it is not clickable. Through a lot of googling I came across [this issue](https://github.com/pixijs/pixi.js/issues/821) and there was a suggestion to convert it into a texture using getTexture() and then pass that into the constructor for a sprite like so new `PIXI.Sprite(new PIXI.Text("WORD"));` but I get told that I need to pass a renderer with it for it to work even though the docs don't show this.

As for Pixi.Graphics() the docs show it as extending DiplayObject but even then I cant get it to recognize clicks. I use `var.interactive = true;` and `var.click = function(ev) { console. log("CLICKED"); }` but nothing happens. I really don't want to go and create images for individual words to make this work. T_T Also is there a simple way to get a select similar to an HTML select going?

**Comment by englercj** [comment]
```js
var text = new PIXI.Text("WORD");
var sprite = new PIXI.Sprite(text.generateTexture(renderer));
```

Is what you are looking for.
