### ISSUE TITLE
Strange artifacts in WebGL

### ISSUE THREAD

**Issue by BetaRavener** [pixijs/pixi.js#2232]
I've previously thought this is canvas related issue so I wrote about the bug here: http://stackoverflow.com/questions/34191893/pixi-js-webgl-renderer-polygon-artifact . But now it seems to be issue either with Pixi.js or the WebGL as direct rendering to HTML5 canvas works.

**Comment by GoodBoyDigital** [comment]
is this issue still present in v4 ? Thanks!

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
