### ISSUE TITLE
Prefiltered line technique to dramatically improve the rendering of lines an shapes

### ISSUE THREAD

**Issue by GordoRank** [pixijs/pixi.js#2234]
My understanding is that currently PIXI uses the stencil buffer to draw graphics objects like lines and shapes.  Since the stencil buffer does not support alpha all lines are very jagged/aliased.  This is fine with AA or FXAA on but both of these come with other sets of issues that may or may not be acceptable for a given project.(GPU/browser support/performance for AA and text rendering issues for FXAA)

I've stumbled across a different technique which appears to complete solve this issue and if my understanding is right, it should be faster than the current method. I thought I would share the link in case it is something you guys might want to look into for a future version of PIXI.

http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter22.html

**Comment by GordoRank** [comment]
Another good alternative would be to use a signed distance field texture and custom shader to render the lines.  We are doing this in our project with a custom written PIXI shader and a simple 32*32 signed distance texture of a line.  This texture is drawn as a PIXI sprite and then ran through our custom shader.  The sprite then simply gets scaled to the width/height of any line you want.  The end result is completely resolution/zoom independent an is always beautifully antialiased and far faster than drawing with the stencil buffer.

The Nvidia approach mentioned above would be the most flexible implementation but the SDF method also works very well.

Here's a screenshot.  All done in PIXI with only a single extra shader.  Anti-Aliasing is turned off and as you can see the result is still perfectly smooth lines (In this example both the Text and the lines are rendered with SDF, we wrote our own Text renderer also).

![example](https://cloud.githubusercontent.com/assets/6388079/11749834/f1b43e62-a027-11e5-9756-e57a837236f3.png)

**Comment by grovesNL** [comment]
Interesting, although I can see some problems with the approach, for example the use of `lineWidth` in thick lines will not work in WebGL.

[The approach used by Leaflet](https://www.mapbox.com/blog/drawing-antialiased-lines/) seems most compatible for straight line segments, but fills would still probably be hard with this approach.

**Comment by GordoRank** [comment]
I'll take a look at the approach you've linked to shortly.  By fills are you referring to textured lines?  If so with the SDF method, it is very simple since everything is done in the shader.  In fact we use it to add gradients and/or textures to our SDF text.

**Comment by grovesNL** [comment]
No, textured lines would be fine because they can be handled in the fragment shader.

In the approach I linked, polygon fills may be difficult. So if you use `Graphics` to draw a polygon, filling the inside of the polygon may be difficult. This is because the vertex positions are calculated in the GPU, so earcut or similar can't be easily used. Hollow shapes would be easy.

**Comment by englercj** [comment]
Interesting find, thanks for this. We should definitely do more research into making the Graphics plugin of v4 use a more well-rounded method.
