### ISSUE TITLE
Closure Compiler Externs for PIXI version 3.0.8

### ISSUE THREAD

**Issue by PatrickSanchez** [pixijs/pixi.js#2240]
I have done the externs file for PIXI version 3.0.8.

How I did it ( I hope this is the right way to do this :) ):
- I have boiled down the source code (3.0.8) to get all the definitions.
- then I have run through the doc to double check that everything is correct (there are some inconsistencies between the doc and current source, but minor, I left comments in the externs file).
- then I have run compile tests on few small projects and added missing bits from the doc and what I had missed in the source, e.g. PIXI.Texture.prototype.interactive

It works great with few small projects I have got it tested with ( but would be great to see if larger projects can use this).

There are few little things left to do ( not preventing from successfully compiling the project, only throwing warnings ):

- few type warnings to sort out ( problems related to externs file ): 

   - Unknown type WebGLFrameBuffer ( I could not strip it out from source )

   - Unknown type DOMHighResTimeStamp ( I am not sure why CC is not recognizing this one )

   - Unknown type PIXI.loaders.ResourceLoader ( I could not strip it out from source )

   - Unknown type Font ( I am not sure what do do about this one )

- source code inconsistencies ( problems related probably to the source code, please correct me if I am wrong ):

   - mismatch of the generateTexture property type and the type of the property it overrides from superclass PIXI.DisplayObject
      in PIXI.Graphics.prototype.generateTexture = function ( resolution, scaleMode ){};
      - original: function (this:PIXI.Container, (PIXI.CanvasRenderer|PIXI.WebGLRenderer|null), number, number): (PIXI.Texture|null)
      - override: function (this:PIXI.Graphics, number, number, number=): (PIXI.Texture|null)

   - mismatch of the getBounds property type and the type of the property it overrides from superclass PIXI.DisplayObject
     in: PIXI.Sprite.prototype.getBounds = function (matrix){};
      - original: function (this:PIXI.Container): (PIXI.Rectangle|null)
      - override: function (this:PIXI.Sprite, (PIXI.Matrix|null)): (PIXI.Rectangle|null)

   - mismatch of the destroy property type and the type of the property it overrides from superclass PIXI.Texture
     in: PIXI.RenderTexture.prototype.destroy = function ( destroyBase ){};
      - original: function (this:PIXI.Texture, boolean=): ?
      - override: function (this:PIXI.RenderTexture, boolean): ?

Are you interested in including this file in the repository?
    
If so, I will do a pull request, just please let me know, what is the best folder to place the externs file in.

**Comment by englercj** [comment]
It would not be in the repo, but we would happily include it in the org, similarly to the [typescript](https://github.com/pixijs/pixi-typescript) and [haxe](https://github.com/pixijs/pixi-haxe) externs.

**Comment by PatrickSanchez** [comment]
Should I create a new github project for you to fork? Or would you prefer to create a project on your org for me to do a pull request?

**Comment by englercj** [comment]
I created the repo and invited you to be the admin of it.

**Comment by PatrickSanchez** [comment]
Cool, thank you for the invite :) I will do the initial commit tomorrow. Is the extern file and readme enough for starters?

**Comment by englercj** [comment]
@PatrickSanchez Yeah man, that sounds good.

**Comment by PatrickSanchez** [comment]
I am not sure if this post is the best place to ask this question.
I have tried to google 'closure compiler externs for pixijs' and nothing is coming up.
Is there a change we could somehow make google to index that page by linking it somewhere, so people can find it?

**Comment by englercj** [comment]
It does index repositories; mostly the description, name, and README files.

i notice you have no description, I recommend changing that; perhaps to "closure compiler externs for pixijs".

**Comment by PatrickSanchez** [comment]
Oh I see, thank you very much, I have just updated the description.
