### ISSUE TITLE
Ghost trail by ping ponging textures has strange effect

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#2242]
Im basically trying to achieve a ghost trail effect by ping ponging textures. It generally works quite well. But when the alpha is to high, the trail never actually disappears.

http://jsfiddle.net/etd2s4m7/

Not quite sure what I'm missing! cc @englercj @ivanpopelyshev

**Comment by englercj** [comment]
Not sure :confused: 

Possibly a rounding issue in the alpha multiply in the TextureShader?
