### ISSUE TITLE
Setup gitter

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2244]
Some projects like [scala-js](https://github.com/scala-js/scala-js) are using [gitter](gitter.im) . Im not admin of pixi.js repo , so I cant create room for it :(

**Comment by englercj** [comment]
We've had one for a while:

https://gitter.im/pixijs/pixi.js

**Comment by ivanpopelyshev** [comment]
Ok, then i'll bring people there
