### ISSUE TITLE
Loader video

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2246]
After looking at this [forum thread](http://www.html5gamedevs.com/topic/19243-crossorigin-for-mask-in-pixi/) , I have noticed that our loader doesnt support videos. 

Currently we can choose video type by using [pixi-compressed-textures](https://github.com/pixijs/pixi-compressed-textures) approach, but loader wont recognize video file types.

```javascript
function getSupportedVideoExt() {
   if (isSafari) return ['ogg'];
   return ['mp4'];
};

loader.before(PIXI.compressedTextures.extensionChooser(getSupportedVideoExt()));

//will choose ogg over mp4 if its supported
loader.add('myvideo.mp4', { metadata: { choose: ['ogg']} }); 
loader.load(function(loader, resources) {
   //...
   var tex = Texture.fromVideo('myvideo.mp4');
});

```

We can add support for videos in loader in separate library.

**Comment by englercj** [comment]
The loader does support loading videos (at least it does now).
