### ISSUE TITLE
Testing and CI

### ISSUE THREAD

**Issue by drkibitz** [pixijs/pixi.js#225]
I thought this merited it's own issue to track this specific implementation, so I am referencing the issue here (and particularly issuecomment-21592227): https://github.com/GoodBoyDigital/pixi.js/issues/216#issuecomment-21592227

An issue like "Coding standards" can easily branch off to related subtasks, sorry I didn't just post those comments here when it did.

**Comment by englercj** [comment]
Reusing this issue to track adding tests for v3.

**Comment by GoodBoyDigital** [comment]
This one is a bit  old :D Good thing is we have a nice new build process set up for v4 along with a way to run visual webGL tests. Fun fun! 👍
