### ISSUE TITLE
Creating geometry using PIXI.mesh.Mesh

### ISSUE THREAD

**Issue by activetheory** [pixijs/pixi.js#2250]
Hi!

I saw in the v4 discussion that custom geometry may be coming, exciting stuff! In the mean time, I've been working my way through the source and trying to find a way to do this now.

It seems like I should be able to use Mesh to do this, however creating a mesh and passing a texture comes up with this:

<img width="108" alt="screen shot 2015-12-15 at 12 07 12 am" src="https://cloud.githubusercontent.com/assets/1118248/11805357/cf752f9c-a2bf-11e5-8bde-7b76529d32ea.png">

So it seems like the default vertices aren't really accurate. I tried a few different combinations trying to draw a single triangle or quad, but didn't get anywhere -- specifically ccw wrapping such as:

`[0, 0
  100, 0,
  0, 100]`

I was wondering if there is a quick explanation how to setup the Mesh vertices/uvs/indices to draw a tri or quad?

**Comment by GoodBoyDigital** [comment]
Hey man!

Exciting stuff indeed! Im quite looking forward to exposing a few things in pixi to allow for it to be much easier to create custom buffers / shaders. It will be ace.

Have you tried using the dev branch? I'm pretty sure we fixed a few bits a couple of weeks back. 

Cheers!

**Comment by activetheory** [comment]
Hey,

Thanks for getting back to me. I just pulled the dev branch but am getting the exact same result with 3.0.9-dev.

I think mesh works, seeing as Rope uses it and works. I'm just trying to understand how vertices need to be arranged and how indices relates to them. Is there a quick explanation?

**Comment by GoodBoyDigital** [comment]
ah, i see what you mean! The default values are incorrect :/

Just pushed the 'correct' initial values to the dev branch so it appears correctly now :)

The indices are setup to be draw using a triangle strip

````
indices = [0, 1, 3, 2]
````

If the draw mode you use is set to triangles the indices would need to be:

````
indices = [0, 1, 2, 0, 2, 3]
````

hope that helps!

**Comment by activetheory** [comment]
Perfect, that's it.. thanks!
