### ISSUE TITLE
Masking and interactive problem

### ISSUE THREAD

**Issue by andrevenancio** [pixijs/pixi.js#2252]
Hey guys.
found another odd one..

touchstart/mousedown events dispatched from inside a masked container keeps firing event when the mask height is 0..

If I click the button it fires an animation to the mask where is height transitions from a 100px to 0 and I'm forcing the hitArea rectangle to be 0 in height too. visually everything works the the container gets masked but if I keep pressing the mouse on the same place the button keeps firing his event.
Only If I move the mouse outside will the event cease to fire...

pseudo code
```
var holder = new PIXI.Container()
scene.addChild(holder);


var mask = new PIXI.Graphics()
mask.drawRect 0, 0, width, height
scene.addChild mask

var anotherContainer = new PIXI.Container
anotherContainer.mask = mask
scene.addChild anotherContainer

var fakeButton = new PIXI.Container()
fakeButton.on 'mousedown', onDown
anotherContainer.addChild fakeButton

function onDown() {
mask.drawRect 0, 0, width, 0
mask.hitArea = new PIXI.Rectangle 0, 0, width, 0
console.log 'this keeps happening until I move my mouse away'
}

```

**Comment by SirKnightDragoon** [comment]
Same bug here... I have a accordion menu, and I can click my hidden element... :/

**Comment by andrevenancio** [comment]
yes @SirKnightDragoon `element.hitArea = new PIXI.Rectangle(0, 0, width, 0)` but in this case it doesn't work as I think the InteractionManager might be storing something it shouldn't...

**Comment by SirKnightDragoon** [comment]
@andrevenancio I done a PR to fix hitArea here https://github.com/pixijs/pixi.js/pull/2275
Now I can create a hitArea that fit with my mask and stop event outside of the hitArea.

**Comment by GoodBoyDigital** [comment]
This has been implemented into v4 :+1:
