### ISSUE TITLE
Coloring a texture?

### ISSUE THREAD

**Issue by Esshahn** [pixijs/pixi.js#2253]
I have a bitmap used as a font.
![chars-commodore](https://cloud.githubusercontent.com/assets/434355/11912238/a89bf9dc-a634-11e5-858f-db0d04111a5c.png)

How can I make these chars any color I like without creating new images for each color? Is there a way to colorize/exchange a specific color in a texture?

Thank you guys.

**Comment by grovesNL** [comment]
You can use tint with BitmapText. I usually use a white foreground and transparent background for my characters because it will color the lighter parts. You will have to use a separate BitmapText instance for each softens color you want, though.

`text.tint = 0x004488;`

**Comment by Esshahn** [comment]
Thank you! I will give it a try.
