### ISSUE TITLE
asset loader for more than images and sound?

### ISSUE THREAD

**Issue by Esshahn** [pixijs/pixi.js#2254]
I have a long list of files that I need to load in advance (like level files).
However, I can't seem to get them to load with the asset loader like the images.
Any way to make sure files are loaded fully before progressing?
Thank you.

**Comment by ivanpopelyshev** [comment]
It depends on file types. For example, that's what I did for compressed textures:

```javascript
Resource._xhrTypeMap['dds'] = Resource.XHR_RESPONSE_TYPE.BUFFER;
Resource._xhrTypeMap['pvr'] = Resource.XHR_RESPONSE_TYPE.BUFFER;
```

**Comment by Esshahn** [comment]
hmm. Thank you for the help, but I can't quite follow.
This is what I'm using for my images (its written in CoffeeScript btw):

load_assets = (cb) -> 
  loader = PIXI.loader
  loader.add 'chars', 'img/chars.png'
  loader.add 'chars_commodore', 'img/chars-commodore.png'
  loader.add 'chars_hint', 'img/chars-hint.png'
  loader.once 'complete', ->
    cb()
  loader.load()
  return

It works for images, but not e.g. for binary files, which I need to read in as they are the (unchangeable) base format.

**Comment by englercj** [comment]
What do you mean by "it doesn't work"? What happens?

Please open an issue on the resource loader: https://github.com/englercj/resource-loader

And please do not modify the private static variables that @ivanpopelyshev mentioned. There is a public API for that:

https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L768-L788

use that instead.

**Comment by ivanpopelyshev** [comment]
@Esshahn by default your files are treated as text. If you want binary - use that thing @englercj mentioned.
