### ISSUE TITLE
AccessibilityManager breaks if PixiCanvas isn't in DOM

### ISSUE THREAD

**Issue by mathatan** [pixijs/pixi.js#2257]
So I have a multilayer pixi implementation with some layers not being in the DOM all the time for multiple reasons. Due to this `pixi.js/src/accessibility/AccessibilityManager.js:118` throws an error whenever I use 'tab' within e.g. HTML forms.

**Comment by GoodBoyDigital** [comment]
ah! good catch, will look to fix before it makes it to master! :+1:

**Comment by GoodBoyDigital** [comment]
fixed! 👍
