### ISSUE TITLE
Container setters do not work.

### ISSUE THREAD

**Issue by BishKor** [pixijs/pixi.js#2259]
Container setters do not work. 

    var stage = new PIXI.Container();
    console.log(stage.scale.x); // 1
    console.log(stage.width); // 0
    stage.width = 2;
    console.log(stage.width); // 0

If this is a bug, I can look into making a PR, but I'm not sure you want someone of my js experience tinkering in this source code.

Furthermore, looking at this [tutorial](https://github.com/kittykatattack/learningPixi#creating-sprites-from-a-loaded-texture-atlas) there is some code that looks like this:

      treasure = new Sprite(id["treasure.png"]);
      stage.addChild(treasure);

      //Position the treasure next to the right edge of the canvas
      treasure.x = stage.width - treasure.width - 48;
      treasure.y = stage.height / 2 - treasure.height / 2;

Which I think is incorrect. Based on my understanding in the context of pixijs (and flash?), stage.scale is not intended for positioning objects within the game space, but rather a container whose children in game space are mapped to rendered space.

Thanks!

**Comment by adelciotto** [comment]
You need to add a child to the container for the width or height get property to return a value greater than 0.

**Comment by BishKor** [comment]
Ah, ok. I see now.
