### ISSUE TITLE
Wish:  An option for scaling each sprite automatically (while preserving aspect ratio)

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#2260]
In a project I have a full-page canvas that scales on resize, to any screen format / aspect ratio.

I scale the sprite(s) like this:
```fooSprite.scale.set(window.innerHeight / someConstantPixelLength);```

The aspect ratio of the sprite gets preserved during scaling / resizing of the window. 

It would be handy if there'd be an option for Pixi JS to scale each sprite automatically (while preserving the aspect ratio of each sprite as in the above example).

**Comment by ivanpopelyshev** [comment]
Adjust the scale of parent container.

**Comment by tobireif** [comment]
When I resize this page (eg making the window smaller in height)
http://codepen.io/TobiReif/full/5c2ff89a8051fece8d0312c3f05983a7/
the tree adjusts in size but its aspect ratio is lost.

Perhaps it's my error?

Otherwise: Perhaps there could be an option in PixiJS so that the aspect ratio gets preserved automatically.

(In the ~finished demo I set scale explicitly, the aspect ratio of the tree gets preserved:
http://codepen.io/TobiReif/full/JGGWZJ )

**Comment by ivanpopelyshev** [comment]
Yeah, aspect ratio options for bounds (width/height) will be good.

**Comment by GoodBoyDigital** [comment]
This would be cool - but is a feature that is outside of core pixi. It could belong in a layout plugin and that could be quite useful for aligning things / setting scale ratios etc.
