### ISSUE TITLE
Performance of 3.0.9 is down when compare 3.0.8 and 3.0.9

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#2261]
Hi. i checked 3.0.9 

but it's slow about 10 fps than 3.0.8.

I don't know correct reason why it's slow now

i tested same project. it was only differrent pixi.js version.

**Comment by GoodBoyDigital** [comment]
Hi @SeminYun! Please provide a link or some specifics. Currently there is not enough information to debug. thanks!

**Comment by SeminYun** [comment]
Hi.

i will link test example..

I will tell you first..before update. 

I tested with spine. there were only goblins

like this(blow example is with 3.0.8
http://jsfiddle.net/n0kzcjyu/7/

and it was changed only PIXI TO 3.0.9

and I could look framedrop when i check FPS

it's seem to drop about 10-15 frame when compare with 3.0.8

and I could look same situation with own project.

thanks..

**Comment by tobireif** [comment]
(Minor info bit: On the example page, in the bottom right area, scroll down :) )

**Comment by tobireif** [comment]
@SeminYun The example page says (in the console)
"Uncaught TypeError: Cannot read property 'spineMetadata' of undefined".
