### ISSUE TITLE
How can i use physics (Box2d) with Pixi

### ISSUE THREAD

**Issue by sorawa** [pixijs/pixi.js#2262]
Can you give me the link to the totorials
thank you

**Comment by ivanpopelyshev** [comment]
Sorry for late answer.

I had my own box2d + debug renderer for pixi somewhere. I'll find it and post a demo in the examples.

**Comment by ivanpopelyshev** [comment]
I hope that you already bought https://www.codeandweb.com/physicseditor , its difficult to make box2d in pixi without it

**Comment by englercj** [comment]
Basic idea is to spawn bodies for sprites and keep the two scenes in sync with eachother.

**Comment by andrevenancio** [comment]
I'm using box2d(web) and pixi.js on a project... there's nothing to it.
an array of bodies added to the world (box2d)
an array of sprites added to the stage (pixi.js)

your render function checks the position and rotation of the box2d bodies, and applies it to the sprites array. let me know if you need a code example

**Comment by GoodBoyDigital** [comment]
closing as seems answered :+1:

**Comment by mspanish** [comment]
@ivanpopelyshev I just want to add collision and bouncing around to a few shapes (rectangle, triangle, circle) - which can be dragged and dropped onto a correct answer sprite.   Is box2d the best solution for that? Does anybody have an actual code sample? I can download the physics editor app if necessary too.

**Comment by andrewstart** [comment]
For just the basic shapes, you shouldn't need the PhysicsEditor app. I've used [p2](https://schteppe.github.io/p2.js/) successfully on mobile in EaselJS for about 10 or so of those same 3 shapes, and it worked out okay.

**Comment by mspanish** [comment]
thanks  p2 has some really nice looking samples - I'll try integrating one of them with my sprites - seems this shouldn't take much to accomplish - shame I can't find an updated physics plugin/bridge for PIxi though.

**Comment by crazyyi** [comment]
@mspanish  You can try this library: [https://github.com/shakiba/planck.js](https://github.com/shakiba/planck.js)
