### ISSUE TITLE
tilingsprite is weird

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#2264]
http://www.html5gamedevs.com/topic/19544-tiliingsprite-is-weird-with-308-pixi/

Hi..
 
my game was upadated to 3.0.8 from 2.2.9 month ago..
 
and i find weird screen with tilingSprite..
 
can you see red rounded box? that looks textures's edge of end.   
it is moving with tiling when move tilingposition.
 
i didn't look this with 2.2.9 
이미지 1.png
 
 
what can i do this?

**Comment by GoodBoyDigital** [comment]
this should be ok in v4 now 👍
