### ISSUE TITLE
PIXI.Graphics always black on PIXI.CanvasRenderer

### ISSUE THREAD

**Issue by andraaspar** [pixijs/pixi.js#2265]
On PIXI 3.0.9, when using the CanvasRenderer, my Graphics instances always end up black, regardless of beginFill's color parameter.

I am drawing like this:
```TypeScript
protected updateWedge(): void {
	var MIN = illa.End.MIN;
	var MAX = illa.End.MAX;
	this.clear();
	// Fix WebGLRenderer spike
	this.moveTo(Math.cos(this.angle.get(MIN)) * this.radius.get(MIN), Math.sin(this.angle.get(MIN)) * this.radius.get(MIN));
	this.beginFill(this.color.get());
	this.arc(0, 0, this.radius.get(MAX), this.angle.get(MIN), this.angle.get(MAX));
	this.arc(0, 0, this.radius.get(MIN), this.angle.get(MAX), this.angle.get(MIN), true);
	this.endFill();
}
```

I have tracked this issue down to:

`CanvasGraphics.js:33` (in `CanvasGraphics.renderGraphics`):
```JavaScript
var fillColor = data._fillTint;
```

`data._fillTint` is `undefined`. I have fixed this by replacing the line with:
```JavaScript
var fillColor = data._fillTint || data.fillColor;
```

But I doubt this is the right solution?

**Comment by andraaspar** [comment]
This is what the `data` object looks like in Chrome:
```
GraphicsData
_fillTint: undefined
_lineTint: 0
fill: true
fillAlpha: 1
fillColor: 7118888
lineAlpha: undefined
lineColor: 0
lineWidth: 0
shape: Polygon
type: 0
__proto__: GraphicsData
```

**Comment by GoodBoyDigital** [comment]
hello! this line looks like it could be the offender? -> this.color.get()

**Comment by andraaspar** [comment]
I'm afraid not. Here's a fiddle:
https://jsfiddle.net/andraaspar/s8p8g83w/1/

**Comment by GoodBoyDigital** [comment]
thanks for sharing @andraaspar 👍 all fixed in the dev branch now!
