### ISSUE TITLE
blend mode with canvas renderer works on desktop but mobile 

### ISSUE THREAD

**Issue by ericguo** [pixijs/pixi.js#2268]
The blend mode failed with canvas render on my Android browser except PIXI.BLEND_MODES.ADD

**Comment by englercj** [comment]
It is up to the browser to implement blend modes for canvas.

**Comment by ericguo** [comment]
ok

**Comment by englercj** [comment]
Mobile Chrome, Firefox, and Safari all implement blend modes properly (IIRC). I honestly don't know about the default android browser.
