### ISSUE TITLE
Error if call destroy on click

### ISSUE THREAD

**Issue by user471** [pixijs/pixi.js#2270]
```
var renderer = PIXI.autoDetectRenderer(256, 256);
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();

var message = new PIXI.Text(
  "Test",
  {font: "32px sans-serif", fill: "white"}
);

stage.addChild(message);
message.interactive = true;
message.on("click", function(){
	stage.destroy(true);
});
renderer.render(stage);

```
On click
The error is ```children[i] is undefined```
if replace ```stage.destroy(true)``` with ```message.destroy()```
The error is ```this._texture._frame is null```

**Comment by englercj** [comment]
This is the same as destroying an array in the middle of the loop, and continuing the loop. It is not safe to destroy the object in the middle of event handlers or the render loop. Instead mark that they need to be destroyed and after those are complete destroy the objects.

**Comment by user471** [comment]
>This is the same as destroying an array in the middle of the loop

I don't think it's a good analogy.
This is more accurate and I don't see anything wrong with it.
```
foo = {
    onClick: null,
    click: function() {
        console.log("click");
        foo.onClick();
    },
    destroy: function() {
        console.log("destroy");
        delete foo;
    }
};

foo.onClick = () => foo.destroy();
foo.click();

```

**Comment by englercj** [comment]
>I don't think it's a good analogy.

It isn't an analogy, there actually is a loop happening. Both in the renderer and the interaction manager. The interaction manager has to emit events to siblings and parents to bubble events, it loops over children and parents, traversing the scene tree.

It is not like what you posted, it is in fact a loop in which you are destroying the objects it tries to hit. You could try to use `event.stopPropagation()` to prevent the loop from moving on.

**Comment by user471** [comment]
> If you destroy the scene tree while it is walking,

Why then there is an error with only ```message.destroy()``` ? There should not be any loop, only one object.

> it will error because you nulled properties in the tree it is walking.

So, why not just check for null?

**Comment by englercj** [comment]
Because it isn't that simple, this isn't C++ we can't just check for a null ptr. The object still exists after destroy, just in an invalid state. The idea being if you cann destroy you need to lose references to it.

Just like a loop, modifying objects during it invalidates the iterator. You need to either stop the loop with `stopPropagation` or delay the destroy.

**Comment by user471** [comment]
>You need to either stop the loop with stopPropagation or delay the destroy so the iterator remains valid. this._texture._frame is null likely comes from the render loop, not sure I would have to debug your application.

What do you mean by my application? I posted the complete code example.
I have added stopPropagation, but it didn't help.
```
var renderer = PIXI.autoDetectRenderer(256, 256);
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();

var message = new PIXI.Text(
  "Test",
  {font: "32px sans-serif", fill: "white"}
);
stage.addChild(message);
message.interactive = true;
message.on("click", function(e){
    e.stopPropagation();
    message.destroy(true);
});
renderer.render(stage);
```

**Comment by englercj** [comment]
The error you are getting is because you are calling `.destroy()` on an object that you then leave in the scene. `.destroy()` is meant to be called when you are disposing an object.

If you remove it in that handler along with the destroy, then it will cause an error since you are modifying the child array inside the loop (and it doesn't expect that). You have to remove the destroy/remove from the loop, which means out of the handler. It is not safe to modify the objects in the handler in that manner.

Working example:

https://jsfiddle.net/v6ujsc8b/3/

**Comment by ivanpopelyshev** [comment]
Do it in setTimeout(() => { stuff; } , 0) aka nextTick.

**Comment by user471** [comment]
> The interaction manager comes by later and tries to interact with that invalid object 
Is it possible to add property isDestroyed, so manager would check if object is invalid and do not interact with it?
Is 1 milliseconds timeout always enough?

**Comment by englercj** [comment]
> Is it possible to add property isDestroyed, so manager would check if object is invalid and do not interact with it?

No it makes people have to understand how to work with the interaction manager, which isn't reasonable.

> Is it possible to add property isDestroyed, so manager would check if object is invalid and do not interact with it?

Yes, it isn't about the time. The interaction loop is sychronous, you just need to make the js engine delay the call of that function until you are out the loop. Literally any number will work since it would run during the setTimeout handler and never within the loop.

**Comment by user471** [comment]
Should such function be in the Pixi? So everyone can use it.
something like
```
Container.prototype.destroyWithDelay() = function(){
   setTimeout(function () { this.destroy();    }, 1);
}
```
Are there any other functions which cannot be used in events?

**Comment by englercj** [comment]
Not that I am aware of, again this is a pretty special case. In the 4 years of pixi this is the first I've heard of someone trying to do it :)

**Comment by user471** [comment]
stage.destroy still throw error even with setTimeout
How can I fix it?
```
https://jsfiddle.net/v6ujsc8b/5/
```

**Comment by ivanpopelyshev** [comment]
I think that's a bug with interactionManager.

**Comment by englercj** [comment]
If you are going to destroy the root object, then you also need to stop the interaction manager from looking for it.

You can stop the interaction manager (you have to manually start it again later when you want it to handle interactions again):

```js

message.on("click", function(e){
    // delay the removal to outside the interaction loop.
    setTimeout(function () {
        console.log('REMOVE');
        stage.destroy(true);
        renderer.plugins.interaction.removeEvents(); // stop manager
        // you can start it again with renderer.plugins.interaction.addEvents();
    }, 1);
});
```

Though I wouldn't recommend destroying the root stage object, unless you are completely done with the pixi scene. If that is true then you probably also want to destroy the renderer and such as the same time, which will prevent this error.
