### ISSUE TITLE
Interactiv Error

### ISSUE THREAD

**Issue by gold256** [pixijs/pixi.js#2273]
We have the following scheme:
1. Create button and the display on the screen.
2. Press. Then execute a metod when button destroy himself.
3. In the MoseUp event appears the following error:

Uncaught TypeError: 
Can not read property 'interactive' of undefined  InteractionManager.processInteractive
   InteractionManager.onMouseUp

In the method:
InteractionManager.prototype.processInteractive = function (point, displayObject, func, hitTest, interactive)

In line:
if (children [i] .interactive)
                 {
                     hitTest = false;
                 }

This line should be changed as follows:
if ( children [i] && children [i] .interactive)
                 {
                     hitTest = false;
                 }

Thank you for your attention.
Petar Petrov, 
bravo.cool@esgoogle.net

**Comment by englercj** [comment]
DUplicate: https://github.com/pixijs/pixi.js/issues/2270

**Comment by gold256** [comment]
It must be written in this way, because at any moment can be destroyed object.
I have Tween over Object in full stsreen. If I pressed ESC i must destroy the application and leave on the screen only one button => Go in Fullscreen.

The Tween can be stopped in the next cycle. But in the current cycle can be destroyed object.

**Comment by englercj** [comment]
Why can't you delay destruction by a single cycle?
