### ISSUE TITLE
AbstractFilter uv problem

### ISSUE THREAD

**Issue by andrevenancio** [pixijs/pixi.js#2274]
Hey, I think `PIXI.AbstractFilter` should have the `uvs` reflect the size of the container its being applied to instead of the browser window size.

pseudo code:
```
s = new PIXI.Sprite()
s.width = 1
s.height = 1
s.scale.x = 200
s.scale.y = 200
stage.addChild s

c = new MyCustomFilter()
s.filters = [c]
```
if we have a gradient from top to bottom on the custom filter, the gradient will be based on the vTextureCoord uvs which are the screen size, which is fine for fullscreen gradients, but not so fine if you want to a gradient over a specific area only.

my filter below:
```
@uniforms = {

            bl: { type: '3fv', value: [1,1,1] }
            br: { type: '3fv', value: [0,0,0] }
            tl: { type: '3fv', value: [0,0,0] }
            tr: { type: '3fv', value: [0,0,0] }
        }

        fragment = [
            'precision mediump float;'
            'varying vec2 vTextureCoord;'
            'varying vec4 vColor;'

            'uniform vec3 bl;'
            'uniform vec3 br;'
            'uniform vec3 tl;'
            'uniform vec3 tr;'

            'void main(void) {'
            '   vec2 uv = vTextureCoord.xy;'

            # mix 4 corners
            '   vec3 col = mix('
            '       mix(tl, tr, uv.x),'
            '       mix(bl, br, uv.x),'
            '       uv.y'
            '   );'

            '   gl_FragColor = vec4(col, 1.0);'

            '}'
        ].join '\n'

        @filter = new PIXI.AbstractFilter null, fragment, @uniforms
        @filters = [@filter]
```
If you have a look at the attached image, this is what happens when the browser resizes...

![abstractfilterproblem](https://cloud.githubusercontent.com/assets/1734502/12137351/dffc848c-b4a3-11e5-927d-9e094e8d6111.png)

**Comment by oal** [comment]
If you're using the filter on a sprite, try setting `s.shader = c` instead of adding it as a filter. Then the coordinates will match the size of the sprite instead of the renderer's size.

**Comment by andrevenancio** [comment]
Hey @oal I was so happy when I saw ur reply, but unfortunately it doesn't work :(
Does it work on yours? can you post a jsfiddle?

**Comment by oal** [comment]
Quick example put together using the sample from the docs and your shader: https://jsfiddle.net/LyyLxLac/1/

Uncomment line 58 and see the difference. Maybe the issue is that you need a texture for the sprite to be able to resize it. My example did not work without it.

I hope this helps.

**Comment by andrevenancio** [comment]
you're right! with a texture we can resize the sprite and then it inherits the shader! :) sorted! Thanks!
