### ISSUE TITLE
Use LOD Bias parameter in default texture shader to improve mipmapped textures at all scales

### ISSUE THREAD

**Issue by GordoRank** [pixijs/pixi.js#2277]
When setting `mipmap=true` for a texture, any sprites that use it become noticeably blurry when downsized.  After some investigation into this issue I have determined that this is down to the default WebGL mipmap LOD bias setting, which appears to not always give the best size mipmap at all levels.  There is a very simple fix however.

`texture2D` takes a third parameter which modify's this LOD bias:

For an example see here:

https://www.shadertoy.com/view/4slGWn

In my case simply adding the 3rd parameter to `texture2d` in PIXI's default texture shader and setting it to `-1.0` makes all my sprites perfectly sharp at all levels of zoom/scale. e.g.

 `texture2D(uSampler, vTextureCoord, -1.0)`

The difference in my case is absolutely tremendous.  Prior to doing this I had implemented manual mip-mapping in our application code simply because our textures were so blurry when downsized.  Obviously this was not an ideal solution either performance or quality-wise.  

It would be great to see this as an option in the `webGL` renderer, something like this:

```

var renderer = PIXI.autoDetectRenderer(width, height, {
             transparent : true,
             resolution : pixelRatio,
             preserveDrawingBuffer : true,
             antialias : false,
             forceFXAA : false,
             mipmapLODbias : -1
});
```

If present it could simply be sen into the default shader as a uniform.

For clarity here is the complete modified default shader:

```
TextureShader.defaultFragmentSrc = [
    'precision lowp float;',

    'varying vec2 vTextureCoord;',
    'varying vec4 vColor;',

    'uniform sampler2D uSampler;',

    'void main(void){',
    '   gl_FragColor = texture2D(uSampler, vTextureCoord, -1.0) * vColor ;',
    '}'
].join('\n');

```

Incidentally, as shown in in the shadertoy example above, this is also a very good way to add a fake box blur to any sprite, which is infinitely faster than actually using a custom blurring filter.  Perhaps worth thinking about?

Here is a quick comparison, you will need to open up the actual images to full size in order to see the dramatic difference.  Please note the blurriness of the girl in the first example.  Which is a single sprite with a single texture.

No LOD bias set:
![example1](https://cloud.githubusercontent.com/assets/6388079/12193172/820868ec-b5dd-11e5-8fb0-bb13579bad78.jpg)

LOD Bias set to -1.0 in default shader:
![example2](https://cloud.githubusercontent.com/assets/6388079/12193187/b07a2508-b5dd-11e5-98c6-3776fd7a618d.jpg)

Also it is worth noting that adding this parameter does not effect non mip-mapped textures in any way, so it should be a very safe change.

**Comment by englercj** [comment]
Thanks for writing this up, very informative and helpful. Just have a quick question:

Would it ever be desired for different textures to have different LOD bias settings, and if so should this be a setting on a texture instead of on the renderer?

**Comment by GordoRank** [comment]
You're more than welcome. :) 

The only real reason I can think of off hand would be in order to implement individual blurring effects on a per sprite basis in a very inexpensive way.

Now that you mention it, I actually think that could be quite valuable and would recommend taking that approach other than adding a setting for the renderer.  Although it wouldn't be useful for my project, I can imagine it could be quite tasty in games that would perhaps want to animate a blur or something (as opposed to adding a shader based blur to individual sprites).  Regardless, it would certainly add more flexibility than the global setting approach I suggested.

**Comment by englercj** [comment]
Awesome, I'll add that soon then. Thanks for bringing this up!

**Comment by mariusheil** [comment]
Hi,

I tried to get this working because I have a problem with mipmaps that are too blurry. However I noticed that this has changed quite a bit in pixi v4 and I do not know where to modify this to select a different LOD. I modified some parts but did not notice any changes.

**Comment by tekintatar** [comment]
Same thing here, looks like passing the 3rd parameter LOD bias has no effect on the current version. Any ideas?

**Comment by gordyr** [comment]
@tekintatar @mariusheil - It still works fine in version 4, but you have to add the third parameter to ```texture2d``` in the multitexture shader generator , which PIXI creates automatically.  

The new spriteRenderer doesn't use the defaultFragment shader as it used to.

The correct place to add it in version 4, is in the function ```generateSampleSrc()```

**Comment by tekintatar** [comment]
thank you. It works now.

@englercj it would be great to have this LOD property on a texture basis. I just tried @ivanpopelyshev 's  plugin example located at https://github.com/pixijs/pixi-plugin-example i think this looks like the best solution to implement on a sprite basis.

**Comment by englercj** [comment]
I agree, this is still something I want to do; just haven't had time for it. I'll put it on my v5 list since that is where I am working now.

**Comment by Teoxoy** [comment]
Hi, this makes a huge difference in my app as well.
So I dug in the code and implemented the feature.
I will make a PR in a sec.
