### ISSUE TITLE
RenderTexture failed to render against WebGL

### ISSUE THREAD

**Issue by holymonson** [pixijs/pixi.js#2278]
Hi all, I need to render a Texture in several renderers parallel, so I generate a RenderTexture and save it, and immediately render it on another renderer, please check this sample code:
```js
    var img = new Image()
    img.src = '/static/img/logo@2x.png'
    // after image loaded
    var sprite1 = new PIXI.Sprite(new PIXI.Texture(new PIXI.BaseTexture(img)))
    var renderer1 = PIXI.autoDetectRenderer()
    var renderTexture = sprite1.generateTexture(renderer1)
    renderTexture.getCanvas()

    var sprite2 = new PIXI.Sprite(renderTexture)
    var renderer2 = PIXI.autoDetectRenderer()
    renderer2.render(sprite2)
    var dataurl = renderer2.view.toDataURL()
```
But it fails and warn like
```
[GroupMarkerNotSet(crbug.com/242999)!:D028058E9C7F0000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

It seems like renderTexture haven't been rendered, and found  `renderTexture.baseTexture.source == null` and `renderTexture.baseTexture.hasLoaded == true`. I'm not sure if it's right in this case.

BTW if replacing renderers to `PIXI.CanvasRenderer`, `renderTexture.baseTexture.source` would be a `CanvasHTMLElement`.

`PIXI.VERSION == "3.0.8"`, Chrome 46.0.2490.86 (64-bit) on MacOSX.

**Comment by holymonson** [comment]
Finally I found in http://pixijs.github.io/docs/PIXI.RenderTexture.html
> The renderer this RenderTexture uses. A RenderTexture can only belong to one renderer at the moment if its webGL.

I will try moving back to `CanvasRenderer`, hope you guys can solve the issue of multi renderer against WebGL. Thanks ^_^

**Comment by englercj** [comment]
If we did make it able to be used by multiple renderers, they wouldn't share the texture but have separate textures for each renderer; right now you cannot share textures/framebuffers between webgl contexts (and render texture is both).
