### ISSUE TITLE
DisplacementFilter semantics 

### ISSUE THREAD

**Issue by qbolec** [pixijs/pixi.js#2286]
I'm having a hard time with DisplacementFilter.
Most of examples found in the web are difficult to judge by human as they contain ripples, fast moving objects, random noise, or small magnitudes of changes.
But when faced with a dead simple demo like this one:
http://codepen.io/anon/pen/mVMqzm 
once can immediately see that there are several problems. 
(Btw. this example is an adaptation of a popular http://dn.ht/picklecat/ which I am not an author of)
Let me start by explaining the example.
It uses two bitmaps, which are rendered as the middle and the right picture.
The leftmost picture uses the greyscale bitmap as the displacement map.
All pictures are 128x128.
The leftmost picture is intentionally positioned in such a way that the part of it which includes my beautiful tie lies bellow the viewport.
The animation affects the scale.y of the DisplacementFilter so it waves between -50..50.

What I expected?
I expected the square part of the picture to be "cut off" and move up and down, perhaps with some stretching/bluring.

What strange things do we see instead (at least in Chrome?):
1. it looks like some parts of the image are duplicated 
2. it looks like the non-zero displacement value for a particular pixel does not make the pixel position to be displaced by a particular vector <r,g>, but rather that the color to be used for that pixel is copied from a pixel which is at relative location <r,g>. That also explains point 1.
3. it looks like if the vector tries to copy a pixel which lays outside the viewport (but not outside the texture or sprite!) then the copied color is black (or a copy of the pixel which is located at the border, which causes "a smoodge" or "a stripe" which I've seen other people reported). I want to stress out, that I'm wearing a tie on this picture which can be seen in the middle picture, but this gets somehow clamped in the leftmost picture. That is: even though there are available pixels in the texture, the shader decides to use black instead of the shirt or tie color.

After an hour of trying to wrap my head around this, I came to the conclusion that my mental model was wrong.
Here is my updated mental model:
- probably the black pixels (0 value) do not mean that there should be no displacement. Instead it means it should be negative. I base this guess on my interpretation of the line https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/filters/displacement/displacement.frag#L16 I know nothing about shaders, but I guess this line means "take the value of  the color component normalized to 0..1 and convert it to -0.5 ... 0.5. I've already used this intuition to update my demo, so that the grayscale image uses graytone 127 as the background, not the black color.
- probably the displacement vector for a particular pixel does not determine where to this pixel will be displaced, but the other way around: from which place we will copy the color to this location (at least that is my interpretation of https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/filters/displacement/displacement.frag#L19)
- probably the pixels are copied not from the real texture, but rather from the "viewport-cliped" texture (which would explain why even though the sprite and texture are big, the displaced pixels seem to be black, or copied from the border of the viewport creating "stripes")

Now, if my new mental model is correct, then I have a few issues:
1. since the original pixel values are from 0 to 255, and normalized values are from 0 to 1, then I guess that 0.5 is exactly 127.5, which is not an integer. This in turn seems to imply that there is no way to specify that a particular pixel should not move at all - the pixel color intensity can be 127 or 128 which in turn will lead to 0.4980392156862745 or 0.5019607843137255 after normalizing 0..255 to 0..1, and the displacement (computed by subtracting 0.5) will be +- 0.02. Am I right? If so, then perhaps a better way to do that would be to use a mapping in which 128 maps to 0? Is there any standard way to handle "signedness" in textures?
2. It seems that (non-scaled) values of displacement are between -0.5...0.5, which explains the peculiar choice of (undocumented!) default value of scale factor which is 20 (I guess it is to make the default range -10...10). Perhaps it would be a good idea to document that the scale factor will actually be halved as the displacement values are not -1..1 but -0.5...0.5, so any value assigned to .scale.x or .scale.y will effectively be halved.
3. is it really a standard way of interpreting displacement that the vector is used to point the location from which pixels are copied, and not the direction into which the pixel should be translated?Perhaps this should be documented, as well?
4. it looks like if the displacement vector tries to reach outside of the current viewport (not outside the texture or the sprite being filtered, but simply to pixels which lay outside of the viewport right now) then the coordinates get "clamped" and the pixel color on the edge of the viewport is used instead which leads to "stripes" being visible near the edges.

**Comment by aurelienlt** [comment]
I also had much troubles with `DisplacementFilter` and I wish I'd see this thread sooner. People giving examples of their usage show a deep misunderstanding of it, most only use gray filters, and internet offers really few explanation of how the filter works, only how to make one with Photoshop. I also had the problem that the alpha channel is interpreted too, in a totally counter intuitive way, and should thus always kept to 255.

The formula for the displacement of a pixel, for a rgba filter, seems to precisely be:

    dx = [floor(r * a / 255) / 255 - 0.5] * scale.x
    dy = [floor(g * a / 255) / 255 - 0.5] * scale.y

I thus suggest the following description of `DisplacementFilter`

> The DisplacementFilter class uses the pixel values from the specified texture (called the displacement map) to perform a displacement of an object. You can use this filter to apply all manor of crazy warping effects. The r property of the texture is used to offset the x and the g property of the texture is used to offset the y, the neutral value being 127.5. The scale controls the the range of displacement, a scale of 1 means that the displacement goes from -0.5 to 0.5, a scale of 255 means that one unit of the r and g properties is equivalent to one pixel. the default scale is 20 (displacement from -10 to 10). The a property of the texture should always be 255.

As for the lack of proper neutral, I also suggest that 128 becomes the real neutral. A simple change in `src/filters/displacement/displacement.frag` (line 16) does the trick:

    map -= 128.0/255.0;

**Comment by bigtimebuddy** [comment]
I’d welcome a PR for v5 (next branch) for the middle gray value tweak and description.
