### ISSUE TITLE
adding alpha to chroma key shader

### ISSUE THREAD

**Issue by barbarosso** [pixijs/pixi.js#2287]
We are trying to create a chroma key filter for video.  
We have adapted following shader from shadertoy to a pixi Filter: https://www.shadertoy.com/view/XsfGzn#

The original video has got a green key and we are able to replace the green values with black, but we would like to make the green values transparent. So we can see the underlying objects. 

And the video is also flipped vertically, but that's another problem...

Screenshot before filter
![alt tag](https://www.dropbox.com/s/6bepyj4eiget7ym/greenkey.png?dl=1)

Screenshot after filter
![alt tag](https://www.dropbox.com/s/80h4lgxwdevfapu/black.png?dl=1)
Can someone help us with this? We haven't got any experience with shaders.

```javascript
function ChromaFilter()
{
    core.AbstractFilter.call(this,
        // vertex shader
        null,
        // fragment shader
       ["precision mediump float;",
            "uniform vec4 dimensions;",
            "uniform sampler2D uSampler;",
            "",
            "void main()",
            "{",
            "vec2 q = gl_FragCoord.xy / dimensions.xy;",
            "vec3 bg;",
            "vec3 fg = texture2D( uSampler, q ).xyz;",
            "float maxrb = max( fg.r, fg.b );",
            "float k = clamp( (fg.g-maxrb)*5.0, 0.0, 1.0 );",
            "float dg = fg.g;",
            "fg.g = min( fg.g, maxrb*0.8 );",
            "fg += dg - fg.g;",
            "gl_FragColor = vec4( mix(fg, bg, k), 1.0 );",
            "}"].join("\n"),
        // custom uniforms
        {
            dimensions: { type: '4fv', value: new Float32Array([0, 0, 0, 0]) },
            pixelSize:  { type: '1f', value: 8 }
        }
    );
}
```

**Comment by englercj** [comment]
Y coords are inversed in framebuffers.

Try:
```glsl
vec3 fg = texture2D( uSampler, q ).xyz;
fg.y = 1.0 - fg.y;
```

**Comment by barbarosso** [comment]
I have created a js fiddle
https://jsfiddle.net/pm02gwgq/2/

@englercj if i try to inverse the framebuffer, like you told, i get a stranger effect, 
see this fiddle
https://jsfiddle.net/pm02gwgq/3/

**Comment by englercj** [comment]
Sorry, I typed `fg` but I meant `q`. That is, the coords you read from the texture.

Since Y is flipped in the framebuffer, you need to flip the Y of the coords you use to read the texture:

https://jsfiddle.net/pm02gwgq/6/

**Comment by barbarosso** [comment]
@englercj 
Thanks, that fixes the vertical flip.
Do you know how to resolve the alpha problem?
We would like to see the red background of the canvas, or underlying pixi objects.

**Comment by englercj** [comment]
All you should need to do is change the exported alpha from a hard-coded "always 1":

```glsl
gl_FragColor = vec4( mix(fg, bg, k), 1.0 );
```

To a value that is based on how "green" that pixel is.

**Comment by barbarosso** [comment]
@englercj Looks great!
I will do some testing with video tomorrow, and will try to create some demo fiddles.
Thx

**Comment by Wolverlink** [comment]
Hey @barbarosso maybe too late to ask but were you able to create the demo fiddles with video? 
Thanks in advance
