### ISSUE TITLE
Question: Using any filter on the stage halfs the framerate on my device

### ISSUE THREAD

**Issue by dcodeIO** [pixijs/pixi.js#2288]
Excuse me if this is a stupid one, I am somewhat new to this. On my iPad mini (first generation, Dual-core PowerVR SGX543MP2), attaching the following filter to the stage halfs the fps once like lets say 100 containers are in play:

```glsl
precision highp float; // intended

varying vec2 vTextureCoord;
varying vec4 vColor;
uniform sampler2D uSampler;
uniform vec4 dimensions;

void main() {
    vec3 color = texture2D(uSampler, vTextureCoord).xyz * vColor.xyz;
    gl_FragColor = vec4(color, 1.0);
}
```

Is this normal / simply due to the limitations of the device? Running 3.0.9 here.

If this is expected, is there anything I can do to improve this - like replacing the default shader with a custom one so that I don't have to use a filter at all?

**Comment by englercj** [comment]
Not sure what specifically is happening, but here is some information that might help:

When using a filter, it adds at least 1 more framebuffer to the mix along with at least 1 more shader pass (depending on the filter). Say for example you were just barely getting exactly 60 fps, then doubling the shader passes could in fact cause it to drop.

Using `highp` on certain devices can be seriously performance impacting, just as an experiment try only messing with the precision there. On desktop you rarely (if ever) notice, and most modern mobile devices are fine; but older devices can easily choke.

Last thing to try is profiling and WebGL inspector to ensure the bottleneck is actually the shader itself and not some weird js we have instead.

Hope that helps!

**Comment by dcodeIO** [comment]
Thanks, that definitely helps. I tried mediump and lowp, but still the same.

Now I am replacing `TextureShader.defaultFragmentSrc` by editing the pixi source as I can't seem to find a way to access that properly. Isn't that exposed somewhere on the PIXI namespace?

**Comment by englercj** [comment]
Make sure also, that your sprites are getting batched. To be batched they need to use the same shader and have the same base texture.

If you have a bunch of sprites, and they all have the same shader (either default or .shader property all the same) and the same base texture (can be different texture objects, but needs to be the same underlying baseTexture object) then they will all be drawn in a single draw call.

You can see if you have a bunch of draw calls by checking `renderer.drawCount` and seeing how many calls you are making. That could also be an issue.

**Comment by dcodeIO** [comment]
Thanks again! Just reduced draw calls from 10 to 4 by rearranging some stuff. Probably not a significant improvement, but an improvement, isn't it.

I wonder if I could actually use ParticleContainer here.

**Comment by englercj** [comment]
If they are all sprites, and the hierarchy is only a single layer deep, you should try it. All sprites within a particle container *must* share a base texture, and by definition of the container they will share a shader (the particle container's shader).

**Comment by dcodeIO** [comment]
After finally finding out how to replace the standard shader (for everyone curious:)

```js
renderer.plugins.sprite.shader = myTextureShader
```

it turns out that my shader is shit. While I get like 10 more frames by replacing the standard shader, doing

```glsl
color *= 0.95 + 0.05 * sin(0.01 * time + vScreenCoord.y);
```

to emulate scanlines seems to be too much (considering I want 60 instead of 40fps) for my iPad ^^

**Comment by dcodeIO** [comment]
Noticed that ParticleContainer (performs great btw!) weirdly stretches animated sprites when using a spritesheet with trimmed whitespace around the individual frames. There's no issues with non-trimmed spritesheets. Is that simply a general restriction? Putting this here before I post something stupid again.

**Comment by englercj** [comment]
Not really an intentional one, we probably just forgot to implement support :P

**Comment by dcodeIO** [comment]
Well then, will just use non-trimmed spritesheets for now :)

New hotness:
![](http://i.imgur.com/vhkPF80.png)

Not sure if
* a) what I am doing here simply is super optimized already so that bufferSubData became the heaviest call
* b) putting lots of moving, rotating and fading stuff into a ParticleContainer is stupid or
* c) that's just something that needs to be optimized ^^

**Comment by englercj** [comment]
Yeah tuning the size to be closer to your batch sizing will yield *much* better performance since we don't have to do expensive sub arrays and such.

Glad it is working out!

**Comment by dcodeIO** [comment]
Next part of dc's adventures in ParticleContainer wonderland: When generating mipmaps of my spritesheet, and I scale a sprite (like a healthbar) on the X axis only, it picks the corresponding mipmap level, even if scale on Y axis is still 100%. Basically it's: The lower the health, the more awkward the sprite. Currently trying to figure out how to prevent this - any advise? ^^

**Comment by dcodeIO** [comment]
Alright, I am cropping the image now. This is a bit awkward, though, and requires all textures to be unique, which sums up quite a bit for healthbars:

```js
this._texture.crop.width = newWidth
this._texture._updateUvs() // which is "protected" and requires touching pixi.js.d.ts
```

I could also assign a new frame of course, but this goes through that many ifs that I'd rather avoid it. Having crop functionality on sprites would be ideal.

**Comment by dcodeIO** [comment]
So, I am trying to crop the frame of a texture, represented by a Sprite within a ParticleContainer, from frame to frame.

What's happening is this: https://jsfiddle.net/79zgL7gr/2/

Not sure if I am doing something wrong here, but what's rendered is obviously wrong. The expected picture is a 10 px height sprite on the left side, and a 40 px (full sized) sprite on the right.

If I comment out the contents of the else-clause, the the left sprite is in fact 10 px in height, but if it is updated dynamically, it's also 40 px.

Any hints how to do this right? Tried assigning frames etc., but nothing seems to work.

**Comment by dcodeIO** [comment]
Found a workaround: https://jsfiddle.net/79zgL7gr/6/

Calling addChild/removeChild for a dummy sprite each frame seems to make it work. This an issue?

**Comment by englercj** [comment]
You changed height (scale) but didn't tell the particle container that scale is dynamic.

**Comment by dcodeIO** [comment]
Hmm, thanks! Really thought this is not scale. Hope I turned not too annoying already, seems that I still have to learn a lot of stuff :)

**Comment by englercj** [comment]
Anytime, not annoying at all :)

**Comment by GoodBoyDigital** [comment]
closing as looks resolved to me :+1:
