### ISSUE TITLE
Custom shader for sprite

### ISSUE THREAD

**Issue by gillesboisson** [pixijs/pixi.js#2290]
Hi,

I'm looking for some infos or doc about how PixiJs manage shaders. I want to create a custom shader for sprites in order to manage lighting. As Geometry of each sprite impact the result I can't use filters. Is there any clean way to create custom shader to extend sprite rendering ?

Cheers

**Comment by englercj** [comment]
If you assign a filter to the `.shader` property of the sprite, the shader for that filter object will be used as the shader to draw the sprite (instead of as a post-processing effect).

ref: http://pixijs.github.io/docs/PIXI.Sprite.html#shader

**Comment by andrevenancio** [comment]
I've been raising a couple of issues on this matter. just be mindful that if your sprite doesn't have a width and a height, the shader will apply the uv's to the window.innerWidth, window.innerHeight

refer to https://github.com/pixijs/pixi.js/issues/2274

**Comment by gillesboisson** [comment]
Thanks for the info, I investigate on using assigning directly a shader to my sprite, but in my case wanted to send extra data to vertex shader. I did it this way :
- create CustomSprite,CustomSpriteRenderer,CustomTextureShader extending Sprite,SpriteRenderer,TextureShader
- setup CustomSprite to use CustomTextureShader and CustomSpriteRenderer for rendering
- setup CustomSpriteRenderer with a new vec2 attributes and sprite geometry to vertex buffer
- update my shader with the new attributes and custom vertex and fragment shader

my sprite still render, I can see that on webgl inspector vertex data are send properly but in my vertex shader my new vec2 attribute is 0,0

I investigate on my CustomSpriteRenderer start function :

```
var gl, stride;
      NormalRenderer.__super__.start.call(this);
      gl = this.renderer.gl;
      stride = this.vertByteSize;
      return gl.vertexAttribPointer(this.shader.attributes.normalT, 2, gl.FLOAT, false, stride, 5 * 4);
``` 

the issue is that this.shader return the default TextureShader created from renderer.shaderManager (ShaderManager class)

I can see that for now there is no clean way to the default renderer of the my renderer default shaderManager, there is TODO (ShaderManager::onContextChange) indicating it will be refactor to plugins. 

is there any not too dirty to way to customize a renderer default TextureShader ? Or I should wait or give finding how we can move this using PIXI-js plugin system ?

**Comment by gillesboisson** [comment]
I finally find a clean way to do it. I override the onContextChange of my CustomSpriteRenderer class.

```
CustomSpriteRenderer.prototype.onContextChange = function() {
      CustomSpriteRenderer.__super__.onContextChange.call(this); // call parent function (coffeescript)
      return this.shader = new CustomTextureShader(this.renderer.shaderManager);
    };
```

**Comment by ttencate** [comment]
@englercj:

> If you assign a filter to the `.shader` property of the sprite, the shader for that filter object will be used as the shader to draw the sprite (instead of as a post-processing effect).

Is this true? Using Pixi 4.0.3., assigning to `.shader` doesn't seem to have any effect, and I can't for the life of me find the code that is supposed to make this happen.

**Comment by ivanpopelyshev** [comment]
There's no way to use custom shader with sprite in v4. There's demo how to do it using renderer plugin: https://github.com/pixijs/pixi-plugin-example . You can make it that way it accepts a filter, but its better to make separate shader, because filter now has some extra uniform variables

**Comment by GoodBoyDigital** [comment]
Hello1 Yup - this is on the todos and part a little refactor I'm working on.
