### ISSUE TITLE
Containers transformations do not apply when rendering on texture

### ISSUE THREAD

**Issue by RonenNess** [pixijs/pixi.js#2291]
If you create a container, set scale, position, etc. and render this container on a RenderTexture, it will render all sprites inside but **without** the container transformations.

To reproduce take this code:

```javascript
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

// create a new Sprite using the texture
var texture = PIXI.Texture.fromImage('_assets/basics/bunny.png');
var bunny = new PIXI.Sprite(texture);

// move the sprite to the center of the screen
bunny.position.x = 200;
bunny.position.y = 150;

// create render texture and sprite
var render_texture = new PIXI.RenderTexture(renderer, 800, 800);
var render_texture_sprite = new PIXI.Sprite(render_texture);
stage.addChild (render_texture_sprite);

// create a container and add sprite to it
var container = new PIXI.Container();
container.addChild(bunny);

// these transformations will NOT apply, for some reason..
container.scale.x = 100;
container.position.y = 100;
// ????

// start animating
animate();
function animate() {
    requestAnimationFrame(animate);

  	render_texture.render(container);
    renderer.render(stage);
}
```

And paste it here: http://pixijs.github.io/examples/

No matter what transformations will be applied on container, it will not take effect when rendered on the texture.

**Comment by RonenNess** [comment]
Note: pushing the container into another empty container and rendering the parent container instead seems to make it work. however it still look problematic that the transformations of the display object itself won't apply.

**Comment by dcodeIO** [comment]
This is actually documented behaviour [around here](https://github.com/pixijs/pixi.js/blob/962f5bdff1ed2d96cfeaef22897ed83b7cce79bd/src/core/textures/RenderTexture.js#L16)

**Comment by RonenNess** [comment]
oh sorry, I totally missed that.
thanks.
