### ISSUE TITLE
Why is there no a threshold filter ?

### ISSUE THREAD

**Issue by pipriles** [pixijs/pixi.js#2297]
Why there is no a threshold filter, i think it would be a very good addition for PIXI.

**Comment by andrevenancio** [comment]
what is it supposed to do? can you provide an example of how it should behave?

**Comment by pipriles46** [comment]
I was working in a liquid simulation using Liquid Fun and PIXI, so i wanted to render the liquid and to do it i wanted to blur and then apply a threshold filter.
Look at this: http://www.patrickmatte.com/?p=29

**Comment by GoodBoyDigital** [comment]
We can add this to the pixi-filters repo 👍
