### ISSUE TITLE
v4 structure idea

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#2299]
Hey guys!

Wanted to float some thoughts past you all to see what you think.I have some thoughts on tweaking the the structure of pixi containers for v4. This structure would basically minimise the need for extending classes and make pixi more component based.

I am currently thinking we have one new base class that all others use (name pending!)

```
var Node = function(transform, renderableItem)
{
    this.transform = transform || new DefaultTransform()
    this.children = [];
    this.renderableItem = renderableItem;
}
```

This way all objects can use this class. The renderable item would be either an image / graphics / mesh etc. Nice and easy to use.

We could still have a 'container' and a 'sprite' but they would essentially be variations of the above. We can bolt on extra functionality as required, but this base class would be very simple.

Feels quite clean to me, what do you peeps think?

Thanks!

**Comment by tobireif** [comment]
Sounds good to me, but others who are more involved in developing the code base (Chad etc) probably are aware of many more implications/consequences/aspects :)

**Comment by GoodBoyDigital** [comment]
true enough! What do you guys think @englercj @photonstorm @ivanpopelyshev ?

**Comment by ivanpopelyshev** [comment]
I think that's very good idea. As for old container and Sprite, they can be implemented with big number of getters/setters, but all inner works will be in renderableItem

**Comment by ivanpopelyshev** [comment]
More arguments: this is VERY GOOD IDEA because that will allow to use one renderableItem per multiple "windows". If the game has portals or mirrors (like gameofbombs.com), it will re-construct pixi stage every frame, renderableItems wont be copied but they'll appear in multiple nodes.

**Comment by englercj** [comment]
Is the idea to separate the scene graph from the items being rendered? The graph is used to update transforms, and then the renderables are drawn?

I like the idea in theory, but I need to see more of actually how it is implemented.

**Comment by ivanpopelyshev** [comment]
Yeah, how exactly are you going to call renderCanvas and renderWebGL in that case? Will you pass the "node" inside? That way renderableItem will be able to use extra data from other components :+1:

**Comment by ivanpopelyshev** [comment]
There have to be some component that deals with sizes. "sprite.dim.width = 100; sprite.dim.height = 200;" that kind of stuff.

**Comment by ivanpopelyshev** [comment]
I have to ask: why not ES6? At least do it for classes stuff, I just hate this prototype syntax.

**Comment by tobireif** [comment]
@ivanpopelyshev
> I have to ask: why not ES6? At least do it for classes stuff, I just hate this prototype syntax.

Some aspects to consider:

https://github.com/joshburgess/not-awesome-es6-classes

Perhaps a nice option:
https://davidwalsh.name/javascript-objects-deconstruction
-> "'without any of the confusion/distraction of "constructor functions", new, .prototype, etc.'

**Comment by photonstorm** [comment]
None of those 'not awesome' reasons for avoiding ES6 classes give any actual technical reasoning. 

They're all just "inheritance is bad, composition is cool" - which on the face of it is fine, but actually isn't a reason to not use an ES6 class over the current 'fake class' prototype approach. Pixi already has inheritance, lots of it. Moving to using ES6 classes won't compound this fact.

**Comment by ivanpopelyshev** [comment]
Most of the cases I use objects is inheritance. Entity/Component model which we are going to use works on inheritance well, it doesnt need composition. Writing "class" instead of "prototype" is making code more compact and understandable. Also composition is possible in ES6, its just works another way.

**Comment by tobireif** [comment]
> None of those 'not awesome' reasons for avoiding ES6 classes give any actual technical reasoning.

I just wrote they're aspects to consider :)

**Comment by ivanpopelyshev** [comment]
@tobireif yeah, that doc is funny :)

**Comment by Oza94** [comment]
Maybe its a little late but +1 on ES6 Classes for Pixi, after all this is just syntaxic sugar about something you're already doing. 

The best proof? In my porject I extend Pixi objects with ES6 Classes (mostly for UIs) and it works very well. Small truncated example : 

```js
import Pixi from 'pixi.js';
import UIStyle from './style';

export default class UIBaseMonsterState extends Pixi.Container {
  constructor() {
    super();

    this.bg = new Pixi.Graphics();
    this.bg.beginFill(UIStyle.Window.background);
    this.bg.lineStyle(2, UIStyle.Window.border);
    this.bg.drawRoundedRect(48, 8, 194, 16, 4);
    // ...
    // more and more and more stuff
  }
  doSomething() { /*...*/ }
  updateStuff() { /*...*/ }
}
```

This is really pleasant to use compared to the classical ES5 inheritance with prototypes.

**Comment by DennisSmolek** [comment]
+1 to what @Oza94 said, I use pixi WAY different than most folks as it ties into my Angular2 app which is written totally in typescript using ES6 class structure. Our original app was designed using DOM elements but for more advanced stuff I decided to switch to a canvas/GL based engine.

It took me a while to get used to it originally but now it speeds up my work, is much cleaner, and I'm more efficient.

**Comment by GoodBoyDigital** [comment]
closing this for now - in practice this did not really offer much so will not be did not go down this path for v4.

@DennisSmolek We will absolutely consider es6 for the next version mind.

**Comment by fr4ngus** [comment]
@DennisSmolek I am very intrested if you could share your code concerning your own implementation of Pixi with Angular2 cause I want to use it in my website.
Thanks !
