### ISSUE TITLE
How to : Human hand and finger animation?

### ISSUE THREAD

**Issue by shivrajsa** [pixijs/pixi.js#2300]
I want to create a human hand & finger animation on musical instrument (For example : guitar) to demonstrate how to play instrument when some sequence of notes are given.
Is it possible to do it with pixi & what would be the correct way to achieve this
1. with json data of hand & fingers? how can I create pixi compatible json data?
2. with images of each position of hand & finger?
3. . . .
Please help. If there is any other solution than pixi then please guide.

**Comment by englercj** [comment]
Look into [spine](http://esotericsoftware.com/) and [pixi-spine](https://github.com/pixijs/pixi-spine).
