### ISSUE TITLE
ColorMatrixFilter does not operate correctly on alpha channel

### ISSUE THREAD

**Issue by mattlima** [pixijs/pixi.js#2302]
This is a follow up to https://github.com/pixijs/pixi.js/issues/1342 - I've done a lot of research before posting here. I'm working on some recursive filtering in a project and I'm having a similar issue with alpha; There's not a ton of material on the behavior of the alpha channel in the color matrix filter; I've looked at the source and it seems very straightforward in that the alpha channel of pixels resulting from a matrix filter where indexes 15-19 are zero should be zero, i.e., the result should be a transparent sprite. This isn't the case.  I've updated the original codepen to pixi v3: http://codepen.io/mattlima/pen/LGOBmv – I'm sure you're insane busy but if you could point me in the right direction I'd really appreciate it.

**Comment by jackie-t** [comment]
I am affected by this too - it seems that transparent parts are heavily mixed with black. Even if I only change the hue by 1 (with the official method, so I'm not playing around with custom matrices), the color is distorted.

Look here for an example that overlaps two pictures - one with the ColorMatrixFilter applied, and one without. As it is, it makes the ColorMatrixFilter almost completely useless.

http://codepen.io/anon/pen/JGVpyP

Here's a screenshot of the result - yes, the black "bar" is the same green you see above, with the hue shifted by 1°: https://gyazo.com/12af2b1c8f8d50b87f94f46d1f680b48

**Comment by jackie-t** [comment]
Just to reiterate, the referenced issue does not fix this bug. Changing the hue by even 1° causes issues with images that rely on the alpha channel. The problem in https://gyazo.com/12af2b1c8f8d50b87f94f46d1f680b48 (that two images with a 1° hue shift are black when merged) exists despite the fix.
