### ISSUE TITLE
generateTexture signature is inconsistent

### ISSUE THREAD

**Issue by LukaszGrela** [pixijs/pixi.js#2304]
I've noticed that:

`DisplayObject.prototype.generateTexture = function (renderer, scaleMode, resolution)`
and
`Container.prototype.generateTexture = function (renderer, resolution, scaleMode)` 
or
`Graphics.prototype.generateTexture = function (resolution, scaleMode)`

have different order of arguments (or number), there is no real need to do this  and also this upsets the `google-closure-compiler` which reports following error:

```
Running "closure-compiler:dev" (closure-compiler) task
>> grunt-google-closure-compiler: src/externs/pixi-3.0.8-externs.js:2745: WARNING - mismatch of the generateTexture property type and the type of the property it overrides from superclass PIXI.DisplayObject
>> original: function (this:PIXI.DisplayObject, (PIXI.CanvasRenderer|PIXI.WebGLRenderer|null), number, number=): (PIXI.Texture|null)
>> override: function (this:PIXI.Container, (PIXI.CanvasRenderer|PIXI.WebGLRenderer|null), number, number): (PIXI.Texture|null)
>> PIXI.Container.prototype.generateTexture = function (renderer, resolution, scaleMode) {};
>> ^
>>
>> src/externs/pixi-3.0.8-externs.js:3360: WARNING - mismatch of the generateTexture property type and the type of the property it overrides from superclass PIXI.DisplayObject
>> original: function (this:PIXI.Container, (PIXI.CanvasRenderer|PIXI.WebGLRenderer|null), number, number): (PIXI.Texture|null)                                                                                                                 >> override: function (this:PIXI.Graphics, number, number, number=): (PIXI.Texture|null)
>> PIXI.Graphics.prototype.generateTexture = function (resolution, scaleMode) {};
>> ^
>
```

**Comment by englercj** [comment]
https://github.com/pixijs/pixi.js/search?utf8=%E2%9C%93&q=generateTexture

Looks like just the DO one is wrong:

https://github.com/pixijs/pixi.js/blob/962f5bdff1ed2d96cfeaef22897ed83b7cce79bd/src/core/display/DisplayObject.js#L483

**Comment by LukaszGrela** [comment]
Hmm, yes, I assume it is not worth to have a type test and swap the params for "old" use?

probably resolution and scaleMode can't be recognised from eachother?

**Comment by englercj** [comment]
both are numbers :(

**Comment by LukaszGrela** [comment]
maybe based on the valid ranges? surely there is distinct difference between `resolution` and `scaleMode`?

**Comment by englercj** [comment]
scaleMode is a constant value in the range [0, 5] and the resolution is generally in the range [1,3].

Hard to tell the difference...

**Comment by GoodBoyDigital** [comment]
Thanks for highlighting @LukaszGrela ! generateTexture has been moved to the renderer now for v4. This means all objects get rendered through a single function :+1:
