### ISSUE TITLE
use with gulp

### ISSUE THREAD

**Issue by JordanDelcros** [pixijs/pixi.js#2305]
Hi!

I just started pixi.js and it seems marvelous!
But I can't make it totally work with Gulp and WebPack...

On Chrome (Mac), everything work but on Safari (iPhone) i get this error: `fs.readFileSync is not a function` from `function FXAAFilter`.
I get the same error on desktop when I use `forceFXAA: true`.

My gulp scripts task :

```javascript
	gulp
		.src(config.scripts.src)
		.pipe(gulp_webpack({
			node: {
				fs: "empty"
			},
			module: {
				loaders: [
					{
						test: /\.js$/,
						exclude: /(nodes_modules)/,
						loader: "babel-loader",
						query: {
							presets: ["es2015"]
						}
					},
					{
						test: /\.json$/,
						loader: "json"
					}
				],
				postLoaders: [
					{
						include: path.resolve(__dirname, "nodes_modules/pixi.js"),
						loader: "transform?brfs"
					}
				]
			},
		}))
		.pipe(gulp_concat(config.scripts.out))
		.pipe(gulp.dest(config.scripts.dst));
```

**Comment by englercj** [comment]
Been posted a few times, may this can help?

https://github.com/pixijs/pixi.js/wiki/Using-Pixi.js-with-Webpack

**Comment by JordanDelcros** [comment]
Nope, none of this work... Still got the same error... none of the `filters` are "loadable/usable"...

**Comment by englercj** [comment]
brfs is the thing that resolved those into strings, if they aren't getting resolved then brfs isn't running properly.

Maybe post for help on the forums or from one of the webpack guys? I honestly don't know :(

**Comment by GoodBoyDigital** [comment]
v4 uses glslify instead of brfs to load and compile shaders into the build step. Fortunatly glslify has a webpack plug in too so you should be good to go :+1:
