### ISSUE TITLE
PIXI.Container();

### ISSUE THREAD

**Issue by dbroadhurst** [pixijs/pixi.js#2308]
Most examples call

var container = new PIXI.Container();

but I'm getting "TypeError: PIXI.Container is not a function"

When I inspect in Chrome I can see Container is not defined in PIXI.

Any ideas?

**Comment by englercj** [comment]
How are you including pixi in your project? And what version is logged to your console?

**Comment by dbroadhurst** [comment]
I include using a script tag in index.html.

```
	<script type="text/javascript" src="vendor/pixi/pixi.js"></script>
```

I've tried to pull down with bower and github (used gulp build) with the same results.

I don't see a version number in the console with

```
      var renderer = new PIXI.WebGLRenderer(800, 600);
      canvas.appendChild(renderer.view);
      var stage = new PIXI.Container(); <= error
```

**Comment by englercj** [comment]
When you create the renderer it should log out the version number. If `Container` isn't defined you are likely using v2 of pixi, not the latest.

**Comment by dbroadhurst** [comment]
Thanks. I was including the old version
