### ISSUE TITLE
Multitouch: objects receive wrong touchend event

### ISSUE THREAD

**Issue by alclub** [pixijs/pixi.js#2309]
BUG: 
If two sprites are handling touchstart and touchend events, sometimes one sprite receives BOTH touchend events, and the other sprite does not receive any touchend events.

Here is a gif demonstrating the effect: https://gfycat.com/PleasingIncompleteAardwolf
As you can see in the console, a sprite will receive a touchstart event, then remember the touch 'identifier' that is embedded in the event. All sprites receive ALL unrelated touchmove events, therefore the sprite must filter out events which pertain to itself by checking the identifier in each event (not printed to console). However, sometimes one sprite receives all the touchend events, including those that contain identifiers associated with the other sprites. These other sprites don't get their touchend events.

SOLUTION:
The workaround stated here involving adding checks to the processTouchStart and processTouchEnd:
http://www.html5gamedevs.com/topic/19273-can-container-get-touchup-event-when-touchdown-of-other-container-press/

Alternatively, perhaps all sprites should receive all touchend events, just like they receive all touchmove events, and allow each sprite to remember its own touchstart identifier, and then listen for a touchend which has the same identifier.

**Comment by andrewstart** [comment]
This should be fixed with the better use of touch identifiers in #3546.
