### ISSUE TITLE
Confused on setting size

### ISSUE THREAD

**Issue by holymonson** [pixijs/pixi.js#2311]
In the constructor of `SystemRenderer`, size is set directly:
```js
    /**
     * The width of the canvas view
     *
     * @member {number}
     * @default 800
     */
    this.width = width || 800;
```

While in `SystemRenderer.resize()`, it multiplies with `resolution`:
```js
SystemRenderer.prototype.resize = function (width, height) {
    this.width = width * this.resolution;
    this.height = height * this.resolution;

    this.view.width = this.width;
    this.view.height = this.height;
```

I guess the _size_ should be _size of view_ instead of _size of canvas_, so I correct the `SystemRenderer.resize()`. However, things go wrong after patched, we got a `1/4` shorten (in length) image in `resolution = 2`, it seems the size handling in `render()` is incorrect. Would anyone please take a look?

**Comment by holymonson** [comment]
Furthermore, re-assigning `resolution ` seems prohibited, `WebGLRenderer._initContext()` uses `resolution` to create `RenderTarget` in constructor.

**Comment by GoodBoyDigital** [comment]
This is expected behaviour I believe. That or maybe I don't understand the problem you are trying to solve?
