### ISSUE TITLE
PIXI.PrimitiveShader is not a function

### ISSUE THREAD

**Issue by webbiesdk** [pixijs/pixi.js#2312]
According to the documentation (http://pixijs.github.io/docs/PIXI.PrimitiveShader.html), the primitive shader can be instantiated like: 

    new PIXI.PrimitiveShader(shaderManager);

The TypeScript declaration file agrees with this, and says that there should be a `PrimitiveShader` class on the PIXI object. 

The problem is that there isn't a PrimitiveShader property on the PIXI object, so i get a `undefined is not a function` whenever i attempt to actually execute `new PIXI.PrimitiveShader(shaderManager);`

I am not trying to make a PIXI project, I am trying to understand the documentation and declaration. 

I'm running PIXI 3.0.9, and the TypeScript declaration file is also for 3.0.9. 
I'm loading PIXI by simply referencing the version on cdnjs.com. 

The problem isn't just with PrimitiveShader, there is the same issue for: 

* PrimitiveShader
* BlendModeManager
* SystemRenderer
* CanvasMaskManager
* TextureShader
* ComplexPrimitiveShader
* FilterManager
* CanvasTinter
* EventEmitter
* StencilManager
* MaskManager

**Comment by englercj** [comment]
None of these objects are actually exported:

https://github.com/pixijs/pixi.js/blob/master/src/core/index.js

But they are in the docs because we document all of our classes, even internal ones.

**Comment by webbiesdk** [comment]
Well ok that explains that, but there are still some things that doesn't match up. 

**PIXI.FXAAFilter:**
FXAAFilter is available on the PIXI object (and the documentation agrees with this), but in the typescript declaration files states that it is available on PIXI.filters.FXAAFilter. 
Accessing PIXI.filters.FXAAFilter prints the warning `filters.FXAAFilter is an undocumented alias, please use FXAAFilter from now on.`
I'll make a pull-request to fix that over in pixi-typescript. 

**PIXI.ParticleRenderer and PIXI.ParticleRenderer**
Both are classes on the PIXI object, both have no documentation in the [documention](https://pixijs.github.io/docs/), and both are simple interfaces in the documentation file, which does not reflect their nature of being classes. 
I might make a pull-request over at pixi-typescript to get them started.

I think that was it for now here, so I'm closing the issue. 

Thanks for the help.

**Comment by englercj** [comment]
Just FYI the typescript def file is maintained separately, and by hand. If it is out of sync it is likely just human error. Thanks for taking the time to look into this and to correct the definition file, we appreciate!
