### ISSUE TITLE
Browserify debug inline sourcemaps

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#2317]
Doing a clean `npm install` and then running `gulp` produces the un-minified version of **bin/pixi.js** with a rather chunky, inline Base64 encoded sourcemap (file is >2.1MB). I would assume this is a mistake since this isn't in v3.0.9. Offending Gulp line is [here](https://github.com/pixijs/pixi.js/blob/master/gulp/util/bundle.js#L63) (when Browserify's `debug` option is set to true no spits out inline sourcemaps).

**Comment by ivanpopelyshev** [comment]
PR please?

**Comment by englercj** [comment]
Sourcemaps were at one point being extracted with:

https://github.com/pixijs/pixi.js/blob/master/gulp/util/bundle.js#L27-L29

But some update caused that to stop working, that being said there is nothing wrong with the inline source maps the way they are. The unminified file should only ever be used for debugging and should never be shipped anywhere.

**Comment by bigtimebuddy** [comment]
This seems broken and not the intended behavior of the build scripts. Is it worth more to fix the externalized sourcemaps, to lock down the devDependencies versions, or cleanup the build scripts to reflect the dependency change?

**Comment by GoodBoyDigital** [comment]
He chaps! That does indeed look odd, I tend to use the unminified pixi build in my projects so I would definitely prefer the source map to be external if possible.

**Comment by GoodBoyDigital** [comment]
closing as this has been addressed with v4
