### ISSUE TITLE
Link to outdated libraries in examples (.md and pixijs.com home)

### ISSUE THREAD

**Issue by bitbay** [pixijs/pixi.js#2326]
I just realized that the [example pages](http://www.pixijs.com/examples/) (PIXI v3 in the header) use all kind of versions of the library.
First ["basics"](http://www.goodboydigital.com/pixijs/examples/1/) using [v1.3.0](http://www.goodboydigital.com/pixijs/examples/1/pixi.js)
Latest ["lasers"](http://www.goodboydigital.com/pixijs/examples/lasers/) using [v1.5.2](http://www.goodboydigital.com/pixijs/examples/lasers/pixi.js)
and what caught my attention was ["interactivity"](http://www.goodboydigital.com/pixijs/examples/6/) using [v1.0.0](http://www.goodboydigital.com/pixijs/examples/6/pixi.js) (!).

5¢
I know that these examples should not be used for "testing", but definitely would be helpful to see how the library does the things it promises in its "live" demos, in it´s "latest and greatest" form, not to mention serving as a knowledge-base for newcomers.
Probably this is not intentional, but a library this wide-spread should take better care of it´s reputation.

**Comment by ivanpopelyshev** [comment]
Yeah, not every example has latest version in http://pixijs.github.io/examples/. by the way , i have new (demo)[http://ivanpopelyshev.github.io/examples/index.html?s=demos&f=texture-rotate.js&title=Texture%20Rotate ]

**Comment by NikkiKoole** [comment]
I ran into something related lately too, I went to try and use the NormalMapFilter, from http://www.goodboydigital.com/pixijs/examples/20/ this example, but I cannot get it working anymore under a recent pixi.. ;)

**Comment by GoodBoyDigital** [comment]
examples are being updated... watch this space 👍
