### ISSUE TITLE
Memoryleaking in generateTexture?

### ISSUE THREAD

**Issue by boymaas** [pixijs/pixi.js#2327]
We encountered an interesting case where we noticed increasing memory usages. We are "pre-rendering" complex structures using generateTexture and noticing an increase in memory usage per "pre-render".

Investigating the problem, we saw in the chrome heap snapshots the following:
![image](https://cloud.githubusercontent.com/assets/300333/12641420/b7dc9ce0-c5af-11e5-9711-a8c469a64a4d.png)

Looking at the code we found:
https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/graphics/Graphics.js#L702

which creates an CanvasBuffer which doest the following:
https://github.com/pixijs/pixi.js/blob/5d385885324e97369fd29b686e9e90eb4cefd14a/src/core/renderers/canvas/utils/CanvasBuffer.js#L16

This seams introduce per generateTexture call a static element to which the "pre-rendered" stays allocated. As can be seen in the heap snapshot. 

I was not aware of this, and its not by my knowledge in the documentation. This could lead to unexpected problems as CanvasBuffer is used internally and there is no way to release it as a caller.

We tried to pinpoint it down, it may have something to do with:
 this.canvas = document.createElement('canvas');
but I cannot tell this for sure. We really isolated the memory leak to the generateTexture call so somehting is there. We are using PIXI 3.0.7, any help or insight would be appreciated.

Great work with PIXI, we enjoy using it every day!

-Boy

**Comment by englercj** [comment]
Are you destroying the generated textures when you are done with them?

**Comment by boymaas** [comment]
Thx! exactly the info we were looking for, we will rewrite using RenderTexture.
