### ISSUE TITLE
No `tint` property for `PIXI.Container`

### ISSUE THREAD

**Issue by AndyBarron** [pixijs/pixi.js#2328]
Is it possible to implement `tint` for `PIXI.Container`? Since `alpha` is already supported, `tint` makes sense.

I know it would technically be possible to loop through the children and tint them, but this won't work e.g. if you have a `Container` with instances of both `Sprite` and `Container` as children. And in my use case, the children of the `Container` change often, so I don't want them to have a residual tint after calling `removeChild`.

**Comment by ivanpopelyshev** [comment]
so, separate it to tint and worldTint, like alpha and worldAlpha?

**Comment by AndyBarron** [comment]
Well, `worldAlpha` is the read-only computed alpha based on a `DisplayObject`'s parents. So it would make sense to add `worldTint` in the same fashion if this went through.

**Comment by rejemy** [comment]
I work around this by using a ColorMatrixFilter, which you can set on a container, but it's overkill for most tinting use cases. Having tint be supported by all display objects along the chain would definitely be more user friendly, and is certainly technically possible, if implemented along the same lines as alpha currently is.

**Comment by GoodBoyDigital** [comment]
we can make a little plugin for this I think!

**Comment by englercj** [comment]
Moving to v5.

**Comment by praleks** [comment]
tint is color multiplication, how about to make color addition e. g. color offset?

**Comment by ivanpopelyshev** [comment]
@praleks  here: https://github.com/gameofbombs/pixi-heaven
