### ISSUE TITLE
Hardcoded 60 fps in MovieClip

### ISSUE THREAD

**Issue by daniele-pini** [pixijs/pixi.js#2329]
Hi, I was trying to implement a moving sprite with an animated texture using MovieClip, and it basically works fine.

But here's the catch: the animated texture represents a short hand-drawn man walking around, meant to be played at 25 fps - while the default rendering fps in PIXI is 60.

So, imagine the little guy's sprite moving around at twice the speed of its walking animation - the movement appears 'too smooth' with respect to the texture updates.

In my case, it would be best if the sprite could move in sync with the texture updates. So, since my application doesn't need a global framerate that high, I just tried changing the value of PIXI.TARGET_FPMS directly to match my desired fps.

But doing so breaks the framerate of MovieClip. A quick glance at the code identifies the culprit:

    MovieClip.prototype.update = function (deltaTime)
    ...
        lag += elapsed / 60 * 1000;

Simply changing `60 * 1000` to `core.TARGET_FPMS` fixes it easy for me.

Aside from the propesed fix, am I doing it right? Is TARGET_FPMS meant to be changed?

**Comment by whizzkid** [comment]
Doesn't myMovieClip.animationSpeed = 0.5;  fix your issues?

**Comment by daniele-pini** [comment]
That would just make the texture animate slower - I already do that by specifying the `time` parameter to textures passed to the MovieClip constructor.

What I want is a way to control the overall rendering framerate of the entire scene if possible, so that sprites move in little bursts together with texture updates.

I can always keep at 60 fps and update sprite positions manually to match the right frame rate, but I thought that changing the global TARGET_FPMS parameter could be an easy way to do it.

**Comment by sktt** [comment]
The 60fps is from the browsers requestAnimationFrame which is supposed to be synced with your monitors refresh rate. 

If you want to throttle throttle the whole rendering you could try something like
```js
var FPS = 25
var t = Date.now()
var scheduled = false
var animate = function() {
  scheduled = false
  var dt = Date.now() - t
  if (dt < 1000/FPS) {
    if(!scheduled) {
      scheduled = true
      // Schedule when to run animate. 
      // This should be better than to just requsetAnimationFrame(animate) 
      // otherwise you could have frame delayed by as much as ~16ms  
      setTimeout(animate, 1000/FPS - dt)
    }
    return
  }
  renderer.render(scene) 
  t += dt
  requestAnimationFrame(animate)
}
animate()
```

**Comment by daniele-pini** [comment]
Yep, you nailed it - tried it, works good.

I'm not sure about the setTimeout, though. It works as intended, but since MovieClip updates the texture internally at 16ms intervals anyway using requestAnimationFrame - independently from animate() - just using the requestAnimationFrame loop would couple the updates, I guess. I'll make some tests and keep the best result.

Thanks sktt, closing.

**Comment by zurcacielos** [comment]
Avoid unneeded computation and DO NOT DO Date.now() manually because requestAnimationFrame will pass the timestamp to the callback you want, and you can use that value, assign it to lastTimestamp in global or object scope, calculate the delta since the currentTimestamp-lastTimestamp and avoid rendering if it was "too fast".
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
