### ISSUE TITLE
Wrong sizing in cacheAsBitmap on Text 

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#2330]
Hi I'm trying to have a text label that is occasionally updated. I want to cache it, so I've been trying cacheAsBitmap. However I've found that if the label gets longer, it ends up cutting off the text. 

See here: 

https://plnkr.co/edit/0AN3fihXkoGOPgkvtmVs?p=preview

**Comment by JiDW** [comment]
Caching a text alone won't give you any performance boost, and you will use
more memory. Cacheasbitmap is only useful to cache multiple sprites into a
single texture.

**Comment by weepy** [comment]
yeah i looked at the text class and realised that it's already drawing on a canvas, so what I'm doing is pointless. I would be interested in knowing why it doesn't work properly though ?

**Comment by GoodBoyDigital** [comment]
should be fixed in v4 I think 👍
