### ISSUE TITLE
Removing child in mouseEvents cause errors in InteractionManager.processInteraction

### ISSUE THREAD

**Issue by Grimka** [pixijs/pixi.js#2333]
Hello there, I'm working with Pixi3 for the first time, I'm making a simple quiz game and I think I found an issue.

It's simple to reproduce, just try the following code and you will see : 

    //basic renderer creation
    var renderer = PIXI.autoDetectRenderer(800, 600);
    document.body.appendChild(renderer.view);

    // create the root of the scene graph
    var stage = new PIXI.Container();

    //create a window
    var w1 = createUi();
    w1.position.set(100,100);
    stage.addChild(w1);

    animate();

    function animate() {
        // render the stage
        renderer.render(stage);

        requestAnimationFrame(animate);
    }

    function createUi()
    {
        //the container of my ui
        var uiContainer = new PIXI.Container();
        uiContainer.position.set(100,100);

        //simplest window
        var basicWindow = new PIXI.Graphics();
        basicWindow.beginFill(0xffffff);
        basicWindow.drawRect(0,0,300,400);
        basicWindow.endFill();

        uiContainer.addChild(basicWindow);

        //simplest closeButton
        var closeButton = new PIXI.Graphics();
        
        closeButton.beginFill(0xff5555);
        closeButton.drawRect(0,0,100,50);
        closeButton.endFill();

        closeButton.position.set(200,0);
        closeButton.interactive = true;
        basicWindow.addChild(closeButton);

        //add a mouseup to it
        closeButton.on("mouseup",function()
        {
            //and here I just want to remove the uiContainer from the stage. Typical closeButton behavior imo.
            //But this cause an error in InteractionManager
            stage.removeChild(uiContainer);
        });

        return uiContainer;
    }

If you close the window an error happen in InteractionManager because the manager loops tough children list which is modified by my mouseup (the removeChild) 

I don't know if there is a better way to removeChild in a mouse event, maybe i'm doing wrong.. But I think the InteractionManager can have few lines of codes to detect the update of children array and avoid trying to acces an undefined array or an outOfRange index.

Sorry for my english, and thanks for reading this and or helping me :)

**Comment by Grimka** [comment]
I found a quick fix for this error in the function processInteractive, in the if statement at line 24112, i changed this : 
    if(displayObject.interactiveChildren)
    {       
        var children = displayObject.children;

        for (var i = children.length-1; i >= 0; i--)
        {
            // time to get recursive.. if this function will return if somthing is hit..
            if( this.processInteractive(point, children[i], func, hitTest, interactiveParent) )
            {
                hit = true;

                // we no longer need to hit test any more objects in this container as we we now know the parent has been hit
                interactiveParent = false;
                
                // If the child is interactive , that means that the object hit was actually interactive and not just the child of an interactive object. 
                // This means we no longer need to hit test anything else. We still need to run through all objects, but we don't need to perform any hit tests.
                if(children[i].interactive)
                {
                    hitTest = false;
                }
            }
        }
    }

into this : 

    if(displayObject.interactiveChildren)
    {       
        var children = displayObject.children;
        
        var oldLength = children.length;

        for (var i = children.length-1; i >= 0; i--)
        {
            // time to get recursive.. if this function will return if somthing is hit..
            if( this.processInteractive(point, children[i], func, hitTest, interactiveParent) )
            {
                hit = true;

                // we no longer need to hit test any more objects in this container as we we now know the parent has been hit
                interactiveParent = false;

                var newLength = children.length;

                if(newLength != oldLength)
                    continue;
                
                // If the child is interactive , that means that the object hit was actually interactive and not just the child of an interactive object. 
                // This means we no longer need to hit test anything else. We still need to run through all objects, but we don't need to perform any hit tests.
                if(children[i].interactive)
                {
                    hitTest = false;
                }
            }
        }
    }

**Comment by ivanpopelyshev** [comment]
The best solution is to delete it later, in setTimeout(function() { }, 0 );

**Comment by Grimka** [comment]
Yeah i though about this workaround, but i expected it was handled by pixijs like in other api (easeljs, flash/starling, etc..)

**Comment by GoodBoyDigital** [comment]
going to look into this one soon! thanks @Grimka !

**Comment by GoodBoyDigital** [comment]
all fixed in the dev branch now :+1:

**Comment by Grimka** [comment]
Thanks, you're awesome :)
