### ISSUE TITLE
Multitouch behaviour

### ISSUE THREAD

**Issue by stdiopt** [pixijs/pixi.js#2338]
Hi I was trying to create a pinch to scale feature, and come to realize that Event is being fired for every finger independently causing some excessive calls tho performance issues on mobile phones.

is there any plans in this matter? I've seen in code the InteractionManager  "//TODO POOL"

**Comment by fs-manabu-iwata** [comment]
Hi. This library works fine for me.
https://github.com/dekimasoon/pixi-simple-gesture

**Comment by stdiopt** [comment]
It seems that, that lib uses pixijs on('touchmove') which is the same called once per finger in a pinch its called twice, I ended up implementing gesture myself using default touchmove event from html5 and some pixijs internals to map touch to local, this way is called less frequent (pool) even if two fingers moved

**Comment by stdiopt** [comment]
Sample tests:

https://jsfiddle.net/jorg6zt9/1/
https://www.youtube.com/watch?v=cqemvQwzgls

**Comment by GoodBoyDigital** [comment]
Hi @stdiopt 

The touch events have an id that lets you differentiate between touches,

```event.data.identifier``` will be unique for each finger.

**Comment by stdiopt** [comment]
I don't think you get my point, the problem is not the identifier for each touch, the problem is the multiplexing of the event causing a possibility of performance issues, its explained on the links I sent. the amount of times the 'touchmove' event is called on pixijs is way higher than the default browser 'touchmove', 

example: 
Lets say i want to rotate/scale by pointing two fingers and render after transforms
on a html5 'touchmove' I get maximum 60, events with two fingers and per Event I can get the information of the two touches, so its calculating angles, distances, whatever at least 60 times,

in PIXI its being calculated that maximum of 60 times Per finger so its 120 events, basically doing twice the calculations of the same thing

**Comment by GoodBoyDigital** [comment]
I think I understand, I guess my question would be are you actually experiencing any performance issues with the events as they are?

**Comment by stdiopt** [comment]
Yes, I was getting performance problem on mobile (and was quite a diference), was trying to figure a way doing the touches with pixi, but ended up implementing the default html5 event
