### ISSUE TITLE
InteractionManager doesn't yet implement event bubbling

### ISSUE THREAD

**Issue by akbr** [pixijs/pixi.js#2342]
Pixi.js should bubble interaction events up the scene graph. (See [#625](https://github.com/pixijs/pixi.js/issues/625).)

Previously, bubbling was handled by EventTarget.js. However, after EventTarget.js was deprecated in favor of EventEmitter3, bubbling disappeared. (See [#914](https://github.com/pixijs/pixi.js/pull/914) and [#1532](https://github.com/pixijs/pixi.js/pull/1532#event-287332803).)

InteractionManager is likely the best place to handle bubbling (particularly `InteractionManager.prototype.dispatchEvent`, where it looks like implementation was contemplated, but never completed).

Do we want _both_ callbacks and `.emit`s to bubble?

If desired, happy to submit a patch.

**Comment by GoodBoyDigital** [comment]
Agreed, a patch would be super! :+1:

**Comment by endel** [comment]
Having global interaction events (https://github.com/pixijs/pixi.js/pull/2658) solves this for interactivity, but I'm still missing bubbling for custom `.emit` events. 

As a matter of code structure sometimes it's needed for a DisplayObject to emit an event and handle it on its parent. Maybe we could implement this as a plugin? Any ideas?

**Comment by ivanpopelyshev** [comment]
Look at how pixi-display changes it:  https://github.com/pixijs/pixi-display/blob/master/src/InteractionManagerMixin.js
You can do something similar to pass event not only to specific element but to its parents that are interactive as well.

**Comment by englercj** [comment]
Closing as the original request was implemented.
