### ISSUE TITLE
Custom ultra-light build?

### ISSUE THREAD

**Issue by albell** [pixijs/pixi.js#2343]
Hi Mat, Thanks for an awesome looking tool.

I have an app that currently uses Canvas 2D to literally just draw rectangles. Very simple, but many thousands of them, so performance matters. I would like to get the speed boost of switching over to WebGL, but I am sensing that I don't really have the time to learn it properly right now.

My problem is that the standard PIXI build would more than quadruple the size of my app. (I've kept things really lightweight.)

In the API notes I see that:

> If there are specific plugins you don't want, say "interaction" or "extras", you can exclude those:

    $> gulp build --exclude extras --exclude interaction

Can you advise specifically on what an absolutely minimal build would look like, and how to do it? Again, I really just need to draw 2D rectangles. I only need to support the very latest browser builds, so I don't need fallbacks. It would be great to see a list of all excludable modules, and what features authors give up by leaving each out.

**Comment by englercj** [comment]
You can pass the name of any folder you don't want to the `--exclude` flag:

https://github.com/pixijs/pixi.js/tree/master/src

**Comment by albell** [comment]
Sure, per my question, I'm clear on `--exclude`. I was wondering what the absolutely bare minimum but still functional build would be. I don't know which functionalities corresponds to which folders. And does that include subfolders, etc? Are there interdependencies between folders I need to be aware of? Can I remove things from `core` and have the build still work? etc.

**Comment by GoodBoyDigital** [comment]
Hello @albell !
tbh the bare minimum would be everything but the core. Im not too sure how small that would be tbh! Hopefully small enough for what you need? 

If performance matters, I would recommend that you create rectangles using a sprite and single white texture and scaling it accordingly to be the desired with hight. You could then set the tint property of the sprite to be the desired color. This method only works with rectangles but is SUPER fast as it would end up using pixi's sprite batching.

Hope that helps!

**Comment by GoodBoyDigital** [comment]
closing this one for now.. :+1:
