### ISSUE TITLE
PIXI.Texture.fromCanvas() only works once in WebGL mode

### ISSUE THREAD

**Issue by s3lf** [pixijs/pixi.js#2350]
hi!

as the title says, i think the Texture's fromCanvas() method does not work properly in WebGL. i need to use another canvases current content (which gets updated from time to time) to be rendered (and updated) to a Sprite. using sprite.texture=PIXI.Texture.fromCanvas(...) it works fine when rendering to a standard canvas. but in WebGL mode, it only renders the first time it is called. all other times it stays in the last state.

i suspected some kind of missing update, but that doesn't seem to change anything.

in the jsfiddle ([here](https://jsfiddle.net/paz87qyh/2/)) you can find a simplified reconstruction. it creates 3 canvases, the first will change colors every second, and the other two will use Texture.fromCanvas() to update a Sprite to the [Canvas 1]'s current content. that works well in [Canvas 2], which is set to the canvas rendering mode. but [Canvas 3], which is using the WebGL mode, just updates once, and since i do not change [Canvas 1]'s background color in the first cycle, it becomes red - and then just never changes to anything else.

i found another issue ([here](https://github.com/pixijs/pixi.js/issues/1980)) where you suggested using the Texture's update() method instead of the 2nd-cycle fromCanvas(), but that won't work in both canvas and WebGL for me.

i also tried updating a sprite repeatedly with changing image resources using fromImage(), this worked as expected, so i think it has something to do with fromCanvas().

i hope my explanation is understandable - thank you very much in advance!

s3lf

**Comment by englercj** [comment]
Calling `fromCanvas()` tries to create a brand new texture and base texture from the thing you have provided. You should only do this once to create the texture, then if you ever change the source canvas, call texture's `update()` method to reupload the texture.

Works fine in both WebGL and Canvas:

https://jsfiddle.net/paz87qyh/3/

**Comment by s3lf** [comment]
oh weird, so i must have made some mistake implementing the update instead of assigning a new texture... thank you for the clarification and the working fiddle!

**Comment by englercj** [comment]
No problem, let us know if you have trouble.

**Comment by iainajohnston** [comment]
wank!
