### ISSUE TITLE
TilingSprite problem when using TileScale + Anchor

### ISSUE THREAD

**Issue by maxdifraia** [pixijs/pixi.js#2353]
I've found a strange behaviour when, using a TilingSprite, I set an anchor different from 0,0 and a TileScale different from 1,1. 
What I get is an unwanted offset in position, the more I set the TileScale the bigger is this offset.

**Comment by maxdifraia** [comment]
The issue only appears when using the CanvasRenderer. Im using PIXI 3.0.9.

**Comment by GoodBoyDigital** [comment]
fixed in dev 👍
