### ISSUE TITLE
Reverse MovieClip

### ISSUE THREAD

**Issue by digitalml** [pixijs/pixi.js#2356]
I see that sometime ago the ability to play a movie clip in reverse was added but the functionality doesn't seem to be in the redistribution build. How can I get a movie clip to play reverse please?

**Comment by GoodBoyDigital** [comment]
hi there! pretty sure its:

```myMovieClip.animationSpeed = -1;```

**Comment by digitalml** [comment]
I tried that and then mc.play() after and nothing happens at all.

**Comment by digitalml** [comment]
Maybe I have the wrong version?  I am only using pixi.js - v3.0.9

**Comment by digitalml** [comment]
I must have been doing something wrong. This works as expected. Sorry! :)
