### ISSUE TITLE
Can I set a edge for a Container?

### ISSUE THREAD

**Issue by lebronchin** [pixijs/pixi.js#2359]
Hi there, I am doing an animation in a container, and sometimes the animation will go outside the edge that I set by the width and height of the container. It seems like setting the width and height does not really define the edge.  Is there any way that I can make the exceeded part disappear? I have tried using the mask already, but it just hide them, so when the page is resized, those hiding part will still be calculated while resizing.

**Comment by englercj** [comment]
Use a mask, Containers do not have dimensions.

**Comment by lebronchin** [comment]
Resizing the mask is totally what I am looking for, and it works great, thanks a lot.
