### ISSUE TITLE
removing an interactive object on a mouse click causes errors, how to properly handle?

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#2362]
What is the correct way of removing yourself on a button click ?

When you remove a button from a container in its own click event, InteractionManager throws an error. because it continues processing your containers children, which now have less children, and fails.

see this example,  open javascript console and click on the white circle.

https://jsfiddle.net/whizzkid74/2wv8531b/

I'm hoping theres a better way than to use a delayedCall using tweenmax or setTimeout..

**Comment by alebianco** [comment]
had the same issue
it has been raised in #2333 and already resolved in the dev branch

**Comment by englercj** [comment]
IN the meantime, just delay the delete:

```js
setTimeout(function () { myobject.destroy(); });
```

Or `removeChild`, or whatever you need.
