### ISSUE TITLE
[3.0.9] Interaction event triggered on multiple overlapping objects

### ISSUE THREAD

**Issue by alebianco** [pixijs/pixi.js#2364]
http://jsfiddle.net/alebianco/2brjt234/

The example shows how two overlapping objects (red square, yellow circle) could be triggered at the same time with a click. This happens when the two objects are added to sibling parents, if they are part of the same parent tree, everything seems to work as expected.

This is definitely a change of behaviour from v3.0.8

**Comment by alebianco** [comment]
bump, no feedback on this?

**Comment by mathieuanthoine** [comment]
it seems more a bug for me than a behavior change. What is the real interest of this behavior ? It completely breaks UI principles.

Here's my post about this issue: http://www.html5gamedevs.com/topic/21164-mouse-behavior-change-between-308-and-higher/

**Comment by GoodBoyDigital** [comment]
yes, seems like a bug! Pretty busy at the mo but will get to it soon :+1:

**Comment by mathieuanthoine** [comment]
Great ! Thank you Mat :)

**Comment by FNevesFMQ** [comment]
Can we expect to see this bug fixed in the next pixi iteration?

**Comment by alebianco** [comment]
I think it was fixed in 3.0.11

**Comment by FNevesFMQ** [comment]
But last release isn't 3.0.10?

**Comment by alebianco** [comment]
it's 3.0.11
https://github.com/pixijs/pixi.js/releases/tag/v3.0.11
but they forgot to bump the version in the code, so it says 3.0.10

**Comment by FNevesFMQ** [comment]
Oh ok!
Thanks

**Comment by staff0rd** [comment]
Looks solved per the tests in #3535
