### ISSUE TITLE
[Idea] Pixi C++ Bindings for Native App.

### ISSUE THREAD

**Issue by McFarts** [pixijs/pixi.js#2366]
Think of, let's say the SMFL library. Or the SDL library,

https://www.libsdl.org/

I was wondering, since electron/nw.js are popular.. it could be possible to bind pixi to native c++ calls that access openGL and not WebGL? If that makes sense. Wouldn't it theoretically boost performance immensely having direct access to the graphics card instead of relying on WebGL conversion.

Not sure, just brainstorming. I think it could be really popular though

**Comment by GoodBoyDigital** [comment]
that would be AWESOME :+1:

**Comment by McFarts** [comment]
Yeap. Taking JS to the next level alright! :) 

I just thought about this because if you go look at SDL or SMFL videos on youtube, they create the most basic games. I mean , you really need like a gazillion lines of code in SDL / SMFL just to have some sprite float around on the screen lol. I kept thinking to my self.. This shit can be done in Pixi / Phaser or whatever in like 1 line. Just imagine the direct access to the graphics card instead of having the WebGL overhead. My goodness gracious, mix that with Pixi's API and Javascript syntax.. We got something very high energy in the making!

**Comment by englercj** [comment]
There are libraries that expose OpenGL calls as WebGL already, CocoonJS and Ejecta come to mind. The browser also does it.

WebGL is OpenGL ES 2.0, it is direct access to the GPU, the bottleneck is definitely not "webgl overhead" its just JS itself.

**Comment by McFarts** [comment]
Is it because Javascript is run as an interpreter language and not compiled to bytecode? Which is where the performance issues start arises? Is there an article or link you have so I can read more about it? I always thought WebGL was being hindered because it's an abstraction ontop of openGL

**Comment by englercj** [comment]
> Is it because Javascript is run as an interpreter language and not compiled to bytecode?

FF used to compile to bytecode and run that on an interpreter, but I don't think they do anymore (not 100% sure). JS is compiled to machine language in V8 and runs on the metal.

http://thibaultlaurens.github.io/javascript/2013/04/29/how-the-v8-engine-works/

> I always read WebGL was being hindered because it's an abstraction ontop of openGL

The bottleneck is and always will be the fact that JS is slow. The fact that the WebGL API is abstracted using ANGLE and is "slower" to use than the OGL C API is irrelevant because JS is so slow that WebGL will never be the bottleneck. Note that the API is slower, but once shaders are compiled and are running, they are running on the GPU and there is no difference. It is only API calls that have an extra layer to flow through, so are "slower". But that speed decrease is negligible, because your JS couldn't run fast enough for you to notice anyway.

**Comment by McFarts** [comment]
Hmm. So with things like WebAssembly coming in the near future, do you think we could see an increase in performance from WebGL then?

I didn't know that V8 was compiled down to machine language. Even when it's compiled down it still cannot keep up with WebGL? That's pretty sad, but on the other hand, the game I'm working on I'm throwing in a ton, and I mean a ton of stuff inside Phaser / Pixi with huge tiled maps and it's not breaking a sweat.  The need for a language faster than JS so it won't be the bottleneck for WebGL is when you would use the SDL or SMFL or whatever graphics library.  But by that time, you would be working on an advanced game engine with a team I suppose. But then again, we're back at square one which I hate. Is the 'If you're going to build a large game, you need a large team and need to use C++!'. Which is just silly, look at the game called CrossCode.

That's why I am worried about Pixi and WebGL. Game dev's don't realize how powerful it is. The stigma of 'You must use C++ with a large team to be successful', is just not right. I think Pixi deserves something like Love2d.  Love2d uses LUA just as the front-end scripting language, but makes all opengl calls using C++ so LUA (or if we used Javascript here), would never be the bottleneck. I think something like that should be done for Pixi. Would be a performance boost I'm sure?

**Comment by englercj** [comment]
> Hmm. So with things like WebAssembly coming in the near future, do you think we could see an increase in performance from WebGL then?

Web assemble is the exact same thing as asm.js; just a different delivery format. People have been using it for some time with emscripten.

>  but makes all opengl calls using C++ binding so LUA (or if we used Javascript here), would never be the bottleneck.

We do have C++ bindings to OpenGL, the API is called WebGL. That "binding" layer you describe *is* WebGL.

OpenGL -> ANGLE -> JS == OpenGL -> Lua Bindings -> Lua

Its the same concept, just different names. Most functions that are "built-in" to the browser are just calling C++ code via V8. Its really not as big of overhead as you think.

**Comment by McFarts** [comment]
I see now. I always thought so differently about WebGL really, now I have a way better understanding of it. So I guess it boils down to is that very small overhead. So it's basically safe to say, the performance increase wouldn't be... worth it I'm guessing? That's fair now since I have a better understanding.  

Aww, so it also comes down to the language's speed as well.
OpenGL -> Angle -> JS VS
OpenGL -> Lua Bindings -> Lua

So then it all boils down to LUA JIT vs V8's performance, which is negligible?  (In terms of WebGL testings) 

Man, out of all the things available on the JS side.. Node, Phaser, DOM, Pixi, etc... I could careless now about that ** "small overhead" **, haha.

**Comment by GoodBoyDigital** [comment]
all interesting stuff that! Gonna close this now as it seems to have run its course. Thanks for the insight @englercj :+1:

**Comment by McFarts** [comment]
I agree I think Englercj should have his own blog, I'd subscribe to it.

**Comment by englercj** [comment]
@McFarts https://englercj.github.io/

Just don't know what to post about most of the time :P
