### ISSUE TITLE
Unable to translate mouse click to local coordinates with pivot.

### ISSUE THREAD

**Issue by iargue** [pixijs/pixi.js#2367]
We are attempting to convert our project from EaselJs to PixiJS. However, I have ran into a major issue when attempting to port.

We have Three containers.

stage = container that holds the player view, children are gameStage and playerBar
gameStage = container that holds the world and all of its objects
playerBar = container that holds the UI for the player to interact with

When the player moves his mouse to the edge of the screen, it pivots the gameStage canvas which simulates scrolling across the game word. This is working.

However, when the player clicks on the stage, the hero should move to there they clicked. The issue that I am having is converting the click object to the local gamestage object. In EaselJS GlobalToLocal worked perfectly for this. However, in PixiJS using toLocal on the gamestage object does not provide accurate coordinates for movement.

Is there a specific method of handing a global mouse click to a containers local position on the render?

**Comment by GoodBoyDigital** [comment]
Hi there! if you could provide a jsfiddle with recreating the issue that would be ace. thanks!

**Comment by iargue** [comment]
When creating the Fiddle, I ran into an issue before even applying the pivot.

http://jsfiddle.net/82dpsL4w/

When clicking somewhere, the circle should be moved to where the click event is at. However, the result is the circle moving far from the click event. I did not feel the need to apply pivoting as this is the base of the issue, and resolving this should resolve the issue at hand.

**Comment by GoodBoyDigital** [comment]
Hello! Its best to use pixi for interactions as it takes care of all transaltions for you:

heres the above fiddle tweaked to work correctly:
http://jsfiddle.net/smn017hd/

Hope this helps! 👍
