### ISSUE TITLE
Pixi 3 loader won't load a json file

### ISSUE THREAD

**Issue by zhaodx** [pixijs/pixi.js#2368]
Uncaught TypeError: Cannot read property 'image' of undefined

**Comment by zhaodx** [comment]
var loader = new PIXI.loaders.Loader('assets/NPC_RoseyParker', 10);

**Comment by zhaodx** [comment]
loader.add('NPC_RoseyParker', 'NPC_RoseyParker.json', {xhrType:'json', loadType:1});
//or
loader.add('NPC_RoseyParker', 'NPC_RoseyParker.json');
loader.load(...);

**Comment by englercj** [comment]
Can you show a running example please?

**Comment by whizzkid** [comment]
Also, make sure your webserver has a mimetype configured for .json files.  

.json    text/json

otherwise your server might simply not be giving you the json file.
