### ISSUE TITLE
Separate touch and mouse event configuration

### ISSUE THREAD

**Issue by sergebat** [pixijs/pixi.js#2369]
Interaction manager currently always listens for touch and mouse events at once.

It would be great if we can configure, if we want all (default), only touch, only mouse (and if we need mouse over, configurable separately).  

For example, we need to only listen for taps on popular Samsung galaxy android browsers, because otherwise it duplicates taps with +-100 ms delay (whether you make "preventDefault" call or not). (this browser bug is discussed in details here: https://www.sencha.com/forum/showthread.php?230646-tap-event-fires-two-events-on-android).

Only way to listen for touch events right now is to unsubscribe (which requires knowledge of PIXI private methods, which is "hacky" and likely to break in future versios):
```
        var badAndroidDevice = navigator.userAgent.indexOf("Android") > -1 && !(navigator.userAgent.indexOf("Chrome") > -1);
        if (badAndroidDevice) {
            var interactionManager = renderer.plugins.interaction;
            window.document.removeEventListener('mousemove', interactionManager.onMouseMove, true);
            interactionManager.interactionDOMElement.removeEventListener('mousedown', interactionManager.onMouseDown, true);
            interactionManager.interactionDOMElement.removeEventListener('mouseout',  interactionManager.onMouseOut, true);
        }
```

**Comment by sergebat** [comment]
Also, it might be good idea to consider hack to prevent duplicate tap issue on android browser inside PIXI (as it is subtle and very destructive bug on relatively popular device).

**Comment by themoonrat** [comment]
@englercj - Pointer event PR gains the functionality required, this can be closed
@sergebat When the latest dev pixi becomes live, you can just listen to the pointer events ('pointerup', 'pointerdown' etc etc.) instead of mouse and touch events. Even if the browser doesn't support pointer events, mouse or touch events will get converted to one. This also solves the Samsung browser 'two events' issue.

**Comment by sergebat** [comment]
>  This also solves the Samsung browser 'two events' issue.

This particular bug is becoming less relevant over time, as it only occurs on native android browser pre Android 5, I think.

However, can you please explain, how above convergence to single event type can help with the bug? 

Are you not listening to touch events only (if they are available), but not mouse events? If yes, this might be problematic for devices that have both touch and mouse input (touch screen notebooks). This is rare usecase, but still something that generic engine should account for, imo.  

If you are still listening to both events, then how can you prevent second totally unrelated tap event from triggering? Are you applying threshold and ignore events?

**Comment by themoonrat** [comment]
For mobile browsers, we favour just listening to the touch event. This stops the old Samsung browser double events. For desktop browsers, we favour just listening to the mouse event; I found that all browser emitted a mouse event even if a touch screen was used. Thus touch screen notebooks using Chrome will work fine. Edge on Windows 10 natively supports the pointer event, so is safe to listen to the real event.

If there are any side issues around this, you can still just listen to mouse / touch events in pixi as previously.

**Comment by sergebat** [comment]
> For desktop browsers, we favour just listening to the mouse event; I found that all browser emitted a mouse event even if a touch screen was used. 

Is this achieved with user agent sniffing? Or you are using something else to differentiate mobile vs desktop?

> If there are any side issues around this, you can still just listen to mouse / touch events in pixi as previously.

Ah - ok. Is there are new methods to manually add mouse/touch DOM listeners? In previous PIXI there were no public methods for that, as example above shows.

**Comment by themoonrat** [comment]
We use the https://github.com/kaimallea/isMobile lib to detect if it's a mobile device.

There is no way to add / remove listeners when interacting on a PIXI object. However, there recently has been the addition to add top level listeners as an addition to listeners on PIXI objects.
`renderer.plugins.interaction.on( 'pointerdown', () => { console.log('Hello World') );
`

**Comment by sergebat** [comment]
> However, there recently has been the addition to add top level listeners as an addition to listeners on PIXI objects.

But - if I understood new approach correctly - touch DOM events will just not be handled on desktop browser with touch screen. Thus, for example, touch event identifier will be lost (as - imo - mouse events do not have "identifier" field?), and you will not be able to handle multi-fingers gestures at all in new version.

Is there a chance we can explicitly choose only-mouse/only-touch/both/auto to be mapped to new pointer events? (with auto being default new approach you are suggesting, and "both" will call preventDefault on touch)

**Comment by themoonrat** [comment]
Ah I get what you mean. The original events are untouched. So, if you had your old galaxy browser, you _could_ listen to mouse, touch and pointer and get events for all 3 of them if you wished. If we are normalising a mouse event... that original mouse event still goes through and can be listened to; we just emit an additional pointer event with the event data in the format expected for that API.

If you wish to disable normalisation on a certain type of event, you can do
renderer.plugins.interaction.normalizingTouchEvents = false;
and/or
renderer.plugins.interaction.normalizingMouseEvents= false;

(may change the name of these slightly before the next release goes live. Wasn't intending on them being used to control the behaviour, but I can see how that could be desired)

**Comment by sergebat** [comment]
Great - thanks for clarifications and points! 

From the look of the above config parameters it indeed looks like they should handle use case I explained. But I'll indeed make it a point to double check the code when it is live!
