### ISSUE TITLE
Mask didn't support 2 renderer

### ISSUE THREAD

**Issue by kongyim** [pixijs/pixi.js#2371]
Hi, I want to use the code below to render a scene in two different render in different transformation.
But I got the following error from PIXI
`pixi.js:16307 Uncaught TypeError: Cannot read property 'data' of undefined`

```
var renderer1 = PIXI.autoDetectRenderer(800, 600)
var renderer2 = PIXI.autoDetectRenderer(800, 600)

document.body.appendChild(renderer1.view)
document.body.appendChild(renderer2.view)

stage = new PIXI.Container()
image = PIXI.Sprite.fromImage('./Winter-Tiger-Wild-Cat-Images.jpg')

var myMask = new PIXI.Graphics();
myMask.beginFill();
myMask.drawCircle(800, 350, 300);
myMask.endFill();

stage.addChild(myMask)
image.mask = myMask

stage.addChild(image)

animate();

function animate()
{
  requestAnimationFrame(animate)

  stage.scale.x = stage.scale.y = 1
  renderer1.render(stage)

  stage.scale.x = stage.scale.y = 0.5
  renderer2.render(stage)
}
```

I would like to ask if I doing something wrong? if I comment either of the rendering code (renderer1.render(stage) or renderer2.render(stage)), it will work. Is it possible to render both at the same time?

**Comment by kongyim** [comment]
Hi

I don't know if it is a proper fix, if I share the maskManager, it works. 
`renderer2.maskManager = renderer1.maskManager`

the complete code as follow
```
var renderer1 = PIXI.autoDetectRenderer(800, 600)
var renderer2 = PIXI.autoDetectRenderer(800, 600)

renderer2.maskManager = renderer1.maskManager

document.body.appendChild(renderer1.view)
document.body.appendChild(renderer2.view)

stage = new PIXI.Container()
image = PIXI.Sprite.fromImage('./Winter-Tiger-Wild-Cat-Images.jpg')

var myMask = new PIXI.Graphics();
myMask.beginFill();
myMask.drawCircle(800, 350, 300);
myMask.endFill();

stage.addChild(myMask)
image.mask = myMask

stage.addChild(image)

animate();

function animate()
{
  requestAnimationFrame(animate)

  stage.scale.x = stage.scale.y = 1
  renderer1.render(stage)

  stage.scale.x = stage.scale.y = 0.5
  renderer2.render(stage)
}
```

**Comment by kongyim** [comment]
I tried to share the maskManager between the renderer
`renderer2.maskManager = renderer1.maskManager`

it didn't throw exception, but the second renderer mask effect is gone ~~~~~~

**Comment by kongyim** [comment]
Hi 

I tried to turn on noWebGL flag in renderer and it works now

```
var renderer1 = PIXI.autoDetectRenderer(800, 600, {}, true)
var renderer2 = PIXI.autoDetectRenderer(800, 600, {}, true)
```

but I think it is not good as the performance will be a huge different.
Anyway, I can continue my development with noWebGL=true, but would it be possible to make it support WebGL.

Thank you very much.

**Comment by GoodBoyDigital** [comment]
fixe din dev branch 👍
