### ISSUE TITLE
Memory leak in PIXI v3

### ISSUE THREAD

**Issue by chronszcz** [pixijs/pixi.js#2375]
It seems that the InteractionManager plugin leaks memory as soon as a new renderer is being created.

Is there a clean way to disable the InteractionManager?

**Comment by GoodBoyDigital** [comment]
Hi there! A little more info on the leak would be ace, do you have an example we could test? Cheers!

**Comment by chronszcz** [comment]
This code tested on nwjs v0.12.3-win-32 shows a [steady increase of memory usage](http://prntscr.com/aaz2ji)

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <script src="pixi_3.js"></script>

        <script>
            var renderer = new PIXI.WebGLRenderer(800, 600);
            document.body.appendChild(renderer.view);
        </script>
    </body>
</html>
````

Deleting the Interaction Manager seems to fix that problem.


```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <script src="pixi_3.js"></script>

        <script>
            delete PIXI.WebGLRenderer.__plugins['interaction'];
            
            var renderer = new PIXI.WebGLRenderer(800, 600);
            document.body.appendChild(renderer.view);
        </script>
    </body>
</html>
```

**Comment by GoodBoyDigital** [comment]
Hi, had a look into this today and I can't seem to see any leaks in interaction manager - is this not a natural gc thing?
does this actually slow down and affect your app?
