### ISSUE TITLE
Asking for advices (or feature req.) : hybrid cacheAsBitmap 

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#2378]
Hello !

So we have this game, half developed with PIXI that runs on mobile. For best performances, we make a heavy use of cacheAsBitmap feature and that's great. However, now that we are at the later stage of the production (launch is for march), we'd like to enhance some UI pages with some visual effects.

Problem is, these pages are cached as a bitmap and therefore, any effects inside these containers would be static too.

http://www.serenity-ff.com/images/screenshots/screenshot1457083750.jpg

Let's take this UI for example. This is a very static interface and everything, excluding header and footer, is inside a cached container.

Now we'd like to add a small animation (like a glowing white effect) on one of the weapon displayed in the boxes. That's where I could use some help. The idea is to keep the cacheAsBitmap but redraw some elements on top of it.

Is anyone familiar enough with cacheAsBitmap internal code have a good idea on how to achieve this without rewriting our UI ? This can (and probably will) modify PIXI code.

I was thinking about flaging some DisplayObject that needs to be drawn on top of the cacheAsBitmap and then modify how cached object are rendered to call for a second render on top of the cached object that would only render the flaged DisplayObject. I have no idea if this is possible as I am not familiar enough with the rendering process of a displayobject in PIXI. (I do understand how cacheAsBitmap works)

Thanks a lot for your time !

**Comment by englercj** [comment]
You can use a render texture for the static parts of the UI, then rendering the dynamic parts on top of the sprite of that render texture.

**Comment by JiDW** [comment]
Thanks for your help Chad!

Yes that's the idea, but I'm wondering what would be the fatest-but-not-too-horrible way to do it for an already existing code.

cacheAsBitmap is already like a RenderTexture, right ?

I have an idea, but I don't know PIXI render loop enough to know if it is possible

1- Set a custom property (like "dynamicObject" or smth) on my DisplayObjects that I want to see drawn on top of the RenderTexture.
2- Modify cacheAsBitmap setter to set "visible" to false for all children of the DisplayObject that have dynamicObject to true, then generate the RenderTexture, and then inverse every "visible" property in order to get the cached sprites to be visible=false, and the dynamic sprites to be visible=true as soon as the cached texture is generated.
3- Set cacheAsBitmap to true
4- Modify DisplayObject._renderCachedWebGL to call a second rendering, this time with the DisplayObject._originalRenderWebGL in order to draw the dynamic objects, because they are the only one still visible

This way, I have a DisplayObject rendered twice, once with static elements, and once with dynamic elements.

If no one knows more about this, I'll give it a try, but before wasting my time I wanted to see if someone had a good idea or knew if my idea is possible.

Regards.

**Comment by ivanpopelyshev** [comment]
Nice, that will be part of my Camera for v4 soon :)

**Comment by GoodBoyDigital** [comment]
closing for now as this thread seems to have run it course.
