### ISSUE TITLE
Container.generateTexture does not work correctly with alpha masks. v3.0.10

### ISSUE THREAD

**Issue by JSideris** [pixijs/pixi.js#2379]
I am working on a tile game using pixi.js, and I've come across a peculiar problem. First, a bit of info about my setup:

# My Setup
It's a dynamic outdoor tile game. Each tile texture is a 128px-sided square, but the tiles overlap by 28px on the top and on the left so that the textures can fade into each other. Like so:

![tiledemo](https://cloud.githubusercontent.com/assets/8083793/13552143/702d3468-e323-11e5-9af9-6a1d318118f7.png)

This is an easy way to make the tiles look like they're transitioning into each other without me having to create numerous transition textures.

I've created an alpha mask texture to draw on top of each tile sprite:

![mask](https://cloud.githubusercontent.com/assets/8083793/13552154/08149820-e324-11e5-85b7-9bba0acae93e.png)

This works when each tile sprite has a mask on it. Here is what it looks like:

![fadedemocomparison](https://cloud.githubusercontent.com/assets/8083793/13552193/3101898a-e326-11e5-9be2-72757633b7cb.png)

Here is the code:

```
//This code is called when the program first starts or when the view resizes.
TileView.prototype.readdAllTiles = function () {
	this.bg.removeChildren();
	for (var x = 0; x < this.fullViewWidth; x++) {
	    for (var y = 0; y < this.fullViewHeight; y++) {
	        var tile = new PIXI.Sprite(); //Texture is set elsewhere.
			tile.position.x = x * this.tileSize;
			tile.position.y = y * this.tileSize;
			var m = PIXI.Sprite.fromImage("../Images/textures/mask.png");
			m.x = 0;
			m.y = 0;
			tile.mask = m;
			tile.addChild(m);
			this.bg.addChildAt(tile, x * this.fullViewHeight + y);
		}
	}
}
```

However, even though the code is not called often, having this many alpha masks on the screen **slows the game right down**. 

So, I decided to use Container.generateTexture to merge the alpha mask with textures from my texture atlas in advance. By doing so, an expensive computation could (presumably) be avoided. The code for generating these textures is as follows:

```
    function createBlurredTextureFromFrame(frameId) {
        var tempstage = new PIXI.Container();
        var s = PIXI.Sprite.fromFrame(frameId);
        var m = PIXI.Sprite.fromImage("../Images/textures/mask.png");
        s.width = 128;
        s.height = 128;
        s.x = 0;
        s.y = 0;
        m.width = 128;
        m.height = 128;
        m.x = 0;
        m.y = 0;
        s.mask = m;
        tempstage.width = 128;
        tempstage.height = 128;
        tempstage.addChild(s);
        tempstage.addChild(m);
        return tempstage.generateTexture(renderer, 1, PIXI.SCALE_MODES.DEFAULT);
    }
```

The key is putting the desired texture and the mask into the tempstage container and then calling generateTexture. After that, I assign the appropriate generated texture to each of the tile sprites. However, I'm getting something very bizarre.

# The Issue
![brokenalphamasktexture](https://cloud.githubusercontent.com/assets/8083793/13552214/8a1b4d34-e327-11e5-9cc3-5c50d324e487.png)

This one runs fast, which I'm happy about, but it's clearly broken. It's the exact same mask texture as before. For some reason, the tiles now appear to be slightly transparent. If I comment out the s.mask = m part (and tempstage.addChild(m)), the program goes back to normal. I tried switching the mask to something bizarre just to see what would happen:

![mask6](https://cloud.githubusercontent.com/assets/8083793/13552238/4f9a60e0-e328-11e5-95af-323a932f3ef6.png)

However, I get the exact same result as the above image (you couldn't tell a circle is being used to mask). If I set the mask's x and y to 64, you can definitely see that there is a mask that's being used in some way, but just not correctly:

![64spacingbrokendemo](https://cloud.githubusercontent.com/assets/8083793/13552261/998d11e2-e329-11e5-921b-ce7cfb729b05.png)

I attempted to reproduce the issue using [one of the pixi js v3 examples](http://www.gamebzh.net/htmlgame/pixi-e/index.html?s=demos&f=alpha-mask.js&title=Alpha%20Mask) but I couldn't get anything generated by Container.generateTexture to display at all, with or without masks. I spent quite a bit of time on it, but perhaps there's something obvious to be tweaked that I'm missing. A new set of eyes are welcome. Here is what I changed the code to:

```
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

var stage = new PIXI.Container();
stage.width = 100;
stage.height = 100;
var tempstage = new PIXI.Container();
tempstage.width = 100;
tempstage.height = 100;

stage.interactive = true;

var cells = PIXI.Sprite.fromImage('_assets/cells.png');

cells.x = 0;
cells.y = 0;
cells.width = 100;
cells.height = 100;

var mask = PIXI.Sprite.fromImage('_assets/flowerTop.png');
mask.x = 0;
mask.y = 0;
mask.width = 100;
mask.height = 100;

//cells.mask = mask;
//tempstage.addChild(mask);
tempstage.addChild(cells);

var tempTexture = tempstage.generateTexture(renderer);
var alphaTextureSprite = new PIXI.Sprite();
alphaTextureSprite.width = 100;
alphaTextureSprite.height = 100;
alphaTextureSprite.x = 0;
alphaTextureSprite.y = 0;
alphaTextureSprite.texture = tempTexture;
stage.addChild(alphaTextureSprite);

requestAnimationFrame(animate);

function animate() {
    renderer.render(stage);
    requestAnimationFrame(animate);
}
```

**Comment by GoodBoyDigital** [comment]
thanks for this @JSideris ! I will take a look soon.

**Comment by GoodBoyDigital** [comment]
Think this is cool in v4 👍
