### ISSUE TITLE
Trim  for PNGs in WebGL Renderer

### ISSUE THREAD

**Issue by FabianElsmer** [pixijs/pixi.js#2384]
When using a trimmed PNG as a texture and giving it the trim:
```
{
          x:padding_left
          y:padding_top,
          width:original_texture_width,
          height:original_texture_height
}
```
Everything works beautifully in the CanvasRenderer, but in WebGL the last pixel on the right and bottom get stretched to the size of the original texture:

![screenshot from 2016-03-09 21 29 09](https://cloud.githubusercontent.com/assets/9722121/13649518/748d8382-e63e-11e5-95aa-9f62085bf360.png)

![screen2](https://cloud.githubusercontent.com/assets/9722121/13649729/51acb10c-e63f-11e5-9b8c-ed8a6a33a637.png)

**Comment by ivanpopelyshev** [comment]
Solved in http://www.html5gamedevs.com/topic/21048-trim-and-crop-in-webgl-and-compressed-textures/ , need to setup "frame" first and "trim" second.

**Comment by FabianElsmer** [comment]
I really wouldn't call this solved, imho its still a hack that makes the Sprites bounds wrong (to the size of the cropped area, instead of the cropped are + trim), manually setting the texture.width/texture.height won't solve this either, since our Sprite.getBounds method uses the texture._frame.width. not the texture.width

**Comment by ivanpopelyshev** [comment]
There's a big problem with getBounds() : it is used for filters and filters dont need trimmed area. It needs to be separated into two methods, one for interaction and one for filters.

**Comment by englercj** [comment]
@ivanpopelyshev Has this been fixed in v4? I feel like it was...

**Comment by ivanpopelyshev** [comment]
It was fixed.
