### ISSUE TITLE
Alpha not honored for DisplayObject when rendering to RenterTexture

### ISSUE THREAD

**Issue by MichaelZawadzki** [pixijs/pixi.js#2386]
Hello,

Using the latest version 3.0.10 of PIXI.

When I have alpha set on sprites I'm rendering to a renderTexture they are not honored and they render with alpha 1 onto the texture. Poking around the sources and the [commit history of renderTexture](https://github.com/pixijs/pixi.js/commits/v3.0.10/src/core/textures/RenderTexture.js) it appears this was originally fixed in this [commit](https://github.com/pixijs/pixi.js/commit/80f77bfd2933b7ee3ee75eecda76b7b4fa2242de). However, it seems when trying to fix some other edge-case later (cached cases I think), the original fix was reverted. This commit is [here](https://github.com/pixijs/pixi.js/commit/0d8d8f39b95c88dfc7977ce3cf7f86ccb1fa07f7#diff-16aaec1b8d1f0b9213f2b6655d4a276e).

In my case taking the original fix (setting the worldAlpha using the displayObject's alpha) works. If the intention of that 2nd commit was to fix a caching case (where the displayObject has a cache where the alpha would already by applied within it), then maybe the proper way to go would be to query cacheAsBitmap and take the appropriate step: set worldAlpha to 1 if cache exists, otherwise use the displayObject's alpha.

For now on our project we are switching to the non-minified version and we'll have a local fix. It would be great if someone who knows this code better could confirm/apply the fix to the codebase.

For reproduction, I modified an [existing sample](http://pixijs.github.io/examples/index.html?s=basics&f=render-texture.js&title=Render%20Texture&v=dev) to reproduce this issue. Attached is the output code from that [render-texture.txt](https://github.com/pixijs/pixi.js/files/166233/render-texture.txt). Note I had to render the sprite to the renderTexture, if its contained within a container then it works. Is it required to have sprites be wrapped in containers to render them? Doesn't seem that way... the renderTexture render call takes a DisplayObject which a Sprite certainly seems to be.

**Comment by ivanpopelyshev** [comment]
Thank you, we know about issue, it will be fixed in v4 :)

**Comment by MichaelZawadzki** [comment]
Thanks for the quick reply. 

Is there a good place to checkout any such "known issues" with the current version? This would be useful for development.

**Comment by ivanpopelyshev** [comment]
I dont know exactly, I just know that I stumbled across that a month or two ago :) May be using two containers, outer with alpha and inner with renderTexture stuff will work too. 

I can look at the issue later :)

**Comment by MichaelZawadzki** [comment]
Pretty sure checking that checking the cacheAsBitmap settings would let you in this case pick the proper behavior. Not sure if there are more than these 2 cases to worry about. 

Either way, I have my local fix for now + there is the container work-around. Focusing on some other fun issues atm. 

Just quickly again: is there some list of known issues for PIXI somewhere? And related... anyone know of a good "known issues" page for WebGL itself?

Thanks again for the fast replies!

**Comment by GoodBoyDigital** [comment]
fixed in dev branch 👍
