### ISSUE TITLE
Color inconsistency in Chrome for windows

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#2387]
Although not directly PIXI related, (canvas.getImageData also has this problem) I thought I'd ask you guys.

I'm using a PNG image as a pixelmap, and I need to get the exact RGB values per pixel. I've discovered today that, in Chrome on windows, this is not always the case.
check out : https://jsfiddle.net/whizzkid74/8p2s3jz8/4/

its an image with black and red pixels, and it will show the red value of this pixel on screen.
in the original image, that's 255
in IE, I get 255 as a result
in Chrome on windows, I get 254 as a result.  on my colleages computer we even get 216 as a result.
Chrome on mac returns 255.

I think it has something to do with the rendering of the canvas element before rendering it to texture.

Does anyone have any idea how to fix this?

**Comment by JSideris** [comment]
I just tried this on Chrome v48 and v49 on Windows and I get 255 for both.

**Comment by ivanpopelyshev** [comment]
Its all about premultiplied alpha. If you have A=0.5 (128) , R=200 you can see R=199,200 or 201. All because browser stores A*R in memory.

**Comment by whizzkid** [comment]
@JSideris Thanks for trying. my home pc (windows 10) also reports 255 and 255..
2 pc's at work (win7) report different values (even from eachothet)

@ivanpopelyshev But I have no alpha.. 
the image only contains 0x000000 and 0xff0000

and even if it did, shouldn't it report the same color on all machines/browsers?

**Comment by ivanpopelyshev** [comment]
no. it seems that it can report 254 or 255 depending on pre-multiplied algorithm even if alpha is 255 :)

**Comment by whizzkid** [comment]
Well that sucks. so different versions of browser can produce different results?  that means no using png's for pixelmaps (well, only for course values, no precision)

the 216 value (which should've been 255) is a BIG difference though...

Would 100% quality jpegs solve this (since they should never have alpha) or maybe even gifs?
(I only have access to 1 pc that gives the correct result, cant test the other 2 at work at the moment)

**Comment by ivanpopelyshev** [comment]
well not exactly, you can use https://github.com/devongovett/png.js/ :+1:

**Comment by whizzkid** [comment]
Thanks I'll give that a try.

I've also found this:
https://html.spec.whatwg.org/multipage/scripting.html#the-canvas-element  

which states: "Due to the lossy nature of converting to and from premultiplied alpha colour values, pixels that have just been set using putImageData() might be returned to an equivalent getImageData() as different values."


yay.

**Comment by ivanpopelyshev** [comment]
just load the file as a binary buffer and pass to png.js
