### ISSUE TITLE
Video fill scale

### ISSUE THREAD

**Issue by lbineau** [pixijs/pixi.js#2389]
Hi,

I try to make the **video fill the background** of the canvas (same effect as here http://dfcb.github.io/BigVideo.js/). 
If I addChild the video to the **stage** the resize of the video it is **working as expected**. 

http://codepen.io/lbineau/pen/eZzvPW (OK)
stage
|__ videoSprite

But if I try to add the video to an intermediate container (**container or sprite or displayobjectcontainer**), it is **not working**. 

http://codepen.io/lbineau/pen/KzMWmp (KO)
stage
|__ container
      |__ videoSprite

The problem seem to be that the container updates its own scale property instead of just its dimensions.
How can I prevent this behaviour ?

Thank you.

**Comment by englercj** [comment]
Don't set the container width/height at all:

http://codepen.io/anon/pen/LNZyRq

In the first one you scaled the sprite (by setting width/height), in the second one you scaled the container and the sprite. Just scale the sprite.

**Comment by lbineau** [comment]
@englercj thanks for you reply. I continue with your idea and add a mask to be able to customize the area size :
http://codepen.io/lbineau/pen/bpexaX?editors=0010
