### ISSUE TITLE
Container.cacheAsBitmap behaving funny on retina

### ISSUE THREAD

**Issue by nuthinking** [pixijs/pixi.js#2393]
almost as if the snap shot wasn't retina. I am developing for an Android TV, sorry if the pictures below are not ideal (without and with cacheAsBitmap).

![cacheasbitmap](https://cloud.githubusercontent.com/assets/163635/13728285/56abee2a-e90a-11e5-8a2d-9d6f366ff4e8.png)

FYI Android TV is considered Retina (small window size in pixels but double density). I used the _rendererOptions.resolution = window.devicePixelRatio_ and _canvas style size = window size_ option to support it.

**Comment by nuthinking** [comment]
On the laptop, with technically the same resolution looks way more readable.

![laptop](https://cloud.githubusercontent.com/assets/163635/13728381/17edf116-e90e-11e5-9f81-a1de7ee72349.png)

**Comment by nuthinking** [comment]
Here Canvas 2D (left) VS Pixi (right).

![img_0659_cropped](https://cloud.githubusercontent.com/assets/163635/13763595/42e3a910-ea3f-11e5-92f2-1c5d81772538.jpg)

I guess this is the price of using 3d rendering. On the TV the difference is much more noticeable.

**Comment by GoodBoyDigital** [comment]
hey there! if you use the pixi canvas renderer, does the text show up sharp?

**Comment by nuthinking** [comment]
Hi @GoodBoyDigital, I tried new PIXI.CanvasRenderer and as a matter of fact the difference in rendering quality is still there!

Here the pen: http://codepen.io/anon/pen/NNbdJY

It should be enough to check it on an iphone.

Thanks!

**Comment by nuthinking** [comment]
@GoodBoyDigital thanks to @ivanpopelyshev I discovered the "resolution" parameter in PIXI.Text. The documentation doesn't seem updated:  https://pixijs.github.io/docs/PIXI.Text.html

This solved the quality of text in general. Still cacheAsBitmap makes the text worse.

**Comment by GoodBoyDigital** [comment]
oh, one more to try:

```PIXI.RESOLUTION = 2```

as pix may be using a lower resolution texture to cache the text. - side note here but there should not be a situation where you would need to use cacheAsBitmap on text as it essentially a bitmap anyway. 

hope that does the trick!

**Comment by nuthinking** [comment]
@GoodBoyDigital updated the pen, seems to work. Thanks! ;) Anyway, I was thinking of using cacheAsBitmap for a composition of more elements.
