### ISSUE TITLE
interactive property behave differently while overlap in 3.0.10

### ISSUE THREAD

**Issue by lebronchin** [pixijs/pixi.js#2399]
Hi there
Recently I've updated my pixi to 3.0.10, and I found out the overlay I made before, which is supposed to cover and avoid the buttons behind it to be clicked, is not working anymore. The way I did it is setting the overlay's "interactive" property to true. 

How can I fix it with 3.0.10, or can you suggest me a better way to do it? 

thanks

**Comment by whizzkid** [comment]
That works fine for me.

is the hitArea correct?
try : 

```
myOverlay.on("click",()=>{console.log("overlay click")});
myOverlay.interactive=true;
``` 

Does it register the click (message in the console)?  If not, the hitArea is probably incorrect or missing.

Alternatively you could also set interactiveChildren to false on the container containing the buttons you want to disable.

**Comment by lebronchin** [comment]
I made a simple experiment, I got two sprites they are all fullscreen, so should not have hitArea issue.
    myBg.on("click",()=>{console.log("Bg click")});
    myBg.interactive=true;
    myOverlay.on("click",()=>{console.log("overlay click")});
    myOverlay.interactive=true;
It turns out in old version, when I clicked on it only print out "overlay click", but in 3.0.10, both are printed.
Is that the desired behavior for 3.0.10?

**Comment by lebronchin** [comment]
@whizzkid 
I just found out this issue will not happen if they are under the same parent. otherwise both onclick events will be fired.

**Comment by GoodBoyDigital** [comment]
Hey chaps!

Heres a fiddle I have constructed that shows how it works:

https://jsfiddle.net/mnrge1x6/

Is this the same behaviour you are expecting / experiencing?

Cheers!

**Comment by lebronchin** [comment]
@GoodBoyDigital 
thanks mate,
I made a little change on your fiddle to show my question. 
[https://jsfiddle.net/mnrge1x6/2/](url)
It seems like it works differently from the previous version.
When the items under different containers overlap, the top one doesn't block the events from the bottom one anymore.
Is it the desired change you want and will be working like this in the future versions?
If so, I will start changing the structure of my code.
Could you confirm it with me, thanks.

**Comment by GoodBoyDigital** [comment]
Ahh! I see it now :) 
Yes, not ideal at all that! Will take a poke around the codes...

**Comment by lebronchin** [comment]
waiting for the good news:)

**Comment by GoodBoyDigital** [comment]
Hello! Should be fixed in the Dev branch now. Let me know if it works ok for ya!

**Comment by GoodBoyDigital** [comment]
hmm.. actually i think i fixed the issue but may have created another. watch this space..

**Comment by GoodBoyDigital** [comment]
ok, think i got it now. Dev branch updated..

**Comment by lebronchin** [comment]
now it works perfectly
thanks
