### ISSUE TITLE
Pixi v 3.0.9 in Galaxy S7

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#2400]
in Galaxy S7 filters are not working.

Probably the problem is that this device implement the new webGL.

anyway to solve this problem rapidly ?

**Comment by englercj** [comment]
What does "not working" mean? 

Please read the [Contributing Guide](https://github.com/pixijs/pixi.js/blob/master/CONTRIBUTING.md#reporting-issues) on how to make helpful issues.

**Comment by JenGL** [comment]
I investigated this problem,

the blur filter is destroying the image... it is replicating the image 4 
times instead of applying the blur.

this is an example: http://jsfiddle.net/63pg3qzm/8/


Il 16/03/2016 16:07, Chad Engler ha scritto:

**Comment by ivanpopelyshev** [comment]
Oh, its filter resolution problem, then :)

**Comment by GoodBoyDigital** [comment]
v4 (dev) should be better 👍
