### ISSUE TITLE
Container caches bounds which leads to incorrect behavior when masking

### ISSUE THREAD

**Issue by MichaelZawadzki** [pixijs/pixi.js#2402]
I have a Container with many children to which I am applying a sprite mask. 
Upon resizing events (where I modify the children in the container as well as the sprite mask source texture)... the rendered container with the mask clips improperly after scaling up. 

Digging into the PIXI code the problem is that the Container class caches its bounds to _currentBounds. This is never invalidated even after modifying the children in it. This leads to the Container thinking it has smaller bounds... and resulting in the blit being clipped.

A work-around for me was to manually invalidate the _currentBounds field of the Container on resize events. 

I think ideally the cached _currentBounds should somehow get auto-invalidated.

Working with v3.0.10 here.

**Comment by ivanpopelyshev** [comment]
> This is never invalidated even after modifying the children in it.

Its invalidated on next updateTransform()

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
