### ISSUE TITLE
Bugged masks under Chrome 49

### ISSUE THREAD

**Issue by PK-BF** [pixijs/pixi.js#2406]
After upgrading from Chrome 48 to 49, setting PIXI.Graphics object as a mask leads to some bugged behaviour: masked object (does not seem to matter if it is just a container, or a sprite) does not render every render() call. It's like it wasn't there or was invisible (but it is there and is visible). It's rendered like every 10th render, sometimes more often, sometimes way less than that. 
No exceptions thrown, no errors logged.
When using sprite as a mask, everything works fine.
I tried Chrome 48 again and everything was perfect.
None of my colleagues has this problem though (everyone's using 49). I work on Win7, i3 3.50, 8GB RAM and Radeon HD 5450.

**Comment by NintendoBen** [comment]
I saw the same issue running Windows 10, Chrome 49.0.2623.87 m - Radeon HD 6970

**Comment by ivanpopelyshev** [comment]
BTW, if you are using rectangles for masks, better just use filter and filterArea. Is that webgl or canvas mode?

**Comment by NintendoBen** [comment]
I placed a mask on my root display object - it was a graphic that I drew a circle to. Kind of like an animated keyhole effect ala Super Mario World. It was rendering in WebGL.

**Comment by NintendoBen** [comment]
The Pixi.js Brings Canvas and webGL Masking blog post also has the problem:
- http://www.goodboydigital.com/pixi-js-brings-canvas-and-webgl-masking/

The issue isn't present for me using the same version of Chrome on Windows 8.1, or Chrome on Mac.

**Comment by GoodBoyDigital** [comment]
Yo! can you try running the example with pixi v4?

**Comment by NintendoBen** [comment]
I'm seeing the issue on my home PC - I can give it a shot when I get back from work. Is the API for version 4 basically the same?

**Comment by GoodBoyDigital** [comment]
pretty much!

**Comment by NintendoBen** [comment]
Looks like the panda example still has the flashing glitch (rapid blinking - not uniform) when using pixi v4 - I pulled down pixi v4 from the dev-v4.0.0 branch here: https://github.com/pixijs/pixi.js/blob/dev-v4.0.0/bin/pixi.js

**Comment by Lexico** [comment]
Hi, I have the same issue on my game. I'm using PIXI 2.2.0 (pretty old, I know) and I just can't afford to update the framework to v3 or v4 because my game is already live and running (and the code is already very complex to try and do an API change).
So far the only thing I could do was force the use of Canvas (it seems to work that way, looks like a webGL only issue).
When I run the panda example, I get the same flickering. Chrome 49 on Windows 7.
Thanks!

**Comment by JiDW** [comment]
Hello,

We have a lot of our players having the same issue in our game, they can't play anymore. We just understood the link between them (AMD+ Chrome 49) and found this issue here.

Any luck finding a fix ?

Regards.

**Comment by JiDW** [comment]
Did someone with the required knowledge took a look at it ?

I mean, it's a critical bug impacting nearly every websites and games using PIXI v3 and there is no fix or workaround for it. We can't seriously ask our customers to switch to Firefox or Edge.

I tested latest Chrome Canary and the bug was there too.

**Comment by Lexico** [comment]
We're now up to version 50.0.2661.75 m of Google Chrome and this is still happening to me.

**Comment by JiDW** [comment]
Yup. I know that it is not directly a PIXI error but it's a bit scary to see that this kind of thing can happens. Like, one automatic update and your app doesn't work anymore, and nobody knows why 1 month later.

**Comment by PK-BF** [comment]
Just tested canary version - 52.0.2714.0 canary (64-bit) and masks seem to be working fine again.

**Comment by Lexico** [comment]
Yup, same here... looks like someone at Google found the bug and fixed it on Canary... I guess it's only a matter of time since it makes it to the official stable release.
Still would like to know what the bug was, though.
