### ISSUE TITLE
Is masking supported with canvas renderer?

### ISSUE THREAD

**Issue by hjujah** [pixijs/pixi.js#2408]
Hi, 

First of all great work with the pixi library. Totally love it and I'm using it on most of the recent projects! :)

But... I can't make the masks to work with the canvas renderer (it works fine with the webGL one).
Is it supported at all? And if it is, what is the trick? 
I saw a similar 2 years old issue, solved by putting the sprite inside of the PIXI.Container, but that didn't work out for me. I assume that was a fix for some older versions of PIXI.
If its needed I can make a jsFiddle, but there are are no special steps to reproduce the issue, the masks just don't work at all with canvas renderer (at least for me)...
I'm using the PIXI 3.08.

Any help would be appreciated! 

Filip

**Comment by GoodBoyDigital** [comment]
A fiddle would be great! - Is you mask a Graphics object? as only they can be used as masks in Canvas.

**Comment by hjujah** [comment]
No, my mask is a sprite, actually a spritesheet. Here is a working [link](http://trojaweb.kitchendev.space/) for the website, so you could see the effect in the page transitions. Do you think its possible to achieve that somehow without the webGL renderer? Thanks.

**Comment by GoodBoyDigital** [comment]
Cool mask effect! You would need to create a custom solution for canvas i'm afraid. Considering 99.3% of browsers run WebGL I would just make a simple alternative transition for the 0.7% who still use canvas. hope that helps!

**Comment by hjujah** [comment]
Ok, tnx for the reply!
