### ISSUE TITLE
"autoPreventDefault = false" still prevents default scroll functionality on Windows Mobile

### ISSUE THREAD

**Issue by dsge** [pixijs/pixi.js#2410]
Setting `renderer.plugins.interaction.autoPreventDefault` to `false` allows our users to use the native scrolling of the browsers on Android and IOS. They can start the swipe on the canvas and it scrolls the html `body` as expected.

Unfortunately `autoPreventDefault = false` does not have any effect on Windows Phone's stock Internet Explorer. If our PIXI canvas is higher than the viewport they cannot scroll the page to access the content below the canvas. Starting a swipe on the canvas does not scroll the html `body`.

Windows Phone operating system version: 8.10.14219.341

**Comment by englercj** [comment]
Just out of curiosity, what is the behavior you expect? That setting makes us call `event.preventDefault()` which will prevent scrolling.

**Comment by Cian911** [comment]
I'm having a similar issue only I'm using Panda.js ( Which Pixi.js is apart of ). Setting autoPreventDefault to false does not solve this problem for me unfortunately.  Does anyone have an update on a solution for this issue?

**Comment by brenwell** [comment]
I had a similar issue with Chrome on Android. I found the issue to come from the following piece of code

```javascript
    InteractionManager.prototype.addEvents = function addEvents() {

       ...

        if (window.navigator.msPointerEnabled) {
            this.interactionDOMElement.style['-ms-content-zooming'] = 'none';
            this.interactionDOMElement.style['-ms-touch-action'] = 'none';
        } else if (this.supportsPointerEvents) {
            this.interactionDOMElement.style['touch-action'] = 'none';
        }

        ...
```

The css rule was killing all my native touch events

Simply overwriting this, after constructing the renderer, fixed it for me

canvasEle.style['touch-action'] = 'auto';

Perhaps this helps with the windows problems aswell

**Comment by brenwell** [comment]
perhaps 'pan-y' is a better value

https://github.com/hammerjs/hammer.js/wiki/How-to-fix-Chrome-35--and-IE10--scrolling-(touch-action)

**Comment by englercj** [comment]
Is this a pixi issue, or a general canvas issue on Windows Phone?

**Comment by Milewski** [comment]
Well i couldn't scroll-down having my canvas fullscreen at the top (on android, ios, win)... i fixed this by setting the `touch-action` to `auto` as mentioned by @brenwell 

```
renderer.view.style['touch-action'] = 'auto';
document.body.appendChild(renderer.view);
```

**Comment by Milewski** [comment]
okay... it did work only on chrome for Android... but didn't on any browser on IOS.... :/

**Comment by englercj** [comment]
I'm going to close this since I think this is a cavas/browser issue; not a pixi-specific issue.

**Comment by zhuyunhe** [comment]
i have the same issue. can we have a way to figure it out?
