### ISSUE TITLE
RenderTexture producing black rectangles

### ISSUE THREAD

**Issue by pwolfert** [pixijs/pixi.js#2411]
I'm trying to use a RenderTexture to create a texture out of a container with multiple sprites, and I always just get black boxes.  The difference I can see between what I'm doing and what the examples do is that I use a different renderer instance.  Is this not okay?  I'm not really sure what I'm doing wrong, but I get this error when I try to render:

`RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.`

I've created a jsfiddle with my problem: [https://jsfiddle.net/9897v3z8/6/](https://jsfiddle.net/9897v3z8/6/).

**Comment by ivanpopelyshev** [comment]
RenderTexture is something that exist on GPU side, and its not possible to transfer it from one context to another in WebGL1. Why do you want to use other renderer for it?

**Comment by pwolfert** [comment]
Okay, I didn't realize that.  It's just that I have a very large project with lots of classes, and the function of making textures (or images—I mainly use it for creating images the are placed in the DOM at the moment) I've separated into its own class.  I'll just have to refactor, then, to make it so I can pass in a renderer somehow.
