### ISSUE TITLE
WebGLRenderer method fails when running on a Google Chrome Extension

### ISSUE THREAD

**Issue by MrAnyone** [pixijs/pixi.js#2413]
Whenever I try to use it injecting the pixi.js to a page etc, when I call WebGLRenderer, it throws an error saying "TypeError: Cannot read property 'bind' of undefined"

The line that produces that is the following: (playerAPIDiv is a jquery DOM element)
renderer = PIXI.WebGLRenderer(playerAPIDiv.width(), playerAPIDiv.height());

When I try to do that:
renderer = new PIXI.autoDetectRenderer(playerAPIDiv.width(), playerAPIDiv.height());

It just freezes the page (because there is no try/catch in autoDetectRenderer)

Thanks for reading. I'm waiting for a feedback.

**Comment by ivanpopelyshev** [comment]
```javascript
//WRONG
renderer = PIXI.WebGLRenderer(playerAPIDiv.width(), playerAPIDiv.height());
//OK
renderer = new PIXI.WebGLRenderer(playerAPIDiv.width(), playerAPIDiv.height());
//WRONG
renderer = new PIXI.autoDetectRenderer(playerAPIDiv.width(), playerAPIDiv.height());
//OK
renderer = PIXI.autoDetectRenderer(playerAPIDiv.width(), playerAPIDiv.height());
```

**Comment by MrAnyone** [comment]
@ivanpopelyshev Doing the above generates the same error, while using it with Tampermonkey don't. Here it is a Tampermonkey extension that works perfectly: https://github.com/MrAnyone/YouTube-Audio-Visualizer

But when I try to execute the same code in a Google Chrome extension, this error occurs.

**Comment by MrAnyone** [comment]
I found an way to fix it, all you need to do is inject the code of the library ( & yours ) to the page scope, here is what injector looks like (using JQuery): 

https://github.com/MrAnyone/YouTube-Audio-Visualizer/blob/master/injector.js

The chrome extension runs in a different scope from the page, thats why PIXI (and any other library like ThreeJS) fails to init.
