### ISSUE TITLE
Drawing new things on top of old things

### ISSUE THREAD

**Issue by jmeas** [pixijs/pixi.js#2416]
This is related to (and may, in fact, be a duplicate of) issues related to z-index, such as #2099 and #1674.

Pixi draws new things on top of old things. So if I draw square A, followed by square B, square B will be on top of square A. I'd like to reverse this behavior, such that square B would appear beneath square A.

Using native 2D canvas APIs, it's possible to set this globally by setting `composite-operation` to `destination-over`. Is the only way to do this in Pixi by "manually" sorting the children for every sprite?

I plan to be rendering 10-20k sprites onscreen at once, so I'm interested in the most performant solution. Is there any simple way to automatically flip the rendering order for everything, or is manually sorting the children the best approach always?

**Comment by GoodBoyDigital** [comment]
Hi there! You could use ```view.addChildAt(bullet, 0)``` as this will add things to the back.

**Comment by jmeas** [comment]
Oh, awesome. Thanks @goodboydigital!
