### ISSUE TITLE
Reloading a spritesheet

### ISSUE THREAD

**Issue by jberube** [pixijs/pixi.js#2419]
I have a scenario in which I need to reload a spritesheet that is likely to have changed on the server.

Currently, loading a spritesheet for a second time won't reload it.

Adding a querystring to the url to bust the local cache won't really help : the new json is loaded, but not the image.

It looks to be done this way by design : `Loader.prototype.add` function has the following check:
``` line 236
    // check if resource already exists.
    if (this.resources[name]) {
        throw new Error('Resource with name "' + name + '" already exists.');
    }
```

Is there a way I can force a spritesheet to be reloaded?

**Comment by englercj** [comment]
Reset the loader if you are done and need to load more resources, or create a new loader:

```js
PIXI.loader.load(..)

//.. later, reuse it
PIXI.loader.reset();
PIXI.loader.load(...);
```

**Comment by andrevenancio** [comment]
Not wanting to open any other bugs on the `reset()`

@englercj I don't think `reset()` is working properly.

Imagine this scenario:
a) you want to load a small sprite for a loading animation.
b) when this first load get completed, you reset() the loader
c) you do a fancy loading animation
d) You create a second loader for all the game assets (images, or whatever)
e) when you get this second load event called, the name you gave to your initial loader is gone (as the reset() was called)

However, if you try to access the textures array, you will only find the textures that came from your 1st loader, not this last one.

Am I the bug?
:)

**Comment by andrevenancio** [comment]
I was the bug!
works fine. turns out I was calling the same .json on the second load :) I need a coffee!

**Comment by englercj** [comment]
:) Closing!
