### ISSUE TITLE
Displacement filter breaks the image borders

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#2423]
I'm trying to use the displacement filter with a depthmap to simulate a 3d effect.
But the filter breaks the border of the image !
this is an example of the problem: https://jsfiddle.net/6w0kuqko/3/

as you can see if you move the mouse on the bottom of the image the border becomes pixelated, even if the image is not finished !

In the example I added the original image to show you that the image in the renderer is scaled, so there is a part of the image that is hidden and I was expecting that this part of the image would be shown instead of pixelate the borders.

Any way to avoid this behaviour ?

**Comment by JenGL** [comment]
I saw that this is caused by the fact that the displacement filter is applied using a mask with a dimension of the renderer, and so if my image is bigger than the renderer it's not considered...

This is the correct behaviour that you want to obtain ?

**Comment by englercj** [comment]
This should be fixed in v4 now.
