### ISSUE TITLE
Center stage on particular object

### ISSUE THREAD

**Issue by Darker** [pixijs/pixi.js#2424]
In the process of making a 2D game it's typically required that the view is centered on whatever represents the player. At this point, I don't know how to do that apart from manually offsetting all coordinates of all sprites.

How to properly move the stage so that player is always in the center of the canvas view?

**Comment by ivanpopelyshev** [comment]
I use standart Position/scale/pivot combo.

```javascript
//(0,0) for us is center of the screen
stage.position.x = renderer.width/2;
stage.position.y = renderer.height/2;
//scale it
stage.scale.x = 2.0;
stage.scale.y = 2.0;
//now specify which point INSIDE stage must be (0,0)
stage.pivot.x = character.position.x;
stage.pivot.y = character.position.y;
```

**Comment by Darker** [comment]
Thank you very much, it works perfectly! :)

It also answered another question I needed but didn't even ask - how to zoom the stage.
