### ISSUE TITLE
PIXI.Line's not a thing ... is it?

### ISSUE THREAD

**Issue by OlsonDev** [pixijs/pixi.js#2425]
The documentation mentions `PIXI.Line` in two places:

1. [Graphics.js](https://github.com/pixijs/pixi.js/blob/master/src/core/graphics/Graphics.js#L1129)
2. [GraphicsData.js](https://github.com/pixijs/pixi.js/blob/master/src/core/graphics/GraphicsData.js#L55)

But I'm not seeing any other mention of it elsewhere. I'm assuming those mentions can be removed..?

**Comment by OlsonDev** [comment]
Also, shouldn't those list `PIXI.RoundedRectangle`?

**Comment by ivanpopelyshev** [comment]
Nice one, we'll fix it, thank you!

**Comment by GoodBoyDigital** [comment]
looks fixed 👍
