### ISSUE TITLE
pixi can be blocked if data:URI's not allowed by CSP

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi.js#2426]
Hi more of a 'heads up' than an issue.
Basically game created for client worked fine until uploaded to their servers. Pixi.js was loaded but undefined.
Tracked it down to the client's CSP not allowing _data_: _URIs._
`canUseNewCanvasBlendModes()` in pixi.js has the following code:

```
var pngHead = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAABAQMAAADD8p2OAAAAA1BMVEX/';
var pngEnd = 'AAAACklEQVQI12NgAAAAAgAB4iG8MwAAAABJRU5ErkJggg==';
```
which was causing the whole of pixi.js to be blocked. Fortunately wasn't using blend modes so just removed the code and everything looks to be working fine.

Cheers

**Comment by englercj** [comment]
Wow, interesting...thanks for the heads up. Not sure what the correct fix for this would even be...

**Comment by GoodBoyDigital** [comment]
just pushed a fix for this 👍 
No more pngs - instead we use little canvas elements. Should do the trick i hope!

**Comment by macguffin** [comment]
Awesome. I'll report back next time I deploy in the environment that caused the issue if there are any problems. 
Thanks.

**Comment by GoodBoyDigital** [comment]
no worries!
