### ISSUE TITLE
License missing in minfied version of library

### ISSUE THREAD

**Issue by rzoller** [pixijs/pixi.js#2427]
In version 3.0.10, and probably all 3.x versions before, the license is not included in the minified version of the library.

As far as I understand, the MIT license requires that the license be included with the software, which means that people who only use the minified version in production (aka almost everybody) currently don't comply with the license.

There is already a
```
// TODO - Concat license header to dev/prod build files.
```
in [bundle.js](https://github.com/pixijs/pixi.js/blob/v3.0.10/gulp/util/bundle.js), but I feel like this is important enough to deserve its own issue.

This might actually not be trivial to fix, since just copying the whole MIT license text kind of goes against the spirit of minification. However, I think something along the lines of
```
/*
 pixi.js v3.0.10
 (c) 2013-2015 Mathew Groves http://pixijs.com
 License: MIT
*/
```
might be sufficient. (inspired by the [minified version of AngularJS](https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js))

**Comment by OlsonDev** [comment]
`2015`? ;-)

**Comment by rzoller** [comment]
Well, it says `2015` in the latest LICENSE file, so I just copied that...

**Comment by GoodBoyDigital** [comment]
poke @englercj - would this be easy to add to the build step?

**Comment by englercj** [comment]
We had it at one point, shouldn't be hard to add again (as long as the prod build has no source-maps).

**Comment by GoodBoyDigital** [comment]
@bigtimebuddy has sorted this in v4 build process 👍
