### ISSUE TITLE
fastest way to compare 2 textures / bitmapData 

### ISSUE THREAD

**Issue by fyyyyy** [pixijs/pixi.js#2429]
Hello

Currently if i want to compare two textures or bitmapDatas with each other, i have to loop through the data arrays and compare each pixel. 

Another method would involve rendering images on top of each other with a difference filter, but i haven't tried if that is possible. It should be considerably faster if hardware support is enabled on the client at least via webgl.

The 3rd option i could think of is converting to base64 and comparing strings which should be really fast to compare. ( if the base64 conversion already happened at creation or is updated on every modification of the texture.) However there seems to be no way to convert a texture or bitmapData to base64 without going through RenderTexture first.

Any other ideas are welcome.

**Comment by digibo** [comment]
Hello

I'm not sure if this is the best place to discuss a general topic like this. Maybe try the [html5gamedev forums](http://www.html5gamedevs.com/forum/15-pixijs/) for general questions.

Anyway, while I'm here, getting the bitmapData from a canvas will probably be the biggest bottleneck, doesn't matter whether you go through RenderTexture or some other way. Converting to base64 is pointless afterwards, just compare the pixels. You probably need an entirely different approach IMO, but if you REALLY want to check if two textures use the same image (not canvas), I'd go for comparing the texture.baseTexture.source.src. Sounds like a last resort, but it should work :)

Again, try the forums, GitHub Issues are generally used for bugs and probably only the devs read them.

**Comment by ivanpopelyshev** [comment]
Why do you even need that?

**Comment by fyyyyy** [comment]
Thanks for the suggestions, i need bitmap comparison for motion detection of 2 video frames, the current frame and the previous frame.

**Comment by fyyyyy** [comment]
I am now comparing `bitmapData.context.getImageData(0,0,width,height).data`pixel by pixel, since bitmapData.data seems to be out of date unfortunately
