### ISSUE TITLE
lineStyle width is not accurate

### ISSUE THREAD

**Issue by sjlynch** [pixijs/pixi.js#243]
When creating a rectangle, setting graphics.lineStyle(1, 0xFF0000); sets the line color to red with a width of 2 pixels instead of 1 pixel. 

The problem occurs in chrome with either CanvasRenderer or WebGLRenderer and it occurs in IE10 with CanvasRenderer (I don't think IE10 supports WebGL yet).

A linewidth of 1 creates a line of 2 pixels and the line is slightly translucent. Setting the line width to 2 creates a line that is opaque and has a thickness of 2 pixels, which is correct.

Zoom level in the browser is set to 100% and I'm not scaling any objects.

**Comment by basickarl** [comment]
I apologize if I am of no use here but the 1px issue still exists for some reason. I'm contemplating on writing my own code which I really would not like to do as I would like to use pixi.

Heres an example of a 1px line which works in my chome browser.
http://jsfiddle.net/drewnoakes/692cbo8q/

**Comment by basickarl** [comment]
For those wanting an answer for 1px lines heres a way of getting it: https://stackoverflow.com/a/13879402/1137669

Add 0.5 onto the position x or y coordinate.
