### ISSUE TITLE
Pixi video player put video in play after a .load()

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#2431]
Hi everyone !

the pixi video player puts video in play if i just do a video.load()

the problem is on VideoBasetexture:

```js
VideoBaseTexture.prototype._onCanPlay = function ()
{
    this.hasLoaded = true;

    if (this.source)
    {
        this.source.removeEventListener('canplay', this._onCanPlay);
        this.source.removeEventListener('canplaythrough', this._onCanPlay);

        this.width = this.source.videoWidth;
        this.height = this.source.videoHeight;

        this.source.play();

        // prevent multiple loaded dispatches..
        if (!this.__loaded)
        {
            this.__loaded = true;
            this.emit('loaded', this);
        }
    }
};
```

this is not working on Mobile devices where i change the src attribute of the video.

To reproduce the bug:

1) init a video with an src and play it.
2) change the src of the video

now the video will be putted in play after the load or the new src is executed but thx to a bug present in Android (not sure about iOS)  this.source.videoWidth; adn  this.source.videoHeight; will be = 0;

and anyway if i want to perform a .load and after a .play in a VideoBaseTexture i can't with this behaviour !

**Comment by JenGL** [comment]
just to help pple that may have the same problem.

to allow autoplay of video on mobile you need to load an empty video and play it on the first touchevent captured. Then you can play video changing the src of this video element without waiting a new touchevent.

But on Android (and iOS) video.onloadedmetadata is bugged, it's triggered too early and the video.videoWidth and video.videoHeight will  be equal to 0. So when you'll put in play a video with pixi substituting the src of the video element probably the video will  be entirely black, only audio will be present.

if you don't put in play the video the real dimension of the video will not be setted ! 

My solution (that i know to be b ad) is to remove these lines from pixi 
`this.width = this.source.videoWidth;
    this.height = this.source.videoHeight;

    this.source.play();`

and to play a video I do the following

`video.pause();
 video.src = src;
 video.currentTime = 0;
 video.volume = 0;
 video.onloadedmetadata = () => {
        const setDimension = () => {
          if(this._video.videoHeight == 0 || this._video.videoWidth == 0 ){
            setTimeout(() => {
              video.play();
              setDimension();
            }, 10);
            return;
          }
          video.width = video.videoWidth;
          video.height = video.videoHeight;
          sprite.width = video.videoWidth;
          sprite.width =  video.videoHeigh;
          video.currentTime = 0;
          video.volume = 1;
          video.play();
        };
   setDimension();
   };
video.load();
`

**Comment by ivanpopelyshev** [comment]
ok, we are going to release v4 today or tomorrow and i think we can change that thing there. Thank you for the input :)

**Comment by ivanpopelyshev** [comment]
Can you please test if it works in latest dev? https://github.com/pixijs/pixi.js/blob/dev/bin/pixi.js

**Comment by JenGL** [comment]
I can't test another version of pixi right now, but looking the source the problem should be the same. because you put in play the video in the 'canplay' callback that in mobile is too early (videoWidth and videoHeight will be equal to 0)

**Comment by ivanpopelyshev** [comment]
In new version there's second place when videoWidth and videoHeight is used. It may work

**Comment by JenGL** [comment]
the last version gives me a lot of error ^^' 
`    Pixi.js 4.0.0 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 


pixi.js:1126 ERROR: 0:116: '26' : memory exhausted 

pixi.js:1083 WebGL: INVALID_VALUE: attachShader: no object or object deleted
pixi.js:1089 Pixi.js Error: Could not initialize shader.compileProgram @ pixi.js:1089Shader @ pixi.js:399generateMultiTextureShader @ pixi.js:19164SpriteRenderer.onContextChange @ pixi.js:18891emit @ pixi.js:5426WebGLRenderer._initContext @ pixi.js:15593WebGLRenderer @ pixi.js:15533module.exports.Object.assign.autoDetectRenderer @ pixi.js:12953Renderer @ renderer.js:28Morphcast @ morphcast.js:13(anonymous function) @ index.js:101UncoatedModuleInstantiator.getUncoatedModule @ traceur.js:229ModuleStore.get @ traceur.js:315(anonymous function) @ _inline_script_1.js:3ModuleStore.getAnonymousModule @ traceur.js:358(anonymous function) @ _inline_script_1.js:1LoaderCompiler.evaluateCodeUnit @ traceur.js:31640$__super.evaluate @ traceur.js:31800InternalLoader.evaluate @ traceur.js:32101InternalLoader.handleCodeUnitLoaded @ traceur.js:32014(anonymous function) @ traceur.js:31886
pixi.js:1090 gl.VALIDATE_STATUS falsecompileProgram @ pixi.js:1090Shader @ pixi.js:399generateMultiTextureShader @ pixi.js:19164SpriteRenderer.onContextChange @ pixi.js:18891emit @ pixi.js:5426WebGLRenderer._initContext @ pixi.js:15593WebGLRenderer @ pixi.js:15533module.exports.Object.assign.autoDetectRenderer @ pixi.js:12953Renderer @ renderer.js:28Morphcast @ morphcast.js:13(anonymous function) @ index.js:101UncoatedModuleInstantiator.getUncoatedModule @ traceur.js:229ModuleStore.get @ traceur.js:315(anonymous function) @ _inline_script_1.js:3ModuleStore.getAnonymousModule @ traceur.js:358(anonymous function) @ _inline_script_1.js:1LoaderCompiler.evaluateCodeUnit @ traceur.js:31640$__super.evaluate @ traceur.js:31800InternalLoader.evaluate @ traceur.js:32101InternalLoader.handleCodeUnitLoaded @ traceur.js:32014(anonymous function) @ traceur.js:31886
pixi.js:1091 gl.getError() 1281compileProgram @ pixi.js:1091Shader @ pixi.js:399generateMultiTextureShader @ pixi.js:19164SpriteRenderer.onContextChange @ pixi.js:18891emit @ pixi.js:5426WebGLRenderer._initContext @ pixi.js:15593WebGLRenderer @ pixi.js:15533module.exports.Object.assign.autoDetectRenderer @ pixi.js:12953Renderer @ renderer.js:28Morphcast @ morphcast.js:13(anonymous function) @ index.js:101UncoatedModuleInstantiator.getUncoatedModule @ traceur.js:229ModuleStore.get @ traceur.js:315(anonymous function) @ _inline_script_1.js:3ModuleStore.getAnonymousModule @ traceur.js:358(anonymous function) @ _inline_script_1.js:1LoaderCompiler.evaluateCodeUnit @ traceur.js:31640$__super.evaluate @ traceur.js:31800InternalLoader.evaluate @ traceur.js:32101InternalLoader.handleCodeUnitLoaded @ traceur.js:32014(anonymous function) @ traceur.js:31886
pixi.js:1096 Pixi.js Warning: gl.getProgramInfoLog() missing shaders
pixi.js:1226 WebGL: INVALID_VALUE: getProgramParameter: no object or object deleted
pixi.js:1266 WebGL: INVALID_VALUE: getProgramParameter: no object or object deleted`

**Comment by themoonrat** [comment]
@JenGL could you recheck this bug please on latest dev branch? Changes have been made to the class that may fix this issue

**Comment by englercj** [comment]
Can you retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!

**Comment by JenGL** [comment]
We are going to upgrade to the new pixi, but atm we decide to not support video.
I'll try to test it if I have time ^^

**Comment by englercj** [comment]
I'm going to close it then, please reopen if you still have issues.
