### ISSUE TITLE
How to tween DOM Element

### ISSUE THREAD

**Issue by dalisoft** [pixijs/pixi.js#2435]
Hi, i'm seen its recently and trying to make comparision with other Animation Library (GSAP, Unim, Animo.js, tween.js) to see how is it really that very 2D fastest animation engine as said in Homepage. Thanks.

**Comment by digibo** [comment]
Hi, dalisoft. Pixi is a rendering library - it takes care of drawing the images to the screen. Animation/tweening libraries take care of moving/changing the images. The two are often combined. I've used Pixi.js with GSAP and it's sweeeet.

**Comment by dalisoft** [comment]
Hi @digibo 
It means it's not a tweening engine? Thanks. I'm maked own script, that maked some work of GSAP and it's free. I optimized their performance and very interested how it be faster than my script animation except GSAP (because GSAP developers is very excellent)
