### ISSUE TITLE
TexturePacker rotation is broken in v4

### ISSUE THREAD

**Issue by digibo** [pixijs/pixi.js#2436]
Using rotation when packing images into atlases with TexturePacker causes them to render stretched/squished.

Reading rotation from json spritesheets (atlases, whatever you call them) was implemented at some point in v3, but it's broken in the current dev branch. They look vertically stretched, in my case, as if height and width were switched at some point during the vertex/uv calculations.

I should be able to isolate a simple example, if needed, but it probably won't be before Monday.

**Comment by ivanpopelyshev** [comment]
Hello! I have changed internals for Textures and this thing. Are you sure you dont have some custom code for loading the spritesheet?

**Comment by digibo** [comment]
I noticed the internal changes, I like to delve into the internals of Pixi when debugging :) I am using the PIXI.loaders.Loader, which goes through spritesheetParser.js. Nothing fancy when loading.

Replacing pixi.js with the v3 version fixes the problem, that's why I raised this issue. Maybe it's something specific to this case, but it works with v3 and breaks with v4.

**Comment by ivanpopelyshev** [comment]
Which object do you have problem with? Sprites are working with rotated texture.

**Comment by ivanpopelyshev** [comment]
@digibo please make a minimal demo, I'll look at it. Rotation is serious issue for me :)

**Comment by ivanpopelyshev** [comment]
@digibo ping

**Comment by bQvle** [comment]
@ivanpopelyshev I think you have your own minimal demo here:
http://pixijs.github.io/examples/index.html?s=basics&f=spritesheet.js&title=SpriteSheet%20Animation&v=dev-4.1.0

 :)

**Comment by ivanpopelyshev** [comment]
@bQvle Its v4.1 bug, v4 is looking just fine.

**Comment by SlawomirMazgaj** [comment]
I'm still checking v4 version and I just came across something similar. Possibly related to trimming as well. Investigating now.

**Comment by ivanpopelyshev** [comment]
I spent a lot of time fixing rotations, and they work for both texture packer atlases and spine atlases, and no one can give me demo where trims arent working correctly.

**Comment by SlawomirMazgaj** [comment]
Challenge accepted! : >

Here you go. Here's a spritesheet with 7 images that have a same width. 4 of them are rotated and few are trimmed. It's suppose to be animation of rectangle getting bigger and bigger.

Sorry, not sure where I can put .png with .json so I can load them into pixi examples so attahcing zip with both of them:
[Sheet.zip](https://github.com/pixijs/pixi.js/files/268057/Sheet.zip)

Here's the code I used (after mapping `mc.json` and `.png` locally, but having them locally you should be able to point to them.
```js
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

PIXI.loader
    .add('spritesheet', '_assets/mc.json')
    .load(onAssetsLoaded);

function onAssetsLoaded()
{
  var textures = [];
  textures.push( PIXI.Texture.fromFrame('transition_04.png') );
  textures.push( PIXI.Texture.fromFrame('transition_05.png') );
  textures.push( PIXI.Texture.fromFrame('transition_06.png') );
  textures.push( PIXI.Texture.fromFrame('transition_10.png') );
  textures.push( PIXI.Texture.fromFrame('transition_11.png') );
  textures.push( PIXI.Texture.fromFrame('transition_12.png') );
  textures.push( PIXI.Texture.fromFrame('transition_13.png') );

  var mc = new PIXI.extras.MovieClip(textures);
  mc.animationSpeed = 0.025;
  mc.play();
  stage.addChild(mc);

  requestAnimationFrame(animate);
}


function animate() {
    renderer.render(stage);
    requestAnimationFrame(animate);
}
```

So what is happening? Images 4, 5, 6, 10, 11 are correct.
Size of images 12 and 13 are wrong.

**Comment by ivanpopelyshev** [comment]
Nice, thank you! That will help me for sure :)

**Comment by SlawomirMazgaj** [comment]
Ah btw, it doesn't have to be MovieClip. If you just make a sprite out of individual images it's also incorrect.

**Comment by whizzkid** [comment]
Just to clarify, the error occurs when the texture is rotated by texturepacker in the atlas file.
(so in the json it has:  rotated:true )
NOT when you rotate textures yourself in pixi.
