### ISSUE TITLE
spritesheetParse is not accounting for base64 images

### ISSUE THREAD

**Issue by davearel** [pixijs/pixi.js#2437]
I'm trying to load a spritesheet that uses a base64 image. However, Pixi is assuming that it's going to be a file path so it's trying to append a baseUrl.

https://github.com/pixijs/pixi.js/blob/master/src/loaders/spritesheetParser.js#L29

**Comment by ivanpopelyshev** [comment]
Propose a fix to that line? Something like "if resource.data.meta.image looks like base64 dont append route"

**Comment by davearel** [comment]
@ivanpopelyshev There's a pull request referenced in this ticket above your comment, PR #2438
