### ISSUE TITLE
Glslify doesn't work as given in webpack

### ISSUE THREAD

**Issue by AMorporkian** [pixijs/pixi.js#2439]
In 4.0-rc1, glslify is used extensively. In the documentation, it makes a special note that it is webpack compatible.

However, in reality, that is not the case. There is a glslify loader *for* webpack, but it doesn't work in the same way as the browserify transform. For instance, in browserify you're able to do:

    var vert = glslify('./whatever.vert');

However, to achieve the same thing in webpack, you have to do the following.

    var vert = require('glslify!raw!./whatever.vert');

Sadly, there is simply no way I can see to reconcile the two. Perhaps I'm missing something obvious, but as far as I can see, Pixi 4 is going to destroy every webpack build out there.

**Comment by AMorporkian** [comment]
I've figured out a workaround. I'm going to detail it below, and then close the issue.

My first thought was using transform-loader, but sadly that fails with glslify.  After some further research, I found another loader that *does* transform it correctly. ify-loader. To bundle successfully with webpack, you will need: ify-loader, browserify-versionify, and glslify. Then you simply add 'ify' as the loader on the pixi.js node_module, and you should be good to go.

**Comment by shshaw** [comment]
For me, Pixi was being included in my Webpack project without any compilation errors, but I was receiving the `Pixi.js __VERSION__` log in the console as other issues describe. Then right below that was this error in the browser console, which I think is what @AMorporkian is describing:

```
Uncaught Error: It appears that you're using glslify in browserify without its transform applied. Make sure that you've set up glslify as a source transform: https://github.com/substack/node-browserify#browserifytransform
```

These are the exact steps that solved the problem, for others who may be more inexperienced with Webpack like myself.

Run `npm install ify-loader --save-dev` to install [ify-loader](https://github.com/hughsk/ify-loader)

Then under _webpack.config.js_, I added this under `module.loaders`:
```
  { test: /node_modules\/pixi\.js/, loader: 'ify' },
```

After that, PIXI ran as expected:
`npm install --save pixi.js`, then `import PIXI from 'pixi.js';`

**Comment by shshaw** [comment]
Also: I'm not sure what needs to happen in PIXI itself to prevent this issue from occurring, but it would be wonderful if this could be solved!
