### ISSUE TITLE
is it possible to specify alpha transparency when setting a mask object to PIXI.Graphics?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#2443]
I have a PIXI.Graphics object which I'm using as a mask. I draw to the graphics object as such:

```
p = []
for pt in intersections
  p.push(new PIXI.Point(pt.x, pt.y))

g = new PIXI.Graphics()
g.clear()
g.beginFill(0x0, 0.5)
g.drawPolygon(p)
g.endFill()
```

any value I set for alpha transparency (0.5, 1.0, omitted, etc) always draws the pixels at full opacity. Am I doing something wrong, or is mask alpha only supported for sprite based masks?

**Comment by mreinstein** [comment]
<img width="608" alt="screen shot 2016-04-02 at 10 16 27 pm" src="https://cloud.githubusercontent.com/assets/718067/14230880/9930c2cc-f920-11e5-9c1f-82584368d322.png">

**Comment by englercj** [comment]
Pretty sure mask alpha is only supported for sprite masks. The sprite masks use a shader, but the graphics vector masks use the stencil buffer and just "cut" the area.

You could generate a sprite from the graphics and use that as the mask?

**Comment by mreinstein** [comment]
> You could generate a sprite from the graphics and use that as the mask

Needs to happen at 60fps. The sprite would be the size of the current window. Do you think this is something pixi can do reasonably fast?

**Comment by mreinstein** [comment]
Sorry I don't know why I'm asking when I can just code the darn thing up in 5 minutes and try it myself. Thanks for the feedback. :)
