### ISSUE TITLE
RenderTextures are broken under CanvasRenderer in v4

### ISSUE THREAD

**Issue by AMorporkian** [pixijs/pixi.js#2452]
We have been trying out Pixi v4 (and v4.1) in our game. Although we only plan on supporting WebGL, during testing we enabled CanvasRenderer to nail down some bugs to help @ivanpopelyshev fix them. During that process, I noticed that Pixi v4 just simply doesn't seem to draw RenderTextures under canvas mode.

Screenshot demonstrating rendering under canvas with our floor sprites being chunked to 1024x1024 render textures:

![](http://i.imgur.com/OCQyRCf.png)

With that chunkification function disabled:

![](http://i.imgur.com/MnxUuME.png)

I have tried different chunkification/RenderTexture sizes, from 128x128 to 2048x2048, and all result in the same results. The problem does not exist in WebGL.

Edit: Probably worth noting, SC in the status UI is Sprite Count, which more accurately should just be display object count.

**Comment by GoodBoyDigital** [comment]
Hello! keen to take a look at this one, please can you have an isolated example that I can fix? Cheers!

**Comment by ivanpopelyshev** [comment]
Its fixed in https://github.com/pixijs/pixi.js/pull/2463

**Comment by AMorporkian** [comment]
Closing as it's fixed.
