### ISSUE TITLE
Version number not incremented for 3.0.11

### ISSUE THREAD

**Issue by jwdunn1** [pixijs/pixi.js#2454]
Is there a specific reason the version number was not updated for release 3.0.11? Expected "Pixi.js 3.0.11" but saw "Pixi.js 3.0.10" on the console. Makes for more difficult version management.

**Comment by englercj** [comment]
3.0.11 hasn't been released to npm yet. Looks like no one has pushed it up yet, I'll have to try and remember to do it when I get home.

**Comment by fsolis17** [comment]
When can the push be expected. Thanks!

**Comment by englercj** [comment]
Done.
