### ISSUE TITLE
Sprite.prototype.destroy not destroying children

### ISSUE THREAD

**Issue by Kouty** [pixijs/pixi.js#2457]
**Container** class has a method:  **destroy(destroyChildren)** which allows the caller to destroy also the children of the container.
A **Sprite** is also a Container, but it's destroy signature is:
**destroy(destroyTexture, destroyBaseTexture)** which does not allow its children to be destroyed. This is not coherent with it's super class (Container) behavior. In addition, calling container.destroy(true) do not guarantee that all children are destroyed, since children of Sprite will not be destroyed. It's an example of violating Liskov substitution principle.

This is a structural cause of memory leaks in PIXI, since there is not an easy way to remove a container and all it's children, so that browser memory is freed accordingly.

Moreover: Sprite.destroy(destroyTexture, destroyBaseTexture) it's cofunsing. What does sprite.destroy(false, true) mean? I have destroyed the Sprite, the baseTexture, but not the texture. But I think that texture, having it's baseTexture destroyed, is not valid anymore.

Probably a good solution is:
- enhance Container with destroy(destroyChildren, destroyTextures), which let you decide if letting or not all textures available for reuse.
- Change Texture to have a no parameter destroy(), that also destroys its base texture.
- make Sprite.destroy to have the same signature of Container: destroy(destroyChildren, destroyTextures)

This issue is related to:
Container#destroy will pass down the first parameter regardless if the child is a Sprite instance, is this right? #2392

**Comment by AMorporkian** [comment]
There is an attempt to fix this in #2418. It looks like it will likely be fixed in v4.0.0.

**Comment by GoodBoyDigital** [comment]
closing as this is fixed in v4 👍
