### ISSUE TITLE
Invalid version number v3.0.10

### ISSUE THREAD

**Issue by Oza94** [pixijs/pixi.js#2458]
Hello,

When I pull pixi.js from npm (v3.0.10) it outputs a wrong version number : 

![Console](http://i.imgur.com/s6r6D1S.png)

It breaks pixi-particles detection logic see pixijs/pixi-particles#25. I also tried a `npm i pixi.js@3.0.10 --no-cache` without success.

**Comment by GoodBoyDigital** [comment]
all good now it seems! 👍
