### ISSUE TITLE
SpriteRenderer.destroy clean up Vertex Array Objects  

### ISSUE THREAD

**Issue by ylambda** [pixijs/pixi.js#2459]
I sent in PR #2448 to fix what looked like a simple typo. This is over my head now, so I'm going to explain the issues:

``` javascript
for (var i = 0; i < this.vaoMax; i++) {
    this.vertexBuffers[i].destroy();
    this.vaos[i].destroy();
}
```
[Source](https://github.com/ylambda/pixi.js/blob/b483372e57540f387ea28b2bc83f08b00d302454/src/core/sprites/webgl/SpriteRenderer.js#L350-L353)

This for loop is limited by `this.vaoMax`, not the true size of `this.vertexBufffers` or `this.vaos`. I believe the variable `this.vertexCount` represents the state tracking for vertexes. 

Secondly, VertexArrayObjects do not have a destroy method. I have no idea weather they should or not. If they should, this is an issue to be submitted to `pixi-gl-core`.

**Comment by GoodBoyDigital** [comment]
good shout @ylambda , we need a destroy method on VertexArrayObjects 👍

**Comment by englercj** [comment]
The loop conditions also likely need to be adjusted. Probably just want 2 loops that use the array length.
