### ISSUE TITLE
Texture.EMPTY should be not destroyable

### ISSUE THREAD

**Issue by Kouty** [pixijs/pixi.js#2460]
> An empty texture, used often to not have to create multiple empty textures.

Texture.EMPTY = new Texture(new BaseTexture());

Well, very useful, but when executing **container.destroy(true), you may destroy this EMPTY texture too**.
Shouldn't it an immutable object? Or at least not destroyable? 

I suggest to add the following line to pixi code, to fix this problem.
Texture.EMPTY.destroy = function(){};

**Comment by GoodBoyDigital** [comment]
good shout! fancy making the PR? cheers!

**Comment by ivanpopelyshev** [comment]
It is merged in dev (v4) #2464

**Comment by Kouty** [comment]
Thanks!
