### ISSUE TITLE
v4.0.0RC2 Filters ignore parents mask

### ISSUE THREAD

**Issue by Jorisslagter** [pixijs/pixi.js#2461]
I've got an container with some children. When I apply an mask to the container, it works fine. But after applying an blur filter on the children, the mask stops affecting the visibility of the children like it normally does.

With filters: http://codepen.io/DrMicra/pen/zqPyOq
Without filters: http://codepen.io/DrMicra/pen/qZVLBr

**Comment by GoodBoyDigital** [comment]
Good catch! All fixed now 👍 thanks for the fiddle, super handy!
