### ISSUE TITLE
3.0.9 Displacement filter and pixelate Filter incompatible !

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#2462]
If i add the Displacement filter and the Pixelate filter to the same sprite the pixelate will not work !

https://jsfiddle.net/6w0kuqko/5/

**Comment by D-Hartley** [comment]
If you swap the order of the filters in the array it works!

**Comment by JenGL** [comment]
yes thanks. I think a fix will be good anyway but this will solve my problem :)

**Comment by GoodBoyDigital** [comment]
looking into this now.. thanks for providing a fiddle to test 👍

**Comment by GoodBoyDigital** [comment]
fixed in v4 (dev)

**Comment by tmanderson** [comment]
@GoodBoyDigital, not sure if this ever made it to release, but the pixelate filter does not work as of v4.3.0. The current state is identical to that in the fiddle provided above.

**Comment by staff0rd** [comment]
@tmanderson is that instead possibly related to pixijs/pixi-filters#4?

**Comment by tmanderson** [comment]
@staff0rd, ah – yes, it would be! That'll do for now, thank you!
