### ISSUE TITLE
v4.0.0 FilterManager doesn't send correct textureCoords and/or projectionMatrix when applying filters

### ISSUE THREAD

**Issue by neutrino84** [pixijs/pixi.js#2466]
I'm noticing strange issues with the way FilterManager is currently working.

Please see the following test case using TwistFilter:
http://codepen.io/anon/pen/pypgOg

I'm assuming that this code is still very much in flux, so I've included a small CodePen example to aid you in the debugging process. If you'd like assistance let me know - although i'm still trying to figure out exactly how SpriteRenderer is batching and working with the FilterManager, and other managers.

**Comment by ivanpopelyshev** [comment]
Oh, wow, its a serious bug somewhere in getBounds()

**Comment by ivanpopelyshev** [comment]
Oh, and #2465 somehow is fixing it!

**Comment by ivanpopelyshev** [comment]
It was fixed there: https://github.com/pixijs/pixi.js/commit/f9d4ca12ad91efca49018c0204a283c4dc609a2d

**Comment by neutrino84** [comment]
awesome, I'm seeing it working with latest from dev -- although I think there might still be an issue, I'll investigate further, and let you know if there is soon

**Comment by neutrino84** [comment]
nevermind, all seems to be working great -- I think I understand the SpriteRenderer batching system better now --- so I need to use vFilterCoord instead of vTextureCoord :+1:
