### ISSUE TITLE
v4.0.0 Rendering a sprite that has filters to RenderTexture renders nothing

### ISSUE THREAD

**Issue by neutrino84** [pixijs/pixi.js#2469]
I think that this might be a new issue, because tests that I did last week were working (although I never tested a filter that applies transforms like TwistFilter.)

Here is a codepen example of the problem to help in the debugging process:
http://codepen.io/anon/pen/jqYZWr

If you comment out Line 28, the sprites are rendered to texture as expected. However, if you add a filter to a child sprite, the renderer fails to render the sprite with filters applied.

**Comment by GoodBoyDigital** [comment]
fixed! 👍
