### ISSUE TITLE
Possible leak with sprite's texture setter

### ISSUE THREAD

**Issue by PK-BF** [pixijs/pixi.js#2470]
When PIXI.Sprite is created without texture explicitly set, PIXI.Texture.EMPTY is used instead. While setting sprite's texture 'update' event listener is registered in texture property setter:
`if (value.baseTexture.hasLoaded)
                {
                    this._onTextureUpdate();
                }
                else
                {
                    value.once('update', this._onTextureUpdate, this);
                }`
In case of an EMPTY texture, baseTexture always has hasLoaded property set to false, so for each sprite created without texture other than EMPTY one 'update' event listener is registered.
But for an EMPTY texture 'update' event is never emitted, so the listeners array eventually keep growing in size. And along with the listener callback (Sprite.prototype._onTextureUpdate) context (sprite itself) is stored as well, keeping the reference to the sprite we might already want to be garbage collected.
Setting new (can be EMPTY) texture for the sprite does not unregister listener set for sprite's previous texture(s) - but it may be another issue.

**Comment by rybon** [comment]
Related https://github.com/pixijs/pixi.js/pull/2008.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
