### ISSUE TITLE
Clear tintCache when RenderTexture renders

### ISSUE THREAD

**Issue by serprex** [pixijs/pixi.js#2485]
I modified my fork like so: https://github.com/serprex/pixi.js/commit/32c66b071ddd65aab6085f5212ccb693af2d6073

_edit:_ doesn't seem like this does the trick, will update when I fix it
_edit2:_ I was lazy & decided to just remove tint cacheing
_edit3:_ there was misconfiguration in my cache-control parameter, my change likely works, though there's also the cachedTintTexture in the sprite renderer, going to stick with no cache tho personally

**Comment by ivanpopelyshev** [comment]
Can you create a Pull Request please? its easy :+1:

**Comment by englercj** [comment]
Is this still active in v4?

**Comment by englercj** [comment]
Can you retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!

**Comment by serprex** [comment]
My issue was fixed in my fork; opened this as an FYI

This can be closed until someone else runs into the issue

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
