### ISSUE TITLE
PIXI.BLEND_MODES.DIFFERENCE doesn't do anything (pixi.js - v3.0.10)?

### ISSUE THREAD

**Issue by dnassler** [pixijs/pixi.js#2486]
I'm trying to use PIXI.BLEND_MODES.DIFFERENCE on a PIXI.Graphics object and it seems to have no effect? Is there a trick to how to use it properly? 

```
  var graphics1 = new PIXI.Graphics();
  graphics1.beginFill(0xFFFFFF);
  graphics1.lineStyle(0);
  graphics1.drawRect(10,10,10,10);
  graphics1.endFill();
  graphics1.blendMode = PIXI.BLEND_MODES.DIFFERENCE;
  graphics1.position.set(0,0);
  stage.addChild(graphics1);

  var graphics2 = new PIXI.Graphics();
  graphics2.beginFill(0xFFFFFF);
  graphics2.lineStyle(0);
  graphics2.drawRect(10,10,10,10);
  graphics2.endFill();
  graphics2.blendMode = PIXI.BLEND_MODES.DIFFERENCE;
  graphics2.position.set(5,5);
  stage.addChild(graphics2);

```

I would expect that the overlapping section to be inverted to black since the difference between 1 and 1 is zero so the result should be zero which means black but instead I see only white where they overlap.

Am I misunderstanding something trivially simple?

**Comment by ivanpopelyshev** [comment]
There are only 4 basic blendmodes implemented in WebGL. Others are still the issue.

**Comment by Beeblerox** [comment]
sorry to interrupt, but it might be possible to achieve different blendmodes by using gl.blendEquation() and gl.blendEquationSeparate().
maybe i'm wrong since i'm only newbie with webgl

**Comment by englercj** [comment]
Probably: http://mrdoob.github.io/webgl-blendfunctions/blendfunc.html

**Comment by ivanpopelyshev** [comment]
Its |Cb - Cs|, it cant be represented as blend equation.

https://www.w3.org/TR/compositing-1/#valdef-blend-mode-difference

**Comment by englercj** [comment]
Sure, I was responding to:

>  it might be possible to achieve different blendmodes by using gl.blendEquation() 

Which, I believe, is the case.

**Comment by ivanpopelyshev** [comment]
@englercj There's no absolute value in standart blendfunction, right?

**Comment by englercj** [comment]
Not sure, I was responding with an opinion. I've done 0 research.

**Comment by ivanpopelyshev** [comment]
@xerver the only way is to implement it with filters and we have to actually use readPixels or current target rendertexture to draw new stuff upon it. The only possible advanced blendmode is "exclusion":

```javascript
gl.blendEquation( gl.FUNC_ADD );
gl.blendFunc( gl.ONE_MINUS_SRC_COLOR, gl.ONE_MINUS_SRC_COLOR );
```

It was in our plans in v4, but Its still not implemented :(

**Comment by GoodBoyDigital** [comment]
Implement it man :D

**Comment by weepy** [comment]
There's some pretty mad things u can do here : 
https://github.com/mrdoob/webgl-blendfunctions

**Comment by ivanpopelyshev** [comment]
@weepy but i want to overlaaaaay! I cannot do that with webgl blend functions! (crying)

**Comment by weepy** [comment]
Yeah - I want color-dodge !

**Comment by weepy** [comment]
maybe try :    ` glBlendFunc (GL_DST_COLOR, GL_SRC_ALPHA); // like Photoshop's 'Overlay' blending mode  `

from https://forum.openframeworks.cc/t/layer-effects-like-in-photoshop-solved/5498/2

**Comment by ivanpopelyshev** [comment]
@weepy 

![http://i.imgur.com/LupQnjy.png]

VS 

![http://i.imgur.com/2EbSIc0.png]

**Comment by weepy** [comment]
Which one you want!?

**Comment by ivanpopelyshev** [comment]
bottom is real overlay. Top one is that fake. Both dont have alpha channel.

**Comment by weepy** [comment]
For that particular style don't you just want NORMAL?

**Comment by ivanpopelyshev** [comment]
Nope. And thats not first time people want to use overlay as a blendmode in webgl.

**Comment by weepy** [comment]
yeah - but it seems you basically just can't do it ?

**Comment by ivanpopelyshev** [comment]
Got it.

http://pixijs.github.io/examples/index.html?s=picture&f=overlay.js&title=Overlay+blendMode&plugins=pixi-picture&v=

**Comment by weepy** [comment]
looks mental ? lots of mad noise textures ?

**Comment by ivanpopelyshev** [comment]
@weepy it works for me

**Comment by weepy** [comment]
I get this on Chrome OSX, Safari OSX and Chrome iPhone :-(

[image: Screen Shot 2016-05-22 at 09.45.46.png]

**Comment by ivanpopelyshev** [comment]
I dont see the image

**Comment by weepy** [comment]
Try this => http://imgur.com/yKTA0Rq

**Comment by ivanpopelyshev** [comment]
@weepy hm premultiplied alpha is off for some reason. Strange. Opaque parts are rendering correctly.

**Comment by weepy** [comment]
What are you viewing on? Also I noticed your link was just using the
default pixi version. Is that correct ?

**Comment by ivanpopelyshev** [comment]
@weepy yep. Because it's newer build than "dev"

**Comment by ivanpopelyshev** [comment]
@weepy ok, OS-X somehow disables pre-multiplied alpha by default. I dont know if thats good or not, but if its off, i need another shader for that thing

**Comment by weepy** [comment]
Ah I see. Dang.

**Comment by ivanpopelyshev** [comment]
@weepy its strange, because i see glTexture.premultiplyAlpha = true; all over the pixi code.

**Comment by ivanpopelyshev** [comment]
@weepy wait a minute, i found something

**Comment by weepy** [comment]
Hm odd. one for @goodboydigital ?

**Comment by ivanpopelyshev** [comment]
@weepy try again. I changed pixi-picture.js. Same link.

**Comment by weepy** [comment]
Same on iPhone. Tho mb something was cached. I can't tell

**Comment by ivanpopelyshev** [comment]
@weepy probably cached.

**Comment by weepy** [comment]
U could add a random number to the query string mb

**Comment by weepy** [comment]
I get the same in incognito

**Comment by ivanpopelyshev** [comment]
I think its that part:

```js
    vec4 source = texture2D(uSampler[0], textureCoord);
    if (source.a == 0.0) {
        gl_FragColor = vec4(0, 0, 0, 0);
        return;
    }
```

Somehow that if doesnt get triggered.

**Comment by weepy** [comment]
Hmmm. I can't see why. Weird.

**Comment by weepy** [comment]
Could set it anyway and see what happens?

**Comment by ivanpopelyshev** [comment]
I set it and asked friend with IPhone5 to test it. Everything is ok there.

**Comment by weepy** [comment]
Weird. It's the same in iOS Safari where I've never looked at the page.
I'll check in some other devices. This is iPhone 6plus

**Comment by weepy** [comment]
OK - So I've investigated a little. Now I find that the OVERLAY works, but
the HARD_LIGHT gives the same noisey alpha channel around the dudes.

**Comment by ivanpopelyshev** [comment]
GOOD! that means I can put same fix there too :)

**Comment by weepy** [comment]
Awesomes!

**Comment by weepy** [comment]
Can you also explain how it works ? What is a PictureSprite?

**Comment by ivanpopelyshev** [comment]
PictureRenderer in new plugin pixi-picture :)

https://github.com/pixijs/pixi-picture/blob/master/src/PictureRenderer.js#L100

**Comment by weepy** [comment]
Sweet! Do u know what performance is like?

**Comment by ivanpopelyshev** [comment]
@weepy It depends on whether current render target is screen or FrameBuffer. Screen - its slow as buck because readPixels. FrameBuffer - I think its the same degree as canvas2d drawImage.

**Comment by weepy** [comment]
Is that what the VoidFilter hack is doing? Worth trying a bunny mark ?!

**Comment by ivanpopelyshev** [comment]
@weepy Bunny mark wont show good points for that. I assume that overlay will be used on big pictures that will create lighting across your map.

**Comment by ivanpopelyshev** [comment]
Normal, (FrameBuffer,screen), 100k bunnies: 27FPS

**Comment by weepy** [comment]
Pretty nice. I guess I should benchmark my specific usecase. Are other
blendmodes like colour dodge possible with a similar approach ?

**Comment by ivanpopelyshev** [comment]
@weepy everything: https://www.w3.org/TR/compositing-1/#blendingdarken

I also want to make displacement filter on that, it will be easier to use, because it will actually affect already drawn game map

**Comment by weepy** [comment]
That would be awesome. What would you want to do with a displacement filter
?

**Comment by ivanpopelyshev** [comment]
Current one is not that easy to use. 
You have to create Sprite, yes, but filter must be assigned to its parent, and it will redraw whole screen with it. Add like 10 displacements and we'll have 10 copies of screen flip-flopping. My approach copies only sprite area to temporary buffer, that's faster, and you dont have to manage filters of gamemap, just assign a filter to sprite.

**Comment by weepy** [comment]
Sounds perfect

**Comment by weepy** [comment]
I tried again - it seems to be all fixed now ! Did you change something ?

**Comment by weepy** [comment]
Hi @ivanpopelyshev. Would your plugin work for instance if I had a container with multiple sprites in. I want the sprites to be rendered normally and then the entire layer be rendered with Hardlight. Thanks!

**Comment by ivanpopelyshev** [comment]
@weepy no, I didnt implement that yet

**Comment by weepy** [comment]
Awesome ! Look forward to seeing it. It will be really useful for getting
that "pro" looking effect.

**Comment by weepy** [comment]
Ivan did you make any progress with the blend modes? I'd love to use
overlay on a container :)

**Comment by ivanpopelyshev** [comment]
@weepy Im working on 3D stuff currently, and I have a number of big tasks before I get back to overlay.

**Comment by weepy** [comment]
Ok sure I understand. Do you think it's something that you will get to or
perhaps not?

**Comment by ivanpopelyshev** [comment]
@weepy that is what I made: https://gameofbombs.github.io/pixi-bin/

**Comment by weepy** [comment]
Really nice ivan! Are you going to use it for game of bombs ?

**Comment by GoodBoyDigital** [comment]
closing as this has a duplicate 👍
