### ISSUE TITLE
Render Warning on v4

### ISSUE THREAD

**Issue by robotlabs** [pixijs/pixi.js#2495]
Hey there on one of my macbook (2013) i get this WARNING, when trying to render a sprite, on a webGL renderer. The sprite is preloaded, through PIXI.loader

( on Chrome 50.0.2661.66 beta )
[.CommandBufferContext]RENDER WARNING: there is no texture bound to the unit 1  ( 2, 3, .. )

I don't get this warning with my latest macbook, or if i use v3.0.2
Any idea ? 
All assets are preloaded

**Comment by stbaer** [comment]
Same with latest codova/webview.

**Comment by GoodBoyDigital** [comment]
Pretty strange that one! If you could provide an example of the issue we can look to debug for ya. Cheers!

**Comment by rensrongen** [comment]
I get the same warning when running my project on Win7 x64 with Pixi v4 on Chrome(50+). Didn't have this issue with v3.

It appears to happen when rendering Text.
I can replicate this with the following steps:
 - Autodetect renderer.
 - Create PIXI.Text.
 - Render scene.

The errors don't show up in Firefox or IE.

Also, my project does not render properly on my Galaxy S4 on Chrome mobile with Pixi v4. (text glitches) It didn't have this problem with Pixi v3. Perhaps this issue is related.

I'll be able to provide an example later today if needed.

**Comment by GoodBoyDigital** [comment]
example would be ace! Just so I can ensure the set up matches you own. Cheers!

**Comment by rensrongen** [comment]
This example will trigger the warnings for me:
https://github.com/rensrongen/experiments/blob/master/index.html

**Comment by GoodBoyDigital** [comment]
Hello! Can you try again with the latest dev branch please? cheers!

**Comment by rensrongen** [comment]
The latest dev branch did not solve the issue unfortunately.

On a side note, I did notice that 'texture.wrapMode' is 'undefined' by default. Changing it to CONST.WRAP_MODES.REPEAT fixed a problem with Seamless textures in my game being mirrored. Perhaps an idea to set it to REPEAT by default, as this appears to have been the case with v3.

**Comment by bQvle** [comment]
Its also a problem in this Example (check console in Chrome)
http://pixijs.github.io/examples/index.html?s=basics&f=click.js&title=Click&v=dev-4.1.0

**Comment by weepy** [comment]
i get this too. seems like Pixi 4 is broken out of the box ?

**Comment by GoodBoyDigital** [comment]
should be all fixed now in the dev branch. Thanks for sharing! 👍

**Comment by robotlabs** [comment]
Sorry for the delay. Yes. that fixed the problem! thanks a lot

**Comment by LucianoGraziani** [comment]
I'm having a similar warning:

>> [.CommandBufferContext.Offscreen-MainThread-000001E0587B00B0]RENDER WARNING: there is no texture bound to the unit 1 (2, 3, ....)

- PIXI version: v4.0.0-rc2
- It can be reproduced with the above example (https://github.com/rensrongen/experiments/blob/master/index.html).

**Comment by englercj** [comment]
@LucianoGraziani Does it reproduce in the latest dev builds?

**Comment by LucianoGraziani** [comment]
Now that you mention it, no. http://codepen.io/lgraziani/pen/PzERNB?editors=0010
I used the same build that Ivan Popelyshev gave me for #2725 (who was a PIXIv3 error) and wasn't that warning.

Thank you.

**Comment by Good4m** [comment]
Im getting this warning right now with latest dev build

**Comment by samvieten** [comment]
confirmed: Getting the same warning with latest dev build. 
By setting Pixi.Loader.add(texture) and applying it to a sprite.
