### ISSUE TITLE
PIXI v3 - WebGL warning error for baseTexture

### ISSUE THREAD

**Issue by LucasBertrand** [pixijs/pixi.js#2498]
Here is my code : 

    var img = new Image( 64, 64 );

    var baseTexture = new PIXI.BaseTexture( img, PIXI.SCALE_MODES.DEFAULT, 1 );

    var texture = new PIXI.Texture( baseTexture );

    var filter = new CustomFilter(); 

    var sprite = new PIXI.Sprite( texture );

    sprite.shader = filter;

This seemly works but i've got this error :

"WebGL: INVALID_VALUE: texImage2D: no image"

Maybe I misunderstand something ? Thanks !

**Comment by englercj** [comment]
`var img = new Image( 64, 64 );`

You created a blank (empty) image container. WebGL is warning that there is nothing to draw, because nothing exists (you didn't assign a `src`).

**Comment by GoodBoyDigital** [comment]
correct! 👍
