### ISSUE TITLE
iOS SVG MovieClip doesn't clear stage

### ISSUE THREAD

**Issue by gurmukhp** [pixijs/pixi.js#2499]
Hi All,

I have 23 SVGs which I'm putting into a MovieClip and then animating on a Canvas. The example works fine on Android and all desktops but on iOS, each frame is not being cleared before the next one is drawn. I've noticed that if I force the CanvasRenderer then the problem disappers (but performance is pretty bad), but on WebGL, it's super quick but leaves a kind of ghosting effect:

**WebGL**
![simulator screen shot 13 apr 2016 16 06 35](https://cloud.githubusercontent.com/assets/899769/14498283/bb98d1fa-0191-11e6-8bc2-b96a285ae526.png)

**Canvas**
![simulator screen shot 13 apr 2016 16 10 27](https://cloud.githubusercontent.com/assets/899769/14498418/444e9318-0192-11e6-8256-20b085526fc6.png)

This is my simple code:

```
var renderer = new PIXI.WebGLRenderer(1000, 1000, {
  resolution: 1,
  view: document.getElementById("stage"),
  backgroundColor: 0xffffff,
  antialias: false
});

// create the root of the scene graph
var stage = new PIXI.Container();

// Smoother graphics on iOS
var o1 = new PIXI.Graphics;

o1.position.x = 0;
o1.position.y = 0;
o1.beginFill(0x000000);
o1.drawRect(0, 0, 800, 800);

stage.addChild(o1);

var explosionTextures = [], i;

for (i = 0; i <= 23; i++) {
var index = (i < 10) ? '0' + i : i;
   var texture = PIXI.Texture.fromImage('/speed-test-web/girl/girl_comp_000' + index + '.svg');
   explosionTextures.push(texture);
}

var explosion = new PIXI.extras.MovieClip(explosionTextures);
explosion.gotoAndPlay(1);
explosion.animationSpeed = 0.5;

stage.addChild(explosion);

requestAnimationFrame(animate);

function animate() {
    renderer.render(stage);
    requestAnimationFrame(animate);
}


```

**Comment by ivanpopelyshev** [comment]
iOS clear bug, not related to SVG, we had solution somewhere. Can you try it on https://github.com/pixijs/pixi.js/blob/dev/bin/pixi.js ?

**Comment by gurmukhp** [comment]
Thanks for the prompt reply, I'll give it a go and report back.

**Comment by gurmukhp** [comment]
It works! Do you know when this push will be made to the production build?

Thanks

**Comment by ivanpopelyshev** [comment]
@gurmukhp its pixi version 4, pre-releases arent published in npm yet: https://github.com/pixijs/pixi.js/releases 

You can use github repo link in npm instead of its version.

**Comment by gurmukhp** [comment]
We're looking to use this in a project that is going to be live around July time, do you think v4 would be promoted from the dev channel to a 'latest release'?

**Comment by ivanpopelyshev** [comment]
@gurmukhp Im sure. I believe v4 is already stable enough.

**Comment by gurmukhp** [comment]
Apologies, I just checked my code and it was forcing the CanvasRenderer, when using the WebGLRenderer, the bug is still there.

**Comment by englercj** [comment]
Closing since this should be fixed in latest v4 now.
