### ISSUE TITLE
PIXI.extras.MovieClip, re-using MovieClips and changing the width and height.

### ISSUE THREAD

**Issue by rlthomasgames** [pixijs/pixi.js#2500]
Hi, firstly well done on the PIXI.js code base :) , its very cool!

However I believe I have found an issue with the width and height setters and getters that are used from Sprite within the MovieClip class, as they are not extended or perhaps you can advise as to how to use them correctly.

I am currently creating 5 MovieClips and storing them in an array so that they can be re-used by changing the 'texture' property when required too, however the issue I see is that if I also change the width and height when re using them, the first time I attempt to change the width and height, width and height is actually acting as a scale property as it reports 1 and if I change that 1 to a 2 it doubles in size, even though the size of the textures that are being used are 140x140, so they become 280x280.
**_This is one issue why does width and height act like scale the first time you use it?_**

 Then when I attempt to re-use them a second time and need to change the width and height it no longer acts as scale and acts as a width and height as it should, so whilst I would normally pass it a scale or 1, now the movieclips become 1x1 pixels.
When I asked for the width and height it had reported to me that it was 140x140 rather than the scale value of 1x1 that I got last time.
**_This is a secondary issue to the first issue_**

There are some inconsistencies with the width and height getter's and setter's no?

I believe this to be because they were not overwritten from Sprite class, I guess the 'texture' property is not set until the first update is run or a gotoAndStop is called.

However when first creating the sprites on very first creation i pass an array of textures and I attempted to run gotoAndStop(1); straight afterwards, which should set the _texture property for the Sprite class to properly inspect, I should now be able to get the width and height correctly, but im afraid not, instead I get......

**Sprite.js Uncaught TypeError: Cannot read property '_frame' of undefined**

.....this is being thrown from the line of code within the Sprite classes width or height getter, or even setter, I can only guess this.texture has still not been set yet?
**_This was the third piece of info i wanted to supply_**

Is there any advice on this issue, perhaps I am doing something wrong? or perhaps this needs to be fixed?

And feedback would really help, I currently need to create a hack around it and its not very nice code.

Thanks again for your time and any feedback and really well done again on the library, its nice to have flash back in HTML5 :)

cheers all!
Rhys Thomas

**Comment by rlthomasgames** [comment]
Errm I must have had my head up my arse because all seems to be working now, i thinking it was to do with creation of MovieClips nested with in a few for loops, i moved stuff around and all seems to work okay for me now, sorry to trouble you with this issue, you can close probably!

Thanks again :)
Rhys Thomas

**Comment by GoodBoyDigital** [comment]
👍
