### ISSUE TITLE
Texture TrimColor/BackgroundColor

### ISSUE THREAD

**Issue by FabianElsmer** [pixijs/pixi.js#2501]
Hey guys,
when you normally use texture.trim, it adds a padding to the texture so that it is positioned and sized in the same way as before trimming the excess transparent space off the original image.
It would be nice, however, to also be able to trim off other colors than fully transparent ones, and get the texture to display the same way the original image would.

I think the most straight forward way to realize this, is to add a backgroundColor or trimColor to the texture and let the WebGL/CanvasRenderer draw some rectangles.
It might be something you could add to v4, since Trim/Crop are getting reworked a bit afaik.

**Comment by ivanpopelyshev** [comment]
I think that's possible if @GoodBoyDigital approves my #2465 and it will required some tinking after. That way all that logic wont appear over all pixi (ParticleRenderer, CanvasSpriteRenderer) but only in one place
