### ISSUE TITLE
MovieClip frame bug

### ISSUE THREAD

**Issue by leafx** [pixijs/pixi.js#2504]
![QQ20160414175357.jpg](http://imgchr.com/images/QQ20160414175357.jpg)

```java
var frames = [];
for (var i = 0; i < 30; i++) {
  frames.push(PIXI.Texture.fromFrame(i + '.jpg'));
}
movie = new PIXI.extras.MovieClip(frames);
movie.animationSpeed = 0.5;
movie.play();
```

All on android device & same codes.

**Comment by whizzkid** [comment]
Please describe the problem. 
We have no idea what the movieclip should look like, so these screenshots don't really add much at the moment.

**Comment by GoodBoyDigital** [comment]
closing as this is a little vague! 👍
