### ISSUE TITLE
PIXI.Text width/height setter is broken

### ISSUE THREAD

**Issue by Lodin** [pixijs/pixi.js#2505]
When I set width or height of the text, it becomes very small until I call `updateText()` method before size setters.
[Example](https://jsfiddle.net/Lodin/yvk256L1/8/)

I think it can be connected to the #2376.

OS: Windows
Browser: tested in Chrome dev 51, Firefox 45

**Comment by ivanpopelyshev** [comment]
Is that in pixiv3? 

Related PR in v4: https://github.com/pixijs/pixi.js/pull/2488

**Comment by themoonrat** [comment]
Changing your and another example to this version
https://rawgit.com/themoonrat/pixi.js/text-setting-max-width-and-height/bin/pixi.js
Seems to fix the issue. All i do is call updateText if dirty automatically within the setters for text width and height. That code was already in the getters, so it seems reasonable to do. Have a branch ready, but it's another PR on the Text that already has a few on it with major potential changes!

**Comment by Lodin** [comment]
@themoonrat Yes, it is the way I have solved it by now, but I wish there would be some more elegant solution. Unfortunately, I cannot use v4.0 until it remains unstable, so I can only wait for final release.
