### ISSUE TITLE
getCachedBounds should use the identity matrix

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#2506]
Sorry but I do not have time to make a clean PR (I do not use git on a daily basis so it always takes me half an hour to make it work) but we found and fixed a bug in the cacheAsBitmap feature.

When you calculate the width and height of a cached container, the values are wrong because the cached sprite multiply its bounds by the worldtransform matrix. It shouldn't.

How to fix : 

````javascript
/**
* Calculates the bounds of the cached sprite
*
* @private
*/
DisplayObject.prototype._getCachedBounds = function ()
{
    this._cachedSprite._currentBounds = null;

    return this._cachedSprite.getBounds(core.math.Matrix.IDENTITY);
};
```

at https://github.com/pixijs/pixi.js/blob/master/src/extras/cacheAsBitmap.js#L252

Regards.

**Comment by ivanpopelyshev** [comment]
Offtopic. So glad you're here! Do you want to join our team slack?

**Comment by englercj** [comment]
Merged, thanks as always @JiDW  and @ivanpopelyshev.
