### ISSUE TITLE
IE Edge fails to display SVG on a Canvas [UPDATE: Now with JS Fiddle]

### ISSUE THREAD

**Issue by gurmukhp** [pixijs/pixi.js#2510]
For some reason, when loading in a SVG on IE Edge, nothing shows. I can see in the log that the images are being loaded in. When trying it on IE 9 or 10, it works perfectly fine (but gives an error in the console).

I've tried loading in an external image and also inlining it, but having the same problem.
https://jsfiddle.net/vwzjzn4h/1/

Here is an example of the same SVG loaded into a Canvas in IE Edge with no errors:
http://jsfiddle.net/gurmukh/wzsz45g4/

Is this is a known issue or is there any working example on Edge I can look at?

Thanks!

**Comment by rbndelrio** [comment]
This also seems to be a problem in firefox.

**Comment by englercj** [comment]
Had lots of suggestions improvements made in the most recent dev branch can you try again with the latest dev build?

**Comment by RanzQ** [comment]
I think there is a problem with SVG images when creating textures before the `'loaded'` event.
