### ISSUE TITLE
V4 - Tint isn't working for TilingSprite

### ISSUE THREAD

**Issue by bQvle** [pixijs/pixi.js#2512]
Try adding Tint to this example

http://pixijs.github.io/examples/index.html?s=basics&f=tiling-sprite.js&title=Tiling%2BSprite&v=v3.0.11

And do the same with v4

As a side-request it would be great if it was possible to add Tint to Mesh objects (Rope etc).

**Comment by GoodBoyDigital** [comment]
All sorted now! Thanks for sharing the issue! 👍
