### ISSUE TITLE
Glitch with MeshShader

### ISSUE THREAD

**Issue by shanemccartney** [pixijs/pixi.js#2513]
Hi we have been working on a small HTML5 game and noticed that because of the precision value used on iPad meshes will glitch with a jittery effect. This can be corrected by changing lowp to mediump as seen below. It would be best to update this into the source code to stop this effect appearing with the use of complex Meshes in our case the mesh was for a procedurally drawn ground.

```
function MeshShader(shaderManager)
{
    core.Shader.call(this,
        shaderManager,
        // vertex shader
        [
            'precision mediump float;',
            'attribute vec2 aVertexPosition;',
            'attribute vec2 aTextureCoord;',

            'uniform mat3 translationMatrix;',
            'uniform mat3 projectionMatrix;',

            'varying vec2 vTextureCoord;',

            'void main(void){',
            '   gl_Position = vec4((projectionMatrix * translationMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);',
            '   vTextureCoord = aTextureCoord;',
            '}'
        ].join('\n'),
        [
            'precision mediump float;',

            'varying vec2 vTextureCoord;',
            'uniform float alpha;',

            'uniform sampler2D uSampler;',

            'void main(void){',
            '   gl_FragColor = texture2D(uSampler, vTextureCoord) * alpha ;',
            '}'
        ].join('\n'),
        // custom uniforms
        {
            alpha:  { type: '1f', value: 0 },
            translationMatrix: { type: 'mat3', value: new Float32Array(9) },
            projectionMatrix: { type: 'mat3', value: new Float32Array(9) }
        },
        // custom attributes
        {
            aVertexPosition:0,
            aTextureCoord:0
        }
    );
}
```

**Comment by ivanpopelyshev** [comment]
May be its better to change lowp to mediump everywhere. Its not supported on some of devices

**Comment by GoodBoyDigital** [comment]
Thanks for sharing man! What do people think, should we let it be a dynamic thing? eg:

```precision %PRECISION% float;```

That way we could store a const in pixi for low/medium/high to automatically populate it as required under the hood with:

 ```shaderSrc.replace('%PRECISION%', Const.PRECISION.DEFAULT);```

**Comment by ivanpopelyshev** [comment]
I remember that @JiDW discussed that problem too

**Comment by JiDW** [comment]
Yes, indeed. We haven't found any performances issues either when we switched to mediump but we didn't run a benchmark, only tested our app.

A lot of low end devices on Android can't deal with lowp. That's why some people say that PIXI doesn't work on their mobile.

**Comment by JiDW** [comment]
https://github.com/pixijs/pixi.js/issues/2147

**Comment by ivanpopelyshev** [comment]
#2520

**Comment by GoodBoyDigital** [comment]
fixed! 👍
