### ISSUE TITLE
missing var in 4.0

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#2515]
seems like this line at ~ 1074 in pixi.js v4 is missing "var"

```compileProgram = function(gl, vertexSrc, fragmentSrc)
```

**Comment by weepy** [comment]
is no one else having this problem?

its imported from `pixi-gl-core/lib/shader/compileProgram.js`, but I'm not sure why the `var` goes walkabout .

**Comment by englercj** [comment]
Did you see that @ivanpopelyshev submitted a PR that should have fixed this?

**Comment by ivanpopelyshev** [comment]
@weepy its in pixi-gl-core, you have to npm udpate it or whatever.

**Comment by weepy** [comment]
aaah i see. I was just using the prebuilt file  in bin/pixi.js
