### ISSUE TITLE
Wrong mouseout event fired after click of Container

### ISSUE THREAD

**Issue by usmjc** [pixijs/pixi.js#2521]
Hi !
I have an interactive Container, holding my buttons in a game. These buttons has different sprites for various states like : 'up','down','over' etc.

My problem seems to be that after a click of the Container a mouseout event is fired as well. See attached screenshot. Seems like pixi's hit-test doesn't apply properly to Containers.

Anyone seen anything similar ? 

To work around it, I have my own hit-detection routine in place, but obviously I think this is a bug.
`        container.mouseout = function(mouseData) {

```
        //hittest required to circumvent pixi.js's erroneus firing of mouseout on clicks
        if(!containsPoint(mouseData.data.global, container)) {
            showFrame((active) ? frameId('up') : 'inactive');
        }
    };
    function containsPoint(point,container) {
        if(!point || !container) return;
        var cp = container.getGlobalPosition();
        if(point.x < cp.x || point.x > cp.x + container.width) return false;
        if(point.y < cp.y || point.y > cp.y + container.height) return false;
        USM.log("point:"+JSON.stringify(point)+", container topleft:"+JSON.stringify(cp)+
                " container size:"+container.width+"x"+container.height);
        return true;
    }
```

`
Running :     Pixi.js 3.0.7 - WebGL 

![pixi-wrong-fire-mouseout](https://cloud.githubusercontent.com/assets/6818117/14675668/61ece488-070a-11e6-8ac8-174f756e492a.PNG)

**Comment by JiDW** [comment]
Yes indeed, same behavior here. We switched our events to mouseupoutside, it's not the same event but at least it works on containers, and it's touch friendly (touchout doesn't exist, touchendoutside does)

**Comment by FNevesFMQ** [comment]
Any news about this?
I'm using v4.7.1 and seems that it still occurs

**Comment by themoonrat** [comment]
Could you put together a fiddle demonstrating this please @FNevesFMQ ?
