### ISSUE TITLE
Unexpected gap between rectangles in canvas renderer

### ISSUE THREAD

**Issue by stanislaw89** [pixijs/pixi.js#2524]
Hi, when two rectangles placed side by side and they are translated by 0.5 an unexpected gap appears if canvas renderer is used.
WebGL version: http://jsfiddle.net/sten/azpgswgz/1/  (OK)
Canvas version: http://jsfiddle.net/sten/80qk6gz9/1/  (BUG)
 
Do you have any idea how to work around it?

**Comment by izar89** [comment]
The gap you see is a "half pixel". Avoid floating points when drawing to the canvas.
graphics.x = 0.5; --> 0 
graphics.y = 0.5; --> 0

**Comment by ivanpopelyshev** [comment]
Yeah, Fill mode works differently on canvas and webgl. I think that canvas is taking line (lineWidth) into the square, while WebGL doesnt.

**Comment by GoodBoyDigital** [comment]
Think this is just the nature of the beast im afraid! Most people use WebGL now :)
