### ISSUE TITLE
Blur filter/(shader) texture not clearing? (V4-dev)

### ISSUE THREAD

**Issue by izar89** [pixijs/pixi.js#2526]
When I use the blur filter alone it works fine, but when using it in combination with another filter the input texture does not reset/clear. For convenience I used 2 blur filters but the same happens with other combinations.

**1 blur filter**
![image](https://cloud.githubusercontent.com/assets/767371/14760949/ff930746-0951-11e6-89c6-9dc2bbb9fb7f.png)
https://jsfiddle.net/n8aqqf85/
**2 blur filters**
![image](https://cloud.githubusercontent.com/assets/767371/14760952/0aea4fbe-0952-11e6-8696-8c5c215d99b6.png)
https://jsfiddle.net/n8aqqf85/3/

**Comment by MrAnyone** [comment]
are you using graphics.clear()?

https://pixijs.github.io/docs/PIXI.Graphics.html#clear

**Comment by izar89** [comment]
No, I think there's something wrong with the new blur filter in pixi.js v4 (which is still in development).
This is an example that uses V3.011 and the same code: https://jsfiddle.net/izar/91acdthy/3/. When I use multiple filters in V4 and the blur filter is the first one added something goes wrong.

**Comment by GoodBoyDigital** [comment]
Hi @izar89 ! Just pushed some changes to the dev branch that should fix the issue! Let me know how it goes 👍

**Comment by izar89** [comment]
@GoodBoyDigital Fixed! Thank you! 
One thing I noticed (me nitpicking :d) with the new filter is that it cuts off the bottom and right border of the canvas when blurring (https://jsfiddle.net/izar/mumxuzk6/1/) but the blur results are much better.
