### ISSUE TITLE
After Texture.destroy the creation of an second Texture from same URL fails

### ISSUE THREAD

**Issue by martenrichter** [pixijs/pixi.js#2527]
Dear Pixi Team!
Thanks for the wonderful lib!
I have the following problem. If a texture was destroyed with the destroy method is not removed from TextureCache (can happen with destroy(true) from a Container containing a Sprite).
If you then try to create a second Sprite or Texture from the same URL, you have a Texture object with a null BaseTexture, since the old destroyed object is still in the Cache.
I suggest the following changes in BaseTexture.destroy() change:`delete utils.TextureCache[this.imageUrl];` to `if (utils.TextureCache[this.imageUrl]) delete utils.TextureCache[this.imageUrl];` .
Furthermore add to Texture destroy method:
`if (this.baseTexture.imageUrl) delete utils.TextureCache[this.baseTexture.imageUrl];` after the destroyBase ifclause but with in the this.baseTexture ifclause.

Marten

**Comment by ivanpopelyshev** [comment]
There are two caches, TextureCache and BaseTextureCache, am I right? Does the problem persists if you actually use async loader?

**Comment by martenrichter** [comment]
Actually the problem is that the Texture in TextureCache is destroyed and has a baseTexture element set to null. Also other elements are set to zero and it is not working anymore. The baseTextureCache element is still working. So it is probably working, if you create a texture object with new and get a BaseTexture element with fromImage. Anyway, every method in Texture using the TextureCache does not work, since baseTexture element and others are set to null. 
Actually I am not sure which code the async loader is. Also I did not see any deprecated marks in the fromImage function in git.

**Comment by martenrichter** [comment]
So new PIXI.Texture(PIXI.BaseTexture.fromImage(pictinfo.url)) works without modification in PIXI.
Only the Texture fromImage and related creation methods are affected.

**Comment by englercj** [comment]
If a texture is destroyed it should be also removed from the texture cache (same for base Texture). If that is not happening, please provide a reproduction case.

**Comment by martenrichter** [comment]
Well here is a stub that reproduces the error https://jsfiddle.net/dacfxe5s/ .(It does not show anything just throws the right error).
But it is basically the error you describe. But it also occurs in v4, see the jsfiddle.
The error is the "Unable to get property 'hasLoaded' of undefined or null reference" message.

**Comment by englercj** [comment]
Yup it is not fixed in v4, feel free to put in a PR with the fix I described:

> Just need to remove the line in BaseTexture that does delete utils.TextureCache[this.imageUrl]; and move it into Texture#destroy so texture removes itself properly.

**Comment by GoodBoyDigital** [comment]
closing as this is fixed in v4 👍
