### ISSUE TITLE
Container.generateTexture Issue

### ISSUE THREAD

**Issue by davearel** [pixijs/pixi.js#2531]
I'm having a strange issue with `container.generateTexture()`

I'm loading several base64 images into the loader (which works fine). In the resource loader callback, I am able to render these to sprites no problem.

However, if I try and combine these sprites into a group and generate a texture from that group, It won't render unless I do so after some middleware code in the loader. The way I've been able to do this is by setting a timeout so that it skips it until after the middleware is done loading. How can I get around this? I imagine it will cause issues at some point.

```javascript
   // Inside resource loader callback
   // loader.load(callback);

   // Create container, add sprites
    var container = new PIXI.Container();
    container.addChild(left);
    container.addChild(right);
    container.addChild(middle);

    // Create new sprite & texture
    var sprite = new PIXI.Sprite();
    window.setTimeout(function() {
      var texture = container.generateTexture(engine.renderer);
      sprite.texture = texture;
    }, 1);

```

Is there an event or method I could use to fire this code after everything is loaded and the middleware has finished?

**Comment by englercj** [comment]
I'm not sure I follow, the loader callback doesn't run until middleware has completed running.

**Comment by izar89** [comment]
@davearel Take a look at the following example https://jsfiddle.net/o6pgq628/1/ .
I think it wil help you solve your problem :).

**Comment by davearel** [comment]
@izar89 Thanks. This helped me realize my issue.

I believe the problem is that my base64 is an `image/svg+xml` type. When I run this through the loader, I'm not returned a texture.

Instead, I'm doing this:
```javascript
var left = new PIXI.Sprite( PIXI.Texture.fromImage(resources.left.url )); 
```

I'm essentially loading the resource twice. Shouldn't the loader return me a texture?

@englercj Is this a bug in resource-loader?

**Comment by englercj** [comment]
Could be, fork [resource-loader](https://github.com/englercj/resource-loader) and write a test that reproduces the problem. A PR with a failing test is really helpful for tracking down issues.

**Comment by davearel** [comment]
@englercj thanks for the info, that did it. I've submitted a pull request to https://github.com/englercj/resource-loader/pull/52

Thanks!

**Comment by GoodBoyDigital** [comment]
closing for now as not a pixi issue. thanks all!
