### ISSUE TITLE
one place to check pixi v4 status

### ISSUE THREAD

**Issue by markmarijnissen** [pixijs/pixi.js#2533]
Context:
I've tried out the Pixi v4 branch. Apart from some slight API changes (e.g. Pixi.POINT didn't have the clone method anymore), I received a bunch of WebGL errors. Seems as if pixi v4 is not quite ready yet.

Problem:
I have no idea about the status, progress and stability of V4

Proposition:
- Use milestones to tag all relevant issues with v4. 
- Inform users of status (stability, todo) in README.md of the v4 branch

**Comment by bigtimebuddy** [comment]
V4 is still a work in progress, but we're working hard to increase the stability as we get closer towards a release. It's not recommended yet to use v4 or the **dev** branch in a production setting. Also, we have not yet announced a release date for V4, but we hope it will come very soon.

Currently, we're looking at improving stability in other ways, such as improving automated test coverage. Utilizing milestones is also a good suggestion too.

Pixi.js is supported largely by the free-time of professional and amateur developers. Sometimes the process can be a little chaotic. We're all doing our best. I would strongly encourage you to please file [your separate issues](https://github.com/pixijs/pixi.js/blob/master/CONTRIBUTING.md#reporting-issues) about the WebGL errors and PIXI.Point.clone. That'd be helpful to have those properly captured.

Thanks for the comments @markmarijnissen.

**Comment by markmarijnissen** [comment]
I know how hard it is to main work on this projects in free time - I fail to maintain some repositories which I regret.

I'll file the issues and in the meanwhile, I'll keep an eye on the issues and announcements.

Thanks for all the good & hard work! Much appreciated :).

I'll close this issue to reduce clutter.
