### ISSUE TITLE
V4 Extract Issue?

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi.js#2534]
There is something a little weird about these 2 classes. 

- `extract/webgl/WebGLExtract.js` Is a class of `Extract` whereas I would expect it to be `WebGLExtract`
- `extract/canvas/CanvasExtract.js` Is a class of `WebGLExtract`.

To me, the contents of each of these needs switched around with the `Extract` becoming `CanvasExtract`.

**Comment by clark-stevenson** [comment]
It is also not overly clear on the `pixels` method.  The docs say `DisplayObject | RenderTexture` and if this is the case, should be parameter name `target` for consistency. Otherwise update Doc. 

`Extract.prototype.pixels = function ( renderTexture )`

I know v4 is in dev, so I am not sure how helpful these tickets are but figure be as well capturing any odd observations.

**Comment by GoodBoyDigital** [comment]
Good catch @clark-stevenson 👍 all fixed!
