### ISSUE TITLE
Sprite flicker

### ISSUE THREAD

**Issue by alphawolf1988** [pixijs/pixi.js#254]
Hey there,

i,ve a problem with moving my sprites around. I've some really slow sprite movements (position.x += 0.1 per second) and because of this, my sprites flicker on teh edges while moving. If i cust move by 1 pixel everithing works fine. Is there anny way to solve this problem or is it a requirement that a sprite needs to move at least 1 pixel per second?

Kind regards

**Comment by anormore** [comment]
var renderer = PIXI.autoDetectRenderer(window_width, window_height,{backgroundColor : 0x000000, resolution:1, autoResize:true, antialias: true, transparent: true});

Set autoResize:true to fix the problem automatically. I paseted my fulle code.
