### ISSUE TITLE
documentation: resolution is not clearly pixel ratio

### ISSUE THREAD

**Issue by Hachitus** [pixijs/pixi.js#2541]
One thing caught my eye, in actually two situations. For me pixelRation would be much more clear than resolution. What I mean is this: https://pixijs.github.io/docs/PIXI.BaseTexture.html#resolution

There also was one stackoverflow question, where somebody was using resolution in another way, which is quite normal assumption (width * height): http://stackoverflow.com/questions/36355140/calculate-resolution-of-sprite-texture-in-pixi-js/36409111#36409111

I am not all that familiar with webGL / openGL, but I think the term resolution is used there and that's where the usage comes from? But I don't think it's clear for all the regular users.

Obviously changing the name in any case would not be wise at this point. But if you agree, I can go through, add explanations / documentation regarding it and PR it.

**Comment by GoodBoyDigital** [comment]
Please do @Hachitus ! Resolution was initially chosen as it was the term used by non web based 2d render engines ( specifically cocos2d from back in my ios dev days! ). If you could help by making it clear to others how it works that would be fantastic for the engine! 👍

**Comment by GoodBoyDigital** [comment]
@Hachitus poke :)

**Comment by Hachitus** [comment]
Yes, I know and I'm ashamed :(. This was a really bad moment for me as overwatch + family events have taken my time :). I hope this is not in a hurry? If it isn't I will most likely start on this next week and I will TRY to find some other useful things to do too :).

**Comment by GoodBoyDigital** [comment]
closing for now. @Hachitus if ya get a chance to look at this that would be ace. 👍
