### ISSUE TITLE
v4 mask not working properly on mobile devices.

### ISSUE THREAD

**Issue by vapesolius** [pixijs/pixi.js#2545]
Hello,
I'm using mask in next way:

```
        private addMask():void {
            this.bonusMask  = new PIXI.Graphics();
            this.bonusMask.isMask = true;
            this.bonusMask.interactive = false;
            this.bonusMask.hitArea = new PIXI.Rectangle(0,0,0,0);
            GAME.components.mainScreen.addChild(this.bonusMask);
            this.bonusMask.position.x = this.view.x;
            this.bonusMask.position.y = this.view.y;
            this.bonusMask.width = 880;
            this.bonusMask.height = 577;
            this.bonusMask.lineStyle(0);
            this.bonusMask.beginFill(0x000000, 1);
            this.bonusMask.drawRect(0, 0, 880, 577);
            this.view.mask = this.bonusMask;

        }
```
in desktop browsers everything works good but on mobile devices mask doesn't shows properly
Mobile version: https://www.dropbox.com/s/pgj9anipuuhcf8u/Screenshot%202016-05-02%2011.54.12.png?dl=0
Desktop version: https://www.dropbox.com/s/p2hat74de0muv9j/Screenshot%202016-05-02%2011.53.25.png?dl=0

**Comment by GoodBoyDigital** [comment]
hello!
if you add the line:

```this.bonusMask.rotation = 0.01```

does the mask work ok? This is more of a test than a fix!

**Comment by vapesolius** [comment]
Hi,
if add rotation mask work ok!

**Comment by GoodBoyDigital** [comment]
cool, is the mobile version running at a resolution of 2?

**Comment by vapesolius** [comment]
what you mean ?

**Comment by vapesolius** [comment]
iPad3-4, android galaxy s6 full screen

**Comment by GoodBoyDigital** [comment]
if you log the resolution of the renderer:
```console.log( renderer.resolution ) ```

**Comment by vapesolius** [comment]
different results on different devices
ipad 2
galaxy s6 4
but also can be 3, 3.26, 2.6

**Comment by SlawomirMazgaj** [comment]
I just got it as well. Latest v4 from dev branch. Rotating by 0.01 is helping as well.
WebGL - resolution 2
I'm able to reproduce this one on google Chrome using device emulation and setting 4K resolution (1920x1080 - desktop).

**Comment by ivanpopelyshev** [comment]
Masks can be either rectangle (SCISSOR) and generic (STENCIL). If rotations works, that means SCISSOR is not working, look inside MaskManager

**Comment by SlawomirMazgaj** [comment]
Not sure if that's gonna help anyhow but I'm doing:
```
_maskShape = new Graphics();
_maskShape.beginFill(0xffffff,0.5);
_maskShape.drawRect(0, 0, 1480, 860);
_maskShape.endFill();
```

**Comment by ivanpopelyshev** [comment]
you can switch off scissor before we fix it: renderer.maskManager.enableScissor = false;

**Comment by ivanpopelyshev** [comment]
Can you check if https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js works for you with enabled Scissor?

**Comment by SlawomirMazgaj** [comment]
- `renderer.maskManager.enableScissor = false;` with current dev version DOES WORK.
- Version from your Dropbox with enabled Scissor also DOES WORK.

That was super quick, thanks 👍

**Comment by ivanpopelyshev** [comment]
#2555

**Comment by GoodBoyDigital** [comment]
thanks for the fix @ivanpopelyshev 👍

**Comment by SlawomirMazgaj** [comment]
Nice one, latest dev working nice. Thanks :)
