### ISSUE TITLE
PIXI v4.1 - Graphics.prototype.getLocalBounds missing return

### ISSUE THREAD

**Issue by joeredfearn** [pixijs/pixi.js#2548]
Line **809** Graphics.js does not actually return a PIXI.Rectangle which means **Graphics.prototype.generateTexture** fails.

**Comment by ivanpopelyshev** [comment]
Make a PR?

**Comment by ivanpopelyshev** [comment]
Ugh, I cant find that line. Where is it?

**Comment by joeredfearn** [comment]
I will attempt a PR right now!

**Comment by ivanpopelyshev** [comment]
Where is that line? I cant find that

**Comment by joeredfearn** [comment]
Line **809** Graphics.js - this._currentBounds = this._localBounds.local.getBounds();

**Comment by ivanpopelyshev** [comment]
You are talking about branch v4.1 which is very very very bleeding edge. Are you experimenting with it? :)

**Comment by joeredfearn** [comment]
Well i'm rendering a texture from a graphics object - regardless I would consider a getter function that does not return anything a bug rather than a feature request!

:)

**Comment by ivanpopelyshev** [comment]
thank you, I'll add "return" there.

By the way https://github.com/ivanpopelyshev/pixi.js/tree/dev-4.1.0 has 84 commits that werent merged into pixijs yet

**Comment by joeredfearn** [comment]
thank you

I understand that 4.1.0 is not officially release yet, we are just trying it out on an internal project and i thought i would help out!

thanks for the hard work and i will let you know if i run into any other problems.

**Comment by ivanpopelyshev** [comment]
Nice! v4.1 is my playground and it has many breaking changes. Better use my repo then (https://github.com/ivanpopelyshev/pixi.js/tree/dev-4.1.0), I can add you as a contributor

**Comment by ivanpopelyshev** [comment]
https://monsterisland.chimeracompanygames.com/lux-demo/index.html - that thing is built on pixi-flip branch, and I'll make a merge attempt soon. Most of changes in v4.1 made for that purpose.

**Comment by ivanpopelyshev** [comment]
Can you please change the title to "v4.1" ?

**Comment by GoodBoyDigital** [comment]
closing for now as this is a completely separate version
