### ISSUE TITLE
PIXI V4 - Nested Masks Blinking in Chrome Ver. 50.0.2661.94 m

### ISSUE THREAD

**Issue by nigromance** [pixijs/pixi.js#2549]
Hi PIXI Team!

Seems like my Chrome has updated today and I´ve found out new visual fails into the game I´m developing with PIXI v4. I´ve updated to the very last version (dev one) but the problem remains.  After hard testing until get mad I realized there is an issue with the masks I´m using there.

Basically once 2 containers are nested, each one of them with a mask, you see how the second container is blinking instead of see it properly.
I´ve checked this is happening on last Chrome version (50.0.2661.94 m) for webGL, canvas and firefox works fine.
Since my code is quite complicated I´ve made an issue reproduction in jsfiddle, so you could check the blinking in Chrome:

https://jsfiddle.net/y4ocdv0c/

**Comment by johanlajili** [comment]
Hi, we are having the same issue in my company and this is seriously affecting our games. Please mark it as the highest priority. Thank you.
(In the mean time, forcing canvas does the trick).

**Comment by GoodBoyDigital** [comment]
hey chaps! Does this fiddle work ok for you?

https://jsfiddle.net/w8rrpv56/

Thanks!

**Comment by johanlajili** [comment]
It is not working for me
![george-costanza](https://cloud.githubusercontent.com/assets/1099219/15039109/eeb70edc-12a1-11e6-8693-70fef3dbb429.gif)

**Comment by nigromance** [comment]
Nop, has exactly the same result.

**Comment by johanlajili** [comment]
In our case, this happens on 3.0.8 by the way.

**Comment by johanlajili** [comment]
(And it happens only on windows, not mac).

**Comment by nigromance** [comment]
In my case, fails into a Windows 10 Pro X64 desktop computer, but works fine into a Windows 10 Home X64 laptop with the same Chrome version. I´m not sure whether this is about an issue from the combination of webGL/graphic processor/browser :(

**Comment by GoodBoyDigital** [comment]
that is a pain! I can't seem to recreate it on any device in our studio :/

**Comment by johanlajili** [comment]
It's happening to us on a Windows 7 Professional Service Pack 1 64 bits, and the graphic card is a Radeon HD 5450. It works fine on the same machine if using firefox, and used to work before that on chrome.

**Comment by GoodBoyDigital** [comment]
might be best if you submit an issue to chrome as a bug? 
I can do a little investigating on my end..

**Comment by johanlajili** [comment]
Can you tell us on what machine you tried (esp. windows machine)?

**Comment by nigromance** [comment]
It seems a Chrome problem, I have a Radeon HD 5700 Series. So I guess is somehing about the Chrome version and machines relationship? That could explain why is so hard to reproduce.
I have the problem just in this computer and since Chrome was updated.
I´ve checked it is happening with PIXI V3 as well, as johanlajili said, so it seems is not about something about the PIXI version.

**Comment by johanlajili** [comment]
I just tested on Google version 51.0.2704.36 beta-m, and it is working, so sounds like Google already has a fix for it. We are going to mark the version 50 as not compatible with webGL on our side. Thanks

**Comment by GoodBoyDigital** [comment]
nice!

**Comment by nigromance** [comment]
I´ve open an issue to chrome about it, but yes, changing Chrome version there is no problem.
I´m doing the same to avoid this Chrome version.

Thanks!

**Comment by ThommyTheThird** [comment]
I'd like to say we're having this problem with pixi 3.0.8 on hardware-accelerated canvas as well. It's not just a WebGL issue, so @johanlajili remark of disabling WebGL on version 50 does not do the trick for us.
But since we cannot control the user's hardware-acceleration settings we are unfortunately unable to provide a stable experience for our current Chrome v50 users.
Are you guys not experiencing issues with hardware-accelerated canvas?

**Comment by johanlajili** [comment]
Oh that is indeed an issue. To be fair we don't have a lot of windows machine to test on, and I'm not exactly sure what triggers hardware-accelaration for canvas (different graphic card?). I think it would be really worth it for the PIXI team to try to find a work around. Or at least give us a way to detect this is happening, so we can display a relevant error message.

**Comment by GoodBoyDigital** [comment]
Good shout @johanlajili, If you get a chance feel free to have a go and submit a PR. 👍

**Comment by GoodBoyDigital** [comment]
closing this for now as it is a chrome bug and looks patched in later versions of chrome. thanks all! 👍
