### ISSUE TITLE
TilingSprite does not support spritesheet

### ISSUE THREAD

**Issue by MKelm** [pixijs/pixi.js#255]
I want to use

> var sprite = new PIXI.TilingSprite(PIXI.Texture.fromFrame(options.image));

with a framename in _options.image_ like "tilingimageabc"

I have a spritesheet which includes the tiling image, but instead of the frame image I will get the whole spritesheet image as tiling image.

If I have a non-power-of-2 tiling image frame, I will get the first frame (another image) of the spritesheet instead, as full-size sprite.

The only solution so far is to change _options.image_ from e.g. "tilingimageabc" to "fullpath/singleimages/tilingimageabc.png" and to add the single file in the assets loader too.

**Comment by jmmk** [comment]
@GoodBoyDigital it seems this is broken in version 2.1.0. I have a sprite that is 32x32 (complies with power-of-2) and I can use it as a ```TilingSprite``` fine if I  use it as a standalone image
e.g.
```javascript
TilingSprite(Texture.fromImage("image.png"))
```

If I include the image in my spritesheet and try:
```javascript
TilingSprite(Texture.fromFrame("image.png"))
``` 

I get the following error:

 ```WebGL: drawElements: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'. Or the texture is Float or Half Float type with linear filtering while OES_float_linear or OES_half_float_linear extension is not enabled.```


All of my other sprites render correctly from the spritesheet using:
```javascript
Sprite.fromFrame("sprite.png")
```
So I don't think that it is a problem with the spritesheet.

**Comment by englercj** [comment]
Is your spritesheet a power of two? Because that is what is bound as the texture in webgl, and for tiling sprite it expects it to be power of two.

**Comment by jmmk** [comment]
Putting the sprite into it's own spritesheet of 32x32 px worked, where adding padding to it (36x36) didn't, so it was a problem with the size of the spritesheet.

It seems like there's no good reason to try and create a TilingSprite from a spritesheet then?

**Comment by englercj** [comment]
Its fine to create it from a spritesheet, as long as the sheet is a power-of-two texture.
