### ISSUE TITLE
Pixi v3 - updateTransform generates "Cannot read property 'worldTransform' of null"

### ISSUE THREAD

**Issue by mathieuanthoine** [pixijs/pixi.js#2550]
call updateTransform on a DisplayObject that isn't added to the displayList generates a : 
Cannot read property 'worldTransform' of null

In Pixi v2, if we wanted to split rendering and calculation, we needed to call updateTransform on the stage when we didn't called renderer.render

In pixi v3, do we need to call stage.updateTransform if we don't call renderer.render ? If it's the case, we need to fix it when there's no parent in the Container.prototype.updateTransform (for the stage for example) : 

line 8106: var pt = this.parent!=null ? this.parent.worldTransform : PIXI.Matrix.IDENTITY;
line 8192: this.worldAlpha = this.alpha * (this.parent!=null ? this.parent.worldAlpha : 1);

**Comment by ivanpopelyshev** [comment]
Current version is v4, I dont think that @GoodBoyDigital will change that in v3. Please look in WebGLRenderer.render(), it assigns temporary parent before doing updateTransform().

**Comment by mathieuanthoine** [comment]
I'm at the moment on a project with students with Pixi v3 and we won't update Pixi in the middle of the production but I found a workaround.
Thank for the information on pixi v4, I will check it for the next project :)

**Comment by ivanpopelyshev** [comment]
Good luck to you and your students!

**Comment by englercj** [comment]
The currently released version is v3, v4 is currently in development. The change from v2 -> v3 was for us to assume there would be a parent (which simplifies and speeds up the updateTransform function that runs every frame) and then we assign a temp parent when one doesn't exist.

If you need to update transform directly, on a root object, then place it in a temporary parent.

**Comment by mathieuanthoine** [comment]
Ok thanks Chad for explanations. The game is in a child of stage so the updateTransform is made on this one and not directly on stage. It works perfectly
