### ISSUE TITLE
How can I set anchor with pixels instead of percent?

### ISSUE THREAD

**Issue by greenSnot** [pixijs/pixi.js#2552]
I would rather use pixels than percent because my sprites maybe change its size.

**Comment by ivanpopelyshev** [comment]
sprite.pivot.x, sprite.pivot.y 
It also works on all containers.

**Comment by greenSnot** [comment]
If I change their rotation ,the centre of rotation will still be anchor's points and it should be pivot's points .

**Comment by ivanpopelyshev** [comment]
Anchor is applied before and after rotation, while pivot is applied only after rotation. You can modify both pivot and position to achieve anchor effect:

```js
sprite.position.x += ax;
sprite.position.y += ay;
sprite.pivot.x = ax;
sprite.pivot.y = ay;
```
