### ISSUE TITLE
Pixi Renders SVG on iOS devices incorrectly.

### ISSUE THREAD

**Issue by gurmukhp** [pixijs/pixi.js#2554]
I'm having this problem whereby when SVGs are drawn on the Canvas, they are drawn too small. If subsequent frames are then added in (also SVGS), they load in the correct width and height. 

There is nothing in the console about any errors and it works perfectly fine on Chrome emulating iOS. All tablets seem to have this behaviour.

Once the SVG has been added once (it's tiny), if I then add it again, it draws tiny (because it's in the texture cache). If however, I make a small change to the SVG, it's no longer in the cache and therefore Pixi recreates the texture, this time it's shown completely correctly.

It's really hard for me to show a demo with the issue since I'm working on a project that isn't public yet. If I simply draw the SVG on a plain canvas, it works fine, even on iOS.

The asset has a width and height defined, and it seems like the texture obeys this but the image inside the texture seems to be super tiny.

Do you have any tips on how to debug this?

Here are a few screenshots:

When asset added to stage on iOS:
![simulator screen shot 6 may 2016 18 30 16](https://cloud.githubusercontent.com/assets/899769/15080989/8342b76a-13b8-11e6-8dc4-829d8b96eeec.png)

When more frames added into MovieClip and played (this problem also occurs if I only make a sprite):
![simulator screen shot 6 may 2016 18 31 13](https://cloud.githubusercontent.com/assets/899769/15081019/9ec4d554-13b8-11e6-9bd0-8319b44ecf30.png)

I'm using the latest Pixi on the dev branch. I've checked the height and width of the textures and also the realHeight and realWidth, they are all correct.

Any idea why this problem is isolated to touch devices and why the SVG is being rendered tiny? I've tried removing viewbox and also the height width attributes but it doesnt seem to make a difference. 

I noticed that in the past I got canvas buffer errors and the asset would be drawn tiny, but the latest dev changes have removed that.

I would really appreciate any tips in terms of debugging this.

Thank you!

**Comment by ivanpopelyshev** [comment]
Something-something <svg> element width and height ? Different behaviours in different browsers.

**Comment by gurmukhp** [comment]
Hey Ivan,

Could you elaborate? A height and width has been defined in the SVG.

**Comment by ivanpopelyshev** [comment]
@gurmukhp there are multiple ways to define them: in svg file, in svg element itself. I dont know exactly whats wrong, but I remember that I had problems with SVG elements across browsers.

**Comment by gurmukhp** [comment]
Update: This problem occurs when the same SVG has been drawn on the page as an image.

If I draw the SVG in Pixi, it loads perfectly fine. If I then append that same SVG string in the DOM, Pixi will render it small. I wonder why?

**Comment by gurmukhp** [comment]
I have fixed this. The problem was related to the browser caching the SVG before loading it onto the Canvas. A way to fix this is to slightly change the SVG by adding a space somewhere inside the string, this fools the browser into thinking its a new image and therefore loads it correctly.
