### ISSUE TITLE
Should renderable = false still render the children?

### ISSUE THREAD

**Issue by SebastianNette** [pixijs/pixi.js#2556]
Right now the `renderable` property works exactly the same as the `visible` property. // edit (forgot that renderable false still calls updateTransform, so not exactly the same)
If set to false, the object including it's children are not rendered at all.

Would it make sense to change it, so that the children are still being rendered, even if the parent is not rendered?

I'm in a situation, where I want to use an object as a placeholder. I do not want to upload it to the GPU, I do not want it to be rendered, however, I want the children to be rendered.

And there doesn't seem to be a way to do this. Or maybe I am just not seeing it.
Or would it be possible to add another property to achieve exactly this behaviour?

Any thoughts on that?

**Comment by SebastianNette** [comment]
Most simple fix to my issue is probably to use a Container instead.
So err, yea.. uh.. non issue :D

**Comment by englercj** [comment]
> I'm in a situation, where I want to use an object as a placeholder. I do not want to upload it to the GPU, I do not want it to be rendered, however, I want the children to be rendered.

That is exactly the use case of containers :)
