### ISSUE TITLE
PIXI V4 - Different width/height values for container than in V3.

### ISSUE THREAD

**Issue by SlawomirMazgaj** [pixijs/pixi.js#2557]
Hi guys, just noticed something weird. I was playing with [Container Example](http://pixijs.github.io/examples/index.html?s=basics&f=container.js&title=Container) a bit and I got to the point where I'm getting different values of width and height in pixi v3.0.11 and Latest dev v4.

I was adding a single bunny to a container and checking width and height of the container. As expected it was same as bunny size. Then I moved bunny inside container and container values were still the same. At the end I made another container (empty) and added it to existing one and now V3 is showing me width and height from 0, 0 to bunny.x+bunny.width, bunny.y+bunny.height.
V4 however is still showing me size of the bunny.

Here's the code I used:
```js
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();

var container = new PIXI.Container();
stage.addChild(container);

var bunny = PIXI.Sprite.fromImage('_assets/basics/bunny.png');
bunny.x = 140;
bunny.y = 140;
container.addChild(bunny);

var tmp = new PIXI.Container();
container.addChild(tmp);

setTimeout(function() {
  console.log("Bunny => " + bunny.width + " | " + bunny.height);
  console.log("Container => " + container.width + " | " + container.height);
}
, 1000);

animate();
function animate() {
    requestAnimationFrame(animate);
    renderer.render(stage);
}
```

**Comment by ivanpopelyshev** [comment]
WOW new bug!

**Comment by SlawomirMazgaj** [comment]
V3 bug?
Imo V3 behavior makes more sense.

**Comment by ivanpopelyshev** [comment]
Backported fix and merged it. Im not sure when it will be published in "bin" folder or npm.

**Comment by SlawomirMazgaj** [comment]
Sry, 2nd container is empty, so it doesn't :v

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
