### ISSUE TITLE
PIXI V4 - Color matrix filter when applied on a sprite disappears all sprites in the scene graph

### ISSUE THREAD

**Issue by neutrino84** [pixijs/pixi.js#2558]
This appears to be a problem that only happens with certain filters. You can reproduce by using the 
PIXI.filters.ColorMatrixFilter(); When adding the color matrix filter to sprite.filters, all other sprites in the scene graph are no longer visible. When removing it from filters, everything goes back to normal.

Relevant jsfiddle:
https://jsfiddle.net/o3qqmw3t/

You should see two robots, one black/white, one color.

Testing using the latest from https://cdn.rawgit.com/pixijs/pixi.js/dev/bin/pixi.js

**Comment by bigtimebuddy** [comment]
I can reproduce the same error. I did a binary search on the commits and this started recently after this commit https://github.com/pixijs/pixi.js/commit/6f2b86151733cf0cad3bb9381f3bd2389fb97495

**Comment by GoodBoyDigital** [comment]
This one is on my todos - will keep you all posted 👍

**Comment by GoodBoyDigital** [comment]
the demo should work now :)
