### ISSUE TITLE
PIXI V4 - Overlapping graphic causing mask issues 

### ISSUE THREAD

**Issue by SlawomirMazgaj** [pixijs/pixi.js#2559]
Hi again, I'm keep playing with pixi v4 and I'm afraid I found another issue. This time it's Graphic and Mask related. I found that if you draw a Graphic and your shapes overlaps mask is only working only in places where there's odd number of "layers". So single Graphic mask works. 2 overlapped shapes works except the overlapped part. It's probably easier to see it in action so here are some jsFiddle.

[V3 which was working](https://jsfiddle.net/3aztw8p3/).

[V4 with the issue](https://jsfiddle.net/o8mxh96L/).

Sorry for giving more work, thanks for great engine :)

**Comment by GoodBoyDigital** [comment]
I think this is fixed now! 👍

**Comment by SlawomirMazgaj** [comment]
@GoodBoyDigital Was just testing that in release version of V4 and it's still causing problems :(

**Comment by raphadko** [comment]
Happened only with webGL here, canvas is fine
