### ISSUE TITLE
Load Multiple Bitmap Text Colors

### ISSUE THREAD

**Issue by mtderryberry** [pixijs/pixi.js#2560]
Hi, 

I am trying to insert text into my application using Bitmap Text. Right now I have created two .xml and .png files for text. One is white text, the other is black text. If I just load one of these, there is no problem. However, how would I load both of them and differentiate between the two? They are the same font (Arial), just different colors. To load one, I am doing:

 function init() {
    var text = new PIXI.extras.BitmapText("Hi", { font: "20px Arial" });
 }

 var loader = new PIXI.loaders.Loader();
 loader.add("whiteText.xml");
 loader.once('complete', init);
 loader.load();

Is there a way to load a second xml file ("blackText.xml") and then differentiate between the two when creating text?

**Comment by englercj** [comment]
Make them have different names in the XML besides calling both of them Arial.

Also, you could use the `tint` feature instead of creating 2 separate bitmaps.

**Comment by mtderryberry** [comment]
Do I just change the face value?

<info aa='1' size='50' smooth='1' stretchH='100' bold='0' padding='0,0,0,0' spacing='0,0' charset='' italic='0' unicode='0' face='Arial'/>

Assuming I changed it to 'ArialBlack', would I then call it with:

var text = new PIXI.extras.BitmapText("Hi", { font: "20px ArialBlack" });

Thanks

**Comment by ivanpopelyshev** [comment]
Hm, as a reference, when RPGMaker loads a resource it can tint it. Something like "font.png:ff0000" will give us a red font. May be we can use the same approach here.

**Comment by mtderryberry** [comment]
The problem with tint is the outline. My white font has a black outline and I would like a black font with a white outline. By just tinting the white font to 0x000000, I just get solid black

**Comment by englercj** [comment]
> Assuming I changed it to 'ArialBlack', would I then call it with:

I'm pretty sure that is the case, try it!

**Comment by GoodBoyDigital** [comment]
closing for now, seems to have run it course!
