### ISSUE TITLE
BitmapText parent rendered over children

### ISSUE THREAD

**Issue by Dadibom** [pixijs/pixi.js#2566]
I've got a BitmapText object that's a child of another object extended from BitmapText, in order to achieve a shading effect. It works as expected until I change the text values of both objects after creation, then the parents characters AFTER the initial string length will be displayed on top of the childrens characters.

Like this (back to front):

After creation (abc)
this:   abc
child: abc

After edit(abcdef) 
this:  abc
child:abcdef
this:        def

There were three characters on creation so only the first three characters will be displayed correctly. If I created the object with "", then all characters will be displayed in the wrong order. It does not matter in which order i do the text change (parent or child first)

Code to reproduce below.
```
var textStyle = {
	font:"16px bitmapfont"
};

var black = 0x000000;

var ShadedText = function(text,tint){
	PIXI.extras.BitmapText.call(this,text,textStyle);
    this.tint = black;
    var c = this.c = new PIXI.extras.BitmapText(this.text,textStyle);
    if(tint)
    	c.tint = tint;
    c.position.x = c.position.y = -1;
    this.addChild(c);
};

ShadedText.prototype = Object.create(PIXI.extras.BitmapText.prototype);
ShadedText.prototype.constructor = ShadedText;
ShadedText.prototype.setText = function(str){
        this.text = str;	
	this.c.text = str;
};


var x = new ShadedText("123");
x.setText("abcdef");//the characters d, e and f on the parent object will render on top of those 
                              //characters on the child.
container.addChild(x);//Add text to any container/stage
```

**Comment by Dadibom** [comment]
By writing this, I realized that the characters of bitmaptext are probably sprites being children of the bitmaptext object, so this is not as strange as I first thought. Note that this does not only happen when changing the text from abc to abcdef, but any string. It does not matter that "abc" was already there, I could have changed it to ijklmn and ijk would be displayed correctly while lmn wouldn't.

**Comment by andrewstart** [comment]
You are correct, BitmapText is a Container with a Sprite for each character in the string. An easy fix would be to make your ShadedText class be a Container with two BitmapTexts as children, or to build the styling into the bitmap font if possible.

**Comment by Dadibom** [comment]
I fixed it by changing my constructor (assuming this to be the foreground and the child to be the background, creating the objects with empty text properties and then calling the settext method)

`var ShadedText = function(text,tint){
	PIXI.extras.BitmapText.call(this,"",textStyle);
    var c = this.c = new PIXI.extras.BitmapText("",textStyle);
    if(tint)
    	this.tint = tint;

    c.tint = black;
    c.position.x = c.position.y = 1;
    this.addChild(c);
    this.setText(text);
};`

However, if the bitmaptext object always created it's character in the beginning of the children array, this would not be a problem and manually added children would always (unless you add with an index of course) be rendered over the parent as one would expect.

**Comment by GoodBoyDigital** [comment]
seems resolved 👍
