### ISSUE TITLE
V4 webgl drawCount

### ISSUE THREAD

**Issue by bQvle** [pixijs/pixi.js#2568]
Is there a way to get the drawCount in V4? I use it all the time to make sure the game is optimized.
thanks.

**Comment by cvissie** [comment]
I added this portion of code for myself.

You just need to set the PIXI.Sprite.drawCount=0 before painting in your game loop.

```javascript
  /**
   * This will add draw counts to PIXI objects
   */
  (function () {

    // PIXI.Sprite

    PIXI.Sprite.drawCount = 0;

    PIXI.Sprite.prototype.__renderWebGL = PIXI.Sprite.prototype._renderWebGL;
    PIXI.Sprite.prototype._renderWebGL = function (renderer) {
      PIXI.Sprite.drawCount++;
      this.__renderWebGL(renderer);
    };


    PIXI.Sprite.prototype.__renderCanvas = PIXI.Sprite.prototype._renderCanvas;
    PIXI.Sprite.prototype._renderCanvas = function (renderer) {
      PIXI.Sprite.drawCount++;
      this.__renderCanvas(renderer);
    };


    // PIXI.Container

    PIXI.Container.drawCount = 0;

    PIXI.Container.prototype.__renderWebGL = PIXI.Container.prototype._renderWebGL;
    PIXI.Container.prototype._renderWebGL = function (renderer) {
      PIXI.Container.drawCount++;
      this.__renderWebGL(renderer);
    };


    PIXI.Container.prototype.__renderCanvas = PIXI.Container.prototype._renderCanvas;
    PIXI.Container.prototype._renderCanvas = function (renderer) {
      PIXI.Container.drawCount++;
      this.__renderCanvas(renderer);
    };


  })();
```

**Comment by cvissie** [comment]
Also just note... This doesn't apply for meshes...

Ideally this should be reworked to report on triangle draw count.

**Comment by ivanpopelyshev** [comment]
That's not how it works. You have to override SpriteRenderer.

**Comment by bQvle** [comment]
gl.drawElements is only only two different places in the V4 src. I've manually added my own counter now. but it would be great if it was build in again. so you wouldn't have to redo it every time a new version is released.

**Comment by fanjules** [comment]
Incrementing a counter when renderer.gl.drawElements occurred worked for me, but does not seem to include Text or BitmapText objects.  I added counter increment to Text.prototype.renderWebGL() but not sure this is the correct thing to do.  I can't find an equiverlent for BitmapText.  Any assistance?

**Comment by ivanpopelyshev** [comment]
The counter must be in pixi SpriteRenderer class.

**Comment by fanjules** [comment]
Yes, you're correct... adding a huge number of both text types did start to increment the number of draw calls, thanks!
