### ISSUE TITLE
V4 TilingSprite BlendMode

### ISSUE THREAD

**Issue by bQvle** [pixijs/pixi.js#2569]
You recently fixed Alpha and Tint for TilingSprite, so i gave V4 a shot again and noticed that BendMode isn't working.

**Comment by ivanpopelyshev** [comment]
Yeah, I just found it :) Gonna make PR now

**Comment by bQvle** [comment]
cool :) thank you!

**Comment by ivanpopelyshev** [comment]
Fixed, merged.
