### ISSUE TITLE
Uniform types documentation?

### ISSUE THREAD

**Issue by OmarShehata** [pixijs/pixi.js#2570]
Is there any page that documents what uniform types pixi.js looks for? I was trying to adapt a shader from an old version and it took me a while to realize that it wasn't working because I had to change `2f` to `v2`. 

This issue seems to be what I'm getting at:

https://github.com/pixijs/pixi.js/issues/1460#issuecomment-76944593

It was closed because v4 uses glslify. However, until that comes out, would it be a good idea to add a table or a reference to that in the documentation? 

For now, I can look at the [source of the syncUniform](https://github.com/pixijs/pixi.js/blob/faf4c15dd6187eef50bb62ae90e005b95976263e/bin/pixi.js#L16721) function to get a list of the uniform types.

**Comment by englercj** [comment]
Until there are docs, you can view the source:

https://github.com/pixijs/pixi.js/blob/364c2457c6693d6e3ab68786539c53d566503e7b/src/core/renderers/webgl/shaders/Shader.js#L232-L463

Try not to link to generated code, it takes forever to load.
