### ISSUE TITLE
Troubles with skew and scale

### ISSUE THREAD

**Issue by Trixt0r** [pixijs/pixi.js#2574]
Hi pixi devs!

I am struggling now for 2 days on some transformation issues for a DisplayObject between 2 containers.

So I have my `WorldContainer`, where all my children live and a `SelectionContainer`, which also belongs to the `WorldContainer` and is able to hold other children from the `WorldContainer`. As soon as I am selecting any child in the `WorldContainer` I remove that selected child from its parent and move it into the `SelectionContainer` with proper position translation, etc. The `SelectionContainer` can be moved, rotated and scaled.

Everything works fine as long as the children in the `SelectionContainer` have no rotation.
Now, if I start stretching the Container, the children with an angle of, let's say 30°, start to skew... The problem is now, that if I want to move the children in the `SelectionContainer` back to the `WorldContainer` I do not know which skew values I have to assign to the children, which results in a very ugly visual effect.

I added two screenshots showing the children in the `SelectionContainer` and then after the transformation into the `WorldContainer`.

![in selection](https://cloud.githubusercontent.com/assets/1076870/15271356/da0680ee-1a44-11e6-82e7-ab345c4bdf4d.png)
![in world](https://cloud.githubusercontent.com/assets/1076870/15271357/da076b8a-1a44-11e6-8ce1-900f6d026c8e.png)

I tried to extract the skew values based on the `worldTransform` of the child:
```
var cos = Math.cos(child.rotation);
var sin = Math.sin(child.rotation);
var A = child.scale.x * cos, B = child.scale.x * sin;
var C = -child.scale.y * sin, D = child.scale.y * cos;
child.skew.x = Math.acos((wt.c + A) / (A + C) ) || Math.acos((wt.d + B) / (B + D));
child.skew.y = Math.asin((A - wt.a) / (A + C)) || Math.asin((B - wt.b) / (B + D));
```
But this results in wrong values (also tried to transform the calculated values into several spaces).

Is it actually even possible to get the original skew values based on the transformation matrix?

Hoping for answers...

-Trixt0r

**Comment by ivanpopelyshev** [comment]
Well, you have the transformation matrix in sprite.worldTransform, you can multiply/divide it to parent matrix, and then calculate position scale and skew. Problem is, currently there's no code in PIXI.Matrix for that kind of decomposition.

**Comment by Trixt0r** [comment]
I would really appreciate it, if you guys could add a method to the matrix class, which returns a decomposition object of a transformation matrix.

This would help me a lot.

-Trixt0r

**Comment by GoodBoyDigital** [comment]
Hey all! just added a decompose function to Matrix class.
We also have a new function in transform to make life easier too:

```
var m = new PIXI.Matrix();
m.tx = 300;
m.ty = 200;

var image = new PIXI.Sprite.fromImage('think.png');
stage.addChild(image);

// will decompose 
image.transform.setFromMatrix(m);
```

enjoy! 👍

**Comment by Trixt0r** [comment]
Sorry for picking this issues up again, but there are some problems with the implementation.

The decomposition is not really working for some cases.
If the rotation has been set and at least one scale component is negative, the rotation and the scale is are longer preserved.

I also would like to kow if it is possible to transform the decomposed skew values into a local container space?

- Trixt0r
