### ISSUE TITLE
Maybe there is a bug at Graphics.js

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#2578]
https://github.com/pixijs/pixi.js/blob/master/src/core/graphics/Graphics.js#L477

```
var sweep = anticlockwise ? (startAngle - endAngle) * -1 : (endAngle - startAngle);
```

Because that (startAngle - endAngle) * -1  ===  endAngle - startAngle, 
 the line 477   equals to : 
```
var sweep = anticlockwise ? (endAngle - startAngle) : (endAngle - startAngle);
```
Is there a bug ?

**Comment by GoodBoyDigital** [comment]
oh yeah! Good catch!

**Comment by GoodBoyDigital** [comment]
tweaked in #3141
