### ISSUE TITLE
[Suggest] add a method  setTextWithoutUpdate  to Text Class

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#2582]
It's very simple:
```
Text.prototype.setTextWithoutUpdate = function(text){
 this._text = text;
// then clear text-canvas and re-render , 
// but Don't need to recompute and reset some properties
};
```

Use Case:
Sometime some texts is updated frequently, for example  time counter(by millisecond).
Developer could set a default state for Text Object like this: 
```
timeLabel.text = "00:00:00.000";
```

Then, in Game loop , we don't have to update text object every time ( the value of text won't bigger than default) , we could use:
```
var timeDisplay= formatTime(timeCount);  
timeLabel.setTextWithoutUpdate(timeDisplay);
```

**Comment by themoonrat** [comment]
Hi there!

In your game loop, at a certain point you're going to want to go from calling timeLabel.setTextWithoutUpdate(timeDisplay) to timeLabel.updateTexture() to then show the correct value.

In which case you may as well just call timeLabel.setText(timeDisplay) there instead!

**Comment by ivanpopelyshev** [comment]
Its javascript. Why not just hack it? myText._text = "01:01" ?

**Comment by GoodBoyDigital** [comment]
this is quite a nice idea! We could actually avoid resizing the texture unless its actually too small! This would speed up frequently updating text a fair bit!

**Comment by englercj** [comment]
Text actually uses a dirty flag right now and doesn't redraw anything until it actually needs to render in the loop. You should be fine assigning the `.text` property as often as you want now!

**Comment by finscn** [comment]
@englercj  , I found that  , when I use  ```.text``` , the this.dirty will be true , then ```updateText``` will be called , it  does many unnecessary  things in some cases, e.g. the case in the first floor in this issues.

I think you didn't understand me , because of my bad english

**Comment by englercj** [comment]
But we can't know if those things should happen without doing them.

**Comment by finscn** [comment]
@englercj ,  you could see my fork version : https://github.com/finscn/pixi.js/blob/master/src/extensions/mixin/mixin-Text.js 

I've added & changed some methods in Text.js  for my request. 
I think it's not a hard work.

**Comment by englercj** [comment]
I don't think that works for all the different changes that could happen on text, I think that only works for your case.
