### ISSUE TITLE
Filter constructor arguments

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#2583]
There are a bunch of filters that don't have any constructor arguments and are only update-able via getters/setter. Any thoughts about these arguments/defaults?
### BlurFilter
```js
new BlurFilter(blur = 4, passes = 2)
new BlurFilter({x: 4, y: 4}, passes = 2) // alternate x & y values
```
### ColorMatrixFilter
```js
new ColorMatrixFilter(hue = 0, saturation = 0, brightness = 0, contrast = 0)
```
### GrayFilter
```js
new GrayFilter(value = 1)
```
### TwistFilter
```js
new TwistFilter(radius = 400, angle = 3, offset = [400,300])
```

### Usage
```js
// without constructor args, boo!
var filter = new BlurFilter();
filter.blur = 8;
container.filters = [filter];

// with constructor args, yah!
container.filters = [new BlurFilter(8)];
```

**Comment by GoodBoyDigital** [comment]
Good idea! 👍

**Comment by englercj** [comment]
Blur has ctor params, and the others have moved out of the repo or changed to where this may not make sense anymore. Going to go ahead and close this out.
