### ISSUE TITLE
Problem upgrading to v4. ErrorCode 1281

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#2584]
Hi there, upgrading from v3 to v4 I get an occassional problem with compileProgram:

<img width="760" alt="screen shot 2016-05-17 at 12 10 36" src="https://cloud.githubusercontent.com/assets/820/15320381/1df08450-1c28-11e6-8f51-b7696c2792bd.png">

It seems to stem from "ERROR: 0:5: '' : array size must be greater than zero"

Any ideas?

**Comment by ivanpopelyshev** [comment]
MAX_TEXTURES is 0. How the heck? is it iOS or what?

**Comment by weepy** [comment]
Just in Chrome OSX

**Comment by ivanpopelyshev** [comment]
PLEASE 

```js
SpriteRenderer.prototype.onContextChange = function ()
{
    var gl = this.renderer.gl;

    // step 1: first check max textures the GPU can handle.
    this.MAX_TEXTURES = Math.min(gl.getParameter(gl.MAX_TEXTURE_IMAGE_UNITS), CONST.SPRITE_MAX_TEXTURES);
```

find that, and change it to 

```js
    this.MAX_TEXTURES = Math.max(1, Math.min(gl.getParameter(gl.MAX_TEXTURE_IMAGE_UNITS), CONST.SPRITE_MAX_TEXTURES));
```

You are the only one who has that bug currently, so its not possible for me to test it. If that works for you, I will make a PR to pixi.

**Comment by weepy** [comment]
Sorry I still get the same problem :-(

**Comment by ivanpopelyshev** [comment]
Ok lets try this one:

```js
 this.MAX_TEXTURES = Math.min(gl.getParameter(gl.MAX_TEXTURE_IMAGE_UNITS), CONST.SPRITE_MAX_TEXTURES);
if (!this.MAX_TEXTURES) this.MAX_TEXTURES = 1;
```

**Comment by weepy** [comment]
Looks pretty similar?!

**Comment by ivanpopelyshev** [comment]
I edited code above, please try it with isNaN and <0 thing

**Comment by ivanpopelyshev** [comment]
Can you please tell me what this.MAX_TEXTURES is for you? console.log it?

**Comment by weepy** [comment]
so in "SpriteRenderer.prototype.flush"

it crashes on "shader = this.shaders[groupTextureCount-1] = generateMultiTextureShader(gl, groupTextureCount)"

groupTextureCount == 0 

groupCount == 1

groups.length = 4096

bit weird?  You're previous fix didn't work BTW

**Comment by ivanpopelyshev** [comment]
Ok, that's not what i thought. GroupTextureCount cant be zero, i dont know how the heck it was achieved. May be sprite._texture was not actual Texture? 

```js
    for (var i = 0; i < this.currentIndex; i++)
    {
        // upload the sprite elemetns...
        // they have all ready been calculated so we just need to push them into the buffer.
        var sprite = sprites[i];

        nextTexture = sprite._texture.baseTexture;
```
add this one:
```js
if (!nextTexture) { console.log("your sprite texture is invalid. Go figure out why."); }
```

**Comment by weepy** [comment]
I'm not quite sure why groups.length == 4096  ? Seems a bit massive ?

**Comment by ivanpopelyshev** [comment]
@weepy pooled. that's ok :)

**Comment by weepy** [comment]
I added that one ... no help ... doesn't get hit.  At some point i can try to package it up for you.

**Comment by ivanpopelyshev** [comment]
Either package it, either try to debug and tell me whats wrong :) I really appreciate your help

**Comment by weepy** [comment]
ok. i won't have time to do it just yet :(

**Comment by weepy** [comment]
OK - so I looked into it, and I think it's caused in a situation where there are two or more renderers. Now that I've removed one of them for performance reasons, the error has not come up.  Does that give a clue at all ?

**Comment by ivanpopelyshev** [comment]
Still no. You did try to debug spriteRenderer, didnt you?

**Comment by weepy** [comment]
No unfortunately not really. I was going to but then another change has reduced the number of renderers from 2 to 1, which seems to have removed the problem. I can see if there's a tag with the broken version, but can't promise.

**Comment by ivanpopelyshev** [comment]
I think that if you are trying to use RenderTexture for two renderers at the same time, it wont be good. Everything else has to work

**Comment by weepy** [comment]
I didn't use RenderTexture at all, only PIXI.Sprite and PIXI.Graphics and
PIXI.Text. Tho I did build a sprite sheet that's shared between the two.

**Comment by ivanpopelyshev** [comment]
@weepy generateTexture?

**Comment by weepy** [comment]
Nope not even cacheAsBitmap

**Comment by GoodBoyDigital** [comment]
This issue is to do with sharing render textures across contexts. I would not recommend it but v4 should handle this type of situation better.
