### ISSUE TITLE
Cannot apply Filter to any Masked Sprite or Container

### ISSUE THREAD

**Issue by up209d** [pixijs/pixi.js#2585]
The issue from v2 now comes back to v4 which works fine on v3. What i did is,

Create Container
Create Background Sprite
Container Add the Background Sprite
Stage Add Container

Create Mask Sprite
Set Background Sprite Mask is Mask Sprite
Stage Add Mask Sprite

Create Displacement Sprite
Create Displacement Filter from that Displacement Sprite

Set Filter of the Background or Container to Displacement Filter

Stage Add the Displacement Sprite

=> pixi.min.js [sm]:17231 Uncaught TypeError: Cannot read property 'apply' of undefined

Is there anyone have the same problem with me ? Thank for the great beloved framework.

**Comment by ivanpopelyshev** [comment]
demo please? I will happy to fix that thing, i already fixed a bit for DisplacementFilter.

**Comment by up209d** [comment]
Wow, what a lightning response. Here the example i write on pixi example site. Thank you so much.

var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

// create a texture from an image path
var texture = PIXI.Texture.fromImage('_assets/basics/bunny.png');

// create a new Sprite using the texture
var bunny = new PIXI.Sprite(texture);

// center the sprite's anchor point
bunny.anchor.x = 0.5;
bunny.anchor.y = 0.5;

// move the sprite to the center of the screen
bunny.position.x = 200;
bunny.position.y = 150;

stage.addChild(bunny);

var maskBunny = new PIXI.Sprite.fromImage('_assets/basics/bunny.png');
stage.addChild(maskBunny);

**// If this line is active, it will return error apply of undefined
bunny.mask = maskBunny;**

// Filter
var displacementSprite = PIXI.Sprite.fromImage("http://i.imgur.com/2yYayZk.png");
var displacementFilter = new PIXI.filters.DisplacementFilter(displacementSprite);

// Apply it
bunny.filters = [displacementFilter];

stage.addChild(displacementSprite);

// start animating
animate();
function animate() {
    requestAnimationFrame(animate);

    // just for fun, let's rotate mr rabbit a little
    bunny.rotation += 0.1;
  
  	displacementSprite.position.x += 10;

    // render the container
    renderer.render(stage);
}

**Comment by ivanpopelyshev** [comment]
Ok, confirmed: Two masks/filters inside each other are not working at all, FilterManager.pushFilter and popFilter are wrong.

**Comment by GoodBoyDigital** [comment]
good catch! will take a poke around

**Comment by GoodBoyDigital** [comment]
done! 👍
