### ISSUE TITLE
Circle's position.x, position.y & .x, .y are always 0. Is it a bug?

### ISSUE THREAD

**Issue by fangqiao** [pixijs/pixi.js#2589]
I am trying to create a classic ball pendulum animation with PIXI.

I used dot1 = PIXI.Graphics.drawCircle(...) to create a circle then tried to move it through setting the circle's .x & .y property through a tween. I saw the circle jumped to an unexpected place by setting the .x, .y value, which i supposed to be upper left corner of the circle's bound rect.

I used console.log(dot1.x + ',' + dot1.y) to show the position after the dot was added to its container, which surprisingly was 0,0.

Is it a bug? I expect that when drawCircle is called its position is calculated immediately.

Below is the code. I use the latest Google Chrome and PIXI 3.0.11. 

  	var dot1 = new PIXI.Graphics();

	dot1.beginFill(0x528B8B);

  	dot1.drawCircle(5 - 60 * Math.sin(0.3) , 60 * Math.cos(0.3), 5);

	dot1.endFill();

        parent.addChild(dot1);
        
        console.log(dot1.x + ',' + dot1.y);
        console.log(dot1.position.x + ',' + dot1.position.y);

**Comment by ivanpopelyshev** [comment]
that's not how Graphics works: its a collection of primitives. How do you think it will determine center of TWO circles, for example?

Center of circle is somewhere in dot1._graphicsData[0]. 

```js
dot1.drawCircle(0, 0, 5);
dot1.position.set(5 - 60 * Math.sin(0.3) , 60 * Math.cos(0.3));
```

If you want to get some info about primtives inside dot1, use dot1.getLocalBounds() or dot1.getBounds()

**Comment by fangqiao** [comment]
thanks for the reply. 

Are you saying that a single PIXI.Graphics object can draw multiple shapes? Tested again by using the dot1 object to draw another circle. It works. But by looking into the children property, i found out its an empty array, meaning the two circles are not children of the PIXI.Graphics object.

Basically you can't use the child object approach to manipulate the circles individually. I am wondering why it was designed in this way. And also the documentation could be clearer.

**Comment by englercj** [comment]
The Graphics object contains primitive drawing information, it was designed to act like the canvas drawing APIs.

It has a position in the scene, and it draws the objects you draw in it at their offset positions from its own. You can draw as many or as few shapes as you want with it.

**Comment by ivanpopelyshev** [comment]
@fangqiao there are two more options for primitives.

```js
//first option, draw one time and use Sprite 
var tex = renderer.generateTexture(graphics);
var spr = new PIXI.Sprite(tex);

//second option: sometimes HTML5 canvas API is better than pixi.
// assume that you drawn your graphics on "canvas" element
var tex = new PIXI.Texture(new PIXI.BaseTexture(canvas));
//use sprite, again.
var spr = new PIXI.Sprite(tex);

```

**Comment by fangqiao** [comment]
Thanks for the clarification.

One suggestion though. I just started to try PIXI. I found it's DOM like object tree very helpful. But I think if you can improve either in code or documentation your coordinate systems on renderer or containers or graphics objects, it would be very helpful for your users. It would even be better if you can provide custom world coordinate support for containers. It would be another killer feature.

**Comment by fangqiao** [comment]
Thanks for the clarification. It helped a lot.
