### ISSUE TITLE
addChild improperly coded?  returns 1 child only

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#2597]
I was trying to 'properly' extend a Container using Typescript when I ran across the following:

The Container.addChild routine is a bit weird.
I never used to add multiple children with 1 addChild call, but was forced to look at it when extending the container and Typescript complained.

When you add 1 child, it returns the added child.
When you add multiple children, it still only returns only 1 child.

That is a bit odd.
(also, I have no clue how to properly do override this in Typescript, see [https://github.com/pixijs/pixi-typescript/issues/57] )

I don't know how much this multiple-child-adding is used. but wouldn't it be better to have 1 addChild function and 1 addChildren?   the one returning the same child, or array of children if multiple are added?

That way you also don't have to do the check if 1 or multiple params are used. everytime you add a child (which can get called a LOT of you implement some kind of sorting)

**Comment by ivanpopelyshev** [comment]
We have discussed it before in PIXI slack chat, assume that it will return void.

**Comment by whizzkid** [comment]
I never use the return of an addchild myself, so thats fine.

Still.   separate functions for addChild, and addMultipleChildren ?

**Comment by ivanpopelyshev** [comment]
@whizzkid Good idea. yes.

**Comment by bigtimebuddy** [comment]
Multiple methods for adding a single child or multiple children is unnecessary. Argument spread is useful for just this reason. I think this comes down to convenience:

```js
// This is convenient
var sprite = container.addChild(new Sprite());

// This is slightly less convenient
var sprite = new Sprite();
container.addChild(sprite);
```

When adding multiple children, I don't think the return value is that useful. 

```js
// This is convenient
container.addChild(new Graphics(), new Container(), new Sprite());

// This is slightly less convenient
container.addChild(new Graphics());
container.addChild(new Container());
container.addChild(new Sprite());
```

If you don't care about the return value, then like Ivan said, consider it void.

**Comment by whizzkid** [comment]
Having multiple methods also has a small speed advantage. 
I've never used the multiple children method. so for every addChild, an unneccesary arguments.length and an if-statement gets executed.

And when you use z-sorting for example, you'll be doing a lot of addChild's  every frame. so PIXI could be a little faster if it had a separate function :)

**Comment by GoodBoyDigital** [comment]
Hello @whizzkid, absolutly understand your perf concerns. Good news is this function has been speed tested a lot as initially we were concerned about possible implications of accessing arguments. As it turns out there are specific ways of dealing with it that end up having zero impact on perf. 

If you are doing a lot of depth sorting, I would recommend accessing the ```children``` and applying a sort function directly to the array - its super fast!

**Comment by whizzkid** [comment]
Good tip, thanks.

**Comment by clark-stevenson** [comment]
So just to confirm! Nothing is changing on the pixi front?

The signature is essentially:

`addChild(...child: DisplayObject[]): DisplayObject` 

But I think that needs to be specifically explained in the Doc.  I have passed over the code, and looked at 2 tickets and I still don't know what this does.  It is not obvious. 

`container.addChild(c1, c2).addChild(c3)`

**Comment by ivanpopelyshev** [comment]
Can someone make a PR for that already?

**Comment by bigtimebuddy** [comment]
I'm going to close this issue. Comments about the `addChild` usage (i.e., documentation) can be added to #2602
