### ISSUE TITLE
getBounds returns wrong values

### ISSUE THREAD

**Issue by mathieuanthoine** [pixijs/pixi.js#2599]
In getBounds, there a test on _currentBounds to avoid recalculation but if getLocalBounds is called just before getBounds, the _currentBounds matrix is changed to the local Matrix resulting in wrong value for getBounds

For example I ask for the height of an Object (calling getLocalBounds). If I call getBounds just after asking the height and before render, getBounds return a wrong value

**Comment by mathieuanthoine** [comment]
maybe it needs different cache for getLocalBounds and getBounds ?

**Comment by mathieuanthoine** [comment]
`Container.prototype.getLocalBounds = function ()
{
	var matrixCache = this.worldTransform;
    this.worldTransform = PIXI.Matrix.IDENTITY;
    for (var i = 0, j = this.children.length; i < j; ++i) this.children[i].updateTransform();
    this.worldTransform = matrixCache;
    this._currentBounds = null;
   var lBounds=this.getBounds( PIXI.Matrix.IDENTITY );
   this._currentBounds = null;
   return lBounds;
};`

This is a proposal to fix the bug

**Comment by mathieuanthoine** [comment]
a reason for closing please ?

**Comment by ivanpopelyshev** [comment]
@mathieuanthoine somehow you did close it yourself :)

**Comment by mathieuanthoine** [comment]
hahahaha thank you @ivanpopelyshev ... stupid I am :)

**Comment by GoodBoyDigital** [comment]
fixed 👍
