### ISSUE TITLE
Problem with Displacement Filter in v4, utils.uid(), glShaderKey ???

### ISSUE THREAD

**Issue by up209d** [pixijs/pixi.js#2600]
![problem](https://cloud.githubusercontent.com/assets/3246881/15515294/c75752ea-2230-11e6-89cd-aa25b921fc37.png)

Hi everyone ! I m playing around with Displacement Filter, i created displacement filters for few container s and the root container(stage) as well, so i tried to use and not to use power of 2 sized texture. But i still get this problem with v4, everything work fine with v3. I found that the problem is caused by the glShaderKey, if i change that to other value like 9999, everything work fine. Is that a bug or i missed something? Thank you.

**Comment by ivanpopelyshev** [comment]
Four more things? WOW

**Comment by GoodBoyDigital** [comment]
hi @up209d you stil getting this in latest dev branch?

**Comment by bQvle** [comment]
It does still have some unresolved filter bugs:
https://github.com/pixijs/pixi.js/issues/2595

Maybe many of these issues are offsprings of a core issue. (maybe related to sprite-batching?)

**Comment by up209d** [comment]
http://i.imgur.com/OLeRnOM.png

Hi @GoodBoyDigital, it s still there when i stop assign random value of glShaderKey.

**Comment by englercj** [comment]
I know you have been asked this before, but would you please retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
