### ISSUE TITLE
Possible leak when clearing PIXI.Graphics() / IE 11.0 memory leak

### ISSUE THREAD

**Issue by thesunlover** [pixijs/pixi.js#2605]
in Graphics.clear() there is no call for clearing or destroying the graphicsData array. or at least I don't see it in the VERSION: '4.0.0';
I'm trying to find why IE crashes with a NON-PIXI-related message: it says there is no more storage to complete an action (in my case rendering the stage)
I am not sure if this is the real cause for that.
thanks for any help provided
We are using some of the new functionality in v4 (compared to v3).
And probably these are causing the memory leak.
more: memory of IE11 process hits about 1.4 GB and then the crash happens.

**Comment by thesunlover** [comment]
problem solved by forcing the webgl renderer

**Comment by GoodBoyDigital** [comment]
closing as looks like its sorted 👍

**Comment by thesunlover** [comment]
@GoodBoyDigital 
well, it would be better if we can find a way to clear this.
Probably collection of garbage is better in the WebGL part of the code and in the Canvas fallback it might happen that it doesn't removes all the links to preparation related canvases. 
On most iOS devices performance is critically low, FPS is reduces drastically or browser crashes after loading. (all of our devices are equiped with not less than 1GB of RAM).
We found another related issue with FireFox and IE. When we repeat* refreshing the browser takes more and more resources and RAM goes up until browser stops responding or crashes. Restarting the browser fixes the  issue.
 Is it normal with those two 'fellas' to act like this?
___
1. holding ctrl+R for quick STR

**Comment by GoodBoyDigital** [comment]
Hello! Happy to take a look if you can provide a fiddle I can play with and debug.

 With regards to the refreshing the browser part - unless I'm mistaken its kind of outside of our control?
