### ISSUE TITLE
Uncaught TypeError: texture.addEventListener is not a function

### ISSUE THREAD

**Issue by Hidejec** [pixijs/pixi.js#2621]
I have a project created around 2014 using PIXI.js v1.5.3. It was working fine until started updating the pixi code to the latest version which is v3.0.10. **Uncaught TypeError: texture.addEventListener is not a function**. This is the error in the console. My app stops running after updating the pixi. This is my code 

```js
var preloadTextureList = function (list, callback, textureCallback ) {
		var at = len = list.length;
		return list = list.map(function (item) {
			var texture = PIXI.BaseTexture.fromImage(item);
			textureMap[item] = texture;
			var f = function(e) {
				e.content.removeEventListener('loaded', f);
				textureCallback && textureCallback.call(texture, texture, len-at, len);
				if(!--at) callback(list);
			}
			if( texture.hasLoaded ) {
				textureCallback && textureCallback.call(texture, texture, len-at, len);
				if(!--at) callback(list);
			}
			else texture.addEventListener('loaded', f)
			return texture;
		}); 
	}
	
	var textureMap = {}
```

**Comment by ivanpopelyshev** [comment]
what if you use "on" and not "addEventListener" ?

That code does same thing as async loader PIXI.loaders.Loader. Please use it instead. 

```js
loader = new PIXI.loaders.Loader();
loader.add('name1', '/img/url1.png');
loader.add('name2', '/img/url2.png');
loader.on('progress', progressCallback);
loader.on('complete', completeCallback);

function completeCallback() {
    var res = loader.resources;
    var sprite1 = new PIXI.Sprite(res['name1'].texture);
}
```

Also, you can pack all your stuff with texturePacker(paid) or shoebox(free) and load json+png atlas instead, that will speed up your rendering.

**Comment by bigtimebuddy** [comment]
@Hidejec Texture extends [EventEmitter3](https://github.com/primus/eventemitter3) which means that the function you're looking for is `texture.addListener` or `texture.on` not `texture.addEventListener`.

**Comment by GoodBoyDigital** [comment]
seems resolved! 👍
