### ISSUE TITLE
Sprite width,height different in v4

### ISSUE THREAD

**Issue by cvissie** [pixijs/pixi.js#2623]
Not sure if this is related to #2599 

In v4 sprite.width and sprite.height reports different widths and heights for trimmed images than in v3.

```javascript
  var renderer = new PIXI.WebGLRenderer(800, 600);

  document.body.appendChild(renderer.view);

  var stage = new PIXI.Container();

  var bunny = null;

  // load the texture we need
  PIXI.loader.add('sprites', 'sprites-0.json').load(function (loader, resources) {
    bunny = PIXI.Sprite.fromFrame("0.png");
    bunny.position.x = 400;
    bunny.position.y = 300;
    stage.addChild(bunny);

    var bounds = bunny.getLocalBounds();

    var rect1 = new PIXI.Graphics();
    rect1.lineStyle(2, 0xff0000, 1);
    rect1.drawRect(bunny.x, bunny.y, bunny.width, bunny.height);
    rect1.endFill();
    stage.addChild(rect1);

    var rect2 = new PIXI.Graphics();
    rect2.lineStyle(2, 0x00ff00, 1);
    rect2.drawRect(bunny.x, bunny.y, bounds.width, bounds.height);
    rect2.endFill();
    stage.addChild(rect2);

    animate();
  });

  function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
  }
```

![image](https://cloud.githubusercontent.com/assets/571532/15780465/1ab4069a-29a2-11e6-872f-4f056c7b2eae.png)

![image](https://cloud.githubusercontent.com/assets/571532/15780459/16334aea-29a2-11e6-8b07-d3b6c8f8b777.png)

As seen above. v4 is returning the trimmed width and height (red rectangle) compared to v3 (source width and height)

This is using the latest in the dev branch.

I'll test now using the last published by mat.

**Comment by ivanpopelyshev** [comment]
Its related to bug #2565, and its fix #2567, which was actually wrong. I'm gonna to rewrite it.

**Comment by ivanpopelyshev** [comment]
Fixed.

**Comment by cvissie** [comment]
Ivan you are a legend.

I think we can mark this as closed?

**Comment by ivanpopelyshev** [comment]
This one - yes, but there are other bounds issues that we are fighting right now.
