### ISSUE TITLE
TilingSprite is not supported on Firefox

### ISSUE THREAD

**Issue by up209d** [pixijs/pixi.js#2625]
By this example:

https://pixijs.github.io/examples/index.html?s=basics&f=tiling-sprite.js&title=Tiling+Sprite&v=dev

and all TilingSprite in my project doesn't work on Firefox.

> Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D texture, with a minification filter requiring a mipmap, and is not mipmap complete (as defined in section 3.7.10). pixi.js:602:1
> Error: WebGL: Drawing without vertex attrib 0 array enabled forces the browser to do expensive emulation work when running on desktop OpenGL platforms, for example on Mac. It is preferable to always draw with vertex attrib 0 array enabled, by using bindAttribLocation to bind some always-used attribute to location 0.
> 

P/S: v3 works like a charm but v4 does not.

**Comment by ivanpopelyshev** [comment]
It works for me in both standart and nightly version. How exactly did you create that texture? Did you resize it somehow?

**Comment by alamboley** [comment]
The link doesn't work for me neither on Firefox OS X but works on Chrome.

**Comment by up209d** [comment]
@ivanpopelyshev I just did the very basic thing without any movement, scaling, rotating and alpha. Mine is also lastest Firefox OSX.

**Comment by GoodBoyDigital** [comment]
all fixed! 👍
