### ISSUE TITLE
generateTexture with SpriteMaskFilter

### ISSUE THREAD

**Issue by louisatome** [pixijs/pixi.js#2629]
I try to generate a texture from a Sprite which have a SpriteMaskFilter but the generated texture doesn't keep the mask as it is defined on the source Sprite.

Example : https://jsfiddle.net/Lojzdoxj/1/

Maybe this is not the right way to do it, any information would be welcome ;)

**Comment by up209d** [comment]
You was wrong at using graphic.generateTexture. Take a look in documentation that:

> generateTexture(resolution, scaleMode){PIXI.Texture}
> 
> core/graphics/Graphics.js, line 695
> Useful function that returns a texture of the graphics object that can then be used to create sprites. This can be quite useful if your geometry is complicated and needs to be reused multiple times.

It is used to generate texture of the graphic object itself, there no relation to your bunny mask as it is another object. In addition, the param you parse in is 'renderer' and that is totally not proper param. I suggest you can put the graphic and the bunny mask in a container and use RenderTexture to render that container.

[](https://jsfiddle.net/t19xom95/)

**Comment by louisatome** [comment]
Thanks a lot for the correction ;) It works with a container which include both the object and the mask!
I wrote my example too fast, in my "real" issue, the object i use is a Sprite that's why i call the generateTexture with the renderer in param. Anyway thanks again! 
Updated example : https://jsfiddle.net/Lojzdoxj/2/
