### ISSUE TITLE
v4 wrong width/height behaviour of PIXI.Graphics and PIXI.Container

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#2631]
```js
var renderer = new PIXI.WebGLRenderer(800, 600);

document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

var g = new PIXI.Graphics();
g.beginFill(0xff00ff, 0.5);
g.drawRect(0, 0, 100, 100);
g.endFill();
stage.addChild(g);

setInterval(function(){ g.width = 200; console.log(g.width); }, 1000);

animate();

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

Expected result: after one second the graphics object resizes to width 200 and is not resizing anymore
Actual result: the graphics object width jumping from 100 to 200 every second

Edit: also PIXI.Container has problems with width and height:

```js
var renderer = new PIXI.WebGLRenderer(800, 600);

document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

PIXI.loader.add("test", "bunny.png").load(function() {

    var c = new PIXI.Container();
    stage.addChild(c);

    console.log("container w/h", c.width, c.height); // correct (0,0)

    bunny = PIXI.Sprite.fromImage("bunny.png");

    console.log("bunny w/h", bunny.width, bunny.height); // correct

    c.addChild(bunny);

    console.log("container w/h", c.width, c.height); // incorrect (0,0) should be the same size as bunny

    setTimeout(function() {
        console.log("container w/h", c.width, c.height); // correct
    }, 500);

    animate();
});

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

**Comment by ivanpopelyshev** [comment]
WOW that's a good bug!

**Comment by whizzkid** [comment]
I'm experiencing the same. 
width is not set correctly on containers before the 1st render call.

**Comment by whizzkid** [comment]
vertexData is all zeroes when you do getbounds before a render() so the getbounds function doesnt work properly

**Comment by ivanpopelyshev** [comment]
So we need to lazily compute vertexData, even without render

**Comment by whizzkid** [comment]
I've been stepping through the code a bit
vertexdata gets calculated for _renderWebGL 
but canvasrenderer also gives a wrong result.

**Comment by whizzkid** [comment]
scratch that. my test is using webgl even when i switched to canvas mode.
gonna try to see if real canvas rendering also has this problem

**Comment by whizzkid** [comment]
yeah. so canvasrenderer also has the same issue. and that's NOT 'fixed' by calling a render().

**Comment by whizzkid** [comment]
That should be it :)

**Comment by whizzkid** [comment]
@ivanpopelyshev did you see the 2nd commit?

I only pushed it to my fork, but git says/shows that it was part of the first pull request when i tried to make a 2nd one.
But it hasnt been merged.. and i can't make a 2nd pull request because it already said this one exists....

**Comment by ivanpopelyshev** [comment]
@whizzkid I dont haver access to pixijs repo :(

**Comment by whizzkid** [comment]
thanks, i hope it works. github confuses me :P

**Comment by ivanpopelyshev** [comment]
@whizzkid I had those kind of problems, now i just have multiple branches for that, my own fork, and even something that comes as a plugin but can be made into PR: https://github.com/gameofbombs/pixi-display

I have the same idea about width/height and I think your solution is not correct: getLocalBounds() does not care about scale at all

**Comment by whizzkid** [comment]
yeah i cancelled it, something's still wrong.

**Comment by whizzkid** [comment]
@ivanpopelyshev  What's your opinion about the Sprite fix with this.calculateVertices(); ?

**Comment by ivanpopelyshev** [comment]
@whizzkid This commit was merged: https://github.com/pixijs/pixi.js/pull/2624 , may be you didnt see it :)

**Comment by whizzkid** [comment]
@ivanpopelyshev I did see it, but that one still has the problem where your sprite size is incorrect before the 1st render call.

**Comment by whizzkid** [comment]
Using the current DEV version.


You don't notice the error if you simply add stuff when you create it.
when you move stuff between containers, thats when bad stuff happens.

I havent got time to make a fiddle for this, but here's my (typescript) code
basically:  create a container, with a gfx and a sprite.    add it to stage
create another container somewhere on stage.
now, after a while, add your first container to the second one.
nothing wrong,
now add it back to the stage again.
BAM.  width is totally wrong, because it takes an incorrect screen-position into account.


```
	public start()
	{
		this.container = new PIXI.Container();
		this.stage.addChild(this.container);
		this.mySprite = this.createSprite();
		this.stage.addChild(this.mySprite);

		this.container.position.set(300, 100);

		setTimeout(this.step1.bind(this), 1000);
		setTimeout(this.step2.bind(this), 2000);
		this.render();


	}

	private step1()
	{
		console.log("Step1");
		this.container.addChild(this.mySprite);
		console.log(this.mySprite.width); // the width is 118, this is correct
	}

	private step2()
	{
		console.log("Step2")
		this.stage.addChild(this.mySprite);
		console.log(this.mySprite.width) // width is now 415.5 .. that is NOT Correct
	}

	public createSprite()
	{
		var container = new PIXI.Container();

		var gfx = new PIXI.Graphics();
		gfx.beginFill(0xff0000);
		gfx.lineStyle(13, 0xffffff);
		gfx.drawRoundedRect(0, 0, 105, 60, 10);
		gfx.endFill();
		container.addChild(gfx);

		var sprite = PIXI.Sprite.fromFrame("50x50.png")
		sprite.position.set((gfx.width - sprite.width) / 2, (gfx.height - sprite.height) / 2);
		container.addChild(sprite);
		return container;
	}

private render()
	{
		this.requestAnimationFrameId = requestAnimationFrame(this.boundRender);
		this.renderer.render(this.stage);	
	}

```

**Comment by whizzkid** [comment]
![100x50](https://cloud.githubusercontent.com/assets/323372/15934102/8b5c1184-2e62-11e6-9cb2-0511d56c8279.png)

**Comment by whizzkid** [comment]
the image used in the example

![100x50](https://cloud.githubusercontent.com/assets/323372/15934138/aff8a02a-2e62-11e6-8af1-06d8deea3246.png)

**Comment by ivanpopelyshev** [comment]
What if you use https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js ?

**Comment by ivanpopelyshev** [comment]
Ok, so, Graphics issue that Graphics._localBounds sometimes are not defined.

**Comment by ivanpopelyshev** [comment]
OK! I've got it, I know what is wrong! Preparing huge PR, its architecture problem with many loose cases.

**Comment by whizzkid** [comment]
Awesome, am anxious to test :)

**Comment by rkrasky** [comment]
Sorry to annoy @ivanpopelyshev... what's the status of the PR?

**Comment by ivanpopelyshev** [comment]
@rkrasky Working on it. https://github.com/pixijs/pixi.js/issues/2642

**Comment by whizzkid** [comment]
@ivanpopelyshev Your pull request isn't merged yet, is there a way I can already test it? (apart from copying all the changed from github by hand)

**Comment by ivanpopelyshev** [comment]
That one: https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js

**Comment by whizzkid** [comment]
Thanks, cool. 
that fixed part of my problems with sprites.  now all thats left are the Graphics to work properly.  
I shall wait patiently... :)

**Comment by ivanpopelyshev** [comment]
@whizzkid what are you talking about? Graphics is working

**Comment by whizzkid** [comment]
@ivanpopelyshev using your pixi.js,  and the test I posted above, I get different, but still incorrect results.

mySprite (containing gfx and a sprite)  width is 118 pixels in step 1.
When moved to the container, its 415.5 pixels, (in the old version, this was still 118) 
and when moved back, its also 415.5 pixels. (while in actual size on screen, its 118 pixels)

when mySprite only contains the Sprite and not the gfx, the widths are correct in all 3 steps

**Comment by whizzkid** [comment]
It works now!
I was writing a jsFiddle with your pixi.js just now, and couldn't get the error reproduced. copied the js code to my working project again, and now the graphics behave like they should.

**Comment by ivanpopelyshev** [comment]
@whizzkid It is because I swapped the file with current version. It does not have my getBounds() optimizations :(

**Comment by ivanpopelyshev** [comment]
your demo works with latest pixi-v4 and with my patch too.

**Comment by rkrasky** [comment]
Thanks a lot!

**Comment by ivanpopelyshev** [comment]
Yeah, I added into my PR, so I will be able to test it again if i change something else

**Comment by whizzkid** [comment]
@ivanpopelyshev Something's not right.
On a graphics object with only 1 rectangle,  just querying the width is enough to destroy the positioning.

see for demo (using your pixi version) 

https://jsfiddle.net/whizzkid74/j3wkcn7q/1/

and one with no tweening but simply setting position

**Comment by ivanpopelyshev** [comment]
TweenMax is using "_x" for a prefix, and our ObservablePoint is using the same. This is the fix:

```js
PIXI.TRANSFORM_MODE.DEFAULT = PIXI.TRANSFORM_MODE.DYNAMIC;
var stage = new PIXI.Container();
```

**Comment by whizzkid** [comment]
Try the second example too please.
that one uses no tweening, and also has the same error.

and the fix you mentioned has no result when I use it in the fiddles.

**Comment by whizzkid** [comment]
btw, this error doesn't affect the gfx object with the circle in it.
They should react the same if the _x thing was the issue

**Comment by ivanpopelyshev** [comment]
Ok, that's a bug. Second fiddle is not working.

**Comment by whizzkid** [comment]
Howabout this one?
https://jsfiddle.net/whizzkid74/1wkpkspy/3/

**Comment by ivanpopelyshev** [comment]
OK, that's bug somewhere in the graphics

**Comment by ivanpopelyshev** [comment]
Try this one : https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js

**Comment by whizzkid** [comment]
That works!
