### ISSUE TITLE
.atlas files do not run by default under IIS

### ISSUE THREAD

**Issue by ayyash** [pixijs/pixi.js#2632]
I had to add .atlas as a mimetype to IIS to make a demo work, that uses .atlas file. My question is, is this limited to local environment? Or am I going to face the same issue when I deploy to an IIS server? Notice I may not have admin rights to add mimetype to remote server.

**Comment by ivanpopelyshev** [comment]
"*.atlas" files are text files for spine, right? You can edit "pixi-spine" plugin that way its using ".txt" instead of atlas. I can add that option and rebuild it, if you dont want to change the library code.

Are you using latest pixi-spine for v3/v4, or the one that was integrated in pixi v2?

I dont know if anyone actually uses IIS for that kind of projects. node.js and nginx dont have that problem.

**Comment by whizzkid** [comment]
We use IIS and also had to add .atlas, otherwise the server wouldn't serve the files.. 

An option to change the extention for atlas files would be helpful for those who can't change mimetypes in their server.

**Comment by ivanpopelyshev** [comment]
Please rename ".atlas" to ".txt" and try https://dl.dropboxusercontent.com/u/46636530/pixi-spine/pixi-spine.js with this code

```js
var spineLoaderOptions = { metadata: { spineAtlasSuffix: '.txt' } };
loader.add('animation', 'assets/spineboy.json', spineLoaderOptions);
```

If it works for you, I'll push it in pixi-spine github and npm.

**Comment by ayyash** [comment]
I added (using latest of pixi)

```
var spineLoaderOptions = { metadata: { spineAtlasSuffix: '.txt' } };
PIXI.loader
    .add('pixie', '_assets/spine/Pixie.json', spineLoaderOptions)
    .load(onAssetsLoaded);
```

This works perfectly. To answer your question about IIS, I love Node but for client-side projects IIS is too convenient to switch away from :)

Highly appreciate it

**Comment by ivanpopelyshev** [comment]
Nice! I uploaded the patch in both github and npm, also added explanation in README. Please close the issue.

**Comment by whizzkid** [comment]
nitpick. but i think spineAtlasExtension would be more appropriate than spineAtlasSuffix?
since we're really talking about a file extension here and not 'text added to a word'

**Comment by ivanpopelyshev** [comment]
@whizzkid Its also possible hack for things like "@2x.atlas".

**Comment by whizzkid** [comment]
I don't think you'll ever need that.  you can change the filename without hacks, 

bla.atlas and bla@2x.atlas

they both should be read as a '.atlas'   so it still only refers to the extention.
