### ISSUE TITLE
Texture atlas with webpack

### ISSUE THREAD

**Issue by LucianoGraziani** [pixijs/pixi.js#2633]
Hello, I'm trying to use PIXI along with webpack, but I can't make work texture atlas. This is how I did it:

```javascript
pixiLoader.add(require('images/dungeon/treasureHunter.json')).load(function setup() {
  // Create an optional alias called `treasureHunter` for all the texture atlas
  treasureHunter = pixiLoader.resources[require('images/dungeon/treasureHunter.json')].textures;

  // Make the treasure box using the alias
  treasure = new Sprite(treasureHunter['treasure.png']);
```

I'm using relative paths provided by webpack. And the file-loader for JSON files (this way I can get the correct URL). This is what I have in my webpack file:

```javascript

export default {
  // Other configure

  resolve: {
    root: __dirname,
    modulesDirectories: [
      'node_modules',
      'src',
      'assets',
    ],
    alias: {
      applicationStyles: 'src/styles/app.scss',
    },
    extensions: ['', '.js', '.jsx'],
  },
  module: {
    loaders: [
      // other loaders

      // pixi uses fs.readFileSync and require()s json files
      {
        test: /\.js$/,
        loaders: ['transform?brfs'],
        include: /node_modules/,
      }, {
        test: /\.json$/,
        loaders: ['file'],
      },
    ],
  },
};
```

The `modules_directory` option let me use relative paths. So, when I use `require('images/dungeon/treasureHunter.json')`, It will return something like this:

`http://localhost:3000/afad27bffb5e0a23373ac809405f0832.json`

The problem is: The JSON atlas points to `treasureHunter.png` and not to the webpack generated url for that file. So, it loads the JSON OK, but throws a 404 trying to get the image.

Someone know how to fix that?

Thank you.

**Comment by LucianoGraziani** [comment]
Well, I "fixed" it by printing the hash name file of my `treasureHunter.png` file, and including it to the JSON atlas file. It worked.

**Comment by magnus-bergman** [comment]
Did you update the atlas manually or did you get it to include the hash within the bundle process?

**Comment by LucianoGraziani** [comment]
No, I had to update the atlas manually. Of course, I didn't pay much time to that.
And yes, every time my tileset changes, I have to update that reference.

I don't know how to update my reference within the bundle process, that would be the easiest (and correct) solution. Because, if you want to pass an object to the loader, you have to customize the PIXI.loaders.Loader class.

**Comment by scottmcdonnell** [comment]
Another way to avoid this is to not `require ` your files - We used the[ copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin) to avoid this, we keep our spritesheet files in an assets directory which gets copied to your output directory - then use the pixi loader as normal.

in your webpack config you can do
```
var CopyWebpackPlugin = require('copy-webpack-plugin');
...
plugins: [
  new CopyWebpackPlugin([
 {
      from: 'src/assets',
      to: 'assets'
    }
]
```

**Comment by LucianoGraziani** [comment]
I did it! And let me use imports (better when using webpack-dev-server since doesn't output any file).

I added this into my file-loader for my images on my webpack.config.js file:

```js
{
  test: /\.(jpe?g|png|gif)$/i,
  loaders: ['file?name=[path][name].[ext]'],
},
```

This way will keep the path ontouched. Here is an example:

![webpack-report](https://cloud.githubusercontent.com/assets/15050200/16892653/ce99b334-4af0-11e6-88d5-66d63601c701.png)

This can be closed.

**Comment by GoodBoyDigital** [comment]
nice one chaps! 👍

**Comment by scottmcdonnell** [comment]
Just to follow on - if you use copy-webpack-plugin method I gave above this will work with the webpack-dev-server by setting the [--content-base](https://webpack.github.io/docs/webpack-dev-server.html#content-base) for example in package.json:
```
"start": "webpack-dev-server --inline --progress --profile --colors --watch --display-error-details --display-cached  --content-base src/"
```
