### ISSUE TITLE
My Little PIXI : z-indices are magic

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2634]
It is my third iteration of z-indexing algorithm.

[Github](https://github.com/gameofbombs/pixi-display)

[Example](http://pixijs.github.io/examples/index.html?s=display&f=zorder.js&title=Z-order&plugins=pixi-display&v=dev)

Basically, API allows to re-order elements without changing the scenegraph.

Performance: sorting applies ONLY to elements that have specified displayGroup and are renderable. Their children can be either ignored, either to render with the parent, either be sorted too if their displayGroup is set.

Use-cases: shadows, dragging, ordering of game sprites from farthest to nearest.

I hope code is understandable, it has enough jsdocs, and it can be easily integrated inside pixi.js.

@GoodBoyDigital I propose to merge it into pixiv4.

@photonstorm I need your opinion on that API, because you know what pain is to sort stuff every frame inside Phaser.Group

**Comment by ivanpopelyshev** [comment]
1. create some DisplayGroup , each has a z-index
2. assign them to some of displayObjects (as shared component)
3. assign displayList to root container (as a component)
4. displaylist looks inside subtree and sorts all the displaygroups that appear there, also filling the list for each displaygroup, which elements belong to that group
5. all elements that don't have displayGroup are added in "displayChildren" list of first parent that has it.
6. inside each DisplayGroup you can specify sorting algorithm, if it is needed. (sort by y-coord or something like that)

SO

1. compatible with other implementations: just assign each element its own DisplayGroup. All elements will be sorted
2.  optimized for cases when you already know that 1000 elements have the same z-index: just assign them the same DisplayGroup
3. optimized for cases when you know that some displayObjects follow natural order of things (rendered just after parent), even if their "brothers"
4. optimized for cases like "ParticleContainer", you can set special DisplayFlag to container that way displayList wont like inside it.

Filters and masks can appear only at root or in leafs. If all subtree have DisplayGroup=null it can be considered a leaf. If there is something like filter or mask on element, we consider it a leaf and dont go inside.

**Comment by kaansoral** [comment]
I would also love to see pixi-display absorbed into pixi

In it's most basic form it allows practical layers, my game is still 60fps, with sorting enabled

It's also extremely practical to integrate

Off topic, I wonder how the performance would be when there are ~2-3K entities on a scene, I guess I will try it soon out of curiosity

**Comment by ivanpopelyshev** [comment]
You can cull something (make renderable=false) before sorting takes place. We can add special event "beforeUpdate" on displayList for that :)

Also I have an idea of how to handle rendering 10K entities if most of them are static (tiles, map background), I'll post this experiment soon :)

**Comment by DubiousDillan** [comment]
Is this going to be added into the official PIXI?
How would I go about using it with Node? Can I just require the file into place?

**Comment by ivanpopelyshev** [comment]
Only if @mat uses it in one of his games. No, the file uses global names. Also, there's new experimental version: https://github.com/pixijs/pixi-display/tree/layers , with example: http://pixijs.github.io/examples/#/layers/lighting.js

**Comment by themoonrat** [comment]
Closing as people can use your plugin @ https://github.com/pixijs/pixi-display/tree/layers for this
