### ISSUE TITLE
Pixi js v4 - Almost good to go!

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#2642]
Good news everyone! Version 4 of of Pixi is almost good to go. We are very confident with where its at. So confident that at Goodboy studios we have shipped two live games worth v4 and have many more in the pipeline. Its pretty much there AND 99.99% compatible with v3. 

There are still a few things left to do before we move it to master. Heres the list:

- [x] Fix the getBounds / getLocalBounds issues ( @ivanpopelyshev )
- [x] Merge new static transform PR once we have verified that it works as intended ( @bigtimebuddy )
- [ ] Add a collection of visual unit tests ( @bigtimebuddy )
- [x] Fix up Blur filter to be more developer friendly ( @goodboydigital )
- [x] Documentation pass 
- [x] Convert v3 filters to v4 - or at least prune out the ones we won't convert for launch

Team Pixi will be working on getting these sorted. If you want to help then please feel free to give me  a poke! Of course you can add any extra requests to this thread too if you think that they are essential. 

Obviously there are lots of great new features we want to add and will eventually - but for now the main goal here is to get v4 into the master branch as its already faster and better than v3 :)

**Comment by ivanpopelyshev** [comment]
> Add a collection of visual unit tests

Kinda difficult task. @bigtimebuddy you sure you can do it in a week?

**Comment by tomka** [comment]
Very nice, looking forward to it! Maybe not essential, but there is one thing that would be great to see in v4: Fixing the filter manager bug discussed in #1598. It is currently not possible to use a single filter and a blend mode at the same time. One additional filter (e.g. a VoidFilter), though, will make it work. This is not blocking, but something I could see many people running into (because Pixi has all these nice filters and makes blend modes easy) and it can be cumbersome to deal with this extra no-op filter (VoidFilter).

**Comment by ivanpopelyshev** [comment]
#2654 mine part is done. Though we need to test it with #2652 , I'm still waiting for actual demo of that bug.

**Comment by mushtat** [comment]
Good job, guys!
Just want to ask when v4 will go to master estimately? Few weeks or maybe few month?

And want to say thank you all for this great framework)

@GoodBoyDigital

**Comment by GoodBoyDigital** [comment]
Weeks I hope :)

**Comment by ivanpopelyshev** [comment]
#2660 #2657 have to be solved to guarantee backwards compatilibity of these particular features. Please to add them to that list.

**Comment by RanzQ** [comment]
Would it be possible to pre-release rc3 and publish it to npm? Currently v4 can't be installed using npm. :)

**Comment by cvissie** [comment]
I merged our company's code bases with PIXI v4 over the last few weeks.

The latest version is almost near perfect. There are a few ugly pops - no idea what that is about and I can't seem to replicate it as it appears randomly.

But apart from that the performance difference, especially on mobile is incredible.

**Comment by danwad** [comment]
It would be nice if #1763 could be looked at for v4.

**Comment by Dadibom** [comment]
Any progress on grayscale/invert filters? I miss them! :D

**Comment by GoodBoyDigital** [comment]
The ColorMatrix filter should help you out there! - most color effects can be managed through there now

**Comment by GoodBoyDigital** [comment]
pretty much there! well done chaps 👍
