### ISSUE TITLE
V4 cacheAsBitmap broken in some scenario

### ISSUE THREAD

**Issue by cvissie** [pixijs/pixi.js#2652]
I can't find the exact reason just yet...

I'm opening this issue for the time being. Wondering if anyone else is having issues with cacheAsBitmap?

I definitely had an issue with the following snippet. The graphics simply doesn't display.

```javascript
    _api.addDarkBkg = function (parent, x, y, width, height, alpha) {
      var bkg = new PIXI.Graphics();
      bkg.beginFill(0x000000, alpha);
      bkg.drawRect(0, 0, width, height);
      bkg.endFill();
      bkg.x = x;
      bkg.y = y;
      bkg.cacheAsBitmap = true;

      parent.addChild(bkg);
      return bkg;
    };
```

But I also this morning had an issue with a container that had cacheAsBitmap set to true.

Trying to find the reason now.

**Comment by cvissie** [comment]
Okay think I found the issue...

![image](https://cloud.githubusercontent.com/assets/571532/16071328/06e91136-32db-11e6-91a8-bb476a333a0a.png)

I assume this is related to #2642 i.e. Fix localBounds issues.

**Comment by ivanpopelyshev** [comment]
It is possible that #2654 will fix this.

**Comment by cvissie** [comment]
On it.

**Comment by ivanpopelyshev** [comment]
@cvissie can you test it on https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js ?

**Comment by cvissie** [comment]
```javascript
    var bounds = this.getLegacyLocalBounds().clone();
```

^^^

It is now reporting the right values in each of the scenarios i.e. Graphics and Container.

![image](https://cloud.githubusercontent.com/assets/571532/16277605/e8940266-38b3-11e6-80c5-abfb8dc6ac30.png)

For some reason the Graphics object is still not displaying right despite getting the right bounds...

Will see if I can pin point it.

**Comment by cvissie** [comment]
Also just want to say - this pixi build of yours has also broken the previous Container issue again :cry: 

Actually it seems it has broken renderer.generateTexture or rather renderer.render for some reason or another...

**Comment by ivanpopelyshev** [comment]
I still need a demo.

**Comment by cvissie** [comment]
@ivanpopelyshev 

https://dl.dropboxusercontent.com/u/21144013/pixi/examples.7z

Check the cvissie demo.

I actually tested using the latest version in the dev repo of github and the issue we had is resolved.

As it is, it's the most stable version of PIXI v4 we've had.

The only remaining issue is the drawRect cacheAsBitmap that's not working entirely right - that's also in the demo.

**Comment by GoodBoyDigital** [comment]
should be fixed in v4 👍
