### ISSUE TITLE
Error with multiple renderers/canvases

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#2657]
```
var stage = new PIXI.Stage(0x000000, {resolution:2});
var stage2 = new PIXI.Stage(0x000000, {resolution:2});

var renderer = new PIXI.WebGLRenderer(620, 400,  { transparent: true });
var renderer2 = new PIXI.WebGLRenderer(620, 400,  { transparent: true });
```

then

```
function animate() {
  stats.begin();
  .........
  renderer.render(stage);
  renderer2.render(stage2);
  requestAnimationFrame( animate );
  stats.end();
}
```

On ever ~3 (it's not constant) refresh i got this

pixi.js:5504 Pixi.js Error: Could not initialize shader.compileProgram @ pixi.js:5504Shader @ pixi.js:4762Shader @ pixi.js:9058generateMultiTextureShader @ pixi.js:20159SpriteRenderer.flush @ pixi.js:20061WebGLRenderer.render @ pixi.js:16354animate @ index.html:177
pixi.js:5505 gl.VALIDATE_STATUS falsecompileProgram @ pixi.js:5505Shader @ pixi.js:4762Shader @ pixi.js:9058generateMultiTextureShader @ pixi.js:20159SpriteRenderer.flush @ pixi.js:20061WebGLRenderer.render @ pixi.js:16354animate @ index.html:177
pixi.js:5506 gl.getError() 1281compileProgram @ pixi.js:5506Shader @ pixi.js:4762Shader @ pixi.js:9058generateMultiTextureShader @ pixi.js:20159SpriteRenderer.flush @ pixi.js:20061WebGLRenderer.render @ pixi.js:16354animate @ index.html:177
pixi.js:5511 Pixi.js Warning: gl.getProgramInfoLog() missing shaders

**Comment by trsh** [comment]
Here's the full code -> https://file.io/RJp8gd

**Comment by ivanpopelyshev** [comment]
Something something with Shader cache? Really?

**Comment by ivanpopelyshev** [comment]
Btw, Stage is deprecated.

**Comment by trsh** [comment]
> Something something with Shader cache?

I don't know. Is it?

**Comment by GoodBoyDigital** [comment]
should be fixed in v4 👍
