### ISSUE TITLE
problem with render too slow

### ISSUE THREAD

**Issue by iauther** [pixijs/pixi.js#2663]
hi, everyone

when use PIXI, I found that the render interval is too long, code as below:

       var stage = new PIXI.Container();
        var render = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight);
        document.body.appendChild(render.view);

        for (i=0; i<10; i++) {
            bt = PIXI.Sprite.fromImage('img/psh_silver.png');
            
            bt.on('mousedown', onDragStart);
            bt.on('touchstart', onDragStart);

            bt.on('mouseup', onDragEnd);
            bt.on('mouseupoutside', onDragEnd);
            bt.on('touchend', onDragEnd);
            bt.on('touchendoutside', onDragEnd);

            bt.on('mousemove', onDragMove);
            bt.on('touchmove', onDragMove); 
            bt.interactive = true;
            bt.buttonMode = true;
            bt.anchor.set(0.5);
            bt.x = 76;
            bt.y = 200;
            
            
            sp = PIXI.Sprite.fromImage('img/psh_bg.png');
            sp.position.x = 40+i*120;
            sp.position.y = 20;
            
            sp.addChild(bt);
            stage.addChild(sp);
        }
        
        var time = Date.now();
        requestAnimationFrame(update);

        
        function update() {            
            var now = Date.now();
            
            console.log("____ render interval: %d ms\n", now-time);
            
            time = Date.now();
            render.render(stage);
            requestAnimationFrame(update);
        }

        function onDragStart(event) {
    	    this.data = event.data;
    	   this.dragging = true;

    	}

    	function onDragEnd() {
    	    this.dragging = false;
            this.data = null;
    	}

	    function onDragMove() {
    		//console.log("_____ onDragMove\n");
    	    if (this.dragging)
            {
                var newPosition = this.data.getLocalPosition(this.parent);
                this.position.y = newPosition.y;
            }
    	}

PIXI version v3.0.10

the console log show that, render interval time is about 100ms, that is too long.how can I reduce it? Is there any wrong in my code?

any suggestion is appreciated.

**Comment by barbarosso** [comment]
Hi @iauther,
Is it possible to create a fiddle? It's easier to check then.
Thx

**Comment by iauther** [comment]
@barbarosso 

ok.

I create it in fiddle: https://jsfiddle.net/iauther/5ofzn329/
but it seems that there is some wrong in the external resources link.
So I add it in github:  https://github.com/iauther/pixi.git
Thanks for your apply.

**Comment by ivanpopelyshev** [comment]
Whats specs of your computer? Which browser is it?

**Comment by iauther** [comment]
@ivanpopelyshev 

win7:     Enterprise 64bits 
cpu:      AMD A8-5600K
brower: chrome V50.0.2661.94 m

**Comment by GoodBoyDigital** [comment]
closing this for now as seems like device issue. thanks all 👍
