### ISSUE TITLE
Some custom plugins

### ISSUE THREAD

**Issue by Nazariglez** [pixijs/pixi.js#2664]
Hello guys!

I made some plugins to use in my games, and I think may be usefull for someone who want audio, tweens, keyboard or game timers. So, my question is, exists any chance to include some of them into the plugin page (wiki). https://github.com/pixijs/pixi.js/wiki/Pixi-v3-Plugins

https://github.com/Nazariglez/pixi-keyboard
https://github.com/Nazariglez/pixi-timer
https://github.com/Nazariglez/pixi-audio
https://github.com/Nazariglez/pixi-tween

Thanks!

**Comment by englercj** [comment]
The page is editable, add them :) it is a wiki!

**Comment by Nazariglez** [comment]
Thanks @englercj!
