### ISSUE TITLE
PIXI.extras.MovieClip provide callback when animation finished

### ISSUE THREAD

**Issue by Rejpal** [pixijs/pixi.js#2665]
I am using PIXI.extras.MovieClip to play a short animation (about 60 frames) and due to not knowing how many FPS there will be on users device I can't tell how much time exactly does it take to play all the frames. setTimeout also does not guarantee that function will be triggered exactly after specified time so it's kinda not my way of solving this too.

When the playing of animation is finished I want to trigger some events in code to remove the MovieClip and write some logs.

The problem is that I can't find any kind of trigger/callback that will be called when last frame of animation was rendered.

example code:

movie = new PIXI.extras.MovieClip(someFrames);
movie.animationSpeed = 1;
movie.loop = false;
movie.onComplete = animationFinished;
movie.play()

animationFinished = function () {
  console.log("Animation just reached it's end.");
  movie.gotoAndStop(0);
};
the obvious problem is, that movie.onComplete is never called. Is there any way to make this work?

Thanks for any suggestions and ideas.

**Comment by themoonrat** [comment]
On the examples page: https://pixijs.github.io/examples/index.html?s=basics&f=spritesheet.js&title=SpriteSheet%20Animation

Below where the movie clip is created, I add

```
movie.loop = false;
movie.onComplete = function() { console.log('onComplete') };
```

Click the lovely green button to test it out, and the console log is outputting correctly when the animation finishes

**Comment by MattOstgard** [comment]
@Rejpal it looks like you are assigning the function before it is created. Just move the function up somewhere before movie.onComplete is set, or do what @themoonrat did and use an anonymous function.

**Comment by englercj** [comment]
Looks like this is answered.

**Comment by courtneyvigo** [comment]
Can one do this with text and images as well?
My goal is to "kill" the text once it moves off screen so I can create new ones

ex:
text1.onComplete = function() { stage.removeChild(text1) };

Thanks!

**Comment by themoonrat** [comment]
With the movie clip question, the movie clip itself knows when it's finished animating, and can thus provide a callback when that occurs.

For text and sprites, however, they don't know when they have 'finished' moving, only the thing that moves it does. 

So you'd want the code to check each frame
if (text1.x > 800 ) {
  text1.destroy();
}

Bonus tip, and pre empting what you may wish to do... don't keep creating and destroying text and sprite objects... Reuse them!

**Comment by courtneyvigo** [comment]
ok. Thanks for the info! So would I just update the innerHTML if I am reusing them?

**Comment by courtneyvigo** [comment]
Also, would that if statement go in the gameloop function?
