### ISSUE TITLE
deterministic simulation with pixi.js

### ISSUE THREAD

**Issue by Arnold1** [pixijs/pixi.js#2668]
Hi,

I use pixi.js for a simulation. I have a set of object which move and change change their direction. How goal is to make the simulation as deterministic as possible: I would like to have the objects moving in the same way for each run.

I used a random number generator with a fixed seed. For changing the direction I currently use a Timer which will be called every second. Because JS timers are not precise, my simulation is not deterministic any more. How to fix this issue?

what i have done so far:
https://jsfiddle.net/j8njn2x4/6/

Thanks,
A

**Comment by ivanpopelyshev** [comment]
Oh I love that kind of tasks!

I see a few possible solutions:
1. Round to millisecond, write down every delta time? That way you'll be able to replay it later.
2. don't use deltaTime, just do a fixed step.
3. decouple physics update from render update. Physics calculates trajectory for next step, render just interpolates it. Physics works at 10 (gameofbombs), 20 (minecraft, quake) or 30 (i dont remember) FPS, while rendering does what it wants.

**Comment by englercj** [comment]
Base your updates on the *elapsed time* or *delta time* between "now" and the last frame. That way when the timers are off, you are updating based on how much time actually passed instead of how much you thought should have passed.

**Comment by Arnold1** [comment]
@englercj could you show a short snippet to understand what you mean?

**Comment by englercj** [comment]
Something along these lines:

```js
var lastFrame = 0;

function animate() {
    requestAnimationFrame(animate);

    var now = Date.now();
    var dt = (now - lastFrame) / 1000; // in seconds
    lastFrame = now;

    update(dt);
    renderer.render(stage);
}

function update(dt) {
    // assuming velocity is "units per second", move sprite based on time passed.
    mySprite.position.x += mySprite.velocity.x * dt;
}

lastFrame = Date.now();
animate();
```

**Comment by ivanpopelyshev** [comment]
@englercj that's not deterministic :(

**Comment by Arnold1** [comment]
@ivanpopelyshev how you show a snippet which makes it deterministic?

**Comment by englercj** [comment]
> @englercj that's not deterministic, by the way

In what way? At any given time index you will always be at the same location. It isn't synchronous, but it is deterministic.

**Comment by ivanpopelyshev** [comment]
@englercj We are using floating point numbers. They are determenistic only if the sequence of operations is the same. +0.1+0.2 !== +0.3

**Comment by Arnold1** [comment]
@ivanpopelyshev can you give me some feedback to the following snippet? https://jsfiddle.net/j8njn2x4/23/

**Comment by englercj** [comment]
> @englercj We are using floating point numbers. They are determenistic only if the sequence of operations is the same. +0.1+0.2 !== +0.3

With a fixed step the operational order is exactly the same, with a dynamic step the rounding errors are negligible for the applications we are talking about.

**Comment by Arnold1** [comment]
@englercj @ivanpopelyshev could you give some feedback on my current version? https://jsfiddle.net/j8njn2x4/23/

**Comment by englercj** [comment]
@Arnold1 What feedback are you looking for?

**Comment by Arnold1** [comment]
@englercj i removed the timer and added a counter which will trigger the parameter change. is it now deterministic?

**Comment by englercj** [comment]
Maybe? The trick isn't removing timers, it is ensuring that on any given frame you will have the same values across multiple runs of the same simulation. Usually you do that by using the frame number or delta time to do updates.

Have you tried your simulation? If you find it deterministic, move on. If you find it not, feel free to post again with the specific issue you are having.

**Comment by Arnold1** [comment]
@englercj i do not understand how to use dt in changeSimParameter: function(dt). changeSimParameter changes the speed or the direction.
could you explain with reference to my current version? https://jsfiddle.net/j8njn2x4/24/

**Comment by englercj** [comment]
Time elapsed between frames means that 1 second into your simulation, all things will have been updated by 1000ms, guaranteed. Though the number of frames it takes for that to happen may be different.

Using a constant step means that X frames into your simulation, all things will have been updates the same X times, guaranteed. Though the amount of time it takes for that to happen may be different.

Just depends on what works best for you simulation. Using delta time, and starting with the same seed will have the same outcome at 1000ms, everytime. Same with constant step, but with frames.

**Comment by Arnold1** [comment]
@englercj Using a constant step means that X frames into your simulation, all things will have been updates the same X times, guaranteed. "Though the amount of time it takes for that to happen may be different each run." why use most games the first approach?

i have logged my simulation parameter changes (without update log): http://ideone.com/23kUJB
one way of checking if it's the same is running it and checking whether or not the state is within some epsilon of another run of the simulation at a particular iteration. the state would be everything which the system is defined, probably x,y,vx,vy,... for every object.

this is the version i used: https://jsfiddle.net/j8njn2x4/29/

**Comment by englercj** [comment]
> why use most games the first approach?

I never said that. I said many real-time games do. Most synchronous games need to be frame-lock deterministic, and so they use the second one. The first one means that on slower machines with less FPS a user can "catch up" to other clients without having to somehow run more frames.

**Comment by Arnold1** [comment]
does my example already implement a Time-based Animation like here? https://www.viget.com/articles/time-based-animation
I mean the simulation be independent on the frame rate?

**Comment by englercj** [comment]
@Arnold1 Just skimming this article it seems like that was what I was talking about. Animating based on time index, not on frame count.

**Comment by Arnold1** [comment]
@englercj or this article is also good http://blog.sklambert.com/using-time-based-animation-implement/
