### ISSUE TITLE
A child Text fattens and fattens - V4

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2671]
![text-issue](https://cloud.githubusercontent.com/assets/170243/16358820/ce1a8596-3b28-11e6-9905-2e42d8085fe2.png)

This Text is a child of the character, they both have anchor.set(0.5,1)'s - the Text has .y=-30

When you play around a bit, the text gets bolder, I'm not sure what's causing it, I checked whether it somehow gets re-added, yet that's not the case, as the console.log is only hit once

I also have no plugins on top of PIXI when this happens

Any ideas for the cause?

**Comment by ivanpopelyshev** [comment]
Yep, thats a bug, can you please try new version?

**Comment by ivanpopelyshev** [comment]
By the way, where did you get the sprites?

**Comment by kaansoral** [comment]
Thanks for the info

I seem to be using the latest one from the bin tho, does the bin's auto-update? last update is 11 days ago

( the sprites are time fantasy sprites : )

**Comment by ivanpopelyshev** [comment]
I updated it 18 minutes ago but i did not push into gh-pages yet

**Comment by kaansoral** [comment]
This is where I get my V4 from: https://github.com/pixijs/pixi.js/tree/dev/bin - Should I check another place?

By the way, I have another very weird bug, wondering whether these 2 issues are related and whether the updated V4 is going to fix it, the main character somehow gets linked to the monsters on the map, each click to the main character goes to random monsters, the main character plays their animations, very bizarre stuff - in it's most basic explanation, the issue causes clicks to one sprite to be diverted to other sprites etc.

Don't know why but today is my pixi bugs day, before today everything was like clockwork :)

**Comment by ivanpopelyshev** [comment]
I thought you are talking about "bin" which contains my plugins. Its there: https://github.com/gameofbombs/pixi-bin/tree/master/bin

Just dont take pixi.js from there, its experimental :)

I have built V4 for you: https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js . Official build will happen next week.

**Comment by kaansoral** [comment]
Thank you so much <3

It turns out the fattened font in my case is the side-effect of the glitch I mentioned above, at one point, something flips off in the game, it's like everything is linked to each other, the main character shakes when it absorbs animations meant for other entities, the Text fattens with this shaking

Investigating at this point, I hope it's an easily solveable innocent bug from my side

**Comment by kaansoral** [comment]
Well apologies

Turns out it was a bug from my side, a bug + bad variable naming

I had a new routine that I use for adopting properties into a sprite from an object, while copy pasting I didn't rename the arguments, it ended up overriding all monster sprite properties with the properties of the main character sprite, causing the headache inducing issue I described
