### ISSUE TITLE
strategy for touch drawing

### ISSUE THREAD

**Issue by PierBover** [pixijs/pixi.js#2674]
I'm trying to pick a library for a project.

AFAIK Pixi doesn't have an API for drawing. When I say drawing, I don't mean the graphics API, I mean being able to draw on the screen with a cursor or touch events.

Is there any example or demo that does that with Pixi?

What would be a proper strategy to do such functionality with Pixi? I'm thinking that an invisible vector bezier curve with smoothing would be needed instead of painting a bunch of pixels on ever frame in case there were frame drops.

Are there plans to implement this in v4?

**Comment by ivanpopelyshev** [comment]
Graphics is emulating canvas2d, but its vector storage - it remembers all operations. You can easily make a container that draws something on RenderTexture, or just wrap canvas2d into new BaseTexture(canvas) and then update it.

Do you have any references on that kind of APIs in other HTML5 rendering engines?

**Comment by PierBover** [comment]
It's not an API per se, but here is an example of how Paper.js does it.

http://paperjs.org/examples/path-simplification/

**Comment by PierBover** [comment]
> Graphics is emulating canvas2d, but its vector storage - it remembers all operations.

How can I access the operations?

I've looked into [the docs](https://pixijs.github.io/docs/PIXI.Graphics.html) and I don't see how I can for example access the nodes of a line I have created with `lineTo()`.

**Comment by ivanpopelyshev** [comment]
Down the rabbit hole. https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/Graphics.js#L253

**Comment by scottmcdonnell** [comment]
@PierBover we used paperjs to draw paths and pixi.js then to animate and display textures captured. 

We just used 2 canvases one for paper and one for pixi and then snapshot the paper canvas as a new texture when you are finished drawing. 
Pixi graphics is convenient for vectors but not smooth enough for the look we were going for.

**Comment by PierBover** [comment]
Hey @scottmcdonnell that sounds very interesting.

Is a demo available?

**Comment by scottmcdonnell** [comment]
@pierbover no demo I'm afraid but just give it a go paperjs for drawing then pixijs for display. The bridge is PIXI.Texture.fromCanvas()

**Comment by PierBover** [comment]
> PIXI.Texture.fromCanvas()

Awesome, thanks for the tip.

I guess I'll be closing this then.

**Comment by ivanpopelyshev** [comment]
@PierBover it will be slow on mobiles, but if you use paper only for a part of scene (not that big area) then it will be ok. Think of it as a video streaming, the same performance.

**Comment by PierBover** [comment]
Yeah... I just tried the paper.js drawing demo on a galaxy tab 4 and it runs like crap. If I also add the bitmap conversion overhead it will be completely useless.

Sadly I need to support those devices, so I will need another idea.

**Comment by ivanpopelyshev** [comment]
That's what I'm talking about . We need high-quality shaders! I'm working on that by the way, but slowly

**Comment by PierBover** [comment]
Excuse my ignorance... but how would a shader help?

**Comment by ivanpopelyshev** [comment]
Move it completely on GPU :)

**Comment by ivanpopelyshev** [comment]
We can actually implement gpu drawer right now , just use RenderTexture and add some graphics elements for it, flip-flop two framebuffers to store it .

**Comment by PierBover** [comment]
I'm not following you... you mean for using with the paper.js method?

**Comment by ivanpopelyshev** [comment]
No, I mean to change two renderTexture-s and render from one to the other, like doublebuffer.

**Comment by scottmcdonnell** [comment]
Sorry to butt in but I would have to disagree with paperjs performance on mobile, drawing works great for us on phone and tablet. 
The demo is not optimised and draws fullscreen (with pixel-ratio=2 its unnecessarily big). 
Try a fixed sized canvas for your performance test. For better performance mousemove event or adding points can be throttled with `requestAnimationFrame` and turn off the handles that are for demo purposes only.

It all depends on the style of your app. paperjs is great if your want/need smoothing methods or editing your paths after drawing. If you don't need this you can also try [native canvas drawing](https://jsfiddle.net/ArtBIT/kneDX/) for additive drawing. 

Would a renderTexture provide a performance boost over native canvas? I thought renderTextures use a HTML Canvas element as a buffer anyway.

**Comment by PierBover** [comment]
The paperjs drawing demo works great on premium and/or modern devices.

I've record [this video](https://www.youtube.com/watch?v=-98A0XJ0kxI) with my testing devices. The one on the left is the [2014 Galaxy Tab 4](https://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_4_8.0) and as you can see on semi complicated paths it takes up to a second to simplify it. Also, it's hard to see in the video, but it's much less responsive than the other devices once the vector shape starts to get more nodes.

Even the performance on the white iPad 3, a 2012 premium device, isn't that good IMO.

Of course, on the other 2 devices it runs great, but those are top devices. An iPad Air 1, and an Nvidia Shield K1.

The problem with the native canvas drawing you posted is that once you draw a bit fast, or the FPS drop, you don't get a line but a series of dots. This can be solved by using a vector shape with path interpolation (like the paper.js demo) and paint the pixels from that, but for old devices a more sophisticated approach is needed. For example by preventing a very long vector build up by splitting it every second or so.

I will try your performance suggestions once I have a bit of time. Maybe that will be good enough.

Could you record a video of how your system performs on an old or low end device?

**Comment by ivanpopelyshev** [comment]
renderTexture will provide a boost, you just have to move the curves to GPU side. Upload vertex buffer with parameters (t=0.0, t=0.1, t=0.2)..., add uniforms with bezier points (4 points for it), and compute the curve inside vertex shader , based on attribute T (curve param) and uniform bezier points.

**Comment by PierBover** [comment]
Thanks @ivanpopelyshev I will try to figure out how to do that.

**Comment by scottmcdonnell** [comment]
drawing a big path with loads of points like you have and then running smooth() is going to to take processing time alright. You could optimise by splitting the path and smoothing every X amount of points. 

Another optimisation is to capture all points on mousemove into an array and then render them only on requestanimationframe().

Just like paperjs - in native canvas and pixi you either draw straight lines between all points and hope they are close enough to not look jagged or you calculate suitable curves between the points using some sort of smoothing algorithm or catmull-rom... and incur processing time. 

The shader approach for rendering curves sounds great, would be a big performance boost. I'm not sure if smoothing algorithm could be done on the GPU to give you the curves?

**Comment by ivanpopelyshev** [comment]
@scottmcdonnell It can be, we just have to quantify it somehow. I dont want to think on that right now, I already have like 10 serious tasks :)
