### ISSUE TITLE
Plane and Texture.fromFrame not working ?

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#2677]
Was trying to make a 9slice scaling example and found out Plane and Texture arent working together nicely.

When I create a Plane directly with a Texture, it doesn't work.

When I use a RenderTexture, it does work..

example:
using latest PIXI dev (4.x)
using @ivanpopelyshev 's version

https://jsfiddle.net/whizzkid74/8p2s3jz8/8/

**Comment by GoodBoyDigital** [comment]
we have a nine slice :D
