### ISSUE TITLE
Amount values for ColorMatrixFilter are not documented

### ISSUE THREAD

**Issue by mheppner** [pixijs/pixi.js#2682]
I apologize if this is obvious to others, but I can't figure out what values to give some of the functions on [ColorMatrixFilter](https://pixijs.github.io/docs/PIXI.filters.ColorMatrixFilter.html). Most functions that take a value just have a generic description. It would be more helpful, for example, if `brightness()` have a description for the `b` parameter to say, "value of the brightness (0-200, where 0 is black, 100 is normal)."

More specifically, I cannot get `contrast()` to work. I tried giving decimal values from -1 to 1, as well as percents from -100 to 100. A decimal of 0.01 results in complete black and -0.01 results in complete white. I'm not sure if this is actually a bug or a user error.

**Comment by englercj** [comment]
The values are almost all "normalized", meaning between 0 and 1. I'll try to get some extra docs in there.
