### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by PierBover** [pixijs/pixi.js#2684]
So I cloned the repo, installed dependencies with `npm install`, and built with gulp.

> Error: Cannot find module 'jshint/src/cli'

I solved it with:

> npm install --save-dev jshint gulp-jshint

I thought I should be opening an issue nevertheless.

**Comment by englercj** [comment]
Looks like we are missing a `jshint` dep. but gulp-jshint is there. Feel free to put in a PR.

**Comment by PierBover** [comment]
Well, instead of building from `master` I built from `dev` and it worked. No need for a PR, it will get fixed on the next merge.

**Comment by englercj** [comment]
Ha, OK :)

**Comment by denour** [comment]
still not fixed?
