### ISSUE TITLE
Sprite's overflow outside their boundaries if coordinates are non-int [V4]

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2685]
So I'm using basic image sprites for walking animations, poses are laid out on a grid, where one pose starts the other ends

One problem I had from the beginning is sprite's overflowing 1px to the neighbouring sprites (not always, but like 1% of the time, so like every 3-4 seconds) (I use sprite's with scale 2, without resizing, so ideally they should be easy to draw)

I solved it by using PIXI.SCALE_MODES.NEAREST and only integer coordinates

However, using only integer coordinates results in shaky movements when map is moving and things on the map are moving

Using float coordinates solves this problem, everything is silky smooth, yet, the creeping sprite issue returns

So it's either (1) creeping sprites or (2) shaky movements, both are bad

Is this a bug, or is this just how it is?

**Comment by ivanpopelyshev** [comment]
1) Float coordinates 
2) scale your textures 2x times
3) LINEAR 
4) "antialias:true" in renderer parameters 
5) when sprite/map is resting, round their coordinates.

**Comment by kaansoral** [comment]
Here is no antialias, 2x scaled map, NEAREST, antialias: false, int
![goodish_pixi](https://cloud.githubusercontent.com/assets/170243/16464117/5a16631a-3e41-11e6-8177-96d3cb4ae23c.png)

Here is antialias, 2x scaled map, LINEAR, antialias: true, float
![bad_pixi](https://cloud.githubusercontent.com/assets/170243/16464128/658518d6-3e41-11e6-8120-d2e4f263dc94.png)

My experience, antialias: true/false makes no visible or observable difference, I even suspect it's always on, I check the drawn stuff with a loupe and can't detect any change

LINEAR/NEAREST - There's something definitely wrong if I use LINEAR, the problem I described tenfolds

int/float: using float triggers the issue from frame to frame even with NEAREST

---

Dirty solution: Use float + manually shrink sprites by 1px, so if sprites overflow by 1px, they render what they should have rendered in the first place

Obviously this is not applicable for the map, the map itself needs to have integer coordinates, as tiles need to be exact, however, the monsters on the map can have float coordinates if I shrink them by 1px from the edges

**Comment by ivanpopelyshev** [comment]
Float coordinates only for characters, map must be rounded. roundPixels=true works only for canvas renderer, so its up to you to code something that will round webgl map correctly.

Add padding between frames on your spritesheet. Its best if you'll have atlases made with shoebox/texturepacker/spritesheet.js . That will take care of border glitches. Like you said about 1px

That all works just fine on gameofbombs.com :)

**Comment by kaansoral** [comment]
Thanks for the info

Up to this point, I didn't really think about WebGL/Canvas, PIXI was an isolating layer as it was supposed to be (and it is : ), now I implemented a routine to see what I was using, it was WebGL, tried Canvas too roughly, luckily my manually patched dynamics works the same on Canvas too - so switching to Canvas didn't change things as I was afraid they might

(Although I check the type/CONST and verify the WebGL/Canvas usage, it's almost unbelievable how the two pictures are exactly the same is in both Renderers, it's admirable how consistent PIXI is)

I think I might implement a pre-deployment routine at one point, that will turn the map into one image, that would solve the problem once and for all - and maybe a similar routine that will space out sprites manually too

But at the time, during development, I guess patching and deferring the issue is the way to go

I really like gameofbombs, just played again :), I checked it first after seeing how horrible font rendering was in my game, yet in game of bombs the text usage seemed very polished, I guess the background really helps

Anyway, do you think these issues could ever be solved from the PIXI side?

**Comment by ivanpopelyshev** [comment]
You can use pixi-tilemap to make your mapof, no need of storing all that in memory. Just make sure all elements is in one atlas.

Text rendering is polished because what i really do is rounding text when character stays in place and there's no movement of camera.

I have special renderer for spritesheets - pixi-picture. However its not optimized at all, I use it only for big pictures like 256x256 or 512x512.

**Comment by ivanpopelyshev** [comment]
I also recommend to use pixi-display, it will help you with character sorting

**Comment by kaansoral** [comment]
All extremely awesome suggestions

I'm already using pixi-display, a game changer

However, pixi-tilemap didn't apply to my usecase as I'm primitive in terms of sprites, using .png's manually. I just tried extending the map to 4Kx4K, ended up placing 60K 16x16 tiles, at that time I dipped into 20fps's for the first time, so I definitely need a tiling solution now :)

I was thinking either manually updating things every 100px, or using a range tree to do the same more effectively, I should check rpgmaker's solution as you suggested, it's quite the challenge

One other problem with adjacent/manually-cut tiles is | | | | -like tearing, while moving, 200px is shaded one color in width, another 200px is shaded a paler color, then another 200px is darker - don't know why it happens, but it happens consistently, both on canvas and webgl - but I guess it's a challenge for another day

**Comment by GoodBoyDigital** [comment]
looks resolved 👍
