### ISSUE TITLE
Strange things with TilingSprite

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#2690]
The description is in this forum thread:

http://www.html5gamedevs.com/topic/23263-strange-things-with-tilingsprite/

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/issues/2660 

Is your bug different? If not, please use search or at least look at the top next time.

**Comment by trsh** [comment]
Yes, my report describes additional issues:

1) Blurriness (or some kind of weird opacity) of tiles taken from generate texture.
2) Problem is present in both v3 and 4 and on scale also greater than 0.5 (also with 1 - default).

You can check the code.

**Comment by trsh** [comment]
I also see this warning in v4: "Deprecation Warning: graphics generate texture has moved to the renderer. Or to render a graphics to a texture using canvas please use generateCanvasTexture", but can't find any related docs.

**Comment by ivanpopelyshev** [comment]
Are using generateTexture somewhere?

**Comment by trsh** [comment]
Yes?!

http://www.html5gamedevs.com/topic/23263-strange-things-with-tilingsprite/

Look at the code, again.

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by trsh** [comment]
Sure, I will prepare tomorrow.

**Comment by trsh** [comment]
https://jsfiddle.net/zLvbwer3/

Here we go!

**Comment by ivanpopelyshev** [comment]
I know what's wrong with it, look at #2660. Turn mipmapping off and it will work just fine.

**Comment by ivanpopelyshev** [comment]
Also, you kinda have half-pixels on the edges, and generateTexture() leaves them at the edge. Make line width 2 or your coords 0.5 where it matters.

**Comment by trsh** [comment]
@ivanpopelyshev can you update fiddle for me? I did not succeed to implement your ideas.

https://jsfiddle.net/zLvbwer3/2/

**Comment by ivanpopelyshev** [comment]
OK. first step is to either set lineWidth to 2 either make your line half-pixel coordinate:

```js
  grid.moveTo(0,9.5);
  grid.lineTo(20,9.5);

  grid.moveTo(9.5,0);
  grid.lineTo(9.5,20);
```
  
Now its less blurry (at least first line), its awesome. Lets do the next step, look at its local bounds

```js
console.log(grid.getLocalBounds())
```

They are x1=-1, x2=-1, w=22, h=22 which is totally that's why we have those extra pixels nearby, it certainly cant be used for repeated texture.

@GoodBoyDigital what to do with that? Override getLocalBounds somehow? Add rectangle as a parameter for generateTexture() ?

**Comment by trsh** [comment]
@GoodBoyDigital , @ivanpopelyshev  any fresh ideas on this? :/

**Comment by GoodBoyDigital** [comment]
Its on our list for v4.1 :)

**Comment by trsh** [comment]
@GoodBoyDigital temporal workarounds? :)) Im in a deadline

**Comment by GoodBoyDigital** [comment]
haha! Arn't we all!
My best suggestion would be to use a po2 texture not from a sprite sheet for now

**Comment by trsh** [comment]
@GoodBoyDigital actually I solved it (https://jsfiddle.net/zLvbwer3/3/) with boundsPadding=1. Now have just to calculate right ;)

**Comment by GoodBoyDigital** [comment]
nice :D

**Comment by trsh** [comment]
Fixed or what? Why closed?

**Comment by englercj** [comment]
Not sure, @ivanpopelyshev can you comment why this was closed? There is no resolution label or comment so I'm not sure what happened here.

**Comment by ivanpopelyshev** [comment]
Test it please.
