### ISSUE TITLE
PIXI v4.0 (current latest dev) PIXI.extras.BitmapText vanished

### ISSUE THREAD

**Issue by joeredfearn** [pixijs/pixi.js#2692]
I just downloaded the latest version of the **dev** branch of pixi 4.0 which fixed an issue i was having with filters completely overriding the children below them.

This issue was fixed but now all the **BitmapText** I have in my prototype has vanished.

Just a heads up!

Thanks for all the hard work :+1:

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by GoodBoyDigital** [comment]
Should be all good now!
