### ISSUE TITLE
PIXI v4.0 (current latest dev) PIXI.extras.BitmapText vanished

### ISSUE THREAD

**Issue by joeredfearn** [pixijs/pixi.js#2693]
I just downloaded the latest version of the **dev** branch of pixi 4.0 which fixed an issue i was having with filters completely overriding the children below them.

But now all the **BitmapText** I have in my prototype has vanished.

Just a heads up!

Thanks for all the hard work :+1:

**Comment by ivanpopelyshev** [comment]
did you assign something like this?

```js
p1 = new Point(10,10);
bitmapText.position = p1;
```

We have gfixed this new glitch, so please build it from sources or use https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js

For future versions of pixi, all assignments to position, scale and pivot are assignments by value, and thing like this wont work anymore in any case: 

```js
obj1.position=p1;
p1.x=10;
```

**Comment by joeredfearn** [comment]
Here is an example of what im doing.

```
this._titleText     = new PIXI.extras.BitmapText("HELP", {font: "60px Great Escape", align: "center"});
this._titleText.y   = 120.0;
this.addChild(this._titleText);
```

**Comment by ivanpopelyshev** [comment]
Ok, now i see that http://pixijs.github.io/examples/index.html?s=demos&f=text-demo.js&title=Text&v=dev does not have bitmap text it had before. We have a bug!

**Comment by adireddy** [comment]
@ivanpopelyshev Missing `/` in the url is the issue. I raised a PR but just closed it https://github.com/pixijs/pixi.js/pull/2681

**Comment by joeredfearn** [comment]
awesome news, how can i get access to this amended version?

thanks

**Comment by ivanpopelyshev** [comment]
@joeandaverde cant you just apply changes from that PR to pixi and build it?

**Comment by GoodBoyDigital** [comment]
fixed in current branch I believe 👍
