### ISSUE TITLE
getCanvas() on a RenderTexture handles alpha incorrectly.

### ISSUE THREAD

**Issue by jackie-t** [pixijs/pixi.js#2695]
Similar to https://github.com/pixijs/pixi.js/issues/2302, the getCanvas on a RenderTexture does not appear to handle the alpha calculations correctly.

Step 1: Load an image that relies on an alpha channel. 
Step 2: Call hue(1) on the ColorMatrixFilter and apply that ColorMatrixFilter.
Step 3: Render the texture, using generateTexture.
Step 4: Call getCanvas() on the generated texture.

This should result in a slight change to the hue, barely noticable.
Instead, the color is heavily distorted.

http://codepen.io/bringerofbabies/pen/yJbGdY

(this uses the newest PixiJS as of today)

**Comment by andrewstart** [comment]
This seems to actually be a problem with getCanvas() on a RenderTexture: http://codepen.io/bringerofbabies/pen/yJbGdY
I would guess due to some sort of premultiplied alpha/non-premultiplied alpha mismatch.

**Comment by jackie-t** [comment]
Alright - nice catch. I'll adjust the title, so it's more easy to find.

**Comment by bastienatome** [comment]
I've got a similar problem with the get canvas on a sprite with a custom texture. It seems that came from the getCanvas of the RenderTexture.
http://codepen.io/anon/pen/xEkWRK

**Comment by mnori** [comment]
Here's a pen I did to replicate this problem, using Graphics instead of Sprite

https://codepen.io/wildtype/pen/NjeRMN

**Comment by setpixel** [comment]
+1

**Comment by ivanpopelyshev** [comment]
Oh, that old thing. Thanks to @setpixel we have an answer:

Everything that is rendered in pixi has premultiplied alpha. There's no way to get non-premultiplied info, unless you patch all the object renderers.

To compare the effort, look at #4033, the PR that introduced non-premultiplied alpha in source textures. For NPM targets you'll need even more code.

**Comment by ivanpopelyshev** [comment]
Thus, `canvas()` result is correct only if alpha=1 everywhere. Otherwise, you have to take pixels() and divide result by alpha. Should we add special flag in `canvas()` that allows to do it automatically?

**Comment by mnori** [comment]
Nice, I applied #4632 and passed the premultiply param as true to solve my old codepen.

```
var canvas = renderer.extract.canvas(stagingContainer, null, true);
```

Proof that it works:
https://codepen.io/anon/pen/GQWYZK

Can resurrect my old project now :D
