### ISSUE TITLE
CanvasSpriteRenderer is exported as CanvasSpriteRender

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi.js#2697]
Please See this issue by @webbiesdk where it is explained fully. 

https://github.com/pixijs/pixi-typescript/issues/64

I have no trouble adjusting the definitions, but I do agree it is a JS fix so will take the opportunity to get some feedback here. 

This is fine:

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/canvas/CanvasSpriteRenderer.js#L27

The offending line `CanvasSpriteRender`:

https://github.com/pixijs/pixi.js/blob/dev/src/core/index.js#L26

Thanks!

**Comment by GoodBoyDigital** [comment]
nice catch! 👍
