### ISSUE TITLE
[3.0.11] TilingSprite issue on Galaxy Tab 3 and some other devices (WebGL only)

### ISSUE THREAD

**Issue by adireddy** [pixijs/pixi.js#2699]
TilingSprite is not being rendered correctly on Galaxy Tab 3 and some other devices when using WebGL.

I managed to fix the issue by changing the shader precision value to `mediump`.
https://github.com/pixijs/pixi.js/blob/master/src/extras/TilingSprite.js#L67

I have done some reading and people are suggesting to use `mediump` precision instead of `lowp` or `highp` and want to check with you guys first before raising PR.

Also haven't noticed any performance drop with `mediump`.

**Comment by JiDW** [comment]
This is a duplicate. It has been fixed in v4 by letting the user change the default precision of the shaders.

**Comment by adireddy** [comment]
Good to have it fixed in v3 as well if possible for existing projects either by changing default precision to `mediump` or with an optional `precision` parameter.

**Comment by GoodBoyDigital** [comment]
seems fixed 👍
