### ISSUE TITLE
"Sprite" uses the same cache variable for local and world bounds 

### ISSUE THREAD

**Issue by sergebat** [pixijs/pixi.js#2700]
The following sequence make vector "p" invalid, as "getBounds()" calculation overwrites the same cache variable with global bounds:
```
var p = this.getLocalBounds();
this.getBounds()
```

Also, calls to getLocalBounds after getBounds will probably screw up subsequent calls to getBounds().

I think it is good idea to keep local and global boundaries in separate variables.

Edit: Might be related to https://github.com/pixijs/pixi.js/issues/2599 (but I think the other issue only speak of the same issue for the Container object). 

Code that creates issue:
```
        var bounds = this._bounds;

        bounds.x = minX;
        bounds.width = maxX - minX;

        bounds.y = minY;
        bounds.height = maxY - minY;

        // store a reference so that if this function gets called again in the render cycle we do not have to recalculate
        this._currentBounds = bounds;
```

**Comment by ivanpopelyshev** [comment]
Fixed in #2654 . That is big change, I'm making tests for it.

**Comment by GoodBoyDigital** [comment]
PR incoming!

**Comment by GoodBoyDigital** [comment]
Fixed 👍
