### ISSUE TITLE
toLocal does not account for parent transformations before updateTransform/render is called

### ISSUE THREAD

**Issue by sergebat** [pixijs/pixi.js#2701]
toLocal (and probably toGlobal) does not take account parent position/scale/etc modifications, until updateTransform/render is called. 

I don't think this is documented anywhere, and it is not particularly consistent behavior (given that it at least properly recomputes transformation matrix on the object itself). 

https://jsfiddle.net/tunkkcj4/

```
var r = PIXI.autoDetectRenderer(200, 200);
var c1 = new PIXI.Container();
c1.x = 20;
c1.y = 0;

var c2 = new PIXI.Container();
c2.x = 0;
c2.y = 0;


c1.addChild(c2);
var p = c2.toLocal(new PIXI.Point(20, 20));
console.log(p); // --> wrong

r.render(c1);
var p = c2.toLocal(new PIXI.Point(20, 20));
console.log(p); // --> right
```

**Comment by ivanpopelyshev** [comment]
Do you have a suggestion on how to handle that? Somehow call updateTransform() lazily?

**Comment by sergebat** [comment]
One option is to just always do updateTransform for all parents recursively/iteratively. Just like you do for "this" object.

Right now PIXI itself is not using these functions, it seems. So existing functionality should not regress/slow down. 

Lazy updateTransform is probably the best option. But it looks like a bit of a challenge, as right now PIXI does not mark dirty/fresh status of transformation matrixes.

**Comment by sergebat** [comment]
Do you see any problems with just iteratively calling obj.displayUpdateTransform() for all parents in toLocal and toGlobal? 

After all, sub-optimal is better than broken (and right now PIXI itself is not using it, as far as search shows)? :) 

If in principle @englercj and others don't see the issue with the approach, I can probably create a pull request.

**Comment by ivanpopelyshev** [comment]
@sergebat go for it, I'm sure that it wont be that bad, at least because we already have lazy calculation on localTransform, half job is done :)

**Comment by ivanpopelyshev** [comment]
Try again with that dropbox pixi:

https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js

no updateTransform() required.

**Comment by englercj** [comment]
> I'm having problems merging even easiest things there - @englercj keeps finding even smallest mistakes in my architecture

Sounds like I'm doing a good job then :)

**Comment by ivanpopelyshev** [comment]
@englercj can you at least examine that getBounds() PR even without tests? ill add some tests tomorrow.

**Comment by englercj** [comment]
I examine all PRs as I find the time.

**Comment by ivanpopelyshev** [comment]
@englercj Its a priority, we really cannot push pixi-v4 without it.

**Comment by sergebat** [comment]
Quick test shows that the same fiddle works ok with dropbox version, same coordinates in both logs!
https://jsfiddle.net/tunkkcj4/
(not publishing as a separate fiddle to avoid overloading your dropbox link, which is not a cdn)

**Comment by staff0rd** [comment]
@ivanpopelyshev which branch on your repo is the lazy updateTransform?

**Comment by staff0rd** [comment]
I think i'm getting this bug - basically I'm making calls to `toLocal(point)` which works for a while but after a while it starts returning different values, even when the same `point` is supplied.

I tried your build @ivanpopelyshev, however it fails on a call in `generateCanvasTexture` to `this.getLegacyLocalBounds`.

**Comment by ivanpopelyshev** [comment]
Try that one: https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds3/pixi.js

**Comment by staff0rd** [comment]
Nah, same problem - nevermind, turns out this bug was not the issue I ran into anyhow.

**Comment by ivanpopelyshev** [comment]
Ah, thank you, found the place. I forgot to change it, gonna fix my build...

**Comment by ivanpopelyshev** [comment]
Can you try that again please? Same location.

**Comment by staff0rd** [comment]
Yeah that fixes the `getLegacyLocalBounds()`, but it spams a deprecation warning so hard to the console that it nearly crashes the window ;)

> TransformManual has been renamed to TransformBase, please update your pixi-spine

**Comment by ivanpopelyshev** [comment]
Nice, I'll make new spine version for that

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
