### ISSUE TITLE
toLocal and toGlobal in V4

### ISSUE THREAD

**Issue by Hachitus** [pixijs/pixi.js#2702]
Did you already know that dev branch calculates toLocal and toGlobal differently than in V3 or v4-RC2?

https://plnkr.co/edit/R9M6E1x67WCQ7cjmlvZF?p=preview (you can comment and activate the different pixi versions in the index.html)

**Comment by ivanpopelyshev** [comment]
Please do not use v4-rc2, try the latest from "dev" branch. All transforms were reworked in v4, thus toLocal and toGlobal are affected too.

Somehow, these demos show me only black screen.

**Comment by Hachitus** [comment]
@ivanpopelyshev Ok. So you probably saw the issue? Basically it isn't supposed to show anything, just console.log the toLocal and toGlobal values. And changing the loaded script in index.html will show you what the different versions print.

**Comment by ivanpopelyshev** [comment]
Oh, there's the other bug, I dont think dev/bin/pixi.js was updated after #2669 was merged. This one works:

```js
PIXI.TRANSFORM_MODE.DEFAULT = PIXI.TRANSFORM_MODE.DYNAMIC;
const sprite1 = new PIXI.Sprite(PIXI.Texture.EMPTY);
sprite1.position = new PIXI.Point(10,10);
const grandParentContainer = new PIXI.Container();
const parentContainer = new PIXI.Container();
parentContainer.x = -50;

grandParentContainer.addChild(parentContainer);
parentContainer.addChild(sprite1);

parentContainer.updateTransform();
```

before that fix, PIXI.TRANSFORM_MODE.STATIC was conflicting with stuff like this:

```js
sprite1.position = new PIXI.Point(10,10);
```

**Comment by ivanpopelyshev** [comment]
OK! try again your stuff with that dropbox pixi: 

https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js

**Comment by Hachitus** [comment]
Yeah, it works with that like a charm! Though you wouldn't have needed to go all that trouble just for this, but thank you! :).

**Comment by ivanpopelyshev** [comment]
I will close like 10 issues with this patch, you are not the only one with the problem.
