### ISSUE TITLE
PIXI.mesh.Plane getLocalBounds() wrong values

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#2703]
Hi!

Sorry, it's me again... 

```
var renderer = new PIXI.WebGLRenderer(800, 600);

document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

PIXI.loader.add("test", "bunny.png").load(function() {

    var texture = PIXI.Texture.fromImage("bunny.png");
	console.log("texture w/h", texture.width, texture.height);
	
	var plane = new PIXI.mesh.Plane(texture);
	stage.addChild(plane);
	
	var sprite = new PIXI.Sprite(texture);
	sprite.y = 200;
	stage.addChild(sprite);

    setInterval(function() {
        plane.x = (Math.random() * 100) >> 0;
        sprite.x = plane.x;
        console.log("plane.x, localBounds.x", plane.x, plane.getLocalBounds().x);
        console.log("sprite.x, localBounds.x", sprite.x, sprite.getLocalBounds().x);
    }, 500);

    animate();
});

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

The plane returns wrong localBounds values.

**Comment by ivanpopelyshev** [comment]
Can you try it with https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js please?

**Comment by rkrasky** [comment]
Great! Works like a charm! Your PR should be definately merged!

**Comment by rkrasky** [comment]
But your version has problems with width and height... 

```
var renderer = new PIXI.WebGLRenderer(800, 600);

document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

PIXI.loader.add("test", "bunny.png").load(function() {

    var texture = PIXI.Texture.fromImage("bunny.png");
	
	var c = new PIXI.Container();
	stage.addChild(c);
	
	console.log("0" + c.width); // returns 0 - correct
	
	var sprite1 = new PIXI.Sprite(texture);
	sprite1.x = c.width;
	c.addChild(sprite1);
	
	console.log("1 " + c.width); // returns 200 - correct
	
	var sprite2 = new PIXI.Sprite(texture);
	sprite2.x = c.width;
	c.addChild(sprite2);
	
	console.log("2 " + c.width); // returns 200 - wrong, should be 400
	
	var sprite3 = new PIXI.Sprite(texture);
	sprite3.x = c.width;
	c.addChild(sprite3);
	
	console.log("3 " + c.width); // returns 200 - wrong, should be 600


    animate();
});

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

**Comment by ivanpopelyshev** [comment]
@rkrasky coordinates (position, scale, pivot) are not applied automatically. They are applied in container.updateTransform() or container.displayObjectUpdateTransform() which is either called manually, either is called from "renderer.render". if you add "sprite2.displayObjectUpdateTransform()" there it will work like intended. 

However, I think I can hack my PR that way it will work just fine :) But only for "getLocalBounds()", "width" and "height", not "getBounds()".

**Comment by rkrasky** [comment]
@ivanpopelyshev that would be perfectly fine!

**Comment by ivanpopelyshev** [comment]
OK, try again with that dropbox pixi:

https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js

No updateTransform() required

**Comment by rkrasky** [comment]
Bounds working! Thanks a lot. Your version seems to have problems with interactivity...

**Comment by ivanpopelyshev** [comment]
@rkrasky tell me more please!

**Comment by rkrasky** [comment]
Sorry, it wasn't a problem with interactivity. For my buttons I used getLocalBounds() for the hitArea. In the current dev version this was ok, in yours, it was broken. But this was because of the wrong/late calculation of the bounds in the dev version. So everything is totally fine!
