### ISSUE TITLE
Chroma key fragment shader black rectangle

### ISSUE THREAD

**Issue by baslentfert** [pixijs/pixi.js#2704]
hi I ported a chromakey fragment shader to pixi based on iq's work on shadertoy.com.
bu i get some strange behavior.
maybe someone could peek at it in a spare moment and tell me how to get rid of the black rect?

here is the link with small demo and source:
http://www.lentfert.net/chromakey3/

thanx in advance

**Comment by englercj** [comment]
Closing this as there is a colorReplace filter in https://github.com/pixijs/pixi-extra-filters/
