### ISSUE TITLE
V4 Filter issue (this time its Blur)

### ISSUE THREAD

**Issue by bQvle** [pixijs/pixi.js#2705]
Seems that most filters that comes in contact with the bottom- or right edge has issues in V4.

Check image, how blur stops before bottom and right edge
![image](https://cloud.githubusercontent.com/assets/12952595/16671190/6351caec-449e-11e6-86fe-4f81a1d6a6ac.png)

**Comment by ivanpopelyshev** [comment]
blur again. I will find old issue for displacementSprite and fix that the same way

**Comment by GoodBoyDigital** [comment]
hello! Just pushed a tweak that may fix this. Let me know! Cheers 👍

**Comment by bQvle** [comment]
sorry missed your message, I've opened a new issue, unfortunatly theres still problems. closing this one.
https://github.com/pixijs/pixi.js/issues/2816
