### ISSUE TITLE
[Dropbox-V4] Uncaught TypeError: Cannot read property 'updateLocalTransform' of undefined

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2706]
When I call .height on a PIXI.Container, I get this error on the latest build of V4 (I got it from Ivan's dropbox url)

Here is the trace:
Container.calcBounds	@	pixi.min.js:10130
DisplayObject.getLocalBounds	@	pixi.min.js:10627
get	@	pixi.min.js:9651
(anonymous function)	@	VM738:1

Feel free to close this issue fast if it's a repetition, as I see lots of .getLocalBounds related issues
(I've tested the same code with earlier versions, it works, the latest one doesn't)

**Comment by ivanpopelyshev** [comment]
fixed, try again

**Comment by ivanpopelyshev** [comment]
Try again please )

**Comment by kaansoral** [comment]
Works: https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js

Thanks :)
