### ISSUE TITLE
v4 masking with empty PIXI.Graphics

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#2707]
This throws an error: "Uncaught TypeError: Cannot read property 'shape' of undefined":

```
var stage = new PIXI.Container();
stage.interactive = true;
   
var g = new PIXI.Graphics();
stage.addChild(g);
	
var toMask = new PIXI.Graphics();
toMask.beginFill(0xff0000).drawRect(0, 0, 100, 100).endFill();
toMask.mask = g;
stage.addChild(toMask);
	
animate();

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

If you remove `toMask.mask = g` or draw something into the graphics mask (drawRect, circle...) it is working. In v3 this is working without drawing...

**Comment by ivanpopelyshev** [comment]
That's one of "fastrect" optimizations: it wants to determine if its possible to use scissor mode, and for that it needs at least one shape in the graphics. I can fix it with a PR, but it will be separate from my build. You can find the place with "maskData.graphicsData[0].shape.type === 1" in your pixi.js file and add one more condition before it "maskData.graphicsData.length === 1" for now

**Comment by rkrasky** [comment]
Thank you Ivan! Again!

**Comment by ivanpopelyshev** [comment]
please reopen it, i will attach PR here
