### ISSUE TITLE
Do you see the flickering during this animation? (Pixi + pixellated Chrome)

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2713]
This issue literally drove me crazy for a long while, I eventually disabled "image-rendering: pixellated" on Chrome to solve it (Applied to "canvas" at CSS)

Here is the animation: http://www.kaansoral.com/images/pixel/index.html

On my external monitor, which is a Dell P2415Q, the animation highly flickers, basically columns with different contrasts appear on the screen, I got a replacement, same thing happens on the new monitor

What really confuses me is that the same flickering isn't noticeable on other monitors, other systems (one with another IPS screen), only with this specific monitor (The monitor is externally connected to a macbook pro with retina screen, on the retina screen the animation is a regular animation, no funky stuff) - The issue happens on OSX or Windows on Chrome (Windows is a different machine, so it's not the same machine)

I'm wondering whether this is a PIXI/Chrome issue that is only observable in the color conditions of this specific monitor, or whether some lcd-types are incapable of rendering highly pixellated stuff

I would really, really appreciate some input

**Comment by ivanpopelyshev** [comment]
Is it UHD? If so, may be changing resolution of renderer will help.

try new WebGLRenderer(window.innerWidth, window.innerHeight, {resolution: 2, autoResize: true})

**Comment by kaansoral** [comment]
It's 4K, Thanks for the suggestion, just tried it, no observable change, flickering continues

It's a very bizarre issue for me, I want the game to have perfect pixels, yet I can't develop the game with this issue, so I disabled the pixellation, I'm also unsure what percentage of people will experience this issue - and what exactly is the issue

**Comment by ivanpopelyshev** [comment]
I can try it on 4K in my office next week

**Comment by kaansoral** [comment]
Thank you

If it's not a Chrome or PIXI issue, I'm suspecting it might be perfect patterns like this revealing a short-coming of this specific IPS screen, the lcd pixels might not be able to regain color fast enough, it might be manifesting as flickering columns

What's interesting is that only this animation/usage triggers it, nothing else

I'm not even sure whether I should be investigating this issue, I could put a "Perfect Pixels" settings into the game and disable it myself, assuming 99%+ of people won't experience this issue - since I couldn't make anyone replicate it, yet it's persistent for me

**Comment by ivanpopelyshev** [comment]
Anyway, please make second version for me to test it: 

```js
var renderer = PIXI.autoDetectRenderer(window.innerWidth,window.innerHeight, {resolution:window.devicePixelRatio, autoResize:true});
```

that way i'll be able to test it correctly on my display too

**Comment by kaansoral** [comment]
Here you go: http://www.kaansoral.com/images/pixel2/index.html

If you want to play around with it, it's just one .html file, pixi.js and outside.png

As an intensity indicator, the tearing is very noticeable, it's not too subtle, looking at it for 10 seconds is enough to give a headache

**Comment by kaansoral** [comment]
By the way, tested:
`resolution:window.devicePixelRatio, autoResize:true`

On my game, it has the same effect as:
`canvas{image-rendering: pixelated;}`

Which is pretty interesting, so `image-rendering: pixelated;` can probably be eliminated as the cause - as the flickering occurs in both scenarios

Off topic, it's an interesting observation for pixel games, resolution:2 should assumably multiply the load by 4, `image-rendering: pixelated;` provides the same looks with assumably less than 1x load

**Comment by ivanpopelyshev** [comment]
In your case, yes. But that way you can do that:

```js
map.x = Math.round(x * renderer.resolution) / renderer.resolution;
map.y = Math.round(y * renderer.resolution) / renderer.resolution;
```

**Comment by GoodBoyDigital** [comment]
webGL renderer now respects renderer.roundPixels. This should sort it! 👍
