### ISSUE TITLE
extractUniformsFromString matches commented lines.

### ISSUE THREAD

**Issue by Excaa** [pixijs/pixi.js#2714]
Extratc uniform assumes commented lines are also uniforms if they match the regexp.

Example of issue https://dl.dropboxusercontent.com/u/8932415/pixi_shader_uniform_detect/shader_uniform_detect.html

**Comment by GoodBoyDigital** [comment]
good catch! will make sure to check sort this one 👍

**Comment by englercj** [comment]
Going to track this in #2999, thanks for bringing it up!
