### ISSUE TITLE
 Unreliable mouse interaction with rope mesh

### ISSUE THREAD

**Issue by aatishb** [pixijs/pixi.js#2717]
Hi, I'm trying to modify the 'strip' pixi.js example that demonstrates the rope mesh. I tried adding interactivity to the rope so that when I click it the size changes.

https://codepen.io/aatish/pen/yJPWBx

However, the click behavior seems unreliable for me. It works in some places and not in others, and I'm having trouble understanding where in the image I should be clicking for the interaction to occur. Ideally I would like the interaction behavior to happen whenever I click within the boundaries of the snake. 

Thanks,
Aatish

**Comment by ivanpopelyshev** [comment]
Actually, thats not a bug. PIXI cant detect what is the size of your canvas, it must be exactly 1:1 with CSS pixel.

**Comment by ivanpopelyshev** [comment]
https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js - that's V4 with my PR, it works.

**Comment by aatishb** [comment]
It works perfectly! Thank you!
