### ISSUE TITLE
Text.style.lineHeight fix

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#2719]
Hello... I've got a problem with PIXI.Text and lineHeight. My text is cropped if lineHeight is set lower than the font size. This is the calculation of the height in PIXI.Text.updateText():
`var height = lineHeight * lines.length;`

Shouldn't it be:
`var height = Math.max(lineHeight, fontProperties.fontSize) + (lines.length - 1) * lineHeight;`

```
var renderer = new PIXI.WebGLRenderer(800, 600);

document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

var t1 = new PIXI.Text("Line height\ndefault");
t1.style.fill = 0xffffff;
t1.style.fontSize = 36;
stage.addChild(t1);

var t2 = new PIXI.Text("Line height\nmodified");
t2.x = 300;
t2.style.fill = 0xffffff;
t2.style.fontSize = 36;
t2.style.lineHeight = 30;
stage.addChild(t2);

animate();

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

**Comment by rkrasky** [comment]
Can someone make a PR.. perhaps... :)

**Comment by englercj** [comment]
I'm pretty sure the expect behavior of `lineHeight` is an override to the normal height calculations. So if you set `lineHeight` we treat it like you know better than us and we don't calculate height, we just use your value.

**Comment by rkrasky** [comment]
But the text is cropped if you set the `lineHeight `smaller than the `fontSize`. So setting `lineHeight `makes no sense.

**Comment by englercj** [comment]
I see what you are saying, the canvas is too small; not the actual line height of the rendered text.

**Comment by rkrasky** [comment]
Thanks @GoodBoyDigital
