### ISSUE TITLE
PIXI.Mesh WebGL flickering on android devices

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#2721]
I've got display errors with PIXI.mesh.Plane. The bitmap is flickering all the time and after a while it's disappearing. This happens only on android devices (tested on Nexus 5 with Android 5.1.1, Samsung Note 5) and only for WebGL renderer, iOS is working fine, desktop too (tested on Safari iPhone 6, Chrome, Firefox, Edge). Perhaps it's related to these issues: [#2712](https://github.com/pixijs/pixi.js/issues/2712), [#2699](https://github.com/pixijs/pixi.js/issues/2699)

Sample code:
```
var renderer = new PIXI.WebGLRenderer(800, 600);

document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

PIXI.loader.add("test", "bunny.png").load(function() {

    var texture = PIXI.Texture.fromImage("bunny.png");

	var plane = new PIXI.mesh.Plane(texture);
	stage.addChild(plane);

    animate();
});

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

**Comment by rkrasky** [comment]
It's NOT working:

- Samsung Note, Android 5
- Nexus 5, Android 5.1.1
- Sony xPeria, Android 5

It's working:
- Sony Z5 compact, Android 6
- HTC M9, Android 6
- all iOS devices

PIXI v3 Mesh is working on ALL devices.

**Comment by rensrongen** [comment]
I can confirm a similar issues rendering PIXI.Mesh on my Galaxy S4(Android 5.0.1). It works fine in v3, but in v4 Meshes are flickering.

I'll report back once I've changed the default shader precision later today, as suggested in #2699

**Comment by rkrasky** [comment]
How can I change the default shader precision?

**Comment by GoodBoyDigital** [comment]
This guy -> ```PIXI.PRECISION.DEFAULT = PIXI.PRECISION.HIGH```

**Comment by rkrasky** [comment]
Thanks @GoodBoyDigital. Changing the precision doesen't make any difference. Issue occurs furthermore.

**Comment by rensrongen** [comment]
Same here, no difference. Old iPad2 suffers the same problem.

**Comment by rkrasky** [comment]
Does someone have a clue? All PIXI meshes are unusable, also NineSlicePlane from @whizzkid.

**Comment by ivanpopelyshev** [comment]
I can test it on ipad2 , thank you, ill look soon :)

**Comment by GoodBoyDigital** [comment]
Hello! Could you try adding this line BEFORE you create a renderer:

PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;

Thanks!

**Comment by rkrasky** [comment]
On Nexus 5 it's working! Great!

**Comment by GoodBoyDigital** [comment]
sweet! Might disable this by default until it becomes more stable in mobile
browsers

**Comment by ivanpopelyshev** [comment]
Just wanted to write about "PIXI.glCore.VertexArrayObject.FORCE_NATIVE" . @GoodBoyDigital did it faster ;)
