### ISSUE TITLE
Uncaught TypeError: Cannot set property worldTransform of #<DisplayObject> which has only a getter

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#2723]
Hi I'm trying to destroy the stage with ```stage.destroy(true)``` in pixi v4, but I get the following error when a displayObject tries to set it's worldTransform to null.

<img width="901" alt="screen shot 2016-07-14 at 18 03 21" src="https://cloud.githubusercontent.com/assets/820/16848273/e0909896-49ec-11e6-924d-da3ef8482425.png">

Any ideas ?

**Comment by weepy** [comment]
Tried the dropbox build, but same problem.
I'm also getting 

Uncaught TypeError: Cannot read property 'updateTransform' of null

<img width="904" alt="screen shot 2016-07-14 at 18 31 28" src="https://cloud.githubusercontent.com/assets/820/16849089/ca7845e6-49f0-11e6-9535-7ff81b59741d.png">

**Comment by ivanpopelyshev** [comment]
Try that one: https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js

**Comment by weepy** [comment]
negative

it's one the line

```
... this.worldTransform = null; ...
```

I guess since worldTransform is a getter it doesn't like it ?

**Comment by ivanpopelyshev** [comment]
yep
need set transform to null instead

**Comment by weepy** [comment]
how to do that ?

**Comment by weepy** [comment]
@ivanpopelyshev what did you mean by ```need set transform to null``` ?

**Comment by GoodBoyDigital** [comment]
fixed!
