### ISSUE TITLE
Right click not triggerd by 'mousedown' event

### ISSUE THREAD

**Issue by Lycan2k** [pixijs/pixi.js#2724]
Hi,
as said in the title I think the 'mousedown' event isn't thrown by a right mouse button click.
To make it short. You can see that it isn't working in this official example
http://pixijs.github.io/examples/index.html?s=demos&f=interactivity.js&title=Interactivity

Is this on purpose or a bug. Is there a workaround?
If you use the 'click' event right clicks actually work, well but that isn't the same.

Thanks in advance

**Comment by themoonrat** [comment]
The available events are

'mousedown','mouseup','rightdown','rightup','click','rightclick','mousemove','mouseover','mouseout','mouseupoutside','rightupoutside'

so you need to listen to rightdown for right mouse button presses
