### ISSUE TITLE
Text won't change his color until it changes its text content

### ISSUE THREAD

**Issue by LucianoGraziani** [pixijs/pixi.js#2725]
When I want to chage the color of a Text component, only when an event is fired, it won't. It'll change other properties as position or scale, but not his color. Only if I force to change his content, will do.

Here is a live example with that error: http://codepen.io/lgraziani/pen/PzERNB?editors=0010
I used PIXIv3.

Is that behavior on purpose? Or is just a bug?
If is on purpose, how I can make it work?

See you.

**Comment by ivanpopelyshev** [comment]
Can you please try it on v4? latest v4 build is here: https://dl.dropboxusercontent.com/u/46636530/pixijs/pixi.js . Yes, dropbox, i am sorry

**Comment by LucianoGraziani** [comment]
Ohh! Is fixed on PIXIv4.

**Comment by GoodBoyDigital** [comment]
fixed! Good to hear! 👍
