### ISSUE TITLE
iOS 10 beta - WebGLRenderer renders PNGs with alpha incorrectly.

### ISSUE THREAD

**Issue by POlITIC** [pixijs/pixi.js#2726]
Create texture from any png image that has transparent areas in it.
Create a sprite from this texture and render it with WebGLRenderer.
Run this on iOS10 beta and observe results:
<img src="https://cloud.githubusercontent.com/assets/1701819/16894466/b79c1df6-4b5f-11e6-9d0d-7ecaec8f326b.PNG" height="200">

Result is that WebGLRenderer draws alpha areas with some artifacts.

The same code is run on iOs 9.3.2 - works fine:
<img src="https://cloud.githubusercontent.com/assets/1701819/16894467/b79d185a-4b5f-11e6-8e48-a0a283ff722b.jpg" height="200">

Code snippet: https://jsfiddle.net/xshn8nvu/1/

Or just run this(http://www.goodboydigital.com/pixijs/examples/16/) pixi sample on iOs10.

**Comment by GoodBoyDigital** [comment]
Hello! Thanks for sharing, I noticed this issue too when I installed the beta a little while back. Im 99% sure its a safari bug that will be rectified by the time iOS10 is officially released. Lets keep this open until its sorted.

**Comment by ivanpopelyshev** [comment]
Try this one please: https://dl.dropboxusercontent.com/u/46636530/pixijs/multutex/pixi.js

**Comment by POlITIC** [comment]
Seems like this issue is now fixed on iOS side.Can be tested on latest beta. So I'm closing this issue.
