### ISSUE TITLE
Any plan to support WebGL 2.0 and WebAssembly

### ISSUE THREAD

**Issue by hmilyyang** [pixijs/pixi.js#2727]
Since the bottle neck of the performance is JS according to   #2366 , I think there will be a significant performance boost when using WebGL 2.0 and WebAssembly.

**Comment by englercj** [comment]
WebAssembly is just asm.js, so the same cross-boundary call costs apply. If you wrote everything, including things that use pixi, in C++ and compiled to asm.js it would be faster.

But if we wrote this lib in C++, compiled to asm.js, and gave it to you to use in your JS app it would be slower, significantly. I've tried to make that work.

**Comment by hmilyyang** [comment]
Thank you for your apply. And thank you for your Great works!

**Comment by mchiasson** [comment]
WebAssembly is just asm.js? Not at all. Two different technologies, and WebAssembly is much much faster than asm.js

**Comment by englercj** [comment]
@mchiasson It was in fact the exact same compiler and vm as asm.js at the time of writting that post (at least the public version was). Wasm has since forked from asm.js.

Originally, wasm was just asm.js but delivered as bytecode to skip the expensive decoding step.

**Comment by ErosZy** [comment]
the egret framework(https://www.egret.com/en/) use wasm in their 5.0 version, they solve the problem that "cross-boundary call costs" can be used for reference.
