### ISSUE TITLE
Pixi v4 - iOS flickering spritesheets

### ISSUE THREAD

**Issue by guilanier** [pixijs/pixi.js#2731]
Hi there,
I have an issue on ios with the latest pixi build (dev branch): playing a spritesheet on ios either by setting the frame of the texture manually or by using the built-in PIXI.MovieClip is making the sprite flicker each frame. The problem doesn't happen on desktop or any other devices not running on iOS. You can see this issue there if you are on iOS : https://dl.dropboxusercontent.com/u/29261094/pixi-spritesheet/index.html

**Comment by ivanpopelyshev** [comment]
Try this one please: https://dl.dropboxusercontent.com/u/46636530/pixijs/multutex/pixi.js

**Comment by guilanier** [comment]
Hey @ivanpopelyshev I've just tried it and put it there : https://dl.dropboxusercontent.com/u/29261094/pixi-spritesheet2/index.html
The problem is remaining on iOs devices

**Comment by ivanpopelyshev** [comment]
pasting from the other issue, try it 

PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;

**Comment by guilanier** [comment]
That is looking better: https://dl.dropboxusercontent.com/u/29261094/pixi-spritesheet3/index.html

 thanks a lot for that, it is still flickering though but less than previously

**Comment by ivanpopelyshev** [comment]
And if you use both my pixi.js and that line?

**Comment by guilanier** [comment]
yes absolutely, that's what happen on the last link

**Comment by englercj** [comment]
Can you retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!

**Comment by themoonrat** [comment]
@guilanier as above.. could you check if this is still an issue on the latest PIXI please? Thanks

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
