### ISSUE TITLE
Weird issue when setting Sprite.visible to false

### ISSUE THREAD

**Issue by RanzQ** [pixijs/pixi.js#2734]
When using a sprite sheet and `Sprite.fromFrame` I noticed that if I set `visible = false` for a single sprite, all other sprites using the same texture aren't rendered. And the weird thing is that this doesn't happen on my desktop Chrome but on a RPi with [WebKit](https://github.com/Metrological/WebKitForWayland/) (WebGL enabled).

Setting visibility for Container works ok, just in case someone ends up with a similar problem.

Any idea why this could happen?

**Comment by ivanpopelyshev** [comment]
pixi v3 or v4?

**Comment by RanzQ** [comment]
@ivanpopelyshev v4, 8fdb17a92f8f1fe015e59d153274c1be0b7ee6f8 to be exact

**Comment by ivanpopelyshev** [comment]
It looks like issue with Sprite._textureID, somehow other sprites dont see that it was updated.. What if you preload stuff with PIXI.loader?

**Comment by RanzQ** [comment]
@ivanpopelyshev I'm using the loader and start rendering after all textures (3 json sheets now) have loaded. I noticed I was initializing one sprite like this:
```
  this.addGreenFrameToStage = () => {
    let greenFrame = PIXI.Sprite.fromFrame('green-frame')
    // greenFrame.visible = false
    greenFrame.alpha = 0.0

    this.stage.addChild(greenFrame)
  }
```
Commenting that line made all the other sprites render again. Touch events were still handled for the invisible sprites, so I guessed it must be some visibility issue.

**Comment by ivanpopelyshev** [comment]
Do you use any esoterics like ParticleContainer?

**Comment by RanzQ** [comment]
No, just `new PIXI.Container()` as stage and some child containers as well.

**Comment by ivanpopelyshev** [comment]
can you make simple demo of that? I think its something about multitexturing. I just need to see the actual code that works on PC but doesnt work correctly on mobiles.

**Comment by ivanpopelyshev** [comment]
Waaait, i actually have an idea. Wait just one moment..

**Comment by ivanpopelyshev** [comment]
Try that one: https://dl.dropboxusercontent.com/u/46636530/pixijs/multutex/pixi.js

**Comment by RanzQ** [comment]
@ivanpopelyshev that works! :)

**Comment by GoodBoyDigital** [comment]
fixed 👍
