### ISSUE TITLE
Reel Spinning in a slot machine

### ISSUE THREAD

**Issue by tywang2006** [pixijs/pixi.js#2737]
I am trying to do a slot machine, normally what i did is just combining  multi textures of icons then display one texture in a sprite. due to reel band's being dynamic, I can't put all icons in a fixed sprite sheet. is there a way to combine icons for reel spinning or is there better way to do that? I need to make a very high performance method because I need to run it in the mobile as well, thank you very much

**Comment by ivanpopelyshev** [comment]
How many elements with different textures appear in one frame? In Pixi-v4 you can use up to 8 textures on mobiles in one batch. If your stuff fits in about 20 batches, it will certainly be ok on mobiles.

**Comment by tywang2006** [comment]
It will be 3*5 slot(I want to make it flexible framework then it can be any size of reel layout). So it has 15 symbols at least. When the reel is spinning, in each reel, it will show full symbol and pat of symbol to simulate a spinning animation. That is why I need to combine some part of symbols and full symbols in one texture that will be for one reel. Each reel have dynamic reel band to tell how to display symbol when the reel is animated. I'm just look into pixies. I used to make it in OpenGL in c++. I did render multi texutes(some are part of symbols, some are full symbol size depending on how to display symbols during spinning). I did unity for slot as well, in unity, I just shift symbol position and update texture on each symbol constantly in update of each frame then drop mask to hide top and bottom because no fast render api in unity.

发自我的 iPhone

在 2016年7月21日，00:48，Ivan Popelyshev <notifications@github.com<mailto:notifications@github.com>> 写道：


How many elements with different textures appear in one frame? In Pixi-v4 you can use up to 8 textures on mobiles in one batch. If your stuff fits in about 20 batches, it will certainly be ok on mobiles.

**Comment by tywang2006** [comment]
There will be at least 20 different icons in e game, if it is 5*3 reel layout, it should have at least 15 symbols slot. Can we draw 3 symbols in one batch for a reel, then it has 5 reels so it should be 5 batches. How to draw part it symbol, and full symbols then combine them in a single reel. Maybe combine them into a single texture assigned to a Sprite. Or is there any better solution for mobile:) thank you very much:)

**Comment by englercj** [comment]
Can you put all the icons/symbols in a sprite sheet, then create each strip as a series of sprites?

> due to reel band's being dynamic, I can't put all icons in a fixed sprite sheet.

Not sure I follow what stops you from using a spritesheet here, can you explain that more? In my head I see a sheet with all the parts to make any symbol, then each band is just a container with X sprites in it for all the different panels of a band. Or are you generating the symbols at runtime? Can you put on a sheet the parts used to generate a symbol, and then use sprites in a container together to create 1 symbol?

**Comment by tywang2006** [comment]
sure i think we can put all icons in a spritesheet.


I want to generate at runtime, I  can't do a strip at the very beginning because there will be very different case to swap reelband and update any symbols with differe icons based on server response. the example is below, in the runtime, i need to draw icon1(part), icon2(full), icon3(full), icon4(part).


in canvas, there is function drawImage, to render texture based on the frame of the orignal texture (frame is a rectangle to tell the display area) thank you very much:)


[cid:78999c5f-33cf-4e15-a5be-bbbb96a9f3ab]

________________________________

**Comment by themoonrat** [comment]
You can re-assign textures to sprites. So you want, say, 5 sprites per reel.
A sprite gets assigned a texture as it appears from the top, and when it disappears off of the bottom is ready to be re-assigned a new texture to appear from the top again.

**Comment by englercj** [comment]
Yeah it sounds like you can do this with 1 sprite sheet, a Texture for each rect in the sheet, and a pool of sprites you just reassign textures to as they "rotate" down the band.

> in canvas, there is function drawImage, to render texture based on the frame of the orignal texture (frame is a rectangle to tell the display area)

That is exactly what a `Texture` is in pixi. A `BaseTexture` is the actual image (the spritesheet) and a `Texture` is what frame of that image to draw. You would have 1 `BaseTexture` for your sheet, and 1 `Texture` for each symbol in the sheet. Then 1 `Sprite` for each visual/positional symbol rendered. Sprites can share `Texture` instances (so you only need 1 per symbol, not 1 per sprite), and their texture can change at any time.

As long as all those sprites have `Texture` objects that all share a single `BaseTexture` they will all be batched in a single draw.

**Comment by GoodBoyDigital** [comment]
Closing for now @englercj has given you lots of juicy tips to get started. 👍
