### ISSUE TITLE
Request: PIXI Performance Guidelines Document

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2738]
When you are starting things, peak performance isn't a concern, but as soon as you are doing something relatively large, it becomes a significant concern

It would be great if there were some basic/main guidelines, suggestions, a list of them, an easily accessible small doc filled with them

For example, while reading issues, I stumbled onto: #2737 - so as an outsider, it's good to know BaseTexture minimisation is important - but I wonder whether loading unused BaseTexture's slow down things, whether there are internal reports that can output what happened at each draw, whether there are internal metrics / reporting utilities that would aid someone who are trying to improve things in this area - and stuff like this

As another example, this was pretty useful too: http://www.html5gamedevs.com/topic/23604-ideas-for-dynamic-map-drawing-re-tiling/ - so now, personally, I re-use Sprite's too, for heavy/recurring draw routines - For each Texture-type, I have an array of Sprite's

**Comment by englercj** [comment]
These can be good additions to the Wiki, or at least to the [Tips & Tricks](https://github.com/pixijs/pixi.js/wiki/Tips,-Tricks,-and-Pitfalls) page.

The Wiki is totally open so feel free to write something up! Great idea!

Some of those (like reusing sprites) isn't pixi specific (allocation is expensive, as a general rule). But stuff like how to get the most of batching and stuff would be awesome.

**Comment by SeminYun** [comment]
agree too. this will be needed.. 

i'm always concerning performance and i'm trying to optimize of many parts like 

if developer is considering mobile, it will be more and more important.. specially about of cpu

mobile's cpu is really really slow..

if  having tips & Tricks, it will be very useful and there are very good ideas to create new version

**Comment by englercj** [comment]
Closing this for now, for anyone else landing here or anyone who wants to help: adding any tips to the [Tips & Tricks](https://github.com/pixijs/pixi.js/wiki/Tips,-Tricks,-and-Pitfalls) page would be very helpful.

Thanks!
