### ISSUE TITLE
arc render bug when x is greater than radius

### ISSUE THREAD

**Issue by yreenchan** [pixijs/pixi.js#2742]
I want to render an semicircle witth method arc，but when x is greater than radius. It didn't render correctly.
![333111](https://cloud.githubusercontent.com/assets/3251726/17054452/d5465572-5039-11e6-8805-72ffe58a679c.jpg)

 I have wrote a sample in jsfiddle.
[https://jsfiddle.net/yreenchan/0c85uxoh/](https://jsfiddle.net/yreenchan/0c85uxoh/)

**Comment by englercj** [comment]
Looks like this is still active in v4:

![image](https://cloud.githubusercontent.com/assets/944497/18960424/8dda272a-861e-11e6-9df4-e5663938a0d3.png)

**Comment by staff0rd** [comment]
Looks fixed in latest; https://jsfiddle.net/16cbefab/
