### ISSUE TITLE
TilingSprite ignoring realtime texture updates with Canvas renderer.

### ISSUE THREAD

**Issue by slackjockey** [pixijs/pixi.js#2743]
So I'm using [PIXI.extras.TilingSprite](https://pixijs.github.io/docs/PIXI.extras.TilingSprite.html) with the new 4.0.0-RC2. I updated to this version after seeing this bug with 3.0.11 while using PIXI.js within [nwjs](http://nwjs.io/), which is pretty much Chromium, in both OS X 10.11 and Ubuntu 16.04. 

I'm using TilingSprites to allow for sprite sheets, which works great if everything is on a single sprite sheet, but when changing sheets (walking, jumping, etc.) the following update seems to be ignored when using the Canvas renderer.

`spriteObj.texture = textureObj;`

The update works perfectly when using the WebGL renderer though. It seems to work when the object is first created and the initial texture is applied, but seems to stop working after the object is attached to a stage.

I'll work on getting more source code together for a better example, but there isn't a lot to do here to reproduce it: just do an assignment as above and see if it's caught in the next render call. Try that with both the WebGL and Canvas renderers. We're working with the WebGL renderer for the time being, but I'm not sure that our target platform will support this renderer (currently a debian os running nwjs).

**Comment by slackjockey** [comment]
lol...found this poking around the source code: https://github.com/pixijs/pixi.js/blob/master/src/extras/TilingSprite.js#L237

**Comment by slackjockey** [comment]
just a minor update from my part: it looks like this is a deal-breaker after all as we only have access to a Canvas renderer in debian, out-of-the-box. Still working on finding a workaround or alternative).

**Comment by ivanpopelyshev** [comment]
Yeah, its a bug. Realy need to fix all wrongs with TilingSprite.

Right now you can monkey-patch something. Try tracking tilingTextureID, and change texture ID when you do something with it.


```js
//this is when you change the texture
texture._updateID++;
//this is after you include pixi.js
TilingSprite.prototype._renderCanvas = function (renderer)
{
    var texture = this._texture;

    if (!texture.baseTexture.hasLoaded)
    {
      return;
    }

    var context = renderer.context,
        transform = this.worldTransform,
        resolution = renderer.resolution,
        baseTexture = texture.baseTexture,
        modX = (this.tilePosition.x / this.tileScale.x) % texture._frame.width,
        modY = (this.tilePosition.y / this.tileScale.y) % texture._frame.height;

    // create a nice shiny pattern!
    // TODO this needs to be refreshed if texture changes..
    if(!this._canvasPattern || this._tilingTextureID !== texture._updateID)
    {
        this._tilingTextureId = texture._updateID;
        // cut an object from a spritesheet..
        var tempCanvas = new PIXI.CanvasRenderTarget(texture._frame.width, texture._frame.height);

        // Tint the tiling sprite
        if (this.tint !== 0xFFFFFF)
        {
            if (this.cachedTint !== this.tint)
            {
                this.cachedTint = this.tint;

                this.tintedTexture = PIXI.CanvasTinter.getTintedTexture(this, this.tint);
            }
            tempCanvas.context.drawImage(this.tintedTexture, 0, 0);
        }
        else
        {
            tempCanvas.context.drawImage(baseTexture.source, -texture._frame.x, -texture._frame.y);
        }
        this._canvasPattern = tempCanvas.context.createPattern( tempCanvas.canvas, 'repeat' );
    }

    // set context state..
    context.globalAlpha = this.worldAlpha;
    context.setTransform(transform.a * resolution,
                       transform.b * resolution,
                       transform.c * resolution,
                       transform.d * resolution,
                       transform.tx * resolution,
                       transform.ty * resolution);

    // TODO - this should be rolled into the setTransform above..
    context.scale(this.tileScale.x,this.tileScale.y);

    context.translate(modX + (this.anchor.x * -this._width ),
                      modY + (this.anchor.y * -this._height));

    // check blend mode
    var compositeOperation = renderer.blendModes[this.blendMode];
    if (compositeOperation !== renderer.context.globalCompositeOperation)
    {
        context.globalCompositeOperation = compositeOperation;
    }

    // fill the pattern!
    context.fillStyle = this._canvasPattern;
    context.fillRect(-modX,
                     -modY,
                     this._width / this.tileScale.x,
                     this._height / this.tileScale.y);


    //TODO - pretty sure this can be deleted...
    //context.translate(-this.tilePosition.x + (this.anchor.x * this._width), -this.tilePosition.y + (this.anchor.y * this._height));
    //context.scale(1 / this.tileScale.x, 1 / this.tileScale.y);
};

```

**Comment by staff0rd** [comment]
Hey @slackjockey, is this still affecting you?  Are you able to supply a [fiddle](https://jsfiddle.net) or [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by slackjockey** [comment]
@staff0rd it looks to be so.

I'm testing with [v.4.3.0](https://github.com/pixijs/pixi.js/releases/tag/v4.3.0). I'll to get a code sample together in a bit but in the meantime, our steps are fairly simple:

* create an empty Sprite instance
* manually set the Sprite instance's texture, width, height, and tilePosition attributes.
* attach it to a container and start a render loop, rendering the container.
* update the Sprite instance's texture attributes, while the render loop is running.

This should be visually apparent, with the updates to texture, with the WebGL renderer. When the same code is run using the Canvas renderer, the Sprite instance retains the texture that was applied prior to attaching it to the rendered container, regardless of what it's texture attribute is set to.

**Comment by englercj** [comment]
@ivanpopelyshev have you had a chance to look at this?

**Comment by sylwesterdigital** [comment]
Hello, maybe it's not 100% relevant to above but my problem is also related to tilingSprite. 
I built a mobile game 2 years ago and after long break decided upgrade game transitioning from Pixijs 2 to the latest ie 4.5. Some things are now different but I managed almost every new feature. So my problem with tilingSprite in general is that after couple minutes of the same animation it's just changin from nice pic to something like mosaic (see pics below)

I create such sprite this way

`var texture = PIXI.Texture.fromImage('assets/tiles/met/met3.jpg');
tilingSprite = new PIXI.extras.TilingSprite(texture, game.appW, game.appH);`

then it's animated by changing tilePosition.x or y

`tilingSprite.tilePosition.y += 8;`

On iPhone after few minutes the texture of tilingSprite became from this

[https://mielniczuk.com/games/debug/IMG_8734.PNG](url)

to this

[https://mielniczuk.com/games/debug/IMG_8738.PNG](url)

and even worse...

[https://mielniczuk.com/games/debug/IMG_8740.PNG](url)

what's the problem?
Need to say that did not experience this issue with Pixijs 2, game is still on Apple Store
This is crucial issue because I can not proceed with new game release.

Any clue?

**Comment by sylwesterdigital** [comment]
My tilingSprite became mosaic with no reason... any clue?

![img_8734](https://cloud.githubusercontent.com/assets/27820237/25432139/38d55388-2a7b-11e7-8652-7fd74ec5ea9e.PNG)
![img_8737](https://cloud.githubusercontent.com/assets/27820237/25432146/3e03fa1c-2a7b-11e7-8ea0-2becf071f4d0.PNG)
![img_8740](https://cloud.githubusercontent.com/assets/27820237/25432151/4037bf6c-2a7b-11e7-8636-0eeec6b84c59.PNG)

**Comment by slackjockey** [comment]
@sylwesterdigital just a guess, but it's possible that this might be due to the tilePosition values in the TilingSprite moving beyond the document bounds. I recall that v. 2.x did wrap (at least horizontally as i recall). While I don't have a lot for evidence at this point, I wouldn't be surprised if this may have changed. Unfortunately, I am no longer using Pixi.js in my work so I don't have a live example I can test this with on hand, but i'll see if i have an old version of something handy.

My bug was that updates to Sprite.texture were not catching in Canvas after the sprite was rendered for the first time. I can't speak to whether it works in 4 or not, because I found it simpler to just use Canvas directly than to maintain monkey patches or try and get all of the dependencies to get WebGL working on a target platform not expected to render beyond 480i.

**Comment by sylwesterdigital** [comment]
Thanks mate. Anyways I just fixed my issue just resetting  tilePosition.x and y - I thought maybe this is somehow managable other way but it works

```
// t - tilingSprite reference
function fixt(t) {
	var w = t.width; 
	var h = t.height;	
	if(t.tilePosition.x <= -w) {
		t.tilePosition.x = 0;
	}
	if(t.tilePosition.y <= -h) {
		t.tilePosition.y = 0;
	}
}
```
