### ISSUE TITLE
Render warning v4 latest build

### ISSUE THREAD

**Issue by Good4m** [pixijs/pixi.js#2744]
**Receiving these warnings 15 times for every rendering call:**
[.CommandBufferContext.Offscreen-MainThread-00000214035F6070]RENDER WARNING: there is no texture bound to the unit 1
index.html:1 [.CommandBufferContext.Offscreen-MainThread-00000214035F6070]RENDER WARNING: there is no texture bound to the unit 2
index.html:1 [.CommandBufferContext.Offscreen-MainThread-00000214035F6070]RENDER WARNING: there is no texture bound to the unit 3
index.html:1 [.CommandBufferContext.Offscreen-MainThread-00000214035F6070]RENDER WARNING: there is no texture bound to the unit 4

**See closed issue #2495 **

**Comment by GoodBoyDigital** [comment]
Hi @Good4m! Thanks for sharing your issue, if you can provide a fiddle I will take a look (i have had trouble recreating this one!)

Cheers!

**Comment by Good4m** [comment]
Pulled latest dev commits rather than RC release and it seems to have been fixed
