### ISSUE TITLE
Filter on Container makes things invisible

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2746]
```
map=new PIXI.Container();
var filter=new PIXI.filters.ColorMatrixFilter()
filter.desaturate(0.2);
map.filters=[filter];
```

There are tiles on the map, they are visible, there are moving sprites on the map, they are invisible when the filter is applied

It's not persistent tho, when everything is redrawn, the moving sprites are visible for a while

**Comment by ivanpopelyshev** [comment]
What kind of tiles, pixi tilemap?

**Comment by kaansoral** [comment]
No, regular PIXI.Sprite's, that's why the issue is bizarre, since moving monsters are similar PIXI.Sprite's too - I tried disabling pixi-display, it wasn't the cause, tried various other things, yet I can't solve it, yet

**Comment by kaansoral** [comment]
Actually, I just realised it's probably pixi-display - filters probably break pixi-display, when pixi-display is broken, the tiles get on top of monsters

**Comment by ivanpopelyshev** [comment]
yep. Either you apply filters to the parent of element with displayList, either you apply it to leafs. How do you think pixi-display is suppoesd to work when tehre's filter between two components, both having displayGroup?

**Comment by kaansoral** [comment]
PIXI is a black-box for me, I'm exploring the inner workings as I go, and as much as I need to :)

Anyway, creating another issue on pixi-display, thanks for your help
