### ISSUE TITLE
Crosswalk Webview issue WebGL -- Sprites not moving

### ISSUE THREAD

**Issue by samredfern** [pixijs/pixi.js#2747]
I have come across a strange issue when making a Cordova project (Android). When using the Crosswalk Webview plugin with WebGL rendering, Pixi sprites do not visually update when their position or scale is changed. The exact same code works fine when using Canvas rendering (or when not using Crosswalk).  (Pixijs 3)

**Comment by nuthinking** [comment]
Have you tried pixi 4rc?

**Comment by samredfern** [comment]
No, I just switched to Canvas rendering, which is fine for this project.
