### ISSUE TITLE
[WebGL] TilingSprite blurry compared to Sprite

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#2748]
TilingSprite, displayed at the same size as a Sprite, is displayed blurry;

![image](https://cloud.githubusercontent.com/assets/6289998/17199459/6082dd4c-54c0-11e6-974c-4356dd94f228.png)

https://jsfiddle.net/staff0rd/j3qyj5fn/1/

**Comment by staff0rd** [comment]
Updated the fiddle into include canvas renderer.  Looks like this is specific to WebGL.

**Comment by staff0rd** [comment]
A new fiddle, with the loaded texture using SCALE_MODES.NEAREST shows the TilingSprite has cut the border of the texture completely off;

![image](https://cloud.githubusercontent.com/assets/6289998/17201796/3e782648-54d5-11e6-8e13-0518b1e3f86e.png)

https://jsfiddle.net/staff0rd/qj901gok/

**Comment by staff0rd** [comment]
[This pen](https://codepen.io/staff0rd/pen/PGPgXr?editors=0010) displays the following from left to right for WebGL and then Canvas;

* Sprite @ Size = 1x, Resolution = 1
* Sprite @ Size = 2x, Resolution = 2
* Sprite @ Size = 2x, Resolution = 1, Scale = .5
* TilingSprite @ Size = 1x, Resolution = 1
* TilingSprite @ Size = 2x, Resolution = 2
* TilingSprite @ Size = 2x, Resolution = 1, Scale = .5

The stage is scaled to 2x for better visibility.

The 6th WebGL image shows that doubling the image size and scaling it by half is a workaround to get a better quality image (although not the quality of 6th Canvas image).  Note that the 5th and 6th images in both are exactly the **same image**.  The difference between them is only telling pixi that one is resolution 2, and that the other is resolution 1 but scaling it by half.

The incorrect display of the 5th Canvas image is due to #2083.

### WebGL

![image](https://cloud.githubusercontent.com/assets/6289998/18429721/54f3ae8a-7918-11e6-8735-2631c1311b4a.png)

### Canvas
![image](https://cloud.githubusercontent.com/assets/6289998/18429716/4e17c92a-7918-11e6-848c-d4657843d64e.png)

[https://codepen.io/staff0rd/pen/PGPgXr](https://codepen.io/staff0rd/pen/PGPgXr?editors=0010)

**Comment by kaansoral** [comment]
I use the shrinking method for Text's, otherwise the quality is unbearable (not PIXI's fault, I'm guessing, just things are) - but never thought of trying it for TilingSprite's - I should test it soon, great idea

I desperately need TilingSprite too, but in all my trials, the quality was awful - I remember seeing discussions of improvements, so I postponed using TilingSprite's (yet to test your method as I need to find a way to double the size of a texture first, to shrink it later on)

**Comment by englercj** [comment]
Looks like this is still active with latest v4:

https://codepen.io/anon/pen/NRvpPJ?editors=0010

**Comment by ivanpopelyshev** [comment]
#3048

```js
texture1.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
  texture2.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
  texture3.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
  texture1.smoothEdge2 = 1;
  texture2.smoothEdge1 = 0;
  texture3.smoothEdge1 = 0;
```

**Comment by ivanpopelyshev** [comment]
OK, I fixed more things, now balls work without any problems, while your alpha stuff works with 

```js
texture.clampBorder = -0.5;
```

**Comment by staff0rd** [comment]
webgl looks perfect, canvas tilesprite @2x is off; 
![image](https://cloud.githubusercontent.com/assets/6289998/20859791/7447d2e4-b9bd-11e6-80bc-3311c301659d.png)

@ivanpopelyshev is the `clampBorder` thing supposed to help there?  I couldn't see it having any effect.

**Comment by ivanpopelyshev** [comment]
I don't know how to do that in canvas. We are using CanvasPattern which does not have additional parameters. At least in webgl we can make different shaders and params for them
