### ISSUE TITLE
TilingSprite.fromFrame ignores transparency

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#2750]
When using TilingSprite.fromFrame, should the referenced frame include transparency, it will be ignored, resulting in tiling that is aligned minus the space of the transparency.  It can be seen in the end images below;

![image](https://cloud.githubusercontent.com/assets/6289998/17206745/a1f1005e-54f4-11e6-9a73-a224cfc11c00.png)

The images above are from right to left;
1. Sprite.fromImage
2. TilingSprite.fromImage
3. Sprite.fromFrame
4. TilingSprite.fromFrame

The second group is then the same again but using CanvasRenderer.  (Another issue is the border artifacts seen in TilingSprite for CanvasRenderer).

Notice that the end images of each group look to be positioned higher - this is because of the ignored transparency.  They additionally include right and bottom artifacts, due to the tile repeating too early because of the ignored transparent pixels.

https://jsfiddle.net/staff0rd/97j3v1tt/

**Comment by englercj** [comment]
Still active in latest v4:

https://jsfiddle.net/22o7v7wv/

**Comment by ivanpopelyshev** [comment]
I don't know of engines that allow transparency pads in texture when dealing with Mesh and TilingSprite. 

We can certainly implement that, but it will make TilingSprite shader slower.

I think its possible to make multiple shaders for TilingSprite for different cases:

1. mipmapping
2. texture with pads
3. texture without pads

**Comment by ivanpopelyshev** [comment]
You can try #3048 now, but remember to set

```js
texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
```

**Comment by ivanpopelyshev** [comment]
Also, that might help:

```js
texture.baseTexture.smoothEdge1 = 0;
```

**Comment by kaansoral** [comment]
Can you share a PIXI build built with #3048 for testing, please? :)

**Comment by ivanpopelyshev** [comment]
#3048

That wont help you because you actually dont have any transparent pixels on top-left of the texture.

**Comment by ivanpopelyshev** [comment]
OK, good news. I fixed the PR, now this thing works:

```js
 frameSprite.texture.clampMargin = -0.5;
```

**Comment by staff0rd** [comment]
Looks aligned properly in latest, although transparency is not preserved; https://jsfiddle.net/7f7kbb00/

<img src='https://cloud.githubusercontent.com/assets/6289998/20798068/aabda372-b831-11e6-8d96-cf64276b67bd.PNG' width="377" />
