### ISSUE TITLE
getBounds doesn't take into account position of parent container

### ISSUE THREAD

**Issue by dan335** [pixijs/pixi.js#2753]
I'm using the latest dev.  Container.getBounds() doesn't take into account the position of the parent container.  If the position of the parent container is changed getBounds() will be wrong.

**Comment by ivanpopelyshev** [comment]
Please build it yourself, latest version has tests about it. What you see in "bin/" directory is not the latest ;)

**Comment by dan335** [comment]
I built the latest dev.  I tried to make a simple reproduction but it's working as expected.  I'm doing something is breaking getBounds and text but can't figure out what.

**Comment by ivanpopelyshev** [comment]
getBounds() and other things are the subject of our last commits :)
