### ISSUE TITLE
Pixi V4 - pixi.mesh.Mesh doesn't apply blendMode, possible fix included

### ISSUE THREAD

**Issue by neutrino84** [pixijs/pixi.js#2754]
Pixi v4 mesh Mesh.js webGL render logic is missing a call to setBlendMode. I was able to fix the issue by adding the call as pictured below. Hopefully this is something that can be added to v4 when you guys have a chance.
```
Mesh.prototype._renderWebGL = function (renderer) {
  ...
  renderer.bindShader(glData.shader);
  renderer.bindTexture(this._texture, 0);
  renderer.state.setBlendMode(this.blendMode);
  ...
```

**Comment by ivanpopelyshev** [comment]
If you have some time, you can make a PR on that. It is a serious bug :)

**Comment by neutrino84** [comment]
alright will do, i'll fork and make a pr
