### ISSUE TITLE
textureCache does not use name but url as key?

### ISSUE THREAD

**Issue by hh8888** [pixijs/pixi.js#2757]
I can not access texture using provided name, but found it was saved using url as key in the textureCache.

in pixi.js
            core.utils.BaseTextureCache[resource.url] = baseTexture;
            core.utils.TextureCache[resource.url] = resource.texture;

Also, when is the new rc coming?

**Comment by getepicerror** [comment]
I agree. This is quite a pain.
The resources object passed to the complete function does contain the texture by the correct name, but in the texturecache it's only there by URL.

**Comment by ivanpopelyshev** [comment]
please don't use textureCache, use "loader.resources". That way you can have different loaders for different levels/stages, just forget old ones and that way memory will be freed.

If I'm not mistaken, @englercj wants to deprecate TextureCache.

**Comment by whizzkid** [comment]
You mean we should also not use Sprite.fromFrame  without proposed modification?
Because that's what I use all the time :)

**Comment by GoodBoyDigital** [comment]
Agreed! Sprite.fromFrame is super handy! Cache is staying. I agree that
more should be done to integrate them a little more smoothly. Also as an
FYI, you can also use Sprite.from() which intelligently figures out the
type of texture!

**Comment by englercj** [comment]
I think things should mostly be using `renderer.resolution` and I just committed a fix to properly default that property to `PIXI.RESOLUTION`. Closing this for now.
