### ISSUE TITLE
failed to load basetexture on is ios

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#2758]
ios is failed to load if loading a lot of basetextures at once.

this meaning is ios always happened on my game

if network is slow, it happened more and more..

how can i request if failed to load basetexture 

or how can i check it

thx 

best regards

Wrong shot
![wrong](https://cloud.githubusercontent.com/assets/5058355/17353141/e5bc1260-5977-11e6-92e1-abe5fdd695f8.png)

Good shot
![normal_shot](https://cloud.githubusercontent.com/assets/5058355/17353235/a706c8ac-5978-11e6-9d76-d7e5e4df2342.png)

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by SeminYun** [comment]
@GoodBoyDigital  thx...
i wanna make jsffile. but it can't.. becuase.. Hmm. i load 15 basetexture at once.
but it could make this issue..

so i checked out game.    how many basetexture  call at once..
it looks about 50 ~ 60 ..

is there any way to check if loading failed?

**Comment by englercj** [comment]
When you say "load" what do you mean? Like using the loader to download the images?

The loader will emit an 'error' even if an image fails to load. Loading a bunch at a single time shouldn't be a problem as the loader and the browser will deal with concurrency issues.

**Comment by themoonrat** [comment]
@SeminYun - Is this still an issue, and if so could you produce an example please? Thanks

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
