### ISSUE TITLE
Incorrect align display in BitmapText with set maxWidth

### ISSUE THREAD

**Issue by Ayoul** [pixijs/pixi.js#2759]
The alignments work with "\n", but not when strictly using the maxWidth property.

In the updateText function in this check here:

        if (lastSpace !== -1 && this.maxWidth > 0 && pos.x * scale > this.maxWidth)
        {
            core.utils.removeItems(chars, lastSpace, i - lastSpace);
            i = lastSpace;
            lastSpace = -1;

            lineWidths.push(lastLineWidth);
            maxLineWidth = Math.max(maxLineWidth, lastLineWidth);
            line++;

            pos.x = 0;
            pos.y += data.lineHeight;
            prevCharCode = null;
            continue;
        }

It removes the characters since the last space, but doesn't push the new width of that line. The following lines are all misaligned since they are aligned with a larger width than the previous line actually is.

I found that if I saved the width of the line since the last space and pushed that instead of "lastLineWidth", it worked like a charm. Something like this:

    BitmapText.prototype.updateText = function ()
    {

    var data = BitmapText.fonts[this._font.name];
    var pos = new core.Point();
    var prevCharCode = null;
    var chars = [];
    var lastLineWidth = 0;
    var maxLineWidth = 0;
    var lineWidths = [];
    var line = 0;
    var scale = this._font.size / data.size;
    var lastSpace = -1;
    var lastSpaceWidth = 0;
    var maxLineHeight = 0;`

    for (var i = 0; i < this.text.length; i++)
    {
        var charCode = this.text.charCodeAt(i);
        
        if(/(\s)/.test(this.text.charAt(i))){
            lastSpace = i;
            lastSpaceWidth = lastLineWidth;
        }

        if (/(?:\r\n|\r|\n)/.test(this.text.charAt(i)))
        {
            lineWidths.push(lastLineWidth);
            maxLineWidth = Math.max(maxLineWidth, lastLineWidth);
            line++;

            pos.x = 0;
            pos.y += data.lineHeight;
            prevCharCode = null;
            continue;
        }

        if (lastSpace !== -1 && this.maxWidth > 0 && pos.x * scale > this.maxWidth)
        {
            core.utils.removeItems(chars, lastSpace, i - lastSpace);
            i = lastSpace;
            lastSpace = -1;

            lineWidths.push(lastSpaceWidth);
            maxLineWidth = Math.max(maxLineWidth, lastSpaceWidth);
            line++;

            pos.x = 0;
            pos.y += data.lineHeight;
            prevCharCode = null;
            continue;
        }

**Comment by GoodBoyDigital** [comment]
great catch @Ayoul , would you mind submitting your solution as a PR? 👍

**Comment by Ayoul** [comment]
Done! Here: https://github.com/pixijs/pixi.js/pull/2780

Tell me if anything.

**Comment by GoodBoyDigital** [comment]
Fixed!
