### ISSUE TITLE
renderer.resize while sprite is partially out of view causes black bars to form

### ISSUE THREAD

**Issue by tebruno99** [pixijs/pixi.js#2761]
http://tebruno99.gitlab.io/pixibugs/resize/

Drag the blue sprite so that it is at the bottom and only partially viewable. Resize the window.  Black bar appears under the area of the sprite that should be off screen and out of view.  If you move sprite back to center and resize the bar vanishes.

I followed several guides for resizing and have tried a number of different ways. Source can be viewed at the url if you wish to reproduce.

![screen shot 2016-08-03 at 5 03 25 pm](https://cloud.githubusercontent.com/assets/24335/17383637/97ffb20a-599c-11e6-92be-52cb1136f56b.png)

**Comment by tebruno99** [comment]
Move sprite to bottom, resize window (see black bar), move sprite back to center, resize,  no black bar.

![screen shot 2016-08-03 at 5 07 47 pm](https://cloud.githubusercontent.com/assets/24335/17383679/da014042-599c-11e6-97c6-2a01cf170a71.png)

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by GoodBoyDigital** [comment]
scratch that! there is an example right there!

**Comment by GoodBoyDigital** [comment]
```
mainStage.height = newHeight;
mainStage.width = newWidth;
```

The above lines will aim to fit all elements, not just the background. I would not do that if possible. The best thing todo is set the scale of the stage.

```
mainStage.scale.set(baseR);
```

might work a bit better!

**Comment by tebruno99** [comment]
ok, I feel it is a bit confusing for a graphic renderer like pixi to ignore the size that it is given and try to compress or expand to fit all elements. The more common behavior is to clip if they don't fit and let the user/developer decide if it needs to be fixed.

**Comment by GoodBoyDigital** [comment]
I know what ya mean! This is natural behaviour for all containers (which
stage is) when you use width and height properties. Resizing the renderer
using CSS might be a better solution here?

**Comment by ivanpopelyshev** [comment]
Yep, not a bug
