### ISSUE TITLE
CanvasRenderer <> RenderTexture resolution issue

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#2762]
I create a CanvasRenderer with a resolution of 2. Then I create a RenderTexture, without resolution value set. After I render the RenderTexture, the resolution of the CanvasRenderer is set to 1 and will never be set back.

This happens in /src/core/renderers/canvas/CanvasRenderer.js on line 136. The resolution should be set back to the rootResolution.

[https://jsfiddle.net/edjx1mLw/](https://jsfiddle.net/edjx1mLw/)

**Comment by GoodBoyDigital** [comment]
Thanks for sharing @rkrasky , fancy putting a PR together? 👍

**Comment by themoonrat** [comment]
I'm not seeing the 'never be set back' - When I change that fiddle to use console logs, and log the state during rAF, you see that the resolution is reset the next time the canvas is rendered: https://jsfiddle.net/6fjtc2h4/1/
