### ISSUE TITLE
Destroying Movieclip not working properly?

### ISSUE THREAD

**Issue by mrjor** [pixijs/pixi.js#2765]
HI I am creating an instance with new PIXI.extras.MovieClip.fromFrames(frameTextures);
And after i am done with the animation I am destroying the Movieclip with instance.destroy(true, true); to remove the texture and basetexture. 

But in renderer._managedTextures the textures are not destroyed and keep adding up. 

Right now i am destroying the _managedTextures with renderer.destroyTexture(renderer._managedTextures[i]);

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by englercj** [comment]
Closing this since it should be fixed in v4.
