### ISSUE TITLE
Graphics and 2 WebGLRenderers

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2767]
https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/webgl/GraphicsRenderer.js#L84

This part of code assumes that we have only one webgl renderer. We need to switch "dirty" to versions, and update current version of webglGraphicsData.

**Comment by GoodBoyDigital** [comment]
we do! good catch

**Comment by ivanpopelyshev** [comment]
Issue found at "tankwars.io" project. We thought its a mask problem, but it turns that it isnt: http://imgur.com/a/wOvYC

**Comment by ivanpopelyshev** [comment]
Same in Mesh (dirty, indexDirty)

**Comment by GoodBoyDigital** [comment]
fixed! 👍
