### ISSUE TITLE
[3.0.11] a little confusion here with the version

### ISSUE THREAD

**Issue by faried** [pixijs/pixi.js#2768]
If I download either the released zip or js file for 3.0.11, I get a file that claims to be 3.0.10, but has changes against 3.0.10's pixi.js.  If I run `gulp build` inside the unpacked 3.0.11 zip, I get a somewhat different pixi.js file in the bin directory, which also claims to be 3.0.11.

I'm trying to package 3.0.11 for [cljsjs/packages](https://github.comc/ljsjs/packages).  I don't think I can run commands like `npm install gulp` in the boot script that prepares the code for use in ClojureScript.  What should I do?

**Comment by GoodBoyDigital** [comment]
Hi there! This should be sorted now we have pushed to the master branch 👍
