### ISSUE TITLE
Graphics and masks don't work correctly

### ISSUE THREAD

**Issue by davidtme** [pixijs/pixi.js#2770]
I'm trying to make a mask using a Graphics > drawRect and setting colour to 0x555555 but it always displays as if the colour hasn't been set so a full alpha

I'm using http://www.gamebzh.net/htmlgame/pixi-e/index.html?s=demos&f=alpha-mask.js&title=Alpha%20Mask as a test changed out the mask object

```
var mask = new PIXI.Graphics()
mask.beginFill(0x555555)
mask.drawRect(0, 0, 100, 100)
mask.endFill()

cells.mask = mask;
```

Outputs the following

![image](https://cloud.githubusercontent.com/assets/1804141/17442801/88ab237c-5b2f-11e6-8b26-8b9ec8d0d1da.png)

Add the following line fixes it
```
var mask = new PIXI.Sprite(mask.generateTexture());
```

![image](https://cloud.githubusercontent.com/assets/1804141/17443059/7ff778a6-5b30-11e6-9594-f917bf96ddb8.png)

But in my game I'm going to dynamically creating these masks so I don't want to do that.

**Comment by ivanpopelyshev** [comment]
Try it here: http://pixijs.github.io/examples/index.html?s=demos&f=alpha-mask.js&title=Alpha+Mask&v=v4.0.0-rc3

**Comment by davidtme** [comment]
I've tried it with v4.0.0-rc3 on the website and in my own code and the same problem.

**Comment by GoodBoyDigital** [comment]
Hi there, this is intended behaviour.

Graphics masking uses the stencil buffer to mask elements. This is very performant but means that masks are binary.

The Sprite masking uses true alpha masking by way of using a shader and is allows users to have varying alpha in the mask. The down side is that performance is not as great.

My recommendation would be do create a renderTexture and draw you updating graphcis to it each frame. You can then create a sprite that uses the renderTexture and use that sprite as a mask.

Hope that helps!

Cheers
