### ISSUE TITLE
PIXI.spine.Spine and alpha

### ISSUE THREAD

**Issue by davidtme** [pixijs/pixi.js#2771]
I would like to use the PIXI.spine.Spine but I've hit a bit of a problem as I want to be able to set an alpha.

Adding `spineBoy.alpha = .5` to http://pixijs.github.io/examples/index.html?s=spine&f=spineboy.js&title=Walking+Animation&plugins=pixi-spine&v=v4.0.0-rc3 illustrates the problem

![image](https://cloud.githubusercontent.com/assets/1804141/17447662/a876236a-5b47-11e6-976b-d10c1522bac5.png)

This also happens setting an alpha to PIXI.Container that that have child sprites

**Comment by ivanpopelyshev** [comment]
PIXI doesn't have layers.

I tried following: 

```js
  stage.alpha = 0.5;
  stage.filters = [new PIXI.filters.VoidFilter()];
```

and that did not affect it.

@GoodBoyDigital do we have any way of doing layers in runtime, not like cacheAsBitmap or separated renderTexture?

**Comment by GoodBoyDigital** [comment]
```
stage.alpha = 0.5;
spine.filters = [new PIXI.filters.VoidFilter()];
```

that should sort it!

**Comment by davidtme** [comment]
Just tried added the VoidFilter and I'm still getting the overlapping arears

**Comment by GoodBoyDigital** [comment]
You have to set the alpha of the spine to be 1. Does that help?

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital No, it does not. That's very old problem: we need to apply alpha after filters somehow. container children must have worldAlpha = 1

**Comment by GoodBoyDigital** [comment]
good point! how about setting the alpha to 2 as a hack fix?

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital that fixes post-filter problem. pre-filter alpha=0.5 doesn't work anyway :)

**Comment by englercj** [comment]
Where are we at on this one fellas?

**Comment by ivanpopelyshev** [comment]
@englercj its still not implemented. The thing is, "worldAlpha" parameter inside of filtered container must become 1, while "alpha" itself must be applied to after the filter.

**Comment by rich-earth** [comment]
hey I'm just using this filter for now:

```mySpine.filters = [new AlphaFilter(0.5, 0.1)]``` 

```
export default class AlphaFilter extends PIXI.Filter {
  constructor(alpha){

    let fragmentShader = [
      'precision mediump float;',
      '',
      'varying vec2 vTextureCoord;',
      'uniform sampler2D uSampler;',
      '',
      'void main(void)',
      '{',
      '      gl_FragColor = texture2D(uSampler, vTextureCoord);',
      '      gl_FragColor.r *= '+alpha+';',
      '      gl_FragColor.g *= '+alpha+';',
      '      gl_FragColor.b *= '+alpha+';',
      '      gl_FragColor.a *= '+alpha+';',
      '}'
    ].join('\n');

    super(null, fragmentShader, null);
  }
}
```

**Comment by luozan** [comment]
I have same problem in v3. Children are transparent  to parent when I set alpha of parent to 1.

**Comment by jmlee2k** [comment]
I have the same issue.  I'm using a version of the filter @rich-earth posted (thanks!), with a uniform to allow us to fade the Spine object in and out.  This works great on most devices, but results in really bad performance on some low-end ones (even without animating the uniform).  Is there any way to accomplish the same thing (even using a hack) by just using alpha?

**Comment by ivanpopelyshev** [comment]
no, you need extra framebuffer for that, and i believe low-end devices have very big penalty on it.

**Comment by jmlee2k** [comment]
Ok, thanks.  I know it's a bit off topic, but do you know of any way to query the GPU capabilities so we can selectively enable/disable the effect?  It seems that in JS, querying anything about the system is kind of off-limits (understandably) as it can be used to fingerprint users.

**Comment by ivanpopelyshev** [comment]
If its an actual game, better to delegate it to user, HIGH and LOW modes, something like that :)

**Comment by jmlee2k** [comment]
Yeah, I guess that's the most straightforward solution, thanks!

**Comment by rich-earth** [comment]
Don't know if this helps but I've been checking Web GL performance to decide whether to choose 2x or 1x resolution for games.  I don't know if any problems with this but works ok for me - maxVertexUniformVectors is low on older devices I tested...

```js
function checkCanHandleWebGl2x() {

  if (window.WebGLRenderingContext) {
    //create temp canvas to test
    let canvas = document.createElement('canvas');
    document.body.appendChild(canvas);
    let gl;
    let possibleNames = ['webgl', 'webgl2', 'experimental-webgl2', 'experimental-webgl'];
    for (let i = 0; i < possibleNames.length; i++) {
      gl = canvas.getContext(possibleNames[i]);
      if (gl) {
        break;
      }
    }
    //web gl context found
    if (gl) {

      let maxVertexUniformVectors = gl.getParameter(gl.MAX_VERTEX_UNIFORM_VECTORS);
      let maxTextureSize = gl.getParameter(gl.MAX_TEXTURE_SIZE);

      document.body.removeChild(canvas);

      if (maxVertexUniformVectors < 1024 || maxTextureSize < 4096) {
        console.log("WebGL performance not good enough for 2x res");
        return false;
      } else {
        return true;
      }
    } else {
      console.log("WebGL context not found");
      return false;
    }

  } else {
    console.log("WebGL not supported");
    return false;
  }
}
```

**Comment by jmlee2k** [comment]
Great, thanks!  I didn't even think that getParameter would be available in WebGL.  It brings me back to my early days of tearing my hair out trying to draw a gradient triangle in C++. :)

**Comment by ivanpopelyshev** [comment]
Yeah, that's good idea,

```js
var gl = renderer.gl;
gl.getParameter(gl.MAX_VERTEX_UNIFORM_VECTORS);
```
