### ISSUE TITLE
OSX Firefox is probably not WebGL safe

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2772]
I have UI elements on top of the page, as most of you probably have, on login/signup, I have a div that covers the entire page, has a background: rgba(0,0,0,0.5)

Firefox goes crazy with this overlay, the rgba(0,0,0,0.5) is mis-rendered and when you remove the overlay, the entire canvas goes dark (This is one issue, I don't know whether there's any more)

Forcing "CanvasRenderer" fixes the issue, I've tried other OS'es, other browsers, seem to be OSX Firefox only

I'm personally not doing anything about it, if Firefox has issues, it might nudge people to use Chrome, but maybe if the issue is recognized, PIXI might select CanvasRenderer automatically for OSX Firefox

**Comment by porglezomp** [comment]
I haven't had any Firefox bugs while I've been using it, what's the DOM structure that you're dealing with that's causing this problem? Something like this?
```html
<div>
    <div><!-- translucent overlay, absolute, etc. --></div>
    <canvas></canvas>
</div>
```

**Comment by kaansoral** [comment]
Something like this:
```
#pagewrapper{
	z-index:200;
	position: fixed;
	top: 0px;
	left: 0px;
	right: 0px;
	bottom: 0px;
	vertical-align:middle;
	text-align: center;
	background: rgba(0,0,0,0.5);
}
<div id="pagewrapper"></div>
```

Reproduces the issue easily on OSX/Firefox

**Comment by porglezomp** [comment]
That renders perfectly on my current app, so it must be some more specific Pixi feature that doesn't work.

**Comment by kaansoral** [comment]
Very interesting, is your app live?

I might manually insert the div and test your app, to see whether it's an issue specific to my machine

I have a barebone pixi testing code, before sharing the CSS I tested/reproduced the issue with that

Normally the background is 0.5 opacity ~gray, on Firefox it renders 0.5 opacity pale white, when you remove remove the wrapper, the canvas either become fully white or fully black

**Comment by porglezomp** [comment]
It's not, it might be in a state where I can share it in a few days, but for now I've just torn off a bunch of pieces.

**Comment by GoodBoyDigital** [comment]
if your try running with this line added (before creating the renderer)

```PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;```

Does that help?

Thanks!

**Comment by izar89** [comment]
I also use an overlay on my website (still local) and the following test(https://jsfiddle.net/izar/zzz5dL6p/) also works fine on my setup (Osx + firefox 48.01)

**Comment by GoodBoyDigital** [comment]
hey all! Going to close this for now as it seems like this is in the hands of the mighty firefoxs..
