### ISSUE TITLE
SystemRenderer backgroundColor property strange code

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2776]
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/SystemRenderer.js#L185

In constructor:

```js
this.backgroundColor = options.backgroundColor || this._backgroundColor;
```

In prototype:

```js
Object.defineProperties(SystemRenderer.prototype, {
    backgroundColor:
    {
        ...
    }
});
```

**Comment by englercj** [comment]
It calls the setter so the string and numeric versions are in-sync.

**Comment by GoodBoyDigital** [comment]
makes sense! Thanks for clarifying @englercj 👍
