### ISSUE TITLE
New Spine runtime

### ISSUE THREAD

**Issue by badlogic** [pixijs/pixi.js#2785]
Hi folks,

Mario from Esoteric Software here. I've just completed the first iteration of our new Spine runtime for JavaScript/TypeScript. It's a complete rewrite of the old JavaScript runtime in TypeScript to make it more maintainable. Obviously TypeScript is not required to use the runtime, but it is required to make changes to it.

The development branch for the new runtime is here https://github.com/EsotericSoftware/spine-runtimes/tree/spine-ts/spine-ts We currently have a single backend based on WebGL. There's also a sample here: https://github.com/EsotericSoftware/spine-runtimes/tree/spine-ts/spine-ts/webgl/example

It should be mostly trivial to replace the current Spine runtime you use with this one. Let me know if I can be of assistance.

Keep up the good work,
Mario

**Comment by GoodBoyDigital** [comment]
Nice! Thanks for sharing! cc @ivanpopelyshev what do ya think?

**Comment by ivanpopelyshev** [comment]
Hello, Mario! Thank you for sharing, these are good news for us! I'll update it ASAP.

Current pixi-spine implementation has deep integration in PIXI: it uses its Texture class and some of Transforms features. 

Our textures can be rotated in different directions, or flipped. I remind you that texturePacker atlas rotations have different directions than spine one :) Our runtime works fine with custom texture packers.

One of our killer features are that we can change texture for any attachment just in one method call. It takes care of trim/crop and other things.

Also I remind you that Meshes still dont work with trim/crop, but we understand that it requires advanced shader for it. We will be happy to see polygon packing feature, I hope that its in your roadmap.

Your webgl implementation is certainly good, but it still lacks GPU acceleration for FFD animations. Support for accelerated FFD is experimental for PIXI but soon I'll merge it.

One more thing - I'm preparing my own Native solution for PIXI, that is based on libgdx, but at the same time it has all awesome javascript dynamic structures. I hope in a few months we will compare speed of your main runtime and my hacky one on mobile devices :)

**Comment by badlogic** [comment]
Hi!

Yeah, I figured you folks have specialized things all up. Didn't mean to
suggest you take all the trivial code from our new WebGL backend. But I
think you can benefit from the typed core classes, makes operations on the
open heart a lot easier :)

Cheers!

**Comment by ivanpopelyshev** [comment]
@badlogic hey. Just found you in Kotlin slack :) Im making https://github.com/pixijs/pixi-native/ so I know who to ask if there'll be problems ^_^

**Comment by englercj** [comment]
Closing this so it can be tracked instead in pixijs/pixi-spine #121.
