### ISSUE TITLE
GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#2786]
Not sure if this an issue with VoidFilter or PixiPicture, but when I run the example: 

https://pixijs.github.io/examples/index.html?s=picture&f=overlay.js&title=Overlay&plugins=pixi-picture&v=

I get the following error in both Chrome and Safari

GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format.

Removing the stage.filters the problem goes away, but I'm guessing that the VoidFilter speed up isn't working in either case.

Any thoughts ?

**Comment by ivanpopelyshev** [comment]
It works for me. Mac or windows?

**Comment by weepy** [comment]
Mac

**Comment by weepy** [comment]
It does "work" for me in that I can see the sprites with overlay. But it seems to throw that error every frame.

**Comment by ivanpopelyshev** [comment]
Some strange webgl problem. Lets look at it:

```js
    if (renderer.renderingToScreen && renderTarget.root) {
        var buf = this._getBuf(pixelsWidth * pixelsHeight * 4);
        gl.readPixels(x_1, y_1, pixelsWidth, pixelsHeight, gl.RGBA, gl.UNSIGNED_BYTE, this._bigBuf);
        //REVERT Y?
        gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, pixelsWidth, pixelsHeight, gl.RGBA, gl.UNSIGNED_BYTE, this._bigBuf);
    } else {
        gl.copyTexSubImage2D(gl.TEXTURE_2D, 0, 0, 0, x_1, y_1, pixelsWidth, pixelsHeight);
    }
```

@GoodBoyDigital what can it be? May be we have not-premultiplied alpha in main renderer and premultiplied in RenderTexture?

**Comment by weepy** [comment]
any thoughts guys @GoodBoyDigital @ivanpopelyshev ?

**Comment by weepy** [comment]
@ivanpopelyshev : can I clarify whether this is "wontfix" or just "low priority". I can't release my app in its current state because I'm dependant on this.

**Comment by englercj** [comment]
Can you retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
