### ISSUE TITLE
Bad antialiasing when using mask

### ISSUE THREAD

**Issue by louisatome** [pixijs/pixi.js#2792]
The antialiasing doesn't work if a sprite contains a mask.

Fiddle : http://jsfiddle.net/gkkgp5bt/2/

**Comment by GoodBoyDigital** [comment]
this is a limitation of WebGL i'm afraid, sprite masking requires the scene be rendered to a framebuffer. FrameBuffers do not support antialiasing :/ In WebGL2 they will though, so the problem wont last forever :)

Solutions:
1: Use a Graphics mask (no generateTexture) This is faster too!
2: Apply the FXAA filter to your scene, this will antialias for you via a shader. Should look nicer, but means pixi needs to do a little more work.

Hope that helps!

**Comment by louisatome** [comment]
Thank you for the quick answer!

The first solution isn't acceptable in my context because i need a mask with transparency level and i think it's not possible with graphics' mask, is it?
I've alredy tried the second solution but the FXAA filter seems to poorly render the text elements.

**Comment by GoodBoyDigital** [comment]
If you set the alpha off the container you are masking - does that achieve
the same effect?

Final resort,  you could also try increasing the resolution of your app too!
