### ISSUE TITLE
roundPixels has no effect on PIXI.Graphics

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#2793]
Code: https://jsfiddle.net/tLzf8znk/1/

Documentation states for roundPixels: "If true Pixi will Math.floor() x/y values when rendering, stopping pixel interpolation.", yet id does not apply to Graphics. 

So, when Graphics and sprites used together, this creates kind of chaos - Sprites are Math.floored, graphics not :(

**Comment by ivanpopelyshev** [comment]
Make a PR? :)

**Comment by trsh** [comment]
roundPixels should be assigned to all or none. Otherwise it's not cool :P

**Comment by trsh** [comment]
I use this of non game project, and it helps a lot to have crisp result on screen, and still it keeps scientific precise coordinates in object. It's kind of really cool.

**Comment by GoodBoyDigital** [comment]
totally agree!  Good catch @trsh 👍  fancy putting a PR together, that would be super helpful as we are quite busy at the moment finalising the v4 release candidate. Cheers!

**Comment by ivanpopelyshev** [comment]
We are rendering lines as polygons. There are many cases in which roundPixels will go wrong.

**Comment by trsh** [comment]
It will.

**Comment by GoodBoyDigital** [comment]
nice :)

**Comment by GoodBoyDigital** [comment]
Guys - should I be rounding the vertex data of the shape, the matrix position of the shape or both?

**Comment by ivanpopelyshev** [comment]
enlarge individual convex shapes from inside?

**Comment by trsh** [comment]
I will not make PR for this. I have checked the code and it's to complicated for me for now, and time is also not on my side :/

**Comment by trsh** [comment]
For the time being I switched to Sprite with inside generated graphics.

**Comment by staff0rd** [comment]
FYI that fiddle is broken now due to a broken link on the jpg

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
