### ISSUE TITLE
WebGL: Graphics moving independently from Sprites on Mobile. 

### ISSUE THREAD

**Issue by XerxesNoble** [pixijs/pixi.js#2794]
Ive noticed that when running WebGL renderer on mobile (Specifically, in my case, iOS). When I move the position of a container that has a set of Graphics and Sprites in it, the sprites move perfectly, however the Graphics tend to need about 5-10 pixels of movement in order to rerender. 

I'm working in the latest dev branch

[I've recorded a video example here][video]

![Example Gif][gif]

I'm wondering if this is an effect of some optimization in the GL GraphicsRenderer. I've run the same code while forcing CanvasRenderer and it runs just fine (all Sprites & Graphics move together). I'm potentially thinking that it has something to do with the `maximumSimplePolySize`? 

I'm still doing some digging, but I was wondering if the PIXI team had any thoughts on why this would happen?

[video]:https://dl.dropboxusercontent.com/u/26451390/sprites_vs_graphics.mov "Video: "
[gif]:https://i.imgflip.com/18s4bu.gif "Gif: "

**Comment by GoodBoyDigital** [comment]
Hello! That is a strange one! are ya running in v4?

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital there was a merged pull request with _localID thing, may be thats it?

**Comment by XerxesNoble** [comment]
@GoodBoyDigital Yeah, I've been trying to keep up to date with the dev branch incase there is a fix. Running the latest dev branch, still seeing the issue.

**Comment by GoodBoyDigital** [comment]
Good stuff, Unfortunatly  I cant say can recreate the issue myself :/ I guess what we really need is an isolated fiddle of the issue to debug and solve your issue. If you can provide one we will take a look and get it nailed. Thanks!

**Comment by XerxesNoble** [comment]
Brilliant, I'll whip one up tonight. Thanks @GoodBoyDigital

**Comment by ivanpopelyshev** [comment]
You are changing its position, nothing else, right?

**Comment by XerxesNoble** [comment]
@ivanpopelyshev Just using: `container.position.set(x, y)`  The container can also be scaled and rotated. But in the example the only property changing is the x/y.

**Comment by ivanpopelyshev** [comment]
put that before you create the stage:

```js
PIXI.TRANSFORM_MODE.DEFAULT = PIXI.TRANSFORM_MODE.DYNAMIC;
```

**Comment by XerxesNoble** [comment]
Hey @GoodBoyDigital, I whipped up an [isolated example](http://codepen.io/xerxesnoble/pen/vKvBbW?editors=0010)

I tested it on Android & iOS and you can clearly see the lag between the shapes and the text. 

@ivanpopelyshev .. I tried to add `PIXI.TRANSFORM_MODE.DEFAULT = PIXI.TRANSFORM_MODE.DYNAMIC;` before creating the stage but it doesn't seem to make any difference.

**Comment by ivanpopelyshev** [comment]
@XerxesNoble 

offtop: use "pivot" for camera. Think that you're pinning container "pivot" point to screen's "position". Whatever is located in the "pivot" of container will be shown in "position" of the screen. That way you can use actual coordinates and not inverted ones. Also that helps with scaling: make position=center of screen, and pivot will be the point on map which will be shown in that center. Scale will zoom in and zoom out :)

**Comment by ivanpopelyshev** [comment]
Yeah, your coordinates are ~3000 , and may be some of our calculations are made with bad precision. @GoodBoyDigital What do you think?

**Comment by ivanpopelyshev** [comment]
@XerxesNoble try this one: http://codepen.io/anon/pen/VjgYpg . I subtracted 2500 from all shape coords and added 2500 to graphics position. If it works better, that's precision problem.

**Comment by ivanpopelyshev** [comment]
Also, try add this one before renderer creation: PIXI.PRECISION.DEFAULT = PIXI.PRECISION.HIGH;

**Comment by XerxesNoble** [comment]
@ivanpopelyshev Reducing the coords seems to help a bit. However, you can still see the shakiness. I could see how you think its a precision issue as the staggering is not really constant nor does it have any pattern to it. 

Using: 
```
PIXI.PRECISION.DEFAULT = PIXI.PRECISION.HIGH;
```

Seems to allow me to leave the coordinates where they are and have the same level of staggering as if the coordinates were 2500 less.

**Comment by ivanpopelyshev** [comment]
@XerxesNoble OK, so first thing we have to do is: for every shape, compute its center weighted point, or may be left-top. Take it as a position, and the rest leave in "shape.points". It is required for your case. If that is not enough, specify high precision.

**Comment by XerxesNoble** [comment]
@ivanpopelyshev no sure if I understand what you're saying..

Do you mean to calculate a generalized polygon (bounding box) and the set the polygons position to the top left of that? Or do you mean to draw a polygon at a closer coordinate and then move them to the ~2600px points?

**Comment by ivanpopelyshev** [comment]
You create graphics for very shape, right? Shape has points. You can find left X and top Y of those points, and make graphics position (X,Y), subtracting those coords from shape.points before you pass it to addPolygon.

**Comment by XerxesNoble** [comment]
Okay got it. I've Implemented it here: http://codepen.io/xerxesnoble/pen/mEvJGm?editors=0010

From what I can tell, the difference between specifying high precision and repositioning the graphics seems to be nonexistent.

@ivanpopelyshev are there any specific drawbacks or negative overhead to specifying high precision over repositioning?

**Comment by ivanpopelyshev** [comment]
High precision can cause performance problems if you are drawing a lot of objects.

So, does that thing satisfy you?

**Comment by XerxesNoble** [comment]
@ivanpopelyshev Thanks for the help, yes this helps me out a great deal!
