### ISSUE TITLE
Width & height 0 when visible is set to false

### ISSUE THREAD

**Issue by Excaa** [pixijs/pixi.js#2795]
After setting visible to false and reading width & height the values are 0 if visible is set to false.

Simple code to reproduce:
```js
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x3030aa, transparent: false}, false);
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();
var sprite1 = new  PIXI.Graphics();
sprite1.beginFill(0x0, 1);
sprite1.drawRect(0,0,40,40);
sprite1.endFill();
stage.addChild(sprite1);
console.log("before: " + sprite1.width);
sprite1.visible = false;
console.log("after vis false: " +sprite1.width);
```

**Comment by Excaa** [comment]
After checking the code a bit more it looks like this is intentional and not a bug after all. Could the transforms work so that instead of resetting the values to 0 object would keep the result from previous transformupdate?

**Comment by ivanpopelyshev** [comment]
width and height calls getLocalBounds, which is implemented differently for Graphics and Sprite. Somewhere inside there is "visible" thing. There are 100 ways of implementing it. 

It was VERY difficult task to refactor it for pixi-v4: I made 4 iterations of new BoundsBuilder object, @GoodBoyDigital made its own official PR on top of that, and covered it with tests. Any change in this algorithm may cause damage for some cases, like cacheAsBitmap.

I don't say that your suggestion is bad, but I warn you: prepare for big headache, that thing already ate a lot of time and it will do it again.

You are free to implement your own algorithms in your own forks like i did it with https://github.com/gameofbombs/pixi.js , its bounds implementation is completely different and tuned for my projects.

**Comment by GoodBoyDigital** [comment]
hello! @Excaa you are correct. For Pixi an object that is not visible has dimensions of 0. As @ivanpopelyshev points out there are lots of way this could have been done, we settled on bounds being visually based, hence 0 dimensions. 

You could always set the object to true, get the bounds and then set it back to false :)

Hope that helps!
