### ISSUE TITLE
Add an enabled property to filters

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#2797]
Some filters can be skipped under certain conditions. Eg a blur with 0 strength. Lets add that!

**Comment by bigtimebuddy** [comment]
Will be useful to manage the display of filters without having to constantly be setting the `filters` property on the display object.

**Example** 

```js
var twist = new PIXI.filters.TwistFilter();
var dot = new PIXI.filters.DotFilter();
sprite.filters = [twist, dot];

twist.enabled = false; // will ignore the twist filter
```
