### ISSUE TITLE
Cannot read property 'transform' of null on MovieClip

### ISSUE THREAD

**Issue by dan335** [pixijs/pixi.js#2800]
I'm using the latest 4.  If I call obj.position.y on a MovieClip I get.

```
Cannot read property 'position' of null
```

If I call getBounds I get 

```
Cannot read property 'updateTransform' of null
```

If I do console.log on the MoveClip then transform is null. Is this a bug or am I doing something wrong?

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by dan335** [comment]
I tried making one but it has a transform.  https://jsfiddle.net/0guok9de/  Not sure why mine doesn't.

**Comment by GoodBoyDigital** [comment]
Random Guess, are you using the 'new' keyword?

**Comment by dan335** [comment]
Here's how I'm using it.

```
export class MapFlagBuilding extends MyMovieClip {
    constructor() {}
}

export class MapFlagCity extends MapFlagBuilding {
    constructor() {}
}

this.flag = new MapFlagCity();
```

Would the new keyword break the transform?

**Comment by GoodBoyDigital** [comment]
Its more of a case that not using it usually creates the issues

**Comment by dan335** [comment]
Ah, I'll check but I think I'm using it.

**Comment by dan335** [comment]
I'm setting the position when it's created and it works.  Somehow it gets set to null though.  I'll keep digging, thanks.

**Comment by dan335** [comment]
This is when it happens.  When the flag color changes I call this function.  Before calling it it has a transform.  Afterwards it's null.

```
drawFlag() {
    if (this.flag) {
      this.flag.destroy();
    }

    this.flag = new MapFlagCity(this.canvas, this._id, this.coord, this);
}
```

**Comment by dan335** [comment]
I got it working.  I needed to call removeChild on the parent container before calling destroy.  Not sure if it's a bug or not?

**Comment by ivanpopelyshev** [comment]
Not a bug, just badly documented API ;) Yes, you should call removechild on parent before destroy.

**Comment by GoodBoyDigital** [comment]
Good shout, one of you chaps fancy making a PR to the docs to save others
from going through the same issue?

**Comment by dan335** [comment]
Should it be on MovieClip.destroy, Sprite.destroy, Container.destroy or DisplayObject.destroy or all of the above?

**Comment by GoodBoyDigital** [comment]
All of the above would work well - as a thought,
As an alternative solution - do you guys think we should remove the object
automatically when destroy is called?

**Comment by dan335** [comment]
Can't think of when you'd not want to remove it so yes.

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital I agree with @dan335, can't think of a case where you'd want to destroy but not remove.

**Comment by GoodBoyDigital** [comment]
Nice! @dan335 if you could knock up a PR that would be ace 👍
