### ISSUE TITLE
nw.js and browserify problem

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2804]
Something wrong happened in pull request #2769 , commit 4d03034cadb4185c92ce2cab4537a48f62768b7d.

nw.js, both new version and the one that is used in rpgmaker MV are failing. I even removed "loader" module so right now the only pixi dependency is eventemitter.

What i see in the console is "PIXI is not defined". Sometimes it crashes, sometimes i can see that "global.PIXI" is set while "window.PIXI" lacks.

How to reproduce: download latest nw.js binaries, put these files in the same directory, launch it.

"pixi.js" is good version, just before 2769 was merged. 
"pixi_fail.js" is one of latest versions, stripped of PIXI.loader so we can pinpoint the problem better.

[nwjs.zip](https://github.com/pixijs/pixi.js/files/417293/nwjs.zip)

By the way, if someone needs good version that works with nw.js - just take it from the archive.

**Comment by GoodBoyDigital** [comment]
could it be this line in the package? 

"main": "./src/index.js", ?

Bit of a guess :)

cc @bigtimebuddy..

**Comment by bigtimebuddy** [comment]
I'll look into this and get back to you. Thanks for the example @ivanpopelyshev

**Comment by bigtimebuddy** [comment]
I think I trace down the problem, just not the solution. When `global.PIXI = core;` is changed to `window.PIXI = core;` in **src/index.js**, works fine. I'm not sure why the browserify implementation is not subbing `window` for `global`.

**Comment by GoodBoyDigital** [comment]
fixed!
