### ISSUE TITLE
Wrong getBounds() on trimmed Sprites inside a Container 

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#2806]
Two sprites are in [this atlas](https://rawgit.com/staff0rd/pixi-tilesprite/c9427eab8d104bed1a06d543bb5798704dd01666/spritesheet-2.json).  The first, 50x50, the second, 100x50 including 25px transparency right and left.

Placing these sprites inside containers results in correct render layout, however inspecting the width of the containers **incorrectly reports the width of the second sprite as 50px rather than 100px**.

![image](https://cloud.githubusercontent.com/assets/6289998/17658372/a7a4aea6-630e-11e6-9161-883cc50ffe7b.png)

https://jsfiddle.net/staff0rd/5h2ybm92/

@ivanpopelyshev, this is possibly from your bounds update, as I didn't see this issue prior, however it doesn't look like [this code](https://github.com/pixijs/pixi.js/blob/0abd932991470dcc8348ef895a58537dbd6f853b/src/core/sprites/Sprite.js#L232-L241) has changed.  I'm not certain whether it's that code, or somewhere else, that causes this issue.

**Comment by ivanpopelyshev** [comment]
That's strange.

Bounds are calculated in next method: https://github.com/pixijs/pixi.js/blob/0abd932991470dcc8348ef895a58537dbd6f853b/src/core/sprites/Sprite.js#L271

**Comment by ivanpopelyshev** [comment]
Yes, it is a bug. We need to call "calculateBoundsVertices" , and then pass vertexData[8,9,..] to calcBounds. 

@GoodBoyDigital that's the part of my PR that you changed. Please look at it and decide what to do with it.

**Comment by whizzkid** [comment]
as a sidenote, I see in the comment there that we need to be compatible with pixiv3..... why?   this is v4 :)

**Comment by ivanpopelyshev** [comment]
Exactly because people are complaining that width must be 100px and not 50px :)

**Comment by ivanpopelyshev** [comment]
That's build: https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds666/pixi.js

**Comment by GoodBoyDigital** [comment]
Gonna throw this out there... @whizzkid makes an interesting point, should bounds care about trim forbounds? v4 could be different...

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital people are using it. There were other issues about that.

**Comment by staff0rd** [comment]
I agree with [this](https://github.com/pixijs/pixi.js/issues/841#issuecomment-48022136).  Under what circumstances is it beneficial to not have access to the full asset size?

**Comment by ivanpopelyshev** [comment]
@staff0rd that's why I'm all hands for it.

**Comment by GoodBoyDigital** [comment]
fair points!

**Comment by GoodBoyDigital** [comment]
Fixed 👍
