### ISSUE TITLE
WebGL: Refused to create native OpenGL context because of blacklisting. 

### ISSUE THREAD

**Issue by dan335** [pixijs/pixi.js#2814]
Out of twenty people I had two report this error.

```
"Pixi.js 4.0.0 - Canvas - http://www.pixijs.com/" 61ab9e62b65f1e7919c421855170a720f3e119f6.js:227:31293
Error: WebGL: Error during ANGLE OpenGL init. 61ab9e62b65f1e7919c421855170a720f3e119f6.js:227:31554
Error: WebGL: Refused to create native OpenGL context because of blacklisting. 61ab9e62b65f1e7919c421855170a720f3e119f6.js:227:31554
Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings) 61ab9e62b65f1e7919c421855170a720f3e119f6.js:227:31554
Error: WebGL: Error during ANGLE OpenGL init. 61ab9e62b65f1e7919c421855170a720f3e119f6.js:227:31579
Error: WebGL: Refused to create native OpenGL context because of blacklisting. 61ab9e62b65f1e7919c421855170a720f3e119f6.js:227:31579
Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings) 61ab9e62b65f1e7919c421855170a720f3e119f6.js:227:31579
```

I found this about it.  http://www.html5gamedevs.com/topic/11939-nothing-works-but-all-demos-do/  From that it sounds like it's their GPU.

I'm already using PIXI.autoDetectRenderer.  Ideally pixi.js would switch to canvas for them.

**Comment by englercj** [comment]
It did, from that log there pixi is in canvas mode:

> Pixi.js 4.0.0 - Canvas - http://www.pixijs.com/"

The error is likely from when it tried to create a WebGL context, and failed, then used canvas.

**Comment by dan335** [comment]
Didn't notice the canvas.  Guess I'll close this.  It looks very broken for them though but one said using a different browser fixed it.

**Comment by englercj** [comment]
@dan335 I would investigate if your application is broken in canvas rendering. Maybe it isn't the errors that are causing issues, but the fact that it renders in canvas.

**Comment by dan335** [comment]
Good call.  It's totally broken in canvas.
