### ISSUE TITLE
How to import Pixi into a react / node project? 

### ISSUE THREAD

**Issue by Lukeout** [pixijs/pixi.js#2815]
I developed my project in Brackets using their generated server. I am trying to now write Pixi code into a React.js app. I am using Facebook's create-react-app 

I am using ES6 import but it doesn't seem to be working. I have tired both V3 and V4. I think I am just downloading the wrong file, and it says the npm module for Pixi is outdated. 

At the  top of my file I say, import import Pixi from './pixi.js';
Which gives me a compile error

With Babel Linting I get: 

Error in ./src/pixi.js
Syntax error: C:/Users/lukeo/Code/pokemon404/src/pixi.js: Unexpected token (5:1)
  3 |
  4 |
> 5 | <!DOCTYPE html>
    |  ^
  6 | <html lang="en" class=" is-copy-enabled is-u2f-enabled">
  7 |   <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
  8 |     <meta charset='utf-8'>
 @ ./src/App.js 17:12-32

In Chrome console I get:

"App.js:17 Uncaught Error: Cannot find module "./pixi.js"webpackMissingModule @ App.js:17(anonymous function) @ App.js:17(anonymous function) @ bundle.js:2893__webpack_require__ @ bundle.js:556fn @ bundle.js:87(anonymous function) @ index.js:11(anonymous function) @ bundle.js:1318__webpack_require__ @ bundle.js:556fn @ bundle.js:87(anonymous function) @ multi_main:4(anonymous function) @ bundle.js:589__webpack_require__ @ bundle.js:556(anonymous function) @ bundle.js:579(anonymous function) @ bundle.js:582
client:22 [WDS] Hot Module Replacement enabled.
client:45 [WDS] Errors while compiling.
client:47 ./src/pixi.js

C:\Users\lukeo\Code\pokemon404\src\pixi.js
  5:2  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
errors @ client:47sock.onmessage @ client:82EventTarget.dispatchEvent @ eventtarget.js:51(anonymous function) @ main.js:274SockJS._transportMessage @ main.js:272EventEmitter.emit @ emitter.js:50WebSocketTransport.ws.onmessage @ websocket.js:35
client:47 ./src/pixi.js
Module build failed: SyntaxError: C:/Users/lukeo/Code/pokemon404/src/pixi.js: Unexpected token (5:1)
  3 | 
  4 | 
> 5 | <!DOCTYPE html>
    |  ^
  6 | <html lang="en" class=" is-copy-enabled is-u2f-enabled">
  7 |   <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
  8 |     <meta charset='utf-8'>"

I have also tried the minified version, import Pixi from 'pixi.min.js' and this works, but gives me 10000 error lines in the console saying, which I think means I will have problems later when I try to use Webpack to build the project to a production build.  

"Critical dependencies:
1:680-687 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./src/pixi.min.js 1:680-687"

**Comment by englercj** [comment]
Looks like you downloaded an HTML document instead of the js file. This happens pretty often when using the browser's Save As...

If you open the `pixi.js` file you are trying to load, it is really an html file?

**Comment by Lukeout** [comment]
Your right, what a silly mistake. I opened the raw Pixi.js file and copied it into my own js file. So now it compiles. 

This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

Is there a better way to import Pixi into node projects? 

As of now I have Pixi.js in a folder and am doing import Pixi from './Pixi.js' 

npm install Pixi will give me an old depreciated version of Pixi that I don't want.

**Comment by englercj** [comment]
> npm install Pixi will give me an old depreciated version of Pixi that I don't want.

You can npm install any version you want:

`npm install --save pixi.js@3.0.11` for example.

Unfortunately there are issues loading pixi with webpack because pixi is built with browserify, and uses a custom transform not available in webpack. I recommend just using the built file.

I'm not sure what the warnings are without seeing your project and the full log. You can see tips about using pixi with webpack by searching the wiki/issues:

https://github.com/pixijs/pixi.js/wiki/Using-Pixi.js-with-Webpack
https://github.com/pixijs/pixi.js/issues?q=is%3Aissue+webpack+is%3Aclosed

**Comment by Lukeout** [comment]
So the built file being, Pixi.min.js or Pixi.js? So you recommend me doing it the way I am now just importing a .js file from my folder. All Pixi.js files you guys have are already "pre-built" right?

**Comment by englercj** [comment]
`pixi.js` is the built output file, and `pixi.min.js` is a minified version of the built output.

**Comment by GoodBoyDigital** [comment]
seems resolved! Thanks for sorting @englercj 👍

**Comment by j-funk** [comment]
This same error happens for me using Webpack.  And though there is a workaround, it is sub-optimal and I don't think this issue should be closed.  Using ES6 imports with Webpack / NPM is a very common use case.
