### ISSUE TITLE
when do you have plan to release v4 stable?

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#2820]
hi i'm wondering v4

i'm developing by v3 and it is good. 

but i heard many issue is better than v3 , speically on mobile

so i'm very expecting..  

but porting  need much time because our not small

and it's using many middleware

so i wanna know when will v4 stable release...?

thx  a lot..

**Comment by ivanpopelyshev** [comment]
http://www.html5gamedevs.com/topic/24525-big-pixijs-news-wonder-what-is-it/

**Comment by GoodBoyDigital** [comment]
very soon :)

**Comment by GoodBoyDigital** [comment]
done!
