### ISSUE TITLE
RenderTexture is not clear in canvas base

### ISSUE THREAD

**Issue by tywang2006** [pixijs/pixi.js#2822]
Hi, 

I got trouble in this v4. in every frame, i got renderTexture updated for a sprite. but it never cleared last displayed graphic, it seems the canvas was not clear every frame.

Thanks

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by tywang2006** [comment]
update(id: number, offset: number) {
        this._id = id;
        this._iconSprite = GameAsset.icons[id];
        this._iconSprite.x = (this.symbolWidth - this._iconSprite.width) / 2;
        this._iconSprite.y = (this.symbolHeight - this._iconSprite.height) / 2 - offset;
        this._renderer.render(this._iconSprite, this._renderTexture, true);

    }

this is my code, i call this function every frame, _rendertexture is assigned to another displayed icon.

**Comment by GoodBoyDigital** [comment]
Cheers for that, if you could turn that into a fiddle that would be ace. Time is not our friend and in order to fix bugs quickly its always better to have a working example. That way a member of the pixi team can debug it and find a fix for you much quicker. Thanks!

**Comment by tywang2006** [comment]
I am afraid it is hard, it is very tiny part based on my massive framework. i can't take it out and put in fiddle because it won't work.

**Comment by GoodBoyDigital** [comment]
that will make it very tricky for us to fix if the error only occurs in your code :/

**Comment by tywang2006** [comment]
it looks like this https://github.com/pixijs/pixi.js/issues/1147

**Comment by tywang2006** [comment]
please let me know when it is fixed. thanks mate
