### ISSUE TITLE
Bug InteractionManager when accessing getLocalBounds()

### ISSUE THREAD

**Issue by endel** [pixijs/pixi.js#2823]
I've spent a couple of hours trying to figure it out what was happening.

I basically have a "viewport", and due to a call to `getLocalBounds()`, PIXI is somehow is flushing the `_boundsID` and the InteractionManager simply stops working.

Live demo of the issue: https://jsfiddle.net/endel/xc6483w4/

If you comment out the `getLocalBounds` call, everything works.

**Comment by endel** [comment]
I'm using latest v4 version by the way.

**Comment by GoodBoyDigital** [comment]
Excellent catch! And thanks for creating the fiddle. It makes it all so much easier to solve :D

**Comment by endel** [comment]
Just to be more specific: the `width` getter from `Container` will call `getLocalBounds`, so this might be an issue for mostly every PIXI application that haves a "viewport/camera" feature out there.

**Comment by ivanpopelyshev** [comment]
If user calls "updateTransform" after that, it will be fine.

**Comment by kib357** [comment]
Hey guys! Any updates on this? I'm using Container `width` prop in `mouseover` event to calculate container menu position, and getting `mouseover` event twice.

**Comment by ivanpopelyshev** [comment]
@kib357 its still the case, I made multiple tries to fix it but they all were rejected. Don't use width/height please , use getBounds()

**Comment by kib357** [comment]
@ivanpopelyshev thanks, i've replaced `width` with `getBounds` and manually applied my stage transform on it. Still hacky, but should work faster and looks cleaner)

**Comment by ivanpopelyshev** [comment]
do you really need width/height or you want to know the center of element?

**Comment by kib357** [comment]
width, i need to place menu in upper-right corner of container

**Comment by themoonrat** [comment]
Fiddle with latest pixi: https://jsfiddle.net/xc6483w4/4/
