### ISSUE TITLE
arc called after lineTo makes the line disappear

### ISSUE THREAD

**Issue by afarber** [pixijs/pixi.js#2824]
This code works well with PIXI 3.0.10 and draws a line and an arc:

```
this.bgGraphics.lineStyle(4, 0xFF00FF, 1);
this.bgGraphics.moveTo(15, 0);
this.bgGraphics.lineTo(60 - 14, 0);
//this.bgGraphics.lineTo(60 - 15, 0);
this.bgGraphics.arc(45, 15, 15, -Math.PI / 2, 0);
```

![screen shot 2016-08-17 at 17 10 52](https://cloud.githubusercontent.com/assets/1884458/17742064/d7ce294a-649e-11e6-9721-a2a5aca54f6e.png)

But change just 1 pixel and the horizontal line is suddenly not displayed:

```
this.bgGraphics.lineStyle(4, 0xFF00FF, 1);
this.bgGraphics.moveTo(15, 0);
//this.bgGraphics.lineTo(60 - 14, 0);
this.bgGraphics.lineTo(60 - 15, 0);
this.bgGraphics.arc(45, 15, 15, -Math.PI / 2, 0);
```

![screen shot 2016-08-17 at 17 11 14](https://cloud.githubusercontent.com/assets/1884458/17742081/e426bffe-649e-11e6-90f7-fe9946825ca9.png)

**Comment by ivanpopelyshev** [comment]
Something wrong happens when point appears two times in current shape. In this base its (45,0). I think you can also omit "lineTo(64-14,0)"

Also, arcTo is not working properly. We need to fix both issues before v4 release.
