### ISSUE TITLE
Text setting width on dirty text doesn't scale correctly

### ISSUE THREAD

**Issue by rfenner** [pixijs/pixi.js#2827]
When setting the width if the text needs updating because it's dirty it scale incorrectly. If you get the width on a dirty text before setting then it updates correctly. The setter needs to add a check for if it's dirty and update before applying the new width.
`        set: function (value)
        {
            if (this.dirty)
            {
                this.updateText();
            }
            this.scale.x = value / this._texture._frame.width;
            this._width = value;
        }`

**Comment by GoodBoyDigital** [comment]
Nice catch and thanks for sharing, fancy putting a PR together? 👍

**Comment by rfenner** [comment]
I can probably do a PR would be my second but they don't seem hard.

**Comment by rfenner** [comment]
Done. [Pull Request](https://github.com/pixijs/pixi.js/pull/2830)

**Comment by GoodBoyDigital** [comment]
This should be sorted now in dev branch! @rfenner thanks for the PR - there was no need to merge it in the end as we have pushed v4 to master. Thanks helping on this issue! 👍
