### ISSUE TITLE
Updating content in masked containers causes blinking outside the mask

### ISSUE THREAD

**Issue by Dadibom** [pixijs/pixi.js#2831]
If I update something in my masked container, it's like the mask disappears for a frame. Very annoying :'(

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by Dadibom** [comment]
Ok, it seems to me that it doesn't happen with any update, but only with bitmaptext inside masked containers. How would I load a bitmapfont in a fiddle?

**Comment by GoodBoyDigital** [comment]
interesting! You can load them in from the github examples I think. Also ,
which version of Pixi are you using? Thanks!

**Comment by Dadibom** [comment]
I can't reproduce it in a fiddle :'(

Currently using:
 * pixi.js - v4.0.0
 * Compiled Mon Aug 15 2016 11:32:11 GMT+0100 (BST)

I have however reduced the problem to this part:
text.cacheAsBitmap = false;
text.text = 'somethingelse';
text.cacheAsBitmap = true;

Doing this on bitmaptext that is a child of a container with a mask when that text object is outside the mask (not visible) will cause the whole mask to be turned of for a quick moment.

**Comment by ivanpopelyshev** [comment]
/me cries about rejected PRs for cache as bitmap and local bounds

**Comment by englercj** [comment]
Can you make a fiddle of this using the latest dev build? You can add the following URL as an "external resource" on jsfiddle to use the lastest dev build:

https://pixi-builds.s3.amazonaws.com/dev/pixi.min.js

**Comment by paladizm** [comment]
Hey all hate to add to this if it has already been answered or prioritized, but I have a 4.2.3 fiddle that shows this happening (the flash then alpha in), and actually does not show the image after tweening the alpha of the container. 

v4.3.2
https://jsfiddle.net/mum6ck48/2/

v3
https://jsfiddle.net/z0rkhf0s/2/

Thanks!

**Comment by GoodBoyDigital** [comment]
Hi there, looks like you are not preloading the bunny - meaning that it will be cached as an empty sprite.

**Comment by paladizm** [comment]
Thanks @goodboydigital I will update and test it out (thumbsup)

**Comment by paladizm** [comment]
@GoodBoyDigital Updated the fiddle and still seeing the same issues, even after load. 

https://jsfiddle.net/b2ufa83j/1/

**Comment by andvolodko** [comment]
I also catched the same bug. pixi.js version 4.8.0
