### ISSUE TITLE
hitarea not respecting anchor property

### ISSUE THREAD

**Issue by Patrick-Hammond** [pixijs/pixi.js#2833]
Not sure if this is intended behaviour.
Setting the hitarea of a sprite which also has it's anchor specified doesn't work. (hit area will then lie outside the bounds of the sprite).

fiddle example, 1st click - okay, 2nd click (after hit area is set) - not okay
http://jsfiddle.net/5mydwyxd/

**Comment by englercj** [comment]
IIRC if you set hitArea it is an absolute area that is checked for hits. By opting into hitArea you basically say "don't try to calculate the hit area, just use this rect exactly".

**Comment by GoodBoyDigital** [comment]
fixed docs!
