### ISSUE TITLE
PIXI.glCore / WebGLTexture as a source to BaseTexture?

### ISSUE THREAD

**Issue by dakom** [pixijs/pixi.js#2834]
I noticed that the PIXI.glCore stuff exists, and must be part of the way of getting to more gl exposure... I'm curious what the plan is. Didn't see it being used directly in PIXI itself.

Wondering whether I'm just going down the wrong rabbit hole, or if I'm just misunderstanding how the pieces together, or if there's some other reason why BaseTexture doesn't use PIXI.glCore more directly. For example, being able to pass a PIXI.glCore.GLTexture.fromData() to BaseTexture.

Would be nice to generate textures at runtime without having to draw to canvas.... (I'm guessing the Graphics stuff does this somehow, but I didn't take too much of a peek there yet)

**Comment by ivanpopelyshev** [comment]
You can do that kind of operations with RenderTexture. It allows to generate textures on GPU side.

GLTexture exists per one renderer, while BaseTexture exists per many, and stores _glTextures[renderer.gl.id]

**Comment by dakom** [comment]
Thanks! Any more hints? renderer.render kinda brings me back full circle to needing the texture to begin with. e.g.:

var gTex = PIXI.glCore.GLTexture.fromData(gl, rgbData, canvasWidth, canvasHeight);
var rTex = PIXI.RenderTexture.create(canvasWidth, canvasHeight);
renderer.render(gTex, rTex);

**Comment by ivanpopelyshev** [comment]
I dont understand what do you want. But you can also pass canvas source to BaseTexture and then use setImageData on it, dont forget to call update() method of baseTexture after that. Anyway, if you want to manipulate rgb data with javascript, you wont be able to use it without uploading to GPU.

**Comment by ivanpopelyshev** [comment]
glCore is used by PIXI itself. If you write a plugin, new object that is somehow faster than PIXI Sprite or Mesh for some cases, you can use glCore for low-level operations.

**Comment by dakom** [comment]
gotcha... I guess I was getting at the difference between "The Easy Way" and "The Advanced Way" at https://goocreate.com/learn/procedural-textures/

For using canvas, I'm having trouble too... will post that on the forum though :)

(anyway I gotta call it a night soon)

**Comment by dakom** [comment]
ah nm got the canvas render to work :) thanks!

**Comment by GoodBoyDigital** [comment]
this guy could help? http://pixijs.github.io/pixi-examples-v2/#/basics/render-texture.js

**Comment by GoodBoyDigital** [comment]
closing for now as this seems solved! thanks @ivanpopelyshev
