### ISSUE TITLE
the pixi files under /bin/ are different then the ones hosted from cdn

### ISSUE THREAD

**Issue by NikkiKoole** [pixijs/pixi.js#2836]
this was a crazy debugging ride, my thing in production uses pixi 3.10 from the cdn,
(https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.10/pixi.js)
locally I am using the pixi 3.10 from this bin folder.
(https://raw.githubusercontent.com/pixijs/pixi.js/master/bin/pixi.js)
both are version 3.10

however:
![screen shot 2016-08-19 at 9 48 32 am](https://cloud.githubusercontent.com/assets/453055/17804127/1dfcae10-65f2-11e6-8341-3d357704e65d.png)

could those at the cdn be similar to the ones here?

**Comment by NikkiKoole** [comment]
oh and btw this is also a bit weird

![screen shot 2016-08-19 at 9 57 26 am](https://cloud.githubusercontent.com/assets/453055/17804414/6b2917e0-65f3-11e6-995a-8f0a993ef1f9.png)

the latest version of 3.10 is found at cdn under pixi.js/3.0.11/pixi.js

**Comment by GoodBoyDigital** [comment]
Hi there! this should be sorted now that we have kicked out v4 👍
