### ISSUE TITLE
no more roundPixels for WebGLRenderer in v4?

### ISSUE THREAD

**Issue by akbr** [pixijs/pixi.js#2838]
```js
var renderer = new PIXI.WebGLRenderer(800, 600, {
  roundPixels: true,
  backgroundColor : 0x1099bb
});

var texture = PIXI.Texture.fromImage('required/assets/basics/bunny.png');
var stage = new PIXI.Container();
var bunny = new PIXI.Sprite(texture);
bunny.position.x = 0.3;
stage.addChild(bunny);

animate();
function animate() {
    requestAnimationFrame(animate);
    renderer.render(stage);
}
```

With version `v3.0.11`, I get a sharp bunny:
![v3](https://cloud.githubusercontent.com/assets/804208/17821498/f919c87a-661f-11e6-9f56-778df8a73311.png)

With version `v4.0.0-rc3` I get a smeared bunny:
![v4](https://cloud.githubusercontent.com/assets/804208/17821572/49ebc03c-6620-11e6-869c-ce39c59eff34.png)

`PIXI.CanvasRenderer` renders sharp in both versions.

**Comment by ivanpopelyshev** [comment]
try https://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js

**Comment by GoodBoyDigital** [comment]
Fixed in the latest dev branch I believe! nice crispy bunnies for all!
