### ISSUE TITLE
Hunting a Memory Leak: Are PIXI Entities regarded as "Nodes" in the Webkit Timeline Inspector?

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#2840]
Hi

I've been hunting a memory leak in my game for 2 days, both Electron and Chrome memory usage grows at the same rate, while Javascript Heap is < 100MB (30MB's now), the "Nodes" count increases, it can't be GC collected, the memory usage slowly increases, I've seen it reach 1.3GB's in <2 hours (so when memory usage of "Electron" or "Chrome" is 1.3GB's, the Heap is insignificantly small)

I'm not even sure whether this "Nodes" increase accounts for the memory usage, it might be something else

I've inspected all my code and found 2 major possible leak causes, I wasn't calling .destroy() on 2X Sprite types, I was just removing them from their parents, I hope this was the cause of the issue, however it wasn't the major cause I was looking for, I think I just fixed the "actual memory leak" - while what I'm hunting is the "Nodes leak" - or something else - after this fix, the Javascript Heap is ~25MB's, however the "Nodes" growth and memory usage growth is still there

I've inspected all my code several times, currently I either have a regular DOM leak, or I might be hunting something WebGL related I can't observe

I'm currently running another experiment, yet each experiment takes 1-3 hours, I just wanted to get some input from the PIXI Community, is there any known PIXI-related causes I should look for?

(My PIXI Is V4, I built it 5 days ago from the source)

**Comment by kaansoral** [comment]
I did some tests, new PIXI.Sprite are not "Nodes", they don't seem to be observable from the "Timeline" either, no surprises there

I frequently added and removed 5000 Sprite's to the scene, without even .destroy()'ing them, didn't observe any significant impact either, both Heap-wise and Total_Memory-wise - to make things worse, while the min. total memory usage was ~140-160MB's, the Electron instance somehow shrinked to ~120MB's after these last tests

At this point I'm assuming the memory leak I'm hunting isn't PIXI related, while I'm not certain, this last trial pushed me in this direction

**Comment by kaansoral** [comment]
I eliminated everything in the game, made sure "Nodes" stayed constant before adding things back again, before this I inspected the PIXI source for document references, the only possible cause for this extra "Nodes" seemed Text's, which I heavily use and destroy

Anyway, it turns out, indeed PIXI.Text's are responsible for all the extra / un-garbed "Nodes" - I will check the source further and probably create an issue about it, at 80.000 "Nodes" - I think all those extra document.createElement('canvas')'s might be accumulating and causing the memory issue - If I'm not mistaken

**Comment by ivanpopelyshev** [comment]
There's "show paths to GC" feature when you make memory dump. Please use it, or give me the demo

**Comment by kaansoral** [comment]
Here is the simplest reproduction for me:
```
for(var i=0;i<2000;i++){ var a=document.createElement('canvas'); a=null; }
for(var i=0;i<2000;i++){ var p=new PIXI.Text(); p.destroy(); p=null; }
```

If you run the first one in the browser, then garbage collect, they are all collected
For the PIXI example, they all stay

**Comment by kaansoral** [comment]
Just checked the source further, for example this works:
```
for(var i=0;i<2000;i++){ var p=new PIXI.Text(); p.destroy({texture:true,baseTexture:true}); p=null; }
```
But I don't think a regular user of PIXI would/should dig this deep, I also wonder whether I should call .destroy with .destroy({children:true}) for large entities, I always assumed children would be destroyed too

**Comment by ivanpopelyshev** [comment]
Are you doing

```js
p.destroy({texture:true,baseTexture:true})
```

in your app for texts or entities that contain them?

**Comment by kaansoral** [comment]
My Text usage is disappearing Text's, so basically they are added to the map

When `.destroy`'ed, I destroy the PIXI.Text - only now I started using `{texture:true,baseTexture:true}` - after the discovery

**Comment by GoodBoyDigital** [comment]
Hello! Good to hear this issue is sorted! 
@bigtimebuddy - what do you think about maybe auto destroying a baseTexture of a text object? As generally a texture is isolated to the single text object?

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital I agree. I think that destroying generally should be, "if you created it, you destroy it". I would put the `baseTexture` of Text's class in that category. Also, the idea that a Text field uses a `baseTexture`, from a dev perspective, is probably pretty opaque. I'd say destroy it.

**Comment by GoodBoyDigital** [comment]
sorted 👍
