### ISSUE TITLE
Possible problem for multitexture renderer

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2841]
https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L237

```js
 nextTexture._enabled = this.tick;
 nextTexture._id = textureCount;
```

nextTexture is baseTexture, and in theory, if two renderers have the same tick , multitexture renderer will be wrong. We have to move _id and _enabled into glTexture.

**Comment by GoodBoyDigital** [comment]
good catch!

**Comment by ivanpopelyshev** [comment]
Confirmed. It was reproduced in beta of one service , they just asked me WTF, and I placed breakpoint, and that was the problem.

**Comment by GoodBoyDigital** [comment]
sorted init!
