### ISSUE TITLE
Error when creating new filter on Android Chrome with v4

### ISSUE THREAD

**Issue by merachefet** [pixijs/pixi.js#2842]
Loading/applying a new filter object with v4 causes execution to stop with an error on Android Chrome, but works as expected on Win7 Chrome. Using v3 works on both platforms.

I got this far -
In Quad.initVao, addAttribute is called with shader.attributes.**aTextureCoord**, which is undefined.
In PIXI.glCore.shader.extractAttributes on line 1292, only one attribute was extracted from the program on Android: aVertexPosition.
On Win7, two attributes are extracted: aVertexPosition and **aTextureCoord**.

The Android call stack:
```
pixi.js:939 Uncaught TypeError: Cannot read property 'location' of undefined
VertexArrayObject.addAttribute @ pixi.js:939
Quad.initVao @ pixi.js:21764
FilterManager.applyFilter @ pixi.js:21022
Filter.apply @ pixi.js:20572
FilterManager.popFilter @ pixi.js:20967
Container.renderAdvancedWebGL @ pixi.js:13271
Container.renderWebGL @ pixi.js:13200
Container.renderWebGL @ pixi.js:13209
WebGLRenderer.render @ pixi.js:19886
animate @ (index):25
window.onload @ (index):19
```

```
<script src="pixi.js"></script>

<script id="shader" type="shader">
void main() {gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);}
</script>

<script>

var renderer = new PIXI.autoDetectRenderer(200, 200);
var stage = new PIXI.Container();

var example = PIXI.Sprite.fromImage("smiley.png");
stage.addChild(example);

var shaderCode = document.getElementById("shader").innerHTML
var simpleShader = new PIXI.AbstractFilter(null,shaderCode);
example.filters = [simpleShader];

window.onload = function()
	{
	document.body.appendChild(renderer.view);
	animate();
	};

function animate()
	{
	requestAnimationFrame(animate);
	renderer.render(stage);
	}

</script>
```

**Comment by merachefet** [comment]
I had time to debug this more and read up on it. It looks like these attributes are activated automatically by the GLSL compiler based solely on the shader code. On desktop, it's apparently enough for the compiler that the aTextureCoord attribute is declared, but on mobile, the compiler is far more aggressive, and absolutely will not activate the attribute unless the fragment output depends on it somehow.

So, if a custom shader ignores the original texture, some clients will not activate the aTextureCoord attribute, and PIXI will crash trying to read undefined properties of it.

**Comment by GoodBoyDigital** [comment]
Nice! Good to hear you  got to the root. WebGL loves to optimise away properties and attributes that are not used by the shader. 👍

**Comment by Muini** [comment]
Hi, I got the exact same error, thanks for the explanation about why its doing this.
Do you have any solution to solve it ?

**Comment by merachefet** [comment]
There's probably a more efficient way, but this seems to work:
```
gl_FragColor = texture2D(uSampler, vTextureCoord);
gl_FragColor.a = (gl_FragColor.a * 0.01);  // close enough to zero
gl_FragColor.a = gl_FragColor.a + 0.5;  // close enough to 0.5
```
The fragment output needs to actually include information from the texture sample. Just calling it and throwing away the result is not enough to fool the compiler.

**Comment by kadir-uix** [comment]
I came across a similar problem. 

My line went from: 
`gl_FragColor = vec4(c * cos(gl_FragCoord.y / resolution.y), 1.0);`
to
`gl_FragColor = texture2D(uSampler, vTextureCoord);
gl_FragColor = vec4(c * gl_FragColor.a * cos(gl_FragCoord.y / resolution.y), 1.0);`

And now it works. Might be handy for anyone running into the same problem. 
Thanks for the initial solution @merachefet
