### ISSUE TITLE
PIXI calling window.getAnimationFrame

### ISSUE THREAD

**Issue by Dadibom** [pixijs/pixi.js#2843]
I would like an option to disable pixi calling getAnimationFrame and instead manually polling it, since it's quite a heavy function

**Comment by ivanpopelyshev** [comment]
which RAF are you talking about, PIXI ticker interaction default one ?

**Comment by andrewstart** [comment]
```javascript
PIXI.ticker.shared.autoStart = false;
PIXI.ticker.shared.stop();
```
will disable the default Ticker. It is the only place where `requestAnimationFrame` is automatically called.

**Comment by Dadibom** [comment]
I'm guessing it's the one andrew mentioned @ivanpopelyshev! I just saw that something called it. Alright, and what will that break @andrewstart?

**Comment by englercj** [comment]
@Dadibom MovieClips

**Comment by Dadibom** [comment]
Alright, I don't use movieclips anymore so I should be good then. Thanks!

**Comment by themoonrat** [comment]
Don't forget that this shared ticker is also used in the interaction manager!

**Comment by ivanpopelyshev** [comment]
@themoonrat but i think we can just shut it down, it will work on events anyway.
