### ISSUE TITLE
[3.0.11] FXAA antialiasing being used instead of native antialiasing

### ISSUE THREAD

**Issue by PierBover** [pixijs/pixi.js#2846]
I'm getting this error on iOS:

> FXAA antialiasing being used instead of native antialiasing

Also getting a very ugly antialiasing compared to Chrome on Android.

Is this fixed in v4?

**Comment by GoodBoyDigital** [comment]
Yup! its now a filter you can use rather than being used automatically:

```myStage.filters = [new PIXI.filters.FXAAFilter()];```
