### ISSUE TITLE
iOS safari cannot window.open from touchstart event

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#2848]
Tested on both iPhone and iPad, the event function is triggered, however window.open or similar is completely ignored.  On non-iOS devices, the new window opens as expected.

http://codepen.io/staff0rd/pen/PzvvNg?editors=0010#0

**Comment by kaansoral** [comment]
Out of curiosity, does regular <a> links work? (I have an issue with my project, where regular links stopped working after one point, just thought 2 issues might be related, or mine might be originating from something else)

**Comment by staff0rd** [comment]
Yeah it does - I just updated the pen to include an `<a>` tag with the same detail, window opens using the link directly.

**Comment by staff0rd** [comment]
As reference (and hopefully to help solving this), [here's a phaser example](http://codepen.io/staff0rd/pen/pbmmPE?editors=0010#0) that works properly in iOS Safari.

That it doesn't work in pixi has me thinking it's something to do with iOS Safari blocking window.open from sources that it doesn't think was an actual button press.  There's obviously some way around this though considering the phaser example works.

**Comment by kaansoral** [comment]
I just debugged my issue, it was unrelated to this by the way, turns out, events propagate from links, and if you call event.preventDefault in a lower level, it prevents opening a new window

Hope you solve your issue, assuming it's solveable, event issues are always demotivating

**Comment by staff0rd** [comment]
Investigating the phaser example I saw that the event was `touchend` rather than `touchstart`.  Changing my example to use `touchend` or `tap` causes the window to open as expected.

[Updated pen](http://codepen.io/staff0rd/pen/KrLjKv)

**Comment by kaansoral** [comment]
Funnily, both out window.open's were probably prevented by the .preventDefault's - I just inspected the pixi source, if you don't disable it, the touchend is preventedDefault'ed by default

**Comment by ivanpopelyshev** [comment]
In iOS it wont work in most cases, due to strict policy on popups. Please use accessability so user touches actual html <a> tag with target=blank.
