### ISSUE TITLE
How to attach the sprite to the stage outside of the viewport?

### ISSUE THREAD

**Issue by sesn** [pixijs/pixi.js#2849]

**Comment by GoodBoyDigital** [comment]
Hi there! Please can you provide more information. Thanks!

**Comment by sesn** [comment]
Main container width is 1280 x 600,
The following one is one of the sprite image. I want it to place before the 1280 width.
I just want that sprite image to be rendered off the stage. 
If lampPost position x co ordinate is 0, the sprite is rendering If it is negative, it is not rendering.

lampPost = new PIXI.Sprite(resourcesAll.street_lamp.texture);
lampPost.position.x = -100;
lampPost.position.y = -100;

**Comment by GoodBoyDigital** [comment]
If you could provide a fiddle for us to debug that would be ace 👍

**Comment by sesn** [comment]
My fiddle link is https://jsfiddle.net/7qdm2x16/

Another error has been coming cross-origin image has blocked.

**Comment by GoodBoyDigital** [comment]
Cool, you will need to fix the crossdomain issue before we can debug - maybe move images to a different server?

**Comment by sesn** [comment]
I am not able fix that cross domain error. 
I have attached the demo url:
https://wklabs.com/dev/github-help/js.html

When i give x position to -400 to lampPost it is not generating

**Comment by GoodBoyDigital** [comment]
I struggling to see the issue? What does - not generating mean?

**Comment by whizzkid** [comment]
The lamp position in your demo is at 0,-100  and it is visible.
if you set its x-position to -400  it is rendered off stage to the left, and you won't be able to see it. because its off stage. that's what that term means :)

so I think everything is working properly ?
