### ISSUE TITLE
Measuring a hidden container always comes back as 0 [v4]

### ISSUE THREAD

**Issue by paladizm** [pixijs/pixi.js#2850]
I was testing out v4 and stumbled across an interesting one. I do a good amount of object creation while a container is not visible. Sometimes I need to measure that container and add a child to the bottom of its current height (measured after already adding a bunch of sprites and graphics to the container). This used to work flawlessly in v3, but it seems like in v4 if the container is not visible the measurement of container.height / container.width comes back as 0. I have made two jsfiddles one using v4 and the other v3 to show what I am talking about. 

v4:
https://jsfiddle.net/9m5hr8vs/1/

v3:
https://jsfiddle.net/u0h5e4x4/1/

Thanks!
Zac

**Comment by akbr** [comment]
This one surprised me too. See #2795.

**Comment by paladizm** [comment]
Oh man! Thanks @akbr! I missed that closed issue. I will close this one as they already answered my question. I will have to flip flop visibility during creation.
