### ISSUE TITLE
http://pixijs.github.io/docs/ search issue

### ISSUE THREAD

**Issue by Hachitus** [pixijs/pixi.js#2851]
Just to mention, if you didn't know yet. The mainpages http://pixijs.github.io/docs/ search functionality does not work correctly after the new pages have been released (Pixi v4 Yay! :). When you go to subpages, the search works fine e.g. http://pixijs.github.io/docs/PIXI.AccessibilityManager.html, but on the mainpage it does not work.

Windows 10, Chrome: 52.0.2743.116

**Comment by photonstorm** [comment]
Also typo in the first point on the homepage:

"PixiJS' strength is speed. When **is** comes to 2D rendering, PixiJS is the fastest there is."

**Comment by GoodBoyDigital** [comment]
@Hachitus - will take a look into that, thanks for sharing!

@photonstorm Haha - typos are my nemesis! Good catch  👍  fixed!

**Comment by mrgoonie** [comment]
Yea, scrolling on the left navigation not working as well. Please check.

**Comment by GoodBoyDigital** [comment]
Not sure it needs scrolling?

**Comment by mrgoonie** [comment]
Check this screenshot:

![2016-08-25_16-58-12](https://cloud.githubusercontent.com/assets/6857382/17965175/66908b9a-6ae5-11e6-92eb-a8264cf527bb.jpg)

**Comment by GoodBoyDigital** [comment]
gotcha! Was looking at the wrong site :D

**Comment by GoodBoyDigital** [comment]
Hey @bigtimebuddy -any ideas as to what could be going on here?

**Comment by bigtimebuddy** [comment]
There's a bug in the JSDoc theme. The code blocks in the README are assumed to be source code with line numbers. Going to fix and push an update of jaguarjs-jsdoc

**Comment by GoodBoyDigital** [comment]
Hero! 👍

**Comment by bigtimebuddy** [comment]
Fixed. @GoodBoyDigital check out the PR and update the documentation using [jaguarjs-jsdoc@1.0.1](https://github.com/pixijs/jaguarjs-jsdoc/releases/tag/v1.0.1), should resolve these issues.

**Comment by GoodBoyDigital** [comment]
Docs have now been update 👍  scrolls and searches like a champ - thanks all!
