### ISSUE TITLE
How to build the same pixi as in dev?

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#2852]
When I run **npm run build** on a freshly checked out git repo on the dev branch on my windows machine,
I get a pixi.js file thats 15kb smaller than the one precompiled in the repository.

How is the pixi.js in the repo actually built ?

**Comment by whizzkid** [comment]
or is the current prebuilt one just out of date?

**Comment by GoodBoyDigital** [comment]
Hello! I'm not too sure tbh - have you tried removing node_modules and adding them again?

**Comment by bigtimebuddy** [comment]
I was going to suggest the same thing @GoodBoyDigital. Also, since you are the only one publishing the bin files to dev, maybe you could also try removing your node_modules next time you republish.

**Comment by whizzkid** [comment]
Size is almost the same now, but the makeup is different.. weird
mac/linux/pc differences maybe?

**Comment by GoodBoyDigital** [comment]
Just pushed some new builds to dev after a clear npm install... looks all good? (if it helps im on a mac?) 

Thanks!
