### ISSUE TITLE
README.md: Release link is broken

### ISSUE THREAD

**Issue by marzepani** [pixijs/pixi.js#2858]
The link to the release page is broken.

> Note: 3.0.11 can be replaced any [released](https://github.com/pixijs/pixi.js/blob/master/pixijs/pixi.js/releases) version.

Should be
> Note: 3.0.11 can be replaced _by_ any [released](https://github.com/pixijs/pixi.js/releases) version.

Thank you for pixi.js! 🚀

**Comment by bigtimebuddy** [comment]
Thanks @marzepani, good find!
