### ISSUE TITLE
V4 - TextStyle `font` VS `fontFamily`

### ISSUE THREAD

**Issue by SlawomirMazgaj** [pixijs/pixi.js#2859]
Hello guys, well done with V4 release!
Looks like migration from V3 is going to be pretty straightforward and I'm looking forward to check performance :)

There's one thing tho I'm not really sure about. It might be a stupid question, but...
Shall I use `font` or `fontFamily`for TextStyle?

According to [DOCUMENTATION-TextStyle](http://pixijs.github.io/docs/PIXI.TextStyle.html):

> **font**
> 
> Set all properties of a font as a single string
>
>     Deprecated
>     - since version 4.0.0

And `fontFamily` is there.
<br />
On the other hand, also from [DOCUMENTATION-Text](http://pixijs.github.io/docs/PIXI.Text.html):
> A Text can be created directly from a string and a style object
```
var text = new PIXI.Text('This is a pixi text',{font : '24px Arial', fill : 0xff1010, align : 'center'});
```

So this guy is still using `font` and wait, there's more:
[V4 Text example](http://pixijs.github.io/examples/#/basics/text.js) is also using `font`.
<br/>
I'm really puzzled by how does it work with `font`... I was even checking [Text.js sources](https://github.com/pixijs/pixi.js/blob/master/src/core/text/Text.js#L226) and it seems like it never uses `style.font` but it's combining it like `this._font = style.fontStyle + ' ' + style.fontVariant + ' ' + style.fontWeight + ' ' + fontSizeString + ' ' + style.fontFamily;`
So what kind of sorcery is that? And which one should be used?

**Comment by bigtimebuddy** [comment]
Hey @SlawomirMazgaj, looks like the documentation for Text needs to get updated. The font property was deprecated. Thanks for pointing that out. Here's what that the example should look like:

```js
var text = new PIXI.Text('This is a pixi text',{
    font : 24, 
    fontFamily: 'Arial',
    fill : 0xff1010, align : 'center'
});
```

**Comment by SlawomirMazgaj** [comment]
Thanks, gonna use `fontFamily` then.
(you probable meant `fontSize : 24` instead of `font : 24`)

**Comment by bigtimebuddy** [comment]
Yup, sorry, `fontSize` (fixed)

**Comment by bigtimebuddy** [comment]
Sorted. Thanks @SlawomirMazgaj!

**Comment by SlawomirMazgaj** [comment]
What about [EXAMPLE](http://pixijs.github.io/examples/#/basics/text.js) web page?

**Comment by SlawomirMazgaj** [comment]
@bigtimebuddy What about [EXAMPLE](http://pixijs.github.io/examples/#/basics/text.js) web page?

**Comment by bigtimebuddy** [comment]
Could you file this issue on https://github.com/pixijs/examples?

**Comment by SlawomirMazgaj** [comment]
Ah, didn't know it's on separate repo. Will do 👍

**Comment by bigtimebuddy** [comment]
Cool, thanks for your help @SlawomirMazgaj
