### ISSUE TITLE
Text doubled up after 4.0

### ISSUE THREAD

**Issue by dan335** [pixijs/pixi.js#2862]
After updating to 4.0 all of my text is doubled up.  It looked ok with 4.0 rc2 (or maybe it was rc3).

![asdf](http://i.imgur.com/EFA8olv.png)

**Comment by GoodBoyDigital** [comment]
Look at that! Its a er.. cool new feature? 
 If you could provide a fiddle for us to debug that would be ace 👍

**Comment by dan335** [comment]
I noticed you made some text changes to dev and tried the dev branch.  Awesome new feature now has random widths to the text! :P   I tried making a fiddle but can't reproduce it.  Not sure where to start looking.  

![asdf](http://i.imgur.com/du041vm.png)

**Comment by GoodBoyDigital** [comment]
haha! nice - Could you share any of the source code for the above imgs?

**Comment by dan335** [comment]
I got it working!  I was setting text.canvas to something.  Commenting it out fixed  both the doubled up text and the strange heights/widths.

**Comment by GoodBoyDigital** [comment]
woop!
