### ISSUE TITLE
resize or scaling looks different between iPhone and pc browser

### ISSUE THREAD

**Issue by tywang2006** [pixijs/pixi.js#2865]
for below code, the scene(container) looks right, always middle and scaled properly.

in iPhone, it looks wrong position and the sprite is not able to click but when you click another place in the container/scene, the sprite become clickable. the scene size and position are even different between webgl and canvas render. I think it will be a big issue to deploy the app/game in iPhone. I am using iPhone 6+

let ratio: number = Math.min(window.innerWidth / that._maxWidth, window.innerHeight / that._maxHeight);
        that._currentScene.scale.x = that._currentScene.scale.y = ratio;
        if (that._maxHeight * ratio > 1) ratio = 1;
        that._renderer.resize(that._maxWidth * ratio, that._maxHeight * ratio);
        that._renderer.view.style.left = ((window.innerWidth - that._renderer.width) >> 1) + 'px';
        that._renderer.view.style.top = ((window.innerHeight - that._renderer.height) >> 1) + 'px';
        that._currentScene.x = (that._renderer.width ) / 2;
        that._currentScene.y = (that._renderer.height ) / 2;

**Comment by tywang2006** [comment]
found the issue, fixed

**Comment by ivanpopelyshev** [comment]
thas not all. Dont forget about that effect:

'''js
renderer=new WebGLRenerer(400,300, {rsolution:2})
console.log(renderer.width) //2x400=800
'''

If you use resolution, actual width in CSS or stage pixels will be "r.width/r.resolution"
