### ISSUE TITLE
Some sprites not displaying - setting anchor to a new Point breaks stuff

### ISSUE THREAD

**Issue by Dadibom** [pixijs/pixi.js#2866]
A few of the many sprites in my game now have all NaN verted data properties since ~16th aug. Nothing special about the sprites, they are not really any different at all from the other sprites in the game. Children work as intended.

**Comment by Dadibom** [comment]
Bounds are infinity as well

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by Dadibom** [comment]
Unfortunately, I can't, because I don't know what causes it. This was caused by #2817 or #2818

**Comment by GoodBoyDigital** [comment]
Cool, appreciate its tricky to recreate - without an example to recreate the bug this will take a lot longer to debug i'm afraid. It would be massively helpful if you could find the time to create one!

**Comment by ivanpopelyshev** [comment]
Solution: dont do that:

```js
sprite.anchor=myPoint
```

we will either make property copy-on-assignment (like with position), either make it read-only (wasnt used in pixijs yet)

Thank you for debugging, that helped us! I added that stuff to migration guide #2867

**Comment by GoodBoyDigital** [comment]
Lets go with @Dadibom 's suggestion of using copy. This sits in line with how other points work in pixi.

**Comment by brianblakely** [comment]
Ran into this issue myself.

The following pattern fixed it.  After instantiating the sprite: `mySprite.anchor.set(0.5, 1.0);`

**Comment by englercj** [comment]
Should be fixed by #3017
