### ISSUE TITLE
Migration guide v3->v4

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2867]
- Textures are clamped by default, in v3 they were repeated http://www.html5gamedevs.com/topic/24778-displacementfilter-not-repeating-when-moving-displacement-sprite/

```js
texture.baseTexture.wrapMode=PIXI.WRAP_MODES.REPEAT;
```

- For filters , you have to use mappedMatrix to convert textureCoord to mapCoord, all because of paddings and pow2. Also, use filterClamp uniform to prevent bad things on edges (inputCoord.xy, filterClamp.xy, filterClamp.zw) : http://www.html5gamedevs.com/topic/24347-weird-filterareas-size-on-v4/ , displacement and blur are good examples for that

- if you had that piece of code somewhere, remove it. In most cases, pixi-display plugin might be able to help you. 

```js
s.position = myPoint; // COPYING ASSIGNMENT! in v3 that was reference
s2.position = myPoint; //shadow sprite , same coord
myPoint.x = 10; //wont work. ha-ha

s.anchor = myPoint ; // DONT do that please! we will fix it later
``` 

- https://github.com/pixijs/pixi.js/issues/2859 - YEAH, font is deprecated use font-family and all that

- TilingSprite works bad with mipmap, and pow2 textures are mipmapped by default. We will fix that issue later, for now just

```js
texture.baseTexture.mipmap=false;
```

**Comment by GoodBoyDigital** [comment]
Thanks for that @ivanpopelyshev ! To all - if you find anything els please feel free to add it here. I think we have most bases covered at this point! 👍

**Comment by bigtimebuddy** [comment]
Would we move this to a Wiki page instead of an Issue?

**Comment by erpy** [comment]
Is Pixi4 actually not understanding comments in shaders source code ?
The new system finds uniforms even when they are commented out...

**Comment by englercj** [comment]
> Is Pixi4 actually not understanding comments in shaders source code ?
The new system finds uniforms even when they are commented out...

That is correct, it does not account for comments. You should open a separate bug, and we should not do source parsing and just use the results of the compiled shader instead.

**Comment by bigtimebuddy** [comment]
Please contribute to https://github.com/pixijs/pixi.js/wiki/Pixi-v4-Migration-Guide

**Comment by englercj** [comment]
Anyone who find things to add to the guide can add them in the wiki here: https://github.com/pixijs/pixi.js/wiki/Pixi-v4-Migration-Guide

Closing this for now.
