### ISSUE TITLE
Minified build missing some deprecated files

### ISSUE THREAD

**Issue by chipbell4** [pixijs/pixi.js#2869]
It looks like `AbstractFilter` was deprecated in favor of `Filter` in v4, and aliased in `deprecation.js`. However, it seems like the minified version doesn't have this deprecated alias in it. When I include the unminified build `PIXI.AbstractFilter` gives me `PIXI.Filter` with a helpful deprecation warning. However, the minified build instead gives me `undefined` for `PIXI.AbstractFilter`, which causes some backwards compatibility to break (pixi-flash in my case).

Is this an intentional step in the build, or an oversight? Or, am I doing some thing wrong here?

**Comment by GoodBoyDigital** [comment]
Good catch @chipbell4 ! Think this is more of an oversight, not too sure why thats the case. It should always be there..

**Comment by bigtimebuddy** [comment]
We decided that deprecations were going to be ignored from the release build. They are, however, presents in the debug build.

**Comment by alvinsight** [comment]
Hi Matt and Mat,
Just to give you my 2 cents there, a lot of people naively grab the minified build, unfortunately.
With tutorials on the web using the old API (think DisplayObjectContainer,etc...), I think it would be wise to put it in the minified build.
Cheers,
Alvin

**Comment by GoodBoyDigital** [comment]
Thats a really good point @alvinsight ! @bigtimebuddy Should we consider adding the deprecation layer in to the main build and removing the warnings instead?

**Comment by bigtimebuddy** [comment]
Yeah, we could certainly do that.

**Comment by bigtimebuddy** [comment]
Fixed.

**Comment by GoodBoyDigital** [comment]
Nice one @bigtimebuddy 👍

**Comment by chipbell4** [comment]
Thanks @bigtimebuddy
