### ISSUE TITLE
PIXI.Text size that specified padding is changed in v4.

### ISSUE THREAD

**Issue by YayoiAyame** [pixijs/pixi.js#2871]
![padding_image](https://cloud.githubusercontent.com/assets/6729410/18016115/94eb5666-6c05-11e6-8e1a-dffb80c02be8.png)
The above image is the view of the time which aimed at the size of the PIXI.Text.
`graphics.drawRect(text.x, text.y, text.width, text.height);`

When specifying padding, it hopes to become get the same size that the padding was not specified.

**Comment by GoodBoyDigital** [comment]
thanks for the example @YayoiAyame 👍

**Comment by GoodBoyDigital** [comment]
All fixed 👍

**Comment by YayoiAyame** [comment]
Thank you!
