### ISSUE TITLE
Video playback broken?

### ISSUE THREAD

**Issue by dakom** [pixijs/pixi.js#2873]
Video playback does not seem to work from a video element... or am I doing something wrong?

https://jsfiddle.net/aegnuj1n/

The audio plays but no visual...

**Comment by GoodBoyDigital** [comment]
Hello there! Thanks for reporting the bug and providing the fiddle too! Will let you know when this has been addressed 👍

**Comment by GoodBoyDigital** [comment]
looks like it could be cross origin issue?

**Comment by dakom** [comment]
Thanks for taking a look! I saw cross-origin errors when using video from somewhere else, but not this time. In any case I'll try to copy the video somewhere so all links are relative...

**Comment by GoodBoyDigital** [comment]
👍

**Comment by dakom** [comment]
OK, check this out: http://storage.googleapis.com/tjandpals-temp/pixi-video-test/index.html

When Play() is called right away - it works. But with the 3 second timeout, same bug...

**Comment by GoodBoyDigital** [comment]
Nice - will make sure to take a look and see whats going on!

**Comment by GoodBoyDigital** [comment]
Hello! Fixed in dev branch 👍

**Comment by pr1ntr** [comment]
This is problematic for me. This seems to be a major bug for using pixi with video in mobile. installing pixi.js#dev from github doesn't work because there are no built files nor does npm run build work (lint errors). the only way I can think of getting this to work is to git clone the whole repo, build it, and then npm link by way of shell scripts in the build process. Any thoughts?

**Comment by englercj** [comment]
@pr1ntr Check out the FAQs to see how you can download a build for any branch: https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build

**Comment by pr1ntr** [comment]
@englercj that is a solution but it seems kind of an anti-pattern when using npm. Meaning I have to manage the dependency manually. Any idea when 4.1 is due to release to npm? :)

**Comment by englercj** [comment]
v4.1 will release when we clear the milestone, hopefully in the next few weeks. If you want to have git urls work with this repo in such a way to where you also get builds you are free to put in a PR that adds the proper install scripts.

**Comment by pr1ntr** [comment]
Thanks. I just might.

**Comment by pr1ntr** [comment]
Is there any way for pixi to not go fullscreen for video playback on ios?

**Comment by englercj** [comment]
@pr1ntr Can you open a different issue with a repro case? I'm not aware of that issue.
