### ISSUE TITLE
tint property not working on Graphics

### ISSUE THREAD

**Issue by aidangrabe** [pixijs/pixi.js#2874]
Using pixijs 3 the following would work:
```Javascript
var g = new PIXI.Graphics();
g.beginFill(0x999999);
g.drawRect(0, 0, 100, 100);
g.endFill();
g.tint = 0xFF0000;
stage.addChild(g);
```

On 4.0.0 it doesn't seem to be working.
Tested on Chrome 52 and Firefox 48

[JSFiddle](https://jsfiddle.net/m15ywyc0/)

**Comment by ivanpopelyshev** [comment]
fastrect, again? need to check renderFastSprite

**Comment by aidangrabe** [comment]
Replacing `g.drawRect(...)` with other shapes seems to work as expected eg:

```Javascript
g.drawPolygon(
	[0, 0,
  100, 100,
  0, 100,
  0, 0]
);
```
or
```Javascript
g.drawCircle(50, 50, 50);
```

**Comment by ivanpopelyshev** [comment]
thats what i said, problem with renderfastsprite, optimization uses sprite instead, it is faster

**Comment by GoodBoyDigital** [comment]
fixed in dev whoop! 👍
