### ISSUE TITLE
Loader - Preserve query strings

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#2875]
I have a scenario where I need to load spritesheets with a version number attached to them via querystring due to static files otherwise being cached.  Whilst I can invalidate the cache on new deployments, some browsers will still pull an old image file without checking whether the cache has been invalidated.  As such, I want to work around this by caching on querystrings, where I'd append a version number like `http://foo.com/bar.json?version=3` as the path to the spritesheet.

Currently that querystring will not be used when the image is queued up in the loader however.  I'm going to change my dev copy of `spriteSheetParser` so it does.  Is something that would be accepted in a PR, or is it something that should be implemented in `ResourceLoader`?

**Comment by staff0rd** [comment]
For example; https://github.com/staff0rd/pixi.js/commit/4ce912e168bcaf65598adf22c6ba12b923e30886

**Comment by englercj** [comment]
Depends, are you saying the resource-loader is stripping query strings, or that you expect the spriteSheetParser to be adding the query string of the original URL to images it loads from the spritesheet?

**Comment by staff0rd** [comment]
The resource loader is not stripping them, rather the the spritesSheetParser doesn't include them when it [builds the url](https://github.com/pixijs/pixi.js/blob/221ff385651b3f54021661a9572c19ba3b4a9338/src/loaders/spritesheetParser.js#L33).

In a caching scenario, if I wanted all resources to have a querystring appended, I would need to append the string to all urls passed to the resource loader, and then override all middlewares that build urls like the spriteParser.

I'm thinking now that the having a single spot in the resource loader where a querystring could be specified and then appended to all resources could possibly be a solution.

**Comment by ivanpopelyshev** [comment]
@staff0rd Will https://github.com/pixijs/pixi-compressed-textures help you? Beware, some of its features arent available in v4 yet, but loading process works just fine

**Comment by staff0rd** [comment]
@ivanpopelyshev I'm not sure that's related - the source doesn't seem to contain anything specific to querystrings?.

**Comment by ivanpopelyshev** [comment]
No, but it can swap suffixes on fly. ".json"->".json?version=3" and so on, its related a bit :)

Which web-server do you use?

**Comment by englercj** [comment]
> The resource loader is not stripping them, rather the the spritesSheetParser doesn't include them when it builds the url.

Then here is the correct place :smile:

**Comment by staff0rd** [comment]
> I'm thinking now that the having a single spot in the resource loader where a querystring could be specified and then appended to all resources could possibly be a solution.

@englercj no interest in this?  It extends to more than just the spritesheet parser.

**Comment by englercj** [comment]
Not sure what behavior you expect from the loader itself, if the parser tells the loader to use a specific URL that doesn't contain the query string what do you expect the loader to do? What is your ideal usage here?

**Comment by staff0rd** [comment]
I'm now certain this is a feature for the loader rather than separate parsers, so I'll close this, implement the functionality I'd like in a fork.  I'll open an issue on the loader for you to determine whether it warrants inclusion or not.

Briefly - I want a timestamp or version number appended as a querystring to every file that the loader processes for caching reasons.  Such functionality is better suited for the loader due to;

* I want all downloads to include the querystring, therefore it would be more consise for the loader to be configured to do it, rather than append the (same) querystring to every path I pass to it.
* Secondary files `add()`ed by parsers do not have a path supplied to them by the user, rather they are built using information in the primary file - this primary file will not (and should not) include the querystring value
* Maintaining this functionality at the parser level would require maintenance of all parsers.  Including the functionality at the loader level would mean future parsers are also covered.
