### ISSUE TITLE
How to NOT draw holes in masks?

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#2877]
We wanted to make a mask with a square and a circle..  turns out it sorta XOR's the shape
Can this be turned off (or: shouldnt this be turned ON instead of being default behavior?)

see fiddle for example  : https://jsfiddle.net/whizzkid74/sLp2qf5g/

probably caused by #1755

**Comment by GoodBoyDigital** [comment]
Thanks @whizzkid , will take a look 👍

**Comment by whizzkid** [comment]
by the way, this fiddle draws the actual maskshape we would like :)

https://jsfiddle.net/whizzkid74/zt88dpbd/1/

**Comment by whizzkid** [comment]
is there a way to turn this off in the current code? 
 if not, its a bug, not an enhancement..

**Comment by SlawomirMazgaj** [comment]
I already bugged that some time ago in https://github.com/pixijs/pixi.js/issues/2559.
I could swear there was a fixed version on dev branch one day but somehow that didn't get merged to final V4 release.

**Comment by MichaelZawadzki** [comment]
Experiencing the same issue. 
Went from v3 to v4 and this started happening.

**Comment by staff0rd** [comment]
Works on CanvasRenderer, not on WebGLRenderer.

**Comment by staff0rd** [comment]
Actually, these samples from @elfrog show the issue also affects CanvasRenderer;

v3 (working): https://jsfiddle.net/elfrog/oozrecjn
v4 (webgl/canvas): https://codepen.io/staff0rd/pen/oYEWZJ?editors=0010

**Comment by ImAdamTM** [comment]
Is there any update on this issue? It's still a problem as of 4.3.4. I've rolled back to v3 for the moment which behaves as expected. Is someone able to pinpoint what change caused this in the meantime?

**Comment by raphadko** [comment]
Any updates on this? Following

**Comment by loudmotion** [comment]
still seeing this in v4.5.2. but canvasRenderer seems ok
https://jsfiddle.net/ggey7u4p/8/ - canvas version
https://jsfiddle.net/o8mxh96L/1/ - webGL

**Comment by englercj** [comment]
Merged in a potential fix for this.

Can you retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!
