### ISSUE TITLE
Using self as mask

### ISSUE THREAD

**Issue by Dadibom** [pixijs/pixi.js#2878]
I'd like to be able to use the parent sprite as a mask for its children. Is it possible already?

**Comment by ivanpopelyshev** [comment]
No, because of "renderable" property. Masks have turned off "renderable" so they wont be drawn on the screen. Unfortunately, this property also affects children :( @GoodBoyDigital that's one more problem about layers

**Comment by Dadibom** [comment]
I should be able to simply set the renderable property to true after using it as a mask. Though this might still be problematic. Should children be part of the mask or no? In that case, the children wouldn't be masked anyway since they would add to their own mask. Hope that was clear enough lol.

**Comment by ivanpopelyshev** [comment]
No, they wont be part of mask. But parent will be drawn one extra time before them, because it has renderable=true.

**Comment by Dadibom** [comment]
So, simply being able to set 
child.mask = parent;
parent.renderable = true;
should work?

**Comment by ivanpopelyshev** [comment]
Yes, but it will have a side effect

**Comment by Dadibom** [comment]
What side effect?

**Comment by ivanpopelyshev** [comment]
I just told you :) Parent will be drawn both as a simple sprite beneath them, and used as a mask. The thing is, "renderable=false" fixes it, but but its recursive by some reason, so it affects children

**Comment by Dadibom** [comment]
Yeah but isn't that exactly what I want? I want both the parent and children to be rendered, but the children shouldn't be visible outside the parent sprites boundaries

**Comment by ivanpopelyshev** [comment]
oh, may be :) but there can be a problem with blending, check if children will have modified colors.

**Comment by GoodBoyDigital** [comment]
Hi @Dadibom I think a similar effect can be achieved by adding the mask to the same container as the children. 

Then any transform you apply to the parent will effect all elements the same way?

**Comment by Dadibom** [comment]
Yeah, I just wanted to avoid having two instances of the same sprite in the same position (mask and the actual sprite). However, I'm still facing a problem: it appears to be impossible to use textureregions on masks..

**Comment by GoodBoyDigital** [comment]
If a Sprite is masking itself, is it not something that can be baked into a new single sprite? That would be much faster!

**Comment by Dadibom** [comment]
Well yes but that would require a ton of work. It's for a shine effect!

**Comment by GoodBoyDigital** [comment]
It would require more effort true! The best thing to do is have two sprites
one to mask and one to be the mask.

I would then add them to a container - and move that around instead of the
mask if that makes sense? That way you are still moving around one element
and they will always aligned.

Hope that helps!

**Comment by Dadibom** [comment]
Yeah, that's what I'm doing now, but I think that this should still be possible (or at least throw an error or something)

**Comment by GoodBoyDigital** [comment]
fair point! Lets make sure this is made clear in the documentation.
