### ISSUE TITLE
cancel animationFrame?

### ISSUE THREAD

**Issue by jesperlandberg** [pixijs/pixi.js#2881]
Hi,

I have this bit of code:

	render(){

		requestAnimationFrame(this.render.bind(this));

		this.tl
			.to(this.displacementFilter.scale, 1, { x: 75, ease: Power2.easeInOut })
			.to(this.displacementFilter.scale, 1, { x: 0, ease: Power2.easeInOut });

		this.renderer.render(this.stage);

	}

I am using Greensock (GSAP) to tween the scale.x property of a filter, however, I just want this to be played once. So how can I render this, and cancel rAF when the tweening is done? Any tips?

**Comment by alvinsight** [comment]
Hi,
You shouldn't put your timeline tweens in the `render` loop, it will create a new tween 60 times a second! 
You just need to put the tween somewhere else where it's only called once.
Also, TweenLite provide an "onUpdate" callback that is called 60 times a second for the duration of the tween, so if you only want to render your scene while the scale is animated, you can put the above code in that callback.

**Comment by GoodBoyDigital** [comment]
@alvinsight is spot on! 👍

**Comment by alvinsight** [comment]
Ha ha cheers ☺

**Comment by jesperlandberg** [comment]
thanks @alvinsight for clearing things up for me=)
