### ISSUE TITLE
PIXI v4 cacheAsBitmap issue

### ISSUE THREAD

**Issue by cvissie** [pixijs/pixi.js#2883]
Not related to https://github.com/pixijs/pixi.js/issues/2831 although I have experienced that as well.

I'll see if I can create a fiddle for this later on today, but what I *think* it is:

```javascript
var container1 = new PIXI.Container();

var container2 = new PIXI.Container();
container2.addChild(someSprite1);
container2.addChild(someSprite2);
container2.cacheAsBitmap = true;
container1.addChild(container2);

container1.alpha = 0;
```

After this container2 doesn't seem to display no matter what the alpha is of container1.

**Comment by GoodBoyDigital** [comment]
Cheers for this! A fiddle would be ace if you have a moment. 👍

**Comment by ivanpopelyshev** [comment]
My patch had fix for worldAlpha too, i just forgot to tell you about that. Its really easy to test, I think: before getLocalBounds you have to change parent worldAlpha for one moment, or change parent ot element.

**Comment by paladizm** [comment]
I ran into this as well. Here are some fiddles,

v4:
https://jsfiddle.net/5b7whd4v/1/

v3
https://jsfiddle.net/z0rkhf0s/1/

**Comment by GoodBoyDigital** [comment]
@paladizm hero! Fiddles make me happy :D

**Comment by cvissie** [comment]
@paladizm Thanks for the fiddles. I never got round to writing them today.

**Comment by GoodBoyDigital** [comment]
Fixed in dev branch. Thanks all 👍
