### ISSUE TITLE
PIXI v4 Triangle Shapes no longer possible using PIXI.Graphics(drawPolygon)

### ISSUE THREAD

**Issue by MrChampion** [pixijs/pixi.js#2884]
In the new v4 version its no longer possible to create a triangle shape w/ only 3 points.

https://jsfiddle.net/g95uzu22/

Don't know if this is intended as there are ways to create the shape anyway by repeating the points to close the shape.

An initial cursory check seems to indicate changes in drawShape 'dirty' flags and/or in GraphicsRenderer?

**Comment by GoodBoyDigital** [comment]
Hello there! Thanks for reporting the bug and providing the fiddle too! Will let you know when this has been addressed 👍

**Comment by GoodBoyDigital** [comment]
Fixed in dev branch! Thanks for providing the info required @MrChampion 👍
