### ISSUE TITLE
Migration issue: fontSize in PIXI 3.0.11

### ISSUE THREAD

**Issue by marekventur** [pixijs/pixi.js#2886]
See: https://jsbin.com/vegisetapa/edit?js,output

```fontSize``` (and probably all the other parameters like ```fontWeight```) don't work in PIXI 3. 

This is of course not a bug, but it creates a lot of migration issues for us. Most of it is because bit of our code are shared between games (in form of a library with components) and I was hoping to first update the shared code and then all games one by one. Since fontSize doesn't work in older PIXI version though I would now either have to live with a console full of migration warnings and only update once all our games are on the new version (which might be never) or update all games at the same time (that's even less likely to work).

Suggestion: Could we backport the new font parameters to PIXI 3? This would make migrating games a lot easier and allows people to do these preparations in advance of the actual switch.

**Comment by englercj** [comment]
Closing this, unfortunately we will not be rewriting Text in v3. We do alot of work to make our migrations to new major versions as easy as possible; I recommend trying that out.

Thanks!

**Comment by marekventur** [comment]
Ok. We have started writing a wrapper around FontStyles that handles both versions, so we'll probably use that insteead.
