### ISSUE TITLE
iOS 10 Chrome - Pixi (v3.0.10 +) fails to load videos

### ISSUE THREAD

**Issue by diddykong13** [pixijs/pixi.js#2888]
If you try and load a video (.mp4) on the current iOS beta using the Chrome browser it will fail to load and cause knock-on issues.

To see the effect, try loading: http://pixijs.github.io/examples/#/basics/video.js in chrome on a device running iOS 10.

I am unable to debug on chrome iOS so I cannot provide any more detailed information about where it is failing.

**Comment by ivanpopelyshev** [comment]
Which audio does it have, mp3 or aac?

**Comment by diddykong13** [comment]
The audio type is AAC on that test video from the examples page. (The same as the videos that I'm trying to use)

**Comment by themoonrat** [comment]
Once https://github.com/pixijs/pixi.js/issues/2979 is fixed, https://github.com/pixijs/pixi.js/pull/2982 should help.
I have found on my personal tests, however, that the new ios10 autoplaying of videos works in Safari, but not any other browsers in iOS :/ Cheers Apple.

**Comment by englercj** [comment]
Since #2982 is merged, I'm going to close this in favor of tracking via #2979.

Thanks!
