### ISSUE TITLE
Any Tips for customized PIXI builds?

### ISSUE THREAD

**Issue by chipbell4** [pixijs/pixi.js#2889]
From what I can tell, the PIXI 4 build is about the same size as PIXI 3, which is awesome. However, it's still pretty hefty which can be a burden on weaker mobile devices. What would be the easiest way to get custom builds to perhaps remove certain components to streamline file size? As a lot of these SpringRoll games end up on mobile, I'd love to be able to optimize exactly which PIXI features are included for that game to squeeze every bit of performance out of the device.

**Comment by chipbell4** [comment]
Oops, just saw this: https://github.com/pixijs/pixi.js/issues/2343

Nothing to see here...

**Comment by ivanpopelyshev** [comment]
remove the extras, remove CanvasRenderer and canvas-related things.
