### ISSUE TITLE
PIXI v4 sprite render show only black object

### ISSUE THREAD

**Issue by HejdukV** [pixijs/pixi.js#2890]
PIXI v 4.0.0 render sprite as black object without colors on Adnroid 5.1.1 (tested on Samsung Galaxy Core Prime). Everything is OK with PIXI v 3.0.11. You can see that it occurs also on examples from Pixi webpage:

**PIXI v4.0.0:**
![pixi_v4_screenshot](https://cloud.githubusercontent.com/assets/21368706/18142716/20e2aa2c-6fbf-11e6-8246-253eb5654a5f.png)

**PIXI v3.0.11:**
![pixi_v3_screenshot](https://cloud.githubusercontent.com/assets/21368706/18142717/20e30cb0-6fbf-11e6-8980-364aa1eb3b47.png)

**Comment by englercj** [comment]
Are you using the WebGL Renderer? If so does changing adding this before you create anything help?

```
PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;
```

**Comment by HejdukV** [comment]
- Yes, I am using WebGL renderer. 
- No change with FORCE_NATIVE, still have same black textures.

**Comment by HejdukV** [comment]
Same behaviour on v 4.1.0

**Comment by englercj** [comment]
Do you get any console errors or warnings?

**Comment by HejdukV** [comment]
Unfortunately no

**Comment by HejdukV** [comment]
It looks like this issue was resolved between version 4.1.1 and 4.2.1. Actual version (4.3.4) is also OK.

**Comment by GoodBoyDigital** [comment]
@HejdukV great news 👍
