### ISSUE TITLE
Spritesheet renders incorrectly with filter

### ISSUE THREAD

**Issue by dakom** [pixijs/pixi.js#2891]
See http://storage.googleapis.com/tjandpals-temp/pixi-temp/pixi-filter-test/index.html

Applying a filter to a texture which was loaded via Animate CC spritesheet fails[*] when using current dev branch of PIXI. It works fine when using master branch. Also works fine when using other spritesheets (for example figher pilot from pixi.js examples page)

[*] fails meaning it seems to be grabbing mixing in data from other cells or something

**Comment by dakom** [comment]
I was also able to duplicate the problem by using ShoeBox as the spritesheet generator, e.g. with this spritesheet: 
[items.zip](https://github.com/pixijs/pixi.js/files/455951/items.zip)

**Comment by dakom** [comment]
Note that the same bug also happens with native PIXI filters or even just a basic filter with default vert/frag shaders

**Comment by ivanpopelyshev** [comment]
That's the real bug here

**Comment by dakom** [comment]
true, I didn't realize it till now - I just assumed the native filters were working ;)

**Comment by dakom** [comment]
I think I'm also seeing the bug outside of spritesheets... :(

**Comment by ivanpopelyshev** [comment]
Something-something premultiplied alpha?

**Comment by dakom** [comment]
I think you're onto something with that, can you be a little more specific? I've stripped the example down to just use PIXI.Filter() (no custom shader etc.) and also used latest build from master. Republished at same url (http://storage.googleapis.com/tjandpals-temp/pixi-temp/pixi-filter-test/index.html) - you'll see when the filter is applied, it still has that affect - though the image goes darker too...

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital https://github.com/pixijs/pixi.js/blob/master/src/core/renderers/webgl/utils/RenderTarget.js#L227

```js
    if(this.destinationFrame !== this.sourceFrame)
    {

        gl.enable(gl.SCISSOR_TEST);
        gl.scissor(this.destinationFrame.x | 0,this.destinationFrame.y | 0, (this.destinationFrame.width * this.resolution) | 0, (this.destinationFrame.height* this.resolution) | 0);
    }
    else
    {
        gl.disable(gl.SCISSOR_TEST);
    }
```

That's the problem. Scissor must be done by sourceFrame, not by destionationFrame.

```js
if(this.sourceFrame && (this.sourceFrame.width !== this.size.width ||
        this.sourceFrame.height !== this.size.height))
    {

        gl.enable(gl.SCISSOR_TEST);
        gl.scissor(0, 0, (this.sourceFrame.width * this.resolution) | 0, (this.sourceFrame.height * this.resolution) | 0);
    }
    else
    {
        gl.disable(gl.SCISSOR_TEST);
    }
```

**Comment by dazld** [comment]
Just want to add that I'm seeing blur filters cropping their parent sprite and padding not working at all, which looks quite similar. Padding is actually cropping the original sprite, which doesn't seem right. Any ideas?

![shaker](https://cloud.githubusercontent.com/assets/201036/18635294/d2622aa6-7e84-11e6-9425-24a4a1d8f08e.gif)

**Comment by ivanpopelyshev** [comment]
@dazId try https://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js ?

**Comment by dazld** [comment]
thanks @ivanpopelyshev will do. does this look like a known issue..?

**Comment by ivanpopelyshev** [comment]
yes, it looks like that, there were filter fixes last week.

**Comment by dazld** [comment]
@ivanpopelyshev tried this, and that's much better, thank you. 

One thing still buggy however. when the blur is being progressively changed (and hence the padding too), the image seems to jump around. With a fixed padding value, this does not happen, but obviously the blur clips then at some point. Here's an example:

![shaker](https://cloud.githubusercontent.com/assets/201036/18661229/f8312f30-7f14-11e6-993b-0f97127222d3.gif)

And with fixed value for padding:

![shaker-fixed](https://cloud.githubusercontent.com/assets/201036/18661233/ffb4c302-7f14-11e6-843b-3a457bdc6240.gif)

**Comment by GoodBoyDigital** [comment]
Hello! This is fixed in the latest branch 👍
