### ISSUE TITLE
Invalid handling of mouse input events when cacheAsBitmap is used with canvas renderer.

### ISSUE THREAD

**Issue by marooou** [pixijs/pixi.js#2895]
The bug occurs when we want to cache as bitmap a container
which has interactive children and some x/y transition applied to it.
The position of the cursor seems to be miscalculated during children hit tests (invalid transformation matrices).
This only happens in canvas renderer and works fine in WebGL.

**Comment by GoodBoyDigital** [comment]
nice thanks for this @marooou 👍
