### ISSUE TITLE
[question] Using meshes in Pixi compared to conventional WebGL - I'm slightly confused!

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#2897]
I'm working on a 2D game, for which I'd like to use meshes.

The syntax is `new PIXI.mesh.Mesh(texture, vertices, uvs, indices, drawMode)`.

For the `vertices`, can I just provide sets of (X,Y) coordinates or do I have to include the Zs? If so, is there any way to disable the Z coordinates? (I'm asking because this would reduce mesh size by 1/3rd.)

Also, Wwith WebGL, I am used to proving an array of (position) vertices and an array of coordinates for textures (to use with a sprite sheet). Where does the texture coordinates array go? I seem to only see a `vertices` argument, which I guess is for position.

Thank you!

**Comment by ivanpopelyshev** [comment]
XY, please look into PIXI.mesh.Rope sources, it uses TriangleStrip. for yourmesh it can be the other mode

**Comment by DubiousDillan** [comment]
It took me a while but I got there eventually. Thank you!
