### ISSUE TITLE
[Working] PIXI v4 DropShadowFilter conversion

### ISSUE THREAD

**Issue by MrChampion** [pixijs/pixi.js#2899]
I've been trying to convert DropShadowFilter to the PIXI v4 format, but it seems something changed on the RenderTarget logic that the filter seems to be applied to the previous renderTarget instead of the input source? Even with the VoidFilter.

Changing the order of the default filter preserves the input renderTarget, but then the composite has the drop shadow on top of it...

Can anyone give me a hint as to what I am doing wrong?

https://jsfiddle.net/8k7fd0on/

**Comment by bigtimebuddy** [comment]
This work has already begun here: https://github.com/pixijs/pixi-filters/pull/9

**Comment by MrChampion** [comment]
It seems to be the same or behind the first test fiddle conversion.
pixijs/pixi-filters#9: https://jsfiddle.net/ekdo9w4g/6/
test fiddle: https://jsfiddle.net/8k7fd0on/

Am I missing something there?

**Comment by MrChampion** [comment]
Ok, I've update my conversion Fiddle.
It was a derpy error, i had inverted the filterManager with the filter in the apply function...

Working Version:
https://jsfiddle.net/7cv0qu7c/6/

**Comment by alexfoxy** [comment]
Is this still working? I'm having trouble getting the shadow to blur, it's just solid?

**Comment by englercj** [comment]
In case people were still working on this, I've updated the jsfiddle to use the latest dev version of pixi. Seems OK, but I'm not 100% sure what the desired effect is.

https://jsfiddle.net/7cv0qu7c/17/

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
