### ISSUE TITLE
Merge quadraticCurveTo and bezierCurveTo?

### ISSUE THREAD

**Issue by fschutt** [pixijs/pixi.js#2900]
Hi,

I wanted to ask what the difference is between quadraticCurveTo and bezierCurveTo. Looking in the source code (src/core/graphics.js Line 298 and beyond), I was wondering what the difference between these two is. Because quadraticCurveTo does the exact same thing, except it doesn't call the function in bezierCurveTo.js.

What I originally intended to do was to move the bezier function from a "20 points on each line" incremental method to a distance-and-angle based approach (since the incremental approach looks very bad on curves).

My original change (not commited yet, bezierCurveTo.js):

```

/**
 * Calculate the points for a bezier curve and then draws it.
 *
 * Ignored from docs since it is not directly exposed.
 *
 * @ignore
 * @param fromX {number} Starting point x
 * @param fromY {number} Starting point y
 * @param cpX {number} Control point x
 * @param cpY {number} Control point y
 * @param cpX2 {number} Second Control point x
 * @param cpY2 {number} Second Control point y
 * @param toX {number} Destination point x
 * @param toY {number} Destination point y
 * @param thresh {number} Threshold between two points
 * @param [path=number[]] Path array to push points into
 * @return {PIXI.Graphics}
 */
var bezierCurveTo = function (fromX, fromY, cpX, cpY, cpX2, cpY2, toX, toY, thresh, path) // jshint ignore:line
{
    //Old formula

    path = path || [];

    //Only call new code when thresh is set, compatability
    if (thresh)
    {
        var threshSq = thresh * thresh;

        path.push(fromX, fromY);
        path.push(subdivideQuadraticBezier(fromX, fromY, cpX, cpY, cpX2, cpY2, toX, toY, threshSq));
        path.push(toX, toY);
        return path;

    }else{
        var n = 20,                 //Maximal Points in the curve
            dt,
            dt2,
            dt3,
            t2,
            t3;

        path.push(fromX, fromY);    //First Point

        var j = 0;

        for (var i = 1; i <= n; ++i)
        {
            j = i / n;              //Percentage of Point from to Point cp

            dt = (1 - j);           //Percentange of Point cp to Point to
            dt2 = dt * dt;
            dt3 = dt2 * dt;

            t2 = j * j; 
            t3 = t2 * j;

            //Cubic Bezier formula
            path.push(dt3 * fromX + 3 * dt2 * j * cpX + 3 * dt * t2 * cpX2 + t3 * toX,
                      dt3 * fromY + 3 * dt2 * j * cpY + 3 * dt * t2 * cpY2 + t3 * toY);
        }

        return path;
    }
};


function subdivideQuadraticBezier(fromX, fromY, cpX, cpY, cpX2, cpY2, toX, toY, threshSq) // jshint ignore:line
{

    //de Casteljau algorithm for recursively subdividing bezier curves
    //Credit to Maxim Shemanarev
    //see http://antigrain.com/research/adaptive_bezier/
    //It would be better to implement this directly in WebGL instead of JS

    //Calculate midpoints
    var x12   = (fromX + cpX) / 2;
    var y12   = (fromY + cpY) / 2;
    var x23   = (cpX + cpX2) / 2;
    var y23   = (cpY + cpY2) / 2;
    var x34   = (cpX2 + toX) / 2;
    var y34   = (cpY2 + toY) / 2;

    var x123  = (x12 + x23) / 2;
    var y123  = (y12 + y23) / 2;
    var x234  = (x23 + x34) / 2;
    var y234  = (y23 + y34) / 2;
    var x1234 = (x123 + x234) / 2;
    var y1234 = (y123 + y234) / 2;

    //Calculate distance
    var dx = toX - fromX;
    var dy = toY - fromY;

    var d2 = Math.abs(((cpX - cpX2) * dy - (cpY - cpY2)));
    var d3 = Math.abs(((cpX2 - toX) * dy - (cpY2 - toY)));

    //Shorter than threshold and the difference in X or Y is one pixel or less (unnoticable)
    if (((d2 + d3) * (d2 + d3) < threshSq * (dx * dx + dy * dy)) || (dx < 1) || (dy < 1)) {
        //Return midpoint
        var point = [x1234, y1234];
        return point;
    }else{
        //First half of curve
        subdivideQuadraticBezier(fromX, fromY, x12, y12, x123, y123, x1234, y1234, threshSq);
        //Second half
        subdivideQuadraticBezier(x1234, y1234, x234, y234, x34, y34, toX, toY, threshSq);
    }
}

module.exports = bezierCurveTo;
```

Yes, there is room for improvement, I have not yet made anything regarding the angle or detecting cusping of paths. However, my question is regarding the structure of the source code. If I wanted to call this method with `graphics.quadraticCurveTo(120, 1000, 350, 330);`, what and where would I need to change something? So far, I would change quadraticCurveTo to use the function in bezierCurveTo.js and later on change CanvasMaskManager and CanvasGraphicsRenderer to adapt to this.

What I also wanted to discuss is if it would make sense to move bezierCurve into its own class. The reasons for doing so:
- It allows access to the vector handles. This is important if you are building a vector editor (like me) and don't want to calculate everything twice
- It allows for different (optional) methods of calculating. The default would be cubic, but we could also specify linear and quadratic
- bezierCurveTo should be generalized as much as possible (for example instead of taking two control points, you could dump an array of control points into it). I do not know how this would work with the existing code and batching functions.
- The resolution of the curve should always, always be dependent on the length of the curve. For example, I want to draw thousands of shapes on the screen (maps, to be exact). If every bezier curve is stuck at 20 points per curve, this will severely impact performance. I also wanted to implement some kind of "performance level" (like the one in InDesign, where it chooses "low" if you are zoomed out very far.

So yeah that was what I was thinking about:
- Make bezierCurve a more general function for all kinds of bezier curves
- Make accessor functions for vector handles
- (Maybe) move the bezierCurve subdividing function into a shader (tesselation, or just ins and outs). Would be much, much faster than doing it in JavaScript (CPU).

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
