### ISSUE TITLE
Access the context of the WebGL renderer

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#2901]
I'd like to access the context of the WebGL renderer, in order to patch a bug (that I commented on in another ticket and on how to solve it).

Could I access it somehow?

**Comment by englercj** [comment]
https://github.com/pixijs/pixi.js/blob/master/src/core/renderers/webgl/WebGLRenderer.js#L120

**Comment by DubiousDillan** [comment]
Got it. Thank you!
