### ISSUE TITLE
Make it more intuitive to smooth textures

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#2902]
Using the WebGL renderer (canvas untested):

When I set the base texture to use nearest neighbour interpolation, it works, _except when a child container has `cacheAsBitmap = true`_ (in which case it renders aliased textures), which is a massive problem because of the performance.

This took ages to find (by chance)- I hope that I've been helpful!

**Comment by DubiousDillan** [comment]
I fixed this by changing the scale mode on the cached image.

**Comment by kaansoral** [comment]
Is this what you do too? `PIXI.utils.BaseTextureCache[file].scaleMode=PIXI.SCALE_MODES.NEAREST;`

Maybe share your solution so others can benefit too

**Comment by GoodBoyDigital** [comment]
Let's make it easier to smooth textures! Will keep this open as a reminder !

**Comment by DubiousDillan** [comment]
@kaansoral I did, although in writing. The code is `PIXI.SCALE_MODES.DEFAULT = PIXI.SCALE_MODES.NEAREST`.
@GoodBoyDigital lets make it easier to find out how to smooth textures :p
Once it found it, it was a one liner.

**Comment by kaansoral** [comment]
```
canvas{
	image-rendering: optimizeSpeed;
	image-rendering: -moz-crisp-edges;
	image-rendering: -webkit-optimize-contrast;
	image-rendering: optimize-contrast;
	image-rendering: pixelated;
	-ms-interpolation-mode: nearest-neighbor;
}
```

This also works in Chrome, which is pretty interesting (interesting to someone who doesn't know how *exactly* things fit together)

**Comment by ivanpopelyshev** [comment]
"default" must mean "its up to renderer". make "DEFAULT=2" that  will work with old and new code.

**Comment by GoodBoyDigital** [comment]
Hello!

To set the smoothing of a cached as bitmap texture you can do the following:

```myCachedAsBitmapElement._cacheData.sprite.baseTexture.scaleMode=PIXI.SCALE_MODES.NEAREST;```

Is that cool?

Let me know if not and I will reopen.
