### ISSUE TITLE
mouseover/out on a moving object

### ISSUE THREAD

**Issue by Dadibom** [pixijs/pixi.js#2903]
Mouseover/out does not work with moving objects (when not moving the mouse)
So for example, if I click on an object and my character starts moving towards it, the camera will move causing the cursor to leave the object, but the out event will never be triggered.

Also, I would love to have touchover/out too.

**Comment by ivanpopelyshev** [comment]
I would like to see firrst succesfull touchover implementation.

**Comment by Dadibom** [comment]
It's for a point and click game! I'm currently using mouseover/out for displaying descriptions of whatever the user hovers over. I would like to be able to just drag across the screen on mobile devices to see these descriptions!

**Comment by GoodBoyDigital** [comment]
interesting stuff! We will make sure to take a look into that for ya!

**Comment by themoonrat** [comment]
Hi @Dadibom - I created a basic example based on another of your fiddle with a moving object, but it seems to work ok. Is there anything you could do to to the fiddle to demonstrate your issue please?
https://jsfiddle.net/jxwwnjuh/1/

**Comment by Dadibom** [comment]
https://jsfiddle.net/vakwar4d/1/
Click it and don't move the mouse

**Comment by themoonrat** [comment]
Doesn't go wrong here :/

**Comment by Dadibom** [comment]
It's very important that you don't move your mouse at all after the click. I made it easier here
https://jsfiddle.net/vakwar4d/2/

**Comment by themoonrat** [comment]
Still not seeing anything wrong, and now I'm getting weird looks from the guy sitting opposite me for clicking my mouse in the air! I'll take a look on a different PC at another time.

What are you seeing happening wrong in that example, for absolute clarification?

**Comment by Dadibom** [comment]
after the click has been made, the internet exploder icon will move away from the cursor without the mouseout event triggering

**Comment by Dadibom** [comment]
Using chrome 52.0.2743.116 (64-bit) on ubuntu 16.04

**Comment by Dadibom** [comment]
It also happens on edge, but not on w10 w/ chrome 53.0.7.x

**Comment by themoonrat** [comment]
FYI, I too see it on Edge on my home Windows 10 PC.
It appears that stopPropagation() on an object in Edge is stopping different event types from being dispatched - in your case, the mouseover / mouseout.

I have a fix that works for me, but will as ever need checking over :)

**Comment by themoonrat** [comment]
https://jsfiddle.net/gzdwt3p6/1/ could you check that this does work for you please :)

**Comment by Dadibom** [comment]
Yes, it works :)

**Comment by englercj** [comment]
Fixed by #2929.

**Comment by Dadibom** [comment]
Not fixed (4.0.2/4.0.3)

**Comment by englercj** [comment]
That fix isn't in those releases, it is however in the latest `dev` build (v4.1):

http://pixi-builds.s3-website-eu-west-1.amazonaws.com/dev/pixi.js

Let me know if that doesn't work.

**Comment by Dadibom** [comment]
Doesn't even run :(
 Pixi.js 4.0.3 - âœ° WebGL âœ° 
pixi.min.js?4:12324 Uncaught TypeError: this._spriteRect.onAnchorUpdate is not a function

**Comment by themoonrat** [comment]
@Dadibom  - try again now, same link, should work!

**Comment by Dadibom** [comment]
Error: Invalid image type in URL.
    at BaseTexture._updateImageType (http://xxxx/js/pixi.js?4:22379:23)
    at HTMLImageElement.source.onload (http://xxxx/js/pixi.js?4:22283:27)

(url: "src/img/../img/npc/xxxx.png?v=0.4.0.R42180")

**Comment by englercj** [comment]
That does seem related to the interaction manager all. I think that is a different error.

**Comment by Dadibom** [comment]
Yeah, but I can't even run that build because of it

**Comment by englercj** [comment]
Lets track this on a separate issue, please: #3059
