### ISSUE TITLE
Creating Sprite Objects - Strange Behaviour

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#2905]
I have a `Texture`.

I set the frame of the texture to a new rectangle.

I create multiple `Sprite` objects using the `Texture`, with different frames.

When I change the frame of the `Texture`, it affects ALL sprites? Why? How are we supposed to use spritesheets like this?

I learnt how to do this by reading https://github.com/kittykatattack/learningPixi

I'd like to be able to draw the same sprite, in a spritesheet, multiple times but am finding it incredibly difficult to understand how.

Thanks!

**Comment by DubiousDillan** [comment]
Small update: if I set the frame of the sprites instead, my FPS drops a lot and my entire computer lags horrible but it does work.

**Comment by kaansoral** [comment]
You can create an individual texture for each frame, then use those textures and change the texture of Sprite's

**Comment by DubiousDillan** [comment]
@kaansoral thank you, that worked!
