### ISSUE TITLE
Re-cache container with cacheAsBitmap=true

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#2907]
I have a container, with `cacheAsBitmap = true` set.

When I add some children to it, it does not change at all- it's not getting re-cached.

When I set `cacheAsBitmap = false`, the children do appear/disappear when added/removed, so it's definitely due to this.

How does one tell a container to re-cache?

**Comment by ivanpopelyshev** [comment]
I dont understand why do you need cacheAsBitmap at the first place. Set to false, then to true, that's how it works. 

My PR's regarding this things were rejected, @GoodBoyDigital will help you better than me :)

**Comment by DubiousDillan** [comment]
@ivanpopelyshev, that worked, thanks!
However, I find it really strange how the library picked up on the fact that I had changed it to `false` and then `true` immediately afterwards.
