### ISSUE TITLE
mask size doubles when applying filter [iOS]

### ISSUE THREAD

**Issue by blancoberg** [pixijs/pixi.js#2909]
When applying a filter to a masked object, the mask doubles in size. 
jsfiddle here :  https://jsfiddle.net/x58h7kaz/6/

**Comment by blancoberg** [comment]
I forgot to mention; this bug appears on iOS. on desktop it works as it is suppose to.

**Comment by GoodBoyDigital** [comment]
Hello there! Thanks for reporting the bug and providing the fiddle too! Will let you know when this has been addressed 👍

**Comment by GoodBoyDigital** [comment]
Hi @blancoberg looks like its working for me on IOS - would you mind elaborating on this issue?
I tested on my IPhone 5s i see the black rectangle and it does not change. Cheers!

**Comment by blancoberg** [comment]
I recently updated to iOS 10 and it seem to be working fine now. I don't remember what version I had before unfortunately :/

**Comment by GoodBoyDigital** [comment]
sweet! It may be that dev branch was updated i the interim too. Either way, glad to hear its working for you 👍

**Comment by blancoberg** [comment]
Yup! pretty sweet! :) thanks for looking into it.
