### ISSUE TITLE
cacheAsBitmap on Graphics not working correctly when width/height accessed

### ISSUE THREAD

**Issue by aidangrabe** [pixijs/pixi.js#2910]
Hello again :)

My Graphics object position is ignored when `cacheAsBitmap` is set to `true` and `object.width` is accessed within an animate loop.

* In the linked fiddle, the red square gets drawn at 0,0 instead of 100, 100.
* If you comment out `square.cacheAsBitmap = true`, the square gets drawn correctly.
* If you comment out `square.width` in the animate loop it also gets drawn correctly. (same happens for `square.height`.
* If you also comment out `requestAnimationFrame(animate)` the square is correctly drawn.

Tested on `v4` and `dev`

Tested on Chrome 52 and Firefox 48
Fiddle: https://jsfiddle.net/Lmmjzots/1/

**Comment by endel** [comment]
Might have some relation with https://github.com/pixijs/pixi.js/issues/2823

**Comment by GoodBoyDigital** [comment]
Hello there! Thanks for reporting the bug and providing the fiddle too! Will let you know when this has been addressed 👍

**Comment by GoodBoyDigital** [comment]
Should be fixed in dev branch no 👍 (you may need to rebuild the project though) 
Thanks again for sharing @endel !
