### ISSUE TITLE
Edge and Chrome throw a "the spinedata param is required" error

### ISSUE THREAD

**Issue by DSPiron** [pixijs/pixi.js#2911]
I don't know what else I should say about this...
Using pixi v3.0.10
It appears to work with Firefox.

**Comment by ivanpopelyshev** [comment]
Well, first - its about pixi-spine. Second - You didn't even make it past example. http://pixijs.github.io/examples/index.html?s=basics&f=container.js&title=Container&v=dev#/spine/dragon.js works just fine

**Comment by ivanpopelyshev** [comment]
added some examples for you

**Comment by DSPiron** [comment]
...
Yeah, that this is about pixi-spine is probably a pretty crucial detail.
And it would probably help to explain what exactly I'm doing:
I'm trying to get a copy of the example to run on it's own page, (locally, on my machine).

I think I implemented it correctly, but I also updated the Pixi.js to v4 before testing the code that was posted. And also I didn't recognize that the line of code was an example of what not to do, in the first place.

The example code pretty much resembles your examples, and changing it look closer to yours has no effect. (unsurprisingly, as I'm pretty such using the example javascript code. )
...Sorry I wasn't clear before.

**Comment by ivanpopelyshev** [comment]
Fortunately, pixi-spine works with both v3 and v4. What web-server do you use to host the app?

**Comment by DSPiron** [comment]
...web-server?

...I think I found my problem: I'm a total noob, and I didn't use a web server, and thus Edge and Chrome deny access to the JSON files.

tch.

**Comment by ivanpopelyshev** [comment]
Yeah, I'm a telepath :)

Next time please look if there's something strange in the console. For web-server i recommend install node.js, then do this thing in command line:

```bash
#one time
npm install -g http-server
#each time you want to launch a server in a folder, "-c-1" is "expire:no-cache"
http-server -c-1 
#if you want another port, not 8080
http-server -c-1 -p8081
```
