### ISSUE TITLE
mouseover triggered outside of canvas

### ISSUE THREAD

**Issue by Dadibom** [pixijs/pixi.js#2914]
The mouseover/out events are triggered even when the mouse is outside the canvas (hovering over offscreen objects)

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by Dadibom** [comment]
https://jsfiddle.net/so56a1y7/1/

**Comment by themoonrat** [comment]
Looking at now.
The mousemove event listener used to be on the interactionDOMElement, but got moved to the window for https://github.com/pixijs/pixi.js/issues/1564

In your fiddle, I would say that 'mouseover' event should be suppressed if you hover over where the image would be outside of the canvas, but that 'mouseout' _should_ be sent if you go from hovering over the image inside of the canvas, to hovering over the where the image would be outside of the canvas.

Thoughts?

**Comment by Dadibom** [comment]
Yes. And if possible, the mouseover event should also be triggered if the mouse moves from inside the border but outside the canvas into the border inside the canvas. If that makes any sense, lol

**Comment by themoonrat** [comment]
Yeps, gotcha

**Comment by themoonrat** [comment]
https://jsfiddle.net/sx1tcy2q/6/

I've seen one problem (which may or may not be a problem, advice welcome) - Your previous jsfiddle had a red box over the canvas, over the sprite... which means the render canvas wasn't 'in focus' and thus stops the mouse over from happening.

https://jsfiddle.net/sx1tcy2q/4/

**Comment by Dadibom** [comment]
The one I made: https://jsfiddle.net/so56a1y7/1/ works for me, but the identical one you posted: https://jsfiddle.net/sx1tcy2q/4/ doesn't. Very strange. But yeah, it was just to show where the sprite was

**Comment by themoonrat** [comment]
Both of those fiddles are with my libs change to show you it's effects :)

/4/ is with a div overlay
/6/ is without

With my change... a div overlay on top of the canvas would not allow sprites underneath it to have a mouseover. Not sure if this is desired behaviour or not!

**Comment by Dadibom** [comment]
OOooooooh. That's fine! :)

**Comment by themoonrat** [comment]
Put up an alternate version that does work with overlayed divs... I'll let @GoodBoyDigital decide which option to take!

**Comment by englercj** [comment]
Merged #2996.

**Comment by Dadibom** [comment]
Not fixed (4.0.2/4.0.3)

**Comment by englercj** [comment]
That fix isn't in those releases, it is however in the latest dev build (v4.1):

http://pixi-builds.s3-website-eu-west-1.amazonaws.com/dev/pixi.js

Let me know if that doesn't work.
