### ISSUE TITLE
Graphics.cacheAsBitmap bug

### ISSUE THREAD

**Issue by blancoberg** [pixijs/pixi.js#2915]
Hi!
PIXI crashes when trying to access width or height of an Graphics object that has its property .cacheAsBitmap set to true.

Error message:
pixi.js:10011 Uncaught TypeError: Cannot read property 'transform' of null

Fiddle:
https://jsfiddle.net/9j1LdaLm/4/

**Comment by whizzkid** [comment]
only if it hasn't been added to stage.

**Comment by GoodBoyDigital** [comment]
nice! thanks for sharing @whizzkid

**Comment by blancoberg** [comment]
@whizzkid hm, I'm not sure that is the only scenario. I still having the same problem with a site i'm working on. ( Even with a parent)
I'm really not sure what is causing this, as I have two almost identical fiddles. One is working and the other on is not. 

In this example, I have extended the PIXI.Container class, which is causing the cacheAsBitmap bug for some reason:
https://jsfiddle.net/2jb7qr7z/5/

In this example I have extracted the functionality from my extended class, and some how it works. I have no idea what is going on here :) It is literally the same functions:
https://jsfiddle.net/9j1LdaLm/8/

Is it a bug or am I doing something wrong here?

**Comment by whizzkid** [comment]
Looks like 2 different bugs to me.

p.s. If you use the normal version of pixi instead of the minified one (remove the .min ) 
you can get a little more info by expanding the error in your console window.

**Comment by blancoberg** [comment]
@whizzkid thanks for the tip!
I get this error message: Container.js:397Uncaught TypeError: this._calculateBounds is not a function,
which is weird, since that is an empty function that is called within the PIXI.Container class ( apperantly it isnt used for anything at the moment). How is that even possible? :)

Am I missing something when extending the PIXI.Container class?

**Comment by whizzkid** [comment]
Nope, its a bug :)   (or... 2 most likely)

**Comment by GoodBoyDigital** [comment]
All sorted now. Thanks for sharing the issue! 👍 
Appreciate the fiddle too, always makes our life easier :D
