### ISSUE TITLE
when number of sprite increased,the browser Become Caton

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#2916]
when number of sprite increased,the browser Become Caton and  Performance degradation,because my project need many sprite,this cause render interval is too long

**Comment by themoonrat** [comment]
This is a duplicate of your previous issue 
https://github.com/pixijs/pixi.js/issues/2892
Please reply to the suggestions and comments made there; for example, the last suggestion was reducing the number of interactive sprites you have

**Comment by GoodBoyDigital** [comment]
good point! @themoonrat closing this as this is a duplicate.
