### ISSUE TITLE
Pixi.js v4 + cocoon.js causing black screen.

### ISSUE THREAD

**Issue by aux-lux** [pixijs/pixi.js#2924]
Hi,
I tried to upgrade pixi.js from 3 to 4 on my mobile game. However using v4 effects black screen on mobile (android).

**Comment by englercj** [comment]
Any errors reported?

**Comment by themoonrat** [comment]
I believe I have a PR that will fix this issue: https://github.com/pixijs/pixi.js/pull/2946

**Comment by aux-lux** [comment]
@englercj I'm not the best mobile debugger ;) however I can see @themoonrat found the solution, so I'll try it when new build will be released and let you know if it will fix this issue. Thank you for help.

**Comment by aux-lux** [comment]
Hi, I added @themoonrat fix to pixi v4 file, and it didn't fixed mine issue :(
I'm still getting black screen after cocoon splash. Tried to use cocoon developer app for debugging with zip I get from them, but I get error about finding file://null/ (even with working app using pixi v3) So right now I'm not sure what I can say, I'll just try to test and debug it more, somehow. Because right now mine issue sounds like "It's not working and I don't know why".

**Comment by englercj** [comment]
Well something is trying to load that file and causing your error. I don't think this is a pixi issue.

**Comment by aux-lux** [comment]
@englercj Don't get me wrong, this file null issue is related to being not able to debug it.
I have 2 versions of game. With pixi v3 working, and pixi v4 not working on mobile. But they both throw this error on debugger. What I wanted to say is that I have hard time debugging it, but issue is after swapping pixi version.

**Comment by aux-lux** [comment]
Ok, finally solved. Did so many mistakes during all the tests, but now it's all clear :)
#1 pasted themoonrat fix inside maxRecommendedTextures instead of AccessibilityManager
#2 cocoon dev application isn't using zip they generate after compiling, but actual game source zip.

The reason of issue #1 was that canvas+ don't have DOM or has it reduced, so hookDiv.style was saying that there is no "style" :)

So sorry for that mess, and I think you can close it, because @themoonrat fix actually does the job.
I noticed that over the internet there was 1 more person that had issue with file://null/ , I'll let him/her know what could go wrong :D

**Comment by englercj** [comment]
Fixed by #2946
