### ISSUE TITLE
Creating texture from SVG elements not on SVG image. 

### ISSUE THREAD

**Issue by Hidejec** [pixijs/pixi.js#2927]
I created a new Sprite as an SVG image and want to change some contents of the SVG. Now that I achieved changing the contents of an SVG image, I want to Sprite.setTexture(svg) from it. This time the svg is an xml element and not saved as an image file. How to do that please help. 
Sorry for my english.

**Comment by RanzQ** [comment]
@Hidejec I'm currently working on a better SVG support, this might be easier in future. Anyway, a hack like this might work:

1. After modifications, convert you SVG element into string using [XMLSerializer](https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer)

2. Create texture from data url:
```
var texture = PIXI.Texture.fromImage('data:image/svg+xml;utf8,' + serializedSvg)
```
While base64 data urls work too, SVG strings are smaller without base64 conversion.

Afaik this doesn't work in IE though.
