### ISSUE TITLE
SVG doesn't work in IE 11 with WebGL

### ISSUE THREAD

**Issue by RanzQ** [pixijs/pixi.js#2928]
SVG support seems to be broken in IE 11, (v3, master and dev). Edge works and IE10 works due to canvas fallback. Noticed while developing the [PR](https://github.com/pixijs/pixi.js/pull/2614).

v3: https://codepen.io/RanzQ/pen/PGqRma
master: https://codepen.io/RanzQ/pen/rrVJoP
dev: https://codepen.io/RanzQ/pen/bwdLOv

No errors, the sprite just won't show up.

This message comes up but it can be removed with `transparent: true`:
```
WEBGL11135: getContext: Context attribute premultipliedAlpha:false is not currently supported
```

I'll see if my PR fixes this. Created an issue since I first thought I broke it myself.

**Comment by GoodBoyDigital** [comment]
Thanks for sharing @RanzQ 👍 
Let me know if you PR fixes this one!

**Comment by RanzQ** [comment]
This doesn't occur on Edge but on IE11. Forgot they are not the same thing. :)

An invalid SecurityError is thrown when using svg images on canvas or with WebGL. MS issue can be tracked here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/110935/

**Comment by englercj** [comment]
Looks like (from that issue) that they fixed it in Edge but aren't porting it back to IE11. That is most unfortunate...
