### ISSUE TITLE
Something about InteractionManager.eventData

### ISSUE THREAD

**Issue by Neugls** [pixijs/pixi.js#2931]
Currently this is a property named target in the eventData, and InteractionManager have implemented the events bubble like way

When user click a object, InteractionManger loops all the objects and it's children to find the deepest object the user click on, then the object dispatch a event with target set to this object event, and then set the event target to parent,  parent dispatch a mouse event, and so on.

So, If  a event listener is added on the world parent object,  the world parent will receive the mouse event, with target set to itself, but not the leveled child object, so, there is no way to know which object is actually clicked in the event.

In ActionScript3, the event class Event have two properties, currentTarget, target. the currentTarget is which object the event is bubbled to, the target is which object is actually clicked and dispatched the event.

So I think Pixi.js can also implements this structure, this may very useful

I love pixi.js, hope it will be better and better.
Thank you.

**Comment by GoodBoyDigital** [comment]
Thanks for sharing @Neugls and thanks for your kind words too! This is a great idea 👍

**Comment by themoonrat** [comment]
@englercj I believe this can be closed after https://github.com/pixijs/pixi.js/pull/2828 was merged
