### ISSUE TITLE
anchor = new Point breaks the render

### ISSUE THREAD

**Issue by mathieuanthoine** [pixijs/pixi.js#2934]
The two syntaxes work:
mySprite.scale.set(0.3,0.3);
mySprite.scale= new PIXI.Point(0.3,0.3);

but not with anchor:
mySprite.anchor.set(0.5,0.5); // ok
mySprite.anchor= new PIXI.Point (0.5,0.5); // breaks the render

**Comment by GoodBoyDigital** [comment]
You are correct 👍 
This is on our to fix list :)

**Comment by englercj** [comment]
Should be fixed by #3017
