### ISSUE TITLE
Filter area misaligned in version 4.0.1 (works fine in 4.0.0)

### ISSUE THREAD

**Issue by weavejester** [pixijs/pixi.js#2935]
If I create a simple mask shader that changes every non-transparent pixel to red, in version 4.0.0 the shader correctly masks the sprite:
![screen shot 2016-09-09 at 18 00 10](https://cloud.githubusercontent.com/assets/8780/18395655/48144f8e-76b7-11e6-8de8-94d656d36e34.png)

But in version 4.0.1, the filter area is misaligned:
![screen shot 2016-09-09 at 18 01 51](https://cloud.githubusercontent.com/assets/8780/18395691/81577d34-76b7-11e6-829b-d09943281fa1.png)

The fragment shader I'm using is:

```frag
void main(void) {
    vec4 pixel = texture2D(uSampler, vTextureCoord);

    if (pixel.a != 0.0) {
        gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
    }
    else {
        gl_FragColor = vec4(0.0);
    }
}
```

Could this be a problem with the filterArea or sprite boundaries? It looks as if the shader isn't being applied across the whole texture.

This issue may be related to #2898 and #2891, but as I can't tell for sure, I decided to create a new issue for it.

**Comment by GoodBoyDigital** [comment]
Thanks for this @weavejester ! Will aim to get this fixed for the next release 👍

**Comment by GoodBoyDigital** [comment]
fixed in dev branch! 👍

**Comment by bigtimebuddy** [comment]
Here's the link to the [latest dev release](http://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js)

**Comment by weavejester** [comment]
Thanks!
