### ISSUE TITLE
Uncaught TypeError in Shader.js (Electron app)

### ISSUE THREAD

**Issue by ignisphaseone** [pixijs/pixi.js#2937]
I am using Electron (and by extension, npm and require), and am just trying to do basic tutorial code. There's a choke on making a new WebGLRenderer.

```
var PIXI = require('pixi.js');
console.log(PIXI); //successful, Object reported to console log.
var renderer = new PIXI.WebGLRenderer(256, 256); //breaks
// OR
var renderer = PIXI.autoDetectRenderer(256, 256); //breaks
```

Error for both of the above lines:
`Uncaught TypeError: src.substring is not a function Shader.js:12`

**Comment by kaansoral** [comment]
I'm using pixi by importing it like any other script in html, using Electron, no issues

However, Electron does require some require/import related modifications to code (if you import them to the DOM, you have to manually convert `module.exports`'s to global variable names, like $ for jQuery)

Nothing tangible to help you, but just my .02

**Comment by ivanpopelyshev** [comment]
Its problem with glsify, then. Like in that webpack issue somewhere here...

**Comment by ignisphaseone** [comment]
webpack issue is #2922

**Comment by Adam-Meisen** [comment]
The workaround for this in webpack is to use the prebuilt version. If it works the same in electron, either `require('pixi.js/bin/pixi.js')`, or download pixi.js (or pixi.min.js) from [here](https://github.com/pixijs/pixi.js/releases), drop it in your directory, and `require('./pixi.js')`

**Comment by englercj** [comment]
Closing as it seems answered, people mentioned webpack workaround and you cannot simply include pixi's entry file using electron's require. You will need to include the built file in electron.
