### ISSUE TITLE
Container.width calculated incorrectly when children contains a TilingSprite

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#2938]
In [this pen](https://codepen.io/staff0rd/pen/ZpbyvE?editors=0010), `TilingSprite`s are horizontally positioned by a static value, followed by a similar set of `TilingSprite`s being positioned by their container's `width`.

The two images should be identical, however differ due to `tileContainer.width` calculation being wrong for tiling sprites.

![image](https://cloud.githubusercontent.com/assets/6289998/18408875/4e541028-777f-11e6-849f-38c4fefba3c2.png)

A third set using `Sprite` is then added (and scaled to the same size as the `TilingSprite`), showing correct calculation of `spriteContainer.width`.

**Comment by GoodBoyDigital** [comment]
Nice one @staff0rd ! Thanks for reporting the bug and providing the example too! Will let you know when this has been addressed 👍

**Comment by staff0rd** [comment]
Fixed in latest
