### ISSUE TITLE
PIXI.extras.MovieClip.onUpdate / onFrameChanged

### ISSUE THREAD

**Issue by thesunlover** [pixijs/pixi.js#2947]
I have to execute certain code when movie clip is updated.
Rasing the issue because i could find only onComplete callback
Of course I can use setInterval for now, but I think other ppl may also like the idea.

**Comment by englercj** [comment]
Just so I am clear, you are asking for events at key moments in the lifetime of a MovieClip that you can hook into?

**Comment by thesunlover** [comment]
yep, exactly: the moment a new texture from the MovieClip sequence is being rendered

**Comment by themoonrat** [comment]
Created a PR with what I believe you are after

**Comment by themoonrat** [comment]
@englercj You can close this after https://github.com/pixijs/pixi.js/pull/2948 was merged
