### ISSUE TITLE
Question: Which version of PIXI does the PIXI Flip branch currently use?

### ISSUE THREAD

**Issue by joeredfearn** [pixijs/pixi.js#2950]
I ask because our game currently has integrated PIXI 4.0 but we could really use some of the 3D functionality that PIXI Flip provides, which I worry is built on PIXI 3.0.

Thanks for the help guys!

**Comment by ivanpopelyshev** [comment]
https://github.com/gameofbombs/pixi.js

https://github.com/gameofbombs/pixi-bin

DEMOS: 

https://gameofbombs.github.io/pixi-bin/index.html?s=flip&f=cards.js&title=Cards

Its up-to-date with v4.0.0-rc2, I'm going to update to 4.0.1 soon.

**Comment by kaansoral** [comment]
Forgive me for going offtopic but that demo is just so impressive!

**Comment by joeredfearn** [comment]
thanks a lot ivan for the quick response!

**Comment by joeredfearn** [comment]
Hi there Ivan.

I've tried out your fork you recommended and its actually working pretty good. My only concern is since i swapped over (including the plugins) my mouse input is not responding any more.

`stage.mousedown = function() {alert("!!")};`
`stage.on("mousedown", function() {alert("!!")};`

Neither of these examples work, both were working before the swap. I'm guessing its something silly...

Any ideas?

Thanks

**Comment by ivanpopelyshev** [comment]
Yeah, I see the problem. So, if we make stage interactive, it wont react on children that aren't interactive... going to fix that

**Comment by ivanpopelyshev** [comment]
Strange, it works for me. Can you make minimal demo of it?

**Comment by englercj** [comment]
Closing this as it seems answered.
