### ISSUE TITLE
Export CANVAS Bug on SAFARI

### ISSUE THREAD

**Issue by mrgoonie** [pixijs/pixi.js#2951]
I'm not sure it's Safari's bug or Pixi's, but here is the situation:

When I use canvas.toDataURL() to export the canvas to base64. On Safari, the exported image was rotated in 180 degree. While the other browsers work normally. 

For example: 
1. I create a sprite & place it on the stage.
![original](https://cloud.githubusercontent.com/assets/6857382/18509520/43c07670-7aa3-11e6-95d8-2d983b93b4f9.png)

2. Call canvas.toDataURL() and the image was flipped:
![export](https://cloud.githubusercontent.com/assets/6857382/18509526/4c8acc06-7aa3-11e6-8973-2495265b7db4.png)

Tested with PIXI 4.0 and 4.0.1

Chrome/Firefox are fine. Only happen on Safari (9.1.3). Not sure what went wrong...

**Comment by ivanpopelyshev** [comment]
There were issues like that before, with Safari. What if you add this canvas to DOM first, and see the result, before you convert it to base64?

**Comment by mrgoonie** [comment]
Thanks @ivanpopelyshev for your quick reply!

I'm not sure I fully understand this part: "add this canvas to DOM first". Because the <canvas> element was there already, why do I need to add it into the document again? 

On the document, I saw the canvas was displaying normally, nothing was rotated. Only when I converted the canvas into Base64 and the resulted image was rotated.

**Comment by ivanpopelyshev** [comment]
Do you use webgl or canvas renderer? In case of webgl you have to use "renderer.extract.canvas()" or "renderer.extract.base64()". Simple "renderer.view.toDataUrl()" wont work with it

**Comment by mrgoonie** [comment]
@ivanpopelyshev: Well, you're right. That's exactly the issue. I'm using WebGL. Changing to "renderer.extract.base64()" solved.

Thanks a bunch, man!

**Comment by ivanpopelyshev** [comment]
That's good, I'm happy for you!

**Comment by mrgoonie** [comment]
Why it only happens on Safari? Whyyyy? 😄 I'm thinking Safari is on its way to become a-new-kind-of-IE, don't you think so? 😆

**Comment by ivanpopelyshev** [comment]
I think so. That happens because for WebGL behaviour of "toDataURL" and "getImageData" is not defined, unless you specify "preserveDrawingBuffer:true" in context options which is VERY slow.

**Comment by mrgoonie** [comment]
I see. Thanks for the explanation. Happy to see you around, @ivanpopelyshev !

**Comment by kaansoral** [comment]
Firefox, Safari, Opera - everything non-Chrome feels like IE's now
