### ISSUE TITLE
Multiple listeners on same object and stopping propagation

### ISSUE THREAD

**Issue by Theodeus** [pixijs/pixi.js#2952]
**TL;DR**
Multiple listeners on the same event for a single object doesn't respect the stopPropagation method.

**Slightly longer**
I don't know if this is considered a bug or not, but the steps to reproduce is as follows:
- I add two separate listeners for the "mousedown" event on a Graphic object
- I stop the event with event.stopPropagation in the first listener
- The second listener is still fired but event.stopped === true 

Click the green box with the console open:
http://codepen.io/Theodeus/pen/LRNNNB?editors=0010

**Comment by englercj** [comment]
This is working as intended, "propagation" is the "bubbling" of the event up the chain. It stops that.

I wonder what the DOM behavior is here?

**Comment by Theodeus** [comment]
Gotcha! I'll go ahead and close this!

And interesting question - had to check myself. Turns out the events in Pixi and the DOM works about the same (calling event.preventDefault() still triggers the second listener, but defaultPrevented is true on the event in the second listener).

**Comment by kaansoral** [comment]
I also had a similar issue/discovery lately, makes you wish it didn't imitate DOM tho, or maybe extend it just a little bit :)
