### ISSUE TITLE
Graphics masks bounds are empty

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2955]
@GoodBoyDigital is there any explanation for https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/Graphics.js#L793 ? 

http://www.html5gamedevs.com/topic/25184-animating-mask-thats-a-graphics-shape/ is one of problems because of that.

May be its better to ask "!renderable" in parent container and not here.

**Comment by englercj** [comment]
@ivanpopelyshev Is this good to go after #2956 was merged?

**Comment by ivanpopelyshev** [comment]
Yeah, we fixed that.
