### ISSUE TITLE
PIXI dies on destroy and re-create renderer

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#2958]
https://jsfiddle.net/g3op2rcu/2/

Any recommendations how to deal with this for now?

**Comment by englercj** [comment]
What do you mean by "dies"? You fiddle had no errors for me, and when I rendered using your second renderer it worked fine:

https://jsfiddle.net/g3op2rcu/3/

What problem are you experiencing?

**Comment by trsh** [comment]
@englercj well. I'm on Linux Chromium. When I open page freezes and has to be killed by force. Lot's of CPU processing. But I can't debug :(

**Comment by kaansoral** [comment]
On OSX/Chrome, I can't open the fiddle either

**Comment by trsh** [comment]
P.S. this was not the case in 3.0.11. I started to exp. this when switched to pixi v4

**Comment by themoonrat** [comment]
Windows & Chrome Beta (v54) and it freezes for me too. Latest Firefox Dev Edition and IE 11 are fine.

**Comment by englercj** [comment]
Hmm, now that I think about it; I'm on a machine that uses CanvasRenderer. So this is probably WebGL renderer only, I'll check again when I get to work.

**Comment by trsh** [comment]
@englercj  ?

**Comment by englercj** [comment]
Sorry busy at work, haven't had a chance to look into this. I should be getting a GFX card in the next few weeks.

**Comment by englercj** [comment]
Ok, been looking into this. Seems like what is happening is the second context we create returns `null` which makes us run the `checkMaxIfStatmentsInShader` function with a maximum value of `0`, so it just runs forever.

Note that this only seems to be a problem if you reuse the same canvas both times. Creating a new canvas for the second renderer doesn't seem to have this issue.

Still looking into why it returns `null`, will update soon.

**Comment by englercj** [comment]
Finally figure this one out, was pretty interesting. You can see more info in #3065, which should fix this issue when merged.

**Comment by trsh** [comment]
Thanks @englercj . Will is into this next week.
