### ISSUE TITLE
Sortable displayobjects

### ISSUE THREAD

**Issue by alaa-eddine** [pixijs/pixi.js#296]
some times we need that display object to be rendered in a certain order to preserve the z-index.

it'd be good if we can have a way to choose the ordre of the drawn children, even with a sort method or by allowing a separate reder method for individual DisplayObjects so the developer can build it's ordered list, iterate throught objects and render them.

**Comment by tengotengo** [comment]
```javascript
var mapContainer = new PIXI.DisplayObjectContainer(),
    unitsContainer = new PIXI.DisplayObjectContainer(),
    menuContainer = new PIXI.DisplayObjectContainer();

mapContainer.zIndex = 5;
unitsContainer.zIndex = 10;
menuContainer.zIndex = 20;

/* adding children, no matter in which order */
stage.addChild(mapContainer);
stage.addChild(menuContainer);
stage.addChild(unitsContainer);

/* call this function whenever you added a new layer/container */
stage.updateLayersOrder = function () {
    stage.children.sort(function(a,b) {
        a.zIndex = a.zIndex || 0;
        b.zIndex = b.zIndex || 0;
        return b.zIndex - a.zIndex
    });
};

stage.updateLayersOrder();

```

**Comment by glebmachine** [comment]
Children array are `readonly`

**Comment by ivanpopelyshev** [comment]
@glebmachine doesnt mean that you cant call "sort"

**Comment by aquachris** [comment]
@tengotengo Thank you! Your solution is simple yet elegant.

**Comment by bluefeet** [comment]
Is @tengotengo's solution really the final solution for this?  Being able to change z-index seems to be a primary feature to me.  Imagine, in an isometric game where depending on your y-axis one sprite could be considered behind of in front of another sprite.  Doing z-index is the traditional way of handling this, and in that case you'd just map the sprites bottom y position to their z-index and done.  For now I'll do the sort hack, but seems this should have an official solution.

**Comment by themoonrat** [comment]
@bluefeet Take a look at https://github.com/pixijs/pixi-display
I think it'd give you the functionality you require

**Comment by loadedsith** [comment]
If you're here looking for this feature in 2017; it's been implemented in Pixi as zOrder.

https://pixijs.github.io/examples/#/display/zorder.js

**Comment by ivanpopelyshev** [comment]
@loadedsith pixi-display is updated to latest version, rewritten on TS and there'll be huge patch with a lot of examples this week.
