### ISSUE TITLE
Bug with generateTexture

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#2967]
Playground: https://jsfiddle.net/uet2fks9/2/

If you want to see 2 bunnies (as expected), comment line 30 (bunny.getBounds()).
# 

In my project, the problem got fixed by changeing fallowing func in PIXI source, but not sure if it's right way.

```
SystemRenderer.prototype.generateTexture = function (displayObject, scaleMode, resolution) {

    //var bounds = displayObject.getLocalBounds();
    var bounds = displayObject.getBounds();
    var renderTexture = RenderTexture.create(bounds.width | 0, bounds.height | 0, scaleMode, resolution);

    tempMatrix.tx = -bounds.x;
    tempMatrix.ty = -bounds.y;

    this.render(displayObject, renderTexture, false, tempMatrix, true);

    return renderTexture;
};
```

**Comment by trsh** [comment]
Correction. If I set "new PIXI.CanvasRenderer", than fix above doesn't work. On on WebGL.

**Comment by trsh** [comment]
Can we add type:bug to this?

**Comment by englercj** [comment]
> Can we add type:bug to this?

I just added the labels yesterday, still working my way through the issues to get them all tagged. Bear with me 💯

**Comment by trsh** [comment]
Thanks
