### ISSUE TITLE
Resolution related bug in chained filters

### ISSUE THREAD

**Issue by lordnoriyuki** [pixijs/pixi.js#2971]
I think this line in FilterManager.popFilter() [FilterManager.js:144](https://github.com/pixijs/pixi.js/blob/6c608aad67c2b4cdcece50614382b29e9aad8c72/src/core/renderers/webgl/managers/FilterManager.js#L144)

`
var flop = this.getPotRenderTarget(this.renderer.gl, currentState.sourceFrame.width, currentState.sourceFrame.height, 1);
`

shouldn't be passing 1 for resolution. I tried changing it to currentState.resolution and this fixed an issue I was having where reordering a sequence of filters caused the result to change resolution. 

`
var flop = this.getPotRenderTarget(this.renderer.gl, currentState.sourceFrame.width, currentState.sourceFrame.height, currentState.resolution);
`

**Comment by englercj** [comment]
Thanks for this, merged into dev!
