### ISSUE TITLE
transform.setFromMatrix not working for 

### ISSUE THREAD

**Issue by Trixt0r** [pixijs/pixi.js#2974]
This is related to #2574 

The decomposition is not really working for some cases.
If the rotation has been set and at least one scale component is negative, the rotation and the scale are no longer preserved.

I also would like to kow if it is possible to transform the decomposed skew values into a local container space?

-Trixt0r

**Comment by ivanpopelyshev** [comment]
BTW, scale.set(-1,-1) is the same as rotation=Math.PI, so its not possible to recover it, unless we talk about some conventions, like "dont use scale negative values, use texture rotation instead" http://pixijs.github.io/examples/#/demos/texture-rotate.js

**Comment by englercj** [comment]
Not sure there is an easy way to decompose these 100% correctly and multiple values affect multiple matrix positions (see scale/skew).
