### ISSUE TITLE
Videos are no longer working in 4.0.1

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#2979]
Look at the examples page
https://pixijs.github.io/examples/#/basics/video.js
And change the version to 4.0.1. You can hear, but not see the video. It works fine in 4.0.0

(ps. for some reason that examples page defaults to 4.0.0 as the 'latest version')

**Comment by themoonrat** [comment]
https://github.com/pixijs/pixi.js/issues/2873 broke it?

**Comment by erpy** [comment]
Is there an ETC for this ?

**Comment by englercj** [comment]
@themoonrat Am I just crazy or did we fix this recently? I don't remember...

**Comment by themoonrat** [comment]
Nopes, still broken after the commit listed above by @GoodBoyDigital which went in to the 4.0.1 release. I've personally just removed those lines in my build of pixi to get it working again, but not submitted a pr because clearly there was a reason for adding them in the first place!

**Comment by themoonrat** [comment]
@englercj Can be closed, fixed by https://github.com/pixijs/pixi.js/pull/3043
