### ISSUE TITLE
Graphics fill without line style draws nothing

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#2984]
Import from: http://www.html5gamedevs.com/topic/25326-shapes-rendered-using-pixigraphics-not-rendering-on-webglrenderer-but-rendering-fine-on-canvasrenderer-solved/

Looks like this code was not working:

``` js
var color = Math.floor(Math.random() * 0xFFFFFF);
var renderObject = new PIXI.Graphics();
renderObject.beginFill(color, 0xFF);
renderObject.drawRect(x * 16, y * 16, 32, 32);
```

But this code was:

``` js
var color = Math.floor(Math.random() * 0xFFFFFF);
var renderObject = new PIXI.Graphics();
renderObject.beginFill(color, 0xFF);
renderObject.lineStyle(1, color, 0xFF);
renderObject.drawRect(x * 16, y * 16, 32, 32);
renderObject.endFill();
```

OP said that the `endFill` was not what fixed the issue, it was adding a call to `lineStyle`. This issue is also WebGL specific.

**Comment by staff0rd** [comment]
Fixed in latest; https://jsfiddle.net/1uL5nm52/
