### ISSUE TITLE
Blob url image to texture

### ISSUE THREAD

**Issue by QQizi** [pixijs/pixi.js#2985]
I'm trying to convert some loaded blob (ex:blob:http://localhost/4606c2ef-5116-b74e-a683-c7dd8519bdd7) into a texture.

When i'm using base64, after the loading (PIXI.loaders.Loader), a texture is automaticly generated, not with the blob url.

I'm also trying to convert the blob into a texture by using new PIXI.Texture((new PIXI.BaseTexture(blob)), not working either.

**Comment by englercj** [comment]
You need to encode the blob into a base64 data-url and assign that to the source of an image. Then use that image as the source in a baseTexture.

The loader should do this for you, if you give it the data-url to "load".

**Comment by QQizi** [comment]
Hey, thx for the fast answer @englercj 

You can download my repo on https://github.com/QQizi/Izzi-Image-Sequence/tree/dev

Basicly it's a little plugin that i use for image sequence.
I'm using https://github.com/keitakun/Magipack.js for generating binary from images and want to use those blob as texture.

You can check izziImageSequence-min.js in the function `handleComplete()`, it's pretty straightforward.

**Comment by englercj** [comment]
You can't draw a `Blob` directly to a canvas, you need to convert it to an `Image` object. You do this by creating a data-url from the blob and using it as the source for an `Image` object.

Assuming the `getURI` method is actually returning a data-url of the binary data, then the loader should work fine.

One thing I see that is wrong is this:

https://github.com/QQizi/Izzi-Image-Sequence/blob/dev/izziImageSequence-min.js#L111

The first parameter of BaseTexture is not a string url, its the Image. You should be able to just use the texture the loader created for you, probably something like:

```js
loaderTexture.once('complete', function(loader){
			izziImageSequence.global.texturePackage = loader.resources;

			izziImageSequence.global.canvasElem = new PIXI.Sprite(loader.resources['sequence_' + _indexActifLoad].texture);
});
```

**Comment by QQizi** [comment]
The loader doesn't create the texture object. I'll give a try of creating an `Image` object **before** adding it the the loader queue.

**Comment by englercj** [comment]
If it isn't then what you pass in likely is not a valid data url (or there is a bug in the loader). I'll try to run your example and check on it this weekend. However, data urls are supported and the tests are passing for the loader.

**Comment by QQizi** [comment]
I'll give it a try and let you know, thx for the help tho !

**Comment by QQizi** [comment]
@englercj Little update.

I used a `XMLHttpRequest` for blob to base64 in a promise for each images. Then used the pixi loader on those base64 and it work fine.
(https://github.com/QQizi/Izzi-Image-Sequence/blob/dev/izziImageSequence-min.js)

I'm kinda disapointed to have to convert the blob to base64 since i already had implemented my plugin with base64 images before.

My json containing my base64 images is only 1MO more than the blob json. But i think that the loading time that i won is lost by converting blob to base64.

**Comment by englercj** [comment]
the browser doesn't have APIs for creating iamges from Blobs unfortunately :(

**Comment by mems** [comment]
@englercj You can load a blob as an image with :
```
var img = new Image();
img.addEventListener("load", event => {
	URL.revokeObjectURL(img.src)
	new PIXI.Texture((new PIXI.BaseTexture(img));
})
img.src = URL.createObjectURL(blob);
```

**Comment by QQizi** [comment]
Actually the blob that i have are already an object URL (ex : blob:http://localhost/484eefb1-6505-c64f-9470-99484954d02f)
Passing those object url into a Pixi Loader doesn't generate a valide texture.

I'v tried a bunch of potential solution (tried yours too) and the only one working is by converting blob to base64

**Comment by englercj** [comment]
@mems That's creating an image from an object URL, not a Blob. Like I mentioned previously in this thread:

> You can't draw a Blob directly to a canvas, you need to convert it to an Image object.

Object URLs aren't supported in the loader currently because, well no one has needed it yet. We could add support for it, but the user will likely still be responsible for cleaning them up.

@QQizi You're probably having trouble using @mems example because that code is releasing the object url then trying to draw the image. Once you revoke the object URL, that url becomes invalid (and so will the image). Try it without revoking the URL. I imagine you would only want to revoke the URL when you destroy the base texture.

**Comment by mems** [comment]
@englercj @QQizi I think we misunderstand ourselves.

In the [basic PixiJS example](https://pixijs.github.io/examples/#/basics/basic.js), paste the following code:

```
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();
// Load the image as blob
var xhr = new XMLHttpRequest();
xhr.responseType = "arraybuffer";
xhr.open("GET", 'required/assets/basics/bunny.png');
xhr.onload = function(){
	// Create a blob contains PNG data
	var blob = new Blob([xhr.response], {type: xhr.getResponseHeader("Content-Type")});
	var blobURL = URL.createObjectURL(blob);
	console.log("the blob URL is: " + blobURL);

	// Now you can:

	/*
	1. create a texture from the blob URL
	*/
	//var texture = PIXI.Texture.fromImage(blobURL);
	// But here we can't control the revokation of blobURL

  	/*
	Or 2. create an image with the blob URL and use the image as texture source
	*/
	var img = new Image();
	img.addEventListener("load", function(event){URL.revokeObjectURL(blobURL);});// onload revoke the blob URL (because the browser has loaded and parsed the image data)
	img.src = blobURL;
	var texture = new PIXI.Texture(new PIXI.BaseTexture(img));

	var bunny = new PIXI.Sprite(texture);
	bunny.anchor.x = bunny.anchor.y = 0.5;
	bunny.position.x = bunny.position.y = 150;
	stage.addChild(bunny);
	animate();
	function animate() {
    	requestAnimationFrame(animate);
    	bunny.rotation += 0.1;
    	renderer.render(stage);
	}
}
xhr.send(null);
```

To create a texture from a blob, you can use directly the blob URL:

```
var texture = PIXI.Texture.fromImage(blobURL);
```

Or use an image as texture source:

```
var img = new Image();
img.addEventListener("load", function(event){URL.revokeObjectURL(blobURL);});
img.src = blobURL;
var texture = new PIXI.Texture(new PIXI.BaseTexture(img));
```
