### ISSUE TITLE
How to get the actual coordinates of sprite or graphics

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#2987]
hi
now.i set sprite position.x,position,y,How get the actual coordinates of children
as : 

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>js test</title>
    <style>
        body {margin: 0;padding: 0;background-color: #000000;}
    </style>

    <script src="//cdn.bootcss.com/pixi.js/4.0.1/pixi.min.js"></script>

</head>

<body>
<script>
    var stage = new PIXI.Container();
    var render = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, {antialias: true},true);
    document.body.appendChild(render.view);

        bt = new PIXI.Sprite();
        bt.anchor.set(0.5);
        bt.x =150;
        bt.y = 200;
        bt.width = 140;
        bt.height = 344;

        gt = new PIXI.Graphics();
        gt.interactive = true;
        gt.beginFill(0x123123,1);
        gt.drawRoundedRect(0,0,1,1);
        gt.endFill();
        bt.addChild(gt);
        stage.addChild(bt);

    requestAnimationFrame(update);
    function update() {
        requestAnimationFrame(update);
        render.render(stage);
    }
</script>
</body>
</html>
```

How get the actual coordinates of gt

**Comment by fengFanYong** [comment]
And, if I draw a line in the sprite,the lineWidth is ratio of sprite,Rather than the actual pixel

**Comment by englercj** [comment]
Please use code tags around your code so I don't have to edit your post each time.

**Comment by whizzkid** [comment]
You're creating an empty sprite and then make its width and height 140x344,  this effectively sets its SCALE to 140x344, this is not what you want. (PIXI is behaving correctly by the way)

But you generally don't set the width and height of a container. setting width and height will stretch the container (i.e. change its scale) 

remove the bt.width and height and you'll see the graphics respond better to what you want.

**Comment by englercj** [comment]
Closing since this seems answered.
