### ISSUE TITLE
Firefox Errors when rendering Video in WebGL

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#2991]
Using the latest Firefox Developer edition, go to the example video: https://pixijs.github.io/examples/#/basics/video.js

Open up the console; you'll see lots of errors for WebGL. The video works, but warnings about being 'very slow' are worrying! 

```
Error: WebGL: texImage2D: Failed to hit GPU-copy fast-path. Falling back to CPU upload.pixi.js:528:6
Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.pixi.js:528:6
Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.pixi.js:528:6
Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401
```

**Comment by englercj** [comment]
Does this still happen for you in the latest `dev`?

https://pixijs.github.io/examples/?v=dev#/basics/video.js

**Comment by themoonrat** [comment]
Yeps

**Comment by englercj** [comment]
Hmm, I'm not getting it Firefox 47 or Chrome 53 on Windows 10. Weird...

There is a chance I am in software emulation, and that might be why I don't see. Can someone else take a look at this one?

**Comment by Friksel** [comment]
I'm getting the same console-messages (only in Firefox). Using the latest Pixi (4.1.0), but also earlier versions. Seen on Firefox 49.0.2 (latest).
I've seen people using threejs have the same problems. Something to do with image format for textures?
https://github.com/mrdoob/three.js/issues/9109

**Comment by englercj** [comment]
Yeah looks like this has to do with image format, and probably premultiplied alpha as well.

https://github.com/mrdoob/three.js/issues/9109#issuecomment-240146741

**Comment by Friksel** [comment]
Looks like a bug in Firefox only: [https://bugzilla.mozilla.org/show_bug.cgi?id=1246410](url)
