### ISSUE TITLE
Setting renderer.plugins.interaction.interactionFrequency has no effect

### ISSUE THREAD

**Issue by hubletkoresh** [pixijs/pixi.js#2992]
[Code](https://jsfiddle.net/megakoresh/xf25yzr2/2/)

Feel free to set the interactionFrequency to whatever and watch the object "slip" from under the pointer just the same.

Also why is the fact that InteractionManager is in the renderer under the plugins attribute not mentioned anywhere in the documentation? I had to console.log each object in the scene and crawl down their attributes to find the reference to InteractionManager.

Workaround for now is 

``` javascript
//Give object 80ms to fly back under the pointer
wonderfulRectangle.addEventListener('mouseup mouseout touchend touchendoutside', function(event){
    event.target.resetTimeout = setTimeout(()=>{
        event.target.moving = false;
        event.target.lastPointerPos = null;
 }, 80);
// Clear the flag timeout if when the object flies back under the pointer
wonderfulRectangle.addEventListener('mouseover', event=>clearTimeout(event.target.resetTimeout));})
```

addEventListener in this case is just an alias for multiple `object.on('eventname', callback);` for cleaner syntax.

**Comment by themoonrat** [comment]
If you follow the dragging example at https://pixijs.github.io/examples/#/demos/dragging.js there is no 'slippage' there.

I'll update the documentation for the interaction manager to let others know where it can be found
