### ISSUE TITLE
Mask a sprite using another sprite not working on CanvasRenderer

### ISSUE THREAD

**Issue by Hidejec** [pixijs/pixi.js#2993]
It's working on WebGLRenderer and autoDetectRenderer but not on CanvasRenderer.

**Comment by themoonrat** [comment]
According to the docs, you cannot use a sprite as a mask on the canvasrenderer

https://pixijs.github.io/docs/PIXI.Sprite.html#mask

**Comment by ivanpopelyshev** [comment]
If you find a way to make sprite mask with "canvas2d" context, you can make a PR to pixi :)

**Comment by Hidejec** [comment]
How do I fix my iOS sprite tinting bug. Using autoDetectRenderer and WebGLRenderer doesn't work on all iOS devices so the only solution I found was to change it to CanvasRenderer which the tint works. Are there any solution where in I can make tinting works using autoDetectRenderer or WebGLRenderer? 

Here is my example code of how I tint a sprite:
mysprite.tint = "0x363533";
renderer.render(stage);

**Comment by ivanpopelyshev** [comment]
tint must be integer.

mysprite.tint = 0x363533;

**Comment by Hidejec** [comment]
Is this fine? 

mysprite.tint = "0x"+randomedSpriteColor;

I am concatenating the hex color because I am generating it dynamically

**Comment by ivanpopelyshev** [comment]
No its not. try 

mysprite.tint = +("0x"+randomedSpriteColor);

**Comment by Hidejec** [comment]
Not working. I also tried this value `mysprite.tint = 0xECAEAA;` and still not working on iOS

**Comment by Hidejec** [comment]
Just found out that WebGL doesn't support iOS 7 and below so I need to use CanvasRenderer instead. So the only solution that will work is either create a PR to pixi or draw the complex mask manually.
