### ISSUE TITLE
Shakiness when animating BlurFilter

### ISSUE THREAD

**Issue by manuel-vivoda** [pixijs/pixi.js#2998]
I am running into an issue when animating the blur filter, applied to a sprite. The sprite starts to shake. This issue can also be seen in the official blurfilter example here: http://pixijs.github.io/examples/#/filters/blur-filter.js

Any idea?

**Comment by nuthinking** [comment]
+1

**Comment by GoodBoyDigital** [comment]
hello! this should be fixed in the dev branch?

**Comment by englercj** [comment]
Can you retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!
