### ISSUE TITLE
DDS example not working

### ISSUE THREAD

**Issue by erpy** [pixijs/pixi.js#3001]
Chrome says:
GLTexture.js:94
Uncaught TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.

**Comment by ivanpopelyshev** [comment]
Yeah, I know. compressed-textures werent updated yet , gonna do it right now

**Comment by ivanpopelyshev** [comment]
Fixed. 

http://pixijs.github.io/examples/#/textures/dds.js
