### ISSUE TITLE
Graphics tint not working when cacheAsBitmap == true

### ISSUE THREAD

**Issue by aidangrabe** [pixijs/pixi.js#3009]
When I try to change the `tint` colour of a `PIXI.Graphics` object when `cacheAsBitmap = true` it doesn't change.

Tested on 4.0.0, 4.0.1, 4.0.2
[Fiddle](https://jsfiddle.net/o50yuw1q/3/)

Expected: a green circle
Actual: a red circle

**Comment by ivanpopelyshev** [comment]
Unfortunately, right now tint property is "inside" of cached stuff. There are plans on making all containers tintable, and that will also make it "outside" of cache.

Right now you'll have to pick on cacheAsBitmap. 

```js
obj.cacheAsBitmap=false;
obj.cacheAsBitmap=true;
```

Or you can cheat your way:

```js
//1. make sure object is cached first time BEFORE you apply the tint.
obj._initCachedDisplayObject(renderer);
obj._cacheData.sprite.tint = newTint;
```

**Comment by aidangrabe** [comment]
Thanks @ivanpopelyshev for the workaround
