### ISSUE TITLE
Source map errors

### ISSUE THREAD

**Issue by paralin** [pixijs/pixi.js#3010]
I'm getting this error as of the latest release from webpack:

```
Chrome 53.0.2785 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected identifier
  at webpack:///source/src/prepare/webgl/WebGLPrepare.js:277:0 <- config/spec-bundle.js:58543
Chrome 53.0.2785 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected identifier
  at webpack:///source/src/prepare/webgl/WebGLPrepare.js:277:0 <- config/spec-bundle.js:58543
```

I had a look at that line and it looks fine... really strange that this is suddenly an issue. Will debug some more.

**Comment by paralin** [comment]
As of the latest release (4.0.2 vs 4.0.1):

```
24 09 2016 18:44:10.570:ERROR [karma]: Error: "/pixi-gl-core/src/GLBuffer.js" is not in the SourceMap.
```

**Comment by paralin** [comment]
Related, I think this is a webpack issue:

https://github.com/webpack/webpack/issues/3063

**Comment by paralin** [comment]
Ignoring the source maps for pixi fixed it, so I think something's wrong with the pixi sourcemaps

**Comment by hdennen** [comment]
same problem, also excluded source map for pixi and it went away.

**Comment by themoonrat** [comment]
Closing in favour of https://github.com/pixijs/pixi.js/issues/3821 which also talks about incorrect source maps
