### ISSUE TITLE
Examples point to old cached build for Latest

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#3013]
/bin has been removed from the dev branch, e0a73586b4785222feafe94c6502cf332b92ee1f, but the [examples](https://pixijs.github.io/examples/) _Latest_ setting still expects it to be there at this address; https://cdn.rawgit.com/pixijs/pixi.js/dev/bin/pixi.js.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev Could you update this on **examples**?  Should be `http://s3-eu-west-1.amazonaws.com/pixi.js/[branch]/pixi.js` not `https://cdn.rawgit.com/pixijs/pixi.js/[branch]/bin/pixi.js`

**Comment by staff0rd** [comment]
@bigtimebuddy how does the latest dev get there?  I'm looking at a local dev build and it doesn't match http://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js.  Notably #3055 is broken locally, but not via the s3 link.

**Comment by bigtimebuddy** [comment]
@staff0rd We changed the S3 bucket. You can check out https://github.com/pixijs/pixi.js/wiki/FAQs.

**Comment by englercj** [comment]
Sorry about that! I also updated the examples to use the new S3 buckets, and you can link directly to a version you choose. Let me know if it doesn't work out.

**Comment by staff0rd** [comment]
Hey I just saw this got updated and broke my pens again again :(

This new host doesn't look to support ssl - is there an intention to implement https or should I link to rawgit on my own repo instead?

**Comment by englercj** [comment]
You can use the S3 urls directly instead of the `pixijs.download` links. All of the following point to the same thing:

```
http://pixijs.download/dev/pixi.js
https://d157l7jdn8e5sf.cloudfront.net/dev/pixi.js

http://pixi.js.s3-website-eu-west-1.amazonaws.com/dev/pixi.js
https://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js
```

I recommend the `pixijs.download` or `cloudfront` urls as they are unlikely to change, even if we change buckets again. The S3 direct urls below those two will change if we change bucket names.
