### ISSUE TITLE
GLShader.js prints debug statements

### ISSUE THREAD

**Issue by Wavewash** [pixijs/pixi.js#3026]
GLShader.js:49

```
    for(var i in this.attributes)
	{
		console.log(i + " : " + this.attributes[i].location)
	}

	console.log(">>>>>>>");
```

Some console.log statements were left in and write out quite often - rather than make a pull request I figured I'd make a simple issue and propose to remove these statements.

Thanks.

**Comment by englercj** [comment]
This is actually in the [pixi-gl-core](https://github.com/pixijs/pixi-gl-core) repo. I think they are actually already removed, just hasn't made its way back into pixi yet.

**Comment by Dadibom** [comment]
aTextureCoord : 1
pixi.min.js?4:9 aColor : 2
pixi.min.js?4:9 aVertexPosition : 3
pixi.min.js?4:9 >>>>>>>
pixi.min.js?4:9 aTextureCoord : 1
pixi.min.js?4:9 aColor : 2
pixi.min.js?4:9 aTextureId : 0
pixi.min.js?4:9 aVertexPosition : 3
pixi.min.js?4:9 >>>>>>>
pixi.min.js?4:9 aColor : 1
pixi.min.js?4:9 aVertexPosition : 0
pixi.min.js?4:9 >>>>>>>
pixi.min.js?4:9 aRotation : 4
pixi.min.js?4:9 aTextureCoord : 1
pixi.min.js?4:9 aColor : 2
pixi.min.js?4:9 aPositionCoord : 3
pixi.min.js?4:9 aVertexPosition : 0
pixi.min.js?4:9 >>>>>>>
?debug:1 [.Offscreen-For-WebGL-0x2bd8b0ed3700]PERFORMANCE WARNING: Attribute 0 is disabled. This has significant performance penalty


Related?

**Comment by englercj** [comment]
Those are the logs we are referring to, yes.
