### ISSUE TITLE
calling getBounds() before adding to container prevents transform update

### ISSUE THREAD

**Issue by bikasx** [pixijs/pixi.js#3027]
```javascript
var stage = new PIXI.Container();
var first = new PIXI.Container();
var second = new PIXI.Container();

stage.addChild(first);
first.position.x = 200;
first.position.y = 200;
first.rotation = Math.PI / 2;
second.addChild(bunny);
second.getBounds(); // if you comment this line, transform will be up to date
first.addChild(second);
```

[jsfiddle](https://jsfiddle.net/263bjo96/4/)

**Comment by englercj** [comment]
@ivanpopelyshev I think this may have to do with the update IDs being wrong if it does `getBounds()` first.

**Comment by ivanpopelyshev** [comment]
It works in development, please confirm.

**Comment by englercj** [comment]
Can you retest this with the latest dev build and see if that has fixed your issue?

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!

**Comment by bikasx** [comment]
Works fine now in v4.1.0: [jsfiddle](https://jsfiddle.net/jd4a4bu4/1/)

Thank you.
