### ISSUE TITLE
Pixi v4 transparent renderer doesn't work in v4.0 and above

### ISSUE THREAD

**Issue by alvinsight** [pixijs/pixi.js#3034]
Hi everyone,
Just flagging this one before I forget, so in v4 and above the rendererOption to make the canvas transparent doesn't work anymore, you can test it in the pixi examples (http://pixijs.github.io/examples/#/basics/basic.js) by settings `{transparent : true}` .
My initial guess is that it was removed when we changed the way we render to a renderTarget, or maybe there's a simple logic error.
I couldn't take a proper look but hopefully it should be a quick fix

**Comment by themoonrat** [comment]
That demo page works fine with transparency for me, in both WebGL and Canvas

**Comment by alvinsight** [comment]
Using v4 ?

**Comment by themoonrat** [comment]
Yeps, tried 4.0.0, and the latest 4.0.3, both work fine
`var renderer = PIXI.autoDetectRenderer(800, 600,{transparent: true});`

**Comment by alvinsight** [comment]
This is what I get at the moment, using OSX El Capitan : 
![screen shot 2016-09-29 at 17 26 51](https://cloud.githubusercontent.com/assets/4254030/18962797/263d8cf0-866a-11e6-8ad3-9ae527853af6.png)

**Comment by themoonrat** [comment]
I see; you are getting transparency AND a background colour, whereas 3.x would override the background colour if you had transparency set

**Comment by englercj** [comment]
@alvinsight Does this behavior need to change?

**Comment by alvinsight** [comment]
Yes, it's a bug, there is no longer a way to get a fully transparent background like in the previous versions, I had to roll back to 3.0.11 :/

**Comment by englercj** [comment]
> there is no longer a way to get a fully transparent background like in the previous versions

Are you sure? Because this is fully transparent for me:

```
var renderer = PIXI.autoDetectRenderer(800, 600,{transparent: true});
```

And this is semi-transparent with the color specified:

```
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor: 0x1099bb, transparent: true});
```

And this is fully opaque:

```
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor: 0x1099bb});
```

**Comment by alvinsight** [comment]
Oh, I see, nice catch, I didn't think about removing the `backgroundColor` option entirely, it might not be a bug then, more like an API change that needs clarification somewhere.
So, in v3, transparent would always override backgroundColor and make it fully transparent, whereas in v4, it's the opposite.

**Comment by englercj** [comment]
We should probably have alpha components to colors and make this simpler...but it should work as you need, just needs to be doc'd better for v4 I think.

**Comment by GoodBoyDigital** [comment]
Great idea!

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
