### ISSUE TITLE
Attribute 0 is disabled

### ISSUE THREAD

**Issue by BrandonRaggett** [pixijs/pixi.js#3040]
I have been following the tutorial and I received the following error 

`[.Offscreen-For-WebGL-0x55f5703ffc80]PERFORMANCE WARNING: Attribute 0 is disabled. This has significant performance penalty`

Is there a fix for this? I can't seem to find anything from a few google searches.

**Comment by englercj** [comment]
What tutorial are you following? Can you share a running example that reproduces the error please?

**Comment by BrandonRaggett** [comment]
This one
https://github.com/kittykatattack/learningPixi  

```
class Canvas{
	constructor(){
		var _this = this;
                 
		this.existingCanvas = document.getElementById("cvs");
		global.canvas = this;

		this.stage = new container();
		this.renderer = new pixi.WebGLRenderer(720, 480, {
			view: this.existingCanvas,
			antialias: false,
			transparent: false,
			resolution: 1 });
		this.renderer.view.style.position = "absolute";
		this.renderer.view.style.display = "block";
		this.renderer.autoResize = true;

		pixi.loader
			.add('testSprite', '../img/testSprite.png')
			.load(function(){
				let tex = resources.testSprite.texture;
				tex.frame = new rectangle(0, 0, 16, 16);
				this.s = new sprite(tex);
				this.s.position.set(100, 100);
				this.stage.addChild(this.s);

				this.resize();
				this.gameLoop();
			}.bind(this));
	}

	gameLoop(){
		requestAnimationFrame(this.gameLoop.bind(this));
		this.s.rotation += 0.1;
		this.renderer.render(this.stage);
	}

	resize(){
		this.renderer.resize(window.innerWidth, window.innerHeight);
		this.renderer.render(this.stage);
	}
}
```

It seems to not show the error any more when I comment out the sprite creation part:
```
let tex = resources.testSprite.texture;
tex.frame = new rectangle(0, 0, 16, 16);
this.s = new sprite(tex);
this.s.position.set(100, 100);
this.stage.addChild(this.s);
```

However, I'm still doing almost exactly what it says in the tutorial.
When I run the tutorial code by itself, without putting it into a class, I do not get the Offscreen-For-WebGL error.

**Comment by englercj** [comment]
What version of pixi.js are you using? can you confirm you are using v4.0.3?

Thanks!

**Comment by BrandonRaggett** [comment]
I didn't even realise that 4.0.3 was out, I just started 3 days ago. It's fixed now, and I'll fix the namespaces :)

Thanks

**Comment by englercj** [comment]
Np! You are welcome to follow myself [@rolnaaba](https://twitter.com/rolnaaba) and others on Twitter (more in [README](https://github.com/pixijs/pixi.js/blob/dev/README.md)) to keep up with news and such.

I try to always tweet when we release a new version, with links and such.

**Comment by BrandonRaggett** [comment]
Great! I am the legendary 500th follower. Thank you again for your help.
