### ISSUE TITLE
PIXI.Text broken on dev branch

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#3055]
I'm getting black squares for PIXI.Text on latest dev build.  Console spammed with this;

Chrome
~~~
[.Offscreen-For-WebGL-000002A20404F470]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
(index):1 [.Offscreen-For-WebGL-000002A20404F470]RENDER WARNING: texture bound to texture unit 2 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
(index):1 [.Offscreen-For-WebGL-000002A20404F470]RENDER WARNING: texture bound to texture unit 3 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
(index):1 [.Offscreen-For-WebGL-000002A20404F470]RENDER WARNING: texture bound to texture unit 2 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
~~~

Edge
~~~
WEBGL11098: INVALID_OPERATION: generateMipmap: The texture is a non-power-of-two texture or not mipmap complete
GLTexture.js (210,1)
WEBGL11098: drawElements: The texture is a non-power-of-two texture or not mipmap complete
SpriteRenderer.js (371,13)
~~~

**Comment by staff0rd** [comment]
Strangely I have isolated this error to 52af393ab9f5d2bf105cba9e5285dbd894ebc5ae, which looks like a totally irrelevant build server config.  The error occurs on that build however, and not on its precursor b0f63fe3d9a011b64d626f7694916c3eca327ace.

**Comment by GoodBoyDigital** [comment]
Weirdly the error is caused by this update #3036
looking into this now..

**Comment by GoodBoyDigital** [comment]
oh! ok, its todo with the size being power of two and the texture automatically being set to wrap mode. If we change those numbers to be say, 3x3 then we should be all good!

**Comment by themoonrat** [comment]
Ack, sorry, I have mipmaps turned off on my build :( Will make sure to test on default pixi build in the future.
