### ISSUE TITLE
Invalid image type in URL

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#3059]
When given a url witha  query string, the IMAGE_TYPE regex fails:

https://github.com/pixijs/pixi.js/blob/dev/src/core/const.js#L299

Imported from [this comment](https://github.com/pixijs/pixi.js/issues/2903#issuecomment-251063579):

```
Error: Invalid image type in URL.
at BaseTexture._updateImageType (http://xxxx/js/pixi.js?4:22379:23)
at HTMLImageElement.source.onload (http://xxxx/js/pixi.js?4:22283:27)

(url: "src/img/../img/npc/xxxx.png?v=0.4.0.R42180")
```

This bug was caused by #2614.

**Comment by Dadibom** [comment]
Still doesn't work in 4.1.0

**Comment by englercj** [comment]
Can you clarify what "doesn't work" means please? When I wrote that fix it did in-fact fix the error for me, and it is currently working in the examples.

**Comment by Dadibom** [comment]
Sorry, I just saw the same error pop up and assumed that it was still broken. But in fact, it wasn't the exact same error. This time it's because I load images from a source without .png in the url. I would really like a way to keep doing this.

**Comment by Dadibom** [comment]
You want a new issue for that?

**Comment by englercj** [comment]
Yes, please.

**Comment by Dadibom** [comment]
Alright, sorry for the confusion. #3159
