### ISSUE TITLE
Post ES6 conversion ruins JSDocs

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#3061]
The output of the docs just ends up in tons of 'PIXI.module.exports' listings down the side and such.

**Comment by englercj** [comment]
I recently change the jsdoc dep to use the latest master which fixes a few of these issues:

https://github.com/pixijs/pixi.js/blob/dev/package.json#L69

But there are still places where it needs some comment cleanup and other things. I'll try to get to this on the weekend.

**Comment by themoonrat** [comment]
Cool, I'll take a look if I can. 
PS. They've just released 3.4.2 officially, so can change the package.json back from using the master

**Comment by englercj** [comment]
Oh sweet, thanks for the heads up

**Comment by englercj** [comment]
Should be fixed now in dev. Finally remembered how I did this in Fae, its a stupid hack until jsdoc3/jsdoc#1137.

**Comment by englercj** [comment]
We have some cleanup to do still, things not in the right namespaces and such. But the docs are generating correctly now.
