### ISSUE TITLE
MovieClip completing conditions

### ISSUE THREAD

**Issue by motan** [pixijs/pixi.js#3068]
I need a clip with the following behavior: after some object is hovered the clip starts to play and it is looped. On click or mouseout from that object clip should play until its end and stop. The way I did this is changing loop property for the clip from true to false. In this case update method starts to check if clip is finished and then stops it. But sometimes it stops it immediately. The problem, as I can understand is that the total number of frames is comparing with the _currentTime property. After a few seconds the time becomes bigger than the number of frames and will be never less than it. 

```
else if (this._currentTime >= this._textures.length && !this.loop)
    {
        this.gotoAndStop(this._textures.length - 1);

        if (this.onComplete)
        {
            this.onComplete();
        }
    }
```

So my clip just stops at the frame it is on. Maybe there is another method to make the clip do what it should?

**Comment by ivanpopelyshev** [comment]
Feel free to hack it, its just a JS class. You can also make a PR of it :)

**Comment by motan** [comment]
Ok. I just thought about not to break something)

**Comment by englercj** [comment]
You can always extend the MovieClip to your own class and override the behavior you want to change.
