### ISSUE TITLE
anchor.set will interpolate even with "roundPixels = true" renderer option.

### ISSUE THREAD

**Issue by ThomasDeutsch** [pixijs/pixi.js#3072]
In PIXI 4.0.3 i will get slightly blurred text if i set the anchor to other values than 0 or 1.
The roundPixels renderer option seems to be ignored in this case.

```js
	var txt = new PIXI.Text("This can appear slightly blurred");
 	txt.position.x = 33;
	txt.position.y = 33;
	txt.anchor.x = 0.5;
```

**Comment by englercj** [comment]
Does this happen on both renderers? Do you mind setting up an example that we can reproduce with?

You can use this link in jsfiddle (or wherever): https://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js

**Comment by kaansoral** [comment]
~Off topic, Text's are so challenging to get right with PIXI, and probably everywhere else too

I was haunted by various blurred Text issues too, my solution was to render Text's 4X, shrink them 0.25, and try to ignore the quality / postpone the issue

**Comment by ThomasDeutsch** [comment]
Here is the fiddle:   [text anchor + roundPixels](http://jsfiddle.net/sD8Tt/305/)
I was not able to reproduce the bug.
Sorry!
