### ISSUE TITLE
Internet Explorer using SVG Sprite not showing.

### ISSUE THREAD

**Issue by Hidejec** [pixijs/pixi.js#3075]
It doesn't work on IE10 and IE Edge. Nothing is shown. No error occured in the debugger on IE Edge. Switching to IE10 using Canvas Renderer it says "SecurityError" on the console. Sprite not showing on IE. 

I tried to pull the latest dev build but still no luck. 
After pulling the latest build, "SecurityError" occured on Edge using WebGL or CanvasRenderer.

**Comment by englercj** [comment]
Potentially related: #2510 and #2928.

Also, is this SVG from a different domain than your app? There are issues trying to render cross-domain images, especially in IE.

**Comment by RanzQ** [comment]
Could you provide a codepen, jsfiddle or some code? For me Edge works but IE10 throws an error that is unrelated to SVG: `Object doesn't support property or method 'assign'`, I guess it's related to #2968.

**Comment by Hidejec** [comment]
@RanzQ http://codepen.io/RanzQ/pen/bwdLOv not working on my IE edge, the Sprite bunny not showing.

**Comment by RanzQ** [comment]
@Hidejec Any errors? And which OS and Edge version?
