### ISSUE TITLE
pixi v4 initialization slower than v3.

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#3076]
I'm using a custom build of pixi v3 and pixi v4 excluding modules accessibility, interaction, mesh, particles.

In my project the time to first texture rendered is crucial, and I tested that with pixi v4 the initialization of pixi (creation of the renderer (autoDetect Renderer)) is much slower than the custom build in pixi v3.

Any suggestion on how to speed up this function ? Have you planned to work on it ?

**Comment by photonstorm** [comment]
You've obviously profiled it and got some time stats, so what kind of 'slower' are we talking about here? 500ms? 5secs?

**Comment by JenGL** [comment]
I need it to be performant on mobile device, in my device pixi v3 it is around 190ms, in pixi v4 it's 350 so it's 160

**Comment by JenGL** [comment]
<img width="357" alt="schermata 2016-10-07 alle 12 20 04" src="https://cloud.githubusercontent.com/assets/17526265/19186836/6fc1f888-8c88-11e6-9ceb-7a089a136677.png">

**Comment by GoodBoyDigital** [comment]
Hi @JenGL, Can you share the code that you are testing with please? Cheers!

**Comment by JenGL** [comment]
This is for pixi v3: https://jsfiddle.net/vLesgdnj/
results:
` Pixi.js 3.0.10 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 
175.93000000000006
143.1300000000001
146.5050000000001
147.59500000000025
178.00499999999988
182.75000000000023
113.24999999999955
101.35500000000002
mean :148.56500000000003`
This is for pixi v4:  https://jsfiddle.net/a61q9y70/
results:
`Pixi.js 4.0.3 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 
340.9100000000001
148.80999999999995
161.28499999999985
221.1450000000002
288.9250000000002
260.4650000000006
268.0600000000004
205.23499999999967
mean :236.85437500000012`

Tested on Android 6, device: OnePlus X, Chrome 53.0.2785.124

The gap become more evident with slower device, with PCs it is almost 0.

**Comment by ivanpopelyshev** [comment]
Oh, thats interesting :)

**Comment by kaansoral** [comment]
I wonder how's the situation on an iPhone 5S (outdated but capable)

Android is shit, you never know why something is slower, or doesn't work, too much segmentation, too much control at the hands of shitty manufacturers

**Comment by englercj** [comment]
Here are 3 CPU profiles, one from v3, and one from v4 release. The v4 one is definitely longer, and it seems like a good chunk of that time is in initializing the shaders.

We initialize more shaders in v4 than we did in v3, and our `gl.getShaderParameter` calls are taking 2-5x as long as they did in v3. Not 100% sure why that is though...

We could wrap the compile success checks in `// @if DEBUG` so they compile out in production builds?

[cpu-profiles.zip](https://github.com/pixijs/pixi.js/files/516451/cpu-profiles.zip)

**Comment by GoodBoyDigital** [comment]
interesting stuff! did not know you could get that graph in chrome! Thats amazing!

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital in DevTools under "Profiles"
![screen shot 2016-10-07 at 3 13 54 pm](https://cloud.githubusercontent.com/assets/864393/19202524/b1068530-8ca0-11e6-8e4a-630fce6947b5.png)

**Comment by JenGL** [comment]
the init time with the last release is even slower: https://jsfiddle.net/a61q9y70/1/

**Comment by RainingChain** [comment]
Caching the result of isWebGLSupported() would greatly improve the performance. What's what takes most of the time.

**Comment by s-r-x** [comment]
> Caching the result of isWebGLSupported() would greatly improve the performance. What's what takes most of the time.

thank you! <3

**Comment by bigtimebuddy** [comment]
Merge PR to cache webgl util
