### ISSUE TITLE
Video not playing in iOS

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#3078]
The video examples (using latest dev) do not work in iOS Chrome or mobile safari.

Chrome plays the video full screen and Safari shows a black empty stage.

I think this is due to security reasons - the HTML video cannot autoplay if it has audio.

**Comment by weepy** [comment]
referencing #3066

**Comment by themoonrat** [comment]
Which ios version are you testing against?

**Comment by weepy** [comment]
10.02

**Comment by pr1ntr** [comment]
for ios 10, use playinline attribute

```
<video playsinline ...>...</video>
```

**Comment by englercj** [comment]
Going to close this in favor of tracking on #3112.
