### ISSUE TITLE
Events keep on propagating to the DOM event with autoPreventDefault=true

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#3079]
**First/Main Issue**

As far as I guessed, `autoPreventDefault=true` should prevent events caught by the PIXI Canvas to propagate further on default, but it doesn't work

For example, I click an in-game NPC, an HTML dialog opens, the click hits that new HTML dialog too, pretty bizarre

---

**Second/Curious Issue - Not directly related**

Second issue that I just noticed, when you put a small canvas, on top of a full page canvas, both canvases capture all mouse move events, even though the move is outside the smaller canvas

I wanted only the small canvas to capture the move event, stop propagation, so I can detect which canvas the mouse is on, doesn't work, fails miserably

Second issue just made me realise I still have no idea how PIXI interaction works

I can patch the first issue manually, just wanted to report my experience, I've checked the docs, but as far as I see, they don't cover the interactivity logic, I've re-inspected the sources, got no leads from there either, and created this issue later on

**Comment by englercj** [comment]
> As far as I guessed, autoPreventDefault=true should prevent events caught by the PIXI Canvas to propagate further on default, but it doesn't work

`event.preventDefault()` prevents the default action a browser would take when that event occurs. It *does not* stop the propagation of the event. That is what `event.stopPropagation()` is for.
