### ISSUE TITLE
Cannot find a way to get the pixel data from texture or sprite.

### ISSUE THREAD

**Issue by ben0bi** [pixijs/pixi.js#3080]
Hello. I don't know if I miss something, but...

How can I get the raw pixel array of a texture? Every and every post talks about putting stuff onto a RenderTexture but there is absolutely no post about how to get the data from that texture.

I need the pixel data to output it with *another protocol* to a self made LED-strip-screen.

I render a RenderTexture with my whole output screen in the browser, create a sprite from it and add that to a new container, resize it to the LED-screen size and render it (scaled) to another RenderTexture....and now I am stuck by not getting this damn pixel data.

I post this as an issue because absolutely nowwhere is *something* about getting the data in a raw format. Only about PUTing data on the texture/sprite/container.

So, my request is: Please add a function RenderTexture.getPixelArray()/getRawData() or something like that. Or link me to the appropiate website where this is explained, I searched about 3 hours and found nothing.

[EDIT] there must be a webGL way, with NOT putting the stuff on a canvas and...so...on...don't you think?

Thanks in advance.
PIXI is great, just to say.

Regards,
ben0bi

**Comment by englercj** [comment]
Look at the WebGLExtract API:

https://github.com/pixijs/pixi.js/blob/master/src/extract/webgl/WebGLExtract.js

`PIXI.extract.webGL.pixels(renderTexture)`

**Comment by ben0bi** [comment]
Thank you very much. It would be great if this is referred in the docs, Texture-classes, with a link.

**Comment by ben0bi** [comment]
I get "Uncaught TypeError: Cannot read property 'webGL' of undefined"

Do I have to add the class manually?

**Comment by ivanpopelyshev** [comment]
V4

```js
renderer.extract.pixels(myContainer)
```

That's how it works: https://github.com/pixijs/pixi.js/blob/master/src/extract/webgl/WebGLExtract.js#L126

I am not sure how did it work in V3, I'm looking at the code and just cant find it :( I remember there was something

**Comment by ben0bi** [comment]
Oh I see here, I do not need a second renderTexture to render the scaled container, seems like I can just use the container itself. (...pixels(container)), very nice very nice. *downloading v4, looking if it works.*

[closed for now ;) ]

**Comment by ivanpopelyshev** [comment]
Oh, there's something:

```js
var canvas = renderTexture.getCanvas();
var pixels = renderTexture.getPixels();
```

It is here: https://github.com/pixijs/pixi.js/blob/v3/src/core/textures/RenderTexture.js#L392

**Comment by ben0bi** [comment]
a little bit of nice makes the spice. :) thanks.

**Comment by ivanpopelyshev** [comment]
Just remember that its a slow method. Every upload/download of texture from/to GPU is slow.

**Comment by ben0bi** [comment]
Yeah but I need the bytestream to output it to the LED array. Is extract faster?

**Comment by ivanpopelyshev** [comment]
No, its slow in general. You can do that may be one time per frame, but not more :) Also you don't have to call "renderer.render" if you only need that output. "pixels" has one inside.

**Comment by ivanpopelyshev** [comment]
How big is your LED?

**Comment by ben0bi** [comment]
The size of the LED screen should be adjustable, that is why I scale the output with a renderTexture + Sprite combination. It is fast enough each 10 frames for now. We can right now control about 300 LED without flickering (serial data speed issues), so the screen will not be really big, only look big because of big LEDs.

Really thanks for your help. I will post some photos or a utube video when it's done and working.

**Comment by ben0bi** [comment]
Here is the first image, proofing that it *may* work. 400x400 scaled down to 40x40 and then put out as html text image. (once)

![image](https://cloud.githubusercontent.com/assets/14248626/19224555/b57c1974-8e88-11e6-99e2-d62d88044b26.png)

Thanks, guys.
