### ISSUE TITLE
Graphics.lineStyle with Graphics.drawCircle produces weird figures

### ISSUE THREAD

**Issue by vlucendo** [pixijs/pixi.js#3082]
Hello,

Sometimes, specially with big renderers and big line widths, Graphics.lineStyle and Graphics.drawCircle produce weird figures.

To reproduce this issue paste the following code on the [examples code box](http://pixijs.github.io/examples/#/basics/basic.js):

``` js
var renderer = PIXI.autoDetectRenderer(2000, 2000,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

var circle = new PIXI.Graphics();

circle.lineStyle(300, 0xff3600, 1);

circle.drawCircle(1000, 1000, 600);

stage.addChild(circle);

// start animating
animate();

function animate() {
    requestAnimationFrame(animate);

    // render the container
    renderer.render(stage);
}
```

The result is this:

![image](https://cloud.githubusercontent.com/assets/11018451/19223335/777e3e2e-8e6d-11e6-8c12-fd81b2276fc0.png)

If I change the line width from 300 to 200, the circle is drawn as it should:

![image](https://cloud.githubusercontent.com/assets/11018451/19223345/d0563be6-8e6d-11e6-8956-0b4426d72435.png)

What can be causing this?

**Comment by GoodBoyDigital** [comment]
This seems fixed in the latest branch! 👍 Let me know if this is working for you. Cheers!
