### ISSUE TITLE
SVGs not rendering in Chrome

### ISSUE THREAD

**Issue by prime-ralph** [pixijs/pixi.js#3085]
For some reason, the demo pen used in #2510 (https://jsfiddle.net/vwzjzn4h/1/) shows pixi.js unable to render SVG to canvas properly (yes, I changed the js used in that pen to 4.0.3, the latest release, but somehow even as it uses 3.0.x it still does not show the svg).

I tried reproducing it with a fresh pen since I was seeing this in my current project: http://codepen.io/prime-ralph/pen/dpmjdq?editors=0010 (I included a sample png to show I was correctly rendering a PNG to canvas)

Is it a bug or I'm just doing something wrong?
Will try to test a few things more, will be reporting back if I find anything.

And I tried it already with a local SVG, not this one borrowed from @RanzQ. Tested with the latest version of Chrome (53.0.2785.143 m). Will try this with another browser later.

**Comment by themoonrat** [comment]
Trying on the latest dev build of PIXI,
http://jsfiddle.net/f8fu0a84/1/
It flags up an error in the console

> pixi.js:22488 Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.(…)

**Comment by ivanpopelyshev** [comment]
Can you make example with loader, and render only onload?

**Comment by prime-ralph** [comment]
@ivanpopelyshev Apparently I was calling the render function before the SVG was loaded. Using requestAnimationFrame I was able to render the stage at some point after the SVG was loaded.

Seems like even if you use a loader to load an SVG does not mean it has been loaded as a texture already. Will update pen.

**Comment by prime-ralph** [comment]
Pen has been updated. Leaving it as a basic example of how not to load things :D I just wish this was documented somewhere.

**Comment by themoonrat** [comment]
It would be a great help if you submitted a PR with the added documentation in the relevant location to help the next person who may have this issue.

**Comment by prime-ralph** [comment]
Will do.
