### ISSUE TITLE
How to pronounce pixi ? And what's mean ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3093]
Could you tell users on Homepage or README.md ?

In non-Latin language speaking countries ,  it's hard to guess the pronunciation, I think.

I'm a Chinese guy , and my english is very poor .

**Comment by photonstorm** [comment]
Like this: http://www.dictionary.com/browse/pixie

**Comment by finscn** [comment]
@photonstorm  , thanks.  But  what's mean of it ? Why named PIXI ?

**Comment by englercj** [comment]
Because it's magic!

**Comment by GoodBoyDigital** [comment]
Dang straight! Its also close to the word 'pixel'

**Comment by finscn** [comment]
Thank you for all  :)  . it's time to close it .
