### ISSUE TITLE
Loader Progress event is incorrect when loading Sprite Sheets

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#3095]
Seems that the loader is currently displaying the incorrect progress when loading sprite sheets.
Loading 3 sprite sheets reports progress as going up to 150%. I have attached the example I have been testing with:

[loaderissue.zip](https://github.com/pixijs/pixi.js/files/522889/loaderissue.zip)

Not sure if this is loader of pixi related!

**Comment by englercj** [comment]
Duplicate of #2876, this is a known issue in the resource-loader.

https://github.com/pixijs/pixi.js/issues/2876#issuecomment-245467084

I'm in-progress rewritting for v2 that should solve this issue.
