### ISSUE TITLE
worldTransform resets after width/height access

### ISSUE THREAD

**Issue by asheb** [pixijs/pixi.js#3097]
Hi everyone!
I was writing tests for Pixi-powered UI with nightwatch and stumbled upon this weird behavior:

![pixi](https://cloud.githubusercontent.com/assets/22747/19297130/f372d1b6-906b-11e6-9166-30c8e94793bd.png)

resulting in wrong DisplayObject handling mouse event.

Any ideas why this is happening?
Is it intended behavior? a bug? result of UFO invasion?... %%

**Comment by asheb** [comment]
The problem seems to be that `getBounds` [resets the transform](https://github.com/pixijs/pixi.js/blob/master/src/core/display/DisplayObject.js#L388), which changes it [for all the children](https://github.com/pixijs/pixi.js/blob/master/src/core/display/Container.js#L380) as well, but only the parent's transform is [returned back](https://github.com/pixijs/pixi.js/blob/master/src/core/display/DisplayObject.js#L442).

**Comment by ivanpopelyshev** [comment]
Yes, that's how PIXI behaves when you call getLocalBounds().

@GoodBoyDigital may be just call updateTransform() after getLocalBounds(), that way it wont affect transforms?
