### ISSUE TITLE
[Request] A easy way to create sprite and texture  from HTMLImageElement

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3099]
Now , do it must like this  : 
```
        var baseTexture = new PIXI.BaseTexture( imgElement );
        var texture = new PIXI.Texture(baseTexture);
        var sprite = new PIXI.Sprite(texture);
```
If  let  Texture.from check HTMLImageElement ,  We will  use  Sprite.from(imgElement) for it.

add HTMLImageElement checking after  HTMLCanvaeElement and HTMLVideoElement
like this:

```
    else if(source instanceof HTMLVideoElement)
    {
        return Texture.fromVideo(source);
    }
    else if(source instanceof HTMLImageElement)
    {
        var baseTexture = new BaseTexture(source);
        return new Texture(baseTexture);
    }
```

**Comment by GoodBoyDigital** [comment]
Hi there! 

```mySprite = PIXI.Sprite.from('myImage.png');```

The above is what you are after!

**Comment by finscn** [comment]
@GoodBoyDigital   ,  Sometimes ,  I have load the  image  by  other way (other tool for loading resource ) ,   if use   PIXI.Sprite.from('myImage.png') ,  I have to load the image again .

**Comment by GoodBoyDigital** [comment]
```mySprite = PIXI.Sprite.from(imgElement)``` ?

**Comment by finscn** [comment]
It can't work .  
the source is : 
```
Sprite.from = function (source)
{
    return new Sprite(Texture.from(source));
};
```

**Comment by englercj** [comment]
Right, but we don't check for `HTMLImageElement` so that wouldn't work.

Check our the current `Texture.from` method:

https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Texture.js#L371

passing an `HTMLImageElement` would just return that image element back to you.

**Comment by finscn** [comment]
@englercj  ,  I found the dev branch has the bug   https://github.com/pixijs/pixi.js/issues/3100
