### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by bebensiganteng** [pixijs/pixi.js#31]
Hi, 

is there a way to have a transparent background?

thanks!

**Comment by bradparks** [comment]
and... for those new to pixi.js... wow! sweet!

**Comment by zur4ik** [comment]
I put 
```
var renderer = PIXI.autoDetectRenderer(400, 300, null, true);
```

but my canvas is black anyway. Any ideas?

**Comment by englercj** [comment]
@zur4ik if you are using v3,that is not the proper param for autoDetectRenderer. Check out the v3 docs:

http://pixijs.github.io/docs/PIXI.html#.autoDetectRenderer

**Comment by courtneyvigo** [comment]
@zur4ik - I was having the same problem:

var renderer = PIXI.autoDetectRenderer(256, 256, {antialias: false, transparent: true, resolution: 1});
