### ISSUE TITLE
[Bug]  About Texture.from function  when pass a BaseTexture object

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3100]
Bug at

https://github.com/pixijs/pixi.js/blob/master/src/core/textures/Texture.js#L471

```
    else if(source instanceof BaseTexture)
    {
        return new Texture(BaseTexture);
    }
```

I think it should be 
```
    else if(source instanceof BaseTexture)
    {
        return new Texture(source);
    }
```

**Comment by themoonrat** [comment]
Good spot, PR made to fix :)

**Comment by GoodBoyDigital** [comment]
Hello! The above code is correct. No fix required 👍

**Comment by englercj** [comment]
@GoodBoyDigital are you sure? Looks like it is passing in the BaseTexture class as the first param to the Texture ctor instead of the source. How is that correct?

**Comment by finscn** [comment]
@GoodBoyDigital are you sure?  Please test it .

**Comment by GoodBoyDigital** [comment]
Pretty sure this is correct, Texture constructor expects a BaseTexture rather than an image.

**Comment by GoodBoyDigital** [comment]
oooohh!

**Comment by GoodBoyDigital** [comment]
you guys are correct

**Comment by GoodBoyDigital** [comment]
sorry about that!

**Comment by englercj** [comment]
K, I'm going to revert your revert :P
