### ISSUE TITLE
[Quesiton] About the performance of  utils.removeItems

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3106]
I found  utils.removeItems is this : 
```
    removeItems: function (arr, startIdx, removeCount)
    {
        var length = arr.length;

        if (startIdx >= length || removeCount === 0)
        {
            return;
        }

        removeCount = (startIdx+removeCount > length ? length-startIdx : removeCount);
        for (var i = startIdx, len = length-removeCount; i < len; ++i)
        {
            arr[i] = arr[i + removeCount];
        }

        arr.length = len;
    },

```

Why don't use  : 
```
arr.splice(startIdx, removeCount);
```

I think  arr.splice is more fast than current   utils.removeItems

**Comment by finscn** [comment]
And share one my extension about Pixi.js

```
Container.prototype.renderWebGLChildren = function(renderer) {
    // In one game loop , the render is the last thing about an entity normally.
    // So we could remove the entity in render function.
    var i = 0,
        len = this.children.length;
    while (i < len) {
        var child = this.children[i];
        if (child._to_remove) {
            len--;
            child.parent = null;
            this.children.splice(i, 1);
            this.onChildrenChange(index);
            child.emit('removed', this);
            continue;
        }
        child.renderWebGL(renderer);
        i++;
    }

};

```

When I want to remove a child, don't do it immediately .
When render children , do that  together , it's more fast and reliable.

**Comment by finscn** [comment]
I've  tested , use : 
```
    removeItems: function (arr, startIdx, removeCount)
    {
         arr.splice(startIdx, removeCount);
    },
```

Everything is OK and with better performance .

**Comment by englercj** [comment]
Here is some reading:

https://github.com/pixijs/pixi.js/pull/2205
https://github.com/pixijs/pixi.js/pull/2209
https://gamealchemist.wordpress.com/2013/05/01/lets-get-those-javascript-arrays-to-work-fast/

`splice` is almost always slower than our `removeItems` function, but also `splice` generates a new array every time it runs which can create unnecessary GC burden.

**Comment by finscn** [comment]
Oh, I think  maybe different  js engine will present different result .
I will do more test again. Thanks .

By the way , the Article at 2013 is too old , maybe the conclusion is out.

**Comment by englercj** [comment]
Landscape changes for sure, but like I mentioned the big one for us is that splice creates a new array and we certainly dont want that garbage.
