### ISSUE TITLE
[Suggestion] move the code about Children to a standalone function

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3107]
Like:

```
Container.prototype.updateTransformChildren = ...
Container.prototype.renderWebGLChildren  = ...
Container.prototype.renderCanvasChildren = ...
```

And call them in   updateTransform /  renderWebGL / renderCanvas .

Then we could extend the  Container via override  xxxxChildren .

**Comment by finscn** [comment]
And share one my extension about Pixi.js

```
Container.prototype.renderWebGLChildren = function(renderer) {
    // In one game loop , the render is the last thing about an entity normally.
    // So we could remove the entity in render function.
    var i = 0,
        len = this.children.length;
    while (i < len) {
        var child = this.children[i];
        if (child._to_remove) {
            len--;
            child.parent = null;
            this.children.splice(i, 1);
            this.onChildrenChange(index);
            child.emit('removed', this);
            continue;
        }
        child.renderWebGL(renderer);
        i++;
    }

};

```

When I want to remove a child, don't do it immediately . ( set  child._to_remove=true ) .
When render children , do that  together , it's more fast and reliable.

**Comment by endel** [comment]
Do you have measurements of how faster your approach could be?

**Comment by finscn** [comment]
Hi @endel , performance is not the key point of this thread .
Because my game is special , I just use pixi  as a  render engine , not a all-in-one engine , So my test case maybe useless for other user.

the key is  https://github.com/pixijs/pixi.js/issues/3106

**Comment by GoodBoyDigital** [comment]
In our game engine, we have this logic in our app rather than pixi itself. Main reason being is that the style you are using is not applicable to all situations. Hope that helps!

**Comment by finscn** [comment]
@GoodBoyDigital  , yes ,  you are right .
The logic in the second floor  ( https://github.com/pixijs/pixi.js/issues/3107#issuecomment-253720685 )  is not applicable to all situations. 
But , please FORGET it  . the key of this issue is 
```
Move the code about Children to a standalone function, please.
``` 
 "Move the code about Children to a standalone function" is important for Flexibility and Extensibility.

If don't do this, developer will hard to extend Container for their own situation.

**Comment by finscn** [comment]
I've create a PR  https://github.com/pixijs/pixi.js/pull/3108  for this issues .

**Comment by themoonrat** [comment]
As the PR was rejected, I'm going to close down this issue
