### ISSUE TITLE
texture.destory() seems not work in some conditions

### ISSUE THREAD

**Issue by Icemic** [pixijs/pixi.js#3109]
However, I'm not sure whether it is a bug...

ex.A

``` javascript
setInterval(() => {
    const texture = PIXI.RenderTexture.create(800, 600);
    renderer.render(sprite, texture, false);
    texture.destroy(true);
}, 16);
```

these codes above works fine, but

``` javascript
let t = null;

setInterval(() => {
    t && t.destroy(true);
    const texture = PIXI.RenderTexture.create(800, 600);
    renderer.render(sprite, texture, false);
    t = texture;
}, 16)
```

It seems that `.destroy()` doesn't work (memory increases rapidly), and several seconds later, browser's WebGL function broke down.

**Comment by englercj** [comment]
Weird, just at a glance maybe something to do with the scoping? I'm not sure that from a pixi standpoint these are any different from eachother.

**Comment by ivanpopelyshev** [comment]
Just for the future: do not use destroy(boolean). Please supply the actual stuff: 

```js
texture.destroy({ baseTexture: true }).
```

All destroy API is frustrating, i know :)

**Comment by englercj** [comment]
Whats wrong with `.destroy(true)`? It is explicitly supported on purpose IIRC?

**Comment by Icemic** [comment]
@ivanpopelyshev I try to use `{ baseTexture: true }` instead of `true`, but the problem still exists.

@englercj In fact, those codes in `setInterval` are just my test code. I encounter the problem at first while i just save a texture to a variable, and call `.destory(true)` later.

**Comment by Icemic** [comment]
I made a test file, it has the problem in my device. (Win10 1607, Chrome 53.0.2785.143 m)

[destroy-bug-maybe.zip](https://github.com/pixijs/pixi.js/files/531124/destroy-bug-maybe.zip)

**Comment by GoodBoyDigital** [comment]
looks fixed in latest version! 👍
