### ISSUE TITLE
Questions about how the mask filter is done

### ISSUE THREAD

**Issue by Cazadorro** [pixijs/pixi.js#3111]
I've been looking through [spriteMask](https://github.com/pixijs/pixi.js/tree/ac95866581c66d924924d1438dec775181e50884/src/core/renderers/webgl/filters/spriteMask) in the current repo trying to figure out how I would implement inverse masking for sprites.   First I'm confused as to what other matrix is supposed to be.  In particular I'm confused as to what [calculateSpriteMatrix](https://github.com/pixijs/pixi.js/blob/e9cb6a164157a62bdb82cec49993bf7e12915a92/src/core/renderers/webgl/filters/filterTransforms.js) actually does, it seems that indeed people were confused in the documentation, since a comment literally says 

```
//this...?  free beer for anyone who can explain why this makes sense!
```

half way through.   I'm not sure why this is needed (I'm new to this sort of thing) but wouldn't the mask texture coordinates already be in the same coordinate system as the texture coordinates? Why do we need to apply a filter to get them to a different place every time you mask? If I try to mask an object, but my mask is some where off in the opposite corner, then the object just doesn't get drawn, not sure why we need to do any sort of texture coordinate translation. 

We see the use of that matrix in the [spriteMaskFilter.vert](https://github.com/pixijs/pixi.js/blob/ac95866581c66d924924d1438dec775181e50884/src/core/renderers/webgl/filters/spriteMask/spriteMaskFilter.vert) shader.  I have specific questions about this shader as well.   Since it is so small, I'll just copy paste the code so you don't have to click another link to see what I'm talking about. 

```
attribute vec2 aVertexPosition;
attribute vec2 aTextureCoord;`

uniform mat3 projectionMatrix;
uniform mat3 otherMatrix;

varying vec2 vMaskCoord;
varying vec2 vTextureCoord;

void main(void)
{
    gl_Position = vec4((projectionMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);
    vTextureCoord = aTextureCoord;
    vMaskCoord = ( otherMatrix * vec3( aTextureCoord, 1.0)  ).xy;
}
```

First I can't find where the code to actually input vertex position attributes are, and I'm not entirely sure what that value is supposed to represent.  I'm guessing it has something to do with translating two different texture coordinate values some how, but I don't see where that is explained or how that would work out.  Other than that I believe our aTextureCoord are the texture coordinates of our source sprite texture, projection matrix is the matrix to translate to screen space, and othermatrix is that odd transformation matrix between the mask and the source. 

for gl_position, I'm guessing we multiply each vertex in the texture by the projection matrix to correctly output the vertex to screen space?  

We obviously just pass through texture coord (though, I'm confused as to why this wasn't just passed on to the fragment shader rather than having to be passed through a vertex shader variable, though that may be because I'm just new to this) 

then we multiply our strange mask/source matrix by each position to get mask texture coordinate positions, though I'm still confused about that, is it trying to expand the texture coordinate range to make sure that it at least encompasses the source sprite?  Why doesn't this mess with sampling (ie aren't the chosen texture points there normalized as well? so grabbing value at -1,-1 would just be the bottom left of the texture?)

Next we have the [fragment shader](https://github.com/pixijs/pixi.js/blob/ac95866581c66d924924d1438dec775181e50884/src/core/renderers/webgl/filters/spriteMask/spriteMaskFilter.frag)

```
varying vec2 vMaskCoord;
varying vec2 vTextureCoord;

uniform sampler2D uSampler;
uniform float alpha;
uniform sampler2D mask;

void main(void)
{
    // check clip! this will stop the mask bleeding out from the edges
    vec2 text = abs( vMaskCoord - 0.5 );
    text = step(0.5, text);
    float clip = 1.0 - max(text.y, text.x);
    vec4 original = texture2D(uSampler, vTextureCoord);
    vec4 masky = texture2D(mask, vMaskCoord);
    original *= (masky.r * masky.a * alpha * clip);
    gl_FragColor = original;
}
```

So we got the mask coordinates and texture coordinates from the vertext shader, the uSampler is from out source texture, alpha is from some sort of global alpha setting, and mask is from the mask texture.

Then the first line comes up and I'm confused again.  Why is it called text? why are we taking the absolute value of the mask coordinates subtracted by a constant?  Why do we have a step function applied to text?  If I understand this correctly it makes sure any of the elements in the vector above zero but below 1.0 are 0.   Not sure why this is useful.  Next I don't understand why we do this 1.0 - max(x, y)?   so now we might actually get values greater than one if both of our coordinates are less than zero initially in vMaskCoord.

Original makes sense getting source color
masky I guess makes sense as well? getting mask color
and setting original makes very little sense. 

 original *= (masky.r \* masky.a \* alpha \* clip);

why are we only multiplying by the red channel of the color instead of doing something with all three?  masky.a, and alpha make sense, but clip is still weird here.  So if we remove clip, we get odd artifacting with parts of the clip appearing the NSEW directions around the clip.  Not sure why this even happens in the first place, but apparently clip fixes that issue and I don't know why.  masky.a should determine what we see of the source (higher mask alpha = higher resulting alpha), and this indeed seems to be the case, but if we do the reverse (1 - masky.a) we don't get the expected inverse masking effect (everything is invisible for some reason), again I'm not sure why. 

Hopefully someone can clear these things up.

**Comment by GoodBoyDigital** [comment]
To inverse the mask you could modify the shader

```original *= 1.0 - (masky.r * masky.a * alpha * clip);```

Hope this helps!
