### ISSUE TITLE
Create an SDF font handler

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#3115]
Right now pixi only has canvas-based text and manually created bitmap fonts. I'd like to also support SDF text directly from a font file.

Parsing library options are listen below. Ideal is small, doesn't have load code (not needed), parses, and creates paths.

https://github.com/Jolg42/awesome-typography

| Library | Stars | Size | Supported Fonts | Loads | Parses | Creates Paths | Multi-line Layout | Notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [opentype.js](https://github.com/nodebox/opentype.js) | 1136 | 288k | TTF, OTF, WOFF | ✓ | ✓ | ✓ |  | Layout added with [opentype-layout](https://github.com/Jam3/opentype-layout) |
| [Typr.js](https://github.com/photopea/Typr.js) | 271 | 60k | TTF, OTF |  | ✓ | ✓ |  | Was created to solve some issues with opentype.js |
| [fontkit](https://github.com/devongovett/fontkit) | 85 | 379k | TTF, OTF, WOFF, WOFF2, TTC, DFONT | ✓ | ✓ | ✓ |  |  |
| [opentype](https://github.com/bramstein/opentype) | 63 | ?k | TTF, OTF, WOFF, WOFF2 |  | ✓ | ✓ |  | node only? |
| [webfontloader](https://github.com/typekit/webfontloader) | 4961 | ?k | ? | ✓ |  |  |  | Mostly just an observer for loading CSS fonts |

**Comment by ivanpopelyshev** [comment]
There are other things with fonts. For example, use R-G-B channels as different spritesheets to cover all asian symbols.

**Comment by PixelsCommander** [comment]
Hi @englercj , @ivanpopelyshev ,

I am currently busy with this since nothing changed since my last year request https://github.com/pixijs/pixi.js/issues/1679 . 

So the plan is to create Mesh and pass point coordinates as point attributes + texture coordinates of characters as additional buffer. Is this possible to attach additional buffer to mesh without reinventing the renderer wheel?

Any suggestions on implementation?

Ivan, not sure I understood you correctly as for RGB. Is it intended to be a kind of compression to keep 3 times more data?

**Comment by PixelsCommander** [comment]
@englercj @ivanpopelyshev let me know your thoughts on this

https://github.com/PixelsCommander/pixi-sdf-text let me know you thoughts on this

@ivanpopelyshev figured out what you mean for RGB. Scheduled for next updates. 

Current priority is multiline rendering and max compatibility with regular Text.

**Comment by ivanpopelyshev** [comment]
RGB - yes.

What's your email? I'll invite you in slack.

**Comment by finscn** [comment]
Mark by @finscn

**Comment by englercj** [comment]
@soimy This is a great time to put in a PR to v5 (`next` branch).

**Comment by soimy** [comment]
Need some discussion on TTF/OTF parse module.
I'm thinking of the necessity of run-time true-type font parser in pixi core. This will add at least 60k+ load of parser code but the benefit of `ttf` resources are not seems to be equal. This feature shall be treated as a `devDependencies`.

Tell me what u think. 
BTW: Can anyone invite me to pixi's slack? slack id: cidstudio@gmail.com

**Comment by my2iu** [comment]
If you need help with this, you can ping me.

I actually just wrote exactly this code for a web vector drawing tool I'm making. Unfortunately, I wrote everything in GWT, and I don't currently have the cycles to rewrite everything in pure JavaScript for Pixi (perhaps, when Google releases their J2CL Java to JS compiler next year, I can just recompile it for JS). 

In my case, the architecture I used was to use Typr.js to parse truetype files at runtime. Then, as each character is displayed, I use a custom ttf renderer (a simple one is actually not much code) to create an SDF on the fly for just the character, and stick it into a cache. And then the SDFs are rendered onto the screen. It's all reasonably fast and code sizes aren't too bad, so I'm not sure if there's any need to precompute the SDF beforehand.

The main drawback is with font sizes. To do things properly, you need to parse the ttf font files yourself, but then you have to bundle a ttf font file into your game. TTF files are only 50KB or so for English-only fonts, but they can be several hundred KB for European fonts, and several MB for non-European fonts. So I'm not sure how practical this approach is for web/mobile games.
