### ISSUE TITLE
Refactor BaseTexture

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#3120]
BaseTexture has grown over time to deal with a wide variety of source objects. Each of which have some special handling necessary. I want to remove the source-type-specific code from BaseTexture into a class for each source type. BaseTexture would then use the proper source type class to manage that source. 

This will hopefully make BaseTexture simplier and allow us to add new sources easier. I also want to make BaseRenderTexture.js and VideoBaseTexture.js into source classes that BaseTexture then uses.

**Comment by ivanpopelyshev** [comment]
That's good idea. But I think we need more stuff in it:

What I want:

1. Store links to alphamask basetexture and may be to normals
2. possibly unload texture from regular memory, store only in webgl
2. Ask loader to do his thing again if texture 

https://github.com/pixijs/pixi.js/projects/2

**Comment by englercj** [comment]
Refactored in v5.
