### ISSUE TITLE
Replace MovieClip with a more robust solution

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#3122]
Currently MovieClip is pretty simple, I'd like to replace it with a more robust animated sprite solution. More similar to what Phaser does for animations.

Ideally it would support:
- Different display times per frame
- Multiple different named animation sequences
- play, pause, reverse, jump

**Comment by kdex** [comment]
It would also be great if there was a more precise means to specify animation speeds. [This](http://pixijs.download/dev/docs/PIXI.extras.AnimatedSprite.html#animationSpeed) isn't very descriptive. 😄

**Comment by themoonrat** [comment]
Bumping to keep this open

**Comment by andrewstart** [comment]
Would we want a singleton animation manager of some sort like Phaser, or purely self contained animation controls like the current AnimatedSprite? Ideally, whatever API we come up with could also apply to pixi-spine with minimal changes (easier with a manager that can wrap the spine API).

**Comment by englercj** [comment]
I think a robust animation manager solution sounds great, but I'm not sure if it belongs in the main repo? Definitely would be easier to start as a plugin and could be promoted to live here later.

**Comment by bigtimebuddy** [comment]
I agree. Something like this is likely to be complex and feature rich. A plugin is good approach to start. It could live in the main repo, and simply be opt-in plugin, like the unsafe-eval plugin we added recently.
