### ISSUE TITLE
Integrate official plugins into the main repo

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#3124]
Currently the GL core library and others are in separate repositories, and I want to bring them into this one. We can still publish them as a separate modules for people who want to use them standalone, but management and development of these plugins would be easier if done here.

**Comment by ivanpopelyshev** [comment]
Totally agree. Also, please look if pixi-display and pixi-compressed-textures can be integrated.

**Comment by thamaranth** [comment]
Is this issue still open, I'd like to contribute.

**Comment by englercj** [comment]
Thanks for wanting to contribute @thamaranth! THis issue is still open since we will be doing it in v5, and it is currently happening on the `next` branch.
