### ISSUE TITLE
Refactor current shader cache

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#3125]
I'd like to refactor the shader cache a bit to be at the GL level. This will allow us to compile shaders less often and to include good metadata about the shader. While the program changes between contexts, the metadata does not; we only need to extract that once.

This also removes the need for parsing shader source text and the bugs associated with that.

Ref: #2999

**Comment by ivanpopelyshev** [comment]
1. Shaders must be compiled lazily.
2. There must be ShaderLib like in Three.js
3. There has to be a way to look at current used shaders for user to put them into pre-loader.
