### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by doender** [pixijs/pixi.js#3130]
I'm using Pixi v4 to show a Spine object (in Ionic 2 / Angular 2 / TypeScript). 

``` typescript
ngOnInit():void {
   this.ticker = PIXI.ticker.shared;
   this.ticker.autoStart = false;
   this.ticker.start();
   this.renderer = PIXI.autoDetectRenderer(400, 600);
   this.canvas.nativeElement.appendChild(this.renderer.view);
   this.stage = new PIXI.Container();
   PIXI.loader.reset()
      .add('avatar', this.file)
      .load((loader:PIXI.loaders.Loader, object:any) => {
         this.draw(object['avatar'].spineData);
      });
   }
}

private draw(spineData:any):void {
    let avatar = new PIXI.spine.Spine(spineData);
    this.stage.addChild(avatar);
    avatar.state.setAnimation(0, "idling", true);
    this.ticker.add(() => {
       this.renderer.render(this.stage);
    })
}
```

When destroying, I do:

``` typescript
ngOnDestroy():void {
   this.ticker.stop();
   Object.keys(PIXI.utils.TextureCache).forEach((texture) => {
      PIXI.utils.TextureCache[texture].destroy({baseTexture:true});
   });
   this.stage.destroy(true);
   this.renderer.destroy(true);
 }
```

On iOS (through XCode) I see that not all memory is returned; around 2-3MB is retained after every destroy. As I need to destroy every 5 minutes or so (length of a typical activity), this quickly adds up which is quite problematic on older devices.

Is there anything I can do to alleviate this problem?

**Comment by englercj** [comment]
Hmm, can you run a memory profile and see what is leaking?

**Comment by ivanpopelyshev** [comment]
Do you use meshes inside spine? Also, please use latest dev version, pixijs.download/dev/pixi.js , I did fix memory leak in Mesh

**Comment by doender** [comment]
@ivanpopelyshev No, I didn't use meshes and I'm using the latest dev version.
@englercj How would I go about doing this? Could you give me some pointers?

**Comment by englercj** [comment]
This is a pretty good article: https://developers.google.com/web/tools/chrome-devtools/memory-problems/

**Comment by lilumat** [comment]
@doender ,
Hello,
I became crazy , i see you have managed to integrate  Ionic 2 RC + Typescript and Pixi v4 in a new project !!!!
I have a problem with rollup.js with Ionic 2 rc.

I know it's not the right place but I am desperate :( :(

Do you have a repo githhub with a blank app ?

Best regards

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍

**Comment by puny-d** [comment]
I have met the same problems with [Dragonbones](https://github.com/DragonBones/DragonBonesJS/tree/master/Pixi) & Vuejs, when I create and destroy pixi application multi times(may be 12+), the memory would increased, which cause page reload on mobile safari
