### ISSUE TITLE
Broken Bitmapfont with more than two font's images

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#3134]
hi..

Using 3.0.11

load bitmapfont with two font's image or more..
and then bitmaptext is broken...

bitmapfont is refered first image 
so characters that refered second image, are all broken.. becuase they refer first image(basetexture)

thx..

**Comment by ivanpopelyshev** [comment]
Got you. Chinese/Korean/Japanese fonts, at least 3 images 2048x2048, may be one with RGB different symbols, ".fnt" output from bmfont

**Comment by themoonrat** [comment]
Fixed for v5 - https://github.com/pixijs/pixi.js/pull/4932
