### ISSUE TITLE
Is there a plugin for perspective transform ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3136]
I found a powerful fork version of Pixi.js https://github.com/gameofbombs/pixi.js , but it is too complex and not based on Pixi.js v4 .
So I want to know where could I find a simple plugin just for  perspective transform .
Thanks

**Comment by ivanpopelyshev** [comment]
Its based on pixi-v4.0.0-rc1. Whats so complex about it? https://gameofbombs.github.io/pixi-bin/index.html?s=flip&f=cards.js&title=Cards

What features from 4.1 do you need in it? I'll make new iteration soon.

**Comment by finscn** [comment]
@ivanpopelyshev  , complex is not correct , sorry.
In fact , I mean there are many features needless for me ,  and many differences between this fork version and origin pixi.js . 

And  the features in  this fork are not designed as plugins or extensions ,  they mix with the origin version, I don't like this way.

I hope the 3D feature could  exists with origin pixi.js as  plugin or extension.

However,  the key point is I just need that  apply  perspective transform on one sprite.

**Comment by ivanpopelyshev** [comment]
It will be possible in pixi-v5 may be ;) To change it only for one sprite, you'll have to add new renderer anyway.

**Comment by finscn** [comment]
@ivanpopelyshev  , So  the answer of "Is there a plugin for perspective transform" is  NO ???

**Comment by ivanpopelyshev** [comment]
@finscn No, you're free to make one. I'd like to see how will you do that without punching straight through the pixi core ;)

You can also hack threejs into pixi, use the same webgl context. For that, please search in gitter.im/pixijs/pixi.js log, we collabed something with someone.

**Comment by finscn** [comment]
@ivanpopelyshev  , thank you & kiss you !

**Comment by finscn** [comment]
Hi, @ivanpopelyshev  ,  I found this https://github.com/evanw/glfx.js  . 
in glfx demo http://evanw.github.io/glfx.js/demo/ , there is a perspective filter is very good.

And in 2D game , perspective filter is just a vision effect,  so  it doesn't need interaction I think.

Could you add it to PIXI.js , please  @englercj  @GoodBoyDigital  ? 

I want to do and tried , but I failed. I'm too weak at WebGL & PIXI.js .
 I don't  know how to find a way to  add a new filter to PIXI.js .

**Comment by finscn** [comment]
There is a simple one  http://jsfiddle.net/rjw57/A6Pgy/

**Comment by finscn** [comment]
@ivanpopelyshev  , I've code a renderer & a filter for perspective transform :

https://github.com/finscn/pixi.js/blob/master/src/extension/PerspectiveRenderer.js
https://github.com/finscn/pixi.js/blob/master/src/extension/PerspectiveFilter.js

Thanks for your help :)

**Comment by ivanpopelyshev** [comment]
@finscn Nice. now make it into a separate plugin like  https://github.com/pixijs/pixi-plugin-example and give us a demo :)

**Comment by glalev** [comment]
@finscn Are these extensions available somewhere? Because I really do need something similar right now and demo looks pretty good, so the source would be really helpful to me.

**Comment by ivanpopelyshev** [comment]
@finscn you had that plugin in different repo somewhere, right?

@glalev we have to ask @GoodBoyDigital what is he using for production. Latest dev-geometry branch has something, there are 2 3d games already:

http://www.bbc.co.uk/cbbc/games/the-worst-witch-magic-adventure-game

https://christmasexperiments.com/2016/14/night-before-christmas/

**Comment by finscn** [comment]
@glalev  , it's here : https://github.com/finscn/pixi.js/tree/master/src/extensions/renderers/perspective

**Comment by finscn** [comment]
@GoodBoyDigital  , you've created many wonderful examples/demos/samples  of PIXI.js , But not opensource ,and no any document/tutorial talk about how to do that . It's so pity.

I've asked at https://github.com/pixijs/pixi.js/issues/3160 . Could you tell why?

**Comment by GoodBoyDigital** [comment]
mainly down to time :/
but when update is ready - i will have some examples to share

**Comment by finscn** [comment]
@GoodBoyDigital  , thanks.  the  https://christmasexperiments.com/2016/14/night-before-christmas/ is amazing! 

I'll close  #3160 .

Thanks
