### ISSUE TITLE
When Graphics  create as a mask of Sprite , the filter is no effect. 

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3139]
I create a  Graphics,   and give it a blur filter .
When it as a normal display object , it is blur.
But when I add it to a sprite as mask , no blur effect.

I want  let the  sprite edge is blur , not sprite body become blur , so I can't add  blur filter to the sprite.

If this way is wrong , what should I do for the goal ?
thanks.

**Comment by finscn** [comment]
@GoodBoyDigital  @englercj  , could you open source of  http://www.goodboydigital.com/client/goodboy/nebulon/ ?

I found many good example of Pixi.js is not opensouce  
(e.g.   some examples  on your homepage  and 
 http:// christmasexperiments.com/experiments/11/  ) .

I think they are very useful for use to learn pixi.js.

**Comment by ivanpopelyshev** [comment]
What if you apply filter to different container? Make two containers, outer with filter, inner with mask. That'll help to determine where exactly is the bug.

**Comment by finscn** [comment]
If  outer with filter , the inner Sprite become blur too . So this way can't work for my gold.

use one photo for info : 

![mask filter](https://cloud.githubusercontent.com/assets/288367/19474068/94afa9e8-9560-11e6-8598-01c3dd26664c.png)

The fat guy in the photo is me . Aha , do you think I'm handsome ?   :p

**Comment by ivanpopelyshev** [comment]
Oh, I've got it. Right, its first time I see FILTER on MASK. The way mask is implemented is much different from filter, and it doesnt call filter logic on itself, so..

Lets mark it as a feature request!

**Comment by finscn** [comment]
Is there any news ?

**Comment by finscn** [comment]
@ivanpopelyshev  ， is there any news ？

**Comment by ivanpopelyshev** [comment]
Yeah, I'm working on pixi-display right now, and new version will have ability to do that kind of stuff. I doubt it will be supported in core pixijs.

I'll use your case as an example :)

**Comment by ivanpopelyshev** [comment]
Actually, the fastest method will be to generate blur mask with renderTexture, and then apply it. Otherwise, it will be done every frame, and that's not good.

**Comment by finscn** [comment]
@ivanpopelyshev  , In my case , the mask is dynamic ( it's a filed of  player's view ) ，so use renderTexture is not a good way.

**Comment by sambshapiro** [comment]
Also wanted to check in on this. I'm working on a face-swapping sort of app, and like @finscn, I have a dynamically changing mask tracked to a user's face via webcam, and I want to feather/blur the edges so it doesn't look like a cutout. @finscn, what did you end up doing?

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
