### ISSUE TITLE
Pixi.mesh.Plane not working

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#3145]
Hi,
I'm trying to display a mesh.Plane, but i was not able to find any doc.
I'm trying this way but it's not working: https://jsfiddle.net/6w0kuqko/59/

Is it bugged or I miss something ?
I add that the API doc is unclear: https://pixijs.github.io/docs/PIXI.mesh.Plane.html

constructor in the example a list of point is passed but in doc 2 numbers are needed.

**Comment by englercj** [comment]
Looks like that is a mistake, it was just copy-pasted from Rope:

https://github.com/pixijs/pixi.js/blob/master/src/mesh/Rope.js#L7-L12

Looks like the Plane is trying to read the Texture's UVs before the image has loaded:

![image](https://cloud.githubusercontent.com/assets/944497/19488294/0b86c7c2-951b-11e6-9f71-060d5c3d31f8.png)

This is a bug, but you should be able to work around it by waiting until the Texture has loaded before putting it in the Plane. Here is an example of this workaround:

https://jsfiddle.net/6w0kuqko/60/

Not sure that looks 100% correct though. May need to look into this a bit more.

**Comment by spaceribs** [comment]
@englercj interestingly, I'm also seeing this bug with the following:
```js
const plane = new PIXI.mesh.Plane(PIXI.Texture.EMPTY, 100, 100);
```

**Comment by englercj** [comment]
Yeah because the `EMPTY` texture is a perpetually non-loaded texture. It never reaches the "ready" state and just sits in a blank unloaded state, so I would expect you to get that error.
