### ISSUE TITLE
Download links for new version broken

### ISSUE THREAD

**Issue by Hachitus** [pixijs/pixi.js#3147]
I don't think this is intentional? The download links for v4.1 are broken in https://github.com/pixijs/pixi.js/releases, e.g.:
http://pixijs.download/v4.1.0/pixi.js
"bad request"
Status Code: 403 Forbidden

**Comment by themoonrat** [comment]
That link works for me?

**Comment by englercj** [comment]
Was a temporary issue (no more than a few minutes) due to the cnames being incorrect. 

It's already fixed, thanks for the report.
