### ISSUE TITLE
looks need touchcancel and unique identifier 

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#3149]
hi.

i think InteractionData need Identifier and 
touchstart ,touchmove, touchend  have to use same inteactiondata 
or can check identifier to use multtouch

and touchcancel need becuase sometimes touchend is disappeared. (ios is happened often)

if attack button's touchend is gone, there give me big problem.

ios touch identifier is increased continuously.

so if pixi don't have own identifier to manage touch, ,, hmm..

i don't have any solution with pixi yet..

3.x 4.x same..

i think touch event operate like phaser touch input
http://phaser.io/examples/v2/input/multi-touch

thx..

**Comment by themoonrat** [comment]
There is a 'touchendoutside' which is often useful to bind to the same function that you call on 'touchend'.   The description according to the docs is

> Fired when a touch point is removed outside of the display object that initially registered a [touchstart]

**Comment by starakaj** [comment]
I'm also finding that I need touchcancel and pointercancel events. Is there any reason that InteractionManager doesn't currently attach to these events?

**Comment by andrewstart** [comment]
Unfamiliarity with the events, I would imagine (first I've heard of them). Do you think it would make sense for those events to fire `touchendoutside` and `pointerendoutside` events within PIXI to streamline what people have to listen for?

**Comment by starakaj** [comment]
In practice that's usually what I end up doing, but it's not always correct. For example, if you're passing your touch events off to a gesture recognizer. Though I agree that it's super annoying to have to listen to three different "touch is over now" events.

**Comment by NicolasVereenoghe** [comment]
@SeminYun there was a pixi.interaction.InteractionData::identifier property, back in pixi 3.1.x.

It was indeed very handy for multitouch / gesturte gameplay. You could distinguish and manage differently each gesture.

I still hope it could be adapted for 4.x, there's nothing that replaced this concept of touch identification.

For 4.x, to manage multitouch environment, and distinguish a touch from another, I update a map of "active" touches, with their coordinates. If something moves, I update the nearest registerd "active" touch coordinates. In this maner, I can give some identification to all registerd touches ... it's quite reliable, but not 100%

**Comment by andrewstart** [comment]
#3546 has been merged, so this should be solved.
