### ISSUE TITLE
Do you use yield/async/await/Promise in new PIXI ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3150]
I see PIXI.js 4.1.0 is based on ES6.

Do you use yield/async/await/Promise in new PIXI ?

I don't hope use them , because there are some performance penalties when  porting yield/async/await/Promise to ES5 .

**Comment by themoonrat** [comment]
None of those are currently used in PIXI

**Comment by GoodBoyDigital** [comment]
indeed!
