### ISSUE TITLE
Interactivity problem with masked elements (v4.1.0)

### ISSUE THREAD

**Issue by jolelievre** [pixijs/pixi.js#3151]
Hello, I just updated pixi with the last update (from 4.0.3 to 4.1.0) and I immediately noticed a bug with elements using masks, the interactivity (over, click, even the cursor changing) don't work when a mask is assigned. I use a PIXI.Graphics object as the mask.

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by jordanhaven** [comment]
Here's a simple fiddle: https://jsfiddle.net/tt4zd79p/

Hopefully that helps.

**Comment by jordanhaven** [comment]
Narrowed it down, the bug appears to have been introduced in this commit: https://github.com/pixijs/pixi.js/commit/475c66b5da11abf367ef0b78d043fa3c9cf3905d

**Comment by jordanhaven** [comment]
One part of the problem appears to be here: https://github.com/pixijs/pixi.js/blob/master/src/core/graphics/Graphics.js#L858

If you remove that conditional, the interaction is detected (cursor changes, click events get all the way through to `dispatchEvent` in InteractionManager, and the correct `displayObject` is identified).

Past that, there are no visible errors with the `displayObject.emit(eventString, eventData);` or `displayObject[eventString](eventData);` calls in `dispatchEvent`, but the handler on the `displayObject` still doesn't fire :/

**Comment by jordanhaven** [comment]
So yeah, just adding a fill to the mask (`mask.beginFill(0xFFFFFF); mask.drawRect(0,0,w,h); mask.endFill()` works around the problem for us. Don't need to set a hitArea or interactive/buttonMode on the mask, either. New (working) fiddle: https://jsfiddle.net/u0z7yasd/

**Comment by staff0rd** [comment]
pen via @ricklamers; http://codepen.io/ricklamers/pen/ygVqaB
reduced; http://codepen.io/staff0rd/pen/qRRmpB?editors=0010

As above, the workaround is to use `beginFill`.

Another workaround is (should be) to generate a texture and use a sprite, although strangely this looks as though the interaction is preserved but the masked item is no longer displayed (BUG);
http://codepen.io/staff0rd/pen/xggdYv?editors=0010

Setting a `filterArea` or `hitArea` on either the mask or the masked item also does not solve this (BUG); http://codepen.io/staff0rd/pen/rjjmQg?editors=0010.

Tests incoming.

**Comment by staff0rd** [comment]
FYI all, @ricklamers; Tests + hitArea/filterArea fix; #3615
