### ISSUE TITLE
[Suggestion] Don't use dynamic parameters of ES6

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3152]
the function with  dynamic parameters  like  this (ES 6) : 
```
   // in  class Container
    addChild(...childs)
    {
        // ......
    }
```
will be transformed to  (ES 5): 
```
    Container.prototype.addChild = function addChild() {
        for (var _len = arguments.length, childs = Array(_len), _key = 0; _key < _len; _key++) {
            childs[_key] = arguments[_key];
        }
        // ......
    }
```

The performance of the porting code is bad.

**Comment by GoodBoyDigital** [comment]
ouch, that is slow :/

**Comment by finscn** [comment]
```
var childs = Array.prototype.slice.call(arguments, 0);
```
is enough.

And why use childs  , children is a good name, I think.

**Comment by GoodBoyDigital** [comment]
thats still creating a new array. The fastest way is how we had it before:

```
var argumentsLength = arguments.length;

    // if there is only one argument we can bypass looping through the them
    if(argumentsLength > 1)
    {
        // loop through the arguments property and add all children
        // use it the right way (.length and [i]) so that this function can still be optimised by JS runtimes
        for (var i = 0; i < argumentsLength; i++)
        {
            this.addChild( arguments[i] );
        }
    }     
    else
    {
          //add child code
    }
```

**Comment by finscn** [comment]
I think best way is separate it to 2 functions:
addChild
addChildren

**Comment by englercj** [comment]
> var childs = Array.prototype.slice.call(arguments, 0);

You should not use that, it causes an argument leak deoptimization. The compiled ES5 from babel is the correct way to convert `arguments` to an array (and is faster that slice anyway).

In this case, not creating the array at all is the obvious solution. However, if the function would be creating an array from arguments anyway then rest-params and the associated transpiled code is perfectly fine.
