### ISSUE TITLE
Custom hitArea for graphics with 4.1.0 broken?

### ISSUE THREAD

**Issue by stbaer** [pixijs/pixi.js#3155]
Hi, I just updated to 4.1.0. I have many graphics with custom hit areas and they all seem to be broken. Can't really provide a reduced test case / fiddle at the moment (no time right now, maybe in the next days) and didn't follow the latest changes enough to have any idea why this is happening. Are there any breaking changes for hitArea's?

**Comment by englercj** [comment]
Not that I am aware of. Will likely need a test case to investigate :(

**Comment by stbaer** [comment]
Here's a simple example that can be run on [pixijs.github.io/examples](http://pixijs.github.io/examples/), just toggle between 4.0.3 and 4.1.0 to see the difference.

```
var renderer = PIXI.autoDetectRenderer(800, 600, { antialias: true });
document.body.appendChild(renderer.view);

var stage = new PIXI.Container();
var graphics = new PIXI.Graphics();
var hitArea = new PIXI.Polygon(190,190, 410,190, 410,210, 190,210);
graphics.lineStyle(2, 0xffd900, 1);

// draw a shape
graphics.moveTo(200,200);
graphics.lineTo(400, 200);

graphics.hitArea = hitArea;
graphics.interactive = true;
graphics.buttonMode = true;

// just for making the hit area visible
graphics.lineStyle(1, 0xff0000, 0.8);
graphics.drawPolygon(hitArea); 

stage.addChild(graphics);

animate();
function animate() {
    renderer.render(stage);
    requestAnimationFrame( animate );
}
```

**Comment by Custi** [comment]
Do you have any idea when this fix will be available via npm?

**Comment by stbaer** [comment]
Hi @Custi - if you want you can use `"pixi.js": "git+https://github.com/stbaer/pixi.js.git#tmp-release"` until this is fixed in a new release in pixi. It's a build of pixi 4.1.0 + this fix.
