### ISSUE TITLE
Needed to downgrade from v4 to v3 because of CORS

### ISSUE THREAD

**Issue by ben0bi** [pixijs/pixi.js#3156]
Hello,
I am loading images from another server for two different projects.
In the first project, I use pixi v3.

I needed over a half day to find out how CORS works and enabling it on the image server.
It then worked fine....for v3.

(Testing from localhost, it's working....)

In the other, newer project, I used v4 [edit] and exactly the same code. (I copied my js file from the first project and used that.) [endedit]

I got this error:
Uncaught SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at ... could not be loaded.  (or something like this.)

I know that the image server has CORS enabled, so what is going on here?

The solution for me was to downgrade to pixi v3 in the second project.

Here is the image for you to test it out on the CORS-enabled image server:
http://46.231.204.122:7777/hallobjects/ada6128e67b999b489ed3ea4c6cc69a4.png

Regards,
Beni Yager

**Comment by photonstorm** [comment]
Yeah your server is set-up fine, you just need to enable CORS on the Loader, which is something like this: `.add('key', 'http://...', { crossOrigin: true },` for the files you want to load.

**Comment by ben0bi** [comment]
I see, thanks.
I thought I had to do this already on the v3 version, so I did not review that part of code.
With that in mind, it was easier to just copy pixi.js from the first project to the second one.
