### ISSUE TITLE
Very critical mouse events issue that affects a small subset - Prevents interaction completely

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#3158]
I've discovered this issue yesterday, thanks to a player who was kind enough to stick around despite the issue, and report the issue, and then again bare with me until we pinpointed the cause

It turned out to be PIXI, the release 4.0.2 build had no issues, but the 4.0.3-dev I was using had the issue, then it turned out a lot more people were experiencing the same issue too

Symptom: Can't "Interact" with anything, none of the mouse events work
Side Symptom: Unlike my Canvas, this player's canvas had a "touch-action: none" - yet the issue persisted after this property is removed too

I think the issue was introduced after 4.0.2, looking at the 4.1.0 release, this caught my eye: https://github.com/pixijs/pixi.js/pull/2997

**Comment by englercj** [comment]
Is it binding mouse events at all?

**Comment by kaansoral** [comment]
The trick of the issue Is, I can't reproduce the issue myself, I've asked about the device, It wasn't a Tablet PC, or anything tricky like that, just a regular Windows PC as the owners described - I've tested Windows 10 myself, no issues, and most people don't have any issues either

So honestly, I have no idea
