### ISSUE TITLE
strange order of matrix operations

### ISSUE THREAD

**Issue by gludion** [pixijs/pixi.js#3163]
Because of a "bug" in pixi-flump-runtime, I've spent some time to figure out the effect of scaling and skewing on a DisplayObject in PIXI, by reading your code here:
https://github.com/pixijs/pixi.js/blob/66462aa91c8df826ace7bc3168cfcb3df71ecd1a/src/core/math/Matrix.js
From your formulas in DisplayObject.setTransform, I understand that what you do is:
- first, you apply a skew matrix 
- then you apply a scale matrix
- then a rotation 
- then a translation

If you choose for example skew.x = 45° and scale.x = 2, you would expect that the object is made twice wider, **and** "skewed" by an angle of 45°. I mean, a real 45°, neither sharper nor smoother.
But what happens actually in the current implementation is that the scale actually **increase** the skew effect and the observed angle is much sharper than 45°, which confirms the order of operations described above.

Instead one would expect:
- first, scale the object 
- then skew the result
- then rotate the result
- then translate the result

This choice preserves a independency of the various effects applied to the object.

Therefore, I tried to find another way to change the transform of the object... but could't find any. Unless I missed something, there is no way besides using scale, skew, and rotation. 

One would expect a displayObject method like
`disp.setTransformMatrix(a,b,c,d,tx, ty)`
Such method can be very useful when you clearly know the matrix of the transform you want to achieve, that's why it's usually provided in display list paradigm.
(side note: from what I understood from the source code, but I may be wrong, I see that there is no localTransform stored anywhere, the actual stored data is globalTransform: weird, what happens if a container is modified do you recursively update all the world transforms of the children? seems cumbersome and probably not very CPU friendly)

Sorry if I missed something, tips and workarounds are welcome.

Some suggestions:
- consider changing the order of operations in setTransform() (but it may break existing apps usings skew extensively)
- consider adding another method: disp.setTransformMatrix(a,b,c,d,tx,ty)

**Comment by ivanpopelyshev** [comment]
Well, i think you are right about skew. 

In Spine they are in different order.

**Comment by gludion** [comment]
I did'nt try Spine, but as far as I remember from tutorials, their IDE focuses more on rotation than skew...
Being stuck with skew issues is rare, because trying to achieve a visual squashing effect is usually ok even if skew is not accurate...
The real problem comes when using third-part tools (animation tools, game engines) built on top of PIXI: they will normally need a proper set transform somewhere...
If it's not available they will need accurate scaling and skewing (rotation can be done by combining 2 skews).
Other issues I've found might be explained by this unusual order of matrix operations:
https://github.com/pixijs/pixi.js/issues/2574
https://github.com/pixijs/pixi.js/issues/1433
https://github.com/pixijs/pixi.js/issues/1156
https://github.com/pixijs/pixi.js/issues/612
...

**Comment by englercj** [comment]
@gludion Thanks for bringing this up. Hopefully we can take a look into it soon. If you are up to making a PR to fix it, that is even better!

**Comment by ivanpopelyshev** [comment]
Yeah, I will approve that PR if you'll make it

**Comment by bigtimebuddy** [comment]
The pixi-animate stuff I've been working on is using skew extensively and PIXI's skewing is consistent with the output of Animate as well as CSS's matrix transform. @gludion could you show an example or visual of what you're describing?

**Comment by gludion** [comment]
@englercj : I digged a little in the Pixi source code (I'm not a heavy user, just know it through Haxe/Flump) and realized that merely modifying setTransform math formula would'nt be enough. Apparently Pixi promises that if an arbitrary matrix in applied to localTransform (in Pixi v4), then pos, rot and skew are updated to match this matrix (which is a not trivial math problem). So perhaps the new way to transform skew into a matrix, would impact this method (aka `Matrix.decompose(transform)`), because it transforms the matrix into skew... I did'nt figure out what strategy Pixi uses regarding the localTransform matrix, normally it's the fastest way to store the transform, but setting the transform directly apparently causes additional computation to set pos, scale, and skew, which seems honorable. Perhaps it should set a "dirty" flag, and compute the desired value only if the user asks for position, scale, or skew.

@bigtimebuddy yeah, it's quite possible for CSS (I didn't test yet). But for flash CS5.5 or flash CC, it's definitely not the same behavior (did'nt check Animate, and it's not impossible that Adobe broke something here)
Just paste the following code
```
container.scale.x = 5;
container.skew.x = Math.PI/4; // skew by 45°
```
after line 27 in this example https://pixijs.github.io/examples/#/basics/container.js and click "refresh".
You should observe that the skew angle is no longer 45°.
In Adobe flash IDE, type "45°" in skew field and "500%" in scaleX, and you will notice that skewing angle is preserved.

**Comment by gludion** [comment]
I've just tested how skew and scale are performed in CSS transform:
1. go to http://www.w3schools.com/css/tryit.asp?filename=trycss3_transform_skewx
2. replace line `transform: skewX(20deg) ` with transform:` skewX(20deg) scale(5,1);`
3. observe that despite the big amount of scaleX, the skew angle isn't changed.
4. now write the **reverse** order of operations: ` scale(5,1) skewX(20deg) ;`
5. This time, the div was first skewed, **then** scaled, which causes a sharper skew angle.

Conclusion: in CSS transform, you can actually control the order of matrix operation (from right-to-left).

As I tried to explained above, I've no plan to fix the problem described in this topic because it requires a deeper understanding of PIXI's policy regarding localTranforms, worldTransforms and PIXI's apparent promise of skew, rotation properties always being accurate.

**Comment by ivanpopelyshev** [comment]
I'd say we add a flag in the transform :)

**Comment by bigtimebuddy** [comment]
This has been fixed on **dev** http://pixijs.download/dev/pixi.js
