### ISSUE TITLE
v4.1.0 tag has no commit history

### ISSUE THREAD

**Issue by M1cha** [pixijs/pixi.js#3164]
why does this 'tag' have one commit only with all the code stashed?
That's really not how git tags works and the previous tags aren't like that.

**Comment by englercj** [comment]
We dont commit builds anymore in our main branches, however bower requires the builds to be there for it to work properly.

To work around this, at release time we bundle up everything and commit to the `release` branch and tag there. This is so bower can pickup the right state of the repo without us having builds in the main lines.

**Comment by M1cha** [comment]
oh I didn't know that bower uses git. I thought it can use github releases.

**Comment by bigtimebuddy** [comment]
Alternatively, we deprecate Bower support. Bower has a smaller package ecosystem than npm anyways. There are lots of current solutions for getting pixi in your project (e.g. CDN, pixijs.download, npm, direct download). Not sure the juice is worth the squeeze in this case, and I agree that this is a less than perfect solution.
