### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by hendrysadrak** [pixijs/pixi.js#3166]
Can you please update https://pixijs.github.io/docs/

![image](https://cloud.githubusercontent.com/assets/4000963/19553137/986b5be8-96bb-11e6-904f-50ede530a6f8.png)

**Comment by englercj** [comment]
http://pixijs.download/v4.1.0/docs/index.html

We build and deploy docs to AWS every build. You can view any versions docs with that URL (replacing the version as appropriate).

**Comment by themoonrat** [comment]
That github link now redirects to the latest release docs
