### ISSUE TITLE
A issue about index.js and Loader

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3169]
I don't use  PIXI.loaders.Loader in my game.
so I build PIXI exclude loaders.
But  in src/index.js  , the code like this : 

```
const loader = new loaders.Loader();

export { loader };

```

The loaders module is not necessary. 
User could load  image via other ResourceLoader Tool , and create Texture/Sprite via  Texture/Sprite.from(HTMLImageElement) .

So I hope it could check  loaders  before use it.

```
//  I've test the code below , it's OK
let loader;
if (typeof loaders.Loader === 'function')
{
    loader = new loaders.Loader();
}
export { loader };
```

**Comment by englercj** [comment]
Good catch!
