### ISSUE TITLE
[Suggestion] Leave Graphics and rendering related functions in core, others move to helper

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3177]
I found there is a PR https://github.com/pixijs/pixi.js/pull/3175 about checking isMoblie.
You want to add it to core.utils 

I hope  PIXI.core could be a pure-rendering module , and the features not about rendering could be excluded when  build.

In fact , I used pixi as a pure rendering layer ,  the other features for Game Engine I used other frameworks.

**Comment by englercj** [comment]
This has been the plan since v2, and each version we have gotten closer and closer to this goal. We plan to get even closer with v5.

Thanks for the suggestion.
