### ISSUE TITLE
Why set  func-names be always ? 

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3178]
I found in PIXI.js , when you defined a function on prototype , you used code lile this : 

```
core.RenderTexture.prototype.getImage = function getImage(target)
{
// ......
}
```

why don't like this : 

```
Foo.prototype.bar = function(args)
{

}
```

When use  `Foo.prototype.bar = function bar` , there will be a  named function in current scope (but it's useless ) , I think it will take some issues. e.g.  there's  a other var/function  named `bar` .

I suggest use  `Foo.prototype.bar = function(args)` and close `"func-names": [2, "always"]`  in `. eslintrc.json`

**Comment by englercj** [comment]
Because we prefer functions to be either:

1) Arrow functions for anonymous, or
2) Named function declarations (not expressions)

There are very few cases where you shouldn't use an arrow function as an anonymous expression, and we dont use the `.prototype.X =` synxtax anywhere except `deprecation.js` so it isn't a big deal.

**Comment by finscn** [comment]
@englercj  , but in built file pixi.js , there are many   ``` .prototype.xxx = function xxx```.

**Comment by bigtimebuddy** [comment]
@finscn Those function names are generated that way in the built file because of Babelify (which converts the ES6 to ES5)

**Comment by finscn** [comment]
@bigtimebuddy , Is there a switch to turn off this feature ?

**Comment by bigtimebuddy** [comment]
I don't know.

**Comment by stbaer** [comment]
The switch would be to import or require the source instead of the build files.

**Comment by englercj** [comment]
> @englercj , but in built file pixi.js , there are many .prototype.xxx = function xxx

Is this a problem for some reason?

**Comment by finscn** [comment]
It would pollute the scope ,   there will be a named function in current scope , but it's useless  and  it will take some issues. e.g.  when there's a other var/function with the same name .

**Comment by englercj** [comment]
I don't think it is an issue since it is in generated code, in a scope otherwise unused. Additionally, they are compiled out when minified.
