### ISSUE TITLE
MovieClip.gotoAndPlay skips first frame when called for the second time.

### ISSUE THREAD

**Issue by Tade0** [pixijs/pixi.js#3180]
Hello everyone, first of all thank you for creating such a magnificent library.

Second thing: I haven't found any similar reported issue, so please take a look at this jsFiddle:
https://jsfiddle.net/zxz0se93/6/

**Expected behaviour**
`gotoAndPlay` always starts with the frame number provided in the parameter.

**Actual behaviour**
When `gotoAndPlay` is called for the second time it stays one frame duration at `4` and then starts with `1`.

Tested and reproduced in Chrome and Firefox.

**Comment by staff0rd** [comment]
Fixed in master; https://jsfiddle.net/szdb6gjc/
