### ISSUE TITLE
Polygon default hitArea is shifted

### ISSUE THREAD

**Issue by xetra11** [pixijs/pixi.js#3181]
As I tried to create some hexagons and wanted to make them clickable I realized that its clickable area doesn't fit with the actualy shape matrix.

Here is a fiddle for reproduction. In my case I cannot click the right downer part of the hexagon. The effect after click is the hexagon to be not visible anymore.

https://jsfiddle.net/mbh7nrx4/1/

**Comment by xetra11** [comment]
I just realized that this issue only occured on my windows machine. On my Linux Mint machine it seems to work well. I will try to get further informations about what might be the problem. In the meantime I hope somebody can reproduce this!

**Comment by staff0rd** [comment]
This is fixed in latest by #3165 

https://jsfiddle.net/vteujkmu/1/

**Comment by xetra11** [comment]
thank you!
