### ISSUE TITLE
Make text go in a circle, or along a path?

### ISSUE THREAD

**Issue by trusktr** [pixijs/pixi.js#3182]
Is this possible? For example, like how in SVG we can [make text along a path](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath)?

**Comment by ivanpopelyshev** [comment]
Make a Text, give its texture to Rope :)

**Comment by trusktr** [comment]
@ivanpopelyshev Thanks, seems like the right direction. I want to do something like:

![screen shot 2016-10-29 at 1 21 31 am](https://cloud.githubusercontent.com/assets/297678/19828246/2b6cfe68-9d76-11e6-9973-361dd57b2d43.png)

In that shot, the text follows a circle path, and I've also applied a mask to the text (the mask goes around a similar circular path).

I can imagine making a `Text` follow the points in a `Rope` (haven't tried yet).

Can I also fade the text out? I want to fade it out when it's too long to fit in the circle.

**Comment by trusktr** [comment]
Hmm, Maybe I just make the Text and mask it with a simple linear gradient, make it marquee, then just pass that final texture to the Rope. I think that's the strategy, now just have to learn and make something with Pixi for the first time. :D

**Comment by ivanpopelyshev** [comment]
make a scene with Text and gradient, render it into separate RenderTexture, use that thing for a Rope. Dont forget to free that renderTexture when you stop using it.

**Comment by englercj** [comment]
Seems answered!

**Comment by trusktr** [comment]
@ivanpopelyshev Still reading up. How do I make the gradient? I see in the docs `PIXI.TEXT_GRADIENT` but that's all. Do I create a separate 2D canvas with a gradient then use that as a texture in Pixi? And then when I apply the texture as a mask, will it fade the opacity based on the white/black color of the gradient?

**Comment by themoonrat** [comment]
For a gradient on text, simply apply an array of colours to fill, rather than a single colour.

There is a class called renderTexture. You can create your text, and then render the text to it (just like you have your mein renderer which you can render on a to level container). You can now treat this renderTexture as a normal texture, and use it for creating a Sprite, or in this case, a Rope

**Comment by trusktr** [comment]
I'm having difficulty putting text into a Rope. I can make simple text like this:

```js
    var container = new PIXI.Container()

    var renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, {
        transparent: true,
    })
    document.body.appendChild(renderer.view)

    var text = new PIXI.Text('Some text!', {
        fontFamily: 'Arial',
        fontSize: '50px',
        fill: 'red',
    })

    container.addChild(text)

    renderer.render(container)
```

But the following isn't working:

```js
    var container = new PIXI.Container()

    var renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, {
        transparent: true,
    })
    document.body.appendChild(renderer.view)

    var text = new PIXI.Text('Some text!', {
        fontFamily: 'Arial',
        fontSize: '50px',
        fill: 'red',
    })

    var renderTexture = PIXI.RenderTexture.create(200, 200)

    renderer.render(text, renderTexture)

    var rope = new PIXI.mesh.Rope(renderTexture, [
        new PIXI.Point(0, 0),
        new PIXI.Point(10, 10),
        new PIXI.Point(20, 20),
        new PIXI.Point(30, 30),
    ])

    container.addChild(rope)

    renderer.render(container)
```

It's just blank, no errors. Where the text?

**Comment by trusktr** [comment]
I can't get even the [example from the blog](http://www.goodboydigital.com/the-pixi-js-rendertexture-arrives/) to work, it's just a black empty canvas. I'm trying the following, modified for the latest API:

```js
    var renderer = new PIXI.autoDetectRenderer(800, 600);

    document.body.appendChild(renderer.view);

    var stage = new PIXI.Container

    // create a new render texture..
    var renderTexture = new PIXI.RenderTexture.create(800, 600);

    // create a sprite that uses the new render texture...
    // and add it to the stage
    var sprite = new PIXI.Sprite(renderTexture);
    stage.addChild(sprite);	

    // create an item..
    var text = new PIXI.Text("OH please render me!");

    // render the item it to the render texture..
    renderer.render(text, renderTexture);

    // render the stage
    renderer.render(stage);
```

**Comment by trusktr** [comment]
Scratch that last one, I just needed to change the font fill color to be different than the background.

I can't get the Rope to work. Basically, here's what works using Sprites:

```js
    var sprite = new PIXI.Sprite(renderTexture);
    stage.addChild(sprite);	
    renderer.render(stage);
```

I thought it would be easy to swap the Sprite for a Rope, but apparently not:

```js
    var rope = new PIXI.mesh.Rope(renderTexture, [
        new PIXI.Point(0, 0),
        new PIXI.Point(10, 10),
        new PIXI.Point(20, 20),
        new PIXI.Point(30, 30),
    ])
    stage.addChild(rope)
    renderer.render(stage);
```

That renders nothing.

**Comment by trusktr** [comment]
Okay, finally got it. Had to move the Rope around using a sub-container to see it, so

```js
    var rope = new PIXI.mesh.Rope(renderTexture, [
        new PIXI.Point(0, 0),
        new PIXI.Point(10, 10),
        new PIXI.Point(20, 20),
        new PIXI.Point(30, 30),
    ])

    var ropeContainer = new PIXI.Container
    ropeContainer.position.x = renderer.width / 2
    ropeContainer.position.y = renderer.height / 2

    stage.addChild(ropeContainer)

    ropeContainer.addChild(rope)

    renderer.render(stage);
```

**Comment by trusktr** [comment]
@themoonrat @ivanpopelyshev 

> For a gradient on text, simply apply an array of colours to fill, rather than a single colour.

That's not exactly what I want. I want to make a *mask*. In SVG, I would make a gradient from white to black, then use that as a mask.

For example, I want to mask the text *before* wrapping it around a circle with a Rope. The final effect will be something like this, which was done with SVG:

![screen shot 2016-10-29 at 1 21 31 am](https://cloud.githubusercontent.com/assets/297678/19828246/2b6cfe68-9d76-11e6-9973-361dd57b2d43.png)

I made the following code to generate a gradient texture:

```js
function createLinearGradient(width, height, stops, mapFn) {
    mapFn = typeof mapFn == 'function' ? mapFn : function(canvas) {return canvas}

    var canvas = document.createElement('canvas')

    canvas.width = width
    canvas.height = height

    var ctx = canvas.getContext('2d')
    var gradient = ctx.createLinearGradient(0, 0, width, 0)
    var stopPoints = Object.keys(stops)

    for (var i=0, n=stopPoints.length; i<n; i+=1)
        gradient.addColorStop(parseFloat(stopPoints[i]), stops[stopPoints[i]])

    ctx.fillStyle = gradient
    ctx.fillRect(0, 0, width, height)

    return mapFn(canvas)
}

var gradientTexture = createLinearGradient(400, 200, {
    0:   'black',
    0.2: 'white',
    0.8: 'white',
    1:   'black',
}, function mapToPixi(canvas) {
    return new PIXI.Texture(new PIXI.BaseTexture(canvas))
})
```

Now that I have that gradient texture, how do I mask another texture (or display object?)?

**Comment by englercj** [comment]
if you have a texture that is a gradient, just assign it to a sprite and use that sprite as a mask.
