### ISSUE TITLE
npm Install pixi.js - missing bin folder

### ISSUE THREAD

**Issue by ddennis** [pixijs/pixi.js#3183]
First and foremost - Thank you for a fantastic library.

Doing **npm install** does not include the **bin** folder. Tested with version 4.1.0.
which makes my require and imports fails - **cannot find module pixi.js**

The package.json also seems to point to the bin folder:

`"main": "./bin/pixi.min.js",`

I might be wrong, but i would expect all files to be included. If i need to install directly from the release branch, the documentation needs to be updated. 

`npm install https://github.com/pixijs/pixi.js.git#release -D`

Thanks
/Dennis

**Comment by bigtimebuddy** [comment]
Hey @ddennis. 

Unfortunately, we no longer include the *bin* folder in our dev or master branches. It was causing issues whenever people trying to make PRs and is generally not a good version control practice. The *bin* folder is available on the release branch, as you've found out. Alternatively, you can also include directly from our download links, e.g. http://pixijs.download/v4.1.0/pixi.js or build pixi.js locally `npm install && npm run build`. 

We'd definitely welcome a PR for updating documentation that mentions this. Thanks.

**Comment by ddennis** [comment]
I will try to do a PR.

I have tried to figure out how it would be possible to make `npm install pixi.js` pull from the release branch and not master. But it seems you manually have to npm publish from the release folder 
Maybe someone else knows how to fix this.

**Comment by englercj** [comment]
It should be included because when running the publish commands it also builds everything then publishes:

https://github.com/pixijs/pixi.js/blob/master/package.json#L38

Since `bin/` is in the `files` array, it should already include the bin folder when we publish. If this is not happening, something strange is going on...

**Comment by RanzQ** [comment]
There should be an empty `.npmignore` file, otherwise it uses the `.gitignore`, see here: https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

I guess that `.gitignore` overrides whatever you have in `files`.

**Comment by englercj** [comment]
> I guess that .gitignore overrides whatever you have in files.

Well that is super dumb, I was under the impression if we had a `files` array specified in package.json that was the entire whitelist and nothing else was considered...

I'll touch an .npmignore file so we can fix this.

**Comment by englercj** [comment]
Try it now, just released v4.1.1 that has a blank npmignore.

**Comment by RanzQ** [comment]
@englercj Now the `bin/` is included. :)
