### ISSUE TITLE
Problem with getCanvas and texture

### ISSUE THREAD

**Issue by ThomasAtome** [pixijs/pixi.js#3186]
Hi,

I'm trying to update a project in pixi v3 to pixi v4, but i got an issue that i can't resolve.

In v3, I just create a texture and retrieve the canvas with the method getCanvas().

But in v4, the getCanvas() return me a "Cannot read property 'extract' of null".

Is there a new method in v4 for retrieve canvas from texture ?

Thanks

**Comment by Pandan** [comment]
I am guessing it might be connected to this problem.
https://github.com/pixijs/pixi.js/issues/3183

**Comment by themoonrat** [comment]
RenderTexture.getCanvas is now deprecated, please use renderer.extract.canvas(target)

**Comment by themoonrat** [comment]
PS. I would advise developing on the non minified build. That way, use of any deprecated API calls, like the one above, would flag up in the browser console. The non minified version of PIXI is treated as a 'debug version' and may have more verbose errors in the console, whilst the minified version of PIXI is treated at the 'release' version and thus shows no such warnings.

**Comment by ThomasAtome** [comment]
@themoonrat Thanks you ! 👍  Can close it ;)
