### ISSUE TITLE
[Help] Making things interactive

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#3190]
As far as I understand, it used to be `new Stage(colour, true)` to have an interactive stage and then the `interactive` property of any children set to true.

What does one do to have an interactive container now? There's no property called `interactive` anymore.

When I tried using events on sprites, they never fired.

Guidance would be appreciated. Thanks!

**Comment by staff0rd** [comment]
All `DisplayObject`s have [these properties](https://github.com/pixijs/pixi.js/blob/22c5248a51059979278b7cefc11e3a7e7078c008/src/interaction/interactiveTarget.js#L17-L55) attached to them, so you can go ahead and set `interactive` to true for any you'd like to be interactive.

**Comment by ddennis** [comment]
Hi - I was trying to fix this my self. You need to use the use `new PIXI.Container() ` the Container inherits from DisplayObject which has 
```
interactive = false;
interactiveChildren = false;
```
[I have done a example:](https://jsfiddle.net/647x6ruo/) but it seems that even with the `interactiveChildren = true` - you still have to set **interactive** flag for each child, which seems to make the interactiveChildren redundant.

**Comment by staff0rd** [comment]
@ddennis the purpose of `interactiveChildren` is for setting it to false to [stop recursive searches of the scene graph](https://github.com/pixijs/pixi.js/blob/d2def3dc931cc414d28d66656615997425c92d30/src/interaction/InteractionManager.js#L801).

**Comment by ddennis** [comment]
@staff0rd Thanks - they just seemed to fit so nicely together.

**Comment by DubiousDillan** [comment]
Thank you to everyone who responded. I've managed to get it to work now and @staff0rd, your example was really helpful.

**Comment by staff0rd** [comment]
@DubiousDillan I think you mean @ddennis's example.  Glad you got it fixed :)

**Comment by DubiousDillan** [comment]
@staff0rd, you're right! Edited to tag him correctly. Ty!
