### ISSUE TITLE
Input not registering using IE11

### ISSUE THREAD

**Issue by Daggersoath** [pixijs/pixi.js#3199]
So I have a little project set up which utilizes the built in "click" functionality, It works fine on firefox, chrome, opera, android browser, android chrome, android firefox and IE10, but when trying to use it in IE11 it stops regestering clicks and I cant figure out why.

There are no errors being reportedand, the only console output is "Pixi.js 4.1.0 - WebGL - http://www.pixijs.com/"

**Comment by themoonrat** [comment]
You may have to use the pointer events for ie11

**Comment by Daggersoath** [comment]
I have tried adding "pointer-events: all;" to my CSS but no change. I have not previously worked with pointer-events so I may be doing something wrong

**Comment by themoonrat** [comment]
Ah, i meant listen to, say, pointertap instead of click or tap. There is a pointer api that ie11 uses that normalises where the interaction comes from. Check it what events are available from http://pixijs.download/v4.1.0/docs/PIXI.interaction.InteractionManager.html

**Comment by Daggersoath** [comment]
That fixed the issue, thanks :)

**Comment by englercj** [comment]
Ignore the commits above, they are unrelated to this issue. I just mistyped the issue number :P
