### ISSUE TITLE
bug of '1 pixel' difference

### ISSUE THREAD

**Issue by opty2001** [pixijs/pixi.js#3205]
![k-002](https://cloud.githubusercontent.com/assets/5646805/19724867/9140e37c-9bbd-11e6-91ed-cd9d61b2a2f5.png)
I'm making assembly UI control.
![k-003](https://cloud.githubusercontent.com/assets/5646805/19725128/d0f3595e-9bbe-11e6-8109-353089647456.png)
But mouse hittest wasn't perfectly worked, because of 'containsPoint' function.
![k-005](https://cloud.githubusercontent.com/assets/5646805/19725506/bfc72bae-9bc0-11e6-8d82-7473c96b6c17.png)
If i moving mouse left and right, 'mouseover' and 'mouseout' event repeated in same container by the '1 pixel'.
![k-004](https://cloud.githubusercontent.com/assets/5646805/19725475/97324da4-9bc0-11e6-9e40-044dbc336818.png)
So i fixed the bugs. Solution is change
`if (tempPoint.x > x1 && tempPoint.x < x1 + width) {`
to
`if (tempPoint.x >= x1 && tempPoint.x < x1 + width) {`
of each class(sprite, tilingsprite)'s 'containsPoint' function.

**Comment by ivanpopelyshev** [comment]
Nice! Make a PR, I'll vote for it.
