### ISSUE TITLE
addChild only adding first child, and multiple containers using same child weird behaviour

### ISSUE THREAD

**Issue by schmooblidon** [pixijs/pixi.js#3209]
Bit of context, I'm making a fighting game and I have split up each scene as it's own PIXI.Container. I want multiple scenes to share some of the same children.

Here is the how I want to structure this and a line to comment in/out to see the problem
http://codepen.io/anon/pen/rrgWNK

So then I thought I'd create a createScene function to add each child one by one, but then things just get weird.
http://codepen.io/anon/pen/JRqbXg

Am I doing something wrong?

**Comment by ivanpopelyshev** [comment]
I dont understand your code. Adding same thing to two ore more containers wont work, it violates one of things that pixi is built upon. 

I did something like that in https://gameofbombs.github.io/pixi-bin/index.html?s=camera&f=mirror.js&title=2%20bunnies%202%20cameras , it uses my own fork of pixi. It requires proxy objects: https://github.com/gameofbombs/pixi.js/tree/master/src/core/display .

**Comment by schmooblidon** [comment]
This is cool but it's not what I want. I want to use them the 2 instances of the Graphics object in quite different ways. I'm still new to pixi, and given that the Graphics object is an object, I just assumed I was feeding the container a pointer for something to draw and thus wouldn't hold any exclusivity to it.

**Comment by staff0rd** [comment]
@schmooblidon each `DisplayObject` can have one parent only.  [Check the source](https://github.com/pixijs/pixi.js/blob/27fbb78670be41ed8d1aa3f9610bba142af65392/src/core/display/Container.js#L60-L63) and you'll see that the first thing `addChild` does is remove the child from its existing parent, should one exist.

**Comment by englercj** [comment]
Pixi's scene is a tree. A tree is an "undirected graph, which is connected, and without circle". Having multiple parents would introduce a circle, and would therefore not be a tree anymore.

Each object can only have 1 parent, containers may have N children.
