### ISSUE TITLE
Rendering texture on webgl generates black background on some devices

### ISSUE THREAD

**Issue by FFankias** [pixijs/pixi.js#3211]
We faced a problem in pixi v4: 
  rendering texture from the graphics on Samsung Galaxy Tab 3 generates texture with black background. 

Black background is because of black background of renderer. Setting property transaparent: true when creating new renderer fixes the issue.

**Comment by staff0rd** [comment]
Hi @FFankias, are you able to supply a [fiddle](https://jsfiddle.net) or [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by kaansoral** [comment]
This black background issues haunt me too, looking at my settings now, I have transparent:false

1) Sometimes everything flashes black - #3373 is related
2) A player reported the game was always black, a while ago, just dropped this bomb and left the game without helping
3) OSX/Firefox was all white for me, I switched to Canvas for OSX/Firefox

(1) + (2) + (3) + OP Might all likely be unrelated

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
