### ISSUE TITLE
How to custom the  Shaders of Sprite ? 

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3212]
I know I could add a Filter to a sprite , but in Filter , the Filter just can do something  after Spriter rendered ,    I know "after Spriter rendered"  is inaccurate    , I mean the aVertexPosition aTextureCoord uSampler are not original of Sprite .
e.g.  the aVertexPosition has bean cut by viewport and  be transformed by sprite.worldTransform.

I want to do something when Spriter be rendered.

So How to custom the  Shaders of Sprite ? 

I found the attribute named shaders in SpriteRenderer,  but it could be changed to the default in 
`SpriteRenderer.prototype.onContextChange` :

```
        this.shaders = new Array(this.MAX_TEXTURES);
        this.shaders[0] = generateMultiTextureShader(gl, 1);
        this.shaders[1] = generateMultiTextureShader(gl, 2);
```

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital is working on it. For now you can use https://github.com/pixijs/pixi-plugin-example and its upgraded version https://github.com/pixijs/pixi-picture for the reference. Make your own Shader, Renderer and extend Sprite object.

**Comment by finscn** [comment]
Hi ， @GoodBoyDigital ， @ivanpopelyshev said you are working on it.  Is there any news? 
Thanks.

**Comment by ivanpopelyshev** [comment]
btw, I'm working on my own implementation to combine sprites and filters approach, it will be different but Its mergable with what @GoodBoyDigital is doing.

**Comment by ivanpopelyshev** [comment]
@finscn Also I updated pixi-plugin-example, it can help you a bit, i think.

**Comment by GoodBoyDigital** [comment]
v5 will let you go way more custom. Should give you the power to do things how you want 👍
