### ISSUE TITLE
renderer.textureGC.unload on generated textures stops them rendering again

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#3215]
My interpretation of the renderer.textureGC.unload function is that in WebGL mode only, it will remove that texture from the graphics card memory; but if it's needed again, it'll be available, but just have to be re-uploaded.

However, I'm finding that with textures created via renderer.generateTexture - once unload has been called on them, they are never able to be drawn again

Here's a fiddle to show what I mean: https://jsfiddle.net/themoonrat/whaq3y2z/
Click on either image to have unload called. The sprite with a texture loaded from an images remains, however the sprite with a texture generated by the renderer disappears never to be seen again :(

**Comment by GoodBoyDigital** [comment]
hello! GC only works with textures that have original srcs as we can easily re-upload them. Anything that uses a render texture only exists on the GPU - so if we remove it its gone forever.

**Comment by themoonrat** [comment]
So the fix for this would be to not call destroyTexture on RenderTextures?
