### ISSUE TITLE
[Suggestion] add a method for generate Shader  in SpriteRenderer.js

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3216]
This suggestion is about Flexibility and Extensibility .
Now, in SpriteRenderer , call generateMultiTextureShader to generate Shader , it's hard to extend.
I can use custom shader  via override the method .
if  in SpriteRenderer.js there is a method like this : 

```
    generateShader(gl, maxTextures){
        return generateMultiTextureShader(gl, maxTextures);
    }
```

use case: 

```
                shader = this.shaders[groupTextureCount - 1] = this.generateShader(gl, groupTextureCount);
```

Then , I could override it by myself for some use cases, like this : 

```
var myRender = new SpriteRenderer(renderer);
myRender.generateShader = function(gl, maxTextures){
 // for my shader
}
```

**Comment by weepy** [comment]
I want to write a custom shader (a gradient tint - see #2216), but I can't find any examples of how to do it (other than PIXI Picture plugin which I'm finding difficult to understand).

**Comment by ivanpopelyshev** [comment]
@weepy you mean that https://github.com/pixijs/pixi-plugin-example is difficult? Btw, its outdated a bit

**Comment by weepy** [comment]
@ivanpopelyshev I meant that https://github.com/pixijs/pixi-picture is difficult. I gather that's the main way to do it ? 

I did try writing as a filter, but it was too slow on iOS

http://codepen.io/anon/pen/VPMjJL

@GoodBoyDigital mentioned in #2216 that "new implementation of Sprite makes this much easier to do" ... I'm not quite sure what this means.

**Comment by ivanpopelyshev** [comment]
pixi-picture is difficult because its actually takes what under image and then uses it for blend.

pixi-plugin-example is basic thing with basic shader. Except, its outdated a bit. I can update if for you :)

**Comment by weepy** [comment]
great - I'd love that. Will it be faster than my example (i.e. using sprite.filters = [ gradient tint ]   ?

**Comment by ivanpopelyshev** [comment]
yes, definitely

**Comment by weepy** [comment]
thanks so much. I look forward to the update.

**Comment by ivanpopelyshev** [comment]
@weepy updated. Gonna add ES6 and TS examples later. 

Also gonna make better filters, it'll be much easier to add stuff with them.

**Comment by weepy** [comment]
Amazing. Will check.

**Comment by weepy** [comment]
Hey thanks @ivanpopelyshev 

I've just been building the code and taking a look. Wither regards to writing a GradientTint plugin, I'm a bit unsure as to which parts are to do with the Plugin and which are part of the PictureRenderer  ?
Can you clarify ?

**Comment by GoodBoyDigital** [comment]
v5 will let you build your own geometries and shaders, so should give you the power to do as you please :)
