### ISSUE TITLE
MovieClip strange offset of frames on iOS

### ISSUE THREAD

**Issue by HejdukV** [pixijs/pixi.js#3218]
I use TexturePacker to create SpriteSheet for MovieClip animation. There is strange behaviour on Pixi v4 (tested on 4.1.0 and 4.0.3) on iOS with my MovieClips. Frames are changing x and y axis position (maybe bad calculation of source frames position?). Everything works fine with Pixi v3.

Screen capture from iPhone: https://dev.hejduk.org/screen_capture.mov
Test page: https://dev.hejduk.org/anim_test.php

Example works fine on PC (Firefox, IE, Chrome, Edge), Mac (Firefox, Safari), Andorid. MovieClip is corrupted only on iOS (iPhone and iPad).

**Comment by siwel** [comment]
I have been able to reproduce this in our project; 

 * I have when using a base texture that is power of two with MipMaping enabled, this does not occur
 * Seems to occur across all iOS Devices - iOS 9 & 10

**Comment by siwel** [comment]
Setting `_PIXI.PRECISION.DEFAULT = PIXI.PRECISION.HIGH_` seems to fix this.

**Comment by HejdukV** [comment]
I confirm that this setting helped. Thanks

**Comment by themoonrat** [comment]
@GoodBoyDigital I believe this setting has been back and forth - was changed to high, but some devices did not support it and caused issues, so was changed back down. Do you think there could be some device / capability detection involved for the default setting on this?

**Comment by englercj** [comment]
We now default to highp in the vertex shader which should fix this issue.
