### ISSUE TITLE
rendering Freezing or lack when Image data move to graphic memory

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#3220]
our game is loading images by async 
like map's objects  or etc..
out game  load minimum image at starting time
and if image(like objects or NPCs) need load,  it load at playing game and used.

but this timing has a little bit problem..
if to service(publish) game, it will be big problem.

its problem is to update  graphic memory(video memory or graphic card memory)
there is  lack(or freezing) to update graphic memory.

i can't find any way to resolve this T-T

normally this case not happen,  because many user load all of images  at  starting time
but out game can't if do , usage memory is too big and loading time is too long..

can you help about this?

i don't have many knowledg about rendering or webgl. do i don't have any solution at this time
but this problem give me stress.. T-T

can you tell me any solution to resolve this?

**Comment by staff0rd** [comment]
Hi @SeminYun, it will be easier for the community to address this if you're able to supply a minimum working example - are you able to supply a [fiddle](https://jsfiddle.net) or [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by themoonrat** [comment]
Hi @SeminYun - wondering if this is still an issue or not? If so, then please provide an example as staff0rd requested. If not, we can close this down :)

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
