### ISSUE TITLE
Is changing a Renderer's view dynamically possible?

### ISSUE THREAD

**Issue by ShayDavidson** [pixijs/pixi.js#3222]
(Pixi v4.x)

I'm trying to dynamically replace a `renderer`'s `view` property by assigning a new `canvas` element to it.

```
renderer.view = <canvas element already on DOM>
```

but the result is just a blank canvas which doesn't work.
Is this even possible?

**Comment by ivanpopelyshev** [comment]
No :) Somebody has to update contexts.

**Comment by englercj** [comment]
Unfortunately not, because we would need a new drawing context and to reinitialize all our GL variables. It is easiest to think of the renderer as having a one-to-one mapping to a canvas. For a new canvas, you need a new renderer.
