### ISSUE TITLE
last release of chrome 54 mobile make carema stuck if pixi is running

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#3226]
we have already opened a bug in https://bugs.chromium.org/p/chromium/issues/detail?id=660738
But we don't know if this is caused by a chrome bug or pixi one, so I replicate the bug there.

Steps to reproduce the problem:
Given a Samsung S6, S7, or Nexus, with Android 6.0.1 or later, with Chrome 54 or later:
1) Empty Chrome cache
2) Close Chrome
3) Click on a link below.
4) Move from portrait to landscape many times, or refresh, or wait some time

Links:
1) https://jsfiddle.net/hs86tLdc/28/
2) https://jsfiddle.net/hs86tLdc/29/
3) https://jsfiddle.net/hs86tLdc/30/

What is the expected behavior?
Div video element is expected to show front-camera frames

What went wrong?
The video stream often freezes, remaining stuck on a random camera frame

Did this work before? Yes 52

Chrome version: 56.0.2900.3  Channel: dev
OS Version: 6.0.1
Flash Version: 

Bug is *not* present on:
-on Chrome 52: Samsung S6, S7
-on Chrome 54: Htc one M8, Samsung S4, Samsung J5, Ngm infinity, One plus X
-on Firefox ( https://jsfiddle.net/hs86tLdc/26/ )

Bug is present on:
-on Chrome 54, 55 (last beta), 56 (last dev): Samsung S6, S7, Nexus 9

More information coming soon..

**Comment by themoonrat** [comment]
Hi @JenGL - do you have an update on this please? Did recent chrome versions fix this?

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
