### ISSUE TITLE
A sample about PerspectiveRenderer

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3227]
I've tried to implement a custom Renderer about perspective transform. 

There is the sample : 
http://fattyboy.cn/pt/ 

I'm a beginner of PIXI.js & WebGL , so there are many mistakes and bad smells in my code.
So it maybe(or must be)  not a useful extension .
I just hope this sample could express my request to the authors of PIXI.js.  ( in https://github.com/pixijs/pixi.js/issues/3136 )

References : 
https://github.com/gohai/processing-glvideo/blob/master/src/gohai/glvideo/PerspectiveTransform.java

 http://jsfiddle.net/rjw57/A6Pgy/

**Comment by ivanpopelyshev** [comment]
OK, no worries, I'll just make a repo, take your files and make you a contributor. Just not now, I'm busy :)

**Comment by finscn** [comment]
the files of this feature : 

https://github.com/finscn/pixi.js/blob/master/src/extension/PerspectiveRenderer.js
https://github.com/finscn/pixi.js/blob/master/src/extension/Matrix3.js
