### ISSUE TITLE
How to pass alpha to shader in PIXI.js ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3228]
I have a little question about  Alpha in shader:

I found there two ways in PIXI.js: 

first : 
pass  ```uniform float uAlpha``` , then use ```gl_FragColor = texture2D(uSampler, vTextureCoord) * vAlpha```  in Fragment.

second:
compute color in JS via  hex2rgb
pass  ```attribute vec4 aColor```, then use ```gl_FragColor = texture2D(uSampler, vTextureCoord) * vColor;```  in Fragment.

Which one is correct or better ? 
(The first one looks easy & fast )

**Comment by englercj** [comment]
Depends on what you want to do. If you want it to work across multiple objects in a batch, that have different alpha/color values then you need to pass it in the vertex array (as an attribute). This is why we upload it as an attribute in the vertex array for sprite's shader.

If it is only for one thing, and you only want to pass one number; the first is fine (and is easier to write).

**Comment by finscn** [comment]
Thanks very much .

**Comment by ivanpopelyshev** [comment]
```glsl
gl_FragColor = texture2D(uSampler, vTextureCoord) * vColor;
```

make sure vColor is pre-multiplied alpha (r*a, g*a, b*a, a). Textures in pixi are all pre-multiplied

**Comment by finscn** [comment]
@ivanpopelyshev  , sorry,  I can't understand your words ... tears ...
Could you explain it in more details , please . 
Or give me some key words for googling .
Thanks.

**Comment by ivanpopelyshev** [comment]
@finscn If your alpha is 0.5, all components in vColor should be multiplied by 0.5 too. Either do it in shader, either in js
