### ISSUE TITLE
Canvas stroke cropped when generateTexture with noWebGL

### ISSUE THREAD

**Issue by ThomasAtome** [pixijs/pixi.js#3232]
Hi, 

I catch something strange in 4.1 that doesn't append in v3.

v3 fiddle : 

https://jsfiddle.net/465e3wjs/

v4 fiddle :

https://jsfiddle.net/kqfx1o9p/

If the sprite is on negative position on the container in v4 the texture generated is cropped, that doesn't append in v3.

Is this a bug ?

Thanks

**Comment by englercj** [comment]
Thanks for the report!
