### ISSUE TITLE
webgl  Rendering efficiency lower than canvas

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#3236]
hello:
   When i set rendering method is webGl,the Rendering efficiency is low,if set rendering method is canvas the Rendering efficiency higher than webGl,How to improve efficiency of webgl?
  Thank!

**Comment by finscn** [comment]
Your question is so big and abstract.
And there may be some mistakes in your code ,  I think .
So , show me your code , please.

P.S.: Are you come from China ,  Mr. 冯方勇 ?

**Comment by englercj** [comment]
Usually if this is true, you are either:

1. Using extremely large textures, or
2. Using software rendering for WebGL which is super slow.

You can check for the later by looking at chrome://gpu/

**Comment by fengFanYong** [comment]
@finscn 
HI
code:
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>js test</title>
    <style>
        body {margin: 0;padding: 0;background-color: #000000;}
    </style>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.0.0/pixi.min.js"></script>

</head>

<body>
<script>
    var stage = new PIXI.Container();
    var render = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, {antialias: true},false);
    document.body.appendChild(render.view);

        bt = new PIXI.Sprite();
        bt.anchor.set(0.5);
        bt.x =150;
        bt.y = 200;
        bt.width = 140;
        bt.height = 344;


        for(var i=0;i<2;i++){
            gt = new PIXI.Graphics();
            bt.addChild(gt);
            gt.beginFill(0x123123,1);
            gt.drawRoundedRect(1*i,0,1,1,.05);
            gt.endFill();
            bt.addChild(gt);
        }
    stage.addChild(bt);
    requestAnimationFrame(update);
    var startTime = Date.now();
    var count = 0;
    function update(){
        if(count == 100){
            count = 0;
            var now = Date.now();
            console.log("____ render interval: %d ms:"+(now-startTime));
            startTime = Date.now();
        }

        requestAnimationFrame(update);
        render.render(stage);
        count ++;

    }

</script>
</body>
</html>

Fourth parameters of autoDetectRenderer is false Rendering with webgl,is true rendering with canvas,Webgl render time longer,if the number of graphics or sprite is increase,the Render time longer.
Yes,i am from china ,Thank!

**Comment by englercj** [comment]
Are you using software rendering for WebGL?

**Comment by fengFanYong** [comment]
@englercj 
Wow should i do?How to rendering for webGl

**Comment by englercj** [comment]
You can check if you are using software rendering by looking at chrome://gpu/
