### ISSUE TITLE
[REQUEST]Could you supply a option to exclude the feature for Canvas2D ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3237]
I want to exclude Canvas2D for building a small bin file , Because my game only supports WebGL.

Thanks.

**Comment by englercj** [comment]
We plan to make this easy in v5.

**Comment by finscn** [comment]
@englercj  I found there are many good features in v5 , when & where  could I get the  early access version of v5 ?

**Comment by ivanpopelyshev** [comment]
@finscn in our dreams ;)

**Comment by englercj** [comment]
I haven't even started yet :) waiting for a couple refactoring changes from @GoodBoyDigital to hit v4, then I'll be off to the races for v5!

**Comment by GoodBoyDigital** [comment]
v5 will have this one covered :)
