### ISSUE TITLE
Multiple textures, one canvas?

### ISSUE THREAD

**Issue by schmooblidon** [pixijs/pixi.js#3238]
I want to make lots of textures using canvas. It makes sense to me to use one canvas, and clear the canvas before making the next texture. It seems that all the sprites use whatever the canvas state is in the first time one of them is rendered.

Is the solution to just make new offscreen canvases for each texture? I worry that it's not optimized, and I have a bit of a history of very unoptimized rendering which I'm trying to rectify now. It's hard to know the right way to do something, as documentation is quite limited.

**Comment by englercj** [comment]
You can draw each of the textures to the same canvas, without clearing in between. Basically draw a "spritesheet" to the canvas and then make textures with the proper frames for all the textures you drew.

**Comment by schmooblidon** [comment]
Ah that makes sense! Thank you for your quick response :)

**Comment by englercj** [comment]
Anytime, good luck!
