### ISSUE TITLE
Using a MovieClip generated from a json/sprites does not work as a mask. 

### ISSUE THREAD

**Issue by kadir-uix** [pixijs/pixi.js#3240]
The last few days I tried to solve this problem without any success. I wonder whether it's my fault or it is simply not possible. 

The case is as follows: 
I have an animated sprite (movie) that is generated and converted into the extras.MovieClip. Now I want to mask this MovieClip to an Image (backgroundImage). But the animation is not working after masking.

---

I don't have this problem using a video such as in this example: 
http://pixijs.github.io/examples/#/basics/video.js
The video masks and it works. 

---

I am sorry but I can not get a good way to host the json so that it works on jsfiddle. 

Here are the assets 
https://dl.dropbox.com/s/dyu1g0zbatz3mqa/backgroundImage.jpg
https://dl.dropbox.com/s/k9y7rve067uoqi9/ink.json
https://dl.dropbox.com/s/njg0s5vujexnqpk/ink.png

```
var width = window.innerWidth; // gets the window size x
var height = window.innerHeight; // gets the window size y
var renderer = new PIXI.autoDetectRenderer(width, height); // creates the container
document.body.appendChild(renderer.view); //adds the dom element

// create the root of the scene graph
var stage = new PIXI.Container(); //Sets up a stage
var container = new PIXI.Container(); //Sets up a container
var ink, movie;


PIXI.loader
    .add('img/ink.json')
    .add('img/ink.png')
    .add('img/backgroundImage.jpg')
    .load(onAssetsLoaded);

/* Frames to Movie */
function onAssetsLoaded() {
    var frames = [];

    for (var i = 0; i < 14; i++) {
        var val = i < 10 ? '0' + i : i;

        frames.push(PIXI.Texture.fromFrame('ink_0' + val + '.png'));
    }

    // Frames from json to PIXI.movie
    movie = new PIXI.extras.MovieClip(frames);

    movie.position.set(0);
    movie.x = width / 2;
    movie.y = height / 2;
    movie.anchor.set(0.5);
    movie.animationSpeed = 0.5;
    movie.play();

    // Background Image
    var backgroundImage = PIXI.Sprite.fromImage("img/backgroundImage.jpg");
    backgroundImage.x = width / 2;
    backgroundImage.y = height / 2;
    backgroundImage.anchor.set(0.5);

    // Add items 
    stage.addChild(container);
    container.addChild(backgroundImage);
    container.addChild(movie);

    // mask backgroundImage
    backgroundImage.mask = movie;
  
}

animate();

function animate() {
    requestAnimationFrame(animate);
    renderer.render(stage);
}

```

---

Thanks

**Comment by kadir-uix** [comment]
Is there an alternate or even better way to achieve what I am looking for within pixi (masking an image using a sprite)?

**Comment by GoodBoyDigital** [comment]
Sprite masks do not work with sprite sheets. The best way to solve this is to use a whole image.

Cheers!

Mat
