### ISSUE TITLE
My 2nd custom Filter : BloomFilter  & There is a problem :(

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3243]
I create a  bloom filter . 
Demo :  
    http://fattyboy.cn/pt/?t=123

Code : 
    https://github.com/finscn/pixi.js/blob/master/src/extension/BloomFilter.js
    https://github.com/finscn/pixi.js/blob/master/src/extension/BrightnessFilter.js

References : 
    http://learnopengl.com/#!Advanced-Lighting/Bloom

It looks correct.

But when I add the filter to  a sprite with PerspectiveRenderer ( more detail at  https://github.com/pixijs/pixi.js/issues/3227 ) , the sprite can't display and no any error in console.

Would you like to suggest some possible reasons why this is ?
Thanks.

cc @ivanpopelyshev  @englercj

**Comment by englercj** [comment]
User the WebGL inspector and check what your buffers look like. I don't have time atm to debug a custom renderer :(

**Comment by finscn** [comment]
I found the reason :  it's   PerspectiveRenderer's fault.
BloomFilter is OK.
I hope PIXI.js could include a filter like  bloom, you could write a better one, I think.

Thanks

**Comment by bigtimebuddy** [comment]
@finscn check out https://github.com/pixijs/pixi-filters there's a Bloom filter there.

**Comment by finscn** [comment]
I've transport the  BloomFilter in https://github.com/pixijs/pixi-filters  to PIXI v4.
I found it's algorithm is different from  http://learnopengl.com/#!Advanced-Lighting/Bloom 
And it can't custom light of bloom .
