### ISSUE TITLE
pointerdown and pointer~~~ doesn't work on chrome 56.0.~~~~

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#3247]
this is not resolved..

chrome 56.0.2896. 64-bit is not working with recent version that update on master 2 days ago

#3167

**Comment by kaansoral** [comment]
https://github.com/pixijs/pixi.js/pull/2997#issuecomment-257703830

**Comment by themoonrat** [comment]
Correct. The latest dev version (found at http://pixijs.download/dev/pixi.js ) should work

**Comment by themoonrat** [comment]
@bigtimebuddy - this can be closed - fixed by https://github.com/pixijs/pixi.js/pull/3233
