### ISSUE TITLE
Is there a function like context.drawImage(...) of Canvas2D in Pixi.js

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3251]
use case like this  :
```
renderer.drawTexture(texture,  sx, sy, sw, sh, dx, dy, dw, dh);
```

Thanks.

================
I know I could create a Sprite with the parameters  ```texture,  sx, sy, sw, sh``` , and change the position and scaleX  scaleY .  but  in this request , ```texture,  sx, sy, sw, sh, dx, dy, dw, dh```  are often changed in per frame.

**Comment by ivanpopelyshev** [comment]
No, there's not, But there also no overhead for sprites and textures;

You dont have to re-create the texture every time, just change its frame

```js
texture._frame.x += 10;
texture._frame.y += 10;
```

But that's for ONE instance of sprite. If you have multiple instances and their "sx,sy,sw,sh" are different, you will need more Textures.

You can make your own "RectSprite" own canvas and webgl renderers like in https://github.com/pixijs/pixi-plugin-example

**Comment by finscn** [comment]
@ivanpopelyshev ,   What's different between https://github.com/pixijs/pixi-plugin-example  &   https://github.com/pixijs/pixi-picture ? I found they are both about  PictureXXXXX .

**Comment by ivanpopelyshev** [comment]
@finscn first is a boilerplate for a plugin, second is real plugin that takes care of certain blendmodes in webgl.

**Comment by finscn** [comment]
the dw & dh are used : 
```
texture._frame.width = dw;
texture._frame.height = dh;
```
or 
use scale of sprite ?
