### ISSUE TITLE
SepiaFilter deleted in v4

### ISSUE THREAD

**Issue by louisatome** [pixijs/pixi.js#3252]
The former SepiaFilter available in pixi v3 seems to have been deleted. Is there another filter we can use in v4 to achieve the same result?

**Comment by bigtimebuddy** [comment]
Sepia is available here: https://github.com/pixijs/pixi-filters

The filters were externalized in v4.

**Comment by louisatome** [comment]
OK thanks, I didn't notice.

**Comment by louisatome** [comment]
Actually it seems that the SepiaFilter isn't in the pixi-filters repo either or maybe it has been renamed?

**Comment by giraluna** [comment]
The built in color matrix filter has a method for this
http://pixijs.github.io/docs/PIXI.filters.ColorMatrixFilter.html#sepia

Usage:
```
 var colorMatrix = new PIXI.filters.ColorMatrixFilter();
 container.filters = [colorMatrix];
 colorMatrix.sepia();
```

**Comment by louisatome** [comment]
That's right but with ColorMatrixFilter i can't set a percent value for my sepia effect as i used to do with the SepiaFilter.

**Comment by englercj** [comment]
Hey @louisatome, I hope https://github.com/pixijs/pixi.js/pull/3944 solves your issue. It will allow you to do an interpolation value for the color matrix which would be the same effect as the "scale" of the previous SepiaFilter.

Thanks for being patient while we caught up to you! :)
