### ISSUE TITLE
Displacement Filter issue with Pixi.js V 4.0

### ISSUE THREAD

**Issue by michaelgrc** [pixijs/pixi.js#3253]
I'd like to have the same result than this jsfiddle. It use pixi.js - v1.6.0

http://jsfiddle.net/glafarge/6h84bpnk/

Unfortunately, I don't succeed having the same result with de new pixi.js v4.1.0 It seems that this line inside the requestAnimationFrame function doesn't work on the new pixi.js

`displacementFilter.offset.x += offset;`
Indeed, offset doesn't exist anymore but I don't know how to replace it ? Does anyone have an idea ?

Thanks

**Comment by ivanpopelyshev** [comment]
all offsets are made with displacementSprite. Please look at the examples.

**Comment by michaelgrc** [comment]
Thank you very much for your answer and advices. 
I think I'm close to the solution. There's only one problem left compare to the jsfiddle I shared with you : It seems like the filter does not repeat itself and it doesn't take the full image, there's only one wave (even when I set the displacementSprite.scale x & y to 1).

You can see the result here : http://michaelg.fr/lab_webgl/displacementfilter/
And here's my code : 

        var renderer = PIXI.autoDetectRenderer(716, 180, {transparent:true});
        document.body.appendChild(renderer.view);

        var stage = new PIXI.Container();

        var texture = PIXI.Texture.fromImage('22.png');
        var logo = new PIXI.Sprite(texture);

        var displacementSprite = PIXI.Sprite.fromImage("http://i.imgur.com/2yYayZk.png");
        var displacementFilter = new PIXI.filters.DisplacementFilter(displacementSprite);

        displacementSprite.scale.y = 0.1;
        displacementSprite.scale.x = 0.1;

        stage.addChild(displacementSprite);
        stage.addChild(logo);

        animate();

        function animate() {
            requestAnimationFrame(animate);
            
            displacementSprite.x += 1;
            displacementSprite.y += 1;

            stage.filters = [displacementFilter];
            renderer.render(stage);
        }

I understand the incrementation of my x & y inside my requestAnimationFrame function but on the jsfiddle (with Pixi v.1.6) the filter stays in the canvas with the same incrementation. 
Are you able to see what I'm missing ?

Thank you very much in advance

**Comment by ivanpopelyshev** [comment]
Look in #2867 . In v4 texture must be set to repeat.

**Comment by michaelgrc** [comment]
Many thanks for the new answer.
I added this line to my code : texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
but unfortunately nothing seems to change.

Here's my code : 

        var renderer = PIXI.autoDetectRenderer(716, 180, {transparent:true});
        document.body.appendChild(renderer.view);

        var stage = new PIXI.Container();

        var texture = PIXI.Texture.fromImage('22.png');
        
        texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
        
        var logo = new PIXI.Sprite(texture);
    
        var displacementSprite = PIXI.Sprite.fromImage("http://i.imgur.com/2yYayZk.png");

        var displacementFilter = new PIXI.filters.DisplacementFilter(displacementSprite);

        displacementSprite.scale.y = 0.1;
        displacementSprite.scale.x = 0.1;

        stage.addChild(displacementSprite);

        stage.addChild(logo);

        animate();

        function animate() {
            requestAnimationFrame(animate);
            
            displacementSprite.x += 1;
            displacementSprite.y += 1;

            stage.filters = [displacementFilter];
            renderer.render(stage);
        }

It should work because when I inspect my page, texture.baseTexture.wrapMode returns 1 on my console. Sorry to bother you again but I really want to understand. Here's the result I get : http://michaelg.fr/lab_webgl/displacementfilter/

Thank you very much once again for your time

**Comment by ivanpopelyshev** [comment]
You have two textures there, one of them is displacement that must be repeated. You guess at which one was wrong ;)

**Comment by michaelgrc** [comment]
I think I got it. 
Now it's working. 
I was applying the repeat mode to the wrong element. 
So I added a new texture with the same url than in my displacementSprite declaration.

I'm not sure this is the good way to do it ? Because I can't find a link between my new texture and the displacementSprite object.

Here's my code : 
    
        var renderer = PIXI.autoDetectRenderer(716, 180, {transparent:true});
        document.body.appendChild(renderer.view);

        var stage = new PIXI.Container();

        var texture = PIXI.Texture.fromImage('22.png');
        var logo = new PIXI.Sprite(texture);
    
        var displacementSprite = PIXI.Sprite.fromImage("http://i.imgur.com/2yYayZk.png");
        
        // add
        var texture2 = PIXI.Texture.fromImage("http://i.imgur.com/2yYayZk.png");
        texture2.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;

        var displacementFilter = new PIXI.filters.DisplacementFilter(displacementSprite);

        displacementSprite.scale.y = 0.1;
        displacementSprite.scale.x = 0.1;

        stage.addChild(displacementSprite);

        stage.addChild(logo);

        animate();

        function animate() {
            requestAnimationFrame(animate);
            
            displacementSprite.x += 1;
            displacementSprite.y += 1;

            stage.filters = [displacementFilter];
            renderer.render(stage);
        }

Sounds a bit messy to you ?
Thank you for your explanations and enigmas ;)

**Comment by ivanpopelyshev** [comment]
Nah, I have a lot of code like that. It works because of caching, but some people want to deprecate it so beware!

Also, the texture is here:
```js
displacementSprite.texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
```

**Comment by michaelgrc** [comment]
Perfect I'll do it on your way !
Thank you that was very helpful and interesting.

**Comment by justrealmilk** [comment]
For anyone else who comes looking for a post like this that's interested in seeing the final result, I've made a CodePen.

https://codepen.io/justrealmilk/pen/MVYYeQ?editors=0010

Been looking for an easy and effective way to do this for ages

**Comment by ivanpopelyshev** [comment]
@justrealmilk  I think this rejected PR can be interesting for you: https://github.com/pixijs/pixi.js/pull/4686 . I'm going to move the code to the plugin.

**Comment by justrealmilk** [comment]
@ivanpopelyshev If I'm honest, I only loosely grasp the relevance - I used Pixi for the first time in making that CodePen! That said, I think it's about making things like https://i.imgur.com/kMMUb33.gifv easier?

**Comment by ivanpopelyshev** [comment]
Yep. Just put all displacements in one container and apply filter to it. It requires filter to copy part of existing framebuffer.
