### ISSUE TITLE
Real browser 'click' event for sprites

### ISSUE THREAD

**Issue by JB-Scott** [pixijs/pixi.js#3255]
I need to support full screen functionality in a web game that will be played in browsers on PCs.

Attaching the full screen code to a pixi sprite 'click' event works for Chrome and Firefox. But it does not work for IE. From looking at the source code, the pixi 'click' event is not a real browser 'click' event, but is being generated in response to a browser mouseUp event.

The IE security model will only accept a full screen request in response to a real browser 'click' event. Example: div.addEventListener('click'...

Is there a way to get a true browser based 'click' event supported for sprites?

**Comment by obviously** [comment]
I might be able to help, but I need the info of your device like this:

Name | Value
--- | ---
OS | Windows 10
Browser |  Microsoft Edge 38.14393.0.0 with Microsoft EdgeHTML 14.14393
Pixi.js Version | 4.0.3

Don't know how to make markdown tables? See [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

**I am not a contributer to Pixi.js, I just know how to use it.**

**Comment by themoonrat** [comment]
Could you try the latest dev build and see if that works please

http://pixijs.download/dev/pixi.js

**Comment by themoonrat** [comment]
Ah my bad, didn't read the question properly. You could try listening to the window click, take the positional data from the event, and compare it to the location of the sprite you wanted to be 'clickable' to decide whether to action on the window click

**Comment by JB-Scott** [comment]
Thanks for the suggestion. I already know that a 'click' eventlistener attached to the pixi renderer view will allow a full screen call in IE (it accepts that as valid under the security model). I guess I'll just have to compare the positional data from that event to the position of my sprite button. It would be nice to have a proper click event supported in a future version of pixi, but I can get by for now. Thanks.
