### ISSUE TITLE
Sprite 'click' error

### ISSUE THREAD

**Issue by obviously** [pixijs/pixi.js#3257]
```javascript
sprite.on('click', function ()
{
    bol = !bol;

    if(bol)
    {
        sprite.texture = secondTexture;
    }
    else
    {
        sprite.texture = texture;
    }
});
```

This snippet from the page [https://pixijs.github.io/examples/?v=v4.1.1#/demos/texture-swap.js](https://pixijs.github.io/examples/?v=v4.1.1#/demos/texture-swap.js) does not work! I don't really know why, nor have I looked into it.

Name | Value
--- | ---
OS | Windows 10
Browser |  Microsoft Edge 38.14393.0.0 with Microsoft EdgeHTML 14.14393
Pixi.js Version | 4.0.3

Note: Sprite object is made with `PIXI.Sprite(texture);`

**Comment by themoonrat** [comment]
If you use the latest development version it should work. There was a bug in interaction manager which is fixed in the dev build only

https://pixijs.github.io/examples/?v=dev#/demos/texture-swap.js

**Comment by englercj** [comment]
#3167
