### ISSUE TITLE
Generated texture is blank within a webGL renderer with PIXI 4.1.1

### ISSUE THREAD

**Issue by sami-sweng** [pixijs/pixi.js#3260]
The following code produces nothing (a blank screen):

```
var windowWidth = $(window).width();
var windowHeight = $(window).height();

var renderer = new PIXI.WebGLRenderer(windowWidth, windowHeight, {
    transparent: true,
    view: document.getElementById("canvas"),
    antialias: false,
    resolution: 1
});
renderer.roundPixels = true;

var canvasRenderer = new PIXI.CanvasRenderer(windowWidth, windowHeight, {
    transparent: true,
    antialias: true
});

var container = new PIXI.Container;
var graphics = new PIXI.Graphics();
graphics.beginFill(0x513d24, 1);
graphics.drawRect(0, 0, windowWidth, windowHeight);
graphics.endFill();
container.addChild(graphics);

var maskGraphics = new PIXI.Graphics();
maskGraphics.beginFill(0x000000, 1);
maskGraphics.drawCircle(0, 0, windowHeight / 3);
maskGraphics.endFill();
maskGraphics.position = new PIXI.Point(windowWidth / 2, windowHeight / 2);

container.mask = maskGraphics;
container.addChild(maskGraphics);

var texture = canvasRenderer.generateTexture(container, PIXI.SCALE_MODES.DEFAULT, 1);

var sprite = new PIXI.Sprite(texture);

var finalContainer = new PIXI.Container();
finalContainer.addChild(sprite);

renderer.render(finalContainer);
```

Whereas if I render directly the `container` it correctly displays a brown circle.
The masking part is probably not the cause as if I remove it, I still get a blank display (instead of a brown rectangle).
Changing the intermediary renderer to a WebGL one changes nothing, but using a Canvas renderer as the main renderer displays it correctly.

(tested on Chrome 50)

Also, it works properly with PIXI 3.0.10

Apart form that, thanks a lot for PIXI, it is really a wonderful project!

**Comment by ivanpopelyshev** [comment]
Yeah, it must be possible to use CanvasRenderTexture for webgl.

As a fallback you can use html5 canvas api, and then use Texture.fromCanvas(canvas)

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
