### ISSUE TITLE
I have two sprite,i want  Control update a sprite

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#3261]
if i have two sprite,this two sprite display in page,but a sprite need Constant refresh，so,i want renderer.render(sprite),but the canvas.clearRect all canvas,so how to i canvas.clearRect a sprite.

Thank!

**Comment by kaansoral** [comment]
By the way, check the forum too

"How" questions are usually better aimed at the forum, in my opinion, as 694 people watch this project and get an email each time you create an issue, which is pretty frequent

http://www.html5gamedevs.com/forum/15-pixijs/
