### ISSUE TITLE
Mouse events do not work in IE 11 or Edge

### ISSUE THREAD

**Issue by MaxWilson** [pixijs/pixi.js#3264]
Issue: click/tap/touchstart/buttondown/etc. events do not work in IE 11 or Edge. 

Minimal repro: go to Pixi examples at https://pixijs.github.io/examples/#/demos/interactivity.js using IE 11 or Edge and try to click on one of the "Turn Me On!" affordances. Nothing happens.

Known workarounds: None.

**Comment by themoonrat** [comment]
Use pointer events instead as the workaround.
This has been reported as an issue a few times already, CX and is fixed on the dev branch :)

**Comment by themoonrat** [comment]
@bigtimebuddy - this can be closed - fixed by https://github.com/pixijs/pixi.js/pull/3233
