### ISSUE TITLE
Polygon interactivity problem in 4.1.1

### ISSUE THREAD

**Issue by Patrick-Hammond** [pixijs/pixi.js#3265]
Hi,
Just upgraded to 4.1.1 and noticed this problem:
Polygon hit test working in 3.0.8 http://jsfiddle.net/symbolShift/om5a4qwL/1/
But acting strangely in 4.1.1 http://jsfiddle.net/symbolShift/6wxa46gL/1/

**Comment by themoonrat** [comment]
This is already fixed in the dev branch; just waiting for that to get brought into a release version :)
Proof: http://jsfiddle.net/knvL9ekL/2/

**Comment by Patrick-Hammond** [comment]
Ah, my bad :) Thanks!
