### ISSUE TITLE
Antialiasing + Mask

### ISSUE THREAD

**Issue by GozuPro** [pixijs/pixi.js#3266]
Hello Pixi.js community,

I'm sorry to probably bring that back again but I'm having some issues with masking. I'm simply creating a Graphic and would like to properly mask an image with it. Below, it's the code you might be interested in. Please let me know if you need more from me to understand this issue.

```
var width = $(window).width();
var height = $(window).height()
var points = [0, 100, width, 50, width, height - 50, 0, height - 100];

this.renderer = PIXI.autoDetectRenderer(width, height);

this.mask = new PIXI.Graphics();
this.mask.beginFill(0xFF3300,.5);
this.mask.moveTo(0,0);
this.mask.drawPolygon(this.points);
this.mask.endFill();

this.background = PIXI.Sprite.fromImage('images/01.jpg');
this.background.mask = this.mask;

handleResize:function(e){
   this.renderer.resize(e.width,e.height);
}
```
**This is the result :** 

<img width="875" alt="screen shot 2016-11-09 at 12 21 47 pm" src="https://cloud.githubusercontent.com/assets/6925462/20153879/af33509c-a679-11e6-9b18-bb079b06c5f2.png">

**Related issue** : #2792 

Thanks.

**Comment by GozuPro** [comment]
Anyone ? Any clues ?

**Comment by ivanpopelyshev** [comment]
@GozuPro WebGL antialiasing works only on primary framebuffer. That means, no masks, no filter, e.t.c.

Theoretically, you can make a sprite mask, where the sprite is AA-ed graphics made from canvas with ```js Texture.fromCanvas(...)```, that'll work.

**Comment by GoodBoyDigital** [comment]
```this.renderer = PIXI.autoDetectRenderer(width, height, {antialias:true);```
should help!

Its worth baring in mind there is a performance hit when enabling antialiasing. Also not all browsers / devices support it. 

If this is the case you could add the FXAA filter to your stage to get 'fake' antialiasing. 

```stage.filters = [new PIXI.filters.FXAA()];```

Cheers!
