### ISSUE TITLE
Centered Rotation

### ISSUE THREAD

**Issue by jnccneto** [pixijs/pixi.js#3269]
Hi

I am trying to rotate an object on it's center but cant achieved it. read some info on pivot changing the position but could not figure a way to simply rotate on its center. 
I am doing this:

```
var Obj = new PIXI.Graphics();
Obj.beginFill(0x9b59b6);
Obj.drawRoundedRect(0, 0, 100, 100, 15);
Obj.endFill();
Obj.pivot.set(50,50);
Obj.rotation = 3.14159;
```

But it rotates out of the render, tried Obj.pivot.set(0.5,0.5); like some documentation, but cant get it to keep the position. 
How is it done?

Thanks

**Comment by ivanpopelyshev** [comment]
That's how :)

```js
Obj.drawRoundedRect(-50, -50, 100, 100, 15);
```

**Comment by ivanpopelyshev** [comment]
You have to modify position anyway, there's no other way

**Comment by jnccneto** [comment]
Thanks for inputs
I managed to doing what I wanted but notice that we need to re-position the graphic after setting up the pivot, somehow it was getting out of the position. So I do 
```
Obj.pivot.set
Obj.position.x
Obj.position.y
```
and it goes where I want it

**Comment by nikolas** [comment]
So, to rotate a Graphics object about its center you need to alter its `position`, not `rotation`? I'm still confused here.

I'm used to rotating Sprites by setting their anchor point, then altering their `rotation`.

Graphics objects like a rectangle doesn't have `anchor`, but does have `rotation`, which doesn't seem to behave like I expect it. Anyone have an example of rotating a rectangle about its center in Pixi?

**Comment by themoonrat** [comment]
Use pivot :)

**Comment by nikolas** [comment]
@themoonrat I was, but was having some trouble getting it to work how I expect. I've solved the issue now though, by putting the rectangle in a Container then pivoting that container. Some of Ivan's info here was helpful: http://www.html5gamedevs.com/topic/37296-scaling-rectangle-from-center-and-transform-origin/  So I think I'm starting to get it.

**Comment by themoonrat** [comment]
ahh cool :)
