### ISSUE TITLE
bug in Polygon.contains

### ISSUE THREAD

**Issue by elfrog** [pixijs/pixi.js#3271]
I found mis-positioned ++ operation bug in Polygon.contains method that leads to wrong result of Graphics.containsPoint.

```javascript
for (let i = 0, j = length - 1; i < length; j = ++i)
```

When I change "++i" to "i++", it works correctly.

[link to line](https://github.com/pixijs/pixi.js/blob/ab9efd72af21ce1acc46e9bf3795397fc2544891/src/core/math/shapes/Polygon.js#L97)

**Comment by stbaer** [comment]
This is fixed in dev by #3165

**Comment by elfrog** [comment]
oh, thanks! I didn't know it fixed.
