### ISSUE TITLE
SVG and charset utf8 dataURIs not supported in PIXI 4.1+

### ISSUE THREAD

**Issue by XerxesNoble** [pixijs/pixi.js#3273]
Hey there, 

Using the basic example here: http://pixijs.github.io/examples/?v=v4.0.3#/basics/basic.js

I've pasted the following SVG dataURI as the argument in `PIXI.Texture.fromImage`

```
const texture = PIXI.Texture.fromImage(`data:image/svg+xml;utf8,<?xml version="1.0" encoding="iso-8859-1"?><!-- Generator: Adobe Illustrator 19.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  --><svg version="1.1" id="Box" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"	 viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;" xml:space="preserve"><style type="text/css"> .Background{fill: #202020;}</style><rect id="Background_9_" class="Background" width="50" height="50"/></svg>`);
``` 

Everything works as expected, up until v4.1.0 where the error `'Invalid image type in URL.'` gets thrown. 

I looked into it and noticed that in the function `decomposeDataUri(dataUri) ` is where the problem occurs.  The issue being that the regex constant `PIXI.DATA_URI` does not match dataURIs that are charset `utf8|utf-8`. 

The current regex is : `/^\s*data:(?:([\w-]+)\/([\w+.-]+))?(?:;(charset=[\w-]+|base64))?,(.*)/i`

I changed it to: `/^\s*data:(?:([\w-]+)\/([\w+.-]+))?(?:;(charset=[\w-]+|base64|utf8|utf-8))?,(.*)/i`

(forgive my lazy regex)

Then, I got an error about the SVG parsing from a string. `getSvgSize(svgString)`

`"The SVG image must have width and height defined (in pixels), canvas API needs them."`

There, the regex `PIXI.SVG_SIZE` was only looking for the width/height properties of the SVG element, ignoring the `viewBox` property. 

Parsing xml from regex is known to be quite the buggy experience, I would suggest to move to using DOMParser if possible.

```javascript
const svgDocument = new DOMParser().parseFromString(svgString, 'text/xml')
const svg = svgDocument.getElementsByTagName('svg')[0]

// Grab viewbox data  [x, y, width, height]
const viewBox = svg.getAttribute('viewBox').split(' ').map(Number)

// Attempt to get size from width/height props. 
const size = {}
size.width = +svg.getAttribute('width')
size.height = +svg.getAttribute('height')

// If no width is specified, look at viewbox, probably check for validity here too
if (!size.width || isNaN(size.width)) size.width = viewBox[2]

// If no height is specified, look at viewbox, probably check for validity here too
if (!size.height || isNaN(size.height)) size.height = viewBox[3] 
```

Thanks for reading :)

**Comment by RanzQ** [comment]
Hi, the SVG support was improved in v4.1, a couple of things:
```
const texture = PIXI.Texture.fromImage(`data:image/svg+xml;utf8,<?xml ...
```
Firstly, this is invalid data URI according to the [spec](https://tools.ietf.org/html/rfc2397), charset is a parameter for media type, after that comes `;base64` if it's base64 encoded data. Change `utf-8` to `charset=utf-8` and the regex should match. The error should be more accurate. :)

Second, `viewBox` and `width/height` are not the same thing, read [this](http://jonibologna.com/svg-viewbox-and-viewport/) for example. It turned out to be impossible to support SVGs without size properties, see https://github.com/pixijs/pixi.js/pull/2614.

Also, it's better to use base64 data if you want to support more browsers, for some reason plain svg doesn't work in all situations, see [this comment](https://github.com/pixijs/pixi.js/issues/3075#issuecomment-252824757).

**Comment by XerxesNoble** [comment]
Hey, thanks for the response!

`data:image/svg+xml;utf8,<?xml ...` is just the shorthand to `data:image/svg+xml;charset=utf-8,<?xml ...`. Certainly this is not supported in all browsers. However, if not supported, I agree with you that a more meaningful error message should be displayed, or perhaps, this issue will educate others. :) 

I ended up using base64 after all even after reading comments in [this article](https://css-tricks.com/probably-dont-base64-svg/) and posting this issue. For the exact reason of browser support. 

Thanks for the viewbox article! I just want to clear up that I wasn't insinuating that `viewBox` and `width/height` are one in the same. Viewbox is a powerful attribute that works in tandem with width/height. However, with a high percentage of svg being exported out of Illustrator, I would imagine some support fro missing width/height attributes. (seeing as Illustrator does not export them by default). When no width or height is specified, the SVG is scaled to fit the parent container, maintaining the aspect of the viewBox width/height property. 

After reading [#2641](https://github.com/pixijs/pixi.js/pull/2614) it does make sense to require a width/height 

Either way, this a great addition to PIXI, thanks @RanzQ

**Comment by RanzQ** [comment]
As I said, it's invalid according to the spec, so I wouldn't trust it. :) For example, utf-8 works in Chrome even if you don't have the charset parameter: http://codepen.io/RanzQ/pen/vyKjzM 

So I guess it defaults to utf-8 in Chrome. Haven't seen that "shorthand" documented anywhere so I think the author of that article just instructed wrong.

Better to use base64. :)

@XerxesNoble Anyway, thanks, nice to know this feature is useful. I'll try to come up with a PR for more meaningful errors at some point.

**Comment by verochan** [comment]
I came across to this issue while I was looking for if it's possible to create an atlas in pixi using SVG images, is it? I'm doing some tests but I can't load any atlas in this format, don't know if I'm doing something wrong or if it's not supported as there's little information about this on github or docs. Sorry if it's not the correct place to ask this, thanks.
