### ISSUE TITLE
Graphics getLocalBounds stops working after generateCanvasTexture is called

### ISSUE THREAD

**Issue by funkybjorn** [pixijs/pixi.js#3274]
Hello!

After updating to PIXI v.4.1.1 I noticed a change in the behavior of generateCanvasTexture() on the Graphics object, which I use quite extensively in the project I'm currently working on. It appears that once generateCanvasTexture() is called on a graphics object, the bounds on that graphics object stop updating even if the graphics object is cleared and new graphics are drawn to it. This was not the case before. And since generateCanvasTexture() uses getLocalBounds() within, it returns a texture with a size that does not necessarily match the size of the graphic.

An example would be if I draw a 10x10 rectangle on a graphics object, then call generateCanvasTexture() on that object, a 10x10 texture will be returned. But if I then clear that graphic object and draw a 20x20 rectangle, calling getLocalBounds() on that object will still return a 10x10 rectangle, and calling generateCanvasTexture() again will return a 10x10 texture. If you do the exact same thing without calling generateCanvasTexture(), getLocalBounds works as expected.

See code sample below - any insight would be helpful!

```js
var squareGraphic = new PIXI.Graphics();

var bounds;

//--

squareGraphic.beginFill(0xFFFFFF, 1);
squareGraphic.drawRect(0, 0, 20, 20);
squareGraphic.endFill();

bounds = squareGraphic.getLocalBounds();
console.log('SHOULD BE 20x20 :', bounds.x, bounds.y, bounds.width, bounds.height);

//--

// COMMENT THIS LINE OUT AND BOUNDS WORK PROPERLY
squareGraphic.generateCanvasTexture(PIXI.SCALE_MODES.DEFAULT, 2);

//--

squareGraphic.clear();
squareGraphic.beginFill(0xFFFFFF, 1);
squareGraphic.drawRect(0, 0, 10, 10);
squareGraphic.endFill();

bounds = squareGraphic.getLocalBounds();
console.log('SHOULD BE 10x10 :', bounds.x, bounds.y, bounds.width, bounds.height);
```

**Comment by staff0rd** [comment]
Here's a fiddle of that code; https://jsfiddle.net/2y1d7ygy/ 

Prior to #3022, resolution was not being properly set, and now that it is, the `2` in this line;
~~~
squareGraphic.generateCanvasTexture(PIXI.SCALE_MODES.DEFAULT, 2);
~~~
is (correctly) producing a texture at `2x` the size of your second `squareGraphic` dimensions.

**Comment by funkybjorn** [comment]
Hi @staff0rd 

I checked out your fiddle, and I still don't see this as resolved.

Please see the following [fiddle](https://jsfiddle.net/funkybjorn/kuz8p4Lh/) which further exemplifies the problem at hand.

If "generateSquareTexture" is set to false, getBounds() works as expected and outputs:

> Square Texture is NOT generated.
> 
> SHOULD BE 20x20 : 20x20
> SHOULD BE 5x5 : 5x5
> SHOULD BE 43x43 : 43x43

If "generateSquareTexture" is set to true, getBounds() continues to return the original graphic dimensions even after the graphics have been cleared and altered, and the code outputs:

> Square Texture is generated.
> 
> SHOULD BE 20x20 : 20x20
> SHOULD BE 5x5 : 20x20
> SHOULD BE 43x43 : 20x20

Hopefully this brings further clarity to the issue. Thank you!

**Comment by staff0rd** [comment]
Indeed, it seems you are correct!  Thanks for the fiddle!
