### ISSUE TITLE
I want add a Img to sprite,but how to i cut it

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#3276]
hello ,
i user sprite.fromImage().or texture.fromImage() add a image,and i want cut the image,Can this be done？

**Comment by finscn** [comment]
There is no short way for it.
you have to do it step by step via  img, x, y, width, height .

```
    var baseTexture = new PIXI.BaseTexture(img);
    var texture = new PIXI.Texture(baseTexture, new PIXI.Rectangle(x, y, width, height));
    var sprite = PIXI.Sprite.from(texture);
```

**Comment by Icemic** [comment]
If you want to change a image's display area frequently, you might as well just setting `sprite.fillterArea`.

**Comment by fengFanYong** [comment]
How am I setting sprite.filterArea?

**Comment by themoonrat** [comment]
Hi @fengFanYong - is this still an issue or are you all sorted now? :)

**Comment by GoodBoyDigital** [comment]
looks done to me!
FYI - @finscn's method is the correct approach.

```
var baseTexture = new PIXI.BaseTexture(img);
    var texture = new PIXI.Texture(baseTexture, new PIXI.Rectangle(x, y, width, height));
    var sprite = PIXI.Sprite.from(texture);
```

FilterArea is used for something different. Cheers!
