### ISSUE TITLE
How to do a gradient mask? Or, how to fade out the edge of a DisplayObject?

### ISSUE THREAD

**Issue by trusktr** [pixijs/pixi.js#3278]
I was playing with the [panda mask demo](http://www.goodboydigital.com/pixijs/examples/14/), and if I set the opacity of the `thing` mask to `0.5` or `1.0`, the result is the same. If I change the color to white or black, the result is the same.

I was hoping that different levels of opacity, or varying colors would mask more (or mask less) each pixel depending on the color or opacity.

For example, in SVG, a gradient from black to white (or white with opacity 0 to white with opacity 1) will cause the final white pixels to be shown, while black or opacity-0 pixels will cause content to be invisible.

So I thought I could write this function to make a gradient, then apply it as a texture:

```js
function createLinearGradient(width, height, stops, mapFn) {
    mapFn = typeof mapFn == 'function' ? mapFn : function(canvas) {return canvas}

    var canvas = document.createElement('canvas')

    canvas.width = width
    canvas.height = height

    var ctx = canvas.getContext('2d')
    var gradient = ctx.createLinearGradient(0, 0, width, 0)
    var stopPoints = Object.keys(stops)

    for (var i=0, n=stopPoints.length; i<n; i+=1)
        gradient.addColorStop(parseFloat(stopPoints[i]), stops[stopPoints[i]])

    ctx.fillStyle = gradient
    ctx.fillRect(0, 0, width, height)

    return mapFn(canvas)
}
```

But that won't seem to work based on what I observe in the panda demo (tried with pixi.js v4.1.1).

Can we achieve a gradient-based mask in Pixi.js?

If not, how would you recommend fading out a texture?

For reference, what I'm trying to create is a text marquee where text fades as it approaches the end of the texture.

**Comment by trusktr** [comment]
Ah, yep, I was able to do it!! When I replaced the `PIXI.Graphics` with a `PIXI.Sprite` containing my gradient texture, that makes a gradient fade out! So, that accomplishes what I want.

I'll close, but I also have a question:

Why does the color of a `PIXI.Graphics` not have the same effect as the color of a `PIXI.Sprite` when either is applied as a mask?

**Comment by englercj** [comment]
Graphics are used a vector masks, they just cut out area based on the shape. Sprites are alpha masks, the color determines the alpha of what it is masking.
