### ISSUE TITLE
How to set fillRule of PIXI Graphics ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3282]
in HTML5 Canvas , when draw polygon , there are 2 fillRules : 

> fillRule:
> The algorithm by which to determine if a point is inside a path or outside a path.
> Possible values:
> "nonzero": The non-zero winding rule, which is the default rule.
> "evenodd": The even-odd winding rule.

How to do that in PIXI ? and Which algorithm is used in PIXI ?

**Comment by finscn** [comment]
the terminology of  fillRule is 『winding rule』 ：
https://en.wikipedia.org/wiki/Nonzero-rule
https://en.wikipedia.org/wiki/Even-odd_rule

There is an article  talk about it with OpenGL :  http://www.glprogramming.com/red/chapter11.html

**Comment by finscn** [comment]
Could you help me ？ @englercj  @GoodBoyDigital

**Comment by englercj** [comment]
I think the tessellation that article describes is using GLU, which we don't have in WebGL.

**Comment by finscn** [comment]
Thanks.

**Comment by bobby** [comment]
Having the ability to control the Winding Rule would really help when integrating with backend 2d libraries like java.awt.geom.

**Comment by 1j01** [comment]
In case this is useful to anyone, I have some working code (not using PIXI but using WebGL) which draws polygons with an even-odd winding rule: see https://github.com/pixijs/pixi.js/issues/891#issuecomment-473567390

It uses [libtess.js](https://github.com/brendankenny/libtess.js/) to convert the polygon to a list of triangles that make up the filled regions.
