### ISSUE TITLE
[Dev Build] Black Textures + Black Game

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#3288]
I previously reported this issue: https://github.com/pixijs/pixi.js/issues/3235 - Yet a more recent dev build solved the majority of my issues

However, still, very occasionally, some textures act up, very rarely, a PIXI.Text is rendered black for an instant

Because of the "pointer" event issues etc. I can't easily roll back to a stable earlier version either (+ I'm using the new/improved TilingSprite, so I can't pinpoint a build that is in-between these two)

The actual reason I created this issue is, a player is reporting a completely dark game, yet, it's one of those players that reports a critical issue, yet doesn't follow through to debug, so I'm blind to this issue, I suspect it could be related to my own black texture experiences, but at a larger scale

**Comment by ivanpopelyshev** [comment]
Just found some problems for iOS, can you test it again?

**Comment by ivanpopelyshev** [comment]
Also, do you use ParticleContainer by some chance?

**Comment by kaansoral** [comment]
The issue didn't happen this intense for me (It only happened once every 2-3 hours on a single PIXI.Text), and the player who experienced the issue never came forward - Instead, the friend of the player used the issue to continually badmouth the game, stating his friend entered a black world whenever he tried to play - I believe the issue happened, since it was on-par with things I saw at one point, yet, sadly, I didn't get to debug it 1:1

Going to push 4.2.2 soon, while not imminently, maybe I will learn whether the issue was solved or not, will update this thread if I learn anything tangible

**Comment by GoodBoyDigital** [comment]
Hi @kaansoral , hows the latest dev version of pixi treating you? Is this issue still present? Thanks!

**Comment by kaansoral** [comment]
@GoodBoyDigital Thanks for checking in, I updated to 4.3.2, I think the original issue is fixed, yet there is another, in my opinion different "Black Screen" issue - Their origin might be the same, I was just about to create an issue for that, let me close this, and reference this issue on that thread
