### ISSUE TITLE
ArrayBuffer is undefined in IE9

### ISSUE THREAD

**Issue by antag0n1st** [pixijs/pixi.js#3291]
I guess it is used before this line is executed

`if (!window.ArrayBuffer) {
    window.ArrayBuffer = Array;
}`

**Comment by Friksel** [comment]
Hi @antag0n1st , I guess the latest pixi-versions are not supporting ie9 anymore. I solve this with the inclusion of a polyfill just for IE9 users:
`<!--[if lt IE 10]><script src="js/typedarray.min.js"></script><![endif]-->`
Wich can be found here:
https://github.com/inexorabletash/polyfill/blob/master/typedarray.js

**Comment by staff0rd** [comment]
I'm gonna mark this as a bug considering the [wiki](https://github.com/pixijs/pixi.js/wiki/FAQs) says IE9+ is supported.

**Comment by themoonrat** [comment]
In index.js, the 2nd line is
import './polyfill';

I know from previous commits that 
import './deprecation';
was changed to
export * from './deprecation';

to force bringing in the code earlier... but I tried that trick with polyfills and it didn't work :/
