### ISSUE TITLE
PIXI v4.1 is undefined webpack

### ISSUE THREAD

**Issue by lbineau** [pixijs/pixi.js#3294]
Since recently PIXI the import of PIXI is undefined  (using webpack but I guess it is the same with browserify)

PIXI v4.1.1
```javascript
import PIXI from 'pixi.js' // returns undefined
```

PIXI v4.0.3
```javascript
import PIXI from 'pixi.js' // returns PIXI Object
```

Correct me if I'm wrong but I also noticed that the path is wrong in package.json it should not be the builded project but the main source file isn't it ?

**Comment by lbineau** [comment]
anwsered in comments of https://github.com/pixijs/pixi.js/issues/3224

**Comment by englercj** [comment]
Also this: https://github.com/pixijs/pixi.js/issues/3204#issuecomment-256751902
