### ISSUE TITLE
Moving mouse out of pixijs canvas sets inline cursor style

### ISSUE THREAD

**Issue by joshas** [pixijs/pixi.js#3301]
Easily observable in every pixijs project, even the one on pixijs website. First move mouse cursor on canvas and then move it on some other element outside of canvas, or outside browser window. As a result "cursor: inherit;" inline style is permanently set for <canvas> element. This prevents setting custom cursors for canvas using CSS classes.

**Comment by andrewstart** [comment]
A while back I wrote some code to allow for custom CSS or on-stage cursors, I will see about updating and improving that.
