### ISSUE TITLE
4.2.1 broke something on Iphone/ios

### ISSUE THREAD

**Issue by bQvle** [pixijs/pixi.js#3307]
http://178.155.161.95/test/4.2.1.html (broken)
http://178.155.161.95/test/4.1.1.html (works)

Console:
```
TypeError: undefined is not an object (evaluating 'this.vertexBuffers[this.vertexCount].bind')
start — pixi.js:20820
setObjectRenderer — pixi.js:16401
_renderWebGL — pixi.js:19596
renderWebGL — pixi.js:8387
renderWebGL — pixi.js:8391
renderWebGL — pixi.js:8391
renderWebGL — pixi.js:8391
renderWebGL — pixi.js:8391
renderWebGL — pixi.js:8391
renderWebGL — pixi.js:8391
renderWebGL — pixi.js:8391
render — pixi.js:16375
Update — test:323
init — test:316
(anonymous function) — test:28
emit — pixi.js:990
_onComplete — pixi.js:5335
(anonymous function) — pixi.js:5374
next — pixi.js:6329
bitmapFontParser — pixi.js:32076
(anonymous function) — pixi.js:5354
next — pixi.js:6335
spritesheetParser — pixi.js:32365
(anonymous function) — pixi.js:5354
next — pixi.js:6335
textureParser — pixi.js:32506
(anonymous function) — pixi.js:5354
next — pixi.js:6335
(anonymous function) — pixi.js:6677
(anonymous function) — pixi.js:5354
next — pixi.js:6335
asyncEachSeries — pixi.js:6336
_onLoad — pixi.js:5351
emit — pixi.js:989
complete — pixi.js:5669
```

@GoodBoyDigital Maybe you know whats up?

**Comment by staff0rd** [comment]
Probably unrelated, but I see something weird in the Chrome console for 4.2.1 in your examples;

#### 4.1.1
![image](https://cloud.githubusercontent.com/assets/6289998/20378135/346a5246-ace8-11e6-8255-f3c742fc6309.png)

#### 4.2.1
![image](https://cloud.githubusercontent.com/assets/6289998/20378129/2b42da58-ace8-11e6-901a-7c32306dd8b2.png)

**Comment by kaansoral** [comment]
Haha, that was the first thing I noticed too

Tested on the iOS Simulator, it doesn't work for me either

However, I tested 4.2.1 in my own game, on the same simulator, didn't notice an issue myself, tho I don't have the Web Inspector setup

**Comment by ivanpopelyshev** [comment]
#3308

**Comment by bigtimebuddy** [comment]
@bQvle could you verify this is fixed using the PR that @ivanpopelyshev added: http://pixijs.download/dev/pixi.js

**Comment by bigtimebuddy** [comment]
I can confirm this is fixed. Will make a patch release.
