### ISSUE TITLE
How to draw a UI Sprite with 9-cells-grid ，like borderImage

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3311]
I create 9 sprites with Rectangle based on a Sheet image.

But there are some gaps between sprites.

**Comment by themoonrat** [comment]
Could this be what you are after?

http://pixijs.download/v4.2.2/docs/PIXI.mesh.NineSlicePlane.html

**Comment by finscn** [comment]
Yes. Thanks
