### ISSUE TITLE
About moving `pixi-live2d` repo here

### ISSUE THREAD

**Issue by Icemic** [pixijs/pixi.js#3313]
Hey, I am invited by @ivanpopelyshev about making my `pixi-live2d` package official. (via https://github.com/avgjs/pixi-live2d/issues/1)

So, what should we do now?

**Comment by ivanpopelyshev** [comment]
As soon as @GoodBoyDigital comments there, you can transfer the repo to him, he'll make it into @pixijs org and checks that you have admin access to it.

**Comment by Icemic** [comment]
@ivanpopelyshev @GoodBoyDigital 

Hey, how is this going on?
