### ISSUE TITLE
Pixijs 4.x.x and Pixijs 3.x.x performance difference on Android devices

### ISSUE THREAD

**Issue by valtver** [pixijs/pixi.js#3314]
Hello guys, after migration from Pixi 3 to Pixi 4 we faced performance drop on several devices. 
Also noticed your examples on these devices perform differently as well.

**Performance comparison between PixiJS v3 and v4 using spine example:**
https://pixijs.github.io/examples/?v=release#/spine/dragon.js
https://pixijs.github.io/examples/?v=v3.0.11#/spine/dragon.js

**Tested devices list:**
**Android**
Motorola MotoG3 - XT1541 - Android 6.0.1 (WebGL) - v3: ~60fps / v4: ~30fps
Asus Nexus7 - ME370TG - Android 5.1.1 (Canvas) - v3: ~60fps / v4: ~30fps
HTC One - M8 - Android 5.0.1 (WebGL) - v3: ~60fps / v4: ~30fps
**iOS**
iPad4 16GB - iOS 9.3.5 (WebGL)  - v3: ~60fps / v4: ~60fps
iPad2 16GB - iOS 9.2.1 (WebGL)  - v3: ~60fps / v4: ~60fps

**Workaround attempts:**
- Pixi-spine updated (no improvement :( )

Performance difference is visually noticeable, v4 fps drop is non-linear and doesn't really change after adding more elements on the scene.

**Comment by GoodBoyDigital** [comment]
Hi there! 

Could you try adding this line before you create the renderer:

```PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;```

Cheers!

Mat

**Comment by valtver** [comment]
Hi Mat,
  Thanks for that, but no luck :(
We are actually using that already. It fixes tiling-sprite rendering.

Cheers!

Val

**Comment by GoodBoyDigital** [comment]
Cool, does this issue only appear with spine? Or is it apparent in other examples too?

Cheers!

**Comment by valtver** [comment]
Non-spine examples perform good on both versions.
![ea362c736c3ea4990cb8997cb3c387ee89eb5d35283920e2cf pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6719094/20433028/8ba2695a-adaa-11e6-885d-15956d667829.jpg)
good.

**Comment by ivanpopelyshev** [comment]
Can you try to isolate this example, run it not in iframe?

**Comment by ivanpopelyshev** [comment]
Of course its 30FPS! the version in examples is pre-pixi-4.0.0 and flowing console with deprecation log messages. I'm updating the examples repo right now

**Comment by j-funk** [comment]
Now I'm curious about benchmarks for the new examples!

**Comment by ivanpopelyshev** [comment]
@j-funk it was only the pixi-spine version problem

**Comment by valtver** [comment]
@ivanpopelyshev logs are not really matter. Dragon spine on iOS it's still 60fps... on Android it's even lower... I measured ~30-10fps. I will try to eliminate iframe later.

**Comment by ivanpopelyshev** [comment]
@valtver browser cache.

**Comment by valtver** [comment]
@ivanpopelyshev yeah, thanks, mate! Works fine now!
