### ISSUE TITLE
Browserify can't find pixi.js as npm module

### ISSUE THREAD

**Issue by PainKKKiller** [pixijs/pixi.js#3316]
I am not good at new javascript technique, so may be my problem really stupid. But I am trying to test pixi.js and to setup my development enviroment.
So I am installing pixi.js with npm:

`npm install -s pixi.js`

Then I made index.js file just for test:
`var PIXI = require('pixi.js');
//var PIXI = require('node_modules/pixi.js/pixi.js');
var renderer = new PIXI.CanvasRenderer(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.view);
var stage = new PIXI.Stage;
var zombieTexture = PIXI.Texture.fromImage('zombi.png'); 
var zombie = new PIXI.Sprite(zombieTexture);

zombie.position.x = window.innerWidth / 2 - 150;
zombie.position.y = window.innerHeight / 2 - 150;
stage.addChild(zombie);

function draw() { renderer.render(stage); requestAnimationFrame(draw); }

draw(); `

Then I run browserify to compile index.js with pixi as dependency:

`browserify index.js -o bundle.js`

And it gives me error:

`Error: Cannot find module 'pixi.js' from 'C:\Users\PainKiller\Desktop\pixitest'
at C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
at process (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
at ondir (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
at load (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
at onex (C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
at C:\Users\PainKiller\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
at FSReqWrap.oncomplete (fs.js:123:15)`

But as far as I know browserify works with npm modules. Please clarify this issue.

**Comment by PainKKKiller** [comment]
I also created a question about this on stackoverflow http://stackoverflow.com/questions/40660456/development-workflow-with-pixi-js-and-browserify-error-browserify-cant-find-p

**Comment by hassanshaikley** [comment]
1.  npm install -s pixi.js is wrong, what you want is  
npm install -S pixi.js

2. the command above really only works after you do
npm init -y

3.  I followed all of your steps and copied your code and was able to get a javascript file that browserify was okay with.

**Comment by PainKKKiller** [comment]
It's really strange because I followed your steps (and I did it before I created this issue). I did create new folder and new project and used all commands and I still can't use browserify am still getting the same error. Have no idea what's wrong. I've tested browserify with jquery installed via npm, and everything worked fine, so I suppose problem not in browserify or how I use it. Anyway thanks for collaboration.

**Comment by PainKKKiller** [comment]
So far I think problem in folder and file structure in pixi.js installed via npm. I can't find index.js file  similar to this https://github.com/pixijs/pixi.js/blob/dev/src/index.js

**Comment by ivanpopelyshev** [comment]
If you want to solve the real issue, sure, keep digging :) I'm digging it to. The problem is that "src" is not published on npm, while the file in "bin" somehow isn't possible to require.

But seriously, if you need to build an app - declare PIXI as global, and don't use browserify to wrap your app with big libraries. If you use like 10 big libs, you'll et 10 JS files which isn't that bad. Also, the final result can be just concatenated.

**Comment by ivanpopelyshev** [comment]
We can also ask @englercj, he's an expert on build systems. I'm sure he finds a fault in my logic.

**Comment by PainKKKiller** [comment]
@ivanpopelyshev  thanks alot for your response, you're making a great engine. So far I am satisfied with solution you're discribed in your post, I made PIXI global, made my index.js, from it I refer to PIXI as global variable, and use other npm and my own modules with require(). I think one more (but I didn't test it) solution would be wrap release file pixi.js in 
`module.exports = {
 
};`

and use it with require() as my own module. Anyway, I am not expert in JS build systems but I'll keep in mind this issue, and if I'll find something I'll write it here. Again thanks for collaboration!

**Comment by ivanpopelyshev** [comment]
@PainKKKiller 
 
If you do that, I suggest to compare the times of compilation if its concatenated or browerified.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
