### ISSUE TITLE
Strange bug with loader.resources when using npm module

### ISSUE THREAD

**Issue by hassanshaikley** [pixijs/pixi.js#3318]
I am using babel es6 2015.

And getting a strange bug where.

console.log(PIXI.loader.resources.playerCast0) 

Does the right thing and prints:

<img width="323" alt="screen shot 2016-11-18 at 8 38 20 pm" src="https://cloud.githubusercontent.com/assets/6746840/20452781/fb406018-adce-11e6-8be9-76e9669652f0.png">

But at the same time, literally the next line of code

PIXI.loader.resources.playerCast0.texture 

is equals to undefined.

Anyways, I would really appreciate help with this bizarre bizarre bug..

**Comment by GoodBoyDigital** [comment]
cc @englercj !

**Comment by englercj** [comment]
inspecting the chrome console displays the value of the object you log *at the time you expand it*. Meaning you almost certainly have some async code that is being treated like it is synchronous.

Please show us how you are using the loader, and doing the logs.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
