### ISSUE TITLE
Linearly scaling images?

### ISSUE THREAD

**Issue by hassanshaikley** [pixijs/pixi.js#3319]
I have pixel art and I want it to linearly scale. I have done some research online but haven't found anything.

I have really simple art but I want to be zoomed into it.

Is this possible?

**Comment by themoonrat** [comment]
Yes, base textures have a scaleMode property. You can change it from the default of nearest (0) to linear (1)

**Comment by hassanshaikley** [comment]
Can you give me an example? Is there a way to call it once and make all textures scale linearly?

**Comment by kaansoral** [comment]
`PIXI.utils.BaseTextureCache[file].scaleMode=PIXI.SCALE_MODES.NEAREST`

**Comment by ivanpopelyshev** [comment]
You can set it for all textures at the same time:

```js
PIXI.SCALE_MODES.DEFAULT = PIXI.SCALE_MODES.NEAREST
```

**Comment by giraluna** [comment]
@ivanpopelyshev `PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST` since 4.2

https://github.com/pixijs/pixi.js/pull/3298

**Comment by ivanpopelyshev** [comment]
@giraluna :) Yep, totally forgot about it!

**Comment by kaansoral** [comment]
For 4.2.2, only my method works tho, however temporary this is :)

**Comment by themoonrat** [comment]
Closing this as the question has been answered for both pre 4.2 and post 4.2.
