### ISSUE TITLE
What does FilterManager.shaderCache do ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3320]
In FilterManager , I found  there is a map named shaderCache, it will cache the shader of filter.
But In PIXI , never read anything from filterManager.shaderCache .

So, What does FilterManager.shaderCache do ?

**Comment by englercj** [comment]
The shader cache is an internal object used to cache programs we compile for a given context. It allows us to not have to recompile a shader every time you create an instance of a filter.

It is not for external use.
