### ISSUE TITLE
Render Texture in IE

### ISSUE THREAD

**Issue by Ewance** [pixijs/pixi.js#3321]
Hello, it looks like Render Textures dont work in IE for Windows Phone (Edge is well) after 4.1.1 version.

**Comment by themoonrat** [comment]
Hi @Ewance - could you create a jsfiddle that reproduces this issue please?

**Comment by Ewance** [comment]
Hi @themoonrat , I just open Render Texture examples on WindowsPhone 8.1
and demos dont work with pixijs after 4.1.1
http://pixijs.github.io/examples/#/basics/render-texture.js
http://pixijs.github.io/examples/#/demos/render-texture-demo.js
pixi 4.1.1 looks fine

**Comment by themoonrat** [comment]
I can't see anything wrong on a windows 10 phone with Edge, but I do see problems with Windows Phone 8.1 with IE

**Comment by englercj** [comment]
Hey @Ewance I don't have a Windows Phone, but can you check if this is fixed for you on the latest version? If not, can you try setting the `legacy` option via the WebGLRenderer constructor and see if that fixes your issue?

**Comment by psyrendust** [comment]
@englercj: I just gave this a try and I'm having issues rendering textures from a dataURI in IE 11 and Edge. Creating a texture from a png works fine in both. I've tried to run this with `legacy` set to `true` and `false`. I created a jsfiddle that uses `Texture.fromImage()` using a png and a data uri. It works fine in other browser, just not IE or Edge.

https://jsfiddle.net/psyrendust/c3ntwfab/

#### Windows Edge
![image](https://cloud.githubusercontent.com/assets/928502/26594845/2ac8f304-451e-11e7-8099-989e372f2353.png)

#### Windows IE 11
![image](https://cloud.githubusercontent.com/assets/928502/26594865/3db4420c-451e-11e7-9532-c98a59f91387.png)

#### Windows Firefox
![image](https://cloud.githubusercontent.com/assets/928502/26595215/8e58bebc-451f-11e7-972c-db7ef2f410cf.png)

#### Windows Chrome
![image](https://cloud.githubusercontent.com/assets/928502/26595318/d63742f8-451f-11e7-8008-adc09d2a16a3.png)

#### OS X Chrome
![image](https://cloud.githubusercontent.com/assets/928502/26594960/9e1ccf1a-451e-11e7-8d40-ef0dc703de67.png)

**Comment by englercj** [comment]
Hi @psyrendust this is a different issue. This issue is about using `RenderTexture`s in IE. Would oyu mind opening a new issue for your problem?

Thanks!
