### ISSUE TITLE
About RenderTexture , RenderTarget and Filter

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3323]
I want to custom a filter ,
In this filter , I need to render a sprite to a temp RenderTexture ,  so I call  : 
```
// in Filter.apply method : 
 renderer.render(sprite,  tempRenderTexture,  true);
```
 How can I let the  tempRenderTexture as a input renderTarget , then pass it  to the  applyFilter ?

And Is there a document talk about  RenderTexture &  RenderTarget ?

**Comment by ivanpopelyshev** [comment]
You have to look into sources of DisplacementFilter or may be some other filter. Pretty sure your renderTexture is called "input" in applyFilter.

**Comment by ivanpopelyshev** [comment]
May be you need an extra renderTexture for second pass, but that's all possible and is already used in PIXI filters. There's no documentation on that, you have to understand whats going on using the source code

**Comment by finscn** [comment]
『May be you need an extra renderTexture for second pass, but that's all possible and is already used in PIXI filters』 ， which filter ？ I found all filters ， no one used "renderTexture for second pass"

**Comment by GoodBoyDigital** [comment]
once you have ```tempRenderTexture```

you can use it as a texture on your shader:

```
myFilter = new AwsomeFilter();
myFilter.uniforms.anInputTexture = tempRenderTexture
```

Cheers!±
