### ISSUE TITLE
bower.json refers to bin/pixi.min.js which doesn't exist

### ISSUE THREAD

**Issue by jhanssen** [pixijs/pixi.js#3327]
I'm new to the world of bower so disregard this if I'm doing something wrong. I installed pixi using bower and I'm using a tool that essentially calls ``bower list -p`` to get the main paths of installed bower components. This returns the path ``bower_components/pixi.js/bin/pixi.min.js`` which doesn't exist in the component installation. I see the README says that running ``npm run build`` will generate the file in bin but the bower installation doesn't include files such as the eslint config so the npm command fails.

**Comment by bigtimebuddy** [comment]
We recently did some re-organization and renamed "bin" to "dist" but forgot to update the **bower.json** file. I submitted a PR to fix this. Thanks for pointing it out.
