### ISSUE TITLE
PIXI.Bounds is missing

### ISSUE THREAD

**Issue by OSUblake** [pixijs/pixi.js#3329]
It looks like the export for `PIXI.Bounds` is missing. I'm getting a `PIXI.Bounds is not a constructor` error when I try to create one.

Using v4.2.2

**Comment by bigtimebuddy** [comment]
@OSUblake thanks for pointing this out. Looks like when we reorganized some of the code in 4.1, we neglected to expose Bounds again. I submitted a PR to fix.
