### ISSUE TITLE
SVG sprites do not get tint. 

### ISSUE THREAD

**Issue by samjohn** [pixijs/pixi.js#3334]
Setting the tint property on a sprite with an SVG texture does not change the sprites tint. 

https://jsfiddle.net/8zenuva0/3/

Thanks!

**Comment by andrewstart** [comment]
Tints work by multiplying the existing color, so you get the full effect of the tint on white pixels, and no effect on black pixels. Your SVG needs a non-black fill and it will work fine.

**Comment by samjohn** [comment]
aaah, very helpful! Thanks you @andrewstart.
