### ISSUE TITLE
Filter behaves weird in Container

### ISSUE THREAD

**Issue by Icemic** [pixijs/pixi.js#3338]
Steps:
1. Create two Graphics (for example, two rectangle), `sp1` and `sp2`
2. Create two Container, `c1` and `c2`
3. Let add `sp1` to `c1`, add `sp2` to `c2`
4. set filters(VoidFilter) and filterArea of two Container
5. add `c2` to `c1`

try to comment `this.filters=xxx` or `this.filterArea=xxx`, you will notice that when any statement is commented out, it behaves differently than when two statements exist at the same time.

Is it normal performance? If so, could you tell me why?

test case: https://jsfiddle.net/Icemic/6oebqatq/7/

**Comment by Icemic** [comment]
Oh, it seems that the `x` and `y` in `filterArea` must be global coordinates?

If so, I will know the reason of my problem...

But..however, it means if I want to move a parent node frequently, I have to re-set `filterArea` in every tick...It is quite a pain!

Is there any way to control display area of a displayObject easier?
 (I want to make a similar effect to `overflow: hidden` in CSS for displayObject)

**Comment by GoodBoyDigital** [comment]
Hi @Icemic ,

Yes - filterArea is global screen coord. It is also optional, so omitting it should get you the results your after!

FilterArea is designed as an optimisation of avoiding the need to measure the bounds of the target object before applying the filter.

Hope that helps! 

Cheers!
