### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by goldenratio** [pixijs/pixi.js#3339]
Hi,

I am trying to upgrade from pixi v3.0.11 to 4.2.2.
When I try to use PIXI.Sprite or any PIXI objects with Tween.js https://github.com/tweenjs/tween.js/, I am getting this error: 

```
new TWEEN.Tween(new PIXI.Sprite());
```

libs.js:formatted:19537 Uncaught TypeError: Cannot convert object to primitive value(…)TWEEN.Tween @ libs.js:formatted:19537(anonymous function) @ VM899:1

It could be Tween.js issue, but pixi v 3.0.11 is working fine.
If someone could help solve this issue, it would be great.

**Comment by goldenratio** [comment]
Found out issue is related to EventEmitter.

```
let gfx = new PIXI.Sprite();
new TWEEN.Tween(gfx._events)
```
throws Cannot convert object to primitive value(…)TWEEN.Tween 

btw `._events` property doesn't exist in pixi v3. Is it because of the new ES6 syntax.

**Comment by hendrysadrak** [comment]
It is a problem with tween.js and how it parses objects, because i had the same problem and now i use a custom build of tween.js where i changed some things so it would work.

**Comment by goldenratio** [comment]
ok.. closing this..
