### ISSUE TITLE
handle multiple stages gracefully

### ISSUE THREAD

**Issue by enriko-riba** [pixijs/pixi.js#334]
I know there have been requests for multiple renderers, but this is about having them multiple but only one active. The problem is that while pixi allows creating multiple stages it is not really aware of them nor trying to handle them...

I am building a SceneManager where a user can create multiple scenes, the later extending the Stage. So one can have an Options scene, main game scene, intro scene etc. The SceneManager simply opts to invoke the render() on the one and only "active" scene. This naive concept is not working as pixi is not aware that other stages are not active.

There should be at least a concept of active/inactive stages. 
For example adding various mouse handlers to multiple scenes (stages) all got fired. So if you happen to change a visual  e.g. cursor inside mousemove on a "inactive" stage , you cant easily prevent the handler from executing. 

We need something similar to stage.renderable = false which would turn off the interaction manager and every other internal stage processing until the stage becomes "Active" or "enabled" again.

Maybe the InteractionManager should be per stage only?

**Comment by weepy** [comment]
Is this possible with v3?

**Comment by englercj** [comment]
Have you tried? :)

**Comment by weepy** [comment]
I thought it would be quicker to ask :)

**Comment by weepy** [comment]
seems to work a treat :)
