### ISSUE TITLE
Using THREE.js render inside PixiJS

### ISSUE THREAD

**Issue by brunosimon** [pixijs/pixi.js#3345]
Hello!

I'm having some troubles with a pretty complexe project . I need to implement a THREE.js render inside PixiJS.

I found a lot of discussions about people wanting to do the opposite (PixiJS inside THREE.js) but it's impossible in my case. Most of the project is in PixiJS. Only a small part need to be a 3D render.

Is it possible ? I can't find any exemple.

Awesome work by the way,  PixiJS is such a huge time saver.

**Comment by JiDW** [comment]
We do not use THREE.js but we use our own 3d engine inside PIXI.

The idea is, in the same loop, to do the following step:
- Render your THREE.js
- Restore the GL environment to what PIXI wants
- Render your Pixijs

Obviously, to restore opengl, you need to know what you modified in the first place in order to use three.js

This is what we do for our use case:

```javascript
gl.disableVertexAttribArray(3);
gl.disable(gl.DEPTH_TEST);
gl.enable(gl.BLEND);
gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);
gl.viewport(0, 0, gl.canvas.width, gl.canvas.height);
gl.useProgram(this.rendererPixi.shaderManager.currentShader.program);
this.rendererPixi.plugins.sprite.start();
```

**Comment by brunosimon** [comment]
I'm a little lost.
Does this mean that I have to use the same **WebGLRenderingContext** for both PixiJS and THREE.js but before the THREE.js render, I have to do a **resetGLState** and before the PixiJS render, I have to do your code ?

Do you have a more advanced example ?

Thanks for the help.

**Comment by brunosimon** [comment]
Currently, I'm rendering the THREE.js on another canvas and I'm using a **PIXI.Texture.fromCanvas** to create a texture from that canvas. On every frame, I'm doing the THREE.js then calling **update()** on the canvas texture.

It works well on Chrome at 60 fps but it's dropping badly on every other browsers.

**Comment by JiDW** [comment]
Well, I'm sure it exists a lot of ways to do this. In our case, we wanted to use the same canvas, so we used the same context, yes. If you can use two canvas, then just set a transparent background on PIXI canvas and use CSS to set one on top of the other.

This is what we did with it (i took a screenshot from our googleplay store, sorry for this): https://lh3.googleusercontent.com/UOu6g3XPjZQOanQXd2z2CnuMaFg1t8ikZdhtuO7kExKn-vF_LI33770fqRgYO_Z3Qw=h900-rw

The UI is PIXI, and the world is in 3d.

**Comment by brunosimon** [comment]
It won't work, I have to convert it to a PixiJS texture so I can use it at multiple places and apply things on it.
But thanks for the help, I'll try to use the same canvas and maybe it will solve the framerate issue on other browsers.

**Comment by vlucendo** [comment]
Create an sprite from the threejs canvas (can be stored in memory) like:

´´´js
const sprite3d = new PIXI.Sprite(PIXI.Texture.fromCanvas(threejsCanvas));
´´´

and call the update() method of its texture on every frame.

**Comment by vlucendo** [comment]
Sorry, I previously posted a comment answering the initial question without checking any other comments.

My project also needs the theejs texture to be used with PIXI and we're facing the same fps issue on browsers other than chrome. I haven't found a way to solve this, but looking at the developer tool seems like the bottleneck is the browser proccess that handles the texture copying so I really doubt there's anything we can do about it.

**Comment by JiDW** [comment]
Yes, creating a texture at every frame is really bad performance wise, that's why we did the pipeline I mentioned with Threejs using the same gl context as pixi.

**Comment by Icemic** [comment]
I have had a similar problem ever.

No matter you want to use three.js in pixi.js, or something else in pixi.js, it's sure that you should insert three.js(or something else)'s draw loop into pixi.js's draw loop.

I've made a plugin to use Live2D(written in native webgl) in pixi.js, it's quite similar to your problem.

Maybe you can refer to https://github.com/avgjs/pixi-live2d/blob/master/src/index.js (especially `_renderWebGL` method)

**Comment by themoonrat** [comment]
@brunosimon do you have enough information to help with your question? If so we can close this down :)

**Comment by brunosimon** [comment]
I couldn't make it work yet but I know now that it's possible and I juste need to try more. 
So yes, you can close it.

Many thanks
