### ISSUE TITLE
Problem with textures in filters since 4.2.1

### ISSUE THREAD

**Issue by vlucendo** [pixijs/pixi.js#3346]
Hello,

I have a filter that takes a texture as a uniform and uses it as a sampler2D in the fragment shader. This texture gets updated every frame.

The filter was working nicely in v4.1.1, since v4.2.1 the texture appears all black or as a mosaic of random colors. If I use a static texture which doesn't get updated then it works as expected.

What can be causing this? I've seen 4.2.1 introduced some changes in texture cacheing, should I tell the filter to update the texture on every frame or something similar?

Thanks.

**Comment by GoodBoyDigital** [comment]
Hi there! Can you try version 4.2.2?

If the issue still persists,  fiddle / example of the issue would be ace!

thanks!

**Comment by vlucendo** [comment]
Hello, sure.

This jfiddle is using PIXI v4.1.1: https://jsfiddle.net/nu2k4txr/7/
This is the same code using v4.2.2: https://jsfiddle.net/nu2k4txr/8/

It is late so I hope I'm not making any mistakes.. As you can see the texture is not visible with the latest version.

Thanks.

**Comment by vlucendo** [comment]
Oh, and if you comment the texture.update() on the 4.2.2 version and rerun the fiddle, it works as expected.

**Comment by warlockuk** [comment]
I have a similar problem in 4.2.2; I have a series of MovieClips (now called AnimatedSprite) which get reused (and their textures set) which no longer show anything.

There's a filter on top of them for clicking; maybe they're breaking it.

**Comment by GoodBoyDigital** [comment]
Hello! This is fixed in the latest version, https://jsfiddle.net/sjp2f43g/
Cheers!
