### ISSUE TITLE
Canvas+/PIXI.js v4 - Images disappear when app resumes from background

### ISSUE THREAD

**Issue by bltizoo** [pixijs/pixi.js#3347]
* **Pixi/Cocoon Version**: 

Latest Cocoon Dev app, Canvas+ and PIXI v4.1.1

* **Basic description of the problem**: 

Some app images disappear when app is placed in background by navigating to another app or device's home screen and then resumed from background. Looks like a classical "context lost" case (texture objects are there although there is nothing rendered on the screen) however no "webglcontextlost" event get's dispatched by the canvas instance.
The app is rendered with Canvas+ engine and runs on top of latest PIXI.js v4.1.1
NOTE:
Switching back to PIXI.js v3 solves the problem.
When using WebView+ engine, regardless of the PIXI version, the issue does NOT exists.

* **Device info**: 

Tested on following devices:

Samsung Galaxy S7 Edge with Android 6.0.1
Samsung Galaxy Tab A with Android 6.0.1

iPhone 5 with iOS 9.3.1
iPhone 6 with iOS 9.1

* **Steps will reproduce the problem**: 

1. Launch Cocoon Dev app.
2. Load the "test_case" app provided using Canvas+.
3. Wait for 5-10 seconds after all animations has completed.
4. Navigate to devices's home screen by pressing it's home button. Let the app go to background, don't kill it.
5. Wait for 5-10 secs and resume the app by pressing it's icon or through device's quick access menu.
6. Notice some images are missing.

REPO RATE: The issue occurs frequently on Android devices but it's harder to replicate it on iOS devices, although it happens there too.
NOTE: When having more apps running at the same time like Camera, Photo gallery or a game the issue becomes more easily reproducible.

* **Expected result**: 

No images to disappear when app is resumed from background.

* **Error log**

Android:
[https://www.dropbox.com/s/rlyy48y7gr619l7/error_log.txt?dl=0](https://www.dropbox.com/s/rlyy48y7gr619l7/error_log.txt?dl=0)

* **Testcase**: 

Download the test case from following link:
[https://www.dropbox.com/s/4bu0n44azzqpfvv/test_case.zip?dl=0](https://www.dropbox.com/s/4bu0n44azzqpfvv/test_case.zip?dl=0)

* **Webview engine(s)**: 

Canvas+ engine is used to replicate the issue.
When app runs using WebView+ engine the issue does NOT exists.

* **Used plugins (if relevant)**: 

Default Cocoon Dev app is used without any tweaks.

* **Framework/game engine (if relevant)**: 

PIXI.js v4.* - is where the issue occurs.
PIXI.js v3.* - no issue with this pixi version.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
