### ISSUE TITLE
Slabo 27px Not Rendering

### ISSUE THREAD

**Issue by ClickSimply** [pixijs/pixi.js#3349]
Hey  Guys,

I've ran into an odd issue, PixiJS won't render the Google Font "Slabo 27px".  Doesn't make any sense why this would be the case but it is.  I threw together a codepen:

http://codepen.io/clicksimply/pen/vymRZM

For some reason the font is always shown at like 2px size Arial, even though the browser is rendering it fine.  I am also using WebFont loader to make sure the fonts are available before painting them to the canvas.

**Comment by bigtimebuddy** [comment]
Ahh. I think I see what's going on here. We are neglecting to put quotes around the fontFamily when the text style string is generated for Canvas. Should be an easy fix.
