### ISSUE TITLE
[BUG] About CanvasRenderTarget.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3350]
```js
/**
 * Creates a little colored canvas
 *
 * @ignore
 * @param {number} color - The color to make the canvas
 * @return {canvas} a small canvas element
 */
function createColoredCanvas(color) {
    var canvas = document.createElement('canvas');

    canvas.width = 6;
    canvas.height = 1;

    var context = canvas.getContext('2d');

    context.fillStyle = color;
    context.fillRect(0, 0, 6, 1);

    return canvas;
}
```
the color must be converted from number to hex string.

**Comment by bigtimebuddy** [comment]
You can try using `PIXI.utils.hex2string` to convert the color into a hex string.

```js
context.fillStyle = PIXI.utils.hex2string(color);
```

**Comment by finscn** [comment]
@bigtimebuddy  , I know how to do that 
 but  in  annotation , It says "@param {number} color" , so I think it's a bug in PIXI.js

**Comment by bigtimebuddy** [comment]
Ah, I see. That does need updating. Do you want to make a pull request for that?

**Comment by finscn** [comment]
I don't know how to do .  change the doc or change the code ？

**Comment by bigtimebuddy** [comment]
My preference is to change the docs to say string. Do you know how to create a pull request?

**Comment by finscn** [comment]
I know, But my english is very very weak . 
I'm afraid a bad comment of PR will break the purity of PIXI.

**Comment by bigtimebuddy** [comment]
No problem. Thanks for all your comments recently and for helping to make Pixi better.

**Comment by chrispwns** [comment]
This is just a documentation change? I could probably do that and get a pr in on it pretty fast.
