### ISSUE TITLE
Mp4 video texture scale down in height when start playing in chrome.

### ISSUE THREAD

**Issue by harrisyu** [pixijs/pixi.js#3351]
Problem with mp4 on Chrome ( webm and firefox both work fine)
1.video texture scale down 8 pixel when put on stage.
2.video texture scale down more 8 pixel when start playing, this is different from v3.
Demonstrate : http://retrodaddy.net/store/PixiV4ChromeMp4Problem/PixiV4.html

**Comment by themoonrat** [comment]
Love the demo! But I'm not seeing a change on my Chrome, despite expectantly watching the bottom edge! Could you supply a screenshot please that shows the before and after?

**Comment by harrisyu** [comment]
![mp4-problem](https://cloud.githubusercontent.com/assets/4844464/20782731/84fa4248-b7c9-11e6-818f-7caec25ea312.jpg)
It's like this, now I going to update my chrome to test it again.

**Comment by FlorianLudwig** [comment]
@harrisyu the link to the example doesn't work for me anymore, is it gone?

**Comment by englercj** [comment]
Hey @harrisyu is this still an issue? Looks like the demo is gone, if it is still active can you make a new demo for us to debug?

Thanks!

**Comment by themoonrat** [comment]
@harrisyu Going to close due to inactivity - if this is still an issue please re-open with those demos back up using the latest pixi. Thanks!
