### ISSUE TITLE
Updating frame properties inconsistent behaviour canvas and webGL

### ISSUE THREAD

**Issue by markknol** [pixijs/pixi.js#3354]
This line of code behaves different in canvas and webGL:

```js
var texture = Texture.fromImage("myimage.jpg");
texture.frame = new Rectangle(0,0, 100, 100);

setInterval(function() {
   texture.frame.x += 10;
}, 1000);
```
In canvas the frame is actually updated, in webGL it isn't.
To make it work in webGL you seem to need a new Rectangle instance:

```js
var texture = Texture.fromImage("myimage.jpg");
texture.frame = new Rectangle(0,0, 100, 100);

setInterval(function() {
   texture.frame.x += 10;
   texture.frame = texture.frame.clone(); // needed in webGL
}, 1000);
```
It would be nice if this was consistent on both renderers.

Info:
 * pixi.js - v4.1.0
 * Compiled Wed Oct 19 2016 06:39:33 GMT+0000 (UTC)

**Comment by bigtimebuddy** [comment]
Could you confirm this is still an issue in the latest 4.2.2 release?

**Comment by themoonrat** [comment]
Hi @markknol - is this something you could confirm is in the latest release please?

**Comment by markknol** [comment]
Happy 2017! I haven't got time to migrate to a newer version so I cannot say it is resolved.

**Comment by staff0rd** [comment]
Still apparent in latest; https://codepen.io/staff0rd/pen/PWYXXZ?editors=0010

**Comment by englercj** [comment]
You don't need a new rectange instance, but you do need to run the `frame` setter right now. You can do:

```js
texture.frame.x += 10;
texture.frame = texture.frame; // needed in webGL
```

Obviously this isn't ideal, and should be fixed. But it is a more GC-friendly workaround.
