### ISSUE TITLE
WebGL refuses rendering in large stages

### ISSUE THREAD

**Issue by mielvds** [pixijs/pixi.js#3355]
I'm experimenting with pixi.js for large surface rendering. There seems to be a difference between WebGL and Canvas in this respect. The WebGL renderer refuses to render at certain sizes.

Small size:
http://codepen.io/mielvds/pen/qqjjQJ

Big size:
http://codepen.io/mielvds/pen/ZByyry

What am I doing wrong? A setting? Or a bug?

**Comment by ivanpopelyshev** [comment]
What device are you testing on? Look at http://webglreport.com/, for my laptop max framebuffer size is 16k.

**Comment by mielvds** [comment]
I guess that's it indeed, I guess I expected a proper error. I'm running this on a recent chrome on macbook pro. 

WebGL report: 

Framebuffer
Max Color Buffers:	8
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	16384
Max Viewport Dimensions:	[16384, 16384]

**Comment by mielvds** [comment]
@ivanpopelyshev this doesn't explain why the example is working for you though...

**Comment by GoodBoyDigital** [comment]
Hi there! This seems like a GPU issue rather than a pixi one. Closing for now.
