### ISSUE TITLE
Pixi 4.2.2 cacheAsBitmap shifts container in Canvas renderer

### ISSUE THREAD

**Issue by FFankias** [pixijs/pixi.js#3356]
I have container full of sprites, for performance set  container.cacheAsBitmap = true;
WebGl renderer works fine, but with in Canvas container being shifted.

**Comment by valtver** [comment]
Hi,

Got the same issue.
Reason is that rendered texture with old transformation is cut by renderer. So, _skipUpdateTransform_ .
**pixi.js/src/extras/cacheAsBitmap.js**
#_`Line 249:         renderer.render(this, renderTexture, true, m, false);`_
**`Line 249:         renderer.render(this, renderTexture, true, m, true);`**

**Comment by valtver** [comment]
Sorry, wrong one...

286:  m.tx -= bounds.x;
 287   m.ty -= bounds.y;

to

 **286:  m.tx = -bounds.x;
 287   m.ty = -bounds.y;**

**Comment by sivael** [comment]
This will not fix the issue, it will simply change where it appears.
I've created a PR #3494 for this.

**Comment by GoodBoyDigital** [comment]
Looks all good here!

**Comment by brenwell** [comment]
I have the same bug

**Comment by brenwell** [comment]
I have a way to small reproducible version if you need it

**Comment by GoodBoyDigital** [comment]
@brenwell yes please!

**Comment by brenwell** [comment]
sure 1 second

**Comment by brenwell** [comment]
This seems to highlight the issue for me

PIXI v4 + CanvasRender + PixelRatio > 1 + CacheAsBitmap = a strange rendering in regard to position. Change the 2 `const` to see the difference

https://jsfiddle.net/brenwell/krok0es6/5/

**Comment by GoodBoyDigital** [comment]
perfect! this will definitely speed up the bug hunting! :D

**Comment by themoonrat** [comment]
That fiddle is not using the latest version. Change it to 4.3.1 or above and you can see that the issue is fixed :)

**Comment by brenwell** [comment]
Yep it 4.3.1+ looks good, thanks guys. Sorry for the run-around

**Comment by bigtimebuddy** [comment]
@brenwell thank _you_ for wanting to make PixiJS better!
