### ISSUE TITLE
How to do something like "#pragma glslify: import()" in PIXI v4

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3358]
In v4, the  glslify & glslify-import are removed ,  How to do something like "#pragma glslify: import()" now ?

Thanks

**Comment by finscn** [comment]
When I do some extensions ， glslify is very  useful ，`readFileSync` couldn't replace `glslify`.
I hope you could take glslify back.

**Comment by bigtimebuddy** [comment]
Removing glslify fixed issues related to devs using webpack.

**Comment by GoodBoyDigital** [comment]
yip, no glslify here im afraid! 

```readFileSync(join(__dirname, './myShader.vert'), 'utf8');``` 

Is what we use as its more compatible for most users. glslify  is cool though, we use it in your own build process 👍
