### ISSUE TITLE
[Share] My extension of PIXI  for Lighting.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3360]
My extension is  inspired by https://github.com/pixijs/pixi-lights.
But it's not simple port of old pixi-lights,  it's re-designed.

The differences : 

* Better performance (just a bit little)
* A new renderer named ```LightSpriteRenderer```, don't change WebGLRenderer & SpriteRenderer
* Light is not the subclass of DisplayObject, it's just a normal Class.
* attribute ```lights``` on sprite, don't need to add a light object to the stage/container. Now, you could set different lights on different sprites in the same stage.
* AmbientLight is not necessary, you could use  ambientColor and ambientLight on PointLight and DirectionalLight. But just use on the first light of ```lights``` please.
* support non-light-sprites  in correct rendering order. (the old pixi-lights always render non-light sprite on the top).
* use pluginName for using LightSpriteRenderer ( see #3330 )
* add an important feature of pixi-gl-core ( see  https://github.com/pixijs/pixi-gl-core/pull/18 )
* DO NOT support Container . Please use LightSpriteRenderer on standalone Sprite with normalTexture.
* ... others...

My english is very poor , so , the example is better than my words  : 
http://fattyboy.cn/pixi-lights-v4/

the key files of this feature in my fork version at  : 
~~https://github.com/finscn/pixi.js/tree/master/src/extension/light~~
[update: new url] : https://github.com/finscn/pixi.js/tree/master/src/extensions/renderers/light

### Why don't use  Deferred Lightning ?
I found that  Deferred Lightning in 2D game with WebGL  won’t help for performance  in most cases.

BTW, 
I've stopped to develop Light Filter.
If want to implement it ，I have to create a new subclass of Sprite for render normalTexture. That's so complex.

**Comment by finscn** [comment]
I can't pull a PR , because I changed some codes in PIXI.js , see : 

https://github.com/pixijs/pixi-gl-core/pull/18
https://github.com/pixijs/pixi.js/issues/3330
https://github.com/pixijs/pixi.js/issues/3217
https://github.com/pixijs/pixi.js/issues/3225
https://github.com/pixijs/pixi.js/issues/3268
https://github.com/pixijs/pixi.js/issues/3358
https://github.com/pixijs/pixi.js/issues/3229


And 
https://github.com/pixijs/pixi.js/issues/3362

**Comment by staff0rd** [comment]
Looks impressive @finscn, I look forward to @englercj's response on this.

**Comment by kaansoral** [comment]
Indeed, so very impressive, looking forward to using it :)

**Comment by Jorisslagter** [comment]
Interesting! Looking forward to play with your plugin.

**Comment by yhwh** [comment]
I'm following this with interest and noticed some tickets resolved and a pr for gl-core pending https://github.com/pixijs/pixi-gl-core/pull/22
I was wondering @finscn if you closed this issue, because you're planning to make a pr or if you just don't have the time to do it ? (Because in case 2 I may have some time off to help for this)

**Comment by finscn** [comment]
I think this feature is not a core function of PIXI.js , so I closed it.  

I hope pixijs team  could create  a new repo ( e.g. named  pixi-extensions) for developers to commit various filters , renderers  etc.  ( cc @GoodBoyDigital  @bigtimebuddy  @staff0rd )

**Comment by Dynasty9** [comment]
This is really cool, I'm going to integrate this into my project and contribute if I can 👍

**Comment by finscn** [comment]
Hi guys   , now support deferred-lighting .  
When pixi support `gl. bindAttribLocation` , I will open a PR for this feature.

  @GoodBoyDigital  ,  when will pixi support  `gl. bindAttribLocation` ?

**Comment by ivanpopelyshev** [comment]
Im gonna race you with my pixi-layers :)

**Comment by finscn** [comment]
pixi-layers is an amazing feature  , I couldn’t wait for it.

**Comment by TarVK** [comment]
I really want to use this project, but neither of your links for the source work.
I found the minimized version of the code through your demo, but would like to try and tweak some things, as I have some issues. Is there any place I can still find the code?

**Comment by finscn** [comment]
@TarVK   the source code  in My fork version https://github.com/finscn/pixi.js

**Comment by Richacinas** [comment]
I'm not being able to find it on that link you provide... What file is it exactly? And how could we use it as in your example?

**Comment by ivanpopelyshev** [comment]
@finscn @prachtan Its done. http://pixijs.io/examples/#/layers/normals.js
