### ISSUE TITLE
How to create standalone plugin or extention of new version PIXI.js

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3362]
Before PIXI.js use ES6 , I know how to do it.
But in ES6 version , I'm lost.

Is there an example under ES6 ?  I found the pixijs official standalone plugins are all under ES5.

**Comment by englercj** [comment]
Not sure I understand, nothing has changed about writting plugins because the library is written in ES6 now. What issue are you having?

**Comment by finscn** [comment]
If My plugin also want be write in ES6 ,
 I don't know how to import some module in pixi.js and build by babel , and how to write build/lint/dist scripts.

**Comment by ivanpopelyshev** [comment]
pixi-plugin-example works with pixify, right? just add babelify there, add it as a transform in package.json and it'll work just fine. Please see pixi.js package.json

**Comment by englercj** [comment]
Closing as answered.
