### ISSUE TITLE
The link to pixi.min.js is dead in the Learning Pixi doc.

### ISSUE THREAD

**Issue by chrispwns** [pixijs/pixi.js#3364]
Might want to update that link because as of now it takes you to this 404: https://github.com/pixijs/pixi.js/tree/master/bin

**Comment by bigtimebuddy** [comment]
Hey @chrispwns, I assume you are talking about: https://github.com/kittykatattack/learningPixi?

You should [file an issue](https://github.com/kittykatattack/learningPixi/issues/new) with that repository, the Pixi team does not maintain it.

**Comment by chrispwns** [comment]
You were right, I went ahead and submitted a pull request over there to hopefully fix the link.

**Comment by bigtimebuddy** [comment]
Thanks @chrispwns
