### ISSUE TITLE
It is not possible to install pixi from github using npm+package.json

### ISSUE THREAD

**Issue by ggarek** [pixijs/pixi.js#3365]
Now it is not possible to install pixi.js from github rather than npm registry. Currently if you add
```json
  "dependencies": {
    "pixi.js": "pixijs/pixi.js",
  }
```
and try to `npm i` you will end up with pixi.js installed from github, but...
```
 % ls -nl node_modules/pixi.js                                                                                                      
total 72
-rw-r--r--  1 501  20   4066 Nov 26 22:36 CONTRIBUTING.md
-rw-r--r--  1 501  20   1093 Nov 26 22:36 LICENSE
-rw-r--r--  1 501  20   9488 Nov 26 22:36 README.md
-rw-r--r--  1 501  20  14740 Nov 26 22:36 package.json
```

As you can see, there is nothing in there. Because `package.json` said that.

One possible solution would be to modify `package.json` like this: add `./src` to `files` and modify `main` property to point to `src/index.js`. *But it will break the published package, since the main file for the published version is `./lib/index.js`.*
```json
"main": "./src/index.js",
"files": [
    "src/",
    "dist/",
    "lib/",
    "CONTRIBUTING.md",
    "LICENSE",
    "package.json",
    "README.md"
  ],
```

----
Since there are many possible solutions to make it work, it depends on the team view point, so i do not provide a PR. But i can do it, if you see how it should work for you.

Why one may need it?
So, for example, i found a bug, forked the repo, fixed the bug and since i work on a project which can not wait for a PR approvement i need to go on while waiting for PR. So i modify my `package.json` to pull pixi from my fork and now i am no longer blocked by an issue. 
It is just what happend to me, and the reason why i began to investigate the issue in the first place. =)

**Comment by bigtimebuddy** [comment]
This is correct. We no longer check-in the built files to Github and we have excluded the source files (since 4.1.0) from publishing (now they are written in ES6). If you want to install directly from Github using npm, your only option is to use the **release** branch. 

```json
"dependencies": {
  "pixi.js": "pixijs/pixi.js#release",
}
```

You might want to check out the [FAQ](https://github.com/pixijs/pixi.js/wiki/FAQs) for more information about consuming builds from different branches via URL.

Hope that helps.

**Comment by ggarek** [comment]
Oh, i see. Now it clear, there is a branch for each release, which contains built sources. This makes sense.

Thank you @bigtimebuddy for pointing that out, i could check this first and not bother you. So please accept my apologies!
*So there is no issue, it can be closed.*

**Comment by bigtimebuddy** [comment]
No worries. Thanks for helping to make Pixi better. We appreciate it!
