### ISSUE TITLE
Broken link in documentation 

### ISSUE THREAD

**Issue by vipyne** [pixijs/pixi.js#3368]
[This link](https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/canvas/CanvasGraphicsRenderer.js#L13) seems to be broken.

A cursory search of the libgdx repo for `CanvasGraphicsRenderer.java` did not find any matches.

**Comment by bigtimebuddy** [comment]
The only thing that seems to make sense here is probably the [ShapeRenderer](https://github.com/libgdx/libgdx/blob/1.0.0/gdx/src/com/badlogic/gdx/graphics/glutils/ShapeRenderer.java). Seems more plausible. We should probably confirm with @GoodBoyDigital

**Comment by vipyne** [comment]
Thanks.  `ShapeRenderer` is a great resource in the meantime.

**Comment by GoodBoyDigital** [comment]
updated!

**Comment by GoodBoyDigital** [comment]
Ding! Done 👍
