### ISSUE TITLE
Web GL Warning in Chrome, when generateTexture on certain shape "WebGL: INVALID_VALUE: texSubImage2D: no pixels"

### ISSUE THREAD

**Issue by rich-earth** [pixijs/pixi.js#3372]
Quite niche...   I'm drawing some arc shapes with a Graphic to use in a pie chart.  When I generate a Texture from the Graphic, (WebGLRenderer.generateTexture) from this shape I get a WebGL warning in Chrome.  It still works,  but I'm just wondering whats going on and if its a problem. On a normal circle no problem, but on a drawn arc section I get a warning in the console.
"WebGL: INVALID_VALUE: texSubImage2D: no pixels"

Could be another drawing with arcs issue #3343

Fiddle:
https://jsfiddle.net/g4xcjxvp/3/

**Comment by Ziao** [comment]
Old, I know. But getting the same result.

```js
let grid = new PIXI.Graphics( false );
//do some lineTo'ing
let gridTexture = PIXI.RenderTexture.create( 128, 128 );
pixiApp.renderer.render( grid, gridTexture );
```

**Comment by themoonrat** [comment]
Confirmed this still occurs on latest (4.8.0) PIXI - https://jsfiddle.net/g4xcjxvp/7/

**Comment by rich-earth** [comment]
Not occurring anymore for me in Chrome beta 68.0!
Still occurs in Safari 11.1

Seems like a bug when you use generateTexture with a small graphic, or not Po2
In this example, draw a square 100x100 and generateTexture from it, you get a warning in Safari, draw a bigger square thats is po2 and you don't get the warning.
https://jsfiddle.net/hv7nz265/11/

Warning in Safari
GLTexture.uploadData:
`[Error] WebGL: INVALID_VALUE: texSubImage2D: no pixels
	texSubImage2D
	uploadData (pixi.js:2439)
	resize (pixi.js:2103)
	resize (pixi.js:20606)
	RenderTarget (pixi.js:20476)
	updateTexture (pixi.js:17333)
	bindRenderTexture (pixi.js:17980)
	render (pixi.js:17838)
	generateTexture (pixi.js:16210)
	onload (show:46)`

**Comment by ivanpopelyshev** [comment]
yep. looks like a bug.

**Comment by eranimo** [comment]
Still happening in Chrome 69
