### ISSUE TITLE
null target and currentTarget on touch event

### ISSUE THREAD

**Issue by akhnaz** [pixijs/pixi.js#3377]
hello,

i am migrating from pixi v3 to pixi v4. Previously, listening to 'touchstart' event, we can get the target from the eventData object. 

Here is the code in jsbin:
https://jsbin.com/koyicariwu/edit?output

The problem does not exist on 'mousedown' event, only 'touchstart'.

In v4, how can i get the correct target again?

**Comment by staff0rd** [comment]
Hi @akhnaz, can you please give some more information, like what device you are finding this on?  I just tested your jsbin and am getting the expected response from both mousedown and touchstart.  What response are you getting?

~~~
InteractionEvent {stopped: false, target: Sprite, currentTarget: Sprite, type: "mousedown", data: InteractionData}
InteractionEvent {stopped: false, target: Sprite, currentTarget: Sprite, type: "touchstart", data: InteractionData}
~~~

**Comment by akhnaz** [comment]
I am using Chrome Ver 54 (64 bit) on linux Mint. 

If u see the console log without further navigation on the log, you will get 
`InteractionEvent {stopped: false, target: Sprite, currentTarget: Sprite, type: "touchstart", data: InteractionData}`. 

**But**, when u click `>` button on the log to further checking, you can see that the target and currentTarget is now `null`.

```
InteractionEvent
     currentTarget: null
     data:InteractionData
          global:Point
          identifier:0
          originalEvent:TouchEvent
          target:null
          __proto__:Object
     stopped:false
     target:null
     type:"tap"
     __proto__:Object
```

**Comment by akhnaz** [comment]
hmm, i think this issue can't reproduce and can be close. I made changes to the jsbin code to check again the 'target', but now it correctly return the sprite:
`Sprite {_events: Events, _eventsCount: 2, tempDisplayObjectParent: null, transform: TransformStatic, alpha: 1…}`
```
function onDown (eventData) {
    console.log(eventData.type);
    console.log(eventData.target);
    sprite.scale.x += 0.3;
    sprite.scale.y += 0.3;
}
```

**Comment by macguffin** [comment]
Hi @akhnaz did you try it in the chrome emulator (iPhone)?
I did and saw that the target is null. It seems to work fine with mousedown, touchstart seems to be the issue.

I've noticed the same coming from 4.2.3 to 4.3

**Comment by akhnaz** [comment]
I did try it with chrome emulator (iphone etc) but can't reproduce it now (at the time i write the jsbin, it is return null). It also not working on my ipad (real ipad) for my project, so i implement a workaround for it.

**Comment by macguffin** [comment]
Hi @akhnaz I was also see seeing null but it was not consistent.
Just has another look and think I see something:

```
sprite.on('mousedown', onDown);
function onDown (eventData) {
    console.log(eventData)
}

```

You are trying to get the info from 'eventData'

have you tried 
```
function onDown (eventData) {
    console.log(this)
}
```
this worked for me. If you change you fiddle to the code below you can see that I called the sprite 'FOO' and requesting this.name returns 'FOO'

```
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});

document.body.appendChild(renderer.view);
// create the root of the scene graph

var stage = new PIXI.Container();
var sprite = PIXI.Sprite.fromImage('https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Emmanuel_College_Front_Court%2C_Cambridge%2C_UK_-_Diliff.jpg/400px-Emmanuel_College_Front_Court%2C_Cambridge%2C_UK_-_Diliff.jpg');
sprite.position.set(230,264);
sprite.name='FOO'

sprite.interactive = true;
sprite.on('mousedown', onDown);
sprite.on('touchstart', onDown);
stage.addChild(sprite);

function onDown (eventData) {
  
    console.log(this.name)
    sprite.scale.x += 0.3;
    sprite.scale.y += 0.3;
}
// start animating
animate();
function animate() {
    requestAnimationFrame(animate);
    // render the root container
    renderer.render(stage);
}
```

**Comment by akhnaz** [comment]
Hi @macguffin Yes, it is not consistent (now i cannot reproduce it anymore) and when i get the error on my code so i need to find workaround.

Using this keyword for above example is ok but not when 'this' keyword will refer to other class. So, 
getting the `currentTarget` and `target` is very important from the event emitted. 

Below is the example of `this` can't be use to get the `currentTarget`.

```js
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);

class Example {
  stage;
  sprite;
  
  constructor() {
    // create the root of the scene graph
    this.stage = new PIXI.Container();
    this.sprite = PIXI.Sprite.fromImage('https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Emmanuel_College_Front_Court%2C_Cambridge%2C_UK_-_Diliff.jpg/400px-Emmanuel_College_Front_Court%2C_Cambridge%2C_UK_-_Diliff.jpg');
    this.sprite.position.set(230,264);
    this.sprite.interactive = true;
    this.sprite.on('mousedown', this.onDown);
    this.sprite.on('touchstart', this.onDown);
    this.sprite.name = 'foo'
    this.stage.addChild(this.sprite);
    this.animate();  
  }

  onDown = (eventData) => {
    console.log(this.name); //this.name will return undefined
    //instead of 'foo' because 'this' keyword used in fat arrow 
    //function will refer to class Example.
    this.sprite.scale.x += 0.3;
    this.sprite.scale.y += 0.3;
  }

  // start animating
  animate = () => {
    requestAnimationFrame(this.animate);
    // render the root container
    renderer.render(this.stage);
  }

}

new Example();
```
See https://jsbin.com/nujosijiqe/1/edit?js,output for live example of the above script.

**Comment by macguffin** [comment]
if you are using => as in your example you could simply 

` console.log(this.sprite.name);`

you will then get 'FOO' again
:)

**Comment by akhnaz** [comment]
yes, the example is simple , and i get it from pixi example with modification

**Comment by lcd11001** [comment]
@akhnaz if you want to use arrow function 

```
onDown = (eventData) => {
    console.log(this.name); //this.name will return undefined
    console.log(eventData.target.name); // will return the sprite's name is clicked
}
```
