### ISSUE TITLE
Using @2X instead of @2x makes the spritesheet load incorrectly

### ISSUE THREAD

**Issue by pypmannetjies** [pixijs/pixi.js#3378]
Hi,

I have found some problems with naming resulting in a spritesheet loading incorrectly. 

If you have named your files @2x, but the .json references the file as @2X, the scaling fails and the sprites become cut off. 

Example JSON meta:

`"meta": {
        "image": "GenericArt@2X.png",
        "format": "RGBA8888",
        "size": {
            "w": 2048,
            "h": 2048
        },
        "scale": 1
    }`

This will scale incorrectly and cut off the artwork. 

This problem is present in version 4.2.2

**Comment by themoonrat** [comment]
Hi @pypmannetjies.

You are free to change the regex that looks for the resolution in an image name via PIXI.settings.RETINA_PREFIX
Documented @ http://pixijs.download/v4.2.2/docs/PIXI.settings.html#.RETINA_PREFIX

Changing it to
`PIXI.settings.RETINA_PREFIX = /@(.+)x/i`
Makes is case insensitive

We could make this the default for future releases if others feel it's worthwhile.

**Comment by pypmannetjies** [comment]
Thanks, I didn't know about this setting. I think it would be worthwhile to make it the default. It was difficult to find the cause of the problem, because all you can see was is bizarre collection of incorrectly cropped sprites.

**Comment by themoonrat** [comment]
@GoodBoyDigital  could I have some guidance please on whether we leave this as it is, ie. only 2x, 3x etc. work, or whether I should change the regex to also accept 2X, 3X etc.
I'm tempted to just leave as it is, because the user can always change this via the PIXI.settings.RETINA_PREFIX .....

**Comment by GoodBoyDigital** [comment]
Hi @themoonrat , I would leave this as is. @pypmannetjies you can set the prefix to whatever you need using ```PIXI.settings.RETINA_PREFIX``` . Hope that helps! 

Cheers
