### ISSUE TITLE
When i set sprite is width != height,the graphics.drawCircle will draw a ellipse

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#3383]
Hi:
i create a sprite,sprite.width != sprite.height,and i want draw a circle in sprite,but it only draw a ellipse;
the jsfiddle link : https://jsfiddle.net/of6rnar7/;
the code below:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
    </style>
    <script src="//cdn.bootcss.com/pixi.js/4.2.2/pixi.min.js" ></script>
</head>
<body>

<script>
    stage = new PIXI.Container();
    renderer = PIXI.autoDetectRenderer(window.innerWidth,window.innerHeight,{antialias:true,resolution:1},true);
    document.body.appendChild(renderer.view);
    requestAnimationFrame(update);

    var sp = new PIXI.Sprite();
    sp.position.x = 100;
    sp.position.y = 100;
    sp.width = 200;
    sp.height = 50;
    stage.addChild(sp);

    var g = new PIXI.Graphics();
    g.beginFill(0xFFFFFF);
    g.drawCircle(.5,.5,.5);
    g.endFill();
    sp.addChild(g);

    function update(){
        renderer.render(stage);
        requestAnimationFrame(update);
    }
</script>
</body>
</html>

Thank!

**Comment by Icemic** [comment]
```
width

The width of the sprite, setting this will actually modify the scale to achieve the value set
```

**modify the scale**

**Comment by fengFanYong** [comment]
but i need draw a circle in sprite,what am i to do?

**Comment by Icemic** [comment]
If you want to display a circle in a sprite, but not want it scaled with its parent.

Solution A: Move the Graphics out of the sprite.
Solution B: Scale the circle, keep the product of the scale ratio of sprite and circle  be 1.

**Comment by fengFanYong** [comment]
this is the sticks,if i want to display text in a sprite,i am only scale the text,and have to get sprite Actual width and height

**Comment by staff0rd** [comment]
Hi @fengFanYong, just a heads up that you can save yourself a bit of code in fiddles by putting the reference to pixi.js in _External Resources_.  Then you can just dump all your javascript in the _Javascript_ pane.  Here's your original fiddle, but with pixi.js in _External Resources_; https://jsfiddle.net/mawbL4zz/

Considering you know that setting the width and height directly on a sprite (or any PIXI.Container) means you're actually setting scale, you could instead put the sprite in a non-scaled container of its own, scale the sprite, and then just add your Graphics object to the non-scaled, parent container.  How does that sound?

**Comment by fengFanYong** [comment]
Thank @staff0rd ,but i do not know your meas,can your give me a demo?

**Comment by staff0rd** [comment]
Sure, here you go; https://jsfiddle.net/d2bLbtob/

Note that I've just added a container to the stage, then I just stick both the scaled sprite, and the graphics object inside that container.

**Comment by fengFanYong** [comment]
@staff0rd,but i want draw circle in a sprite,so i can not move the graphics oup of the sprite,

**Comment by staff0rd** [comment]
The sprite is a container, so if you scale it, all of it's children will be scaled also.  Why does the circle have to be inside the sprite?

**Comment by fengFanYong** [comment]
because Layout is like this,the parent is a sprite,set it is width and height,and it childrens only set Percentage of parent

**Comment by staff0rd** [comment]
Understood, but if you put the sprite in a container, that container will automatically have the width/height of the sprite, so you can use the container, rather than the sprite, for layout purposes.  Additionally you can add the graphics to the object to it, which will ensure the graphic object is not affected by the modifications you're making to the sprite.

**Comment by fengFanYong** [comment]
Thank,i Understood.When i want to draw a circle,and shoule add it to container,just use sprite more easies.
thank you!
