### ISSUE TITLE
PIXI.Text wordWrap not work when the text is Chinese

### ISSUE THREAD

**Issue by hantaogo** [pixijs/pixi.js#3384]
wordWrap not work when the text is Chinese
`
var style = {
                    fontFamily : 'Microsoft YaHei',
                    fontSize : '12px',
                    fontStyle : 'normal',
                    fontWeight : 'bold',
                    fill : '#F7EDCA',
                    stroke : '#4a1850',
                    strokeThickness : 6,
                    wordWrap : true,
                    wordWrapWidth : 100
                };
`
![image](https://cloud.githubusercontent.com/assets/1722190/20782689/0f574f90-b7c9-11e6-8c40-ccf37da7d4b1.png)

**Comment by Icemic** [comment]
try style `breakWords: true`

**Comment by themoonrat** [comment]
This is actual desired behaviour for that setting. You see, the way it detects words is by looking for spaces between them. Chinese has no spaces, and so PIXI can't detect words...

Have no fear though... as well as turning on wordWrap, also turn on breakWords. This will gain your desired behaviour. I'd advise having breakWords turned on for Chinese and similar languages, but off for English and similar languages.

**Comment by hantaogo** [comment]
Thank you very much!
