### ISSUE TITLE
[Suggestion]  about NineSlicePlane's parameters

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3385]
```
export default class NineSlicePlane extends Plane
{
    /**
     * @param {PIXI.Texture} texture - The texture to use on the NineSlicePlane.
     * @param {int} [leftWidth=10] size of the left vertical bar (A)
     * @param {int} [topHeight=10] size of the top horizontal bar (C)
     * @param {int} [rightWidth=10] size of the right vertical bar (B)
     * @param {int} [bottomHeight=10] size of the bottom horizontal bar (D)
     */
    constructor(texture, leftWidth, topHeight, rightWidth, bottomHeight)
   {
       // ......
   }

    // ......
}
```

In the web development ,  the order of direction parameters  is  top, right,  bottom and left.
It's like a clock , one new day always start from 0 o'clock.

PIXI.js is based on HTML5 ， So I think it should consider the habits of the web developers.

**Comment by ivanpopelyshev** [comment]
If we are talking about those sizes, yep, I agree. Right now its (x1, y1, x2, y2) but we are dealing not with coords.

**Comment by finscn** [comment]
Oh, I see. 
I found there are named  xxxHeight , I think they are about  size
