### ISSUE TITLE
Dependency `resource-loader` should be updated

### ISSUE THREAD

**Issue by Icemic** [pixijs/pixi.js#3387]
Now, pixi is using `^1.8.0`, but this version does not support audio files (will be treated as text).

`resources-loader`'s latest release is `2.0.1` which support audio files.

How about considering using new version? 

@englercj

**Comment by staff0rd** [comment]
I believe this is planned, however v2 has some breaking changes that will need to be addressed.

**Comment by bigtimebuddy** [comment]
The new **resource-loader** uses signals instead of events so we need to create a deprecation layer to not break everyone's loading. That's mostly what's holding back this update.

**Comment by Icemic** [comment]
I tried to update it, but stuck at `npm run dist`.
Pixify throws `ERROR: 'import' and 'export' may appear only with 'sourceType: module'`, because resource-loader use `./src/index.js` as its package entry which is in ES6.
But pixi.js now prefers to transpile ES6 to ES5 before using pixify to output bundle.

**Comment by ivanpopelyshev** [comment]
Its better if we also use signals in v5. That deprecation layer should exist as a plugin, "pixi-compatibility" or something like that

**Comment by staff0rd** [comment]
Duplicate of #3116
