### ISSUE TITLE
[Confused] About ```skipUpdateTransform``` in WebGLRenderer.prototype.render

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3388]
```js
    /**
     * Renders the object to its webGL view
     *
     * @param {PIXI.DisplayObject} displayObject - the object to be rendered
     * @param {PIXI.RenderTexture} renderTexture - The render texture to render to.
     * @param {boolean} [clear] - Should the canvas be cleared before the new render
     * @param {PIXI.Transform} [transform] - A transform to apply to the render texture before rendering.
     * @param {boolean} [skipUpdateTransform] - Should we skip the update transform pass?
     */
    render(displayObject, renderTexture, clear, transform, skipUpdateTransform)
    {
       // ......

        if (!skipUpdateTransform)
        {
            // update the scene graph
            const cacheParent = displayObject.parent;

            displayObject.parent = this._tempDisplayObjectParent;
            displayObject.updateTransform();
            displayObject.parent = cacheParent;
           // displayObject.hitArea = //TODO add a temp hit area
        }
       // ......
    }
```
in in WebGLRenderer.prototype.render ,   the  default value of skipUpdateTransform is false,
But in some cases , it could take a mistake. example:

There is a DisplayObject Tree:

containerA
      |_____ spriteA
      |_____ spriteB
      |_____ spriteC
      |_____ ... many other sprites else ...

Sometimes , I want to decide render which  how render sprite by myself, like this : 
[example 1]
```
if ( condition1 ） {
    renderer.render(spriteA);
    renderer.render(spriteB);
} else if ( condition2 ） {
    renderer.render(spriteB);
    renderer.render(spriteA);
} else  if ( condition3 ）  {
    renderer.render(spriteC);
} else {
    renderer.render(containerA);
}
```

But , because  ```skipUpdateTransform==false``` and  ```displayObject.parent = this._tempDisplayObjectParent```, the sprites will lost the worldTransform in the parent, the result is wrong.
if I set skipUpdateTransform == true,  the result is also wrong, because the updateTransform will be ignored.

I think this is a bad design. under this design , if the users  want to render one display object have to use :   
```
sprite.updateTransform();
renderer.render(sprite, null, false, null, true);
```
it's so verbose.

in current PIXI design ,  we hard to do something like [example 1].

========

Sometimes , We add many sprites to a container  that's just for transforming them with an uniform worldTransform in container， not because that  "they are under / on the container , or are nodes in an rendering tree".

the ``` renderer.render(container)``` should NOT be the one way for rendering.

In the real game ,   the  Sprites Management  is a complex work , the array(container.children)  is far from enough. Sometimes We have to manage the sprites with ```if...else```  or even finite-state machine.
(e.g. ： In [example 1] ，the code is simple and clear.  
But if I use ```renderer.render(containerA)```, I have to switch ```visible``` of sprites, and resort the order of ```children```, or remove/add child dynamically / manually.  The real situation in the game would be more complicated. )

So , a  flexible & simple way to render one sprite  is very useful.

related issues :
 #3367    
 #3383    
 #3370    
 #3388

.

**Comment by finscn** [comment]
Suggestion : 

change ```skipUpdateTransform```{boolean}   to  ```transformUpdateMode```{int} : 

transformUpdateMode : 
* 0 : ignore ```displayObject.updateTransform()```
* 1 :  ignore parent.transform, use _tempDisplayObjectParent as parent. (like current skipUpdateTransform==false
* 2 : Auto-mode:   if  displayObject has parent , use the parent ;  if no parent , use _tempDisplayObjectParent as parent
`

**Comment by finscn** [comment]
I know there is an easy way to solve this problem  : add a new function like this : 
```
newFunction(displayObject, renderTexture, clear)
{
    displayObject.updateTransform();
    renderer.render(displayObject, renderTexture, clear, null, true);
}
```

But I think it's easy , but not good.

**Comment by ivanpopelyshev** [comment]
With that kind of stuff, you should make your own for of pixi, like my [2.5d pixi](github.com/gameofbombs/pixi.js) . I'm sure those kind of changes in API won't be accepted, unless it will contain serious improvements.

Year ago, I made same suggestions that you are making. I made new transform class, redone rendering pipeline. After 3 iterations (2 complete rewites), I realized that its not enough and I need to keep doing it, until it will be REALLY good to merge it into master branch. One of serious improvements I was able to separate into plugin that works both on mine and pixi version - [pixi-display](https://github.com/pixijs/pixi-display)

Keeping your own fork is good strategy, some of real projects can exist in production with it.

**Comment by GoodBoyDigital** [comment]
Hey @finscn , Thanks for sharing. Ultimately I think this is going to add confusion to the renderer rather than enhance it. It seems that you have some cool ways to make it work for you so lets stick with that. Cheers!
