### ISSUE TITLE
[Confused] About DisplayObject.prototype.updateTransform

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3389]
In current  PIXI.js : 
```
    updateTransform()
    {
        this.transform.updateTransform(this.parent.transform);
        // ......
    }
```

the  DisplayObject.prototype.updateTransform not check the parent , So this code can't run : 
```
var myContainer = new PIXI.Container();
// ......
myContainer.updateTransform();
```

If I want to run it , I have create an abstract  parent container , like this

```
var uselessAndAbstractContainer = new PIXI.Container();
var myContainer = new PIXI.Container();
uselessAndAbstractContainer.addChild(myContainer);
// ......
myContainer.updateTransform();
```

related issues : #3370

**Comment by finscn** [comment]
I think the ```updateTransform```  of DisplayObject/Container/Sprite need to think about 3 important questions : 
* which transform matrix should be update ? localTransform?  worldTransform?  or both?
* whether  with parent's  transform？ if with ,  with which one ？parent.localTransform?  parent.worldTransform?  or both?
* whether  call children's  updateTransform ?

In the real game , 
Sometimes we use  containers & child nodes as a pure rendering tree ， in this case ```container.updateTransform()``` or  ```renderer.render(container)``` is good enough.
But Sometimes ,  We have to consider  updateTransform/render  of sprites separately.  in this case Container is like an abstract  group.  

I know Container is an subclass of DisplayObject , it shouldn't be used as a abstract group.
But in PIXI , there is no an other way to manage some sprites which have same parent transform.

**Comment by finscn** [comment]
Share my solution now ：

the first step， add a new function named ```updateWorldTransform```  to  Transform & TransformStatic, like this  (sure, there is a little difference)  : 
```
    /**
     * Updates world matrix(include local matrix) without parent
     */
    updateWorldTransform()
    {
        const lt = this.localTransform;

        lt.a = this._cx * this.scale._x;
        lt.b = this._sx * this.scale._x;
        lt.c = this._cy * this.scale._y;
        lt.d = this._sy * this.scale._y;

        lt.tx = this.position._x - ((this.pivot._x * lt.a) + (this.pivot._y * lt.c));
        lt.ty = this.position._y - ((this.pivot._x * lt.b) + (this.pivot._y * lt.d));

        const wt = this.worldTransform;

        wt.a = lt.a;
        wt.b = lt.b;
        wt.c = lt.c;
        wt.d = lt.d;
        wt.tx = lt.tx;
        wt.ty = lt.ty;

        this._worldID ++;
    }
```

the 2nd step, add a function named ```updateTransformLite``` to DisplayObject & Container like this  (sure, there is a little difference) : 
```
    /**
     * Updates the transform of this object self
     */
    updateTransformLite()
    {
        if (this.parent)
        {
            this.transform.updateTransform(this.parent.transform);
            this.worldAlpha = this.alpha * this.parent.worldAlpha;
        }
        else
        {
            this.transform.updateWorldTransform();
            this.worldAlpha = this.alpha;
        }

        this._bounds.updateID++;
    }
```

**Comment by englercj** [comment]
Doing a check for parent takes a significant performance hit. We decided to remove it a while ago in favor of always assuming there will be a parent which made a big impact on perf.

Seems like the other issue you opened (#3415) talked more about this problem.
