### ISSUE TITLE
[Suggestion] About dist script: remove the old pixi.js pixi.mini.js and  *.map before start build dist

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3403]
The old version pixi would do it , but new version not.

If don't do it, there will be  an confusing situation ： 
At some time , the new pixi.js  and old pixi.min.js will concurrence, if  dist script be stop.

**Comment by finscn** [comment]
I create a PR to pixify  ， now just to use
```
    "dist": "pixify -d dist -n PIXI -o pixi -t babelify -r",
```
in pixi.js/package.json

**Comment by bigtimebuddy** [comment]
This can be accomplished (and should be) without changes to pixify. This [line](https://github.com/pixijs/pixi.js/blob/dev/package.json#L21) removes dist and lib folder using **rimraf**, thats the preferred way. So we could add: 

```json
{
  "scripts": {
    "predist": "rimraf dist && mkdirp dist",
    "dist": "pixify -d dist -n PIXI -o pixi -t babelify"
  }
}
```

**Comment by finscn** [comment]
Thanks.
 If I just want to remove that  4 files  ,not the folder , how should I do ?
 thanks

**Comment by bigtimebuddy** [comment]
`rimraf dist/*.js dist/*.map`
