### ISSUE TITLE
Latest FontFamily fix causes issue when supplying multiple families

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#3406]
https://github.com/pixijs/pixi.js/pull/3352

Putting quotes around the font works for that example, but stops the code working when supplying multiple fonts

Here are 2 new codepens, with before and after the fix, but with multiple options for font-family
Before fix: http://codepen.io/anon/pen/woyLaJ
After fix: http://codepen.io/anon/pen/eBVwYK

We need a new fix that works for both scenarios!

**Comment by bigtimebuddy** [comment]
What about something like:

`'"' + fontFamily.split(',').join('","') + '"'`

We probably need to trim each item after the split.

**Comment by hendrysadrak** [comment]
Any progress on this?

**Comment by bigtimebuddy** [comment]
@themoonrat Could you make a PR for this change?

**Comment by themoonrat** [comment]
Will do after I finish my last minute xmas present panic buying ;)

**Comment by bigtimebuddy** [comment]
### 🎁 !!!

**Comment by kennardconsulting** [comment]
+1

**Comment by bigtimebuddy** [comment]
Created a new PR #3513 to address this issue. For example:

```js
const text = new PIXI.Text('Hello World', {
    // Expressed as a comma-separated
    fontFamily: 'Arial, sans-serif'
});
```

```js
const text = new PIXI.Text('Hello World', {
    // Expressed as an array of fonts
    fontFamily: ['Arial', 'sans-serif']
});
```
