### ISSUE TITLE
Update documentation for DestroyOptions

### ISSUE THREAD

**Issue by userusernamenameception** [pixijs/pixi.js#3407]
Destroy Options are defined as an Object | Bool in documentation for Container but no reference for properties of DestroyOptions Object.

Could potentially use an IDestroyOptions Interface or DestroyOptions value object here?

Also if True is passed in as argument to container then children are also passed True, which by default destroys the textures + baseTextures of children. Should this be default behavior?

**Comment by ivanpopelyshev** [comment]
That's exactly why we added options. Bool will be deprecated.

**Comment by ivanpopelyshev** [comment]
as for interface, is there a way to do it in ES6? I just know how to do it in TS...

**Comment by bigtimebuddy** [comment]
Boolean for destroy should not be deprecated, it is a shorthand for setting all destroy options on. It's still a valuable API to keep around.

**Comment by userusernamenameception** [comment]
I can see how passing true could be useful for hard destroying, however it seems like it's quite easy to do something quite destructive here that IMHO wouldn't be done very often. No, not without Typescript probably should stay as is with just an update to documentation to reflect allowed properties.
