### ISSUE TITLE
Why `mousemove` bind on document, it will cause conflict with other plugins

### ISSUE THREAD

**Issue by fancyoung** [pixijs/pixi.js#3412]
When I use `Sortable` in my page, it also use this event.
So the event in other plugin will not fired.

This problem in both v3 and v4.
v2: `domElement.addEventListener('mousemove',  this.onMouseMove, true);`
v3: `window.document.addEventListener('mousemove',    this.onMouseMove, true);`
v4: `window.document.addEventListener('mousemove', this.onMouseMove, true);`

Why this event must bind on document, but other events are bind on `interactionDOMElement`?
Is there any config to disable it?

**Comment by staff0rd** [comment]
Hiya @fancyoung.  Are you saying that using another javascript library is stopping PIXI from working as expected?

**Comment by fancyoung** [comment]
PIXI works, but another javascript library's `mousemove` event is not working.
It seems prevented by PIXI.

**Comment by themoonrat** [comment]
Odd; because preventDefault isn't called on the mousemove event in PIXI.

mousemove used to just be on the canvas, but was moved to the window on May 2015 to fix the following issue: https://github.com/pixijs/pixi.js/issues/1564

**Comment by themoonrat** [comment]
Any update on this @fancyoung ?

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
