### ISSUE TITLE
JSdoc Bug with Members

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#3416]
Some members are not showing up in the docs. For instance: [PIXI.Sprite#blendMode](https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L77-L84). 

**Example:**
http://pixijs.download/dev/docs/PIXI.Sprite.html

This issue was noticed with #3413.

**Comment by staff0rd** [comment]
It seems no public members are displaying by default.  To have them displayed you currently need to use `@memberOf` which makes `@private` seem a bit redundant.  See #3471.

**Comment by themoonrat** [comment]
Indeed, I've found that with jsdoccing my game, which also uses es6 classes. Public functions are output, but not public members. @private isn't redundant as it'll correctly assist IDEs. Maybe there's some JSDoc configuration somewhere to pull in the public members

**Comment by themoonrat** [comment]
Annoyingly, even if you set "private" to true in scripts/jsdoc.conf.json - that outputs private functions to the docs... but still no members at all. :8ball:

**Comment by bigtimebuddy** [comment]
Is this a bug with jsdoc?

**Comment by themoonrat** [comment]
I believe so, can't see a config option for it

**Comment by themoonrat** [comment]
I've raised an issue on JSDoc github (https://github.com/jsdoc3/jsdoc/issues/1301) - we'll see what they say

**Comment by Native-Coder** [comment]
REALLY wish we could get the ES6 Class Memebers to document correctly...

**Comment by Native-Coder** [comment]
I'm having the same problem, but it looks as though it was reported over a month ago (https://github.com/jsdoc3/jsdoc/issues/1293). According to this report it has to do with using @export in the module that contains the class.

**Comment by bigtimebuddy** [comment]
Fixed with #3542
