### ISSUE TITLE
WebGL render error resulting from cacheAsBitmap=true upon upgrading to 4.2.3

### ISSUE THREAD

**Issue by BossLevel** [pixijs/pixi.js#3418]
I have a number of "layers" (complex, static Pixi Containers) that I render at start and then cache. Upon upgrading from 4.0.0 to 4.2.3 I'm now receiving multiple errors as follows:

```
[.Offscreen-For-WebGL-0x34fecf810000]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[.Offscreen-For-WebGL-0x34fecf810000]RENDER WARNING: texture bound to texture unit 1 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
WebGL: too many errors, no more errors will be reported to the console for this context.
```

As "texture unit 1" isn't particularly clear I disabled each render instruction individually and this was how I established that it was the layer.cacheAsBitmap = true; instructions that were causing it.  Interestingly the layers still appear to render fine and there are no other apparent ramifications.

As an FYI, the canvasRenderer/layer size is 1920*750 although this could be variable. Occurs in Chromium Version 55.0.2883.75 (64-bit) on Ubunut 16.04. I did test it in FF 50.0.2 also and whilst I didn't see any console errors, the frame rate dropped to 10fps and there were render errors although these could be entirely unrelated as I haven't tested in FF recently.

**Comment by bigtimebuddy** [comment]
Could you create a [jsfiddle](https://jsfiddle.net/) or [jsbin](https://jsbin.com) which reproduces this error on that platform? It really helps us squash these types of bugs if we have a reproducible example to validate against. Thanks.

**Comment by BossLevel** [comment]
@bigtimebuddy totally appreciate that and would have normally but in this instance there's just too much prior setup. Also there was no code change inbetween upgrading the Pixi version so I suppose my purpose in posting this issue (and I meant to append this to my original post) is to initally ask the question of whether there's something obvious you've changed between those versions?

Googling that particular issue showed that it principally occurred when attempting to use a texture that hadn't loaded yet so my thinking was that given a) the size of the canvas and b) the fact that there were multiple ones layered on each other, perhaps the cacheAsBitmap function was taking slightly too long to execute before the next render tick?  Have there been changes to cacheAsBitmap between those versions that would cause it to take longer?

Ta

**Comment by BossLevel** [comment]
Also, is there potentially an issue with caching a bitmap where the sides aren't powers of two?

**Comment by BossLevel** [comment]
@bigtimebuddy @staff0rd Just wanted to update you on this - the problem appears to have disappeared as quickly as it came! I'll confess that I didn't notice exactly when, due to too much console output but I suspect this is as a result of a Chrome update - they appear to have been breaking plenty of stuff in the past month ;-)  As such, marking "closed".
