### ISSUE TITLE
posssible InteractionManager propagation bug

### ISSUE THREAD

**Issue by uorbe001** [pixijs/pixi.js#3419]
We have stumbled upon what I think is a bug, but might be intended behaviour for some reason I don't comprehend. I have prepared a basic example that I've used to replicate the issue:

```js
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

var parent = new PIXI.Container();
parent.on("click", onStageDown);
parent.interactive = true;
stage.addChild(parent);

var sprite = PIXI.Sprite.fromImage('required/assets/basics/bunny.png');

sprite.position.set(230,264);
sprite.interactive = true;
sprite.on('click', onSpriteDown);

parent.addChild(sprite);

var shadow = PIXI.Sprite.fromImage('required/assets/basics/bunny.png');
shadow.position.set(230,264);
parent.addChild(shadow);

function onSpriteDown (eventData) {
    console.log("Sprite clicked");
}

function onStageDown (eventData) {
    console.log("Stage clicked");
}
// start animating
animate();

function animate() {

    requestAnimationFrame(animate);

    // render the root container
    renderer.render(stage);
}
```

With a structure similar to this, I would expect both the `onSpriteDown` and `onStageDown` listeners to be called, but what I get with that code (tested with pixi 4 in the examples pages) is that only the `onStageDown` is getting called. 

I've debugged this and I know that when [`processInteractive`](https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L819) iterates over the children, when it reaches `shadow` this element is considered as hit, and by the time it processes `sprite` hitTest is set to false, so it never actually tries to test it and call its function.

Is this expected behaviour? If it isn't, I can probably find some time to fix it 😇

**Comment by staff0rd** [comment]
Pen; https://codepen.io/staff0rd/pen/YpjozL

**Comment by staff0rd** [comment]
@uorbe001 I've added some tests that display this functionality, and I agree it seems inconsistent.  Waiting on feedback for #3535 to determine whether this is expected functionality or not.

**Comment by uorbe001** [comment]
@staff0rd thanks for doing that! I'm still waiting for confirmation before spening time trying to fix it.

**Comment by staff0rd** [comment]
Heya @uorbe001, team members agree that the expectation in #3535 is correct.  Please feel free to commit a fix that makes that test pass.

**Comment by KosGrillis** [comment]
Is there a fix for this? I'm having the same issue but on mouseover events, I want only the foremost element to receive the events.
