### ISSUE TITLE
Freezing render at update huge texture to gpu

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#3420]
https://github.com/pixijs/pixi.js/issues/1899

this is same issue and this issue is very critical for us..

our game use many textures and it is load during game playing,

game is frozen short time during load texture.

if  move textures's loading on loading time,  there have problems too

because render is freezing so loading looks stopped until loading done..

is there any solution to resolve this?

thx..

our game's textures have following size
512x512, 1024x1024 - usually using this ( this size load during playing game)
2048x2048 - some texture load at playing game, some texture load at loading time
4096x4096 - only for pc this size can load at loading time

thx.. alots..

**Comment by staff0rd** [comment]
Hi @SeminYun, are you able to supply a [fiddle](https://jsfiddle.net) or [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by themoonrat** [comment]
@SeminYun Any update if this is still a problem or not? If it is, then a fiddle would be great to investigate; if not we can close this issue down :)

**Comment by GoodBoyDigital** [comment]
closing for now as seems inactive. @SeminYun you could try looking into the renderer.prepare functions to solve your issue. 

Cheers!
