### ISSUE TITLE
Creating multiple looping MovieClips in the Same stage

### ISSUE THREAD

**Issue by ahmedelmahalawey** [pixijs/pixi.js#3425]
I tried to render multiple movieclips in the same stage and it was successfully created but sometimes during the first loop of every clip, frames of another clip appears over it causing a twitching effect on the clip. So is there a better way to add multiple looping movieclips in the same stage.

Thanks

**Comment by staff0rd** [comment]
Hiya, are you able to supply a [fiddle](https://jsfiddle.net) or [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

Is this similar to #3180?

**Comment by themoonrat** [comment]
@ahmedelmahalawey Any update on this? If you've found a solution, let us know and we can close the issue. Thanks!

**Comment by GoodBoyDigital** [comment]
closing for now as seems inactive.
