### ISSUE TITLE
[ERROR] About an error :  "WebGL: INVALID_ENUM: activeTexture: texture unit out of range"

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3426]
the code at

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L275-L295

Sometimes ,  ```t._enabled ``` always equals ```TICK``` , then the nextTexture._virtalBoundId always be ```-1```.

And there is an error on browser's console : 
```
WebGL: INVALID_ENUM: activeTexture: texture unit out of range
```

**Comment by bigtimebuddy** [comment]
Duplicate of #3373

**Comment by finscn** [comment]
@bigtimebuddy  , OK. I've add more informations  at  https://github.com/pixijs/pixi.js/issues/3373#issuecomment-265764333

I hope it could help you to find the key point of this issues.

**Comment by bigtimebuddy** [comment]
Thank you @finscn!
