### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by issy123** [pixijs/pixi.js#3427]
I would love to have a changelog each time a new feature or changes in features are made, so I know how to migrate to the newest version :)

**Comment by bigtimebuddy** [comment]
We usually include these notes in the [releases section](https://github.com/pixijs/pixi.js/releases). Were you looking for something else?

**Comment by themoonrat** [comment]
https://github.com/pixijs/pixi.js/releases might be what you're looking for... contains both a change log and diffs from the last released version

**Comment by issy123** [comment]
Ah yes! Thanks
