### ISSUE TITLE
AnimatedSprite should NOT force to use core.ticker.shared.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3428]
Maybe Users  want to update animatedSprite by their gameLoop/gameTick method.

So I think there should be a switch to control whether use ```core.ticker.shared```

**Comment by bigtimebuddy** [comment]
Would be easy to add another constructor argument and member for self-updating. Turning this off should not use shared-ticker.
```js
class AnimatedSprite {
  constructor(textures, selfUpdate=true);
}
```
Alternatively or in addition, could add global setting `AnimatedSprite.SELF_UPDATE` to disable shared ticker usage for all AnimatedSprite. 

Thoughts?

**Comment by finscn** [comment]
@bigtimebuddy ， I've add a PR.

But I think your plan is better.

**Comment by staff0rd** [comment]
See #3429

**Comment by GoodBoyDigital** [comment]
merged 👍
