### ISSUE TITLE
How to create a  AnimatedSprite with textures that have different sizes ？

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3430]
The animatedSprite's  size is   100*100.
But  the textures of it have different sizes and the original images've been trimmed.

**Comment by ivanpopelyshev** [comment]
What's the problem ? If "texture.orig" is the same for all of them it should work

**Comment by finscn** [comment]
@ivanpopelyshev  , 
I mean that  How to handle the frames with different anchors ?

**Comment by themoonrat** [comment]
If you set the anchor of the AnimatedSprite to 0.5,0.5 then all the textures it uses will all be centred, no matter their different sizes

**Comment by ivanpopelyshev** [comment]
Why do you need different anchors? We are talking about trimming. All textures need to have same "texture.orig" but "texture.frame" and "texture.trim" will be different. "frame" is region on real baseTexture, while "trim" is how it was trimmed in original image.

**Comment by finscn** [comment]
The key point is "All textures need to have same "texture.orig".
My textures have different "texture.orig" , so I want to use ```anchor``` to offset the differences.

**Comment by ivanpopelyshev** [comment]
No, that means you have to make "texture.orig" the same, and edit "texture.trim" that way it shows trimmed width&height, and x,y offset.

**Comment by finscn** [comment]
OK , I see.
Thanks.

@ivanpopelyshev  , 
And I don't know how to let my fork version of PIXI  become a branch on your  fork version .
Could you tell me some detail about it ? 
Thanks again.

**Comment by ivanpopelyshev** [comment]
@finscn 

![Alt text](https://monosnap.com/file/0Az2KmqUytKdqAgu6kOSGx0uudzsVz.png)

In my config I have yours, mine (origin) and pixi (upstream). I can push any branch I create to any of these repos where I have enough access. I can fetch each repo, so "origin/master", "finscn/master", "upstream/master" and just "master" are different branches for me.

**Comment by staff0rd** [comment]
Seems like this is answered so closing - please let me know if it's not.
