### ISSUE TITLE
iPhone 6 + iOS 10 flickering

### ISSUE THREAD

**Issue by cmayhem** [pixijs/pixi.js#3432]
There is random intermittent flickering on iPhone 6 + iOS 10. This seems to be general webgl issue not limited to pixi.js.
Workaround seems to be to add renderer.gl.flush() call after render() call.

**Comment by kaansoral** [comment]
What kind of a flickering is it? Could be related to #3373 - If only some textures flicker

**Comment by cmayhem** [comment]
The canvas flashes completely black.

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by GoodBoyDigital** [comment]
@englercj, @ivanpopelyshev - what are your thoughts on having a flush at the end of the render function? From what I have read, looks like it couldn't hurt!

**Comment by englercj** [comment]
I think a gl flush would be fine, according to docs (emphasis added by me):

> Because any GL program might be executed over a network, or on an accelerator that buffers commands, **all programs should call glFlush whenever they count on having all of their previously issued commands completed**. For example, call glFlush before waiting for user input that depends on the generated image.

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital yes.

**Comment by gg4u** [comment]
Could you provide an example?

I am trying the following with pixi 4.5.4: but flickering persist.

where is gl object in :
https://pixijs.download/v4.5.4/docs/PIXI.WebGLRenderer.html#flush ?

  ```
var renderer = PIXI.autoDetectRenderer(width, height, renderer_param , false, true);
  renderer.backgroundColor = 0xf5f5f5;

  // adding and manipulating graphics

  // public API
  var pixiGraphics = {
       run : animationLoop
  }

  function animationLoop() {
    requestAnimationFrame(animationLoop);
    // other stuff
    renderOneFrame();
  }

  function renderOneFrame() {
    graphics.clear();
// render different elements
    renderer.render(stage); // render stage

    renderer.flush(); // adding flush
  }
```

**Comment by ivanpopelyshev** [comment]
try "renderer.gl.flush()" instead.

**Comment by gg4u** [comment]
@ivanpopelyshev  can I offer you a coffe?
 👍 

It seems to work!

I haven't found it in documentation: what is .gl property ?
Would it work also on android ? (testing on iOS)

**Comment by ivanpopelyshev** [comment]
Its underlying webgl rendering context :)

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
