### ISSUE TITLE
【 2 + 1 Suggestions】The eslint config of PIXI.js  is too much strict .

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3434]
### One :  "no-unmodified-loop-condition"
I have a function like this : 
```
funcA(loopMoreThanOnce)
{
    //  .....
    do {
        //  .....
    } while (loopMoreThanOnce);
    //  .....
}
```
This funcA is reasonable.  But  because ```"no-unmodified-loop-condition": 1``` , I have to write the code very ugly like this : 
```
funcA(loopMoreThanOnce)
{
    //  .....
    let flag;
    do {
        flag = loopMoreThanOnce;
        //  .....
    } while (flag);
    //  .....
}
```
Could you remove it please ?

### Two :  "func-names"

Because of ```"func-names": [1, "always"]```

When I want to define a function have to write like this : 
```
const funcName = function funcName()
{

}
``` 

The name on right side is unnecessary and stupid.

Could you remove it please ?

### Three : "quote-props" & "dot-notation"
I want to use  `'key'` for the same object ,
but because   `"quote-props": [1, "as-needed"]`  & `"dot-notation" : 1` , 
I can't use Uniform Style in my code：

```js

// look at the keys : 
        this.compositeOperations = {
            'source-over': [gl.ONE, gl.ONE_MINUS_SRC_ALPHA, 1],
            lighter: [gl.ONE, gl.ONE_MINUS_SRC_ALPHA, 0],
            lighten: [gl.ONE, gl.ONE_MINUS_SRC_ALPHA, 0],
            darker: [gl.DST_COLOR, gl.ONE_MINUS_SRC_ALPHA, 1],
            darken: [gl.DST_COLOR, gl.ONE_MINUS_SRC_ALPHA, 1],
            'destination-out': [gl.ZERO, gl.ONE_MINUS_SRC_ALPHA, 1],
            'destination-over': [gl.ONE_MINUS_DST_ALPHA, gl.ONE, 1],
            'source-atop': [gl.DST_ALPHA, gl.ONE_MINUS_SRC_ALPHA, 1],
            xor: [gl.ONE_MINUS_DST_ALPHA, gl.ONE_MINUS_SRC_ALPHA, 1],
            copy: [gl.ONE, gl.ZERO, 1],
            'source-in': [gl.DST_ALPHA, gl.ZERO, 1],
            'destination-in': [gl.ZERO, gl.SRC_ALPHA, 1],
            'source-out': [gl.ONE_MINUS_DST_ALPHA, gl.ZERO, 1],
            'destination-atop': [gl.ONE_MINUS_DST_ALPHA, gl.SRC_ALPHA, 1],
        };

obj['source-over'];
obj.lighter;
obj.lighten;
obj.darker;
obj.darken;
obj['destination-out'];
obj['destination-over'];
obj['source-atop'];
obj.xor;
obj.copy;
obj['source-in'];
obj['destination-in'];
obj['source-out'];
obj['destination-atop'];


```

**Comment by BossLevel** [comment]
FYI the reason you put the name of the function on the right hand side is so that it doesn't appear as an anonymous function when debugging. Which I've never found to be unnecessary. If you don't want to write it twice, remove the "const funcName =" (although personally, for reasons related to hoisting, I've always found doing both led to less errors).

I should point out that I'm not affiliated to PIXI so feel free to ignore me.

**Comment by finscn** [comment]
@BossLevel  ,  
 if I want to do something like this : 
```
obj.methodA = function () { ....}
```
I have to use 
```
obj.methodA = function methodA() { ....}
```
I don't like it.

**Comment by themoonrat** [comment]
Hi finscn. Sorry you don't like it, but as BossLevel, it's an extra method name for the sake of extra debugging information. I'm sure you can understand why, given a choice, developers of a library might choose ease of debugging over more concise syntax.

**Comment by finscn** [comment]
@themoonrat  @bigtimebuddy  , what do you think about   One & Three ?

**Comment by themoonrat** [comment]
One: 'meh'. I have no strong feelings over!
Three: I agree with you, this is annoying. 'quote-props' would be best changed to 'consistent-as-needed' - I don't know if this is enough to make 'dot-notation' be less annoying tho in these situations

**Comment by finscn** [comment]
@themoonrat ， see  https://github.com/pixijs/pixi.js/pull/3429#issuecomment-267046207 ,  it's  about One.
the code at   https://github.com/finscn/pixi.js/blob/master/src/extensions/Animation.js#L247 

If don't remove it ,  the method `updateByTime(time, skipFrame)`  will have to write in ugly style.

**Comment by ivanpopelyshev** [comment]
Yeah, better change the 3, I dont know about 1.
Better not change something without @englercj response, he started this problem :)

**Comment by bigtimebuddy** [comment]
I agree with @ivanpopelyshev. @englercj set the style rules and I want him to weigh in before tweaking the linting.

**Comment by finscn** [comment]
@themoonrat  @ivanpopelyshev  ,  see  https://github.com/pixijs/pixi.js/pull/3429#issuecomment-267046207 ,  it's  about One.

the code at   https://github.com/finscn/pixi.js/blob/master/src/extensions/Animation.js#L247 

If don't remove it ,  the method `updateByTime(time, skipFrame)`  will have to write in ugly style.

**Comment by bigtimebuddy** [comment]
@finscn if this change is blocking you from the Animation PR, I would suggest you conform to the existing lint styles (even if you disagree with it) and submit it anyways. If we reconsider the linting rules, you can make a change to your PR or submit another patch so it's styled according to the updated lint rules.

**Comment by englercj** [comment]
- `no-unmodified-loop-condition`: A loop where the condition is not modified in the loop is nearly always a bug, this rule is useful and needs to stay.

- `func-names`: The second is for debugging purposes, like others have mentioned. It is also around to help enforce a consistency that *most* function expressions should be arrow functions and *most* non-anonymous functions should be declarations. Meaning you should almost never be doing `a.b = function b() {}`. Do one of these: `a = { b() {} }`, or `a.b = () => {}` or `function b() {}; a.b = b;`. In the rare case where you *must* use a function expression with an anonymous function *and* that function needs its own context, you can disable this rule inline: `/* eslint-disable func-names */ .... /* eslint-enable func-names */`. Note that code we merge into core pixi that disable eslint rules will be scrutinized, you almost never need to disable the rules (but sometimes you do).

- `quote-props`: I can definitely see how that would be annoying. It would be best if we made this rule to just be "consistent". Meaning you use quotes on all properties of the object, or on none. Specifically use `consistent-as-needed` configuration: `"quote-props": [1, "consistent-as-needed"]`. That's a good change.

- `dot-notation`: This rule is in place to enforce usage of dot notation when possible. It is pretty rare when you need to break that rule. Usually if you have a property that requires brace notation, you aren't accessing it directly, but instead using a variable somewhere to represent the key. What I mean is you would rarely do this: `obj['source-over'];`, you'd probably almost always do this: `obj[blendMode];`. I feel comfortable with the current rule here, I'm not convinced this is an issue.

**Comment by finscn** [comment]
@englercj , Thanks for your detail talking.
But if enable  `no-unmodified-loop-condition`, how should I write the method like this  : 
```
methodA(loopMoreThanOnce)
{
    //  .....
    do {
        //  .....
        // there are some 'continue' in the loop.
        //
    } while (loopMoreThanOnce);
    //  .....
}
```

And I think the  `a.b = () => {}` is not a good choice. because the `this` in  `() => {}` not as same as `function(){}`.   `a = { b() {} }` is the best one, thank you.

**Comment by englercj** [comment]
> But if enable no-unmodified-loop-condition, how should I write the method like this :

Depends on what that is actually doing, looks like what you are doing is `while(true) {}` with a break inside. But what a better way to write it would be, depends on what is actually happening in the loop.

> And I think the a.b = () => {} is not a good choice. because the this in () => {} not as same as function(){}.

Like I said before:

> Do one of these: a = { b() {} }, or a.b = () => {} or function b() {}; a.b = b;. In the rare case where you must use a function expression with an anonymous function and that function needs its own context, you can disable this rule inline

Again, it depends on what specifically you are doing. These rules are setup the way they are because the *general* case should follow these rules, only rare specific instances should ignore them.

**Comment by finscn** [comment]
@englercj , Thanks for you reply , I understand you absolutely.

But there is another question , it's about  `"` and `'` of string.
The  new JS  supports  "`" for magic string , but the   ' & `  are too similar.
Do you want to   use " to string ?

**Comment by englercj** [comment]
I honestly don't think it is worth it, but I don't have strong feelings.
