### ISSUE TITLE
[confused] formula to make calculate the width of a text box 

### ISSUE THREAD

**Issue by courtneyvigo** [pixijs/pixi.js#3437]
Hi all :) I am trying to calculate the width of a text box so I can animate a second text box next to the first one, leaving enough space for what ever content is put in the first. How should I go about doing this?

this is what I have so far but its not working. The text just disappears with no errors in the console:

text2.x = text1.textWidth + 500;

**Comment by themoonrat** [comment]
text2.x = text1.width + 500;

**Comment by courtneyvigo** [comment]
Thank you!

**Comment by courtneyvigo** [comment]
Is there a way to add this with y position in one line? Thanks!

**Comment by courtneyvigo** [comment]
text1b.position.set((text1a.width + 520), 0)

never mind :)
