### ISSUE TITLE
unreliable font

### ISSUE THREAD

**Issue by courtneyvigo** [pixijs/pixi.js#3438]
sometimes the google font loads and sometimes it doesn't. I have tried loading the font in the HTML, CSS, as well as the JS. The only one that really worked was the CSS but as I said, when I refresh, sometimes it shows up and sometimes it doesn't.

**Comment by bigtimebuddy** [comment]
This sounds like a loading race-condition. I suspect that you're trying to render text in PIXI when the font hasn't completed loading yet. 

One suggestion would be to use the `document.font.load` API? Currently, it has limited browser support, but helpful for preloading fonts: https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/load

Hope that helps.

**Comment by themoonrat** [comment]
I use and find https://github.com/bramstein/fontfaceobserver good for font loading.
