### ISSUE TITLE
PIXI.Text may has bug with cacheAsBitmap

### ISSUE THREAD

**Issue by Icemic** [pixijs/pixi.js#3442]
with v3.0.2 (works fine): https://jsfiddle.net/Lfp8hr0m/2/
with v4.0.2 (cannot display the initial text, but the other works): https://jsfiddle.net/Lfp8hr0m/3/
with v4.2.3 (same as v4.0.2, in addition to some webgl warnings): https://jsfiddle.net/Lfp8hr0m/4/

**Comment by Icemic** [comment]
and 

```js
text.cacheAsBitmap = false;
text.cacheAsBitmap = true;
```

cannot update cache's area

see https://jsfiddle.net/5xun0wrL/4/

**Comment by Icemic** [comment]
Why not cache by default (performs like a normal sprite) and update it once `text` or `style` changed?

Now, Text's performance on mobile devices is quite bad because it copies texture from hidden canvas context2d in every tick. 

I have a save & load screen which has 20*5 (archive number * number of text sprite in each archive), it performs 1 fps on my phone...And only if on destop, the CPU use rate are high. (I hope I did not write the wrong code)

**Comment by GoodBoyDigital** [comment]
fixed via #3633 👍
