### ISSUE TITLE
strange error when loading image assets

### ISSUE THREAD

**Issue by courtneyvigo** [pixijs/pixi.js#3448]
Hi! Im trying to add an image to animate on the canvas and I keep getting this error in the console:

'file:///Users/courtneyvigo/Desktop/CHEERScup_Pixi/images/red.png' from origin 'file://' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access.

This is what I am trying so far:
// create a texture from an image path
  var texture = PIXI.Texture.fromImage("images/red.png");
  // create a new Sprite using the texture
  var red = new PIXI.Sprite(texture);
 
  // center the sprites anchor point
  red.anchor.x = 0.5;
  red.anchor.y = 0.5;
 
  // move the sprite t the center of the screen
  red.position.x = 200;
  red.position.y = 150;
 
  stage.addChild(red);

**Comment by themoonrat** [comment]
Hiya. It's really best to test your page via web server rather than just loading the html file directly. Windows comes with iis that you can install so you can host the page on your own pc, but there are others. Browsers don't like hosting files from a local file system due to security reasons.

**Comment by courtneyvigo** [comment]
You rock! Thank you!

**Comment by courtneyvigo** [comment]
<img width="366" alt="screen shot 2016-12-12 at 11 19 49 am" src="https://cloud.githubusercontent.com/assets/17307689/21113039/f058a2b4-c05c-11e6-9499-246998085437.png">

**Comment by courtneyvigo** [comment]
Its still not loading but the error is gone

**Comment by courtneyvigo** [comment]
What should I do if it wont load past 50%?

loader
//add images by:
  .add("images/red.png")
  .add("https://res.cloudinary.com/dubyisimd/image/upload/v1481228417/buttonplaceholder_iit0dp.png")
  
  //creates a progress statement that will check to see if assets are loading
  .on("progress", loadProgressHandler)
  .load(runAnimation, addButton, addRedGem);

//this function will check to see if all assets are loading to the stage. loader 
function loadProgressHandler(loader, resource) {
  //Display the file `url` currently being loaded
  console.log("loading: " + resource.url);

  //Display the precentage of files currently loaded
  console.log("progress: " + loader.progress + "%");
}

//button:
function addButton() {

  button = TextureCache(resources["https://res.cloudinary.com/dubyisimd/image/upload/v1481228417/buttonplaceholder_iit0dp.png"].texture);
  stage.addChild(button);

  button.position.set(15,15);

}
var TextureCache = PIXI.utils.TextureCache;

function addRedGem() {
  red = TextureCache(resources["images/red.png"]);
  stage.addChild(red);

  red.position.set(40,40);
}

**Comment by courtneyvigo** [comment]
https://jsfiddle.net/courtneyvigo/3t6ncvhz/15/
