### ISSUE TITLE
Truncating text instead of word wrap?

### ISSUE THREAD

**Issue by devnill** [pixijs/pixi.js#3449]
I'd like to truncate text in a manner similar to the 'text-overflow' css property. I looked at the documentation but didn't see any provided tools to do so. Considering how often this behavior is used elsewhere, it seems like something that I might be missing.

Is this functionality provided in pixi or is it something that I should shim in?

**Comment by themoonrat** [comment]
Hi devnill. This is not something that PIXI currently has functionality for, but we'd love a PR to add it in!

**Comment by abraaobuenotype** [comment]
try https://github.com/abraaobuenotype/type

**Comment by englercj** [comment]
Going to close this since I don't think we will be adding it anytime soon. Ideally we will move all the text layout code *out* of pixi and into userland. That way we can focus on rendering text the best we can, and letting other libs do a better job of laying out text than we can.

**Comment by EloB** [comment]
I'm also a bit interested in this... I managed todo this with `measureText()` (http://pixijs.download/release/docs/PIXI.TextMetrics.html#.measureText) and some calculation.

My current problem is that I'm away from `Text` and towards against `BitmapText`. Can anyone pin point me in the right direction to solve this?

**Comment by EloB** [comment]
Here is an excerpt from that code.

```jsx
reload(text, style, maxLines) {
  if (maxLines === Infinity) {
    this.setState({ text });
    return;
  }
  const { wordWrapWidth } = style;
  const pixiStyle = new TextStyle(style);
  const { lines } = TextMetrics.measureText(text, pixiStyle);
  let newText = text;
  if (lines.length > maxLines) {
    const truncatedLines = lines.slice(0, maxLines);
    const lastLine = truncatedLines[truncatedLines.length - 1];
    const words = lastLine.split(' ');
    const wordMetrics = TextMetrics.measureText(`\u00A0\n...\n${words.join('\n')}`, pixiStyle);
    const [spaceLength, dotsLength, ...wordLengths] = wordMetrics.lineWidths;
    const { text: newLastLine } = wordLengths.reduce((data, wordLength, i) => {
      if (data.length + wordLength + spaceLength >= wordWrapWidth) {
        return { ...data, length: wordWrapWidth };
      }
      return {
        text: `${data.text}${i > 0 ? ' ' : ''}${words[i]}`,
        length: data.length + wordLength + spaceLength,
      };
    }, { text: '', length: dotsLength });
    truncatedLines[truncatedLines.length - 1] = `${newLastLine}...`;
    newText = truncatedLines.join('\n');
  }
  this.setState({ text: newText });
}
```
