### ISSUE TITLE
Bug with mouse events on overlapping interactive elements

### ISSUE THREAD

**Issue by edclement** [pixijs/pixi.js#3450]
Using  Pixi.js 4.2.3 - ✰ WebGL ✰

I have two sprites that overlap partially. They have the following code attached for example purposes (I cut out some excess and this will need to be modified slightly to actually work):
```js
let marker = new pixi.Sprite(this._texture);
marker.interactive = true;
marker.on('mouseover', this._onMarkerMouseOver);
marker.on('mouseout', this._onMarkerMouseOut);

notifyMouseOverMarker (spriteMarker) {
    console.log('over', spriteMarker.identifier, this._markersUnderMouse);
}

notifyMouseOutMarker (spriteMarker) {
    console.log('out', spriteMarker.identifier, this._markersUnderMouse);
}
```

This is what I get in my console:
![image](https://cloud.githubusercontent.com/assets/5667395/21113434/9860669e-c077-11e6-81b7-317eac06461f.png)

Notice that the `6cb255` marker gets the `mouseout` event twice, once before it even gets the `mouseover`event... ??

**Comment by edclement** [comment]
This is in chrome 54.0.2840.99 btw

**Comment by themoonrat** [comment]
Hi @edclement - could you create a codepen or jsfiddle demonstrating this please to make it easier for us to investigate? thank you!

**Comment by edclement** [comment]
I'll try to do so today. Thanks.

**Comment by edclement** [comment]
Here is an example of the issue: https://jsfiddle.net/gf2sabv7/
Check the console to see how the wrong sprite is passed as the event.data.target

**Comment by staff0rd** [comment]
Possibly using the wrong property?  Switching this to `currentTarget` looks to get the functionality you're expecting; https://jsfiddle.net/pa4x26eb/
