### ISSUE TITLE
how to check the position of an element

### ISSUE THREAD

**Issue by courtneyvigo** [pixijs/pixi.js#3451]
I need to write an if statement that checks the position of an element once it reaches the center of the canvas, I will add physics to that element. I have:

if red.position == 250 {console.log("this is it")}

but I get an error saying:
unexpected identifier (it doesnt like the red.position I think)

Thanks in advance!

**Comment by ivanpopelyshev** [comment]
```
if (red.position.x == 250) {console.log("this is it")}
```

**Comment by courtneyvigo** [comment]
Ha! That easy

**Comment by ivanpopelyshev** [comment]
UPD.

http://shop.oreilly.com/product/9780596805531.do 6th or 7th edition

**Comment by courtneyvigo** [comment]
Thanks. Its giving me another error but Ill fix it

**Comment by courtneyvigo** [comment]
Thanks. Just a little rusty and not used to pixi. :p

**Comment by themoonrat** [comment]
It's worth bookmarking http://pixijs.download/v4.2.3/docs/index.html for pixi docs
