### ISSUE TITLE
Objects not getting fully rendered in a big canvas

### ISSUE THREAD

**Issue by Ch1pStar** [pixijs/pixi.js#3454]
Some very weird rendering behaviour can be seen when rendering in a big canvas, part of the image is getting cut off. From the testing I've done so far it looks like a mask effect. Here is an example - https://jsfiddle.net/6orhoonw/ (scroll down). 
Some notes so far(only tried it with canvas height for now, I'll test some more and post updates if I find something):
 - For pixi 4.0 the cutoff starts after the height gets >~8000(for pixi 3.0 it starts after >~18000)
 - Container nesting doesn't seem to affect this
 - Rendering to a texture doesn't change anything as well
 - Rendering the same image using only WebGL works fine

**Comment by staff0rd** [comment]
@Ch1pStar thanks for this report!

Reduced, pointed at latest, added both renderers; https://jsfiddle.net/k3xebfot/

@themoonrat Looks like webgl to me

**Comment by themoonrat** [comment]
Ah, well op reported canvas performance being the issue! Device/browser effected?

**Comment by Ch1pStar** [comment]
@themoonrat I observed this on chrome 55 initially, but its the same in firefox and ie 11 all on desktop. On a galaxy s4 with android 5.1 and chrome the image is not cut off but the top border is stretched. My guess would be a gpu buffer memory issue.

**Comment by GoodBoyDigital** [comment]
Hey chaps! wandering if there is much we can do here? Unless I'm mistaken - seems like this issue is out of our control?

**Comment by Ch1pStar** [comment]
@GoodBoyDigital This is quite the corner case and probably not worth the time investigating. As noted in my original post this image can be rendered properly using WebGL only, plus the inconsistent behaviour with different versions means it is most likely an issue with PIXI.

**Comment by englercj** [comment]
I'm almost positive there isn't anything we can do here. huge canvases are hard because they aren't natively supported by most (any?) GPUs so you have to do some crazy software emulation to get it to work (none of which we can control in pixi).

Closing this one!
