### ISSUE TITLE
How to use Mesh.Plane ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3456]
I see the doc says :
>  The Plane allows you to draw a texture across several points and them manipulate these points.

But how to manipulate these points?

I read the source , but can't find the way.
 I know how to do that for Rope , but I've no idea for Plane.

**Comment by finscn** [comment]
If control plane.vertices directly , when texture changed , the vertices will be reset.

**Comment by ivanpopelyshev** [comment]
Then modify it that way it respects "texture.rotate", and modify that texture rotation.

**Comment by finscn** [comment]
Sorry，
"Then modify it that way it respects "texture.rotate", and modify that texture rotation."
I can't understand this sentence ， because of my bad English
