### ISSUE TITLE
Base Texture Resolution Issue (0.5 when should be 1)

### ISSUE THREAD

**Issue by megmut** [pixijs/pixi.js#3458]
After Updating from 4.1.0, to 4.2.3, the textures are all double the size they should be when the device pixel ratio is 1. This still works fine when it is 2. When creating a new PIXI.Texture, if I log the resolution in either the constructor or in BaseTexture.prototype.update
    -- DPR1 --
    console.log(mySprite.texture.baseTexture.resolution) = 0.5
    -- DPR2 --
    console.log(mySprite.texture.baseTexture.resolution = 2

After much digging around in the BaseTexture, BaseRenderTexture and RenderTexture (constructors or update prototype), I am unable to find the source of this. If I am to console.log the resolution set in the BaseTexture, it shows as 1. I can't find where the resolution is being overriden, and I have tried overriding it myself by setting (mySprite.texture.baseTexture.resolution - 1) however this has no effect at all.

I even tried adding the src@1.png to my atlas's in an attempt to override this. Just as a note, this works fine for every version prior to 4.2.X.

**Comment by staff0rd** [comment]
I'm struggling to remember how/where I discovered something similar, but I did and the issue was due to #3297.  Looking in my generated sprite sheets json, I strangely found (can't remember how I generated it or what tool I used) something like this;
~~~
"meta": {
    "image": "myspritesheet.png",
    "size": {"w":972,"h":1780},
    "scale": "0.5"
}
~~~

I'm not sure how the `0.5` got there in scale but switching it to `"1"` magically solved this problem for me, as it wasn't until #3297 that PIXI was referencing that field.

**Comment by staff0rd** [comment]
Found it - it was a [codepen](https://codepen.io/staff0rd/pen/PGPgXr?editors=0010) for [this issue](https://github.com/pixijs/pixi.js/issues/2748#issuecomment-264641320) that broke (was pointing at latest pixi) so to fix it I did [this](https://github.com/staff0rd/pixi-tilesprite/commit/1393a4075971e6b010cfffd915406b1f00eb3329).

Prior to the fix the left side images were displayed in double size.

**Comment by megmut** [comment]
You are right, we found the issue much later last night. I don't know why PIXI is parsing the scale object in the texture packer json file, but I think it probably shouldn't be. Now I have to make sure I manually update all my textures after exporting them :(

Thanks for taking the time to find the issue! Do we leave this as open for the dev's to fix or close this?

**Comment by staff0rd** [comment]
Considering @GoodBoyDigital [set it](https://github.com/pixijs/pixi.js/pull/3297/commits/6a7a6c57a57b4d1a99d5c6accf012d32ef429908), I'm assuming he knows why its like that, so I'll close.

**Comment by bigtimebuddy** [comment]
This was changed recently to respect the spritesheet's internal scale. Previous this was ignored and the only way to specify the resolution/scale was with the name of the file "whatever@2x.png". There was a need to support both scenarios. 

I think one way we could support this situation (filename is set but also has a defined non-1 scale value), Would be to return `null` with `getResolutionOfUrl` if no value is available on the file suffix. This would allow us to prioritize the filename resolution over the internal resolution. 

What do you think @staff0rd?

**Comment by staff0rd** [comment]
Doesn't affect me - I don't use the scale normally, it was TexturePacker that set it for a demo spritesheet, and I don't otherwise use TexturePacker.  Perhaps @megmut has some thoughts.

**Comment by megmut** [comment]
When you export 3 sizes, you start with x3, then x2, then x1.. but the images you place in there are always at x3. So @3x would be scale = 1, @2x would be scale 0.6333 and @1 would be 0.3333. This doesn't make sense to me. Using the Texture Packer scale to determine the resolution for the baseTexture only works if you are using @1x scale. 

I like the functionality to read of getting the resolution from the texture packer JSON file, however as it completely breaks a game if everything doesn't go according to plan, could we pass an option to read resolution from the JSON file, or better yet.. for us to pass our own resolution and  that gives the ability to read and interpret the JSON file up to the developer?

**Comment by bigtimebuddy** [comment]
What I'm suggesting is to always prioritize the filename resolution (e.g. @2x). If that isn't set at all, fallback to the `scale` set in the JSON. Otherwise, resolution of `1`.

The current implementation reads the filename but defaults to `1` and then overrides with the JSON `scale` if it's defined and not `1`.

**Comment by megmut** [comment]
Okay, that sounds good! Thanks for the support guys, my first bug submit here 😄

**Comment by bigtimebuddy** [comment]
@megmut thanks for helping to make Pixi better. I'll put together a PR for this.

**Comment by bigtimebuddy** [comment]
@megmut Here's the build with that fix. Would appreciate it if you could verify that it works as expected: http://pixijs.download/fix-spritesheet-resolution/pixi.js

**Comment by megmut** [comment]
I can't import your code directly as my project doesn't run from an already bundled pixi.js. I'm importing the classes on build with webpack and typescript. If you like, you could just give me the source of the class you changed and I can update my local build, fix the typings if need be and let you know :)

**Comment by bigtimebuddy** [comment]
Thanks, that'd be helpful.
