### ISSUE TITLE
PIXI undefined

### ISSUE THREAD

**Issue by jmbaron** [pixijs/pixi.js#3462]
n vote
favorite
I am using pixi.js to learn about HTML5 game development. When using this line of code

var bunny = new PIXI

I get an undefined error saying that PIXI isn't defined.

Here is my HTML

```html
<!doctype html>
<head>
    <title>PixiJS</title>
    <meta charset="UTF-8">
</head>

<body>


<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.2.2/pixi.min.js"></script>
<script src="index.js"></script>
</body>
```

**Comment by ivanpopelyshev** [comment]
Missing <body> tag, missing <html> tag. "isn't defined" or "isn't a constructor" ?

**Comment by bigtimebuddy** [comment]
Hey @jmbaron if you're getting started with PIXI, you might want to check out the examples:
http://pixijs.github.io/examples/

This includes some javascript examples of things to do with PIXI. Also, here's an HTML template you can use.

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>PixiJS</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.2.2/pixi.min.js"></script>
</head>
<body>
  <script src="index.js"></script>
</body>
</html>
```

**Comment by ivanpopelyshev** [comment]
And this book too: https://github.com/kittykatattack/learningPixi

**Comment by themoonrat** [comment]
Closing as I believe the question has been answered :)
