### ISSUE TITLE
Rendering performance is worse compared to v3.0.11 (Samsung devices)

### ISSUE THREAD

**Issue by artvinn** [pixijs/pixi.js#3463]
Hey guys!

I've noticed a significant difference in FPS between v3 and v4. I did the tests on Samsung Galaxy Tab 3, WebGL specifically. Please check two examples I prepared:

[Pixi.js v3.0.11](http://zenext.github.io/demos/performance/v3/)
[Pixi.js v4.2.3](http://zenext.github.io/demos/performance/v4/)
[Source](https://github.com/Zenext/Zenext.github.io/blob/master/demos/performance/v4/src/Main.js)

Basically what is happening there is that 10 sprites with 5 different textures are getting rendered. In v3 it's steady 60 fps while in v4 it's 40. I also did test this on different iPads and no such issue there. I also encountered periodic WebGL crashes(Rats! WebGl hit a snag) on many Samsung devices after switching to version 4, especially if cacheAsBitmap used a lot. I think those issues are connected.

Any ideas on what could go wrong? :)
Thanks!

**Comment by themoonrat** [comment]
Hi @Zenext 

Could you try a couple of things for me please?
Firstly: If you change to canvas rendering only, how does the performance compare between 3.0.11 and 4.2.3 on your device?
Second: Does the performance difference show up in our bunnymark test? https://pixijs.github.io/bunny-mark/
Finally: With your test, try
`PIXI.settings.SPRITE_MAX_TEXTURES = 1;`
Before creating the PIXI renderer, and let us know how that effects v4.2.3 performance.

Thanks!

**Comment by Zenext** [comment]
1) This device doesn't perform well at all when in canvas, both in v3 and v4 it is like 5-10 fps.
2) With 5000 bunnies it runs at 6-8 fps in v3 and 2-3 fps in v4.
3) For this test it did the thing and fps is 60 now. But in game itself it makes no difference for some reason.

**Comment by Zenext** [comment]
By the way, what does the `SPRITE_MAX_TEXTURES` do?

**Comment by ivanpopelyshev** [comment]
@Zenext larger batches, multitexturing. Moving some work on GPU side.

**Comment by GoodBoyDigital** [comment]
Hello! would you mind adding the following before creating your webGL renderer:

```
PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;//window.OPTIMIZE;
PIXI.settings.SPRITE_MAX_TEXTURES = 1;
```

Let me know how that goes!

**Comment by FFankias** [comment]
Hi

PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;
PIXI.settings.SPRITE_MAX_TEXTURES = 1;
settings didn't help, game performance result is the same.

**Comment by FFankias** [comment]
update

The problem was with PIXI.settings.SPRITE_MAX_TEXTURES = 1;   

SpriteRenderer ignores it.
`        // step 1: first check max textures the GPU can handle.
        this.MAX_TEXTURES = Math.min(gl.getParameter(gl.MAX_TEXTURE_IMAGE_UNITS), SPRITE_MAX_TEXTURES);

        // step 2: check the maximum number of if statements the shader can have too..
        this.MAX_TEXTURES = (0, _checkMaxIfStatmentsInShader2.default)(this.MAX_TEXTURES, gl);
`

the new change https://github.com/pixijs/pixi.js/pull/3630 where legacy added mode sorts it out

**Comment by ivanpopelyshev** [comment]
@Zenext whats your email? wanna send you invite in pixi slack )

**Comment by Zenext** [comment]
@ivanpopelyshev artjomvinnikov@gmail.com
