### ISSUE TITLE
mouseup should check for originalEvent target

### ISSUE THREAD

**Issue by andrevenancio** [pixijs/pixi.js#3466]
This might be very specific, but imagine this scenario:

You have a fullscreen canvas with a `DisplayObjectContainer` with some background.
If I add the `mouseup` event to it, when I "click" on it it fires normally as it should.

However,
If I add a `domElement` occupying a certain area of my fullscreen canvas and click on it, I expect that the event will not fire inside pixi because I clicked on another element not the `<canvas>` itself.

What happens is that the element does fire, and I could fix this in 2 ways

a)
compare the `e.data.originalEvent.target` of the event and if its not a `<canvas>` element proceed with the rest of my logic. Otherwise if its a `<canvas>`, return.
```
foo.on('mouseup', (e) => {
    // mouse up detected
    // check the original event target to see if it was a canvas 
    if (e.data.originalEvent.target.nodeName !== 'CANVAS') {
        return;
    }
    // if you do click on a canvas handle some logic.
});
```
Now, this creates a problem. the test will always pass if you click on a canvas element.
The test should check if you clicked on the domElement used on the pixi renderer.

b)
store a global reference to the renderer domElement and explicitly compare it.

Any ideas @GoodBoyDigital ?

**Comment by andrewstart** [comment]
I think that the `mouseup` event should still fire - the canvas got a mouseup event. It shouldn't fire a `click` event because the complete mousedown->mouseup interaction did not happen on the canvas, which should already be the case.

**Comment by andrevenancio** [comment]
I think you got it wrong. I'm not expecting a click event. but i'm not expecting a mouseup event either. the "clicked" area is outside of the canvas so the mouseup should not fire. I think the listeners in pixi might be attached to the window not to the domElement. so regardless of where you click you'll always get a mouseup and you shouldnt. imagine this: you have ur window.innerWidth at 800px, if your canvas is on the left and it only ocuppies 400px, if you click on the right at 500px the mouseup still fires. it shouldnt :)

**Comment by andrevenancio** [comment]
Is there a reason you guys remember this is attached to the window? 
https://github.com/pixijs/pixi.js/blob/7656cd94244c66a6377c3a69761ef63b975b9b25/src/interaction/InteractionManager.js#L549

**Comment by andrevenancio** [comment]
Do you guys remember why the `mouseup` event is attached to the window? @englercj @GoodBoyDigital ?

**Comment by andrewstart** [comment]
So that if one mouses down on the canvas, moves the mouse out of the canvas, and then releases, we know about it instead of having a hanging 'the mouse is down' state.

**Comment by andrevenancio** [comment]
I suspect that that's how the `mouseupoutside` works. and that's fine. I'm 100% with you on that one @andrewstart. That behaviour should be expected and covered. However, from the several examples I've described above, the `mouseup` should have one behaviour and the `mouseupoutside` should have another.

For your example all you would need to do is listen to `mousedown` and `mouseupoutside` on the canvas. Not the `mouseup` :)

**Comment by andrevenancio** [comment]
![tumbleweed](http://stream1.gifsoup.com/view4/1158287/tumbleweed-o.gif "zzZzzzZzZ")

**Comment by andrevenancio** [comment]
4 months later lol :)
