### ISSUE TITLE
【Share】A new Animation Class for PIXI.js

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3469]
There is a demo of my new Animation  Class : 
http://fattyboy.cn/anim/

source code :  https://github.com/finscn/pixi.js/blob/v4-plus/src/extensions/Animation.js

The features of  my new Animation : 
* It's a normal Class  , not the subclass of DisplayObject. it doesn't do anything about rendering.
* We could apply Animation feature to any display object with texture , e.g. Sprite , Rope.
* We could add an animation object to a Sprite/Rope via `bind`.
* We also could let a  Sprite/Rope become a animation object  via `applyTo` & `initAnimation`.
* It doesn't be auto-updated by core.ticker.shared. But if want to do it , it's very easy.
* It can implement any feature of  current AnimatedSprite (except `auto update by core.ticker.shared`) , even include time scaling & backward playing.
* There is a better & more clearly logic for updating animation than current AnimatedSprite.

I hope it could be a part of official PIXI.js .

BTW : 
* There are more discussions about animation at https://github.com/pixijs/pixi.js/pull/3429#issuecomment-265963396
* If we don't fix  the bug https://github.com/pixijs/pixi.js/issues/3453  , the demo can't run correctly.
* If  we don't remove  "no-unmodified-loop-condition" in eslint config , my class can't pass lint .
( see https://github.com/finscn/pixi.js/blob/master/src/extensions/Animation.js#L256 )
More detail see  the first suggestion in  https://github.com/pixijs/pixi.js/issues/3434

**Comment by finscn** [comment]
I hope pixi core team could consider this feature.   cc @ivanpopelyshev @staff0rd @bigtimebuddy @GoodBoyDigital 
 
A new animation (decouple with displayObject) is very necessary.
Animation should be a tool for `changing texture` , not a displayObject or Sprite.

**Comment by ivanpopelyshev** [comment]
Implemented in a plugin: https://github.com/gameofbombs/pixi-heaven#animation . It doesnt assign fields like you do, it works as a component.
