### ISSUE TITLE
Text align center doesn't work in v4.0.0

### ISSUE THREAD

**Issue by starInEcust** [pixijs/pixi.js#3476]
I used Graphics.line to draw a border for the Text. The code is as follows
```
  const textText = new Text('0 0 0 0 0 0 0', {
    fontSize: 18,
    fill: 0x000000,
    align: 'center',
  });
  textText.y = -100;
  line.x = textText.x;
  line.y = textText.y;
  line.moveTo(0, 0);
  line.lineTo(textText.width, 0);
  line.lineTo(textText.width, textText.height);
  line.lineTo(textText.x, textText.height);
  line.lineTo(0, 0);
```
![image](https://cloud.githubusercontent.com/assets/5434131/21284786/8e4aecfe-c461-11e6-8cd3-3db4b789a7a0.png)

The rendered word is not centered. More blank areas to the right. And I do not know how to get the width of this blank area. I also found that Text.height is not the true height of the text,  but I don't know how to get the height of the blank area (above and below texts ).

version: 4.0.0

**Comment by themoonrat** [comment]
If you set the x anchor of the text to 0.5 i believe you'll achieve what you want :)

**Comment by starInEcust** [comment]
@themoonrat There are some fonts that do not appear in this case,
So I do not know when to use your method

**Comment by themoonrat** [comment]
If you could create a jsfiddle or codepen demonstrating your issue that would help us a huge amount, thanks!

**Comment by starInEcust** [comment]
@themoonrat 
The code only has different font-family

https://jsfiddle.net/starCoding/p49u34hd/4/

![image](https://cloud.githubusercontent.com/assets/5434131/21749528/f6361d2c-d5da-11e6-826b-6ec2171d16b9.png)

**Comment by staff0rd** [comment]
I've opened PR #3565 as a possible solution.

Note that if that PR doesn't get accepted, you can just extend PIXI.Text to have the same functionality as the PR as i've done here with a `TrimmedText` class; https://codepen.io/staff0rd/pen/NdxGag?editors=0010

@starInEcust here's your fiddle pointing at the PR's changeset; https://jsfiddle.net/4h4otaeb/
