### ISSUE TITLE
Default Anchor

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#3477]
I'd like to set the anchor of every sprite ever to (0.5, 0.5).

How can I do this?

**Comment by staff0rd** [comment]
How about extending Sprite to have your functionality?
~~~javascript
class CenteredSprite extends PIXI.Sprite {
  constructor(texture) {
    super(texture);
    this.anchor.set(0.5);
  }
}
~~~

https://codepen.io/staff0rd/pen/zoexVP?editors=0010

**Comment by DubiousDillan** [comment]
That works- thank you!
