### ISSUE TITLE
[BUG] There is a bug when use Blur & Displacement filters together.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3478]
Blur is OK
Displacement is OK.
But when I turn on them both , the background would not be clean.

I use Chrome 55 for mac. 

<img width="767" alt="2016-12-17 9 38 00" src="https://cloud.githubusercontent.com/assets/288367/21287213/3eb73504-c4a1-11e6-9373-a7de5b5c6ae0.png">
<img width="773" alt="2016-12-17 9 38 07" src="https://cloud.githubusercontent.com/assets/288367/21287216/40ac466a-c4a1-11e6-81cc-1f161f9b1386.png">
<img width="743" alt="2016-12-17 9 37 50" src="https://cloud.githubusercontent.com/assets/288367/21287217/430f2526-c4a1-11e6-8e56-53fafa0e0677.png">

**Comment by Rubyroidas** [comment]
Video card is also important. For example, on AMD Radeon behaviour is different: there are bugs often present. On NVIDIA it's usually ok.

**Comment by finscn** [comment]
I  test it on  Chrome for Android 6.0 ( many devices with different APUs )   ,   Safari for iOS ,  Safari for macOS (Intel HD & AMD Radeon GPU) .  The results are same. 

So I think this issue is not about GPU.

**Comment by GoodBoyDigital** [comment]
hey all! #3525 should fix this!

**Comment by finscn** [comment]
@GoodBoyDigital  , thanks .

 I hope it could be merged as soon as possible .
