### ISSUE TITLE
Uncaught TypeError: PIXI.filters.NoRedFilter is not a constructor(…)

### ISSUE THREAD

**Issue by RealMakAttak** [pixijs/pixi.js#3481]
Hello Friends,

I hope you can help me, I have been trying for a solid day to understand why this is happening!

I am following this article here to try and create a custom filter:

https://developer.tizen.org/community/tip-tech/creating-pixi.js-filters-using-webgl

In the end I put in to my file exactly what they have from the example:

function NoRedFilter() {
  var vertexShader = null;
  var fragmentShader = [
    'precision mediump float;',
    '',
    'varying vec2 vTextureCoord;',
    'uniform sampler2D uSampler;',
    '',
    'void main(void)',
    '{',
    '    vec4 pixel = texture2D(uSampler, vTextureCoord);',
    '    pixel.r = 0.0;',
    '    gl_FragColor = pixel;',
    '}'
  ].join('\n');
  var uniforms = {};

  PIXI.AbstractFilter.call(this,
    vertexShader,
    fragmentShader,
    uniforms
  );
}

NoRedFilter.prototype = Object.create(PIXI.AbstractFilter.prototype);
NoRedFilter.prototype.constructor = NoRedFilter;

But all I get is, no matter what I do:

**Uncaught TypeError: PIXI.filters.NoRedFilter is not a constructor(…)**

I changed the above code from AbstractFilter to just Filter but it persists. The only thing I could think is that the tutorial is using Pixi v3 and I'm using the latest v4...but would this affect the creation of a constructor?

Please help me! and my hair! Thanks.

**Comment by giraluna** [comment]
You're defining `NoRedFilter`, not `PIXI.filters.NoRedFilter`. Try calling `new NoRedFilter()` instead.

**Comment by RealMakAttak** [comment]
@giraluna That worked, thank you very very much
