### ISSUE TITLE
Layout engine / dynamic positioning

### ISSUE THREAD

**Issue by endel** [pixijs/pixi.js#3482]
Is there some library in the community that allows composing elements into a specific layout?

Something similar to https://github.com/facebook/yoga

Thanks!

**Comment by ivanpopelyshev** [comment]
There is https://github.com/pixijs/pixi-ui , its port of Unity NGUI. No docs yet, but we can ask @bQvle

**Comment by bQvle** [comment]
just updated with the latest changes, its not a direct port of NGUI, but the current features is inspired from it. Please look at the examples in the "Test" directory. 

Since its in a pretty early stage, every update might break stuff because I'm not doing any deprecation handeling yet.

**Comment by endel** [comment]
Thanks @bQvle @ivanpopelyshev. Nice lib. I actually wanted something simpler than that, though. 

Just positioning and resizing without having to manually compute everything. I often find myself writing UI's like this:

```
function resize () {
  right.position.x = window.innerWidth - element.width - MARGIN;
  left.position.x = MARGIN;
}
document.addEventListener("resize", resize);
```

On this example, the same result could be achieved by creating a container and setting a `padding` value to it.

So maybe a port of yoga for Pixi would be a great thing. :)

**Comment by bigtimebuddy** [comment]
@andrewstart and I created a UI resize plugin within a larger framework called SpringRoll. You might be able to modify this for your needs. https://github.com/SpringRoll/SpringRoll/tree/master/src/ui

**Comment by themoonrat** [comment]
closing: a couple of options have been given :)
