### ISSUE TITLE
cacheAsBitmap not working properly for nested elements

### ISSUE THREAD

**Issue by sivael** [pixijs/pixi.js#3485]
Hi.

I'm working on a component using pixi and am encountering a weird issue as illustrated here:

https://codepen.io/sivael/pen/rWPwpg?editors=0011

Basically when I do a pixi equivalent of:
```
<scene>
  <g>
    <g x:10 y:10 ::cachethis>
      <roundedBox />
      <text>1,1</text>
    </g>
  </g>
</scene>
```
All works well, and there's no issues with cacheAsBitmap. (the green boxes in example)

BUT when I do:
```
<scene>
  <g>
    <g x:10 y:10>
      <g  ::cachethis>
        <roundedBox />
        <text>1,1</text>
      </g>
    </g>
  </g>
</scene>
```

Then anything beyond the first box doesn't render properly(the red boxes example)

It looks like the function call to:
` m.invert()`
caused my 
`m.tx = -3999.5`

And that prevented the proper rendering of the component.

Note, however, that canvas has the following code:
```    m.invert();

    m.tx -= bounds.x;
    m.ty -= bounds.y;
```

while webGL has this:
```var m = _tempMatrix;

    m.tx = -bounds.x;
    m.ty = -bounds.y;
```

Now the implementations are probably different, and changing canvas to
```    m.invert();

    m.tx = -bounds.x;
    m.ty = -bounds.y;
```
actually breaks the rendering of green elements while fixing reds.

Any ideas?

**Comment by FFankias** [comment]
https://github.com/pixijs/pixi.js/pull/3366

**Comment by sivael** [comment]
It doesn't fix the issue - that change only makes the currently working properly elements stop working.

**Comment by sivael** [comment]
#3494 I've made a PR to fix all use cases.
