### ISSUE TITLE
[Request] Mesh Plane supports polygon border/edge.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3486]
Current Mesh Plane only supports  rectangle border/edge.

I hope it could support polygon border/edge , like this : 
<img width="484" alt="2016-12-19 5 54 11" src="https://cloud.githubusercontent.com/assets/288367/21308287/499bc722-c614-11e6-8a80-93bff9b51d79.png">

@ivanpopelyshev ， Is it feasible ？

**Comment by finscn** [comment]
I know ， in fact it's also rectangle border，it just hides the points out of edge/border

**Comment by ivanpopelyshev** [comment]
It doesn't support polygon packing yet, but @mat is working on it.

**Comment by GoodBoyDigital** [comment]
Hello! Closing this one for now as this request can already be found here: #2243

Cheers!
