### ISSUE TITLE
`DisplayContainer.visible` omitted from the documentation

### ISSUE THREAD

**Issue by NoiSek** [pixijs/pixi.js#3489]
http://pixijs.download/release/docs/PIXI.DisplayObject.html
http://pixijs.download/release/docs/PIXI.Container.html
http://pixijs.download/release/docs/PIXI.Sprite.html

I've been able to find the implied existence of the `.visible` property from #2795 , #3388 , and a forum thread while searching around for how to accomplish viewport culling in Pixi.js, but the documentation itself doesn't appear to mention this anywhere.

It is also not covered in the examples.

Is this feature not actually intended to be part of the published API, or is this a legitimate documentation error?

**Comment by themoonrat** [comment]
It's part of the same issue as https://github.com/pixijs/pixi.js/issues/3416
alpha doesn't show either, for example. 
Members do not show, but getters do show

**Comment by staff0rd** [comment]
Dupe #3416
