### ISSUE TITLE
.height and .width properties return scale rather than height and width

### ISSUE THREAD

**Issue by KosGrillis** [pixijs/pixi.js#3490]
Trying to access the height and width properties of a sprite gives the scale of the sprite, rather than the height or width in pixels.

Here's a segment of the code where I discovered the issue:

`var inputDependencySprite = PIXI.Sprite.fromImage(OperationInstance.inputDependencyPath);`
`inputDependencySprite.interactive = true;`
`inputDependencySprite.anchor.set(0.4, 0.5);`
`inputDependencySprite.scale.set(0.12, 0.12);` 
`inputDependencySprite.position.set((mousePosition.x - backgroundSprite.width/1.75), mousePosition.y);`
`inputDependencySprite.visible = false;`
`console.log(inputDependencySprite.height);`
`console.log(inputDependencySprite.width);`

This logs 0.12 to the console twice, which are the scale values. If I removed the line where I set the scale, 1 is logged to the console twice.

**Comment by themoonrat** [comment]
I'm going to take a guess that the texture you are using for the Sprite hasn't been pre-loaded? Because if not, then the default frame size of the texture and sprite will be 1 by 1, and thus any changes to scale will cause the width and heights to match them.

**Comment by KosGrillis** [comment]
I haven't pre-loaded the texture, I only used the .fromImage() method. If I use PIXI.Loader to load the texture and then create the sprite using this texture, I'll be able to access width and height in pixels? And if I scale the Sprite I'll get the new scaled height and width?

**Comment by themoonrat** [comment]
If you want to find out the width and height of a sprite immediately after creation, then preloading is required - pixi needs that texture to be loaded to give you the information you require.

**Comment by KosGrillis** [comment]
I added the line console.log(bunny.height) on line 12, after the texture was loaded, and it still logged 1 to the console.

**Comment by themoonrat** [comment]
But at that point the texture hasn't been loaded. It has been _requested_ to be loaded, but that fromImage is asynchronous... after that call, in the background the image is being loaded.

If you put the logging at say line 27, you'd see how width would be logged as 1 for a small period, before then returning it's proper width. The point it changes away from being 1 is when the texture has finally been loaded :)

**Comment by KosGrillis** [comment]
Is there anyway to run the loader synchronously? The whole execution of my program depends on the height and width of my texture, so I need to wait until the texture is loaded before I can proceed.

**Comment by staff0rd** [comment]
@KosGrillis 
~~~javascript
PIXI.loader.on("complete", () => {
    // do something with my loaded assets
});
~~~
[This](https://github.com/englercj/resource-loader) also suggests;
~~~javascript
PIXI.loader.load((loader, resources) => {
  // do something with resources["mytexture"]
});
~~~

**Comment by KosGrillis** [comment]
oops, I meant running the Texture.fromImage() function synchronously

**Comment by staff0rd** [comment]
You could look into listening to a loaded event on the BaseTexture, but if you need your textures beforehand then you should use the loader instead of fromImage
