### ISSUE TITLE
How to move a Sprite after rotated in the new rotation coordinate system?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3492]
```
sprite.rotation = Math.PI / 4;
var offsetX = 10;
sprite.position.set( x+ offsetX , y);
```
in this test case , the sprite will move by offsetX  in original coordinate system.

If I want to move it in  rotated coordinate system , how should I do ?

In native canvas 2d , I could do something like this  : 
```
context.save();
context.translate(x, y)
context.rotate(Math.PI / 4);
context.drawImage(img, offsetX , 0);
context.restore();
```

**Comment by ivanpopelyshev** [comment]
There's also a pivot

```js
sprite.pivot.set(-offsetX, 0);
```

**Comment by finscn** [comment]
In my opinion,  `pivot`  is similar to `anchor` , it's another anchor in pixel nearly.  
It shouldn't be used for moving, though it can do.

Am I wrong ?

**Comment by finscn** [comment]
And There is an similar question about scale : 

How to do something like this : 
```
context.save();
context.translate(x, y);
context.scale( 0.5, 0.6);
context.rotate(Math.PI / 4);
context.scale( -0.7, 0.8);
context.drawImage(img, 0, 0);
context.restore();
```
The core of this question is about the order of `scale rotate translate`.

**Comment by ivanpopelyshev** [comment]
in pixi Transform its ```translate rotate skew scale pivot" , but you can make your own Transform class. For example, Spine Transform has an option to ignore scale or rotation of parent :)

**Comment by hustcc** [comment]
I write a [pixi-action](https://github.com/hustcc/pixi-action) plugin, inspired by cocos2d-x action API. May can help you.

@ivanpopelyshev `skew` attribute is not exist in v4.3.0 ?

**Comment by ivanpopelyshev** [comment]
@hustcc Look at examples and try "bunny.skew.x = 0.4". http://pixijs.download/release/docs/PIXI.DisplayObject.html#skew

**Comment by hustcc** [comment]
@ivanpopelyshev I write a plugin named pixi-action, and a demo used v4.3.0, you can see [move action](http://git.hust.cc/pixi-action/res/html/move.html), in console, I log the `cat`(instance of sprite), there is no `skew` prop in it.

And in demo of [action skew](http://git.hust.cc/pixi-action/res/html/skew.html), it can not find the prop `skew` of cat (instance of Sprite).

**Comment by ivanpopelyshev** [comment]
![Skew there is](https://monosnap.com/file/DK5ukDtGjw1FCbDIAJf9OR658RoQq9.png)

**Comment by hustcc** [comment]
It is ok, it can run. https://github.com/pixijs/pixi.js/issues/3500 .

**Comment by ivanpopelyshev** [comment]
I'm closing this.
