### ISSUE TITLE
pixi-action plugin & document offline

### ISSUE THREAD

**Issue by hustcc** [pixijs/pixi.js#3493]
Where I can download the document file of [http://pixijs.download/release/docs/index.html](http://pixijs.download/release/docs/index.html), Then I can read it offline, I came from China, because of the GFW, the online document can not open something, and so slow.

**Comment by themoonrat** [comment]
npm run docs

On a local copy of the repo will generate the docs you require for offline use

**Comment by hustcc** [comment]
Got it! 
![image](https://cloud.githubusercontent.com/assets/7856674/21376213/1b7be146-c76e-11e6-9fdf-5da9d5dfb247.png)

Other question:

**Is there a plugin to write animation easily just like cocos2d-x**, such as:

```js
sprite1.moveTo(100, 200, 2); // sprite1will move to (100, 200) in 2 sec.

// or
animate1 = ...; // an animate1 action
animate2 = ...; // another animate1 action
sprite2.runAction(cc.sequence(animate1, animate2).repeatForever()); // sprite2 will run action which contains animate1, animate2 forever.

```

**Comment by hustcc** [comment]
Just write one plugin for pixi to make animation easily, with simple api like cocos2d-x.

here is the code [https://github.com/hustcc/pixi-action](https://github.com/hustcc/pixi-action), and now only the code structure, and only actions: **MoveTo**, **MoveBy**.

Online demo here: [http://git.hust.cc/pixi-action/](http://git.hust.cc/pixi-action/).
