### ISSUE TITLE
I want to draw many many many points , Which is better ? image or glPoint?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3495]
I want to draw many  white round points to simulate snowing.
They have different `size`s and  `alpha`s  , but same color 0xffffff.

Use the shader like this : 
```

// Vertex shader program
var VSHADER_SOURCE = [
    'attribute vec4 aPosition;',
    'attribute float aSize;',
    'attribute float aAlpha;',
    'varying float vAlpha;',
    'void main() {',
    '  gl_Position = aPosition;',
    '  gl_PointSize = aSize;',
    // '  gl_PointSize = 20.0;',
    '  vAlpha = aAlpha;',
    '}',
].join('\n');

// Fragment shader program
var FSHADER_SOURCE = [
    'precision mediump float;',
    'varying float vAlpha;',
    'void main() {',
    '  float d = distance(gl_PointCoord, vec2(0.5, 0.5));',
    '  if(d < 0.5) {',
    '    gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0) * vAlpha;',
    '  } else {',
    '    discard;',
    '  }',
    '}',
].join('\n');

```
In theory ， Which one  has better performance ？ 
  `glPoint + size + alpha`    or   `image + PIXI.Sprite  + scale + alpha`  ？

I know I should test them , but I don't know how to use glPoint in PIXI.

**Comment by JiDW** [comment]
I would just just an image and a ParticleContainer. You can display easily 60.000 images at 60fps with the same texture this way.

**Comment by finscn** [comment]
@JiDW  thanks for your reply . 
If on PC ,  I think both ok ,  but if  on Android device  (released in 2015 ) ... I've no idea.

**Comment by finscn** [comment]
I test it . 
The performance is closely related to `point size` & `point alpha`.

For the case `simulate snowing` , point is better.

**Comment by ivanpopelyshev** [comment]
glPoint has some problems on some devices, that's why pixi-tilemap has both modes : rects and squares
