### ISSUE TITLE
Interaction manager breaks existing code to handle mousedown events

### ISSUE THREAD

**Issue by tobico** [pixijs/pixi.js#3499]
Hi, I recently updated my project to the latest PIXI (from a quite old version), and all of my mousedown handling (implemented through DOM events attached to the canvas element) broke, with mousedown events silently ignored.

Took me many hours to figure out this is a result of something called InteractionManager, and can be disabled by calling `renderer.plugins.interaction.destroy()` after creating the renderer.

Could I suggest that features like this that intrude on doing things the standard "HTML way" be opt-in instead of opt-out? I'm sure there's many great reasons to use the interaction manager over handling the events manually the way that I have, but that should be a choice when using the library rather than just having it bundled in.

**Comment by themoonrat** [comment]
If you don't need PIXI interaction, you can do a custom build that doesn't include it. 

npm run dist -- -e interaction

**Comment by chyde** [comment]
My problem was that Containers dont handle mousedown, but sprites and drawn graphics do

**Comment by themoonrat** [comment]
Containers should handle mousedown! :) Do you have a fiddle to demonstrate your issue please?

**Comment by chyde** [comment]
Did some experimenting and I think my issue was that my container did not have width or height,  Because I can get it to work in codepen...

**Comment by themoonrat** [comment]
Ok cool, will close this then. If you see any issues relating to this, just open up a new issue :)
