### ISSUE TITLE
Cannot read property 'utils' of undefined in Pixi.js plugin.

### ISSUE THREAD

**Issue by hustcc** [pixijs/pixi.js#3500]
The plugin pixi-timer run with pixi.js 4.3.0, can see: 

![image](https://cloud.githubusercontent.com/assets/7856674/21417277/5d6f428c-c854-11e6-97a1-c2abfafc0439.png)

because can not found PIXI object, v3.0.8 is OK.

**Are there something  specail in v4.3.0**, How to do with it ?

**Comment by hendrysadrak** [comment]
After importing PIXI and before importing `pixi-timer` try: 
```
window.PIXI = PIXI;
window.PIXI[ "default" ] = PIXI;
```
Fixed issuses for me with `pixi-audio`

![image](https://cloud.githubusercontent.com/assets/4000963/21418995/abbcb75c-c82d-11e6-8f25-517464251cda.png)

**Comment by hustcc** [comment]
If I use it with `script` tag to import the plugin, how to do with it ?

**Comment by hendrysadrak** [comment]
are you importing PIXI before `pixi-timer`?

**Comment by hustcc** [comment]
It works~ when use `script` tag to import the plugin.

```js
<script src="http://cdn.bootcss.com/pixi.js/4.3.0/pixi.min.js"></script>
<script type="text/javascript">
  window.PIXI = PIXI;
  window.PIXI[ "default" ] = PIXI;
</script>
<script src="../../build/pixi-action.js"></script>
```

But this is really not perfact, How to do something in the plugin source code to solve it.

**Comment by hendrysadrak** [comment]
try removing this line 
![image](https://cloud.githubusercontent.com/assets/4000963/21420438/66d4d8aa-c836-11e6-8a7a-441479f2cf3d.png)
in your ActionManager, maybe it helps

**Comment by hustcc** [comment]
Can not work, new error:
```
Uncaught TypeError: Cannot read property 'actionManager' of undefined
```
and 
```
move.html:24 Uncaught TypeError: Cannot read property 'MoveTo' of undefined
```

I have test `pixi-timer`, has same errors.

**Comment by hustcc** [comment]
How to solver it in plugin's source code, or need to do something in `pixi.js` 's code.

**Comment by englercj** [comment]
The correct import for pixi.js is `import * as PIXI from 'pixi.js';` Pixi has no default export.

**Comment by hustcc** [comment]
@englercj done.

replace all the `import * as PIXI from 'pixi.js';`, then OK.

last friday ,I just replace the code in `index.js`.
