### ISSUE TITLE
Problem with render when cacheAsBitmap and mask is used together

### ISSUE THREAD

**Issue by kiture** [pixijs/pixi.js#3505]
If inside container is element, which have set mask on it and this element position is not 0,0, then this element will be not rendered if we set '**cacheAsBitmap**' to true on the container wherein the element is located.

Link to example: http://codepen.io/kiture/pen/bByGKg

If we remove this line: 
_container.cacheAsBitmap = true;_
Then all works correctly.

**Comment by staff0rd** [comment]
Works as expected on canvas, not on WebGL
