### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [pixijs/pixi.js#3506]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of pixy.js (v 4.0.1) our tools detected approximately 206 unused function in dependencies. Removing those functions, the size of  pixy.js bundled could be reduced at least 10% (All tests passed). 
[pixi(optimized).txt](https://github.com/pixijs/pixi.js/files/671154/pixi.optimized.txt)
I’m attaching the reduced version of your project.
 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this kind of problem?

Thanks in advance.

Cheers,

**Comment by bigtimebuddy** [comment]
Since our unit tests are incomplete, how do you determine an "unused" function?

**Comment by GoodBoyDigital** [comment]
Poke @hcvazquez this sounds really cool! - any chance you could share with us how you achieved the above? Thanks!

**Comment by stbaer** [comment]
Isn't that exactly what for example webpack2 with tree shaking is tackling?

**Comment by englercj** [comment]
I'd like to know what the defeinition of an "unused function" is, or at least of a list of the functions you determined were "unused".

**Comment by GoodBoyDigital** [comment]
Hello! v5 uses rollup, should help out here 👍
