### ISSUE TITLE
How to render tow sprites with the same texture (but texture changed)?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3509]
I see in the Graphics of PIXI.js ,  when I render 2 fill-rects , they are use one texture `Graphics._SPRITE_TEXTURE`

the second graphics will change the content of texture ， but  2 fill-rects could be rendered correct.

But I do the same thing on sprite , it's failed.
* create a Texture from canvas
* draw something on canvas
* create  the first sprite with the texture
* draw other things on canvas (content of canvas changed)
* create  the second sprite with the texture
* render the sprites

there is only the  second be rendered.

**Comment by finscn** [comment]
I see. the `Graphics._SPRITE_TEXTURE` never been changed, it's a `placeholder`

**Comment by ivanpopelyshev** [comment]
We solved it by clearing _spriterect , right? Texture is never changed, its white square

**Comment by finscn** [comment]
@ivanpopelyshev  ， yes.    

Merry Christmas.
