### ISSUE TITLE
Is it possible to apply a stroke to a scene/container after rendering all my sprites?

### ISSUE THREAD

**Issue by TrentWDB** [pixijs/pixi.js#3516]
I'm looking to apply a stroke around every opaque part of a container after I've added all of my sprites. Any help or guidance would be appreciated - I assume that pixi compiles all sprites into some sort of a large image before rendering which should then make it possible to apply a global stroke to the image.

Thanks!

**Comment by RainingChain** [comment]
What you are looking for is a Outline filter.
https://github.com/pixijs/pixi-extra-filters/tree/master/src/filters/outline

**Comment by GoodBoyDigital** [comment]
@RainingChain is correct! HOpe that sorts you out!
