### ISSUE TITLE
Painting outside bounds with pixel shader

### ISSUE THREAD

**Issue by underdogkid91** [pixijs/pixi.js#3520]
hey ✌️ 

first, thanks to the pixi.js team and collaborators for making such a great rendering library 😊 ✨ i'm pretty new to shaders, so this might be a basic question.

i'm creating a `wave warp` filter. i started adding only a sine displacement, and the amplitude is a uniform. this is the fragment shader and how it looks applied to a sprite:

```
varying vec2 vTextureCoord;
uniform sampler2D uSampler;
uniform float amplitude;
void main(){
  vec2 p = vTextureCoord;
  p.x = vTextureCoord.x + amplitude * sin(vTextureCoord.y * 30.0);
  vec4 texture = texture2D(uSampler, p);
  gl_FragColor = texture;
}
```

![image](https://cloud.githubusercontent.com/assets/17030477/21529656/64cde344-cd3b-11e6-93e3-bb7a1f72e481.png)

problem is, of course this is not painting outside of the bounds defined by the vertexes. i would need to make the bounds increment as much as the amplitude.

how can i address this? should i create my own vertex shader? do i need to edit *some matrix something* in my sprite?

thanks!

**Comment by GoodBoyDigital** [comment]
Hi @underdogkid91 ! you are most welcome :)

Cropping and modifying the vertex data is a little outside of how the filters work at the moment.

For this kind of effect I would recommend you use a ```PIXI.mesh.Plane```. Then you can modify the vertices to be all bendy and they will move the image in a way you require.

Hope that helps!
