### ISSUE TITLE
AnimatedSprite in reverse

### ISSUE THREAD

**Issue by iggyZiggy** [pixijs/pixi.js#3522]
v4.3.0

I'm unable to make it work, tried:

1) setting animationSpeed in negative value
2) creating new animatedSprite using reverse array of frames
3) switching 2 sprites with add/remove child and with visible true/false
Always the same animation plays

**Comment by themoonrat** [comment]
Option 2 is the one to take, and it does work

If I go to the examples page at https://pixijs.github.io/examples/#/basics/spritesheet.js
and add
`frames.reverse();`
on line 25, then the aircraft spins the opposite way as expected

**Comment by iggyZiggy** [comment]
Not sure why it didn't work with 2 animated sprites, i have used single sprite and set negative animationSpeed on last frame, that made it work. Maybe problem was somewhere else, if I notice the same issue again i'll reopen and add more info

**Comment by iggyZiggy** [comment]
keep it closed, just wanted to drop this line here for next time, don't know how i keep getting back to this one all the time:
```
self.body.animationSpeed = -Math.abs(self.body.animationSpeed);
```
