### ISSUE TITLE
glDrawElements: range out of bounds for buffer

### ISSUE THREAD

**Issue by goldenratio** [pixijs/pixi.js#3524]
```
[.Offscreen-For-WebGL-000001BF031B5C60]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
```
Can some please help me, why this happens?
I rendering lots of PIXI.Sprite in PIXI.Container and some of the sprites are outside canvas visible area.

I also found a similar issue,
https://github.com/pixijs/pixi.js/issues/1409 which seems to happen in version 4.3.0 (both release and dev)

**Comment by Armegalo** [comment]
Are you using particle containers with limited sprite allowance (have you limited them or not set them higher than the default?)
