### ISSUE TITLE
Bug with TilingSprite anchor behaviour

### ISSUE THREAD

**Issue by RainingChain** [pixijs/pixi.js#3536]
Changing the anchor of a TilingSprite causes the tiling to be misplaced in 4.x using WebGL.
In 3.x or 4.x with Canvas, the Tiling would stay the same. The sprite would be positioned and rotated relative to the anchor like one would expect.

Drawing a circle TilingSprite in 4.x with WebGL with anchor at (0.5,0.5):
![](https://puu.sh/tawEN.png)

Drawing a circle TilingSprite in 3.x (or 4.x with Canvas) with anchor at (0.5,0.5):
![](https://puu.sh/tawI1.png)

This behaviour is important when drawing textures such as a rope.

Behaviour in 4.x WebGL:
![](https://puu.sh/tawQw.png)

Comment/uncomment <script> tag to load 3.0.7 or use PIXI.CanvasRenderer to see how it used to be.
https://jsfiddle.net/Lfozgwfd/

**Comment by staff0rd** [comment]
Thanks for this report, definitely looks like a bug.  I reduced the fiddle a bit, pointed it at latest and included both renderers; https://jsfiddle.net/mb6b808c/

**Comment by themoonrat** [comment]
Interesting that at anchor.set(0) and anchor.set(1) canvas and webgl both match up. It's the bits in between where it goes wrong
