### ISSUE TITLE
Wrong calculation in colorMatrix.frag

### ISSUE THREAD

**Issue by hajimehoshi** [pixijs/pixi.js#3539]
As for 'translation' part, I guess

```frag
        gl_FragColor.r += m[4] * c.a;
```

should be

```frag
        gl_FragColor.r += m[4];
```

, shouldn't it? m[8], m[12] and m[16] are in the same situation.

**Comment by GoodBoyDigital** [comment]
same for this one, if you could submit a PR fixing the above issue that would be great. Thanks!

**Comment by andrewstart** [comment]
I don't know that that should be fixed - we specifically made that change in https://github.com/pixijs/pixi.js/pull/2397.

**Comment by hajimehoshi** [comment]
Hmm? I was wondering whether ColorMatrix is applied to pre-multiplied alpha colors or non-pre-multiplied alpha colors.

**Comment by andrewstart** [comment]
Given my tests at the time, it appears that it is applied to pre-multiplied colors, regardless of the pre-multiplied alpha setting of PIXI.

**Comment by hajimehoshi** [comment]
So, IMO multiplying alpha to premultiplied color in #2397 doesn't make sense.

**Comment by GoodBoyDigital** [comment]
I will let you guys duke this one out :P 
Always get muddled up in areas like this!

**Comment by andrewstart** [comment]
I probably didn't explain that well enough, as I don't have the best understanding of pre-multiplied alpha vs not. However, the behavior we were seeing without multiplying in the source alpha is that additive RGB was causing transparent pixels to become visible, as shown in the images in that PR. I assume this means that the filter's output is handled as premultiplied alpha, and thus the source alpha must be multiplied in if we want it to be respected properly. If there is another way to get the correct result with different math, then I am all for it.

**Comment by hajimehoshi** [comment]
Well, my understanding is that adding color to premultiplied RGB breaks assumption that RGB value must equal to or less than alpha value. That PR makes sense in terms of that. Thank you for explanation. However, I still feel like that method is not correct in terms of mathematics.

My new suggestion is, how about applying a color matrix to non-premultiplied-alhpa color instead of premultiplied-alpha color? In my suggestion, premultiplied color values are converted to non-premultiplied color values once, then a color matrix is applied to the converted color value, and finally the color value is converted to premultiplied color value again. This would be correct in terms of mathematics, and additive doesn't break the assumption of premultiplied alpha since the result must be a correct premultiplied alpha.

Actually, my game library does the same thing:
https://github.com/hajimehoshi/ebiten/blob/master/internal/graphics/shader.go#L65

What do you think?

**Comment by andrewstart** [comment]
I wouldn't know how to enforce that the source pixels are non-premultiplied. Perhaps @GoodBoyDigital would have some ideas on that front.

**Comment by hajimehoshi** [comment]
Enforcing that and reverting can be done in the shader. Please see the above link :-)

**Comment by andrewstart** [comment]
Certainly worth a try. We can add a unit test to ensure the correct functionality of such a feature.
