### ISSUE TITLE
Pointer events normalized from touch events do not support multi-touch.

### ISSUE THREAD

**Issue by probityrules** [pixijs/pixi.js#3541]
I've noticed an issue where listening for a pointer event like "pointermove" on several display objects and then touch-moving multiple display objects at the same time results in the "pointermove" event only being triggered on one of the display objects.

This seems to occur when touch events are used to create the pointer events (so it doesn't affect Chrome, but does Safari). When a touch event occurs, the InteractionManager creates a single pointer event instead of creating a pointer event for each changed touch in the event's `event.changedTouches` array.

**Comment by themoonrat** [comment]
Hi @probityrules - I wonder if the PR proposed https://github.com/pixijs/pixi.js/pull/3375 would also help with this? Could you give it a try please?

**Comment by probityrules** [comment]
I'll check it out!

**Comment by probityrules** [comment]
I just tried it out and it works beautifully; thanks! Is there a general timeline for this PR to be included in a release?

**Comment by bigtimebuddy** [comment]
@probityrules I'm trying to get that into the release today

**Comment by themoonrat** [comment]
@probityrules unfortunately we couldn't squeeze that pr in for the latest release today, as we need more time to fully review and test it. But it's definitely something we want to add soon. And thank you for testing the PR so quickly :)

**Comment by probityrules** [comment]
Totally understand. Thanks for the update!

**Comment by andrewstart** [comment]
#3546 has been merged, so this should be solved.
