### ISSUE TITLE
Unused uniform float triggers error

### ISSUE THREAD

**Issue by rensrongen** [pixijs/pixi.js#3549]
Uniforms of type float will trigger an error when they are declared without being used in the fragment shader.

For example, the following fragment source triggers an error when used by a custom filter:

var fragmentSource = [
        'precision mediump float;',
        'varying vec2 vTextureCoord;',
        'varying vec2 vFilterCoord;',
        'uniform vec4 colorA;',
        'uniform float test;', //unused float
        'void main(void){',
            'gl_FragColor = colorA;',
        '}'].join('\n');

[pixi.js:18308 Uncaught TypeError: Cannot read property 'value' of undefined
    at FilterManager.syncUniforms (pixi.js:18308)]

Tested on PixiJS v4.3+

**Comment by englercj** [comment]
Related to us reading source for uniform reflection rather than using a compiled program I suspect.
