### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#3550]
hi.

i tested with example
       http://pixijs.github.io/examples/?v=v4.3.1#/basics/spritesheet.js

and code write like following 
    only added following Colde
~~~
 var container = new PIXI.Container();
  
  for ( var k = 0; k < 10000; k++){
  for (var j = 0; j < 5; j++) {

    for (var i = 0; i < 5; i++) {
        var bunny = PIXI.Sprite.fromImage('required/assets/basics/bunny.png');
        bunny.x = 40 * i;
        bunny.y = 40 * j;
        container.addChild(bunny);
    };
};
    
    stage.addChild(container);
~~~

Full Code
----------
~~~
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

// create a texture from an image path
var texture = PIXI.Texture.fromImage('required/assets/basics/bunny.png');

// create a new Sprite using the texture
var bunny = new PIXI.Sprite(texture);

// center the sprite's anchor point
bunny.anchor.x = 0.5;
bunny.anchor.y = 0.5;

// move the sprite to the center of the screen
bunny.position.x = 200;
bunny.position.y = 150;

stage.addChild(bunny);

// start animating
animate();
function animate() {
    requestAnimationFrame(animate);

    // just for fun, let's rotate mr rabbit a little
    bunny.rotation += 0.1;

    // render the container
    renderer.render(stage);
}
~~~

3.0.11 was 11-12 fps
4.x including 4.3.1 was 6-7fps

i think if drawcall is up. 4.x will be more fast.
but normally 4.x is more slow..

do you know about this issue?

thx a lot

**Comment by staff0rd** [comment]
Hi @SeminYun, thanks for your report.  I edited it was a little more readible - you should surround multi-line code snippets in \~\~\~ instead of \` which is used for inline code.

If I follow you correctly, you're saying that [this code](https://codepen.io/staff0rd/pen/GrJPGY) is running faster on Pixi v3?  

How are you determining fps?

**Comment by englercj** [comment]
HI @SeminYun, have you had a chance figure this out? Are you still having an issue?

**Comment by themoonrat** [comment]
@SeminYun going to close this issue due to inactivity, but please re-open if you feel there is still something we need to take a look at :) thanks!
