### ISSUE TITLE
Color threshold (in range) filter modifying alpha

### ISSUE THREAD

**Issue by jimothyhalpert7** [pixijs/pixi.js#3556]
The filter should set the alpha to 1 if a given point does not fall into the provided color range: `{ r: [80, 100], g: [100, 170], b: [40, 60] }`. The user can specify whether the threshold should be treated as a union (OR - if at least one of the colors is withing range, keep the point), or intersection (AND - all of the colors must be within range).

1. Can this be achieved using a **color matrix** filter?
2. Is there currently something out of the box like this?
3. If not, how to implement this (preferably without using another masking layer)

Thanks.

**Comment by GoodBoyDigital** [comment]
Hi @jimothyhalpert7 ,

Are you looking to create a filter? Sounds like you might have to go off road and make a custom one!

**Comment by englercj** [comment]
Yeah I think a custom filter is the way to go here. Feel free to open an issue if you need help!
