### ISSUE TITLE
The performance of BunnyMark reduces on the last PIXI.js

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3557]
The  test case  BunnyMark on 
```
 * pixi.js - v4.3.0
 * Compiled Mon, 02 Jan 2017 22:52:03 UTC
```
It could 45+ FPS on My  mobile (android 6.0 ,chrome 54).

Buy When I replace the pixi.min.js to the last version : 
```
 * pixi.js - v4.3.0
 * Compiled Sun, 08 Jan 2017 21:13:16 UTC
```
the FPS is 30+ .

**Comment by GoodBoyDigital** [comment]
hello @finscn ! Please provide more info if you can,
are you comparing the latest master release v4.3.1 to the previous master release v4.3.0?

Cheers!

**Comment by finscn** [comment]
I use last version on dev branch , but the package.json not update, so the build info is still '4.3.0'
My  test case use ParticleContainer with 12000 bunnies.

**Comment by staff0rd** [comment]
Hey @finscn can you post your code to a [pen](https://codepen.io)?

**Comment by staff0rd** [comment]
I ran the pens below twice each on an iPhone 5S, ios10, Safari, and timed how long it took to reach 60FPS.  4.3.0/latest would hang around 45-47fps for a while at the start, 4.2.1 would hang around 52-53fps at the start;

* 4.2.1
  * https://codepen.io/staff0rd/full/Bpomrd/
  * 18s
  * 24s
* 4.3.0
  * https://codepen.io/staff0rd/full/jybaLZ/
  * 48s
  * 38s
* latest
  * https://codepen.io/staff0rd/full/qROPzg/
  * 32s
  * 1m7s

**Comment by GoodBoyDigital** [comment]
you guys think it may be todo with highp on shaders?

**Comment by GoodBoyDigital** [comment]
Thanks for digging @staff0rd! Im not 100% sure what your results mean though! (dunce hat for me!). Are they the time it takes for the js to get compiled to the speedy version and hit 60fps?

**Comment by staff0rd** [comment]
@GoodBoyDigital dunno what you mean by "compiled to the speedy version".

I opened the device on each of the pens above, waited until PIXI loaded and began rendering, and then timed how long it took for the FPS to reach 60.  I did the process twice per pen, which is why there's two times against each.

**Comment by BossLevel** [comment]
Apologies for wading in with an utterly unscientific post, but I noticed a similar performance reduction with my own stuff (steady 60FPS dropped to hovering around 56FPS). I've been wracking my brains trying to work out what changed and having read this and checked my git logs, it turns out it was around the time I moved from 4.2.3 to 4.3.1.

**Comment by GoodBoyDigital** [comment]
hi @BossLevel ! Thanks for letting us know, which device is that on? desktop or mobile?

**Comment by BossLevel** [comment]
@GoodBoyDigital / Mat - apologies for the late response mate, I'm currently out of the country with limited internet access. It's desktop, I'm only just starting mobile testing now.

**Comment by finscn** [comment]
Is there any news about this issue ?

**Comment by finscn** [comment]
@staff0rd  , why pixi.js (or webgl ) needs some time to reach high performance ?

you said : 

> I ran the pens below twice each on an iPhone 5S, ios10, Safari, and timed how long it took to reach 60FPS. 4.3.0/latest would hang around 45-47fps for a while at the start, 4.2.1 would hang around 52-53fps at the start;

4.2.1
https://codepen.io/staff0rd/full/Bpomrd/
18s
24s
4.3.0
https://codepen.io/staff0rd/full/jybaLZ/
48s
38s
latest
https://codepen.io/staff0rd/full/qROPzg/
32s
1m7s

**Comment by finscn** [comment]
I found this : 
>Chrome and Safari will JIT it, and the JIT needs to run the code for some time to see which pieces of code are used a lot and need to be optimized, which cause such a "warm-up" phase as you describe.

**Comment by finscn** [comment]
I think the crime culprit is babel .  
the dist js compiled be babel is hard to optimize for JIT.
JS engine need more time to understand the code. 

@staff0rd @GoodBoyDigital @BossLevel  , How do you think about that  ?

**Comment by bigtimebuddy** [comment]
One approach to test @finscn comment would be to test performance of babel es5 vs babel es6 vs some other transpiling, like bubel. Also, am interested in using rollup instead of browserify, which does not create internal module structures, which would perform better at init-time

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍

**Comment by finscn** [comment]
Hi  @GoodBoyDigital  @bigtimebuddy @ivanpopelyshev  , in the v5 , the performance has risen up ?

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital I'm seeing a slight dip in performance with v5-alpha.2 (~8fps) vs v4.7.1 (~14fps) on MacBook Pro, Chrome 65 using bunny-mark
