### ISSUE TITLE
 When loading a SVG with PIXI.loader, the resulting resource has no texture

### ISSUE THREAD

**Issue by starInEcust** [pixijs/pixi.js#3560]
```
loadImages() {
    return new Promise((resolve, reject) => {
      loader
      .add('note0', 'images/renderImages/0.svg')
      .add('note1', 'images/renderImages/1.svg')
      .add('plus', 'images/plus-yellow.png')
      .on('error', reject)
      .load(resolve);
    });
  }
loadImages().then(() => {
    // has texture 
    console.log(loader.resources.plus.texture);
    // undefined
    console.log(loader.resources.note0.texture);
})

```
note0 and note1 have no texture,but plus has texture.

**Comment by staff0rd** [comment]
Hi @starInEcust , are you able to supply a [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by starInEcust** [comment]
@staff0rd  I'm sorry, version 4.3.2 is working.I just updated to 4.3.0 last week. 
You guys update too fast~ thank you very much!

**Comment by staff0rd** [comment]
All good!  I'll close this one if it's working on latest.
