### ISSUE TITLE
When update the version of PIXI.js , don't forget update package.json please.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3561]
The last version is `4.3.1` .
But in `package.json` , there is still `4.3.0`.

The build script will read version in package.json , and lead to the dist files are always with `4.3.0`.

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out. I need to update the publish scripts to commit the **package.json**. This has been fixed in 4.3.2.

**Comment by finscn** [comment]
@bigtimebuddy  ,  Do you update the  pixify  to the npm ?  the github of pixify is 1.8.x , the version in  package.json is still 1.7.x

**Comment by bigtimebuddy** [comment]
**pixify** version is 1.9.0: https://github.com/pixijs/pixify/blob/master/package.json#L3
