### ISSUE TITLE
Resolution resets to 1 when changing device orientation or resizing

### ISSUE THREAD

**Issue by sivael** [pixijs/pixi.js#3562]
When the pixi canvas is created it's created properly with double resolution on high density devices.

However, when the device is reoriented(or a resize is called) the systemRenderer has resolution = 1.
It's caused by CanvasRenderer changing it's resolution to target resolution ( 1 ) when rendering to texture. It seems to be needed otherwise everything is scaled up and the benefits of drawing in native resolution is lost.

Fix: SystemRenderer should remember it's resolution in a separate variable and use this for window resizing.
To avoid interactionManagers issues with double pixels that happen in this scenario, it also has to use the new resolution variable. 

Working on a demo and a PR.

**Comment by sivael** [comment]
#3563 covers interactionManager issues connected to wrong target point when clicking when resolution > 1
#3564 covers the resolution reset issue when changing renderer size

Both of those pull requests resolve the issue.

Working on a demo.

**Comment by staff0rd** [comment]
ping @themoonrat re; #3530 in case related.

**Comment by sivael** [comment]
#3530 is the proper fix for both issues, PRs closed.
Strangely enough I tried similar and it didn't work.

**Comment by sivael** [comment]
Since it's pulled to dev I'll be closing it now:)
