### ISSUE TITLE
[pixi.4.3.2] use spine have error !

### ISSUE THREAD

**Issue by shaoahs** [pixijs/pixi.js#3566]
http://pixijs.github.io/examples/?v=v4.3.2#/spine/dragon.js   // has error!
http://pixijs.github.io/examples/?v=v4.3.1#/spine/dragon.js   // has error!
http://pixijs.github.io/examples/?v=v4.3.0#/spine/dragon.js    // is okay !

**Comment by staff0rd** [comment]
Fixed
