### ISSUE TITLE
Displacement Map Jump/Stuttering Issue

### ISSUE THREAD

**Issue by Dairnon** [pixijs/pixi.js#3568]
I've been dealing with displacement maps to try and create an offset of a light overlay in RPGMakerMV. 

What I've done is created a silhouette of my sprites. I am then using that as the displacement map(these sprites rendered to a renderTexture). The characters are solid black, while the background is solid white. I then change the scale of the displacement map in the Y. This works really well and almost perfectly for what I want.

The issue I'm running into is when I move my sprite down toward the lower edge of the screen, the offset starts to jump or change. It starts to jump up as I progress down. It reverts back as you go back up. Is there something I'm doing wrong? 

I'd prefer to use a displacement map as it allows me to only need one renderTexture (instead of 3 used to copy both lights/shadows to then offset using another mask) but as of now I'm stuck trying to figure out what to do. 

Update: 

I've applied a photo showing the strange studdering / jumping. When I have the displacement center it looks normal, but if I move up or down (so the displacement moves when the view changes) its suddenly moves... Look at the distance of the offset of the shadow in both pictures, its wrong. Keep in mind I am not moving the displacement offsets/sprite at all (other then the view) and that I'm only adjusted the scale. The only thing changing is the renderTexture created from the character sprites, used for the displacement texture

This is by apply the displacement only to a shadow sprite, and setting scale.y to 20

I've provided a link of the problem in video form, its easier to see whats weird
Image example:
https://youtu.be/zBwppVohtSw

Image example: 
![bugshadow](https://cloud.githubusercontent.com/assets/17523069/21878470/659f2dfc-d847-11e6-8427-3a70cf70488d.png)

I am hoping there is either a fix or an easier way to achieve this effect... as it will save a lot of performance if I can just do it this way (or a way similar) All I want is an offset based on a "mask"

**Comment by staff0rd** [comment]
Hi @Dairnon, are you able to supply a [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by Dairnon** [comment]
I've only have experience with Javascript via RPG Maker MV... my knowledge of pen is limited... it may take a longer time to sort out a working demonstration via that. Basically I'm just curious if I am using the displacement texture correctly, or if there is some other way to generate a offset using a heightmap. I only want to shift the image up when the character walks through it... 

This method with the displacement map works, but I'm having issues with strange jumping of the displacement map when moving the view. 

I could provide a build of the game with the code.

I'm also noticing an issue when scaling the displacement map. If I scale it via the scale.y, the top of the screen starts to distort based on the scale... I'd rather that not happen.

http://imgur.com/a/GW9Z5

**Comment by Dairnon** [comment]
I recently got a working pen working but it appears to work with that version of pixi. RPG Maker MV is on 4.0.3, while then newest version is far higher then that 4.3.2. I have no idea what to port over or how too.

@ivanpopelyshev If I am not mistaken you had helped convert MV from pixi 2.0 over to pixi 4.0 Would it be difficult to port 4.3? And if not at least fix the displacement issue apparent here? 

I've provided essentially what I am doing here in the pen, it seems to be working almost entirely correctly (aside the strange distortion on the left due to the scaling which I hope to find a way to fix) 

https://codepen.io/Dairnon/pen/WRxKjQ

It doesn't work however in MV. (in which I provided the videos showcasing the strange stuttering)

I know your busy so please take your time, I just hope its possible as this is a feature I'd greatly like to take advantage of. 

I can easily provide a example project as well if need be. Thanks.

**Comment by Dairnon** [comment]
This has been solved by Ivan, was exclusive to RPG Maker MV 1.3 at the time.
