### ISSUE TITLE
TypeError: Class constructor Loader cannot be invoked without 'new'

### ISSUE THREAD

**Issue by darkowic** [pixijs/pixi.js#3573]
**Version** 4.3.2
```
TypeError: Class constructor Loader cannot be invoked without 'new'
```
In resource loader
![loader_pixi](https://cloud.githubusercontent.com/assets/11510581/21885244/104de166-d8b7-11e6-8552-c46cc6e214b1.png)

Everything is ok with version 4.3.0

**Comment by staff0rd** [comment]
Hi @darkowic, are you able to supply a [pen](https://codepen.io) that repro's this against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by darkowic** [comment]
I can simply reproduce it with my webpack config just by importing pixijs
```
import "pixi.js";
```
I use `webpack@2.1.0-beta.25`
babel
```
  "babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": [
          "src"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements"
        ]
      },
      "test": {
        "plugins": [
          "istanbul",
          "rewire"
        ]
      }
    }
```
Here are the rules:
```
    rules: [{
      test: /\.jsx?$/, // Transform all .js and .jsx files required somewhere with Babel
      loader: 'babel-loader',
      exclude: /node_modules/,
      query: options.babelQuery,
    }, {
      // Do not transform vendor's CSS with CSS-modules
      // The point is that they remain in global scope.
      // Since we require these CSS files in our JS or CSS files,
      // they will be a part of our compilation either way.
      // So, no need for ExtractTextPlugin here.
      test: /\.css$/,
      include: [
        path.resolve(process.cwd(), "src"),
        /node_modules/,
      ],
      loader: ExtractTextPlugin.extract({
        fallbackLoader: "style-loader",
        loader: 'css-loader',
      })
    }, {
      test: /\.(eot|svg|ttf|woff|woff2)$/,
      loader: 'file-loader',
    }, {
      test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
        'image-webpack-loader?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}',
      ],
    }, {
      test: /\.html$/,
      loader: 'html-loader',
    }, {
      test: /\.json$/,
      loader: 'json-loader',
    }, {
      test: /\.(mp4|webm)$/,
      loader: 'url-loader?limit=10000',
    },
    ],
  },
```
I started building my project with webpack when pixi was in in version 4 +
And I noted there https://gist.github.com/mjackson/ecd3914ebee934f4daf4 that since version 4.1.1 it doesn't require building by browserify.

I reproduced it also in react boilerplate project https://github.com/mxstbr/react-boilerplate - just install it, install pixi and import it in app.js.

**Comment by darkowic** [comment]
I see in diff that resouce-loader lib was updated for release 4.3.1 https://github.com/pixijs/pixi.js/compare/v4.3.0...v4.3.1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by GoodBoyDigital** [comment]
hi @darkowic , did updating the loader fix this for you? cheers!

**Comment by darkowic** [comment]
I didnt update recouce-loader couse I do not use it. It is used by pixi only

**Comment by GoodBoyDigital** [comment]
poke @englercj looks like one for you!

**Comment by englercj** [comment]
This has to do with how babel transforms native classes:

https://github.com/babel/babel/issues/4269

What happens is that since pixi (and the loader) are ES5, if they try to extend an ES6 class it will fail. I assume this is happening for you at runtime, can you please develop a pen that reproduces? None of our examples have this issue, and I'm not sure how you ended up with a version of pixi that has ResourceLoader in ES6 (our release builds do not).

Thanks!

**Comment by darkowic** [comment]
@englercj The problem is with 4.3.2 version of pixi. I can reproduce it with https://github.com/mxstbr/react-boilerplate project (version 3.3.3). Simply install pixi 4.3.2 and `import "pixi.js"` in main js file. I think this is easiest way to reproduce it.

I had similar problem with `material-colors` library https://github.com/shuhei/material-colors/issues/13 which used es6 features. The owner found that file pointed by `jsnext:main` should not use es6 features (weird, right? more https://github.com/jsforum/jsforum/issues/5). You can find more in links that I posted here.

Thanks for looking at the issue! Notice me if you reproduced the error.

**Comment by darkowic** [comment]
This are my babel dependencies
```
    "babel-cli": "~6.18.0",
    "babel-core": "~6.18.2",
    "babel-eslint": "~7.1.0",
    "babel-loader": "~6.2.7",
    "babel-plugin-istanbul": "~3.0.0",
    "babel-plugin-react-transform": "~2.0.2",
    "babel-plugin-rewire": "~1.0.0",
    "babel-plugin-transform-react-constant-elements": "~6.9.1",
    "babel-plugin-transform-react-inline-elements": "~6.8.0",
    "babel-plugin-transform-react-remove-prop-types": "~0.2.10",
    "babel-plugin-transform-runtime": "~6.15.0",
    "babel-preset-es2015": "6.18.0",
    "babel-preset-latest": "~6.16.0",
    "babel-preset-react": "6.16.0",
    "babel-preset-react-hmre": "~1.1.1",
    "babel-preset-stage-0": "6.16.0",
    "babel-register": "~6.18.0",
```

**Comment by englercj** [comment]
Ok, so what may be happening here is that `jsnext:main` is causing an issue. Can you open your locally installed version of resource-loader and just remove `jsnext:main` completely and see if that works?

If it does, I too will remove it and no longer publish the ES6 source.

**Comment by darkowic** [comment]
I confirm that removing `jsnext:main` form the `resource-loader` lib fix the problem. So this is `resource-loader`'s bug.

**Comment by darkowic** [comment]
@englercj I dont know if you should remove it. Maybe you need to compile it other way. I dont know. Anyway thanks!

**Comment by englercj** [comment]
Can you try using the latest master?

`npm rm pixi.js && npm i pixijs/pixi.js#master`

**Comment by darkowic** [comment]
Ok will test it for you tomorrow.

2017-01-19 18:11 GMT+01:00 Chad Engler <notifications@github.com>:

**Comment by darkowic** [comment]
I tested it with pixi 4.3.4. I get another error now. Issue in resource-loader library https://github.com/englercj/resource-loader/issues/84
