### ISSUE TITLE
PIXI Rope issue (Canvas vs WebGl renderer)

### ISSUE THREAD

**Issue by drewrg** [pixijs/pixi.js#3575]
Hello everybody.
There is an issue with PIXI rope when being rendered via Canvas.
Here is the preview.
![screenshot 89](https://cloud.githubusercontent.com/assets/11686119/21886004/700cb584-d8d3-11e6-9ea8-a003606d8a3f.png)

There is no seams when being rendered with WebGL. But I got to do this via Canvas,
Will be grateful for any advice.

Thank you in advance.

**Comment by staff0rd** [comment]
Hi @drewrg, are you able to supply a [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by drewrg** [comment]
Yes of course, [**Here it is**](https://codepen.io/Drewrg/pen/apNGOx)

**Comment by GoodBoyDigital** [comment]
```strip.canvasPadding = 2``` shoudl fix this for ya!

https://codepen.io/anon/pen/oBzmQZ

**Comment by drewrg** [comment]
Thank you for response.
It is working for regular images, but with semi transparent images I got overlapping effect.

![screenshot 94](https://cloud.githubusercontent.com/assets/11686119/22010148/e5de3bb8-dca0-11e6-9453-c8cf0bc56f2b.png)

Is there any way to get rid of overlapping ?

**Comment by GoodBoyDigital** [comment]
hello! have you tried ```strip.canvasPadding = 1```? Its not an exact science i'm afraid :/
A down side of canvas!

**Comment by drewrg** [comment]
Yes I've tied almost every value, but nothing worked.
With `strip.canvasPadding = 1` you can already see the seam between sections, and the sections are still overlaping.

![screenshot 100](https://cloud.githubusercontent.com/assets/11686119/22094804/882f9e78-de29-11e6-9561-a22293fab1c9.png)

**Comment by icefox0801** [comment]
Got the same issue

**Comment by ivanpopelyshev** [comment]
OK, one more time - you guys have to rewrite CanvasMeshRenderer. Make sure all triangles oriented in the way that doesnt lead to those problems.
