### ISSUE TITLE
loader events ( progress, complete)doesn't fire in v4.3.2 when concurrency count != 10

### ISSUE THREAD

**Issue by humanhighway** [pixijs/pixi.js#3579]
loader events ( progress, complete)doesn't fire in v4.3.2 when concurrency parameter != 10
ex : 
   var loader = new PIXI.loaders.Loader('', 2); // default is 10
    loader.add('./a.json');
    loader.add('./b.json');
    loader.on('progress', function(e) {
      console.log('progress', e.progress);
    });
    loader.on('complete', function(e) {
      console.log('complete', e.progress);
    });
    loader.load();

example code :
https://dl.dropboxusercontent.com/u/66179/pixi-loader-test2.zip

step :

npm install
browser-sync start --server
check consloe.log

**Comment by CintoVC** [comment]
Today i update to 4.3.1/4.3.2 from 4.0.3 and have a similar problem.
I think happens any problem when try to load a second json or xml file.
Don't respond more.

**Comment by bigtimebuddy** [comment]
Confirmed locally that is an issue. Thank you @humanhighway for the example, very helpful.  

Loader seems to hang if the initial number of items you're loading is less than or equal the concurrency value. Looping in @englercj, seems like a bug with **resource-loader**.

**Comment by warlockuk** [comment]
Also in 4.3.3, this one hit me in the face this morning while updating :D

**Comment by bigtimebuddy** [comment]
Ping @englercj

**Comment by englercj** [comment]
Hey, sorry for the delay. This got lost in the noise for me, I am aware and looking into this.

**Comment by englercj** [comment]
Working on this in englercj/resource-loader#82. I have a failing test and am working on a solution.

**Comment by englercj** [comment]
Can you try this now with the latest master build?

http://pixijs.download/master/pixi.js

Should be fixed there.

**Comment by bigtimebuddy** [comment]
That fixes @humanhighway issue in the demo he provided. Thanks for the fix @englercj.

**Comment by humanhighway** [comment]
hi @englercj , found a issue about progress, loader progress maximum always get 50.

**Comment by lebronchin** [comment]
Similarly, after updating, I got stocked at 52%.

**Comment by bigtimebuddy** [comment]
@humanhighway and @lebronchin have you updated to v4.3.4?

**Comment by humanhighway** [comment]
yes.

**Comment by lebronchin** [comment]
indeed

**Comment by bigtimebuddy** [comment]
Calling @englercj

**Comment by englercj** [comment]
Fixed this issue in resource-loader and have updated `dev` to use the latest version.

https://github.com/englercj/resource-loader/releases/tag/v2.0.6
