### ISSUE TITLE
Texture.fromCanvas() and mesh.Rope() leak of performance

### ISSUE THREAD

**Issue by Jeremboo** [pixijs/pixi.js#3580]
Hi, Pixi.js is totally new to me ! And in order to try it, I wanted to develop à little rope generator with a gravity physics.

For the texture of my ropes, I proceded that way :

- Use the `PIXI.mesh.Rope()` method following this example : [Textured Mesh](https://pixijs.github.io/examples/#/basics/textured-mesh.js). 
- Create the texture of the rope with canvas. Based on a repeated rope pattern :
![Rope Pattern](http://jeremieboulay.fr/assets/ropePattern.png)
- This is the end result  :
![Rope Pattern](http://jeremieboulay.fr/assets/rope.png)

You can find a complete example of my code on this [codepen](http://codepen.io/Jeremboo/pen/QGVaYa).

But here is a simplified snippet :

```javascript
import { Container, mesh, Texture } from 'pixi.js';
const ROPE_WIDTH = 30;
const ropeLength = 300;
const scene = new Container();
const points = [...]; // Array of new Point(x, y) distanced by ROPE_WIDTH
...
function buildRopeTexture(callback) {
  ...
  const canvas = document.createElement('canvas');
  const context = canvas.getContext('2d');
  const nbrOfRopePattern = ropeLength / ropePatternPic.height;
  let i;
  for (i = 0; i < nbrOfRopePattern; i++) {
    context.drawImage(ropePatternPic, i * ROPE_WIDTH, 0);
  }
  callback(Texture.fromCanvas(canvas));
  // callback(Texture.fromImage(canvas.toDataURL()); // Same leak
}
buildRopeTexture(texture => {
  scene.addChild(new mesh.Rope(texture, points));
});
```

And it works ! But with a really poor fps :(
With only 4 ropes rendering, the fps goes down a lot.

To find out what does not work well, I tried to : 

- **Use `Texture.fromImage('rope.png')` instead of a canvas :** I can build up to 25 ropes before it leaks. Its better, but my rope texture gets distorted depending on its length. So its not what I wanted.

- **Use only `Graphics` method to draw my ropes :** After optimization, 90 ropes (approximately 1000 Points) can be build before leaks.

Conclusion, even if my `update()` method is greedy, using `mesh.Rope` with a canvas it make the peeormance go down...
When I see other Pixi.js examples, I really think my test could be work better. But I don't know how to improve it.

Is there something wrong in my process ? How can I improve it ?

Thank you in advance <3

**Comment by GoodBoyDigital** [comment]
Hi @Jeremboo , each time you are adding a rope, you are also increasing the times the whole scene is rendered too.

heres a fixed version of your pen: http://codepen.io/anon/pen/JERwGm

perf is much better! Thanks!

**Comment by Jeremboo** [comment]
Hum... I didn't think I would have made such a stupid mistake in my base code.

Thank for your time.

**Comment by egogg** [comment]
set rope.autoUpdate = false or set rope.cacheAsBitmap = true, or both
