### ISSUE TITLE
DisplacementFilter does not clamp to edges

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#3582]
In the following the edges behind the sprite are visible at times;

https://codepen.io/staff0rd/pen/LxZJVv?editors=0010

<img src="https://cloud.githubusercontent.com/assets/6289998/21952034/cefdd42c-da65-11e6-892d-5b2f977715ef.png" width=300 />

I think this is because `filterClamp` is not working?

Possibly also related to #2816, #2572 (closed)

**Comment by manuelodelain** [comment]
following the wiki page https://github.com/pixijs/pixi.js/wiki/Creating-Filters-in-Pixi-v4

this code solves the problem:
```displacementFilter.filterArea = app.screen; // not necessary, but I prefer to do it.
displacementFilter.padding = 0;```

**Comment by englercj** [comment]
Just setting the padding to `0` worked for me:

```js
displacementFilter.padding = 0;
```
