### ISSUE TITLE
Errors in minified code after creating custom lib (v4.3.2)

### ISSUE THREAD

**Issue by Friksel** [pixijs/pixi.js#3583]
After creating a custom build with the npm run dist line below, the minified output looks way off in sublime text (the editor doesn't recognise the code from half the lib to the bottom, causing half the code to be displayed in yellow). 
I never seen this happening before, so something seems to be causing this in on of the latest versions of the lib. A run of both the unminified as the minified outputs through jshint show the 'too many errors'-message after 51 warnings, like Missing semicolons and so on. So maybe this could be the problem?
btw Phpstorm still seems to 'understands' the code in the editor though, but there definitely is something wrong in the minified output here.

This is the command creating the file:

`npm run dist -- -e accessibility -e filters -e mesh -e particles -e extract`

**Comment by GoodBoyDigital** [comment]
Thanks for sharing @Friksel ! cc'ing @bigtimebuddy and @englercj.

**Comment by bigtimebuddy** [comment]
@Friksel Thanks for the issue. 

I ran the built code generated with all those excludes and it ran fine in Chrome/Firefox. Also, browserified and/or minified code is not intended to be run through jshint. 

Color-coding in the editor like Sublime will typically have issues with minified JS files because of the underlying regular expressions used to create the colorization. I'm using Sublime Text 3 and only half the code is colorized correctly. From my experience, this is not unusual.

**Comment by Friksel** [comment]
Thanks for your quick action @bigtimebuddy .

I always include the pixi minified code in a file together with other libs I use, like greensock. All libs start on a new line and have a license comment followed by the code.
The minified pixi file that's coming with the zip is always (in all versions) showing fine in all editors I use. But the custom created minified file is messing up all code underneath (including license-comments of the other libs in the combined file), wich let me not only wonder if the file is ok (because I never had this before), but also it's not really easy to spot the other libs in the combined file with this.

I never seen this happening before (from one of the first pixi versions 1 up to v4.3.2.), but I only just recently started to create custom pixi versions and it only happens on these custom minified versions in v4.3.2 (in v4.2.2 it was still working fine).

I know it's crazy to run a minified file through jshint for the check of semicolons. But I also get a long list of warnings on the unminified pixi code. 

If there would be something wrong with a regular expression inside the code I would expect the same thing to happen on the minified file that's coming with the zip too, but that's not the case.
So to be honoust, I'm not really convinced the generated custom min. file is okay.

**Comment by GoodBoyDigital** [comment]
Interesting! to check - does the minified file actually work?

**Comment by bigtimebuddy** [comment]
The minified version seemed to work fine for me. @Friksel?

**Comment by GoodBoyDigital** [comment]
poke @Friksel :)

**Comment by Friksel** [comment]
@bigtimebuddy  and @GoodBoyDigital , I didn't try the file on the project in the end, 'cause I don't really  rely on it this way and it's easy to avoid it by just using the full file. Unfortunately these weeks I'm very short on time, otherwise I would have tested this by now, sorry for that. If I find the time I give the file a shot

**Comment by englercj** [comment]
I'd say about half the minified js files I open in sublime are not colored correctly. Sublime is *not* a js lexer, it has no idea if your syntax is correct. The highlighting is purely based of regex, which can *easily* break when looking at a minified file.

If you didn't get errors from the build process when building that minified file, it is fine. Because that *does* use a js lexer, parsing the syntax tree (not regex). Unless you experience a runtime error, there is nothing to worry about if your text editor gets confused by minified text, happens all the time.

**Comment by Friksel** [comment]
@englercj Thanks for your response. I never had syntax highlightproblems before in sublime with minified files, and I used a lot of different libs. I always pack these into one single javascript file and it is always working fine with syntax coloring except for this custom build minified file on my site. If the minified pixi file doesn't have any problems showing in sublime, why would the custom build version do? It doesn't make sense to me. I'm using Sublime2 btw.

But hey, I don't know anything about 'js lexer', so you're probably more into that stuff and maybe I'm missing something here. To be honest I'm way too busy on a large project and therefore have other priorities at the moment so can't find the time to dive deeper into this to help. Sorry for that. 
For me no problem now, I just got back to using the standard supplied minified pixi file instead, wich is working fine and has the right syntax highlighting, like expected and I'm used to see.

**Comment by englercj** [comment]
> I just don't understand this then: If the minified pixi file doesn't have any problems showing in sublime, why would the custom build version do? It doesn't make sense to me. I'm using Sublime2 btw.

Because the builds are different, anything could happen differently between them.

You can always find the exact character where highlighting breaks and see why it happens. If it runs in browser, then it is a sublime highlighting bug. Probably just an obscure one.
