### ISSUE TITLE
The pixels that out of map image are changed in DisplacementFilter Example.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3586]
the test case : 
http://pixijs.github.io/examples/#/filters/displacement-map.js
(official  demo, no change)

see the image : 

![2017-01-15 3 00 46](https://cloud.githubusercontent.com/assets/288367/21957327/dd220b54-dace-11e6-80ff-7779c8708a5b.jpg)

**Comment by finscn** [comment]
Because the map used CLAMP_TO_EDGE ?

**Comment by themoonrat** [comment]
Closing as fixed
