### ISSUE TITLE
Bad WebGL Detection

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#3587]
I'm using Pixi.js on openSUSE (GNOME 3) in a VirtualBox instance and am unable to do 3D acceleration. However, Pixi.js still tries to load WebGL when `autoDetectRenderer` is used.  If I set `noWebGL` to `true` then everything works fine, otherwise nothing renders to the screen (FYI, there is no JavaScript error).  This is concerning as I'd prefer to rely on `autoDetectRenderer` to give WebGL when possible, but I don't like the idea that it would mean for a small group of people the web application would be completely unusable.

**Comment by englercj** [comment]
We use WebGL when the browser tells us WebGL is available to be used. Do you have an example that reproduces this issue? Have you tried debugging to see why it doesn't render?

**Comment by darkfrog26** [comment]
WebGL detects true, but WebGL 2 doesn't.  I'm not sure if that's applicable to the problem, but I have found nearly every "WebGL Detection" system thinks that I can run WebGL even though I can't.

**Comment by photonstorm** [comment]
Report it as a bug to the browser vendor, the problem is theirs alone, and
they do fix things like this.

**Comment by GoodBoyDigital** [comment]
Hi @darkfrog26 , thanks for sharing. As @photonstorm mentioned, this seems like a vendor issue rather than a pixi one. Worth reaching out to them I reckon! Cheers!

**Comment by darkfrog26** [comment]
Thanks guys.  I agree this is a VirtualBox issue, but was hoping there might be a way for Pixi to offer better WebGL detection to handle it.

**Comment by photonstorm** [comment]
There's literally only one way to ask a browser if it supports WebGL, and if it lies about it there's sadly very little that can be done.
