### ISSUE TITLE
Anchor Point for Primitives

### ISSUE THREAD

**Issue by iraladson** [pixijs/pixi.js#359]
Hey,

Is there a way to anchor Graphics() objects? I'm trying to have a square and a triangle rotate around their center point. Is that possible?

**Comment by yuhwkim** [comment]
using g.pivot.x not good. it's - 50 px. 
have to use g.position with g.pivot to display on the screen.

**Comment by ivanpopelyshev** [comment]
Anchor depends on graphics width/height which is calculated every time you update it. It's a bad idea
