### ISSUE TITLE
When render object to RenderTexture, some shaders will be incorrect

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3590]
When render object to RenderTexture ， the  PIXI use RenderTarget by a different way.
 some shaders will be incorrect.

e.g.      PointLight  of  `LightSpriteRenderer` 
https://github.com/finscn/pixi.js/blob/master/src/extensions/renderers/light/LightSpriteRenderer.js
https://github.com/finscn/pixi.js/tree/master/src/extensions/renderers/light/lights/pointLight

I  think (just think ,I'm not sure)   the key point of  this issue is  

When render object to Screen , the PIXI will flip coordinates ，but not do it for RenderTexture.
So the `gl_Position`  , `gl_FragCoord`  `projectionMatrix` will be different.

If  a shader compute something with `gl_Position`  , `gl_FragCoord` , `projectionMatrix` ,  
there  will be different between rendering to Screen & to RenderTexture.

And I test and found this : 
```
    vec2 fragCoord = gl_FragCoord.xy / uViewSize;

    // FBOs positions are flipped.
    fragCoord.y = 1.0 - fragCoord.y;

```

And The second problem is : 
the relative position of gl_FragCoord and object  is also  different ( if RenderTexture  doesn't ignore position & rotation , No this problem).

Could you give some suggestions  ? 

.

**Comment by finscn** [comment]
And I want to know why use different `projectionMatrix ` 
```
        if (!this.root)
        {
            pm.a = 1 / destinationFrame.width * 2;
            pm.d = 1 / destinationFrame.height * 2;

            pm.tx = -1 - (sourceFrame.x * pm.a);
            pm.ty = -1 - (sourceFrame.y * pm.d);
        }
        else
        {
            pm.a = 1 / destinationFrame.width * 2;
            pm.d = -1 / destinationFrame.height * 2;

            pm.tx = -1 - (sourceFrame.x * pm.a);
            pm.ty = 1 - (sourceFrame.y * pm.d);
        }
```

Could you tell me why ? thanks.

**Comment by finscn** [comment]
Now  I add `varying float flippedY;` in shader.

And in vert shader: 
```
    flippedY = projectionMatrix[1][1] < 0.0 ? 1.0 : 0.0;
```
Then check in frag shader:
```
    vec2 fragCoord = gl_FragCoord.xy / uViewSize;

    if (flippedY > 0.0)
    {
        // FBOs positions are flipped.
        fragCoord.y = 1.0 - fragCoord.y;
    }
```

Is there a better way ? Thanks.

**Comment by GoodBoyDigital** [comment]
hi @finscn, this is correct - when rendering to a framebuffer everything is flipped on the y. Its a webGL thing (always thought is was a bit strange!) . Pixi renderTargets deal with this under the hood by automatically modifying the perspective matrix for you. 

If you are using your own matrix then the above should do the trick!

Cheers!
