### ISSUE TITLE
Two PIXI.filters.ColorMatrixFilter's on an entity causes the main stage to go dark

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#3594]
We were originally experiencing #3288 and #3373 - Basically, before 4.3.2, things were extremely chaotic and it was hard to pinpoint a single cause for the black screen issues, post 4.3.2, I think the original issues are fixed, yet this new issue is present

Basically, when two PIXI.filters.ColorMatrixFilter are applied on an entity, the game stage goes dark, yet the children on the lower half of the screen are visible, on the upper half of the screen, all entities are invisible, when one filter is removed, the stage is back to normal, there are no logs, or no after effects

This issue isn't present in 4.3.0

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by GoodBoyDigital** [comment]
super keen to get these last remaining texture issues squashed :D

**Comment by kaansoral** [comment]
I tried to create one but failed, the entity that goes dark has a texture from a RenderTexture - I tried to take a jsfiddle from another issue, work on that to add double filters, but for some reason the filters were ineffective, I gave up - Patched my game to disable the second filter, tho I intend to return to the issue when there is time, apologies for now

Most players also report "Rats WebGL" issues, and they have GPU's along the lines of GTX 980/1080's with latest drivers, going to see whether 4.3.3 with this issue patched is going to prevent those issues - but ever since 4.0.2, each version is breaking something, I'm also experiencing GPU issues on the system level on macos, like system freezes, it pains me to not have the capacity/time to inspect these issues

One player was kind enough to send a browser webgl crash report, if the issue persist intending to open another issue related to that, it feels like webgl is leaving behind things that aren't ever free'd, and when they accumulate, these crashes on windows and my freezes on macos occur

**Comment by themoonrat** [comment]
FYI, I have this issue too - I'll see if I can create a fiddle at some point. I have 3 ColorMatrixFilters on a sprite, to allow adjusting of hue, saturation and brightness separately. When using it on anything other than the background, it causes the rest of the screen to go black.

**Comment by GoodBoyDigital** [comment]
Hey @kaansoral ! Are you on the pixi slack? I am very keen to solve the issues you are seeing. Maybe if we collaborate a little closer we can figure out what the problem and solve it ?

Cheers!

**Comment by kaansoral** [comment]
I am not, my email is kaansoral [a] gmail

Since @themoonrat has this issue too, I suspect it's on the edge of being solved, so glad I'm not the only one :)

**Comment by GoodBoyDigital** [comment]
sweet! @themoonrat if you can get me a fiddle that would be ace!

**Comment by themoonrat** [comment]
Will get you one over the weekend

**Comment by GoodBoyDigital** [comment]
@themoonrat my hero 👍

**Comment by GoodBoyDigital** [comment]
looks like a fix just popped in! #3632

**Comment by themoonrat** [comment]
Woop! I will test it tomorrow. Sorry I didn't get a fiddle, gradient text thing took longer than I thought and ate into programming funtime

**Comment by GoodBoyDigital** [comment]
fixed via #3632 👍
