### ISSUE TITLE
Interactive parents should not make non-interactive children block interactive children

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#3596]
When parent is interactive and front child is non-interactive clicking an overlap should cause the behind (interactive) child to be hit.

See the failing test in #3535's description.  [This test has been commented out](https://github.com/pixijs/pixi.js/blob/15881774d4b0a0bb305b428990f0a303989ad72b/test/interaction/InteractionManager.js#L367-L385) to allow merging of the passing tests, however, pixi is still displaying the bug that causes the test to fail. Bug needs to be fixed, test needs to be uncommented.

Example pen; https://codepen.io/staff0rd/pen/BpQaxg?editors=0010

In the example pen above, click the blue square (half hidden behind the green square) and note the console fires the handler.  Click the right-hand side of the green square (the overlap) and note the console fires the handler.  Now, uncomment line 38 and perform the test again;  Clicking blue results in both parent & behind handlers firing.  Clicking the overlap results in **only the parent** firing, which is the bug.  In this scenario (and commented test above), it is expected that the behind handler should also fire - as it does when the parent is not interactive.

**Comment by vdddslep** [comment]
Any ideas how could I handle it? 
I have a big project(more than 1k classes) with very sophisticated scene and at this time my whole work stopped case of this.

Or maybe someone could suggest me any other PIXI like library to move?

**Comment by ivanpopelyshev** [comment]
@vdddslep why not just modify your pixi.js with @staff0rd 's patch?

**Comment by ivanpopelyshev** [comment]
^^^ updated the post, please look above.

**Comment by vdddslep** [comment]
Thank you,
I will try to do that, It could be difficult for me because I have no idea how to get it) 
I mean, I am working with TypeScript and I have no know idea how to compile pixijs because i don't have such an experience with JS. 

But looks like I have no choice!

**Comment by vdddslep** [comment]
Thank you, it works! I'm going to love JS

**Comment by themoonrat** [comment]
Closing as fixed
