### ISSUE TITLE
Scaling a Container does not scale child graphics objects

### ISSUE THREAD

**Issue by KosGrillis** [pixijs/pixi.js#3600]
I've noticed an issue in Pixi where upon scaling a Container, any primitive Graphics objects are not scaled, while other objects such as Sprite are scaled.

Here is the code that I use for scaling, just in case it's useful:

```
scroll($event){
    this.zoom($event.deltaY, $event.offsetX, $event.offsetY);
}

zoom(deltaY, offsetX, offsetY){
    deltaY = (deltaY > 0) ? 1.1 : 0.9;
    var worldPos = {x: (offsetX - this.stage.x) / this.stage.scale.x, y: (offsetY - this.stage.y)/this.stage.scale.y};
    var newScale = {x: this.stage.scale.x * deltaY, y: this.stage.scale.y * deltaY};
    var newScreenPos = {x: (worldPos.x ) * newScale.x + this.stage.x, y: (worldPos.y) * newScale.y + this.stage.y};

    this.stage.x -= (newScreenPos.x - offsetX) ;
    this.stage.y -= (newScreenPos.y - offsetY) ;
    this.stage.scale.x = newScale.x;
    this.stage.scale.y = newScale.y;
    console.log(this.stage.children);
}
```

`$event` is simply a browser event. When this code runs, all the children Sprite objects of `stage` are scaled appropriately. However, primitive Graphics objects (in my case a bezier curve) are not scaled **at all**.

**Comment by themoonrat** [comment]
Hi @KosGrillis 

I'm looking at our examples page, and I can't replicate what you are seeing? I'm looking at https://pixijs.github.io/examples/#/basics/graphics.js and adding
`stage.scale.set(2);`
on line 6. The stage is scaling as expected, including the primitive graphics.

**Comment by KosGrillis** [comment]
I gave that a shot too and it is also working for me. Perhaps it could be an issue that occurs when the graphics objects are scaled dynamically, or it could be a problem with my code. I'll keep this updated if I get any closer to figuring it out.

**Comment by themoonrat** [comment]
Please do; if you can narrow it down to something you can post onto jsfiddle or codepen it helps us a huge amount! :)

**Comment by staff0rd** [comment]
Will re-open if a repro is supplied.
