### ISSUE TITLE
Browser zoom issues with canvas renderer

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#3602]
1. Open https://jsfiddle.net/79tvfm5m/
2. Zoom a little in/out via ctrl+scroll.
3. See it flickering like hell.

**Comment by bigtimebuddy** [comment]
@trsh I cannot reproduce. Can you give more information about your environment? Which browser/device/platform?

**Comment by trsh** [comment]
@bigtimebuddy - ubuntu x64, browser up-to-date Chromium. Sorry, that was important. On windows the problem seems not to be present.

**Comment by BossLevel** [comment]
@trsh @bigtimebuddy Just to add some more info, same OS but out of date Chromium (Version 51.0.2704.79 Ubuntu 15.10 (64-bit)) - works fine.

**Comment by staff0rd** [comment]
I'm able to cause some flickering on the canvas renderer in Chrome 56, Windows 10.  See this pen; https://codepen.io/staff0rd/pen/YNvVYm?editors=0010

Make the window so its not full screen, then drag the right window border back and forth.  CanvasRenderer flickers but WebGLRenderer does not.
