### ISSUE TITLE
using webgl renderer and canvas renderer in the same time is not working

### ISSUE THREAD

**Issue by yeahlo** [pixijs/pixi.js#3610]
I'm using a webgl renderer for my game and as long as I add a new renderer for an overlay, I have this error : 
"This browser does not support webGL. Try using the canvas renderer"
it seems to be a problem to create a canvas context before webgl.
v4.3.3

**Comment by yeahlo** [comment]
ok it was between me and angular...

**Comment by GoodBoyDigital** [comment]
no worries! glad its solved 👍

**Comment by TombolaShepless** [comment]
@yeahlo can you explain what the issue was please? We are facing something similar but aren't having any luck fixing.

**Comment by yeahlo** [comment]
I don't really remember...something stupid like using the same canvas for both.
Can I have a look to your code ?
