### ISSUE TITLE
Mesh.Plane video texture not working on safari ios10

### ISSUE THREAD

**Issue by avanderpotte** [pixijs/pixi.js#3611]
Hello,

I'm using Mesh.Plane with video texture, in short :
```
var texture = new PIXI.Texture.fromVideo(videoUrl)
var mesh = new PIXI.mesh.Plane(texture, 2, 2)
mesh.texture.baseTexture.source.play()
```

It works perfectly on desktop but not on Safari on iPhone ios10. I've also tried to create a video element and use for the texture, but no results.

I've also noticed that even the example isn't working too : https://pixijs.github.io/examples/#/basics/video.js . When the page is loaded, the video isn't starting, you need to press the restart button.

Have you any idea on how to fix this ?

**Comment by themoonrat** [comment]
Safari on ios10 cannot play video that has sound without a user interaction

Also make sure that the video has the following tags to allow inline playing of video on ios10

video.setAttribute('webkit-playsinline', '');
video.setAttribute('playsinline', '');

**Comment by englercj** [comment]
Closing this since it seems like this has been answered.
