### ISSUE TITLE
Drag and Drop with bounds, snap, target drop, velocity/gravity?

### ISSUE THREAD

**Issue by mspanish** [pixijs/pixi.js#3613]
I'm finding the drag element to be a bit limited - I would love to use Greensocks's Draggable with Pixijs - but so far haven't figured out how to do that as I guess I need a dummy dom element first.

Is there any plan to make a more robust drag and drop element? Features like snap, a bouncing ease on drop, throwing, etc - are really vital when it comes to kids games and educational apps.

Thanks very much for your library!!

**Comment by ivanpopelyshev** [comment]
There are no animations in the core lib. Plugins have some of those - pixi-animate, pixi-spine, but not exactly what are you describing ;)

**Comment by englercj** [comment]
We probably will not add something like this in the core, though it would make for a good plugin! You can use greensock with pixi, without DOM. You just have to sync the results of the tweening back into the pixi objects.

Good question!

**Comment by mspanish** [comment]
Thanks I did finally find a great example from Blake at Greensock - will try to post the URL later as it's a great Codepen.
