### ISSUE TITLE
The document don't include spine api

### ISSUE THREAD

**Issue by yangguansen** [pixijs/pixi.js#3619]
I want to find some spi about pixi-spine in the doucment :http://pixijs.download/release/docs/index.html
.But there isn't include the api of spine。
 So I want to know where could I learn the pixi-spine api, and how I made the altas file?
Thx!

**Comment by finscn** [comment]
pixi-spine is a standalone extenstion at https://github.com/pixijs/pixi-spine .
I think it shouldn't be included in the doucment  of pixi.js

**Comment by ivanpopelyshev** [comment]
Hey there! Spine atlas is exported from spine, but you can make it from pixi textures just fine, please look at  https://github.com/pixijs/pixi-spine description

**Comment by yangguansen** [comment]
thanks !~
