### ISSUE TITLE
Multi Texture Batching in PIXI v4 mess up with cocoon Canvas+ processing. 

### ISSUE THREAD

**Issue by artsjedi** [pixijs/pixi.js#3623]
would like to know if is possible to disable the multi texture batching in a PIXI V4 game. 
Recently i jus update my game PIXI lib from version 3 to 4.3. I`m using cocoon Canvas + . It seems perfect on iOS and android version greater than 5. 
In a old phone the texture batching is messing with the textures. 

https://www.youtube.com/watch?v=t6wVYRm731I

I made a lot of tests. It seems that, the renderer doesnt know what texture file to render. and it become this mess. 

I already tried 
            PIXI["settings"].SPRITE_MAX_TEXTURES = 1;
            PIXI["settings"].SPRITE_BATCH_SIZE = 1024; 
  
without success 

Any clue to figure out what is happening?

**Comment by cvissie** [comment]
I've got a sinking feeling that this is related to #3558 @GoodBoyDigital?

We've also been hit with a few cases of this bug and we've set it to 1 as well now.

I'm going to go dig in the code now but let me ask the obvious question. Is there a simple way for us to detect if we can use multi texture or shall we just resort to user agents?

**Comment by artsjedi** [comment]
it is definitally related to #3558 .! I didint found any way to detect if the device is able to support multi texture. I tested in a limited range of devices. 

- iphone 5s, ipad mini v1 and v2 .  working good
- New androids devices, no problem in almost all of them, except a little flickering at loading textures
- Old android device Moto razr HD totally messed up
- Windows 10 devices (pcs and phones) no problem with them.

In my game app, i will just verify if it is an android, and them activate the compatibility mode

**Comment by GoodBoyDigital** [comment]
hello! have you tried also
```PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true```

Let me know if this helps! ta!

**Comment by cvissie** [comment]
@GoodBoyDigital 

What I have experienced.

```PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true``` did not fix the performance issues we've been having.

It did however fix a very weird and nasty bug relating to ```Rope``` that caused vertices to go all over the place. Or that might have been setting the shader to mediump. Not 100% sure on that one. But it definitely did not fix the flickering or performance issues.

Setting Max textures to 1 was the only way to fix the performance issues.

**Comment by GoodBoyDigital** [comment]
cool! does that mean things are working as expected for you now?

**Comment by cvissie** [comment]
yeah ... let me actually just add the snippet that I added.

```
PIXI.settings.SPRITE_MAX_TEXTURES = 1;
PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;
PIXI.settings.PRECISION = PIXI.PRECISION.MEDIUM;
```

the precision mediump is working now - but i could have sworn a few builds back it broke things with Rope.

The obvious downside about the above settings of course is that the performance of the mobile app is back to PIXI 3 (well not quite, but it is noticeably slower without the multi-texture support)

**Comment by GoodBoyDigital** [comment]
Awesome. I just added this guy: https://github.com/pixijs/pixi.js/pull/3630

So it should be easier for people in the future to activate what i am now affectionally calling the 'legacy' settings :)

Its a bit of a pain that some older environments are holding things back in terms of compatibility. But hopefully you can do some checking on the app side to only set the 'low' settings if you have too.

Remember, sprite sheets will be you best friend with multi-texture disabled.

Thanks for helping us out!

**Comment by artsjedi** [comment]
i tried
```
if(legacy_mode){
                PIXI.settings.SPRITE_MAX_TEXTURES = 1;
                PIXI.settings.PRECISION = PIXI.PRECISION.MEDIUM;
                PIXI.glCore.VertexArrayObject.FORCE_NATIVE = true;
}
```
Does not works for me

I figured out that is due to the a lot number of texture files. I'm not using spritesheets. 
When I reduce to 4 or 5 big texture pack files, the issue is gone.

the result. 
- separated texture files (near 30 files) and turn on "legacy mode" does NOT works.
- packing into 5 big sprite sheets and turn on the "legacy mode" does works good.
- Without "legacy mode" none of the options above works.

**Comment by artsjedi** [comment]
I really would like to have any clue to when we should turn on this legacy mode. Any clue?

**Comment by artsjedi** [comment]
Hey @GoodBoyDigital  I dont think this issue is closed. The "legacy mode" just bypasses the problem, not solves it.
