### ISSUE TITLE
Changing Texture.frame.x does not apply a _updateUVs()

### ISSUE THREAD

**Issue by BjornMoren** [pixijs/pixi.js#3625]
This might be by design to keep things simple in the Rectangle class, but perhaps a note about it in the documentation could be warranted.

**Comment by staff0rd** [comment]
Extending Rectangle to inherit from EventEmitter is probably a bit overkill.  Looks like the supported method is to set the frame rather than the frame properties.

**Comment by ivanpopelyshev** [comment]
I had this PR that takes care of that some time ago, but it wasnt accepted. There were cached UV's, also frames for sprites and stuff...

I can do that again later :)

**Comment by englercj** [comment]
We should add a note in the documentation about this.
