### ISSUE TITLE
How to inject a sprite-sheet data object directly into the loader?

### ISSUE THREAD

**Issue by Milewski** [pixijs/pixi.js#3635]
I have been doing this approach so far which pretty much will request this json data with an additional http request... which works!

```js
 Loader.add('../build/animation-sprite.json');
```

however what i want to do is to give the json object directly to the loader....

```js
let animationSprite = require('../build/animation-sprite.json');
Loader.add(animationSprite);
```

which doesn't seem to work.. how do i inject this data directly to the loader to by pass the http request it will further do?

**Comment by megmut** [comment]
If you are using webpack or some kind of external loader, then there is no need to add the JSON to the loader. When you specify the require, it will trigger the file to be bundled in with the rest of your module.. something like this maybe.

`module: {
        loaders: [
            {
                test: /\.json$/,
                exclude: /node_modules/,
                loader: 'json-loader'
            }
        ],
}
`

You can just call your JSON object directly in your code. If you need this data to persist, then you may want to put a global object to store your json in some simple caching system. If you REALLY want to, though I can't recommend, you can force an object into the loader resources. You  may be able to create an instance of the Resource class. Resource type for JSON is type 1. Set the STATUS_FLAGS to 1 << 1, which is complete so it doesn't make a new xmlhttp request. I don't know what the side effects of doing this are though.

<img width="468" alt="screen shot 2017-01-30 at 10 46 32" src="https://cloud.githubusercontent.com/assets/10081046/22418467/79da0134-e6d9-11e6-9a0f-3b19cfe48234.png">

**Comment by Milewski** [comment]
I didn't quite understand what you meant... 

My json data is dynamic generated... But I would like it to be bundled along my js file.. Because it's so small.. It not really necessary to make a new http request just to fetch this such small json data... 

However what I found annoying is that I can't manually tell the Loader 'look, I have this sprite sheet data, please set up it for me' 

Forcing my assets into the loader resource.. How would I define the offset of each asset.. My sprite sheet has at least 30 assets.. If i manually insert those resource.. I wouldn't be aligning them accordingly.

**Comment by megmut** [comment]
Yes, in order to bundle your JSON along with your js file, you need to use an appropriate JSON loader. With Webpack, it will detect that you have required a JSON file, and inject it into your js bundle there.  [JSON Loader](https://github.com/webpack-contrib/json-loader)

I don't understand 'how do i inject this data directly to the loader to by pass the http request it will further do' If you already have the JSON object, why would you inject it into the loader? The loader is only there for making xmlhttp requests. Sorry, I don't quite think I understand what you are trying to achieve.

**Comment by Milewski** [comment]
i dont mean the problem is with webpack... i know i can require a json i'm not on a browser environment but nodejs (aka Electron)

 what i want is this...

suppose i have the following sprite-sheet.json

```json
{
   "meta":{
      "image":"images/animation-sprite.ba87fc57860cb0d066df841e9cb39c75.png",
      "size":{
         "w":3147,
         "h":2899
      },
      "scale":"1"
   },
   "frames":{
      "tree.png":{
         "frame":{
            "x":938,
            "y":1,
            "w":1149,
            "h":926
         },
         "rotated":false,
         "trimmed":false,
         "spriteSourceSize":{
            "x":0,
            "y":0,
            "w":1149,
            "h":926
         },
         "sourceSize":{
            "w":1149,
            "h":926
         }
      },
      "branch-1.png":{
         "frame":{
            "x":1,
            "y":1,
            "w":935,
            "h":1378
         },
         "rotated":false,
         "trimmed":false,
         "spriteSourceSize":{
            "x":0,
            "y":0,
            "w":935,
            "h":1378
         },
         "sourceSize":{
            "w":935,
            "h":1378
         }
      },
   ....
   }
}
```

and then 

```js
PIXI.loader.add('sprite-sheet.json').load((loader, resources) => {})
```

until here everything is okay.. pixi will make a http request to get the sprite-sheet.json .. and make another request to grab the ```images/animation-sprite.ba87fc57860cb0d066df841e9cb39c75.png``` and set up create/name/offset each sprite accordingly with the frames property in the json... 

however what i am trying to do is... skip the sprite-sheet.json request itself... and instead server this Object directly to the ```PIXI.loader.add({...}) ```

**Comment by Milewski** [comment]
this is exactly what i meant.. [https://github.com/pixijs/pixi.js/pull/3676#issuecomment-276355860](https://github.com/pixijs/pixi.js/pull/3676#issuecomment-276355860).. waiting the merge thanks :D

**Comment by staff0rd** [comment]
#3676 now merged
