### ISSUE TITLE
Container.addChild, Container.addChildAt

### ISSUE THREAD

**Issue by midiusRed** [pixijs/pixi.js#3636]
Container.addChild contains
`// ensure a transform will be recalculated..`
`this.transform._parentID = -1;`
`this._boundsID++;`
And Container.addChildAt not have a code, why?

The situation is similar for Container.removeChild and Container.removeChildAt

**Comment by GoodBoyDigital** [comment]
Thanks for sharing, fancy putting a PR together? 👍

**Comment by finscn** [comment]
@GoodBoyDigital  , not only this one point .
I create a PR , please review and test .  https://github.com/pixijs/pixi.js/pull/3640

**Comment by staff0rd** [comment]
#3640 has been merged. :v:
