### ISSUE TITLE
[Suggest] let `filters` be a public property without getter/setter & slice.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3639]
Now , access `filters` with getter/setter.
```
    get filters()
    {
        return this._filters && this._filters.slice();
    }

    set filters(value) // eslint-disable-line require-jsdoc
    {
        this._filters = value && value.slice();
    }
```

First , I don't know why do this . I don’t think their actions make any  sense/value/meaning（please forgive me for my bad english） in the real game.

Second, there will be a strange behavior : 
the codes : 
```
obj.filters.push( f );
obj.filters.pop();
obj.filters.length=0;
```
They can't work （because obj.filters is a clone of real filters in obj ).
 
But in the  real game , changing the filters dynamically  is a reasonable operation.
And change the filters via `obj.filters` is  the most  intuitive way.

**Comment by finscn** [comment]
@GoodBoyDigital  , @ivanpopelyshev  , @bigtimebuddy  ,  what do you think about it ？
Could I open a PR for removing  getter/setter of filters ？

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital introduced slicing in [this](https://github.com/pixijs/pixi.js/commit/32beaaa1c4611b3a626a25085acc1bc74a071a44) commit. I see @finscn's point, but maybe Mat can speak to the rationale for slicing when setting or returning the filters.

**Comment by englercj** [comment]
I think the idea (at the time) was that we wanted you to be able to assign an array to the filters, but then not be able to modify that array unless you called the setter again.

In retrospect, we probably want to allow you to do that. This is a great improvement for v5.

**Comment by finscn** [comment]
Don't forget this in v5.
Now I don't know anything about v5. I don't want to touch any code of it & create any PR for it.
@GoodBoyDigital , @ivanpopelyshev , @bigtimebuddy  @englercj

**Comment by bigtimebuddy** [comment]
@finscn just give us another week to let some of the dust settle on v5 restructuring, then we can start accepting PRs like changing this

 I think not cloning the array is a better and less mysterious API.

**Comment by GoodBoyDigital** [comment]
Removed slice in filter refactor PR 👍
