### ISSUE TITLE
Bizarre artifact on WebGL

### ISSUE THREAD

**Issue by bebensiganteng** [pixijs/pixi.js#364]
Hi,

Something wrong happened when I tried to create a shape with circles.

```
function drawWave(fillColor, amount, boxWidth, radius, offsetX, offsetY, padding) {

  var graphic = new PIXI.Graphics(),
    n = 0;

  graphic.clear();
  graphic.beginFill(fillColor); 

  for(var i = 0; i < amount; i++) {

    var m = (i%boxWidth);
    var nX = m * padding + offsetX + (Math.sin(n) * 10);
    var nY = Math.floor(i/boxWidth) * padding + offsetY;

    if(m == boxWidth - 1) n++;

    graphic.drawCircle(nX, nY, radius);
  }

  return graphic;
} 

stage.addChild(drawWave(0x003566, 5000, 100, 2, 200, 100, 10));
```

Canvas
![screen shot 2013-10-18 at 19 07 35](https://f.cloud.github.com/assets/188012/1359426/37f9235c-37dd-11e3-9b05-1057e1a64d9f.png)

WebGL
![screen shot 2013-10-18 at 19 07 50](https://f.cloud.github.com/assets/188012/1359428/3b18157a-37dd-11e3-99a0-1de54d836408.png)

I'm aware there's a limit on textures, but if the circles were built with points this shouldn't be happening, right? Plus on WebGL the outlines are jagged.

**Comment by mattlockyer** [comment]
Had the same issue with jagged edges, here's a two step solution:

Draw a rect around your shape that uses a transparent fill (you only need to be 1 pixel outside the edge of your shape.
Use graphics.cacheAsBitmap = true;

Example:

var graphics = new PIXI.Graphics();
graphics.lineStyle(6, 0xFFFFFF, 0.0001);
graphics.drawRect(-100, -100, 200, 200);
graphics.lineStyle(4, 0x0000FF, 1);
graphics.drawRect(-100, -100, 200, 200);
graphics.cacheAsBitmap = true;
stage.addChild(graphics);

**Comment by photonstorm** [comment]
Be very careful if you do this *a lot*. It will generate one new canvas object every time you cacheAsBitmap, and it's easy to quickly exhaust the browser.
