### ISSUE TITLE
Tiling Sprite texture position not correct in > 4.3.3

### ISSUE THREAD

**Issue by alexfoxy** [pixijs/pixi.js#3642]
I updated my pixi.js from version 4.3.2 to 4.3.3 but it resulted in the texture position of a tiling sprite I was using being off centre.

See the screen shots below, the circle should sit symmetrically in the grid.

4.3.2:
<img width="146" alt="screen shot 2017-01-24 at 07 27 07" src="https://cloud.githubusercontent.com/assets/151772/22237937/a929205a-e206-11e6-8619-263e34bb498c.png">

4.3.3:
<img width="158" alt="screen shot 2017-01-24 at 07 27 53" src="https://cloud.githubusercontent.com/assets/151772/22237948/b1e4a228-e206-11e6-831c-7f0da9931f99.png">

Did something change or is this a bug?

**Comment by themoonrat** [comment]
Do you have anchors set on it? Might be due to a fix for https://github.com/pixijs/pixi.js/issues/3536

It's the only thing i can think of from the changelog that might effect this https://github.com/pixijs/pixi.js/releases/tag/v4.3.3

**Comment by ivanpopelyshev** [comment]
v3 and v4 had different behaviour. Now, by default its v3 behaviour, but you can change it!

```
tilingSprite.uvRespectAnchor = true;
```

**Comment by alexfoxy** [comment]
Yes, 

`tilingSprite.uvRespectAnchor = true;`

Does the trick!
