### ISSUE TITLE
Nested masks distorted in Chrome with v4

### ISSUE THREAD

**Issue by merachefet** [pixijs/pixi.js#3655]
Using masks on multiple nested objects in v4 causes weird display issues on Chrome Win7 desktop, tested with Chrome 55 and Chromium 54. The inner mask and the sprites it's applied to are drawn in the wrong scale. The amount of distortion seems to be based on position. In this example, two overlapping masks should be creating a donut shape, but the inner mask and sprite are drawn at something like twice the correct scale, creating a crescent instead.

https://jsfiddle.net/0wsugnjk/

The effect is not consistent, it sometimes flickers back and forth between the correct and incorrect scale. It works normally on Chrome for Android and Firefox desktop. Pixi v3 works normally as well.

**Comment by staff0rd** [comment]
I see this on win10 chrome 56 - what's the issue?

![image](https://cloud.githubusercontent.com/assets/6289998/22395476/e11909ae-e593-11e6-9cdf-4c0d502aa0b7.png)

**Comment by merachefet** [comment]
This is Chrome 56 on Win7 32 with an NVIDIA GeForce GTX 550 Ti.

![download](https://cloud.githubusercontent.com/assets/2681169/22395961/f9714b02-e51a-11e6-94e4-44800690665f.png)

**Comment by staff0rd** [comment]
Can you try it on any other browsers?

I just tried on IE11, Edge on Win10.  Also Safari on iPhone 5S.  Can't replicate the issue.

**Comment by merachefet** [comment]
No issue with Firefox or Chrome Android. Tried it with Intel Integrated Graphics, the issue persists.

**Comment by merachefet** [comment]
I've been trying to isolate the difference between v3 and v4 that's causing this. Setting the renderer to the new legacy mode doesn't help.  Neither does forcing each mask to use a separate shader program, like v3 did.  It certainly seems like something is going on with a shader, since the effect is so unstable, but everything looks the same in the shaders themselves. Maybe some kind of GL environment setting? Could just be my GPU is damaged or something, but it's making me crazy that it works perfectly in v3.

**Comment by GoodBoyDigital** [comment]
thanks for checking @merachefet! do you get any errors? or is it simply not  working?

**Comment by merachefet** [comment]
No errors. It seems to be based on Chrome's performance, or something in the rendering environment. For example, opening a second browser window to the same page will cause the effect to flicker on and off. If I capture a normal frame using the WebGL Inspector extension, and step through the same GL calls, the result shows the error where the original frame didn't.
[Here's a video of what I'm seeing.](https://www.youtube.com/watch?v=mbT0k7g57i0)

**Comment by merachefet** [comment]
Bingo! v4 uses the default 4px padding for the mask filter, and v3 didn't. Overriding the padding to zero in the SpriteMaskFilter constructor resolves the problem.

**Comment by merachefet** [comment]
Okay, apparently this is a known stencil bug in ANGLE **D3D9**. I was missing a D3D11 component, and Chrome was using a D3D9 fallback mode. Reinstalling DirectX 11 fixed this. Ugh.
