### ISSUE TITLE
cacheAsBitmap not working for a container

### ISSUE THREAD

**Issue by krojew** [pixijs/pixi.js#3658]
I have a container which holds 135x135 sprites, all 32x32 px. As they never change, this would seem a perfect case for cacheAsBitmap. Unfortunately, setting it to true makes the container disappear entirely, without any message in the console. When not using cacheAsBitmap, the performance is incredibly slow.

**Comment by DubiousDillan** [comment]
I also have this issue. It _used_ to work.

**Comment by GoodBoyDigital** [comment]
Hello! Have you preloaded your assets?

**Comment by krojew** [comment]
Yes. This is the exact TypeScript code for reference:

            // fetch the background texture and create tile textures
            let
                texture = PIXI.BaseTexture.fromImage(map.image, false, PIXI.SCALE_MODES.NEAREST),
                textures: PIXI.Texture[] = [];

            for (let y = 0; y < texture.height; y += this.tileHeight) {
                for (let x = 0; x < texture.width; x += this.tileWidth) {
                    let
                        width = (x + this.tileWidth > texture.width) ? (texture.width - x) : (this.tileWidth),
                        height = (y + this.tileHeight > texture.height) ? (texture.height - y) : (this.tileHeight);

                    textures.push(new PIXI.Texture(texture, new PIXI.Rectangle(x, y, width, height)));
                }
            }

            // we now have tiles, so let's create the background object and render our static background
            let background = new PIXI.Container();
            background.cacheAsBitmap = true;

            for (let y = 0; y < map.rows; ++y) {
                for (let x = 0; x < map.columns; ++x) {
                    let tileSprite = new PIXI.Sprite(textures[map.data[y * map.columns + x]]);
                    tileSprite.x = x * this.tileWidth;
                    tileSprite.y = y * this.tileHeight;

                    background.addChild(tileSprite);
                }
            }

            this.app.stage.addChild(background);

**Comment by GoodBoyDigital** [comment]
I see! You must set cacheAsBitmap after you added the assets - cachingAsBitmap will instantly take a snapshot of the displayObject as it currently is. hope that helps!

**Comment by krojew** [comment]
Already tried setting it just before this.app.stage.addChild(background); but still I get a black rectangle.

**Comment by GoodBoyDigital** [comment]
If you could provide an isolated example for us to test that would be ace. thanks!

**Comment by macguffin** [comment]
Hi Matt I noticed something similar before.

http://pixijs.github.io/examples/#/basics/container.js

if on line 28 I add
container.cacheAsBitmap =true;

container.x = 100;
container.y = 60;
container.cacheAsBitmap =true;
// start animating
animate();

all the bunnys dissapear

Is this correct behaviour?

Cheers

**Comment by GoodBoyDigital** [comment]
its because the assets have not loaded yet, at that point your are caching unloaded textures.
If you give it a little time to load it should work fine 👍 

```setTimeout(function(){
  alert("CACHE")
	container.cacheAsBitmap = true;
}, 3000)```

hope that helps!

**Comment by macguffin** [comment]
so it does, thanks for the tip :)

**Comment by krojew** [comment]
I did some investigating and it seems my texture was not preloaded. Now it works. I think the documentation should have it more explicitly explained.

**Comment by krojew** [comment]
But it seems there's another error - after caching the bitmap, this.app.stage.width suddenly changed from 4320 to ~6500px. Now I have a black rectangle extending my container.

**Comment by GoodBoyDigital** [comment]
Good shout! docs updated here: #3661

Glad its solved 👍

**Comment by krojew** [comment]
Nice. What about that strange resizing of the container? Should I create another issue for that?
