### ISSUE TITLE
PIXI.settings.SCALE_MODE not working

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#3660]
I set `PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;` and it does not work.

Doing `PIXI.SCALE_MODES.DEFAULT = PIXI.SCALE_MODES.NEAREST;` does not work in the latest version either, even though it prints the deprecation message.

**Comment by DubiousDillan** [comment]
However, it works if I disable `cacheAsBitmap` on the container but this really kills performance.

**Comment by bigtimebuddy** [comment]
Hey @DubiousDillan, would it be possible for you to create a [fiddle](https://jsfiddle.net/) or [bin](https://jsbin.com/) that reproduces this issue? It would help us a lot. Thanks.

**Comment by DubiousDillan** [comment]
@bigtimebuddy, okay, I've made a simple JSFiddle but it seems even more broken. When I uncomment the `container.cacheAsBitmap = true;` line, the console has an error and nothing renders.

```VM64 pixi.min.js:10 Uncaught TypeError: Cannot read property 'transform' of null
    at e.updateTransform (VM64 pixi.min.js:10)
    at e.a._initCachedDisplayObjectCanvas (VM64 pixi.min.js:16)
    at e.a._renderCachedCanvas (VM64 pixi.min.js:16)
    at e.render (VM64 pixi.min.js:12)
    at e.PIXI.loader.add.load ((index):75)
    at e.o.emit (VM64 pixi.min.js:8)
    at e.n._onComplete (VM64 pixi.min.js:9)
    at VM64 pixi.min.js:9
    at o (VM64 pixi.min.js:9)
    at e.<anonymous> (VM64 pixi.min.js:18)
e.updateTransform @ VM64 pixi.min.js:10
a._initCachedDisplayObjectCanvas @ VM64 pixi.min.js:16
a._renderCachedCanvas @ VM64 pixi.min.js:16
e.render @ VM64 pixi.min.js:12
PIXI.loader.add.load @ (index):75
o.emit @ VM64 pixi.min.js:8
n._onComplete @ VM64 pixi.min.js:9
(anonymous) @ VM64 pixi.min.js:9
o @ VM64 pixi.min.js:9
(anonymous) @ VM64 pixi.min.js:18
(anonymous) @ VM64 pixi.min.js:9
o @ VM64 pixi.min.js:9
(anonymous) @ VM64 pixi.min.js:18
(anonymous) @ VM64 pixi.min.js:9
o @ VM64 pixi.min.js:9
(anonymous) @ VM64 pixi.min.js:18
(anonymous) @ VM64 pixi.min.js:9
o @ VM64 pixi.min.js:9
(anonymous) @ VM64 pixi.min.js:9
(anonymous) @ VM64 pixi.min.js:9
o @ VM64 pixi.min.js:9
i @ VM64 pixi.min.js:9
n._onLoad @ VM64 pixi.min.js:9
o.emit @ VM64 pixi.min.js:8
n.complete @ VM64 pixi.min.js:9```

Link: https://jsfiddle.net/4jpfqa10/

**Comment by Edisoni** [comment]
It works before transfer methods in version 4.2.1, pls fix.
https://jsfiddle.net/f8190mjq/
![2017-01-30 9 49 39](https://cloud.githubusercontent.com/assets/10086099/22414562/86e40396-e6d1-11e6-91db-2df7c42062b2.png)

**Comment by bigtimebuddy** [comment]
I updated your fiddle to the latest (v4.3.4) and it seems to work: https://jsfiddle.net/1j4vkzn5/3/

**Comment by DubiousDillan** [comment]
@bigtimebuddy, until you uncomment `container.cacheAsBitmap = true;` and run it.

**Comment by bigtimebuddy** [comment]
I have a couple of pieces of information for you that should help:

* First, it's important that `cacheAsBitmap` not be applied to the root object that is rendered. See this [example](https://jsfiddle.net/8sz55dxt/1/)
* Second, there seems to be a bug with RenderTexture respecting the default scale mode. Will work on a PR for this today, and it should be in our next 4.4 release. The work around is to not scale the container you're cacheAsBitmap but instead scale the children. Not ideal, but works (also reflected in that test).

**Comment by DubiousDillan** [comment]
@bigtimebuddy, ah, apologies for the incorrect usage of `cacheAsBitmap` in the example.

Thank you!

**Comment by DubiousDillan** [comment]
@bigtimebuddy, is this uploaded to NPM now? How would I go about installing the version with the fix? Thanks!

**Comment by bigtimebuddy** [comment]
We are waiting on a proper 4.4 release, which might be a week or more. You can use the latest dev release if you want check out the FAQ section of the Wiki for links to the latest dev.

**Comment by DubiousDillan** [comment]
@bigtimebuddy ah, I've had a look and the only thing in the Wiki is a link to a "compiled" version of PIXI. I'm using it with NPM though and compiling the project using Browserify. How would I go about getting the dev version for NPM?

I've tried to download the dev branch as a zip file and `npm install it` but even then it's using some sort of strange format. I.e. `import * from X` etc.

**Comment by bigtimebuddy** [comment]
Because we don't checkin our build files, you will need to build Pixi locally. If you have already npm installed from the dev branch simply go into node_modules and run "npm install && npm run lib" then try to rebuild your project.
