### ISSUE TITLE
Can't exclude moudle when build PIXI.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3663]
Because the bug #3662 , I have to build pixi without  `interaction`.

But I found 
```
npm run build -- --exclude interaction
```
is useless.

the  `--exclude interaction` can't be pass to pixify.

What can't do for it ?

**Comment by bigtimebuddy** [comment]
You need to do "npm run dist -- --exclude interaction". Use dist not build.

**Comment by bigtimebuddy** [comment]
https://github.com/pixijs/pixi.js/blob/dev/README.md#how-to-build

**Comment by finscn** [comment]
@bigtimebuddy  , I found  use 'build' is OK .

If use  two `--` , the parameters will be pass two level.

```
npm run build -- -- --exclude interaction
```
npm run build **_-- --_** --exclude interaction

I think you could update the document.
