### ISSUE TITLE
Touch events are no long working after MockPointer changes for #3375 (#3546) in Cocoon.

### ISSUE THREAD

**Issue by artsjedi** [pixijs/pixi.js#3668]
Today I tried the dev breanch with MockPointer changes #3375 (#3546). after it touch events are no long working.

I got those error messages when I touch the screen.

I tried on ludei's Cocoon packing , in iOS and Android.

here are the results:

(iOS)
![ios](https://cloud.githubusercontent.com/assets/2263037/22397862/679df138-e562-11e6-8870-1b7e1e22d8f2.jpeg)

(Andoid)
![android](https://cloud.githubusercontent.com/assets/2263037/22397861/679dc06e-e562-11e6-8e3f-6d7245807c6b.jpeg)

**Comment by andrewstart** [comment]
Does Cocoon not have a TouchEvent class?

**Comment by GoodBoyDigital** [comment]
Hi , touch /mouse seemed to break when I updated to latest dev branch on an
app we are developing. Not 100% sure why yet!

**Comment by artsjedi** [comment]
@andrewstart  Yes Cocoon does have a TouchEvent class.

**Comment by andrewstart** [comment]
Does changing https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1387 to `if (this.supportsTouchEvents && event instanceof window.TouchEvent)` fix the problem? It shouldn't, but maybe Cocoon works in ways that I am unaware of.

**Comment by artsjedi** [comment]
sorry, i didint find the line you mentioned.

**Comment by andrewstart** [comment]
Oh, merges messing up the line numbers 🙄. The relevant line is now https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1444

**Comment by artsjedi** [comment]
Nothing changes, by changing that line.  however, thanks to some "log events" the error is clear now.

![screenshot_2017-02-06-23-37-19](https://cloud.githubusercontent.com/assets/2263037/22674157/969c25d0-ecc5-11e6-9d7e-5372dd84017c.png)

**Comment by artsjedi** [comment]
OOOooKaay ,  I found the bug..

`event `is not defined in this scope.
` if (navigator.isCocoonJS && event.pointerType === 'touch') {`

interactionEvent is the correct name for this variable
`if (navigator.isCocoonJS && interactionEvent.pointerType === 'touch') {`

solve the error  here #3703

**Comment by andrewstart** [comment]
That was the only problem? Wasn't the error thrown elsewhere?

**Comment by artsjedi** [comment]
By testing my game app in CocoonJS everything else is working good. It seems that it is the problem.

It makes sense cause the first part `navigator.isCocoonJS ` was evaluated false to the most users, Only if evaluate true (in case of using CocoonJS) it will test the second part ` event.pointerType === 'touch'` and then it will throw an "undefined variable" error. 

We got this error cause we are testing directaly on cocoon.
