### ISSUE TITLE
SVG Resolution Not Working

### ISSUE THREAD

**Issue by megmut** [pixijs/pixi.js#3669]
When I try to create a texture using SVG, passing a resolution makes no difference to the size.

PIXI.Texture.fromImage('assets/image.svg', true, 0, 2);

I would have expected the above to double the size of the SVG when the texture is created. However regardless of the DPR of the  @screen, the texture if being created at the same size. 
http://pixijs.download/release/docs/core_textures_BaseTexture.js.html - line 235/6

Am I misunderstanding how the resolution of SVG's are being handled? 

Thanks, Nick

**Comment by staff0rd** [comment]
Seems to be working for me;
https://codepen.io/staff0rd/pen/egVYaR?editors=0010

Are you using latest?

**Comment by megmut** [comment]
Hi, sorry about the delay. 

I'm preloading my SVG as an SVG file, not the data URI. However, when I try to convert my SVG to Data URI, nothing loads. 

I shared the SVG here, as I can't upload it because the file type is not supported. [sharesvg](http://svgshare.com/i/em.svg).

May I ask how you generate your URI?

**Comment by staff0rd** [comment]
Still works with URLs; http://codepen.io/staff0rd/pen/ggBRVL?editors=0010

Check the console on your pen - doesn't look like you can use that host.  Also, your svg doesn't seem to display anything.  Not sure how I got the URI, think I just googled a conversion service and used the first one.

**Comment by megmut** [comment]
@staff0rd Hey, so I was finally able to debug the issue. You were correct, there is nothing wrong with how it works in PIXI.

The issue was with Webpack. When serving SVG files over a webpack-dev-server, the scaling wasn't working, however when I ran a production build, or pulled the file in from an external resource, then it worked fine. 

I hope this saves someone else some time as I've spent too many hours realising that Webpack was the issue. Thanks guys!

**Comment by megmut** [comment]
@Pandan Hey, sorry to hear you're having the same issues! I didn't dig deep enough to know what in the file was actually being changed, though.. I might take a guess and say it's encoding. I'm unsure if webpack-dev-server is handling files gziped to speed things up. 

My work around actually isn't much of one. I ended up creating an abstract class for my SVG's, and bundling them with the code, so there is no need to load them at all (reducing xhr calls).

The class looks a little something like this...

`
export default class SVG {
    public static get hourGlass():string {
        return 'data:image/svg+xml;charset=utf8,<svg></svg>';
    }
}
`

You can place the actual contents of your SVG file in between the SVG tags, you should see them when you open the file with any ide. Then to use, I simply did:

`
var texture = new PIXI.Sprite.fromImage(SVG.hourGlass);
var x = new PIXI.Sprite(texture);
`

Hope this is some help!

**Comment by Pandan** [comment]
@megmut Thanks for the tip! I think I am going to see if I can configure webpack to just copy the svg files or something. Have alot of svgs. But if I don't solve it I will try your solution.
