### ISSUE TITLE
NineSlicePlane does not play nice with spritesheet texture

### ISSUE THREAD

**Issue by Dimous** [pixijs/pixi.js#3671]
Hello!

I made spritesheet with TexturePacker, then loaded atlas and placed sprites with corresponding textures on stage. The result was as expected.
Then I decided to make these textures scalable. It turned out that the NineSlicePlane used whole image, instead of a specified patch.

Demo - https://dimous.github.io/pixi-ninesliceplane-spritesheet-bug/

**Comment by whizzkid** [comment]
Yup. I've reported on this when I added the NineSlicePlane #2677  I see that the ticket is closed. but the problem is still there..

**Comment by jeebus3000** [comment]
I see, @ivanpopelyshev didnt add his "special function" https://github.com/pixijs/pixi.js/pull/2688#issuecomment-231782419

**Comment by alamboley** [comment]
Hey any news on this? @ivanpopelyshev
