### ISSUE TITLE
SVG with width and height in pts

### ISSUE THREAD

**Issue by VsevolodZakharov** [pixijs/pixi.js#3674]
In the _loadSvgSourceUsingString() there is regexp to fetch width and height from SVG string which expects only pixels as units. Could that also process pts? (convert to pixels on base on DPI - it is tricky in JS but is possible AFAIK) There are a lot of SVGs with pts in the header and they throw an exception there.

**Comment by staff0rd** [comment]
Hey @VsevolodZakharov can you supply an SVG that breaks this?  (Bonus points for [pen](https://codepen.io) that displays this issue against latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)).

**Comment by englercj** [comment]
Hey @VsevolodZakharov have you had a chance to provide a reproduction case for this so we can track it down?

Thanks!

**Comment by VsevolodZakharov** [comment]
@englercj , any SVG with pts in the header for example:
`<!DOCTYPE html>
<html>
<body>

<svg height="20pt" width="20pt">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
  Sorry, your browser does not support inline SVG.  
</svg> 
 
</body>
</html>`
