### ISSUE TITLE
An issue in Chrome for Ubuntu only.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3677]
My game runs correct on  iOS , Android 6  ,  macOS & windows.
But  in Chrome on Ubuntu  , there is a issue (see image):
<img width="688" alt="2017-01-30 11 55 51" src="https://cloud.githubusercontent.com/assets/288367/22429992/93c57b32-e747-11e6-86d3-afea8226951c.png">

Then the canvas become  black.

Could you help me ,  please ? 

The 'code' is an all-in-one  file with pixi.min.js .

n.upload is Texture.prototype.upload
t.updateTexture is TextureManager.prototype.updateTexture
o.emit is texture.baseTexture.emit
e.updateTexture is Text.prototype.updateTexture
e.updateText is Text.prototype.updateText

**Comment by ivanpopelyshev** [comment]
You sure its not related to your videodrivers version?

**Comment by finscn** [comment]
@ivanpopelyshev  , I'm sure.
Because it's not always incorrect.  The game could run correct in common.
But when there is something use Text or TilingSprite , this issue will appear.

There are some error in the log of Chrome （not in the browser console， it's in terminal ） : 

[103721:103721:0131/002755.040054:ERROR:gles2_cmd_decoder.cc(16945)] [.DisplayCompositor-0x5556d12684d0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[103721:103721:0131/002755.049873:ERROR:gles2_cmd_decoder.cc(9408)] [.DisplayCompositor-0x5556d12684d0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

**Comment by ivanpopelyshev** [comment]
Are you experiencing it in latest pixi, or in yours, that is customized? :)

**Comment by finscn** [comment]
use the last PIXI.  There is a similar thread :  http://www.html5gamedevs.com/topic/23928-win10-chrome-with-pixi/

**Comment by finscn** [comment]
The logic is like this: 
1. When render some sprites and  a **Text object** :  everything is OK.
2. Then  I 'open' a panel ,  this  issue appeared. 
 the panel is a TilingSprite , the image is a Canvas element.
The call stack display : the issue is thrown be the **Text object**

**Comment by ivanpopelyshev** [comment]
Try legacy mode? MAX_TEXTURES=1 and all that?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/pull/3630 is going to be merged soon, may be it can help you

**Comment by finscn** [comment]
Thanks. I'll be waiting #3630  :)

**Comment by finscn** [comment]
@ivanpopelyshev  , I've updated. But this issue is still  be there.

**Comment by ivanpopelyshev** [comment]
@finscn :(  anyway it looks like chromium bug. "fence" is multithreading term, its not related to our lib. Search chromium bugtrack?

Also, just added WIP of new plugin: http://pixijs.github.io/examples/#/layers/lighting.js , it'll be ready this week :) may be we'll solve your "mask+rect+blur" issue

**Comment by finscn** [comment]
@ivanpopelyshev  I don't know TS . If PIXI is used TS , I can't  custom and extend it anymore . So sad.

**Comment by ivanpopelyshev** [comment]
Basically its the same. pixi_display is actually "PIXI.display", you can use and extend things like before. But at the same time, you can do

```
npm install types@pixi.js
npm install pixi-display
```
and your IDE (webstorm or vscode) will autocomplete your expressions both in js and ts.

**Comment by finscn** [comment]
If I want to do something on(or in? Bad english)  TS file , I have to understand it. But I don't.

I know I could learn TS . But I'm an old(35 years old)  game developer , my most time is spent on 'write game with a mature + stable engine & technology' , not  on new language.

I love algorithm ， AI，graphics，geometry，math.
But I hate new language (not only compute language, include English , haha).

**Comment by ivanpopelyshev** [comment]
sooooo old! I'm 30.  Yeah, I'm font of math and algorithms too! Did you take part in ACM ACPC?

Also TS is just documented javascript, there's nothing to learn except module/namespace structure and may be interfaces. Imagine interfaces and types as jsdocs declarations and it should be fine.

**Comment by finscn** [comment]
I didn't  take part in ACM ACPC , I love them ,but not good at them . :)  

If PIXI will use TS completely ， I think I have to learn TS，  There may not be another choice .
Tears ...

**Comment by ivanpopelyshev** [comment]
I really don't know what part are you scared of in that code. For me it looks like JS. But of course, I was java developer for long time and now I'm writing apps on Kotlin...

**Comment by macguffin** [comment]
Ivan is correct. TS isn't too scary and webstorm takes care of all the
boring bits. If you ever did any actionscript work (showing my age now) it
will seem familiar.

**Comment by finscn** [comment]
My first game is write by J2ME  when I was a young boy, So I'm good at Java 1.3 to 5.0   ( never used 6 7 8 9 ...) .  And I  learned ActionScript too when it was popular.

But now I don't love to learn TypeScript. Maybe I become lazy .  :'(

**Comment by ivanpopelyshev** [comment]
@finscn You have to learn TS to improve your Js code. You also have to learn Kotlin because its new java.

**Comment by tuco-lc** [comment]
For us the GL_INVALID_OPERATION : glGenSyncTokenCHROMIUM occurs with Chrome browsers on Android.  The error does not happen with v4.1.1, but happens if using Pixi v4.2.1 -> v4.3.4

**Comment by englercj** [comment]
Is this still active in the latest version (v4.5.0)?

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
