### ISSUE TITLE
[Suggestion] Move the Feature about Canvas2D into a mix-in module.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3684]
In current PIXI , the feature about Canvas2D is build-in , it's hard to be exclude when build PIXI.

Most browsers support WebGL , and many features of PIXI need WebGL . The Canvas2D become in the minority.

**Comment by bigtimebuddy** [comment]
We are already planning on this for v5 of Pixi which will start to separate out the core pieces into different packages/modules. CanvasRenderer will be easier to include or exclude as a project requires. Eventually, we might be able to deprecate Canvas altogether. But we hear you @finscn!

**Comment by jeebus3000** [comment]
Hey, @fscn check this out - https://englercj.github.io/2016/08/24/composition-ecs/

> Recently I’ve been working on building Fae, a modular 2D renderer. My main driving force for building the project was exploring the question “If I was building Pixi.js, from scratch, today; what would I do?”

**Comment by finscn** [comment]
Thanks . I see & I will be waiting .
