### ISSUE TITLE
Error with with mouse events on latest dev build on destroyed sprites

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#3685]
Tried a quick replication via the examples page, but couldn't get it to happen, but it occurs on my game after updating to the latest dev build.

The issue comes on line 945 in interactionManager
`this.dispatchEvent(displayObject, 'pointerdown', interactionEvent);`
You see, I had a sprite that listened for this event, and destroyed itself
The error would occur because a few lines later on line 961
`displayObject.trackedPointers[id].leftDown = true;`
The trackedPointer object gets cleaned when the sprite is destroyed earlier, so when a few lines later it gets here, displayObject.trackedPointers[id] no longer exists

**Comment by bigtimebuddy** [comment]
Have you tried to reproduce this aside from the examples?

**Comment by themoonrat** [comment]
I can reproduce every time on my game. Will try later to create a fiddle to replicate

**Comment by bigtimebuddy** [comment]
@starakaj or @andrewstart might have thoughts on this error, since they were the most recent folks to touch it. A fiddle would certainly help.

**Comment by starakaj** [comment]
Looks like this is a new bug with 8fe33af3. I think I remember @andrewstart asking about making some changes to the interactiveTarget mixin, which are probably necessary but also would cause this bug.

**Comment by themoonrat** [comment]
Ok, ignore, it's fine, an issue on my libs. For some components I'm a bit more aggressive cleaning properties on destroy, and it was touching this one, when by default PIXI does not clear this object on destroy.

Sorry all

**Comment by bigtimebuddy** [comment]
No worries.
