### ISSUE TITLE
[AD] My game with PIXI.js  is on Steam Greenlight. Could you give it a up vote ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3686]
The game is my first game based on HTML5 tech. on Steam.

Though it's just a mini game , I hope it could  pass  Greenlight.

Could you give it a up vote ?  Game url : 

http://steamcommunity.com/sharedfiles/filedetails/?id=839510594

Thank you.

( I will close this issue after 2017-02-05 , give me some days please )

**Comment by ivanpopelyshev** [comment]
one more steam dev! yay!

**Comment by ivanpopelyshev** [comment]
btw, i wonder why no one invited you to slack group yet.. Gimme an email? :)

**Comment by finscn** [comment]
finscn{a}google's email

@ivanpopelyshev  , Thanks

**Comment by staff0rd** [comment]
Very cool @finscn, voted.  Any chance of a playable demo/beta?

**Comment by kaansoral** [comment]
Likewise, voted

**Comment by finscn** [comment]
@staff0rd  , I will upload the  beta version  on  itch.io  when it's ready :)

**Comment by englercj** [comment]
Closing this since it is not really the place for this. Good luck anyway @finscn.
