### ISSUE TITLE
[question] Render loop with new Ticker vs rendering with shared ticker

### ISSUE THREAD

**Issue by CharlesHolbrow** [pixijs/pixi.js#3687]
What are the implications of using a `new Ticker` for the main render loop vs using a `PIXI.ticker.shared`?

I noticed the [Application](https://github.com/pixijs/pixi.js/blob/dev/src/core/Application.js) helper class creates a new Ticker instead of using `PIXI.ticker.shared`. 

Doesn't this mean that pointer events from the interaction manager (which uses the shared ticker) might go out of sync with the rendering ticker? 

In the [dragging example](https://pixijs.github.io/examples/#/demos/dragging.js), the Application class is used at the same time as the events triggered by the interaction manager. Is this intentional?

**Comment by themoonrat** [comment]
I would make the argument that the render loop _should_ be a separate ticker to PIXI.ticker.shared. For example, imagine you wanted to pause everything on screen by stopping the ticker; you wouldn't want interactions to also be paused, you'd want them to carry on as normal.

**Comment by bigtimebuddy** [comment]
That was the intention (^@themoonrat) with the Application class. But the use-case you describe is more advanced. There's an argument that using the shared ticker would help unify all the loops used by PIXI, therefore making it easier to pause everything at once. I created a PR #3688 to allow the shared Ticker's usage in Application.
