### ISSUE TITLE
Graphics Circle gets distorted on mobile under certain circumstances

### ISSUE THREAD

**Issue by theplatapi** [pixijs/pixi.js#3690]
When setting a graphics object's position to high values, the graphics circle gets distorted on mobile devices. Antialiasing fixes the distortion somewhat, some devices do not support it. In the below example I disabled antialiasing so it's easier to test. 

[Graphics positioned and circle distortion](https://codepen.io/anon/pen/ygjMyN?editors=0010)
[Graphics not positioned and circle not distorted](https://codepen.io/anon/pen/rjvyaM?editors=0010#0)

Screenshots from the iPad Air which suffers from the problem the worst since it lacks antialiasing.

**WebGL**
![ipadwebgl](https://cloud.githubusercontent.com/assets/5661209/22584064/40193216-e9a5-11e6-984e-6b0e4dd2b55c.PNG)

**Canvas**
![ipadcanvas](https://cloud.githubusercontent.com/assets/5661209/22584099/678008d4-e9a5-11e6-9b7b-66f3e91e0a5e.PNG)

Even for devices with antialiasing, there are leftover artifacts. Below you can see that the circles are sometimes not aligned. This is from the Moto X, which supports antialiasing.

![androidwebgl-c](https://cloud.githubusercontent.com/assets/5661209/22583993/da90e470-e9a4-11e6-99ef-4cd08f57b666.png)

[Here](http://pastebin.com/3Z3PTbYx) is the output from webglreport.com for the iPad Air in case it helps.

**Comment by ivanpopelyshev** [comment]
> When setting a graphics object's position to high values, the graphics circle gets distorted on mobile devices

Can't fight that, its precision problem. Use "graphics.position" to specify "big" part of your circle coordinates.

**Comment by theplatapi** [comment]
Can you clarify what you mean about the big part of the circle coordinates?

**Comment by ivanpopelyshev** [comment]
```
var bad = new PIXI.Graphics();
bad.drawCircle(10000, 10000, 50);
```

vs 

```
bad = new PIXI.Graphics();
bad.position.set(10000, 10000);
bad.drawCircle(0, 0, 50);
```

**Comment by staff0rd** [comment]
@ivanpopelyshev is this something that needs to be fixed in pixi or a limitation of the browser?

**Comment by theplatapi** [comment]
@ivanpopelyshev Out of curiosity, which part of the graphics pipeline is having the precision issue? I ask because the vertex shader for my Macbook Pro and iPad both report [-2<sup>127</sup>, 2<sup>127</sup>] (23).

**Comment by ivanpopelyshev** [comment]
@staff0rd @theplatapi shaders. Somehow precision on iphones and ipads is very bad. Its certainly not (23)

**Comment by theplatapi** [comment]
In case it helps anyone, I fixed this by using several dozen graphics objects to add up to dimensions of about 1000x1000 instead of one large one, and wrote a manager to delegate which one to write to. I found that the iPad Air starts to lose precision after 64x64.
