### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by LegitSoulja** [pixijs/pixi.js#3693]
Hey, I am wondering if there's a solution to my problem..

My problem is that I want the child container, to always have a z-index higher than the other children. 

Basically, think of a game with a leaderboard. I'm having that drawn into a container, and added to the main container, but the problem I stated is what I'm currently facing. 

Is this not the use of containers? Or, how could I achieve with what I'm trying to do? 

BTW: I've found solutions as to re-organizing the array, but that is not an efficient way of doing so, and then again, im already using a sorting system to sort out the other children.

I've tried placing the child at an index, `stage.childrens.length + 1`, and some high number as `9999`, but looks as if I cannot do that. Currently, im left with no more options to work with.

If anyone can help in which what I shall do that would be great. Thanks.

**PIXI** 

> would be more awesome if a z vector for a container,sprite, and or object(child) existed.

**Comment by ivanpopelyshev** [comment]
This one: https://github.com/pixijs/pixi-display
Or new version (unstable but more stuff): https://github.com/pixijs/pixi-display/tree/layers

**Comment by staff0rd** [comment]
As @ivanpopelyshev notes, pixi-display is a great plugin that will let you set z array on objects regardless of their hierarchy in the scene.

Another way, without using plugins, would be to have parent containers that represent the main objects in your scene (scoreboard, game area) ordered such that the scoreboard is in front.  Then when you're messing around with adding/removing elements to your game, you only do so inside the game area container and the scoreboard always stays in front.

**Comment by LegitSoulja** [comment]
@ivanpopelyshev @staff0rd Thanks, I'll try this out. Hopefully it works.
