### ISSUE TITLE
ParticleContainer shadow?

### ISSUE THREAD

**Issue by Cyral** [pixijs/pixi.js#3694]
Hello,

Is there a way to add a shadow to a particle container? I want to add a shadow to blocks on a tilemap by using a blur filter. I've been using the particle container to render tiles quickly by recycling the sprites used for each and changing the texture which is derived from a base texture (so each tile uses a different frame of that texture). I assume this is the best way to render tiles in Pixi.+

Since it doesn't look like the particle container supports filters, can it be rendered to another texture with a blur effect applied? (So the blurred texture would then be drawn with a black tint behind the particle container to create a shadow)

**Comment by ivanpopelyshev** [comment]
Best way to render tilemaps is https://github.com/pixijs/pixi-tilemap 

But to make your current solution work, simply add particle container into another container and specify filterArea for it, because particle container just cant calculate the bounds of its children.

**Comment by Cyral** [comment]
@ivanpopelyshev Thank you for the quick reply. Is there a way to copy or render the contents of the particle container (or tilemap renderer) to another texture so I can blur it? The idea is to draw the background tiles, then a blurred and darkened version of the foreground, and then the foreground tiles, so that the foreground has a shadow over the background.

**Comment by ivanpopelyshev** [comment]
Yep, render it to renderTexture first. There'll be new ways to do it without renderTexture later ;)
 
```
renderer.render(container, renderTexture);
```
