### ISSUE TITLE
Right click on a container, sprite or graphics, does not fire any events.

### ISSUE THREAD

**Issue by m-ahmadi** [pixijs/pixi.js#3695]
If I define an event handler for a Pixi element (DisplayObject: container, sprite, graphics), and on the 'mousedown' event (or some of the other events),
the handler get's fired when clicking with the left click of the mouse,
and it gets fired when clicking with the middle click of the mouse,
but when clicking with the right click nothing happens,
and the browser context-menu comes up that says `save image as, copy image, etc, etc.`

So basically there is no right-click in a PIXI App, is there?

I read from [here](https://github.com/pixijs/pixi.js/issues/36) that by doing this:
```
document.querySelector('body > canvas').addEventListener('mousedown', function(e) { console.log('native', e.button, e); }, false);
stage.mousedown = function(e) { console.log('stage', e.originalEvent.button, e.originalEvent); };
```
You should get the following result:
```
// left-click:
stage 0 MouseEvent
native 0 MouseEvent

// right-click:
stage 2 MouseEvent
native 2 MouseEvent
```
But I get this:

```
// left-click:
stage 0 MouseEvent
native 0 MouseEvent
// right-click:
native 2 MouseEvent
```

anyways the following does not work either:
```
var renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, {backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();
stage.interactive = true;
stage.hitArea = new PIXI.Rectangle( 0, 0, 100000, 100000 );
stage
	.on('mousedown', down)
	.on('touchstart', down)
	.on('mouseup', up)
	.on('mouseupoutside', up)
	.on('touchend', up)
	.on('touchendoutside', up);
animate();
function animate() {
    requestAnimationFrame(animate);
    renderer.render(stage);
}
function down(e) { console.log(e); }
function up() { console.log(e); }
```

**Comment by ivanpopelyshev** [comment]
```
stage.hitArea = new PIXI.Rectangle( -100000, -100000, 100000, 100000 );
```

should be 

```
stage.hitArea = new PIXI.Rectangle(0, 0, 100000, 100000 );
```

**Comment by m-ahmadi** [comment]
That's right, I forgot to put my multiplication in.
I meant it like this:
new PIXI.Rectangle( -100000, -100000, 100000 * 100, 100000 * 100 );
Basically I meant a massive huge big hitArea.
Still no event fires when right-clicking.

**Comment by andrewstart** [comment]
Is this in dev or a current release? I believe that right clicks should work the same as left clicks, but in dev we just did a major refactor of the InteractionManager and it is possible that some stuff got lost.

**Comment by m-ahmadi** [comment]
Just tested it with v4.3.4 dev and release.
nothing fires when right-clicking. (only left and middle click)

**Comment by staff0rd** [comment]
Are you able to supply a [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by andrewstart** [comment]
Hmm, in http://pixijs.github.io/examples/?v=dev#/basics/click.js if I change the `mousedown` event that it is listening for to `rightdown` or `rightup`, it all seems to be working as intended - mousedown/mouseup for left clicks, rightdown/rightup for right clicks.

**Comment by m-ahmadi** [comment]
Yeah! It seems 'pointerdown' event does not have this problem.
[I tried to test all the events](http://codepen.io/mohammad-ahmadi/pen/jyKmrV)
change lines 40 through 62 to test different events.

**Comment by andrewstart** [comment]
The way the system is designed is that `mousedown`, `mouseup`, `mouseupoutside`, and `click` are all for left clicks, and that `rightdown`, rightup`, `rightupoutside`, and `rightclick` are all for right clicks.

**Comment by like2d** [comment]
@andrewstart Having some issues getting the events to work properly when using a wacom (intuos 3).
Pointerevents seem fine, using rightup, mouseup, etc dont seems to trigger..

Application tested and working using touchpad/trackpad/mouse.

Normally using pointerevents would be good enough, but since I need to use rightdown/up specifically this is a bit of a hassle. Or am I missing something?

**Comment by themoonrat** [comment]
In the event data from a pointerdown event, you can look at 
e.data.originalEvent.button to see which buttons were pressed. 

(In fact, that's what PIXI does internally to say whether something was a right click or not; looks to see if button === 2. I think in the future we should deprecate the separate right click versions... I think devs should look at the event data and decide what to make of it themselves!)

**Comment by like2d** [comment]
Good one, gonna test that, thnx

**Comment by andrewstart** [comment]
See also: https://www.w3.org/Submission/pointer-events/#chorded-button-interactions

**Comment by like2d** [comment]
@themoonrat @andrewstart Works like a charm when using just pointerevents + switching manually. 

Thanks guys!
