### ISSUE TITLE
Possible issue with Matrix constructor

### ISSUE THREAD

**Issue by JessicaNeary** [pixijs/pixi.js#3698]
While creating tests for Matrix.js, I noticed the constructor can only create matrices with the default values. 
i.e: `new PIXI.Matrix(2, 2, 2, 2, 100, 100)` will create a matrix with the default values of a = 1, b = 0, c = 0, d = 0, tx = 0 and ty = 0.

This is not necessarily an issue, as custom Matrix values can then easily be set using set(), but as this differs from all the other PIXI object constructors I looked at, I wasn't sure whether or not it was an intentional design choice.

**Comment by bigtimebuddy** [comment]
That's correct, looks like Matrix doesn't have any constructor arguments: https://github.com/pixijs/pixi.js/blob/dev/src/core/math/Matrix.js

Would be interested in a pull request to add it, if you're up for it.

**Comment by JessicaNeary** [comment]
Sure thing, I'll starting working on that now
