### ISSUE TITLE
Tests broken locally

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi.js#3701]
I think it has something to do with loader, haven't figured out the fix yet;

~~~
C:\git\pixi.js\dist\pixi.js:23561 Uncaught TypeError: Cannot read property 'naturalWidth' of null
update @ C:\git\pixi.js\dist\pixi.js:23561
_sourceLoaded @ C:\git\pixi.js\dist\pixi.js:23883
source.onload @ C:\git\pixi.js\dist\pixi.js:23653
~~~

**Comment by staff0rd** [comment]
Isolated to `test/core/SpriteSheet.js`

Quick fix is to comment out SpriteSheet from test\core\index.js;

~~~javascript
require('./Sprite');
//require('./Spritesheet');
require('./TilingSprite');
~~~

ping @bigtimebuddy

**Comment by bigtimebuddy** [comment]
Possibly a Windows compatibility issues with the Spritesheet tests (builds fine on Mac). I'm firing up my virtual Windows to try to reproduce.

**Comment by bigtimebuddy** [comment]
@staff0rd can you please review #3702?
