### ISSUE TITLE
"INVALID_VALUE: texSubImage2D: no pixels" error on creating a 100x100 RenderTexture 

### ISSUE THREAD

**Issue by TerryHibbert** [pixijs/pixi.js#3705]
Using the value of **100**  as the size of a RenderTexture like this:
> var brt = new PIXI.BaseRenderTexture(**100**, **100**, PIXI.SCALE_MODES.LINEAR, 1);
var rt = new PIXI.RenderTexture(brt);

...produces these errors on my Mac (Windows untested):
- Chrome: "WebGL: INVALID_VALUE: texSubImage2D: no pixels"
- FireFox: "Error: WebGL: texSubImage2D: Source must not be null."

This is reproducible in the examples if you change line 17:
https://pixijs.github.io/examples/#/basics/render-texture.js

There are no errors for values of 99 or 101, but I'm kinda set on 100.

**Comment by staff0rd** [comment]
Confirmed also on Win10, Chrome 57

**Comment by staff0rd** [comment]
pen; https://codepen.io/staff0rd/pen/XpBBMy?editors=0010

**Comment by megmut** [comment]
I'm also getting this, Macbook OSX, Chrome and Firefox. Also, in FF, getting this additional info error

Error: WebGL: texSubImage2D: Source must not be null.  pixi.min.js:8:18913
Error: WebGL: drawElements: This operation requires zeroing texture data. This is slow. pixi.min.js:14:26606

**Comment by eranimo** [comment]
Still happening in Chrome 69. Related issue: https://github.com/pixijs/pixi.js/issues/3372
