### ISSUE TITLE
PIXI-side NeutrinoParticles integration.

### ISSUE THREAD

**Issue by ymiroshnyk** [pixijs/pixi.js#3708]
This is not actually an issue. This is a request for integration for [NeutrinoParticles](https://neutrinoparticles.com/)

I made external variant of such integration (without changing any framework code). You can find it [here](https://github.com/ymiroshnyk/neutrinoparticles.js/tree/master/dist-PIXI). My integration is a kind of hack, because I need to reset some internal renderer features from outside. And also I'm not a JavaScript guy. My land is C++, and I don't actually know, how you guys develop your code and how you glue it together to have single .js file. 

So, if you like NeutrinoParticles, you could make full integration (internal renderer and object) for effects. My code is a good base. It is well optimized, uses generic WebGL calls and it works well with both Canvas and WebGL renderers. But, I think it would be much better to use internal shaders, vertex buffers internal loader and etc.

I could make any support for such integration and will be happy to see official PIXI's support for NP.

The video tutorial for the Editor are not well organized and they need for updated, but you still can learn how to make effects on different levels of complexity. I'm working on them hard.

**Comment by ivanpopelyshev** [comment]
Awesome! I can help with it a bit later :)

**Comment by ymiroshnyk** [comment]
@ivanpopelyshev Great :) I can't find your email. And I didn't really understand where should I join to.

**Comment by ivanpopelyshev** [comment]
@ymiroshnyk ivan.popelyshev@gmail.com

**Comment by englercj** [comment]
If this gets done, it will certainly be a plugin; not in the core library. Good luck to anyone wanting to work on this! Sound awesome!
