### ISSUE TITLE
Animated Sprite Current Time Infinity on Tab Change

### ISSUE THREAD

**Issue by megmut** [pixijs/pixi.js#3709]
Hey guys, I found an issue with Animated Sprites / Movie Clip. When I change tabs with an animation running, the whole game breaks.

When you have a running animation, the current frame is calculated with this:

`
AnimatesSprite.js 372: var currentFrame = Math.floor(this._currentTime) % this._textures.length;
`

However, when you change tab, this._currentTime is being set to Infinity, and so this._currentFrame is being set to NaN. This in turn causes this._textures[this._currentFrame] to return undefined and then the renderer crashes because an invalid texture has been set on the sprite.

I did a quick isFinite stop this from breaking the renderer.

`
        get: function get() {

        if(!isFinite(this._currentTime)) {
            this._currentTime = 0;
        }

        var currentFrame = Math.floor(this._currentTime) % this._textures.length;       

        if (currentFrame < 0) {
            currentFrame += this._textures.length;
        }

        return currentFrame;
}
`

Hope this might help someone else too!

**Comment by staff0rd** [comment]
Hi @megmut a PR or a [pen](https://codepen.io) that displays this issue against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js) or both would be great ;)

**Comment by themoonrat** [comment]
@megmut Sorry to bother you again, but a pen / fiddle to replicated this issue for us would be much appreciated!

**Comment by megmut** [comment]
Sorry I completely forgot.. let me try and get one done tonight :)

**Comment by themoonrat** [comment]
@sorry to bug you again @megmut - It's been a while now! Just wanna make sure this isn't an issue going forward. It's not something I am able to reproduce here
