### ISSUE TITLE
[BUG] When I exclude `interaction` & `accessibility`, The last PIXI can't be used.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3710]
Because deprecation.js use it.

**Comment by bigtimebuddy** [comment]
We could probably easily add some `if` checks within the deprecations file to check whether these sub-components are actually included. **Would welcome a PR for that.** The only challenge here is that this deprecations file is not organized well.

Long-term, the architectural approach would be to create a more discrete plugin architecture where developers have more options around which things they want to include that doesn't require custom building. Likely, this is a feature for v5.

**Comment by jeebus3000** [comment]
May I chime in? @englercj re-engineered PIXI (_or should I say - implemented his new vision of PIXI_) with entity-component-system architecture. I belive that the PIXI team should take inspiration of [Fae](https://github.com/Fae/fae) if not make it PIXI.next :shipit:

**Comment by bigtimebuddy** [comment]
@jeebus3000 Yes, that will undoubtedly be our approach.

**Comment by englercj** [comment]
@jeebus3000 I stopped working on Fae to try and reorganize pixi into a similar architecture. It will likely not be *purely* ECS, but it may be something similar.

One important thing is that I abandoned the scene tree in Fae, which is something we don't want to do here. I'll be trying some of these things out in v5.
