### ISSUE TITLE
Problem rendering to renderTexture

### ISSUE THREAD

**Issue by Patrick-Hammond** [pixijs/pixi.js#3713]
Hi,
I have a nested container with some stuff in it. I'd like to render this container to a renderTexture.
My issue is best demonstrated with an example: http://jsfiddle.net/5mydwyxd/27/
For reasons I don't understand, container2 will render correctly, but not the nested container.

**Comment by sergebat** [comment]
Let me chime in and note that the following seem to work ok:

```
    app.renderer.render(container, rt, true);
```

So culprit is probably around your attempt to "negate" transformation, which is probably (?) not what you wanted (see rendering code):

https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/WebGLRenderer.js#L278

**Comment by ivanpopelyshev** [comment]
@Patrick-Hammond @sergebat that's how things are cached in pixi. Yes, its not good. I'm refactoring it at the moment :) I'm working on new iteration of these API's right now. 

If you want some kind of stability, don't use "transform" that is passed to renderer at all.

**Comment by sergebat** [comment]
> Yes, its not good. I'm refactoring it at the moment :)

And may I ask, sir, what will be the new behavior? :) 

Because if you point to arbitrary object in the object tree and ask PIXI to render it in isolation, then what PIXI currently does is quite intuitive, no? "Ignore global transformation of this object, and just render it ignoring its parent transformation, then restore things as they were before".

**Comment by ivanpopelyshev** [comment]
Right now PIXI depends on side effect of "getLocalBounds()" that changes transforms in subtree. 

Just don't copy behaviour in your code, and use "cacheAsBitmap" and "generateTexture()" directly.

**Comment by englercj** [comment]
Closing this since it seems answered.
