### ISSUE TITLE
Smart bound - double-bind texture

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#3720]
According to https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/WebGLRenderer.js#L500 , plugins can easily bind same texture two times, which will break the SpriteRenderer on next call.

What can we do about that? Protect SpriteRenderer, unbind double-bounded before run?

It can't be broken in vanilla, but if I'm mistaken, then its one more source for problems on iPAD's.

**Comment by GoodBoyDigital** [comment]
should not be an issue in v5 👍

**Comment by ivanpopelyshev** [comment]
Because we fixed it in v4

**Comment by ivanpopelyshev** [comment]
It was actually a big critical bug.
