### ISSUE TITLE
Feature request: A Graphics.drawLine(anchorPoints : PIXI.Point[]) method

### ISSUE THREAD

**Issue by KosGrillis** [pixijs/pixi.js#3725]
I'm using pixi.js to prototype a product that, sometime in the future, will go into production. One of the features of this product is the ability to produce flowcharts. Currently I'm using the bezierCurveTo() method to connection objects in the flow chart. This works for the prototype, but for production the client would like a much more robust way of connection flow charts.

I humbly request a method to be added to the Graphics class: drawLine(anchorPoints : PIXI.Point[]) which takes an array of anchor points, and draws a line _smoothly_ through these anchor points. 

Here's a visualisation: http://imgur.com/a/TQUS2

You can see here that the array of anchor points would have contained 4 PIXI.Point(x, y) objects and the line  was drawn smoothly between them. Note that the anchors are there for visualization purposes and shouldn't be there in a final version.

I think this would be a really good addition to the Graphics class and could see some good use.

**Comment by gooderist** [comment]
Does anyone still want this implemented? It seems like #1703 would take of this. I also have a lighter solution here ([fiddle](https://jsfiddle.net/a0rbj9Ln/11/)) if anyone is interested.
