### ISSUE TITLE
Staggered positioning when rotating shapes in iOS Safari

### ISSUE THREAD

**Issue by XerxesNoble** [pixijs/pixi.js#3727]
I'm seeing this issue in iOS safari. (The issue doesn't exist with the canvas renderer).

I have some shapes drawn and while I'm rotating them, they begin to stagger around *0º, 90º, 180º, 270º* 

Heres an example snippet you can paste into your examples app to try out. *(Using v4.3.5)*

```javascript
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

var points = [50, 50, 250, 50, 250, 250, 50, 250, 50, 50]

var graphics = new PIXI.Graphics();
graphics.lineStyle(5, 0x202020, 1);
graphics.beginFill(0xFFFFFF);
graphics.drawPolygon(points);
graphics.endFill();

var container = new PIXI.Container();
container.addChild(graphics);
container.position.set(300, 300)
app.stage.addChild(container);

app.ticker.add(function(delta) {
  container.rotation += 0.005
});
```

**Comment by ivanpopelyshev** [comment]
Yes, its a known issue, I'm working on it. Dont close the issue though

**Comment by XerxesNoble** [comment]
Thanks @ivanpopelyshev 

Is there another workaround rather than forcing a canvas renderer?

**Comment by englercj** [comment]
@ivanpopelyshev was this fixed by changing the default precision for vertex shaders to be highp?

**Comment by XerxesNoble** [comment]
@englercj @ivanpopelyshev - I just tested the above code on my iPhone using `v4.4.0` and it seems to work!

I've been holding out on updating PIXI until this fix came in, thanks!

**Comment by englercj** [comment]
Awesome! Closing to close this out then, glad you got it nailed.
