### ISSUE TITLE
Fps drops in android phone using ionic 2 (using the v4.3.5)

### ISSUE THREAD

**Issue by caninojories** [pixijs/pixi.js#3728]
my fps drops when using and android phone when accessing the app by means of localhost. Nonetheless it is stable when i am accessing it in desktop. You can know what would be the reason.

**Comment by Dimous** [comment]
In what browser?

**Comment by ivanpopelyshev** [comment]
How much memory do you use?

**Comment by caninojories** [comment]
chrome... 
40% memory in used

**Comment by ivanpopelyshev** [comment]
So, which is baseline FPS that you want, how did you achieve it?

And whats the problem in your current device, whats FPS on it?

**Comment by Dimous** [comment]
Run this - http://dev.goodboydigital.com/client/goodboy/bunnymark/ and report back the results. Bunnymark is somewhat _synthetic_, but still.

**Comment by Dimous** [comment]
I must note that that bunnymark version uses multi-texture sprite batching (every type of bunny is a separate image).
I assembled standard bunnymark with pixi.dev.js and ran on Samsung Galaxy Note II. This is what I got: 

![based pixi](https://cloud.githubusercontent.com/assets/283939/22886401/602decfc-f249-11e6-9b24-3a792ae16992.png)

**Comment by bigtimebuddy** [comment]
FYI, you can use https://pixijs.github.io/bunny-mark/ as a better test for comparing relative performance of different versions of Pixi.

**Comment by caninojories** [comment]
im using sprite 
with the width and height of the image (7x7)
with a total of 64 sprite

like this one:
  let _column1row1SquareforBigRoad = new PIXI.Sprite(
      PIXI.loader.resources.square.texture
    );
    this._column1row1GraphicsContainerforBigRoad.addChild(_column1row1SquareforBigRoad);

upto 64 column x 6rows.. and my fps drops from (58 - 30) to (19 - 14).

**Comment by ivanpopelyshev** [comment]
You still didnt specify the device. (58-30) means that its very bad situation. There can't be 30fps on nothing

Also for your cause https://github.com/pixijs/pixi-tilemap will work better?

**Comment by caninojories** [comment]
the device is J7 samsung.. pixi-tilemap.. it is still the same.. 
but then i tried it in iphone i got 60fps.. but when i tried it in android phone (j7) my fps drops between 14 and 19

**Comment by macguffin** [comment]
Are you using the native Samsung browser? If you are try it in Chrome and
see if there is a difference.

I have found that the native Samsung browser performs poorly with both
canvas and webgl content in many of my games, but will performce
excellently on the same device in Chrome.

If you find this is the case you might want to detect the use of a Samsung
browser and suggest your users try the content in Chrome.

**Comment by caninojories** [comment]
still the same..  im using the chrome browser... im going to upload the source code in my github account so that you can check it..

**Comment by englercj** [comment]
Going to close this since it has been inactive for a while. If you want to continue the discussion, feel free to reopen.
