### ISSUE TITLE
performance v4 vs v3

### ISSUE THREAD

**Issue by Edisoni** [pixijs/pixi.js#3738]
Why?
v4
![2017-02-15 22 58 36](https://cloud.githubusercontent.com/assets/10086099/22993039/99639690-f3d2-11e6-9be1-418470a42d00.png)
v3
![2017-02-15 22 59 05](https://cloud.githubusercontent.com/assets/10086099/22993040/99878302-f3d2-11e6-91eb-f4e7a921fbc1.png)

**Comment by ivanpopelyshev** [comment]
multitexture vs single texture. These are different tests 

@bigtimebuddy what about adding "single texture" option in bunnymark so we can compare it to v3?

**Comment by Edisoni** [comment]
One texture
Pixi v4.3.5 
![2017-02-16 12 47 40](https://cloud.githubusercontent.com/assets/10086099/23016040/2d9cc48a-f446-11e6-9b39-8a6e69a78715.png)

**Comment by ivanpopelyshev** [comment]
Now that's a problem. Its either new renderer either static transforms.

**Comment by ivanpopelyshev** [comment]
Either those bunnies at the bottom actually are included in the batch!

**Comment by GoodBoyDigital** [comment]
Howdy, the v3 above version is particle container I believe

**Comment by Edisoni** [comment]
Yes exactly
![2017-02-16 14 04 29](https://cloud.githubusercontent.com/assets/10086099/23018940/1d3b3dbe-f451-11e6-97f7-1f9ba413a07a.png)
