### ISSUE TITLE
"Rats! WebGL hit a snag" on Samsung Galaxy S4 (GT-I9505) while using masks.

### ISSUE THREAD

**Issue by valtver** [pixijs/pixi.js#3745]
Hi guys,

  We faced a trouble on Galaxy S4 Chrome a time ago, while game goes with WebGLRenderer. 
WebGL hit a snag every time we use **masks** in amount of 3 or more. Device's Chrome logs an error: 
> GL_INVALID_OPERATION : glGenSyncTokenCHROMIUM: fence sync must be flushed before generating sync token
> WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost.

We use masks mostly for spine-animations.
After a little investigation it became clear about kind of "special" S4 GPU limitations.

Accidentally the same problem was reproduced later on this device using **RenderTexture**.
The problem looks like this:
> renderer.render(someContainer, renderTexture); 

Calling this method on S4 more than 2 times per frame (between stage rendering) gives a 100% error on this device.
 Current workaround we got is skipping those calls per frame, so if we got 5 containers to be rendered, we spread those rendering in 5 separate frames to keep WebGL alive on that device, but frame skip is more noticeable as soon as we crop more than 5 animations at once.
Can somebody advice about it precisely except **forcing Canvas**? Is it an issue or there are any correct Workarounds / PIXI.settings / ... ?
Thank you!

**Comment by Dimous** [comment]
Disable gpu sandbox.
https://bugs.chromium.org/p/chromium/issues/detail?id=615651

**Comment by valtver** [comment]
![image](https://cloud.githubusercontent.com/assets/6719094/23079487/c12c9ba2-f555-11e6-87a2-f3bcfd430668.png)
Thank you, got it.

**Comment by kaansoral** [comment]
One of the players of my game gets these `context lost` webgl errors frequently too, using a GTX1080-ish graphics card on Windows, could be related

I wonder if there is a PIXI-side cause too

**Comment by englercj** [comment]
If WebGL is crashing it is *usually* not a pixi issue; it is usually a browser/driver/hardware issue.

Closing this since it has been inactive for some time.
