### ISSUE TITLE
[BUG] about `utils.getResolutionOfUrl`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3755]
If there are multi `@` in url ,  the result will be wrong.

**Comment by bigtimebuddy** [comment]
Could you provide an example URL?

**Comment by finscn** [comment]
@bigtimebuddy  , I've opened a PR for fix this issue.

The example:

file://app/www/image@asset/foo@2x.png

I know the `@` in a path is unusual ，but it's reasonable.

**Comment by ivanpopelyshev** [comment]
Fixes #3734

**Comment by finscn** [comment]
@ivanpopelyshev ,  I think #3734 is not about this issue.

**Comment by ivanpopelyshev** [comment]
Oops wrong issue :)
