### ISSUE TITLE
CocoonJS canvas+ and threejs with pixi. pixi stops rendering after threejs starts rendering. Still having input from pixi controls.

### ISSUE THREAD

**Issue by khalimwu** [pixijs/pixi.js#3761]
Been trying to deploy for cocoonJS using threejs and pixi. Made a simple example to show the problem.

https://codepen.io/anon/pen/egawoq

Using a fresh pixi.js - v4.3.5 and threejs r71 will allow you to run it with the cocoonjs dev app.

The problem is that as soon as i have a mesh on scene, it seems like the threeJS renderer cleans up the rendered screen from pixi and the pixi renderer stops rendering anything at all (it also shows some weird behavior if you comment the root.addChild( sprite ); line. Im still receiving the input events from my controls but no rendered image. pixi is using canvasRenderer so its not because they are using the same renderer type.

- [x] CocoonJS
- [x] Android

Edit: updated the codepen to show how the rendering on pixi gets inverted after the threejs render is done with its work (and removed from the domelement)

**Comment by staff0rd** [comment]
Hi @khalimwu, does the codepen you've supplied display the issue on all platforms, or just on Android w/ Cocoon?

**Comment by khalimwu** [comment]
It happens on iOS with cocoonjs too, different behavior (still, pixi doesnt renders when threejs is rendering, but when threejs is stopped rendering, image appears rotated). it doesnt happens on iOS/Android browser or pc.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
