### ISSUE TITLE
Problem with Texture / spritesheet 

### ISSUE THREAD

**Issue by Dosseum** [pixijs/pixi.js#3762]
Hi !
Since few weeks i'm working on a game which was initially in ActionScript (Flash), in HTML5
Everything is nice, i almost finish everything, but now i have a problem.
I have a system of various skin for a character, every skins work except one.
I have this error `Texture Error: frame does not fit inside the base Texture dimensions`

I've check everything in the JSON and it doesn't get out of the bounds.
(I use Adobe Flash to make the spritesheet and i never had a problem before with it)

And the weird things is that it works on Firefox, Edge, Opera but doesn't work on Chrome (the error)

Chrome take me to this 
```
    set frame(frame) // eslint-disable-line require-jsdoc
    {
        this._frame = frame; // HERE
```

Here's the json:

```
{"frames": {

"body2":
{
	"frame": {"x":65,"y":97,"w":45,"h":43},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":45,"h":43},
	"sourceSize": {"w":45,"h":43}
},
"body1":
{
	"frame": {"x":193,"y":50,"w":67,"h":55},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":3,"y":1,"w":67,"h":55},
	"sourceSize": {"w":67,"h":55}
}},
"meta": {
	"app": "Adobe Flash Professional",
	"version": "13.1.0.226",
	"image": "body.png",
	"format": "RGBA8888",
	"size": {"w":256,"h":256},
	"scale": "1"
}
}
```

Thank you !

**Comment by themoonrat** [comment]
Well, in body1, it has frame x as 193, and w as 67. That adds up to 260, which is bigger than the 256 width of the image.

**Comment by Dosseum** [comment]
Thanks for the reply !
Well i add more "border" to the clip on Flash and spritesheet it
`{"frames": {

"test1":
{
	"frame": {"x":0,"y":567,"w":45,"h":43},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":45,"h":43},
	"sourceSize": {"w":45,"h":43}
},
"test2":
{
	"frame": {"x":0,"y":0,"w":67,"h":55},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":67,"h":55},
	"sourceSize": {"w":67,"h":55}
}},
"meta": {
	"app": "Adobe Flash Professional",
	"version": "13.1.0.226",
	"image": "test.png",
	"format": "RGBA8888",
	"size": {"w":512,"h":645},
	"scale": "1"
}`

Now 567+43 = 610 and 610 < 645 so that's ok
0+45 = 45 < 512 so that's ok
67 < 512 and 55 < 645

But it keeps bugging and why does it work well on Firefox ? That's really weird :/ But thank you for the reply

**Comment by Dosseum** [comment]
I think i find a clue of the problem
The real name i use is "corps_1.json" but when i rename the file to test.json everything is ok

**Comment by englercj** [comment]
You may have had some caching going on in other browsers that hid the issue away. Going to close this now since it seems answered.
