### ISSUE TITLE
[poll] Should we drop Bower Support?

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#3770]
Some of the PixiJS team were having a [conversation](https://twitter.com/rolnaaba/status/793507889486770177) about dropping support for Bower. We feel strongly that supporting this dependency manager hurts us more than it helps. Looking for some feedback from the community before we make a change like this.

## Approach
Propose that we maintain the current **release** branch as is, but future releases will be tagged against the **master** branch instead. This would effectively maintain Bower support for the current release and below to be as non-disruptive as possible. Future versions would be available only as direct downloads, from CDNs and through NPM/Yarn.

### Pros
* Would allow us to completely remove our custom deployment system which uses snapshots on a 'release' branch to keep from uploading build files. Would simplify things.
* NPM/Yarn is more robust/less brittle dependency management system and has more features than Bower.
* It would be easier to see version diffs (with commits) instead of comparing snapshots. This would help make release notes easier and easier to do binary searches.

### Cons
* Bower PixiJS consumers would need to switch to NPM, CDN downloads (e.g., [cdnjs.com](https://cdnjs.com/libraries/pixi.js/)) or some other method in their projects.

**If you are in favor, please give it a** 👍 
**If you are **not** in favor, give it a** 👎 

Or please leave your thoughts.

**Comment by macguffin** [comment]
(y)

**Comment by neutrino84** [comment]
I currently use bower, and there is no reason for my pixi.js code to be coming in through bower. I support dropping bower.

**Comment by staff0rd** [comment]
Thanks for voting everyone, [bower is out](https://github.com/pixijs/pixi.js/issues/3772).
