### ISSUE TITLE
ParticleContainer.js should support tint optionality, as many effects require this

### ISSUE THREAD

**Issue by neutrino84** [pixijs/pixi.js#3777]
Doesn't seem like it would effect performance all that much, unless i'm missing something. The tint is applied in shader correct, and a CPU calculation done in client to invert the hex.

... Specifically, it becomes possible to animate the tint, or re-use the same "glow" texture in many different situations, especially if your animation data is pre-rendered.

**Comment by englercj** [comment]
Although this was posted first, I'm going to close it in favor of tracking this issue in #3899 since I saw it first 😜 

Thansk!

**Comment by englercj** [comment]
One quick question though: Are you asking for a tint that is applied to all sprites in the particle container, or a tint per-sprite in the container?

**Comment by nwlieb** [comment]
@englercj would it be possible to optionally support tinting in the particle container for each Sprite? We are running into a situation where having tinting on a huge number of sprites (with high performance) would be a huge boon. Are there major technical limitations for that?

It seems like a simple enough per pixel operation roughly equivalent to 3 times the opacity transform, but I'm a laymen when it comes to graphics.

**Comment by ivanpopelyshev** [comment]
@nwlieb We might add it as one of "properties" option: https://github.com/pixijs/pixi.js/blob/dev/src/particles/ParticleContainer.js#L144

**Comment by tonyka** [comment]
This is unrelated to #3899 since that one only applies to the entire container.

This, however, is a per-particle tint. Which would be pretty awesome since in most if not all particle effects the ability to change the color is a must.

@englercj can you reopen this?

**Comment by englercj** [comment]
Yes I can, tinting each aprticle could be very useful.
