### ISSUE TITLE
High CPU consumption on relatively small NineSlicePlane number on stage

### ISSUE THREAD

**Issue by Dimous** [pixijs/pixi.js#3779]
Static 15x15-grid of NineSlicePlanes makes my laptops fan go crazy. Be it Firefox or Chrome, CPU load goes over 30%.
I'm using NineSlicePlanes as a base class for skinnable ui-components. Complex components composed of several simple components. 5+ complex components turn my laptop into a heat gun 😞 

https://dimous.github.io/pixi-scale9plane-high-cpu-consumption/

**Comment by Dimous** [comment]
Intel® Core™ i5 3230M Processor @ 2.60 Ghz

**Comment by Dimous** [comment]
Intel® Core™ i5 3230M Processor @ 2.60 GHz

**Comment by andrewstart** [comment]
Well, it looks like there is a decent amount of time spent in the WebGL `MeshRenderer.render()`, although that may not be time spent on the javascript side of things. It might be a little easier to do CPU profiling if you were to use the non-minified release of Pixi.

**Comment by Dimous** [comment]
Changed to a development build.

**Comment by Dimous** [comment]
Removed PIXI.Text objects.

**Comment by andrewstart** [comment]
Hmm, it looks like pretty much the entirety of the mesh rendering time is spent uploading to the GPU, so I don't know how much room for optimization there is. Someone more experienced at that stuff like @ivanpopelyshev might have better thoughts on that.

For your bulk usage, you could see if a sprite based implementation (like this one: [sprite](https://github.com/CloudKidStudio/springroll-utils/blob/master/src/pixi/Slice9Sprite.js), [texture](https://github.com/CloudKidStudio/springroll-utils/blob/master/src/pixi/Slice9Textures.js)) is better for you. That might work particularly well if the text is BitmapText and can be shared in the same texture as the backgrounds - in real use cases, I'm sure that would be rare, but it is a possible optimization.

**Comment by ivanpopelyshev** [comment]
ok, so may be something is wrong with the cache?

**Comment by ivanpopelyshev** [comment]
```
                vertexBuffer: glCore.GLBuffer.createVertexBuffer(gl, mesh.vertices, gl.STREAM_DRAW),
                uvBuffer: glCore.GLBuffer.createVertexBuffer(gl, mesh.uvs, gl.STREAM_DRAW), 
```

may be change it to DYNAMIC_DRAW ?

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital we need you help!
