### ISSUE TITLE
An issue about the size of Texture & Sprite.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3782]
In many texture tools , there is an attribute `offsetX/offsetY` for offsetting the position of the core content of  the texture image.

In PIXI.js , If users want to deal with `offsetX/offsetY` , need to do something like this : 
(related : https://github.com/pixijs/pixi.js/issues/3744 )
```
    var baseTexture = PIXI.BaseTexture.from(img);
    var textureFrame = new PIXI.Rectangle(sx, sy, sw, sh);

    var orig, trim;
    if (offset) {
        orig = new PIXI.Rectangle(sx + offset[0], sy + offset[1], sw - offset[0], sh - offset[1]);
        trim = new PIXI.Rectangle(-offset[0], -offset[1], sw, sh);
    }
    texture = new PIXI.Texture(baseTexture, textureFrame, orig, trim);

```

In this situation , the real size of Texture is not  `texture.orig.width`/`texture.orig.height`.

e.g. in #3744 , the real size (excepted size) is the size of the purple rect.

So , I think we need  methods in Texture.js like this  : 
```
    /**
     * The width of the Texture in pixels.
     *
     * @member {number}
     */
    get width()
    {
        if (this.trim)
        {
            return this.trim.width;
        }

        return this.orig.width;
    }

    /**
     * The height of the Texture in pixels.
     *
     * @member {number}
     */
    get height()
    {
        if (this.trim)
        {
            return this.trim.height;
        }

        return this.orig.height;
    }
```

And in fact , the `trim` could not only trim size, but also could extend the size.
 e.g.
```
 trim = new PIXI.Rectangle(-10, -15,  frameWidth + 20, frameHeight + 30);
```
In the example above , the `orig.size === frame.size` , but the real/expected size of the texture in users's mind  should be  `trim.size`.

The size of Texture is not always === orig.size .

So , I suggest we should re-think about the size of Texture & Sprite.

.

**Comment by finscn** [comment]
BTW , Should I add new attribute for offsetting  ?

**Comment by ivanpopelyshev** [comment]
Can offset be emulated with pivot?

**Comment by finscn** [comment]
I tried , but I found the  `offset` can’t be emulated with `pivot` completely.

Sometimes , It can, sometimes It can’t.
e.g. When I want to create  an animation. 
All frames(this frame is not texture.frame)  of animation should be aligned.
(My english is not good enough to explain, sorry)

**Comment by ivanpopelyshev** [comment]
Oh, right , animation.. that's a problem

**Comment by finscn** [comment]
Oh , ont only animation.
If anchor is not 0,0 , there will be issue https://github.com/pixijs/pixi.js/issues/3744

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
