### ISSUE TITLE
Polygon tests not being run

### ISSUE THREAD

**Issue by kguthrie** [pixijs/pixi.js#3783]
Polygon tests were written in #3184. [Code coverage report](https://s3-eu-west-1.amazonaws.com/pixi.js/dev/coverage/src/core/math/shapes/index.html) makes me think they aren't being run, and they appear to be missing from the [index.js](https://github.com/pixijs/pixi.js/blob/dev/test/core/index.js) file

**Comment by staff0rd** [comment]
Nice spotting!  Raised #3786
