### ISSUE TITLE
PIXI.loader / progress

### ISSUE THREAD

**Issue by markknol** [pixijs/pixi.js#3791]
I have trouble understanding how the resource loading of PIXI works.  I don't understand how `PIXI.loader.add("a.png").add("a.png").load(function() { console.log("loaded"); }` could works for subsequent adding/loading, e.g. how should this even work when two functions adds some resources and call `load` at the same time? Or is `PIXI.loader` creating a new ResourceLoader each time you request it?

Anyway, what I want to do is to load some [Flump libraries](https://github.com/tconkling/flump). In order to do that I've created a ResourceLoader and load a library.json file. After the json is loaded I re-use the loader to load the images defined in this file. The loading part of this works (it loads the json and the images), but now I want to visualize the progress in my preloader.

```haxe
function loadLibrary(libraryPath:String, complete:Library->Void):ResourceLoader
{
	if (!libraryPath.endsWith("/")) libraryPath += "/";
	var jsonPath = libraryPath + "library.json";
	// load the library.json first
	var loader:ResourceLoader = new pixi.loaders.Loader();
	loader.add(jsonPath);
	loader = loader.load(function() 
	{
		var json:Format = Reflect.field(PIXI.loader.resources, jsonPath).data;
		// do stuff with the json.
		for (textureGroup in json.textureGroups)
		{
			for (atlas in textureGroup.atlases)
			{
				loader.add(libraryPath + atlas.file); // add the images defined in the json
			}
		}
		// I don't get whats happening here exactly. I am loading again, but now with the images
		loader.load(function() 
		{
			var libraryPath = libraryPath.substr(0, libraryPath.length - 1); 
			complete(new Library(libraryPath));
		});
	});
	return loader;
}
```

This function returns a ResourceLoader, I would expect to `loader.progress` is good enough to display a preloader, but for some reason (maybe because I recycle the loader) it logs values over 100%. Am I doing it wrong or is this a bug?

```
    0
    100
    106.25
    118.75
    137.5
    143.75
    168.75
    181.25
    187.5
```

* I'm using Haxe and https://github.com/pixijs/pixi-haxe but the question isn't Haxe specific.
* Im also using pixi.js - v4.4.0

**Comment by englercj** [comment]
The `.add()` method enqueues a resource path to be loaded, but doesn't actually load anything. When you call `.load()` the loader kicks off loading the resources you queued up.

You cannot reuse a loader without calling `.reset()` first.

```haxe
function loadLibrary(libraryPath:String, complete:Library->Void):ResourceLoader
{
	if (!libraryPath.endsWith("/")) libraryPath += "/";
	var jsonPath = libraryPath + "library.json";
	// load the library.json first
	var loader:ResourceLoader = new pixi.loaders.Loader();
	loader.add('atlasData', jsonPath);
	loader.load(function() 
	{
		var json:Format = loader.resources.atlasData.data;

               // now that we finished loading, and stored off the resource we wanted, reset the loader
               // so it can be used again.
               loader.reset();

		// do stuff with the json.
		for (textureGroup in json.textureGroups)
		{
			for (atlas in textureGroup.atlases)
			{
				loader.add(libraryPath + atlas.file); // add the images defined in the json
			}
		}

		loader.load(function() 
		{
			var libraryPath = libraryPath.substr(0, libraryPath.length - 1); 
			complete(new Library(libraryPath));
		});
	});
	return loader;
}
```

This is still strangely constructed though, because what you will get after this in a progress listener outside this function is progress going from 0-100, then 0-100 again. You can do this all in a single load if you write a middleware that handles the atlas type you have, something like this:


```js
function myAtlasHandler(libraryPath: String)
{
    return function (resource, next)
        {
        // skip if no data, its not json, it isn't spritesheet data, or the image resource already exists
        if (!resource.data
            || resource.type !== Resource.TYPE.JSON
            || !resource.data.textureGroups
        )
        {
            return next();
        }

        const loadOptions = {
            crossOrigin: resource.crossOrigin,
            loadType: Resource.LOAD_TYPE.IMAGE,
            parentResource: resource,
        };

        for (textureGroup in resource.data.textureGroups)
        {
            for (atlas in textureGroup.atlases)
            {
                this.add(libraryPath + atlas.file, loadOptions); // add the images defined in the json
            }
        }

        return next();
    }
}

function loadLibrary(libraryPath:String, complete:Library->Void):ResourceLoader
{
    if (!libraryPath.endsWith("/")) libraryPath += "/";
    var jsonPath = libraryPath + "library.json";

    var loader:ResourceLoader = new pixi.loaders.Loader();

    loader.use(myAtlasHandler(libraryPath));
    loader.add(jsonPath);
    loader.load(function()
    {
        var libraryPath = libraryPath.substr(0, libraryPath.length - 1); 
        complete(new Library(libraryPath));
    });

    return loader;
}
```

With something like that, there will be only a single load and the loader will automatically (via the myAtlasHandler middleware) detect images and load them as well.

**Comment by markknol** [comment]
Thank you very much for this explanation!
