### ISSUE TITLE
autoDetectRenderer should trigger an error if supplied view was not found

### ISSUE THREAD

**Issue by Sairahcaz** [pixijs/pixi.js#3792]
```javascript
var myView = document.getElementById('fooMap');
console.log(myView); //is null
var stage = new Container(),
renderer = autoDetectRenderer(window.innerWidth, window.innerHeight, {view: myView});
```

Using pixi.js 4.4.0.

I had a small typo failure (Id of my canvas was "barMap").
And wondered that nothing happends even dont get any errors.
It's a small thing but maybe it would be nice if this case triggers an error...

**Comment by nyeecola** [comment]
Based on #3807 comments, I believe this should be closed.
