### ISSUE TITLE
Interaction bug (Mouse Position)

### ISSUE THREAD

**Issue by bQvle** [pixijs/pixi.js#3794]
renderer.plugins.interaction.mouse.global  now only returns:

Point {x: -999999, y: -999999}

same for renderer.plugins.interaction.activeInteractionData['MOUSE'].global

however I get a position in renderer.plugins.interaction.activeInteractionData['1'].global

**Comment by ivanpopelyshev** [comment]
That one , plus "settings.SCALE_MODE" are actually critical. I recommend 4.4.1
