### ISSUE TITLE
[BUG] Can't keep(always clear) the content of WebGL Canvas

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3805]
I've ready set `clearBeforeRender:false` , but the content of WebGL (rendered in previous tick) still be cleared.

How to keep(don't clear) the content of  WebGL Canvas ?

**Comment by ivanpopelyshev** [comment]
How do you call your "render" method?

**Comment by finscn** [comment]
@ivanpopelyshev  , The code : 
```js
var width = 640;
var height = 480;

var bunnies = [];
var rectCount = 0;
var startRectCount = 1000 * 5;
var maxRectCount = 1000 * 200;

var gravity = 0.75;

var renderer;
var container;
var stats, counter;

window.onload = function() {

    renderer = new PIXI.WebGLRenderer({
        width: width,
        height: height,
        backgroundColor: 0xF0F0F0,
        clearBeforeRender: false,
    });
    document.body.appendChild(renderer.view);

    renderer.view.style.transform = "translatez(0)";
    renderer.view.style.position = "absolute";

    if (typeof Stats != "undefined") {
        stats = new Stats();
        stats.domElement.style.position = "absolute";
        stats.domElement.style.top = "0px";
        document.body.appendChild(stats.domElement);

        counter = document.createElement("div");
        counter.className = "counter";
        document.body.appendChild(counter);
    }


    container = new PIXI.Container();

    addMoreRects(startRectCount);

    requestAnimationFrame(update);

}


function update() {
    stats && stats.begin();

    for (var i = 0, len = bunnies.length; i < len; i++) {
        var rect = bunnies[i];
        rect.rotation += rect.speedR;
        var x = rect.position.x += rect.speedX;
        var y = rect.position.y += rect.speedY;
        rect.speedY += gravity;

        if (x > width) {
            rect.speedX *= -1;
            rect.position.x = width;
        } else if (x < 0) {
            rect.speedX *= -1;
            rect.position.x = 0;
        }

        if (y > height) {
            rect.speedY *= -0.85;
            rect.position.y = height;
            rect.spin = (Math.random() - 0.5) * 0.2
            if (Math.random() > 0.5) {
                rect.speedY -= Math.random() * 6;
            }
        } else if (y < 0) {
            rect.speedY = 0;
            rect.position.y = 0;
        }
    }
    renderer.render(container);

    requestAnimationFrame(update);

    stats && stats.end();
}


function createRect() {

    var rect = new PIXI.Graphics();
    rect.beginFill(randomInt(0x666666, 0xEEEEEE));
    rect.drawRect(0, 0, 20, 40);
    rect.endFill();

    rect.rotation = (Math.random() - 0.5);
    rect.speedX = Math.random() * 5;
    rect.speedY = (Math.random() * 6) - 4;
    rect.speedR = ((1 + Math.random() * 10) >> 0) / 50;

    return rect;
}

function addMoreRects(count) {
    var i = 0;
    while (rectCount < maxRectCount && i < count) {
        var rect = createRect();

        bunnies.push(rect);
        container.addChild(rect);

        i++;
        rectCount++;
    }
    if (counter) {
        counter.innerHTML = rectCount + " RECTS";
    }
}


function randomInt(from, to) {
    return Math.floor(Math.random() * (to - from + 1) + from);
}
```

**Comment by finscn** [comment]
There is no any specific thing.  
And When I use `renderer.render(container, null, true)` , the bug is still there.

**Comment by finscn** [comment]
I changed the `WebGLRenderer.prototype.render` to a simple one : 
```js
WebGLRenderer.prototype.render = function(displayObject) {

    this.renderingToScreen = true;

    var cacheParent = displayObject.parent;
    displayObject.parent = this._tempDisplayObjectParent;
    displayObject.updateTransform();
    displayObject.parent = cacheParent;

    displayObject.renderWebGL(this);

    this.currentRenderer.flush();
};
```

The bug is still there.

.

**Comment by ivanpopelyshev** [comment]
"null" wont work, you have to pass "undefined" there.

**Comment by finscn** [comment]
@ivanpopelyshev  Whatever null or undefined , the bug is still.

**Comment by finscn** [comment]
I don't sleep for debug this issue , But I didn't  get any useful information :'(  tears.

I have to go to bed ,  I've worked for 36 hours . 

I hope there will be a good news when I wake up.

**Comment by ivanpopelyshev** [comment]
I bet its browser behaviour.  You have to use separate RenderTexture and not clear it, and just render it (or copy) when you have to render to the stage.

**Comment by finscn** [comment]
@ivanpopelyshev  , if you are right , the `clearBeforeRender` will be a 'wrong / bad' name, 
because whatever true or false ,  it always  does `clear` .


I  couldn’t sleep ,  the insomnia is back.

**Comment by ivanpopelyshev** [comment]
It doesn't . I think there's auto-clear somewhere in the browser when we start using webgl context after a frame.

**Comment by finscn** [comment]
@ivanpopelyshev  ,  You say " just render it (or copy) when you have to render to the stage" ,  How to copy ?  copy is faster than render ?

**Comment by clineil** [comment]
I am experiencing this same bug when rendering to a RenderTexture. 

I am attempting to render multiple times into one texture, directly on top of what was in the texture before.

If I call :

`renderer.render( someDisplayObject, myRenderTexture, false );`

myRenderTexture is cleared anyways.

**Comment by ivanpopelyshev** [comment]
Random thought: what resolution does your device have? What gets passed into "resolution" param of renderer?

**Comment by clineil** [comment]
using a macbook pro with a window size of 1200 x 800

**Comment by ivanpopelyshev** [comment]
OK, and whats pixel density?

**Comment by clineil** [comment]
Retina Display

![image](https://user-images.githubusercontent.com/6218364/34470419-4f6f9be2-eefe-11e7-97ff-67751fd0ed19.png)

**Comment by ivanpopelyshev** [comment]
Do you pass "devicePixelRatio" into "resolution" param of renderer?

**Comment by clineil** [comment]
no, will try now

**Comment by clineil** [comment]
tried, same result. still not clearing

**Comment by ivanpopelyshev** [comment]
I actually thought that bug can be related to retina mode, but now we know that it doesnt, because you didnt active it.

OK, so, esoteric params in webgl renderer:

```js
renderer = new WebGLRenderer(1200, 800, {antialias:false, preserveDrawingBuffer: false ));
```

Those are default params. Try to set antialias to true, and if it doesnt work try to set preserveDrawingBuffer to true.

**Comment by clineil** [comment]
added those parameters as well, and it is still clearing

**Comment by ivanpopelyshev** [comment]
Ok, what about other computers / browsers ?

**Comment by clineil** [comment]
same behavior

**Comment by ivanpopelyshev** [comment]
Then our bug is not related to hardware, its either pixi bug either you did something wrong. Post a fiddle, we'll look at it.

**Comment by clineil** [comment]
Ok, I'll make a fiddle and post here shortly.

**Comment by clineil** [comment]
i can't recreate my issue in the fiddle, in fact, clearBeforeRendering is working as intended : 

https://jsfiddle.net/n9px2341/5/

i'll dig a little deeper into my application and get back to this thread

**Comment by finscn** [comment]
set preserveDrawingBuffer=true
