### ISSUE TITLE
Graphics.generateCanvasTexture() Bug

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#3806]
There's a bug when converting a graphics object to a texture with generateCanvasTexture.
Here's a Pen that demos the bug: [CodePen](http://codepen.io/anon/pen/qrNpyX)

The triangle displayed on the right side shows the Graphics object.
The triangle displayed on the left side shows the generated texture.

The corners of the texture's triangle are cut off, making the corners much less sharp and making the triangle a little smaller.

Setting the line width to 0 fixes the issue in that the corners are no longer cut off, but of course then we loose the outline.

P.S. - We're using the latest release of Pixi (4.4.1). 

And if anyone has a workaround we'd love to try it :)

**Comment by ivanpopelyshev** [comment]
I use plain html5 2d api for those things. Then "Texture.fromCanvas(myGeneratedCanvas)"

**Comment by andrewstart** [comment]
I think that the workaround would be either making a RenderTexture from two layered triangle fills, or using the Canvas2D api directly to generate the canvas. Since the extra space needed for sharp line joins isn't easily predicted, I imagine that a fix for this would just be giving`generateCanvasTexture` a padding parameter for cases like this.

**Comment by jaspervaz** [comment]
Thanks for the quick suggestions guys 👍

We've got it working using the Canvas2D API and PIXI.Texture.fromCanvas and loving the nice crisp graphics.

One maybe-issue we're having thou is that we need to create a new canvas element for each texture, because if we clear the canvas after creating the texture and sprite, the sprite ends up being empty.

Does this sound right?

Thanks again: )

**Comment by ivanpopelyshev** [comment]
You can upload it to GPU and then re-use the canvas:

```
renderer.textureManager.updateTexture(myTexture)
```

It happens when you first time draw sprite, so if you re-used canvas before update, it will upload newer version. Do that manually and it'll work.

**Comment by jaspervaz** [comment]
Thanks Ivan, this led me in the right direction for our use case (which is slightly more complicated than I let on). After some experimentation and RTFM'ing I ended up using texture.baseTexture.update() instead, which seems to more thoroughly update the texture's properties (height, width, and resolution being important in our case).

Thanks again, this solved the issue for us - and quicker than I dared hope :)

**Comment by jaspervaz** [comment]
@ivanpopelyshev

Thanks for the update  about the PIXI Canvas Renderer. My current approach was crashing w/ WebGL disabled (no textureManager). I don't mind requiring WebGL, but am glad to know that I need to check for it :)

**Comment by jaspervaz** [comment]
FYI, after some more tinkering with @ivanpopelyshev's suggestions I found an approach that seems to be working for both WebGL and Canvas-fallback rendering, and allows the off-screen canvas to be cleared and re-used.

`  texture.baseTexture.update();
    sprite.texture = texture;
    renderer.render(stage);
    offScreenContext.clearRect(0, 0, offScreenCanvas.width, offScreenCanvas.height);`


Below incorporates both techniques, using the WebGL version when possible.

`  if (renderer.textureManager) {
        renderer.textureManager.updateTexture(texture.baseTexture);
    }
    else {
        texture.baseTexture.update();
        sprite.texture = texture;
        renderer.render(stage);
    }
    offScreenContext.clearRect(0, 0, offScreenCanvas.width, offScreenCanvas.height);`

**Comment by jaspervaz** [comment]
Sorry my first time using the "Insert Code". It it supposed to condense like that?

**Comment by jaspervaz** [comment]
Hi @ivanpopelyshev. I'm trying to re-use a canvas to create multiple textures, using the method you showed me, but it's not working after all. I made a very simple little CodePen that tries do draw a green square, update the texture, and then draw a red square, but both squares are always the same color. Can you please take a peek if you get a chance? I'm not sure what else to try..

**Comment by ivanpopelyshev** [comment]
Oh my!
"fromCanvas" caches stuff, and it won't update texture that already exists in cache.

```
new PIXI.Texture(new PIXI.BaseTexture(offScreenCanvas));
```

**Comment by jaspervaz** [comment]
Awesome! Thanks @ivanpopelyshev. BTW, when I redraw a texture (on resize), if I call "texture.destroy(true)", set all my sprites' texture property to the new texture and don't keep any extra references to the object in my code, that should take care of freeing up the old texture's resources, right?
