### ISSUE TITLE
Issues with sprite filters in 4.4.1

### ISSUE THREAD

**Issue by 1N50MN14** [pixijs/pixi.js#3808]
`toBGR()` and `technicolor()` are broken. 
The combination of multiple filters doesn't work, for example `brightness()` and `contrast()` with any other filter.
`sepia()` is no longer adjustable.

**Comment by themoonrat** [comment]
@1N50MN14  Would it be possible to put together a fiddle example for us please?

**Comment by englercj** [comment]
Hey @1N50MN14 would you mind adding some running examples? It will help us figure out the issues!

**Comment by 1N50MN14** [comment]
@themoonrat @englercj Apologies didn't notice you had pinged me earlier, yeah absolutely! I'm about to hit the sack will put together a fiddle tomorrow evening, thanks!

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
