### ISSUE TITLE
Changing the Renderer's Resolution

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#3810]
Is there a way to update the renderer's resolution? I tried renderer.resolution = window.devicePixelRatio, but it just makes the screen flash white.

**Comment by jaspervaz** [comment]
The best temporary workaround that I came up with is to destroy and re-create the renderer, passing the new resolution to autoDetectRenderer. This works but maybe isn't the most efficient way to do it. Also, there's maybe still an issue with repeatedly destroying and re-creating the renderer: #2233 

It seems like there should be a simple function call to do this, like renderer.setResolution, that minimizes the amount of extra processing and dead resources.

**Comment by GoodBoyDigital** [comment]
Hi @jaspervaz! Curious about what is your use-case for this is? 
Cheers!

**Comment by ivanpopelyshev** [comment]
Yes, it is.

```
renderer.resolution = 2;
renderer.rootRenderTarget.resolution = 2;
renderer.resize(w-1, h);
renderer.resize(w, h);
```

**Comment by themoonrat** [comment]
And don't forget to update the interaction plugin resolution too

**Comment by jaspervaz** [comment]
Hurrah, that's working @ivanpopelyshev 👍 

Maybe for now the documentation for the resolution property could be marked "read only" with a link to this issue and your fix?

**Comment by jaspervaz** [comment]
Hi @GoodBoyDigital

The use case is to adapt to zoom changes. If the resolution is set only once when the renderer is created, then the user must reload the page for the renderer to become updated with the new resolution. If the browsers didn't contaminate window.devicePixelRatio with the software's zooming factor then... Sorry I guess that's a whole other topic and the browsers are how are they are ;)

PS - love the engine and how active the community is :)

**Comment by ivanpopelyshev** [comment]
@jaspervaz 

EXACTLY, Zoom changes, that's what i want to do too :)

**Comment by jaspervaz** [comment]
Here's a quick update to @ivanpopelyshev's solution that allows it to work with the Canvas-fallback rendering. Note if you omit setting the rootRenderTarget for WebGL-rendering then the screen will flash white (or maybe some other unstable behavior in different cases), but if you try to set it with Canvas-fallback rendering, the browser chokes on its non-existence. Adding this checks allows the resolution to be updated in either case. Cheers!

`if (renderer.rootRenderTarget) {
      renderer.rootRenderTarget.resolution = pixelRatio;
  }`

**Comment by jaspervaz** [comment]
Beware doing this for iOS Safari: window.devicePixelRatio seems to change at unexpected times. Since meta viewport tag disables zooming on mobile devices, I ended up using PIXI.utils.isMobile.any to check for them. That way I only adjust the resolution when desktop users zoom in/out. That's the idea any way => so far it's testing well 👍

**Comment by ivanpopelyshev** [comment]
Yeah, I agree.

**Comment by starInEcust** [comment]
@ivanpopelyshev I want to scale the screen. 
Using your method will make the canvas blurred.
Using my method resolution can not be greater than 20

https://jsfiddle.net/starCoding/p49u34hd/8/

**Comment by ivanpopelyshev** [comment]
@starInEcust Why do you need resolution more than 20? Resolution is not about scaling, its browser zoom.

**Comment by starInEcust** [comment]
@ivanpopelyshev I want to enlarge the the renderer and keep the text and svg pictures won't be distorted

**Comment by ivanpopelyshev** [comment]
@starInEcust I solved that kind of issues by manual adjusting of scale and font size. Use SDF fonts?  https://github.com/PixelsCommander/pixi-sdf-text

**Comment by starInEcust** [comment]
@ivanpopelyshev how about svg? I just want to make a text editor with cool animation, in the print preview can zoom in and out, but does not affect the typesetting.
And is there any problem with the use of resolution magnification?

**Comment by ivanpopelyshev** [comment]
That's very unusual use-case for pixi. You have to adjust resolution of SVG and text, not the resolution of whole renderer. And I didnt use SVG in pixi so I dont know how to adjust resolution for it :)

**Comment by starInEcust** [comment]
Thank you very much！Maybe I should open an issue to discuss this question :(

**Comment by englercj** [comment]
Going to close this issue since it seems answered, feel free to open another if you have another question!
