### ISSUE TITLE
 SVG No Texture Dimensions Until Next RAF

### ISSUE THREAD

**Issue by megmut** [pixijs/pixi.js#3813]
Hey guys.. I'm hoping this is something I'm doing wrong, but basically.. when I'm creating a new SVG, it's having width, and height of 1 until 1 frame has passed and then it has actual dimensions. 

My guess is that the onTextureChange event is being triggered, however the new local transformation isn't happening until the next loop takes place. Here is an example of my code:

    var texture = PIXI.Texture.fromImage('mySVGPath.svg');
    var sprite = new PIXI.Sprite(texture);
    console.log(sprite.width, sprite.height) // 1, 1

    setTimeout(() => {
        console.log(sprite.width, sprite.height) // 500, 465
    }, 0);

https://jsfiddle.net/gmg4uyxx/

Thanks!!

**Comment by themoonrat** [comment]
In comments at the top of the texture class

>  * Textures made from SVGs, loaded or not, cannot be used before the file finishes processing.
>  * You can check for this by checking the sprite's _textureID property.
>  * ```js
>  * var texture = PIXI.Texture.fromImage('assets/image.svg');
>  * var sprite1 = new PIXI.Sprite(texture);
>  * //sprite1._textureID should not be undefined if the texture has finished processing the SVG file

This a case of you trying to measure the sprites width "before the file finishes processing".
