### ISSUE TITLE
Using mask flashing

### ISSUE THREAD

**Issue by fang5502** [pixijs/pixi.js#3814]
Hi, I have tried to change pixi's example code. 
I use drawRect() as the mask run in Samsung Galaxy S3 but it has the flash problem and crash.
This is the code where I changed.
```
var thing = new PIXI.Graphics();
//app.stage.addChild(thing);
// thing.x = container.width / 2;
// thing.y = container.height / 2;
container.addChild(thing);
thing.beginFill(0x000000);
thing.drawRect(0, 0, 70, 70);
container.mask = thing;
```

pixi: v4.4.1
Chrome: v56.0.2924.87
device: Samsung Galaxy S3 (GT-I9300)
Android: 4.1.2
And this is the video: [https://youtu.be/7nwCXntWtSg](https://youtu.be/7nwCXntWtSg)

Thanks a lot!

**Comment by fang5502** [comment]
Excuse me, 
請問這個問題有辦法解決嗎

**Comment by fang5502** [comment]
Excuse me, Is this problem has the solution to solve?

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by fang5502** [comment]
Here is the code: [https://jsfiddle.net/811egucy/](https://jsfiddle.net/811egucy/)
Thanks

**Comment by englercj** [comment]
I am unable to reproduce this on my desktop, is this still an issue in v4.5.0 by chance?

**Comment by GoodBoyDigital** [comment]
Hello! Try forcing transparency to be true on the renderer. I'm not sure why - but it often fixes flickering devices! 👍

**Comment by ivanpopelyshev** [comment]
Its true by default, try force `false` there or `"notMultiplied"`
