### ISSUE TITLE
Question About Smart Batching and Containers

### ISSUE THREAD

**Issue by jaspervaz** [pixijs/pixi.js#3815]
Hi, just a quick question about smart batching. Say I'm displaying many sprites, each with the same texture, but with different position, rotation, and tint properties. If I add all of these sprites to their own container will that help with the smart batching, since they're all drawn consecutively? Or is there a more optimal best practice for this scenario?

BTW, is it okay netiquette to ask these non-bug-related questions here?

**Comment by ivanpopelyshev** [comment]
That depends on how many do you have. If they are like 100-1000 , then you can put them in different containers, batching does not care about container tree, it just works for elements that are drawn consecutively. Things that break batching: different blendMode, different textures (more than 8), masks and filters.

If you have more than 1000 sprites, its better to put them in single "PIXI.particles.ParticleContainer".

If your stage is difficult, and you have some kind of Z-index, please use this thing: http://pixijs.github.io/examples/#/layers/lighting.js

**Comment by jaspervaz** [comment]
@ivanpopelyshev

But the Container.renderWebGL function renders the container's children consecutively, so putting all sprites that use the same texture in in their own container should force them to be drawn consecutively, right? It seems like it would work as well as z-index sorting, in terms of making sure the sprites are drawn consecutively, unless I'm misunderstanding?

In my case, I'll only have several hundred sprites per texture. And I'll need to be able to adjust the tint on a per-sprite basis, too, so it looks like the ParticleContainer is a no go this time.

8 textures without breaking the batch: that's interesting, so if my app only uses 8 textures or less in total, then I don't have to worry about the draw order at all, in terms of batch-breaking?

**Comment by ivanpopelyshev** [comment]
Layers are working fine, they are branch of "pixi-display", but no one used it to help batching yet, I dont know if it makes sence for your game. Use-cases for it are "render all text above stage" or "render some lights inside filtered container".

"And limiting each container's children to use 8 or less textures int total would help too, since the container's elements are rendered consecutively"

"Consecutively" render all elements if they are rendered in the tree-walking order. If two elements are in different containers, they can be batched anyway.

**Comment by macguffin** [comment]
Hi, can I just clarify as I'm always looking for tips to improve performance?
When you say 8 textures you mean a single 'sprite' from the sprite sheet?
So if my sprite sheet has images a,b,c,d,e,f,g,h,i,j,k - a container might benifit if it only had images a-h?

But I can have 10 image a's etc without reducing performance?

**Comment by ivanpopelyshev** [comment]
I mean base textures aka spritesheets. Actually up to 16 on most of PC's.

**Comment by themoonrat** [comment]
When referring to textures and batching, we're always referring to the equivalent of a PIXI.BaseTexture. You could create 999999 PIXI.Textures from that PIXI.BaseTexture, but they'd all get batched nicely. It's when the renderer has to swap from rendering from one BaseTexture to another that there will be the tiny performance penalty. Well, in PIXIs case, from one of 16 BaseTextures to another BaseTexture that isn't one of those 16 (that number changes based on hardware for what is possible - it's higher on desktops than on mobiles. Legacy mode reduces this number to 1, for example)

**Comment by macguffin** [comment]
Ok, thanks for the info interesting stuff.

**Comment by jaspervaz** [comment]
Thanks for clarifying, I was immensely confused and over-complicating things I guess.

So the order that sprites are added to the stage for instance doesn't affect batching at all then?
