### ISSUE TITLE
version > 4.3.5, onDragEnd called on the next click, wherever where.

### ISSUE THREAD

**Issue by francisvidal** [pixijs/pixi.js#3816]
Try the demo: https://pixijs.github.io/examples/?v=v4.3.5#/demos/dragging.js
Add a console.log('OnDragEnd'); in the onDragEnd() function.
Drag a bear, release it.  --> OnDragEnd in console.
Click anywhere (but on a bear) --> OnDragEnd in console.
OnDragEnd should be called only once.

This cause me a lot of headaches, please fix.

**Comment by andrewstart** [comment]
Is this fixed by the branch in https://github.com/pixijs/pixi.js/pull/3800?

**Comment by ivanpopelyshev** [comment]
@andrewstart Can you post a build to test?

**Comment by ivanpopelyshev** [comment]
OK, I'll test it

**Comment by arsnl** [comment]
How dare you?! These are bunnies! Ugly bunnies. But not bears!

**Comment by themoonrat** [comment]
Any update @francisvidal - could you test your scenario using the latest release & dev versions please?

**Comment by francisvidal** [comment]
Fix in 4.4.4, thanks.
