### ISSUE TITLE
Tinting on Canvas Renderer

### ISSUE THREAD

**Issue by rsdelta** [pixijs/pixi.js#3817]
Rendering sprite with tint produces white artifacts on the edges. It happens when you use png image with transparent pixels. Reproduces on any browser (Except IE11), only on Canvas.

PIXI Version: Any version (tested on 3.0.11, 4.0.1, 4.2.1, 4.4.1)
Browsers:  Edge, Mozilla Firefox, Google Chrome

Example below:
https://jsfiddle.net/yjcqz3o8/

**Comment by rsdelta** [comment]
Found a solution. Setting 'tintWithPerPixel' as tint method fixed the issue.

https://jsfiddle.net/yjcqz3o8/1/

**Comment by jaspervaz** [comment]
@rsdelta: Thank you so much for finding and posing the solution!  I was just wresting/despairing with the same issue :)
