### ISSUE TITLE
Build error: header and sourcemaps are not compatible

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#3821]
Subject. Our header is 7 lines, and offset in debugging is 7 lines too.

**Comment by bigtimebuddy** [comment]
This issue should probably be filed on https://github.com/pixijs/pixify instead.

**Comment by bigtimebuddy** [comment]
Is this in minified or unminified mode?

**Comment by ivanpopelyshev** [comment]
unminified.

**Comment by GoodBoyDigital** [comment]
@bigtimebuddy is this one good to close?

**Comment by ivanpopelyshev** [comment]
No its not, its still a case and I'm very frustrated about it.
