### ISSUE TITLE
version > 4.3.5 FXAAFilter not working

### ISSUE THREAD

**Issue by DerivcoHK** [pixijs/pixi.js#3822]
From 4.4.0,
`stage.filters[new PIXI.filters.FXAAFilters()]`
not working anymore
Seem like the FilterManager change cause the filterArea broken
![fxaafilter](https://cloud.githubusercontent.com/assets/16910927/23789318/58dff0d8-05b5-11e7-9a35-3f8febd45cea.png)

**Comment by ivanpopelyshev** [comment]
What if you try this one

```
PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH;
```

**Comment by DerivcoHK** [comment]
With PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH;
no error throw now
Thanks a lot~

**Comment by ivanpopelyshev** [comment]
Anyway that's a bug, we have to fix it. I just gave you workaround

**Comment by GoodBoyDigital** [comment]
closing as fixed and tested in v5
