### ISSUE TITLE
PIXI.Text.buttonMode doesn't work when parent is masked

### ISSUE THREAD

**Issue by Knight52** [pixijs/pixi.js#3823]
I have some texts being a stage's children. I added mask to the stage using browser's console, and suddenly it doesn't register any input, whether the text is inside or outside the mask.

Here are relevant code. This is in typescript function, but the code in output .js isn't different: 

    createText(text: string, y: number, fontSize: number = 32, fontFamily: string = "Arial")
    {
        var style = new PIXI.TextStyle({
            fontFamily: fontFamily,
            fontSize: fontSize,
            fontWeight: 'bold',
            fill: ['#ffffff'],
            dropShadow: true,
            dropShadowColor: '#000000',
            dropShadowBlur: 4,
            dropShadowAngle: Math.PI / 6,
            dropShadowDistance: 6,
            wordWrap: true,
            wordWrapWidth: 800,
            padding: 10
        });
        var basicText = new PIXI.Text(text, style);
        basicText.x = 10;
        basicText.y = y;

        this.game.stage.addChild(basicText);
        return basicText;
    }
    createButton(text: string, y:number, onMouseDown: Function)
    {
        var button = this.createText(text, y, 20);

        button.buttonMode = true;
        button.interactive = true;
        button.on("pointerdown", onMouseDown);
        return button;
    }
    this.createButton("SYNC", 170, this.onSync);`

And on the Firefox's console. I put in:
`var graphic = new PIXI.Graphics();
graphic.drawRect(0, 0, 400, 300);
greeter.game.stage.mask = graphic;`

`

**Comment by staff0rd** [comment]
Hi @Knight52, please see [this pen](http://codepen.io/staff0rd/pen/qrpxyy?editors=0010) where a mask added to the parent does not stop interaction on the child.  If you can edit this pen to reproduce your issue, I'll re-open this.
