### ISSUE TITLE
Alpha masks disable additive blending mode

### ISSUE THREAD

**Issue by Spigo-Kevin** [pixijs/pixi.js#3824]
It appears that applying an alpha mask to a Pixi object will disable the additive blending mode.

```javascript
var imageEntity = new PIXI.Sprite(this.imageTexture);
imageEntity.blendMode = PIXI.BLEND_MODES.ADD;

var mask = new PIXI.Sprite(this.maskTexture);
imageEntity.addChild(mask);
imageEntity.mask = mask;

stage.addChild(imageEntity);
```

I seem to remember this having been reported in the past but was unable to find it.

We are using Pixi V.4.0.0.

**Comment by ivanpopelyshev** [comment]
Yes, it is a bug, however if you imagine how it works internally - its actually not. We'll fix that.

Right now iot works only for CanvasRenderer

For webgl renderer there's a workaround:

```
var addFilter= new PIXI.filters.VoidFilter();
addFilter.blendMode = PIXI.BLEND_MODES_ADD;
imageEntity.filters = [addFilter];
```

Its not the best thing, it uses one more framebuffer. 

@GoodBoyDigital @mattcarl I propose we add special field "maskBlendMode"

**Comment by Patrick-Hammond** [comment]
I noticed there is no blendMode assignment in the MaskManager.pushSpriteMask method. But I suspect there is more to it than I understand. Something like:

```
            alphaMaskFilter[0].blendMode = target.blendMode;
```

**Comment by ivanpopelyshev** [comment]
It will work if you actually use alphaMaskFilter instead of mask.

**Comment by chesovnik** [comment]
I have maybe the same problem. If I create mask from Graphics and apply it to Graphics it works fine. If I apply blend mode to these Graphics everything is okey too. But if I apply blend mode and then make mask — blend mode don't work.

`let overlay = new Graphics();
        overlay.lineStyle(5,0xFF3300,1);
        overlay.beginFill(0x66CCFF);
        overlay.drawRect(window.innerWidth / 2, 0, window.innerWidth / 2, window.innerHeight);
        overlay.endFill();`

`let rectangle = new Graphics();
        rectangle.lineStyle(5,0xFF3300,1);
        rectangle.drawRect(window.innerWidth / 3, window.innerHeight / 3, 500, 500);`

`overlay.blendMode = PIXI.BLEND_MODES.MULTIPLY;
overlay.mask = rectangle;
app.stage.addChild(overlay);
app.stage.addChild(rectangle);`

**Comment by ivanpopelyshev** [comment]
I gave the solution: 

> It will work if you actually use alphaMaskFilter instead of mask field.

**Comment by chesovnik** [comment]
Thanks! But what is the syntax and API of alphaMaskFilter? I didn't find it in PIXI API documentation

**Comment by ivanpopelyshev** [comment]
You are already at the point where docs are useless, you have to clone the repo. 

https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js

Assume we have `alphaSprite` and `mySprite`

```js
var spriteMaskFilter = new PIXI.filters.SpriteMaskFilter();
spriteMaskFilter.glShaderKey = 'uniqueMaskKey'; // ask filterManager to cache filter shader, handy if you use many of them

spriteMaskFilter.sprite = alphaSprite;
alphaSprite.renderable = false;

mySprite.filters = [spriteMaskFilter];
```
