### ISSUE TITLE
Updated Examples Misuse Delta

### ISSUE THREAD

**Issue by jaspervaz** [pixijs/pixi.js#3826]
Hi again! I just noticed that the official Pixi [examples](https://pixijs.github.io/examples/#/basics/basic.js) have been changed so that the animation velocity is now multiplied by delta. The examples used to divide by delta instead. As of version  4.4.1, though, the velocity still needs to be divided by delta, not multiplied. I'm hoping that the changed examples means that the next version of Pixi will invert delta so that we can multiply, since most engines and tutorials do it that way:) In the meantime, thou, the examples are misleading/confusing..

**Comment by bigtimebuddy** [comment]
cc @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
According to ticker sources, it needs to be multiplied

```
this.deltaTime = elapsedMS * settings.TARGET_FPMS * this.speed;
```

deltaTime is in linear dependency of elapsedMS

**Comment by jaspervaz** [comment]
Hi @ivanpopelyshev. I think we're talking about different things. Delta, not deltaTime. It's equal to 60/fps. Since higher frame rates make delta smaller and lower frame rates make delta larger, the velocity should be divided by delta, as the examples showed previously.

Typically people will expect delta to be fps/60, thou, in which case velocity would be multiplied by delta, as it is in the recently updated examples.

P.S. - For clarity, by delta I'm referring to the parameter name that the examples use, not a property:
`app.ticker.add(function(delta) {
    // just for fun, let's rotate mr rabbit a little
    // delta is 1 if running at 100% performance
    // creates frame-independent tranformation
    bunny.rotation += 0.1 * delta;
});`

**Comment by ivanpopelyshev** [comment]
I'm feeling stupid here. @bigtimebuddy plase help

**Comment by jaspervaz** [comment]
@bigtimebuddy, @ivanpopelyshev: no I was one being stupid - needed a break from staring at code all day - I updated my last comment and closed this one - no issue after all :)
