### ISSUE TITLE
originalEvent.changedTouches is undefined in andriod chrome after v4.4+ 

### ISSUE THREAD

**Issue by humanhighway** [pixijs/pixi.js#3828]
check [https://output.jsbin.com/qabutamifo](https://output.jsbin.com/qabutamifo) in chrome develop tool simulator or andriod chorme.
v4.3.5 works normally.

**Comment by andrewstart** [comment]
Pixi now listens to PointerEvents where available, so you would only see the `changedTouches` property of a TouchEvent where PointerEvents are not supported. You should get an event for each touch that occurs.
