### ISSUE TITLE
Textures updating from a canvas fade out when scaled down

### ISSUE THREAD

**Issue by palmerama** [pixijs/pixi.js#3832]
This is a weird one. I need an animating canvas to draw arcs, circles, etc, so I'm using PIXI.Texture.fromCanvas() like this:

```
var canvasTexture = PIXI.Texture.fromCanvas(canvas);
var sprite = new PIXI.Sprite(canvasTexture);
```

I then update the texture as I move stuff about on the canvas like this:

```
canvasTexture.update();
```

This works, but that sprite now fades as the scale goes down, as far as scale .5, when it disappears. This also happens when it's inside a scaled container.

Any ideas?

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by palmerama** [comment]
Here you go: https://jsfiddle.net/a94ze5tq/12/
Just change the _scale_ variable to see the issue. It's invisible at .5, then fully visible at 1.

**Comment by themoonrat** [comment]
By turning off mipmaps on the canvas texture it fixed the problem
https://jsfiddle.net/a94ze5tq/16/

**Comment by ivanpopelyshev** [comment]
OK, now I think that was kind of obvious. We really should disable mipmaps for canvas source by default.

**Comment by themoonrat** [comment]
Any thoughts @GoodBoyDigital @bigtimebuddy on @ivanpopelyshev's suggestion?

**Comment by englercj** [comment]
@ivanpopelyshev I'm stupid, can you explain to me why canvas sources would do this when mipmaps are enabled? Not sure I fully understand the underlying problem, so I'm sure about turning on a new default behavior.

**Comment by themoonrat** [comment]
@bigtimebuddy bump? Should we disable mimaps for canvas source by default for v5?
