### ISSUE TITLE
[Suggestion] About the attribute name in XxxxxRenderer

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3838]
In WebGLRenderer , the context of canvas named `gl`, 
In CanvasRenderer , the context of canvas named `rootContext` , I hope they could with the same name.

Maybe could add `this.rootContext = this.gl;` in WebGLRenderer.

Or both use `viewContext` , because the canvas named `view` in Renderer.

**Comment by ivanpopelyshev** [comment]
They have completely different interface that has to be hidden from the user eyes. "rootContext" named that way because CanvasRenderer uses multiple contexts, while WebGLRenderer only one.

**Comment by finscn** [comment]
I know they have completely different interface.  But in some case , I need get the context. 
Now I have to do this 
```
var context  = renderer.webgl ? renderer.gl : renderer.rootContext;
```
I think it's not good enough.

**Comment by ivanpopelyshev** [comment]
And in html5 you have to call

```
view.getContext(renderer.webgl ? "2d" : "webgl") 
```

It's same problem. Those things don't have common methods at all.

**Comment by finscn** [comment]
I know "2d context & webgl context don't have common methods at all".
But The key point is "I want get the context of canvas", not "use the context".
"Using the context"  is an other module's job, I don't care about it.
 
I want add the code in WebGLRenderer 
```
        this.gl = this.options.context || glCore.createContext(this.view, this._contextOptions);

        /* the unified alias of canvas context */
        this.viewContext = this.gl;
```

And in CanvasRenderer 

```
        this.rootContext = this.view.getContext('2d', { alpha: this.transparent });

        /* the unified alias of canvas context */
        this.viewContext = this.gl;
```

**Comment by ivanpopelyshev** [comment]
Don't forget about docs on this thing and "destroy()". I seriously doubt there are common use-cases for that.

**Comment by finscn** [comment]
Yes , there is no common use-case.
In fact ,  most of my requests are not for common use-cases . Sometime , they are for do extensions of PIXI.

**Comment by GoodBoyDigital** [comment]
Sounds to me like this one is easily fixable in user land! No need to add this to PIXI :)
