### ISSUE TITLE
ParticleContainer corrupts Graphics rendering

### ISSUE THREAD

**Issue by slinkydinks** [pixijs/pixi.js#3846]
Hi

I've run into an issue where the creation and use of a ParticleContainer messes up nearby Graphics objects. Here is a [codepen](http://codepen.io/kingsleyOneOfMany/pen/QpOROE).

If you change the ParticleContainer at line 27 to a normal Container, rendering is fixed.

I'm using PIXI 4.4.1. using Webgl renderer I expect. 
Problem happens on Mac: Chrome and Safari. Win10: Chrome is bad, however Edge is fine
Here is an [image](https://www.dropbox.com/s/dzvmo7n5llh8krb/Screen%20Shot%202017-03-20%20at%2011.00.21.png?dl=0) of the broken version

**Comment by themoonrat** [comment]
Confirmed fixed in latest PIXI: https://codepen.io/anon/pen/gjPWbP
