### ISSUE TITLE
Container height (or width) gives different values on different runs of the application

### ISSUE THREAD

**Issue by esteban-filardi** [pixijs/pixi.js#3848]
I create a container and add three sprites, then I scale the full container.

I need the container height to calculate the position of an element that should be below the container, but I'm having the issue that the total height of the container changes on every "run" of the application. So the element that comes below always changes position. 
(I'm preloading the images)

Has anyone had this issue?

**Comment by ivanpopelyshev** [comment]
1. Width and height are calculated, based on children position
2. they have side effects, which "getBounds()" doesnt have

I'm afraid you can't use them for relative positioning of the children.

**Comment by esteban-filardi** [comment]
I don't understand why the height changes on every run.  The sizes and positions of the sprites are the same on every run and the sprite below the container is added just after the the container is created.

I'll try to use getBounds() instead. Thanks.

**Comment by ivanpopelyshev** [comment]
Also it matters how do you preload it. Are you using pixi-loader?
