### ISSUE TITLE
Ubuntu - WebGL slows to a crawl and crashes 

### ISSUE THREAD

**Issue by zcr1** [pixijs/pixi.js#3856]
I'm having an issue on a game I'm working on that works perfectly on my weak MacBook Air but comes to a crawl on my desktop which is far beefier, running Ubuntu. Issues are present in both Firefox and Chrome although it seems like only Chrome ends up crashing.

It's difficult for me to isolate the code as it's an intertwined game that is not finished. I included a picture of the chrome profiler though. PC runs the bunny benchmark fine. Using latest version of pixi but have tried a few previous releases as well.

![profile](https://cloud.githubusercontent.com/assets/451388/24169367/ca6b802c-0e53-11e7-83a9-c4c2d38c1a14.png)

Any thoughts?

**Comment by ivanpopelyshev** [comment]
Something about Graphics class. How exactly do you use it?

**Comment by zcr1** [comment]
@ivanpopelyshev Thanks for the hint I seem to have found the issue! I had a few objects with an attached Graphics that drew two rectangles every frame, but I forgot to clear() beforehand. Adding that in seems to have solved it.
