### ISSUE TITLE
Pixi Renderer Resize Issue - Memory Leak / Flickering

### ISSUE THREAD

**Issue by funkybjorn** [pixijs/pixi.js#3860]
Hello!

We are working on a project where the PIXI renderer resizes dynamically. 

We started noticing that the GPU memory would increase every time the renderer was resized, specifically on computers with integrated graphics cards, ultimately causing the web-browser to crash. We also noticed that the renderer would flicker upon resizing in Safari, even on computers with dedicated graphics cards.

Here is a jsFiddle demonstrating the issue : https://jsfiddle.net/funkybjorn/khg7me9f/

Open Activity Monitor / Task Manager and keep on eye on memory usage, and keep in mind that the only thing going on is the resizing of the renderer. On computers with integrated graphics cards it's likely you'll see a massive increase in memory usage very quickly. (Specifically this is happening on a 13" MacBook Pro, Intel Iris Graphics 6100)

We are wondering why this is occurring, and what the workaround is, if any exists.

Thank you!

**Comment by kaansoral** [comment]
I'm very curiously following this issue, out of curiosity, can you track GPU memory through the Task Manager? (I guess it might be because the memory is shared)

**Comment by tekintatar** [comment]
this still exists, it is interesting that chrome task manager shows it is properly collecting garbage but the activity monitor keeps increasing, i think this is not related to pixi but overall webgl. It happens in three.js examples too. Resize your browser when the below animation is running. 
https://threejs.org/examples/#webgl_animation_cloth

**Comment by tekintatar** [comment]
Someone already filed a bug to Apple. there you go:
https://github.com/lionheart/openradar-mirror/issues/16348
