### ISSUE TITLE
Rendering 10,000 graphics, the first render is very slow

### ISSUE THREAD

**Issue by nickli** [pixijs/pixi.js#3861]
Rendering 10,000 graphics, the first render is very slow, the back of the render much faster, is there a way to optimize? The time difference between the two render is too big

**Comment by nickli** [comment]
This situation occurs in the webgl mode, canvas mode render speed is very stable, the first and the back of the render is basically no difference

**Comment by ivanpopelyshev** [comment]
You have to preload texture into GPU. Use "renderer.prepare.upload(item, callback)" : http://pixijs.download/dev/docs/PIXI.prepare.WebGLPrepare.html

**Comment by nickli** [comment]
`for( var i=0,l=10000; i<l; i++ ){

            var graphics = new PIXI.Graphics();
            
            graphics.beginFill(0x4e6dc4 , 0.5);
            graphics.lineStyle(1, 0x4e6dc4, 1);

            var dx = Math.random()*800;
            var dy = Math.random()*600
            graphics.moveTo(210+dx,300+dy);
            graphics.lineTo(450+dx,320+dy);
            graphics.lineTo(570+dx,350+dy);
            graphics.lineTo(330+dx,120+dy);
            graphics.lineTo(410+dx,200+dy); 

            stage.addChild(graphics);           

        }`

I created the 10000 graphics elements, with the prepare and no improvement. Because each of my graphics will have a different matrix, it must be a new instance every time, so that the first frame rate rendering is very slow, probably more than 5000 milliseconds

**Comment by themoonrat** [comment]
For the very best performance, you'll want to be using sprites.  It does this internally automatically for rectangles with no line width. Otherwise you are best off creating one texture yourself and re-using that
