### ISSUE TITLE
NineSlicePlane tint not working at CanvasRenderer

### ISSUE THREAD

**Issue by DerivcoHK** [pixijs/pixi.js#3862]
NineSlicePlane cannot apply tint for canvas renderer but work fine on WebGL renderer

---------------

Found that #2656 does not applied to CanvasMeshRenderer. It is by design?

**Comment by ivanpopelyshev** [comment]
That's a bug. But NineSlicePlane is not using CanvasMeshRenderer: https://github.com/pixijs/pixi.js/blob/dev/src/mesh/NineSlicePlane.js#L154

We can add tinting there, you are right. But I recommend to use "cacheAsBitmap" on it later, otherwise performance will be a problem.

**Comment by DerivcoHK** [comment]
Thanks a lot~

**Comment by zaynyatyi** [comment]
Any info about that feature request?

**Comment by ivanpopelyshev** [comment]
I didnt have time for this :( If you want you can try do it with CanvasTinter, look into CanvasSpriteRenderer how it does the stuff, I'll promise to review the PR. How seriously in peril are you right now? Depends on the case I can do something fast.
