### ISSUE TITLE
PIXI.TextStyle padding doesn't work

### ISSUE THREAD

**Issue by slikts** [pixijs/pixi.js#3865]
Pixi.js 4.4.3
Test case: https://jsfiddle.net/slikts/594p8k17/

The edges of large letters get cut off regardless of the value of the padding style property.

**Comment by ivanpopelyshev** [comment]
Doesn't work on dev too.

**Comment by bigtimebuddy** [comment]
If you `console.log(text.getBounds()`, it looks like this: 

```
height: 2221,
width: 2145,
x: -950,
y: -950
```

The bounds of the Text object seem correct. I think it has to do with the values of that particular character and how the heigh is calculated.

**Comment by slikts** [comment]
Sorry for the confusion, turns out that it's just how Times New Roman looks, and my issue was with a different font and having set `cacheAsBitmap` by mistake.
