### ISSUE TITLE
PIXI.WebGLExtract() not in pixi.js

### ISSUE THREAD

**Issue by jnccneto** [pixijs/pixi.js#3868]
Hi

Was experimenting the PIXI.WebGLExtract() but it does not seem to be in the pixi.js, I am using the https://pixijs.download/release/pixi.js 
I am using it on a mobile/cordova project so no node.js features

Do I need to do any extra step to include it in the file? 

Output
new PIXI.WebGLExtract()
Uncaught TypeError: PIXI.WebGLExtract is not a constructor

Thanks

**Comment by bigtimebuddy** [comment]
There should be a note in the documentation about this. To access, you need to do access the plugin on the WebGLRenderer. For instance:

```js
renderer.plugins.extract
```

This is an instance of WebGLExtract.

**Comment by jnccneto** [comment]
Ok 
it works like that, but didn't found reference on docs.
found some info on the source.

just a final doubt, extract to canvas is doing 
getImageData() 
and then
putImageData()

right?
would it be quicker than doing CanvasRenderingContext2D.drawImage on the renderer.view ?

that's what I am doing so far, so just wondering if I can optimize here

Thanks

**Comment by englercj** [comment]
Only benchmarks can tell. If you do some and find we can optimize extract, please feel free to put in a PR.

Thanks!
