### ISSUE TITLE
Memory leak in Graphics.clear

### ISSUE THREAD

**Issue by Adam13531** [pixijs/pixi.js#3869]
I investigated this and figured out a fix already; I just wanted to file an issue first before making a pull request.

Repro: this is caused by repeatedly clearing a Graphics object and then calling `drawRect` from WebGL. Rendering the Graphics object will call `_renderSpriteRect`, which makes a new Texture that never gets destroyed, so the TextureUvs object that gets created is never dereferenced.

JSFiddle repro link: http://jsfiddle.net/yabm091r/3/

Solution: add this code to Graphics.prototype.clear:
```js
if (this._spriteRect) {
    this._spriteRect.destroy({texture: true});
    this._spriteRect = null;
}
```

P.S. here's a clip of me accidentally filing this bug with the title "tv" (my ctrl key wasn't working): https://clips.twitch.tv/ArbitraryConcernedHamCharlietheUnicorn

**Comment by VitoGaming** [comment]
There's a huge memory leak in my tv caused by pixi: https://clips.twitch.tv/ArbitraryConcernedHamCharlietheUnicorn (pls don't ban me or something)

**Comment by ivanpopelyshev** [comment]
That one is mine, investigating.

**Comment by Adam13531** [comment]
I've submitted a pull request here to make things easier: https://github.com/pixijs/pixi.js/pull/3870

**Comment by ivanpopelyshev** [comment]
White and Empty textures are supposed to be special, no destroy is needed for them. That is critical issue, I'll create PR for master branch.

**Comment by ivanpopelyshev** [comment]
Done, #3872. Build will be here: https://d157l7jdn8e5sf.cloudfront.net/dev-texture-critical/pixi.js

**Comment by ivanpopelyshev** [comment]
And someone just wrote me in KOTLIN slack about twitch translation

**Comment by ivanpopelyshev** [comment]
Timeline from my point of view:

https://www.twitch.tv/videos/130864061
05:28:00 - filling the issue
06:10:00 - submitting issue
06:30:00 - I'm making alternative PR
06:41:00 - you can see our chat
and then we started a talk about a filters
"hackerham : OH GOD FILTERS !#@$%"
06:44:40 - the issue itself

**Comment by englercj** [comment]
@Adam13531 Can you confirm that the PR put in by @ivanpopelyshev fixed you issue? Thanks.

**Comment by Adam13531** [comment]
@englercj yes, I confirmed this on Friday. Thank you both for the quick response times!
