### ISSUE TITLE
Filter issue with sourceFrame.fit

### ISSUE THREAD

**Issue by Adam13531** [pixijs/pixi.js#3873]
I talked to @ivanpopelyshev offline about this and he said to file an issue.

Here's the JSFiddle that I've made: http://jsfiddle.net/xbmhh207/ (edit: updated to Ivan's JSFiddle that loads Pixi.js as an external resource)

It's a combination of code from other resources that I've found. When the bunny goes off-screen, you can see the yellow circle get "squished" into the visible portion of the sprite even though the shader attempts to position this at the center of the sprite. This is due to [this line of code in FilterManager](https://github.com/pixijs/pixi.js/blob/58ccf3381566c009c418aa305924539f372281f3/src/core/renderers/webgl/managers/FilterManager.js#L111). If I comment that out, things "work" perfectly (as in it renders how I'd expect, but I don't know the full repercussions of removing that line). Ivan mentioned that Pixi may need to provide two different modes so that you can choose whether you want sourceFrame.fit to be called based on the filter.

**Comment by ivanpopelyshev** [comment]
Looking @ it

**Comment by ivanpopelyshev** [comment]
That is build together with #3872: https://www.dropbox.com/s/3a98x273twrnans/pixi.js?dl=0

Please test it.

```
filter.dontFit = true;
```

**Comment by ivanpopelyshev** [comment]
@Adam13531 please, next time add pixi to external resources and not to HTML. Your fiddle appears only after a half of minute.

**Comment by ivanpopelyshev** [comment]
Also, http://www.html5gamedevs.com/topic/29327-guide-to-pixi-v4-filters/

**Comment by Adam13531** [comment]
> @Adam13531 please, next time add pixi to external resources and not to HTML. Your fiddle appears only after a half of minute.

@ivanpopelyshev Ah, I didn't realize; I'd modified a JSFiddle that I found through the forums where they made the same mistake. I updated my original post to use your JSFiddle.

> Also, http://www.html5gamedevs.com/topic/29327-guide-to-pixi-v4-filters/
👍 I'll have to take a closer look at this during the week if I still see any problems with my filters.

**Comment by englercj** [comment]
Hey @Adam13531 have you had a chance to take a look at this?

@ivanpopelyshev Do you have a PR or anything related to this issue?

**Comment by Adam13531** [comment]
@englercj sorry for the incredibly delayed response. Using the new `filter.autoFit = false;` works for me!
