### ISSUE TITLE
Modern js and Object.freeze

### ISSUE THREAD

**Issue by drkibitz** [pixijs/pixi.js#3875]
So I remember seeing a change go into InteractionTrackingData.js using `Object.freeze`, hard to track the author might have been @starakaj or @andrewstart. I remember the days when `Object.freeze` and `Object.seal` were laughable in terms of their performance cost, but that was like 5 years ago. Now today, when I saw that change I dug through some jsPerfs to see what was up today. Here's a couple:
- https://jsperf.com/freeze-vs-seal-vs-normal/21
- https://jsperf.com/object-freeze-on-prototype-is-awful-for-performance/4 (this title doesn't really fit anymore 😉 )

No perf cost, and actually, a good boost when simply reading properties of a frozen object. So kudos to whoever decided to use it in InteractionTrackingData 👍 .

So anyway, why am I bringing this up? I think it's worth knowing that things have changed, and with the strict use of eslint, removal of `var` throughout PIXI, it would be worth exploring what would be some good usecases for `Object.freeze`, and keeping it in mind in writing new code.

Some possible candidates would be certain module's exports objects, especially the `const.js` module. Maybe pulling in one of the many [babel freeze plugins](https://www.npmjs.com/package/babel-plugin-object-freeze) for other things like class prototypes, or `const` objects. One thing to note, is with the way certain things mixin, especially the `deprecation.js` module, this would be a selective process, not a blanket approach.

Speaking of `deprecation.js`, probably a good time to remove most of that for PIXI v5!

**Comment by bigtimebuddy** [comment]
One piece of low-hanging fruit in this is freezing the const objects and sealing PIXI.settings. Would welcome a PR for that.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
