### ISSUE TITLE
Module / namespace / class documentation

### ISSUE THREAD

**Issue by drkibitz** [pixijs/pixi.js#3876]
PIXI's documentation has always been great. This is just an issue to make it better. There really needs to be a description of the purpose and usage of a module, namepace, and class.

One in particular is `PIXI.{const name}` versus `PIXI.settings`. What's the difference, why are certain values in one, and others in the other? I would like some documentation to tell me, otherwise I will be going on forums, chat, or create an issue to ask.

Other good examples are just about every available namespace, especially:
- PIXI.prepare: http://pixijs.download/release/docs/PIXI.prepare.html
- PIXI.extras: http://pixijs.download/release/docs/PIXI.extras.html
- PIXI.utils: http://pixijs.download/release/docs/PIXI.utils.html
- PIXI.ticker: http://pixijs.download/release/docs/PIXI.ticker.html (I'm a guilty party for this one)
- and more...

I know people who have been really into PIXI probably think they are self-explanatory. This is at least one person saying they are really not 🦆 .

**Comment by bigtimebuddy** [comment]
Great suggestion. Anyone wanna out there in Pixi-land wanna take a crack at these? Would definitely welcome PR for v4.5.0.

**Comment by bigtimebuddy** [comment]
@drkibitz I added PR #3907 to start to add namespace docs. Would love your feedback on that.

**Comment by drkibitz** [comment]
@bigtimebuddy sorry never got a chance to look at it before merging.

**Comment by drkibitz** [comment]
Everyone else's comments were mine ;) thanks!

**Comment by drkibitz** [comment]
Ok one comment, if `PIXI.settings` is "User customizable", how? If you want to `Object.freeze` it here https://github.com/pixijs/pixi.js/issues/3875#issuecomment-289424833, what is the usage of this? Maybe a little more usage examples would help to understand some of these namespaces, like the settings for one, and other plugins.

**Comment by bigtimebuddy** [comment]
@drkibitz started a new PR for you:  #3876

Also, PIXI.settings should use seal, not freeze. Consts should use freeze, since they are static and don't change. I took a pass at this, but it's complicated because of the deprecations. So I just left them alone for now.

**Comment by drkibitz** [comment]
@bigtimebuddy With that PR I think you've taken care of the goal of this issue.
