### ISSUE TITLE
Documentation / Example 

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixi.js#3879]
Hello, 

I use this lib since the v1/beta and from the v2 I get a bit lost each time I have to reuse PIXI on a project after a long time without using it.

The API changed each time, and thats good it evolve but at the same time it's annoying to google it and found some pixiv2 doc, outdated infos a lot and stuffs like that.

The current Pixi's state make me feel the lib is incredibly powerfull but if you are not fullstack pixijs dev or don't know the right peoples to ask for the advanced questions, its painful to get into it even with good programmation skills & experiences

I suggest for the good of the project to re-organize the current ressources with standard url / improving his seo, and work/rework content to ease & improve the use of pixijs: 

pixijs.com/**manual** : introduce the concept basic & advanced, [see starling](http://manual.starling-framework.org/en/)

pixijs.com/**performance** : tips about performance, [see starling again](http://manual.starling-framework.org/en/#_performance_optimization)

pixijs.com/**docs** : official latest doc with all features + micro example , [see threejs](https://threejs.org/docs/#Reference/Geometries/BoxBufferGeometry)

pixijs.com/**examples** : cover the maximum of features individually ( not only trivial one, basically one by feature/class + advanced examples ), [again threejs](https://threejs.org/examples/#webgl_postprocessing_glitch)

I know its work to provide there and not a one day/one month work but with the community PIXI have Im sure it'll be worth it to standardize it and then build it over the year, especly with the coming up of PIXI v5 / 3d / and all the amazing stuffs! 

edit:swapped threejs links

**Comment by drkibitz** [comment]
Additional thought, pixijs.com/**try**. Think playground or in-browser fiddle.
The current examples could even be modified to just support this.

I think pixi as a whole has come a looooong way, and it is basically there with most of what is mentioned in this issue, just needs a little more love on the continuous integration side, and maybe an update to https://github.com/pixijs/pixi.js/blob/dev/CONTRIBUTING.md. First comes first though, **tests**, and those are coming in now with more contributions than ever from the core team as well as the community. Once there are tests and high coverage on a project like this, everything else becomes surprisingly a lot easier. It can just be a rather difficult mountain the scale ⛰, and takes a lot of time and resources to do it. Worth it. It's good to have people focused on the tooling and community involvement while others focused on innovation. Only in the past year (maybe year and a half), this has happened and has gained a lot of momentum recently. So really, things are humming along in my opinion.

One thing I have never mentioned, but have always thought was a little cumbersome is the fact that pixi still pushes http://www.html5gamedevs.com/forum/15-pixijs/ for discussion. It's a pretty large community and active forum, but I wonder how many people use and watch pixi without ever joining in there? It's just another login to me, and feels rather disconnected and informal compared to the rest of the project. Not a big deal, but with pixi becoming more popular by the week/day, it might be time to host it's own forum or some other channel with a very cheap barrier to access.

@Makio64 FYI, your threejs links are swapped.

**Comment by GoodBoyDigital** [comment]
Very good points @Makio64 ! Docs and examples is definitely something we are always keen to improve!

Anyone out there who enjoys a bit of fancy helping out in this area and pulling things together. We would love to have you on the team :D

@drkibitz good point, maybe it is time for us to create a pixi forum? I agree that pixi is being used for more than just games at the mo! 

Once the v5 API is settled i will certainly make sure that we have more tests / examples and docs too :)

**Comment by Makio64** [comment]
About thé forum why not stackoverflow/github?
