### ISSUE TITLE
WebGL extract giving empty image

### ISSUE THREAD

**Issue by noffle** [pixijs/pixi.js#3880]
I'm trying to use the WebGLExtract class to create screenshots, but am getting a black image instead (of the correct dimensions). 

```js
    var sourceCanvas = renderer.extract.canvas();
    var sourceContext = sourceCanvas.getContext('2d');
    var extractCanvas = document.createElement('canvas');
    var extractContext = extractCanvas.getContext('2d');
    var imageData = sourceContext.getImageData(x, y, width, height);

    extractCanvas.width = width;
    extractCanvas.height = height;
    extractContext.putImageData(imageData, 0, 0);
    return extractCanvas.toDataURL();
```

I've also tried just accessing `sourceCanvas.toDataURL()` directly, but with the same results. Any chance I've forgotten something obvious?

**Comment by ivanpopelyshev** [comment]
It can happen in some cases, but if you pass your stage there, and it gets imageData just after rendering it - I'm sure it'll work.

```js
renderer.extract.canvas(stage);
```

And if you are friday-night-drunk and forgot where is your stage

```js
renderer.extract.canvas(renderer._lastObjectRendered);
```

**Comment by englercj** [comment]
Hey @noffle is this still an issue?

**Comment by noffle** [comment]
@ivanpopelyshev That did it! Thank you so much. :heart:  And thanks @englercj for poking me on this.

**Comment by gebeto** [comment]
@ivanpopelyshev **Спасибо тебе огромное!**
