### ISSUE TITLE
Container issue with `updateTransform`

### ISSUE THREAD

**Issue by lgraziani2712** [pixijs/pixi.js#3882]
Hello, I don't know if I'm doing things wrong or it's a **bug**.

### Basic information

- PixiJS version: 4.4.3

### Description

When a class extends `PIXI.Container`, it's possible to use the `updateTransform` hook. But if inside the constructor you modify a `PIXI.Container` property, it will stop the construction of the object and will call `updateTransform`.

Thing is, if you read, for example, the same property setted on the constructor, it will create an infinite loop.

Here is a live example: http://codepen.io/lgraziani/pen/aJjwNZ?editors=0011

This is the basic class example:

```js
class BunnyContainer extends PIXI.Container {
  constructor() {
    super();
    
    // PIXI.Container prop
    this.width = 100;

    // It will never reach here
    this.bunny = PIXI.Sprite.fromImage('http://pixijs.github.io/examples/required/assets/basics/bunny.png');
    this.bunny.anchor.x = 0.5;
    this.bunny.anchor.x = 0.5;
    this.bunny.position.y = this.bunny.position.x = 50;
    
    
    this.addChild(this.bunny);
  }
  updateTransform() {
    const bunnyPosition = this.width * 0.1;
    
    // It will never reach here
    this.bunny.position.x = bunyPosition;
  }
}
```

If is there anything I can help just tell me :)

Thank you!

**Comment by ivanpopelyshev** [comment]
Width is calculated based on positions of children and uses updateTransform if there are any. Its not css element width, its a bounding box. Use either "bunny.width" either "bunny.

**Comment by ivanpopelyshev** [comment]
sorry, hit wrong button

**Comment by lgraziani2712** [comment]
Ok, and what if I don't specify the width inside the constructor but still want to use it inside `updateTransform`? It still crash

**Comment by andrewstart** [comment]
Because `updateTransform` is intended to prepare the object for rendering, you probably don't want to be reading or changing the display tree within it.

**Comment by ivanpopelyshev** [comment]
spine uses updateTransform to animate some parts so its ok. just dont use "width" property, use some other name

**Comment by lgraziani2712** [comment]
Perfect! Thank you for your help :)
