### ISSUE TITLE
PIXI.Text does not respect renderer resolution

### ISSUE THREAD

**Issue by windsurfer** [pixijs/pixi.js#3883]
No matter what the renderer's resolution is set to, PIXI.Text will always render the text at resolution 1.

**Comment by ivanpopelyshev** [comment]
I think text and filters respect "PIXI.settings.RESOLUTION"

**Comment by windsurfer** [comment]
The comment says it should: "The resolution / device pixel ratio of the canvas. This is set automatically by the renderer." [Text.js#L66](https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L66)

Is the comment wrong? Or am I reading it wrong?

**Comment by bigtimebuddy** [comment]
Yes, this is incorrect. It should read: "The resolution / device pixel ratio of the canvas. The default is set by `PIXI.settings.RESOLUTION`"

**Comment by themoonrat** [comment]
However, both rendererWebGL and _rendererCanvas force the resolution of text to be what the resolution of the renderer is
```
if (this.resolution !== renderer.resolution)
{
  this.resolution = renderer.resolution;
  this.dirty = true;
}
```

**Comment by bigtimebuddy** [comment]
Seems like @themoonrat is right.

@windsurfer can you provide an example?

**Comment by englercj** [comment]
Hey @windsurfer have you had a chance to provide us with a running example so we can track down this issue? Thanks!

**Comment by themoonrat** [comment]
Going to close this in favour of https://github.com/pixijs/pixi.js/issues/4034 which seems to have more traction in being assigned to the relevant person
