### ISSUE TITLE
v4.3.3 WebGLRenderer Errors

### ISSUE THREAD

**Issue by jeensshi** [pixijs/pixi.js#3884]
v4.3.3
i just replace the code:
renderer =PIXI.autoDetectRenderer(width, height);
by:
renderer = PIXI.WebGLRenderer(width, height);
then errors come:
Cannot call a class as a function

i traced the code and found that 
_classCallCheck(this, WebGLRenderer); made errors.

can some one tell me what caused it.
ps: webgl is supported by my  browser;

**Comment by prachtan** [comment]
renderer = **new** PIXI.WebGLRenderer(width, height); ?

**Comment by jeensshi** [comment]
it worked!!!
thank you for answering.
