### ISSUE TITLE
Filters - Padding texture management explanations

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixi.js#3888]
Hello, I created a manual displacement without sprite and only using a canvas texture to acheived some glitch effect but some, even with the use of the padding, it looks like the uv dont go for 0-1 0-1 and actually use pixel from other texture in some case : 

the color on the right are not blue and from another image, only filter on the left element

![screen](https://www.dropbox.com/s/3i7cxxh2h54q0cg/Screen%20Shot%202017-03-28%20at%209.38.59%20AM.png?dl=1) 

on above left / right element are not even close element, same textures parts shows up even I move the left element.

Can someone clarify it how the texture are managed in intern , I see displacementFilter use some sprite / matrix but i feel its useless in my case, thanks!

**Comment by ivanpopelyshev** [comment]
Hello, Makio! Yes, filters are difficult, and they even more difficult in pixi-v4 because it uses pool of textures with pow2-dimensions. I've put lot of time in R&D:

https://github.com/pixijs/pixi.js/wiki/Creating-Filters-in-Pixi-v4

**Comment by englercj** [comment]
Closing this, since it seems like the question was answered.
