### ISSUE TITLE
Pixi v4 bug mask?

### ISSUE THREAD

**Issue by williammanco** [pixijs/pixi.js#3889]
Hello, in Pixi v3 masks works in additive way (for me is correct) in Pixi v4 they work in exclude mode.

Look at the examples, same code but different results, is a bug? I need the result as in Pixi v3, but i need to use v4.

Thanks 👍 

Pixi v4
![schermata 2017-03-28 alle 11 15 25](https://cloud.githubusercontent.com/assets/3954950/24397894/e50e4442-13a7-11e7-87de-e124f7b8bfa3.png)

Pixi v3
![schermata 2017-03-28 alle 11 15 35](https://cloud.githubusercontent.com/assets/3954950/24397902/eb8d9eee-13a7-11e7-9bdc-dcb400fe0aff.png)

http://codepen.io/williammanco/pen/RpYzGV
http://codepen.io/williammanco/pen/xqaoKK

**Comment by prachtan** [comment]
_As part of my pixi learing program and my investigation_ :)

The problem only occurs on webGL renderer.

Graphics are packed and rendered as a single triangle strip:

`webGLData.vao.draw(gl.TRIANGLE_STRIP, webGLData.indices.length);`
_https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/webgl/GraphicsRenderer.js#L112_

For above examples, in area of shape intersection, multiple triangles are rendered.

That generates problem in StencilManager:

`gl.stencilOp(gl.KEEP, gl.KEEP, gl.INCR);`
_https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/managers/StencilManager.js#L64_

multiple pass for same area, increments the value in stencil buffer, and that implies false result in test function:
 
`gl.stencilFunc(gl.NOTEQUAL, 0, sms.length);`
_https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/managers/StencilManager.js#L69_

For example `gl.REPLACE` here:
`gl.stencilOp(gl.KEEP, gl.KEEP, gl.REPLACE);`
_https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/managers/StencilManager.js#L64_

for above examples, works well, but I don't now _yet_ how and when `stencilMaskStack` may be longer than one _(gl.REPLACE probably will break `gl.stencilFunc(gl.NOTEQUAL, 0, sms.length);`)_

@themoonrat
