### ISSUE TITLE
NineSlicePlane in canvas renderer has little gap on it

### ISSUE THREAD

**Issue by DerivcoHK** [pixijs/pixi.js#3891]
As you can see here, NineSlicePlane has some little gap on it when using CanvasRenderer. Any work around can fix this issue?
![nine-slice-plane](https://cloud.githubusercontent.com/assets/16910927/24436112/332a7d3e-146c-11e7-919d-64d7fa1114ce.png)

**Comment by themoonrat** [comment]
does 
roundPixels: true
help when creating the renderer?

**Comment by DerivcoHK** [comment]
It does help when the scale of the mesh is 1.
Problem still exists when scale > 1

**Comment by themoonrat** [comment]
Closing as was fixed in 4549
