### ISSUE TITLE
TilingSprite CanvasRenderer @2x images tilePosition bug

### ISSUE THREAD

**Issue by brenwell** [pixijs/pixi.js#3892]
Hello everyone

I have noticed that when animating the `tilePosition.x` of an instance of `PIXI.extras.TilingSprite` with the canvasRenderer and the sprite is built from a source retina @2x image e.g. myImage@2x.png there is a jump when the new tile is added to the left, I think its a simple miscalculation error.

I have made an example, simply watch a wait until the tilePosition.x is a factor of  256px

http://jsfiddle.net/brenwell/kn6zvpnL/12/

I looked through the issues and there seemed to be many similar issues but not this exact one

Thanks for any help in advance

**Comment by ivanpopelyshev** [comment]
Good catch!
