### ISSUE TITLE
Tinting Grey Areas

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#3893]
I have some sprites and I'd like to apply a tint to them. 

However, part of the sprite is already coloured and some of the pixels are grey- I'd only like to tint the grey pixels.

How could I do this?

**Comment by ivanpopelyshev** [comment]
red tint, as an example

```js
sprite.tint = 0xFF0000
```

**Comment by DubiousDillan** [comment]
@ivanpopelyshev oh gosh- sorry! I literally forgot to finish typing out that post before sending. Here we go- I'd like to tint the grey areas of a sprite (where all colour values are the same) but keep the coloured areas.

**Comment by ivanpopelyshev** [comment]
The easiest way is to separate texture into two, and tint only one of them.

But its actually depends on your task - sometimes you can just write custom shader https://github.com/pixijs/pixi-plugin-example , or even pre-calculate your tint like we are doing it https://gameofbombs.com/ctor/index.html

**Comment by DubiousDillan** [comment]
Thank you!
