### ISSUE TITLE
How use modules?

### ISSUE THREAD

**Issue by Edisoni** [pixijs/pixi.js#3898]
![2017-03-30 20 36 33](https://cloud.githubusercontent.com/assets/10086099/24518434/ad72c654-158a-11e7-813a-717f21e460c4.png)

**Comment by andrewstart** [comment]
I'm not sure I understand. Is this a question about how to use javascript modules in general?

**Comment by Edisoni** [comment]
@andrewstart how to import { Sprite, Container }  from pixi ?

![2017-03-31 14 25 36](https://cloud.githubusercontent.com/assets/10086099/24548447/edea930e-161d-11e7-9ecc-2a52174605cd.png)
No sprite,container

**Comment by Edisoni** [comment]
i install pixi with npm

**Comment by englercj** [comment]
`import { Sprite, Container } from 'pixi.js'` is correct.

**Comment by ivanpopelyshev** [comment]
I want to know how to use it with webpack too.
