### ISSUE TITLE
Apply Tint to Particle Container

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#3899]
Why do particle containers not allow you to tint the entire thing, like you can do to a sprite?

How would I go about efficiently tinting an entire particle container? (It needs to be re-tinted, since it changes colour.)

**Comment by englercj** [comment]
No particular reason we *cant* do it. Just a matter of adding another uniform where we upload the tint value of the `ParticleContainer`. We could also add support for uploading the tint value of each sprite in the attributes, but it does cost a bit more memory to do that.

Does having a tint on `ParticleContainer` only that is applied to all sprites seem useful?

**Comment by thamaranth** [comment]
Is this still available?

**Comment by englercj** [comment]
@thamaranth Sure, feel free to put in a PR for this if you are interested in contributing.

**Comment by bigtimebuddy** [comment]
Closing, fixed with #4014
