### ISSUE TITLE
Memory leak when discarding PIXI.Text objects on Chrome

### ISSUE THREAD

**Issue by bsep-chromium** [pixijs/pixi.js#3900]
I wrote a simple program that's leaking memory at an alarming rate, on the order of a megabyte a second:
```
var count = 0;
var text = null;

function updateText(app) {
  if (text)
    app.stage.removeChild(text);
  text = new PIXI.Text("nice " + count);
  app.stage.addChild(text);
};

window.onload = function() {
  var app = new PIXI.Application(800, 600, {backgroundColor: 0x1099bb});
  document.body.appendChild(app.view);

  updateText(app);
  app.ticker.add(function() {
    count += 1;
    updateText(app);
  });
};
```

I thought it was a Chrome bug originally and went to investigate, since it doesn't seem to reproduce on Firefox, but Chrome's memory tools claim it's leaking instances of `HTMLCanvasElement` in `BaseTexture.source` (I think). I see "BaseTextureCache in system / Context" in there too, if that's a helpful hint.

Plus if you call `text.destroy()` before calling `app.stage.removeChild(text)` the leak appears to go away. But [the documentation on PIXI.Text#destroy](http://pixijs.download/release/docs/PIXI.Text.html#destroy) states that you shouldn't need to call `destroy()` on a PIXI.Text object.

I'm still not totally convinced this isn't Chrome's fault so if you discover evidence that it is I can file a bug there and follow up.

Windows 10 version 1511, tested on Chrome versions 56 (stable) and 59 (canary).

**Comment by bsep-chromium** [comment]
Forgot to mention this is with Pixi version 4.4.4

**Comment by bigtimebuddy** [comment]
The problem is your approach to the text field, you should not create a new text field on every frame, that will allocate a crazy about of memory. Use the same text field and set the text properly to update the display instead.

**Comment by ivanpopelyshev** [comment]
PIXI automatically removes old Text textures with garbage collector, it just doesnt happen in the same second, you have to wait two minutes or so.

**Comment by bsep-chromium** [comment]
I'm aware that allocating a new Text object every frame is not typical, but it makes the memory leak show up faster. And I'm fairly certain this is a real memory leak. Here is a screenshot of the test program using over a gig of memory after about 10 minutes:
<img width="581" alt="pixi memory leak" src="https://cloud.githubusercontent.com/assets/26828752/24582415/734a05d6-16e4-11e7-8afa-cc7be351283c.PNG">

Just to double-check I added a key that stops it from allocating new Text objects, in an attempt to let the garbage collector catch up. When it's stopped the memory doesn't increase of course, but it also doesn't decrease even after waiting several minutes.

**Comment by bigtimebuddy** [comment]
The documentation says:

> Note* Unlike a Sprite, a Text object will automatically destroy its baseTexture and texture as the majority of the time the texture will not be shared with any other Sprites.

There's probably some confusion. This does _not_ mean that you do not need to call `destroy` method, it means that the baseTexture is handled during the destroy and you don't need to explicitly destroy that with the destroy options.

**Comment by bsep-chromium** [comment]
I see, that would be the problem then. I assumed I didn't have to manually manage memory since there's no mention of `destroy` in the tutorials. Thanks for clearing that up.

I tested Firefox again and I was supposed to be looking at the plugin-container.exe process, so that's why it didn't appear to be leaking.
