### ISSUE TITLE
Graphics disappears when cached and multiple filters are applied

### ISSUE THREAD

**Issue by mikeqcp** [pixijs/pixi.js#3901]
I've noticed following behavior of _PIXI.Graphics_ object (checked on v4.4.4).
It disappears completely from scene when there are 3 conditions fulfilled:
1) it has at least one filter applied
2) one of its parent containers also has at least one filter applied
3) cacheAsBitmap is set to _true_

Removing any of those points fixes the issue.

Please see here: http://codepen.io/miq/pen/XMONQz
The item without filters is visible all the time.
The second one only appears if you comment out one of 3 described lines.

Is there any explanation of this, or is it a bug?

**Comment by ivanpopelyshev** [comment]
Graphics + Filter + cacheAsBitmap = COMBO

**Comment by themoonrat** [comment]
Closing as the advice https://github.com/pixijs/pixi.js/issues/4659 applies to here too.... for v4 it's just a tough combo that causes issues
