### ISSUE TITLE
Support for Measuring Text

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#3903]
I am trying to determine a way to measure a block of text given a `TextStyle` without having to render it to the screen.  I'd like to determine the "measured" width and height of the text if it were rendered without word-wrapping but Pixi.js doesn't seem to have any mechanism to do this.  Am I missing something?

**Comment by andrewstart** [comment]
One option is to call `myText.updateText(true)` - it's a private method, but it will update the text without drawing it to the screen immediately. The updated text will be drawn during the next render however, and the method is somewhat expensive as it has to draw your text to its internal canvas, as usual.

Alternatively, you could [do the same calculations as Text does](https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L149). Keep in mind that if you would need to account for outer stroke width and drop shadows, if present.

**Comment by darkfrog26** [comment]
I'm really surprised there isn't just a method on `TextStyle` called `measure` that does this.  Wouldn't `updateText(true)` apply wrapping if defined on the `Text` thus not giving a true measurement of the text itself?

**Comment by bigtimebuddy** [comment]
The TextStyle class just maintains the style settings, but doesn't provide any functionality. But I would definitely welcome a PR which provides a public method on the `Text` class to measure text (basically abstracts the little bit @andrewstart highlighted). @darkfrog26 is this something you might be interested in doing?

**Comment by darkfrog26** [comment]
Perhaps, I'll take a look at it in more detail later. I've been creating a facade around Pixi (https://github.com/outr/scalajs-pixijs) but haven't actually touched the code yet.

**Comment by darkfrog26** [comment]
@bigtimebuddy what would you say to a PR that adds a method to `TextStyle` for `measure(text: String): PIXI.Rectangle`?  This would give the ability to measure text without the need of creating a `Text`.

If you're opposed to that I can go ahead with a method on `Text`.

**Comment by englercj** [comment]
link #3921

**Comment by themoonrat** [comment]
Added in 4.50
