### ISSUE TITLE
iOS Google Font Text broken?

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi.js#3905]
Hey,

I tried this page http://pixijs.github.io/examples/#/demos/text-demo.js on my iPhone 6S with iOS 10.3 and I got:
![img_0224](https://cloud.githubusercontent.com/assets/687978/24617641/c9890314-1894-11e7-8afb-db56f0f452a5.PNG)

I've also the same issue on my project, but once the Text is updated everything is fine.

**Comment by kcbleeker** [comment]
Hey @alamboley 

We ran into the same problem, removed -apple-system from our font list and had no problems - I think our default is now BlinkMacSystemFont on iOS.

**Comment by alamboley** [comment]
Thanks for the answer. It's probably a dumb question, but how did you remove it?

**Comment by kcbleeker** [comment]
Sounds like you maybe don't have a font list yourself. You can pass font options to the PIXI Text object when creating it: https://pixijs.github.io/examples/#/basics/text.js

If the default isn't working, pass in a font of your choice.

**Comment by englercj** [comment]
Closing this, since it seems answered. Thanks @kcbleeker for helping out!

**Comment by alamboley** [comment]
Well it isn't really solved @englercj, online example isn't fixed!!

**Comment by englercj** [comment]
The fix is to change the font list for your device, this isn't a bug. Just that your device doesn't have that example's `Snippet` font. Simply use a different font.

**Comment by alamboley** [comment]
Sorry, feeling a bit dumb but just to be sure, this line `families: ['Snippet', 'Arvo:700italic', 'Podkova:700']` load three google fonts. Snippet doesn't work, so it means this font isn't compatible with iOS? Didn't know that some Google Fonts won't work on mobile.

**Comment by englercj** [comment]
Some fonts can not work on all kinds of OSes. Not sure if that is the issue here, but if you see if the font is getting loaded properly before the rendering starts you can tell. Maybe it is a font loader issue and not a pixi issue.

Pixi uses the system to render text. If a font doesn't work, it isn't pixi because we don't render fonts. We just write text to canvas and let the browser do it.
