### ISSUE TITLE
Big issue with animation's Wobbling

### ISSUE THREAD

**Issue by tywang2006** [pixijs/pixi.js#3906]
Hi guys, i make animation in sprite sheet and set scale to 0.5 for better performance in the latest version. 
but the animation is Wobbling all the time especially for the small size of animated item. I tried PRECISION to high, low and default, all is not working. it happens on iphone 6+, but working well in browser.

**Comment by themoonrat** [comment]
In the latest version of PIXI

PIXI.settings.PRECISION_FRAGMENT = 'highp';

solves that problem for me

**Comment by ivanpopelyshev** [comment]
Also, using https://github.com/pixijs/pixi-picture and adding "sprite.pluginName = 'picture'" helps in some cases.

**Comment by themoonrat** [comment]
@tywang2006 closing as I believe the above 2 answers solve your issue. Feel free to reopen if the solutions don't work for you :)
