### ISSUE TITLE
CanvasRenderer.render bug using RenderTexture.

### ISSUE THREAD

**Issue by YayoiAyame** [pixijs/pixi.js#3911]
http://pixijs.github.io/examples/#/basics/render-texture.js

In this example, if specifying `noWebGL=true` in the constructor and animating to move position of ` container`, past display content will remain when rendering RenderTexture and it will not be displayed correctly.
Since this bug does not occur in `WebGLRenderer.render` , it seems to be a bug in `CanvasRenderer.render`.

<img width="695" alt="rendertexture_bug" src="https://cloud.githubusercontent.com/assets/6729410/24720420/1274b71e-1a78-11e7-9967-a676e85d0ed8.png">

**Comment by wildaces215** [comment]
Is this open?
