### ISSUE TITLE
'tap' event fired not correctly

### ISSUE THREAD

**Issue by ThomasKasim** [pixijs/pixi.js#3912]
Started from 4.4.0, 'tap' is fired when touch started outside the object and then ended inside the object,
even if there is a "div" overlaid upon it

**Comment by bigtimebuddy** [comment]
Hello! Could you please provide a jsfiddle of the issue happening with the latest release (4.4.4). Thanks for your help.

**Comment by themoonrat** [comment]
@ThomasKasim We're upto 4.5.2 now... a fiddle demonstrating your problem on the latest version would be awesome. Thanks!

**Comment by ThomasKasim** [comment]
It is fixed on 4.5.1. Thanks all.
