### ISSUE TITLE
Support for 2.5d sprite

### ISSUE THREAD

**Issue by tywang2006** [pixijs/pixi.js#3916]
Can we make sprite rotationX, rotatonY, rotationZ, and x, y and z

**Comment by englercj** [comment]
Not in v4, *maybe* in v5.

**Comment by tywang2006** [comment]
Ok, thanks, can you put in to-do of v5, actually I really hope you guys can make it in v4.5 or provide a plugin:)

**Comment by pkieltyka** [comment]
hey guys, just wondering if there are any branches or experiments inside or out of pixi relating to this? It would be great to have some 2.5d support, thanks

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-projection

There's a hope that i'll port my 3d sprites from ]old 3d fork](https://gameofbombs.github.io/pixi-bin/index.html?s=flip&f=cards.js&title=Cards) to this plugin.

**Comment by GoodBoyDigital** [comment]
v5 baby!

**Comment by tywang2006** [comment]
I did my own in my project too, it is webgl only
