### ISSUE TITLE
Deprecation warnings show when importing PIXI using Systemjs

### ISSUE THREAD

**Issue by JustASquid** [pixijs/pixi.js#3917]
When using the module loader [Systemjs](https://github.com/systemjs/systemjs) to load PIXI, it triggers a whole bunch of deprecation warnings:

![Deprecation warnings](https://i.gyazo.com/fc2fce7ff321294d766d12dff9bc86fe.png)

I originally thought that it was a problem with Systemjs so I brought it up with them in [this issue.](https://github.com/systemjs/systemjs/issues/1651) However it seems like this is a problem based on the way imports/exports work, combined with the way PIXI handles its deprecation warnings using setters.

I'm not even sure if this issue is fixable, but I thought I'd bring it up here.

**Comment by englercj** [comment]
This means your code is using deprecated things, those warnings are there to let you know which items are deprecated and how to fix them.

These are issues with pixi, but warnings from pixi to you about your code. :)

**Comment by JustASquid** [comment]
@englercj As you can see in the linked issue, I'm not actually using these features at all. Instead, the way systemjs loads PIXI causes the deprecation warnings to show up.

**Comment by englercj** [comment]
Ah interesting, sorry I didn't read the other issue first. Thanks for reporting this.
