### ISSUE TITLE
RenderTexture with TilingSprite does not wrap around

### ISSUE THREAD

**Issue by jaime4d** [pixijs/pixi.js#3918]
I want to be able to scroll a few Sprites arranged vertically within a Tiling Sprite.   I was hoping a RenderSprite and TilingSprite would do the trick to render very efficiently.  Say, for example I have image 1, image 2, image 3 stacked up one after the other.  I want to scroll these three images within a rectangular area along the y axis; but I want the images two wrap around seamlessly.  The effect I want to achieve is very similar to how a slot machine would display and scroll its reel symbols.  I started doing all this work moving individual sprites around, but using RenderTexture would be more efficient.   

How is this done with Pixi using RenderTexture?

**Comment by englercj** [comment]
Honestly, I think your best bet is to have 3 sprites and just reset the positions as it moves around. Will be simpler than doing something more clever with RenderTexture and may have similar (or better) performance since you aren't using an extra Framebuffer.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
