### ISSUE TITLE
Updating Stage Size Causes Scaling

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#3919]
I have a `SystemRenderer` and `Container` (for `stage`) representing a simple example (based on http://pixijs.github.io/examples/#/basics/basic.js).  However, I'm attempting to resize the canvas using `systemRenderer.resize(width, height)` and then calling `stage.width = width; stage.height = height` but this seems to cause scaling issues.  If I don't set the stage width and height then everything stays like it should.  I assume this is probably intentional, but I'm failing to understand why it is?  Shouldn't the stage represent the same size as the renderer?

**Comment by ivanpopelyshev** [comment]
Stage is container. Container doesn't have proper width and height, its not HTML element or div, width and height are calculated based on bounds of all objects in inside of it.

```js
stage.scale.x = width / YOUR_APP_WIDTH;
stage.scale.y = height / YOUR_APP_WIDTH;
```

that will do :)

**Comment by darkfrog26** [comment]
Thank you, I think I understand now.  Updating the size manually on a Container causes the scale to adjust as a result?  I just changed my code to update the scale to 1.0 after each update to size.

**Comment by ivanpopelyshev** [comment]
Yep, scale is first-class citizen, while width and height are derivatives. "container.width = 100" actually changes the scale.

**Comment by darkfrog26** [comment]
Thanks for the insights.
