### ISSUE TITLE
Lack of Event Documentation

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#3920]
This has been driving me crazy for a while, but the utter lack of documentation regarding events is very frustrating.  I see that `Texture` does fire an `update` event, but what does that event look like?  What properties does it contain?  Why is it not documented?

**Comment by englercj** [comment]
Because someone hasn't written it yet :)

You can see what is emitted here: https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Texture.js#L200

Its just itself as the only parameter.

**Comment by darkfrog26** [comment]
Is that the case with most events?  Do they typically just fire with a reference to the owner instead of an actual event object?

**Comment by axelvaindal** [comment]
If I remember correctly, events are based on `EventEmitter` provided by the Node.js implementation, which you can find here : https://nodejs.org/api/events.html. 
This is probably why the base about events is not documented, this would be redundant.

However, based on source code, many fired event in Pixi are given with an object containing :

- the name of the event
- the data about the event (thus, you get the event target and position)

This is actually the case for all `DisplayObject` ( such as `Container` or `Sprite` for instance), as you can see there : https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js 

For specific case, such as `Texture`, I'm afraid you will have to jump into the source code to see which data are actually provided during the event emitting considering no documentation about this exist at the moment.

**Comment by englercj** [comment]
> Is that the case with most events? Do they typically just fire with a reference to the owner instead of an actual event object?

No, just the one you mentioned. The event can emit anything we pass in, and we will pass along what is relevant for that event. Best thing to do is to read the source and improve the docs as you go along. @bigtimebuddy has already put in a PR to improve many of them.

**Comment by bigtimebuddy** [comment]
Fixed with #3922

**Comment by darkfrog26** [comment]
@bigtimebuddy thanks. :)
