### ISSUE TITLE
FilterManager. Code style may be a potential error.

### ISSUE THREAD

**Issue by mmykola** [pixijs/pixi.js#3926]
Hi, I used custom filter with settings: 
```
uniforms: {
        uMyTexture: {
          type: 'sampler2d',
          value: ''
        }
}
```
but it doesn't work so I changed type to 'sampler2D'. 
There was code 
```
if (uniformData[i].type === 'sampler2D' && uniforms[i] !== 0) {
```
in FilterManager.syncUniforms class.

Perhaps you need to check type for 'sampler2D' in a register lowercase?

**Comment by englercj** [comment]
That's a good idea. We used `sampler2D` because that is the actual type, however you are right that doing a `.toLowerCase()` on the type could catch issues like this and probably ones with the other type too.

Do you have time to put a PR in that does a `.toLowerCase()` before checking types?

**Comment by mmykola** [comment]
Yes, I'll create a pull request with fixed.
