### ISSUE TITLE
pixi in rollup dosen't work after build

### ISSUE THREAD

**Issue by luzhuang** [pixijs/pixi.js#3927]
it's say  No name was provided for external module 'url' in options.globals – guessing 'url'
No name was provided for external module 'path' in options.globals – guessing 'require$$1'

Dose pixi run in browser need url or path ?

i install them  it's not work either

**Comment by bigtimebuddy** [comment]
Are you using [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins)? **url** and **path** are Node APIs that PIXI uses and which are provided as Browserify's built-ins.

**Comment by luzhuang** [comment]
no ,  i just use rollup-plugin-node-resolve to  us the lib  , should i use rollup-plugin-node-builtins?

**Comment by luzhuang** [comment]
no , i just use rollup-plugin-node-resolve to use the lib , should i use rollup-plugin-node-builtins?

**Comment by luzhuang** [comment]
this'is  my devdependence:
"autoprefixer": "^6.5.3",
    "ava": "^0.17.0",
    "babel-cli": "^6.24.0",
    "babel-eslint": "^7.1.1",
    "babel-plugin-object-assign": "^1.2.1",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "browser-env": "^2.0.16",
    "compare-versions": "^3.0.0",
    "cross-env": "^3.1.4",
    "css-loader": "^0.26.1",
    "eslint": "^3.11.1",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^2.0.6",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-flow-vars": "^0.5.0",
    "eslint-plugin-html": "^1.7.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "extend": "^3.0.0",
    "ghooks": "^1.3.2",
    "gzip-size": "^3.0.0",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "mkdirp": "^0.5.1",
    "nyc": "^10.0.0",
    "postcss-loader": "^1.2.0",
    "postcss-px2rem": "^0.3.0",
    "rimraf": "^2.5.4",
    "rollup": "^0.41.6",
    "rollup-loader": "^0.0.2",
    "rollup-plugin-buble": "^0.14.0",
    "rollup-plugin-commonjs": "^7.0.0",
    "rollup-plugin-less": "^0.1.1",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "rollup-plugin-uglify": "^1.0.1",
    "rollup-plugin-vue": "^2.2.10",
    "standard": "^8.6.0",
    "style-loader": "^0.13.1",
    "uglify-js": "^2.7.5",
    "webpack": "^1.13.3",
    "webpack-dev-server": "^1.16.2",
    "webpack-merge": "^1.0.2",
    "webpack-notifier": "^1.4.1"

**Comment by bigtimebuddy** [comment]
Not positive. Give it a shot.

**Comment by luzhuang** [comment]
i write a demo    https://github.com/luzhuang/pixirollup.git    look at  the dist/component.js

**Comment by luzhuang** [comment]
.config/.rollup.config.js  is my rollup file

**Comment by luzhuang** [comment]
.config/rollup.config.js is my rollup file

**Comment by englercj** [comment]
Have you tried the plugin that @bigtimebuddy recommended?

**Comment by GoodBoyDigital** [comment]
v5 uses rollup, so this should be good now :)
