### ISSUE TITLE
prepare plugin does not work if you only switch textures in animatedSprite.textures

### ISSUE THREAD

**Issue by krompir2** [pixijs/pixi.js#3932]
Take a look at this example: http://forwardingsolutions.club/issue/px5

On **second** click, there should be texture atlas already loaded in GPU, because this function is called on first click:

```
function loadNext() {
    if (firstRun) {
        infiniteLoader.add('jimages/2s.png.json');
        infiniteLoader.load(function (loader, resources) {
            next.textures = setupFrames("2_000"); // setupFrames just prepares textures 

            app.renderer.plugins.prepare.upload(next, () => {
                canRunNext = true;
                $("body").css("background-color","green");
            });
        });
...
}
```

However, there is still significant delay between click and the start of animation. I am not sure if this is a bug or am I just too stupid to use prepare functionality correctly, so I'll just leave it here for you to decide :)

What I am trying to achieve is to load texture atlases dynamically and display them on click without any delay. At the same time the click happens, the previously loaded texture atlas gets played. Sounds a lot easier than it is, because a running texture atlas animation freezes for example when new sprite is added to canvas.

**Comment by englercj** [comment]
Please refer to the forum thread where I answered your questions:

http://www.html5gamedevs.com/topic/29700-unexpected-delay-when-loading-texture-atlases-dynamiclly/

JS is synchronous, you can only do 1 thing at a time. If a texture is uploading, you have to wait for it. Whether it is us doing it automatically for you, or if you put it into prepare; it still takes the same time to upload.
