### ISSUE TITLE
Available features in pixi.js for creating the 'jpg, png images' to make a game Spritesheet by 'directly URL from API'?

### ISSUE THREAD

**Issue by flyjwayur** [pixijs/pixi.js#3934]
Hello :) I am a newbie in pixi.js and quite beginner in programming. 
I am not sure whether I can ask question here ;) 
If it's ok, could I ask some advice?

*Briefly my question is : If I want to create the 'jpg, png images' to make a game Spritesheet by 'directly URL from API', which keywords should I search for in pixi.js OR should I use other way(like make this url from API to dataUrl and make dataUrl to image file) ?:) I have worked on creating Spritesheet for several hours but I couldnt understand thoroughly and I was not able to succeed to create it. 

[This is the situation :)]
I am working on the school thesis project for which I try to create a puzzle game using Chromecast.
Today, I fetched the some image data from Finna API(https://www.kiwi.fi/x/dYU1Aw) but I confronted with another obstacle.

I need to make a game spritesheet which has a format jpg, png etc. I have been using pixi.js and I used to use Texturepacker software to create Spritesheet manually as an pixi example. But now I need to create the game Spritesheet automatically by code. Finna API display the image by URL(not jpg, png etc format). (like this => https://finna.fi/Cover/Show?id=musketti.M012:HK19321130:15583-1906)

I'm not sure this issue is related in this case (https://github.com/pixijs/pixi.js/issues/2985).

**Comment by h3rb** [comment]
https://github.com/kittykatattack/learningPixi   This covers it as far as reading in sprites from a texture ..

 the URL provided texture can be from a PHP file, for instance, which assembles a sprite sheet from ImageMagick, but I don't recommend this as it puts a load on the server (you should precompute it when the images are uploaded or something)

An example in PHP to create an image from an image using php-imagick:
`<?php
 function thumbnailImage($imagePath) {
  $im = new Imagick();
  $im->setBackgroundColor(new ImagickPixel('transparent'));
  $im->readImage(realpath($imagePath));
  $dim=$im->getImageGeometry();
  if ( !isset($_GET['wh']) ) $wh=100; $wh=intval($_GET['wh']);
  if ( $wh <= 0 ) $wh=100;
//  $aspect=floatval($dim['width'])/floatval($dim['height']);
//  $inverse_aspect=floatval($dim['height'])/floatval($dim['width']);
  $width=$wh;
  $height=$wh;
  $im->setImageFormat("png32");
  $im->thumbnailImage($width,$height, true, true);
  header("Content-Type: image/png");
  echo $im;
 }
 if ( isset($_GET['src']) ) {
  try {
   @thumbnailImage(urldecode($_GET['src']));
  } catch ( Exception $e ) {}
 }`   Source: http://github.com/h3rb/page

You could modify the above to do other operations or use imagick "convert" from the command line, then output the file similar to above in PHP see http://www.fmwconcepts.com/imagemagick/coloration/index.php (tons of image magick command line bash scripts)

**Comment by flyjwayur** [comment]
@h3rb thank you ! I just have frontend and not the backend for our project (using github.io currently) so it seems like I can't use this way but Thanks for giving me the idea!

**Comment by h3rb** [comment]
@flyjwayur Does this help? https://blog.webkid.io/image-processing-in-javascript/

**Comment by englercj** [comment]
Hope this helped answer your question. Going to go ahead and close this.
