### ISSUE TITLE
modularizing removeItems?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#3939]
hey folks! Long time no see. :)

a while back we worked on an implementation of array splice that doesnt generate memory garbage. 2 years on and I have yet to find as high a quality version as the one we worked on. I want to use this in several projects, so I've modularized it here, in this npm module:

https://github.com/mreinstein/remove-array-items

Are y'all open to a PR to include this module? Happy to send one along. Just let me know what branch you'd like it in, etc.

thanks!

-Mike

**Comment by englercj** [comment]
I don't have many feelings about this, looks like it is the same code we are currently using. Curious what we buy by moving to use the module rather than the one we have in the lib already?

**Comment by mreinstein** [comment]
> Curious what we buy by moving to use the 
> module rather than the one we have in the 
> lib already

Not much of any substance, although I've used this snippet in at least 5 different projects/modules. Given there is little to no cost in modularizing this it seems like a good opportunity for re-use.

**Comment by englercj** [comment]
As long as we can maintain the current level of documentation we have for that method I'm all for moving to a module.

Did you move our tests there too when you made the repo?

**Comment by mreinstein** [comment]
> Did you move our tests there too 
> when you made the repo?

Yep its in there and wired up to Travis
