### ISSUE TITLE
Mask clipping wrong position if rotate

### ISSUE THREAD

**Issue by laminhtruong** [pixijs/pixi.js#3947]
Hi Team

I just got issue with mask. The mask will transform incorrect when i rotate container. Can you help me check.

**Here is my code**

```javascript
this.splash = new PIXI.Sprite(PIXI.loader.resources.imgSplash.texture);
this.splash.anchor.set(0.5, 0.5);
this.splash.position.set(APP.GetWidth() / 2, APP.GetHeight() / 2);

this.splash.mask = new PIXI.Graphics();
this.splash.mask.beginFill(0xFF700B, 1);
this.splash.mask.drawRect(200, 200, 120, 120);
this.splash.mask.endFill();

this.background.addChild(this.splash);

let abc = new PIXI.Graphics();
abc.beginFill(0xFF700B, 1);
abc.drawRect(200, 400, 120, 120);
abc.endFill();

this.background.addChild(abc);
````

**And here is my result**

- Not rotate background container
![11](https://cloud.githubusercontent.com/assets/27716922/25112691/0f9eb3d8-241d-11e7-9589-0c8347bd6a12.png)

- Rotate background container
![22](https://cloud.githubusercontent.com/assets/27716922/25112693/0fd0c7f6-241d-11e7-9cc9-45fbbd7ff6dd.png)

- Not rotate background container and without mask
![33](https://cloud.githubusercontent.com/assets/27716922/25112692/0fa18536-241d-11e7-99d5-0d01f4676fa0.png)

Thanks
Truong

**Comment by staff0rd** [comment]
If you want the mask to transform with the container, add the mask to the container;

Mask not in container;
![image](https://user-images.githubusercontent.com/6289998/29991626-e71a161a-8fcd-11e7-89b5-5f65825766e3.png)

Mask in container;
![image](https://user-images.githubusercontent.com/6289998/29991627-f20e5392-8fcd-11e7-9f5d-3ae1e33f9327.png)

See the last line of [this pen](https://codepen.io/staff0rd/pen/GvzXyQ?editors=0010)

**Comment by ivanpopelyshev** [comment]
You have to add "this.splash.mask " somewhere too

```js
background.addChild(this.splash.mask);
```

Imagine that mask is an element like others (sprite, graphics), it can be inside container and will be transformed with it. I dont know how to explain it further :(
