### ISSUE TITLE
Loader svg bug IOS

### ISSUE THREAD

**Issue by hendrysadrak** [pixijs/pixi.js#3949]
When using PIXI.loader to load textures and later using those textures, the textures look like they are drawn over eachother.

Output on MacOS Chrome:
![image](https://cloud.githubusercontent.com/assets/4000963/25122179/a8411fa4-242c-11e7-9a3f-fc5e3ee277ca.png)
On MacOS Safari: (same on ios safari)
![image](https://cloud.githubusercontent.com/assets/4000963/25122196/b738582e-242c-11e7-84df-b05ab7a9d947.png)
Will add live test case in sec

**Comment by hendrysadrak** [comment]
Live test case:
https://beta.hendrysadrak.com/pixibug1/

**Comment by hendrysadrak** [comment]
Does not reproduce when using like this:
`app.stage.addChild(PIXI.Sprite.fromImage('./svg/s1.svg'));`

**Comment by hendrysadrak** [comment]
IOS screenshot:
![18015807_1634559826571748_2146190201_o](https://cloud.githubusercontent.com/assets/4000963/25122436/97f7e564-242d-11e7-8bfe-2b6e0a4b5ece.jpg)

**Comment by hendrysadrak** [comment]
Also, all the svg's have the same width/height if that can be the case

**Comment by englercj** [comment]
If you add `legacy: true` to the options passed into PIXI.Application, does that fix your issue?

**Comment by hendrysadrak** [comment]
Nope, doesn't help. 
Though, can't it be resource-loader or loader middleware issue? Because if i don't preload the assets and later construct sprites from those and create sprites like `PIXI.Sprite.fromImage('./svg/s1.svg')` then it is ok

**Comment by hendrysadrak** [comment]
@englercj any updates?

**Comment by englercj** [comment]
Nope, I don't have any iOS devices so someone else will have to track this down.

**Comment by hendrysadrak** [comment]
@ivanpopelyshev 😬

**Comment by hendrysadrak** [comment]
No updates regarding this?

**Comment by GoodBoyDigital** [comment]
heya! I think this should be working better in v5 👍

**Comment by glennflanagan** [comment]
@GoodBoyDigital are you able to share how this was resolved in V5 so us V4-ers are able to fix in the meantime?

**Comment by ivanpopelyshev** [comment]
Is it still the issue? try to reproduce it with just canvas+svg+webgl-texture-upload , without pixi and send it to apple.

As for V5, we've made a release so you can test it. I doubt that @GoodBoyDigital has any time to do that for you.

**Comment by hendrysadrak** [comment]
I fixed this by creating a svg loading middleware for loader which loads the svg and creates a texture itself.

**Comment by glennflanagan** [comment]
@hendrysadrak I know I'm being cheeky but any chance you can share that middleware? I'm super new to all this WebGL and SVG stuff and I feel like I'm swinging in the dark with a lot of my attempts.

**Comment by hendrysadrak** [comment]
@glennflanagan will do when i have a free moment

**Comment by hendrysadrak** [comment]
Svg loader middleware.
```javascript
const pixelRatio = window.devicePixelRatio || 1;

function svgLoader( resource, next ) {
  if ( resource.extension !== 'svg' ) return next();

  const canvas = document.createElement( 'canvas' );
  const ctx    = canvas.getContext( '2d' );
  const image  = new Image();

  const onImageLoad = () => {
    canvas.width = image.width *= pixelRatio;
    canvas.height = image.height *= pixelRatio;

    ctx.drawImage( image, 0, 0, canvas.width, canvas.height );

    resource.texture = PIXI.Texture.fromCanvas( canvas );

    resource.complete();
    next();
  };

  image.addEventListener( "load", onImageLoad );

  image.crossOrigin = 'anonymous';
  image.src         = resource.url;
}
```

Add it to PIXI.loader before loading anything.

```javascript
PIXI.loader.pre( svgLoader );
```

**Comment by NickRimer03** [comment]
Yeah, I've got this bug too. Seems that it's still actual in Safari (I'm using v.4.7.1)
