### ISSUE TITLE
Event not bubbling through Sprite

### ISSUE THREAD

**Issue by megmut** [pixijs/pixi.js#3950]
Hey guys, I'm not sure if this is a bug or an intended functionality change. In 4.4.1, my use case flow is as follows.

1. Make sprite graphics cover entire screen
2. Draw hole in graphics
3. Perform hit test if input is in hole (do nothing, allow event to bubble)
4. If outside of hole, use 'event.stopPropagation()'

This works fine, if the click is inside the hole, then anything inside that hole, (underneath in the display list) then it also captures gets triggered.

However after upgrading to 4.5.0, the event does not bubble through the sprite, and it's input handler is eating the object. When inspecting, the event, it looks like the current target is null, which is not what I would normally expect?

![screen shot 2017-04-18 at 12 13 48](https://cloud.githubusercontent.com/assets/10081046/25125841/8d3bc868-2430-11e7-978d-239379d3f8e8.png)

**Comment by andrewstart** [comment]
Between 4.4.1 and 4.5.0, we made a few patches that fixed situations where mouse ups and clicks were improperly happening when they should not. Is it possible that your use case was dependent on that bug?

**Comment by megmut** [comment]
Haha, quite possible! In that case, if you had two sprites, of the same size (eg 100x100) directly stacked on top of each other, and both had interactivity.. If you clicked on the top one, would you expect the one underneath to catch the click?

**Comment by andrewstart** [comment]
The answer to that question is indeed no. 
It sounds like a solution could be a new hit testing method that gets all interactive children under a single point, without firing events (to be performed by the dev on the InteractionManager's `click` event).
Another solution could be to manually hit test against specific things upon click events on a given sprite on top.

**Comment by megmut** [comment]
Okay, I understand. I didn't realise that the event won't bubble to those children not in the display order tree. You can go ahead and close this! Sorry for the false alarm.
