### ISSUE TITLE
How to create bitmap at runtime?

### ISSUE THREAD

**Issue by luyang177** [pixijs/pixi.js#3951]
How to create bitmap at runtime?
I mean I have an array of binary image data, how to create bitmap at runtime in order to using pixijs display it?

**Comment by englercj** [comment]
You could draw it to a canvas with [putImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData), then use that canvas as a texture.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
