### ISSUE TITLE
Centering PIXI.Graphics inside Container

### ISSUE THREAD

**Issue by Shawak** [pixijs/pixi.js#3953]
How to archieve that?

I'm looking for smth like this: https://pixijs.github.io/examples/#/basics/container-pivot.js

But PIXi.Graphics doesnt support the anchor property, I couldnt find anything else on the docs/internet either.

**Comment by englercj** [comment]
Just position it in the center, offseting for your size:

```js
graphics.position.x = (container.width / 2) - (graphics.width / 2);
graphics.position.y = (container.height / 2) - (graphics.height / 2);
```

**Comment by Shawak** [comment]
And how to rotate it then?

**Comment by englercj** [comment]
Have you tried setting the pivot to be centered and rotating it?

**Comment by bigtimebuddy** [comment]
@Shawak check this out:
https://jsfiddle.net/scvwdy74/

**Comment by Shawak** [comment]
Thanks for trying to help me @bigtimebuddy but this example is not using a container with multiple graphics.

**Comment by bigtimebuddy** [comment]
I'm not exactly sure what you're trying to do here. 

To change the rotational point, set `container.pivot.x` and `container.pivot.y`, like @englercj suggested. These x, y values are relative to the coordinates of the container, not the stage.

**Comment by msqaddura** [comment]
It is much simpler than that, you can do code below
```
class MyContainer extends PIXI.Container {
    _anchorX = 0;
    _anchorY = 0;


    set anchorX(value) {
        this._anchorX = value;
        this.pivot.x = value * this.width / this.scale.x;
    }

    get anchorX() {
        return this._anchorX;
    }

    set anchorY(value) {
        this._anchorY = value;
        this.pivot.y = value * this.height / this.scale.y;
    }

    get anchorY(){
        return this._anchorY;
    }


}

```

Then the only thing you need to do is to is to update it the pivot everytime you change the affective ones (width, height, scale.x, scale.y) you can do so by 

`
myContainer.anchorX = myContainer.anchorX;
`
or you can add something like that inside MyContainer class:
```
refershAnchors(){
this.anchorX = this.anchorX;
this.anchorY = this.anchorY;
}

```
I personally override the setters and getters for height, width, pivot.x, pivot.y inside MyContainer class
