### ISSUE TITLE
Question? - visibility=false vs alpha=0

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi.js#3955]
Hi sorry to post here, if there is somewhere better for questions let me know.
Just wondering from an optimisation point of view is there any difference between alpha=0 and visibility =false;
The docs seem to suggest that visibility=false would be the most performant, is this correct?

Thanks

**Comment by ivanpopelyshev** [comment]
"visible=false" turns off transform updates of element and children. "renderable=false" turns of only render. "alpha=0" doesnt even affect interaction.

**Comment by macguffin** [comment]
Thanks, Ivan I thought so.

**Comment by bigtimebuddy** [comment]
Closing this. Thanks @ivanpopelyshev for that answer.
