### ISSUE TITLE
Drop Shadow Color

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#3960]
I'm probably doing something wrong here, but when I do a drop shadow the blurred edges show the right color but the inner portion always seems to appear black.  Is there something else I need to set to make it show red as well?

Example: https://jsfiddle.net/u5tt0z8u/2/

**Comment by themoonrat** [comment]
A bug was introduced from v4, whereby the drop shadow is linked to the stroke thickness :/

**Comment by themoonrat** [comment]
Nopes, not that, the colour stops working when shadow blur is used
