### ISSUE TITLE
PIXI.loader.add image instead of json file

### ISSUE THREAD

**Issue by krompir2** [pixijs/pixi.js#3962]
I have a couple of texture atlases. The order of textures that create animation is the same in all of them. In other words, my first frame of animation is always (0,0,100,100), my second frame is in all atlases (100,0,100,100) and so on. The only thing that changes is meta's image: "image1.png". It changes to "image3.png" and so on. Frames in all texture atlases are named the same

```
{
    "meta": {
        "image": "image1.png",
        "size": {"w"1000,"h":2000},
        "scale": "1"
    },
    "frames": {
        "image_0000.png":
        {
            "frame": {"x":0,"y":0,"w":100,"h":100},
            "rotated": false,
            "trimmed": false,
            "spriteSourceSize": {"x":0,"y":0,"w":100,"h":100},
            "sourceSize": {"w":100,"h":100}
        },
        "image_0001.png":{...}

    }
}
```

I have a couple of texture atlases. The order of textures that create animation is the same in all of them. In other words, my first frame of animation is always (0,0,100,100), my second frame is in all atlases (100,0,100,100) and so on. The only thing that changes is meta's image: "image1.png". It changes to "image3.png" and so on. Frames in all texture atlases are named the same

 
It is kinda wasteful to load 10 different json files, because the positions and frame names are always the same for all of the animations. How can I load images instead of json files?

```
PIXI.loader .add(['assets/file1.json']); // don't wanna load 10 json files
function createFrames(name, imageToUse) {
    var frames = [];

    for (var i = 0; i < 30; i++) {
        var val = i < 10 ? '0' + i : i;
        frames.push(PIXI.Texture.fromFrame(name + val + '.png')); // use imageToUse to tell PIXI from which image should it create frames.
    }
    return frames;
}
```

**Comment by bigtimebuddy** [comment]
Good question.

If you want to use the same JSON data for different images, I would suggest that you check out the [Spritesheet API](http://pixijs.download/release/docs/PIXI.Spritesheet.html). This is used by the loader to generate all the textures from the data and image.

```js
// Lets assume this is your preloaded JSON
var data = {};

// Load your images normally
PIXI.loader.add('image1', 'image1.png')
  .add('image2', 'image2.png')
  .add('image3', 'image3.png')
  .load(function(loader, resources) {
    for (var name in resources) {
       // Create a new spritesheet with loaded image and data
       var spritesheet = new PIXI.Spritesheet(resources[name].texture.baseTexture, data);
       spritesheet.parse(function(){
          console.log(spritesheet.texture);
       });
     }
  });
```

Hope that helps.

**Comment by Username-is-already-taken** [comment]
This might work for you, depending on your needs...

```
var myTextures = [];
for(var i = 0; i < 40; i++) {
    myTextures.push(new PIXI.Texture(textures['myImage.png'].texture, new PIXI.Rectangle(150 * i, 0, 150, 150))); 
}
var spr = new PIXI.extras.AnimatedSprite(myTextures);
```
Doesn't require any JSON, just load your image and chop it into frames.
