### ISSUE TITLE
BUG: Graphic/generatedTexture/NineSlicedSprite something goes wrong

### ISSUE THREAD

**Issue by Tigerwulf** [pixijs/pixi.js#3964]
So first of all, we create 2 fiddle versions with Pixi 4.3.5 and 4.5.0.
In every version is a different behavior.

The first rec is graphic object, with issues on the border.
The second one is a generatedSprite of the first one. That has just a pixel issue in the middle of each  border. (Zoom in to see it)
The last one is a nineSlicedSprite with the texture of the second one. The corners looks broken and  in version 4.5.0 the are scaled too!

Till the version 4.3.5 we used a workaround that give some better look for the generated graphics/textures. When you put the workaround bool to false or true, it has different behavior again.

Fiddle:
v4.3.5 http://jsfiddle.net/sD8Tt/335/
v.4.5.0 http://jsfiddle.net/sD8Tt/336/

I guess there are more than one bug. Hope it helps to find them.

**Comment by Tigerwulf** [comment]
Eh, sry that Fiddle examples dont represent clearly the bug. That ticket here can be close.
The main problem is that in 4.4.4 the nineSlicedSprite works good, but in 4.5.1 goes something wrong. I'll open a new ticket next week, that will showes better the main problems.

Sry for that.

**Comment by englercj** [comment]
NO problem @Tigerwulf thanks for trying to get this tracked down.
