### ISSUE TITLE
Alpha transparency ignored for Graphics cached as bitmap?

### ISSUE THREAD

**Issue by thomas-dm** [pixijs/pixi.js#3965]
Hello,

I just wanted to ask about something I found out today, namely the fact that the `alpha` property seems to be completely ignored for `Graphics` elements that _have been_ or _will be_ cached as bitmap using `cacheAsBitmap = true` in Pixi 4.5.0.

I also want to point out that:
1) This used to work in previous versions of Pixi (I tested it in 4.0.0);
2) There is no issue with `Sprite` elements.

I cooked up a small [fiddle](https://jsfiddle.net/94ra2o9v/) so you can check for yourself.

Is this the expected behavior now?

Thank you

**Comment by bigtimebuddy** [comment]
Hmm interesting. I am not sure the behavior is working quite right in v4.0.0 either. When you cacheAsBitmap, it looks like it becomes _more_ transparent. 

The workaround seems to be to wrap the Graphics in a Container:
https://jsfiddle.net/sd1ebmjg/

**Comment by themoonrat** [comment]
Issue still exists, but we'll track via https://github.com/pixijs/pixi.js/issues/4610
