### ISSUE TITLE
Uncaught Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 1205 + 5 > 1209 Y: 0 + 402 > 402

### ISSUE THREAD

**Issue by mirosssc** [pixijs/pixi.js#3966]
I'm new to pixi and I'm following the book. I'm trying to figure out what is the problem here. Happens when I'm trying to make moving animation sprite with su.filmstrip(....) function. Unless I specify exact dimensions of the tileset it's not working and throwing this error. However I want to specify the size of one frame.
Thanks for replying

**Comment by bigtimebuddy** [comment]
Hello, glad that you're learning Pixi! 

Could you please provide some more information about what you're doing or include a snippet of your code? Your title and description don't give us enough information about what's going on or why you might be getting that error.

Please include what version of Pixi you're using, as well.

**Comment by mirosssc** [comment]
Pixi.js version 4.5.0. 

It's this part:

u.filmstrip("anyTilesetImage.png", frameWidth, frameHeight, optionalPadding);

let textures = u.filmstrip("tileset.png", 32, 32);
let anySprite = u.sprite(textures);

After I specify frameWidth and frameHeight of the frame that I want to crop, error occurs

**Comment by mirosssc** [comment]
And this is the whole snippet of my code:

// load helper SpriteUtilities library
let su = new SpriteUtilities(PIXI);

// make aliases

    // everything is in container
let Container = PIXI.Container,

    // detects whether to use webgl or canvas smthng automatically
    autoDetectRenderer = PIXI.autoDetectRenderer,

    // loader for images and so
    loader = PIXI.loader,

    // get sources
    resources = PIXI.loader.resources,

    // sprite object
    Sprite = PIXI.Sprite;

//Create the renderer
let renderer = autoDetectRenderer(512, 512,{antialias: false, transparent: false, resolution: 1});

//Add the canvas to the HTML document
document.body.appendChild(renderer.view);
renderer.view.style.border = "3px dashed red";
renderer.backgroundColor = 0xe7e7e7;

//Create a container object called the `stage`
let stage = new Container();

loader
  .add("img/tezdzbrajd.json")
	.load(setup);

let bot;

//Set the game's current state to `play`:
let state = play;

function setup() {

  // let anySprite = su.sprite('img/tezdzbrajd.png', 32, 32);

  let frames = su.filmstrip("img/tezdzbrajd.png", 5, 402, 0);
let tezdzbrajd = su.sprite(frames);



  //Create a AnimatedSprite from the frames
  bot = new PIXI.extras.AnimatedSprite(frames);
bot.play();

bot.animationSpeed = 0.1;

	stage.addChild(bot);

	bot.x = 0;
	bot.y = 0;

	// speed modularity for bot
	bot.vx = 0;
	bot.vy = 0;

	//Capture the keyboard arrow keys
	var left = keyboard(37),
	  up = keyboard(38),
	  right = keyboard(39),
	  down = keyboard(40);

   	//Left arrow key `press` method
  	left.press = () => {
	    //Change the sprite's velocity when the key is pressed
	    bot.vx = -5;
    	bot.vy = 0;
  	};

  	//Left arrow key `release` method
  	left.release = () => {
		//If the left arrow has been released, and the right arrow isn't down, //and the pixie isn't moving vertically, stop the sprite from moving //by setting its velocity to zero
		if (!right.isDown && bot.vy === 0) {
	    	bot.vx = 0;
	    }
	};

	//Up
  	up.press = () => {
    	bot.vy = -5;
    	bot.vx = 0;
	};

	up.release = () => {
    	if (!down.isDown && bot.vx === 0) {
      		bot.vy = 0;
    	}
	};

	//Right
  	right.press = () => {
    	bot.vx = 5;
	    bot.vy = 0;
  	};

  	right.release = () => {
    	if (!left.isDown && bot.vy === 0) {
      		bot.vx = 0;
		} 
	};

	//Down
  	down.press = () => {
    	bot.vy = 5;
    	bot.vx = 0;
  	};

  	down.release = () => {
    	if (!up.isDown && bot.vx === 0) {
  			bot.vy = 0;
		} 
	};

	//Tell the `renderer` to `render` the `stage`
	renderer.render(stage);

	//Call the `gameLoop` function once to get it started
	gameLoop();
}

function gameLoop(){

  	//Loop this function 60 times per second
	requestAnimationFrame(gameLoop);

	//Update the current game state:
	state();

	  //Render the stage
  	renderer.render(stage);
}

function play() {

	//Apply the velocity values to the sprite's position to make it move
	bot.x += bot.vx;
	bot.y += bot.vy;
}

function keyboard(keyCode) {
  var key = {};
  key.code = keyCode;
  key.isDown = false;
  key.isUp = true;
  key.press = undefined;
  key.release = undefined;

  //The `downHandler`
  key.downHandler = function(event) {
    if (event.keyCode === key.code) {
      if (key.isUp && key.press) key.press();
      key.isDown = true;
      key.isUp = false;
    }
    event.preventDefault();
  };

  //The `upHandler`
  key.upHandler = function(event) {
    if (event.keyCode === key.code) {
      if (key.isDown && key.release) key.release();
      key.isDown = false;
      key.isUp = true;
    }
    event.preventDefault();
  };

  //Attach event listeners
  window.addEventListener("keydown", key.downHandler.bind(key), false);

  window.addEventListener("keyup", key.upHandler.bind(key), false);

  //Return the `key` object
  return key;
}

**Comment by themoonrat** [comment]
@mirosssc Sorry it's been so long... going to close due to this being around for so long; hope you found a solution, and if you have any more questions please raise a new issue :)
