### ISSUE TITLE
Inconsistent behavior between WebGL renderer and canvas PIXI.Application(forceCanvas) when a canvas as view is specified

### ISSUE THREAD

**Issue by aerusso** [pixijs/pixi.js#3967]
[Minimal example](https://jsfiddle.net/z1re71rn/)

When WebGL is available and forceCanvas is false, no red line appears in the output. When forceCanvas is enabled or WebGL is unavailable (and fallback to canvas is automatic) the red line appears, as expected.

Chrome 58 on Linux, nvidia graphics drivers, not that it should matter. This is 4.5.1

**Comment by bigtimebuddy** [comment]
Seems like an bug with `dirty` flag on Graphics which is not forcing WebGL to re-render the Graphics. Adding `clearDirty++` seems to resolve. https://jsfiddle.net/z1re71rn/4/

@ivanpopelyshev could you look at this?

**Comment by themoonrat** [comment]
Closing as fixed; don't see it using latest version of pixi: https://jsfiddle.net/e5ur7bow/1/
