### ISSUE TITLE
Deprecation Warnings with 4.5.0 and 4.5.1

### ISSUE THREAD

**Issue by overdub60** [pixijs/pixi.js#3968]
When I updated to pixi 4.5.0 I started getting several deprecation warnings

```
Deprecation Warning: getFontStyle is now deprecated, please use TextStyle.toFontString() instead
Deprecation Warning: Text.fontPropertiesCache is deprecated
```

Now, I am not calling these methods at all. It looks like they are being called from pixi's own calculateTextStyle() method, which I am not calling myself either. I just set up a couple of text objects, that's it.

I'm using pixi with es6, babel and webpack.

Can anyone help?

**Comment by bigtimebuddy** [comment]
Ahh, I see. We recently refactored these things, but there are still references [here](https://github.com/pixijs/pixi.js/blob/dev/src/prepare/BasePrepare.js#L433-L448) in BasePrepare. Should be an easy fix. Thanks for pointing this out.
