### ISSUE TITLE
Cursor effects not working in v4.5.1

### ISSUE THREAD

**Issue by luozan** [pixijs/pixi.js#3971]
The cursor of sprite not working when I set it.

`sprite.cursor = 'text';`

[https://jsfiddle.net/sd1ebmjg/1/](https://jsfiddle.net/sd1ebmjg/1/)

**Comment by andrewstart** [comment]
In version 4.3.0, we added the [`cursorStyles` dictionary](http://pixijs.download/release/docs/PIXI.interaction.InteractionManager.html#cursorStyles) to the InteractionManager, to allow even more flexibility in cursor usage. The `cursor` property on your sprite is used to select which what to use from `cursorStyles`. 

Add the following to your jsfiddle to make it work correctly:
```javascript
app.renderer.plugins.interaction.cursorStyles.text = 'text';
```

However, we should make a patch to use the cursor mode as a CSS value if there is nothing present in `cursorStyles`.

**Comment by luozan** [comment]
Thank you very much!
