### ISSUE TITLE
FilterState retains destroyed sprites

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#3973]
Steps

- Take heap snapshot
- add some bunny
- take heap snapshot
- destroy bunnies container
- collect garbage
- take an heap snapshot
- filter by "Objects allocated between Snapshow 1 and Snapshot 2"

Some destroyed sprites (and related resources like _boundsRect) are retained by FilterState
![test](https://cloud.githubusercontent.com/assets/15343100/25430727/0da201b8-2a7e-11e7-8be9-370dfc4d3692.png)

[test.zip](https://github.com/pixijs/pixi.js/files/958086/test.zip)

**Comment by englercj** [comment]
Good catch, thanks for the steps and test case. Hopefully we can take care of this soon.

**Comment by YahorPadlucki** [comment]
Hi @englercj, @lucap86  - can you check my PR for this issue?
