### ISSUE TITLE
Bower install pixi.js fetch data from dev branch

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#3979]
bower install pixi.js fetch data from dev branch

**Comment by bigtimebuddy** [comment]
Not sure what you are asking. Please clarify.

We have dropped support for Bower in Pixi 4.5.0+. We suggest you use npm or yarn for package management.

**Comment by lucap86** [comment]
ok
readme says..

![readme](https://cloud.githubusercontent.com/assets/15343100/25530131/6fab712a-2c25-11e7-8251-c6abf330700b.png)

if bower support has been dropped readme should be updated.

**Comment by bigtimebuddy** [comment]
Yup, we missed this! Will fix.
