### ISSUE TITLE
FXAA filter error, Failed to execute 'getProgramParameter' on 'WebGLRenderingContext'

### ISSUE THREAD

**Issue by Rojoss** [pixijs/pixi.js#3981]
I'm trying to use the FXAA filter but I'm getting the following error.
When you add the following line to any example on the PIXI examples site you get the error.
``app.stage.filters = [ new PIXI.filters.FXAAFilter()];``
Am I doing something wrong, is it related to my graphic card or is it a bug?

```
Uncaught TypeError: Failed to execute 'getProgramParameter' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at extractAttributes (pixi.js:2686)
    at Shader (pixi.js:1791)
    at new Shader (pixi.js:8049)
    at FilterManager.applyFilter (pixi.js:18682)
    at FXAAFilter.apply (pixi.js:18180)
    at FilterManager.popFilter (pixi.js:18625)
    at Container.renderAdvancedWebGL (pixi.js:9270)
    at Container.renderWebGL (pixi.js:9207)
    at WebGLRenderer.render (pixi.js:17338)
    at Application.render (pixi.js:7905)
```

Before that error I also get a few warnings which seem related.
![image](https://cloud.githubusercontent.com/assets/1093861/25533407/ddd0d0ae-2c30-11e7-94cf-5fa6e3be736f.png)

**Comment by strunkie30** [comment]
Same here on OSX.

**Comment by jmlee2k** [comment]
I'm getting the same thing on windows 10, looks like it can't compile the shader.

**Comment by bigtimebuddy** [comment]
JSFiddle reproduces error: https://jsfiddle.net/hzcf5536/

**Comment by jmlee2k** [comment]
Chrome doesn't give any info about why it can't compile the shader, but the Firefox console shows:

Pixi.js Warning: gl.getProgramInfoLog() Uniform `filterArea` is not linkable between attached shaders.

Hopefully this helps.

**Comment by GoodBoyDigital** [comment]
Hello there! Thanks for reporting the bug! Will let you know when this has been addressed 👍

**Comment by GoodBoyDigital** [comment]
thanks for thefiddle @bigtimebuddy

**Comment by jmlee2k** [comment]
Looks like this may be a duplicate (or at least related to) #3822.

When using `PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH`, the filter appears to work without issue.  As @ivanpopelyshev said, it's a workaround, not a fix.

**Comment by englercj** [comment]
Looks like this is a duplicate of that issue, closing this one.
