### ISSUE TITLE
Camera following player

### ISSUE THREAD

**Issue by mirosssc** [pixijs/pixi.js#3982]
So basically what is the most efficient way to do this with Pixi? I want
1. camera basically to follow a player and change the background according to the position of player
2. scroll the world only if player is for example 400 px from right end of canvas and 300 px from left end of canvas
3. things like enemies, things on the ground and objects adapt accordingly(adapt with the scenery too).

Thanks in advance

**Comment by ivanpopelyshev** [comment]
make "Camera" container, put everything there.

```js
camera.position.set(renderer.screen.width/2, renderer.screen.height/2);
camera.pivot.copy(player.position);

//EVERY FRAME

var targetPivot = player.position;

//LERP IT
camera.pivot.x = (targetPivot.x - camera.pivot.x) * dt + camera.pivot.x;
camera.pivot.y = (targetPivot.y - camera.pivot.y) * dt + camera.pivot.y;

//big square

var mapRect = new PIXI.Rectangle();
mapRect.x = camera.pivot.x - renderer.screen.width/2;
mapRect.y = camera.pivot.x - renderer.screen.height/2;
mapRect.width  = renderer.screen.width;
mapRect.height = renderer.screen.height;
mapRect.enlarge(400);

//every time camera changes position


var newRect = new PIXI.Rectangle();
newRect .x = camera.pivot.x - renderer.screen.width/2;
newRect .y = camera.pivot.x - renderer.screen.height/2;
newRect .width  = renderer.screen.width;
newRect .height = renderer.screen.height;
if (newRect.x < mapRect.x || newRect.right > mapRect.right ||
   newRect.y < mapRect.y ||  newRect.bottom > mapRect.bottom) {
   mapRect = newRect;
   //ADJUST THE BACKGROUND AND STUFF
}
```

**Comment by ivanpopelyshev** [comment]
Somebody, please make that a wiki article.

**Comment by mirosssc** [comment]
Thank you. It does the job however I'm not able to accomplish 2. point. The result of mapRect.enlarge(400); is NaN. According to documentation there's supposed to be another rectangle. 
If you could just explain it in a little more detail that would be great.
Thank you.

**Comment by ivanpopelyshev** [comment]
OK, use "pad(400,400)"" instead ;)

**Comment by mirosssc** [comment]
There still seems to be the problem because in every frame newRect.x is always gonna be bigger. I am missing something huge in here i guess :(

**Comment by ivanpopelyshev** [comment]
@mirosssc 

```
mapRect = newRect;
mapRect.pad(400,400);
```

also make sure you create newRect every time. If you dont, please use "mapRect.copy(newRect);" instead of assignment.

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
