### ISSUE TITLE
TextMetrics Character Locations

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#3983]
I'm working on writing a text editing feature for Pixi.js and realized that it would be much easier if `TextMetrics` included offset positions and widths for characters. This isn't incredibly hard to calculate it myself, but with kerning, it's not incredibly simple either.  Rather than my doing the work that the internals Pixi is already doing it seems to make more sense to have it just return more information.

Does anyone see any problem with that?

**Comment by ivanpopelyshev** [comment]
Agree.

Text is one of critical components, we need more enchantments! I'm gonna make multiple textShadow, just one "dropShadow" is not enough.

**Comment by darkfrog26** [comment]
The only problem with this is that looking at the Canvas API I'm not sure how we'd get that information.

**Comment by themoonrat** [comment]
I think it'd have to work similar to how the text trimming works; ie. draw to a canvas and analyse the pixels.

**Comment by darkfrog26** [comment]
@themoonrat there's got to be a better way to do it than that....if we just had the ability to parse kerning pairs then we could do it....also, we determining kerning pairs dynamically by measuring each character and then measure the two characters together and accounting for character spacing and then caching the kerning pairs.  It would be far less efficient than just accessing the information, but I bet it would be more reliable and probably faster than analyzing pixels.

**Comment by ivanpopelyshev** [comment]
@darkfrog26 @themoonrat do the pixels. Make everything that way use can ask for caching before he starts the app.

**Comment by darkfrog26** [comment]
@ivanpopelyshev can you re-state that?

**Comment by darkfrog26** [comment]
What about incorporating something like https://opentype.js.org/ ?

**Comment by darkfrog26** [comment]
That would give us complete control and flexibility for each character drawn and we could do so much more like drawing on paths, introducing custom letter spacing, etc.

**Comment by ivanpopelyshev** [comment]
@darkfrog26 it will be nice as a plugin. Official plugin! Like pixi-spine or pixi-sound :)
