### ISSUE TITLE
NineSliceScaling issue with different borders

### ISSUE THREAD

**Issue by Tigerwulf** [pixijs/pixi.js#3987]
Hey,

i build a fiddle example to test around, what kind of results are possible with the new 4.5.1 nineSlice Version.

In the 4.4.4 version it looks better, but not perfect.

Version 4.4.4: http://jsfiddle.net/sD8Tt/347/
Version 4.5.1: http://jsfiddle.net/sD8Tt/348/

I have add some var bools to switch the behaviors, the comments explain what happens with each bool.

In that fiddle examples there is a graphic, sprite with the generated texture from that graphic object and a nineSlicedSprite with the texture.

Over the sprite i painted the visual lines, that represent the borders of the nineSliced plane. If you change the bool "differentBorderSizes" you will see an other result. The corner of the nineSlicedPlane are scaled, not much, but different behavior as in version 4.4.4.

Another thing is, that the graphic object have not the same symmetric. The GenerateTexture with the graphic data looks good.

Hope it helps to track them.

**Comment by bigtimebuddy** [comment]
Fixed with #3991 http://jsfiddle.net/sD8Tt/350/
