### ISSUE TITLE
PIXI.extras.TilingSprite#destroy does not pass options to super

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#3994]
PIXI.extras.TilingSprite extends PIXI.Sprite

is it correct that no options are passed to super in destroy method?

**Comment by ivanpopelyshev** [comment]
no, its not. Make a PR?

**Comment by ivanpopelyshev** [comment]
Never mind, here it is :)

**Comment by lucap86** [comment]
thanks i was forking repo :)

**Comment by ivanpopelyshev** [comment]
@lucap86 It'll be handy when you find another small critical bug

**Comment by lucap86** [comment]
seems the same with PIXI.extras. AnimatedSprite

**Comment by ivanpopelyshev** [comment]
adjusted PR.

**Comment by bigtimebuddy** [comment]
Merged. Thanks @lucap86 for finding this.
