### ISSUE TITLE
Pixi.js modules webpack and CustomEase plugin

### ISSUE THREAD

**Issue by williammanco** [pixijs/pixi.js#3996]
Hi everybody, i'm using pixi.js with webpack v2, i pack all the pixi package with a general import (so i'll open another issue for using pixi to modules)

```js 
Import * as PIXI from 'pixi.js'
```

For the pixi libraries outside the general package use a require such as this example

```js 
require ('./assets/js/Pixi-sound.min.js')
```

**Everything works great but...**

...when I use the CustomEase plugin, there is no way to run it by using require. Like this:

Show this error:
**_CustomEase.min.js:12 Uncaught Error: Cannot find module "TweenLite"_**
```js 
require('./assets/js/CustomEase.min.js')
```

The solution might be to use **import-loaders** and **export-loaders** but with various tests I did not come to the solution

Do you have a solution?

Thanks
W

**Comment by bigtimebuddy** [comment]
Related? https://github.com/greensock/GreenSock-JS/issues/193

This seems unrelated to Pixi.js and is an issue with CustomEase.

**Comment by williammanco** [comment]
Oh sure, it's about GreenSock, sorry!

It's time to take a break
Thanks @bigtimebuddy and and again excuse me

**Comment by bigtimebuddy** [comment]
No worries. If for some reason Pixi _is_ the culprit here (which seems a little unlikely), please feel free to re-open. Thanks for using Pixi.
