### ISSUE TITLE
Tinting an AnimatedSprite displays errors on a canvas renderer

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#3997]
https://pixijs.github.io/examples/?v=dev#/basics/spritesheet.js
Change top line to
```
var app = new PIXI.Application({ forceCanvas: true } );
```
And add
```
anim.tint = 0xFF0000;
```
after the play call

I know there was a fix for static sprites https://github.com/pixijs/pixi.js/pull/3985 which doesn't fix this scenario I'm afraid

**Comment by brenwell** [comment]
+1

Here is an example https://jsfiddle.net/brenwell/62qub9vn/2/

**Comment by brenwell** [comment]
this issue occurred with 4.5.0. Version 4.4.4 was working.

**Comment by brenwell** [comment]
I managed to fix the issue for myself by modifying line 129 of https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/canvas/CanvasSpriteRenderer.js 

```js
if (sprite.cachedTint !== sprite.tint || sprite.tintedTexture.tintId !== sprite._texture._updateID || sprite.constructor.name !== 'AnimatedSprite')
```
I doubt this is ideal, but it shows where the issue is with the Tint Caching.

> Sidenote: While I was testing the consequences I noticed that the TilingSprite class will not tint at all on pointerover with Canvas

**Comment by ivanpopelyshev** [comment]
Lets test this thing: https://pixijs.download/dev-canvas-animated-tint/pixi.js , please test both cases.

**Comment by brenwell** [comment]
Ok one of the conclusions I have made is false. 4.4.4 doesn't nessecarily for because `forceCanvas: true` is ignored and WebGL prevails.

Will check what you sent

**Comment by brenwell** [comment]
Doesn't appear to work https://jsfiddle.net/brenwell/62qub9vn/4/

**Comment by brenwell** [comment]
**AnimatedSprite caching tint** - https://jsfiddle.net/brenwell/62qub9vn/4/
**TilingSprite not tinting** - https://jsfiddle.net/brenwell/yo2Lz9dc/1/

**Comment by brenwell** [comment]
Both appear to be working now, did you update the build files??

**Comment by ivanpopelyshev** [comment]
Fixed both. Look at them again ;)

**Comment by ivanpopelyshev** [comment]
Yeah, files are updated automatically as I push commits to the PR.

**Comment by brenwell** [comment]
Ok great, I checkout out that branch and linked it to my game and things seem to work as expected. Cheers!!
