### ISSUE TITLE
Header animation at pixijs.com

### ISSUE THREAD

**Issue by sntiagomoreno** [pixijs/pixi.js#4001]
Are there any examples or tutorials on how to create the pixijs.com header animation? Thanks

**Comment by englercj** [comment]
It is an iframe of http://pixijs.teamgbaws.net/header/. Even though the source is minified, it should still give you all the juicy implementation details.

**Comment by Yvanovitch** [comment]
Any chance to see the unminified code ? My eyes aren't minified yet...
