### ISSUE TITLE
gl.SCISSOR_TEST enabled by default?

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4004]
is it correct that gl.SCISSOR_TEST is enabled by default?

```
 app.renderer.gl.getParameter(app.renderer.gl.SCISSOR_TEST);
``` 

furthermore i've noticed that masking a container with a rect graphic cause SCISSOR_TEST to be disabled.

Try to console
```
 app.renderer.gl.getParameter(app.renderer.gl.SCISSOR_TEST);

```
in eg1 and eg2

furthermore i think that in ```MaskManager#popMask```  method ```popScissorMask``` call parameters are useless.

[eg.zip](https://github.com/pixijs/pixi.js/files/983654/eg.zip)

**Comment by lucap86** [comment]
I think that something wrong with https://github.com/pixijs/pixi.js/commit/5b52befc#diff-44f18d077850050582b57150f34f2a4e

In ```setFrame```        

```
this.sourceFrame = sourceFrame || this.sourceFrame || destinationFrame;
```

should be 
```
this.sourceFrame = sourceFrame || this.sourceFrame || this.destinationFrame;
```

furthermore in ```activate``` method comparison between ```this.destinarionFrame``` and ``this.sourceFrame``` should be done by x,y,top,bottom,with,height and not by ===

what do you thing about that?

**Comment by englercj** [comment]
Merged! Thanks for the contribution!
