### ISSUE TITLE
PIXI transparent background renderer doesn't work any idea how to fix this?

### ISSUE THREAD

**Issue by msgopinath** [pixijs/pixi.js#4006]

**Comment by themoonrat** [comment]
Could we have a fiddle or demo somewhere please of your issue and what you are seeing? Thanks!

**Comment by qinxgee** [comment]
Hi! 

I don't know what OP sees, but their description matches a problem that I'm currently facing. I'm trying to render a texture from a container that has two sprites overlaying. The bottom one is a PNG with transparency, the top one is a JPG with textures against a black background. This top sprite has blendMode set to PIXI.BLEND_MODES_ADD. The resulting container is the picture from the JPG, but with transparency where the underlying PNG is transparent. When I try to render the container to a texture, the picture goes back to being opaque:

```javascript
var renderer = PIXI.autoDetectRenderer(1280, 720, { antialias: false, resolution: 1, transparent: true});
    container = new PIXI.Container(),
    alphaSprite = new PIXI.Sprite.fromImage(urlAlpha),
    textureSprite = new PIXI.Sprite.fromImage(url),
    renderTexture;

textureSprite.blendMode = PIXI.BLEND_MODES.ADD;
container.addChild(alphaSprite);
container.addChild(textureSprite);

renderTexture = PIXI.RenderTexture.create(container.width, container.height);
renderer.render(container, renderTexture);

callback(renderTexture.baseTexture);
```

urlAlpha is the location of the PNG, url is the location of the JPG

(If this is not related to the issue that OP has, I apologise for hijacking their thread)

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
