### ISSUE TITLE
crossOrigin parameter for Video

### ISSUE THREAD

**Issue by dakom** [pixijs/pixi.js#4007]
BaseTexture.fromImage allows supplying a crossOrigin setting or defaulting to anonymous via determineCrossOrigin.

VideoBaseTexture (or Texture.fromVideo, etc.) needs a similar mechanism. Otherwise Safari (and possibly others) will block loading the video texture from a remote source.

This is not necessarily a showstopper for current production code, considering that a Video Element can be created first with the proper crossOrigin policy and then supplied, like so:

```
var videoElement = document.createElement('video') as HTMLVideoElement;
videoElement.crossOrigin = "anonymous";
videoElement.autoplay = true;
videoElement.src = "http://cdn.example.com/video.mp4";

var texture: PIXI.Texture = PIXI.Texture.fromVideo(videoElement);
var videoSprite = new PIXI.Sprite(texture);
SomeContainer.addChild(videoSprite);
```

**Comment by themoonrat** [comment]
@dakom Could you give https://pixijs.download/video-base-texture-cross-origin/pixi.js a go please and let me know if it works without your workaround. I've just done a straight port of the BaseTexture.fromImage crossorigin stuff to VideoBaseTexture.fromUrl and have done zero testing on it... so would appreciate your checking before I submit a PR! Cheers

**Comment by AliasT** [comment]
it works! @dakom thanks

**Comment by dakom** [comment]
@themoonrat whoa, sorry I totally missed this notification... do you still need this to be tested?

**Comment by themoonrat** [comment]
The PR is out of date; I'll update it to match the most recent cross origin code for Images and then give you a buzz if that's ok?

**Comment by dakom** [comment]
Cool - my test project for that is long gone but if you need help I'm happy to lend a hand if I can, somehow... problem is I'm not entirely sure how I hit that failure case to begin with, might get false positives now :\
