### ISSUE TITLE
Incorrect link to website in README

### ISSUE THREAD

**Issue by Bielijbog** [pixijs/pixi.js#4009]
Last sentence of second paragraph of README.md contains a dead link:

`You can also check back on [our site](http://www.goodboydigital.com/blog) as any breakthroughs will be posted up there too!
`
</br>
Should this be linking to [Pixi.js](http://www.pixijs.com) or [GoodBoyDigital](http://www.goodboydigital.com)?

(Link to blog in the [Pixi.js](www.pixijs.com) drop down on the website is also dead.)

**Comment by drkibitz** [comment]
I saw this too and wondered where to file the bug. Might want consider what many other projects do, which is to have a public repo specific to site bugs, even if the site source is private, and a link on the site to file bugs on that repo.

**Comment by bigtimebuddy** [comment]
I chatted briefly with @GoodBoyDigital about this and he said it was a known issue with their blog/site. Not sure what the resolution was, but he's aware. He's on holiday this week so maybe when he gets back someone can check it out. Otherwise, we can remove this bit on the Readme.

**Comment by staff0rd** [comment]
Fixed
