### ISSUE TITLE
Texture.fromCanvas not preserving alpha

### ISSUE THREAD

**Issue by ollyskinner** [pixijs/pixi.js#4010]
I'm probably missing something here, but...

Animated scene built in CreateJS - rendering off-screen to canvas which I then turn into a bitmap using Texture.fromCanvas() - this works except what had been transparent in the source canvas is now black.

`var canvas, stage, hiddenStage, exportRoot;
function init() {

	exportRoot = new lib.Figure_WalkTest_2();

	var renderer = PIXI.autoDetectRenderer(200,400, {view:document.getElementById("canvas")}, {transparent:false});
	
	//Create the off-screen CJS canvas
	canvas = document.createElement("canvas");
	canvas.setAttribute("width",200);
	canvas.setAttribute("height",400);

	hiddenStage = new createjs.Stage(canvas);
	hiddenStage.addChild(exportRoot);
	hiddenStage.update();

	// Create the visible Pixi Canvas and add a Sprite of the off-screen rendered canvas
	stage = new PIXI.Container();
	var sprite = new PIXI.Sprite(PIXI.Texture.fromCanvas(canvas));
	stage.addChild(sprite);

	// Currently using the CJS timeline controls
	createjs.Ticker.setFPS(lib.properties.fps);
	createjs.Ticker.addEventListener("tick", eachFrame);

	function eachFrame() {
		// Update the off-screen canvas, then make a bitmap from it, then draw to the PIXI renderer.
		hiddenStage.update();
		sprite.texture.update();
		renderer.render(stage);

	}

}`

Pixi is being used to perform subsequent WebGL operations on the animation. If I draw the 'hiddenCanvas' to the screen it has the correct transparency.

Is this expected behaviour? And if so, is there a way to restore transparency (without resorting to filters, which is the only way I can think of so far)?

**Comment by mnori** [comment]
I also encountered this problem, but this time just using Container and Graphics, no sprites.

Whittled it down to a little codepen demonstrating the issue:

https://codepen.io/wildtype/pen/NjeRMN

**Comment by ollyskinner** [comment]
Sorry, I should have followed up with my resolution rather than just closing the thread. I had the wrong syntax in the renderer properties object, possibly using v2 or some older syntax - looking briefly at your pen it might be the same issue:

`renderer = PIXI.autoDetectRenderer(200, 200, {
			"antialias": true,
			"transparent": true,
			"clearBeforeRender": false,
			"preserveDrawingBuffer": true
		});`

...should be more like:

`renderer = PIXI.autoDetectRenderer(200, 200, {
			antialias: true,
			transparent: true,
			clearBeforeRender: false,
			preserveDrawingBuffer: true
		});`

ie, without the quotes.

I don't think the docs are very clear on this, thus a lot of support is from forum threads relating to older versions of the library!

**Comment by mnori** [comment]
Have followed your suggestion and updated the pen, it didn't make a difference with this bug though.

**Comment by mnori** [comment]
I tested this out using both the Canvas and the WebGL renderers, interestingly both of them produce the same result.

**Comment by mnori** [comment]
Using PIXI.CanvasRenderer instead of WebGL gives a different result:

https://codepen.io/anon/pen/rwBYMM

The alpha is correct in this case, but now the cropping has broken.
