### ISSUE TITLE
Mouse events triggering outside/inside sprite in scaled container

### ISSUE THREAD

**Issue by balance80** [pixijs/pixi.js#4012]
I'm trying to create live previews of sections from a canvas onto a secondary canvas. The source canvas has a container (world) that might be scaled up or down. The problem is that when the world is scaled, and the rendering to the secondary canvas is running, continuos mouseover and mouseout events are triggered. This happens while moving the pointer outside of the sprite if the scaling of the world-container is < 1 and inside if the scaling is > 1. 

Moving the mouse in and out of the sprite works as normal:
https://media.giphy.com/media/AiwU1sNvkyFIA/giphy.gif

Here is a fiddle containing a full example showing the problem. Try moving the mouse to the right of the sprite, and lots of mouseover and mouseout events are triggered:
https://jsfiddle.net/omgy2aqj/11/

Browser: Chrome 58.0

Is this a bug, or am I just doing something completely wrong here?

**Comment by themoonrat** [comment]
Having a quick look now.
First thing, even though the sprite seems to sit in the webgl renderer perfectly, with space to it's right, it's width is being reported as 257. That's why the interaction manager reports it as a hit when moving your mouse over that area... it appears blank, but the sprite says it's wide enough to cover that area

**Comment by themoonrat** [comment]
If I comment out lines
previewTexture = createTexture(1);
renderPreviewTexture(previewTexture);
it works. Something about using a second renderer is the issue here

**Comment by themoonrat** [comment]
Something is happening that resets it's world transform. 
When it goes 'wrong' with the above lines in - the sprites worldTransform is as if it's of scale 1.
When it's not going 'wrong', with the above lines commented out, the sprites worldTransform shows it correctly at being 0.5 scale.

Something about your passing a container of a one renderer to a different renderer to process feels wrong, and could be causing these issues. Can't the primary renderer do all of the work to generate a texture which the second can just use?

(added note, there's no need to keep creating destroying and creating sprites all of the time, just set a new sprite.texture)

**Comment by balance80** [comment]
Yeah, I might be misunderstanding how I should be doing this. Do you have an example for what you mean by generating a texture on the primary renderer that the second can use?

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
