### ISSUE TITLE
SVG and power-of-two mipmap

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4013]
Following discussion in russian html5gamedev channel in telegram.

@busyrev has a great idea:

When we make texture from SVG, add an option to make power-of-two texture with mip levels made from the same SVG source.

**Comment by Busyrev** [comment]
May be it will be better to use gl.TEXTURE_MIN_FILTER with gl.LINEAR_MIPMAP_NEAREST value, because mip levels generated separatly from vector.
