### ISSUE TITLE
PIXI.Graphics border padding applied incorrectly?

### ISSUE THREAD

**Issue by namark** [pixijs/pixi.js#4019]
https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/Graphics.js#L996
I might be misunderstanding this, but if that's maxX/Y shouldn't we just apply padding as is, instead of doubling it, as one would when dealing with width/height? As it stands applying any padding seems to throw my graphics off center.

Thanks!

**Comment by bigtimebuddy** [comment]
I believe you're right! This doesn't make sense. 

I put together this jsfiddle to repro the problem: https://jsfiddle.net/ed6zpLtj/

It should not be doubling the padding because maxX/Y are the position not the width. Added a PR for this.

**Comment by bigtimebuddy** [comment]
Merged fix to dev. Thanks for catching this.
