### ISSUE TITLE
Samsung Galaxy S8+ + Pixi = missing Items

### ISSUE THREAD

**Issue by DerivcoHK** [pixijs/pixi.js#4022]
Samsung Galaxy S8+ + Pixi = missing Items ( Screens, fonts, containers, masks, etc) 
WebGL related.

It seems there is some issue with the shaders gl.getProgramParameter , not sure. 

https://www.kindernauts.co.uk/#/activities
one of the example

**Comment by DerivcoHK** [comment]
updated: 
comparing S7 and S8+
the S8+ failed the webGL test of 
https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/angle-instanced-arrays.html?webglVersion=1&quiet=0

**Comment by AdrianDroid** [comment]
I appear to me that 
Both Version S8 (the Exynos and Snapdragons CPU )exhibit the same behavior

**Comment by ZebraRoy** [comment]
Are you using a older version of PIXI v4 ?
It seems like the issue of #3558
It should be fixed after added the "legacy" options of WebGLRenderer

**Comment by glalev** [comment]
I had a similar problem with a project on PIXI 4.1.1 and updating PIXI to the next version 4.2.1, which is actually a version without the  "legacy" options added, fixed the problem. It seems that the 4.1.1 is the last version that has issues with WebGL rendering on galaxy s8

**Comment by englercj** [comment]
Going to close this since it seems like the new `legacy` options should take care of this.
