### ISSUE TITLE
https://pixijs.github.io/bunny-mark/ "Pixi is unavailable"

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#4023]
On https://pixijs.github.io/bunny-mark/ when I click "v3.0.8" I get this:

![screenshot](https://cloud.githubusercontent.com/assets/80411/26049957/2cb57704-395d-11e7-9d20-4a2cf824002e.png)

Ditto for 3.0.9, 3.0.10.

**Comment by tobireif** [comment]
(And perhaps the version number boxes could get sorted into a better sequence)

**Comment by bigtimebuddy** [comment]
This is now fixed.
