### ISSUE TITLE
Method loadFramedSpriteSheet

### ISSUE THREAD

**Issue by dima74** [pixijs/pixi.js#4024]
There was PR for adding method `loadFramedSpriteSheet`: #311. But now I can't find this method. Can you please say, where is this method? Thank for PIXI!

**Comment by englercj** [comment]
That function no longer exists, it was in v1 of this lib but was later removed as we reworked the loader (a few times). I feel like that method is a bit too specific for inclusion in the core loader.

**Comment by dima74** [comment]
OK, thank you for answer :)
