### ISSUE TITLE
https://pixijs.github.io/bunny-mark/ , "Click to add more"

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#4025]
After the bunnymark is started at https://pixijs.github.io/bunny-mark/ ,
people might not know that they can click to add more bunnies,
so it would be great if there'd be some text eg "Click to add more".

**Comment by bigtimebuddy** [comment]
Could you please add this issue to https://github.com/pixijs/bunny-mark repo instead? Thank you. Will help us keep issues organized.

**Comment by tobireif** [comment]
https://github.com/pixijs/bunny-mark/issues/3
