### ISSUE TITLE
PIXI.BLEND_MODES.ERASE

### ISSUE THREAD

**Issue by dakom** [pixijs/pixi.js#4027]
Feature request for new blend mode to allow erasing pixels

@ivanpopelyshev gave some details at http://www.html5gamedevs.com/topic/30361-best-practices-approach-to-painting/?do=findComment&comment=174593

**Comment by ivanpopelyshev** [comment]
We need better blendModes, we have to add two more params, srcAlpha and destAlpha to https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js

Possible modes:

Non-premultiplied normal [gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA]

Erase (x,y,gl.ONE,gl.ZERO)
