### ISSUE TITLE
Feature request for React renderer

### ISSUE THREAD

**Issue by EloB** [pixijs/pixi.js#4028]
I really love Pixi for it's good performance and the fallback to context2d when it can't use webgl. I'm using almost React to everything at the moment. I can't live without declarative/functional programming but I would really want a solid renderer for Pixi for React. Then I would probably use Pixi a lot more 😄 

Right now there is one project with Pixi renderer for React (https://github.com/Izzimach/react-pixi). The problem is that is backed by one active developer (love the guy for trying) but the documentation is lacking and the task seems to big for one person. There is also some API issues with "pure" components. I would be super happy to see a bigger organisation that have the strength to build someone like this. Not just a renderer but all the documentation that is needed as well. 

Here are some examples of bad API decisions from mentioned project:
```js
<Text anchor={new PIXI.Point(0.5,0)} />
```
Should have implemented like below. Not create instances (only use primitive values as strings/numbers/booleans) when rendering. To be able to create "PureComponents".
```js
<Text anchorX{0.5} anchorY={0} />
```

Also missing out some simple feature like `onDimensionChange` on native components that might change size if some prop is changed. If you trying to build a button component and the text change you probably have to update the rectangle etc if the dimension changes and you want to know how big is the text on initial render.
```js
// My proposal
const Button = ({ padding, width, height, value, onDimensionChange, ...props }) => (
  <Container {...props}>
    <Rectangle width={width + padding} height={height + padding} />
    <Text x={padding / 2} y={padding / 2} value={value} onDimensionChange={onDimensionChange} />
  </Container>
);
```

Would be awesome to not use `<Text />` instead use lowercased `<text />` so the native components is built into the React renderer. So you don't have to `import { Text } from 'react-pixi-renderer';` etc.
```js
const test1 = <Text />;
// JSX compiled
React.createElement(Text, null);

const test2 = <text />;
// JSX compiled
React.createElement("text", null);
```

If this could be combined somehow with `react-dom`. It will blow my mind!

**EDIT**: Maybe it's better to import components so it's can be combined with `react-dom`.

**Comment by EloB** [comment]
More resources about the subject. To write custom renderers.
https://github.com/iamdustan/tiny-react-renderer

**Comment by englercj** [comment]
This is not something that we are likely to support in the core, I don't think we can afford to spend time officially supporting this and still maintain the feature set we want to give for everyone.
