### ISSUE TITLE
WebGL bug in iOS

### ISSUE THREAD

**Issue by manubb** [pixijs/pixi.js#4032]
I am using Pixi.js to draw geometries over Leaflet maps. The behavior of this [example](https://manubb.github.io/Leaflet.PixiOverlay/webgl.html) is fine in most tested situations (Chrome, Firefox, Opera on Fedora 25 and same browsers + Safari on MacOS 10.11.6) but not on iOS Safari (iPad 10.3.2 and iPhone 4S 9.3.5).
On iOS Safari, flickering occurs with high probability after moving or zooming: geometries are not displayed at the right place for a very short amount of time. This problem is not present when forcing a Canvas renderer as in this [example](https://manubb.github.io/Leaflet.PixiOverlay/canvas.html).

If you think this is Pixi.js related, i can provide additional informations (and maybe a simpler test case).
By the way, thanks for your great lib.

**Comment by ivanpopelyshev** [comment]
Precision.

That's bad: 

```js
graphics.moveTo(10000, 10000);
graphics.lineTo(10010, 10000);
graphics.lineTo(10010, 10010);
graphics.lineTo(10000, 10010);
graphics.lineTo(10000, 10000);
```

That's good:

```js
graphics.position.set(10000, 10000);

graphics.moveTo(0,0);
graphics.lineTo(10,0);
graphics.lineTo(10,10);
graphics.lineTo(0,10);
graphics.lineTo(0,0);
```

Find some point (center, left-top, whatever) somewhere in the polygon, and specify points relative to that point. Positions are calculated on JS side, and numbers can be big, while vertices are on shader-side and it has only 16 mantissa bits on iphones, not 23 :(

**Comment by manubb** [comment]
Thanks for your answer. I tried your suggestion on a simple test with a single polygon and the problem is still there. Here is a more precise description of the problem. 
* During a drag, the geometries are not rerendered, it is the canvas container that is translated.
* At the end of a drag, the geometries are rendered once (after applying a translation on the Pixi container and a scaling if zoom is not the initial zoom). During this rendering, the geometries appear for some ms at a wrong position (not always but often) but finally are displayed at their correct places.

Moreover, this happens at initial zoom where scaling factor is 1 and points coordinates are around 10^4.

**Comment by ivanpopelyshev** [comment]
> During a drag, the geometries are not rerendered, it is the canvas container that is translated.

Who handles the drag, leaflet or pixi?

**Comment by ivanpopelyshev** [comment]
Its unfortunate, that i dont have mobile devices to test this on :( I think I understand whats going on. We have to make sure that canvas is moved at the same time its re-rendered, right?

**Comment by manubb** [comment]
Between dragstart and dragend, a CSS transform is applied on a parent of the `<canvas>` element: no rerendering and everything seems fine. On dragend, the position of the `<canvas>` element is reset and geometries are rerendered. The problem occurs only during this processing: geometries are briefly shown at their previous computed positions. (As far as i know, this only concerns iOS with WebGL renderer.) 

Tomorrow, i'll try to make a video showing the problem as it is not easy to explain it ;-)

**Comment by ivanpopelyshev** [comment]
ok, so we have to do something clever. Like, call extra renderer.render( ) before we move canvas?

**Comment by manubb** [comment]
I made a small video that you can watch [here](https://www.dropbox.com/s/eaw818e1zpj1gpo/leaflet-pixi.mp4?dl=0).

**Comment by manubb** [comment]
It was challenging but finally found a workaround for this. IMHO, iOS WebGL is a mess. Thank you for your support.

**Comment by j-funk** [comment]
@manubb can you post your workaround?

**Comment by manubb** [comment]
Here are the main lines of the workaround: i use a second `<canvas>` with 2d context.
Before a rendering, i copy the WebGL content into the 2d `<canvas>` (with drawImage). I hide the WebGL `<canvas>`  and show the 2d `<canvas>`. After the rendering, i call `webGLRenderer.gl.finish();` then show the WebGL `<canvas>` and hide the 2d `<canvas`>.

**Comment by ivanpopelyshev** [comment]
you can draw your stage into RenderTexture, and render it on canvas only when you moved it.

**Comment by manubb** [comment]
@ivanpopelyshev Can you please give more details on your suggestion? (I'm not a Pixi master ;-))
