### ISSUE TITLE
Unnecessary restriction in Text.js?

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#4034]
```
if (this.resolution !== renderer.resolution)
 { 
   this.resolution = renderer.resolution;
   ...
```
I wonder if those lines above have any deeper meaning, than protecting devs against crappy text texture quality? If not, I would like them to be removed, because I have a user-case where it actually get's handy to be able to-do this thing.
```
var richText = new PIXI.Text('Rich text with a lot of options and across multiple lines', style);
richText.resolution = 2;
....
richText.scale.x = 2;
richText.scale.y = 2;
richText.updateText(true);
```
So... richText is scaled exactly 2 times, but the quality is still great.

**Comment by ivanpopelyshev** [comment]
Yes, I agree. How did it end up there?  May be we need a flag for that autodetect?

**Comment by bigtimebuddy** [comment]
Looks like these lines originated here #2799

**Comment by trsh** [comment]
> Removed text resolution as a parameter for text. This is now set by the renderer. So if renderer has a resolution of 2, so will the text. Much easier!

Would be nice, if it's left as an option :)

**Comment by trsh** [comment]
Something like

```
if(this.resolution === null) {
    this.resolution = renderer.resolution;
    ...
}
```

**Comment by bigtimebuddy** [comment]
@trsh, exactly! I believe @GoodBoyDigital is going to work on a PR for this. Lots of other objects have internal resolutions that we'd like to standardize around in a similar way. Right now, there's a mix of defaulting to `renderer.resolution` or `PIXI.settings.RESOLUTION`. We'd like to make this consistent across the board.

**Comment by themoonrat** [comment]
Closing down this in favour of https://github.com/pixijs/pixi.js/issues/4915
