### ISSUE TITLE
Using sprites rendered with Pixi as texture

### ISSUE THREAD

**Issue by xormak** [pixijs/pixi.js#4036]
Hello,

i recently started to use PixiJS to create a drawing app.
Because i plan to create a very complex brush engine i wanted to ask if my planned approach would actually be better practice and if so, how to do it because i am not able so far to create it on my own.

TL;DR the engine depends on drawing a lot of sprites per second (thousands to be precise) and so far it is holding up extremely well. no performance loss even at 100k+ sprites it stays consistent. that changes however when i apply filters to the strokes (applying it to every sprite was a mess) it quickly turns into a heavy loss in performance.

Now, the approach i thought about was the following:
- create sprite1 with brush-shape
- apply possible scaling, rotations, filters etc to that shape
- turning the modified sprite into a texture
- on pointerDown create new sprite2 that uses the old sprite1 as texture 
- as pointer moves/drags draw the new sprite2

could/would that work and if so would it be a possible to increase performance that way since the task will be to create thousand of blurred/textured and otherwise modified sprites in quick succession?

regards,

Xormak

PS: Hello everyone, first post ^^

**Comment by LegitSoulja** [comment]
Basically, looks to be you ran into memory issues when using filters. You shouldn't recreate those, but instead store them to be used as a texture for another object.

The way of generating the texture for the sprite is a bright idea, and would in fact work. 

And there's no way of increasing performance, as long as you stay efficient, and think smart. Your creating 60+ sprites per second. Should it be 60fps? 

Do some comparisons and tell me what you see.

**Comment by xormak** [comment]
Heya, the problem is am not sure yet how to actually approach my idea code-wise. currently i am only familiar with the tutorial-way of generating sprites and for the start that was enough, not anymore tho. if possible i would really appreciate help in that regard. 

also yes, 60 FPS is the target. 

I have also tried to only apply filters to the "strokes" in my drawing-program but it's still not quite the effectiveness i want to achieve.

**Comment by englercj** [comment]
Apply a filter to a sprite breaks its batch. So it is possible you are batching them all heavily, then breaking the batches when using filters.

**Comment by xormak** [comment]
Okay, late reply BUT in the end everything worked out.
Primitives are being rendered into texture on mousedown and sprites are drawn on mousedrag with requestAnimFrame renderloop for the canvas. application runs smoothly up to the 300.000-500.000 sprite counts. still working on performance but so far it works.

Praise PIXIjs an amazing library if used correctly :D
