### ISSUE TITLE
MeshRenderer#render: Question

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4037]
i've noticed that for uvBuffer upload
```
 if (mesh.dirty !== glData.dirty) {
      glData.dirty = mesh.dirty;
      glData.uvBuffer.upload(mesh.uvs);
}
```

and indexBuffer upload

```
if (mesh.indexDirty !== glData.indexDirty) {
     glData.indexDirty = mesh.indexDirty;
     glData.indexBuffer.upload(mesh.indices);
}
```

a dirty check is defined

Why not for vertexBuffer upload?

```
 glData.vertexBuffer.upload(mesh.vertices);
```

**Comment by ivanpopelyshev** [comment]
In this version, vertex buffer is uploaded every time. We cant change it because of some dependent libraries wont work after it. However, its different in v5 ("next") branch

**Comment by lucap86** [comment]
ok thanks

**Comment by lucap86** [comment]
@ivanpopelyshev @englercj 
this is my problem:
(with chrome 58.0.3029.110 (64-bit) on iMac (10.11.6) i haven't tried jet on other browsers)

Scenario: 
a 60fps app with two or more meshes; 

I leave chrome opened for a long time (12+h) with the app idle and mac with screen locked, when i come back and i unlock the mac screen, fps drops to 30/35fps (it don't care if i reload the page when this state is reached).
But, if i make meshes ```visible = false``` or i ```cacheAsBitmap = true``` fps came back to 60fps.

If i open https://pixijs.github.io/examples/#/basics/textured-mesh.js and add some more mesh i got 60fps.

In profiler I've seen that the long frames are caused gpu.

I've identified this call as possible bottleneck:
https://github.com/pixijs/pixi.js/blob/dev/src/mesh/webgl/MeshRenderer.js#L105
and more in depth by:
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/WebGLRenderer.js#L571
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/WebGLRenderer.js#L572

Furthermore if i close/reopen chrome app come back to 60fps.
Any idea?
