### ISSUE TITLE
Masking not works correctly in Android Phone Oppo R9S 

### ISSUE THREAD

**Issue by darting** [pixijs/pixi.js#4038]
### The following browsers not working:
- Chrome 58.0.3029.83
- CM Browser 5.21.00
- UC Mini Browser V10.9.0.946 Android pf139(en-us) inapprelease (Build17031015)
- Dolphin V11.5.19

I used this link for testing:
http://pixijs.github.io/examples/#/demos/masking.js

![screenshot_2017-05-18-18-37-42-35](https://cloud.githubusercontent.com/assets/4946661/26199261/f74fcc44-3bfb-11e7-89e4-827d260c8b27.png)

**Comment by darting** [comment]
Hi there, any ideas for this? thanks

**Comment by englercj** [comment]
I too see this issue using Chrome on my android device, and it looks like it has been broken for a long time (including in v3). I have no looked into the cause at all.

**Comment by darting** [comment]
the bug is come from chrome?

**Comment by darting** [comment]
Seems like masking issue has been solved with updated version of above-mentioned devices.

**Comment by aslanov-a** [comment]
Is there another solution to this problem? No browser update. Thanks!

**Comment by themoonrat** [comment]
In that example, anti aliasing is turned on. Try turning it off.
You may always want to try 
legacy: true
in the settings object for creating the renderer

**Comment by ivanpopelyshev** [comment]
Use Sprite masking instead of Graphics?

**Comment by aslanov-a** [comment]
legacy: true - did not help

I simplified the scene as much as possible, I add only one picture. It's not about masks, I guess.*
http://take.ms/OmO45

* Я максимально упростил сцену, добавляю только одну картинку. Думаю, что дело не в масках

**Comment by aslanov-a** [comment]
Android 7
Chrome 58.0.3029.83

**Comment by ivanpopelyshev** [comment]
Now i just dont understand which elements do you have on the stage, what do you want to see, and what do you actually see. Please make a fiddle or share it some way.

**Comment by ivanpopelyshev** [comment]
What's the resolution in that case?

**Comment by aslanov-a** [comment]
resolution = 3.5
If you remove resolution, then everything is fine, but the image is blurred. Excuse me, I didn't think to try without this option.
Blur can be fixed?
Thanks

**Comment by ivanpopelyshev** [comment]
Ok, that's non-standart fractional resolution, I'm trying to think what does it affect...

**Comment by ivanpopelyshev** [comment]
Ok, next idea: set the size to 350x350 , resolution:1, no autoResize, but specify canvas css 100,100. That'll be  red square with green square of exactly 100x100 pixels at left-top corner.

**Comment by aslanov-a** [comment]
https://jsfiddle.net/fLhycqb4/5/
http://take.ms/xnz0y

**Comment by ivanpopelyshev** [comment]
and now I really dont know whats going on. Try to change this param, its auto by default, but you can try to fix one of options:

```css
canvas {
image-rendering: auto;
image-rendering: crisp-edges;
image-rendering: pixelated;
}
```

**Comment by aslanov-a** [comment]
Has helped antialias: false. Thanks!
