### ISSUE TITLE
Displacement Map demo corruption

### ISSUE THREAD

**Issue by tonywarriner** [pixijs/pixi.js#4039]
This demo shows a corrupt region to the left of the moveable circle. Not a good advert for pixi!

http://pixijs.github.io/examples/#/filters/displacement-map.js

**Comment by ivanpopelyshev** [comment]
Screenshot please?

**Comment by tonywarriner** [comment]
![pixi-fault](https://cloud.githubusercontent.com/assets/3610512/26263580/4c2344fa-3cd1-11e7-8d4b-44cf55bbc37b.jpg)

**Comment by ivanpopelyshev** [comment]
I suppose everyone was thinking that its ok. Now I see thatsactually problem with displace texture 👍 

We all thought that its not a bug, its a feature!

**Comment by ivanpopelyshev** [comment]
Ok, fixed, but you have to clear cache, i have modified the displacement texture :)

**Comment by tonywarriner** [comment]
Cool 👍

**Comment by chrisjj** [comment]
Fix confirmed. http://i.imgur.com/llEkp39.png
