### ISSUE TITLE
So... What is Pixi Flex?

### ISSUE THREAD

**Issue by thomas-dm** [pixijs/pixi.js#4041]
Hello,

I've just been browsing the [DDD Conference](http://workshop.ddd.it/workshop/easy-webgl-with-pixijs) website and saw that @GoodBoyDigital will be giving an interesting workshop focused on **Pixi Flex**. But a quick search for “Pixi Flex” turned up absolutely nothing, except for the page of said workshop.

Is Pixi Flex a brand new exciting thing that's yet to be announced, or is it an alias for something I'm not aware of?

Thanks!

**Comment by englercj** [comment]
I believe Pixi Flex refers to the new geometry-based rendering system that @GoodBoyDigital has been working on for the v5 branch. WE should have more to share as we actually get the branch going :)
