### ISSUE TITLE
Possible bug in PIXI.CanvasRenderer.clear()

### ISSUE THREAD

**Issue by namark** [pixijs/pixi.js#4045]
This might be an expected behavior, but calling clear() before render() causes a null exception, since this.context is not yet initialized at that point. 

So this blows up:
```
const renderer = new PIXI.CanvasRenderer();
renderer.clear();
```

While this works just fine:
```
const renderer = new PIXI.CanvasRenderer();
renderer.render(new PIXI.Container());
renderer.clear();
```

Perhaps it should just clear the rootContext in that case, or maybe do nothing?

**Comment by finscn** [comment]
I think it's a bug.
Maybe the default value of `this.context` should be `this.rootContext`.
