### ISSUE TITLE
Sprite children being skewed when texture is fromCanvas()

### ISSUE THREAD

**Issue by cavemon** [pixijs/pixi.js#4054]
I'm not sure if this is a bug or if I'm doing something incorrectly, but it seems when I have a sprite thats created from a canvas texture, it's children are being skewed.

Originally my canvas was holding a gradient fill, but I've reduced it to a solid color to find that the canvas seems to be the issue.

This pen has the texture from a canvas - black circle is skewed.
https://codepen.io/westleymon/pen/KmJaEj

This pen has the texture as an image - black circle is not skewed.
https://codepen.io/westleymon/pen/qmgrxo

I appreciate the help and am really enjoying using this library!

**Comment by OSUblake** [comment]
Try adding a width and height to your canvas.
https://codepen.io/osublake/pen/oWOwgR?editors=0010

**Comment by ivanpopelyshev** [comment]
You forgot to set canvas width/height and its not square, at all.

```
square.width = 490;
square.height = 490;
```

That changes scale, and "scale.x !== scale.y"

**Comment by bigtimebuddy** [comment]
Sounds like there's a solution here, thanks @OSUblake. Closing.

**Comment by cavemon** [comment]
@OSUblake @ivanpopelyshev ahhhh interesting!  Thanks for the help!
