### ISSUE TITLE
An issue about commit https://github.com/pixijs/pixi.js/commit/dc9e26ec9c4924bff151459d40eea96558e49484

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4057]
There is no `_tintRgb` in `Mesh` Class & `ParticleContainer` Class.

But when call `core.utils.premultiplyRgba` , passed foo.`_tintRgb`.

Is it a bug ?

**Comment by ivanpopelyshev** [comment]
Yes. https://github.com/pixijs/pixi.js/pull/4058

**Comment by bigtimebuddy** [comment]
Fixed, thanks @finscn!
