### ISSUE TITLE
Looking a new maintainer for some plugins

### ISSUE THREAD

**Issue by Nazariglez** [pixijs/pixi.js#4061]
Hi,

I don't know if this is the better place to post this, sorry if it's not.
I have some pixi-plugins and none of time to work in them because my daily job and other projects, so, i'm looking for people who want to maintain them.

Also i'm thinking in move the plugins here, to the pixijs organization in github to be maintained by the pixi community. Is that possible?

Plugins: 
- https://github.com/Nazariglez/pixi-audio
- https://github.com/Nazariglez/pixi-tween
- https://github.com/Nazariglez/pixi-keyboard
- https://github.com/Nazariglez/pixi-timer

Regards!

**Comment by bigtimebuddy** [comment]
Hi @Nazariglez. First off, thank you for making these plugins for supporting the pixi community. Lots of hard work here, and we definitely appreciate the offer to have someone take over development. I'm sure we could find a nice future home. 

I could help you bring these over to pixijs organization on Github, if you'd like (also, would also need ownership on npm). Most likely **pixi-timer**, **pixi-tween** and **pixi-keyboard** are the likely candidates to migrate. Unfortunately, **pixi-audio** duplicates an existing effort we're working on right now called **pixi-sound** (which uses WebAudio + filters in a distinctly Pixi way with an Audio fallback), so we'd probably pass on that plugin.

The core team's main effort right now is to working on v5 which will have a better system for dealing with plugins. Unless someone is really eager to take up work on these, they would be a good candidate to test out 3rd party plugins for v5.

Thanks again.

**Comment by themoonrat** [comment]
I do have my own branch of pixi-tween @ https://github.com/themoonrat/pixi-tween - has a couple of bugfixes, a change to the manual update call (takes ms elapsed) and adds a startPromise syntax with no fallback with a caveat a lot perhaps wouldn't like.... (call playPromise twice, and the 2nd immediately resolves). There isn't a better PIXI based tween option around (I love how you can just draw shapes using PIXI and use that as a path) so I'd be happy to make sure it stayed working on 4.x at the very least

**Comment by Nazariglez** [comment]
Hi guys! I'm so sorry for not follow this thread before. Thanks you, i'm so glad to see how my work could be useful for you. I don't have any problem to transfer the repositories and the npm ownership to you, i think here it's the best place. So, just drop me an email at nazari.nz@gmail.com and we'll start the "transfer".

Thanks!
