### ISSUE TITLE
question about the src/core/display/Transform* modules

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#4062]
I'm curious about `Transform` vs `TransformStatic`. Is it safe to say that these 2 implementations are completely identical _except_ for the fact that `TransformStatic` caches computations?

**Comment by englercj** [comment]
Yup!

**Comment by mreinstein** [comment]
@englercj thanks for clarification! 

I think this could be simplified substantially: We could take the `TransformStatic` class, merge it with the base class `TransformBase`, and add a parameter in the constructor (e.g., `cache`) which would default to true (the current default behavior in pixi.) Then there would be one class named `Transform`, and that could be used everywhere. Would remove the bits of code duplication across the 3 classes, reduce the number of classes, and generally be more readable.

Thoughts? Open to a PR for this?

**Comment by mreinstein** [comment]
another possibility, if there is concern over changing the exposed transform APIs:  Move all of the `TransformStatic` code into `TransformBase`, and then the 2 extended classes could by very thin wrappers for the base class:

```javascript
export default class TransformStatic extends TransformBase {
    constructor() {
        super({ cache: true });
   }
}
```

```javascript
export default class Transform extends TransformBase {
    constructor() {
        super({ cache: false });
    }
}
```

This is not as clean as having 1 simple `Transform` class used everywhere, but it does preserve the existing API which obv has other benefits. :)

**Comment by englercj** [comment]
> I think this could be simplified substantially

Yup! I'm redoing this paradigm completely in v5.

**Comment by mreinstein** [comment]
Ah ok. I'll stay out of the way then. :) Thanks for the update!

**Comment by mreinstein** [comment]
@englercj took a stab at the more conservative of the 2 above approaches (not breaking the existing API) Thought maybe this would be useful in the meantime until you do a more drastic refactor.

**Comment by ivanpopelyshev** [comment]
Just a note for future me: pixi-spine will stop working after that, because it uses TransformBase a bit, so I'll have to update it. 

We need a way to stop automatic updates (by position,scale,...), suppose localTransform is changed from somewhere else. Is there an easy solution?

**Comment by mreinstein** [comment]
@englercj I'm happy to close #4134 if you would prefer to take another approach. I would take no offense. :) I just felt like seeing if I could throw this together semi-sanely. If it happens to be useful that's great, but I don't want to clog up a competing solution you might have in mind.
