### ISSUE TITLE
BitmapText with maxWidth set has repeated characters at the end of wrapped lines

### ISSUE THREAD

**Issue by abelzile** [pixijs/pixi.js#4063]
When I set the maxWidth property on a BitmapText object that results in wrapped text, I often see characters from the next line repeated at the end of the current line. The issue can be seen here:

https://jsfiddle.net/3ogqwg4b/8/

In the above example, the letter 'r' at the end of lines 3, 5 and 7 is the 'r' from the first word in lines 4, 6 and 8. If I add my own \n characters into the text in addition to setting maxWidth, the issue becomes even more pronounced with multiple characters being repeated on some lines. If I don't set maxWidth the issue does not occur. 

Pixi version: 4.5.1
Browsers: Firefox 52.1.0 on Debian, Chrome 58 on Android 6, Firefox 53 on Android 6

**Comment by themoonrat** [comment]
Thanks for the report and the fiddle!

I can see what is happening within BitmapText... we keep a record of the last entry for an empty space " " according to it's array index in the string passed in. Then, as we're adding text, if we go over the max width limit, we delete all the characters created after that space (including that space), reset the loop index, move to the next line then carrying on. But if there is multiple wrapping of text, you can see that there could now be a mismatch between what character is at index, say, 57 in the piece of text compared to what the 57th sprite character we're going to render is. 
It's this mismatch that causes the issue your seeing
