### ISSUE TITLE
pixi.text Styles generator ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4071]
hi !, is there a pixi.text generator for the style.?
Because I find it very long to try different configuration styles without preview.

similar as pixi-particles but for the text style ?

http://pixijs.github.io/pixi-particles-editor/
If that does not exist, it would be a good request.
thank a lot for help

is for a easy way to control and generate this , with slider or button!
```
{
        align: 'right',

        breakWords: false, //Break words between any two letters on wordWrap
        dropShadow: false,
        dropShadowAngle: Math.PI / 6,
        dropShadowBlur: 0,
        dropShadowColor: '#000000',
        dropShadowDistance: 5,
        fill: 'black',
        fillGradientType: TEXT_GRADIENT.LINEAR_VERTICAL,
        fontFamily: 'Arial',
        fontSize: 26,
        fontStyle: 'normal', //normal|italic|oblique|initial|inherit
        fontVariant: 'normal', //normal|small-caps|initial|inherit
        fontWeight: 'normal', //normal|bold|bolder|lighter|number|initial|inherit|900|600|400
        letterSpacing: 0,
        lineHeight: 0,
        lineJoin: 'miter', //"bevel|round|miter"
        miterLimit: 10,
        padding: 0,
        stroke: 'black',
        strokeThickness: 0,
        textBaseline: 'alphabetic', //"alphabetic|top|hanging|middle|ideographic|bottom"
        wordWrap: false,
        wordWrapWidth: 100,
    }
```

**Comment by djmisterjon** [comment]
It would be something like that, but I'm not sufficiently good with html5 and and javascript.


https://jsfiddle.net/jonforum/zL5beuoc/5/

Ideally to offer live changes

**Comment by bigtimebuddy** [comment]
@djmisterjon Good idea. I threw this together. It's very rough. We'll need to support gradients and a better color selector, but it's a start!

https://pixijs.github.io/pixi-text-style/

**Comment by bigtimebuddy** [comment]
If you have any suggestions for the generator, add it here: https://github.com/pixijs/pixi-text-style/issues
