### ISSUE TITLE
`AnimatedSprite`: `onComplete` never fires

### ISSUE THREAD

**Issue by kdex** [pixijs/pixi.js#4072]
I have a three-frame animation stored in `frames`. I'd expect that this code would fire whenever the third frame is reached:

```js
const jack = new PIXI.extras.AnimatedSprite(frames);
jack.onComplete = () => {
	console.log("complete");
};
jack.play();
```

However, it doesn't look like it's ever fired. `onFrameChange`, on the other hand, seems to work as expected, so I'm sure that I'm using `onComplete` the right way.

Is this a bug or am I doing something wrong?

**Comment by kdex** [comment]
Looking at the source code, it seems like `onComplete` isn't fired for loops. This might be unexpected behavior for some. A current workaround is to check if the current frame is the last frame in `onFrameChange`.

**Comment by themoonrat** [comment]
It makes sense for onComplete not to fire if the animation is looped. A new onLoop callback would be a welcome PR imo. You can't rely on onFrameChange for a specific frame index in case the frame rate is low and you never actually hit that specific frame index

**Comment by englercj** [comment]
I agree with @themoonrat, adding a new event that represents looping is the backwards compatible way to do this change.

**Comment by bigtimebuddy** [comment]
Anyone fancy putting together a PR to add `onLoop` to AnimatedSprite?

**Comment by themoonrat** [comment]
I can do that tomorrow

**Comment by bigtimebuddy** [comment]
PR merged to dev. The next release will have an `onLoop` callback.

**Comment by kdex** [comment]
Thank you! 🎉
