### ISSUE TITLE
PIXI v4.5.2 using Edge and IE 11 does not allow rendering textures from a dataURI

### ISSUE THREAD

**Issue by psyrendust** [pixijs/pixi.js#4073]
@englercj: I'm having issues rendering textures from a dataURI in IE 11 and Edge. Creating a texture from a png works fine in both. I've tried to run this with `legacy` set to `true` and `false`. I created a jsfiddle that uses `Texture.fromImage()` using a png and a data uri. It works fine in other browser, just not IE or Edge.

https://jsfiddle.net/psyrendust/c3ntwfab/

#### Windows Edge
![image](https://cloud.githubusercontent.com/assets/928502/26594845/2ac8f304-451e-11e7-8099-989e372f2353.png)

#### Windows IE 11
![image](https://cloud.githubusercontent.com/assets/928502/26594865/3db4420c-451e-11e7-9532-c98a59f91387.png)

#### Windows Firefox
![image](https://cloud.githubusercontent.com/assets/928502/26595215/8e58bebc-451f-11e7-972c-db7ef2f410cf.png)

#### Windows Chrome
![image](https://cloud.githubusercontent.com/assets/928502/26595318/d63742f8-451f-11e7-8008-adc09d2a16a3.png)

#### OS X Chrome
![image](https://cloud.githubusercontent.com/assets/928502/26594960/9e1ccf1a-451e-11e7-8d40-ef0dc703de67.png)

**Comment by psyrendust** [comment]
I was able to do some more digging today. I found that for IE11 and Edge you have to use `encodeURIComponent` on the svg string before you apply that to the `image.src`. Without the encoding the `source.onerror` function in `BaseTexture.prototype.loadSource` will fire immediately. I created a separate image element and attached it to the DOM. You'll notice that 1 renders (uses `encodeURIComponent`) and 1 has a broken image icon (does not use `encodeURIComponent`).

You can view the fiddle with the `encodedURIComponent` here: https://jsfiddle.net/psyrendust/m7nxs7wp/

The big difference is that you have to go from:

```js
var svgString = '<svg xmlns="http://www.w3.org/2000/svg" ...</svg>'; // shortened for eg
var dataURI = 'data:image/svg+xml;charset=utf-8,' +  svgString;
var dataTexture = PIXI.Texture.fromImage(dataURI);
```

To this:

```js
var svgString = '<svg xmlns="http://www.w3.org/2000/svg" ...</svg>'; // shortened for eg
var encodedDataURI = 'data:image/svg+xml;charset=utf-8,' +  encodeURIComponent(svgString);
var source = new Image();
source.src = encodedDataURI;
source.onload = function imgLoaded() {
  var baseTexture = new PIXI.BaseTexture(source);
  dataTexture = new PIXI.Texture(baseTexture);
	createIcons();
};
```

I had to do this because if you try and load the encoded source string into `Texture.fromImage` you get the following error:

```
Error: The SVG image must have width and height defined (in pixels), canvas API needs them.
    at e._loadSvgSourceUsingString (VM119 pixi.min.js:15)
    at e._loadSvgSourceUsingDataUri (VM119 pixi.min.js:15)
    at e._loadSvgSource (VM119 pixi.min.js:15)
    at HTMLImageElement.t.onload (VM119 pixi.min.js:15)
``` 

I figure that this breaks the regex that you use to get the dimensions for a svg when using `getSvgSize`.

As an alternative you might consider using something like this for `getSvgSize`, which converts the svg string into a valid svg element. Then you can use the dom api to get the correct width and height using `getAttribute`.

```js
const domParser = new DOMParser();
const ObjectToString = Object.prototype.toString;
const SVG_ELEMENT_TYPE = 'SVGSVGElement';
const SVG_DOCTYPE = 'image/svg+xml';

function stringToSvg(rawString) {
  if (ObjectToString.call(rawString).slice(8, -1) === SVG_ELEMENT_TYPE) return rawString;
  return domParser.parseFromString(rawString, SVG_DOCTYPE).documentElement;
}

function getSvgSize(svgString) {
  var svg = stringToSvg(svgString);
  var size = {};

  if (svg) {
    size.width = svg.getAttribute('width');
    size.height = svg.getAttribute('height');
  }

  return size;
}
```

**Comment by englercj** [comment]
Looks like some great fixes/changes, would you mind putting in a PR to the `dev` branch that addresses these issues?

**Comment by psyrendust** [comment]
@englercj: sure thing. For some reason I can't seem to get IE 11 to work though.

**Comment by englercj** [comment]
Hmm, that's really weird; not sure what the issue is without looking into it more with a debugger.

Does encoding the data uri work correctly in all other browsers as well?

**Comment by psyrendust** [comment]
It's looking pretty good with the monkeypatch:

#### Windows Edge
![image](https://cloud.githubusercontent.com/assets/928502/26611513/ab088ac6-4563-11e7-881a-2fb7c7914b83.png)

#### Windows IE 11
![image](https://cloud.githubusercontent.com/assets/928502/26611529/cacc3b82-4563-11e7-86a1-02d320c31920.png)

At least I'm now getting black squares to show up in IE 11.

**Comment by psyrendust** [comment]
The error in IE 11 is a `IndexSizeError` on the following line of `BaseTexture.prototype._loadSvgSourceUsingString`.

```js
canvas.getContext('2d').drawImage(this.source, 0, 0, svgWidth, svgHeight, 0, 0, this.realWidth, this.realHeight);
```

Making the dimensions a 1px smaller (in this case), allows it to run past this `IndexSizeError` issue.

```js
canvas.getContext('2d').drawImage(this.source, 0, 0, svgWidth-1, svgHeight-1, 0, 0, this.realWidth-1, this.realHeight-1);
```

But then I get hung up on a Security Error inside of `Texture.prototype.upload`:

```
gl.texImage2D(gl.TEXTURE_2D, 0, this.format, this.format, this.type, source);
```

**Comment by psyrendust** [comment]
I forgot to add the link to the fiddle: https://jsfiddle.net/psyrendust/jhfz87bf/

This contains a monkey patch for `getSvgSize` and `PIXI.BaseTexture.prototype._loadSvgSourceUsingString`. If you run this in IE11 you should see the Security Error I mentioned above.

**Comment by psyrendust** [comment]
I just made a quick test to see if the canvas was being tainted in IE11, and it is!

https://jsfiddle.net/psyrendust/19xkdag4/

![image](https://cloud.githubusercontent.com/assets/928502/26661606/95f8d5fc-4633-11e7-8f24-ac67f7c62823.png)

**Comment by josephmcasey** [comment]
Thanks for this write up @psyrendust. I read this and found out how unresponsive MSIE has been on their forums, not addressing bug reports for three years straight (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/110935/). At least with your latest response, anyone encountering this issue can quickly use feature-based control flow.
