### ISSUE TITLE
`AnimatedSprite`: Animation modes

### ISSUE THREAD

**Issue by kdex** [pixijs/pixi.js#4075]
It would be nice to have some common animation modes (e.g. `ping-pong`, `reverse`).

Currently, this can be achieved by either introducing duplicate frames into a sprite sheet (which for obvious reasons, is a bad idea) or assembling a custom array of frames from the texture cache, which isn't too great for memory (for `ping-pong`, the memory used when assembling such a frame array is almost doubled.)

This should rather be addressed by `AnimationSprite#play` itself.

**Comment by themoonrat** [comment]
Linking these ideas to https://github.com/pixijs/pixi.js/issues/3122 - a v5 refactor of this class
