### ISSUE TITLE
WebGL crashing in Chrome

### ISSUE THREAD

**Issue by Armegalo** [pixijs/pixi.js#4077]
Pixi v4.5.2 crashes WebGL in Chrome when using cacheAsBitmap=true / false several times per second on a bigger-than-screen container housing hundreds of Sprites and Graphics objects. (at least I first spotted this when I included cacheAsBitmap to stop Pixi worrying about so many sprites every frame)

Throws the following:
GL_INVALID_OPERATION : glGenSyncTokenCHROMIUM: fence sync must be flushed before generating sync token
localhost/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

**Comment by englercj** [comment]
Looks like a chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=615651

**Comment by Armegalo** [comment]
Oh well, I'll do it another way anyway

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
