### ISSUE TITLE
Float Capability

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#4078]
Similar to how `position: absolute` works in CSS it would be very useful if you could define a `float` boolean to have it ignore the parent's matrix when updating the transform.  This would give the ability to render on-screen with absolute positioning instead of being dependent on its parental hierarchy.

**Comment by englercj** [comment]
What is the use-case of having an object be a child of another object when you don't want the transforms shared? Just alpha?

**Comment by darkfrog26** [comment]
@englercj No, it's useful for situations of encapsulation (component grouping) while still allowing something to be positioned absolutely.  In my specific use-case at the moment it's more about toggling between being fixed in the layout and floating apart from the layout.

**Comment by englercj** [comment]
I don't like the idea of adding a `float` property in v4, but I will try to consider this use-case in v5 as we refactor.

**Comment by darkfrog26** [comment]
it shouldn't be a difficult addition since it would just ignore the parent's worldMatrix when updating the transform it's just impossible to accommodate without it being explicitly supported in Pixi.

**Comment by englercj** [comment]
It isn't that it is difficult, it just seems out of scope. The purpose of the scene-tree in pixi is to parent transforms. If you are grouping in a way that doesn't want those transforms grouped, that is an application-level concept.

Additionally, adding another branch to our already strained update loop is probably a no-go.

**Comment by darkfrog26** [comment]
@englercj it's entirely a distinction of encapsulation vs transformation.  If I want to create a simple component that can be reused but has many parts to it, it's not unreasonable to want those parts to be contained in that component, but not to necessarily be positioned in the same hierarchical transformation.  I could create a simple PR that has like five lines of code to support this.

**Comment by bigtimebuddy** [comment]
What about adding DisplayObject functions `localToGlobal(pt)` and `globalToLocal(pt)` so that at least it's easier to translate a global space coordinates to nested display objects?

**Comment by darkfrog26** [comment]
@bigtimebuddy that wouldn't really solve my problem though would it?  I want my object to ignore the parent matrix entirely.

**Comment by bigtimebuddy** [comment]
The `globalToLocal` approach would allow you to translate a position, but, yes, all the other parent transforms would apply.

I'm having a hard time imagining what types of components would need this for and you wouldn't just deal with a flat structure yourself. Could you please explain your use-case more? Maybe there's another approach.

**Comment by englercj** [comment]
I think the distinction I'm trying to convey is that your logical grouping and your rendering grouping are currently the same, and they shouldn't be.

If you have a logical grouping of like-minded components that you reuse; those things don't have to exist in the render tree in that same hierarchy. Group your objects in structures that make sense for you application, and group the visible rendering obnjects (pixi objects) in ways that make sense for rendering. Those two objects and concepts can (and should) be separate.

**Comment by darkfrog26** [comment]
@bigtimebuddy imagine a toolbar at the top of a page, but you can switch it to "floating" to detach it from the rest of the layout.

**Comment by Patrick-Hammond** [comment]
This could be handled by re-parenting the toolbar to and from a tranformed/untransformed container.

**Comment by darkfrog26** [comment]
@Patrick-Hammond you're right, I was simply wanting to avoid adding and removing it dynamically like that.  I'll do that if I have to, but was hoping for a more flexible option.  I assumed this would be a no-brainer since this is representative of a very common feature in HTML (absolute positioning) and is trivial to support in Pixi.

**Comment by bigtimebuddy** [comment]
PIXI is not trying to be CSS, if you have better layout options with those tools, you might consider using CSS for your layout, and just having multiple PIXI renderers that are resizable.

While technically it's an easy change, it's certainly not trivial. It would allow users to opt-out of a core feature of PIXI's display trees. I would not consider this change because I do not see the utility beyond your limited circumstance, especially when there are alternative approaches available.

In v5 we are going to introduce a much more component-based system where you could make a custom renderer which includes only the features you want. You, ostensibly, could implement your own layout/positioning paradigm but still use all the guts of PIXI, like textures, loading, etc.

**Comment by darkfrog26** [comment]
@bigtimebuddy I do believe this has far larger usefulness than just my narrow case, but I can work around it.  Any details on when 5 will be useable?

**Comment by bigtimebuddy** [comment]
We are still months away from v5 beta. You should get on the PIXI Slack channel, we post some notices there when new stuff is about to come out. Ping @ivanpopelyshev if you want to join.

**Comment by englercj** [comment]
>  I assumed this would be a no-brainer since this is representative of a very common feature in HTML (absolute positioning) and is trivial to support in Pixi.

To be clear HTML5/CSS does exactly what I suggested you do. Decouples the application layout (HTML/CSS) with the rendering layout (internal render objects). Changing a float values simply moves around internal render objects so they render differently. `HTMLElement` doesn't render anything in chromium, it just represents the application layers idea of what the document says to do, and a separate render thread holds render data that actually draws. Treat your application the same. You can have an object where setting `float = true` means it just moves some pixi objects under the hood.

**Comment by bigtimebuddy** [comment]
@darkfrog26 what approach did you settle on?

**Comment by darkfrog26** [comment]
@bigtimebuddy I wrote my own abstraction to make it so it adds and removes itself from the container if floating is enabled.

**Comment by bigtimebuddy** [comment]
Sounds good! Glad you found something that works.

I'm going to close this since you have a solution and we are unlikely to consider the `float` API you suggested.
