### ISSUE TITLE
Overlay Blending Issue

### ISSUE THREAD

**Issue by bigbadwofl** [pixijs/pixi.js#4079]
When using the overlay blend mode in a WebGL scene, I see something that looks like this. 

![image](https://cloud.githubusercontent.com/assets/5211865/26715589/8d72b4f4-4776-11e7-9d22-fed8063b1413.png)

What I'm actually expecting is something more along these lines:

![image](https://cloud.githubusercontent.com/assets/5211865/26715724/0b7008f2-4777-11e7-9ea6-797bfa4bf0e1.png)

(Ignore how badly this is shopped).

Notice how light colors are made much brighter? It honestly doesn't look like the blend mode is being applied at all. I did make sure I'm on the latest version of pixi. Could I be missing something silly?

**Comment by bigbadwofl** [comment]
Failing that ^, would it be possible to write a shader that performs arithmetic on the sprite and whatever is below it (already in the scene)?

**Comment by ivanpopelyshev** [comment]
Surprise! https://github.com/pixijs/pixi-picture

**Comment by bigbadwofl** [comment]
Noice. Looks promising, will check it out. Thanks!

**Comment by ivanpopelyshev** [comment]
I edited the message above, gave more info

**Comment by bigbadwofl** [comment]
So I'm assuming (given the performance penalty), that applying it to particles probably isn't a great idea?

Regarding the shader idea, is that feasible? I know I used to do that with Unity shaders by doing a GrabPass, but I'm assuming that's not possible with a WebGL shader?

**Comment by ivanpopelyshev** [comment]
You can render all the particles in different layer and then apply overlay, like here: https://pixijs.github.io/examples/?v=dev-blendmodes-class#/layers/lighting.js 

However, that demo uses https://github.com/pixijs/pixi-display/tree/layers , you dont need that plugin if you manually put all particles into special container. It even can be particleContainer if you have more than 1000 of them :)

**Comment by ivanpopelyshev** [comment]
But pixi-picture does not support filterBlendMode, yet :( I can implement that if you really need it :)

**Comment by bigbadwofl** [comment]
That sounds promising. How does filterBlendMode differ from blendMode?

**Comment by ivanpopelyshev** [comment]
blendMode is applied when sprite is rendered. 

filterBlendMode is applied when insides of container processed through last filter it has.

So the only thing i need to make is a special "blendFilter" that will work like pixi-picture but for big container.

**Comment by bigbadwofl** [comment]
Ah, alright. 

So with that, I'd use this example: https://pixijs.github.io/examples/#/picture/overlay.js except I wouldn't set the blendMode on individual sprites, but rather on the container (`container.filterBlendMode = ...`) just like the example does `.filters = ...` (while still using the VoidFilter) to force it to use the FrameBuffer?

**Comment by ivanpopelyshev** [comment]
Yep. The problem is i didnt implement it yet ;) gonna do it soon.

**Comment by bigbadwofl** [comment]
Gotcha. Thanks so much for all your help so far, you saved me a lot of effort.

In the meantime I got it working with the example method (setting individual particles to overlay using the plugin) and it works great! Being able to do it with an entire container will be perfect.

![1](https://cloud.githubusercontent.com/assets/5211865/26750961/96ce64ae-482e-11e7-8dd4-e3bf18d7189e.gif)

**Comment by ivanpopelyshev** [comment]
Open it in https://github.com/pixijs/pixi-picture please, otherwise i will forget about it

**Comment by bigbadwofl** [comment]
Oh, right. I had forgotten you were still busy with this.
