### ISSUE TITLE
Disable window.PIXI with NPM module

### ISSUE THREAD

**Issue by Ikderr** [pixijs/pixi.js#4082]
Is it possible to disable window.PIXI when using the NPM module with webpack? I don't want users to be able to use edit the library functions easily via devtools

**Comment by lgraziani2712** [comment]
It is not possible right now, and I'm sure it won't be possible until v5 is release. See  #3118.

**Comment by englercj** [comment]
@lgraziani2712 is correct, in v4 (and v3) our plugin strategy is basically "always export to global, plugins just pretend PIXI will exist on global". Because of that we always export to it.

I'm hoping to have a much better plugin strategy in v5 that helps alleviate this issue. Sorry :/
