### ISSUE TITLE
Canvas not redrawing RenderTexture

### ISSUE THREAD

**Issue by hanesjw** [pixijs/pixi.js#4085]
In my project I'm using a RenderTexture in conjuction with a TilingSprite to simulate slot machine reels.
If my RendurTexture gets too long then I believe I hit the max texture size in webGL and things don't look right. So instead I had the idea of having a smaller, shorter RenterTexture container and just swapping out any given texture of the RenderTexture at any given time to swap out the reel tiles. I can get it working in WebGL but canvas doesn't seem to refresh or redraw the RenderTexture. Here is some sample code you can paste into the PIXIjs website examples [https://pixijs.github.io/examples/#/basics/basic.js](https://pixijs.github.io/examples/#/basics/basic.js)

Toggle the disabledWebGl variable and see what happens in canvas; the old texture does not get removed. 
```js
var disabledWebGl = false;

var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb}, disabledWebGl);
document.body.appendChild(app.view);
var woodTexture = PIXI.Texture.fromImage('required/assets/button.png');
var bunnyTexture = PIXI.Texture.fromImage('required/assets/basics/bunny.png');

var sprites = [];
var container = new PIXI.Container();
for (var i = 0; i < 2; i++) {
    var bunny = new PIXI.Sprite(woodTexture);    
    bunny.x = 60 * i;
    bunny.y = 60 * i;
    container.addChild(bunny);
  	sprites.push(bunny);
}

var brt = new PIXI.BaseRenderTexture(300, 300, PIXI.SCALE_MODES.LINEAR, 1);
var rt = new PIXI.RenderTexture(brt);

var spriteHolder = new PIXI.Sprite(rt);

spriteHolder.x = 100;
spriteHolder.y = 100;
app.stage.addChild(spriteHolder);

app.ticker.add(function() {
    app.renderer.render(container, rt);
  	sprites[0].texture = bunnyTexture;
});
```

**Comment by hawk8** [comment]
I see of course that this is Closed, but I am not sure where to add information regarding this.

I have added both a pen with the problem and also some code how this could be solved (it might exist better solutions obviously) in https://github.com/pixijs/pixi.js/issues/1147. Or should I open a new issue (even though it seems like this has come up multiple times without really becoming resolved). I have tested against version 4.6.2 which is the latest right now. It is obvious that this does will not work until the TODO in the code has been changed to an implementation. 

Please advise what else I should do! Thanks.
