### ISSUE TITLE
Is `roundPixels` broken?

### ISSUE THREAD

**Issue by kdex** [pixijs/pixi.js#4087]
I've tested the following against `4.5.2`.

With `roundPixels: true`, I would **not** have expected the gap on the left-hand side:
![screenshot_20170606_222752](https://user-images.githubusercontent.com/4442505/26850488-ecc5c22c-4b07-11e7-87c1-64cbf81fe375.png)

If I floor `bunny.x` from `-5.656854249492381` to `-6` manually, I get what I was hoping `roundPixels` would do for me:

![screenshot_20170606_222905](https://user-images.githubusercontent.com/4442505/26850518-0f416ca2-4b08-11e7-90a0-b257be1b47eb.png)

Am I doing something wrong or is this a bug?

[Here's](https://jsfiddle.net/9jnkodor/1/) the fiddle from above.

**Comment by kdex** [comment]
Irrelevant side remark: `roundPixels` is quite a misnomer, as it doesn't actually *round*. Might be worth renaming this to `floorPixels`. 😄 I see this has [confused people before](https://github.com/pixijs/pixi.js/issues/3581).

**Comment by kdex** [comment]
Might be related to #3891

**Comment by ivanpopelyshev** [comment]
The final X,Y are rounded, not the relative ones. If you have x=0.11 and scale=10, image will appear at x=0.1

I see pixel-sharp bunny in your example, so it is correct.

If you want relative X/Y rounded automagically, make your own Transform class based on https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Transform.js ,

You should name it "roundTexels" ;)

**Comment by kdex** [comment]
Interesting. I take you're saying "absolute" when you say "final", right? What makes the coordinates  at hand *not* absolute, though? To use your example, given `scale = 10`, a bunny point with `x = 0.11` would have an absolute `x` component of `x * scale` or `1.1`. If this absolute `x` component is floored once it's time to render, it yields `x = 1`, so it should snap to a whole pixel.

Of course, I wouldn't expect it to floor relative coordinates (`x = 0.11` should not be floored to `x = 0`).

**Comment by ivanpopelyshev** [comment]
Yeah, and that's why you have one black pixel there. Its not pixel of the bunny (texel) but actual pixel in cnvas.

**Comment by kdex** [comment]
Thanks!
