### ISSUE TITLE
`forceCanvas` is broken in the latest dev

### ISSUE THREAD

**Issue by kdex** [pixijs/pixi.js#4088]
If I set `forceCanvas: true` in [this fiddle](https://jsfiddle.net/9jnkodor/), the bunny isn't rendered anymore. Doesn't happen in the `4.5.2`, but in the latest dev.

**Comment by bigtimebuddy** [comment]
The latest **dev** does work: https://jsfiddle.net/tokerxbe/

The problem is that we aren't supporting v5.0.0 yet. That was a preview release and we are not tracking issues for it yet. Please only use v4.x.

**Comment by kdex** [comment]
Gotcha, thanks!
