### ISSUE TITLE
SpriteRenderer#sprites retains destroyed sprites

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4090]
Steps

- Take heap snapshot
- add some bunny
- take heap snapshot
- destroy bunnies container
- collect garbage
- take an heap snapshot
- filter by "Objects allocated between Snapshot 1 and Snapshot 2"

Try also to look at  ```app.renderer.plugins.sprite.sprites``` before and after destroy them all

![screen shot 2017-06-07 at 16 27 56](https://user-images.githubusercontent.com/15343100/26883878-a8116fcc-4b9e-11e7-949a-3a4580f993f9.png)

[test.zip](https://github.com/pixijs/pixi.js/files/1058342/test.zip)

**Comment by englercj** [comment]
Which version of the lib is this?

**Comment by lucap86** [comment]
sorry in the example is 4.4.4 bu it also happen with 4.5.2
here it is the test case with last pixi
[test-4.5.2.zip](https://github.com/pixijs/pixi.js/files/1060170/test-4.5.2.zip)
 version

**Comment by englercj** [comment]
Thanks @lucap86 for the details, we'll look into this as soon as we find time.

**Comment by nunocf** [comment]
Any update on this? We're facing the same problem of having lots of tiny memory leaks that would be good to address.
