### ISSUE TITLE
Text dropshadow color is wrong and it is being affected by the outline stroke

### ISSUE THREAD

**Issue by NoxWings** [pixijs/pixi.js#4091]
3 examples with a red dropShadow with blur.

![image](https://user-images.githubusercontent.com/1453762/26885630-6eec72f0-4ba3-11e7-9b35-0889a36781ae.png)

```javascript
var app = new PIXI.Application(300, 300, {backgroundColor: 0x1099bb});
document.body.appendChild(app.view);

var style = new PIXI.TextStyle({
    fontFamily: 'Arial',
    fontSize: 36,
    fill: '#ffffff',
  
    strokeThickness: 5,
  
    dropShadow: true,
    dropShadowAngle: Math.PI/2,
    dropShadowDistance: 45,
    dropShadowColor: '#FF0000',
    dropShadowBlur: 5
});

var text = new PIXI.Text('Sample Text', style);
app.stage.addChild(text);
```

![image](https://user-images.githubusercontent.com/1453762/26886007-8c2cb554-4ba4-11e7-9f09-b727eaa97244.png)

Same code without the strokeThickness set to 1. You can still see the drop shadow blur is red but the shadow itself is now black instead of red.

![image](https://user-images.githubusercontent.com/1453762/26885799-ecb3ee8e-4ba3-11e7-9148-322ccf0d65df.png)

Same code without strokeThickness. You can barely see the drop shadow blur but the shadow itself is now completely black.

**Comment by themoonrat** [comment]
This is fixed in the latest dev branch via https://github.com/pixijs/pixi.js/pull/4069

**Comment by NoxWings** [comment]
Oops sorry, I forgot to take a look at closed issues I just looked in the open ones. I didn't think about the possibility of it being fixed already. 

Thank you.
