### ISSUE TITLE
Rats! WebGL hit a snag when creating (and destroying) many AnimatedSprites during app lifetime

### ISSUE THREAD

**Issue by krompir2** [pixijs/pixi.js#4093]
I am creating new AnimatedSprites on pointerdown event (and deleting them on next pointerdown event)  over the course if application lifetime. At some point around 20 clicks, the app crashes with an error:  Rats! webGl crashed. At that point no error is displayed in console. Crash happens on a mobile device, and would probably also happen on desktop, if someone perform plenty of clicks. You can anticipate the crash. Few clicks before the final crash, animations become really stuttering. 

Code that is repeatedly used is below. I also include live example at http://forwardingsolutions.club/. Can someone please point out what am I doing wrong?
```js
 function setupNextSpritesAnimation(){
        setupNextAnimation();
        console.log("next color: "+nextColor);
        switch (nextColor) {
            case "red":
                var newLoader = new PIXI.loaders.Loader()
                .add('nextSprite', '/assets/sprite/red.png.png')
                .load(function (loader, resources){
                    var interval = setInterval(function(){
                        if (!isAnimating){
                            clearInterval(interval);
                            createNewAnimatedSprite(resources,newLoader);
                        }
                    },50);

                });

                break;
            case "aqua":
                var newLoader = new PIXI.loaders.Loader()
                .add('nextSprite', '/assets/sprite/aqua.png.png')
                .load(function (loader, resources){
                    var interval = setInterval(function(){
                        if (!isAnimating){
                            clearInterval(interval);
                            createNewAnimatedSprite(resources,newLoader);
                        }
                    },50);
                });
                break;            
            case "green":
                var newLoader = new PIXI.loaders.Loader()
                .add('nextSprite', '/assets/sprite/blue.png.png')
                .load(function (loader, resources){
                    var interval = setInterval(function(){
                        if (!isAnimating){
                            clearInterval(interval);
                            createNewAnimatedSprite(resources,newLoader);
                        }
                    },50);
                });
                break;            
            case "purple":
                var newLoader = new PIXI.loaders.Loader()
                .add('nextSprite', '/assets/sprite/purple.png.png')
                .load(function (loader, resources){
                    var interval = setInterval(function(){
                        if (!isAnimating){
                            clearInterval(interval);
                            createNewAnimatedSprite(resources,newLoader);
                        }
                    },50);
                });
                break;   
                         }
    }
 

    function createNewAnimatedSprite(resources,newLoader){
        var tmpSprite = new PIXI.extras.AnimatedSprite(setupFrames(resources["nextSprite"].texture.baseTexture));
        app.stage.addChild(tmpSprite);
        spritesArray.push(tmpSprite);
        setupNextSprites(tmpSprite);

        app.renderer.plugins.prepare.upload(tmpSprite, function(){
            console.log("updoaded now");
            canRunNext = true;
            newLoader.reset();
            //console.log("kill");
            delete tmpSprite;

        });
    }
 

    function setupNextSprites(nextSprite){
        nextSprite.x = app.renderer.width / 2;
        nextSprite.y = app.renderer.height / 2;
        nextSprite.anchor.set(0.5);
        nextSprite.loop = false;
        nextSprite.animationSpeed = 0.5; 
        nextSprite.visible = false;
        nextSprite.onComplete = function (){
            console.log("animation finished");
            isAnimating = false;
        };
    }


    function setupNextAnimation(){
        var randomNumber = getRandomInt(0,3);
        switch (randomNumber) {
            case 0:
                nextColor = "red";
                break;
            case 1:
                nextColor = "aqua";
                break;            
            case 2:
                nextColor = "green";
                break;            
            case 3:
                nextColor = "purple";
                break;   
                            }  
    }
 

 

    app.stage.on("pointerdown", function () {
        if (firstRun && !isAnimating) {
            firstRun = false;
            isAnimating = true;
            currentSprite.gotoAndPlay(0);
        }else{ 
            if (canRunNext && !isAnimating){
                isAnimating=true;

                if (currentSprite.visible){
                    currentSprite.visible = false;
                    currentSprite.destroy(true);
                }
                spritesArray[spritesArray.length-1].visible = true;
                spritesArray[spritesArray.length-1].gotoAndPlay(0);

                app.stage.removeChild(spritesArray[spritesArray.length-2]);
               spritesArray[spritesArray.length-2].destroy({ children:true, texture:true, baseTexture:true});

                canRunNext = false;
                setupNextSpritesAnimation();

            }
        }
    });


function setupSpritesAnimation(){
//created currentSprite just once at the start of app
spritesArray.push(currentSprite);
}
```

**Comment by ivanpopelyshev** [comment]
That's exactly what I imagine as "multi-scene game". I understand that pixi is build with approach "user handles it itself", but can we have at least one demo for that?

**Comment by krompir2** [comment]
hey Ivan, thanks for stopping by. demo is included in the question :) I will post it here as well http://forwardingsolutions.club/

**Comment by ivanpopelyshev** [comment]
I mean that we need to put it to pixi wiki after we resolve it. That's one common use-cases.

**Comment by krompir2** [comment]
Do with the code whatever you need :) that is the least I could do to help community

**Comment by bigtimebuddy** [comment]
Hello @krompir2,

I suspect the reason that you're crashing is because you're allocating a lot of memory by creating a new Loader, new Sprite/Texture/BaseTexture every click and uploading to the GPU constantly. Something is leaking and/or the garbage collector isn't getting called fast enough to un-allocate the limited memory on your device.  I would strongly encourage you to separate the construction of the items from the playback/interaction logic, i.e., limit how often you call `new`.

For instance, make sure to preload all your images up-front instead of loading each time you need them. 

```js
new PIXI.loaders.Loader()
  .add('purple', '/assets/sprite/purple.png.png')
  .add('red', '/assets/sprite/purple.png.png')
  .add('aqua', '/assets/sprite/purple.png.png')
  .add('green', '/assets/sprite/purple.png.png')
  .load(function(loader, resources) {
     // from here on you can create a new sprite from the
     // name/id of the image you loaded
     // you're using AnimatedSprite, but this is a similar idea
     // you can use PIXI.BaseTexture.fromFrame()
     const sprites = {
       purple: PIXI.Sprite.fromFrame('purple'),
       aqua: PIXI.Sprite.fromFrame('aqua'),
       red: PIXI.Sprite.fromFrame('red'),
       green: PIXI.Sprite.fromFrame('green')
    };
    // Now there's no need to destroy the sprites each time.
  });
```

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy you sure about that? sprites are heavy too. 

I think case with one global loader and one custom loader for every stage is legit and we have to support it.  About "loader after every click" - that's only for a test.

**Comment by krompir2** [comment]
Thanks to both of you!

It seems that if you perform clicks slowly, you can get to more than 20 animations before it crashes. Garbage collection is probably the reason for this issue then, but I am not sure if phone always had the same amount of memory available, when running these tests.

However, my app requires over 100 textures (but not at the same time). I cannot load them an start, because well, it would take forever and none of the phones have the capacity, therefore I adopted the approach described above. 

There doesn't seem to be possible to trigger garbage collection manually.

**Comment by krompir2** [comment]
You are right about the loders, there is no reason for not using just 2 loaders, one on start, and one for everything else.

I added this new line at the start of example code:

`var newLoader = new PIXI.loaders.Loader();
`

and than in each case statement used `newLoader.add()`... instead of 

`var newLoader = new PIXI.loaders.Loader();
`
surprisingly this yields an error:

`Loader.js:334 Uncaught Error: Cannot add resources while the loader is running.`

**Comment by englercj** [comment]
You need to call `loader.reset()` when you are done with it. The loader is made to have resources added, load them, and be done. If you call reset it goes back to step one (clearing the `.resources` property of the things previously loaded). This is how you can resuse a single loader instance for all loading done in your game, just call `.reset()` when you plan to use it again.

This is similar to how you call `destroy` on sprites when you are done with them.
