### ISSUE TITLE
Rotation and scaling with different pivots

### ISSUE THREAD

**Issue by RiuSalvi** [pixijs/pixi.js#4094]
I want to do rotation and scaling with different pivots, how to achieve that with pixi?

**Comment by ivanpopelyshev** [comment]
The only way is two containers.

For those who understand how transforms work, make your own transform and assign it to the container: https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Transform.js

**Comment by RiuSalvi** [comment]
I want to target a single displayObject. What u are saying is aplying the scale, put object in container, rotate the container, right? i will try that

**Comment by ivanpopelyshev** [comment]
Yes.

**Comment by RiuSalvi** [comment]
I implemented the scaling manually and then used pixi rotation with the desired pivot relative to the object before the scaling. i will close the issue =)
