### ISSUE TITLE
Bitmapfontloader not reusing loaded textures

### ISSUE THREAD

**Issue by RiuSalvi** [pixijs/pixi.js#4095]
Bitmapfontloader dont reuse properly already loaded textures when loading .png and .fnt with the loader. To try this load an image with multiple bitmapfonts inside and other assets, then load the fnts relative to that image.

To patch this go to the function:
exports.default = function () {
    return function bitmapFontParser(resource, next) {
 
and look in this.resources for the texture instead of utils.TextureCache, that is empty at that moment.
line 72 from bitmapFontParser.js

for my code to work i did other fixes, like the way the image url it built and searched. 

if other people want and have this problem i can post my code.

**Comment by englercj** [comment]
At [this](https://github.com/pixijs/pixi.js/blob/9bf609a34e4bd3aeaee9965036a952ad0da9e45c/src/loaders/bitmapFontParser.js#L88) point in the middleware you have could change it to instead check if that resource already exists in the loader, and if it does use it and if not perform the loading behavior that is there.
