### ISSUE TITLE
Dynamic baseTexture SCALE_MODE

### ISSUE THREAD

**Issue by Ikderr** [pixijs/pixi.js#4096]
hi,
Is it possible to dynamically change the SCALE_MODE on a baseTexuture? 
On my pixel-art based game, I need to set PIXI.SCALE_MODES.NEAREST to all the stage when you click on my zoom button (so scale.x and scale.y are > 1) and I need to set PIXI.SCALE_MODES.LINEAR when you click on my "unzoom" button (so scale.x and scale.y are < 1).

**Comment by englercj** [comment]
Have you tried setting the `.scaleMode` property of the BaseTexture instance and then calling `.update()`?

**Comment by Ikderr** [comment]
Still not working, my game is still blurry at zoom 2
`    public SetLinearSM() {
        for(var sprite of this.Stage.children) {
            var Sprite: PIXI.Sprite = (<any> sprite);

            if(Sprite.texture && Sprite.texture.baseTexture) {
                Sprite.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.LINEAR;
                Sprite.texture.baseTexture.update();
            }
        }
    }

    public SetNearestSM() {
        for(var sprite of this.Stage.children) {
            var Sprite: PIXI.Sprite = (<any> sprite);

            if(Sprite.texture && Sprite.texture.baseTexture) {
                Sprite.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
                Sprite.texture.baseTexture.update();
            }
        }
    }`

**Comment by englercj** [comment]
Can you create a running example that reproduces the issue using jsfiddle or something similar please?

**Comment by Ikderr** [comment]
@englercj here's a simple example using a Mario pixel art from google

https://jsfiddle.net/0efjbtr2/

**Comment by jonaswalekvist** [comment]
Just stumbled across this issue and i had a similar experience at one point. What i found was that as soon as the texture is actually uploaded to the gpu there is no going back. We used the PIXI.prepare  to upload stuff to memory when each assets was loaded. That prevented us from changing scalemode. 

I could make it work by first `dispose()`  of the basetexture and let pixi reupload it to the gpu when it''s needed.  Though doing this for lots of textures all the time will have a negative performace impact.

**Comment by themoonrat** [comment]
I definitely think it would be useful if you could force a re-upload a base texture

**Comment by ivanpopelyshev** [comment]
it works in v5.
