### ISSUE TITLE
TypeError: Argument 7 is not valid for any of the 7-argument overloads of WebGLRenderingContext.texSubImage2D.

### ISSUE THREAD

**Issue by sidewinderZ** [pixijs/pixi.js#4097]
When trying to look at the examples.

Mozilla Firefox:

TypeError: Argument 7 is not valid for any of the 7-argument overloads of WebGLRenderingContext.texSubImage2D.

```
upload()
 pixi.js:21343
updateTexture()
 pixi.js:21762
bind()
 pixi.js:21675
flush()
 pixi.js:24794
render()
 pixi.js:17691
render()
 pixi.js:7911
emit()
 pixi.js:30018
update()
 pixi.js:29858
Ticker/this._tick()
 pixi.js:29594
```

Chrome:

Examples run fine.

A few days ago I tried to develop my own solution to render stuff, but there are still too many differences between browsers, enough differences to make me go crazy. The main reason I want to use pixi.js for is cross-browser compatibility, so how come I can't see the examples in Firefox 45.7.0? It's not the latest firefox version but hey, it was released this year, so I'm kind of astonished I can't even see the examples.

**Comment by englercj** [comment]
I assume this is using v5-alpha? @bigtimebuddy Have you solved the examples not using the alpha yet?

**Comment by ivanpopelyshev** [comment]
Every time you open example, switch from "release" to "development" version, that'll work. Its temporary bug )

**Comment by sidewinderZ** [comment]
Fixed. Thanks.
