### ISSUE TITLE
Does clearBeforeRender have a Performance impact?

### ISSUE THREAD

**Issue by siwel** [pixijs/pixi.js#4102]
Hey,

Can anybody help me understand if there is a performance benefit to enabling/disabling clearBeforeRender on WebGL.

I've done some testing that would suggest a small performance boost by disabling it (on mobile devices), but it's within a margin of error so want to understand more.

Thanks,
Lewis

**Comment by englercj** [comment]
It might have a small benefit, but it would be negligible. The reason to change this option wouldn't be performance, but instead would be if you actually didn't want to clear the buffer before rendering.

**Comment by siwel** [comment]
Perfect. Thankyou for confirming 👍
