### ISSUE TITLE
FPS down occurs when the number of PIXI.Sprite is over 10,000

### ISSUE THREAD

**Issue by cheerun** [pixijs/pixi.js#4103]
Hello.

 I want to create seating solution for large theater. (more then 100,000)
 So I chose Pixi.js for WebGL performance, and I tested it.

 I created 10,000 seats that has size with 10px * 10px, and they had each different 4 colors. I wanted to boost up speed, so I had to convert graphics to sprite. That means I needed 4 textures because all seats' size is same but there is 4 colors each 2500 seats. Therefore I created 4 textures and create sprite instance of graphics.

 Nevertheless I changed 10000 graphics to 10000 sprites with 4 textures, FPS down still occurs.

 I did more experiment then I became aware of FPS drop related with seat's number, that is, sprite's number. But I need to create over 100,000 seats at the same time.

 How can I do this?

 There is no animation, and I need just moving seat, selecting seat with click, multi-selecting seats with drag and little features.

 Please help me. Thank you.

**Comment by englercj** [comment]
Put all the textures into one single image, and have all the sprites share a single `BaseTexture` instance. You should have 1 `BaseTexture`, 4 `Texture`s (these are the frames for each colored chair), and 10k `Sprite`s that use one of the 4 textures each. Then put all the sprites in a `ParticleContainer`.

**Comment by cheerun** [comment]
Thank you for your fast response.

Each Chair isn't image. They are just Rect Graphics. They've only x, y, widht, height, and color.

So I created Graphics with PIXI.Graphics like below.
```typescript
const graphic = new PIXI.Graphics()

graphic.beginFill(Converter.hexStringToNumber(this.color))
graphic.drawRect(0, 0, this.width, this.height)
graphic.endFill()
    
return graphic
```
Then I converted them with `renderer.generateTexture(graphics)`.
Next, I generated Sprites with these textures, and I just set x, y, then I add to container as child.

```typescript
seatSprite.x = this.x
seatSprite.y = this.y

this.containers.seat.addChild(seatSprite)
```

How can I create `BaseTexture` with graphics? I had tried to find how to create them but I failed.

Thank you.

**Comment by cheerun** [comment]
I have one more question.

`ParticleContainer` is really awesome. But, Its children seem that they can't be interactive.
I need feature clicking each seat for selection. is It true?

**Comment by englercj** [comment]
Draw one of each chair to a RenderTexture and use that as if it were a spritesheet.

**Comment by cheerun** [comment]
Thank you! Did you have a nice weekend?

I profiled also, but I don't know why frame drop occurs with profiling that.
![screen shot 2017-06-19 at 2 28 26 pm](https://user-images.githubusercontent.com/20786586/27270800-d2783d66-54fb-11e7-93b8-5c264aea9631.png)

But I think that.. I set `interactive=true` and `seat.on('mousedown', handler)` to all seats I added. So, If seats' number is 30K, Yes, There were over than 30K event listener. Then I think also It is cause of FPS drop. What do you think?

**Comment by themoonrat** [comment]
Remove the handlers and set interactiveChildren to false on their parent and see if there's a difference :)

If there is, maybe have one overlay container that takes care of the click, and that looks at the position to convert it to a seat.

**Comment by englercj** [comment]
Looks like updatetransform is taking most of the frame time. Your best bet is to render using the ParticleContainer to fix that, then doing interaction manually or using a more specific solution than the generalized one in pixi.

**Comment by cheerun** [comment]
@themoonrat @englercj 
Thank you for yours help!

**Comment by bigtimebuddy** [comment]
Looks like this is answered. Thanks everyone.
