### ISSUE TITLE
Property 'backgroundColor' does not exist on type 'WebGLRenderer | CanvasRenderer'

### ISSUE THREAD

**Issue by Alessio22** [pixijs/pixi.js#4104]
Hi,
with pixijs v4.5.3 when I try to set background color in renderer:
`let app = new PIXI.Application(this.WIDTH, `this.HEIGHT);
`app.renderer.backgroundColor = 0xffffff;`

I get this error: 
> Property 'backgroundColor' does not exist on type 'WebGLRenderer | CanvasRenderer'

I checked the documentation [https://pixijs.download/v4.5.3/docs/PIXI.WebGLRenderer.html](url), and the property is available.

How to set background color in rederer with pixijs v4.5.3?

**Comment by bigtimebuddy** [comment]
This seems to work fine: https://jsfiddle.net/Lu1gnkqq/

In addition, you can change the backgroundColor as a constructor option: 

```js
let app = new PIXI.Application({
  width: this.WIDTH,
  height: this.HEIGHT,
  backgroundColor: 0xffffff
});
```

**Comment by Alessio22** [comment]
@bigtimebuddy it's works.
Thx!
