### ISSUE TITLE
ParticleContainer renders Sprites in only one color when sprites are assigned with multiple colors

### ISSUE THREAD

**Issue by BigFatDog** [pixijs/pixi.js#4105]
I create 2 sprites with 2 colors: indigo and green. ParticleContainer always renders them only with the first sprite's color

My code:

        let graphics = new PIXI.particles.ParticleContainer(dataLength, {}, 10000);
        stage.addChild(graphics);

        let circle1 = new PIXI.Graphics();
        circle1.beginFill(0x009688); //indigo
        circle1.drawCircle(3,3,3);
        circle1.endFill();
        let texture1 = renderer.generateTexture(circle1);

        let sprite1 = new PIXI.Sprite(texture1);
        sprite1.x = 200;
        sprite1.y = 100;
        graphics.addChild(sprite1);

        let circle2 = new PIXI.Graphics();
        circle2.beginFill(0x3F51B5); // green
        circle2.drawCircle(3,3,3);
        circle2.endFill();
        let texture2 = renderer.generateTexture(circle2);

        let sprite2 = new PIXI.Sprite(texture2);
        sprite2.x = 200;
        sprite2.y = 100;
        graphics.addChild(sprite2);

**Comment by englercj** [comment]
Correct, particle containers only use a single texture that is shared for all sprites. This allows us to push all the matrix calculations to the GPU and draw the entire container in a single draw call.

If you want multiple textures for sprites in a Particle Container you need to put them in a sprite sheet and calculate the frames.

**Comment by BigFatDog** [comment]
I see, thank you for your quick reply!

**Comment by englercj** [comment]
Anytime, closing this since it seems answered.
