### ISSUE TITLE
PIXI.mesh.Mesh - Texture framing not working.

### ISSUE THREAD

**Issue by Andrews54757** [pixijs/pixi.js#4108]
Hi, I am creating a game with pixi.js and I came across this bug: Texture framing doesn't work for Pixi.mesh.Mesh.

```js
var baseTexture = new PIXI.BaseTexture(textureAtlas);
var textureFramed = new PIXI.Texture(baseTexture, new PIXI.Rectangle(x,y,w,h));
var mesh = new PIXI.mesh.Mesh(textureFramed);
stage.addChild(mesh);
```

Instead of framing the texture, it just displays the texture as a whole.

I am using PIXI v 4.5.2 (Tested 4.5.1 too, doesnt work).

I have tested some more, and I found that texture framing works for PIXI.mesh.Plane. Perhaps https://github.com/pixijs/pixi.js/blob/dev/src/mesh/Plane.js#L107 is the reason why?

(Example: https://jsfiddle.net/5th34wcs/)

**Comment by Andrews54757** [comment]
I found a quick-n-dirty fix for anyone who has this issue as well - Do this:

```
var baseTexture = new PIXI.BaseTexture(textureAtlas);
var textureFramed = new PIXI.Texture(baseTexture, new PIXI.Rectangle(x,y,w,h));
var mesh = new PIXI.mesh.Mesh(textureFramed);

mesh.refresh();
mesh.multiplyUvs();

stage.addChild(mesh);
```

**Comment by ivanpopelyshev** [comment]
ok, that means I somehow implemented it wrong :) You found the functions that i made for framing, somehow they weren't called in your case.

**Comment by ivanpopelyshev** [comment]
btw, another workaround:

```js
mesh.uploadUvTransform = true;
```

**Comment by themoonrat** [comment]
Still an issue @ivanpopelyshev ?

**Comment by ivanpopelyshev** [comment]
No, it can be closed.
