### ISSUE TITLE
Support for all blendEquations in WebGL Renderer

### ISSUE THREAD

**Issue by mawe42** [pixijs/pixi.js#4109]
Hi,

I noticed that there is no way to set different [blendEquations](https://developer.mozilla.org/de/docs/Web/API/WebGLRenderingContext/blendEquation) for the WebGL renderer. I'm thinking about adding that support and creating a pull request. But before I delve into the code and start the attempt..... are different blendEquations maybe left out for a specific reason? Is compatibility an issue, or does it not fit into the current PIXI blending architecture?

Thanks,
Marcus

**Comment by mawe42** [comment]
Excellent, thanks! Is the v5 branch very experimental or fairly stable already?

**Comment by englercj** [comment]
Very experimental, it is not currently usable.

**Comment by ivanpopelyshev** [comment]
There's another branch for blendmodes, https://github.com/pixijs/pixi.js/pull/4049

**Comment by mawe42** [comment]
Thanks! I've decided to simply patch my renderer.state.setBlendMode during runtime to enable the DIFFERENCE blend mode in WebGL (using blendEquation(gl.FUNC_REVERSE_SUBTRACT) and blendFunc(gl.ONE, gl.ONE). Works great and is a good workaround until v5 is ready.
