### ISSUE TITLE
Is the hack for iOS still valuable?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4112]
In SpriteRenderer.js , there are some code for iOS  performance : 

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L398

( about canUploadSameBuffer(). )

In the last iOS ( 11.x ) , do we still need them ?

**Comment by themoonrat** [comment]
Did you find an answer to this @finscn ? Personally, I never had any issues with ios 11 performance wise.

**Comment by finscn** [comment]
I don't know any thing about this issue. maybe @ivanpopelyshev could help us

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital  might help with it. He's developing new renderer for v5 we can ask him whether this optimization is present there.
