### ISSUE TITLE
Question: PIXI.Text Drop Shadow blur expected behaviour

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4113]
i've tried  https://pixijs.github.io/examples/?v=v4.5.3#/basics/text.js exaple with dropShadowBlur settled to 20.

the question is:
should when dropShadowBlur > 0 only blur to be visible?
My expectation was to see "unblurred" drop shadow hidden.

**Comment by GoodBoyDigital** [comment]
Seems this to have been lost in the sea if of issues! Sorry about that :)
The drop shadow uses the basic canvas methods to achieve.  More info here: https://www.html5rocks.com/en/tutorials/canvas/texteffects/

Hope this is useful 👍
