### ISSUE TITLE
Feature request: Force rendering to whole-pixel coordinates

### ISSUE THREAD

**Issue by kdex** [pixijs/pixi.js#4115]
I'm trying to achieve something along the lines of what has been described in #4087, but after fiddling around and seeing no other way than to fork PIXI to monkey-patch `Transform` as was proposed, I'd like to ask if this could be implemented in the main project.

Basically, the current behavior of `roundPixels` doesn't do what I expected it would; I'm looking for a way to floor every `x`/`y` component before rendering it to the screen, while still storing them as regular floating-point `Number`s in the containers.

**Comment by ivanpopelyshev** [comment]
I thought that's how it actually works, it works in SpriteRenderer: https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js

I believe that you can modify that code to achieve what you want to do.

**Comment by kdex** [comment]
Thanks again, @ivanpopelyshev; `SpriteRenderer` seems like the right class. :)

I've tried changing `vertexData = sprite.vertexData;` to `vertexData = sprite.vertexData.map(Math.floor)`, and `float32View = float32View.map(Math.floor)` (once it's been modified) for testing purposes, but apart from visual glitches, I don't see the `Sprite` pixels snapping. What am I missing?
