### ISSUE TITLE
skew & pseudo 3d rotation

### ISSUE THREAD

**Issue by ramarro123** [pixijs/pixi.js#4116]
Hello,

coming from flash world, i am trying to convert an animation of a card that move around an inclinated table.

do simulate the 3d transformation and prespective, on the old code, the movieclip that contains the card get some skew, and some rotationX,Y,X (that are props of movieclip)

there is anything like that on pixi?

it's possible to rotate/flip/keep in prospective an object with this kind of transformation?

tnx

**Comment by ivanpopelyshev** [comment]
There was @finscn 's code that worked, but i dont remember where is it.

Also there is also an old fork https://github.com/gameofbombs/pixi.js that allows 3d sprites, especially cards: https://gameofbombs.github.io/pixi-bin/index.html?s=flip&f=cards.js&title=Cards

**Comment by finscn** [comment]
the demo is at  http://fattyboy.cn/pt/  , 
the source code is at https://github.com/finscn/pixi.js/tree/master/src/morerenderers/perspective

**Comment by ivanpopelyshev** [comment]
Hello! We have new plugin: https://github.com/pixijs/pixi-projection , it does not have flip/rotate by axis yet, but at least it has perspective.
