### ISSUE TITLE
UnWanted Flickering in game due to spine animation

### ISSUE THREAD

**Issue by shubhrakushal** [pixijs/pixi.js#4117]
I am writing a code using pixi.js ,in which i have to animate multiplw characters at one position constantly, but i am facing an issue of unwanted flickering in the same, this issue occurs in chrome, firefox,IE, safari browsers for both desktop and mobile.The approach i am following is as follows:-
1. creating a root container at PIXI.Point(0,0) and then give it an appropriate position.
2. create child of the root container and add spine that is to be animated.
3. animate the spine .
4. after the animation is complete if there comes another spine that is to be animated in the same container, i hide the previous spine and display the new.(**This is the point when flickering occur at the PIXI.Point(0,0).If i remove the old spine also same issue still occurs)**
5. remove all the childern of root container once the animation is completed.
Please help me out as it is very important

I am working on pixi version (4.1.0)

**Comment by ivanpopelyshev** [comment]
Can you update to latest pixi.js? Also, are both spine objects of the same model?

**Comment by shubhrakushal** [comment]
@ivanpopelyshev 
Both the spine are rendering in same container one after the another.
The solution you gave spineObject.update(0); is not working in pixi 4.1.0

Is there any solution possible on pixi 4.1.0?

**Comment by shubhrakushal** [comment]
I have updated to pixi version 4.5.2 but no luck... still facing this issue.

**Comment by ivanpopelyshev** [comment]
There are too many ways to implement what you asked, I need the exact code that isnt working.

**Comment by ivanpopelyshev** [comment]
Or you can just change the code of https://pixijs.github.io/examples/#/spine/dragon.js and post it here.

**Comment by shubhrakushal** [comment]
dragon = new PIXI.spine.Spine(res.dragon.spineData);
    var dragonCage = new PIXI.Container();
    dragonCage.addChild(dragon);

    // measure the spine animation and position it inside its container to align it to the origin
    var localRect = dragon.getLocalBounds();
    dragon.position.set(-localRect.x, -localRect.y);

    // now we can scale, position and rotate the container as any other display object
    var scale = Math.min(
        (app.renderer.width * 0.7) / dragonCage.width, 
        (app.renderer.height * 0.7) / dragonCage.height
    );
    dragonCage.scale.set(scale, scale);
    dragonCage.position.set(
        (app.renderer.width - dragonCage.width) * 0.5,
        (app.renderer.height - dragonCage.height) * 0.5
    );

    // add the container to the stage
    app.stage.addChild(dragonCage);
  
dragon.state.setAnimation(0, 'flying', false);
 dragon.state.addListener ({// updated to pixi 4.5.2
                complete: function() {
                   // do certain task();
                  // just setting the variables that define our animation is completed

                    }
                }
            });

**Comment by ivanpopelyshev** [comment]
That works for me. I still dont understand what do you mean.

**Comment by shubhrakushal** [comment]
you might be placing single spine in that, in our project multiple spines are animating together, maybe that is causing us issue, we have used masking for now to resolve the issue, but we are not sure whether that is full proved solution or not.

**Comment by ivanpopelyshev** [comment]
I don't place anything there, I just run it. I need an example that doesn't work properly on your computer.

I'll either fix the pixi-spine, either fix your example that way it works fine :) Just the word "masking" tells me that you are doing it wrong.

I know that you need working solution right now, but making crutches crutches is not the best method in this situation. Just calm down, make full example that i can paste into pixi-examples, or upload something to https://fiddle.jshell.net/

**Comment by shubhrakushal** [comment]
I will do this exercise and share with you :)

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍

**Comment by ivanpopelyshev** [comment]
I've fixed the issue in pixi-spine last week.

**Comment by shubhrakushal** [comment]
Thank you so much ... 😊
