### ISSUE TITLE
Set sprite source x/y and width/height?

### ISSUE THREAD

**Issue by Ikderr** [pixijs/pixi.js#4121]
Hello,
In my massive MMO multiplayer game, every player have his own skin. 
When my client reaches about 500+ players, it uses a lot of ram (approx 1gb)

## **Part I - Explanations of this high memory usage**

_(skip this if you don't care about explanations xD)_ 

This is due to textures I assign to EACH user. 

Each user have about 50 textures (for animations), so imagine with 500 users (= 50 * 500 = 25000 textures). 

To fix this issue, I want to do like I was doing in HTML5 Canvas: using **only one spritesheet as a texture** per user, and then set _source x, source y, source width and source height_ dynamically. 

So instead of using 50 textures per user, I'll only be using one. 
Wow, imagine how much memory this will free up!

**How can I do this with PIXI?** 

## **Part II - Little example / demo of my problem**

To help you understand (I don't know if my explanations were clear enough), I've made a little demo with some Mario sprite from Google.

*Fiddle*: https://jsfiddle.net/yq2hb514/1/

The code in the fiddle is basically speaking for himself (comments),

**so I'm expecting this result:**

[![img1][1]][1]

**instead of this (like in the demo)**

[![img2][2]][2]

**NOTICE**: As told before, I don't want to crop my spritesheet into multiple textures, I want to use only **ONE texture** (the spritesheet)

Thanks in advance.

  [1]: https://i.stack.imgur.com/vPal7.png
  [2]: https://i.stack.imgur.com/y9Our.png

**Comment by ivanpopelyshev** [comment]
The idea is to create multiple Texture's with same BaseTexture.

PIXI.Texture is actually texture region.

```
var baseTex = PIXI.loader.resources["mario"].texture.baseTexture;
var frames = [new PIXI.Rectangle( 0, 0, 87, 175), new PIXI.Rectangle( 87, 0, 87, 175)];
var tex = frames.map(function(frame) { return new PIXI.Texture(baseTex, frame); });

var MarioSprite = new PIXI.Sprite(tex[0])

// later
MarioSprite.texture = tex[1];
```

**Comment by ivanpopelyshev** [comment]
Also, if you use linear filtering (by default), its better if all frames have 1 transparent pixel on the border, otherwise you'll see some artifacts in case of non-integer coords.

**Comment by englercj** [comment]
>How can I do this with PIXI?

`BaseTexture` hold a source, like an image. Create only 1 of those. `Texture` holds a reference to a `BaseTexture` and a `frame` which is the rectangle into the `BaseTexture` that should be drawn.

I updated your example:

https://jsfiddle.net/yq2hb514/2/

**Comment by Ikderr** [comment]
@ivanpopelyshev don't worry, this is just a demo to illustrate my problem 😃 
@englercj oh, thank you!!

**Comment by ivanpopelyshev** [comment]
@lkderr Its an issue that appears only in webgl, and is not seen with simple canvas drawImage, so don't be surprised when you see it. Switching ```PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST```, or just changing scaleMode of particular baseTexture, or just adding that one pixel will help.

Also, pixi can parse json spritesheets if you give generate some with https://renderhjs.net/shoebox/ (json hash format) or other tool. You can even embed it all in one big json with all of your skins and load at startup, then just pass stuff to spritesheetParse or something like that. But that all requires that you actually clone and read pixijs code and not just read the documentation (which by the way is generated from the code).

**Comment by ivanpopelyshev** [comment]
Also, try
 
```
texture.rotate = 12;
```

You'll be surprised ;) http://pixijs.github.io/examples/#/demos/texture-rotate.js

**Comment by Ikderr** [comment]
@ivanpopelyshev oops, I haven't seen it when you posted it

Are you sure that creating textures for each frame (~50) per user (so it'll be 50 textures and 1 base texture per user) won't leak memory like in my explanation part?
 
Talking about SCALE_MODE, what about my previous issue? https://github.com/pixijs/pixi.js/issues/4096, is it just because of my "GPU" (intel hd graphics) or is it a bug? 

Going to try texture.rotate now to see haha

**Comment by ivanpopelyshev** [comment]
Dynamic changing is not possible in v4, it changes properties only when the texture is uploaded first time, and second time it only re-uploads pixels: 

https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/TextureManager.js#L180

Of course you can do that yourself...

```js
BaseTexture.prototype.I_JUST_WANT_IT_TO_WORK = function(renderer) {
    baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
    var glTexture = baseTexture._glTextures[renderer.CONTEXT_UID];
    if (glTexture) {
        glTexture.bind();
        glTexture.enableNearestScaling();
    }
}

myBaseTexture.I_JUST_WANT_IT_TO_WORK(renderer);
```

**Comment by Ikderr** [comment]
No problem don't worry, I'll probably look in the source later when I'll be working on my zoom functionnality to see how things work with linear & nearest scale modes.

What about my previous question : "Are you sure that creating textures for each frame (~50) per user (so it'll be 50 textures and 1 base texture per user) like what you did in your answer won't leak memory like in my explanation part?" 

I really need something that'd use the less amount of ram possible

**Comment by englercj** [comment]
It will only leak if you don't call `.destroy()`.

**Comment by ivanpopelyshev** [comment]
It'll leak if you dont destroy baseTexture. 

But you also are using PIXI.loader that can retain links to that baseTexture, and i dont know what it will do when you ask it to download the resource one more time.
