### ISSUE TITLE
glDrawElements: attempt to access out of range vertices in attribute 0

### ISSUE THREAD

**Issue by fabien-h** [pixijs/pixi.js#4122]
I tried to setup the dome : http://pixijs.github.io/examples/#/demos/batch.js . The demo runs, but I get this warning :

	254 [.Offscreen-For-WebGL-0x7fb93c163200]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
	WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by bigtimebuddy** [comment]
@fabien-h thanks for reporting. Could you give us some more information about what browser, platform, device, hardware, etc that you're using? Thanks.

**Comment by fabien-h** [comment]
MacOs, chrome. Pixi last version on npm. 

Here is the weird thing : when I add to my main container the demo and then another container on the top of it, no warning. But when the container is under it, I have the warnings.

**Comment by ErikLarsson82** [comment]
I have stumbled upon this error aswell but the setup to reproduce it is quite complicated.
I've seen the error in both v4.3.4 and v4.5.4.
There seem to be a combination two containers. One containing a ParticleContainer and one with Graphics that use _drawPolygon_ with some _alpha_ and _blendMode_
One way to solve it for me is to draw the particle layer before the graphics layer.

I'd love to get some feedback on what i can try to debug this, since my temporary solution might really limit my game design in the future.

**Comment by ivanpopelyshev** [comment]
That sounds esoteric! I think I stumbled upon it too.

**Comment by ivanpopelyshev** [comment]
I did some changes on blendmodes. Doi you still encounter that bug?

**Comment by ErikLarsson82** [comment]
Running the same code on 4.5.5 still produces the error. Unfortunately the code is a bit difficult to reproduce separated from the rest so I have difficulties showing it to you.

**Comment by ivanpopelyshev** [comment]
I cant reproduce it. However I'm here to help if you find the way to share it :)

**Comment by ivanpopelyshev** [comment]
Found something interesting: try to specify maxSize for that ParticleContainer (first param in constructor).

**Comment by ErikLarsson82** [comment]
I spent some hours trying to reproduce it in a separate project but without success. An interesting thing is that im using a full screen graphics tint object and that seems to glitch in the rendering whenever my particles cause the error.
I did try to specifiy maxSize and also tinker with the other settings but it had no effect.

**Comment by ivanpopelyshev** [comment]
Full screen graphics tint? Is that rectangle? If so, can you please just switch to tinted PIXI.Sprite with PIXI.Texture.WHITE ?

**Comment by ErikLarsson82** [comment]
Yes, it's a rectangle. I tested switching and the bug is no longer present, however my previously full screen color tint is now reduced to a small 10x10 rectangle (as defined by PIXI.Texture.WHITE).
I don't understand how i would fit this to the whole screen (and paint it in a proper color).

**Comment by ivanpopelyshev** [comment]
just set width/height of that sprite and it'll fit the screen

```js
sprite.width = app.screen.width;
sprite.height = app.screen.height;
```

**Comment by ErikLarsson82** [comment]
Nice!
However, i spoke too soon. The blend modes for the tint is not behaving the same way.
(I'm only using NORMAL, ADD, MULTIPLY and SCREEN)
1. Graphics beginFill(color) + alpha + blend mode
2. Sprite with WHITE + tint + alpha + blend mode
Should these yield the same results?

**Comment by ivanpopelyshev** [comment]
It should have same results. Whats your case?

**Comment by ErikLarsson82** [comment]
I solved it. Another piece of code had changed causing two separate layers to render together, causing a different end result.
The two different ways described above now renders the same - correct and as expected. Thanks!

**Comment by ivanpopelyshev** [comment]
@ErikLarsson82 it looks like you have fun with layers and blendmodes. Wanna join pixi slack to discuss it?

**Comment by ErikLarsson82** [comment]
Oh nice! I'd love to!

**Comment by ivanpopelyshev** [comment]
Then send me something from your email to ivan.popelyshev@gmail.com

**Comment by ErikLarsson82** [comment]
Done.

**Comment by distinctdan** [comment]
I just had this issue in my game and tracked it down to trying to draw a circle with a negative radius.
