### ISSUE TITLE
Cannot read property 'width' of null when moving away from screen

### ISSUE THREAD

**Issue by royibernthal** [pixijs/pixi.js#4125]
I have an Ionic app that uses the latest versions of angular 4 and ionic 3.

I'm using PIXI (4.5.2) in one of the screens in it - the game screen.

The player frequently moves in and out of that screen.

**Before starting the game I'm:**

-Preparing resources
-Moving to game screen
-Adding the canvas (app.view) to DOM

**Before moving away from the game screen I'm:**

-Destroying resources and resetting the PIXI.loader
-Removing the canvas (app.view) from DOM

Most of the time everything works fine, but rarely when I'm moving away from the game screen I'm getting the following error:

> Runtime Error
> 
> Cannot read property 'width' of null
> Stack
> TypeError: Cannot read property 'width' of null at Image.e.calculateVertices (http://localhost:8100/assets/imageSwapper/pixi.min.js:14:13368) at Image.e._renderWebGL (http://localhost:8100/assets/imageSwapper/pixi.min.js:14:14230) at Image.e.renderWebGL (http://localhost:8100/assets/imageSwapper/pixi.min.js:10:21822) at Swapper.e.renderWebGL (http://localhost:8100/assets/imageSwapper/pixi.min.js:10:21898) at e.renderWebGL (http://localhost:8100/assets/imageSwapper/pixi.min.js:10:21898) at e.render (http://localhost:8100/assets/imageSwapper/pixi.min.js:13:8590) at t.render (http://localhost:8100/assets/imageSwapper/pixi.min.js:10:10909) at t.emit (http://localhost:8100/assets/imageSwapper/pixi.min.js:16:7855) at t.update (http://localhost:8100/assets/imageSwapper/pixi.min.js:16:6834) at _tick (http://localhost:8100/assets/imageSwapper/pixi.min.js:16:5017) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12256) at Object.onInvokeTask (http://localhost:8100/build/main.js:4539:37) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12177) at n.runTask (http://localhost:8100/build/polyfills.js:3:7153) at invoke (http://localhost:8100/build/polyfills.js:3:13213)

I don't know yet why this error only rarely occurs and why. What do you think?

**Comment by bigtimebuddy** [comment]
Would it be possible to get the unminified stackstrace? Also, could you give a code snippet of how you're destroying the app?

**Comment by royibernthal** [comment]
For some reason I'm not able to reproduce this issue anymore, if and when this happens again I'll send here the stack trace of the unminified version.

**Comment by bigtimebuddy** [comment]
Sounds good. I'm going to close this issue, if it happens again and there's more info, please reopen.

**Comment by royibernthal** [comment]
I finally have an unminified stacktrace:

> core.es5.js:1084 ERROR TypeError: Cannot read property 'width' of null
>     at Image.calculateVertices (Sprite.js:211)
>     at Image._renderWebGL (Sprite.js:295)
>     at Image.renderWebGL (Container.js:409)
>     at Swapper.renderWebGL (Container.js:414)
>     at Container.renderWebGL (Container.js:414)
>     at WebGLRenderer.render (WebGLRenderer.js:318)
>     at Application.render (Application.js:128)
>     at TickerListener.emit (TickerListener.js:78)
>     at Ticker.update (Ticker.js:394)
>     at Ticker._tick (Ticker.js:113)
>     at t.invokeTask (polyfills.js:3)
>     at Object.onInvokeTask (core.es5.js:4116)
>     at t.invokeTask (polyfills.js:3)
>     at n.runTask (polyfills.js:3)
>     at invoke (polyfills.js:3)

**Comment by bigtimebuddy** [comment]
Guessing it's this line: https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L215 

If you are able to reproduce this again, could you log out `texture` and `orig`?

**Comment by royibernthal** [comment]
console.log(texture, orig); - orig is null

![log](https://user-images.githubusercontent.com/7274413/28731269-f13b9f0a-73db-11e7-8d4b-6aa95b041173.png)

**Comment by bigtimebuddy** [comment]
Is it possible to make a jsfiddle which reproduces this error?

**Comment by royibernthal** [comment]
It's a bit difficult and cumbersome because we're talking about an ionic app that wraps this.
Do you think it's possible to solve it without a reproduction? Or otherwise by remote control?

**Comment by bigtimebuddy** [comment]
Is it possible you are destroying the Texture and then rendering? Or destroying resources but not removing children from your app? Are you using app.destroy?

**Comment by royibernthal** [comment]
Yup.

**-Destroying resources and resetting the PIXI.loader**
-Removing the canvas (app.view) from DOM

Apparently PIXI kept rendering after canvas was removed from DOM?

Now whenever I'm destroying textures I'm removing the sprites that are using them. I think it's solved. Thank you :)

**Comment by bigtimebuddy** [comment]
Sounds good 👍
