### ISSUE TITLE
Basic Shader example with Pixi 4.x

### ISSUE THREAD

**Issue by nuthinking** [pixijs/pixi.js#4126]
Trying to use custom shaders with Pixi 4 but I struggle to port the example: https://codepen.io/nuthinking/pen/vZpOEJ?editors=0010

Thanks!

**Comment by nuthinking** [comment]
Solved (removing **alpha** from the fragment as advised [here](https://stackoverflow.com/questions/41785478/converting-pixijs-v3-abstractfilter-to-v4-filter))

**Comment by ivanpopelyshev** [comment]
I added one more demo some time ago: https://pixijs.github.io/examples/#/filters/filter-mouse.js
