### ISSUE TITLE
Pixi.js v4.5.2 crashing when using an Iphone7 (iOS 10.3.2)

### ISSUE THREAD

**Issue by Richacinas** [pixijs/pixi.js#4127]
I can't figure it out, why both Safari and Chrome on my Iphone7 is causing the browser to crash.

I am unable to read any log information as it closes the browser when I'm inspecting. Here is a little piece of my code:

```
 init: function () {
     self.renderer = PIXI.autoDetectRenderer(1920, 1070, { 
      transparent: true,
      view: document.getElementById('stage'),
      resolution: window.devicePixelRatio || 1,
      autoResize:true
    }); 
    document.getElementById('drawingArea').appendChild(self.renderer.view);


    // create the root of the scene graph
    self.stage = new PIXI.Container();
    self.stage.interactive = true;

    PIXI.loader
      .reset()
      .add("ottoBonesData", "./app/public/static/image/chapter9/ottoProject_ske.json")
      .add("textureDataA", "./app/public/static/image/chapter9/ottoProject_tex.json")
      .add("textureA", "./app/public/static/image/chapter9/ottoProject_tex.png");
      PIXI.loader.once("complete", self._loadComplateHandler, self);
      PIXI.loader.load();

    self.animate();
}

_loadComplateHandler: function(loader, resources){
    var self = this;

    dragonBones.PixiFactory.factory.parseDragonBonesData(resources["ottoBonesData"].data);
    dragonBones.PixiFactory.factory.parseTextureAtlasData(resources["textureDataA"].data, resources["textureA"].texture);   

    self.armatureDisplay = dragonBones.PixiFactory.factory.buildArmatureDisplay("Armature");
    self.armatureDisplay.animation.play("aleteo_mute");
    self.armatureDisplay.scale.x = 0;
    self.armatureDisplay.scale.y = 0;
    self.armatureDisplay.interactive = true;
    //self.armatureDisplay.y = self.renderer.height * 0.5 + 100;
    self.stage.addChild(self.armatureDisplay);

    self.loadMultipleTimelines( self.options.data, self.options.readyCallback);
    self.renderOnCanvas();
 },

  animate : function () {
    var self = this;
    self.renderer.render(self.stage);
    self.frame = requestAnimFrame(self.animate);
  },

  renderOnCanvas() {
    var self = this;
    self.renderer.render(self.stage);
  },

```

There is no error when I initialize my web game, however, as soon as I play the GSAP timelines that I'm using to call my animations, I can see a couple of seconds of my animations being rendered incredibly slow and then it crashes.

Any ideas? could this be a PIXI problem?

Thanks a lot...

Ricardo

**Comment by Richacinas** [comment]
This doesn't happen on older Iphones, neither on an older Ipad... It only happens on the latest ones. Android is working great too.

**Comment by ivanpopelyshev** [comment]
Do you have meshes there?

**Comment by Richacinas** [comment]
No, I don't.. I just tried playing different parts of my game, and it plays nicely. It must be something about some of the animations I'm using here, or something else... debugging

**Comment by ivanpopelyshev** [comment]
I havent study how dragonBones runtime works yet

**Comment by Richacinas** [comment]
Hi again Ivan.

I wanted to let you know that it was a problem with CSS. Really, really strange. 

When we animate a layer like this on the device that I mentioned:

```
div.bgPortion {
	background-size: 50% 100%;
	background-position: left bottom;
	background-repeat: repeat-x;
	width: 200vw;
    	height: 100vh;
    	position: absolute;
    	bottom: 0;
    }
```

```
@keyframes animatedBackground {
	from { 
        transform: translate3d(0, 0, 0);
        -webkit-transform: translate3d(0, 0, 0);
    }
    to { 
        transform: translate3d(-50%, 0, 0);
        -webkit-transform: translate3d(-50%, 0, 0);
    }
}
```

It makes both Chrome and Safari crash on the Iphone. If we remove, for example, the position absolute from CSS, it works great but we can't see those layers properly positioned.

Just wanted to let you know, out of curiosity.

Thanks for your help, we could close this issue for sure!

**Comment by ivanpopelyshev** [comment]
Ok then, we have to write it down somewhere: CSS 3d animations + webgl = pain on iphone.

**Comment by stevenalanstark** [comment]
this sounds similar to: [https://github.com/pixijs/pixi.js/issues/1848](https://github.com/pixijs/pixi.js/issues/1848)

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
