### ISSUE TITLE
Canvas extract blank during pointerdown event

### ISSUE THREAD

**Issue by jordanhe2** [pixijs/pixi.js#4129]
I'm trying to extract a canvas from a sprite when it has been clicked or tapped. For some reason when I use the renderer's extract all I get is an empty canvas with the proper width and height.

Here's the essence of my code, I can provide the actual code if neccessary.
```javascript
sprite.on("pointerdown", function (e) {
    // results in the blank canvas with the dimensions of the sprite
    var canvas = app.renderer.extract.canvas(sprite);

    window.open(canvas.toDataUrl());
});
```

I from my tests, the extract will work on any other DisplayObject within the pointerdown event except for the DisplayObject that is the target of the event. The extract will also work on the sprite in question when I use it outside of the pointerdown event. I'm using v4.5.3 by the way.

**Comment by ivanpopelyshev** [comment]
Are you trying to make pixel-perfect interaction?

**Comment by jordanhe2** [comment]
I've found why I'm getting this behavior. So when I have code like this:

```javascript
var app = new PIXI.Application({
	antialias: true,
	backgroundColor: 0xFFFFFF
});

var loader = PIXI.loader;

var stage = app.stage;
var extract = app.renderer.extract;

var url = "http://www.goodboydigital.com/wp-content/uploads/2014/04/pixijs.png";

loader
	.add(url)
	.load(function () {
		var sprite = new PIXI.Sprite(
			PIXI.loader.resources[url].texture
		);


		sprite.interactive = true;
		sprite.on("pointerdown", function () {
			window.open(extract.canvas(sprite).toDataURL());
		});

		stage.addChild(sprite);
	});

document.body.appendChild(app.view);
```

Everything is fine and the canvas shows the sprite properly like this:
![](http://www.goodboydigital.com/wp-content/uploads/2014/04/pixijs.png)
But if the sprite had its position offset like in the following code:

```javascript
sprite.x = sprite.width / 2;
sprite.y = sprite.height / 2;
```

You get something like this:
![download 3](https://user-images.githubusercontent.com/17969543/27698946-4af2a6ae-5cbe-11e7-8980-2b4c64b1210d.png)

So the canvas offsets the texture from the sprite by the same amount as it's offset by the stage. Is this expected behavior?

**Comment by jordanhe2** [comment]
Right now I can work around it by doing the following:

```javascript
sprite.interactive = true;
sprite.on("pointerdown", function (e) {
	var x = sprite.x;
	var y = sprite.y;

	// Re-render sprite at 0,0 to prevent shifting on canvas
	sprite.x = 0;
	sprite.y = 0;
	app.renderer.render(sprite);

	window.open(extract.canvas(e.target).toDataURL());

	// Place sprite back to normal position and let autoRender re-render it
	sprite.x = x;
	sprite.y = y;
});
```

**Comment by modjke** [comment]
@jordanhe2 Besides resetting sprite's position you should also reset pivot, anchor, rotation.
