### ISSUE TITLE
Allow passing Sprite destroy options down from PIXI.Application

### ISSUE THREAD

**Issue by baseten** [pixijs/pixi.js#4135]
It would be useful to be able to entirely destroy an application including it's textures from a single call to `PIXI.Application.destroy` at the top level. However the additional options required to destroy a `PIXI.Sprite` can only be called on the Sprite itself. Would be great if these could be passed through from `PIXI.Application` too.

**Comment by bigtimebuddy** [comment]
Are you suggesting changing this:
```js
destroy(removeView)
{
    // ...
    this.stage.destroy();
    // ...
}
```
To this:
```js
destroy(removeView, stageOptions)
{
    // ...
    this.stage.destroy(stageOptions);
    // ...
}
```

Would welcome a PR for this!

**Comment by baseten** [comment]
@bigtimebuddy, yes that's exactly what I'm suggesting :)

I'll see about getting a PR made early next week.
