### ISSUE TITLE
ParticleContainer is broken for certain scene graphs

### ISSUE THREAD

**Issue by mirraj2** [pixijs/pixi.js#4137]
I created a little particle system and a demo -- the demo was working great with 100k particles.

I then incorporated the particle system into my game.  The moment I cast a spell, which created a new particle emitter, the following error started spitting out to console:

`[.Offscreen-For-WebGL-0x7f952006bc00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer`

The screen no longer rendered most of my tile map.  It did render the particles.

Here is the scene structure I had

- rootContainer
  - Container
      - ParticleContainer
  - Container
      - Lots of sprites (the tiles)
  - Container
  - Container
  - Container

You can see, as recently as a month ago, that other people have this problem as well.  http://www.html5gamedevs.com/topic/30675-gldrawelements-range-out-of-bounds-for-buffer/

The last post on that thread says:

> I have had this same issue with particleContainer. Solved that by changing the particleContainers to regular containers

I'm going to solve this the same way for now, but I think particle container should either be removed or fixed.

I'm on chrome 58 on a macbook pro.

**Comment by davidfig** [comment]
You need to increase the number of particles by changing maxSize or setting autoResize=true when you create the particle container. See http://pixijs.download/dev/docs/PIXI.particles.ParticleContainer.html

**Comment by themoonrat** [comment]
@mirraj2 I know it's been a long time, but was wondering it this is still an issue on the latest pixi? Thanks!

**Comment by mirraj2** [comment]
Sorry, I have no idea.  Would take me too long to try to reproduce it again.

**Comment by themoonrat** [comment]
No probs.

Will close for now then
