### ISSUE TITLE
Feature Request: Origin Property

### ISSUE THREAD

**Issue by OSUblake** [pixijs/pixi.js#4138]
Using pivot and anchor seems to confuse a lot of people because it changes the position. It's like doing this in CSS. 

```
// PixiJS
sprite.rotation = 45 * Math.PI / 180;
sprite.pivot.set(sprite.width / 2, sprite.height / 2);

// CSS equivalent
.sprite {
  transform-origin: 50% 50%;
  transform: translate(-50%, -50%) matrix(0.7071, 0.7071, -0.7071, 0.7071, 0, 0);
}
```

Normally, you wouldn't use `translate(-50%, -50%)` because the transform origin is at the center by default. That does work great when you want to center something, but not when you want to position stuff from top-left corner. 

There needs to be a way to control how the display object is oriented, like the origin property described here. This would also make it more consistent with how transforms work with DOM elements.
https://github.com/pixijs/pixi.js/issues/997

Here's a demo showing how that might look. I'm not 100% sure about my matrix, but I think that is the behavior a lot people are expecting. 
https://codepen.io/osublake/pen/a4f18b10530f8f385aec9f253d226275

**Comment by englercj** [comment]
It would be great if we implemented #997 in the v5 transform, at least `pivot` and `origin`, obviously anchor is texture related.
