### ISSUE TITLE
potential bug in src/core/math/Matrix.toArray ?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi.js#4140]
looking at `fromArray()`:  https://github.com/pixijs/pixi.js/blob/dev/src/core/math/Matrix.js#L76-#L83

the array structure is `[a, b, tx, c, d, ty]`

looking at `toArray()`  https://github.com/pixijs/pixi.js/blob/dev/src/core/math/Matrix.js#L140-#L148

for this non-transposed case, why is the array ordering different?

**Comment by englercj** [comment]
No idea...

Pretty sure we don't use `fromArray()` or `toArray(false)` anywhere in the lib so they may just be hold overs from previous versions.

**Comment by mreinstein** [comment]
prior to submitting this issue I grepped the code to see if `toArray()` is ever called with `false`. It's not. That's what led me to believe this *could* be a bug...given how fundamental the matrix module is I'd figure this would have been surfaced by now if it were used in the engine in any significant way.

Still, this might be investigating/fixing since the `Matrix` module is documented in the public interface, so someone might use it.

**Comment by bigtimebuddy** [comment]
We should probably deprecate that toArray() method. Would welcome a PR for that.

**Comment by mreinstein** [comment]
Sounds like we're not clear there's a bug with the code. Closing.

**Comment by englercj** [comment]
I removed these in v5, but feel free to PR v4 with the changes you think are appropriate!
