### ISSUE TITLE
Request: ES6 Build on NPM

### ISSUE THREAD

**Issue by KritR** [pixijs/pixi.js#4141]
It would be nice to be able to easily integrate newer build management systems and use the neat tree shaking features of the new JS module builders. (e.g. Rollup, Webpack)

If the library were to include a [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module) pointing to an ES6 build, this would allow for backwards compatibility with existing build systems as well as the option of using a newer ES6 build.

This may need to be an issue under [pixify](https://github.com/pixijs/pixify).

**Comment by bigtimebuddy** [comment]
In v5 of PixiJS (In the works right now) we are planning on moving to Rollup for building source code so this will be much easier to do. I'll definitely keep in mind generating a pkg.module file. The current build system, however, isn't ideal for this and will be unlikely to change unless someone is interested in creating a PR.

**Comment by dekdevy** [comment]
Is there a way to look into the v5 already? i'm currently trying to get rollup + pixi going, but having no success so far. Any news / info is highly appreciated, thank you!

**Comment by englercj** [comment]
v5 is mostly a collection of proposals, experiments, and ideas at this point. Stay tuned.

I keep my worklist here: https://github.com/pixijs/pixi.js/projects/3

**Comment by bigtimebuddy** [comment]
This has already been implemented in v5. Until we make a new release, you can check it out by cloning the **next** branch of this repo.
