### ISSUE TITLE
Pixi fails to render on older hardware using Chrome 59 or later

### ISSUE THREAD

**Issue by DDowell** [pixijs/pixi.js#4146]
PixiJS (and PhaserJS as well) fails to render when running in WebGL mode on some older devices (like the Samsung Galaxy Tab E with KitKat 4.4).

This only happens in Chrome 59 or later (tested on Canary 61 with same results).

Steps to reproduce:
1. Open any PixiJS example running in WebGL mode (for instance the RenderTexture demo).
2. Observe that the canvas is rendered completely black.
3. Notice that the log is clean (no errors).
4. Test the same demo in another browser (e.g FireFox) and notice it renders correctly.

Was it working before: Yes, in previous versions of Chrome (<59).

**Comment by photonstorm** [comment]
Given that Chrome is constantly updating its GPU blacklist it's entirely possible they decided to do this on purpose. Do other WebGL demos (three.js, etc) work or not? If not, there's nothing Pixi (or you I'm afraid) can do about it. If they do, something specific to Pixi is going on.

**Comment by themoonrat** [comment]
Using legacy webgl mode may help, if it is only pixi suffering the issues. Else do what i do and maintain your own list of devices to not allow webgl on (I've done this on all devices on android versions less then 5, for example, as any device still on that android version is old and I've learnt i can't trust the webgl drivers for those devices to be stable or always work correctly.

**Comment by DDowell** [comment]
I don't think it is due to blacklisting since I am able to get a custom project of mine to render for a split second and then go black. All examples only renders black though (at least from what I can see). There are also other WebGL content out there that DO render correctly. It is only pixi-based applications that fail.

Simply turning off WebGL on older devices may not be so great an approach since it will negatively affect the product's performance.

**Comment by englercj** [comment]
Have you tried enabling legacy mode (`{ legacy: true  }` in your constructor params)?

**Comment by craig-memero** [comment]
I think I am experiencing a similar issue and am not sure what the expected behaviour should be. 

If I go to chrome://gpu/ I can see: WebGL: Unavailable and WebGL2: Unavailable.

The if I go to http://pixijs.github.io/examples/#/filters/outline-filter.js I can see the bunnies but the filter is not working (works in other browsers). I assume this means filters are only available in WebGL? Is that correct?

**Comment by DDowell** [comment]
Sorry for the late response. Setting legacy:true makes no difference.
PhaserJS (all versions) are also affected by this issue so it is not only "pure" PIXI but all derivatives as well.
The issue is present in Chrome 59+ only.

**Comment by englercj** [comment]
If some other apps work, but ours doesn't it could be related to the fact that we initialize with a Stencil buffer?

**Comment by ivanpopelyshev** [comment]
There's setting to drop down stencil, but masks with PIXI.Graphics wont work after that.

**Comment by ZergMaster** [comment]
I have the same problem. I try exec examples from https://github.com/kittykatattack/learningPixi, but in chome i see just have black screen. Other browsers is working well. 
But this https://www.goodboydigital.com/pixijs/bunnymark/ right work chrome.
Whats the hell?)

**Comment by ivanpopelyshev** [comment]
@ZergMaster need more details ;)

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
