### ISSUE TITLE
Displacement + rotation error

### ISSUE THREAD

**Issue by jbjanot** [pixijs/pixi.js#4147]
Hi!

First, I would like to thank you all for this amazing tool.

I am working on a displacement applied to a shape (PIXI.Graphics()).
When the container is rotated, the shape starts "moving" randomly.

[Here is the pen I have been working on](https://codepen.io/jbjanot/pen/VWBqpr?editors=0010)

I guess it is a PIXI bug, because it doesn't occur when the filter is not applied.

Thanks for your help!

Have a nice day.

PIXI 4.5.3
Google Chrome 59.0
Mas OS Sierra 10.12.5

EDIT : I updated the pen to be sure the map is overlaping the rectangle. You might need to resize the viewport a bit to see the glitch.

**Comment by ivanpopelyshev** [comment]
Just a small note: its not important whether its TilingSprite or Sprite in dispacelement, only its transform matrix and texture matters.

**Comment by jbjanot** [comment]
Absolutely, the TilingSprite is just a remaining of my previous full code before reducing to a simple case. I used it to have a debug sprite to see what was happening when moving the displacement texture map.
The pen is now updated, thank you for your feedback.

**Comment by themoonrat** [comment]
@jbjanot I know it's been a looooong time (sorry!) but is this still an issue in the latest PIXI?

**Comment by ivanpopelyshev** [comment]
Actually, did you see in ANY renderer displacement filter that can handle the rotations of sprites? just for reference to use.

**Comment by jbjanot** [comment]
Sadly, I did not work on the project for a year or so, and I erased my codepen.
I might open it again, and I'll be more happy to leave a feedback here.
Thanks for the help.
