### ISSUE TITLE
OS hides cursor while pressing WASD

### ISSUE THREAD

**Issue by mirraj2** [pixijs/pixi.js#4149]
I realize this issue is not really a fault of PixiJS, but I figured it would be a common issue for people making games in the browser, so maybe someone here knows how to solve this.

In my game, the user presses WASD to move, while simultaneously using the mouse to aim and fire off spells.  The cursor is constantly flickering because OSX has a "feature" that hides the mouse cursor while someone is typing -- something that makes sense in normal scenarios, but not for games.

I've tried hiding the native mouse cursor and listening for the "mouseover" event and then rendering my own cursor at the latest location.  This works to a degree in that it stops the flickering, but there is noticeable input delay.  The cursor just feels sluggish.

Any ideas?

**Comment by kaansoral** [comment]
I remember being where you are about a year ago, ignoring the issue solved it for me :)

**Comment by mirraj2** [comment]
@kaansoral Ignoring the flickering or the sluggishness?

**Comment by kaansoral** [comment]
Ignoring the flickering, also, generally people move their cursors while gameplay, and when you move the cursor, the cursor constantly re-appears, it's a small consolidation
