### ISSUE TITLE
Ability to substitute earcut for libtess.js for a given Graphics object

### ISSUE THREAD

**Issue by trusktr** [pixijs/pixi.js#4151]
Drawing SVGs in Pixi.js (f.e. with pixi-svg and similar projects) results in incorrect output because Earcut doesn't care about accuracy. Libtess.js does.

Maybe it would be great to be able to specify whether a Pixi Graphics object should use earcut or libtess.js. Most of the time earcut might be fine. But then after experimenting, some Graphics objects could be switched to libtess.js. This way we aren't using libtess.js for everything so we still have earcut speed where earcut works, and only slower speed on a limited set of Graphics.

Example use case:

Use a tool like pixi-svg to create a hierarchy of Graphics objects that mirror the structure of the SVG tree being drawn (or create complex shapes with Pixi itself). See output on the screen and notice that one polygon (of possibly many) may have incorrect polygons sticking out (you know, earcut problems, glitchy looking). Add new code to get the culprit Graphics node from the tree and switch it to libtess.js, knowing that only that node has the problem. And now everything draws as expected.

**Comment by trusktr** [comment]
Here's a screenshot showing an SVG drawn with pixi-svg:

![screenshot 2017-07-08 at 6 34 54 pm](https://user-images.githubusercontent.com/297678/27990443-44893760-640c-11e7-80ba-842b7e40475d.png)

On the left is the native DOM SVG version for reference. On the right (although flipped vertically) is the one drawn with Graphics commands by [pixi-svg](https://github.com/bigtimebuddy/pixi-svg). Besides the extruding polygons, the cutout word "my" in the ribbon is filled in.

**Comment by ivanpopelyshev** [comment]
If someone makes minimal test for earcut, I might be able to fix it.

**Comment by englercj** [comment]
Earcut (and its tests) are here: https://github.com/mapbox/earcut

Looks like we are a bit behind in versions, it is possible that updating could help. Otherwise I'd suggest opening a PR on earcut that includes a failing test they can fix. I will try to make this more modular in v5.

**Comment by ivanpopelyshev** [comment]
@englercj pixijs package.json specifies "earcut": "^2.0.7", and we have latest version (2.1.1) in latest build for sure, I see the changes from their last commits.

**Comment by englercj** [comment]
> @englercj pixijs package.json specifies "earcut": "^2.0.7", and we have latest version (2.1.1) in latest build for sure, I see the changes from their last commits.

Ah, good call. Wonder if this is an earcut or Graphics issue then.

> because Earcut doesn't care about accuracy

They do, they just make tradeoffs like we all do. I bet if you raise a use-case (or a failing test, even better) on the repo the author will look into it. They have been responsive to issues in the past.

You can always triangulate using anything you want, and render the triangles instead of using Graphics altogether.

**Comment by finscn** [comment]
Be careful about this issue of mapbox/earcut :  https://github.com/mapbox/earcut/issues/74

**Comment by englercj** [comment]
Great share @finscn thanks for bringing this up. I'll make sure to think about plugable triangulation in v5.

**Comment by finscn** [comment]
BTW ， I don't test.  but I think the performance of  mapbox/earcut is better than cdt2d's.

**Comment by ivanpopelyshev** [comment]
I aree on pluggable triangulation.
