### ISSUE TITLE
possible to drawRoundedRect with 2 different number

### ISSUE THREAD

**Issue by jcyuan** [pixijs/pixi.js#4152]
drawRoundedRect(0, 0, w, h, ellipseWidth, ellipseHeight);
I mean this, draw rounded rectangle with these 2 numbers

**Comment by ivanpopelyshev** [comment]
Just patch the graphics.

https://github.com/pixijs/pixi.js/tree/dev/src/core/math/shapes

https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/Graphics.js#L613

https://github.com/pixijs/pixi.js/tree/dev/src/core/graphics/webgl/utils

**Comment by jcyuan** [comment]
ok, I'll try it later once Im available.  thanks buddy.

**Comment by feldhaus** [comment]
[https://github.com/feldhaus/pixi-rounded-polygon/blob/master/index.html](url)
