### ISSUE TITLE
Large WebGL context dimensions do not match drawingBufferWidth and drawingBufferHeight

### ISSUE THREAD

**Issue by manubb** [pixijs/pixi.js#4153]
I can not say that this is really a bug but width and height of very large WebGL renderer do not match gl.drawingBufferWidth and gl.drawingBufferHeight (depending on hardware and browser). For example:
In chrome 59 with 
```js
var test = new PIXI.WebGLRenderer({width: 4000, height: 2000, resolution: 1.5});
```
We have: 
```js
test.width = test.view.width = 6000
//and
test.height = test.view.height = 3000
```
 but:
```js
test.gl.drawingBufferWidth = 5792
//and
test.gl.drawingBufferHeight = 2896
```
 A possible fix for this could be to automatically lower resolution so that width (resp. height) matches drawingBufferWidth (resp. drawingBufferHeight): in the previous example, setting resolution to `1.5 * 5792 / 6000 = 1.448` leads to:
 ```js
test.width = test.view.width = test.gl.drawingBufferWidth = 5792
//and
test.height = test.view.height = test.gl.drawingBufferHeight = 2896
```
What is your feeling on this? Should this be done on application side or on Pixi side?

**Comment by ivanpopelyshev** [comment]
That's serious issue, I think we need to think on it.

**Comment by manubb** [comment]
FYI, in order to dynamically change resolution of a renderer, i need to set new resolution both on the `renderer` and on  `renderer.rootRenderTarget`. Then a call on `renderer.resize(width, height)` does the job. (It appears that updating resolution on the renderer only is not sufficient.)

**Comment by imamik** [comment]
Is this issue solved? I have the same problem and modifying the rootRenderTarget does not work in my application...

**Comment by ivanpopelyshev** [comment]
It wasnt fixed.  @imamik if its for mobiles , there's possible workaround with meta-tags on html page: https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#mobile-devices-crashes-and-problems

**Comment by ivanpopelyshev** [comment]
There's workaround:

> A possible fix for this could be to automatically lower resolution so that width (resp. height) matches drawingBufferWidth (resp. drawingBufferHeight): in the previous example.

**Comment by ivanpopelyshev** [comment]
I doubt it will be fixed before someone from core team reproduces it, so we need more details on how to reproduce it.

**Comment by manubb** [comment]
I'm fixing this on application side. You can have an example [here](https://github.com/manubb/Leaflet.PixiOverlay/blob/master/L.PixiOverlay.js#L194-L209). Basically, i resize the renderer with using initial resolution and if the renderer does not have the expected size, i lower the resolution and resize again.

**Comment by geddski** [comment]
I've run into this same bug on bigger monitors :(

**Comment by geddski** [comment]
Example screen size with no bug:
canvas size: 7680 x 1976
drawingBuffer: 7680 x 1976

Example screen size **with** bug:
canvas size: 7680 x 3008
drawingBuffer: 6544 x 2563

It appears Pixi is limiting the drawingBuffer size.

**Comment by geddski** [comment]
Oh nevermind I realized I just need to scale the stage down as well.

**Comment by levabala** [comment]
Got the same bug
When I use WebGLRenderer with width > 4000px it starts stretching
For test I draw rectangle 100x100 and when check its size it shows something like 160x100

![image](https://user-images.githubusercontent.com/6113473/59432163-57b9b800-8def-11e9-9e53-2d80fbbae809.png)

A bit less context's width
![image](https://user-images.githubusercontent.com/6113473/59432230-80da4880-8def-11e9-9e03-9bef43d44c39.png)

It seems like 4096 is max size for WebGLRenderer. 

P.S.
Solved by changed resolution in order to increase render dimensions to 4096px (like mentioned upper)
