### ISSUE TITLE
Paths in PIXI.Graphics get auto-closed when using PIXI.CanvasRenderer and beginFill

### ISSUE THREAD

**Issue by fmhdp** [pixijs/pixi.js#4154]
Hi,

first of all, thanks for this really nice framework. PIXI basically spared me writing my own, bug-ridden abstraction from WebGL with a canvas fallback.

One thing, that I believe to be a bug, I came across is a difference in render behavior between the WebGLRenderer and the CanvasRenderer. 
Assume a PIXI.Graphics object that draws an arc. If there is a beginFill command, even one with an alpha value of 0, the paths gets closed automatically in when using the PIXI.CanvasRenderer, while that is not the case with the WebGLRenderer.

Example:
https://jsfiddle.net/3snvu0dy/5/
PIXI version used in the fiddle should be 4.5.3.
I see no differences between Chrome, Firefox and Safari on OSX.

Expected behavior:
Same rendering behavior for canvas and webGL. The arc is not closed.

Experienced behavior:
The arc is closed only when using PIXI.CanvasRenderer.

I unfortunately did not have the time yet to dig into the PIXI code to see what causes the difference.

Thanks in advance for considering this :)

**Comment by bigtimebuddy** [comment]
Looks like a bug. Thanks for reporting this!
