### ISSUE TITLE
Mouse event on stage doesn't capture mouseup/mousedown of right button

### ISSUE THREAD

**Issue by crazyyi** [pixijs/pixi.js#4157]
I have read the bug/enhancement [3963](https://github.com/pixijs/pixi.js/pull/3963) which tries to make pixi.js interaction event closer to browser behavior.

However in my testing I have found it unable to capture mouse right button event on `mouseup` and `mousedown` events.

In the native browser behavior, `mouseup` and `mousedown` events are both captured/fired when I click the right button. You can see it in the second example of  the following link [here](https://stackoverflow.com/questions/40705350/how-to-detect-right-mouse-button-release-event-in-javascript).

In pixi.js 4.5.3, when I click/press the right button, neither on PC nor on Mac will these two events be captured. Only the `contextmenu` event is fired/captured. `mouseup` and `mousedown` are simply ignored. Unless I use "ctrl + left button" combo on Mac, which is not the same as a right click with mouse. Check it out [here](https://codepen.io/caymanbruce/pen/xrmKZE?editors=1111)

What is the consequence?

It is hard to separate `mouseup` and `mousedown` events of the right button pressing and releasing. Sometimes I want the right button down to do something and `mouseup` to do some other thing but end up getting the opposite result. If this can't be fixed I have to use a native javascript event to do the job.

**Comment by DennisSmolek** [comment]
The mousedown event is still firing if the user has their mouse set to "one-click" or whatever they call it. Mine is setup for `contextMenu` so your browser `preventDefault()` catches it and kills the event. 

I actually switched up your setup to use `pointerEvents` instead. That way I could track mouse and touch, and use the `event.data.buttons` to know what button triggered the event. You can see that here: 

https://codepen.io/DennisSmolek/pen/OjbJZm?editors=1111
```
app.stage.pointerdown = mousedownEventHandler;

function mousedownEventHandler(e) {
  //get the data
  var button = e.data.button;
  console.log('Mouse Down: button is:', button);
}
```

**Comment by crazyyi** [comment]
@DennisSmolek OK it seems pointerdown/pointerup does similar things with mousedown/mouseup, I am not aware of that. So why do we need both mousedown/mouseup and pointerdown/pointerup in pixi.js? Why not just combine them?

**Comment by themoonrat** [comment]
In future versions of pixi, we may do, but for backwards compatibility within the v4 release it is important to keep mouse and touch events

**Comment by DennisSmolek** [comment]
Yeah, if you support less than IE 11 you can't use pointerEvents or need a shim. The biggest reason is that older apps used mousedown/mouseup and they dont want them to break when  they upgrade to the newer versions.

Moving forward though I would use `pointerEvents` as it makes it much much easier for different devices like Mice, Touchscreen, Pens, Tablets, etc...
