### ISSUE TITLE
need help , this qusetion is about fps in pixi.js

### ISSUE THREAD

**Issue by wocaatm** [pixijs/pixi.js#4160]
```js
        var stats = new Stats()

        document.body.appendChild( stats.dom );

        var app = new PIXI.Application();

        var renderer = PIXI.autoDetectRenderer(window.innerWidth,window.innerHeight);

        document.getElementById('stage').appendChild(renderer.view);

        var stage = new PIXI.Container();

        let sprite = new PIXI.Sprite.fromImage('circlef.png');

        stage.addChild(sprite)

        function update (){
            requestAnimationFrame(update)
            sprite.x +=1
            renderer.render(stage)
            stats.update()
        }

        update()
```

i set the renderer full of screen , when the screen is large , the fps only have 30 - 33 fps ,but when the screen is small ,the fps can make to 60 fps ,  why?

**Comment by ivanpopelyshev** [comment]
Using DIV above canvas forces different compositeLayers behaviour. May be you should report FPS in console every few seconds instead.

**Comment by bigtimebuddy** [comment]
Small note here about your code. Application auto-updates so you don't need to setup a new requestAnimationFrame. Your example will render twice per frame (which is expensive). To do the sprite.x += 1 bit do this instead:

app.ticker.add(function() { sprite.x += 1; });

**Comment by Shafley** [comment]
I have encountered the problem, my design is 1040px*1440px, so the canvas is the same size, the computer can reach 60 FPS, but in 53cm * 90cm screen, FPS only 20~30, when I set the stage zoom 0.5, FPS can reach 30~40. I use app.ticker.FPS show FPS. why?

**Comment by wocaatm** [comment]
i think the reason why the FPS is so low is beacause the autoDetectRenderer method return a webGL renderer , but my computer is older , when i switch the autoDetectRenderer to the CanvasRender , the FPS go back 60 fps

**Comment by wocaatm** [comment]
@Shafley i think the reason why the FPS is so low is beacause the autoDetectRenderer method return a webGL renderer , but my computer is older , when i switch the autoDetectRenderer to the CanvasRender , the FPS go back 60 fps
