### ISSUE TITLE
Right click event?

### ISSUE THREAD

**Issue by jsbloo** [pixijs/pixi.js#4162]
Hello,
I saw a post from 2014 with the same issue.
I am making a simple pirate ship game, I want the left click to fire cannons of the port side of the ship and
a right click to fire the cannons of the starboard side of the ship.

I am currently using this `document.oncontextmenu = document.body.oncontextmenu = function() {return false;}`
To prevent the user opening the context menu on right click. 
Does anyone know how I can implement my idea?

**Comment by crazyyi** [comment]
change your function to 
```
function(event) {
    event.preventDefault();
    // fire some cannons here
}
```

**Comment by jsbloo** [comment]
@crazyyi Brilliant thank you Aaron
