### ISSUE TITLE
Leak to kernel_task on OSX

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#4163]
Hi,

My game started leaking to kernel_task on OSX, we had a similar leak a while ago, it turned out to be a Chrome/DOM leak, several Chrome versions later the issue was gone, this one isn't Chrome tho, it happens on an old Electron build too

Since the leak is not on the browser, as the memory usage of kernel_task increases, rather than the browser process itself, I'm out of ideas - I suspect it might be a WebGL issue

Any ideas? / Could it be PIXI?
(I was on 4.4.4, tried 4.5.3, same)

**Comment by ivanpopelyshev** [comment]
Hey! Yeah, it could be WebGL issue. Do you use renderTextures?

**Comment by kaansoral** [comment]
Yes, very heavily

**Comment by ivanpopelyshev** [comment]
PIXI GC doesn't care about renderTextures. May be you have to create an array where you put all of them and scan it sometimes, whether all of them were really destroyed, just check some of the properties that are set to null in destroy of base texture: 

https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/BaseTexture.js#L612

that's fired on every renderer on dispose event:

https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/TextureManager.js#L192

Actually, i dont see where the glRenderTarget is destroyed.

@mat @englercj @bigtimebuddy  ALARM!!!

**Comment by ivanpopelyshev** [comment]
@kaansoral can you place breajkpoint here please?

 https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/BaseRenderTexture.js#L123

If you have a problem with it , write in your file

```js
PIXI.BaseRenderTexture.prototype.destroy = function() { 
  this.super(true); this.renderer = null; 
}
```

If you actually use that thing, app will stop there. In that case, its probable that we have leak in RenderTexture and its not destroyed properly when your app asks for it.

If app is not stopping there, then its something else.

**Comment by kaansoral** [comment]
I imported the `PIXI.BaseRenderTexture.prototype.destroy` bit into my code, initially it wasn't called, turns out I wasn't calling the `.destroy` of renderTexture's as `.destroy(true)` - However, since I don't want the actual base textures to be destroyed, shouldn't I be calling the destroy of renderTexture as just `.destroy`?

Anyway, I've reproduced the issue easily after you've pointed me in the direction of RenderTexture's, without `.destroy(true)` - the memory pressure instantly goes up

**Comment by ivanpopelyshev** [comment]
If your render textures are global you don't have to destroy them. The question is about temporary base-render-textures.

**Comment by kaansoral** [comment]
Each time a map is visited, I generate a renderTexture from all the small tiles, each time a user visits another map, I destroy everything related to the old map - Don't use any meshes

I see that I destroy my Text's with `text.destroy({texture:true,baseTexture:true});` - I guess this was another live and learn experience, thanks for your help, this issue was bugging me for a week, I'm really relieved after finding a solution, and sadly, it seems the leak was there for a while too, but I only now discovered it

If it's the expected behaviour, the issue can be closed too

**Comment by ivanpopelyshev** [comment]
Btw that's default params for destroying text, you dont have to specify them: 

https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L12

so how do you generate and then re-use the renderTexture?

**Comment by kaansoral** [comment]
I don't re-use the renderTexture, I just generate it once when the player visits a map, use it in a Sprite, and when the user visits another map, I destroy everything from the old map, including the renderTexture

**Comment by ivanpopelyshev** [comment]
There we have our leak. Hope @GoodBoyDigital will fix it soon in critical update.

**Comment by ivanpopelyshev** [comment]
#4173 #4174 Possibly fixed the issue. @kaansoral please report!

**Comment by kaansoral** [comment]
Hi, `.destroy(true)`'s are still needed, otherwise, there is no change between `4.5.3` and `4.5.4` for me, at `4.5.3`, `.destroy(true)` was also a solution

**Comment by bigtimebuddy** [comment]
That's to be expected. Destroy param is definitely needed here. See the docs for destroy info. http://pixijs.download/release/docs/PIXI.Container.html#destroy
