### ISSUE TITLE
AnimatedSprites goToAndPlay / goToAndStop updateTexture never called

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4166]
````
  AnimatedSprite.prototype.gotoAndStop = function gotoAndStop(frameNumber) {
        this.stop();

        var previousFrame = this.currentFrame;

        this._currentTime = frameNumber;

        if (previousFrame !== this.currentFrame) {
            this.updateTexture();
        }
    };

    AnimatedSprite.prototype.gotoAndPlay = function gotoAndPlay(frameNumber) {
        var previousFrame = this.currentFrame;

        this._currentTime = frameNumber;

        if (previousFrame !== this.currentFrame) {
            this.updateTexture();
        }

        this.play();
    };
````
previousFrame !== this.currentFrame is never true.

**Comment by bigtimebuddy** [comment]
Thanks for reporting. Would it be possible to create a jsfiddle which recreates this error? That would be tremendously helpful for us to track down this issue.

**Comment by lucap86** [comment]
I don't know if it may be a problem
I neither have a buggy example
just seeng this piece of code and want to focus your attention over it.

**Comment by bigtimebuddy** [comment]
Well currentFrame is a getter and converts the currentTime to a frame and then compares against the previous frame.

**Comment by lucap86** [comment]
oh, i miss this step.
so forget it and sorry.

**Comment by bigtimebuddy** [comment]
No worries, thanks for looking at the source code. Let us know if you see anything else!
