### ISSUE TITLE
Filters + scaling

### ISSUE THREAD

**Issue by gle6da** [pixijs/pixi.js#4167]
Hello guys,
I have some problem with custom filters (even with core filters, like displacement), when I try to scale the object with filter applied.

Here is the fast pen with this problem:
https://jsfiddle.net/gle6/3t3whLLp/19/

Is there a way to fix this? As I understand I need to update bounds of the DisplayObject every time I scales it?

**Comment by ivanpopelyshev** [comment]
You use "mapCoord" then "unmapCoord", and if you comment "unmap" it works fine.

**Comment by gle6da** [comment]
Thanks! Works great

**Comment by ivanpopelyshev** [comment]
mapped coords are in 0..1 that's what you need. unmapped is for the case if you need to get the original object texture. If you dont use it, I recommend to try https://github.com/pixijs/pixi-plugin-example or even the v4 plugin generator: http://www.html5gamedevs.com/topic/31704-createshaderplugin-helper-function/

It'll work much faster (no extra framebuffer) and you wont need to map coords.
