### ISSUE TITLE
PIXI Matrix, Skew live Generator Tools ???

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4168]
**Hi everyone** 
Is there a tool to generate a live preview of the Matrix PIXI.
I'm talking about being able to preview live the transformation of a sprite, and get the code.
I find it very long and hard to do a lot of rending testing each faith to search the good behavior.
It would be really great if someone could make a small live generation tool. (HTML)

i made a sample on PS To help understand my need.
![matix-sample-generator](https://user-images.githubusercontent.com/24865815/28399712-bd4ee3d8-6cdc-11e7-8926-b74d5681acbd.png)

I hope this overview helps to understand.
Ideally, it be something similar to this awesome tools by **Karl Matt (bigtimebuddy)** 
[https://pixijs.github.io/pixi-text-style/#](https://pixijs.github.io/pixi-text-style/#)

**I would be very happy if a similar tool would exist.**
thank

**Comment by ivanpopelyshev** [comment]
We should add pivotX,pivotY and axises there. Sorry, no perspective in pixi, that bunny isnt possible in vanilla v4, but people asked for 3d plugins a number of times already, I hope to make proposal for v5 :)

**Comment by djmisterjon** [comment]
oups yes i forget rotation pivot.
It was a quick visual concept.

**Comment by djmisterjon** [comment]
In fact I do not know why we talk about 3d.
It is simply 4 point redimention. !
we have no Z Axe here , only a manual scale 4 per point limit
I made a fast gif here to show .
We have only XY AXE with a anchor to center.
![597095f3bab1b396803491](https://user-images.githubusercontent.com/24865815/28415711-e20d31d8-6d1e-11e7-934c-389a37374862.gif)

If I understand correctly, pixi only allows the scale by 2 points and not 4 ?

**Comment by ivanpopelyshev** [comment]
Good question. 3d projection is required to map a texture to quad: 

http://xproger.info/projects/OpenLara/shots/uv.gif

http://xproger.info/projects/OpenLara/shots/uv_chairs.gif

**Comment by ivanpopelyshev** [comment]
Actually, now i think i can make it with 2d, but not with affine transform :)

**Comment by djmisterjon** [comment]
Yes I think that's what you're talking about.
Unfortunately this is out of range of my knowledge.

http://mathinsight.org/determinant_linear_transformation

https://en.wikibooks.org/wiki/GLSL_Programming/Vector_and_Matrix_Operations
It would be really ideal to have a live tool to practice.

**Comment by XProger** [comment]
In general case (not only for trapezoids) problem is solving by storing all four vertices in each of them and bilinear interpolation in the shader.
http://www.reedbeta.com/blog/quadrilateral-interpolation-part-1/
http://www.reedbeta.com/blog/quadrilateral-interpolation-part-2/
or you can use tessellation (not perfect result)
https://youtu.be/8TleepxIORU

**Comment by ivanpopelyshev** [comment]
I didnt read it, i just noticed that in homogenous coords our matrix is 

```
ca 0  0
0  cb 0
sa sb 0
```

Where (ca, sa) is (cos a, sin a) , angle around Y axis. 

I wanna make a plugin that adds two more angles that'll do the job!

**Comment by djmisterjon** [comment]
i follow you keep us update of your work friend. 🥇 👍

**Comment by finscn** [comment]
I created an renderer for perspective

the demo is at  http://fatidol.com/pt/  , 
the source code is at https://github.com/finscn/pixi.js/tree/master/src/morerenderers/perspective

**Comment by djmisterjon** [comment]
https://github.com/pixijs/pixi.js/issues/4180

**Comment by djmisterjon** [comment]
thank to @ivanpopelyshev 
https://pixijs.github.io/examples/#/projection/basic.js
It is enough to inject a small console.log () to follow the values in real time.

**Comment by ivanpopelyshev** [comment]
Here we are: http://pixijs.github.io/examples/#/projection/quad-bi.js 

Bilinear quad mapping!

**Comment by djmisterjon** [comment]
awesome thanks !

**Comment by jchayan** [comment]
@ivanpopelyshev What is the status for projections? Should we expect them to be available on the next version of PIXI?

**Comment by ivanpopelyshev** [comment]
People are waiting for me to make 3d version. Right now its 2.5d stuff.

No, they wont be available in v5, but there will be multiple 3d plugins: I will make one and @GoodBoyDigital will post whatever they use for 3d games on pixi.

**Comment by jchayan** [comment]
@ivanpopelyshev Got it, thank you.
