### ISSUE TITLE
InteractionManager#processInteractive OverOut problem

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4169]
In InteractionManager#processInteractive method interaction are parsed by children order.
https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1039

this can produce some problems.
look at this example where button 1 is added before button 2

test1 
-mouse over first button (text is filled)
-mouse out from first button (text is resetted)
-mouse over second button (text is filled)

test2
-mouse over first button (text is filled)
-mouse over second button (text should be filled but actually is resetted because of mouseout from button1 is triggered after mouseover button2)

test2
-mouse over second button (text is filled)
-mouse over first button (text is filled - work because of children order)

I think that mouseout shuold always be processed before mouseover.

[overTest.zip](https://github.com/pixijs/pixi.js/files/1163191/overTest.zip)

**Comment by AshtonRoute** [comment]
+1. I found the same bug, sometimes events run (over -> out -> over), but sometimes (over -> over -> out), which kinda breaks the logic, so I had to put some workarounds

**Comment by andrewstart** [comment]
Handling the over & out events separately would decrease performance of the interaction manager and possibly have unforeseen side effects from not firing events immediately. In your example, I would suggest tracking what DisplayObject is associated with the text, and in the out event only clear the text if you moused out of the thing currently associated.

**Comment by AshtonRoute** [comment]
@andrewstart 
> I would suggest tracking what DisplayObject is associated with the text, and in the out event only clear the text if you moused out of the thing currently associated.

that's exactly what I'm doing :smiley:
