### ISSUE TITLE
Sprite getLocalBounds Bug

### ISSUE THREAD

**Issue by magig** [pixijs/pixi.js#4175]
Hey guys I just stumbled onto this little bug while copying/overriding some Sprite methods: getLocalBounds incorrectly uses '_anchor._x' to compute 'maxY'.

`this._bounds.maxY = this._texture.orig.height * (1 - this._anchor._x);`

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L360

**Comment by ivanpopelyshev** [comment]
heh, that's fun :)
