### ISSUE TITLE
Graphics.addHole API doesn't work with CanvasRenderer

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#4183]
Found in #4177

It appears that `addHole` does not render correctly for CanvasRenderer.

**WebGL example** (works): https://jsfiddle.net/kr1ha29b/ 👍 
**Canvas example** (broken): https://jsfiddle.net/LLk9nj00/ 👎 

Correct render:

![image](https://user-images.githubusercontent.com/864393/28672911-0fbea41e-72af-11e7-9c5b-e536c878d6b1.png)

**Comment by vdbongard** [comment]
I have found a similar problem but for me the CanvasRenderer seems to render it correctly and not the WebGLRenderer when comparing it to a similar svg. In the SVG it doesn't matter if we draw the small or the large rectangle first, as long as the direction of the inner and outer rectangles are different. The CanvasRenderer behaves the same but the WebGLRenderer renders differently as you can see in my example:

**Small rectangle first**:
**WebGL example (broken)**: [https://jsfiddle.net/kr1ha29b/10/](url)
**Canvas example**: [https://jsfiddle.net/LLk9nj00/6/](url)
**SVG example**: [https://jsfiddle.net/LLk9nj00/7/](url)

**Large rectangle first**:
**WebGL example**: [https://jsfiddle.net/LLk9nj00/9/](url)
**Canvas example**: [https://jsfiddle.net/LLk9nj00/10/](url)
**SVG example**: [https://jsfiddle.net/LLk9nj00/9/](url)

**Comment by anticore** [comment]
Any prediction of when this is going to be fixed?

**Comment by ivanpopelyshev** [comment]
@anticore Any ideas on how to fix it?

**Comment by anticore** [comment]
@ivanpopelyshev Unfortunately, no. I tried solving it but couldn't figure it out.

**Comment by ivanpopelyshev** [comment]
Do you need it for a mask?

**Comment by anticore** [comment]
@ivanpopelyshev Yes. We have a mask that's constructed dynamically by adding holes and we need it to work on both WebGL and Canvas.

**Comment by ivanpopelyshev** [comment]
Well, there's an idea that you have to make outer polygons counter-clockwise and inner clockwise. Let me see the code ...

**Comment by ivanpopelyshev** [comment]
I think I can try to implement that only for masks.

**Comment by bigtimebuddy** [comment]
Fixed by #5202
