### ISSUE TITLE
graphics.generateCanvasTexture() problems

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4187]
I've noticed some issue with this method

1- if I generate a texture and then apply it to a sprite, shapes seems trimmed
![trimmed](https://user-images.githubusercontent.com/15343100/28710787-adabb17c-7385-11e7-8f9f-416d32d17d48.png)

2- if clean, redrawn and regenerate texture, new shape bounds seems that are not correct (see example 2)

[graphics.html.zip](https://github.com/pixijs/pixi.js/files/1182566/graphics.html.zip)

**Comment by ivanpopelyshev** [comment]
Yep, the's an issue. Any idea how to fix that? Graphics getLocalBounds report something wrong, or "generateTexture" fails?

**Comment by lucap86** [comment]
I think that it should be a Graphics.clear issue, it does not correctly calculates localbounds when already been done before.
I've tried to find out a fix but without success
