### ISSUE TITLE
PixiJS testing suite - subsets only?

### ISSUE THREAD

**Issue by parmjitv** [pixijs/pixi.js#4189]
Hello All,

I am a developer interested in contributing to the PixiJS project.  I have a question about the testing suite:

Is it possible to run only a subset of the available tests at one time, and not the entire suite?  For example, if an update is made to the core Circle feature and a new test scenario is added, can we test the Circle aspect alone as:

`floss --path test/core/Circle.js`

... or alternatively, as an `npm run` directive?

I believe the testing suite currently runs through all tests from the top level down, and does not allow for a subset as I have described.  Please correct me if I am wrong?  Thank you!

Cheers,

Parmjit V.

**Comment by englercj** [comment]
Well `npm test` just runs the index js file, which includes all the others (https://github.com/pixijs/pixi.js/blob/dev/package.json#L28).

You could instead just `floss --path test/core/Circle.js` just like you described.

**Comment by bigtimebuddy** [comment]
The other option is with Mocha you can use the "only" API. For instance, describe.only() or it.only() and only those tests will run. Helpful if you're focused on making tests for a particular API.

**Comment by parmjitv** [comment]
Thanks for the prompt replies!  Running the test suite on a subset as I have described results in each test failing with a `ReferenceError: PIXI is not defined` error message, but I expect this was intended by design.

The approach that @bigtimebuddy mentions should be an adequate workaround for testing changes locally, although really the entire test suite should be run regardless.

I really like what I see in this project.  Looking forward to making some contributions!

**Comment by bigtimebuddy** [comment]
Thanks for being willing to help @parmjitv. Let us know if you have any questions. Unit tests are definitely a great place for contributing. One place to identify gaps in the tests is using "npm run coverage". This generates an HTML report which will tell you which classes, methods, lines are run with tests. Here's the latest coverage report on the dev branch: http://pixijs.download/dev/coverage/index.html
