### ISSUE TITLE
[Help Wanted] Missing PIXI.TextStyle documented members

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#4197]
I noticed that none of the members in TextStyle are documented: http://pixijs.download/release/docs/PIXI.TextStyle.html

There are public getters/setters for all the construction options which should be listed as properties. Does anyone want to make a PR for adding these docs?

**Comment by themoonrat** [comment]
I'll sort it

**Comment by bigtimebuddy** [comment]
Thanks @themoonrat
