### ISSUE TITLE
Method is not found

### ISSUE THREAD

**Issue by hyunsooda** [pixijs/pixi.js#4202]
Hello, I'm korean.
I watched your lighting demo and have tried that myself but, "PIXI.display.Layer is not function" said my console.
afterward I reached your official doccument, but not found the method.

http://pixijs.github.io/examples/?v=v4.5.4#/layers/lighting.js

**Comment by themoonrat** [comment]
Pixi display is a plugin, so not part of the core pixi release
https://github.com/pixijs/pixi-display

**Comment by hyunsooda** [comment]
Oh my god! I'm so sorry for my mistake.
I just found that there is a plguin link. 
Thank you.
https://github.com/pixijs/pixi-display/tree/layers
