### ISSUE TITLE
part of tiling sprite getting pixelated on mobile device(webgl)

### ISSUE THREAD

**Issue by ergoposti** [pixijs/pixi.js#4204]
I've ran into quite weird issue with tilingSprite. the more I move the tileposition the more pixelated it gets(also this only happens on mobile devices, on pc it's fine),

example image:
![capture](https://user-images.githubusercontent.com/16805406/28995011-00a99ae0-79e6-11e7-8eaf-4ea318e09544.PNG)
(the white line is part of tile texture)

**Comment by ivanpopelyshev** [comment]
```
PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH;
```

**Comment by ergoposti** [comment]
Thanks, that seems to have fixed the issue.
