### ISSUE TITLE
Spritesheet inside @0.5 spritesheet, Frame does not fit inside the base Texture dimensions

### ISSUE THREAD

**Issue by axldns** [pixijs/pixi.js#4213]
Prior to PIXI **v4.1.1** we were able to put one spritesheet inside another (e.g. bitmap font inside bigger atlas) and use both BitmapText fonts along with other images from the atlas.
 
This applies also for the case where that bigger atlas has "@0.5" in name, used advisedly for some mobile platforms. PNG twice smaller, JSON the same, all contents correctly upscaled by PIXI.

From PIXI **v4.2.1** on, using combined atlases while parent atlas is @0.5 causes either 

- textures misplacement 

- Error: `Texture Error: frame does not fit inside the base Texture dimensions`

I'm attaching minimal source sample exposing the problem for your investigation.

Please advise. 
[pixi4v5bitmapfont.zip](https://github.com/pixijs/pixi.js/files/1208638/pixi4v5bitmapfont.zip)

**Comment by ivanpopelyshev** [comment]
Ok, its a problem because different packers make different output formats. I dont know what to do about that, it really depends on user case.

**Comment by themoonrat** [comment]
Closing as PR submitted fix this
