### ISSUE TITLE
Is it possible to create a mouseover effect on a Graphics line?

### ISSUE THREAD

**Issue by bschnelle** [pixijs/pixi.js#4216]
I've been trying for quite a while to add a `mouseover` event to a `Graphics` object that is just a line between two points, but am having no luck accomplishing it.  I can see that `interactive` must be set to `true` and that `hitArea` is required in certain cases, but `hitArea` doesn't appear to accept lines.

[Example](https://codepen.io/anon/pen/VzzYow?editors=0010)

Is this use case possible with Pixi?

**Comment by gg4u** [comment]
Actually it should, I think you must specifiy the area of hitArea.

I tried with:

l```
line.hitArea = new PIXI.Rectangle(0, 0, 125, 125);

line.on("pointerdown", function (event) {
  console.log("down")
});

line.on("pointerup", function (event) {
  console.log("up")
});

```

...ahem it s not working, don't know exactly why ... :| but this is the way I made stage interactive :)
