### ISSUE TITLE
Rendering multiple Sprites into a single Texture

### ISSUE THREAD

**Issue by xormak** [pixijs/pixi.js#4217]
Hello

My question:
Can i render multiple sprites as a single new texture and if yes, what would be the correct way to do so?

Example: 
1 - stage is filled with 1000 dots.
2 - all 1000 dots should be rendered into a single new texture
3 - new texture should be added to the stage instead of the 1000 single ones

only #2 still gives me a headache

**Comment by englercj** [comment]
Look at `RenderTexture`, you can render anything you want to it then use it as a texture elsewhere.

**Comment by xormak** [comment]
RenderTexture left me with an Error
`
var cont = stage.children[0];
let renderTexture = new PIXI.RenderTexture.create(100, 100);
renderer.render(cont, renderTexture);
`

`WebGL: INVALID_VALUE: texSubImage2D: no pixels`

**Comment by xormak** [comment]
Update: Figured it out. Forgot to give the renderTexture a size big enough to have the sprites be rendered to it properly.
