### ISSUE TITLE
bounds after cacheAsBitmap seem to calculate wrong 

### ISSUE THREAD

**Issue by tengotengo** [pixijs/pixi.js#4220]
Example: (see the console)
https://jsfiddle.net/w4bxh8w6/3/

1) I'm not sure if this is how it's supposed to be but cachingAsBitmap affects bounds after some time, like it's asynchronous.
2) in this particular example scaling cached container results in weird bounds change
3) in my game code caching as bitmap also affects bounds, but even without any scaling, only by changing position of a cached container

**Comment by ivanpopelyshev** [comment]
Fixed in that PR.
