### ISSUE TITLE
[Share] A plugin to use SDF-based rich-text in PixiJS

### ISSUE THREAD

**Issue by Icemic** [pixijs/pixi.js#4225]
Hi, I made a new plugin for PixiJS.

PIXI.Text is pretty good in most situation, but it has some problems to me:

- Stroke and shadow effects are not very good, especially for CJK (Chinese, Japanese, Korean) characters or in 1~2px thickness.
- No support for CJK layout
- No support for rich text (mix multiple style in a line)
- Costly in performance when you want to make a typewriter effect

That's why I wrote pixi-richtext.

Link: https://github.com/avgjs/pixi-richtext

**Any suggestion or contribution is welcomed!** 🎉

### Feature

- Runtime signed distance field algorithm, with LRU cache for 1024 characters
- Better rendering effect
- No font file required, while supporting custom font via `@font-face`
- Full support for CJK languages
- Simple layout using [huozi](https://github.com/Icemic/huozi.js)
- Rich-text support

### Preview

![image](https://user-images.githubusercontent.com/837432/29248168-0c903076-8044-11e7-9125-1fd8b91415f4.png)

```
Rich text parsing time: 2 ms
SDF texture generating time: 286 ms
Convert AST to plain array: 13 ms
layout time: 35 ms
```

**Comment by ivanpopelyshev** [comment]
You have high proficiency regarding pixi code! 

That's one more rich-text plugin for pixi. Btw, I know that @bQvle works on dynamic text plugin in https://github.com/pixijs/pixi-ui, he also made temporary atlas for characters.

I also copied SpriteRenderer to https://github.com/pixijs/pixi-projection lib, but i've made it like a abstract class, I can use multiple shaders with it.

**Comment by Icemic** [comment]
@ivanpopelyshev 

Yeah, I did spend a lot of time reading and understanding PixiJS code.
I know that sdf-text plugin, but it depends on pre-generated fnt file. A fnt format font of CJK characters is usually badly big. So I have to consider run-time generating. 😭 

In addition, copying SpriteRenderer is not a good practice but it seems we have no choice? 
However, I noticed [this proposal](https://github.com/pixijs/pixi.js/issues/4178), which mentioned the problem, will it help solve it?

**Comment by ivanpopelyshev** [comment]
Right now we have no choice, but in next big version (v5) it will be fixed. That proposal is very likely to be accepted, and we have enough experience to implement it.

If you look at https://github.com/pixijs/pixi-ui/blob/master/src/DynamicText/DynamicText.js#L527 , there's runtime atlas, and I gave that algo to @bQvle and soon I'll help him to make it faster.

**Comment by themoonrat** [comment]
Closing this, but thanks for the plugin share!
