### ISSUE TITLE
MS Gothic font is cropped.

### ISSUE THREAD

**Issue by VsevolodZakharov** [pixijs/pixi.js#4228]
Win 7 + Google Chrome. Texts with fontfamily MS Gothic are cropped.

**Comment by bigtimebuddy** [comment]
Try adjusting the TextStyle's "padding" property and see if that helps.

**Comment by VsevolodZakharov** [comment]
Yes. That is what I'm using for now. Just reported for you to know there is such problem. Obviously text metrics are calculated with a mistake.

**Comment by bigtimebuddy** [comment]
Could you provide a screenshot of what it looks like cropped?

**Comment by VsevolodZakharov** [comment]
![screen shot 2017-08-14 at 13 25 44](https://user-images.githubusercontent.com/8831428/29268155-4dbff17a-80f4-11e7-82be-6c7ba45197a0.png)

Left one is "MS Gothic.ttf' imported with @font-face, the right one is embedded MS Gothic. See digits and korean glyphs upper edge.

**Comment by VsevolodZakharov** [comment]
In fact a couple of pixes are cutted.

**Comment by ivanpopelyshev** [comment]
Btw, RpgMaker uses MS Gothic as default. Do you use it?

**Comment by VsevolodZakharov** [comment]
Sorry, don't know about RpgMaker. 
Btw it is pixijs 4.2.2, also the same for 4.5.3

**Comment by ivanpopelyshev** [comment]
Workaround: https://github.com/pixijs/pixi.js/blob/dev/src/core/text/TextMetrics.js#L209 , 

Re-define it in separate js file, or just add it to your app:

```js
PIXI.TextMetrics.measureFont = function() {
  ...
  context.fillText('|MÉq', 0, baseline);
 ...
}
```

Add there some other symbols.

**Comment by bigtimebuddy** [comment]
I would assume the characters we are using to measure might fall short with this particular type face With this approach there are always going to be some fonts that may be cropped and require a little padding. Any ideas for a better metrics test? https://github.com/pixijs/pixi.js/blob/dev/src/core/text/TextMetrics.js#L225

**Comment by VsevolodZakharov** [comment]
AFAIK in some browsers ascent, descent etc. are available explicitly for now . https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics

**Comment by Megabyteceer** [comment]
I noticed that Text starts to crop last letter if letterSpacing is not zero. If set it to non zero, fixed amount of latest letter is always cropped.

**Comment by bigtimebuddy** [comment]
@Megabyteceer could you make a jsfiddle for that issue?

**Comment by Megabyteceer** [comment]
@bigtimebuddy https://jsfiddle.net/Megabyte/7epankmv/1/

**Comment by themoonrat** [comment]
@Megabyteceer This is because of the cyrillic alphabet you are using for your examples. You can use the API provided by https://github.com/pixijs/pixi.js/pull/4550 to customise what is used to measure pieces of text.

Closing this issue as I believe the original issue has been solved. If you need any more help, please open a new issue :)
