### ISSUE TITLE
Debugging performance: handle events properly ( stopPropagation )

### ISSUE THREAD

**Issue by gg4u** [pixijs/pixi.js#4235]
Hi, 
I would like to debug performance of interaction of my app, and see if I am handling events properly.

I have a stage associated with pinch gesture.
Above the stage, I have several sprites with each own its texture.

I would like to capture the event on the stage, and prevent trickling down do the images (pinch is only associated to stage)
I would like to prevent bubble up of events associated to textures (pointertap is only associated to textures).

Each texture is interactive with a pointertap interaction, like:

```
ui.thumbnail.interactive = true;
    ui.thumbnail.buttonMode = true;
    ui.thumbnail.on('pointertap', function(e){
   // do things
}

```

I would like a debrief on how events are handled here VS events on DOM (I was using Hammer.js),

and understand how to properly handle events on pixi (reading here about DOM: https://stackoverflow.com/questions/4616694/what-is-event-bubbling-and-capturing)

and understand how to track or debug if I am doing it correctly :)

Do I have to stopPropagation() ? Is it handled by default on textures ? ...

**Comment by englercj** [comment]
If I actually understand your question, then the answer is: "Yes, stopPropagation will prevent the event from going to any other objects". This is listed in the docs (and source):

https://github.com/pixijs/pixi.js/blob/3031846ba0791b072d1a8b3ef1c699a3f090bd87/src/interaction/InteractionEvent.js#L51-L55

**Comment by gg4u** [comment]
How does propagation works for objects in canvas VS objects in DOM ?
Does stopPropagation for objects apply for both propagating to parent elements and child elements  ?

**Comment by englercj** [comment]
JS has no "objects in canvas". All interaction events in pixi are purely within pixi and have nothing to do with the DOM.

The events in pixi use bubbling, in that it first emits on the element then all parents. in sequence If you call stopPropagation it will not travel any higher up the hierarchy.

In DOM there are multiple event phases (capture & bubble), as well as multiple ways to change the behavior of the event/browser (preventDefault & stopPropagation). Try not to get the two systems confused with eachother. The browser doesn't dispatch any events on the pixi objects, that is just pixi.
