### ISSUE TITLE
Bug in mask in pixi 4.5.4 (not present in 4.5.3)

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#4236]
Mask with graphics have some problems in 4.5.4

try 
https://jsfiddle.net/2z7zbc9h/1/ pixi 4.5.3 (works)
and 
https://jsfiddle.net/z8szbu57/1/ 4.5.4 (doesn't works)

the two examples have the same code.

**Comment by rich-earth** [comment]
Also having a different problem with masks in 4.5.3/4 if it provides any clues...  

A Sprite I'm using as a mask, is created from TextureCache["myShape"] loaded from a Spritesheet and looks fine when add it to stage. 

When I set it as a mask for another container,  the masking works, but the shape of the mask changes to some other area of my spritesheet, like the Sprites texture frame co-ords referencing the baseTexture goes wrong when set as a mask.

**Comment by lucap86** [comment]
It is not a typo, It need for inverse mask
I want red background and black mask

the first drawCircle draw the first circle, the second erase a smaller area of the first one

**Comment by rich-earth** [comment]
AH sorry my bad!  Maybe Graphics drawing has changed,  theres an addHole() on Graphics but only works with drawPolygon I think.

**Comment by jonaswalekvist** [comment]
Whats the status on this, anyone have a clue to whats going on? I have the exact same problem using 4.5.5. My nice circle wipe effect is broken :(

**Comment by jonaswalekvist** [comment]
After some reading in the change log this popped up as an interesting candidate to why we experience a problem: Fixed issues with overlapping shapes in masks for WebGL #4164 

I do agree that the above mentioned fix is the correct approach (canvas and webgl works the same way), though it would be awesome to add this as a optional feature that can be turned on and off. It is super useful for making inverted masks. (And btw isn't this, behavior pre #4164 the default behavior when drawing with WebGL anyway?)

**Comment by ivanpopelyshev** [comment]
@jonaswalekvist i made special webgl mode for that effect: http://www.html5gamedevs.com/topic/31803-scratch-card-effect/?tab=comments#comment-182673

It does not depend on masks, only renderTextures.
