### ISSUE TITLE
how to update text style dynamically

### ISSUE THREAD

**Issue by gg4u** [pixijs/pixi.js#4237]
I would like to update rendering of text labels.
Say, fontSize will change up to some object properties.

I don't want to use scale, I prefer to use fontSize and update directly all style properties I want (e.g. color, shadow, etc.)

How to access it?
I tried with:

`node.label.style._fontSize = number`

but does not get updated, while

`node.label.scale.set( number );` does

how to programmatically access text style properties, once they have been initilised? 

e.g. for updating textures I could attach a listener to a new image, and once updated, run a function.
How could I do uptade styles for text labels?

**Comment by bigtimebuddy** [comment]
Text already supports this, just change the [`fontSize` property](http://pixijs.download/dev/docs/PIXI.TextStyle.html#fontSize) on TextStyle.

```js
var text = new PIXI.Text();
text.style.fontSize = 10;
```

Also related: https://pixijs.github.io/pixi-text-style/

**Comment by gg4u** [comment]
👍
