### ISSUE TITLE
Custom Image Cursor for Containers

### ISSUE THREAD

**Issue by ArronFerguson** [pixijs/pixi.js#4238]
I don't see any ability to set a custom cursor image other than to do this:

```
let c1 = new PIXI.Container();
c1.interactive = true;
c1.buttonMode = true;
c1..defaultCursor = "url('./img/cartoon-pointer-96x96.png'), auto";
```

This works to display a custom image on mouse over of the container but is a poor choice for several reasons:
- it doesn't use any app code that may be performing loading and so this image may or may not be ready as the app loads
- cannot set the anchor point within the image (so the image for the cursor can't be set to a particular spot within the image)
- the image cannot be scaled if one is honoring a responsive WebGL environment
- cannot apply any shaders on the cursor

I suppose this isn't so much of an issue as it is for a RFE since it is clearly not a show stopper. But it really would be nice to have since it would allow an app to maintain a consistent look-and-feel for the app cursor(s) as well.

:)

Arron

**Comment by andrewstart** [comment]
Given that your example has `defaultCursor`, I am guessing that you are using an older version of Pixi. Since version 4.3.0, you would set cursor modes globally, and then an individual container would be set up to use a specific mode:
```javascript
const interaction = myRenderer.plugins.interaction;
interaction.cursorStyles["pointer"] = "url('./img/cartoon-pointer-96x96.png'), auto";
let c1 = new PIXI.Container();
c1.interactive = true;
c1.cursor = "pointer";
```
However, you can also use callbacks instead of CSS:
```javascript
const cursor = new PIXI.Sprite();
const interaction = myRenderer.plugins.interaction;
interaction.cursorStyles["default"] = (mode) => {
    //mode parameter is the cursor mode, giving you the option of one callback for all mode changes with a switch statement, or separate callbacks for each mode
    cursor.texture = PIXI.Texture.fromFrame("defaultCursor");
}
interaction.cursorStyles["attack"] = (mode) => {
    cursor.texture = PIXI.Texture.fromFrame("attackCursor");
}
interaction.on("pointerover", () => {
    //mouse is now on stage
    cursor.visible = true;
});
interaction.on("pointerout", () => {
    //mouse left stage
    cursor.visible = false;
});
interaction.on("pointermove", (event) => {
    //update cursor position on each move
    cursor.position.set(event.data.global);
});
let c1 = new PIXI.Container();
c1.interactive = true;
c1.cursor = "attack";
```

**Comment by ArronFerguson** [comment]
Andrew, thanks for your response and your time. I was using Pixi version 4.3.4 but there is no such property cursorStyles of the interaction object of this version of Pixi and so this causes an error.

Just downloaded 4.5.4 and there is that property (so no errors) but when I assign my container's cursor to anything other than 'default', 'wait', or any of the predefined cursor types, no image shows up. I've tried:

```
cursor.texture = sprites.arron.texture;
cursor.texture = PIXI.Texture.fromImage("./img/cartoon-pointer-96x96.png");
```

No errors, but no image used as a cursor either. Did a console.log and the texture seems to be there and is loaded. Is there any sort of requirements for the image used as a cursor? A certain set of dimensions? File format? Transparency, no transparency? Indexed vs. True color?

**Comment by ivanpopelyshev** [comment]
@ArronFerguson you forgot to add cursor to the stage, aren't you? 😼 Or may be you added to the stage but changed stage position/scale, and it affected cursor position. 

Code that is posted by authors is often incomplete, this world is cruel :(

**Comment by ArronFerguson** [comment]
@ivanpopelyshev, thanks for the reminder. So what I have thus far is this:

```
        var cursor = null;
        var interaction = null;
    ...
        interaction = renderer.plugins.interaction;
        cursor = new PIXI.Sprite();
        cursor.anchor = {x: 0.35, y: 0.25}; // position specific to where the actual cursor point is
        stage.addChild(cursor);

        interaction.cursorStyles["cartoonPtr"] = (mode) => {
            cursor.texture = sprites.cartoonPointer.texture;
        }

        interaction.on("pointerover", () => {
            cursor.visible = true;
        });
        interaction.on("pointerout", () => {
            cursor.visible = false;
        });
        interaction.on("pointermove", (event) => {
            cursor.position = event.data.global;
        });

        aboutTextContainer = new PIXI.Container();
        aboutTextContainer.interactive = true;
        aboutTextContainer.buttonMode = true;
        aboutTextContainer.cursor = "cartoonPtr";
```


So I do get the sprite that follows the actual operating system mouse cursor (yay), but the system mouse cursor does not disappear, it is overlaid on top of the sprite image that I chose. Any idea how to turn that off?

**Comment by andrewstart** [comment]
Whoops, forgot to mention that in my example of all the hooks you'd need to set up your own cursor. You'll need to do this bit once, as the interaction manager will leave the canvas element's CSS alone if you override all cursor modes that are used (default ones are `"default"` and `"pointer"`).
```javascript
//myView is your HTMLCanvasElement
myView.style.cursor = "none";
```

Also, you don't need to use `buttonMode = true` - it just sets `cursor` to `"pointer"` for backwards compatibility.

**Comment by ArronFerguson** [comment]
@andrewstart, @ivanpopelyshev,

That is what I needed. I now have custom mouse cursors! Thank you very much for your time gentlemen, I really appreciate that.


Arron

**Comment by ivanpopelyshev** [comment]
@andrewstart wanna make an example for https://github.com/pixijs/examples out of it?

**Comment by ArronFerguson** [comment]
Yes! I will do that! I'll put something together. Where/who should I send it to?

**Comment by ivanpopelyshev** [comment]
You can submit PR (https://help.github.com/articles/creating-a-pull-request/) to https://github.com/pixijs/examples, or just give us code and resources for it in zip-file.

We'll make it anyway, that's not a rare case.

**Comment by bigtimebuddy** [comment]
Thanks @ArronFerguson for helping 👍

**Comment by ArronFerguson** [comment]
Sorry to do this, but I think there's some problems with the event handling. I've noticed a few glitches such as:
- mouse off a sprite doesn't seem to allow setting of the cursor to something else (the event is firing)
- clicking quickly, events are ignored - sometimes for long periods of time (e.g., two seconds)
- clicking quickly sometimes causes the system cursor to appear and can't be removed unless a mouse off of the stage and then back on again
- clicking quickly sometimes causes the sprite that is used as an image to disappear for a half second
- mouse up and outside of a sprite also does not seem to respond to setting the cursor (either the sprite's cursor or the stage's cursor)

The following code is what I used to make this happen. Unless I'm doing something wrong I think there may be some issues.

```
var renderer = PIXI.autoDetectRenderer(
    window.innerWidth, window.innerHeight,
    {antialias: true, transparent: false, resolution: 1}
);
document.body.appendChild(renderer.view);


if(renderer instanceof PIXI.CanvasRenderer) {
    //canvas renderer
    console.log("Canvas ONLY!");
} else {
    //webgl renderer
    console.log("Doing WebGL, all is good.");
}

renderer.view.style.position = "absolute";
renderer.view.style.display = "block";
renderer.autoResize = true;
renderer.resize(window.innerWidth, window.innerHeight);
renderer.backgroundColor = 0xe1ab15;

var stage = new PIXI.Container();
stage.interactive = true;

var textOptions = {
    font: "bold 22pt Arial",
    fill: '#3498db',
    align: 'center',
    stroke: '#34495e',
    letterSpacing: 1.5,
    strokeThickness: 2,
    dropShadow: true,
    dropShadowColor: "#000000",
    dropShadowDistance: 6,
    dropShadowAlpha: 0.12,
    wordWrap: true,
    wordWrapWidth: 400,
    dropShadowBlur: 10,
    lineJoin: 'round'
}

var text = new PIXI.Text("Example custom mouse cursor", textOptions);
text.position = {x: 80, y: 80};
stage.addChild(text);

var goofyGuy = PIXI.Sprite.fromImage("./img/arron-avatar-colorized-MED.png");
goofyGuy.position = {x: 150, y: 180};
goofyGuy.scale = {x: 0.5, y: 0.5};
goofyGuy.interactive = true;
stage.addChild(goofyGuy);

var handOpen = PIXI.Sprite.fromImage("./img/cursor-can-select.png");
var handPoint = PIXI.Sprite.fromImage("./img/cursor-pointer.png");
var handGrab = PIXI.Sprite.fromImage("./img/cursor-grab.png");
handOpen.position = handPoint.position = handGrab.position = {x: -999, y: -999};
handOpen.scale = handPoint.scale = handGrab.scale = {x: 0.5, y: 0.5};
handOpen.anchor = handPoint.anchor = handGrab.anchor = {x: 0.35, y: 0.25};
stage.addChild(handOpen);
stage.addChild(handPoint);
stage.addChild(handGrab);


var cursor = handPoint;

var interaction = renderer.plugins.interaction;
interaction.cursorStyles["handPoint"] = (mode) => {
    cursor.texture = handPoint.texture;
}

interaction.cursorStyles["handGrab"] = (mode) => {
    cursor.texture = handGrab.texture;
}

interaction.cursorStyles["handOpen"] = (mode) => {
    cursor.texture = handOpen.texture;
}

interaction.on("mouseover", () => {
    //mouse is now on stage
    cursor.visible = true;
});

interaction.on("mouseout", () => {
    //mouse left stage
    cursor.visible = false;
});

interaction.on("mousemove", (event) => {
    cursor.position = event.data.global;
});

stage.on('mouseout', onMouseStage)
     .on('mouseover', onMouseStage)
     .on('mousedown', onMouseStage)
     .on('mouseup', onMouseStage)
     .on('mouseupoutside', onMouseStage);

function onMouseStage(event) {
    stage.cursor = "none";
}

goofyGuy.on('mouseout', onMouseOffGoofy)
        .on('mouseover', onMouseOverGoofy)
        .on('mousedown', onMouseDownGoofy)
        .on('mouseup', onMouseUpGoofy)
        .on('mouseupoutside', onMouseUpOutsideGoofy);


function onMouseOverGoofy(event) {
    //console.log("over");
    goofyGuy.cursor = "handOpen";
}

function onMouseOffGoofy(event) {
    console.log("off");
    // neither of these work :(
    goofyGuy.cursor = "handPoint";
    stage.cursor = "handPoint";
}

function onMouseDownGoofy(event) {
    goofyGuy.cursor = "handGrab";
}

function onMouseUpGoofy(event) {
    goofyGuy.cursor = "handOpen";
}

function onMouseUpOutsideGoofy(event) {
    // doesn't work???
    //goofyGuy.cursor = "handOpen";
}

// render loop
function update() {
    renderer.render(stage);
    requestAnimationFrame(update);
}
update();
```

HTML is:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Custom Cursor Example</title>
    <meta charset="utf-8"/>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
    <style>
      @import url(https://fonts.googleapis.com/css?family=Hind);

      html, body{
        font-family: 'Hind', sans-serif;
        margin: 0px;
        padding: 0px;
      }
    </style>
  </head>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="js/pixi.min.js"></script>
    <script src="js/main.js"></script>
    <script>
    /*<![CDATA[*/
        $(document).ready(function() {
        });
    /*]]>*/
    </script>

  </body>
</html>
```

**Comment by ivanpopelyshev** [comment]
Wow, thank you! Yep, we'll look how to improve that.

**Comment by ArronFerguson** [comment]
Thank you! :)

**Comment by ArronFerguson** [comment]
@themoonrat which branch would you like me to check?

**Comment by themoonrat** [comment]
The latest of v4, please :)
https://pixijs.download/dev/pixi.js

**Comment by ArronFerguson** [comment]
Unfortunately not working. Things that don't work (from code from the Aug 22, 2017) post:
- cursor never changes back to the pointer hand (so onMouseOffGoofy function lines don't work)
- sometimes clicking on the goofy guy causes the sprite cursor to completely disappear
- sometimes the system cursor shows up

The intermittent behavior is hard to pin point the cause of. It doesn't appear to be too slow, too fast, or any particular spot on the sprite.

I'm initially tried in Chrome Version 67.0.3396.99 (Official Build) (32-bit), Windows 10 Enterprise, but then also tried with Microsoft Edge 40.15063.674.0 and Firefox 60.0.2 (64-bit) - all with the same sorts of intermittent behaviors however Edge seemed to have the most trouble with switching between the different images based on mouse events (i.e., so didn't update the images with, for example, a mouse click, a mouse off, etc.).

**Comment by ArronFerguson** [comment]
Andrew,

I had been asked if it fixed something, I said it doesn't, you can close this, no big deal. 

If mobile first (and foremost) is the perspective, then I wouldn't worry about this. If, however, the Pixi API should support desktop web apps, then I'd look into resolving this.

As far as comparing this to how the DOM handles events, I think it's an apples-to-oranges comparsion - there's really no relation. But anyways, close this down, like I say, no worries.
