### ISSUE TITLE
Add the number of draw calls

### ISSUE THREAD

**Issue by tleunen** [pixijs/pixi.js#424]
It could be nice to have the number of draw calls the stage uses to draw the entire scene.

A variable inside PIXI.Stage or something which contains the number of draw calls will be a nice addition to know how bad our app is :D

This is just a reminder to not forget about it as @GoodBoyDigital said it was a good idea ;) https://twitter.com/Doormat23/status/406055526012059649

**Comment by fanjules** [comment]
Has this moved?  I can't find anything called .drawCount in the dev branch pixi.js
