### ISSUE TITLE
about mesh demos.

### ISSUE THREAD

**Issue by hyunsooda** [pixijs/pixi.js#4241]
Hello, I'm korean student.

I had seen mesh which provided in your engine and it was beautiful and  I had would like to watch about example  using it, but can't find it.
This class seems be in need of math experience, therefore I hope to watch it.

 Do you know  where be able to watch demo or example by any chance?

**Comment by englercj** [comment]
https://pixijs.github.io/examples/#/basics/textured-mesh.js
https://pixijs.github.io/examples/#/demos/strip-demo.js

**Comment by hyunsooda** [comment]
Thanks for answer.
I had already watched example you indicated. 
It is limited number of examples.
My math experience so poor that I would like to watch another exmaple.

**Comment by ivanpopelyshev** [comment]
What exactly do you have trouble with?

**Comment by finscn** [comment]
I still hope the new mesh (https://github.com/pixijs/pixi.js/pull/3842) could be include PIXI 4.x.

The 5.x is waited too long.

**Comment by hyunsooda** [comment]
I had used PIXI.mesh.Rope for hours, by the way, vertices(points) must be horizontally straight line. otherwise I found that image is broken.

I has watched internal code.  That seems relevant to motion that control vertices of four pieces, but I'm not sure the reason of broken image, unless make to straight line.

example)
for(let i=0; i<10; i++) {
  points.push(new PIXI.Point(i*10,0)); // not damage
  points.push(new PIXI.Point(i*10, (i%2===0) ? 100 : - 100); //  damage to image
}

**Comment by hyunsooda** [comment]
well... What I indicated above will seems probably to use PIXI.mesh.Mesh. right?
I also had seen official doc, but I was not understand parameters.... 
I searched parameters on google, but there are only somthing which related to usage in unity.
Do you know where see them?

**Comment by ivanpopelyshev** [comment]
http://learningwebgl.com/blog/ Mesh = vertices + indices.

**Comment by hyunsooda** [comment]
Thanks for answer. but I'm not able to find material about mesh and is mesh a technology of webgl?
if so, what is a masking example uploaded your site ? Is masking example also not part of mesh?

**Comment by VCtaiwan** [comment]
If u want to bend or animated the mesh.texture
Here is the example below:
https://codepen.io/vccodepen/pen/qVGwRo

U can update each points.x/y to do everything u want with Tweenmax(GSAP)
