### ISSUE TITLE
I've an issue with scale, renderer or roundpixel

### ISSUE THREAD

**Issue by Dosseum** [pixijs/pixi.js#4242]
Hello ! I created an online game few months ago using pixi.js, everything is ok, PIXIJS is really strong (for the first version of my game i used easeljs and the performance was really bad)

But i've got a problem since the beginning and i really want to end this problem.

The problem is that all of my sprites, text, graphics become blur depending on the position of them.

For example when my main character is on a specific spot (in my game), the sprite of my character can be clear, but on other spot it can be blur, i thought it was a problem with rounding pixel between the background of the game and the sprite character, but even with a bubble of text (which follow the character when he talk, it's a black text on white bacrkground) it has the same problem.

I tried many many thing, like putting true, false to roundpixel, using different kind of scaling (NEAREST, etc...), using scale x2, x1

But i've got always the same thing, to "fix" the problem with the text, i used resolution: 2 but well the sprite got blurry (that's normal because of resolution 2), but normally everything should be nice with resolution: 1 (clear text and clear sprite) and no, it's always blurry or clear depending on the position x/y.

(I didn't have this problem with easeljs)
![texteproblem](https://user-images.githubusercontent.com/25887041/29498578-ca3cc15a-85ff-11e7-9666-476392bcbe94.png)

I thought using the last version of pixi.js would fix the problem but no :/

So now i'm creating this thread and i hope someone could help !

I join a picture of the same text in two different position (i didn't change anything, just the x and the y)

Thank you for reading !

**Comment by ivanpopelyshev** [comment]
Do you use anchor 0.5? Then that's solution:

```
Sprite.prototype.centerMe = function() {
   var orig = this.texture.orig;
   this.anchor.ste( Math.floor(orig.width / 2) / orig.width, Math.floor(orig.height / 2) / orig.height);
}
```

**Comment by Dosseum** [comment]
Hello ! 
Thanks for the reply, well i use anchor = 0 and scale 1, i tried to do .centerMe() on all of my sprite, but it doesn't work :/  (and it changed the position of some sprite but that's normal if we change the anchor)

You had some blurry thing like that ?

**Comment by ivanpopelyshev** [comment]
My solution was for anchor =0.5 which is not your case. Also it requires to call updateText() before it, i forgot about that ;)

I had many blurry things while i coded the game. There are many solutions. I dont know how to determine what's yours, unless you make a fiddle, may be? :)

**Comment by Dosseum** [comment]
Oh ok, that's why ! But thanks !
So this kind of "blurry" problem is recurring

I don't know if i could make a fiddle because i use a lot of ressources like image, etc.. and my project used websocket, but i will try to "cut"

I will try to make a fiddle and editing this post by posting the fiddle

**Comment by Dosseum** [comment]
OK ! I found the problem, i'm really idiot.. 
Really thanks to you Ivan, because you reply to me, and because when you ask me to make a fiddle i was cutting some code, and when i removed the CSS, everything became fine.
I had a problem for a long time, just because my canvas was "width 608" and the CSS of the canvas "width 606", that explains the blurry thing.

Thank you for helping me !
