### ISSUE TITLE
toLocal and updateTransform understanding help

### ISSUE THREAD

**Issue by stevenalanstark** [pixijs/pixi.js#4247]
Hello,

I am unsure if this is a bug or if this is a lack of understanding on my part. 

When I call `toLocal`, it will effect future `toLocal` calls inversely, but only after `updateTransform` has been called. 

note: yes I an using a point to calculate dimensions, but that should be fine shouldn't it?

note 2: I have already scaled the scene down and maintained aspect ratio with `renderer.resize` and `stage.scale.set`

Take a look at this example:

```
        console.log( "SET 1 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}, false, false, true).x );
        console.log(`ROOT X IS ${this.root.x}`);
        this.root.updateTransform();

        console.log( "SET 2 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}, false, false, true).x );
        console.log(`ROOT X IS ${this.root.x}`);
        this.root.updateTransform();

        console.log( "SET 3 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}, false, false, true).x );
        console.log(`ROOT X IS ${this.root.x}`);
        this.root.updateTransform();
```
will log: 
```
SET 1 
ROOT X IS 0
SET 2 
ROOT X IS 133
SET 3 
ROOT X IS 0
```

however, this: 

```
        console.log( "SET 1 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}, false, false, true).x );
        console.log(`ROOT X IS ${this.root.x}`);

        console.log( "SET 2 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}, false, false, true).x );
        console.log(`ROOT X IS ${this.root.x}`);

        console.log( "SET 3 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}, false, false, true).x );
        console.log(`ROOT X IS ${this.root.x}`);
```
will log: 
```
SET 1 
ROOT X IS 0
SET 2 
ROOT X IS 0
SET 3 
ROOT X IS 0
```
however, when something else later does run updateTransform, then the position issue happens again.

is this a bug, or is this me?

What I am trying to do is consistently center the root clip when the screen is resized. It works the first time but fails the second.

version 4.5.4

If it is a bug, could it be because the toLocal and toGlobal methods are referencing the instance of the transformation matrix and applying math to it, mutating the referenced object? [](https://github.com/pixijs/pixi.js/blob/dev/src/core/display/DisplayObject.js#L472)

**Comment by ivanpopelyshev** [comment]
Where did you get "false", "false", "true" list of params? That "true" corresponds to "skipUpdate" param.

position (x,y), scale, rotation are first-class citizens of PIXI

transform , toLocal, toGlobal, bounds are second, they are calculated lazily, toLocal and toGlobal are calling "_recursivePostUpdateTransform" to check if matrices need to be updated.

When you ask toLocal ignore the changes and just roll with current data it has, well, of course it shows 0,0,0.

**Comment by stevenalanstark** [comment]
the false false true was in there to skip the update transform portions in `toLocal`, just to better illustrate the issue by calling `updateTransform` instead. The issues are the same without those parameters, however the order of the colsole logs does change depending on where and when the updates are called

what I am trying to show is that x is bouncing it's values back and forth, even though `toLocal` params are not changing

**Comment by stevenalanstark** [comment]
new example for you: 

```

        console.log( "SET 1 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}).x );
        console.log(`ROOT X IS ${this.root.x}`);

        console.log( "SET 2 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}).x );
        console.log(`ROOT X IS ${this.root.x}`);

        console.log( "SET 3 ");
        this.root.x = Math.floor( this.root.toLocal({x:300, y:0}).x );
        console.log(`ROOT X IS ${this.root.x}`);
```

logs: 

```
SET 1 
ROOT X IS 0
SET 2 
ROOT X IS 133
SET 3 
ROOT X IS 0
```

**Comment by ivanpopelyshev** [comment]
If scale.x is negative then its correct ;)

**Comment by ivanpopelyshev** [comment]
I dont even understand why are you using toLocal here.

Though I'm happy to help, we'll get one more person to understand transforms after that ^_^

**Comment by stevenalanstark** [comment]
Thank you so much, I am assuming this is to do with my understanding. Understanding transforms would be great!

A bit of background first.

This project is using pixi-animate-extension and pixi-animate to export FLA's into assets. The main stage is 800 * 600, and it's being targeted on mobile devices in landscape mode only.

The canvas, and container div, takes up 100% of the screen, and overflow is hidden. 

In portrait is displays 'please rotate your device' with the canvas visibility set to none, and in landscape the canvas is visible.

In some use cases, the address bar in the browser is shown, and it's not possible to hide it. When this happens, the height of the screen is smaller. After a user action is able to remove the bar again, the resizing of the screen changes the dimensions of the canvas and it needs to be resized again. Without the resizing, the game is distorted.

I am listening to the window reload event, and this is where I am resizing the canvas.

my resize code looks like: 

```
// aspect ratio
        let aspect = 4/3;
        let width = window.innerWidth;
        let height = window.innerHeight;
        if(width > height * aspect) {
            width = height*aspect;
        } else {
            height = width*aspect;
        }

        this.scene.renderer.resize(800 * window.devicePixelRatio, 600 * window.devicePixelRatio);
        if( setScale ) {
            this.scene.stage.scale.set(width/this.innerWidth * window.devicePixelRatio, height/window.innerHeight * window.devicePixelRatio);
        }
```


and this scales it down very nice, but the game is on the left side of the screen. So now I need to center it, and this gives me a perfect center... the first time: 

```
        this.canvasStage.className = "hide"; //I do not want the canvas to accidentally change window.innerWidth

            let rendererWidth = this.scene.renderer.width;
            let rootWidth = this.root.toGlobal({x:this.root.width, y:0}).x;
            let diff = rendererWidth - rootWidth;
            this.root.x = this.root.toLocal({x:diff / 2, y:0}).x;

        this.canvasStage.className = "";
```

I don't like that I am abusing .toLocal and .toGlobal here, and that tells me I am likely doing something wrong, but I will explain my reasoning.

We have a few sets of positions to consider: ( I'm making up names here )

DOM space : This is where the window's innerWidth and innerHeight are coming from

World space: This is the position with all the transforms of the parent chain applied to dive a calculated 'global' world space.

Designed space: This is the layout according to the original 800 x 600 dimensions of the layout, and what all instances' .x and .y positions will be using. 



If this is a bug, I think it has to do with this line: [https://github.com/pixijs/pixi.js/blob/dev/src/core/display/DisplayObject.js#L332](https://github.com/pixijs/pixi.js/blob/dev/src/core/display/DisplayObject.js#L332)

the getter for the worldTransform is passing a reference, but then you're running the applyInverse function, mutating the worldTransform in the process ( I assume ). My thinking is that this could result in the ping pong of the x value due to using the inverse.




because the .toLocal method, run using the same "design space" or "DOM space" as an input value, produces different results each time.

**Comment by ivanpopelyshev** [comment]
```
var screen = renderer.screen; //is innerWidth, innerHeight
var screen_that_i_want = ...;

container.pivot.set(screen.width/2, screen.height/2);
container.position.set(screen_that_i_want.width/2, screen_that_i_want.height/2);
```

**Comment by stevenalanstark** [comment]
well thank you, I was able to get it to center with that approcah: 

```
        this.root.scale.set(1,1);
        this.root.pivot.set(this.root.width/2, 0);
        this.root.x = this.scene.stage.width * this.pixelDensity / 2;
        this.root.scale.set(width/this.origInnerWidth * this.pixelDensity, height/window.innerHeight * this.pixelDensity);
```

This does feel like cheating a little to me, as knowing the px from the left is cleaner and makes it easier to snap to whole pixels.

I am still curious about how to calculate that, but I am happy that my problem was solved.

Also, I had problems getting this to work when I was scaling the stage, but scaling the root container worked.

**Comment by ivanpopelyshev** [comment]
Please do not use "width" and "height" of container, its calculated based on children positions.

**Comment by stevenalanstark** [comment]
that's very good to know, thank you! 👍
