### ISSUE TITLE
PIXI.filters.DisplacementFilter Texture Not Repeating - Even with PIXI.WRAP_MODES.REPEAT

### ISSUE THREAD

**Issue by ArronFerguson** [pixijs/pixi.js#4248]
I came across a couple of example posts that had suggested that setting a texture's baseTexture wrapMode to PIXI.WRAP_MODES.REPEAT but this does not seem to work for me using Pixi 4.5.4. What I've tried:

Couple of things:

1. splat is a splat image that will have the displacement filter
2. splatDisplacement is the displacement image used to warp the splat image

```
// 'sprites' is an array of images that were successfully loaded
sprites.splat.texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;  // nope
sprites.splatDisplacement.texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;  // nope

splatDisplacementSprite =
            new PIXI.Sprite(sprites.splatDisplacement.texture);
splatDisplacementSprite.texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT; // nope
splatSprite.texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT; // nope

splatDisplacementFilter =
            new PIXI.filters.DisplacementFilter(splatDisplacementSprite);
splatDisplacementFilter.map.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT // nope
```
I've tried all of these individually, and then uncommented all of them to see if any combination has an affect.

Animation loop has this in it:

```
        if(splatDisplacementSprite) {
            splatDisplacementSprite.x += 2;
            splatDisplacementSprite.y += 2;
        }
```
The example for v4.x of Pixi doesn't show an example where the texture has to repeat and unfortunately I cannot find any other docs or bugs reports that might suggest what, if anything, that I am doing wrong.

Any help, greatly appreciated.

**Comment by ivanpopelyshev** [comment]
Yeah, I forgot to say in https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters#extra-texture-mapped-matrix , that texture has to be power-of-two size. Because OpenGL, WebGL and all that computer graphics stuff.

**Comment by ArronFerguson** [comment]
Thanks for the reply  @ivanpopelyshev . I set both images to powers of two (256x256, and 512x512) respectively but no change. :/

Not sure what else.

**Comment by ivanpopelyshev** [comment]
That applies only the one that wrapped (displacement). If if doesnt work, that means you somehow already uploaded it to GPU, and it wasn't wrapped. Make a fiddle and i'll fix it.

**Comment by majman** [comment]
@ivanpopelyshev I'm having the same issue (i think). Here's a super basic fiddle:
https://jsfiddle.net/9mkpmced/

**Comment by ivanpopelyshev** [comment]
@majman that's not the same issue. DisplacementFilter uses texture as an input, while in your case there's 
no extra input texture in shader. 

Imagine that you add more stuff in that sprite, how do you think filter will handle it? First it renders whole container into pooled FrameBuffer which does not have any REPEAT's on texture, and it even can be different size,

**Comment by ivanpopelyshev** [comment]
@majman You can describe what do you want to do in separate issue, and I'll help you to use different things for it :)

**Comment by ArronFerguson** [comment]
@ivanpopelyshev  hmm....created an isolated example and it works fine. I'm going to have to see if it has something to do with the loader or something else. I'll close this.

Thanks for your help and sorry to be a pain. :)

**Comment by ivanpopelyshev** [comment]
About preloading texture, there is a bug : even if you use `renderer.textureManager.updateTexture(myTex)` it wont rewrite wrap_mode if the texture is already uploaded :( so be sure that you change wrapmode before you use "prepare" stuff

**Comment by ArronFerguson** [comment]
Ivan,

Solved it. It was two things: 
1) The loader and;
2) #$@&%*! Chrome cached the image despite shift-reloading the page probably three dozen times (I had resaved the image as a power of 2 ... should have renamed it)
