### ISSUE TITLE
Unable to interact when canvas touch-action set to none 

### ISSUE THREAD

**Issue by akhnaz** [pixijs/pixi.js#4250]
In Pixi version 4.5.2:
> If TouchEvents are supported, use those instead of PointerEvents for touch based events 

so sad, it breaks our app (unable to upgrade to version 4.5+) because we disabled the touch-action.
`canvas.setAttribute('touch-action', 'none');`

FYI, we used Pointer Events Polyfill, https://github.com/jquery/PEP so we can just listen to pointer event instead of Mouse or Touch.

Maybe u can also check for `touch-action` attribute of the canvas before deciding TouchEvents or PointerEvents?

**Comment by themoonrat** [comment]
touch-action shouldn't be effecting anything.
Go to the examples page
https://pixijs.github.io/examples/#/demos/interactivity.js
look at the css of the canvas being used.... it has 
touch-action: none
and that works in all the browsers

I think the problem may lie with the polyfill you are using conflicting with PIXI.

**Comment by akhnaz** [comment]
Thank you. Maybe i need to find another solution.

**Comment by akhnaz** [comment]
For who ever read this:

The error is due to i am checking `isPrimary`, because TouchEvent does not have that, only PointerEvent.
