### ISSUE TITLE
OffscreenCanvas is already here

### ISSUE THREAD

**Issue by Kamil93** [pixijs/pixi.js#4252]
Hello

Latest version of Chrome and Firefox has full support for OffscreenCanvas - enabled by default. :D

Maybe it is time to implement mechanism that lead us to use Pixi inside WebWorker?
Should be easy as pie.

Greets

**Comment by englercj** [comment]
This almost certainly will not happen for v4, though it should be possible for someone to write a plugin for v5.

If you're up to it, please feel free to [write a proposal](https://github.com/pixijs/pixi.js/wiki/v5-How-to-Write-a-Proposal) that describes the technical documentation on how this feature would be implemented.

**Comment by themoonrat** [comment]
Closing this one down as we'll track this request in https://github.com/pixijs/pixi.js/issues/4538
