### ISSUE TITLE
Unable to wrap texture in custom shader

### ISSUE THREAD

**Issue by majman** [pixijs/pixi.js#4253]
I'm trying to do something that is probably very basic, and assume I'm missing something obvious. 

Here is a fiddle with a reduced use case: https://jsfiddle.net/majman/9mkpmced/1/

My expectation is that the texture would repeat to fill `mainContainer` width & height. 
I created a super simple shadertoy example of the same idea, where the texture repeats to fill the canvas. 

https://www.shadertoy.com/view/XtfcRN

/cc  @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
Yep, lets continue here. You cant use it in filter, because filter uses temporary framebuffer that cant be controlled from outside.

Please look at this thing: https://github.com/pixijs/pixi-plugin-example

**Comment by ivanpopelyshev** [comment]
btw, i love shadertoy. I found this thing AFTER i made perspective demo (http://pixijs.github.io/examples/#/projection/quad-bi.js), and I found errors in Inigo's code: https://shadertoy.com/view/lsBSDm

**Comment by majman** [comment]
Ah - ok, that makes sense. Will dig into the plugin example and see what I can figure out. 

And yes - Inigo is pretty much a shader-god :) 

I aspire to understand 0.01% of his stuff. One day!

**Comment by ivanpopelyshev** [comment]
If you need batched version, you can take one from pixi-projection. But that's only if you need 1000 of objects on screen running your shader.
