### ISSUE TITLE
npm install missing lib and dist

### ISSUE THREAD

**Issue by ddennis** [pixijs/pixi.js#4258]
Hi 
When doing **npm install pixi.js** the ***dist*** and ***lib*** folders are missing.
I been trying for the last hour, also tried ***npm cache clean***

I also tried installing directly from the github url, same result.

    npm i https://github.com/pixijs/pixi.js -D

/Dennis

**Comment by bigtimebuddy** [comment]
Unfortunately you cannot install Pixi.js directly from the repo we do not commit build files. Just do 'npm i pixi.js -D'

**Comment by ddennis** [comment]
Hi 
I tried that multiple times, but i just did a clean install in another directory and everything works.
Sorry - for wasting your time but was pulling my hair out.

Thanks again.
/Dennis

**Comment by ivanpopelyshev** [comment]
@ddennis its ok ;)

**Comment by bigtimebuddy** [comment]
No worries @ddenis! Happens to the best of us.
