### ISSUE TITLE
Texture.fromCanvas() doesn't update when called more than once and is always linked

### ISSUE THREAD

**Issue by DennisSmolek** [pixijs/pixi.js#4259]
Hey guys, 

I'm building a pixi based image/content editor and using [quill.js](https://quilljs.com/) as my text editor.

What I do is position the editor directly over a rectangle object when you open it, then you type/make changes and when you off-click it fires to a hidden [HTML2Canvas](html2canvas.hertzen.com) that renders a canvas image of the html.

I Inject that image into pixi in the rectangle and BAM it's perfect right in place. 

 I was going to have to generate a hidden dom image with the src being the base64. Then I realized I could just use the canvas as the source for a `PIXI.Sprite` or `PIXI.Texture`

This works as expected and generated the image, but I was killing myself trying to figure out why it wasn't working when I would go a second time. 

I use: `const texture = PIXI.Texture.fromCanvas(canvasElement);`
What I figured out is because the texture uses the same `canvasElement` pixi treats it as the same texture I had used before and simply ignores the request with no errors or messaging. 
So it goes:

1. paint the texture from html2canvas
2. Import the texture with `fromCanvas()`
3. Clear the html2canvas canvas, 
4. paint new data to html2Canvas
5. Attempt to import new texture with `fromCanvas()` with the new painted data
6. Pixi detects the canvas is the same as the one from step 2.
**<< NOTHING HAPPENS >>**

My thinking is if I'm trying to create a new texture from the same source PIXI should automatically run `BaseTexture.update()` which would update the texture from the passed canvas. 

The other issue is that once linked, updating/changing the canvas at all will always change the `BaseTexture` for all linked textures that use the same `canvas` element. I can see that `origin` argument is used to generate the `_pixiId` and `cache` but I can't see how I can target different textures by adjusting this at all.. 

My plan at the moment is to use my html2canvas `canvas` to generate hidden dom images and use them as the `source` for the `BaseTexture` and then change them as needed and fire `updates()` but this seems heavy.. Not sure what I'd want Pixi to do, but figured I'd put it out there..

**Comment by m9dfukc** [comment]
Hey, did you figure out how to solve this? 

I would be interested in a similar approach.

**Comment by ivanpopelyshev** [comment]
Just hack it.

https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/BaseTexture.js#L719

```js
PIXI.BaseTexture.fromCanvas = function(canvas, scaleMode, origin)
{
    origin = origin || 'canvas';
    if (!canvas._pixiId)
    {
       canvas._pixiId = `${origin}_${uid()}`;
    }

    let baseTexture = BaseTextureCache[canvas._pixiId];

    if (!baseTexture)
    {
        baseTexture = new BaseTexture(canvas, scaleMode);
        BaseTexture.addToCache(baseTexture, canvas._pixiId);
    } else 
    {
        baseTexture.update();
    }

    return baseTexture;
}
```

The only problem is that there's no way to now was canvas updated or not. If we make default behaviour with "update()" it can cause problems for existing games. What if we make optional fourth parameter there?

**Comment by englercj** [comment]
To update the texture with changes you made to the underlying canvas you can just call `texture.update()`. You should only call `.fromCanvas()` to create a new texture, which all you want to do is reupload the changes to your canvas to the GPU again.

**Comment by DennisSmolek** [comment]
Thanks @ivanpopelyshev I'll take a look and fiddle with that. 

I think the disconnect was that I didn't realize the canvas is treated as the lifetime texture source vs generating an output once. 

I thought I could use the same canvas element to generate many different textures but once you bind the canvas element it is directly related to the `BaseTexture` that was created. 

This is fine in principle but if the same canvas element is passed I thought it would be helpful to update the texture to the new canvas data vs simply ignoring the later calls. 

The constant binding is also fine, It makes sense but I didn't realize that's what is was doing. I'll close the issue...

@m9dfukc I felt I had 2 options:

1. Create new `Canvas` elements every time I needed one ( not efficient )
2. Made my own function to generate base64 data off the canvas into a generated `img` component, then import the texture like normal. I had to do some stuff with ID keys but this is the way I went.

**Comment by englercj** [comment]
> I think the disconnect was that I didn't realize the canvas is treated as the lifetime texture source vs generating an output once.

Yeah, we don't generate anything we just upload your source to the GPU.

> I thought I could use the same canvas element to generate many different textures but once you bind the canvas element it is directly related to the BaseTexture that was created.

You could make multiple BaseTextures manually using the same canvas, I just wouldn't recommend it.

> This is fine in principle but if the same canvas element is passed I thought it would be helpful to update the texture to the new canvas data vs simply ignoring the later calls.

`.fromCanvas` is for creating a texture, and so if one is already made we just return you a cached one. If you want to update the texture on the GPU call `.update()` on an existing texture instance, which will upload the source to the GPU for you.

If you have separate textures, having separate canvases is OK. If you draw something, upload it once, then never need to change it you can always: create a canvas, create a BaseTexture, draw to the canvas, upload to the GPU, then create a new base texture, clear/draw canvas again, upload to the new texture, etc. Then you only create 1 canvas, but multiple GPU textures. The catch is that the textures you made only live on the GPU so you would have to recreate them to upload/change them. Separate canvases mean they live in GPU and RAM, so you can easily upload them again. base64 data in an image is basically the same thing but you add a serialize to string, decode from string step inbetween.
