### ISSUE TITLE
Child AnimatedSprite does not update Width Height parent PIXI.Sprite

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4260]
hi guys , do i made a mistake ?
**AnimatedSprite** Does not update its parent !!!?

the parent name is **animationControler** 
and i add all AnimatedSprite in the **animationControler** child.
but **animationControler** **alway have width and height 1** ?!

```javascript
animationControler = function () {
    this._motionsListing = {};
    this._currentMotionRendered = null;
    PIXI.Sprite.call(this); // animationControler  herite pixi class
};
animationControler.prototype = Object.create(PIXI.Sprite.prototype);
animationControler.prototype.constructor = animationControler;
```
![afeefef](https://user-images.githubusercontent.com/24865815/29746164-78abca8a-8a9f-11e7-8e0f-0136b0e0a0f7.jpg)

It is possible that the parent takes the maximum width of the AnimatedSprite in child ?
thanks

**Comment by ivanpopelyshev** [comment]
Width of Sprite differs from container width: https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L491

As you see, it depends only on scale and sprite texture, and its 1 because you dont have texture on it. 
May be you want to use getBounds() instead?

**Comment by djmisterjon** [comment]
thanks work now  close:

i replace by pixi container

```javascript
animationControler = function () {
    this._motionsListing = {};
    this._currentMotionRendered = null;
    PIXI.Container.call(this);
};
animationControler.prototype = Object.create(PIXI.Container.prototype);
animationControler.prototype.constructor = animationControler;
```
