### ISSUE TITLE
TilingSprite with sub pixel position drops fps to 30 in IOS

### ISSUE THREAD

**Issue by godluck** [pixijs/pixi.js#4262]
Hi, I was testing particle animation effects using TilingSprite in my demo program, and noticed a performance difference in my Android and IOS device.
My Android device is mush slower than my IOS device in general, but the result is that I have 60 fps in Android and 30fps in IOS.
- Then I tried to change the code to find the problem, and noticed that the bunnymark demo runs with 60fps in my ios device, with the difference that bunnies are created using Sprite rather than TilingSprite
- I changed my code. With TilingSprite changed to Sprite, or the positions of sprites rounded to integer, the 60 fps come back in my ios device

Additionally, this fps drop happens in both canvas renderer and webgl renderer

I wander what code would cause this problem, and is there any way to fix it?

**Comment by ivanpopelyshev** [comment]
Do you use tilingSprite on a texture from atlas?

**Comment by godluck** [comment]
Yes, I use an image of varies blocks together with tilingSprite to produce different blocks, and change the tiling position of each sprite to change their status.
Although I have changed to sprite and managed to get the same result, I still wander why tiling sprite drops the fps

**Comment by ivanpopelyshev** [comment]
TiingSprite is not batching, and if you have many of these blocks that'll affect performance.

You have to use Sprite + Texture instead: https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Texture.js

You can just create many textures with same base but different frames.

**Comment by godluck** [comment]
https://codepen.io/godluck/pen/oeVGzo

codepen attached

notice in function *frame*, x is added with i/3 each frame, which shows around 30fps in ios device;
when changed to  x+=i, then it can reach 60fps 
tested in iphone se, iphone 6, iphone 7plus

**Comment by ivanpopelyshev** [comment]
> new PIXI.CanvasRenderer

try webgl.

**Comment by ivanpopelyshev** [comment]
Also, for this example, it might be better to use same pattern for all tilingsprites. According to https://github.com/pixijs/pixi.js/blob/dev/src/extras/TilingSprite.js#L199 , pattern is created per tiling sprite.

You can hack that method:

```js
PIXI.extras.TilingSprite.prototype._renderCanvas = function(renderer) {
var canvasTinter = PIXI.CanvasTinter;
...
}
```

**Comment by godluck** [comment]
Thanks for the information, for the solution I just switched to multi textures cut from one image. The animation is then silky fluent.
Although I still can't find the reason why sub pixel position would cause tiling sprite to drop fps, the problem is now no bother to the program. I'll close this issue.
