### ISSUE TITLE
Question: should I use PixiJS for fast icon/image creation?

### ISSUE THREAD

**Issue by aalbericio** [pixijs/pixi.js#4265]
Hello all,

PixiJS is a great library but can I use it as a helper library on an Angular/React/etc project just to help me create images/bitmapData fast?

My application needs fast dynamic icon/bitmap creation and I'd like to know if PixiJS can help there as a helper library.

Thanks in advance.

**Comment by englercj** [comment]
Sounds like you could probably just use canvas if you are just drawing a couple images once to create an icon.

**Comment by DennisSmolek** [comment]
FWIW I use Pixi and Angular2 mixed with Firebase to do all sorts of crazy graphics/images stuff and it's awesome... If you just need image blob/base64 data though I agree with @englercj just use canvas
