### ISSUE TITLE
Enhancement: is it possible to have mousewheel event support?

### ISSUE THREAD

**Issue by jcyuan** [pixijs/pixi.js#4267]
on PC i'd like to use mouse wheel to scroll my list instead of dragging.
so will you guy add this event? i'm not familiar to the event mechanism of PixiJS, so a little hard to make a PR sorry.

**Comment by englercj** [comment]
You could just listen to the mousewheel event on the canvas, and if you are hovering over a scrollable element use the canvas mousewheel event to scroll it.

**Comment by claudemuller** [comment]
@englercj I'd like to ask for some clarification on the process please - you could add an .on('scroll', ...) to a Pixi DisplayObject, listen for the scroll event on the canvas and emit that through to the DisplayObject in question. But if you have multiple DisplayObjects and you'd want to scroll the one directly below the cursor, how would you access/reference that DO? In DOM land you'd have document.elementFromPoint()...

**Comment by claudemuller** [comment]
Additionally, I've been trying to simulate a click on the canvas with MouseEvent and have it "propagate" down to Pixi objects. Is there anything that needs to be set besides interactive?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L657

```js
var found = renderer.plugins.interaction.hitTest(...);
```

**Comment by claudemuller** [comment]
Thanks @ivanpopelyshev, that helps out with another avenue I was pursuing, but could you shed some light on why it seems simulated clicks don't "propagate" down to Pixi elements?

**Comment by ivanpopelyshev** [comment]
They propagate only through "interactive=true" elements. To tell more, I need to know more about your situation.

**Comment by ivanpopelyshev** [comment]
Look at https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1125 - that's how it handles onPointerDown. May be it helps you somehow.

**Comment by claudemuller** [comment]
That does help thanks - I guess I hadn't looked at the code before because I was a little intimidated by such a complex library. I set some breakpoints on onPointerDown and discovered that the DOM event listener placed on renderer.view doesn't even fire with "simulated" clicks. However when I add an event listener to the canvas element it does fire (but the Pixi elements' listeners don't). I created https://jsfiddle.net/mwLwkebo/4/ if you'd like to have a look? I'm just trying to understand why created MouseEvents aren't getting picked up by the listener in the lib. Maybe I'm constructing it incorrectly? Could it have something to do with MouseEvent.isTrusted?

**Comment by bigtimebuddy** [comment]
Here's a simple example of using mousewheel event with the canvas and using InteractiveManager's `hitTest` to find the interactive object.

https://jsfiddle.net/bigtimebuddy/134e4u03/1/

**Comment by claudemuller** [comment]
Thanks @bigtimebuddy I did get that working as suggested, but I'd like to understand what is happening in the other scenario so that I can rule that line of investigation out as infeasible

**Comment by jcyuan** [comment]
@bigtimebuddy many thanks bro although I've had my problem resolved.

**Comment by sergebat** [comment]
@bigtimebuddy thanks a lot for the almost working example! 

I have updated the fiddle to correctly map coordinates from client space to PIXI stage space with mapPositionToPoint: https://jsfiddle.net/sergebat/v1c4bL9b/1/ (had to scratch my head for a while on why hitPoint was off :) ).

**Comment by qq731749207** [comment]
I use mousewheel like this.  Hope it's useful for you

`if (document.addEventListener) {	
        	document.addEventListener('DOMMouseScroll', scrollFunc, false);   
        }
        window.onmousewheel = document.onmousewheel = scrollFunc;`

`var scrollFunc = function (e) {    
    	ee = e || window.event;       
    	if (e.wheelDelta) {
    		if(e.wheelDelta < 0) {
    			if(layerContainer.scale.x >= 1.25) {
        			layerContainer.scale.x *= 0.8;
        			layerContainer.scale.y *= 0.8;
    			}
    		}else if (e.wheelDelta > 0){
    			if(layerContainer.scale.x < 5) {
    				layerContainer.scale.x *= 1.25;
    				layerContainer.scale.y *= 1.25;
    			}
    		}
    	} else if (e.detail) {
    		if(e.detail < 0) {
    			if(layerContainer.scale.x >= 1.25) {
        			layerContainer.scale.x *= 0.8;
        			layerContainer.scale.y *= 0.8;
    			}
    		}else if(e.detail > 0){
    			if(layerContainer.scale.x < 5) {
    				layerContainer.scale.x *= 1.25;
    				layerContainer.scale.y *= 1.25;
    			}
    		}
    	}   
    }`

**Comment by Mwni** [comment]
I needed this functionality for a project, so here is a plugin for it: [pixi-mousewheel](https://github.com/Mwni/pixi-mousewheel)

Events are opt in:
```
displayObject.interactiveMousewheel = true
displayObject.on('mousewheel', (delta, event) => {
    otherDisplayObject.y += delta * 100
})
```
