### ISSUE TITLE
Animated Sprites barely out of sync

### ISSUE THREAD

**Issue by hassanshaikley** [pixijs/pixi.js#4270]
I have two animated sprites running at the same time.

I have an array that iterates over them and runs goToAndPlay(0) on both of them.

The both of them more or less happen at the same time except one always finishes first. So there is a split second where they are out of sync.

I don't know if this has to do with renderer settings or buffering, which are all more or less the default settings.

If there's an obvious answer please let me know, otherwise close this issue. It may not be very useful to people helping me debug without code.

**Comment by ivanpopelyshev** [comment]
Its strange. AnimatedSprite uses "PIXI.ticker.shared" which is emitting the same delta time to all listeners. The priority of this operation is higher than rendering, so render cant stick between two updates. Default settings should work.

Need to debug "animatedSprite._currentTime" and "animatedSprite.currentFrame" of both sprites.

**Comment by bigtimebuddy** [comment]
Is it possible @hassanshaikley to create a JSFiddle which reproduces this issue?

**Comment by hassanshaikley** [comment]
@bigtimebuddy I can't do a JS Fiddle, it could end up being too complicated to set up but I do have this hosted although it is very much an in-pre alpha project.

http://aotb.io/

**Comment by hassanshaikley** [comment]
@ivanpopelyshev that helps me understand which direction to go in as I debug, thank you! I feel really screwed haha

**Comment by hassanshaikley** [comment]
@ivanpopelyshev so they are slightly out of sync, by one frame!! The base animation and the shield animation. I start them like this:

		```this.allAnimations.forEach((thing) => {
			thing.gotoAndPlay(0);
		})```

This could be starting them late. How do I start them at the same time? : (

**Comment by ivanpopelyshev** [comment]
I still think that "out of sync" is actual bug. Plesae make a fiddle.

**Comment by hassanshaikley** [comment]
So when I print the _currentTime I can see it trail off and they fall out of sync.... : (

![erghtime](https://user-images.githubusercontent.com/6746840/30008425-c444e344-90dc-11e7-8fa6-5e810b7ec6d5.png)

**Comment by ivanpopelyshev** [comment]
Then its a bug, lets find it

**Comment by themoonrat** [comment]
@hassanshaikley Sorry for a delay in getting back to you... is this something you found a way around or found a solution for?

**Comment by hassanshaikley** [comment]
I found a work around.

However this does seem like a bug to me? I will try to upload some code later for you guys to look at as it is sort of a pain to deal with. I wish I did that before creating the PR.
