### ISSUE TITLE
Failed to execute 'texImage2D' on 'WebGLRenderingContext': The video element contains cross-origin data, and may not be loaded.

### ISSUE THREAD

**Issue by wpitallo** [pixijs/pixi.js#4274]
Hi This seems to be a bug,

Cannot load any video's from cross origin. Even with all headers set correctly.

codepen issue:

https://codepen.io/Wpitallo/pen/VzqgXR?editors=0010

**Comment by englercj** [comment]
Duplicate:

https://github.com/pixijs/pixi.js/issues/4007
https://github.com/englercj/resource-loader/issues/99
