### ISSUE TITLE
Masking textures get different proportions with same mask applied

### ISSUE THREAD

**Issue by gg4u** [pixijs/pixi.js#4276]
I need help :) 

I have some squares, and want to fill them with textures.

I am updating squares' textures when user does some interaction.
Textures are images with different sizes.
The effect I want to have, is to have square sprites, each with its image: so I want to crop textures, or mask them, with the same size of the square...

The problem I have, is that masked textures have "visually" different sizes as a result. I thought it may be because textures are scaled, and so masks may scale differently, but adjustment did not fix.

Here's my thing:

```
// somewhere in my code, I have a square object: I initialise a texture and set its scale
ui.thumbnail = new PIXI.Sprite.fromImage( '2.png' );
ui.thumbnail.anchor.set( 0.5, 0.5);
ui.thumbnail.scale.set(0.1, 0.1);

// the user does something, and here I update the texture
// I tried to crop texture, but has no effect
// var newTexture = new PIXI.Texture.fromImage( thumbnail.source , new PIXI.Rectangle(- NODE_WIDTH / 2, - NODE_WIDTH / 2, NODE_WIDTH, NODE_WIDTH), new PIXI.Rectangle(- NODE_WIDTH / 2, - NODE_WIDTH / 2, NODE_WIDTH, NODE_WIDTH) );

// so I try with mask:
var newTexture = new PIXI.Texture.fromImage( thumbnail.source );
newTexture.baseTexture.mipmap = true;
newTexture.scaleMode=PIXI.SCALE_MODES.NEAREST;

newTexture.addListener("update", onSquareTextureUpdate);

function onSquareTextureUpdate() {
                      // here I update my square object
                      nodeUI[node.id].thumbnail.texture = newTexture;
                      nodeUI[node.id].thumbnail.texture.scaleMode=PIXI.SCALE_MODES.NEAREST;

                     // here I normalise the textures: if w > h, then w == the side of the square
                      if (newTexture.width > newTexture.height) {
                          nodeUI[node.id].thumbnail.width = NODE_WIDTH;
                          nodeUI[node.id].thumbnail.height = NODE_WIDTH * newTexture.height / newTexture.width;
                      } 
                      else {
                          nodeUI[node.id].thumbnail.width = NODE_WIDTH * newTexture.width / newTexture.height;
                          nodeUI[node.id].thumbnail.height = NODE_WIDTH;
                      }


                      // create a mask                      
                      var mask = new PIXI.Graphics();
                      mask.beginFill(0, 0);

                      mask.drawRoundedRect(-NODE_WIDTH/2, -NODE_WIDTH/2, NODE_WIDTH, NODE_WIDTH, 40);
                      mask.endFill();

                      // here I apply the mask as a child of my square object
                      nodeUI[node.id].thumbnail.addChild(mask);

                      //mask the texture with the polygon
                      nodeUI[node.id].thumbnail.mask = mask;

                      // is this line working? ?
                      newTexture.removeListener();
}
```

This is the result: the masked textures have different sizes and can't fill in the square, despite the mask is the same size of the square!

<img width="209" alt="screen shot 2017-09-02 at 9 00 41 am" src="https://user-images.githubusercontent.com/284214/29993642-43305dd0-8fbd-11e7-8f95-11ad15d50440.png">
<img width="211" alt="screen shot 2017-09-02 at 9 00 27 am" src="https://user-images.githubusercontent.com/284214/29993641-432da9d2-8fbd-11e7-870d-15e6209d7cd4.png">
<img width="217" alt="screen shot 2017-09-02 at 9 00 18 am" src="https://user-images.githubusercontent.com/284214/29993644-4333bfb6-8fbd-11e7-85d5-86047aacbcbb.png">
<img width="237" alt="screen shot 2017-09-02 at 9 00 08 am" src="https://user-images.githubusercontent.com/284214/29993643-4331b2ac-8fbd-11e7-8359-df8d59955e05.png">

**Comment by ivanpopelyshev** [comment]
That's too difficult. It needs a fiddle.

**Comment by gg4u** [comment]
Hi @ivanpopelyshev I am not handy of fiddle yet. I will try first an alternative:
could you please suggest how to crop a texture ? It would be good to already pass a size before loading the texture with "fromImage()".
The idea is to normalise first all the textures to a fixed width or height, and then update them and crop or mask them.
Thank you for helping.

**Comment by themoonrat** [comment]
Hi gg4u - I'm closing this down due to inactivity. It really helps us massively having a jsfiddle to help us help you :) If you still have any problems, please raise a new issue. Thanks!
