### ISSUE TITLE
Event sequence problem.

### ISSUE THREAD

**Issue by jcyuan** [pixijs/pixi.js#4278]
![image](https://user-images.githubusercontent.com/850854/30019793-55eb920e-9194-11e7-8b50-9687203d5c21.png)

the nested objects are:
stage -> root -> c2 -> c1 -> btn1
as the debug info you can see:
all are sorted except up & click, they should be in sequence to be dispatched like other events too?
i tested a few game enginies events are dispatched in sequence even HTML dom:
see:
 
![image](https://user-images.githubusercontent.com/850854/30020541-b8baf896-9196-11e7-863d-cbec3899a35b.png)

or this is just a normal sequence you guys designed?

**Comment by ivanpopelyshev** [comment]
That's a good point. 

I suggest we push everything into array and then fire events on it, like here: https://github.com/pixijs/pixi-display/blob/master/src/InteractionManagerMixin.ts#L136
