### ISSUE TITLE
PIXI.mesh.NineSlicePlane display error when its width less than its center block width.

### ISSUE THREAD

**Issue by jcyuan** [pixijs/pixi.js#4279]
see online test: 
    http://jc-space.com/testnsp/

when the image's width / height is set to less than the width of it's nine slice center, it shows a weird display.  i think in this siutation the image should be scaled like a normal image which does not have a nineslice setting.

**Comment by ivanpopelyshev** [comment]
Feel free to change it: https://github.com/pixijs/pixi.js/blob/dev/src/mesh/NineSlicePlane.js

If you add less than 50 lines of code for that, I suppose we can merge it. Otherwise, its a good idea for a plugin.

**Comment by jcyuan** [comment]
i'll try it ,man

**Comment by ivanpopelyshev** [comment]
I'll help if you have any questions about that code.

**Comment by ivanpopelyshev** [comment]
Also, you may just make a simple patch or make your own class that extends PIXI.mesh.Plane, I can help with converting it onto our code style.

**Comment by jcyuan** [comment]
fixed, so close
