### ISSUE TITLE
Question: how to draw efficiently a long triangle strip?

### ISSUE THREAD

**Issue by manubb** [pixijs/pixi.js#4280]
Hi,
i am the author of [graph-draw](https://www.npmjs.com/package/graph-draw) that i use to display boundaries on leaflet maps. Currently, i am drawing all triangles as polygons using `PIXI.Graphics` which is not really efficient regarding both memory and time. I can easily get a triangle strip:
```js
var vertices = [[12 ,14], [200, -129], ...]; // length: 439378
var triangle_strip = [5, 6, 10, ...]; //length: 1451472
```
I think that this approach would divide memory usage by a factor of at least 2. 
Note that all triangles have same color and same alpha.
My problem is that i have no idea how to display this with Pixi. Can someone help me with this?
Thank you!

**Comment by ivanpopelyshev** [comment]
440k ? you have to separate it into multiple figures and cull them.

If you want vertices/trignagle_strip, see "PIXI.mesh.Mesh" instead. To make it the same performance as graphics,  I recommend to change it a bit that way it doesnt upload all vertices every tick, like current version does: https://github.com/pixijs/pixi.js/blob/dev/src/mesh/webgl/MeshRenderer.js#L101 , add one more dirty flag.

You can patch it like that:

```js
PIXI.mesh.MeshRenderer.prototype.render = function(mesh) {
var glCore = PIXI.glCore;
...
}
```

either make your own MeshRenderer, just copy the code, register it in renderer, and use different "pluginName" in your mesh.

**Comment by manubb** [comment]
Performance is not an issue and i do not think that i need to remove triangles that are not visible: the stage is static and only needs to be uploaded once. (See this [demo](https://manubb.github.io/graph-draw/city-mesh.html) for example.)

I will dive into MeshRenderer code then. Thank you @ivanpopelyshev .

**Comment by manubb** [comment]
@ivanpopelyshev you saved me a lot of time. Thank you again. I was a bit pessimistic as memory usage is now more than 5 times less than before! Pretty happy with this. You can see the result [here](https://manubb.github.io/graph-draw/city-mesh.html).
