### ISSUE TITLE
Question: how to convert canvas image to black and white?

### ISSUE THREAD

**Issue by juwoni** [pixijs/pixi.js#4282]
Hi

how to convert canvas image to black and white??

**Comment by englercj** [comment]
Have you looked at the canvas 2d api? https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D

**Comment by juwoni** [comment]
thanks I just wondered is there method in pixi.

**Comment by bigtimebuddy** [comment]
You could apply a ColorMatrixFilter to your whole scene to make it black/white 

http://pixijs.download/dev/docs/PIXI.filters.ColorMatrixFilter.html#desaturate
