### ISSUE TITLE
Can not scroll page on "Chrome Android" and "Chrome on Mac with mobile mode"

### ISSUE THREAD

**Issue by takumus** [pixijs/pixi.js#4283]
Can not scroll page on `Chrome on Android` and `Chrome on Mac mobile mode`.
```
Android 4.4.2
Chrome 60.0.3112.107
```
```
Mac 10.12.6
Chrome 60.0.3112.113(64bit)
```

I tried this. 
```js
renderer.plugins.interaction.autoPreventDefault = false;
```

But can not scroll on chrome on Android.

I found these codes in `/src/interaction/InteractionManager.js` at `line 709`.
```js
if (window.navigator.msPointerEnabled)
{
   this.interactionDOMElement.style['-ms-content-zooming'] = 'none';
   this.interactionDOMElement.style['-ms-touch-action'] = 'none';
}
else if (this.supportsPointerEvents)
{
   this.interactionDOMElement.style['touch-action'] = 'none';
}
```
And remove these codes, works fine on `Chrome on Android` and `Chrome on Mac mobile mode`.

Do you have any suggestions?

I think you may want to add property like `cssTouchAction: boolean` to `InteractionManager`.

thanks.

**Comment by themoonrat** [comment]
It's easy to undo those css options, but I see no reason a setting couldn't be added to v5 to customise the interaction manager experience a little better
