### ISSUE TITLE
Support for PNG_4444, PNG_565 and others

### ISSUE THREAD

**Issue by Gravois** [pixijs/pixi.js#4286]
To use these image formats, in order to save some gpu memory, we need to set the format and type parameters of the texture objects that are loaded to the gpu.
By default these are coded this way:
 
glTexture = new _pixiGlCore.GLTexture(this.gl, null, null, null, null);
 
var Texture = function(gl, width, height, format, type)
{
…
this.format = format || gl.RGBA;
this.type = type || gl.UNSIGNED_BYTE; 
}
 
We need to change these two parameters on a texture basis.
For PNG_4444, this.type would need to be set to gl.UNSIGNED_SHORT_4_4_4_4.
For PNG_565, this.type would need to be set to gl.UNSIGNED_SHORT_5_6_5 and this.format to gl.RGB.
 
What’s the best way to set those flags without editing PIXI’s source code?

**Comment by ivanpopelyshev** [comment]
Just a reference from playcanvas code: https://github.com/playcanvas/engine/blob/21ed3bc8eb3000e484dd1438c7c7492995e81ab9/src/graphics/device.js#L1275

It actually possible to make custom loader for texture using new plugin: https://github.com/gameofbombs/pixi-super-atlas

Sorry, there are no examples yet, but basically you have to override TextureResource and make your own texture loader: https://github.com/gameofbombs/pixi-super-atlas/blob/master/src/superAtlas/SuperAtlas.ts#L217

**Comment by ivanpopelyshev** [comment]
If you seriously need it, i can make the demo this week.

However, things that you mentioned will not save videomemory at all: you need to use "internalFormat" for it, not "type". Please see MDN : https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D

The only way to reduce videomemory usage is to use this plugin: https://github.com/pixijs/pixi-compressed-textures/

**Comment by Gravois** [comment]
Thanks for the quick response. It's in no way urgent so please don't worry about demo for it. We'll make memory reductions elsewhere.

We're aware of the compressed textures plugin thanks, we've only run internal tests on it so far. The current issue arose because we had a large set of 2D textures that rely heavily on alpha and tiling we were trying to avoid having multiple texture sets (including compressed + alpha) for the different platforms. So beyond physical size reduction were investigating ways of reducing the VRAM.

**Comment by ivanpopelyshev** [comment]
As far as I know, browser stores PNG version of image, and its automatically converted to RGBA before pixi uploads it to GPU. After some time RGBA form in RAM becomes forgotten and we have only PNG in RAM and RGBA in VRAM, which is fine.

If your platform is PC, you should use S3TC (DDS) format. I dont know what to recomment for mobiles.

**Comment by ashleygwinnell** [comment]
Use PVRTC for iOS and ETC1 for Android - you can test various compression formats [here](http://toji.github.io/texture-tester/).  

I've implemented the ability to set these formats in [a fork](https://github.com/ashleygwinnell/pixi.js/commit/d992d35bf21615b618f95d53ea67353a839a9c62) of the dev branch. You have to pass `glFormat` and `glType` as metadata object (the third `loader.add` parameter).

**Comment by themoonrat** [comment]
@bigtimebuddy Is the above by @ashleygwinnell something that could go into v5? Looks a nice concise improvement to me
