### ISSUE TITLE
Question : how to render texture applied colormatrix to CanvasRenderer?

### ISSUE THREAD

**Issue by juwoni** [pixijs/pixi.js#4288]
I'd like to render texture which is applied colormatrix to CanvasRenderer.
```javascript
const resources = PIXI.loader.resources;

const texture = new PIXI.Texture(resources['faces'].texture, new PIXI.Rectangle(1, 1, 6, 6));
const userFaceSprite = new PIXI.Sprite(texture, new PIXI.Rectangle(0, 0, 24, 24));
tint && (userFaceSprite.tint = tint);


userFaceSprite.scale.x = this.props.screenScale;
userFaceSprite.scale.y = this.props.screenScale;

let colorMatrix = new PIXI.filters.ColorMatrixFilter();
userFaceSprite.filters = [colorMatrix];
colorMatrix.blackAndWhite();


if (!this.renderer) {
    this.renderer = new PIXI.WebGLRenderer(12, 12, {
        backgroundColor: 0x000000,
        antialias: false,
        view: this.userFace
    });
}
this.renderer.render(userFaceSprite);
```

how to render texture in webglRenderer to canvasRenderer?
if is not possible , I just want to get texture applied colormatrix.

**Comment by englercj** [comment]
Filters are a WebGL-only feature.

**Comment by juwoni** [comment]
The reason is I use The texture as a message Icon(html element) so I had to make many webgl renderer.
when I make many webgl renderer, warning occurred  "createContext.js:14 WARNING: Too many active WebGL contexts. Oldest context will be lost."

Is it possible that just make one WebGL renderer then render to many canvas elements?

**Comment by englercj** [comment]
But you don't have to make many renderers. You only need to make one.

1. Create a renderer
2. Render an icon
3. Use the `extract` API to pull out the image
4. Goto step 2

No need to create a new renderer for each icon if you are just rendering an icon once, then putting it in an html element.

**Comment by juwoni** [comment]
Thanks for helping me.
