### ISSUE TITLE
After Effects to PIXI.js

### ISSUE THREAD

**Issue by karthickvkumar** [pixijs/pixi.js#4290]
Hi @GoodBoyDigital  @ivanpopelyshev ,
I saw this after effect [example](https://codepen.io/airnan/pen/yapJWq), It show the option `renderer: 'pixi'` I would like to know whether this will use the pixi js renderer technique or else it will create a pixi js canvas for making animation.

Also would like to know is it possible to load after effect animations into pixi js?

Thanks in Advance

**Comment by ivanpopelyshev** [comment]
Hi! @bigtimebuddy is our expert on Adobe software :)

**Comment by bigtimebuddy** [comment]
@karthickvkumar I'm not familiar with any tooling right now for After Effects. We have not be involved in **bodymovin**, so maybe the author of that example will have some guidance for you. Maybe someone out there knows of some alternative pipelines for After Effects. 

At the very least, there might be some spritesheet exporting approach you could try. E.g., exporting each frame of the AE animation as standalone PNGs and then packing together using TexturePacker.

A robust exporter for After Effects seem like a good idea though. I created an Adobe Animate exporter [here](https://exchange.adobe.com/addons/products/14345#.WbKr-5OGPOQ) ([repo](https://github.com/bigtimebuddy/pixi-animate-extension)).

**Comment by karthickvkumar** [comment]
@ivanpopelyshev  @bigtimebuddy  Thanks for the quick response.

**Comment by goccy** [comment]
@karthickvkumar  The other day, I released https://github.com/knocknote/pixi-after-effects .
This library can use AfterEffects animation as PIXI.Container ! Please see it :)
