### ISSUE TITLE
BitmapText throws "Cannot read property 'size' of undefined"

### ISSUE THREAD

**Issue by deusprogrammer** [pixijs/pixi.js#4293]
Pixi.js's BitmapText type is throwing the following exception:

Uncaught TypeError: Cannot read property 'size' of undefined
    at i.updateText (CanvasExtract.js:64)
    at new i (deprecation.js:478)
    at i.setup (pyst.js:310)
    at i.n.emit (index.js:117)
    at i._onComplete (Loader.js:444)
    at Loader.js:483
    at once.js:12
    at s (eachOfLimit.js:54)
    at n (eachOfLimit.js:44)
    at onlyOnce.js:12

I am importing an xml based font file generated by bmglyph (Sparrow/Starling) like other's have mentioned to do to correct this issue, but it still doesn't work.  I tried generating the file with multiple different bitmap font generators, tried changing the extension on the font file to .xml, but alas, nothing works.

**Comment by deusprogrammer** [comment]
Nevermind, I just figured it.  You go off of the face attribute in the font file, not the key I give it on the loader.  That should probably be documented clearly somewhere.

**Comment by ivanpopelyshev** [comment]
> Nevermind, I just figured it. You go off of the face attribute in the font file, not the key I give it on the loader. That should probably be documented clearly somewhere.

Make a PR or tell me what to specify in docs: https://github.com/pixijs/pixi.js/blob/dev/src/extras/BitmapText.js
