### ISSUE TITLE
Incorrect documentation for ParticleContainer maxSize default value

### ISSUE THREAD

**Issue by griest024** [pixijs/pixi.js#4294]
The [documentation](https://github.com/pixijs/pixi.js/blob/dev/src/particles/ParticleContainer.js#L31) says that the max size for `ParticleContainer` is 15000 but [the default value](https://github.com/pixijs/pixi.js/blob/dev/src/particles/ParticleContainer.js#L40) is only 1500. Is this a typo?

**Comment by ivanpopelyshev** [comment]
Yes, it should be 1500

**Comment by bigtimebuddy** [comment]
Welcome a pull request to fix this.

**Comment by ivanpopelyshev** [comment]
Actually, when I read the code, I see that it should be 15000 by default.

**Comment by ivanpopelyshev** [comment]
I dont know, I think I just change ParticleContainer that way it works better :)
