### ISSUE TITLE
Changing texture of NineSlicePlane does not change the image.

### ISSUE THREAD

**Issue by filharvey** [pixijs/pixi.js#4296]
We have a NineSlicePlane which we use as a XP Bar. When XP reaches it max, it changes from a Red texture to a Blue Texture.

What seems to be happening in WebGl, is that when the texture is changed, I can see on the main NineSlicePlane, the uv's have changes (image is in a sprite sheet). But the _glDats for the uvBuffer, keep the old uv's of the original texture.

![gldata](https://user-images.githubusercontent.com/232101/30386413-9cbb405a-985e-11e7-9c95-9ca4527dfcdd.png)

**Comment by ivanpopelyshev** [comment]
There might be bugs in NineSlicePlane and Mesh in general, because some time ago I made big refactoring to support texture regions. In this case I dont see a bug yet :( 

Please make a fiddle and I'll fix it.

**Comment by filharvey** [comment]
https://jsfiddle.net/n47g1h7t/

**Comment by ivanpopelyshev** [comment]
Thank you! Now it works: https://pixijs.download/dev-plane-dirty-fix/pixi.js 
Soon it'll be merged ^_^

**Comment by filharvey** [comment]
Thanks, will grab your pixi for now.

**Comment by ivanpopelyshev** [comment]
Yep, you can see the changes in #4299

**Comment by filharvey** [comment]
Tried in our project, all works fine :-) Thanks
