### ISSUE TITLE
pointermove on mobile results in unexpected mouse.global values.

### ISSUE THREAD

**Issue by SamBenson** [pixijs/pixi.js#4297]
I'm having some issues with the interaction manager on mobile. Desktop works absolutely fine and as expected but when I try on mobile it results in `this.mouse.global` being `{x: -999999, y: -999999}`.

    var manager = new PIXI.interaction.InteractionManager(app);
        manager.on('pointermove', onDragMove);

    function onDragMove() {
        if (this.dragging) {
            var newPosition = this.mouse.global,
                radius = width/2,
                atan = Math.atan2(newPosition.x-radius, newPosition.y-radius),
                deg = -atan/(Math.PI/180) + 180;

            console.log(this.mouse.global); // On mobile this is {x: -999999, y: -999999}

            audio.currentTime = (deg / 360) * audio.duration;
        }
    }

Any reason this could be? I'm using Pixi 4.5.0.

**Comment by themoonrat** [comment]
You're looking at a property only used for a mouse, and you're on a touch screen
Look at https://pixijs.github.io/examples/#/demos/dragging.js for example on how to do dragging

**Comment by ivanpopelyshev** [comment]
There are advanced demos on dragging that have better results: https://pixijs.github.io/examples/#/projection/basic.js , try to move red squares or click on them.

**Comment by andrewstart** [comment]
Another place to look for inspiration is https://github.com/SpringRoll/springroll-pixi-display/blob/master/src/ui/DragManager.js, which properly handles multiple touches on different objects.
