### ISSUE TITLE
Spritesheet.json auto loading related image

### ISSUE THREAD

**Issue by JonnyCodes** [pixijs/pixi.js#4298]
When I load a spritesheet's json (packed using texture packer) Pixi automgically loads the related image thanks to the 'meta' object in the json.

I'm not a fan of magic and would prefer to handle image loading myself, I can't find a way to disable this magic image loading. Am I missing something?

**Comment by JonnyCodes** [comment]
For now I've added a check in `spritesheetParse.js:12` to see if the _meta_ object is in the json data and deleted the _meta_ object from the json file.

`if (!resource.data || !resource.isJson || !resource.data.frames || this.resources[imageResourceName] || !image.data.meta)
        {
            return next();
        }`

This seems to only affect setting a custom the resolution on the spritesheet. (Which I don't need). 
I don't really want to have to remove the _meta_ object for every spritesheet and for newly generated spritesheets. Is there another way?

**Comment by ivanpopelyshev** [comment]
Loader can be tricky. Its good that you found a workaround. 

Lets try another: `this.resources[imageResourceName]` <-- that already exists in pixi

```js
loader.add('atlas_image', 'some_image.png');
loader.add('atlas', 'some_atlas.json');
```

**Comment by JonnyCodes** [comment]
Of course, just name my image sheet the same as the spritesheet parser's  generated name for the sheet. Such a simple solution!

Thanks so much.

**Comment by ivanpopelyshev** [comment]
Just comment "//hack" there, because I don't have guarantees that it wont be changed in next versions to something more legit.
