### ISSUE TITLE
Interaction Masking?

### ISSUE THREAD

**Issue by simplygreatwork** [pixijs/pixi.js#4301]
I've been working with Pixi recently at:
https://github.com/simplygreatwork/goodshow
https://rawgit.com/simplygreatwork/goodshow/master/examples/kitchen-sink/index.html

I have some non-interactive shapes in my app which are drawn properly within the applied mask - however these shapes interfere with other mouse interaction outside of the bounds of the mask. Should I upgrade to Pixi v4 from Pixi v3.0.11 in order to solve this issue? Or could you offer any other advice pertaining to the interaction manager?

**Comment by ivanpopelyshev** [comment]
That's the code in v4: https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1019

OK, lets try the following:
1. add https://github.com/ivanpopelyshev/pixi-legacy (bin/legacy.js) into the project
2. call "PIXI.legacy.patchV3InteractionMask()".

**Comment by ivanpopelyshev** [comment]
Btw, you have very positive username and repository names 👍

**Comment by simplygreatwork** [comment]
Thank you, Ivan, for your advice. I did decide to try updating to Pixi v4 and that did solve the interaction masking issues really well. Upgrading to PIXI v4 ended up being easier than I originally thought it would be - mainly just some issues updating PIXI.Text configuration and filters.

"Good show" was what we would say before plays when I was in drama in high school.  :-) 👍 So, good show Pixi!
