### ISSUE TITLE
Setting Bounds Manually, Locally?

### ISSUE THREAD

**Issue by simplygreatwork** [pixijs/pixi.js#4306]
I've been doing a lot of layout/arrangement management in PIXI. So far, I've been manually assigning *bounds* (globally I think) to DisplayObjects after my layout calculations. This works well for now but I am bracing that at some point soon I'm going to have to do a bit of refactoring. I suspect that applying bounds manually breaks the position property because bounds are global and not local. It would be nice if when I set the bounds of a DisplayObject that the local position would automatically update. Is it possible to set bounds *locally* so position within a parent remains valid?

Maybe all I need to do is: 1.Perform all of my layout calculations using continuing to use my own private rectangle bounds object. 2. Set only position on each DisplayObject - do not set bounds directly. 3. Then when I issue drawing commands on my Graphics object, draw using [0, 0, mybounds.width, mybounds.height]. 4, Let PIXI automatically calculate bounds.

Thanks,
Philip

https://rawgit.com/simplygreatwork/goodshow/master/examples/kitchen-sink/index.html

**Comment by ivanpopelyshev** [comment]
My mind cant process that yet, I just woke up :) 

Places you have to look up: https://github.com/pixijs/pixi.js/blob/dev/src/core/display/DisplayObject.js#L194, https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js#L343

Position, scale, rotation and transform are first-citizens of pixi stage. width/height and getBounds are second and calculated upon them, that's why its not easy to make UI on top. I would like to see your solution to the problem. There's https://github.com/pixijs/pixi-ui which mirrors unity API but there are not much docs to it.

**Comment by simplygreatwork** [comment]
Thank you Ivan. 

I am groking now why bounds need to be calculated on the fly - due to any transforms potentially applied. I did go through and refactor my code. The biggest omission I had was that I was drawing all Graphics globally at [0,0] and never setting position at all because layout was being managed. But I've corrected that. I'm now setting positions in my layout code and then applying sizes/extents when I draw on Graphics. And so I don't think I'm really touching Container.bounds at all.

Right now I am basically ignoring scaling and rotation in my layout managers. I'm mostly focused on different sorts of extents for planar layout: fixed, flex, inherited, flow & and stack layout. I'll let you know if I begin to account for scaling and rotation. I also know that I probably ought to dig around more in the Pixi UI projects.

**Comment by ivanpopelyshev** [comment]
OK, let me know if you need help with understanding something specific

**Comment by simplygreatwork** [comment]
Thank you so much. Closing this issue.

The moral of this story for others is that you typically do not want to set bounds on DisplayObjects manually. For example, when you rotate a DisplayObject, its bounds will change. When you draw on many Graphics objects and add them to a container, Pixi automatically calculates the bounds of that container from all of the drawing operations you've made on the Graphics.

**Comment by ivanpopelyshev** [comment]
There's also hitArea, and you can set local bounds by hacking _calculateBounds(). Look up toLocal, toGlobal methods too.

**Comment by ivanpopelyshev** [comment]
Also be sure not to call getBounds() on containers that have 10.000 children ;) However, Graphics with big number of primitives inside is ok - its cached.
