### ISSUE TITLE
Container & app.stage don't support interactive ???

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4307]
Container & app.stage don't support interactive ???

Or there are something I did are  wrong ?

```
    app.stage.interactive = true;
    app.stage..on("pointerdown", function(event) {
        var p = event.data.global;
        console.log(p);
    });
```

**Comment by ivanpopelyshev** [comment]
If you put a bunny on a stage, you can click that bunny. Background isnt interactive ;)

**Comment by finscn** [comment]
I see.

**Comment by ivanpopelyshev** [comment]
There are special handlers on interactionManager for that "renderer.plugins.interaction.WHATEVERIDONTREMEMBER"

**Comment by finscn** [comment]
THanks
