### ISSUE TITLE
[Share] Example:  Pixi.js + Tiled 

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4308]
There is a pixi tool named pixi-tilemap ( https://github.com/pixijs/pixi-tilemap )
It could work for  rendering map based tile.
But there is no official  example for telling us  how to use it with Tiled.
( Tiled  is an excellent  map editor  , at http://www.mapeditor.org/  ) . 

I'm a crazy fan of Tiled , I think I should do something. 
So, I create a tool at  https://github.com/finscn/tiled-kit.js  , it could help us to use Tiled in Web more easily.

There are some examples showing that  how to use  pixi.js + pixi-tilemap + tiled-kit.js : 

* Normal Tile map ( orthogonal rect tile): 
http://fatidol.com/tiled/main.html?example=1

* Normal Tile map with tileoffset & multi layer
http://fatidol.com/tiled/main.html?example=2

* Normal Isometric Tile map ( orthogonal rhombus tile): 
http://fatidol.com/tiled/main.html?example=3

* Normal Staggered Isometric Tile map ( orthogonal rhombus tile): 
http://fatidol.com/tiled/main.html?example=4

My english is very poor , so there is no  document now. 
But I'm glad to discuss about Tiled , pixi-tilemap &  tiled-kit.js with you.

**Comment by ivanpopelyshev** [comment]
Can I just copy it when its stable enough? We'll make examples for it and i'll give you rights over pixi-tilemap

**Comment by ivanpopelyshev** [comment]
The least I think, I should reference it from pxi-tilemap itself

**Comment by finscn** [comment]
of course . You could do everything you want to do.

**Comment by winniehell** [comment]
@ivanpopelyshev @finscn Could we have a `tmxParser` that loads tilesets and images similar to the [`spritesheetParser`](https://github.com/pixijs/pixi.js/blob/v4.6.2/src/loaders/spritesheetParser.js)?

**Comment by finscn** [comment]
My project https://github.com/finscn/tiled-kit.js is `tiled-json-paser` . 
You could use Tiled's `export as json` , then use tiled-kit.js to parse the json file.
I think `tmx` is  not  necessary.
tmx is xml, parse xml is complex & slow.

**Comment by winniehell** [comment]
> My project https://github.com/finscn/tiled-kit.js is tiled-json-paser .

@finscn Thank you for pointing that out! :+1: I had a look at your project and in my opinion it does a lot more than what I had in mind. The `spritesheetParser` only fetches the referenced image while `tiled-kit.js` also contains convenience methods for accessing the Tiled data structures (things like `collideWithEntity`).

What I would like to see in pixi.js is a `tmxParser` that

- `loader.add()`s the reference external tilesets
- `loader.add()`s the reference tileset images
- maybe also: `loader.add()`s [image layers](http://doc.mapeditor.org/en/latest/reference/tmx-map-format/#imagelayer) (I think this is not yet supported by the editor)

Dealing with (additional) parsing, rendering and operating on the TMX file would not be part of pixi.js.

> I think tmx is not necessary.
> tmx is xml, parsing xml is complex & slow.

While I agree that using JSON seems more natural, `PIXI.loaders.Loader` is already able to load `.tmx` files [via resource-loader](https://github.com/englercj/resource-loader/blob/v2.1.0/src/Resource.js#L1030), so I think we should not neglect it. Also the requirements for the `tmxParser` that I listed above are independent of JSON/TMX.

@ivanpopelyshev What do you think?

**Comment by winniehell** [comment]
> What I would like to see in pixi.js is a tmxParser

Just for reference: Decision has been made not to include such a parser in PixiJS v5 (https://github.com/pixijs/pixi.js/pull/4583#issuecomment-355852001).

**Comment by themoonrat** [comment]
Closing, but thanks for sharing!
