### ISSUE TITLE
Rectangle.top/left/right/bottom returns incorrect values with negative size

### ISSUE THREAD

**Issue by markknol** [pixijs/pixi.js#4310]
At the moment I see that for example `Rectangle.top` just returns the `y` value. This is not what I would expect when the height is a negative value, since the description says _top edge of the rectangle_. Of course one should avoid negative width/height but in some cases that can happen.

I would suggest to use this: 

* For `top` it should return `return Math.min(this.y, this.y + height)`
* For `bottom` it should return `return Math.max(this.y, this.y + this.height);`
* For `left` it should return `return Math.min(this.x, this.x + this.width);`
* For `right` it should return `return Math.max(this.x, this.x + this.width);`

**Comment by ivanpopelyshev** [comment]
Rectangle size is always positive. Make your own OrientedRectangle and use it. If you want pixi to do that, hack 

```js
Object.defineProperties(PIXI.Rectangle.prototype, {
    'top': {
       'get': function() { ...}
    }
});
```

Or fork it, just change it in sources and build your version of pixi.

**Comment by markknol** [comment]
Yes well I just created my own rectangle, but I personally think it shouldn't matter if the size is positive or negative. It is not documented that the size should be positive, so I would either add that to the docs or fix it as I proposed. I wouldn't mind to PR the latter.

**Comment by ivanpopelyshev** [comment]
There is abstraction AABB, Axis-Alighned-Bounding-Box, it exists in all gamedev engines, 2d and 3d. In PIXI its represented by Bounds and Rectangle. 

You are talking about Oriented AABB, I dont remember where did I see it but I guess its not rare ;)
