### ISSUE TITLE
rgb2hex utility function is broken

### ISSUE THREAD

**Issue by meverett** [pixijs/pixi.js#4314]
To test this, load Pixi and try this following snippet:

```
var areColorsEqual = PIXI.utils.rgb2hex([255, 0, 0]) === 0xff0000;
```

You'll find the answer is false, even though the intended hex output should be red (0xff0000).

The answer lies in the function's implementation:

```
export function rgb2hex(rgb)
{
    return (((rgb[0] * 255) << 16) + ((rgb[1] * 255) << 8) + (rgb[2] * 255 | 0));
}
```

Not sure why the individual components are being added with a '+'. Shouldn't they be combined bitwise with a '|' instead? 

Anyways, here is an implementation which works as intended:

```
export function rgb2hex(rgb)
{
        return rgb[2] | (rgb[1] << 8) | (rgb[0] << 16);
}
```

The incorrect output from the function as it stands now is: **-33488896**

If you check the numeric value of the hex for red, it is: **16711680** and not **-33488896**.

The function I have offered correctly produces the output **16711680** for **[255, 0, 0]**.

Thanks!

**Comment by ivanpopelyshev** [comment]
Rgb array numbers are in 0..1 interval. I now that flash uses 0..255 but here its 0..1

**Comment by meverett** [comment]
My mistake! 0-1 makes sense, I'm just very used to RGB generally being specified as 8 bits per color. Disregard this comment then!

**Comment by ivanpopelyshev** [comment]
There are many problems with colors, its ok to miss them. Btw, checkout this thing if you want better tint for sprites: https://github.com/gameofbombs/pixi-heaven
