### ISSUE TITLE
Uncaught TypeError: Cannot read property 'baseTexture' of undefined at ParticleContainer.renderWebGL

### ISSUE THREAD

**Issue by CuAnnan** [pixijs/pixi.js#4315]
I saw that my game uses between 20 and 35% of the CPU

Since I'm using any of the snazzy functions that Container would profer, I thought to use ParticleContainer. But when I change my code to use PIXI.particles.ParticleContainer, I get the above exception. Since all of my addedChildren are instantiations of the PIXI.Graphics class, I'm having trouble figuring out a solution.

**Comment by ivanpopelyshev** [comment]
ParticleContainer doesn't work with Graphics. However we had many cases like that, and there are many optimizations for them. 

Just describe it more and we'll find solution for your case :)

**Comment by CuAnnan** [comment]
I'm building a map with some 8000+ irregular, but solid, polygon cells that need to be interactable, but fixed position (so mouseover, mouseout and click events bound). These 8000+ cells are drawn in place using the Graphics object with their x and y coordinates provided by the Map class. They're all added to a stage class which I keep a module/function scoped stage variable for. Which is rendered in the animationRequestHandler function.

From reading through the internet about using Graphics, it's less efficient than using Sprites, but I can't figure out a way to turn all of my procedurally generated cells into Sprites on the fly.

**Comment by ivanpopelyshev** [comment]
I can give you simple optimizations that possibly solve your case. If not, we'll move to something more hardcore.

## Tilemap

### Single chunk

The idea is to maintain big Graphics object that contains everything on a certain rectangle that is bigger than camera. Once camera is out of it, you have to move the rectangle that way its center is the  same as camera's and refill tilemap with polygons. To make it easier, you can store PIXI.Polygon objects somewhere and re-add only those of them who are inside rectangle. 

### Many chunks

Maintain multiple Graphics objects, each containt 8x8 cells or so. Set "renderable" to false for those that are not seen by camera. You can also use that "discrete moving rectangle" trick for it.

## Interaction

Yeah, you'll have problems with interaction in any case. Please define your own containsPoint() method for tilemap, that finds which polygon can contain mouse, and then check only that polygon.
