### ISSUE TITLE
[FEATURE] add clearRect method to PIXI.RenderTexture

### ISSUE THREAD

**Issue by akhimchak** [pixijs/pixi.js#4321]
Hi, is there a way to add something like this?
```
import * as PIXI from 'pixi.js';

const app = new PIXI.Application(800, 600);
const renderTexture = PIXI.RenderTexture.create(800, 600);
const car = new PIXI.Sprite(PIXI.utils.TextureCache['car']);

app.renderer.render(car, renderTexture)

const x = 0;
const y = 0;
const width = 100;
const height = 100;

// missed API
renderTexture.clearRect(x, y, width, height);
```

**Comment by ivanpopelyshev** [comment]
There's a hack of how to clear something: http://www.html5gamedevs.com/topic/31803-scratch-card-effect/?tab=comments#comment-182673

**Comment by akhimchak** [comment]
Thank you, sir!

**Comment by ivanpopelyshev** [comment]
Btw, there's no clearRect in webgl, so partial clear happens as "just render alpha=0 over that rectangle" anyway.

**Comment by akhimchak** [comment]
Thank you very much for your detailed explanation and for your time.
