### ISSUE TITLE
Affine 2d Matrix elements order

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4324]
Look at the order of "b" and "c" variables:

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Matrix.html
https://developer.apple.com/documentation/coregraphics/cgaffinetransform

Pixi matrix is same as in swift, while Spine prefers flash style. Every time I merge pixi-spine with upstream, I have to change b<->c in the places where I use Pixi matrix.

Personally, I like Pixi/swift way of things, where "(a,b)" has a meaning - its global coords of local X axis vector (1,0).

UPD. In flash, (a,b) affects result X when you apply transform to a point.

I dont want to live on this planet anymore.

**Comment by ivanpopelyshev** [comment]
!@#$ I'm an idiot.

Look into russian documentation: http://help.adobe.com/ru_RU/FlashPlatform/reference/actionscript/3/flash/geom/Matrix.html

and in english: 

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Matrix.html

**Comment by Busyrev** [comment]
http://service.crazypanda.ru/v/clip2net/k/f/Oq9soQ9OAY.png
