### ISSUE TITLE
Component Shown Events?

### ISSUE THREAD

**Issue by simplygreatwork** [pixijs/pixi.js#4325]
Java Swing had component events and a method specifically: componentShown. I do see that Pixi has events for 'added' and 'removed'. But is there currently a strategy in Pixi to know when a DisplayObject is currently fully visible and connected in the display hierarchy?

I want to be informed when a display object has been added and is visible - and *then* be able to look up an ancestor display object to attach an 'emit' or 'on' to that ancestor. My actual goal is to emit 'view-has-entered' after a tween. I'll keep searching for an answer but I wanted to ask. If I use my own higher-level PubSub implementation I don't encounter this issue - but I'm trying to use EventEmitter3 "properly" in Pixi.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/issues/4179

**Comment by ivanpopelyshev** [comment]
For now you can override Container's addChild and removeChild to work like you need it. Add variable "stage" to container prototype and set it on add/remove, recursively.

**Comment by simplygreatwork** [comment]
Thank you so much for your attention, Ivan. I'll review your links and comments and revisit a bit later today...

**Comment by ivanpopelyshev** [comment]
@simplygreatwork yeah :) I used swing but i dont remember how is it implemented there. Can you provide more details? What is "stage" in its case?

**Comment by simplygreatwork** [comment]
I considered overriding DisplayObject.renderWebGL to emit 'rendered' or something like that. I had some hanging issues so I moved on. But something like that could possibly work.

In my project, I have layout methods I'm currently calling 'draw'. Inside of 'draw', I now emit 'shown'. At this point, I know that everything is on screen, and so on('shown') I'm able to lookup the ancestor (parent) I need.

The main point to take from this is - just because a display object is added to another - it doesn't necessarily mean that it's has been rendered to the screen. Looking up an ancestor doesn't necessarily require a stage container to be defined. The ancestor might not be the stage.

Needs more polish and review but this is what I'm going now...
https://github.com/simplygreatwork/goodshow/blob/master/goodshow/entity/Graphics.js#L103
https://github.com/simplygreatwork/goodshow/blob/master/goodshow/component/Markup.js#L34

**Comment by ivanpopelyshev** [comment]
Yep, looks like workaround that is not yet integrated into pixi pipeline, simple setTimeout can do it. 

So you set timeout on function that checks whether object was added and not removed afterwards some time ago, then emit "shown"?

**Comment by simplygreatwork** [comment]
Yes, I did previously successfully use setTimeout. I wasn't sure whether that would be correct. I did realize that what I was trying to do was a bit incorrect: inside/out instead of outside/in. I was trying to present some floating HTML content above Pixi after the view slid in. Synchronizing HTML views with Pixi is going to take a lot of study. I'll close this. Thanks.

**Comment by Hoangminhtrang0109** [comment]
Nguyễn Văn Công
