### ISSUE TITLE
Samsung Galaxy s8+ international, exynos processor ,filter problems

### ISSUE THREAD

**Issue by albymack** [pixijs/pixi.js#4330]
I saw an old issue about rendering problems with galaxy s8+.  The issue I'm running into is even more specific to the galaxy s8+ international version only.  Some of the pixi filters causes black screen on the s8+ international.  Even the pixi filters demo page itself will exhibit these problems on an s8+ international version.  The US version with the snapdragon processor works fine.

Filters that I know don't seem to work even on the pixi-filters demo include the glow filter and the ascii filter (both of which blackscreens).  The distortion filter also behaves erratically, sometimes working and sometimes causing a blackscreen on a galaxy s8+ international in my own project, though it seems to work on the pixi filters demo page.

I've tried setting legacy flag when creating the renderer, which doesn't seem to resolve the issue.

Has anybody else run into this, and can offer some insights into how I might go about resolving this?

**Comment by ivanpopelyshev** [comment]
Which version of chrome is it?

I suspect the nature of it, so lets try:

```js
var renderer = new PIXI.WebGLRenderer( {
   antialias: true
});
```

And if it doesnt work lets try to sacrifice some performance:

```js
var renderer = new PIXI.WebGLRenderer( {
   antialias: true,
   preserveDrawingBuffer: true
});
```

**Comment by SeminYun** [comment]
we have same problems..

**Comment by ivanpopelyshev** [comment]
OK, now really many people have that problem. I know several others.

**Comment by themoonrat** [comment]
I had issues with the S8 too... where larger textures generate via Text would randomly show / not show. I ended up just blacklisting the default browser version from being able to use WebGL.... later Chrome versions must blacklist a driver or something that the S8 uses and fixes any S8 problems for me!

**Comment by nikkop** [comment]
Is there any way to catch this behavior? In case there's some issue with webgl, catch it and then do something (up to the developer).

For example, if not being able to use a filter, simply don't use it instead of using it and displaying all wrong.

**Comment by themoonrat** [comment]
Closing because I found that updated browser versions fixed this issue on this device.
At the time, I just detected if it was the "SamsungBrowser" and had Chrome version of less than 58, and if so, forced to be in Canvas mode.
