### ISSUE TITLE
webglrenderer.clearRenderTexture does not update gl viewport and scissor mask

### ISSUE THREAD

**Issue by nidefawl** [pixijs/pixi.js#4333]
I had a problem where my RenderTexture wasn't fully cleared by calling 
`renderer.clearRenderTexture(renderTexture, 0);`

Turns out the webgl implementation doesn't disable the scissor mask and also does not update the viewport before clearing the framebuffer.

Also, clearRenderTexture method is not present in the canvas renderer.

**Comment by ivanpopelyshev** [comment]
Do you call it from outside of render() of from inside?

**Comment by themoonrat** [comment]
@nidefawl Do you have any update on this issue please? Are these still issues on the latest pixi version?
