### ISSUE TITLE
Alpha on container affects children in unexpected way

### ISSUE THREAD

**Issue by nikkop** [pixijs/pixi.js#4334]
When two sibling Graphics objects (or Sprites) are overlapping and their parent's (in this case a container) alpha is being manipulated, the results are not what I'm expecting. When setting the container alpha to 0.5, both the children will behave as if themselves had an alpha of 0.5 (even though they have an alpha of 1)

What's actually happening:
![alphaissue1](https://user-images.githubusercontent.com/6517126/30970201-cbeb4610-a464-11e7-9ad3-f293ab75351b.jpg)
[jsfiddle](https://jsfiddle.net/6jau9e29/1/)

What I was expecting:
![alphaissue](https://user-images.githubusercontent.com/6517126/30970075-8851feee-a464-11e7-8a6b-8c37d4ab6468.jpg)

Is this a bug or am I thinking wrong about the behavior? If so, how do I get the behavior I am looking for? I'm used to change opacity of groups/layers and I was hoping it would work the same in Pixi. I tried to search for it but no success.

Thanks in advance

**Comment by ivanpopelyshev** [comment]
Its not a bug. You need to do it in a separate layer, either using filter either renderTexture:

### Filter

```js
var voidFilter = new PIXI.filters.VoidFilter();
container.filters = [voidFilter];
```

but in current pixi version it doesnt work with alpha, so for now you need a filter that  treats alpha correctly:

```js
var colorMatrix= new PIXI.filters.ColorMatrixFilter();
colorMatrix.alpha = 0.5;
container.filters = [colorMatrix];
```

@GoodBoyDigital @bigtimebuddy  we really need to add alpha or tint to VoidFilter!

### RenderTexture

This one doesnt work in realtime :( Its just snapshotting the container and then applying alpha on that texture. Im posting clear solution, without "cacheAsBitmap" and "generateTexture", those things have not enough info to do the alpha fix.

```js
var bounds = container.getBounds();
var x2 = Math.ceil(bounds.x + bounds.width);
var y2 = Math.ceil(bounds.y + bounds.height);
bounds.x = Math.floor(bounds.x);
bounds.y = Math.floor(bounds.y);

var trans = new PIXI.Matrix();
trans.tx = -bounds.x;
trans.ty = -bounds.y;

var renderTexture = PIXI.RenderTexture.create(bounds.width, bounds.height);
renderer.render(container, renderTexture, null, trans);

var sprite = new PIXI.Sprite(renderTexture);
sprite.position.x = bounds.x;
sprite.position.y = bounds.y;
sprite.alpha = 0.5;
stage.addChild(sprite);
```

**Comment by nikkop** [comment]
@ivanpopelyshev Thanks  alot for your explanation and suggestions of approaches. I now have a better understanding of it.

I would be interested in running the approach with ColorMatrixFilter. However, I can't get it to work as it doesn't seem to have any effect at all. Could you please fork my provided fiddle with the solution?

Thanks in advance

**Comment by ivanpopelyshev** [comment]
Ugh, you are right!

Lets fix that.

```js

`
varying vec2 vTextureCoord;

uniform sampler2D uSampler;
uniform float uAlpha;

var frag = `void main(void)
{
   gl_FragColor = texture2D(uSampler, vTextureCoord) * uAlpha;
}
`;

var vert = `
attribute vec2 aVertexPosition;
attribute vec2 aTextureCoord;

uniform mat3 projectionMatrix;

varying vec2 vTextureCoord;

void main(void)
{
    gl_Position = vec4((projectionMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);
    vTextureCoord = aTextureCoord;
}
`;

function AlphaFilter() {
   PIXI.Filter.call(vert, frag);
   this.alpha = 1.0;
}

AlphaFilter.prototype = new PIXI.Filter();
AlphaFilter.prototype.constructr = AlphaFilter;

Object.defineProperties({
   alpha: {
       get: function() { return this.uniforms.uAlpha; }
       set: function(value) { this.uniforms.uAlpha = value; }
   }
});

```

**Comment by ivanpopelyshev** [comment]
I havent tested this yet, so you have to fix it if you see an error.

**Comment by ivanpopelyshev** [comment]
And, updated again.

**Comment by ivanpopelyshev** [comment]
It seems that I mixed ES5 and ES6 here.. please rewrite it that way it works for your case :)

**Comment by nikkop** [comment]
Thank you so much for your time and effort and I'm glad to say it is working!
I now get the desired effect and you can spot it here: [jsfiddle](https://jsfiddle.net/gdrpzfq7/)

I just had to fix some typos in your class example, so I'll post the working one here:

```
class AlphaFilter extends PIXI.Filter {
    constructor() { super(vert,frag); this.alpha = 1.0; }
    get alpha() { return this.uniforms.uAlpha; }
    set alpha(value) { this.uniforms.uAlpha = value; }
}
```

Perhaps this could be added in future releases?

**Comment by ivanpopelyshev** [comment]
I'll make PR to add alpha to the VoidFilter itself.

**Comment by bigtimebuddy** [comment]
Can we rename VoidFilter to AlphaFilter? I think it should be named for the use-case.

**Comment by ivanpopelyshev** [comment]
I took that name from VirtualDub: filter that does nothing but allows to use all the features inside it. I agree, I'll rename it and put a deprecation notice.

**Comment by bigtimebuddy** [comment]
Thanks 👍
