### ISSUE TITLE
Jittering when using split screen iframes for multiple pixijs applications/instances

### ISSUE THREAD

**Issue by dupuis2387** [pixijs/pixi.js#4335]
So I'm not sure if this is a bug or just not doable, but I have something similar to this plunk i created:

[https://plnkr.co/edit/F9ERb0FThEZIjSMttxHS](https://plnkr.co/edit/F9ERb0FThEZIjSMttxHS)

where I just copied the sample code for Masking+renderTexture from 

[http://pixijs.github.io/examples/#/demos/mask-render-texture.js](http://pixijs.github.io/examples/#/demos/mask-render-texture.js)

In the plunk, it's two iframes, side-by-side which share the same pixijs application/JS file, and only in chrome, do I see the first one, on the left, "jitter/jump" when "drawing" with the brush. The one on the right works fine. 

If I nuke one of the iframes, everything works fine....

Is a setup like this just not supported? I didnt see the issue in Firefox, nor IE, nor Safari on iOS 11, nor Chrome in iOS11...wondering if it's just a Desktop Chrome bug?

Thanks for any help!

**Comment by ivanpopelyshev** [comment]
I didnt think drawing demo will be THAT popular, there are multiple threads in html5gamedev forum about it for last month.

I dont see jittering, I think it depends on configuration. I agree that there can be problems.

Workaround: 

1. MEDIUM: use different method for drawing, one of them was described here: http://www.html5gamedevs.com/topic/33107-masking-rendertexture-and-its-positioning/

2. EASY: may be simple params like  "{ antialias: true; }" in the renderer/application options can affect that issue.

**Comment by dupuis2387** [comment]
So from your MEDIUM example, you're saying replacing 

```
brush.position.copy(event.data.global);
app.renderer.render(brush, renderTexture, false, null, false);

```           
with 

```
renderTextureSprite.toLocal(event.data.global, undefined, brush);
brush.x += renderTextureSprite.anchor.x * renderTexture.width;
brush.y += renderTextureSprite.anchor.y * renderTexture.height;
app.renderer.render(brush, renderTexture, false, null, false);

```            

? If that's so, i just tried modifying the plunk, and it still happens in Chrome...or did I misunderstand your suggestion?

**Comment by ivanpopelyshev** [comment]
No, that's not related :) You just have to read the thing about how to use Canvas2d + fromCanvas thingy and implement it. Right now i dont have code for that solution.

**Comment by dupuis2387** [comment]
Oh, right on. I'll try that part, then. Thanks!

**Comment by themoonrat** [comment]
Seems answered!
