### ISSUE TITLE
PIXI.Graphics.drawRoundedRect with radius 0 does not correctly render outline in WebGLRenderer

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#4337]
Hi. Nice library. I think I found a bug.

**Issue:** Outline of rounded rect with radius 0 is rendered incorrectly for WebGLRenderer when ``PIXI.Graphics.drawRoundedRect`` is called with radius 0. This does not look like an issue for CanvasRenderer.
**Expected:** Outline of rounded rect with radius 0 should be rendrered like outline of regular rect.
**Severity:** Low - can work around by calling ``PIXI.Graphics.drawRect`` instead by checking if radius being passed is 0.
**Version:** 4.5.1
**Example:** https://jsfiddle.net/1z6qd7s5/7/

Thanks in advance.

**Comment by robberfree** [comment]
@uzawaj i meet this problem too.i also use `drawRect` as a option.

i also meet some strange thing when use linewidth and radius to draw `roundedRect`.
like this:
![2017-11-23 10 14 59](https://user-images.githubusercontent.com/15938895/33156707-3eda6de2-d037-11e7-8cdf-b15f3b3f56ce.png)
![2017-11-23 10 15 04](https://user-images.githubusercontent.com/15938895/33156708-3edcab52-d037-11e7-95e5-1570d45e2078.png)
do you know why?
thanks.

**Comment by andresilvasantos** [comment]
@robberfree did you find a solution? I'm having the same issue.

**Comment by andresilvasantos** [comment]
I found out that setting the radius as half the height of the rectangle would cause this. If the radius is set to (height / 2 - 1) it will render properly. Also, I experimented the line to be drawn with the native argument set, which draws all the line, but the width of the line will be ignored.

**Comment by bigtimebuddy** [comment]
We just need a little bit of logic in the rounded rectangle class for handling this case. PR welcome if anyone wants to take a crack at it.

**Comment by bigtimebuddy** [comment]
Fixed by #6539
