### ISSUE TITLE
Mesh.Plane. TextureAtlas (uvs) not updated.

### ISSUE THREAD

**Issue by hirowaki** [pixijs/pixi.js#4339]
Hi!

I have code like this expecting the texture uvs are updated. But it won't.
```
// Here anotherTextureAtlas is not another BaseTexture.
// It's another texture atlas (same BaseTexture but different uvs).

plane.texture = anotherTextureAtlas;
```
The issue is similar to [#4296](https://github.com/pixijs/pixi.js/issues/4296) and [#4299](https://github.com/pixijs/pixi.js/pull/4299).

I have no idea whether this is an expected behavior or not. But let me report what I found.

### The issue.
* Using PIXI 4.5.6
* `plane.texture = differentTexture` is working.
* But `plane.texture = differentTextureAtlas` is not working.

### What I found.
It looks both `Mesh.Plane.prototype.texture` and `Mesh.Plane.prototype._onTextureUpdate` don't update the `dirty` counter. Then WebGL `MeshRenderer.prototype.render` won't upload `uvBuffer` even when the mesh data was processed by `_refresh`.

In MeshRenderer.prototype.render, I can see this if statement is not hitting true.
```js
if (mesh.dirty !== glData.dirty) {
    glData.dirty = mesh.dirty;
    glData.uvBuffer.upload(mesh.uvs);
}
```

### Workaround.
The workaround I have is the following.
```
plane.texture = anotherTextureAtlas;
plane.dirty++;
```

### Sample code to repro.
I made a sample code to reproduce the issue on jsfiddle. Please check this out.
https://jsfiddle.net/hirowaki/7kdufLjt/

Thank you!

**Comment by ivanpopelyshev** [comment]
OK, I've made PR, we can test it here : https://pixijs.download/dev-plane-dirty-fix/pixi.js

Also, workaround: set `plane.uploadUvTransform` to true

**Comment by bigtimebuddy** [comment]
Verified with fix: https://jsfiddle.net/bigtimebuddy/x1w4rycq/
