### ISSUE TITLE
Sprite.on("click") doesn't support mobile/touch

### ISSUE THREAD

**Issue by cawoodm** [pixijs/pixi.js#4340]
For mobile platforms it would be good if the "click" event was also triggered by a "touch" event. Sprite.on("click") is not fired on a tap currently.

**Comment by bigtimebuddy** [comment]
Try using "pointertap" instead of "click" https://pixijs.download/v4.5.6/docs/PIXI.DisplayObject.html#event:pointertap

In PixiJS interactive events for touch and mouse are normalized as pointer events. Use those event works for both.
