### ISSUE TITLE
chrome issue on macos

### ISSUE THREAD

**Issue by ramarro123** [pixijs/pixi.js#4342]
Hello, 

i am having issue with chrome Versione 61.0.3163.100 (Build ufficiale) (a 64 bit)
on osx 10.11.6

the machine can be considered high end (imac 27inch, 16gb ram etc etc)

the problem happen on almost all examples, there is screen flickery or choppy animation.

the particle example with bugs, canvas became black and every 2-3 secs i see a flash with all bugs.

cacheasbitmap example lag every time to time, and sometimes the canvas become black (it's not as severe as particle example)

on my own app, everything lag as a crazy and it's not usable.

i will test the same machine with safari & firefox, i'll leave the ticket here as a reference

devel console doesn't show any error

**Comment by ivanpopelyshev** [comment]
What about other webgl renderers? Are there any problems with threejs? https://threejs.org/examples/

**Comment by ramarro123** [comment]
yes, same problem, choppy animation at the very best, major issue on other examples.

so it's a browser problem?

**Comment by ivanpopelyshev** [comment]
Videodrivers.

**Comment by ramarro123** [comment]
i am running the latest version of osx, that normally include even graphics driver. the only option that i have it's to update to sierra, but, i can't then ask to all my customers that run elcaptain to update to sierra :)

i'll wait to see if we have any feedback from chromium bugtracker.

on safari, same machine, some everything, it work, so, at the very least, it's the chrome implementation that have some issue with that driver, but not safari?

**Comment by ivanpopelyshev** [comment]
Its possible. Chrome quality suffers last year :(

**Comment by chris-t-reilly** [comment]
[Here is a video of a similar issue.](https://www.youtube.com/watch?v=ZcGlgADqWkM&feature=youtu.be)

**Comment by ivanpopelyshev** [comment]
Bucking hell with a framebuffer. @ramarro123 @chris-t-reilly what if we enable antialias on that context? I dont mean pixijs main site demo, just find an example that doesnt work properly at https://pixijs.github.io/examples/#/basics/basic.js and pass {antialias:true}into renderer/app options.

**Comment by ramarro123** [comment]
it doesn't make any difference with or without antialias :( 
i'll try to do some more tests later.

chrome bugtracker say that there isn't any issue at all in chrome (as always, deny it's the first step lol)

i can reproduce it on both treejs (on the examples as suggested, i don't use threejs on my own) and here in pixi on both examples and on my code.

**Comment by themoonrat** [comment]
Closing as it seems like it's not a pixi issue.
Hopefully the browsers updating have fixed this in the meantime!
