### ISSUE TITLE
Feature Request: Set a custom frame order or loop for AnimatedSprite

### ISSUE THREAD

**Issue by griest024** [pixijs/pixi.js#4346]
It would be cool if you could add a field to `AnimatedSprite.FrameObject` that designates the next frame to play after the current one. It would save me from having a bunch of `AnimatedSprites` just to implement a single character.

I would be willing to submit a PR if you are open to this feature.

**Comment by ivanpopelyshev** [comment]
Lets open it: https://github.com/pixijs/pixi.js/blob/dev/src/extras/AnimatedSprite.js#L30

Now, what do you want me to add there?

**Comment by bigtimebuddy** [comment]
If you wouldn't mind, could you please explain your proposal more and give a concrete example of how it would be used.

**Comment by griest024** [comment]
@ivanpopelyshev see #4348

@bigtimebuddy For example, if I had multiple animations for walking in a specific direction:

```
new PIXI.extras.AnimatedSprite(
    {texture: PIXI.Texture.from('walkUpLeftFoot.png', time: 0.2},
    {texture: PIXI.Texture.from('walkUpRightFoot.png', time: 0.2, next: 0},
    {texture: PIXI.Texture.from('walkDownLeftFoot.png', time: 0.2},
    {texture: PIXI.Texture.from('walkDownRightFoot.png', time: 0.2, next: 2},
    {texture: PIXI.Texture.from('walkLeftLeftFoot.png', time: 0.2},
    {texture: PIXI.Texture.from('walkLeftRightFoot.png', time: 0.2, next: 4},
    {texture: PIXI.Texture.from('walkRightLeftFoot.png', time: 0.2},
    {texture: PIXI.Texture.from('walkRightRightFoot.png', time: 0.2, next: 6}
)
```
