### ISSUE TITLE
How to feather or blur edges?

### ISSUE THREAD

**Issue by nikkop** [pixijs/pixi.js#4347]
Hi there,

I'm looking for a way to feather or blur edges of a graphics object/sprite. What would be the best way to achieve this? 

For example I would like to be able to achieve something similar to this:
![featheredges](https://user-images.githubusercontent.com/6517126/31180009-c0a903d8-a91d-11e7-928c-2107bb9aefa2.jpg)

Is there any way to do this while still having OK performance? I have tried various methods using BlurFilter (with blur value of 40 and 5 passes) and Masks, but it's simply too demanding to get the desired effect and hurt performance too much on tablets and mobile phones.

I would try out anything possible
I'm currently running v.3.0.8 and upgrading is not an option at this time.

Best regards

**Comment by finscn** [comment]
It lets me remember an old issue :  https://github.com/pixijs/pixi.js/issues/3139

**Comment by nikkop** [comment]
Yes I got into that issue while searching but the difference is I'm not looking to necessarily mask my sprite in before doing the blur/feather. I'd like to do it on a graphic or unmasked sprite.

Did you solve it somehow?

**Comment by ivanpopelyshev** [comment]
I ahve an idea: take a Graphics, add BlurFilter, then SpriteMaskFilter on it, pass sprite image to SpriteMaskFilter constructor.

**Comment by ivanpopelyshev** [comment]
Though I recommend to cache blurred graphics into a texture:

```js
var rt = PIXI.RenderTexture.create(W1, H1);
var spr = new PIXI.Sprite(PIXI.Texture.WHITE);
spr.anchor.set(0.5);
spr.width = W2;
spr.height = H2;
spr.filters = [blurFilter];
var tex = renderer.generateTexture(spr);

//use tex as a texture for mask sprite or masked sprite
```

**Comment by finscn** [comment]
What's mean of `then SpriteMaskFilter on it` , @ivanpopelyshev ?

**Comment by ivanpopelyshev** [comment]
@finscn If an element has mask and filters, mask is applied "inside" filters. You can manually add mask to filters array in the place you want it, just use SpriteMaskFilter for it.

**Comment by djmisterjon** [comment]
any help please , am tring to do same thing here but filter not work ?

```javascript
    var blur = new PIXI.filters.BlurFilter(10);
    var texture = new PIXI.Sprite(PIXI.Texture.WHITE);
    texture.width = 500, texture.height = 40;
    texture._filters = [blur]; // add blur to texture

    this.addChild(texture);
    this.mask = texture; // add texture as mask to the parent
```
![sans-titre-1](https://user-images.githubusercontent.com/24865815/32983469-17f38132-cc63-11e7-8ec2-b1744fe17457.jpg)
#4451

**Comment by themoonrat** [comment]
closing as the original question was given an answer
@djmisterjon if you're still having problems, please open a new issue :)
