### ISSUE TITLE
Incorrect color rendering 

### ISSUE THREAD

**Issue by antontereshin1992** [pixijs/pixi.js#4356]
Hello.

I ran into strange bug. I think it's depends on the latest updates of the G. Chrome or something like that, because it did not appear before.

I use the latest version of the pixi.js lib for current time - it's 4.5.6.
 
When I use the **PIXI.WebGLRenderer** - colors of all sprite have changed. (became dimmer)
When I use the **PIXI.CanvasRenderer** - colors are still right untill I change text in any instance of PIXI.Text component. ... after that all sprites became dimmer too.

For view I'm attaching a screenshot of the color changing and URL of this picture on G. Drive.

![123](https://user-images.githubusercontent.com/15610915/31338422-cebf919c-ad07-11e7-97d4-c639db3eefaa.png)

https://drive.google.com/file/d/0B9xC8Ta34EqSTFNfWmtIdml1d1U/view

P.S. Sorry for my english. :-)

**Comment by ivanpopelyshev** [comment]
Do you use tint on sprites? If not, then you have a problem with videodrivers.

**Comment by antontereshin1992** [comment]
No, I don't use any tint for sprites. Also I checked it with another device but got the same behavior. ... so I think it is not videodrivers

**Comment by antontereshin1992** [comment]
But not reproduced after Chrome update
