### ISSUE TITLE
Jagged strokes on tiny polygons.

### ISSUE THREAD

**Issue by XerxesNoble** [pixijs/pixi.js#4361]
Hi there,

We are coming across an issue when rendering tiny polygons with a stroke. The stroke does not seem to be lining up with the shape itself, causing the shape to appear jagged. 

I've attached a working code sample to paste into your examples app. Further, I've attached an image of the jagged shape.

```javascript
var app = new PIXI.Application(800, 600, { antialias: true });
document.body.appendChild(app.view);

var graphics = new PIXI.Graphics();

// set a fill and line style
graphics.beginFill(0xFF3300);
graphics.lineStyle(0.1, 0xFFFFFF, 1);

var shape = [0.084, 0.52, 0, 0.497, 0.029, 0.394, 0.005, 0.387, 0.114, 0, 0.305, 0.034, 0.308, 0.018, 2.663, 0.437, 2.652, 0.499, 4.171, 0.767, 3.439, 3.2, 2.836, 3.02, 2.465, 4.253, 2.205, 4.178, 1.369, 3.947, 0.53, 3.728, 0.018, 3.6, 0.723, 1.101, 0.084, 0.52];

// draw a shape
graphics.drawPolygon(shape);

graphics.endFill();

graphics.scale.set(90);
graphics.position.set(150, 150);

app.stage.addChild(graphics);
```

![screenshot 2017-10-12 14 00 39](https://user-images.githubusercontent.com/5123814/31511558-22e12c0e-af56-11e7-9b5d-d2db3dcb3482.png)

**Comment by ivanpopelyshev** [comment]
Wow, that's interesting bug.

**Comment by XerxesNoble** [comment]
@ivanpopelyshev 


For a bit more insight, after playing around. I tried to filter out all points that are no less than 0.5px apart from each other, and got an acceptable result.. however.. I'm unsure if this is a proper solution that will work across all shapes. It may hopefully help you pinpoint what is going on though.


```javascript
// Merge points into tuples, for distance checking
var points = shape.map((point, i) => i%2 === 0 ? [point, shape[i+1]] : null).filter(p => p)

// Set a minimum distance for points
var MIN_DISTANCE = 0.5

// Create a list of points that are no less than 0.5px apart from siblings
var farPoints = points.reduce((list, point, i) => {
  var previousPoint = list[list.length - 1]
  if (previousPoint) {
    var distance = distanceBetween(previousPoint, point)
    if (distance > MIN_DISTANCE) list.push(point)
  } else {
    list.push(point)
  }
  return list
}, [])

// Flatten points back to polygon array
shape = [].concat(...farPoints)

function distanceBetween(a, b) {
  return Math.sqrt(Math.pow((b[0] - a[0]), 2) + Math.pow((b[1] - a[1]), 2))
}
```

**Comment by bigtimebuddy** [comment]
I remember seeing this precision issue with Graphics #3690. However, I'm pretty sure this is mobile-related and has to do with larger numbers. Seems like a precision issue drawing small. @ivanpopelyshev would be the person to know.

**Comment by ivanpopelyshev** [comment]
Its strange, because vertex shaders already have high precision in latest pixi version.

**Comment by ivanpopelyshev** [comment]
And it actually reproduced on PC. What. The. Hell?

**Comment by ivanpopelyshev** [comment]
I think that's the place: https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/webgl/utils/buildLine.js#L166
