### ISSUE TITLE
ParticleContainer Canvas Tint Bug

### ISSUE THREAD

**Issue by TazOen** [pixijs/pixi.js#4364]
Hi, I'm loving the tint support for WebGL ParticleContainer, but with Canvas-fallback rendering the sprites aren't getting tinted! Is there any help for this?

P.S. - I tested on updated Chrome and Firefox on MacBook, using the example at https://pixijs.github.io/examples/#/demos/batch.js, but changed it to pass forceCanvas:true to PIXI.Application.

**Comment by ivanpopelyshev** [comment]
`ParticleContainer.renderCanvas` certainly wont speed up anything if you use tint, and I certainly dont like copy&paste there:

this is particlecontainer's "optimized" thingy:

https://github.com/pixijs/pixi.js/blob/dev/src/particles/ParticleContainer.js#L245

this is standart canvas sprite renderer:

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/canvas/CanvasSpriteRenderer.js#L42

As you see, not only "canvasTinter" is missing, but also rotate/trim isn't supported in particleContainer canvas version, Best fallback is to create Container if `renderer.type != PIXI.RENDERER_TYPE.WEBGL` .

@bigtimebuddy please tell me what to do with this thing.

**Comment by ivanpopelyshev** [comment]
Technically, ParticleContainer helps if there are 1000 or so elements, and Canvas wont be able to renderer that in acceptable time. 

At the same time, there's no significant speedup under webgl for 100-200 elements for ParticleContainer. 

Are you sure that you want to use ParticleContainer at all?

**Comment by TazOen** [comment]
Actually for really small particles (mine are 7x7 pixels) Canvas fallback can handle a few 1000 elements at 60 FPS (even on my 5-year old MacBook with Canvas 2D GPU Acceleration disabled, for instance). Using ParticleContainer is giving a nice little performance boost over Container, but I really need the tinting for a falling sand game that I'm tinkering with...

Maybe thousands of tiny tinted particles on Canvas fallback is too obscure a use case... IMO it would be good to update the docs thou to say which properties are WebGL only, otherwise it seems like a bug when a property doesn't work for Canvas :)

**Comment by ivanpopelyshev** [comment]
Ok, now you've persuaded me to fix it :)

**Comment by TazOen** [comment]
That would be awesome! I'm using one container for all of the sand particles with different tint colors for different sprites (newly added sprites get their tint set to the player's current color selection). I can make a minimal CodePen demo to help test this use case if would help?

**Comment by ivanpopelyshev** [comment]
Tinting will be VERY slow for canvas, you better to put all colors you need in atlas. IF you need all the colors, well, you need dynamic atlas and that's different talk.

**Comment by TazOen** [comment]
With normal Container I'm getting 60FPS with 2000 tinted sprites. With ParticleContainer I'm getting 60FPS with 4000 sprites. So as long as implementing sprite tinting for ParticleContainer doesn't cut its performance in half then it should still be faster than normal Container, theoretically IMO, at least for small textures... 

Atlas solution might limit the amount of colors too much (whereas with tinting players can choose any arbitrary RGB-based color). I'll try that with a fixed color selection thou, to see if I can get more than 2000 sprites and still have enough color choices - If not then I'll stick with normal Container for now.

And don't get me wrong: 2k tinted sprites is still pretty awesome for Canvas, and 16K+ tinted sprites is **really** great for WebGL - love the new tint support for it:)

**Comment by ivanpopelyshev** [comment]
Its interesting.
That means somehow that stupid optimization of storing only one current tint color and using it multiple times works. Its always a problem to estimate canvas2d performance :)

**Comment by TazOen** [comment]
I think can be closed as an issue - now that I've tried falling back to the normal Container for Canvas and seen that I can already get 2K+ tiny tinted sprites - that's enough to more forward:)
