### ISSUE TITLE
Stuck at 33fps on iOS 11

### ISSUE THREAD

**Issue by saibotlive** [pixijs/pixi.js#4371]
Pixi since iOS 11 now never goes above 33 fps for both Canvas and WebGL. I have tested with pixi v3 bunnymark test (http://www.goodboydigital.com/pixijs/bunnymark_v3/) and pixi v5 alpha with just 2 bunnies (https://pixijs.github.io/bunny-mark/)

**Comment by finscn** [comment]
what's your device & how many bunnies  ?
In my device , it's 60 fps (10000 bunnies)

**Comment by saibotlive** [comment]
I’m using iPhone 7 and recently updated to iOS 11. Before then it was all 60fps. This issue also happens with another iPhone 6 with iOS 11 I tested with. All the android devices were all at 60fps.

**Comment by finscn** [comment]
That's so strange. My devices are iPhone 6  & iPhone 7  iOS 11.  Both 60 fps when bunnies is 10000.

**Comment by JetLua** [comment]
Is the low power mode turned on?

**Comment by saibotlive** [comment]
@JetLua, thanks a lot! That was the problem. My phone is always set to low power mode. It went straight to 60fps after I changed it.

**Comment by bigtimebuddy** [comment]
Looks like this is solved, good to know about low power mode! Closing.
