### ISSUE TITLE
BUG: sprite masking - wrong clipping of spritesheet images

### ISSUE THREAD

**Issue by bitbay** [pixijs/pixi.js#4372]
When using a sprite as a mask over another sprite (both from images, from the same spritesheet) the clipping (in the shader(?)) isn't calculated correctly.

Have a look at these two plunks, the first seems to work-as-expected (it seems that You have to manually click on the refresh in the preview):
https://embed.plnkr.co/rAvGK9eQZSNoUSvcm7oA/
and here is the buggy one:
https://embed.plnkr.co/HSXSEncO0ZGEiPTjU6Jp/

The result should be the same, but it seems that the clipping part of the fragment shader doesn't do it's job at all (inverted clipping?).
Anyway, looking over the source it seems that the SpriteMaskFilter (or even worse, the FilterManager itself) is using the textures baseTexture to do the math and can't work with sheet frames.

----
edited: "buggyplnkr" updated

**Comment by ivanpopelyshev** [comment]
It was a long way to make this PR: https://github.com/pixijs/pixi.js/pull/4357

build is here: pixijs.download/dev-mask-texture/pixi.js

I hope it will be merged soon.

**Comment by bigtimebuddy** [comment]
I cannot get the second (buggy) plunk to load.  Could you fix that @bitbay?

**Comment by bitbay** [comment]
@bigtimebuddy done it, hope it works this time!

**Comment by bigtimebuddy** [comment]
Until @ivanpopelyshev's PR gets merged, PixiJS does not support Sprite masks from trimmed Textures. Please see our gotchas section: https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#things-that-dont-support-spritesheet-textures

I'm closing this since it's a known issue. We are working to add this feature either to v4 or coming v5.

**Comment by ivanpopelyshev** [comment]
@bitbay I changed pixi link in your plnkr to "https://pixijs.download/dev-mask-texture/pixi.js" and it works :)

**Comment by bitbay** [comment]
nice! any scheduled date or version for the merge?

**Comment by ivanpopelyshev** [comment]
no, we are waiting @GoodBoyDigital to confirm that this patch does not interfere with our move to v5.
