### ISSUE TITLE
InteractionData::identifier, String or Number ?

### ISSUE THREAD

**Issue by NicolasVereenoghe** [pixijs/pixi.js#4373]
Hello, I noticed this property is defined as a "number" (in comments).
https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionData.js#L40-L45

For touch events the value seems to be an integer. But for mouse events, it's a String : "MOUSE".
https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L14
https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L80-L81

Is it intended ?

**Comment by bigtimebuddy** [comment]
That doesn't seem right, thanks for pointing this out @NicolasVereenoghe. Seems like it should be `string|number` because of how it's [used](https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1646). Either the documentation or the API needs to be updated. @andrewstart or @themoonrat could either of you take a look at this?

**Comment by andrewstart** [comment]
It is intended, just to make sure that we have a unique value that won't be used by actual touches/pointers. A value of `-1` would probably work, but the simplest solution would be to update the documentation.

**Comment by englercj** [comment]
When the mouse is the pointer, `pointerId` should be `1`:

https://www.w3.org/Submission/pointer-events/#attributes

> If the device producing the event is a mouse, then the pointerId must be 1. Device types other than mouse must not have a pointerId of 1.

Makes sense to me to follow the pointer event specification when we are normalizing?

**Comment by andrewstart** [comment]
Huh, I didn't know that existed in the specification. Does it still hold true for touch events though (which I know vary by browser)?

**Comment by englercj** [comment]
That is only true for pointer events, when normalizing to pointer from touch we would have to manually ensure it is true.

**Comment by themoonrat** [comment]
This has been fixed.
`this.mouse.identifier = MOUSE_POINTER_ID;`
and
`const MOUSE_POINTER_ID = 1;`
