### ISSUE TITLE
pointertap happens even if mouse down happens outside a displayobject

### ISSUE THREAD

**Issue by Gaikov** [pixijs/pixi.js#4374]
1. try mouse button down (touch down) outside a some displayobject
2. move pointer over this displayobject
3. then release mouse (or touch)

as a result: pointertap happens

**Comment by andrewstart** [comment]
This is with something near the latest version (4.5.6), right?

**Comment by Gaikov** [comment]
yes, I use latest version

**Comment by NemoStein** [comment]
Any news on this?
Still firing in the latest stable (v4.7.0)

**Comment by themoonrat** [comment]
A fix was added for 4.8.0 :)
