### ISSUE TITLE
VideoBaseTexture does not set crossOrigin attribute automatically

### ISSUE THREAD

**Issue by akihikodaki** [pixijs/pixi.js#4376]
`BaseTexture` automatically sets `crossOrigin` attribute of images, but `VideoBaseTexture` does not for videos. That behavior is inconsistent.

**Comment by themoonrat** [comment]
Version 4.6.0 fixed this with https://github.com/pixijs/pixi.js/pull/4345

**Comment by akihikodaki** [comment]
:tada: I'll close this issue.
