### ISSUE TITLE
Sprite is rendered as a black rectangle on mobile browsers

### ISSUE THREAD

**Issue by thekolapo** [pixijs/pixi.js#4377]
Hi,
I have an issue where sprite is rendered well on a desktop browser but appears as a black rectangle on mobile browsers. I have tried and checked on possible causes but couldn't come up with a solution. Please do you have an idea of what the issue could be and if possible a solution too.

<img width="1680" alt="screen shot 2017-10-19 at 1 54 09 pm" src="https://user-images.githubusercontent.com/4974861/31771894-a588a31a-b4d5-11e7-9c13-6f9583d1f61d.png">

![img_2161](https://user-images.githubusercontent.com/4974861/31771968-e286834a-b4d5-11e7-9a31-0e53ca11349b.PNG)

**Comment by ivanpopelyshev** [comment]
What's the size of the texture?

**Comment by thekolapo** [comment]
The size of the texture is 497 KB

**Comment by ivanpopelyshev** [comment]
In pixels :)

**Comment by thekolapo** [comment]
I left it as autodetectrenderer and the size of the image is 11820 * 501

**Comment by ivanpopelyshev** [comment]
I dont know limitations of your device, but most mobile devices have limt of 4096 or 8192 on texture size. 11820 doesnt fit.

**Comment by ivanpopelyshev** [comment]
Also, png size affects only networking. In videomemory that thing costs 11820*501*4 = 23MB, several of them will can clogg your app.

**Comment by thekolapo** [comment]
Alright thanks a lot, I'll definitely keep that in mind. I also just tried a texture with a much smaller size and it happened to display well on mobile, so I guess the texture size was the problem after all :)
