### ISSUE TITLE
About BlurFilter's algorithm

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4378]
I found  In the BlurFilter ,  when `quality` > 1,  the filter  need  multi-pass  (as many as `quality`)

but the algorithm of `2D Gaussian blur`  in https://software.intel.com/en-us/blogs/2014/07/15/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms ,  just use one-pass . 
Maybe with better performance.

So Is there space for improvement in BlurFilter ?

**Comment by themoonrat** [comment]
Does the newer 'KawaseBlurFilter' satisfy this request?

**Comment by finscn** [comment]
Yes. this one cloud be closed
