### ISSUE TITLE
Why only blur filters with `resolution` in constructor ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4379]
the `resolution` is the common property . Every filter supports it .
But I found only blur filters ( BlurFilter, BlurXFilter, BlurYFilter) with `resolution` in constructor.
Why ?

I hope all filters are in the same style : 
Every filter is with `resolution` in constructor.
or
Every filter is NOT with `resolution` in constructor.

**Comment by finscn** [comment]
One user is puzzled by this point . 
see :  https://github.com/pixijs/pixi-filters/issues/93

**Comment by ivanpopelyshev** [comment]
That thing exists everywhere => dont add it in constructor. Something like chained "setResolution" can be fine though

```
var filter = new Filter().setResolution(2);
```

**Comment by finscn** [comment]
@ivanpopelyshev  , I agree with you . 
Shall we remove the `resolution` from blur filters ?

**Comment by ivanpopelyshev** [comment]
Make PR against `next` : setResolution chain and remove resolution from constructor.
