### ISSUE TITLE
PIXI.Text/PIXI.TextStyle textBaseline rendering bug

### ISSUE THREAD

**Issue by yhwh** [pixijs/pixi.js#4383]
## Example code
```
const style = new PIXI.TextStyle({
    fontStyle: 'italic',
    textBaseline: 'middle'
});
const text = new PIXI.Text('Hello World', style);
```
## Output
<img width="222" alt="screen shot 2017-10-24 at 20 53 49" src="https://user-images.githubusercontent.com/274100/31964898-7788df58-b8fd-11e7-8ba7-cbbb6bb887fb.png">

Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit) MacOS Sierra

Note: I guess it's not system dependant.

## Live Example:
https://pixijs.github.io/pixi-text-style/#%7B%22style%22%3A%7B%22fontStyle%22%3A%22italic%22%2C%22textBaseline%22%3A%22middle%22%7D%7D

**Comment by themoonrat** [comment]
You can add padding to the style to help out on this

**Comment by djmisterjon** [comment]
if my memory is good this problem exists since the beginning.
I corrected it in my personal project.
i just add new code for take the line style 
`lineStyle:'middle', //'top'||'middle'||'bottom' `


```javascript
MVPixi_Text.prototype.positioningChild = function(pixiText) {
    var data = pixiText._resultLine;
    var pixiChild = pixiText.children;
    var lS = pixiText._style.primary.lineStyle;
    var lA = pixiText._style.primary.align;
    var lH = pixiText._style.primary.lineHeight || 0;
    lS = lS==='middle'&& 0.5 || lS==='bottom'&& 1 || 0; // lineStyle
    lA = lA==='center'&& 0.5 || lA==='right'&& 1 || 0;  // lineAlign
    var limit = pixiText._style.primary.wordWrapWidth || Math.max.apply(Math, pixiText._dataLW);
    for (var R=0, id=0, lineMaxH=0, Y=0, alignX=0, LEN=data.length; R<LEN; R++) {
        if(lA){ alignX = (limit-pixiText._dataLW[R])*lA; };
        for (var r=0, len=data[R].length; r<len; r++, id++) {
            pixiChild[id].anchor.y = lS;
            pixiChild[id].x = data[R][r]._x+alignX;
            pixiChild[id].y = Y;
        };
        Y+=pixiText._dataLH[R]+lH;
    };
return pixiText
};
```

**Comment by wildaces215** [comment]
Its not only just the middle for textBaseline but also hanging and top and hanging
