### ISSUE TITLE
PIXI LOGO ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4384]
Hi, I had to improvise mine, but I wanted to know if pixi had a logo intro?
example here
[![Alt text](https://i.ytimg.com/vi/7-DUC_uMIbs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLApjVpD3btjhlaG2GrarIidVP0gew)](https://youtu.be/7-DUC_uMIbs)
 i made my own free PIXI logo on AE (4 day work)  see at (0:16 sec), but need to know if PIXI have a Reel animated motion LOGO for made prez on game  or other  thecnologie ???
also  
https://youtu.be/opIv40R4mw0
old test code in AE with pixi logo in rmmv thecnologie and loop test with pixi text.

**Comment by bigtimebuddy** [comment]
We don't have a preroll animation, but here's the logo.

![PixiJS Logo](http://pixijs.download/pixijs-logo.svg)
http://pixijs.download/pixijs-logo.svg

![PixiJS Logo Text Only](http://pixijs.download/pixijs-text.svg)
http://pixijs.download/pixijs-text.svg
