### ISSUE TITLE
Proposal for V5: move interactionManager initialization into application

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4388]
After introduction of ticker and application a pair of things are still done the old way:
1. interaction
2. animation updates

Both of them should be related to stage through application, not through `renderer._lastRenderedObject`.

Application has to be scaffold that user can copy and that way make their own app with multiple stages, custom animations and other customized stuff.

**Comment by themoonrat** [comment]
Slightly related; I don't like how there is one shared ticker that is used for everything internally. If I want to pause the game, you could say just pause that shared ticker... but not only are sprites paused, but interaction movement is paused, base textures being uploaded via the prepare plugin get paused. At a simple level, you could have 'system ticker' and 'visual ticker' perhaps? Or allow the application class to let the user define which tickers are used for what?

**Comment by ivanpopelyshev** [comment]
We need a way to pause a group of handlers without stopping RAF or creating another one.

**Comment by andrewstart** [comment]
So perhaps something similar to [Starling's Juggler class](http://doc.starling-framework.org/current/starling/animation/Juggler.html)?

**Comment by bigtimebuddy** [comment]
We could also pause individual handlers in ticker to skip them

**Comment by ivanpopelyshev** [comment]
Pausing individual handlers is a good idea.

**Comment by andrewstart** [comment]
Juggler is similar to our Ticker, but the main thing I wanted to mention about them is that Jugglers are designed to tick other Jugglers. With that, you could set up a small ticker tree that runs off the main ticker, but be able to, from one place, disable all game world activity while leaving the InteractionManager and UI update ticks running, or even pause/slow down the update ticks for everything in your game world that is not the player.

**Comment by ivanpopelyshev** [comment]
Yeah, something like that.

**Comment by ivanpopelyshev** [comment]
We have to specify in docs that it can't be used for 10k animations because add/remove has linear complexity, and its better to make special animationManager for those cases.

**Comment by andrewstart** [comment]
For v5 are we going to require some level of ES6 support, at least the Set class?

**Comment by bigtimebuddy** [comment]
Native support for Set is unlikely since IE 9 and 10 don't support it. But there are some decent polyfills available for Set, so that's an option.
