### ISSUE TITLE
Sorry for this issue , But I can't tall about this on slack at this weekend.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4389]
( I can't connect to slack , because the network ... )

Because the v5 is coming , I reviewed some issues , I found there are someone for v5. 

So Could you add the tag `Version: v5.x` to let users and contributors know that "this issue will be solved in v5" ? 
Or give me a right for `add tag to issues` , I'm glad to do it.

**Comment by themoonrat** [comment]
I'm going through tagging older issues now :)
