### ISSUE TITLE
Is there any animation-lib supports pixi.js?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4391]
I know some good animation-lib , e.g. http://mojs.io/ ,  http://animejs.com . But they only support css3 or svg.

Is there any animation-lib supports pixi.js?

**Comment by OSUblake** [comment]
GreenSock does.
https://greensock.com/docs/Plugins/PixiPlugin

Demo.
https://codepen.io/osublake/pen/qmXPMm

**Comment by Icemic** [comment]
animejs supports js object (http://animejs.com/documentation/#JSobject).

**Comment by themoonrat** [comment]
Closing as a few good suggestions have been made :)
