### ISSUE TITLE
PIXI.settings.FILTER_RESOLUTION doesn't do anything

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi.js#4392]
Hi the docs say that this will change the Default filter resolution but it doesn't seem to do anything.
Has this been implemented?

It it supposed to change the resolution of all filters or have I misunderstood its use?

Thanks very much

**Comment by themoonrat** [comment]
This was fixed with https://github.com/pixijs/pixi.js/pull/4743 :)
