### ISSUE TITLE
The common property in Filter should be `"set/get property" + "_property"`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4393]
The common property in Filter should be `"set/get property" + "_property"`.
Like the  `blendMode & _blendMode`.

Because if a filter includes another filter,  when users change  the outer-filter , the inner-filter should also be change ,  `"set/get property" + "_property"` could implement this feature .
If only `property` or `set/get property` , can't do that .

We need `"set/get property" + "_property"`.

The common properties I found : 
```
blendMode
resolution
padding
```

btw, this issue  https://github.com/pixijs/pixi.js/issues/4379 ,  needs this feature too.

**Comment by ivanpopelyshev** [comment]
The easiest way is to move them in applyFilter. Those operations cost nothing compared to actual rendering.

**Comment by finscn** [comment]
blendMode & resolution are moved to applyFilter it's ok.  but `padding` not.  because  `cacheAsBitmap` use it.
