### ISSUE TITLE
autoDetectRenderer does not detect own canvas

### ISSUE THREAD

**Issue by pptic84** [pixijs/pixi.js#4398]
Hi!

Sorry for my english.

I has the following code:
ownCanvas= document.getElementById('ownCanvas');
	
	renderer = autoDetectRenderer(size[0], size[1], {view: ownCanvas, preserveDrawingBuffer:true });

In the last version, create a new canvas and not detect my own Canvas.

Thanks!!!

**Comment by themoonrat** [comment]
I've just had a test with this, and everything works ok pixi side.

What happens is in your example code, is that if the variable 'ownCanvas' is null / undefined, PIXI will create it's own canvas to use instead. I believe that is what is happening here; put a breakpoint after ```ownCanvas= document.getElementById('ownCanvas');``` and I think you'll see that ownCanvas is null

My test code was this
```
const canvas = document.createElement("canvas");
canvas.id = "NotPixiCanvas";

const app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb, view: canvas});
document.body.appendChild(app.view);
```
