### ISSUE TITLE
About performance of `indexBuffer` & `drawElements`.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4399]
recently , I try to create some examples about shader (just for studying), so I don't use PIXI.
I use a simple webgl wrapper `igloojs` at https://github.com/skeeto/igloojs 

And I found a strange thing :  
When I just render  thousands of sprite (use same texture , so they're batch) ---- no motion , no animation, no transform, no shader ,no filter ,no any effect, just "stand & still" , the `igloojs` is faster than pixi very much , very very very much , at least 3x.
Even I try to use  PIXI.glCore directly to render texture (similar to  http://dev.goodboydigital.com/client/goodboy/million/ , but no physics, no `particles shader`), the `igloojs` is still faster very much.

> So I read the code , I found the biggest difference is that `igloojs` use `drawArrays(TRIANGLES...)` , and no `indexBuffer` , I have to set ` the 6 vert ` manually.
> 
> And I found use  `drawArrays(gl.TRIANGLES...)` is faster than `gl.drawElements(gl.TRIANGLES...)`.
> 

Is  `indexBuffer` & `drawElements` the hotspot of performance ?

**Comment by finscn** [comment]
I refactor http://dev.goodboydigital.com/client/goodboy/million/  , create a new version  with `drawArrays`  http://fatidol.com/million-draw-arrays  . 
You could find it's as fast as use glPoint.

**Comment by GoodBoyDigital** [comment]
wow! thats really cool @finscn 👍 
Do you think its worth refactoring sprite renderer to use drawArrays?

**Comment by ivanpopelyshev** [comment]
```
var indices = new glCore.GLBuffer.createIndexBuffer(gl, indices);
```

Try this one:

```
var indices = glCore.GLBuffer.createIndexBuffer(gl, indices, gl.STATIC_DRAW);
``

**Comment by ivanpopelyshev** [comment]
Also I see that number of bunnies on those two examples is different. I dont know why, please find it.

**Comment by finscn** [comment]
I found when use `drawElements` , there is a limitation of sprites count in batch .  detail : https://github.com/pixijs/pixi.js/issues/91

But when use drawArrays , no this limitation.

So,  @GoodBoyDigital  , maybe we should consider  use drawArrays.

**Comment by ivanpopelyshev** [comment]
I think instancing will give more than that. Try instancing approach too.

**Comment by ivanpopelyshev** [comment]
Lets not add drawArrays before we research everything and take into account multi-texturing and instancing.

**Comment by ivanpopelyshev** [comment]
upd: we've concluded that limit is not on drawElements but because of fboSize.

**Comment by finscn** [comment]
@ivanpopelyshev  , the limit ( 16384 )  is not because of fboSize ,  the fboSize (int the code I give you) is  200 , the limit is 400000.  the 16384 is because of  #91  & indexBuffer(maybe)

**Comment by neutrino84** [comment]
that seems like a pretty big performance disparity, shouldn't drawArray and drawElements be very similar in speed, with elements being much faster w vertex reuse (uses less bandwidth)

drawArray = sizeof(vertex) * # of triangle * 3
drawElements = sizeof(vertex) * nb of vertex + sizeof(indice) * nb of triangles * 3

without vertex reuse drawArray doesn't have indexing overhead, so is faster

**Comment by maximilianh** [comment]
I'm getting 32k bunnies on finsc's links and both show the same FPS (2016 macbook, chrome)
