### ISSUE TITLE
In IE11, all the animations disappear

### ISSUE THREAD

**Issue by CrackRen** [pixijs/pixi.js#4401]
In IE11, all the animations disappear: 
the page height is 2000, the canvas is at the top of the page and the height is 1000. 
When the page moves to the bottom for 10 seconds and then moves back to the canvas, 
all the animations in Pixi 4.5.1 disappear. 
Pixi4.6.0 PIXI.sprite animation exists, PIXI.mesh.Rope still disappeared.

**Comment by themoonrat** [comment]
Hi @CrackRen , sorry it's taken so long to get back to you. Gonna close this issue as it's so old and I'd have hoped you'd have solved it by now! If not, please do open a new issue with a jsfiddle or something that we can use to try and help you with
