### ISSUE TITLE
[SUGGEST] Add `tintMultiplier` & `tintOffset` in v5, and remove `tint`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4403]
the `tint` in v4 (for Sprite) is useful , but has limitation.

`tint` only could make Red Green Blue channels become small.

If supply `tintMultiplier` & `tintOffset` , it will has  less limitation.

```newColor = oldColor * tintMultiplier + tintOffset  ```

the  `tintMultiplier` is a float  from 0.0 to 255.0, will apply to RGB  (rgb as a whole).
the `tintOffset` is from 0x000000 to 0xFFFFFF , will apply to R/G/B (as 3 channels).

In some render engine , the `tintMultiplier` is  three-float-values , and apply to R/G/B (as 3 channels), but I think that's too complex .  use one float is good enough.

**Comment by ivanpopelyshev** [comment]
That's not how it works. Either flash multiplier+offset either spine "light-dark" system. No one has "tintMultiplier" as a single number.

**Comment by finscn** [comment]
Yes, could use another name . Whatever , current `tint` is too weak , and  `newColor = oldColor * a + b` is a good choice.

**Comment by ivanpopelyshev** [comment]
"a" can be negative ;)

**Comment by neutrino84** [comment]
i think the simple tint is a good baseline feature, and the devs of games and game engines can subclass to create a more powerful tint

**Comment by ivanpopelyshev** [comment]
https://github.com/gameofbombs/pixi-heaven works just fine.
