### ISSUE TITLE
Patch Samsung Galaxy S8 on older Pixi?

### ISSUE THREAD

**Issue by nikkop** [pixijs/pixi.js#4405]
Some issues related to the Galaxy S8 have been fixed in latest couple of versions, but is there any way for us sitting on v3 to patch it somehow to get rid of these issues? For example the following issues [#4330](https://github.com/pixijs/pixi.js/issues/4330) and [#4022]( https://github.com/pixijs/pixi.js/issues/4022) are now fixed in latest versions.

For us in our project the issue is regarding filters (the BlurFilter makes the DisplayObject with the filter applied completely disappear) and with the Tiling Sprite (the texture is missing and instead a rainbow-like gradient is shown). Upgrading from 3.0.8 to v4 is a big step for us and currently happily avoided.

Is there a temporary fix we can use until we manage to upgrade to v4?

**Comment by ivanpopelyshev** [comment]
It wasn't fixed. People just use different set of options

```js
var renderer = new PIXI.WebGLRenderer( {
   antialias: true, //try this one first
   preserveDrawingBuffer: true //add this thing if first doesnt work
});
```

There's also "legacy" option, which makes v4 sprite renderer work like v3, it cant be applied to your case.

Of course I have one more stupid idea - make sure that v3 creates framebuffer of integer size, add "Math.ceil" there.

**Comment by nikkop** [comment]
Thanks for your feedback. I have tried with the antialias and preserveDrawingBuffer earlier but didn't work out unfortunately.

So nothing has been fixed in Pixi? It's weird because the latest version works well and the issues we have in Galaxy S8 are gone. I have tested this myself with various JS-fiddles with the issues we have (Tiling Sprites and BlurFilter) and both of them work out of the box without any extra parameters supplied to the constructor.

How come it works now but not a couple of versions ago with the same parameters supplied?

**Comment by ivanpopelyshev** [comment]
TilingSprite shader is just different from v3, also it enables REPEAT on texture if it wasnt set and disables mipmaps. 

As for filters, they use temporary buffers of pow2 size, the whole FilterManager is different. I also remember that Blur uses special flag to not clear one of temporary framebuffers, i dont know how did it work in v3.

**Comment by nikkop** [comment]
Ok, about TilingSprite it makes sense if it's not working the same. Regarding your thoughts about the filters, how come it's working out of the box in 4.2.1 but not in any released version before? I read it has something to do with the legacy options. Is there any way we can apply something similar or are we better looking into upgrading to v4, even if it's a big and time consuming step for us? 

Tomorrow I will get my hands on a S8 and I will do some further testing and hopefully have more information. Thanks for the help so far.

**Comment by themoonrat** [comment]
The 'legacy' setting added within v4 was actually to make certain rendering occur _more_ like how v3 worked! So that part is not something that could be backported, I don't think, because you're already on v3!

**Comment by ivanpopelyshev** [comment]
OK, one more idea: get webgl2.0 context and use other functions. We have to determine whats wrong with webgl1.0 on samsung and switch it.

**Comment by nikkop** [comment]
I think we will consider upgrading to v4 soon and the problem should be gone. Thanks for your inputs.

**Comment by cendlerko** [comment]
Hi All,any news on it , we also use pixi v3, i have try @ivanpopelyshev recommendations , with renderer options i have also forced to use webgl2 but with no luck .

So question is if if somebody know where is the problem ?
