### ISSUE TITLE
loading sprites issue

### ISSUE THREAD

**Issue by ramarro123** [pixijs/pixi.js#4406]
Hi,

i am using pixi 4.6 with osx, i can reproduce this "issue" with both firefox, chrome and safari

please note the "issue" here, i think that i need help investigating whats happening.

in my code i load everything with preloadjs, i can confirm that everything seems to be loaded (preloadjs fire the correct event) and then pick up the data from a local cache.

when i create pixi objects (of spritesheet, of bitmapdata, spine) sometimes (it's not easy to reproduce it) a random object get black with green box as the bitmap data it's not ready to be used.

i have try to do a super ugly setTimeout right after preloadjs fire the onComplete event, to give pixi more time to warm up (and to dirty check if it's a problem of not yet laoded data) but with any delay the problem happen again.

the game it's quite complex, and it doesn't happen with a simple test case so it's very hard to isolate this issue. also it's not repeatable and i am having quite a lot of difficulties :(

can someone point me in the right direction or give some suggestion on what i should investigate more?

tnx

**Comment by finscn** [comment]
Could you show me your code ?

**Comment by themoonrat** [comment]
@ramarro123 going to close since it's been a long time! If you've still got any issues don't hesitate to come back and raise a new issue or ask a question at http://www.html5gamedevs.com/forum/15-pixijs/
