### ISSUE TITLE
PIXI.TextStyle.lineJoin Documentation improvement

### ISSUE THREAD

**Issue by brenwell** [pixijs/pixi.js#4409]
Hey guys,

I wanted to suggest a very simple upgrade to the TextStyle docs, adding the alternate values for lineJoin. Something like below:

Name | Type | Default | Description
-- | -- | -- | --
from ...
lineJoin | string | 'miter' | *optional* The lineJoin property sets the type of corner created, it can resolve spiked text issues. Default is 'miter' (creates a sharp corner).
to ...
lineJoin | string | 'miter' | *optional* The lineJoin property sets the type of corner created, it can resolve spiked text issues. **Possible values "miter" (creates a sharp corner), "round" (creates a round corner) or "bevel" (creates a squared corner).**

Just an idea, thanks for all the hard work guys

**Comment by themoonrat** [comment]
Looks good to me, I'd approve a PR with that doc change, clears up any confusion over what the setting does.

**Comment by bigtimebuddy** [comment]
Merged
