### ISSUE TITLE
why pixi skew was not same as css3 transform skew

### ISSUE THREAD

**Issue by jasonChen1982** [pixijs/pixi.js#4417]
when i use skew to transform a `display-object`, i get a different results. it`s not same as css3 transform skew. so I want to know what this is about ~~~

**Comment by ivanpopelyshev** [comment]
Its using rads, not grads.

**Comment by ivanpopelyshev** [comment]
Btw, if you want to use grads, there are two ways
1. Multiply everything by `PIXI.DEG_TO_RAD` which is `180 / Math.PI`
2.  Hack "updateSkew" on transform static https://github.com/pixijs/pixi.js/blob/dev/src/core/display/TransformStatic.js

```js
PIXI.TransformStatic.prototype.updateSkew = function()
{
    this._cx = Math.cos((this._rotation + this.skew._y)*PIXI.DEG_TO_RAD);
    this._sx = Math.sin((this._rotation + this.skew._y)*PIXI.DEG_TO_RAD);
    this._cy = -Math.sin((this._rotation - this.skew._x)*PIXI.DEG_TO_RAD); // cos, added PI/2
    this._sy = Math.cos((this._rotation - this.skew._x)*PIXI.DEG_TO_RAD); // sin, added PI/2
    this._localID ++;
}
```

voila, pixi now works with degrees and not radians!

**Comment by finscn** [comment]
@ivanpopelyshev , Why use grads in v5 ?   rad & deg not good enough ? 
What's the advantage of grads ?

**Comment by ivanpopelyshev** [comment]
Grads are integers, they are easier to store in source code (without * PI) and in json files.

Other 2d engines use grads on top-level, only use radians internally.

**Comment by jasonChen1982** [comment]
@ivanpopelyshev thanks for your answer, maybe i don't describe clearly about my question. i want to say is skewX was just affect `x-component` in `css3 transform skewX`, but `pixi skewX` would affect `both-component`. 

i am very like `pixi`, and very curious about the reason~~~

**Comment by ivanpopelyshev** [comment]
CSS skew also scales? I didnt know. Ok, thank you. You can make your own Transform with different updateSkew.

**Comment by jasonChen1982** [comment]
thanks for your time~~~ 

and i hope `pixi` could bring into correspondence with `css3-transform`

**Comment by ivanpopelyshev** [comment]
Ok guys, it looks like Flash skew is the same as CSS: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Matrix.html 

That means pixi skew is really wrong. I propose we add "shear" instead and use it in decomposition, 

At the same time we add skew with one "if" , whether to apply that tangent matrix.

**Comment by jasonChen1982** [comment]
great~~~

**Comment by OSUblake** [comment]
> Ok guys, it looks like Flash skew is the same as CSS: 

That doesn't mean it's desirable. Skewing like that causes the object to become **EXTREMELY** stretched. I would rather keep skewing the way it is now by default. Other libraries like GreenSock and EaselJS do skewing the same way. 

See the comparison. The image on the top is like CSS, and the image on the bottom is like PixiJS.
https://codepen.io/osublake/pen/dc1c5263e2f6c0026ea1ca31cc262832?editors=0010

**Comment by OSUblake** [comment]
> and i hope pixi could bring into correspondence with css3-transform

The biggest problem with PixiJS is that it doesn't have a transform origin like CSS. The default transform origin for an element is its center. To do that with pixi, you have to use pivot or anchor, which moves the object. That is not intuitive, and scares away a lot of first users.
https://github.com/pixijs/pixi.js/issues/4138

**Comment by dghez** [comment]
> That doesn't mean it's desirable. Skewing like that causes the object to become EXTREMELY stretched. I would rather keep skewing the way it is now by default. Other libraries like GreenSock and EaselJS do skewing the same way.

Actually Greensock has a parameter like "skewType: normal" or something similar to make the skew like CSS. Is there a way to do the same in pixi? It will me save a lot of time :)

**Comment by OSUblake** [comment]
> Actually Greensock has a parameter like "skewType: normal" or something similar to make the skew like CSS. Is there a way to do the same in pixi? It will me save a lot of time :)

Hehe. That's what I used in that demo above to show the difference. 

But no, there currently isn't an option for that. After reading my comment, it might not be clear, but that's actually what I was trying to suggest. Have an option for the 2 different types, with the way skewing is currently done set as the default skew type.

**Comment by dghez** [comment]
@OSUblake:  My bad, I didn't open the codepen demo ahah
What about using the css matrix @jasonChen1982 showed and use that as transform matrix?

**Comment by OSUblake** [comment]
> EDIT: does anyone know why if I skew it using greensock & skeyType: simple it doesn't work? If someone has the answer fine, otherwise I'll ask on gsap forum :)

That will only work for DOM elements. When you animate a pixi object with GSAP, it doesn't handle the transforms. It's only changes the value. Pixi handles the transform.

To handle skew like CSS, you would need to change how transforms are calculated. I think what @jasonChen1982 shows is for the matrix class. For display objects, I think you would have to modify the TransformStatic and Transform classes.
