### ISSUE TITLE
ColorMatixFilter documentation issue

### ISSUE THREAD

**Issue by LunarRed** [pixijs/pixi.js#4419]
On the example at the top of http://pixijs.download/dev/docs/PIXI.filters.ColorMatrixFilter.html it gives this as an example: 
    ` let colorMatrix = new PIXI.ColorMatrixFilter();`
should be:
    ` let colorMatrix = new PIXI.filters.ColorMatrixFilter();`

**Comment by bigtimebuddy** [comment]
Good find! Feel free to make a pull-request for this change.
