### ISSUE TITLE
Unable to destroy WebGLRenderer when context lost.

### ISSUE THREAD

**Issue by akhnaz** [pixijs/pixi.js#4420]
Hello,
May i know how can i destroy a WebGLRenderer that has lost context?..because, it'll break in FilterManager.destroy()

**Comment by ivanpopelyshev** [comment]
I thought we fixed it, but https://github.com/pixijs/pixi.js/issues/4418 , same issue.

**Comment by ivanpopelyshev** [comment]
Please use https://pixijs.download/fix-destroy-filters/pixi.js if you want to try the fix.

**Comment by akhnaz** [comment]
Sure, but i will be able to try with the fix only on monday. Will let you know the result. Thank you so much!

**Comment by akhnaz** [comment]
Thank you, the new release 4.6.1 fixed the problem.
