### ISSUE TITLE
Mouse events for non-filled graphics don't work

### ISSUE THREAD

**Issue by rusomirt** [pixijs/pixi.js#4436]
How can I get mouse events for non-filled graphics (drawn with `graphics.drawRect()` or `graphics.drawEllipse()` etc. without `beginFill()`)?

I found #233 and #264 but they are pretty old and only filled shapes are considered there. 
I need to catch events only when the mouse pointer is over graphics line, not when it's within graphics shape (i.e. the line should fire an event).

My Pixi version is 4.5.5.
Is there any way to do it?

**Comment by andrewstart** [comment]
Add https://github.com/CloudKidStudio/springroll-utils/blob/master/src/math/HoledShape.js to your code, and use two regular shapes (`PIXI.Rectangle`, `PIXI.Polygon`, etc) as your outer and inner shapes with enough difference between them to cover the line, then set `myGraphic.hitArea = myConstructedHoledShape;`

**Comment by rusomirt** [comment]
Andrew, thanks for you reply.
Could you please explain more detailly how should I use this code? I can't get it working.

To get `myConstructedHoledShape` I need to call a function with `outer` and `hole` parameters. But what function?

**Comment by andrewstart** [comment]
`HoledShape` is an (ES5) class:
```javascript
//0, 0 for this shape should be the same 0,0 for myGraphic - if a rectangle was drawn on the graphic from 
//-25, -25 with a width & height of 50, then inner should be something like -24, -24, 48, 48 depending 
//on how much clickable area you want
var inner = new PIXI.Rectangle(5, 5, 5, 5);
//example is 2 px larger than inner in each direction - depends on how much clickable area you want
var outer = new PIXI.Rectangle(3, 3, 9, 9);
//make a new instance of HoledShape - this can be shared by all Graphics that have been given the same art, if any
var final = new HoledShape(outer, inner);
myGraphic.hitArea = final;
```

**Comment by andrewstart** [comment]
`HoledShape` is an (ES5) class:
```javascript
//0, 0 for this shape should be the same 0,0 for myGraphic - if a rectangle was drawn on the graphic from 
//-25, -25 with a width & height of 50, then inner should be something like -24, -24, 48, 48 depending 
//on how much clickable area you want
var inner = new PIXI.Rectangle(5, 5, 5, 5);
//example is 2 px larger than inner in each direction - depends on how much clickable area you want
var outer = new PIXI.Rectangle(3, 3, 9, 9);
//make a new instance of HoledShape - this can be shared by all Graphics that have been given the same art, if any
var final = new HoledShape(outer, inner);
myGraphic.hitArea = final;
```

For the code from the file, you just want the part from `var HoledShape = function(outer, hole)` to the end of the `p.contains = function(x, y)` function. the `drawOnGraphics` function is not required, and you do not want the outer wrapping code that is specific to the project that file is in.

**Comment by rusomirt** [comment]
Works like a magic! Thank you!
