### ISSUE TITLE
Matrix.scale(x,y)  affect 'tx' and 'ty' in Matrix source code

### ISSUE THREAD

**Issue by XESDog** [pixijs/pixi.js#4440]
If this is a lack of understanding on my part. why the method can affect tx and ty?
below code from the PIXI source code
````
scale(x, y)
    {
        this.a *= x;
        this.d *= y;
        this.c *= x;
        this.b *= y;
        this.tx *= x;
        this.ty *= y;

        return this;
    }
````

**Comment by ivanpopelyshev** [comment]
It prepends the scale, not appends it. Same as in https://github.com/pixijs/pixi.js/blob/dev/src/core/math/Matrix.js#L326

Also, Flash Matrix does the same. I guess all 2d engines have the same Scale in 2d 6-component Matrix.

**Comment by ivanpopelyshev** [comment]
If you want to append it, it'll be like this:

```js
this.a *= x;
this.b *= x;
this.c *= y;
this.d *= y;
```

**Comment by ivanpopelyshev** [comment]
If you think about it, all engines use this form

```
world = parent * local
```

local coords are appended to parent
parent gets prepended to local

if you set only scale in local - itl'll be appended to parent and that's the scale you want.
if you set scale in parent - it'll be prepended to local, that's default Scale matrix operation in all 2d engines.
