### ISSUE TITLE
Repeating deprecation warnings

### ISSUE THREAD

**Issue by bash-tp** [pixijs/pixi.js#4443]
If you use a deprecated method, you'll get a console warning every time you call it. This can cause performance problems and can also make it harder to spot issues because the console log gets flooded with repeating deprecation warnings.

Would it be possible to have each deprecation warning be emitted only once? Looking at deprecation.js, this should be fairly easy to do, by having warn() ignore duplicate calls with the same msg+stack. If you agree, I can make this change and send a PR.

**Comment by ivanpopelyshev** [comment]
Agree, I'm using that approach in pixi-spine. I agree that we have to move it to v5 too.

**Comment by bigtimebuddy** [comment]
Not a bad idea! Would welcome a PR for that. Ideally it would be added to the warn function instead of to each deprecation to make the change minimal.

**Comment by ivanpopelyshev** [comment]
add a key to warn function, so it stores whether particular key was used

**Comment by wildaces215** [comment]
So is it a lot deleting in the depreactionjs file?

**Comment by bigtimebuddy** [comment]
@wildaces215 Deprecation warnings were not designed to be hard breaks, that's why we aren't throwing Errors. It gives people time to update their code between major releases. However, we should fix this and remove repeated calls to make it more performant.

**Comment by YahorPadlucki** [comment]
Hi, @bigtimebuddy , I've added a PR for this issue
