### ISSUE TITLE
Error: cannot find module 'querystring' from 'url/url.js' with npm, Brunch and Windows

### ISSUE THREAD

**Issue by scambier** [pixijs/pixi.js#4450]
Essentialy, I have the same issue than this one: https://stackoverflow.com/questions/42461415/node-brunch-pixi-js-on-windows-module-querystring-not-found

System:
- Windows 10  (works fine on OSX and Ubuntu Bash for Windows 10)
- Node 8.4.0  
- npm 5.3.0
- pixi.js package 4.6.1

To reproduce:

```
npm install -g brunch
brunch new .
npm install --save-dev pixi.js
```

Then insert `require("pixi.js")` somewhere (e.g. initialize.js), and
`npm run start`

Open localhost:3333 and there's the following error:

```
Uncaught Error: Cannot find module 'querystring' from 'url/url.js'
    at require (app.js:61)
    at expanded (app.js:34)
    at app.js:147
    at url.js:104
    at url.js:737
    at initModule (app.js:42)
    at require (app.js:59)
    at expanded (app.js:34)
    at app.js:147
    at determineCrossOrigin.js:10
```

**Comment by JoelHobson** [comment]
I'm seeing the same issue (also on windows 10), but without pixi.js. I'm not sure what's causing it in my case.
What I have noticed is that although querystring isn't being included in the vendor.js file, querystring-es3 is. 
I tried directly requiring querystring in one of my files, but it still didn't include it in any of the concatenated files.

**Comment by landongn** [comment]
Also having this issue.

**Comment by landongn** [comment]
This is in `pixi.js/lib/core/utils/determineCrossOrigin.js`, it seems like, specifically on windows 10, it doesn't resolve whatever package `url` is referring to. In the latest node, that package ought to exist.  Maybe it's a collision?

**Comment by themoonrat** [comment]
Any idea @bigtimebuddy ?

**Comment by bigtimebuddy** [comment]
I just got my Windows 10 machine setup so I can try to reproduce. Has anyone here tried `require('pixi.js/dist/pixi.js')` instead of `require('pixi.js')`? I suspect maybe there are fewer issues with the bundled version.
