### ISSUE TITLE
AnimatedSprite cannot display if its texture not loaded by PIXI.loader

### ISSUE THREAD

**Issue by Icemic** [pixijs/pixi.js#4452]
Hi, I am using v4.5.6

```js
var app = new PIXI.Application();
document.body.appendChild(app.view);

// PIXI.loader.add('bunny', 'assets/animation.png').load(function(loader, resources) {

const tex = PIXI.Texture.fromImage('assets/animation.png');
const textures = [];

tex.update();
const deltaX = tex.width / 8;
const deltaY = tex.height / 1;

for (let j = 0; j < 1; j++) {
  for (let i = 0; i < 8; i++) {
    textures.push(new PIXI.Texture(tex, new PIXI.Rectangle(deltaX * i, deltaY * j, deltaX, deltaY)));
  }
}

const img = new PIXI.Sprite(tex);
app.stage.addChild(img)

setTimeout(() => {
  var bunny = new PIXI.extras.AnimatedSprite([PIXI.Texture.EMPTY]);
  bunny.textures = textures;

  bunny.play();
  bunny.x = app.renderer.width / 2;
  bunny.y = app.renderer.height / 2;
  app.stage.addChild(bunny);
}, 2000);

// });
```

The code below cannot display a animated sprite. But if you uncomment the code about PIXI.loader, it will display normally however.
At first, I think it may be a resource loading problem, so i tried to give a 2000ms delay, which didn't make sense.

I looked into AnimatedSprite class, it worked perfect except for no image displayed, I mean,  `this._texture` is changed normally. And it seems impossible that sprite renderer has a bug, because the sprite using the same texture and created before `setTimeout` displays without problem.

So, what's wrong? Please help me.

**Comment by djmisterjon** [comment]
hi, I do not know if this can help you, but I remember having a similar problem in one of my plugin.
here is a code snippet at the beginning. **look at the comment**

 ```javascript
   var Imported = Imported || {};
    Imported['pixiSSA'] = "PIXI SPRITESHEETS ANIMATIONS v.1.0";
    PIXI.loader.add(''); //FIX: i dont know why!, but need this or PIXI.extras.AnimatedSprite will not work at ALL! WTF (but work if another loader used in other plugin)
    function _pixiSSA() {};
    function _pixiSSA_aniObj() { this.initialize(); };
    
    var pixiSSA = pixiSSA || new _pixiSSA();
    pixiSSA._rmmvAlias = {};
    console.log('pixiSSA: ', pixiSSA);
```
if you do like me, is that it works. ??
add a float line 
**PIXI.loader.add('');**

**Comment by ivanpopelyshev** [comment]
According to ttps://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Texture.js#L137

Texture re-calculates uvs on basetexture load only if frame was not specified.

That means there's obvious workaround:

```
let newTexture = ...
newTexture.baseTexture.once('loaded', () => { newTexture._updateUvs(); });
```

**Comment by Icemic** [comment]
I found it!

`tex.update()` can not update width until `loaded` event is emitted. Before that, `tex.width` is `1`, which means I got a wrong width, then wrong frame.

Wait for `loaded` event solves it. thx

**Comment by djmisterjon** [comment]
**hey guys its solved thanks sorry i update from other forum after i have discut we a team dev:**


Ok thank a lot guys now it solved !!!. :D:rock-left:
I really have a hard time to understanding this chit rendering system, but now I understand a better how it works.
Here is how I did it.
This makes it possible to use any filters in the mask.


```javascript
motionTextContainers.prototype.testmask = function(){ 
    var renderTexture = new PIXI.RenderTexture.create(300); // initialise a texture render
    var sprite = new PIXI.Sprite(renderTexture); // create a sprite that uses the texture render ...
    
    // create dinamyque elements + filters
    var square = new PIXI.Graphics(); // blank square
    square.beginFill(0xffffff, 1); square.drawRect(0, 0, 200, 200); square.endFill();
    square._filters = [new PIXI.filters.BlurFilter(15)]; // test a filter
    
    // render the item it to the render texture..
    Graphics._renderer.render(square,renderTexture); // Merge element+filter and a it to the texture render
    this.mask = sprite; //hell, now masking with filter work, no more need photoshop
    return this;
};
```
