### ISSUE TITLE
[Share] Shader-Particle System in PIXI.js v4.6

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4453]
I've finished the feature about `shader-particle` in PIXI v4.6.
There is a demo : http://fatidol.com/shader-particle/

For comparison, there is a demo used `ParticleContainer` :  http://fatidol.com/shader-particle/classic.html

Notice : the `shader-particle` is *NOT* always more fast than `ParticleContainer`.  
It's depend on `what's texture & what's computing logic used in particles`.

**Comment by Patrick-Hammond** [comment]
Wow, cool feature. Will this be available as a plug-in?

**Comment by finscn** [comment]
Yes , but in my fork version  https://github.com/finscn/pixi.js 
The main problem is that :  there is no document for telling how to use it.
And whatever with or without document , it's  hard to use.
Users should know the principle of shader particles and good at WebGL Shader .

**Comment by themoonrat** [comment]
Thanks for sharing!
