### ISSUE TITLE
Is it possible to just use the drawing API without the scene graph?

### ISSUE THREAD

**Issue by EisenbergEffect** [pixijs/pixi.js#4455]
I'm curious to know if (and how) it's possible to just use the 2d drawing API without the scene graph (I want to create my own object model for other purposes). Basically, I'm looking for something that provides the Canvas 2d API but on top of WebGL. Is that possible with Pixi.js?

**Comment by themoonrat** [comment]
A canvas can be used as a base texture in pixi. So use all of the canvas api you want onto your canvas then create a texture of it when you're finished and let a Sprite use it. If you then do some more drawing on that canvas, just call .update() on the texture, and your sprite will update to display the latest changes to that canvas

**Comment by englercj** [comment]
If you are only using the canvas2d api and uploading it as a texture, you should just use canvas2d and not WebGL. Canvas2d is hardware accelerated in most browsers nowadays, did you encounter performance issues with Canvas2d that made you want to switch to WebGL?

**Comment by ivanpopelyshev** [comment]
Yeah, look how pixi tree works (DisplayObject, Container, Sprite), make your own. Add more renderers (SpriteRenderers e.t.c.) if you need so. The sky is the limit.

I have three projects with custom stage trees on pixi, but I wont share, its proprietary ;)

**Comment by EisenbergEffect** [comment]
Thanks everyone!
