### ISSUE TITLE
TextStyle padding option

### ISSUE THREAD

**Issue by akhnaz** [pixijs/pixi.js#4456]
Hi,

Currently, padding on TextStyle is set to all sides of text which is not enough to fix problem with some fonts are cropped (some fonts sometime have the left side bearing and right side bearing too much).

I would like to request the padding value to be also an object so it can be set separately.

example:
```
// to only have padding on the left
const textstyle = PIXI.TextStyle();
textstyle.padding = {
  left: 10
};

// to set the same value of all sides
textstyle.padding = 10;

// to set different value for different side
textstyle.padding = {
  left: 10,
  right: 5,
  top: 3,
  bottom: 2
};
```

**Comment by themoonrat** [comment]
@akhnaz One option is to add padding, but then also enable trim to make sure the texture you have is even on all sides?
