### ISSUE TITLE
How to get pixels of Pixi graphics

### ISSUE THREAD

**Issue by orklann** [pixijs/pixi.js#4457]
Is there any way to get pixels data of Pixi graphics? example code would be good.

**Comment by themoonrat** [comment]
http://pixijs.download/dev/docs/PIXI.extract.html

**Comment by orklann** [comment]
@themoonrat  thank you for the doc, and my solution works by using the API you pointed to.

```
var extract = renderer.plugins.extract;
var canvas = extract.canvas();
const context = canvas.getContext("2d");
var rgba = context.getImageData(p.x, p.y, 1, 1).data;
```

**Comment by ivanpopelyshev** [comment]
@orklann 
You can use `pixels()` instead. No need to create temporary canvas, it only makes extra operations for that.

**Comment by ivanpopelyshev** [comment]
Ah, right, we forgot to count flipY in pixels() . If you use pixels, flip y-coord and it'll be ok.
```
var newY = renderer.height - p.y - 1;
```

**Comment by orklann** [comment]
@ivanpopelyshev 
You pointed to the right place, but the `p.x` and `p.y` is floating values (like 1.79, 2.05), and I always calculated the wrong `offset` from `p`.

**Comment by ivanpopelyshev** [comment]
Use "floor" on it first , then use my formula :)

**Comment by ivanpopelyshev** [comment]
Ok, wait, do you want to implement Interaction with that thing? Why do you need only one pixel?

**Comment by orklann** [comment]
@ivanpopelyshev 
I use `parseInt(p.x)`, I think it's the same as `floor`?

I draw something with PixiJS, and need to highlight those drawings depending on the mouse clicking. Yes, I implement interactions.

**Comment by orklann** [comment]
`canvas()` is more accurate.

**Comment by ivanpopelyshev** [comment]
I know how to do interactions through a pixel. The method you chose is ideal only for one Graphics element. If there are two or more, it'll be a huge problem.

I assume you dont want to use standart pixi interaction because it doesn't see clicks on strokes (lines, edges)?

**Comment by orklann** [comment]
I redraw things one by one onto the hidden Graphics, and check if the mouse clicking on that pixel is transparent or not to decide if the thing should be highlight or not.

This is something like pixel perfect checking.

**Comment by orklann** [comment]
anyway, I will use `canvas()` by now, because it works perfect. I will debug `pixels()` later while other parts are done in my project. thank you for the discussion.

**Comment by ivanpopelyshev** [comment]
If you are experienced enough, you can make it that Graphics uses different shader, the one that places index of element instead of color in the result canvas if the pixel is under mouse. Then you can get the index with one "renderer.gl.readPixels" call. 

Problem is that no one uses it in pixi, except me, and my solution is proprietary and not open-sourced yet.

The way you chose will give the result but it is slow as a snail. Welcome to 2FPS zone. Better enhance standard pixi interaction and Graphics methods like "containsPoint".

**Comment by orklann** [comment]
Yep, maybe using `canvas()` will be slow, but I tested on my iMac, and I don't use it in `live` mode, so it's acceptable to me. btw, every `Path` (drawing things with a lot of subpath like curve, line, etc) has a bound (as a rect), so I will first filter out `path` whose bound does not contain mouse point, so the performance is so good so far.

**Comment by ivanpopelyshev** [comment]
You can render shapes with different colors. Just beware that RGBA you get is premultiplied so if alpha <1 then you'll see Ra, Ba, Ga and not RGB.

But I still dont understand why dont you just hack pixi interaction.

**Comment by orklann** [comment]
@ivanpopelyshev 

yep, clever solution, with different colors, so I just need one draw and call `canvas()` once.
