### ISSUE TITLE
PIXI.mesh.Rope demo broken by PixiJS update

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#4458]
When I use the latest version of PixiJS (4.6.1) instead of the older version 3.0.8 for this demo
https://tobireif.com/demos/merry_christmas/
the PIXI.mesh.Rope animated tree is broken:
<img width="524" alt="screenshot" src="https://user-images.githubusercontent.com/80411/33016574-591d3594-cdef-11e7-856c-5c40fa8ac509.png">

**Comment by ivanpopelyshev** [comment]
Wow, that's interesting. Care for a fiddle? :) or just zip-file is enough for me.

**Comment by tobireif** [comment]
Thanks for your interest!

Here you go:
[merry_christmas_new_pixi.zip](https://github.com/pixijs/pixi.js/files/1487482/merry_christmas_new_pixi.zip)

**Comment by ivanpopelyshev** [comment]
Ok, seriously, WTF is going there?

**Comment by tobireif** [comment]
The issue must be in PixiJS somewhere ...

**Comment by ivanpopelyshev** [comment]
I found critical bug in ParticleContainer. And probably other things too.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev keep me posted, happy to push through a releases if needed.

**Comment by tobireif** [comment]
Thanks so much for caring/investigating/etc @ivanpopelyshev and @bigtimebuddy !

**Comment by ivanpopelyshev** [comment]
@tobireif Congratulations. If you've made that demo year ago, we could save so many lives^W projects. At least we'll fix it now and in v5.

**Comment by bigtimebuddy** [comment]
This build, with @ivanpopelyshev's change, fixes the demo: https://dl.dropboxusercontent.com/s/gpjhqclp1o2higw/pixi.min.js

**Comment by tobireif** [comment]
@ivanpopelyshev 

> Congratulations!

Sincere or sarcastic? With you I never know 😀

In any case: Thanks so much for fixing the issue!

> If you've made that demo year ago, we could save so many lives^W hours!

I had made that demo two years ago 😀

http://www.html5gamedevs.com/topic/494-pixijs-showcase/?page=6&tab=comments#comment-110530

It worked (and still works) fine with PixiJS 3.0.8.

Today I wanted to update to the latest version of PixiJS but saw the issue.

I hope you can ensure some sort of visual pre-release testing in order to prevent such issue for the future. That way, PixiJS would depend less on lib-users accidentally finding such issues. Would the rope demo http://pixijs.io/examples/#/demos/strip-demo.js have shown the issue with the current Pixi version? Just trying to think about QA and the future 😀

> At least we'll fix it now and in v5.

Yay! 👍 🎉

**Comment by tobireif** [comment]
I updated Pixi in https://tobireif.com/demos/merry_christmas/ to 4.6.1. + the fix ( https://dl.dropboxusercontent.com/s/gpjhqclp1o2higw/pixi.min.js ), and it works.

Thank you @ivanpopelyshev @bigtimebuddy @GoodBoyDigital !

**Comment by bigtimebuddy** [comment]
FYI @tobireif, I rebuilt this: http://pixijs.download/dev/pixi.js which should be a better thing to include.

**Comment by tobireif** [comment]
I need the minified version - is that the same thing just minified?

http://pixijs.download/dev/pixi.min.js

**Comment by bigtimebuddy** [comment]
Yup!

**Comment by jpardey** [comment]
Coincidentally, I've been working on a Christmas card involving a `mesh.Plane` behind a `ParticleContainer`, and the `Plane` wasn't showing up. Updating to 4.6.1 didn't fix it, but 4.6.2 did. Amazing work you're doing here, and thanks for fixing this!

**Comment by bigtimebuddy** [comment]
@jpardey could you open a new issue and provide an example of the issue you’re having? Might be different from this.

**Comment by jpardey** [comment]
@bigtimebuddy The changes in #4462 seem to fix the issue. My personal code is too convoluted for a bug report, and I've been having trouble consistently replicating the bug with jsfiddle. If you do want something that fails in 4.6.1 for regression tests or whatever, I should be able to put together a proper bit of demo code tomorrow.

**Comment by tobireif** [comment]
@jpardey Is our PixiJS Christmas card public? Just curious what yours looks like 😀
