### ISSUE TITLE
setTargetElement in documentation is labeled as @private in the comments while it should be public.

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#4459]
I've been using this feature for 2 years already. but noticed it's been labeled as @private now in the comments.   (and therefore now also in the pixi.d.ts which now breaks my compilation :)

I think this should be a public function though?

**Comment by bigtimebuddy** [comment]
@whizzkid, feel free to make a PR for this and remove `@private`.

**Comment by finscn** [comment]
I thin this issues could close. Because it's been fixed.
