### ISSUE TITLE
ParticleContainer docs not up to date

### ISSUE THREAD

**Issue by nikkop** [pixijs/pixi.js#4463]
It seems that since version 4.5.6 it is possible to add tint so individual sprites in a particle container. However, [the docs](http://pixijs.download/dev/docs/PIXI.particles.ParticleContainer.html) states this is not possible. Perhaps this should be updated?

- [4.5.6 official example](http://pixijs.io/examples/?v=v4.5.6#/demos/batch.js)
- [4.5.5 official example](http://pixijs.io/examples/?v=v4.5.5#/demos/batch.js)

**Comment by bigtimebuddy** [comment]
Would welcome a PR to fix the ParticleContainer header and be more explicit about tint working since 4.5.6.

**Comment by nikkop** [comment]
Ok, I have done so at #4465. Please bear in mind this is my first PR to PixiJS and I hope it's what you were expecting :)

**Comment by bigtimebuddy** [comment]
Merged. Thanks again.
