### ISSUE TITLE
[BUG] ParticleContainer's shader never used `scale`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4467]
When create `ParticleContainer` , there are some options : 
```
     * @param {boolean} [properties.scale=false] - When true, scale be uploaded and applied.
     * @param {boolean} [properties.position=true] - When true, position be uploaded and applied.
     * @param {boolean} [properties.rotation=false] - When true, rotation be uploaded and applied.
     * @param {boolean} [properties.uvs=false] - When true, uvs be uploaded and applied.
```

But whatever  the values of  `properties.scale` , in the ParticleShader ,  `scale` never be used.

![image](https://user-images.githubusercontent.com/288367/33066834-58f7a9e8-cee7-11e7-9619-ec6691c1ca2a.png)

See the highlight line  `attribute vec2 aScale;`, 
the `aScale` never be used in the `vertex shader`. 
So , in JS , whatever you set `properties.scale=false` or `properties.scale=true` , it's no effect.

**Comment by ivanpopelyshev** [comment]
Read the source code. Its about uploading into STATIC buffers and DYNAMIC ones. If you add element at index 0, everything will be re-uploaded. If you just change some props of elements, only dynamic properties will be re-uploaded.

**Comment by finscn** [comment]
I've update this issue. Please review this one again, thanks.

**Comment by finscn** [comment]
suggestion : 

1) remove `attribute vec2 aScale;` in the shader source. it's needless. because `scale` has been compute in  ParticleRenderer's `uploadVertices()`.

2) update the document about `properties.scale` in ParticleContainer.
in fact , when sprite's scale/frame/orig changed , users have to set  `scale:true` . 
though that option  named `scale` , but it's not only about `sprite.scale`.

**Comment by themoonrat** [comment]
Closing as looks like there were a couple of commits that fixed this
