### ISSUE TITLE
Pixi demo not shown in Chrome Canary

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#4470]
Please check out this issue report
https://bugs.chromium.org/p/chromium/issues/detail?id=786945
and all comments on that page.

Two of the comments:

"KBR" from the Chromium project:
> is there any way you can get Pixi.js to create its WebGL context without specifying the premultipliedAlpha context creation attribute (allowing it to default to true)? Or does its blending assume it's set to false? If you can get it to set it to true, that will work around this bug.

Me:
> A fix in Chrome would be much better than a workaround in PixiJS.
>
> If you fix it in Chrome it will work for everyone, not just for PixiJS.

What you decide to do is up to you :)

**Comment by ivanpopelyshev** [comment]
Yeah, no problem, in renderer options

```
transparent: 'notMultiplied'
```

**Comment by tobireif** [comment]
Does this transparent:'notMultiplied' have any drawbacks? Would it for example lower the rendering quality?

**Comment by ivanpopelyshev** [comment]
Theoretically, it does not change anything for solid picture without background.

```
this._contextOptions = {
            alpha: this.transparent,
            antialias: this.options.antialias,
            premultipliedAlpha: this.transparent && this.transparent !== 'notMultiplied',
            stencil: true,
            preserveDrawingBuffer: this.options.preserveDrawingBuffer,
            powerPreference: this.options.powerPreference,
        };
```

You can also try this one:

```
transparent: false
```

I bet they both will work in canary.

**Comment by tobireif** [comment]
Thanks! I hope the will fix it  in Chrome, as it is a Chrome issue (it works in Chrome stable so they can fix it in Canary).

**Comment by ivanpopelyshev** [comment]
Give them fiddles with those parameters, otherwise they wont fix it.

**Comment by finscn** [comment]
In Chrome Dev (last version) , the pixi demo often makes browser crash.
I don't know is  the reason is the same to this issue.

**Comment by tobireif** [comment]
@finscn 

Thanks for the info.

Can you report the issue you're seeing at https://bugs.chromium.org/p/chromium/issues/list ?

**Comment by tobireif** [comment]
Has been fixed in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=786945

@finscn Regearding the other issue you described above (crashes):
Are you still getting crashes? If yes: Please report the issue at https://bugs.chromium.org/p/chromium/issues/list .

**Comment by tobireif** [comment]
(Then this PixiJS ticket can get closed.)

**Comment by tobireif** [comment]
(Someone who is getting crashes eg in Chrome still needs to report that issue.)

**Comment by bigtimebuddy** [comment]
Oops misunderstood!

**Comment by tobireif** [comment]
@finscn 

If you're still getting crashes when open/viewing the  demo
https://tobireif.com/demos/merry_christmas/ :
Please report that issue at
https://bugs.chromium.org/p/chromium/issues/list .

I haven't had any crashes, so I can't report that issue.

@bigtimebuddy 

No problem!

This issue
https://bugs.chromium.org/p/chromium/issues/detail?id=786945
got fixed in Canary/Chrome, and the Chrome crashes should get reported in the Chromium bug tracker, so OK to close this Pixi ticket.
