### ISSUE TITLE
Multiple Sprites From Image

### ISSUE THREAD

**Issue by ezlikespie** [pixijs/pixi.js#4472]
Hello, I am trying to make identical sprites from a sprite sheet image by creating a texture for a sprite and changing the frame of the texture to animate it. This is my code: 
```
var playerTexture = PIXI.utils.TextureCache["public/images/SpriteSheet.png"];
var enemyTexture = PIXI.utils.TextureCache["public/images/SpriteSheet.png"];

PIXI.Texture.addTextureToCache(playerTexture, 'playerTexture');
PIXI.Texture.addTextureToCache(enemyTexture, 'enemyTexture');

var player = new PIXI.Sprite.fromFrame('playerTexture');
var enemy = new PIXI.Sprite.fromFrame('enemyTexture');
```
I can change the x and y positions of the player and enemy and it will work fine, but when I change the frame of the playerTexture to animate it, the enemy will also change, and vice-versa.

For example:
```
//This Works:
player.x = 100;
player.y = 100;
enemy.x = 70;
enemy.y = 70;
//But If I Do This:
playerTexture.frame = new PIXI.Rectangle(0,1*32,13*32,16*32);
//Then the enemyTexture.frame will change as well.
```
So far the only way I have found to fix this is by copying the SpriteSheet.png and making a SpriteSheet2.png and using that image instead for the enemy.

Any help or suggestions would be appreciated.

**Comment by ivanpopelyshev** [comment]
`new PIXI.Texture(oldTexture, newFrame)` wil make sure that textures are different. Right now playerTexture and enemyTexture are pointing to the same texture.

**Comment by ezlikespie** [comment]
Can you give me some example code, please? I tried doing what you said by instead of doing `playerTexture.frame = new PIXI.Rectangle(0,1*32,13*32,16*32)` replacing that with this, `new PIXI.Texture(playerTexture, new PIXI.Rectangle(0,1*32,13*32,16*32))`, but it gives the error that PIXI.Texture is not a constructor.

**Comment by ivanpopelyshev** [comment]
"PIXI.Texture is not a constructor" - that's not possible, sorry. Look, I can even make 8 different rotations of same texture: http://pixijs.io/examples/#/demos/texture-rotate.js

**Comment by ezlikespie** [comment]
I got it to work, but will it be a speed problem if I am changing the frame like this for multiple characters, multiple times a second?

**Comment by ivanpopelyshev** [comment]
You can create all the textures before you start the animation and then just change `sprite.texture = textureWithFrame15` . That's how AnimatedSprite works, by the way.

**Comment by ivanpopelyshev** [comment]
Actually, in libgdx engine, that thing is named TextureRegion, not Texture. Just to make sure you understand what is it :)

**Comment by finscn** [comment]
I don't advice that use `PIXI.utils.TextureCache` directly.
Please do sth. like this: 
```js
var baseTexture = new PIXI.BaseTexture('public/images/SpriteSheet.png');
var playerTexture = new PIXI.Texture(baseTexture);
var enemyTexture = new PIXI.Texture(baseTexture);

var player = new PIXI.Sprite.from(playerTexture);
var enemy = new PIXI.Sprite.from(enemyTexture);
``` 

In my case , the playerTexture & enemyTexture are different instances of `PIXI.Texture`.
So you could change their `frame` freely.

.

**Comment by ivanpopelyshev** [comment]
`from` doesnt need `new`

**Comment by gitgudongithub** [comment]
What is the solution for this now ? 
That doesnt seem to work:
var baseTexture = new PIXI.BaseTexture('public/images/SpriteSheet.png');
var playerTexture = new PIXI.Texture(baseTexture);
var enemyTexture = new PIXI.Texture(baseTexture);

var player = new PIXI.Sprite.from(playerTexture);
var enemy = new PIXI.Sprite.from(enemyTexture);
 @finscn 
Caus the argument given to BaseTexture isnt assignable.

**Comment by themoonrat** [comment]
Just use `.from` to cover you in pretty much all scenarios
`var player = PIXI.Sprite.from('imgs/player.png')` 
or if you already have a texture.
`var player = PIXI.Sprite.from(playerTexture);`

**Comment by gitgudongithub** [comment]
> Just use `.from` to cover you in pretty much all scenarios
> `var player = PIXI.Sprite.from('imgs/player.png')`
> or if you already have a texture.
> `var player = PIXI.Sprite.from(playerTexture);`

ty, that works well
