### ISSUE TITLE
Pixijs dont render sprite on Meteor when using dynamic route

### ISSUE THREAD

**Issue by damjuve** [pixijs/pixi.js#4479]
Hi,

I am working on a project using Meteor with Pixi.js, 
and I'm facing a very strange problem when I try to use a router
(I tried both IronRouter and FlowRouter), and a pixi canvas.

The canvas is built, but i cant render any sprite on it.
This happen only when i use a route parameter, such as '/game/:id'

This is working except when i use a route parameter, such as '/game/:id'
More, if i dont use route parameter,
Sprite is showing up when i access '/game'
Sprite doesn't show up when i access '/game/

Here is a minimal error code on a meteor app :

Any Router definition :
Router.route('/room/:_id', {
    action: function() {
        this.render('game');
    }
});

A basic template :
Html :
<template name="game"></template>

Js :
Template.game.onRendered(function () {
PIXI.loader.add("assets/mario.png")
    .load(() => {
        let app = new PIXI.Application();
        document.body.appendChild(app.view);
        let mario = new PIXI.Sprite(PIXI.loader.resources["assets/mario.png"].texture);
        mario.position.set(5, 5);
        mario.width = 48;
        mario.height = 48;
        app.stage.addChild(mario);
        app.render();
    });
});

The pixi canvas will show up but mario sprite doesn't.

**Comment by ivanpopelyshev** [comment]
Because `load()` can be used only one time. You have to reset the loader, or use different loader for that code to work. 

Also dont forget to destroy whole application when that thing is removed from screen, you're leaking canvases there.

**Comment by damjuve** [comment]
Hi, thanks for the awnser

I actually use load only 1 time, i just wanted to access to my template who render the game using an id in the url.
As i said the issue occure when router deals with a dynamic url (/game/[id] or /game/ but not /game)
I am not sure how routers works on meteor but this looks like a very strange problem so i dont know where to look at.

**Comment by ivanpopelyshev** [comment]
You use loader two times, because its the same global loader.

```js
var myNewLoader = new PIXI.loaders.Loader();
```

> I am not sure how routers works on meteor but this looks like a very strange problem so i dont know where to look at.

Same as routers and components in angular and react and other frameworks. The problem is not strange, its just first time you deal with external resources. 

Again, I remind you that you have to find the place where to put "app.destroy()", or you'll have serious memory leak.
