### ISSUE TITLE
hq2x GLSL shader: missing main()

### ISSUE THREAD

**Issue by daintycode** [pixijs/pixi.js#4480]
I'm trying to use the hq2x shader from [Armada651/hqx-shader](https://github.com/Armada651/hqx-shader), but I get `ERROR: Missing main() (compileProgram.js:73)`.

Because the vert-frag-stuff (i'm not that confident with shaders tbh) is in one file i initialized the PIXI filter with both arguments using the same source (the full glsl file) first.

Then I splitted the glsl file into the right parts und using them. Yields to `unknown overload: transpose`.

Lastly I tried only supplying one argument (the full glsl file), still missing main. But this time once. Makes sense.

I see that the shader checks if it's asked for VERTEX or FRAGMENT, so I guessed my first way of using it was right, but the result feels like neither VERTEX nor FRAGMENT are defined ever.

Is there something wrong with pixi or is there a right way to use this/any glsl shader with pixi?

**Comment by ivanpopelyshev** [comment]
I really need more details to help in that case.

**Comment by daintycode** [comment]
Long time no see. ;)

- Used this shader file: [shader.glsl](https://github.com/Armada651/hqx-shader/blob/master/glsl/hq2x.glsl)
- Got a container containing _everything_, more containers, sprites, all that.
- Applied the shader like that:
`const filter = const filter = new PIXI.Filter(glslSrc, glslSrc);
mainContainer.filters = [filter];`
- Results into said error, it tells me there is no `main()` in the shader. I guess it's a problem with this if-else FRAGMENT/VERTEX stuff in there..
- To ensure I did the actual appliance of filters right I tried it with `new PIXI.filters.BlurFilter()`, works as expected.

**Comment by ivanpopelyshev** [comment]
Try `'#define VERTEX 1\n'+glslSrc` and `#define FRAGMENT 1
n'+glslSrc` respectively. Also prepare to understand how filters in v4 work. Its not easy. https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters

**Comment by daintycode** [comment]
That makes totally sense actually, I prepended it. Now I get:
```
ERROR: 0:20: 'transpose' : no matching overloaded function found
```
and
```
ERROR: 0:57: 'transpose' : no matching overloaded function found
ERROR: 0:57: '=' : dimension mismatch
ERROR: 0:57: '=' : cannot convert from 'const mediump float' to 'mediump 3X3 matrix of float'
ERROR: 0:65: 'mat4x3' : undeclared identifier
ERROR: 0:65: 'pixels' : syntax error
```

But I already see in your linked wiki-page that it's not a simple copy-paste thing any more when it comes to shaders?
So I guess its not really pixis fault and I'm not even going to dig deeper into that.^^

**Comment by ivanpopelyshev** [comment]
You need webgl2 for "transpose" and "mat4x3". PIXI v4 supports only webgl1, however for pixi-v5. You can try to build thing from "next" branch, or just wait two months or so :)

**Comment by daintycode** [comment]
Ohh, now i get it. Alright, thanks.
Well, it's not that necessary for me right now, just read somewhere about pixi supporting stuff like that and I wanted to try it out. :)

**Comment by ivanpopelyshev** [comment]
Well you can try to hack it that way it creates webgl2 context instead of webgl, may be it'll work fine.

**Comment by ivanpopelyshev** [comment]
Basically, if you know how webgl works, you can use pixi for faster development, because it takes care of many things but not everything.
