### ISSUE TITLE
PIXI.BaseTexture.fromImage - crossOrigin is TRUE by default (documentation doesn't say)

### ISSUE THREAD

**Issue by kurozael** [pixijs/pixi.js#4485]
Can you please put a note on your documentation to indicate this, we were expecting crossOrigin to be false by default.

Thanks :)

**Comment by bigtimebuddy** [comment]
Feel free to make a PR for this.

**Comment by themoonrat** [comment]
@kurozael Think you could submit a quick PR for this? Let us know! Cheers :)

**Comment by kurozael** [comment]
Hi @themoonrat, it appears the documentation is currently saying:

> Should use anonymous CORS? **Defaults to true if the URL is not a data-URI.**

So all is okay and this can be closed :)

**Comment by themoonrat** [comment]
thanks for the response!
