### ISSUE TITLE
Public subscribe to ObservablePoint

### ISSUE THREAD

**Issue by axldns** [pixijs/pixi.js#4486]
More a feature request than issue. 
Back in the times of PIXI 3.x, it was easy to follow position / scale / anchor / pivot of particular display object in dispersed solutions. Simple assignment `b.position = a.position`, regardless of good practices conduct, allowed to stick and unstick display objects easily.

Re-designed transformation system in PIXI 4.x put kibosh on it, and among other benefits, made tracking/following changes in position, scale, anchor, pivot as easy and faulty as _per frame check_ or _hacky as duck_.

Can we make this more friendly?

**Comment by ivanpopelyshev** [comment]
Some objects are copied and assigned by value even in Flash.

For most use-cases, `pixi-display` works better than sticking objects together.

**Comment by axldns** [comment]
I'm not denying that at all. Pixi-display works absolutely perfect. Just wanted to see, if there's a chance for extending the ObservablePoint API rather than changing the way it works.
