### ISSUE TITLE
Rendering breaks with 2 shaders affecting geometry

### ISSUE THREAD

**Issue by nuthinking** [pixijs/pixi.js#4488]
In a project I am using fragment shaders to affect geometry (like `scale` and `rotate`). When both filters are applied, other filters break (making things appear twice!).
<img src="https://user-images.githubusercontent.com/163635/33269846-6185acdc-d382-11e7-9db4-d5ab404ee5d5.png" width="250" height="250">
If only 1 is applied, things seem fine.
<img src="https://user-images.githubusercontent.com/163635/33269888-7d3f690e-d382-11e7-884a-27bfe6031230.png" width="250" height="250">
Codepen [here](https://codepen.io/nuthinking/pen/VrGZRL?editors=0011).
It could easily be a bug in my shaders, if so it would be great to know what I am doing wrong.
Thanks a lot!

**Comment by ivanpopelyshev** [comment]
There's fourth param you have to pass thorugh, called "clear"

```js
rotateFilter.apply = function(filterManager, input, output, clear){
  this.uniforms.dimensions[0] = input.sourceFrame.width;
  this.uniforms.dimensions[1] = input.sourceFrame.height;
  filterManager.applyFilter(this, input, output, clear);
}
```

That fixed your fiddle.

**Comment by nuthinking** [comment]
Wow, thanks a lot for spotting this!

**Comment by ivanpopelyshev** [comment]
I also changed Wiki to add that param.
