### ISSUE TITLE
Logical error in FilterManager.applyFilter?

### ISSUE THREAD

**Issue by Zzzen** [pixijs/pixi.js#4491]
trdl: I encountered an error when I destroyed WebGLRender. As you see, filters starting from 1 have no glshaders. `filters[i].glShaders[renderer.CONTEXT_UID]` will be undefined and an exception will be thrown.

I have two PIXI.Graphics objects, each of which has exactly one filter.
![image](https://user-images.githubusercontent.com/6630042/33301106-d349108c-d42e-11e7-8e0c-a671ea7d9396.png)

Here is my current workaround.
![image](https://user-images.githubusercontent.com/6630042/33301328-2fd9070c-d430-11e7-8de6-eeefcd99908b.png)
text version
------------
```javascript
    applyFilter(filter, input, output, clear)
    {
        const renderer = this.renderer;
        const gl = renderer.gl;

        let shader = filter.glShaders[renderer.CONTEXT_UID];

        // cacheing..
        if (!shader)
        {

+          let isFromCache = true
            if (filter.glShaderKey)
            {
                shader = this.shaderCache[filter.glShaderKey];

                if (!shader)
                {
                    shader = new Shader(this.gl, filter.vertexSrc, filter.fragmentSrc);
+                  isFromCache = false

                    filter.glShaders[renderer.CONTEXT_UID] = this.shaderCache[filter.glShaderKey] = shader;
                }
            }
            else
            {
                shader = filter.glShaders[renderer.CONTEXT_UID] = new Shader(this.gl, filter.vertexSrc, filter.fragmentSrc);
+              isFromCache = false
            }

+          if (!isFromCache) {
                this.managedFilters.push(filter);
                
                // TODO - this only needs to be done once?
                renderer.bindVao(null);

                this.quad.initVao(shader);
+          }
        }

        renderer.bindVao(this.quad.vao);

        renderer.bindRenderTarget(output);
```

**Comment by ivanpopelyshev** [comment]
I thought I fixed it in 4.6.2 . Are you sure? Can you try same thing with 4.6.2?

**Comment by ivanpopelyshev** [comment]
Oh wait, its not released yet. Try this one: https://pixijs.download/dev/pixi.js

**Comment by Zzzen** [comment]
When will it be released? BTW, FilterManger has no test, which I think is dangerous.

**Comment by ivanpopelyshev** [comment]
Today or tomorrow. As for tests, https://github.com/pixijs/pixi.js/pull/4431

**Comment by Zzzen** [comment]
Good job

**Comment by Zzzen** [comment]
works on 4.6.3!
