### ISSUE TITLE
Firefox Quantum WebGL Warning

### ISSUE THREAD

**Issue by marcus-sa** [pixijs/pixi.js#4496]
I'm using the latest version of Firefox Quantum (I know it's experimental)
> PixiJS 4.6.1 - WebGL - http://www.pixijs.com/

So practically isn't the purpose of **autoDetectRenderer** to detect whether or not the browser actually supports WebGL fully?
I get this error in console when initializing a new Pixi.js renderer and doing some basic stuff:

> Error: WebGL warning: drawElements: This operation requires zeroing texture data. This is slow.

By the time I've finished writing this issue, it still haven't rendered anything at all, so the question is; wouldn't it be better to use canvas renderer in Firefox Quantum?

Renders in WebGL without problems in the latest version of Google Chrome

**Comment by ivanpopelyshev** [comment]
> Error: WebGL warning: drawElements: This operation requires zeroing texture data. This is slow.

I still dont know what is this warning about. @GoodBoyDigital any ideas?

> By the time I've finished writing this issue, it still haven't rendered anything at all

not related to that warning. What exactly is not working there?

**Comment by themoonrat** [comment]
Just to say, we are also getting this Firefox issue in our games now; only happens since the first quantum release.
You can see the warning happen even on the basic Pixi example.
I believe it might be related to rendering sprites that have no loaded texture source yet.

**Comment by ivanpopelyshev** [comment]
That's strange, because if texture is not valid, sprites aren't rendered at all. May be it related to empty textures we use in renderer. They are small so `slow` does not affect us.

**Comment by garkin** [comment]
This warning bugs me too. Firefox sourcee code could help:
https://github.com/mozilla/gecko-dev/blob/1cdb198bd9e1d2605ac48d2588e29475fb01a74e/dom/canvas/WebGLTexture.cpp#L645
```cpp
ZeroTextureData(WebGLContext* webgl, const char* funcName, GLuint tex,
                TexImageTarget target, uint32_t level,
                const webgl::FormatUsageInfo* usage, uint32_t width, uint32_t height,
                uint32_t depth)
{
    // This has two usecases:
    // 1. Lazy zeroing of uninitialized textures:
    //    a. Before draw, when FakeBlack isn't viable. (TexStorage + Draw*)
    //    b. Before partial upload. (TexStorage + TexSubImage)
    // 2. Zero subrects from out-of-bounds blits. (CopyTex(Sub)Image)

    // We have no sympathy for any of these cases.

    // "Doctor, it hurts when I do this!" "Well don't do that!"
    webgl->GenerateWarning("%s: This operation requires zeroing texture data. This is"
                           " slow.",
                           funcName);
```

**Comment by dennisdahlchristensen** [comment]
Is there something that can be done to avoid this performance hit ?
I have just tested the first basic Pixi example in FF, and even that triggers the warning.

**Comment by jdashg** [comment]
Firefox presently doesn't initialize texture images to zeros on creation, but rather only as necessary.
We will be moving to zeroing on creation Soon(tm), but that's the present cause of the warning: You're using a texture image before you initialize its data yourselves.

**Comment by profesors** [comment]
I find this warning only after I add a text layer in Mozilla 59.0.2 running in a MacOS:
```
    var layerText = new PIXI.Container();
    message = new PIXI.Text("Hello World");
    message.style.fill = 0xFFFFFF;
    message.position.set(54, 96);
    layerText.addChild(message);
    app.stage.addChild(layerText);
```

I hope this can help somebody to solve the issue.
