### ISSUE TITLE
Downloading example code from older versions still includes Application

### ISSUE THREAD

**Issue by Lukenickerson** [pixijs/pixi.js#4499]
Reproduction:

1. http://pixijs.io/examples/?v=v4.0.0#/demos/animatedsprite-demo.js
1. Select an older version of pixi from the drop down, e.g. v3.0.11
1. Click Download
1. View code: includes `var app = new PIXI.Application();`
1. Running code gives "Uncaught TypeError: PIXI.Application is not a constructor"

**Comment by ivanpopelyshev** [comment]
Actually, it works. You just need this thing: https://github.com/ivanpopelyshev/pixi-legacy/tree/master/bin
