### ISSUE TITLE
Italic text are cut off on the top-right corner on Asian Languages

### ISSUE THREAD

**Issue by ning-nolimitcity** [pixijs/pixi.js#4500]
We are using PIXI 4.4.2.
For English and other western languages, no problem. but for the Asian languages (Chinese Thai and Korean as I tested) the top right corner is cut off.

On the image the font is OpenSans, I've also tested some other fonts, the results are the same.

```
new PIXI.Text("继续", {
        "fontFamily" : "Open Sans",
        "fontStyle" : "italic",
        "fontSize" : 28,
        "fill" : "#ffffff"
    });
```

![image](https://user-images.githubusercontent.com/17565912/33422716-de01c58a-d5b6-11e7-88ae-644662133adb.png)

**Comment by themoonrat** [comment]
Add some padding to your style. The libs makes some best guesses about how big to make the 2d canvas which is used to create text, but it's not always correct. Padding will give the 2d canvas extra space in which to draw the text, and fix your problem

**Comment by ivanpopelyshev** [comment]
Difficult solution.

Add more symbols there: https://github.com/pixijs/pixi.js/blob/dev/src/core/text/TextMetrics.js#L195 

Just patch it

```js
PIXI.TextureMetrics.measureFont = function(font) {
...
}
```

**Comment by themoonrat** [comment]
Closing as we've had a PR which can help you customise how text size is calculated merged in, and there is padding for fallback :)
