### ISSUE TITLE
BitmapText position accuracy issue using CanvasRenderer and roundPixels is true

### ISSUE THREAD

**Issue by mantolo** [pixijs/pixi.js#4501]
Hi, 

My project is using PIXI 4.5.3,

With usage of CanvasRenderer and `roundPixels` (#3581, #27) on
BitmapText's character position will look "shifting" during a period of `updateText()` call

the use case is a bitmap text for numeric count up, given identical xAdvance values for the number glyphs, and the issue will not occur in WebGLRenderer. Text values keep updating from 1 to lets say 15,000 over 5 seconds, under some window resize conditions, shifting of the text can be observed.

Additionally attempted to modify BitmapText.updateText(), if I force all glyphs final position to be wrapped by Math.floor(), it will be fine (not sure about the side effects)

Is that potentially an issue or is there any workaround?

**Comment by themoonrat** [comment]
@mantolo Is this still an issue for you in the latest version?

**Comment by mezykr** [comment]
+1 I also see this issue on latest version
