### ISSUE TITLE
Documentation specifies incorrect default value for `autoResize` param to constructor of `ParticleContainer`.

### ISSUE THREAD

**Issue by rozzzly** [pixijs/pixi.js#4504]
The docs say it is **`true`**.
https://github.com/pixijs/pixi.js/blob/d4cf9c84df1d0fe300d85e26d3e0f67f90274b18/src/particles/ParticleContainer.js#L41

The code says it is **`false`**.
https://github.com/pixijs/pixi.js/blob/d4cf9c84df1d0fe300d85e26d3e0f67f90274b18/src/particles/ParticleContainer.js#L44

I'm assuming that the docs are outdated and that the desired value is in fact **`false`**, but stranger things have happened so I will forgo the PR and leave it for a maintainer—who knows what it should actually be—to review.

You gents the good work. I'll keep up the nitpicking. 😉

**Comment by ivanpopelyshev** [comment]
Oops :)

**Comment by bigtimebuddy** [comment]
Would gladly accept a PR for this if someone wants it

**Comment by rozzzly** [comment]
Done. #4508
