### ISSUE TITLE
WebGl: jagged edges of rounded shapes 

### ISSUE THREAD

**Issue by vlasenkoigor** [pixijs/pixi.js#4505]
Hi guys, I'm trying to draw rounded rect using PIXI.Graphics class, and I noticed one thing that webGl renderer draws this shape with some ugly jagged borders, but canvas renderer draws it good.
I know that this is known issue, does anyone have a solution how to draw it smoothly also for webGL renderer ? 
Thanks 

`this.clear();
this.beginFill(color, 1);
this.drawRoundedRect(0, 0, w, h, h/2);
this.endFill();`   

webGl renderer
![webgl](https://user-images.githubusercontent.com/6866909/33486380-7b97fed0-d6b2-11e7-8f98-e0f5366e1154.PNG)

canvas renderer 
![canvas](https://user-images.githubusercontent.com/6866909/33486385-7fc54756-d6b2-11e7-9292-2e1a7782bbfe.PNG)

**Comment by ivanpopelyshev** [comment]
try `antialias:true` in renderer options.

```
var renderer = PIXI.autoDetectRenderer(800, 600, {antialias:true});
```

**Comment by vlasenkoigor** [comment]
Thank you very much. It works
