### ISSUE TITLE
PIXI-picture very slow on mobile

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#4513]
Hi I was just looking at http://pixijs.io/examples/#/picture/overlay.js on my iPhone 6 

It’s very slow on mobile chrome and mobile safari. Is this expected ?

Thanks!

**Comment by ivanpopelyshev** [comment]
Yes, its expected to be very slow on mobiles because of heavy FrameBuffer usage.

**Comment by weepy** [comment]
Ah interesting I wonder how the css overlay is fast ?

**Comment by ivanpopelyshev** [comment]
Overlay exists on mobiles, but webgl interface doesnt have it, and we are using big hack. CSS does have access to native version.
