### ISSUE TITLE
[Feature Request] Dynamic generate texture atlas at runtime

### ISSUE THREAD

**Issue by k8w** [pixijs/pixi.js#4514]
Framework `Layaair` have a feature that can generate texture atlas dynamicly at runtime.

[Demo here](https://k8w.github.io/webgl_2d_benchmark/)

It manage several 2048x2048 atlas, and when some texture (less than 512x512) need to render, it will draw them into the big atlas (use maxrect algorithm).

It is very useful for scene with lots of textfields and avatar images (download from Internet).

And with the advantage of "multiple texture in single batch" by pixi.js.
The performance may be extremly good!

Compare: 100 png (without packaging atlas), texture in WebGL Inspector
**Layaair**
![](https://i.loli.net/2017/12/06/5a2794f52ab56.png)

**Pixi.js**
![](https://i.loli.net/2017/12/06/5a2794f551c59.png)

**Comment by ivanpopelyshev** [comment]
https://github.com/gameofbombs/pixi-super-atlas/ works in production in two projects (one by me, one by @cursedcoder). Unfortunately there are not many docs yet.

https://github.com/gameofbombs/pixi-super-atlas/blob/master/test/checkpack.ts

That's main method that swaps one texture for atlas'ed - https://github.com/gameofbombs/pixi-super-atlas/blob/master/src/superAtlas/SuperAtlas.ts#L69 . Dont forget to call repack after you add everything
