### ISSUE TITLE
Uncaught TypeError: (0 , _parseUri2.default) is not a function

### ISSUE THREAD

**Issue by perny** [pixijs/pixi.js#4515]
webpack3
pixi.js 4.6.2

`import * as PIXI from 'pixi.js';

import './css/styles.scss';
import './04_aliases.pug';

const requireContext = require.context('./images/', false);
requireContext.keys().map(requireContext);

const loader = new PIXI.loaders.Loader();

const app = new PIXI.Application(document.documentElement.clientWidth, document.documentElement.clientHeight);

document.querySelector('.canvas').appendChild(app.view);

loader.add('cat', '../20170828_pixi/images/cat.png')
  .load();`

chorme error：
Uncaught TypeError: (0 , _parseUri2.default) is not a function

thanks everybody！

**Comment by themoonrat** [comment]
Did you solve this? I get the feeling this is a Webpack setup issue rather than a PIXI issue, so closing for now :)
