### ISSUE TITLE
Missing PIXI.Stat 

### ISSUE THREAD

**Issue by k8w** [pixijs/pixi.js#4516]
Is there any way to display fps and drawcall for profiling?

just like:
![](https://i.loli.net/2017/12/06/5a27c073b2c57.png)

**Comment by ivanpopelyshev** [comment]
people make their own stuff to count drawcalls.
as for fps stat, you can use mrdoob stats.js or the thing that is used in Rpgmaker Web, look at sources, there was something about FPS: https://github.com/rpgtkoolmv/corescript

**Comment by k8w** [comment]
> people make their own stuff to count drawcalls.

Is that means I must modify pixi source code ?

**Comment by ivanpopelyshev** [comment]
Yep. SpriteRenderer is the most common place, search for `drawElements` and `drawArrays`.

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js

Another idea is to re-define "gl"'s drawElements and drawArrays that way they increase your counter, than call `WebGLRenderingContext.prototype.drawElements`.

**Comment by k8w** [comment]
Get it~

Buy why not pixi consider its own stat display ? 
It is like a standard feature that many render engine have.

**Comment by bigtimebuddy** [comment]
I agree @k8w good feature to have. We will consider more debugging features like this in v5, which is currently in progress.
