### ISSUE TITLE
Use switch instead of if..else ? In fragment shader of multi-texture batching

### ISSUE THREAD

**Issue by k8w** [pixijs/pixi.js#4520]
See this in fragment shader of multi-texture batching
```glsl
if(textureId == 0.0)
{
	color = texture2D(uSamplers[0], vTextureCoord);
}
else if(textureId == 1.0)
{
	color = texture2D(uSamplers[1], vTextureCoord);
}
else if(textureId == 2.0)
{
	color = texture2D(uSamplers[2], vTextureCoord);
}
else if(textureId == 3.0)
{
	color = texture2D(uSamplers[3], vTextureCoord);
}
else if(textureId == 4.0)
{
        // ... up to textureId 15.0
```

Maybe `switch...case` is better here ?
It seems switch is faster if there are many items.

**Comment by ivanpopelyshev** [comment]
switch is webgl2-only.

**Comment by ivanpopelyshev** [comment]
Actually, now that I think of it, correct nested tree of Ifs is the same as switch and we can optimize it a bit. But I dont believe it will give us even 10% of speed.

**Comment by ivanpopelyshev** [comment]
@finscn I summon you!

**Comment by finscn** [comment]
@ivanpopelyshev  I tested . I can't find any difference .
My friend tells me : "When `if..else` is very simple , it doesn't make shader-branching" 
e.g.
```js
x = 0;
if (a>1000) {
  x = 1
}
else if (a>100){
  x = 2
}
else if (a>10){
  x = 3
}
```
The shader  compiler will make the code become : 
```
x = a > 1000 ? 1 : ( a > 100 ? 2 : ( a > 10 ? 3 : 0);
```

I think the if...else in Sprite shader is `simple`

**Comment by ivanpopelyshev** [comment]
if its simple then it asks all the samplers.
