### ISSUE TITLE
DragOver event?

### ISSUE THREAD

**Issue by caracal7** [pixijs/pixi.js#4521]
Is it possible to catch DragOver event on pixi.Sprite?

I need to drag html content to PIXI canvas but then I drag it 'mousemove' and 'dragover' events is not fired((

**Comment by ivanpopelyshev** [comment]
That's what we have: https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js

No dragover :( You have to hack the manager, its inside `renderer.plugins.interaction`

**Comment by caracal7** [comment]
I already did it by adding to 'dragover' the same handler as to "mouseover" in InteractionManager.js 

`
// line 795

this.interactionDOMElement.removeEventListener('mouseover', this.onPointerOver, true); 
this.interactionDOMElement.removeEventListener('dragover', this.onPointerOver, true); 
`
Now in my project it works fine because I don't use 'mouseover' but It will be good to separate this events. But at moment I don't know how)
