### ISSUE TITLE
using pixi loader directly in html file

### ISSUE THREAD

**Issue by randomarchive101** [pixijs/pixi.js#4522]
I just started with pixi, and I would like to load an animated json model as is shown [here](http://pixijs.io/examples/#/basics/spritesheet.js) but instead doing it in .js i would like to do it directly in the html file. 
So I tried to load json model as is shown [here](https://github.com/pixijs/pixi-examples-v2/blob/master/examples/others/loader-progress.html) (and then somehow work out how to add animation) but in the example they dont add it to the stage. 
I tried various ways to do it, but nothing seems to make an image show even if try using a .png instead of .json. Help?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Spritesheet.js#L11

You have to get baseTexture from loader or somehow else. Then use this class to parse your json and get the textures.

**Comment by randomarchive101** [comment]
Okay, i know im completely butchering this, and im sorry, because this is what i manage to come up with (hint: it doesnt work and it  might hurt your eyes)
```
			loader.add('t','monster.json');
			loader.on('complete',function (loader,res) {
                                var texture= res.t.BaseTexture;
				var spritesh= new PIXI.Spritesheet( texture,t); //im not sure what data in this case is?
				stage.addChild(spritesh.parse(callback)); //i have no idea where im supposed to get callback 
				text.text = "Everything is loaded! If it was too quick for you, use your network panel :)";
			});


			loader.load();
```
Sorry again, i know this isnt even close, but when i said "i just started with pixi" i do mean today...

**Comment by randomarchive101** [comment]
Okay i realized i was going about it the wrong way, since didnt actually need to change anything from the first example to make it work in a html file. Man i feel stupid. Sorry for bothering you.
