### ISSUE TITLE
Demos look different on Chrome and Safari

### ISSUE THREAD

**Issue by JohnnyG2017** [pixijs/pixi.js#4523]
Hi All,

I hope this wasn't covered already but am I the only one seeing [this issue](https://snag.gy/VHTCNm.jpg)?

It appears that the samples are all transparent on Safari. Chrome works as expected. 

- Is this a bug with Safari 11+? 
- Are there any workarounds? 

Any information work be greatly appreciated!

`Safari Version 11.0.2 (12604.4.7.1.4)`
`Chrome Version 63.0.3239.84 (Official Build) (64-bit)`

Thanks!

**Comment by jpweeks** [comment]
I ran into this issue yesterday; it's a bug in Safari `11.0.2` (which was just released December 7).
It's related to the `transparent` WebGL context attribute and the containing element's css `background-color`. With `transparent = false` and `background-color: #fff`, the rendered canvas will be fully transparent; changing `background-color: #000` renders as expected.
This is a fiddle of these conditions: https://jsfiddle.net/n9ccne2n/

**Comment by zolotykh** [comment]
Same issue in user's browser (OS X El Capitan Safari 11.0.2)

**Comment by themoonrat** [comment]
Hoping Safari has fixed this by now!
