### ISSUE TITLE
How to use pixi in es6 version ? 

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4524]
the pixi is wrote by ES6 , but in dist , it's compiled to es5 .

How to keep ES6 code ?

**Comment by bigtimebuddy** [comment]
Rebuild without Babel. You might need uglify-es to compress output.

**Comment by finscn** [comment]
How to rebuild without Babel ? Is there a script in current PIXi ? or I need create it by myself ? thanks.

**Comment by VCtaiwan** [comment]
Try add the igrone target in .bablerc

```
{
  "ignore": [
    "filepath/yourfile.js"
  ]
}
```

Babel will complied to es5 without ignore files.

**Comment by themoonrat** [comment]
Closing as looks like you have an answer :)
