### ISSUE TITLE
Is there a WebGL only version of PIXI?

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi.js#4525]
Now that WebGL is widely supported (97%+) I think it makes sense for PIXI to have a WebGL-only version (for both speed and bundle size reasons).

Can it be compiled so that the dist bundle doesn't include any Canvas-specific code (eg. removes everything related to the canvas renderer).

And as a "larger" question, do you think Canvas fallback is still needed?

**Comment by bigtimebuddy** [comment]
Agreed! We have designed this for v5 which is currently on the “next” branch. The default build of PixiJS v5 will not have canvas, which is now treated as second class.

**Comment by Cristy94** [comment]
I just realised after asking the question that one use case for Canvas rendering might be server-side rendering. But I don't know if anyone actually used, uses or will use PIXI for server-side rendering (on servers without GPUs).

Still, the first question is still unanswered: can the current build be bundled without the Canvas renderer?

**Comment by ivanpopelyshev** [comment]
Current, no. This one works without canvas: https://github.com/pixijs/pixi.js/tree/next . Even more, if you try "pixi-legacy" build from that branch, it wont work because CanvasRenderer is botched and we havent fixed it yet.
