### ISSUE TITLE
Clamping custom textures to their UVs

### ISSUE THREAD

**Issue by akella** [pixijs/pixi.js#4528]
First of all, thank you all the contributors for this wonderful engine.
Secondly: Is there any option in PIXI to clamp textures to their UVs so they dont repeat edge pixels?
It works by default for uSampler, but not for custom ones.
Here is example (second one):
https://cdn.rawgit.com/akella/masks/664a6ad2/build/page.html
And code for this one: 
```

 	var newimage = PIXI.Sprite.fromImage('img/5_.jpg');
 	var oldimage = PIXI.Sprite.fromImage('img/6_.jpg');
 	background.width = app.renderer.width;
 	background.height = app.renderer.height;


 
 	app.stage.addChild(background);


 	// Stop application wait for load to finish
 	app.stop();

 	PIXI.loader.add('shader', 'js/shader.frag')
 	    .load(onLoaded);

 	var filter;


 	function onLoaded(loader,res) {


 	    filter = new PIXI.Filter(null, res.shader.data);

 	    background.filters = [filter];

 	    filter.uniforms.currentimage = newimage._texture;
 	    filter.uniforms.oldimage = oldimage._texture;
 	    filter.uniforms.time = 0;
 	    app.start();
 	}

```
and in shader i just map them to UVs with a shift: https://github.com/akella/masks/blob/master/src/js/shader.js

As a hack i added 2px black border, but still some horizontal artefacts could be seen on a dog texture (the second animation). Is that a thing i can just enable in API or should i clamp it manually?

**Comment by ivanpopelyshev** [comment]
SpriteMaskFilter clamps textures, even if uv's are inside atlas.

https://github.com/pixijs/pixi.js/tree/dev/src/core/renderers/webgl/filters/spriteMask

You can use that `clip` approach from fragment shader to make better filter.

Also there are problems with shaders in v5, you have to read https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters to understand it.

Dont forget to fiddle with `filter.padding`, may be make it zero.

Try custom renderer approach, it doesnt have all those problems with coords: https://github.com/pixijs/pixi-plugin-example
