### ISSUE TITLE
PIXI.Polygon tool for generator point ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4529]
hey guys , do you have a Shape point generator with polygon coordinate ?
A tool like that
https://github.com/pixijs/pixi-text-style
but for make spatial coordinate for use PIXI.Polygon and drawShape(shape)PIXI.GraphicsData ?
thank
i search on the web but i not found a tool to help me to draw.

**Comment by ivanpopelyshev** [comment]
Physics Editor export is easy to add in the game.

**Comment by djmisterjon** [comment]
thank a lot friend , awsome tool
