### ISSUE TITLE
canvas() on extract double and flipping the drawings

### ISSUE THREAD

**Issue by orklann** [pixijs/pixi.js#4530]
Bug demo code: https://jsfiddle.net/kkjwfk1t/

Steps to reproduce:

* Open above link
* Click the `start test` button
* An HTML Canvas element will be insert into the page which double the drawings and flipping it.

But if change line 6:

```javascript
 var app = new PIXI.Application(800, 600, { antialias: true, transparent: true, backgroundColor: 0xffffff});
```

to

```javascript
 var app = new PIXI.Application(800, 600, { antialias: true, transparent: false, backgroundColor: 0xffffff});
```

the bug is gone.

I think this is a bug on WebGL renderer and transparent.

Need help

**Comment by ivanpopelyshev** [comment]
It depends on browser. We think that its always flipped, and flip it back: https://github.com/pixijs/pixi.js/blob/dev/src/extract/webgl/WebGLExtract.js#L98 , however you shown that its not the case.

**Comment by orklann** [comment]
I created another demo which let you download an image presenting the whole renderer without talking to canvas(), and it works normally.

https://jsfiddle.net/4yLu3g3w/ 

And the code is almost the same as the first one, beside last part.

**Comment by ivanpopelyshev** [comment]
```var data = renderer.view.toDataURL();```

That works only if you use "preserveDrawingBuffer". Otherwise, no guarantees.
