### ISSUE TITLE
ReferenceError: TouchEvent is not defined

### ISSUE THREAD

**Issue by josephmcasey** [pixijs/pixi.js#4533]
`event instanceof TouchEvent`

TouchEvents are not defined by a few browsers which are not Chrome, such as FireFox.

https://github.com/pixijs/pixi.js/blob/923a8eced8e43f71d48d7916305b48588bccf69b/src/interaction/InteractionManager.js#L1723

**Comment by josephmcasey** [comment]
Considering the documented param for this method, might I suggest the following?

`!(event instanceof MouseEvent && event instanceof PointerEvent)`

**Comment by andrewstart** [comment]
What is different about your setup that `window.ontouchstart` exists, but `TouchEvent` does not? For me, Firefox 57 has neither of these defined, so `this.supportsTouchEvents` would be set to false when the InteractionManager is created.

**Comment by josephmcasey** [comment]
FireFox 57.0.1 (64-bit), MacOS High Sierra (10.13.1)

It looks like on of my extensions was defining a function on the window.ontouchstart namespace. My apologies for not being more thorough in my investigation.
