### ISSUE TITLE
When enable depthTest , there is a strange effect

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4536]
I use  `app.renderer.state.setDepthTest(true)` to enable DEPTH_TEST

but the sprites can't be rendered correct.

I set gl_Position.z in shader (with custom shader) , one sprite is 

```
// A
gl_Position = vec4((projectionMatrix * vec3(v, 1.0)).xy, 0.0, 1.0);
```

another one is 
```
// B
gl_Position = vec4((projectionMatrix * vec3(v, 1.0)).xy, -1.0, 1.0);
```

I expect A could be over B , but not.

![image](https://user-images.githubusercontent.com/288367/33957565-ef113e98-e07c-11e7-8535-ac6f6f199e89.png)

the html-logo  & bunny are both with transparent background.

So How to use `setDepthTest` ?

**Comment by ivanpopelyshev** [comment]
Its not strange. Depth test isnt working with alpha. You have to make to passes on z-field, i dont want to explain it now , im busy.

**Comment by finscn** [comment]
I see.
