### ISSUE TITLE
Experimental: OffscreenCanvas

### ISSUE THREAD

**Issue by ruslanchek** [pixijs/pixi.js#4538]
Hi all! How about some experiments with OffscreenCanvas API? I think it could be useful in the future. For example it can be used for generating text-sprites for Text() objects, it can highly improve performance.   

[OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)

**Comment by bigtimebuddy** [comment]
Related: #4212 and #4207

The discussion in those PRs is useful for understanding how we think about experimental API features. OffscreenCanvas is definitely not something we are planning to add support for in v4.  For v5, we are focused mostly on taking advantage of WebGL 2 support whenever possible to improve performance.

If someone can show some real-world use cases for OffscreenCanvas and the performance benefits we'd gain by implementing, then we should consider it. There are different levels of utilizing OffscreenCanvas: 1). might be using it under-the-hood to help speed up rendering operations, and 2). supporting OffscreenCanvas via the PixiJS API for things like providing a view when creating a new renderer/application.

Would like to hear some specific examples of how we might take advantage of OffscreenCanvas. The example above for using with Text wouldn't really work because Text is context2d-only and OffscreenCanvas only works with WebGL.

**Comment by tekintatar** [comment]
+1 for this. I guess we can use OffscreenCanvas for extract method already build in PIXI. Offscreen canvas has a direct method of transferToImageBitmap which should be faster compared to creating buffer, readPixels and than creating a 2d canvas and getting base64. At least in theory for now.

Right here: http://pixijs.download/dev/docs/extract_webgl_WebGLExtract.js.html#line70. 

https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/transferToImageBitmap

I will do more investigation and will try to create some case and compare performance.

**Comment by johnnymast** [comment]
+1 want this !!

**Comment by themoonrat** [comment]
@tekintatar Did you ever manage to create some benchmarks that demonstrated the usefullness of this API within PIXI? Thanks!

**Comment by eranimo** [comment]
Why was this closed?

**Comment by sanbornhilland** [comment]
I'm also curious why this was closed. Was it moved somewhere else or have you decided that `OffscreenCanvas` support is not a priority? 

@bigtimebuddy I'll try to lay out a specific case for you here. I'm interested in using PIXI.js to draw/animate overlays overtop of a real-time video application and I'd like those overlays to be driven by a real-time data source (e.g. Twitter feed etc.). We're fighting a major bottleneck on the main thread with the video rendering alone, so adding all the additional work of handling the data + rendering overlays produces pretty janky video. What I'd really like to be able to do is move all of that work into a Web Worker and not have to worry too much about this new layer adding work to the main thread.

What I have been able to get working without much difficulty is something like this:

`main.js`
``` 
const w = new Worker('index.worker.build.js')
const canvas = document.createElement('canvas')
const offscreencanvas = canvas.transferControlToOffscreen()

w.postMessage({
  canvas: offscreencanvas,
}, [offscreencanvas])

document.body.appendChild(canvas)
```

`index.worker.build.js`
```
self.document = {
  createElement(type) {
    if (type === 'canvas') {
      return new OffscreenCanvas(0, 0)
    } else {
      console.log('CreateElement called with type = ', type)

      return {
        style: {},
      }
    }
  },

  addEventListener() {},
}

self.window = {
  console: self.console,
  addEventListener() {},
  navigator: {},
  document: self.document,
}

const PIXI = require('pixi.js')
const tweenManager = require('pixi-tween')

self.addEventListener('message', (event) => {
  const { canvas } = event.data
  canvas.style = {}

  const state = {
    canvas,
    app: new PIXI.Application({
      width: 1280,
      height: 720,
      view: canvas,
      antialias: true,
    }),
    graphic: null,
    message: null,
    textStyle: null,
    container: null,
    direction: 'right',
    padding: 25,
  }

  const gameLoop = (delta) => {
    self.requestAnimationFrame(gameLoop)

    PIXI.tweenManager.update()

    if (!state.graphic) {
      state.container = new PIXI.Container()
      state.graphic = new PIXI.Graphics()

      state.graphic
        .beginFill(0x00aaff)
        .drawRect(0, 540, 640, 90)
        .endFill()

      state.container.addChild(state.graphic)

      state.tween = PIXI.tweenManager.createTween(state.container)
      state.tween.from({ x: -640 }).to({ x: 0 })
      state.tween.time = 500
      state.tween.easing = new PIXI.tween.Easing.outCubic()
      state.tween.start()

      state.textStyle = new PIXI.TextStyle({
        fontFamily: 'Arial',
        fontSize: 36,
        fill: 'white',
      });
      state.message = new PIXI.Text('Good News Everyone!', state.textStyle)
      state.message.position.set(state.graphic.width - state.message.width - state.padding, 565)

      state.container.addChild(state.message)
      state.app.stage.addChild(state.container)
    }
  }

  gameLoop()
})
```

Note that I have to stub out several APIs, mostly for the sake of the `AccessibilityManager`. I have no idea what the impact of this is right now other than I assume the `AccessibilityManager` won't work at all. But this does perform the main function of doing all the work in a `WebWorker` and then drawing to the `canvas` on screen.

This is essentially the approach that is described in [this talk](https://www.youtube.com/watch?v=wkDd-x0EkFU) with respect to Three.js.

The `OffscreenCanvas` APIs are obviously pretty new and I've just started exploring PIXI.js so I'm not sure if ultimately this is a fruitful direction to go in or not but it seems promising.

**Comment by sanbornhilland** [comment]
I just accidentally discovered that I've been running a `CanvasRenderer` in the WebWorker because PIXI was not correctly recognizing that WebGL was available. I had to make this little change to get it to use a `WebGLRenderer`

```
self.window = {
  console: self.console,
  addEventListener() {},
  navigator: {},
  document: self.document,

  /*
   * This is necessary for PIXI.js to correctly detect that WebGL is present: 
   * https://github.com/pixijs/pixi.js/blob/f6f00047d6c523df2aa366cf3745eb831cec6ec5/src/core/utils/index.js#L314
   */
  WebGLRenderingContext: self.WebGL2RenderingContext || self.WebGL2RenderingContext,
}
```

**Comment by jdelrue** [comment]
We also want to use PixiJS to render our canvas offscreen so it can work in a webworker. Having a PixiJS instance running in a webworker leaves more thread time available for other controls such as our Vue.js interface. At this time, if PixiJS is very busy rendering Vue.js totally blocks or the other way around.

**Comment by bichotll** [comment]
Just for the record. This dull monkey patch worked for me.
I can say that I could not see much improvement tho if any...(running it in the same thread tho)

```
const canvasEl = window.canvasEl = new OffscreenCanvas(0, 0)

PIXI.interaction.InteractionManager.prototype.addEvents = () => {}

const pixiApp = new PIXI.Application(1920, 1080, {
  view: canvasEl,
});
```

**Comment by jdelrue** [comment]
Performance increase will only happen if you run in webworker..

**Comment by bichotll** [comment]
I presumed that. It was easy to give a try anyway.

**Comment by joel1st** [comment]
@sanbornhilland Did you have any luck getting textures to work inside a worker with pixi.js? I had a brief attempt at monkey patching image calls with ImageBitmap (which is worker friendly), but didn't have much success.

**Comment by sanbornhilland** [comment]
@joel1st I did this a little while ago so I don't remember all the issues I ran into but looking at the comment I kindly wrote to myself 😛 it looks like it fails because DOM elements are missing? I guess that's what you tried to monkey patch. I didn't try that, instead I just drew the images to a canvas myself and then created Textures from the canvases:

```javascript
/*
 * PIXI uses DOM elements to create Textures from images in v4 so we
 * need to do this kind of ugly work around to create a twitter logo
 * Texture.
 *
 * You probably don't need to Base 64 it actually. You could just fetch it from the 
 * network or have the bitmap transferred from the main thread. This is one of those 
 * solutions that I slowly arrived at so there are probably some unnecessary steps 
 * here.
 */
const getImg = async (base64Png) => {
  // This would be much nicer if we could just load a Texture from an ImageBitmap
  // This is supported in v5 apparently.
  const res = await fetch(base64Png)
  const blob = await res.blob()
  const bitmap = await createImageBitmap(blob)
  const c = new OffscreenCanvas(bitmap.width, bitmap.height)
  const ctx = c.getContext('2d', { alpha: true, antialias: true })
  ctx.drawImage(bitmap, 0, 0)

  return PIXI.Texture.fromCanvas(c)
}

const texture = await getImg(SOME_BASE_64_IMG)
```

It looks like v5 has a `fromBuffer` method that would allow you to skip all the canvas drawing stuff here which would be nice.

**Comment by eranimo** [comment]
Bump. This would be great to have!

**Comment by Lusya-make** [comment]
Hello, I am from China, I am a novice to this platform, but I want touse it to make foreign friends, can i make friends with you, do youplay QQ?

**Comment by Oikio** [comment]
Hello, has anyone succeeded? I've tried to use Pixi with OffscreenCanvas in worker, but it looks like Pixi (v5.1.2) relies on window and different HTMLElements too much. Code suggested by [sanbornhilland](https://github.com/pixijs/pixi.js/issues/4538#issuecomment-428267327) helps to start Pixi, with some minor adjustments. But I'm still failing to even create a Sprite in such context.
I don't have much knowledge of the code base, and would really appreciate if someone can reveal if it's possible to use Pixi in worker and how? If developers with better understanding of Pixi will say no, others like me can at least stop trying.

**Comment by eranimo** [comment]
Sprite probably doesn't work because it uses DOM APIs. OffscreenCanvas needs to be built-in to the library because Pixi needs to be able to split the parts that use the DOM from the rest of the graphics engine. Theoretically you could mock the DOM APIs used in the worker, but that feels really brittle.

**Comment by Oikio** [comment]
Thanks for the response, I've spent several hours mocking dependencies, but
it feels too overwhelming. In my case I can stick to main thread. Though
such feature can be very useful in future anyway.

**Comment by eranimo** [comment]
@Oikio Your best bet is to use the bare WebGL APIs yourself, which should work with offscreen canvas.

**Comment by sanbornhilland** [comment]
> Hello, has anyone succeeded? I've tried to use Pixi with OffscreenCanvas in worker, but it looks like Pixi (v5.1.2) relies on window and different HTMLElements too much. Code suggested by [sanbornhilland](https://github.com/pixijs/pixi.js/issues/4538#issuecomment-428267327) helps to start Pixi, with some minor adjustments. But I'm still failing to even create a Sprite in such context.
> I don't have much knowledge of the code base, and would really appreciate if someone can reveal if it's possible to use Pixi in worker and how? If developers with better understanding of Pixi will say no, others like me can at least stop trying.

It sounds like maybe you're fine with keeping PIXI on the main thread but for us it's not really an option so if you're curious, we are running v5 in a worker with `OffscreenCanvas` though it's definitely not officially supported. We are using a small subset of features as well so depending on your use case you may run up against a wall if you need more features.

Here's the minimal Pixi.js build we're using.

```js
import '@pixi/polyfill';
export * from '@pixi/constants';
export * from '@pixi/math';
export * from '@pixi/runner';
export * from '@pixi/settings';
export * from '@pixi/ticker';
import * as utils from '@pixi/utils';
export { utils };
export * from '@pixi/display';
export * from '@pixi/core';
export * from '@pixi/sprite';
export * from '@pixi/app';
export * from '@pixi/graphics';
export * from '@pixi/text';

// Renderer plugins
import { Renderer } from '@pixi/core';
import { BatchRenderer } from '@pixi/core';
Renderer.registerPlugin('batch', BatchRenderer);

// Application plugins
import { Application } from '@pixi/app';
import { TickerPlugin } from '@pixi/ticker';
Application.registerPlugin(TickerPlugin);
```

Polyfill
```js
DEBUG && console.debug('Installing PIXI.js worker polyfills')

invariant(!self.document, 'document is already defined globally. Did you import this file twice?')
self.document = {
  createElement(type) {
    if (type === 'canvas') {
      return new OffscreenCanvas(0, 0)
    }

    return {
      style: {},
    }
  },

  addEventListener() {},
}

invariant(!self.window, 'window is already defined globally. Did you import this file twice?')
self.window = {
  console: self.console,
  addEventListener() {},
  removeEventListener() {},
  navigator: {},
  document: self.document,

  /*
   * This is necessary for PIXI.js to correctly detect that WebGL is present:
   * https://github.com/pixijs/pixi.js/blob/f6f00047d6c523df2aa366cf3745eb831cec6ec5/src/core/utils/index.js#L314
   */
  WebGLRenderingContext: self.WebGL2RenderingContext || self.WebGLRenderingContext,

  // Required by react-spring hooks
  requestAnimationFrame: self.requestAnimationFrame.bind(self),
}

self.HTMLVideoElement = function HTMLVideoElement() {}

// https://github.com/pixijs/pixi.js/pull/5756
self.HTMLCanvasElement = self.OffscreenCanvas
```

Here's how you could create a `Sprite` from a `bitmap`

```js
const createSpriteFromBitmap = (bitmap, optWidth, optHeight) => {
  const width = optWidth || bitmap.width
  const height = optHeight || bitmap.height
  const canvas = new OffscreenCanvas(width, height)
  const context = canvas.getContext('2d', { alpha: true, antialias: true })
  context.drawImage(bitmap, 0, 0)

  return new Sprite(Texture.from(canvas))
}
```

**Comment by jdelrue** [comment]
We have a version, I can put it online tomorrow! Works in worker and offscreen.

**Comment by Oikio** [comment]
@sanbornhilland oh, that looks very promising for my case, I will try it out, thank you!
@jdelrue it would be great, the more information we have the better.

**Comment by jdelrue** [comment]
@Oikio Working example can found here https://github.com/jimbertools/pixiForWorker

**Comment by sanbornhilland** [comment]
Can we get this re-opened? I think there's a lot of value in officially supporting web workers, at least for a sub-set of Pixi functionality as the web trends toward offloading more and more work to workers.

**Comment by bigtimebuddy** [comment]
If this as desired a feature as this thread suggests, surely some hero out there would be willing to invest some time into supporting it in Pixi. Because OffscreenCanvas is [unsupported](https://caniuse.com/#feat=offscreencanvas) on a lot of browsers the core team is unlikely to devote effort to it right now. But if someone is willing to help, this seems like it might be high value for some devs working on bleeding edge content.

**Comment by DrSensor** [comment]
Is this already implemented?

**Comment by zszq** [comment]
> @sanbornhilland It would be even better if you could support all ‘events’, can you do it?

**Comment by sanbornhilland** [comment]
> > @sanbornhilland It would be even better if you could support all ‘events’, can you do it?

In our specific case we are using pixi.js purely for rendering so I haven't investigated what would be required to handle events.

**Comment by IhsenBen** [comment]
is this implemented?
this could be a great workaround to use Pixi with other libraries that already use a canvas

**Comment by SuperSodaSea** [comment]
> is this implemented? this could be a great workaround to use Pixi with other libraries that already use a canvas

@IhsenBen Yes, `OffscreenCanvas` is supported in PixiJS v7, here is an example: https://pixijs.io/examples/#/offscreen-canvas/basic.js
