### ISSUE TITLE
[Help Wanted] Clean up Documentation Globals

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#4539]
I would like to integration this new feature into our JSDoc template:
https://github.com/pixijs/pixi-jsdoc-template/pull/7

However, I noticed there are a handful of incorrectly documented things here:
http://pixijs.download/dev/docs/global.html

In PixiJS there should be no global documented items. These all should be removed by adding a `@private` flag, making sure it's represented as part of a class/namespace with `@memberof` or by making typedefs attached to a class e.g. `PIXI.Container~SomeDefinition`. The hardest thing would be to track down these items in the source code.

Anyone want to work up a PR for this?

**Comment by Pansaai** [comment]
Hello,
I tracked down the file in the source code. I set it to private, but couldn't help but wondering if this didn't make the whole GraphicsData class unsearchable in the docs ? Please do correct me if i am wrong.

```javascript
/**
* @member {number} the width of the line to draw
*/
this.lineWidth = lineWidth;
```
It is this comment line that is on the global.html page.

Thanks for your reply as this is the first issue i looked into .

**Comment by bigtimebuddy** [comment]
Format should look like this, this is incorrectly documented. It shouldn't be private.
```js
/**
 * the width of the line to draw
 * @member {number} 
 */
```

**Comment by bigtimebuddy** [comment]
And thank you @Pansaai for looking into this!

**Comment by Pansaai** [comment]
@bigtimebuddy My pleasure. Thanks for the feedback. I will make the changes to correct the formatting.

**Comment by bigtimebuddy** [comment]
Merged!
