### ISSUE TITLE
[Suggestion] About PIXI.math in v5

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4540]
I hope in v5 , the PIXI.math could support more feature , e.g.  Vector2D,  Vector3D, Matrix4.

even you could create a new standalone project PIXI.Math.

Because in a game app , they are useful  ,  but pixi miss them , users have to include another math-lib ,like gl-matrix. 
If PIXI could support them , it will be more valuable .

----
OR   PIXI.js v5 uses gl-matrix directly.

**Comment by ivanpopelyshev** [comment]
Lets add box2d too.

**Comment by finscn** [comment]
@ivanpopelyshev  ,  I know you are kidding . 

But I'm serious. The `Math lib` is different from `Physics engine`.

Math is a basic component , it's useful for many things in PIXI. 

An example , if somebody want to implement a plugin about 3D , he/she will need Vector3D  & Matrix4 .

**Comment by ivanpopelyshev** [comment]
Like always, its only partially a joke :( Box2d has different math lib inside. And flash has different math lib inside. All math libs are actually different.  

We can use `gl-matrix` for 3d plugin that @GoodBoyDigital want to make for v5, but there's no suitable tasks for it in plain v5. For PIXI Matrix and Point we need improvements in different direction, copyFrom/copyTo and may be add Float64Array into Matrix. 

`gl-matrix` uses Float32Array which is not enough for our 2d cases.

**Comment by finscn** [comment]
@ivanpopelyshev  , OK , I got your point.
 But I still think `Vector3D/Point3D` & `Matrix4`  are useful.
