### ISSUE TITLE
Badly font height measurement

### ISSUE THREAD

**Issue by eXponenta** [pixijs/pixi.js#4541]
Text cropped at the top on tall fonts, same as https://fonts.google.com/specimen/Amatic+SC

![6e7db646-5231-400f-a355-7875cce661de](https://user-images.githubusercontent.com/12572222/34071773-55dbcc78-e2ae-11e7-891a-5aeb5b90bfbc.jpg)

**Comment by bigtimebuddy** [comment]
Duplicate/related issues #4500 #4228 #1527

Workaround is to add padding to Text style.
