### ISSUE TITLE
PIXI texture from image load not work when image is loaded

### ISSUE THREAD

**Issue by TommyDong1998** [pixijs/pixi.js#4543]
PIXI.Texture.fromImage do not use scaleSource if you loaded the image with loader.
It should not load from cache.

**Comment by bigtimebuddy** [comment]
Could you please provide an example? A jsfiddle or codepin are recommended.

**Comment by TommyDong1998** [comment]
This is how it looks
https://jsfiddle.net/5x6c3h4s/6/
but it shouldn't be blurry because its svg

**Comment by bigtimebuddy** [comment]
You unfortunately cannot provide `sourceScale` when loaded through the Loader. This works though:

```js
var app = new PIXI.Application();
document.body.appendChild(app.view);
var url = "https://cdn.shopify.com/s/files/1/0496/1029/files/Freesample.svg?5153";
var text = new PIXI.Texture.fromImage(url, undefined, undefined, 3);
var sprite = new PIXI.Sprite(text);
app.stage.addChild(sprite);
```

**Comment by TommyDong1998** [comment]
Yeah but one time because of the cache
https://jsfiddle.net/5x6c3h4s/9/
If i was to resize it and made a new texture it won't work

**Comment by bigtimebuddy** [comment]
Try this: https://jsfiddle.net/bigtimebuddy/utxs3rj6/

**Comment by TommyDong1998** [comment]
If I was to make two items. How would I resize one of them.
https://jsfiddle.net/utxs3rj6/1/

**Comment by bigtimebuddy** [comment]
The `sourceScale` is used as the scale to rasterize the SVG. You should rasterize at the largest size you need in the BaseTexture and then scale down from there using the Sprite `scale` property.

https://jsfiddle.net/bigtimebuddy/pjd67cxu/

**Comment by themoonrat** [comment]
Closing as suggestion above should be used :)
