### ISSUE TITLE
TextMetrics.wordWrap() ignores TextStyle.letterSpacing

### ISSUE THREAD

**Issue by brenwell** [pixijs/pixi.js#4544]
Hey everyone, I found an issue with `TextMetrics.wordWrap`, which also effects `TextMetrics.measureText` & `TextMetrics.measureFont`. The wordwrap function does not account for letterSpacing values larger than 0.

**jsfiddle**

https://jsfiddle.net/brenwell/59660ayb/

I will make a pull request with the fix

**Comment by brenwell** [comment]
I found that my pull request has improved the calculation but not completely fixed it. I am working on a slightly improved version. 

Also want to confirm that this is a bug that needs fixing and not an issue with how I was using TextMetrics??

**Comment by HansKaufmann** [comment]
+1

**Comment by Esshahn** [comment]
+1

**Comment by brenwell** [comment]
I have also noticed that the dropshadow is not factored into the calculation of TextMetrics. Am I correct in assuming that this is intentional?

**Comment by brenwell** [comment]
I have updated my pull request. It’s calculation is more accurate now. 

Would be great if I can get some feedback.

**Comment by brenwell** [comment]
Link with changes https://jsfiddle.net/brenwell/59660ayb/1/

**Comment by themoonrat** [comment]
Closing as I think you're PR fixed this if I remember correctly :)
