### ISSUE TITLE
The grapics class is potential buddy

### ISSUE THREAD

**Issue by johnnymast** [pixijs/pixi.js#4546]
The Graphics class sets the shape type by if it sets a linestyle or not.. If you set the linestyle it will be a poly if you have a setLineStyle in your code by mistake it will break the Graphics class. You could also set a line style for a rect but then its type of poly already.

**Comment by ivanpopelyshev** [comment]
Papers^W Fiddle, please :)

**Comment by bigtimebuddy** [comment]
We need more info, like Ivan said a jsfiddle or codepen is the best way to show, validate and fix something.

**Comment by johnnymast** [comment]
Alright, i will get to it when i leave my job for home.

**Comment by themoonrat** [comment]
Gonna close due to inactivity, but if you still have the issue and get back to us feel free to re-open :)
