### ISSUE TITLE
Is Mesh.plane example wrong?

### ISSUE THREAD

**Issue by ByronHsu** [pixijs/pixi.js#4551]
http://pixijs.download/release/docs/PIXI.mesh.Plane.html

In the constructor, the docs defines construct method like this, and verticesX Y are both number type.
new PIXI.mesh.Plane(texture, verticesX, verticesY)

But in the example above, it passes PIXI.Point into the constructor and there is only one arg, is there something wrong?
```

for (let i = 0; i < 20; i++) {
    points.push(new PIXI.Point(i * 50, 0));
};

let Plane = new PIXI.Plane(PIXI.Texture.fromImage("snake.png"), points);
```

**Comment by themoonrat** [comment]
It's because it does
```
        this.verticesX = verticesX || 10;
        this.verticesY = verticesY || 10;
```
really, the default of 10 should be put in the constructor params, and the docs updated to reflect this!
