### ISSUE TITLE
How to copy Webgl content to another canvas element without create new Pixi.application

### ISSUE THREAD

**Issue by VCtaiwan** [pixijs/pixi.js#4552]
Hi all,

How to do the result like pure html canvas for redraw canvasA's content to canvasB.

Here is the result i wished:
```
var canvasA = document.getElementById("canvasA");
var ctxA = canvasA.getContext("2d");
//ctxA drawsomthing......
...
...

var canvasB = document.getElementById("canvasB");
var ctxB = canvasB.getContext("2d");

ctxB.drawImage(canvasA, 0, 0, canvasB.width, canvasB.height);

```
**How to do it in Pixi.jsV4**
By the way, my renderer is **'Webgl context'**

Thanks a lot!

**Comment by ivanpopelyshev** [comment]
Are you sure that you need PIXI for that? 

1. Application class is mashup, you need only WebGLRenderer.

2. All related code is here: https://github.com/pixijs/pixi.js/tree/dev/src/extract , you can copy basic webgl operations and do it without pixi.

**Comment by VCtaiwan** [comment]
Thanks for reply.

But sorry, i still not understand. Is there any demo?

My canvasA was a pixi.application which is webglContext, i wish to sync drawing to canvasB
I make it by declare two same variable and add to different stage, **every strip is same container.**

```
var appA = new PIXI.Application(100, 100, {
   view: document.getElementById('canvasA')
});
var appB = new PIXI.Application(100, 100, {
   view: document.getElementById('canvasB')
});

var imgSrc = PIXI.Texture.fromImage('http://.....');
var strip1: new PIXI.mesh.Rope(imgSrc, points),
var strip2: new PIXI.mesh.Rope(imgSrc, points),

var con1 = new PIXI.Container();
var con2 = new PIXI.Container();

con1.addChild(strip1);
con2.addChild(strip2);

appA.stage.addChild(con1);
appB.stage.addChild(con2);
```
This work for me, But i think this is stupid way.
Is there any other way to succeed?

**Comment by ivanpopelyshev** [comment]
Application is a mashup: https://github.com/pixijs/pixi.js/blob/dev/src/core/Application.js , it has Renderer, ticker and stage inside.

Juts make two renderers instead of one and render the same stage.

```
var renderer1 = new WebGLRenderer(100, 100, { view : ... } );
var renderer2 = new WebGLRenderer(100, 100, { view : ... } );

function RAF() {
    renderer1.render(stage);
    renderer2.render(stage);
    requestAnimationFrame(RAF);
}

requestAnimationFrame(RAF);
```

You can customize some params, like transform applied to stage, if you look at [render documentation](http://pixijs.download/dev/docs/PIXI.WebGLRenderer.html)

**Comment by ivanpopelyshev** [comment]
Dissecting the application and making separate gameloop, handling stage and renderer  is the first thing to do if your case is not a "hello world".

We had examples with a separate renderer and stage before, but now all examples are using `Application` just to make it easier. Unfortunately, people dont like to look inside sources, I dont know what to do about that.

**Comment by VCtaiwan** [comment]
Really helpful, thanks
