### ISSUE TITLE
TypeError: "cwd" must be a string

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [pixijs/pixi.js#4554]
when run: npm start (parallelshell npm run *) will popup errors :
`child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at exports.spawn (child_process.js:487:38)
    at /Users/tusm/Desktop/front/github/pixi.js/node_modules/.2.0.0@parallelshell/index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/tusm/Desktop/front/github/pixi.js/node_modules/.2.0.0@parallelshell/index.js:100:6)
`

**Comment by bigtimebuddy** [comment]
Need more information. Could you please provide NodeJS and Operating System versions?

**Comment by brenwell** [comment]
I saw this issue when building with the latest node. Rolled back to v6 and all good. 

What is the supported version?

**Comment by bigtimebuddy** [comment]
I’ve been using v6. I’ll check to see if there’s a parallelshell big with the latest Node.

**Comment by bigtimebuddy** [comment]
Looks like there’s a new major version. Related: https://github.com/darkguy2008/parallelshell/issues/57

**Comment by themoonrat** [comment]
@bigtimebuddy know if this is working again on newer node versions? I'd assume so since we're no heard anything else?

**Comment by BillShiyaoZhang** [comment]
I solve it by update the version comparison from `'8.0.0'` to `8` at `node_modules\parallelshell\index.js:104:17`

> var child = spawn(sh,[shFlag,cmd], {
        cwd: process.versions.node < 8 ? process.cwd : process.cwd(),
        env: process.env,
        stdio: ['pipe', process.stdout, process.stderr]
    })
