### ISSUE TITLE
This is not an issue but a compliment

### ISSUE THREAD

**Issue by johnnymast** [pixijs/pixi.js#4555]
Hey guys!,

I wanted to let you know, pro game developer here! I want to let you know i make html5 games for a living. I know my canvas but i'm step by step recreating the PIXI engine just to train my self in private to get more effective. This should be a compliment to the devs here .. My engine half in size is here https://github.com/prophecyjs/Engine .. 

Thanks guys  !! 

PS: I already deprecated Graphics.lineAlpha because i have a dedicated color class based on rgba  .. See https://github.com/prophecyjs/Engine/blob/master/src/core/color/Color.js

**Comment by bigtimebuddy** [comment]
Good luck @johnnymast! And if you find anything while going through the PixiJS source to share, please consider making contributions back as we prepare for v5 (**next** branch)!

**Comment by johnnymast** [comment]
well considering i'm recreating the engine to advance my knollage i see a load of redundant calculations and calls. I will report on this soon .. its like what i said before i made my color class hold the alpha RGBA (right) so its not needed for the graphics class to hold its own alpha i'm aiming to use this color class on more places as well to save kb's in the compiled result. An other redundant calculation could the Container rect bounds .. In the most usecases is almost never used .. so i didn't implement it (YET)  Okey i don't implement WebGL yet but i guess thats not much of a change.

**Comment by ivanpopelyshev** [comment]
Color class? Look at this one: https://github.com/gameofbombs/pixi-heaven/blob/master/src/twotint/ColorTransform.ts

**Comment by johnnymast** [comment]
@ivanpopelyshev that is so sexy :)
