### ISSUE TITLE
Diagonal lines when rendering in headless chrome 

### ISSUE THREAD

**Issue by jhollingworth** [pixijs/pixi.js#4557]
Hey! We've created a simple animation which contains a number of animated sprites. We're then rendering this in a headless chrome browser with swiftshader enabled and then exporting each frame with `renderer.view.toDataUrl('image/jpeg')`.

We've noticed diagonal lines appearing in the exported images which we don't see when rendering in a normal browser. Have anyone seen this before? Any suggestions how to fix it?

![screen shot 2017-12-21 at 22 45 49](https://user-images.githubusercontent.com/151172/34278216-642c8280-e6a1-11e7-9c99-5e2bea9525f0.png)

**Comment by VCtaiwan** [comment]
Check the chrome browser's scale is reset to 100% or not
![image](https://user-images.githubusercontent.com/21326779/34332454-b97e31ee-e96b-11e7-8e94-e7c701b43831.png)

**Comment by jhollingworth** [comment]
I realized Pixi was downgrading to canvas which was causing this. Closing

**Comment by ivanpopelyshev** [comment]
Downgrading shouldn't affect it unles you have Mesh somewhere
