### ISSUE TITLE
Pixi can't run correctly on Huawei Android Phone

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4563]
Huawei (the third largest phone producer in the world)  released some new android phones. But the pixi can't run on them.  
the browser has updated to Chrome 63.xxxx (last version)

I test them with  webglreport.com , the result shows they support WebGL & some main glExtensions(that PIXI used)

Huawei doesn't use Qualcomm Chip ,  It uses the chip developed by itself .

The game created by unity/cocos/unreal can run very well on Huawei's phone. 
So I think the OpenGL ES has been supported Huawei's phone very well.

But I don't know why PIXI can't.

I don't buy these phones , I test them in the store, So I can't do debug to find out the error.

**Comment by GoodBoyDigital** [comment]
Hey @finscn, thanks for sharing! Might buy the a device to test on. Which one do you think we should get to test? 

Thinking this one:

https://www.amazon.co.uk/Huawei-Lite-2017-SIM-Free-Smartphone-Black/dp/B0725CGWQD/ref=sr_1_3?s=telephone&ie=UTF8&qid=1514973420&sr=1-3&refinements=p_89%3AHuawei

Cheers!

**Comment by themoonrat** [comment]
@GoodBoyDigital If he's referring to 'the latest' Huawei phones; then they run with their own chipset: "Hisilicon Kirin", which is currently the Huawei Mate 10 / Huawei Mate 10 Pro use the latest version of, the 970. The other recent phones is a cut down version of that, the Huawei Mate 10 Lite, using an older chipset, the 659.

**Comment by finscn** [comment]
they are with different names  in different country.
in China  ,    Huawei Mate 10  ,  nova2s  ,  Honor V10 are last phone.

nova2s uses  Kirin 960,
Huawei Mate 10 & Honor V10 use Kirin 970.

When we talk phone (just phone, not about webgl opengl pixi),  I like ` Honor V10`.

For test webgl, the `nova2s` is better , because it supports the least WebGL feature.

**Comment by rich-earth** [comment]
I had problems with Samsung Galaxy tabs and recent Chrome versions, changing some PIXI settings did the trick,  I think it was
PIXI.settings.CAN_UPLOAD_SAME_BUFFER = false,  and passing {preserveDrawingBuffer:true} into the renderer options.

**Comment by wwepenguin** [comment]
i run pixi in Huawei P7 Webview has Flickering problem , and i set preserveDrawingBuffer:true can fix Flickering problem

But set preserveDrawingBuffer:true  will cause some low fps device flickering  at pixi version heigher than 4.5.0,
in pixi 4.4.4 set  preserveDrawingBuffer:true those low fps device work fine , not flickering  
is any change at 4.5.0 will cause flickering  ?

**Comment by themoonrat** [comment]
I've personally not had any issues with Huawei phones with PIXI, tho only had them in test relatively recently on recent Chrome versions. 
Will close for now due to inactivity, but feel free to re-open if it's still an issue!
