### ISSUE TITLE
container with hitarea and mask issue

### ISSUE THREAD

**Issue by suconghou** [pixijs/pixi.js#4564]
container with mask and hitarea , but the hitarea is still working outside the mask , it is strange . so 
I wtite some code here http://jsfiddle.net/suconghou/ckrtbsn6/6/   and  ask help in https://gitter.im/pixijs/pixi.js  ,  someone tried and modify code here http://jsfiddle.net/ckrtbsn6/5/ 
and it is still not working . 

is it a bug ? how can I make these work 

relative:  https://stackoverflow.com/questions/47980765/pixi-container-hitarea-with-mask

**Comment by themoonrat** [comment]
@suconghou - there is a bug in regards to PIXI where children who are outside of the hitArea are still allowed to be interactive with. There is a fix for that: https://github.com/pixijs/pixi.js/pull/4608

However, if you use a **filled in** mask, then that will act as a restricted hit area too.
Here is an updated fiddle, using the latest version of PIXI (no fix applied), using just a filled in mask to achieve close to what I believe you require: http://jsfiddle.net/themoonrat/ckrtbsn6/8/

**Comment by suconghou** [comment]
@themoonrat thank you , I will have a try .
