### ISSUE TITLE
PIXI.Container don't have method containsPoint cause event cannot be triggered at Container

### ISSUE THREAD

**Issue by k8w** [pixijs/pixi.js#4567]
```js
let app = new PIXI.Application(800, 600);
document.body.appendChild(app.view);
app.stage.interactive = true;
app.stage.on('click', () => {
    console.log('CLICKED');
})
```

**Expect**
Click on stage would trigger click event.

**Actual**
Nothing triggered

Found out the reason is `PIXI.Container` doesn't have method `containsPoint`, and it lead to hitTest is skiped.

**Comment by ivanpopelyshev** [comment]
Not a bug. Either add click event to interaction manager (renderer.plugins.interaction) directly, either use background element:

```js
var back = new PIXI.Container();
back.hitArea = app.screen;
app.stage.addChild(back);
back.interactive = true;
back.on('click', () => {... });
```

**Comment by k8w** [comment]
@ivanpopelyshev Not only stage, normal Container cannot trigger event by itself.

```js
let containter = new PIXI.Container();
container.addChild(...);
container.on('click', ()=>{
  //... NOT TRIGGERED TOO
})
```

And add event directly to interaction manager seems not work too..
```
app.renderer.plugins.interaction.on('click', () => {
    console.log('RClick')
})
```

**Comment by k8w** [comment]
Shouldn't `Container`'s `hitArea` be their `localBounds` by default?

**Comment by ivanpopelyshev** [comment]
According to current InteractionManager code, hitArea is supposed to be used on single elements that do not have interactive children. Also, localBounds are based on children position, that makes cvery strange effects - add one invisible element somewhere in top-left and one in bottom-right and you'll have whole screen covered.

You can make your own implementation of InteractionManager that will work like you want. 

Here's how to patch it: https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#interaction

The method you need is processInteractive: https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js

I'm both hands for alternative interaction plugin!

**Comment by k8w** [comment]
> Shouldn't Container's hitArea be their localBounds by default?
Maybe I mean bounds based on its visible children.

> that makes cvery strange effects - add one invisible element somewhere in top-left and one in bottom-right and you'll have whole screen covered.
If this two element are visible, I think this is very normal.

Just like it is in HTML/CSS, every element is actually a box.
Pointer events are based on it content box, if I don't want event be triggered at empty area, I should addEventListener on its children rather than container itself.

**Comment by ivanpopelyshev** [comment]
Then it'll be a DOM and not 2d renderer stage. Pixi is based on Flash :)

**Comment by ivanpopelyshev** [comment]
By the way, about box - if you try to use `width` and `height` on containers, they also work Flash way, so prepare to study docs and sources about it. 

It would be good if someone implements containers for for web-devs based on their DOM experience, you should go for it :) Basic pixi container: https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js
