### ISSUE TITLE
Manually set container children indexes

### ISSUE THREAD

**Issue by rusomirt** [pixijs/pixi.js#4568]
I have a tiled image: container holds several sprites.
When sprites are loaded with Pixi loader, they came in random order (so random indexes are assigned).
But I need to keep their indexes ordered in container for subsequent processing.

For example, if image size is 3 tiles in width and 2 tiles in height, indexes should be: 
top-left corner - 0,  top-middle - 1, top-right corner - 2,
bottom-left corner - 3, bottom-middle - 4, bottom-right corner - 5.

Is there any way to manually set container children indexes?
`AddChildAt()` and `setChildIndex()` return error 'index is out of bounds'.

**Comment by ivanpopelyshev** [comment]
> When sprites are loaded with Pixi loader, they came in random order (so random indexes are assigned).

Please provide more details. When loader completes loading it fires "oncomplete" event, then you can process all resources. They do have names, how can it be random?

Make a fiddle, if its possible.

**Comment by ivanpopelyshev** [comment]
`index out of bounds` - you should add them first, you cant just assign an index like in js array, imagine that you take `java.util.List` or `std::vector` and put things in random indices, it will fail too. 

Pixi is one of Flash successors, you cant do that kind of thing in ActionScript too. If you want to explore all the details, please read the source code for Container: https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js

**Comment by rusomirt** [comment]
"Oncomplete" event helped, thanks!
