### ISSUE TITLE
Demos in README.md contain broken links

### ISSUE THREAD

**Issue by aaronang** [pixijs/pixi.js#4571]
The following demos are broken:
- Run pixie run
- Fight for Everyone
- Bunny Demo
- Storm Brewing
- Filters Demo
- Render Texture Demo
- Primitives Demo
- Masking Demo
- Interaction Demo

**Comment by bigtimebuddy** [comment]
Looks like @GoodBoyDigital and co have created a new website and all these things were blown away. We are looking to see if we can restore these. Thanks for pointing them out!
