### ISSUE TITLE
How to find this pixi.js docs Source code

### ISSUE THREAD

**Issue by yyman001** [pixijs/pixi.js#4576]
HI!
How to find this pixi.js docs Source code.I learn pixi.js ,want to Translation documents，but can no find this docs Source code, has download? Thanks~

**Comment by englercj** [comment]
The docs are generated from the source code.

For example [this comment](https://github.com/pixijs/pixi.js/blob/cba512d042b0f4ed4d6ec6c67fc3d6e4725d0635/src/core/display/Container.js#L4-L16) generates parts of [this page](http://pixijs.download/dev/docs/PIXI.Container.html). We use [jsdoc](http://usejsdoc.org/) to parse the comments and output the html documentation.
