### ISSUE TITLE
Impact of browser changes as a result of Meltdown and Spectre Security Risk

### ISSUE THREAD

**Issue by fanjules** [pixijs/pixi.js#4581]
Not sure if anybody is aware but a dramatic vulnerability in the worlds Intel processors has resulted in an unfortunate knock-on effect for Javascript.  The performance.now() function will be nerfed, and SharedArrayBuffer will be removed.  Hopefully these effects will be temporary until things become more clear.  On Chrome the exact change to performance.now() has not yet been published, on Firefox they are adding in a random modifier of 20 microseconds which seems reasonable, though some may be impacted.    The loss of SharedArrayBuffer I am uncertain of it's impact and I don't know if other browsers will be going further.  The CPU vulnerability is a breaking news story within the last 24hrs.

Will the Pixi.js library continue to function as normal?  Obviously we cannot pass SharedArrayBuffer objects to it anymore.

**Comment by ivanpopelyshev** [comment]
Fortunately, we dont use SharedArrayBuffer. I know its critical for apps that use webworker for heavy tasks. Pixi performs well in single-threaded environment.

**Comment by ivanpopelyshev** [comment]
Also I really dont like new solutions like webasm, so you can be sure that someone blocks that modern stuff  from pixi ;)

**Comment by fanjules** [comment]
This is good to know, thanks for the swift response. :)

And yes, though I'm always looking for more performance, reliability comes first.

I picked Transferable Objects over SharedArrayBuffer for this reason in my nav codes Astar web workers... if anybody is coming to this topic via a Google Search regarding SharedArrayBuffer, I guess that's your only option until/if it's reinstated.

**Comment by ivanpopelyshev** [comment]
btw, your previous pixi issue was fixed in november (i found workaround for v4, and its fixed in v5)

**Comment by fanjules** [comment]
Excellent support! :)
