### ISSUE TITLE
Blend Modes issue OR add new mode

### ISSUE THREAD

**Issue by ganzimaro** [pixijs/pixi.js#4582]
Good day to everyone. I ask forgiveness if this topic has already been raised. Currently PIXI supports as 'Normal', 'Additive', 'Multiply', 'Screen', 'Overlay' and 'Hard Light' blend modes. The question, is there an opportunity to add other blend modes, especially interested in 'Soft Ligth'. Or at least a clue where to find information on this topic.

**Comment by ivanpopelyshev** [comment]
You can add soft light in https://github.com/pixijs/pixi-picture . Overlay and hard-light are emulated, they use extra framebuffer and texture to copy background, that's slower than ADD or MULTIPLY. You need formulas for `Soft Light` and others, but i forgot where did i take them from.

**Comment by ganzimaro** [comment]
Got it. So, I'll go to look for formulas. If there will questions on integration, and they will, then I will write off on this topic.

**Comment by ivanpopelyshev** [comment]
http://www.html5gamedevs.com/topic/34859-does-pixijs-support-background-blending-shaders/

**Comment by ganzimaro** [comment]
Does this look like what is required?
https://github.com/mattdesl/glsl-blend-soft-light

**Comment by ivanpopelyshev** [comment]
Dont forget to divide rgb by alpha like i did in overlay implementation. Pixi uses premultiplied (Ra,Ga,Ba,a) everywhere.

**Comment by ganzimaro** [comment]
After a long study, that's what I got.
[pixi-picture.zip](https://github.com/pixijs/pixi.js/files/1609631/pixi-picture.zip)

However, there was a problem with checking it, because even the already available functions "overlay" and "hard_light" can not be started. Using "PIXI.Sprite" and "PIXI.extras.PictureSprite" result did not. I enclose the file in which the images are processed, the items "Ground" and "Light". I hope for a hint about the error I made.

**Comment by ivanpopelyshev** [comment]
Good, that's something i can work with.

**Comment by ivanpopelyshev** [comment]
Actually, you gave me compiled file, what do I have to do with it?

**Comment by ivanpopelyshev** [comment]
give me complete example in a zip file and ill fix it.

**Comment by ganzimaro** [comment]
I understand and apologize for the inaccuracies.
Here is a link to a mini example of the game "[GAME](https://github.com/ganzimaro/HwTF/blob/master/Test.zip?raw=true)". In the "SAMPLE" folder I put the code in a readable version and two images with what is and what should be.

**Comment by ivanpopelyshev** [comment]
Ah, its RMMV :) Yeah, its making things easier.

**Comment by ivanpopelyshev** [comment]
You've specified different blendmode in rmmv editor for a Picture, right?

**Comment by ganzimaro** [comment]
Yes, "OVERLAY" and "HARD_LIGHT" work great, I had problems with their connection, but I decided them. The only thing left is "SOFT_LIGHT", or more accurately it does not match Photoshop, apparently there is an error in the formula. Can you help, or prompt me where I could be wrong?

**Comment by ivanpopelyshev** [comment]
I didnt have time to look at it yet, I'm very busy :) I remember about your problem.

**Comment by ganzimaro** [comment]
I understand, you can not rush, this is not the last thing i need to do for the game. I am grateful that you are devote your time)
