### ISSUE TITLE
what and how we can prevent new update of pixi.js ? 5.0

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4584]
hi guys||girls,  i read you a lot work on PIXI 5.0.
I develop an alpha project based on pixi thecnologie, I would like to be able to anticipate some behavior of the next update.
Do you have a follow-up link on the changes made or a possible release date?
i dont know a lot the labyrinth github are, but I may miss the place to look!?

I would like to avoid breaking my codes, especially if the v5 is better than the 4, and would make a update.
I speak of it because I have read in many places that you work on it.
thank.

**Comment by ivanpopelyshev** [comment]
If you use npm, specify that you only need same major version. v5 will break many things, including RMMV

**Comment by djmisterjon** [comment]
i use the rmmv core base for software, but all my code and project are based on pixi only.
I use almost nothing rmmv, thats ask me if I should not rather switch to Unity and study the C#.!?

This is a reason why I would like to follow future changes because I would like to be able to avoid rewrite all my codes. Especially if pixi 5.0 has something essential update for me.

**Comment by GoodBoyDigital** [comment]
Hey @djmisterjon v5 API will be almost 100% the same as current version. We will make sure to deprecate any changes too. 

What may be affected is any code that uses pixi but not its top level api, such as rmmv.

hope that helps!

**Comment by allanbreyes** [comment]
> ... v5 API will be almost 100% the same as current version.

@GoodBoyDigital: Thank you *so* much for this. It's not something you had to do, esp. with a major version bump, but the fact that you're striving for it overwhelmingly shows how much the pixi.js team cares about the project and its users.

Thank you.

**Comment by GoodBoyDigital** [comment]
Thanks for the kind words @allanbreyes ! I honestly believe the API is one of pixi's greatest strengths :)
We would only really consider changing it if had some really compelling reasons!
