### ISSUE TITLE
Transparent PNGs + WebGL + Headless Chrome

### ISSUE THREAD

**Issue by jhollingworth** [pixijs/pixi.js#4587]
I'm having some problems with rendering transparent PNGs when in headless chrome with WebGLRenderer. Using the [overlay blendMode example](http://pixijs.io/examples/#/picture/overlay.js) I can render everything perfectly in Chrome (v63):

![chrome](https://user-images.githubusercontent.com/151172/34639897-9fe0d60a-f2e0-11e7-9982-3e4a7e5e8d66.png)

However when I render in Headless Chrome on a server with no GPU (Chrome uses [Swiftshader](https://github.com/google/swiftshader/) in this case) any transparent bits of the image are used over the underlying image. 

![swiftshader](https://user-images.githubusercontent.com/151172/34639894-9d3eb624-f2e0-11e7-8d89-1763eb927913.png)

The options passed into `getContext('webgl')` are 

```
{
	"alpha": true,
	"antialias":false,
	"premultipliedAlpha":false,
	"stencil":true,
	"preserveDrawingBuffer":true
}
```

Setting `alpha` to false just makes transparent regions black. Setting `premultipliedAlpha` to true makes the whole screen transparent (nothing rendered).

I'm guessing this is a bit of an edge case but wondered if anyone had any suggestions what the problem could be?

**Comment by ivanpopelyshev** [comment]
```
new WebGLRenderer(800, 600, {transparent:false}); //try that thing
```

**Comment by jhollingworth** [comment]
With 

```
var renderer = new PIXI.WebGLRenderer({
  width: app.screen.width,
  height: app.screen.width,
  transparent: false,
});
```

The background goes from transparent to black 😢 

![image](https://user-images.githubusercontent.com/151172/34640182-ca444454-f2e5-11e7-95b2-fe747dac7182.png)

**Comment by ivanpopelyshev** [comment]
ok, so overlay doesnt work, something wrong with copyTexImage2D. That blendmode is emulated through `pixi-picture` plugin.

**Comment by jhollingworth** [comment]
Firstly, thank you for your help with this. I really appreciate it! 

My code is now using the pixi-pixture plugin ([Code is identical to example](http://pixijs.io/examples/#/picture/overlay.js)). It seems the overlay plugin is working however I'm still seeing black where the image is transparent.

![image](https://user-images.githubusercontent.com/151172/34641999-3926ce0a-f304-11e7-9eb9-f45b883a8f81.png)

I've been looking at chrome's GPU logs and found a couple of occurrences of `GL_INVALID_OPERATION` on `glCopyTexSubImage2D`:

```
[.Offscreen-For-WebGL-0x3e74ea9cf020]cmd: kCopyTexSubImage2D
[.Offscreen-For-WebGL-0x3e74ea9cf020]GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format
```

```
glDrawElements(GL_GEOMETRY_SHADER_BIT_OES, 6, GL_UNSIGNED_SHORT, (nil))
[.Offscreen-For-WebGL-0x3e74ea9cf020]GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format", source: http://localhost:3000/template?export=true&template=pixi-alpha&renderID=1515258599267-e89e (0)
[.Offscreen-For-WebGL-0x3e74ea9cf020]GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format", source: http://localhost:3000/template?export=true&template=pixi-alpha&renderID=1515258599267-e89e (0)
[.Offscreen-For-WebGL-0x3e74ea9cf020]GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format", source: http://localhost:3000/template?export=true&template=pixi-alpha&renderID=1515258599267-e89e (0)
[.Offscreen-For-WebGL-0x3e74ea9cf020]GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format", source: http://localhost:3000/template?export=true&template=pixi-alpha&renderID=1515258599267-e89e (0)
[.Offscreen-For-WebGL-0x3e74ea9cf020]GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format", source: http://localhost:3000/template?export=true&template=pixi-alpha&renderID=1515258599267-e89e (0)
```

If I remove these two lines then no errors are reported (I double checked, it's [using `readPixels` instead of `copyTexSubImage2D`](https://github.com/pixijs/pixi-picture/blob/master/src/PictureRenderer.ts#L143-L146)) but the problem persists.

```
app.stage.filters = [new PIXI.filters.AlphaFilter()];
app.stage.filterArea = app.screen;
```

Have you got any other thoughts on things I could try?

**Comment by ivanpopelyshev** [comment]
Are you sure that you need overlay blendmode in webgl environment? :)

**Comment by ivanpopelyshev** [comment]
I think its unpack premultiplied alpha doesnt work properly. Pixi manupulates (Ra,Ga,Ba,a) and not (R,G,B,a), and when the texture is uploaded its supposed to be multiplied by alpha.

**Comment by jhollingworth** [comment]
Oh interesting, are you suggesting the underlying OpenGL implementation is incorrect? Or there is there some change I could make to the Pixi code (e.g. in a shader or something)? 

I've created a [simpler test case](https://gist.github.com/jhollingworth/ae9361a260238166b32e365980b02244) that demonstrates the issue ([Chrome GPU logs of render](https://gist.github.com/jhollingworth/46a7804e21439816535773581fa6c1fb)). I then played with [`gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL`](https://github.com/pixijs/pixi-gl-core/blob/30c2db8b20be0bc6e64807cf53d982b39bc5adfd/src/GLTexture.js#L87) but didn't change much.

**gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, true)**

<img width="300" height="300" src="https://user-images.githubusercontent.com/151172/34643198-03b584f0-f318-11e7-807a-11000b2b1362.png"/>

**gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, false)**

<img width="300" height="300" src="https://user-images.githubusercontent.com/151172/34643187-de1a8826-f317-11e7-8c7e-d2bd2cc98895.png"/>

**Expected result**

<img width="300" height="300" src="https://user-images.githubusercontent.com/151172/34643162-66289d1c-f317-11e7-9118-22f4a521862f.png"/>

_Rendered on Chrome_

**Comment by ivanpopelyshev** [comment]
I think PNG decoder is wrong here.

**Comment by jhollingworth** [comment]
I've finally figured out the issue, it's unrelated to Pixi so closing this issue.

For anyone who comes across this thread with the same issue, the issue was using Chrome in headless mode with Swiftshader. If you run Chrome with XVFB instead everything works as expected. You can find more info here: https://github.com/jhollingworth/swiftshader-transparent-image.

Thanks again for your all help with this
