### ISSUE TITLE
When resize the screen, how to preserve the original size of all sprites? Or how to avoid distortion and deformation?

### ISSUE THREAD

**Issue by qtttttttttting** [pixijs/pixi.js#4597]
When resize the screen,  how to preserve the original size of all sprites?  Or how to avoid distortion and deformation?

**Comment by ivanpopelyshev** [comment]
Need more details. Why exactly do you need to resize it?

**Comment by qtttttttttting** [comment]
For example, in full screen, there are two sprites, 50px*50px. While exiting full screen, they remain the size. The distance between them can be  changed.

**Comment by qtttttttttting** [comment]
![image](https://user-images.githubusercontent.com/20217875/35255217-efb19ab6-0028-11e8-9376-f2ccedfe6ab2.png)
maybe like this.
Thank you so much!

**Comment by bigtimebuddy** [comment]
https://jsfiddle.net/bigtimebuddy/do59fk0h/

**Comment by themoonrat** [comment]
Closing as looks like question is answered :)
