### ISSUE TITLE
Plugin-level methods

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4604]
Some methods in pixi are neither public neither private by their meaning.

Here is collection of functions that I want to be marked as `plugin-level`:

Everything in Transform https://github.com/pixijs/pixi.js/blob/dev/src/core/display/TransformStatic.js
Uvs of the texture: https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Texture.js#L103
All `_updateID` in other files.

ActionScript has custom namespaces, while JsDoc and typescript dont have it. Our typescript definitions mark everything private, its like we need separate `d.ts` file for plugins.

What can we do about it?

**Comment by themoonrat** [comment]
@ivanpopelyshev With the recent changes to v5 (i remember plugin changes for interaction ap / using applicationi )has this been addressed or is this a plugin in a different area that hasn't been addressed yet?

**Comment by ivanpopelyshev** [comment]
Its documentation issue. The problem exists but there's no solution in JS/TS world as far as I know. 

It can be solved through extra code conventions and hacks with jsdoc plugin, but im not a specialist in it, i just declare the problem.

**Comment by bigtimebuddy** [comment]
I think we are overcomplicating this. We should just add those APIs to the typing and docs and make sure we make a note about it in the docs about what's advanced usage. Where appropriate we should use `@protected` like @themoonrat suggested. I'd be in favor of using some convention (like preceding underscore) to be synonymous with "don't touch this unless you know what you're doing" and not just limited to private members/methods.
