### ISSUE TITLE
broken lineTo

### ISSUE THREAD

**Issue by developer-av** [pixijs/pixi.js#4605]
Hi, How can i smooth this line?
lineTo with webGL renderer
![image](https://user-images.githubusercontent.com/15675868/34898355-5218fd24-f7fb-11e7-863e-3ef16861056f.png)
lineTo with canvas renderer
![image](https://user-images.githubusercontent.com/15675868/34898395-912a12f0-f7fb-11e7-80d7-90ba6e5d8686.png)
v: 4.6.2
[example](https://jsfiddle.net/zwdruqL9/1/)

**Comment by ivanpopelyshev** [comment]
```
new PIXI.WebGLRenderer(800, 600, {antialias: true});
```

**Comment by developer-av** [comment]
@ivanpopelyshev, thanks, closed
