### ISSUE TITLE
ColorMatrixFilter how to use by color 

### ISSUE THREAD

**Issue by neciszhang** [pixijs/pixi.js#4607]
hello, i want to use a picture by use ColorMatrixFilter with color "#e73b37", how can i use by matrix Array, how to  calculation? thanks a lot

**Comment by bigtimebuddy** [comment]
Not exactly sure what you're looking for but:

Here's an approach which basically replicates `tint` using ColorMatrixFilter.

```js
const color = new PIXI.filters.ColorMatrixFilter();
const tint = 0xe73b37;
const r = tint >> 16 & 0xFF;
const g = tint >> 8 & 0xFF;
const b = tint & 0xFF;
color.matrix[0] = r / 255;
color.matrix[6] = g / 255;
color.matrix[12] = b / 255;
```

https://jsfiddle.net/bigtimebuddy/4612gq30/1/

I used an approach with PixiAnimate: https://github.com/jiborobot/pixi-animate/blob/master/src/mixins/DisplayObject.js#L143-L153

The above code would allow you to do additive color as well as multiply tint.

**Comment by neciszhang** [comment]
@bigtimebuddy My problem has been successfully solved! thanks a lot! Sincerely ask you to marry you.

**Comment by neciszhang** [comment]
@bigtimebuddy My problem has been successfully solved! Thanks a lot! Sincerely wish you
