### ISSUE TITLE
Alpha property is ignored if cachedAsBitmap = true

### ISSUE THREAD

**Issue by hardcoremore** [pixijs/pixi.js#4610]
Hi all,

There is a bug where I can not change alpha of the object once the cacheAsBitmap is set to true. After I set cacheAsBitmap = true object can not be transparent anymore. I am setting casheAsBitmap on a PIXI.Container class.

I am using PixieJS v4.6.2

**Comment by ivanpopelyshev** [comment]
Yep, that issue is known. No one submitted good enough solution to fix that.

**Comment by ivanpopelyshev** [comment]
#3965 , #2771

**Comment by ivanpopelyshev** [comment]
I might give you a workaround if you give me more information. Feed me with your fiddle.

**Comment by hardcoremore** [comment]
Well that is a sad really. PixieJS is a great framework and it is a blast to use it. I have refactor my app to use pixie in no time. But this is a big problem for me since I need to use blur filter with high resolution settings and if I do not set cacheAsBitmap GPU usage becomes too high. Lack of this feature means that using filters if very limited.

Here is a fiddle https://jsfiddle.net/15dr5976/2/

**Comment by hardcoremore** [comment]
Is there any news about this issue, no fix yet?

**Comment by bigtimebuddy** [comment]
Hi @hardcoremore, there are at least two workarounds you could use here:

* You could wrap the DisplayObject that you are using `cacheAsBitmap = true` with another Container and apply alpha to that. https://jsfiddle.net/0su7ddvk/4/
* You could use the `PIXI.filters.AlphaFilter` to bake alpha into your `cacheAsBitmap` https://jsfiddle.net/ojb39991/

**Comment by ivanpopelyshev** [comment]
yep, it works: https://jsfiddle.net/0su7ddvk/6/

**Comment by themoonrat** [comment]
@bigtimebuddy Have the cacheAsBitmap annoyances been address with v5 yet? Or are they on the list to be addressed?

**Comment by replaysMike** [comment]
I'm surprised this is closed and as WillNotFixed, it's been a bug for a long time despite having a workaround.

**Comment by replaysMike** [comment]
I should note, the workaround fixes alpha issues however the height magically changes internally. It keeps growing, when cacheAsBitmap is turned off the height stays correct.

**Comment by bigtimebuddy** [comment]
@replaysMike I understand this is still an issue and would welcome if someone wanted to take a stab as fixing it, but as a very small core team of maintainers we don’t have enough resources to fix every issue so we focus on high-impact or critical things where there’s no alternative or workaround. While the workarounds here aren’t perfect, they work. PRs welcome!
