### ISSUE TITLE
Adapt loader to output blob for createImageBitmap

### ISSUE THREAD

**Issue by m9dfukc** [pixijs/pixi.js#4611]
**Setup:**
Pixi: v5 next [#cb75b1d](https://github.com/pixijs/pixi.js/commit/a8160890528f0ed8eef988d59500960d8ec6c05b), 
Browser: Chrome 64.0.3282
OS: macOs 10.12.06

**What happens:**  
I am trying to offload image decoding from the main thread to avoid bumps in framerate. Using the current version of Pixi.js next the ResourceLoader provides an `HTMLImageElement` to `createImageBitmap` which seems to block the main thread as opposed to `createImageBitmap(Blob)` which spans a separate thread.

**Code to replicate:**
I uploaded my test code to github which you can find [here](https://github.com/m9dfukc/createImageBitmap-performance).

**Comment by ivanpopelyshev** [comment]
Current version doesnt use async createImageBitmap. Please use `window.createBitmap` manually or wait for pixi-v5 where its used.

**Comment by m9dfukc** [comment]
Yes, I know that the current version doesn't use createBitmap. This issue targets the current next branch as stated above in the *Setup* section.

**Comment by ivanpopelyshev** [comment]
Can you measure it in firefox?

**Comment by m9dfukc** [comment]
I would love to do measurements in Firefox, unfortunately I am not really familiar with their developer tools. Especially the performance tools a hard to read and I don't get any reasonable information from that :/

**Comment by englercj** [comment]
You can specify how an image should be loaded already.

```js
loader.add('myimage', 'myimage.png', { loadType: Resource.LOAD_TYPE.XHR, xhrType: Resource.XHR_RESPONSE_TYPE.BLOB });
```

That will force the loader to load the image as a Blob over XHR.

If you want to force all images to load as XHR blobs, resource-loader supports doing so by extension:

```js
Resource.setExtensionLoadType('png', Resource.LOAD_TYPE.XHR);
Resource.setExtensionXhrType('png', Resource.XHR_RESPONSE_TYPE.BLOB);
```

After that any resources you add to the loader will default to being a Blob downloaded over XHR, unless you specify something specifically for an image.

I think in pixi resource-loader's `Resource` class as `LoaderResource`.

Hope this helps.

**Comment by m9dfukc** [comment]
@englercj Ah good to know. Unfortunately this still doesn't work as wanted. The `createImageBitmap` still get's a inline `HTMLImageElement` but this time instead with `<img src="image.png">` it's `<img src="blob:http://192.168.178.24:9966/394aa032-57ac-4a10-8bec-16949242e74f">` ... no separate worker thread spawned for the image decoding process. 

It's important to pass a [`Blob`](https://developer.mozilla.org/de/docs/Web/API/Blob) to `createImageBitmap` otherwise decoding will still happen in blocking nature on the main thread!

**Comment by m9dfukc** [comment]
I'm slowly digging through all the source code but still missing the whole picture. I'll submit a pull request whenever I am ready.

**Comment by ivanpopelyshev** [comment]
It would be good to get another specialist on texture uploading process in v5. I, @bigtimebuddy and @GoodBoyDigital  understand how it works.

We've made texture-resource refactoring, but we didnt test `createImageBitmap`, we assumed that all problems can be solved later, architecture allows it.

**Comment by ivanpopelyshev** [comment]
texture-resource API is upgraded from `completely internal pile of ... code (i guess?)` to `hooks for advanced users`.

**Comment by themoonrat** [comment]
Hi @m9dfukc - Have you had a chance to look at opening a PR for this? Thanks! :)
