### ISSUE TITLE
sprite can't use for a container?

### ISSUE THREAD

**Issue by windreamlion** [pixijs/pixi.js#4613]
if i add a graphics to a sprite  i can't get correct width 

let sprite =  new Sprite()

let gp:Graphics = new Graphics;
    gp.beginFill(0x134534);
    gp.drawRoundedRect(0,0,100,100,5);
    gp.endFill();

sprite.addChild(gp);

console.log('width:',sprite.width)  --> width: 1

means sprite can't use for a container?

thx

**Comment by themoonrat** [comment]
Until the sprite has been rendered to the screen at least once, it's internal properties won't be accurate.

**Comment by ivanpopelyshev** [comment]
Sprite overrides width and height: https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L492

If you want container width and height, take `getLocalBounds()` and multiply by scale. You can also take `getBounds()` if you dont have any rotations or scale at parent.

**Comment by themoonrat** [comment]
Closing as I think this has been answered :)
