### ISSUE TITLE
How to calculate hitArea based on pixels()?

### ISSUE THREAD

**Issue by nikkop** [pixijs/pixi.js#4614]
Heya,

Having .png images with transparency I would like to have a hitArea that is only the non-transparent parts of the image. My idea is this could be done by generating a polygon based on the pixel data ([pixels()](http://pixijs.download/dev/docs/PIXI.extract.WebGLExtract.html#pixels)) and then assigning that polygon as the hitArea of the sprite.

Any idea how to get a polygon out of the pixel data? I'm not too familiar with the approach.

Thanks & best regards

**Comment by ivanpopelyshev** [comment]
Its a bad idea to use `pixels()` in runtime, its better to load bitmap data from a separate file, only 1 bit per pixel. Assign `constainsPoint` method to sprite that uses that data.

**Comment by nikkop** [comment]
I was thinking at only doing this upon creating the sprite, not multiple times. So it shouldn't hurt performance I guess?

If you have any idea how to generate the polygon I'd be so happy to try it out.

**Comment by ivanpopelyshev** [comment]
you dont need polygon, just override `containsPoint` in your sprite. 

> upon creating the sprite

upon setting up the stage. Also its better to use original baseTexture source (Image), that way it wont go to videomemory and back. 

Do you know how to store info in a bit array?

I dont want to give you code examples, because its not a first-class feature, you have to understand how those parts work. Dig some more, then I'll help.

**Comment by djmisterjon** [comment]
it would be really great idea to integrate.
i use this function all time on AE for create animatedSprite for pixi.
![aerafra](https://user-images.githubusercontent.com/24865815/34983701-605c7a22-fa7c-11e7-809c-94ecd9bd9636.png)

this could open the door to easily putting physic in pixi, similar to plugin newton2 for AE.
it will export all data to xml like
```javascript
density="" 
friction="" 
restitution="" 
meshPrecision="" 
linearVelocityMagnitude=""
```
it would be necessary that pixi can build in cache a texture base on the alpha, and be able to set the mesh precision

**Comment by nikkop** [comment]
@djmisterjon Thanks for your suggestion.

I ended up using [PhysicsEditor](https://www.codeandweb.com/physicseditor) and exported it as text and created a PIXI.Polygon out of those points and then assigned the polygon to the hitArea. It works perfect!
