### ISSUE TITLE
[REQUEST][v5] Add progressive texture upload

### ISSUE THREAD

**Issue by m9dfukc** [pixijs/pixi.js#4615]
**Targets:** 
Pixi.js v5
WegGl 2
Firefox >= 42,  Chrome >= 50, Opera >= 39

**Problem description:**
Certain applications - VR for example (I know, not really the target audience of pixi.js) - require realtime assets loading without dropping frames. Therefore we need a way to decode and upload images in a non blocking manner.

**Proposal:**
With `createImageBitmap` we already got a async method of decoding an image in the two major browsers. The pixi.js support for ImageBitmap is already in the pipeline for v5 although [still not properly implemented](https://github.com/pixijs/pixi.js/issues/4611). The second part of this would be the progressive texture upload which is currently done using one pass with `texImage2D`. For larger images this could be done using `texSubImage2D` uploading the texture over serval frames or via `requestIdleCallback`.

**Related:**
- [http://www.html5gamedevs.com/topic/34997-progressive-texture-upload/](http://www.html5gamedevs.com/topic/34997-progressive-texture-upload/)  
- [https://github.com/mrdoob/three.js/issues/11746](https://github.com/mrdoob/three.js/issues/11746)  
- [https://github.com/spite/THREE.UpdatableTexture](https://github.com/spite/THREE.UpdatableTexture)

**Comment by ivanpopelyshev** [comment]
I guess its time to discuss it in issues :) Do the thing, I'll make sure that it will be approved. 

Gonna say it one more time - that's why I've fought for #4507, I've spent half year to think about it, and it took 3 weeks of heated discussion to merge it. Now we have a base to implement things like that.

**Comment by themoonrat** [comment]
Hi @m9dfukc - Did you get a chance to look at this? Sounds useful!
