### ISSUE TITLE
regarding Click on sprite/grphics element in multiple L.PixiOverlay

### ISSUE THREAD

**Issue by vk207** [pixijs/pixi.js#4616]
I am using mutliple layer application using pixioverlay on leafllet map. But the click event on sprite/garphics   is only effecting the last child layer ... can we get the click in the elements on the all layer

**Comment by ivanpopelyshev** [comment]
Yes, you can do that on `hacks` level of pixi usage. Not safe for newbies.

You have to patch processInteractive: https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L990

https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#css-transforms-on-canvas - here is how to patch InteractionManager, in general.

Sorry, I wont give you the complete code, I'm sure you guys can read that function, understand it and modify that way it works for you.

**Comment by Pandan** [comment]
I am also having problems with this. So thanks for the suggestion on patching processInteractive.

For me it creates issues when creating a scrollview, where I want to pick up elements in the scrollview but also the actual scrollview for determine if it should scroll or if an element has been clicked. But I will dig in and see if I can adjust the logic in processInteractive to get multiple events for overlapping targets.

But it feels a bit weird that we must patch pixi to get this kind of functionality. 
Or is there some other type approach that developers are using in this type of cases

**Comment by ivanpopelyshev** [comment]
Its all about balance of readability, code size, features and maintainability. For elements that pixi has its enough. When you add layers or ui, you need better core code. 

[pixi-display](https://github.com/pixijs/pixi-display/blob/layers/src/InteractionManagerMixin.ts) is one those cases, it adds special logic to re-order elements. You can take same `queue` approach to fire events across all the elements under the mouse.

**Comment by Pandan** [comment]
@ivanpopelyshev Thanks for the info

**Comment by themoonrat** [comment]
Closing as I think you have the answers :)
