### ISSUE TITLE
FontMetrics.fontSize is different than the input font size (TextStyle.fontSize)

### ISSUE THREAD

**Issue by maximedupre** [pixijs/pixi.js#4617]
let style = new PIXI.TextStyle({ fontSize: 41, fill: "#8A35A5" });
    let metrics = PIXI.TextMetrics.measureText(100, style);

    console.log(metrics.fontProperties) // {ascent: 38, descent: 9, fontSize: 47}

I think this is a bug, but maybe there is something I don't quite understand...

**Comment by bigtimebuddy** [comment]
`fontSize` maybe is not a great name, but it's the height from ascent to descent, not the actual fontSize from TextStyle

**Comment by maximedupre** [comment]
Thanks for the reply.

I see. What does `TextStyle.fontSize` represent then, if it isn't the height from ascent to descent?

**Comment by bigtimebuddy** [comment]
`fontSize` of the `TextMetrics.measureText` output is really `total`: the total height in pixels (ascent + descent). The `fontSize` in TextStyle, however is the actual internal size of the font itself. The TextStyle fontSize can also be expressed in unit like CSS, (`em`, `%`, `pt`, `px`, etc)
