### ISSUE TITLE
String contains only line break(s) causes WebGL error on PIXI.Text in iOS 11

### ISSUE THREAD

**Issue by dolow** [pixijs/pixi.js#4618]
__Environment:__
iPhone X / iOS 11.1 / Safari

__To reproduce:__
It can be reproduced with this line.

```
this.addChild(new PIXI.Text('\n'));
```

__Problem:__
It causes the error like this.

```
WebGL: INVALID_VALUE: texImage2D: no canvas
```

__Reason:__
It seems that the canvas with zero width and non-zero height causes this error.

__Solution:__
It can be solved like this.
https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L147

```
this.canvas.width = Math.ceil((width + (style.padding * 2)) * this.resolution);
if (this.canvas.width === 0) {
  this.canvas.width = 1;
}
```

__Need advice:__
I understood the problem and solution, but I can not decide if PIXI supports characteristic behavior (or bug) for particular rendering engine such as WebKit.

**Comment by dolow** [comment]
@bigtimebuddy 
Thanks ! I pushed the fixes here.
https://github.com/pixijs/pixi.js/pull/4627

**Comment by themoonrat** [comment]
Closing as has been fixed :)
