### ISSUE TITLE
Sprite mask error on MacOS

### ISSUE THREAD

**Issue by artem-popereka** [pixijs/pixi.js#4619]
Hi All,

Faced with such a problem: in chrome on a MacBook, when added a sprite mask, an error occurs
"Cannot read property 'push' of undefined"
error log attached.

The strangeness of this error lies in the fact that this happens only on a MacBook in chrome and also it is happened not on all MacBook. The error is not systemic, so it's very difficult to understand why this happens.

one more detail: on one of the MacBook the error was reproduced during the day (each time) and in the evening of the same day it ceased and was no longer reproduced. There is only one Mac in our office on which it is reproduced. We found out that this does not depend on the version of the chrome, OS and the parameters of the Mac.

As a quick solution used shaders instead of a mask - there is no error. But I would like to understand the cause of this phenomenon and still use the sprite mask.

Another detail over the mask and masked container is spine animation. (this does not affect, was checked)

Error Log:

`index.js:260 
    PixiJS 4.6.2 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 

soundjs-0.6.2.min.js:19 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
n._updateVolume @ soundjs-0.6.2.min.js:19
FilterManager.js:608 Uncaught TypeError: Cannot read property 'push' of undefined
    at e.freePotRenderTarget (FilterManager.js:608)
    at e.popFilter (FilterManager.js:160)
    at e.popSpriteMask (MaskManager.js:127)
    at e.popMask (MaskManager.js:83)
    at e.renderAdvancedWebGL (Container.js:474)
    at e.renderWebGL (Container.js:405)
    at e.renderWebGL (Container.js:414)
    at e.renderWebGL (Container.js:414)
    at e.renderWebGL (Container.js:414)
    at e.renderWebGL (Container.js:414)
e.freePotRenderTarget @ FilterManager.js:608
e.popFilter @ FilterManager.js:160
e.popSpriteMask @ MaskManager.js:127
e.popMask @ MaskManager.js:83
e.renderAdvancedWebGL @ Container.js:474
e.renderWebGL @ Container.js:405
e.renderWebGL @ Container.js:414
e.renderWebGL @ Container.js:414
e.renderWebGL @ Container.js:414
e.renderWebGL @ Container.js:414
e.renderWebGL @ Container.js:414
e.renderWebGL @ Container.js:414
e.render @ WebGLRenderer.js:329
t.render @ RenderManager.ts:205
t.onTick @ RenderManager.ts:191
t.emit @ desktop.js:46280
t.update @ Ticker.js:394
_tick @ desktop.js:45855
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858
requestAnimationFrame (async)
_tick @ desktop.js:45858`

Thanks,
Artem

**Comment by themoonrat** [comment]
@artem-popereka Is this still an issue on the latest version of pixi with the latest browser version?

**Comment by artem-popereka** [comment]
Hi! We cheked. In version 4.8.1 issue is not reproduced. In version 4.7.3 is exist.

Thanks for helping.

**Comment by ivanpopelyshev** [comment]
It was related to #4858
