### ISSUE TITLE
Video Texture won't autoplay on Android (Urgent Help!)

### ISSUE THREAD

**Issue by codyng** [pixijs/pixi.js#4620]
Hi there,

I have found that video texture doesn't autoplay on Android.
The video is mp4 and I used PIXI.Texture.fromVideo() method.
It is fine on iOS 10 and the video is mute.

What is going on?

Urgent Help!
Thank you very much!!

**Comment by themoonrat** [comment]
A lot of mobile browsers require that sound and video playback can only be unlocked on a user interaction. Not much you can do about that.

**Comment by mauro1998** [comment]
as @themoonrat says, it is a known limitation for some mobile browsers with autoplay.
I've been looking for a workaround to this. 
if user can interact with the site before autoplaying your video, this might help:
first, create the video element in html:

    <video id="video" autoplay webkit-playsinline="true" playsinline="true">
        ...sources
     </video>

once page loads, do this trick:

    const video = document.getElementById('video');
    // add a one time tap event to play and pause the video 
    // to meet the requirement about "explicitly play media by user gesture"
    document.addEventListener('touchend', function(event) {
        document.removeEventListener(event.type, arguments.callee);
        video.play().catch(e => e); // avoid logging any errors like "play request interrupted by a call to pause()"
        video.pause();
    });

then, later on when you'd like to play your video, programmatically call the play method:

    video.play();

if user tapped the screen before, it will hopefully work.
it worked for me on android and iOS (but not sure which versions).

**Comment by themoonrat** [comment]
Closing as I feel the workaround described is the only way around browser requirements to have an interaction before video can autoplay. Feel free to re-open if you disagree!
