### ISSUE TITLE
Coordinates of a Graphics are always 0

### ISSUE THREAD

**Issue by maximedupre** [pixijs/pixi.js#4621]
let rectangle = new PIXI.Graphics();

    rectangle.drawRect(70, 35.5, 10, 10);
    rectangle.endFill();

    console.log('rectangle.x', rectangle.x) // 0
    console.log('rectangle.y', rectangle.y) // 0
    console.log('rectangle.position', rectangle.position) // {x: 0, y: 0}
    console.log('rectangle.getBounds()', rectangle.getBounds()) // {x: 70, y: 35.5, width: 10, height: 10, type: 1}

Here is a little [jsfiddle](https://jsfiddle.net/o9k66bum/6/) to help you.

All sorts of weird behaviours ensue from this bug. If I try setting `y` after this code (e.g. `rectangle.y = 10`), it acts like `rectangle += 10`. So even though I can get the correct data from `getBounds`, I can't find a way to set the correct data.

Is there a workaround that I can currently use?

**Comment by bigtimebuddy** [comment]
Try this:

```js
let rectangle = new PIXI.Graphics();

rectangle.drawRect(0, 0, 10, 10);
rectangle.endFill();

rectangle.position.set(70, 35.5);

console.log('rectangle.x', rectangle.x)
console.log('rectangle.y', rectangle.y)
console.log('rectangle.position', rectangle.position)
console.log('rectangle.getBounds()', rectangle.getBounds())
```
With `drawRect` the x and y values that you set don't change the x and y of the Graphics object itself, it's only the local coordinate where to draw the rectangle.

**Comment by maximedupre** [comment]
Ah, got it. And there is no difference between `rectangle.position.set(x, y)` and `rectangle.x = x; rectangle.y = y` right?

And how does one change the coordinates of the rectangle (not the Graphics container)?

Thanks

**Comment by bigtimebuddy** [comment]
Check out the at the docs for [`drawRect`]( http://pixijs.download/release/docs/PIXI.Graphics.html#drawRect), first arguments are x and y. You cannot change the position of the shape after you draw it. Create separate Graphics for separate shapes that you need to position.

And yes, position.set is the same as setting x and y directly.
