### ISSUE TITLE
"Cannot read property 'children' of null" when trying to Container.removeChild()

### ISSUE THREAD

**Issue by karaliunas** [pixijs/pixi.js#4623]
https://codepen.io/gka/pen/zpyMNV

Steps to reproduce:
1. Delete some circles (select and press Del key). Works fine.
2. Try to delete more circles and I get an error on 22nd line.

"el.parent" on 22nd line becomes null after one or two cycles of removing, but the Container still exists with children. Looks like "el.parent"  looses it's linkage with Container.

**Comment by bigtimebuddy** [comment]
When you remove the Graphic object from the stage you never remove it from your `seats` Array.

**Comment by ivanpopelyshev** [comment]
You dont remove it from seats.

**Comment by bigtimebuddy** [comment]
Beat you @ivanpopelyshev!

**Comment by ivanpopelyshev** [comment]
I was triple-checking $)

**Comment by karaliunas** [comment]
Thank you guys for such instant reaction! This cleared things for me!
