### ISSUE TITLE
Proposal: Add PIXI.extract.pixelSampler(target, x, y)

### ISSUE THREAD

**Issue by soimy** [pixijs/pixi.js#4624]
In the current implementation of PIXI.extract, if we want to sample a pixel of `DisplayObject` or `RenderTexture`, we have to extract the entire canvas first. And this is not good for real-time (not static and cached) usage.
I was able to extend the `WebGLExtract.js` to add a `pixelSampler(target: DisplayObject | RenderTexture, x: number, y: number)` method with only simple changes:
``` javascript
gl.readPixels(x * resolution, y * resolution, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, webglPixels);
```
and the latency is around 3-5ms in my late 2014 13inch rmbp. I don't think it's good enough, maybe some lower-level approach is possible but far beyond my abilities.

**Comment by ivanpopelyshev** [comment]
readPixels is the only synchronous function in webgl context, it waits info from GPU. Your program doesn't do anything until it gets that info. Its ok to use it once per frame, after its end (same as preserveDrawingBuffer).

**Comment by soimy** [comment]
OK, If your think this `pixelSampler` API is necissary, I can create a pull request.

**Comment by themoonrat** [comment]
@soimy Is this something you think you could get around to submitting? Would be appreciated! Thanks
