### ISSUE TITLE
custom ObjectRenderer for liquidfun particleSystem

### ISSUE THREAD

**Issue by doebi** [pixijs/pixi.js#4625]
First of all, I am not sure if this is actually a bug in PIXI or just me using it wrong.

I am trying to render a scene of physical objects with PIXI. The physics engine I am using is liquidfun (a fork of Box2D extended with fluid particle systems)

https://github.com/doebi/liquidfun.js-demo/

In the beginning I created Sprites for each particle, which performed horribly. After a lot of iteration I came to the current approach, where I create a custom Object renderer in PIXI based on https://github.com/pixijs/pixi-plugin-example

This enabled me to pass the complete buffers of the particle System to the GPU at once.

To render the particleSystem as a monogamous fluid using the metaballs technique I need to render in 3 passes.
1. render balls at the particles locations
2. blur the whole image
3. apply a threshold

For this I need 2 textures and a framebuffer object to render at, which i create using the native gl API.
I managed to get that all working with the native gl API, but combined with default PIXI renderd Sprites this causes some strange behaviour.

As soon as the first particles get rendered, all other objects in the scene disappear. I think this is related to: http://www.html5gamedevs.com/topic/34448-add-raw-webgl-texture-to-pixijs/
In my current setup all 'normal' sprites use the same texture.

I think there is something wrong in the way I use or create the textures and fbo, the sourcecode in question can be found at:
https://github.com/doebi/liquidfun.js-demo/blob/master/js/lib/liquidfun-renderer.js

I also tried to replace all native gl objects with objects from pixi-gl-core, which introduced a lot of other bugs and i stopped trying.

It would be nice if someone more experienced than me can have a look at my renderer and lead me to a working renderer. Thanks.

**Comment by ivanpopelyshev** [comment]
You have to bind textures and framebuffer through `renderer.bindTexture(tex, 0, true)` (where 0 is location), and use `renderer.bindRenderTexture` .

Alternative way: call `renderer.reset()` after your render pass to clear all cached values (bound tetxure list, bound framebuffer, e.t.c.)

**Comment by doebi** [comment]
@ivanpopelyshev Thanks for your quick answer.
As I mentioned earlier, I already tried moving away from native GL to all the PIXI internal GL calls. Cause just replacing the call to `renderer.bindTexture` won't work since i initalized a native GL Texture and that call expects a PIXI.Texture. I stopped pursuing that approach cause one led to another and I faced myself rewriting the complete code until I lost control and nothing was working anymore.
But if there is no other way of doing I might have to take that approach again.. :/

Adding a call to `renderer.reset()` just throws an `Maximum call stack size exceeded` error, no matter if i add it after my render code in `flush()` or in `stop()`

**Comment by ivanpopelyshev** [comment]
`reset()` calls `objectRenderer.flush`, and you're already inside it, so you have to detect recursion and stop it.

**Comment by doebi** [comment]
well if i move the render logic to `render()` and call `renderer.reset()` in there, i get really ugly flickering at about 1fps and some webgl errors: `GL ERROR :GL_INVALID_OPERATION : glDrawArrays: Source and destination textures of the draw are the same.`


What actually is causing my custom GL code to 'overwrite/discard' the textures of other sprites?

**Comment by ivanpopelyshev** [comment]
That because it handles framebuffer switching wrong. What version of pixi do you use?

**Comment by doebi** [comment]
PixiJS 4.7.0

**Comment by ivanpopelyshev** [comment]
ok then , either you make a fiddle for me, either you look inside reset() method and figure out why it doesnt change framebuffer back to root. Also, it might be that you need save framebuffer state and restore it, i dont know if there's a filter above you :)

**Comment by doebi** [comment]
You can just clone https://github.com/doebi/liquidfun.js-demo and look at the complete sourcecode.
Or do you prefer a fiddle?

Which steps do you suggest in further debugging?

**Comment by ivanpopelyshev** [comment]
github is fine.

**Comment by ivanpopelyshev** [comment]
If you dont want to wait for me, you can look at https://github.com/ymiroshnyk/neutrinoparticles.js/blob/master/dist-PIXI/neutrinoparticles.pixi.js#L524 as an example.

**Comment by doebi** [comment]
Thanks for pointing that out.
I did some trial and error and found, that by adding those 3 lines it works as intended:
```
    renderer.bindVao(null);
    renderer._activeShader = null;
    renderer.bindTexture(null, 0, true);
```

**Comment by ivanpopelyshev** [comment]
You rock!
