### ISSUE TITLE
cacheAsBitmap causing issues in Canvas mode

### ISSUE THREAD

**Issue by onehost1** [pixijs/pixi.js#4626]
HI all,

First of all, thank you for building this wonderful library. Really makes life so much easier!

While PIXI seems to work without any issues in Webgl mode, I see problems when I am trying to load the same code in Canvas mode. Our setup has thousand of sprites but I tried with only few components as well and if cacheAsBitmap is turned on, it's the same issue. We are doing panning-zooming on the canvas so probably can be an issue but below code which I forked from cacheAsBitmap function in the webglRenderer seems to do the trick...

I have been diagnosing the issue and found the culprit to be cacheAsBitmap functionality.

I thought cacheAsBitmap would be same for Webgl and canvas and pretty much would work in similar fashion. Also looking at the main function, , it says '// TODO this can be the same as the webGL verison.. will need to do a little tweaking first though..'. Looks like author realizes that and therefore has added it to the todo list.

Since I needed this fix quickly for what I am doing, I decided to copy Webgl code for similar function and use that after making few necessary changes. 

Is it possible to merge that for your next release and even better, look at the code changes I did.

Added 
```js
/**
     * Changes the current renderer to the one given in parameter
     *
     * @param {PIXI.ObjectRenderer} objectRenderer - The object renderer to use.
     */


    CanvasRenderer.prototype.setObjectRenderer = function setObjectRenderer(objectRenderer) {
        if (this.currentRenderer === objectRenderer) {
            return;
        }

        this.currentRenderer.stop();
        this.currentRenderer = objectRenderer;
        this.currentRenderer.start();
    };

    /**
     * This should be called if you wish to do some custom rendering
     * It will basically render anything that may be batched up such as sprites
     *
     */


    CanvasRenderer.prototype.flush = function flush() {
        this.setObjectRenderer(this.emptyRenderer);
    };
```
and then modified function _initCachedDisplayObjectCanvas as below
```js
DisplayObject.prototype._initCachedDisplayObjectCanvas = function _initCachedDisplayObjectCanvas(renderer) {
    if (this._cacheData && this._cacheData.sprite) {
        return;
    }

    var cacheAlpha = this.alpha;

    this.alpha = 1;

    // first we flush anything left in the renderer (otherwise it would get rendered to the cached texture)
    renderer.plugins.sprite.renderer.flush();
    // this.filters= [];

    // get bounds actually transforms the object for us already!
    var bounds = this.getLocalBounds();

    // next we find the dimensions of the untransformed object
    // this function also calls updatetransform on all its children as part of the measuring.
    // This means we don't need to update the transform again in this function
    // TODO pass an object to clone too? saves having to create a new one each time!
    var bounds = this.getLocalBounds().clone();

    // add some padding!
    if (this._filters) {
        var padding = this._filters[0].padding;

        bounds.pad(padding);
    }

    // for now we cache the current renderTarget that the webGL renderer is currently using.
    // this could be more elegent..
    var cachedRenderTarget = renderer.context;
    // We also store the filter stack - I will definitely look to change how this works a little later down the line.
    // var stack = renderer.filterManager.filterStack;

    // this renderTexture will be used to store the cached DisplayObject

    var renderTexture = core.RenderTexture.create(bounds.width | 0, bounds.height | 0);

    var textureCacheId = 'cacheAsBitmap_' + (0, _utils.uid)();

    this._cacheData.textureCacheId = textureCacheId;

    _BaseTexture2.default.addToCache(renderTexture.baseTexture, textureCacheId);
    _Texture2.default.addToCache(renderTexture, textureCacheId);

    // need to set //
    var m = _tempMatrix;

    m.tx = -bounds.x;
    m.ty = -bounds.y;

    // m.tx -= bounds.x;
    // m.ty -= bounds.y;

    // m.append(this.transform.worldTransform.)
    // set all properties to there original so we can render to a texture
    this.renderCanvas = this._cacheData.originalRenderCanvas;

    renderer.render(this, renderTexture, true, m, true);
    // now restore the state be setting the new properties
    renderer.context = cachedRenderTarget;

    this.renderCanvas = this._renderCachedCanvas;
    this._calculateBounds = this._calculateCachedBounds;

    this._mask = null;
    this.filterArea = null;

    // create our cached sprite
    var cachedSprite = new core.Sprite(renderTexture);

    cachedSprite.transform.worldTransform = this.transform.worldTransform;
    cachedSprite.anchor.x = -(bounds.x / bounds.width);
    cachedSprite.anchor.y = -(bounds.y / bounds.height);
    cachedSprite._bounds = this._bounds;
    cachedSprite.alpha = cacheAlpha;

    // easy bounds..
    this._calculateBounds = this._calculateCachedBounds;
    this.getLocalBounds = this._getCachedLocalBounds;

    this._cacheData.sprite = cachedSprite;

    this.transform._parentID = -1;
    // restore the transform of the cached sprite to avoid the nasty flicker..
    if (!this.parent) {
        this.parent = renderer._tempDisplayObjectParent;
        this.updateTransform();
        this.parent = null;
    } else {
        this.updateTransform();
    }

    this.updateTransform = this.displayObjectUpdateTransform;

    this.containsPoint = cachedSprite.containsPoint.bind(cachedSprite);
};
```

**Comment by onehost1** [comment]
Added 
`/**
     * Changes the current renderer to the one given in parameter
     *
     * @param {PIXI.ObjectRenderer} objectRenderer - The object renderer to use.
     */


    CanvasRenderer.prototype.setObjectRenderer = function setObjectRenderer(objectRenderer) {
        if (this.currentRenderer === objectRenderer) {
            return;
        }

        this.currentRenderer.stop();
        this.currentRenderer = objectRenderer;
        this.currentRenderer.start();
    };

    /**
     * This should be called if you wish to do some custom rendering
     * It will basically render anything that may be batched up such as sprites
     *
     */


    CanvasRenderer.prototype.flush = function flush() {
        this.setObjectRenderer(this.emptyRenderer);
    };
`
and then modified function _initCachedDisplayObjectCanvas as below
`DisplayObject.prototype._initCachedDisplayObjectCanvas = function _initCachedDisplayObjectCanvas(renderer) {
    if (this._cacheData && this._cacheData.sprite) {
        return;
    }

    var cacheAlpha = this.alpha;

    this.alpha = 1;

    // first we flush anything left in the renderer (otherwise it would get rendered to the cached texture)
    renderer.plugins.sprite.renderer.flush();
    // this.filters= [];

    // get bounds actually transforms the object for us already!
    var bounds = this.getLocalBounds();

    // next we find the dimensions of the untransformed object
    // this function also calls updatetransform on all its children as part of the measuring.
    // This means we don't need to update the transform again in this function
    // TODO pass an object to clone too? saves having to create a new one each time!
    var bounds = this.getLocalBounds().clone();

    // add some padding!
    if (this._filters) {
        var padding = this._filters[0].padding;

        bounds.pad(padding);
    }

    // for now we cache the current renderTarget that the webGL renderer is currently using.
    // this could be more elegent..
    var cachedRenderTarget = renderer.context;
    // We also store the filter stack - I will definitely look to change how this works a little later down the line.
    // var stack = renderer.filterManager.filterStack;

    // this renderTexture will be used to store the cached DisplayObject

    var renderTexture = core.RenderTexture.create(bounds.width | 0, bounds.height | 0);

    var textureCacheId = 'cacheAsBitmap_' + (0, _utils.uid)();

    this._cacheData.textureCacheId = textureCacheId;

    _BaseTexture2.default.addToCache(renderTexture.baseTexture, textureCacheId);
    _Texture2.default.addToCache(renderTexture, textureCacheId);

    // need to set //
    var m = _tempMatrix;

    m.tx = -bounds.x;
    m.ty = -bounds.y;

    // m.tx -= bounds.x;
    // m.ty -= bounds.y;

    // m.append(this.transform.worldTransform.)
    // set all properties to there original so we can render to a texture
    this.renderCanvas = this._cacheData.originalRenderCanvas;

    renderer.render(this, renderTexture, true, m, true);
    // now restore the state be setting the new properties
    renderer.context = cachedRenderTarget;

    this.renderCanvas = this._renderCachedCanvas;
    this._calculateBounds = this._calculateCachedBounds;

    this._mask = null;
    this.filterArea = null;

    // create our cached sprite
    var cachedSprite = new core.Sprite(renderTexture);

    cachedSprite.transform.worldTransform = this.transform.worldTransform;
    cachedSprite.anchor.x = -(bounds.x / bounds.width);
    cachedSprite.anchor.y = -(bounds.y / bounds.height);
    cachedSprite._bounds = this._bounds;
    cachedSprite.alpha = cacheAlpha;

    // easy bounds..
    this._calculateBounds = this._calculateCachedBounds;
    this.getLocalBounds = this._getCachedLocalBounds;

    this._cacheData.sprite = cachedSprite;

    this.transform._parentID = -1;
    // restore the transform of the cached sprite to avoid the nasty flicker..
    if (!this.parent) {
        this.parent = renderer._tempDisplayObjectParent;
        this.updateTransform();
        this.parent = null;
    } else {
        this.updateTransform();
    }

    this.updateTransform = this.displayObjectUpdateTransform;

    this.containsPoint = cachedSprite.containsPoint.bind(cachedSprite);
};`

**Comment by onehost1** [comment]
Anybody able to volunteer to check code and make a pull-request out of it?

Thanks heaps!

**Comment by bigtimebuddy** [comment]
Would you mind making a jsfiddle that clearly shows a broken cacheAsBitmap on canvas?  Then we can use this fiddle in the future to validate the PR.

**Comment by onehost1** [comment]
Hi @bigtimebuddy, Where it is causing the issues is file with thousands of line of codes. I will soon have something simpler prepared for you.

Thanks

**Comment by onehost1** [comment]
Hi @bigtimebuddy,

It is taking extended amount of time trying to replicate the same setup. What we are doing is as follows. Hope it gave you some insight into the issue and how above patch fixed it.

We have a huge canvas that loads SVGs on the initialization of the page. We allow user to do pan and zoom to the elements and do different interactions etc. SVGs are downloaded through ajax the first time and then saved into Indexdb as blob to make page load quicker for next times. 

Everything seems to work fine in WEBGL and Canvas mode. However, when user tries to Pan/Zoom  position seems to reset to 0,0, i.e the left most block goes to 0,0 position while others take position relative to that block. In short, nothing breaks, the position just resets to 0,0 and nothing seemed to move any further or zoom at all.

I don't know how or why but `DisplayObject.prototype._initCachedDisplayObjectCanvas` function seem to be the culprit and copying code from WEBGL seem to do the trick. On that note, I don't understand why functions for Webgl and canvas mode different in the first place. May be they evolved over time and Webgl code upgrade seemed to take on precedence?

Please let me know if it makes sense.

**Comment by onehost1** [comment]
Hope below gif helps. This is in 'forceCanvas' mode
![2018-01-25_09-20-00](https://user-images.githubusercontent.com/7464668/35362442-147fa25a-01b1-11e8-9973-db8d0cb1c0f8.gif)

**Comment by onehost1** [comment]
@bigtimebuddy , did you had a moment to think about this issue?

Cheers
