### ISSUE TITLE
turn on antialias makes cpu fan runs crazy

### ISSUE THREAD

**Issue by superliwei** [pixijs/pixi.js#4628]
i made a very simple test of creating some graphics after turning on antialias for a while, the cpu fan runs crazy.

**Comment by ivanpopelyshev** [comment]
Macbook?

**Comment by superliwei** [comment]
@ivanpopelyshev yes

**Comment by superliwei** [comment]
@ivanpopelyshev yes.

**Comment by ivanpopelyshev** [comment]
```
INSERT_JOKE_ABOUT_APPLES_HERE
```

Its true for pixi, phaser, threejs, any other engine, since the creation of canvas element. Yes, even 2d context.

**Comment by ivanpopelyshev** [comment]
Plug in the power cable.
