### ISSUE TITLE
[v5] Remove isPowerOfTwo check for webgl2

### ISSUE THREAD

**Issue by m9dfukc** [pixijs/pixi.js#4629]
**Targets:** 
Pixi.js v5
WegGl 2
Firefox >= 42,  Chrome >= 50, Opera >= 39

**Problem description:**
Pixi.js next as of [b631a77](https://github.com/pixijs/pixi.js/commit/b631a77439a8e828a7b67018928b4500cc84e269) does a power of two check (*TextureSystem*) before generating mipmaps even in webgl2 mode. According to the Khronos [specification](https://www.khronos.org/registry/webgl/specs/latest/2.0/#4.1.3) for webgl2 *there are no special restrictions on non power of 2 textures* for mipmapping or wrapping modes. 

**Solution:**
Only check for `isPowerOfTwo` when not in webgl2 mode (which will be the default in pixi.js v5 ?).

**Comment by ivanpopelyshev** [comment]
That's good indicator - if texture is pow2 => user wants to generate mipmaps. We can add one more flag in settings, or make current one number instead of bool - whether we use that features of webgl2.
