### ISSUE TITLE
AccessibilityManager uses wrong values

### ISSUE THREAD

**Issue by nikkop** [pixijs/pixi.js#4630]
Upon experimenting with the AccessibilityManager I noticed weird behavior when setting the **width** and **height** of the overlay div in the update method. The width and height are set using the renderers width and height, instead of the DOM elements _getBoundingClientRect()_.

This leads to wrong values being set, as borders are not accounted for.
The Canvas has a border of 10px:
![borderissue](https://user-images.githubusercontent.com/6517126/35220094-57963a6a-ff75-11e7-8df1-ec9e5b2bc07b.jpg)

Current code:
```javascript
const rect = this.renderer.view.getBoundingClientRect();
const sx = rect.width / this.renderer.width;
const sy = rect.height / this.renderer.height;

let div = this.div;

div.style.left = `${rect.left}px`;
div.style.top = `${rect.top}px`;
div.style.width = `${this.renderer.width}px`;
div.style.height = `${this.renderer.height}px`;
```

Simply changing the last two lines to use the rect instead solves the issue:
```javascript
div.style.width = `${rect.width}px`;
div.style.height = `${rect.height}px`;
```
![borderfix](https://user-images.githubusercontent.com/6517126/35231728-cce8d786-ff99-11e7-85f7-258ab0785f46.jpg)

Is there any reason the renderer's width and height are used instead of the getBoundingClientRect()? If not and it's simply a miss I can create a PR that fixes it :)

**Comment by ivanpopelyshev** [comment]
```js
const sx = rect.width / this.renderer.width;
const sy = rect.height / this.renderer.height;
```

I dont like those lines too. Its real pixel width and height, not CSS. It should at least `this.renderer.screen.width`

**Comment by nikkop** [comment]
@ivanpopelyshev So what I found is actually a issue and not a quirk? So I know if I should make a PR out of it. I could at the same time include what you are suggesting. Should I simply copy what you have suggested?

**Comment by ivanpopelyshev** [comment]
Better make PR with a fiddle that shows the wrongness.

As for my suggestion, *if you have free time*, please look at resolution param:

```js
renderer = new PIXI.WebGLRenderer(800, 600, {resolution:2, autoResize: true});
```
This setup will make 1600x1200 canvas with 800x600 css dimensions. If accessability fails to cover the canvas, you can try to fix that too, the same or separate PR.

**Comment by nikkop** [comment]
@ivanpopelyshev I will take some time to look into it sure :) Thanks for helping out.

I've got another question and suggestion about the AccessibilityManager I thought I could ask here instead of opening a new issue.

Inside the createTouchHook method the "HOOK DIV" button is appended to the body. Is there any specific reason for this?
```javascript
createTouchHook()
{
    // ...creation of the element etc.
    document.body.appendChild(hookDiv);
}
```

Wouldn't it be better (and make more sense) to prepend/append it to the same parent container that the Canvas/view is instead? i.e:
```javascript
createTouchHook()
{
    // ...creation of the element etc.
    this.renderer.view.parentNode.insertBefore(hookDiv, this.renderer.view);
}
```

I've encountered a issue where the current way (appending to body) breaks our application but where my suggestions fixes it. Unfortunately due to confidentiality I can't share that and nor have I found a way to recreate it outside of our environment (we are running 4.7.0). 

However I think that making sure the hookDiv and the Canvas/view are in the same level or hierarchy makes sense when you're tabbing and triggering the AccessibilityManager?

If you agree with me I can make a single PR of the things we have discussed so far :)
Best regards

**Comment by ivanpopelyshev** [comment]
Honestly, its not my area of expertise. Lets wait for others. 

I just pointed out `renderer.screen.width` thing, that's one of mine :)

**Comment by nikkop** [comment]
@ivanpopelyshev Ok, sounds good. I will continue doing some testing and see what I can find and do :)

**Comment by themoonrat** [comment]
Hi @nikkop - Did you find a solution for this?
