### ISSUE TITLE
http://pixijs.github.io/examples/ can not load js

### ISSUE THREAD

**Issue by yyman001** [pixijs/pixi.js#4631]
pixi.js Failed to load resource: net::ERR_INSECURE_RESPONSE
pixijs.io/:1 Uncaught ReferenceError: PIXI is not defined
window.onload @ VM1713:1
pixi.js Failed to load resource: net::ERR_INSECURE_RESPONSE
VM1713:1 Uncaught ReferenceError: PIXI is not defined

**Comment by ivanpopelyshev** [comment]
We do have problems with SSL certificate, thank you for pointing that.
