### ISSUE TITLE
how to update use after sprite object for setTransform ?

### ISSUE THREAD

**Issue by yyman001** [pixijs/pixi.js#4633]
### pixi.js - v4.6.2
    Hi~
1.first to do `setTransform ` is OK, but the second is at this `Original object`  to `setTransform `...
I try it use `updateTransform` ,but it is invalid~
eg:
Original object width 152px
one `setTransform ` after is 200px
second to do `setTransform ` 。。。that use `Original object` to sacle. first `setTransform ` is no save!,no update~
    so,how can i update use `setTransform ` after ? the `updateTransform` is no invalid .thank you~
look img
![image](https://user-images.githubusercontent.com/5688485/35278454-0fa8d22e-0085-11e8-9a84-4dd085c26b92.png)
![222](https://user-images.githubusercontent.com/5688485/35278735-e2d779b6-0085-11e8-8d8f-da6f79857643.png)
![3](https://user-images.githubusercontent.com/5688485/35278748-e738f2fa-0085-11e8-9c97-82a5fbbb847a.png)

```js
let shape = window.controlObject
            let x = shape.x
            let y = shape.y
            let w = shape.width
            let h = shape.height
            let offsetX = newPosition.x - x
            let offsetY = newPosition.y - y
            let scaleX = offsetX / window.tempPosition.width
            let scaleY = offsetY / window.tempPosition.height
             console.log('offset-x:', offsetX)
             console.log('scaleX:', scaleX)
            shape.offsetX = offsetX
            shape.offsetY = offsetY
            this.updateBBox({x: x, y: y, w: offsetX, h: window.tempPosition.height, shape: shape})
            this.updateControlListPosition(shape, offsetX, offsetY)
            if (window.targetSprite) {
console.log('>>>>onDragMove:',window.targetSprite.width,'window.tempPosition.width',window.tempPosition.width);
              window.targetSprite.setTransform(x, y, scaleX, 0, 0, 0, 0, 0, 0)
              window._temp_width = window.targetSprite.width
              console.log('onDragMove>>>>:', window.targetSprite.width,'window.tempPosition.width',window.tempPosition.width);
              console.log('_temp_width:', _temp_width)
            }
```

**Comment by ivanpopelyshev** [comment]
setTransform with scaleY = 0. I cant give any guarantees for degenerate matrices.

Also, `width` of sprite is `scaleX * sprite.texture.width` according to https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L492

Please notice that container has different meaning for width, its calculated through `getLocalBounds`.

**Comment by yyman001** [comment]
thank you! that is ok !
