### ISSUE TITLE
Failed to load assets on IE/Edge

### ISSUE THREAD

**Issue by iyuuya** [pixijs/pixi.js#4634]
With basic authentication on IE / Edge, if crossOrigin is set, the result is 401.
I tried this.

```js
//= Context ====================
// The protocol and host are https://example.com
window.location.hostname; //=> example.com
window.location.protocol; //=> https:

var texture = PIXI.Texture.fromImage("/path/to/imgA.png");
// RequestHeader[Origin]: https://example.com
// IE/Edge: status 401
// Chrome: status 200

//= Debug ===================
image = new Image();
image.src = "/path/to/imgB.png";
image.crossOrigin = "https://example.com";
dom.appendChild(image);
// RequestHeader[Origin]: https://example.com
// IE/Edge: status 401
// Chrome: status 200

var image = new Image();
image.src = "/path/to/imgC.png";
dom.appendChild(image);
// RequestHeader[Origin]: NOT SET
// IE/Edge: status 200
// Chrome: status 200
```

What do you think?

### Reproduction
- PixiJS: v4.5.6
- Edge: 38.14393.1066.0
- Internet Explorer: 11.1358.14393.0

### Related?
#1149 #1234 #1269

---

I'm not good at writing English, and I may make many mistakes. So, please be patient with me.

**Comment by themoonrat** [comment]
@iyuuya Did you find a way around this issue? Closing as I get the feeling it's not a PIXI specific issue, but feel free to re-open if you feel it is :)
