### ISSUE TITLE
Loading spritesheet from a REST api

### ISSUE THREAD

**Issue by lebesnec** [pixijs/pixi.js#4637]
I'm trying to load a spritesheet which is generated by a REST api. It doesn't work unless I add a `.json` extension at the end of the URL.

This does not work:
`PIXI.loader.add('spritesheet_123', '/api/spritesheet/123');`
`PIXI.loader.load();`

This work:
`PIXI.loader.add('spritesheet_123', '/api/spritesheet/123.json');`
`PIXI.loader.load();`

Is there a way to avoid using the `.json` part ?

Also is there a way to load a spritesheet from json you already have on the client side ? Something like:
`var spritesheet = { frames: { ... }, ... };`
`PIXI.loader.add(spritesheet);`
`PIXI.loader.load();`

**Comment by bigtimebuddy** [comment]
## 1.

Check out the documentation [here](http://englercj.github.io/resource-loader/Loader.html#add) for the `add` method. You should be able to define the type of the response. For instance:

```js
PIXI.loader.add('spritesheet_123', '/api/spritesheet/123', {
  xhrType: PIXI.loaders.Resource.XHR_RESPONSE_TYPE.JSON
});
```

## 2.

There _is_ a way to parse spritesheet data: 

```js
const spritesheet = new PIXI.Spritesheet(baseTexture, data);
spritesheet.parse((textures) => {
  // Got textures and they are cached!
});
```
See [here](http://pixijs.download/release/docs/PIXI.Spritesheet.html) for documentation.

**Comment by lebesnec** [comment]
Perfect ! thanks !
