### ISSUE TITLE
cacheAsBitmap & scaling parent containers

### ISSUE THREAD

**Issue by nicokruger** [pixijs/pixi.js#4640]
Hi there,

Perhaps I'm not quite understanding cacheAsBitmap, but as far as I'm aware the following should in theory work:

We use a container for our camera, we set the scaling on this so that we setup the scenegraph with world coordinates starting at (0,0), with the screen being (16,9) on a phone etc. This seemed like a good idea at the time.

However, this now seems to be causing issues with cacheAsBitmap. See the following pen: https://codepen.io/nicokruger/pen/goNdNW

As you can see from the pen, the sprite comes out blurry after cacheAsBitmap kicks in. If you change the scaleValue to = 1 at the top, everything works fine.

According to my (admittedly limited) understanding, cacheAsBitmap should work in this case, as the two scalings of sprite and container should cancel each other out.

Is this supposed to work? Or am I missing something, and we should change our coordinate system to be able to use cacheAsBitmap?

**Comment by nicokruger** [comment]
Here is a version that works:

https://codepen.io/nicokruger/pen/vpqVMR

The only difference is an additional parent container, with scale (1,1), and the the cacheAsBitmap is on that container instead of the inner container.

**Comment by ivanpopelyshev** [comment]
There's constant debate about whether container transform and alpha should be applied if container is a root of some rendering tree. It exists for all flash-like renderers.

**Comment by ivanpopelyshev** [comment]
Imagine that there are many operations in container and their order is constant. Currently its "transform, render" and transform is "position,rotation,scale,pivot" . If we change it, some other tests will fail and people will ask about new order of operations. And if we make it dynamic, code will be full of ifs and dynamic operations and hard to debug.

**Comment by nicokruger** [comment]
Thanks for the reply. I understand that a line has to be drawn somewhere. It's just strange that it displays correctly before cacheAsBitmap (the scale cancels out), and then suddenly after cacheAsBitmap it breaks.

So we should just try go with version #2 then? With the additional dummy container? So cacheAsBitmap is not taking the first container's scale into account? Is that what's happening here?

**Comment by nicokruger** [comment]
Check this out as well:

https://codepen.io/nicokruger/pen/VyJqyw

So if I scale up, and then down, it works again. It's just with scale down/scale up combination that it doesn't work.

It does look like something fishy is going on?

**Comment by ivanpopelyshev** [comment]
Yeah, because you scale up, and cached bunny size is 10 times by dimensions, 100 times by area. If you set scale=10 you'll see that.

The behaviour is defined here:

https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Transform.js#L97
https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js#L319
https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js#L343
https://github.com/pixijs/pixi.js/blob/dev/src/extras/cacheAsBitmap.js#L153

**Comment by nicokruger** [comment]
Thanks for helping here. I understand a little bit more now the tradeoffs etc. involved here.
