### ISSUE TITLE
Get visible part of out-of-bounds image

### ISSUE THREAD

**Issue by rusomirt** [pixijs/pixi.js#4645]
My Pixi app is an image viewer. 
It contains an image in Сontainer which is shiftable so it can exceed app bounds (i.e. only part of image is visible).
I need to get only visible part of image for further processing (print or save to file).
Is there any way to do it in Pixi?
![default](https://user-images.githubusercontent.com/17779217/35510751-8dc85862-0523-11e8-85aa-65a6f02c9906.png)

**Comment by ivanpopelyshev** [comment]
Need more details. What do you need to extract?

```js
var texture = renderer.generateTexture(stage, undefined, undefined, renderer.screen);

var exportCanvas= renderer.extract.canvas(texture);

texture.destroy(true);
```

**Comment by rusomirt** [comment]
`generateTexture()` helped me, thank you!

One note: initially I used Pixi 4.5.5 and last parameter ('region') of `generateTexture()` didn't work. Resulting texture always had full size of passed container.
After updating to Pixi 4.7.0 all have become OK.

**Comment by ivanpopelyshev** [comment]
We have a PR that adds `region` to all extract functions, so you wont have to generate the texture manually in future versions.
