### ISSUE TITLE
need FORCE_NATIVE for `OES_vertex_array_object`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4646]
in some android devices,   when use
```
gl.getExtension("OES_vertex_array_object")
```
We could get OESVAO Object, but it has many issues , can't run correctly.

So I think we need a setting value to force `don't use getExtension vao`

**Comment by themoonrat** [comment]
@finscn is this still something to think about for v5?

**Comment by ivanpopelyshev** [comment]
i believe we've found the bug with indexBuffer somewhere in the end of 2017 that fixed it.
