### ISSUE TITLE
About GLSL_SINGLE_SETTERS on Android.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4647]
in PIXI (pixi-gl-core) ,  the code: 
```
var GLSL_SINGLE_SETTERS = {
... ...
    sampler2D: function setSingleSampler2D(gl, location, value) {
      console.log(Array.isArray(value), value)
      gl.uniform1i(location, value);
    },
... ...
}

```

In some android , `Array.isArray(value)` is always true.
I have to use `gl.uniform1i(location, value[0]);`

**Comment by finscn** [comment]
I think the key point of this issue is : 
```
function generateSetter(name, uniform)
{
    return function(value) {
        this.data[name].value = value;
        var location = this.data[name].location;
        if (uniform.size === 1)
        {
            GLSL_SINGLE_SETTERS[uniform.type](this.gl, location, value);
        }
        else
        {
            // glslSetArray(gl, location, type, value) {
            GLSL_ARRAY_SETTERS[uniform.type](this.gl, location, value);
        }
    };
}
```

When `(uniform.size === 1` , but `value` is an array , there will be this issue.

**Comment by themoonrat** [comment]
@finscn is this still something to think about for v5?

**Comment by finscn** [comment]
@themoonrat  , I haven't started learn v5.
So, I don't know.

But, I'm sure my PR https://github.com/pixijs/pixi-gl-core/pull/36 could solve this issue in v4.
