### ISSUE TITLE
Demo request

### ISSUE THREAD

**Issue by pennybuster** [pixijs/pixi.js#4650]
Hi everyone. Can you help me create a demo of a responsive pool water background animation?
I found this: https://jsfiddle.net/skibulk/m4fc0kn2/ but I don't know how to modify it to make it fullpage and responsive.
I would like to use this seamless texture: https://i.pinimg.com/originals/0e/98/9b/0e989bc5eae0aa4382e6ab07300b7b04.jpg
Thank you so much!!

**Comment by ivanpopelyshev** [comment]
That's pixi v4 example with displacement: http://pixijs.io/examples/#/filters/displacement-map.js

**Comment by pennybuster** [comment]
Thanks a lot!! I will try to implement it. I'm not much of a programmer.
