### ISSUE TITLE
Pixi InteractionManager Pointer Lock support

### ISSUE THREAD

**Issue by danecek099** [pixijs/pixi.js#4651]
Pixi doesn't update pointer possition after a pointerlockchange event. IS it going to be supported in future versions?

**Comment by themoonrat** [comment]
When pointer lock is enabled, .clientX and .clientY positions (what we use to identify the position of the pointer) are frozen. From the spec at https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API
```
When Pointer lock is enabled, the standard MouseEvent properties clientX, clientY, screenX, and screenY are held constant, as if the mouse is not moving. 
```
So, it's an interesting one. PointerLock is saying 'the mouse isn't moving'. So if it's not moving, then Pixi is doing the right thing in not updating the pointer position.

What is your opinion in what Pixi should do when pointer lock is enabled?

**Comment by danecek099** [comment]
It's true that if the pointer isn't moving, why should Pixi bother. But then the Sprite interaction events are unusable. In my opinion, Pixi should have some sort of API to the mousemove event's movementX/Y properties and a flag like "updateCursorPosOnLockedPointer" to enable interactions.

**Comment by djmisterjon** [comment]
i need this in v4
thanks
