### ISSUE TITLE
comment mistake in Matrix.js

### ISSUE THREAD

**Issue by koalaylj** [pixijs/pixi.js#4654]
the original comment for Matrix class
```javascript
/**
 * The PixiJS Matrix class as an object, which makes it a lot faster,
 * here is a representation of it :
 * | a | b | tx|
 * | c | d | ty|
 * | 0 | 0 | 1 |
 *
 * @class
 * @memberof PIXI
 */
```

according to the source code , I think the matrix should be like this(also same as canvas [transform](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform) api).
```javascript
/**
 * | a | c | tx|
 * | b | d | ty|
 * | 0 | 0 | 1 |
 */
```
and comment for constructor should be like this(b is x skew,c is y skew).
```javascript
/**
  * @param {number} [a=1] - x scale
  * @param {number} [b=0] - x skew
  * @param {number} [c=0] - y skew
  * @param {number} [d=1] - y scale
  * @param {number} [tx=0] - x translation
  * @param {number} [ty=0] - y translation
 */
```

**Comment by ivanpopelyshev** [comment]
Eagle eye!

!@#$ I notified Adobe about this mistake in i18n version of ActionScript docs but I didnt see that someone copied that into pixi :)

By the way, esotericsoftware.com really uses that order of elements :)  I hope they are the only one project that really implemented it across all of runtimes.

**Comment by ivanpopelyshev** [comment]
Feel free to make a PR against `dev`. And against `next` if you like. It'll be approved.

**Comment by koalaylj** [comment]
I have made a PR aginst `dev` and against `next`.

**Comment by ivanpopelyshev** [comment]
Thank you!
