### ISSUE TITLE
Changing pivot position of child graphics element - changes size of container

### ISSUE THREAD

**Issue by karaliunas** [pixijs/pixi.js#4657]
It's not an issue hopefully, but I just want to confirm this behavior because I couldn't find it in documentation (maybe documentation could be clearer on this point).
As stated in title, if a child is added to container and I change pivot location of child - somehow container becomes bigger proportionally (even if container is much bigger size than child already). I found this relationship by debugging code. Then I tried to change child pivot location before putting it into container and it worked as expected.

**Comment by ivanpopelyshev** [comment]
The only clearer can be more examples or the source code.

https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js#L343

The same behaviour as Adobe Flash.

Many people want different behaviour but there is no stable behaviour that can be shipped - no one made pixi plugins dedicated to that cause. 

Either you agree to Adobe Flash behaviour, either you code something, override width/height and bounds of your container and call it "MyContainer". May be you are the chosen one that will bring us new plugin that changes Container behaviour and satisfies many people.

**Comment by karaliunas** [comment]
Thanks for clarification @ivanpopelyshev . I don't want to change this logic, just to make it clear for others in the future. At least they can find it here.

**Comment by ivanpopelyshev** [comment]
Well, there's a way: v3 docs `Retrieves the bounds of the Container as a rectangle. The bounds calculation takes all visible children into consideration.` https://github.com/pixijs/pixi.js/blob/v3/src/core/display/Container.js#L405

But in v4 we removed `getBounds` in `Container` in favor of general implementation in `DisplayObject`

You can make PR to change description of getBounds in DisplayObject.
