### ISSUE TITLE
Text disappears when multiple filters are applied and using cacheAsBitmap

### ISSUE THREAD

**Issue by arthurmuchir** [pixijs/pixi.js#4659]
I got a problem (think a bug) with the last version of pixi (4.7.0)
When I use Text and apply a filter to his container, if the container already got a filter applied to it the text will disappear.

Here is a fiddle :
https://jsfiddle.net/avOff/7zwv63dh/3/

If you comment cacheAsBitmap or any of the filter it will work again.

Maybe related to #3901 ?

**Comment by ivanpopelyshev** [comment]
Sorry, no guarantees about combination of cacheAsBitmap and filters on the same element. You have to separate it into two elements. If the situation is the same, then its a bug. Otherwise, undefined behaviour.

**Comment by themoonrat** [comment]
@arthurmuchir closing this down as I believe ivan's advice has you answered :)
