### ISSUE TITLE
pointerover/pointerout not firing on mobile

### ISSUE THREAD

**Issue by NemoStein** [pixijs/pixi.js#4661]
I'm not sure if this is by design or not, but `pointerover` and `pointerout` won't fire on mobile, but works as expected on desktop.

If this is working as intended, is there a workaround?

**Comment by bigtimebuddy** [comment]
Please provide more information, specifically what mobile platform (and version) and what version of PixiJS.

**Comment by NemoStein** [comment]
I'm running PIXI 4.7.0 in Chrome 64 on Android 5.0.1 and in Chrome 65 on Windows 10.
It works on the desktop, but fails on device and Chrome device simulation.

Here is a fiddle: https://jsfiddle.net/t3xqd2bt/

**Comment by themoonrat** [comment]
pointerover / pointerout are for when a mouse cursor is positioned over the top of, and then away from, a display object. 

Mobile devices do not have a pointer, and therefore cannot emit these events. 
The Chrome simulation is showing you a circle of the area that would simulate being touched if you clicked your mouse, but does not acting like an actual mouse cursor.

**Comment by NemoStein** [comment]
Indeed, mobile doesn't have a cursor, but it does have a pointer.
What I'd expect is the over/out to be dispatched while swiping (eg.: while dragging some Sprite).

**Comment by themoonrat** [comment]
pointerover / pointerout events are not emitted by the interaction manager.

http://pixijs.download/dev/docs/interaction_InteractionManager.js.html#line487
http://pixijs.download/dev/docs/interaction_InteractionManager.js.html#line854

pointermove event _is_ emitted for touch, however, which I believe is what you require

**Comment by themoonrat** [comment]
Closing as I think you have your answer :)
