### ISSUE TITLE
[Question] way of computing matrix transform in CanvasMeshRender.js's _renderDrawTriangle function.

### ISSUE THREAD

**Issue by koalaylj** [pixijs/pixi.js#4663]
Should I ask question here?
I am reading the source code of CanvasMeshRender.js and have a question about the way of computing matrix transform.

Code in  ` _renderDrawTriangle(mesh, index0, index1, index2)`function from about line 220 to 235:

```javascript
// Compute matrix transform
const delta = (u0 * v1) + (v0 * u2) + (u1 * v2) - (v1 * u2) - (v0 * u1) - (u0 * v2);
const deltaA = (x0 * v1) + (v0 * x2) + (x1 * v2) - (v1 * x2) - (v0 * x1) - (x0 * v2);
const deltaB = (u0 * x1) + (x0 * u2) + (u1 * x2) - (x1 * u2) - (x0 * u1) - (u0 * x2);
const deltaC = (u0 * v1 * x2) + (v0 * x1 * u2) + (x0 * u1 * v2) - (x0 * v1 * u2) - (v0 * u1 * x2) - (u0 * x1 * v2);
const deltaD = (y0 * v1) + (v0 * y2) + (y1 * v2) - (v1 * y2) - (v0 * y1) - (y0 * v2);
const deltaE = (u0 * y1) + (y0 * u2) + (u1 * y2) - (y1 * u2) - (y0 * u1) - (u0 * y2);
const deltaF = (u0 * v1 * y2) + (v0 * y1 * u2) + (y0 * u1 * v2) - (y0 * v1 * u2) - (v0 * u1 * y2) - (u0 * y1 * v2);

context.transform(
    deltaA / delta,
    deltaD / delta,
    deltaB / delta,
    deltaE / delta,
    deltaC / delta,
    deltaF / delta
);
```
Question 1 : `Does The formula should like this?`

```javascript
/**
 mapping uv coordinates to canvas coordinates
| u0 | v0 | 1 |     | a | d | 0 |    | x0 | y0 | 0 |
| u1 | v1 | 1 |  *  | b | e | 0 | =  | x1 | y1 | 0 |
| u2 | v2 | 1 |     | c | f | 1 |    | x2 | y2 | 1 |
 */
```

And then we can use  [Cramer's rule](https://en.wikipedia.org/wiki/Cramer&#39;s_rule ) to work out the value of transform matrix 

```javascript
/**
  | a | d | 0 |
  | b | e | 0 |
  | c | f | 1 |

 a = deltaA / delta, 
 b = deltaB / delta,
 ....... 
 f = deltaF /delta.

 */
```

Question 2  :  Why we use 

```javascript
context.transform(
    deltaA / delta,
    deltaD / delta,
    deltaB / delta,
    deltaE / delta,
    deltaC / delta,
    deltaF / delta
);
```

in stead of using

```javascript
context.transform(
    deltaA / delta,
    deltaB / delta,
    deltaC / delta,
    deltaD / delta,
    deltaE / delta,
    deltaF / delta
);
```

I have a guess about question 2. the transform matrix in canvas should be like this:

```javascript
/** 
 | a | c | e |
 | b | d | f |
 | 0 | 0 | 1 |
*/
```

So  we should transpose the matrix that got in Question 1 to match the canvas `transform(a,b,c,d,e,f)` API ?

Postfix:

I have been struggled for many days about this. Can someone tell me where can I get more knowledge about these(texture mapping using HTML5 Canvas and mesh in canvas)?

THANKS guys. my English is not good , I hope I have made the question clear.

**Comment by ivanpopelyshev** [comment]
transform matrix in canvas is

/**
| a | c | tx |
| b | d | ty|
| 0 | 0 | 1 |
**/

You just tried cramer on degenerate matrix with zero row,

**Comment by koalaylj** [comment]
I have fixed the degenerate matrix problem .
So the matrices used in question 1(Cramer's rule ) is by rows , but canvas `tranform()` use matrices by cols(same as webgl?), is that right? 
For those reason  we need transpose the matrices
```javascript
/**
  | a | d | 0 |
  | b | e | 0 |
  | c | f  | 1 |

 a = deltaA / delta, 
 b = deltaB / delta,
 ....... 
 f = deltaF /delta.
 */
```
to
```javascript
/** 
 | a | c | e |
 | b | d | f |
 | 0 | 0 | 1 |
*/
```

then call `context.transform(transposed transform matrices)` function?

**Comment by ivanpopelyshev** [comment]
yes, the form I mentioned is for math equations. WebGL and canvas work with transposed matrices.

**Comment by koalaylj** [comment]
Got it , Thanks!

**Comment by ivanpopelyshev** [comment]
Good luck! Its rare to have math questions here. If you want more advanced things, look at https://github.com/pixijs/pixi-projection :) Its not 3d, just advanced 2d.
