### ISSUE TITLE
sprite in ParticleContainer can not animate alpha value

### ISSUE THREAD

**Issue by rockmandash** [pixijs/pixi.js#4664]
sprite in ParticleContainer can not animate alpha value
I have set 
`{ alpha: true }`
It can be 0 or 1, but can not be 0.5, 0.6 etc...............
Please Help.
Thank you very much!!!!!

**Comment by ivanpopelyshev** [comment]
You have to change alpha of elements inside ParticleContainer or its own alpha. Options alpha is true when you want alpha fields of elements be dynamic.

**Comment by rockmandash** [comment]
so hard 😫​😫​😫​😫​😫​😫​😫​😫​😫​😫​😫​

**Comment by ivanpopelyshev** [comment]
I take it, you want one ALPHA property that does everything. Unfortunately, this place of pixi is not written by telepaths, you have to read docs and sources to understand what means
1. alpha of container
2. alpha of element
3. options "alpha" aka "tint"

**Comment by rockmandash** [comment]
I found a much more stunning things!
I wan't able to adjust alpha, so I split my snow assets(I wan making snow rain) into 10 png.
like this
png10 -> opacity 10%
png20 -> opacity 20%
png30 -> opacity 30%

However, the sprites in ParticleContainer only shows alpha 0, 1.
Truely Sad ! 😩​😩​😩​😩​😩​😩​😩​😩​😩​😩​😩​😩​

**Comment by ivanpopelyshev** [comment]
Its not about alpha, you just used several textures in ParticleContainer, and it can show sprites only from same atlas. 

If you want a performance boost,m you have to satisfy all the conditions or else optimization will crash.

**Comment by rockmandash** [comment]
@ivanpopelyshev I success !
But I changed a lot, don't know what is really going on.
So my conclusion is, child in particleContainer can change alpha XDDDD
😀​😀​😀​😀​😀​😀​😀​😀​😀​😀​😀​😀​😀​😀​
