### ISSUE TITLE
click the link once,but triggered many times

### ISSUE THREAD

**Issue by qtttttttttting** [pixijs/pixi.js#4665]
I use pixi and d3 in my project. When in the layout process, nodes and links are being cleared and redrawn constantly. In the tick function,  I bind the hitArea for every link. When click the link, the callback function is triggered many times(almost equal to tick times).

**Comment by ivanpopelyshev** [comment]
Which version of pixi is it?

**Comment by qtttttttttting** [comment]
https://jsfiddle.net/1gvhxhg3/2/

**Comment by qtttttttttting** [comment]
I use 4.7.0 .
Thank you ~

**Comment by qtttttttttting** [comment]
update in 
https://jsfiddle.net/qtttttttttting/1gvhxhg3/3/

**Comment by themoonrat** [comment]
@qtttttttttting Did this stay an issue for you or were you able to resolve this?
