### ISSUE TITLE
TilingSprite not Repeating 

### ISSUE THREAD

**Issue by mtderryberry** [pixijs/pixi.js#4666]
Hello,

I'm trying to use TilingSprites to create a footprint path of indeterminate length. I have an image of a set of footprints that I want to repeat to make a path. I am using the following but cannot get it to repeat:

```
let pixiTexture = PIXI.Texture.fromFrame(footprint.png);
let sprite = new PIXI.extras.TilingSprite(pixiTexture);
myContainer.addChild(sprite);
```

My image is 64x64 so should be working since it is power-of-two. Any help as to why this isn't repeating would be greatly appreciated!

**Comment by Cpin0312** [comment]
Sorry that i not full understanding your question,
http://pixijs.io/examples/#/basics/tiling-sprite.js

is this link able to help you?

**Comment by Cpin0312** [comment]
Have you add this codes?

`app.ticker.add(function() {

    count += 0.005;

    tilingSprite.tileScale.x = 2 + Math.sin(count);
    tilingSprite.tileScale.y = 2 + Math.cos(count);

    tilingSprite.tilePosition.x += 1;
    tilingSprite.tilePosition.y += 1;
});`

you image would not been move without this.

**Comment by mtderryberry** [comment]
Well I don't want it to move. That code is just used for the animation. The original image in that demo though is just four squares. However, it is tiled over the entirety of the stage, which is the aspect of TilingSprite that I am trying to accomplish. I don't want it to move and change size, just to be statically tiled over the size of a container.

**Comment by Cpin0312** [comment]
if you want do have a same effect with that link without moving, 
`
var tilingSprite = new PIXI.extras.TilingSprite(
    texture,
    your_wish.width,
    your_wish.height
);`

if this also cannot solve your problem, maybe you need to wait for other answer.Sorry(_ _)

**Comment by ivanpopelyshev** [comment]
TilingSprite works even without webgl repeat and pow2 texture. 

You've  just posted "TilingSprite is not working for me" without any other details. How can we help you?

**Comment by mtderryberry** [comment]
I actually just figured out the issue. The Container I was trying to add the TilingSprite to was a ParticleContainer. I guess it doesn't work with those. Switching to PIXI.Container caused the repeating to function as intended. Thanks!
