### ISSUE TITLE
[BUG] ParticleContainer can only be renderered in one renderer

### ISSUE THREAD

**Issue by manubb** [pixijs/pixi.js#4668]
I am using double buffering and i render a particleContainer once in a renderer, once in another renderer.
The particleContainer is always correctly displayed in the first renderer and always invisble in second renderer.
This can be seen in this [demo](https://manubb.github.io/Leaflet.PixiOverlay/particles.html). You just have to translate or zoom the map to see that the markers are displayed, invisible, displayed, invisible,...

If i patch `ParticleContainer.prototype.renderWebGL` this way:
```js
PIXI.particles.ParticleContainer.prototype.renderWebGL = function(renderer) {
  if (!this.visible || this.worldAlpha <= 0 || !this.children.length || !this.renderable)
    {
        return;
    }
    if (!this.baseTexture)
    {
        this.baseTexture = this.children[0]._texture.baseTexture;

    }
    // patch begin
    this.onChildrenChange(0);

    // if (!this.baseTexture.hasLoaded)
    //     {
    //         this.baseTexture.once('update', () => this.onChildrenChange(0));
    //     }

    // patch end 
    renderer.setObjectRenderer(renderer.plugins.particle);
    renderer.plugins.particle.render(this);
};
```
the problem disappears like in this [demo](https://manubb.github.io/Leaflet.PixiOverlay/particles-patched.html). Apparently, the texture is not usable in second renderer and needs to be uploaded.
I'm not very happy with this solution. Do you think another approach is possible?

**Comment by ivanpopelyshev** [comment]
Yep, that's why:

https://github.com/pixijs/pixi.js/blob/dev/src/particles/ParticleContainer.js#L94

https://github.com/pixijs/pixi.js/blob/dev/src/particles/webgl/ParticleRenderer.js#L191

It can be fixed but I'm so lazy right now :)

**Comment by manubb** [comment]
Thank you @ivanpopelyshev 
I'm             sx      No hurry

**Comment by manubb** [comment]
I didn't see your question: i'm drawing alternatively in two renderers to avoid terrible flickering in iOS (see #4032).

**Comment by ivanpopelyshev** [comment]
oh god

**Comment by manubb** [comment]
I can try to PR this but i need some help. 
Should i keep track of the previous renderer and check if it is the same as the current one?
Then if `current !== previous`, trigger `this.onChildrenChange(0)` ?

**Comment by ivanpopelyshev** [comment]
I'll do the PR, don't worry :) The idea is that we need to remember some kind of updateID for every buffer, not just "the smallest changed buffer". We store those id's in renderer-specific part too

**Comment by ivanpopelyshev** [comment]
Try this one: http://pixijs.download/dev-particle-two-renderers/pixi.js 
It takes a couple of minutes to build a branch.

**Comment by manubb** [comment]
I confirm that this build fixes the problem.
Great!
