### ISSUE TITLE
renderer.extract.pixels returns wrong values for sprite if a parent is not at 0,0

### ISSUE THREAD

**Issue by ascii-husky** [pixijs/pixi.js#4670]
Please see [jsFiddle](https://jsfiddle.net/ASCII_HUSKY/7dt7fpsv/27/)

without line 6 the correct data is returned

**Comment by ivanpopelyshev** [comment]
Pixi generateTexture() and extract methods are skipping updateTransform by default. I dont know whether its intended behaviour or a bug, I believe you have to remove element from parent and attach it after extract.

**Comment by ivanpopelyshev** [comment]
I've added tests in my PR #4632 and I confirm that's a real bug of extract. Don't know which one though.
