### ISSUE TITLE
How to prevent initial black canvas?

### ISSUE THREAD

**Issue by rockmandash** [pixijs/pixi.js#4671]
How to prevent initial black canvas?
Setting opacity 0 can fix it, but when is the best time to set opacity to 1?
Is there anything similar to onload event when everything is ready?
Thank you very much!

**Comment by Cristy94** [comment]
You can set the canvas background color to transparent I think.

**Comment by rockmandash** [comment]
@Cristy94 But what if I want background color?
My solution right now is to fade in whole canvas in two seconds.

**Comment by ivanpopelyshev** [comment]
I still dont understand what do you want to do.

**Comment by rockmandash** [comment]
Here I simulate snow raining, how can I detect the whole process is done?
If I don't set canvas to opacity 0, then fadeIn in several seconds, there will be and initial black canvas flash over screen
```

this.snowApp = new PIXI.Application(300, 300, {
  backgroundColor: `0x123456`
});

let snowParticleContainer = new PIXI.particles.ParticleContainer(
  100,
  {
    rotation: true,
    alpha: true
  },
  100,
  false
);

this.allSnow = [];

times(100, () => {
  let snowSprite = new PIXI.Sprite.fromImage('./static/snow.png');
  snowSprite.anchor.set(0.5);
  snowSprite.x = random(0, 300, true);
  snowSprite.y = -10;

  snowSprite.alpha = 0.2;
  snowParticleContainer.addChild(snowSprite);

  this.allSnow.push(snowSprite);
});
this.snowApp.stage.addChild(snowParticleContainer);

this.refs.SnowRainPixi.appendChild(this.snowApp.view);
this.snowApp.start();

```
