### ISSUE TITLE
'mouseover' and 'mouseout' events not firing without mouse movement

### ISSUE THREAD

**Issue by funkybjorn** [pixijs/pixi.js#4672]
Hello,

Right now display objects only fire 'mouseover' and 'mouseout' events if the cursor is moved. However, if the cursor is not moving, and an object's transform is updated to appear behind the cursor, or disappear from behind the cursor (specifically rotation, scale, position, visible), the 'mouseover' and 'mouseout' events are not fired, which would be a very important feature to have.

Would this be possible to implement? It would be very important for our project. I can elaborate on usage if requested. Thanks!

**Comment by themoonrat** [comment]
Hmmm, http://pixijs.download/dev/docs/interaction_InteractionManager.js.html#line844 seems to indicate that there was an attempt to have this working. 

Could you provide a fiddle with this please?

**Comment by funkybjorn** [comment]
Here ya go!
[JSFiddle Demonstration](https://jsfiddle.net/funkybjorn/ccqz6n8a/3/)

**Comment by YahorPadlucki** [comment]
Looked at this issue...
In `InteractionManager.processInteractive` invisible object is completely ignored:
` if (!displayObject || !displayObject.visible)
        {
            return false;
        }`
so `processPointerOverOut` doesn't handle it...
Previous state should be somehow stored? Didn't find any easy solution for this (

**Comment by sonofthort** [comment]
Just curious if there was ever a resolution to this? I still notice this behavior v5.2.0.

**Comment by funkybjorn** [comment]
There wasn't any resolution to my knowledge. I got around it by merely manipulating the ticker to start/stop any time I knew an object  might appear/disappear. Would have to be customized for your project's needs. Check out the ticker checkbox in the jsfiddle.

**Comment by sonofthort** [comment]
Thank you. I didn't notice the "Ticker Toggle" at first. Nice workaround!
