### ISSUE TITLE
Textbox: Calculation of size incorrect when using dropshadow- result: shadow cutted off

### ISSUE THREAD

**Issue by Vaganza** [pixijs/pixi.js#4673]
Hi,
if you take the the text example ([http://pixijs.io/examples/#/basics/text.js](http://pixijs.io/examples/#/basics/text.js)) you see at the right edge of the first line, at the letter "**f**" that the _dropshadow is partly cut away_.
If you change the dropshadow values of _blur, angle_ and _distance_ you see the same behavior at the left and top edge. Only to the bottom there seems to be no problem, even with extreme values, see below.

cut away **RIGHT**:
```
dropShadowAngle: Math.PI / 6,
dropShadowDistance: 12,
```

cut away **LEFT**:
```
dropShadowAngle: Math.PI / 1,
dropShadowDistance: 30,
```

cut away **TOP**:
```
dropShadowAngle: Math.PI / -2,
dropShadowDistance: 30,
```

no issue **BOTTOM**:
```
dropShadowAngle: Math.PI / 2,
dropShadowDistance: 182,
```
Behavior tested on Windows 10 with:
Chrome: 63.0.3239.132 - 64 Bit
Firefox: 58.0.2 - 32 Bit
Internet Explorer: 11.125.16299.0
Microsoft Edge: 41.16299.15.0 (has also other proplems... :D )
Opera: 51.0.2830.26 - 64 Bit

Thanks a lot for your support.

**Comment by ivanpopelyshev** [comment]
Related : #4550

**Comment by themoonrat** [comment]
The calculations are trying to work out text width and height can never be perfect by the nature of text; we just take a best guess. In this case, adding 'padding' would stop any cutoffs
