### ISSUE TITLE
sprite.texture.frame change hides the sprite

### ISSUE THREAD

**Issue by AlexandrKrivosheev** [pixijs/pixi.js#4674]
Here is a pen https://codepen.io/anon/pen/wyrbJY?editors=0010

When I change the frame
`sprite.texture.frame = new PIXI.Rectangle(0, 100, sprite.width, sprite.height - 100)`
sprite just hides. But i want to show bottom part of sprite

**Comment by ivanpopelyshev** [comment]
Because there's no width or height before image is ready. Use pixi loader to wait before everything loads,  or specify width height manually.
