### ISSUE TITLE
clearRenderTexture is not implemented in CanvasRenderer

### ISSUE THREAD

**Issue by Huararanga** [pixijs/pixi.js#4677]
clearRenderTexture method was recently added to WebGLRenderer (#3647), but it is still missing in CanvasRenderer.
Could you please add clearRenderTexture method to CanvasRenderer?

I am currently using this polyfill which does not support color fill
`if (!PIXI.CanvasRenderer.prototype.clearRenderTexture) {
		PIXI.CanvasRenderer.prototype.clearRenderTexture = function(renderTexture) {
			const baseTexture = renderTexture.baseTexture;
			const context = baseTexture._canvasRenderTarget.context;
			context.clearRect(0, 0, baseTexture.width, baseTexture.height);
		};
	}`

Thanks

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out. @finscn: want to add this?

**Comment by finscn** [comment]
In fact , I don't care about canvas2d , so , you're the boss :)

**Comment by Huararanga** [comment]
I found, that the baseTexture could be sometimes null. Needs to be checked before context is acquired

**Comment by ivanpopelyshev** [comment]
> I found, that the baseTexture could be sometimes null. Needs to be checked before context is acquired

Its a bug, then.

**Comment by Huararanga** [comment]
I am using RenderTextures so the null baseTexture issue will be probably connected with it, since it could take time to create RenderTexture

**Comment by themoonrat** [comment]
@Huararanga have you had a chance to take a look at submitting a PR for this please? Would be much appreciated!
