### ISSUE TITLE
Resolution issue on custom filter on iOS Mobile Devices

### ISSUE THREAD

**Issue by Alfredahoy** [pixijs/pixi.js#4679]
Hi there,

I'm still a beginner with pixiJS, but I've been having this issue where I've got this custom filter running and it performs fine on desktop, but when I open it up in Google Chrome on an iPad or my iPhone, the resolution becomes incredibly pixelated (I don't think it runs at all on android).

This is what it's meant to look like:

<img width="1419" alt="screen shot 2018-02-19 at 2 05 12 pm" src="https://user-images.githubusercontent.com/8272613/36359272-268ffe50-157e-11e8-9902-9cced93404a5.png">

and this is what it looks like on my iPhone: 

![img_5968](https://user-images.githubusercontent.com/8272613/36358892-f945c6c2-1579-11e8-9280-22630a0bae04.jpg)

I've got a codepen of it running here: https://codepen.io/alfredahoy/pen/PQWaKG

If anyone could pinpoint what's causing this, that'd be appreciated.

Cheers!

**Comment by ivanpopelyshev** [comment]
try highp instead of mediump

**Comment by Alfredahoy** [comment]
Dude, thanks so much man!
