### ISSUE TITLE
Add a layout engine like yoga

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4684]
IMHO issue #3482 should be opened again, I think that the question by @endel  has been overlooked. 
Add support for yoga would be awesome. I think that pixijs actually needs a layout engine and yoga could be the best option since its the one under react. 

According to Flipboard's team it took a very little effort to put yoga in top of their react-canvas library. Maybe this could be the case?

**Comment by ivanpopelyshev** [comment]
Go on, make a plugin :)

**Comment by DavidGOrtega** [comment]
Ok ;)

**Comment by endel** [comment]
@DavidGOrtega if you happen to start this plugin I'm willing to contribute.

**Comment by Icemic** [comment]
In fact, I've done most of it for my game framework (based on PixiJS). Maybe I should make it a independent plugin...

https://github.com/avgjs/avg-core/blob/feature/state_tree/packages/avg-plugin-flexlayout/src/wrapper.js

**Comment by DavidGOrtega** [comment]
@endel I'm definetely looking at it. However we are going to need a new DisplayObject implementation.

@Icemic thanks for your link, definetely I'm reading  it! Do you have a flexbox pixi container? My goal is able to create containers that you can just add Sprites into it and they are going to be positioned by them self and their dimensions.

**Comment by DavidGOrtega** [comment]
Hi guys,

now I'm attacking this problem in my app. I have to say that integrating Yoga with Pixie and Zynga Scroller, taking aside minor issues with Yoga docs, has been very easy.

I have replicated the Zynga demo with pixi and then I put Yoga.

![](https://dzwonsemrish7.cloudfront.net/items/461B4109470A3N0V333P/Screen%20Recording%202018-06-09%20at%2007.44.47.35%20PM.gif)
