### ISSUE TITLE
Sprite height does not reflect children text?

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4685]
```
class SpriteLabel extends PIXI.Sprite
{
    constructor(opts)
    {
        super();

        this.txt = new PIXI.Text('text here',  {fontFamily : 'Arial', fontSize: 11, fill : 0x000000,});
        this.addChild(this.txt);
    }
    
    set text(val)
    {
        this.txt.text   = val;
    }
    
    get text()
    {
        return this.txt.text;
    }
}

var lbl = new SpriteLabel();
console.log( lbl.height ); //prints 1 
```

height is 1 instead of 11 ??

**Comment by ivanpopelyshev** [comment]
because you extend `PIXI.Sprite` and it does have special rule regarding width and height: its width and height of its Texture, and you have EMPTY texture there. 

I know in Flash people extend Sprite, but here you can extend Container and that'll be ok :)

**Comment by DavidGOrtega** [comment]
> because you extend PIXI.Sprite

and I have to... there are some features in the Sprite that I will need that the container does not offer to me... Sprite being a DisplayObject should update it's size depending on the objects contained...

**Comment by themoonrat** [comment]
Text is lazily updated. So, because you haven't rendered the text yet, the texture for it hasn't been generated, thus your dimensions are off. 
You can call updateText method manually to update the texture there and then. That might help update the dimensions despite no render?

**Comment by ivanpopelyshev** [comment]
> there are some features in the Sprite that I will need that the container does not offer to me... 

use `getLocalBounds().width * this.scale.x ` or just `getBounds()`. `width` and `height` props in Container and Sprite are shortcuts, one-liners.

**Comment by DavidGOrtega** [comment]
> Text is lazily updated. 

In reality this issue occurs with any class extended from Sprite that use composition , I mean addChild to stage with no texture involved, don't have to be text, can be other Sprites.

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev thanks for the help!

> PixiJS is not a black box.

I know! I was just only pointing what I consider a bug, to me a DisplayObject should be aware of its size. In fact there are some issues also setting the width and height of the Container or the sprite and how scale it's content... but I will review that in the issue regarding the possibility of adding yoga as a layout engine.

**Comment by ivanpopelyshev** [comment]
Yep, that's the problem with Container and DisplayObject - there are too many ways to implement width height and scaling. Adding layout there will lead to different complexity and we dont need it in the core of open-source renderer.

There's good chinese UI project that supports phaser pixi and other engines/renderers, I forgot its name :(

**Comment by DavidGOrtega** [comment]
> There's good chinese UI project that supports phaser pixi and other engines/renderers, I forgot its name :(

http://en.fairygui.com/ maybe this?

>

**Comment by ivanpopelyshev** [comment]
Yes, that one :)

**Comment by ivanpopelyshev** [comment]
I have several projects that im helping with and no one needs yoga there, I dont know if other persons in core team use it. I guess, you have to do it yourself. I can help with reviews :)

**Comment by themoonrat** [comment]
Closing @DavidGOrtega as I think the original question has been answered :)
