### ISSUE TITLE
hitArea on PIXI polygon is not working

### ISSUE THREAD

**Issue by vk207** [pixijs/pixi.js#4689]
```js
var coords = data[0].map(function (point) {
  return new PIXI.Point(point[0], point[1]); 
});
var drawing = new PIXI.Polygon(coords);
drawing.hitArea = new PIXI.Polygon(coords);
drawing.interactive = true;
drawing.buttonMode = true;
pixiContainer.beginFill(color);
pixiContainer.drawPolygon(drawing);
```
Polygon is drawing but couldnt hit on hitarea 
Checked Click and mousedwon ...
Or is there any issues in my code ? 
Please help me ...

**Comment by ivanpopelyshev** [comment]
It should work. Make a fiddle.

**Comment by bigtimebuddy** [comment]
The problem looks like in your code a PIXI.Polygon is not a display object and is not interactive. Make a couple tweaks here:
```js
var coords = data[0].map(function (point) {
  return new PIXI.Point(point[0], point[1]); 
});
var polygon = new PIXI.Polygon(coords);
var drawing = new PIXI.Graphics();
drawing.hitArea = polygon;
drawing.interactive = true;
drawing.buttonMode = true;
drawing.beginFill(color);
drawing.drawPolygon(drawing);
```

**Comment by vk207** [comment]
@ivanpopelyshev  , @bigtimebuddy   Thanks for the quick reply

@bigtimebuddy let me implement your code

**Comment by vk207** [comment]
@bigtimebuddy 
i think we dont need a hitarea if we drawing polygon using drawing object and its working events directly on the drawing object  👍  . let me check the speed of loading of its 50K polygons ;)

**Comment by ivanpopelyshev** [comment]
IF you create 50k DisplayObject's that'll be a problem. Put all polygons into one graphics, or in multiple.

**Comment by vk207** [comment]
Im not using display objects.  Only adding graphic objects to an pixiConatiner.  Actaully i am on PixiLeafletOverlay  :)

**Comment by themoonrat** [comment]
Closing as I think we've got this one answered :)
