### ISSUE TITLE
Semi-transparent edges of blurred sprite

### ISSUE THREAD

**Issue by jaccunio** [pixijs/pixi.js#4690]
I'm trying to show a fullscreen sprite with high blur radius.
I've noticed that the bigger the blur radius, the more transparent the edges of the sprite become, please see attached image. I've played with custom padding in the filter, but it didn't help.
(All the images I use are po2)
This problem is known in After Effects, they solved it by providing an option to "repeat edge pixels".

![blur60](https://user-images.githubusercontent.com/1387170/36553952-a80efdb8-17f5-11e8-8700-41b2a60078d2.png)

**Comment by GoodBoyDigital** [comment]
Hey ya! Got a fix for this in the works for v5 :) hold tight..

**Comment by jaccunio** [comment]
@GoodBoyDigital Is there a way to make this work in v4?
My intuition tells me that it has something to do with clamping the texture coordinates so that it doesn't read pixels outside the texture (but my opengl knowledge isn't good enough to actually test that hypothesis)

**Comment by jaccunio** [comment]
I actually fixed it myself.
For posterity: follow this https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters#bleeding-problem and use `filterClamp` to clamp your coordinates

**Comment by ivanpopelyshev** [comment]
@jaccunio I'm late, I just wanted to suggest to read my doc, but you did it on your own :)
