### ISSUE TITLE
High GPU Usage

### ISSUE THREAD

**Issue by savage-na** [pixijs/pixi.js#4691]
Hi,

I am experiencing incredibly high GPU usage on my PIXI implementation.

It's not my GC, because I generally run a low % on most websites with an implementation of PIXI. 

However with the below code I run between 50% and 80% of my GPU constantly.
Am I missing a crucial element in my code?

```js
let app = new PIXI.Application({ 
    width: 200,         // default: 800
    height: 200,        // default: 600
    antialias: true,    // default: false
    transparent: true, // default: false
    resolution: 1,       // default: 1
  });
document.body.appendChild(app.view);

app.renderer.view.style.position = "absolute";
app.renderer.view.style.display = "block";
app.renderer.autoResize = true;
app.renderer.resize(window.innerWidth, window.innerHeight);

let target = new PIXI.Graphics();
let targetx = 1030;
let targety = 768;

target.lineStyle(2,0xFFFFFF,1);
target.drawCircle(targetx, targety,5);
target.endFill();

target.lineStyle(2,0xFFFFFF,1);
target.drawCircle(targetx, targety,10);
target.endFill();

target.lineStyle(1,0xFFFFFF,1);
target.drawCircle(targetx, targety,15);
target.endFill();

target.filters = [
    new PIXI.filters.GlowFilter(10, 2, 0, 0x00c9fb, 0.5)
];

app.stage.addChild(target);
```

**Comment by ivanpopelyshev** [comment]
MacOS, retina? turn antialias off, plug in power cable.

**Comment by themoonrat** [comment]
Hi @savage-na - Did you work out what the performance drain was?

**Comment by zhsisusie** [comment]
hi, i have the same problem,  did you solve this problem

**Comment by englercj** [comment]
How do you measure "GPU usage"?

**Comment by macguffin** [comment]
That's because if you disable hardware acceleration you will be using the canvas renderer therefore you see a drop in performance

**Comment by darren-dev** [comment]
@macguffin absolutely, just worthwhile noting :) Another 'duh' point, but worthy to note, is if you turn off AntiAliasing then GPU usage decreases (albeit marginally)

**Comment by englercj** [comment]
How big is innerWidth/innerHeight? Do you have a running example that reproduces the issue?
