### ISSUE TITLE
Graphic looks different on CanvasRenderer and WebGLRenderer

### ISSUE THREAD

**Issue by dentez** [pixijs/pixi.js#4693]
When I try to draw a graphic (polygon) with some kind of "invalid data", for example an array of points that ends with two points that have the same value, or when the distance of two points is smaller than the lineWidth, the image displayed by CanvasRenderer is different than the one generated by WebGLRenderer.

Here is a sample when the distance of two points is smaller than the lineWidth and with an incorrect line (last point should be inside the "generated line"): [WebGLRenderer displays a very strange line](https://jsfiddle.net/8qco9pw0/3/)

Here is a sample when there are 2 points with the same values (line ends with 2 points in the same position): [WebGLRenderer doesn't display any data](https://jsfiddle.net/kh0gxw2c/) 

I would like to know, even though the points are invalids, why in those situations the WebGLRenderer doesn't display the graphic like CanvasRenderer, because in my opinion the CanvasRenderer is showing the expected behavior.

**Comment by ivanpopelyshev** [comment]
Pixi uses [earcut](https://github.com/mapbox/earcut) to generate triangulation for polygon. Sometimes , its behaviour is strange.
