### ISSUE TITLE
About requestAnimationFrame and Tick event

### ISSUE THREAD

**Issue by Cpin0312** [pixijs/pixi.js#4694]
i am beginner of Js and PIXI.
i have try to use to different methods to minus my sprite(height,width) every fps.
And i get some confuse about tick and requestAnimationFrame,some site is say this 2 is same function.
What my code below

`var app = new PIXI.Application();
document.body.appendChild(app.view);

// create a texture from an image path
var texture = PIXI.Sprite.fromImage('http://pixijs.io/examples/required/assets/p2.jpeg');

var container = new PIXI.Container();
container.addChild(texture);
console.log(texture.width,texture.height);
app.stage.addChild(container);
app.ticker.add(delta => gameLoop(delta));
//gameLoop();

function gameLoop()
{
//	requestAnimationFrame(gameLoop);
	//	if remove it, sprite cant be display
	if (texture.width >= 101)
	{
		texture.width -= 0.2;
		texture.height -= 0.2;
    }
}
`

when using tick event, this almost function able.
when using requestAnimationFrame,without the [if] event, sprite is not able show on my stage.
if  the [if] event is using ,sprite is able to show and be smaller every fps.

main issue
1.console.log(texture.width,texture.height);  ⇒ show 1 1 ,why?
2.cant show sprite without [if] event ⇒ why ?
3.cant direct add texture to app.stage when 
var texture = PIXI.Texture.fromImage(url); ⇒ why

is this my problem or what?Can any one help me?

**Comment by ivanpopelyshev** [comment]
```js
if (texture.width >= 101)
{
texture.width -= 0.2;
texture.height -= 0.2;
}
```

`fromImage` cant physically get you a texture in on line, browser has to load it first. Thus before the texture loads its size is (1,1).  You cannot change the texture size, you can change the frame, so please read the docs and read issues, use search, look at forum html5gamedevs.com/forum/15-pixijs/ for `texture frame` or something like that.

**Comment by Cpin0312** [comment]
@ivanpopelyshev

**Comment by Cpin0312** [comment]
@ivanpopelyshev 
Thanks, I would check it and learn it again.
