### ISSUE TITLE
PIXI. FilterManager ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4696]
hum , what this suppose do ?
if i understand , it just a class to store, create and distribute the filters need in a project?
https://pixijs.download/v4.5.2/docs/PIXI.FilterManager.html

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/managers/FilterManager.js#L62

pushFilter, popFilter are called from Container.
