### ISSUE TITLE
how to draw heat map?

### ISSUE THREAD

**Issue by molchanov1983** [pixijs/pixi.js#4699]
Hello
I have a question. How to draw heat map with pixi.js
I use pixijs to draw topology window. User is able to select any image as a map and put device. Any device has some signal level (drawing red circle now). What i need
1 - clean canvas (already works)
2- draw background color (already works)
3-draw custom image (already works)
4 - draw device (already works)
5 - draw circle(s) as a signal level with opacity 0.5 (heat map)
Thanks

**Comment by allanbreyes** [comment]
> NOTE: I don't speak for the `pixi.js` team.

I recommend you reach out on the [HTML5 Game Dev Forums](http://www.html5gamedevs.com/forum/15-pixijs/). Reading [`CONTRIBUTING.md`](https://github.com/pixijs/pixi.js/blob/dev/CONTRIBUTING.md#reporting-issues), it appears that "Issues" are solely for those revolving around the library itself, e.g. bugs.

**Comment by ivanpopelyshev** [comment]
Same as in http://pixijs.io/examples/#/layers/lighting.js , but you dont have to use extra lib for sorting.
