### ISSUE TITLE
Crop image

### ISSUE THREAD

**Issue by Cpin0312** [pixijs/pixi.js#4708]
I need to have crop a image like width 100px to 50px.
`// create a texture from an image path
※var texture = PIXI.Texture.fromImage(imaegegUrl);

var baseTexture = new PIXI.BaseTexture(texture);

var texture2 = new PIXI.Texture(baseTexture, new PIXI.Rectangle(0, 0, 128, 128));

var sprite = PIXI.Sprite.from(texture2);`
 
but this is not function for me.
However　※have been change to Sprite

HAVE any suggestion for me? Thanks

**Comment by ivanpopelyshev** [comment]
```js
var texture = PIXI.Texture.fromImage(imageUrl);
var texture2 = new PIXI.Texture(texture.baseTexture, new PIXI.Rectangle(0, 0, 128, 128));
var sprite = new PIXI.Sprite(texture2);
```

Also it might be a problem if `texture` is not yet loaded.

**Comment by Cpin0312** [comment]
@ivanpopelyshev

**Comment by Cpin0312** [comment]
@ivanpopelyshev 
`var app = new PIXI.Application();`
`document.body.appendChild(app.view);`
`PIXI.loader`
`  .add('textuerImage','urlImage')`
`  .load(setup);`
`function setup()`
`{`
`	var texture2 = new PIXI.Texture(PIXI.loader.resources.textuerImage.texture.baseTexture, new PIXI.Rectangle(0, 0, 200, 200));`
`	var sprite = new PIXI.Sprite(texture2);`
`	app.stage.addChild(sprite);`
`}`

finally i done it like this!!
Look like i still not enough study  for PIXI.
Thanks!
