### ISSUE TITLE
transform is null when trying to set a value

### ISSUE THREAD

**Issue by cvissie** [pixijs/pixi.js#4709]
![image](https://user-images.githubusercontent.com/571532/36718950-42887f5e-1bac-11e8-8a5d-a7cce5fb9a49.png)

This is really something that should be fixed on our side - I'm not sure in fact when or how it's happening.

But realistically this can only happen when a sprite/displayobject is destroyed, and then the render loop still tries to render the object.

But it does beg the question, shouldn't these getters/setters be checking if object is destroyed/valid?

**Comment by ivanpopelyshev** [comment]
> But realistically this can only happen when a sprite/displayobject is destroyed, and then the render loop still tries to render the object.

May be  you forgot to remove it from your animation loop or a tween. Pixi doesnt care neither about animation loop neither events.

Please give more information.

**Comment by cvissie** [comment]
I think maybe you are right - I think this happens inside a tween i.e. it's tweening a Sprite's position and then it get's destroyed mid way but now the Tween is still accessing the property. I originally thought it was inside the render loop when I looked at the stacktrace.

Will send when I have more info.

I merely commented on the fact that setters/getters should return safely in the event that the object is destroyed.

**Comment by ivanpopelyshev** [comment]
You dont have to `destroy()` sprites, it doesnt actually free anything, its javascript GC job. If you ask it to destroy base texture -then its different, it will free webgl resource.

Current system in pixi is very stupid and its not worth to add safeguards for it. Current policy is that its a user problem and not ours.

**Comment by cvissie** [comment]
👍
