### ISSUE TITLE
Masking with text

### ISSUE THREAD

**Issue by jhollingworth** [pixijs/pixi.js#4710]
We want to use text as a mask for an image. Something like this:

![image](https://user-images.githubusercontent.com/151172/36720851-154ac14c-1ba1-11e8-9597-fe209c6d2d94.png)

As I understand it, PIXI renders text to an image but we need a PIXI.Graphics object to do a mask. Is that correct? If so, does anyone know how I could turn text into a `Graphics`?

**Comment by GoodBoyDigital** [comment]
yo! you can use a text or a sprite as the mask 👍

**Comment by jhollingworth** [comment]
Oh, I didn't realize it worked out the box! I ❤️ pixi 😄 

I just gave it a go, everything works except the background image is black & white.

![image](https://user-images.githubusercontent.com/151172/36721753-b4eb9724-1ba3-11e8-8c52-dc510bf73827.png)

I'm guessing I'm doing something stupid, any suggestions?https://gist.github.com/jhollingworth/41403b8462849f115c08b91fe73ec67f

**Comment by ivanpopelyshev** [comment]
Which version of pixi is it?

**Comment by ivanpopelyshev** [comment]
Use text as a mask for sprite, not the other way around.

**Comment by jhollingworth** [comment]
[I gave that a try](https://gist.github.com/jhollingworth/84db653a7df1e5b7675394bea8e00ac4) but I just get a blank screen.

![image](https://user-images.githubusercontent.com/151172/36727402-ffd73408-1bb4-11e8-8712-d2c3d58e9ef5.png)

Any other thoughts what I could try?

**Comment by ivanpopelyshev** [comment]
yeah, force text update. Font rendering is lazy here and its not done if text is not renderable. Just throw this line after creating text element.

```js
text.updateText();
```

**Comment by Cpin0312** [comment]
Can i join here?
i have read @jhollingworth  code and try to do it by my way.
however my code like this
`var app = new PIXI.Application(800, 600, { transparent: true });`
` document.getElementById('container').appendChild(app.view);`
`PIXI.loader`
`	.add('godzilla','https://i.kinja-img.com/gawker-media/image/upload/s--fbE5h4t0--/c_scale,fl_progressive,q_80,w_800/1501840081290294050.jpg')`
`	.load(setup_B);`
`	var style = new PIXI.TextStyle({`
`        fontFamily: 'Arial',`
`        fontSize: 200,`
`        fontWeight: 'bold',`
`    });`
    
`	function setup_A()`
`	{`
`		var texture = PIXI.loader.resources.godzilla.texture;`
`		var godzilla = new PIXI.Sprite(texture);`
`		var text = new PIXI.Text('Godzilla', style);`
`		text.x = 0`
`		text.y = 100`
`		godzilla.width = 800;`
`		godzilla.height = 449;`
`		godzilla.mask = text`
`		app.stage.addChild(godzilla);`
`		text.updateText();`
`	}`
	
	
`	function setup_B()`
`	{`
`		var texture = PIXI.loader.resources.godzilla.texture;`
`		var godzilla = new PIXI.Sprite(texture);`
`		var text = new PIXI.Text('Godzilla', style);`
`		text.x = 0`
`		text.y = 100`
`		godzilla.width = 800;`
`		godzilla.height = 449;`
`		text.mask = godzilla`
`		app.stage.addChild(text);`
`		text.updateText();`
`	}`
 
in setup_A, window show nothing , 
in setup_B, text.mask just show mono,not color.
Have missing understanding something?

**Comment by themoonrat** [comment]
Sounds like it would be great to show this effect off in the official Pixi examples page?

**Comment by jhollingworth** [comment]
I'm seeing the same issue as @Cpin0312, calling `updateText()` doesn't change anything for me

**Comment by ivanpopelyshev** [comment]
Pixi masks use alpha and red channels. Your text is black, so its 0 by red => no mask.

https://jsfiddle.net/Hackerham/s7hh0590/3/ - it works for White text just fine.

**Comment by jhollingworth** [comment]
Amazing, thank you! Closing now as issue has been resolved.
