### ISSUE TITLE
Container size changes after textures are loaded

### ISSUE THREAD

**Issue by mchiasson** [pixijs/pixi.js#4712]
This is easily reproducible from the container-pivot.js example:

```Javascript
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

var container = new PIXI.Container();

app.stage.addChild(container);

// Create a new texture
var texture = PIXI.Texture.fromImage('required/assets/basics/bunny.png');

// Create a 5x5 grid of bunnies
for (var i = 0; i < 25; i++) {
    var bunny = new PIXI.Sprite(texture);
    bunny.anchor.set(0.5);
    bunny.x = (i % 5) * 40;
    bunny.y = Math.floor(i / 5) * 40;
    container.addChild(bunny);
}

// Move container to the center
container.x = app.screen.width / 2;
container.y = app.screen.height / 2;

// Center bunny sprite in local container coordinates
container.pivot.x = container.width / 2;
container.pivot.y = container.height / 2;

// Listen for animate update
app.ticker.add(function(delta) {
    // rotate the container!
    // use delta to create frame-independent transform
    container.rotation -= 0.01 * delta;
});
```
Where the container pivot is set to the center of the container's width and height... guess what? it only works because the textures have not been loaded yet at this point.  Once the textures are loaded, `container.width` and `container.height` will be different.

Try this for example:
```Javascript
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

var container = new PIXI.Container();

app.stage.addChild(container);

// Create a new texture
var texture = PIXI.Texture.fromImage('required/assets/basics/bunny.png');

// Create a 5x5 grid of bunnies
for (var i = 0; i < 25; i++) {
    var bunny = new PIXI.Sprite(texture);
    bunny.anchor.set(0.5);
    bunny.x = (i % 5) * 40;
    bunny.y = Math.floor(i / 5) * 40;
    container.addChild(bunny);
}

// Move container to the center
container.x = app.screen.width / 2;
container.y = app.screen.height / 2;

// Center bunny sprite in local container coordinates
container.pivot.x = container.width / 2;
container.pivot.y = container.height / 2;

// Listen for animate update
app.ticker.add(function(delta) {
    // rotate the container!
    // use delta to create frame-independent transform
    container.rotation -= 0.01 * delta;
  
    container.pivot.x = container.width / 2;   // <------- ADD THIS LINE
    container.pivot.y = container.height / 2; // <------- ADD THIS LINE
});
```
and then you'll see that you're now rotating off center.

This behaviour made everything very confusing, and wasted a lot of time wondering why it was working fine for this sample, while my stuff wasn't centred correctly, which turned out that it was because I was using the loader to wait until all the assets were downloaded in my little project.

**Comment by ivanpopelyshev** [comment]
Ah, I've missed this problem in example.

To be fair, width/height and getLocalBounds() are second-class citizens in pixi, scale is first. People have many problems with it and suggest their implementations, and so far no one made plugins with better containers. Week ago someone published dock plugin http://www.html5gamedevs.com/topic/34913-virtual-container/?tab=comments#comment-204181

I agree that we need more comments in that demo. Can you write exact words to add there?

**Comment by themoonrat** [comment]
@mchiasson is this something you would be willing to submit a PR for please? The changes you describe would definitely be helpful for others :)
