### ISSUE TITLE
Alignment Problem In a For Loop In Ticker

### ISSUE THREAD

**Issue by hellofolks** [pixijs/pixi.js#4717]
I have created a prototype of the error here: https://codepen.io/anon/pen/JpwXdo/?editors=0010

With the stop button I want to achieve that the square line will stop when top square matches. But somehow same for loop working without any problem corrupts the alignment of the line sometimes. What can be the reasons?

If you can update the code in pro pixie ways, I would be appreciated also.

**Comment by ivanpopelyshev** [comment]
That one is on the border between free advice on html5gamedev forum and paid work. No guarantees that someone here will help you here. 

I looked at it for 3 minutes and i dont understand what you want.

**Comment by ivanpopelyshev** [comment]
That part is confusing me.

```js
            for (let j = 0; j < 10; j++) {
                if (squares[i].objs[j].y + squares[i].addY <= 500) {
                    squares[i].objs[j].y += squares[i].addY;
                }
                else {
                    squares[i].array.unshift(squares[i].array[squares[i].array.length - 1]);
                    squares[i].array.pop();
                    squares[i].objs[j].y = 0;
                }
            }
```

**Comment by hellofolks** [comment]
I want start moving with the Start button and after 3secs it will start stopping function. And Stop does stop it when the top square matches with the array[0]

**Comment by hellofolks** [comment]
At that part I'm moving the square if it is in between the area else I'm shifting it to the zero again.
Then I'm checking if it is the right square

**Comment by ivanpopelyshev** [comment]
Spent 5 more mintutes. I failed to understand. @themoonrat is our expert about slot machines.

**Comment by hellofolks** [comment]
How can I contact with him?
In the code I'm creating 10 rows of 4 columns. And with start they start to spin. With the stop I want to achieve to stop to line when squares[i].TopStop matches with the square[0] at the moment. The code is doing that but for loop in the ticker messing only some squares' alignments unexpectedly

**Comment by ivanpopelyshev** [comment]
Also there's no "pixi way" for animations. Animations are handled by user-side, Pixi is a renderer lib and tween libraries can be used with it.

```js
                if (squares[i].objs[j].y + squares[i].addY <= 500) {
                    squares[i].objs[j].y += squares[i].addY;
                }
                else {
                    squares[i].array.unshift(squares[i].array[squares[i].array.length - 1]);
                    squares[i].array.pop();
                    squares[i].objs[j].y = 0;
                    if (squares[i].TopStop === squares[i].array[0]) {
                        squares[i].addY = 0;
                    }
                }
```

You change addY while j=5 and for j=6,7,8,9 stop moving , while 0,1,2,3,4 were moved.

**Comment by ivanpopelyshev** [comment]
1. calculate movement amount by doing For and only taking ```amount = Math.min(amount, 500 - squares[i].addY);```. IF its less than addY , stop it. If its more than addY, make it addY.
2. do the movement for all squares in the column

**Comment by ivanpopelyshev** [comment]
3. Visit https://www.patreon.com/user?u=2384552 .

**Comment by hellofolks** [comment]
No the only way tho change the addY is when it comes to the end. Because just the last one shifts to the first. So if addY becomes zero it means that line is moved completely without any problem

**Comment by ivanpopelyshev** [comment]
Imagine it as a line of cars, one stops and everything after it just crashes in it, `For` is not parallel, its sequential.

**Comment by hellofolks** [comment]
So what can be the solution here to prevent this? And why https://gitter.im/pixijs/pixi.js is silent always. If it wasn't I would get ideas from others also rather than opening an issue

**Comment by ivanpopelyshev** [comment]
40 minutes is not always. We have [forums](html5gamedevs.com/forum/15-pixijs/) and slack chat by invites. Most of gitter population moved there.

Are you sure you cant figure this thing out? You have to detect the

**Comment by ivanpopelyshev** [comment]
https://codepen.io/ivanpopelyshev/pen/QQzKKv?editors=0010

**Comment by ivanpopelyshev** [comment]
Next time post it in forums. Its not graphical bug and you posted custom game animation logic. 

It would be fine if it was an indie game, but, considering there are hundreds of devs who are working on slot games and that's their business logic - its just rude.

**Comment by hellofolks** [comment]
Thank you very much for your guiding light and helps! Have a nice day.
