### ISSUE TITLE
DropShadowFilter gets cut off

### ISSUE THREAD

**Issue by daviddelusenet** [pixijs/pixi.js#4723]
**OS:** macOS High Sierra 10.13.3
**Browser:** Google Chrome 64.0.3282.186
**Pixi:** 4.7.0
**Pixi Filters:** 2.6.0

———————————————————————————————————————————————

Hello everyone!

I've been building a small application with `Pixi.js`. I'm trying to show some images with a `DropShadowFilter` applied to them.

This is the code which I use to set up my sprites:

```
getImageSprite(image, texture) {
  const Image = new PIXI.Sprite(texture);
  const { Height, Width } = this.getImageSpriteSizes(texture.baseTexture, image.size.w);

  // Set the anchor point in the center
  Image.anchor.set(0.5);

  // Set the coordinates, width and height
  Image.x = this.app.renderer.width * image.location.x;
  Image.y = this.app.renderer.height * image.location.y;
  Image.width = Width;
  Image.height = Height;
  Image.filters = [
    new PIXI.filters.BlurFilter(1, 10, 1),
    new DropShadowFilter({
      alpha: 1,
      blur: 20,
      color: 0x000000,
      distance: 0,
      quality: 5,
      rotation: 0
    })
  ];

  return Image;
}
```

However, when I show the images on my canvas the `DropShadowFilter` gets cut off:

![screen shot 2018-03-01 at 15 01 37](https://user-images.githubusercontent.com/1398418/36848442-8293a248-1d61-11e8-91c9-0c72caa6d4a6.png)

Anyone has any idea on how to fix this? Thanks in advance!

**Comment by bigtimebuddy** [comment]
You need to add `padding` to the blur filter. Here's an example: https://jsfiddle.net/khff1o7f/5/

Basically the way PixiJS filters work is the first filter sets the bounds of the filterable area. Because your blur is first, it's using that area. However, if you manually set the padding much higher, it will incorporate more of the drop shadow effect.

**Comment by daviddelusenet** [comment]
@bigtimebuddy thanks, you're the best! That was it indeed 👍
