### ISSUE TITLE
Stage and container not all interactive events are working

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4727]
Hi, I have this issue that I think is related to #4307 

If I bind interactive events to the stage like this:

```var app = new PIXI.Application(800, 600);
app.stage.interactive = true;
app.stage.on('pointerdown', pointerDown);
app.stage.on('pointerup',   pointerUp);
app.stage.on('pointermove', pointerMove);

function pointerMove(event) 
{
    console.log('move');
}

function pointerDown(event) 
{
    console.log('down');
}

function pointerUp(event) 
{
    console.log('up');
}

document.body.appendChild(app.view);
```

just only the move event raises, however if I add a Sprite

```var app = new PIXI.Application(800, 600);
app.stage.interactive = true;
app.stage.on('pointerdown', pointerDown);
app.stage.on('pointerup',   pointerUp);
app.stage.on('pointermove', pointerMove);

var background      = new PIXI.Sprite.fromImage( "required/assets/bkg-grass.jpg" );
background.width    = app.screen.width;
background.height   = app.screen.height;
app.stage.addChild(background);

function pointerMove(event) 
{
    console.log('move');
}

function pointerDown(event) 
{
    console.log('down');
}

function pointerUp(event) 
{
    console.log('up');
}

document.body.appendChild(app.view);
```

Everything is as it should.

It's this behaviour expected? Why just only move works? According to #4307 explanation no event should be fire, correct?

How should I create a event surface? Should I create a full screen sized transparent Sprite?

**Comment by ivanpopelyshev** [comment]
> however if I add a Sprite

Its expected behaviour. You can add those events to InteractionManager directly, its in `renderer.plugins.interaction` . We'll rework it in v5 that way it'll be in the Application.

Stage is a simple container and you cant just click it if it has no bounds.

**Comment by DavidGOrtega** [comment]
Thanks @ivanpopelyshev ! I have hack it right now addind a transparent Sprite.

**Comment by djmisterjon** [comment]
you can also use document
its work very well for me and better than the pixi Interaction, also good performance.
```javascript

   function mousedown_Button(event) { 
 // stuff
        }

  document.addEventListener('mousemove', mousemove_function); // basic store mouse XY
   document.addEventListener('mousedown', mousedown_function); // basic store mouse XY
   document.addEventListener('mouseup',mouseup_function );
document.addEventListener('mouseup',mousedown_function.bind(this)); // example with bind 
```

**Comment by DavidGOrtega** [comment]
@djmisterjon I know! was more to point a possible bug.

**Comment by themoonrat** [comment]
Closing as appears we have answers :)
