### ISSUE TITLE
Canvas Renderer does not support masks with alphas

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4732]
Hi, as the title says, CanvasRenderer does not support masks with alphas.

I think that this functionality is pretty straight forward to be implemented with globalcompositionOperation, however I have followed the code and I have found that the MaskManager is extending  WebGLManager...

Is there any reason (apart of dev time oviously) to not support this in canvas?

Thanks guys!

**Comment by ivanpopelyshev** [comment]
Its dev time, like you said.

The problem is that pixi supports black-white and alpha masks, both. We cant do that on canvas, it will be limited functionality. However, I think I can solve that given time.

Why do you need alpha masks on Canvas renderer?

If you need to help the issue, I remember that there was PR about canvas alpha masks, please dig that out from https://github.com/pixijs/pixi.js/pulls?utf8=%E2%9C%93&q=is%3Apr+mask and post the link here.

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev thanks, ivan for your support.

> Why do you need alpha masks on Canvas renderer?

First of all, compatibility with Canvas! I though that the main goal of pixi was a webgl renderer with a 100% compatible fallback into Canvas, now I see the potentially Pixi prefers WebGL vs Canvas.

I use alpha masks with Canvas intensivelly, Im porting a Canvas project into pixi just because I have access to a gl renderer and not Canvas in React Native. In Canvas alpha mask can be used a lot an it's bery easy to be implemented with globalCompositionOperation.

One thing that I also find strange is the way that the masks works in pixi, completely the opposite than in Canvas. In canvas black is the visible part of the mask.

**Comment by ivanpopelyshev** [comment]
You can patch SpriteMaskFilter fragment shader that way it only multiplies by alpha channel, then rebuild whole pixi.js

Anyway, give me implementation for canvas and I'll try to merge it in both v4 and v5. I think there was implementation somewhere in old PR's.

**Comment by DavidGOrtega** [comment]
👍

**Comment by themoonrat** [comment]
@DavidGOrtega Did you ever get a chance to have a look at a PR or this? Let us know whether it's something to keep an issue open for or not :)
