### ISSUE TITLE
Question regarding PIXI documentation

### ISSUE THREAD

**Issue by birdkingz** [pixijs/pixi.js#4733]
Hi, 
I just started to learn Pixi and forgive me for asking simple question like this but I couldn't get an answer by my own. Hope that I'll be able to get some help from the experts here:

Currently I'm following this [tutorial](https://github.com/kittykatattack/learningPixi#displaying)
I wish to learn more about `loader` but when I try to find it in [documentation](http://pixijs.download/release/docs/PIXI.loaders.html)
It doesn't seems like the actual documentation of `loader`. May I know where can find/learn more (_eg:_ _public methods, members_) of `loader`?

**Comment by bigtimebuddy** [comment]
The Loader class in PixiJS is from **resource-loader** package. You can look here: http://englercj.github.io/resource-loader/ for the documentation for this API.

**Comment by birdkingz** [comment]
@bigtimebuddy  thank you 👍
