### ISSUE TITLE
pixijs.io HTTPS certificate is invalid

### ISSUE THREAD

**Issue by allanbreyes** [pixijs/pixi.js#4734]
Note: I'm not sure if this is the right repository to post this issue, as I can't seem to find the where the GitHub pages source is.

**Issue**
It appears that https://pixijs.io has an invalid certificate:

> pixijs.io uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Repro**
Visit https://pixijs.io

**Suggestion**
I believe this is due to the default HTTPS certificate afforded by GitHub, which does not transfer to custom domains. You can find out more about the issue here: https://github.com/isaacs/github/issues/156 There are some suggestions there that may work, including using something like Cloudflare to front the custom domain.

**Motiviation**
I really like this project, and I want to see more people use it—consider the [SEO implications of not having valid HTTPS hosting](https://www.brightedge.com/blog/http-https-and-seo/).

Thanks!

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out, we have definitely seen this pop-up. We'll look into some of the solutions in that Github issue you attached.

**Comment by bigtimebuddy** [comment]
Just launched today: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Waiting for DNS to propagate, but should be able to switch over to HTTPS soon.

**Comment by bigtimebuddy** [comment]
https://pixijs.io/examples
