### ISSUE TITLE
Flickering on Galaxy Tab A

### ISSUE THREAD

**Issue by JB-Scott** [pixijs/pixi.js#4741]
We have been working on a pixi.js based project and have moved into the device testing phase. We are having trouble with bad flickering on the Galaxy Tab A. It appears to be a general problem with pixi.js. Loading any of the example apps (even the most simple) in Chrome or the Samsung Internet Browser results in the flickering problem. Loading in Firefox works without any flickering. Also loading some other non-pixi.js html 5 applications in Chrome works correctly and does not result in flickering. We are not seeing any error messages so we have no idea what is going on. Any help would be greatly appreciated because we are unable to release until this problem is resolved. Below are the details of the device we are seeing the problems on:

Galaxy Tab A 7" (2016)
Model SM-T280
Android version 5.1.1
Android security patch level 2017-12-01
Chrome 64.0.3282.137
Processor 1.3GHz Quad-Core, T-Shark 2A
Memory: 1.5 GM RAM, 8GB ROM

**Comment by themoonrat** [comment]
Try setting 'legacy' to true in the settings when creating your renderer.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#mobile-devices-crashes-and-problems

**Comment by ivanpopelyshev** [comment]
just beware that it adds one synchronous operation and just waits for data to be copied back from gl every frame. tT doesnt consume battery, just does nothing for some time.

**Comment by themoonrat** [comment]
Closing as a solution was found
