### ISSUE TITLE
Filter resolution.

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4742]
That's the place `FILTER_RESOLUTION` is defined: https://github.com/pixijs/pixi.js/blob/dev/src/core/settings.js#L57

That's the place where it is supposed to be used: https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/Filter.js#L86

However, `PIXI.settings.RESOLUTION` is used instead.

**Comment by finscn** [comment]
Hi , don't forget that remove `resolution` in BlurFilter's constructor , in v5
