### ISSUE TITLE
[next] ceil function imperfection

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4745]
Related to #4739

Lets take resolutiont that chrome is using for zoom:

```js
function testRes(sq, resolution)
{
    var a = sq / resolution;
	var b = a * resolution;
	return b > sq;
}

var res = [0.25, 0.3333333432674408, 0.5, 0.6666666865348816, 0.75, 0.800000011920929, 0.8999999761581421, 1, 1.100000023841858, 1.25, 1.5, 1.75, 2, 2.5]

for (var i=0;i<res.length;i++) {
   var cnt = 0;
   for (var j=1;j<=1024;j++) {
       if (testRes(j, res[i])) {
	       console.log(`testRes res[${i}]=${res[i]} w=${j}`)
		   cnt++;
		   if (cnt>=3) break;
	   }
   }
}
```

output:
```
VM81:15 testRes res[1]=0.3333333432674408 w=15
VM81:15 testRes res[1]=0.3333333432674408 w=30
VM81:15 testRes res[1]=0.3333333432674408 w=49
VM81:15 testRes res[3]=0.6666666865348816 w=15
VM81:15 testRes res[3]=0.6666666865348816 w=30
VM81:15 testRes res[3]=0.6666666865348816 w=49
VM81:15 testRes res[6]=0.8999999761581421 w=121
VM81:15 testRes res[6]=0.8999999761581421 w=123
VM81:15 testRes res[6]=0.8999999761581421 w=125
VM81:15 testRes res[8]=1.100000023841858 w=21
VM81:15 testRes res[8]=1.100000023841858 w=25
VM81:15 testRes res[8]=1.100000023841858 w=42
VM81:15 testRes res[11]=1.75 w=29
VM81:15 testRes res[11]=1.75 w=58
VM81:15 testRes res[11]=1.75 w=116
```

That means, if we have resolution=1.75 and take a bunny of size 58 x 29, and then try to create renderTexture with same width and height of frame , we'll get 59x30 framebuffer.

Should I make fix for the cornercase?

**Comment by bigtimebuddy** [comment]
Just to point a finer point on it: we know there is a floating-point issue using `Math.ceil` to define framebuffer sizes with weird resolutions. This would cause the framebuffer to be slightly larger than intended. Will only fix if developers report this as a bug.

**Comment by ivanpopelyshev** [comment]
And another point: I've failed reproduce this issue for different order of operations: multiplication, then addition. That means, if user asks us to create Canvas of CSS size width x height with resolution res, `ceil` will work correctly.

**Comment by themoonrat** [comment]
@bigtimebuddy  / @ivanpopelyshev think we should close this for now then until it becomes a bigger problem?

**Comment by ivanpopelyshev** [comment]
yep
