### ISSUE TITLE
[advise again] I hope pixi could remove `AnimatedSprite` from v5.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4746]
About animation , I've talked many things , 
e.g. :  
https://github.com/pixijs/pixi.js/issues/3469

and some things I talked in slack.  (now I can't open it, F**K China GFW) .

I hope pixi core team could consider that remove or deprecate `AnimatedSprite`.
Then create a new & better Animation.

An Animation Object should NOT be a subclass of Sprite.

**Comment by ivanpopelyshev** [comment]
Agree, we'll discuss if its proper for next revision of v5 alpha. Our mesh will be discussed too, https://gameofbombs.github.io/examples-heaven/#/mesh/animation.js

**Comment by bigtimebuddy** [comment]
@finscn in v5, because everything is broken into separate packages, you could create your own custom bundle of PixiJS more easily and remove AnimateSprite if you like (this is a single package). We will, however, probably like to improve this class for v5 but it will not be removed.

**Comment by finscn** [comment]
@ivanpopelyshev , thanks.

@bigtimebuddy , I could understand your mind.

In fact I like this struct : 

![image](https://user-images.githubusercontent.com/288367/37223139-873e5054-240a-11e8-98ed-404c02ec4efe.png)

**Comment by bigtimebuddy** [comment]
Will take this structure into consideration for when we get around to improving AnimatedSprite, however, we will not be removing AnimateSprite from v5. Closing this issue but added "Future Work" tag to make sure we come back to this.

**Comment by finscn** [comment]
OK. When I finish my game project, I will research v5 , and do sth. for Animation.
