### ISSUE TITLE
[v5-SUGGESTION] Remove `resolution` from BlurFilter's constructor

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4747]
In fact , all of filters have the property `resolution`.
But most of them haven't put `resolution` into constructor's arguments.
Only BlurFilter & BlurFilterPass do that.

It's so strange.

I advise that make `resolution` be a property only. if user want to change it,  use this : 
```
var filter = new SomeFilter();
filter.resolution = newValue;
```

**Comment by finscn** [comment]
The deadline of my owner game project is attacking me,  
 I don't have time to learn v5 ,
So I can't create PR in the next few months , sorry

**Comment by themoonrat** [comment]
It makes sense for all filters to have a consistent api
