### ISSUE TITLE
pixijs.com is inaccessible over IPv6

### ISSUE THREAD

**Issue by tambry** [pixijs/pixi.js#4750]
The website is wholly inaccessible for people on IPv6-only connections.

![2018-03-10_10-18-46_chrome](https://user-images.githubusercontent.com/1827708/37239954-7806baa8-244c-11e8-8239-86fc5f82ed1c.png)

**Comment by themoonrat** [comment]
@tambry is this still the case?

**Comment by themoonrat** [comment]
@GoodBoyDigital  / @bigtimebuddy  - This something either of you can fix?
