### ISSUE TITLE
rotation strange bug ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4753]
Hum why when 
sprite.rotation = **"1"** ;
it's not same than
sprite.rotation = **1**;

but 
sprite.rotation = **"1.1"** ;
its same like 
sprite.rotation = **1.1**

thanks
![image](https://user-images.githubusercontent.com/24865815/37255780-aeb4d41e-2527-11e8-82d3-7eaedfd9942f.png)

**Comment by ivanpopelyshev** [comment]
Its not a bug, its js. please dont pass strings there.

**Comment by djmisterjon** [comment]
ok good to know so i nned to do Number(valur) to be shure

**Comment by ivanpopelyshev** [comment]
`rotation = +"1.1"` also works.
