### ISSUE TITLE
Pixi FontFace in Chrome

### ISSUE THREAD

**Issue by Nocthan** [pixijs/pixi.js#4754]
PixiJS 4.6.2
Browser: nwjs-sdk-v0.28.3-win-x64 (chrome)

Pixi uses the default Chrome font when you point a custom font-face using the FontFace obj:

Sample code:
var fontFace = new FontFace('95845e56-1b06-457d-ac03-c765ad13ec9e.ttf','url(chrome-extension://fadmacekllolfgoklhinaljokeapepka/data/95845e56-1b06-457d-ac03-c765ad13ec9e.ttf)');
document.fonts.add(fontFace);
let pixapp = new PIXI.Application({width:810, height:41, transparent:true});
fnt_pix.appendChild(pixapp.view);
var style = new PIXI.TextStyle({ fontFamily:'95845e56-1b06-457d-ac03-c765ad13ec9e.ttf', fontSize:36 });
var richText = new PIXI.Text('ABCDEFGHIJKLMNOPQRSTUWVXYZ',style);
pixapp.stage.addChild(richText);

Pixi successfully donwloaded the font files:  
![image](https://user-images.githubusercontent.com/14614685/37264353-aec5c6ac-258b-11e8-9f46-9f76e35585a0.png)
But i suspect Chrome is handling the default font to Pixi, part of their "Webfonts Intervention" feature.

And because this only happens on the first moment, when Pixi is downloading the fonts:
![image](https://user-images.githubusercontent.com/14614685/37264517-7cf7103a-258c-11e8-9de1-2ba5a059d4f3.png)
(Each line is an PIXI.Application)

On a second moment if i don't reload the page and create new PIXI.Application objects everything runs smooth:
 ![image](https://user-images.githubusercontent.com/14614685/37264604-167983a0-258d-11e8-9e7b-22dce93c600a.png)

Any hints?

**Comment by Nocthan** [comment]
Produced another sample code to better illustrate the problem, you can run it on regular Chrome.
Observed the problem also occurs when font-faces loads directly from CSS.
![image](https://user-images.githubusercontent.com/14614685/37282754-56db91da-25d4-11e8-9c19-e863ae369ec0.png)
Here: [pxtx.zip](https://github.com/pixijs/pixi.js/files/1802623/pxtx.zip)

**Comment by macguffin** [comment]
A quick fix might be to add https://github.com/typekit/webfontloader to your project.
You could then do something like this to only display the content once the fonts were loaded
```javascript
   let countLoadedFonts = 0;
         WebFont.load({
                custom: {
                    //font name set in css
                    families: ['css fontName1', 'css fontName2', 'css fontName3']
                },
                testStrings: {
                    'css fontName1': '\uE003\uE005',
                    'css fontName2': '\uE003\uE005',
                    'css fontName3': '\uE003\uE005'
                },
                loading: function () {
                    console.log('css font loading');
                },
                active: function () {
                    countLoadedFonts++;
                    console.log('css fontName active', countLoadedFonts);
                    //Display pixi content
                }
            });`

**Comment by Nocthan** [comment]
macguffin, your suggestion was effective!
![image](https://user-images.githubusercontent.com/14614685/37287895-a1af5e8e-25e4-11e8-9e4a-a6544a152664.png)

But i still suggest the devs to give a chance to this issue.
I banged my head for many hours until you comment. =D

**Comment by themoonrat** [comment]
@Nocthan it can be a browser bug that exists using regular html and css with custom fonts. Not only does the font have to be loaded, but it has to be used once before it 'kicks in' as it were. Therefore you have libraries like the one given, or the one I use, https://github.com/bramstein/fontfaceobserver - which uses the font in the background, and measures the size of the area it has been used, and when the size changes it knows the custom font is loaded, active, and can be used.

Closing as I think we're covered here :)
