### ISSUE TITLE
PIXI {.name} props ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4755]
I ask myself an existential question.
Why the property **.name** existe and why is such empty.

For my part, I use it specifically to identify resources and easily debug them.
Does it have another logical feature?

if not , Why not include the ability to directly name sprites or a container in the constructor with a arg ?
It's just a question because I find myself add names for most of my Objects, and I always use this proprety at the second degree.

**Comment by ivanpopelyshev** [comment]
Occam razor.

**Comment by djmisterjon** [comment]
ok thank for answer, so I can use it without fear of future problem.
