### ISSUE TITLE
30-40FPS with multiple Blur Filters?

### ISSUE THREAD

**Issue by XerxesNoble** [pixijs/pixi.js#4756]
Hey!

I'm working on a little visualization, and I seem to be having some trouble with frame rate. My plan is to have about ~50 sprites added to 4 different PIXI containers. Each one of these containers will have a Blur Filter with powers set to 2, 4, 6, and 8. 

The stage needs to be the full screen, so on my mac its **1440 x 780** .

I'm wondering if the frame rate of _30-40fps_ is expected for what I'm trying to do- and If there are better ways of doing this.

Any thoughts would be appreciated :)

You can see an example of it if you paste the following code into your examples application:

```javascript
// Small animated point class
class Point {
  constructor(sprite, bounds) {
    this.sprite = sprite
    this.bounds = bounds
    this.trajectory = Math.random() * (Math.PI * 2)
    this.speed = Math.random() + 0.3
  }
  updateTrajectory() {
    this.trajectory += Math.PI / 2
  }
  spriteInBounds() {
    const p = this.sprite
    const b = this.bounds
    return p.x > b.x && p.y > b.y && p.x < b.width && p.y < b.height
  }
  moveOnTrajectory() {
    const sprite = this.sprite
    sprite.x += Math.cos(this.trajectory) * this.speed
    sprite.y += Math.sin(this.trajectory) * this.speed
  }
}

const bounds = {
  x: 0,
  y: 0,
  width: 1440,
  height: 780,
}

var app = new PIXI.Application(bounds.width, bounds.height, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

// create a texture from an image path
var texture = PIXI.Texture.fromImage('required/assets/bunny.png');
texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST



// Create 4 containers to add the sprites randomly
const containers = [
  new PIXI.Container(),
  new PIXI.Container(),
  new PIXI.Container(),
  new PIXI.Container(),
]

// Four different blur filters
const blurVariance = [
  new PIXI.filters.BlurFilter(2),
  new PIXI.filters.BlurFilter(4),
  new PIXI.filters.BlurFilter(6),
  new PIXI.filters.BlurFilter(8),
]

// Match filters to container and add container to stage
containers.forEach((c, i) => {
  c.filters = [blurVariance[i]]
  app.stage.addChild(c)
})

// Create artifacts
const points = []
for (let i = 0; i < 50; i++) {
  const sprite = new PIXI.Sprite(texture)
  sprite.x = bounds.width * Math.random()
  sprite.y = bounds.height * Math.random()
  sprite.alpha = 0.8
  sprite.scale.set(0.5)
  containers[Math.floor(blurVariance.length * Math.random())].addChild(sprite)
  points.push(new Point(sprite, bounds))
}

// Fade canvas in and animate artifacts
app.view.classList.add('fade-in')
app.ticker.add(() => {
  points.forEach((point, i) => {
    point.moveOnTrajectory()
    if (!point.spriteInBounds()) point.updateTrajectory()
  })
})
```

**Comment by macguffin** [comment]
Filter are quite CPU intensive especially if you want your work to be viewed on mobile.
If you don't need to change the blue dynamically you will get a performance boost by making multiple versions of your image and blur them in Photoshop.

**Comment by XerxesNoble** [comment]
Hey @macguffin 

Thanks for the response, I was in fact hoping to change the blur dynamically. Although, you are right- I may need to explore other options. Thanks for the suggestion.

**Comment by themoonrat** [comment]
Hi @XerxesNoble - were you able to work around the issue? It is true that lots of large filters can be cpu intensive. Reducing the amount of filters and finding other ways to gain the effect (multiple sprites near each other to create a 'blur' effect) or reducing the resolution of filters can help.

**Comment by XerxesNoble** [comment]
@themoonrat I ended up using assets that I blurred in photoshop instead of the blur filter in PIXI.

**Comment by themoonrat** [comment]
:+1:
