### ISSUE TITLE
videos not working properly on iOS

### ISSUE THREAD

**Issue by mauro1998** [pixijs/pixi.js#4761]
Testing under iPad Air - iOS 11.1: http://pixijs.io/examples/?v=dev#/basics/video.js
video plays for 1 ~ 2 seconds and then just stops.

![gif](https://user-images.githubusercontent.com/20090908/37547746-7f921d2c-2941-11e8-9c4b-3c4ab6e971fa.gif)

**Comment by mauro1998** [comment]
Hi guys, is there any way to fix this?

**Comment by ivanpopelyshev** [comment]
I think that's platform-dependend bug that appears in other rendering libraries too. Try search it for ThreeJS.

**Comment by themoonrat** [comment]
@mauro1998  Could you double check again on the latest ios version to see if it works ok now? Cheers
