### ISSUE TITLE
v5 filter error 

### ISSUE THREAD

**Issue by numez** [pixijs/pixi.js#4762]
I'm having "TypeError: Cannot read property 'filterStack' of undefined" by using the code below
`player.filters = [new PIXI.filters.BlurFilter()];`

![filterdata_error](https://user-images.githubusercontent.com/6752432/37558019-ce4d8fc4-2a0d-11e8-9b68-b34d72eefdcb.png)

I'm using the **next** version 5.0.0-alpha
npm install pixi.js@next --save

screenshot
![filterdata](https://user-images.githubusercontent.com/6752432/37558009-9faf5a30-2a0d-11e8-9a43-11d89a9eeaf6.png)

**Comment by ivanpopelyshev** [comment]
Try http://pixijs.download/next/pixi.js

**Comment by numez** [comment]
@ivanpopelyshsv how to install via npm?

**Comment by bigtimebuddy** [comment]
You cannot not install alpha.2 yet, like Ivan said we are about to publish to npm using the `next` tag. You should be able to `npm i pixi.js@next`

**Comment by themoonrat** [comment]
Closing as it appears it's been fixed in later v5 alphas
