### ISSUE TITLE
Pixi explodes on imports in jest

### ISSUE THREAD

**Issue by thomasuster** [pixijs/pixi.js#4769]
TypeError: Cannot set property 'fillStyle' of null

<img width="1382" alt="screen shot 2018-03-18 at 10 55 13 am" src="https://user-images.githubusercontent.com/220965/37569102-d84a688e-2a9a-11e8-88af-881420684877.png">

**Comment by thomasuster** [comment]
```yarn add canvas-prebuilt``` fixes this, this is an issue with jsdom not auto configured to use canvas.

**Comment by ellipticaldoor** [comment]
> yarn add -D canvas-prebuilt
works for me 🙂

**Comment by seethroughtrees** [comment]
In case anyone else searches for this, here's a little more info:

You have to install the `1.x` version of canvas-prebuilt until https://github.com/jsdom/jsdom/pull/1964 is fixed.

```yarn add -D canvas-prebuilt@1```

after that, this shouldn't be an issue.

**Comment by andrevenancio** [comment]
you dont need to install the canvas-prebuilt to be honest. Simply create a mock api on your tests setup.

Here's mine, with `mocha`, `enzyme`, `jsdom`.

```javascript
import { JSDOM } from 'jsdom';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

const exposedProperties = ['window', 'navigator', 'document'];
const { document } = (new JSDOM('', { url: 'https://fitch.com/' })).window;
global.document = document;
global.window = document.defaultView;
global.requestAnimationFrame = (callback) => {
    setTimeout(callback, 0);
};

Object.keys(document.defaultView).forEach((property) => {
    if (typeof global[property] === 'undefined') {
        exposedProperties.push(property);
        global[property] = document.defaultView[property];
    }
});

global.window.HTMLCanvasElement.prototype.getContext = () => {
    return {
        fillRect: () => {},
        clearRect: () => {},
        getImageData: (x, y, w, h) => {
            return {
                data: new Array(w * h * 4),
            };
        },
        putImageData: () => {},
        createImageData: () => {
            return [];
        },
        setTransform: () => {},
        drawImage: () => {},
        save: () => {},
        fillText: () => {},
        restore: () => {},
        beginPath: () => {},
        moveTo: () => {},
        lineTo: () => {},
        closePath: () => {},
        stroke: () => {},
        translate: () => {},
        scale: () => {},
        rotate: () => {},
        arc: () => {},
        fill: () => {},
        measureText: () => {
            return {
                width: 0,
            };
        },
        transform: () => {},
        rect: () => {},
        clip: () => {},
    };
};

global.window.HTMLCanvasElement.prototype.toDataURL = () => {
    return '';
};


global.navigator = {
    userAgent: 'node.js',
};
```

**Comment by sgb-io** [comment]
nice @andrevenancio 😄

**Comment by sgb-io** [comment]
For anyone googling, this can also affect `react-lottie`

**Comment by andrevenancio** [comment]
That's was exactly why I found this issue @sgb-io ! I was trying to use `react-lottie` 😆

**Comment by StephanBijzitter** [comment]
I already had `canvas-prebuilt` installed and used it successfully before, but today it suddenly started throwing this error.

If you already have `canvas-prebuilt` (and you want to keep it), `yarn install --force` did the trick for me.

**Comment by lk-jeffpeck** [comment]
This worked for me:
https://www.npmjs.com/package/jest-canvas-mock

**Comment by NoriSte** [comment]
The @lk-jeffpeck solution works like a charm for me!

**Comment by ZufengW** [comment]
> This worked for me:
> https://www.npmjs.com/package/jest-canvas-mock

Thanks. Worked for me as well.

In case future readers get this problem:
Blindly following their [Setup](https://www.npmjs.com/package/jest-canvas-mock#setup) section did not work. I had to add `"setupFiles": ["jest-canvas-mock"]` to my `jest.config.js` instead of `package.json`.

See: [configuration](https://facebook.github.io/jest/docs/en/configuration.html#content)

**Comment by bedryck** [comment]
s;kdj\spdjf\sdpifj\sdf

**Comment by enkztw** [comment]
> For anyone googling, this can also affect `react-lottie`

Any solution?

**Comment by alanaugustodias** [comment]
> For anyone googling, this can also affect `react-lottie`

having the same here...

**Comment by enkztw** [comment]
> > For anyone googling, this can also affect `react-lottie`
> 
> having the same here...

Some of `canvas`, ` canvas-prebuilt`,  `jest-canvas-mock` did the work for me. Can't tell exactly, i've been messing with `jsdom-quokka-plugin` also.

**Comment by alanaugustodias** [comment]
> > > For anyone googling, this can also affect `react-lottie`
> > 
> > 
> > having the same here...
> 
> Some of `canvas`, ` canvas-prebuilt`, `jest-canvas-mock` did the work for me. Can't tell exactly, i've been messing with `jsdom-quokka-plugin` also.

Nice one! I've got that also from an [(open issue on lottie-react-web repo)](https://github.com/felippenardi/lottie-react-web/issues/21)

**Comment by SiGnaLz314** [comment]
Hope this helps the next seeker.

I was able to get a clean pass on jest after running into this exact issue by following this:
#https://github.com/iov-one/ponferrada/issues/133
More specifically (@alexlouden with jsom fourteen):
#https://github.com/iov-one/ponferrada/issues/133#issuecomment-501664576

Note: does appear `window.*` will fail.

**Comment by stansey** [comment]
Sorta maybe worked for me too. I added `canvas` and `jest-canvas-mock`. 

`canvas-prebuilt` seems to be unavailable now.

**Comment by AshishKapoor** [comment]
NOTE: the canvas-prebuilt package is deprecated. As of version 2, canvas itself bundles prebuilt versions from this repo. Install by running

npm install --save canvas
…and use canvas as usual.
