### ISSUE TITLE
Double shadow with PIXI.Text and blurred shadows

### ISSUE THREAD

**Issue by uorbe001** [pixijs/pixi.js#4772]
We are getting something weird that I haven't been able to quite pinpoint yet. 

Using this piece of basic canvas code to render text with shadows:
```
var canvas = document.getElementById("myCanvas");
var ctx = canvas.getContext("2d");
ctx.font = "30px Arial";
ctx.shadowOffsetX = 0;
ctx.shadowOffsetY = 10;
ctx.shadowBlur = 50;
ctx.shadowColor = "rgba(0, 0, 0, 0.3)";
ctx.fillText("Hello World",10,50);
``` 
It looks like this:

![screen shot 2018-03-19 at 11 19 01](https://user-images.githubusercontent.com/610728/37590066-5f26f3e6-2b67-11e8-816e-a7b65ba73c69.png)

Using Pixi.Text, with this code and what I think *should* be identical params:
```
var basicText = new PIXI.Text('Hello World', {
    dropShadow: true,
    dropShadowColor: 'rgba(0, 0, 0, 0.3)',
    dropShadowBlur: 50,
    dropShadowAngle: Math.PI / 2,
    dropShadowDistance: 10
});
```
It renders like so: 
![screen shot 2018-03-19 at 11 20 12](https://user-images.githubusercontent.com/610728/37590113-89e132ae-2b67-11e8-8d99-2834a89b32ca.png)

On the pixi version, you can see how there is what looks like a second shadow (un blurred) but I can't see what the cause of that shadow is. Does anyone know what is creating that shadow and how to prevent it?

**Comment by ivanpopelyshev** [comment]
Lets ask @themoonrat 

But its better if you debug https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L164 for yourself, you can just override that method and try to change it.

**Comment by uorbe001** [comment]
@ivanpopelyshev I'm trying to do that, but I figured someone might at least be able to tell if this is a mistake in my understanding or an actual bug somewhere.  If I find the problem and it turns out to be a bug, I will open a fix for it but I haven't been able to find the cause yet.

**Comment by uorbe001** [comment]
FYI, I have been able to find this call to `drawLetterSpacing` is what is causing the double-shadow: https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L194

I don't yet understand what the reason for this call is, but maybe someone can shed some light into it?

**Comment by themoonrat** [comment]
So, there are a few things here.
1. You are not seeing the drop shadow on the canvas version because your setting is far too high. 50 pixels for 30px text? Set it to a value of 5 or lower and you'll see the correct effect
2. You are not seeing any blurring on the drop shadow of the pixi version because it appears that the blurring isn't working right now. 
3. PIXI does drop shadows in a slightly different way. It doesn't use the shadow abilities build into canvas, but instead draws text a second time to gain the drop shadow effect. I don't know why it is done this way, before my time!

**Comment by uorbe001** [comment]
1- I should have been more clear about this, on the canvas version you *can* see the shadow, it's just absurdly blurred and it looks like a cloud around the text (the background is actually white on that screenshot, and the colour is due to the blurred shadow. We noticed this testing absurd numbers because our designers were complaining about the shadows on PIXI.Text not blurring correctly.

If I remove the line I mentioned on my previous comment, I can get a similar effect using PIXI.Text:

![screen shot 2018-03-19 at 13 30 15](https://user-images.githubusercontent.com/610728/37595602-afbb7d10-2b79-11e8-88b1-94257429359e.png)

(note the background here is white, and the gray colour is the blur)

2- I'm not on the latest dev branch and this might be different there, but it would appear the blur is working, just doing a second shadow on the version I'm using (v4.3.4). I can try with the dev branch later, but I didn't see any big changes related to this there.

3- I've seen that used to prevent some weird effects with overlapping shadows, this might be why it's done this way. What I'm confused about is that simply commenting out the line I mentioned before seems to make this work as expected (and I couldn't see any broken text anywhere in my codebase, but there is, no doubt, some combination that must be broken with my change)

**Comment by themoonrat** [comment]
woop, found the commit drop shadow was added!: https://github.com/pixijs/pixi.js/commit/670d2d9fb55021607ac56a5ee5696d57585a930b

I've tested and there are differences on how things are displayed between 4.4.3 and the latest (4.7.1)

**Comment by uorbe001** [comment]
[This is using PIXI 4.7.0](http://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.3%2C%22dropShadowAngle%22%3A0.5%2C%22dropShadowBlur%22%3A50%2C%22dropShadowDistance%22%3A10%2C%22fontFamily%22%3A%22%5C%22Lucida%20Sans%20Unicode%5C%22%2C%20%5C%22Lucida%20Grande%5C%22%2C%20sans-serif%22%2C%22fontSize%22%3A84%2C%22stroke%22%3A%22%23846e39%22%7D%7D) (not the latest, but pretty close), and it shows what I'm talking about, if you have blur at 50, it shows the blurred version of the shadow *and* another shadow at the same time. I would have expected it to show just the blurred shadow.

**Comment by themoonrat** [comment]
ok, this is because we're setting a shadowBlur when we draw the shadow. This is wrong, as it doesn't actually blur the shadow we are drawing, but blurs behind the shadow we are drawing.
Only way I can see out of this is either...
* Don't support drop shadow blurring (boooo, but is where we are now)
* Use the canvas api for drop shadows (yay) .... and hope it matches the look of the existing implementation.

I wonder if @GoodBoyDigital can remember back 4 years as to why he implimented drop shadows as a separate text pass rather than use the canvas api...

**Comment by themoonrat** [comment]
Adding a v5 label as a reminder to use the canvas api for drop shadows, unless @GoodBoyDigital remembers why we didn't do this before!
