### ISSUE TITLE
How to use z-index on a container?

### ISSUE THREAD

**Issue by daviddelusenet** [pixijs/pixi.js#4781]
Hi everyone!

I'm building a PixiJS application which shows some items on a canvas. These items can be moved and also the layering of them can be modified.

This is the data of my items:

```
[
   {
      "location": {
         "x": 0.39462618123058807,
         "y": 0.5383270333344155,
         "z": 259
      },
      "resource": "/images/WW0WW23069302_F_B8305/original.png"
   },
   {
      "location":{
         "x": 0.40992410608521873,
         "y": 0.5618217735187145,
         "z": 258
      },
      "resource": "/images/WW0WW24351403_F_B8305/original.png"
   }
]
```

Before adding these items to the stage I'm first sorting the array based on the `location.z` value to render the items in the right order.

However, then I get new data like this:

```
[
   {
      "location": {
         "x": 0.41735826339011933,
         "y": 0.5568044477100773,
         "z": 261
      },
      "resource": "http://10.88.216.1/images/WW0WW23069302_F_B8305/original.png"
   },
   {
      "location": {
         "x": 0.40992410608521873,
         "y": 0.5618217735187145,
         "z": 258
      },
      "resource": "/images/WW0WW24351403_F_B8305/original.png"
   }
]
```

So the `location.z` value of the items has changed. But now I've no idea on how to update the ordering on the stage. I've tried this:

```
updateLayersOrder() {
  this.app.stage.children.sort((a, b) => b.zIndex - a.zIndex);
}
```

But this doesn't do anything.

I know of the [`z-order` example](http://pixijs.io/examples/#/layers/zorder.js) but I've two issues with this:

- The example isn't clear whatsoever;
- This seems quite complicated for just changing the z-index on a sprite.

Any help is welcome and let me know if you need more information. Thanks in advance!

**Comment by ivanpopelyshev** [comment]
In the plugin wiki, there's a snippet how to NOT use that plugin:

https://github.com/pixijs/pixi-display/wiki

**Comment by daviddelusenet** [comment]
@ivanpopelyshev thanks for once again a very quick response.

How would I go about sorting stuff in my container?

**Comment by ivanpopelyshev** [comment]
The code you mentioned should sort all stage children every frame. If it doesnt work for you, well, its possible that you assigned zIndex wrongly.

Make a fiddle, I'll look.

**Comment by daviddelusenet** [comment]
@ivanpopelyshev you're right, I didn't implement it well enough. I managed to get it working. To get it working I added the following line to my containers:

`container.zIndex = image.location.z;`

Then when I get new data I check if the `location.z` value is changed. If so, I execute to following code:

```
const child = this.app.stage.getChildByName(item.identifier);

child.zIndex = item.location.z;
this.app.stage.children.sort((itemA, itemB) => itemA.zIndex - itemB.zIndex);
```

And it works like a charm! Thanks again for your help.

On another note: did you have time to check out my other [issue](https://github.com/pixijs/pixi.js/issues/4773)?

**Comment by mqliutie** [comment]
loader.add([{
    name: "body",
    url: './sleep/body.png'
}, {
    name: "head",
    url: './sleep/head.png'
}, {
    name: "leftArm",
    url: './sleep/left_arm.png'
}])
.load(setup)

function setup(){
	const body = new Sprite(TextureCache.body);
	const head = new Sprite(TextureCache.head);
	const leftArm = new Sprite(TextureCache.leftArm);

	const people = new Container();
	people.addChild(leftArm)
	people.addChild(head)
	people.addChild(body)

	// I want leftArm is front of body. but not now.
	app.stage.addChild(people);

	// I have test these ways, all of them are not working

	// people.updateLayersOrder = function () {
 //        people.children.sort(function (a, b) {
 //            a.zOrder = a.zOrder || 0;
 //            b.zOrder = b.zOrder || 0;
 //            return b.zOrder - a.zOrder
 //        });
 //    };
 //    people.updateLayersOrder();

 //    people.setChildIndex(body, 0);
 //    people.setChildIndex(leftArm, 2);



}

What should I do

**Comment by ivanpopelyshev** [comment]
what's TextureCache ? you should read Container source. There are also some tips in https://github.com/pixijs/pixi-display/wiki#how-to-not-use-pixi-display

**Comment by mqliutie** [comment]
@ivanpopelyshev Thanks for your reply. I will read the wiki
```
const TextureCache = PIXI.utils.TextureCache;
```
