### ISSUE TITLE
pointerupoutside does not exist!

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#4782]
Noticed this callback does not exist for interactive elements whilst coding away this morning!
mouseupoutside <- cool!
touchendoutside <- awesome
pointerupoutside <- non-existant :(

**Comment by haunguyen1996** [comment]
Vào 4:36 Th 4, 21 thg 3 2018 Mat Groves <notifications@github.com> đã viết:

**Comment by GoodBoyDigital** [comment]
False alarm! im an idiot 👍
