### ISSUE TITLE
Pixi.js text like Photoshop text tool, it's possible?

### ISSUE THREAD

**Issue by Nocthan** [pixijs/pixi.js#4786]
Hello,
i'm studying pixi capabilities to see if it meets my project needs! This time the task is to display a simple wooden board at the stage where user input is show. They can load their self font faces and define very basic stylizing like fontSize and fill. I have to insure that the text do not overflow the board surface even if they try it, like pasting a book contents into the html text inputs!

Before looking at the docs i came searching for something like Adobe Photoshop text tool. Predefined x/y start/end coordinates where the text is show and the overflows don't.

After looking the docs i partially solved the exercise with "wordWrap" and "wordWrapWidth" text style properties, but they don't limit the used height and the text can overflow throught the lower part of the board. Or with the width and height properties of the text object but they stretch/shrink the contents and don't wrap the words, the result is awful. =|

Any Hints? It's possible?

**Comment by djmisterjon** [comment]
http://pixijs.io/pixi-text-style/#

**Comment by themoonrat** [comment]
pixi text style is awesome!
