### ISSUE TITLE
Pixi slider frame by frame

### ISSUE THREAD

**Issue by CharlieGlez** [pixijs/pixi.js#4788]
Hi! I'm a huge fan of pixi.js and it's awesome! I've seen a awesome webpage that uses pixi for the effects and I only wanted to know the "drag to start" part where you move and the animation follows frame by frame. Is that in the pixi interactions and what name of the interaction is it. 
Here is the web page [https://inculerate.com/](https://inculerate.com).

Have a nice day! :)

**Comment by bigtimebuddy** [comment]
Thanks for the compliments 👍 

The short answer is there's is not an interaction feature in PixiJS to achieve that effect. You'll have to create it from scratch, like the author of the website did.

The effect could be created several ways using the interaction manager to handle mouse/touch  events for the drag. Potentially a VideoBaseTexture to seek to a location of a video texture, like moving a playhead or using an AnimatedSprite to show a frame of an animation.

**Comment by allanbreyes** [comment]
GSAP's `TimelineMax` might help as well: https://greensock.com/timelinemax

**Comment by allanbreyes** [comment]
@bigtimebuddy - on a tangential note, any idea how they did the "glitching" in text effects?

**Comment by bigtimebuddy** [comment]
Looks like a DisplacementFilter

**Comment by CharlieGlez** [comment]
Hello! Thanks for the fast feedback, I appreciate it a lot!
Thank for both of you giving me ideas to make the style look a like.

Cheers!
