### ISSUE TITLE
Mesh examples are not working

### ISSUE THREAD

**Issue by olivoil** [pixijs/pixi.js#4795]
The mesh examples on pixi's v4 website aren't working at all. It looks like they use `PIXI.Geometry`, which I believe is a construct from v5? You can look at http://pixijs.io/examples/#/mesh/triangle.js to see it broken.

Are there examples or tutorials out there on creating meshes within Pixi? Something that shows how to get from a very simple mesh created in blender/maya/3dsmax or from parsing an svg file to rendering it in Pixi would be of great help.

**Comment by bigtimebuddy** [comment]
These only work work with "next" branch:
http://pixijs.io/examples/?v=next#/mesh/triangle.js

Just select "next" from the "PixiJS Version" list at the bottom.

We'll work on providing a better user experience in examples for this. @ivanpopelyshev would you mind adding an alert or warning to the page about compatibility of these tests.

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy There's a warning, but we need it in red.
![image](https://user-images.githubusercontent.com/695831/37868325-6d73c9fe-2fb5-11e8-85dd-6d9bec669222.png)

**Comment by olivoil** [comment]
@bigtimebuddy thanks, my bad for not seeing the comment at the top of the example. Feels obvious now that I know it's there!

@ivanpopelyshev I'm trying to display custom geometry but still in 2D. Things like custom 2D triangulated shapes cut out from a plane. I've been using sprites with rasterized svg textures, but need to be able to zoom in on these shapes and the textures look blurry as a result. I've been invalidating the texture cache every time a user zooms in and re-rendering the objects at the right scale, but am exploring using meshes instead, hoping it will be of better quality/performance. Does it make sense to try and render meshes for that use case?

**Comment by ivanpopelyshev** [comment]
yep, Mesh and Graphics. Its even possible to generate stuff in graphics , call updateGraphics(), take _webglData, choose every 2 floats over 6, and thats how you get vertices for Mesh.

**Comment by bigtimebuddy** [comment]
I'm thinking of something a little less subtle than that, I'll put together a PR for examples

**Comment by zwalden** [comment]
Not sure if it's entirely related; but selecting next didn't seem to work for me. I ended up getting the following:

Uncaught TypeError: PIXI.RawMesh is not a constructor at window.onload (?v=next:71)

Will report back if I figure out why !

**Comment by ivanpopelyshev** [comment]
They renamed RawMesh to just Mesh and broke it. yeah.

**Comment by themoonrat** [comment]
Do we need to separate out our examples maybe? Have currently v4 examples in one place, then an all new better place for v5 examples

**Comment by bigtimebuddy** [comment]
It's time to tweak the examples to provide a support version to each example (in this case >=5.0.0-alpha.3) and provide some more explicit messaging (e.g. alert, dialog, etc). The current approach of a subtle code comment is not obvious enough.

**Comment by mrgoonie** [comment]
I think you guys should move the version select box on top of the code area so people can get noticed easier:

![image](https://user-images.githubusercontent.com/6857382/43882642-91c5a250-9bda-11e8-8dc8-b6858d8b9761.png)

**Comment by dorado-lmz** [comment]
problem still exist!!!!

**Comment by themoonrat** [comment]
Examples can now have a required version.

**Comment by Zzzen** [comment]
https://pixijs.io/examples/?v=v5.1.2#/mesh/triangle.js

it's not working now.

```
Mesh.js:20 Uncaught TypeError: this.material._renderCanvas is not a function
    at Mesh._renderCanvas (Mesh.js:20)
    at Mesh.renderCanvas (Container.js:34)
    at Container.renderCanvas (Container.js:37)
    at CanvasRenderer.render (CanvasRenderer.js:237)
    at Application.render (Application.js:97)
    at TickerListener.emit (TickerListener.js:96)
    at Ticker.update (Ticker.js:459)
    at Ticker._tick (Ticker.js:167)
```

**Comment by themoonrat** [comment]
That example works for me. What browser / os combo are you using?

**Comment by Zzzen** [comment]
When Chrome hardware acceleration is turned on, it's working again. Weird. You can try turning  Chrome hardware acceleration.  
Nevertheless, I am using

```
Chrome 76.0.3809.132   64bit
Windows 10  v1803
```
