### ISSUE TITLE
auto resize pixi.js to full width and height on page load

### ISSUE THREAD

**Issue by inglesuniversal** [pixijs/pixi.js#4796]
Hi:

LOVE pixi.js can't wait to start creating GREAT things!

ragarding my question: most demos and sample code show a default resolution of 800x600... is there a way to auto expand the frame or canvas area to the full width and height of the screen, but at the sametime... if I rotate the screen, can the new screen size be applied dynamically? I tried some code with jquery but I didn't get the results I expected.

**Comment by bigtimebuddy** [comment]
Hi @inglesuniversal, you might want to check this out:
https://github.com/pixijs/pixi.js/wiki/v4-Tips%2C-Tricks%2C-and-Pitfalls#resizing-renderer

We've been getting a lot of issues about this, I'm considering making a convenience property to the Application to handle this internally. But for know, that example should be what you're looking for.
