### ISSUE TITLE
How can I initialize PIXI if I already have a canvas element in DOM

### ISSUE THREAD

**Issue by sussertod891015** [pixijs/pixi.js#4798]
I want to use the canvas that already exist to initialize PIXI, what should I do?

**Comment by ivanpopelyshev** [comment]
You can pass canvas in application or renderer constructor

```
var renderer = new PIXI.WebGLRenderer(800, 600, { view: myCanvas });
```

**Comment by ivanpopelyshev** [comment]
http://pixijs.download/dev/docs/PIXI.Application.html
http://pixijs.download/dev/docs/PIXI.WebGLRenderer.html

https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/SystemRenderer.js#L92

**Comment by sussertod891015** [comment]
thank you so much!!

发自我的 iPhone

在 2018年3月26日，15:28，Ivan Popelyshev <notifications@github.com<mailto:notifications@github.com>> 写道：


You can pass canvas in application or renderer constructor

var renderer = new PIXI.WebGLRenderer(800, 600, { view: myCanvas });
