### ISSUE TITLE
Bug in root container masking ,touch event doesn't work

### ISSUE THREAD

**Issue by twobear** [pixijs/pixi.js#4799]
there are some stange thing,if I add a  mask to the root container ,and all touch event  can't work...
code like this
`    let render = PIXI.autoDetectRenderer(640,1136,{transparent: true});`
       ` NODE.appendChild(render.view);`
       ` let stage = new PIXI.Container();`
     `  let grap=new PIXI.Graphics();`
     `   grap.drawRect(0,0,640,1136);`
       ` game.stage.mask=grap;`

but  if root container no mask,all is OK.

**Comment by themoonrat** [comment]
This is a known issue @twobear, with the easy workaround being to create another container and put the mask on that, not on the root container :)
