### ISSUE TITLE
Tilemaps

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#48]
Talk to me about tilemaps, grapefruit uses the [Tiled Editor](http://www.mapeditor.org/) json format for tilemaps. But I am less worried about specifics for that format, talk to me more about how you think tilemaps should render using Pixi.

I was thinking about having a Map (extends DisplayObjectContainer) with Layers (each extending DisplayObjectContainer). The Layers each generate and add one PIXI.Sprite for each "tile" on the map. I was thinking they would each share a PIXI.Texture instance for the texture holding all the tiles, and do some offset fancyness to make that work.

Is there a better way to do tilemaps in Pixi? How would you do it? I cam move this to [the forums](http://www.goodboydigital.com/forum/) if it would be more appropriate there.

**Comment by McFarts** [comment]
Here is a code we can use to adapt pre-render chucked maps if we want for help I found:

https://github.com/bsparks/impact-tiled/blob/master/example/lib/plugins/tiled/tilelayer.js#L74
