### ISSUE TITLE
BaseTexture loading SVG data uri, RegEx wizard anyone?

### ISSUE THREAD

**Issue by rich-earth** [pixijs/pixi.js#4801]
Hi,  

I'm having some issues with BaseTexture loading SVG's which I think I've got to the bottom of.  I would submit a pull request,  but I'm baffled by Regular Expressions and would like to request changes on two in core/Consts if it doesn't cause any other problems I'm not aware of... Some background:

I'm creating sprites from SVG's, using some svg data baked into my code. 
Currently working in PIXI,  you can create a Sprite from an image data uri encoded to base64, as you can with png's etc, and then scale how big the browser loads that image using sourceScale,  like so:

```js
let tex = PIXI.Texture.fromImage(
      "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2IDYiPjxjaXJjbGUgY3g9IjMiIGN5PSIzIiByPSIzIiBmaWxsPSIjZmYyODI4Ii8+PC9zdmc+",
      false,//crossorigin
      PIXI.settings.SCALE_MODE,
      2 //sourceScale, create texture twice as original for 2x res
);
tex.baseTexture.resolution = 2;
let spr = new PIXI.Sprite(tex);
```

👌This is all good,  you get a sprite and texture at whatever size you want.

But now I want to do the same thing,  but not encode the SVG data to base64 like so:
```js
let tex = PIXI.Texture.fromImage(
      'data:image/svg+xml;<svg width="30" height="30"><circle cx="3" cy="3" r="3" fill="#ff2828"/></svg>',
      false,
      PIXI.settings.SCALE_MODE,
      2 //sourceScale has no effect
);
```

This works too (except for IE not liking the lack of base64 encoding), but this time the sourceScale has no effect. This seems to be because BaseTexture treats it like a png instead (imageType defaults to png)  because **Consts->DATA_URI** Regex fails to find the file type here,  there being no 'base64' in that svg data URI.  So first request is to make that RegEx accept non base64 and allow it to return svg as the file type.

I'm also looking at [this](https://www.npmjs.com/package/mini-svg-data-uri) as a way to include raw svg data and save space, while keeping it IE compatible without using base64 data uri's. Ok the svg looks ugly but it works in IE without having to base64 encode it,  which keeps the svg data smaller. 

So it would then look like this:
```js
let tex = PIXI.Texture.fromImage(
      "data:image/svg+xml,%3csvg width='30' height='30'%3e%3ccircle cx='3' cy='3' r='3' fill='%23ff2828'/%3e%3c/svg%3e"
);
```

This is valid svg, but doesn't work at all because **Consts->SVG_SIZE**,  can't parse the width and height from that svg data, as it is expecting xml tags instead of those %3c html characters.  Can anyone edit that RegEx as well to to return the width/height from the data uri above? 

Many Thanks
Rich

**Comment by englercj** [comment]
I believe your data uri is malformed. `data:image/svg+xml;<svg...` should be `data:image/svg+xml,<svg...`

Notice the comma instead of the semicolon. A comma separates the mime type and data sections, but you are missing that character. Another valid option for you may be `data:image/svg+xml;charset=utf8,<svg...`

**Comment by rich-earth** [comment]
Cool.  Thanks for your help
