### ISSUE TITLE
Loader throws 'Cannot add resources while the loader is running' error

### ISSUE THREAD

**Issue by daviddelusenet** [pixijs/pixi.js#4804]
Hi everyone,

I'm building an application with `PixiJS` which shows an assortment of products. There are multiple assortments which a user can switch between. Each assortment contains a lot of images. This is how I add the images to the loader:

```
items.forEach((item) => {
  if (item.resource && !(item.identifier in this.loader.resources)) {
    this.loader.add(item.identifier, item.resource.replace('original', 'w1000'));
  }
});
```

When an assortment gets loaded I'm adding all of the images to the loader. However, when I quickly switch assortments while the loader is still loading the previous images I get the following error:

`Cannot add resources while the loader is running.`

After some Googling I found a 'solution': every time I want to use the loader again I call `this.loader.reset();`. This fixes my `Cannot add resources while the loader is running` error but now I get the following warnings:

<img width="847" alt="screen shot 2018-03-27 at 15 13 48" src="https://user-images.githubusercontent.com/1398418/37969615-7b03d28a-31d1-11e8-881b-4192797c0e79.png">

Any idea on how to properly tackle this problem?

Thanks in advance!

**Comment by ivanpopelyshev** [comment]
empty pixi texture cache. `PIXI.utils.clearTextureCache()` every time you do that reset. 

pixi texture cache exists for `fromImage` and `from` methods. If you dont use them, you can clear it whenever you want.

**Comment by ivanpopelyshev** [comment]
Also I recommend to create new loader each time you do that, and move resources that you already had in previous "level" there, instead of adding them again.
