### ISSUE TITLE
(5.0.0-alpha.2) Primitives / drawing geometry

### ISSUE THREAD

**Issue by Kamil93** [pixijs/pixi.js#4808]
Hello

I'd like to test v5 while developing my things, so I've tried and 99% works good for now. But drawing primitives not.

https://imgur.com/qdDZGKc

The blue arrows on the screenshot show glichy geometries. Before updating to v5 works well.

For example the black lines should surround the gray ground. And the white geometries looks like cut to 1/4.

But the little purple circles seems drawn well.

Where may be a problem?

I'm just doing things like here: http://pixijs.io/examples/?v=next#/basics/graphics.js

**Comment by ivanpopelyshev** [comment]
Good job and good bugreport! Its enough for me to detect the bug, but i think If you make a fiddle that'll be even better!

**Comment by Kamil93** [comment]
Don't know how to make it separeted from my kind of big project. The only thing that came to my mind is bug may be releated to nested multiple containers, but I'm not sure.

This function is used for black geometry from screenshot:

```
PIXIHelper.polygon = function(x, y, vertices, borderWeight, borderColor, fillColor, alpha) {
  var gfx = new PIXI.Graphics();
  var verticestmp = [];

  for ( var i=0; i<vertices.length; i++ ) {
    verticestmp.push(vertices[i][0]);
    verticestmp.push(vertices[i][1]);
    
    if ( i == vertices.length-1 ) {
      verticestmp.push(vertices[0][0]);
      verticestmp.push(vertices[0][1]);
    }
  }

  gfx.lineStyle(borderWeight, borderColor);
  if ( fillColor !== undefined ) gfx.beginFill(fillColor);
  gfx.drawPolygon(verticestmp);
  if ( fillColor !== undefined ) gfx.endFill(fillColor);

  if ( alpha !== undefined ) gfx.alpha = alpha;

  return gfx;
}
```
