### ISSUE TITLE
Somber news

### ISSUE THREAD

**Issue by GaryTsang** [pixijs/pixi.js#4810]
Guys, 

I am sending you this message with a heavy heart. My ex-colleague and team member and contributor to this and many other open source repos - Adi Reddy Mora has sadly passed away yesterday. This came very suddenly.  He left behind his wife and two young children.

https://www.facebook.com/TDFUKEU/posts/1728641237229242

Gary

**Comment by ivanpopelyshev** [comment]
.

**Comment by bigtimebuddy** [comment]
This is very sad news indeed. Thank you for letting us know Gary. @adireddy was a frequent presence and contributor on Pixi and other related projects. He will be sorely missed.

**Comment by GaryTsang** [comment]
Thank you.

**Comment by allanbreyes** [comment]
Apologies for your loss. Perhaps the maintainers could consider something like [all-contributors](https://github.com/kentcdodds/all-contributors). It's a small gesture, but I think it's a good way to commemorate @adireddy's contribution to `pixi.js`.

**Comment by englercj** [comment]
Thanks for letting us know Gary. I'm sorry for your loss, @adireddy will be missed.
