### ISSUE TITLE
Flicker / Render issue with roundPixels AND cacheAsBitmap turned on 

### ISSUE THREAD

**Issue by mikemarshal** [pixijs/pixi.js#4811]
I have a chunk that generates tiles as sprites, the sprites are added to a container which is then translated around the player. There originally was a weird flicker issue going on around the edges of each tile but setting `roundPixels: true` fixed this (NOTE: all sprite coordinate values were already getting rounded before this so I'm not sure how this fixed that issue)

My issue now is that when I set `this.sprite.cacheAsBitmap = true;` on the container filled with tiles, a weird rendering issue occurs 
![515fcbef2126454e74047a90f0c6b6ab](https://user-images.githubusercontent.com/31336297/38014022-c90eed1a-322c-11e8-933b-4fa3a5568085.png)
NOTE: the border line is much thinner in the center and this ONLY occurs when you move your character towards the right side of the map (isn't like that always)

Now the weird part is setting roundPixels to false and keeping cacheAsBitmap true fixes this, or turning off cacheAsBitmap to false and keeping roundPixels true fixes it too. My issue is that I would like to keep both roundPixels and cacheAsBitmap but have no idea what the problem being caused is currently. 

Thanks in advance!

**Comment by ivanpopelyshev** [comment]
I, personally, cant give guarantees about cacheAsBitmap. If you make a fiddle, we'll fix it.

Workaround: please use https://github.com/pixijs/pixi-tilemap , tutorial is here: https://github.com/Alan01252/pixi-tilemap-tutorial

**Comment by mikemarshal** [comment]
Am trying to replicate it on fiddle, will message you soon. I would rather not use more libraries if possible

**Comment by mikemarshal** [comment]
@ivanpopelyshev [jsfiddle](https://jsfiddle.net/roastydev/opuyx5ph/43/)
very strange behavior, the render issue seems to have disappeared without me changing anything but now there's a weird flicker that occurs horizontally (halfway across the bitmap) and vertically (halfway across the bitmap) almost as if it's being split up into 4 quadrants. I replicated the code as best as I can but none of those things are occurring on jsfiddle. There is smoothing code on my copy that I haven't added to the fiddle, which takes the expected sprite location - current sprite location / variable adjusted for time between frames (this gives float values for the sprite) but they should be getting rounded through the roundpixel game setting. Turning the cacheAsBitmap to false makes all of this go away.

**Comment by themoonrat** [comment]
Closing as looks like you have a handle on a solution :)
