### ISSUE TITLE
Container cuts of contents

### ISSUE THREAD

**Issue by daviddelusenet** [pixijs/pixi.js#4812]
Hello everyone,

I've some `PixiJS` containers which contain a 'fake shadow' and a image. However, these contents get cut off by the container itself.

This is my code:

```
getImageSprite({ image, texture }) {
  const { height, width } = this.getImageSpriteSizes({ baseTexture: texture.baseTexture, ratio: image.size.w });

  // First setup the container and sprite
  const container = new PIXI.Container();
  const sprite = new PIXI.Sprite(texture);
  const spriteWidth = width * ZOOMED_STAGE_SCALE;
  const spriteHeight = height * ZOOMED_STAGE_SCALE;

  // Set the sprite dimensions
  sprite.width = spriteWidth;
  sprite.height = spriteHeight;

  // Add the blur filter used for the 'fake' shadow
  sprite.filters = [new PIXI.filters.BlurFilter(50)];

  // Give the container a name so it can be found later on and set the position
  container.name = image.identifier;
  container.x = this.app.renderer.width * image.location.x;
  container.y = this.app.renderer.height * image.location.y;

  // Setup a RenderTexture to 'fake' a shadow
  // https://github.com/pixijs/pixi.js/issues/4773#issuecomment-376544044
  const renderTexture = PIXI.RenderTexture.create(spriteWidth, spriteHeight);
  this.app.renderer.render(sprite, renderTexture);

  const shadow = new PIXI.Sprite(renderTexture);
  shadow.anchor.set(0.5);
  shadow.opacity = 0.1;
  shadow.tint = 0x0;
  container.addChild(shadow);

  // Add the sprite to the container and scale it down
  // Also set the zIndex (used for sorting)
  container.addChild(sprite);
  container.scale.set(1 / ZOOMED_STAGE_SCALE);
  container.zIndex = image.location.z;

  // Set the filter used for the image and cache the container as bitmap
  sprite.filters = [new PIXI.filters.BlurFilter(1)];
  sprite.anchor.set(0.5);
  container.cacheAsBitmap = true;

  return container;
}
```

This is the result:

![screen shot 2018-03-28 at 10 54 43](https://user-images.githubusercontent.com/1398418/38018941-a14cf8d6-3276-11e8-807a-8a2acf3641c9.png)

Here another screenshot without the sprite to illustrate my problem better:

![screen shot 2018-03-28 at 11 00 01](https://user-images.githubusercontent.com/1398418/38019205-3c9e13b0-3277-11e8-9461-74776f3f87b8.png)

As you can see the 'fake shadow' gets cut off by the container. One solution I thought off was adding a `PIXI.Rectangle` which is bigger than the sprite to make the container bigger. I came up with the following code:

```
// Add a rectangle
const rectangle = new PIXI.Rectangle(0, 0, spriteWidth + 50, spriteHeight + 50);
container.addChild(rectangle);
```

However, when I execute this code I get the following error:

`Uncaught TypeError: Cannot set property '_parentID' of undefined`

Any ideas on how to fix this? Like setting overflow/padding on the container?

**Thanks!**

**Comment by ivanpopelyshev** [comment]
We had a problem with wrong padding for BlurFilter. Please check that you use latest version of pixi, and try to set padding to filter.

**Comment by daviddelusenet** [comment]
@ivanpopelyshev I'm using `PixiJS 4.7.1`.

I've tried the following:

```
const blur = new PIXI.filters.BlurFilter(1);
blur.padding = 50;
sprite.filters = [blur];
sprite.anchor.set(0.5);
container.addChild(sprite);
container.cacheAsBitmap = true;
```

But it doesn't change anything.

**Comment by daviddelusenet** [comment]
@ivanpopelyshev I'm not sure I'm following you. The `cacheAsBitmap` option doesn't change anything for me (in terms of the content being cut off).

I really need the container because controlling all my shadows and sprites individually isn't an option (tried that already, it's impossible to position them the same). So do you have any other suggestions?

What I don't understand though is why the following code:

```
const rectangle = new PIXI.Rectangle(0, 0, spriteWidth + 50, spriteHeight + 50);
container.addChild(rectangle);
```

Throws the `Uncaught TypeError: Cannot set property '_parentID' of undefined` error?

If I can fix this I can probably also fix my other problem.

**Comment by daviddelusenet** [comment]
This code gives me the same error:

```
const circle = new PIXI.Circle(0, 0, 100);
container.addChild(circle);
```

Error: `Uncaught TypeError: Cannot set property '_parentID' of undefined`

![ynlqwrm](https://user-images.githubusercontent.com/1398418/38024770-36b3fab4-3286-11e8-992f-c7d477e10d80.jpg)

**Comment by ivanpopelyshev** [comment]
Ok, keep fiddling with cacheAsBitmap.

Because Rectangle and Circle are shapes. They are not DisplayObjects. If you want to set bounds for specific container, try this thing:

```js
container.myBounds = new PIXI.Rectangle(-50, -50, spriteWidth + 100, spriteHeight+100);

container.calculateBounds = function()
{
   this._bounds.clear();
   this._bounds.addFrame(this.transform, this.myBounds);
   this._lastBoundsID = this._boundsID;
}
```

**Comment by ivanpopelyshev** [comment]
Just for the context: I had my own implementation for bounds and other things, and half of it was thrown out because it was difficult, the other half refactored by @GoodBoyDigital and that's how v4 bounds were born. 

We know there are many bounds-related problems with cacheAsBitmap/generateTexture/filters, and every 3 months I make another try to fix something. So far we didnt find better solution to bounds suited for open-source project.

**Comment by daviddelusenet** [comment]
I've managed to fix my problem. This is my final code:

```
getImageSprite({ image, texture }) {
  const { height, width } = this.getImageSpriteSizes({ baseTexture: texture.baseTexture, ratio: image.size.w });
  const spriteWidth = width * ZOOMED_STAGE_SCALE;
  const spriteHeight = height * ZOOMED_STAGE_SCALE;

  // First setup the container and sprite
  const container = new PIXI.Container();
  const sprite = new PIXI.Sprite(texture);

  // Set the sprite dimensions
  sprite.width = spriteWidth;
  sprite.height = spriteHeight;

  // Set the blur filter and coordinates used for the 'fake shadow'
  sprite.filters = [new PIXI.filters.BlurFilter(10)];
  sprite.x = 200;
  sprite.y = 200;

  // Give the container a name (so it can be found later on)
  // And set the position
  container.name = image.identifier;
  container.x = this.app.renderer.width * image.location.x;
  container.y = this.app.renderer.height * image.location.y;

  // Setup a RenderTexture to 'fake' a shadow
  // https://github.com/pixijs/pixi.js/issues/4773#issuecomment-376544044
  const renderTexture = PIXI.RenderTexture.create(spriteWidth + 400, spriteHeight + 400);
  const shadow = new PIXI.Sprite(renderTexture);
  shadow.anchor.set(0.5);
  shadow.tint = BLACK.replace('#', '0x');
  shadow.alpha = 0.7;
  this.app.renderer.render(sprite, renderTexture);

  // Set the actual filter and coordinates used and set the anchor
  sprite.filters = [new PIXI.filters.BlurFilter(1)];
  sprite.anchor.set(0.5);
  sprite.x = 0;
  sprite.y = 0;

  // Add the shadow and sprite to the container and scale it down
  // Also set the zIndex (used for sorting) and cache the container as bitmap
  container.addChild(shadow, sprite);
  container.scale.set(1 / ZOOMED_STAGE_SCALE);
  container.zIndex = image.location.z;
  container.cacheAsBitmap = true;

  return container;
}
```

The trick was adding more space to the `RenderTexture`. So I changed `PIXI.RenderTexture.create(spriteWidth, spriteHeight);` to  `PIXI.RenderTexture.create(spriteWidth + 400, spriteHeight + 400);`.

I also added:

```
sprite.x = 200;
sprite.y = 200;
```

Beforehand to position the sprite in the centre of the `RenderTexture`.

Result:

![screen shot 2018-03-29 at 13 58 02](https://user-images.githubusercontent.com/1398418/38087748-946b85ea-3359-11e8-9242-bb05576ec199.png)

Couldn't be happier 😄
