### ISSUE TITLE
Rendering multiple objects into a single RenderTexture

### ISSUE THREAD

**Issue by Gaikov** [pixijs/pixi.js#4814]
When I have been rendering multiple objects consistently into a single texture with custom matrix for each object only first matrix for first the object applies to all the objects. And this only applies to webgl render, in canvas mode everything is fine. 

I think the bug in .bindRenderTexture method that assigns the custom transform to texture during activating it. And the next call for that method do not activates the texture be cause it is already active and do not reassign a new matrix.

**Comment by ivanpopelyshev** [comment]
Yep, its a bug, I have collection of those things related to transforms in `generateTexture()` and other methods. It wont be fixed in v4. 

workaround: make a container, and every time you render something in renderTexture, put it in container first and change container transform.

**Comment by Gaikov** [comment]
I've made something like this:

            renderer.render(source, texture, false, matrix);
            if (renderer["bindRenderTexture"]) {
                renderer["bindRenderTexture"]();
            }

**Comment by themoonrat** [comment]
Closing as looks like you have a solution, and it wouldn't be fixed for v4 anyway!
I'll annoy @ivanpopelyshev  by pinging him again to double check this has been thought about for v5
