### ISSUE TITLE
unwanted shadow when extracting

### ISSUE THREAD

**Issue by m31271n** [pixijs/pixi.js#4816]
I am using extract plugin to extract an canvas like this: 

```js
const app = new PIXI.Application(width, height, {
  antialias: true,
  backgroundColor: 0xb9bdbc,
});

...

app.renderer.plugins.extract.canvas(app.stage).toDataURL();
```

But I got a image with annoying shadow. 

<img width="464" alt="screen shot 2018-03-29 at 7 55 13 pm" src="https://user-images.githubusercontent.com/12194646/38087556-252b05e8-338b-11e8-8f41-d0e4f314dcde.png">
(The most obvious shadow is at the bottom of image.)

* * *

I tried a lot, but can't find any ways to remove this.

If anyone could give me some tips, I'd sure be grateful.

**Comment by themoonrat** [comment]
@m31271n did you have any luck solving this? Did antialiasing on / off effect things? What about Canvas renderer vs WebGL renderer? Thanks!
