### ISSUE TITLE
moving node group, trim child filter

### ISSUE THREAD

**Issue by numez** [pixijs/pixi.js#4818]
using PixiJS 5.0.0-alpha.2 - ✰ WebGL 2 ✰"

```

    let instance = new PIXI.Graphics();

    let g1 = new PIXI.Graphics();
    g1.beginFill(0xff00ff);
    g1.drawRect(50, 50, 100, 100);
    g1.filters = [new PIXI.filters.BlurFilter(22)];
    instance.addChild(g1);

    let g2 = new PIXI.Graphics();
    g2.beginFill(0x00ffff);
    g2.drawRect(100, 100, 150, 150);
    instance.addChild(g2);

    instance.filters = [new PIXI.filters.NoiseFilter()];

```

moving the graphics by calling

```
    instance.position.set(130, 150)
```

is trimming the **g1** Graphics filter

![trim](https://user-images.githubusercontent.com/6752432/38117013-12be424e-33b3-11e8-91fb-11280e31b3d6.png)

**Comment by ivanpopelyshev** [comment]
nice! we have a new bug!

**Comment by numez** [comment]
it seems that the graphics move, but the children's filterArea is still 

any workaround @ivanpopelyshev ?

**Comment by ivanpopelyshev** [comment]
manual filterArea is your workaround:

```
g1.filterArea = app.screen; //or renderer screen
```

That thing will use full-screen temporary buffer, its super-slow for blur.

you can set filterArea (ITS ABSOLUTE) if you know where exactly that element will appear on screen, however due to this bug it might have offset too.

**Comment by bigtimebuddy** [comment]
Does this still happen if you change instance to a PIXI.Container?

**Comment by themoonrat** [comment]
@numez Would it be possible to get a reply to @bigtimebuddy  please? :)

**Comment by lordnoriyuki** [comment]
By the way, I'm getting this problem with a filter applied to `app.stage` when one of the children is moved around, and had to do `app.stage.filterArea = app.screen` after `app.stage.filters = [myFilter]`to get it to work correctly.
