### ISSUE TITLE
Number.isIntege is not working in IE 10

### ISSUE THREAD

**Issue by tywang2006** [pixijs/pixi.js#4819]
I found the code in pixijs

`InteractionData.prototype.copyEvent = function copyEvent(event) {
        // isPrimary should only change on touchstart/pointerdown, so we don't want to overwrite
        // it with "false" on later events when our shim for it on touch events might not be
        // accurate
        if (event.isPrimary) {
          this.isPrimary = true;
        }
        this.button = event.button;
        // event.buttons is not available in all browsers (ie. Safari), but it does have a non-standard
        // event.which property instead, which conveys the same information.
        this.buttons = Number.isInteger(event.buttons) ? event.buttons : event.which;
        this.width = event.width;
        this.height = event.height;
        this.tiltX = event.tiltX;
        this.tiltY = event.tiltY;
        this.pointerType = event.pointerType;
        this.pressure = event.pressure;
        this.rotationAngle = event.rotationAngle;
        this.twist = event.twist || 0;
        this.tangentialPressure = event.tangentialPressure || 0;
      };`

I suggest to add below code to fix the PIXIJS 4.7.1 not working in IE 10

```
Number.isInteger = Number.isInteger || function(value) {
  return typeof value === 'number' && 
    isFinite(value) && 
    Math.floor(value) === value;
};
```

**Comment by themoonrat** [comment]
This is already fixed on the latest dev branch. Sorry about the inconvenience, my mistake for this being there :/

**Comment by bigtimebuddy** [comment]
Closing because this is fixed in dev, but good workaround for people bumping into 4.7.1 issue to include that polyfill.
