### ISSUE TITLE
What is the perfect displacementSprite png image to use to simulate a loop effect ?

### ISSUE THREAD

**Issue by michaelgrc** [pixijs/pixi.js#4821]
Hi,

I want to simulate the zoom effect of a loop on displacement Map, something like on this example : http://pixijs.io/examples/#/filters/displacement-map.js

But on this example the displace.png doesn't do perfectly the loop effect.
Does anyone knows what is the role of each color on the displace.png ?

Also does anyone knows what shape and gradients the displace.png image has to have to simulate a perfect loop effect ? 

Thank you very much

**Comment by ivanpopelyshev** [comment]
according to https://github.com/pixijs/pixi.js/blob/dev/src/filters/displacement/displacement.frag#L14

`map.xy` is actualy RED and BLUE colors of displacements. Also if its gray, then `map.xy - 0.5` is zero, no displacement.

**Comment by themoonrat** [comment]
@michaelgrc Closing as I think you have your answer? If not, re-open! :)
