### ISSUE TITLE
renderTexture is not working with Canvas mode

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4822]
Hi, 

renderTexture is not working with canvas, in fact Im raising this issue after discovering that renderTexture is not working with crosswalk (cocoonjs implementation)

To reproduce just go to the pixi demo:
http://pixijs.io/examples/#/demos/mask-render-texture.js

change line:
```
var app = new PIXI.Application(800, 600);
```

with:

```
var app = new PIXI.Application(800, 600, {forceCanvas:true} );
```

**Comment by themoonrat** [comment]
@DavidGOrtega This demo relies upon using a sprite as a mask, and the Canvas renderer does not support sprites as a mask
