### ISSUE TITLE
Mousemove triggered on all children

### ISSUE THREAD

**Issue by hellraisercenobit** [pixijs/pixi.js#4825]
### Expected Behavior
Mousemove callback should be executed only on desired element

### Current Behavior
Callback is triggered outside element

### Possible Solution
Don't know

### Steps to Reproduce
Create a simple app
Inject some sprites
Apply mousemove event on a single sprite
Callback is triggered everywhere

### Environment

- `pixi.js` version: _e.g. latest stable
- Browser: _e.g. Chrome latest stable
- Device: _e.g. Desktop_

**Comment by themoonrat** [comment]
You can enable this behaviour via turning this flag on
http://pixijs.download/dev/docs/interaction_InteractionManager.js.html#line130
`renderer.plugins.interaction.moveWhenInside = true`

**Comment by hellraisercenobit** [comment]
@themoonrat i saw that in another issue, but how it is supposed to work?

**Comment by hellraisercenobit** [comment]
```
    var myapp = new PIXI.Application({
      width: window.innerWidth,
      height: window.innerHeight,
      view: this.rendering.nativeElement
    });

    myapp.renderer.plugins.interaction.moveWhenInside = true;
```

**Comment by hellraisercenobit** [comment]
@themoonrat it is possible to apply this only on a single element?
