### ISSUE TITLE
Efficient/Safe way to change a texture's Scale Mode on the fly.

### ISSUE THREAD

**Issue by tekintatar** [pixijs/pixi.js#4826]
I am trying to find an efficient way to change the scaleMode of a baseTexture on the fly after it is created. Our app's scale mode is linear and it is working perfectly for screen rendering. However when we want to export our scene to an image file we want to change the scale mode to nearest for certain type of textures (e.g. text) without re-creating and re-uploading it.

I tried doing below but it did not change anything, looks like this does not switch the scale mode once the texture is created.

texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;

So i checked WebGL documentation and figured out that it is possible to change the scaleMode on the fly by binding the texture and unbinding when it is done. I then checked the PIXI GL Core and came up with the following code which works fine:

myRenderer.bindTexture(texture);
texture.baseTexture._glTextures[0].enableNearestScaling();
myRenderer.unbindTexture(texture);

Is this the correct/safe way of changing baseTexture's scaleMode on the fly after it is created? 

Thanks

**Comment by themoonrat** [comment]
@ivanpopelyshev could you confirm please if this is the best way? Is this something we could make easier for v5 if it's not already?

**Comment by ivanpopelyshev** [comment]
v5 treats that automatically.

**Comment by themoonrat** [comment]
:+1:  Will close this one for v4 down then
