### ISSUE TITLE
Rectangles have a diagonal anti-aliasing artifact with WebGL

### ISSUE THREAD

**Issue by oli414** [pixijs/pixi.js#4836]
### Current Behavior
With the WebGL renderer and anti-aliasing enabled filled rectangles have a diagonal line with transparency on them which shows up when the rectangle is drawn overtop something else.

This is quite likely due to a combination of the anti-aliasing, the fact that rectangles are made out of triangles and floating point precision.

Here's a demo that should show the issue:
https://jsfiddle.net/wab3g251/8/

### Expected Behavior
A filled rectangle drawn with a graphics object should be completely filled.

### Steps to Reproduce
- Create a WebGL renderer with anti-aliasing enabled.
- Create a graphics object.
- Draw a rectangle on top of something else.
- Resize the rectangle if the background doesn't show a diagonal line across the rectangle yet.

### Environment

- `pixi.js` version: 4.7.3
- Browser: Chrome 65
- Device: Desktop

**Comment by oli414** [comment]
Possible solution: 
- Rectangles might be drawn with quads instead of triangles in order to prevent the gap.

As I user I'll probably just draw an additional shape in the same color behind my rectangle to fill the lines.

**Comment by ivanpopelyshev** [comment]
Thak you for that demo, now i can send it to people who say that webgl AA doesnt have problems :)

There are no quads in webgl1 as far as i know. Yes, additional shape can help :)

**Comment by nbilyk** [comment]
I wrote a webgl framework which has the exact same problem, so this definitely isn't specific to pixi.js.  It doesn't happen on desktop, and it doesn't happen when antialiasing is off. It seems to be a problem in multiple browsers.  If anybody can figure out a workaround I'd love to hear it.

**Comment by themoonrat** [comment]
@ivanpopelyshev This something we wanna keep open or are we putting it down to browser issues?

**Comment by Qriva** [comment]
_PIXI 4.7.1 Firefox_
I got a lot of these kind of artefacts after addding Sprite to Sprite as children and changing scale.
Any way to fix it or it's kind of webgl limitation?
![obraz](https://user-images.githubusercontent.com/29434176/46046715-6148a600-c122-11e8-9bdf-c531a7a36e33.png)
