### ISSUE TITLE
Image - Mipmapping, Quality

### ISSUE THREAD

**Issue by Bokos-** [pixijs/pixi.js#4845]
Hello Pixi,
please would someone explain me: how Fabric JS did it.. Fabric always has good quality of image (when i am resizing image) unlike pixi which still losing quality? i was trying turn on mipmapping in order to get best quality. 
So i tried changed the scale mode to LINEAR (small images look smudgy) and then to NEAREST (some sizes were okay but most of them looks really bad).
I want to let people manually resize image but dont want to offer them ugly pictures.

I tried your another similiar issues (http://www.html5gamedevs.com/topic/24558-down-scaling-quality-loss/?_fromLogin=1) but any help me.

Thank you all

### Expected Behavior
Original:
<img width="487" alt="screen shot 2018-04-12 at 16 37 42" src="https://user-images.githubusercontent.com/4490694/38685575-8471ef66-3e72-11e8-8a22-9571411d9f7d.png">

Fabric:
<img width="413" alt="screen shot 2018-04-12 at 16 38 11" src="https://user-images.githubusercontent.com/4490694/38685572-7ff8c6b2-3e72-11e8-833c-c1f99ed2bef7.png">

### Current Behavior
Pixi js -> mipmapping linear
<img width="168" alt="screen shot 2018-04-12 at 16 37 16" src="https://user-images.githubusercontent.com/4490694/38685594-8f5d6bbc-3e72-11e8-97a4-9ec338ee4f08.png">

Pixi js -> mipmapping nearest
<img width="240" alt="screen shot 2018-04-12 at 16 57 40" src="https://user-images.githubusercontent.com/4490694/38685625-a3b93aaa-3e72-11e8-91fa-bbde15a19a0e.png">

### Steps to Reproduce
- Take big image scale him down.

### Environment
- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_ (mac)
- Device: _e.g. Desktop_

**Comment by ivanpopelyshev** [comment]
>  i was trying turn on mipmapping in order to get best quality.

For WebGL1, mipmapping works only for textures that have power-of-two size (256x512 or so)

**Comment by Bokos-** [comment]
Yes sorry, i forget, texture is 2048x2048 in example.

**Comment by ivanpopelyshev** [comment]
Can you make a fiddle of it, please? :)

**Comment by Bokos-** [comment]
Yes, thank you for help.
Pixi JS: https://jsfiddle.net/de2o3c5s/22/ ( ver 4.7.1 )
Fabric JS: https://jsfiddle.net/bokos/954hwedm/4/ (ver 1.7.7 )

**Comment by Bokos-** [comment]
Thanks but if you can notice there is still big difference on my pc.
Fabric ( https://jsfiddle.net/bokos/954hwedm/4/ ):
<img width="124" alt="screen shot 2018-04-12 at 18 31 27" src="https://user-images.githubusercontent.com/4490694/38691059-fa908830-3e7f-11e8-87a3-4e95cb5ed710.png">
Pixi ( https://jsfiddle.net/de2o3c5s/27/ ):
<img width="137" alt="screen shot 2018-04-12 at 18 31 39" src="https://user-images.githubusercontent.com/4490694/38691070-febffed6-3e7f-11e8-9457-9bfd815a3b11.png">

So it doesnt solve a problem :/.

**Comment by ivanpopelyshev** [comment]
Nearest: https://jsfiddle.net/de2o3c5s/32/

Both fiddles show upper picture for me. 

![image](https://user-images.githubusercontent.com/695831/38691656-239e8b0a-3e8a-11e8-9f4d-e6cdecb0aed7.png)

**Comment by ivanpopelyshev** [comment]
If you want to make better quality for resize for particular purpose, you have to use sequence of rendertextures with filters applied, and i dont know which filters are suited for it.

**Comment by hendrysadrak** [comment]
@Bokos- 
You have to set resolution manually by your displays pixel ratio for pixi.js.
I updated your example https://jsfiddle.net/de2o3c5s/40/

**Comment by Bokos-** [comment]
Good Job! Thanks.

**Comment by Bokos-** [comment]
FYI check it now! 

<img width="443" alt="screen" src="https://user-images.githubusercontent.com/4490694/39113840-36808c22-46dd-11e8-9339-3aba7bd569c0.png">
