### ISSUE TITLE
Double dynamically generated textures in scaled sprite

### ISSUE THREAD

**Issue by Ewanse** [pixijs/pixi.js#4848]
Hello,
I generate base texture from canvas, next I call update method and getting result.
But, if I try to scale or rotate sprites with this texture, I get double textures in sprite.

Codepen example:
https://codepen.io/ewanse/pen/GxaQGM

- `pixi.js` version: 4.7.3
- Browser: All
- Device: All

**Comment by themoonrat** [comment]
@ivanpopelyshev What do you think we should do with this? I don't consider it a _major_ bug on 4.x, as there is a workaround, and it's fixed on v5... so think we should close?

**Comment by ivanpopelyshev** [comment]
We should ask @bigtimebuddy if its worth backport for v4.
