### ISSUE TITLE
loaded JSON object contains error: TypeError: JSON.parse is not a function

### ISSUE THREAD

**Issue by Wikonator** [pixijs/pixi.js#4850]
Your issue may already be reported! Please search [existing issues](../) before creating one.

### Current Behavior
Reffering to loader.resources["nameOfJson.json"]returns undefined. When console.logging loader.resources I see the object as loaded with the correct name but the "error" property states: "error: Error: Error trying to parse loaded json: TypeError: JSON.parse is not a function"

    var stage = new PIXI.Container();
    var loader = new PIXI.loaders.Loader();

    .add('exoWalkSheet', 'images/ExoWalkTex.png')
    .add('exoWalkJson', 'images/ExoWalkTex.json')
    .load(setup);

    function setup() {
        stage.interactive = true;
        console.log("habbening");
        var rect = new PIXI.Rectangle( 0, 1002, 340, 174 );

        var exoId = loader.resources["exoWalkJson"].textures;
        var secondTexture = loader.resources["exoWalkSheet"].texture;
        texture.frame = rect;
        console.log(loader.resources);

        var exoSprite = new PIXI.Sprite( exoId["1_00000.png"]);
        console.log(exoId);

exoId returns Undefined
log returns habbening
loader.resources return > 
    exoWalkJson: Object { _flags: 2, name: "exoWalkJson", url: "images/ExoWalkTex.json", … }
    exoWalkSheet: Object { _flags: 2, name: "exoWalkSheet", url: "images/ExoWalkTex.png", … }

- `pixi.js` version: current / latest
- Browser: Firefox (same in Chrome)
- Device: Win 8 Desktop

**Comment by Wikonator** [comment]
an npm http-server

  https://www.npmjs.com/package/http-server

-could- it be the mime type?

**Comment by ivanpopelyshev** [comment]
json works fine for me through http-server . btw, i recommend to use `http-server -c-1` to launch it without cache.

Anyway, it should work. If it doesnt work for you, give me zip-file with app that i can test and i'll find whats wrong.

**Comment by Wikonator** [comment]
I've used a reserved name for my JSON and to top it off I made it const.

Everything works now, please close the issue
