### ISSUE TITLE
Quantification rotation && pivot

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4852]
Guys am not very good in math , if a good guys in math can help me .
How can you compute rotation base on pivot in pixi ?
Example i move pivot to XY.
And i move rotation to ( randian || degree )
After i move again pivot with mouse compute... all became weird..

How i can compute rotation but base on the position from pivot ?
for now here it my try code.
thank guys, i have difficult with deep math.
Also, I would like to compute skew :)

```javascript
    // update QuickEdit proprety mode 
    function update_quickEditMode(objSprite){
        const D = 45; // distance marge for active a mode
        const difX = mX-memX;
        const difY = mY-memY;
        let angle = Math.atan2(difY, difX);
        const kX = objSprite.skew._x*difX; // skew for help compute pivot ?
        const kY = objSprite.skew._y*difY; // skew for help compute pivot ?
        // angle = Math.radians(angle *180);
        if(!QuickEditMode){// wait move mouse in a direction for identify wich mode
            QuickEditMode = difX>D&&'rot'||difX<-D&&'sc'||difY>D&&'ske'||difY<-D&&'piv'||false;
        }else{
            switch (QuickEditMode) {
                case 'rot':
                objSprite.rotation=(angle);
                break;
                case 'sc':
                objSprite.scale.set(-((difX-D)/100),(D-difY)/100)
                break;
                case 'ske':
                objSprite.skew.set((D-difX)/100,(difY-D)/100)
                break;
                case 'piv':
                objSprite.pivot.set((difX*-1)/objSprite.scale._x+kY,(difY*-1)/objSprite.scale._y+kX)
                const color = objSprite.linePivot.graphicsData[0].lineColor
                objSprite.linePivot.clear();
                objSprite.linePivot.lineStyle(2, color, 0.6);
                objSprite.linePivot.moveTo(0,0).lineTo(objSprite.pivot.x||0.1, objSprite.pivot.y).endFill();
                objSprite.lineH.position.set(objSprite.pivot.x,objSprite.pivot.y);
                break;
            };
        };
    };
```

![image](https://user-images.githubusercontent.com/24865815/38853578-badc0600-41eb-11e8-84ad-57aa61061d3d.png)

I have succeeded in allowing the mouse factor to allow all other proprety to work intuitively, but I block when the rotation or skew is engaging.
All the mouse come very weird psychedelic !?
If you need video i can give.

**Comment by ivanpopelyshev** [comment]
Sorry, its too difficult for stupid me in the morning. Can you make a fiddle? I just dont understand what you want to do.

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
here 
https://jsfiddle.net/jonforum/ow9w7rfz/1/
as you can see , i don't know the math formula for compute the position with rotation.

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
a friend help me a little bit but we are stock here.
Are you able to make the saure follow mouse correctly in you side ?
https://jsfiddle.net/jonforum/ow9w7rfz/8/

I am convinced that need use .cos and .sin , but not sure...
