### ISSUE TITLE
Video current time issue when force canvas is true

### ISSUE THREAD

**Issue by Anthelmed** [pixijs/pixi.js#4854]
Hi,
Setting the video currentTime value make the sprite disappeared when the renderer is a canvas.

https://jsfiddle.net/zfyw7t46/21/

pixi.js version: 4.7.3
Browser:  Chrome 65

**Comment by allanbreyes** [comment]
^ @ivanpopelyshev: thought this might be of interest to you... potentially another Chrom(ium) bug.

This works butter smooth in Firefox 59.

**Comment by ivanpopelyshev** [comment]
i think there were two bugs like that in threejs and they are fixed in canary. Can you check it there?

**Comment by themoonrat** [comment]
@Anthelmed Closing as I'm not sure there is anything PIXI can do about this, it appears to be a browser issue I'm afraid
