### ISSUE TITLE
Change ticker to 120 FPS

### ISSUE THREAD

**Issue by JackyGithubUnderscore** [pixijs/pixi.js#4855]
Hi! I've just recently started using Pixi.JS.

I'm trying to set a ticker to update 120 times a sec. In the docs, it says I should be able to change it using the ticker.speed. When I do so, it shows the variable is indeed changed, but I don't get more frequent updates at all.

```
window.onload = function(){
	var tick = 0

	setInterval(function(){
		console.log(tick)
		tick = 0
	},1000)

	var ticker = new PIXI.ticker.Ticker()
	ticker.speed = 2
	ticker.add(function(){
		tick += 1
	})
	ticker.start()
}
```

Also how can I change the shared ticker?

**Comment by bigtimebuddy** [comment]
Check out this:
https://pixijs.download/dev/docs/PIXI.ticker.Ticker.html#FPS

**Comment by bigtimebuddy** [comment]
Try changing the default frames per millisecond setting:

```js
PIXI.settings.TARGET_FPMS = 0.12
const ticker = new PIXI.ticker.Ticker();
console.log(ticker.FPS); // should be 120
```

Alternatively you change the `elapsedMS` property of ticker

```js
const ticker = new PIXI.ticker.Ticker();
ticker.elapsedMS = 1 / 0.12;
console.log(ticker.FPS); // should be 120
```

**Comment by JackyGithubUnderscore** [comment]
@bigtimebuddy, awesome! It's working now.

**Comment by JackyGithubUnderscore** [comment]
When I try to hook the ticker up to a function, it becomes 60 ticks again.

**Comment by bigtimebuddy** [comment]
@JackyGithubUnderscore from the docs:

```

**Comment by JackyGithubUnderscore** [comment]
Hmmm.. I see. It's wired, cause when I use setInterval(function(){},1000/120), I have no problem running at that speed.

**Comment by JackyGithubUnderscore** [comment]
Oh, the FPS does cap at 60, It's just able to handle 60+ tick updates.
- Solved.
