### ISSUE TITLE
[Question] Moving reverse mask

### ISSUE THREAD

**Issue by arsenikolupin76** [pixijs/pixi.js#4857]
Hi,
I'm trying to create a reverse mask (like the one displayed in the attached image). On mouseover on the circle the mask should move following the mouse pointer. I tried to use masks but no way...

![bg-circle](https://user-images.githubusercontent.com/3216025/39102771-1072daac-46a7-11e8-9bcd-90d57276319e.jpg)

**Comment by themoonrat** [comment]
Had any luck @arsenikolupin76?

**Comment by arsenikolupin76** [comment]
Not at all @themoonrat
