### ISSUE TITLE
scrolling-text marquee in PIXI js

### ISSUE THREAD

**Issue by PappuBache** [pixijs/pixi.js#4860]
I have an application using Pixi.js and it uses WebGLRenderer.

I want to do a scrolling-text marquee with fade out gradient on the left and right edges similar to this CSS example below.

https://codepen.io/jamesbarnett/pen/kfmKa

Anyone has done it before ? any help is appreciated.

**Comment by djmisterjon** [comment]
I have already done something similar in a old project.
By downloading the script, I think you should have a good idea to how proceed.
You need use mask and container for parent.
https://forums.rpgmakerweb.com/index.php?threads/pixi-text-multi-motions-styles-core-v1-0.86117/

**Comment by themoonrat** [comment]
@PappuBache closing as you have been kindly shown an example :)
