### ISSUE TITLE
Scaling issues on devices with fractional device pixel ratios

### ISSUE THREAD

**Issue by danrostron** [pixijs/pixi.js#4866]
### Expected Behavior
On devices which have fractional device pixel ratios (ie. Pixel 2 which has a device pixel ratio of 2.625), I expect PIXI to scale the application correctly.

### Current Behavior
When setting the renderer resolution using window.devicePixelResolution on devices which have fractional device pixel resolutions (ie. Google Pixel 2 is 2.625), the application is getting skewed on the X-axis is seems. If I Math.floor(window.devicePixelResolution) it works fine, but we're not using the true resolution capable on the device.

When _resolution: window.devicePixelRatio_ ie. 2.625
![screenshot_20180426-125610](https://user-images.githubusercontent.com/2691545/39309487-0da1e7e4-4960-11e8-9c2e-380701920541.png)

When _resolution: Math.floor(window.devicePixelRatio)_ ie. 2
![screenshot_20180426-143559](https://user-images.githubusercontent.com/2691545/39309596-4e7c14f6-4960-11e8-8611-443b759f1191.png)

I can't see where the application is getting skewed. The values for canvas size seem correct (5040 x 2835) which is 1920 x 1080 * 2.625. The canvas uses CSS styling and sets the width and height correctly to 732 x 411 px.

### Possible Solution
Allow fractional device pixel ratios.

### Steps to Reproduce
Create a renderer using the following:

let rendererOptions: RendererOptions = {
			width: 1920,
			height: 1080,
			resolution: window.devicePixelRatio
		};
		this._app = new PIXI.Application(rendererOptions);

Test on any devices which uses fractional device pixel ratios.

### Environment

- `pixi.js` version: 4.5.6
- Browser: _Chrome 66.0.3359.126_
- Device: _Google Pixel 2_

**Comment by ivanpopelyshev** [comment]
Please look at https://github.com/pixijs/pixi.js/issues/4153 , maybe its your issue.

**Comment by ivanpopelyshev** [comment]
Also, look at CSS dimensions in chrome in PC with same resolution, maybe its wrong. How do you resize the canvas?

**Comment by ivanpopelyshev** [comment]
did you specify "autoResize:true" in renderer options? make sure its false, or pixi will override your settings: https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/SystemRenderer.js#L225

**Comment by danrostron** [comment]
No, we're not using autoResize. Tried setting to false to make sure, and doesn't make any difference. When testing on a Mac in Chrome emulator, the scaling issue doesn't replicate. Only on device itself.

**Comment by danrostron** [comment]
You can see on the screenshot below, the canvas size and style size all seem correct.

<img width="1379" alt="screen shot 2018-04-26 at 15 25 36" src="https://user-images.githubusercontent.com/2691545/39311933-24beddfa-4966-11e8-9652-dfe64e8f12e3.png">

**Comment by ivanpopelyshev** [comment]
I suspect that it cant create framebuffer larger than 4096.

**Comment by ivanpopelyshev** [comment]
Yes.

**Comment by danrostron** [comment]
Great Ok, so the only solution for now is as per this ticket - https://github.com/pixijs/pixi.js/issues/4153 whereby we have to resize the renderer and resolution if the buffer size is too small?

Is it a common strategy just to limit the resolution to 2 for Android devices?

**Comment by themoonrat** [comment]
For games on mobile, I disagree with the idea of a direct link of window.devicePixelRatio and the PIXI resolution setting.

You say limiting the resolution to 2... But that's still rendering at 4k! A punishing resolution causing poorer performance and battery drain to push more pixels than the device actually has. The actual number of pixels on the pixel 2 is 1920x1080. So if you're game is natively at that resolution, then your resolution should be 1.

**Comment by frankmcpolin** [comment]
Hi all, I work with Dan and we're trying to figure this out. We were having problems with blurry images and pixelated text and read a ton of threads earlier this week suggesting that the best way to get quality sharp rendering on devices was to set the renderer's resolution to be the devicePixelRatio (In particular this one: https://github.com/pixijs/pixi.js/issues/621). So how do these 2 solutions reconcile with each other? 

Thanks in advance.

**Comment by themoonrat** [comment]
@frankmcpolin A higher resolution helps, and also roundPixels can help. If a global setting doesn't work, I had a PR for v4 that i'll update for v5 https://github.com/pixijs/pixi.js/pull/4833 that allowed Text objects to always be rendered to a whole pixel whilst leaving other sprites alone.

If you're still having issues, feel free to re-open with a jsfiddle with an example of what you have so far, and we could look at best solutions to get your game looking sharper
