### ISSUE TITLE
Code should not use document.createElement('canvas') in order to have a pure GL renderer

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4868]
Hi,

The code uses a lot inline canvases, I would like to use this library in the future with reac-native using [glview](https://github.com/gre/gl-react-native-v2) or [gcanvas](https://github.com/alibaba/GCanvas) however I can find too much canvas creation in the code.

A good solution could be calling a function that could be later on rewritten. What do you think?

**Comment by bigtimebuddy** [comment]
Using the tools you described has not been a common use-case for PixiJS so no one has implemented it yet. I suspect that there would be a lot more work to make this work successfully than abstracting createElement for canvas. There are undoubtedly other DOM APIs being used too. But if you want to take a stab at it, test it and make a PR, please give it a go.

**Comment by ivanpopelyshev** [comment]
That's the list of used functions - https://github.com/Prozi/pixi-shim

**Comment by ivanpopelyshev** [comment]
We have no guarantees about performance and availability of pixi on this thing. Try to make bunnymark on it: https://github.com/pixijs/bunny-mark

**Comment by bigtimebuddy** [comment]
While some Node.js-only implements for pixi have focused on trying to shim DOM APIs, it wouldn't be very hard to make an adapter for all these external calls. It would benefit both Node.js (server-side rendering) and situations described in this issue. I'd consider something like this for v5. I agree with Ivan that any attempts with v4 should be forked.
