### ISSUE TITLE
Pointertap emited on "non-pointerdowned" displayobject

### ISSUE THREAD

**Issue by selirion04** [pixijs/pixi.js#4869]
### Steps to Reproduce
1. Create two buttons (Sprites)
2. Clamp first of them
3. Move pointer to other button
4. Release mouse button 

### Expected Behavior
No buttons pressed (e.g. no buttons pressed if use click event instead of pointertap event)

### Current Behavior
Second button pressed

### Environment
- `pixi.js` version: 4.7.3
- Browser: latest chrome, firefox
- Device: Desktop and others.
- Could reproduced in http://pixijs.io/examples/#/basics/click.js with attached code pasted
[click.txt](https://github.com/pixijs/pixi.js/files/1957461/click.txt)

**Comment by bigtimebuddy** [comment]
I noticed this bug recently too. Thanks for filing the issue. @andrewstart or @themoonrat, could you guys look at this?
