### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of undefined v5

### ISSUE THREAD

**Issue by ellipticaldoor** [pixijs/pixi.js#4870]
### Expected Behavior
Loader adds an image.

### Current Behavior
When trying to add an image you get the following error
```
Uncaught TypeError: Cannot read property 'add' of undefined
```

### Possible Solution
I don't know, maybe this happens because I'm using https://parceljs.org/
Though on v4 I don't have any problems.

### Steps to Reproduce
This is the code that produces this error
``` js
import { Application, loader } from 'pixi.js';
import characterImage from './character.png';

const app = new Application();
document.body.appendChild(app.view);

loader.add(characterImage);
```
You can find a repo that reproduces the error here https://github.com/ellipticaldoor/pixi_add_error

### Environment
Im using parcel 1.7.1

- `pixi.js` version: "^5.0.0-alpha.2"
- Browser: _Chrome 66.0.3359.139 
- Device: macos 10.13.4

**Comment by ivanpopelyshev** [comment]
```js
import { Application, Loader } from 'pixi.js';

const loader = Loader.shared;
//or this one
const loader = app.loader;
```

**Comment by ellipticaldoor** [comment]
Loader.shared is working for me 🙂
