### ISSUE TITLE
Where is the loader using the new ES6 imports on v5?

### ISSUE THREAD

**Issue by ellipticaldoor** [pixijs/pixi.js#4871]
### Expected Behavior
``` js
import { Loader } from '@pixi/loaders'
```
Should work

### Current Behavior
I get the error
```
Uncaught TypeError: Cannot read property 'state' of undefined
```

### Possible Solution
Right now it works with 
``` js
import { Loader } from 'pixi.js'
```

### Environment

- `pixi.js` version: 5.0.0-alpha.2

**Comment by ivanpopelyshev** [comment]
`state` variables exist only in Filters/FilterSystem. Are you sure? Please prodive more details.

**Comment by ellipticaldoor** [comment]
Okay, I think this is not related with the Loader. Maybe I'm missing one import.
If you uncomment the first line it works
``` js
// import PIXI from 'pixi.js'
import { Application } from '@pixi/app'
import { Sprite } from '@pixi/sprite'
import { Texture } from '@pixi/core'
import characterImage from './assets/character.png'

const app = new Application()

document.body.appendChild(app.view)

const playerTexture = Texture.fromImage(characterImage)
const player = new Sprite(playerTexture)

app.stage.addChild(player)
```
Without * import PIXI from 'pixi.js'* I get this error

![image](https://user-images.githubusercontent.com/3449006/39408423-db93c6da-4bcd-11e8-977b-618d9f6e8e60.png)

**Comment by ivanpopelyshev** [comment]
Look at https://github.com/pixijs/pixi.js/blob/next/bundles/pixi.js/src/index.js

If you dont use the bundle, you have to register plugins that you are using with `core.registerPlugin`. In this case, sprite renderer wasnt registered.

**Comment by ivanpopelyshev** [comment]
We cannot add `registerPlugin` calls in modules themselves, because we dont know whether it will be called before or after creation of renderer/application combo.

Make sure that all registrations run before you create the Application.

**Comment by ellipticaldoor** [comment]
Thank you, this code solves the problem.
``` js
import { Application } from '@pixi/app'
import { SpriteRenderer, Sprite } from '@pixi/sprite'
import { Renderer, Texture } from '@pixi/core'
import characterImage from './assets/character.png'

Renderer.registerPlugin('sprite', SpriteRenderer)

const app = new Application()

document.body.appendChild(app.view)

const playerTexture = Texture.fromImage(characterImage)
const player = new Sprite(playerTexture)

app.stage.addChild(player)
```
