### ISSUE TITLE
Texture Error: frame does not fit inside the base Texture dimensions v5

### ISSUE THREAD

**Issue by ellipticaldoor** [pixijs/pixi.js#4873]
### Expected Behavior
Make a texture smaller changing its frame with a Rectangle.

This is the code
``` js
import PIXI from 'pixi.js'
import { Application } from '@pixi/app'
import { Sprite } from '@pixi/sprite'
import { Rectangle } from '@pixi/math'
import { Texture } from '@pixi/core'
import characterImage from './assets/character.png'

const app = new Application()
document.body.appendChild(app.view)

const playerTexture = Texture.fromImage(characterImage)
const player = new Sprite(playerTexture)
playerTexture.frame = new Rectangle(0, 0, 40, 40)
player.position.set(100, 100)

app.stage.addChild(player)
```

### Current Behavior
With the code above I get this error when I load the page for the first time
![image](https://user-images.githubusercontent.com/3449006/39408457-686cd5b0-4bce-11e8-8e9f-7069a56c5cf3.png)

If I reload I don't get this error any more.
Also if I remove the line that changes the frame this error never happens.

- `pixi.js` version: 5.0.0-alpha.2

**Comment by ivanpopelyshev** [comment]
Same as in pixi-v4, you have to preload the image or somehow specify its dimensions before you specify custom frame.

You can use `baseTexture.setSize()`  [setSize](https://github.com/pixijs/pixi.js/blob/next/packages/core/src/textures/BaseTexture.js#L342) if you want to specify dimensions before image is actually loaded. Im not sure that it'll work, but you can try :)

**Comment by ellipticaldoor** [comment]
This code works for me
``` js
import { Application } from '@pixi/app'
import { Sprite, SpriteRenderer } from '@pixi/sprite'
import { Rectangle } from '@pixi/math'
import { BaseTexture, Renderer, Texture } from '@pixi/core'
import characterImage from './assets/character.png'

Renderer.registerPlugin('sprite', SpriteRenderer)

const app = new Application()
document.body.appendChild(app.view)

const base = new BaseTexture(characterImage)
base.setSize(64, 64)
const playerTexture = new Texture(base)
playerTexture.frame = new Rectangle(0, 0, 40, 40)
const player = new Sprite(playerTexture)
player.position.set(100, 100)

app.stage.addChild(player)
```
Is this the proper way for using BaseTexture?

**Comment by ivanpopelyshev** [comment]
It works? nice. Either that, either preload images with like here: http://pixijs.io/examples/#/demos/texture-rotate.js . However its differs for v5, you have to use `app.loader` or `PIXI.Loader.shared`.

**Comment by ellipticaldoor** [comment]
Yes with the loader it works just fine :)

**Comment by ellipticaldoor** [comment]
It looks like it doesn't work on firefox

**Comment by ellipticaldoor** [comment]
Can I use the loader and second time after load is finished?

Maybe I don't want to load all my assets at the beginning

**Comment by ellipticaldoor** [comment]
Maybe something like this?

```js
export const textureOf = imagePath => {
	const texture = TextureCache[imagePath]
	if (texture) return texture

	Loader.shared.add(imagePath)
	Loader.shared.load()
	return TextureCache[imagePath]
}
```
This code doesn't works

**Comment by ellipticaldoor** [comment]
Okay, I'm trying something like this
``` js
const asyncLoad = filePath =>
	new Promise((resolve, reject) => {
		Loader.shared.add(filePath)
		Loader.shared.load(() => resolve())
	})

export const textureOf = async imagePath => {
	const texture = TextureCache[imagePath]
	if (texture) return texture

	await asyncLoad(imagePath)
	return TextureCache[imagePath]
}

```
But now I get the error 
![image](https://user-images.githubusercontent.com/3449006/39409467-879fe4c0-4bdf-11e8-9e9f-09a50f1ad001.png)

**Comment by ivanpopelyshev** [comment]
What do you want to achieve? I mean that you have to create texture with that frame only when that thing is loaded. 

Also beware, load() happens only one time, you have to reset() loader after that. Please read loader docs.

**Comment by ivanpopelyshev** [comment]
Sync way: use fromImage, specify size if you need to know width/height before it loads.

Async way by @xerver: add all the textures to loader. Call `load`. Create new textures and sprites only when loading is done.

**Comment by ivanpopelyshev** [comment]
Look, multiple resources are added, stage created after that: http://pixijs.io/examples/#/projection/runner.js

**Comment by themoonrat** [comment]
@ellipticaldoor closing as I think you found your solution? Feel free to re-open if you still have issues :)

**Comment by ellipticaldoor** [comment]
Yes, my solution was to use the code that I shared

**Comment by ellipticaldoor** [comment]
Oh! Sorry, it was a mistake. I was thinking in other stuff, yup this error is still there so maybe it should be reopened
