### ISSUE TITLE
[Question] About getLocalBounds()

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixi.js#4874]
```js
const app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb})
document.body.appendChild(app.view)

const bunnies = [
    PIXI.Sprite.fromImage('required/assets/basics/bunny.png'),
    PIXI.Sprite.fromImage('required/assets/basics/bunny.png'),
    PIXI.Sprite.fromImage('required/assets/basics/bunny.png')
]



const container = new PIXI.Container()
app.stage.addChild(container)

container.addChild(...bunnies)

bunnies.forEach((bunny, i) => {
    bunny.x = i * 100
})

console.log(bunnies[1].getLocalBounds()) // output: {x: -0, y: -0, ...}
```

Why not output `{x: 100, y: 0, ...}` ? Did I get the wrong idea?

**Comment by ivanpopelyshev** [comment]
Because its not loaded yet.  Use async loader like here: http://pixijs.io/examples/#/demos/texture-rotate.js

**Comment by JetLua** [comment]
```js
const app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb})
document.body.appendChild(app.view)

PIXI.loader
    .add('bunny', 'required/assets/basics/bunny.png')
    .load(main)


function main() {

    const bunnies = [
        PIXI.Sprite.fromFrame('bunny'),
        PIXI.Sprite.fromFrame('bunny'),
        PIXI.Sprite.fromFrame('bunny')
    ]



    const container = new PIXI.Container()
    app.stage.addChild(container)

    container.addChild(...bunnies)

    bunnies.forEach((bunny, i) => {
        bunny.x = i * 100
    })

    console.log(bunnies[1].getLocalBounds().x, bunnies[1].x) // output: -0, 100
}

```

@ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
Now it has the right width/height. X coord is 0 because you asked local bounds. There's also global getBounds(). If you want bounds of bunny relative to the parent.. well.. Flash had that, we dont :( Though we might add it in the future.

**Comment by JetLua** [comment]
Thank you, I'm just confused. But does not affect the use, completely may use the `bunny.x` substitution.

**Comment by JetLua** [comment]
Got it.

**Comment by JetLua** [comment]
![image](https://user-images.githubusercontent.com/6738986/39415164-9af4a28e-4c72-11e8-840f-d521b73560d2.png)

`getBounds()` always get the right results

can i use : `child.getLocalBounds() = child.getBounds() - parent.getBounds()`

@ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
If that's what you need, yep, do it. "-" in that case is a subtraction of both `x` and `y` components.
