### ISSUE TITLE
Documentation: Capitalize letter "t" in "Twitter"

### ISSUE THREAD

**Issue by adnanislam** [pixijs/pixi.js#4876]
In the first section of the current README it states to follow the lead contributors on "twitter," but I believe it should be capitalized because Twitter is a proper noun. It also helps differentiate between Twitter (the social media platform) and twitter (the verb that describes the sounds that birds make). It's a very minor point and should be a very trivial fix!

**Comment by bigtimebuddy** [comment]
Welcome a PR for this. Good catch!
