### ISSUE TITLE
Bitmap Font issue

### ISSUE THREAD

**Issue by Sevenops** [pixijs/pixi.js#4877]
Here is the code i try to use but it doesn't work also i couldn't find any info on net about font loading any help pls ?
`app.loader.add("fonts/sf.fnt");
app.loader.load(function (e,b) {
    console.log(PIXI.BitmapText.fonts);
    let text = new PIXI.BitmapText("text using a fancy font!", {font:"Soopafresh", align: "right"});
    text.x=200;
    text.y=200;
    app.stage.addChild(text);
});`

**Comment by themoonrat** [comment]
The example of loading and using bitmap fonts here: https://pixijs.io/examples/#/demos/text-demo.js 
should get you up and running :)
