### ISSUE TITLE
[SUGGESTION] Backport DisplayObject.prototype.filters property from v5 

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4881]
I found there is a commit "Backport filterPoolKey property from v5 "

I'm glad to see that you don't give up v4, and try to bring some better features from v5 to v4.

----
I hope this commit  about DisplayObject.prototype.filters in  v5 https://github.com/pixijs/pixi.js/commit/3b303d15b0aa08f274d0a4d17020f2bcdafa2de7#diff-cc987d42d04990b6318d3335b4997f12 could be brought   to v4.

**Comment by themoonrat** [comment]
Since v4 is on 'critical bug fixes only', I doubt this'll happen?

**Comment by finscn** [comment]
@themoonrat  ,  you said  'critical bug fixes only' , but there are some PRs & commits about feature & API changing  in July 2018. 
So  I hope pixi core team could rethink about this PR.

Because there are some plugins of pixi are only support PIXI v4 ,
So the PIXI v4 will still be main version for a very long time.

Don't give up on improving it  , please
