### ISSUE TITLE
Video type wrongly set

### ISSUE THREAD

**Issue by dtemes** [pixijs/pixi.js#4882]
Trying to use a video from cloudfront, with a url like:

http://mycd.com/media/myvideo.mp4?Expires=12345678...

In firefox the video will not load and firefox will complains about the wrong type of video

### Expected Behavior
The media type is set to video/mp4

### Current Behavior
type is set to 'video/mp4?Expires=12345678......'

note: my cdn config is not setting a proper mime type
### Possible Solution

change the createSource function in videoBaseTexture.js which parses the video url badly:

if (!type)
    {
        type = `video/${path.substr(path.lastIndexOf('.') + 1)}`;
    }

### Steps to Reproduce
var texture = PIXI.Texture.fromVideoUrl('http://mycd.com/media/myvideo.mp4?Expires=12345678...');
var videoSprite = new PIXI.Sprite(texture);

### Environment

- `pixi.js` version: _e.g. 4.7.3_
- Browser: Firefox

**Comment by gooderist** [comment]
Hello, can I work on this? If so, is there anything else I should be aware of?

**Comment by gooderist** [comment]
Hello, can I work on this? Is it up for grabs?

**Comment by bigtimebuddy** [comment]
Fixed in **dev**. Will be released in v4.8.2
