### ISSUE TITLE
Cannot read property 'Group' of undefined - v5

### ISSUE THREAD

**Issue by ellipticaldoor** [pixijs/pixi.js#4883]
### Expected Behavior
I wan to be able to create a group and order the z index display.

### Current Behavior
When trying to follow the example from here http://pixijs.io/examples/#/layers/zorder.js I get the error
``` js
Uncaught TypeError: Cannot read property 'Group' of undefined
```
### Possible Solution
There is a new way to manage the z index on v5 or that functionality is not yet ready?

### Steps to Reproduce
Just run zorder.js with v5

### Environment

- `pixi.js` version: "^5.0.0-alpha.2"
- Browser: 66.0.3359.139

**Comment by ivanpopelyshev** [comment]
1. you need https://github.com/pixijs/pixi-display/
2. i didnt make it for v5 yet, but you can swap `WebGLRenderer` to `Renderer`  and `renderWebGL` to `render` inside that js, and it'll work.

**Comment by ellipticaldoor** [comment]
Do you have an example? I'm a little bit lost here.

You mean that I should make a PR changing that in the code?

**Comment by ivanpopelyshev** [comment]
no, just take JS file, and swap those things i mentioned, and it'll work. also, `particles.ParticleContainer` -> `ParticleContainer`.

**Comment by ellipticaldoor** [comment]
Thank you Ivan, I will try it on the weekend.

**Comment by ellipticaldoor** [comment]
There is no other way to control zIndex?

I don't want to manually download a dependency a tweak it...

**Comment by ellipticaldoor** [comment]
I really tried to make it work with v5 but its not working

**Comment by ellipticaldoor** [comment]
Just found a solution!!!

``` js
import { setup as mapSetup } from '~/items/map/map'
import { setup as playerSetup } from '~/items/player/player'
import { setup as cameraSetup } from '~/items/camera/camera'
import { setup as collisionSetup } from '~/items/collision/collision'
import { map } from 'ramda'
import { Container } from 'pixi.js'

module.exports = app => {
	collisionSetup(app)
	const camera = cameraSetup(app)
	const mapLayers = mapSetup(app)
	const playerLayer = playerSetup(app, camera)

	const groundLayerContainer = new Container()
	groundLayerContainer.addChild(...mapLayers[0])

	const entityLayerContainer = new Container()
	entityLayerContainer.addChild(...mapLayers[1])

	map(layerToDraw => camera.addChild(layerToDraw), [
		groundLayerContainer, // Ground
		playerLayer, // Player
		entityLayerContainer, // Entities
	])

	// Here you change the index of the layers :)
	camera.setChildIndex(groundLayerContainer, 1)
	camera.setChildIndex(entityLayerContainer, 0)
	camera.setChildIndex(playerLayer, 2)

	app.stage.addChild(camera)
}

```

Is this a good approach?

**Comment by ivanpopelyshev** [comment]
Well, if it works for you ;)
