### ISSUE TITLE
Incorrect rotation of circles

### ISSUE THREAD

**Issue by TngSam** [pixijs/pixi.js#4884]
Hi! I tried to rotate tiny circles and then they became like a triangles.

https://jsfiddle.net/6ee4n175/

When I setting up rotation to any value (e.g. view.rotation = 0.1), this happens. When the rotation is 0 everything is fine! View is the container. Where's the problem?

![default](https://user-images.githubusercontent.com/25546058/39535014-87ab2f48-4e3b-11e8-909c-ebf954770e33.PNG)

Thanks!

FIXED

**Comment by ivanpopelyshev** [comment]
Make a fiddle.

**Comment by TngSam** [comment]
https://jsfiddle.net/6ee4n175/
Here it is.

**Comment by ivanpopelyshev** [comment]
strange, i thought i answered it. add `antialias: true` in renderer params.

**Comment by TngSam** [comment]
Thank you! It's become better!

**Comment by TngSam** [comment]
In addition, can you tell how to turn off the rotation of PIXI.Container?

**Comment by ivanpopelyshev** [comment]
What do you mean turn it off?

**Comment by TngSam** [comment]
Well, imagine I want to rotate a container, which contains two shapes. What if I don't want to rotate some shape from this container?

**Comment by ivanpopelyshev** [comment]
you can rotate `Graphics` back: `graphics.rotation = -container.rotation`.

**Comment by ivanpopelyshev** [comment]
Flash didnt have this feature, pixi doesnt have it yet. Spine has transforms that can ignore parent rotation, scale or flip.

**Comment by TngSam** [comment]
thank you!
