### ISSUE TITLE
DeltaTime on Ticker update is incorrect

### ISSUE THREAD

**Issue by eiko** [pixijs/pixi.js#4885]
`settings.TARGET_FPMS` is supposed to set a limit for how many MS elapse each frame. By default, it equals 0.06, which roughly translates to a cap of 16 MS per frame.

But on [line 390 of Ticker.js](https://github.com/pixijs/pixi.js/blob/72edf398277c4d78e63e78cca29bfe4938e9253f/src/core/ticker/Ticker.js#L390) `TARGET_FPMS` is a direct part of the deltaTime calculation:

`this.deltaTime = elapsedMS * settings.TARGET_FPMS * this.speed;`

This takes `elapsedMS` which is generally around 16 MS, and multiplies it by `0.06`, setting deltaTime to an average value of  1 MS, causing Ticker to claim an update rate of around 1000 FPS.

`TARGET_FPMS` is already used to calculate `this._maxElapsedMS`, so I believe it's already doing it's job. We should be able to remove it from the `deltaTime` calculation:

`this.deltaTime = elapsedMS * this.speed;`

**Comment by ivanpopelyshev** [comment]
`deltaTime===1` corresponds to 1 frame, its working as intended. `TARGET_FPMS ` is how many frames are elapsed per milliseconds. Yes, its strange, we should name it `deltaFrame`

That way if user writes `element.x += 5` and it works fine on 60FPS, he cant just add `* deltaTime` to make smooth animations.

**Comment by ivanpopelyshev** [comment]
You can write your own ticker with same interface and use it in your custom application class, and even assign `PIXI.tickers.shared` to it. or `ticker.shared`, i dont remember.

Make sure that AnimatedSprite and other things that you add in it, like your own tween manager, understand what exactly do you pass in.

**Comment by fightingcat** [comment]
This is really confusing, I have wasted my time on this.

**Comment by jcyuan** [comment]
const ms = deltaTime / PIXI.settings.TARGET_FPMS;

**Comment by jcyuan** [comment]
emmm.... I think this can be closed.
