### ISSUE TITLE
InteractionEvent.target is null in 'pointermove' event on touch devices

### ISSUE THREAD

**Issue by guigzz** [pixijs/pixi.js#4887]
### Expected Behavior
target value should be set to the object which caused this event to be dispatched.

### Current Behavior
target value is `null`

### Steps to Reproduce
Just set a pointermove callback on any DisplayObject and log the target property in the callback.
[Here is a pen](https://codepen.io/guigzz/pen/NMgezy) demonstrating the issue

### Environment

- `pixi.js` version: 4.7.2, 4.7.3
- Browser: Chrome 66, Firefox 59.0.2
- Device: Microsoft Surface Pro 3, DELL XPS 15 9550 (it's a touch device as well)

NB: `currentTarget`is correctly set.

**Comment by jcyuan** [comment]
touchmove?

**Comment by tobi2424** [comment]
Anyone found a fix for that?

**Comment by themoonrat** [comment]
Do `app.renderer.plugins.interaction.moveWhenInside = true;` and move events from touch will match how they are from a mouse
