### ISSUE TITLE
bug: lineTo() removes previous line

### ISSUE THREAD

**Issue by Friksel** [pixijs/pixi.js#4890]
I was just searching for some time to find out why my lines weren't showing up on screen during development of a path creation tool. I didn't expect pixi to erase my lines just by drawing them, but it does it for some reason;

When drawing a line with the Graphics object with `lineTo(x, y) ` and after that draw another line with `lineTo(x, y)` and the same x and y values, none of both lines will be drawn!!!

I understand drawing a line to to the same spot is not very useful, but during debug process this can happen, for example for quick testing, like happened to me today. 
It's confusing if, like in my case, no line is drawn at all if this happens. I would never expect drawing two lines would result in no line at all.

So this is drawing a line:
```
g.moveTo(0, 0);
g.lineTo(200, 200);
```

But this is not drawing anything:
```
g.moveTo(0, 0);
g.lineTo(200, 200);
g.lineTo(200, 200);
```

### Expected Behavior
The second lineTo() should be ignored by pixi, because it's having no length. But the first line should not be removed.

### Current Behavior
None of the lines are drawn when there are more following `lineTo`s with same values

### Possible Solution
Ignore lineTo's if they have zero length but don't change previous lines.

### Steps to Reproduce
I've just created this pen with an example: https://codepen.io/Friksel/pen/OZjpBg
The first line is removed by the second `lineTo`.
Just remove the second `lineTo` in the example and the first line is visible again

### Environment
- `pixi.js` version: 4.7.3
- Browser: Chrome, Firefox, Edge etc.
- Device: Tested on Windows 10

**Comment by ivanpopelyshev** [comment]
> I understand drawing a line to to the same spot is not very useful, but during debug process this can happen, for example for quick testing, like happened to me today.

There are many operatsions that cause `PIXI.Graphics` to lose screws. I want to port something better from one of existing vector libraries :)

Here is what i did with repeated lineTo and moveTo's one of those libs, that one is used by Google Chrome canvas2d context: https://bugs.chromium.org/p/skia/issues/detail?id=7792

**Comment by Friksel** [comment]
Thanks @ivanpopelyshev . I see you have been busy up there.
