### ISSUE TITLE
Memory leak found? And Fixed

### ISSUE THREAD

**Issue by Grahamwww** [pixijs/pixi.js#4891]
I'm not familiar with the internals of Pixi, so could well be wrong, but I think I have found a memory leak, and also have a fix for it.  

The code is in pixi.js at line 11951. It looks like its a simple case-sensitivity bug, where _webgl is used instead of _webGL

```javascript
//gw        for (var id in this._webgl) {
//gw            for (var j = 0; j < this._webgl[id].data.length; ++j) {
//gw                this._webgl[id].data[j].destroy();
//gw            }
//gw        }

// GRAHAM'S FIX
        for (var id in this._webGL) {
            for (var j = 0; j < this._webGL[id].data.length; ++j) {
                this._webGL[id].data[j].destroy();
            }
        }
// GRAHAM'S FIX END
```

**Comment by ivanpopelyshev** [comment]
Yep, vertex data is leaking.

Its here: https://github.com/pixijs/pixi.js/blob/dev/src/core/graphics/Graphics.js#L1188
Also people rarely destroy graphics. Do you use `graphics.destroy()` ? 

Also, we dont have destroy in Mesh at all: https://github.com/pixijs/pixi.js/blob/dev/src/mesh/Mesh.js

**Comment by Grahamwww** [comment]
I have a highly dynamic app where things get loaded and destroyed pretty much continuously, and could see that memory use rising and performance dropping over time. With this fix, that doesn't happen.

If this does get fixed, note also that a few lines below theres another reference to _webgl that probably also needs updating.

**Comment by ivanpopelyshev** [comment]
Ok, I'll make PR for both v4 and v5. 

I congratulate you with first github issue and for breaking the wall between your app and our lib. Now pixi is not a black box for you, but part of your own engine  that you patch according to your case.

**Comment by bigtimebuddy** [comment]
@Grahamwww:
Would you mind verifying @ivanpopelyshev's PR by using this build:
https://pixijs.download/dev-vao-leak/pixi.js

**Comment by bigtimebuddy** [comment]
Merged

**Comment by Grahamwww** [comment]
Yes, that looks good. Apologies for the delay, was away on holiday :)
