### ISSUE TITLE
Masked sprite with another sprite still raises the interactivity events on hidden areas

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4892]
Hi guys,

If I mask a sprite with another sprite generated both sprites with image textures, the masked sprite interactivity still arises in the hidden area.

This effect does not appear when you mask the sprite with a Sprite generated with a Graphics.

Maybe this is related to #3151, #2252 and #4608?

Maybe there is a setting to avoid this?
If not, why should be a Sprite generated with an image different from a sprite generated with a Graphics?

Is there any way to resolve it without using hitArea? the poligon is actually very complex and I haven't found a physics hit editor that works with pixi yet.

**Comment by ivanpopelyshev** [comment]
> If I mask a sprite with another sprite generated both sprites with image textures, the masked sprite interactivity still arises in the hidden area.

https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1044

you cant use hitArea from a mask, but if you make your custom `containsPoint` function inside the mask, interactiveManager will take it into account.

Something like this:

```js
containsPoint(p) { return this.myHitArea.contains(p.x, p.y) }
```

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev 

Thanks a lot for your support!!
I'm very surprised how the whole mask, interaction and hitArea works. I think there is some space for improvement or I haven't understand how it works.

Here are some thoughts:
- hitArea should accept a Graphics object or an array of polygons. In my case my Sprites are quite complex (like a videogame) so a simlple polygon is not working for me.
- Setting the mask from a complex Graphics works however yo have to be very exact with the poligons or the mask will give you a bot very good looking sprite.

Here is my own solution.
I do pixel perfect png masks so Im going to extend my masks from the class written below checking if the hitting point is transparent or not.

```
class AlphaMask extends PIXI.Sprite
{
    constructor(texture)
    {
        super(texture);
        
        //WARNING!! I have a global renderer to simplify the code 
        //its initiated with the pixi app renderer RENDERER = app.renderer
        this.pixels = RENDERER.extract.pixels(this);
    }
    
    containsPoint(point)
    {
        var tempPoint   = new PIXI.Point();
        this.worldTransform.applyInverse(point, tempPoint);

        const width     = this._texture.orig.width;
        const height    = this._texture.orig.height;
        const x1        = -width * this.anchor.x;
        let y1          = 0;

        if (tempPoint.x >= x1 && tempPoint.x < x1 + width)
        {
            y1 = -height * this.anchor.y;

            if (tempPoint.y >= y1 && tempPoint.y < y1 + height)
            {
                return this.point(tempPoint.x >> 0, tempPoint.y >> 0)[3] != 0;
            }
        }

        return false;
    }
    
    point(x, y)
    {
        var index = (y * this.width + x) * 4;

        return [ this.pixels[index], this.pixels[index + 1], this.pixels[index + 2], this.pixels[index + 3] ] 
    }
}
```

Please note how I also have to round the x and y with the >> operator.
One thing that we ahould also take in mind is that rendering at floating points positions it's much slower that fixed points, at least in HTML canvas. I dont know if that the case for sure, bust just only take that into account. 

Some months ago I did my Canvas lib for the project and I always used fixed points for rendering and also changed de ImageData access which is terribly slow.

**Comment by ivanpopelyshev** [comment]
You are right, I was wrong: https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L385 , it has applyInverse inside.

Why dont you just use getImageData from temporary canvas where you draw `texture.baseTexture.source` ?

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev sorry man I don't get you. I don't really know why you should wrong.

> Why dont you just use getImageData from temporary canvas where you draw texture.baseTexture.source ?

I think that one of the weakness of PIXI is that actually the code relies too much on DOM instead of wrappers that abstracts the DOM. If you check the code of EaselJS you will see that they have taken that approach. I'm avoiding relying on Canvas as much as I can. One of my main reasons to use PIXI was the ActionScript alike API plus the access to WebGL. My intention is to use PIXI in react native. as I stated in one of my issues #4868. 

I can envision that in a few months HTML5 developers can benefit of the React Native platform for all the shit (lists, navigation, etc... ) making specialized UI components based on WebGL technology, this can  be VR, games, complex UIs, etc...

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev I wanted to say that I TRUST your code and your renderer instead of checking the underliying canvas filling my code with canvas access. I know that one day PIXI will be 120% perfect 😉

**Comment by ivanpopelyshev** [comment]
`extract` is one of worst things to trust in, however its good that `pixels` doesnt use DOM. It gives you premultiplied data, and it can have problems with coordinates. 

https://github.com/pixijs/pixi.js/blob/dev/src/extract/webgl/WebGLExtract.js#L167

I still need to re-do my rejected PR: https://github.com/pixijs/pixi.js/pull/4632

I think its better if we make our own bitmap implementation, corresponding to Canvas, that way we dont have to use DOM one. My PR had something like that: https://github.com/pixijs/pixi.js/pull/4632/files#diff-e38c1de4b0f48ed1293bccc38b07e6c1R19

When I will make another approach to fork pixi and make native version, I will definitely call you to test it.

**Comment by themoonrat** [comment]
@DavidGOrtega closing this as I feel that you have the answer you needed. Feel free to re-open if you need any more help!
