### ISSUE TITLE
[Question] Drawing sprites and text directly to the renderer

### ISSUE THREAD

**Issue by nickaversano** [pixijs/pixi.js#4894]
I am trying to draw sprites and text directly to the renderer (or to a render texture) without creating multiple sprites or text objects. How can I do this?

E.g. psuedocode would look like:

```javascript
const sprite = new PIXI.Sprite(PIXI.loader.resources["images/bunny.png"].texture);
renderer.render(sprite)
renderer.render({...sprite, x: 100})
renderer.render({...sprite, x: 200})
```

Thanks!

**Comment by ivanpopelyshev** [comment]
It'll turn off batching and other optimizations.

Just `renderer.render(sprite);`. You have to specify coordinates in a sprite or in a 4th param of `render` which is a translation matrix. Read docs and do experiments. 

If you want to specify render list and everything by yourself, look at lower level - renderer plugins, sprite renderer, mesh renderer, all those things. Pixi does help newbies to understand the higher level, but for everything that is below - you have to learn, there's no alternative.

**Comment by nickaversano** [comment]
I see, just needed to set `renderer.clearBeforeRender = false` and then manually call `renderer.clear()`.

Where do I get the renderTexture from to pass to `renderer.render`? I know I can do something like:
`renderer.render(sprite, ___, false, sprite.transform, false)`

The use case is compatibility with another api that allows direct sprite and text drawing. Though I'm considering just faking these calls on my end. E.g. if someone tries `draw_sprite`, then internally I create a sprite in a cache and use that instead.

**Comment by ivanpopelyshev** [comment]
http://pixijs.download/dev/docs/PIXI.WebGLRenderer.html#render
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/WebGLRenderer.js#L289
http://pixijs.download/dev/docs/PIXI.WebGLRenderer.html#clearRenderTexture

renderTexture is the second

dontClear is the third

fourth parameter is your own camera transform, not the sprite one

> The use case is compatibility with another api that allows direct sprite and text drawing.

if it is something like

```
beginRender();
drawImage1();
drawImage2();
drawImage3();
endRender();
```

you can fill temporary stage instead, and render it all on one pass after the end.

**Comment by nickaversano** [comment]
+1 to the temporary stage idea! I'm going to run with that
