### ISSUE TITLE
Support for loading assets from SWF files

### ISSUE THREAD

**Issue by nightfury7** [pixijs/pixi.js#4903]
Are you guys working on support for loading assets from SWF files? If you are not, I can contribute a very small and optimized library that reads SWF files and renders them using the standard moveTo/lineTo/curveTo API and supports literally all of the SWF features flawlessly except animation. All kinds of static vector assets can be loaded. Do you want me to work on contributing this to the pixi.js project?

**Comment by ivanpopelyshev** [comment]
Right now every contribution towards SWF counts, even if its your own lib. 

I have a project that does it but its too heavy and not connected to pixi yet: https://github.com/pixijs/pixi-swf 

Pixi lacks necessary Graphics methods and I'm working on new Graphics for PixiJS :)

**Comment by nightfury7** [comment]
Thanks for the response. 

> Pixi lacks necessary Graphics methods and I'm working on new Graphics for PixiJS :)
Can I render vector shapes with the standard moveTo/lineTo/curveTo API?
What about solid/gradient fills and line styles? Those supported as well?

**Comment by ivanpopelyshev** [comment]
Yeah, 

You'll get https://github.com/pixijs/pixi.js/issues/4890 and some other things, like, pixi cant detect holes automatically.

**Comment by ivanpopelyshev** [comment]
That's why we need better Graphics. This is what I'm focusing on right now.

**Comment by ivanpopelyshev** [comment]
Another related PR: https://github.com/pixijs/pixi.js/pull/4658

**Comment by nightfury7** [comment]
I assume we'd want to render the graphics to a bitmap and then use it as a regular bitmap sprite from then on? Or would we be using vector rendering on CPU/GPU in real time every frame? rasterizing can be a bitch on the CPU...

**Comment by ivanpopelyshev** [comment]
Well, we have to do it :)

Yep, pow2 levels of detalization with vertex or bitmap cache. Need different settings for that thing.

**Comment by MindfulMe** [comment]
I want to take care of it as well

**Comment by ivanpopelyshev** [comment]
Join https://t.me/html5dev .

**Comment by MindfulMe** [comment]
thx

**Comment by nightfury7** [comment]
@ivanpopelyshev I uploaded my optimized [SWF parser ](https://github.com/nightfury7/as3swfgfx)& renderer in the original ActionScript 3 format. I will be porting this to JS soon.

**Comment by themoonrat** [comment]
@nightfury7 Closing this issue, but sounds like a useful thing if a plugin came out of this for others to use!

**Comment by nightfury7** [comment]
@themoonrat Can we re-open this issue? I started working on SWF support for Pixi JS again, my WIP library is [here](https://github.com/nightfury7/swfrender.js), and I could use the community help with this.

**Comment by englercj** [comment]
This should remain closed because it doesn't really belong in the core library. Like @themoonrat mentioned, this sounds like a great plugin.

**Comment by bigtimebuddy** [comment]
If you aren’t already, you should join the PixiJS Slack. It’s a good place to chat about ideas like this. Send me your email address and I can add you: matt@mattkarl.com
