### ISSUE TITLE
font not correct size using resolution 2

### ISSUE THREAD

**Issue by nickaversano** [pixijs/pixi.js#4904]
### Expected Behavior

`Text` isn't taking resolution into account properly. For example, when rendering a `Text` object within a game with `resolution` set to 2 within a container that has been scaled up to 4, the text pixels are width 2. The `Sprite`'s pixels are rendering correctly at 4px per pixel, but the text's pixel's are only 2px per pixel.

### Current Behavior
![screen shot 2018-05-11 at 9 14 41 pm](https://user-images.githubusercontent.com/5448363/39952262-fea9e810-5560-11e8-994b-d21738f7de03.png)

### Possible Solution
Multiply Text scale by resolution.

### Steps to Reproduce

```javascript
var app = new PIXI.Application(800, 480, { resolution: 2, autoResize: true, antialias: false });
PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
document.body.appendChild(app.view);

app.stage.scale.set(4);

var sprite = PIXI.Sprite.fromImage('./player.png');

app.stage.addChild(sprite);

var text = new PIXI.Text("awesome!", {  fill: 'white',  fontSize: 12 });

app.stage.addChild(text);
```

### Environment

- `pixi.js` version: 4.7.3
- Browser: 66.0.3359.139
- Device: Mac 10.12.6 Desktop

**Comment by ivanpopelyshev** [comment]
Why do you scale the stage? `PIXI.Text` does not take into account stage scale.

**Comment by bigtimebuddy** [comment]
I disagree that `fontSize` should respond to the global scale. There are lot of uses where you'd want those to be independent. You should set the scale of the Text object and `fontSize` or use a BitmapText object instead.

https://jsfiddle.net/0f4r1Lss/

**Comment by haunguyen1996** [comment]
https://jsfiddle.net/0f4r1Lss/

Vào 0:16 CN, 13 thg 5 2018 Matt Karl <notifications@github.com> đã viết:

**Comment by themoonrat** [comment]
Closing as I think you have the answers above, @nickaversano :)
