### ISSUE TITLE
Could you put `pixi.min.js` on cdn.jsdelivr.net ? 

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4905]
In Current version , the  `pixi.min.js` in on pixijs.download , I don't why it's hard to be visited in China.

Even I use proxy to visit it , it's very slow.

Could you put `pixi.min.js` on cdn.jsdelivr.net (Or other cdn that could be visited in China) ?

Thanks

**Comment by bigtimebuddy** [comment]
The current version (v4.7.3) does exist on jsdelivr:
https://cdn.jsdelivr.net/npm/pixi.js@4.7.3/dist/pixi.min.js

Could you clarify what you mean by "current"? Do you mean the "dev" branch?

**Comment by finscn** [comment]
@bigtimebuddy  , but the online demo  http://pixijs.io/pixi-filters/tools/demo/ still use  pixi.download .
'current' means  'current online demo

**Comment by jcyuan** [comment]
put one on your own server.

**Comment by englercj** [comment]
Currently CloudFront is the CDN we use for all our pixi apps (like the examples). Unfortunately CloudFront doesn't work well in China.

> Amazon CloudFront edge locations are currently not available inside of China.
Source: https://www.amazonaws.cn/en/content-delivery/

**Comment by themoonrat** [comment]
@bigtimebuddy Is this something that can be done?

**Comment by jimaek** [comment]
jsDelivr has an ICP license and works in China just fine https://www.jsdelivr.com/network#china
Latest min version https://cdn.jsdelivr.net/npm/pixi.js@4.8.1/dist/pixi.min.js
