### ISSUE TITLE
PIXI.BLEND_MODES.ADD Pixi 3 vs Pixi 4 difference.

### ISSUE THREAD

**Issue by klaun76** [pixijs/pixi.js#4910]
Hi 

We're moving from pixi3 to pixi4. (almost 60 games in portfolio). After basic migration i've found out that when alpha of DisplayObject is lower than 1, and blend is set to PIXI.BLEND_MODES.ADD result is pretty much different between pixi3 and pixi4. I've prepared jsfiddles and test page for better comparison. We've probably missed train a long time ago, but it's still worth asking. 

We use particles heavily and a lot of them have also PIXI.BLEND_MODES.ADD and we're experiencing same problems there. I've developed an upgrade for [particles editor](http://mrtn.sk/particles-editor/) with pixi4 where our graphic artists started complaining.

thanks
.mrtn
### Expected Behavior
Same visual output.
### Current Behavior
Different visual output. pixi4 version is much brighter.
### Possible Solution
No idea, except changing resources and approach.
### Steps to Reproduce
Check: http://mrtn.sk/jsfiddle/test.html
Or direct links to jsfiddle:
pixi 3: http://jsfiddle.net/klaun76/gh8zgs6d/
pixi 4: http://jsfiddle.net/klaun76/kcf6dcsr/
### Environment
Probably all browsers and mobile devices. I've tested chrome, safari, mozzila, Iphone 6.

**Comment by ivanpopelyshev** [comment]
pixi4 is correct. pixi-3 applied alpha two times instead of one.

Possible solution: where you have `alpha=0.5` put `alpha=0.25` instead. Swap `0.6` to `0.36`

There's also small difference in blendMode itself, which is not applicable for your case because you have solid background, but I post it here nevertheless. You dont have to use it.

```js
renderer.state.blendModes[20] = [gl.ONE,       gl.DST_ALPHA];
sprite.blendMode = 20;
```

**Comment by klaun76** [comment]
thanks for info. well do as you proposed
.mrtn

**Comment by shepelevstas** [comment]
where do I get `gl` object?

**Comment by klaun76** [comment]
**gl** is for renderer that you create within your application. (check for fiddle above)
default solution in pixi 3: var **gl** = new PIXI.WebGLRenderer(size.x, size.y); 
default solution in pixi 4:
const app = new PIXI.Application(size.x, size.y);
const **gl** = app.renderer.gl
