### ISSUE TITLE
[QUESTION] Changing PIXI.Text resolution - without changing the renderer resolution

### ISSUE THREAD

**Issue by joeredfearn** [pixijs/pixi.js#4915]
Hi there!

I have question regarding PIXI.Text and its resolution. There is some PIXI.Text in my project that is a little blurry - setting the renderer resolution > 1 fixes this issue, but this is not a practical solution for just improving text quality alone.

I would like some clarity on the PIXI.Text resolution public member and how (if possible) to change the resolution of the text alone, before it is drawn to its canvas.

Thanks

**Comment by ivanpopelyshev** [comment]
Override this method: https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L360

**Comment by joeredfearn** [comment]
Thanks for the answer - the results weren't actually how I expected them. The quality looks pretty much the same, I guess that is because if the final renderer is still low pixel density then the text will still come out blurry.

Are there any other possible solutions? I really want to refrain from increasing the pixel density for the renderer as a whole.

**Comment by Mwni** [comment]
This is related: https://github.com/pixijs/pixi.js/issues/4034

As a temporary fix you could replace `if (this.resolution !== renderer.resolution)` with `if (!this.resolution)` to allow for custom resolutions for each textfield, but still have textfields use the renderer's resolution if it's not explicitly set.

Minified version (4.7.3) with only these changes:
[pixi.min.txt](https://github.com/pixijs/pixi.js/files/2031397/pixi.min.txt)

**Comment by themoonrat** [comment]
The workaround above is good.

This is something that should be properly addressed for v5. A flag to enforce text resolution to match renderer resolution perhaps. Or an initial resolution is grabbed from the renderer, but can be overridden by the user.
