### ISSUE TITLE
[next] Can't build docs?

### ISSUE THREAD

**Issue by jacobcoughenour** [pixijs/pixi.js#4918]
Doing `npm run docs` just says `There are no input files to process.` 

I'm stuck on some spotty hotel wifi right now, so some offline docs could be pretty useful.

**Comment by bigtimebuddy** [comment]
Next more info here. What version of Node and NPM are you running and on what platform?

**Comment by jacobcoughenour** [comment]
works perfectly on my desktop with node v8.4.0 and npm v5.3.0 but not on my laptop with node v8.9.4 and npm v5.6.0.  And both running windows 10 with the latest update.

**Comment by jacobcoughenour** [comment]
I used node version manager to install node v8.4.0 and npm v5.3.0 on my laptop, to match my desktop.  Did `npm install` then `npm run docs` and it's still saying `There are no input files to process.`

**Comment by theGolyo** [comment]
@jacobcoughenour does your path maybe contain an underscore?

**Comment by jacobcoughenour** [comment]
@theGolyo The path does not contain an underscore.

```npm run docs``` works now.
