### ISSUE TITLE
Rectangle linked ?

### ISSUE THREAD

**Issue by thib3113** [pixijs/pixi.js#4919]
Hello, firstly, I'm sorry because I'm new with pixi.js, so I'm not sure I done the things in the proper way .

I'm not sure, but I think I've found a bug with Rectangle frame when using the same spritesheet (for two sprite)

### Expected Behavior
two "players" (sprite), using the same spriteSheet, but with different frames (it's an animation, and I want the two player don't do the same animation in the same time)

### Current Behavior
the two players use the same frame Rectangle

### Steps to Reproduce
I've created a little jsfiddle : https://jsfiddle.net/thib3113/159zvapo/

Ok, It's show nothing, but in the console, you can see, the first time (first debugger;)  aSprite._texture._frame.x = 0,
and the second time
aSprite._texture._frame.x = 0,
 
in code : 
```javascript
  let aTexture = PIXI.utils.TextureCache[SpriteKen];
  aTexture.frame = new PIXI.Rectangle(0,0,43,87);
  aTexture.height = 87;
  aTexture.width = 2289;
  let aSprite = new PIXI.Sprite(aTexture);
  aSprite.position.x = 10;
  aSprite.width = 43;
  aSprite.height = 87;
  aSprite.position.y = 10;
  //here aSprite._texture.orig.x = 0
  debugger;
  stage.addChild(aSprite);

  let bTexture = PIXI.utils.TextureCache[SpriteKen];
  bTexture.frame = new PIXI.Rectangle(500,0,43,87);
  bTexture.height = 87;
  bTexture.width = 2289;
  let bSprite = new PIXI.Sprite(bTexture);
  bSprite.position.x = 100;
  bSprite.width = 43;
  bSprite.height = 87;
  bSprite.position.y = 0;
  //here aSprite._texture.orig.x = 500
  debugger;
  stage.addChild(bSprite);
```

So I think, when I create bTexture, and adding the rectangle, the rectangle of the first sprite is updated .

### Environment

- `pixi.js` version: 4.7.3 / 4.0.0 (on jsfiddle)
- Browser: Chrome 66
- Device: Desktop

**Comment by ivanpopelyshev** [comment]
ok, setting

```
aTexture.height = 87;
aTexture.width = 2289;
```

is not supported.

**Comment by ivanpopelyshev** [comment]
here is your problem, i believe:
```js
 let bTexture = PIXI.utils.TextureCache[SpriteKen];
```

you should create new instance:
```js
bTexture = new PIXI.Texture(bTexture, bTexture.frame.clone());
bTexture.frame.x = ...
bTexture.frame.y = ...
bTexture._updateUvs(); //we just updated frame fields
```

**Comment by thib3113** [comment]
@ivanpopelyshev : for height and width, it's because I copy paste from my code, and try to do this without loader, and trying to force width and height (before the image load), and I forgot to remove it .

OMG, yes .... the texture is always the same object ..... so I just update the texture without recreating one .... So .... I'm sorry . 

Is the _updateUvs() needed ? (because it's start by an underscore, I think it's maybe a "private" function ?)

Thanks you

**Comment by ivanpopelyshev** [comment]
`_updateUvs()` needed only if you change `frame.x` manually. 

`frame` itself is a property, when you set it, all UV coords are updated automatically.

**Comment by thib3113** [comment]
ok, so needed in your example, but not in mine (because I set frame with a rectangle directly);
