### ISSUE TITLE
Pass hovered item to function on.('mouseout', 

### ISSUE THREAD

**Issue by Jones-S** [pixijs/pixi.js#4920]
Hi everyone
I am currently using Pixi.JS in a vue app and I want to register interaction events.
So far so good, I managed to get pointerdown and pointerup and mouseover, but somehow I am stuck with `mouseout`.

Let's look at this example
```
this.pixiSprite.on('mouseover', this.itemHover)
this.pixiSprite.on('mouseout', this.cancelItemHover)
```

Within the function `itemHover ()` I can address the hovered element by:
```
itemHover (event) {
  this.log('event.target hover: ', event.target)
}
```
Which will return a Pixi Sprite (that's correct, because I registered the eventlistener on every of my sprites.

If I do the same with `cancelItemHover`
It will tell me that `event.target = null`

Although I am doint the exact same thing:

```
cancelItemHover (event) {
  this.log('event: ', event)
  this.log('event.target: ', event.target)
},
```

I do get the event but the `event.target`, the `event.currentTarget` and `event.data.target` are all `null`.

I found a solution:
```
this.pixiSprite.mouseout = function () {
  console.log('this: ', this)
}
```
But this is not applicable because I need to access the vue app's `this` context.
So how could I bind/pass on the hovered element to the `cantelItemHover ()` function?

I don't know if this is a wanted behaviour or a bug, anyway I would be very glad to get some information.
(I just want to scale a pixi sprite on hover and scale it back to original size on mouseout)

Cheers

- `pixi.js` version: _e.g. 4.7.3_
- Browser: _e.g. Firefox Developer Edition 61.0.b2 / Chrome 66.0.3359.139_
- Device: _e.g. Desktop_

**Comment by djmisterjon** [comment]
what about ?
`this.pixiSprite.on('mouseover', this.itemHover.bind(this.pixiSprite))`

**Comment by Jones-S** [comment]
I tried this `this.pixiSprite.on('mouseover', this.itemHover.bind(this.pixiSprite))`
but I either don't know how the bind works, or it just does not work

When I do the following:
```
cancelItemHover (event, test) {
  this.log('event: ', event) // event from before with target = null
  this.log('event.data: ', event.data) // event.data from before but data.target also null
  this.log('test: ', test) // undefined
  this.log('this: ', this) // this = vue app component
}
```

I would have expected that this would now be the pixiSprite, but this would also cause problems because I want to have direct access to the this context of the vue app component...

**Comment by bigtimebuddy** [comment]
Try this for bind:

this.pixiSprite.on('mouseover', this.itemHover.bind(this, this.pixiSprite))

itemHover(sprite, event){}

Additional parameters you pass to bind are added as additional preceding arguments to your callback.

**Comment by Jones-S** [comment]
This works. Thanks @bigtimebuddy 
I just wonder, why pixi has a target of `null` in the first place.
Do you know if this is intended behaviour or a bug? If the latter I might report it...?

**Comment by bigtimebuddy** [comment]
Try this:
https://jsfiddle.net/bigtimebuddy/a75pmzg8/4/

**Comment by Jones-S** [comment]
Hm I see that in your case target seems to be defined in all cases. In my case though the mouseout was null. 
I had a stage, inside I had a container, inside this I had a lot of sprites, which all contain 2 graphics.
I registered the mouseout on the sprite. I don't know what could cause this...

**Comment by Jones-S** [comment]
Hm I tried to get it to work, but somehow my pattern is not showing up:
https://jsfiddle.net/dgnjb7pe/3/

If I inspect the element I can see a little preview on the hover which actually contains my pattern, but on screen I don't see it. Therefore I don't know what the output would show. Do you maybe have an idea what could be the reason for the missing image?

**Comment by djmisterjon** [comment]
its true , will work only if you use asynchronous timeout !


`setTimeout(function(){ console.log('target mouseout: ', event.target); }, 1000);`

**Comment by Jones-S** [comment]
Oh interesting...
Just out of interest: What's the reason for that?

**Comment by djmisterjon** [comment]
i don't know, am only work with **document Listener** for my PIXI projects.
https://www.w3schools.com/jsref/met_document_addeventlistener.asp
I **never use the interaction manager.**
Maybe a pixi guys will give you more information about this.
but the interaction event manager does not seem to work well! 
I find that strange too.

you have fellow all guide here ?
https://pixijs.io/examples/#/demos/interactivity.js

**Comment by andrewstart** [comment]
To reduce object creation/garbage collection, we use a single InteractionEvent for all interaction events. As a result, the interaction event object is only valid during the event callback itself, and if you want to retain the data for later use you'll need to make a copy, including a copy of the event's `data` property that is also pooled.

**Comment by Jones-S** [comment]
Ok. I don't fully understand, but you gave me an idea :D. (Why would the oject still be valid on mouseover and not on mouseout?
Anyway, I solved it with the .bind() answer from above. Thx again @bigtimebuddy
