### ISSUE TITLE
PIXI is not compatible with Angular v6

### ISSUE THREAD

**Issue by samalexander** [pixijs/pixi.js#4921]
An Angular v6 app that imports PIXI fails to compile. I think this is likely related to this [issue](https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814):

As of version 6, Angular-Cli no longer: 
- provides a shim for global and process.
- supplies an empty module when fs, crypto, tls and net are requested.

Is there a suitable workaround for this issue or does the PIXI code need to be updated to make it compatible with Angular v6?

### Expected Behavior
An Angular v6 app that imports PIXI should compile.

### Current Behavior
Compilation fails with the following error:
```
ERROR in ./node_modules/pixi.js/lib/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/core/renderers/webgl/filters/spriteMask'
ERROR in ./node_modules/pixi.js/lib/core/sprites/webgl/generateMultiTextureShader.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/core/sprites/webgl'
ERROR in ./node_modules/pixi.js/lib/extras/webgl/TilingSpriteRenderer.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/extras/webgl'
ERROR in ./node_modules/pixi.js/lib/filters/alpha/AlphaFilter.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/filters/alpha'
ERROR in ./node_modules/pixi.js/lib/filters/colormatrix/ColorMatrixFilter.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/filters/colormatrix'
ERROR in ./node_modules/pixi.js/lib/filters/displacement/DisplacementFilter.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/filters/displacement'
ERROR in ./node_modules/pixi.js/lib/filters/fxaa/FXAAFilter.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/filters/fxaa'
ERROR in ./node_modules/pixi.js/lib/filters/noise/NoiseFilter.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/filters/noise'
ERROR in ./node_modules/pixi.js/lib/loaders/bitmapFontParser.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/loaders'
ERROR in ./node_modules/pixi.js/lib/mesh/webgl/MeshRenderer.js
Module not found: Error: Can't resolve 'path' in '/Users/samalexander/Developer/test-pixi/node_modules/pixi.js/lib/mesh/webgl'
```

### Steps to Reproduce
I have created a basic Angular project [here](https://github.com/samalexander/test-pixi) that demonstrates this issue. To run the project: clone the repo, install dependencies with `yarn install` and run `yarn start` to build and serve the app. You will see the error message above is displayed when build fails.

**Comment by bigtimebuddy** [comment]
Could you check to see if this also applies to pixi.js@5.0.0-alpha.2?

**Comment by samalexander** [comment]
@bigtimebuddy looks like it very nearly works! I am getting the following error:
```
ERROR in node_modules/pixi.js/pixi.js.d.ts(636,36): error TS2694: Namespace 'PIXI' has no exported member 'CanvasRenderer'.
node_modules/pixi.js/pixi.js.d.ts(2022,35): error TS2304: Cannot find name 'CanvasRenderer'.
```
But seems to just be an issue with the Typescript definitions, as if I manually change the CanvasRenderer types to anys, it builds successfully.

**Comment by samalexander** [comment]
I also noticed that Pixi.js v5 now has its own Typescript definitions :+1:

**Comment by samalexander** [comment]
I'm not specifying the canvas renderer anywhere. It is an issue with the published typescript definition file and it looks like there is a fix [here](https://github.com/pixijs/pixi.js/commit/d0a1e1e6a28b9beaa75bb02c7f76dad40cca4256#diff-473392bc89ed860313152089275e1637), just hasn't been released yet.

**Comment by bigtimebuddy** [comment]
Oh yup, you're right! Well glad to know if solved the primary issue. Another idea, if you didn't want to move to v5 yet is to import with Angular using the built file: `import * as PIXI from 'pixi.js/dist/pixi.js';` this will not try to use any Node-specific APIs.

**Comment by samalexander** [comment]
We are happy to move to v5. When do you expect to cut a new release with the typings fix? Thanks very much for all your help!

**Comment by bigtimebuddy** [comment]
That's a good question! Probably in the next two weeks.

**Comment by bigtimebuddy** [comment]
Going to close this issue. If you feel like it's not resolved, feel free to reopen.

**Comment by sanasus** [comment]
I change d.ts file to 
declare module "pixi.js/dist/pixi.js" {
    export = PIXI;
}
and import to project import * as PIXI from "pixi.js/dist/pixi.js";
type checking works!
pixi v4.8.1 d.ts 4.8.0

**Comment by marcj** [comment]
Can you please re-open that? I was able to use PIXI.JS 4.7.1 for months using Angular 6. Now after re-installing all my dependencies, I'm getting the errors from above as well. I'm still investigating what happened here, as I'm using a package-lock.json and this is definitely a weird behavior.

```
ERROR in ./node_modules/pixi.js/lib/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/core/renderers/webgl/filters/spriteMask'
ERROR in ./node_modules/pixi.js/lib/core/sprites/webgl/generateMultiTextureShader.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/core/sprites/webgl'
ERROR in ./node_modules/pixi.js/lib/extras/webgl/TilingSpriteRenderer.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/extras/webgl'
ERROR in ./node_modules/pixi.js/lib/filters/alpha/AlphaFilter.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/filters/alpha'
ERROR in ./node_modules/pixi.js/lib/filters/colormatrix/ColorMatrixFilter.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/filters/colormatrix'
ERROR in ./node_modules/pixi.js/lib/filters/displacement/DisplacementFilter.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/filters/displacement'
ERROR in ./node_modules/pixi.js/lib/filters/fxaa/FXAAFilter.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/filters/fxaa'
ERROR in ./node_modules/pixi.js/lib/filters/noise/NoiseFilter.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/filters/noise'
ERROR in ./node_modules/pixi.js/lib/loaders/bitmapFontParser.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/loaders'
ERROR in ./node_modules/pixi.js/lib/mesh/webgl/MeshRenderer.js
Module not found: Error: Can't resolve 'path' in '/app/node_modules/pixi.js/lib/mesh/webgl'
```

The question is, why does code meant for the browser use `path` and [`fs` modules](https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js#L3), which comes from NodeJS? I mean that SpriteMaskFilter.js which should run in the browser uses fs.readFileSync? That can't be right.

What's going on there, do you filter it out in a build process? If we need to use the `dist/pixi.js` file, why don't you add it into `package.json:main` property?

I tried to add the `dist/pixi.js` into the tsconfig.json, like so:

```
  "compilerOptions": {
    "paths": {
      "pixi.js": [
        "../node_modules/pixi.js/dist/pixi.js"
      ],
   }
```

But then I get tons of other errors. Like

```
ERROR in src/app/Editor/Components/EditorRenderComponent.ts(334,52): error TS2339: Property 'getBounds' does not exist on type 'LayerContainer
```

although I correctly use it and have used it for months, since it was compiling perfectly fine.

What is the difference in pixi.js and the raw source code except that is now in one big file? 
Do you guys have any idea what is going on here?


> If you want Canvas use pixi.js-legacy module instead. We removed canvas from the default module.

Can you please elaborate on that? PIXI.JS uses now always OpenGL to render? Since when?

**Comment by marcj** [comment]
I took a look in the code in `node_modules/pixi.js/lib/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js`, where you can see that the build process gets rid of the `fs.readFilesync` call and replace it with something like

```
var _this = _possibleConstructorReturn(this, _Filter.call(this, 'attribute vec2 aVertexPosition;\nattribute vec2 aTextureCoord;\n\nuniform mat3 projectionMatrix;\nuniform mat3 otherMatrix;\n\nvarying vec2 vMaskCoord;\nvarying vec2 vTextureCoord;\n\nvoid main(void)\n{\n    gl_Position = vec4((projectionMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);\n\n    vTextureCoord = aTextureCoord;\n    vMaskCoord = ( otherMatrix * vec3( aTextureCoord, 1.0)  ).xy;\n}\n', 'varying vec2 vMaskCoord;\nvarying vec2 vTextureCoord;\n\nuniform sampler2D uSampler;\nuniform sampler2D mask;\nuniform float alpha;\nuniform vec4 maskClamp;\n\nvoid main(void)\n{\n    float clip = step(3.5,\n        step(maskClamp.x, vMaskCoord.x) +\n        step(maskClamp.y, vMaskCoord.y) +\n        step(vMaskCoord.x, maskClamp.z) +\n        step(vMaskCoord.y, maskClamp.w));\n\n    vec4 original = texture2D(uSampler, vTextureCoord);\n    vec4 masky = texture2D(mask, vMaskCoord);\n\n    original *= (masky.r * masky.a * alpha * clip);\n\n    gl_FragColor = original;\n}\n'));
```

However, the line `var _path = require('path');` is still at the head of the file, although `_path` is never used in the code. This is actually the error here I guess.

**Comment by uahic** [comment]
any progress? i got it working for me with the workaround mentioned above, but when using Angular's ahead-of-time compilation it wont compile

**Comment by TomMettam** [comment]
If it helps anyone, i've made a fork with a couple of adjustments to work well with typescript and angular.

`npm install --save https://github.com/CasperTech/pixi.js.git`

**Comment by TomMettam** [comment]
@wkamir - all I did was update package.json to point to the compiled version of pixi rather than the source,  then copied the typescript definitions from @types/pixi.js, and referenced them in the package.json too. 

I didn't create a pull request since it seemed that this was a design decision.

**Comment by wkamir** [comment]
@TomMettam thanks for the quick reply! ... I have tried to do this myself... but on my local pixi.js installation (in node_modules) - should this not also have had the same effect?

Why did you also include the d.ts file? Is this necessary for it to work?

Sorry if those are basic questions but I am a little overwhelmed with how exactly typescript modules + different JS module formats + TS toolset (@types) interact.... when it works it works, but when not it is always such a hassle...

**Comment by kellyprankin** [comment]
> 
> 
> I change d.ts file to
> declare module "pixi.js/dist/pixi.js" {
> export = PIXI;
> }
> and import to project import * as PIXI from "pixi.js/dist/pixi.js";
> type checking works!
> pixi v4.8.1 d.ts 4.8.0

Thank you for this. Just wasted a lot of time trying to understand what the heck was going on.

**Comment by krojew** [comment]
Just encountered this problem with latest pixi and angular 7.1. The issue should be reopened.

**Comment by generalcss** [comment]
We are currently on Angular 7.1 and have reverted from the 5 alpha back to PIXI 4.8.5.

I have fixed this by adding the pixi dist file to the angular.json scripts property.
`
// excerpt of angular.json
"architect": {
        "build": {
            "scripts": [
              "src/assets/js/jwplayer/jwplayer.js",
              "src/assets/js/jwplayer-key.js",
              "node_modules/quill/dist/quill.js",
              "node_modules/webfontloader/webfontloader.js",
              "node_modules/pixi.js/dist/pixi.min.js"
            ]
          },
}
`

And importing the typing as followed.
`declare const PIXI: typeof import('pixi.js');`

**Comment by grantyi** [comment]
Has anyone had any success using one of the extra filters in Angular? I am able to use all of core filters but when trying to use `filter-glow` for example, I get the same error message as above.
