### ISSUE TITLE
Could not find a declaration file for module '@pixi/loaders' - v5

### ISSUE THREAD

**Issue by ellipticaldoor** [pixijs/pixi.js#4923]
### Expected Behavior
You install typescript types and you don't get an error.

### Current Behavior
If you use typescript with pixi new modules you get the following error
```
Could not find a declaration file for module '@pixi/loaders'. '/Users/miguel/src/later/node_modules/@pixi/loaders/lib/loaders.js' implicitly has an 'any' type.
  Try `npm install @types/pixi__loaders` if it exists or add a new declaration (.d.ts) file containing `declare module 'pixi__loaders';`
```

### Possible Solution

I tried to install @types/pixi.js but it doesn't detects it. Also the error tells me to npm install @types/pixi__loaders but pixi__loaders doesn't exists.

- `pixi.js` version: 5.0.0-alpha.2

**Comment by bigtimebuddy** [comment]
Currently, we do not have typings for packages like `@pixi/loaders`, only typings are available for **pixi.js** and **pixi.js-legacy** bundles. We need a better way to generate these with our build process. Somewhat non-trivial. If anyone has an elegant solution or wants to create typings for 30 some modules, please help.

**Comment by ellipticaldoor** [comment]
Maybe instead of having a different package for each module it would be better to create a babel plugin that when you build your project just detects which ones are you using to include them.

A good example of this concept is this plugin https://github.com/megawac/babel-plugin-ramda

I think it would be a lot easier than maintaining all those packages.

**Comment by bigtimebuddy** [comment]
We are using rollup to generate ES builds which can be used by Webpack and other for tree shaking build processes. We’d rather have dependencies be declarative than using a magic build process to drop code. It handles more use cases for people who aren’t using Babel. I think the package org is not that much to maintain/test/release unless we have to be maintaining hand rolled typings.

**Comment by ellipticaldoor** [comment]
Okay, I just thought about this because I think it would solve this particular problem with types.

If the only that can be done is this manual process for every package I can help, I just need an example. I'm quite new at typescript and Im not familiar with the webpack bundling process.

**Comment by bigtimebuddy** [comment]
Thanks that’d be awesome. The best example right now would be pixi-filters which is similar to v5. https://github.com/pixijs/pixi-filters. If you look at any one of the filters they have their own typings.the difference is that v5 packages don’t have a namespace or global export. So there would just be a module definition.

**Comment by ellipticaldoor** [comment]
I can take a look at the weekend, though at first sight I don't have very clear what I have to do. Just one module as an example would be nice to start 🙂
