### ISSUE TITLE
fromBuffer not working in all case on @next branch

### ISSUE THREAD

**Issue by hellraisercenobit** [pixijs/pixi.js#4925]
### Expected Behavior
Texture.fromBuffer should return a texture with any typedarray

### Current Behavior
In Some cases, nothing is render and some warnings are thrown
`BufferResource.js:67 WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request
upload @ BufferResource.js:67
updateTexture @ TextureSystem.js:187
bind @ TextureSystem.js:118
flush @ SpriteRenderer.js:382
render @ Renderer.js:343
render @ Application.js:199
emit @ TickerListener.js:89
update @ Ticker.js:412
Ticker._tick @ Ticker.js:139
requestAnimationFrame (async)
Ticker._tick @ Ticker.js:143
requestAnimationFrame (async)
_requestIfNeeded @ Ticker.js:162
start @ Ticker.js:319
start @ Application.js:215
Application @ Application.js:116
(anonymous) @ index.html:20
255[.Offscreen-For-WebGL-000001C1794E3740]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
index.html:1 WebGL: too many errors, no more errors will be reported to the console for this context`

- Tested with a simple getImageData with an other image and it's working like a charm.
- Tested with a direct ArrayBuffer from node and casted to Uint8Array results to same issue.

### Possible Solution
I suppose it could be a transform issue but maybe it's coming from my code.

### Steps to Reproduce
https://jsfiddle.net/qvtf5cLf/

### Environment

- `pixi.js` version: _e.g. 5
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by ivanpopelyshev** [comment]
272 x 92  = 25296 , multiply it by 4 to get number of bytes for that buffer in RGBA32: 101184
Your buffer has size 5969.

Are you trying to parse compressed png?

**Comment by hellraisercenobit** [comment]
I have tried with jpeg and png.
Base img comes from https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png

**Comment by hellraisercenobit** [comment]
An other example with direct arraybuffer
https://jsfiddle.net/jzhu0a72/

**Comment by ivanpopelyshev** [comment]
`fromBuffer`  accepts only uncompressed input.

**Comment by ivanpopelyshev** [comment]
You have to set image src to dataUrl to decode it, and use decoder built in browser, or use JS-based decoder which can be slow.

**Comment by hellraisercenobit** [comment]
haaaaaaaaaa ok that's why it didn't work with different sources!
And working well with old fashion fromImage ^^.
Thx a lot @ivanpopelyshev !

ps: 
I hope you're not sick anymore

**Comment by hellraisercenobit** [comment]
In your opinion what's the most effective way:
Bigger uncompressed image and direct fromBuffer
