### ISSUE TITLE
Sprite listens to texture update event after being detroyed

### ISSUE THREAD

**Issue by namark** [pixijs/pixi.js#4930]
Here is where the listener in question is registered https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L591
I'm guessing it should be removed in the destroy function, otherwise if the sprite is destroyed before the texture is loaded, it will throw an exception when the event triggers.
Probably not a common use case, lazy loading sprites, but should be an easy fix.

**Comment by ivanpopelyshev** [comment]
Either  we have in  `onTextureUpdate`, either in `destroy`

**Comment by namark** [comment]
I guess an `if(destroyed)` check in `_onTextureUpdate` will work as well, but if you mean removing the listener there, then I think that's not necessary since it's registered with `.once`.

**Comment by bigtimebuddy** [comment]
I'm more in favor of explicitly removing a listener that is created by a class instead of implicitly ignoring the callback.  PR welcoming to add this to `destroy`. Definitely an edge-case, but good find regardless @namark.

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy we have to check that texture was still not loaded, and then ask to remove listener.

**Comment by bigtimebuddy** [comment]
Yup that makes sense
