### ISSUE TITLE
[QUESTION]  How I can emit event between two different PIXI.Containers?

### ISSUE THREAD

**Issue by MykhailoMaliarchuk** [pixijs/pixi.js#4931]
Hi there!
I have two PIXI.Containers . The first is over the second. Also i have two events "pointerdown" and "pointerover".  I want after "pointerdown" to change color of the first PIXI.Container, and  after "pointerover" change color of the second.
Is it posible?
I tried use interactive  = false  for the first PIXI.Container. But in this case  we can not  lisen to events for first.

**Comment by bigtimebuddy** [comment]
You could try wrapping both Container instances with another Container and listen for `pointerdown` and `pointerover` on the parent Container.

**Comment by MykhailoMaliarchuk** [comment]
There are a lot of pixi.Containers. And can drag one Container above another. I want use this case if some container was placed over another.

**Comment by jcyuan** [comment]
@MykhailoMaliarchuk 

in your pointerdown event handler, set interactive = false for the first container, and then:
    function pointerDownHandler(e) {
        var theSecondContainer = pixiApp.renderer.plugins.interaction.hitTest(e.data.global, e.target.parent);    //find the second container by the global position where your mouse down. notice: here it assumes that the 2 containers has the same parent so use e.target.parent.
        if(theSecondContainer) {
            //change color for it    
        }
    }

hope it helps.

**Comment by themoonrat** [comment]
Closing @MykhailoMaliarchuk as it seems your question has been answered. If not, feel free to re-open :)
