### ISSUE TITLE
[QUESTION] Using blendmode with two renderers

### ISSUE THREAD

**Issue by Mikael294** [pixijs/pixi.js#4936]
Hello,
I currently have an issue with my project.

## The context

My 2D game is splitted into two renderers. The first one is the background renderer, it's only drawn once or redrawn sometimes. However, the second one is the "live" renderer - it's rendered at 60 FPS or more (`requestAnimationFrame`)

I'm using two canvases because the background canvas contains big sprites that doesn't need to be drawn each time and will slow down performance if they are.

## The problem

Now I've encountered a problem: I need to use `BlendMode ` on a sprite in my live renderer, and I need that the blendmode 'applies' with the background canvas.

## Example

**Here's what's expected :**

![img1](https://i.imgur.com/XiEv3RB.png)

**Here's what I get:**

![img2](https://i.imgur.com/D30xolp.png)

Quick demo illustrating my context: https://codepen.io/anon/pen/xjvPYW

How can I solve this?

**Comment by ivanpopelyshev** [comment]
You can't. Cache background in RenderTexture instead of second canvas.

**Comment by jcyuan** [comment]
put your background into a Container, and render this Container onto a RenderTexture, than use this texture to apply blendmode.

**Comment by Mikael295** [comment]
@jcyuan @ivanpopelyshev could you please provide an example?

**Comment by Mikael295** [comment]
Hello,
I've created a RenderTexture using `PIXI.RenderTexture.create(this.Renderer.width, this.Renderer.height)`
I also have a container which contain all my static sprites that can be accessed under the name `this.Stage2`

Now, how can I draw my container (stage2) into the rendertexture? Thanks

**Comment by ivanpopelyshev** [comment]
`renderer.render(stage2, renderTexture)`

**Comment by themoonrat** [comment]
@Mikael295 closing this as it seems answered. If you need anymore help, just ask :)
