### ISSUE TITLE
[QUESTION] Blurry text after scaling

### ISSUE THREAD

**Issue by artleitch** [pixijs/pixi.js#4939]
Hey there! I’m attempting to create a labelling system for a map where a user can zoom into the canvas to see the labels more clearly, however I’m finding that when I scale the container, the text labels are becoming blurry. Please see attached reduced test case

https://codepen.io/David_Leitch/pen/GGKQax

Is there a way to render text in a way that will maintain the quality of the text while its container is scaled? I know that one solution is to render the text with a large fontSize and then scale down:

https://codepen.io/David_Leitch/pen/bKbvpZ

.. however, doing this creates memory issues on smaller devices when I have 100+ labels rendered at 60px

Do you have any suggestions on how I can achieve high quality text at any scale?

**Comment by bigtimebuddy** [comment]
Using a high resolution BitmapText font is propbably going to yield better result in terms of memory, performance and scaling. Every time you draw a new Text object it generates a unique texture. So lots of Text objects really add up in terms of memory.

**Comment by artleitch** [comment]
Ah okay, yep got that working and have definitely noticed the difference. Just to check, this approach would mean packaging the app with a .fnt file to use as the font (as opposed to being able to use websafe fonts like Arial directly)?

**Comment by bigtimebuddy** [comment]
That’s correct, you need to prebake the font as an atlas. The downside is that a *.fnt isn’t as useful for Chinese, Korean and Japanese languages, which have many more characters and can be very difficult to pack together.

**Comment by artleitch** [comment]
Awesome, thank you very much for the help/info. Much appreciated

**Comment by bigtimebuddy** [comment]
No problem @artleitch. Good luck. I’m going to close, if you need anything else related to this issue, feel free to reopen.

**Comment by artleitch** [comment]
Hey there, sorry to reopen - the client is now interested in using Chinese, Japanese and Korean in their application. You mentioned earlier that the bitmap font method wasn't as useful for these languages and I see that now, with bitmap font files with impractical sizes of 5mb+. I wondered whether you had any other ideas on how to avoid pixellation when zooming in, while also using Chinese/Japanese/Korean fonts?

**Comment by ivanpopelyshev** [comment]
Try pixi-sdf?

**Comment by bigtimebuddy** [comment]
https://github.com/PixelsCommander/pixi-sdf-text

**Comment by artleitch** [comment]
Awesome, thanks for the tip. Will check it out!
