### ISSUE TITLE
New bitmap font parser breaks loader.

### ISSUE THREAD

**Issue by jonaswalekvist** [pixijs/pixi.js#4940]
Support for multiple textures for single bitmap font. #4641

This update breaks the loader. The loader never "completes" when trying to load bitmap fonts.  

This is the offending code: 

```
 for (let x = 0; x < pages.length; ++x)
        {
            const textureUrl = xmlUrl + pages[x].getAttribute('file');

            if (utils.TextureCache[textureUrl])
            {
                textures.push(utils.TextureCache[textureUrl]);
            }
            else
            {
                // load the texture for the font
                this.add(`${resource.name}_image${x}`, textureUrl, loadOptions, () =>
                {
                    const nextTextures = [];

                    for (let x = 0; x < pages.length; ++x)
                    {
                        const nextTextureUrl = xmlUrl + pages[x].getAttribute('file');

                        if (utils.TextureCache[nextTextureUrl])
                        {
                            nextTextures.push(utils.TextureCache[nextTextureUrl]);
                        }
                        else
                        {
                            return;
                        }
                    }
                    parse(resource, nextTextures);
                    next();
                });
            }
        }

```

See first else, here we load the images if not present in texture cache. Once loaded the inline function checks if its in the texture cache. 

This is the problem, because when adding the image to the loader we add a suffix "_image" + page number. Eg. `myFontImage.png_image0`

But when checked after loading complete we check if the original file name exist in the cache. 
`nextTextureUrl` will be something like: `myFontImage.png`. That don't exist in the cache so we just return. Missing the vital `next()`
```
// load the texture for the font
                this.add(`${resource.name}_image${x}`, textureUrl, loadOptions, () =>
                {
                    const nextTextures = [];

                    for (let x = 0; x < pages.length; ++x)
                    {
                        const nextTextureUrl = xmlUrl + pages[x].getAttribute('file');

                        if (utils.TextureCache[nextTextureUrl])
                        {
                            nextTextures.push(utils.TextureCache[nextTextureUrl]);
                        }
                        else
                        {
                            return;
                        }
                    }
                    parse(resource, nextTextures);
                    next();
                });
            }
```

So the next() function is never called which result in a loader that will never complete.

All the images and such do in fact load, but the loader will never complete and thus no complete event will be dispatched and our games will not start. 

- `pixi.js` version:  4.8.0
- Browser:  66.0.3359.181
- Device: Desktop PC

**Comment by bigtimebuddy** [comment]
Thank you for reporting. We have already seen this in the wild. Would you mind testing your game with this build: http://pixijs.download/dev/pixi.js, we recently fixed with #4932. Would be helpful to verify. If so, we can push out a hotfix for this.

**Comment by jonaswalekvist** [comment]
I wanted to test the fix in our games but we have a pretty complicated build process for our engine with npm, typscript and browserify and so on, and so forth . So I could not test the file you provided directly. But with some good ol' fashion copy/pasting from your file into 4.8.0 node module sources it worked perfectly. 

The code i tested was the bitmapFontParser and the changes in BitmapText.registerFont. I just copy and pasted over the whole functions. 

This is not a perfect verification process, but the issue seems fairly isolated so for me it's enough. 

Also i have not tested actually using a BitmapFont that uses multiple pages. We only use bitmap fonts for number so we don't need more. But i don't see any reasons for it not to work.

**Comment by bigtimebuddy** [comment]
Thank you for verifying, this is good enough for me.
