### ISSUE TITLE
[PIXI v5] cacheAsBitmap strange behavior...

### ISSUE THREAD

**Issue by Grimka** [pixijs/pixi.js#4941]
Hello there, I tried using PIXI v5 into my current game to see if it can solve a major mask issue (and it did gracefully !) but it added a new minor issue on my tilemaps.

All layers are different containers and cacheAsBitmap are set to true on all of them since their graphics are static.

Here is some screenshots 
https://imgur.com/a/Q7XKb1H

I also made 2 jsfiddle examples with same code but one using pixi4 and the other pixi5
v4 -> http://jsfiddle.net/Lubkht4h/1/
v5 -> http://jsfiddle.net/qm1z7m1a/1/

**Comment by bigtimebuddy** [comment]
Thank you @Grimka for posting this issue and the separate fiddles are very helpful. Give us some time to look into it.

**Comment by bigtimebuddy** [comment]
Seem like this affects WebGL only, here's the Canvas version:
http://jsfiddle.net/bigtimebuddy/w3mapts0/

**Comment by Grimka** [comment]
Thanks for your answer i'm happy to help the team !
Good luck fixing it, can't wait for v5 release !

cheers

**Comment by Mursaat** [comment]
Hello, what is the purpose of that line in `SpriteRenderer.js` ?
```js
// reset elements for the next flush
this.currentIndex = 0;
```

When I remove it, the example with the red square works.

**Comment by ivanpopelyshev** [comment]
you can remove that if you want `sprites` array to overflow and render extra sprites on every frame.

**Comment by ivanpopelyshev** [comment]
Still broken in `next` branch.

**Comment by themoonrat** [comment]
@ivanpopelyshev I've closed down a few cacheAsBitmap issues, like 5190 above but realised they're for v4. What's the status of cacheAsBitmap for v5?

**Comment by Parez** [comment]
Experiencing the same strange behaviour. And this is the core feature my app needs. Will have to use v 4.x for now
