### ISSUE TITLE
Feature request: PIXI.Text empty strings and PIXI.TextMetrics spaces

### ISSUE THREAD

**Issue by spiekermax** [pixijs/pixi.js#4942]
### PIXI.Text
PIXI.Text currently does not support empty strings like "" and instead will replace such with " ".  
-> Please allow empty strings.

### PIXI.TextMetrics
`(PIXI.TextMetrics.measureText("sample  ", textStyle).width  == PIXI.TextMetrics.measureText("sample", textStyle).width)` currently returns `true`. 
Also `PIXI.TextMetrics.measureText(text, textStyle, true).lines[index]` returns a string that does not include spaces if they are at the end of the text: For example: "Sample text\nwith second line " would return "with second line" only  if `index = 1`, instead of "with second line ".
-> Maybe an option should be added that allows to measure spaces aswell.

If needed I can provide a jsFiddle with the presented issues!

- `pixi.js` version: 4.8
- Browser: Chrome 66.0.3359.181
- Device: Windows 10

**Comment by themoonrat** [comment]
I agree that text should be allowed to be just `""`
However, allowing this would be a breaking change to expectations for v4 (I know in my libs we have an expectation that 'empty' text in pixi will show as `" "`)

Would be good to fix this for v5
