### ISSUE TITLE
Text rendering artifacts and wrong canvas size

### ISSUE THREAD

**Issue by shepelevstas** [pixijs/pixi.js#4947]
### Expected Behavior
Crisp text rendering
Canvas size set in PIXI.Application options argument

### Current Behavior
Blurry text rendering with strange artifacts
The letter M has some "horns"
![untitled-1](https://user-images.githubusercontent.com/14919836/40823582-0b2de88a-659b-11e8-8bb9-d91533bd9e88.jpg)

### Steps to Reproduce
On Windows 7 I have UI set to 150%
so I set new PIXI.Aplication({resolution: 1.5}) otherwise it looks even worse
also right after creating an app I have to set app.renderer.autoResize=true and app.renderer.resize() to my desired size, since PIXI.Aplication({width:  and height:}) are scaled 1.5 times and everything looks bad again and the canvas size is wrong.

### Environment

- `pixi.js` version: 4.8.0
- Browser: chrome&firefox
- Device: Desktop Win7

**Comment by ivanpopelyshev** [comment]
btw, you can pass autoResize here:
```
 PIXI.Aplication({resolution: 1.5, autoResize: true}) 
```

**Comment by shepelevstas** [comment]
Thank you! I'll study more! =)
