### ISSUE TITLE
The 3d chart use pixijs how to do?

### ISSUE THREAD

**Issue by TongDaDa** [pixijs/pixi.js#4949]
![screen shot 2018-06-01 at 6 20 32 pm](https://user-images.githubusercontent.com/23241188/40836227-80e50ce8-65c8-11e8-8b75-c42b75c45832.png)

![screen shot 2018-06-01 at 6 21 44 pm](https://user-images.githubusercontent.com/23241188/40836279-af1e6c3a-65c8-11e8-9f37-2b4e2daa40c6.png)

**Comment by jcyuan** [comment]
pixijs是2D引擎。没法做这个。你这个去用three.js https://github.com/mrdoob/three.js

**Comment by TongDaDa** [comment]
@jcyuan 感谢回复,为什么用中文回复我，难道，我的2级英文水平暴露了？

**Comment by jcyuan** [comment]
是的。看到这种英文基本上就可以确定是中国人。。。

**Comment by jcyuan** [comment]
@TongDaDa 这个issue关掉吧，以免给别人造成困扰。
