### ISSUE TITLE
Single Page BitmapFont parsing issue

### ISSUE THREAD

**Issue by khacha** [pixijs/pixi.js#4950]
### Expected Behavior
version 4.7.3 I load a bitmap font (.xml) and BitmapText was working
### Current Behavior
version 4.8.0 I load the a bitmap font (.xml) and BitmapText is not working, because the frame size of the children of BitmapText is x: 0, y:0 , w:0, h: 0 but the texture is the proper BitmapFont texture
### Possible Solution
If there is one page for bitmapFont in the xml there is no page attribute for characters, which means 
the page is NaN and the frame rectangle will be 0 0 0 0 for it. Some more additional conditions are needed. 
//BitmapText.js
...
page = parseInt(letter.getAttribute('page'), 10);
if (isNaN(page)) {
    textureRect = new core.Rectangle(0, 0, 0, 0);
    page = 0;
} else {
    textureRect = new core.Rectangle(parseInt(letter.getAttribute('x'), 10) / res + textures[page].frame.x / res, parseInt(letter.getAttribute('y'), 10) / res + textures[page].frame.y / res, parseInt(letter.getAttribute('width'), 10) / res, parseInt(letter.getAttribute('height'), 10) / res);
}
...

### Steps to Reproduce
make a bitmapFont in xml format which has only one texture , where char tags doesn't have a page attribute and create a BitmapText.  Use PIXI 4.8.0 version - with 4.7.3 it works
### Environment

- `pixi.js` version:  4.8.0
- Browser: Chrome 66
- Device: Mac

**Comment by khacha** [comment]
#4940 maybe related to this issue @bigtimebuddy

**Comment by bigtimebuddy** [comment]
@khacha Could you please test the latest dev build: https://pixijs.download/dev/pixi.js

Does this fix the problem?

Or better yet, make a jsfiddle that reproduces the problem.

**Comment by bigtimebuddy** [comment]
@khacha what tool did you use to generate the fnt file that doesn't have `page` reference for each character?

**Comment by bigtimebuddy** [comment]
Could you please test using this build: http://pixijs.download/fix-single-page-fnt/pixi.js
