### ISSUE TITLE
Sprite Rotation - Observable Point

### ISSUE THREAD

**Issue by Bokos-** [pixijs/pixi.js#4955]
Hello Pixi,

In Pixi is implemented observable point for many actions like scale, position etc. But i couldn't find this obs point for rotation ? Is there any way how to listening on rotation change?

Now software creates two sprites at one position and when one is changed then second must be changed as well. 

Thanks Pixi! 

![screen shot 2018-06-05 at 13 35 27](https://user-images.githubusercontent.com/4490694/40973655-5c393090-68c5-11e8-85c1-59b067c636c3.png)

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by djmisterjon** [comment]
what do you think about to replace updateTransform to check if rotation !== oldRotation?
It just a suggest.

```javascript
pixiObj.updateTransform = function updateTransform() {
// custom
 if(this.rotation !== oldRotation){
// do your stuff here
}
// native
        this._boundsID++;

        this.transform.updateTransform(this.parent.transform);

        // TODO: check render flags, how to process stuff here
        this.worldAlpha = this.alpha * this.parent.worldAlpha;

        for (var i = 0, j = this.children.length; i < j; ++i) {
            var child = this.children[i];

            if (child.visible) {
                child.updateTransform();
            }
        }
    }

```

**Comment by ivanpopelyshev** [comment]
Or use https://github.com/pixijs/pixi-display , just put two sprites in the same container, but in different layers.

**Comment by djmisterjon** [comment]
or maybe more more easy, you can also create a method to global

```javascript
function Rotates(obj1,obj2,value){
    obj1 = value, obj2 = value;
}
```

**Comment by Bokos-** [comment]
Thanks for fast response.
@djmisterjon yeah it looks nice but i was asking 'cause almost all attributes have same logic with obs points just rotation not.
@ivanpopelyshev thanks but this is solution for odering in pixi. I need change one sprite if its twin changed. ( on image are two sprite dark and normal/color. when i change normal sprite then dark must be changed as well )

**Comment by ivanpopelyshev** [comment]
You can put them in the same container, and when you move container they both will be moved too. The problem is that you have to draw one of them on different layer.

**Comment by Bokos-** [comment]
It helps, thanks!
