### ISSUE TITLE
[Question] is there atlas frame info in shader?

### ISSUE THREAD

**Issue by jcyuan** [pixijs/pixi.js#4960]
my shader is done, if i use a single texture, all work well, like this:

    let filter = new MyFilter();
    filter.texture = PIXI.Texture.fromImage("...");  //single image

but if I use a texture by `PIXI.Texture.fromFrame("frameID");` the texture is part of an atlas, the shader works incorrectly, so I wonder if the engine provides some coords info already, like screen size / atlas size etc? so I can transform the uv and then read the correct pixel from the atlas?

@ivanpopelyshev @bigtimebuddy @someone

**Comment by ivanpopelyshev** [comment]
Its possible. It was difficult, but we've made alpha sprite mask work with atlases: 
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/spriteMask/spriteMaskFilter.frag
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/spriteMask/spriteMaskFilter.vert

However, your case is easier - there's no sprite transform in it. In this line you'll have to use just `tex.transform.mapCoord`: https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js#L59

**Comment by jcyuan** [comment]
thank you for the info Ivan.
