### ISSUE TITLE
Two rectangles problem

### ISSUE THREAD

**Issue by Jujudo** [pixijs/pixi.js#4961]
Why does this not work? when i change rectangle2 x and y, it changes on rectangle1 too.. why?

let rectangle1 = new Rectangle(0, 920, 340, 150);
let rectangle2 = new Rectangle(0, 0, 450, 150);

  let texture1 = resources['images/foreground.png'].texture;
  let texture2 = resources['images/foreground.png'].texture;

  texture1.frame = rectangle1;
  texture2.frame = rectangle2;

  const foregroundObj1 = new Sprite(texture1);
  const foregroundObj2 = new Sprite(texture2);

  app.stage.addChild(foregroundObj1);
  app.stage.addChild(foregroundObj2);

**Comment by ivanpopelyshev** [comment]
because you use the same Texture object. You have to copy it .

```
let texture1 = new PIXI.Texture(resources['images/foreground.png'].texture.baseTexture, rectangle1);
```
