### ISSUE TITLE
Writing a container with a layout plugin

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4962]
I have put Pixi with Yoga quite easily.

I could write an extension of DisplayObject to consider dynamic layouts.
Would you like to be plugin or a commit to the code?

https://cl.ly/25292N0g3k3B

**Comment by bigtimebuddy** [comment]
Layout solutions should be a plugin.

**Comment by DavidGOrtega** [comment]
Agree, specially with the size of yoga, its quite heavy
