### ISSUE TITLE
Cannot read property 'scale' of null   in   _onTextureUpdate

### ISSUE THREAD

**Issue by Hardcore0331** [pixijs/pixi.js#4964]
### Steps to Reproduce
after call destroy of the text

### Environment

- `pixi.js` version: _e.g. 4.8.1_
- Browser: _e.g. Chrome  67.0.3396.79
- Device: _e.g. Desktop_

**Comment by bigtimebuddy** [comment]
Can you make a jsfiddle which reproduces the problem. We can use this to verify fix.

**Comment by Hardcore0331** [comment]
i had made a mistask, sorry

thank you for your reply;
