### ISSUE TITLE
BitmapText left/top/right/bottom padding defined in BitmapText .fnt file?

### ISSUE THREAD

**Issue by remiX-** [pixijs/pixi.js#4967]
Hey,

Will BitmapText ever include some padding in the near future? This would be so that `getLocalBounds` on `BitmapText` will include this padding.

**Comment by themoonrat** [comment]
Surely this is down to how you generate the bitmap pngs and the data you include on them? If you generate them with lots of padding between them all as described in the xml file, then surely you have what you need?

**Comment by remiX-** [comment]
It works fine with non-trimmed BitmapFonts but trimmed ones are a problem. Like for numbers, trimmed version of all the numbers would have different heights/widths

**Comment by themoonrat** [comment]
Cheers for the clarification :)
