### ISSUE TITLE
PIXI.Text  with anchor.x = 0.5 is blurred if resulting textures's width is odd.

### ISSUE THREAD

**Issue by Megabyteceer** [pixijs/pixi.js#4970]
to centralize single-line text i use this.anchor.set(0.5, 0);
but in 50% cases this text become blurred if  text.texture.widht is not even.

### Possible Solution
temporary i added this fix for me
```
PIXI.Text.prototype._onTextureUpdate = function() { // centred text with odd width is blurred bug fix
	if((this.style.align === 'center') && (this.texture.width & 1)) {
		this.x = Math.floor(this.x) + 0.5;
	} else {
		this.x = Math.floor(this.x);
	}
	PIXI.Text.__proto__.prototype._onTextureUpdate.call(this);
}
```
but one of better solutions may be is expand text's texture by one pixel if widht is not even.

### Environment

- `pixi.js` version: _e.g. 4.8.0
- Browser: Chrome 67
- Device:  Desktop

**Comment by Megabyteceer** [comment]
Additionally, any textures with 0.5 0.5 anchor and  odd sized texture will be blured. Mabe wiil  be  great to fix anchor to set pivot to rounded x,y values.

**Comment by Megabyteceer** [comment]
Additionally, any textures with 0.5 0.5 anchor and  odd sized texture will be blured. Mabe wiil  be  great to fix anchor to set pivot to rounded x,y values.

**Comment by themoonrat** [comment]
Also, potentially not needed if in v5 I add the PR for https://github.com/pixijs/pixi.js/pull/4833 . This PR allows each display component to draw to rounded pixels only, and turns that on for Text by default to stop blurriness

**Comment by Megabyteceer** [comment]
Very often case of using text in games is fly up text "+10"  when hero pick up coin of "-4" when hero gets damage. So with rounded x y text will fly not smoothly. Another case - UI panel with text which scrolls or meves sometime with easing. Any text with rounded x/y on UI element will move sharply. So i think enforce one object to be rounded and another to not is good for static objects only. In motion it will look bad.
