### ISSUE TITLE
[Question]how to automate the PixiJS canvas components.

### ISSUE THREAD

**Issue by anupamdas24** [pixijs/pixi.js#4971]
### Detailed Description

How to automate the PixiJS components.

The dom elements are not exposed, so using Selenium WebDriver, we are not able to automate it.

Please let me know if we can take help of Puppeter / Cypress / Protractor tool for automating the same.

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by Cristy94** [comment]
What exactly are you trying to automate? Can you define more what you mean by automate?

**Comment by anupamdas24** [comment]
In the above screenshot you can see there are few components present in the left side panel. I want to drag them and drop in the canvas (center).

**Comment by themoonrat** [comment]
Perhaps you could take a look at using the accessibility plugin? 
Example: https://www.goodboydigital.com/pixijs/accessibility/accessibility.html (press to change item and space to simulate a click)
Docs: http://pixijs.download/dev/docs/PIXI.accessibility.AccessibilityManager.html & pixijs.download/dev/docs/PIXI.accessibility.html

**Comment by themoonrat** [comment]
I'm saying that the accessibility plugin _does_ expose a DOM element if, say, you set a buttons property of accessibleTarget to true and press tab to select it.

You can also automate by exposing things that need interacting with to the browser. Write your own code that registers a 'start' button press to an automation controller, which can be the point that your automation library calls functions.

Or if could register the position of the button, to know where abouts to simulate a browser click event.

I've never used protractor so can't help with that, I'm afraid

**Comment by sureshready** [comment]
@anupamdas24 , are u able to automate canvas now?could you let us know the solution please. we are also facing the same issue.
Thanks in advance.

**Comment by Harsh-BBC** [comment]
@sureshready Pixi canvas elements are not exposed directly so we need to first use the application in accessibility mode as it exposes the elements. A key issue remains is you cannot add any Visual Regression Tests as images of those elements cannot be accessed. But functional tests can be done.
Let me know if you need any help specifically. Been working on automating Pixi canvas elements for almost 1 year now. Will try to help as much I can.

**Comment by sureshready** [comment]
Hi Harsh,

Thanks for taking your time in replying to this email .Actually, we are
trying to automate the canvas using selenium. as you say functional tests
can be done. is it through automation?. if so ,could you  help us here
please.


Thanks & Regards
Suresh Reddy
8977688776

**Comment by reddypdl** [comment]
> @sureshready Pixi canvas elements are not exposed directly so we need to first use the application in accessibility mode as it exposes the elements. A key issue remains is you cannot add any Visual Regression Tests as images of those elements cannot be accessed. But functional tests can be done.
> Let me know if you need any help specifically. Been working on automating Pixi canvas elements for almost 1 year now. Will try to help as much I can.

Hi @Harsh-BBC  can  you please help me out if you have any documentation on using Puppeteer for functional automation of Pixi canvas elements.

**Comment by GitIranna** [comment]
Been automating similar app using Sikuli which identifies objects based on Image recognition.  Give it a try if you haven't found a solution yet.

**Comment by sureshready** [comment]
Hey GitIranna,
Thanks for your response. I have used browser logs and got the
coordinates dynamically and automated using Selenium.
you can consider this as one option 😊

Thanks & Regards
Suresh Reddy

**Comment by vshevchenko12** [comment]
Hi @Harsh-BBC!
I would be grateful if you could share documentation about exposing the elements.

Thank you!
Looking forward to hearing from you
