### ISSUE TITLE
where baseTextures for video in the loader ressource ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4972]
hey guys where i can find **baseTexture** in the loader if i preload a video inside the loader ?
i deep search , but i can not find where base textures are stored .
```javascript
    loader_loadingDataVideo.onProgress.add((loader, res) => {
        console.log('res: ', res); // see printScreen bellow
```
![image](https://user-images.githubusercontent.com/24865815/41626743-3a3d1a84-73eb-11e8-8343-0b2dc68d9576.png)

But if i use ` var texture = PIXI.Texture.fromVideo('vid/intro_logo.webm');`

it work and it create a baseTextures, but i need to create and get baseTextures from the  loader instance .
![image](https://user-images.githubusercontent.com/24865815/41626890-fbf25914-73eb-11e8-89cd-2b1bbc74e717.png)
but if i use loader for preload video, i can find where texture are stored during progress ?

thanks a lot for help

**Comment by djmisterjon** [comment]
pixi demo here don't use loader 
https://pixijs.io/examples/#/basics/video.js

 i also see here a old tread that do not explain how it work.
https://github.com/pixijs/pixi.js/issues/2246

**Comment by englercj** [comment]
There is no loader middleware in pixi that converts a video resource into a texture. You need to make one with `PIXI.Texture.fromVideo()`. That method can take a string video url, or a video element (which is what the loader will give you).

**Comment by djmisterjon** [comment]
@englercj 
ok i understand, thank you.
so I have to find another way to synchronize `PIXI.Texture.fromVideo() ` with my current resource loader?
Because if i use the pixi loader to tell when all ressource are ready.
Caching all video with `PIXI.Texture.fromVideo() `, is not synchronous with the loader progress.

I have my little idea how to proceed now, but it will complicate my work.
Do you have a suggestion or a tips to synchronize the caching of a video with the loader?

Or i need to make a special update check for see when video are ready ?

**Comment by englercj** [comment]
On complete just call `PIXI.Texture.fromVideo()`. For example:

```js
loader.add('myvideo.mp4').onComplete.once(() => {
    const res = loader.resources['myvideo.mp4'];
    res.texture = PIXI.Texture.fromVideo(res.data);
});
```
