### ISSUE TITLE
How can i get the mouse cordinates on click?

### ISSUE THREAD

**Issue by tifDev** [pixijs/pixi.js#4974]
When click on the canvas /pixy application, i want to return the clicked zone coordinates. How can i achieve this?

**Comment by andrewstart** [comment]
Attach a [pointertap event to your InteractionManager](http://pixijs.download/release/docs/PIXI.interaction.InteractionManager.html#event:pointertap) (`yourRenderer.plugins.interaction.addEventListener(...`). On the [InteractionEvent](http://pixijs.download/release/docs/PIXI.interaction.InteractionEvent.html) that is passed to your listener, you can retrieve the global (to the canvas/renderer) coordinates of the event with `event.data.global`.

**Comment by tifDev** [comment]
Still not getting it. Could you please provide me an example? Or show me some example working? (like a jsfiddle)

It's something like this that i want:

var pixiCanva = ELEMENT THAT REPRESENTS THE PIXI CANVA AREA;

pixiCanva.on('click', onClick);

function onClick () {
var target = this;
        alert(target.x);
	alert(target.y);
}

**Comment by andrewstart** [comment]
https://jsfiddle.net/t7d0wxra/13/

`event.data.global` is a PIXI.Point with x/y properties that range from 0 to the size of the canvas.
