### ISSUE TITLE
[QUESTION] How can i change the RenderTexture resolution after it is created?

### ISSUE THREAD

**Issue by tekintatar** [pixijs/pixi.js#4975]
I am trying to figure out a way to change the rendertexture's resolution after it is created. Something like below:

```javascript
//Start with a render texture of default resolution 1
renderTexture  = PIXI.RenderTexture.create(1000,1000,PIXI.settings.SCALE_MODE,1);

//render with resolution 1
renderer.render(mySprite, renderTexture);

//Change the resolution to 0.5
renderTexture.baseTexture.resolution = 0.5
renderer.render(mySprite, renderTexture);
```
I tried using renderTexture.baseTexture.update() but it did not work because it is not created from a source. I tried doing a same width/height resize on RenderTexture hoping that it will trigger an update but there are same w/h controls that returns it without going further.  I  tried to resize directly RenderTarget and set resolution and corresponding FrameBuffer but i messed up with all the transforms and internal calculations. I guess this is being addressed in V5 [here](https://github.com/pixijs/pixi.js/blob/next/packages/core/src/renderTexture/BaseRenderTexture.js)  but is there a way to safely do this in v4? Maybe i am missing something. Any help will be appreciated.

**Comment by ivanpopelyshev** [comment]
What if you resize it first to 500x500? https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/RenderTexture.js#L98

**Comment by tekintatar** [comment]
Thanks for replying Ivan, I am actually looking for a functionality like in filters where you can set the the filter's resolution on the fly and the filter manager will adjust the RenderTarget resolution accordingly. In our case, we are editing an image with a custom object renderer plugin (inherited from the picture plugin you created)  with a custom shader and this image could be a large one zoomed out (Scaled down) to the main renderer. There is no need to scale down this image on full resolution on the main renderer for performance reasons therefore i thought that i can decrease the resolution while processing our custom shaders and increase it back when the processing is done. I know i can do this with filters but we already have a RenderTexture that we render the sprite on so the filters extra RenderTargets are creating an overhead in our case. I don't want to change the  RenderTexture size because they are already a baseTexture for sprites that are displayed on screen, that will mess up with whole transforms.
