### ISSUE TITLE
chromium,chrome 65 BaseTexture update not working ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4977]
### Expected Behavior
auto update texture in 
BaseTexture.prototype.update
https://github.com/pixijs/pixi.js/blob/f6f00047d6c523df2aa366cf3745eb831cec6ec5/src/core/textures/BaseTexture.js#L261

### Current Behavior
not update on chromium nwjs project (chrome 65.0), only work in fireFox !?

### Possible Solution
for now manual hack textures update on all container, video, spriteAnimation,spine....
example video
```javascript
    // hack update TEXTURES? 
    vid1A1_sprite.update = function() {
        vid1A1_textures.update(1);
    };

    const videoContainer = this.videoContainer;
    this.videoContainer.update = function() {
        videoContainer.children.forEach(child => {
            child.update();
        });
    };
```

### Steps to Reproduce
maybe more issue but what i can see.
Create Video,animatedSprites,spine. ....
Addchild to the stage, and run project with chromium

### Environment

-  * pixi.js - v4.8.1
- "5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"
- Device: _e.g. pc Win32
chromium:"65.0.3325.146"
http_parser:"2.7.0"
modules :"59"
nghttp2:"1.29.0"
node:"9.7.1"
node - webkit:"0.29.0"
nw:"0.29.0"
v8: "6.5.254.31"

**note:**
I made you a little video to show you the problem.
Thanks a lot for the help, am stuck and can not debug or understand more than that, because it need to deep understand pixijs engine.
Please tell me if you need more information or a demo project, it very urgent for me.
[VIDEO YOUTUBE](https://youtu.be/8JW3enpq2Hw)

**Comment by ivanpopelyshev** [comment]
Its known bug of chrome-65. Nothing can be done here.

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
yes i also try update to **Chromium 67 + Node 10.4.1**
and was not fixed.. grrr
But very strange.
I un-install all and clear all folder cache user data from + all regedit local nwjs create.
\user\current\AppData\Local\nwjs
_\user\current\AppData\Local\Temp
\user\current\AppData\Local\User Data_

**And now it works properly on a clean installation !!!**
wtf, i hate it when something stupid like that happens, a loss of colossus time.


**ps:** for your link yes, I noticed that this happens ocationelement, the video will freeze 1 time out of 5. This happens especially when it seems to have too much memory to give to the application.
For example when the debug console is open, it often happens that the video will freeze.

thank you very much for answering me.
