### ISSUE TITLE
No mention of TextStyle Editor in docs

### ISSUE THREAD

**Issue by Glitch0011** [pixijs/pixi.js#4978]
Hi all

When implementing Text in my project I never came across the helpful TextStyle Editor. 

Whilst that's mostly my own fault given it's the second listing on Google I think it'd be great to have some links to it in the docs.

Tom

**Comment by Glitch0011** [comment]
I've added a pull-request that does a first pass at solving this.

Maybe some value in adding a link to the advance Text demo in examples? I would but I couldn't easily find their repo 😄

Share and Enjoy
Tom

**Comment by themoonrat** [comment]
Cheers for the PR!
