### ISSUE TITLE
CacheAsBitmap on container with mask causing container contents to disappear

### ISSUE THREAD

**Issue by Saltallica** [pixijs/pixi.js#4980]
Hey all,

I'm using creating a "composite" mask that is made of several black and white sprites rendered to a render texture, eg: 

```javascript
...
//build composite mask
this.maskComposite = new PIXI.TilingSprite(textures.mainMask, width, height);
this.maskRenderTexture = PIXI.RenderTexture.create(width, height);
this.maskSprite = new PIXI.Sprite(this.maskRenderTexture);
...
```

This render texture is then applied as a mask to a container.  The mask is also *part of the container* so it stays in the same position as the underlying sprite

```javascript
this.maskSprite.anchor.y = 1;
this.maskSprite.position.x = 0;
this.maskSprite.position.y = main.height;
			
this.container.addChild(this.maskSprite);
this.container.mask = this.maskSprite;
```

This works as expected, except the performance -  the TilingSprite really slows things down.

Here's with the mask applied (note the colored building frames in the foreground):

![image](https://user-images.githubusercontent.com/1064853/41820967-e04e815a-77a7-11e8-932d-c0ae9268a5f0.png)

When turning on cache as bitmap, the container contents completely disappear:

```javascript
this.container.cacheAsBitmap = true;
```

![image](https://user-images.githubusercontent.com/1064853/41820994-377f2fec-77a8-11e8-85a4-92b66a7c415f.png)

I would expect the mask and sprite to be combined and cached as a bitmap - is this a bug or some restriction on the capability of the masking feature?

**Also, for comparison here's the same scene with no masking applied at all, but cached as a bitmap...**

![image](https://user-images.githubusercontent.com/1064853/41821050-f9564024-77a8-11e8-8d40-7d15b93b4ea3.png)

PIXI version: 4.6.2
Chrome 67

**Comment by ivanpopelyshev** [comment]
For example, cacheAsBitmap use of getLocalBounds() can translate the mask somewhere else.

**Comment by Saltallica** [comment]
Ok, fiddle here:

https://jsfiddle.net/nd9tmpcg/81/

...and it is working as expected here with this isolated example  

I'll have to investigate further

**Comment by ivanpopelyshev** [comment]
Please test it on this branch: https://github.com/pixijs/pixi.js/pull/5298

**Comment by themoonrat** [comment]
@Saltallica I know it's been a while, but could you confirm the above fix please?
