### ISSUE TITLE
[Question] Understanding worldTransform

### ISSUE THREAD

**Issue by shepelevstas** [pixijs/pixi.js#4982]
Please, help!
I am working on a graphics editor app, and I feel like PIXI is the best base for it!
But it still is complicated. I have a problem translating a Point from one Container to another. Now I am trying to translate a-Point-inside-a-Sprite-inside-a-Container-inside-stage to stage coordinates. I tried several approaches and missed every time. The Point is bottom right corner of the bunny sprite. I've made a [codepen](https://codepen.io/shepelevstas/pen/bKoXLM?editors=0011).
How do I get to the Point?
The picture of my misses:
![untitled](https://user-images.githubusercontent.com/14919836/41892447-4d7ce028-7942-11e8-8bd3-4120508407b3.png)

**Comment by odrick** [comment]
Use sprite.toGlobal({x: spritePointX, y: spritePointY})

**Comment by shepelevstas** [comment]
`sprite.toGlobal` also misses for some reason. You can see it the codepen.

**Comment by shepelevstas** [comment]
`sprite.toGlobal({x: spritePointX/sprite.scale.x, y: spritePoint.Y/sprite.scale.y})` seems to be correct

**Comment by shepelevstas** [comment]
same as `sprite.worldTransform.apply({x: spritePointX/sprite.scale.x, y: spritePointY/sprite.scale.y})`, but it looks like worldTransform is lagging behind in rendering movements. I thought `sprite.scale` is somehow represented in `sprite.localTransform` and tried to combine `sprite.worldTransform` and `sprite.localTransform` to avoid division of a Point by `sprite.scale`, buy appending and prepending worldTransform matrix with localTransform matrix produce unexpected result. How do I multiply two transform matrices?

**Comment by ivanpopelyshev** [comment]
If toLocal and toGlobal doesn't work for you, it might be that you actually need partial transformation, like "apply scale but not position", and pixi cant do that, you have to use toLocal on parent and add position.

Your last idea is lagging behind because you dont call updateTransform() or recursive post update transform, look up how DisplayObject `toLocal` and `toGlobal` work. At this point you absolutely need to clone pixi repo and investigate how transform code works.

**Comment by ivanpopelyshev** [comment]
Ok, I've spent 2 minutes to read your code and I cant spend more because you have too many lines in it and too many points. Please make it easier and tell me exact lines that you want me to modify and what do you want to see in it.

**Comment by shepelevstas** [comment]
Thank you! I removed everything unnecessary. My problem is line 38.

**Comment by ivanpopelyshev** [comment]
https://codepen.io/ivanpopelyshev/pen/xzyJRy

**Comment by shepelevstas** [comment]
That gets to the center of the sprite, but how do I get to the bottom right corner of the sprite?

**Comment by shepelevstas** [comment]
Oh, I can do that by changing the number in the brackets from 0 to 1, right? 
So the bottom right corner will be this:
```
const p = new PIXI.Point(
			this.texture.width * (1 - this.anchor.x), 
			this.texture.height * (1 - this.anchor.y) )
```

**Comment by shepelevstas** [comment]
I think your approach is much better! Thank you!

**Comment by ivanpopelyshev** [comment]
Yes, it takes time to understand global coords, local coords, and texture space. Previously you didnt take texture space into account. toGlobal/toLocal are useful enough that you dont need to call localTransform and worldTransform directly.

**Comment by themoonrat** [comment]
Closing as a problem solved. Please re-open if you have further questions
