### ISSUE TITLE
Blurry @2x images with WebGl enabled. Everything good without WebGl.

### ISSUE THREAD

**Issue by waxattack** [pixijs/pixi.js#4986]
Hello,

Chrome browser. We are using @2x images for retina displays and the method itself works fine except the image is blurry if WebGL support is enabled in browser.

Once we turn off WebGl everything looks good. As expected. 

We do not resize this image. Antialiase on|off doesn't do anything. LINEAR | NEAREST doesn't do anything. cacheAsBitmap = false.

Same issue in Mozilla except there we get blurry result with and without WebGl. Always (.

Here is the link to screenshot. Left is good version without WEBGL right is with WEBGL enabled.

https://snag.gy/WDhErK.jpg

Thank you.

**Comment by ivanpopelyshev** [comment]
Hi! Do you pass correct "Resolution" parameter in renderer through options in constructor or set it later? 

Dynamic change of resolution of renderer requires knowledge of how WebGLRenderer works, like, you have to change rootRenderTarget resolution too and then call resize on renderer itself.

For Canvas its easier. it just works.

**Comment by waxattack** [comment]
Ivan,

We do this only in constructor.

new PIXI.Application(width, height, {'transparent': true,  'resolution': window.devicePixelRatio, 'roundPixels': true})

**Comment by waxattack** [comment]
Ivan,

Also, we checked to be sure:

app.renderer.rootRenderTarget.resolution
app.renderer.resolution

=2
=window.devicePixelRatio

**Comment by ivanpopelyshev** [comment]
Then it should work, congratulations!

**Comment by ivanpopelyshev** [comment]
I mean, get me more information ;)

**Comment by waxattack** [comment]
That's the problem. We don't see anything unusual more (. That is why I'm asking here. Maybe we don't know any hidden parameters.

**Comment by ivanpopelyshev** [comment]
ok, you have multiple bugs there

first, its possible that you dont use canvas CSS, either pass "autoResize:true" in renderer options, either do it yourself: https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/SystemRenderer.js#L218

second, "baseTexture.resolution = window.devicePixelRatio" fixes it partially , now your texture has two times less size. Dont do that, texture resolution depends only on the source you loaded. 

third, if you didnt specify "@2x" in the name, there's no way pixi recognizes that it has to load different texture.

fourth, generateTexture returns new texture, and you dont use whatever texture it returned => why did you even call it?

**Comment by waxattack** [comment]
Ivan,

Sorry the developer is out of office already:

1. We do not set any additional css. The game canvas size for regular displays is 960x640. On the retina it becomes twice bigger:
canvas width="1920" height="1280"

Looking in to inspector the css is set automatically: 
element.style {
    width: 960px;
    height: 640px;

2. Removed. No changes.

3. We use @x2 in names. More to say, we now doing all the experiments with @x2 image only, even for regular displays. To be sure.

4. Yes, sorry, this is the part from old code. You right, in case of our bitmap image we do not need to generateTexture again.

**Comment by ivanpopelyshev** [comment]
ok, then it should work :) give us more details and we'll be happy to help!

**Comment by waxattack** [comment]
Ivan,

Fixed. It was our fault. There was a layer on top of the image which was hidden (we need it only some times). And this layer has the Color Matrix filter. PIXI filters also require resolution setting:

PIXI.settings.FILTER_RESOLUTION  = window.devicePixelRatio

Without this setting this layer made bluring for image layer behind.

**Comment by ivanpopelyshev** [comment]
Ugh, I knew i forgot something. Sorry, my telepathy failed, this issue appeared 3 times already and i had it too :) Yes, you have to modify FILTER_RESOLUTION.

**Comment by themoonrat** [comment]
Looks solved to me!
