### ISSUE TITLE
Mesh & Sprite performance compare?

### ISSUE THREAD

**Issue by navigator117** [pixijs/pixi.js#4988]
I have tried replace Sprite class with mesh.Panel in my game. The frame rate drops heavily. Is it possible to boost this up? I have created > 2000 sprite or mesh in my game for test.

### Environment

- `pixi.js` version: _e.g. 4.8.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by navigator117** [comment]
Thanks! I will look at that library. BTW, I want to use mesh class to do vertex animation to make my game look more impressive.

**Comment by ivanpopelyshev** [comment]
There are better meshes in heaven: https://gameofbombs.github.io/examples-heaven/#/mesh/plane.js

However, you have to read sources, there are not many docs on this thing: https://github.com/gameofbombs/pixi-heaven/tree/master/src/mesh

**Comment by navigator117** [comment]
What's the main difference between these two meshes? Can I implement heaven mesh use a pixi mesh class?

**Comment by ivanpopelyshev** [comment]
Meshes in that plugin have more features, and implementation is just different. Its easier to animate your objects with them, for example Plane and Rope have vertical mode (direction) and anchor.

No, you have to use `PIXI.heaven.mesh.Mesh` and `PIXI.heaven.sprite.Sprite` if you want to batch those things.

**Comment by navigator117** [comment]
I have tried the new Mesh class, but there are no obviously improvements, it's still very slow. Any suggestion? In my test i create > 2000 mesh objects

**Comment by ivanpopelyshev** [comment]
did you set `MESH_PLUGIN` setting to enable the batching?

**Comment by navigator117** [comment]
Yes, I have set: PIXI.heaven.settings.MESH_PLUGIN = 'meshHeaven';

**Comment by jcyuan** [comment]
if you know what "Instanced Buffer" is, I think this is easy to solve.
actually instanced mesh is a way to share the geometry (vertices etc buffers) for all the same objects (planes for your case), but with different matrix (for you plane instance) for them to calculate rotation /scale / translation in shader, so if you have 2000 same planes but with only different position/scale/rotation, this is the best way for you. 2000 planes actually = 1 drawcall.

**Comment by zakjan** [comment]
@jcyuan Pardon me for reopening this, but how can be an instanced mesh created and rendered with PIXI? I suppose you meant `ANGLE_instanced_arrays` extension? I found `instanced`, `instanceCount` properties in `Geometry`, calls to `drawElementsInstanced`, `drawArraysInstanced` in `GeometrySystem`, but it's not apparent how `instanceCount` can be set to > 1, I couldn't find a way how to use this feature. I was always seeing one GL call for each mesh, instead of one GL call for all meshes.
