### ISSUE TITLE
Set width and height of Sprite or Container is failing

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4990]
Hi guys, what's going on here? 
The first example would work if I wait the Sprite to be ready.
The second example works if the var container is typeof Container instead of Sprite. 

```js
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

var bunny = PIXI.Sprite.fromImage('required/assets/basics/bunny.png')

var container = new PIXI.Container();
container.addChild(bunny);
container.width = 10;
container.height = 10;

app.stage.addChild(container);
```

```js
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

var p       = new PIXI.Graphics();
p.beginFill(0xff0000, 1);
p.drawRect(0, 0, 50, 50);
p.endFill();

var container = new PIXI.Sprite();
container.addChild(p);
container.width     = 20;
container.height    = 20;

app.stage.addChild(container);
```

**Comment by themoonrat** [comment]
First, remember that in pixi, width and height are just another way of expressing scale.

Second, a containers width and height are expressed by the bounds of its children, but express no dimensions themselves. Whereas a sprites dimensions, with no children, are expressed by it's texture size.

Third, in your top example, you've set a scale on a sprite with no texture. When that texture loads in, it's texture size will change, but keep the large scale you've effectively set
