### ISSUE TITLE
[feature request] support for custom blend modes

### ISSUE THREAD

**Issue by nickav** [pixijs/pixi.js#4991]
I'm currently able to do this by defining my own like this:

```javascript
const { renderer } = app;
const gl = renderer.gl;
renderer.state.blendModes[20] = [gl.ONE, gl.DST_COLOR];

// ...then later
sprite.blendMode = 20;
```

Is there a better way to do this currently? Are there plans to add support for custom blend modes in a future version of PIXI?

**Comment by jcyuan** [comment]
PIXI currectly has implemented all features for both Canvas mode & WebGL mode.
this one I think is really hard to implement if use Canvase mode.

**Comment by nickaversano** [comment]
You could just leave it up to the user to provide one or both implementations of these. Either that or allow WebGL blend mode and let the user specify an existing canvas fallback.

**Comment by jcyuan** [comment]
> You could just leave it up to the user to provide one or both implementations of these. Either that or allow WebGL blend mode and let the user specify an existing canvas fallback.

emm, reasonable.
