### ISSUE TITLE
CanvasRenderer errors without referencing them in codebase on 5.0-alpha

### ISSUE THREAD

**Issue by MikaAK** [pixijs/pixi.js#4993]
I think this may have gotten lost. 

https://github.com/pixijs/pixi.js/issues/4921#issuecomment-391014009

Using Angular 6 and alpha-2 I get `CanvasRenderer` errors without having any reference to them in my code.

```
ERROR in node_modules/pixi.js/pixi.js.d.ts(636,36): error TS2694: Namespace 'PIXI' has no exported member 'CanvasRenderer'.
node_modules/pixi.js/pixi.js.d.ts(2022,35): error TS2304: Cannot find name 'CanvasRenderer'.
```

- `pixi.js` version: 5.0.0-alpha.2

**Comment by ivanpopelyshev** [comment]
Use pixi.js-legacy : https://www.npmjs.com/package/pixi.js-legacy . CanvasRenderer is optional now.

**Comment by bigtimebuddy** [comment]
I believe this Typing issue is fixed in https://github.com/pixijs/pixi.js/pull/4764

Probably will be making alpha.3 release this week for v5.

**Comment by MikaAK** [comment]
@bigtimebuddy  I can confirm this works on new alpha.3
