### ISSUE TITLE
Uncaught TypeError: PIXI.Geometry is not a constructor On PIXIJS.IO MESH SAMPLES

### ISSUE THREAD

**Issue by MikBin** [pixijs/pixi.js#4996]
Hi there, 
 simple issue, just happening on pixi website here:
https://pixijs.io/examples/#/mesh/triangle.js
all the samples of MESH category are throwing "Uncaught TypeError: PIXI.Geometry is not a constructor" error and the canvas screen is black.
![screenshot from 2018-07-04 17-18-11](https://user-images.githubusercontent.com/9196595/42284921-42fcfc60-7fae-11e8-9f03-061a968b19a4.png)
see chrome console screenshot

**Comment by ivanpopelyshev** [comment]
1) it requires you to switch to "next" branch
2) there were changes in "next" that broke that example.

summary: it just doesnt work right now :) We need a hero to fix it!

**Comment by MikBin** [comment]
ok Ivan. thanks

**Comment by bigtimebuddy** [comment]
Fixed.
