### ISSUE TITLE
Cache breaker for spritesheets loaded via JSON

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi.js#4998]
We are having caching issues with updating assets spritesheet. The spritsheet loading is done by adding `spritesheet.json` to the PIXI loader, which in turn will load the referenced `spritesheet.png` file. We added cache breaker to all the assets, like `spritesheet.json?version=1.2`, but there is now way to forward this cache breaker to pixi.

Chrome is aggresively caching the spritesheet.png file because it has the same name. Is there any way we can force the PIXI loader to add a cache breaker for the images loaded as spritesheets?

Currently, the files are loaded in the browser like:
```
spritesheet.json?version=1.2
spritesheet.png
```

What it should look like:
```
spritesheet.json?version=1.2
spritesheet.png?version=1.2
```

**Comment by themoonrat** [comment]
The loader lets you specify
`defaultQueryString` which automatically lets you perform cache busting for each item it loads. Might be what you need?
https://github.com/englercj/resource-loader

**Comment by Cristy94** [comment]
I tried setting `PIXI.loader.defaultQueryString` but it doesn't seem to do anything.

**Comment by themoonrat** [comment]
You probably won't need your own cache busting URLs and the loader doing to too?

**Comment by Cristy94** [comment]
Seems to be working now, the only issues is that the cache breaker is not added for sound (.mp3) files.
