### ISSUE TITLE
[QUESTION] How to create a glow around object with object's alpha = 0?

### ISSUE THREAD

**Issue by mfuluna** [pixijs/pixi.js#5000]
Hello. 
I need to create a glow shining border around graphics object. But object must have alpha =0.
 I mean, is it possible to create glowing border around some display object, in such a way as to not see this object, but only glow around his boarder?
In as3 I could create Shape, set its alpha to zero, and add glow filter. But in pixi, when I do the same - create Graphics object, set alpha to zero, and add to filters my GlowFilter, I see nothing. Only if object's alpha>0 I see my glow. But I need only boarder. I can't create my graphics without filling (because I actually load my graphic object from svg using a converter).

**Comment by ivanpopelyshev** [comment]
No, its not possible without usage of RenderTexture. You have to learn a number of tricks with RenderTexture and filters to do that thing.

Yes, theoretically its possible to do the same order of operations that flash does for it, but I want to remind you and everyone that there is no renderer in html5 that supports vector as good as flash does :(

**Comment by mfuluna** [comment]
> You have to learn a number of tricks with RenderTexture and filters to do that thing.
Is there any source where I can find info, about how to do that?

**Comment by mfuluna** [comment]
> You have to learn a number of tricks with RenderTexture and filters to do that thing.
Is there any source, where I can find some information, about how to do that?

**Comment by mfuluna** [comment]
That's great=) thank you, I will try to find my own solution

**Comment by ivanpopelyshev** [comment]
Actually, i think it cant be fixed. Do you know a shader to do it with rotations?

**Comment by mfuluna** [comment]
hm.. I don't need rotations.. Why do you mention them?

**Comment by ivanpopelyshev** [comment]
oops, wrong thread :)

**Comment by mfuluna** [comment]
ok =)

**Comment by ivanpopelyshev** [comment]
Of course its easier to just use photoshop and generate outlines :)

**Comment by mfuluna** [comment]
I've done it using two masks. It is not the best way because of performance, I believe, but it works.

**Comment by ivanpopelyshev** [comment]
Applause.

**Comment by ivanpopelyshev** [comment]
I just found that it is possible even in canvas2d, however, i might have found a bug in chromium while doing that :) https://bugs.chromium.org/p/chromium/issues/detail?id=863037

So yeah, glow/blur for invisible objects is a thing and pixi has to support it somehow.

**Comment by djmisterjon** [comment]
i trying do same thing here without success.
![affga3fgt](https://user-images.githubusercontent.com/24865815/43697539-ef47e39a-9912-11e8-8e25-a7dfe2baa9ef.jpg)

I would have thought it would work with 2 filters.
`sprite._filters = [ new PIXI.filters.AlphaFilter(0.3) , FILTERS.OutlineFilterx8Red ];`
there will not be any code example without using mask or renderer?
