### ISSUE TITLE
V5 graphics object causes crash when calling its destroy function

### ISSUE THREAD

**Issue by Owlzy** [pixijs/pixi.js#5002]
Can see the issue in this codepen, simply comment out the g.destroy(); line and the sprite will be visible. This is a fairly commonly used bit of code for us, to generate a small round texture for instance, so would be cool if you guys can find a fix. Seems that its the vao that is undefined when trying to call this.vao.destroy();

https://codepen.io/Owlzy/pen/PBYeqj

Thanks.

----------------------------------------------------------------------------

Expected - graphics object can be destroyed without crashing

Currently - crashes

Possible solution - ensure vao is defined. 

- `pixi.js` version: v5.0.0-alpha.3

**Comment by themoonrat** [comment]
We should check that this is fine in the latest rc

**Comment by themoonrat** [comment]
Can confirm it's fixed in latest dev: https://codepen.io/anon/pen/MxXrwB
