### ISSUE TITLE
In Safari browser on iphone, tapping an interactive rectangle doesn't work

### ISSUE THREAD

**Issue by edcarstens** [pixijs/pixi.js#5004]
The interactive rectangles in my game work in Chrome on my laptop, but not in Safari on my iphone.

### Environment

- `pixi.js` version: 4.5.5
- Browser: Safari (iphone)
- Device: iphone

**Comment by edcarstens** [comment]
Here is a link to my game:
https://wgx-oftzhvsjhn.now.sh/

**Comment by andrewstart** [comment]
What event are you listening for on the interactive rectangle?

**Comment by bigtimebuddy** [comment]
@edcarstens, we need more information to reproduce the issue. Please consider making a jsdfiddle or codepen to demonstrate the issue you're having?

**Comment by themoonrat** [comment]
@edcarstens Do you think you could create a jsfiddle for us please?

**Comment by bigtimebuddy** [comment]
The information you provided is insufficient and too vague. Without seeing some code we cannot help resolve your issue. Closing this issue. If you can recreate your issue, please post a jsfiddle.net link and we can reopen.
