### ISSUE TITLE
Issue starting up PIXI on Android

### ISSUE THREAD

**Issue by shanemccartney** [pixijs/pixi.js#5005]
We are using Pixi 4.8.1 when running PIXI on Android devices it reliably throws this error:

compileProgram.js:19 Uncaught TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.
    at n (compileProgram.js:19)
    at e.u (GLShader.js:40)
    at new e (Shader.js:46)
    at Object.generateMultiTextureShader (generateMultiTextureShader.ts:6)
    at SpriteBilinearRenderer.MultiTextureSpriteRenderer.onContextChange (SpriteRenderer.ts:109)
    at e.o.emit (index.js:150)
    at e._initContext (WebGLRenderer.js:274)
    at new e (WebGLRenderer.js:192)
    at i (autoDetectRenderer.js:49)
    at new t (Application.js:86)

The issue is on this line with the compileProgram method
gl.attachShader(program, glFragShader);

Which is possibly because the line above is failing i.e.
var glFragShader = compileShader(gl, gl.FRAGMENT_SHADER, fragmentSrc);

Causing for the 2nd param in the attachShader call to not be of the correct type.

This issue happens when using the projection extension and trying to compile the shader used for this with Pixi which uses highp in the shader, changing this to mediump fixes the error above.

**Comment by bigtimebuddy** [comment]
Thanks for reporting this. Could you produce a jsfiddle or codepen that reproduce the problem? Also, can you be more specific about what Android devices. Hardware and browsers can differ dramatic, so need some more details there.

**Comment by shanemccartney** [comment]
This issue was always producible on all our low end Android devices these included Samsung A5 and Kindle Fire. I am more or less just logging this in case it helps someone else.

**Comment by themoonrat** [comment]
I think this is related to https://github.com/pixijs/pixi.js/issues/4110 - where there should be some feature detection on precision to use, and auto revert down to a precision that the device _does_ support

**Comment by shanemccartney** [comment]
Yeah agreed on the solution and the related issue, the console even logs that the error is due the precision and wont compile the shader because of this, however we can not notice any visual difference in changing the precision from highp to mediump.
