### ISSUE TITLE
Path rendering in WebGL differs from Canvas, WebGL has "chips" in paths

### ISSUE THREAD

**Issue by fmhdp** [pixijs/pixi.js#5006]
Expected behavior:
Paths look the same when rendered with CanvasRenderer and WebGL renderer.

Observed behavior:
Paths look different when rendered with WebGL. 
An initial moveTo command adds an arrow like shape.
An arc added after a line chips off a bit of the line.
Example: https://jsfiddle.net/3snvu0dy/63/

This certainly is looking as obvious as it looks due to the fact that the line width in this example is really high. The example isn't artificial though, as I actually want to render that shape.

Relationship with other bugs:
This bug is very likely related to #3592 and #4046. 

I haven't verified it, but my best guess is that adding the second arc causes a duplicate point to be added to the points array for the shape, reducing the chip damage to what's described in #4046. Except that it's probably even less expected when adding a new shape to the graphics.

This is also not verified, but my best guess for the arrow-like shape at the start is that there's probably a point added to the points array for the shape when calling a moveTo command.

Environment:
PIXI 4.8.1, Fiddle looked the same in current Chrome (67) and Safari (11.1.1) on an iMac.
A random Windows 10 box renders it the same with current Chrome (67).

**Comment by fmhdp** [comment]
Thanks for the, as always, immediate response and the bug report flattery ;)

I'll see what I can do, but given you're working on replacing the current path handling altogether, I guess I'll try to find a workaround for the project I'm working on and hope that your Skia ports lands hopefully soon.

If I end up fixing things or finding a workaround that might be generally useful to others, I'll hand in a PR or post something. Same goes for #5007 and #5008.

**Comment by fmhdp** [comment]
I'm not sure if I can come up with a fix, but I think I triaged the problem coarsely at this point.
I'm working off this fiddle here, which has a bit less geometry but shows a nice chip: https://jsfiddle.net/3snvu0dy/101/

The graphics object collects the stuff to draw as polygon points. The calls to render end up here:
https://github.com/pixijs/pixi.js/blob/49b07302126167bb668e3a331d3d579ffde65673/src/core/graphics/webgl/utils/buildLine.js#L37

If you look at the points in graphicsData.shape.points, everything looks normal. The points array always has a size divisible by 2 (or is 0) and stores points as pairs of X and Y coordinates. So its [x1,y1, x2, y2....xn,yn].
A plot of the contents looks like this:
![chipped_graphicsdata_points](https://user-images.githubusercontent.com/29923869/42462496-b9325986-83a3-11e8-9fe8-02c8a2bcbda2.png)
The Y-Axis here is positive upwards,  that's why the curving goes the other way.
I presume we might be in trouble here already, though. The second and the third point, at the start of the arc, have almost the same position. They overlap perfectly in the plot. Point 2 is (463.632, -87.867), point 3 is (463.63199999999995, -87.868). That's a delta of (~5e-14, 1e-3)!

If we actually enter the method referenced above and see what it does, it looks like it's trying to build the vertices that should end up rendering the line at its specified width. Let's see what happens if we plot the stuff that ends up in the verts array. (Format seems to be [X, Y, (rgba), ?], but 6 bytes per vertex with X and Y up front.)
![chipped_verticepoints_with_nums](https://user-images.githubusercontent.com/29923869/42463083-6ed50558-83a5-11e8-9a38-08d3adca9038.png)
I added numbers to the first couple of points, so we can see in what order things are drawn. The indices array at this point contains [1,1,2,3...86] - Two 1s, the counting to 86.

I have less of an idea about 3D graphics than any reader here might imagine, but I'd be surprised if this isn't rendered as ~84 triangles, where two points are reused for the next triangle. If we plot this in, we get this:
![chipped_vertices_with_triangles](https://user-images.githubusercontent.com/29923869/42463327-1a94b758-83a6-11e8-8f63-a724a0925be6.png)
Yeah, checks out, except for the Y-axis direction.

At this point I haven't really understood the algorithm that's doing the work here, but there's something that caught my eye:
https://github.com/pixijs/pixi.js/blob/49b07302126167bb668e3a331d3d579ffde65673/src/core/graphics/webgl/utils/buildLine.js#L143-L159
Here, the deltas for X and Y are calculated, a distance is calculated from that via SQRT and then there's a division with that value.
I'll have to dig a little deeper, but from the looks of it I wouldn't be surprised if we have a simple floating point accuracy problem.

Since git blames him as the newest contributor, I know his github handle and he has a genie as an avatar, maybe i can summon @englercj with a mention and a friendly smile :)

**Comment by ivanpopelyshev** [comment]
All those lines are processed with `earcut` later, so here we only generate the path itself.

**Comment by bmcgary** [comment]
I have run into this issue as well, even after updating to v4.8.4. Just as the issue states this only happens when using webgl. When forceCanvas: true is set there is no issue, as can be seen in this screen shot
![canvas](https://user-images.githubusercontent.com/9909710/50666853-6ca23d80-0f6b-11e9-8801-98bb1e3c4f4a.PNG)

This is the same shot but using webgl
![weg_gl](https://user-images.githubusercontent.com/9909710/50666881-8479c180-0f6b-11e9-9630-feef0a17e66e.PNG)

I am using d3 v4 to draw the arcs as so:
`ringArc.context(graphic)(pieSeg);`
pieSeg is just a result of d3.pie. 

Here is fiddle demonstrating what I am seeing: https://jsfiddle.net/23vn6bg9/1/ (Thanks fmhdp as I forked yours to begin.)

I am using Windows 10, Chrome 71, and have also seen this on FF 64

**Comment by bmcgary** [comment]
UPDATE: I figured out how to work around this. What I did was change d3.arc innerRadius to be a different number than the outerRadius and then filled the graphic object with graphic.beginFill() instead of with graphic.lineStyle(). So instead of making a really fat curved line I made a curved rectangle and filled it in.
