### ISSUE TITLE
360 degree arc is not a circle, is missing part of a sector

### ISSUE THREAD

**Issue by fmhdp** [pixijs/pixi.js#5007]
Expected Behavior:
Drawing an arc from angle 0 to 360 * PIXI.DEG_TO_RAD should draw a circle

Current Behavior:
It draws almost a circle, but a bit is missing. See: https://jsfiddle.net/3snvu0dy/83/
At around ~362 degrees, the arc seems to turn into a real circle.

Environment
PIXI 4.8.1, Chrome (67) on Windows and OSX.

**Comment by ivanpopelyshev** [comment]
Probably related to #5006, first and end points are almost the same => duplicate edge.

**Comment by fmhdp** [comment]
I haven't looked into the code that draws the circles yet, but I think I have a limited workaround for my case.
It seems that the arcs being drawn have too short an angular length as a fraction of their angular length. By stretching the start and end each about 0.013 times the angular length of the arc, one backwards, one forwards, we get the arc to have the correct angular length when rendered.

There's a caveat in that the arcs aren't drawn correctly in another way that gets visible when trying to draw a circle as multiple segments. You can't do that without either having crevices at the outside diameter or overlaps on the inside diameter.

That's certainly no fix and if you look closely at e.g. overlaid semi-transparent arc segments, you can see that they overlap more in the center than at the outside, hinting at the arcs having other problems. But for making sure that opaque elements with mostly 45 degree angles don't have gaps when touching each other and "flat" endings, this should be enough.
Here's a fiddle: https://jsfiddle.net/3snvu0dy/159/

If you enable adaptive curves, the necessary factor changes. That seems to indeed point towards the problem of points going missing. Probably points at the outer diameter, which would explain the deformation of the arc segments and the missing angular length.

**Comment by fmhdp** [comment]
A better bandaid seems to be to change this line:
https://github.com/pixijs/pixi.js/blob/49b07302126167bb668e3a331d3d579ffde65673/src/core/graphics/Graphics.js#L657
to
const theta = sweep / ((segs * 2) - 1);
and leave adaptive curves off.

This still isn't correct, but changes the drawn arc length from being noticeably too low to being just a tad too high.
