### ISSUE TITLE
Extract container to image - wrapped in white space

### ISSUE THREAD

**Issue by Bokos-** [pixijs/pixi.js#5013]
Hello PIXI community,
I would like to create image from PIXI.Container with mask (in my case only sprites/texts which are pasted on t shirt). 
So I used `app.renderer.plugins.extract.image(spriteContainer)` and plugin then returned the image of container. The problem is image is wrapped with big white space around. Maybe it depends on dimensions of canvas ? 
Or my setting PIXI.settings.RESOLUTION = 2

Please, how can I get only visible part of container without white space around? 
Some images below.

### Current Behavior
Canvas without mask:
![screen shot 2018-07-11 at 10 14 11](https://user-images.githubusercontent.com/4490694/42559710-32aedc92-84f5-11e8-9110-1936fbdfc9a0.png)

Canvas with mask:
![screen shot 2018-07-11 at 10 14 21](https://user-images.githubusercontent.com/4490694/42559612-e896587e-84f4-11e8-8aef-816dfaaafc1e.png)

Extracted canvas as image:
![screen shot 2018-07-11 at 10 14 59](https://user-images.githubusercontent.com/4490694/42559615-e9fca038-84f4-11e8-8bb4-6c2de3d91ab7.png)

**Comment by Bokos-** [comment]
Example
http://jsfiddle.net/54zu1y7n/19/

**Comment by ivanpopelyshev** [comment]
I have a feeling that this issue will be answered only when we make a pass on extract plugin for v5. Try to find a workaround.

You can try to render this thing to `renderTexture` and then pass it to extract.

**Comment by Bokos-** [comment]
What do you mean by renderTexture? Would you introduce some example, please? 
http://jsfiddle.net/54zu1y7n/31/

**Comment by ivanpopelyshev** [comment]
you dont need one more renderer for this, you should use `app.renderer`. Sorry, i dont have time to explain, and there are too many questions about it in last few days both here and on forums. 

The only way is to look up all pixi examples related to `renderTexture`, like https://pixijs.io/examples/#/basics/render-texture.js

You have to understand how it works and not just wait for a solution in terms of pixi API. `extract`, `cacheAsBitmap` and some other things in pixi rely on it, and the only way to get rid of bugs in them is to study RenderTexture, make a workaround for your case, and if you have good enough solution - make PR for other people to use, or at least make an article about it.

**Comment by Bokos-** [comment]
Thanks. I created pull request with fix.
https://github.com/pixijs/pixi.js/pull/5016
