### ISSUE TITLE
Question: Garbage Collecting Only Some Textures

### ISSUE THREAD

**Issue by Prozi** [pixijs/pixi.js#5014]
On latest pixi version in our project, we'd like the pixi garbage collector to still be on AUTO but with possibility to not garbage-clean some of our textures that we know will be re-used

Is there such possibility in current/next stable release to mark some textures not to be GC'd while keeping the default behavior of GCing those that arent marked/in array/something

Regards, Jacek

**Comment by ivanpopelyshev** [comment]
According to https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/TextureGarbageCollector.js#L65 , it doesnt care about RenderTextures.

You can make a hack - just add that field in your BaseTexture :)

**Comment by Prozi** [comment]
you mean adding `_glRenderTargets = ...` to textures I dont want to cleanup?

**Comment by ivanpopelyshev** [comment]
Yep.

**Comment by ivanpopelyshev** [comment]
However, it might be a problem for `updateTexture` method, so you should set that thing after it was called. https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/TextureManager.js#L74

Or just make a patch for gc: `renderer.textureGC.run = function() { ...} ` add your own flag there.
