### ISSUE TITLE
Graphics addHole() strange artifact

### ISSUE THREAD

**Issue by Patrick-Hammond** [pixijs/pixi.js#5015]
Hi,
I'm wanting to add some square holes in a rectangular polygon and in some cases something strange happens. It's best illustrated by this http://jsfiddle.net/knwf6L9c/
I haven't figured out yet whether there is a particular arrangement or order that triggers this issue.
Perhaps someone has some idea of what is going on?
Thanks!

**Comment by Patrick-Hammond** [comment]
@ivanpopelyshev thanks! It appears I may have hit an issue with duplicate hole vertices https://github.com/mapbox/earcut/issues/67
If I reduce the hole size to avoid duplicates, then my example looks correct http://jsfiddle.net/Lsg5um6e/

**Comment by bigtimebuddy** [comment]
If they share verts you have to make the hole contiguous:
https://jsfiddle.net/knwf6L9c/13/

**Comment by Patrick-Hammond** [comment]
@bigtimebuddy much more elegant solution, i'll do it like this!
