### ISSUE TITLE
Infinite Scrollbar

### ISSUE THREAD

**Issue by gsknbabu** [pixijs/pixi.js#5019]
Hi,
Is there a way to allow the canvas object to be scrolled beyond content. 
Example:  
A canvas created with 1000*1000. And Enabled PAN and Zoom on the canvas.  Draw a rectangle on the canvas and move the rectangle with mouse to the edge of the boundaries( top,right, bottom, left) it should scroll the the rectangle to the end of the canvas. 

Right now my issue is I can drag the rectangle till the browser boundaries. I need to allow the rectangle to drag beyond the content so that I can use the full canvas.  I can PAN the canvas to move around the browser.

Thanks,
Naveen.

**Comment by ivanpopelyshev** [comment]
Yes, it is possible!

Please make a fiddle, to start with something.

**Comment by gsknbabu** [comment]
Thanks Ivan,
I have created fiddle http://jsfiddle.net/gsknbabu/sD8Tt/412/
I added the container to access the pivot, somehow not working.  Please help.

**Comment by djmisterjon** [comment]
this can maybe help you.
Am sorry am not sure if i understand all your issue.
https://codepen.io/djmisterjon/pen/pZjdQg
when you drag, you mean you lose the focus ?
You can try use classic listener for your document.
https://developer.mozilla.org/fr/docs/Web/API/EventTarget/addEventListener
```javascript
    document.addEventListener('mousemove', mousemove_Editor);
    document.addEventListener('mousedown', mousedown_Editor);
    document.addEventListener('mouseup',mouseup_Editor);
    document.addEventListener('wheel', wheel_Editor);
    document.addEventListener('keydown', keydown_Editor); // change layers
```

also for use memory coor, her a sample from my source code
Credit to ivan, but sorry i can find the original tread. You can use pixi.point to get memory coor

```javascript
   const memCoord = new PIXI.Point(), memCoord2 = new PIXI.Point(); // for control zoom memory
let mX,mY,memX,memY; mX = mY = memX = memY = 50; // Mouse screen Position XY scoped, memX,memY its memory when mouse start hold 
const Zoom = TilesMap.scale;

 // zoom camera to a memory point
    function wheel_Editor(event) {
        const pos = new PIXI.Point(mX,mY);
        TilesMap.toLocal(pos, null, memCoord);
        if(event.wheelDeltaY>0){
            Zoom.x+=0.1,Zoom.y+=0.1
        }else{
           if(Zoom._x>0.3){ Zoom.x-=0.1, Zoom.y-=0.1 }; 
        };
        TilesMap.toLocal(pos, null, memCoord2);  // update after scale
        TilesMap.pivot.x -= (memCoord2.x - memCoord.x);
        TilesMap.pivot.y -= (memCoord2.y - memCoord.y);
        ScrollX -= (memCoord2.x - memCoord.x);
        ScrollY -= (memCoord2.y - memCoord.y);
        // update light zoom
        update_lightZoom();
    };

    // refresh all variable mouse
    function refreshMousePos(event) {
        // screen mouse
        mX = (event.pageX-Graphics._canvas.offsetLeft)/Graphics._realScale //Graphics.pageToCanvasX(event.pageX);
        mY = (event.pageY-Graphics._canvas.offsetTop)/Graphics._realScale //Graphics.pageToCanvasY(event.pageY);
        return Graphics.isInsideCanvas(mX, mY);
    };
```

**Comment by ivanpopelyshev** [comment]
actually im a bit busy, so if you dont want to wait on me, try search "pixi-viewport" lib
