### ISSUE TITLE
PIXI.Shader - How to use?

### ISSUE THREAD

**Issue by legman** [pixijs/pixi.js#5020]
I have a question regarding using the PIXI.Shader and the .shader property on a PIXI.Sprite. I am familiar with the difference between shaders and filters, I wish to use a shader on individual tiles to fill them a certain colour with alpha being 0 or 1 without the overhead of a filter. The end goal is a tile map that I use for picking isometric tiles.

I set up the shader correctly and applied it to each tile sprite, but it seems as if the PIXI.SpriteRenderer doesn't even use individual sprite shaders, rather it defaults to the generateMultiTextureShader function.

Am I missing something?

Thanks

**Comment by ivanpopelyshev** [comment]
Unfortunately, v4 its not possible to assign shader to sprite the same way as in v3. However, you can make a renderer plugin and set `sprite.pluginName` string to its name.

It requires some hacks.

Look here: https://github.com/pixijs/pixi-plugin-example

If you want batching and multitexturing for your shader, look at https://github.com/gameofbombs/pixi-heaven , specifically, https://github.com/gameofbombs/pixi-heaven/blob/master/src/base/webgl/SpriteRenderer.ts and the my custom shader based on it, https://github.com/gameofbombs/pixi-heaven/blob/master/src/twotint/sprites/SpriteHeavenRenderer.ts

**Comment by legman** [comment]
ok thanks for the quick reply

**Comment by ivanpopelyshev** [comment]
We want custom Shader is supported in v5. I think, @GoodBoyDigital works on it right now. 

As for v4, yeah, its only through plugins but even then its possible to achieve great things with it: https://pixijs.io/examples/#/projection/cards.js
