### ISSUE TITLE
Weird rendering issue in firefox

### ISSUE THREAD

**Issue by dumptyd** [pixijs/pixi.js#5022]
### Current Behavior
A bar appears next to the drawn canvas. I noticed that the bar is 150px long and `(300 - width)`px wide and it disappears as soon as the focus shifts to some other element, so it's not even possible to take a screenshot. 

Edit: The same thing happens when the height is less than 150px in which case this bar appears on the bottom.

### Steps to Reproduce
https://jsfiddle.net/dumptyd/05kbqaeg/ (Click Run several times)

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: Firefox 62.0b7 (64-bit)
- Device: Desktop

**Comment by ivanpopelyshev** [comment]
make a video.

**Comment by ivanpopelyshev** [comment]
Yeah, I saw that. I see the bar for one frame after "Run" but cant reproduce it without pressing the button.

**Comment by themoonrat** [comment]
I can't get it to happen here :/ Video would be good
Could it be a css issue?

**Comment by dumptyd** [comment]
Here's the video https://gfycat.com/PleasantDescriptiveHarborporpoise

**Comment by dumptyd** [comment]
>disappears **as soon as the focus shifts** to some other element

Also that part isn't exactly correct, the bar disappears randomly when you type something or right click somewhere but it stays if you don't do anything.

**Comment by jcyuan** [comment]
the action triggers renderer.resize, so I think this is a low-level problem related to buffer reallocating in some special browsers, does this appear in Chrome too?

**Comment by dumptyd** [comment]
I'm not familiar with the codebase, but in the gfy, I'm not resizing the canvas but instead re-running it every time I change the values. In one of the last updates of FF Dev Edition, this issue kind of went away (it was just happening for one frame, but it was hardly noticeable) but now it's back again.
