### ISSUE TITLE
v3 Shader doesn't work in v4

### ISSUE THREAD

**Issue by jake-a-wood** [pixijs/pixi.js#5023]
### Expected Behavior
https://codepen.io/omarshe7ta/pen/xVeWWy?editors=1010

This is the example I'm wanting to port over to pixi v4. It works fine in v3.

### Current Behavior
https://codepen.io/jake-a-wood/pen/wxKjNo?editors=1010

I've made small adjustments to reduce the number of uniforms send to the shader program to just reduce the number of variables of what might be going wrong. I've also changed the use of a sprite over to a graphic since it doesn't load the resource anyway due to cross-origin restrictions. 

### Possible Solution
I'm not certain what's potentially wrong here. I've ran this same shader code in VSCode using the glsl-canvas extension preview and it works fine without any errors.

### Steps to Reproduce
- Go to https://codepen.io/jake-a-wood/pen/wxKjNo?editors=1010 and see that the screen is black.
- You can uncomment last comment in the shader text to see that a simple use-case shader does indeed work.

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

Let me know if I can provide any more info on this!

**Comment by ivanpopelyshev** [comment]
just `uniforms.time` and not `uniforms.value`. 

Another different is mapCoord and clamping , please look in this article: https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters . However you can solve this one by assigning `container.filterArea=renderer.screen`

I will look at your fiddle closely later.

**Comment by jake-a-wood** [comment]
Thanks for responding!

I'm assuming you looked at the first link in regard to your initial feedback. That link is the v3 code, the second link (https://codepen.io/jake-a-wood/pen/wxKjNo?editors=1010) is my work porting it to v4. 

In regard to mapCoord and clamping, I'm don't think the article is relevant to this particular shader as there isn't a requirement to use a texture in my port. However, that is useful to know as I progress in understanding shaders in pixijs. So I do appreciate you sharing the wiki link. I'll likely refer back to it for future shaders.

**Comment by jake-a-wood** [comment]
Also noticed I put in the wrong reproduction link. Updated! Sorry about that.

**Comment by jcyuan** [comment]
change line 30 to:
that's all.

    {
		u_resolution: { value: [width, height] },
		u_time: { value: 0 }
	}

**Comment by jake-a-wood** [comment]
You are my hero @jcyuan. Thank you so much for noticing this! Sure enough! It works now!
