### ISSUE TITLE
pixi 4.8.1 bitmap font loading error. Cannot read property 'frame' of undefined

### ISSUE THREAD

**Issue by markknol** [pixijs/pixi.js#5025]
When loading bitmapfont I get a runtime error.

I bumped my pixi.js from v3.7.4 to v4.8.1 and then this error was introduced.

### Expected Behavior
Bitmap font should just be loaded and registered without errors. 

### Current Behavior
I get this runtime error
```
Uncaught TypeError: Cannot read property 'frame' of undefined
    at Function.registerFont (BitmapText.js:581)
    at parse (bitmapFontParser.js:5)
    at completed (bitmapFontParser.js:72)
    at Loader.bitmapFontParser (bitmapFontParser.js:89)
    at Loader.js:614
    at async.js:35
```

### Steps to Reproduce
* It doesn't _always_ fail, might be related to browser cache. Please test with empty cache.
* It doesn't seem to matter if I first try to load the image then fnt file.

0. Open <https://codepen.io/markknol/pen/WKweKd>
0. Open devtools
0. Observe error
0. If there is no error, add a space in the js, to re-run the pen. This triggers the error.

In general this is enough to reproduce
```js
let options = { crossOrigin: true };
let loader = new PIXI.loaders.Loader();
loader.add("fnt", "font.fnt", options); 
loader.add("png", "font_0.png", options);
loader.load();
```

### Environment

- `pixi.js` version: 4.8.1
- Browser: Chrome 67
- Device: _e.g. Desktop

**Comment by ivanpopelyshev** [comment]
It works for me. Console is clear.
https://codepen.io/ivanpopelyshev/pen/LBNERQ

**Comment by ivanpopelyshev** [comment]
Ok, explanation: second `add` it a problem. Workaround: just remove it.

This code produces an error if a texture resource exists, but loading is not completed yet: https://github.com/pixijs/pixi.js/blob/dev/src/loaders/bitmapFontParser.js#L95

**Comment by ivanpopelyshev** [comment]
fixed in dev.
