### ISSUE TITLE
Backgrounds are opaque when rendering

### ISSUE THREAD

**Issue by bedeoverend** [pixijs/pixi.js#5029]
I'm running into issues when trying to render text in WebGL. They're getting a solid background - sometimes as white, other times black. It sometimes happens with shapes too, where even with an alpha fill of 0 they get rendered, again as black or white, but not _all_ shapes. This doesn't happen with Canvas.

Does anyone have any tips on where to even start? I'm at a bit of a loss. I've looked around and seems most common cause is `preserveDrawingBuffer`, but that's all fine (see below config). It also is more likely to happen in the resulting image when you call `.toDataURL`, if that helps at all.

I'm setting up the renderer with the following options:

```
{
  transparent: 'notMultiplied',
  preserveDrawingBuffer: true,
  clearBeforeRender: true,
  antialias: true
}
```

**Environment**

- `pixi.js` version: 4.8.1
- Browser: Chrome 64
- OS: CentOS

Thanks!!

**Comment by ivanpopelyshev** [comment]
It should work. My telepathic abilities that its 90% change that its something wrong in chrome linux backend, videodriver or so. The only way to solve that is to find suitable workaround, and I can provide a number of ideas, however its better if we meet in the middle and you give the fiddle and a video.

**Comment by bedeoverend** [comment]
Ok actually ended up resolving it. For anyone in future who might have this issue, we'd updated `mesa-dri-drivers.x86_64` package on CentOS and that seemed to cause the problems. I don't have the specific version, but rolling it back fixed.

Thanks for the quick response - your telepathic abilities were spot on!
