### ISSUE TITLE
Why the outline effect doesn't work on chrome (Ubuntu)?

### ISSUE THREAD

**Issue by tifDev** [pixijs/pixi.js#5034]
In my web application i draw some elements on canvas and those elements show an outline red color on mouse hover. On windows it works but on ubuntu (desktop 18.04) it doesn't. Why? (If i open in mozilla browser it works but chrome not)

Example of the effect: https://pixijs.io/examples/#/filters/outline-filter.js

**Comment by ivanpopelyshev** [comment]
because filters in pixi dont work with CanvasRenderer. Make sure to update your graphics driver.

**Comment by jcyuan** [comment]
sounds like driver problem.

**Comment by themoonrat** [comment]
Does sound like one of the issues above
