### ISSUE TITLE
Kawase blur filter flickering edges on moving sprite

### ISSUE THREAD

**Issue by bedeoverend** [pixijs/pixi.js#5036]
So I'm applying a Kawase blur filter to a Sprite, but when the sprite moves, the edges of the sprite appear to 'flicker'. If the image is static, you don't see it. If you switch on cacheAsBitmap you also don't see it (not an option in my case unfortunately as I want to animate the blur). Anyone got any ideas / suggestions? Thanks!

Codepen that shows the bug: https://codepen.io/bedeoverend/pen/qymwmg

### Environment

- `pixi.js` version: 4.8.1
- `KawaseBlurFilter` version: 2.6.0
- Browser: Chrome 67
- Device: Desktop + Mobile

**Comment by themoonrat** [comment]
turning on `roundPixels: true` for the renderer seems to help a bit too, so might be a sub-pixel thing?

**Comment by bigtimebuddy** [comment]
In the demo, changing `sprite.x = 100 + 100 * Math.sin(SPEED * frame);` to `sprite.x = Math.round(100 + 100 * Math.sin(SPEED * frame));` solves the issue. So I agree that it may be a sub-pixel issue.

**Comment by bedeoverend** [comment]
Yup using `roundPixels` or manually applying `Math.round` solves it for me too. I'll leave this open as I'm pretty sure this is still a bug, but feel free to close. Thank you!
