### ISSUE TITLE
strange rope on mousemove behavior

### ISSUE THREAD

**Issue by mvk843** [pixijs/pixi.js#5037]
Hello! I made a rope with a texture of svg file with some text. I want it to distort on mousemove on it. Here is my code:
http://jsfiddle.net/swbem7t3/
But it distorts even when I move mouse not on the element, even outside the canvas. How can I fix it?

`pixi.js` version: latest
Browser: FF61.0.1
Device: Desktop

**Comment by mvk843** [comment]
I made a crutch:
 if (appX > 0 && appX < 800 && appY > 0 && appY < 600)
but is it normal?

**Comment by mvk843** [comment]
btw, did anyone do a wave effect for text on hover (like on the picture)?
http://i105.fastpic.ru/big/2018/0725/38/475c5ee3b4a81737fa24d2f738f5d538.png

**Comment by themoonrat** [comment]
Hi @mvk843 

First of all your fiddle doesn't work, I'm afraid, as it's trying to refer to scripts in the html that do not exist in the fiddle.

Second; by default the mouse move event is always sent, regardless if it over the object in question. You can change this behaviour via `renderer.plugins.interaction.moveWhenInside = true` - docs at http://pixijs.download/dev/docs/interaction_InteractionManager.js.html#line130

Third; if you don't want to change the above behaviour, then within the mousemove event, just check that the target matches your desired display object
