### ISSUE TITLE
Blurred sprite with scaled container behaves different when cached

### ISSUE THREAD

**Issue by bedeoverend** [pixijs/pixi.js#5038]
I've got a sprite which is inside a scaled container, and has a blur applied to it. Now I want to cache it as a bitmap (as a work around for 5036) at a certain point - but when I set cacheAsBitmap true, it blurs it slightly differently. See repro [here](https://codepen.io/bedeoverend/pen/EpXQJV) - any ideas? Thanks!

### Environment

- `pixi.js` version: 4.8.1_
- Browser: Chrome 67
- Device: Desktop

**Comment by ivanpopelyshev** [comment]
This issue appeared many times here, please use search. Every time its a pain.

**Comment by themoonrat** [comment]
https://github.com/pixijs/pixi.js/issues?utf8=%E2%9C%93&q=is%3Aissue+cacheAsBitmap+filter is the search you want :)
You get issues like https://github.com/pixijs/pixi.js/issues/4773 and https://github.com/pixijs/pixi.js/issues/4659

Essentially, filters + cacheAsBitmap on the same element and you're asking for trouble!

**Comment by bedeoverend** [comment]
Thanks @themoonrat - I had seen those errors, though thought they were different issues. But perhaps they are all symptoms of the same problem? Will leave this open in case someone has a specific fix for this particular issue, or I find a workaround. Thanks for PIXI btw, absolutely great library!
