### ISSUE TITLE
Getting error when set trim=true to the empty text

### ISSUE THREAD

**Issue by corporalik** [pixijs/pixi.js#5039]
![image](https://user-images.githubusercontent.com/1940989/43205934-30c1378e-902d-11e8-8626-c84d9412065b.png)

Hi there. Getting an error when trying to create any text with empty value. In my case the value will be assigned dynamically after some calculations.

### Steps to Reproduce
`let text = new PIXI.Text('',{trim:true});`

### Steps to Reproduce
`let text = new PIXI.Text('Initial text',{trim:true});`
`text.text = '';`

### Environment

- `pixi.js` version: 4.8.1

**Comment by johnSjo** [comment]
PR with a suggested fix: https://github.com/pixijs/pixi.js/pull/5045

**Comment by bigtimebuddy** [comment]
Merged into dev. Will be released with 4.8.2
