### ISSUE TITLE
skipUpdateTransform for specific DisplayObject?

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi.js#5041]
I have a container in which I constantly add sprites, I know that their position won't change so I don't want theit transform to be calculated each frame. Can I somehow pass `skipUpdateTransform` to the container so the `updateTransform()` call won't be called each frame? Something like `container.skipUpdateTransform = true`. The issue is that it looks like the `updateTransform` function uses the most CPU (7%) of all the functions in the app.

- `pixi.js` version: _4.7.1_
- Browser: _Chrome 67_
- Device: _Desktop_

**Comment by ivanpopelyshev** [comment]
make your own container and override `updateTransform` method. Like, how ParticleContainer does it.
