### ISSUE TITLE
Background image renders slightly blurry in PIXI v4 vs. PIXI v3

### ISSUE THREAD

**Issue by colmandesilva** [pixijs/pixi.js#5042]
I made a simple CodePen example to display the issue. I want to upgrade to PIXI was, but when I simply loaded in a background image (and applies scale/position) etc. I noticed that it was being rendered slightly blurry.

PIXI 3 version (Good)
https://codepen.io/colmandesilva/pen/PBKyYZ

PIXI 4 version
https://codepen.io/colmandesilva/pen/xJLmPW

At first I thought the issue was cause because I reposition the stage on resize on floats, so I tried forcing it to integers but that did not help.

I am out of ideas as what could be causing this issue. I hope one of you guys could point me in the right direction.

- `pixi.js` version: _e.g. 4.8.1
- Browser: _e.g. Chrome 68, Safar and FireFix
- Device: _e.g. OSX

**Comment by ivanpopelyshev** [comment]
`bg.texture.baseTexture.mipmap = false;` just after you added  or created bg. v4 enables mipmaps for textures of pow2 size, it affects the image. Sometimes its better, sometimes not.

**Comment by colmandesilva** [comment]
Mate you are a legend. Thanks for taking the time to reply. I did not stumble on mipmap on my searches, but good to know for future reference. Cheers.
