### ISSUE TITLE
Force PIXI.Text to render

### ISSUE THREAD

**Issue by siwel** [pixijs/pixi.js#5043]
Can you force PIXI.Text to render the texture (so you can clone the texture, use its width/height, etc.) *before* you add it to the scene?

```const width = window.innerWidth;
const height = window.innerHeight;
const options = {backgroundColor : 0xffffff};

var renderer = PIXI.autoDetectRenderer(width, height, options);
document.body.appendChild(renderer.view);

const stage = new PIXI.Container();
const style = new PIXI.TextStyle({
      fill: "red"
});

const text = new PIXI.Text('Hello World', style);

// Ideally want to force the texture to render here.
// text.texture.width = zero :/

stage.addChild(text);
renderer.render(stage);

// Getting texture works correctly here.
```

Thanks,
Lewis

**Comment by siwel** [comment]
For reference, I would intend never to add it to the stage directly. I'm trying to use with Spine, So something like this;


```
var text = new PIXI.Text(message, style);

// FORCE TEXT TEXTURE TO RENDER??

spineAnimation.hackTextureBySlotName('textSlot', text.texture, {width: 300, height: 300})
```

**Comment by ivanpopelyshev** [comment]
Next time just look in the sources: https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L120 . The level of hacks you are accessing requires basic knowledge of how to look through pixi files. believe me, after `hackTextureBySlotName` there'll be ten more small things that aren't mentioned in docs ;)

**Comment by themoonrat** [comment]
`text.updateText()` will force updating the canvas texture that the text is renderer to
`text.updateText(true)` if you wish to respect the `dirty` flag

**Comment by siwel** [comment]
Thanks very much for the speedy responses. Missed that method somehow.

**Comment by stephane-lallee** [comment]
Hey @siwel !

Nice hack :-)

I'm trying to use the same approach as you did (pixi.js + spine) and dealing with text is hell...
The text is streched/squeezed if the slot in spine does not match the text. 

Did you find any workaround this issue?

**Comment by djmisterjon** [comment]
Alternative if you want keep the pixi text feature, it create slots named `txtArea` with 1px*1px in spine editor.
and 

```javascript
const text = new PIXI.Text("dynamic text",style);
spine.skeleton.findSlot('txtArea').currentSprite.addChild(text);
```
Maybe not performance friendly !
