### ISSUE TITLE
Phenomenon: WebGL Residue / Resident RAM Leak

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#5044]
I develop a game that's left open 24/7 in a browser, so even the slightest memory leaks or bugs causing leaks stack up and crash things - previous examples include an early PIXI.Text texture destroy issue, and a temporary Chrome bug, tiniest issue, and the game catches it like a bug catcher :|

Latest issue I've been facing is an invisible increase in memory usage in Chrome, JS Heap is 24MB's and stable, yet the actual memory usage increases from 100-150MB's to 400+MB's

What makes things bizarre is that even after the tab is refreshed, that additional 300MB's is resident

As I don't know the inner workings of the WebGL system, can you give me any clues as to what could be the cause?

**Comment by ivanpopelyshev** [comment]
which version of pixi do you use?

**Comment by kaansoral** [comment]
I was using 4.6.2, and indeed that's probably it - going to test spamming Graphics on monday to verify (I've spammed pretty much everything else, but graphics didn't occur to me)

**Comment by kaansoral** [comment]
Spammed creating and destroying lines, compared 4.6.2 and 4.8.1 - couldn't reproduce the resident leak issue I mentioned

However, during this test, 4.6.2 produced 4fps, while 4.8.1 was 44fps - so there was a change

I'll keep an eye on the issue

**Comment by themoonrat** [comment]
Closing for now. We'll re-open if there's any more info on a recent version :)
