### ISSUE TITLE
Issue - Graphics.lineTo with delay dose not work.

### ISSUE THREAD

**Issue by shawnmypark** [pixijs/pixi.js#5047]
sorry. My english is short. so I can only post demo.

[DEMO](http://jsfiddle.net/1b68eLdr/48025/)

![image](https://user-images.githubusercontent.com/17754709/43387105-8b9798be-9420-11e8-950d-6244a0b9d555.png)

### Environment

- `pixi.js` version: 4.7.1
- Browser: All browser
- Device: Desktop.

**Comment by themoonrat** [comment]
I've updated the fiddle to use the latest version of pixi, and it still occurs: http://jsfiddle.net/4db7t15j/
Note: this is a WebGL only bug. Setting `forceCanvas: true` shows the expected behaviour of the line being extended every second

**Comment by themoonrat** [comment]
Looking it a bit:
```
points: (6) [0, 0, 10, 0, 20, 0]
shape: Polygon {closed: false, points: Array(10), type: 0}
```
Notice that there is a `points` array that has a length of 6 that does not match the shape object.
For Canvas renderer, there is no separate `points` array

**Comment by macropp** [comment]
Another option is to call `lineStyle` again before calling `lineTo`.

http://jsfiddle.net/qx3Lz9r7/1/
