### ISSUE TITLE
Comments in shader can comment out lines of code

### ISSUE THREAD

**Issue by bramhoven** [pixijs/pixi.js#5048]
### Expected Behavior
When creating a shader like this one for example:
```
varying vec2 vTextureCoord;

uniform sampler2D uSampler; // Just commenting some useful information

uniform vec4 newColor;

void main() {
  gl_FragColor = newColor;
}
```
When creating the filter I use do not pass the uniforms, but let ```extractUniformsFromString()``` parse the shader to extract the uniforms. ```extractUniformsFromString()``` should ignore comments and parse the variables like you think they would.

### Current Behavior
Currently it does not ignore comment and it sometimes ignores whole uniforms because of this. The way ```extractUniformsFromString()``` works is by splitting the shader source with the separator ```;```. The resulting array would be something like this:
```
[
"varying vec2 vTextureCoord",
 "uniform sampler2D uSampler",
 "// Just commenting some useful information uniform vec4 newColor",
 "void main() { gl_FragColor = newColor",
 "}"
]
```

As you can see the by splitting by ```;``` comments will be placed in front of the variables which would make them invalid.

#### Solution 1
One solution is to don't get the uniform types and names by using there default locations in a line, so instead of doing:
```
if (line.indexOf('uniform') > -1) {
      var splitLine = line.split(' ');
      var type = splitLine[1];

      var name = splitLine[2];
      // Do other extracting stuff
}
```
Get the indexes of the type and name by doing:
```
if (line.indexOf('uniform') > -1) {
      var splitLine = line.split(' ');
      var uniformIndex = splitLine.indexOf('uniform');
      var type = splitLine[uniformIndex + 1];

      var name = splitLine[uniformIndex + 2];
      // Do other extracting stuff
}
```

#### Solution 2
Another solution is to remove all the comments before parsing the shader source.
This can be done by using the following regex:
```
/(\/\*[\w\'\s\r\n\*]*\*\/)|(\/\/[\w\s\']*[\r\n]+)/g
```

In  ```extractUniformsFromString()``` we change
```
var lines = string.replace(/\s+/g, ' ').split(/\s*;\s*/);
```
to
```
var lines = string.replace(/(\/\*[\w\'\s\r\n\*]*\*\/)|(\/\/[\w\s\']*[\r\n]+)/g, ' ').replace(/\s+/g, ' ') .split(/\s*;\s*/);
```

### Steps to Reproduce
Create a shader with the following code or any other code with comments behind or above uniform variables
```
varying vec2 vTextureCoord;

uniform sampler2D uSampler; // Just commenting some useful information

uniform vec4 newColor;

void main() {
  gl_FragColor = newColor;
}
```

Create a sprite with just any texture and a filter with this source and add the uniform. Add this filter to the sprite and add the sprite to the stage
```
let filter = new PIXI.Filter('', fragmentSource);
filter.uniforms.newColor = [0.6, 0.6, 1.0, 0.1];

let rocks = new PIXI.Sprite(resources.rocks.texture);
rocks.filters = [filter];
this.stage.addChild(rocks);
```

You should now see a black square because the newColor uniform is not being detected by the ```extractUniformsFromString()```. After you remove the comment you can see that the color appears on the screen and it works like expected.

### Environment

- `pixi.js` version: 4.8.1
- Browser: Chrome 68.0.3440.75
- Device: Windows 10 Laptop

**Comment by djmisterjon** [comment]
that explains a little brothel here when we compile pixi-light.
I was wondering why there were comments characters.
![image](https://user-images.githubusercontent.com/24865815/43447055-88512a6e-9478-11e8-93e3-bf350caba973.png)

**Comment by TarVK** [comment]
I think purely using regex to extract the uniforms could also be a nice solution.
Below is a mock-up of what it could look like approximately.
```js
var regex = /uniform\s(\w+)\s(\w+)/g
var match;
while(match = regex.exec(shaderText)){
    var type = match[1];
    var name = match[2];
}
```
