### ISSUE TITLE
Hello ! How does pixi.js lay out a picture

### ISSUE THREAD

**Issue by yinhui1129754** [pixijs/pixi.js#5052]
Your issue may already be reported! Please search [existing issues](../) before creating one.

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by yinhui1129754** [comment]
I want to repeat the same spirit with pixi.js. Is it only a copy spirite?

**Comment by themoonrat** [comment]
You need a new Sprite object for each instance to be renderered, yes. But Sprites are such light objects, for all intents and purposes on most scenarios they are 'free'.
Alternatively, for certain scenarios, https://pixijs.io/examples/#/basics/tiling-sprite.js may be useful

**Comment by yinhui1129754** [comment]
已经解决了 谢谢
