### ISSUE TITLE
Renderer transform problem

### ISSUE THREAD

**Issue by eonicum** [pixijs/pixi.js#5053]
### Description

I want to implement camera movement using transform argument in [render method](http://pixijs.download/release/docs/PIXI.WebGLRenderer.html#render) of WebGLRenderer.
I tried [this code](http://jsbin.com/kelemifasu/edit?html,console,output) and expected scene translation, but nothing happened. Then I changed WebGLRenderer to CanvasRenderer and code execution crashed. Error from the console down below:

![default](https://user-images.githubusercontent.com/17524324/43677347-f8075e4c-9819-11e8-8294-8615882cea14.PNG)

### Environment

- pixi.js version: 4.8.1
- Browser: Chrome 68
- Device: Desktop

**Comment by ivanpopelyshev** [comment]
I think you have to pass matrix and not the transform there, its error in docs.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev is correct, this:
```js
renderer.render(stage, null, true, cameraPosition)
```
should be this:
```js
renderer.render(stage, null, true, cameraPosition.localTransform)
```
Example: https://jsfiddle.net/juhme24L/3/

Will make a PR to update docs.

**Comment by eonicum** [comment]
It works with CanvasRenderer only. Same code with WebGLRenderer does not translate a scene.

**Comment by bigtimebuddy** [comment]
That looks like a bug then.

**Comment by bigtimebuddy** [comment]
I see that but it has no effect on the render

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital knows how it supposed to work. No one properly documented this feature behaviour, there are no tests.

@eonicum just use position-pivot approach (look up it on html5gamedev forum) or look inside pixi-viewport.

**Comment by eonicum** [comment]
Are there any updates?

Honestly, I do not understand how this feature should work on paper. I tried to change the transform matrix each frame using canvas renderer and it changed sprite transform at the first call only then the transform argument was ignored ([demo](https://jsfiddle.net/eonicum/9q0x4dwc/)). [1]

I also looked inside the source code of webgl viewport class. Projection matrix which sends to the vertex shader changes only in a [activate](https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/utils/RenderTarget.js#L232) method. This method called only during resizing. I tested it in [demo](https://jsfiddle.net/eonicum/mgu8yosL/). Constant resizing with canvas renderer makes the black screen ([demo](https://jsfiddle.net/eonicum/3mnurxc5/)). If I resize canvas renderer with intervals it works the same as [1] ([demo](https://jsfiddle.net/eonicum/78d46ykp/)).

Hope you will understand my English 🙂

**Comment by ivanpopelyshev** [comment]
Did you try to change container position/pivot instead? I dont have estimate of time on this issue, nobody uses that parameter, its not critical, Probably, it'll be resolved when original author of the feature tells us what he wanted to do with it.
