### ISSUE TITLE
Reset Sprite's mask to null still makes the masked Sprite clipped (Only if Sprite has a filter)

### ISSUE THREAD

**Issue by ZumiKua** [pixijs/pixi.js#5058]
### Expected Behavior
go to http://zumikua.in/pixibug/
click the '123' button at top.
The full size of background.png should be visibile
### Current Behavior
only area of map_mask.png is visible
If I remove `window.background.filters = [colorMatrix];` from code, everything works fine.
### Possible Solution
After compare the Sprite object before and after mask applied, I found that filterArea is modified after setting mask, and setting it back to null does not bring this filterArea value back to the default value. I think this is the source of this bug.

### Environment
- `pixi.js` version: _4.8.1_
- Browser: _Chrome 67_
- Device: _Desktop_

the source code of this live demo:
````

    let app = new PIXI.Application({width: 1024, height: 768});

    //Add the canvas that Pixi automatically created for you to the HTML document
    document.body.appendChild(app.view);
    PIXI.loader.add("background.png").add("map_mask.png").load(setup);
    function setup(){
        window.background = new PIXI.Sprite(PIXI.loader.resources["background.png"].texture);
        let colorMatrix = new PIXI.filters.ColorMatrixFilter();
        window.background.filters = [colorMatrix];
        window.mask = new PIXI.Sprite(PIXI.loader.resources['map_mask.png'].texture);
        app.stage.addChild(background);
        app.stage.addChild(mask);
        window.background.mask = window.mask;
    }
    function buttonclick(){
        if(window.background.mask){
            window.background.mask = null;
        }else{
            window.background.mask = window.mask;
        }
    }
````

**Comment by JetLua** [comment]
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/managers/MaskManager.js#L114

The `target.filterArea` is not reset in `popSpriteMask()`.
