### ISSUE TITLE
i am use PIXI.Graphics

### ISSUE THREAD

**Issue by yinhui1129754** [pixijs/pixi.js#5065]
Your issue may already be reported! Please search [existing issues](../) before creating one.

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_
![image](https://user-images.githubusercontent.com/19921594/43875396-d45998be-9bc2-11e8-941a-b21eb19ccedb.png)

**Comment by yinhui1129754** [comment]
Why _width has value but width has no value

**Comment by yinhui1129754** [comment]
I called updateLocalBounds and didn't change the width the same way I wanted to change the width, but the width felt like it couldn't be changed.

**Comment by bigtimebuddy** [comment]
Please can you provide a jsfiddle or some code that demonstrates your issue.

**Comment by yinhui1129754** [comment]
http://wow.techbrood.com/fiddle/40691  这是地址

**Comment by yinhui1129754** [comment]
谢谢你的解答了 我最终解决了问题 这里估计是一个坑 我用的displayObject这个对象来解决的 这个对象是可以设置宽度与高度的

**Comment by bigtimebuddy** [comment]
Essentially this is what you're doing:
```js
var g1 = new PIXI.Graphics();
g1.width = app.screen.width;
g1.height = app.screen.height;
g1.drawRect(0, 0, this.width, this.height);
```
This is not how width and height work in PixiJS. You cannot set these properties because there's no content to resize. If you set width and height, based on the current size, it's used to compute scale. Because your Graphic has no content, there's nothing to change.

Try this instead:

```js
var g1 = new PIXI.Graphics();
g1.drawRect(0, 0, 100, 100);
g1.width = app.screen.width;
g1.height = app.screen.height;
```

**Comment by yinhui1129754** [comment]
是的 谢谢了
