### ISSUE TITLE
Video only have sound in Android wechat app webview.

### ISSUE THREAD

**Issue by peng** [pixijs/pixi.js#5066]
https://pixijs.io/examples/#/basics/video.js

This demo only have sound in android WeChat App webview .
WeChat have two model in android use native webview and use itself webview , itself webview is tencent x5-core webview .  Default is x5-core webview . The problem is in x5-core webview.
This problem also happen in QQ Browser App.

### Environment

- PixiJS 4.7.3
- Browser: WeChat App(tencent x5-core webview)
- Device: MI 5S , android 7.0

**Comment by themoonrat** [comment]
I'm not sure what PIXI can do about this; it sounds like an issue with the browser / webview implimentation

**Comment by peng** [comment]
I think it looks like a compatibility issue .  Like IE 6.

**Comment by kelvinlee** [comment]
@peng 昨天又测试了一下 , 

```
video.setAttribute('playsinline','');
video.setAttribute('webkit-playsinline','');
video.crossOrigin = 'anonymous';
var src = document.createElement('source');
src.setAttribute('src', "test.mp4");
src.setAttribute('type', 'video/mp4');
video.appendChild(src);

var vvtexture=PIXI.Texture.fromVideo(video);
vvtexture.baseTexture.source.loop = true
vvtexture.baseTexture.autoPlay = false
var videoSprite = new PIXI.Sprite(vvtexture);
videoSprite.texture.baseTexture.on('loaded',function(evt){
	this.source.play()
})
```

不在 fromVideo 里直接放 url , 而是先创建一个 video.

这个在安卓里可以播放, 但是低端机型可能还是有问题 我没测过 只测了 小米8.

**Comment by ihuguowei** [comment]
@kelvinlee 我使用 `fromVideo ` 貌似没测出问题，是我测试机型太少了吗，有什么坑可以探讨下。

**Comment by qianmenglin** [comment]
huaweiP10的机型也不可以，只有声音没有画面，和用pxi fromurl创建basetexture的效果一样

**Comment by qianmenglin** [comment]
我觉得像是pixi,js的问题，因为直接用video标签创建出来加上x5那些属性可以在微信上浏览器播放，但是用pixijs就只有声音没有画面

**Comment by kelvinlee** [comment]
@qianmenglin 不是pixi的问题 就是微信不支持canvas， 你用别的框架 或者原声canvas 也是不出画面的。

**Comment by devon** [comment]
This works: http://www1.pcauto.com.cn/test/gz/testdog/20170001/index.html

https://github.com/phoboslab/jsmpeg
