### ISSUE TITLE
How to get the fillColor of rect

### ISSUE THREAD

**Issue by BH-NOTHING** [pixijs/pixi.js#5067]
How do I get the fill color of the previous rectangle when I reset the rectangle border color?
fillColor is empty, and tint is not the previous color.LineWidth,lineColor,height,widht，These properties can be obtained through some properties, but the background color is not.
![image](https://user-images.githubusercontent.com/26459908/43937453-4fcc1fe4-9c90-11e8-8f13-36910e6abf65.png)

**Comment by bigtimebuddy** [comment]
Please provide some code that demonstrates your issue.

**Comment by BH-NOTHING** [comment]
'target' is Graphics Object.This is a bug, I solved it through Object.defineProperty create a new property to preserve the background color.

target.clear()
 target.beginFill(bgColor)
 if (borderWidth >= 0) {
    target.lineStyle(borderWidth, borderColor, 1)
   target.drawRect(0, 0, width - borderWidth, height - borderWidth)
 }else{
    target.drawRect(0, 0, width, height)
 }
