### ISSUE TITLE
Zoom integer multiple, some blur

### ISSUE THREAD

**Issue by 958877748** [pixijs/pixi.js#5068]
PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
![tim 20180811121038](https://user-images.githubusercontent.com/31437616/43988067-d95ef7f2-9d5f-11e8-80e1-e5f139ee46c5.png)
Please save it locally and use Microsoft Drawing to open this picture,
You will see the problem,
How to make him clear?

**Comment by 958877748** [comment]
Set the computer's zoom to 100%, and it's very clear. The Blur will appear at 150%, how to solve it
<img width="277" alt="default" src="https://user-images.githubusercontent.com/31437616/43988459-31c494a8-9d68-11e8-9a56-fb4c32718fc5.PNG">

**Comment by 958877748** [comment]
devicePixelRatio = 1.5

**Comment by 958877748** [comment]
devicePixelRatio = 1.5

**Comment by 958877748** [comment]
-webkit-min-device-pixel-ratio = 1.5

**Comment by 958877748** [comment]
window.devicePixelRatio 
 How to change him?

**Comment by themoonrat** [comment]
You can't change that. it's set by the browser. You can control the `resolution` scale factor when creating a PIXI application or renderer

**Comment by 958877748** [comment]
There is a workaround ,But there are some problems.
document.body.style.zoom = 100/window.devicePixelRatio+"%";

**Comment by bigtimebuddy** [comment]
Why not disable zooming with viewport meta tag?

**Comment by 958877748** [comment]
<img width="511" alt="default" src="https://user-images.githubusercontent.com/31437616/44011987-9ff502b4-9eee-11e8-84c9-a065910468d3.PNG">
Change the zoom of the browser makes "window.devicePixelRatio" change,
It's a breach.

**Comment by 958877748** [comment]
A new way to solve ->
document.body.style.cssText = document.body.style.cssText + '; -webkit-transform: scale(' +1/window.devicePixelRatio + ');-webkit-transform-origin: 0 0;';  
But there's got to be a better way.
Change the pixel ratio of the device to CSS,
make window.devicePicePixelRatio = 1

**Comment by jcyuan** [comment]
a bit strange requirement.. I don't think the result you change the page zoom is what you'll have on a phone even the pixelRatio changes?
