### ISSUE TITLE
Ask a proper way to create graphics based texture.

### ISSUE THREAD

**Issue by yiyuezhuo** [pixijs/pixi.js#5070]
I used the following code to create some static textures from `PIXI.Graphics`.

```
function graphics2texture(graphics, config){
    var renderer = PIXI.autoDetectRenderer(graphics.width, graphics.height, config);
    var stage = new PIXI.Container();
    stage.addChild(graphics);
    renderer.render(stage);
    var texture = PIXI.Texture.fromCanvas(renderer.view);
    return texture;
}
```

It works on my PC well, but failed in my mobile phone. I connect mobile Chrome to my PC Chrome to debug and find that it raise some `pixi.js:28788 WARNING: Too many active WebGL contexts. Oldest context will be lost.`. The problem can be bypassed if I call `new PIXI.CanvasRenderer` to force using canvas instead but I wonder whether my code abused WebGL/Canvas though it is able to run PC? Or there's
a smart method so that I can call `PIXI.autoDetectRenderer`-like function to find most effective way to create static graphic texture depending environment?

### Environment

- `pixi.js` version: v4.8.1_
- Browser: (For PC) Chrome 68.0.3440.106 (Official Build) (32-bit), (For android) Chrome 68.0.3440.91
- Device: Desktop/Android

**Comment by bigtimebuddy** [comment]
You want to create a RenderTexture instead of creating a new Renderer each time. Pass in the instance to the renderer you've already created.

```js
function graphics2texture(renderer, graphics) {
  const texture = PIXI.RenderTexture.create(graphics.width, graphics.height);
  renderer.render(graphics, texture);
  return texture;
}
```

**Comment by yiyuezhuo** [comment]
@bigtimebuddy Thanks a lot! The problem is fixed.
