### ISSUE TITLE
[QUESTION] Sprite should not scale with container but should change position

### ISSUE THREAD

**Issue by Justintijd** [pixijs/pixi.js#5071]
Whenever I drag the white square the black square scales with it. This is how I want it but the red squares in the black square are also scaling.. Is it possible to not scale the red squares? The red squares should change position but not scale.

I create a sprite with:
`new PIXI.Sprite(PIXI.Texture.WHITE)`

and then call a function:
```

function createSquare(instance, directions, x, y, placement) {
    instance.tint = 0xff0000;
    instance.factor = 1;
    instance.position.set(x, y);
    instance.interactive = true;
    instance.buttonMode = true;
    instance.directions = directions;
    return instance;
}
```
Is there a option to not scale the squares?

![scaling-issue](https://user-images.githubusercontent.com/33153367/44022726-b6bde750-9ee8-11e8-9987-7f7154b01056.png)

**Comment by themoonrat** [comment]
Could you create a jsfiddle for this please so that we can get a better answer to your question? Thanks!

**Comment by jcyuan** [comment]
when you drag, emit a customized event and red squares around the black box should listen to it. when they receives the event, do scale oppsite to its parent.

**Comment by Justintijd** [comment]
I made a quick example on [jsfiddle](https://jsfiddle.net/7afzr91g/197/)

When you click on the small red square the big white square gets smaller. The big red square scales with the white square. This is what I want but... the little black square should not scale but change position, is that possible? The black square should be in the red square BUT with the same height and width.

**Comment by jcyuan** [comment]
https://jsfiddle.net/7afzr91g/261/
