### ISSUE TITLE
How to set PIXI.text width and height to automatic

### ISSUE THREAD

**Issue by BH-NOTHING** [pixijs/pixi.js#5075]
How to set PIXI.text width and height to automatic, similar to the initialization height and height will automatically change with fontSize size.The problem I encountered was that after I set PIXI.text width and height, I want to set its width and height  to be automatic..

**Comment by djmisterjon** [comment]
the font size are accessible in the text objet like this if you not have scoped a `new PIXI.TextStyle()`

```javascript
const txt = new PIXI.Text("myText");
txt.style.fontSize = 100;
```

**Comment by bigtimebuddy** [comment]
Can you please show a visual example of what you want to do? “width and height to be automatic” does not make sense to me. Whenever you set the text or change the font size, text is redrawn at the new size. Do you wan to constrain the text to automatically adjust the fontSize to fill and area?

**Comment by bigtimebuddy** [comment]
Ahhh, I think I understand. The default behavior of Text is to automatically adjust the width and height. After you manually set width or height, you want to use to the automatically resizing behavior but there's no clear way how to do this through the API.

Any thoughts @themoonrat?

http://jsfiddle.net/kvy3bj2h/28/

```js
const app = new PIXI.Application(300, 300);
document.body.appendChild(app.view);
const txt = new PIXI.Text('short', {
	fill: 0xffffff
});
txt.width = app.screen.width;
txt.height = app.screen.height;
txt.scale.set(1);
txt.text = "blah blah blah long";
app.stage.addChild(txt);
```
### Expected
![image](https://user-images.githubusercontent.com/864393/44420066-c90f3e00-a531-11e8-8df7-f2ca43e34088.png)

### Actual
![image](https://user-images.githubusercontent.com/864393/44420049-bd237c00-a531-11e8-998a-7bb9cc177d27.png)

**Comment by themoonrat** [comment]
@bigtimebuddy That's just how all of PIXI sprites work, not just text.

add this just after the bunny sprite is created on https://pixijs.io/examples/#/basics/basic.js

```
bunny.width = app.screen.width;
bunny.height = app.screen.height;

bunny.scale.set(1);
```

You'll see the exact same thing. Once a sprite's width or height has been set manually (giving values to internal `_width` and `_height` properties) you can never then 'unset' them.

**Comment by BH-NOTHING** [comment]
Ok,maybe I should try other ways to realize the demand,thanks both.

**Comment by TheSzRaPnEL** [comment]
while(txtF.width>maxWidth) txtF.style.fontSize--;

**Comment by biblekiss** [comment]
you have to use the main width and Height of the element
```
demoText.x=w/2
demoText.y=h/2
var fx=demoText.width/demoText.height

demoText.width =w
demoText.height =w/fx
```

https://jsfiddle.net/eq9paxob/2/
