### ISSUE TITLE
Some UI Questions.

### ISSUE THREAD

**Issue by yuriilychak** [pixijs/pixi.js#5080]
Hi. I try to migrate from Cocos2d-JS to PIXI.js and have few questions about UI generation:

- Is it any way to avoid breaking batch when use PIXI.mesh.NineSlicePlane, cause every new slice-9 element generate new draw-call, or better write my own that use 9 sprites?
- I know that PIXI.js use multi-texture sprite batch. Does this apply to bitmap fonts? And how many textures can batch in same time? For example for UI I use one texture atlas for all buttons, panels and etc, and 3 atlases for fonts (for example 60, 30, 15 pt to avoid artifacts). In cocos for render all UI in one draw-call I need to merge all fonts and UI to one atlas. Do I need to do this on PIXI? For example if I create game window with 200 elements that contains frames from 8 different atlases, do I have 1 draw-call or near 50 (In edition that they all use same vertex and fragment shader).
The main problem of merging UI with font is localization. When I pack Latin and Cyrillic letters it's OK, but I think for Japanese and Arabian i don't have space in atlas (If manager want to localize to this languages).
Example of Cocos2d-JS atlas.
![ui](https://user-images.githubusercontent.com/8695823/44310439-00210a80-a3df-11e8-8fc7-5f6e747cddf6.png)

**Comment by themoonrat** [comment]
Regarding 2
* Yes, it applies to bitmap text. Bitmap text class is a container that automatically adjust child sprites :)
* The amount of textures that can be batched depends on the hardware. On mobile, it's hardcoded to be just 4 atm (we really should change that), and on desktop, it depends on the hardware. It's obtained via querying the gl context via `MAX_TEXTURE_IMAGE_UNITS`. You can see the values for hardware via visiting http://webglreport.com/
* The rules for batching are the same. https://chrome.google.com/webstore/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk?hl=en is a very useful plugin to be able to record the number of WebGL calls being made within a scene
* This is an issue. pixi-ui repo has dynamicly atlassed text... so it will build up the atlas with characters as they are required. Might be something worth taking a look at and adapting? https://github.com/pixijs/pixi-ui/tree/master/src/DynamicText

**Comment by loohoo** [comment]
try this ui framework [https://jc-space.com/pixigui/](url)

**Comment by yuriilychak** [comment]
@loohoo. Try to open it with Spector or WebGL inspector and you see 422 draw-call's. The main problem for me in PIXI UI, that UI frameworks (EZGUI, Gown and etc.) generate more draw-call's that other part of game. I write my own solution that merge bitmap font's and SpriteFrames to one big atlas and generate slice 9 via sprites, as result I have only one draw-call (If not use clipping) for all UI elements that use same atlas.

**Comment by bigtimebuddy** [comment]
Regarding 1: in v4 only sprites are batched. In the upcoming v5 release meshes and graphics (which have simple-ish geometries) are also batched, in addition to sprites.

**Comment by yuriilychak** [comment]
@bigtimebuddy what do you mean by "simple-ish geometries"? It means that in 5 version I can batch spine mesh animation with other sprites, or create [polygon sprites](https://www.codeandweb.com/texturepacker/tutorials/cocos2d-x-performance-optimization), or both. Cause second is very useful, mostly for isometrics.

**Comment by bigtimebuddy** [comment]
We are setting a limit on the complexity of the geometries that can be batched for performance reasons. For instance, meshes or graphics with 100 or fewer vertices.

**Comment by yuriilychak** [comment]
> We are setting a limit on the complexity of the geometries that can be batched for performance reasons. For instance, meshes or graphics with 100 or fewer vertices.
I do not mean the number of vertices (cause you always can divide one sprite to two different), but the opportunities of a geometric and fragmentary shader. Will the sprites (if there are polygonal) be available  skew transform or dynamic editing of vertex positions, or it brake batch?
