### ISSUE TITLE
Generated texture cropped in iOS only

### ISSUE THREAD

**Issue by FNevesFMQ** [pixijs/pixi.js#5087]
Hello!

In my app, I'm building a container with lot of assets (balls with numbers inside) and save their positions and dimensions to use later, then I save a texture of it using _.generateTexture()_ on this container.

Then for each ball I use this generated texture and apply a frame with position and dimensions saved before, like: _**new PIXI.Texture (baseTexture, frame)**_

On any desktop, everything works fine.
On any android, same thing, all good.
But on iOS, some assets get cropped.

Here is the generated texture, with all numbered balls, that is equal on all platforms:
![ios_atlas](https://user-images.githubusercontent.com/7628846/44536771-1a1b5f80-a6f5-11e8-8a2f-21766421d28c.PNG)

Now let's take a look on how ball with 22 is, after generate texture with frame.

On android and desktop:
![android_ball_ok](https://user-images.githubusercontent.com/7628846/44536885-5b137400-a6f5-11e8-8620-448e2ccdf2f1.png)

And on iOS:
![ios_ball_cropped](https://user-images.githubusercontent.com/7628846/44536893-6070be80-a6f5-11e8-8c6d-3dc14f429024.PNG)

As you can see, on the right side it seems cropped. This occurs everytime I load the webpage, always with the same asset (in this case, the ball with 22, and also occurs with some other balls). But if I changed the balls position on original container, before generate texture, 22 probably will be ok but others don't.

Any clue why this happens?

**Comment by themoonrat** [comment]
@FNevesFMQ Does this happen with both Canvas and WebGL renderers?

**Comment by FNevesFMQ** [comment]
No, only in WebGL!

**Comment by wilcobrouwer** [comment]
@FNevesFMQ is it just me or is the ball in the android/desktop screenshot cut off on its left side instead of on its right side?

**Comment by FNevesFMQ** [comment]
@wilcobrouwer hmm, yes, with the zoomed version it really seems.. but with original sizes I don't have that perception.
This occurrences are clearly evident on iOS.

**Comment by FNevesFMQ** [comment]
Any clue?

**Comment by FNevesFMQ** [comment]
After searching in other places I found this thread: http://www.html5gamedevs.com/topic/40684-pixi-v4-textures-from-atlas-cropped-with-webgl-on-ios/

Where the solution given was setting this:
`PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH`

And it worked!

**Comment by themoonrat** [comment]
Thanks very much for letting us know the solution after this time! We've set precision to high by default for ios on v5 since there were a number of other issues solved by that, like wobbly animations. Glad to know that it will also cover this scenario too
