### ISSUE TITLE
Focusing by clicking the canvas, while hovering a sprite, stops the hover interaction until the pointer is moved.

### ISSUE THREAD

**Issue by wilcobrouwer** [pixijs/pixi.js#5092]
### Expected Behavior
The hover interaction is never lost, if the pointer hovers a sprite.

### Current Behavior
Focusing by clicking the canvas, while hovering a sprite, stops the hover interaction until the pointer is moved.

### Possible Solution
Setting `renderer.plugins.interaction.mouseOverRenderer = true;` on focus of the canvas used by the renderer.

### Steps to Reproduce
- Create a PIXI.Application/PIXI.WebGLRenderer.
- Render an interactive sprite. 
- Somehow lose focus of the view canvas, or don't have it in the first place.
- Focus by clicking while hovering the interactive sprite

### Environment
- `pixi.js` version: 4.8.1
- Browser: any recent browser
- Device: Desktop

**Comment by themoonrat** [comment]
Hi @wilcobrouwer 
Would it be possible to create a quick fiddle for this please to demonstrate, then I'll get on to take a look :)

**Comment by djmisterjon** [comment]
i don't have this issue, if a turn false **rendering** and **visible** a sprite was hover another and my mouse are hover those!, the sprite below will executed hover event.
Like _themoonrat_ say a fiddle can't help, but on my side i don't have this issue.

**Comment by wilcobrouwer** [comment]
@themoonrat I'm not sure of how to include the latest version of Pixi in a fiddle, could you point me toward a good approach of doing so? Fiddle.js appears to just offer Pixi 3.x and Pixi 4.0.0 out of the box.

**Comment by englercj** [comment]
Use `https://pixijs.download/release/pixi.js` as the url for an external resource.
