### ISSUE TITLE
Changes to PIXI.RenderTexture.frame not corretly updating RenderTexture

### ISSUE THREAD

**Issue by uberhalit** [pixijs/pixi.js#5098]
### Expected Behavior
According to docs one can move around the section a RenderTexture cuts out of its BaseTexture with `.frame`. So when I have a 1024x1024 BaseTexture and my RenderTexture is 512x512 I'll see the upper left quarter. With setting `frame.x = 512` one should see the upper right quarter of the image.

### Current Behavior
The texture is limited to the initial 512x512 pixel, "moving" the seeable window around using `frame` does not update the image, but "smears" it's corner pixel around. Calling `_updateUvs()` will sometimes break the texture, darken it or fall back to a static, smeared version of the texture. Changing `frame` outside of render loop shows that the original texture won't get removed, but the new "moved" one gets drawn on top of it.

### Possible Solution
1. A call to `_updateUvs()` should clear the old texture before redrawing. 
2. The section of the base texture of which RenderTexture copies its texture out must be moveable, so the texture has to be re-initialized with the new set section.

### Steps to Reproduce
I've made a minimum example in the style of the official pixi examples: https://codepen.io/anon/pen/gdgJmY?editors=0010

In case the image won't load one can use any other 200x200px test picture.

### Environment

- `pixi.js` version: _4.8.1_
- Browser: _Opera 54, Firefox 60_ 
- Device: _Desktop, Mobile_

**Comment by ivanpopelyshev** [comment]
I think you mistook how RenderTexture works. Line 14 - you render 100x100 pixels. line 21 - you move the window out of those 100 pixels.

**Comment by uberhalit** [comment]
According to docs:

> _The frame specifies the region of the base texture that this texture uses. Please call_ __updateUvs() after you **change coordinates** of frame manually._

It clearly states that one can move this window. Whats the point of frame in the first place if you are not able to do so?
