### ISSUE TITLE
Setting sprite width/height to negative value causes scale to become positive.

### ISSUE THREAD

**Issue by Robbss** [pixijs/pixi.js#5102]
When setting a Sprites width or height to a negative value, it causes the scale to become positive if scale is already negative.

### Expected Behavior

Assuming a sprite's texture is 200px wide:

`sprite.width = -200;`

Should produce:

`sprite.scale.x === -1`

### Current Behavior

Assuming a sprite's texture is 200px wide, and the current scale.x is negative:

`sprite.width = -200;`

Produces: 

`sprite.scale.x === 1`

An example is available at https://codepen.io/robbss/pen/jvLZoE

### Possible Solution
```
set width(value) // eslint-disable-line require-jsdoc
{
    const s = sign(this.scale.x) || 1;

    this.scale.x = s * value / this._texture.orig.width;
    this._width = value;
}
```
The method implementation at [pixi.js/core/sprites/Sprite.js](https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L519) explains why this happens.

### Environment

- `pixi.js` version: 4.8.2
- Browser: any
- Device: any

**Comment by djmisterjon** [comment]
I had talked about this on slack with some dev, and it would seem like it's normal and expected behavior.

> The getter height alway return positive value.

You should never set a negative width,height.
