### ISSUE TITLE
25920x1920 canvas becomes stretched

### ISSUE THREAD

**Issue by Nowayz** [pixijs/pixi.js#5103]
### Expected Behavior
25920x1920 canvas with normal coordinates.

### Current Behavior
A canvas which is 25920 pixels wide and 1920 pixels high does create a canvas but for some reason it is stretched (larger) and translated slightly so y = 0 is higher than it should be.

### Environment
- `pixi.js` version: PixiJS 4.8.2
- Browser: _e.g. Chrome 68

**Comment by themoonrat** [comment]
I very much doubt that your, or any, hardware will be able to deal correctly with a canvas that size. My 1070 for example only supports 16384x16384

**Comment by djmisterjon** [comment]
it your approach are maybe not good
I try on my side with gtx 1070, and work fine.
**width 26 779 pixel.**

![image](https://user-images.githubusercontent.com/24865815/46259345-42416f80-c4a6-11e8-98aa-4c8a3c985976.png)

i tray hack to check if is true

```javascript
    ContainerBG.prototype.createBases = function(dataBase, dataValues) {
        // TODO: les bg pourrai etre parfoi decouper en arrays dans textures packer 
        const td = dataBase.textures || PIXI.Texture.EMPTY; // ref texture:diffuse
        const tn = dataBase.textures_n || PIXI.Texture.EMPTY; // ref texture:normal
        const d = new PIXI.Sprite(td);
        const n = new PIXI.Sprite(tn);
        this.Sprites = {d,n};
        this.addChild(d,n);
        // hack, let try isane stage on (3826*3004) * 6 +[diffuse,normal]
        for (let i=0, l=6; i<l; i++) {
            const dd = new PIXI.Sprite(td);
            const nn = new PIXI.Sprite(tn);
            dd.position.x = 3826*(i+1);
            this.addChild(dd,nn);
        };
    };
```
So you can easily pack texture with texturePacker, don't exceed the limit @themoonrat tell you and compute your Stage with multiPack **(pro feature from texturePacker)**
in my example my map are **(3826*3004)  * 6 + * 2[diffuse,normal]**
