### ISSUE TITLE
[BUG] Merged sprites (safari)

### ISSUE THREAD

**Issue by martinboksa** [pixijs/pixi.js#5104]
Hello Pixi,

please, have you met a problem of double(triple, ...) safari textures? I used PIXI.loader to preload svg textures. After that i added them to stage. Some of them Safari wanna merge together. Check images below.

https://codepen.io/bokos/pen/LJzNoz  

### Expected Behavior
Chrome, Firefox:
![screen shot 2018-09-06 at 14 08 22](https://user-images.githubusercontent.com/4490694/45156517-bc9c0e00-b1de-11e8-9203-601275515eac.png)

### Current Behavior
Safari:
![screen shot 2018-09-06 at 14 08 07](https://user-images.githubusercontent.com/4490694/45156514-bb6ae100-b1de-11e8-9191-024ea5d17e7f.png)

### Steps to Reproduce

- run [this](https://codepen.io/bokos/pen/LJzNoz) on safari :)

### Environment
- Browser: Safari 11.1.2
- Device: Mac

// i found similar issue [here](https://github.com/pixijs/pixi.js/issues/3433)

**Comment by Bokos-** [comment]
Do you have any idea where is that problem? 

Temporarily fix for Safari.

```javascript
import { Texture } from "pixi.js";
import config from "../../config";

const svgExtensions = ["svg+xml", "svg"];

export function svgLoader(resource, next) {
  if (!svgExtensions.includes(resource.extension)) {
    next();
    return;
  }

  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  const image = new Image();

  image.addEventListener("load", () => {
    const width = image.width * config.pixelRatio;
    const height = image.height * config.pixelRatio;

    canvas.width = width;
    image.width = width;
    canvas.height = height;
    image.height = height;

    ctx.drawImage(image, 0, 0, image.width, image.height);

    // eslint-disable-next-line no-param-reassign
    resource.texture = Texture.fromCanvas(canvas);
    resource.complete();
    next();
  });

  image.addEventListener("error", () => next());

  image.crossOrigin = "anonymous";
  image.src = resource.url;
}
```
