### ISSUE TITLE
OffscreenCanvas support

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi.js#5105]
As you may already know, there is a specification for [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) which allows rendering (game loop) in a separate thread and also updating the canvas data on the page without triggering composition. This API was already introduced in the latest Chrome version (v.69).

Are there any plans for integrating PIXI with this new API? I think it would lead to a big performance improvements in most cases. By integrating it I mean making sure PIXI can run in a separate Worker (including assets loading) and maybe provide a few examples on how this can be used in order to take advantage of OffscreenCanvas.

**Comment by Cristy94** [comment]
Did you link to my own issue? :smile:

**Comment by Cristy94** [comment]
Nevermind, I failed when initial searching for open issues. I found the other ones, will close this one.

**Comment by themoonrat** [comment]
haha link fail! sorry dude
