### ISSUE TITLE
Sprite sizing when increasing the size of the texture's frame

### ISSUE THREAD

**Issue by SamStonehouse** [pixijs/pixi.js#5110]
Currently when I create a sprite, I sometimes want to increase the resolution of the sprite on the fly. To do that I update the Sprite's texture BaseTexture to a higher resolution image and then update the texture's frame to cover the new texture.

This causes the current sprites to increase in size.

Note: There's maybe another bug regarding updating a textures base texture, if I do not update the Textures frame then it seems to not update the Sprite size but still updates and shows the full resolution (which seems to me that it isn't always correctly respecting the textures frame).

### Expected Behavior

When setting a sprites size by height and width (instead of scale) it should always be that height and width.

### Current Behavior

When changing the sprites texture, updating the texture frame changes the size of the sprite

### Possible Solution

If height and width are used to set a sprites dimensions, update the scale property when the texture frame is changed

### Environment

- `pixi.js` version: 4.5.1

**Comment by englercj** [comment]
Are you changing the frame, or are you changing the width/height? In PixiJS, `width` and `height` are just setters/getters of `scale`. There is no concept of "set this object to be X pixels wide", instead it is "set the scale to be a value that will make it X pixels wide *right now*".

If you want to adjust the sprite to have a specific width/height after the frame has changed, you will need to manually set width/height again.

**Comment by SamStonehouse** [comment]
I understand that's how it works now and that's how I currently use it, by rescaling once a texture has changed, which means that this may be more of a feature request than a bug report.

But given I am specifying the width and height of a sprite, I think it would be sensible to enforce those dimensions as that's what I would expect as a user, and automatically rescale if a height or width is set.

Is this is an unreasonable expectation/out of the scope of PIXI?

**Comment by bigtimebuddy** [comment]
@SamStonehouse thanks for the feature suggestion.

I'm not sure I fully understand your use-case. You want to change the resolution of a Sprite on-the-fly? Could you explain why you'd want to do this? There are other paths in PixiJS to achieve the same thing and locking the width and height is a little counter to how the library currently handles sprites, as @englercj explained well above.

Another approach you might want to try is extending `PIXI.Sprite` and add or override APIs to set the a bounded width and height.

Personally, I think the suggestion is slightly out of scope of Pixi, but would love to hear what other folks think. If there's enthusiasm for a feature, we will consider.

**Comment by SamStonehouse** [comment]
My use case is as follows:

- I have lots of the same sprites on the screen, at different (scalable) sizes, but they all use the same texture
- My sprites are generated from SVG's, so when a new bigger sprite comes in I regenerate the texture so it's the size of the largest sprite (so it looks like it's a normal resolution)
- I then re-scale all my other already existing sprites to not enlarge with the new texture dimensions

But I've already specified what width and height I want them to be in pixels and it makes sense to me that if I set the width and height then I don't expect it to be dependent on the texture size changing.

Extending the PIXI.Sprite is maybe an option, is there methods available to listen for a texture changing size or frame?

**Comment by bigtimebuddy** [comment]
BaseTexture has an `update` [event](https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/BaseTexture.js#L272). You could also emit your own event on Texture or BaseTexture that your Sprite instances listen to and automatically react to.

**Comment by SamStonehouse** [comment]
I've spent a day looking at this and I definitely feel the current way doesn't work the way it's supposed to.

If I change the sprites texture then it obeys the height and width which is already set (and rescales automatically). However the same behavior does not happen when changing the current textures base texture (as described above).

But it does seem that updating the baseTexture of a Texture isn't handled that well? (or at all?)

Since that it doesn't re-apply some some BaseTexture listeners in Texture, it only applies them on initialisation, such as:

`baseTexture.on('update', this.onBaseTextureUpdated, this);`

Am I abusing PIXI by changing a textures base texture or is this just part of the API which hasn't been looked at in a while?

**Comment by bigtimebuddy** [comment]
Could you please provide a jsfiddle or codepen demonstrating what you're trying to do? Would be helpful to see a simple example.

**Comment by englercj** [comment]
(or a playground: https://pixiplayground.com/#/edit) 😄

**Comment by SamStonehouse** [comment]
This is the gist of what I'm trying to do: https://pixiplayground.com/#/edit/6O5VSa8ll5lLTR~xVzqF0

At the bottom I have a timeout which does the change I'm intending to do after 1 second.

I've also included an example which works by creating a new texture, rather than updating the current texture's base texture. (Something I don't wish to do as I don't control sprites in the area of code this operates, it's only concern is updating textures).

**Comment by bigtimebuddy** [comment]
If you create a texture from a canvas and then redraw you can called `update` on the baseTexture. For instance:
https://pixiplayground.com/#/edit/UTNuXvJ1r3KxtI_WV_7cf

**Comment by SamStonehouse** [comment]
You're still resetting the sprite height and width once changing the base texture that way which is what I'm trying to avoid. I don't have any sprite code near my texture engine due to separation of concerns, so I'd still like to know whether re-assigning a baseTexture is wrong? Or is it supposed to work similar to just setting a texture in which case there's a small bug which I think can be fixed by adding a baseTexture getter and setter.

That or make the Texture baseTexture property read only and updating the docs so it's clear you're not supposed to do that?

**Comment by bigtimebuddy** [comment]
Reassigning a baseTexture isn't necessarily _wrong_ but it's probably safe to say this is an antipattern. It's more common to swap Texture object between Sprite objects than it probably is to swap BaseTextures between Texture objects.

**Comment by SamStonehouse** [comment]
I'd agree if it was the case that I was using this to actively change the texture of a sprite, but I'm just updating the texture with a new resolution, which I want to do for all sprites in the scene, which use the same texture; this could be hundreds.

Using the same texture and updating the base texture once makes much more sense to me.

I'm definitely not saying that this should be the way to swap a sprites texture, just a way to update a texture.

Do you mind if I create a PR with better support for changing base textures?

**Comment by themoonrat** [comment]
Closing this as I believe the question has been answered :)
