### ISSUE TITLE
WebGLRenderer does not handle alpha properly.

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#5114]
As I wrote in #2695 
 
```
class Layer extends PIXI.Sprite {
    constructor(opts) {
        super(PIXI.RenderTexture.create(opts.texture.width, opts.texture.height));

        RENDERER.render(new PIXI.Sprite(opts.texture), this.texture, false, null, false);
   }
   toBase64() {
        return RENDERER.extract.canvas(this, null, true).toDataURL();
    }
}
```
My class loads drawings with alphas saved to base64 everytime. Every render makes the alpha look darker, until it looks almost black. For me saving to base64 does not affect (or very little to be seen), saved image looks the same, however re-rendering again make it looks worse.

How can I avoid premultiplied?

**Comment by themoonrat** [comment]
Would it be possible to create a jsfiddle or pixiplayground example for this please? Thanks!

**Comment by ivanpopelyshev** [comment]
@DavidGOrtega Why dont you use the workaround i posted in the old issue?

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev Thanks for the reply, sorry for my delay.

I have tried it, howwever it does not work, I can see any improvement.
In the mean time I have done a hack. I set a white background and it works, no more alphas getting dark. It's not ideal.

@themoonrat 
Yes! My app which is a painting app is very complex. However I will try to minimise the example give me a couple of days

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev  I will thanks
