### ISSUE TITLE
怎么让pixi所有精灵的坐标的是整型而不是浮点型啊 不知道有没有什么参数

### ISSUE THREAD

**Issue by yinhui1129754** [pixijs/pixi.js#5115]
Your issue may already be reported! Please search [existing issues](../) before creating one.

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by englercj** [comment]
@finscn Do you think you could help this person out? Not sure you speak the same language, but you're the most likely of any of us to break the language barrier.

**Comment by finscn** [comment]
@yinhui1129754  , 这个目前没有参数 以后也不会有.  需要自己处理下.

**Comment by yinhui1129754** [comment]
好的
