### ISSUE TITLE
pixijs 在苹果手机上面的微信浏览器里面用loader无法加载音频文件

### ISSUE THREAD

**Issue by yinhui1129754** [pixijs/pixi.js#5116]
Your issue may already be reported! Please search [existing issues](../) before creating one.

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by englercj** [comment]
@finscn Do you think you could help this person out? Not sure you speak the same language, but you're the most likely of any of us to break the language barrier.

**Comment by finscn** [comment]
这个需要你提供更多细节.  比如 代码和音乐文件.

**Comment by yinhui1129754** [comment]
我解决了

**Comment by yinhui1129754** [comment]
我用的是自己写的加载音频的方法

**Comment by yinhui1129754** [comment]
还有一个问题 用pixi在不播放音乐文件的时候一点都不卡 非常流畅 但是我在加入音乐文件过后 游戏就变的有点卡了 我是用的audio标签做的音乐播放没有用audioAPI来处理音乐文件
