### ISSUE TITLE
How can i make specific zones from a background image to react on click?

### ISSUE THREAD

**Issue by tifDev** [pixijs/pixi.js#5117]
Here is the image https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi0V5nPBik3OrZ77kkKsE4Eb6GXz_iKxz5qhgDCT4sGPZ_bnm1

As you can see, its a map, and this will be the background image of the canvas. Now i need to get which city was clicked and also an effect when the city is clicked to highlight the clicked one. Currently im thinking about using the outline effect to highlight the clicked one and creating a "clickable" sprite for each city but this is just "impossible"! Drawing a sprite with the same shape of each city is very difficult. Any tip or workaround for doing this?

**Comment by englercj** [comment]
Use `PIXI.Graphics` to draw polygons :)

**Comment by englercj** [comment]
Sure, here is a random interactive graphics shape I drew:

https://www.pixiplayground.com/#/edit/DhEmfnbdJfRNiEltQEjdw

**Comment by tifDev** [comment]
Cool but how did you draw that? 
Where did you get all this points:
```
shape.drawPolygon([
    -0.884, 4.248,   0.458, 3.830,
     0.458, 3.830,   1.602, 2.730,
     1.602, 2.730,   1.646, 0.948,
     1.646, 0.948,   0.370, 0.420,
     0.370, 0.420,   0.700,-2.418,
     0.700,-2.418,   0.964,-4.354,
     0.964,-4.354,  -0.862,-4.596,
    -0.862,-4.596,  -2.600,-3.738,
    -2.600,-3.738,  -1.412,-1.978,
    -1.412,-1.978,  -0.774, 0.134,
    -0.774, 0.134,  -2.468, 1.190,
    -2.468, 1.190,  -3.634, 2.818,
    -3.634, 2.818,  -0.488, 1.652,
    -0.488, 1.652,  -0.884, 4.248,
]);
```

Any tool that one can draw and then automatically retrieves the points of the shape drawn?

**Comment by englercj** [comment]
I found a few by googling "polygon drawing app" which is how I made that random shape. How you get the points for an image is up to you, pixi doesn't help.
