### ISSUE TITLE
PIXI  gl function null

### ISSUE THREAD

**Issue by zhu106878723** [pixijs/pixi.js#5118]
_this.state = new _WebGLState2.default(_this.gl);

this.gl all function is notfound

**Comment by englercj** [comment]
Need more context, can you create a running example that we can look at?

**Comment by zhu106878723** [comment]
This problem is appearing on the WeChat mini-game platform, which can provide actual cases, but it requires complicated registration platform procedures before it can run, and it requires a real machine to report an error. An error is not a 100% error.

**Comment by zhu106878723** [comment]
https://pan.baidu.com/s/1t5BMOpcosy0T4jsOROdgjQ

**Comment by zhu106878723** [comment]
![2](https://user-images.githubusercontent.com/10559048/45603484-eff05f80-ba5e-11e8-8c64-1ee56dbe68ae.jpg)
![1](https://user-images.githubusercontent.com/10559048/45603490-f67ed700-ba5e-11e8-83e7-fd0b03377dac.jpg)

**Comment by zhu106878723** [comment]
frist image is ihone X, tow image  is iphone 6

**Comment by zhu106878723** [comment]
[DEMO.zip](https://github.com/pixijs/pixi.js/files/2387224/DEMO.zip)

**Comment by LIU9293** [comment]
@zhu106878723 Same issue, my error is `e.disable is not a function`, please give some help if you find any clue about it.

**Comment by englercj** [comment]
@finscn You are the only one I know with WeChat browser experience. Is this something you've encountered?

**Comment by finscn** [comment]
I've used pixi to develop some wechat tiny games.

@zhu106878723 ,  @LIU9293  ,  There are 2 suggestions : 

1) use my weapp-adapter:  https://github.com/finscn/weapp-adapter
Some persons in tencent/wechat core team help me for this project, so it's better than the default weapp-adapter.

2) use my forked pixi : https://github.com/finscn/pixi.js

some issues have been forgotten in  official pixi and  pixi-gl-core  ( like this : https://github.com/pixijs/pixi-gl-core/issues/38 )

**Comment by themoonrat** [comment]
Closing as according to finscn this is an issue with the WeChat mini-game platform rather than PIXI
