### ISSUE TITLE
Preloading Video code not working.

### ISSUE THREAD

**Issue by joseph-olivemultimedia** [pixijs/pixi.js#5119]
```js
PIXI.loader
	.add("VideoKW", "assets/Video/BWvideo.mp4")	
	.on("progress", loadProgressHandler)
	.load(delay_gotogame);	

function loadProgressHandler(loader, resources)
{
	//Display the percentage of files currently loaded
	load_percentage = Math.round(loader.progress);
	preloaderPercentageText.text=load_percentage + "%";				
}

function delay_gotogame()
{	
	var videoData = resources['VideoKW'].data
	videoTexture = PIXI.Texture.fromVideo(videoData)					
	videoSprite = new PIXI.Sprite(videoTexture);			 
}
```

video is ~35MB, it freezes. Please help me with the correct code for loading the video.

**Comment by djmisterjon** [comment]
this issue come from the autoplay, i was get the same issue with freeze at first!~~5 frames.
see the fix https://github.com/pixijs/pixi.js/pull/5128
If i understand you talk about the video are fully loaded but when play, it freeze.
Remove autoplay and manually play was fixed the freeze for me.
Did you try ?

**Comment by djmisterjon** [comment]
this is how i code my video on my side if this can also help you.

```javascript
Scene_IntroVideo.prototype.create_IntroVideo = function() {
    const texture = PIXI.Texture.fromVideo('data2/Video/intro/vidA1.webm');
    const videoSprite = new PIXI.Sprite(texture);
    const videoControler = texture.baseTexture.source;

    videoSprite.width = 1920;
    videoSprite.height = 1080;

    videoControler.currentTime = 12.2;
    videoControler.onended = function(){
        this.nextVideo();
    }.bind(this);

    this.addChild(videoSprite);
    this.videoControler = videoControler;
};

Scene_IntroVideo.prototype.isReady = function() {
    // check scene stabilisator // TODO:
   return !this.wait--;
};

Scene_IntroVideo.prototype.start = function() {
    Scene_Base.prototype.start.call(this);
    this.videoControler.play();
};
```

**Comment by joseph-olivemultimedia** [comment]
Ok, will check and let u know. Thank you for the help.

**Comment by skizzo** [comment]
`.fromVideo` doesn't seem to exist in v5, how would this work in this latest version?

**Comment by themoonrat** [comment]
you can just use `.from` - it handles any source type automatically

**Comment by skizzo** [comment]
Thanks! Any way to control playback, loop it, mute it?

**Comment by themoonrat** [comment]
`videoSprite.texture.baseTexture.source` gives you direct access to that video html element. So you can control it according to the docs at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by skizzo** [comment]
Splendid, thank you good sir.
