### ISSUE TITLE
Black screen in Samsung Internet app when using WebGL renderer.

### ISSUE THREAD

**Issue by qinxgee** [pixijs/pixi.js#5121]
- `pixi.js` version: 4.8.1
- Browser: Samsung Internet 7.4.00.70
- Device: Seen on at least Samsung Galaxy S5, S7, S8 and S9

Hi!

Are there known issues with using pixi.js in the Samsung Internet app?

We currently are facing an issue that does not appear on any other browser that we support (i.e. Safari, Chrome, Firefox). When starting our application, the first canvas item (a loading screen) is shown correctly. When loading is finished and the loader disappears, we're left with a black screen instead of our application. We have a CSS UI on top of the canvas that shows and functions correctly. The behaviour is not consistent: sometimes the application appears immediately, sometimes after a second or so, sometimes not for minutes. It seems that eventually, the application will always show. There does not seem to be a relation to caching: emptying the browser cache does not seem to change anything. 

When connecting Chrome to the mobile device as a debugger, we can see that the pixi WebGL renderer is initialised, and all our pixi containers are available. Their "visible" flags are all set to true, and although we cannot see anything, breakpoints seem to suggest that pixi-spine animations do run. 

There are no error or warning messages. Once the application appears, it works exactly as intended. When we force the pixi canvas renderer, we cannot reproduce the behaviour, so it looks like it is some combination somewhere of the Samsung Internet app, WebGL, pixi and pixi-spine.

Does this behaviour sound familiar to anyone? Since we do not know what causes it, I cannot give any information for reproducing. Our application is - compared to most of our other applications - pretty heavy on spine animations, but removing a bunch of them does not really seem to help.

**Comment by themoonrat** [comment]
Might be sorta related to https://github.com/pixijs/pixi.js/issues/4790
I too have found that some Samsung devices just 'crash' the browser with WebGL enabled. Sometimes :/

**Comment by qinxgee** [comment]
We've closed in on the source of the problem. With the 8.2 beta of the Samsung browser we get a warning:

`WARNING: Too many active WebGL contexts. Oldest context will be lost.`

when pixi tries to create a context in createContext.js.

This happens when we are trying to add canvases to a CSS element for the game rules. And sure enough, when we remove the rules from the game, everything works.

So it seems that there is a memory issue introduced in version 7.4 of the Samsung browser. We've now fixed the game rules (by forcing canvas rendering - it does not seem to affect the animations in the game rules so much) and will be on our merry way :-)

**Comment by rich-earth** [comment]
Have you tried changing some renderer settings,  like any of the following? :

PIXI.settings.CAN_UPLOAD_SAME_BUFFER = false;
renderer options : preserveDrawingBuffer = true; 
renderer options : legacy = true

**Comment by qinxgee** [comment]
@rich-earth We messed about with the preserveDrawingBuffer because that resolved issues on devices using a specific GPU, but it didn't help with this issue. The other settings you mention do not make any (observable) difference either. I'm afraid the Samsung Browser is just buggy (seeing how they added a warning in the beta rather than solving the issue)
