### ISSUE TITLE
renderer.generateTexture() doesn't capture the main Sprite

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#5125]
In the above example, I use `renderer.generateTexture` to showcase various poses of a Sprite, the actual Sprite is the body, the head and the hat is children, `renderer.generateTexture` only captures the children, also, the resulting texture has weird dimensions but I didn't dive into it that issue yet

<img width="308" alt="screen shot 2018-09-21 at 17 14 50" src="https://user-images.githubusercontent.com/170243/45886578-27923b00-bdc2-11e8-92a5-92229e5e691d.png">

- `pixi.js` version: 4.8.2
- Browser: Chrome Latest
- Device: Macos
- Plugins: All disabled (no layers or display : )

**Comment by englercj** [comment]
Can you build an example [playground](https://www.pixiplayground.com/#/edit)? Looking at the code, this shouldn't be happening as far as I can tell.

**Comment by kaansoral** [comment]
Couldn't replicate, best I could do is this: https://www.pixiplayground.com/#/edit/Bl3h4KNg4qxgtXCL6RNPZ

You can also add `bunny.scale=new PIXI.Point(2,2);` - and messes things further, which makes me think whether the body was pushed down by this anomalies rather than went missing on my initial report

**Comment by kaansoral** [comment]
This issue really turned into an obsession for me - I've tested some old PIXI versions too, other browsers, the issue is persistent

I've tested it on NPC objects, rather than Character's in my game, NPC's work, there's almost no difference between NPC's and Characters, but obviously something on the Character entities causes the `renderer.generateTexture` to render the texture on the Character invisible, I even tried giving the same texture to an NPC, it's rendered there, so at this point, I'm just eliminating things one by one and hoping to reach the cause

<img width="804" alt="screen shot 2018-09-24 at 09 40 10" src="https://user-images.githubusercontent.com/170243/45940083-97c9d800-bfdf-11e8-9ce2-d4b8d59311d4.png">

FYI, `renderer.generateTexture(element,PIXI.SCALE_MODES.NEAREST,window.devicePixelRatio);` <- this was a must for me, it seems the scaleMode / ratio isn't adopted - it was the cause of the blur issues

**Comment by englercj** [comment]
Best thing that will help us track this down is a minimal repro case. :)

**Comment by kaansoral** [comment]
I couldn't reproduce it, in the end, it was easier to just re-create the Sprite rather than copying it with `generateTexture`
