### ISSUE TITLE
Draw Gradient color in Graphics

### ISSUE THREAD

**Issue by wrbing728** [pixijs/pixi.js#5131]
How can I fill graphics with a set of color to implement gradient effect.

**Comment by bigtimebuddy** [comment]
In the upcoming version of PixiJS v5, you'll be able to use a texture as a fills or lines with Graphics. This will make it much easier to support gradients. Example here:

https://jsfiddle.net/bigtimebuddy/Lu52dgmv/

We are unlikely to support in v4, so your best option there is to use SVG and render it to a canvas.

Hope that helps.

**Comment by bigtimebuddy** [comment]
Closing issue, as it seems the question was answered.
