### ISSUE TITLE
Rendering Mathematical Expressions in Pixi

### ISSUE THREAD

**Issue by ry-randall** [pixijs/pixi.js#5133]
Hello,

Thank you for all the great work that's done here. 

I thought I'd give back in some way for anyone who wants to render mathematical expressions (via LaTeX) in PIXI.

I created a library: https://github.com/CurriculumAssociates/canvas-latex where each mathematical symbol is rendered as a PIXI displayObject (text, graphic, etc.). This allows you to display math in your pixi application, manipulate specific parts of that math, etc. 

Great for anyone working in the ed-tech space.

Enjoy!

**Comment by englercj** [comment]
This is really cool @ry-randall, thanks for sharing.

I'm going to close this since it is not an issue or a question, feel free to cross-post on the [showcase topic](http://www.html5gamedevs.com/topic/494-pixijs-showcase/) in the forums.
