### ISSUE TITLE
Is there any way to load bitmap font files without ajax GET?

### ISSUE THREAD

**Issue by mezykr** [pixijs/pixi.js#5134]
Hi,

I need to create pixi component which will be used across few applications. I want to use BitmapText to generate text inside. 
Now first what I have to do is to load needed .fnt and .png by pixi.loader.add('name' , URL) bo be able to use my font. Pixi loader uses resource-loader to call ajax GET to specific resource. Is there any way to load needed files using something like `import fntFile` from '/some/file/location'` and `import pngFile` from '/some/file/location'` and next parse them to texture and cache to TextureCache ? 

Without that I will have to take care about needed .fnt and .png files to be served by each of my application which will be using my pixi component as dependency..

**Comment by bigtimebuddy** [comment]
I think what you’re looking for is http://pixijs.download/dev/docs/PIXI.extras.BitmapText.html#.registerFont

**Comment by mezykr** [comment]
yes! Thank you very much
