### ISSUE TITLE
[BUG] WebGLRenderer cannot draw BaseTexture correctly on Chrome v69

### ISSUE THREAD

**Issue by krmbn0576** [pixijs/pixi.js#5136]
Hi!
I am a committer of RPG Maker MV(Community).
RMMV failed to draw some sprites on Chrome v69, and this bug may be caused by Chrome or PIXI.
So, I wrote reproducible test case without RMMV.

Run https://codepen.io/krmbn0576/pen/aRbqor

![ss](https://user-images.githubusercontent.com/20380362/46206746-fc7a8f00-c35f-11e8-9d65-aec5ee2a8b87.png)

The left side canvas that uses WebGLRenderer, at first, displays a white rectangle on the upper left, but it disappears after several seconds. (**Actual Behaviour**)
The right side one that does not use WebGLRenderer, displays forever. (**Expected Behaviour**)

### Environment

- `pixi.js` version:  4.8.2 or less
- Browser:  Chrome 69
- Device: at least Windows7, Windows10, Mac OS, Android

**Comment by djmisterjon** [comment]
you maybe do something wrong in your code, my screen and gpu crashed and all my monitor turn black.

**Comment by krmbn0576** [comment]
Hmm
The below is all of codes.

```js
var renderer = new PIXI.WebGLRenderer(640, 480, { view: document.getElementById("main") }); // This renderer has bug
var app = new PIXI.Application({width: 640, height: 480});
document.body.appendChild(app.view); // This view has no bug
requestAnimationFrame(function tick() {
  var canvas = document.createElement("canvas");
  var context = canvas.getContext("2d");
  var baseTexture = new PIXI.BaseTexture(canvas);
  canvas.width = 640;
  canvas.height = 480;
  context.fillStyle = 'rgb(255, 255, 255)';
  context.fillRect(0, 0, 144, 144);
  baseTexture.update();
  var texture = new PIXI.Texture(baseTexture);
  var sprite = new PIXI.Sprite(texture);
  app.stage = new PIXI.Container();
  app.stage.addChild(sprite);
  renderer.render(app.stage);
  requestAnimationFrame(tick);
});
```

Am i use it the wrong way?

**Comment by themoonrat** [comment]
so, I'm not seeing an error in your original fiddle.
There's a huge chance that the reason things are going wrong your end is because you're creating a new canvas, a base texture, a new texture, a new sprite .... every single frame. Maybe your browser is (understandably) not liking this.

Here's a fiddle with things created once: https://codepen.io/anon/pen/XxJQNa
Does this work as expected for you?

**Comment by themoonrat** [comment]
Does that mean this can be closed? I think this is a case of 'you can't create loads of canvases and textures all the time because browsers don't like it'

**Comment by krmbn0576** [comment]
My code is terrible, but it works fine for older versions of Chrome and any other browsers.
Does pixi really do not deal with this?

Certainly, we hardly generate canvases and textures every frame.
Therefore, I changed my code as follows.

Before:

```js
requestAnimationFrame(...);
```

After:

```js
setInterval(..., 100);
```

This still causes a bug.

@djmisterjon 
I updated my code!
It will not crash your PC anymore.
Would you try again?

https://codepen.io/krmbn0576/pen/aRbqor

**Comment by kib357** [comment]
Hey guys! I have a similar problem with multiline PIXI.Text on Chrome 69/WebGL renderer. After 99 texts are created all next Text instances will be not visible. They have bounds, but don't render on screen.

**Comment by kib357** [comment]
This bug also reproduces when rect renders 100 times:
https://codepen.io/kib357/pen/YJpwYw
And all fine when 99:
https://codepen.io/kib357/pen/QZGyQQ

**Comment by kib357** [comment]
I've created an example with PIXI.Text only:
https://codepen.io/kib357/pen/yRVPgJ
With canvas renderer all fine after 100 render, and text is invisible for WebGL renderer:
![image](https://user-images.githubusercontent.com/347668/46600598-4c411f00-caf3-11e8-80b4-187f06143ab5.png)
