### ISSUE TITLE
renderer.plugins.extract.base64(stage) No longer works as expected in 4.8.2

### ISSUE THREAD

**Issue by Billydwilliams** [pixijs/pixi.js#5137]
### Expected Behavior
renderer.plugins.extract.base64(stage) no longer takes the x and y of the stage into account.
### Current Behavior
renderer.plugins.extract.base64(stage) extracts a stage sized square from 0,0

- `pixi.js` version: 4.8.2 (from 4.7.3)
- Browser: FireFox Nightly
- Device: Windows 10 Desktop

**Comment by themoonrat** [comment]
Would it be possible to create either a jsfiddle or a pixiplayground example for us please? Thanks!

**Comment by Billydwilliams** [comment]
I'll try to get one put together as soon as I can. Thanks!

**Comment by Billydwilliams** [comment]
using 4.7.3 build
https://jsfiddle.net/1y4Leg0q/

using 4.8.2
https://jsfiddle.net/9dompw25/1/

Clicking the square will open the generated image in a new tab.

**Comment by Billydwilliams** [comment]
using 4.7.3 build
https://jsfiddle.net/1y4Leg0q/1/

using 4.8.2
https://jsfiddle.net/9dompw25/1/

Clicking the square will open the generated image in a new tab.
