### ISSUE TITLE
Sprite with texture of PIXI.Text doesn't work without adding original Text.

### ISSUE THREAD

**Issue by edreal** [pixijs/pixi.js#5138]
```
var text = new PIXI.Text("HELLO");
app.stage.addChild(text); // Code below doesn't work without this.

var sprite = new PIXI.Sprite(text.texture);
sprite.position.x = 200;
app.stage.addChild(sprite);
```
I need to use same text on multiple positions with different scales. I assume its faster to use same texture rather than creating and adding new PIXI.Text everytime?

If I remove the line with a comment, neither of texts will show.
Please tell me if I am missing something.

PixiJS 4.8.1
Chrome 69

EDIT:
However, generateTexture seems to do the job.

**Comment by themoonrat** [comment]
Text only lazily updates it's texture as the object is being rendered. The reason being, if you were counting from 0 to 1000000 in 1 second... would you want the texture being updated 1000000 times? Or, in our case, just 60 times; only when it needs to update.

Now, you _can force_ an update for text, via `updateText` method

So in your example, do 

```

**Comment by edreal** [comment]
> Text only lazily updates it's texture as the object is being rendered. The reason being, if you were counting from 0 to 1000000 in 1 second... would you want the texture being updated 1000000 times? Or, in our case, just 60 times; only when it needs to update.
> 
> Now, you _can force_ an update for text, via `updateText` method
> 
> So in your example, do
> 
> ```
> var text = new PIXI.Text("HELLO");
> text.updateText();
> app.stage.addChild(text); // Code below doesn't work without this.
> 
> var sprite = new PIXI.Sprite(text.texture);
> sprite.position.x = 200;
> app.stage.addChild(sprite);
> ```

**Comment by edreal** [comment]
Does lazily update mean that it updates everytime when I change text?
