### ISSUE TITLE
Createjs to PIXIjs Conversion

### ISSUE THREAD

**Issue by joseph-olivemultimedia** [pixijs/pixi.js#5140]
used CREATEJS to develop a casino slot game and it started to behave slow on many devices. Because of this, I want to stop using createJS, but switch to pixiJS without deleting all the code and if someone did a similar conversion or what would be a list of best practices to use when doing this conversion or if there are any tools online that can do such conversion or if there is a migration tool for pixiJS, please let me know about it.

**Comment by bigtimebuddy** [comment]
You may want to check out a project @andrewstart and I had worked on several years ago called PixiFlash (https://github.com/CloudKidStudio/PixiFlash). This uses the CreateJS output from Flash/Animate and creates a bridge to PixiJS rendering. This project was abandoned, but maybe it's a starting point? Good luck.
