### ISSUE TITLE
Canvas Texture for Tizen 4.0 (latest version) broken on Smart TVs

### ISSUE THREAD

**Issue by EloB** [pixijs/pixi.js#5143]
Hello,

I'm developing smart tv apps using Pixi. I got a problem that canvas textures often ends up broken. This only happens in the latest Samsung Smart TVs Tizen 4.0 (2018) (it works good in older models) and only using the WEBGLRenderer. Right now I have to `forceCanvas` on the latest Samasung TVs because of that.

I'm pretty sure that something is bad with Canvas Textures because `PIXI.Text` and `Texture.fromCanvas` only have this problem.

https://developer.samsung.com/tv/develop/specifications/tv-model-groups/
https://developer.samsung.com/tv/develop/specifications/web-engine-specifications/

![image](https://user-images.githubusercontent.com/476567/46354548-259c6780-c65f-11e8-934b-e4f92fc2f2c2.png)

**Comment by EloB** [comment]
**A simple app with rendering errors on Samsung Smart tvs 2018 tizen 4.0 devices**
https://github.com/EloB/broken-app-tizen

It looks like the memory is not cleaned properly and it reuses old textures. I managed to get this output and as you can see from the code it isn't possible to have green background and "First time app started" in the end of the Lorem text.
 
![image](https://user-images.githubusercontent.com/476567/46362508-c21b3580-c670-11e8-8b4d-b5c0fdb98e76.png)

Sometimes it ends up right...
![Uploading image.png…]()

**Comment by themoonrat** [comment]
I can't say I've seen this occur on any devices or browsers I've supported before... (android, windows, ios, mac, windows) but I've never targeted Tizen!

The fact that it's not been seen before would lead me to think it's more likely a Browser bug not clearing the state of the window on a reload than anything wrong PIXI is doing....

The only thing vaguely similar are 
https://github.com/pixijs/pixi.js/issues/4405
https://github.com/pixijs/pixi.js/issues/4790
https://github.com/pixijs/pixi.js/issues/5121
https://github.com/pixijs/pixi.js/issues/5155

Times when, again, things have not worked on a Samsung browser compared to every other browser. They've a track record for this :/
