### ISSUE TITLE
Sprite rendering 1px offset with pivot and/or scale.

### ISSUE THREAD

**Issue by Rojoss** [pixijs/pixi.js#5145]
### Current Behavior
See image/Fiddle (https://jsfiddle.net/gr35oyfe/), on the top row the white squares have no pivot, on the bottom rows the white squares have the pivot centered.

BLUE: Negative scale pivot 0.5
GREEN: Positive scale pivot 0.5
ORANGE: Negative scale pivot 0
PURPLE: Positive scale pivot 0
TOP ROW: All white blocks have pivot 0.
BOTTOM ROW: All white blocks have pivot 0.5

**Image**: White square, 64*64px
**Scale mode**: Nearest but linear has same results.

As you can see here on the top row the blue and green squares are 1px offset on both x and y axis.
On the bottom row the blue and orange square are 1px offset on the x axis.

![image](https://user-images.githubusercontent.com/1093861/46542415-a311e300-c8be-11e8-9bd1-17a660f6e0b7.png)

### Expected Behavior
When scaling or setting the pivot of sprites the rendered position should not change.

### Steps to Reproduce
See fiddle: https://jsfiddle.net/gr35oyfe/

### Environment
- `pixi.js` version: 4.8.2
- Browser: Chrome 69

**Comment by bigtimebuddy** [comment]
https://jsfiddle.net/bigtimebuddy/pj6239bv/

Sprites have both `pivot` and `anchor`. I think you want the `anchor` (generally a float from 0 to 1) not `pivot` (absolute pixels).

**Comment by Rojoss** [comment]
> absolute pixels

Oh I really though pivot was also a float between 0 and 1.
That makes sense then since it would just offset the sprite by 0.5 pixels 😛
