### ISSUE TITLE
set hitarea  automatically

### ISSUE THREAD

**Issue by Hardcore0331** [pixijs/pixi.js#5146]
How to set hitarea automatically in the non-transparent area of a sprite?

- `pixi.js` version: _e.g. 4.8.1_

**Comment by angiagia** [comment]
You can set the hitarea of a sprite with a PIXI.Rectangle | PIXI.Circle | PIXI.Ellipse | PIXI.Polygon | PIXI.RoundedRectangle. 
Ex: 
const sprite = new PIXI.Sprite(texture);
sprite.interactive = true;
sprite.hitArea = new PIXI.Rectangle(0, 0, 100, 100);
Read more about it in: http://pixijs.download/dev/docs/PIXI.Sprite.html

**Comment by ivanpopelyshev** [comment]
Make a bitmap out of your image and override `containsPoint` method for the sprite. Unfortunately Bitmap class does not exists in pixi, so you have to learn how to implement it :)

**Comment by themoonrat** [comment]
Closing as I think there's some answers to help you!
