### ISSUE TITLE
addChild() performance with many sprites

### ISSUE THREAD

**Issue by edreal** [pixijs/pixi.js#5147]
When I use for loop to add bunch of new circles with .addChild, sprites are not rendered as quickly as the loop goes through. I also noticed that if I do:
> renderer.generateTexture(circle);

 for each circle beforehand, later when I use .addChild they will render immediately. Is that some kind of a caching system?

There might be 1000 different sprites on the screen at time and I need to remove and add them continuosly, what I could do to improve performance? I have heard about pooling and particle container could they be useful on this situation?

**Comment by edreal** [comment]
Does the first link use ParticleContainer, is it much faster than normal container?

**Comment by bigtimebuddy** [comment]
@edreal pixi-particles is a runtime for creating particle emitters, and the ParticleContainer is a core Container optimization for rendering a lot of the same textured Sprite. I believe pixi-particles utilizes ParticleContainer but it's a much bigger system for customizing emitters. Core PixiJS has no internal support for emitters.

**Comment by edreal** [comment]
@bigtimebuddy Okay! What particle emitter means, looks like it creates a lot of those tiny sprites?

**Comment by bigtimebuddy** [comment]
@edreal An emitter a bigger system for rendering Sprites which typically includes things like animation, physics or other dynamic properties. A ParticleContainer is just a static object, like PIXI.Container (but with a few restrictions).

**Comment by edreal** [comment]
@bigtimebuddy Ok, thank you and @angiagia you too for answering my questions and helping, this can be closed now :)
