### ISSUE TITLE
renderer always resorts to canvas even when webgl is supported

### ISSUE THREAD

**Issue by mhazaa** [pixijs/pixi.js#5154]
I'm setting a renderer with auto detect renderer

    let size = [1920, 1080];
    renderer = PIXI.autoDetectRenderer(size[0], size[1], null, {
        antialias: true,
        transparent: true,
        resolution: 1,
        autoResize:true
    });

and when I check for webgl support, it returns true (I'm using the latest version of chrome on mac)

     console.log(PIXI.utils.isWebGLSupported()); //true

But when I check which mode the renderer is using it console logs canvas

     if (renderer.type == PIXI.WEBGL_RENDERER){
        console.log('Using WebGL');
      } else {
        console.log('Using Canvas');
     };

I even tried force webgl, using new PIXI.WebGLRenderer, and it still returns canvas. Which I can also tell because my game is kinda laggy. Any ideas why PIXI won't use a webgl renderer even though it's supported?

**Comment by englercj** [comment]
Because you are using the wrong signature for autoDetectRenderer.

Try this instead:

```
renderer = PIXI.autoDetectRenderer({
    width: size[0],
    height: size[1],
    antialias: true,
    transparent: true,
    resolution: 1,
    autoResize:true
});
```
