### ISSUE TITLE
Some text fields not rendering on android mobile chrome

### ISSUE THREAD

**Issue by albymack** [pixijs/pixi.js#5155]
### Expected Behavior
All text fields render correctly on android chrome browser.

### Current Behavior
Some text fields don't render on android chrome browser.  Which text field doesn't render varies from device to device and even from one run to the next.  Some text also disappears if other text changes.  I've tried using default Samsung browser on these devices and all text renders properly.  On desktop and IOS it works fine.

The weird thing is that it was working fine 5-6 months ago.  A slots game that was completed 6 months ago worked fine at the time, and I didn't look at it anymore, but recently tried on android mobile chrome and text no longer renders correctly. 

Anybody else run into something like this?  Any ideas to try?  I've tried legacy mode true and false,  I don't know what else to try.

### Steps to Reproduce

if you try 

https://slotsdemo.asylumlabsinc.com/testportal?game=slots03

on android mobile chrome browser, and you open up the bet panel by clicking on button on the right, you'll see various buttons without text.  Click on any of the bet amount buttons, and bring up the bet panel again, and different buttons will have text missing.  There is text missing from other places as well.  Not all text is missing, just some.

### Environment
I've tried on s6edge, s7edge internation version, s8, lowend LG tablet, all running latest android and chrome v69.0.3497.100, using both pixijs 4.6.0 and 4.8.2.  Problem is there.

Run using default android browser, no problems.

I did try using Galaxy Tab s3 and that worked just fine using chrome or default android browser.

**Comment by albymack** [comment]
Some further info, it seems if I create a renderer with resolution set to anything > 2, then text starts disappearing.  2 or lower, and it doesn't.  My code creates the renderer as such.

Asylum.m_pRenderer = new PIXI.autoDetectRenderer(fDeviceWidth, fDeviceHeight, {
                    view : document.getElementById("stage"),
                    backgroundColor : 0x000000,
                    resolution:window.devicePixelRatio,
                    autoResize:true,
                    legacy:true                     
                }, bIsAtLeastIE11);

If window.devicePixelRatio > 2, then text starts disappearing.  I don't know what to make of it, I could hack for how to force chrome on android to not exceed resolution of 2, but it'd be nice to know what's going on.

**Comment by albymack** [comment]
Okay, turns out it's not specifically 2 or lower.  I have one project where a resolution of 2 works, but another where resolution of 2 still has text going missing and I have to drop it all the way down to 1 before it works.  I have projects done in pixi 3 that doesn't seem to have the same problems running on android chrome.

Seems like somehow the texture representing the text is getting lost.  I've tried disabling the dirty check in updateText() and that does indeed cause all text to render correctly, but of course not viable since it's recreating the text every frame even when it hasn't changed.

Any idea how this might be happening.  I'm looking through pixi.js code and nothing is popping out as the problem.

**Comment by gfcrba** [comment]
Hi. Text disappearing happened to my on android, If you have many dynamic texts (that creates over and over) and not disposing it. That caused by canvas creation for each new Text(...). There must be some limit on mobile for canvas count (especially in WebView). Managed to handle this with StaticText class which is a copy of Text except it use single canvas for all StaticText and when you set .text property it draws this on shared canvas and convert to image with toDataUrl. Hope this helps.

**Comment by albymack** [comment]
Ok, so further investigation has yielded some puzzling results and a possible fix.  Here's what I did.

On my android device (samsung galaxy s6edge), my devicePixelRatio is reported as 3.

I modified my version of pixijs so there's a separate textResolution setting in the renderer so when I autoDetectRenderer, the options I pass in include resolution:window.devicePixelRatio which is 3, and textResolution:1.

I then modified the pixijs code to use textResolution instead of resolution in the renderWebGL and renderCanvas functions.

This seems to fix my disappearing text issue and the text is still rendered crisp and clear.  This has me baffled as to why the text is still crisp even though the text resolution is now set to 1.  Got me to thinking maybe there's a bug in pixijs when resolution is set that causes text to oversample and waste memory?  Perhaps when it's doing measureFont, that somehow is already taking into account the resolution because it has it's own context that it's using to measure with, and then the text object is doing another resolution multiply on top of it?  That seems the only logical explanation as to why the text doesn't get all pixelated and ugly if I use resolution=3 and textResolution=1.

**Comment by themoonrat** [comment]
So, to explain your scenario, and why it isn't an issue with Pixi....

You are using devicePixelRatio, plus the device width and height, to create your resolution and canvas dimensions.
This means that you are rendering the game as a VERY high resolution for a mobile phone. Just using the Chrome debugger, pretending to be a Pixel 2 XL..
![image](https://user-images.githubusercontent.com/1528426/47116511-c1ca8f00-d259-11e8-9d66-9c0312e48933.png)
You may be rendering at the native-ish 1440p resolution.... but that's nearly 4million pixels; double the amount you'd be rendering if you rendered at 1080p. And do you notice a visual difference? Well, as a fellow slots maker.... not really. There's a reason Apple still get away with releasing an iPhone XS with a 720p display; it's so small that most people don't notice the difference. And that's what you're experiencing when manually setting the text resolution lower. You notice it still looks good. 

So drop that precise link of devicePixelRatio. You may want to render at 720p for lower devices, and 1080p for higher devices. But you'll lose performance and get no noticeable benefit from rendering your game at a native 1440p.

Regarding text not showing up... browsers often have a limit of how large they allow canvases to be. Sometimes 2048x2048, sometimes 4096x4096. And Text uses canvases in the background to use as a texture source. It could well be, that if you were trying to generated large text, or large amounts of large text, that the browser was hitting a canvas size limit and going 'nope'.

**Comment by albymack** [comment]
Hello, TheMoonRat

Thanks for the explanation, so I do notice a difference when I leave the resolution at just 1, all the bitmaps get jagged and the text in particular looks horrible, like 6 pixel font, on my galaxy 6edge (probably because of the devicePixelRatio being 3).  On a 7 edge, I have to drop resolution all the way down to 1 to not have text disappear, and at that resolution it's just very ugly.

What's really confusing is why the text being at resolution 1 while everything else is resolution 3 results in sharp and crisp text still, while just using a resolution of 1 for everything results in horribly low res text.

Seems like pixi internally, when using resolution > 1, would be wastefully rendering text at a larger res than it needs to.  That seems like a bug to me.

Your comment that the game could still be acceptable at a lower res stands, though.  The confusion on my part is mostly due to the resolution/textResolution thing.

**Comment by themoonrat** [comment]
Hmmm. The text class by default automatically makes its resolution match the renderers in the renderWebGL and renderCanvas functions, so maybe your 3 / 1 combo is turning out to be 3 / 3 after the first render?

**Comment by albymack** [comment]
You're correct, that why I had to modify pixi code so that in the renderWebGL and renderCanvas functions, it looks like this:

    Text.prototype.renderWebGL = function renderWebGL(renderer) {
        if (this.resolution !== renderer.textResolution) {
            this.resolution = renderer.textResolution;
            this.dirty = true;
        }

        this.updateText(true);

        _Sprite.prototype.renderWebGL.call(this, renderer);
    };

    Text.prototype._renderCanvas = function _renderCanvas(renderer) {
        if (this.resolution !== renderer.textResolution) {
            this.resolution = renderer.textResolution;
            this.dirty = true;
        }

        this.updateText(true);

        _Sprite.prototype._renderCanvas.call(this, renderer);
    };

You'll notice I added a textResolution member variable to the renderer that I initialize based on options passed into autoDetectRenderer.

I've checked in the chrome debugger connected to my phone.  The res stays at 3:1, and the text no longer disappears.  All the bitmaps and text are crisp and clear, which makes me believe when res was 3:3 there must have been some oversampling/wasteful use of resources going on.

I agree going to lower res like limiting to 1080P would result in something that looks fine and perform better in general (on ipad prod 12 in, maybe not?)  But why not have your cake and eat it too.  With this change to 3:1 res I'm able to have full res and still have crisp text that doesn't disappear.  Also, as I mentioned, I had to drop res so low on one of our games in order to prevent text from disappearing, that it was really ugly.  We're making a slots game, not a spreadsheet.  There isn't THAT much text overall.  Just seems like there must be a bug.

**Comment by themoonrat** [comment]
Well it's not anything I've ever come across, and we use text quite heavily in our games! Tho it could be device specific, since this is only happening on Samsung devices. We have had other issues with their devices in the past, and you'll see other bugs on here relating to them.

I feel something is up with the 3/1 setting that isn't quite right. Check the width and height of the canvas being created for the same bit of text? I'd get that 1/1 wouldn't look at good as 3/1, as more pixels to render helps. But it shouldn't look at good as 3/3... Hmmm

**Comment by albymack** [comment]
Not just samsung, as I noted an LG tablet exhibited similar behavior.  And it's just chrome browser.  Default browser and firefox both work fine.  And it started doing this sometime in the last 6 months, cause the game was completed 6 months ago and didn't exhibit any problems on android chrome previously, and then I decided to check on it recently and discovered this strange text disappearing problem was now happening.

So I tried seeing the difference with the text string "PLAY" and fontsize 61.
res 3:1
text canvas width: 147
text canvas height: 107

res 3:3
text canvas width:  441
text canvas height  321

I believe this is the culprit here, in the updateText function

        this.canvas.width = Math.ceil((width + style.padding * 2) * this.resolution);
        this.canvas.height = Math.ceil((height + style.padding * 2) * this.resolution);

        context.scale(this.resolution, this.resolution);

You notice canvas width and height is calculated by multipying with this.resolution.
It then also scales the context by this.resolution, resulting in a double multiplying of the resolution.

Perhaps the fix then is to not to multipy the canvas.width canvas.height calcs with this.resolution, or else not the call context.scale with this.resolution?

**Comment by albymack** [comment]
So nothing that simple, removing either one of those 2 mults results in messed up font/font sizes.  I'll keep poking and see if I can figure out what's happening.

**Comment by digibo** [comment]
The problem seems to be in the Chrome 69 update - after the Chrome 70 release yesterday, all our devices updated to Chrome 69 and started to have the same problem. We saw the problem few weeks ago on an updated phone, but thought it was device specific thing.

Setting resolution = 1 in updateText() indeed works perfectly. Changing the resolution option of the renderer makes text look bad/pixelated, I don't understand it either. Anyway, THANKS for investigation and solution!

Btw, it is most probably a Chrome bug - while Chrome 70 for desktop is already released, the Android version just entered beta, but the beta version seems to work fine without any changes to PIXI.Text

**Comment by themoonrat** [comment]
Arg, bloody browser updates! Thanks for the update, I'll let my guys know about the temporary but impending doom!

**Comment by digibo** [comment]
Also, we saw the same problem on an old project using Pixi 3 on Chrome on desktop. We were directly setting text.resolution = 2 and removing that fixed it. This was part of the "dots" we connected to reach the conclusion that it was all related to 'Chrome 69 - PIXI.Text - resolution'

**Comment by themoonrat** [comment]
I think this is something with your setup that I can't quite understand without it being in front of me to debug.

All I know is that I have different resolutions for text, renderer and assets, and all 3 can vary depending on devices, and all 3 do effect the quality in different ways, and are useful to adjust for different scenarios.

So I know this doesn't help you and your scenario... but I know it's working for me! The only difference I have is that I don't have the 
```
if (this.resolution !== renderer.textResolution) {
    this.resolution = renderer.textResolution;
    this.dirty = true;
}
```

part in my code _at all_. At constructor time, I just have the this.resolution = a global pixi text resolution setting. And that's it.
