### ISSUE TITLE
Error when use Bitmaptext in typescript.

### ISSUE THREAD

**Issue by TrinhVanDan** [pixijs/pixi.js#5160]
I use typescriptand pixijs to code my app. When i create a bitmaptext and set anchor for it, but the typescript show error:"Property 'set' does not exist on type 'number | Point'.
Property 'set' does not exist on type 'number'.".

var txt = new PIXI.extras.BitmapText("0sfsfds", { font: "15px RockerSmall", align: "center" });
txt.anchor.set(0.5);
why. Thanks

**Comment by themoonrat** [comment]
I believe this is an error in the typescript definitions?
Raise with https://github.com/pixijs/pixi-typescript

**Comment by clark-stevenson** [comment]
@TrinhVanDan 

Because that seems to be a Union and they don't share an interface.  If you are using `set` then you need to tell the compiler you know it is a point. 

```
const bitmap = new PIXI.extras.BitmapText('Hi');
(<PIXI.Point>bitmap.anchor).set(100, 100);
```

**Comment by bigtimebuddy** [comment]
Issue should be filed on pixi-typescript instead. Closing.
