### ISSUE TITLE
Button clickable under the image

### ISSUE THREAD

**Issue by SerG-Y** [pixijs/pixi.js#5173]
If I create Button then add image above this button, the button still fires `mouseover` and `pointerup` events.
Maybe someone knows how to fix it, or some tips?

Example:
https://jsfiddle.net/863qvran/4/

**Comment by andrewstart** [comment]
In the interest of performance, non-`interactable` elements are not considered for hit testing at all. If you want the top image to block mouse input, set `interactable` to true on it.

**Comment by djmisterjon** [comment]
https://jsfiddle.net/jonforum/863qvran/13/
also just add another empty event work.
