### ISSUE TITLE
Displacement map not working in MS Edge

### ISSUE THREAD

**Issue by tmikesic** [pixijs/pixi.js#5174]
When tested in MS Edge, Displament Map in example doesn't work 
https://pixijs.io/examples/#/filters/displacement-map.js

Is this known issue and will it be resolved in v5?

MS Edge 41.16299.492.0
MS EdgeHTML 16.16299

Thanks

**Comment by bigtimebuddy** [comment]
Could you be more specific about "doesn't work"? Any messages, console info, does it just not show up, does the scene show up? Also, with WebGL, hardware is sometime a culprit so could you also provide your graphics card and OS version?

**Comment by tmikesic** [comment]
By 'doesn't work' I meant displacement filter is not applied, it just shows magnifier but inside it there is normal image.

It just prints pixi 4.8.2 to console, no errors are shown.

Microsoft Windows 7 Professional
6.1.7601 Service Pack 1 Build 7601
NVIDIA GeForce GTX 750

**Comment by bigtimebuddy** [comment]
Thanks @tmikesic, very helpful. Also, it says  `PixiJS 4.8.2 - ✰ WebGL ✰`, right? It's not trying to render with Canvas?

**Comment by tmikesic** [comment]
It says Canvas, not WebGL.

**Comment by bigtimebuddy** [comment]
Filters are not supported in Canvas, so this is to be expected. Does MS Edge not support WebGL?

**Comment by tmikesic** [comment]
It supports WebGL, could be issue with this specific hardware setup.

**Comment by bigtimebuddy** [comment]
Hardware can definitely be an issue.

Here is the function that's used to test if WebGL is available. Maybe try running this on it's own to see where it bails out:
https://github.com/pixijs/pixi.js/blob/dev/src/core/utils/index.js#L308-L342

If that returns `false` you don't support WebGL in a way that PixiJS needs.

**Comment by tmikesic** [comment]
It returns false, so it must be something hardware related.
I tested on another PC and it works good in MS Edge. 
I'll close issue for now. Thanks for all help!
