### ISSUE TITLE
Using Sprite as Pixi mask twice causes inverse mask to be applied

### ISSUE THREAD

**Issue by genesis-derek** [pixijs/pixi.js#5177]
### Expected Behavior
 When Re-applying the same sprite as a mask it should behave the same way as it did the first time.

### Current Behavior
When swapping masks on an object if you reassign a sprite as a mask it masks the inverse.

### Possible Solution
Not sure at this time

### Steps to Reproduce
1. Create a container add a sprite to see
2. Create a sprite and apply it as a mask to the container.
3. Create a graphics object and apply it as a mask to the container
4. Re assign the first mask sprite as a mask to the container ( it will now mask the inverse of the sprites alpha )

```
	protected updateMainReelMask (): void {
		if ( this.reelsContainer.mask ) {
			this.reelsContainer.removeChild( this.reelsContainer.mask );
			this.reelsContainer.mask = undefined;
		}
		let mask = this.reelMasks.get( this.currentReelSetIndex );
		this.reelsContainer.mask = mask;
		this.reelsContainer.addChild( mask );
	}
```

### Environment

- `pixi.js` version: "4.8.1"
- Browser: Chrome 70
- Device: Desktop

**Comment by ivanpopelyshev** [comment]
Added it in `reset()` method in https://pixijs.io/examples/#/demos/alpha-mask.js

```js
app.stage.removeChild(mask);
cells.mask = undefined;
app.stage.addChild(mask);
cells.mask = mask;
```

Nope, not reproduced. Please make a fiddle.
