### ISSUE TITLE
Container overflow hidden

### ISSUE THREAD

**Issue by mezykr** [pixijs/pixi.js#5187]
![image](https://user-images.githubusercontent.com/3213836/47299580-d2dd1c80-d61a-11e8-8c81-3b87a2f78eb9.png)

Hi,
I have a case like this above. I need to have 2 Containers with some children containers. Container B is scrollable - I'm changing position of children containers inside. In case when some content is out of the Container B top edge I would like to hide it... Basically I'm looking for something like "overflow: hidden" from CSS. Do you have some idea how to deal with it ???

**Comment by themoonrat** [comment]
Masks :)

**Comment by bigtimebuddy** [comment]
Try something like this:
```js
const mask = new PIXI.Sprite(Texture.WHITE);
mask.width = 100;
mask.height = 20;
containerB.addChild(mask); // make sure mask it added to display list somewhere!
containerB.mask = mask;
```

**Comment by mezykr** [comment]
Hi,
Thanks for your responses! In case when I would use mask, it will cover children elements from ContainerA. (ContainerA also is scrollable). It will look like this:

![image](https://user-images.githubusercontent.com/3213836/47303957-9fec5600-d625-11e8-9290-915598b71dff.png)

:(

**Comment by mezykr** [comment]
YES! 
@bigtimebuddy you are right!
`containerB.mask = mask;` did a trick .. 

thank you very much I really appreciate your help.
