### ISSUE TITLE
ParticleContainer with "alpha:true" is slow

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#5188]
Got a report from user, apparantly this part is slow

https://github.com/pixijs/pixi.js/blob/dev/src/particles/webgl/ParticleRenderer.js#L422

### Possible Solution

We should add one more `if` to check if tint is trivial `0xffffff`. That helped in the case.

### Environment

- `pixi.js` version: 4.8.2_

**Comment by amanriquez** [comment]
looking for my first open source contribution, can I try this?
