### ISSUE TITLE
Lines with cacheAsBitmap=true rendered incorrectly

### ISSUE THREAD

**Issue by BetaRavener** [pixijs/pixi.js#5190]
May be related to #4941 (the slime offset in image) although happens also for Canvas renderer.

### Expected Behavior
Cached graphics, especially lines should render the same as non-cached versions.

### Current Behavior
Cached lines don't display correctly. For example, lines deviating from diagonal get strange offset. The saved geometry (coordinates) is correct though. The more straight line is (both vertical and horizontal) the more is this apparent. There also seems to be issue with antialiasing (_kinda_straight_ line in the example) or the lines are losing width. 

### Possible Solution
Definitely was not present in Pixi.js 3 but that's many version ago. Because issue is most pronounced with straight lines and lines are losing width, I'd suspect an error with bounding box.

### Steps to Reproduce
Example: https://jsfiddle.net/vqrcsbf0/2/
Red square marks correct position where lines should end. Blue line is not using caching. Green lines do use caching. Perfectly diagonal line seems to be ok. Perfectly straight line shows largest error. 

### Environment

- `pixi.js` version: _4.8.2_
- Browser: _Chrome 70, Firefox 62_
- Device: _Desktop_

**Comment by ivanpopelyshev** [comment]
Still broken

**Comment by themoonrat** [comment]
Closing as fix merged in
