### ISSUE TITLE
Bolder text is more higher

### ISSUE THREAD

**Issue by liajoy** [pixijs/pixi.js#5191]
### Expected Behavior
Maybe bolder text should be as high as the normal text, just like in canvas do?
see: https://jsfiddle.net/1bvyrck6/2/
### Current Behavior
Bolder text is higher than the normal one.  
see: https://jsfiddle.net/1bvyrck6/3/

### Environment

- `pixi.js` version:  4.8.2
- Browser: Chrome 69

**Comment by liajoy** [comment]
Seems the reason is the letter 'É'.
Bolder É is not as high as normal even in canvas. So measureFont function return a larger fontSize.
Is there any solution?

**Comment by themoonrat** [comment]
Could changing the text metrics settings `TextMetrics.METRICS_STRING`, `TextMetrics.BASELINE_SYMBOL = 'M';` and `TextMetrics.BASELINE_MULTIPLIER = 1.4` help?
http://pixijs.download/dev/docs/core_text_TextMetrics.js.html#line674

**Comment by liajoy** [comment]
@themoonrat 
I'll appreciate it very much if you could tell me why letter 'M' could be the baseline symbol.

**Comment by themoonrat** [comment]
Unfortunately, the canvas api only lets us measure the width of text drawn, not the height.
So the baseline symbol and multiplier are basically trying to use a wide symbol, and use that as a guesstimate as to how tall text might be

**Comment by liajoy** [comment]
thanks a lot!
I am also very curious about ascent calculation. Seems Pixi scans from top to bottom until find a non red pixel, then the diff of line index and baseline will be the ascent. But sometimes ascent isn't the top of some letter, maybe the ascent line is higher than the top of letter. How does Pixi's text position almost equal to text dom under the most conditions?

**Comment by liajoy** [comment]
thanks a lot! 
Could you please take a quick look on the pr?
