### ISSUE TITLE
pixi.js lack of some feature, that is 'stage scale mode' and 'stage align' like adobe flas's

### ISSUE THREAD

**Issue by loohoo** [pixijs/pixi.js#5192]
I am new to pixi.js, I found nothing about the stage scale mode and stage align.
Could any body tell me does pixi.js has this kind of facility? If doesn't I would going to implement by myself...

**Comment by ivanpopelyshev** [comment]
Google "pixi viewport", there are multiple plugins. 

Its too project-specific to be part of vanilla pixijs, and people prefere to do it different ways. Its also good exercise to do it on your own, to get familiar with basic pixi elements and how pixi connects to html page.. 

In general, you'll see that many things from flash don't exist in pixi (like effective cache for filtered elements), and no one implemented full Flash in web so far.

**Comment by loohoo** [comment]
thank you very much for helping me a lot.

**Comment by bigtimebuddy** [comment]
Good answer from Ivan. We don’t plan to add similar features you mentioned to PixiJS. And there are plugin solutions available. Closing.
