### ISSUE TITLE
Rendering texture created with other renderer

### ISSUE THREAD

**Issue by edreal** [pixijs/pixi.js#5194]
I have game scene and minimap. I am creating all the player names with game.renderer.generateTexture() and cache them. In minimap I would like to use the same generated textures to increase performance. It looks like minimaps own renderer doesn't render textures generated with game.renderer.generateTexture(). Renderers have same settings except width and height. What could I do, is the only way to create own PIXI.Text's for minimap names?

**Comment by englercj** [comment]
You cannot share resources between two different WebGLRenderers. You cannot render to a framebuffer (RenderTexture, from generateTexture) and use it in a different WebGLRenderer. That is not supported by WebGL.

I also wouldn't recommend using a separate renderer for a minimap in your game, unless you are rendering in a separate window or something. Ideally your minimap would just be a container in your normal game renderer.

**Comment by edreal** [comment]
By having only one renderer, is the performance much better?

**Comment by englercj** [comment]
I don't think I can answer a question that vague. I don't know what you mean by "performance" or "much better".

But your code will be simpler, and you can share resources.

**Comment by edreal** [comment]
In my situation, first renderer needs to render as often as possible and other renderer only once in a second, so I thought its better to not burden the first renderer with stuff which doesn't need to be rendered every frame.

**Comment by themoonrat** [comment]
You could always use cacheasbitmap or rendertexture or on the minimap container. So yes it's being rendered every game, but only at the cost of 1 sprite, which is nothing in the grand scheme of things.

**Comment by edreal** [comment]
Does cacheAsBitmap save the containers/sprites state thus better performance?

**Comment by englercj** [comment]
Rendering a single image is really fast. Your minimap should be a RenderTexture that you update when it is necessary.

> Does cacheAsBitmap save the containers/sprites state thus better performance?

Cache as bitmap does what I just described above. Renders a container to a RenderTexture and then renders that (via a Sprite) each frame.

**Comment by edreal** [comment]
Okay, thanks mate!
