### ISSUE TITLE
isWebGLSupported not checking getProgramParameter 

### ISSUE THREAD

**Issue by nuthinking** [pixijs/pixi.js#5195]
### Expected Behavior

If a device passes the isWebGLSupported check, it should be able to run Pixi.

### Current Behavior

Some old machine throws: Failed to execute 'getProgramParameter' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.

### Possible Solution

Check if getProgramParameter is supported.

### Environment

- `pixi.js` version: 4.6.1
- Browser: Chrome 70
- Device: Desktop (Win 8.1)

**Comment by englercj** [comment]
Do you have a piece of code that duplicates the behavior? What version of pixi are you using?

**Comment by nuthinking** [comment]
The behavior only happens in some devices (I receive the errors through Sentry). I put the pixi version in the issue, just forgot to remove some decorations. It's 4.6.1

**Comment by nuthinking** [comment]
Oh, maybe this is related to this: https://github.com/pixijs/pixi.js/issues/3822
