### ISSUE TITLE
Documentation error (or not only) for "graphics.drawRoundedRect()" method

### ISSUE THREAD

**Issue by AleXNoD** [pixijs/pixi.js#5197]
Hi,

Please check this one: 
http://pixijs.download/release/docs/PIXI.Graphics.html#lineStyle

It is actual only for "drawRoundedRect()" method, not "drawRect()".

Wrong:
"alignment of the line to draw, (0 = inner, 0.5 = middle, 1 = outter)".

Right:
"alignment of the line to draw, (1 = inner, 0.5 = middle, 0 = outter)".

Proof:
https://codepen.io/AleXNoD/pen/yRZdaO

**Comment by ivanpopelyshev** [comment]
I think it depends on the orientation of figure.

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital did you take into account orientation?

**Comment by ivanpopelyshev** [comment]
Orientation is not possible to determine if figure is not closed, so I really don't know if we should take it into account.

However, its strange that orientations of RECT and ROUNDED_RECT are different :)

**Comment by ivanpopelyshev** [comment]
It works: https://pixijs.download/dev-roundedrect-orientation/pixi.js

@AleXNoD good catch!

**Comment by AleXNoD** [comment]
@ivanpopelyshev thanks for fix!
Please pay attention also to this https://github.com/pixijs/pixi.js/issues/5135 issue that contains more serious problem.
