### ISSUE TITLE
v3.x documentation—available somewhere?

### ISSUE THREAD

**Issue by kjleitz** [pixijs/pixi.js#5198]
Searched around a bit and couldn't find them. Tried going to https://pixijs.download/v3.0.8/docs/index.html (swapped out the release tag since it seemed to route consistently for 4.x versions) but no luck.

Is the documentation for version 3 available somewhere?

**Comment by englercj** [comment]
We didn't start publishing every version to our servers after v4. AFAIK the v3 docs are not hosted anywhere. Your best bet is to clone the repo, checkout a v3 tag, build the docs and open them.

**Comment by bigtimebuddy** [comment]
I can add them to the S3 bucket for historical reasons like this. I think I got most of v4, since we moved to Travis deployments.

**Comment by bigtimebuddy** [comment]
The latest v3 docs are available here:
https://pixijs.download/v3.0.11/docs/index.html

**Comment by kjleitz** [comment]
Thank you so much @bigtimebuddy!!
