### ISSUE TITLE
Add some documentation how to use webpack and PIXI (atlas/bitmap font)

### ISSUE THREAD

**Issue by EloB** [pixijs/pixi.js#5199]
It's pretty common to use webpack and other tools like that these days. I don't see any examples within the documentation how to use with it with atlas or bitmap fonts for instance.

Is there any best practices?

# I came up with this for Bitmap text `.fnt` files.
## webpack.config.js
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.fnt$/,
        use: [
          'file-loader',
          'extract-loader',
          {
            loader: 'html-loader',
            options: {
              // by adding this it will extract each "page” file from the xml as well
              attrs: ['page:file'],
            },
          },
        ],
      },
      {
        test: /\.png$/,
        use: ['file-loader'],
      },
    ],
  },
};
```
## Example of fnt file
```xml
<?xml version='1.0'?>
<font>
   <info aa='1' size='50' smooth='1' stretchH='100' bold='0' padding='0,0,0,0' spacing='0,0' charset='' italic='0' unicode='0' face='Arial'/>
   <common scaleW='832' packed='0' pages='1' lineHeight='56' scaleH='768' base='46'/>
   <pages>
        <!-- This file will get extracted too with webpack now -->
        <page id='0' file='arial.png'/>
   </pages>
    <chars count='590'>
        <char xadvance='14' x='64' chnl='0' yoffset='46' y='198' xoffset='0' id='32' page='0' height='0' width='0'/>
        <!-- A lot of chars -->
   </chars>
   <kernings count="67">
        <kerning first="86" second="117" amount="-1"/>
        <!-- A lot of kerning -->
   </kernings>
</font>
```
## Usage
```js
import { loader } from 'pixi.js';
import bitmapFontUrl from './path/to/my/bitmap.fnt';
// with the loader in place it will automatically add both the fnt and png file to your webpack build :)

loader
  .add(bitmapFontUrl)
  .load(startMyApp);
```

**Comment by EloB** [comment]
There is one issue with the above solution. The Bitmap parser doesn't look if the "page" file path is relative so it always adds xmlPath.

https://github.com/pixijs/pixi.js/blob/00241de7ffb9df47d2b84c1b07c3b710733e0833/src/loaders/bitmapFontParser.js#L88

**Comment by bigtimebuddy** [comment]
Unfortunately, this isn’t the correct way to add resources with webpack. Would love it if someone wrote an article or howto about this. 

If you want to use webpack loaders to pack external assets, you cannot send them through the resource-loader (eg PIXI.loaders.Loader). Instead use BitmapText.registerFont API directly to register your font XML and textures. Basically, create your own internal loader. The Loader is only for loading external assets via XMLHttpRequest, not ones packed with a bundler.

**Comment by EloB** [comment]
My code above does exactly that. It sends them through "resource loader" and it works. :)

It uses the `file-loader` combined with `html-loader` to extract `<page file="thefile.png" />` to the bundle as well.

**Comment by EloB** [comment]
How I preload my assets is by using `require.context`.

**Example**
```js
const requireContext = require.context('./components/', true, /([^/]+)\/preload\.js$/);

export const preload = () => new Promise((resolve) => {
  const files = [].concat(
    ...requireContext
      .keys()
      .map(pathName => Object.values(requireContext(pathName))),
  );
  loader
    .add(files)
    .load(resolve);
});
```

Each of my component have their own folder and I can place a `preload.js` file to specifiy what I would like to preload for that specific component.

**components/Something/preload.js**
```js
export { default as someAsset } from './someAsset.png';
```

**Comment by EloB** [comment]
> Basically, create your own internal loader. The Loader is only for loading external assets via XMLHttpRequest, not ones packed with a bundler.

How do you mean? If the app is hosted on internet you still need to use `XMLHttpRequest` to download the assets or do you mean to include base64 data?
