### ISSUE TITLE
Pixi Loader stops loading when loading more than 1 mp3's on UC Browser

### ISSUE THREAD

**Issue by genesis-derek** [pixijs/pixi.js#5201]
### Expected Behavior

When loading audio files they should load on all browsers.

### Current Behavior

When loading more than 1 mp3 file on UC Browser iOS causes the loader to stop loading any subsequent files. No errors are thrown and error event never happens. Same build works fine on all other browsers/device pairs.

### Possible Solution

Unknown at this time

### Steps to Reproduce

Load more than 1 mp3 file through pixis loader on ios UC browser

### Environment

- `pixi.js` version: 4.8.1
- Browser: UC v11.3.2.1094
- Device: iphone x - iOS 11.4.1

**Comment by genesis-derek** [comment]
Sorry for the description, but this also appears to happen with only 1 mp3 as well

**Comment by genesis-derek** [comment]
Only iOS UC browser. I can get a link that you can reproduce this on a little later tonight when I get home.

I've been debugging our code today and I dont think it's in the middleware but it's still probable. I'm having a slow time with this as I cannot find a easy way to debug uc browser on iOS. 

Currently using weinre to debug and can only use console logs and no breakpoints with it.

If it helps we are using howler for our sound api.

**Comment by englercj** [comment]
I don't have a device to debug this on, so I won't be able to help if it doesn't reproduce elsewhere.

**Comment by genesis-derek** [comment]
Im not sure why it works on all other devices/ browser combos without this fix but adding this fixed the issue for me.

		PIXI.loaders.Resource.setExtensionLoadType( 'mp3', PIXI.loaders.Resource.LOAD_TYPE.XHR );
		PIXI.loaders.Resource.setExtensionXhrType( 'mp3', PIXI.loaders.Resource.XHR_RESPONSE_TYPE.BLOB );

Can close the issue

**Comment by englercj** [comment]
Likely has something to do with the `<audio/>` element implementation on that browser?
