### ISSUE TITLE
Filter demos page is crashed

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#5210]
Get this error => 

compileProgram.js:19 Uncaught TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.

Was working fine last week.

**Comment by englercj** [comment]
This error happens when a shader fails to compile. You should see log output of the compile errors above this error.

I think the new lodBias parameter that got introduced may be causing this error but I haven't had time to build locally yet.

**Comment by bigtimebuddy** [comment]
Caused by #5120

**Comment by bigtimebuddy** [comment]
Fixed

**Comment by Teoxoy** [comment]
I didn't look into why this happens yet but maybe #3929 is a better alternative to what I was trying to accomplish with my PR.
