### ISSUE TITLE
Partially transparent container causes add blendmode sprites to bleed through opaque sprites

### ISSUE THREAD

**Issue by distinctdan** [pixijs/pixi.js#5222]
Here's my sprite hierarchy:
```
Container - Fader (alpha goes 0 to 1)
    Container
        Opaque Sprite (normal blendmode)
        Add Sprite (add blendmode)
```

Normally, the opaque sprite blocks part of the add sprite. However, when the fader container is fading in, the add sprite shows through it. The "add" effect ought to be applied first and blocked by the opaque sprite, then the result of that ought to be faded. However, it's like the add effect goes up through all the containers. Seems like a bug to me, I'd be interested in workarounds though. It's not a huge deal, just looks slightly weird during scene fade in/out.

### Environment
macOS 10.13.6 High Sierra

- `pixi.js` version: 4.8.2
- Browser: Chrome 70.0.3538.102
- Device: Desktop

**Comment by ivanpopelyshev** [comment]
Order of operations is important here, Blending is not associative. 

Put AlphaFilter on that container , enable it when you need to Fade, change filter alpha.

Or just put a big black sprite or graphics over everything and fade it instead.

**Comment by bigtimebuddy** [comment]
Would definitely recommend using the AlphaFilter for this situation:
```js
const container = new PIXI.Container();
const filter = new PIXI.filters.AlphaFilter();
container.filter = [filter];
// change `filter.alpha` from 0 to 1 instead of `container.alpha`
```

**Comment by distinctdan** [comment]
Thanks for the suggestions. So I just tried doing an alpha filter, but I'm getting what looks like moire patterns on some long thing graphics, and some visual artifacts on some of the objects. There's also a visual "pop" you can see when the filter turns on. Here's a screencap: https://youtu.be/lE81gK46_M4

Doing a big black graphics over everything worked nicely though.

For reference, this is on my level start screen, so the camera is doing a flyover fadein/out of the level.

**Comment by Dairnon** [comment]
@distinctdan Hey if you don't mind could you provide an example of the alphaFilter problem you encountered? 

Something like a codepen that we can see in action. alphaFilter shouldn't be behaving that way so it be interesting to see what's causing that issue.

**Comment by distinctdan** [comment]
Hmm, I'll try to repro it when I've got some time.

**Comment by distinctdan** [comment]
Here's a demo of the aliasing issue on the graphics. You can see some strobing on the blue square and square jaggies on the edges of the shapes. If you comment out the line adding the alpha filter, it goes away: https://plnkr.co/edit/71xavEiWbjn9iBMRBfyL?p=preview

I'll try and repro the other weirdness with the sprites in a separate plunker.

**Comment by distinctdan** [comment]
Got the alpha one reproed too. Looks like the alpha filter isn't working with overlapping sprites that have the add blend mode: https://plnkr.co/edit/cvhJdNR5hzEuosiZaCJX?p=preview

**Comment by Dairnon** [comment]
The aliasing issue is strange...

For your alphaFilter blendMode problem...

the issue is that filters dont work correctly with sprites with blendModes applied... 

u can solve this by setting the filter.blendMode to whatever blendmode you need

**Comment by distinctdan** [comment]
Hmm, thanks for the info, although since my use case was for a global fade in/out, I've got a mix of blend modes throughout the scene, so I can't just use the filter blendmode.

**Comment by distinctdan** [comment]
If the alphaFilter isn't supposed to work with sprites with different blendmodes, then I feel that ought to be in the docs.
