### ISSUE TITLE
Should `value` and `type` be included in uniforms?

### ISSUE THREAD

**Issue by Ovilia** [pixijs/pixi.js#5223]
I'm using PIXI v4.8.2 and I'm not sure if shader uniforms should use the value itself, or an object containing `value` and `type`?

As according to the [API](http://pixijs.download/release/docs/PIXI.Filter.html#uniforms), it should be
```js
filter.uniforms.time = performance.now();
```
rather than 
```js
filter.uniforms.time = {
    type: float,
    value: performance.now()
};
```

But I tried and it's not working this way: (result: all in black)
```js
const magic = 0.3;
const uniforms = {
    magic: magic
};

const fShaderText = `
precision mediump float;
uniform float magic;
void main(){
    gl_FragColor = vec4(magic, 0.0, 0.0, 1.0);
}`;

var simpleShader = new PIXI.Filter('', fShaderText, uniforms);
bg.filters = [simpleShader];
```

And it works when using `type` and `value` like: (result: all in color (0.3, 0.0, 0.0, 1.0))
```js
const uniforms = {
    magic: {
        type: 'float',
        value: magic
    }
};
```

I noticed that [the source code](https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/filters/Filter.js#L52) do take the value property. So is the doc outdated?

### Expected Behavior

Work with 
```js
const uniforms = {
    magic: magic
};
```

### Current Behavior

All in black.

### Environment

- `pixi.js` version: 4.8.2
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by finscn** [comment]
The  struct of the argument `uniforms ` in the  constructor  is different from the property `uniforms`.
( the argument `uniforms ` in the  constructor  should be called `uniformsData` , I think)

When you create a filter instance , you should use:  
```
const uniforms = {
    magic: {
        type: 'float',
        value: magic
    }
};
```

But , when you want to change the value of `magic`, you just use : 
```
filter.uniforms.magic = newValue;
```
.

By the way , in the most cases , you could ignore the 3rd  argument `uniforms `.

**Comment by ivanpopelyshev** [comment]
Its different in v5. I doubt it will be changed in v4. Would you like to change this article? https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters

**Comment by ivanpopelyshev** [comment]
I've added @finscn post to the article. Good idea about renaming the parameter
