### ISSUE TITLE
Filter uniforms: Point for vec2 – inconsistent behavior

### ISSUE THREAD

**Issue by idudinov** [pixijs/pixi.js#5226]
Hi there!

I've encountered an issue when a filter accept PIXI.Point object for vec2 uniform.
Here's live example: https://jsfiddle.net/idudinov/a4m3kb9e/

So what's going on there. There're 2 instances of simple RGBSplit filter, each for its own object. One of them being animated through TweenMax. The second filter getting uniform values from the first one, which is not desired.
It happens when filter initialized with points, but animated like arrays; and vice versa – initialized with arrays but animated like points. There're also other 'good' and 'bad' cases, but it's better to skip to the root cause of the problem.

https://github.com/pixijs/pixi.js/blob/8db11a48ca8a78c5506a47edf549777cd9e42934/src/core/renderers/webgl/managers/FilterManager.js#L411-L423

In case the code assumes that the uniform is a Point (`uniforms[i].x !== undefined`), it takes current uniform value and then changes it; but current value is a reference to an array, which can be uniform of another filter instance! Because in case current uniform value is NOT a Point, it just copies **reference** to an array to shader's uniforms object.

So there is just a reference sharing problem. Possible solutions:
1) Of course, make client code consistent: if you need to animate Point, use Point and never arrays for setting uniform value;
2) Just make a copy of an array before sending to shader; that will result to extra allocations though;
3) Same as previous, but use some kind of pool of re-usable arrays, or maybe each Point could have own array for representing itself; this should guarantee uniform values will not get overridden during rendering.

**Comment by ivanpopelyshev** [comment]
v5 is different. We wont patch v4.

**Comment by idudinov** [comment]
Got it!
Hopefully this issue will be useful for somebody who encounters such problem. Also, as a kind reminder for everyone to keep memory management under control :)
