### ISSUE TITLE
NineSlicePlane renders incorrectly on canvas with rotated texture from texture atlas

### ISSUE THREAD

**Issue by PrashaanP** [pixijs/pixi.js#5228]
### Expected Behavior
Using sprite sheets with rotated sprites for nine slice planes should be sliced and added to the canvas correctly.

### Current Behavior
The nine slice plane works perfectly on a webgl context, however when forcing the renderer to canvas results in different behaviour. It seems as if the texture is not being rotated back to its original orientation before being sliced.

### Steps to Reproduce
- Use texture packer to build a sprite sheets with rotations 
- Force the renderer to canvas
- Read in the texture using the texture atlas
- construct the nine slice plane

### Environment

- `pixi.js` version 4.8.0
- Browser: Chrome 70.0.3538.110
- Device: Desktop and Mobile

**Comment by ivanpopelyshev** [comment]
Please provide a fiddle. I remember that we fixed something like that but not sure was the before 4.8.0 or after.

**Comment by ivanpopelyshev** [comment]
Ok, no need of fiddle, I see that this method doesn't care about rotations: https://github.com/pixijs/pixi.js/blob/dev/src/mesh/NineSlicePlane.js#L211
