### ISSUE TITLE
ParticleContainer have wrong width and height no matter how many children.

### ISSUE THREAD

**Issue by rockmandash** [pixijs/pixi.js#5229]
Please see this minimum example.
Codepen [https://codepen.io/rockmandash/pen/YREeOX?editors=0010](https://codepen.io/rockmandash/pen/YREeOX?editors=0010)

Or see code
```javascript

// create a normal app
const app = new PIXI.Application(window.innerWidth, window.innerHeight, {
  transparent: true
});
document.body.appendChild(app.view);

// create a texture for sprite
const graphics = new PIXI.Graphics();
graphics.beginFill(0xffffff);
graphics.drawRect(0, 0, 1, 1);
graphics.endFill();
const particleTexture = graphics.generateCanvasTexture(
  PIXI.settings.SCALE_MODE,
  2
);

// create a particle Container
const particlesContainer = new PIXI.particles.ParticleContainer(300, {
  position: true,
  tint: true
});

// add 100 children to particle container, right now the particle container's width & height should be 100
for (let i = 0; i < 100; i++) {
  const pixel = new PIXI.Sprite(particleTexture);
  pixel.x = i;
  pixel.y = i;
  pixel.alpha = 1;
  particlesContainer.addChild(pixel);
}

app.stage.addChild(particlesContainer);

// width & height is 1 (bug)
console.log(particlesContainer.width); // 1
console.log(particlesContainer.height); // 1
```

As you can see, particlesContainer's width & height will always be 1, same thing goes different when particlesContainer is a normal container (will console.log  100)

**Comment by jcyuan** [comment]
out of topic: I will never expect that particlecontainer will give me size info, just imagine that there is thousands of particles in it and everyone moves rapidly.... so from engine level, I have to loop so many objects to calculate the AABB bounds... this is so terrible..
(just my thought. don't know if PIXI has implemented this already)

**Comment by rockmandash** [comment]
@jcyuan Thank you for your perspective.
But sometimes my particle container contains still objects, they don't move, if there is a method we can manually call to recalculate the particle container's width and height, that will be good enough for me.

**Comment by ivanpopelyshev** [comment]
Congratulations! You have reached the level where you have to hack pixi to get result that no one else needs.

Hack its `calculateBounds` method: https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js#L342
