### ISSUE TITLE
Video transparency in mp4  using an alpha mask

### ISSUE THREAD

**Issue by Dzazaleo** [pixijs/pixi.js#5233]
Hi,

I want to play animations with transparency but PNG sequences can be quite heavy. So i was thinking that using video instead could be a workaround. 

h.264 is great format but it doesn't support transparency, right? So i was thinking that if i export the same animation both in normal mode and alpha channel mode, maybe i could use the alpha channel version as a mask for the original video.

Basically, the "mask" video could be used to tell Pixi that pixels within the black areas are to be transparent.

I exported these two videos so you can understand better what i'm saying:

[Video Test.zip](https://github.com/pixijs/pixi.js/files/2600673/Video.Test.zip)

I am a designer and don't have any experience in coding. I just want to find some basic answers before I talk to the programmers in our company about this. 

But if what I'm proposing is impossible, what would be the best workflow to play transparent videos?

Thank you very much,
Leo

**Comment by barbarosso** [comment]
Hello @Dzazaleo,
The webm video format does support tranpsarency, you should check 'caniuse' to see if the browsers you're targetting are supported.

https://caniuse.com/#feat=webm

The only downside at the moment is that there is a bug in chrome +70  on windows, where the redraw of the layer is corrupted, and the previous frame is still showing. 

I don't know if the pixi team has a fix for this? 

I've also created an example so you can see how to implement it.
https://codesandbox.io/s/kw6l14wxw5?from-embed

**Comment by djmisterjon** [comment]
Try encode your video in vp9 codec.
![image](https://user-images.githubusercontent.com/24865815/48799680-ca3d3c00-ecd5-11e8-9520-6906136957d8.png)
And add this to your transcoder
https://github.com/FFmpeg/FFmpeg/commit/acca56d9629b7fc158ce188190d22314c3d92c39
You also need add some fix if you have ghost images.
https://github.com/pixijs/pixi.js/issues/4089
![image](https://user-images.githubusercontent.com/24865815/48799776-053f6f80-ecd6-11e8-8bbd-1cca2f1ab9cc.png)

Also i good doc here will help you
http://avisynth.nl/index.php/Avisynthplus_color_formats

**Comment by barbarosso** [comment]
@djmisterjon @Dzazaleo  the fix isn't working anymore in chrome + 70 on windows.
#4089#issuecomment-436318186
The only fix we've found so far is switch to canvas renderer when on windows.
