### ISSUE TITLE
[Question] About drawMode in MeshRenderer

### ISSUE THREAD

**Issue by jcyuan** [pixijs/pixi.js#5234]
I wonder why `Mesh.DRAW_MODES` does not have a `FAN` mode?

    Mesh.DRAW_MODES = {
        TRIANGLE_MESH: 0,
        TRIANGLES: 1,
    };

I think the `FAN` mode is really useful for drawing circles? 

and I think this is easy to add, just change https://github.com/pixijs/pixi.js/blob/90268cd4472618c28c383ed5901caa3105c9a7df/src/mesh/webgl/MeshRenderer.js#L130 this line to add `gl.TRIANGLE_FAN`?

or is it actually realted to a compatible problem?

**Comment by HypnosNova** [comment]
TRIANGLE_FAN mode is useful
