### ISSUE TITLE
Adding correct page title for documentation on pixijs.download

### ISSUE THREAD

**Issue by TeodorDre** [pixijs/pixi.js#5237]
Hello everyone! 

I'm starting to learn pixi.js not a long time ago. Thank you for pixi.js it is really amazing work. After working with a native webgl, it is like a breath of fresh air.

I'm hardly learning your documentation at pixijs.download, but as i can see all pages have similar titles, and doesnt't show correct inner of page. Its really uncomfortable when i open 2-3 tabs in my browser, so i cant identity them. 

It will be great, if you add correct `<title></title` for every page. Thank you! I think it can be useful for everyone, who starts to meet with PIXI. 

for example => http://pixijs.download/release/docs/PIXI.Application.html

**Comment by AndreKleef** [comment]
+1

**Comment by bigtimebuddy** [comment]
We’ll also need to update the dependency here, but let’s get the title fixed and I can help with the publishing of the template. Thanks for agreeing to help out!
