### ISSUE TITLE
Erro: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by TrinhVanDan** [pixijs/pixi.js#5238]
sometimes pixi loader say: "Cannot read property 'width' of undefined". but when i press f5. it works. How to fixed this. Thanks

**Comment by ivanpopelyshev** [comment]
Loader resources aren't created at `add` method, they are progressively downloaded, so you can't just assume that after

```
loader.add('something.png').load();
```

this exists:
```
loader.resources['something.png'].texture.width
```

Do you have the code like that one?

```
setTimeout(function() {
   var sprite = new PIXI.Sprite(loader.resources['something.png'].texture);
}, 1000);
```

Make sure that your code access textures only after load() is completed.

**Comment by TrinhVanDan** [comment]
I use oncomplete to sure resources has loaded.  my code is: ` this.loader.on("complete", complete);` I create game after load complete. Sometime it has error but sometime it works.

**Comment by TrinhVanDan** [comment]
> Sounds like somewhere things are assuming it takes time to load, so when it is cache it fails. Can you give us an example that reproduces your error?

sorry, another people write other modules, he add pixijs to webpack and when run his modules. It load pixijs and has error.Closed
