### ISSUE TITLE
Large sprites performance hit

### ISSUE THREAD

**Issue by distinctdan** [pixijs/pixi.js#5246]
So I'm trying to do a starfield effect for the game I'm working on, so I have a lot of large overlapping sprites to create the stars effect, with each sprite containing many stars. However, I'm discovering that it seems like large sprites have a huge performance hit, even if they're using low resolution textures. In this plunkr, I've taken the particle container example off the website and changed the sprites' scale to "2" instead of "1" with the `totalScale` variable. As you can see, it really chugs. If you set it higher, like 5 or 10, it'll really lock up. Any ideas what's going on? I wouldn't expect this to be such a big hit. 

Edit: Discovered it was large sprites in general, not just if the scale is set greater than 1.

### Plunkr Link

https://plnkr.co/edit/zoBSGCYQS1NCcc6y1IXN?p=info

- `pixi.js` version: 4.8.2
- Browser: Chrome 70.0.3538.102
- Device: Desktop Mac OSX

**Comment by ivanpopelyshev** [comment]
Fillrate problems. Number of pixels drawn on screen is important, and pixi doesn't and can't optimize that part. You have to make shaders and renderer for two-passes algorithm that uses z-buffer to solve the issue.

**Comment by distinctdan** [comment]
Hmm, that sounds complicated. Are there any examples of pixi stuff that does that, or any resources of where to start?

**Comment by ivanpopelyshev** [comment]
Its not pixi, its webgl problem, it also depends on your videocard, whether its nvidia or integrated intel. 

Its mostly a problem for integrated videos.

**Comment by englercj** [comment]
@distinctdan Fillrate is how fast your GPU can draw pixels (to simplify a bit). What Ivan is saying is that when you have many big sprites, suddenly the fragment shaders have to do a *lot* of work. Texture resolution isn't relevant, the number of pixels on the screen that the GPU has to render is. Low resolution texture save memory, they don't increase fillrate.

The solution he is recommending is to have a buffer that stores z data, which you can use to reduce the amount of actual fragment drawing that happens later. We don't do this for you in pixi. This is also rarely needed in 2d applications, so I doubt you'll have an easy time finding a ready-made solution.

**Comment by englercj** [comment]
Another option is to use a single sprite with a custom shader that reads from multiple textures, rather than doing multiple large sprites that layer on top of eachother.

**Comment by distinctdan** [comment]
Hmm, ok, I see what you're saying about the fillrate. For my particular effect, the sprites are mostly transparent, so unfortunately a zbuffer wouldn't allow me to cull anything. However, I can play around with maybe using a few larger sprites kind of like you mentioned with the multiple textures, or perhaps since my sprites have a lot of empty space, putting the particles on more dense, smaller, sprites to reduce the fill area.

Thanks for the help guys.
