### ISSUE TITLE
BaseRenderTexture.render is not a function

### ISSUE THREAD

**Issue by adrian-castravete** [pixijs/pixi.js#5247]
I'm trying to create a "background" for a game, and was thinking of using a BaseRenderTexture on which to render some Sprites as tiles.
Following the documentation I get the following error in the browser console:
```
    Uncaught TypeError: baseRenderTexture.render is not a function
```

The documentation I'm referring to is: http://pixijs.download/release/docs/PIXI.BaseRenderTexture.html

I have also added a JSFiddle with the barebones needed to test this behaviour:
https://jsfiddle.net/adrian_c/5omq0bdy/

- `pixi.js` version: _4.7.1_
- Browser: _Chrome 70_
- Device: _Desktop_

**Comment by ivanpopelyshev** [comment]
It was in v3. Docs are wrong, wanna make PR to fix that? :)

**Comment by ivanpopelyshev** [comment]
Oh, docs in v5 (next branch) are also wrong.

**Comment by bigtimebuddy** [comment]
PR welcome!
