### ISSUE TITLE
RenderTexture not getting rendered to

### ISSUE THREAD

**Issue by wkamir** [pixijs/pixi.js#5248]
### Expected Behavior

A Spirte (with applied filters) is rendered to a new RenderTexture.

### Current Behavior

RenderTexture stays blank, nothing is rendered

### Steps to Reproduce

  let texture = textures['window']; // holds a valid texture, can be rendered with a Sprite
  let origSize = texture.orig;
  let originalSprite = new Sprite(texture);

  let cr = new CanvasRenderer(origSize.width, origSize.height);
  let renderTexture = RenderTexture.create(origSize.width, origSize.height);

  cr.render(originalSprite, renderTexture);

  let renderSprite = new Sprite(renderTexture);
  stage.addChild(renderSprite);

### Environment

- `pixi.js` version: _e.g. 4.8.2_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by bigtimebuddy** [comment]
Recreated your code here. Seems to display fine:
https://jsfiddle.net/bigtimebuddy/4q0tzsdp/

**Comment by wkamir** [comment]
Hm... yes it does. Thank you for taking the time.

It seems that my problem is that I use a separate newly created CanvasRenderer.

When I use 
`pixiApp.renderer.render(originalSprite, renderTexture);`

instead of the new CanvasRenderer, everything works as expected.
Is this by design? Because I can use the new CanvasRenerer to call e.g. cr.context.getImageData() and get the correct image back....
