### ISSUE TITLE
[Question] How do I cap framerate to, say, 30 FPS?

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [pixijs/pixi.js#5250]
### Question

How do I cap the renderer's framerate to a specific value if I'm using the default shared ticker? Are there any existing options to do that, or should I just write my own loop with `requestAnimationFrame` and call `somePixiApp.render()`?

### Use Case

A pixel art game that would benefit from lower framerate to make itself more aesthetically close to older games. Also, I'm making a general-purpose game maker on top of pixi.js.

### Environment

- `pixi.js` version: _4.8.2_
- Browser: _e.g. Chrome 69, Firefox 63.0.3_
- Device: _Linux_

**Comment by bigtimebuddy** [comment]
Check out [TARGET_FPMS](http://pixijs.download/dev/docs/PIXI.settings.html#.TARGET_FPMS)

Also relevant is the PIXI.ticker object and PIXI.tickers.Ticker. These actually do the raf.

**Comment by rich-earth** [comment]
Here's one way, not sure its the best way!   Use your own Ticker and `autoStart:false`, so you can control when render() is called. Any problems doing this @bigtimebuddy ?

[playground bunny at 15 fps](https://www.pixiplayground.com/#/edit/W2exgj042tW0QUPHTya02)

**Comment by bigtimebuddy** [comment]
Thanks @rich-earth. I'd make one tiny change to your example. The Application option `sharedTicker: false` cause the app to create a new Ticker instead of using `PIXI.ticker` (the internal ticker used for Video, AnimatedSprites, etc). This also works:
https://www.pixiplayground.com/#/edit/oGvDC6wt~XQ_xBT6Ssb10

**Comment by rich-earth** [comment]
Thanks @bigtimebuddy .  If you make your change then app.render gets called automatically (you can comment out "app.render()" in line 66 and still works.  So renderer still rendering at 60fps, instead of when desired time has elapsed?  should that be happening?

**Comment by rich-earth** [comment]
I've simplified the example...   All it does now is stop the internal ticker calling render, so we do it ourselves at desired framerate.  Any problems with that? 

[https://www.pixiplayground.com/#/edit/oGvDC6wt~XQ_xBT6Ssb10](https://www.pixiplayground.com/#/edit/oGvDC6wt~XQ_xBT6Ssb10)

**Comment by themoonrat** [comment]
The ability to set a maxFPS was added in v5 via this PR: https://github.com/pixijs/pixi.js/pull/5357
