### ISSUE TITLE
Samsung Galaxy Tab A bug with GLTexture enableLinearScaling, patch for v4?

### ISSUE THREAD

**Issue by rich-earth** [pixijs/pixi.js#5251]
Here is a solution in v4 for enabling mipmaps on a non PO2 image file, by rendering the sprite to a PO2 sized RenderTexture and enabling mipmaps on it. Thanks @ivanpopelyshev #4155 

[pixi playground](https://www.pixiplayground.com/#/edit/8Rm6eQx6fQKxICMAkELJe)

This works great on desktop/iOS but on a particular Samsung tab it renders a garbled image.  
Works fine in v5.  V4 and lines 33-35 are the problem for Samsung which are not needed in v5 as the mipmaps enable automatically.

Long shot but I was wondering if there was anything I can patch in v4,  if you know what has changed in v5 to fix Samsung GL bugs? 

Thanks  

- `pixi.js` version:  4.8.2
- Browser: Android Chrome 69
- Device: Samsung Galaxy Tab

**Comment by ivanpopelyshev** [comment]
v5 uses webgl2 and different TextureManager, it can generate mipmaps even for renderTexture and update them every time renderTexture is changed. Try v5 but with `PIXI.settings.PREFER_ENV= PIXI.ENV.WEBGL;`

**Comment by ivanpopelyshev** [comment]
Is that macOS? It looks like this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=913033

**Comment by rich-earth** [comment]
That is the view of the Samsung Tab A screen, via remote devices in Chrome (plugged into usb on a Mac) which sends a feed of the device screen through when you debug.

**Comment by themoonrat** [comment]
We default on mobile to WebGL 1, due to other driver issues, so this won't be an issue
