### ISSUE TITLE
.anchor.set(0.5,0) causes text to go persistently blurry

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#5252]
In the past, I always assumed blurry text was because of positioning and the inability to always capture pixel-perfect text with moving objects, and I never really thought too much on it - I was rendering texts 8X, shrinking them to increase quality, but even with this method, text was always blurry

I've noticed that some text was persistently blurry, no matter where they are placed, which led me to experiment, and I've discovered that setting a [0.5,0] anchor causes the text to go blurry

<img width="212" alt="screen shot 2018-11-29 at 11 28 10" src="https://user-images.githubusercontent.com/170243/49209605-fd658680-f3cb-11e8-8e2d-36fc847c715e.png">
<img width="477" alt="screen shot 2018-11-29 at 11 37 07" src="https://user-images.githubusercontent.com/170243/49209612-ffc7e080-f3cb-11e8-8066-c62f3ccc62a8.png">

After I remove the .anchor.set, even if I position text at highly floated coordinates, it never goes blurry any more

As a throwback, it seems to be a long standing issue #3072

So if I just calculate coordinates manually, and not use anchoring, my issue is solved, but I really want to preserve my .anchor usages

--------

As some extra info, this seems to happen when the width is not a perfect number, for example 35.5, when it gets anchored, text goes blurry, but when the coordinates are manually set, no value can make the text go blurry

I tried to create a pixi playground reproduction, but can't load my pixelled font through CORS

**Comment by kaansoral** [comment]
https://www.pixiplayground.com/#/edit/~~TZJA4yrsomULBPHq9_k

This playground requires one to install the m5x7 pixel font locally

So the issue isn't related to anchor, but there's a sweet spot for Text's, if a Text renders blurry, replacing it 0.25px makes it render perfectly, once it renders perfectly in a container, moving that container doesn't affect the Text crispness - so basically, crisp moving text is possible, but it needs to be placed perfectly in the first place - and I'm not sure whether the perfect positioning will be cross platform

**Comment by kaansoral** [comment]
Upon further testing, it blurs out during movement, and I only managed to reduce the amount of blurriness, so there's no bug or issue

For those who stumble onto this issue in the future, it's possible to achieve pixel perfection for static text, but one needs to calculate and apply a dynamic offset - there's probably pixel ratio in play too, since my game is 4X retina, I probably get away with 0.25's, which made me believe perfection was possible, but in the end, it was just smart rounding

**Comment by themoonrat** [comment]
https://github.com/pixijs/pixi.js/pull/5057 is a pr for v5 that lets you set individual objects to be drawn on whole pixel values only, which helps this. You might want to consider creating your own version of pixi v4 with this backported

**Comment by kaansoral** [comment]
Final update, indeed the roundPixels is the ultimate solution, and it's very easy to apply/patch-in manually - Also, roundPixels rounds based on .resolution

It's a bit awkward at first, but I set .roundPixels for moving objects to false, and it becomes true when the entity stops, so I got the best of both worlds - when stopped, you can see the ~0.5px displaced name tag / Text, at first I thought it was because roundPixels was just rounding to integer values, but it's just the way it is, that 0.5px is slightly noticeable, so instead of blurry text, there is slightly displaced text, but definitely times and times better

**Comment by themoonrat** [comment]
Glad you've got something better! Maybe to solve the slightly displaced text a bit, you could roundPixel the black text block area too? Then they might both 'snap' to nearest pixel in the same way keeping text alignment looking good?

**Comment by kaansoral** [comment]
That makes a lot of sense, never thought of it, thank you

Feels good to finally tackle this blurry texts issue, I was holding back from using Text's, no more!
