### ISSUE TITLE
drawing performance optimization help

### ISSUE THREAD

**Issue by superliwei** [pixijs/pixi.js#5253]
I use pixi.js to draw some lines.when there are many lines, render speed becomes slow, can anyone help me to optimize performance of it? thanks for help.

I gave up using Graphic API to draw because it could not set the lineCap and lineJoin style of lines. 

I made a pen here : 
https://codepen.io/superliwei/pen/XyydVy

**Comment by ivanpopelyshev** [comment]
http://www.html5gamedevs.com/topic/41582-drawing-performance-optimization-help/

Lets continue it here ;)
