### ISSUE TITLE
Is there anyway to use Subtract blend mode?

### ISSUE THREAD

**Issue by rkdrnf** [pixijs/pixi.js#5255]
I'm trying to create color overlay effects, except certain area on the screen.

My plan was to cover whole screen as ADD Blendmode with color of my choice,
and remove effect from certain area by applying SUBTRACT Blendmode with the same color used in ADD Blendmode.

But It seems there's no Subtract Blendmode in pixi v4.

Is there any workaround I can try? 
or can I implement custom blend mode in pixi v4?

**Comment by ivanpopelyshev** [comment]
I think params for subtract are `[gl.ONE, gl.DST_ALPHA]`  , but functions are `[gl.FUNC_REVERSE_SUBTRACT, gl.FUNC_ADD]`

You can make custom blendmode
http://www.html5gamedevs.com/topic/31803-scratch-card-effect/?tab=comments#comment-182673

However, pixi webglstate does not change blend function:
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/WebGLState.js#L149

Lets patch it and bring everything together: https://www.pixiplayground.com/#/edit/6c0X5xaWa2MMy6vXfIix0

TA-DA!

**Comment by ivanpopelyshev** [comment]
Though, it doesnt help with your plan, because SUBTRACT does not subtract alpha. You have to make your own equation based on my example.

**Comment by ivanpopelyshev** [comment]
Maybe that's for your case:
KNOCKOUT: `[gl.ZERO, gl.ONE_MINUS_SRC_ALPHA, gl.ZERO, gl.ONE_MINUS_SRC_ALPHA]`
