### ISSUE TITLE
PixiJS v5 does not work on IE11 due to missing Object.assign()

### ISSUE THREAD

**Issue by GAFBlizzard** [pixijs/pixi.js#5258]
### Expected Behavior
PixiJS v5 runs on IE11.

### Current Behavior
PixiJS v5 fails to load due to missing Object.assign().  PixiJS v4 did not require this.  Please let me know if any additional data is needed, or if the end user is expected to stub the Object.assign() behavior and I just missed that in the documentation somewhere.  I'm a new PixiJS user so I apologize if I am clueless about this.

### Environment

- `pixi.js` version: v5.0.0-alpha.3
- Browser: Internet Explorer 11.0
- Device: Windows desktop

**Comment by themoonrat** [comment]
Bumping to make stale bot regret his words
