### ISSUE TITLE
GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

### ISSUE THREAD

**Issue by navigator117** [pixijs/pixi.js#5259]
I have tried the method you prompt in [http://www.html5gamedevs.com/topic/38099-texture-between-pixi-and-three/](http://www.html5gamedevs.com/topic/38099-texture-between-pixi-and-three/).

pixi stage was correct displayed. but I got this error in the console:

GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

I'm thinking it's due to __webglTexture share. pixi.js write to the webglTexture and threejs read it as a material texture. This share is not allow in webgl? maybe two webglTexture swapping should be used?

**Comment by navigator117** [comment]
It seems fixed by create two PIXI.RenderTexture & swap them on each update.

**Comment by navigator117** [comment]
It seems PIXI.Text on the stage is Y flipped.

**Comment by englercj** [comment]
That error is telling you what you are reading from to draw, and what your are drawing to are the same thing.

For example, if you have a RenderTexture render to itself, using itself as input.

**Comment by ivanpopelyshev** [comment]
> It seems fixed by create two PIXI.RenderTexture & swap them on each update.

Everything is Y-flipped :)

Also I implemented double-buffering in pixi-layers, 
https://pixijs.io/examples/#/layers/trail.js
https://github.com/pixijs/pixi-display/blob/layers/src/Layer.ts#L6

**Comment by navigator117** [comment]
Sorry,  I didn't desc clear. after apply patch in http://www.html5gamedevs.com/topic/38099-texture-between-pixi-and-three/. All Y-flipped' objects were handled. But when I change PIXI.Text text dynamically It's Y-flipped again.

**Comment by ivanpopelyshev** [comment]
because its a regular texture and not renderTexture, its still flipped in pixi. 

Either you synchronize ThreeJS texture and text canvas, search how to take canvas element into threejs. Either patch TextureManager that way baseTextures with CANVAS elements are uploaded flipped.
