### ISSUE TITLE
Cross Origin errors in Sandboxed iFrame

### ISSUE THREAD

**Issue by rtibbles** [pixijs/pixi.js#5265]
### Expected Behavior
When executing Pixi.js code inside a sandboxed iframe that does not have the `allow-same-origin` attribute, it should automatically make cross origin requests for any loaded resources.

### Current Behavior
Currently, this does not happen, due to the default behaviour of https://github.com/englercj/resource-loader which fails to check `window.origin` to see if it is set to `null` which it will be inside a sandboxed iframe.

### Possible Solution
This issue has been reported upstream at https://github.com/englercj/resource-loader/issues/119 and fixed at https://github.com/englercj/resource-loader/issues/120, once this fix has been merged and a new version of `resource-loader` has been released, upgrading the package should fix this issue in Pixi.js.

### Steps to Reproduce
1. Run any Pixi.js app that uses resources (particularly WebGL resources) from inside a sandboxed iframe:
```
<iframe sandbox='allow-scripts' src='index.html'></iframe>
```
Where the index.html is a bootstrap for the Pixi.js app.

2. Observe the CORS errors in the console, as WebGL complains about reading out data from a 'tainted' canvas (i.e. one that has improperly loaded cross origin images).

### Environment

- `pixi.js` version: _4.5.2_ (but should still be extant)
- Browser: _Chrome 70_
- Device: _Ubuntu 16.04 Desktop_

**Comment by bigtimebuddy** [comment]
Thanks for reporting this and for your detailed explanation. Will make sure we get this in as soon as @englercj updates resource-loader.

**Comment by englercj** [comment]
Just published `v2.2.0` which contains the fix from @rtibbles.

**Comment by rtibbles** [comment]
Hi @bigtimebuddy would it help to submit a PR for the dependency update, or is it simpler to do from your side? Some kids in Uganda are going to be very happy when Pixi.js can work in a sandboxed iframe environment!

**Comment by englercj** [comment]
Putting in a PR is the fastest way to get changes into pixi :)

**Comment by rtibbles** [comment]
Sorry, looks like my fix in https://github.com/englercj/resource-loader/pull/120 did not actually work, am submitting an improvement that directly checks window.origin against window.location.origin.

**Comment by rtibbles** [comment]
Thanks for bringing in the fix @englercj - still thinking how to add a test or JSFiddle to show the issue this is fixing, but probably won't get to it until the new year.
