### ISSUE TITLE
How to tile Mesh Texture?

### ISSUE THREAD

**Issue by nidiy** [pixijs/pixi.js#5266]
Mesh's Texture has been stretched，How to tile Mesh Texture?
![image](https://user-images.githubusercontent.com/9928382/49560367-0535a580-f94d-11e8-93ee-8e5061c81bd3.png)

### Environment

- `pixi.js` version: _e.g. 4.8.2_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by bigtimebuddy** [comment]
TilingSprite? http://pixijs.download/release/docs/PIXI.extras.TilingSprite.html

**Comment by nidiy** [comment]
@bigtimebuddy Not TilingSprite, I need to draw a polygon of Mesh and need to support holes

**Comment by nidiy** [comment]
![image](https://user-images.githubusercontent.com/9928382/49564289-f6a3ba00-f95d-11e8-910a-07c531151b56.png)
I hope to achieve the right display

**Comment by englercj** [comment]
Try setting `baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT`.

**Comment by nidiy** [comment]
@englercj  Thanks!  setting
 `
baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT;
baseTexture.wrap = true
` 
Does not seem to work，

**Comment by bigtimebuddy** [comment]
Did you call `baseTexture.update()`? Could you provide a codepen, jsfiddle, etc?

**Comment by nidiy** [comment]
@bigtimebuddy    codepen: https://codepen.io/nidiy/pen/EOqzmB

**Comment by ivanpopelyshev** [comment]
It works only if your image is pow2.

**Comment by ivanpopelyshev** [comment]
Another way, you can make tiling mesh shader renderer, and override `pluginName` in your mesh. 

Its more difficult, you have to extend https://github.com/pixijs/pixi.js/blob/dev/src/mesh/webgl/MeshRenderer.js , change its `onContextChange` and pass your shader there. 

Anyway, you want a feature that exists only on bleeding edge plugins or pixijs version.

**Comment by ivanpopelyshev** [comment]
Here I even have a fragment shader that trims stuff! you can add % there, like in TilingSprite shader and it'll work! All you have to do is to override pixi-heaven mesh renderer. https://github.com/gameofbombs/pixi-heaven/blob/master/src/mesh/webgl/MeshHeavenRenderer.ts

**Comment by bigtimebuddy** [comment]
Power of Two texture works:
https://pixiplayground.com/#/edit/y4TYuKuD~INPAbnbfjIYO

Like @ivanpopelyshev said, you should consider using v5 (http://pixijs.download/next/pixi.min.js) we are about to make a release candidate, that's the latest build. The advantages of using v5 is that Mesh and Graphics are batched along with Sprites. Using Mesh in v4 can be slow if you have a complex scene. Also, v5 adds [`beginTextureFill`](http://pixijs.download/next/docs/PIXI.Graphics.html#beginTextureFill) to Graphics objects, which is handy for doing stuff like this.

**Comment by nidiy** [comment]
@bigtimebuddy @ivanpopelyshev   Thank you, I plan to use the pixi-v5
