### ISSUE TITLE
NineSlicePlane has gaps on CanvasRenderer (only in Firefox)

### ISSUE THREAD

**Issue by wkamir** [pixijs/pixi.js#5273]
When using NineSlicePlane with CanvasRenderer, gaps appear between the tiles:
![capture](https://user-images.githubusercontent.com/13885303/49687626-0cec7a00-fb06-11e8-87b3-ba4e4eb124b4.PNG)

In Chrome everything looks fine.

... any advice on different settings I could fiddle with? ... already tried "roundPixels", does not make a difference.

**Comment by bigtimebuddy** [comment]
Could you verify what version of pixijs you’re using? Does this present in 4.8.3? Also, a JSfiddle would be extremely helpful. Thanks.

**Comment by wkamir** [comment]
Hi, thanks for the reply.

Here is the fiddle: (reproduces the glitch in firefox, not in chrome though):
https://jsfiddle.net/pyx7u2Ln/17/

... please note that I set the scale factor of the stage... I do this because I try to always utilize the maximum screen estate... I implemented my own auto-resize-mechanism.

If I don't set the scale factor, it looks ok in FF too...

**Comment by wkamir** [comment]
almost forgot - yes, it is in the latest version 4.8.3

**Comment by ivanpopelyshev** [comment]
Hack it , add round's inside. You wont get good result in canvas renderer if edges are fractions and not integers.

**Comment by wkamir** [comment]
Thanks for your reply ivan.... Could you please explain what you mean by "adding round's inside"?

**Comment by wkamir** [comment]
Ok, found a solution - rasterized it on a RenderTexture.
