### ISSUE TITLE
earcut has updated to 2.1.4 , please sync , thanks.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#5275]
earcut has updated to 2.1.4 , please sync , thanks.

**Comment by bigtimebuddy** [comment]
Any notable changes?

**Comment by finscn** [comment]
https://github.com/mapbox/earcut/pull/108

**Comment by englercj** [comment]
Looks like a really low-risk upgrade. Only one code change (that @finscn linked):

https://github.com/mapbox/earcut/compare/v2.1.3...v2.1.4
