### ISSUE TITLE
Browser-specific Masking Problem

### ISSUE THREAD

**Issue by elittle42** [pixijs/pixi.js#5281]
### Expected Behavior
Application of mask to a graphic should not be affected by the blend mode of the graphic or that of  any object in the graphic's nested hierarchy.
### Current Behavior
When using the canvas renderer, if a graphic has a child sprite whose blend mode is multiply and the graphic has an assigned mask, the graphic will not appear as if the mask is applied when viewing in Firefox. Graphic is displayed as expected in Chrome and Edge.
### Steps to Reproduce
1. Instantiate a sprite
2. Set the sprite's blend mode to multiply
3. Instantiate a graphic
4. Add the sprite from step 1 as a child of the graphic from step 3.
5. Instantiate another graphic and draw masking information
6. Set the mask property of the graphic from step 3 to the graphic from step 5
### Environment
- `pixi.js` version: 4.8.3
- Browser: Undesired behavior observed in Firefox 62.0.2
- Device: Windows desktop

I have created a [fiddle ](https://jsfiddle.net/jn1cgukh/3/)as a working example. When viewed in Chrome, the secondary image appears to have its mask applied and it only takes up a small portion of the canvas. When viewed in Firefox, the secondary image takes up much more of the canvas, as if the mask had not been applied.

**Comment by ivanpopelyshev** [comment]
Here we go

https://jsfiddle.net/Hackerham/ugbwzy3f/7/

**Comment by elittle42** [comment]
Awesome. Thanks for narrowing that down, and for filing the bug with Mozilla.

**Comment by ivanpopelyshev** [comment]
Looks like the issue was reported 2 years ago but nobody cares.
