### ISSUE TITLE
InteractionManager Cannot assign to read only property 'twist'

### ISSUE THREAD

**Issue by chirieac** [pixijs/pixi.js#5283]
Very often I get this error:
`Cannot assign to read only property 'twist' of object '#<PointerEvent>'`
pointing to this line:
https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1794

I wasn't able to find a specific way to reproduce since I only got the error logged from other users.

### Environment

- `pixi.js` version: _e.g. 4.8.2_
- Browser: _e.g. Chrome 70_
- Device: _e.g. Desktop_
- OS: _Windows 10_

**Comment by englercj** [comment]
Interesting.

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/twist) does describe a PointerEvent's `twist` property as read-only:

> The twist read-only property of the PointerEvent interface represents the clockwise rotation of the pointer (e.g., pen stylus) around its major axis, in degrees.

But that code runs for `MouseEvent` and specifically *not* `PointerEvent`:

```js
else if (event instanceof MouseEvent && (!this.supportsPointerEvents || !(event instanceof window.PointerEvent)))
```

Dangers of using `instanceof` I guess.

The users that are reporting this to you are on Chrome 70, Windows 10?

**Comment by chirieac** [comment]
@englercj I actually have reports for Firefox and other Windows versions too:
* Firefox 63, Windows 10 (`setting getter-only property "twist"`)
* Chrome 70.0.3538, Windows 8.1
* Chrome 69.0.3497, Windows 7

**Comment by andrewstart** [comment]
The error could get past the `if` if  `supportsPointerEvents` was set to false after pointer event listeners were added to the document. Alternatively, someone could have overwritten `window,PointerEvent` with something else (truthy, or overwritten after renderer init). I don't think that those browsers would be sending PointerEvents for mouse events.

**Comment by themoonrat** [comment]
Hmmmmm, interesting point. I remember solving an issue in html5gamedevs recently, caused by avpointerevent polyfill being used

**Comment by andrewstart** [comment]
In any case, the same check as the lines above it (`if (typeof event.pressure === 'undefined')`) should make it safe even if an overly aggressive polyfill is present,

**Comment by andyjessop** [comment]
Has there been progress on this bug?

**Comment by englercj** [comment]
No one has put in a PR to fix this yet. The only movement I am aware of is the discussion you see here.

**Comment by themoonrat** [comment]
@chirieac & @andyjessop - I remain convinced that this is occurring due to including a PointerEvent polyfill amongst your code. That was the case when it something similar was brought up on the help forums: http://www.html5gamedevs.com/topic/40671-no-touchevents-error/

As @andrewstart has mentioned, however, just using the same 'if undefined' caveats should stop this from happening even in polyfilled scenarios, so I'll put together a PR for that soon

**Comment by bigtimebuddy** [comment]
Updated build is available here: https://pixijs.download/v4.x/pixi.min.js

@chirieac or @andyjessop could you see if this resolves your problem? If it does, I'll publish a release to NPM.
