### ISSUE TITLE
PIXI Mesh/Spine issue ( canvas renderer )

### ISSUE THREAD

**Issue by neymanushka** [pixijs/pixi.js#5284]
Hello everybody.

There is an issue with PIXI spine when being rendered via Canvas ( forceCanvas: true )
Here is the preview.
![screenshot](https://user-images.githubusercontent.com/5113973/49796918-056be180-fd4f-11e8-91e4-4c09a2fa9044.png)

canvas on the left side, webgl on the right. can be reproduced and clearly visible on partially semitransparent texture. used example from trial Spine editor. 

[sources] https://www.dropbox.com/s/xpzijw3vfio8oi3/_spine_test.zip?dl=0

May be this is the similar issue [#3575]?

- `pixi.js` version: latest dev build
-  pixi-spine: 1.5.19
- Browser: Chrome / FF
- Device: Desktop

Thank you in advance!

**Comment by ivanpopelyshev** [comment]
Its not possible to do in canvas with transparency, you have to use cacheAsBitmap, or, better, temporary renderTexture to avoid that.

**Comment by neymanushka** [comment]
too bad. sprite spine worked perfect,but mesh :( terrible. thank you!
