### ISSUE TITLE
Version 4.8.3: Cloned graphics element end up with 0 dimensions

### ISSUE THREAD

**Issue by mathatan** [pixijs/pixi.js#5286]
After cloning an graphics element all dimension data, e.g. height and width will result 0 in the cloned element.

### Expected Behavior

Graphics dimensions to be cloned properly

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/zoINKofYwbxMf9WP~WQkL

### Environment

- `pixi.js` version: 4.8.3

**Comment by themoonrat** [comment]
@mathatan I just checked the playground, but it appears to be something unrelated to this issue?

**Comment by mathatan** [comment]
Apparently the playground has reseted...

**Comment by mathatan** [comment]
Updated with new playground link: https://www.pixiplayground.com/#/edit/zoINKofYwbxMf9WP~WQkL

Issue still persist even with the latest pixi versions, altho the height and width are now calculated by the graphics content. Still not cloned though.

**Comment by themoonrat** [comment]
thank you!
