### ISSUE TITLE
Is there a way to improve RenderTexture performance which changes constantly.

### ISSUE THREAD

**Issue by rkdrnf** [pixijs/pixi.js#5289]
Currently I'm implementing mini map feature in my game by using RenderTexture.

The problem is that minimap changes constantly, (for example, if player moves, player pointer on a minimap changes) and it makes minimap to be redrawed.
My minimap is size of 400 x 400 pixel, and there's some unignorable overhead on redrawing minimap.

Because minimap can be shown as small window at the corner of the the game, and as seperate big window if player press key, I must use easy way to draw same map on multiple different location at the same time on the screen. (So I chose RenderTexture to do this).

Is there any way to achieve this without using RenderTexture?
Something like drawing single displayobject directly to main framebuffer at multiple position.

### Environment
pixi v4

**Comment by ivanpopelyshev** [comment]
> Drawing single displayobject
I did that trick in a separate pixi fork, its too difficult.

Your case shouldn't be slow, did you implement any kind of culling to remove unseen geometries from a big map?

**Comment by rkdrnf** [comment]
When I do not redraw minimap, gpus takes about 4ms to render a frame, but when I redraw minimap  into rendertexture, it takes almost 8ms to render a frame. (It's not 8ms for every frame though, because redraw does not happen every frame)
What I draw on minimap and its order is as below
single 400 x 400 sprite -> single small sprite somewhere on 400 x 400 pixel map (player pointer which changes constantly) -> group of texts(counts to 15 ~ 20) -> dynamic graphic which has it's own filter applied(also constantly changes)
Is there anything that I can optimize inside this rendering flow?

**Comment by ivanpopelyshev** [comment]
Filters and masks can be slow, but in general, your setup is fine. 

I don't know why is it slow for you. You didnt tell my anything about testing device.

**Comment by rkdrnf** [comment]
![image](https://user-images.githubusercontent.com/1143159/50095313-dcb08400-0247-11e9-8446-ae719fb9459b.png)
This is my device. 
Measured gpu rendering time by chrome performance profiler.
I will check if there's something wrong with my setting.

**Comment by rkdrnf** [comment]
Just something popped up in my mind.
I think filter is using much gpu resources than it is expected. 
Because graphic object which filter is applied is bigger than 400 x 400 Canvas. it can be much bigger like 700 x 700 in its rectangular boundary (it's circle graphics object).
I read that pixi filter and it's applied object is rendered in separate framebuffer.
So it will be rendered to needlessly big extra framebuffer, which overuse gpu resource.
Is this scenario possible? and can it affect to performance?

**Comment by ivanpopelyshev** [comment]
how do you create pixi renderer?

**Comment by rkdrnf** [comment]
PIXI app is initialized as below. There's no specific settings for renderer, but I checked WebGLRenderer is used internally. (I didn't checked renderer for RenderTexture though, just thought it would be same as main renderer)
```
        this.app = new PIXI.Application({
            backgroundColor: 0x111111,
            antialias: false,    // default: false
            transparent: false, // default: false
            autoResize: true,
            resolution: 1,
            roundPixels: true,
        });
```

And I use custom filter using my custom shader which is implemented like this.
```
export default class StormFilter extends PIXI.Filter<{}> {
    constructor() {
        super(vertex, fragment);
    }
}
```

And for additional information, this is custom fragment shader i use for the filter above. 
```
varying vec2 vTextureCoord;
uniform sampler2D uSampler;

void main(void)
{
    vec4 c = texture2D(uSampler, vTextureCoord);

    if (c.r == 0.0) {
        gl_FragColor = vec4(0);
    } else {
        gl_FragColor = vec4(c.r, c.g, c.b, 0.1);
    }
}
```

**Comment by ivanpopelyshev** [comment]
btw, that's wrong because all colors have to be pre-multiplied.
gl_FragColor = vec4(c.rgb * 0.1, 0.1);
```

```

**Comment by Cristy94** [comment]
Are you using Text or BitmapText?

**Comment by rkdrnf** [comment]
I'm using PIXI.Text

**Comment by Cristy94** [comment]
From what I know PIXI.Text is pretty slow if text changes, try using a BitmapFont and I think your performance might be fixed. Or first test without the text and see if it's better.On 20 Dec 2018 03:11, 안준형 <notifications@github.com> wrote:I'm using PIXI.Text

**Comment by Dairnon** [comment]
It's very likely that the PIXI.Text (if constantly changed) is the issue. Alternatively if you have any other bitmap refreshing stuff, those could also cause issues.
