### ISSUE TITLE
Loader crashes: "Cannot read property 'XHR_RESPONSE_TYPE' of undefined"

### ISSUE THREAD

**Issue by pnobbe** [pixijs/pixi.js#5290]
When trying to load a file with the built in Loader, Pixi crashes internally in the blobMiddleware with the following error.

```
Uncaught TypeError: Cannot read property 'XHR_RESPONSE_TYPE' of undefined
    at Loader.blobMiddleware (blob.js:28)
    at Loader.js:639
    at async.js:45
```

### Expected Behavior
`XHR_RESPONSE_TYPE` to be defined.

### Current Behavior
The blobMiddleware seems to request a `default` property on `_Resource2` which is not defined:
![](https://i.gyazo.com/67d45b583f55b5fa66929f4c26b512ac.png)

![](https://i.gyazo.com/b386d1e1bede9a402c2525bbf5621859.png)

This automatically means ```XHR_RESPONSE_TYPE``` is also undefined.

### Possible Solution
No clue

### Steps to Reproduce
(not minimal config, but still rather thin)
https://github.com/pnobbe/pixi-dev/blob/master/src/index.ts 

### Environment

- `pixi.js` version: _4.8.3_
- `node` version: _10.14.2_
- `webpack` version: _4.27.1_
- `typescript` version: _3.2.2_
- Browser: _Chrome 70_
- Device: _Windows 10_

**Comment by englercj** [comment]
Have you tried this with the latest pixi `dev` branch? This should be fixed by resource-loader v2.2.2

**Comment by pnobbe** [comment]
> Have you tried this with the latest pixi `dev` branch? This should be fixed by resource-loader v2.2.2

Thanks for the advice, that will _probably_ fix it, however:

Maybe a dumb question, how do I specify a git repo as a dependency for npm? I tried adding `		"pixi.js": "pixijs/pixi.js#dev"` to my `package.json` which is how Google told me to do it, but that doesn't work.

**Comment by bigtimebuddy** [comment]
You unfortunately cannot install directly from npm like that. However, you can download the latest dev build here: https://pixijs.download/dev/pixi.js

**Comment by pnobbe** [comment]
Alright, I figured as much since I'd never seen anything directly referencing git in `package.json`.

Any eta for when the fix will be published?

**Comment by bigtimebuddy** [comment]
Looks like there's a IE bug that seems significant. As soon as we can track that down, I'll push out another release.

**Comment by bigtimebuddy** [comment]
Otherwise, this has been addressed. Closing issue.
