### ISSUE TITLE
Pixi.js 4.8.3 is crashing on loader in IE11. 4.8.2 was working (and other browsers too)

### ISSUE THREAD

**Issue by Friksel** [pixijs/pixi.js#5291]
Since the upgrade to pixijs 4.8.3 pixi loader is crashing during loading. This seems to only happen in IE11 (and lower IE). This was working without any problems with pixijs 4.8.2 on several (finished) projects I am running here. All projects before this update run, projects after the upgrade don't run.

There seems to be something in the 4.8.3 build, I excluded everything else during several testing here by turning back to an old git commit which was still and again fine in IE11 and then only upgraded pixijs after that to 4.8.3; resulting in the same errors again.

Unfortunetely IE11 is not the biggest star in nice error messages or even showing meaningful errormessages to begin with, but problem is that the loader seems to throw some 'unknown' DOM error  11 and then spriteframes from the single spritesheet can't be found.

### Expected Behavior
Browser is able to find sprite-frames after loading.

### Current Behavior
Browser is not able to find sprite-frames after loading.

### Possible Solution
Something changed in the security department or newer js-techniques IE11 don't support? Then changing it back or adding polyfills for IE perhaps?

### Steps to Reproduce
Upgrade to pixi.js. 4.8.3 and use the loader to load a spritesheet from json.

### Environment
- pixi.js version 4.8.3
- IE 11 and lower (tested on Chrome and Firefox and they work perfectly fine still)
- Desktop (Win 10)
- webpack 4.17.2
- nodejs (only for building with webpack): 8.11.1

I just saw there's another loader issue on 4.8.3 opened today here...
https://github.com/pixijs/pixi.js/issues/5290
... which can be a related issue, but I think this is a different one, because I don't get the error messages discussed in that issue and here 4.8.3. perfectly works still with projects on Chrome (71.0.3578.98 64b), Firefox (64.0) and also Ms Edge (42.17134.1.0). I didn't test it yet, but I'm positive things will run in android and iOS browsers too...  
...except for IE11 and lower...

**Comment by englercj** [comment]
Do you have a running example that reproduces this issue?

**Comment by Friksel** [comment]
I just downloaded the dev-branch as a zip, did a 'npm run lib' after unpacking, replaced the lib-folder in the node_modules/pixi.js with the new dev-version and did a test with both wepack-dev-server (dev-build) and a production build to dist on a project. The same error appears, so it looks like the current dev-build doesn't yet fix this.

**Comment by bigtimebuddy** [comment]
When you import the latest dev build are you doing “pixi.js/dist/pixi.js” not just “pixi.js”?

**Comment by Friksel** [comment]
I import from `pixi.js`

**Comment by englercj** [comment]
> these are client projects and I never share them

You don't have to, just head over to https://www.pixiplayground.com/ and create an example that reproduces the issue you are having.

**Comment by Friksel** [comment]
I just looked at this example which uses a loader: [https://pixijs.io/examples/#/basics/spritesheet.js](https://pixijs.io/examples/#/basics/spritesheet.js). And it is working in IE11. So that's some test.

So I decided to use that exact code only and put it in a Webpack/npm workflow with babel and es6. And suddenly the exact same demo does still work everywhere, but stops working in IE11 and below.
All npm modules are up to date and I set pixi to 4.8.3.

Strange thing is that with this project it doesn't matter if pixi is on version 4.8.3 or version 4.8.2. Somehow this project does not work in IE11 in both versions of pixi.
It is clearly hanging on the XMLhttpRequest.

I stripped the project down a lot and removed things like uglifyJs webpack plugin (although there's still one inside Webpack 4 probably still active, but pixi should be and was always able to handle that on default settings, cause there's no mangling or whatever and default settings are pretty safe. If applied). 

I also tested the dist build on a server online, because Internet Explorer can sometimes be a pain in the ass because of security when using local projects, although I adjusted everything to that and didn't have any complains on that no more in recents years, so that was just to be absolutely sure it's not a security issue. But that wasn't the case. Still no rotating airplane in IE11.

It's starting to look like something is off in combination between babel/webpack and pixiJs, because all the trouble starts when the online demo is made ES6 and transpiled through babel. But all my other projects (also pretty large and complex ones) are ALL running with the latest npm packages of everything and I update them all regularely. No problems at all on IE11 and below... except... 
...for ONLY projects running pixijs. And they were all running fine in IE before, so there must be something changed recently in pixi making it not work anymore, where all other libs (EaslJs, Threejs, jQuery etc) never stopped working with the exact same build system.

I also thought of a recent windows 10 update where Microsoft also adressed security on IE somehow, but it would be odd if only pixi projects would suffer from this, but not the ones in the demos on the pixi website online. Eventhough also EaselJs and Threejs projects use loaders probably the same way.

At the same time I can't understand why this project (the pixi spritesheet demo put in a webpack workflow) (and also one other pixi project here using the loader for sprite-frames) doesn't start working in IE11 when I downgraded pixijs to 4.8.2. So it's not sure this problem is introduced in 4.8.3 either than.
Strange. Even tried 4.8.1. Still the same. Crazy. I might be missing something here or this issue goes some versions back and I didn't see it somehow (A lot of my recent projects were all SVG and no raster-graphics, so that could be the case).

I can't really wrap my head around this for now. But hopefully this webpack setup helps you guys. In the zip you'll find the project in webpack that's running in Chrome and Firefox, but not in IE11.
[pxDemoWebpck-4.8.3.zip](https://github.com/pixijs/pixi.js/files/2687119/pxDemoWebpck-4.8.3.zip)

Unfortunately I'm pretty busy getting a deadline, because I converted a project from EaselJs to PixiJs because I like Pixi a lot and wanted to supply a WebGl project to this client, but then this problem occured, so I'm afraid I have to stick with the EaselJs version for now, which *thank god* works perfectly fine in IE11 down to even IE9! But I love pixi and rather have all my 'raster'-projects on pixi and hand the customer a nice webGL version instead! 

Long thread. Hope this helps. If I know more I let you know!
Now I have to work hard to make the deadline! (but if we know what caused this I might switch to pixi, 'cause I have 2 almost identical projects - one in easel and one in pixijs... :) )

**Comment by Friksel** [comment]
Well this looks strange inside pixijs in the dist production build.. `new XMLHttpRequest` without function brackets. Maybe this is the problem?:

![no function brackets](https://user-images.githubusercontent.com/3089978/50106359-f219b400-022f-11e9-8eea-d9c458a1c2c1.JPG)

BTW: To my surprise when using 'formatting document' (javascript formatter in Vs Code) this is suddenly corrected by the formatter obvously. I wouldn't expect a formatter to change the code itself:
![no function brackets - corrected](https://user-images.githubusercontent.com/3089978/50106493-43c23e80-0230-11e9-9dd3-859d57126354.JPG)

**Comment by Friksel** [comment]
Well, forget about the missing-bracket-thing. That isn't the issue here. Just did a test on a project without webpack/babel/es6/build workflow on the rotating-plane demo with loading pixi.min.js in an ordindary script tag and that demo still runs fine in IE11 even with missing-brackets in the minified pixi.

**Comment by englercj** [comment]
Braces are not required in JS to call a constructor. `new A` and `new A()` are equivalent. The minifier removed the braces to save space since they are not necessary.

Is this the issue you are encountering? https://github.com/englercj/resource-loader/issues/125

**Comment by Friksel** [comment]
Yes!! Great, that did the trick! Now it works in IE11 in the webpack project I sent here. I'm possitive it will work in my other pixi-projects too, 'cause I recognise the .timeout issue from the other issue you fixed.

Great to know resource-loader is a different packge. I didn't know about that. I thought it was only about pixi.js and pixi-gl-core modules in pixiJs. Guess that also explains why sometimes downgrading to pixi 4.8.2 did the trick and the other time didn't (probably not up-/downgrading the resource-loader with pixi, leaving the issue at the loader). Great info to know now.

Thanks a lot!! @englercj

**Comment by Friksel** [comment]
> Braces are not required in JS to call a constructor. 

Yes, I figured you don't have these kind of problems in the lib. Just didn't know about this rule. Thanks for the info. Everyday a great day to learn :)

**Comment by Friksel** [comment]
Everything is working now with the current dev-branch of the resource-loader, so happily closing this!

**Comment by englercj** [comment]
v2.2.3 is now released which includes this fix.
