### ISSUE TITLE
How to render synchronously (not use requestAnimationFrame)

### ISSUE THREAD

**Issue by lk-jeffpeck** [pixijs/pixi.js#5299]
I am trying to use Pixi with OpenSeadragon, where the canvas should update synchronously when OpenSeadragon triggers the `update-viewport` event.

Even though pixi is rendering everything very fast (under 5ms), there is still a lag, which appears to be due to rendering happening asynchronously.

I tried searching for information about this, but the behavior appears to be different between the current version of pixi and previous (< v4?)

So, I thought I would just ask to be clear: is there any way to render synchronously?

Thanks!

**Comment by lk-jeffpeck** [comment]
If pixi is not suited for this, or it is recommended to use an earlier version, I would appreciate hearing that as well. I am just trying this out at the moment to see if pixi.js can be a viable solution for an OpenSeadragon overlay to quickly render thousands of markers.

**Comment by ivanpopelyshev** [comment]
Why do you need it as a texture in pixi? Just put it above or below webgl canvas.

Its not pixi problem, its webgl. If you are aware of how texture is uploaded in TextureManager, you can hack it and if you know how to do it fast using basic webgl operations - you should hack TextureManager. In v5 its easier, there's abstraction called "texture-resource".

Ask someone who knows both OpenSeaDragon lib and webgl context, if its possible to synchronize it fast enough.

**Comment by englercj** [comment]
> which appears to be due to rendering happening asynchronously.

What is it that you mean by this? When you call `renderer.render()` we do all the rendering that can happen synchronously. It may take some amount of time before the GPU processes all the commands, but that is the same as every GPU application.

What isn't working for you, and what are you trying to accomplish?

**Comment by lk-jeffpeck** [comment]
I am not even calling `renderer.render()`.

I have a list of markers all with the same texture (for now), and I add them them to the stage like this:
```
     // remove previous sprites
     this.sprites.forEach((sprite) => {
       this.stage.removeChild(sprite);
     });
 
     this.sprites = [];
     
     // Draw new sprites
     markers.forEach((marker) => {
       const sprite = new PIXI.Sprite(this.texture);
       sprite.x = marker.x;
       sprite.y = marker.y;
       this.stage.addChild(sprite);
       this.sprites.push(sprite);
     });
```

It updates, but not in sync with the view.

Other approaches that I have used (direct canvas drawing, svg overlay with d3, and a webgl-based approach using Two.js) all draw to the overlay synchronously so as you pan and zoom the overlay does not drag behind. With pixi, using the above code.

Is there a way to append everything to the stage and call `.render()` whereby it will asynchronously draw everything?

This is my first time trying pixi.js so please excuse a possibly obvious question.

**Comment by englercj** [comment]
I assume you are using `PIXI.Application`, don't. Just make your renderer and render a container.

**Comment by lk-jeffpeck** [comment]
Oh wow, yes, thank you!

This is exactly what I was looking for.

I know that you are saying that "there is no asynchronous drawing going on", but when I did this through `PIXI.Application` and not calling `.render()` there _was_ a lag as a panned and zoomed.

With your suggestion, those issues are gone!

Thank you for the help!

**Comment by bigtimebuddy** [comment]
Application also has an argument to turn off automatic rendering (`requestAnimationFrame` loop):

```js
const app = new PIXI.Application({
  autoStart: false
});
app.render(); // manual render
```

**Comment by englercj** [comment]
I wasn't aware of that, good shout @bigtimebuddy
