### ISSUE TITLE
Question:how to create texture from buffer?

### ISSUE THREAD

**Issue by johnny19941216** [pixijs/pixi.js#5300]

**Comment by ivanpopelyshev** [comment]
Its possible in v4 through hacks, you have to hack `TextureManager.updateTexture` method.

Its done in v5 through texture resources, please wait for v5 :)

**Comment by bigtimebuddy** [comment]
In v5, you can use `PIXI.Texture.fromBuffer` (see http://pixijs.download/dev/docs/PIXI.Texture.html#.fromBuffer)

No plans to add in v4. Closing issue.
