### ISSUE TITLE
Cloned Graphics does not draw original graphics lines.

### ISSUE THREAD

**Issue by nagromlin** [pixijs/pixi.js#5303]
### Expected Behavior
Cloned Graphics draw original Graphics lines.

### Current Behavior
Cloned Graphics does not draw original Graphics lines.

### Possible Solution
quickfix: Setting `lineAlignment` of each clone graphic `graphicsData` works. 

Clone `lineAlignment` property in `GraphicsData.clone` :

    diff --git a/src/core/graphics/GraphicsData.js b/src/core/graphics/GraphicsData.js
    index 382074d7..88281694 100644
    --- a/src/core/graphics/GraphicsData.js
    +++ b/src/core/graphics/GraphicsData.js
    @@ -114,7 +114,8 @@ export default class GraphicsData
                 this.fillAlpha,
                 this.fill,
                 this.nativeLines,
    -            this.shape
    +            this.shape,
    +            this.lineAlignment
             );
         }

### Steps to Reproduce
Create a Graphics, draw lines in it with lineTo, clone it.
https://www.pixiplayground.com/#/edit/97PKPjsg5PKWx~g7s34Vy

### Environment
- `pixi.js` version: 4.8.4 e4835a3b00
- Browser: Chromium 71
- Device: Desktop

**Comment by bigtimebuddy** [comment]
Fixed with the PR (https://pixijs.download/fix-graphics-clone/pixi.min.js) above:
https://www.pixiplayground.com/#/edit/9aQhrPmPFu1pV3Hd3QHUh

Thanks for pointing this out.
