### ISSUE TITLE
Font rendered choppy and unclear when scaled down

### ISSUE THREAD

**Issue by louieyuen** [pixijs/pixi.js#5304]
Your issue may already be reported! Please search [existing issues](../) before creating one.

### Expected Behavior
Smaller text should appear crisp around the edges, similar to the examples below.

### Current Behavior
Large fonts that has been scaled down is showing blurry and unclear.

### Possible Solution
Rendering engine issue.

### Steps to Reproduce
Please refer to this example:
http://jsfiddle.net/2pb6myk8/1/

We have increased the font size and scaled it down in order to provide clearer text, however, it still looks blurry compared to the text below.

### Environment

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by englercj** [comment]
There is a big difference between rendering text at a large font size then scaling the resulting image and drawing the text at a small font size.

Those two things will almost never look the same, and there isn't anything we can really do to make them look the same.

**Comment by englercj** [comment]
Use a different font rendering technique such as SDFs. We rasterize text which is fast and good as long as you don't scale, but other rendering techniques exist specifically to solve the issue you are having.

There is an SDF text plugin someone made: https://github.com/PixelsCommander/pixi-sdf-text
as well as MSDF techniques that can make it better: https://github.com/Chlumsky/msdfgen

**Comment by louieyuen** [comment]
I will definitely look into those options. Thank you for all your help!
