### ISSUE TITLE
How to use dynamic svg as a texture?

### ISSUE THREAD

**Issue by mvk843** [pixijs/pixi.js#5307]
Hello!

How can I pass dynamic generated (from text) texture here?
PIXI.mesh.Rope(PIXI.Texture.from(???), points);

I tried
PIXI.mesh.Rope(PIXI.Texture.from(document.getElementById('svg').children[0]), points),
where ('svg').children[0] is svg tag in a div tag, svg generated by svg.js.
But I think it's not correct because it's not svg picture url (with static svg file it's working).
What can i do?

**Comment by ivanpopelyshev** [comment]
`Texture.fromCanvas()` + `baseTexture.update()` every frame. Speed will depend on texture size, because `texImage2D` will be called every frame.

**Comment by bigtimebuddy** [comment]
Seems to have been answered. Closing.
