### ISSUE TITLE
Safari 12 Restarting when using multiple LineTo calls before endFill

### ISSUE THREAD

**Issue by msucharski** [pixijs/pixi.js#5308]
### Current Behavior
Safari 12.0.2 will restart with a message "This website has reloaded because of a problem", and then after restarting several times will show a page displaying "A problem has repeatedly occurred with (name of website)"

### Possible Solution
To fix this problem in the short-term, I've had success with following each call to lineTo with moveTo at the same coordinates. (In my case I'm only drawing lines, and have no need for an actual fill.)

### Steps to Reproduce
Using Safari 12.0.2, draw lines with a PIXI.Graphics using code similar to the following: 
 
_ctx.clear();
_ctx.beginFill("#ffffff", 1);
_ctx.lineStyle(2, "#ffffff");
_ctx.moveTo(0, 0);
_ctx.lineTo(0,100);
_ctx.lineTo(100,100);
_ctx.lineTo(100, 0);
_ctx.lineTo(0, 0);
_ctx.endFill(); 

Call this and render it every frame. 

Sometime within 5 seconds to 1 minute Safari 12.0.2 will restart with the error mentioned above. 

### Environment

- **`pixi.js` version**: 4.3.0
- **Browser & Version**:Safari 12.0.2
- **OS & Version**: MacOS 10.13.6

**Comment by bigtimebuddy** [comment]
Create an example of this:
https://pixiplayground.com/#/edit/s899WR_0XaP~awZ5CQfly

Does this reproduce for you, @msucharski? I cannot get this to reproduce on v4.8.4 (with the same Browser & OS versions).

**Comment by bigtimebuddy** [comment]
Is there any follow up @msucharski? If you cannot reproduce the issue, please close. Thank you.

**Comment by msucharski** [comment]
No, I cannot reproduce in the playground. There must be some additional steps that are required for the results I'm seeing in my own app.
