### ISSUE TITLE
Mesh - update texture from atlas frame is not working (cached uvs?)

### ISSUE THREAD

**Issue by EneaEntertainment** [pixijs/pixi.js#5312]
### Expected Behavior
Texture to be updated

### Current Behavior
Mesh texture is not updated, when assigning another texture frame from same atlas

### Possible Solution
update Mesh UVs if texture frame has changed

    set texture(value)
    {
        if (this.shader.texture === value || !value.valid)
        {
            return;
        }

        if (this.shader.texture.frame !== value.frame)
        {
            value.updateUvs();
        }

        this.shader.texture = value;
    }

### Steps to Reproduce
- run provided example 
- upper button is changing it's texture on mouse over
- bottom button is not

### Environment

- **`pixi.js` version**: 5.0.0-alpha.3
- **Browser & Version**: 71.0.3578.98
- **OS & Version**: Win7
- **Running Example**: https://www.pixiplayground.com/#/edit/w1XiifwuHEmeG95ZwFr6r

**Comment by ivanpopelyshev** [comment]
I think its fixed in `dev` , and we'll publish 5.0.0-beta soon :)

**Comment by EneaEntertainment** [comment]
nope, doesn't work with latest alpha 3 build.. looking forward to beta release :)

**Comment by ivanpopelyshev** [comment]
ok, its NineSlicePlane bug.
