### ISSUE TITLE
Migrating to usage of NPM scope packages

### ISSUE THREAD

**Issue by marcus-sa** [pixijs/pixi.js#5313]
After not having looked at the Pixi repository for a while, I see that you've moved on to mono repositories and pushed them into a NPM scope.
So is there a migration guide for how to properly upgrade to use that?
Because currently `import * as PIXI from 'pixi.js';` just doesn't look well in a TS project and that the `PIXI` scope is globally available from outside your bundle probably isn't a great idea.

**Comment by englercj** [comment]
If you are using npm, you should be able to install each individual package that is important to you and include them as you need.

Otherwise, unless I'm mistaken, `import * as PIXI from 'pixi.js'` should still work.
