### ISSUE TITLE
[.WebGL-0x28b1ecce9e00]GL ERROR :GL_INVALID_ENUM : glGetIntegerv: pname was GL_MAX_SAMPLES_ANGLE

### ISSUE THREAD

**Issue by Leigh-M** [pixijs/pixi.js#5318]
Chrome 70.0.3538.77, Ubuntu 18 Linux is throwing a warning on bare bones setup, code as follows: 

`<!DOCTYPE html>
<meta charset="utf-8">
<title>Demo</title>
<body>
<script src="./pixi/pixi.min.js"></script>
<script>
  let Application = PIXI.Application,
      Container = PIXI.Container
  let app = new Application({ 
      width: 2102, 
      height: 796
    }
  );
  document.body.appendChild(app.view);
</script>
</body>`

Error warning in console: [.WebGL-0x28b1ecce9e00]GL ERROR :GL_INVALID_ENUM : glGetIntegerv: pname was GL_MAX_SAMPLES_ANGLE

What is the cause of this and the best solution?

Thanks

**Comment by englercj** [comment]
Looks like an ANGLE bug.

**Comment by bariscicek** [comment]
@englercj I have a similar error but not from pixiJS but from CesiumJS. So I am wondering source of this error is from Chrome or display driver?
