### ISSUE TITLE
PIXI v5 appears to run slower then v4 in bunnymark

### ISSUE THREAD

**Issue by Dairnon** [pixijs/pixi.js#5319]
### Expected Behavior
I expected bunnymark for v5 to run the same speed as v4 at the very least.
### Current Behavior
Currently it appears that v4 runs a bit faster then v5

On my computer with 100,000 bunnies. I get the following avg fps

4.8.4 :  18-19fps

5.0.0-alpha.3 : 13-16
### Possible Solution

Ivan suggested that it could be texture binds due to v4 boundTextures optimization maybe not being implemented all the way in v5, but the reality is we don't really know. 

### Steps to Reproduce
Set these settings in bunnymark 
https://pixijs.io/bunny-mark/

StartBunnyAmount:  100,000
 clearBeforeRender: on
### Environment

- **`pixi.js` version**: _e.g. 5.0.0-alpha.3
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Windows 10
- **Running Example**: https://pixijs.io/bunny-mark/

**Comment by GoodBoyDigital** [comment]
Thanks for sharing @Dairnon !

This PR should bring things closer (https://github.com/pixijs/pixi.js/pull/5320), turns out we were antialiasing is true for all things v5 at the mo in dev branch.

Let us know if that makes a difference for ya! 

Cheers!

**Comment by Dairnon** [comment]
19-20 v4.8

16-17 dev

It seems improved by 1 or 2 fps overall

**Comment by bigtimebuddy** [comment]
We recognize there are different performance advantages for v5 over v4, and that bunny-mark isn’t the most precise or real-world example. Trying to performance optimize around 100K sprites is arguably not as useful. We are going to be working on another approach to bunny-mark, which allows the user to see the impact of things like masks, filter, text and other performance limiting things. @Dairnon has agreed to help in the endeavor. Closing this for now.

**Comment by Cristy94** [comment]
Any updates on this? Is it worth spending the time to update from v4 to v5 if your only concern is performance?

**Comment by themoonrat** [comment]
I created https://themoonrat.github.io/webgl-benchmark/ to test a few scenarios against various versions of PixiJS and Phaser.

With the multi-texture scene, there's only a 1 fps difference when I throw 50k sprites at it on my PC. But then use the complex graphics scene, and you see a massive advantage to v5, as it added code to allow these to be batched when rendered. Anything rendered with meshes can also take advantage of this in v5.

So as bigtimebuddy said, it's not quite so straight forwards as in that original bunnymark! If you use meshes & complex graphics, then you'd definitely see a performance improvement in v5. If not, then it's trickier to say, and the only way to find out is to give it a go for your scenarios!

**Comment by Cristy94** [comment]
From what I remember when testing for performance issues I noticed that having a lot many containers was pretty slow in PIXI v4 as each frame all the transforms were re-calculated for all sprites/nested containers.  I remember that the `updateTransform` function was taking most CPU time (especially when using particles without the particle container). Was this improved in V5?
