### ISSUE TITLE
[issue] 2 sprite with same size & position

### ISSUE THREAD

**Issue by shawnmypark** [pixijs/pixi.js#5334]
demo - https://jsfiddle.net/ririz/mL3ck20s/

2 sprite with same position, size.

index 0 - ff0000 color
index 1 - ffffff color

You can see red-line ( index 0 sprite ).

![image](https://user-images.githubusercontent.com/17754709/50746249-71b80300-1271-11e9-9b79-123d057e138d.png)

### Environment

- **`pixi.js` version**: 4.7.1 ~ 4.8.4, WebGL only
- **Browser & Version**: all
- **OS & Version**: windows
- **Running Example**: https://jsfiddle.net/ririz/mL3ck20s/
- **display**: not retina display only

**Comment by ivanpopelyshev** [comment]
Its a known webgl problem. Turn off antialiasing.

We need WebGL2 and MXAA to fix that.

**Comment by ivanpopelyshev** [comment]
Relevant discussion: https://github.com/open-source-flash/open-source-flash/issues/107

**Comment by shawnmypark** [comment]
Oh my god! I need antialias = true
Thx for comment.
