### ISSUE TITLE
PIXI.RenderTexture not wrapping

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi.js#5335]
I am generating a RenderTexure by drawing multiple sprites on it, I then want to use this texture on a mesh and set `renderTexture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT; ` but it doesn't seem to work.

The RenderTexture is a power of 2 (1024x1024), and the wrapping works if I replace the render texture with a basic asset loaded Texture.

I am now trying to somehow convert the RenderTexture to a normal texture (maybe it solves the issue), but I didn't find any way.

Any ideas why wrap mode would not work if the base texture comes from a RenderTexture?

- **`pixi.js` version**:  4.8.3

**Comment by Cristy94** [comment]
I managed to go around this issue by creating a normal Texture like this:

`const normalTexture = PIXI.texture.fromCanvas(app.renderer.extra.canvas(renderTexture);`

Setting the `wrapMode` on this newly generated texture worked as expected.

The question/issue still stands: Why doesn't `wrapMode` work if the texture used is a `RenderTexture` instead of a `Texture` (even though it extends it).

**Comment by ivanpopelyshev** [comment]
It works in v5, as for v4 i remember that I made code for it , somewhere on html5gamedev's forum. Its possible.

**Comment by Cristy94** [comment]
But when I create the texture I create it of size (1024,1024), do I have to manually set the `isPowerOfTwo` flag?

**Comment by ivanpopelyshev** [comment]
dont forget to switch mipmap to false if you manage to make it power-of-two

**Comment by Cristy94** [comment]
I never used mipmap in any way (unless they're on by default).

I understand focus is on v5, but for now I am still forced to use v4 for my current project, so I was curious if there's at least a better solution for this issue (also because I didn't find anything on Google, so this might also help others).

So I guess the solution for now would be to manually set `isPowerOfTwo` somehow, what would be the best way to fix that for the playground demo above?

**Comment by ivanpopelyshev** [comment]
yes

**Comment by Cristy94** [comment]
I actually tried to replace my texture generation code with just setting the `isPowerOfTwo` flag and using directly the RenderTexture. It seemed to work at first (wrapping works) but then I started having **strange issues** (when the game was scaled down parts of the mesh started disappearing, the entire mesh being gone after a specific window size).

**Comment by ivanpopelyshev** [comment]
because you didnt set `mipmap` to `false`. Its true by default, and with power-of-two it actually enables mipmapping, but there are no mip levels for renderTexture.

**Comment by Cristy94** [comment]
Thanks! It worked after setting `isPowerOfTwo` to `true` and `mipmap` to false (first fixes wrapping, second fixes scaling issues).

**Comment by Cristy94** [comment]
I have another issue with this, the problem is now that the mesh looks jagged, not aliased. I realised it's the scale mode, it was set to nearest, I set it to LINEAR but it didn't fix the issue.

Looking at the draw calls I noticed that the only different (between my custom texture generation and RenderTexture) was the texture minFilter:

Custom texture:
![image](https://user-images.githubusercontent.com/1384885/51668823-5401d200-1fc3-11e9-8d60-0289f2378e48.png)


RenderTexture:
![image](https://user-images.githubusercontent.com/1384885/51668850-611ec100-1fc3-11e9-8b9c-8a8d1e3c3810.png)


This makes sense, as I set mipmap to false, but because of this the quality is worse. Any solution to also fixing the minFilter value?

**Comment by Cristy94** [comment]
Any other suggestion on how to make a `RenderTexture` behave as a normal `Texture`?

My initial solution to copy the texture using `renderer.extract.canvas` has issues with `premultipliedAlpha` https://github.com/pixijs/pixi.js/issues/2695 

If I use the `RenderTexture` as explained above (isPowerOfTwo to true and mipmap to false), the mesh looks jagged.

**Comment by Cristy94** [comment]
Managed to fix "everything" by keeping the `extract.canvas`, but adding this monkey-patch:

```
/**
 * Neutralizes pre-multiplied alpha in pixels array
 * @param {Uint8Array} pixels input
 */
PIXI.extract.webgl.postDivide = function (pixels) {
    for (let i = 0; i < pixels.length; i += 4) {
        const alpha = pixels[i + 3];

        if (alpha) {
            pixels[i] = Math.round(Math.min(pixels[i] * 255.0 / alpha, 255.0));
            pixels[i + 1] = Math.round(Math.min(pixels[i + 1] * 255.0 / alpha, 255.0));
            pixels[i + 2] = Math.round(Math.min(pixels[i + 2] * 255.0 / alpha, 255.0));
        }
    }
}

/**
 * Neutralizes pre-multiplied alpha in pixels array
 * @param {Uint8Array} pixels input
 */
const BYTES_PER_PIXEL = 4;
PIXI.extract.webgl.prototype.canvas = function (target) {
    const renderer = this.renderer;
    let textureBuffer;
    let resolution;
    let frame;
    let flipY = false;
    let renderTexture;
    let generated = false;

    if (target) {
        if (target instanceof PIXI.RenderTexture) {
            renderTexture = target;
        }
        else {
            renderTexture = this.renderer.generateTexture(target);
            generated = true;
        }
    }

    if (renderTexture) {
        textureBuffer = renderTexture.baseTexture._glRenderTargets[this.renderer.CONTEXT_UID];
        resolution = textureBuffer.resolution;
        frame = renderTexture.frame;
        flipY = false;
    }
    else {
        textureBuffer = this.renderer.rootRenderTarget;
        resolution = textureBuffer.resolution;
        flipY = true;

        frame = TEMP_RECT;
        frame.width = textureBuffer.size.width;
        frame.height = textureBuffer.size.height;
    }

    const width = frame.width * resolution;
    const height = frame.height * resolution;

    const canvasBuffer = new PIXI.CanvasRenderTarget(width, height, 1);

    if (textureBuffer) {
        // bind the buffer
        renderer.bindRenderTarget(textureBuffer);

        // set up an array of pixels
        const webglPixels = new Uint8Array(BYTES_PER_PIXEL * width * height);

        // read pixels to the array
        const gl = renderer.gl;

        gl.readPixels(
            frame.x * resolution,
            frame.y * resolution,
            width,
            height,
            gl.RGBA,
            gl.UNSIGNED_BYTE,
            webglPixels
        );

        // add the pixels to the canvas
        const canvasData = canvasBuffer.context.getImageData(0, 0, width, height);

        PIXI.extract.webgl.postDivide(webglPixels); // <-- THIS WAS MONKEY PATCHED

        canvasData.data.set(webglPixels);

        canvasBuffer.context.putImageData(canvasData, 0, 0);

        // pulling pixels
        if (flipY) {
            canvasBuffer.context.scale(1, -1);
            canvasBuffer.context.drawImage(canvasBuffer.canvas, 0, -height);
        }
    }

    if (generated) {
        renderTexture.destroy(true);
    }
    // send the canvas back..
    return canvasBuffer.canvas;
}
```
