### ISSUE TITLE
Handling 404 on file loading.

### ISSUE THREAD

**Issue by simeon-uxiliary** [pixijs/pixi.js#5336]
### Expected Behavior
loader.onError should run the passed function if the resource receives a 404.

### Current Behavior
There is no way to handle a 404 resources error.

### Possible Solution
Make onError run if the resources results in a 404.

### Steps to Reproduce

const videoLoader = new PIXI.loaders.Loader();

videoLoader.add("PATH/TO/ASSET");
videoLoader.onError(() => console.log("error")); // Doesn't run
videoLoader.onComplete(() => console.log("complete")); // Doesn't run
videoLoader.onProgress(() => console.log("progress")); // Doesn't run
videoLoader.onLoad(() => console.log("load")); // Doesn't run
videoLoader.use(() => console.log("Does this run?")); // Doesn't run

videoLoader.load((loader, resource) => {
  console.log(loader);  // Doesn't run
});

### Environment

- **`pixi.js` version**: 4.8.4
- **Browser & Version**: Chrome 71.0.3578.98
- **OS & Version**: Mac OS 10.14.2

**Comment by bigtimebuddy** [comment]
**resource-loader** uses onError as a [mini-signal](https://github.com/Hypercubed/mini-signals) so you need to do something like this to handle the error:

```js
videoLoader.onError.add((err, loader, resource) => {
  // handle error here
});
```

Example: https://jsfiddle.net/bigtimebuddy/x2hydc3m/

**Comment by simeon-uxiliary** [comment]
Yup my bad sorry.

**Comment by bigtimebuddy** [comment]
No worries, I'm sure other people will bump into that issue too and now there's an issue folks can search.

**Comment by simeon-uxiliary** [comment]
So while I definitely got this to work with image files I can't seem to get it to work for video files.

```javascript
      const videoLoader = new PIXI.loaders.Loader();
      videoLoader.add("Path/TO/VIDEO");
      videoLoader.onComplete.add(this.setupVideo);
      videoLoader.onError.add(this.setupStaticHomeBackground);
      videoLoader.load();
```

**Comment by bigtimebuddy** [comment]
I would encourage you to add an issue to https://github.com/englercj/resource-loader since this is the library we are using for the Loader.  If I had to guess maybe resource-loader isn't handling `<video>` element load error events correctly. Not sure tho but filing an issue over there seems like the right approach.

**Comment by aaclayton** [comment]
Experiencing the same issue for video resource loads. A 404 does not get handled in the error callback which can prevent your loader request from ever finishing.

**Comment by leduyhoang1994** [comment]
Any update ?
