### ISSUE TITLE
Refactor renderTextureSystem and frameBufferSystem names in v5

### ISSUE THREAD

**Issue by Dairnon** [pixijs/pixi.js#5337]
When building my own renderer I noticed some confusing variable names. 

**RenderTextureSystem** uses the name `renderTexture` 

**FrameBufferSystem** uses the name `framebuffer`.

This adds a lot of confusing, especiually when reading or writing lines like this. 
`this.renderer.framebuffer.bind(baseTexture.frameBuffer, destinationFrame);` the first frame buffer is actually system... while the baseTexture framebuffer is the actual frame buffer

`this.renderTexture.bind(renderTexture);` this is really confusing cause this.renderTexture is actually system, while the other renderTexture is the actual renderTexture

We also should add a getter in renderTexture to access the frameBuffer's other colorTextures easier...

Currently its really long `renderTexture.baseTexture.framebuffer.colorTextures`

**Comment by ivanpopelyshev** [comment]
Its for internal plugins usage, system names are fine.

Though that long line needs shortcut.

**Comment by Dairnon** [comment]
can we get away with a shorter name for systems that can't be confused for what it manages? 

`this.renderer.renderTexture.bind(rt1);` 

this to a viewer would imply that a renderTexture is binding a renderTexture still (even if the name is just rt1) 

`rendTextureSystem`

or `buffFrameSystem`

**Comment by Dairnon** [comment]
Do you think its worth refactoring the names to be easier to understand for custom renderer development? Personally I think it help with less confusion. 

We at the very least should try shortening the names more as like @ivanpopelyshev  said

`this.renderer.renderTexture.bind(rt1);` even tho renderTextures may have shorter names, they still end up having long lines.

**Comment by themoonrat** [comment]
@bigtimebuddy Think this naming issue is something to decide on before an official v5 release? As I doubt we'd want to be changing that after

**Comment by bigtimebuddy** [comment]
I’m not that worried about this for v5, this type of thing is easy to change because it mostly involves a simple deprecation. Not critical.
