### ISSUE TITLE
Strange image texture distortion

### ISSUE THREAD

**Issue by animanathome** [pixijs/pixi.js#5338]
When rendering an image I'm sporadically getting the following visual distortion which I can't see in the original image. Here I'm just wondering if anyone has seen this issue before and what the root cause is. 

![strange_image_render_issue](https://user-images.githubusercontent.com/2272141/50803135-4ac3f600-129e-11e9-89d6-21ef9be8d24c.png)

Thanks

**Comment by bigtimebuddy** [comment]
Could you please provide more information, like PixiJS version, browser, OS and graphics hardware. Or an example that demos the problem. Also what does “sporadically” mean? How often is this happening? All images or just this one? Help us, help you.

**Comment by animanathome** [comment]
@bigtimebuddy this is the only information I can provide:
OS: Windows 10
Browser: Firefox 65.0
PIXI: 4.8.2
Code: new PIXI.Sprite(PIXI.Texture.fromImage(source_url))
And I haven't been able to quantify how often this actually happens. That's why I went with sporadically. 

@ivanpopelyshev this is useful and at least gives me something to further look into. I was also wondering if we know how PIXI behaves when the system is running out memory. Do you have any insights on that? thanks.

**Comment by ivanpopelyshev** [comment]
Yeah, webgl crashes if there's not enough memory :)

**Comment by animanathome** [comment]
I haven't able to reproduce this issue myself. Otherwise, I would have created a demo. One of our users send us this screenshot.

**Comment by Dairnon** [comment]
I think until we can get a reproducible demo of the issue, we can't really do much about it. 

Please open a new Issue if you are able to reproduce the problem again.
