### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by grasilife** [pixijs/pixi.js#5346]
inti() {
      let thisp = this;
      var app = new PIXI.Application({
        backgroundColor: 0xf0f3fa,
        forceCanvas: true
      });
      thisp.app = app;
      document.getElementById('pixiview').appendChild(app.view);
      thisp.app.renderer.resize(window.innerWidth, window.innerHeight - 65);
    },
my The display has a resolution of 1080p;
execute init function High CPU utilization is 37%;
remove thisp.app.renderer.resize(window.innerWidth, window.innerHeight - 65)  CPU usage is down 15%
resize methods if defective?

### Environment

- **`pixi.js` version**: _e.g. 4.8.2_
- **Browser & Version**: _e.g. Chrome 71_
- **OS & Version**: _e.g. windows 7_
- **Running Example**: _url_

**Comment by englercj** [comment]
> resize methods if defective?

Resizing it makes it bigger. Bigger canvases have to draw more pixels. The canvas renderer isn't necessarily GPU accelerated and may use software (CPU) rendering (up to the browser).

**Comment by djmisterjon** [comment]
i just test , and no issue on my side.
this can maybe help you to make your own method for resize your projet with your resolutions.
https://github.com/djmisterjon/PIXI.ProStageEditor/blob/65a1f0321257187fb7d4f6da32ba881301529eeb/js/core/app.js#L74

**Comment by bigtimebuddy** [comment]
@grasilife do you have any other information to share or did you resolve your issue?

**Comment by grasilife** [comment]
he

> @grasilife您是否有任何其他信息要分享或您是否解决了您的问题？

hello,If you use websocket to continuously push data, there will still be a memory leak in the line drawing and update points
