### ISSUE TITLE
Pixi v4 WebGL detection failure on WPEWebkit

### ISSUE THREAD

**Issue by TomMettam** [pixijs/pixi.js#5347]
### Current Behavior

When running on WPEWebkit, pixi.js does not detect WebGL support correctly and needlessly falls back to the Canvas renderer.

The WPEWebkit browser **does** support WebGL (it renders the HelloRacer demo quite well).

### Expected Behavior

Pixi.js should detect the availability of WebGL on this platform and should use it.

### Possible Solution

Workaround:

```
this.app = new PIXI.Application({
            autoStart: false
});
this.app.renderer = new PIXI.WebGLRenderer();
this.app.start();
```

### Steps to Reproduce

Use Pixi.js v4 on WPEWebkit (in my case, on the Raspberry Pi 3b+)

### Environment

- **`pixi.js` version**: 4.8.5
- **Browser & Version**: WPEWebkit 7431ea406a97
- **OS & Version**: Yocto Linux

**Comment by englercj** [comment]
This may be due to the stencil support which pixi considers the absence of a failure (because we use it for masking and Graphics). Does removing that from the check function do what you would expect?

**Comment by TomMettam** [comment]
Yes, it does. Is there any possibility that this could be allowed as a configuration option?

**Comment by themoonrat** [comment]
I'm not sure it's something that should be an option IMO .... a flag that could cause areas of the libs to just not work. And then we'd get bugs coming in :/

You could always override the `PIXI.utils.isWebGLSupported` function in your code, before creating the renderer, to force it to be true? Or to do the same logic but take out the stencil requirement.

**Comment by TomMettam** [comment]
Well, a flag which is specifically for that purpose... disableStencil, for example..  seems quite intuitive. Yes, I can work around it, of course.

**Comment by bigtimebuddy** [comment]
I think we’d be unlikely to remove the stencil requirement since it is essential for the pieces @englercj described above.  Also, WPEWebkit is not really a big enough market share for us to  officially support. The workaround will have to do for now but please share any insights you find that others might find useful. Thanks.
