### ISSUE TITLE
Spritesheet image fails to load because of cross origin

### ISSUE THREAD

**Issue by distinctdan** [pixijs/pixi.js#5350]
So, I'm using pixi along with cordova. I know about the cross origin issues with loading `file://` urls and have solved them for most resources by passing options to the `PIXI.loader.add` call like this: 
```
PIXI.loader.add(this.laserBeamPath, {
    crossOrigin: 'anonymous',
    loadType: PIXI.loaders.Resource.LOAD_TYPE.XHR,
});
```
However, this doesn't work for spritesheet images. It loads the spritesheet json fine, but it doesn't load the spritesheet image using the cross origin options. Seems like child resource calls should inherit the parent's options. Anybody know anything I can do to fix this in the mean time?

All my resources need the same options, so another way would be if there's a global options config I can set that would work for all resources including child loads?

### Environment

- **`pixi.js` version**: 4.8.2
- **Browser & Version**: Mobile Safari
- **OS & Version**: iOS

**Comment by ivanpopelyshev** [comment]
According to https://github.com/pixijs/pixi.js/blob/v4.x/src/loaders/spritesheetParser.js#L24 , it should work.

**Comment by distinctdan** [comment]
Hmm, it's not passing the loadType though, which was necessary for me to get it to work originally.

By the way, I found a workaround using the loader's middleware to set the options of each request (the `device.platform` part is cordova specific):
```
PIXI.loader.pre((resource, next) => {
    if (window.device && (device.platform === 'iOS' || device.platform === 'Android')) {
        resource.crossOrigin = 'anonymous';
        resource.loadType = PIXI.loaders.Resource.LOAD_TYPE.XHR;
    }
    next();
});
```
