### ISSUE TITLE
Sprite.from bug on Firefox

### ISSUE THREAD

**Issue by ProtonGustave** [pixijs/pixi.js#5354]
### Description
There is a bug with `window.createImageBitmap` function on Firefox(i think [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1472194) bug on bugzilla is related), because of it function `PIXI.Sprite.from` isn't working properly on Firefox.
### Current Behavior
Code:
```javascript
const bg = PIXI.Sprite.from('bg.png');
app.stage.addChild(bg);
``` 
I create about 4 sprites with `PIXI.Sprite.from` function(from 4 different images). Error originates only for one pic `bg.png` and only if it's fetched from browser cache. I should note that `bg.png` is the biggest image(1136K), everything else is small(under 80K), and also this is first sprite(i create other sprites right after it).
Error:
```
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
```
file: `core/src/textures/resources/ImageResource.js`; line: 167; (i.e. `window.createImageBitmap` call)

Notes:
I think it's some race problem in firefox(bg.png is the biggest image and also i have slow laptop, probably firefox can't get file from local fs in time or something like this). I tried to delay call of `window.createImageBitmap` in `ImageResource.process` function: when i was using `requestAnimationFrame` and `setTimeout` with 4 ms delay it was sometimes working (and sometimes it wasn't), when i was using `setTimeout` with 200ms delay it was always working. With use of pixi loader(i.e. without `PIXi.Sprite.from` at all, classic way) it was always working, idk why.

Temporary workaround is to use loader and create sprite from loader texture, it works just fine.
Error on bugzilla wasn't updated for 7 months, i think we need to modify pixi in some way.

### Env
- **`pixi.js` version**: _5.0.0-alpha.3_
- **Browser & Version**: _Firefox Developer Edition 65.0b2_
- **OS**: _Arch Linux_

**Comment by ivanpopelyshev** [comment]
Wrkaround:
switch it off in settings.

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/ImageResource.js#L61

**Comment by ivanpopelyshev** [comment]
We have to make reproducible demo, otherwise we dont have a chance against bugzilla.

They are VERY slow, my previous issue about createImageBitmap exists fr a year: https://bugzilla.mozilla.org/show_bug.cgi?id=1442632

I really don't know should I spend my time right now digging into it only for them to stall it for another year.

**Comment by bigtimebuddy** [comment]
Maybe you could try something like this as a workaround:
```js
const createBitmap = navigator.userAgent.indexOf("Firefox") === -1;
const bg = PIXI.Sprite.from('bg.png', { resourceOptions: { createBitmap } } );
app.stage.addChild(bg);
```
