### ISSUE TITLE
AccessibilityManager is randomly blocking all user interactions in my app

### ISSUE THREAD

**Issue by distinctdan** [pixijs/pixi.js#5356]
So I'm play testing my app on a device, and I've noticed that every once in a while, the app completely stops responding to user input. I seem to remember it only happening when the app is first launched, and if I reopen it, it doesn't do it again. Well, it happened again, and I was able to debug the webview and noticed that there's a random absolutely positioned div with a z-index that's blocking all interactions! What the heck!

This is a showstopper for me because my pixi view is the background for my whole app. I can't just have it randomly start blocking user input. I happened across the place in pixi's source where the accessibilityManager creates this div, but I'm not using accessibility features that I know of, so I have no idea why it's doing this.

How can I prevent this from ever happening?

- **`pixi.js` version**: _e.g. 4.8.2
- **Browser & Version**: Mobile Safari
- **OS & Version**: iOS

**Comment by distinctdan** [comment]
As a workaround, I found out you can build a custom version of pixi and exclude the module, so I've done that for the accessibility module. I'm not using interactions either, so went ahead and excluded that too.

**Comment by bigtimebuddy** [comment]
Check out this solution for removing accessibility or interaction at runtime, in case you don’t want to maintain a custom build.

https://github.com/pixijs/pixi.js/issues/5111#issuecomment-420047824

In v5 you’ll be able to create a custom build use if various sub packages. Sounds like that might be a good option if you’re doing your own interaction, which sounds like you are.

**Comment by distinctdan** [comment]
Thanks for the info, I may do that if I get tired of doing the custom one.

Yeah, I built my app's UI as a single page app with html/css because css is just so nice for layout. My game is tilt-controlled, so there's not really any user interaction with pixi objects.

**Comment by bigtimebuddy** [comment]
Seems answered. Closing

**Comment by distinctdan** [comment]
I'm ok if you still want to close it, but I do want to point out that this appears to still be a serious issue with accessibility manager. Other people may still need accessibility, or may not know to remove it. Using a z-indexed overlay seems like an inherently risky thing to do. I don't know why it was done that way, but seems like you could just listen for events on the canvas itself instead.

**Comment by GoodBoyDigital** [comment]
Worth noting that Accessibility Manager is disabled by default unless you actually try to access content via pressing tab or screen reader on mobile. So if its never used, its never there. Its very aggressively managed :)

Accessibility is a pain and unfortunately the only way to tap into screen reader technology is to have div elements over the canvas as we can lean on the native implementations for things like tab-index, tab-order etc.

fun fun!

**Comment by distinctdan** [comment]
Yeah, I get the reason for it being there, no arguments there. However, it's supposed to be opt-in, but there must be a bug in that code because I'm not using any accessibility features, and the app is being run on mobile devices, so it's impossible that tab is being pressed. I'm kind of mystified as to what's activating it.

I've done a little work with making stuff accessible in the past, and I haven't ever seen anything like an absolutely positioned overlay being necessary. Usually when something wants to be tabable, it has an extra element in the dom, but it's positioned offscreen, like `left: -9999px; width: 1px; height: 1px;`. Then, you would add keyboard event listeners to that offscreen div that has focus. For mouse events on the canvas, I would think you could listen directly on the canvas itself.

**Comment by distinctdan** [comment]
Ok, I've figured out what's going on here. I randomly encountered the bug again, and found that the accessibilityManager's `isMobileAccessibility` property is true, which appears to only get set if the hook div gets focus. However, this should be impossible since the hook div is positioned offscreen.

So, I poked around and discovered that on android, Cordova calls `requestFocusFromTouch` in its init stage. There appears to be a race condition where if pixi is able to create the hook div before cordova shows its view, the hook div will get autofocused when cordova's webview requests focus. I was able to consistently replicate the problem by adding a delay before the webview requests focus, which gave pixi enough time to set up.

This means this issue could affect all cordova/ionic user, or anyone that's embedding a webview in their app, although I imagine that's a pretty small subset of pixi users. I was wondering, since you have to do some setup for accessibility to work anyways, is there a reason for the accessibility manager to be on by default?
