### ISSUE TITLE
Can i give RGB color as texture for PIXI.rope?

### ISSUE THREAD

**Issue by vicchoutw** [pixijs/pixi.js#5365]
Hi Everyone

I wish to give RGB color as texture for PIXI.rope but it seems only supported with `PIXI.Texture.fromImage()`.

 I tried to use 
```
const texture = PIXI.Texture.WHITE;
texture.tint = 0xD3872A;
```
but it still not working. Any ideas?
Thanks a lot!

Environment:
`PixiJS 4.8.2`

**Comment by ivanpopelyshev** [comment]
`rope.tint = 0xD3872A`

**Comment by ivanpopelyshev** [comment]
Also texture height is important for rope, so if you want specific height, you have to do some hacks:

```js
var baseTex = PIXI.Texture.WHITE.BaseTexture;
var myWhiteTex = new PIXI.Texture(baseTex);
myWhiteTex.orig.height = 40;
```

**Comment by vicchoutw** [comment]
It works! Thanks for your reply.

Btw, i tried to use https://github.com/gameofbombs/pixi-heaven now, 
can i set tint color like the code below?
`rope.strip.color = 0xff0000;` 

without using:
`rope.strip.color.setLight(0, 1, 0);` because use `setLight()` or `setDark()` is difficult for me to get correct color i want. 

I follow this example: https://gameofbombs.github.io/examples-heaven/#/mesh/rope-colored.js.
it.

Thanks!

**Comment by ivanpopelyshev** [comment]
`rope.tint` works there too.

**Comment by vicchoutw** [comment]
That's Awesome, you save my life!
Thanks again.
