### ISSUE TITLE
Latest Pixi not compatible with Angular 7

### ISSUE THREAD

**Issue by krojew** [pixijs/pixi.js#5367]
Continuation of https://github.com/pixijs/pixi.js/issues/4921 since it's not resolved for v7.

### Expected Behavior

Angular 7 with Pixi should build.

### Current Behavior

Build fails with multiple instances of:

`Module not found: Error: Can't resolve 'path' in ...`

### Steps to Reproduce

Install Pixi with Angular 7, using official npm packages. Run `ng build` or `ng serve`.

### Environment

- **`pixi.js` version**: 4.8.5
- **OS & Version**: Ubuntu 18.10
- **Angular version**: 7.1.2

**Comment by bigtimebuddy** [comment]
Could you please provide a repo the reproduces? We are not Angular folks here and need some help figuring out this integration. Thanks.

**Comment by ivanpopelyshev** [comment]
https://blog.lysender.com/2018/07/angular-6-cannot-resolve-crypto-fs-net-path-stream-when-building-angular/

**Comment by krojew** [comment]
This is a simple project based on the previous bug, but updated to the latest versions: https://github.com/krojew/test-pixi

After cloning, run `npm install` and `ng build`. You should see a lot of errors from pixi relating to 'path'.

**Comment by clark-stevenson** [comment]
Here is what I seen when `ng serve` . 

```
ERROR in ./node_modules/pixi.js/lib/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\core\renderers\webgl\filters\spriteMask'

ERROR in ./node_modules/pixi.js/lib/core/sprites/webgl/generateMultiTextureShader.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\core\sprites\webgl'

ERROR in ./node_modules/pixi.js/lib/extras/webgl/TilingSpriteRenderer.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\extras\webgl'

ERROR in ./node_modules/pixi.js/lib/filters/alpha/AlphaFilter.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\filters\alpha'

ERROR in ./node_modules/pixi.js/lib/filters/colormatrix/ColorMatrixFilter.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\filters\colormatrix'

ERROR in ./node_modules/pixi.js/lib/filters/displacement/DisplacementFilter.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\filters\displacement'

ERROR in ./node_modules/pixi.js/lib/filters/fxaa/FXAAFilter.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\filters\fxaa'

ERROR in ./node_modules/pixi.js/lib/filters/noise/NoiseFilter.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\filters\noise'

ERROR in ./node_modules/pixi.js/lib/loaders/bitmapFontParser.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\loaders'

ERROR in ./node_modules/pixi.js/lib/mesh/webgl/MeshRenderer.js
Module not found: Error: Can't resolve 'path' in 'I:\Downloads\test-pixi-master\test-pixi-master\node_modules\pixi.js\lib\mesh\webgl'
```

**Comment by clark-stevenson** [comment]
My Stackblitz seems fine: [App](https://stackblitz.com/edit/angular-at454v)

I just updated dependencies, added `pixi.js` and `@types/pixi.js`

Then pasted this into `app.component.ts`

```
import { Component } from '@angular/core';
import { Application } from 'pixi.js';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  private app = new Application();
}

```

It works fine,  it asks for a `url` dependency but I presume that is just Stackblitz?

Anyway, locally, the exact same project fails to build.  😕  How can that be?

**Comment by ivanpopelyshev** [comment]
I take it , link that I sent is not related to the issue? It cant find `path` module, is that right?

**Comment by clark-stevenson** [comment]
@ivanpopelyshev  

Ahh sorry! I missed your link somehow.  

[On the link](https://blog.lysender.com/2018/07/angular-6-cannot-resolve-crypto-fs-net-path-stream-when-building-angular/) you sent us above.  I looked at just the first "annoying example". 

This file

`node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js`

By default is `node: false` but when when it is changed to `node: { path: true }`.  Then the following commands work. 

- `ng serve`
- `ng build`
- `ng build --prod`

Soon as I flip that back to `node: false`.  We return to this Issue.

**Comment by krojew** [comment]
Maybe there's a way to gracefully handle node dependencies? At the moment, pixi is the only package I've encountered with this issue, so I suspect there is a way to do it.

**Comment by bigtimebuddy** [comment]
With other bundlers, they have builtins polyfills for node.js modules like path. I assume maybe there’s something similar in Angular?

**Comment by krojew** [comment]
Given that other packages build with Angular, I suspect it's up to the package to handle it.

**Comment by bigtimebuddy** [comment]
I don't think `path` is used in many places, so I can switch over to use https://www.npmjs.com/package/path instead, which should solve this.

**Comment by bigtimebuddy** [comment]
PR welcome to v4.x branch to fix this. I have a release I need to do for v4 so we should be able to get this out quickly.

**Comment by axelvaindal** [comment]
I've managed to make my project work by running `npm install --save path` so it would be bundled along pixi client side.
@bigtimebuddy 
I'll propose a PR that just add path as a dependency to pixi.js, I assume it's the only thing I have to do so the require looks for bundled module instead of the native one right ?

**Comment by ivanpopelyshev** [comment]
Is there module version of pixi-v4? I thought we have that only in v5.

**Comment by krojew** [comment]
Any news?
