### ISSUE TITLE
Calculate visible bounds of an object (excluding masked/covered areas)

### ISSUE THREAD

**Issue by LFP6** [pixijs/pixi.js#5372]
If a DisplayObject is a child of a container that has a mask, is there a way to determine, without knowing the mask of the parent, what the visible bounds of the child are?

**Comment by ivanpopelyshev** [comment]
Short answer - no. Pixi does calculate bounds of parent properly, but child is considered unmasked.

**Comment by LFP6** [comment]
The answer doesn't change, but what I'd actually be looking for is not just masking - if another object is partially covering it, I want to know the bounds of the visible portion (regardless of what's hiding the other part). Not sure if this would be a viable feature request or just too much of an ask.

The brute-force approach would be recursively determining the bounds of each object (or at least, each object that could viably be "over" the object visible bounds are being calculated for), starting at the root. I imagine that'd be awfully expensive though...

**Comment by ivanpopelyshev** [comment]
Take polygonal shapes and do a scanline algorithm, i remember how i did that :)
