### ISSUE TITLE
CanvasRenderer - "extract" does not scale (works with WebGLRenderer)

### ISSUE THREAD

**Issue by wkamir** [pixijs/pixi.js#5373]
Basically I am doing this:

```
const canvasRenderer = new CanvasRenderer();
const sprite = Sprite.fromImage('someLoadedImage.png');
return canvasRenderer.extract.base64(sprite);
```

to render some images as base64 and later use them as data urls in  CSS.
Works like a charm.

Except now I tried to set a scale on the sprites - it does not get picked up at all :-( The image is always rendered with scale factor 1.0.
I tried the same with a WebGLRenderer - this works.

I just don't want to use WebGLRenderer since I'm concerned that older machines will not support it (I am only building a very simple 2D browser-game).

**Comment by bigtimebuddy** [comment]
Could you make a simple jsfiddle, codepen pixiplayground.com, etc the demonstrates this behavior? It helps us verify changes and makes it easier for us to help. Thanks.

**Comment by wkamir** [comment]
Sure thing:
https://codepen.io/anon/pen/ebqRzy

This codepen shows exactly what I'm doing...  There can be seen 2 divs.
One get's the scaled, extracted base64 image from a CanvasRenderer, the other from the WebGLRenderer.

**Comment by ivanpopelyshev** [comment]
When I tried to fix that thing it was pain and PR was too big :( Wrap it in container please, and don't try to extract stuff from existing stage element, remove parent first (`sprite.parent.removeChild(sprite)`)

**Comment by wkamir** [comment]
Thank you very much!! That workaround is good enough for me.

And also thanks for this great library ;-)
