### ISSUE TITLE
Problem building dev branch

### ISSUE THREAD

**Issue by phpositive** [pixijs/pixi.js#5374]
### Expected Behavior
'npm run build' to build valid pixi and pixi-legacy bundles

### Current Behavior
bundles\pixi.js\dist
bundles\pixi.js-legacy\dist

content for both folders is created, but producing approx. 40kb/4kb files only.

### Steps to Reproduce
npm install
npm run build

### Environment
- **`pixi.js` version**: dev branch
- **OS & Version**: Windows 7

**Comment by themoonrat** [comment]
What version of node are you using?

**Comment by phpositive** [comment]
10.15, npm 6.6.0

**Comment by themoonrat** [comment]
Hmm, I'm on 10.15 and npm 6.4.1 and it works fine. Would you be able to try it with 6.4.1 npm and a fresh deletion of node_modules followed by an  `npm i` please?

**Comment by themoonrat** [comment]
Ahh, I believe this is because you are looking in 
`\bundles\pixi.js-legacy\lib\pixi-legacy.js`
When you should be looking in
`\bundles\pixi.js-legacy\**dist**\pixi-legacy.js`

**Comment by phpositive** [comment]
no, I'm not, see first comment. In post above export is weirdly truncated. Forgot to mention, master branch builds fine.

**Comment by themoonrat** [comment]
hmmm, odd. Because what you pasted is exactly what i see in my lib folder. Why that's appearing in your dist folder I've no idea, I'm afraid. Hopefully someone else can help!

**Comment by phpositive** [comment]
These are mine dist-lib files
![dist-lib](https://user-images.githubusercontent.com/46866263/51443352-01d16000-1ce8-11e9-8c23-2f3d10127b18.jpg)

**Comment by bigtimebuddy** [comment]
I'm unable to reproduce this error. Did you resolve @phpositive or figure out what's going on?

**Comment by phpositive** [comment]
I did not solve it

**Comment by phpositive** [comment]
@bigtimebuddy Solved. Problem was me having pixi folder named "pixi test" with whitespace in it. Removed it and everything works now.
