### ISSUE TITLE
BaseRenderTexture "setResolution" is not a function

### ISSUE THREAD

**Issue by RamdomGuy** [pixijs/pixi.js#5376]
Hello.

I have a problem with the function "setResolution" of BaseRenderTexture.
It's say that the function is undefined, but when i go to the doc the function is there.

Anyone can help ? Any help is appreciated.

**Comment by ivanpopelyshev** [comment]
Which version of pixi do you use, the one from "v4.x" branch (4.8.x) or "dev" (v5.0.0-alpha3) ?

People are confused because we didnt officially publish v5 yet and its under "dev" branch. 

http://pixijs.download/dev/docs/index.html
http://pixijs.download/v4.x/docs/index.html

**Comment by RamdomGuy** [comment]
Hello and thank for your quick answer.

I have actually pixi 4.5.5 i will update it and retry to call the function it's propably because of that.
Once i have update it i will let you know if it is working or not.

Thank again for your quick answer and have a nice day. :)

**Comment by RamdomGuy** [comment]
Sorry if my english is bad btw.

**Comment by RamdomGuy** [comment]
So i update the pixi version to the 4.8.4 minify and now pixi say that the function dosen't exist anymore, so i guess maybe she was deprecated ?

Thank anyways for your help. :)

**Comment by RamdomGuy** [comment]
I forgot to motion that the setResolution function does exist on the 4.5.5 version

**Comment by englercj** [comment]
> I forgot to motion that the setResolution function does exist on the 4.5.5 version

Are you sure? I looked at v4.5.5 and found no "setResolution" in the entire file: http://pixijs.download/v4.5.5/pixi.js

**Comment by bigtimebuddy** [comment]
Please refer to this documentation: http://pixijs.download/v4.8.5/docs/PIXI.BaseRenderTexture.html

**Comment by RamdomGuy** [comment]
He dosen't give me a error in pixi 4.5.5 so i presume that the function exist.

Thanks for the doc.I will watch it out. :)

**Comment by RamdomGuy** [comment]
> Are you sure? I looked at v4.5.5 and found no "setResolution" in the entire file: http://pixijs.download/v4.5.5/pixi.js

As strange as it is. It's working. But when i watch the file too i see that the function in the file dosen't exist.
I use google chrome for debugging. Maybe it's because of that ?

**Comment by RamdomGuy** [comment]
I watch the doc and no "setResolution" is in the doc,so i guess that the function was deprecated and theyremove it from the file, since you can achieve the same result from filters. i close the thread because i got an answer to my question.

Thanks to all and have a nice day. :)

**Comment by RamdomGuy** [comment]
If you ask what i mean by resolution,i mean the parameter in the constructor of baserendertexture but anyways it's was my fault, i should have watched the version of the doc.
