### ISSUE TITLE
[Question] Draw multiple instances of the same sprite with different position

### ISSUE THREAD

**Issue by renatonolo** [pixijs/pixi.js#5378]
Hello everyone.

In my game, I have a map with 25x13 tiles with 32px width tile size for each tile.
When I get the map, I have a lot of same tiles in different positions, like the example:
**[tile01, tile01, tile01, tile01, tile01]
[tile01, tile02, tile02, tile02, tile01]
[tile01, tile02, tile02, tile02, tile01]
[tile01, tile02, tile02, tile02, tile01]
[tile01, tile01, tile01, tile01, tile01]**

How can I cache the sprites with same texture when I need to change sprite position?
And how it works with AnimatedSprites?

It's worth to clone sprites to change it's position?

I am using the below code to load each sprites:
`let texture = new PIXI.Texture(tilesetName, new PIXI.Rectangle(x, y, w, h));`
`return new PIXI.Sprite(texture);`

Thanks! :)

**Comment by englercj** [comment]
A sprite is basically a position at which to draw a texture. Just make separate sprites for each tile that share the same texture instance:

```
const tile01 = new PIXI.Texture(tilesetName, new PIXI.Rectangle(x, y, w, h));

const sprite1 = new PIXI.Sprite(tile01);
const sprite2 = new PIXI.Sprite(tile01);
const sprite3 = new PIXI.Sprite(tile01);
// etc..
```

**Comment by renatonolo** [comment]
Then, can I do something like this in my getTexture method

```
getTexture(tilesetName, x, y, w, h) {
    if(this.textureCache[`${tilesetName}.${x}.${y}.${w}.${h}`]) return this.textureCache[`${tilesetName}.${x}.${y}.${w}.${h}`];
    else {
      let textureCache = new PIXI.Texture(this.getResources()[tilesetName].texture, new PIXI.Rectangle(x, y, w, h));
      this.textureCache[`${tilesetName}.${x}.${y}.${w}.${h}`] = textureCache;
      return textureCache
    }
  }
```

**Comment by renatonolo** [comment]
It work for me! Thanks. 👍
