### ISSUE TITLE
moveTo() / lineTo() semantics - are the coordinates inclusive?

### ISSUE THREAD

**Issue by vedadkajtaz** [pixijs/pixi.js#5380]
Hello,

I have a newbie question regarding `PIXI.Graphics::moveTo()` and `PIXI.Graphics::lineTo()`: are the coordinates inclusive (as per specifications - I couldn't find the answer in the docs)?

Moreover, there is apparent discrepancy in way 0 is handled in vertical and horizontal axis:

```
const red = 0xff0000;
const green = 0x00ff00;
App.stage.addChild(new PIXI.Graphics().lineStyle(1, red, 1, 1, true).moveTo(0, 0).lineTo(99, 0));
App.stage.addChild(new PIXI.Graphics().lineStyle(1, green, 1, 1, true).moveTo(0, 0).lineTo(0, 99));

```
The first line gets drawn (with a missing rightmost pixel in a 100x100 canvas), while the second doesn't. However, it does fill the leftmost pixel (except the bottom one) when using 1 instead of 0 for horizontal axis:

`App.stage.addChild(new PIXI.Graphics().lineStyle(1, green, 1, 1, true).moveTo(1, 0).lineTo(1, 99));`

Thanks,

**Comment by ivanpopelyshev** [comment]
same as for canvas2d context, (0,0) is actually a corner of pixel, and width=1 leads to two pixel width instead of one (half-pixel). In case of antialiasing there'll be two pixels each with alpha=0.5

**Comment by ivanpopelyshev** [comment]
As for line endings, pixi doesn't have CapStyle yet, so its always "NONE"

**Comment by bigtimebuddy** [comment]
Seems answered.

**Comment by vedadkajtaz** [comment]
Indeed, thanks.
