### ISSUE TITLE
CDN sample broken

### ISSUE THREAD

**Issue by novalain** [pixijs/pixi.js#5382]
### Expected Behavior

Should render the sample correctly

### Current Behavior

Getting the error `Uncaught TypeError: Cannot read property 'shared' of undefined`
at PIXI.Loader.shared(...)

### Possible Solution

Changing PIXI.Loader.shared(...) to PIXI.loader.add(...) seems to make things work

### Steps to Reproduce

1. Follow instructions on GitHub how to setup project with CDN
2. Run the bunny sample

### Environment

- **`pixi.js` version**: _e.g. 4.5.1_
- **Browser & Version**: _e.g. Opera 57.0.3098.116_

**Comment by bigtimebuddy** [comment]
Known issue. This new code only applies to v5 as we are in the middle of a transition and this recently changed.
