### ISSUE TITLE
document.execCommand('copy') doesnt work on Mobile browser

### ISSUE THREAD

**Issue by koalaylj** [pixijs/pixi.js#5383]
- **`pixi.js` version**:  v4.8.2
- **Browser & Version**: ios  Chrome71 & safari12
- **OS & Version**: IOS12/Android 5.x

function that can copy somthing to clipboard(`npm copy-text-to-clipboard`).
``` javascript
const copyToClipboard = input => {
    const el = document.createElement('textarea')

    el.value = input

    // Prevent keyboard from showing on mobile
    el.setAttribute('readonly', '')

    el.style.contain = 'strict'
    el.style.position = 'absolute'
    el.style.left = '-9999px'
    el.style.fontSize = '12pt' // Prevent zooming on iOS

    const selection = document.getSelection()
    let originalRange = false
    if (selection.rangeCount > 0) {
      originalRange = selection.getRangeAt(0)
    }

    document.body.appendChild(el)
    el.select()

    // Explicit selection workaround for iOS
    el.selectionStart = 0
    el.selectionEnd = input.length

    let success = false
    try {
      success = document.execCommand('copy')
    } catch (err) {
    }

    document.body.removeChild(el)

    if (originalRange) {
      selection.removeAllRanges()
      selection.addRange(originalRange)
    }

    alert('copied' + success)
    return success
  }
```
the code below works well on pc but does't work on mobile device(ios & android)
alert shows `copied:false` , copy failed.
```javascript 
  var bunny = PIXI.Sprite.fromImage('./bunny.png')
  bunny.interactive = true
  bunny.on('pointerdown', event => {
    copyToClipboard('something need to be copied')
  })
 app.stage.addChild(bunny);
```

but i tried the copy fucntion without pixi.js，it works well(both pc and mobile).
```javascript
<button onclick="copyToClipboard('aaaaaaaa')">copy</button>
```

my question is how should i make  `document.execCommand('copy') ` worked on mobile device.
any help is appreciate thanks!

**Comment by themoonrat** [comment]
try using 'click' for the bunny event?

**Comment by koalaylj** [comment]
@themoonrat  click event is not fired on mobile device browser.

**Comment by themoonrat** [comment]
try 'touchstart' or 'touchend' then. Just trying to find a different event that it'll work on. Just like WebAudio has to be unlocked by a valid event, maybe browsers require that for the copyToClipboard functionality too.

**Comment by bigtimebuddy** [comment]
Seems answered by @themoonrat.
