### ISSUE TITLE
Preprocess spritesheets

### ISSUE THREAD

**Issue by cjus** [pixijs/pixi.js#5388]
I'm looking for a way to process a spritesheet after PIXI has loaded the JSON but before PIXI has an opportunity to parse it.

In my usecase I compressed JSON files including my sprites.json atlas and would like to unpack the file before it's use to create textures.  I'm using an NPM package I wrote (https://www.npmjs.com/package/simple-json-pack)

In my code example below (typescript) I load a game.json file and unpack it. Then I add remaining resources using this.loader.add(asset)

I've tried to use a middleware function to unpack JSON files.  That works just fine except for my sprite.json atlas.

```
  init(filename: string, initComplete: ICallback): void {
    this.loader.add(filename);
    this.loader.load((_loader: PIXI.loaders.Loader, resources: any) => {
      this.gameConfig = resources[filename].data;
      if (this.gameConfig._dict) {
        this.gameConfig = this.unpack(this.gameConfig);
        resources[filename].data = this.gameConfig;
      }
      for (let asset of this.gameConfig.assets) {
        this.loader.add(asset);
      }
      this.loader.use((resource: any, next: any) => {
        if (resource.extension === 'json' && resource.data._dict) {
          resource.data = this.unpack(resource.data);
        }
        next();
      });
      this.loader.load((_loader: PIXI.loaders.Loader, resources: any) => {
        this.resources = resources;
        initComplete(this.resources);
    });
    });
  }
```

### Environment

- **`pixi.js` version**: 4.8.5

**Comment by ivanpopelyshev** [comment]
Maybe use pair of loaders instead of one?

**Comment by cjus** [comment]
@ivanpopelyshev thanks for the fast reply and for your years of service to this project. 

I'm not sure I'm following. The underlying problem seems to be that PIXIJS has middleware which executes *before* loading completes.  There doesn't appear to be a way to add a custom middleware before the standards ones execute. In my usecase I still need spritesheet processing - but I want to decompress the underlying JSON before pixi executes its default middleware spritesheet handling.

**Comment by ivanpopelyshev** [comment]
I recommend to patch pixi, because I don't know any other way except finding that particular middleware in the array and changing it to something else.

**Comment by ivanpopelyshev** [comment]
We can also ask @englercj : what is intended, author-way of extracting and changing the middleware in resource-loader? :)

**Comment by djmisterjon** [comment]
And what about package manage from nwjs or electron?
http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#package-option-2-zip-file
I dont know if we talk about same thing, but if this can help you, in prod, all my spritesheet and ressource are compressed, and it nwjs that decompress

**Comment by Dairnon** [comment]
@djmisterjon He has his own software which he uses to compress his json files. 

He just wants an easy way to uncompress them after load but before the loader tries to use the json file for creating the actual textures

**Comment by englercj** [comment]
I've had this up on resource-loader for a bit, but haven't seen a lot of people asking for it yet, but sounds like it would help solve this issue:
https://github.com/englercj/resource-loader/issues/100

In the meantime, middleware runs in registration order. So you need to inject your middle in the right spot in Pixi's loader plugins, before creating one.

The loader in Pixi is *very* simple. Basically the only thing it does is automatically add pixi-related middleware when one is created. If you are using v4, you can see how it does that [here](https://github.com/pixijs/pixi.js/blob/v4.x/src/loaders/loader.js).

Because of that what you need to do is inject your middleware into the `PIXI.Loader._pixiMiddleware` array at the right spot.

If you feel up for implementing middleware priorities in resource-loader I'm always accepting PRs.

**Comment by cjus** [comment]
@englercj Thanks for the above post! On the surface it seems that converting the `PIXI.Loader._pixiMiddleware` to an array of objects would allow for members such as `fn` and `priority`. Then the array could be sorted based on the priority key. The `addPixiMiddleware` function would change by only adding an optional `priority` key. The actual sorting would occur once in the constructor after the Emit call. Would it be as simple as that?

**Comment by englercj** [comment]
That would be a quick-and-dirty way to get it working for global pixi middleware, but it doesn't actually add the feature to the loader library itself so that everyone can use it.

**Comment by cjus** [comment]
@englercj Doesn't adding a second param to `addPixiMiddleware` make the feature available to the loader lib for public use?

**Comment by englercj** [comment]
Only in pixi, which is not the only consumer of the [`resource-loader`](https://github.com/englercj/resource-loader) library. Like I mentioned before, the pixi wrapper around the actual loader just adds pixi-specific middleware. That entire library is a separate library consumed by pixi.

Adding what you are describing would be a hack for ordering pixi middleware, but wouldn't affect any other middleware added after construction or middleware that uses the non-pixi-specific APIs.

**Comment by cjus** [comment]
@englercj thanks for that classification. For now I'll need to work around this issue.  Feel free to close this ticket.

**Comment by englercj** [comment]
Feel free to vote up that issue on resource-loader I mentioned so I know that at least someone is asking for it. The reason I haven't worked on it at all is this is only the second time anyone has ever asked for it, and the first time was in 2017 when I entered the issue.
