### ISSUE TITLE
Documentation: v4 Filters - Broken Link

### ISSUE THREAD

**Issue by Shatterbrain** [pixijs/pixi.js#5390]
On this page:
https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters

The following link under **Extra texture, mapped matrix** is broken:
https://github.com/pixijs/pixi.js/blob/dev/src/filters/displacement/DisplacementFilter.js

If I search DisplacementFilter.js in the repo, it comes up with a version that looks like it's for pixi v5 (vertex shader is referencing v5 filter uniforms - inputSize, outputFrame. See: https://github.com/pixijs/pixi.js/blob/a0b4f732c033af97f02a5fb089ffb9e4516d2b63/packages/filters/filter-displacement/src/displacement.vert).

On a related note, I wish there was a more minimalist example of using an extra texture in a filter. The displacement map example is somewhat advanced for a tutorial/reference; it's hard to figure out which parts I actually need for the extra texture and what is specific to a displacement map.

Thanks for all your hard work on pixi.js!!

**Comment by Shatterbrain** [comment]
I found the corresponding link in the v4 branch and might continue to clarify the wiki if I make more progress after analyzing the right code.

**Comment by bigtimebuddy** [comment]
Contributions welcome! Especially if you find broken links.

**Comment by ivanpopelyshev** [comment]
Of course its broken, we switched to v5 and now we have to change all the links to old `v4.x` branch. 

https://github.com/pixijs/pixi.js/tree/dev/packages/filters/filter-displacement/src

As for extra texture, just add it to uniforms and it'll work both in v4 and v5. Though without mappedMatrix there's no guarantee that coordinates will be the same as for your container, and they can be changed even through `padding`.

**Comment by ivanpopelyshev** [comment]
About "creating filters for XXX" - I provided enough information for people to start experimenting. Of course it'll be better if someone makes more detailed doc that allows people to write their filter without experimenting, from the first try ;)

**Comment by ivanpopelyshev** [comment]
Extra doc about v5 filters: http://pixijs.download/dev/docs/PIXI.Filter.html

**Comment by ivanpopelyshev** [comment]
I also beileve that it'll take one more year to fix all the documentation and provide all the examples for v5. Yes, its that difficult.

**Comment by Shatterbrain** [comment]
After a lot of trial and error, I was eventually able to achieve the simple effect I was going for. Filters are clearly a complicated business!
