### ISSUE TITLE
PIXI.Texture.fromCanvas holds and never releases canvas objects

### ISSUE THREAD

**Issue by samjohn** [pixijs/pixi.js#5398]
### Expected Behavior
When I create a `PIXI.Texture` from a `canvas`, then destroy that texture, it should not keep the `canvas` in memory. 

### Current Behavior
The `canvas` object never goes out of memory after uploading to a `PIXI.Texture`. 

### Possible Solution
I'm guessing there is a reference to the canvas that is sticking around erroneously. Perhaps we could find the reference and release it when we destroy the texture (or better yet, when you remove the texture from the WebGL canvas). 

### Steps to Reproduce
I made a small gist here to demonstrate the problem: https://gist.github.com/samjohn/9c04250d9b97f67282ea3347e9eb7050
 
If you take a memory trace from the timeline, you will see that our `canvas` objects never go away. 
![2019-02-01 at 4 31 pm](https://user-images.githubusercontent.com/126436/52156743-f44c9c00-263e-11e9-963b-099391a6946d.jpg)

### Environment

- **`pixi.js` version**: 4.5.8
- **Browser & Version**:  Chrome/Safari
- **OS & Version**: MacOS Mavericks
- **Running Example**: https://c.gethopscotch.com/projects/zzf06rgo2

**Comment by bigtimebuddy** [comment]
I think the problem is how you're destroying:
`texture.destroy();`

You should also destroy the baseTexture by calling
`texture.destroy(true);`

Documentation reference here: http://pixijs.download/v4.x/docs/PIXI.Texture.html#destroy

See if that helps you.

**Comment by bigtimebuddy** [comment]
No problem.

There are cases where you might not want to destroy the baseTexture like creating a dynamic spritesheet. The Texture object is just a reference to a part of an image, or resource. Welcome a doc PR to help clarify, but i feel like this issue has been addressed.
