### ISSUE TITLE
Texture not showing with multiple renderer in 5.0.0-rc

### ISSUE THREAD

**Issue by Dosseum** [pixijs/pixi.js#5402]
Hello, i just update to the 5.0.0-rc, I was on the 4.8.5.
I had a game which work well on 4.8.5, I use AnimatedSprite & Sprite for all the game and I have multiple renderer.
After the update, I updated all the methods/class like extras.AnimatedSprite => AnimatedSprite, Loader => Loader.shared, etc...

Everything works  well except that I have a latency when it comes to use the same Image on multiple renderer. (and except that it seems more blurry but i think it's because you added antialiasing)

Before that, everything worked well, the images shows up immediatly after the loading.

But now the image/texture on the first renderer is ok but on the second renderer it takes times (like 30 seconds).  I made a small code that reproduces this issue, but it doesn't do the exact same as on my game.
On my game if i go on other tab and go back to the main tab, the textures will show up.

```
// 5.0.0 code 
	
		var tmpRenduTizDemo = new PIXI.Renderer(160, 190,  { transparent: true, resolution: 1 });
    var myCharDemo = [new PIXI.Container(), tmpRenduTizDemo];

    document.getElementById("renderer1").appendChild(tmpRenduTizDemo.view);
	let tmpTexture = new PIXI.Sprite(PIXI.Texture.from("btn.png"));
	myCharDemo[0].addChild(tmpTexture);

	
	var tmpRenduTizDemo2 = new PIXI.Renderer(160, 190,  { transparent: true, resolution: 1 });
    var myCharDemo2 = [new PIXI.Container(), tmpRenduTizDemo2];

    document.getElementById("renderer2").appendChild(tmpRenduTizDemo2.view);
	let tmpTexture2 = new PIXI.Sprite(PIXI.Texture.from("btn.png"));
	myCharDemo2[0].addChild(tmpTexture2);
	
	
    var inn = setInterval(function (r) { r[1].render(r[0]); }, 1000 / 24, myCharDemo);
    var inn2 = setInterval(function (r) { r[1].render(r[0]); }, 1000 / 24, myCharDemo2);

	// 4.8.5 code
		var tmpRenduTizDemo = new PIXI.autoDetectRenderer(160, 190,  { transparent: true, resolution: 1 });
    var myCharDemo = [new PIXI.Container(), tmpRenduTizDemo];

    document.getElementById("renderer1").appendChild(tmpRenduTizDemo.view);
	let tmpTexture = new PIXI.Sprite(PIXI.Texture.fromImage("btn.png"));
	myCharDemo[0].addChild(tmpTexture);

	
	var tmpRenduTizDemo2 = new PIXI.autoDetectRenderer(160, 190,  { transparent: true, resolution: 1 });
    var myCharDemo2 = [new PIXI.Container(), tmpRenduTizDemo2];

    document.getElementById("renderer2").appendChild(tmpRenduTizDemo2.view);
	let tmpTexture2 = new PIXI.Sprite(PIXI.Texture.fromImage("btn.png"));
	myCharDemo2[0].addChild(tmpTexture2);
	
	
    var inn = setInterval(function (r) { r[1].render(r[0]); }, 1000 / 24, myCharDemo);
    var inn2 = setInterval(function (r) { r[1].render(r[0]); }, 1000 / 24, myCharDemo2);
	`
```

You can test here : 
5.0.0 - http://93.113.206.174/pixi500.html
4.8.5 - http://93.113.206.174/pixi485.html

### Environment
I use Chrome (last version) on Windows but this issue occurs on Firefox too (i didn't test anything else).
UPDATE : It seems to be random on Firefox (sometimes working, sometimes not), but on Chrome it keeps doing this issue

**Comment by ivanpopelyshev** [comment]
OK, temporary workaround for you:

```js
PIXI.settings.CREATE_IMAGE_BITMAP = false;
```

It creates a bitmap, updates texture in first renderer and deletes bitmap, change in `dirtyId` forces bitmap upload by second renderer, its never ending cycle.
