### ISSUE TITLE
Custom fragment shader does not get precise texture color value 

### ISSUE THREAD

**Issue by rkdrnf** [pixijs/pixi.js#5406]
### Expected Behavior
texture2D(uSampler, vTextureCoord) color value should be precise value as in the texture.

### Current Behavior
color value at the edge of textures are not fetched correctly.

![image](https://user-images.githubusercontent.com/1143159/52197772-15fa8d00-28a4-11e9-8d6b-6570983285fe.png)

Above is the result of my custom shader applied.

belows are my vertex shader and fragment shader.
```
attribute vec2 aVertexPosition;
attribute vec2 aTextureCoord;

uniform mat3 projectionMatrix;

varying vec2 vTextureCoord;

void main(void)
{
    gl_Position = vec4((projectionMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);
    vTextureCoord = aTextureCoord;
}
```

```
precision mediump float;
varying vec2 vTextureCoord;
varying vec4 vColor;
uniform sampler2D uSampler;
uniform vec3 uColor;

void main(void)
{
    vec4 c = texture2D(uSampler, vTextureCoord);

    if (c.r == 1.0 && c.b == 1.0) {
        gl_FragColor = vec4(uColor.r * c.g, uColor.g * c.g, uColor.b * c.g, 1);
    } else if(c.r <= 0.1 && c.g <= 0.1 && c.b <= 0.1 && c.a == 1.0) {
        gl_FragColor = vec4(1, 1, 1, 1);
    } else if(c.a > 0.0) {
        gl_FragColor = vec4(c.r, c.g, c.b, c.a);
    }
}
````

You can see the black outline not properly converted to white at the right side of the character. and some pink pixels also not converted though it has 255 red and blue value in original texture.
I don't know why texture2D can't fetch precise value but just thinking it's somehow blended to nearby pixels.

Is there any way to get precise color value from texture2D as original texture?

### Environment
pixi v4
Chrome

**Comment by ivanpopelyshev** [comment]
In pixi all framebuffers and textures have premultiplied alpha: instead of (r,g,b,a) we actually use (r*a, g*a, b*a, a), that allows us to use linear filtering better.

It can be changed for textures if you switch `premultipliedAlpha` param in baseTexture to false. Maybe its `premultiplyAlpha`, I dont sactually remember and it depends on pixi version.

Linear filtering can be changed in `baseTexture.scaleMode`

The result has to be premultiplied anyway.

Example: https://github.com/pixijs/pixi-filters/blob/master/filters/color-map/src/color-map.frag#L14 , as you see there's `color.rgb /= color.a;` operation and in the end we do `color.rgb *= color.a;`. Simple shaders dont use division because we can work with (r*a) just fine.

**Comment by rkdrnf** [comment]
Thank you for reply Ivan!

I'm trying to change color of some parts of the sprites by it's original color value using shader.
below is the original texture shader to be applied.
![image](https://user-images.githubusercontent.com/1143159/52207163-dfcb0680-28bf-11e9-863f-6833d4d8ecee.png)

I'm gonna change the color of clothes by inspecting it's color value. 
because pixels I'm targeting to change always has (1, x, 1, 1) rgba value (pink pixels on the image), I inspect if it has ```r == 1.0 && b == 1.0``` and change it to user defined color.

I think it is not affected by premultiplied alpha because every texture I put this shader has 1.0 alpha value.
Also scale mode is set as ```NEAREAST``` mode.

Weird thing I found is that it depends on the screen size like below.

![image](https://user-images.githubusercontent.com/1143159/52206778-a6de6200-28be-11e9-8ca7-5eccc53c6698.png)
![image](https://user-images.githubusercontent.com/1143159/52206969-47cd1d00-28bf-11e9-8f92-c75433e0858e.png)

pixel area that shaders are not properly applied changes according to the screen size.

currently I dynamically changes ```app.screen.width ```, ```app.screen.height```, ```app.view.width``` and ```app.view.height``` when user resizes window.
```app.view.width```, ```app.view.height``` is always integer multiples of ```app.screen.width``` and ```app.screen.height```

**Comment by Dairnon** [comment]
Is this a filter? 

I believe you do apply the screen resolution into the shader to get correct results.

**Comment by rkdrnf** [comment]
@Dairnon Yes it is a filter.

Can you explain it more for me? what do you mean by applying screen resolution into the shader?
currently screen resolution is set as 1 and it does not change.

For more additional information, giving some tolerance to color check make it works properly, by checking ``` r >= 0.95 && b >= 0.95 ``` instead of ``` r == 1.0 && b == 1.0 ```. But I know this is not a good way to solve this problem.

**Comment by Dairnon** [comment]
Not exactly screen resolution rather... shaders can sometimes have issues when it comes to like... scaling the whole viewport size/screen resolution.

You said the results change based on screen size right? 


https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters

Many gotchas can cause strange results in creating a filter. I dunno if you've read this, but it can be helpful.

For example filterArea changing can change results when multiplied into the coordinates. 

You can get pixel coords by doing 

`vec2 pixelCoord = vTextureCoord * filterArea.xy;`

**Comment by Dairnon** [comment]
Also try taking a look at the colormap filter, it remaps colors to the textures pixels.

https://github.com/pixijs/pixi-filters/blob/master/filters/color-map/src/color-map.frag

**Comment by rkdrnf** [comment]
Thank you @Dairnon, @ivanpopelyshev.
I fixed it by adding 
```
 if (color.a > 0.0) {
        color.rgb /= color.a;
        ...
        color.rgb *= color.a;  
}
```
part before I do something with sampled pixel color.
I still don't know why alpha value matters because original texture has all alpha value 1.0
I will look into the source code later to know what happens behind.
Thank you again!
