### ISSUE TITLE
Different results of scaling between 5.0.0rc and 4.8.5

### ISSUE THREAD

**Issue by Dosseum** [pixijs/pixi.js#5407]
Hello again ! I updated to the pre-release 5.0.0rc and I figured out that it was more blurry. I already had problem with blur before but it was not a bug (just something i did wrong).

But now, I just updated to 5.0.0rc (and replace the name of methods) and some part of the game is now more blur.

Theses objects become blurry when I resize an object by 50% (scale.x = 0.5 / scale.y = 0.5).

=> I use the SCALE_MODES.LINEAR

### Expected Behavior
I scale down to 50% my object and it looks "nice"

### Current Behavior
I scale down to 50% my object and it looks "blurry"

### Possible Solution
I supposed it was a problem with PIXI.settings.SCALE_MODE, but even by forcing the LINEAR, it gets more blurry on the 5.0.0 version.

### Steps to Reproduce
My game was in Flash and I remade it in JS using Pixi.JS, so to have good effects when I need to scale up ( doing scale x 2) on my texture. I decided to have all my texture in scale x2 (so my raw .PNG are two times bigger than the size of the object on Flash).

Finally to have the correct size, I scaled down x 0.5. It was perfect on 4.8.5 but now it's blurry on 5.0.0rc.

I tried to reproduce it by using a x2 image of the bunny.png

http://93.113.206.174/pixi485_2.html
http://93.113.206.174/pixi500_2.html

We can see that the bunny from 5.0.0rc is one pixel bigger but it's only in the renderer, when I do the localBounds it has the same size on both.

```
// 4.8.5
	PIXI.settings.ROUND_PIXELS = true;
	PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.LINEAR;

	var renderer = new PIXI.autoDetectRenderer(160, 190,  { transparent: true, resolution: 1 });
    var bunny = new PIXI.Container();

    document.getElementById("renderer1").appendChild(renderer.view);
	let tmpTexture = new PIXI.Sprite(PIXI.Texture.fromImage("bunny2.png"));
	bunny.addChild(tmpTexture);
	
	  var inn = setInterval(function (r) { renderer.render(bunny); }, 1000 / 24);

	bunny.scale.x = 0.5;
	bunny.scale.y = 0.5;

// 5.0.0
	PIXI.settings.ROUND_PIXELS = true;
	PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.LINEAR;
	
	var renderer = new PIXI.Renderer(160, 190,  { transparent: true, resolution: 1 });
    var bunny = new PIXI.Container();

    document.getElementById("renderer1").appendChild(renderer.view);
	let tmpTexture = new PIXI.Sprite(PIXI.Texture.from("bunny2.png"));
	bunny.addChild(tmpTexture);
	
	  var inn = setInterval(function (r) { renderer.render(bunny); }, 1000 / 24);

	bunny.scale.x = 0.5;
	bunny.scale.y = 0.5;

```

![bunny2](https://user-images.githubusercontent.com/25887041/52212036-d45de800-288b-11e9-8afb-c9e785b01178.png)

You can see how it is more blurry on the 5.0.0 and it's taller. 

### Environment
Firefox & Chrome last version on Windows

On Edge it's the contrary, it's better (less blurry) on the 5.0.0rc than the 4.8.5

**Comment by T-vK** [comment]
On 5.0.0-rc you use `new PIXI.Renderer` whcih from my understanding will force the use of WebGL. In your 4.8.5 code, you use `PIXI.autoDetectRenderer` which returns either an instance of `PIXI.CanvasRenderer` or `PIXI.Renderer` depending on your OS/browser/settings/addons...

Interestingly though, `PIXI.autoDetectRenderer` appears to be broken in 5.5.0-rc or it was removed. But it should be there [according to the documentation](https://pixijs.download/v5.0.0-rc/docs/PIXI.html#.autoDetectRenderer)... https://jsfiddle.net/fzL0py8o/  
I don't know, maybe I'm just going crazy.

**Comment by bigtimebuddy** [comment]
You're not crazy, we need to make this more explicit in the docs, but `PIXI.autoDetectRenderer` is only found in **pixi.js-legacy** package. There's not canvas-related renderer functionality in **pixi.js**.

**Comment by Dosseum** [comment]
> On 5.0.0-rc you use `new PIXI.Renderer` whcih from my understanding will force the use of WebGL. In your 4.8.5 code, you use `PIXI.autoDetectRenderer` which returns either an instance of `PIXI.CanvasRenderer` or `PIXI.Renderer` depending on your OS/browser/settings/addons...
> 
> Interestingly though, `PIXI.autoDetectRenderer` appears to be broken in 5.5.0-rc or it was removed. But it should be there [according to the documentation](https://pixijs.download/v5.0.0-rc/docs/PIXI.html#.autoDetectRenderer)...
> https://jsfiddle.net/fzL0py8o/
> I don't know, maybe I'm just going crazy.

Thank you for the reply but i'm pretty sure i'm in WebGL with 4.8.5 on my game because i can use ColorMatrix :/



> You're not crazy, we need to make this more explicit in the docs, but `PIXI.autoDetectRenderer` is only found in **pixi.js-legacy** package. There's not canvas-related renderer functionality in **pixi.js**.

Yes it seems to be broken, i thought it was just deleted

**Comment by ivanpopelyshev** [comment]
Cant open those demos.

Also in 5.0.0 with webgl2 bunnies are mipmapped, even if they dont have pow2 texture.

Try this:

```js
PIXI.settings.MIPMAP_TEXTURES = false;
```

**Comment by Dosseum** [comment]
> ```js
> ```js
> PIXI.settings.MIPMAP_TEXTURES = false;
> ```
> ```

Thanks for reply, sorry for the demo (I forgot to renew my subscription of my VPS)

Here's the code I used 

```
  | PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.LINEAR;
  |  
  | var renderer = new PIXI.Renderer(160, 190,  { transparent: true, resolution: 1 });
  | var bunny = new PIXI.Container();
  |  
  | document.getElementById("renderer1").appendChild(renderer.view);
  | let tmpTexture = new PIXI.Sprite(PIXI.Texture.from("bunny2.png"));
  | bunny.addChild(tmpTexture);
  |  
  | var inn = setInterval(function (r) { renderer.render(bunny); }, 1000 / 24);
  |  
  | bunny.scale.x = 0.5;
  | bunny.scale.y = 0.5;


```
