### ISSUE TITLE
Wrap Text around Image

### ISSUE THREAD

**Issue by omidahourai** [pixijs/pixi.js#5408]
I'm looking for a way to wrap text around a square image, similar as you would in word documents. My image is 60x60, and I have `wordWrap=true` and `wordWrapWidth=250` for the text object. Does anyone know a good way? I'm thinking if I parse it manually, I would somehow have to:

________   abc abc abc abc
|...........|  abc abc abc
|_______|  abc abc abc abc
abc abc abc abc abc abc
abc abc abc abc

1. calculate the line height
2. calculate how many lines are rendered when displaced by the image (wordWrapWidth set to 250-60=190)
3. chop the text at the correct breaking word, and create 2 separate text objects
4. align them to fit accordingly

But again, this seems tedious, especially since I'm using dynamic texts/ image sizes.

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
No, we dont have a good way for that. Please code it and share it with us :)

**Comment by bigtimebuddy** [comment]
In general Pixi doesn’t do text layout with the exception of multi line wrapping. This type of flow layout would be a good idea for a plugin. You could use PIXI.TextMetrics to compute the layout.

The other option is to layout with SVG which would support a css float and then render that to a Texture or canvas. This approach would not use the Text object at all.
