### ISSUE TITLE
Pixi 5.0.0rc SimpleMesh Tints broken?

### ISSUE THREAD

**Issue by fanjules** [pixijs/pixi.js#5414]
Had a tinting bug occur in my current project which I am migrating to pixi5 and able to reproduce:

https://jsfiddle.net/fanjules/xer523nw/19/

With SimpleMesh over a certain number of vertices, the tint red channel is reversed with the blue channel.  In the example above I am able to draw 24 boxes (2 triangles per box), any more than that an the bug occurs.   Change LboxCount value to observe.

5.0.0rc
Chrome 71.0.3578.98 
Windows 10

**Comment by JetLua** [comment]
me too

**Comment by JetLua** [comment]
https://github.com/pixijs/pixi.js/blob/dev/packages/mesh/src/MeshMaterial.js#L146
```js
premultiplyTintToRgba(this._tintRGB, this._alpha, this.uniforms.uColor, baseTexture.premultiplyAlpha);
```
@ivanpopelyshev should change `this._tintRGB` to `this.tint`？I tried to modify code and run normally.
```
premultiplyTintToRgba(this.tint, this._alpha, this.uniforms.uColor, baseTexture.premultiplyAlpha);
```

**Comment by ivanpopelyshev** [comment]
Oops, i didnt notice that issue :)
