### ISSUE TITLE
cacheAsBitmap makes container 'jump'

### ISSUE THREAD

**Issue by takopus** [pixijs/pixi.js#5416]
This issue might intersect with some other cacheAsBitmap issues, but I've got a workaround and working example of it, just in case this will help someone.

If we have a PIXI.Container with some stuff in it, and it's bounds are not integers, and all of it's content positioned somewhere far from 0:0 coordinates, toggling cacheAsBitmap will make this container 'jump': move some pixels up and left. The farther from 0:0 is content, the farther it will jump.
Bug can be seen through comparing bounds of the container before and after cacheAsBitmap toggling. Only in Canvas mode, though: in WebGL mode bounds will be the same, even though the jump is obvious.

Problem seen in pixi.js PixiJS 4.8.1 on both WebGL and Canvas renderers and in Chrome and Firefox browsers for Windows 7.

There is a workaround for this bug: before setting cacheAsBitmap add something to 0:0 of the container. 1x1 pixel transparent Graphics rectangle would do.

Full exmaple with a workaround and explainations:
https://codepen.io/takopus/pen/NoXGMv

**Comment by ivanpopelyshev** [comment]
Good job! Lets add it to collection and wait when some hero solves all of the issues of `generateTexture` derivatives. Maybe i'll give it one more shot this year.

**Comment by ivanpopelyshev** [comment]
Oh yeah, in latest v4 it works , but it CRASHES when i set cacheAsBitmap back to `false` , lol!

**Comment by ivanpopelyshev** [comment]
Summary: yeah, i fixed that somewhere v4.x, but cacheAsBitmap was broken for canvas renderer. I've made PR.

**Comment by takopus** [comment]
Yes, in 4.8.5 it crashes on setting cacheAsBitmap to true for the second time and on getting bounds after setting it to false for the first time. On the other hand, in 4.8.5 my initial bug is gone, there's no jumping around. Looks like a serious bug to me, will have to stick to 4.8.1 for now.
Thank you for update!

**Comment by Dairnon** [comment]
I believe this was solved. Thanks @ivanpopelyshev
