### ISSUE TITLE
Pixi 5.0.0-rc: CanvasRenderer not instantiated when forceCanvas is true

### ISSUE THREAD

**Issue by nikolas** [pixijs/pixi.js#5417]
### Expected Behavior
I expect `(new PIXI.Application({forceCanvas: true})).renderer` to yield a `CanvasRenderer`.

### Current Behavior
`(new PIXI.Application({forceCanvas: true})).renderer` gives me a `Renderer`, using WebGL.

### Possible Solution
Well.. my solution for now is to just continue using Pixi 4.x.

### Steps to Reproduce
* Run `(new PIXI.Application({forceCanvas: true})).renderer` with pixi 5.0.0-rc.

### Environment

- **`pixi.js` version**: 5.0.0-rc
- **Browser & Version**: Brave 0.59.35, and Chromium 72.0.3626.53 
- **OS & Version**: Debian buster/testing
- **Running Example**: http://nikolas.us.to/lunar-phase-sim/

**Comment by themoonrat** [comment]
You need to use the legacy package to gain canvas support

**Comment by bigtimebuddy** [comment]
Duplicate issue, see explanation here: https://github.com/pixijs/pixi.js/issues/5389#issuecomment-457889307
