### ISSUE TITLE
In Chrome mobile , there will be an error about event.preventDefault

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#5421]
![image](https://user-images.githubusercontent.com/288367/52518027-634d7480-2c7f-11e9-91ea-04778169db23.png)

there is a thread talk about it : 

https://stackoverflow.com/questions/26478267/touch-move-getting-stuck-ignored-attempt-to-cancel-a-touchmove

**Comment by finscn** [comment]
Maybe we could do this in  `InteractionManager.js` : 
```
    onPointerDown(originalEvent)
    {

        // ... ...

        const cancelable = originalEvent.cancelable || !('cancelable' in originalEvent);

        if (cancelable && this.autoPreventDefault && events[0].isNormalized)
        {
            originalEvent.preventDefault();
        }

        // ... ...

    }
```

**Comment by finscn** [comment]
Maybe it's also in pixi v5

**Comment by themoonrat** [comment]
I think your solution looks good
