### ISSUE TITLE
Running into offset bug when drawing sprites

### ISSUE THREAD

**Issue by cuddlemeister** [pixijs/pixi.js#5426]
### Expected Behavior

I have the map on which I need to draw some amount of hexagons (approximately it will be from 50*50 to 150*150 elements).

When I draw them on the canvas using PIXI, I get really strange behavior: while it's not a lot of elements, the map has been drawn correctly, all the elements on their places. But when the canvas size changed to about 5000px width and height, all the elements are moved top above the screen. Moreover, the click on the element has been handled on the place where it should be.

I've created a pen to demonstrate this: https://codepen.io/cuddlemeister/pen/OdzMBw

### Steps to Reproduce

Try to change canvasWidth and canvasHeight in the evnironment from
`canvasWidth: 1500,  canvasHeight: 1500` to `canvasWidth: 4500,  canvasHeight: 7500` and you will see the result.

You will the that all the visible content has been moved in top direction and it depends on the height of the canvas.

There's a logger enabled on click, try to click the elements or the area where they are supposed to be - the click is handled correctly on the place where the element should be

**Comment by themoonrat** [comment]
I know a lot of devices have a canvas limit of 4096x4096. Have a play and see if things start going wrong over that limit, as that could be the issue.

**Comment by cuddlemeister** [comment]
> I know a lot of devices have a canvas limit of 4096x4096. Have a play and see if things start going wrong over that limit, as that could be the issue.

Seems like you are right. I didn't know about that limit and behavior of the canvas was looking really strange to me. Thank you.
