### ISSUE TITLE
Renderer.reset is breaking things

### ISSUE THREAD

**Issue by Samsy** [pixijs/pixi.js#5427]
**Is it only supposed to reset the webGL state only ?** 
I suspect this method omits to reset some states ? and is breaking things.

Running renderer.reset in a loop before getting things drawn on screen is breaking things

PixiJS 4.8.5 :
https://jsfiddle.net/johndordman/e7ajcfgy/4/
Returns an error " Source and destination textures of the draw are the same "
The example here is trying to render thing in a framebuffer and on screen, but there might be a confusion in the framebuffer bindings using renderer.reset ?

PixiJS 5.0 :
https://jsfiddle.net/johndordman/x4nvwfaz/17/
Returns no error, but don't show anything on screen as well, just the blue background but not the sprite.

Removing the renderer.reset line makes each of them working.

**Expected render :** 

![capture d ecran 2019-02-10 a 13 35 04](https://user-images.githubusercontent.com/3786958/52533759-e4b50d80-2d38-11e9-8c25-264890faca5c.jpg)

**Comment by ivanpopelyshev** [comment]
Yep, its a bug. `reset()` is supposed to reset both pixi and wegl state. In case someone wants to use threejs or other renderer lib or pure webgl code with pixijs. If its called from outer code (not renderer internals), it should not affect the application.

**Comment by Samsy** [comment]
That is the final use-case actually, the interoperability between PIXI and THREE, any clue how to hot fix ( if there is one known ? )

**Comment by ivanpopelyshev** [comment]
The problem is that multiTextureRenderer has many samplers and one of them points to that renderTexture.

Re-bind all textures in `reset` to emptyTextures, you can find them in pixi WebGLRenderer. However, im gonna make better implementation today, lazy one, I'll add it to `unbind` function, so pixi will re-bind empty textures only on .

**Comment by ivanpopelyshev** [comment]
I fixed your case in v4, but it looks like v5 `reset` doesnt work properly, I need more time to fix everything.

**Comment by ivanpopelyshev** [comment]
v4 build is here: https://pixijs.download/v4.x-reset-textures/pixi.js

**Comment by ivanpopelyshev** [comment]
Reset state for v5 build: https://dev-reset-textures/dev-reset-textures/pixi.js

Yeah!

**Comment by Samsy** [comment]
Very nice, 
I did hack the reset function as well with the same thing,
Thank for doing it more officially ;)
