### ISSUE TITLE
Loading image as texture should be asynchronous

### ISSUE THREAD

**Issue by jdelrue** [pixijs/pixi.js#5428]
When loading an image as a texture (new or deprecated method) there should be a callback function, since loading images in javascript is asynchronous.

### Expected Behavior
Image is loaded immediately 
### Current Behavior
Image is loaded async, causing weird issues
### Possible Solution
Load image in js first, then use onload handler to do more work.
### Steps to Reproduce

```
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

var container = new PIXI.Container();



var texture = PIXI.Texture.fromImage('https://pixijs.io/examples/required/assets/basics/bunny.png');


var bunny = new PIXI.Sprite(texture);

var text = new PIXI.Text("hello world");
container.addChild(text);
container.addChild(bunny);

/* setTimeout(function() { */
  
  
var renderTexture = PIXI.RenderTexture.create(500, 500);
app.renderer.render(container, renderTexture);

let sprite1 = new PIXI.Sprite(renderTexture);
sprite1.x = 0;
sprite1.y = 0;
  
app.stage.addChild(sprite1);
/* } , 200);*/
```

(enable/disable commented lines to see difference in result)
### Environment
Chrome 71

- **`pixi.js` version**: . 4.8.5 

- **OS & Version**:  Ubuntu 18.04

**Comment by themoonrat** [comment]
We always recommend loading textures via the loader http://pixijs.download/v4.8.5/docs/PIXI.loaders.html#.shared which gives the ability to track load progress as desired.
https://pixijs.io/examples/#/basics/spritesheet.js gives an example of this

**Comment by englercj** [comment]
The BaseTexture also emits `'loaded'` when the load completes.
