### ISSUE TITLE
Namespace 'PIXI.AnimatedSprite' has no exported member 'textures'

### ISSUE THREAD

**Issue by Skuriles** [pixijs/pixi.js#5433]
Hello,
I'm using pixi with typescript, Pixi V5rc.

I import pixi like that:
import * as PIXI from "pixi.js";

But in Typescript I can't use things like that

`textures: PIXI.AnimatedSprite.textures;`

to do something like that (change the textures of a sprite)
`this.sprite.textures = this.textures;`

Error:
Namespace 'PIXI.AnimatedSprite' has no exported member 'textures'. It works if I set all types to "any", so it looks like that the typedef is not wokring correctly?!

But from the API I can't find that this should be wrong or that there is a method like "setTextures" or something.

Background:
I'm trying to switch textures from a AnimatedSprite.
Or would it be better to pack all textures to the sprite from the beginning and only switch animation index for the textures? But I didn't found to to this as well...

Thanks for all help!

**Comment by ivanpopelyshev** [comment]
That's what I see in typings:

```
textures: PIXI.Texture[];
```

Try that one:

```ts
let textures: Array<PIXI.Texture> = [tex1, tex2, tex3];

animSprite.textures = textures;
```

**Comment by bigtimebuddy** [comment]
It's a property of the `AnimatedSprite` class, not a namespace property. Are you doing something like this:

```js
const animSprite = new PIXI.AnimatedSprite();
animSprite.textures = [texture1, texture2, texture3];
```

**Comment by Skuriles** [comment]
> It's a property of the `AnimatedSprite` class, not a namespace property. Are you doing something like this:
> 
> ```js
> const animSprite = new PIXI.AnimatedSprite();
> animSprite.textures = [texture1, texture2, texture3];
> ```

If I do something like this, the compiler will show the above mentioned warning.

Code would be:

```
export default class Direction {
  **sprite: PIXI.AnimatedSprite;**
...
some more properties
...
  constructor(main: Main) {
...
    **this.sprite = null; => not allowed!!!!**
...
  }

  setSprite(sprite: PIXI.AnimatedSprite) {
    this.sprite = sprite;
  }

  startAnimation() {
    switch (this.currentKey) {
      case Key.DOWN:
        **this.sprite.textures = this.downTextures; ===> PIXI.AnimatedSprite has no exported member "textures"**
        break;
      case Key.UP:
        this.sprite.textures = this.upTextures;
        break;
... etc. etc.      
    }
    this.sprite.animationSpeed = 0.5;
    this.sprite.play();
  }
```

**Comment by ivanpopelyshev** [comment]
and what's `downTextures`?

**Comment by Skuriles** [comment]
> and what's `downTextures`?

it is from the same type: PIXI.AnimatedSprite.Textures, tried PIXI.AnimatedSprite.textures as well, both not working. 
If I use type any for everything it works, but this kills a little bit the advantage of using Typescript...
To be clear: So it is just a TypeDef problem..

**Comment by Skuriles** [comment]
Forget everything I wrote and sorry for wasting your time...
My bad. You were right: I used AnimatedSprite.Textures as namespace instead of PIXI.Texture[]. Stupid mistake.
Sorry and thanks
