### ISSUE TITLE
loader onComplete called twice. resources.textures empty in first call.

### ISSUE THREAD

**Issue by rkdrnf** [pixijs/pixi.js#5437]
```PIXI.loader.onComplete``` event callback is called twice.

in a first call, ```PIXI.loader.resources["resourceName"].textures``` is undefined.
in a second call it is populated.

I think it might be a bug.
and additionally, is there any callback that is called after all resource loader middlewares are processed?
I need callback after ```textures```field is populated.

pixi.js - 4.8.2

**Comment by rkdrnf** [comment]
I found that it's not always twice.
sometimes it is called only once, and the ```textures``` field is also populated when it is called only once.

and also the event order between ```complete``` event and ```load``` event is also inconsistent.

**Comment by englercj** [comment]
Can you create a [playground](https://pixiplayground.com/#/edit) that reproduces this behavior? The `onComplete` signal is only sent once, when middleware processing is complete. Anything else is a bug.

**Comment by themoonrat** [comment]
@rkdrnf Do yo think you could create this playground for us please? Thanks!

**Comment by rkdrnf** [comment]
From my experience, it only happend while I turned on Chrome WebGL Inspector extension. I will make a playground soon.
