### ISSUE TITLE
pixi 5.0 rc createContext with power preference option set crashes on Safari (black screen)

### ISSUE THREAD

**Issue by NikkiKoole** [pixijs/pixi.js#5438]
Hiya, just noticed a 5.0rc is available and started playing with it.
Very cool stuff, I have a rather big project to update from 3.0.10 to 5.0 , hope all goes well  and looking forward to all the great stuff.
The bunny mark on Safari breaks on 5.0rc though.
https://pixijs.io/bunny-mark/

I've narrowed it down to the powerPrefernce setting in the options.
when you remove that its fine and just returns null 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext
(there are a whole lot of browser that don't support the powerPreference, I havent checked if they all fail so miserably, I imagine Safari is worse then others.)

ContextSystem.js line 112
`canvas.getContext('webgl2', options)`

### Expected Behavior
 when using a browser that doesn't support webGL2 (like Safari) it probably shouldn't break alltogether ;)
### Current Behavior
You are presented a black screen and a Type  Error (on Safari)
### Steps to Reproduce
use the bunny mark on Safari and pick 5.0
### Environment

- **`pixi.js` version**: 5.0
- **Browser & Version**: Safari Version 12.0.2 (14606.3.4)
- **OS & Version**: macOS Mojave

**Comment by themoonrat** [comment]
It's because the bunny mark uses a boolean for power-preference, when it needs to be a string. So a problem with bunnymark, not pixi :)

**Comment by NikkiKoole** [comment]
Ah great to know, I tried it using 'default' and its fine indeed.
