### ISSUE TITLE
Can't update vec2 uniform after creation

### ISSUE THREAD

**Issue by georgealways** [pixijs/pixi.js#5439]
I'm able to update simple 1d uniforms like floats after creation, but can't seem to do the same for a 2d value.

```js
const filter = new PIXI.Filter(null, shader, { 
  testVector2: {
    type: 'v2',
    value: { x: 100, y: 100 }
  }
});

sprite.filters = [filter];

filter.uniforms.testVector2.x = 0; // does nothing
gui.add(filter.uniforms.testVector2, 'x'); // does nothing
```

### Environment

- **`pixi.js` version**:  4.8.5

**Comment by ivanpopelyshev** [comment]
that's old pixi-v2 format
you can just pass `testVector2: {x:100, y:100}` there.

**Comment by bigtimebuddy** [comment]
Seems answered, closing.
