### ISSUE TITLE
Fullscreen mode shifts the active area of a DisplayObject.

### ISSUE THREAD

**Issue by Ujimych** [pixijs/pixi.js#5440]
Fullscreen mode shifts the active area of a DisplayObject.

Below is the complete code of the example:
```
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
	app.view.id = "myCanvas";
document.body.appendChild(app.view);

document.cancelFullScreen = document.cancelFullScreen || document.webkitCancelFullScreen || document.mozCancelFullScreen;

var inFullscreen = false;
var el = null;
var _fullscreenBtn = createBtn(100, 20);

var info = new PIXI.Text('Click Bunny to go full screen');
	info.x = 30;
	info.y = 90;
app.stage.addChild(info);

function createBtn(x, y) {
    var btn = new PIXI.Sprite(PIXI.Texture.fromImage('https://pixijs.io/examples/examples/assets/bunny.png'));
		btn.interactive = true;
		btn.buttonMode = true;
		btn.on('pointerup', btn_onDragEnd);
		btn.x = x;
		btn.y = y;
    app.stage.addChild(btn);
}

function btn_onDragEnd() {
    fullscreen(!inFullscreen);
}

function fullscreen(value) {
	if(el == null) {
		var el = document.getElementById("myCanvas");
			el.addEventListener("webkitfullscreenchange", onFullscreenChange);
			el.addEventListener("mozfullscreenchange", onFullscreenChange);
			el.addEventListener("fullscreenchange", onFullscreenChange);
	}
	
	if(value) {
		if (el.webkitRequestFullScreen) {
			el.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
		} else {
			el.mozRequestFullScreen();
		}
	}
	else {
		document.cancelFullScreen();
	}
}

function onFullscreenChange(e) {
	inFullscreen = !inFullscreen;
	
	var msg = !inFullscreen ? "Click Bunny to go full screen" : "Bunny remained in place, but his active area shifted to the left";
	info.text = msg;
}
```

- **`pixi.js` version**:  4.0.0 ... 5,0,0
- **Browser & Version**: Chrome 71, Opera 57, FireFox 65
- **OS & Version**: Windows, Android
- **Running Example**: https://jsfiddle.net/fdcz4mL2/

**Comment by bigtimebuddy** [comment]
Just to clarify, the interactive area for the bunny moves in fullscreen mode.  Seems like a bug.

This happens if you request fullscreen on the `<canvas>` element. As a workaround, if you request fullscreen on a `<div>` element wrapping the canvas, you could adjust the CSS to position the canvas. 

For instance: https://jsfiddle.net/bigtimebuddy/2mvwsnuj/

With this workaround, interactive positioning seems to be okay.

**Comment by ivanpopelyshev** [comment]
Where do you call `renderer.resize()`?

Also if interaction stuff goes wrong you can debug `mapPositionToPoint`: https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/InteractionManager.js#L962

If you want to handle strange case that pixi interaction doesn't cover,  just hack your own function there:

```
renderer.interaction.mapPositionToPoint = function() { ... }
```

**Comment by bigtimebuddy** [comment]
The user isn't using `renderer.resize`, they are fullscreening the canvas element directly, which doesn't change the renderer size. There's something funny here about the renderable area versus the horizontal offset (black bars) that are considered part of the target element. So the position in InteractiveManager are all messed up. Someone needs to dig into how canvas behaves in fullscreen mode. But there's a suitable workaround, so I don't think this is high priority.

**Comment by Ujimych** [comment]
Thanks for the workaround

**Comment by ivanpopelyshev** [comment]
`mapPositionToPoint` is a good point for fast fixes in that case anyway ;) Add extra checks for those bars if you figure out how those bars work.
