### ISSUE TITLE
vertexData null after creating graphics object and using drawRect

### ISSUE THREAD

**Issue by MRVDH** [pixijs/pixi.js#5448]
### Expected Behavior
vertexData is present

### Current Behavior
vertexData is not present

### Possible Solution
add callback/promise

### Steps to Reproduce
```javascript
var testGraphic = new PIXI.Graphics();
testGraphic.beginFill(0xff0000);
testGraphic.drawRect(150, 150, 600, 200);
testGraphic.endFill();
app.stage.addChild(testGraphic);
// no vertexData
testGraphic.calculateVertices();
// still no vertexData
console.log(testGraphic.vertexData); // -> null
```

### Environment

- **`pixi.js` version**: * v5.0.0-rc
- **Browser & Version**: * Chrome 72.0.3626.81 (Official Build) (64-bit)
- **OS & Version**: * Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/d4keZhFdWFMNYvWyTUWVh

**Comment by MRVDH** [comment]
For now I fixed this by adding the following code at the end, but it's kind of a hack.

```javascript
continueThis();
function continueThis() {
    if (!testGraphic.vertexData) {
        setTimeout(continueThis, 5);
    } else {
        console.log(testGraphic.vertexData); 
    }
}
```

**Comment by ivanpopelyshev** [comment]
There's a protected method `graphics.geometry.updateBatches();` that has to be called to get `graphics.points`
