### ISSUE TITLE
Moving object to parent resets the position of the object

### ISSUE THREAD

**Issue by MRVDH** [pixijs/pixi.js#5455]
### Expected Behavior
1. Put object in the stage at x<sup>1</sup> and y<sup>1</sup>.
2. Move the object from the stage to the container.
3. Move the position of the container to x<sup>2</sup> and y<sup>2</sup>.
4. Move the object from the container to the stage.
5. Object is put on the stage on the new position x<sup>2</sup> and y<sup>2</sup>.

### Current Behavior
1. to 4. -> Same
5. Object is put on the stage back on the old position x<sup>1</sup> and y<sup>1</sup>.

### Possible Solution
?

### Steps to Reproduce
See the example: https://www.pixiplayground.com/#/edit/_rVNfoO9FC78pxT9603tv
```javascript
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

// Load the bunny texture
app.loader.add('bunny', 'https://pixijs.io/examples/examples/assets/bunny.png')
    .load(startup);

function startup()
{
    // set bunny position
    var bunny = new PIXI.Sprite(app.loader.resources.bunny.texture);
    app.stage.addChild(bunny);
    bunny.x = app.renderer.width / 2;
    bunny.y = app.renderer.height / 2;
    bunny.anchor.x = 0.5;
    bunny.anchor.y = 0.5;
    bunny.angle = 90;
    
    // create container
    var cont = new PIXI.Container();
    app.stage.addChild(cont);
    cont.pivot.x = cont.x;
    cont.pivot.y = cont.y;
    cont.addChild(bunny);

    // move and rotate container
    cont.x += cont.x + 100;
    cont.y += cont.y + 100;
    cont.angle = 30;

    cont.updateTransform();

    // comment out the line below to see the expected location
    app.stage.addChild(bunny);
}
```

### Environment
- **`pixi.js` version**: v5.0.0-rc2
- **Browser & Version**: Chrome 72.0.3626.81 (Official Build) (64-bit)
- **OS & Version**: Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/_rVNfoO9FC78pxT9603tv

**Comment by ivanpopelyshev** [comment]
Bunny local transform is changed only in beginning, where you set `x`, `y` and `angle`. Moving stuff to container does not change local transform. Moving stuff back does not change it too.

I do not know of renderer lib, or big framework that works like you described. Pixi in this case works like Flash does.

**Comment by ivanpopelyshev** [comment]
It can be achieved with a combination of `toLocal`, `toGlobal` functions, or direct matrix operations with `transform.worldTransform` and `transform.localTransform`, `transform.setFromMatrix(...)`

**Comment by bigtimebuddy** [comment]
Seems like @ivanpopelyshev answered the question. Let us know if this hasn't been answered @MRVDH.

**Comment by MRVDH** [comment]
Correct, thanks for the information :)
