### ISSUE TITLE
[v5] Mipmaps are not generated for RenderTexture

### ISSUE THREAD

**Issue by Teoxoy** [pixijs/pixi.js#5458]
In v5, mipmaps are set to off by default in the BaseRenderTexture class.
https://github.com/pixijs/pixi.js/blob/b5d63bd7742ecebf40317d3a3199630b0eb18384/packages/core/src/renderTexture/BaseRenderTexture.js#L73

The BaseTexture class sets mipmaps on or off based on the global mipmap setting.
https://github.com/pixijs/pixi.js/blob/b5d63bd7742ecebf40317d3a3199630b0eb18384/packages/core/src/textures/BaseTexture.js#L86

I don't think this is the intended behavior.
This change was added in 7d0bbd1 (#4707).

**Comment by ivanpopelyshev** [comment]
Its intended behaviour. Some apps update renderTextures every frame.

**Comment by Teoxoy** [comment]
Oh, ok. Just wanted to make sure it is intended.

I was using `renderTexture.baseTexture.mipmap = PIXI.MIPMAP_MODES.POW2` before rendering the renderTexture to set the mipmap.

I guess I will close this issue then.
