### ISSUE TITLE
Graphics.generateCanvasTexture() is undefined.

### ISSUE THREAD

**Issue by zzybccdb** [pixijs/pixi.js#5461]
### Expected Behavior
expected this function exsits
### Current Behavior
Graphics.generateCanvasTexture() is undefined
### Possible Solution
empty
### Steps to Reproduce
```html
<html>
<script src="pixi.min.js"></script>
<script>
let g = new PIXI.Graphics()
console.log(g.generateCanvasTexture)
</script>
</html>
```
### Environment
- **`pixi.js` version**: _v5.0.0-rc.2_
- **Browser & Version**: _e.g. Chrome Version 71.0.3578.98 (Official Build) (64-bit)_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
use pixi-legacy bundle.

**Comment by themoonrat** [comment]
Ivan: There are a couple of unit tests that currently rely on this function existing (interactionManager and getLocalBounds). Do all unit tests use pixi-legacy?

**Comment by bigtimebuddy** [comment]
Interaction includes canvas-graphics as a devdependency so it can be used in tests.

**Comment by bigtimebuddy** [comment]
Question was answered by @ivanpopelyshev. Closing
