### ISSUE TITLE
lines in one graphic event

### ISSUE THREAD

**Issue by xiaoshidetaikuai** [pixijs/pixi.js#5465]
like this fiddle [https://jsfiddle.net/Fboy/pf6cx592/2/](https://jsfiddle.net/Fboy/pf6cx592/2/) 
I use one graphic to draw more lines,I want add event for every lines.How do I change it?

**Comment by ivanpopelyshev** [comment]
I cant interpret what do you want. Please provide more information.

**Comment by xiaoshidetaikuai** [comment]
I want when mouse hover line,to change lines color,or width and more for each line

**Comment by ivanpopelyshev** [comment]
Sorry, pixi does not have that feature.

easy way: each line is its own graphics. Its slow.
hard way: use Mesh instead, override containsPoint that way it modifies the mesh. Add colors in shader
hard way #2: take Graphics element, copy all the code, or just override parts that matter: containsPoint, lines rebuild algorithm. Its possible, but its very hard way.

**Comment by xiaoshidetaikuai** [comment]
I have tried the simple method, it is really slow, I will try the second method. thanks a lot
