### ISSUE TITLE
Text shadow is too big on Safari with 'dropShadowBlur' set

### ISSUE THREAD

**Issue by smikheiev** [pixijs/pixi.js#5467]
Shadow in Safari is huuuge if to set parameter `dropShadowBlur` in text style.
Without it the text looks the same in both Safari and Chrome

### Environment
- **`pixi.js` version**: _v5.0.0-rc.2_
- **Browser & Version**: _Safari 12.0_
- **OS & Version**: _e.g. MacOS 10.14_
- **Running Example**: _https://pixiplayground.com/#/edit/o8JjRrCi2YoY2waBSXe4C_

**Comment by ivanpopelyshev** [comment]
Just copying your comment from slack: 

> I got this problem in version 4.6.2, but also can reproduce this problem with pixi examples with the latest development version

**Comment by themoonrat** [comment]
I see exactly the same in Edge, Firefox and Chrome on my Windows 10 PC.

So I'm wondering if this is a Safari issue...

I've put together a playground that puts pixi at the top versus the native canvas api at the bottom, with the same style. How do these shadows compare?
https://pixiplayground.com/#/edit/WgIUhuAPCGOxedLTZ23VU

**Comment by bigtimebuddy** [comment]
Chrome on top, Safari on the bottom.
![screen shot 2019-02-21 at 9 02 05 am](https://user-images.githubusercontent.com/864393/53187169-64ec3600-35b7-11e9-8b38-409a49f9b504.png)

Seems like a browser issue. Any ideas on how we might work around?

When I changed the blur amount in Safari from `24` to `12`, it looks closer.
![screen shot 2019-02-21 at 9 04 41 am](https://user-images.githubusercontent.com/864393/53187334-c44a4600-35b7-11e9-8f68-6b507e982b9e.png)

**Comment by ivanpopelyshev** [comment]
/sacrasm mode on

Use BlurFilter

/sarcasm mode off

Well, actually that's something for the future. Right now we can try something with getImageData, we already use it for font detection.

**Comment by bigtimebuddy** [comment]
Anyone care to research why Safari is doing this? Maybe default units are different? Maybe a bug?

**Comment by themoonrat** [comment]
I really can't see us doing anything wrong on this, and trying to compensate for Safari being broken could cause problems if Safari fixes itself...

**Comment by marleneHoj** [comment]
Found an issue around this matter and did a playground this is a problem in mobile safari.
https://pixiplayground.com/#/edit/GnkCGHRo5BuNKbt4ezaHE
