### ISSUE TITLE
[Performance] Speed of playing animation is sometimes strangely fast in ios

### ISSUE THREAD

**Issue by chilin99999** [pixijs/pixi.js#5470]
Edit:

I find that I am wrong.
The problem doesn't happen in iOS, but in machines with poor hardware.

--
I run dragonbones skeleton animation with PIXI.
(Sorry I am not sure is it appropriate to ask here)

> this.factory = dragonBones.PixiFactory.factory;
> this.armatureDisplay = this.factory.buildArmatureDisplay('Bone', name);
> this.addChild(this.armatureDisplay);
> this.armatureDisplay.animation.play(actionName);

It's good in Chrome running in windows / android.
But the speed of playing animation is sometimes strangely fast in ios.
If I play the animation continuously, it works fine.
But if I wait for few seconds and then play it, the animation speed will be strangely fast!

### Environment

- **`pixi.js` version**: 4.8.5
- **Browser & Version**: Chrome 72
- **OS & Version**: ios12.1

**Comment by ivanpopelyshev** [comment]
I don't own iPhone and I don't use dragonBones. The only thing I can tell is that maybe its RequestAnimationFrame-related.

Pixi ticker in v4: https://github.com/pixijs/pixi.js/blob/v4.x/src/core/ticker/Ticker.js#L360

That's how to move update out of application: https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop

Add more update functions, log all delta's , put it on screen with pixi text or some other means.

**Comment by bigtimebuddy** [comment]
Could you please provide more information @chilin99999 or an example that we can test? It’s hard to know what you mean by strangely fast. Thanks.

**Comment by chilin99999** [comment]
I put part of my code in codepen to demo, but I found everything is working fine!
It's really strange..
Same code working fine in codepen but not in my real world application..

**Comment by chilin99999** [comment]
I find that I am wrong.
The problem doesn't happen in iOS, but in machines with poor hardware.
These machines with poor hardware will run animation with low fps.
(I see fps information in Chrome Rendering tool)

It's the original codepen:
(click the button to start animation)
https://codepen.io/chilin49/pen/drXzPe?editors=0010

It's the new codepen with loop to increase CPU usage to simulate machines with poor hardware:
https://codepen.io/sa212320/pen/VRjGed?editors=0010

Is there any way to alleviate this problem?

**Comment by chilin99999** [comment]
I know that there're some problems in machines with poor hardware is naturally.
But I wonder if there is a way to run animation in machines with poor hardware in fixed time.
Drop frame and not smooth is acceptable, but run animation sometimes quick and sometimes slow is not acceptable.

**Comment by ivanpopelyshev** [comment]
I still dont understand, is that PixiJS problem or dragonbones runtime problem?

**Comment by chilin99999** [comment]
Thanks for your applies!
I find that if I set the **minFPS** value to 60, the animation speed in every devices will be unified!
Although it will also set **delta** value to 1, and effect the operation of **ticker**.
But I think it's another issue.

``` javascript
PIXI.ticker.shared.minFPS = 60;
```

**Comment by themoonrat** [comment]
I believe this is down to a similar issue as https://github.com/pixijs/pixi.js/issues/5494 with how you were advancing time without using a delta. 

Will close for now, please re-open if there is something wrong
