### ISSUE TITLE
Container Events

### ISSUE THREAD

**Issue by davidfig** [pixijs/pixi.js#5471]
DisplayObject has the 'added' and 'removed' events. It would be helpful if Container included events for 'addedTo' and 'removedFrom' (or something along those lines) for when the container's children change. the Container.onChildrenChange() overridable is not ideal since it doesn't say what was added or removed.

Happy to create a PR if this is something that's interesting.

**Comment by bigtimebuddy** [comment]
Good idea, PR welcome!
