### ISSUE TITLE
Followup on pixi.js example question #2514

### ISSUE THREAD

**Issue by Arnold1** [pixijs/pixi.js#5478]
Hi,

I would like to follow up on this issue: https://github.com/pixijs/pixi.js/issues/2514

@whizzkid Why is it not using the entire canvas to draw the circles? I dont want to use unction onResize() to resize the window!
Here the updated fiddle: http://jsfiddle.net/5afkrqv9/

Can I do 
```
var maxX = window.innerWidth;
var maxY = window.innerHeight;
```
in that case?

like here?
http://jsfiddle.net/tvq3L2hf/

Thanks,
Arnold

**Comment by themoonrat** [comment]
@Arnold1 I'm not sure I understand the question, sorry. If it's help with using pixi, perhaps stackoverflow or html5gamedevs forum might find the audience for this? Cheers
