### ISSUE TITLE
Transform tool

### ISSUE THREAD

**Issue by juliocanares** [pixijs/pixi.js#548]
Hi guys , I'm trying to make a tool for transforming objects like this http://www.greensock.com/transformmanageras3/, according lei have to work with matrices of transformation, as I can do this in pixi.js?

**Comment by mrgoonie** [comment]
Sorry for digging but here is my plugin in case someone needs:

https://github.com/mrgoonie/pixi-transform-tool

Cheers!

**Comment by GoodBoyDigital** [comment]
Thats really cool @mrgoonie ! 👍
