### ISSUE TITLE
seems like rgb2hex or hex2string has bug

### ISSUE THREAD

**Issue by maple-leaf** [pixijs/pixi.js#5481]
### Expected Behavior
hex related color converter should work
### Current Behavior
hex related color converter output incorrect for some value
### Steps to Reproduce
Th `P` refers to `PIXI`

```
P.utils.hex2string(P.utils.rgb2hex([255, 255, 255]))
```

![image](https://user-images.githubusercontent.com/3980995/53611786-b4abac80-3c0a-11e9-9166-8340a00e82f3.png)

### Environment

- **`pixi.js` version**: 4.8.6
- **Browser & Version**: Chrome 72.0.3626.109
- **OS & Version**: macOS 10.14.3

**Comment by djmisterjon** [comment]
It come from **rgb2hex**  !
![Uploading image.png…]()

here a temp fix 
https://campushippo.com/lessons/how-to-convert-rgb-colors-to-hexadecimal-with-javascript-78219fdb

**Comment by djmisterjon** [comment]
ho well here the fix for pixijs 
`(rgb[0]<<16|rgb[1]<<8|rgb[2])`

it seem work
![image](https://user-images.githubusercontent.com/24865815/53614507-33233280-3ba8-11e9-809b-68c9036c3c64.png)

**Comment by ivanpopelyshev** [comment]
rgb array has values between 0.0 and 1.0 . not 0.0 and 255.0 

Maybe we have to be more clear in docs.

**Comment by djmisterjon** [comment]
That explains a lot of things. I work myself always with a range of 255 in rgb.
 Is the term rgb that creates confusion.
I noticed this same problem in my publisher at the time.
thank you for enlightening the situation.

**Comment by ivanpopelyshev** [comment]
OK, its `normalized RGB` now.
