### ISSUE TITLE
Turn the canvas content into base64 images

### ISSUE THREAD

**Issue by hacer-healer** [pixijs/pixi.js#5483]
app.renderer.plugins.extract.base64(app.stage)
Using this method causes the browser to crash.
Browser information :  Debugging connection was closed.Reason:Render process gone.Reconnect when ready by reopening DevTools.

**Comment by ivanpopelyshev** [comment]
Need more details. version of pixi, which device is it, e.t.c.

**Comment by ivanpopelyshev** [comment]
Oh, right, you didnt specify the area. It takes bounds of all the stage (which can be very big in your case) and tried to render it into renderTexture with that size. 

Specify bounds in that method please.

**Comment by hacer-healer** [comment]
The parameters only need to be converted to the base64 target (app. stage), without specifying boundaries in the method, the Pixi version is v4, running on Google Browser.

**Comment by ivanpopelyshev** [comment]
if your stage has width=10000 and height=10000 it will probably crash. Either you specify boundaries in that function either you dont supply the stage, ask it to take image from screen. If my words aren't understandable ( they usually are regrading to this plugin), please look in the sources of `extract.base64`and debug it, place breakpoints - you'll see what im talking about.

**Comment by hacer-healer** [comment]
If I don't provide the stage, it will save a duplicate image.

**Comment by hacer-healer** [comment]
Demo : https://codepen.io/hacer-healer/pen/YgGmBR
The spriteSum parameter controls the number of nodes.
RandomInt's two parameters control node coordinates.
The pixi version is 4.8.6.
When the pixi version is v5, only the visible area part of the image is generated

**Comment by hacer-healer** [comment]
Is there any recommended way to convert the entire canvas content to a picture?

**Comment by djmisterjon** [comment]
you have many way, this is old code and not update but take a look on the context.
Sorry it copy past some code are not userfull. 

// example 1
```javascript
    function snapMap(options) {
        const fs = require('fs');
        const pathName = `img/parallaxes/${$dataMap.parallaxName}.png`;
        const snap = Bitmap.snap2(Scene);
        const urlData = snap._canvas.toDataURL();
        const base64Data = urlData.replace(/^data:image\/png;base64,/, "");
        fs.writeFile(pathName, base64Data, 'base64', function(error){
            if (error !== undefined && error !== null) {  console.error('An error occured while saving the screenshot', error); } 
        });

   };

   Bitmap.snap2 = function(stage) {
    var width =  $dataMap.width*48;
    var height = $dataMap.height*48;
    var bitmap = new Bitmap(width, height);
    var context = bitmap._context;
    var renderTexture = PIXI.RenderTexture.create(width, height);
    if (stage) {
        Renderer.render(stage, renderTexture);
        stage.worldTransform.identity();
        var canvas = null;
        if (Graphics.isWebGL()) {
            canvas = Renderer.extract.canvas(renderTexture);
        } else {
            canvas = renderTexture.baseTexture._canvasRenderTarget.canvas;
        }
        context.drawImage(canvas, 0, 0);
    } else {

    }
    renderTexture.destroy({ destroyBase: true });
    bitmap._setDirty();
    return bitmap;
};
```

example 2

```javascript
    function snapScreenMap(options) {
        // create a snap to import in rmmv sofware
        CAGE_EDITOR.renderable = false;
        const w = CAGE_MAP.width;
        const h = CAGE_MAP.height;
        CAGE_MAP.position.set(0,h);
        CAGE_MAP.scale.set(1,-1);
        CAGE_MAP.pivot.set(0,0);
        const renderer = PIXI.autoDetectRenderer(w, h);
        const renderTexture = PIXI.RenderTexture.create(w, h);
            renderer.render($stage, renderTexture);
        const canvas = renderer.extract.canvas(renderTexture);
        const urlData = canvas.toDataURL();
        const base64Data = urlData.replace(/^data:image\/png;base64,/, "");
        const _fs = require('fs');
        const crypto = window.crypto.getRandomValues(new Uint32Array(1));
        _fs.writeFile(`testSnapStage_${crypto}.png`, base64Data, 'base64', function(error){
            if (error !== undefined && error !== null) {  console.error('An error occured while saving the screenshot', error); } 
        });
        // RESTOR
        CAGE_EDITOR.renderable = true;
        CAGE_MAP.position.set(0,0);
        CAGE_MAP.scale.set(1,1);
        CAGE_MAP.pivot.set(0,0);
   };
```

I was use thos custom method to take a prinscreen of the pixi stage and export in png for photoshop in multi  layer.

**Comment by djmisterjon** [comment]
i dont have this issue , but maybe you can try this 
https://github.com/niklasvh/html2canvas

But am not understand thats `only capture the canvas content of the visible window`
Maybe show a print-screen can help to understand.

**Comment by ivanpopelyshev** [comment]
The problem that you want 10000x10000, right? The idea is to split it into chunks and ask for small things, then save pngs somehow, then combine it to big one.

**Comment by hacer-healer** [comment]
I want to scale the canvas in another container. Like the small map in the game, the original sprite moves, and the zoom map also needs to be modified synchronously.
![无标题](https://user-images.githubusercontent.com/31279647/55221257-03695800-5244-11e9-90e6-fb3fe44a6345.png)
my

**Comment by djmisterjon** [comment]
There are really many ways to do it.
The solution that comes to mind to do this it is to use:
`generateTexture` on your display objet
http://pixijs.download/release/docs/PIXI.WebGLRenderer.html#generateTexture

**Comment by iamappmaker** [comment]
Is there any simple & direct way to convert canvas to image?

I need entire canvas to image.
I tried adding image and circle (only half circle is in canvas visible part remaining outside canvas)
app.renderer.plugins.extract.image() // Only last rendered image or object is visible. Either image or circle

app.renderer.plugins.extract.image(app.stage) // works but objects outside canvas visible area also visible in output image.  Full circle is visible

**Comment by anonymousRega** [comment]
Who have html.  For Facebook

**Comment by themoonrat** [comment]
So in v5, part of the code for `PIXI.renderer.extract.canvas` is 
```
        if (target) {
            if (target instanceof RenderTexture) {
                renderTexture = target;
            } else {
                renderTexture = this.renderer.generateTexture(target);
                generated = true;
            }
        }
```

This means that you can pass through a renderTexture to this function. And with `renderer.generateTexture`, the last parameter lets you set a region: http://pixijs.download/dev/docs/PIXI.AbstractRenderer.html#generateTexture

So generate your own render texture on the whole container, but supplying a region. Then pass that render texture to `PIXI.renderer.extract.canvas`. Should work

**Comment by themoonrat** [comment]
I'm going to close this for now. We've had questions for both 'it captures everything but I only want the visible area' and 'It only captures the visible area, but I want it to capture everything', and I think we've had answers for both now. Feel free to open a new issue if you still have issues!
