### ISSUE TITLE
How to syncronize PIXI objects position with p2.js body position?

### ISSUE THREAD

**Issue by FlamesoFF** [pixijs/pixi.js#5485]
How to syncronize PIXI objects position with p2.js body positions? The positioning seems absolutely different in this two frameworks.

```ts
const physBody = new p2.Body({
            position: pos,
            mass
        });

        const physShape = new p2.Box({
            width: size[0],
            height: size[1]
        });

        physBody.addShape(physShape);

        physBody.position[0] += position[0];
        physBody.position[1] += position[1];

        const pixiGraphics = new PIXI.Graphics();
        pixiGraphics.beginFill(color);
        pixiGraphics.drawRect(position[0], position[1], size[0], size[1]);
        pixiGraphics.endFill();
```

And the result looks like this:
![image](https://user-images.githubusercontent.com/5371279/53703250-18eb8d80-3e10-11e9-8907-a1590e1c3fd9.png)

And this advice not working, everything is totally messed up:
![image](https://user-images.githubusercontent.com/5371279/53703211-8cd96600-3e0f-11e9-8371-8fa154510288.png)

Cube is a simple example where pivot point is in the center, but in more complex shapes center of a physical body can be anywhere and synchronize rotation between view and physics body is almost impossible, as i see it.

**Comment by Dairnon** [comment]
That seems like a pivot/anchor issue. I assume box2d defaults the pivot at 0.5. 

Try offsetting the pivot so that its center in the graphics.

pixiGraphics.pivot.set()

**Comment by FlamesoFF** [comment]
@Dairnon i set pivot to 0.5. It became better, but it still not centered accurately.

**Comment by Dairnon** [comment]
Oops i think pivot is in pixel dimension. Not 0-1 rather 0 - dimensions of displayObject.

Try half the size of your graphics object.

**Comment by Dairnon** [comment]
Any progress?

**Comment by bigtimebuddy** [comment]
Closing because of the lack of response. @FlamesoFF if you found a solution please share as other might find the same issue as you did.

**Comment by FlamesoFF** [comment]
@Dairnon Yes, with pixels it working fine.
