### ISSUE TITLE
Render process gone

### ISSUE THREAD

**Issue by xiaoshidetaikuai** [pixijs/pixi.js#5490]
I use pixi.js rendered 10000 Contanier, 9999 lines, 9999 text. every container have an image,test.
When this page lasts for a while, it will crash。but It is not often appear.How did this problem occur?
the chrome version is `71.0.3578.98`, ram `16GB` ， Graphics card `GT1030` pixi version `v5.0.0-rc2`

**Comment by bigtimebuddy** [comment]
It seems you are allocating too many things at once. Text objects in particular are very expensive. You should _only_ create the objects that you need to visually show on screen and then recycle and pool the rest. For Text, consider using [BitmapText](https://www.adammarcwilliams.co.uk/creating-bitmap-text-pixi/) as it's much faster and allocates a lot less memory. If you need to instantiate many objects at once, try doing it across multiple requestAnimationFrames instead of all at once.

**Comment by ivanpopelyshev** [comment]
lines are underlining the text or what? What kind of text?

**Comment by xiaoshidetaikuai** [comment]
@bigtimebuddy @ivanpopelyshev Thank you very much for your reply.
First, I used the `Text` class to initialize the text. It has about 20,000 Text Sprites.Each paragraph has about 11 words.lines are `graphics` for draw straight line. The page will continue to show for a while and will crash.
Now I use the `BitmapText` class to initialize the text.There is no crash at present.But I found if each paragraph has a long text，It will also slow down。
And What is the performance of consumption besides text?

**Comment by ivanpopelyshev** [comment]
I think its time for you to read the source code. Whatever I suggest at this point wont work if you suddenty add 100000 texts ;) The main feature of PixiJS is architecture that allows you to add your own effective algorithms for input that is specific for your game. 

I know many ways to improve default pixi shaders and several approaches for text, but I can explain that only when you know basic stuff: BatchRenderer, Text, underlying canvas2d and webgl contexts.

**Comment by xiaoshidetaikuai** [comment]
em...I saw a lot of places I need to learn.Thank you for your patience answer！

**Comment by xiaoshidetaikuai** [comment]
Hi~
After several modifications, the problem of the crash still exists. It happens once or twice a day. The problem is that it will crash when there are only 1000 sprites. I can't locate the problem. I am sorry because I can't display the original code on the internal network. I can only use this example to explain the project I am doing.Is there any problem here?
[github project](https://github.com/xiaoshidetaikuai/pixiForceLayout)

**Comment by bigtimebuddy** [comment]
Wasn’t sure if you’re doing this already... Adding culling (setting things off screen to be invisible) and hiding text when it gets too small to see might improve your stability.

**Comment by xiaoshidetaikuai** [comment]
@bigtimebuddy  Just need to set visible to save performance? like :
`bitmapText.visiable = false`

**Comment by themoonrat** [comment]
@xiaoshidetaikuai Yes :)

**Comment by bigtimebuddy** [comment]
The reason is that invisible objects are skipped by the renderer. There’s usually a significant performance boost by doing this simple thing if you’re rendering a lot of objects.

Small detail in your code: the property is “visible” not “visiable”.

**Comment by xiaoshidetaikuai** [comment]
@themoonrat @bigtimebuddy  Thank you for your help.I will follow your suggestions to optimize the code.But, I found that when I open the chrome development tool and lock the screen for a while, the graph will has a great chance of crashing, even if there are only a few points on the map.What is the reason for this?

**Comment by themoonrat** [comment]
@xiaoshidetaikuai  Is this still an issue? If it is please create a playground and we'll take another look at this :) If not, we can close this.
