### ISSUE TITLE
Displacement filter + displacement sprite rotation (maybe feature request?)

### ISSUE THREAD

**Issue by distinctdan** [pixijs/pixi.js#5491]
Hi, I'm trying to use a displacement filter to apply a directional ripple effect to my character (an orb), but it looks like the displacement filter doesn't fully support rotating the displacement sprite. It's a little hard to describe. It rotates the sprite, but it doesn't rotate the displacement vectors of the pixels. So if a pixel's displacement is `x = 10`, after the rotation the pixel has moved, but it's still displacing along the x axis as `x = 10`.

Here's an image of what I'm talking about. The orb on the left is unrotated and you can see the horizontal ripples end in nice rounded waves on the sides. However, the right orb is rotated 90deg, and you can see the ripples are now vertical, but they're still displacing in the direction they were in when unrotated, which breaks the effect.

Not sure if this is really a bug, or maybe just a feature request. I can create a running example if necessary.

<img width="342" alt="screen shot 2019-03-05 at 2 22 58 am" src="https://user-images.githubusercontent.com/10030156/53788180-0c8a3200-3eef-11e9-8313-2d1a0336e82f.png">

- **`pixi.js` version**: 4.8.5
- **Browser & Version**: Chrome 72.0.3626.119
- **OS & Version**: OSX

**Comment by ivanpopelyshev** [comment]
How good are you with editing glsl shaders? ;)

**Comment by distinctdan** [comment]
Lol, never done it before, but I'm a fast learner ;). I am interested in this feature, so I'd be willing to take a stab at it.

**Comment by distinctdan** [comment]
So I read through the displacement filter code, and I don't understand everything, but it looks like the actual displacement part is pretty simple. It looks like the relevant part is where it adds the displacement map value like `vTextureCoord.x + map.x`. So, instead of just adding the map value, we'd need to rotate the map value by the displacement sprite's global rotation.

Once we have the rotation, it looks like it'd be as simple as passing in `sin(angle)` and `cos(angle)` to the fragment shader so it can rotate the map value. However, I'm not 100% on how to get the rotation. It looks like we already have a filterMatrix, so would the right way to do it be to decompose the rotation out of the filterMatrix?

**Comment by ivanpopelyshev** [comment]
rotation and scale are somewhere inside vertex part of shader, I remember that there's a matrix that we are passing inside to correctly get UV's of displacement sprite. you can try pass two values from that matrix (0-th and 1-th for example, `.xx` and `.xy`) to new varying vector, and then use them in fragment to rotate/scale stuff.

**Comment by ivanpopelyshev** [comment]
Actually, just create playground with that thing and your vertex/fragment shader code from displacement, and then i'll maybe hack it in two mintes ;)

**Comment by distinctdan** [comment]
Thanks! Yeah, if you know the right variables to use, I can put it together into a PR. Ok, it's ugly, but I copied the displace filter stuff into a playground. The orb rotates to follow your mouse. The vert and frag shaders are strings up at the top: https://www.pixiplayground.com/#/edit/dJFQCcVGLSvhAS_jzZ_Z2

**Comment by ivanpopelyshev** [comment]
### My way: use already existing matrix

https://www.pixiplayground.com/#/edit/WMGSORaQBtz7pInb3kp~U

I've added rotation mat2 in vertex array to pass it inside. Normalization is here. I'm still not sure that it works like its supposed to, maybe it has side-effects. Yeah, negation means that we rotate map to back to screen, its reversed.

```glsl
vRotation = mat2(normalize(vec2(filterMatrix[0][0], -filterMatrix[0][1])),
    normalize(vec2(filterMatrix[1][0], -filterMatrix[1][1])));
```

Then I multiplied displacement vector:

```glsl
map.xy = scale * inputSize.zw * (vRotation * map.xy);
```

## Your way: just pass rotation uniform

Yeah, lets calculate global rotation matrix, and normalize it on JS side:

https://www.pixiplayground.com/#/edit/dJFQCcVGLSvhAS_jzZ_Z2

```js
let wt = this.maskSprite.transform.worldTransform;
let lenX = Math.sqrt(wt.a * wt.a + wt.b * wt.b);
let lenY = Math.sqrt(wt.c * wt.c + wt.d * wt.d);
this.uniforms.rotation[0] = wt.a / lenX;
this.uniforms.rotation[1] = wt.b / lenX;
this.uniforms.rotation[2] = -wt.c / lenY;
this.uniforms.rotation[3] = -wt.d / lenY;
```

**Comment by distinctdan** [comment]
Thanks for looking at it! Yeah, I was thinking doing the calc on the JS side may be more efficient too, since the rotation should be the same for every vert and pixel. I did notice on the "existing matrix" example, I'm seeing a little bit of distortion in the effect when it rotates around multiples of 45deg. I don't understand enough of the math to really be any help in debugging it though. Do you have a preference for which way to go with? My preference is for the JS calc way, but I'll defer to you here. I can code up a PR here in a bit.

And one other question, if we do the JS way, is there any circumstance wheres `lenX` or `lenY` can be 0? Definitely want to do defensive coding here.

**Comment by ivanpopelyshev** [comment]
If you dont try to set scale to 0 by some tween (tween from 1 to -1 for example). EVen then, there are other places that dont like it. Degenerate matrices are evil and I dont know renderer/engines that allow them.

**Comment by distinctdan** [comment]
Ok, makes sense. It'd be easy to add a guard like:
```
if (lenX !== 0 && lenY !== 0) {
    this.uniforms.rotation[0] = wt.a / lenX;
    this.uniforms.rotation[1] = wt.b / lenX;
    this.uniforms.rotation[2] = -wt.c / lenY;
    this.uniforms.rotation[3] = -wt.d / lenY;
}
```

**Comment by distinctdan** [comment]
Ok, just created a PR for it: https://github.com/pixijs/pixi.js/pull/5507

I've also updated the playground because I realized the displacement image didn't have any displacement in the y axis, which made it impossible to test the y rotation. It turned out the y displace was inverted, but it was a quick fix: https://www.pixiplayground.com/#/edit/M~8Ld47o6vOWvFTxmvvOX

**Comment by distinctdan** [comment]
PR is merged, closing.
