### ISSUE TITLE
Make backdrop available for shader

### ISSUE THREAD

**Issue by dooxe** [pixijs/pixi.js#5493]
Hello there,

Today I posted this message on the pixi.js forum: 
http://www.html5gamedevs.com/topic/42352-how-to-get-the-background-texture-wrt-a-sprite/

The purpose is the following: 
When applying a shader on a specified sprite, have access to the current stage render (backdrop), 
in order to, for example, create a heat effect above a fire (that needs to modify background pixels).

While the given resources apply some cool effects (thanks again @ivanpopelyshev), the effect I want cannot be achieved with pixi from what I understand of:
> requirement: have a renderTexture or filter at background. For example, a fullscreen AlphaFilter, otherwise there's no way to get backdrop dat﻿a﻿

From that I hacked a bit on pixi to get a (coarse) solution to this problem. 
The following codepen shows the patch I made and the final result we can achieve:
https://codepen.io/dooxe-the-reactor/pen/WmGRLm

The patch consists in the following modifications:
* Use a `RenderTexture` for the main rendering step
* In `Renderer.js`, save the current `renderTexture` in an attribute (let's say `renderTextureBuffer`)
* In `FilterSystem.js`, send the renderTexture as uniform inside the shader: 
```
if(renderer.renderTextureBuffer){
    var backdropTexture = renderer.renderTextureBuffer.baseTexture;
    filter.uniforms.uBackdrop = backdropTexture;
}
```
tested with `pixi.v5`, but I didn't checked the performances.

Such a feature could be _really_ nice to be available in pixi.js.

**Comment by ivanpopelyshev** [comment]
Hello!

That change for v4 was rejected, https://github.com/pixijs/pixi.js/pull/4686

It will be rejected for v5 because we have a freeze on features before release.

Also, last month I figured out that there is even better way to work with backdrop stuff, that allows to use multi-pass filters with it (like blurs). I dont want that API to be introduced to vanilla pixi, because it will be deprecated later for sure. 

Adopting pixi-picture implementation for v5 is the better idea right now.

**Comment by dooxe** [comment]
Hey ! 

I think I was misunderstanding the sense of:

> "requirement: have a renderTexture or filter at background. For example, a fullscreen AlphaFilter, otherwise there's no way to get backdrop data. "

I thought there was no way at all, even with plugins. 

If the effect can be achieved with `pixi-picture` I'm happy with that and will take a closer look to it.

Thanks 👍

**Comment by ivanpopelyshev** [comment]
LOL
