### ISSUE TITLE
Graphics.clear()  Calling this method does not empty the canvas

### ISSUE THREAD

**Issue by hacer-healer** [pixijs/pixi.js#5495]
**

> Problem description

**
After drawing a broken line, each call to the method deletes a segment of the line and redraws it. When deleting the last segment, the canvas is not empty. In this case, pixi v5 version and pixi v4 version are normal.Here's the code for the demo.
**

> demo code

**
`<input type="button" value="删除" `onclick="deleteLine()"/>
`<script` `src="js/pixi_v5.js"></script>`  

`<script` >
    let app = new PIXI.Application(   
                     
                   { width: window.innerWidth, 
			 height: window.innerHeight, 
			 antialias: true, 
			 transparent: false,
			 resolution: 1 
			 } 
		); 
		document.body.appendChild(app.view);
		app.renderer.backgroundColor = 0xffffff;
		let posAllList = [[0,0],[120,40],[398,49],[239,39],[232,120],[102,39],[222,331]];
		let lineContainer = new PIXI.Container();
		app.stage.addChild(lineContainer);
		lineContainer.addChild(new PIXI.Graphics())
		drawLines(posAllList);
		function deleteLine (posList) {
				posAllList.pop();
				drawLines(posAllList);
		}
		function drawLines (posList) {
				let lineGraphics = lineContainer.children[0];
				lineGraphics.clear();
				for (let i = 0; i < posList.length - 1; i++) {
						lineGraphics.lineStyle(1,'0x38589a');
						lineGraphics.moveTo(posList[i][0],posList[i][1]);
						lineGraphics.lineTo(posList[i + 1][0],posList[i + 1][1]);
				}
		}
`</script>`

**Comment by ivanpopelyshev** [comment]
We had that bug in 5.0.0-rc1. Do you use rc2?

**Comment by hacer-healer** [comment]
I under https://pixiplayground.com editor, using the rc2 but still exists the question. When I submit the demo, There was an error trying to save the playground.

**Comment by ivanpopelyshev** [comment]
Bug reproduced.

Here's your demo: https://www.pixiplayground.com/#/edit/LSRbC7zrNAq5i5yp7jEEP 

Even easier example: https://www.pixiplayground.com/#/edit/ry07lOifbUxG1bt85ay2k
