### ISSUE TITLE
PIXI V5 Sprites Disappear on Android Galaxy S7 Edge

### ISSUE THREAD

**Issue by adammarcwilliams** [pixijs/pixi.js#5496]
### Expected Behavior

Sprites added to stage container stay on screen.

### Current Behavior

Sprites appear on screen and then disappear almost instantly.

### Steps to Reproduce

Run Basics PIXI demo on a Galaxy S7 Edge (SM-G935F) usingv5.0.0-rc.2

### Environment

- **`pixi.js` version**: 5.0.0-rc2
- **Browser & Version**: Chrome 72.0.3626.121
- **OS & Version**: Android 8.0.0
- **Running Example**: https://pixijs.io/examples/?v=v5.0.0-rc.2#/basics/basic.js

**Comment by ivanpopelyshev** [comment]
```js
PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL;
```

due to

https://bugs.chromium.org/p/chromium/issues/detail?id=934823

**Comment by adammarcwilliams** [comment]
Thanks, interestingly it worked on v5.0.0-rc just not rc.2 after further investigation.

**Comment by ivanpopelyshev** [comment]
Its not worth investigation what was wrong there. Maybe `TEXTURE_ARRAY` stuff or something like that, I can try to switch several such things off if you are ready to test them.

Related PR : #5502

**Comment by adammarcwilliams** [comment]
Don't worry if it's a Chrome bug, I'm sure it will sort itself out soon enough.

I'll close the issue.
