### ISSUE TITLE
PIXI.Graphics#clear() does not working when line length is zero

### ISSUE THREAD

**Issue by derushio** [pixijs/pixi.js#5498]
### Code
```
protected draw() {
    for (const line of this.lines) {
        // line is PIXI.Graphics
        line.clear();
        line.moveTo(0, 0);
        // clear does not working when `line.lineTo(0, 0);`
        line.lineTo(line.point.x, line.point.y);
    }
    
    requestAnimationFrame(this.draw);
}
```

### Expected Behavior
* Always execute graphics clear

### Current Behavior
* Clear does not working when line length is zero
* line.point state is not equal to actual line length

### Environment
- **`pixi.js` version**: 5.0.0-rc.2
- **Browser & Version**: Google Chrome 72.0.3626.121 (Official Build) (64-bit)
- **OS & Version**: KDE neon 5.15
- **Running Example**: N/A

**Comment by derushio** [comment]
```
line.lineTo(line.point.x || 1 / 1000, line.point.y);
```

is good work

**Comment by ivanpopelyshev** [comment]
Os this the same as #5495 ?

**Comment by derushio** [comment]
Yes, I will close issue.
