### ISSUE TITLE
Do these plugins/extensions support PIXI.js V5 ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#5500]
In my project , I use  plugins/extensions below  :

https://github.com/pixijs/pixi-projection
https://github.com/pixijs/pixi-lights

https://github.com/pixijs/pixi-filters

https://github.com/pixijs/pixi-tilemap

https://github.com/pixijs/pixi-display
https://github.com/pixijs/pixi-picture

https://github.com/pixijs/pixi-particles

Do  they support PIXI.js v5 now ?

Thanks

**Comment by andrewstart** [comment]
pixi-particles should work if you use `dist/pixi.min.js` (the one that adds the PIXI namespace), but won't work if you are including it as a module, which no longer adds the namespace. I am currently working on updating it to fully support v5.

For the others, I imagine that most of them do not, but @ivanpopelyshev could probably confirm that.

**Comment by ivanpopelyshev** [comment]
Only filters.

**Comment by bigtimebuddy** [comment]
I believe pixi-filters works runtime, but typing do not work yet if you use TypeScript.

**Comment by ivanpopelyshev** [comment]
Work with v5:

https://github.com/pixijs/pixi-filters
https://github.com/pixijs/pixi-tilemap
https://github.com/pixijs/pixi-display
https://github.com/pixijs/pixi-spine

**Comment by finscn** [comment]
@ivanpopelyshev could you update the new result ?
