### ISSUE TITLE
inner/outer lineStyle alignment swapped for circles in 5.0.0-rc.2

### ISSUE THREAD

**Issue by nstolpe** [pixijs/pixi.js#5504]
### Expected Behavior

A `lineStyle.alignment` of 0 should draw the stroke inside a circle's radius and a `lineStyle.alignment` of 1 should draw the stroke outside a circle's radius. [Example](https://jsfiddle.net/bigtimebuddy/zcrub78v/) from @bigtimebuddy 

### Current Behavior

`lineStyle.alignment` of 0 draws the stroke outside of a circle's radius and 1 draws the stroke inside the radius. [Forked version](https://jsfiddle.net/5ca6j74u/) of @bigtimebuddy's example using `5.0.0-rc.2` instead of `4.7.3`.

### Possible Solution

I'm not sure. I thought I could find the issue `Graphics.js` or `buildLine.js`, but I looked through the source and both files appear to be the same on dev and master (they're also the same as in version 4.7.3). That might narrow it down a little.

### Steps to Reproduce

Compare the following JSFiddles:
[Expected](https://jsfiddle.net/bigtimebuddy/zcrub78v/)
[Actual](https://jsfiddle.net/5ca6j74u/)

### Environment

- **`pixi.js` version**: `5.0.0-rc.2`
- **Browser & Version**: Chrome Version 71.0.3578.98, Firefox 65.0 (64-bit)
- **OS & Version**: `KDE Neon 18.04`
- **Running Example**: https://jsfiddle.net/5ca6j74u/

**Comment by ivanpopelyshev** [comment]
I think I fixed that in v4 months ago, maybe it wasnt moved to v5 because graphics was refactored.

**Comment by nstolpe** [comment]
@ivanpopelyshev it looks like it was [last working](https://jsfiddle.net/Lgp61doj/) in 5.0.0-alpha.3

**Comment by bigtimebuddy** [comment]
Fixed with #5567
