### ISSUE TITLE
Kindle 7 Flicker Issue

### ISSUE THREAD

**Issue by Darren-Ivey** [pixijs/pixi.js#5506]
We have received a report from Amazon that on the new Kindle 7 there is a flicker issue with games that use pixi.
We have a large codebase and are running pixi v4.7.2 upgrading to a major release would be a mammoth task. Would it be possible to backport a fix to 4?

This is Amazon's suggested fix for the flicker on the new Kindle 7 tablet:

This document provides information on the issue identified.

[Steps to Reproduce]

Launch App
Start to access the game
Observe the screen and buttons.
[Expected Results]
Flickering and graphic distortion should not be seen in any app

[Observed Results]
Graphic distortion and flickering is happening on the screen and the buttons.

Root cause

There is compiler optimization between Mali GPU DKK r12 andr20, which affect the return index of render.

Why did it regress

In DDK r12, the render index of program 7 and 10 are in sequence of 0, 1, 2 as below:
attribute mediump vec2 webgl_fdb73dbb0e7c8f8a; // program 7 index: 0 program 10: 0
attribute mediump vec2 webgl_9dbbaaac2712c491; // program 7 index: 1 program 10: 1
attribute mediump vec4 webgl_9e740ab728e139e5; // program 7 index: 2 program 10: 2
attribute mediump float webgl_ca143f53438616ee; // program 7 index: NA program 10: 3
In DDK r20, after compiler optimization, the render index depends on real render usage.
attribute mediump vec2 webgl_fdb73dbb0e7c8f8a; // program 7 index: 0 program 10: 0
attribute mediump vec2 webgl_9dbbaaac2712c491; // program 7 index: 2 program 10: 3
attribute mediump vec4 webgl_9e740ab728e139e5; // program 7 index: 1 program 10: 1
attribute mediump float webgl_ca143f53438616ee; // program 7 index:NA program 10: 2

From our observation, application assumes that all attributes should be the same because the VS source code is totally the same. So application uses program10’s vertex attribute to set vertex attribute pointer for program 7. If the render index different in two different programs, the render attribute mapping will be wrong.

Why it can’t be fixed on the device side?

We cannot correct the wrong calling sequence in GPU driver side since GPU cannot guarantee the attribute index sequence is always the same in a program.

What should the 3p app dev to do fix this?

According to spec: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetAttribLocation.xhtml
The association between an attribute variable name and a generic attribute index can be specified at any time by calling glBindAttribLocation. Attribute bindings do not go into effect until glLinkProgram is called”
Which means compiler has the freedom to assign any index to either position or texcoord.
Please kindly suggest application developer to call glGetAttribLocation for each program and ensure not mixing them up.

**Comment by ivanpopelyshev** [comment]
That's helpful.

Try latest in v4. we had several changes in sprite renderer.

I see only one main shader: https://github.com/pixijs/pixi.js/blob/v4.x/src/core/sprites/webgl/SpriteRenderer.js#L119

I looked in binary of 4.7.2 and it looks the same at that place.

Maybe the problem is that we test shader on a test context somewhere or on compile different testing program somewhere? Then v5 will have the same problem, because im not sure how are those locations obtained, we have to re-check everything.

**Comment by GoodBoyDigital** [comment]
hello! Set transparent to true on the render and it should work perfectly 👍
