### ISSUE TITLE
Custom binding event

### ISSUE THREAD

**Issue by hacer-healer** [pixijs/pixi.js#5508]
### Expected Behavior
Does pixi support custom binding events, similar to d3.js(mousedown.zoom),I want to bind multiple methods to the same object's mousedown.
### Current Behavior
Now it can only bind one method.
### Environment

- **`pixi.js` version**: _e.g. 5.0.0_rc2
- **Browser & Version**: _e.g. Chrome 60_

**Comment by ivanpopelyshev** [comment]
its EventEmitter, it works for several.

**Comment by bigtimebuddy** [comment]
Add multiple event handlers.
```js
container.on('mousedown', function() {});
container.on('mousedown', function() {});
```
