### ISSUE TITLE
v5 unsafe-eval error when creating new Renderer

### ISSUE THREAD

**Issue by distinctdan** [pixijs/pixi.js#5509]
When creating a new renderer like `new PIXI.Renderer(options);` pixi throws the error:
```
Current environment does not allow unsafe-eval, please use @pixi/unsafe-eval module to enable support.
    at ShaderSystem.systemCheck (ShaderSystem.js:59)
    at new ShaderSystem (ShaderSystem.js:27)
    at Renderer.addSystem (Renderer.js:258)
    at new Renderer (Renderer.js:142)
    at new PixiView (pixiViewFactory.ts:57)
```

My content security policy is set to block eval because it's a huge security hole, and I'm uneasy about including the `unsafe-eval` module because it sounds like it's going to do bad things. This worked in v4, so I believe the issue is new in v5. Here's my CSP:

```
<meta http-equiv="Content-Security-Policy" content="
    default-src 'self' 'unsafe-inline' data: gap: blob: https://ssl.gstatic.com https://www.googletagmanager.com
        https://www.google-analytics.com ws://127.0.0.1:35729/livereload localhost:8090;
    style-src 'self' 'unsafe-inline';
    media-src *;
">
```

### Environment

- **`pixi.js` version**: v5.0.0-rc.2
- **Browser & Version**: Chrome 72.0.3626.121
- **OS & Version**: OSX

**Comment by ivanpopelyshev** [comment]
#5463

Its dangerous to go alone, take this: 

https://pixijs.download/dev/pixi.js (or pixi.min.js)
https://pixijs.download/dev/unsafe-eval.min.js

**Comment by bigtimebuddy** [comment]
We haven't published `@pixi/unsafe-eval` yet, but this is designed specifically for your situation, where the use of `new Function` or `eval` is restricted. By including this new package, it's so that PixiJS doesn't use `new Function` although at a slight performance cost.

Either way, this is a response to #5459.

**Comment by distinctdan** [comment]
Thanks, I read through the source of the `unsafe-eval` module, and it looks ok, so I can use it.

However, I'm a bit concerned that PIXI is using eval at all. It's a big security risk and opens a lot of doors for potential XSS attacks. Like, I'm considering adding a level editor for my game that would allow users to create their own levels. It would be very bad, for example, if a user was able to put some javascript in for some character's position, and have PIXI execute it. Is that the case, or is eval used only for stuff that never interacts with user-entered data?

**Comment by distinctdan** [comment]
I am still planning on sanitizing the user's input, but defense in depth is a good thing.

**Comment by photonstorm** [comment]
`eval` isn't being used anywhere, it's `new Function` that is being used, and it's literally impossible for user-land code to be injected into those given the way Pixi uses it with pre-defined strings. XSS isn't applicable here.

**Comment by distinctdan** [comment]
Great! Glad to hear it, needed to check to make be sure.
