### ISSUE TITLE
RopeGeometry constructor param types

### ISSUE THREAD

**Issue by scythianfuego** [pixijs/pixi.js#5512]
Hi, here the fist parameter should be changed from texture to width:
https://github.com/pixijs/pixi.js/blob/f0dbf5714f72a3f0538acf0cfe5b48fad89aafff/packages/mesh-extras/src/geometry/RopeGeometry.js#L20-L23

Also, the name _width_ here is confusing as it is a _rope width_ corresponding to _texture height_
May be worth renaming to _ropeWidth_ or mentioning this explicitly in the comment

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out. Looks like a copy-pasta error. PR welcome!
