### ISSUE TITLE
new Graphics.generateTexture()error

### ISSUE THREAD

**Issue by hacer-healer** [pixijs/pixi.js#5517]
### Expected Behavior
Turn graphics into sprites.  
The calling method (generateTexture()) failed, but it can be implemented in pixi v4.8.2.
### Demo
    `let app = new PIXI.Application( 
			  
                   { width: window.innerWidth, 
			 height: window.innerHeight, 
			 antialias: true, 
			 transparent: false,
			 resolution: 1 
			 } 
		); 
	document.body.appendChild(app.view);
	app.renderer.backgroundColor = 0xffffff;
	let graphics = new PIXI.Graphics();
    graphics.beginFill(0x38ee22);
    graphics.drawPolygon([
                -32, 64,
                 32, 64,
                 0, 0]);
    graphics.endFill();
    let graphicsTexture = graphics.generateTexture();
    let graphicsSprite = new PIXI.Sprite(graphicsTexture);
    graphicsSprite.anchor.x = 0.5;
    graphicsSprite.anchor.y = 0.5;
    graphicsSprite.rotation = 0.5;
    graphicsSprite.x = window.innerWidth / 2;
    graphicsSprite.y = window.innerHeight / 2;
    app.stage.addChild(graphicsSprite);`
### Environment

- **`pixi.js` version**: _e.g. 5.0.0_rc2
- **Browser & Version**: _e.g. Chrome 60_

**Comment by ivanpopelyshev** [comment]
`generateTexture` is actually `generateCanvasTexture` and it works only with pixi-legacy.js:

https://www.pixiplayground.com/#/edit/Bz7XeR6wvkPRWpDCl3c0U

https://pixijs.download/dev/pixi-legacy.js

If you use it with npm - it has different name of module, i dont remember which one.

**Comment by bigtimebuddy** [comment]
[pixi.js-legacy](https://www.npmjs.com/package/pixi.js-legacy)
