### ISSUE TITLE
[Question] PIXI.Graphics renders large, complex, concave polygons incorrectly and buggily. Is this intended behaviour?

### ISSUE THREAD

**Issue by sniggyfigbat** [pixijs/pixi.js#5531]
### PIXI.Graphics doesn't do what I want, probably because I'm using it wrong.

I'm writing a rather silly bit of game code that creates a long, flowing tail behind moving objects by storing a bunch of past points and then using offsets to generate a (very) complex polygon using a PIXI.Graphics object - think roughly 30-gons, plus or minus a bit.

Unsurprisingly, it doesn't work very well.

What is slightly surprising to me, however, is that it doesn't just not work in the way I expected - bridging gaps over all the concave bits of a path - but is also weirdly flickery. It's hard to show on screenshots, because it's... well... flickery.

Anyway, I just wanted to check that this isn't actually available functionality that I've somehow missed a 'allowConcave' toggle on, or an obscure bug I've stumbled upon. I suspect not, but hey, one never quite knows.

**Comment by bigtimebuddy** [comment]
Could you provide an example of what you're doing (https://jsfiddle.net or https://pixiplayground.com) would be really helpful to understand what that flickery behavior is. It's hard to get a sense based on  your description.

Also, what version of PixiJS are you using? And what platform/device?

**Comment by ivanpopelyshev** [comment]
Select u its carefully. Its better to adjust scale and position than moveTo(0.0001, 0.0001) lineTo(0.0002, 0.0002) or big values moveTo(10000.001, 10000.001) . There are multiple places with epsilon operations, also shaders work with float16 which is not precise. Cant explain everything in one post, please provide a demo or at least pixijs version.

**Comment by sniggyfigbat** [comment]
Apologies! It turns out, the reason my code didn't work is because it was written at 3AM and riddled with bugs - which is also why I didn't think to include sample code, platform specifics, or anything else remotely useful.

I've rewritten it to draw segments individually, and it works fine. Looks like this:
![image](https://user-images.githubusercontent.com/3359069/54710191-04610200-4b3f-11e9-8e0b-f7c46751736f.png)
