### ISSUE TITLE
PIXI.Graphics.arc() 180 degrees edges not horizontally (or vertically) straight.

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi.js#5533]
### Expected Behavior
Arc edges are straight, aligned with the X axis:
![image](https://i.imgur.com/09h5hSR.png)

The issue is that because of this, if you have 2 semi-circles and want to glue them together, you will have small gaps between them.

The `canvas.arc` works as expected: https://jsfiddle.net/vnaf2qgp/1/
![image](https://user-images.githubusercontent.com/1384885/54760536-91b05f00-4bf0-11e9-955e-c54d33157ad4.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/1384885/54759392-47c67980-4bee-11e9-92aa-0dd79d6a27c4.png)

### Possible Solution
It looks like the center of the arc is aligned on the horizontal axis, but because of the increased thickness the outer and inner edges are not aligned.

### Steps to Reproduce
```
var app = new PIXI.Application(800, 600, {backgroundColor : 0x1099bb});
document.body.appendChild(app.view);

var graphics = new PIXI.Graphics();
graphics.lineStyle(150, 0xFF00FF, 1);
graphics.arc(200, 200, 100, 0, Math.PI);

app.stage.addChild(graphics);
```

### Environment

- **`pixi.js` version**: . 4.8.6 (also reproductible in latest version)
- **Browser & Version**: _Chrome 73
- **OS & Version**:  Windows 10

**Comment by ivanpopelyshev** [comment]
Workaround is fills with "arc" or "quadraticCurveTo"  instead of strokes. I do not recommend to make strokes that big.

I know the math behind that bug and I dont know how to solve that properly. Its interesting that canvas2d solves it just fine, maybe I'll look in Google Skia sources.

**Comment by ivanpopelyshev** [comment]
P.S. I see that you take your rest seriously, no commits in weekends ;)

**Comment by Cristy94** [comment]
> Workaround is fills with "arc" or "quadraticCurveTo" instead of strokes. I do not recommend to make strokes that big, better do it with fills.

Ok, so that means I still have to figure out the math for drawing a filled semi-circle using arc and lineTo, right? Or is there a simple way of drawing the shape above that I'm missing? :-?

**Comment by bigtimebuddy** [comment]
https://pixiplayground.com/#/edit/boNSR7Cww43E4YmUXa904

**Comment by Cristy94** [comment]
Thanks, that's a good start, but I need it to be able to draw incomplete donuts (eg. have angle as a parameter, where angle can be between 0 and Math.PI), so you can have a quarter donut also).

PS: I searched on google for pixi playground to post an example, but had a hard time finding it (I searched for: pixi sandbox, pixi editor, pixi online editor, pixi examples).

**Comment by bigtimebuddy** [comment]
It might be nice for someone to make a generalized torus drawing function in Graphics. Could be very handy. Something a little more generalized than that example I created. That way you can specify a start/end angle, center, inner radius, outer radius, etc.

Sounds like your issue here is solved. Definitely use fills vs line strokes. Closing issue.

**Comment by bigtimebuddy** [comment]
Here's another example that's a little bit easier to reuse:
https://pixiplayground.com/#/edit/OBQor67s0zJdfHKMc85f3

**Comment by Cristy94** [comment]
Thank you!If it works better than the strokeFill code, why not use this method to implement stroke for arcs? This way the same code can also be reused for arc fill and arc stroke.On 22 Mar 2019 00:57, Matt Karl <notifications@github.com> wrote:Here's another example that's a little bit easier to reuse:
https://pixiplayground.com/#/edit/OBQor67s0zJdfHKMc85f3

**Comment by Cristy94** [comment]
The example doesn't seem to work in 4.8.6, nothing is shown. https://pixiplayground.com/#/edit/OBQor67s0zJdfHKMc85f3

**Comment by bigtimebuddy** [comment]
Yeah, that code is v5 only.

**Comment by movAX13h** [comment]
arc() is still imprecise in the latest dev version:
![image](https://user-images.githubusercontent.com/1974959/55083715-3ffe4d80-50a4-11e9-8e95-0ccfeb7ceea1.png)

Having this in a pixi canvas that scales with the browser using app.renderer.resize() and redrawing the lines makes the problem visible at some sizes (typical flickering, appearing/disappearing of those cracks).

All angles are multiples of 90 degree (Math.PI / 2)

**Comment by bigtimebuddy** [comment]
@movAX13h could you please create a new issue with a demo of that screenshot. Thanks.
