### ISSUE TITLE
FXAA filter only works against a black background

### ISSUE THREAD

**Issue by treewhopper** [pixijs/pixi.js#5534]
### Expected Behavior
Using the FXAAFilter on a Graphics object should blend a line's color in with that of the surrounding colors.

### Current Behavior
FXAAFilter adds what look like black aliased outlines to Graphics lines, even if the background is not black. If the background is black, this looks good, but if it is transparent or white, it looks wrong.

### Possible Solution
I'm not sure. Maybe something about the colors are not being correctly passed into the shader?

### Steps to Reproduce
Set up an Application with a white background. Then create and add a graphics object with a FXAAFilter applied. See my example at: https://jsfiddle.net/treewhopper/zqgrbcau/

### Environment

- **`pixi.js` version**: 4.x
- **Browser & Version**: Chrome 73
- **OS & Version**: Windows 10
- **Running Example**: https://jsfiddle.net/treewhopper/zqgrbcau/

**Comment by ivanpopelyshev** [comment]
According to source code, https://github.com/pixijs/pixi.js/blob/dev/packages/filters/filter-fxaa/src/fxaa.frag#L107 , it doesnt care that we use premultiplied alpha framebuffers.

**Comment by treewhopper** [comment]
I'm stumped. I wrapped the texture2D calls with this function:
```
vec4 texture2Da(sampler2D tex, vec2 coord) {
    vec4 t = texture2D(tex, coord);
    if (t.a > 0.0)
        return vec4(t.xyz / t.a, t.a);
    return t;
}
```
Then I multiply the alpha back later. It does look improved in some cases, but thin lines or strong color differences still look poor or aliased respectively.

How does the forceFXAA setting work in the application options? Is that using a browser provided implementation? Ideally setting and applying this filter to the stage would have the same output as setting antialias to true and forceFXAA to true.

**Comment by ivanpopelyshev** [comment]
I dont think that option is implemented in v4 and v5

**Comment by treewhopper** [comment]
Well lol that would explain a lot. I was relying on the documentation.

**Comment by bigtimebuddy** [comment]
We should remove that from the docs if it’s unused. PR welcome!
