### ISSUE TITLE
Pool TickerListeners ?

### ISSUE THREAD

**Issue by yingDev** [pixijs/pixi.js#5536]
`Ticker#add` method creates a new `TickerListener` every time, is it possible to pool & reuse these listeners to reduce garbage for GC ?

**Comment by ivanpopelyshev** [comment]
How many elements do you put in ticker? I suggest to use it for systems, and each system has to track certain type.of objects. I usually put several optimizations that depend on object type.

**Comment by yingDev** [comment]
> How many elements do you put in ticker? I suggest to use it for systems, and each system has to track certain type.of objects. I usually put several optimizations that depend on object type.

for example we want to build some `delayed execution` mechanism. 
yes I did it the way just as you described. 
i'm asking here because I think it might be beneficial to pool the listeners for most use cases ?

```typescript
const QNAME = 'View:refresh';

//View is a base class for all UI elements.There can be hundreds of View's in a scene.
class View extends PIXI.Container
{
	static get dirtyQueue() { return DirtyQueue.get(QNAME) || DirtyQueue.set(QNAME, o=>o.doLayout()) }

	/*...*/
	set layout(layout: any | null)
	{
		/*...*/
		this.layoutLater();
	}

	protected onChildrenChange()
	{
		super.onChildrenChange();
		this.layoutLater();
	}
	
	/*...*/
	
	layoutLater()
	{
		/*...*/
		//this is what I actually do, this is cheap
		View.dirtyQueue.push(this);
		
		// however this is tempting because the `add/remove` api looks harmless (allocation-free), but it is not ...
		// PIXI.Ticker.shared.remove(this.doLayout, this);
		// PIXI.Ticker.shared.add(this.doLayout, this);
	}
	
	protected doLayout()
	{
		/*some heavy computation here...*/
	}
}
```

**Comment by ivanpopelyshev** [comment]
Oh, I have that thing. I use single ticker entry for it, there are many ways to store queue not in pixi ticker itself.
