### ISSUE TITLE
[Question] Loading and saving pixel values from PNGs.

### ISSUE THREAD

**Issue by sniggyfigbat** [pixijs/pixi.js#5538]
I'm planning on using PNG images as a means of storing data, essentially reading them as raw binary. This probably isn't optimal, but it vaguely makes sense for my application.

As such, I need to be able to read and write exact 4-byte pixel data to and from .png files. I won't be doing this a lot, so it doesn't have to be blazingly fast, I just need to be able to do it.

Does PIXI have adequate built-in tools for this job, and if so how do I actually use them? Research suggests I can use the `extract()` function of `PIXI.extract.Extract`, but I'm struggling to work out how to actually turn PNGs into the appropriate input type - the loader outputs `PIXI.Texture` objects rather than `PIXI.DisplayObject` or `PIXI.RenderTexture`. Output is even less obvious; I haven't yet found any built-in tool for it.

This all seems like it should be possible, but I haven't quite worked it out.

Any suggestions would be greatly appreciated.

**Comment by ivanpopelyshev** [comment]
If we talk about v4, then `texture.baseTexture.source`  is Image that was used for texture.
As for v5, we have special API texture-resource, https://github.com/pixijs/pixi.js/tree/dev/packages/core/src/textures/resources , and a single demo that shows how to use your own storage for info: https://pixijs.io/examples/?v=v5.0.0-rc.2#/textures/gradient-resource.js . You can store stuff in a ImageData or just Uint8Array like in ResourceBuffer or whatever you want. Its not easy but its better than hacking internals ;)
