### ISSUE TITLE
Graphics.arc() inaccuracy

### ISSUE THREAD

**Issue by movAX13h** [pixijs/pixi.js#5545]
all angles are multiples of 90°
positions are floating
scale the window to see it flickering
![image](https://user-images.githubusercontent.com/1974959/55090481-768d9580-50af-11e9-8499-603ce20225d2.png)

https://pixiplayground.com/#/edit/vkEOPvUGBXB1P~KfUYmBz
(code is an extract from a project I was working on)

tested with 5.0.0-rc.2

might be related to #5533

**Comment by ivanpopelyshev** [comment]
Try 5.0.0-rc3

**Comment by movAX13h** [comment]
thanks, that's solved!
