### ISSUE TITLE
PIXI 5 - PIXI.Graphics() not fully cleaned up?

### ISSUE THREAD

**Issue by fanjules** [pixijs/pixi.js#5548]
I currently have my game running with dual setups of either PIXI 4 or PIXI 5.  From time to time, I create Graphics objects and destroy them, create some more, etc... all normal tasks.   No problems experienced in PIXI 4, but in PIXI 5, but after I destroy it and try to create another Graphics object, WebGL raises the following error in the console:

**WebGL: INVALID_OPERATION: bindVertexArray: attempt to use a deleted object**

I have managed to recreate this in a fiddle by simply destroying and recreating a Graphics object with some rectangles in it.  Click the yellow create/destroy button and check the console output: 

https://jsfiddle.net/fanjules/5vb7fxjs/

I find it unusual that the error does not occur until you create another Graphics object.

A curiosity which may or may not help resolve this problem, is that this problem does not occur if you draw very little in the Graphics object.  So, change stuff.boxcount to 8 or less and this problem does not occur.

I'm not 100% up to speed with latest developments, but is this something to do with batching?

Pixi 5.0.0-rc.3
Windows 10
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by ivanpopelyshev** [comment]
thanks! We have another issue when graphics is not freed, so its obvious i have a error somewhere in graphics geometry reference counter.

**Comment by ivanpopelyshev** [comment]
It turns out everything was ok, its just we trigger warnings because of stupid case. Fix is in #5558
