### ISSUE TITLE
Mipmapping individual sprites from a spritesheet results in a blurriness

### ISSUE THREAD

**Issue by Adam13531** [pixijs/pixi.js#5549]
### Problem summary

A sprite that was loaded from an image file containing only that sprite will mipmap correctly on its own. However, that same sprite loaded from a spritesheet will not always mipmap correctly even though both the sprite and the spritesheet have powers-of-two dimensions. I'm not actually sure if this is a problem in my code or in Pixi. 😢

### Expected Behavior
I'm trying to get the sprites to render exactly the same regardless of the source. That way, I don't need to know anything about the spritesheet itself and I don't need to produce the spritesheets in a specific way.

### Current Behavior
The sprite that's drawn from the spritesheet (i.e. the one on the right) is blurrier than the one drawn from the standalone image on the left. This is more apparent in the example code that I've included than it is in this image:
![example_output](https://user-images.githubusercontent.com/7192897/55262388-e5dbc480-522a-11e9-8ca0-2deded3eda7b.png)

### Possible Solution
I think this problem is due to the X and Y coordinates of the sprite when inside the spritesheet. I have some commented-out PIXI.Rectangle objects that point to the same image in different parts of the spritesheet, and some of those render just fine.

### Steps to Reproduce
I uploaded a ZIP file [here](https://share.bot.land/mipmap_mvce.zip). If you prefer just the application code, here it is:

```js
const resolution = window.devicePixelRatio;
const spriteName = "256x256.png";
const spritesheetName = "2048x1024.png";
var canvas = document.createElement("canvas");
document.body.appendChild(canvas);

var renderer = new PIXI.WebGLRenderer({
  width: 400,
  height: 300,
  view: canvas,
  resolution: window.devicePixelRatio || 1,
  roundPixels: true,
  autoResize: true,
  antialias: true,
  backgroundColor: 0xffbbbb
});
var stage = new PIXI.Container();

function mainLoop() {
  renderer.render(stage);
  requestAnimationFrame(mainLoop);
}

function finishedLoadingAssets() {
  const sprite = new PIXI.Sprite(PIXI.loader.resources[spriteName].texture);

  // The commented-out rectangles still point to the same general sprite but at
  // different locations in the spritesheet.
  //
  // const rect = new PIXI.Rectangle(0, 0, 256, 256);
  // const rect = new PIXI.Rectangle(512, 0, 256, 256);
  // const rect = new PIXI.Rectangle(0, 364, 256, 256);
  const rect = new PIXI.Rectangle(504, 582, 256, 256);
  const singleTexture = new PIXI.Texture(
    PIXI.loader.resources[spritesheetName].texture,
    rect,
    rect.clone()
  );

  const spriteFromSpritesheet = new PIXI.Sprite(singleTexture);

  sprite.scale.set(1 / 8);
  spriteFromSpritesheet.scale.set(1 / 8);
  spriteFromSpritesheet.position.set(sprite.width + 5, sprite.y);
  stage.addChild(sprite);
  stage.addChild(spriteFromSpritesheet);

  mainLoop(0);
}

function main() {
  PIXI.loader
    .add(spriteName)
    .add(spritesheetName)
    .load(finishedLoadingAssets);
}

main();
```

### Environment

- **`pixi.js` version**: _e.g. 4.8.7_
- **Browser & Version**: _e.g. Chrome 73_
- **OS & Version**: _e.g. Windows 10_
- **Running Example**: https://share.bot.land/mipmap_mvce/

**Comment by ivanpopelyshev** [comment]
Hi, Adam!

Try this one before renderer is created:
`PIXI.settings.PRECISION_FRAGMENT=PIXI.PRECISION.HIGH` 

It should work in some cases I believe

**Comment by Adam13531** [comment]
Hey, Ivan! 😄

I did some testing based on what you said, and I've included my discoveries below (mostly for the sake of [people finding this through a search engine in the future](https://xkcd.com/979/)):

* In this particular case, `PIXI.settings.PRECISION_FRAGMENT` shouldn't come into play since no filters are involved, and only `core/Shader.js` in v4 (moved to `core/src/shader/Program.js` in v5) uses this value.
* The special offset works. I believe that it has to be [nextPow2](https://github.com/pixijs/pixi.js/blob/d2a83b3fc457f6b0bd41dc5ca268fe1a05b4b50a/packages/utils/src/data/pow2.js#L11) of the lowest scale value ever used. So, for example, if I wanted a scale of 1/12 the original size, then I need the sprite to be positioned at coordinates divisible by **16** in the spritesheet.
* TexturePacker, as in [CodeAndWeb's TexturePacker](https://www.codeandweb.com/texturepacker), *does* seem to support `commonDivisorX` and `commonDivisorY` options ([docs here](https://www.codeandweb.com/texturepacker/documentation/custom-exporter)). However, that's paid software, and unfortunately, [the free TexturePacker that I'm using from libgdx](https://github.com/libgdx/libgdx/wiki/Texture-packer) only has one semi-related, undocumented option called [`multipleOfFour`](https://github.com/libgdx/libgdx/blob/b7927d90e54db31efed791257e4bf96155b4119e/extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java#L812), which in my case will not suffice even if it does what I think it does since my scale value is 1/8, not 1/4.

So my options are either:
- Use the paid TexturePacker with the options mentioned earlier.
- Generate a mipmappable texture from the spritesheet, then make a sprite from that texture, that way the coordinates that the sprite was at in the spritesheet shouldn't matter.

Either way, it doesn't sound like this is a bug in Pixi, so I'll close this. Thanks for the help!

**Comment by ivanpopelyshev** [comment]
Hey, I left a note to @badlogic for him to make this a priority if you make that PR.

**Comment by Adam13531** [comment]
Update (not that anyone probably cares 😜): [I filed a feature request to libgdx](https://github.com/libgdx/libgdx/issues/5603), but I ended up closing it since I think I'm going to go the render-to-texture route.

I did try out the CodeAndWeb TexturePacker and it seemed to address my issue, but I think I'm just not comfortable "solving" this entirely via spritesheet generation; I'd rather have my game code handle this.
