### ISSUE TITLE
calculateNormalizedScreenSpaceMatrix is not exposed through the FilterSystem

### ISSUE THREAD

**Issue by Adam13531** [pixijs/pixi.js#5550]
I tested out migrating my code from v4 to v5 (more specifically v5.0.0-rc.3), and in the process, I couldn't find out how to use `calculateNormalizedScreenSpaceMatrix` since it's never exposed via `FilterSystem` like the other functions from `filterTransforms.js` are. Note: I'd only found out about `calculateNormalizedScreenSpaceMatrix` from [the v4 migration guide](https://github.com/pixijs/pixi.js/wiki/v4-Migration-Guide) which pointed to [this forum post](http://www.html5gamedevs.com/topic/24347-weird-filterareas-size-on-v4/), so this could actually just be a documentation bug where `calculateNormalizedScreenSpaceMatrix` is no longer the suggested way to do things in v5 (in which case I don't mind updating the [v5 migration guide](https://github.com/pixijs/pixi.js/wiki/v5-Migration-Guide)).

Anyway, my workaround in the meantime was to just copy/paste [the entirety of the function](https://github.com/pixijs/pixi.js/blob/b5d63bd7742ecebf40317d3a3199630b0eb18384/packages/core/src/filters/filterTransforms.js#L23) into my own codebase and call that version, then I changed my v4 code to v5 code as shown below.

v4 code:
```js
this.filter.apply = function(filterManager, input, output, clear) {
    var matrix = new PIXI.Matrix();

    this.uniforms.mappedMatrix = filterManager.calculateNormalizedScreenSpaceMatrix(
        matrix
    );
    filterManager.applyFilter(this, input, output);
};
```

v5 code:
```js
filter.apply = function(
    filterManager,
    input,
    output,
    clear,
    currentState,
    derp
) {
    const filterArea = currentState.sourceFrame;
    const textureSize = currentState.destinationFrame;
    this.uniforms.mappedMatrix = PixiUtil.calculateNormalizedScreenSpaceMatrix(
        this.uniforms.mappedMatrix,
        filterArea,
        textureSize
    );
    filterManager.applyFilter(this, input, output);
};
```

(finally, it's also strange that there's an unused variable called `derp` in the PixiJS codebase)

**Comment by ivanpopelyshev** [comment]
That's a real bug, we should expose that, thanks! Migration is WIP, and I'm working on filters/shaders part. The biggest different is default vertex shader, I suggest you copy it from v4 otherwise it'll enable new v5 uniform set which is different from v4-legacy mode.

**Comment by ivanpopelyshev** [comment]
Please check pixijs.download/dev-filter-normalized-space/pixi.js . I've started a draft for migration and complete explanation on filter spaces in #5555
