### ISSUE TITLE
Why is there pixi js file for server side (npm) and one for client side?

### ISSUE THREAD

**Issue by MegaManLegends2** [pixijs/pixi.js#5551]
Really it is not an issue I have, rather a simple question that was going through my mind.
Why is there a pixi.min.js file available for download through npm? What is the thinking behind having pixi for the node server side? Isn't it sufficient for the code of the game to run on client side? or is it basically the same thing and we just have this pixi npm package to send the file to the client instead of doing it through a CDN or a local directory file? I was thinking perhaps we can have a server side pixi for maybe say making multiplayer games and verify movements of a client using pixi? I am not really sure, so in short, what is the purpose of having pixi available for node? is it just another way to send the file to the client?
Thanks

**Comment by andrewstart** [comment]
It isn't for server side, but just that many use npm as a way to manage libraries in their projects, particularly if using bundlers like Webpack or Rollup,

**Comment by CosmoMyzrailGorynych** [comment]
And then there are hybrid apps, that can benefit from using `require` in their DOM context.

**Comment by ivanpopelyshev** [comment]
That's for tree-shakers ;)

> I was thinking perhaps we can have a server side pixi for maybe say making multiplayer games and verify movements of a client using pixi?

If you are making multiplayer game - have my respect.

**Comment by MegaManLegends2** [comment]
Thanks everyone for your responses.

> If you are making multiplayer game - have my respect. Dont bother with that advanced client-side tooling, its not important.

Do you not recommend using pixi for a multiplayer game? I am really just starting to learn how to make multiplayer games with html5 canvas and javascript, and don't have much experience. Do you recommend another client side framework or just do vanilla javascript with html5 canvas?

**Comment by andrewstart** [comment]
Pixi will work fine for a multiplayer game, but because it is just a renderer, it has nothing to do with server or net code (which tend to be the more difficult parts).

**Comment by MegaManLegends2** [comment]
> Pixi will work fine for a multiplayer game, but because it is just a renderer, it has nothing to do with server or net code (which tend to be the more difficult parts).

Yeah that's the hardest part I would say, trying to tie everything together and get pixi stage and other objects and containers to be updated correctly as they interact with the server, but once I am passed that part it should be easier from there. For now I think I am going to stick with pixi along with a websockets server and see how I go from there.

**Comment by bigtimebuddy** [comment]
Good luck! Closing this issue as it seems answered.
