### ISSUE TITLE
Issue with pixijs v4 Spritesheet.js

### ISSUE THREAD

**Issue by lycwed** [pixijs/pixi.js#5553]
In Spritesheet.prototype._processFrames you are using `_.Rectangle` and `_.Texture` but the code can not resolve the `_`. When I replace the `_` with `PIXI` like this `PIXI.Rectangle` and `PIXI.Texture` it works.

**Comment by ivanpopelyshev** [comment]
We dont use it, its babel.

If you want to copy the class or override just one method, use this as reference: https://github.com/pixijs/pixi.js/blob/dev/packages/spritesheet/src/Spritesheet.js

Otherwise, please provide more information about the case.
