### ISSUE TITLE
How to compile a version without webgl function

### ISSUE THREAD

**Issue by redw** [pixijs/pixi.js#5559]
How to compile a version without webgl function. WeChat game is the largest js game platform in China. The open domain of WeChat game does not support webl, thank you!

**Comment by redw** [comment]
The function is ok, only display the information of friends in the open domain. Can only use canvas, can not use webgl. Additional functions can not, the smaller the package, the better.

**Comment by rtalon83** [comment]
Webgl: `new PIXI.WebGLRender(options, arg1, arg2)`
Canvas: `new PIXI.CanvasRender(options, arg1, arg2)`

Canvas is a PIXI version without webgl function.

Doc: http://pixijs.download/release/docs/index.html

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/issues/5459 I asked you to provide more information when I prepared a fix for it. That's the first time I hear that WeChat does not support WebGL.

I'm all for helping coders who do WeChat apps but it can't be a one-side game when you just ask us something and wait when we spend many hours to solve it!

Please provide more information if you want us to help you, and do reply to your own threads when we ask you to test something.

**Comment by ivanpopelyshev** [comment]
In this case, removing all WebGL from PixiJS is not possible because that's the focus of our library. I recommend to use something else if you want small canvas-only build. Did you try https://github.com/MassiveHeights/Black ?

**Comment by tywang2006** [comment]
I believe wechat support webgl, I got confirmed from one of my friends from tencent. they have ever done a 3D game in the built-in browser of wechat.

我相信微信支持webgl，我的腾讯的哥们以前在微信内嵌的浏览器做过3D游戏。 你确认是否是你自己的问题吗？@redw

**Comment by ivanpopelyshev** [comment]
According to https://stackoverflow.com/questions/54107987/wechat-webgl-minigame-not-working-on-a-device-but-works-in-devtool , WebGL is supported but you have to create `PIXI.Renderer` inside the first `requestAnimationFrame`.

Here's how to create your own application class , and how to create renderer separately from application: https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop

**Comment by redw** [comment]
> #5459 I asked you to provide more information when I prepared a fix for it. That's the first time I hear that WeChat does not support WebGL.
> 
> I'm all for helping coders who do WeChat apps but it can't be a one-side game when you just ask us something and wait when we spend many hours to solve it!
> 
> Please provide more information if you want us to help you, and do reply to your own threads when we ask you to test something.

WeChat games support webgl, but the open domain of WeChat games only supports canvas, and there are many friends and friends in the open domain.

**Comment by redw** [comment]
> I believe wechat support webgl, I got confirmed from one of my friends from tencent. they have ever done a 3D game in the built-in browser of wechat.
> 
> 我相信微信支持webgl，我的腾讯的哥们以前在微信内嵌的浏览器做过3D游戏。 你确认是否是你自己的问题吗？@redw

微信小游戏肯定是支持webgl的，微信小游戏的开放域不支持webgl

**Comment by redw** [comment]
> #5459 I asked you to provide more information when I prepared a fix for it. That's the first time I hear that WeChat does not support WebGL.
> 
> I'm all for helping coders who do WeChat apps but it can't be a one-side game when you just ask us something and wait when we spend many hours to solve it!
> 
> Please provide more information if you want us to help you, and do reply to your own threads when we ask you to test something.
Thank you very much! Yes, most of the environment supports webgl, but some environments are definitely not supporting webgl. Of course, the cavnas mode with pixi.js-legacy is also possible, but it can be reduced by configuration compilation. The size of the package is perfect.

**Comment by redw** [comment]
> e your own application c



> #5459 I asked you to provide more information when I prepared a fix for it. That's the first time I hear that WeChat does not support WebGL.
> 
> I'm all for helping coders who do WeChat apps but it can't be a one-side game when you just ask us something and wait when we spend many hours to solve it!
> 
> Please provide more information if you want us to help you, and do reply to your own threads when we ask you to test something.

I am Chinese, I really like pixi.js. I don’t know how to develop WeChat games with pixi.js in China. I am one of them. The demand for WeChat small game platform in China is quite large, and it is quite popular. In China, we use egret, layabox, cocos2d to develop WeChat games.

**Comment by redw** [comment]
> According to https://stackoverflow.com/questions/54107987/wechat-webgl-minigame-not-working-on-a-device-but-works-in-devtool , WebGL is supported but you have to create `PIXI.Renderer` inside the first `requestAnimationFrame` (inside PIXI Ticker)
> 
> Here's how to create your own application class , and how to create renderer separately from application: https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop
> 
> I hope you can follow that advice and this time report us back.

Last time I proposed a new function with insecure problems. It is because WeChat games are not supported. WeChat games are of course support for webgl, but WeChat's open domain does not support webgl. https://developers.weixin. Qq.com/minigame/en/dev/tutorial/open-ability/open-data.html?t=19040212

**Comment by tywang2006** [comment]
egret的创立者是我朋友 以前是adobe的项目经理，我建议你可以试着egret，他们做的还，PIXIJS-legacy 也是一个不错的选择。关于开放域的问题我觉得这个不是pixijs的bug，所以最好不要发在这里，因为我们调试是很花时间的，这样让人很迷惑，如果需要的是一种解决方案，社区是不错的选择。

**Comment by redw** [comment]
> egret的创立者是我朋友 以前是adobe的项目经理，我建议你可以试着egret，他们做的还不错，PIXIJS-legacy 也是一个不错的选择。关于开放域的问题我觉得这个不是pixijs的bug，所以最好不要发在这里，因为我们调试是很花时间的，这样让人很迷惑，如果需要的是一种解决方案，社区是不错的选择。

谢谢!egret的创立者是7悦是吧。我实际是要想要一个方案。自己修改下.

**Comment by redw** [comment]
> In this case, removing all WebGL from PixiJS is not possible because that's the focus of our library. I recommend to use something else if you want small canvas-only build. Try https://github.com/MassiveHeights/Black .

**Comment by redw** [comment]
> In this case, removing all WebGL from PixiJS is not possible because that's the focus of our library. I recommend to use something else if you want small canvas-only build. Try https://github.com/MassiveHeights/Black .

Thank you! I am Chinese, using google translation, may be a problem with google translation, I mean not to let you modify the pixi.js code, I want to compile a canvas version for the open domain of WeChat games. Can provide A little suggestion is the best.

**Comment by finscn** [comment]
@redw 开放域即将支持 webgl . (内测版的开放域已经可以使用 webgl 了)

**Comment by tywang2006** [comment]
> > In this case, removing all WebGL from PixiJS is not possible because that's the focus of our library. I recommend to use something else if you want small canvas-only build. Try https://github.com/MassiveHeights/Black .
> 
> Thank you! I am Chinese, using google translation, may be a problem with google translation, I mean not to let you modify the pixi.js code, I want to compile a canvas version for the open domain of WeChat games. Can provide A little suggestion is the best.

下次有什么问题建议的什么在http://html5gamedevs.com。
