### ISSUE TITLE
How can I draw the lines on holes in polygons?

### ISSUE THREAD

**Issue by lordjesus** [pixijs/pixi.js#5561]
How can I draw the lines on holes in polygons? In the example on [Pixi Playground](https://www.pixiplayground.com/#/edit/Ak~6AKnGVYdJTkmB1Y~W~
) I have created a polygon square and then defined two holes. If I draw the hole without calling `.addHole()` the shape gets drawn correctly with outline (the small triangle). If I call the function `.addHole()` it will correctly add a hole in the square shape, but the lines are not being drawn on the hole (big triangle). 

Just to be clear, I would like to be able to add one or more holes to a shape and have those holes be drawn with the same linestyle as the rest of the shape.

![image](https://user-images.githubusercontent.com/3789478/55553354-3dbd7400-56e0-11e9-90ec-b6b0e0bea6f0.png)

- **`pixi.js` version**: 4.8.7
- **Browser & Version**: Chrome v. 73.0.3683.86
- **OS & Version**: Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/Ak~6AKnGVYdJTkmB1Y~W~

**Comment by ivanpopelyshev** [comment]
Hey! It was fixed in pixi-v5 , https://github.com/pixijs/pixi.js/pull/5516 , dont mind the name of PR, it has the demo.

I dont know whether its possible to port it back to v4, maybe its an easy port, I can look later. Depending on whether you have big old project or new demo you can try v5.

**Comment by bigtimebuddy** [comment]
Your easiest solution in v4 is to draw another triangle where the hole is that has the line style and transparent fill.

https://www.pixiplayground.com/#/edit/kn8TI2dhHZLyTAR~MfIeM

**Comment by bigtimebuddy** [comment]
I don't think this is worth back-porting lines + holes. The graphics stuff is dramatically different in v5 and the hole API is half-backed in v4 anyways (doesn't work with shapes, etc). There's also a workaround above.
