### ISSUE TITLE
DisplayObject dissappear when positioned with falsey value

### ISSUE THREAD

**Issue by KoolieKangaroo** [pixijs/pixi.js#5564]
If a DisplayObject (Sprite/Container) is fed with a non numeric value such as undefined or NaN it will disappear from the displaylist without any error. 

I would at least expect a warning if this is by design (to avoid crashed perhaps)

```
let mySprite = new PIXI.Sprite(someTexture)
mySprite.x = undefined; // maybe coming from some setting with a missing value

```

example:
https://www.pixiplayground.com/#/edit/~DeMdvuebjHAySoW_Q8TG

**Comment by ivanpopelyshev** [comment]
Even better if you set `scale.x` to undefined, I think whole matrix goes to NaN , not only two `tx`, `ty` elements. Btw, how does ThreeJS react to that?
