### ISSUE TITLE
Canvas renderer addHole() change introduced in v4.8.3 release

### ISSUE THREAD

**Issue by ericente** [pixijs/pixi.js#5568]
(updated with new info): The Canvas Renderer renders holes differently in v4.8.3 than it did in v4.8.2.

Example:
V4.8.2:
![v4 8 2](https://user-images.githubusercontent.com/1676115/55755124-48e40d00-5a1c-11e9-8775-990da5834d05.png)

v4.8.3:
![v4 8 3](https://user-images.githubusercontent.com/1676115/55755130-4bdefd80-5a1c-11e9-98bb-1d6d169c7281.png)

**Comment by bigtimebuddy** [comment]
I'm pretty sure it must be this PR #5202 from @ivanpopelyshev, which was the only thing that changed in 4.8.3 related to holes and masks. I think something flipped directionally with the hole drawing. Maybe Ivan can clarify.

@ericente could you provide a simple sample polygon/draw calls that we can validate with?

**Comment by ericente** [comment]
Yeah, flipping the directions does change things. In the following example `gfx1` is wrong in 4.8.2 and correct in 4.8.3, and `gfx2` is correct in 4.8.2 but wrong in 4.8.3. 
```
var pixi = new PIXI.Application({ width:200, height:200});
document.body.appendChild(pixi.view);
var gfx1 = new PIXI.Graphics()
    .beginFill(0xFF0000, 1)
    .moveTo(10, 10)
    .lineTo(90, 10)
    .lineTo(90, 90)
    .lineTo(10, 90)
    .lineTo(10, 10)
    .moveTo(40, 40)
    .lineTo(60, 40)
    .lineTo(60, 60)
    .lineTo(40, 60)
    .lineTo(40, 40)
    .addHole()
    .closePath();
pixi.stage.addChild(gfx1);

var gfx2 = new PIXI.Graphics()
    .beginFill(0x00ff00, 1)
    .moveTo(190, 190)
    .lineTo(190, 110)
    .lineTo(110, 110)
    .lineTo(110, 190)
    .lineTo(190, 190)
    .moveTo(140, 140)
    .lineTo(160, 140)
    .lineTo(160, 160)
    .lineTo(140, 160)
    .lineTo(140, 140)
    .addHole()
    .closePath();
pixi.stage.addChild(gfx2);
```

**Comment by ivanpopelyshev** [comment]
OK, that means my algorithm is wrong somewhere.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev here's @ericente's example as fiddles:

* [v4.8.2](https://jsfiddle.net/bigtimebuddy/874Lsmz2/) (partially broken)
* [v4.8.3](https://jsfiddle.net/bigtimebuddy/d51eypmn/) (partially broken)
* [v5](https://jsfiddle.net/bigtimebuddy/9b6fudh8/) (completely broken)

WebGL is fine for v4 and v5. Doesn't care about the hole orientation.
