### ISSUE TITLE
Rounded rect with different radii

### ISSUE THREAD

**Issue by azertyalex** [pixijs/pixi.js#5570]
It is possible to draw rounded rectangles in a user friendly way.
```javascript
graphics.drawRoundedRect(50, 50, 100, 100, 10);
```
I can not find anything on how to draw a rounded rectangle with different radii.
Reading the documentation I think it is not possible, could this be added?

Example:
```javascript
graphics.drawRoundedRect(50, 50, 100, 100, r1, r2, r3, r4);
```

**Comment by azertyalex** [comment]
Currently I do this by drawing 4 rounded rects with their respective radii (r1, r2, r3, r4), and clipping out the corners.
But this seems a but convoluted.

**Comment by JohnKarel** [comment]
+1
Also seems really "convoluted" to me!

**Comment by ivanpopelyshev** [comment]
line-arc-line-arc-line-arc-line-arc

**Comment by JohnKarel** [comment]
And what about filling up? Isn't it much easier adding it to the rounded rect api?

**Comment by ivanpopelyshev** [comment]
> Isn't it much easier adding it to the rounded rect api?

Its completely valid feature request, because CSS already has border-radius for every corner.

However, it is also one of cases without pitfalls where users can learn what `graphics.quadraticCurveTo` does, that's why I wont approve such pull request without additional example "how to do it on your own" and link in the docs.

**Comment by JohnKarel** [comment]
Thanks for the excellent service :+1:

**Comment by ivanpopelyshev** [comment]
Anyway, now we need a hero, or maybe i'll do it next time I swipe the Graphics code (there were like 10 bugs in it last month).

**Comment by Makio64** [comment]
I just needed it on a project so here how to do it : 

```
export function drawRectRounded(graphics, x, y, width, height, topLeftRadius, topRightRadius, bottomRightRadius, bottomLeftRadius) {
	// Starting from the top left corner.
	graphics.moveTo(x + topLeftRadius, y)

	// Drawing the top line with top right corner.
	graphics.lineTo(x + width - topRightRadius, y)
	graphics.quadraticCurveTo(x + width, y, x + width, y + topRightRadius)

	// Drawing the right line with bottom right corner.
	graphics.lineTo(x + width, y + height - bottomRightRadius)
	graphics.quadraticCurveTo(x + width, y + height, x + width - bottomRightRadius, y + height)

	// Drawing the bottom line with bottom left corner.
	graphics.lineTo(x + bottomLeftRadius, y + height)
	graphics.quadraticCurveTo(x, y + height, x, y + height - bottomLeftRadius)

	// Drawing the left line with top left corner and closing the shape.
	graphics.lineTo(x, y + topLeftRadius)
	graphics.quadraticCurveTo(x, y, x + topLeftRadius, y)

	// Since this shape will likely be filled, closePath ensures that the shape is fully closed.
	graphics.closePath()
}

// Usage:
// const graphics = new PIXI.Graphics();
// drawRectRounded(graphics, 10, 10, 200, 100, 20, 30, 40, 50);
```

**Comment by stylustrader** [comment]
> I just needed it on a project so here how to do it if someone need it: [drawRectRounded](https://gist.github.com/Makio64/1223f7bc4cbe0465b4901eb8bf8f67ae)

the problem with this approach is that it doesn't automatically adjust the radius when the height or width changes dynamically and becomes less than the radius value.

with drawRoundRect(), it automatically adjusts the radius with dynamic height/width changes to prevent clipping.
