### ISSUE TITLE
These emoji characters become weird after letterSpacing

### ISSUE THREAD

**Issue by RhinoLu** [pixijs/pixi.js#5571]
### Expected Behavior
set letterSpacing should not change this character
![註解-2019-04-10-234205](https://user-images.githubusercontent.com/349025/55893380-b8a7f280-5bea-11e9-9f31-df370f0ff9aa.gif)

### Current Behavior
Please take a look :
[PixiJS TextStyle](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22letterSpacing%22%3A1%7D%2C%22text%22%3A%22%F0%9F%98%80%20%F0%9F%98%81%20%F0%9F%98%82%20%F0%9F%A4%A3%20%F0%9F%98%83%20%F0%9F%98%84%22%7D)

### Possible Solution
https://github.com/pixijs/pixi.js/blob/7476583718bb5a4586a82a071eac37272f14245d/packages/text/src/Text.js#L262
from
```
const characters = String.prototype.split.call(text, '');
let currentPosition = x;
let index = 0;
let current = '';
while (index < text.length) {
  current = characters[index++];
  if (isStroke) {
    this.context.strokeText(current, currentPosition, y);
  }
  else {
    this.context.fillText(current, currentPosition, y);
  }
  currentPosition += this.context.measureText(current).width + letterSpacing;
}
```
to
```
let currentPosition = x;
for (const s of text) {
  if (isStroke) {
    this.context.strokeText(s, currentPosition, y);
  } else {
    this.context.fillText(s, currentPosition, y);
  }
  currentPosition += this.context.measureText(s).width + letterSpacing;
}
```

### Steps to Reproduce
"letterSpacing: 0" is OK, otherwise become weird.

### Environment

- **`pixi.js` version**: 4.8.7
- **Browser & Version**: Chrome 73
- **OS & Version**: Windows10 & Mac 14
- **Running Example**: [PixiJS TextStyle](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22letterSpacing%22%3A1%7D%2C%22text%22%3A%22%F0%9F%98%80%20%F0%9F%98%81%20%F0%9F%98%82%20%F0%9F%A4%A3%20%F0%9F%98%83%20%F0%9F%98%84%22%7D)

**Comment by themoonrat** [comment]
Checked your fix, and it looks good! Putting up a PR for it now for v5

**Comment by themoonrat** [comment]
Fixed for next v5 release

**Comment by LeifRoss** [comment]
This seems to be broken again, but in a slightly different way.
Now the layout breaks on text containing emojis and non-default letterSpacing.

Examples:
[letterSpacing = 0.](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22miterLimit%22%3A20%7D%2C%22text%22%3A%22Hello%20World%20%F0%9F%98%8A%F0%9F%98%8A%F0%9F%98%8A%22%7D
)
[letterspacing = 1.](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22letterSpacing%22%3A1%2C%22miterLimit%22%3A20%7D%2C%22text%22%3A%22Hello%20World%20%F0%9F%98%8A%F0%9F%98%8A%F0%9F%98%8A%22%7D)

**Comment by cyocun** [comment]
@themoonrat @fanlistener 

Hi.

I had the same problem.
It seems to recur with surrogate pairs, such as for new emojis.
Is it possible to fix it?

Environment
PixiJS 6.4.2
Browser & Version: Chrome 107



https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22letterSpacing%22%3A8%2C%22wordWrap%22%3Atrue%7D%2C%22text%22%3A%22%F0%9F%99%86%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%F0%9F%98%80%20%F0%9F%98%81%F0%9F%98%A4%F0%9F%91%A8%E2%80%8D%F0%9F%92%BB%20%F0%9F%98%82%20%5Cn%22%7D

**Comment by SuperSodaSea** [comment]
@cyocun `Text` uses `Array.from` now, and it don't take care of multi-codepoint emojis. Now that we have [`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segmenter) that can split multi-codepoint emojis correctly, I think we can use it when the browser support it. I can make a PR for it later.

https://github.com/pixijs/pixijs/blob/e02cda6f8113f886c92717715f25845c5fd9d4d6/packages/text/src/Text.ts#L356-L362

```js
const s = '🙆🏻‍♂️😀 😁😤👨‍💻 😂';

console.log(s.split(''));
// ['\uD83D', '\uDE46', '\uD83C', '\uDFFB', '‍', '♂', '️', '\uD83D', '\uDE00', ' ', '\uD83D', '\uDE01', '\uD83D', '\uDE24', '\uD83D', '\uDC68', '‍', '\uD83D', '\uDCBB', ' ', '\uD83D', '\uDE02']

console.log([...s]);
// ['🙆', '🏻', '‍', '♂', '️', '😀', ' ', '😁', '😤', '👨', '‍', '💻', ' ', '😂']

const segmenter = new Intl.Segmenter();
console.log([...segmenter.segment(s)].map(x => x.segment));
// ['🙆🏻‍♂️', '😀', ' ', '😁', '😤', '👨‍💻', ' ', '😂']
```

**Comment by cyocun** [comment]
@SuperSodaSea 
Thank you for letting us know about the issues and fixes!

However, Firefox doesn't seem to support Intl.Segmenter.
Is there a better way? 🙁

**Comment by SuperSodaSea** [comment]
@cyocun You can make a polyfill for `Intl.Segmenter` using other libraries such as [`grapheme-splitter`](https://www.npmjs.com/package/grapheme-splitter) or [`graphemer`](https://www.npmjs.com/package/graphemer). Since the polyfill can be very large to handle various Unicode grapheme correctly, I don't think Pixi shall ship with it.

**Comment by SuperSodaSea** [comment]
@cyocun I added `Text.graphemeSegmenter` in #8893, which you can set to your own polyfill function.

**Comment by cyocun** [comment]
@SuperSodaSea 
Thank you for your response!

I have a consultation.
How can I apply this to pixi.js@6.4.2?
I forked 6.4.2 and wrote this change myself, but pixi.js doesn't build well. .

I've never dealt with something like this before and would appreciate it if you could tell me a better way.

**Comment by SuperSodaSea** [comment]
@cyocun Maybe you can try monkey patching `Array.from` like this:
```js
const _from = Array.from;
Array.from = function from(x) {
    if(typeof x === 'string') return polyfill(x);
    return _from(x);
}
```
Although this hack can break the behavior of `Array.from`, I think it can hardly affect other code.

**Comment by cyocun** [comment]
@SuperSodaSea 
Thank you for the nice solution!
The display of the emoji was successfully done with the method you provided!

However, there was another problem with pixijs@6.4.2. .
It seems that the width calculation did not work well, and when there were multiple emojis in one line, the right side was cut off.

Also, even with the latest pixijs, if breakWords is true, the emoji will break. 
Emojis are so nasty....

https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22breakWords%22%3Atrue%2C%22letterSpacing%22%3A8%2C%22wordWrap%22%3Atrue%7D%2C%22text%22%3A%22%F0%9F%99%86%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%F0%9F%98%80%20%F0%9F%98%81%F0%9F%98%A4%F0%9F%91%A8%E2%80%8D%F0%9F%92%BB%20%F0%9F%98%82%20%5Cn%22%7D

**Comment by SuperSodaSea** [comment]
@cyocun Without modifying Pixi's source code, you can try to replace `TextMetrics.wordWrapSplit` (in a nasty way, since the code for word wrapping is buggy):

```js
const segmenter = new Intl.Segmenter();
PIXI.TextMetrics.wordWrapSplit = s => {
    const result = [];
    for(const { segment } of segmenter.segment(s)) {
        result.push(segment);
        // wordWrap assumed char.length === 1, so we need some padding
        for(let i = 0; i < segment.length - 1; ++i) result.push('');
    }
    return result;
};
```

(You can paste this code to the console of the website you give, change the text to trigger a repaint and see the result.)

https://github.com/pixijs/pixijs/blob/a87bb87036d5fb9119ee92fd9c3da23b5bb9424b/packages/text/src/TextMetrics.ts#L562-L577

**Comment by bigtimebuddy** [comment]
Alternatively, try using @pixi/text-html plugin instead. https://github.com/pixijs/html-text This plugin uses HTML rendering and therefore does a better job with wrapping, letter-spacing and emojis. We have discussed making this the future of Text because it requires less code for layout.

**Comment by cyocun** [comment]
@SuperSodaSea 
Thank you so much for your really great solution. And very informative.
This time I decided to implement Text Class by myself instead of relying on pixijs. The code you taught me helped me a lot!

@bigtimebuddy 
Sounds good.
I should have noticed that plugin earlier 😭
Thanks for letting me know.
