### ISSUE TITLE
Ask. How to create a Graphic base on Sprite Shape?

### ISSUE THREAD

**Issue by egg734631** [pixijs/pixi.js#5577]
Excuse me, I have some problem.
 
How to create a Graphic base on Sprite Shape?

My Original task is like example " Sprite Alpha Mask ".

But I'm don't want the alpha, 

just want mask style like graphic but base on Sprite Shape .

Screen Shot Below:
1. Expect:
https://drive.google.com/file/d/14XjD4MGCQ1Kmh4TzZbzYIk2PpN9a2N2h/view?usp=sharing
2. Actual:
https://drive.google.com/file/d/1sAaekbFUSrNiboiTITP5C_cuark8f5Jz/view?usp=sharing

**Comment by ivanpopelyshev** [comment]
Put it something like https://www.codeandweb.com/physicseditor , then export polygons in json , load it in pixi, construct your graphics based on that json. That solution is not included in pixi.

Second way: copy SpriteMaskFilter sources, make your own filter that doesnt care about alpha value.

Third way: take pixi-heaven (https://github.com/gameofbombs/pixi-heaven/) , make sprite of the same color. If you need something to be done with alpha, you have to extend its MultiTextureSpriteRenderer and modify its shader code.

**Comment by egg734631** [comment]
It's Okay. Thank you for help!!!
I will try second way first. 
Maybe the solution will help other people.

**Comment by bigtimebuddy** [comment]
Seems answered as Ivan gave a couple solutions. Closing. Let us know if you need to reopen.
