### ISSUE TITLE
Broken path on http://pixijs.io website, no examples load

### ISSUE THREAD

**Issue by Ewan-Roberts** [pixijs/pixi.js#5578]
I popped you an email so sorry if this is a duplicate.

### Expected Behavior
PIXI.js will load on the example page, then a spinning bunny 

### Current Behavior
Canvas is black for all examples

### Possible Solution
The path for your cdn seems to be broken, maybe to do with you changing the name to pixi.io in the url path? 

### Steps to Reproduce
Go to your examples page below:
http://pixijs.io/pixi-examples-v2/#/basics/basic.js (in Chrome)

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by themoonrat** [comment]
The correct examples url is https://pixijs.io/examples/

How did you get to the url you described?

**Comment by Ewan-Roberts** [comment]
I had a good look and sorry to say I'm not sure :( 

I can't see myself typing out this url, but stranger things have happened.

I'll be sure to let you know if I find it. Apologies for the false flag

**Comment by themoonrat** [comment]
That's fine :) We should probably delete that repo @bigtimebuddy since it's not used anymore?

**Comment by Ewan-Roberts** [comment]
Here it is: https://www.google.com/search?q=pixi.js+examples&oq=pixi.js+examples&aqs=chrome..69i57j69i60l3j0l2.4751j0j4&sourceid=chrome&ie=UTF-8

**Comment by themoonrat** [comment]
Ah, I don't get it via my profile on google. A search on a fresh browser and it shows. Maybe since it's ranked 2 we should set up a redirect to the proper url instead

**Comment by bigtimebuddy** [comment]
I removed those examples and archived the repo.
