### ISSUE TITLE
Filters vs _filters : [add,remove,clear,get] ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#5579]
I would like to know if this has been proposed or discussed for v4 or v5?
I find it a bit strange to have 2 properties named **filters** and **_filters** in the **displayObjet**.
Could we have something that natively will do a better management for filters in objects.
Example:
```javascript
DisplayObject.filters.add(filter,index); 
DisplayObject.filters.remove(filter);
DisplayObject.filters.clear();  // same as 'DisplayObject._filters = null;'
DisplayObject.filters.get(index);
```
Or maybe there is a reason for the existence of these 2 properties that I do not consider?
thanks in advance

**Comment by ivanpopelyshev** [comment]
Nothing. Its just `filters` array in v5.

In my engine I use component `renderBehaviour` that can store filters, masks , other stuff, but I dont want to propose it here because its still in development and I change it very often.

**Comment by djmisterjon** [comment]
ho shit i see ! 
![image](https://user-images.githubusercontent.com/24865815/56166302-4301a500-5fa3-11e9-9391-5cb73c055316.png)
why I used that `_filters` everywhere!? i will have a lot of batch renaming jobs here!

Btw, so I'm going to extend methods to `DisplayObject` to control this in my projet, unless a future native alternative is already planned?
Because it's very annoying to do manage multi-filters with vanilla Arrays !

**Comment by djmisterjon** [comment]
oups not from dysplayObj , from the `class Container`
I will notice is there where `addChild` `addChildAt`, `swapChildren` , `getChildIndex` , `setChildIndex` , `getChildAt` ....

So my idea it to extend same method here but for manage filters
So maybe something like this... 
`addFilters`
`addFiltersAt`
`swapFilters`
`getFilterIndex`
`getFilterAt`
.....

**Comment by bigtimebuddy** [comment]
I think there some good ideas here @djmisterjon. I think the last one would be easy to implement as a mixin. Feels very much like mixin-get-child-by-name, on its own, not really complicated, but useful for some users and some situations. We recently added `DIsplay.mixin(target)`, so you can do something like this...

```js
Display.mixin({
  addFilterAt(filter, index) {},
  addFilter(filter) {},
  swapFilters(filter1, filter2) {},
  getFilterIndex(filter) {},
  getFilterByIndex(index) {},
  addFilters(...filters) {},
});
```

I probably wouldn't add this to the default bundle, but an optional package for users. Maybe for v5.1?

**Comment by djmisterjon** [comment]
interesting ! I did not know the existence of that!
```javascript
PIXI.utils.mixins.mixin(PIXI.Container.prototype,{
// stuff
})
```
i will check this more deep tomorrow, thank for the tips .
And a optional package for v5.1 look nice for me :)

**Comment by bigtimebuddy** [comment]
We removed the `utils.mixins` recently in v5 and replaced it with the more direct `DisplayObject.mixin`. It was used for interaction and accessibility targets but felt like we could simplify.
