### ISSUE TITLE
High GPU on loop

### ISSUE THREAD

**Issue by jasondonnellya** [pixijs/pixi.js#5580]
Hey guys, my first time posting on github and I'm trying to use pixi for game dev. I don't know if this is a stupid problem or not but running a loop with requestAnimationFrame() at 60fps is taking around 20% of my GPU usage on Task Manager, with antialias it's about 50%. This is with no sprites in the rendered container object. I understand that if there's nothing to render I shouldn't be calling the render method but this is from testing with tilemaps/camera panning/animated sprites and noticing the GPU was spiking so rerendering the stage every frame is kind of a necessity in the long run.

I've noticed that at smaller window sizes it works better but again I need it to run at the full window size and I understand that with a bigger screen it makes sense that it's harder to run. This is currently at a screen resolution of 1366 x 768.

This is a snippet of what I was using to test:

```javascript
var canvas = new PIXI.Renderer({
    width: window.innerWidth,
    height: window.innerHeight
}),
    stage = new PIXI.Container(),
    then = Date.now(),
    fps = 60,
    fpsInterval = 1000 / fps;

document.body.appendChild(canvas.view);

var loop = function () {
    requestAnimationFrame(loop);

    var now = Date.now(),
        elapsed = now - then;

    if(elapsed > fpsInterval) {
        then = now - (elapsed % fpsInterval);
        canvas.render(stage);
    }
}

loop();
```

Not even sure if that throttles the loop correctly but my main question is if I'm just being ignorant and this is standard at 60fps for pixi or not? Right now my game tests only use about 500 sprites on screen at once so they don't add much more to the GPU and CPU usage is almost non-existent but I'm worried about running on a lot of different hardware and how much I'll be adding in the future. For example I've added a camera zooming feature and need antalias for it to not squash and stretch in an ugly fashion, so if it takes up 50% of my GPU with nothing else on screen it's kind of stressful. 

If this isn't normal then does my laptop have a buggy graphics driver or something? I've also noticed that another process called Desktop Window Manager uses a lot of usage in accordance to pixi running but I'm not sure how webGL works or if that's supposed to be running or not.

I'm willing to lower the FPS to 30 if this is just standard so I was wondering if you guys have advice about if 30fps is good for games to run or if it's limiting?

Thank you very much and sorry again if this is a bad post!

**Comment by bigtimebuddy** [comment]
Hey @jasondonnellya, first congrats on your first GitHub post 🎉 . We feel honored you posted to PixiJS!

I'm sure others might chime in thoughts. Also, you might want to try http://www.html5gamedevs.com which is a good resources for beginner or general queries. The community is pretty active there.

Also, it's helpful with performance issues if you can share your browser, OS version, and hardware (e.g., Graphics card, laptop make, etc).

**Comment by rtalon83** [comment]
Welcome @jasondonnellya 

If I were you, I firts will create a simple test in `https://www.pixiplayground.com/` with basic sprite. Then, You might look your GPU/CPU percentage about this test, maybe your problem is other.

You can see examples in `https://pixijs.io/examples/` and test your performance too.

**Comment by jasondonnellya** [comment]
Thanks for the quick replies guys!

Browser: Chrome,
OS: Windows 10,
Laptop Make: Dell Inspiron 15700 Gaming
Graphics cards: Intel(R) HD Graphics 630 and NVIDIA GeForce GTX 1050

I tried some of the pixijs.io examples but they're having the same problem it just sits at 20% GPU usage even when nothing is being rendered or spikes up really bad even on small things being rendered.

I've done a bit of research and think chrome is using the intel graphics card instead of both and that's why it's not performing well. I tried:

```javascript
powerPreference: "high-performance"
```

in the renderer constructor function but it doesn't seem to make a difference.

I did a chrome://gpu check and there's a few things that pop out to me that I don't quite understand, like the native GPUMemoryBuffers is software only and hardware acceleration is disabled and another thing that popped out to me is that my optimus is false which is apparently the NVIDIA GPU switching technology

**Comment by rtalon83** [comment]
Check here: http://webglreport.com/

You musth read `This browser supports WebGL 1/2`

**Comment by Dairnon** [comment]
There is a high chance it's prioritizing the Intel gpu over the Nvidia one.

**Comment by Owlzy** [comment]
My money would be on the laptop using onboard graphics too.  In my experience those laptops do strange things.  I recently came across a similar issue with GPU spikes in a C# game library, and it turned out to be device related where it was trying to share work between the GPU's.  I'd try a different device before going too crazy looking for code fixes.

**Comment by jasondonnellya** [comment]
I've been messing around for hours with the GPU chrome flags and trying to forcibly activate everything, as well as updating my NVIDIA driver but nothing seems to be making a difference. Looked into a lot of stuff about NVIDIA optimus laptops and how chrome and NVIDIA don't work well together.

In chrome://gpu it says that it's using the NVIDIA gpu but I have a feeling it's using the integrated graphics card in the background. I'll try it on a different computer soon and see what happens. In the meantime can I ask how your guys systems fare? I'm guessing this isn't common?

**Comment by djmisterjon** [comment]
@jasondonnellya  what say @Dairnon can make  sence here. 

Did you check on what **GPU ID** your app or web run ?
In you case you have a hybride gpu in your cpu, and a external gpu card.
![image](https://user-images.githubusercontent.com/24865815/56203916-349fa180-6014-11e9-82e1-14dc15e4d01a.png)
be sure your app,browser,game.. ... run on the **NVIDIA GeForce GTX 1050 ID**
and not on your **cpu/gpu HD Graphics 630**

Those flag can also interesting you 
`--gpu-active-device-id=0x1b81 --supports-dual-gpus=false --ignore-gpu-blacklist --disable-gpu-driver-bug-workarounds --use-angle=gl --enable-gpu-scheduler --gpu-testing-vendor-id=0x10de --gpu-testing-device-id=0x1b81`
more flag here example : https://peter.sh/experiments/chromium-command-line-switches/

Also this link can help you to get more info
https://www.lifewire.com/hardware-acceleration-in-chrome-4125122

**Comment by ivanpopelyshev** [comment]
Two videos system aren't common. Also I have very heavy app in development. ~millions lines of code, 500gigapixels of content. It performs on intel hd graphics 3000 with 20FPS. 

I remember several threads like this - bad performance at simple one-bunny example. We do wait for the hero who can make complete guide on that problem, including "antialias:false" (default) and "transparent:true" (NOT DEFUALT) and other hacks, how they affect browser rendering engines on different systems.

**Comment by djmisterjon** [comment]
you can also check on your panel to force how window manage your default gpu 
![image](https://user-images.githubusercontent.com/24865815/56205249-3fa80100-6017-11e9-923c-227ef8809f3e.png)

**Comment by jasondonnellya** [comment]
Thanks for the extra help guys! I'm fairly certain it is running on the NVIDIA graphics card and is still on the same performance so it might have been this whole time. Starting to think that my GPU might just be poop or WebGL just doesn't like it, cause I run pretty heavy games on this laptop at higher settings. Do you think it's viable for me to still try make games at 60fps and hope I don't push it too far for a 2D game or should I lower it?

**Comment by ivanpopelyshev** [comment]
Try transparent option

```
var canvas = new PIXI.Renderer({
    width: window.innerWidth,
    height: window.innerHeight,
    transparent: true
}),
``` 

And do your games at 60FPS. You can always add switch to 30FPS and even make it default setting later. The idea is to apply ` * delta` in your animation, where `delta = Math.min(elapsed / fpsInterval, 5);`. This fpsInterval is different from yours, its **targetFPS** interval (targetFPMS in pixi) and not actual that you use to render stuff.

https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop

**Comment by djmisterjon** [comment]
I find your message rather disturbing! because am on Nvidia 1070 and it seem only ~x2 performance from you1050.
And GTX 1050 are relatively good recent card from last Pascal Architecture!
![1_ll6taa1F3jdjmUY8PahDIw](https://user-images.githubusercontent.com/24865815/56208462-3458d380-601f-11e9-8f59-5efd9bb391ef.png)

Are you able to provide a printScreen of https://www.pixiplayground.com/ like this ?
![image](https://user-images.githubusercontent.com/24865815/56208402-0c697000-601f-11e9-9f97-ac08663f3816.png)

Am curious because my game are really heavy , and am curious to see if i will have future problem from **gamers used a GTX 1050 !**
I test my game on GTX 1060 and not issue, but 1050 should be good and you should get average ~~10,12% if we take the logic of the bench from my 1070 vs 1050.

20%load on GPU it really heave for just draw a sprite !! And i think something wrong !

**Comment by jasondonnellya** [comment]
@ivanpopelyshev  I see, you mean like an offset for the FPS change in things like animation speed and movement physics? Thanks for the help! I think I get it.

@djmisterjon  If the window is resized smaller it takes less GPU so I have to keep it at fullscreen but now that you mentioned it I haven't looked into the Desktop Window Manager much and it could be a cause as to why it's taking so much GPU. It only takes more when I run webGL tho it's very very low like 0.1% when it's not running:

![Test](https://user-images.githubusercontent.com/41059325/56209901-9419a380-604c-11e9-89a7-d2aa7580d375.png)

I looked it up and it says that the NVIDIA graphics sends a buffer to the desktop windows manager for the integrated graphics card to then display it on screen because the intel gpu is in charge of the screen rendering, any thoughts?

**Comment by Dimous** [comment]
Hello there, may I chime in?

![image](https://user-images.githubusercontent.com/283939/56210343-fe583580-6098-11e9-8642-61ef56b0c219.png)

**Comment by ivanpopelyshev** [comment]
> I looked it up and it says that the NVIDIA graphics sends a buffer to the desktop windows manager for the integrated graphics card to then display it on screen because the intel gpu is in charge of the screen rendering, any thoughts?

I think I remember something like that, its a part of all double-video systems. Even on PC with two videos (nvidia+intel for example) you can hook up displays into both cards, and you dont have a problem when you move a window from one display to another. In that case you shouldn't worry because that overhead will appear in all apps that use nvidia.

**Comment by jasondonnellya** [comment]
Fair enough, I probably should have posted a screen cap from the start so sorry about that haha, i'll start only focusing on the individual program's GPU instead of the overall usage and ignore the DWM.exe

**Comment by jasondonnellya** [comment]
Thanks guys you've been a huge help! I've been freaking out about this for longer than I'll admit over fear of running into problems, now I can develop happily :)

**Comment by bigtimebuddy** [comment]
Going to close, since it more or less seems resolved. Thanks everyone for you generous advice.
