### ISSUE TITLE
app.view draw to canvas

### ISSUE THREAD

**Issue by hacer-healer** [pixijs/pixi.js#5581]
### Expected Behavior
Can the canvas content(app.view) generated by pixi be drawn to an existing canvas?

- **`pixi.js` version**: 5.0.0_
- **Browser & Version**: _e.g. Chrome 60_

**Comment by ivanpopelyshev** [comment]
Use https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels just after rendering.

`readPixels` is synchronous operation that will be marked in your profiling as 100% CPU usage, however it doesn't actually consume CPU resources, it just waits when info from videomemory will be available.

How its done in pixi: http://pixijs.download/dev/docs/PIXI.extract.html , `renderer.plugins.extract.pixels()` if you want to take current image. Better do it just after `render()` operation

How its done inside pixi: https://github.com/pixijs/pixi.js/blob/dev/packages/extract/src/Extract.js#L165

**Comment by hacer-healer** [comment]
This is done in order to refer to app.view by foreignObject svg, a direct reference to the words will affect other functions, I would like to add this namespace Can

**Comment by bigtimebuddy** [comment]
Is this what you're looking for?

```html
<canvas id="stage" width="800" height="600"></canvas>
```
```js
// If using an Application
var app = new PIXI.Application({
  view: document.querySelector("#stage")
});
// Alternately:
var renderer = PIXI.autoDetectRenderer({
  view: document.querySelector("#stage")
});
```

**Comment by hacer-healer** [comment]
Thanks.This is a good method. In addition, I found that when I overwrite svg onto the canvas, the brush provided by d3 is invalid. Is there any prohibition in the app?
