### ISSUE TITLE
Antialias is not working when rendering to textures

### ISSUE THREAD

**Issue by JohnKarel** [pixijs/pixi.js#5583]
When rendering graphics/roundedrects to textures; antialias is not used. Although this is defined in application options AND is set on the renderer object.

### Expected Behavior
Antialias works
### Current Behavior
doesnt

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: https://pixiplayground.com/#/edit/8DkP2AoK9qL3iXtUFX3cL

**Comment by ivanpopelyshev** [comment]
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1

> antialias
> If the value is true and the implementation supports antialiasing the drawing buffer will perform antialiasing using its choice of technique (multisample/supersample) and quality. If the value is false or the implementation does not support antialiasing, no antialiasing is performed.

Only on main drawing buffer.

WebGL2 supports MSAA but we can use webgl2 only in v5 and we didnt implement it yet.

Use the workarounds, feel the pain of all us, vector-lovers!

**Comment by jdelrue** [comment]
Got a hint to workarounds?

**Comment by ivanpopelyshev** [comment]
For static elements - `graphics.generateCanvasTexture()` , then put it in sprite. There's a small detail: you need to adjust sprite anchor accordingly to graphics local bounds, like `anchor.x = -bounds.x / bounds.width`

**Comment by jdelrue** [comment]
This is not available in pixijs5, so I guess there is no workaround in pixi5 yet?

**Comment by ivanpopelyshev** [comment]
its availble in `pixi-legacy.js` because it requires an algorithm from canvas2d.
