### ISSUE TITLE
Rounded rects look weird in v5

### ISSUE THREAD

**Issue by JohnKarel** [pixijs/pixi.js#5584]
Left border of rounded rects looks very weird in pixiv5. Same works flawlessly in v4.8.

### Expected Behavior
Nice rounded rect
### Current Behavior
Ugly rounded rect

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: https://pixiplayground.com/#/edit/vAe2zb~6rHek295Eu3QVl

**Comment by ivanpopelyshev** [comment]
Strange, we had an issue like that but i cant find it :(

**Comment by bigtimebuddy** [comment]
This was fixed in #5567
