### ISSUE TITLE
Attribute.from has wrong parameter order

### ISSUE THREAD

**Issue by ASWC** [pixijs/pixi.js#5586]
Seen on PIXI 5.0.0.
Even though it's not used anywhere, the static function Attribute.from has wrong parameter order:

Attribute.from = function from (buffer, size, stride, start, normalized)
{
    return new Attribute(buffer, size, stride, start, normalized);
};

function Attribute(buffer, size, normalized, type, stride, start, instance)

normalized and stride are reversed.

**Comment by bigtimebuddy** [comment]
Merged.
