### ISSUE TITLE
Missing arrayBuffer for response XMLHttpRequest PIXI.Loader?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#5593]
hi guys, when load a Audio from PixiLoader, we canot get the **arrayBuffer**.
It needed for create a `decodeAudioData ``ctx.decodeAudioData(req.response, resolve, reject);`
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData

i try with a classic `XMLHttpRequest` with promise, and am able to get the arrayBuffer.
I think it a bug ? or i miss something in the pixiLoader ?
**I need those information for create a Pitch filters for Pixi-audio. :)**
I made a screen but if you need a demo on playGround, just tell me.

In Red from pixiLoader, green it what i should get .
![aegegaeg](https://user-images.githubusercontent.com/24865815/56331127-0f687b80-6159-11e9-82d8-930c28a950ad.jpg)

**Comment by bigtimebuddy** [comment]
I’m doing this with pixi-sound. You can set a response type by extension (link below). You can also pass it to the loader.add options.

https://github.com/pixijs/pixi-sound/blob/master/src/loader/LoaderMiddleware.ts

**Comment by bigtimebuddy** [comment]
Seems answered. Closing

**Comment by djmisterjon** [comment]
i reopen sorry :) , 
despite your explanation , i try hard , but not able to decode data from pixi.loader.


this example it a classic pitch filter
https://www.pixiplayground.com/#/edit/~mgqw~OL0FsA7InSgyWJN
`this.start('B');` it without pixi.load
and if you replace by `this.start('A')` it where am not understand.
Not allowed to get decode data.
Or maybe you store decodeData somewhere in pixiSoud, i look, but not able to find.

**Comment by djmisterjon** [comment]
forget me sorry , it fixed, i was misunderstood your answer. :)
