### ISSUE TITLE
The site of "pixijs.download" is down!

### ISSUE THREAD

**Issue by webpatch** [pixijs/pixi.js#5595]
nslookup pixijs.download

;; Got SERVFAIL reply from 1.0.0.1, trying next server
;; Got SERVFAIL reply from 8.8.8.8, trying next server
Server:		1.0.0.1
Address:	1.0.0.1#53

** server can't find pixijs.download: NXDOMAIN

**Comment by bigtimebuddy** [comment]
Known issue, we’re working on it

**Comment by fanjules** [comment]
I normally use the online documentation, so am now stuck.
Is there an alternative location for the documentation, e.g. a mirrored version on Amazon S3, or downloadable zip, etc.

**Comment by themoonrat** [comment]
I'd recommend checkout out the repo and getting them yourself. Will only take a few mins
npm i
npm run docs

**Comment by ivanpopelyshev** [comment]
Yo, @fanjules ! 

There's a workaround that'll always work: 

```bash
git clone git@github.com:pixijs/pixi.js.git
cd pixi.js
git checkout v4.x
npm install
npm run docs
```

Third line in case you need v4.

Look into `dist` folder for v5 .
Also, docs are generated from sourcecode, so if you have a wide-screen monitor you can dedicate some space to extra window of your favorite IDE with opened PixiJS project, sources give much more information than just docs.

If you use any of JetBrains products I recommend to mark those folders as excluded: `dist` for v4, or whole `node_modules;lib` inside project settings in "exclude filtes" input.

**Comment by fanjules** [comment]
Thanks guys!  Hope you get the site problems sorted it soon

**Comment by bigtimebuddy** [comment]
Fixed! Thanks to @englercj
