### ISSUE TITLE
Treat loader with JSON created from blob

### ISSUE THREAD

**Issue by zoohie** [pixijs/pixi.js#5597]
Hi everyone.

I'm trying to create some sort a game and i came up with problem with loader, to be exact, i want to treat loader with json file, that is created from an object within my project (not in project dist) and created an url from blob for it. The thing is that i want my assets to be in base64 format with linked json. Let me show in example.

First, I have my JSON stored like an object:
```javascript
static GetImagesJson() {
        return {"frames":{/*FRAMES HERE*/},"meta":{"image":this.DataURItoBlob(this.GetImages()),"size":{"w":2324,"h":2351},"scale":"1"}};
}
```

where this.GetImages() return me a base64 atlas with my images. Then i convert them into an url from blob.

```javascript
static DataURItoBlob( dataURI ) {
        let byteString = atob(dataURI);
        let ab = new ArrayBuffer(byteString.length);
        let ia = new Uint8Array(ab);
        
        for (let i = 0; i < byteString.length; i++) {
            ia[i] = byteString.charCodeAt(i);
        }
    
        let blob = new Blob([ab]);
        return URL.createObjectURL(blob);
}
```

After, generating url from JSON object and treating it to loader.

```javascript
static GetAssets() {
                let jsonUrlFromBlob = this.DataURItoBlob( JSON.stringify( this.GetImagesJson() ));
		return new Promise((resolve) => {
		PIXI.loader
                .add("imgs", "assets/sprites.json") //this works perfectly, but
                .add("imgs1", jsonUrlFromBlob) //does not, as it's treated 
                .load( (loader, resources) => {
			loader.reset();
			loader.destroy();
			resolve(resources);
                });
	});
}
```

Here what i get:
![image](https://user-images.githubusercontent.com/26651167/56420013-fe2c8580-62a4-11e9-98a4-a7cda7623b7a.png)

To conclude, i want my assets to be stored via code, to lessen the http request and get in the end a single html bundled file.

Hope you can get what i'm trying to archive. Feel free to ask for additional info or whatever.

Regards, Ihor

P.S. I've tried to set value of "image" in JSON with base64 image, still not working

**Comment by ivanpopelyshev** [comment]
Do you actually need BLOB here?

`BaseTexture.from(image)` and `new PIXI.Spritesheet` should be enough.

**Comment by zoohie** [comment]
Thanks for your answer, Ivan

Well, I need any working solution ;)

I've tried this approach too, unfortunately, didn't work.
```javascript
let image = new Image();
    image.src = "data:image/png;base64," + this.GetImages();

let baseTexture = new PIXI.BaseTexture(image);
let fullSprite = new PIXI.Sprite.from("baseTexture"); //full image is OK, it can be shown on the page
let spritesheet = new PIXI.Spritesheet(baseTexture, this.GetImagesJson(baseTexture)); //in GetImagesJson i set baseTexture to meta's image key
let sprite = new PIXI.Sprite(spritesheet.textures["oliver"]); //doesn't show anything, as spritesheet has no textures
```

So that's what I get:
![image](https://user-images.githubusercontent.com/26651167/56427210-bff28e80-62c3-11e9-8e0e-43e123deafd1.png)

Might I made a mistake somewhere?

**Comment by ivanpopelyshev** [comment]
You have to call `parse` method manually: https://github.com/pixijs/pixi.js/blob/dev/packages/spritesheet/src/Spritesheet.js#L160

It'll be sync in case of less than 10000 frames and async in case there are more, its because some users complained that the parsing hangs up the application for very big spritesheets.

**Comment by zoohie** [comment]
Thanks, Ivan

That solved my problem!

Have a nice day.

Regards, Ihor
