### ISSUE TITLE
All examples on site are broken

### ISSUE THREAD

**Issue by anselanza** [pixijs/pixi.js#5601]
- **Browser & Version**: _Chrome 73_ and _Firefox 66_
- **OS & Version**: _ Ubuntu 18.04_ and _Mac OS 10.14.4_
- **Running Example**: _https://pixijs.io/examples/#/demos-basic/container.js_

All examples on the PixiJS site appear to be broken, always with an error in the console like:
```
ReferenceError: PIXI is not defined
```

**Comment by anselanza** [comment]
Also probably relevant:
```
Loading failed for the <script> with source “https://d157l7jdn8e5sf.cloudfront.net/dev/pixi.js”.
```

**Comment by themoonrat** [comment]
Same issue as https://github.com/pixijs/pixi.js/issues/5595

**Comment by bigtimebuddy** [comment]
Fixed! Thanks to @englercj
