### ISSUE TITLE
Invalid metrics for some tall chars when zooming in the browser. And now different height for bold and regular font

### ISSUE THREAD

**Issue by iv-menshenin** [pixijs/pixi.js#5610]
there is another way to fix it:
in `pixi.js/packages/text/src/TextMetrics.js`

**al line 544:**
```js
canvas.height = height + 1;
```
instead of
```js
canvas.height = height;
```
and then, **at 584 line:**
```js
properties.ascent = baseline - i + 1;
```
instead of
```js
properties.ascent = baseline - i;
```
it just adds 1px to the top of the canvas. this method has no side-effects
have a look please
@bigtimebuddy @themoonrat

_Originally posted by @iv-menshenin in https://github.com/pixijs/pixi.js/issues/5594#issuecomment-485430676_

**Comment by iv-menshenin** [comment]
This issue relates to https://github.com/pixijs/pixi.js/issues/5594#
After these changes on our codebase, we have a side-effect: we have offset of baseline for regular font versus bold font.
![image](https://user-images.githubusercontent.com/38577106/56505834-66899a00-6525-11e9-9cde-866ea01f7a09.png)

**Comment by iv-menshenin** [comment]
And this commit should be reverted:
https://github.com/pixijs/pixi.js/commit/3c019c77ca5482e2213b2acc1d9860d260cdabb6

**Comment by themoonrat** [comment]
A "+1" sounds like a hack without some evidence as to why it's the best solution. Surely actually calculating the height is better than fudging it?

**Comment by iv-menshenin** [comment]
not. I do not claim to be the ultimate truth. I just wanted to say that the solution with BASELINE gives side effects while we only need to increase the canvas by 1 px
In any case, you know better than me how to fix it.

**Comment by iv-menshenin** [comment]
And I am tried magic with these settings:
- METRICS_STRING
- BASELINE_SYMBOL
- BASELINE_MULTIPLIER

everything looked bad

**Comment by themoonrat** [comment]
@iv-menshenin  That is a separate issue unrelated to the previous PR. Here is a playground using text from the last 4.8.7 version of PixiJS: https://www.pixiplayground.com/#/edit/Sgm5c~TGHlUfmN6bTBEss

Bold text and unbold text take up different amounts of space, so when you put them side by side they may not all have the same baseline. 

I'd have no idea how to begin on solving that. You've have to measure every style variant I guess, and then pick something that they can all work on. It might be more in the scope of a non official pixi plugin: https://github.com/tleunen/pixi-multistyle-text

**Comment by iv-menshenin** [comment]
How did this happen? how can I remove the previous comment?
