### ISSUE TITLE
Help setting the position of a sprtie to another sprite in a different container

### ISSUE THREAD

**Issue by MegaManLegends2** [pixijs/pixi.js#5612]
So I have been trying to figure out how to do this correctly. So, let's say I have containerA which has spriteA child, and we have containerB which has spriteB child, and we add both containers to app.stage, so they are not children of one another.
So now how would I go about setting the position of spriteB to equal the position of spriteA?
Is there a way in which I could set the global position of a sprite to a value? I was thinking of that since I can get the global position of spriteA using the toGlobal() method, but then I don't know how to set the global position of spriteB to the global position of spriteA...

I am using the latest release of PIXI v4 by the way.
Hope anyone can help me with this... Thanks

**Comment by bigtimebuddy** [comment]
You mostly got it. `toGlobal` will give you the global/world position of a display object, and using `toLocal` will allow you to translate that position to a local coordinate space in any container.

**Comment by MegaManLegends2** [comment]
Thank you!! I got it to work now :)
