### ISSUE TITLE
Pixel font gets blurred when rendered

### ISSUE THREAD

**Issue by FaultyNeuron** [pixijs/pixi.js#5613]
Not sure if this is a bug. Might also be caused my floating imprecisions in the fonts I have tested. 
I have also posted this as a [SO question](https://stackoverflow.com/questions/55692097/make-pixel-font-display-pixelated-without-antialiasing). You can find a screenshot of the current behaviour online.

### Expected Behavior
Font is displayed with sharp edges (alpha of each pixel is either 0 or 1).

### Current Behavior
Font is blurred on the edges.

### Steps to Reproduce

I am using [this](https://fontmeme.com/fonts/pokemon-classic-font/) font for `fonts/pokemon_classic.ttf` (I found no way to host that font online, so no jsfiddle), but you can use any pixel font you like.

#### JS:
```
PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
let scale = 30;
let app = new PIXI.Application();
document.body.appendChild(app.view);

app.renderer.view.style.position = "absolute";
app.renderer.view.style.display = "block";
app.renderer.autoResize = true;
app.renderer.resize(window.innerWidth, window.innerHeight);

let root = new PIXI.Container();
app.stage.addChild(root);
root.scale.set(scale);

document.fonts.load('8pt "pokemon"').then(() => {
    let text = new PIXI.Text("Test", {fontFamily: 'pokemon', fontSize: 8, fill: 0xff1010});
    root.addChild(text);
});
```

#### CSS:

```
@font-face {
    font-family: 'pokemon';
    src: url("fonts/pokemon_classic.ttf");
}

* {
    padding: 0;
    margin: 0;
}
```

- **Browser & Version**:  Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- **OS & Version**: Windows 10

**Comment by ivanpopelyshev** [comment]
Nearest filtering.

Try it:

```js
text.updateText();
text.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
```

or just enable it for ALL SPRITES:

```
PIXI.settings.SCALE_MODE = PIXI.sSCALE_MODES.NEAREST;
```

**Comment by FaultyNeuron** [comment]
Thanks for the suggestion. But `PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;` is already the first line of my code.

**Comment by bigtimebuddy** [comment]
I think it’s more of a context2d issue (which Is how Text is rendered) rather than a Texture issue.

Perhaps hacking [imageSmoothingEnabled](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled) = false into your PixiJS might help. If that works, let us know.

**Comment by bigtimebuddy** [comment]
For pixelated fonts, however it probably better to use BitmapText. It’s faster and easier to render pixel accurately.

**Comment by ivanpopelyshev** [comment]
> But PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST; is already the first line of my code.

Something wrong with my eyes :)
