### ISSUE TITLE
Transparent Graphics cannot trigger click(v5.0.0-rc3)

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixi.js#5614]
But it's normal in v4.

demos:
[v4](https://jsfiddle.net/JetLu/1fuLqjmo/)
[v5](https://jsfiddle.net/JetLu/yLozj731/)

**Comment by ivanpopelyshev** [comment]
I don't know how to fix that without breaking some new v5 features. Workaround:

```
const g = new PIXI.Graphics()
	.beginFill(0xffcc33, 1.0)
  .drawRect(0, 0, 500, 500)
  .endFill()
g.alpha = 0.0;
```

**Comment by ivanpopelyshev** [comment]
Probably, its new default behaviour and not a bug.

We have to mention it in changelist.

Thank you!

**Comment by themoonrat** [comment]
I doesn't feel good to have the inconsistency to have transparent graphics not register a click whilst transparent sprites do.

**Comment by ivanpopelyshev** [comment]
v5 Graphics logic:
Every shape has fill and stroke. Transparent fill = no fill. Transparent stroke = no stroke.

**Comment by JetLua** [comment]
Got it

[Graphics.js](https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/Graphics.js#L591-L596)

```js
const visible = alpha > 0;

if (!visible) {
  this._fillStyle.reset();
}
```

**Comment by JetLua** [comment]
@ivanpopelyshev 

[GraphicsGeometry.js](https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/GraphicsGeometry.js#L367-L370)

I try to fix it in the following way: 

```js
GraphicsGeometry.prototype.containsPoint = function containsPoint (point)
{
    var graphicsData = this.graphicsData;

    for (var i = 0; i < graphicsData.length; ++i)
    {
        var data = graphicsData[i];

        console.log(data.fillStyle)
        /** === **/
        if (!data.fillStyle.visible && !data.fillStyle.alpha)
        /** === **/
        {
            continue;
        }
.....
```

Will there be any side effects?

**Comment by ivanpopelyshev** [comment]
No, try it

**Comment by JetLua** [comment]
[https://pixiplayground.com/#/edit/3MoUUu4MD8~ZGpY25LaK_](https://pixiplayground.com/#/edit/3MoUUu4MD8~ZGpY25LaK_)

I removed the entire `if` statement and it looked OK. Affect performance?
Well, stroke only half works.

![FastStoneEditor1](https://user-images.githubusercontent.com/6738986/56843793-9d223480-68d8-11e9-93e3-ba3ed467cb6b.png)
