### ISSUE TITLE
The region parameter of generateTexture seems to be ignored in 5.0.0-rc3

### ISSUE THREAD

**Issue by balance80** [pixijs/pixi.js#5615]
Hi, I've been generating previews from sections of my main renderer using generateTexture with the region parameter. This works in Pixi 4.8.7, but not in 5.0.0-rc3.

Example with 4.8.7: https://www.pixiplayground.com/#/edit/ac2myHBKVqT9xqzm5k2d7
![image](https://user-images.githubusercontent.com/481780/56744396-b613d400-6778-11e9-8aa5-2b3f2ed7bb73.png)

Example with 5.0.0-rc3: https://www.pixiplayground.com/#/edit/xa1Hx9m9MbJqLiAzf1MmF
![image](https://user-images.githubusercontent.com/481780/56744510-f1160780-6778-11e9-8988-4a53c86f106e.png)

Clicking the "Crop" button should generate a cropped texture from a region in app.stage, create a sprite and render it onto a different renderer which we then get a PNG from using toDataURL on the view canvas. In 5.0.0-rc3 the region sent into generateTexture is just ignored it seems.

Code used to generate texture with the region parameter
```
var cropTexture = myRenderer.generateTexture(
    app.stage,
    PIXI.SCALE_MODES.LINEAR,
    1,
    new PIXI.Rectangle(x, y, w, h),
);
```

Then generateTexture in turn calls this.render, which takes in the region as a transform. Comparing the code for 4.8.7 and 5.0.0-rc3 I can see that handling of the transform sent into the render function has changed.

4.8.7; transform is used on the renderTexture
```
Renderer.prototype.render = function render (displayObject, renderTexture, clear, transform, skipUpdateTransform) 
{
    ...
    this.bindRenderTexture(renderTexture, transform);
    ....
}
```

5.0.0-rc3; transform is still sent in, but not used at all
```
Renderer.prototype.render = function render (displayObject, renderTexture, clear, transform, skipUpdateTransform)
{
    ....
}
```

I don't have the insight into the inner workings of Pixi to say if this matters or not, but I thought I should mention it :)

1. Has something changed and I'm just doing it wrong, or is this a bug?
2. Is there some other/better way I should be creating thumbnails from sections of a renderer?

**Comment by ivanpopelyshev** [comment]
#5603 , fixed 4 days ago.

It works with latest dev, https://pixijs.download/dev/pixi.js
