### ISSUE TITLE
How do I create a line-pattern-filled rectangle?

### ISSUE THREAD

**Issue by dorsharon** [pixijs/pixi.js#5618]
Hi, i'm new to Pixi and I can't seem to find a way to render a rectangle with vertical stripes for a fill pattern.

Is there any way to create a texture to a pattern fill for a rectangle in Pixi api?

**Comment by bigtimebuddy** [comment]
Check out TilingSprite class, which is designed for such a thing.

Example:
https://pixijs.io/examples/#/sprite/tiling-sprite.js

**Comment by dorsharon** [comment]
Thanks for replying.
Would you be able to supply an example of using TilingSprite for a vertical lines pattern fill for rectangle? It would help me a lot.

**Comment by bigtimebuddy** [comment]
You’ll need to create a repeating pattern of lines as an external image and use the example above to get started. Good luck! 

I’m going to close this because your initial question is answered. If others want to provide more help, they can leave comments below.
