### ISSUE TITLE
[Feature] Allow for manual rendering, without halting the 'Application' ticker.

### ISSUE THREAD

**Issue by Turbine1991** [pixijs/pixi.js#5620]
I'm building an application and it would be useful to trigger the rendering manually when a change occurs, as occurred as opposed to default behaviour of 'PIXI.Application'.

The solution people propose is to halt rendering through the 'autoStart: false' option, affecting the ticker's rendering behaviour. However this requires calling the update/render event manually, defeating the purpose of using the ticker. (Unless you create another ticker to do this)
Example: [https://github.com/pixijs/pixi.js/blob/69e6cee71ebd5ef7834c7f7b269c0c105d32ba19/packages/ticker/src/Ticker.js#L568](url)

I propose a new 'Application' parameter 'autoRender', to cleanly control the rendering logic contained in the ticker.

### Workaround
```javascript
PIXI.Application.prototype.render = null; // Disable auto-rendering by removing the function
const app = new PIXI.Application({ width: 200, height: 200, backgroundColor: 0xFFFFFF });
document.body.appendChild(app.view);

app.ticker.add(() => {
    if (condition) // Manually render when something has changed
        app.renderer.render(app.stage);
});
```

### Environment

- **`pixi.js` version**: v5.0.0-rc.3

**Comment by themoonrat** [comment]
The `Application` class is a simple helper class for creating apps in PixiJS and contains common properties and functions. It's mega helpful for us in the examples we provide, for instance. But it is not meant to be a 1 stop solution for all use cases. For more complex requirements, we advise that users create their own version of `Application` that takes into account their needs, which is what I would advise you to do :)

**Comment by Turbine1991** [comment]
> The `Application` class is a simple helper class for creating apps in PixiJS and contains common properties and functions. It's mega helpful for us in the examples we provide, for instance. But it is not meant to be a 1 stop solution for all use cases. For more complex requirements, we advise that users create their own version of `Application` that takes into account their needs, which is what I would advise you to do :)

I don't agree it's a complex requirement, in-fact, I'd argue every application made using Pixi.js would potentially want to render manually.

For example, this is how much of my GPU is used to render a blank fullscreen canvas @ 60fps.
![usage2](https://user-images.githubusercontent.com/7228980/56849797-663a3600-694d-11e9-95f3-b0b2e1a68a9c.png)

Sure, the hardware isn't the most powerful. (Surface Pro 4 2016, Intel 520) An application wouldn't be viable on my device with the default rendering behaviour, it just isn't powerful enough.

**Comment by themoonrat** [comment]
If you don't want the extra things that Application provides, then just create a Renderer and update it when you want.
```
const renderer = new PIXI.Renderer(800, 600, { backgroundColor: 0x1099bb });
document.body.appendChild(renderer.view);
const stage = new PIXI.Container();
// some stuff, only want to manually render
renderer.render(stage);
```

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop

PixiJS Application class is used as training wheels. The more abilities we add there, the more people will use it and forget "Whats an event loop?" and "Whats a renderer?". 

We do not have enough tutorials and documentation, that's why we might leave some natural obstacles for people to train on. Its completely safe, it doesnt have pitfalls, optimal place for training.

I agree that autoRender is useful feature, but I'm also afraid that someone else will ask "why does not pixi re-render only if something was changed?".
