### ISSUE TITLE
How to redraw elements after stage scale?

### ISSUE THREAD

**Issue by dorsharon** [pixijs/pixi.js#5622]
When i scale the stage (like app.stage.scale.x = 2), the rectangles and TilingSprites I drew become blurry.

How do I make sure they redraw on scale so that this won't happen?

thanks!

**Comment by ivanpopelyshev** [comment]
It shouldn't work like that. Please give more information.

**Comment by dorsharon** [comment]
I have an issue supplying working code because I use data that is dynamically generated in a complex piece of code.

but the point is that, I'm trying to do sort of Gantt:
![image](https://user-images.githubusercontent.com/23096334/56862530-9a950d00-69b4-11e9-962f-8df487efbec8.png)

and when I zoom in, I set the scale of the stage (only on X axis) and it looks bad:
![image](https://user-images.githubusercontent.com/23096334/56862540-bdbfbc80-69b4-11e9-9769-74dd411fab72.png)

The Tiling Sprites are blurry and the lines that border the primitive rectangle become very thick.

How can I handle redrawing so that the tiling sprite will re-render the repeating background and perhaps also handle the rectangle line border thing?

**Comment by ivanpopelyshev** [comment]
'tilingSprite.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST'

As for graphics there is nativeLine param in constructor, it works only for lineWidth=1. If you need bigger line width, you have to refill graphics according to scaling and pixi will re-create the mesh.

Adding dynamic line scaling in graphics is a huge problem, we are waiting for hero who solves it :)

**Comment by dorsharon** [comment]
> If you need bigger line width, you have to refill graphics according to scaling and pixi will re-create the mesh.

How do I do that?
Can you guide me with a code snippet?

**Comment by dorsharon** [comment]
≈

> '''tilingSprite.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST'''

also, I used this and this isn't the result I meant, I should have been more clear.
I wanted the background to repeat in its original resolution, not the stretched out one

**Comment by ivanpopelyshev** [comment]
`tilingSprite.tileScale = 0.5` to compensate scale 2 on stage.

> Can you guide me with a code snippet?

```js
graphics.clear(); 
// now do everything again
```

The problem is that pixi Graphics does not have operation that re-calculates the whole mesh. Theoretically, its possible to do if you dig inside the code and figure out how to drop all graphicsData and redo it. 

In practice, either people make it and don't report us back, either its too difficult. That's one of things that I'm waiting community to take care of.

**Comment by dorsharon** [comment]
> tilingSprite.tileScale = 0.5 to compensate scale 2 on stage
For some reason this doesn't work, I'm not seeing the tiling sprite at all after applying this method:
![image](https://user-images.githubusercontent.com/23096334/56884447-78fa5b00-6a72-11e9-90bd-7d98ed4a1e5b.png)

Also:
> As for graphics there is nativeLine param in constructor,

How do I provide this param?
I'm not seeing anything about it in the docs.

Thank you for your help, as you can tell, I'm new to Pixi :)

**Comment by dorsharon** [comment]
Never mind, I managed to figure it out.
I had to use tileScale.x instead of just tileScale.
Also, I figured that to use NativeLines I need to simply pass true or false to the Graphics constructor. Wish the docs made it more clear.
Thank you @ivanpopelyshev !
