### ISSUE TITLE
Sprite as mask seems broken in v5rc3

### ISSUE THREAD

**Issue by JohnKarel** [pixijs/pixi.js#5624]
Testing sprites as masks seems broken in v5rc3. This seems only to be the case if the sprite is created from a rendertexture.

### Environment

- **`pixi.js` version**: _e.g. 5.0 rc3_
- **Browser & Version**: _e.g. Chrome 73_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: https://pixiplayground.com/#/edit/e9EyNbhRGlnG2T0Mt1Ktw

**Comment by JohnKarel** [comment]
Tested in 4.8.7: same problem

**Comment by ivanpopelyshev** [comment]
Graphics masks is created through stencil and it exists on all geometry.

Sprite mask use red and alpha channels, so blue actually doesn't cover it :(

We'll make setting for different color channels for sprite masks in future.

For now you can rebuild PixiJS with patched SpriteMaskFilter: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/filters/spriteMask/spriteMaskFilter.frag#L22

change `masky.r` to `masky.a` and it'll be fine.

**Comment by ivanpopelyshev** [comment]
Its possible to do from outside: Need a copy of SpriteMaskFilter and need to override one of MaskSystem methods, I'll do it in a hour . This is the place: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/mask/MaskSystem.js#L137
