### ISSUE TITLE
The PointerEvent interaction API sometimes emits mouseup/mousedown events as mousemove events

### ISSUE THREAD

**Issue by SamStonehouse** [pixijs/pixi.js#5625]
I discovered this issue after a MacOS user reported different behaviour on Safari than Chrome, when using different mouse buttons to interact with the canvas at the same time.

### Current Behavior

As Safari doesn't have support for window.PointerEvent it uses the 'mousedown', 'mouseup' and 'mousemove' events instead of the newer pointer events. The code below is how this is defined in Pixi.js in Interaction Manager.

```
if (this.supportsPointerEvents) {      // this.supportsPointerEvents = !!window.PointerEvent;
  window.document.removeEventListener('pointermove', this.onPointerMove, true);
  this.interactionDOMElement.removeEventListener('pointerdown', this.onPointerDown, true);
  this.interactionDOMElement.removeEventListener('pointerleave', this.onPointerOut, true);
  this.interactionDOMElement.removeEventListener('pointerover', this.onPointerOver, true);
  window.removeEventListener('pointercancel', this.onPointerCancel, true);
  window.removeEventListener('pointerup', this.onPointerUp, true);
} else {
  window.document.removeEventListener('mousemove', this.onPointerMove, true);
  this.interactionDOMElement.removeEventListener('mousedown', this.onPointerDown, true);
  this.interactionDOMElement.removeEventListener('mouseout', this.onPointerOut, true);
  this.interactionDOMElement.removeEventListener('mouseover', this.onPointerOver, true);
  window.removeEventListener('mouseup', this.onPointerUp, true);
}
```

### Issue

When PointerEvents are used, if a mouse button is held down, and then a second one is pressed, the second mouse button down event is a 'pointermove', not a 'pointerdown', then, the next button released, whether it was the mouse button depressed first or not is also a 'pointermove' event, and then the last button released is a 'pointerup'.

This differs from the 'mouseup' and 'mousedown' behaviour as they will always fire correctly whether another mouse button is already down or not.

There's a demo for Pixi events here: https://jsfiddle.net/8pfz4vL9/
There's a general demo of PointerEvents here: https://jsfiddle.net/0svmbLea/1/

### Expected Behavior

Not sure what the expected behaviour should be, other than that it should be emitting consistent events from Pixi. After having a quick look at the pointer API it does seem you could get the information off a 'pointermove' event to determine that it actually is a 'mousedown' or 'mouseup' event thought I've not dug deep enough into the objects to be totally sure.

As a temporary solution I've had to disable disable other mouse events while one mouse button is held down.

### Possible Solution

- Change 'pointermove' events to emit 'mouseup'/'mousedown' events in certain circumstances
- Completely split out pointer and mouse interaction and let users handle them separately (probably not what you want to do but it's an option)

### Environment

- **`pixi.js` version**: _4.8.7_
- **Browser & Version**: _Chrome and Firefox_
- **OS & Version**: _Windows 10_

**Comment by themoonrat** [comment]
Hiya!

I sort of had a go at fixing https://github.com/pixijs/pixi.js/pull/5605, but need to have a re-think about it. There are lots of other issues around pointer events.

The problem comes because the official spec for pointer events are that pointerdown is only sent when the first button is pressed, and pointerup is only sent when the last button is released. This is different to the official mouse events or touch events spec.

So you come to the problem; do we follow the spec, or try to normalise behaviour across specs to have a special "here's what pixi does".

I haven't quite worked that out yet! My instinct right now is that if you listen to a mousedown, you get a mouse event and all the behaviour it comes with. Right down you could listen to a mousedown but get a pointerdown behaviour, or vice versa, and that's definitely not right.

**Comment by themoonrat** [comment]
PS any change to this would be v5 only. To avoid pointer event behaviour altogether in v4, then do 
```
const interactionDOMElement = app.renderer.plugins.interaction.interactionDOMElement;
app.renderer.plugins.interaction.removeEvents();
app.renderer.plugins.interaction.supportsPointerEvents = false;
app.renderer.plugins.interaction.setTargetElement(interactionDOMElement);
```
After creating your renderer

**Comment by SamStonehouse** [comment]
Apologies for not seeing the issue already there, feel free to close this.

For me, Pixi not following the spec is fine, it's an engine built on top of the other events so I aren't expecting it to follow another spec.

I guess it depends on how broad a solution you think is required too, pixi could provide different models for capturing input, so when initialising Pixi you can choose something like `simpleModel` which uses mouse events and ignores pointer events, and `pointerModel` which uses the pointer model and a pointer events polyfill (maybe?). I imagine it working as a map between DOM events and Pixi events, so a user could even implement their own if they so wished.
