### ISSUE TITLE
PIXI 5 - Sprites disappearing in RenderTextures after sprite texture unloaded?

### ISSUE THREAD

**Issue by fanjules** [pixijs/pixi.js#5626]
I have noticed some of my sprites disappearing that are in render textures.  This did not happen on PIXI 4, only PIXI 5.

It has been a frustrating bug to evaluate as it is very intirmittent.  If the rendertexture is rendered constantly I do not see the bug.  However, the rendertextures with the problem are rendered infrequently.  When the problem occurs, if I call render on the rendertexture again in the next frame the sprites are back in the rendertexture again.

I realised only sprites which used textures not in the main scene were affected.  So I found one way to fix this was to place dummy sprites in the main scene, but hidden (like with a tiny scale).  This isn't really a solution though.  I did try called render on renderTexture twice but this did not seem to work.

I presume that anything that is rendered constantly is kept "fresh".  I soon learn about there is a special PIXI garbage collector removing old resources, though changing it's settings to manual seemed to have no effect.  I also did not want to manage it manually.  However, I did wonder if the texture is being unloaded from the GPU some other way.

I then looked at the sprites basetextures used by the sprites and noticed that values suggested it was being unloaded, confirming my assumptions:

The value baseTexture._eventsCount becomes "0" when unloaded.  Once active again baseTexture.dirtyId is incremented by one.  Hopefully this will mean something to the PIXI devs.

Since this didn't occur in PIXI 4, it seems PIXI 5 does not reload the texture back onto the GPU in time for it to be available when render is called on the renderTexture?

PIXI 5 RC 3
Chrome 73
Windows 10 64bit

I have made a fiddle...

https://jsfiddle.net/fanjules/h8dpgxw1/

Click render to render the render texture.  Pay attention to "_eventsCount" in the table.  When it becomes 0, click render again - and no sprite!   A second click and normality is restored since the texture is presumably in memory.   On PIXI 4 I presume the texture is reloaded to memory again in time before the render.

**Comment by ivanpopelyshev** [comment]
OK, it seems like createImageBitmap is not that good as we thought.

When image is uploaded first time , or first time after we clean it because no one used it - createImageBitmap is called and real upload happens only in a frame or two.

We didnt take into account the fact that users love renderTextures , I think its better if we switch that thing off by default, or maybe texture resources should know whether current frame is rendered on screen or in renderTexture.

`PIXI.settings.CREATE_IMAGE_BITMAP=false` should solve it. Or you can turn of pixi gc `PIXI.settings.GC_MODE=PIXI.GC_MODES.MANUAL` before renderer creation.

@bigtimebuddy @GoodBoyDigital guys, i think we have a problem here!

**Comment by ivanpopelyshev** [comment]
Anyway, thank you or the *very detailed* report, your efforts in recognizing why async texture loading can be sometimes bad are recognized.

**Comment by fanjules** [comment]
Thanks for the response, both fixes work (I had previously disabled the garbage collector without effect but should have done this after renderer creation).

For now I have kept createImageBitmap on so I don't lose it's performance benefit, and will disable the GC instead.

Perhaps being able to mark some baseTextures as "do not unload" or "ignoreGC" may offer an elegant solution, this way the GC can stay on but individual textures can be protected.

And/or perhaps a special version of .render() could be made which delays execution until a supplied list of textures are uploaded on the GPU, though this arguably a greater undertaking I would assume.

**Comment by ivanpopelyshev** [comment]
Both your ideas are good :)

**Comment by bigtimebuddy** [comment]
You can use [resourceOptions](http://pixijs.download/dev/docs/PIXI.resources.html#.autoDetectResource) to turn on/off createImageBitmap.
```js
const baseTexture = BaseTexture.from('blah.png', { resourceOptions: { createBitmap: false } } );
```

**Comment by fanjules** [comment]
That will be useful.  But will it also be possible to exclude a resource from the automated garbage collection with a similar flag, whilst still keeping the GC on automatic?  That would suit my usage case better than unloading then uploading a texture without benefit of createImageBitmap performance.

**Comment by bigtimebuddy** [comment]
We disabled createImageBitmap by default, so you'll have to opt-in or use the global flag to toggle on and off per things loading.
