### ISSUE TITLE
Make `sharedTicker` default to `true` in `PIXI.Application` constructor

### ISSUE THREAD

**Issue by EvidentlyCube** [pixijs/pixi.js#5628]
### Expected Behavior
When I add a new listener to App's ticker that runs with the priority above `INTERACTION` priority I expect it to run before the interactions out of the box.

### Current Behavior
My listener runs after the input interactions because the interactions hook up to `PIXI.ticker.shared` while a new instance of `PIXI.Application` by default creates its own ticker. 

### Possible Solution
1. Modify the constructor of `PIXI.Application` so that `sharedTicker` is `true` by default. I don't foresee this having any real impact on existing applications.
2. Alternatively force the user to provide the value for this options (and throw an exception when it is not provided) so that they have to make an informed decision.
3. Or update the documentation for [Interaction Manager](http://pixijs.download/dev/docs/PIXI.interaction.InteractionManager.html) to contain this as a warning to the users.

### Environment

- **`pixi.js` version**: 4.8.5

The code that adds interaction manager events to shared ticker: https://github.com/pixijs/pixi.js/blob/v4.x/src/interaction/InteractionManager.js#L709
Code that creates the new ticker in `PIXI.Application`: https://github.com/pixijs/pixi.js/blob/v4.x/src/core/Application.js#L106

I understand there is a reason behind the default behavior which would invalidate option 1 but my search turned up nothing. Option 2 is likely to be impossible because of the philosophy that makes it as easy as possible to set PIXI up.

**Comment by themoonrat** [comment]
For v5, Interaction and upload textures to the gpu are on their own 'system' ticker, whereas anything animation wise is on the 'shared' ticker

I've create a PR that explains this better in the Application docs
