### ISSUE TITLE
tree shaking in v5

### ISSUE THREAD

**Issue by federicovezzoli** [pixijs/pixi.js#5629]
Hi guys, I'm moving to v5 right now.
Anyone can give me any tip for how use tree shaking to only import the features I need?

For example I need only core and filters, but I don't understand how to do it.

thanks a lot

**Comment by bigtimebuddy** [comment]
Check out this tool: https://pixijs.io/customize it should help you enable only the things you want.

**Comment by bigtimebuddy** [comment]
Is that what you're looking for @federicovezzoli? If so, please close.

**Comment by federicovezzoli** [comment]
yes, you made my day.
