### ISSUE TITLE
Request: Extend documentation about parent/child relationship

### ISSUE THREAD

**Issue by ganzf** [pixijs/pixi.js#5636]
Hello,

I am very new to PixiJS and am relatively unaware of how the parent/child relationship works.
I've seen example using Sprites where the size is defined by the loaded asset.
However, i'm trying to build a GUI based on PIXI.Graphics() rather than fixed-sized sprites.
My issue is how scaling/sizing works for children inside a container.
I've seen that position is relative to parent in the documentation, however i've not found anything related to size.
What i've noticed is that specifying the width/height of a child does not behave the same. How could I group graphics (so that moving the parent moves the children) but still being able to specify the size of children in absolute terms (width of 200 pixels for example). Or even better, could I specify the width of the child as a percentage of the parent (say 95% for example).

Maybe the parent/child relationship is not meant for this purpose and I should implement my own ? Maybe there are plugins I can use ? (I'm already using pixi-viewport). 

Thank you for you help :) #reques

**Comment by ivanpopelyshev** [comment]
It all comes from Flash.

Position, rotation and scale  are local Transform, first-class citizen. There are two extra fields, pivot and rotation.

World Transform is parent transform multiplied by local transform.

Width and height are calculated fields that use getLocalBounds and change scale.

Sprites have anchor that allows to adjust texture position.

Unfortunately, there's no second scale that affects only current element without children. The workaround is simple - extend a Container , put whatever you need as first child,  add 'size' field that adjusts scale of child.

Many people asked us, pixijs core team to do something about it, but we are waiting for community to come up with something. The best attempts are pixi-viewport and pixi-ui (no docs, only helpful author). Others dont share their solution, but if you have specific questions, people are ready to answer here and html5gamedev forum.

**Comment by ivanpopelyshev** [comment]
Parent/child relation works for 

1. Adding removing elements to stage
2. Transform sharing (move X and all children also move)
3. Event bubbling
4. Bounds calculation
5. Heavy rendering (masks, filters)

If you know pixijs code good enough, you can use different Transform for your elements, like my pixi-projection that allows 2.5d and 3d. Or pixi-spine that uses very advanced tranfrom, that can drop scale or rotation for children (thanks EsotericSoftware)

Other aspects also can be improved with hacks, for example, pixi-display changes rendering a lot and even allows tricks like deferred rendering.

Of course we will improve our scene tree, but its a slow process. If you look in issues PRs and our discussions in pixijs slack (ask invite if you are ready to talk to advanced guys), you'll see that sometimes we work like crazy. And yet, we still have nothing better than Flash transform and parent-child relation.
