### ISSUE TITLE
Empty "plugins" object in Application instance

### ISSUE THREAD

**Issue by mmagik** [pixijs/pixi.js#5638]
This occurs when app creates by:
`const app = new PIXI.Application()`
As a result i have empty `app.renderer.plugins` object and error while rendering

<img width="826" alt="Снимок экрана 2019-05-02 в 20 19 09" src="https://user-images.githubusercontent.com/21048113/57094397-21314d80-6d19-11e9-8281-ffad1d951ce9.png">

If you create only PIXI.Renderer instance everything is ok.

### Environment

- **`pixi.js` version**: _5.0.0_

**Comment by themoonrat** [comment]
All of the examples at https://pixijs.io/examples/ use pixi application and work fine. Do they work for you? If so, could you create a playground please to demonstrate your issue? Thanks!

**Comment by bigtimebuddy** [comment]
https://pixiplayground.com/#/edit/x3ESF0Fpp16K4kp6DlQm5

@mmagik, can you tell us more about your environment? How are you importing PixiJS into your project? Are you using a bundler like Webpack? Which packages are you importing?

**Comment by mmagik** [comment]
@bigtimebuddy, I use webpack in create-react-app and install pixi.js with npm.
I tried to use pixi v5.0.0-rc2 - its ok

And when I install latest version of pixi from npm I have this massage in console:
<img width="255" alt="Снимок экрана 2019-05-02 в 22 14 19" src="https://user-images.githubusercontent.com/21048113/57100544-dcf97980-6d27-11e9-9912-7b680d310f9d.png">

@themoonrat Yes, in this example all works right

**Comment by bigtimebuddy** [comment]
Are you importing by doing `import { Application } from 'pixi.js'` or `import { Application } from '@pixi/app'`?

The version number in the console is wrong for 5.0.0. This was fixed in #5635 and will get fixed for 5.0.1.
