### ISSUE TITLE
How to create a new package for v5 ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#5639]
I want to create a new package for v5.
the package could be build (there are some right js files in  lib & dist of package) 
But it's not included in  pixi.js.
And there are some errors : 
![image](https://user-images.githubusercontent.com/288367/57104878-0a601a80-6d5c-11e9-8606-2c7d1971d374.png)

**Comment by bigtimebuddy** [comment]
Is `@pixi/texture-animation` included in the **pixi.js** dependencies in package.json? Could you provide your code/repo?

**Comment by finscn** [comment]
Yes , it's included in the pixi.js dependencies in package.json.
the repo is  https://github.com/finscn/pixi.js/tree/v5-plus

**Comment by finscn** [comment]
I know the reason :  the build script doesn't create  the  symbolic of texture-animation in bundles/pixi.js/node_modules/@pixi 

How to do it ?

**Comment by bigtimebuddy** [comment]
npm run bootstrap

**Comment by finscn** [comment]
I see.
