### ISSUE TITLE
Performance Question: Does changing properties to same value cause PIXI to do work?

### ISSUE THREAD

**Issue by distinctdan** [pixijs/pixi.js#5640]
For performance in my game, I'm currently setting all objects' `visibility` properties to `false` every frame, then doing a tree lookup with my camera's visible area to set the visible ones to `true`. However, I'm wondering if this is causing pixi to do extra work. Like, does pixi use getters/setters for object properties? Here are some contrived examples:

```
// Does toggling visibility cause pixi to do extra work?
myContainer.visible = false;
myContainer.visible = true;

// Same question for object props.
mySprite.rotation = Math.PI;
mySprite.rotation = 0;
```

If pixi is using getters/setters and is doing extra work every time I set these properties, then I can easily track them myself and only set them when they're changed. Just wanting to know if that's necessary.

**Comment by bigtimebuddy** [comment]
`visible` is a vanilla property, no cost here.
`rotation` is a pass-thru for transform.rotation which is a setter. This does some math to re-compute the skew, but only if rotation is changed (so in your case yes).

**Comment by djmisterjon** [comment]
this will maybe interest you, i was ask similar question here 
https://github.com/pixijs/pixi.js/issues/4638
This will depending of your source code and game system.

Menue,huds sprites Out of camera are `.renderable = false` on my side and seem more fast.

**Comment by ivanpopelyshev** [comment]
All computations are lazy, it doesnt matter if you set rotation 10 times per frame or just 1. Even then, the cost of drawing sibgle element is much more than setter+matrix computation. It will affect your app only on 5000+ elements.

**Comment by distinctdan** [comment]
Great, so sounds like minimal impact from setting values, even though some properties do have setters. Thanks for the info guys.
