### ISSUE TITLE
Resizing canvas behind sprite texture regression in v5

### ISSUE THREAD

**Issue by steve-o** [pixijs/pixi.js#5641]
### Expected Behavior
Resizing a PIXI.Sprite to match a PIXI.Texture matching an underlying HTML5 Canvas.

![v4.5.3 expected visual output](https://i.imgur.com/Q0N3Y4x.png)

### Current Behavior
In v4, whether intentionally or not, it visually works as expected.  In v5 the functionality has regressed and the baseTexture size is not updated causing distortion in the image.

![v5.0.0 visual regression](https://i.imgur.com/kc1Y2TK.png)

### Steps to Reproduce
These are the steps currently in use for resizing; width is protected against being zero otherwise Chrome raises many errors.
```
let canvas = document.createElement("canvas");
let sprite = new PIXI.Sprite.from(canvas);
...
canvas.width = new_width > 0 ? new_width : 2;
sprite.texture.orig.width = new_width;
sprite.width = new_width;
sprite.texture.update();
```

The value of `new_width` may be fractional.

### Environment
- pixi.js 4.5.3, and 5.0.0.
- Chrome 76.
- Demo with 5.0.0: http://ahyoomee.miru.hk/zignage/not-so-tiny-ticker.html
- Demo with 4.5.3: http://ahyoomee.miru.hk/zignage-previous/not-so-tiny-ticker.html

**Comment by steve-o** [comment]
Viewing the texture via `console.log` in v4.5.3, dimensions appear correct,
![4.5.3 - console dump](https://user-images.githubusercontent.com/258627/57119733-6c0f8d00-6d3a-11e9-8d95-977e44041ccc.png)
In v5.0.0 the width of `baseTexture` remains at original setting of 1408.
![5.0.0 - console dump](https://user-images.githubusercontent.com/258627/57119734-6ca82380-6d3a-11e9-8cae-845f8cc645e3.png)

**Comment by ivanpopelyshev** [comment]
Workaround: try something with sprite.texture.baseTexture.setSize

**Comment by ivanpopelyshev** [comment]
I'm preparing a fix.

**Comment by ivanpopelyshev** [comment]
Please try pixijs.download/dev-texture-canvas-update/pixi.js 

I'll test it myself in several hours. Your case also allowed to solve another one, #5609

**Comment by steve-o** [comment]
Updated, looks good, thanks.

**Comment by ivanpopelyshev** [comment]
fixed that too. You can omit setting width now,

**Comment by bigtimebuddy** [comment]
Merged!
