### ISSUE TITLE
beginTextureFill behaves weirdly with non-square Textures?

### ISSUE THREAD

**Issue by M00nR4bb1t** [pixijs/pixi.js#5646]
### Expected Behavior
`PIXI.Graphics.beginTextureFill()` can render a non-square texture.
### Current Behavior
`PIXI.Graphics` behaves very weirdly when made to render a non-square texture.
### Steps to Reproduce
Supply a non-square texture to `PIXI.Graphics.beginTextureFill()` and use `drawRect()` to draw it.
### Environment

- **`pixi.js` version**: _5.0.0_
- **Browser & Version**: _Chrome Version 73.0.3683.103 (Official Build) (64-bit)_
- **OS & Version**: _macOS Mojave Version 10.14.4_
- **Running Example**: _https://www.pixiplayground.com/#/edit/XqJMwvedJ6AgVsvAvFgBn_

**Comment by ivanpopelyshev** [comment]
Did we use width instead of height somewhere? Interesting

**Comment by ivanpopelyshev** [comment]
Btw, im making new tutorial and it has simple tilemap implementation https://github.com/ivanpopelyshev/pixi-starfighter , maybe it will give you some ideas

**Comment by M00nR4bb1t** [comment]
> Did we use width instead of height somewhere? Interesting

Maybe, it's really weird...

> Btw, im making new tutorial and it has simple tilemap implementation https://github.com/ivanpopelyshev/pixi-starfighter , maybe it will give you some ideas

Well, here I'm trying to make a bitmap font renderer, but I'll take a look regardless. Thanks!

**Comment by ivanpopelyshev** [comment]
Please confirm that pixijs.download/dev-textureFill-offset-height/pixi.js works for you

**Comment by bigtimebuddy** [comment]
Merged.

**Comment by m00nr4bb1t** [comment]
Awesome, thanks! :)
