### ISSUE TITLE
PIXI.SpriteMaskFilter without color?

### ISSUE THREAD

**Issue by jasondonnellya** [pixijs/pixi.js#5647]
Is there a way to deactivate the color masking for the mask filter so it only uses alpha? I read up about it using the r channel but I don't know much about WebGL filters and shaders. Is there an easy setting to just remove the color masking?

Preferably without having to just remove it from the pixi file itself, I wanted to be able to choose some masks to remove color and others to be just alpha masks.

Thanks! Appreciate everything from you guys

**Comment by jasondonnellya** [comment]
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/mask/MaskSystem.js#L137

Only seeing this now was mostly searching Google posts but I still don't understand how to create my own SpriteMaskFilter with the ability to choose between colour and alpha instead of explicitly removing colour altogether, gonna look into it more tomorrow sorry about this guys

**Comment by ivanpopelyshev** [comment]
Good question, good search skills. Yeah, its a problem for many people, but I'm sorry I cant give you the code right now, I'm dead on my feet =) If you dont use npm webpack and all that - just patch `pixi.js` file and, replace` masky.r` with `masky.a` and be done with it.

**Comment by jasondonnellya** [comment]
It's for v5, don't worry I have plenty of time it's not that big of a deal I have plenty to work on in the meantime, thanks for the quick reply!
