### ISSUE TITLE
Texture with rounded corners without masks

### ISSUE THREAD

**Issue by AleXNoD** [pixijs/pixi.js#5650]
Hi,

Can I display a sprite that uses a texture with rounded corners without applying a mask?
I need it because masks have a very bad perfomance on mobile devices (4 fps vs 60 with no masks). But the design requires rounded corners on photos.

**Comment by ivanpopelyshev** [comment]
PixiJS v5 Graphics beginTextureFill.

**Comment by AleXNoD** [comment]
It looks good, thanks!
