### ISSUE TITLE
Setting resolution to 2 flips canvas V5

### ISSUE THREAD

**Issue by tmk1991** [pixijs/pixi.js#5654]
### Expected Behavior
Resolution to be 2 for retina devices
PIXI.settings.RESOLUTION = 2;

***Edit***
This is happening while exporting to base64 image.

### Current Behavior

Setting resolution to 2 flips and skews the canvas

- **`pixi.js` version**: 5
- **Browser & Version**: chrome latest
- **OS & Version**: mojave

**Comment by bigtimebuddy** [comment]
Example?

**Comment by ivanpopelyshev** [comment]
Did you put `resolution` param into renderer options?

**Comment by tmk1991** [comment]
I tried setting it with the PIXI Settings and as recommended: 
        const app = new PIXI.Application({
          height: 500,
          width: 500,
          resolution: 2,
          backgroundColor: 0x0c101b
        });

Same result. 

Sorry - should have put an example
![image](https://user-images.githubusercontent.com/20258296/57198652-2eca1b80-6f43-11e9-8493-8b362bca5dff.png)

**Comment by themoonrat** [comment]
I'm not seeing this on Windows, Linux, Android or iOS on any available browsers. Sounds like a graphic driver issue on your Mac? A mac is the one thing I don't have access to :/

**Comment by ivanpopelyshev** [comment]
That's super fun :) Need other mac guys to check it!

**Comment by bigtimebuddy** [comment]
I cannot reproduce this on chrome + mojave
https://pixiplayground.com/#/edit/guRZ8Aj2wDhiDWiLmZJ6L

**Comment by tmk1991** [comment]
Ah - 

Should have specified. The output image i'm generating from the pixi app is what is getting flipped.

https://pixiplayground.com/#/edit/393uM2pshcdJmPehosztH

**Comment by ivanpopelyshev** [comment]
OK, now we understand what's that. I will not fix any extract problems because there are too many and I'm going to make separate implementation for it this or next month.

Either wait for someone else to look at it, either use a possible workaround:

Copy that part to your app, figure out whats wrong and fix it: https://github.com/pixijs/pixi.js/blob/dev/packages/extract/src/Extract.js#L74

**Comment by themoonrat** [comment]
There have been issues raised in the past about Safari doing this
https://github.com/pixijs/pixi.js/issues/2951
https://github.com/pixijs/pixi.js/issues/2283

**Comment by tmk1991** [comment]
Works in 4.8.7 

Used this solution for angular 7+ 
https://github.com/pixijs/pixi.js/issues/4921#issuecomment-453943859

**Comment by themoonrat** [comment]
@tmk1991  Is this still an issue for the latest v5 pixi for you?
