### ISSUE TITLE
pointermove => pointerstop

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#5655]
It will be nice to have a native event .on `pointerstop `in plugins.interaction ?
I don't know if is a good idea or if pixi already have it ?
It's not really a problem, just a suggest feature.

in classic listener we can do this, it tricky.
```javascript
document.onmousemove = (function() {
    let onmousestop = function() {
            stopped = true;
        },
        thread;
    return function() {
        clearTimeout(thread);
        stopped = false;
        thread = setTimeout(onmousestop, 40); // setup time precision for stop
    };
})();
```

**Comment by themoonrat** [comment]
Since the current policy with Pixi is to try and stick closely to browser event behaviour, I think this is best handled via a plugin rather than natively within the core library itself

**Comment by djmisterjon** [comment]
well i found a little tricky way with this.
https://github.com/pixijs/pixi.js/blob/22f146c932d8e9e0ec952ca64b83dd57764d3ac6/packages/interaction/src/InteractionManager.js#L840

It little hack and dirty and not cleaner like a event register but it work fine for what i need.
