### ISSUE TITLE
Diagonal white line on a Texture

### ISSUE THREAD

**Issue by AleXNoD** [pixijs/pixi.js#5658]
Hi,

See example: https://app.alexnod.com/pixi_beginTextureFill_line.jpg

Why the diagonal line appears on the texture created with Graphics.beginTextureFill()?
I apply there a PIXI.Matrix with scale (1) and translate (0,0).
Is it Pixi or WebGL bug?

**Comment by AleXNoD** [comment]
I would not ask these questions if masks worked correctly on mobile devices. But FPS shows an extremely low value. Perhaps the reason is that MaskSystem.enableScissor does not work in PIXI 5? So all masks use stencil right?

**Comment by ivanpopelyshev** [comment]
We were too tired to return scissor masks to v5, you know ;) Did you turn on antialias in webgl renderer options? Try switch it off.

**Comment by AleXNoD** [comment]
Yep. There is no artifact lines without antialias. Nice temporatry resolve, thanks.
