### ISSUE TITLE
Video texture not updating

### ISSUE THREAD

**Issue by jmckible** [pixijs/pixi.js#5659]
I just upgraded to 5.0.1 and noticed some weird behavior with video textures. To sanity check, I loaded up the example from the documentation, and it seems to be suffering from the same problem:

https://pixijs.io/examples/#/sprite/video.js

I hear the audio, but do not see any video. Verified the same behavior in latest Chrome, Safari, and Firefox. On OS X 10.14.4.

**Comment by jmckible** [comment]
Toggling to 5.0.0 in the example does seem to work.

**Comment by djmisterjon** [comment]
well first it the resource path seem wrong  ! 
it should be `examples/examples/assets/video.mp4`

**Comment by themoonrat** [comment]
Oops! I'll sort that out

**Comment by bigtimebuddy** [comment]
Merged and released! Thanks for reporting @jmckible.
