### ISSUE TITLE
pixi@v5.0.0 

### ISSUE THREAD

**Issue by DawnSouther** [pixijs/pixi.js#5661]
advice:
When calling the method PIXI.Ticker.add, can I add an id field to the handler for tick events in order to remove this handler?

why i need it?
In this
![image](https://user-images.githubusercontent.com/22205542/57267796-e9792b80-70b3-11e9-8d1a-0c6c00aa79af.png)
user lambda Passing parameters generate a Anonymous function, and then  i want to remove this handler in this handler inside, its not remove this handler.

If you have a better way to remove the handler in this case, please let me know.

thx

**Comment by themoonrat** [comment]
If you want to add and remove functions from a ticker, then you'll want to save it to a variable and pass that through to add and remove

**Comment by DawnSouther** [comment]
![image](https://user-images.githubusercontent.com/22205542/57276742-125de880-70d5-11e9-8b16-fbb4c230f1bf.png)
great! It solved my problem.
thank you very much!
