### ISSUE TITLE
May I translate this project into Korean?

### ISSUE THREAD

**Issue by JunHyeok-K** [pixijs/pixi.js#5662]
Hi :) I am Jun Hyeok Kim, a university student in Kwangwoon University, Korea.
I am working on a project translating useful informations related to Learning Pixi.
I think this can help a lot of Koreans who are interested in Pixi.

So, may I translate these infos in to Korean?
If i could, plz tell me how i can share the translated results.
Thank you.

**Comment by ivanpopelyshev** [comment]
Korean project: Http://www.madworldmmo.com

Thats heavily modified pixi-v3. 

As for translation there are two problems: 

1. We are working on new set of examples and tutorials, so you can wait month or two and then translate better material

2. Existing materials are changing, and i dont know how properly maintain sync between two parallel texts.

Can you give me example of other projects of our size that have multi-lang examples? We can look how others do it and then decide.

I'll post more info for you later today.

**Comment by m00nr4bb1t** [comment]
+1

If Korean translation happens, I could help.
