### ISSUE TITLE
draw line v5.0.1

### ISSUE THREAD

**Issue by DrSnuggles** [pixijs/pixi.js#5663]
Hi,

have issue with v5.0.1 version., also happened in RCs but works without problems in v4.8.7
i draw a lot of lines, and remove all childs every frame.
after a short while out-of-memory in graphicsgeometry.js buildDrawCalls occurs.
tested in Chrome & FF

I tried to make a fiddle for you: 
https://jsfiddle.net/SnugglesDr/s92Lnmt0/
Or here in my PIXI branch: https://github.com/DrSnuggles/jsGoniometer/tree/PIXI/goniometer.js

**Comment by ivanpopelyshev** [comment]
Thanks for example, we'll look at it!

**Comment by JetLua** [comment]
`parent.removeChild` did not destroy the child nodes, you can try `child.destroy({children: true})`.
Of course, it doesn't explain why `v4` doesn't crash.

**Comment by DrSnuggles** [comment]
Thank you very much, destroying in this way prevents crashing.

**Comment by ivanpopelyshev** [comment]
The difference is in what leaks. PixiJS v4 doesnt track geometry objects and only uploaded buffers are leaked. v5 has `managedGeometries` field that has all active geometries and of course it eats up memory VERY fast.
