### ISSUE TITLE
Mesh-based classes crash if WebGL not present (pixi-legacy)

### ISSUE THREAD

**Issue by TheWyo** [pixijs/pixi.js#5664]
### Expected Behavior
Using autoDetectRenderer and not getting WebGL should fallback to canvas and use the canvas mesh renderers.

### Current Behavior
In a WebGL-disabled environment, creating a mesh-based object (e.g. SimplePlane, NineSlicePlane etc) will create a MeshMaterial, whose construction will eventually call getTestContext in core shader utils, which fails to get a valid WebGL context, and throws.

### Possible Solution
I've tested moving calls to getTestContext into try/catch blocks (as both places this method is called are followed by null-checks anyway), and this seems to fix the issue, but not sure if it's better to do this, or just make getTestContext not throw. Happy to make a PR for this if wanted.

### Steps to Reproduce
https://jsfiddle.net/3zshfLmy/
(Swap pixi-legacy for latest v4 and the plane initialisation lines to compare with v4 behaviour).
Firefox - about:config - webgl.disabled = true (or other webgl-disabling method)
Not reproducible by merely doing forceCanvas true, as WebGL context creation is still available.

### Environment

- **`pixi-legacy.js` version**: 5.0.1
- **Browser & Version**: Firefox Developer Edition 67.0b17
- **OS & Version**: Windows 7
- **Running Example**: https://jsfiddle.net/3zshfLmy/

**Comment by themoonrat** [comment]
@TheWyo  Could you test if this is still an issue in the latest version of PixiJS please?

**Comment by bigtimebuddy** [comment]
Doesn't show up in **dev** https://jsfiddle.net/bigtimebuddy/sqprxfo0/

**Comment by TheWyo** [comment]
Yep, still reproduces with @bigtimebuddy's jsfiddle.

**Comment by bigtimebuddy** [comment]
What still reproduces? Can you be specific about what you're seeing? 

With [this fiddle](https://jsfiddle.net/bigtimebuddy/sqprxfo0/), I set to `forceCanvas` to `true` and see this on Chrome 75 and Firefox 68:
<img width="413" alt="Screen Shot 2019-07-28 at 2 33 03 PM" src="https://user-images.githubusercontent.com/864393/62013240-a07dc400-b144-11e9-8c43-196f02b44b0c.png">

Cannot reproduce your issue.

**Comment by TheWyo** [comment]
forceCanvas doesn't reproduce it as you're still running in an environment where WebGL exists. You have to fully disable WebGL or do it on a device that doesn't support WebGL (how I found it) so the attempted context creation fails. Firefox's `webgl.disabled` config will do this.

If you change that FF config and reload you'll get this sequence in the console:
```
PixiJS 5.1.0 - Canvas - http://www.pixijs.com/
Error: This browser does not support WebGL. Try using the canvas renderer
```

Solution is in the original issue, just not sure which approach you'd prefer depending on whether or not you want getTestContext to throw still.

**Comment by bigtimebuddy** [comment]
Okay, that makes more sense. I was able to reproduce this by running:

```
 /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome -disable-webgl
```

**Comment by bigtimebuddy** [comment]
Fixed: https://jsfiddle.net/bigtimebuddy/bLyd497t/
