### ISSUE TITLE
chrome developer tools extreme slow

### ISSUE THREAD

**Issue by switers-wang** [pixijs/pixi.js#5668]
my project use pixi . but it is extremely slow when i open chrome developer tools for debug

### Environment

- **`pixi.js` version**: 
                 "pixi-center": "^1.0.11",
                 "pixi-spine": "^1.5.19",
- **Browser & Version**: _e.g. Chrome  74.0.3729.131
- **OS & Version**: _mac_os 10.12_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
You probably spawn too many sprites, or you forgot to remove conditional breakpoints. Please lrovide more info.

**Comment by themoonrat** [comment]
Closing due to lack of info. Please open a new issue if you still require help on this :)
