### ISSUE TITLE
interaction fast mouse identification [suggest]

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#5669]
On my side I do this to manage the identifications click of my mouse and possibly an xbox controller.
```javascript
var interaction = $app.renderer.plugins.interaction;
    Object.defineProperty(interaction.eventData, 'isLeft'  , { get: function() { return this.data.button === 0 } }); // <==
    Object.defineProperty(interaction.eventData, 'isRight' , { get: function() { return this.data.button === 2 } }); // ==>
    Object.defineProperty(interaction.eventData, 'isMiddle', { get: function() { return this.data.button === 1 } }); // =|=
```
It just a idea, but i think the `InteractionEvent ` should have some native method or getter to fast check what kind of click is used ?

My laziness made me think it would be pretty good.
this allow shortcut and less code.. it not impact performance.

**example:**
Instead to scope variable like this for each listener.
```javascript
    pointerup_pinSlot(e) {
        const ee = e.currentTarget;
        const isLeft   = e.data.button === 0;
        const isRight  = e.data.button === 2;
        const isMiddle = e.data.button === 1;
        if (isLeft) {
            //do stuff
        }else
        if (isRight) {
            
        }
    };
```

use getter from the event
```javascript
    pointerup_pinSlot(e) {
        const ee = e.currentTarget;
        if (e.isLeft) {
            //do stuff
        }else
        if (e.isRight) {
            
        }
    };
```
good or bad idea ?

**Comment by themoonrat** [comment]
I personally feel that we shouldn't bloat the api where it isn't required. The entire web world is used to distinguishing between which button is pressed via the `button` property. 

I also feel it's something that if you wanted, that it might be best served as a function on the event callback rather than adding properties into the event data itself.

```
const buttonName = getButtonName( e.data.button );
if ( buttonName === 'left' ) {
 // blah blah
}
```
