### ISSUE TITLE
Rectangle corner has an issue

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#5670]
One corner of the red rectangle at https://pixijs.io/examples/#/graphics/dynamic.js has an issue:

<img width="1053" alt="screenshot" src="https://user-images.githubusercontent.com/80411/57514381-a8ca1e00-7310-11e9-8b97-ce1a3b6d3f78.png">

eg in Chrome, Firefox, Safari
eg on MacOS 10.14

**Comment by themoonrat** [comment]
Yep I see that too on Chrome Android

**Comment by ivanpopelyshev** [comment]
Its legit, there's no closePath() in the demo ;)

**Comment by tobireif** [comment]
https://github.com/pixijs/examples/pull/70

**Comment by tobireif** [comment]
In the block "draw a second shape" there also should be a closePath(): ```graphics.closePath()```. Perhaps every shape in every Graphics example should get a closePath()?

**Comment by tobireif** [comment]
Added two more, should be sufficient for examples/js/graphics/dynamic.js .
pull-request: https://github.com/tobireif/examples/pull/1

**Comment by ivanpopelyshev** [comment]
Only ones with a stroke

**Comment by tobireif** [comment]
Pull-request for the Simple Graphics demo: https://github.com/tobireif/examples/pull/2 .
This (plus the earlier PRs) should be sufficient (regarding ```closePath()```) for all the Graphics demos.
Thanks @ivanpopelyshev , @themoonrat , @GoodBoyDigital , @bigtimebuddy , and the rest of the Pixi crew for PixiJS!

**Comment by themoonrat** [comment]
Examples have been fixed; closing!
