### ISSUE TITLE
DisplayObjects with negative positioning messes up parent container's bounding box

### ISSUE THREAD

**Issue by NordlingDev** [pixijs/pixi.js#5672]
I am creating a simple scene and when a DisplayObject's position is set to a negative value, that object appears outside of container's bounding box but its total size (height in this case) is still added to container's overall size. This makes it very difficult to center a container in viewport because the negative positioned objects aren't taken into account even though their sizes still are.

Check red rectangle in images below:

### Expected Behavior
![image](https://user-images.githubusercontent.com/2098838/57571786-8fa99600-7412-11e9-85f2-245e9ce30691.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/2098838/57571588-67b93300-7410-11e9-87e3-9b0207862e31.png)

### Possible Solution
I could not find a solution for this.

### Steps to Reproduce
Add a few DisplayObjects into a shared container and set one or more of them to a negative position (X or Y doesn't matter). Then check the container's bounding rectangle with own tools or PixiJS DevTools for Chrome.

### Environment

- **`pixi.js` version**: 5.0.2
- **Browser & Version**: Appears on all browsers (primarily using Chrome Chrome 74)
- **OS & Version**: _e.g. Appears on every OS (using MacOS 10.14.4 now though)
- **Running Example**: https://codesandbox.io/embed/o49w5419ly

**Comment by ivanpopelyshev** [comment]
This thing is being reported with "cannot give you URL" for N-th time.

**Comment by NordlingDev** [comment]
@ivanpopelyshev - Alright, had no idea that was a common occurrence. I’ll do my best to hand you a running example within a couple hours. Sorry for the inconvenience.

**Comment by ivanpopelyshev** [comment]
> Alright, had no idea that was a common occurrence. 

My sarcasm is towards the issue, no worries ;)

There are multiple lazy calculations, that's why its difficult. Also I believe we fixed a couple of issues there, just not all. I remember one time that I had issue like that in giant open-source project and we played ping-pong with fiddles/patches 14 times in one week.

**Comment by ivanpopelyshev** [comment]
```js
border.drawRect(container.x, container.y, container.width, container.height);
```

that's not how you get a border.

```js
let rect = container.getBounds();
border.drawRect(rect.x, rect.y, rect.width, rect.height);
```

container.x is not a calculated property, its not about border, its about local cordinate system.

**Comment by NordlingDev** [comment]
@ivanpopelyshev - It's not about the border. It was used as a tool to visualize the issue. If you use PixiJS DevTools for Chrome, it will show you the exact same thing. Or is that tool using wrong calculations as well?

Anyhow, using `getLocalBounds()` is a working solution. I'll stick to that, thank you!

**Comment by bigtimebuddy** [comment]
Maybe file an issue with pixijs dev tools? Closing issue as it seems solved.
