### ISSUE TITLE
How to Set Click Events Without Executing Click Events in the Transparent Zone of Click png Picture

### ISSUE THREAD

**Issue by ecma8** [pixijs/pixi.js#5676]
How to Set Click Events Without Executing Click Events in the Transparent Zone of Click png Picture

![image](https://user-images.githubusercontent.com/13748493/57687240-a992e500-766d-11e9-9a2a-2eeda886b2cf.png)

**Comment by themoonrat** [comment]
The quickest and easier thing to do is set a custom hitArea on the displayObject
```
displayObject.hitArea = new PIXI.Circle( 0, 0, 200 ); // x, y, radius
```

**Comment by ecma8** [comment]
How to set up irregular transparent pictures?

**Comment by ecma8** [comment]
> 最快捷方便的事情是在displayObject上设置自定义hitArea
> 
> ```
> displayObject.hitArea = new PIXI.Circle( 0, 0, 200 ); // x, y, radius
> ```
How to set up irregular transparent pictures?

**Comment by themoonrat** [comment]
`displayObject.hitArea = new PIXI.Polygon( [0,0,50,100,200,50] );` // array of x y co-ordinates

**Comment by ecma8** [comment]
What about the figure? 
![fbe68f2111bd49f1fe83a3467232feb3_pixijs-v5-logo-1](https://user-images.githubusercontent.com/13748493/57688686-aea56380-7670-11e9-9434-76f670406269.png)

**Comment by themoonrat** [comment]
You'll need to extract the pixels and check the point position to the pixel you are examining. This is slow, but is the only option, I believe
http://www.html5gamedevs.com/topic/41939-sprites-containspoint-method-check-alpha/

**Comment by rokadi** [comment]
Nice

**Comment by bigtimebuddy** [comment]
Seems answered. Closing.
