### ISSUE TITLE
Animation speed defined in json?

### ISSUE THREAD

**Issue by spidamoo** [pixijs/pixi.js#5678]
As far as I can tell from reading docs and sources there is no way to define animation speeds when loading spritesheet from a json file. It seems to me that having such a feature would be really convenient and useful. It also seems like a very easy thing to implement and I'm willing to do it and submit a MR unless there is a reason not to that I am failing to see.

**Comment by themoonrat** [comment]
You could always read the json, then create the correct array of objects to pass to PIXI.AnimatedSprite that allows both a 'texture' and a 'time' for how long to show each texture. 

Any PRs are always welcome!
