### ISSUE TITLE
'loader not exported from pixi.js' compile error with react.js using create-react-app

### ISSUE THREAD

**Issue by Grallator** [pixijs/pixi.js#5679]
### Expected Behavior
Used

import * as PIXI from "pixi.js";

to import Pixi in a react.js project set up with create react. When using the loader I expect sprite to load and trigger the callback.

### Current Behavior
When using the loader (testing using npm start) I get the following compile error

./src/canv.js
Attempted import error: 'loader' is not exported from 'pixi.js' (imported as 'PIXI').

### Environment

- **`pixi.js` version**: 5.0.2
- **`React` version**: 16.8.6
- **`project set up with` create-react-app**

**Comment by ivanpopelyshev** [comment]
`PIXI.loader` is deprecated, Use `app.loader` or `let loader = new PIXI.Loader`

**Comment by Grallator** [comment]
Perfect - thanks!
