### ISSUE TITLE
Projection matrix issue

### ISSUE THREAD

**Issue by pglagol** [pixijs/pixi.js#5680]
Hello guys,

Trying to apply transform matrix to projection.

```
let mtx = new Matrix();
mtx.rotate(Math.PI);
pixiApp.renderer.render(stage, undefined, undefined, /*transform:*/ mtx);
```

### Expected Behavior
Game view will be rotated to Math.PI radians statically.

### Current Behavior
Rotation is different every frame.

### Possible Solution
Add to projectionSystem.js this lines at 104:

```
pm.c = 0;
pm.d = 1;
```

### Environment

- **`pixi.js` version**: 5.0.1

**Comment by ivanpopelyshev** [comment]
That `transform` param in renderer is transitions-only. 

Workaround: rotate the stage, or css rotate canvas. In case of css rotation watch out for interaction issues, you have to modify `mapPositionToPoint` or something like that in `renderer.plugins.interaction`, please look up our wiki , gotchas page.

**Comment by ivanpopelyshev** [comment]
I wonder why do you need that. Please explain your case, it sounds interesting :) Maybe I can find suitable solution or fix something in PixiJS. Right now I dont know whether its your mistake or what. For example, rotate by PI will show all NEGATIVE space, why do you need that?

**Comment by pglagol** [comment]
I'm trying to implement a fast camera. As I know, fastest way to do this working with a projection matrix.
My render function looks like this (stage layer with camera and UI):

`
this.pixiApp.renderer.render(this.stage, undefined, undefined, this.cameraMatrix);
this.pixiApp.renderer.render(this.uiRoot, undefined, false, undefined, true);
`

It's works perfect with camera moving and zoom, but rotation and skew is accumulated inside ProjectionSystem.projectionMatrix. 

https://github.com/pixijs/pixi.js/blob/1b996b2b1f543781b698ad6e7bc362fcd5a74ce7/packages/core/src/projection/ProjectionSystem.js#L103

This line was previously a matrix reset. If you remove the comment, my camera works perfectly with rotation. But fastest way is just reset two fields.
```
pm.b = 0;
pm.c = 0;
```
Because the others are assigned below.

I hope now clearer :)
Thanks for the help Ivan

**Comment by ivanpopelyshev** [comment]
It can work, but I predict problems with masks and filters calculation. I implemented fast camera (2d and 3d) in my games and pixi forks several times, and so far i dont see a general way to do it. Its still requires too bigger changes in vanilla pixi. I hope to implement it next year, maybe :)
