### ISSUE TITLE
Question: Layers

### ISSUE THREAD

**Issue by wpitallo** [pixijs/pixi.js#5681]
Hi, Just wanted to find out if there are any plans to support layers in PIXI version 5?

**Comment by Cristy94** [comment]
You can have different Containers and add your sprites to the corresponding container.

http://pixijs.download/dev/docs/PIXI.Container.html

```
const layer1 = new PIXI.Container();
const layer2 = new PIXI.Container();

layer1.addChild(spriteBg);
layer2.addChild(spriteHero);
```

Or what do you mean when you say layers?

**Comment by bigtimebuddy** [comment]
The pixi-layers plugin hasn’t been updated yet to v5, but we are working on it.

**Comment by wpitallo** [comment]
Yes, I was referring to the pixi-layers plug-in. This is great news, thx very much :)

**Comment by ivanpopelyshev** [comment]
@wpitallo Done! Please read the migration doc: https://github.com/pixijs/pixi-layers/#migration-from-v4
