### ISSUE TITLE
Transparent .webm video does not play on chromium and opera

### ISSUE THREAD

**Issue by rohtie** [pixijs/pixi.js#5683]
### Expected Behavior
Expected video to play when loaded.

### Current Behavior
Transparent .webm video does not play in pixi when using chromium and opera. 
Firefox works fine.

Video starts playing in chromium and opera if you manually type `video.texture.baseTexture.source.play()` into the console.

Video plays fine in opera and chromium when viewed directly.

This error comes up in the console: `Uncaught (in promise) DOMException` on this line in code: https://github.com/pixijs/pixi.js/blob/24459ad0166e712347a29ba67785277749ef66bf/packages/core/src/textures/resources/VideoResource.js#L260

Maybe pixi thinks the video has loaded before it actually has loaded? 

The .webm video is encoded with vp9 codec using ffmpeg.

### Environment

- **`pixi.js` version**: v 5.0.2
- **Browser & Version**: 
Chromium: Version 74.0.3729.157
Opera: Version:60.0.3255.83

- **OS & Version**:  Arch linux: 5.1.2-arch1-1-ARCH
- **Running Example**:
https://thor-merlin.no/media/pixi-bug.html
https://thor-merlin.no/media/video.webm

**Comment by themoonrat** [comment]
I'm wondering if what you're seeing is the video not autoplaying due to not having had a user interaction. Videos work the same way as sound now :/ 
An example of starting with an interaction: https://pixijs.io/examples/#/sprite/video.js

**Comment by rohtie** [comment]
Hm... I don't get what it could be.

When I edit the pixijs example with the live-editor to this:

```
var app = new PIXI.Application();
document.body.appendChild(app.view);

var videoSprite = PIXI.Sprite.from('examples/assets/video.mp4');

videoSprite.width = app.screen.width;
videoSprite.height = app.screen.height;

app.stage.addChild(videoSprite);
```

Then it works in chromium without any user interaction. 

But I tried doing the equivalent on my own page, and it doesn't work. Not even with the same video from the example:
https://thor-merlin.no/media/pixi-bug-2.html

**Comment by rohtie** [comment]
I tried opening that page in firefox now and got the warning `Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted.` so it is probably correct that it needs some kind of interaction. I'll try adding an interaction button as the example you sent and see if that works.

**Comment by rohtie** [comment]
Yep, that works!

It is kind of annoying that we need interaction in order to autoplay video, but I can also see why browsers would implement it like this to protect the users.

The pixi example edit I did probably only worked because pixi interpreted the reload button as an interaction to play the video.
