### ISSUE TITLE
JSDoc errors in Sprite constructor results in faulty Typescript definitions

### ISSUE THREAD

**Issue by stagr** [pixijs/pixi.js#5687]
The texture parameter in the Sprite constructor should be optional in the JSDoc. 

### Current Behavior

```
    /**
     * @param {PIXI.Texture} texture - The texture for this sprite.
     */
    constructor(texture)
    {
```

generates:

```
     * @class
     * @extends PIXI.Container
     * @memberof PIXI
     */
    class Sprite extends PIXI.Container {
        constructor(texture: PIXI.Texture);
```

### Possible Solution

```
    /**
     * @param {PIXI.Texture} [texture] - The texture for this sprite.
     */
    constructor(texture)
    {
```

generates:

```
     * @class
     * @extends PIXI.Container
     * @memberof PIXI
     */
    class Sprite extends PIXI.Container {
        constructor(texture?: PIXI.Texture);
```

### Steps to Reproduce

Setup with typescript and try to create a new Sprite without texture:

`const sprite = new Sprite();`

### Environment

- **`pixi.js` version**: 5.0.2
- **Browser & Version**: All
- **OS & Version**: All
- **Running Example**: None

**Comment by bigtimebuddy** [comment]
Thanks for reporting :+1:
