### ISSUE TITLE
"Tab" button hungs pixijs on mobile

### ISSUE THREAD

**Issue by selirion04** [pixijs/pixi.js#5690]
Tab button press makes application hung.

Easiest way to reproduce:
1. Open https://pixijs.io/examples/#/interaction/click.js on PC Chrome
2. Enable mobile emulation in dev tools
3. Press tab on keyboard
4. Application hung, because AccesibilityManager div covers the screen and never removed

Tab button exists on iPad Pro default soft keyboard, maybe on some custom soft keyboards for android and device-like keyboards So if your application have inputs it makes problems.
Also it reproduced somehow with "return/done" button on ios keyboard but I don't have stable steps to reproduce.

**Comment by themoonrat** [comment]
Can confirm this happens with v4 too. 
It's not that the application has hung or crashed, just that the div overlay stops any interaction.

If I change the overlay to include `pointer-events: none` then things start working again, so wonder if that's the valid solution here? I don't see why we need the accessibility layer to block input

**Comment by selirion04** [comment]
> If I change the overlay to include `pointer-events: none` then things start working again, so wonder if that's the valid solution here? I don't see why we need the accessibility layer to block input

I've just use this workaround:
if (AppInfo.mobile) //my own mobile indicator
   this._renderer.plugins.accessibility.activate = () => {};

**Comment by abhinavsagar** [comment]
Could i work on this ?

**Comment by themoonrat** [comment]
@selirion04 Is this still an issue? I've tried to replicate and I never get any 'freezing' like you describe.

**Comment by selirion04** [comment]
> @selirion04 Is this still an issue? I've tried to replicate and I never get any 'freezing' like you describe.

Yes, still here. Still reproduced as described in 1st comment (key moment is mobile emulation and pixi canvas focused when tab pressed).  App not freezed, just interaction unavailable because some interaction manager div is over the app.
Chrome 75.0.3770.100

**Comment by themoonrat** [comment]
Bump.
`pointer-events: none` could still be the solution

**Comment by themoonrat** [comment]
For those wondering; this PR for v5 lets you change the pointer events value - depending on your usage, you may want to change it to 'none'
https://github.com/pixijs/pixi.js/pull/6124
