### ISSUE TITLE
beginHole(v5) or addHole(v4) make pointerdown doesn't work

### ISSUE THREAD

**Issue by MisakiHCL** [pixijs/pixi.js#5696]
when i use hole, i can't pointerdown in hole area, even if i fill it

**Comment by ivanpopelyshev** [comment]
interaction doesn't work in holes, wow :) Can you help us to make an example on https://www.pixiplayground.com/ ?

**Comment by MisakiHCL** [comment]
thank you, it doesn't work on red area,but i can use child to fix it

https://www.pixiplayground.com/#/edit/sLaKxVH7U7zFe2YO9X8l9

**Comment by bigtimebuddy** [comment]
Yeah, that seems like a bug. If you click on a shape and it hits a hole, we ignore the click for that shape. I don't believe interaction checks for other shapes after it hits a hole. Maybe @themoonrat can confirm.

**Comment by themoonrat** [comment]
Update the example with a second one. Basically, once the whole is 'out' of the graphics, you lose all interactivity any further inside you go. But if the hole still takes you to an inner part of the graphic, then it correctly all stays interactive. 

Feels like a bug to me .
