### ISSUE TITLE
Need help with transformation

### ISSUE THREAD

**Issue by NoleDjok** [pixijs/pixi.js#5698]
![example](https://user-images.githubusercontent.com/15738295/58001638-bb98db80-7ae4-11e9-8b59-2844529ef3b1.png)
Hello!
I need your help, guys. How can I transform sprite or container  like it's on the picture?
Is it possible?
Thank you

**Comment by ivanpopelyshev** [comment]
Need pixi-v4 and pixi-projection plugin.

**Comment by NoleDjok** [comment]
oh, it`s bad, because I use pixi v5(
pixi-projection don`t support pixi v5, am i right?
What can i do?

**Comment by ivanpopelyshev** [comment]
You can wait with several others :) I'm already overdue with updating that plugin. Hoe bad do you need it?

**Comment by NoleDjok** [comment]
We have a project with a lot of clients and we have to add a new feature to it.
For this we need to have a opportunity of transformation like on the picture.
We would be happy this plugin will be updated rather.
When  will you plan to update  pixi-projection?

**Comment by ivanpopelyshev** [comment]
I'm a chaotic person, when everything is on fire, I dont have plans :) I can do it this evening if you help me test it, do you have telegram? Mine is t.me/hackerham

**Comment by themoonrat** [comment]
It now works with v5, so closing :)

**Comment by ivanpopelyshev** [comment]
@NoleDjok https://github.com/pixijs/pixi-projection works with latest dev, pixijs.download/dev/pixi.js . You can see the demos here: https://pixijs.io/examples/#/plugin-projection/quad-homo.js https://pixijs.io/examples/#/plugin-projection/cards.js
