### ISSUE TITLE
[Feature Request]Support OES_element_index_uint

### ISSUE THREAD

**Issue by Norgerman** [pixijs/pixi.js#5699]
any plan to support gl.UNSIGNED_INT in gl.drawElements?

https://github.com/pixijs/pixi.js/blob/ba03f57001cd8bae3ae3644911cd513c68184e7c/packages/core/src/geometry/GeometrySystem.js#L594-L606

see https://developer.mozilla.org/en-US/docs/Web/API/OES_element_index_uint

**Comment by ivanpopelyshev** [comment]
Yep.

**Comment by abhinavsagar** [comment]
@ivanpopelyshev Could I work on this ?

**Comment by ivanpopelyshev** [comment]
@abhinavsagar go for it! I'm currently busy with multitexture shader plugins.

**Comment by liufangqiangu** [comment]
404 not fuond
