### ISSUE TITLE
WebGL context restored incorrectly (pixi v5)

### ISSUE THREAD

**Issue by YuryKuvetski** [pixijs/pixi.js#5700]
Everything works fine for pixi v4, but in v5 (WebGL 2) application restored incorrectly

### Expected Behavior
For both versions of pixi, application should be restored correctly.

### Current Behavior
If you choose **v5** pixi version with webgl2, application is not restored.
If you choose **v4** pixi version with webgl, application restored fine.

### Steps to Reproduce
1. Open https://pixijs.io/examples/#/demos-basic/container.js on PC Chrome
2. Choose **v5** pixi version
3. Open chrome dev tools console with iframe context
4. Write next command to lose webgl context `document.querySelector('canvas').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext()`
5. Wait for a few sec
6. Write next command to restore webgl context `document.querySelector('canvas').getContext('webgl2').getExtension('WEBGL_lose_context').restoreContext()`
### Environment

- **`pixi.js` version**: _5.0.3_
- **Browser & Version**: _Chrome 74.0.3729.157_
- **OS & Version**: _MacOS Mojave 10.14.4_

**Comment by ivanpopelyshev** [comment]
Its a known issue. I've fixed geometries but not texures and shaders :) How critical is that for you, is it something that you can  integrate into app a month after now or do you need it this week?

**Comment by YuryKuvetski** [comment]
Good. I think it's ok for us to wait a month.

**Comment by JetLua** [comment]
@ivanpopelyshev Are you already doing this? If not, I can add a PR.
