### ISSUE TITLE
creating a ListView (component) for Pixi.JS

### ISSUE THREAD

**Issue by inglesuniversal** [pixijs/pixi.js#5703]
Hi, I am enjoying the updates and new features of Pixi.JS version 5.x.x

I would like to ask you if there is a way or plugin, to display a scrollable ListView, which in my case can hold, a table element displaying multiple rows of tiny album covers and song title information.

Is that possible?

Best regards

**Comment by themoonrat** [comment]
Not sure of it's compatibility with v5, but https://github.com/pixijs/pixi-ui is the most advanced plugin for that kinda thing
