### ISSUE TITLE
Bug with Graphics pixi.js@5.0.3

### ISSUE THREAD

**Issue by guillaumefer** [pixijs/pixi.js#5707]
### Expected Behavior
the render should be a square 400 x 400 px.
### Current Behavior
there seems to be a limit with Graphics on this v5 (not in v4)
### Steps to Reproduce
https://codepen.io/ferguillaume/pen/pmdKVw
### Environment

- **`pixi.js` version**: _e.g. 5.0.3_
- **Browser & Version**: _e.g. Chrome  69.0.3497.100_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: https://codepen.io/ferguillaume/pen/pmdKVw

**Comment by themoonrat** [comment]
A continuation of https://github.com/pixijs/pixi.js/issues/5614 ?

**Comment by guillaumefer** [comment]
> A continuation of #5614 ?
i don't think so

I made another example : https://codepen.io/ferguillaume/pen/PvEPYN
It's not possible to draw more than 16384 rectangles

**Comment by themoonrat** [comment]
Ooops, sorry, I commented on the wrong graphics issue!

**Comment by JetLua** [comment]
It may have something to do with [GraphicsGeometry.js](https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/GraphicsGeometry.js), but I don't know the details.

**Comment by ivanpopelyshev** [comment]
I don't suggest to do that because every drawRect() spawns several objects. Why do you want that many rects?

**Comment by ivanpopelyshev** [comment]
We need either #5699 either to limit number of vertices in a static drawcall.

**Comment by JetLua** [comment]
@ivanpopelyshev Many `PIXI.Graphics` instances actually faster?

[Many instances](https://www.pixiplayground.com/#/edit/NbK9K0xQZTVt66Cp0TDJy)
[Many shapes](https://www.pixiplayground.com/#/edit/dgCrKVPRVjKnVuZSkqocD)

**Comment by bigtimebuddy** [comment]
@JetLua The most performant solution is to share GraphicsGeometry between instance. This way you only have to tesselate the shapes once.

https://www.pixiplayground.com/#/edit/IufITuJ8N2eLEWSmhRHJH

**Comment by guillaumefer** [comment]
> Every drawRect() spawns several objects. Its fine if you do it one time, but if you re-fill it periodically it can clog GC. Why do you want that many rects?

I need many rects to draw a perlin noise like this : http://josephg.github.io/noisejs/demo3d.html
What is the best way / practice for fill an entire stage pixel by pixel (like formely BitmapData in AS3) ?


> @JetLua The most performant solution is to share GraphicsGeometry between instance. This way you only have to tesselate the shapes once.
> 
> https://www.pixiplayground.com/#/edit/IufITuJ8N2eLEWSmhRHJH

Sharing GraphicsGeometry between instance works, but it seems impossible to change color for each pixel : https://www.pixiplayground.com/#/edit/89eIFOIIp9H6CxeDi3U~g

**Comment by bigtimebuddy** [comment]
You can apply a tint @guillaumefer per Graphics instance:
https://www.pixiplayground.com/#/edit/TZ6zfhrusXQq155y54teB

**Comment by ivanpopelyshev** [comment]
> What is the best way / practice for fill an entire stage pixel by pixel (like formely BitmapData in AS3) ?
canvas2d setImageData, then "new BaseTexture(canvas)" or "BaseTexture.from(canvas)" depends on version. In pixi-v5 you can use BufferResource.

**Comment by camilacanhete** [comment]
Possibly related:

Wrong size of PIXI.Graphics() using PIXI.Sprite() as container. See more: https://codepen.io/anon/pen/jjwero

Explaining:
Parent (invisible sprite) is 100x100
Child (yellow square) should be 50x50, but the rectangle appears bigger than it should
