### ISSUE TITLE
Can't add a sprite from a big size image

### ISSUE THREAD

**Issue by luoge** [pixijs/pixi.js#5708]
Code:
`var bg = PIXI.Sprite.from('***');`
`bg.width = 5789;`

This image has a big size, then display a black screen. 

- **`pixi.js` version**:  5.0.3_
- **Browser & Version**:  Mobile Chrome 74_
- **OS & Version**:  Android And iOS_

**Comment by ivanpopelyshev** [comment]
Webgl limit is 4096 on most of devices

**Comment by luoge** [comment]
Thanks a lot!
