### ISSUE TITLE
Using Graphics native lineStyle does not close shapes

### ISSUE THREAD

**Issue by stagr** [pixijs/pixi.js#5711]
### Expected Behavior
The below code, with the lineStyle parameter "native" set to true, should paint a rectangle with a 1 pixel wide red border.
```
    var graphics2 = new PIXI.Graphics();
    graphics2.lineStyle(1, 0xFF0000, 1, 0.5, true);
    graphics2.drawRect(10, 120, 100, 100);
```
### Current Behavior
The rectangle is painted with only three sides, the border of the left side is not visible at all.

### Possible Solution
No idea.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/yo2dXuKUxzhfGphLmRC0k

### Environment

- **`pixi.js` version**: 5.03
- **Browser & Version**: Chrome 74.0.3729.157, Microsoft Edge 42.17134.1.0, Firefox 66.0.5 (64-bit)
- **OS & Version**: Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/yo2dXuKUxzhfGphLmRC0k

**Comment by stagr** [comment]
Pinging this to see if anyone has any news on this one?

**Comment by bigtimebuddy** [comment]
Yup, this definitely looks like a bug.

**Comment by JetLua** [comment]
Add notes: If you set the color of `lineStyle` to `0xffffff`, `Graphics` will not be displayed.

https://www.pixiplayground.com/#/edit/eyv91KYjD~Gz~P0N95cC_

**Comment by bigtimebuddy** [comment]
That's more serious. 

Here's the same bug but showing on **dev** instead of the latest release. Will be helpful to verify.

https://www.pixiplayground.com/#/edit/EWjPwKmpr9LlGPYHugusU

cc @ivanpopelyshev

**Comment by stagr** [comment]
This is now working in 5.1.0. Closing the issue. Thanks a lot!
