### ISSUE TITLE
Impossible to load a Video for an URL without a video file extension (mp4 etc.)

### ISSUE THREAD

**Issue by miriti** [pixijs/pixi.js#5712]
I'm trying to load a video from URL to use as a texture but the loader is failing to recognize the resource as a video, probably because the URL doesn't have an appropriate extension for a video file. But when I try to specify loadType as `PIXI.LoaderResource.LOAD_TYPE.VIDEO` it completely hands the loader and `load` callback never fires. Also none of event handlers like onError or onProgress ever fire.

Other URLs with appropriate extensions work fine.

URL that doesn't work: https://media.gettyimages.com/videos/taking-a-slice-of-pizza-from-the-plate-video-id606042756?suffix=.mp4
URL that works: https://thumbs.gfycat.com/ForthrightOrnateArgali-mobile.mp4

Without specifying `loadType` option resource loads but with `loadType = 1` (`XHR`) and `Texture.from` doesn't recognize it as a video. Also `extension` in the resource is set to `com/videos/taking-a-slice-of-pizza-from-the-plate-video-id606042756`

### Expected Behavior
Video is loaded and displayed on the stage or `onError` handler is fired.

### Current Behavior
After adding a resource to queue with `add` method nothing happens. Calling `load` has no effect.

### Steps to Reproduce
I'm attaching a running example. Line 16 contains URL that doesnt work, line 17 contains one that works in a comment.

### Environment

- **`pixi.js` version**: _5.0.3_
- **Browser & Version**: _Google Chrome 74.0.3729.157 (Official Build) (64-bit)_
- **OS & Version**: _Arch Linux x86_64 Kernel: 5.1.2-arch1-1-ARCH_
- **Running Example**: _http://michael-miriti.com/loader-problem/_

**Comment by mortonjohn** [comment]
is possilbe to watch someone without the either knowing it
