### ISSUE TITLE
[RFC] .basis Texture Format

### ISSUE THREAD

**Issue by Teoxoy** [pixijs/pixi.js#5713]
What do you guys think about the newly announced Basis Universal Texture Format?
It seems like it would solve the problem with GPU Texture Size vs Disk Texture Size.
Should this new format be supported and implemented in PIXI or trough a plugin?

Links:
https://github.com/BinomialLLC/basis_universal
https://opensource.googleblog.com/2019/05/google-and-binomial-partner-to-open.html

**Comment by ivanpopelyshev** [comment]
We were waiting for it for a long time. Finally. @GoodBoyDigital is looking into it.

**Comment by englercj** [comment]
Basis is pretty cool, glad they are open sourcing it.

> It seems like it would solve the problem with GPU Texture Size vs Disk Texture Size.

Basis files are often smaller than a PNG equivalent (using default setting, without mips), but that isn't the best feature IMO.

The biggest benefit of basis is the ability to transcode it to whatever GPU compression is supported on the machine you are on. That way you don't have to build your texture into 5 different formats for each different platform it might land on, you just build it to basis and transcode it to the platform specific format the GPU on your host machine supports.

**Comment by Teoxoy** [comment]
Yeah, the benefit of not having to serve multiple texture formats for different platforms is also a great advantage.

**Comment by Teoxoy** [comment]
`@stale` Don't close.

**Comment by GoodBoyDigital** [comment]
I believe @eXponenta has already done this 👍 
Where did this code land in the end?

**Comment by bigtimebuddy** [comment]
Pretty sure it’s here: 

https://github.com/pixijs/pixi-compressed-textures

Not sure if there’s a release but @ivanpopelyshev  should be able to answer that.

Closing as this seems to be addressed. Further questions or issues about BASIS should be left on the compressed textures repo.

**Comment by eXponenta** [comment]
https://pixijs.io/examples/#/plugin-compressed-textures/basis.js
