### ISSUE TITLE
Adjust my text to the size of my screen

### ISSUE THREAD

**Issue by AlainBarrios** [pixijs/pixi.js#5721]
Any way to get my texture does not distort and fits the size of the screen?

This is the code
https://codepen.io/AlainBarrios/pen/rgYNRN?editors=0010

**Comment by themoonrat** [comment]
Hi @AlainBarrios  - are you still having an issue? I can't quite work out from that codepen what it is that's wrong?

**Comment by AlainBarrios** [comment]
> Hi @AlainBarrios - are you still having an issue? I can't quite work out from that codepen what it is that's wrong?

I have several textures, ¿it is possible that all textures have the same aspect ratio?

**Comment by hdennen** [comment]
> I have several textures, ¿it is possible that all textures have the same aspect ratio?

It looks to me like you have accomplished this? All texture scale to fit without distorting the aspect ratio.
