### ISSUE TITLE
Question: Is Pixi.js compatible with React Native (without Expo)?

### ISSUE THREAD

**Issue by bernardbaker** [pixijs/pixi.js#5723]
I would really like to use Pixi.js in my vanilla JS React Native project. Is this possible with out the use of Expo?

### Environment

- **`pixi.js` version**: _e.g. 5.0.3_
- **OS & Version**: _e.g. MacOS Mojave version 10.14.5 - Android emulator_

**Comment by ivanpopelyshev** [comment]
So far I didnt see any demos on pixijs with react native. Would you like to make one? :)

Its dangerous to go alone, take this: https://github.com/Prozi/pixi-shim

**Comment by bernardbaker** [comment]
@ivanpopelyshev thanks for the sabre.

**Comment by ivanpopelyshev** [comment]
Even a partial report on the issues you encounter will be a significant contribution, I can help if there are specific prorblems. So far no one reported them , just asked if its possible.

**Comment by bernardbaker** [comment]
I'll update this thread with my findings and research.

I've installed: pixi.js, pixi-shim and fs.

The project is a vanilla JavaScript - React Native build.

**Comment by bigtimebuddy** [comment]
@bernardbaker thanks for digging into this. If you get a hello world working, would be great to capture this info on a wiki page here on the repo.

**Comment by bernardbaker** [comment]
@bigtimebuddy I think I have made a mistake. I'm working client side on a mobile application for Android and iOS.

**Comment by flyskywhy** [comment]
@[vitalije](https://github.com/vitalije) @[GoodBoyDigital](https://github.com/GoodBoyDigital) @[englercj](https://github.com/englercj) @[okcoker](https://github.com/okcoker) @[gre](https://github.com/gre) @[Prozi](https://github.com/Prozi) @[timknip](https://github.com/timknip) @[themoonrat](https://github.com/themoonrat) @[jackwlee01](https://github.com/jackwlee01) @[RossKinsella](https://github.com/RossKinsella) @[ivanpopelyshev](https://github.com/ivanpopelyshev) @[nickdima](https://github.com/nickdima) @[stevenalanstark](https://github.com/stevenalanstark) @[chipbell4](https://github.com/chipbell4) @[bernardbaker](https://github.com/bernardbaker) 

You can try [react-native-pixi](https://github.com/flyskywhy/react-native-pixi) based on [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) refactored from [GCanvas](https://github.com/alibaba/GCanvas ).

The example game [snakeRN](https://github.com/flyskywhy/snakeRN) is based on [react-native-pixi](https://github.com/flyskywhy/react-native-pixi).

**Comment by flyskywhy** [comment]
@Timson020 , I've forked your repo and fix "pixi.js with react-native-gcanvas can't work in android" in commit https://github.com/flyskywhy/Timson020-react-native-demo/commit/88f2d31e631f9f5e4c16ca572ebf8a0c0b259096 based on new version of `react-native-pixi@2` and `pixi.js@4.8.9`.

Breaking: Any APP now can be based on `pixi.js` `@4`, `@5`, `@6` or `@7` directly without `react-native-pixi` as described in [react-native-pixi@3](https://github.com/flyskywhy/react-native-pixi), you can easily follow the comments in example https://github.com/flyskywhy/GCanvasRNExamples/blob/master/app/components/Pixi.js to use any version of pixi.

So now you can upgrade you repo to `pixi.js@6` easily 😋
