### ISSUE TITLE
Can't build docs on Node 12

### ISSUE THREAD

**Issue by andresroberto** [pixijs/pixi.js#5724]
### Expected Behavior

After running `npm run docs` I should get the docs built into the `dist/docs` folder.

### Current Behavior

When running the command on Node 12, the current result of running `npm run docs` is:

<img width="1117" alt="Screenshot 2019-05-24 at 17 14 44" src="https://user-images.githubusercontent.com/1273138/58338114-73ace800-7e47-11e9-8265-460c56b35abb.png">

### Possible Solution

In order to solve this issue jsdoc needs to be updated to version 3.6 which supports Node 12. However, jsdoc 3.6 has some breaking changes that cause the docs to be generated in a erroneous way. More research is needed in order to find a way to upgrade and fix the docs afterwards.

### Steps to Reproduce

1. Set node 12 as current node version (for instance install and set it as current node version with nvm).
2. Run the `npm run docs` command.
3. See the error message.
4. Check the `dist/docs` folder does not exist.
5. Running `npm test` also generate the same error message but won't prevent the tests from running. The error shows up because the test script also generates typescript types based on the jsdoc output, therefore running jsdoc is part of the process.

### Environment

- **`pixi.js` version**: 5.0.3
- **Browser & Version**: No Browser but Node 12.2.0
- **OS & Version**: macOS 10.14.5
- **Running Example**: NA

**Comment by ivanpopelyshev** [comment]
Yep, its a known issue of requizzle, we are waiting for fix. Can you check it in their repo if it was solved?

**Comment by andresroberto** [comment]
Yes, they made a fix (https://github.com/hegemonic/requizzle/pull/4) and released it and JSDoc `3.6.0` includes the fix. Unfortunately, upgrading JSDoc breaks the generated documentation as mentioned by @bigtimebuddy (https://github.com/pixijs/pixi.js/pull/5722#issuecomment-495632329).
