### ISSUE TITLE
Holes don't work in CanvasRenderer

### ISSUE THREAD

**Issue by rpatwariingenuity** [pixijs/pixi.js#5727]
### Expected Behavior
beginHoles() and endHoles() should create holes.
### Current Behavior
They don't render anything on screen.
The same code worked with v4.8

### Steps to Reproduce
1. Use pixi-legacy for CanvasRenderer.
2. Create graphics.
3. Create holes using moveTo and lineTo, because addRect doesn't work.

- **`pixi.js` version**: _PIXI v5.0.3-legacy_
- **OS & Version**: _Windows10_
- **Running Example**: _https://www.pixiplayground.com/#/edit/4GVTR9VA2uBmxe74PB2~z_

**Comment by rpatwariingenuity** [comment]
I needed invert masking. So, I would create a bigger rectangle, and cut holes where I don't my image to show. Now apply this as mask. It worked with WebGL, but not with CANVAS. Is there any way to implement it?

**Comment by ivanpopelyshev** [comment]
Holes again.. ill look at it :)

**Comment by ivanpopelyshev** [comment]
Actually, it works: https://www.pixiplayground.com/#/edit/4GVTR9VA2uBmxe74PB2~z

I think you had wrong coords there in addRect.

**Comment by ivanpopelyshev** [comment]
I made a fix ONLY for polygon holes inside a polygon. Build is here: https://pixijs.download/dev-graphics-canvas-polygon-hole/pixi-legacy.js

Full solution will take much more time, we have too many issues that have bigger priority.

**Comment by rpatwariingenuity** [comment]
> I made a fix ONLY for polygon holes inside a polygon. Build is here: https://pixijs.download/dev-graphics-canvas-polygon-hole/pixi-legacy.js
> 
> Full solution will take much more time, we have too many issues that have bigger priority.

This works for me. Thanks, man.
