### ISSUE TITLE
Why does PIXI use Object.defineProperty ?

### ISSUE THREAD

**Issue by tleunen** [pixijs/pixi.js#573]
Just a global question to know the reason why PIXI uses that... Because it's isn't compatible with the obfuscation process as the variable is defined with a string, but not when we access it later in the code.

If you want to use that, you should use the variable as a string everywhere else in the code. In that case, it won't break the obfuscated code.

Or you want to prevent users to obfuscate their code :D

**Comment by cdunlap** [comment]
> I have a new work around that fix this issue for me without changing the initial code so it's perfect.

@tleunen Does your workaround allow uglify to complete the obfuscation and minification processes without any problems? If so, I'm interested.

**Comment by tleunen** [comment]
@cdunlap: I didn't test with uglify but we were using Google Closure Compiler and it worked well.
Unfortunately, it was done in my previous company and I don't work there anymore so I don't have access to the custom code I did at that time.

The code was also based on Pixi v2, now that it's v3, it might not be needed anymore
