### ISSUE TITLE
BitmapText tint doesn't work with pixi v5 Canvas Renderer

### ISSUE THREAD

**Issue by drskullster** [pixijs/pixi.js#5731]
### Expected Behavior

Tinting a BitmapText in a CanvasRenderer should work the same as for a WebglRenderer.

### Current Behavior

When adding a tint to a BitmapText in CanvasRenderer mode, only the first letter in the xml `<chars>` group is shown (with the properties of the other letters). And the letter is not tinted.

### Steps to Reproduce

  * Create a PIXI app and force canvas renderer
  * Create a BitmapText object
  * Add a tint

### Environment

- **`pixi.js` version**: 5.0.3
- **Browser & Version**: Firefox 67
- **OS & Version**: MacOS 10.13.6
- **Running Example**: 
https://www.pixiplayground.com/#/edit/07nXx54J53DrMMKg6PO5Q

(comment line 8 to switch between webgl and canvas)

**Comment by ivanpopelyshev** [comment]
5.0.3 works, its latest dev that doesn't . its interesting, what did we do wrong.. Thank you!

**Comment by ivanpopelyshev** [comment]
https://www.pixiplayground.com/#/edit/Cb6stLyzhuLCOEiaYcsZa

canvastinter fails.

**Comment by ivanpopelyshev** [comment]
PR build is here: https://pixijs.download/dev-canvas-tint/pixi-legacy.js

**Comment by drskullster** [comment]
Seems to work in the example I posted. 

Looking at the PR it also explains other bugs I have (basically since all my sprites are white (so they can be tinted) it looks like nothing is rendered).

Thanks a lot for your reactivity ! Will be on the lookout for v5.0.4 release :)

**Comment by redbeardmickey** [comment]
Thanks for the fix. What is the ETA for v5.0.4? We really want to migrate to v5 but are now blocked by this.

**Comment by bigtimebuddy** [comment]
Hoping to get it out this week
