### ISSUE TITLE
PIXI v5.03 mesh blendMode

### ISSUE THREAD

**Issue by bmdproject99** [pixijs/pixi.js#5736]
Hi,

Can't seem to get a mesh to apply its blendMode when placed over another sprite.

(see this codepen I just made:  https://codepen.io/bmdproject99/pen/araNEg  )

I wonder if the bug in v4 is back in v5?

(See the v4 issue:  https://github.com/pixijs/pixi.js/issues/2754  )

I tried setting blendMode to the shader, but still no luck.

Any thoughts?

bmd

**Comment by ivanpopelyshev** [comment]
https://www.pixiplayground.com/#/edit/785nGjqG5wSZoa9r2Xn7I

Third param in mesh constructor should be `state`, not `uniforms` . It breaks all webgl state management.

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital @bigtimebuddy do you guys think we need to guard users from that problem somehow?

**Comment by bmdproject99** [comment]
Thanks for speedy response, and the solution!.
I had used the following example, where uniforms are listed as third parameter:
https://pixijs.io/examples/#/mesh/uniforms.js

**Comment by ivanpopelyshev** [comment]
Not anymore.
