### ISSUE TITLE
Pixi-Legacy v5.0.3 CanvasRenderer's RenderTexture not working

### ISSUE THREAD

**Issue by edreal** [pixijs/pixi.js#5743]
When I try rendering sprite/container with `CanvasRenderer.prototype.render()` method to RenderTexture I get some internal deprecation warnings and its not working.

> PIXI.BaseTexture.source property has been moved, use resource.source

In playground I added Pixi-legacy's URL in settings "custom url" tab.
If you change Pixi version to v4.8.7 in playground it works with the same code.
It also works in legacy v5.0.3 if you change forceCanvas to **false** to make it use WebGL

Here is the link for code below:
[https://www.pixiplayground.com/#/edit/kWvBh7cKy7ai4yCWWXcf3](https://www.pixiplayground.com/#/edit/kWvBh7cKy7ai4yCWWXcf3)
```
var renderer = PIXI.autoDetectRenderer({
    forceCanvas: true
});

document.body.appendChild(renderer.view);

var circle = new PIXI.Graphics();
circle.beginFill(0xFF0000);
circle.drawCircle(0, 0, 512);
circle.endFill();

// Render "circle" object to renderTexture
var renderTexture = PIXI.RenderTexture.create(512, 512);
renderer.render(circle, renderTexture);

// Create sprite of renderTexture
var sprite = new PIXI.Sprite(renderTexture);

// Render sprite to the main canvas
renderer.render(sprite);
```

Can anyone overwrite the playground script btw?

**Comment by ivanpopelyshev** [comment]
Yes, anyone can override that script. Btw, there is a way to reference certain branch : `pixijs.download/dev/pixi-legacy.js` where `dev` is the name of branch.

RenderTexture doesn't work, its strange that we didnt test it.

**Comment by Rigwarl** [comment]
Any update on this?
It prevents my team from migration to v5.

**Comment by themoonrat** [comment]
https://github.com/pixijs/pixi.js/pull/5840 should have fixed it for next version. Try the latest dev build to test in the meantime

**Comment by Rigwarl** [comment]
Yes, it fixed in latest dev!
Can u give any clue when it will be released?

Thanks!

**Comment by themoonrat** [comment]
5.1.0 is due soon. Maybe within a week time period? It's not gonna too much longer

**Comment by bigtimebuddy** [comment]
Gonna close this, but yes probably sometime early next week.
