### ISSUE TITLE
CanvasRenderer's transform pivot bug (v4 and v5 legacy)

### ISSUE THREAD

**Issue by edreal** [pixijs/pixi.js#5744]
When using CanvasRenderers `render()` method with transform matrix argument, it messes up pivots in future renders. Bug doesn't happen in WebGL renderer and was in both v4.8.7 and v5.0.3 legacy

Playground link (v5.0.3 legacy)
[https://www.pixiplayground.com/#/edit/wZna2Z8U6kOZR5mz8BmoO](https://www.pixiplayground.com/#/edit/wZna2Z8U6kOZR5mz8BmoO)

```
var renderer = new PIXI.CanvasRenderer();

document.body.appendChild(renderer.view);

// Create stuff and render them to temporary renderTexture
var matrix = new PIXI.Matrix();
var emptySprite = new PIXI.Sprite(PIXI.Texture.WHITE);
var renderTexture = new PIXI.RenderTexture.create(123, 123);

// PROBLEM LINE: Removing matrix argument makes circles pivot work
renderer.render(emptySprite, renderTexture, false, matrix);

// Render untouched circle object to canvas
var circle = new PIXI.Graphics();
circle.beginFill(0xFF0000);
circle.drawCircle(0, 0, 100);
circle.endFill();
circle.pivot.set(-100);

renderer.render(circle);
```

**Comment by ivanpopelyshev** [comment]
CanvasRenderer swaps root element transform to the one you specified in matrix. That's different from what WebGLRenderer does. 

I've tried to fix this and some other inconsistencies in `extract` and `generateTexture` functions, but my PR was too big and was rejected. 

I don't know if its possible to fix this exact bug without making new ones at the moment. Need to make a document on how render() and all other render-related functions should behave with that parameter.

Workaround: put that circle in a container, change container transform (setFromMatrix) instead.

**Comment by edreal** [comment]
Okay. I'l try to work around it, thanks for the answer!
