### ISSUE TITLE
Memory leak in Pixi v5 ?

### ISSUE THREAD

**Issue by alaa-eddine** [pixijs/pixi.js#5747]
Hi,
I think I'm facing a memory leak in Pixi v5.
I have a code which was working just fine on some mid-end Android tablets in Pixi v4, but in v5 I get GL_OUT_OF_MEMORY errors.

The code that triggers the error uses a Rendertexture on which I draw sprites ; it's basically an avatar customization script, where I draw the base character, then draw the outfits on top of it.

I explicitely destroy the temporary textures I use, and checked that the number of textures in renderer.texture.managedTextures doesn't grow.

but I feel that, even if the textures are destroyed, they keep using memory leading to an out of memory error.

Note : I had the same behavior on Pixiv4 when I was not destroying the textures, but after adding code to destroy them, everything worked perfectly.

Could you please give me hints on how to debug this ? for example with a tool/code that allows me to check if destroyed textures are actually removed from gl context ? or which texture is leaking ?

Many thanks

**Comment by djmisterjon** [comment]
dev tool will allow to check your reference ,objet in memory and find your issue
it allow to see what stuff retain object.
example here, the GC will can't remove this object ref because it retain by 3 other ref.
![image](https://user-images.githubusercontent.com/24865815/58763341-68347d80-8527-11e9-913b-dbb7c6e563b9.png)
if is not a web app, you will need found a tool that's allow easily emulate the apk for debug from your pc to your tablet.
![image](https://user-images.githubusercontent.com/24865815/58763400-35d75000-8528-11e9-8284-3028e4c892d5.png)

**Comment by ivanpopelyshev** [comment]
I fixed stencil buffer leaks in v5 before, they were fixed. I believe that you found another memory leak, I can look at the code again, make a pass over everything, but im not sure that i'll find it. If you reproduce it and make smaller example, then it'll be easier for me.

**Comment by alaa-eddine** [comment]
Thank you @djmisterjon  for the hints, my game is both playable on browser and tablets, but the issue is only noticable on mid-end tablets (I guess because of limited Graphics memory), I'm able to debug the application remotely and I'm aware of memory allocations, but I think that what you pointed here is the main memory not the GPU one : The Texture instances are JS Objects I guess and not gl.texImage2D instances .  but you're right I can start here and check what's going on.


@ivanpopelyshev yes I read some older issues about memory leaks and saw that they were fixed, I'll try to reproduce mine with a simpler example.
what's pretty sure is that the issue is somehow related to RenderTexture instances . when I instantiate many (and destroy them) .... at a certain point I get the GL_OUT_OF_MEMORY error.

**Comment by alaa-eddine** [comment]
I managed to fix my issue by writing the code differently.
I was previously creating a renderTexture for each new player skin, and destroy the old one ==> this causes the leak.

in my new implementation, I clear the renderTexture and reuse it ==> no leak.

so this solves my problem, but the memory leak is actually present, seems that some data is not released when we destroy a renderTexture.

I'll close this issue, and reopen another when I manage to write a simple code that reproduce the issue.
I think it's a very specific case since I'm playing with textures and basetextures in my code.
