### ISSUE TITLE
Sprite mask WebGL error in v5

### ISSUE THREAD

**Issue by qtiki** [pixijs/pixi.js#5750]
### Expected Behavior

Using a sprite mask should work regardless of renderer resolution.

### Current Behavior

Sprite masks break the renderer with a WebGL error when the renderer resolution is 1.25 (or some other non-integer number):

```
128[.WebGL-00000234285BF510]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
128[.WebGL-00000234285BF510]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
results.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

### Steps to Reproduce

See Pixi Playground reproduction: https://www.pixiplayground.com/#/edit/95vNwHxGTVCOaHrGCneKG

### Environment

This happens when using `window.devicePixelRatio` for the resolution field with Chrome in Windows 10 when the display is set to 125% zoom in the OS display settings.

**Comment by ivanpopelyshev** [comment]
I fixed this, but it we didnt make release yet.

I switched pixijs version to `https://pixijs.download/dev/pixi.js` in that demo, please look again.

**Comment by qtiki** [comment]
I can confirm this is working for me too with the dev build of Pixi.

**Comment by bigtimebuddy** [comment]
Closing issue. Will be fixed in coming v5 release.
