### ISSUE TITLE
WebGL2 bad performance only in Firefox

### ISSUE THREAD

**Issue by Redsandro** [pixijs/pixi.js#5751]
### Expected Behavior

If I understand correctly, a `webgl2` canvas is hardware accelerated, as opposed to `2d` canvas. I expect two browsers that both run in `webgl2` mode to perform about the same.

### Current Behavior

Pixijs is very performant in Chrome. It is however very slow in Firefox.

### Steps to Reproduce

Open https://pixijs.io/pixi-filters/tools/demo/ in Chrome, full screen, High-res (retina). Very performant. Now do the same in Firefox. Less than 10 FPS (unless your computer is very fast I guess).

### Environment

- **`pixi.js` version**: _PixiJS 5.0.3 - ✰ WebGL 2_
- **Browser & Version**: _Firefox Quantum 67 x64, Chrome 76.0.3806.1 64-bit_
- **OS & Version**: _Linux Mint 19.1 AKA Ubuntu 18.04.1_
- **Running Example**: _https://pixijs.io/pixi-filters/tools/demo/_

**Comment by ivanpopelyshev** [comment]
OK, I'll try to reproduce!

>  Linux Mint 19.1 AKA Ubuntu 18.04.1

Oh noes, i will have to install OS!

Its also depends on linux drivers, beware! Which ones do i have to install?

**Comment by Redsandro** [comment]
> Oh noes, i will have to install OS!

Perhaps you can observe the same difference using the bootable Live image. I believe it's running the open source Nouveau driver.

Either way, I'm running Nvidia proprietary driver 396.54 from the "Driver Manager". You can't install drivers on the Live image, because you have to reboot.

**Comment by ivanpopelyshev** [comment]
OK got it. Though you will have to wait before I confirm it. My queue for that kind of tasks is loooong.

**Comment by Redsandro** [comment]
#### Update

I see the same problem using non-pixijs graphics, e.g. https://webglsamples.org/aquarium/aquarium.html
Hence, this is not directly pixijs related.

However, contrary to what my mother says, I am not unique. So this will probably affect a (small) fraction of pixijs users. It might be in everyones interest to find out if a specific method or call causes this and can be circumvented.

Not sure if I should close this issue or leave open until upstream cause and pixijs workaround is found.

**Comment by ivanpopelyshev** [comment]
We can report it to bugzilla and then close this issue.

**Comment by Redsandro** [comment]
I have amended an existing issue in Bugzilla here: [Mozilla Bugzilla #1246410 comment 39](https://bugzilla.mozilla.org/show_bug.cgi?id=1246410#c39). I am not sure this has the same cause.

Either way, note that when searching through the bug tracker, you can find similar reports dating back 7 years. Every next release had a `wontfix` label. They probably have their reasons (or not, could be lack of interest in `webgl`), but it looks a bit like `webgl` in Firefox is like Duke Nukem Forever: It's done when it's done.

People are slowly [moving from Chrome to Firefox](https://www.forbes.com/sites/kateoflahertyuk/2019/05/30/google-just-gave-2-billion-chrome-users-a-reason-to-switch-to-firefox/), so more people will be affected by this. So we can either wait for upstream fixes (Duke Nukem Forever took 15 years), or see if a local workaround is possible in PixiJS.

### Possible workaround in PixiJS

If I understand correctly, `texImage2D` is to blame. A function used by PixiJS for everything texture related. I read in https://www.khronos.org/registry/webgl/specs/latest/2.0/ that `texStorage2D` is more performant:

> `texStorage2D` should be considered a preferred alternative to `texImage2D`. It may have lower memory costs than `texImage2D` in some implementations.

If OpenGL ES is related to WebGL, this might also be interesting:

http://www.voidcn.com/article/p-qijrpsze-bcq.html

I don't know enough about this to say something more meaningful.

**Comment by ivanpopelyshev** [comment]
interesting. We have workaround through `texSubImage2D` : https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/BaseImageResource.js#L69 

We didnt use `texStorage2D` yet.

As for bugzilla, I'm afraid that its very slow compared to chromium. Im waiting for more than a year on 2 issues.

**Comment by Redsandro** [comment]
Can you tell me what would effectively cause the `if` right above that to be false?

**Comment by Redsandro** [comment]
Also gameofbombs (wow pretty addictive) is laggy in Firefox/Linux. Smooth on Chrome.

> We can report it to bugzilla and then close this issue.

I will close this issue. Firefox is lacking in Linux. I better detect Firefox + Linux and tell visitors that this browser is not supported.
