### ISSUE TITLE
PIXI.Ticker and PIXI.ticker

### ISSUE THREAD

**Issue by davidfig** [pixijs/pixi.js#5757]
I maintain pixi-viewport and pixi-ease, and I'm having a tough time with the name change from PIXI.ticker to PIXI.Ticker. 

I was wondering if you guys are open to mapping PIXI.Ticker to PIXI.ticker for v5 builds. I use PIXI.Ticker.shared as a default to handle my update loops, and I have not found a good way of handling this change while supporting both pixi.js v4 and v5 builds.

I've been hacking it using this code:
```js
const ticker = typeof PIXI.Ticker === 'undefined' ? PIXI.ticker.shared : PIXI.Ticker.shared
```
But this breaks when building with rollup since it tries to import { ticker, Ticker }, which causes problems for both pixi.js v4 and v5 builds. 

I know this is not ideal, and I'm open to a workaround if you have any ideas. I'm trying to avoid dropping support for v4 at least in the short run. Happy to submit a PR if you're interested.

Thanks!

**Comment by davidfig** [comment]
For now, I'm asking users who want to use v4 to pass { ticker: PIXI.ticker.shared } in the options. It's not ideal since it does not work out with the default options for pixi.js v4.

**Comment by ivanpopelyshev** [comment]
I'm moving a number of heavy pixijs plugins, In my case, there are too many changes to maintain one version for all pixies. I use `v4.x` branch to store the old version, and I ask users to specify particular npm version for v4.

That doesn't mean you should drop the support. I think you know better than me, how many v3-v4 users actually care about updates in your repo.

**Comment by andrewstart** [comment]
See https://github.com/pixijs/pixi-particles/blob/master/src/Emitter.ts - I
have rollup friendly support for both tickers.

**Comment by davidfig** [comment]
Clever piece of code! Cutting and pasting for future peeps.

```js
let ticker: pixi.ticker.Ticker;
// to avoid Rollup transforming our import, save pixi namespace in a variable
const pixiNS = pixi;
if (parseInt(/^(\d+)\./.exec(pixi.VERSION)[1]) < 5)
{
	ticker = pixiNS.ticker.shared;
}
else
{
	ticker = (pixiNS as any).Ticker.shared;
}
```

**Comment by ivanpopelyshev** [comment]
Holy Cow!

**Comment by andrewstart** [comment]
Some additional details - that code is being built against the PIXI V4 types, to build against V5 you would just need to change the `let ticker: pixi.ticker.Ticker` variable type to `let ticker: pixi.Ticker` and change which block gets `(pixiNS as any)`.
