### ISSUE TITLE
Sprite tint no longer works with CanvasRenderer in v5 legacy

### ISSUE THREAD

**Issue by redbeardmickey** [pixijs/pixi.js#5759]
Tinting sprite with CanvasRenderer no longer works in v5 (worked in v4)

v4.8.7: https://www.pixiplayground.com/#/edit/1gEV0l2vOPzlXMfuP63MA
v5.0.3 legacy: https://www.pixiplayground.com/#/edit/I7o5iQkGBNFwylJAzUAzu

**Comment by ivanpopelyshev** [comment]
It works in latest dev, here: https://pixijs.download/dev/pixi.js
