### ISSUE TITLE
Sprite.pluginName should be "sprite"?

### ISSUE THREAD

**Issue by mudcube** [pixijs/pixi.js#5761]
I noticed that Sprite.pluginName is now “batch” is that on purpose? Or should it be “sprite”? I notice [in the documentation](http://pixijs.download/dev/docs/PIXI.Sprite.html#pluginName) it says the default name should be “sprite”, so it seems one of the two should be updated, just not sure which.

### Expected Behavior
Sprite.pluginName should equal "sprite"

### Current Behavior
Sprite.pluginName equals "batch"

- **`pixi.js` version**: _e.g. 5.0.3

**Comment by ivanpopelyshev** [comment]
`batch` is the default plugin in v5. previously named `sprite` :)

**Comment by bigtimebuddy** [comment]
This change was intentional. SpriteRenderer was replaced with BatchRenderer which now supports mesh, graphics as well.

**Comment by mudcube** [comment]
Ahh, thanks for the insightful responses. Very cool update :)
To confirm, would it make sense to update the following documentation line to read 'batch'?

https://github.com/pixijs/pixi.js/blob/1d7ad71790a2f7427de556cb3e58ef2117a621de/packages/sprite/src/Sprite.js#L164

**Comment by themoonrat** [comment]
Yes, definitely!

**Comment by bigtimebuddy** [comment]
PR welcome for that fix
