### ISSUE TITLE
Misrendering of stroke and fill of Graphics drawn with bezierCurveTo

### ISSUE THREAD

**Issue by dylanbox** [pixijs/pixi.js#5762]
### Expected Behavior
When drawing a Graphics with a fill, stroke, and multiple _straight_ curve segments drawn with `bezierCurveTo` (like a dashed line), the graphics should appear as such:

![image](https://user-images.githubusercontent.com/487275/59067724-541eb200-8880-11e9-86f6-53cf118102fd.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/487275/59067832-9516c680-8880-11e9-9db2-e24e74f57d3c.png)
Currently, the line caps appear cut off on one segment and the fill texture (which shouldn't be seen, because the line is straight) is appearing as part of the stroke color.

This only occurs if:
- The starting point and the y values of the control and end points are the same (it's a straight curve). So modifying any of those y values (you only need to do it to one) so it's slightly off will fix the issue. (I'd personally like to avoid this hacky solution in my code)
- There is also a fill on the Graphics. So removing the fill will also draw it correctly.

### Steps to Reproduce

This Pixi Playground has the broken use case, with 3 potential solutions that involve modification to the Graphics object.
https://www.pixiplayground.com/#/edit/nxye~v5fiCBJzWTuRMjJX

### Environment

- **`pixi.js` version**: 5.0.3
- **Browser & Version**: Chrome 75, Safari 12.1.1
- **OS & Version**: macOS Mojave 10.14.5
- **Running Example**: https://www.pixiplayground.com/#/edit/nxye~v5fiCBJzWTuRMjJX

**Comment by ivanpopelyshev** [comment]
Its interesting that "forceCanvas:true" works there. I've specified `pixi-legacy.js` in the settings of your playground.

**Comment by dylanbox** [comment]
Also interesting to note: this doesn't occur in PixiJS v4. We'd definitely love to avoid using pixi-legacy, here, as well.

**Comment by themoonrat** [comment]
Updated that example to the latest dev version, and it looks correct, so closing!

**Comment by dylanbox** [comment]
Hey I'm still seeing it on the latest version, I don't think it's been fixed.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/487275/62060301-dda08f80-b1f2-11e9-9945-6f65ee9156d7.png">

**Comment by FurFrenzy-cell** [comment]
Ok

**Comment by themoonrat** [comment]
Bumping - still an issue

**Comment by bigtimebuddy** [comment]
I'm not seeing this issue anymore on latest. Closing again.

**Comment by dylanbox** [comment]
Yeah looks like 5.2.1 solved it, thanks everyone!
