### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixi.js#5765]
https://github.com/pixijs/pixi.js/blob/f8ed935c26f6c34f5777b5ff5846b4cec2c923e8/packages/sprite/src/Sprite.js#L17

https://github.com/pixijs/pixi.js/blob/f8ed935c26f6c34f5777b5ff5846b4cec2c923e8/packages/sprite/src/Sprite.js#L498

`from` is a static method, should `new` be removed?

https://github.com/pixijs/pixi.js/blob/f8ed935c26f6c34f5777b5ff5846b4cec2c923e8/packages/core/src/textures/Texture.js#L20

**Comment by bigtimebuddy** [comment]
You are correct. PR welcome to fix this.
