### ISSUE TITLE
lineTextureStyle doesn't work with CanvasRenderer

### ISSUE THREAD

**Issue by redbeardmickey** [pixijs/pixi.js#5767]
### Expected Behavior
`lineTextureStyle` should work with both WebGL renderer and CanvasRenderer.

### Current Behavior
`lineTextureStyle` doesn't work with CanvasRenderer.

### Environment

- **`pixi.js` version**: v5.0.4
- **Browser & Version**: Chrome/FF/Safari
- **Running Example**: https://www.pixiplayground.com/#/edit/BO0J_OzCi2aCMB6DTOJPJ

**Comment by ivanpopelyshev** [comment]
We dont have that code yet, so its a feature request :) Of course its possible, we can pass pattern to strokeStyle: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeStyle
