### ISSUE TITLE
SVG Support for Internet Explorer's XMLSerializer.serializeToString

### ISSUE THREAD

**Issue by KTM450SXF** [pixijs/pixi.js#5773]
new window.PIXI.Texture.from() blows up with the a string produced by Internet Explorer's XMLSerializer.serializeToString.

I.E.'s serializeToString returns a string different than other browsers.    Rather than this string output created by Chrome's serializeToString:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="2450px" height="1850px" viewBox="-9.5 -12 2450 1850" enable-background="new -9.5 -12 2450 1850" xml:space="preserve">
<defs>
</defs>
<rect x="812.5" y="0" fill="none" width="806" height="602.448"/>
<polygon id="C_21_" fill="#102C62" points="1525.248,372.64 1120.833,590.583 949.177,592.044 1465.646,258.272 "/>
<polygon id="A_19_" fill="#F406D7" points="1545.326,411.166 1267.7,590.583 1036.099,587.371 1485.726,296.797 "/>
</svg>`

Internet Explorer's serializeToString produces this:
`<svg xmlns=\"http://www.w3.org/2000/svg\" enable-background=\"new -9.5 -12 2450 1850\" viewBox=\"-9.5 -12 2450 1850\" x=\"0px\" y=\"0px\" width=\"2450px\" height=\"1850px\" xmlns:xml=\"http://www.w3.org/XML/1998/namespace\" xml:space=\"preserve\" version=\"1.1\">\n<defs>\n</defs>\n<rect fill=\"none\" x=\"812.5\" y=\"0\" width=\"806\" height=\"602.448\" />\n<polygon id=\"C_21_\" fill=\"#102c62\" points=\"1525.25,372.64 1120.83,590.583 949.177,592.044 1465.65,258.272\" />\n<polygon id=\"A_19_\" fill=\"#f406d7\" points=\"1545.33,411.166 1267.7,590.583 1036.1,587.371 1485.73,296.797\" />\n</svg>`

Notice how IE's produces what appear to be escaped quotes and newlines, but actually renders the backslash and the quote or backslash and "n".

Attempts to string.replace have proven futile; I simple replace a rendered \" with another rendered \"

A) I'm a bit ashamed to admit that I would've called a \" the exact same unicode character as a literal " - What did I miss here?
B) I would hope you'd want the product of I.E.'s serializeToString to be usable by window.PIXI.Texture.from() so I do consider this a legitimate issue.

**Comment by ivanpopelyshev** [comment]
It looks like an issue for compatibility plugin, we already have one: https://github.com/pixijs/pixi.js/tree/dev/packages/unsafe-eval

However I'm a bit of skeptical that anyone in pixijs core team will want to take this issue this month. The fate of this issue is uncertain, unless someone writes actual code for it.

**Comment by KTM450SXF** [comment]
Totally understandable.  I'll simply not support I.E. for now.  I'll keep my eye on this issue in case it ever does get addressed.

Thanks again for such an awesome library.

**Comment by jaber975** [comment]
تطوير الخيارات والمميزات وجود ميزة إعلانية مجانيه لمنشوراتي على  الفيسبوك أدناه  على جهازي وهذا
