### ISSUE TITLE
Cannot run unit tests in chrome --headless due to WebGL support

### ISSUE THREAD

**Issue by stevenalanstark** [pixijs/pixi.js#5778]
I'm using Karme with babel, webpack and karma-typescript in order to run unit tests in Chrome

When running a karma unit test, it will run correctly when using chrome, but fails when using chrome --headless.

the error shown is: 

`Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.`

I could do as the error suggest, and re-work the code to use support the Canvas renderer via pixi.js-legacy, however I am expecting that I can run the unit tests without relying on that as a solution. I would like to keep my tests in WebGL and not Canvas2D.

adding in the `--disable-gpu` flag did not resolve this for me; I have read that this flag will tell Chrome to use swiftshader as the GPU renderer.

I'm in OSX, but I will also need this to run under CI in a Ubuntu docker container.

Thank you in advance for any help resolving this issue.

### Environment

- **`pixi.js` version**: 5.0.2
- **Browser & Version**: Chrome 75
- **OS & Version**: OSX 10.14.5

**Comment by ivanpopelyshev** [comment]
We used `withGL` function in tests not so long ago: https://github.com/pixijs/pixi.js/pull/4748/files

We removed it because our testing environment has WebGL in it. Do we have to add it back?

**Comment by stevenalanstark** [comment]
Sorry for the confusion, I don't think I was clear. I am talking about my own unit testing, and not running the pixi.js test suite itself.

The line that causes the error is:

`let scene = new PIXI.Application();`

This is because running Chrome in --headless doesn't pass PIXI.JS's WebGL check. 

I'm going to test this some more here today to see if it's Chrome that's the issue, since WebGL support in --headless mode is fairly new still.

**Comment by stevenalanstark** [comment]
I've narrowed down the issue.

I copied the code from here:

https://github.com/pixijs/pixi.js/blob/824b8d20ecbacad0c80d82a002009aded7f62ab1/packages/utils/src/browser/isWebGLSupported.js

and made a unit test, and it failed.

I then changed `failIfMajorPerformanceCaveat` to be `true`, and it passed.

This seems to be the culprit, but I don't know much about this option. Could this be something that should be configurable?

**Comment by englercj** [comment]
That param (more or less) means that when WebGL will be software rendered, just use canvas instead which can be faster. We should allow the user to set that parameter for sure.

**Comment by themoonrat** [comment]
New setting implemented for pending 5.1.0 release

**Comment by stevenalanstark** [comment]
@themoonrat Thank you very much! 🎉

**Comment by LymanLiu** [comment]
`PIXI.settings.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT = false`
