### ISSUE TITLE
pixi.js v5 examples doesn't work under Firefox

### ISSUE THREAD

**Issue by WinPooh32** [pixijs/pixi.js#5780]
### Expected Behavior
Working examples in gallery
### Current Behavior
Doesn't work any example on pixi.js v5, but v4 works well.
I can see error in browser console:
```
TypeError: invalid 'instanceof' operand window.OffscreenCanvas pixi.js:11815:1
    test pixi.js:11815
    autoDetectResource autoDetectResource.js:84
    BaseTexture BaseTexture.js:55
    from Texture.js:356
    onload (index):11
```

### Steps to Reproduce
Open any example using Firefox browser.

### Environment

- **`pixi.js` version**: _5.0.4_
- **Browser & Version**:  any Firefox ( 67.0.2 ), also tested on PaleMoon, Firefox 68.0b9
- **OS & Version**: _e.g. Windows 10_
- **Running Example**: https://pixijs.io/examples/#/demos-basic/container.js

**Comment by bigtimebuddy** [comment]
@mudcube would you mind taking a look at this? The logic in test probably isn’t quite right when OffscreenCanvas is undefined.

**Comment by mudcube** [comment]
@bigtimebuddy Sorry for not being around earlier. It looks like you've got this resolved in the best way possible. Thanks for sorting this out.
