### ISSUE TITLE
The guarantee that the sprite was rendered

### ISSUE THREAD

**Issue by martinboksa** [pixijs/pixi.js#5781]
Hello guys,

Please, is it possible to get guarantee that sprite was rendered at canvas? 
Time to time I need extract screenshot from container ( to create some previews, thumbnails, ... ). 

But sometimes screenshot is wrong 'cause it excluded some sprites from image.

Example:
**WRONG SCREENSHOT**
![wrong](https://user-images.githubusercontent.com/4490694/59510916-3fac6c00-8eb5-11e9-968d-f839f2cb4723.png)

**GOOD SCREENSHOT**
![good](https://user-images.githubusercontent.com/4490694/59510981-65397580-8eb5-11e9-8a8d-087a99c46e7d.png)

In this case I have generator which is loading sprites and then create screenshot with them.
So generator is waiting for sprites and before screenshot it checks conditions whether everything is okay.

Condtions:
- sprite.visible = true
- sprite.texture.baseTexture.hasLoaded = true
- sprite.alpha = 1
- sprite.renderable = true

I call Extract instantly after adding sprite to container.
Please, what next i need check to be sure that screenshot will be okay with all sprites?

Additional info:
Loading texture:
- image = new Image()
- image.onload = () => texture = Texture.fromLoader(image, image.src)
- sprite = new Sprite(texture)
- addChildToContainer(sprite)

**Comment by stevenalanstark** [comment]
I'm just curious if you have already tried calling `render()` on the Container before taking your screenshot?

https://pixijs.download/dev/docs/PIXI.Container.html#render

**Comment by ivanpopelyshev** [comment]
@stevenalanstark it'll be called inside `extract` if container is passed there.

**Comment by martinboksa** [comment]
I'm gonna close issue. Despite my effort to repeat, I did not succeed. So it looks like my problem.
https://jsfiddle.net/bou1s7qn/1/
