### ISSUE TITLE
(Base)Texture from Blob or ImageData

### ISSUE THREAD

**Issue by dev-zetta** [pixijs/pixi.js#5783]
Hello everyone,

I have a spritesheet that I load manually. Now I have ImageBitmap object, created from Blob. I would like to create BaseTexture and then Spritesheet.

Is this possible? I didn't see any option to pass Blob or ImageBitmap to the source parameter.

**Comment by bigtimebuddy** [comment]
There are two parts to your question, the first is creating the BaseTexture. We should, but currently don't support, ImageBitmap as a source type in `BaseTexture.from`. You'll need to install a new resource type to handle this. Give something like this a try:

```js
class ImageBitmapResource extends PIXI.resources.BaseImageResource {
  static test(source) {
    return source instanceof ImageBitmap;
  }
}
// Install the new resource type
PIXI.resources.INSTALLED.push(ImageBitmapResource);
```

The second part is easier, once you have a BaseTexture, you can create a Spritesheet pretty easily. Look at the docs for Spritesheet: http://pixijs.download/dev/docs/PIXI.Spritesheet.html

```js
const baseTexture = PIXI.BaseTexture.from(imageBitmap);
const spritesheet = new PIXI.Spritesheet(baseTexture, data);
```

**Comment by dev-zetta** [comment]
@bigtimebuddy Thank you Karl, for the quick response and solution, it works :)

**Comment by bigtimebuddy** [comment]
I'd suggest that we create a first-class resource type like ImageBitmapResource. Anyone want to create a PR for that?
