### ISSUE TITLE
Cannot Create a texture from a Graphic if CacheAsBitmap is on

### ISSUE THREAD

**Issue by stevenalanstark** [pixijs/pixi.js#5784]
I understand this is an edge case, and may very well be 'as designed', however I wanted to raise the issue anyhow so that it is known.

I made a CodePen to prove the issue here:

https://codepen.io/anon/pen/rExjVy?editors=0011

if you remove the line `graphics.cacheAsBitmap = true;`, then things work as expected and the texture is rendered, but with that set to true, there is no texture. Or, perhaps, it's an empty texture?

### Expected Behavior

Texture to render, or at least an error to be shown.

### Current Behavior

Texture is empty. No errors are shown.

### Possible Solution

Render the texture, or throw an error

### Environment

- **`pixi.js` version**: 5.0.4
- **Browser & Version**: Chrome 75
- **Running Example**: https://codepen.io/anon/pen/rExjVy?editors=0011

**Comment by JetLua** [comment]
http://pixijs.download/release/docs/PIXI.Container.html#cacheAsBitmap
> IMPORTANT GOTCHA - Make sure that all your textures are preloaded BEFORE setting this property to true as it will take a snapshot of what is currently there. If the textures have not loaded then they will not appear.

I think you might need to render it first(It could be a bug).

```js
graphics.cacheAsBitmap = true; // Change this to false and it will work.
app.renderer.render(graphics); // Work
```

**Comment by stevenalanstark** [comment]
@JetLua - Thank you, that is a decent work around for the time being


I just wanted to add that this worked in v4 and it works in pixi.js-legacy, it is only a v5 issue.

**Comment by mofnire** [comment]
Found two problems in `DisplayObject#_initCachedDisplayObject`.

1) The first one is `renderer._activeRenderTarget` does not hold a current rendering target.

https://github.com/pixijs/pixi.js/blob/4d71fa06ea787d81651fc3e624610ccfc3c3f457/packages/mixin-cache-as-bitmap/src/index.js#L185-L189

`const cachedRenderTarget = renderer.renderTexture.current;` works in my test.

2) The second one is `renderer.projection.transform` is not restored after the line 213.

https://github.com/pixijs/pixi.js/blob/4d71fa06ea787d81651fc3e624610ccfc3c3f457/packages/mixin-cache-as-bitmap/src/index.js#L210-L216

With these two modifications, the purple rectangle is rendered on my PC.
https://www.pixiplayground.com/#/edit/SwOYH3ruZKO3ntG01n9~P

**Comment by mofnire** [comment]
Working example:
[https://www.pixiplayground.com/#/edit/hk1gjmUM84Nl72GncOii~](https://www.pixiplayground.com/#/edit/hk1gjmUM84Nl72GncOii~)
