### ISSUE TITLE
No way of telling if BaseTexture is in cache

### ISSUE THREAD

**Issue by dev-zetta** [pixijs/pixi.js#5785]
Hello there,

how do I find out that a base texture with given key is in cache?

There are methods PIXI.BaseTexture.addToCache and  PIXI.BaseTexture.removeFromCache, but no method to find out, if it is in cache or not.

Well, except manually accessing the cache object PIXI.utils.BaseTextureCache.

**Comment by englercj** [comment]
Manually access the cache object

**Comment by dev-zetta** [comment]
Thanks for the answer :)

I added helper method to the BaseTexture class:

```
PIXI.BaseTexture.getFromCache = (key) => PIXI.utils.BaseTextureCache[key]
```
