### ISSUE TITLE
plugins extract bug?

### ISSUE THREAD

**Issue by nareistar** [pixijs/pixi.js#5786]
Hello.

I'm trying extract Container to base64 (or canvas, or image).

```
var user = new PIXI.Container();
user.add('image.png');

var graphics = new PIXI.Graphics();
graphics.beginFill();
graphics.drawCircle(310, 130, 170);
graphics.endFill();

container.addChild(graphics);

user.mask = graphics;
console.log(_user.libs.canvas.pixi.renderer.plugins.extract.base64(user)); 
```

This results in a blank image.
But if user.mask = null - it's work correct.

**Comment by ivanpopelyshev** [comment]
Same as #5784 . This question is asked too often.

**Comment by stevenalanstark** [comment]
@ivanpopelyshev - sorry but I don't see how the two are the same issue. Am I missing something?

This issue is about loading the image, yes, just as you say.

#5784 - This is about being unable to generate a texture from a drawn Shape if `cacheAsBitmap` is on, which is a regression from v4.

**Comment by badasszay** [comment]
I need help with submittng my plugins extract bug

**Comment by themoonrat** [comment]
Closing this issue as it seems answered. Please create a new issue if you still have problem. Thanks!
