### ISSUE TITLE
Animated sprite from spritesheet error

### ISSUE THREAD

**Issue by dev-zetta** [pixijs/pixi.js#5789]
Hello there,

you get an error when you create AnimatedSprite from Spritesheet's textures. The constructor of AnimatedSprite takes Array of textures whereas Spritesheet textures property is an Object/Map. 

Here you reference textures parameter with index 0.
https://github.com/pixijs/pixi.js/blob/9ce2c6c878bc87d1475f942bcc3a6e7acf99e3d2/packages/sprite-animated/src/AnimatedSprite.js#L47

There is no index 0 in the generated textures in Spritesheet. Those are key:texture values, where key is a name of the frame.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/packages/spritesheet/src/Spritesheet.js#L260

There's a way to pack animations to spritesheet and get arrays. If you dont know how to do it in editor, you can manually convert whatever you get to array.

**Comment by dev-zetta** [comment]
I converted that map of textures to an array manually, but still, according to docs, it should be possible to pass textures from spritesheet to animated sprite directly

**Comment by ivanpopelyshev** [comment]
its about `animations` property: 

https://github.com/pixijs/pixi.js/blob/9ce2c6c878bc87d1475f942bcc3a6e7acf99e3d2/packages/sprite-animated/src/AnimatedSprite.js#L29

It exists only if you specified something in texturepacker, i dont know what :)

**Comment by dev-zetta** [comment]
There is also an issue with the _processFrames method.

https://github.com/pixijs/pixi.js/blob/44c88cfe00f58fb36f6406215706a1741c8401b0/packages/spritesheet/src/Spritesheet.js#L183

It loads the "anchor" property from frame definitions. Howerer, my generated spritesheet has "center" property, which is pixel based. 

This spritesheet is loaded just fine in Phaser.

**Comment by ivanpopelyshev** [comment]
PixiJS doesnt have center of textures. Also you can use PixiJS spritesheet JSON format when using texturePacker, im not sure about other editors, it should contain anchor instead.

As for center, either you can modify Spritesheet for your case easily:

```js
PIXI.Spritesheet.prototype._processFrames = function(initialFrameIndex) { ... }
```

We cant add it to vanilla PixiJS because our official format doesn't have `center` and even if we add it, we dont have such field in `Sprite`, we only have `pivot` and it affects children. Our format is approved by TexturePacker author.

**Comment by dev-zetta** [comment]
Thank you Ivan :) I already hooked that method.

```
        let anchor = data.anchor
        if (!anchor && data.center) {
          anchor = {
            x: data.center.x / rect.w,
            y: data.center.y / rect.h
          }
        }

        this.textures[i] = new Texture(
          this.baseTexture,
          frame,
          orig,
          trim,
          data.rotated ? 2 : 0,
          anchor
        )
```

**Comment by dev-zetta** [comment]
> https://github.com/pixijs/pixi.js/blob/dev/packages/spritesheet/src/Spritesheet.js#L260
> 
> There's a way to pack animations to spritesheet and get arrays. If you dont know how to do it in editor, you can manually convert whatever you get to array.

I believe that it's called "hash" format. It's supported in Phaser 3 (I'm switching to Pixi).  It's basically the same format, only frames have are saved in object and not array.

**Comment by themoonrat** [comment]
Seems like it's a new format being requested to be supported?
