### ISSUE TITLE
Blend modes do not work with filters

### ISSUE THREAD

**Issue by blueblue4437** [pixijs/pixi.js#5795]
https://pixijs.io/examples/#/demos-basic/blendmodes.js

Add this line to the above demo.
`dude.filters = [new PIXI.filters.AlphaFilter()];`

Then PIXI.BLEND_MODES.ADD will not apply.

PIXI: v5.0.4

**Comment by blueblue4437** [comment]
It seems not a bug. sorry

**Comment by themoonrat** [comment]
And @ivanpopelyshev sighs with relief ;)
