### ISSUE TITLE
BitmapText: kerning symbol ID divide into resolution.

### ISSUE THREAD

**Issue by Re-Mind** [pixijs/pixi.js#5796]
Maybe this is a bug. 

In `BitmapText.registerFont` 

https://github.com/pixijs/pixi.js/blob/44c88cfe00f58fb36f6406215706a1741c8401b0/packages/text-bitmap/src/BitmapText.js#L637

`first` and `second` is kerning characters (decimal ID in Unicode).
There is no need to divide them.

- **`pixi.js` version**: 5.0.4

**Comment by themoonrat** [comment]
@Re-Mind would it be possible to create a fiddle or playground that demonstrates this being wrong please? Thanks!

**Comment by Outfire** [comment]
@themoonrat 
For reproduce you can use https://pixijs.io/examples/#/text/bitmap-text.js
Just add PIXI.settings.RESOLUTION = PIXI.settings.FILTER_RESOLUTION = 2 at the first row

**Comment by Re-Mind** [comment]
Need fix this.

With bug:
https://github.com/pixijs/pixi.js/blob/44c88cfe00f58fb36f6406215706a1741c8401b0/packages/text-bitmap/src/BitmapText.js#L637-L638

Without bug:
```
const first = parseInt(kerning.getAttribute('first'), 10);
const second = parseInt(kerning.getAttribute('second'), 10);
```

`first` and `second` vars is ID of characters from the Unicode table.
(column "Decimal" https://en.wikipedia.org/wiki/List_of_Unicode_characters)

Demo with bug:
https://www.pixiplayground.com/#/edit/cm1LD_a9oa4qsRILNvDDB
(change first line `PIXI.settings.RESOLUTION` to `1` or `2`.)
