### ISSUE TITLE
JPEG Blend modes issue in Pixi 2.2.9 with Phaser 2.6.2

### ISSUE THREAD

**Issue by redsanso** [pixijs/pixi.js#5799]
Hello,
I have a png animation spritesheet of some "light FX" with transparent pixels. 
Since I must spare on assets weight in my game, I'm trying to:
- export it as jpg to shrink its size a little bit
- use it in PIXI with the blendMode ADD
- put it over a png sprite in blendMode NORMAL that uses an animation spritesheet
- put them above a jpg background.

The undesired result is the following: 
The "jpg light fx" in mode ADD seems to "pierce" my underlying character just like it also had ADD. The background is unaffected.

Can you help me?

**Comment by bigtimebuddy** [comment]
Please provide an example of what your describing.

**Comment by ivanpopelyshev** [comment]
Nope, ask guys from phaser community edition. Here you can wait two or three months, maybe I'll try to move phaser2 to pixi-v5 ;) I certainly cant help with old v2. maybe something like changing it to `[gl.ONE, gl.ONE]` in a certain file with all webgl modes can help.

**Comment by redsanso** [comment]
> Nope, ask guys from phaser community edition. Here you can wait two or three months, maybe I'll try to move phaser2 to pixi-v5 ;) I certainly cant help with old v2.
> 
> Maybe something like changing it to `[gl.ONE, gl.ONE]` in a certain file with all webgl modes can help.

I'll try, thanks

**Comment by themoonrat** [comment]
Going to close this down; the version of Pixi that Phaser 2.x uses is their own custom version, so it's best to ask for support there, as Ivan recommended :)
