### ISSUE TITLE
Installing package from github

### ISSUE THREAD

**Issue by dev-zetta** [pixijs/pixi.js#5800]
Hello,

I'm trying to install pixi package from github using url like this:

```npm install pixijs/pixi.js#master```

It reports error:
```Can't install github:pixijs/pixi.js#b7d187073f3b2d5940fadd65629536da1745c349: Missing package version```

I also tried to specify path to bundles/pixi.js, but npm does not support this.

Then I tried to clone the repo manually and use it as file in package.json:
```"pixi.js": "file:vendor/pixi.js/bundles/pixi.js"```

But the package is not being "found" by cjs loader.

I found issue #3365, where it says that I should refer to release branch... but that is several years old.

**Comment by bigtimebuddy** [comment]
This is not supported because we do not publish built code anymore on the repo. If you want the latest code, the easiest way is to pull https://pixijs.download/dev/pixi.min.js but that won’t work with npm.

**Comment by dev-zetta** [comment]
Thanks Matt. So I will have to fork the repo, clone, build and push to the fork :)
