### ISSUE TITLE
Adding nodes to D3 force simulation

### ISSUE THREAD

**Issue by hinshun** [pixijs/pixi.js#5801]
Hello, I'm new to both D3 and pixi.js and wanted to add new nodes to a D3 force simulation and render the nodes via pixi.js. The starting nodes simulate fine, but adding new nodes run off to the corner. Curious if anyone knows what's going on with my simple example.

![](https://i.ibb.co/TPKPFx9/pixi-d3.png)

- **`pixi.js` version**: _5.0.4_
- **`d3.js` version**: _5.9.2_
- **Browser & Version**: _Chromium 71.0.3578.98_
- **OS & Version**: _Ubuntu 18.04_
- **Running Example**: https://www.pixiplayground.com/#/edit/R3qKqS3iblJFmFW_NiLss

**Comment by englercj** [comment]
I don't know anything about d3, but logging the node data in the ticked function seems to suggest that the pixi graphics are rendering what the node's values are. So the issue is with the D3 usage, not your pixi usage.

**Comment by hinshun** [comment]
Thanks @englercj, I narrowed down the D3 usage issue and worked out the example here: https://www.pixiplayground.com/#/edit/R3qKqS3iblJFmFW_NiLss
