### ISSUE TITLE
4.8.8 not released to CDN

### ISSUE THREAD

**Issue by afarber** [pixijs/pixi.js#5802]
Thank you for the wonderful software!

The release 4.8.8 seems to be missing at the CDN:

https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.8.8/pixi.min.js

returns "404 Not Found"

**Comment by bigtimebuddy** [comment]
Not sure what’s up with that. Shows up on jsdelivr 

https://cdn.jsdelivr.net/npm/pixi.js@4.8.8/dist/pixi.min.js

**Comment by themoonrat** [comment]
Both links work for me, so closing. Please create a new issue if you're still having problems!
