### ISSUE TITLE
pointermove not working as expected in nested objects

### ISSUE THREAD

**Issue by juregregorin** [pixijs/pixi.js#5805]
As far as I understand, `pointermove` event should always fire, even when the mouse is outside the hit area of a DisplayObject. I'm experiencing issues with this event where in a certain configuration it does not. The event is only fired if the mouse is over the object itself or over a direct parent. Here is a relatively minimal example: https://jsfiddle.net/tgbjy9of/3/

If I omit the Containers from the example, it works as expected. The same problem is also seen on `pointerupoutside`.

Is there anything that can be done as a workaround or is this an actual bug?

**Comment by djmisterjon** [comment]
i think what you are looking for is global on move ?
`  app.renderer.plugins.interaction.on('pointermove' , pointermove_global );`

**Comment by juregregorin** [comment]
That is a workaround, but one I don't like. I really don't like the idea of passing the interaction system across multiple classes, especially when it shouldn't be necessary. And as far as I know, there's no other way to access the interaction system globally.

**Comment by ivanpopelyshev** [comment]
> That is a workaround, but one I don't like. I really don't like the idea of passing the interaction system across multiple classes

1. There was an idea that interaction should be created by you (dev) only if its needed, and then you can do whatever you want with global events. Unfortunately for me, it didnt pass and interaction is still deep inside renderer, but its ok to get it from there, make a global and use it.

2. Maybe its possible to hack https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/InteractionManager.js#L1349  to do that thing.

Hope you can help us with it and maybe provide a hack workaround. Good Luck!

**Comment by juregregorin** [comment]
I think I found the issue.
https://github.com/pixijs/pixi.js/blob/4e1ca79a916ba266f23c9ab653251b935490d45c/packages/interaction/src/InteractionManager.js#L1035
If `hitTestChildren` is never set to false, everything works as expected. There's probably a minor perfomance penalty for this, but maybe `hitTestChildren` should be only set to false based on `moveWhenInside`. Seems like that would be pretty reasonable.

**Comment by ivanpopelyshev** [comment]
IS it connected to #5695 somehow? @themoonrat I think this need your attention.

**Comment by juregregorin** [comment]
@ivanpopelyshev Thank you, `containsPoint` works perfectly!
