### ISSUE TITLE
@GoodBoyDigital I came across a problem with making arcs with PIXI.Graphics, why only 40 segs ?

### ISSUE THREAD

**Issue by s4l4x** [pixijs/pixi.js#5807]
@GoodBoyDigital I came across a problem with making arcs with PIXI.Graphics, why only 40 segs ?

http://codepen.io/Elyx0/pen/VLLEVb

If I up this number in arc prototype, I get a much smoother rendering, could it be possible to make this var public to set it before drawing ?

_Originally posted by @Elyx0 in https://github.com/pixijs/pixi.js/issues/1086#issuecomment-98384415_

**Comment by s4l4x** [comment]
I'm not sure if the above issue is the same as mine. Here is an example I put together that illustrates the issue: 

https://codesandbox.io/s/pixijs-arc-example-ifsdy

**Comment by s4l4x** [comment]
Here's the code for reference: 

```import * as PIXI from "pixi.js";

var renderer = PIXI.autoDetectRenderer({
  width: window.innerWidth,
  height: window.innerHeight,
  backgroundColor: 0xd17277,
  antialias: true

  // FIXME: Uncommenting these no longer shows arc
  // resolution: window.devicePixelRatio,
  // autoDensity: true,
});

document.body.appendChild(renderer.view);

const stage = new PIXI.Container();

var arc = new PIXI.Graphics();
arc
  .lineStyle(10, 0xffffff)
  .arc(renderer.width / 2, renderer.height / 2, 20, 0, Math.PI * 2 * 0.7);
stage.addChild(arc);

var arc2 = new PIXI.Graphics();
arc2
  .lineStyle(10, 0xffffff)
  .arc(renderer.width / 2, renderer.height / 2, 100, 0, Math.PI * 2 * 0.7);
stage.addChild(arc2);

renderer.render(stage);```

**Comment by bigtimebuddy** [comment]
Please check out this example:
https://pixiplayground.com/#/edit/iNs872TvTYfl4cvhc6dzB

There are two issues, one is the resolution. Your curves are showing up but they are offscreen. You need to make sure you use `renderer.screen.width` and `renderer.screen.height` to get the proper internal dimensions, not just the pixel dimensions of the renderer.

Second, there are some options for making curves be adaptive, which will give you much smoother results at the expense of more segments. Look up `PIXI.GRAPHICS_CURVES` in the [documentation](http://pixijs.download/dev/docs/PIXI.html#.GRAPHICS_CURVES)

**Comment by s4l4x** [comment]
Thanks @bigtimebuddy for the quick response! Much appreciated!
