### ISSUE TITLE
ObservablePoint enumerable cb scope

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#5810]
hi , is there any reason why your keep **cb** and **scope** enumerable inside **ObservablePoint** ?
I think it should be not enumerable, to avoid  a `Converting circular structure to JSON` to allow stringify ObservablePoint in factory data ex:`JSON.stringify(this.position)`.
![image](https://user-images.githubusercontent.com/24865815/59963874-fc5e8880-94c6-11e9-9057-31c0df656c14.png)

Will it cause problems in the core?
Do i need start a PR or you can do it ?
thanks

**Comment by ivanpopelyshev** [comment]
In one of my pixijs forks I use FlatTransform thingy that has all the fields that are required for transform: https://github.com/gameofbombs/gobi/blob/master/src/core/math/FlatTransform2d.ts#L2

Yes, we do not address persistance/serialization issues in vanilla PixiJS.

**Comment by ivanpopelyshev** [comment]
ObservablePoint has other problems: its not a Point and we dont know what to do when we `clone()` it, that's why there is no `clone` method. Its a gray area and I think we wont accept any simple PR's to fix that.

**Comment by djmisterjon** [comment]
> In one of my pixijs forks I use FlatTransform thingy that has all the fields that are required for transform:

lol it exactly what a want avoid to do again, manually do this, `i know am a ugly lazy dev`.

i use many kind of clone experiment in my projet.
```javascript
    clone(updateBefor){
        return new this.constructor(this.dataBase,this._textureName);
        /*const jsonValues = JSON.parse(JSON.stringify(this));
        return new this.constructor(jsonValues._dataBaseName,jsonValues._textureName,jsonValues.dataValues);*/
    };
```

I guess the creation of a template like you say is the best solution for now, but not really productive
My general idea is to be able to create a JSON factory quickly with all settable values by doing something like that mayby.
```javascript
JSON.stringify({
    p:{ euler, proj, position3d, scale3d, pivot3D,position,pivot,skew,scale,color,alpha,tint},
    d:{ euler, proj, position3d, scale3d, pivot3D,position,pivot,skew,scale,color,alpha,tint},
    n:{ euler, proj, position3d, scale3d, pivot3D,position,pivot,skew,scale,color,alpha,tint},
})
```

**Comment by djmisterjon** [comment]
ok i succeed to get something clean
example here C is a container.
in this snippet, i just need add prop we want in **flatter** 
And set a **circular** variable.

it seems to me clean and acceptable ? am open to suggest plz.
```javascript
    initializeLegacy(C=this.child){
        const flatter = {
            _own:["renderable","visible","zOrder","alpha","proj","interactive"], // keep props
            _3d:["euler","position3d","pivot3d","scale3d","proj"], // keep getter 3d
            _2d:["position","pivot","scale","skew"], // keep getter 2d
        };
        const circular = ["ObservableEuler","ObservablePoint","Matrix3d","TransformStatic"]; // class to remove
        const factory = {};
        Object.values(flatter).flat().forEach(key => {
            const prop = factory[key] = C[key];
            if(circular.contains(prop.constructor.name)){
                Object.defineProperty(prop, 'cb', { enumerable: false });
                Object.defineProperty(prop, 'scope', { enumerable: false });
            }else
            if(prop.constructor.name === "Projection3d"){
                for (const _key in prop) {
                    if (circular.contains(prop[_key] && prop[_key].constructor.name) ) {
                        Object.defineProperty( prop, _key, { enumerable: false });
                    };
                };
            };
        });
    };
```
So the console.log give this
`JSON.stringify(factory, null, '\t')`
```json
"{
	"renderable": true,
	"visible": true,
	"zOrder": 71.63822416066955,
	"alpha": 1,
	"proj": {
		"_enabled": true,
		"_projID": 26,
		"_currentProjID": 26,
		"_affine": 0,
		"affinePreserveOrientation": false,
		"scaleAfterAffine": true,
		"cameraMatrix": null,
		"_cameraMode": false
	},
	"interactive": true,
	"euler": {
		"_quatUpdateId": 0,
		"_quatDirtyId": 0,
		"_sign": 1,
		"_x": 0,
		"_y": 0,
		"_z": 0,
		"quaternion": {
			"0": 0,
			"1": 0,
			"2": 0,
			"3": 1
		}
	},
	"position3d": {
		"_x": 7.642325247998559,
		"_y": 0,
		"_z": 71.63822416066955
	},
	"pivot3d": {
		"_x": 0,
		"_y": 0,
		"_z": 0
	},
	"scale3d": {
		"_x": 1,
		"_y": 1,
		"_z": 1
	},
	"position": {
		"_x": 0,
		"_y": 0
	},
	"pivot": {
		"_x": 0,
		"_y": 0
	},
	"scale": {
		"_x": 1,
		"_y": 1
	},
	"skew": {
		"_x": 0,
		"_y": 0
	}
}"
```
![image](https://user-images.githubusercontent.com/24865815/59967306-24191500-94f6-11e9-8d1f-7c0c1d1f6f8e.png)

@ivanpopelyshev 
if you can allow me to put a PR for disable enumerability in Projection3d class
this will allow me to remove the `for (const _key in prop) ` in my method.
I don't think those class are important because we have access in parent, and they are same.
`c.euler === c.proj.euler // return true;` ! 
![image](https://user-images.githubusercontent.com/24865815/59967334-722e1880-94f6-11e9-8ed8-ee894f9cb342.png)
except if you see a disadvantage or need a time of reflection.

**Comment by djmisterjon** [comment]
solved thanks
https://github.com/djmisterjon/pixi-factory
