### ISSUE TITLE
Type inconsistency across MeshGeometry and Buffer

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#5814]
In `@pixi/mesh/MeshGeometry.js`, the constructor's documentations says that the `vertices`, `uvs`, and `index` buffers can be provided as two types: `TypedArray` or `number[]`.

However, its code isn't written to support the `number[]` type.

```
const verticesBuffer = new Buffer(vertices);
const uvsBuffer = new Buffer(uvs, true);
const indexBuffer = new Buffer(index, true, true);
```
This is since the `Buffer` constructor does not except a `number[]` type; however, if the user provides `number[]` array, then the buffer created will have an invalid type.

There are two solutions to this:

* Correct the documentation to make `vertices`, `uvs`, and `index` data be given as a `TypedArray`.

* Change the constructor's code to the following:

```
const verticesBuffer = Buffer.from(vertices);
const uvsBuffer = Buffer.from(uvs, true);
const indexBuffer = Buffer.from(index, true, true);
```

**Discovery Notes:**
The following is how I got to this error. 

```
const geom = new PIXI.MeshGeometry([
  0, 0,
  0, 100,
  100, 100,
  100, 0
], [
  0, 0,
  0, 1,
  1, 1,
  1, 0
], [
  0, 1, 2, 3, 0
]);
const mesh = new PIXI.Mesh(geom,
  new PIXI.MeshMaterial(tex), undefined,
  PIXI.DRAW_MODES.TRIANGLE_STRIP);
```

On adding the mesh created and rendering it, PixiJS (on my computer) complained that `unsupported index buffer type: int32` in `GeometrySystem.draw`.

This was because the index buffer was automatically converted into an unsigned integer buffer (from `number[]`); however, the index buffer is supposed to be an `Uint16Array` instead.

NOTE: `Buffer` cannot accept an `number[]` type because WebGL's `bufferData` doesn't accept that.

### Environment

- **`pixi.js` version**:  5.04

**Comment by SukantPal** [comment]
To bypass this problem, end users will have to use:

```
new MeshGeometry(Uint32Array.from([...]), Uint32Array.from([...]), Uint16Array.from([...]));
```

**Comment by ivanpopelyshev** [comment]
That's a bug, it breaks compatibility with pixi-v4 Mesh. The problem is that it uses `byteLength` somewhere inside.

I forgot to report that, thank you for reminding me!

**Comment by ivanpopelyshev** [comment]
We cant even use `from`, because we need Uint16/Uint32 for indices and Float32 for everything else.

**Comment by SukantPal** [comment]
Yeah, I forgot that `Buffer.from` always uses `Float32`. However, we could fix that in the constructor by using,

```
this.index = new Buffer((index instanceof Array) ? Uint16Array.from(index) : index), true, true);
```

**Comment by SukantPal** [comment]
> That's a bug, it breaks compatibility with pixi-v4 Mesh. The problem is that it uses `byteLength` somewhere inside.
> 
> I forgot to report that, thank you for reminding me!

Could you please explain a little more? I am kind of interested in becoming a contributor to this project.

**Comment by ivanpopelyshev** [comment]
I've sent pixijs slack invite to your email that is specified in github profile.
