### ISSUE TITLE
Textures from base64-encoded data URIs reports wrong validity

### ISSUE THREAD

**Issue by mofnire** [pixijs/pixi.js#5816]
### Expected Behavior

`PIXI.Texture.from('data:image/svg+xml;base64,...').valid` is expected to be `false` If it is not cahched.

### Current Behavior

It returns true regardless of the loading state.

### Possible Solution

As far as I known, this issue is caused by the SVGResource L20. Canvas elements created at that line has the non-zero width / height, thus the method `#valid` reports true even if a SVG is not loaded yet.

https://github.com/pixijs/pixi.js/blob/c4968736f2c6e928097ef7e903e14e86e6f1de01/packages/core/src/textures/resources/SVGResource.js#L20

https://github.com/pixijs/pixi.js/blob/c4968736f2c6e928097ef7e903e14e86e6f1de01/packages/core/src/textures/resources/Resource.js#L115-L118

Thus, resetting the canvas width/height explicitly solves this issue.
At least, it worked for me.
```javascript
export default class SVGResource extends BaseImageResource
{
    constructor(source, options)
    {
        options = options || {};
+       const canvas = document.createElement('canvas');
+       canvas.width = canvas.height = 0;
+       super(canvas);
-       super(document.createElement('canvas'));
```

### Steps to Reproduce

Please see the following playground:
https://www.pixiplayground.com/#/edit/_2bneblE7~49HhtvsviJZ

### Environment

- **`pixi.js` version**:  _5.0.4_
- **Browser & Version**: _Chrome 75.0.3770.100_
- **OS & Version**: _Windows 10_
- **Running Example**: _https://www.pixiplayground.com/#/edit/_2bneblE7~49HhtvsviJZ_

**Comment by ivanpopelyshev** [comment]
Yes, it shouldn't be valid before we actually know its size. `super(canvas)` isn't good idea, I'll think how to modify your PR, it should look better.

**Comment by ivanpopelyshev** [comment]
Btw, you are on fire, 4 PR's in short time 👍

**Comment by mofnire** [comment]
> Yes, it shouldn't be valid before we actually know its size. `super(canvas)` isn't good idea, I'll think how to modify your PR, it should look better.

OK, I got it.

**Comment by mofnire** [comment]
> Btw, you are on fire, 4 PR's in short time 👍

Thank you for making PixiJS 👍 
Saved me a lot.

**Comment by mofnire** [comment]
The PR is merged 🎉
