### ISSUE TITLE
No v5 tutorials

### ISSUE THREAD

**Issue by madroneropaulo** [pixijs/pixi.js#5818]
I can't find any good v5 resource for beginners. The community tutorials are outdated, and many methods marked as *deprecated

**Comment by bigtimebuddy** [comment]
We are working on new tutorials for v5, but would love to see the community make more. There’s a huge need for this type of thing.

One place where I’ve seen good beginner tutorials is CJ Gammon’s YouTube series https://m.youtube.com/watch?v=eKsTVZKMeuI

**Comment by ivanpopelyshev** [comment]
I'm working on https://github.com/ivanpopelyshev/pixi-starfighter and on `v5` section of our wiki : https://github.com/pixijs/pixi.js/wiki
