### ISSUE TITLE
If DisplayObject#hitArea accepts a PIXI.HitArea alternative, might be useful?

### ISSUE THREAD

**Issue by mofnire** [pixijs/pixi.js#5823]
So far, I could not find the `PIXI.HitArea` alternative for PixiJS v5. And `DisplayObject#hitArea` accepts the following classes or their derived classes only:

- `PIXI.Rectangle`,
- `PIXI.Circle`,
- `PIXI.Ellipse`,
- `PIXI.Polygon`, and
- `PIXI.RoundedRectangle`.

Thus, in my case, I changed the super class of my custom hit-area classes to `PIXI.Rectangle`.
As far as I known, all the codes which use `DisplayObject#hitArea` must not require anything other than the methods `#contains(x, y)` and `#clone()` because these are the only methods the union type of the above 5 classes has.

Is it an acceptable idea introducing the virtual JSDoc comments(*1) that define an `PIXI.HitArea` interface and adding it to the `@param` of `DisplayObject#hitArea`? Namely, something looks like this:
```
/**
 * Interface for classes that represent a hit area.
 *
 * @interface PIXI.HitArea
 */

/**
 * Checks whether the x and y coordinates given are contained within this Rectangle
 *
 * @method
 * @name PIXI.HitArea#contains
 * @param {number} x - The X coordinate of the point to test
 * @param {number} y - The Y coordinate of the point to test
 * @return {boolean} Whether the x/y coordinates are within this Rectangle
 */


export default {
    /**
     * Interaction shape. Children will be hit first, then this shape will be checked.
     * Setting this will cause this shape to be checked in hit tests rather than the displayObject's bounds.
     *
     * @example
     * const sprite = new PIXI.Sprite(texture);
     * sprite.interactive = true;
     * sprite.hitArea = new PIXI.Rectangle(0, 0, 100, 100);
     * @member {PIXI.HitArea|PIXI.Rectangle|PIXI.Circle|PIXI.Ellipse|PIXI.Polygon|PIXI.RoundedRectangle}
     * @memberof PIXI.DisplayObject#
     */
    hitArea: null
}
```

[*1 Please refer to the virtual comment section of the JSDoc manual](https://jsdoc.app/tags-interface.html)

### Environment

- **`pixi.js` version**: _5.0.4_
- **Browser & Version**: _Chrome 75.0.3770.100_
- **OS & Version**: _Windows 10_
- **Running Example**: _None_

**Comment by mofnire** [comment]
Btw, `AccessibilityManager` seems to be assuming that the `DisplayObject#hitArea` has properties including `width`. If this is the case, I might be wrong about the union type things.

https://github.com/pixijs/pixi.js/blob/dd9c99080505b7f8a39343a82ec06b04fea0ad51/packages/accessibility/src/AccessibilityManager.js#L321-L325

**Comment by ivanpopelyshev** [comment]
I agree that we need an interface like that.

**Comment by mofnire** [comment]
> I agree that we need an interface like that. 
> We already have problems with `IPoint = Point|ObservablePoint`

Thank you for the quick response.
I am glad you agreed.

> Accessability does not support all shapes, maybe.

I got it 👍
