### ISSUE TITLE
Rendering systems are getting binded twice to contextChange signal

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#5825]
I'm not sure if my doubt is right, but I wanted to let you guys know.

The `System` constructor in `@pixi/core` attaches its instance to the `renderer.runners.contextChange` signal. However, the `Renderer#addSystem` attaches the system to all runners; hence, I think each system being added is attached twice to the `contextChange` signal.

```
// Renderer.js #addSystem()
for (const i in this.runners)
 {
  this.runners[i].add(system);
 }
```

```
// System.js #constructor
this.renderer.runners.contextChange.add(this);
```

Was this intended or is this a bug?

**Comment by bigtimebuddy** [comment]
This seems like a bug. Would welcome a PR to address.

**Comment by SukantPal** [comment]
> This seems like a bug. Would welcome a PR to address.

Hey, I've made a PR, check it out!
