### ISSUE TITLE
How does the pivot work?

### ISSUE THREAD

**Issue by tleunen** [pixijs/pixi.js#583]
I'm trying to rotate a sprite at its center, but I don't understand how the pivot work. Could anyone explain me?

If I want to rotate at its center, for me it's natural to do `sprite.pivot.set(sprite.width/2, sprite.height/2);` but obviously it doesn't work ^^

I've setup an example: http://jsfiddle.net/dfbAn/
This uses PIXI 1.4.3 as I can't find the latest version hosted somewhere. And also because I can't use PIXI 1.5 because of #551 

Thanks.

**Comment by bharal** [comment]
Pivot is really really complicated - can someone update the documents with the details of what it actually does, and where its reference point is?

From the examples given here, it seems that setting a pivot at x,y will let a shape rotate around that point WHILE ALSO meaning that the shape's top-left co-ord changes by -x, -y.

This seems like really odd behaviour, but it seems the intended behaviour, so, fine. But could you be clear about this in the doco? Or just add a method that sets the pivot point and *doesn't* change the top-left coord, which is really what anybody who sets pivot wants?

**Comment by ivanpopelyshev** [comment]
There's no such method. 

I have the explanation: "pivot" in local coordinates pinned to "position" in world coordinates. Its not about rotation, it is also about scale.

If you want the behaviour you explained, then if pivot is (x,y), add (-x, -y) to position.

**Comment by chenyong** [comment]
Still can't understand PIVOT although I found a long explanation in https://stackoverflow.com/a/39021592/883571

Anyone please draw it? It's hard to understand such a concept with a decent example.

**Comment by chenyong** [comment]
Got my own version,

This is a basic example when **pivot** is `(0, 0)`, a shape is placed on its container:

![normal](https://user-images.githubusercontent.com/25790987/35369925-abe8ad8a-01c5-11e8-9971-ce8f0fbcec94.png)

Confusing part is, **pivot is totally different from transform origin**, which is used by CSS transform. Pivot is the position on the shape, not on container:

![pivot](https://user-images.githubusercontent.com/25790987/35369930-b0832db6-01c5-11e8-90a0-74adfd3920e6.png)

As a shape with non-zero pivot placed in a container, like a thumbtack, the pivot point is nailed down to the position point. If it rotates, it will circle around this fixed point:

![rotate](https://user-images.githubusercontent.com/25790987/35369938-b74d2674-01c5-11e8-818a-3692be5e1c5b.png)

Meanwhile this example also shows pivot influences the visual position of the shape in container.

Not tried skewing...
