### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by protectedvar** [pixijs/pixi.js#5830]
https://pixijs.io/examples/#/filters-basic/blur.js

This example not works..
Linux

**Comment by ivanpopelyshev** [comment]
canvas or WebGL or WebGL2?

**Comment by protectedvar** [comment]
following link i have no filters... my browser automaticaly switch to CanvasRenderer

**Comment by ivanpopelyshev** [comment]
yeah, probably because v5 requires `stencil`. If there's no stencil in browser graphics driver, then pixi falls back to canvas.
