### ISSUE TITLE
Wrong size of Pixi.Graphics() when using PIXI.Sprite() as container

### ISSUE THREAD

**Issue by camilacanhete** [pixijs/pixi.js#5832]
See more: https://codepen.io/anon/pen/jjwero
Possibly related to #5707

### Expected Behavior
Parent (PIXI.Sprite()) is 100x100 
Child (Pixi.Graphics()) is 50x50

### Current Behavior
Parent (PIXI.Sprite()) is 100x100
Child (Pixi.Graphics()) should be 50x50, but the yellow rectangle appears much bigger than it should

- **`pixi.js` version**: 5.0.4
- **Browser & Version**: Chrome 75
- **OS & Version**: Mac OSX

**Comment by ivanpopelyshev** [comment]
```
target.width = 100;
target.height = 100;
```

And thus, you've changed the sprite scale, and it affects all children. Its the same behaviour as in Adobe Flash.

I've tried to  PR to add `size` to sprite one or two times but it wasnt approved.

Workaround: use extra container for it.

**Comment by ivanpopelyshev** [comment]
Working as intended.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/v4.x/src/core/sprites/Sprite.js#L510

**Comment by camilacanhete** [comment]
@ivanpopelyshev But the child isn't 100x100 pixels neither. It's much bigger than the parent.
