### ISSUE TITLE
"pointerout" event not fired on a display object if its parent has a hit area

### ISSUE THREAD

**Issue by mofnire** [pixijs/pixi.js#5837]
### Expected Behavior

The `pointerout` event fired on a display object even if its parent has a hit area.

### Current Behavior

Not fired.

### Possible Solution

I think the same approach as Mr. Dave Moore took for fixing the issue #5135 is applicable.
Removing `hitTestChildren` fixes this issue. It worked for me. 

https://github.com/pixijs/pixi.js/blob/4d71fa06ea787d81651fc3e624610ccfc3c3f457/packages/interaction/src/InteractionManager.js#L1023-L1035

### Steps to Reproduce

Please see the following playgounds:
- With a hit area (The `pointerout` event not fired)
https://www.pixiplayground.com/#/edit/BaVVcoIBfgl~mbH3v2TeW
- Without a hit area (Works as expected)
https://www.pixiplayground.com/#/edit/v_xmiGcKv~2uGMkp_Naa3

### Environment

- **`pixi.js` version**: _5.0.4_
- **Browser & Version**: _Chrome 75.0.3770.100_
- **OS & Version**: _Windows 10_
- **Running Example**: _https://www.pixiplayground.com/#/edit/BaVVcoIBfgl~mbH3v2TeW_

**Comment by ivanpopelyshev** [comment]
Related:

#5805
#5695
#4608

**Comment by jame10103er** [comment]
``

**Comment by mofnire** [comment]
I decided not to use the hit area as suggested in #5805. And working fine so far!
