### ISSUE TITLE
Mouseout event does not have a target

### ISSUE THREAD

**Issue by JKAnderson409** [pixijs/pixi.js#5850]
There was an issue similar to this a little over a year ago with a hack suggested of binding the function to a sprite. But in my implementation I have input handlers that need to handle mouse and key events that may apply to one of many sprites while sprites are sporadically added from a server.

### Expected Behavior

When a user moves their mouse over a DisplayObject the InteractionEvent passed to the callback function assigned to the "mouseover" event has a target that corresponds to the DisplayObject. When the user moves their mouse out of the bounds of the DisplayObject that same InteractionEvent target is passed to the callback function assigned to the "mouseout" event.

### Current Behavior

The correct InteractionEvent target is passed to the "mouseover" callback but the target of the InteractionEvent passed to the "mouseout" callback is undefined.

### Possible Solution

I solved this in my implementation by using a single function for "mouseover" and "mouseout" and declaring a variable that represents the DisplayObject that is being moused over. If the variable is null I can assign it to the target and make the correct changes. If the target is undefined (meaning this is a "mouseout") I can undo those changes and set the variable to null. This works because in my case there is logically only one relevant DisplayObject that would be moused over at a time. It would be nice if the API handled this so that I could just switch the settings on and off and it seems that a "mouseout" should have a target.

### Steps to Reproduce

Set a single function as the callback for both "mouseover" and "mouseout" and console.log the target on the InteractionEvent parameter.

### Environment

- **`pixi.js` version**:  5.0.4
- **Browser & Version**: Firefox Developer 68, Chrome 75
- **OS & Version**: MacOS Mojave 10.14.5

**Comment by ivanpopelyshev** [comment]
Maybe related : #5695 
Try pixijs.download/bugfix/touchmove-target/pixi.js

**Comment by JKAnderson409** [comment]
Thank you, I will try it when I get a chance. That PR looks like it was made for touch events but if it makes the same changes to mouse events that would be nice.

**Comment by themoonrat** [comment]
@JKAnderson409  Would it be possible to take a look at the latest version of PixiJS and see if your issue is resolved after that PR? Thanks!

**Comment by JKAnderson409** [comment]
Sure thing, I am restructuring my project today so I will try it out as soon as I have a chance to update PIXI.

**Comment by JKAnderson409** [comment]
Sorry I let this sit for so long. I am closing this issue, thank you for addressing it.
