### ISSUE TITLE
Failed to compile with react-scripts

### ISSUE THREAD

**Issue by karmux** [pixijs/pixi.js#5854]
My React and Pixi app was using Webpack and Babel directly and built without issues. Then I decided to try using `react-scripts` instead and app doesn't run in development anymore (haven't tried to build for production). I have no custom config for `react-scripts`.

### Expected Behavior

Pixi application builds with `react-scripts` like it does with Webpack and Babel setup.

### Current Behavior

If running `npm run start` (which runs `react-scripts start`) then following error happens:

```
Failed to compile
./node_modules/@pixi/loaders/lib/loaders.es.js
Attempted import error: 'resource-loader' does not contain a default export (imported as 'ResourceLoader').
This error occurred during the build time and cannot be dismissed.
```

### Steps to Reproduce

1. Import following module:

```
import * as PIXI from 'pixi.js';

export default () => {
    return null;
}
```
2. Run `react-scripts start`

### Environment

- **`pixi.js` version**: 5.0.4
- **`react-scripts` version**: 3.0.1
- **Browser & Version**: Chrome 75
- **OS & Version**: Manjaro Linux
- **Running Example**: `react-scripts start`

**Comment by karmux** [comment]
At least for my app Pixi is incompatible with `resource-loader` 3.0.0 that was released during my `react-scripts` migration. It works well with `resource-loader` 2.2.4.

**Comment by bigtimebuddy** [comment]
We accidentally pushed out a breaking change to resource-loader and then fixed the problem. Should be fixed now. v3 of resource-loader will not work yet.

**Comment by karmux** [comment]
App runs again with latest and fixed `resource-loader`. Thank you.
