### ISSUE TITLE
pixi-layers doesn't work with canvas renderer context

### ISSUE THREAD

**Issue by ViktorLiubenok** [pixijs/pixi.js#5855]
After moving on Pixi v5 we see a problem with pixi-layers. ParentGroup property doesn't work. Does pixi-legacy support pixi-layers?

pixi.js version: 5.0.4

**Comment by themoonrat** [comment]
I'd raise the question on the pixi-layers page rather than here :) 
https://github.com/pixijs/pixi-layers

**Comment by ivanpopelyshev** [comment]
I believe I fixed it 9 days ago, please take latest version from that repo `dist` folder and provide more details. It should work.

**Comment by ViktorLiubenok** [comment]
Works fine! Thank you very much!

**Comment by tabathapictou** [comment]
👌
