### ISSUE TITLE
sprites loaded doesn't show ? work only in canvas mode. [CanvasRenderer﻿, webgl Render﻿er﻿﻿﻿﻿]

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#5860]
this demo worked from 26june (~6 days ago).
Since it can't show sprites in `webgl mode`.
It work only if we set the app in `canvas mode`.

Sorry, i know it a complexe demo, but it the only one i can show.
In webgl mode i get no error in console, so i can't track what happens here.

If you `comment` the `line 55` or set `forceCanvas:false`, sprites will disappear, but `spriteText` and `graphics` work fine.

https://www.pixiplayground.com/#/edit/KLahFCph5MmXIFST~LDzt

gl and thanks

**Comment by djmisterjon** [comment]
Canvas mode 
![image](https://user-images.githubusercontent.com/24865815/60476597-34459880-9c4a-11e9-998a-c7e4e5b64606.png)
webGl mode
Sprite existe, bounds are fine, but just no showed ! 
![image](https://user-images.githubusercontent.com/24865815/60476639-58a17500-9c4a-11e9-92b0-a814a9598c3f.png)

**Comment by JetLua** [comment]
It may be related to [pixi-projection](https://github.com/pixijs/pixi-projection).

https://pixijs.io/examples/#/plugin-projection/basic.js

@ivanpopelyshev

**Comment by djmisterjon** [comment]
hoho, yes you maybe true, last commit on `pixi-projection` are from `9 days ago`
so maybe it a new commit in `pixijs` broke `pixi-projections` or something missing :) thats to point this.

**Comment by ivanpopelyshev** [comment]
Fixed

**Comment by djmisterjon** [comment]
thanks for this
