### ISSUE TITLE
How do I properly adjust rectangle's width after container resize?

### ISSUE THREAD

**Issue by dorsharon** [pixijs/pixi.js#5863]
I'm trying to deal with responsiveness, and I'm creating a complex Gantt with pixi.
Whenever the container is resized and the stage's width changes, I'm trying to resize all my rectangles in the Gantt accordingly, so they'll still be in that correct place timeline-wise.

When I tried to simply change their scale, it wasn't enough, because their position had to be changed too.

Changing their width seem to change their scale as well, so is there another way to do this?

**Comment by ivanpopelyshev** [comment]
extra containers. Or you can rewrite transforms and how width/height is defined, PIXI tree is based on Flash stage, its not suited for many tasks. Its ok to rewrite it once you know how it works :)

**Comment by themoonrat** [comment]
Closing as you have an answer! Please create a new issue if there is anything else you need help with. Thanks!
