### ISSUE TITLE
Italic PIXI.Text is cut off

### ISSUE THREAD

**Issue by martinboksa** [pixijs/pixi.js#5864]
The right edge of italic PIXI.Text is cut off. 
https://www.pixiplayground.com/#/edit/5c0kJBUwHzWl29oH_aIZh

Any simple workaround to fix it, please? 

<img width="477" alt="Screenshot 2019-07-02 at 11 33 04" src="https://user-images.githubusercontent.com/4490694/60503270-a4423600-9cbf-11e9-8603-801829ee3a59.png">
<img width="425" alt="Screenshot 2019-07-02 at 11 33 07" src="https://user-images.githubusercontent.com/4490694/60503312-b58b4280-9cbf-11e9-8bed-bdfbfb8919fb.png">

### Environment

- **`pixi.js` version**: 4.8.8
- **Browser & Version**: Chrome 75.0.3770.100
- **OS & Version**:  Mac Mojave 10.14.5

**Comment by ivanpopelyshev** [comment]
According to https://github.com/pixijs/pixi.js/blob/dev/packages/text/src/Text.js#L128 , there's padding but its added to all sides, not just right.

**Comment by themoonrat** [comment]
Padding is the only solution. We make a guess at how big the canvas has to be before drawing text to it, and 99% of the time it's right. But occasionally.... not so. Add padding to fix, and turn on trim if you find you're getting 'excessive' padding

**Comment by martinboksa** [comment]
Thanks. It works. I don't suppose it will be solved so I close the issue.
