### ISSUE TITLE
Problem getting image from toDataURL when using masks

### ISSUE THREAD

**Issue by balance80** [pixijs/pixi.js#5865]
# Expected Behavior
![image](https://user-images.githubusercontent.com/481780/60508221-4ebf5680-9cca-11e9-9752-d02b25003ea2.png)

The toDataURL function should return an image of a visible, but masked bunny as seen above.

### Current Behavior
No bunny is visible when mask is enabled :(

### Steps to Reproduce
Mask turned off, toDataURL returns an image of a visible bunny and the mask: https://www.pixiplayground.com/#/edit/0XYVrK3mY_DRg6G8bEI2c

See: // bunny.mask = mask;

Mask turned on, no image of masked visible bunny is returned:
https://www.pixiplayground.com/#/edit/24fENadi8vBrhMeI6KCSz

See: bunny.mask = mask;

### Environment
Pixi v5.0.4
Chrome
Windows

**Comment by ivanpopelyshev** [comment]
```
previewRenderer.view.toDataURL();
```

There's no guarantee that it will work. The onyl way to get something for sure is to call `readPixels` just after frame is rendered or to call it on temporary framebuffer. 

You can use `PIXI.extract` plugin or copy its code and investigate how it works, making your own version.
https://github.com/pixijs/pixi.js/blob/dev/packages/extract/src/Extract.js#L167

**Comment by balance80** [comment]
I pulled code from extract and added postdivide. Rendering directly to canvas, no toDataURL, even added the code into the postrender event, but still no luck.

Updated playground here:
https://www.pixiplayground.com/#/edit/Ittldpf0t~nYxQ4lttdS0

Is there anything more I can do here, or is this a lost cause?

**Comment by ivanpopelyshev** [comment]
btw i added postdivide here: #5875 . Thanks, now i'll look into it!

**Comment by ivanpopelyshev** [comment]
OK, so, apparently its another `generateTexture` with `crop rectangle`+`filter/mask` problem.

I'm sorry, @balance80, but I cannot help you because I spent too much time on that kind of issues and my advice is that: make your own `generateTexture` , control whats happening with transforms , temp parent.

When I tried to fix all those issues in that PR you found, it was rejected. I've spent two complete days on  it. I do not want to go there again.

I cannot guarantee that `generateTexture` works with crop correctly with masks and filters.

**Comment by ivanpopelyshev** [comment]
Its not related to extract, its pure generateTexture problem, I can reduce that example and ask the rest of the team to investigate it.

Workaround is to copy generateTexture and use RenderTexture directly, find which combination of transforms works for your case.

**Comment by ivanpopelyshev** [comment]
Here we go: https://www.pixiplayground.com/#/edit/jcJbkTkp5xbGNraluSLwd

Now someone else can try to find whats wrong with it.
