### ISSUE TITLE
PixiJS Examples Crashed

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixi.js#5879]
Use the `Latest Development` version of pixi.js.
https://pixijs.io/examples/#/demos-basic/container.js

**Comment by bigtimebuddy** [comment]
This is most likely related to merging #5877 

Ping @SukantPal

**Comment by bigtimebuddy** [comment]
We're on it. Thanks @JetLua for reporting so quickly.

**Comment by bigtimebuddy** [comment]
Merged fix. Should be fixed after build is available.
