### ISSUE TITLE
advice for scaling bitmap fonts & smoothing

### ISSUE THREAD

**Issue by alexfoxy** [pixijs/pixi.js#588]
Heya,

I'm using a bitmap font rendered at 70px which looks great large but when I use smaller font sizes the text starts to look ugly : 

![screen shot 2014-02-16 at 12 17 53](https://f.cloud.github.com/assets/151772/2180209/ec4d1f58-9704-11e3-8045-7ea4fd865e85.png)

Is there any way to improve this? Rendering different sprites at different font sizes is an option but obviously it's not ideal if you want to have many different font sizes.

Thanks!

**Comment by luwen-huang** [comment]
could you confirm that this is how we would do it?

`PIXI.MIPMAP_TEXTURES = true;`
then for each bitmap font created, do:
`var bitmapText = new PIXI.extras.BitmapText(data.text, {font: '10px myCustomFont'})`
`bitmapText.mipmap = true`

is that right?

**Comment by ivanpopelyshev** [comment]
That wont work. you have to manually adjust '10px' that way it looks good. The number must be somewhere between 0.5x-2x of real resolution
