### ISSUE TITLE
CanvasRender: Tint not applied to Graphics pixi-legacy.js v5

### ISSUE THREAD

**Issue by dougmcintyre-pipkins** [pixijs/pixi.js#5889]
### Expected Behavior
Tint should be applied to Graphics

### Current Behavior
Tint does alter the graphics color - box should be red.

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/b5nFl_L2Zmc~3br3IV9iZ

### Environment
- **`pixi-legacy.js` version**: 5.*
- **Running Example**: https://www.pixiplayground.com/#/edit/b5nFl_L2Zmc~3br3IV9iZ

**Comment by phpositive** [comment]
Not sure if this is related somehow, but also crashes on NineSlicePlane

[https://www.pixiplayground.com/#/edit/WF0gD7FRlpVCtvUB8iuWJ](url)
