### ISSUE TITLE
Why does Renderer#resize not use super to access AbstractRenderer#resize?

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#5892]
I wonder why we are using the following in `Renderer#resize`:

```
AbstractRenderer.prototype.resize.call(this, screenWidth, screenHeight);
```
Why can't we simplify it as:
```
super.resize(screenWidth, screenHeight);
```

Is this related to a bug in ES6 or what? Since I come from Java, this looks like an anti-pattern.

**Comment by bigtimebuddy** [comment]
I agree, that should be `super.resize`, while these two things express the same functionality, the `super` call is more clear and concise. 

This was introduced 5 years ago by @englercj here https://github.com/pixijs/pixi.js/commit/5ebc77bd68dd59c8e96e2db04d130cc459793739 

I'm guessing it was added before we fully converted to ES6 and that's the ES5 way to do super calls.

**Comment by englercj** [comment]
Yeah that was way before we converted to ES6 when there was no such thing as `super` :)

**Comment by djmisterjon** [comment]
Is not it more interesting from a performance point of view to use call rather than super?
I made test here and it the difference are very huge.
https://jsbench.me/jdjxrdszul/1

**Comment by bigtimebuddy** [comment]
Code is always transpiled down to es5, super is never called natively.

**Comment by SukantPal** [comment]
@djmisterjon The link you've given says that `super` is actually faster.

**Comment by djmisterjon** [comment]
hum interesting what browser you use, i use Vivaldi based on chromium.
i get 1,2 billion ops/s for `call` and only 17 million for `super`.
![image](https://user-images.githubusercontent.com/24865815/60757021-f1c9e600-9fd2-11e9-8fd5-f997f24c1b1e.png)

**Comment by SukantPal** [comment]
I use Firefox (latest) on Ubuntu 19.04. I have a 3rd generation quad-core i7, so I think its slower than your computer - only 34M ops/s.

![image](https://user-images.githubusercontent.com/22450567/60760255-50598900-a000-11e9-855a-8d7947966978.png)

**Comment by djmisterjon** [comment]
@djmisterjon 
thanks for this, for me too , it look like fireFox are more slow for this case , but yes `super`  run more fast than `call` with mozilla engine !
tested from `AMD Ryzen 7 2700X`
![image](https://user-images.githubusercontent.com/24865815/60760825-b565ac80-a009-11e9-93ca-3e2dc348e25a.png)
