### ISSUE TITLE
BatchRenderer isn't exported properly

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#5894]
We are exporting `BatchPluginFactory.create()` rather than the actual `BatchRenderer` class. 

`index.js` in `@pixi/core` exports `BatchRenderer` from `BatchPluginFactory.js` rather than `BatchRenderer.js`. This means that end-users implementing batch rendering will be inheriting from an actually useless middle-man.

```
// BatchPluginFactory.js


// Setup the default BatchRenderer plugin, this is what
// we'll actually export at the root level
export const BatchRenderer = BatchPluginFactory.create();
```

```
// index.js

export { default as BatchPluginFactory, BatchRenderer } from './batch/BatchPluginFactory';
```

I don't think this was intended.

To maintain backward compatibility, we can rename the actual `BatchRenderer` class to `AbstractBatchRenderer` and export that as well. This will work since the actual class isn't exported right now.

**Comment by bigtimebuddy** [comment]
Yes please rename to AbstractBatchRenderer. 👍
