### ISSUE TITLE
drag the whole container

### ISSUE THREAD

**Issue by jinwei14** [pixijs/pixi.js#5896]
Could some one help me to check if there is any why to drag the whole container together.

I have a vehicle and some text associated with it, when I dragged on the vehicle I wants to drag the whole (car and text).

### Expected Behavior
All Sprite Object will be dragged together
### Current Behavior
object move to the corner when click on the object with mouse down
### Possible Solution

The code snippet as follow but it is not working.

```js
        // enable the bunny to be interactive... this will allow it to respond to mouse and touch events
        container.interactive = true;
        // this button mode will mean the hand cursor appears when you roll over the bunny with your mouse
        container.buttonMode = true;

        // setup events for mouse + touch using
        // the pointer events
        container
            .on('pointerdown', onDragStart)
            .on('pointerup', onDragEnd)
            .on('pointerupoutside', onDragEnd)
            .on('pointermove', onDragMove);
```

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by themoonrat** [comment]
Take a look at https://pixijs.io/examples-v4/#/interaction/dragging.js for a good example on how to do dragging. I think your issue may be that in the example, it's a sprite that can have an anchor of 0.5 to centralise things, whereas you do not have anchor on a container. You might need to adjust the position by the container width / height

**Comment by jinwei14** [comment]
@themoonrat Thank you very much for the quick response. I think I have set the anchor of the container to be 0.5. It seems like I need to get the Text and change the position  it dynamically instead of just change the position of the container. I did it through another way, I have store the reference in array and this way is faster and better for my program.

**Comment by ivanpopelyshev** [comment]
@jinwei14 https://pixijs.io/examples-v4/#/plugin-projection/basic.js also good example on interaction, and it drags exactly the point of object you pointed at.

Its an example of pixi-projection plugin (https://github.com/pixijs/pixi-projection/tree/v4.x) you wont be able to run it without extra js file.
