### ISSUE TITLE
BaseTexture error event is not getting fired.

### ISSUE THREAD

**Issue by saiberfun** [pixijs/pixi.js#5900]
### Expected Behavior
When a BaseTexture fails to load I expect BaseTexture to throw an error event and not stop the JS execution.

Based on: https://pixijs.download/dev/docs/PIXI.BaseTexture.html#event:error ( weirdly the documentation offers 2 different error and loaded events )

### Current Behavior
BaseTexture is not firing the error event and stops my JS execution.

### Steps to Reproduce
See example.

### Environment

- **`pixi.js` version**:  5.0.4
- **Browser & Version**:  Chrome 75( probably not limited to )
- **OS & Version**:  Windows 10
- **Running Example**: https://jsfiddle.net/c7psehxj/

**Comment by saiberfun** [comment]
Excuse me. Updated the fiddle to use the error event string instead of our predefined variable.

**Comment by saiberfun** [comment]
Sorry to bump this.

But isn't there anyone that can help with this?
Or is there anything wrong with my issue?

**Comment by themoonrat** [comment]
Nothing wrong with your issue; I took a quick look and there doesn't appear to be anything linking up resources failing to load and the base texture firing an error event. Not that I can see in v5, anyway :/

**Comment by saiberfun** [comment]
Thank you for your reply.
I didn't get quit how you mean that.

If you look at the fiddle and the documentation page linked, the least I'd expect is that I get an error event fired because 'https://google.com/foo.png' is of course not defined and cross-origin which I could catch then.

But this way there is no real way to tell the basetexture souce was not able to load without a timeout.
The documentation defines an error event though.

**Comment by themoonrat** [comment]
I think in the change of how base textures work in relation to resource from pixi v4 to pixi v5, we accidentally lost the functionality of sending an error in your use case.

**Comment by saiberfun** [comment]
Ok, I've been thinking maybe I am just being dumb. 👍 
So this is something that needs to be fixed then.

**Comment by bigtimebuddy** [comment]
We definitely need test coverage for this. PR welcome to fix this and add tests in v5.
