### ISSUE TITLE
How to use multiple canvas in 64*64 size ?

### ISSUE THREAD

**Issue by iamappmaker** [pixijs/pixi.js#5901]
I like to know how to implement like this?
![image](https://user-images.githubusercontent.com/43312229/60913324-c4b45680-a2a4-11e9-91d6-568a98fd442c.png)

If user upload a image, i need to show preview how their image looks when applied a filter.

Suppose if i have 100 filters then i need to show 100 preview. If i create 100 small canvas and execute then process will take time and will be too slow. 

How others are doing in photo filter app?
What is the best way to show preview of 100 filters in effectively.
someone help me please

**Comment by ivanpopelyshev** [comment]
are you making an desktop app? If you use nwjs, you can make sure that user users latest chromium. If so, you have access to OffscrenCanvas, which gives an ability to copy image across canvases :) Theoretically. Practically i didnt check it yet.

**Comment by iamappmaker** [comment]
No. It is mobile app.. I need to show filters preview like this.  What is the perfect and optimized way to show this.
![image](https://user-images.githubusercontent.com/43312229/60969788-0a712d80-a33e-11e9-8c5d-22f9b54fbc3a.png)

**Comment by ivanpopelyshev** [comment]
> What is the perfect and optimized way to show this.

well, first you have to understand how to stop and start rendering when its needed. https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop

thumbs can be obtained through `extract` plugin. https://pixijs.download/dev/docs/PIXI.extract.html

**Comment by Cristy94** [comment]
Load the image in the PIXI app and then create 100 sprites for it, each one with a different filter. Also make sure to pause the updates (so don't run at 60FPS if nothing changes).
