### ISSUE TITLE
Simple and direct way to convert entire canvas to image?

### ISSUE THREAD

**Issue by iamappmaker** [pixijs/pixi.js#5903]
Is there any simple & direct way to convert canvas to image?

I tried many ways but i didn't get correct answer. I need entire canvas to image not any particular object. 

I tried adding image and circle (only half circle is in canvas visible part remaining outside canvas)
app.renderer.plugins.extract.image() // Only last rendered image or object is visible. Either image or circle

app.renderer.plugins.extract.image(app.stage) // works but objects outside canvas visible area also visible in output image. Full circle is visible

**Comment by ivanpopelyshev** [comment]
Here:

```js
renderTexture = PIXI.RenderTexture.create({width, height});
renderer.render(whatDoYouWantToRenderThere, renderTexture);
renderer.plugins.extract.image();
```

**Comment by iamappmaker** [comment]
Thank you very much.

**Comment by ivanpopelyshev** [comment]
Dont forget `renderTexture.destroy()` after that.

**Comment by bildungsroman** [comment]
> Here:
> 
> ```js
> renderTexture = PIXI.RenderTexture.create({width, height});
> renderer.render(whatDoYouWantToRenderThere, renderTexture);
> renderer.plugins.extract.image(renderTexture);
> renderTexture.destroy(true);
> ```
> 
> I guess we have to add it to docs, because people keep requesting that thing.

Is this still the recommended way? I'm trying to do `app.renderer.plugins.extract.image(app.stage);` where `app` is `PIXI.Application` and am getting the following error:

```Uncaught RangeError: Invalid typed array length: 9012016008004
    at new Uint8Array (<anonymous>)
    at Extract2._rawPixels (Extract.ts:220:24)
    at Extract2.canvas (Extract.ts:107:55)
    at Extract2.base64 (Extract.ts:95:21)
    at Extract2.image (Extract.ts:79:26)```

**Comment by austintheriot** [comment]
Thanks for your note, @bildungsroman, my image output was showing as blank until I added the `app.stage` to the function call. This is working for me locally:

```ts
    const newImage = await app.renderer.extract.image(app.stage, 'image/webp')
    document.body.appendChild(newImage)
```
