### ISSUE TITLE
pointer events not working

### ISSUE THREAD

**Issue by iamappmaker** [pixijs/pixi.js#5907]
Why pointer even not working. 

 const app = new PIXI.Application({ 
    width: 300,         // default: 800
    height: 300       // default: 600

  });
document.body.appendChild(app.view); 

const aa = PIXI.Sprite.from('a.jpg');
aa.width = 200;
aa.height = 300;
aa.interactive = true;
  aa.buttonMode = true;
   aa.x = 50;
    aa.y = 50;
  aa.on('pointerdown', onDragStart)
        .on('pointerup', onDragEnd)
        .on('pointerupoutside', onDragEnd)
        .on('pointermove', onDragMove);
app.stage.addChild(aa);

function onDragMove() {
    if (this.dragging) {
        const newPosition = this.data.getLocalPosition(this.parent);
        this.x = newPosition.x;
        this.y = newPosition.y;
		console.log("dragging Move");
    }
}

function onDragStart(event) {
      this.data = event.data;
    this.alpha = 0.5;
    this.dragging = true;

}

function onDragEnd() {
    this.alpha = 1;
    this.dragging = false;
    // set the interaction data to null
    this.data = null;
}

What is wrong in this code.

**Comment by bigtimebuddy** [comment]
You didn't exactly say what you're looking to achieve. but maybe this will help:
https://pixiplayground.com/#/edit/2Aaza6S_L2Gp8fJ_1WCgB

**Comment by iamappmaker** [comment]
I want to move the image by touch and move pointer

**Comment by themoonrat** [comment]
@iamappmaker  I'm not sure what we can say here. bigtimebuddy as provided an example of what you require working; so if it's not working in localhost then there must be some error your side we can't see, either in pixi setup or in copy pasting the example! :)
