### ISSUE TITLE
Double click event

### ISSUE THREAD

**Issue by dorsharon** [pixijs/pixi.js#5910]
Is there any support for a double click event?
Alternatively, can someone help me how to implement such an event on a PIXI.Graphics?

**Comment by djmisterjon** [comment]
i don't think so , may i think this should work.
It a barbar example to start.
```js
    pointerdown_global(e){
        if(this._clicked){
            console.log('double click in 600ms detected');
        }
        this._clicked = false;
        clearTimeout(this.__double);

    };

    pointerup_global(e){
        this._clicked = true;
        this.__double = setTimeout(() => { this._clicked = false; }, 200);
    };
```

**Comment by mofnire** [comment]
This is something like what I am doing:

https://www.pixiplayground.com/#/edit/UvM_wgJh0686y7Pdatx8C

**Comment by themoonrat** [comment]
There's no plans to add double click natively into PixiJS, but there's a couple of good solutions here, so closing :)

**Comment by HusakYurii** [comment]
@dorsharon , @englercj Hey! Although this thread is closed I have come up with this solution. Since  PIXI 5 ahs been split into components, I added a feature, just import it and it should work fine

```javascript

import { InteractionManager, InteractionTrackingData } from '@pixi/interaction';

const superAddEvents = InteractionManager.prototype.addEvents;
const superRemoveEvents = InteractionManager.prototype.removeEvents;

/**
 * To add DOM native 'dblclick' event to the manager
 * @private  
 * @extends
 */
InteractionManager.prototype.addEvents = function () {
    superAddEvents.call(this);

    this.onDoubleClick = this.onDoubleClick.bind(this);
    this.processDoubleClick = this.processDoubleClick.bind(this);

    if (this.interactionDOMElement) {
        this.interactionDOMElement.addEventListener('dblclick', this.onDoubleClick, true);
    }
};

/**
 * @private
 * @extends
 */
InteractionManager.prototype.removeEvents = function () {
    if (this.interactionDOMElement) {
        this.interactionDOMElement.removeEventListener('dblclick', this.onDoubleClick, true);
    }
    superRemoveEvents.call(this);
};

/**
 * Processes the result of the double click check and dispatches the event
 *
 * @private
 * @param {PIXI.interaction.InteractionEvent} interactionEvent - The interaction event wrapping the DOM event
 * @param {PIXI.Container|PIXI.Sprite|PIXI.TilingSprite} displayObject - The display object that was tested
 * @param {boolean} hit - the result of the hit test on the display object
 */
InteractionManager.prototype.processDoubleClick = function (interactionEvent, displayObject, hit) {
    var data = interactionEvent.data;
    var id = interactionEvent.data.identifier;

    if (hit) {
        if (!displayObject.trackedPointers[id]) {
            displayObject.trackedPointers[id] = new InteractionTrackingData(id);
        }
        if (data.pointerType === 'mouse') {
            this.dispatchEvent(displayObject, 'dblclick', interactionEvent);
        }
    }
};

/**
 * @param {PointerEvent} originalEvent
 */
InteractionManager.prototype.onDoubleClick = function (originalEvent) {
    // if we support touch events, then only use those for touch events, not pointer events
    if (this.supportsTouchEvents && originalEvent.pointerType === 'touch') {
        return;
    }

    const events = this.normalizeToPointerData(originalEvent);

    if (this.autoPreventDefault && events[0].isNormalized) {
        const cancelable = originalEvent.cancelable || !('cancelable' in originalEvent);

        if (cancelable) {
            originalEvent.preventDefault();
        }
    }

    const eventLen = events.length;

    for (let i = 0; i < eventLen; i++) {
        const event = events[i];

        const interactionData = this.getInteractionDataForPointerId(event);

        const interactionEvent = this.configureInteractionEventForDOMEvent(this.eventData, event, interactionData);

        interactionEvent.data.originalEvent = originalEvent;

        this.processInteractive(interactionEvent, this.renderer._lastObjectRendered, this.processDoubleClick, true);

        this.emit('dblclick', interactionEvent);
    }
};

```

**Comment by fakob** [comment]
Thanks @HusakYurii, your solution works great!

**Comment by HusakYurii** [comment]
@fakob , nice to hear that, enjoy!
It can be a feature like the others that PIXI has (@englercj  ?)
Have not tried to add something like this for double touch yet. It would be more difficult, I think...

**Comment by fakob** [comment]
That is definitely a feature I think.
@HusakYurii  If you ever have some time to spare, adding double touch in an as easy to implement way would be fantastic :-)

**Comment by HusakYurii** [comment]
@fakob if I add the feature for double touch, it will be here
 https://github.com/HusakYurii/pixi-additional-events

**Comment by fakob** [comment]
Great, thanks @HusakYurii.
I will be watching the repo.

**Comment by HusakYurii** [comment]
@fakob hey! 
I updated the repo, added a feature for double tap event.
I have done a small test and it seems to work. Would appreciate if you test it as well,
Thanks!

**Comment by englercj** [comment]
I don't generally work on this project anymore, @bigtimebuddy and @themoonrat might be able to help though.

**Comment by fakob** [comment]
Thanks @HusakYurii , that is great. I am currently abroad, but will test it as soon as I am back.

**Comment by git-ashish** [comment]
With the pixi version 7.2, addEventListener can be used to detect and handle the doubleclick as mentioned in the [docs](https://pixijs.download/dev/docs/PIXI.Container.html#addEventListener)

```
// Tell the user whether they did a single, double, triple, or nth click.
 button.addEventListener('click', {
     handleEvent(e): {
         let prefix;

         switch (e.detail) {
             case 1: prefix = 'single'; break;
             case 2: prefix = 'double'; break;
             case 3: prefix = 'triple'; break;
             default: prefix = e.detail + 'th'; break;
         }

         console.log('That was a ' + prefix + 'click');
     }
 });

 // But skip the first click!
 button.parent.addEventListener('click', function blockClickOnce(e) {
     e.stopImmediatePropagation();
     button.parent.removeEventListener('click', blockClickOnce, true);
 }, {
     capture: true,
 });

```

**Comment by zszq** [comment]
> With the pixi version 7.2, addEventListener can be used to detect and handle the doubleclick as mentioned in the [docs](https://pixijs.download/dev/docs/PIXI.Container.html#addEventListener)
> 
> ```
> // Tell the user whether they did a single, double, triple, or nth click.
>  button.addEventListener('click', {
>      handleEvent(e): {
>          let prefix;
> 
>          switch (e.detail) {
>              case 1: prefix = 'single'; break;
>              case 2: prefix = 'double'; break;
>              case 3: prefix = 'triple'; break;
>              default: prefix = e.detail + 'th'; break;
>          }
> 
>          console.log('That was a ' + prefix + 'click');
>      }
>  });
> 
>  // But skip the first click!
>  button.parent.addEventListener('click', function blockClickOnce(e) {
>      e.stopImmediatePropagation();
>      button.parent.removeEventListener('click', blockClickOnce, true);
>  }, {
>      capture: true,
>  });
> ```

How to support single click and double click at the same time?
And the click won't be triggered on double click?

**Comment by zszq** [comment]
> With the pixi version 7.2, addEventListener can be used to detect and handle the doubleclick as mentioned in the [docs](https://pixijs.download/dev/docs/PIXI.Container.html#addEventListener)
> 
> ```
> // Tell the user whether they did a single, double, triple, or nth click.
>  button.addEventListener('click', {
>      handleEvent(e): {
>          let prefix;
> 
>          switch (e.detail) {
>              case 1: prefix = 'single'; break;
>              case 2: prefix = 'double'; break;
>              case 3: prefix = 'triple'; break;
>              default: prefix = e.detail + 'th'; break;
>          }
> 
>          console.log('That was a ' + prefix + 'click');
>      }
>  });
> 
>  // But skip the first click!
>  button.parent.addEventListener('click', function blockClickOnce(e) {
>      e.stopImmediatePropagation();
>      button.parent.removeEventListener('click', blockClickOnce, true);
>  }, {
>      capture: true,
>  });
> ```

How to support single click and double click at the same time?
and don't trigger click on double click

**Comment by SuperSodaSea** [comment]
@zszq You can use `setTimeout`: <https://stackoverflow.com/questions/61461518/javascript-how-prevent-dblclick-double-click-to-also-fire-a-single-click-even>

**Comment by fakob** [comment]
Does anyone have an example on how to register a double tap on a mobile device?
It seems that the [above solution](https://github.com/pixijs/pixijs/issues/5910#issuecomment-1703767168) works well on desktop, but does not work on mobile. Maybe I am doing something wrong? 
How would I go about to detect a double tap on a mobile device?
