### ISSUE TITLE
flickering, pixelated graphics on Raspberry Pi

### ISSUE THREAD

**Issue by scitronboy** [pixijs/pixi.js#5914]
### Expected Behavior
My code should create a simple blue rectangle in the top left of the stage.
### Current Behavior
Instead, the rectangle is a pixelated mess of colors that flickers and constantly changes, like static on a CRT TV screen.
![image](https://i.ibb.co/cCV1zQX/img.png)
### Possible Solution
I really don't know. I have a feeling it's something wrong with my WebGL renderer since it's running on a raspberry pi. I'm going to go grab my laptop right now and test it there, then I'll update the issue.
### Steps to Reproduce
Here's my code (I'm using Vue)
```html
<div id="canvas-container">
  <canvas width="700" height="500" ref="raceCanvas" />
</div>
```
```javascript
mounted() {
  this.app = new PIXI.Application({ view: this.$refs.raceCanvas, backgroundColor: 0xa3a5a8 })
  const rect = new PIXI.Graphics()
    .beginFill(0x4287f5)
    .drawRect(0, 0, 100, 100)
    .endFill()
  this.app.stage.addChild(rect)
}
```
### Environment

- **`pixi.js` version**: 5.0.4
- **Browser & Version**: Chromium 74
- **OS & Version**: Raspbian (Debian) 10, running on a Raspberry Pi 3b

**Comment by englercj** [comment]
Your example works as expected for me: https://pixiplayground.com/#/edit/GKgfJK2ppZyAOBbWjI~VP

Maybe it has something to do with vue messing with the canvas element?

**Comment by scitronboy** [comment]
Nope! It's something wrong with the Pi's WebGL renderer, because I visited your link on my pi and a different computer and on the pi the rect was still flickering. I'll try to find a solution and I'll update the issue if I do.

**Comment by englercj** [comment]
Let me know if there is anything I can do to help. I'll be watching the issue.

**Comment by ivanpopelyshev** [comment]
try add `transparent:true` to application options.

**Comment by scitronboy** [comment]
That didn't work, it just made it disappear. What exactly does the `transparent` option do? It seems like it would make it transparent but I can't see how that would ever be useful!

Thanks for the responses, by the way.

**Comment by bigtimebuddy** [comment]
I’d probably assume this is a hardware issue. On some old Android or iOS devices, for example, using transparency is sometimes a hack to get things to render correctly. You might have to do some digging on Graphics drivers for the Pi. 

When you say other pixi projects work, which ones? Do any of the examples (pixijs.io/examples) work for you? Can you get things to work without Vue?

You need to isolate the issue more. Vue, Pixi, Pi or your code could be the issue. Make something simpler to see if you can narrow it down.

**Comment by ivanpopelyshev** [comment]
> What exactly does the transparent option do?
Browser magic.

**Comment by scitronboy** [comment]
I've tried all the `PIXI.Application` options and none of them worked. The only solution I've found so far is using the legacy/forceCanvas option. It also didn't work with WebGL on the examples page.

**Comment by ivanpopelyshev** [comment]
Try open ThreeJS  examples!

**Comment by dogindot** [comment]
Experienced the same today on my raspberry pi 3 with chromium 74. pixi 5.1.5.
I've tried several chrome flags but even the examples on the pixi-website are displayed as pixel noise.
Having the OpenGL disabled in raspi-config, sprites are rendered as expected but the render is slowly and the screen resolution is not as expected.

Any updates on this?

**Comment by scitronboy** [comment]
I was never able to figure it out. I just went with the canvas option as
well. Hopefully with future raspbian webgl updates it will be fixed.
