### ISSUE TITLE
Video texture not updating when load m3u8(HLS) on ios mobile device

### ISSUE THREAD

**Issue by m6fish** [pixijs/pixi.js#5920]
HI,
I want to use Pixi(v5) to play an HLS(.m3u8) video on a mobile webpage, 
but I find that on IOS (iPhone Xs), PIXI.Texture.from﻿﻿ is not updated as predicted.

#### code 
v5.0.4
https://jsbin.com/pohikim/edit?html,js,output
v4.8.8
https://jsbin.com/qecucav/edit?html,js,output

#### just Output
v5.0.4
https://output.jsbin.com/pohikim/
v4.8.8
https://jsbin.com/qecucav/8

### Expected Behavior
Display .m3u8 video
(Browsers which supported HLS (ex: edge on PC) can play normally(both <video> & pixi ) )

### Current Behavior
black screen. Sometimes it will flash a picture and then back to black.

### Steps to Reproduce
open test link on iPhone

### Environment
pixi.js:  v5.0.4, v4.8.8
iPhone Xs safari & telegram webview

**Comment by themoonrat** [comment]
So I tried this on Chrome on my Android device, and in the console you get

```
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The video element contains cross-origin data, and may not be loaded.
```

I wouldn't be surprised if iOS will be throwing up the same kind of cross origin error

**Comment by dabe93** [comment]
I'm experiencing a similar issue when loading a video from a CDN in the same way. Did you find a workaround?

**Comment by dabe93** [comment]
So in my case was a CORS problem that i solved as you can see here #5922 
Now with an HLS stream i have the same problem on safari, it flash a picture at the beginning than black screen without throwing any error.
@m6fish did you find a workaround? Do you have the same error also with Pixi v4?
Thank you very much

**Comment by m6fish** [comment]
Thanks for your solution!! Will try it latter.

did you find a workaround?
-> Sadly not yet.

Do you have the same error also with Pixi v4?
-> Yes, got the same problem at v4.

There is a new discovery that use HLS.js can play on android & PC chrome.
At the beginning, I just want to use it to play on PC chrome, but found that it can strangely play on Android well. Not yet try on apple.
Maybe this can help.

**Comment by dabe93** [comment]
I use jwplayer as a cross-device HLS player but i got the same error as yours trying using HLS file as source for Pixi on mobile and Safari. With Chrome or Firefox on Desktop it works great also with HLS.
The strange thing is that for a moment you can see the render and Pixi doesn't trow any error in the console.

**Comment by m6fish** [comment]
yeah, totally not knowing how to deal with mobile Safari.

My Temporary solution is to make a pop-up <div> to play the video without Pixi ....

**Comment by dabe93** [comment]
Tried pixi-legacy and enabled force-canvas and it seems to work with safari (both MacOS and iOS). Need more test on this.
So it seems that WebGL has a problem with safari and m3u8...

**Comment by themoonrat** [comment]
So, I know that Safari on iOS 10 used to have an issue rendering video to WebGL if it was cross domain, even if you set the right headers. 
That isn't *this* issue, as they fixed it for iOS 11, but Apple do have form in messing up videos and WebGL :/

**Comment by dabe93** [comment]
> So, I know that Safari on iOS 10 used to have an issue rendering video to WebGL if it was cross domain, even if you set the right headers.
> That isn't _this_ issue, as they fixed it for iOS 11, but Apple do have form in messing up videos and WebGL :/

This issue is also with Safari on MacOS, not iOS. So it seems to be a problem with Safari and WebGL with m3u8 videos (this is great considering that HLS is developed by Apple...)

**Comment by m6fish** [comment]
provide force-canvas code at here.

https://jsbin.com/pohikim

May be a problem with Safari & WebGL, So.... should i close this issue ?

**Comment by themoonrat** [comment]
I think so... there's not much we can do PixiJS side apart from provide workarounds ... of which the canvas renderer is the solution :/

I wonder if you create a canvas yourself, and drew directly from the video to that using the canvas api... and then used that as a BaseTexture source, that'd let you keep the WebGL renderer?

**Comment by m6fish** [comment]
video -> canvas -> pixi

Can play video & keep the WebGL renderer.
Thanks for this interesting solution. I'll take a try.

**Comment by dabe93** [comment]
> I wonder if you create a canvas yourself, and drew directly from the video to that using the canvas api... and then used that as a BaseTexture source, that'd let you keep the WebGL renderer?

This is interesting. I'm just worried about performance. @m6fish let me know if you try it.

**Comment by m6fish** [comment]
@themoonrat  It's OK to play on ios !!
@dabe93  Maybe can reduce FPS to deal with the performance problem ?

https://output.jsbin.com/qetuhug/5
