### ISSUE TITLE
Pixi js Masking over the line

### ISSUE THREAD

**Issue by vpatel1621** [pixijs/pixi.js#5921]
Hello,

I have a blue line drawn on pixi 
I need to change the color of the line halfway.
So after changing the color, half line will be blue and rest of half will be another color.
I am using mask and rectangle shape on top of original line to achieve this.
for now I am just creating square to see if object is  being drawn. But I am not able to see the masked square. Once I see, I will convert to a thin line.

Please help.

Below is the code. 
PathGraphics is the original line in blue.
  const highlightPath = this.pathGraphics.clone();
    this.container.addChildAt(highlightPath, 0);
    const highlightMask = new PIXI.Graphics();
    highlightMask.beginFill(0xb54c00);
    highlightMask.drawRect(50, 50, 50, 50);
    highlightMask.endFill();
    highlightPath.mask = highlightMask;

**Comment by ivanpopelyshev** [comment]
Please use https://www.pixiplayground.com/ to make a demo. I think I understand what you want only partially? Why cant you just draw one part of line and than another?

Also graphics mask doesn't change a color, it just decides what to draw and whats not. Sprite mask works differently. 

You can also use white lines and `graphics.tint` property to color them.

**Comment by vpatel1621** [comment]
Thanks for reply.
My requirement is I have a blue line drawn already on page load and on that line I have a moving object, lets assume a ball, which keeps changing the position on the line/rolling over the line.

When I mouse hover on the ball, I need to change the color of the portion of the ball already travelled to red. Rest of the portion will stay Blue as it is not travelled yet.

What do you think the best way to achieve this.

Thanks.

**Comment by vpatel1621** [comment]
![Requirement](https://user-images.githubusercontent.com/53017663/61484922-e3ce7a80-a96d-11e9-85f5-72a2ff36c199.png)

**Comment by vpatel1621** [comment]
![Requirement](https://user-images.githubusercontent.com/53017663/61485165-72db9280-a96e-11e9-9aad-0142da32bf0d.png)

**Comment by vpatel1621** [comment]
See the above diagram, assuming that ball rolling towards right, 

1) Currently it always has blue color on the line.
2) On mouse hover on the ball, I need to change the color of the portion which is completed to green and pending portion will continue to be blue.

Hope this clarifies.

**Comment by ivanpopelyshev** [comment]
oh, now i see. Yeah, just simple mask should work here.

Why doesn't it work for you i dont know, please give me a demo.

**Comment by vpatel1621** [comment]
![BezierCurve Mask](https://user-images.githubusercontent.com/53017663/61535401-3193c300-aa00-11e9-8b8d-d838c764f673.png)

**Comment by vpatel1621** [comment]
Another thing.
Above blue curve is drawn using BezierCurve, 
If I need to mask the portion of the curve with another color,  is it possible ?

**Comment by ivanpopelyshev** [comment]
Just one rectangle should work.
