### ISSUE TITLE
Video CORS issue

### ISSUE THREAD

**Issue by dabe93** [pixijs/pixi.js#5922]
Trying this code:

```
source.crossOrigin = 'anonymous';
let texture = new PIXI.Texture.from(source);
video = new PIXI.Sprite.from(texture);
app.stage.addChild(video);
```
where source is a HTML video element already present on the page i get a CORS error.
The video is loaded from a cdn (Akamai).
I tried with solutions from older threads but nothing solved. I need to load the video from the HTML element to control it with the player.

There is something I can do?
Thank you very much

**Comment by ivanpopelyshev** [comment]
maybe related to #5920

**Comment by dabe93** [comment]
i discovered that in my case the problem was setting the crossOrigin attribute AFTER the video src setting.
Because i was using jwplayer as video player, i've customized jwplayer in order to add the attribute before loading the video. Not tested with every browser yet

**Comment by themoonrat** [comment]
Useful to know, thanks for posting your solution!
