### ISSUE TITLE
Should we define a maximum line length?

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#5924]
We've touched on this before and I'm going to open an issue regarding this. I see documentation going up to 110-120 characters, whereas the code mostly exists till 80 characters (I'm talking about `DisplayObject.js`).

Should we define a maximum line length? According to Google's JavaScript guide, it should be 80 columns per line, which I prefer.

If defined, we can use ESLint to enforce this.

**Comment by ivanpopelyshev** [comment]
I htink that current length is fine.

https://github.com/pixijs/pixi.js/blob/dev/.eslintrc.json#L165

**Comment by SukantPal** [comment]
Okay, you guys have big monitors that means.
