### ISSUE TITLE
Improve typings for Container.addChild and Container.addChildAt

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi.js#5927]
We're switching from Pixi4 to 5, and using the included typings instead of https://github.com/pixijs/pixi-typescript.

Container.addChild and Container.addChildAt are not generic (excerpt from pixi.d.ts included in Pixi5):
```
addChild(...child: PIXI.DisplayObject[]): PIXI.DisplayObject;
addChildAt(child: PIXI.DisplayObject, index: number): PIXI.DisplayObject;
```

Therefore,  code like this doesn't work:

```
const sprite = this.stage.addChild(new PIXI.Sprite(tex));
sprite.anchor.set(0.5);
```
In this example, sprite is inferred to be a PIXI.DisplayObject, so we get the following error:
`Property 'anchor' does not exist on type 'DisplayObject'.`

If we add generics to the code, the types are properly inferred and everything works as expected:

```
addChild<TChildren extends PIXI.DisplayObject[]>(...child: TChildren): TChildren[0];
addChildAt<T extends PIXI.DisplayObject>(child: T, index: number): T;
```
Right now we're using a custom version of pixi.d.ts with these changes, and everything works great.

The pixi4 typings has support for generics, so I think this may be an issue for any typescript users moving to Pixi5.

I attempted to put together a PR for this, but I saw that the typings are automatically generated from the JSDoc comments, and I'm unsure how (or if it's even possible) to type something like this.

If someone could point me in the right direction, I'd be more than happy to help out with a PR!

**Comment by bigtimebuddy** [comment]
This is a good example of where our JSDoc -> typings solution starts to run out of steam. I doubt that @englercj could/should support generics in **tsd-jsdoc** (probably wouldn't be compatible with JSDoc).

The best long-term solution right now, which we are planning to do, is move the code base to TypeScript and then auto-generate types. Unfortunately, there's a lot of work to do there. 

The short-term, hacky solution is to make a change to this script (https://github.com/pixijs/pixi.js/blob/dev/types/assemble.js). Simply replace the `addChild` `addChildAt` lines with something like you proposed. I'd probably accept this PR.

**Comment by ivanpopelyshev** [comment]
wow, i didnt even know it can work like that :) I like the idea!

**Comment by jmlee2k** [comment]
Ok, great, I actually noticed that file when I was looking around, but wasn't sure if there was any other way to accomplish this.  I'll put together a PR on Monday.

I agree, adding support to tsd-jsdoc would be quite a task, but I was thinking it may be possible to add a custom attribute, like "@tstype" which would be a string that emitted to the d.ts file instead of using the jsdoc comments to figure out the type.  @englercj can let me know how crazy that idea is. :)

**Comment by bigtimebuddy** [comment]
I think that's a great ideas @jmlee2k. JSDoc complains about tags it doesn't understand (unless parsing is set to being lenient), but maybe there's a paved-road for adding custom user-defined tags.

**Comment by englercj** [comment]
> I doubt that @englercj could/should support generics in tsd-jsdoc (probably wouldn't be compatible with JSDoc).

tsd-jsdoc does support generics through the [@template](https://github.com/englercj/tsd-jsdoc#supported-closurecompiler-tags) closure compiler tag. Recent versions of jsdoc support it as well, which actually broke tsd-jsdoc is recent jsdoc versions (because they removed it from the 'custom tags' list and put it elsewhere) so I have to fix that soon.

> The best long-term solution right now, which we are planning to do, is move the code base to TypeScript and then auto-generate types.

Honestly this is the business, we should do this :)

> @englercj can let me know how crazy that idea is. :)

Already supported. Example [jsdoc markup](https://github.com/englercj/tsd-jsdoc/blob/362045182080d8d762b170bf9798021a5cfc6820/test/fixtures/namespace_all.js#L5-L33), example [dts output](https://github.com/englercj/tsd-jsdoc/blob/362045182080d8d762b170bf9798021a5cfc6820/test/expected/namespace_all.d.ts#L5-L23).
