### ISSUE TITLE
Empty "plugins" object after upgrading from 5.0.4 to v5.1.0

### ISSUE THREAD

**Issue by enriko-riba** [pixijs/pixi.js#5932]
Working & unchanged project breaks after upgrading to pixi 5.1.0.  because the plugins object is empty.

In Sprite.js 
```
_render(renderer)
    {
        this.calculateVertices();

        renderer.batch.setObjectRenderer(renderer.plugins[this.pluginName]);
        renderer.plugins[this.pluginName].render(this);
    }
```

the renderer.plugins is empty.

I am bundling with webpack using the following config:
```const config: webpack.Configuration = {      
    entry: {
        main:   "./src/app.ts",
        common: ["@tweenjs/tween.js", "pixi.js", "pixi-filters", "toaster-js"],
        frb: ["firebase/app","firebase/auth", "firebaseui"],
    } 
etc...,
```

in index.ts reexporting pixi as:
```
import * as pixi from 'pixi.js';
export var PIXI = pixi;
```

And than just adding some text:
```
this.loadingMessage = new PIXI.Text("booting ...", {
             fontSize: "36px", 
             fontFamily: "Permanent Marker", 
             fill: 0x0ff00, 
             dropShadow: true, 
             stroke: 0x44ff44, 
             strokeThickness: 1 
        });
etc...
```

Anyone has an idea what to change in webpack config to import the plugins?

**Comment by enriko-riba** [comment]
Not sure what was the cause of the issue but after deleting node_modules, "npm i" and rebuilding everything works as expected.

**Comment by themoonrat** [comment]
Turned if off then on again. Works (nearly) every time ;)

**Comment by lebesnec** [comment]
I have the same problem after upgrading from 5.0.3 to 5.2.0.. Deleting `nodes_modules` did not help.

```
import { Application } from 'pixi.js';
// ...
this.pixiApp = new Application({
        view: this.canvas,
        width: this.canvas.width,
        height: this.canvas.height,
        antialias: true,
        transparent: true
});
console.log(this.pixiApp.renderer.plugins);

show an empty object in the console.
```

**Comment by lebesnec** [comment]
Got it to work by deleting both `nodes_modules` and `package-lock.json`.
It took 2 `npm install` to succesfully install after that. Sometime I hate npm.
