### ISSUE TITLE
NineSlicePlane crash with Canvas renderer

### ISSUE THREAD

**Issue by phpositive** [pixijs/pixi.js#5935]
### Expected Behavior
Pixi should not crash when using Canvas renderer and NineSlicePlane with PIXI.Texture.EMPTY texture. WebGL renderer works as expected.

### Current Behavior
NineSlicePlane._renderCanvas() crashes as textureSource is undefined

### Possible Solution
-

### Steps to Reproduce
Please paste following code to Pixi examples page:

```
const app = new PIXI.Application({ forceCanvas: true });
document.body.appendChild(app.view);

const plane = new PIXI.NineSlicePlane(PIXI.Texture.EMPTY, 2, 2, 2, 2);
app.stage.addChild(plane);
```

### Environment

- **`pixi.js` version**: 5.1.0
- **Browser & Version**: Chrome 75.0.3770.142
- **OS & Version**: Windows 8
- **Running Example**:

**Comment by jjhesk** [comment]
does it happen on 5.1.1 still?

**Comment by phpositive** [comment]
![image](https://user-images.githubusercontent.com/46866263/63002634-aa0e6800-be76-11e9-8fe5-7abbec647beb.png)

yes, it is still there

**Comment by jjhesk** [comment]
its the browser version problem. they need to specify which version does work and not work

**Comment by phpositive** [comment]
Crashes for me on latest Chrome/Firefox/Edge, so it's probably not a browser version issue
