### ISSUE TITLE
[Suggestion] An new Animation Class

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#5936]
I've talked about it .
at

https://github.com/pixijs/pixi.js/issues/4746
https://github.com/pixijs/pixi.js/issues/3469  

but they are locked by bot :'(

**Comment by ivanpopelyshev** [comment]
Yes, we can re-open it for 5.2.0 , I'll support you :)

**Comment by ivanpopelyshev** [comment]
OK, in pixi-heaven v5 its there.
I'm going to make PR for 5.1.2 or 5.2.0

**Comment by finscn** [comment]
Is there any news ?

**Comment by bigtimebuddy** [comment]
This is a pretty big undertaking. If someone wants to make a new plugin or module for more advanced animations, they are welcome. However, this is low on the current priorities of the core team and likely will not get started without the help of the community.

**Comment by finscn** [comment]
I went from programmer to manager. There are many thing  bother me. 
I haven't started learning pixi v5 yet.  
So I can't give you some help , Although I hope.  :(
