### ISSUE TITLE
Plugin-Layers first example broken

### ISSUE THREAD

**Issue by bakugod** [pixijs/pixi.js#5937]
### Broken example

  Problem looks like:

  __The selected version of PixiJS does not work with this example.__

  __Selected version: v5__

  __Required version: v4__

### Environment

- **Browser & Version**: _e.g. Chrome 75_
- **OS & Version**: _e.g. Windows 8_
- **Running Example**: [here]

[here]://pixijs.io/examples/#/plugin-layers/normals.js

**Comment by bakugod** [comment]
Also broken 4 and 5 examples

**Comment by ivanpopelyshev** [comment]
lights and double-buffering are still broken, yeah :)
