### ISSUE TITLE
 Aliasing artifacts using DisplacementFilter

### ISSUE THREAD

**Issue by nicknack23** [pixijs/pixi.js#5940]
I started a thread about this [here at html5gamedevs](http://www.html5gamedevs.com/topic/43276-aliasing-artifacts-using-displacementfilter/) a couple of weeks ago, but since my problem remains unresolved I think it's time to open an issue.

I'm trying to use DisplacementFilter in Pixi to warp images based on displacement maps in .msh files created by Photoshop Liquify. My implementation works but results in ugly aliasing artifacts. Below are three demos (here slightly simplified so the displacement maps are read as Base64 strings instead of parsing the original .msh files).

### Expected Behavior
This is my reference implementation using vanilla javascript. Click "Change view" and put the code along the left side so you can see the image, and then click the button to toggle between results from Photoshop and my vanilla javascript code. 
https://codepen.io/anon/pen/orOMjr

The two results are virtually identical (although there are minuscule differences if you really go crazy with with pixel peeping). This is what I expect from Pixi too.

### Current Behavior

This is the Pixi version with displacement maps translated to 8 bit color channels and then sent to DisplacementFilter:
https://codepen.io/anon/pen/PrgBoN

After discussions in the html5gamedevs thread I suspected the aliasing may be caused by posterization if 8 bits are insufficient to represent displacements. I got a tip to try 32 bit float textures instead, and this is the result:
https://codepen.io/anon/pen/JQVZQw

To my eyes this is slightly better (without the small shift towards the upper left), but it doesn't really improve the aliasing.

### Possible Solution

No idea. My code uses bilinear interpolation of both displacement vectors and color samples to get a smooth result. Does Pixi do this too?

### Steps to Reproduce

Run the three Codepen demos above.

### Environment

- **`pixi.js` version**:  5.0.4
- **Browser & Version**:  Chrome 75 and Firefox 68
- **OS & Version**:  Windows 10
- **Running Example**:  see above

**Comment by ivanpopelyshev** [comment]
Congratulations on solution!

http://www.html5gamedevs.com/topic/43276-aliasing-artifacts-using-displacementfilter/

That's what you've used:
```glsl
    vec4 topleft = texture2D(sampler, (icoord + vec2(0.5,0.5)) * samplerSize.zw);
    vec4 topright = texture2D(sampler, (icoord + vec2(1.5,0.5)) * samplerSize.zw);
    vec4 bottomleft = texture2D(sampler, (icoord + vec2(0.5,1.5)) * samplerSize.zw);
    vec4 bottomright = texture2D(sampler, (icoord + vec2(1.5,1.5)) * samplerSize.zw);
```

Yes, enabling "baseTex.scaleMode = PIXI.SCALE_MODES.LINEAR" only makes things worse in 5.0.4.

However, it works in 5.1.1 because we automaticaly enable FLOAT_LINEAR extension, lines 172 and 183 of https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/context/ContextSystem.js#L183 

It doesn't work on all devices, you can see where's it actually available at webglstats.com . Its different extensions for webgl1 and webgl2. Your solution will work everywhere.

**Comment by alejandromizraji** [comment]
Hi! I am also seeing artifacts and pixelated borders on my images when I apply the displacement map. I am using version 5.2.2 of pixi.

<img width="265" alt="Screen Shot 2020-04-29 at 12 30 39 PM" src="https://user-images.githubusercontent.com/10290181/80615102-a70fd380-8a15-11ea-8198-9981380170ae.png">

<img width="202" alt="Screen Shot 2020-04-29 at 12 30 49 PM" src="https://user-images.githubusercontent.com/10290181/80615107-aaa35a80-8a15-11ea-908a-02dc4843bdfb.png">
