### ISSUE TITLE
Pixi5 - drop shadow is applied twice to text with a stroke and shadow

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi.js#5953]
### Expected Behavior
Drop shadow should be applied under the stroke.

### Current Behavior
Drop shadow is applied under the stroke _and_ over it

### Steps to Reproduce
Make a PIXI.Text object with both a stroke and drop shadow

### Environment
Works as expected in pixi 4.8.8 [playground](https://www.pixiplayground.com/#/edit/CUBr6lK85gRH6qPPWKe3H)
Broken in pixi 5.1.0 [playground](https://www.pixiplayground.com/#/edit/9nzjGWkoAVPPoLDMH8t5V)

**Comment by themoonrat** [comment]
There is a PR pending to fix this: https://github.com/pixijs/pixi.js/pull/5947

**Comment by jmlee2k** [comment]
Thanks, sorry about that!

**Comment by themoonrat** [comment]
No probs :)
