### ISSUE TITLE
PIXI.Graphics clear does not clear memory

### ISSUE THREAD

**Issue by Metatron92** [pixijs/pixi.js#5955]
Hello.

PIXI.Graphics clear does not clear memory.

### Example
https://www.pixiplayground.com/#/edit/fs9uki6NjIsYat6ebEKMI

### Example with destroy & geometry.dispose()
https://www.pixiplayground.com/#/edit/hj~OMQX8DVGr4mEk~T8W4

At start a had:
![image](https://user-images.githubusercontent.com/346867/61974843-348a4700-aff0-11e9-9981-5f0e0efc92da.png)

After 20 clicks on refresh:
![image](https://user-images.githubusercontent.com/346867/61974892-54216f80-aff0-11e9-9b6a-5dbfabf28fbc.png)

Memory continue grow up and without refresh does not clear.

Using dispose does not obvious.

### Environment

- **`pixi.js` version**:  5.1.0
- **Browser & Version**: Chrome 75
- **OS & Version**:  Window 10
- **Running Example**: https://www.pixiplayground.com/#/edit/fs9uki6NjIsYat6ebEKMI

**Comment by ivanpopelyshev** [comment]
The problem with the first is that we have to call `dispose` .

The problem with second is that destroy() removes geometry from children, and forEach skips every second geometry.

I've removed `destroy()` and it works: https://www.pixiplayground.com/#/edit/nrga_1W3wADpVWexU0n1c

**Comment by distinctdan** [comment]
Sounds like the old "iterating while modifying" problem. When I need to destroy stuff like this, I loop backwards over the array with a good old fashioned for loop:
```
for (i = rectStage.children.length - 1; i >= 0; i--) {
    rectStage.children[i].destroy();
}
```
That way, when it's removed from the array, your loop is still in the right place.
