### ISSUE TITLE
RenderTexture setResolution > 1 causes GL Error in 5.1.0, but it works in 5.0.4

### ISSUE THREAD

**Issue by ahdai0718** [pixijs/pixi.js#5967]
### Current Behavior
RenderTexture is blank and console log report warning above.
```
[.WebGL-0x7fde108d5600]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
```

But it works when remove 
`renderTexture.setResolution(window.devicePixelRatio);`,
or
`renderTexture.setResolution(1);`,

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/wS_08rQME3tUHPN3Ph~zb
### Environment

- **`pixi.js` version**:5.1.0
- **Browser & Version**:Chrome 75.0.3770.142 64bit
- **OS & Version**: macOS Mojave 10.14.6 
- **Running Example**: https://www.pixiplayground.com/#/edit/wS_08rQME3tUHPN3Ph~zb

**Comment by themoonrat** [comment]
Could you try http://pixijs.download/dev-fix-basetexture-over-zealous-ceiling/pixi.js please and see if that works?

**Comment by ahdai0718** [comment]
Hi @themoonrat, thanks for reply so soon.

I use `npm` and `webpack-dev-server` to develop my project.

And I replaced `pixi.js` and `pixi.min.js` under `node_modules/pixi.js/dist/` with
`http://pixijs.download/dev-fix-basetexture-over-zealous-ceiling/pixi.js`,
then re-build and re-run the project.

But i have no idea the replacement of `pixi.js` and `pixi.min.js` is correct or not.

Still got the same error in debug console.

**Comment by ivanpopelyshev** [comment]
Its possible that webpack uses stuff from `lib` folder, it imports `pixi-core` module and then uses latest pixi-core. 

In that case you cant do anything unless connect pixijs as external file.

Here's the hack fix to test:

```
PIXI.BaseTexture.prototype.setRealSize = function (realWidth, realHeight, resolution)
{
    this.resolution = resolution || this.resolution;
    this.width = realWidth / this.resolution;
    this.height = realHeight / this.resolution;
    this._refreshPOT();
    this.update();

    return this;
}

PIXI.BaseTexture.prototype.setResolution = function(resolution)
{
    const oldResolution = this.resolution;
    if (oldResolution === resolution)
    {
        return this;
    }
    this.resolution = resolution;

    if (this.valid)
    {
        this.width = this.width * oldResolution / resolution;
        this.height = this.height * oldResolution / resolution;
        this.emit('update', this);
    }

    this._refreshPOT();
    return this;
}
```

**Comment by ahdai0718** [comment]
Hi @ivanpopelyshev, i will try this solution, thanks.
