### ISSUE TITLE
Firefox fails to load using Texture.from() when image is cached

### ISSUE THREAD

**Issue by ted537** [pixijs/pixi.js#5968]
### Expected Behavior

Texture.from() should succeed whether loading from cache or not

### Current Behavior

Texture.from() fails when an image is cached and and HTTP 304 is received.

### Other

Noticed that when loading from cache, textures are immediately seen as valid.

I'm currently working around this by loading image urls into Image elements, and waiting for them to load before creating the PIXI textures.

### Steps to Reproduce

```
<html>
<meta charset="UTF-8">

<body>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.1.0/pixi.js"></script>
<script>
let app = new PIXI.Application({width:640,height:480});
document.body.appendChild(app.view);
let tex = PIXI.Texture.from("https://i.imgur.com/vt1Bu3m.jpg");
let sprite = new PIXI.Sprite(tex);
app.stage.addChild(sprite);
</script>

</html>
```

Open the following doc in firefox. When reloading, the image won't appear. If you disable cache, the image will appear on reload

### Environment

- **`pixi.js` version**: 5.1.0
- **Browser & Version**: Firefox 68.0
- **OS & Version**: Ubuntu 18.04

**Comment by mirandayvonnemann8276** [comment]
How do i get rid of it

**Comment by laino** [comment]
Happens to me as well.

Make sure to close the dev console or uncheck "Disable cache" in the network tab to reproduce this.

* **`pixi.js` version**: 5.1.0
 * **Browser & Version**: Mozilla Firefox 68.0.1
* **OS & Version**: 5.2.2-arch1-1-ARCH

**Comment by mofnire** [comment]
Seems like a bug of FireFox as it was before?

https://github.com/mpetroff/pannellum/issues/505
https://github.com/photonstorm/phaser-ce/pull/3

When I delayed the `gl.texImage2D` timing as shown below, the kitty showed up. So I think FF 68 sets `HTMLImageElement#complete` to true before it's ready to be uploaded.

```javascript
const load = PIXI.resources.ImageResource.prototype.load;
PIXI.resources.ImageResource.prototype.load = function(createBitmap) {
    this._width = 0;
    this._height = 0;
    return load.call( this, createBitmap );
};
```

Working example:
https://www.pixiplayground.com/#/edit/QU9AHtc7TUS4LOsR7CWjW

Could be a workaround if combined with a browser detection?

**Comment by GoodBoyDigital** [comment]
Thanks for sharing @mofnire! If you could do a PR with this fix that would be ace!

Cheers!

**Comment by mofnire** [comment]
I was wrong. What the FireFox 68 does is setting the `HTMLImageElement#width` and `#height` to non-zero values before its loading completes if the kitty image is in a cache. Because PixiJS treats resources with non-zero width and height as resources ready to be uploaded, the `gl.texImage2D` fails.

**Comment by mofnire** [comment]
Namely, need to check the `HTMLImageElement#complete`.
https://www.pixiplayground.com/#/edit/XX8a7e2XBMBpDMc0gLzz_
