### ISSUE TITLE
Garbled output with lots of rectangles in v5

### ISSUE THREAD

**Issue by pkerpedjiev** [pixijs/pixi.js#5973]
Apologies in advance for submitting an issue without a self contained example. I'm hoping that maybe somebody will see an obvious issue. If not, I'll dig further and try to create a working example.

The issue is quite simple. I have code that renders a bunch of rectangles (thousands to tens of thousands). It works perfectly with PIXI v4. When switching to v5, the rectangles become garbled when there's more than about 30K. I've attached screen captures of both:

**v4**

![Jul-29-2019 18-44-18](https://user-images.githubusercontent.com/2143629/62094158-f7f95e00-b230-11e9-882a-cf1e6d650dbd.gif)

**v5**

![Jul-29-2019 18-43-55](https://user-images.githubusercontent.com/2143629/62094163-fdef3f00-b230-11e9-9f7a-81eeca496faf.gif)

### Expected Behavior

The behavior shown in the v4 screen capture.

### Current Behavior

The behavior shown in the v5 screen capture.

### Possible Solution

Downgrade to v4.

### Steps to Reproduce

Unclear exactly. This is buried within a bunch of other code. It is reproducible though.

### Environment

- **`pixi.js` version**: working (4.8.1), not working (5.1.0)
- **Browser & Version**: Chrome 75.0.3770.100, also tried with Firefox 67.0.4
- **OS & Version**: _e.g. OS X 10.13.6
- **Running Example**: local

**Comment by ivanpopelyshev** [comment]
Is that one Graphics object, several , or hundreds?
There's that hack that allows you to have any number of vertices in Graphics.

**Comment by ivanpopelyshev** [comment]
https://www.pixiplayground.com/#/edit/NGOapxXGbS5btz5KS7Dge

Execute this if graphics was changed before the render.
```js
graphics.geometry.updateBatches();
// try commenting that to see Uint16 overflow
graphics.geometry._indexBuffer.update(new Uint32Array(graphics.geometry.indices));
```

Alternatively: patch this line, use Uint32Array https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/GraphicsGeometry.js#L554

I want to add this thing to main pixijs code soon,

Alternatively, just create several Graphics with less rectangles.

**Comment by pkerpedjiev** [comment]
Hey, thanks for the prompt response! Looks like looking at the video was enough to diagnose the issue :-)

All of my draw calls were in one Graphics object. Splitting the `drawRect` calls across multiple Graphics objects fixes the issue completely. Completely anecdotally it feels slightly faster than the v4 rendering with all the rectangles in one Graphics object. Might just be the placebo effect.

Anyway, thanks again and keep up the good work! We're using the library for scientific data visualization and absolutely love it.

**Comment by bigtimebuddy** [comment]
Not a placebo effect. The reason that it's faster than v4 rendering is because Graphics (and Mesh objects) are now batched in v5 instead of just Sprites. Especially if you're just drawing a bunch of rectangles (low complexity, fewer verts), then Graphics are a great option!

**Comment by pkerpedjiev** [comment]
Oh nice! I'm not sure I know what that means but I'm glad it's there 👍

**Comment by bigtimebuddy** [comment]
Ha, no worries. Glad it's working now.
