### ISSUE TITLE
Specific nested masks + filter breaks drawing (v5 and v4)

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi.js#5974]
### Expected Behavior
Filters and masks should work together normally

### Current Behavior
Objects disappear and only certain masks are applied

### Steps to Reproduce
In Pixi5, the issue occurs when a filter is added to an object (A) which contains a masked child object, and object A's parent chain includes an EVEN number of masks >= 2.

In Pixi4, the issue occurs when object A's parent chain includes an ODD number of masks >= 3.

### Test Case

https://www.pixiplayground.com/#/edit/PmNR2aqebJB2i56E5IiBz

In the test case, 4 objects are created, each with a masked bunny and a gray bg.  Clicking on an object will move it down by 10px and add a ColorMatrixFilter which darkens the object, clicking again will restore it.

You can change the level of nesting by modifying the length prop on line 69 - a value of 0 will add the objects directly to the stage, 1 will make a single container, etc.  Each container has a different background color, and each mask's x position is offset by 10px to make it easier to visualize the nesting.

#### Pixi5
Changing the level of nesting to anything >= 2 will show the problem.  If the level of nesting is EVEN, clicking on the objects will make them disappear (since it adds a filter), and once all 4 have filters, the circle at the bottom will no longer be drawn.  If the level of nesting is odd, the objects won't disappear, but you can see that only alternating masks are being applied (changing the nesting level to 7 and clicking on the first object makes this very clear, as you can notice the "jailbars" effect at the left while the object is masked).

#### Pixi4
Running the same playground link in pixi4 will result in similar problems, except the nesting level has to be >=3, and the objects will disappear if the level of nesting is ODD, vs EVEN in pixi5.

**Comment by ivanpopelyshev** [comment]
OK guys, we failed somewhere in MaskSystem in both versions.

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/mask/MaskSystem.js#L173
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/mask/StencilSystem.js#L55

Ideas?

**Comment by ivanpopelyshev** [comment]
Filter and masks are working together here: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/renderTexture/RenderTextureSystem.js#L98

**Comment by ivanpopelyshev** [comment]
Can you check the result please? https://www.pixiplayground.com/#/edit/t09LhS3_ttR6R7przuBOi

That gray bar at the right - is that supposed to happen?

**Comment by jmlee2k** [comment]
Nope, the bar shouldn't be there - nothing should go out of the green square.

I also noticed that when you click on the 3rd item, the bunny in the 4th item is masked properly, but it's background isn't:

![image](https://user-images.githubusercontent.com/7396545/62321860-a986d200-b471-11e9-9ac5-adab7917b41d.png)

On the plus side, nothing disappears anymore.

**Comment by ivanpopelyshev** [comment]
OK, now its better. Right?

**Comment by jmlee2k** [comment]
Yep, I just checked again, and it looks like it's working great, thanks!  Is https://pixijs.download/fix-mask-filters/pixi.js in a state where I can try my actual code against it?

**Comment by ivanpopelyshev** [comment]
yep.

**Comment by jmlee2k** [comment]
Ok, great, I'll try it out and let you know.

**Comment by ivanpopelyshev** [comment]
we just found a critical in separate thread, so you'll have to move to dev version as soon as both PR's get merged.

**Comment by jmlee2k** [comment]
I just tried it on our actual code, and it works great, thanks again!
