### ISSUE TITLE
Container.destroy is mistyped in v5

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi.js#5978]
The JSDoc comments correctly describe that the options param can be either a boolean or an object:
```
* @param {object|boolean} [options] - Options parameter. A boolean will act as if all options
*  have been set to that value
```
However, the fact that the options param can be a boolean is missing from the d.ts file:

```
destroy(options?: {
    children?: boolean;
    texture?: boolean;
    baseTexture?: boolean;
}): void;
```
@englercj  - It looks like tsd-jsdoc should support this, as it appears to be used in other places, but I think this is the only occurrence where the properties of the object are also documented, so perhaps it could be something to do with that.

This also applies to the destroy method of all the subclasses of DisplayObject, as well as GraphicsGeometry.

Currently, I have to manually add "| boolean" to pixi.js.d.ts to get our project to compile without errors:

```
destroy(options?: {
    children?: boolean;
    texture?: boolean;
    baseTexture?: boolean;
} | boolean ): void;
```

I know the eventual plan is to move to TypeScript, which will eliminate this entire class of issues, but until then, I can put a PR together to patch this in assemble.js (unless it should be working and is an issue with tsd-jsdoc).

**Comment by bigtimebuddy** [comment]
This seems more like a bug than something that should be monkey patched in. I’d see if @englercj has any thoughts.

**Comment by jmlee2k** [comment]
I totally agree! :)

**Comment by laino** [comment]
Hello. Just ran into this as well and I found a workaround that isn't too bad.

Basically just define a type for the argument to get tsd-jsdoc to output it correctly. Example:

```
/**
 * @param {boolean|object} [options] - blub
 * @param {boolean} [options.prop=false] - whatever
 */
export function doesntWork(options) {
    console.log(options);
}

/**
 * @typedef {boolean|object} SpriteDestroyOptions - blub
 * @property {boolean} [prop=false] - whatever
 */

/**
 * @param {SpriteDestroyOptions} options
 */
export function works(options) {
    console.log(options);
}
```

``jsdoc -t tsd-jsdoc/dist test.js && cat out/types.d.ts`` produces:
```/**
 * @param {boolean|object} [options] - blub
 * @param {boolean} [options.prop=false] - whatever
 */
declare function doesntWork(options?: {
    prop?: boolean;
}): void;

/**
 * @typedef {boolean|object} SpriteDestroyOptions - blub
 * @property {boolean} [prop=false] - whatever
 */
declare type SpriteDestroyOptions = boolean | {
    prop?: boolean;
};

/**
 * @param {SpriteDestroyOptions} options
 */
declare function works(options: SpriteDestroyOptions): void;
```

**Comment by englercj** [comment]
This looks like a bug in tsd-jsdoc, but a workaround for pixi would be to split it into a typedef which seems to work correctly. Accepting PRs if anyone has time to investigate a fix, or at least wants to write a failing test.

The repo is here: https://github.com/englercj/tsd-jsdoc
