### ISSUE TITLE
Tint fails when redrawing a graphics with 0 size stroke

### ISSUE THREAD

**Issue by MattShaile** [pixijs/pixi.js#5980]
Pixi V4 (I haven't tried V5)

It's a very specific scenario which took me a while to figure out, but I found a simple way to reproduce:

https://jsfiddle.net/80pn9rz2/2/

```
var stage = new PIXI.Stage(0x000000);
var renderer = PIXI.autoDetectRenderer(500, 400);
document.body.appendChild(renderer.view);

var graphics = new PIXI.Graphics();
stage.addChild(graphics);

const draw = () => {
  graphics.clear();
  graphics.lineStyle(0,0,0); // Setting stroke size to 1 fixes this issue
  graphics.beginFill(0xffffff, 0.5);
  graphics.drawRect(20, 20, 20, 20);
}

draw();
graphics.tint = 0xff0000;
renderer.render(stage); // If you redraw before rendering, the tint will remain
draw(); // If you don't redraw after rendering once, the tint will remain in subsequent renders
renderer.render(stage);
```

**What happens:**
Shape is drawn
Shape is tinted
Render
Tint works
Shape is cleared and redrawn
Render
Tint no longer works

**What should happen:**
Tint should remain

**How to reproduce**
See above code / jsfiddle. Specifically, this line is causing the problem:
`graphics.lineStyle(0,0,0);`
If you set stroke size to above 0, the tint will remain.
Note that with or without that line, the tint works initially, it's only after you redraw (after at least one render) that it occurs.

**Comment by eXponenta** [comment]
v5 wors fine.
![image](https://user-images.githubusercontent.com/12572222/62319734-54fe4980-b4a7-11e9-9e20-069226fb2f4f.png)
