### ISSUE TITLE
Bug with `.toDataURL()` after `stage.addChild()`

### ISSUE THREAD

**Issue by Paulooze** [pixijs/pixi.js#5994]
### Expected Behavior
Inverted "mask" should be visible. After the inversion, I need to replace the whole canvas with "raw" image instead of `Sprite` with `BLEND_MODE` set to `ERASE`.
### Current Behavior
Full color image is displayed instead.
### Possible Solution
Whole thing works when I put the code inside `setTimeout`, which is not ideal/expected. It seems like `addChild` behaves kinda async, which means that `app.view.toDataURL()` returns full red image instead of inverted "mask". Maybe you could point me in the right direction.
### Steps to Reproduce
See the attached Codepen, draw something on canvas, then click `Invert` button. Comment line 109 out, and uncomment line 112 - it works now.

### Environment

- **`pixi.js` version**: 5.0.4
- **Browser & Version**: Chrome 75
- **OS & Version**: macOS Mojave 10.14.5
- **Running Example**: https://codepen.io/Paulooze/pen/ymPRKe?editors=1010

**Comment by hdennen** [comment]
Looking at your codepen, the mask is already redrawn in the `invertMask()` function so having a separate redraw function is only adding the inverted square over your drawing area.

I think the reason that putting it in a `setTimeout` works is that it never gets rendered then.

updated codepen here: https://codepen.io/hdennen/pen/qeJwwm?editors=0010

**Comment by ivanpopelyshev** [comment]
> this.app.view.toDataURL();

No guarantees about `getImageData` and `toDataURL` for webgl context.

Please use `extract` plugin, or `readPixels` directly.

If you take image from main framebuffer, you have to do it just after current frame, setTimeout's wont do.

If you want to just make a copy at any time, look at #5903

If you want to take the screen and use as `PIXI.Sprite`, use RenderTexture instead, no need of heavy CPU<->GPU memory copy, its pure GPU stuff. https://pixijs.io/examples/#/textures/render-texture-basic.js
