### ISSUE TITLE
Videos not working anymore on Chrome v76

### ISSUE THREAD

**Issue by borradaniele** [pixijs/pixi.js#5996]
Videos are not working anymore just after updating Google Chrome to v76.
Loading the video (with the app loader) and creating a Sprite using the video as texture does not work anymore. Nothing has been changed in the site source code, I've only updated Chrome. Tested the same site from the same local development server on an older version of Chrome and everything is fine. The error in console is the following

```
WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty
[.WebGL-0x7f861a496800]GL ERROR :GL_INVALID_OPERATION : glTexSubImage2D: level 0 does not exist
```
### Steps to Reproduce
I get the same error on the PIXI official site in the video demo page. And the video is not playing even there.
https://pixijs.io/examples/#/sprite/video.js

### Environment
Mac OS High Sierra 10.13.6
Chrome Version 76.0.3809.87 (Official Build) (64-bit)
PIXI v5.1.1

**Comment by drpepper** [comment]
I have the same problem. I'm also on Mac Mohave 10.14.5, Chrome Version 76.0.3809.87 (Build officiel) (64 bits), PixiJS 5.0.2.

**Comment by nicholas-slepchenko** [comment]
Same problem here
Windows 10
Chrome Version 76.0.3809.87 (Official Build) (64-bit)

**Comment by eXponenta** [comment]
@drpepper @nicholas-slepchenko @borradaniele 
This is problem only with Chrome 76 and later.
Temporary fix:
https://www.pixiplayground.com/#/edit/F1nTXxdf9xfBQt6uTurAM

**Comment by drpepper** [comment]
Thanks @eXponenta !

If understand your fix correctly, the trick is to wait for the promise from the video element's play() method resolve before creating the sprite. I just tried this and it worked for Chrome. However, now Firefox gives me an error and refuses to play the video:

`Error: WebGL warning: drawElements: TEXTURE_2D at unit 1 is incomplete: The dimensions of `level_base` are not all positive.`

**Comment by eXponenta** [comment]
@drpepper Can you create fiddle for this? Because my fix works correct on Firefox.
You must memento what video can't be played before user interaction.

**Comment by borradaniele** [comment]
@eXponenta Thanks for the quick reply and the temp fix, I'm going to implement it in the upcoming days.

**Comment by goswamibodhgaya** [comment]
I need work

**Comment by drpepper** [comment]
I haven't had the time to make a fiddle, sorry.

But I believe the difference for me is that I use the PIXI loader to pre-load the video. The steps I ended up following were:

1) Load the video using the PIXI loader and a custom video element with the plays-inline and muted attributes set.
2) Wait for user interaction
3) Call play() on the video element, and for the promise to resolve
4) On Firefox, wait an addition 100ms. Otherwise I get a WebGL error
5) Create a VideoResource with the pre-loaded video element
6) Create the sprite and display the video 

I'm not very happy with this, especially the extra delay part, but it seems to work so far.

**Comment by meowtec** [comment]
@drpepper @borradaniele 
try this:
```
const video =  document.createElement('video')
video.crossOrigin = 'anonymous'
video.preload = ''
video.src = 'VIDEO_URL'
const sprite = Sprite.from(video)
app.stage.addChild(sprite)

```

also see: #6023

**Comment by dghez** [comment]
Just for information, I had the same problem and I solved it adding `video.preload = 'auto'` and `video.autoload = true` where video is `const video = document.createElement('video')`

**Comment by BH-NOTHING** [comment]
@dghez It works,thank you !

**Comment by BH-NOTHING** [comment]
@dghez But It dosen't work on mobile device, is there any solution?

**Comment by dghez** [comment]
> @dghez But It dosen't work on mobile device, is there any solution?

Weird, I tried on my Oneplus7 with Android 9 and Chrome 76.0.3809.111 and it works. 
Keep in mind that on mobile you probably need to add other stuff like `playsInline` and `muted` to allow autoplay videos

**Comment by Bouh** [comment]
This dosen't work on my phone "Wiko view 3" in webview from chrome.

**Comment by krobibero** [comment]
Still seeing this issue with PixiJS 5.1.2 - WebGL 2
WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty

I'm working with a Dev that has been troubleshooting this issue with his project and unfortunately has not found a fix or workaround.  

Warnings point to:
gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, baseTexture.format, baseTexture.type, source);
gl.texImage2D(baseTexture.target, 0, baseTexture.format, baseTexture.format, baseTexture.type, source);

**Comment by themoonrat** [comment]
Could you try the latest dev version please? https://github.com/pixijs/pixi.js/pull/6088 might have helped this

**Comment by krobibero** [comment]
> Could you try the latest dev version please? #6088 might have helped this

@themoonrat Confirmed video file issue with Chrome and Opera resolved after upgrading to PixiJS 5.1.5.  Many thanks!

**Comment by qiancj1022** [comment]
@krobibero @themoonrat   thanks.

**Comment by nuthinking** [comment]
`video.preload = 'auto';` was enough for me, also because `autoload` is not recognized.

**Comment by lihongyi1234** [comment]
> @drpepper @borradaniele
> 
> Try this:
> 
> ```
> const video =  document.createElement('video')
> video.crossOrigin = 'anonymous'
> video.preload = ''
> video.src = 'VIDEO_URL'
> const sprite = Sprite.from(video)
> app.stage.addChild(sprite)
> ```
> 
> also see: #6023

right!it works

**Comment by marcusx2** [comment]
It works but it breaks Safari. Videos won't play with the preload attribute.
