### ISSUE TITLE
npm will not install any version of v5 except for 5.1.1

### ISSUE THREAD

**Issue by bgenchel** [pixijs/pixi.js#5998]
### Expected Behavior
when, in my package.json, I specify a different version of pixi.js, such as 5.0.4, as in
`"pixi.js": "5.0.4",`
npm install should install that version of pixi.js, and not v5.1.1

### Current Behavior
every time i've tried this, even after deleting `node_modules/` and `package-lock.json`, 5.1.1 is always installed.

Additionally, when the installation is running, in my terminal, I can see it says `pixi.js@5.0.4 postinstall ...`, but when I open my browser and run my app, I get `PixiJS 5.1.1` in the console.

### Possible Solution
I have no idea what the solution could be. I don't really know why this is happening. 

### Steps to Reproduce
in `package.json`, change your pixi.js version to a version above 5, but not 5.1.1, then run `npm install`. Additionally, try first deleting your `node_modules/` folder and `package-lock.json` file.

### Environment

- **`pixi.js` version**:  trying to be any version of 5 besides 5.1.1
- **Browser & Version**: _e.g. Chrome 75.0.3770.142
- **OS & Version**: Mac OSX High Sierra

**Comment by Dawnlee** [comment]
I have the same problem. Have you solved it? I have try set npm config save-exact true,but it does't work.

**Comment by bgenchel** [comment]
I have not unfortunately :(
