### ISSUE TITLE
generateCanvasTexture missing in pixi.js-legacy Graphics

### ISSUE THREAD

**Issue by danrostron** [pixijs/pixi.js#6000]
According to documentation, the following method should exist:

generateCanvasTexture (scaleMode, resolution)PIXI.Texture 

Generates a canvas texture. Only available with pixi.js-legacy bundle or the @pixi/canvas-graphics package.

I can't find it in either pixi.js-legacy or @pixi/canvas-graphics. How can I migrate code using this?

**Comment by eXponenta** [comment]
Look this:
https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-graphics/src/Graphics.js
