### ISSUE TITLE
OffscreenCanvasRenderingContext2D.measureText in UC Browser

### ISSUE THREAD

**Issue by AleXNoD** [pixijs/pixi.js#6006]
An error was detected on line 30868 in pixi.js 5.1.1 in UC Browser.
var width = Math.ceil (context.measureText (metricsString) .width);

Error:
pixi.js? 2: 30870 Uncaught TypeError: context.measureText is not a function

I think UC Browser has no method measureText in OffscreenCanvas.

- **`pixi.js` version**:  5.1.1
- **Browser & Version**: UC Browser
- **OS & Version**: Win 10

**Comment by ivanpopelyshev** [comment]
Summoning @fserb

**Comment by ivanpopelyshev** [comment]
@AleXNoD you know the workaround, right? 

https://github.com/pixijs/pixi.js/blob/dev/packages/text/src/TextMetrics.js#L726

Should be something like that:

```js
function hackTextMetrics(TextMetrics) {
    TextMetrics._canvas = document.createElement('canvas');
    TextMetrics._canvas.width = 10;
    TextMetrics._canvas.height = 10;
    TextMetrics._context = TextMetrics._canvas.getContext('2d');
}

hackTextMetrics(PIXI.TextMetrics);
```

**Comment by fserb** [comment]
That's weird. I didn't know there were browsers out there with Canvas2D but no measureText. 

Assuming that this is the problem, we can just change line [709](https://github.com/pixijs/pixi.js/blob/dev/packages/text/src/TextMetrics.js#L709) from:

```
 return c.getContext('2d') ? c : document.createElement('canvas');
```

to

```
 return c.getContext('2d').measureText ? c : document.createElement('canvas');
```

I'll play with UC Browser a bit and will report back.

**Comment by fserb** [comment]
ok. I just checked `UC v12.12.8.1206`.

It doesn't have `window.OffscreenCanvas`. Pixi.js's `canvas =` function is returning `HTMLCanvasElement`.
Could it be that `TextMetrics.measureText` is being called before the constructor?

**Comment by monicaleerich** [comment]
What the fuck fernando
