### ISSUE TITLE
I need some help about create AnimationSprite

### ISSUE THREAD

**Issue by WeiFree** [pixijs/pixi.js#6012]
i create some AnimationSprites but when it in some mobile it will slowly
![image](https://user-images.githubusercontent.com/20769663/63010429-f37fa700-beb8-11e9-979f-5418c005044f.png)

`pixi.js` version**: _e.g. 4.8.8_

**Comment by ivanpopelyshev** [comment]
It should work. Give us more information.

**Comment by WeiFree** [comment]
when i create it in same time to play the video ,the video will skip some time.

**Comment by WeiFree** [comment]
Also when i change the contain visible  also solwly

**Comment by WeiFree** [comment]
![image](https://user-images.githubusercontent.com/20769663/63013100-0d6fb880-bebe-11e9-93d9-bfebf6ce3d9a.png)
i use this to create AnimationSprite

**Comment by ivanpopelyshev** [comment]
If you mean problem with the first frame - if its the first time texture is shown - there will be lag.

Look in issues and in forums and in docs about `PIXI.prepare`, it should help.
