### ISSUE TITLE
'texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering

### ISSUE THREAD

**Issue by uahic** [pixijs/pixi.js#6014]
### Expected Behavior
A clear error message, whether its a power-of-2 issue or too large texture in general

### Current Behavior

When loading large arrayBuffers via PIXI.Texture.fromBuffer(array), my colleges get the following error on (some, but not all of) their devices (e.g.  Samsung Tablet (SM-T580) or Xiaomi Mi9). On my laptop, however, it works fine (Thinkpad P51 with dedicated GPU)

> 'texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering

I am not really sure if the texture is just too large (my assumption) or of the array is malformed. On significantly smaller images it works perfectly fine even on the mobile devices. I think none of our images have dimensions to the power of 2.

The images are basically indoor maps and can be very large in warehouses. Are there any tiling implementations for pixi that work well? Thanks!

### Steps to Reproduce
Load some image via Texture.fromBuffer(.) that is slightly larger than 4000 x 4000 px 

### Environment

- **`pixi.js` version**:  5.0.4.
- **Browser & Version**:   Chrome 73.0.36 (64 bit) & Firefox 68.0.1 (64 bit)
- **OS & Version**:  Ubuntu 18.04/Ubuntu 16.04

**Comment by ivanpopelyshev** [comment]
Most mobile devices have 4096 as a limit.

**Comment by uahic** [comment]
As usual, thank you very much (especially for your quick response ;)) 
Is this a per-texture limit or a total-texture-memory-limit?

**Comment by themoonrat** [comment]
It's a per texture limit. You can find it under max texture size https://webglreport.com/
A lot of mobile devices have that at 4096x4096

**Comment by linonetwo** [comment]
I get this when I use Buffer loaded by nodejs's fs:

```js
// renderer preload script
const { ipcMain } = require('electron');
const path = require('path');
const fs = require('fs').promises;

ipcMain.handle('get-texture', async (event, textureIRI) => {
  const modFolder = path.join(__dirname, '../../src/mods/core/textures');
  const textureLocation = path.join(modFolder, textureIRI);
  const result = await fs.readFile(textureLocation);
  return result;
});

contextBridge.exposeInMainWorld('mod', {
  getTexture: textureIRI => ipcRenderer.invoke('get-texture', textureIRI),
});

// renderer game side
const resourceDetailName = `${resourceName}_${facing}`;
const resourceBuffer = await window.mod.getTexture(
 `Heads/Female/${resourceDetailName}.png`,
);

// ...
new PIXI.Texture.fromBuffer(resources[`${randomHeadName}_${pawnFacing.NORTH}`], 256, 256)

```

The image will be loaded with a black background, instead of transparent background of png.

And it run with following error:

```
core.es.js:818 WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request
./node_modules/@pixi/ticker/lib/ticker.es.js.TickerListener.emit @ ticker.es.js:129
./node_modules/@pixi/ticker/lib/ticker.es.js.Ticker.update @ ticker.es.js:583
:40992/#/main:1 [.WebGL-0x7f9e6d04d400]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
254[.WebGL-0x7f9e6d04d400]RENDER WARNING: texture bound to texture unit 1 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
:40992/#/main:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Comment by bigtimebuddy** [comment]
You’ll need to decode the png into raw image data (pixels) not the file buffer read directly. There are lots of utilities on npm that you can use for this.

**Comment by linonetwo** [comment]
Thank you!

This works:

```js
const PNG = require('png-js');

function parsePng(filePath) {
  return new Promise(resolve => {
    PNG.decode(filePath, pixels => {
      // pixels is a 1d array (in rgba order) of decoded pixel data
      resolve(pixels);
    });
  });
}

ipcMain.handle('get-texture', async (event, textureIRI) => {
  const modFolder = path.join(__dirname, '../../src/mods/core/textures');
  const textureLocation = path.join(modFolder, textureIRI);
  const result = await parsePng(textureLocation);
  return result;
});
```

**Comment by findthebug** [comment]
had similar problems, but with an PIXI.Text Element. The problem was uppercase text. If i set the text via js from an html data attribute older iOS devices and chrome browser wont render this. If i hardcode the text inside PIXI.Text it works.
