### ISSUE TITLE
Masking with canvas

### ISSUE THREAD

**Issue by ShimaMax** [pixijs/pixi.js#6015]
### Expected Behavior
I want to load [this](https://pixijs.io/examples/#/demos-advanced/scratchcard.js) example in canvas. But anything goes wrong.
### Current Behavior
Mask isn't applied to "bg_rotate.jpg" image.
### Possible Solution
Need to fix masking in Canvas. 
### Steps to Reproduce
Just run this example with pixi-legacy.js v5.0.4.
```
const app = new PIXI.Application({
	forceCanvas: true
});
```
### Environment

- **`pixi.js` version**: 5.0.4 legacy
- **Browser & Version**: Chrome 76
- **OS & Version**: windows 10
- **Running Example**: https://pixijs.io/examples/#/demos-advanced/scratchcard.js

**Comment by themoonrat** [comment]
Sprite based masks aren't supported on the canvas renderer

**Comment by ShimaMax** [comment]
Maybe I can use graphics primitives instead of:
```
const renderTexture = PIXI.RenderTexture.create(app.screen.width, app.screen.height);
const renderTextureSprite = new PIXI.Sprite(renderTexture);
stage.addChild(renderTextureSprite);
imageToReveal.mask = renderTextureSprite;
```
because only what I need is to mask with rectangle.
But this code:
```
const renderTexture = new PIXI.Graphics();
renderTexture.beginFill(0xffffff);
renderTexture.drawRect(0, 0, app.screen.width, app.screen.height);
renderTexture.endFill();
stage.addChild(renderTexture);
imageToReveal.mask = renderTexture;
```
also doesn't work.

**Comment by ivanpopelyshev** [comment]
HEre's version with just blendMode, it works both in WebGL and in Canvas.

Relative to original example - it has 3 changes.

https://www.pixiplayground.com/#/edit/PuQ5~sGEpxcTGuBfH96SV

**Comment by ShimaMax** [comment]
When I tried start it on localhost, it doesn't work (https://www.pixiplayground.com load example with WebGL while on my computer example load with canvas)

**Comment by ivanpopelyshev** [comment]
remove `app.loader.baseUrl = 'https://pixijs.io/examples/';` and host assets locally.
