### ISSUE TITLE
Add types for @pixi packages

### ISSUE THREAD

**Issue by leomeloxp** [pixijs/pixi.js#6016]
As previously discussed in #5397 it would be extremely useful if we had types for the individual `@pixi/*` packages. 

Is there a way to get around the missing type definitions at the moment that wouldn't involve `import { Container } from 'pixi.js';`?

### Expected Behavior

```ts
import { Container } from '@pixi/display';

// Container type exists
```

### Current Behavior

```ts
import { Container } from '@pixi/display';

// Container type doesn't exist
```

### Possible Solution

Add type definition files to each PIXI module or add type definitions for each PIXI module to DefinitelyTyped

### Steps to Reproduce

- Use Typescript
- Import any pixi module from an @pixi/* package
- Find that no type definition exists

### Environment

- **`pixi.js` version**: _5.x.x_
- **Browser & Version**: _N/A_
- **OS & Version**: _N/A_
- **Running Example**: _N/A_

**Comment by guansss** [comment]
Currently I'm using TypeScript's [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) as a workaround:

```typescript
// pixi-shim.d.ts

declare module '@pixi/display' {
    export { Container } from 'pixi.js';
}

declare module '@pixi/math' {
    export { Matrix, Point } from 'pixi.js';
}
```

This only works on types which are directly under `PIXI` namespace, I still have no idea how to get the types inside nested namespaces.

For example, `InteractionManager` is inside `PIXI.interaction` in `pixi.js`, I couldn't find a way to extract `InteractionManager` from `pixi.js` and then export it to `@pixi/interaction` module.

**Comment by bigtimebuddy** [comment]
We are planning to moving the source code to TypeScript soon. It's a big project but will allow us to produce types accurately for all packages. Short-term, it's best to use @guansss's suggestion of module augmentation.

**Comment by bigtimebuddy** [comment]
If you would like to support us with TypeScript migration right now, please consider becoming a sponsor on [Open Collective](https://opencollective.com/pixijs). This is one of our top priorities for this year.
