### ISSUE TITLE
There are any attribute 'MeshRenderer' on PIXI.

### ISSUE THREAD

**Issue by zhfhz** [pixijs/pixi.js#6017]
Is it be lost?

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
I dont understand the question. In v4 its in `PIXI.mesh.MeshRenderer`. 

If you need advanced mesh for pixi-v4 you can look here: 

https://github.com/gameofbombs/pixi-heaven/tree/v4.x/
https://github.com/gameofbombs/pixi-heaven/tree/v4.x/src/mesh
https://gameofbombs.github.io/examples-heaven/#/mesh/plane.js

Is there any special cause why do you use 4.7.1 and not stable 4.8.8? What about moving to v5?

**Comment by zhfhz** [comment]
ver5.0



---Original---

**Comment by ivanpopelyshev** [comment]
in v5 its separated to `Mesh._renderDefault` and `Mesh._renderToBatch`

https://github.com/pixijs/pixi.js/blob/dev/packages/mesh/src/Mesh.js#L275

Shader and parameters are configured inside MeshMaterial, you can extend it:

https://github.com/pixijs/pixi.js/blob/dev/packages/mesh/src/MeshMaterial.js

Here's why we made it: https://pixijs.io/examples/#/mesh/triangle-textured.js . You can set custom shader without creating MeshRenderer.
