### ISSUE TITLE
lineTo connections are not smooth

### ISSUE THREAD

**Issue by baunov** [pixijs/pixi.js#6026]
### Expected Behavior
Consecutive calls of graphics.lineTo() should draw a single connected line without visible connections/overlaps.

### Current Behavior
If lineStyle width is big enough and line alpha is < 1 - you can clearly see where the lines are connected. Looks like each line is drawn on top of the previous one and not actually connected.

<img width="757" alt="Снимок экрана 2019-08-20 в 13 39 52" src="https://user-images.githubusercontent.com/54023692/63340568-07f7ef80-c350-11e9-89ac-824f357df5f9.png">

I was using canvas before to perform those operations and line was smooth with no overlaps.

### Steps to Reproduce
1. Set lineStyle width to something like 20 and alpha to 0.5
2. Create an array of points that are close to each other with some overlaps.
3. Draw a line from those points.

### Environment

- **`pixi.js` version**:5.1.1
- **Browser & Version**: _e.g. Chrome 67_

**Comment by ivanpopelyshev** [comment]
Its probably a problem with sharp edges. Cant solve it yet, we dont have LineJoin and other things :(

**Comment by ivanpopelyshev** [comment]
Do you know workaround for that?

**Comment by trippyVaibhav** [comment]
is there any solution for it now ?

**Comment by ivanpopelyshev** [comment]
Try use graphics-smooth?
