### ISSUE TITLE
Sprite doubled in size on retina screen

### ISSUE THREAD

**Issue by CHENXINNN** [pixijs/pixi.js#6029]
I have a problem about retina display, let's take iPhone 6 for example. The size of the screen is 375x667, and the device pixel ratio is 2, which means the physical pixel is 750x1334 and the CSS pixel is 375x667.

If we want a full screen canvas, what we usually do is to set the canvas size to 750x1334, and then set the actually display size of canvas to 375x667.

This is what I have done in pixi.js(v5.1.1):

```

let app = new Application({
    width: 375,
    height: 667,
    antialiasing: true,
    resolution: 2,
    autoDensity: true,
})
```
I set the `resolution : 2`, and `autoDensity : true`, but when I add a sprite with size of 750x1334, it only shows a quarter of the sprite(The size is doubled). It seems that the `autoDensity` is not working.

What now I am doing is setting the whole stage with `scale(0.5)`:

```
app.stage.scale.set(0.5);
```

It temporarily solved my problem, but I feel like this is not the current way to go. You shouldn't use scale for this kind of thing.

What should I do then?

**Comment by ivanpopelyshev** [comment]
> but when I add a sprite with size of 750x1334, it only shows a quarter of the sprite

Textures also have resolution. Use `myImage@2x.png` instead of `myImage.png`.

Explanation: if you have 375x667 screen, sprite of size 375x667 will always cover all the screen, no matter the resolution. Changing resolution should add pixels, it shouldn't affect the scene! 182.5 is always the center, whether its resolution=2,3 or 4.

You load 750x1334 - of course its bigger then screen! Either you specify that texture also has resolution=2, either you scale down the sprite.

It takes some time to understand those things, they are the same in all 2d renderers,  both web and native.

**Comment by tuuling** [comment]
Is there a way to set the resolution of a texture in code?
For example when an image is a base64 encoded url string. A common occurrence if using webpack url-loader like this:

```
import houseimg from './images/house@2x.png';

app.loader.add('house', houseimg).load...
```

Using pixijs 5.3.3

**Comment by tuuling** [comment]
> Is there a way to set the resolution of a texture in code?
> For example when an image is a base64 encoded url string. A common occurrence if using webpack url-loader like this:
> 
> ```
> import houseimg from './images/house@2x.png';
> 
> app.loader.add('house', houseimg).load...
> ```
> 
> Using pixijs 5.3.3

So I found a solution that works great for me.

```
import house from '../images/house.png';

const app = new Application({
  resizeTo: window,
  resolution: 2,
  autoDensity: true,
  antialias: false,
  backgroundColor: 0xFFFFFF
});

const baseTexture = new BaseTexture(house, { resolution: 2 });
const sprite = new Sprite(new Texture(baseTexture))

```

With the following webpack config/plugins:

```
module: {
        rules: [
...,
            {
                test: /\.(png|jpg|gif)$/i,
                use: [
                    {
                        loader: 'url-loader',
                        options: {
                            limit: 1024
                        }
                    }
                ]
            }
        ]
    },
```
