### ISSUE TITLE
Repeating sprite with same texture gets 'smeared' occasionally, when refreshing with no code change.

### ISSUE THREAD

**Issue by lancewellspring** [pixijs/pixi.js#6030]
EDIT: Figured it out myself, but this raises an interesting question.  See comments below.

### Expected Behavior
Sprite appears with repeating texture (top of attached image)
### Current Behavior
Refresh enough times, and the row of repeating sprites will appear smeared (bottom of attached image)
### Steps to Reproduce
Keep refreshing until you see it
### Environment

- **`pixi.js` version**: 5.1.1
- **Browser & Version**: Chrome 76.0.3809.100
- **OS & Version**: Windows 10
- **Running Example**: http://undefinedx.com:7023/lanceTest

![image](https://user-images.githubusercontent.com/6957193/63483619-04a55680-c46b-11e9-909a-295098c50baa.png)

**Comment by lancewellspring** [comment]
relevant code:

`
class AssetLibrary{
        static newSprite(texName){
		if(!AssetLibrary.textures[texName])
			AssetLibrary.textures[texName] = new PIXI.Texture(PIXI.BaseTexture.from(texName));
		return new PIXI.Sprite(AssetLibrary.textures[texName]);
	}
}

for(var w = 0, var r; w < this.gridRight; w+=r.width){
	var r = AssetLibrary.newSprite("images/river.png");
	r.scale.set(.5);
	r.position.set(w, this.gridBottom);
	app.stage.addChild(r);
}
`

**Comment by lancewellspring** [comment]
While piecing together the relevant code, I realized that I hadn't (or accidentally deleted?) loaded this image with app.loader.  I went ahead and added it and now the problem seems to have been fixed.  But still, why would that cause this problem?

**Comment by ivanpopelyshev** [comment]
`BaseTexture.from` works even without loader, and images will be shown later in a few frames, but you cant get width/height before that :) `r.width` is 1 in your case, that's not a smear, that's a huge number of sprites!

Either use `app.loader` and wait for completion, either hard-code that width in your code.

**Comment by lancewellspring** [comment]
Ah that makes sense, thank you!
