### ISSUE TITLE
IHitArea missing in pixi.js-legacy

### ISSUE THREAD

**Issue by fffyyyyy** [pixijs/pixi.js#6031]
Hi

I found IHitArea in PixiJS Documentation and also can get it in pixi.js. But I can not get IHitArea from pixi.js-legacy. I need IHitArea because I want to override hitArea contains function.

Thanks!

### Expected Behavior
can get IHitArea from pixi.js-legacy
### Current Behavior
check the interface of hitArea in pixi.js-legacy.
- hitArea: PIXI.Rectangle | PIXI.Circle | PIXI.Ellipse | PIXI.Polygon | PIXI.RoundedRectangle;

### Environment

- **pixi.js-legacy version**: 5.0.4

**Comment by mofnire** [comment]
`PIXI.IHitArea` was introduced in the version 5.1.0.
Please refer to the v5.1.0 release note.

> Change DisplayObject#hitArea type declaration to support more hit-area classes (#5827)

https://github.com/pixijs/pixi.js/releases/tag/v5.1.0

**Comment by fffyyyyy** [comment]
> `PIXI.IHitArea` was introduced in the version 5.1.0.
> Please refer to the v5.1.0 release note.
> 
> > Change DisplayObject#hitArea type declaration to support more hit-area classes (#5827)
> 
> https://github.com/pixijs/pixi.js/releases/tag/v5.1.0

It works！Thanks！
