### ISSUE TITLE
.roundCoordinates on any kind of container

### ISSUE THREAD

**Issue by laino** [pixijs/pixi.js#6037]
It is easy to emulate by just doing ``container.x = Math.round(x)``**, but it would be nice
to have this as a consistent feature across all elements. Maybe call it ``roundCoordinates`` (doesn't have to be same behavior as ``roundPixels``, necessarily).

Then I could still use the real ``x`` for computations, but wouldn't have to worry about some of my UI graphics becoming blurry because their containers are offset by half a pixel or something.

Right now  I have to keep track of the real ``x`` and the integer ``x`` separately. And on top of that make sure no parent container does something funky. 

** This may go horribly wrong if there are transforms that are not translations. But in that case your graphics are going to be blurred anyways. For X, Y translations this feature should make sure that the final coordinates are rounded.

So if we have this:
```js
const interfaceContainer = new pixi.Container();
// add my pixel-perfect interfecace stuff to interfaceContainer

interfaceContainer.roundCoordinates = true;

const parentContainer = new pixi.Container();

parentContainer.addChild(interfaceContainer);
parentContainer.x = 10.3;
```

Pixi should draw my interface container at ``x = 10``.

**Comment by eXponenta** [comment]
I think you must extends Container in your class and use this features, without implementation in Core.
Pixi shouldn't do all of what do you want.

**Comment by ivanpopelyshev** [comment]
There's a way to override transforms: https://github.com/pixijs/pixi.js/wiki/v5-Hacks#ignore-parent-scale--rotation

There are many things that can be added in pixi transforms: big ones like https://github.com/pixijs/pixi-projection/blob/master/src/base/LinearProjection.ts and HUGE like https://github.com/pixijs/pixi-spine/blob/master/src/core/Bone.ts#L94

Imagine what will happen if we add all of them in our core ;)
