### ISSUE TITLE
Sprite size inconsistency depending on parent.

### ISSUE THREAD

**Issue by lancewellspring** [pixijs/pixi.js#6046]
### Expected Behavior
Two sprites that are set up with identical sizes should be rendered as the same size.
### Current Behavior
The 2 identical sprites are rendered at different sizes.

### Steps to Reproduce
https://codepen.io/Lancer611/pen/YzKVEEd

The green squares are set up with identical values.  However, s3 is added as child of s, while t3 is added as child of t2.  Why does the parent affect the rendered size of the child?  Shouldn't the child's size be unaffected by its parent?

### Environment

- **`pixi.js` version**: 5.1.1
- **Browser & Version**: Chrome 75.0.3770.142
- **OS & Version**: Windows 10
- **Running Example**: https://codepen.io/Lancer611/pen/YzKVEEd

**Comment by ivanpopelyshev** [comment]
Because its same in Flash.

There are many hacks that can help with that, I dont know even which one to recommend ...

My attempt at making frame size independent from scale was rejected 4 years ago.
