### ISSUE TITLE
Proper use of Sprite.shader

### ISSUE THREAD

**Issue by hanna-greaves** [pixijs/pixi.js#6049]
Hi there!

I have been using PixiJS and really enjoy it, its a great library. Thank you so much for all of your hard work <3 

I am interested in the proper use of the [`shader`](https://pixijs.download/dev/docs/PIXI.Sprite.html#shader) field on a `Sprite` object. I'd love to be able to use this in my application, but cannot seem to work it out. I'd really prefer to set the shader directly, rather than using a `Filter` (as I am drawing a huge number of sprites in a `ParticleContainer`).

Please see the below example, I have applied a fragment shader intended to render the circle red, however it does not seem to have any effect. Is it not possible to use Shaders in this case?

https://www.pixiplayground.com/#/edit/flErmN0_OQs1h8R4C752y

Sorry if this is a noob question!

**Comment by eXponenta** [comment]
When you use custom shader - you disable batcher, performance drops to critical on huge sprite count.
There not simple way for overriding standard batch render without creating custom Renderer .

**Comment by hanna-greaves** [comment]
I see, thank you for the info! 👍

**Comment by ivanpopelyshev** [comment]
> I'd really prefer to set the shader directly, rather than using a Filter (as I am drawing a huge number of sprites in a ParticleContainer).

ParticleContainer has its own shader, and so far i didnt see ParticleContainer hacks with custom shadeys. Though I dont see a problem if you already know how to make pixi shaders :) Go for it!

**Comment by laino** [comment]
It's still broken. Please re-open.
