### ISSUE TITLE
Cut corners of stroked rectangle drawn with bezierCurveTo

### ISSUE THREAD

**Issue by dylanbox** [pixijs/pixi.js#6052]
### Expected Behavior
The `bezierCurveTo` Graphics should be able to draw stroked, closed rectangles with control points equal to the vertexes without error.

### Current Behavior
Currently, on stroked rectangles built with bezier curves, larger drawn rectangles will have their corners cut off at 45 degree angles.

![image](https://user-images.githubusercontent.com/487275/63891327-eed7ea00-c9b2-11e9-97f9-d13c8953c19b.png)
1. The top yellow rectangle is a smaller rectangle showing a correct drawing method.
2. The middle cyan rectangle is shows the smallest size where this starts happening, resulting in one cut corner.
3. The bottom magenta rectangle shows this occurring on all corners of the rectangle

### Possible Solution
Drawing this shape with `drawRect` or `drawPolygon` don't show this same issue, but due to some intricacies of our app, we have to use bezier curves.

### Steps to Reproduce
[Example Here](https://www.pixiplayground.com/#/edit/15uWvOm~waxyYVM56QF50)
Also, If you toggle closing the path, you can see that the cut is where the unclosed path should be filled in

### Environment

- **`pixi.js` version**: _5.1.2_
- **Browser & Version**: _Chrome 76.0.3809.100_
- **OS & Version**: _=MacOS 10.14.5_
- **Running Example**: https://www.pixiplayground.com/#/edit/15uWvOm~waxyYVM56QF50

**Comment by eXponenta** [comment]
There is a `aligment` parameter of line style, it  shifts points by normal.
Default value is 0.5, set it to 0 and corners not be cutted, or dot'n use curves for Rects, because beziers generate 2 points for corner instead of 1 for rect. This is'n bug.

![image](https://user-images.githubusercontent.com/12572222/63921786-1c24a680-ca4c-11e9-8738-f3eeb3f161aa.png)

**Comment by ivanpopelyshev** [comment]
Yep, there's a problem with our bezier, its strange that I cant find previous issue. Your test is a good one, thanks!

**Comment by mattkahl** [comment]
Should this be closed as "Won't Fix"? I realize that it's stale, but the issue remains.

Thoughts?

**Comment by dylanbox** [comment]
I'll note that the issue seems to have become more pronounced on the latest releases. This is v5.2.1:
![image](https://user-images.githubusercontent.com/487275/75810007-b943fd00-5d57-11ea-963f-6957345ed0b4.png)
