### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [pixijs/pixi.js#6055]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io

**Comment by markalzate13** [comment]
are you the respective owner?

**Comment by markalzate13** [comment]
If you are the respective owner just a head up I am doing all I can to
protect this data.

**Comment by lastmjs** [comment]
I'm not sure what you mean?

**Comment by ivanpopelyshev** [comment]
npm-based funding, wow. much crypto.

**Comment by bigtimebuddy** [comment]
We are not interest in Ethereum donations at this time. Thanks for the suggestion.
