### ISSUE TITLE
GraphicsGeometry calculateBounds not taking alignment into account

### ISSUE THREAD

**Issue by lwallent** [pixijs/pixi.js#6056]
### Prologue
I wanted to make a pull request with a fix, but `npm test` is failing with the message:

`Error: Unable to find Electron. Install 'electron' alongside Floss. `

I tried to install electron and floss globally but that didn't fix the issue. Same problem for both _master_ and _dev_.

Suddenly I had two problems instead of one :-)

### Expected Behavior
When drawing with a line style having an alignment different from 0.5 the `GraphicsGeometry` bounds are not calculated correctly.
 
The correct bounds calculation can be seen in the previous [updateLocalBounds](http://pixijs.download/dev/docs/core_graphics_Graphics.js.html) implementation.

### Current Code

```
  GraphicsGeometry.prototype.calculateBounds = function calculateBounds ()
        {

      ...
                for (var i = 0; i < this.graphicsData.length; i++)
                {
                    var data = this.graphicsData[i];

                    var type = data.type;
                    var lineWidth = data.lineStyle ? data.lineStyle.width : 0;

                    shape = data.shape;

                    if (type === math.SHAPES.RECT || type === math.SHAPES.RREC)
                    {
                        x = shape.x - (lineWidth / 2);  <<<<<
                        y = shape.y - (lineWidth / 2); <<<<<
                        w = shape.width + lineWidth; <<<<<
                        h = shape.height + lineWidth; <<<<<
   ....
```
Same for CIRC and ELIP

### Correct Solution
The bounds needs to reflect the alignment like in the old implementation:
    
 ```
for (var i = 0; i < this.graphicsData.length; i++)

            {
                var data = this.graphicsData[i];

                var type = data.type;
                var lineWidth = data.lineStyle ? data.lineStyle.width : 0;
                var lineAlignment = data.lineStyle ? data.lineStyle.alignment : 0.5;
                var lineOffset = lineWidth * lineAlignment;

                shape = data.shape;

                if (type === SHAPES.RECT || type === SHAPES.RREC)
                {
                    x = shape.x - lineOffset;
                    y = shape.y - lineOffset;
                    w = shape.width + 2 * lineOffset;
                    h = shape.height + 2 * lineOffset;
```
I would like to make a Pull Request, but not being able to run the test suite kind of makes me not want to do so.

Thanks for a great library.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/pull/5991

Try pixijs.download/dev/pixi.js

**Comment by bigtimebuddy** [comment]
We could use some more details about electron issue. 

What version of npm/node and what operating system? Also please do a clean npm install my deleting your node_modules and see if that helps? 

Graphics bounds issue should be fixed like Ivan said but I’ll keep this open for sorting the electron issue.

**Comment by lwallent** [comment]
@ivanpopelyshev, super - can you say when that fix is released?

@bigtimebuddy, my bad turns out that specific terminal window was running an old version of node.  Test as running fine now, thanks.

**Comment by eXponenta** [comment]
@lwallent 5.2

**Comment by dylanbox** [comment]
@lwallent I didn't see an example of this occurring in your original post, is this the behavior that you're seeing?

![image](https://user-images.githubusercontent.com/487275/65049960-a28a2500-d934-11e9-82c3-0797cbcdcb0d.png)

[Pixi Playground Example](https://www.pixiplayground.com/#/edit/2KIe0eR3Ftn~RDeYpCmSl)

**Comment by ivanpopelyshev** [comment]
@dylanbox Its different in dev: https://www.pixiplayground.com/#/edit/PxCgDoE88v_sfxQThrPWF , it doesnt account for miters, I'll check it in Flash later.
