### ISSUE TITLE
Pixi vector logo?

### ISSUE THREAD

**Issue by ArondeParon** [pixijs/pixi.js#6057]
Hi,

Short non-code question: is there a PixiJS SVG logo available for download somewhere? We're building a showcase of stuff that we built and the frameworks we have used to do so and I'm looking for an SVG logo that I can use.

**Comment by themoonrat** [comment]
The PixiJS examples uses an svg version of the logo
https://pixijs.io/examples/img/logo.svg

**Comment by ArondeParon** [comment]
Nice, thanks! 👍
