### ISSUE TITLE
PIXI.Texture.fromBuffer posible bug

### ISSUE THREAD

**Issue by developer-av** [pixijs/pixi.js#6059]
### Expected Behavior
A red square will be drawn
### Current Behavior
if forceCanvas set to true a red square will not be drawn
### Steps to Reproduce
```
let pixi = new PIXI.Application({
    width: 100,
    height: 100,
    forceCanvas: true,
});
let buff = new Uint8Array(100 * 100 * 4);
for (let i = 0; i < 100 * 4 * 100; i++) {
    buff[i * 4] = 255;
    buff[i * 4 + 1] = 0;
    buff[i * 4 + 2] = 0;
    buff[i * 4 + 3] = 255;
}
let texture = PIXI.Texture.fromBuffer(buff, 100, 100);
let sprite = PIXI.Sprite.from(texture);
pixi.stage.addChild(sprite);
```
### Environment

- **`pixi.js` version**: 5.1.2
- **Browser & Version**: windows 10
- **OS & Version**: Chrome 76.0
- **Running Example**: [https://jsfiddle.net/developer_av/x3khg2p1/](https://jsfiddle.net/developer_av/x3khg2p1/)

**Comment by ivanpopelyshev** [comment]
TextureResource's dont work with forceCanvas. We didnt implement it.
