### ISSUE TITLE
Texture frame with zero width/height

### ISSUE THREAD

**Issue by namark** [pixijs/pixi.js#6063]
Hello, I was wondering what is the reason of considering a texture frame with zero width or height invalid, and not updating the UVs when such a frame is set.
https://github.com/pixijs/pixi.js/blob/873b65041bd3a5d173b0e0e10fa93be68bc033d9/packages/core/src/textures/Texture.js#L548

I've implemented a simple progress bar using this and occasionally when the progress immediately drops to zero the bar remains stuck in the previous state. Removing the width/height check seems to fix the problem for me, without causing any other issues.

**Comment by bigtimebuddy** [comment]
Is there a reason you’re animating the Texture’s frame and not the Sprite’s scale/width?

**Comment by eXponenta** [comment]
> Is there a reason you’re animating the Texture’s frame and not the Sprite’s scale/width?

I think he crops image without using masking, this it pretty cheap and easy way. BUT framw.width = 0 and frame.height = 0 is  inlegal state.

**Comment by namark** [comment]
Yes I'm using the frame as a rectangular mask as it seemed like the easiest way. Also as I understand the usual mask approach would be more expensive and sprite's scale/width would stretch the image instead of masking/cropping.

There are probably a number of ways I could work around this for the purposes of a progress bar, so this more of a question regarding the zero width/height case in general.

The issue I'm having doesn't seem to affect any recent versions of PIXI, since I'm guessing invalid textures are not rendered (in my case they were rendered with outdated UVs), so really just a question for sanity of an old fork.

**Comment by ivanpopelyshev** [comment]
Wait, how actually does it stay in that state when do you change width later? Any ideas?

**Comment by namark** [comment]
I've put together a minimal example
```javascript
var renderer = new PIXI.WebGLRenderer(400, 400);
renderer.backgroundColor = 0;
document.body.appendChild(renderer.view);

const graphics = new PIXI.Graphics();
graphics.beginFill(0xffffffff);
graphics.drawRect(0, 0, 2, 2);
graphics.endFill();

const sprite = new PIXI.Sprite(renderer.generateTexture(graphics));
sprite.width = 200;
sprite.height = 50;
sprite.x = 200;
sprite.y = 200;
sprite.anchor.set(0.5);

const stage = new PIXI.Container();
stage.addChild(sprite);

renderer.render(stage);

const frame = sprite.texture.frame;
frame.width = 0;
sprite.texture.frame = frame;

renderer.render(stage);
```

Now that I have this, it seems like I lied, it does affect latest v4.
The project I'm working on is stuck with v4.4.4 though. 

[jsfiddle with v4.8.8](https://jsfiddle.net/hm3s87z2/)

**Comment by EneaEntertainment** [comment]
try calling sprite.texture._updateUvs(); after you set new frame width

**Comment by ivanpopelyshev** [comment]
if `_updateUvs()` helps, we can close this issue, because I'm certain that there wont be fix like that in v4.x  . We rewrote it in v5, if people want to get more comfortable, they can spend time moving app to new version.

**Comment by namark** [comment]
Sure _updateUVs() helps, but I went with removing the width/height check instead, so I was expecting some scolding on that approach, if anyone has in mind what the check is for.

And yes, feel free to close if it's too much to fix in v4.
