### ISSUE TITLE
Can I use pixi legacy with Rollup?

### ISSUE THREAD

**Issue by egaoneko** [pixijs/pixi.js#6064]
I need to use pixi legacy to support when WebGL is disabled.

So I try to use pixi.js-legacy, but it does not work with Rollup.

It occur like under error with [this line](https://github.com/pixijs/pixi.js/blob/dev/bundles/pixi.js-legacy/src/index.js#L21).

```
 Uncaught TypeError: Cannot define property CanvasPrepare, object is not extensible
```

I think it is occurred by [this reason](https://github.com/rollup/rollup-plugin-commonjs#strict-mode).

Is there another way to use pixi legacy?

### Environment

- **`pixi.js` version**: _5.1.2_
- **Browser & Version**: _All browser with disabled WebGL_
- **OS & Version**: _All OS_

**Comment by ivanpopelyshev** [comment]
Yes, you can, its supposed to work. 

If you or someone else finds whats wrong with it. Maybe its something about default exports? we just refactored it in `dev` branch.

**Comment by bigtimebuddy** [comment]
If the `Object.assign` is the issue, there are definitely other ways that we can handle that. It would be helpful if @egaoneko you could create a simple repo that reproduce this? That would be very helpful.

**Comment by egaoneko** [comment]
@ivanpopelyshev 
I'll try with dev branch.

@bigtimebuddy 
I made a simple repo for test.

https://github.com/egaoneko/pixi-test

And this is a test page.
https://blog.smilecat.dev/pixi-test/examples/base/index.html

**Comment by bigtimebuddy** [comment]
I need to fix this. Bumping.

**Comment by GerkinDev** [comment]
This is super annoying. Did anyone found a solution for this ?

**Comment by anito** [comment]
I also would love to have a solution on this.
with `import "pixi.js-legacy"` Object.assign is the issue in the legacy build Error: Cannot add property CanvasPrepare, object is not extensible
with `import "pixi.js"` and "pixi-projection" (or any other method trying to manipulate PIXI) Error: Cannot add property ..., object is not extensible

...just annoying
 [Demo](https://sapper.webpremiere.de) (legacy)

**Comment by bigtimebuddy** [comment]
If someone wants to take a shot at this, basically we need to remove Object.assign from prepare and extract namespaces in the legacy bundle. Simplest option is we could remove the namespaces all together, add classes at the root and add deprecations. It’s kinda silly to have these namespaces since I’m sure the class names are unique and add unnecessary level of complexity. The downside is it makes the docs a little more organized, but not by much.

**Comment by bigtimebuddy** [comment]
I added a PR to resolve this
