### ISSUE TITLE
There is a delay during the showing animation before playing

### ISSUE THREAD

**Issue by jiroler** [pixijs/pixi.js#6066]
Hello, i need help.
I use `textureManager.updateTexture()` for big textures with animations after loading all resources. And it's working if animation will be played after little time. But if 3+ minutes have passed before first playing this animation - i see freeze delay again (like without `textureManager.updateTexture()`)

How i can resolve this problem?

**Comment by jiroler** [comment]
Addition: exactly the same behavior when using `app.renderer.plugins.prepare.upload (app.stage)`

**Comment by themoonrat** [comment]
You want to check out https://pixijs.download/dev/docs/PIXI.settings.html#.GC_MODE

There is an automatic garbage collector that removes textures from gpu memory if they are unused for a certain period of time (controlled via GC_MAX_IDLE). Turn this to manual mode and you're sorted :)

**Comment by eXponenta** [comment]
@themoonrat You write faster than me. =)

**Comment by jiroler** [comment]
@themoonrat Thank you very much, it helped me
