### ISSUE TITLE
Mesh's destroy method is not following its documentation

### ISSUE THREAD

**Issue by MRSalomao** [pixijs/pixi.js#6070]
### Expected Behavior
What's described in the function documentation:
![image](https://user-images.githubusercontent.com/4553084/64377724-ab9ffb80-cff0-11e9-888d-1d3bc284d201.png)

### Current Behavior
Mesh's **children** are destroyed.
Mesh's **texture** and **baseTexture** are not destroyed.

### Possible Solution
Manually destroying the texture and its base texture:
```
mesh.texture.baseTexture.destroy();
mesh.texture.destroy();
mesh.destroy();
```

### Steps to Reproduce
1. Create a mesh with a texture;
2. Call `destroy(true)` on it;
3. Verify that the texture has not been destroyed.

### Environment

- **`pixi.js` version**: 4.5.6
- **Browser & Version**: Chrome
- **OS & Version**: MacOS Mojave
- **Running Example**: https://codesandbox.io/s/silly-burnell-n34x5

**Comment by bigtimebuddy** [comment]
This seems to be fixed in the latest version of v4 (4.8.8):
https://www.pixiplayground.com/#/edit/8bFs2kvJ1gaJddAP7MRek
