### ISSUE TITLE
The best way to extending PIXI display objects

### ISSUE THREAD

**Issue by jiroler** [pixijs/pixi.js#6073]
Hi all. I want to extend all PIXI objects (Container, Sprite, Text, Graphics, etc), for example:

```js
PIXI.DisplayObject.prototype.show = function(alpha = false){
    this.visible = true
    alpha && (this.alpha = 1)
    return this
}
```
What best way for extend, using ES6 modules? Very important to VScode shows hints custom methods

**Comment by jiroler** [comment]
I tried to use inheritance:

```js
export class PixiContainer extends PIXI.Container {

    /**
     * @constructor
     * @param {string} name 
     */
    constructor(name = '[noname] container'){
        super()
        this.name = name
    }

    /**
     * Show object
     * @param {boolean} alpha - set alpha to 1
     */
    show(alpha = false){
        this.visible = true
        alpha && (this.alpha = 1)
        return this
    }
}
```

But other pixi objects (PIXI.Sprite etc.) will can't to use custom methods.
Because PIXI.Sprite extends from PIXI.Container... I'm confused(

**Comment by ivanpopelyshev** [comment]
The one with `prototype` is fine and it shows in hints if you provide jsdoc or if you writing it in typescript.

**Comment by jiroler** [comment]
I can use only `prototype`, but it is not working: empty hint
```js
/**
 * @method
 * @name PIXI.DisplayObject#hide
 * @param {boolean} alpha
 */
PIXI.DisplayObject.prototype.hide = function(alpha = false){
    this.visible = false
    alpha && (this.alpha = 0)
    return this
}

const text = new PIXI.Text()
//text.hi... - empty hint :(

```

Screenshot https://prnt.sc/p2kw5e

**Comment by bigtimebuddy** [comment]
VScode uses typings to figure out what is hinted. You need to add a typing for it to show up in autocomplete.
