### ISSUE TITLE
Textures created from SVGs with a linear gradient are rendered without a linear gradient on Microsoft Edge

### ISSUE THREAD

**Issue by mofnire** [pixijs/pixi.js#6074]
### Expected Behavior

Rendered with a linear gradient.

### Current Behavior

Not rendered with a linear gradient.

### Possible Solution

Based on the observation, `HTMLImageElement` is not ready to be copied to a canvas even though `HTMLImageElement#complete` is true on Edge. 

https://www.pixiplayground.com/#/edit/dRF1UoxkJm3WALgyHhgCI

Removing the "Copying to a canvas" part is a possible solution if backwards compatibility does not matter.

https://github.com/pixijs/pixi.js/blob/a1d342c60a5c4279eb1407ce9fb2dad92712a9ac/packages/core/src/textures/resources/SVGResource.js#L134-L164

### Steps to Reproduce

Please open the following on Microsoft Edge and push the refresh button repeatedly.
You will see the black rectangle sometimes.

https://www.pixiplayground.com/#/edit/kTtgztr6986_L2V7S_Igp

### Environment

- **`pixi.js` version**: _5.1.2_
- **Browser & Version**: _Microsoft Edge 42.17134.1.0_
- **OS & Version**: _Windows 10_
- **Running Example**: _https://www.pixiplayground.com/#/edit/kTtgztr6986_L2V7S_Igp_

**Comment by mofnire** [comment]
If backwards compatibility does matter, ...
Any thoughts?

**Comment by ivanpopelyshev** [comment]
Yep, reproduced. No idea how to fix that and what warkaround to use. pixi5-svg also doesnt support gradients yet.

**Comment by mofnire** [comment]
Thank you for your comments.

> No idea how to fix that and what warkaround to use.

If we are allowed to remove the `SVGResouce#scale`, `#_overrideWidth` and `#_overrideWidth`, I think we can fix this... But may not be.

**Comment by eXponenta** [comment]
It can't be allowed.
There are some reason: 
1. you can create correct resource and register it as SVG loader,
2. EdgeHTML render core is depricated and will be replaced on Chomium on next release. 

it browser bug, because it call onload when resource loaded, but it  may not rasterized at the momen.
Same problems existed when you use embedded `styles` - them wasn't calc immediate.

**Comment by mofnire** [comment]
Thank you for taking the time.

> 1. you can create correct resource and register it as SVG loader,

Yes, you are right.
This is the one I am using as a workaround in my project, so far.

I was hoping the properties including `#scale` might not be used widely.
