### ISSUE TITLE
Interaction stopImmediatePropagation

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#6075]
For @laino

Follow-up for #6043

I just found out that Flash had extra method, I don't know if its related to "mouseDown stops click" issue, https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/Event.html#stopImmediatePropagation()

What do you think?

**Comment by laino** [comment]
It is kind of related in that it is closer to how ``.stopPropagation`` worked before the https://github.com/pixijs/pixi.js/pull/6043 change.

The main issue with pixi's events right now is that the same event object gets re-used for events of different names, meaning when you do something in a ``mouseup`` event, like stopping propagation, you're also affecting ``click`` events.

**Comment by laino** [comment]
About the change itself: It won't hurt to have it, especially because it can be added easily without introducing any extra complexity. But it is probably too easy to shoot yourself in the foot with until events are properly isolated from each other.

**Comment by ivanpopelyshev** [comment]
I think its usually re-used if its a broadcast :)

**Comment by themoonrat** [comment]
If there is an event object per event type required, then I think that is a valid route to take. A handful of event objects isn't the issue, it's stopping a new one being created every mouse move that is the goal trying to be achieved.

**Comment by ivanpopelyshev** [comment]
Extra object per frame is fine. Mouse events frequency is almost the same. I recommend to leave pooling only for broadcasts.
