### ISSUE TITLE
Add in support for setting default texture resolution

### ISSUE THREAD

**Issue by mobileben** [pixijs/pixi.js#6080]
Currently if one is running on a browser with a `devicePixelRatio` > 1 and one is not using retina prefix values, then the textures will be displayed larger than expected. To provide more flexibility, it would be helpful to support the ability to allow for a default texture resolution to use.

An example usage, which I am doing, is opting to treat everything as native resolution (eg. set `Application` resolution to 1, not `devicePixelRatio`).

I've actually written about it here, along with a solution I am currently using.

http://www.html5gamedevs.com/topic/43636-texture-loading-and-non-integer-devicepixelratio

**Comment by ivanpopelyshev** [comment]
do you load all your texture through a loader? maybe we can add something in `metadata` object that can be passed to it :) I use it for pixi-spine loading.

https://github.com/pixijs/pixi-spine/blob/master/examples/change_atlas_extension.md

https://github.com/pixijs/pixi-spine/blob/master/src/loaders.ts#L75

We can do pass-through of certain parameters in the texture loader the same way. right now its very stupid: https://github.com/pixijs/pixi.js/blob/dev/packages/loaders/src/TextureLoader.js#L18

**Comment by mobileben** [comment]
Yes, I do all my loading through the loader. 

I couldn't find anything indicating the actual arguments for loader `add`. I also thus far haven't found what calls `Texture` `from` (so I can understand the process better).

I have seen this in the Pixi-spine code you referenced.

```
                loader.add(name, url, imageOptions, (resource: PIXI.LoaderResource) => {
                  if (!resource.error) {
                    callback(resource.texture.baseTexture);
                  } else {
                    callback(null);
                  }
                });
```

Which presumably indicates that `loader.add` can take options.

What is the expected format of this? I've tried

```
loader.add('sprite', 'sprite.png', { resolution: 2 });
loader.add('sprite', 'sprite.png', { metadata: { resolution: 2 }});
```

And a few other variants which include putting it into `imageMetadata`. But have not seen it make any noticeable changes. I also put in some debug `console.log` into pixi.js, and I don't even see my values surface within `BaseTexture`, `Texture`, or `Spritesheet`.

One aspect which is confusing is that the code references at some point, the concept of `imageMetadata` and also then references a `meta.scale`. So it seems like inconsistency (I can't get it to work right now by trying to feed in values). I guess the point of this comment, is it is slightly convoluted how this is being handled.

From my testing, any object I use as the 3rd argument to `loader.add` does not seem to make it into `BaseTexture`, `Texture`, and `Spritesheet`. The loaders (`TextureLoader` and `SpritesheetLoader`) do see the meta.

The other comment I would cite is if the solution stems from adding options to the calling argument, this seems more error prone to the end user. Because one needs to do this for every asset of `BitmapText`, `Spritesheet`, and `Texture` that is loaded.  

The ideal solution should uniformly apply resolution to `BaseTexture`, `BitmapText`, `Spritesheet`, and `Texture`. Right now the most "common" way is through `getResolutionOfUrl`. A weakness of this approach would be if someone passed in an actual image versus a URL, it would not be covered.

One last note here. I did try and override

```
PIXI.settings.RESOLUTION = window.devicePixelRatio;
```

And it did not help either.

I'm still going through the code and experimenting.

**Comment by ivanpopelyshev** [comment]
```
loader.add('sprite', 'sprite.png', { metadata: { resolution: 2 }});
```

then you'll get `resource.metadata` inside the loader middleware, and you can pass it somehow to `Texture.fromLoader` , then maybe we need to modify `fromLoader`method itself to pass it further.

Btw, `premultiplyAlpha` is one more param that i'd like to see there :)

**Comment by mobileben** [comment]
Eventually one can get the values in that way. However, it requires a changed to the loaders. So I suppose perhaps what you are trying to say is just make custom loaders? And if this is the case, why not just wire it up so real meta can pass through.

I don't think I'm necessarily an outlier in wanting to do resolution = 1. Even this individual was sort of querying about the same

https://github.com/pixijs/pixi.js/issues/6029

I'm happy to implement if needed. IMHO, slightly cleaner to require less code entry. Just let me know which way you prefer and I'll put that method in a branch for you to review.

Another thing to factor, which I mentioned was if you don't pass in a url but actual data. Both `getResolutionOfUrl` and whatever we do here won't catch it.

Another thing I notice BTW, unfortunately values of width/height are also not correct once one goes down this route. For example, if I get `width` from the sprite, the value requires resolution scaling.

The `BaseTexture` itself has the proper `realWidth`, `realHeight` but that is for the overall texture.

Typically one would expect the proper unit values returned. For example, if I have a resolution !=1 it implies "points".  If == 1, then it would be equivalent to "pixels".

I'm currently working on some layout code, so I may have some more observations soon

**Comment by ivanpopelyshev** [comment]
I think that issue is related to `baseTexture.setResolution` , need some time to remember what did i write there.

**Comment by mobileben** [comment]
I plan on looking at this further this weekend. I'll probably do a couple of versions and show you.  Now that I have my foundational code working, I have a bit better understanding of my needs as well as the things I misunderstood about what pixijs is doing. I'm still getting used to pixijs so my mental model of how it works changes daily.

**Comment by ivanpopelyshev** [comment]
> I'm still getting used to pixijs so my mental model of how it works changes daily.

I'm familar with code of several renderers with different architecture, I know that feeling :)
