### ISSUE TITLE
Feature request: resizeTo redraw

### ISSUE THREAD

**Issue by fvonellerts** [pixijs/pixi.js#6081]
### Expected Behavior
If a PIXI `Application` has a `resizeTo` element, it would be nice if the element positions inside the application would also update when resizing. Plus some throttling on the resize event would help avoid performance problems.
If this functionality is too complicated to implement (or already present), a best practice example of a responsive application would be very helpful.

### Current Behavior
Only the canvas is resized.

### Environment

- **`pixi.js` version**: 5.1.3

**Comment by bigtimebuddy** [comment]
Maybe a resize event on the Application’s renderer and/or stage Container would be good? So you could respond to resize events from there and pass them to your children display objects.

Also, would welcome a resize throttle PR to fix that performance issue you’re experiencing.

**Comment by fvonellerts** [comment]
Yes maybe or a proxy variable, if that's possible. The same way CSS has `vw` and `vh`.

Ok I will try.

**Comment by bigtimebuddy** [comment]
Adding a resize event is a good start and would be a simple PR if you or someone wants to take a stab at it.

**Comment by eXponenta** [comment]
>>
Yes maybe or a proxy variable, if that's possible. The same way CSS has vw and vh.

What are you mean? Add relative position to Container element?
It is very bad idea implement layout system deirect in core.
There is some Objects can't supported auto layouting, such as Graphics or Rope. 
It mus be implemented in plugin outside  pixi package.

**Comment by fvonellerts** [comment]
@eXponenta Yes, relative positions.
@bigtimebuddy Sure.

**Comment by bigtimebuddy** [comment]
I agree that layout should be a plugin and not implemented directly in core. But the resize event could pass along the width/height, viewport and frame of the renderer. Should be more than enough to calculate anything you need relatively.
