### ISSUE TITLE
Feature request: Fixed sprites length for BitmapText

### ISSUE THREAD

**Issue by EloB** [pixijs/pixi.js#6082]
I just took a look at `BitmapText` and I saw that it adds/removes sprites on demand and it's determined by text length. Wouldn't it be more preferred if that stays the same and just use `visible: true/false` and/or change texture on the unnecessary sprites or at least make it as a property or something like `minSprites/maxSprites` to avoid `add/remove`?
I work on crappy hardware and need as much performance as possible :)

**Comment by eXponenta** [comment]
You can write extended BitmapText and implement yours mechanism of showing/hiding sprites.
Techinicaly visible and add/remove similar, but `add/remove` changes children's array.

BUT when you have 1000 glyphs and remove 999 from it then render loop check 1 from 1000, but when you use `visible` then render iterate 1000 from 1000 and check `visible` state. For static ist more costly.

There are cases:
1. Many static texts - add/remove.
2. Many dynamic texts - visible + texture changing

**Comment by EloB** [comment]
The bigger purpose of BitmapText are high frequency changes so add/remove are less applicable or did I get you wrong?

**Comment by bigtimebuddy** [comment]
I have a hunch that changing from `addChild/removeChild` to toggling visibility isn't going to be the performance win that you're hoping for... probably an imperceptible improvement? Allocating the Sprite and applying the transforms are probably more costly than pushing to the children list. BitmapText already recycles Sprites and your approach would need to loop through each character anyways to set position based on the kerning metrics.

Would welcome some performance measurements to demonstrate the need. But we should start with that to fully understand the problem. If you can prove there's a meaningful difference, then we should talk about the best way to integrate and what API changes would be needed, if any. Otherwise, we will likely not consider this request.

**Comment by EloB** [comment]
I mainly work on smart tvs and the performance is way slower there than normal. My overall experience is that adding and removing sprites have bigger impact on performance. Having sprite pools and not make changes to scenes with sprites is faster.

I might be wrong but that is my gut feeling.

**Comment by eXponenta** [comment]
Benchmarks are required for it.

**Comment by ivanpopelyshev** [comment]
Yep, I agree that its time to switch BitmapText to v5 batched mesh :)

**Comment by EloB** [comment]
> Yep, I agree that its time to switch BitmapText to v5 batched mesh :) I'll help.

Sounds amazing 😍

**Comment by EloB** [comment]
@ivanpopelyshev It would be pretty insane if you somehow could parse real font types (woff, woff2, ttf) and transform them into mesh. So you no longer need to provide those bitmaptext spritesheets. I don't know if this is possible but that would be pretty cool :)

**Comment by bigtimebuddy** [comment]
Sounds a lot like this plugin: https://github.com/PixelsCommander/pixi-sdf-text

**Comment by EloB** [comment]
@bigtimebuddy but that is not using the new stuff you guys implemented for v5?

**Comment by bigtimebuddy** [comment]
I'm pretty sure that plugin is still v4.

**Comment by ivanpopelyshev** [comment]
@EloB 
At the moment im working on Flash fonts implementation. all opentype fonts and their scaling will depend on that :)

**Comment by EloB** [comment]
@ivanpopelyshev I'm just curious... Have you had any time to investigate this feature?

**Comment by EloB** [comment]
@ivanpopelyshev Any progress? It's sad to see this one disappear into eternity xD

**Comment by bigtimebuddy** [comment]
We should’ve closed this. @GoodBoyDigital merged in a new changes to BitmapText that uses Mesh instead of Sprites. Should be much faster!

**Comment by jeffg2k** [comment]
I did see that someone had a working version of msdf for v5, though it looks like it needs a little work. https://github.com/cjsjy123/pixi-msdf-text-v5

Wonder how this would compare with regard to speed and clean zoom.
