### ISSUE TITLE
generateCanvasTexture generates textures twice the size

### ISSUE THREAD

**Issue by naranjamecanica** [pixijs/pixi.js#6083]
I've converted a project to PIXI v5 and since we generate a lot textures from graphics we use the canvas for a visual smoother result. 

For this reason I use the legacy build which uses the @pixi/canvas-renderer etc, which works really well, but there is one strange behaviour: the generated textures are twice the size on a retina display.

### Expected Behavior
Generate texture in size of current renderer.

### Current Behavior
Generates a texture twice the size

### Possible Solution
Set up canvas renderer with right settings? 

### Steps to Reproduce
See: https://www.pixiplayground.com/#/edit/XWQP2rDIDQgi7SO_tawZA

Or should i allways pass resolution = 1 to the `generateCanvasTexture()`

- **`pixi.js` version**: 5.1.2

**Comment by ivanpopelyshev** [comment]
Yep, confirmed on dev branch: https://www.pixiplayground.com/#/edit/mzTlmuzRlCsZA6nAqjygj

**Comment by bigtimebuddy** [comment]
Anyone want to check Ivan’s fix idea?
