### ISSUE TITLE
Sprite with RenderTexture set to mask another object renders nothing.

### ISSUE THREAD

**Issue by supermoos** [pixijs/pixi.js#6084]
Check, line 48: https://www.pixiplayground.com/#/edit/Q6pSV9pf0uBlZHrj9pCyN
### Expected Behavior
Should render bunny masked to square at 50% opacity:
### Current Behavior
Completely removes the bunny, rendering nothing, like the mask just results in nothing showing up.
### Environment

- **Browser & Version**: Chrome 76_
- **OS & Version**: macOS Mojave

**Comment by eXponenta** [comment]
Works as must be.
You try use mask source as render destination (same as draw self to self ).
You must render do different RT and flips between them.
