### ISSUE TITLE
how to save backgroundColor when I use app.renderer.plugins.extract.base64

### ISSUE THREAD

**Issue by hufei1993** [pixijs/pixi.js#6085]
how to save backgroundColor when I use app.renderer.plugins.extract.base64

**Comment by ivanpopelyshev** [comment]
need more information

**Comment by hufei1993** [comment]
when I use app.renderer.backgroundColor = 0x061639,
next  I use app.renderer.plugins.extract.base64,
but the result is without backgroundColor

**Comment by eXponenta** [comment]
Create example please!

**Comment by ivanpopelyshev** [comment]
It should work. Probably you are doing something strange that triggers a bug.
