### ISSUE TITLE
Question about PIXI v5 on Windows 

### ISSUE THREAD

**Issue by smparsons** [pixijs/pixi.js#6086]
I apologize if this was asked previously or if I missed something in the documentation. I just had a quick question. I noticed that when I visit the pixi.js examples page in Firefox or Edge using Windows 10, pixi will fallback to using the canvas renderer. However I know WebGL is supported because when I visit https://get.webgl.org/, it tells me WebGL is supported. If I visit the examples page in Chrome using Windows 10, it renders using WebGL.

If I try visiting the examples page in Firefox or Chrome using Mac, it will also render using WebGL.

I just wanted to confirm, is it a known issue that WebGL rendering in pixi will not work in Firefox or Edge using Windows 10? If so, is it because of a lack of stencil support? Am I just completely misunderstanding something? It may or may not also be important to mention that I'm doing this testing with BrowserStack. 

Thanks!

**Comment by ivanpopelyshev** [comment]
Probably stencil. We'll make it optional like in pixijs v4 in next versions.

**Comment by bigtimebuddy** [comment]
Here's the function that does the webgl detection (stencil required):
https://github.com/pixijs/pixi.js/blob/dev/packages/utils/src/browser/isWebGLSupported.js

**Comment by immanuelx2** [comment]
Console shows WebGL for Firefox on Windows 10 for me:

![image](https://user-images.githubusercontent.com/53500318/64733830-76455300-d4b3-11e9-8ff7-dcfaa018e53e.png)

**Comment by smparsons** [comment]
@immanuelx2 Got it. Perhaps it has something to do with the fact that all of the testing I've done has been on VMs (BrowserStack browsers and my own locally installed VM). But even still, why would it work on Chrome but not on Firefox or Edge?

**Comment by themoonrat** [comment]
Browsers have their own blacklists for devices or driver versions; sometimes a complete blacklist, sometimes webgl features blacklisted.

**Comment by smparsons** [comment]
Ah, that makes sense, that probably explains why I was running into those issues. I think my question is answered so I'm closing this, if I have any further questions I'll post a new issue. Thanks guys.
