### ISSUE TITLE
PIXI.SCALE_MODES.NEAREST causing pixel glitches

### ISSUE THREAD

**Issue by immanuelx2** [pixijs/pixi.js#6087]
### Expected Behavior
* No visual glitches
### Current Behavior
* On some frames, glitches appear when pixel art moves around on the screen
* When motion stops, glitches remain in frame on the screen

![image](https://user-images.githubusercontent.com/53500318/64735156-fec4f300-d4b5-11e9-8428-a46530c6ca28.png)

### Steps to Reproduce
1. Set `PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST`
2. Have some things moving, e.g. camera following a player:
```javascript
camera.pivot.set(player.position.x, player.position.y);
camera.position.set(app.renderer.width / 2, app.renderer.height / 2);
```
3. Move your player
### More Info
* Tested on Chrome & Firefox -- does not seem to make a difference.
* Tested with `pixi.js-legacy` setting `forceCanvas = true` -- does not seem to make a difference.
* The glitches *do not* seem to appear on my Surface Pro 2 which has a different GPU (integrated) versus my desktop (GeForce GTX 660Ti).
* When viewing some areas of the map (in this case, towards the top or bottom of the level where half the canvas is black) **the visual glitches disappear** -- this part has me the most confused...

### Environment
- **Live demo**: https://www.pixiplayground.com/#/edit/Od8NGNEsFru4NjMDkfURQ
- **`pixi.js` version**: 5.1.3
- **Browser & Version**: Chrome 76 & Firefox 69
- **OS & Version**: Windows 10

**Comment by eXponenta** [comment]
You must create simple public example with bug for testing.

**Comment by immanuelx2** [comment]
> You must create simple public example with bug for testing.

Added: https://pixiplayground.com/#/edit/H1vw02mHEbFKG4ctrX3CG
