### ISSUE TITLE
Pixi.js v5.1.3 Legacy internal deprecation warnings.

### ISSUE THREAD

**Issue by edreal** [pixijs/pixi.js#6093]
In canvas renderer when I call function below:
`canvasRenderer.render(sprites, renderTexture, true)`
which in turn calls `BaseTexture.prototype.getDrawableSource` somewhere which logs deprecation message:
> PIXI.BaseTexture.source property has been moved, use PIXI.BaseTexture.resource.source

**Comment by ivanpopelyshev** [comment]
Here: https://www.pixiplayground.com/#/edit/NRX~iJ43n7OQbcIQXU2zM

The only way to trigger that warning is to use sprite with that renderTexture before you rendered something in it.

This code: https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-renderer/src/BaseTexture.js#L14

is called before this one: https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-renderer/src/CanvasRenderer.js#L157

I think we need to initialize that canvasRenderTarget in that case or just make it not valid and dont call drawImage at all.

**Comment by edreal** [comment]
How to do the first one?
I am trying to render multiple sprites into one renderTexture to create sprites of later.

**Comment by ivanpopelyshev** [comment]
Does your code work if you use webgl? 

The thing is that you are trying to draw renderTexture before its ready. Probably renderTexture over itself - which can never work.

**Comment by ivanpopelyshev** [comment]
You can just override getDrawableSource from outside , `PIXI.BaseTexture.prototype.getDrawableSource = function() {...}` 

Try produce a code that wont trigger that problem ;)

**Comment by edreal** [comment]
The bug has disappeared overnight for some magical reason.
Thanks for the help however
