### ISSUE TITLE
Add method like unregisterPlugin for instance of Loader

### ISSUE THREAD

**Issue by developer-av** [pixijs/pixi.js#6101]
Could you add method like unregisterPlugin for instance of Loader, please.
Thanks for the work!

**Comment by bigtimebuddy** [comment]
Could you explain your use-case a little more? Curious to understand what you’re trying to achieve or which loader plugins are getting in your way.

**Comment by developer-av** [comment]
@bigtimebuddy, I want make custom spritesheet loader for my project
I had to use https://pixijs.io/customize
I would like something like this:
```
let SpritesheetLoader  = require('@pixi/spritesheet')
const loader = new Loader();
loader.unregisterPlugin(SpritesheetLoader);
loader.registerPlugin(MyCustomSpritesheetLoader);
```

**Comment by englercj** [comment]
Hey @developer-av, something challenging with removing middleware from the loader is that the middleware function may not be stored anywhere.

Consider this factory function for a middleware:

```js
function someMiddlewareFactory(options)
{
    return theMiddleware(resource, next)
    {
        // do stuff on resource using `options`.
    }
}
```

If I add it to the loader like this:

```js
loader.use(myMiddlewareFactory(options));
```

How can I then remove it? If I call the factory again I'll get a new function object, so I can't look it up from that.

I'm open to ideas on how this should work instead as I am writing v4 now, so please share your ideas. Though it might make more sense to share them on the [resource-loader](https://github.com/englercj/resource-loader) page.

**Comment by bigtimebuddy** [comment]
@developer-av 

If you are using https://pixijs.io/customize then just remove the line from the auto-generated code.

```js
Loader.registerPlugin(SpritesheetLoader);
```

**Comment by developer-av** [comment]
@bigtimebuddy, I am forced to use custom only because of the inability to disable the plugin

**Comment by developer-av** [comment]
recursive load for multipack and i want add polygon to sprite for hit area at the once

**Comment by developer-av** [comment]
@englercj like a crutch

```
/**
 * @param disablePlugins {number|Function}
 */
constructor(baseUrl = '', concurrency = 10, disablePlugins) {
    ...
    for (let i = 0; i < Loader._plugins.length; ++i){
        if(disablePlugins.includes.(i) == false && disablePlugins.includes(Loader._plugins[i]) == false)
    }
    ...
}

Loader.registerPlugin = function registerPlugin(plugin, fn) {
    let id = Loader._plugins.push(plugin) - 1;

    if (plugin.add) {
        plugin.add();
    }

    if(fn){
        fn(id)
    }

    return Loader;
};
```

**Comment by developer-av** [comment]
@bigtimebuddy, temporary option in my project

`SpritesheetLoader.js`
```
if (resource.data.meta.related_multi_packs) {
    for (let i = 0; i < resource.data.meta.related_multi_packs.length; i++) {
        let resPath = url.resolve(resource.url.replace(this.baseUrl, ''), resource.data.meta.related_multi_packs[i]);
        if (this.resources[resPath] === undefined) {
            this.add(resPath, {parentResource: resource});
        }
    }
}
```

**Comment by ivanpopelyshev** [comment]
Yes, overriding spritesheet middleware is a problem I met with many times.
