### ISSUE TITLE
Blank Screen (Nothing displays)

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [pixijs/pixi.js#6103]
I've already made a couple games with Pixi so I don't understand why this isn't working.

```
<body>
<script type="text/javascript" src="pixi.js"></script>
<script>
app = new PIXI.Application({ width: 1366, height: 768 });
texture = new PIXI.Texture.from(`images/tiles.png`);
sprite = new PIXI.Sprite.from(texture);
app.stage.addChild(sprite);
console.log(texture);
</script>
</body>
```

There are no errors in console.  

It's not a CORS problem because I can log the correct width of the texture with `console.log(texture.width) //prints 480` but `sprite.width` is `1` for some reason.

NOTHING shows on the screen.

It's not a problem with the `pixi.js` file either because I just downloaded it yesterday and it works with my previous game.  

Why do I have just a white screen?

**Comment by themoonrat** [comment]
Could it be doing 'new' texture and 'new' sprite? The 'from' commands return new objects themselves, so don't 'new' yourself.

https://www.pixiplayground.com/#/edit is a good place to start with is something is wrong with your setup or your code!

**Comment by MelerEcckmanLawler** [comment]
Sadly that is not the problem. I tried with and without `new` on both lines, it did not help.  Besides, I used `new` on my rock-paper-scissors game yesterday and it works fine:

[RPS](https://github.com/MelerEcckmanLawler/RPS/blob/master/index.html)

**Comment by MelerEcckmanLawler** [comment]
I was missing this line:

`document.body.appendChild(app.view);`
