### ISSUE TITLE
Graphics drawing at larger sizes has artifacts

### ISSUE THREAD

**Issue by delaneyj** [pixijs/pixi.js#6107]
Made a test example of the behavior

### Expected Behavior
Randomized grid background
![image](https://user-images.githubusercontent.com/438252/65167811-25c07f00-d9f8-11e9-8ea3-365c2ecdd869.png)

### Current Behavior
When window resized and the bg gets recalculated render errors occur.  ![image](https://user-images.githubusercontent.com/438252/65167858-383ab880-d9f8-11e9-91d1-b5cdd671c220.png)

### Steps to Reproduce
Resize playground example window

### Environment
Ubuntu 18.04
Chrome Version 77.0.3865.75 

- **`pixi.js` version**: _e.g. 5.1.3_
- **Browser & Version**: _e.g. Chrome 77_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _https://www.pixiplayground.com/#/edit/35JFOwxjXFWBkemSsbcL2_

**Comment by bigtimebuddy** [comment]
This is a known issue duplicate. See #5973, #6047 and #6104. Also see: 
https://github.com/pixijs/pixi.js/wiki/v5-Hacks#pixigraphics

There are several workarounds if you investigate those other issues. Also, this is not the most performant way to draw your background. Would suggest using individual Graphics objects with sharing geometry or using Sprites + tint/opacity. All would produce similar effects and would render faster.

**Comment by bigtimebuddy** [comment]
Fixed in #6417
