### ISSUE TITLE
childrenInteractive strange behavior or bug ?!

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#6110]
### Expected Behavior
if `REDSQUARE.interactive = true` and `REDSQUARE.childrenInteractive = false`.
We should able to hover `REDSQUARE`, but not `BLUESQUARE` because they are childrens..

### Current Behavior
if `REDSQUARE.interactive = true` and `REDSQUARE.childrenInteractive = false`.
`BLUESQUARE` interaction not emit, but also the parent `REDSQUARE`!?
The `REDSQUARE` should emit.

### Steps to Reproduce
unComment line `29`
![image](https://user-images.githubusercontent.com/24865815/65348266-b345cf80-dbae-11e9-84a4-7af0f5384b87.png)

### PUBLIC TEST
https://www.pixiplayground.com/#/edit/U8XAqMp38kmY32oUpYOWy

### CONTEXT USAGE
If we have parrent button container with sub Button container
Easily allow or disable sub button container.
But if i disable childrendInteractive on parent button, it also disable parent interactive.
![childrenInteractive](https://user-images.githubusercontent.com/24865815/65349312-1afd1a00-dbb1-11e9-9d0c-aeda37a407c3.gif)

**Comment by ivanpopelyshev** [comment]
interactiveChildren=false turn off interactive for children completely. that means pixi doesnt do that kindof computations: "ok, mouse over blue square but its switched off, so i shouldnt do anythying". Pixi will ignore the blue square, and see only red one, and mouse is above the red one!

**Comment by djmisterjon** [comment]
thanks for your explain,i think it make sense for me i will test :)

**Comment by djmisterjon** [comment]
We can close this, so for people want do similar stuff , i choose suggestion by @themoonrat .
Add `this.hitArea ` to all my initialise stuff also give more optimisation.
If you use pixi-display, just beware to also apply on children, because hitArea will not allow children interactive with pixi-display.

here solution i choose.
https://www.pixiplayground.com/#/edit/~RjosY9BJvpQ9yjFhrZjt

So i dont think is a pixi bug, but a bad interpretation of `childrenInteractive ` on container from my side.
Thanks all for the help.
