### ISSUE TITLE
Setting cacheAsBitmap=true on a Container translates positions on its children if they have a mask

### ISSUE THREAD

**Issue by apinder** [pixijs/pixi.js#6112]
Setting `cacheAsBitmap=true` on a Container that contains a child that's a Graphic masked with a Sprite offsets the Graphic to the bottom right.

(Container->Graphic->Sprite mask)

### Expected Behavior
cacheAsBitmap should maintain the Graphic's position. No visual difference should occur after setting `cacheAsBitmap=true`

### Current Behavior
Setting `cacheAsBitmap=true` on the container translates the Graphic to the bottom right.

### Steps to Reproduce
See: https://www.pixiplayground.com/#/edit/cuRi6fT3x7QHWL7cNxRNM

This example:
- Creates a circle Graphic
- Sets the Pixi rabbit Sprite as the mask for this graphic
- Puts both in a Container
- Waits 5 seconds and sets cacheAsBitmap to true on the Container
 
On Chrome this will show the Pixi rabbit masked in the top left of the container. The example waits 5 seconds and then sets `cacheAsBitmap=true`. This shifts the Graphic to the lower right eliding parts of the rabbit. Poor rabbit.

### Environment

This was working as expected in versions <5 but seems to be consistently reproducible for versions >= 5.0.4.

- **`pixi.js` version**: 5.1.4
- **Browser & Version**:  Chrome 67
- **OS & Version**: Ubuntu 18.04
- **Running Example**: https://www.pixiplayground.com/#/edit/cuRi6fT3x7QHWL7cNxRNM

**Comment by ivanpopelyshev** [comment]
Good catch! Reproduced it on dev.

**Comment by ivanpopelyshev** [comment]
Actually that's a bigger problem: any filter that calculates sprite position doesn't account for projection transform stuff.
