### ISSUE TITLE
Typescript Buffer typings

### ISSUE THREAD

**Issue by lxender** [pixijs/pixi.js#6117]
Hey,

I've noticed that at least the methods `addAttribute` or `addIndex` expect PIXI.Buffer or an array without giving the option to provide an array to the function. The option is just in the description (and probably works fine in JavaScript).

It's possible that other functions that expect buffers or arrays similarly lack the array type.

I cannot link to the troublesome file in this repo because I couldn't find it. VS Code threw me to the pixi.d.ts file which I couldn't find here.

To see the problem yourself:
1. create a new project with pixi installed
2. create a typescript file
3. copy and paste the [uniforms example code](https://pixijs.io/examples/#/mesh-and-shaders/uniforms.js)
4. VS Code will start complaining

~~Until it's fixed, the workaround is to wrap the arrays in PIXI.Buffer.from calls.~~ **[SEE COMMENT](https://github.com/pixijs/pixi.js/issues/6117#issuecomment-534208390)**

**Comment by lxender** [comment]
Actually, PIXI.Buffer.from fixes the IDE's problems but the example doesn't work anymore with those calls in place.

**Comment by bigtimebuddy** [comment]
Need more information. Please be more specific about what you mean bay "will start complaining", what is the TypeScript error.

Ideally, if you can reproduce this in a repo for us to investigate, that would be great.

**Comment by lxender** [comment]
It complains about number[] not having the methods from PIXI.Buffer because it's a type mismatch.

## But if it's still too little information:

This code will throw an compiler error in a TS file because number[] is not PIXI.Buffer:
```javascript
const geometry = new PIXI.Geometry()
    .addAttribute('aVertexPosition', // the attribute name
        [-100, -100, // x, y
            100, -100, // x, y
            100, 100,
            -100, 100], // x, y
        2) // the size of the attribute
    .addAttribute('aUvs', // the attribute name
        [0, 0, // u, v
            1, 0, // u, v
            1, 1,
            0, 1], // u, v
        2) // the size of the attribute
    .addIndex([0, 1, 2, 0, 2, 3]);
```
However, it works fine in a JS file, because it doesn't care about types.

To fix the compiler error, you need to provide a PIXI.Buffer. Since PIXI.Buffer let's you create a buffer from an array with the .from method, wrapping the arrays in these calls, solves the compiler error. The code would look like:
```javascript
const geometry = new PIXI.Geometry()
    .addAttribute('aVertexPosition', // the attribute name
        PIXI.Buffer.from([-100, -100, // x, y
            100, -100, // x, y
            100, 100,
            -100, 100]), // x, y
        2) // the size of the attribute
    .addAttribute('aUvs', // the attribute name
         PIXI.Buffer.from([0, 0, // u, v
            1, 0, // u, v
            1, 1,
            0, 1]), // u, v
        2) // the size of the attribute
    .addIndex(PIXI.Buffer.from([0, 1, 2, 0, 2, 3]));
```
As said, this satisfies the compiler but doesn't work (without throwing any error).

So, the most obvious fix would be to add number[] to the typings of PIXI.Geometry.addAttribute and .addIndex. However, those methods still couldn't accept any PIXI.Buffer.from return values.

The code is taken from the linked example.

**Comment by ivanpopelyshev** [comment]
Good catch!

**Comment by bigtimebuddy** [comment]
Got it, thanks for pointing it out @lxender
