### ISSUE TITLE
This has been address in v3. Should work like a champ as the batch's now get split if they are too large.

### ISSUE THREAD

**Issue by aaronhudon-ts** [pixijs/pixi.js#6119]
This has been address in v3. Should work like a champ as the batch's now get split if they are too large.

_Originally posted by @GoodBoyDigital in https://github.com/pixijs/pixi.js/issues/1076#issuecomment-74873889_

**Comment by aaronhudon-ts** [comment]
I am experimenting with drawing approximately 18,000 circles per second, and have found that only the first 30% are rendered.

Switching to `drawRect` seems to do a bit better, but not all 18,000 are drawn.

I'm looking for guidance on how to render all of these items without loss.

E.g.

        this.points.clear();

        this.points.lineStyle(0);
        this.points.beginFill(0x9966FF);
        for (let i = 0; i < points.length; i++) {
            //this.points.drawCircle(points[i].z, points[i].y * -1, 1); //only about 30% are rendered
            this.points.drawRect(points[i].z, points[i].y * -1, 1, 1)// better - about 80% are rendered
        }
        this.points.endFill();

**Comment by ivanpopelyshev** [comment]
Same as #6047 . Graphics in v5 has one 16-bit index buffer.

**Comment by aaronhudon-ts** [comment]
Workaround of using a `Graphics` object for around 1000 calls to `drawRect` works perfectly.
