### ISSUE TITLE
Is there a skew property coming?

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#612]
In addition to the already impressive repertoire of changeable DisplayObject properties, are you guys by any chance going to add skewing? It would also be cool if the skew transformed all the children along like skewing one big flat image.

Thanks.

**Comment by lucas-jones** [comment]
+1 Nearly been a year ):

**Comment by englercj** [comment]
We don't have any plans to add this any time soon.

**Comment by NikkiKoole** [comment]
in this thread (http://www.html5gamedevs.com/topic/7546-pixi-dragonbones/page-3
) @wayfinder and others add that functionality, people are adding it because of DragonBones 2d skeleton animation tool, http://dragonbones.effecthub.com/ personally I would like it t o be part of pixi aswell, it seems like a small change, and a tiny little extra api, with alot of new functionalities that are possible because of it.

**Comment by englercj** [comment]
I'll see if I can get this working in the v3 branch since more people than I thought want it.

**Comment by englercj** [comment]
Implemented in v3, just need to optimize it a bit.

**Comment by englercj** [comment]
This was reverted temporarily, we are going to do it a different way.

**Comment by lunte** [comment]
hi. 
i switched from kinetic to pixi (it is great) and i really needed skewing back. so i searched for the mechanism that skews shapes in kinetic and included it into updateTransform. i don't know how this works together with sprites and cached objects etc. but for me it works perfekt.
jsfiddle.net/6phukr6r/9/

**Comment by englercj** [comment]
I need to make this into a plugin when I find the time. Sorry for the delay!

**Comment by englercj** [comment]
Reopening this as a reminder that the plugin needs to get made.

**Comment by jordwalke** [comment]
I was also surprised to see lack of matrix perspective transforms, so I'm excited for the PIXIFlip plugin. You mentioned it wasn't stable yet. What should I look out for (and test/report bugs for)?

https://github.com/GoodBoyDigital/pixi.js/commits/dev-flip

**Comment by jackwlee01** [comment]
I'm also waiting on skew. I am building a Flump runtime and require skew to make it fully compatible.

**Comment by wayfu** [comment]
Does it make sense to make the skew values into a Point object, like in your code? It's logically something very different (two angles)

**Comment by mathieuanthoine** [comment]
@jackwlee01 +1 for a Flump plugin for pixi. Don't hesitate to ask if you want some help.

**Comment by jackwlee01** [comment]
@mathieuanthoine Thanks, it would be great to have a helping hand!

I'm only working on this in my spare time at the moment, so it will probably be a while before it is ready for contributors. I'll keep you posted though :)

**Comment by mathieuanthoine** [comment]
@jackwlee01 Maybe we can continue to discuss the project by mail (you'll find mine on my Github profile)

**Comment by cloakedninjas** [comment]
:+1:

**Comment by GoodBoyDigital** [comment]
Skew has landed in dev branch 
Better late than never :)

**Comment by lucas-jones** [comment]
![Alt Text](http://media.giphy.com/media/nLfEVuqqk9puw/giphy.gif)

**Comment by shanemielke** [comment]
Awesome. Was just hit up about a project that would require skew. So this is good news :)

**Comment by sgal** [comment]
@GoodBoyDigital Do you have any info about when it will be released? Thanks in advance.

**Comment by englercj** [comment]
Soon™

**Comment by PRASS95** [comment]
Hi,
Meanwhile the release of the next PIXI, I've made this little workaround.
https://github.com/PRASS95/skewable-graphics
