### ISSUE TITLE
this.currentRenderer is undefined

### ISSUE THREAD

**Issue by Fxlr8** [pixijs/pixi.js#6120]
### Expected Behavior
The app renders as usual
### Current Behavior
The app crashes. The error happens in BatchRenderer object. `app.renderer.batch.currentRenderer is undefined` My app worked fine with `v5.0.4` but it started crashing after the update. Same for `5.1.0` and newer.

When I create an empty app and add it to the page there is no error. The error happens when I try to add any graphics to the scene.
### Steps to Reproduce
I can't reproduce this problem with code sandbox. The exact same code crashes in my environment.
https://codesandbox.io/s/frosty-almeida-2q66x
### Environment

- **`pixi.js` version**: 5.1.5
- **Browser & Version**: firefox 70.0b7, chrome 77.0.3865.90
- **OS & Version**: _e.g. MacOS Mojave

**Comment by Fxlr8** [comment]
This was a weird magic issue on my side that fixed by itself

**Comment by prichey** [comment]
FWIW I'm seeing this with 5.2.1 when using a custom build. No idea what's going on. 🤔

**Comment by epicureanian** [comment]
I re-download the depencies of pixi.js and it works !!! By using 'npm install' in the directroy
For I found the version of @pixi/core was not corresponed, which was 6.5.9 and I'm using 5.3.10
