### ISSUE TITLE
Question about RenderTexture

### ISSUE THREAD

**Issue by Liiioooo** [pixijs/pixi.js#6125]
I have a question,

I am generating a lot of Graphics, and have to regenerate them pretty often because of scaling.
So my question is, if it is possible to render the Graphics object to a Texture with RenderTexture, when needed and then cache the texture and reuse it to generate new Sprites.
But when I try to do this now, my screen stays blank, I think it has something to do with the hint in the docs http://pixijs.download/release/docs/PIXI.RenderTexture.html

```typescript
private static getGridTexture(scale: number): PIXI.Texture {
	if (this._gridTextures.has(scale)) {
		return this._gridTextures.get(scale);
	}
	const graphics = new PIXI.Graphics();
	graphics.beginFill(ThemingService.staticInstance.getEditorColor('grid'));
        graphics.drawRect(i * environment.gridPixelWidth, j * environment.gridPixelWidth, 1 / scale, 1 / scale);

	const texture = PIXI.RenderTexture.create({
		width: environment.gridPixelWidth * environment.chunkSize,
		height: environment.gridPixelWidth * environment.chunkSize
	});
	this._renderer.render(graphics, texture);
	this._gridTextures.set(scale, texture);
	return texture;
}
```

and then I use the Texture to create Sprites, but when I add them to the scene, nothing is displayed.

Thanks in advance

**Comment by ivanpopelyshev** [comment]
you dont need `i` and `j` there. `render()` draws only whatever is in (0,0)-(w,h)

**Comment by Liiioooo** [comment]
Sorry, I forgot to remove the varibales, when simplifying the code, here is the entire code snippet I use in my App.
And when I add the Graphics directly to the screen, I see the desired object rendered on screen.

```typescript
export const environment = {
	chunkSize: 20,
	gridPixelWidth: 20,
};

private static getGridTexture(scale: number): PIXI.Texture {
	if (this._gridTextures.has(scale)) {
		return this._gridTextures.get(scale);
	}
	const graphics = new PIXI.Graphics();
	graphics.beginFill(ThemingService.staticInstance.getEditorColor('grid'));
        for (let i = 0; i < environment.chunkSize; i++) {
		for (let j = 0; j < environment.chunkSize; j++) {
			graphics.drawRect(i * environment.gridPixelWidth, j * environment.gridPixelWidth, 1 / scale, 1 / scale);
		}
	}

	const texture = PIXI.RenderTexture.create({
		width: environment.gridPixelWidth * environment.chunkSize,
		height: environment.gridPixelWidth * environment.chunkSize
	});
	this._renderer.render(graphics, texture);
	this._gridTextures.set(scale, texture);
	return texture;
}
```

**Comment by Liiioooo** [comment]
I fixed the issue, the problem was that I loaded a font with PIXI.Loader in a Promise, when i removed the promise it works. I dont know why this works now, but OK.
