### ISSUE TITLE
Typings file for triple-slash directive

### ISSUE THREAD

**Issue by aaronhudon-ts** [pixijs/pixi.js#6129]
I'm looking for some guidance on how to use PixiJS without a module system.  I was hoping to use the [Triple-Slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) but this project doesn't provide a pixi.d.ts file.

**Comment by bigtimebuddy** [comment]
The typings file is provided only in the published file. You can grab it from a NPM CDN, like here:
https://cdn.jsdelivr.net/npm/pixi.js@5.1.5/pixi.js.d.ts

**Comment by aaronhudon-ts** [comment]
@bigtimebuddy perfect!  Thank you.
