### ISSUE TITLE
does blendMode support XOR?

### ISSUE THREAD

**Issue by huangjianke** [pixijs/pixi.js#6131]
like this
https://photonstorm.github.io/phaser3-docs/Phaser.BlendModes.html#.XOR__anchor

https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

thank you

**Comment by huangjianke** [comment]
![image](https://user-images.githubusercontent.com/8692455/65826882-9734e300-e2be-11e9-85b0-ef062a722042.png)

**Comment by eXponenta** [comment]
Phaser 3 support XOR only in canvas mode.
![image](https://user-images.githubusercontent.com/12572222/65828346-8c6c5500-e2a2-11e9-9597-20eb0ec05d55.png)

WebGL in Pixi v5 is a priority.
You can't do it in WebGL mode with blendFunc, but there are https://github.com/pixijs/pixi-picture , it  can be used for implementing custom blend modes, but you must port it on v5;)

**Comment by huangjianke** [comment]
@eXponenta thanks
Are there any plans to add support XOR later

**Comment by hajimehoshi** [comment]
> @hajimehoshi
> Phaser 3 support XOR only in canvas mode.

You have the wrong number :-)

**Comment by ivanpopelyshev** [comment]
> Are there any plans to add support XOR later

Nobody asked that before :)

**Comment by huangjianke** [comment]
> > Are there any plans to add support XOR later
> 
> Nobody asked that before :) Do you have equation for it that takes into account alpha (premultiplied or not)?

@ivanpopelyshev 
not yet = =
hope you can add support for that, thanks

**Comment by eXponenta** [comment]
@huangjianke without equation it is will be not soon

**Comment by ivanpopelyshev** [comment]
I think its something like "if (alpha1>alpha2) color1 else color2" in non-premultiplied case.

**Comment by ivanpopelyshev** [comment]
You are right, we are missing one blendMode that can be done according to https://de.wikipedia.org/wiki/Porter-Duff_Composition. I'm making new demo for XOR :)

**Comment by huangjianke** [comment]
@ivanpopelyshev 
Wow, Great job
it will help me a lot
thanks 😜

**Comment by ivanpopelyshev** [comment]
Done, build is here: https://pixijs.download/dev-blendmode-xor/pixi-legacy.js (and pixi.js is there too)

Demo of all composition modes, including missed XOR: https://www.pixiplayground.com/#/edit/bWeh8BX~4XaD5jslgtb_3

please fork it if you change , we dont have "lock" feature yet :(

**Comment by ivanpopelyshev** [comment]
its merged. build is here : pixijs.download/dev/pixi.js

**Comment by huangjianke** [comment]
@ivanpopelyshev 
hey, When will this fix be released🤣🤣🤣

**Comment by DavidGOrtega** [comment]
@ivanpopelyshev 
I did this on my own long time ago

```js
array[_const.BLEND_MODES.SOURCE_OUT]           = [gl.ONE_MINUS_DST_ALPHA, gl.ZERO];        array[_const.BLEND_MODES.SOURCE_IN]               = [gl.DST_ALPHA, gl.ZERO];        
array[_const.BLEND_MODES.DESTINATION_OUT] = [gl.ZERO, gl.ONE];     
array[_const.BLEND_MODES.DESTINATION_IN]      = [gl.ZERO, gl.SRC_ALPHA];
``` 
however in my experience this actually generates shadow effects that if you save the curren image and use it as a texture if you do it several times it gets darker and darker. This means that the blend is not clean maybe because of the premultiplied.

How would be the non premultiplied formulae for those blends?
