### ISSUE TITLE
BatchSystem.setObjectRenderer called with undefined objectRenderer

### ISSUE THREAD

**Issue by cternoey** [pixijs/pixi.js#6134]
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by cternoey** [comment]
I tried to compile one of the boiler plates listed here:

**Comment by cternoey** [comment]
https://github.com/pixijs/pixi.js/wiki/v5-Boilerplate
The project I used was:
"PixiJS + TypeScript + Webpack + pixi-sound"
( https://github.com/bigtimebuddy/pixi-sound-webpack-example/tree/typescript )
But it does not work.
It crashes with this error: 

Do you know how I can fix this?

core.es.js:5284 Uncaught TypeError: Cannot read property 'start' of undefined
at BatchSystem.setObjectRenderer (core.es.js:5284)
at Graphics._render (graphics.es.js:3101)
at Graphics.render (display.es.js:1615)
at Container.render (display.es.js:1620)
at Renderer.render (core.es.js:10812)
at Application.render (app.es.js:73)
at Module../src/index.ts (index.ts:36)
at webpack_require (bootstrap:19)
at Object.0 (index.ts:52)
at webpack_require (bootstrap:19)

BatchSystem.prototype.setObjectRenderer = function setObjectRenderer (objectRenderer)
{
    if (this.currentRenderer === objectRenderer)
    {
        return;
    }
    this.currentRenderer.stop();
    this.currentRenderer = objectRenderer;
    this.currentRenderer.start();
};

**Comment by cternoey** [comment]
(sorry for not following the recommended format better. i kept having my draft notes submitted automatically by just hitting the return-key.)

**Comment by cternoey** [comment]
Thanks for these tips. If these steps do not work, I will try switching away from webpack.

**Comment by hellmark1990** [comment]
Seems like can be related to:
https://github.com/pixijs/pixi.js/issues/6171#issuecomment-619507968
