### ISSUE TITLE
PIXI.mesh.NineSlicePlane FPS drop

### ISSUE THREAD

**Issue by lisovskyR** [pixijs/pixi.js#6135]
Adding multiple slices object with different texture to one container cause FPS drop.

```
const container = new PIXI.Container();
for (let i = 1; i < 50; i++) {
  const item = new PIXI.mesh.NineSlicePlane(texture1, 0, 0, 0, 0);
  // item2 with same texture
  const item2 = new PIXI.mesh.NineSlicePlane(texture1, 0, 0, 0, 0);
  container.addChild(item, item2);
}
```

This won't cause any problems

```
const container = new PIXI.Container();
for (let i = 1; i < 50; i++) {
  const item = new PIXI.mesh.NineSlicePlane(texture1, 0, 0, 0, 0);
  // item2 with same texture
  const item2 = new PIXI.mesh.NineSlicePlane(texture2, 0, 0, 0, 0);
  container.addChild(item, item2);
}
```

This cause FPS drop to very low values.
UPD: item.cacheAsBitmap = true; solves the problem, but it's still weird
UPD2: looks like it appears only on mac OS

**Comment by eXponenta** [comment]
Not reproduced.

https://www.pixiplayground.com/#/edit/FO6BHsYf7_bDFnefDaZTs

Could you create simple test?

**Comment by ivanpopelyshev** [comment]
> PixiJS Deprecation Warning: PIXI.mesh.NineSlicePlane class has moved to PIXI.NineSlicePlane

@eXponenta he's using v4

@lisovskyR please move to v5. We certainly wont fix this in v4.
