### ISSUE TITLE
Incorrect documentation for `PIXI.Program.from`

### ISSUE THREAD

**Issue by Ldash4** [pixijs/pixi.js#6137]
[Documentation for `PIXI.Program.from` is incorrect.](https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/shader/Program.js#L225) JSDoc says that the signature is `(vertexSrc: string, fragmentSrc: string, uniforms: object)`, when the expected signature is `(vertexSrc: string, fragmentSrc: string, name: string)`.

- **`pixi.js` version**:  5.1.5
- **Browser & Version**: n/a
- **OS & Version**: n/a
- **Running Example**: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/shader/Program.js#L225

**Comment by bigtimebuddy** [comment]
PR welcome to fix this. good catch.
