### ISSUE TITLE
BitmapText line height issue

### ISSUE THREAD

**Issue by andrevenancio** [pixijs/pixi.js#6138]
I can't seem to change the line height without having to re-export the bitmap-fonts all the time.
Which is impractical because you might want to have the same bitmap font with different line-heights.

Following up the code [here](http://pixijs.download/release/docs/packages_text-bitmap_src_BitmapText.js.html#line587) it seems to be possible to pass a prop `lineHeight` with a big enough value, and then whenever a new paragraph happens, that will be taken in consideration.

However no matter how high I put this value, I can't seem to have any different result.

Example:
```
this.subtitle = new BitmapText('LOREM IPSUM OR WHATEVER BIG ENOUGH TEXT', {
            font: '40px ITC Franklin Gothic',
            align: 'center',
            lineHeight: 500, // doesn't work
            wordWrap: true,
});
this.subtitle.maxWidth = 1000;
this.subtitle.wordWrap = true;
this.subtitle.lineHeight = 500; // doesn't work either
this.addChild(this.subtitle);
```

**Comment by themoonrat** [comment]
BitmapText does not have a 'lineheight' property. It's the xml data that contains this value. It's a data driven format for text as opposed to normal Text which has more control of the styling.

**Comment by andrevenancio** [comment]
Not sure I agree with you there... The property exists in the code, and as far as I can tell its used when the `registerFont` static method gets called. this method gets called when the bitmap font gets loaded for the first time. So in theory changing lineHeight at the very first time the font is loaded it would work. But this doesn't allow for changing the line-height from container to container, and if you can do it with the character spacing why not with line-height? :)

**Comment by andrevenancio** [comment]
Pseudo code:

constructor()
```
this._lineHeight = style.lineHeight || 0;
```

updateText()
```
pos.y += data.lineHeight + this.lineHeight;
```

setter/getters
```
get lineHeight() {
  return this._lineHeight;
}

set lineHeight(value) {
  if (this._lineHeight !== value) {
    this._lineHeight = value;
    this.dirty = true;
  }
}
```

Is this a feature anyone finds useful, I'm happy to do a PR. otherwise I'll override my BitmapText class as I need to dispatch something to production addressing this issue.

**Comment by andrevenancio** [comment]
@GoodBoyDigital ?

**Comment by bigtimebuddy** [comment]
Sure, PR welcome for this! Please just make sure you align with the normal TextStyle units for the lineHeight. I’m not sure if it’s scalar value based on the type or a real pixel value. Whatever it is, BitmapText should try to do the same.

**Comment by ivanpopelyshev** [comment]
In general, lineheight should be formed from ascent, descent and leading. Does anyone know how did setting line height work in Flash?

**Comment by andrevenancio** [comment]
> In general, lineheight should be formed from ascent, descent and leading. Does anyone know how did setting line height work in Flash?

Tell that to a designer 😭

**Comment by andrevenancio** [comment]
There's a reference [here](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextLineMetrics.html) but not sure how they did their implementation. I think we could do this in two ways

1) automatic have the `.lineHeight` to be the same as the bitmap font size
So for example `label.lineHeight` will return a integer corresponding to the font size

```javascript
const label = new BitmapText("Lorem Ipsum",
  {
    font: '36px SomeRandomFont',
  }
);
```

so `console.log(label.lineHeight)` will yield 36;

or

2) Or we have lineHeight always to be 0 and this works a little bit like an extra "padding". Calling it `.lineHeight` might be confusing because `.lineHeight = 0;` I'm expecting to have all lines drawn in over each other. So maybe something line `.lineSpacing` so its similar to the existing `.letterSpacing`... 

I think the `1)` option is more robust for people used to do CSS. But if we want to keep mirror the flash api then maybe we can call it `leading` and go with option `2)`. I don't remember the exact implementation but I assume leading is 0 when we want to use the specified lineHeight coming through the XML on the bitmap-font, and we can increase it to increase the space between lines.

Happy to implement either, I kind of just need to be able to increase the space in between lines for a project :)

**Comment by molst** [comment]
Thumbsup for this addition!
