### ISSUE TITLE
PIXI will not render a sprite with a new texture unless renderer.render() is deferred?

### ISSUE THREAD

**Issue by lk-jeffpeck** [pixijs/pixi.js#6142]
Consider this example:
```
const ballTexture = `data:image/svg+xml;charset=utf8,<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800"><defs><defs><radialGradient id="gradient-%23FFCCCC" gradient-units="userSpaceOnUse" cx="60%" cy="40%" r="60%"><stop offset="0%" stop-color="rgb(255,204,204)" stop-opacity="1"/><stop offset="7.8%" stop-color="rgb(255,204,204)" stop-opacity="0.98"/><stop offset="18.5%" stop-color="rgb(255,204,204)" stop-opacity="0.96"/><stop offset="27.7%" stop-color="rgb(255,204,204)" stop-opacity="0.92"/><stop offset="60.2%" stop-color="rgb(255,204,204)" stop-opacity="0.85"/><stop offset="78.7%" stop-color="rgb(255,204,204)" stop-opacity="0.78"/><stop offset="100%" stop-color="rgb(255,204,204)" stop-opacity="0.4"/></radialGradient></defs></defs><circle cx="50%" cy="50%" r="50%" style="fill: url(&quot;%23gradient-%23FFCCCC&quot;);"/></svg>`

const test = () => {
  const renderer = PIXI.autoDetectRenderer({
    view: document.getElementById('test-canvas'),
    width:240,
    height:240,
    backgroundColor: 'black',
  });
  const stage = new PIXI.Container();
  const texture = PIXI.Texture.from(ballTexture);
  const sprite = new PIXI.Sprite(texture);

  stage.addChild(sprite);

  const [x, y, radius] = [120, 120, 100];
  sprite.x = x - radius;
  sprite.y = y - radius;
  sprite.height = 2 * radius;
  sprite.width = 2 * radius;

  // renderer.render(stage); # Will not render!!!!

  setTimeout(() => { renderer.render(stage) });
}
```

If I call the above example, it will not render anything if I call `renderer.render(stage)` directly at the end. Instead I need to `setTimeout(() => { renderer.render(stage) })`.

After a little digging, I found that if I set:
```
texture.on('update', () => { console.log(`texture updated!`) });
```

and end with:
```
renderer.render(stage);
console.log('rendered!');
```

the texture is actually updating _after_ the call the renderer.render()!

I tried explicitly calling `texture.update()` with no affect.

### Expected Behavior

PIXI will update the texture before rendering it.

### Current Behavior

PIXI does not update the texture until after rendering has happened, resulting in a blank image.

### Possible Solution

Deferring the call to `renderer.render(stage)` by wrapping in `setTimeout()` seems to do the trick, but it is not ideal to use in every case as it can cause an image to drag (in my use-case anyway). One work-around is to _only_ wrap in `setTimeout()`  when the texture changes, but it's a slightly messy solution.

One other solution is to do:
```
texture.on('update', () => { // trigger render here! });
```

In my actual use-case, I am updating several textures and would not want to trigger until all have been updated. It would not be difficult to implement, but I'd rather use a cleaner solution if available.

### Steps to Reproduce

See example above.

### Environment

- **`pixi.js` version**:  5.1.5
- **Browser & Version**:  Chrome 77
- **OS & Version**:  MacOS Mojave
- **Running Example**: Try to run `test()` after page loads with `<canvas id="test-canvas"/> somewhere on the page

**Comment by lk-jeffpeck** [comment]
Thinking this through, I actually think the second "Possible Solution" is the way to go!

(It helped to make the ticket though, and I will leave this in case anyone finds it and is in a similar predicament.)

In my actual use case, I have some textures defined by some rgb hex color stings:
```
this.markerTextures = generateMarkerTextures(colors, this._maxRadius);
```

I set a a flag to false for each color:
```
const colorsDidUpdate = Object.assign({}, ...colors.map(c => ({[c]: false})));
```

And then:
```
    colors.forEach(color => {
      this.markerTextures[color].once('update', () => {
        colorsDidUpdate[color] = true;
        if (Object.values(colorsDidUpdate).every(Boolean)) {
          this._triggerUpdateViewport();  // this includes the call to `renderer.render()`
        }
      });
    });
```

And just like that, everything works as expected!

---

I believe the reason I had trouble with this is because it's not a typical use-case of PIXI.js to call renderer.render() directly, outside of an animation loop.

In my case, I wanted to update the canvas _immediately_ after a user selects new colors/textures. And so I thought to trigger the render event right after doing so.

It might make sense to state somewhere in the documentation that the creation/updating of new textures is deferred. But otherwise, I think this is resolved.

**Comment by bigtimebuddy** [comment]
Your code worked for me (Chrome 77): https://www.pixiplayground.com/#/edit/VTEHqbFYmE~7it05HaabV

**Comment by lk-jeffpeck** [comment]
@bigtimebuddy Well, hrm. That seems odd. But, I think I see what is happening!

On the PIXI Playground, try changing one character of the `ballTexture` svg. You notice how it comes up black?

Now, change it to something else and then change it back. You see the image reappear?

**Comment by lk-jeffpeck** [comment]
Here is what I ultimately ended up doing, and works well!

I initialize a PIXI.loader() in the constructor of my class and use it to call `this.loader.add(colorHex, colorTextureString)` where `colorHex` is something like '#ff00aa' and `colorTextString` is something similar to `ballTexture` in the example above (but generated based on that `colorHex` value).

Every time the colors update, I do this:
```
    newColors.forEach(color => {
      const colorTextureString = getColorTextureString(color, this._maxRadius);
      this.loader.add(color, colorTextureString);
    });

    this.loader.load((loader, resources) => {
      Object.entries(resources).forEach(([color, resource]) => {
        this.markerTextures[color] = resource.texture;
      });

      this._triggerUpdateViewport();
    });
}
```

This ensures that `this._triggerUpdateViewport()` will only be called _once_ and only _after all textures are truly loaded_.

---

I could not find a way to do this as cleanly with `PIXI.Texture.from()`, but I am ultimately happy with this solution.

**Comment by bigtimebuddy** [comment]
Your solution is the best way to do this. Loading from a data-uri is not guaranteed to be a synchronous process and you can not be certain that Texture.from will load a valid texture in all browsers. Best to go though the loader. 

Closing as this seems answered.
