### ISSUE TITLE
[Docs] What needs doing most?

### ISSUE THREAD

**Issue by carlsmith** [pixijs/pixi.js#6143]
I'd like to start contributing to the PIXI documentation, and wondered where to start. I'm not a PIXI wizard, but am familiar with the library and regularly work with it, so should be able to help, and I'll improve over time.

The API docs contain a lot of minor grammatical errors that would be easy for me to start with, but those docs are already readable, so I wondered if there's anything that needs more urgent attention.

Any ideas??

**Comment by bigtimebuddy** [comment]
Thanks for helping! Definitely grammatical stuff needs some help as well as having a consistent tense and tone.

After that, a good place to start is looking at the top 25 pages. Here are the Google Analytics for the past month:

![Screen Shot 2019-10-04 at 3 07 27 PM](https://user-images.githubusercontent.com/864393/66243231-b1086880-e6b8-11e9-8bd4-47628457f653.png)

Prioritizing these pages, I think, is a good focus. Want to make sure that there are no blaring gaps in those pages.

**Comment by carlsmith** [comment]
> Prioritizing these pages, I think, is a good focus. Want to make sure that there are no blaring gaps in those pages.

Good thinking. That's ideal. Thanks.
