### ISSUE TITLE
Understanding shaders in v5

### ISSUE THREAD

**Issue by lancewellspring** [pixijs/pixi.js#6144]
- **`pixi.js` version**: 5.1.5
- **Browser & Version**:  Chrome 77.0.3865.90
- **OS & Version**: Windows 10 Prof
- **Running Example**: https://www.pixiplayground.com/#/edit/oc2KBcabLO9Wmh_qp_~0J

The shader programs get called for every pixel in the geometry, each frame, correct?  So for one particular pixel, say 50x, 50y in the playground I linked, p1 = vec2(50, 50), and vUvs = vec2(.75, .75), right?

If my assumptions above are correct, then I feel like something isn't working properly here.  The function squareToCircle is supposed to transform the square into a circle, which clearly isn't happening.  Additionally, the mapped variable should be .734x, .734y for the above example, but if you uncomment the bit in the fragmentSrc so that it uses mapped instead of vUvs, everything becomes a single color, which implies that x1 and y1 in the squareToCircle are always 0, which just doesn't seem right at all.

What am I missing?

**Comment by ivanpopelyshev** [comment]
> The shader programs get called for every pixel in the geometry, each frame, correct?

Yes, but you put your mapping to vertex shader instead of fragment, so it rans on 4 vertices and transforms them to another four vertices, its still two triangles.

Mapping has to be inside fragment shader, not vertex.

**Comment by ivanpopelyshev** [comment]
Wanna see real difficult mapping? https://github.com/pixijs/pixi-projection/blob/master/src/curve/SpriteBilinearRenderer.ts#L38 , That's a bilinear, i didnt port it to v4 yet :)

I'm too tired to help you with your shader, but maybe next week if you dont get it then.

**Comment by lancewellspring** [comment]
Your comments actually helped me realize I misunderstood some things, and now I've got it working.  Thanks for the help!
