### ISSUE TITLE
BitmapText texture loading error when using defaultQueryString

### ISSUE THREAD

**Issue by soylomass** [pixijs/pixi.js#6147]
When using bitmaptext with that parameter set, an error happens in this line:

text-bitmap.es.js
line 797 if (bitmapResource.url === url)
As bitmapResource.url has the defaultQueryString appended and url doesn't, so the comparison fails, and it tries to load the texture again, resulting in a fatal exception.

**Comment by soylomass** [comment]
It can be fixed by changing line to 
bitmapResource.url === url + '?' + PIXI.Loader.shared.defaultQueryString

**Comment by soylomass** [comment]
Can't provide source at the moment, but set the defaultQueryString:

 PIXI.Loader.shared.defaultQueryString = "v=2";

Then add a bitmapfont through an xml file and load.

**Comment by bigtimebuddy** [comment]
Cannot reproduce: https://jsfiddle.net/bigtimebuddy/s1okhy90/

Closing.
