### ISSUE TITLE
Some videos displayed inverted or incorrect orientation

### ISSUE THREAD

**Issue by lilredc5** [pixijs/pixi.js#6148]
### Expected Behavior
Video on Pixi stage should display in same orientation as video source is displayed by browser.

### Current Behavior
Some videos display inverted or sideways.  The behavior is consistent between iOS and MacOS, Chrome and Safari.  This occurs with Pixi 5.1.4.  It worked correctly in 4.8.8.

### Possible Solution
My guess is that Pixi is displaying the video in the very same way that the data exists in memory, but that the browser is rotating videos in some cases based on the video's metadata, which might indicate that the video should rotate some degrees.

### Steps to Reproduce
    // Open local video file 
    public openFile(event): void {
        let video = document.createElement('video');
        video.playsinline=true;
        video.type=event.srcElement.files[0].type;
        video.src=window.URL.createObjectURL(event.srcElement.files[0]);
        video.load();

        this.stage = new PIXI.Container();
        this.renderer = new PIXI.Renderer({width:this.canvasWidth, height:this.canvasHeight });
        this.baseTexture = PIXI.BaseTexture.from(video, {resourceOptions: {autoPlay: false}});
        this.baseTexture.autoPlay = false;
        this.texture = new PIXI.Texture(this.baseTexture);

        this.sprite = new PIXI.Sprite(this.texture);

        this.renderer.render(this.stage);
    }

### Environment

- **`pixi.js` version**: 5.1.4
- **Browser & Version**: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- **OS & Version**: MacOS Mohave 10.14.5
- **Running Example**:

**Comment by lilredc5** [comment]
The attached gzipped tarball has a video that works fine and one that does not.  Both were recorded with an iPhone, but one recorded upside down.

[example.tar.gz](https://github.com/pixijs/pixi.js/files/3785136/example.tar.gz)

**Comment by bjoseph1** [comment]
@GoodBoyDigital Hey Mat - Can we get some help on this one, it's been sitting for a few months?  Thanks
