### ISSUE TITLE
"removed" event of PIXI.DisplayObject

### ISSUE THREAD

**Issue by ZeratulDev** [pixijs/pixi.js#6153]
"removed" event not fired in DisplayObject when removed from container. 

### Steps to Reproduce
```
let a = new PIXI.Container();
let b = new PIXI.Container();
b.on("added", () => {
  console.log("added fired");
});
b.on("removed", () => {
  console.log("removed fired");
});
a.addChild(b); // added fired 
a.removeChild(b); // nothing
```
### Environment

- **`pixi.js` version**: _5.1.5_
- **Browser & Version**: _Chrome 77_
- **OS & Version**: _Windows 10_
- **Running Example**:

**Comment by ivanpopelyshev** [comment]
Not confirmed. Both fired.

https://www.pixiplayground.com/#/edit/9ETJlCFtebY1EZL3Hfajf , i've added your code to the end of example. Look in the console.

**Comment by ZeratulDev** [comment]
Yes, can't reproduce as simplified code too. Have issue when use removeChild() on complete event of greensock animation. sorry.
