### ISSUE TITLE
Pixi.js-legacy as a drop-in replacement for Pixi.js in Webpack bundles

### ISSUE THREAD

**Issue by flekschas** [pixijs/pixi.js#6155]
We build a package that depends on pixi.js v5. By default, we assume WebGL support is given and that users use the normal version of pixi.js v5. Hence, in our code we import Pixi stuff using `import * as PIXI from 'pixi.js';`. Additionally, we would like to allow users to also use pixi.js-legacy in case they would like to render with the Canvas API.

This works fine as the bundle of our package (let's call it _ourPackage_) treats `pixi.js` as a global variable. So the user can either load `pixi.min.js` or `pixi-legacy.min.js` prior to loading `ourPackage.min.js` in their HTML file.

### Current Behavior

Now an issue arises when we try to build a new application (let's call it _newApplication_) that depends on _ourPackage_, and  _newApplication_ is bundled into a single JS file with Webpack.

When we install `pixi.js-legacy` in _newApplication_ and try to create a bundle we will get an error as Webpack can't resolve the `pixi.js` dependency in _ourPackage_ stemming from `import * as PIXI from 'pixi.js';`. This makes sense so we tell Webpack to treat `pixi.js` as an alias for `pixi.js-legacy` in the Webpack config as follows:

```
{
  resolve: {
    alias: {
      'pixi.js': path.resolve('./node_modules/pixi.js-legacy')
    }
  }
}
```

Doing so will fix the issue with the unresolved import of `pixi.js` but it will create a new issue because `pixi.js-legacy` is relying on three `pixi.js` import: https://github.com/pixijs/pixi.js/blob/dev/bundles/pixi.js-legacy/src/index.js#L1

Of course, these three imports can't be resolved because we had to tell Webpack that `pixi.js` is an alias for `pixi.js-legacy` but `pixi.js-legacy` doesn't export these properties. Hence I am getting

```
Attempted import error: 'accessibility' is not exported from 'pixi.js'.
```

### My question

Is there a way to use `pixi.js-legacy` as a drop-in replacement for `pixi.js` in this context? If not, can you guys think of another way to support both versions of pixi.js v5?

### Environment

- **`pixi.js-legacy` version**: 5.1.5
- **`webpack` version**: 4.41.1

**Comment by ivanpopelyshev** [comment]
I'm glad that there are so many new tasks for community generated by webpack adoption!

Especially by poor library creators. 

/me looking at his 10 pixi plugins and crying

**Comment by ivanpopelyshev** [comment]
Am I right that you have mixed ES6 vanilla/modules usage here? How exactly do your users load modules? `<script src=` or `script type= "module" src=` ?

**Comment by flekschas** [comment]
No this has nothing to do with a mix of ES6 and vanilla JS. This is about a clash in using `pixi.js-legacy` as a drop-in replacement for `pixi.js` when the code is bundled with Webpack.

As a developer who uses `pixi.js` I would like to write code that can be bundled with either `pixi.js` or `pixi.js-legacy`. Simply installing `pixi.js-legacy` won't work though because webpack wouldn't be able to resolve it as `pixi.js` when importing it with `import * as PIXI from 'pixi.js';`. Setting an `alias` also doesn't work because `pixi.js-legacy` requires `pixi.js`. So the only way to get this working is to duplicate https://github.com/pixijs/pixi.js/blob/dev/bundles/pixi.js-legacy/src/index.js and set a different `alias` for `pixi.js` as follows.

**Workaround:**

To work around the issue one has to copy the code from https://github.com/pixijs/pixi.js/blob/dev/bundles/pixi.js-legacy/src/index.js into a new file called `src/pixi.js`. Now only the first line needs to be changed in this new file. I switch `pixi.js` to `pixi.js-new`:

```javascript
import { accessibility, interaction, prepare, extract } from 'pixi.js-new';
import { CanvasRenderer, canvasUtils } from '@pixi/canvas-renderer';
import { CanvasMeshRenderer } from '@pixi/canvas-mesh';
import { CanvasGraphicsRenderer } from '@pixi/canvas-graphics';
import { CanvasSpriteRenderer } from '@pixi/canvas-sprite';
import * as canvasExtract from '@pixi/canvas-extract';
import * as canvasPrepare from '@pixi/canvas-prepare';
import '@pixi/canvas-sprite-tiling';
import '@pixi/canvas-particles';
import '@pixi/canvas-display';
import '@pixi/canvas-text';

CanvasRenderer.registerPlugin('accessibility', accessibility.AccessibilityManager);
CanvasRenderer.registerPlugin('extract', canvasExtract.CanvasExtract);
CanvasRenderer.registerPlugin('graphics', CanvasGraphicsRenderer);
CanvasRenderer.registerPlugin('interaction', interaction.InteractionManager);
CanvasRenderer.registerPlugin('mesh', CanvasMeshRenderer);
CanvasRenderer.registerPlugin('prepare', canvasPrepare.CanvasPrepare);
CanvasRenderer.registerPlugin('sprite', CanvasSpriteRenderer);

Object.assign(prepare, canvasPrepare);
Object.assign(extract, canvasExtract);

// Export ES for those importing specifically by name,
// e.g., `import {autoDetectRenderer} from 'pixi.js-legacy'`
export * from 'pixi.js';
export {
    CanvasRenderer,
    CanvasGraphicsRenderer,
    CanvasMeshRenderer,
    CanvasSpriteRenderer,
    canvasUtils,
};
```

In the Webpack config I now set the following aliases:

```json
{
  resolve: {
    alias: {
      'pixi.js-new': path.resolve('./node_modules/pixi.js'),
      'pixi.js': path.resolve('./src/pixi.js')
    }
  }
}
```

This fixes the circular import issue 🎉 but it requires duplicated code. Of course, `pixi.js-legacy`
still needs to be installed with npm otherwise some imports will be missing.

**Comment by bigtimebuddy** [comment]
Aliasing approach in that way will not work because pixi.js-legacy is a superset of pixi.js (as you already found out).

Why not do something like this in your Webpack config? 
```js
let pixiAny;
try { 
    pixiAny = path.resolve('pixi.js-legacy');
} catch (err) {
    pixiAny = path.resolve('pixi.js');
}
// ...
{
  resolve: {
    alias: {
      'pixi.js-any': pixiAny
    }
  }
}
```

```js
import * as PIXI from 'pixi.js-any';
```

**Comment by flekschas** [comment]
That would also work but we'll have to replace all occurrences of `import * as PIXI from 'pixi.js';` in our package. We might end up doing that but I was hoping there's another way that doesn't require us to touch our package.

**Comment by bigtimebuddy** [comment]
The other alternative is don’t bundle pixi.js and treat it as an external dependency. And leave it up to your downstream users to make sure the PIXI global is available via whatever bundle they choose.

**Comment by bigtimebuddy** [comment]
Ultimately this seems like a webpack and bundling issue. There are a bunch of workarounds here and many of them depend on the specifics of what you’re trying to achieve. We are unlikely to change the dependency relationship between pixi.js-legacy and pixi.js so I’m closing this issue.
