### ISSUE TITLE
Graphics with hole containsPoint issue

### ISSUE THREAD

**Issue by xuyangbill** [pixijs/pixi.js#6156]
### Current Behavior
the first graphicsData has a hole,the second graphicsData is in the hole.click the second graphicsData,hitTest return false
### Possible Solution
https://github.com/pixijs/pixi.js/blob/460992f299abd87e698d5286180e320c42482cc1/packages/graphics/src/GraphicsGeometry.js
line 385:continue when hole contains point

### Environment

- **`pixi.js` version**:4.8.8
- **Browser & Version**: Chrome 76.0.3809.100
- **OS & Version**:win10
- **Running Example**: 
```
function render(view: PIXI.Graphics) {
    view.clear();
    view.beginFill(0xff0000, 1);
    const outer = [new PIXI.Point(1000, 1000),
    new PIXI.Point(1000, 8000),
    new PIXI.Point(8000, 8000),
    new PIXI.Point(8000, 1000)];
    const holes = [[new PIXI.Point(3000, 3000),
    new PIXI.Point(3000, 6000),
    new PIXI.Point(6000, 6000),
    new PIXI.Point(6000, 3000)]];
    drawPolygonWithHoles(view, outer, holes);
    view.endFill();

    view.beginFill(0x00ff00, 1);
    const inner = [new PIXI.Point(4000, 4000),
    new PIXI.Point(4000, 5000),
    new PIXI.Point(5000, 5000),
    new PIXI.Point(5000, 4000)];
    drawPolygon(view, inner);
    view.endFill();
}

function drawPolygon(view: PIXI.Graphics, points: PIXI.Point[]) {
    points.push(points[0]);
    view.drawPolygon(points);
}

function drawPolygonWithHoles(graphics: PIXI.Graphics, outer: PIXI.Point[], holes: PIXI.Point[][]) {
    graphics.currentPath = null!;
    drawPolygon(graphics, outer);
    holes.forEach(hole => {
        graphics.currentPath = null!;
        drawPolygon(graphics, hole);
        (graphics as any).addHole();
    });
}
```

**Comment by ivanpopelyshev** [comment]
Unfortunately, I can't use continue there due to jslint rule.

```
  354:9   warning  Using 'LabeledStatement' is not allowed  no-restricted-syntax
```

build will be here: https://pixijs.download/fix-hole-hittest/pixi.js

**Comment by ivanpopelyshev** [comment]
Oh, right, you need pixi-v4?

**Comment by ivanpopelyshev** [comment]
v4 fix here: https://pixijs.download/v4.x-fix-hithole/pixi.js

**Comment by markalzate13** [comment]
<!document html>
<html>
<head>
<body>
<title></title>
<quoted: message“pixi.js>
<quote>
</quote>
<block>
</block>
Packyouth
(¡¡)
Agal
Ala
Ti
Ti<p>
::
</p>

On 10/12/19, Ivan Popelyshev <notifications@github.com> wrote:
> v4 fix here: https://pixijs.download/v4.x-fix-hithole/pixi.js
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pixijs/pixi.js/issues/6156#issuecomment-541334586


-- 
Mark Alzate
