### ISSUE TITLE
The 'pointerout' event cannot be triggered on the phone.

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixi.js#6157]
Use Chrome DevTools(Mobile Simulation):

https://pixiplayground.com/#/edit/vxt55MKGiGk3wC2h_~GsN

Is there any way to monitor `pointerout` events on mobile devices?

**Comment by eXponenta** [comment]
![image](https://user-images.githubusercontent.com/12572222/66700850-4b425f00-ecfe-11e9-9d6d-a5d46fb3a29d.png)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerout_event
