### ISSUE TITLE
how to preload the font about type of .ttf

### ISSUE THREAD

**Issue by WeiFree** [pixijs/pixi.js#6158]
i need to use external font , i add in loader， but when the loader complete ,the external font still unload. so how can i load the font about type of .ttf
Thank you 

- **`pixi.js` version**: _e.g. 4.8.8_

**Comment by themoonrat** [comment]
Use https://github.com/bramstein/fontfaceobserver to preload fonts rather than the pixi loader.

**Comment by bigtimebuddy** [comment]
Duplicate #5474
