### ISSUE TITLE
PIXI.loader v5 types misleading

### ISSUE THREAD

**Issue by connorjclark** [pixijs/pixi.js#6161]
### Current Behavior

```
// no typescript errors
PIXI.loader.add(...)
```

but at runtime, `PIXI.loader` is undefined.

### Possible Solution

Change `PIXI.loader` to `never` (the jsdoc points to `PIXI.Loader.shared` so migration steps are obvious)

### Environment

- **`pixi.js` version**: 5.1.5

**Comment by ivanpopelyshev** [comment]
pixi-v5 types include deprecations.

**Comment by bigtimebuddy** [comment]
I suggest we exclude the deprecations file from the types generation.

**Comment by eXponenta** [comment]
There is a second problem. 
There is a types for pixi v4 in Microsoft type library, and vs code use it as default
