### ISSUE TITLE
How to remove specific color to make image transparent.

### ISSUE THREAD

**Issue by iamappmaker** [pixijs/pixi.js#6178]
I am trying to remove specific color from image and video to make it transparent.
i found pixi v3 example https://jsfiddle.net/pm02gwgq/10/ but after trying many times i can't able to convert the code to v5.
Please help me.

**Comment by ivanpopelyshev** [comment]
Its easy but I'll help you tomorrow :)

**Comment by eXponenta** [comment]
@iamappmaker 
https://www.pixiplayground.com/#/edit/mtG9LU1VmxcNdcDAvriGC

About passig custom uniforms to filter look this: https://github.com/pixijs/pixi.js/tree/dev/packages/filters

**Comment by ivanpopelyshev** [comment]
here we go: https://www.pixiplayground.com/#/edit/BalkST7v1zt8IM5ccSudL

**Comment by iamappmaker** [comment]
Thank you. I always feel there are many things to explore in pixi and played with all the filters, made animations etc. Is there any other new filter created by you or anyone else?
One more curious question. Is it possible to do like pixaloop app does.

**Comment by ivanpopelyshev** [comment]
Here's good collection of filters: https://beatflyer.com/
