### ISSUE TITLE
texImage2D problem in IE11

### ISSUE THREAD

**Issue by softshape** [pixijs/pixi.js#6183]
Running Pixi v4.8.6 and IE11 under Windows 10 we're getting the following error:

```
SCRIPT5022: SecurityError
GLTexture.js (94,1)
```
In the line 94 is **gl.texImage2D()** is called. The code is stopped then.

Any idea what can be wrong? It works fine with modern browsers, but we need to support IE11 also.

**Comment by ivanpopelyshev** [comment]
something with CORS?

**Comment by eXponenta** [comment]
Please,
use some last version of pixi v4 or migrate to v5, then make fiddle with bug reproducing.
