### ISSUE TITLE
Google Ads reporting "html5 assets are malformed" using Pixi.JS

### ISSUE THREAD

**Issue by mbpictures** [pixijs/pixi.js#6185]
Hi!
I just found out, that google won't accept playable ads or normal html5 assets which are using pixi.js. By removing the functions the XHR and XDR functions of pixi.js. Maybe you can provide some kind of "XHR/XDR" free version of the plugin?
Thank you already and nice plugin ;)

**Comment by bigtimebuddy** [comment]
How do you load assets without XHR in this context? Is everything just bundled together? Also which pieces did you have to remove?

**Comment by ivanpopelyshev** [comment]
I know that google ads is difficult to make compared to facebook ad. @eXponenta  knows more.

**Comment by eXponenta** [comment]
You can build custom pixi version without Loader.
But only v5, for v4 you can do it manualy.

**Comment by mbpictures** [comment]
Thank you guys for your help!
@bigtimebuddy yeah I base64 encoded all assets (images and sound) to work with facebook and unity ads. I removed all function bodies which are using the some kind of XHR event handling (_loadXHR, loadXDR ? Can't remember the name :/)
@eXponenta yes i used the Texture.from("") method to pass a base64 encoded image in the texture, that worked without using XHR. Ouh.. that customizer would have been usefull :D Also.. this html validator didn't work. I first uploaded my ad and it said it has to be less than 150KB (google says 1MB?!). Anyways, I uploaded an zip with just an html basic structure inside and it loaded for hours without an result :/

**Comment by eXponenta** [comment]
@mbpictures 

![image](https://user-images.githubusercontent.com/12572222/67165630-3b76ea80-f390-11e9-8f74-cf957f06a9a0.png)

This is single and recommended validator for Google ADS =).
https://support.google.com/google-ads/answer/7584219

Please, check documentation before creating anything!

**Comment by shahho** [comment]
My playable files is Through the review of Google tester:[https://h5validator.appspot.com/adwords/asset](url)。
and i published the playable,After 24 hours,
I have received from Google ADS mail:



Ads (2) impacted by Google Ads policy
--
Campaign: 
App_Utopia_ID_Android_H5_1122
 [​8​1​8​5​8​0​1​1​8​0​]

Disapproved
Ads (1)
Policy: | **Invalid fourth party call, Unacceptable HTML5 ad**

Disapproved
Ads (1)
Policy: | **Punctuation and symbols**

What should I do？thank guys!

**Comment by eXponenta** [comment]
So.... Ask a Google what it means.😁

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dranitski** [comment]
Hi all! I had an issue that can be related 

I have to remove some lines from pixi loader code for my playable to be accepted by google validator 🤦🏻‍♂️

Without that it didn’t accept my playable because of some mysic error, something like “wrong url: data::”

Take a look at line 1548 https://pastebin.com/Wf0368X8

**Comment by phloud** [comment]
great stuff here, thanks for the pioneering work on demystifying the html5 validators generic errors. I was getting "Missing asset check" and under "More details" this helpful bullet item: "INVALID_URL_REFERENCE: data:" Not a lot to go on and couldn't find anyone talking about it except for this issue. I'm creating playables in a single html file and using @dranitski fix worked for me! great way to start 2020!

**Comment by dranitski** [comment]
I know it may not fit this thread well, but I know no other place to put that information.

Google assets validator (https://h5validator.appspot.com/adwords/asset) now shows strange error 
`Unsupported creative size 480x320` if you have `<meta name="ad.size" content="width=480,height=320">` in your playable ad despite 480x320 is a valid playable ad size according to all documentation I have.

The solution is to change playable size meta-tag to `<meta name="ad.size" content="width=300,height=250">` for example.

According to support and docs it really not matters much:
> The system will still size the ad frame according to device dimension larger than 320x480, making the unit responsive.

> Note on Ad Preview:
> Ad preview will only show your ad in one size, depending on the dimension referenced in the header of the HTML file. Don't assume that the ad will always be rendered in that size as explained above.

> We realize that the 320x480 label requirement in the header representing portrait interstitial of variable size is confusing. However, it is mandatory in order for UAC to serve the asset in the right dimension. If the asset is responsive, UAC will still serve it accurately according to the screen size (i.e. iPhone 4 vs 7). We hope to remedy this experience in the future, and we appreciate your patience in the meantime.

From google support email
> On the top left hand side of H5 Validator, there is an adjustable area but it is nothing more than a preview for advertisers to adjust their assets on their own without affecting the actual asset dimension. Therefore, to answer your question "if the the dimensions of HTML5 asset in H5 validator makes any difference?", the answer is yes. This is because at the time of uploading the asset in H5 validator tool, it requires you to check the box "Select for App Campaigns", which means that only supported dimensions can be uploaded. 

> Having said that, H5 validator is still not accepting 480x320 and 320x480 ads because of a known internal issue (as we have shared in the last response and the internal details have been shared with AM).

> Please note that for the supported dimension for AC, our system will adjust the dimension according to the device/inventory size if the creative's orientation is declared as such. As such, if the size of file playable-v200, will be updated from 480X320 to 300X250 the system allows to upload the asset in H5 Validator and will also be responsive in the actual serving as well.
