### ISSUE TITLE
Overlapping holes cause drawing artifacts

### ISSUE THREAD

**Issue by plurry** [pixijs/pixi.js#6187]
Using `beginHole` to make overlapping holes in a `PIXI.Graphics` instance often messes up. In my case I was trying to draw hexagons that touch each other but, it can be seen even with overlapping rectangles in Pixi 5.1.5.

```javascript
g.beginFill(0xFF, 0.5);
g.drawRect(0, 0, 200, 200);
g.endFill();

g.beginHole();
g.drawRect(10, 10, 50, 50);
g.endHole();

g.beginHole();
g.drawRect(30, 30, 100, 100);
g.endHole();
```
https://www.pixiplayground.com/#/edit/KxM_1~VTzYqbAYOnf7r3O

If you replace the `beginHole` calls with regular `beginFill` calls, they're drawn overlapping without any problem.

**Comment by eXponenta** [comment]
It is limitations of triangulator used in pixi. earcur doesn't support this case. 
The docs notices about it.
https://pixijs.download/dev/docs/PIXI.Graphics.html#beginHole
