### ISSUE TITLE
Accessibility issue when resolution is set

### ISSUE THREAD

**Issue by c-andrews** [pixijs/pixi.js#6189]
Hi I am currently having an issue with Accessibility when the app resolution is set to the devicePixelRatio with a full screen canvas.

I have created a Pen to show the issue: https://codepen.io/c-andrews/pen/abbWJZd?editors=0010
Im currently working in Chrome. I don't seem to be able to tab into anything on Safari on a Mac but thats another issue.

When tabbing in Chrome the highlighted div is not over the button. If i remove the resolution from the App constructor then things are fine but I don't get the quality I need. 

I am using the latest version of Pixi: 5.1.5.

I've also attached a screen shot:

<img width="512" alt="Screenshot 2019-10-24 at 15 29 10" src="https://user-images.githubusercontent.com/1464901/67496297-19bd8200-f674-11e9-89ca-10a8f34dc41e.png">

Any help would be really appreciated, please let me know if i am missing something.

**Comment by ivanpopelyshev** [comment]
Try `autoDensity: true,` near resolution. Its not magic, it sets `view.style.width` and `view.style.height`.
