### ISSUE TITLE
pixi.js5.1.5

### ISSUE THREAD

**Issue by Steven201314** [pixijs/pixi.js#6190]
when we use pixi.js5.1.5 in babylon, after 'npm run build ', the ide(vscode) reports error like this
`ERROR in ./node_modules/querystring-es3/index.js
Module not found: Error: Can't resolve './decode' in 'D:\workspace\babylonjs\h5_game_project\node_modules\querystring-es3'
 @ ./node_modules/querystring-es3/index.js 3:33-52
 @ ./node_modules/url/url.js
 @ ./node_modules/@pixi/utils/lib/utils.es.js
 @ ./node_modules/pixi.js/lib/pixi.es.js
 @ ./src/index.ts

ERROR in ./node_modules/querystring-es3/index.js
Module not found: Error: Can't resolve './encode' in 'D:\workspace\babylonjs\h5_game_project\node_modules\querystring-es3'
 @ ./node_modules/querystring-es3/index.js 4:37-56
 @ ./node_modules/url/url.js
 @ ./node_modules/@pixi/utils/lib/utils.es.js
 @ ./node_modules/pixi.js/lib/pixi.es.js
 @ ./src/index.ts

ERROR in ./node_modules/url/url.js
Module not found: Error: Can't resolve './util' in 'D:\workspace\babylonjs\h5_game_project\node_modules\url'
 @ ./node_modules/url/url.js 25:11-28
 @ ./node_modules/@pixi/utils/lib/utils.es.js
 @ ./node_modules/pixi.js/lib/pixi.es.js
 @ ./src/index.ts

ERROR in ./node_modules/@pixi/polyfill/lib/polyfill.es.js
Module not found: Error: Can't resolve 'object-assign' in 'D:\workspace\babylonjs\h5_game_project\node_modules\@pixi\polyfill\lib'
 @ ./node_modules/@pixi/polyfill/lib/polyfill.es.js 9:0-41 21:20-32
 @ ./node_modules/pixi.js/lib/pixi.es.js
 @ ./src/index.ts`

- **`pixi.js` version**: _e.g. 5.1.5_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. windows 10
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
remove package.lock and node_modules, try `npm i` again?

**Comment by Steven201314** [comment]
> package.lock

Tryed, the same error like this :
`'D:\workspace\babylonjs\h5_game_project\node_modules\querystring-es3'
@ ./node_modules/querystring-es3/index.js 3:33-52
@ ./node_modules/url/url.js
@ ./node_modules/@pixi/utils/lib/utils.es.js
@ ./node_modules/pixi.js/lib/pixi.es.js
@ ./src/index.ts

ERROR in ./node_modules/querystring-es3/index.js
Module not found: Error: Can't resolve './encode' in 'D:\workspace\babylonjs\h5_game_project\node_modules\querystring-es3'
@ ./node_modules/querystring-es3/index.js 4:37-56
@ ./node_modules/url/url.js
@ ./node_modules/@pixi/utils/lib/utils.es.js
@ ./node_modules/pixi.js/lib/pixi.es.js
@ ./src/index.ts

ERROR in ./node_modules/url/url.js
Module not found: Error: Can't resolve './util' in 'D:\workspace\babylonjs\h5_game_project\node_modules\url'
@ ./node_modules/url/url.js 25:11-28
@ ./node_modules/@pixi/utils/lib/utils.es.js
@ ./node_modules/pixi.js/lib/pixi.es.js
@ ./src/index.ts

ERROR in ./node_modules/@pixi/polyfill/lib/polyfill.es.js
Module not found: Error: Can't resolve 'object-assign' in 'D:\workspace\babylonjs\h5_game_project\node_modules@pixi\polyfill\lib'
@ ./node_modules/@pixi/polyfill/lib/polyfill.es.js 9:0-41 21:20-32
@ ./node_modules/pixi.js/lib/pixi.es.js
@ ./src/index.ts``

**Comment by Steven201314** [comment]
> remove package.lock and node_modules, try `npm i` again?

We change the include type by include the files pixi.js and pixi.js.d.ts ,it can work now!

**Comment by bigtimebuddy** [comment]
Could you please provide a repo where we can reproduce this problem? Nothing is coming to mind based you the errors you provided. Please also include details about your tools (VSCode, NPM, TypeScript versions)

**Comment by zs-soft** [comment]
my ide is vscode, with npm and babylonjs. the error asseted when create a pixi.js container.And in pixi.js5.1.5 with babylonjs4.x the babylonjs engine render bug.
![image](https://user-images.githubusercontent.com/45423321/68063993-ca9cde80-fd50-11e9-94a3-28fd6e9935f9.png)
![image](https://user-images.githubusercontent.com/45423321/68063996-d12b5600-fd50-11e9-94ef-44fc504fb5cf.png)

**Comment by Steven201314** [comment]
By testing, when the scene by u3d exported and render pixi.js 5.1.5 ,the model render bug.But, when we use 3dmax for babylon to export the scene,the result is ok.

**Comment by ivanpopelyshev** [comment]
Just in case, there was a problem with babylon+pixi: https://github.com/pixijs/pixi.js/issues/6078

**Comment by Steven201314** [comment]
> Just in case, there was a problem with babylon+pixi: #6078
> 
> Honestly, the best way to make sure everything works - throw out the webpack, and use pixi externally, like you did ;)

But with u3d or 3dmax exported the render not worked . we only use the default babylon-gui  to build our 2d part.
