### ISSUE TITLE
No touchend fired after touchstart

### ISSUE THREAD

**Issue by molst** [pixijs/pixi.js#6191]
Hi!

While testing a menu system on iPhone/iPad I noted that touchend sometimes is not sent by pixi if I tap quickly, releasing the finger rapidly. This is extremely hard, if not impossible, to reproduce on a fast PC, but is easy to repeat on these slower devices.

### Expected Behavior

A touchstart should always be followed by a touchend after releasing the finger from the screen.

### Current Behavior

A touchend is not sent if I tap quickly, releasing the finger rapidly, on a slow device.

### Possible Solution

If this is not a platform/OS problem, the logic around how touchend/mouseup is sent needs to be revised.

### Steps to Reproduce

  1. Create a sprite and attach callbacks for touchstart and touchend altering the tint or alpha of the sprite and add logs to the callbacks.
  1. Load the page on an iPad or iPhone. The slower hardware, the easier to reproduce. It could be easier to reproduce in an app with lots of rendering going on.
  1. Tap lightly and quickly a few times.
  1. You should note that the touchend usually does **not** fire under these circumstances.

### Environment

- **`pixi.js` version**: 5.1.5
- **Browser & Version**: Chrome/Safari (iPad)
- **OS & Version**: iOS12.4.2 (tested on iPad and iPhone)

**Comment by ivanpopelyshev** [comment]
Can you check if native (html) touchend happens before touchstart somehow?

**Comment by molst** [comment]
Sure! I just put a log in InteractionManager.onPointerDown and InteractionManager.onPointerUp (I have a log function that sends the logs back to the server from the iPad/iPhone). I can see that onPointerUp is **always** called, .ie even when the error occurs, so there must be some logic in pixi preventing the event to be fired.

**Comment by molst** [comment]
Unfortunately I don't have a full debug environment set up for the devices..

**Comment by ivanpopelyshev** [comment]
something-something delayedEvents fail @themoonrat

**Comment by molst** [comment]
I sprinkled some more logs around in an effort to give you a better hint of what might be happening. Without any knowledge about how these internals should be working I note that the following happens at a single (light) touch on the button.

When the error does NOT occur (the normal flow):

`EventEmitter.emit` is called **4 times** for the evt string 'touchend'. Only the last time it is preceded by passing the `event.pointerType === 'touch'` clause in `InteractionManager.onPointerComplete`.

When the error DOES occur, the same thing happens with the difference that the emit function is only called **3 times** for 'touchend'.

So, the only difference I can see is that 'emit' is called an extra time when it works.

Without proper debugging env for the devices I haven't yet been able to understand why emit needs to be called that many times.

**Comment by BingBlog** [comment]
I have the same situations when I want to do some TWEEN.Easing effect.
So is there is a solution for this?

**Comment by BingBlog** [comment]
I finally found a solution for my situation. It trigger an "touchendoutside" instead of "touchend".

**Comment by laino** [comment]
@molst 
> `EventEmitter.emit` is called **4 times** for the evt string 'touchend'. Only the last time it is preceded by passing the `event.pointerType === 'touch'` clause in `InteractionManager.onPointerComplete`.
> 
> When the error DOES occur, the same thing happens with the difference that the emit function is only called **3 times** for 'touchend'.

@BingBlog 
> I finally found a solution for my situation. It trigger an "touchendoutside" instead of "touchend".

So basically the fourth event appears to randomly become a ``touchendoutside`` instead of ``touchend`` on iOS - which does sound like an iOS bug.

**Comment by laino** [comment]
So maybe just listening to ``touchendoutside`` as well will fix it?

**Comment by molst** [comment]
Yes, listening also to `touchendoutside` solves my problem. Thanks!
