### ISSUE TITLE
Setting uniform struct in shader

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixi.js#6192]
I have this in my fragment shader:

```GLSL
struct PointLight {
  vec3 color;
};

uniform PointLight pointLight;
```

I'm trying to set this uniform in my pixi shader:

```javascript
this.uniforms["pointLight.color"] = [1, 0, 0]
```

I get the following error message:

Uncaught TypeError: Cannot read property 'color' of undefined
    at eval (eval at generateUniformsSync (pixi.js:17896), <anonymous>:53:32)
    at ShaderSystem.syncUniforms (pixi.js:19896)
    at ShaderSystem.syncUniformGroup (pixi.js:19882)

How can I set my uniform struct?

**Comment by ivanpopelyshev** [comment]
oh right, we dont have this yet :( Lets ask @GoodBoyDigital for workaround.

**Comment by jnsmalm** [comment]
@ivanpopelyshev I created this PR:

https://github.com/pixijs/pixi.js/pull/6298

**Comment by bigtimebuddy** [comment]
PR was merged, closing.
