### ISSUE TITLE
getting base64 assets in the Texture Cache

### ISSUE THREAD

**Issue by NikkiKoole** [pixijs/pixi.js#620]
Hiya I am trying to get base64 data from a jsonp file into the textureCache, 
atm I am doing a sprite =  PIXI.Sprite.fromImage(data.under, true)
where data is the jsop file and data.under is the part where the base64 string is at.

this works wonderfully, but I'd like a way of putting that texture in the cache, preferablu under a name like JSONPURL+'under', 

because I have the feeling these base64 strings are slowing me down when I want to draw that asset multiple times

how does that work?

**Comment by blurymind** [comment]
how do we get the base64 out of a texture?

**Comment by englercj** [comment]
Please open a new issue with your question.
