### ISSUE TITLE
TextMetrics incorrect calculations using breakWords and Emojis

### ISSUE THREAD

**Issue by Teraqz** [pixijs/pixi.js#6201]
Using:
`var characters = token.split('');`
in TextMetrics.wordWrap will return incorrect character array and calculated width, when you have string of emoji like "🤪🤪"

### Current Behavior
`"🤪🤪".split("") => (4) ["�", "�", "�", "�"]`
### Possible Solution
Using ES6 i managed to get it right: 
`[..."🤪🤪"] => (2) ["🤪", "🤪"]`

### Environment

pixi.js version: e.g. 5.1.3
Browser & Version: e.g. ios13.1 safari

**Comment by ivanpopelyshev** [comment]
Good carch!

**Comment by Teraqz** [comment]
@ivanpopelyshev is there any chance you guys could integrate this lib https://github.com/orling/grapheme-splitter as a plugin or extension to TextMetrics? 
It would be very handy and it's actually make sense if you are willing to use PIXI with more complicated Text, and if not, just don't use this plugin.

**Comment by bigtimebuddy** [comment]
I don't think we should integrate this dependency because it's rather heavy, but we should allow for users to plugin/replace the string-splitting functionality themselves. For users that need emojis, we should support a drop-in replacement.

**Comment by Teraqz** [comment]
@bigtimebuddy yeah, no need for dependency there, just an option to allow to plugin/replace this split function
