### ISSUE TITLE
Renderer#render is not reentrant and does not revert state

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6203]
If an display-object's `render` method needs to render something onto a `RenderTexture`, then it cannot use `Renderer#render` without caveats. This is because that method fails to:

1. Flush the current object-renderer (in the batch system). It merely starts the current object-renderer, which is not enough because we are rendering to the render-texture, while the object-renderer needs to be flushed onto the screen (or previous render-texture).

2. Revert the current render-texture to the previous (or to the screen). The `render` method will bind the `renderTexture` given; however, it will not unbind it. This causes problems because any display-object's being rendered afterward are rendered onto the render-texture instead (remember, other object's will be rendered using their own `render` method.)

I want to know if you would be open to making `PIXI.Renderer#render` reentrant by solving the above two problems.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/Renderer.js#L378

`This causes problems because any display-object's being rendered afterward are rendered onto the render-texture instead`

We have no guarantees about current rendertexture, current filterstate and anything else out of `render` function. 

If you do calls outside, make sure to `renderer.renderTexture.bind(myRt)`. Also, current framebuffer and texture location can be changed from outside of `render`, for example, by `prepare` plugin, so we really cant guarantee that the object draw outside `render` will happen on particular framebuffer.

Also we wont return renderTexture because its extra framebuffer bind call and we want to make minimal code in SpectorJS listings :)

**Comment by ivanpopelyshev** [comment]
However, many times I encountered issues when someone reported one bug and it was actually another. Please post your failed demo here.

**Comment by SukantPal** [comment]
@ivanpopelyshev I have bypassed that problem by manually flushing the batch renderer and then unbinding the current render-texture.

**Comment by SukantPal** [comment]
```js
renderer.batch.flush()
renderer.render(this, renderTexture)
renderer.renderTexture.bind()
```

This is the "bypass". If I only put the middle line there, then some stuff disappears (apparently anything after the current display-object).

**Comment by SukantPal** [comment]
> https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/Renderer.js#L378
> 
> > This causes problems because any display-object's being rendered afterward are rendered onto the render-texture instead
> 
> We have no guarantees about current rendertexture, current filterstate and anything else out of `render` function.
> 
> If you do calls outside, make sure to `renderer.renderTexture.bind(myRt)`. Also, current framebuffer and texture location can be changed from outside of `render`, for example, by `prepare` plugin, so we really cant guarantee that the object draw outside `render` will happen on particular framebuffer.
> 
> Also we wont return renderTexture because its extra framebuffer bind call and we want to make minimal code in SpectorJS listings :)

The thing is that sometimes we expect the renderer's state to not change after rendering. For example, if I render to a render-texture, I don't expect later `render` calls to render onto that render-texture; rather they should render onto the screen.

We could make another `safeRender` method that flushes the previous state and preserves it too.

**Comment by laino** [comment]
This is a big one. It would render textures so much more user friendly. Right now stuff like ``cacheAsBitmap`` (buggy as hell with filters) and ``pixi-layers`` have to use a myriad of hacks just to work halfway properly. Most of these hacks are related to saving and restoring state around ``.render``.

I just recently spent a few days implementing a better ``cacheAsBitmap``, and most of it was spent trying to not break filters.

I haven't cleaned this up yet, but unlike cacheAsBitmap it plays nicely with filters and some scaling situations.

The main fixes are modifying the filter stack before and after render (stolen from pixi-layers) and also setting ``renderTexture.filterFrame``, which makes filters use the correct coordinates when your sourceFrame has ``x|y != 0`` (``cacheAsBitmap`` is missing both of these right now). But the list of things that need to be taken care of is confusing, way too long, and undocumented in any case.

Here is the code (TypeScript) for now. I will update this post when I get around to cleaning it up in the future:

```ts

import * as pixi from 'pixi.js';

const originalBounds = pixi.Container.prototype.calculateBounds;

// TODO: this might miss filter padding on parent containers that still apply to this one
pixi.Container.prototype.calculateBounds = function() {
    originalBounds.call(this);

    if (this.filters) {
        for (const filter of this.filters) {
            this._bounds.pad(filter.padding);
        }
    }
};

interface RenderingContext {
    renderer: pixi.Renderer;
    renderTexture: pixi.RenderTexture;
    sourceFrame: pixi.Rectangle;
    destinationFrame: pixi.Rectangle;
    transform: pixi.Matrix;
}

const tmpParent = new pixi.Container();

function STORE_RENDERING_CONTEXT(renderer: pixi.Renderer): RenderingContext {
    renderer.batch.flush();

    let transform = renderer.projection.transform;

    if (transform) {
        transform = transform.clone();
    }

    return {
        renderer,
        renderTexture: renderer.renderTexture.current,
        sourceFrame: renderer.renderTexture.sourceFrame.clone(),
        destinationFrame: renderer.renderTexture.destinationFrame.clone(),
        transform
    };
}

function RESTORE_RENDERING_CONTEXT(context: RenderingContext) {
    context.renderer.projection.transform = context.transform;
    context.renderer.renderTexture.bind(context.renderTexture, context.sourceFrame, context.destinationFrame);

    const filterStack = context.renderer.filter.defaultFilterStack;

    if (filterStack.length > 1) {
        filterStack[filterStack.length - 1].renderTexture = context.renderer.renderTexture.current;
    }
}

export class CacheContainer extends pixi.Container {
    private cacheSprite: pixi.Sprite;
    private textureCacheId: string;
    private cacheEnabled = false;

    public blendMode: number = pixi.BLEND_MODES.NORMAL;

    public constructor() {
        super();
    }

    public destroy() {
        super.destroy();

        this.destroySprite();
    }

    public updateCache(enabled?: boolean) {
        this.destroySprite();

        if (enabled !== null && enabled !== undefined) {
            this.cacheEnabled = enabled;
        }
    }

    public render(renderer: pixi.Renderer) {
        if (!this.visible || this.worldAlpha <= 0 || !this.renderable) {
            return;
        }

        if (!this.cacheEnabled) {
            return super.render(renderer);
        }

        (this as any)._boundsID++;

        this.createCacheSprite(renderer);

        this.cacheSprite.transform.updateTransform(this.transform);
        this.cacheSprite.alpha = this.worldAlpha;
        this.cacheSprite.blendMode = this.blendMode;
        (this.cacheSprite as any).worldAlpha = this.worldAlpha;

        this.cacheSprite.render(renderer);
    }

    private createCacheSprite(renderer: pixi.Renderer) {
        if (this.cacheSprite) {
            return;
        }

        const oldContext = STORE_RENDERING_CONTEXT(renderer);

        const {alpha} = this;
        const worldTransform = this.transform.worldTransform.clone();

        this.alpha = 1;

        tmpParent.transform.setFromMatrix(this.parent.transform.worldTransform);
        const oldParent = this.parent;
        (this as any).parent = tmpParent;

        this.updateTransform();

        const bounds = this.getBounds(false);
        bounds.ceil(pixi.settings.RESOLUTION);
        const renderTexture = pixi.RenderTexture.create({
            width: bounds.width,
            height: bounds.height
        });
        (renderTexture as any).filterFrame = bounds;

        this.textureCacheId = "cacheContainer_" + (pixi.utils.uid());

        pixi.BaseTexture.addToCache(renderTexture.baseTexture, this.textureCacheId);
        pixi.Texture.addToCache(renderTexture, this.textureCacheId);

        renderer.renderTexture.bind(renderTexture, bounds);
        const filterStack = renderer.filter.defaultFilterStack;
        if (filterStack.length > 1) {
            filterStack[filterStack.length - 1].renderTexture = renderer.renderTexture.current;
        }

        //(renderer as any)._activeLayer = null;

        renderer.renderTexture.clear();

        super.render(renderer);

        renderer.batch.flush();

        renderTexture.baseTexture.update();

        worldTransform.translate(-bounds.x, -bounds.y);

        this.cacheSprite = new pixi.Sprite(renderTexture);
        this.cacheSprite.transform.setFromMatrix(worldTransform.invert());
        this.cacheSprite.roundPixels = true;

        RESTORE_RENDERING_CONTEXT(oldContext);

        this.alpha = alpha;
        (this as any).parent = oldParent;

        this.updateTransform();
    }

    private destroySprite() {
        if (!this.cacheSprite) {
            return;
        }

        pixi.BaseTexture.removeFromCache(this.textureCacheId);
        pixi.Texture.removeFromCache(this.textureCacheId);

        this.cacheSprite.texture.destroy(true);
        this.cacheSprite = null;
    }
}

export default CacheContainer;
```

**Comment by SukantPal** [comment]
@ivanpopelyshev Did you consider this input?

**Comment by eXponenta** [comment]
We will change it when Core Package will start migrate to TS, because there is some architecture problems on renderer.

**Comment by SukantPal** [comment]
@eXponenta Do you have a specific method to add this in your mind? Or does this look okay? If you want, you could assign yourself!
