### ISSUE TITLE
Update NineSlicePlane texture source to resource.source?

### ISSUE THREAD

**Issue by wss534857356** [pixijs/pixi.js#6204]
https://github.com/pixijs/pixi.js/blob/b4d2a40e7a2fdc63aa10006ea05c4366fea97597/packages/canvas/canvas-mesh/src/NineSlicePlane.js#L57

**Comment by bigtimebuddy** [comment]
Yup!

**Comment by bigtimebuddy** [comment]
https://jsfiddle.net/bigtimebuddy/2zbtowq7/1/

Throws deprecation warning, will fix.

**Comment by wss534857356** [comment]
Thanks!

**Comment by bigtimebuddy** [comment]
no problem, thanks for finding that.
