### ISSUE TITLE
Custom drag algo miscalculates first touch coordinates only in iOS.

### ISSUE THREAD

**Issue by outisfun** [pixijs/pixi.js#6209]
Hello,

I am building a demo based on [this cool example](https://experiments.withgoogle.com/drag-and-glitch).
Live example [here](https://interactive-development.hsnb.io/xpr/smudge-touch/index.html).

I rewrote it in PIXI v5, but an issue that's also present in the original, persists.
The drag and smudge feature works without problems on Android and on desktop, but on IOS, on the very first touch and drag, it takes not the pixels under the brush (finger), but in the top left corner of the screen. On each subsequent touch in a different spot, it seems to carry a "snapshot" of its previous position.

My guess is, this might have something to do with the vTextureCoord it receives, but I don't have much experience with WebGL, so that might be completely wrong.

vTextureCoord is calculated in the vertex shader like this:
`{ return aVertexPosition * (outputFrame.zw * inputSize.zw); }`

Screenshots on first touch and drag:
[iOS](https://interactive-development.hsnb.io/xpr/smudge-touch/_ios.jpg)
[Android](https://interactive-development.hsnb.io/xpr/smudge-touch/_android.jpg)

Screenshots on second touch and drag:
[iOS](https://interactive-development.hsnb.io/xpr/smudge-touch/_ios2.jpg)
[Android](https://interactive-development.hsnb.io/xpr/smudge-touch/_android2.jpg)

Here is the fragment shader code:
```glsl
    precision highp float;
    varying vec2 vTextureCoord;
    uniform sampler2D uSampler;

    uniform vec2 brushPosition;
    uniform vec2 brushDrag;
    uniform float resx;
    uniform float resy;
    uniform float brushStrength;
    uniform float brushRadius;
    uniform float brushInverse;
    uniform float brushOpposite;

    void main(void) {
      vec2 uv = vTextureCoord.xy;
      vec2 pixelUnit = vec2(1.0/resx, 1.0/resy);
      vec2 res = vec2(resx, resy);
      vec2 center = uv - (brushPosition / res); 
      center.x *= resx/resy;
      float radius = brushRadius/resy;
      float dist = smoothstep(0.0, radius, length(center));
      dist = mix(step(0.999, dist), dist, 1.0);
      dist = mix(1.0 - dist, dist, brushInverse);
      dist = mix(dist, dist * -1., brushOpposite);
      uv = uv - brushDrag * dist * pixelUnit * brushStrength;

      vec4 color = texture2D(uSampler, uv);
      color = mix(color, color * 1.0, dist * clamp(brushStrength, 0.0, 1.0));

      gl_FragColor = color;
  }
```

... and the uniforms brushPosition and brushDrag (which are the only ones that change dynamically) are set in the ticker function, before the app renders.

Thanks a lot!

**Comment by ivanpopelyshev** [comment]
Yes, I can help with that but only in Sunday, I'm attending JS Conference. 

Very good report, thank you!

**Comment by outisfun** [comment]
@ivanpopelyshev , that would be awesome, thank you!

**Comment by outisfun** [comment]
@ivanpopelyshev , did you by any chance have an opportunity to check the issue? I still can't seem to solve it, so whenever you have time, it would be wonderful if you could look at it, or at least give me a suggestion about what to look at. Thank you!

**Comment by ivanpopelyshev** [comment]
I'll check it tomorrow or the day after :)

**Comment by ivanpopelyshev** [comment]
Can you post it in codepen or jsfiddle, somewhere where i can edit it?

**Comment by outisfun** [comment]
Yes, I'll do it first thing tomorrow morning, I'm traveling this weekend.
Thank you!

**Comment by outisfun** [comment]
Here's a quick pen:
https://codepen.io/outis/pen/oNNJowo

I've only tried to include the stuff that I think is relevant (the PIXI-related functions and the shaders), but if something is unclear or missing, let me know. Thank you and have a great week!

**Comment by outisfun** [comment]
Here's a quick and dirty pen:
https://codepen.io/outis/pen/xxxmPNY

I tried to add only the stuff I find relevant, but if anything is unclear or missing, please let me know and I'll add it. Thank you! And have a great week.

**Comment by ivanpopelyshev** [comment]
I don't understand what's going on yet, I need to make it even more simpler. I'll try to borrow iOS phone , that way i'll be able to reduce example to something tiny, maybe just two "render" operations with even simpler shader.

**Comment by outisfun** [comment]
Thank you! I would be happy to simplify it even further, just let me know which parts you want gone or highlighted. It's part of a larger demo so there's a few things that are not relevant, but the PIXI stuff is all in the pen.

And yes, it happens on both Safari and Chrome.

**Comment by ivanpopelyshev** [comment]
No, your code is good, but I need to cut down number of webgl operations seriously.

It'll be a large number of reductions, and each time i'll check if bug is gone or not. In the end it'll be very small. If bug persists, I will make pure webgl version of it too - that's how its usually goes with low-level bugs.

**Comment by ivanpopelyshev** [comment]
There's also very small chance that its a bug that also affecting security, because manipulation with Framebuffers is tricky.

**Comment by ivanpopelyshev** [comment]
Im debugging interaction:

https://codepen.io/ivanpopelyshev/pen/rNNPyyz

```js
    if (this.isDragging && !this.failedDrag) {
      if (Math.abs(this.dragDelta.x) > 100 ||                      Math.abs(this.dragDelta.x) > 100) {
        this.failedDrag = true;
        const debugSprite = new   PIXI.Sprite(PIXI.Texture.WHITE);
        debugSprite.scale.set(10);
        this.app.stage.addChild(debugSprite);
      }
```

**Comment by outisfun** [comment]
Wow, that's a wonderful catch - so if you keep your finger a bit longer
before you drag, it actually works correctly, at least for me.
The glitch seems to happen if you drag too quickly.

**Comment by outisfun** [comment]
Okay, thank you, that's a wonderful catch - I will try resolving it from within my code. It shouldn't be pixi-viewport, because the original code doesn't use it, and it has the same issue.

If the quick drag is the issue, then its absolute value can be clamped for iOS - at least that's what comes to mind first, I'll play around a bit, interactions are much easier to debug. Thank you, that was very helpful!

**Comment by ivanpopelyshev** [comment]
Its not quick drag, I made that code to see if FIRST touch in iOS can force it because previous brushPosition is (0,0). That means in iOS in first touch drag is going from point (0,0) to (inputX, inputY) - that's what i caught.

In general fast drag is ok, and you can fix it with doing several flip-flops along the path. In this case its different - its "first coordinate" bug.
