### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by arahlf** [pixijs/pixi.js#621]
On a retina display, shapes drawn with PIXI look blurry.  I tried making a [forum post](http://www.html5gamedevs.com/topic/4234-lines-look-blurry-on-retina-display/) about this but it didn't really go anywhere.  I looked into this further, and setup some side by side examples of normal canvas vs. PIXI to help better demonstrate the problem.  Here's a [fiddle](http://jsfiddle.net/bxNVX/)

And a [screenshot](https://f.cloud.github.com/assets/865624/2304330/10411a3c-a217-11e3-9327-42d4398cf0a9.png)

I'm not sure what the deal is w/ the weird black background on my attempt at scaling the PIXI canvas context... I might've done it incorrectly or something else in the framework is getting in the way or got messed up by modifying the context.

It seems like PIXI could add built in retina support by checking `devicePixelRatio` and then adjusting the canvas + context properties accordingly, but I'm not sure what other implications that might have.

**Comment by PierBover** [comment]
I'm having an issue with a retina macbook pro.

I'm not using `{resolution:2}`.

The stage width returns the real retina pixels. In my case it's `2540` pixels. The textures are rendered at twice their size and their widths are not in real 1:1 retina pixels either. So a 300 x 200 image occupies 600 x 400 retina pixels, but the width returns 300.

Is this expected behaviour?

**Comment by englercj** [comment]
@PierBover Yes, the height/width of the object hasn't actually changed. It is just rendered at a different resolution.

**Comment by PierBover** [comment]
@englercj but how come there are dimensions in real pixels and doubled pixels mixed?

**Comment by brenwell** [comment]
Hey guys, am I doing something wrong here. If I make my CanvasRenderer's resolution 2 for a retina display it makes my canvas twice the size and my `@x2` images four times the size.

```coffeescript
    @scale = window.devicePixelRatio
    width = 960/@scale
    height = 556/@scale

    renderer = new (PIXI.CanvasRenderer)(width, height,{resolution:@scale})
    container = document.getElementById 'container'
    container.appendChild renderer.view
```

StackOverflow Question
http://stackoverflow.com/questions/29142342/pixi-js-retina-display-canvas-is-doubled-in-size

**Comment by brenwell** [comment]
In this issue and in this blog post http://www.goodboydigital.com/pixi-js-v2-fastest-2d-webgl-renderer/ the retina images are mentioned to need either a **@2x** or a **@x2** before the extension. I am assuming the correct is **@2x**. Is this correct?

**Comment by adireddy** [comment]
@2x is correct. It can be a folder name or appended to the image name.

`assets/@2x/image.png
or
assets/image@2x.png`

**Comment by brenwell** [comment]
@Adireddy thanks. That's half the battle. Any idea why my canvas is scaled rather than the resolution increasing?

**Comment by dyleeo** [comment]
Has anyone had any issues with retina display and pixi filters? I have rollover events on an item, but when rolled over, the item scales down and position shifts down.

**Comment by Elyx0** [comment]
Same problem here for retina, any usage of resolution: 2, makes some PIXI.Text anchor positioning wrong. Rescaling back the canvas in CSS doesn't help much. I had to set resolution to 1, double my Text  font size, then scale it to half.  

And Even with that the text still not look smooth.

**Comment by JiDW** [comment]
Hi Elyx0, you may try my text plugin for mobile available here : https://github.com/JiDW/pixi-cocoontext

Does it fix your issues ?

**Comment by Elyx0** [comment]
Hi @JiDW , I finally fixed it. I'm using bare PIXI.js so no Cocoon for me, my view canvas wasn't properly setup. Thx

**Comment by tobireif** [comment]
@GillesVermeulen 

I'm considering to support High DPI devices in my project, so I'm wondering:

> The canvas is scaled, but the hit areas are not.

Has this been solved in PixiJS? (eg in a later/recent version)

**Comment by GillesVermeulen** [comment]
Hey @tobireif, I do think so yes. Haven't had the problem for a long time, but that's with Pixi v2. I don't think it's an issue with newer version either.

**Comment by tobireif** [comment]
@GillesVermeulen Sounds good! Thanks!

**Comment by as-f** [comment]
A CSS method that worked for me using canvas (without pixi.js)
`canvas {
    image-rendering: optimizeSpeed;            
    image-rendering: -moz-crisp-edges;         
    image-rendering: -o-crisp-edges;           
    image-rendering: -webkit-optimize-contrast;
    image-rendering: optimize-contrast;        
    image-rendering: crisp-edges;              
    image-rendering: pixelated;                
    -ms-interpolation-mode: nearest-neighbor;  
}`
Just in case this can help anyone.

**Comment by romaincazier** [comment]
Hi !

I'm having an issue with my last project : http://romaincazier.com/davatars/

I can't get the right pixel resolution on my objects... I don't know if it's about the renderer or the graphics I generated the textures from, but in both case I added the window.devicePixelRatio but it doesn't seem to have any influence.
