### ISSUE TITLE
"WebGL renderer unsupported in this browser" in Chrome on latest Catalina

### ISSUE THREAD

**Issue by ZachSaucier** [pixijs/pixi.js#6213]
### Expected Behavior
WebGL renderer to be used by pixi.

### Current Behavior
WebGL Renderer not available to pixi.

I'm getting the following error when loading from the CDN, both on CodePen and locally:
> Renderer.js:49 Uncaught Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.

The [pixi v5 demos](https://pixijs.io/examples/#/demos-basic/container.js) run using pixi 5.2.0 but with the Canvas renderer. 

I have double checked to make sure all of my drivers are up to date and that GPU processing is turned on. Other WebGL projects not using PIXI and they work fine. https://get.webgl.org/ works fine. It works fine in Firefox.

### Environment
I have a pretty new Macbook.
- **`pixi.js` version**:  5.1.5
- **Browser & Version**:  Chrome 78.0.3904.87 (Official Build) (64-bit)
- **OS & Version**: macOS Catalina 10.15.1 (19B88) 
- **Running Example**: https://codepen.io/GreenSock/pen/Rwwymrd?editors=0010

**Comment by bigtimebuddy** [comment]
I was seeing something similar in Brave browser yesterday. Created this example with  `isWebGLSupported`. See: https://codepen.io/bigtimebuddy/pen/Jjjvqqz?editors=0011

For me it was tracked down to this line:

```js
const success = !!(gl && gl.getContextAttributes().stencil);
```

Throws this error:
 > Cannot read property 'stencil' of null"

@ZachSaucier are you getting something similar?

**Comment by ZachSaucier** [comment]
Yep, commenting out `stencil: true,` in that demo causes it to say that WebGL is not supported. Thanks for doing the hard work of debugging for me 😉

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev where are we loosening the stencil requirement?

**Comment by ZachSaucier** [comment]
If possible, it'd be nice to get pixi working in Chrome on Catalina by Monday because we have a release happening then. 

Is there some code I can add as a work-around for now to disabled the stencil? Something like `PIXI.Renderer(stencil: true)`?

**Comment by bigtimebuddy** [comment]
For a workaround, you can override this function and replace `isWebGLSupported()` with your own function that doesn't consider `stencil`
```js
PIXI.Renderer.create = function create (options) {
    if (isWebGLSupported()) {
        return new PIXI.Renderer(options);
    }
    throw new Error('WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.');
};
```

**Comment by ZachSaucier** [comment]
Thanks, I worked around it by [detecting WebGL differently](https://stackoverflow.com/a/11871182/2065702) inside of that function.

**Comment by ivanpopelyshev** [comment]
Yes, I can work on stencil stuff , because we made that refactoring and it wont make our code worse.

**Comment by ivanpopelyshev** [comment]
Also, can someone please go to their bugtracker and fish for information? We need a person in charge of contacting apple with WTF webgl demos :)

**Comment by irongaze** [comment]
+1 on this issue.  Oddly, in our case we worked properly in Firefox, got the error only in Chrome on the same box.  Chrome-specific issue, perhaps?

**Comment by jacklynlxq** [comment]
> For a workaround, you can override this function and replace `isWebGLSupported()` with your own function that doesn't consider `stencil`
> 
> ```js
> PIXI.Renderer.create = function create (options) {
>     if (isWebGLSupported()) {
>         return new PIXI.Renderer(options);
>     }
>     throw new Error('WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.');
> };
> ```

Sorry if it's a stupid question, but how should I override it? When I tried to override it by defining it again it says 
> Property 'create' does not exist on type 'typeof Renderer'.
