### ISSUE TITLE
I want to use pixi.js but I don't understand the licence

### ISSUE THREAD

**Issue by signgitgit** [pixijs/pixi.js#6216]
Hello,

Please I want to use some animations in my web application using pixi.js but I don't understand the licence of the library exactly this point:

"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, ......... "

Must I include this copyright notice and the permission notice in my web application?

Thanks in advance.

**Comment by ivanpopelyshev** [comment]
https://tldrlegal.com/license/mit-license

Look in pixijs build: http://pixijs.download/dev/pixi.js

```js
/*
 * pixi.js is licensed under the MIT License.
 * http://www.opensource.org/licenses/mit-license
 */
```

That's all. If you modify it, rebuild it e.t.c. you just dont remove this notice.

**Comment by bigtimebuddy** [comment]
Closing, as this is answered.
