### ISSUE TITLE
particle container's sprite not clickable

### ISSUE THREAD

**Issue by novaknole** [pixijs/pixi.js#6218]
### Environment

 **`pixi.js` version**:  4.8.8
 **Browser & Version**: Chrome 67
 **OS & Version**: Ubuntu 18.04

Hi, I am using ParticleContainer with the length of 20,000. I am creating sprites and add them as children to this particle container. 

1) I want to have click event on sprite object. Does it work for ParticleContainer, if so, why doesn't it work for me? later I saw this , is this still true and sprites can't be clickable for particle container? 
https://www.html5gamedevs.com/topic/35348-pixiparticlesparticlecontainer-children-particle-hitareas-dont-seem-to-follow-the-particles-as-they-move/

2) I am using map and putting spirtes onto Leaflet map. I can't really figure out what really makes it a little big laggy, but somehow a little bit of bad performance comes from interactive setting to true.

I have 20,000 markers. What performance would you suggest if particlecontainer is no option?

I need clicking marker, hovering event on marker to show some data, changing sprite location.

**Comment by eXponenta** [comment]
Because it is specifically container for large count of elements with caching algorithms for preventing bounds recalculation.

Performance will he dropped when input will enabled on it.

Use regular PIXI.Container if you need capture events from particles, or check point hit for particles manually.

**Comment by novaknole** [comment]
how do I check manually? I should add map event and when clicked i should see if there's a marker there?

also can sprite be moved in particle container in real time?

**Comment by eXponenta** [comment]
1. Use binary search for reducing iteration over particles. 
3. Particles Container is specifically container for indentical elements, without interaction, alpha blending, tinting, scaling, anchors, position changing by default.

https://pixijs.download/dev/docs/PIXI.ParticleContainer.html

**Comment by novaknole** [comment]
I don't get your comment fully.


1) So, if I use particle container, all elements should be the same? I can't use different textures?
if tinting works for each one of them separately, why not texture?

2) can it be moved?

**Comment by eXponenta** [comment]
There are differences between PIXI.Texture and real image.
Textures can be different when it is from one image (spritesheet) - is same BaseTexture.

2. Check documentation and set special flag for enabling position update. But position update enabled by default.
