### ISSUE TITLE
Memory leak for sprites (I guess)

### ISSUE THREAD

**Issue by novaknole** [pixijs/pixi.js#6219]
### Environment

- **`pixi.js` version**:4.8.8
- **Browser & Version**: Chrome 67_
- **OS & Version**:Ubuntu 18.04_

I am using mainContainer and childContainer. I add sprites to childrenContainer. I add childrenContainer to mainContainer. and I render mainContainer.  When adding sprites to childrenContainer, I create empty array, push sprites into this array and also add them as children to childrenContainer.

Now, when some event for my app gets thrown, I receive new data which means I have to remove every sprite on the screen and add new ones. What I do is

```
childrenContainer.removeChildren(0)
mainContainer.removeChild(childrenContainer);
renderer.render(mainContainer);
mainContainer.addChild(childrenContainer)
renderer.render(mainContainer)
markerSprites = []; //when drawing new sprites, i equal this to empty array, so that this array no more watches sprites which means(sprites that were in the array before should get removed).
```

```
data.forEach(item =>{
   var sprite = new Pixi.Sprite(texture);
   childrenContainer.addChild(sprite)
  markerSprites.push(sprite);
})
renderer.render(mainContainer);
```

So, even though i removed children from childrenContainer and make the array which had sprites to empty one, it still looks like old sprites are remaining in the heap and each time new data comes, my ram gets bigger and bigger. 

What else should I do? Than you.

**Comment by JetLua** [comment]
You can try the `destroy` method.

**Comment by novaknole** [comment]
On what? sprite directly? that's what I didn't want(looping through sprites array and destroy each one of them separately). Is this what you're referring?

**Comment by eXponenta** [comment]
https://pixijs.download/dev/docs/PIXI.Container.html#destroy

**Comment by novaknole** [comment]
@eXponenta 

So, As it says, I can't use the container anymore after I destroy it. 

1) Does this mean I can reinitalize it? like in my code

               childrenCont.removeChildren(0)
              pixiContainer.removeChild(childrenCont);
                childrenCont.destroy({
                 children: true,
                 texture: true,
                 baseTexture: true
               })
              childrenCont = new PIXI.Container() //I initialize it again.
              renderer.render(pixiContainer);

2) Why childrenCont.removeChildren(0) doesn't take care of memory leak removal?

Thank you.

**Comment by ivanpopelyshev** [comment]
Did you look in heap dump? Its easy to make and look how exactly random instances of Sprites are hanging

**Comment by novaknole** [comment]
I did, I am just curious how the above code I posted should work and what should delete what. 

A little explanation would be great.
