### ISSUE TITLE
Issue with drawPolygon / (moveTo; lineTo) - different version, different result - [v4.X-v5.X]

### ISSUE THREAD

**Issue by aculhd** [pixijs/pixi.js#6220]
### Expected Behavior
![image](https://user-images.githubusercontent.com/12642760/68700240-d3798580-0584-11ea-9e3f-036476e59b1b.png)
... not filled Polygon.

### Current Behavior
![image](https://user-images.githubusercontent.com/12642760/68700330-04f25100-0585-11ea-9e5d-1725cea22d60.png)
**v4.8.8**

![image](https://user-images.githubusercontent.com/12642760/68700396-22271f80-0585-11ea-9d42-bf356298a777.png)
**v.5.2.0**

In Pixi v4.X the Triangle is not filled -> that's correct, in v5.X the Triangle is filled.
... same test-source - difference result with PIXI.JS v4.X and v5.X.

Used method: "drawPolygon", with the "lineTo" /" moveTo" methods their are simular results.

The problem also appears with equal generated Triangles in my application (**PIXI v4.8,8**) ,  but I couldn't reproduced that in the sandbox for now.

### Steps to Reproduce

1. Demo-Sandbox - with "drawPolygon":
https://www.pixiplayground.com/#/edit/WqEYQSrt~kO6B1neduGw5

2. Demo-Sandbox - with "lineTo" / "moveTo":
https://www.pixiplayground.com/#/edit/NHw7ElFPcyx_nXYilDPbi

    ---> Switching Version between Pixi v4.8.8 and v5.2.0.

### Conclusion

It chould be a backport from Issue https://github.com/pixijs/pixi.js/pull/5735.
In case it is an bug, so please fix this Issue not only in v5.X **also in v4.X**. 👍 

Greeting form Germany! :-)

EDIT: 
The problem also appears between PIXI.js "v5.0.0-alpha" and "v5.0.0-alpha.2", so the Issue have to exits between this versions?!

**Comment by ivanpopelyshev** [comment]
No guarantees about very close points. You have to filter your input, otherwise line mesher will not understand it.

**Comment by aculhd** [comment]
So when I multiply the input data with an factor of 1000 the points are not close each other, but the problem still exists  --> https://www.pixiplayground.com/#/edit/rW5mUl9ITdtxeih47_hBy

Is their any workaround for (not filled) Trianlges in PIXI 4.X?

**Comment by ivanpopelyshev** [comment]
Its not a problem, its a limitation of triangulation algorithm that we use by default, mapbox-earcut and our buildLine implementation. Workaround - do filtering, and look what exactly do you pass in pixi in this case. For example, you can round all points to 0.05 (1/20) then remove equal adjastent points.

**Comment by aculhd** [comment]
I have filter my input to an roundness of ~0.05 (1/20) - the behaviour still exists:
https://www.pixiplayground.com/#/edit/CEDHDqXhoO8IDu80GIXuw

**Comment by ivanpopelyshev** [comment]
I've added `lastX !== pointX` and it works in v5: https://www.pixiplayground.com/#/edit/0d2bHuYAMabi3_CIlaTkW

**Comment by ivanpopelyshev** [comment]
Ugh, i dont understand your example, what those number mean? Are you trying to make a hole inside triangle or what?

**Comment by aculhd** [comment]
Your example does not work in 4.X / 5.X. You have added the "forceCanvas"-flag?! - on Canvas-Rendering it is working, in WebGL-Mode not.

I would like to draw an not filled Triangle - same input data as in the issue description.

**Comment by aculhd** [comment]
@ivanpopelyshev Is their any solution - is the bug already fixed?

**Comment by ivanpopelyshev** [comment]
Yes, for WebGL, use `tess` instead of mapbox. Its possible in v5 to change triangulator, @eXponenta uses it.

As for why 4.8.8 forceCanvas differently from 5.2.0 - new version actually re-orders vertices based on area and that can affect winding-related problems.

I'd like to point out that due to diffuculty of the problem, PixiJS team does not guarantee work of Graphics on all non-simple shapes, especially if you dont use beginHole() and endHole() to mart them. Historically, 2d path is collection of small paths, but in pixi its just 1 path, and we cant distinguish unions or holes.

I'm working on my own implementaion of Graphics that works with that kind of paths, its very hard.

**Comment by eXponenta** [comment]
@aculhd 
So, tess2 example with windings rules.
Please, don't change example, create copy before.

https://www.pixiplayground.com/#/edit/NWa_z1hMuF92Dwmyb3AEl

**Comment by aculhd** [comment]
@eXponenta thank for you example - how can I access the "buildPoly" in my projects.
There is only PIXI.graphicsUtils**.**
BATCH_POOL / DRAW_CALL_POOL / FILL_COMMANDS

**Comment by eXponenta** [comment]
@aculhd Same way, if types not exist this does not mean that fields can't exist too ;).

**Comment by aculhd** [comment]
@eXponenta 
jup, that does not mean that... :)

... now the following error shown up:
![image](https://user-images.githubusercontent.com/12642760/74662718-badbc580-519a-11ea-8d30-c467f5c67524.png)

I add the element in the Pixi loader, but the Graphicelement is stacked in containers - so can I use the TessGraphic without Pixi loader?
