### ISSUE TITLE
Performance Ideas(Really Need Help)

### ISSUE THREAD

**Issue by novaknole** [pixijs/pixi.js#6221]
### Environment

- **`pixi.js` version**: _e.g. 4.8.8
- **Browser & Version**: Chrome 67_
- **OS & Version**: Ubuntu 18.04_
- **Running Example**: _url_

I need performance ideas so, I hope you can advise me more. I will list my questions as I can.

I am using leaflet map and pixi.js. The plugin I am using is leaflet-pixioverlay. The thing is It's just pixi.  I use 16,000 markers texture with sprites. each one of them is interactive/buttonMode for click event and also they have tint. The thing is on the map, it's kind of laggy for my pc. when I want to move on the map, it lags. For 5,000 markers, It's not laggy.  

1) Do you think this is the normal behaviour? I want it to be so fast that user can never say it lags sometimes. What do you think?

2) Is there anything I can do for performance optimization? as I need click events, I can't use ParticleContainer.  Any other ideas?

If you need to know more, let me know and I will quickly provide more.

Thanks.

**Comment by ivanpopelyshev** [comment]
Yes, according to the https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/TreeSearch.js its normal behaviour.

You have to make better algo than that. Then hack it to `renderer.plugins.interaction` object.

I call it "100k bunnies problem". PixiJS covers many things but if you add 10k-100k objects, you have to modify it with your high-level algorithms that suit your case. There's no way we can satisfy all users, so you have to actually code stuff to remove bottlenecks ;)

For example, if we add chunks support in this - it can affect all the "pointerover" thing we are trying to add to support more events. Open-source development in team is not easy :(

**Comment by ivanpopelyshev** [comment]
In 4.8.8 TreeSearch was in "processInteractive" function of InteractionManager, same location - `renderer.plugins.interaction`. I remember that it had different handling of hitArea - maybe just separating markers into chunk containers and adding hitArea to those containers can work, but dont believe that it'll work magically on first try. You have to actually debug this thing and do some profiling.

**Comment by novaknole** [comment]
Thanks man for this explanation. Will dig into it more and let you know. 

Meanwhile, could you help me with this? https://github.com/pixijs/pixi.js/issues/6219 many thanks really

**Comment by Patrick-Hammond** [comment]
If the lag is coming from the InteractionManager, would it be feasible to set the parent of your 16,000 objects to interactiveChildren=false when the map moves and re-enable it after moving?
