### ISSUE TITLE
Scissor mask not updated with the Graphics object

### ISSUE THREAD

**Issue by qtiki** [pixijs/pixi.js#6223]
### Expected Behavior

Scissor mask should be updated when the corresponding PIXI.Graphics object is updated.

### Current Behavior

When updating a "fast rect" graphics object mask the scissor mask stays in the old position.

### Possible Solution

The scissor rect should update with the graphics object.

### Steps to Reproduce

Enable scissor masks. Create a "fast rect" PIXI.Graphics object and set it as a mask. Update object with a new rectangle and observe the scissor mask not moving.

### Environment

- **`pixi.js` version**: _5.2.0_
- **Running Example (broken scissor mask)**: _https://www.pixiplayground.com/#/edit/386sIn5QW8PcUQ9Jm0e4G_
- **Running Example (working stencil mask)**: _https://www.pixiplayground.com/#/edit/DY4e_97kCe_42Utx5xDZJ_

ps. Since the scissor masking is disabled by default it's quite likely that this is a known issue. But in any case now you have a ticket for it!

**Comment by bigtimebuddy** [comment]
Thank you for the example, very helpful.

**Comment by ivanpopelyshev** [comment]
Good catch! Yes, it wasnt implemented in v5 before 5.2.0 and I wasn't sure that my implementation is correct, even with my tests.

**Comment by ivanpopelyshev** [comment]
Its kind of undefined behaviour because you didnt add `mask` to stage. updateTransform is not called -> boundsID not changed -> calculateBounds() are cached between frames. 

Workaround: add mask to the stage.

I can make PR to reset boundsID in case something was added, but im not sure if we want this behaviour, i will think about it.

**Comment by qtiki** [comment]
@ivanpopelyshev good point! It makes perfect sense that the mask has to be in the stage, my bad. Here's a link to a working scissor mask: https://www.pixiplayground.com/#/edit/loLYz~FFp6J42~hRrSvez

I've profiled this with a GPU profiler and can confirm that it's actually using the scissors and as such is a more optimal solution than the stencil version. So for what it's worth I think you guys should enable them by default.
