### ISSUE TITLE
Road to Native Support

### ISSUE THREAD

**Issue by stevenalanstark** [pixijs/pixi.js#6225]
Hello,

I know this has been brought up in the past, but I wanted to rephrase the question.

I am looking for a happy path to build our games once and run them on web and in native mobile for iOS and Android.

So far, the best solution seems to be either:

* 1) To look into GCanvas to have React Native render the Pixi.js code in OpenGL.
* 2) To build the game in C++ and use ams to run on the web. Maybe with emscripten
* 3) Custom code web, iOS and Android, with a shared assets pipeline
* 4) Wrapping the games in a web view

Option 1 hasn't been proven yet with Pixi, and I am unclear if it is production ready with any frameworks

Option 2 has a lot of issues as well, main one being that the games would need to be re-developed in C/C++

Option 3 shares the art, but has a custom development for Web, Android and iOS.

Option 4 has performance issues, but more than that it is highly discouraged by Apple. For my industry, this is not an option because Apple would reject any app using a webview 

Are there options I am missing, or some workflow that others have found to work for them on their projects?

thank you for any discussion on this topic.

**Comment by chipbell4** [comment]
I can speak to option 4) quite a bit! I don't know your exact use case but I've helped ship at least a dozen apps using PIXI.js in a WebView. In my experience we've received no rejections from Apple, or at least none on account of using a WebView. In all honesty, I think Apple is (understandably) trying to prevent people from "wrapping up a website" and trying to sell it on the app store. I think it really just boils down to making cool, unique content that runs at a decent framerate and if you've got that Apple will probably be happy!

Again, not knowing your particular use case, I really think option 4 is the best (we use cordova internally, but you might not need all of that).

**Comment by stevenalanstark** [comment]
@chipbell4 As I do fully agree with your assessment, business does not and with reason. It's looking more and more like I'll just need to dig my heels in and go for a webview or just do a PWA, and hope that Apple will approve it. The saving grace here is that all the js will be included in the initial app bundle, so there is no additional downloaded code.

**Comment by themoonrat** [comment]
I get the feeling you've gone through the same decision process our company went through, potentially the same industry if this was a relatively recent 'panic'. In the end, we were assured by Apple that their big issue was with a web view being used to bypass all App Store checks. You could host content remotely, and Apple had no idea what it was, and couldn't control any updates to it. 

But if all code and assets sat locally bundled in the app, or as part of dlc, then Apple could see that, see any updates to it, so would be fine.

They do still prefer native code, as developing on a Mac makes them more money! But for now I think we're ok...

Option 2 becomes more viable when WebAssembly properly takes off, as that would open the door to engines like Unity

**Comment by stevenalanstark** [comment]
@themoonrat Yes, you are very correct ;)

I am looking forward to where WebAssembly can take us :)

**Comment by flyskywhy** [comment]
@[vitalije](https://github.com/vitalije) @[GoodBoyDigital](https://github.com/GoodBoyDigital) @[englercj](https://github.com/englercj) @[okcoker](https://github.com/okcoker) @[gre](https://github.com/gre) @[Prozi](https://github.com/Prozi) @[timknip](https://github.com/timknip) @[themoonrat](https://github.com/themoonrat) @[jackwlee01](https://github.com/jackwlee01) @[RossKinsella](https://github.com/RossKinsella) @[ivanpopelyshev](https://github.com/ivanpopelyshev) @[nickdima](https://github.com/nickdima) @[stevenalanstark](https://github.com/stevenalanstark) @[chipbell4](https://github.com/chipbell4) @[bernardbaker](https://github.com/bernardbaker) 

You can try [react-native-pixi](https://github.com/flyskywhy/react-native-pixi) based on [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) refactored from [GCanvas](https://github.com/alibaba/GCanvas ).

The example game [snakeRN](https://github.com/flyskywhy/snakeRN) is based on [react-native-pixi](https://github.com/flyskywhy/react-native-pixi).

**Comment by ivanpopelyshev** [comment]
@flyskywhy holy cow!

**Comment by flyskywhy** [comment]
Breaking: Any APP now can be based on `pixi.js` `@4`, `@5`, `@6` or `@7` directly without `react-native-pixi` as described in [react-native-pixi@3](https://github.com/flyskywhy/react-native-pixi), you can easily follow the comments in example https://github.com/flyskywhy/GCanvasRNExamples/blob/master/app/components/Pixi.js to use any version of pixi.

**Comment by miltoncandelero** [comment]
This is forcing canvas 🤔 
Doesn't it work with webgl?

**Comment by flyskywhy** [comment]
TODO debug why webgl runs no error but no display.

But, since pixi.js is 2d game engine, so, work with forcing canvas or webgl, what is the difference for 2d game?

**Comment by miltoncandelero** [comment]
Canvas is CPU bound and really slow compared to GPU accelerated webgl.
Also, webgl gives you access to filters, meshes and other goodness

**Comment by flyskywhy** [comment]
Canvas in [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) is accelerated by GPU, and I found canvas is even faster some when run https://github.com/flyskywhy/snakeRN

There is `const _Filter = class extends Shader {` in `pixi.js-legacy/dist/pixi-legacy.js` , so can you test or give me some filters and meshes example code?
