### ISSUE TITLE
Texture color hue difference in Firefox  

### ISSUE THREAD

**Issue by darkowic** [pixijs/pixi.js#6228]
Hello!

The color hue is different on some machines.
![screenshot_13](https://user-images.githubusercontent.com/11510581/69159737-b266e680-0ae8-11ea-95b0-4af19a372d52.png)
_Tool used for checking difference: https://www.diffchecker.com/image-diff_

_I am aware that this issue is not probably strictly related to Pixi.js but I post it here to ask you guys for help with debugging it and finding a solution or if it is even possible to solve._

### Expected Behavior
Textures are rendered visually the same across all browsers.

### Current Behavior
On one laptop the color hue of the image is different than on other machines.
Correct result:
![test_chrome_laptop](https://user-images.githubusercontent.com/11510581/69160358-bba48300-0ae9-11ea-990b-ea7d4ef062de.png)
Incorrect result:
![test_firefox_laptop](https://user-images.githubusercontent.com/11510581/69160344-b3e4de80-0ae9-11ea-9caa-66edf4ca9361.png)

### Steps to Reproduce
Image causing problem: https://i.ibb.co/TkbRCsc/s-Sternenbaum-Vordergrund.png
(Probably I have more images causing the problem)
Playground for tests: https://www.pixiplayground.com/#/edit/lzu8cfq7tNHxPqRNb~Swa

Open the playground in chrome and in firefox. On some devices, the color of the image has different hue (see comparison above).

### Environment

- **`pixi.js` version**: _5.2.0_
- **Browser & Version**: _Firefox 70_
- **OS & Version**: _Window 10 Pro 1903_
- **Graphics card**: _Intel HD Graphics 3000_
- **Running Example**: _https://www.pixiplayground.com/#/edit/lzu8cfq7tNHxPqRNb~Swa_

**Comment by bigtimebuddy** [comment]
You might want to double check the color profile in the image. Sometimes this can cause subtle color rendering differences.

**Comment by darkowic** [comment]
Thank you for your answer. I checked the photo and it has correct `sRGB`

<details><summary>Image identify</summary>
<p>

```bash
$ identify -verbose s_Sternenbaum_Vordergrund.png 
Image: s_Sternenbaum_Vordergrund.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 561x800+0+0
  Units: Undefined
  Type: TrueColorAlpha
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 1-bit
  Channel statistics:
    Pixels: 448800
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 48.279 (0.189329)
      standard deviation: 61.1424 (0.239774)
      kurtosis: 5.71151
      skewness: 2.67739
      entropy: 0.538908
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 83.7481 (0.328424)
      standard deviation: 51.9363 (0.203672)
      kurtosis: 4.78862
      skewness: 2.36593
      entropy: 0.715744
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 48.5289 (0.19031)
      standard deviation: 60.7403 (0.238197)
      kurtosis: 5.81634
      skewness: 2.68632
      entropy: 0.641075
    Alpha:
      min: 255 (1)
      max: 255 (1)
      mean: 255 (1)
      standard deviation: 0 (0)
      kurtosis: 0
      skewness: 0
      entropy: 0
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 45.139 (0.177016)
      standard deviation: 50.3119 (0.197302)
      kurtosis: 12.4677
      skewness: 3.72237
      entropy: 0.473932
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 561x800+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2019-11-20T09:49:08+01:00
    date:modify: 2019-11-19T15:08:54+01:00
    png:iCCP: chunk was found
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 561, 800
    signature: 67fc147622ccacef1deb2e7b87b0d50ea08a3521959afa0f04e1c26b32b5f3c3
  Artifacts:
    filename: s_Sternenbaum_Vordergrund.png
    verbose: true
  Tainted: False
  Filesize: 521KB
  Number pixels: 449K
  Pixels per second: 44.88MB
  User time: 0.010u
  Elapsed time: 0:01.010
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
```
</p>
</details>

Also here is another photo causing the problem - https://i.ibb.co/wKVrk97/6e64ef15-922e-4a5a-92ef-9cb50d79a5c2.jpg
And it is also correct `sRGB` image.
<details><summary>Image 2 identify</summary>
<p>

```bash
$ identify -verbose 6e64ef15-922e-4a5a-92ef-9cb50d79a5c2.jpeg 
Image: 6e64ef15-922e-4a5a-92ef-9cb50d79a5c2.jpeg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 4032x3024+0+0
  Units: Undefined
  Type: TrueColor
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Pixels: 12192768
    Red:
      min: 1 (0.00392157)
      max: 255 (1)
      mean: 114.541 (0.449179)
      standard deviation: 40.7048 (0.159627)
      kurtosis: 1.09179
      skewness: 1.03132
      entropy: 0.901382
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 118.929 (0.466387)
      standard deviation: 43.4787 (0.170505)
      kurtosis: -0.0639422
      skewness: 0.383965
      entropy: 0.927328
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 130.62 (0.512233)
      standard deviation: 68.3421 (0.268008)
      kurtosis: -1.25719
      skewness: 0.257624
      entropy: 0.970017
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 121.363 (0.475933)
      standard deviation: 52.3384 (0.205249)
      kurtosis: -0.178115
      skewness: 0.617967
      entropy: 0.932909
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 4032x3024+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 75
  Orientation: Undefined
  Properties:
    date:create: 2019-11-20T11:20:28+01:00
    date:modify: 2019-11-20T11:20:11+01:00
    jpeg:colorspace: 2
    jpeg:sampling-factor: 2x2,1x1,1x1
    signature: dc02e7853644a849acf960777d69b6465b5068d05224cafd8dc56b8286b35882
  Artifacts:
    filename: 6e64ef15-922e-4a5a-92ef-9cb50d79a5c2.jpeg
    verbose: true
  Tainted: False
  Filesize: 873KB
  Number pixels: 12.19M
  Pixels per second: 135.5MB
  User time: 0.090u
  Elapsed time: 0:01.089
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
```
</p>
</details>

Updated playground - https://www.pixiplayground.com/#/edit/lzu8cfq7tNHxPqRNb~Swa
![new_test_compare_download](https://user-images.githubusercontent.com/11510581/69244601-8493a780-0ba5-11ea-90a0-e4925cb2dad3.png)

Well, I have the same second laptop and I moved hard drive to it to check if it is a hardware problem. **And it is not - the result is the same on the second laptop.** I will try to upgrade drivers.

Do you think it might be anything related to the browser, so I can handle it?

**Comment by darkowic** [comment]
The drivers' upgrade did not help. Well, it's a mystery for me ;)

**Comment by ivanpopelyshev** [comment]
I saw those kind of cursed images. `texImage2D(image)` reads RGB instead of sRGB somehow :) 

Change the image.

Thank you for the report, I saved images as an example for my future talks about image-related problems that WebGL users might stumble across.

**Comment by darkowic** [comment]
Well, Is there any way I can detect that it happened?

**Comment by darkowic** [comment]
And many times I can not change the image - it is uploaded by a user ;)

**Comment by ivanpopelyshev** [comment]
No :) There's also option try to use `createImageBitmap` , pixi supports it if you switch on the flag, you can also do it per image, but i dont want to give you all the code.

The thing is, if you encountered it , you have to understand how texture uploading works:

https://github.com/pixijs/pixi.js/tree/dev/packages/core/src/textures/resources
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/BaseImageResource.js
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/ImageResource.js
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/CanvasResource.js

You can give extra params when you create resources, but its not possible with current textureLoader plugin for `PIXI.Loader`, its not that hard to solve.

Try to upload through canvas, try use createImageBitmap, detect if images are somehow different (readPixels ftw).

**Comment by darkowic** [comment]
Thank you very much @ivanpopelyshev for the tips! I will go deeper into it in the near future. I will close this issue then.
