### ISSUE TITLE
Fail to compile pixi.js-legacy

### ISSUE THREAD

**Issue by hezhuojie** [pixijs/pixi.js#6230]
Fail to compile project which imports pixi.js-legacy@5.0.3 by es-module
### Expected Behavior
Compile successfully
### Current Behavior
Error Occur:
```
./node_modules/pixi.js-legacy/lib/pixi-legacy.es.js 11:0-69
'@pixi/canvas-renderer' dose not contain an export named 'CanvasTinter'.
```
### Possible Solution
Now dependencies of pixi.js-legacy are specified like this
```
"dependencies": {
    "@pixi/canvas-display": "^5.2.0",
    "@pixi/canvas-extract": "^5.2.0",
    "@pixi/canvas-graphics": "^5.2.0",
    "@pixi/canvas-mesh": "^5.2.0",
    "@pixi/canvas-particles": "^5.2.0",
    "@pixi/canvas-prepare": "^5.2.0",
    "@pixi/canvas-renderer": "^5.2.0",
    "@pixi/canvas-sprite": "^5.2.0",
    "@pixi/canvas-sprite-tiling": "^5.2.0",
    "@pixi/canvas-text": "^5.2.0",
    "pixi.js": "^5.2.0"
  }
```
**To solve this problem, all of them should be specified static version instead of starting with '^' !!**

After diagnosing, I found `/node_modules/pixi.js-legacy/lib/pixi-legacy.es.js` try to import `CanvasTinter` from `@pixi/canvas-renderer`. However, installed version of `@pixi/canvas-renderer` is 5.2.0 and `CanvasTinter` is renamed to `canvasUtils`. Well, compilation must fail.

I can solve this issue by simply upgrading pixi version to latest. But risk remains while make any breaking change, so i suggest **All @pixi's package should use static version !!!**

### Steps to Reproduce
install pixi.js-legacy@5.0.3 and compile project with it
### Environment

- **`pixi.js-legacy` version**: 5.0.3

**Comment by themoonrat** [comment]
Hi @hezhuojie 
This is fixed in a recent PR: https://github.com/pixijs/pixi.js/pull/6211 for any new PixiJS releases :)

**Comment by bigtimebuddy** [comment]
Fixed already, closing.
