### ISSUE TITLE
Visual differences between PixiJS v4 and PixiJS v5 with resolution of 0.75

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#6232]
When upgrading from v4 to v5, I'm seeing visual rendering differences when the resolution is less than 1. This is most noticable when it's set to 0.75, and is throwing off some visual aspects of the games.

v4: 
![image](https://user-images.githubusercontent.com/1528426/69339761-034c1b80-0c5e-11ea-856e-915fbf09826f.png)
v5: 
![image](https://user-images.githubusercontent.com/1528426/69339766-0810cf80-0c5e-11ea-9374-cd0ac7fcc5cd.png)

You can see things very slightly move, like the text. And the sprites then also move very slightly; in this case messing up the tiling effect.

Some pixi playgrounds to demonstrate this

v4: https://www.pixiplayground.com/#/edit/i9g9G07R5FOkkC3ieRbP6
v5: https://www.pixiplayground.com/#/edit/A2RzqbjAKoxoQRzVMNND4

Change the resolution to 1 or above, and both playgrounds look identical. But take it below 1, and there are differences.

This only occurs on the WebGL Renderer. The Canvas Renderer is uneffected.

### Environment

- **`pixi.js` version**: _5.2.2_
- **Browser & Version**: _Chrome 78_
- **OS & Version**: _Windows 10_

**Comment by themoonrat** [comment]
Ok, doing some hunting, and it's because for roundPixels
v4: for each value something like: `float32View[index] = ((vertexData[0] * resolution) | 0) / resolution;`
v5: `vertexData[i] = Math.round(vertexData[i]);`

If I hack together the v5 to do `vertexData[i] = Math.round((vertexData[i] * 0.75 | 0) / 0.75);` then it's a lot lot closer; close enough for me, anyway. The problem is, `calculateVertices` doesn't have access to the renderer, so doesn't have access to the resolution ... and it's not all routes to calling calculateVertices have an instance of the renderer as a param in the first place.

Any ideas?

**Comment by ivanpopelyshev** [comment]
Yes, I've changed that, I think I and @GoodBoyDigital decided that it wasnt that important.

Turns out it is :)

For temp fix, you can override `Sprite.prorotype.calculateVertices` that way it uses your global resolution to round stuff.
