### ISSUE TITLE
Missing `ApplicationOptions` in type definitions for 5.x

### ISSUE THREAD

**Issue by EvidentlyCube** [pixijs/pixi.js#6237]
In the 4.x Pixi.js types all of the options in `PIXI.Application` constructor were an interface called `PIXI.ApplicationOptions`, now it's just an anonymous object defined inline in the function. I believe the reason is that previously the type definitions were assembled manually, while now it's generated from the code itself.

I also understand that Pixi is planning to migrate to typescript, either fully or partially (at least looking at the commit history). Migration `Application` to TypeScript would essentially solve the problem, and is something I'd be both capable and willing to do.

Is there a plan to migrate Pixi code to TS? If so, are there any standards you have established so far towards how this is happening, and are outsiders welcome to help with that endeavor? Otherwise, any plans to expose `Application` constructor options as an interface?

**Comment by bigtimebuddy** [comment]
Great idea and thanks for being willing to help. PR welcome! Right now we are trying to convert display and core packages to TS. Once we are over that hump, things like app get much easier.
