### ISSUE TITLE
Wrong x Axis display when the data points>80K

### ISSUE THREAD

**Issue by rubyzhao** [pixijs/pixi.js#6238]
Please see the code at [Sine Wave]( https://github.com/rubyzhao/Pixi_MyChart_Line)
When set loop=2e3, this shows as below:
![image](https://user-images.githubusercontent.com/12829001/69490394-3974df80-0e98-11ea-83e0-6c4d03500760.png)
When set loop>8e4, the plot area in X direction becomes less and less. 
### Expected Behavior
The plot area in X direction shouldn't be change, because the maximum X isn't changed.  
### Current Behavior
When set loop=2e5, it becomes about one third in X direction:
![image](https://user-images.githubusercontent.com/12829001/69490415-88227980-0e98-11ea-8147-00370b108df2.png)

### Steps to Reproduce
set loop=2e2,2e3,2e4,2e5 to see the difference
### Environment

- **`pixi.js` version**: _5.2.0_
- **Browser & Version**: _Chrome 78.0.3904.108_
- **OS & Version**: _Windows 10X64 1803_
- **Running Example**: _https://github.com/rubyzhao/Pixi_MyChart_Line_

**Comment by ivanpopelyshev** [comment]
maybe its 64k vertices limit? 

https://github.com/pixijs/pixi.js/wiki/v5-Hacks#pixigraphics

**Comment by rubyzhao** [comment]
Thanks for your help. I follow the suggestion and add below, but the issue is still there.
`//PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL;
PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL2;`
...
`line.geometry.updateBatches();
//try commenting that to see Uint16 overflow
line.geometry._indexBuffer.update(new Uint32Array(line.geometry.indices));`

Please see the video for loop=2e5. Initially looks right, then the area become less automatically. 

[Pixi Line - Google Chrome 11_24_2019 12_58_23 PM.zip](https://github.com/pixijs/pixi.js/files/3883425/Pixi.Line.-.Google.Chrome.11_24_2019.12_58_23.PM.zip)

**Comment by ivanpopelyshev** [comment]
Oh, that's interesting. OK, I'm trying to debug it here: https://www.pixiplayground.com/#/edit/ub6F36aWoMfw0o7ebnu8o

It can be a real bug. I just want to remind that real app shouldn't do that kind of input, 

That's what I call `100 thousands bunnies problem` - you need high-level algorithm to complement pixi low-level or it can have all kind of interesting side effects.

**Comment by ivanpopelyshev** [comment]
OK, found that `finishPoly()` is needed because line wasnt closed and it awaits input. `render()` method has that line just in case. That's a protected method, but I see more and more cases that we need something like that to be public.

```js
line.finishPoly();
line.geometry.updateBatches(); 
line.geometry._indexBuffer.update(new Uint32Array(line.geometry.indices));
```

**Comment by rubyzhao** [comment]
Great. Appreciate your help.
I know I shouldn't challenge this again. But when set loop=2e7,  it initially shows right as [basic canvas](https://github.com/rubyzhao/Sine-Wave-with-Basic-Canvas/blob/master/Canvas_Sin.html), after while disappear again.

**Comment by ivanpopelyshev** [comment]
There are no breaks on plot train. I'll look up later :)
