### ISSUE TITLE
ShaderSystem has unused method `setUniforms`

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#6241]
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/shader/ShaderSystem.js#L106

It also uses `shader.syncUniforms` which does not exist. @GoodBoyDigital do you remember why did you want to add it here?

**Comment by GoodBoyDigital** [comment]
honestly nope! I think it may just be a there from previous times! `bind` does the trick for most situations!
