### ISSUE TITLE
confusion between desired global cache textureCacheIds and PIXI.Texture instance textureCacheIds

### ISSUE THREAD

**Issue by nphias** [pixijs/pixi.js#6242]
I get the following error when trying to get texture cache data to check if the image has been cached:
Property 'textureCacheIds' does not exist on type 'typeof Texture'.ts(2339)

### Expected Behavior
an array of image id's (in my case the filenames  of the images)
### Current Behavior
typing error
### Possible Solution
typings fix?

### Steps to Reproduce
console.log(PIXI.Texture.textureCacheIds)

### WORK AROUND
iterate over the PIXI.utils.TextureCache to check if the image exists in the cache

- **`pixi.js` version**: 5.20
- **Browser & Version**: electron 7.1.1 (chrome)
- **OS & Version**:  mac os mojave 10.14.6

**Comment by bigtimebuddy** [comment]
I'm not sure you're using this correctly. `textureCacheIds` is a property on the Texture instance. It is not static. Here's an example: https://www.pixiplayground.com/#/edit/hnws9kc5uY4eaYmuwSV4m

**Comment by nphias** [comment]
ok thanks .. seems i got confused between the global cache  and the one Texture instance..
documentation is lacking (in todo state) 
https://pixijs.download/dev/docs/PIXI.utils.html#.TextureCache
basically I thought there was a helper method that would return an array of the all the keys i have in the static PIXI.utils.TextureCache.. 
Its actually very confusing:  because  PIXI.Texture has a static method : 
` addToCache(texture: PIXI.Texture, id: string): void; `
which does add to the global cache...  but it does not offer any helper method to retrieve ids from the gloabl cache...  (the textureCacheIds is only for one Texture instance)... 
 
I think this issue should be converted into a feature request for a getGlobalTextureCacheIds helper function... :)

**Comment by nphias** [comment]
i refactored the logic in my code .. now i just test to see if the texture is in the cache using
if (PIXI.utils.TextureCache["myimagefile"] ) .....
hope its clearer for other people new to texture management
