### ISSUE TITLE
Did event.stopPropagation get tweaked recently?

### ISSUE THREAD

**Issue by xevrem** [pixijs/pixi.js#6244]
It may be we've just somehow sidestepped this situation in the past (due to luck or ignorance), but `stopPropgation` seems to not stop all event propagation :( (i.e., clicks)

### Expected Behavior
If `Container.on('click')` is set and a child of that container whom also listens to a click or a precusor (e.g., mousedown, mouseup) calls `stopPropagation()`; then `Container` should never receive a `click` event (nor the appropriate precusor).

I believe this also held true (at least at some time) if children had multiple listeners (i.e., two different class Mixins listened to something like 'mousemove' say for movement vs resizing) that their parent container would not receive the event.

### Current Behavior
The parent seems to receive the event, at least for certain cases in multi-listeners, even when all listeners call `stopPropagation()`...

i.e. we're seeing events issued to our parent container from children whom have issued `event.stopPropagation()` from all their listeners: (i.e., we only want events directly issued to our Container to be handled by it)

### Possible Solution
no idea atm other than a custom event pre-processor to merge `Graphics`/`Sprite` events into a meta-event.

### Environment

- **`pixi.js` version**: 5.2.0
- **Browser & Version**: Chromium 76-78, Firefox 69-71
- **OS & Version**: MacOs 10.14.6
- **Running Example**: [codepen example](https://codepen.io/xevrem/pen/NWWJjoX?editors=0011) in this example the parent is only prevented if i prevent the `mouseup` or explicitly a `click` it is not prevented on a `mousedown` even though a `mousedown` must be a precursor for a `click`

All that said, i assume the issue is probably with our use, is there a description somewhere about how multi-listeners and multiple stopPropagations operate against a potential parent event?

edit: description and codepen example

**Comment by ivanpopelyshev** [comment]
Yes, it was tweaked with delayedEvents: 

https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/InteractionManager.js#L1020
https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/InteractionManager.js#L958

If `mouseUp` was prevented on element, same element can still receive `click`. That's all I know, I'm not the interaction master :)

**Comment by xevrem** [comment]
It looks like maybe the current workaround is to see if `event.stopped` is `true` then before allowing any event listener to proceed (i.e., fast-fail)

**Comment by laino** [comment]
You are expecting ``.stopPropagation()`` to also work like ``.preventDefault()``.

The short answer is that events work now more like they do in HTML/JavaScript, which is the the long term goal (though pixi is not 100% there yet).

This is the PR which changed that behavior with some more information: https://github.com/pixijs/pixi.js/pull/6043
