### ISSUE TITLE
FilterSystem doesn't handle autoFit correctly.

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6245]
```
// FilterSystem.js#195-6
// only auto fit if all filters are autofit
autoFit = autoFit || filter.autoFit;
```

According to the comment, `autoFit` should be merged with the `&&` operator. Is this the case?

**Comment by ivanpopelyshev** [comment]
yes, that's a bug. We had `dontFit` in a PR before it was fixed to `autoFit` , but sign remained :)

**Comment by dev7355608** [comment]
This hasn't been fixed yet, it looks like.
