### ISSUE TITLE
Proposal (work-in-progress): extended filter system features

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6246]
Our team has uses a modified version of pixi.js's `FilterSystem`. We are adding new features that might be useful to other users, and we were looking to know if this would be accepted into the main codebase or as a plugin.

`pixi-extended-filter-system` package repo is here: https://github.com/phase-software/pixi-extended-filter-system/tree/master/src

Currently, we have added these feature(s):

- [x] `measure` pass: pixi.js has two options for the input frame given to a filter - the "object + padding" or its intersection with the screen. There is no intermediate. This can cause performance problems, since `autoFit=false` filters needlessly apply on the whole object. By allowing the filters to measure their required input, we eliminate this issue. (Note: the input is never outside the object being rendered, and this is enforced in our repo).

- [x] returning a texture other than output: In multi-pass filters like the kawase-blur, passes are done in a flip-flop basis. If the number of passes are even, then we cannot use the input & output textures to do the passes (since we would end on the input texture). If we allow filters to return output textures (other than the given output texture), we could eliminate extra texture allocations in filters like the drop-shadow & blurs. Of course, sometimes we cannot change the output texture (like in the case of the very last filter, which applies to the screen). We can specify whether returning an alternative output texture Is allowed with a filter-manager property.

- [x] providing a custom geometry to `FilterSystem#applyFilter`.

- [x] pipeline support: in order to simplify building multi-pass filters, we should create an API that allows filters to change the input/output for each pass.

Sidenote: I would like to reference this issue from `pixi-filters`, and ask that pixi devs consider allowing that feature into the `pixi-filters` codebase: https://github.com/pixijs/pixi-filters/issues/231

**Comment by ivanpopelyshev** [comment]
You are on a right path. I have custom FilterSystem that has second feature.

**Comment by ivanpopelyshev** [comment]
Of course its better when all measurement is done even before render() pass - that opens way to smart caching, but your approach is good enough to be considered in vanilla pixijs.

**Comment by st3v0** [comment]
What about adding the ability to selectively disable filter types globally. For example we're currently implementing an adaptive performance controller and it would be very handy if we could for example disable all Blurs or Glows in the system when we detect the users game performance is being degraded. At the moment I can't seem to find and existing way of doing this without rewriting some components.

**Comment by SukantPal** [comment]
> What about adding the ability to selectively disable filter types globally. For example we're currently implementing an adaptive performance controller and it would be very handy if we could for example disable all Blurs or Glows in the system when we detect the users game performance is being degraded. At the moment I can't seem to find and existing way of doing this without rewriting some components.

Nice idea; maybe @ivanpopelyshev could tell you if that's something pixi.js would want to support natively - the thing is that it might just be too specific.

**Comment by SukantPal** [comment]
@st3v0 Maybe we could create a plugin library for that use case.
