### ISSUE TITLE
Import problem for '@pixi/utils': "Cannot read property 'device' of undefined"

### ISSUE THREAD

**Issue by kapulkin** [pixijs/pixi.js#6250]
I get message "Cannot read property 'device' of undefined" for code

` import { correctBlendMode, premultiplyRgba } from '@pixi/utils'`

### Expected Behavior
The project compiles and works without compile and runtime errors

### Current Behavior
I got error message
` import { correctBlendMode, premultiplyRgba } from '@pixi/utils'`

### Possible Solution

pixi/utils.js import pixi/settings.js, which actually contain code with error.

Code

`var isMobile = _interopDefault(require('ismobilejs'));

if (!isMobile.apple) {
    isMobile.apple = {}
}
`
solves the compilation/runtime problem.

### Steps to Reproduce

Just create .js file in project and import '@pixi/utils'. For example:

pixiTest.js
`import { correctBlendMode, premultiplyRgba } from '@pixi/utils'`
![2019-11-26_22-39-35](https://user-images.githubusercontent.com/800129/69666977-38150400-109e-11ea-834a-cebc79d0f848.png)
`

### Environment

- **`pixi.js-legacy` version**: ^5.1.3
- **Browser & Version**: Chrome 78.0.3904.108
- **OS & Version**: _e.g. Mac OS 10.14.5
- **Running Example**: https://global.tix-system.com/events/mamasha_kurazh/380308/

**Comment by bigtimebuddy** [comment]
This was fixed in https://github.com/pixijs/pixi.js/pull/6283
