### ISSUE TITLE
Graphics.lineStyle.alignment has a problem drawing polygon

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixi.js#6253]
![FastStoneEditor1](https://user-images.githubusercontent.com/6738986/69741966-f310d080-1176-11ea-9fb6-322ef89ef85d.png)

Painting circle are normal.

https://pixiplayground.com/#/edit/UTeG6bO~SbfOZNVz5Ckco

**Comment by ivanpopelyshev** [comment]
Spot the difference: https://pixiplayground.com/#/edit/pT0YrL9q8IgBIHVWvfN4A

The idea is that Line alignment is based on its orientation. If we make closed polygon behaviour different , like, if we detect whether it left-oriented or right-oriented - it'll be different from not-closed polygon. 

Can you tell me which behaviour is right, especially when there is no lineAlignment in other 2d renderers ? :)

**Comment by JetLua** [comment]
Well, I didn't think about drawing directions (clockwise or counterclockwise).

**Comment by ivanpopelyshev** [comment]
Yep, its a problem that @GoodBoyDigital didn't think about when he introduced that. We even fixed rounded rects after his initial PR, they were in other direction.

All winding/holes - related issues wil be solved in next year i think, we can start discussing them.

**Comment by georeith** [comment]
> Can you tell me which behaviour is right, especially when there is no lineAlignment in other 2d renderers ? :)

I think a simple rule is that inside is always on top of the fill, center is always the same and outside is always outside the fill.

If you look at Figma (WebGL) or Sketch (OpenGL) they both have stroke/line alignment and direction of the polygon doesn't matter.
