### ISSUE TITLE
Pixi BlurFilter showing interference from other sprites.

### ISSUE THREAD

**Issue by gregorymark** [pixijs/pixi.js#6257]
Hi, I'm having problems blurring images with transparent backgrounds. I'm animating multiple sprites with transparent backgrounds. The edges of each sprite seem to pick up the colour from the sprites around them as they move. The colour doesn't always correspond to the sprite itself, so I'm assuming it picks up the other sprites' colours somehow.

I'm running this on Pixi 5.1.5 on Chrome 78, Mac Mojave. Unfortunately I can't show a link as it's a client project I can't share, but I've attached a screenshot of the effect, which I'm hoping will help identify.

Some excerpts of what I'm hoping are the relevant bits of code. Please let me know if anything else would be useful!

Initialising:
```
// Create a Pixi Application
this.pixi.app = new this.pixi.Application({
    antialias: true,
    transparent: true
});

// Add the Pixi created canvas to the HTML document
this.stage.appendChild(this.pixi.app.view);

// Canvas setup
this.pixi.app.renderer.autoDensity = true;
this.pixi.app.renderer.resize(window.innerWidth, window.innerHeight);

// Add sprites
this.pixi.loader.add(this.shapeURLs)
    .load((loader, resources) => this.setupShapes(loader, resources));
```
Setting up sprites:
```
this.pixi.container = new this.pixi.Container();

for (let i = 0; i < this.requiredShapes; i++) {
    let shapeSprite;
    const texture = resources[`${this.shapesDirectory}/shape${this.shapes[i].shapeNum}-blur-0.png`].texture;
    shapeSprite = new this.pixi.Sprite(texture);
    shapeSprite.anchor.set(0.5, 0.5);
    shapeSprite.resolution = 2;
    shapeSprite.alpha = 0;

    this.shapes[i].filter = new this.pixi.filters.BlurFilter(8);
    shapeSprite.filters = [this.shapes[i].filter];

    this.shapes[i].sprite = shapeSprite;
    this.pixi.container.addChild(shapeSprite);

    shapeSprite.scale.set(this.minScale, this.minScale);
}

this.pixi.app.stage.addChild(this.pixi.container);
```
and from the render function:
```
this.shapes[i].cycleTime = timestamp - this.shapes[i].cycleStartTime;

// Fade the shape in right at the start
const alphaVal = this.shapes[i].cycleTime / 1000 > 1 ? 1 : this.shapes[i].cycleTime / 1000;
if (this.shapes[i].alpha !== alphaVal) {
    this.shapes[i].alpha = alphaVal;
    this.shapes[i].sprite.alpha = alphaVal;
}

if (this.shapes[i].cycleTime >= this.shapes[i].duration) {
    this.shapes[i].cycleStartTime = timestamp;
} else {
    const fractionComplete = this.shapes[i].cycleTime / this.shapes[i].duration;

    // Set the z which will be used to project 3d position to 2d
    this.shapes[i].z = this.maxZ - this.maxZ * fractionComplete;

    /*
    * The zFocusPoint is the point in a shape's motion towards the screen at
    * which it should be in focus. pauseForNTextures is how many textures' worth
    * we'll keep it in focus (setting the pause by a number of textures requires
    * less calculation than setting it as a decimal).
    */
    const zFocusPoint = 0.65;
    this.shapes[i].filter.blur = this.maxBlur - this.maxBlur * fractionComplete / zFocusPoint;

    // Scale the shape up to full scale
    const scale = this.minScale + (1 - this.minScale) * fractionComplete * fractionComplete; // easeInQuad
    this.shapes[i].sprite.scale.set(scale, scale);
}
```
<img width="922" alt="Screenshot 2019-12-02 at 21 13 27" src="https://user-images.githubusercontent.com/7263649/69996651-65ecc380-154a-11ea-89e8-586ace636aa9.png">
<img width="863" alt="Screenshot 2019-12-02 at 21 25 55" src="https://user-images.githubusercontent.com/7263649/69996652-65ecc380-154a-11ea-87d0-b40717692fda.png">

Thanks in advance!!!

**Comment by ivanpopelyshev** [comment]
Oh, those lines. Yes, need to add clamping in texture sampling, that's like 1.5x slowdown.

https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters
Its this problem: https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters#bleeding-problem
I didn't add a fix to pixi-v5 blurFilter. You can just copy it and add usage of filterClamp.

If you don't understand how to do that, well, wait a month or two when i release my own blurfilter, or ask me to make a fix special for your game.

**Comment by gregorymark** [comment]
@ivanpopelyshev thanks for the info!

I am a bit unsure about how it would work, especially the *WE_CALCULATED_IT_SOMEHOW_SEE_ABOVE* bit :) Is there somewhere I could message you privately about some of this?

**Comment by gregorymark** [comment]
@ivanpopelyshev if it would be possible to patch, that would be brilliant. What would you need?

**Comment by ivanpopelyshev** [comment]
Just a minimal demo where it happens on codepen or pixi-playground. I probably can do it myself but you can save my time by doing test, its not difficult as a solution.

**Comment by ivanpopelyshev** [comment]
Here's the clamp in outline filter: https://github.com/pixijs/pixi-filters/blob/3138e6d973251d1d46d53c443369636fb36b79fb/filters/outline/src/outline.frag#L18

**Comment by gregorymark** [comment]
Heya, yeah I'm not too sure where I should be editing and adding the clamp. I'd appreciate it loads if you could fix the pixi-playground I've made. I've randomly placed the shapes, but I get the issue pretty consistently.

https://www.pixiplayground.com/#/edit/tX9YWzc-pFgiMYLwWJqvb

Thanks so much! I was also wondering if you do any paid work on this kind of stuff, as I have a project that I may need help in optimising. Ignore me if this isn't the place though.

**Comment by ivanpopelyshev** [comment]
Good, that makes things easier!

> Thanks so much! I was also wondering if you do any paid work on this kind of stuff, as I have a project that I may need help in optimising. Ignore me if this isn't the place though.

I've sent you invite to PixiJS slack, we can discuss it there. I dont have secrets about it - most of the its free, but sometimes people contribute to https://opencollective.com/pixijs or pay for my hosting, im maintaining old servers of gameofbombs.com :)

**Comment by ivanpopelyshev** [comment]
OK, temporary solution is here: https://www.pixiplayground.com/#/edit/kuhrhc4jG5QnRRtIfwGwk

Basically i went here: https://github.com/pixijs/pixi.js/blob/dev/packages/filters/filter-blur/src/BlurFilterPass.js#L88

and changed `true` to `false`

```js
function blurFilterPassApply(filterManager, input, output, clear)
{
    if (output)
    {
        if (this.horizontal)
        {
            this.uniforms.strength = (1 / output.width) * (output.width / input.width);
        }
        else
        {
            this.uniforms.strength = (1 / output.height) * (output.height / input.height);
        }
    }
    else
    {
        if (this.horizontal) // eslint-disable-line
        {
            this.uniforms.strength = (1 / filterManager.renderer.width) * (filterManager.renderer.width / input.width);
        }
        else
        {
            this.uniforms.strength = (1 / filterManager.renderer.height) * (filterManager.renderer.height / input.height); // eslint-disable-line
        }
    }

    // screen space!
    this.uniforms.strength *= this.strength;
    this.uniforms.strength /= this.passes;

    if (this.passes === 1)
    {
        filterManager.applyFilter(this, input, output, clear);
    }
    else
    {
        const renderTarget = filterManager.getFilterTexture();
        const renderer = filterManager.renderer;

        let flip = input;
        let flop = renderTarget;

        this.state.blend = false;
        // changed false to true here
        filterManager.applyFilter(this, flip, flop, true);

        for (let i = 1; i < this.passes - 1; i++)
        {
            renderer.renderTexture.bind(flip, flip.filterFrame);

            this.uniforms.uSampler = flop;

            const temp = flop;

            flop = flip;
            flip = temp;

            renderer.shader.bind(this);
            renderer.geometry.draw(5);
        }

        this.state.blend = true;
        filterManager.applyFilter(this, flop, output, clear);
        filterManager.returnFilterTexture(renderTarget);
    }
}

PIXI.filters.BlurFilterPass.prototype.apply = blurFilterPassApply;
```

**Comment by ivanpopelyshev** [comment]
I'm testing two versions of custom blur shader here, it doesn't work on some mobiles
5x5 blur: https://www.pixiplayground.com/#/edit/R-UkzTo-okWF7sfxdcqGn
4x4 blur: https://www.pixiplayground.com/#/edit/7ch9gJwmlddGRZvx_Id3d

**Comment by jteutenberg** [comment]
This also affects TiltShiftFilter.apply() which currently does not take a "clear" argument.

Adding a clear value to the calls to [TiltShiftXFilter.apply() and TiltShiftYFilter.apply()](https://github.com/pixijs/pixi-filters/blob/master/filters/tilt-shift/src/TiltShiftFilter.js#L34) fixes the bleeding for me.

**Comment by bigtimebuddy** [comment]
@jteutenberg can you make a Pull request to fix that in the pixi-filters repo?
