### ISSUE TITLE
Render texture fading with low opacity will not be pure black

### ISSUE THREAD

**Issue by gs11118** [pixijs/pixi.js#6259]
![image](https://user-images.githubusercontent.com/38950021/70057962-07dae180-1619-11ea-81cd-8e275cbe75a8.png)

If you see closely there is a trailing dark grey line. If I draw a black rect with 0.03 opacity many many times,

### Expected Behavior
 I'd expect to reach 100% black. 
### Current Behavior
But it's still this kind of grey.
### Steps to Reproduce

https://codepen.io/kentskyo/pen/ragamj
```

var x = 20.0; // Initial x-coordinate
var y = 10.0; // Initial y-coordinate
var targetX = 370.0; // Destination x-coordinate
var targetY = 380.0; // Destination y-coordinate
var easing = 0.02; // Size of each step along the path
var d;

var stage = new PIXI.Stage(0x000000);
var renderer = PIXI.autoDetectRenderer(512, 512,
  {antialiasing: true, transparent: false, resolution: 1});
document.body.appendChild(renderer.view);
 

var fade = new PIXI.Graphics();
stage.addChild(fade);

mainLoop();

function mainLoop() {
  d = dist(x, y, targetX, targetY);

  if (d > 1.0) {
    x += (targetX - x) * easing;
    y += (targetY - y) * easing;

    fade.beginFill(0x000000,0.05);
    fade.drawRect(0, 0, renderer.width, renderer.height);
    fade.endFill();             
    
    fade.beginFill(0x0cf727);
    fade.drawEllipse(x, y, 20, 20);
    fade.endFill();             
  }

  renderer.render(stage);          
  requestAnimationFrame(mainLoop);
}
 
// find distance between two points
function dist(x1,y1,x2,y2) {
  return Math.sqrt( (x2-=x1)*x2 + (y2-=y1)*y2 );
}
```

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
ok, so suppose we have color range from 0 to 255. Your operation is basically `color = color * 0.97;`. if color is 15 or so, `Math.round(15*0.97) = Math.round(14.55) = 15`. For 16 its rounded to 15.

Lets take a pixel after 3 seconds, right when you started the circle:
```js
setTimeout(() => {
  const gl = renderer.gl;
  const w = renderer.view.width;
  const h = renderer.view.height;
  const pixels = new Uint8Array(4);
  renderer.render(stage);     
  gl.readPixels(20, h-10, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, pixels);
  console.log(pixels);
},3000)
``` 

result is `12, 15, 15, 255`. ok, we have g=15, b=15 like predicted, but r=12.. oh right it was 12 in beginning.

btw, your PixiJS version in that demo is 2.2.8

**Comment by stevemarksd** [comment]
I think this is still an issue. For example go to photoshop and add 2 layers with 97% opacity on a white background. is pure black, not grey
