### ISSUE TITLE
Initialisation: Application Ticker starts before rendering. Initial Freeze?

### ISSUE THREAD

**Issue by npx** [pixijs/pixi.js#6267]
Hi!

I am relatively new to Pixi v5 and I find this behavior odd.

Assume the following code:
```TypeScript
import { Application, Graphics, Point, Ticker } from 'pixi.js';

function makeRect(color: number, zIndex: number, pos: Point): Graphics {
  const rectangle = new Graphics();
  rectangle.beginFill(color);
  rectangle.drawRoundedRect(0, 0, 50, 50, Math.floor(50 / 2));
  rectangle.endFill();
  rectangle.position = pos;
  rectangle.zIndex = zIndex;
  return rectangle;
}

const app = new Application({ width: 70, height: 360, antialias: true });
document.body.appendChild(app.view);

const start = makeRect(0x00ff00, 1, new Point(10, 10));
const stop = makeRect(0x0000ff, 1, new Point(10, 300));
const tween = makeRect(0xff0000, 2, new Point(10, 10));

app.stage.addChild(start, stop, tween);

let tweenStart;
const begin = 10;
const end = 300;
const duration = 2000;

function tweenUpdate() {
  // start with the first update
  tweenStart = tweenStart || Date.now();

  const now = Date.now();
  const t = Math.min(1, (now - tweenStart) / duration);
  tween.position.y = begin * (1 - t) + end * t;
}

// Listen for animate update.
// app.ticker.add(delta => {
//   tweenUpdate();
// });

const ticker = new Ticker();
ticker.add(() => {
  tweenUpdate();
});

setTimeout(() => {
  ticker.start();
}, 2000);
```

I wrote a very very simplified time based animation/tweening. On the first call of `tweenUpdate()` I set the start time of my animation and I know it should last for 2000ms.

Now when I use the Application Ticker to run my animation right after the initialisation, I am missing half of my animation.

That is because the ticker is running and the `tweenUpdate()` happens before we can actually see anything on our scene.

When using the `setTimeout()` approach, starting the ticker only after the initial freeze, I can see the full animation.

Even when starting the Ticker in `requestAnimationFrame`, time passes until the first rendering is visble.

Is there an event I can rely on, to start my ticker after the initial rendering is visible to the user?
Why is pixi freezing up initially?

**Comment by bigtimebuddy** [comment]
The Application has a Ticker instance built in and you should use that: `app.ticker.add()`. I think that a lot of the race condition stuff you’re seeing is because of this. Also the Ticker add method had a priority in case you have something that needs to run before rendering.

**Comment by npx** [comment]
Using the Application Ticker (as I stated in my original report) I get the behavior I describe, meaning, I do not see the complete animation, as pixi is freezing up in the beginning! 
Hence I am reporting!

I uncommented the app ticker and used my own to delay the start. I could as well put the `setTimeout` around adding my update function to the app ticker.

**Comment by ivanpopelyshev** [comment]
"freeze" word associate in my brain with "texture uploading lag". Please search docs for PIXI.prepare. I cant describe it in two words , its a big topic where no ideal solution exist due to relation to both loading resources and starting the stage, and it was discussed many times.

**Comment by npx** [comment]
Even using pixi prepare the same behavior occurs.

**Comment by ivanpopelyshev** [comment]
Maybe its shader compilation? Try render graphics rect once before you start the ticker.
