### ISSUE TITLE
FilterSystem: filterArea is considered legacy, but is still used in filters like the GlowFilter

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6268]
```js
class PIXI.FilterSystem {
   pop() {
        // ... to line #273

        // only update the rect if its legacy..
        if (state.legacy)
        {
            const filterArea = globalUniforms.filterArea;

            filterArea[0] = state.destinationFrame.width;
            filterArea[1] = state.destinationFrame.height;
            filterArea[2] = state.sourceFrame.x;
            filterArea[3] = state.sourceFrame.y;

            globalUniforms.filterClamp = globalUniforms.inputClamp;
        }
   }
}
```

In the above snippet, we are updating the `filterArea` uniform if the filter is legacy. However, on my machine, constructing a `new PIXI.filters.GlowFilter(...)` has `legacy=false`. The glow filter actually uses the `filterArea` uniform. I can't set its legacy flag to false manually due to its side effects; however, on removing the `state.legacy` condition for the filter-area, my glow filter works properly. Without that, it fills my objects with the glow color if its inner-strength is non-zero.

Is this a bug, or there is a problem in the glow filter?

**Comment by ivanpopelyshev** [comment]
`legacy` mode is detected by which attributes filter accept.

When first v5 filters were made, they were completely incompatible with v3 and v4. I've changed uniforms around and added legacy mode to support old stuff.

**Comment by cha0s** [comment]
I apologize if this is a stupid question, but I'm trying to get into shaders/filters with Pixi and I'm seeing this filterArea uniform used for e.g. pixelation and seeing that it's considered "legacy", so my question is, what is the "right" (or, recommended) way to accomplish the same thing?
