### ISSUE TITLE
Add support (and documentation) for proper npm/yarn linking and building

### ISSUE THREAD

**Issue by mobileben** [pixijs/pixi.js#6269]
I'm currently using `pixi.js` 5.2.0 and my project uses Typescript and Webpack. 

I encountered an issue in pixi-sound (https://github.com/pixijs/pixi-sound/issues/119), where I was having issues using pixi-sound in my project due the `sound` object existing, but seemingly not initialized properly. It appeared as if there was some out of order initialization occurring.

I was using my own version of pixi.js built from source and linked in using `npm link`.  When I unlinked and installed via `npm install --save pixi.js` it worked. I did some experiments in manually copying over my built version into node_modules and had different levels of success. I believe the problem relates to the scoped pixi packages. I was linking only the built bundle (bundles/pixi.js directory).

Overall, the documentation is good about explaining how to install and build pixi.js. However it is a little more difficult to figure out how to actually build and then use/test the results locally. In particular, I ran a folder diff on my project's node_modules with pixi.js being linked versus installed. The main difference came down to the scoped pixi packages (since I did run an install, node_modules contained the installed version of the pixi packages) and the actual pixi.js directory had less files (and of course different contents within the files). Within the built directories, there are a bunch of symbolic links within the generated scoped packages. So it is not straightforward to  `npm link` each of the scoped packages.  So perhaps as part of the build process (or a different script), it can perhaps create another directory structure which would play nicely with npm linking?

It would be beneficial to have clearer and better support for how to `npm link` as well as build and debug any mods one is attempting on pixi.js. I experimented quite a bit to figure out how I could npm link my built version into my project (I documented it here https://www.html5gamedevs.com/topic/43682-best-way-to-test-fork-of-pixijs). But now, based on the problem I ran into with pixi-sound, it seems while what I did worked, it doesn't play nicely with the scoped pixi packages. 

I would also guess this would make it easier for people to contribute, because it would be far easier to work with and test ones changes.

@bigtimebuddy recommended that I open an issue related to this.

Please note, I'm a C++ game guy trying out HTM5 games. So  am woefully on the steep side of the learning curve on building JS stuff. Hence I could be doing things that are ... well ... dumb.

**Comment by ivanpopelyshev** [comment]
> Please note, I'm a C++ game guy trying out HTM5 games. So am woefully on the steep side of the learning curve on building JS stuff. Hence I could be doing things that are ... well ... dumb.

You can also use vanilla JS, no modules. Most of my plugins are built with tsc, concatenation, no imports/exports. If I use modified pixi, I just copy or link the `bundles/pixi.js/dist/pixi.js`

Also, if you want to make fast changes, you dont need to change the main bundle.

```js
PIXI.Sprite.prototype.render = function(renderer) { ... }
```
