### ISSUE TITLE
AnimatedSprite.onFrameChange fire twice at last frame

### ISSUE THREAD

**Issue by TotooriaHyperion** [pixijs/pixi.js#6271]
### Expected Behavior
every frame fire once during one play.
### Current Behavior
last frame fire twice
### Possible Solution
not sure, but the bug lies on gotoAndStop.
Assuming you have 8 keyframes, then in gotoAndStop, where you save this.currentFrame as previousFrame, then this._currentTime updated, thus when you finished the last frame, the getter of currentFrame will first return 0, and when compare, return 7. Compare 0 to currentFrame triggers one more updateTexture with frameNumber 7.
reverse play has same problem.
the previousFrame read from this.currentFrame is 7, but after
```javascript
this._currentTime = frameNumber;
```
this.currentFrame is 0, thus trigger one more updateTexture with frameNumber 0.
### Steps to Reproduce
simply do a keyframe animation, add onFrameChange handler, then you got the result
![image](https://user-images.githubusercontent.com/16434801/70430923-cc2b9600-1ab6-11ea-8a35-dd2ce4eabfd7.png)

### Environment

- **`pixi.js` version**: 5.2.0
- **Browser & Version**: Chrome 78.0.3904.108
- **OS & Version**: mac os 10.14.5
- **Running Example**: _url_

**Comment by TotooriaHyperion** [comment]
current solution:
```typescript
export default class Patched extends AnimatedSprite {
  triggerdFrame = -1;
  speed = 1;

  constructor(
    textures: PIXI.Texture[] | PIXI.AnimatedSprite.FrameObject[],
    autoUpdate?: boolean,
  ) {
    super(textures, autoUpdate);
    this.loop = false;
    this.onFrameChange = (frame: number) => {
      // fix: https://github.com/pixijs/pixi.js/issues/6271
      if (this.triggerdFrame === frame) {
        return;
      }

      this.triggerdFrame = frame;
      this.emit("frameChange", frame);
    };
    this.onComplete = () => {
      if (__DEBUG__) {
        console.log("onComplete", this.name);
      }
      this.emit("complete");
    };

    this.on("frameChange", (frame: number) => {
      if (__DEBUG__) {
        console.log("onFrameChange", frame, performance.now(), this.name);
      }
    });
  }
  in() {
    this.stop();
    this.emit("frameChange", 0);
    this.animationSpeed = this.speed * 1;
    this.play();
  }
  out() {
    this.stop();
    this.emit("frameChange", this.textures.length - 1);
    this.animationSpeed = this.speed * -1;
    this.play();
  }
}
```

**Comment by bigtimebuddy** [comment]
PR welcome to fix this. Would be good to get a unit test for it.
