### ISSUE TITLE
AnimatedSprite's private method "update" missing from TS definitions.

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/pixi.js#6272]
If you set an AnimatedSprite's `autoUpdate` flag in the constructor as `false` you need access to the `update(dt)` method that is private and the .TS definition doesn't include it.

### Expected Behavior
to be able to call `update(dt)` from class that extends AnimatedSprite

### Current Behavior
You can't call update nor check the `_autoUpdate` flag.

### Workarround
In a class that extends AnimatedSprite:

```ts
    customUpdate(dt: number) {
        if ((<any>this)._autoUpdate === true) {
            console.warn("You called the customUpdate of an Animated Sprite that is running in auto mode. Nothing will happen but you probably shouldn't be doing this.");
        }
        else {
            if (this.playing) {
                (<any>this).update(dt); //Uglt hack to be able to use the private method
            }
        }
    }
```

- **`pixi.js` version**: 5.2.0

**Comment by ivanpopelyshev** [comment]
TS is generated from jsdoc. Add jsdoc to it.

**Comment by miltoncandelero** [comment]
#6464 happened <3
