### ISSUE TITLE
[RFC] Emit `upload` when Resource has been uploaded to the GPU

### ISSUE THREAD

**Issue by Teoxoy** [pixijs/pixi.js#6276]
I have been using the prepare plugin as an alternative to getting notified when a resource has been uploaded to the GPU. The prepare plugin uses the ticker to check if the resource has been uploaded or not and I think a better way to do this is to have the resource emit an event.

Is there a better way to achieve this and I'm missing it?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/TextureSystem.js#L288

Hack it.

`PIXI.systems.TextureSystem.prototype.updateTexture = ...`

We won't add that thing to vanilla pixi for sure because "events inside render() method" can be a bad idea. Probably.

**Comment by Teoxoy** [comment]
Thanks for the tip! I ended up just creating a new class that extends the resource.
If someone else needs this in the future here is the code:
```ts
class CanvasResource extends PIXI.resources.CanvasResource {
    public upload(renderer: PIXI.Renderer, baseTexture: PIXI.BaseTexture, glTexture: PIXI.GLTexture, source: HTMLCanvasElement): boolean {
        const res = super.upload(renderer, baseTexture, glTexture, source)
        console.log('loaded')
        return res
    }
}
```

**Comment by Teoxoy** [comment]
Hmm, I see what you meant with

> events inside render() can be a bad idea

In the example above `console.log('loaded')` works but I've tried callbacks, promises and event emitters that in turn would call a complicated function and everything hangs.

I think why it happens is that I end up in a situation where I tell PIXI to render but it's not yet done rendering the previous frame.

I will just stick with the prepare plugin which watches on every ticker tick if the resources have been loaded.
