### ISSUE TITLE
marker sprite is not clickable after leaflet draw

### ISSUE THREAD

**Issue by novaknole** [pixijs/pixi.js#6277]
Hey. 

I am using this plugin and also leaflet-draw plugin. When drawing sprites, each one of them is clickable. Clicks work fine. Now, after I draw leaflet-draw's one of the inputs(let''s say circle) which happens to include some of the marker sprites, those that got included inside this circle are no more clickable. Nothing at all.

How Do I achieve this so that they are still clickable?

```
pixiContainer = new PIXI.Container();
pixiContainer.interactive = true
pixiContainer.buttonMode = true;
 let markerSprite = new PIXI.Sprite(textureImage);
 markerSprite.interactive = true
 markerSprite.buttonMode = true
 markerSprite.on('click', _self.clickedMarker.bind(this, markerSprite)) 
 pixiContainer.addChild(markerSprite);
```

Now, when I draw circle from leaflet-draw's, maybe its layer is getting put on that pixiContainer. no idea. and sprite is not clickable anymore. I mean that when I click, i should be getting console.logs but not anymore. Before drawing leaflet-draw's circle, it works fine. I know this might be related to what leaflet-draw does, but maybe you can think of any easy workaround.

- **`pixi.js` version**:  5.2
- **OS & Version**: _e.g. Ubuntu 18.04_

**Comment by ivanpopelyshev** [comment]
One of possible problems are if you use `getLocalBounds()`, or `width`/`height` properties from click handler.

Need more info, please reproduce minimal example.

**Comment by ivanpopelyshev** [comment]
Here's the class to debug: https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/TreeSearch.js

You can just copy whole class, make your own instance and do `renderer.plugins.interaction.search = mySearch`, then you can change the method and see the result.

**Comment by novaknole** [comment]
I am not using none of those you mentioned. It's just simple thing. imagine I have a map loaded on whole page. Then I use pixi to draw interactive sprites and they get shown on the map. Then map has a drawing method which draws a circle. if this circle included any of the sprite, boom, sprite is not clickable anymore until i remove that circle again.


Reproducing this example will be kind of time consuming as i am using

leaflet-pixioverlay
leaflet-draw
leaflet
pixi.js

all of those together.

I think circle's layer which is not related to pixi gets put on the sprite and sprite looses ability of being clicked on. Can't find any solution :(

**Comment by ivanpopelyshev** [comment]
It should work. Unfortunately, my telepathy does not work in your case, you have to actually make a demo. Then if it doesn't work again, a minimal demo.
