### ISSUE TITLE
https://pixijs.io/examples/#/sprite/basic.js

### ISSUE THREAD

**Issue by Vi-jay** [pixijs/pixi.js#6280]
https://pixijs.io/examples/#/sprite/basic.js

_Originally posted by @djmisterjon in https://github.com/pixijs/pixi.js/issues/6279#issuecomment-565415054_

Thanks for your response. But I want create AnimateSprite. In the Examples they create AnimateSprite use `PIXI.Loader.shared.add("assets/spritesheet.json").load(setup);
`
But i want do this 
```js
const jsonObj = get json from other way;
PIXI.Loader.shared.add(jsonObj).load(setup);

```

**Comment by ivanpopelyshev** [comment]
Usually its easier to inline spritesheet loader.

https://github.com/pixijs/pixi.js/blob/dev/packages/spritesheet/src/SpritesheetLoader.js#L57

You can do those operations manually:

```js
loader.add('my.png').load(() => {
     let sheet = new PIXI.SpriteSheet(loader.resources['my.png'].texture, jsonData);
     sheet.parse(); // works if number of textures is less than 1000. otherwise you need a callback or increase batch size
});
```

**Comment by bigtimebuddy** [comment]
Good answer. Closing.

**Comment by Vi-jay** [comment]
> Usually its easier to inline spritesheet loader.
> 
> https://github.com/pixijs/pixi.js/blob/dev/packages/spritesheet/src/SpritesheetLoader.js#L57
> 
> You can do those operations manually:
> 
> ```js
> loader.add('my.png').load(() => {
>      let sheet = new PIXI.Spritesheet(loader.resources['my.png'].texture, jsonData);
>      sheet.parse(); // works if number of textures is less than 1000. otherwise you need a callback or increase batch size
>      console.log(sheet.animations);
> });
> ```
> 
> Make sure your json file contains animation arrays and not just a few textures. If there is only
> a collection of textures without animation sequences - you'll have to convert object to array manually.

thanks for a lot . that's  solved my problem
