### ISSUE TITLE
Renderer sets parent back to old value before calling render() on display-object

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6281]
I was having trouble with `getBounds` during a render pass onto a render-texture; I traced it to this part in `Renderer`:

```js
        if (!skipUpdateTransform)
        {
            // update the scene graph
            const cacheParent = displayObject.parent;

            displayObject.parent = this._tempDisplayObjectParent;
            displayObject.updateTransform();
            displayObject.parent = cacheParent;
            // displayObject.hitArea = //TODO add a temp hit area
        }

        this.renderTexture.bind(renderTexture);
        this.batch.currentRenderer.start();

        if (clear !== undefined ? clear : this.clearBeforeRender)
        {
            this.renderTexture.clear();
        }

        displayObject.render(this);
```

If `getBounds()` is called on a display-object, it will re-update its transform with its real parent. We don't want that to happen when rendering to a render-texture.

Was this the intended behavior? Or could we move `displayObject.parent = cacheParent` after calling `displayObject.render`.

**Comment by ivanpopelyshev** [comment]
That's why we have `getBounds(rect, false)`
But yes, you are right, its a bug.

**Comment by govardhan27** [comment]
Hi, @ivanpopelyshev are you still working on this?
If not can I take it up?

**Comment by SukantPal** [comment]
@govardhan27 This will probably be deferred to the issue related to the lack of reentrancy in the renderer https://github.com/pixijs/pixi.js/issues/6203

**Comment by SukantPal** [comment]
@govardhan27 If you would like, you can write a PR though.
