### ISSUE TITLE
Destroy method should have a default `children` parameter

### ISSUE THREAD

**Issue by wss534857356** [pixijs/pixi.js#6282]
When the user does not pass any parameters, `children` should be `true` by default, which can better hide the details of the call to help users get started quickly.
https://github.com/pixijs/pixi.js/blob/46cf0babeb8c900528900da5cfe71d89c18fec32/packages/display/src/Container.js#L609

Like:
```js
const destroyChildren = typeof options === 'boolean' ? options : options == undefined ? true : options.children; 
```

**Comment by bigtimebuddy** [comment]
This is a breaking change feature request and we will not be considered at this time. 

Also, I’d disagree that destroying children is better/easier for users than the default behavior. In general, it’s a better practice to reuse display object when possible so it seems more dangerous to opt-out of destroying all children than to opt-in.

**Comment by wss534857356** [comment]
Do you mean that the same instance object will appear in different containers?

**Comment by djmisterjon** [comment]
hum i am rather ok with this opinion here, where I use some destroy for my dynamics objects, i found annoying to alway need to fill options param..
`this.destroy({children:true})`.
But it true, it a break change.
btw I don't have any context idea where it can be interesting to call a `destroy()` with `children:false` .
Am interesting to see some scenario and context.

**Comment by bigtimebuddy** [comment]
Many objects are containers but have no children: Text, Graphics, etc

**Comment by wss534857356** [comment]
https://github.com/michalochman/react-pixi-fiber/pull/157
My adjustments were adopted, so this breaking change didn't make much sense to me, so I decided to close this issue.
