### ISSUE TITLE
Extract pixels returns image larger then app

### ISSUE THREAD

**Issue by CoenraadS** [pixijs/pixi.js#6284]
### Expected Behavior

If I initialize my app with width: 640; height: 640 then call `app.renderer.plugins.extract.image(app.stage);` I would expect the output image to be 640x640

### Current Behavior
If textures are loaded and places on scene that are larger then 640x640, they are also extracted

![image](https://user-images.githubusercontent.com/5593825/70887486-696a5b00-1fde-11ea-9db7-f75ecdf26b3f.png)

### Possible Solution
Crop the output
### Steps to Reproduce
Add a sprite larger then the app dimensions

### Environment

- **`pixi.js` version**: 5.1.3
- **Browser & Version**: Firefox 71
- **OS & Version**: Windows 10

**Comment by ivanpopelyshev** [comment]
Nope, it takes getLocalBounds() of stage. 

You have to use `renderer.generateTexture` with region param (you can take `app.screen` or `renderer.screen`) then pass that texture to extract, then destroy it because you dont need it anymore.

Yes, we know that its not clear, and we are working on better API for `extract`.

**Comment by croraf** [comment]
@ivanpopelyshev I started using PixiJS couple of days ago. Seems very nice. Keep on with the excellent work!

Today I played with extract and it is really inconvenient. What we as users need is the examples in the docs about how to manipulate it to extract what we want.

First I tried using extract on the `app.stage` container. I was very surprised to see that it takes my entire stage and that there is no easy way to crop it in the local coordinates. The image I got has completely different origin, and it is impossible to extract the wanted area. 

Then I tried extracting only one Sprite that was added to the `app.stage` container (at some location different than origin). But it does not extract it in its local coordinates, but seems to extract the portion of the visible view from its (0, 0) with the size of the targeted Sprite. The extracted portion seems to be unusable, as it is a just a transparent image, as the Sprite is not rendered in this portion.

P.S. Perhaps you can keep this issue open until examples in the docs are added, or the API is improved.
