### ISSUE TITLE
Click event's preventDefault not being called properly in Edge on touch-capable laptop

### ISSUE THREAD

**Issue by irongaze** [pixijs/pixi.js#6285]
### Expected Behavior
Dragging (via mouse) within Pixi canvas has no effect.

### Current Behavior
Dragging withing Pixi canvas causes the whole canvas to be dragged as a static image (presumably normal canvas dragging behavior in edge?)

### Possible Solution
My guess is that there's some timing issue or state issue that is preventing Pixi's interaction manager from eating the mouse events properly.  Am digging into the source code to try and find what might be wrong.

### Steps to Reproduce
Load example below, drag on any part of the game scene repeatedly.  After a few tries, you should see a screen snippet dragging with your cursor.

### Environment

- **`pixi.js` version**: 5.2.0
- **Browser & Version**: Edge 44.18362.449.0
- **OS & Version**: Windows 10 - latest
- **Running Example**: https://app.lexercise.com/mylexercise/index/index/demo/k2l4hfh4b1fhx8xt

I've tried using the InteractionEvent#stopPropagation method, but it has no effect on this problem.  Seems to be a low-level issue.

![drag-bug](https://user-images.githubusercontent.com/1086959/71026638-a403ee80-20d7-11ea-9def-07d1e5d10a72.jpg)

**Comment by ivanpopelyshev** [comment]
Edge, 44.18362.449.0 . windows 10 , everything works fine.

As for preventing default behaviour,

We call `preventDefault` only on mousedown events.

https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/InteractionManager.js#L1077
https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/InteractionManager.js#L67

@themoonrat @eXponenta any ideas?

**Comment by irongaze** [comment]
Have confirmed that dragging a blank canvas, without Pixi being loaded at all, is default Edge behavior.  Am now playing around with DOM to verify that eating pointerdown events actually prevents this dragging.  Thanks for the pointers to the relevant PIXI source code, will see what I can find.

> P.S. I was a bit startled when demo told me "Thank you for checking out the bug"

Haha, we have a demo feature for our games platform that lets us narrate a bit at the start of the demo.  :-)

**Comment by irongaze** [comment]
OK, so here's the problem:

https://github.com/pixijs/pixi.js/blob/c2b582c965825cecd6b9c93267b568cb17828a9d/packages/interaction/src/InteractionManager.js#L1689

The test above fails due to both `supportsPointerEvents `and `event instanceof window.PointerEvent` being true, so the event's isNormalized flag is not set.  This leads the code here:

https://github.com/pixijs/pixi.js/blob/c2b582c965825cecd6b9c93267b568cb17828a9d/packages/interaction/src/InteractionManager.js#L1071

To skip the preventDefault call.  The event goes through, Edge says "Wheee!  Let's drag some f'n CANVAS BABY!" and my customers get cranky.  Am still digging into what supportsPointerEvents implies in the InteractionManager, but that's the ultimate issue.  Any ideas on what the best fix might be?

**Comment by irongaze** [comment]
@ivanpopelyshev, another thought - my dev laptop has a touch-capable screen.  Even though I'm interacting with the mouse exclusively while testing, is it possible that's what's causing it to fail for me and work for you?

**Comment by ivanpopelyshev** [comment]
Yes, usually something goes wrong with touch devices.

While our interaction specialists think how to answer to your request, you can override any functions inside InteractionManager simply by specifying `renderer.plugins.interaction.myFunction = ...;` - no need to rebuild whole pixijs.

**Comment by irongaze** [comment]
I'm not clear on how to patch this one out.  If I replace `onPointerDown` by running `renderer.plugins.interaction.onPointerDown = function() { ... patched code ... };`, it has no effect because by the time I have a renderer, the interaction manager is already created, and has set up event handling with pointers to its original onPointerDown function.  I could patch `normalizeToPointerData` to always set `isNormalized`, but that seems like it might have knock-on issues.

Is there some way to modify the InterationManager prototype before PIXI instantiates it?

**Comment by irongaze** [comment]
Ah, got it:

> PIXI.interaction.InteractionManager.prototype.onPointerDown = <my patched function>

That did it.  I simply removed the check for isNormalized, and that seems to have fixed the problem.  Seems like an easy fix overall - I can't see the harm in preventing default handling for events that aren't normalized.  Hard to believe that's a performance optimization, but I'm sure there is some reason for that check.

Regardless, thanks again Ivan for being the most responsive and helpful open source developer I know.

**Comment by ivanpopelyshev** [comment]
Thanks for kind words!

That means guys have one more case to take into account for that logic in InteractionManager.

You can remove the demo, because, like you said, it should be easy to reproduce just with empty pixi canvas.
