### ISSUE TITLE
Graphics rendering is slow in Firefox on macOS Catalina

### ISSUE THREAD

**Issue by redbeardmickey** [pixijs/pixi.js#6286]
### Current Behavior
This example runs smoothly in Firefox on macOS Mojave but is very sluggish on macOS Catalina. Both running Firefox 71.0.
https://pixijs.io/examples/?v=v5.2.0#/graphics/dynamic.js

### Environment
- **`pixi.js` version**: _5.2.0_
- **Browser & Version**: _Firefox 71.0_
- **OS & Version**: _macOS Catalina 10.15.2_
- **Running Example**: _https://pixijs.io/examples/?v=v5.2.0#/graphics/dynamic.js_

**Comment by ivanpopelyshev** [comment]
Try remove the antialias?

```js
const app = new PIXI.Application({ antialias: false });
```

**Comment by bigtimebuddy** [comment]
Are you sure that Catalina, if on a laptop, is plugged in?

**Comment by redbeardmickey** [comment]
Thanks @ivanpopelyshev @bigtimebuddy. This issue seems to be caused by an add-on ([Privacy Possum](https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/)). After removing it and refreshing all settings, everything works fine.
