### ISSUE TITLE
Is there an official 2D camera extension?

### ISSUE THREAD

**Issue by sbfkcel** [pixijs/pixi.js#6289]
Just need some simple functions, rotate, scale, and shift.
If not, directly control if the container is too rough.

**Comment by lekzd** [comment]
@sbfkcel Did you try pixi-viewport plugin https://davidfig.github.io/pixi-viewport/?

**Comment by Levelleor** [comment]
@lekzd is it possible to get rid of the easing when mouse released?

**Comment by lekzd** [comment]
@Levelleor didn't do this before, I can't have a good suggestion for this stuff(

**Comment by bigtimebuddy** [comment]
**pixi-viewport** is a good suggestion. If you have feature suggestions, please provide feedback to that repo: https://github.com/davidfig/pixi-viewport/
