### ISSUE TITLE
Extension "OES_standard_derivatives" is supported, but it doesn't work when trying to use it

### ISSUE THREAD

**Issue by jnsmalm** [pixijs/pixi.js#6291]
I want to use this WebGL extension called "OES_standard_derivatives", which by me seems to be supported by almost everything.

I have it working in Chrome without any issues, but running it in Safari gives me an error "ERROR: 0:1: 'GL_OES_standard_derivatives' : extension is not supported". That's weird, because the browser tells me it's supported when I use the code below:

```javascript
if (app.renderer.gl.getExtension("OES_standard_derivatives")) {
  console.log("GL_OES_standard_derivatives is supported!")
}
```

When I was writing a small example to reproduce this error using jsfiddle I realized I got the same error in Chrome as I got in Safari (using the exact same code). Something is fishy here :-) Can someone help me trying to figure out what is going on here?

* It works in Chrome when running it locally.
* It doesn't work in Safari when running it locally.
* It doesn't work in Safari or Chrome when running it in jsfiddle.

Below is the full example, the expected output is a red rectangle in top-left corner and the background should be magenta.

```javascript
PIXI.settings.PREFER_ENV = PIXI.ENV.WEBGL1

let app = new PIXI.Application({
  width: 300, height: 300, backgroundColor: 0xff00ff
})

if (app.renderer.gl.getExtension("OES_standard_derivatives")) {
  console.log("GL_OES_standard_derivatives is supported!")
}

document.body.appendChild(app.view)

let graphics = app.stage.addChild(new PIXI.Graphics())
graphics.beginFill(0)
graphics.drawRect(0, 0, 100, 100)
graphics.endFill()

var vert = `
#version 100

attribute vec2 aVertexPosition;
attribute vec2 aTextureCoord;

uniform mat3 projectionMatrix;

varying vec2 vTextureCoord;

void main(void){
   gl_Position = vec4((projectionMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);
   vTextureCoord = aTextureCoord;
}`

var frag = `
#extension GL_OES_standard_derivatives : require

precision mediump float;

void main() {
  gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}`

graphics.filters = [new PIXI.Filter(vert, frag)]
```

The same example in jsfiddle can be found at https://jsfiddle.net/4vf26ujy/

**Comment by eXponenta** [comment]
#extension GL_OES_standard_derivatives : enable

Then use macros 

#ifdef GL_OES_standard_derivatives
   //my code with fwidth
#endif

https://developer.mozilla.org/en-US/docs/Web/API/OES_standard_derivatives

**Comment by jnsmalm** [comment]
Thanks, this helped a lot!
