### ISSUE TITLE
The size of the Text with shadow is not correct.

### ISSUE THREAD

**Issue by pagoru** [pixijs/pixi.js#6297]
### Expected Behavior
![image](https://user-images.githubusercontent.com/1551265/71534302-3c7f4780-28fe-11ea-9d45-9ec4ab0f4216.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/1551265/71534327-62a4e780-28fe-11ea-9342-4d7851e4717c.png)

### Possible Solution

The bounds from the text are not the rendered one.

### Steps to Reproduce

```JS
const _text = new PIXI.Text('test', {
    fontFamily: X,
    fontSize: 16,
    strokeThickness: 0,
    dropShadow: true,
    dropShadowAngle: Math.PI/4,
    dropShadowDistance: 24
});
```
I know, the dropshadow is 24, but you can only see a 16px shadow.

### Environment

- **`pixi.js` version**: 5.1.0
- **Browser & Version**: 79.0.3945.88 (Build oficial) (64 bits)
- **OS & Version**: Windows 10
- **Running Example**: --

**Comment by ivanpopelyshev** [comment]
> I know, the dropshadow is 24, but you can only see a 16px shadow.

Math.PI/4 is direction, and `24 / sqrt(2)` is something like 17. 

We're on holidays right now, if you cant wait, try to debug https://github.com/pixijs/pixi.js/tree/dev/packages/text/src , its related to canvas2d API, almost no webgl usage there. 

Yes, we periodically find strange things in our Text implementation. I can't analyze whether the issue exist right now but I won't be surprised if you are right. Can you elaborate, why did you specify that kind of dropShadowDistance? Shouldn't expected behaviour be different for that big shadow?

**Comment by themoonrat** [comment]
For a quick fix, try setting trim to true

**Comment by pagoru** [comment]
@ivanpopelyshev I can wait, don't worry and merry xmas! :D

> Math.PI/4 is direction, and 24 / sqrt(2) is something like 17.
- My bad!
> Can you elaborate, why did you specify that kind of dropShadowDistance? 
- I try it with only 16, but never worked, so I started scaling numbers. I'm working in a project with precise pixels, so 24 is 16 + 8, 16 is the size of the font. But I don't understand why 8 is a single pixel in the shadow if the font is 16 pixels, doesn't make any sense(?)
> Shouldn't expected behaviour be different for that big shadow?
- Yeah, I mean, if the font is 16 pixels, the shadow with only one pixel, needs to be one pixel not 24, no?
> Do you think that shadow can be bigger than original text and its size is dropShadowDistance?
- I don't really understand the behavior, but yes, the size of the shadow is the dropShadowDistance, but if I only put 1 px, the shadow doesn't appear.

Maybe the css solution is more easy to implement?
x offset, y offset, and if you need blur, new param?
```css
text-shadow: 2px 2px 5px red;
```
```js
const _text = new PIXI.Text('test', {
    fontFamily: X,
    fontSize: 16,
    strokeThickness: 0,
    dropShadow: true,
    dropShadowBlur: 2
    dropShadowX: 2,
    dropShadowY: 2,
    //or
    dropShadowPosition: new PIXI.Point(2, 2)
});
```
maybe?



@themoonrat 
> For a quick fix, try setting trim to true
- I think it's worse, because it's a crop and every text has his own bounds... :S But thank you!!
