### ISSUE TITLE
After destroying an object

### ISSUE THREAD

**Issue by aolsx** [pixijs/pixi.js#6299]
I found out when I was using tween

```
var Container = new PIXI.Container();
.....
.....
Container.destroy({children:true});
.....
if(Container._destroyed){
  stopTween()
}

```
-------------------------------------
**These values will give an error message {width，height，..} [TypeError: ..]**
```
{
   width:[TypeError: Cannot read property 'scale' of null
    at Container.prototypeAccessors.scale.get (webpack-internal:///./node_modules/@pixi/display/lib/display.es.js:1040:31)
    at Container.prototypeAccessors.width.get (webpack-internal:///./node_modules/@pixi/display/lib/display.es.js:1851:21)
    at Container.invokeGetter (<anonymous>:1:142)],

height:[TypeError: .......]
.....
 _destroyed: true,  //  OK
}
```
Does this affect performance？

**Comment by ivanpopelyshev** [comment]
What exactly?

**Comment by aolsx** [comment]
> What exactly?

Many values will give error messages [TypeError：..]

**Comment by ivanpopelyshev** [comment]
Those aren't values, those are calculated properties, and objects inside container/sprite are destroyed, so things like `get x() { return this.transform.position.x};` will fail because there's no `transform` anymore :)
