### ISSUE TITLE
Congratulations to ALL the Amazing people behind Pixi.js

### ISSUE THREAD

**Issue by inglesuniversal** [pixijs/pixi.js#6300]
The more I use Pixi.js the more I fall in LOVE with it!!!

Where can I find the best ONLINE resources for the latest training or reference guide.

The book you suggest was printed in 1915 or so... Is there a more up to date reference or training manual?

Best regards and happy holidays!

**Comment by djmisterjon** [comment]
hum , You can add a google file filter to get all pdf related to pixijs (free and paid)
https://www.google.com/search?lr=&hl=fr&as_qdr=all&ei=G48JXtSsM-i0ggf-oay4Bw&q=filetype%3Apdf+pixijs&oq=filetype%3Apdf+pixijs&gs_l=psy-ab.3...1706.2763..3129...0.0..0.77.596.9......0....1..gws-wiz.JDveOjjqrg4&ved=0ahUKEwiUpqrf1dzmAhVomuAKHf4QC3cQ4dUDCAs&uact=5

Youtube have also a lot of fan video with pixijs stuff
https://www.google.com/search?q=pixijs&lr=&hl=fr&tbm=vid&source=lnt&tbs=srcf:H4sIAAAAAAAAANOuzC8tKU1K1UvOz1XLKMnNMU1PzE1NSS0rBouUlGeWlKQWgdnJWUCp3Pw8MCexvLw8sSgFogqoIbM0F8wEADprAj1QAAAA&sa=X&ved=0ahUKEwiH9pCE1tzmAhWIiOAKHRNRDdIQpwUIIQ&biw=1502&bih=750&dpr=1.25

You have also a wiki in github
https://github.com/pixijs/pixi.js/wiki
