### ISSUE TITLE
Filter padding should be additive

### ISSUE THREAD

**Issue by laino** [pixijs/pixi.js#6303]
### Expected Behavior

Since each filter sees the result of calculations of the previous one, filter padding should be calculated additively. 

### Current Behavior

Right now the maximum padding is used. If you had 2 outline filters for instance, the second filter would get cut off.

https://github.com/pixijs/pixi.js/blob/873b65041bd3a5d173b0e0e10fa93be68bc033d9/packages/core/src/filters/FilterSystem.js#L194

### Possible Solution

I'd be all for including filter padding in the bounds calculation. Then other code wouldn't have to worry about filter padding anymore. For instance ``cacheAsBitmap = true`` will cut filters off if they're on a child element, because it doesn't take filter padding into account properly at all (there are multiple issues with how it calculates those).

### Environment

* **`pixi.js` version**:  5.20

**Comment by ivanpopelyshev** [comment]
> Right now the maximum padding is used. If you had 2 outline filters for instance, the second filter would get cut off.

Well, we need better constomizable behaviour, however, its the first time I see combining two paddings on same element. Do you happen to know if that was the case for Adobe Flash? I can test it in a week when I go back to my work after holidays :)

**Comment by ivanpopelyshev** [comment]
I think that padding is so that there's no chance that "+" there will fix it. We need to customize it. That's one of reasons I'm waiting on #6255, I just don't know yet how to make custom padding.

**Comment by laino** [comment]
Eh... adding padding should fix it. In my case I had an outline filter + glow filter.

The outline filter adds 2 pixels and the glow filter 6 on top of that. So make that padding 8.

**Comment by laino** [comment]
Just to illustrate the issue:

<img src="https://i.imgur.com/ZFDQRkn.png"></img>

Each rectangle has 2 blur filters chained, each with a radius of 10 and a padding of 10.
The left rectangle used the maximum padding, the right one calculated padding additively.
