### ISSUE TITLE
How do I place multiple Sprites in TilingSprite, which can be moved like a picture?

### ISSUE THREAD

**Issue by Vi-jay** [pixijs/pixi.js#6305]
How do I place multiple Sprites in TilingSprite, which can be moved like a picture?
Please help me.

**Comment by Vi-jay** [comment]
Now i write like this.
I set a mask for the container and let the sprite move inside .
```js
 const sprites = [logo, logo2];
    app.ticker.add(() => {
        sprites.forEach((s) => {
            if (s.y < -s.height) {
                const last = sprites.pop();
                s.y = last.y + last.height;
                sprites.unshift(last);
            }
            s.y--;
        })
    })
```
How to do better？

**Comment by eXponenta** [comment]
Tiling Sprite use custom shader for self tiling, you can't do it from separate tiles.

There's a few methods:
1. Your implementation
2. Render sprites to texture and create TiledSprite
3. Use Graphics#begonTextureFill

**Comment by Vi-jay** [comment]
> TilingSprite used custom shader for self tiling, you can't do it from separate tiles.
> 
> There's a few methods:
> 
> 1. Your implementation
> 2. Render sprites to texture and create TiledSprite
> 3. Use Graphics#beginTextureFill

thank you for your reply
