### ISSUE TITLE
PIXI.Graphics size not being rendered properly

### ISSUE THREAD

**Issue by krnbatta** [pixijs/pixi.js#6309]
Hi
I have created a codepen that will make it easier to understand my problem: https://codepen.io/krnbatta/pen/PowEGbK

I have a string which represents a maze grid map. I want to draw it using PIXI.js ('@' represents a black cell and '.' represents a white cell)

The string in the example represents the map with 512*512 cells.
Initially, I was drawing a PIXI.Graphics rectangle for each cell. That made it very slow which I didn't expect from PIXI. I read that it is better to use Sprite instead of Graphics but that didn't help much as well. 
So, what I did was I drew straight black lines on a white background and filled only black cells as per '@' in the map string. 
The problem is when I specify size of each cell as 10px, the whole map is displayed fine.
When I change it to 15px, some part of the map is not shown. At 20px, a major chunk is not shown. The map portion is displayed less as I increase the size of the map. Can someone help me with this?

**Comment by eXponenta** [comment]
Use latest pixi or 5.1.5.
It has bounds fix.

**Comment by krnbatta** [comment]
Using the latest pixi.js didn't fix my problem.
