### ISSUE TITLE
PIXI.ParticleContainer not drawing sprites beyond certain amount

### ISSUE THREAD

**Issue by krnbatta** [pixijs/pixi.js#6310]
Hi
I have created a codepen that will make it easier to understand my problem: 
https://codepen.io/krnbatta/pen/JjoMRzb

I have a string which represents a maze grid map. I want to draw it using PIXI.js ('@' represents a black cell and '.' represents a white cell)

The string in the example represents the map with 512*512 cells.
So, what I did is I drew straight black lines on a white background and filled only black cells as per '@' in the map string.
I am using ParticleContainer to draw black cells for optimization purposes. The problem is all cells are not being drawn. Is this a bug?
Compare this to normal PIXI.Container where the whole map is being drawn properly: https://codepen.io/krnbatta/pen/PowEGbK

**Comment by eXponenta** [comment]
1 BaseTexture per 1 ParticleContainer

**Comment by ivanpopelyshev** [comment]
Tiles again?

Archive of tilemap-related thread from https://www.html5gamedevs.com/forum/15-pixijs/

Basically, secret of successful tilemap is :
1. high-level algo - its yours. You choose how to cull tilemap, when to refill, and whether you need chunks.
2. low-level representation: Container/Sprite , `Graphics.beginTextureFill`, pixi-tilemap plugin. All have their own limitations.

You chose ParticleContainer as low-level, its a good thing,, but its docs dont mention that it requires same BaseTexture on all sprites inside, I don't know why, we have to make a PR, we have this "issue" every month.

**Comment by krnbatta** [comment]
> 1 BaseTexture per 1 ParticleContainer.
> And ParticleContaoner works only with Sprites.
> 
> Then PC has 1500 sprites limit by default.
> https://pixijs.download/dev/docs/PIXI.ParticleContainer.html

Suppose I have 15000 sprites. What is better? 
1.) 1 Particle Container with 15000 sprites
2.) 10 Particle Containers with 1500 sprites each

**Comment by krnbatta** [comment]
Hey 
I drew the same thing with plain canvas. Seems like it is much faster. Why is it so?
Any explanation? 
I modified the same codepen: https://codepen.io/krnbatta/pen/PowEGbK
So, to give you an overall picture: I want to visualise pathfinding algorithms. For showing each step, I have to fill certain rectangles, hide previous ones, show path lines. Just basic graphics like rectangles, circles and lines. Interactions like highlighting them on hover and click on nodes, etc. Do you think PIXI is well suited for this job? There will be too many objects or should I just resort to the canvas as there are no fancy sprites or images and only plain graphic objects of different colours.
I started off with PIXI.Graphics inside PIXI.Container.
But this seems to be slow as there can be 100,000 objects with hiding and showing them. So, I am thinking of/doing these things:

- I found Sprites are faster than Graphics. So, I am trying to convert Graphics into texture and thus, sprites. 
- Furthermore, I am trying to keep a single texture for similar graphics objects to use ParticleContainer as it seems faster. 

But I don't think this will improve the situation much. 
Looking at how just the map is drawn so quickly just by canvas, I think I should stick to the canvas and use hacks(like tracing mouse position) for click and highlight events. What do you think?

**Comment by ivanpopelyshev** [comment]
10x1500 and 1x15000 ParticleContainer is the same thing, you can look inside the source code.

There are many ways to do this :) 

1. many Graphics with same GraphicsGeometry
2. decrease quality of curves thgouthg GraphicsUtils, i dont remember where it is, its easy to find, i mentioned many times.

> Looking at how just the map is drawn so quickly just by canvas, I think I should stick to the canvas and use hacks(like tracing mouse position) for click and highlight events. What do you think?

I made 60FPS tilemap with 32x32 size tiles back in 2012-2013.

The thing is, WebGL is difficult. There are many tricks and you have to do extra research if you want it to be significantly faster than canvas when you do tilemaps. It doen'st mean its slower, its just requires extra time to balance things.

As for 100.000 objects - you dont need that many. Good high-level algorithm will cull it down to 4000 with rare refill. Canvas2d is faster because, well, you dont store those objects and you do your culling. In PixiJS there's no culling, if you dont implement it - of course its much slower than culled canvas2d.

**Comment by ivanpopelyshev** [comment]
Did you even try to use https://github.com/pixijs/pixi-tilemap/ ?

**Comment by Pidlik** [comment]
Hi, was about to post a new issue but was wondering if this could be the cause of my problem.
I have made a CodePen that [illustrates my problem](https://codepen.io/Pidlik/pen/gOpXpjW).

> 1 BaseTexture per 1 ParticleContainer.
> And ParticleContaoner works only with Sprites.

So I cannot have multiple textures in one ParticleContainer?
