### ISSUE TITLE
RenderTexture is not working as expected

### ISSUE THREAD

**Issue by UltraCakeBakery** [pixijs/pixi.js#6318]
### Expected Behavior
I want to render a RenderTexture on to my canvas. I have a class called 'PixiSignPresentation' that extends PIXI.Container.

```
class PixiSignContainer extends PIXI.Container
{
    constructor()
    {
        super()

        const test = new PIXI.Graphics()

        test.beginFill( 0xFFFF00 )
        test.lineStyle( 5, 0xFF0000 )
        test.drawRect( 0, 0, 400, 400 )

        this.addChild( test )
    }
}

        this.pixi = new PIXI.Application({
            width: this.$refs.canvas.offsetWidth,
            height: this.$refs.canvas.offsetHeight
        })

        const internalCanvas = new PixiSignPresentation()
        const internalCanvasRenderTexture = new PIXI.RenderTexture.create( 400, 400 )
        const internalCanvasRenderTextureSprite = new PIXI.Sprite( internalCanvasRenderTexture )

        this.pixi.renderer.render( internalCanvas, internalCanvasRenderTexture )

        this.pixi.stage.addChild( internalCanvasRenderTextureSprite )
```

### Current Behavior
It doesn't render anything. Console is clear.

### Environment

- **`pixi.js` version**: _e.g. 5.2-legacy

**Comment by UltraCakeBakery** [comment]
The idea is to have a container in the center that content gets drawn on. I will move that container around. I need it to be a specific size and don't want to use a mask due to some context I won't get in to. I'm pretty sure i'm doing something wrong but I just can't get to wrap my head around it.

**Comment by laino** [comment]
I think 
```js
const internalCanvas = new PixiSignPresentation()
```
should be 
```js
const internalCanvas = new PixiSignContainer()
```
for your example to make sense. With that change it works for me.

Playground: https://www.pixiplayground.com/#/edit/weAMqj2pO1mquMwIl_TT4

**Comment by UltraCakeBakery** [comment]
I imported the container with a different name. The example had a lot of code removed.
The issue was that PIXI never had a canvas to draw on. 

Now its working on my end.

Thanks man. Sometimes you just need a second pair of eyes to spot something haha
