### ISSUE TITLE
VideoResource unused delta parameter

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#6319]
Subj: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/VideoResource.js#L110

Found this while converting to TS.

**Comment by djmisterjon** [comment]
just in case , because you talk about video.
Are your team know video is broken in v4 ?
![image](https://user-images.githubusercontent.com/24865815/72160949-37ee7080-338d-11ea-9fa0-bb585d13c6c5.png)
