### ISSUE TITLE
Bounds Problem In Case Of Negative Width Passed To DrawRect

### ISSUE THREAD

**Issue by andyc365** [pixijs/pixi.js#6321]
### Expected Behavior
Graphics return positive width and height instead of 0s
### Current Behavior
Graphics returned 0 value for both width and height
Please also have a look at the console output for bounds, we got INFINITY, which is also a problem.

![BoundsProblemInCaseOfNegativeWidthPassedToDrawRect](https://user-images.githubusercontent.com/17470555/72149372-f1753200-33dd-11ea-935f-8a92ed5343dc.png)

### Steps to Reproduce
https://github.com/andyc365/for-pixi/blob/master/src/views/Home.vue

### Environment

- **`pixi.js` version**: 5.2.0
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
Do you know if any other 2D renderer supports negative width and height there?

I think that's undefined behaviour.

**Comment by andyc365** [comment]
In PIXI version 5.1.0, I passed negative width or height to Graphics.DrawRect, and got positive bounds from Graphics._bounds, and also got positive value from graphics.width and graphics.height. But In version 5.2.0, that's not the case. Though, in both versions, the rect can be rendered out in canvas.

I need the behavior in version 5.1.0, and it seems to be the correct behavior for the width and height of a rect rendered out. : )

**Comment by ivanpopelyshev** [comment]
Thanks for the info, now we can make a fix.
