### ISSUE TITLE
Drawing Meshes

### ISSUE THREAD

**Issue by krnbatta** [pixijs/pixi.js#6324]
Hi, I am attaching the image of what I want to draw on the Canvas: 
![download](https://user-images.githubusercontent.com/8068341/72211478-017e3600-34f2-11ea-8dc8-091adc9af2ae.jpeg)

This is a mesh which consists of approximately 20k polygons. 
Here is what I did to achieve this:
* Initially, I tried PIXI.Graphics but it was extremely slow that browser hung.
* Then, I drew canvas with `lineTo`, `moveTo`, `stroke` and `fill` commands. This too was slow. And I couldn't draw larger mesh(multiplying each point by a factor say 10)
* Then I divided this into chunks and used `setTimeout` which didn't hang the browser but took a lot of time.
* Then, I used web workers to draw using `offscreenCanvas`. This was relatively fast not great though. I drew 4 transparent canvas on top of each other and divided the task between different workers.

Now, my problem is these are not very good solutions as they don't fully accomplish my goal. I can't pan zoom as if I zoom in, pixels will tear.
I am thinking of using svg node and converting it to canvas without putting it to dom. But 20k `g` nodes in `svg` node. Meh!

Another thing I am thinking is tracing the edge of the polygons. These will greatly reduce the `fill` and might speed up things but writing that algorithm is a challenge in itself. This can be achieved by constructing a planar graph and then forming the outer hull.

I am happy to switch to other platforms. Need not be a browser. 

Here is my requirement:
* Draw the 20k+ objects.
* Ability to pan and zoom.

Is there any suggestion/solution to this?

**Comment by ivanpopelyshev** [comment]
Is canvas2d a requirement, or is pure webgl fine for you?

> This is a mesh which consists of approximately 20k polygons.

When you solve that, you'll be welcomed to "100k bunnies" club.

That's one of a heck task both in browser and in native.

The solution is usually divided to high-level part and low-level. High-level is your algo that parses and divides that thing, low-level is PixiJS Mesh or something else. You have to do both parts acceptable, if one is bottleneck - no change in other will help you.

Unfortunately, I cant help in that because you didn't specify what input do you have. 

We solved like 10 tasks like that with @eXponenta in last several months and every time it was  difficult. I'm not sure that I can help you with 1 post or 10 posts. I think it need actual input, slow demo, and description - whether its your own project or you are doing a job for client.

**Comment by laino** [comment]
> Ability to pan and zoom.

If there's no rotation your entire task can basically be reduced to rendering a 2D vector graphic. Create multiple detail levels of it for zoom levels and also tile it so you can just render the relevant tiles when zoomed in. You're basically solving the same problem as any digital map viewer that doesn't use bitmap graphics.

**Comment by ivanpopelyshev** [comment]
^^^ Here's the trick for your high-level stuff. Low-level can still be pixi meshes.

**Comment by krnbatta** [comment]
Hi @ivanpopelyshev 
The input is array of polygons. Each polygon is array of coordinates. Each coordinate is array of x and y.

**Comment by eXponenta** [comment]
Custom MeshGeometry and Mesh - one you love!
Currently dynamics meshes not support directly.

If you need static mesh - push you triangle to MeshGeometry and draw it. 20k polygons is heavy, but possible.
https://pixijs.download/dev/docs/PIXI.MeshGeometry.html

**Comment by ivanpopelyshev** [comment]
> The input is an array of polygons. Each polygon is an array of coordinates. Each coordinate is an array of x and y.

Convex / concave? With this input `graphics.drawPolygon` should be fastest solution. Unless that data has extra condititions that you dont take into account.

**Comment by krnbatta** [comment]
@ivanpopelyshev Do you thnk graphics.drawPolygon will be faster than 2d canvas ?

**Comment by ivanpopelyshev** [comment]
Yes, because webgl has no antialias. 
No, because triangulation is treated on JS side, and first run will consume some time.

Its all about balance.

**Comment by krnbatta** [comment]
Hi @ivanpopelyshev 
```
meshPolygons.forEach(function (polygonObj) {
          let polygon = new PIXI.Graphics();
          polygon.lineStyle(1, attrs.strokeStyle);
          polygon.beginFill(attrs.fillStyle);
          polygon.drawPolygon(attrs.points);
          polygon.endFill();
          context.stage.addChild(graphics);
});
```
This is the code as you suggested. The browser hangs for 20k polygons

**Comment by krnbatta** [comment]
I tried using turf.js and used the `union` function to get dissolved polygon: https://turfjs.org/docs/#union
Calculating Dissolved polygon takes a lot of time. Once, it is done, I see that 20k polygons are reduced to ~8k. The browser still hangs for PIXI.
I used these 8k polygons by the offscreen rendering of the canvas using multiple web workers. If I draw without scaling, the drawing is almost quickly. But, when I tried to scale by a factor of 10, the browser started crying.
No solution as of now! 😢

**Comment by krnbatta** [comment]
Hi @eXponenta 
Can you point to detailed documentation and example usage of what you suggested?
I don't know much of webGL intricacies and used pixi.js to escape from them. Is this knowledge required?

**Comment by ivanpopelyshev** [comment]
> The browser still hangs for PIXI.

PixiJS is, fortunately, JS. It can be profiled. It is not a black box.

**Comment by eXponenta** [comment]
@krnbatta You need have advanced skills if you decide render more that 2000 polygons :)
Welcome to family!

**Comment by ivanpopelyshev** [comment]
^^^
(zoom out with mouse wheel to see it)
