### ISSUE TITLE
[Question] Is it worth parsing all GLSL filters through an optimiser

### ISSUE THREAD

**Issue by st3v0** [pixijs/pixi.js#6329]
I stumbled upon a nice little repo/article regarding GLSL filter optimisation. It's a few years old now but i was wondering what your thoughts would be around parsing all existing filters through it?

Here's the [Article](http://aras-p.info/blog/2010/09/29/glsl-optimizer/) and [Repo](https://github.com/aras-p/glsl-optimizer).

**Comment by ivanpopelyshev** [comment]
Certainly no. Pixi filters bottleneck is fillrate and texture reads, I didnt see any math-heavy filters.
