### ISSUE TITLE
Too many `any` in official type definition.

### ISSUE THREAD

**Issue by kuanyui** [pixijs/pixi.js#6331]
### Expected Behavior
PIXI.js is a very complex framework and has lots of APIs, but the officially provided type definition (`pixi.js.d.ts`) installed via npm has too many `any`. For example:

```typescript
// Official
declare namespace PIXI {
    class Texture extends PIXI.utils.EventEmitter {
        static from(source: string | HTMLImageElement | HTMLCanvasElement | HTMLVideoElement | PIXI.BaseTexture, options?: any, strict?: boolean): PIXI.Texture;
    }
}
```
It would be much better like this:

```typescript
declare namespace PIXI {
    export interface BaseTextureOption {
        mipmap?: PIXI.MIPMAP_MODES;
        anisotropicLevel?: number;
        wrapMode?: PIXI.WRAP_MODES;
        scaleMode?: PIXI.SCALE_MODES;
        format?: PIXI.FORMATS;
        type?: PIXI.TYPES;
        target?: PIXI.TARGETS;
        alphaMode?: PIXI.ALPHA_MODES;
        width?: number;
        height?: number;
        resolution?: number;
        resourceOptions?: AutoDetectResourceOptions;
    }
    export interface AutoDetectResourceOptions {
            width?: number;
            height?: number;
            autoLoad?: boolean;
            scale?: number;
            createBitmap?: boolean;
            crossorigin?: boolean;
            autoPlay?: boolean;
            updateFPS?: number;
        }
    class Texture extends PIXI.utils.EventEmitter {
        static from(source: string | HTMLImageElement | HTMLCanvasElement | HTMLVideoElement | PIXI.BaseTexture, options?: BaseTextureOption, strict?: boolean): PIXI.Texture;
    }
}
```

### Current Behavior
Those `any` makes development **extremely painful and inefficient**. And unfortunately, `class` cannot be overwritten by custom `.d.ts`. Strongly hope these issues can be solved officially.

### Possible Solution
...Refactoring the project to TypeScript gradually?

### Environment

- **`pixi.js` version**: 5.2.0

**Comment by themoonrat** [comment]
There already is a project in progress for converting the project to TypeScript; some PRs have already been merged into dev for this, and there are PRs outstanding for converting more :)

**Comment by ivanpopelyshev** [comment]
Oh, you done know how deep is that problem :)

v4 typings were handwritten.

v5 typings are generated automatically from jsdoc, specifying interfaces in jsdoc is pain.

Even with a number of modules converted, and with upcoming convertion of "@pixi/core" , we still cant generate proper typings.

**Comment by bigtimebuddy** [comment]
I’m going to close this because we are already working in the effort like @themoonrat. If anyone would like to help the project to convert, let us know.

**Comment by kuanyui** [comment]
Wait, so you're still going to generate .d.ts from jsdoc in the future? This task sounds too painful and not a 

If my ability can afford, I'd know how can I help.

**Comment by bigtimebuddy** [comment]
The JSDoc bit that Ivan mentioned is a temporary solution. It’s not ideal and not perfect. We are working to phase out this and use Typings generated from TypeScript. However, it’s a big code base and takes awhile. We are converting package by package. Currently display and settings are about to be merged. After core is done then we will convert the rest. If you’d like to help, please make a pull request! We could use the help migrating to TS faster.

**Comment by bigtimebuddy** [comment]
Oh and @kuanyui if you aren’t already on PixiJS Salck, send me an message (matt@mattkarl.com) with your email and I’ll add you. We discuss issues like this there.
