### ISSUE TITLE
Feature: Filter's program name should be the filter's constructor?

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6337]
Debugging PixiJS by using WebGL inspection tools like Spector.js is made hard by the fact that shader names are generic, e.g. "pixi-shader-7".

If the name given to each filter's program could be 'this.constructor.name', that would be really helpful!

**Comment by ivanpopelyshev** [comment]
Only if its fourth parameter. If its first or second - you'll have to spend time on threads like https://www.html5gamedevs.com/topic/44542-need-help-of-migrating-shader-from-v4-to-v5/ explaining people why is there suddenly one more parameter :)

**Comment by SukantPal** [comment]
There is no need for parameters.

**Comment by SukantPal** [comment]
@ivanpopelyshev `PIXI.Program` already has a third parameter, and `PIXI.Filter` doesn't pass that. We could just do this in the filter class:

```js
super(program, uniforms, `${this.constructor.name}`);
```

**Comment by ivanpopelyshev** [comment]
Agree

**Comment by SukantPal** [comment]
@ivanpopelyshev Yeah, we could make it the default parameter.
