### ISSUE TITLE
New Spritesheet Animation technique doesnt work : Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by DonBenjo** [pixijs/pixi.js#6338]
Hi there, I'm new to pixijs and want to do a spritesheet animation. There is a way with a for loop but also another one that is also in the doc of Pixijs since version 4.8.8 but it doesn't work and I only get the error: Cannot read property '0' of undefined. What have I done wrong here ?.
I use Pixi 4.8.9 

  let app = new PIXI.Application({ width: 800, height: 450});

    document.body.appendChild(app.view);

    PIXI.loader.add("trollSprite.json").load(setup);

    function setup() {
        let sheet = PIXI.loader.resources["trollSprite.json"].spritesheet;

        animatedSprite =  new PIXI.extras.AnimatedSprite(sheet.animations["troll00"]);

        animatedSprite.animationSpeed = 0.176;
        animatedSprite.play();
    }

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
Place breakpoint here: https://github.com/pixijs/pixi.js/blob/dev/packages/spritesheet/src/Spritesheet.js#L264

Check that json has necessary "animations" field. Check that it has necessary key.

**Comment by DonBenjo** [comment]
Thanks Ivan, that helped. There was no animation field in my Json. The Json was obsolete.

**Comment by ivanpopelyshev** [comment]
You can add it to json manually or use correct format in texturepacker. I don't remember if other packers support this feature.
