### ISSUE TITLE
Buggy quadraticCurveTo !

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#6342]
I experimenting a bubble text box with pure graphics instead of spine2d, am getting buggy and weird behavior with `quadraticCurveTo`

I don't know a word to describe this bug.
It like a `random jiggly spasme` if you drag the bubble very slow.
![bubleissue](https://user-images.githubusercontent.com/24865815/72660344-8e197000-399a-11ea-9119-b24f5694790c.gif)

According to my logic, I expected a more smoother behavior.
I dont think is a math issu, it very experimental sorry for the huge code.
Please take a look only on **line 157**
https://www.pixiplayground.com/#/edit/_J2hUKx2DSNbRmwPlzYgJ

thanks in advance for any help.

**Comment by eXponenta** [comment]
https://pixijs.download/dev/docs/PIXI.html#.GRAPHICS_CURVES

Try enable 'adaptive'

**Comment by djmisterjon** [comment]
thanks , i update the playground with this options , it seem not fix !
but it ok, i use another way and it seem fix...
```js
            BubblePin.quadraticCurveTo(this._curvX, -poy/this._curvY, -pox, -poy);
            BubblePin.quadraticCurveTo(this._curvX, -poy/this._curvY, 0, 0);
```
The spasme disappear with another dynamic values :)
So we can close if your think is was normal behavior.

**Comment by ivanpopelyshev** [comment]
I think we need to dump parameters of that curve when it fails and make a smaller example based on it.
