### ISSUE TITLE
What is the correct way to install type support, pre-5.x?

### ISSUE THREAD

**Issue by Nick-Riggs** [pixijs/pixi.js#6344]
Currently, `npm install pixi.js ` installs version 4.8.9, which doesn't have types defined.

However `npm install @types/pixi.js` installs a version of the types that are stubbed for 5.0+ and also doesn't define types. 

So in this transition period, what is the best way to install pixi.js 4.8+ and type support for it?

**Comment by Nick-Riggs** [comment]
For anyone else running into this, I've temporarily changed my package.json to reference a previous version of @types/pixi.js to get around the problem: `"@types/pixi.js": "^4.8.9",`

**Comment by ivanpopelyshev** [comment]
> However npm install @types/pixi.js installs a version of the types that are stubbed for 5.0+ and also doesn't define types.

Its strange, it should be for 4.8.8

**Comment by ivanpopelyshev** [comment]
Hey, Nick! Long time no hear

**Comment by bigtimebuddy** [comment]
This was my bad, when I published v4.8.9, it pushed to the `latest` dist-tag on npm, it should have been legacy. This has been fixed and v5.2.0 should now be latest.

**Comment by Nick-Riggs** [comment]
@bigtimebuddy Thanks for the quick turn around!

@ivanpopelyshev It has been a long time! You've become quite the pixi.js big shot! :)
