### ISSUE TITLE
Rendering large images using sprite renders only subset of image.

### ISSUE THREAD

**Issue by krnbatta** [pixijs/pixi.js#6353]
Hi, I want to render this self generated image:
![TheFrozenSea](https://user-images.githubusercontent.com/8068341/73145583-7791b800-4102-11ea-94dc-742cf795a044.png)
It is 16384 X 16384 pixels image.
(Originally, at very low scale, the image was 1024*1024 but I wanted high resolution so, multiplied each pixel by 16)
Following is the code:

```
let mapSprite = new PIXI.Sprite.from(`${config.clientAddr}/maps/images/${map.mapName}.png`);
mapSprite.width = gridData.width * config.nodeSize;
mapSprite.height = gridData.height * config.nodeSize;
stage.addChild(mapSprite);
```

Now, the following are the results for different values of the nodeSize:

The size 20 and 16 are so large that I am not able to download the image. But the quality of the image rendered is not very good.

10:
![10-tfs](https://user-images.githubusercontent.com/8068341/73145889-ca1fa400-4103-11ea-93e6-b970d0fc3e8a.png)

8:
![8-tfs](https://user-images.githubusercontent.com/8068341/73145912-f3403480-4103-11ea-96df-2d626bd49cd7.png)

5:
![5-tfs](https://user-images.githubusercontent.com/8068341/73145936-18cd3e00-4104-11ea-96c1-52be675e4761.png)

**Comment by ivanpopelyshev** [comment]
You broke the page.

My brain is currenlyt unavailable but i can advice you to search https://www.html5gamedevs.com/forum/15-pixijs/ , we had an issue like that there. RenderTexture, 1024 size, extract plugin

**Comment by eXponenta** [comment]
For this case u can downscale image to cell size = 1 px , enanle nearest filter for texture and scale it for restoring original size.

**Comment by krnbatta** [comment]
> For this case u can downscale image to cell size = 1 px , enanle nearest filter for texture and scale it for restoring original size.
What you mean is:
```
PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
//and 
let mapSprite = new PIXI.Sprite.from(`${config.clientAddr}/maps/images/${map.mapName}.png`);
mapSprite.width = gridData.width * 1//config.nodeSize;
mapSprite.height = gridData.height * 1//config.nodeSize;
stage.addChild(mapSprite);
```

**Comment by krnbatta** [comment]
> For this case u can downscale image to cell size = 1 px , enanle nearest filter for texture and scale it for restoring original size.
> 
> U can't render BIG texture as one sprite sometimes, because there is a GPU limit of texture size as 16x16k on Modern PC, 4x4k on modern Mobile.
> 
> Look supported texture size on:
> https://webglreport.com/
> 
> If you MUST render 16k image as one, you must split it to 4k images (or less) and create multi-tiled image from it.
> 
> I implemented it in world map (~24 k x 18k):
> https://exponenta.games/games/map/

**Comment by krnbatta** [comment]
> U can't render BIG texture as one sprite sometimes, because there is a GPU limit of texture size as 16x16k on Modern PC, 4x4k on modern Mobile.
> If you MUST render 16k image as one, you must split it to 4k images (or less) and create a multi-tiled image from it.

So, for my 16k x 16k image, I will need 16k images for proper rendering on PC?

> I implemented it in the world map (~24 k x 18k):
> https://exponenta.games/games/map/

I can't understand the proper implementation from public/index.js file. Do you have a public repository pointing towards it?

**Comment by krnbatta** [comment]
> If you MUST render 16k image as one, you must split it to 4k images (or less) and create a multi-tiled image from it.

Is the following correct?
```
PIXI.loader.add([`${config.clientAddr}/maps/images/${map.mapName}.png`]).load(setup);
function setup(){
  let mapTiles = new PIXI.tilemap.CompositeRectTileLayer(0, 
  PIXI.utils.TextureCache[`${config.clientAddr}/maps/images/${map.mapName}.png`]);
  app.stage.addChild(mapTiles);
  for (var i = 0; i <= parseInt(16384 / config.nodeSize); i++) {
    for (var j = 0; j <= parseInt(16384 / config.nodeSize); j++) {
      groundTiles.addFrame(`${config.clientAddr}/maps/images/${map.mapName}.png`, i * 
                                                config.nodeSize, j * config.nodeSize);
    }
  }  
}
```

**Comment by eXponenta** [comment]
@krnbatta Sorry, but it is proprietary project and I can show full implementation publicly.

Technically I load 4 spritesheets asynchronous with tiles by 1024x1024, and add it to container.

> What you mean is:
> 
> ```
> PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
> //and 
> let mapSprite = new PIXI.Sprite.from(`${config.clientAddr}/maps/images/${map.mapName}.png`);
> mapSprite.width = gridData.width * 1;
> mapSprite.height = gridData.height * 1;
> stage.addChild(mapSprite);
> ```
> 
> Have I interpreted what you said correctly?
> 
> Maybe add pixi-viewport for zooming and panning later?

Yep, you can set nearest flag texture specifically.
'mapSprite.texture.baseTexture.scaleMode'
