### ISSUE TITLE
getLocalBounds() causes transform to update, can cause problems in render pass

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6355]
I have found that calling `DisplayObject#getLocalBounds` can mess things up if called while the renderer is rendering. This is because this method will cause a transform update after removing the parent.

In many parts of `@pixi/core`, we use `DisplayObject#getBounds(false)`, which will not update the transform to _include_ the parent's transform. This is an inherent weakness in PixiJS and should be properly documented.

To solve the problem, you _must_ call update-transform after getting the local bounds.

```js
target.getLocalBounds();
target.updateTransform();
```

**However, code like `Container#width` (getter) already uses the `getLocalBounds()` method. This means that trying to access a display-object's width will result in failure of the renderer.**

Maybe we should solve this? @ivanpopelyshev thoughts?

**Comment by SukantPal** [comment]
Also, using `getLocalBounds()` every time results in heavy calculations to the transform. I think it is _very inefficient_ for display-object's width to depend on this.

`getBounds()` prevents `calculateBounds()` via the `this._bounds.updateID == _boundsID` check. However, using update-transform breaks that condition and forces the `calculateBounds`.

_Even there are no real changes in the object's transform, we are causing recalculations of the bounds._

**Comment by SukantPal** [comment]
**Sidenote: Display object bounds are updated only if the transform changes. There is no way to communicate that the inherent dimensions of the object have changed. This is another weakness in PixiJS.**

**Comment by bigtimebuddy** [comment]
Could you please provide a working example (jsfiddle, codepen, etc) of the issue? I’m not sure what you mean by “mess things up”.

**Comment by SukantPal** [comment]
@bigtimebuddy Sorry for the delay, here is a demo: https://jsfiddle.net/ShukantPal/bjc0te8x/7/.

At line 26, the `getLocalBounds()` method causes the Sprite to render at 128x128 instead of the scaled up 256x256 (due to 2x scale of stage).

**Comment by ivanpopelyshev** [comment]
Congratulations, you've stumbled across bug that I cant properly fix for 5 yaers! Yes, using those in render and interaction can .

Unfortunately, fixes that i tried to make a few years ago were too big to merge.

The real fix should remove global matrices update from `getLocalBounds`. If you somehow need to update coords of elements in `render`, then even those fixes wont help, because transform inside `render()`s is a VERY bad architectural idea. In my apps I have separate `prerender()` pass where all filters and caches are measured, and elements re-positioned.

**Comment by SukantPal** [comment]
@ivanpopelyshev There is a simple solution in small lines of code - swap transform in getLocalBounds with another copy. This way update transform will not affect the original transform.

**Comment by ivanpopelyshev** [comment]
> @ivanpopelyshev There is a simple solution in small lines of code - swap transform in getLocalBounds with another copy. This way update transform will not affect the original transform.

You have to swap it in children too.

**Comment by SukantPal** [comment]
@ivanpopelyshev Can’t we use getLocalBounds for children too?

**Comment by SukantPal** [comment]
Override getLocalBounds in Container? That way we can’t keep the two separate.

**Comment by ivanpopelyshev** [comment]
Its based on `calculateBounds`, we need a separate instance of `calculateBounds` or a flag in it, which set of cache fields to use. That way was rejected because of extra params and bigger code.

**Comment by SukantPal** [comment]
Nope. getLocalBounds swaps transform and then Container will use getLocalBounds on children.

**Comment by ivanpopelyshev** [comment]
OK, got it, but that also means extra `Transform` instance for all objects, worse case it gets called from the root.

**Comment by ivanpopelyshev** [comment]
As well as all of its objects inside.
There was also attempt to make it easier for obvious cases: https://github.com/pixijs/pixi.js/pull/3711

**Comment by SukantPal** [comment]
@ivanpopelyshev By keeping things like this way, a recursive transform update occurs every time getLocalBounds is called and then a getBounds after. Even simple things like using width or height properties results in this.

What do you is worse - an extra transform or a recurring recursive transform update? We could even share a transform instance among all display objects for this too.

**Comment by ivanpopelyshev** [comment]
How can we make it work:

1. Take into account my previous PR
2. make getLocalBounds true container implementation separate, with protected name
3. switch transform.worldTransform with matrices from a pool, switch it back in post-section of recursion

**Comment by SukantPal** [comment]
So you will accept a fix, right?

**Comment by ivanpopelyshev** [comment]
Of course I want this thing for several years :) It just wasn't my priority and I waited for some time to collect cases that prove that we need it.
