### ISSUE TITLE
renderer.plugins.interaction.mouse.global bad coords

### ISSUE THREAD

**Issue by s-r-x** [pixijs/pixi.js#6356]
hi ^-^
first of all thanks for such a great library

just migrated from PixiJS 5.0.0-rc.2 to PixiJS 5.2.0

`
const {x, y} = renderer.plugins.interaction.mouse.global;
`

this stuff is used to work before, but now it gives me pair of NaN's

![Selection_031](https://user-images.githubusercontent.com/41614937/73245373-e556e600-41cd-11ea-9198-62c1dce01f40.png)

**Comment by ivanpopelyshev** [comment]
That's the first time I see that and, honestly, no idea how could that happen. Please give more information.

**Comment by eXponenta** [comment]
Must be -99999 before first mouseMoveEvent.

I made test, its works normaly:
https://www.pixiplayground.com/#/edit/FyzfzajVdiAypT1MSC_bY

**Comment by s-r-x** [comment]
unfortunately i don't use pixi.Application

i figured out the problem actually.
x,y coordinates for some reason are always NaN if you pass the custom canvas to the Renderer constructor in v 5.2.0.
but if you omit the view property and do something like document.body.appendChild(renderer.view) - then it works perfectly.

please check this little example with both 5.2.0 and 5.0.0-rc.2  versions:
[https://www.pixiplayground.com/#/edit/cYdlslHuIPAdyxuLj3VwI](url)

**Comment by eXponenta** [comment]
![image](https://user-images.githubusercontent.com/12572222/73260251-95cae700-41da-11ea-9664-842bde6988dc.png)

**Comment by ivanpopelyshev** [comment]
Yes, `new PIXI.Renderer(window.innerWidth, window.innerHeight)` doesnt work anymore, you should use `new PIXI.Renderer({width: window.innerWidth, height: window.innerHeight});` instead

**Comment by s-r-x** [comment]
спасибо)

**Comment by ivanpopelyshev** [comment]
Если хочешь, можешь зайти на https://t.me/gamedevforweb и https://t.me/threejs_ru - там мы помогаем с пикси и с другими штуками по html5-играм на русском.
