### ISSUE TITLE
Typescript Def incorrect for TextStyle.fontWeight

### ISSUE THREAD

**Issue by jonaswalekvist** [pixijs/pixi.js#6357]
Current def: 
`	fontWeight?:string; `

How it shoud be:
`	fontWeight?:string | number; //Example values "bold", "bolder", 100, 400 etc. `

The issue is this:

(I'm guessing a bit because i have not read the whole sourcecode)

I guess that the canvas created is rendering text styles with css. The css property for font-weight is actually a string ("bold", "bolder" etc) or a number (100,300 etc). When the font-weight is set to "100" or "300" (number as strings) it does not work. 

The wrong font is renderd in the canvas. It can't find my loaded fonts. So it defaults to some "TimesNewRomas" like font. 

If i however do this:

`(<any>myPixiText.style.fontWeight) = 600; //I need to type it to <any> to get around the typescript definition. `

It works perfectly. 

As a side note: 
https://pixijs.io/pixi-text-style/
Even in your Text Style editor you set the font weight to a number, but i'm not allowed to because of the incorrect typescript definition.

**Comment by jonaswalekvist** [comment]
Actually after a bit more digging. The problem lies in the updateText function in PIXI.Text. 

The font is set on the 2d context by first doing style.toFontString(). 

I think its this` toFontString();` It creates an invalid font string.


this is my example:

`this._style.toFontString(); //Result: "italic normal 600 48px "Open Sans""`

when this is set to the context the context will actually try to make it into a valid font string and strip the invalid parts resulting in:

`"italic 48px "Open Sans"", `

which as you can see, does not contain my font weight. Then the font is rendered incorrectly because i have loaded an italic 600 font. 


I think a better approch is to set the different style parameters individually instead of bunching them up like this in a string.

**Comment by themoonrat** [comment]
The canvas 'font' property unfortunately only accepts the font string as a whole, so you can't just set individual parameters. 

This is something that should be looked into and fixed, however

**Comment by SerG-Y** [comment]
Hi @jonaswalekvist, can you please provide an example where font renders incorrectly. I think this problem not connected to `this._style.toFontString();` as this function return correct string it's just a bug of chrome and safari (missing font weight component when retrieving font property from Canvas context) only Firefox works well.
