### ISSUE TITLE
Event capture not supported, fine. But capture not even hackable outside of pixi, NOT fine!

### ISSUE THREAD

**Issue by molst** [pixijs/pixi.js#6359]
Hi, I've been stumbling on this problem a couple of times now so I think it's in place to get this clarified once and for all.

I know the capture phase is not supported by pixijs. That's OK for now. However, when I try to catch events this way I would expect it to work properly (pixiCanvas is my renderer's view element):
`pixiCanvas.addEventListener('mousedown' , this.onPointerDownCapture, true);`
` this.on("mousedown" , this.onPointerDown, this);`

When I do this, **onPointerDown** is called **BEFORE** **onPointerDownCapture**, which is extremely annoying because it means I cannot hack around to get any type of capture working as long as pixi is loaded onto the page. And I really have to capture it before in order to have a proper and simple design for my event handling code..

If I recall my last investigation correctly I think that pixi attaches its listeners to the window, the topmost possible object, which I think is the reason why it is so hard to hack around it. If an event is captured there, the only option to have a chance capturing it before pixi is to make a really ugly hack to get my handler added to window before pixi is even loaded. Maybe possible, but that would be really ugly and require a huge inline comment to explain why that has to be done.

Maybe I have missed something fundamental. If so, please let me know. Otherwise my suggestion is that we ensure that pixi never attaches any listeners to elements above its **view** in the page element hierarchy.

**Comment by ivanpopelyshev** [comment]
Hello and welcome!

InteractionManager is known for such tricks. I tried to fight the fact that it attaches automatically just when the `Renderer` is created. I even had a PR that moved it out of Renderer, and one of editions of certain document had an outer interaction: https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop/3199c9a91bc26b60c375e3db3b7faba5ae27376e#custom-application 

Unfortunately, it was rejected. Well, maybe pluggable  interactionManager will appear in next versions, but for now you need something, right?

Good news! PixiJS is not a blackbox. You can just hack that thing. Good luck with it, and do share the code when you make this mod. I need a link to point to when people ask for this question again.

```js
PIXI.interaction.InteractionManager.prototype.addEvents = myAddEvents;
```

https://github.com/pixijs/pixi.js/blob/89324e3223e05a4216b8746a3a630b7760c1deff/packages/interaction/src/InteractionManager.js#L785

Just in case, if you need different algo inside the tree, you can create different `search` element, tree search is a component of InteractionManager.

**Comment by molst** [comment]
Thanks, Ivan, for the fast reply, the code pointer, and for all your great posts that have helped me a lot so far!

I'll try to avoid hacking pixi as much as I can (for a rock solid upgrade process), but I'll let you know if I fall back to replace addEvents!

**Comment by ivanpopelyshev** [comment]
> I'll try to avoid hacking pixi as much as I can (for a rock solid upgrade process)

Don't worry, that part of InteractionManager is rarely changed, and you can just add a comment to your hack that explains what did you do to the future you

**Comment by molst** [comment]
I managed to solve my problem another way, involving attachment of data to the bubbling events. However, still, for the future I think the attachement of capturing event handlers to window and window.document should be revised and changed if possible. I suppose it should be possible to attach them to the renderer view element instead, but maybe there is some reason why it had to be done this way. If so, an explanation here would be great.

**Comment by ivanpopelyshev** [comment]
If there is , I'm sure @themoonrat can clarify that. 

All those events are magic for me, I'm the webgl and architecture guy :)

**Comment by themoonrat** [comment]
Sorry getting late to this @molst 

I believe the reason why we need to capture the windows is for accurate over / out / up events when going in and out of the canvas.

It's actually a bit of a mix where events are attached to. For mouse, you have...

```
window.document.addEventListener('mousemove', this.onPointerMove, true);
this.interactionDOMElement.addEventListener('mousedown', this.onPointerDown, true);
this.interactionDOMElement.addEventListener('mouseout', this.onPointerOut, true);
this.interactionDOMElement.addEventListener('mouseover', this.onPointerOver, true);
window.addEventListener('mouseup', this.onPointerUp, true);
```

So, we need up to be window, so that if you press down, but move the mouse away from the canvas, we still know that the mouse button has been released. And movement, we need that on the window to ensure that move events still work if you have html over the top of the canvas (very common to have a html ui over a canvas). This is only for mouse / pointer events. touch events are all on the interactionDomElement

So it's not something that I'd feel comfortable changing by default in PixiJS, unfortunately. 

InteractionManager does have a public `setTargetElement`, so you can change what that interactionDOMElement is. 

The only thing I can think of is adding an flag to setTargetElement that, if set, forces all events to be added to the interactionDOMElement rather than any to 'window', and the consequences are then down to the developer.

In the meantime, you could override 
addEvents and removeEvents on `renderer.plugins.interaction`

**Comment by molst** [comment]
Thanks @themoonrat for the info!

Then, because there are (although pretty nasty) workarounds, I think we should leave it as is and strive for supporting listening to an **event capture** phase within pixijs. If it would be possible to set some state on an event immediately when it enters any container wrapping a target, but before it reaches the target and starts bubbling back again, I believe that would have been the best solution in my case.
