### ISSUE TITLE
ReasonML support

### ISSUE THREAD

**Issue by ambientlight** [pixijs/pixi.js#6360]
**Feature request**: ReasonML ecosystem is growing, curious about you thoughts about supporting it in PIXI?

I have been using it internally with reasonml and thus far I have completed essential bindings and also ported basic examples. Will be happy for any feedback.

https://github.com/ambientlight/bs-pixi

**Comment by ivanpopelyshev** [comment]
Hello!

Added your link to new section for plugins: https://github.com/pixijs/pixi.js/wiki/v5-Resources#integration-with-platforms-and-frameworks

Btw, out of all variations, `PIXI.js`, `PIXIJS` we've decided to use `PixiJS` as library name.

**Comment by eXponenta** [comment]
Welcom!

But we will not support it officially, at the moment.
Support third party platforms and bindings is not prior for us, and any API changes you will have fix self, when it was break compatibility.
If will be cool things on Reason + PIXI , and it will have good documentation, examples, community, we can help support it

We migrate to TS and perhaps API will change, don't forget about it!

Good start.

**Comment by ambientlight** [comment]
@ivanpopelyshev: amazing, thanks!

@eXponenta: 
certainly, `PixiJS` seems to have decent semantic versioning, so we can expect no breaking changes until next major?  hopefully will have code coverage done soon for what's already supported for this matter also.

Thus far I have copied documentation from your docs, though docgen requires more work, as the default tooling doesn't yet generate that readable docs with its structure and css

> We migrate to TS and perhaps API will change, don't forget about it!
yes saw it, thanks.

I am adding more examples now and most likely the api coverage will expand also over next few month, thanks again! :+1:

**Comment by ivanpopelyshev** [comment]
API changes in TS conversion will be minimal. 

When we have actual typings-per-module, you will be able to think about automatic conversion.

**Comment by happylinks** [comment]
Wow I'm really happy about this! I started my own bindings a couple of months ago: https://gist.github.com/happylinks/261b2ab147e4c866195d5898718bc13f but yours look so much better! Thanks for sharing, and I'll be sure to contribute if I find something missing :)
