### ISSUE TITLE
Backward incompatible change in 5.2.1 and problem with sub dependencies in package.json

### ISSUE THREAD

**Issue by stagr** [pixijs/pixi.js#6364]
### Expected Behavior

With pixi.js-legacy fixed to 5.2.0 the sub dependencies (for example @pixi/canvas-prepare) should not use the next version (at least not when there is a non-backward compatible change).

### Current Behavior

With pixi.js-legacy fixed to 5.2.0

package.json:
`@pixi/canvas-prepare`

the package-lock.json ends up like this:

`"@pixi/canvas-prepare": {
			"version": "5.2.1",
			"resolved": "https://registry.npmjs.org/@pixi/canvas-prepare/-/canvas-prepare-5.2.1.tgz",
			"integrity": "sha512-aVdBeLAqtupsmDU9J4fUVZszrcS2/JNJX+OPc8zshwrbd/NP3JyShIJs5ZZnHjs4+R3e4DWyVoaJ7l1I3HW4CA==",
			"requires": {
				"@pixi/canvas-renderer": "5.2.1",
				"@pixi/core": "5.2.1",
				"@pixi/prepare": "5.2.1"
			}
		},`

### Possible Solution

Edit package.json of the pixi.js package to look something like this:

` "@pixi/canvas-prepare": "5.2.0",`

instead of

`"@pixi/canvas-prepare": "^5.2.0",`

**Or** when a non-backward compatible change is made, step the minor version and use a package.json similar to:

`"@pixi/canvas-prepare": "~5.2.0",`

**Or** don't introduce non-backward compatible changes within the same major version.

### Steps to Reproduce

With an application with the version of pixi.js-legacy fixed to 5.2.0. Note that it must have been installed before the release of 5.2.1 remove package-lock.json and run "npm install". This erroneously installs 5.2.1 versions of all subpackages instead of 5.2.0 and since the prepare subpackage contains a non-backward compatible change the compilation fails. In my case with the following error:

./node_modules/pixi.js-legacy/lib/pixi-legacy.es.js
35:14-21 'pixi.js' does not contain an export named 'prepare'.

### Environment

- **`pixi.js` version**: 5.2.0 (existing install, see steps to reproduce)
- **Browser & Version**:  N/A
- **OS & Version**: N/A
- **Running Example**: N/A

**Comment by bigtimebuddy** [comment]
For some context: sub-dependencies are now locked to exact versions, and we publish all packages for every release, so now 5.2.1 works _only_ with 5.2.1 sub packages. Not only does this eliminate confusion and remove a bunch of fuzzy versioning issues users were reporting (like installing multiple resolved sub-packages), but it also mentally simplifies things for users and insures PixiJS packages that were tested together, run together.

This will, as you've pointed out, might create some issues installing `pixi.js` or `pixi.js-legacy` @ 5.2.0. Would suggest cleanly installing 5.2.1. Alternatively, pin all package sub-dependencies to `<=5.2.0`.

I apologize for the inconvenience, going forward things should be much stricter.

**Comment by stagr** [comment]
Ok. Great. It was for a greater good then, but unfortunately with a side effect. Hopefully this issue will help people avoid troubleshooting the same problem or at least find a solution quickly. Closing the issue.

**Comment by bigtimebuddy** [comment]
Thanks for reporting, this should be helpful for people stubbing their toe on this issue.
