### ISSUE TITLE
Loading textures bigger than MAX_TEXTURE_SIZE

### ISSUE THREAD

**Issue by darkowic** [pixijs/pixi.js#6372]
In an application that we are writing, we need to load textures which size exceeds usual WebGL MAX_TEXTURE_SIZE. We have an old solution for that (download the image, draw it into the canvas and split it to tiles) but we are planning a migration to Pixi v5 and we want to adjust our elements API to Pixi's API for easier maintaining it in future.

**You can skip it and go into the actual question below**

We found in the documentation option `frame PIXI.Rectangle - The rectangle frame of the texture to show` for [Texture](http://pixijs.download/release/docs/PIXI.Texture.html#Texture) and we initially thought that only this part of the image will be loaded to the GPU.
```jsx
    const texture = new PIXI.Texture(
      baseTexture, // the huge texture
      new PIXI.Rectangle(0, 0, 500, 500)
    );
```
But its not - we get the error about exceeding the max size of the texture (Test: https://codesandbox.io/s/pixi-loading-huge-images-example-9mbvl). We dive deeper into the code and we already know why :)

**Actual question:** Do you think it would be possible to write custom `BaseTexture` or `Texture` or maybe `Resource` where we could handle the optional splitting of an image (etc) into smaller tiles to keep usage of Pixi APIs and to be able to load the few tiled textures into the GPU? In the end, it could be even an optional feature for Pixi or some plugin. Any tips are very appreciated!

Thank you for your time :)

**Comment by eXponenta** [comment]
We can't upload this texture.
BaseTexture upload original texture image.
Texture has only frame as UV from this BaseTexture.

Use canvas2d for croping huge texture.

**Comment by ivanpopelyshev** [comment]
From outside view - yes, why not hack insides that they support such textures? I made that kind of "giant object" hacks several times :)

However, in this particular case, you cant do anything without Scene hacks - special Sprite / TilingSprite / Mesh/ Graphics that takes either MultiBaseTexture either a BaseTexture and generates geometry for it. You'll have some antialiasing problems because of floating point edges, its possible to solve, and you have to solve it even if you make just general app and not a hack.

Now, suppose we made it. Will PixiJS `BaseTexture` hack help with to achieve more? I dont see how.

**Summary**: Scene manages geometry => we require special scene element => no need for BaseTexture hack.

**Comment by qiliangW** [comment]
> In an application that we are writing, we need to load textures which size exceeds usual WebGL MAX_TEXTURE_SIZE. We have an old solution for that (download the image, draw it into the canvas and split it to tiles) but we are planning a migration to Pixi v5 and we want to adjust our elements API to Pixi's API for easier maintaining it in future.
> 
> **You can skip it and go into the actual question below**
> 
> We found in the documentation option `frame PIXI.Rectangle - The rectangle frame of the texture to show` for [Texture](http://pixijs.download/release/docs/PIXI.Texture.html#Texture) and we initially thought that only this part of the image will be loaded to the GPU.
> 
> ```js
>     const texture = new PIXI.Texture(
>       baseTexture, // the huge texture
>       new PIXI.Rectangle(0, 0, 500, 500)
>     );
> ```
> 
> But its not - we get the error about exceeding the max size of the texture (Test: https://codesandbox.io/s/pixi-loading-huge-images-example-9mbvl). We dive deeper into the code and we already know why :)
> 
> **Actual question:** Do you think it would be possible to write custom `BaseTexture` or `Texture` or maybe `Resource` where we could handle the optional splitting of an image (etc) into smaller tiles to keep usage of Pixi APIs and to be able to load the few tiled textures into the GPU? In the end, it could be even an optional feature for Pixi or some plugin. Any tips are very appreciated!
> 
> Thank you for your time :)

I try  can't upload this texture
