### ISSUE TITLE
How to scale screen for android device

### ISSUE THREAD

**Issue by ejamshidiasl** [pixijs/pixi.js#6380]
- **`pixi.js` Version**:  v5.2.1
----------------------------------------
i have a simple game with **`width:480`** and **`height:800`** that runs on windows chrome browser. now i want to export to android. i do this with **`Cordova`** but my game is not fit to screen. (**NOTE:** i did it on Unity3D and everything was good). so how to do this with **`pixi.js`**?

**Comment by bigtimebuddy** [comment]
Easy way: You can do this easily with CSS and set your canvas view to 100% width. This will scale your content. If your screen is larger than your game size, it can make the render seem blurry.

Less Easy way: if you’re using Application, use the `resizeTo` option to scale to whatever DOM element you want. For instance, `resizeTo: window`. If you do this, it won’t be blurry if it’s scaled up, but you are responsible for resizing your game’s contents, which is some effort if you want a responsive game to accommodate different aspect ratios.

Hard way: if you’re not using Application, then there’s a `resize` method on Renderer you can use to adjust the size of the render. Everything else you’ll need to hook up like resize events on the window.

**Comment by ejamshidiasl** [comment]
it is my code:

`canvas{
            width: 100%;
            height: 100%;
        }`

`<script>
        const canvas = document.querySelector('canvas');

        const config = {
            view: canvas,
            height: 800,
            width: 480,
            backgroundColor: 0x3ba7ff
        };
        const app = new PIXI.Application(config);

        var texture1 = PIXI.Texture.from('asset/box.png');
        var texture2 = PIXI.Texture.from('asset/ground.png');
        var sprite1 = new PIXI.Sprite(texture1);

        sprite1.position.set(boxA.position.x, boxA.position.y);
        sprite1.width = 80;
        sprite1.height = 80;
        app.stage.addChild(sprite1);

        var sprite2 = new PIXI.Sprite(texture1);
        sprite2.position.set(boxB.position.x, boxB.position.y);
        sprite2.width = 80;
        sprite2.height = 80;
        app.stage.addChild(sprite2);

        var sprite3 = new PIXI.Sprite(texture2);
        sprite3.position.set(ground.position.x, ground.position.y);
        sprite3.width = 240;
        sprite3.height = 10;
        app.stage.addChild(sprite3);
        

        sprite1.anchor.set(0.5, 0.5);
        sprite2.anchor.set(0.5, 0.5);
        sprite3.anchor.set(0.5, 0.5);

    </script>`

i need a way to make game fit to all screens

**Comment by ejamshidiasl** [comment]
in my code width is from 0 to 1080(my device width) but height is from 0 to 800 (my device is 1920)
so height is true but width is not.
how to have HEIGHT FROM 0 TO 480?

**Comment by ejamshidiasl** [comment]
i finally solved the problem.
i changed anchor to 0.5 and forgot that.
thanks @bigtimebuddy your **easy way** 😄  solved problem (css: width 100%)
