### ISSUE TITLE
How to extend PIXI.Sprite to make custom Sprite like Player?

### ISSUE THREAD

**Issue by ejamshidiasl** [pixijs/pixi.js#6384]
- **`pixi.js` version**: v5.2.1_
---------------------------------------------
i want to make custom Sprite that have some additional properties like id , gun , health and more.
i extend Sprite like this:
`class MySprite extends PIXI.Sprite{
    constructor(){
        super();
    }
    setId(id){
        this.id = id;
    }
}`

but it shows nothing on canvas and has no error !

**Comment by bigtimebuddy** [comment]
Here's an example:
https://pixiplayground.com/#/edit/tvDi4NZNlpuawQJCBV_IQ

**Comment by ejamshidiasl** [comment]
thank you
it works
