### ISSUE TITLE
Graphics.setMatrix does not work for Canvas Renderer

### ISSUE THREAD

**Issue by apptaro** [pixijs/pixi.js#6394]
### Expected Behavior
Graphics.setMatrix should work for canvas renderer

### Current Behavior
Graphics.setMatrix does not have any effect when using canvas renderer.
Only works for WebGL.

### Steps to Reproduce
https://jsfiddle.net/y5scnf3j/

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Chrome 79
- **OS & Version**: Windows 10

**Comment by eXponenta** [comment]
Improve in 5.3, less version not support this feature.

**Comment by ivanpopelyshev** [comment]
Bad news, @eXponenta , its different `matrix` he's talking about :) Wanna make a PR?
