### ISSUE TITLE
Name a sprite to find it into a container.

### ISSUE THREAD

**Issue by LituOffi** [pixijs/pixi.js#6395]
Hi everyone, i have a game that have the principe of agario, to draw a cell (player circle), i call function to draw it into a prototype and place sprites into a container. The problem starts now, because i can't predict what color, size and name the cell will have, i can't pre-render everything. So for avoiding a memory heap, i need to count the container length to clear every sprites of the same type when its value is exceeded. It would be cool to save used sprites and only clear the ones that are not used anymore. This will in certain cases save a lot of performance loss like mine. @djmisterjon has been asking for this this feature but it got refused.

**Comment by eXponenta** [comment]
There no really reason implement children map into core.

**Comment by bigtimebuddy** [comment]
@LituOffi if your problem is avoiding a memory heap, are you pooling and reusing your sprites?

**Comment by LituOffi** [comment]
@bigtimebuddy I made that for my textures. But how am i supposed to do this with sprites? If i i can't identify something in my container how i am supposed to do it?

**Comment by bigtimebuddy** [comment]
Sounds like you might need to create your own Sprite to do it. If you want to attach some data.
```js
class MyIDSprite extends PIXI.Sprite {
  constructor(texture, identifier) {
    super(texture);
    this.identifier = identifier;
  }
}
```
I'm still not 100% about what you want to do. If you could provide some code or examples, we might be able to help.

**Comment by LituOffi** [comment]
Hi ! Sorry for the long anwser... I made it ! i am now able to sync the circle id with the sprite with spritename.identifier. But when i'm trying to do container.spritename.identifier it's not working and i don't know how i am supposed to destroy them with destroy() function.
