### ISSUE TITLE
PixiJS Deprecation Warning: PIXI.BaseTexture.source property has been moved, use `PIXI.BaseTexture.resource.source`Deprecated since v5.0.0

### ISSUE THREAD

**Issue by cvDecheva** [pixijs/pixi.js#6401]
![Screenshot_2](https://user-images.githubusercontent.com/60930676/74248220-e91b5a00-4cef-11ea-9006-d1a602216c16.png)
![Screenshot_3](https://user-images.githubusercontent.com/60930676/74248357-24b62400-4cf0-11ea-8d88-0aad50faaaf3.png)

This warning appears only with Canvas, not with WebGL.

**Comment by themoonrat** [comment]
I noticed this too. I assume it started off this way to support v4 style and v5 style, before we added the polyfills in deprecation @ivanpopelyshev ?

**Comment by ivanpopelyshev** [comment]
It should not be triggered even in that case. Is that a RenderTexture?

**Comment by themoonrat** [comment]
This occurs on the canvas renderer when you have a sprite that doesn't have a texture given to it yet.
https://www.pixiplayground.com/#/edit/sao_iLKl-iQazcxNsH5eY

**Comment by ivanpopelyshev** [comment]
do you think its `PIXI.Texture.Empty` fault?

**Comment by bigtimebuddy** [comment]
https://www.pixiplayground.com/#/edit/hx6BNMXAxMpsbr9BT-11y

Returning `null` from `getDrawableSource` silences the deprecation. I think this is the correct fix for this issue because `this.source` isn't a thing anymore.
