### ISSUE TITLE
Antialias stops working as expected after adding a filter to the stage

### ISSUE THREAD

**Issue by UltraCakeBakery** [pixijs/pixi.js#6407]
### Current Behavior
I have a pixi-legacy instance that adds randomly generates shapes with random colors to my canvas. The Graphics get added to the stage and the stage has a dropShadowFilter from pixi-filters.

When I add the dropshadow filter to the stage the at startup configured antialias stops working:
![chrome_2020-02-12_11-40-12](https://user-images.githubusercontent.com/12383587/74328397-16b6e080-4d8e-11ea-9380-b30e59d19362.png)

But when I remove the dropshadow filter it starts working again:
![chrome_2020-02-12_11-40-34](https://user-images.githubusercontent.com/12383587/74328572-757c5a00-4d8e-11ea-96f5-909c3bcce99b.png)

### Possible Solution
I've not found one yet but I think I have to add another FXAA filter?

### Steps to Reproduce
```
import { Application } from 'pixi.js-legacy'
import { DropShadowFilter } from '@pixi/filter-drop-shadow'

const pixi = new Application({
     view: canvas,
     width: window.innerWidth,
     height: window.innerHeight,
     backgroundColor: 0x000000,
     antialias: true,
     sharedTicker: true
})

const circleGraphic= new Graphics()
circleGraphic.lineStyle( 5, 0xFF00FF)
circleGraphic.drawCircle( 500, 500, 30 )

pixi.stage.addChild( circleGraphic )

pixi.stage.filters = [ new DropShadowFilter({ blur: 0 }) ]
```
**note**: This is code is only a small part of my project and variable size values have been replaced with fixed values.

### Environment

- **`pixi-legacy.js` version**: 5.2.1
- **Browser & Version**: _e.g. Chrome 79_
- **OS & Version**: _e.g windows_

**Comment by eXponenta** [comment]
WebGL doesn't support AA in framebuffer, you may use FXAA filter as alternative.
Or you can use pixi-blit (in core since 5.3)
https://github.com/gameofbombs/pixi-blit

**Comment by bigtimebuddy** [comment]
Legacy just means it has the fallback support for canvas, not that is only canvas.

**Comment by UltraCakeBakery** [comment]
@eXponenta Sadly I need backwards compatibility. If the filters don't work on the canvas its not a big deal.

I guess I'll just use the filter if webGL is enabled. Thank you.

**Comment by eXponenta** [comment]
@bigtimebuddy i asked it because author should know what he do.
Statistical there no reason to use legacy bundle in 2020, otherwise when target platform doesn't support WebGL, filters don't works too and problem with AA is disappear .

**Comment by UltraCakeBakery** [comment]
@eXponenta I've got multiple clients who still use IE11 because they switch laptops every week running windows 7 due to windows 10 licensing cost. IE11 still has a 2.5% marketshare in my country and is the main browser for 70% of my target demographic (older and non-tech business people).

So, statistically, there is a reason to use the legacy bundle. But everyone's situation is different.

Thanks for giving me the heads up tho. I'll keep your advice in mind.

**Comment by UltraCakeBakery** [comment]
I remember reading that WebGL had limited support on IE11 and there was some miss-match where one build did have WebGL and the other one did not (depending on the version of windows). Is this true? If not i'll just drop the legacy version and use the native one.

**Comment by ivanpopelyshev** [comment]
Unless you really need those sweet kilobytes for something else, dont drop pixi-legacy.

It has `graphics.generateCanvasTexture()` that is usable even on webgl. Generate textures for shapes that look bad in webgl without aa under filters.

**Comment by UltraCakeBakery** [comment]
@ivanpopelyshev Thanks for the tip. I'll keep that in mind. Right now my total final bundle size is roughly 600kb. When I cut corners on the other libraries (Vue, GSAP, FontAwesome, random polyfills) by switching to svelte, tree-shaking font-awesome and removing polyfills that number will drop significantly.

I PIXI is a great library and has the best performance as / compatibility imo. For now its worth every KB it needs. But the less it needs the better and the less corners I need to cut.

Thanks for the advice and help guys. I will close this issue for now. Feel free to open it if needed.

**Comment by derMart** [comment]
having the same issue with pixi 5.2.2
@eXponenta  Do you mean 5.2 ? 5.3 is not released yet, right ?
Can you elaborate a bit how to use pixi blit to enable anti alias on filters?
