### ISSUE TITLE
How to use pixi.js-legacy and verify that it has been activated?

### ISSUE THREAD

**Issue by afarber** [pixijs/pixi.js#6412]
Hello, this is not a bug report, but just a question on how to use [pixi.js-legacy](https://github.com/pixijs/pixi.js/blob/dev/bundles/pixi.js-legacy/src/index.js). 

I would like to activate it in my word game, because player numbers have dropped after the upgrade to pixi.js v5 and some users complain about the "WebGL unsupported in this browser" error.

In my [HTML-file](https://apps.facebook.com/slova-farbera/) I have added the CDN-link to pixi.js-legacy:

```
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js@5.2.1/dist/pixi.min.js"></SCRIPT>
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js-legacy@5.2.1/dist/pixi-legacy.min.js"></SCRIPT>
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi-filters@latest/dist/pixi-filters.js"></SCRIPT>
```

In my [Javascript file](https://slova.de/words/Words.js) I have the following code (without any imports at the top):

```
jQuery(document).ready(function($) {
        var app = new PIXI.Application({
                width: BOARD_WIDTH,
                height: BOARD_HEIGHT + SmallTile.HEIGHT,
                view: document.getElementById('board'),
                antialias: true,
                backgroundColor: 0xFFFFFF
        });
```

Thank you

### Expected Behavior
The game is rendered in all browsers

### Current Behavior
The game is not displayed for some users, with console error: *WebGL unsupported in this browser*

### Possible Solution
Use pixi.js-legacy, but unclear how.

### Environment

- **`pixi.js` version**:  5.2.1
- **OS & Version**: Windows 7, 10
- **Running Example**: 

- https://apps.facebook.com/slova-farbera/ 
- https://slova.de/words/google/
- https://vk.com/app5442212
- https://ok.ru/game/1158060544

**Comment by afarber** [comment]
Nevermind my question -

It seems that the above is enough, i.e. after adding just a single line:
```
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js-legacy@5.2.1/dist/pixi-legacy.min.js"></SCRIPT>
```
my word game works again - even if I toggle webgl.disabled in about:config in Firefox 60.7.2 on Win 10.

In the console I can read then, either -
```
PixiJS 5.2.1 - Canvas - http://www.pixijs.com/
```
or -
```
PixiJS 5.2.1 - WebGL 2 - http://www.pixijs.com/
```

![Canvas](https://user-images.githubusercontent.com/1884458/74436365-9adc9700-4e66-11ea-90d7-5a3be05340d4.png)

![WebGL_2](https://user-images.githubusercontent.com/1884458/74436378-a039e180-4e66-11ea-9045-15d43369e1e1.png)

Thank you

**Comment by stla** [comment]
Hello,

 I don't understand. `pixi.js` and `pixi-legacy.js` both define `var PIXI`. So the second one doesn't overwrite the first one?

**Comment by rubenlg** [comment]
@stla a bit late but hopefully this will help others landing here: you should only have one installed. `pixi.js-legacy` is a superset of `pixi.js`, including both WebGL and Canvas.

**Comment by afarber** [comment]
Thanks @rubenlg but what about when using CDN with

```
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js@5.2.1/dist/pixi.min.js"></SCRIPT>
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js-legacy@5.2.1/dist/pixi-legacy.min.js"></SCRIPT>
```

should I remove the 1st line?

**Comment by rubenlg** [comment]
I suspect so. If you see the file sizes, the legacy version is 7% larger, which hints that it doesn't just include the canvas fallback code, but the entire PIXI library with both canvas and webGL support. It's easy to test, take any trivial PIXI example and run it on the legacy library alone, to see if you can create both a canvas and a webgl `PIXI.Application`.

**Comment by themoonrat** [comment]
Correct.
When dealing with these full pre-builds of pixijs on a cdn, use either the regular version OR the legacy version, but not both

**Comment by afarber** [comment]
This has worked for me. Thank you for taking your time to reply.
