### ISSUE TITLE
social badge

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#6413]
Maybe this can be a good idea.
https://github.com/gliderlabs/slack/blob/master/slackin/README.md

Add a button in the README pixi front page.
![image](https://user-images.githubusercontent.com/24865815/74512666-cac38300-4ed6-11ea-852d-9c24857183b3.png)

**Comment by SukantPal** [comment]
@ivanpopelyshev @bigtimebuddy This is a yes/no. We can resolve this easily.

**Comment by bigtimebuddy** [comment]
Yeah good idea.
