### ISSUE TITLE
PIXI.SimplePlane doesn't work properly 

### ISSUE THREAD

**Issue by hellmark1990** [pixijs/pixi.js#6416]
HI!
Seems like PIXI.SimplePlane(replacement of PIXI.mesh.Plane) doesn't work properly. 
How can I rewrite this v4 code to v5?
https://codepen.io/shshaw/pen/qqPwXM

**Comment by eXponenta** [comment]
What u mean?
API was be changed, there aren't direct access to vertices from mesh instance now.

For access to vertices should be used: 
https://pixijs.download/dev/docs/PIXI.MeshGeometry.html#getBuffer

like as:
```
const mesh = new PIXI.SimplePlane();
const vertBuff = mesh.getBuffer('position');
// ... any changes.

vetBuff.update()
```

**Comment by hellmark1990** [comment]
@eXponenta great! Thx a lot!
