### ISSUE TITLE
PIXI.Graphics.arcTo does not work in IE11

### ISSUE THREAD

**Issue by apptaro** [pixijs/pixi.js#6421]
### Expected Behavior
Methods below should work on IE11:
- PIXI.Graphics.arcTo
- PIXI.Graphics.quadraticCurveTo
- PIXI.Graphics.bezierCurveTo

### Current Behavior
They don't work on IE11. The error occurs:
SCRIPT438: Object doesn't support property or method 'isNaN'

### Possible Solution
Use polyfill for Number.isNaN

### Steps to Reproduce
Open this URL with IE11:
https://www.pixiplayground.com/#/edit/WsSW6X13GV_0mup3AbreX

### Environment
- **`pixi.js` version**: 5.2.1
- **Browser & Version**: IE11
- **OS & Version**: Windows 10

### Cause
The problematic code is here:
https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/const.ts#L32

**Comment by themoonrat** [comment]
Ok, this is my bad. Should have just used "isNaN" rather than "Number.isNaN" which was only introduced in ES2015

**Comment by bigtimebuddy** [comment]
Fixed in #6426
