### ISSUE TITLE
PIXI.Graphics.beginTextureFill does not work in IE11

### ISSUE THREAD

**Issue by apptaro** [pixijs/pixi.js#6422]
### Expected Behavior
PIXI.Graphics.beginTextureFill should work on IE11.

### Current Behavior
PIXI.Graphics.beginTextureFill does not work correctly on IE11.
No errors are thrown, but resulting fill is not correct.

### Possible Solution
Not known.

### Steps to Reproduce
Open this URL with IE11, and compare the result with other browsers:
https://www.pixiplayground.com/#/edit/CNvhNbOIikcWICejhb7Bz

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: IE11
- **OS & Version**: Windows 10

**Comment by eXponenta** [comment]
U tried repeat nPOT textures, that supports only in Webgl2, IE doesn't support this.
Same problem on mobile, because pixi force webgl 1 on it.
