### ISSUE TITLE
Antialias doen't work with mask

### ISSUE THREAD

**Issue by hellmark1990** [pixijs/pixi.js#6429]
Hi! I apply mask for SimplePlane and its borders contains steps and seems like antialiasing doesn't work properly. How can I sole those steps and make them smooth on the border of the SimplePlane?

**Image result:**

http://tinyurl.com/u6lxwz3

**This is the code:**
```
let app       = new PIXI.Application({
    backgroundColor: '0xA4A4A4',
    width:           750,
    height:          563,
    antialias:       true,
});
let container = new PIXI.Container();

    // let whiteTShirtsSprite    = new PIXI.Sprite(PIXI.Texture.fromImage('images/mask_white_t-shirts.png'));
    let whiteTShirtsSprite    = new PIXI.Sprite(PIXI.Texture.fromCanvas(canvas));
    whiteTShirtsSprite.width  = baseSprite.width;
    whiteTShirtsSprite.height = baseSprite.height;
    whiteTShirtsSprite.cacheAsBitmap = true;
    whiteTShirtsSprite.roundPixels = true;

 let base  = PIXI.BaseTexture.from('images/imprint_left.jpg');
    let frame = new PIXI.Rectangle(0, 0, SETTINGS.IMPRINTS.LEFT.WIDTH, SETTINGS.IMPRINTS.LEFT.HEIGHT);

    let imprintSprite = new PIXI.SimplePlane(
        new PIXI.Texture(base, null, frame, frame),
        SETTINGS.IMPRINTS.LEFT.BUFFER_SIZE.X,
        SETTINGS.IMPRINTS.LEFT.BUFFER_SIZE.Y
    );

    imprintSprite.width       = SETTINGS.IMPRINTS.LEFT.WIDTH;
    imprintSprite.height      = SETTINGS.IMPRINTS.LEFT.HEIGHT;
    imprintSprite.position.x  = 190;
    imprintSprite.position.y  = 215;
    imprintSprite.mask        = whiteTShirtsSprite;
    imprintSprite.roundPixels = true;

```

- **`pixi.js` version**: _e.g. 5.2.1_
- **Browser & Version**: _e.g. Chrome 78.0.3904.70_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by eXponenta** [comment]
Sprite mask is filters
Same as:
https://github.com/pixijs/pixi.js/issues/6407

**Comment by ivanpopelyshev** [comment]
> I apply mask for SimplePlane

goodbye anti-aliasing. WebGL doesnt have AA inside custom framebuffers.

You can add extra transparent pixels at the edges and corner - thus that job will be handled by texture filtering and not AA. Of course you'll have to change size of your plane to accomodate those pixels.

**Comment by hellmark1990** [comment]
> texture filtering is applied on a cat
@ivanpopelyshev Thx for reply! Could you point me to some example or article about texture filtering? Should I use shaders for this?

**Comment by eXponenta** [comment]
@hellmark1990 
https://learnopengl.com/Getting-started/Textures

WebGL is OpenGL implementation in browsers, Pixi based on WebGL.

**Comment by ivanpopelyshev** [comment]
> > texture filtering is applied on a cat
> 
> @ivanpopelyshev Thx for reply! Could you point me to some example or article about texture filtering? Should I use shaders for this?

https://webgl2fundamentals.org/

In pixi texture filtering is set with `texture.baseTexture.scaleMode` , which is value of `PIXI.SCALE_MODES`.

Basically, if you ask for texture pixel between the four real texture pixels, it will give you a mix of them. If you have a transparent border in texture - border pixels will be mixed with that transparency, giving you a crude antialiasing.
