### ISSUE TITLE
Cannot render Container2d in RPG maker MV

### ISSUE THREAD

**Issue by SQDT** [pixijs/pixi.js#6431]
A few of my RPG maker MV game players report that the game encounters `Cannot read property 'render' of undfined` error when they enter battle scene.

One of them send me a screenshot: https://i.imgur.com/L1OWge8.png

It seems `Container2d` from `pixi.projection.js` I use in battle scene causes the error.
They say they 100% encounter the error when entering battle.
But almost all players include me don't encounter the error at all. So I have no idea how to fix this.

As for now, all of the reporters use Windows 7 32bit. Does this matter?

Any kind of leads will be appreciated.

- **`pixi.js` version**: _4.5.5_
- **`pixi.projection.js` version**: _2.0.8_
- **`nw.js` version**: _0.44.1 win-ia32_
- **`nw.js` version**: _0.43.3 win-ia32_

**Comment by eXponenta** [comment]
This is problems of pixi-projection
https://github.com/pixijs/pixi-projection

And you use very old PIXI wich can't supported now.
Latest supported v4 versoion 4.8.9.

@ivanpopelyshev I challenge you!

**Comment by ivanpopelyshev** [comment]
Latest pixijs v4: https://github.com/pixijs/pixi.js/releases/tag/v4.8.9
pixi-tilemap for v4: https://github.com/pixijs/pixi-tilemap/tree/v4.x/dist
pixi-projection for v4: https://github.com/pixijs/pixi-projection/tree/v4.x/dist

It should work. However when I last time helped with RMMV , upgrade to latest pixi-v4 caused some problems. If you use any plugins that re-write the ShaderTilemap class - you'll have to make them compliant with latest corescript (https://github.com/rpgtkoolmv/corescript)

**Comment by ivanpopelyshev** [comment]
As for canvas2d - Im sorry, pixi-projection for v4 does not support canvas fallback :(

You have to ask your users what do they see in console, if its Pixi WebGL or Pixi Canvas

**Comment by SQDT** [comment]
@eXponenta  @ivanpopelyshev 
Thx for reply!

I updated pixi.js and pixi-tilemap.js to the latest version and they work well for now.

@ivanpopelyshev ,
Sorry but I couldn't get what "Uglify your code by adding IF's that use regular Container in case of canvas2d" mean. Does "Uglify" mean obfuscation? Does "IF" mean if-else condition?

**Comment by ivanpopelyshev** [comment]
@SQDT
Sometimes, we all obfuscate our code by adding more conditions to avoid buggy places ;)

**Comment by SQDT** [comment]
@ivanpopelyshev 
I got it... yes, that's what we all sometimes do ;D

I'll try to "uglify" my code then.
Thank you for your help!
