### ISSUE TITLE
Latest dev version failing to run in WebGL on iOS

### ISSUE THREAD

**Issue by EneaEntertainment** [pixijs/pixi.js#6433]
### Expected Behavior
WebGL running

### Current Behavior
console reports 'canvas mode'

### Steps to Reproduce
open: https://pixijs.io/examples/?v=dev#/mesh-and-shaders/textured-mesh-basic.js
compare: https://pixijs.io/examples/?v=v5.2.1#/mesh-and-shaders/textured-mesh-basic.js

### Environment

- **`pixi.js` version**: dev
- **Browser & Version**: Safari, Chrome, Firefox
- **OS & Version**: iOS/iPadOS 13.3.1

**Comment by eXponenta** [comment]
Fixed!
Thanks for report!
