### ISSUE TITLE
pixi.js@5.2.1 No typescript error if I use PIXI without importing it. Just runtime errror that is undefined.

### ISSUE THREAD

**Issue by stevemarksd** [pixijs/pixi.js#6445]
### Expected Behavior
Typescript error
### Current Behavior
No error
### Possible Solution
I think you guys cast pixi as a global somehow
### Steps to Reproduce
create new file and add

// No PIXI import
new PIXI.Point()

No typescript error, but run time error.

### Environment

- **`pixi.js` version**: 5.2.1
"typescript@3.8.2"
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
The typings aren’t exactly perfect. They reference a global PIXI namespace, but this is only available if you are using the browser dist file. If you are building using webpack or a bundler, you need to `import * as PIXI from ‘pixi. js’`

If you look at the wiki there are a bunch of boilerplate projects.

**Comment by stevemarksd** [comment]
I think you missed my point. I'm not importing pixi at all. So PIXI should be undefined, but somehow typescript thinks PIXI is present. @bigtimebuddy

**Comment by bigtimebuddy** [comment]
If you could provide a sample project, that’d be helpful. Not enough information in your post to understand what’s going on. I assume your tsconfig is using the typings for pixi which says PIXI global is okay?

**Comment by stevemarksd** [comment]
@bigtimebuddy  I didn't include the tsconfig because doesnt have anything special.
Just this:
```

  "typeRoots": [
    "./node_modules/@types"
  ],

```

To reproduce just create a new file like this:

```
new PIXI.Point()
```

run `yarn add pixi.js`

Configure typescript and run typechecker.

It should error because you didn't import PIXI. but it doesnt

**Comment by bigtimebuddy** [comment]
Are you including `@types/pixi.js‘ as a dependency?

**Comment by embeddedt** [comment]
I'm pretty sure that this is intentional behavior. AFAIK TypeScript auto-detects globals (i.e. what would be available if you used a CDN) from type definitions which specify them.

**Comment by JacobFischer** [comment]
I'm having this issue too in one of my projects. Thankfully this issue exists, so I created a small repo that reproduces the error:

https://github.com/JacobFischer/pixi-ts-global-error

The error appears to be that the current `pixi.js.d.ts` definitions pollute the global variable by declaring the `PIXI` namespaces without directly exporting them, so they just exist as a global ambient declarations to TypeScript as soon as PIXI is first imported, regardless if it actually is a global or not.

One solution would be to update the definitions to move away from ambient declarations and use exports instead.

I can try to put together a PR to resolve this.

**Comment by stevemarksd** [comment]
> I'm pretty sure that this is intentional behavior. AFAIK TypeScript auto-detects globals (i.e. what would be available if you used a CDN) from type definitions which specify them.

If this is intentional I think has a huge design flaw. You probably don't want to design something that will work at compile time, but will blow at run time. I hope you guys realize how important is for types to actually work properly.

**Comment by bigtimebuddy** [comment]
I can provide some context here.

First, if you are importing as modules `import { Application, Graphics } from 'pixi.js'`, types should work because we also export the namespace as the module:

```
declare module "pixi.js" {
    export = PIXI;
}
```

It's true that there is also a global `PIXI` namespace, however, there are some users that do not bundle PIXI using webpack/rollup/etc, but they still need typing information. The current typings serve both module and ambient use-cases. For instance, if you are including PixiJS from a CDN or the distribution (bundled) build.

If someone would like to propose an alternative that supports both these cases, please let us know.

Also, we are about to wrap our conversion to TypeScript, which will likely support module-only typings for all the low level packages (e.g., `@pixi/core`) and the namespace + module typings for the bundle (e.g, `pixi.js` or `pixi.js-legacy`).

**Comment by JacobFischer** [comment]
I believe the "Typescript" way to approach modules is to not assume any modules are automatically loaded globally. This way developers have the freedom to inject a any modules they desire globally, like pixi.js in this case, and then extend their own global types to inform Typescript what they did.

For example, if a developer excepts pixi to be available globally as they loaded it into the `window` in browser, they just have to tell TypeScript they did that:

```ts
import * as PIXI from "pixi.js";

export declare global {
  interface Window {
    // add you custom properties and methods
    PixiOrWhateverYouWantToReferToItGlobally: PIXI;
  }
}
```

**Comment by bigtimebuddy** [comment]
That’s fair.

Another important quirk of our current typings is they are generated from JSDocs. This assumes global namespacing. This approach is just temporary for the time being until we can auto generate typings.

**Comment by JacobFischer** [comment]
Ah neat.

I created a PR that should be a simple fix for this issue. However as noted developers that use pixi globally will have to tell Typescript they are doing so. There should be no functional changes for non TS users as it only changes one line in typings file generated by the build script.
