### ISSUE TITLE
CanvasSpriteRenderer strange rounding functions

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#6447]
Reported here: https://www.html5gamedevs.com/topic/44803-canvasrenderer-problem/

Demo: https://www.pixiplayground.com/#/edit/dviwM8_okZ91hhxBDbjrg

Possible fix is there, just uncomment the first line. I cannot make PR yet, need to do a bit of history digging and check how to use roundPixels in our case.

**Comment by themoonrat** [comment]
The floors existed because when you had odd resolutions, like 0.75, rounding issues could cause trying to draw more than actually existed. All browsers handled this fine...... apart from IE, which error out
https://github.com/pixijs/pixi.js/pull/5836
