### ISSUE TITLE
PIXI.settings.RESOLUTION bug with filters

### ISSUE THREAD

**Issue by Maximvsed** [pixijs/pixi.js#6453]
There is PIXI.settings.RESOLUTION and FILTER_RESOLUTION bug when filters are using.
Usually it can't use real display pixel ratio settings, I works correctly only with 1, 2, 4 sets. For example, it bug with size when we use 2.5, 3 or so.
For example set with 2.5 that shows incorrect size of filtered object:

PIXI.settings.RESOLUTION = 2.5;
PIXI.settings.FILTER_RESOLUTION = 2.5;

app = new PIXI.Application({
		  width: 210,
		  height: 400,
		  resolution: 2,
		  listening: false
	});
document.body.appendChild(app.view);
points = Array();
points.push(10,10);
points.push(100,10);
points.push(100,200);
points.push(10,400);
var container = new PIXI.Container();
var sprite = new PIXI.Sprite(); 
var graphics = new PIXI.Graphics();
app.stage.addChild(container);
container.addChild(sprite);
sprite.addChild(graphics);

graphics.lineStyle(2, 0xffffff);
graphics.beginFill(0xFF3300);
graphics.moveTo(points[0], points[1]);
for (var l=2;l<points.length;l+=2) graphics.lineTo(points[l], points[l+1]);
graphics.lineTo(points[0], points[1]);

var graphics2 = new PIXI.Graphics();
graphics2.lineStyle(2, 0xffffff);
graphics2.beginFill(0xFF3300);
graphics2.moveTo(points[0], points[1]);
for (var l=2;l<points.length;l+=2) graphics2.lineTo(points[l], points[l+1]);
graphics2.lineTo(points[0], points[1]);
app.stage.addChild(graphics2);

var blur_filter = new PIXI.filters.BlurFilter(0.5, 1);

graphics.filters = [blur_filter];
graphics.y = 0;
graphics.x = 100;

app.renderer.render(app.stage);

setInterval(function () {
	container.cacheAsBitmap = false;
	if (!graphics.filters) graphics.filters = [blur_filter]; else {graphics.filters = null;};
	container.cacheAsBitmap = true;
	if (graphics.y>10)
	{
		graphics.y = -100;
	}
}, 1000);

**Comment by ivanpopelyshev** [comment]
Confirmed, we have a bug somewhere: https://www.pixiplayground.com/#/edit/l8VRZeUAzgfpNzh6Y1kib

Marking it as X-Files because I suspect its rounding error somewhere.
