### ISSUE TITLE
Scaling moves graphics

### ISSUE THREAD

**Issue by SimBioT1954** [pixijs/pixi.js#6454]
### Expected Behavior
Scale graphics
### Current Behavior
It acts like I'm changing **x** and **y** properties (also moves the circle instead of just scaling) 

https://jsfiddle.net/d2gce06z/2/

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Chrome 80.0.3987.122
- **OS & Version**: Windows 10

**Comment by TheWyo** [comment]
Transformations (position/scale/rotation etc) happen around an object's pivot point, which by default, is the top-left (0, 0) of it's bounding box.

If you want to keep the circle in the same position, add these lines to your draw function:
```javascript
this.circleGraphics.pivot.set(x, y);  
this.circleGraphics.position.set(x, y);
```

This will move the pivot into the place you draw the circle's center, but as a result, will move the object up and to the left that amount. So we then set the position to this as well to counteract that offset, and you get the behaviour you're after.

**Comment by SimBioT1954** [comment]
@TheWyo thank you very much!
