### ISSUE TITLE
Bug with re-cacheAsBitmap and filters

### ISSUE THREAD

**Issue by Maximvsed** [pixijs/pixi.js#6456]
There is bug with re-caching filtered objects. Some times objects are dissapears after cacheAsBitmap becomes false.
Here is simple example:

app = new PIXI.Application({
		  width: 1000,
		  height: 500,
		  autoStart: false
	});

document.body.appendChild(app.view);
points = Array();
points.push(10,10);
points.push(100,10);
points.push(100,200);
points.push(10,400);
var container = new PIXI.Container();
app.stage.addChild(container);
var sprites = Array();
var cnt = 20;
for (i=1;i<=cnt;i++)
{

	var sprite = new PIXI.Sprite(); 
	var graphics = new PIXI.Graphics();
	container.addChild(sprite);
	sprite.addChild(graphics);
	graphics.lineStyle(2, 0xffffff);
	graphics.beginFill(0xFF3300);
	graphics.moveTo(points[0], points[1]);
	for (var l=2;l<points.length;l+=2) graphics.lineTo(points[l], points[l+1]);
	graphics.lineTo(points[0], points[1]);

	var blur_filter = new PIXI.filters.BlurFilter(0.5, 1);
	graphics.filters = [blur_filter];
	graphics.y = 20;
	graphics.x = 20;
	sprite.scale.x = 0.5;
	sprite.scale.y = 0.5;
	sprite.x = (i-1)*50;
	sprites[i] = sprite;

}

setInterval(function () {
	for (var i=1;i<=cnt;i++)
	{
		sprites[i].cacheAsBitmap = false;
		if (Math.random()<0.5){
			sprites[i].cacheAsBitmap = true;
		};
	}
	app.renderer.render(app.stage);
}, 1000);

**Comment by ivanpopelyshev** [comment]
I think its fixed here: https://github.com/pixijs/pixi.js/pull/6333
