### ISSUE TITLE
Bounds calculations - mask not included at parent level

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6460]
I have a display-object that has children, and one child's bounds fall partially outside of the parent. However, the parent is masked so that the part of the child outside of parent's content bounds aren't visible.

# Expected Behavior
Now, I would expect pixi.js to mask the parent's bounds. However, `Container#calculateBounds` only masks child bounds, but not the parent's bounds.

### Possible Solution

I think we should add another bounds-mask intersection in `calculateBounds` for the top-level node via `addBoundsMask`.

@ivanpopelyshev This could be an easy fix if you think that this behavior is indeed incorrect.

**Comment by ivanpopelyshev** [comment]
I think its correct, however we have to check if Flash does that. Just in case.

**Comment by SukantPal** [comment]
![Bounds](https://user-images.githubusercontent.com/22450567/75929917-88d78e00-5e3f-11ea-8456-3f12b250f250.png)

This is a visual representation of the layout.
