### ISSUE TITLE
Events keep on propagating to the DOM event with e.stopPropagation()

### ISSUE THREAD

**Issue by yandianjiangfeng** [pixijs/pixi.js#6463]
Events keep on propagating to the DOM event with e.stopPropagation()

**Comment by ivanpopelyshev** [comment]
Debug if this line is called in your case: 

https://github.com/pixijs/pixi.js/blob/1e06df5ae7b3f089b851e6ce4708d64e411fe800/packages/interaction/src/InteractionManager.js#L1150-L1158

**Comment by yandianjiangfeng** [comment]
>  yes ！
![wx](https://user-images.githubusercontent.com/34053795/76278913-cd43ad80-62c7-11ea-9eaa-95a3bf1a67b1.png)
 the line is called

**Comment by yandianjiangfeng** [comment]
no  the line is not called

**Comment by yandianjiangfeng** [comment]
I got it!   All interaction events in pixi are purely within pixi and have nothing to do with the DOM.

**Comment by rnike** [comment]
Can resolve by calling `e.nativeEvent.stopPropagation()`
