### ISSUE TITLE
Changing PIXI.Text text value while offscreen can cause texture to not update.

### ISSUE THREAD

**Issue by cnewtonvgw** [pixijs/pixi.js#6475]
Problem:
In certain scenarios updating a text string while the browser is not visible can cause the rendered texture to not update to the new value.

### Expected Behavior
On next render pass the rendered text should update to the new value
### Current Behavior
Rendered text does not update
### Possible Solution
I spent a few hours debugging around some PIXI internals but couldn't find anything obvious.
My guess is this is something to do with the way canvas itself is updated while the browser is in the background. Since there is a 'forced' background update PIXI is maybe reading the texture before the browser has updated the canvas. (Just speculating)
### Steps to Reproduce
1. Have a non-RAF ticker update (example uses setInterval every 1 second)
2. Render text with an initial value - e.g. "20"
3. Have a method to change the text value when the browser session is offscreen (so RAF is not running), example uses setTimeout after 5 seconds.
4. Change the text value while the session is offscreen - e.g. "80"
5. View the rendered output and see the rendered text has not updated - i.e. still renders "20"

### Notes
So far I've only reproduced this on Android/Chrome. However I have received reports ( and seen evidence ) of the issue occurring on Windows/Chrome, though I have not reproduced that.
If the new text value results in different sized texture the bug doesn't occur - i.e. rendering 20 and then 200 makes the texture wider, bug doesn't happen.
Bug does not appear if there is no "background update" i.e setInterval in this case.

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Chrome 80
- **OS & Version**: Android 9
- **Running Example**: https://www.pixiplayground.com/#/edit/7PhToYqEdkS7Hz7PU7vAl

Example explanation:
It *should* display the text '20' for 5 seconds, and then the text '80' thereafter.
To trigger the bug:
- Open on an android device in chrome
- After you see '20' switch to another browser tab
- Wait 6 seconds
- Switch back to the playground
- You should still see '20' and it never becomes '80'.

**Comment by cnewtonvgw** [comment]
I can now confirm it is reproducible on Windows/Chrome. If you minimize the browser after the '20' is rendered, wait 6 seconds and then maximize again.

**Comment by ivanpopelyshev** [comment]
PixiJS updates the texture - that's for sure. 

Related places:
https://github.com/pixijs/pixi.js/blob/ba40000582e0692572866ed101b6590abda69b45/packages/text/src/Text.ts#L414
https://github.com/pixijs/pixi.js/blob/ba40000582e0692572866ed101b6590abda69b45/packages/text/src/Text.ts#L175
https://github.com/pixijs/pixi.js/blob/ba40000582e0692572866ed101b6590abda69b45/packages/text/src/Text.ts#L395
https://github.com/pixijs/pixi.js/blob/ba40000582e0692572866ed101b6590abda69b45/packages/core/src/textures/BaseTexture.ts#L428
https://github.com/pixijs/pixi.js/blob/ba40000582e0692572866ed101b6590abda69b45/packages/core/src/textures/BaseTexture.ts#L519
https://github.com/pixijs/pixi.js/blob/ba40000582e0692572866ed101b6590abda69b45/packages/core/src/textures/TextureSystem.ts#L151
https://github.com/pixijs/pixi.js/blob/ba40000582e0692572866ed101b6590abda69b45/packages/core/src/textures/resources/BaseImageResource.ts#L81

All that code was tested. The fact that it breaks on tab change indicates that there's a Chromium bug with canvas2d.

I dont see it in the list, so it must be something unique: https://bugs.chromium.org/p/chromium/issues/list?q=canvas&can=2

**Comment by cnewtonvgw** [comment]
Thanks for looking into this @ivanpopelyshev - If you have any trouble reproducing the issue with my playground example I'm happy to help. Note: I could not reproduce the issue on MacOS/Chrome. 
If you are able to reduce and file a chromium issue would you mind letting me know?

**Comment by cnewtonvgw** [comment]
If anyone is running into the same issue and needs a workaround we have implemented this (not pretty) workaround for some text elements we really don't want to be inaccurate.
https://www.pixiplayground.com/#/edit/X3oEM6qYTorCCC2hD7fvd

**Comment by themoonrat** [comment]
Cheers for that @cnewtonvgw 

If you're wanting to avoid creating your own class, you could do something like

```
function generateText( displayObject ) {
	if ( displayObject.updateText && displayObject.style ) {
		displayObject.updateText();
	}

	if ( displayObject.children ) {
		for ( let i = displayObject.children.length - 1; i >= 0; i-- ) {
			generateText( displayObject.children[i] );
		}
	}
}

```
and when visibility becomes true

`generateText( app.renderer._lastObjectRendered );`

to force updating of the texture immediately. That's a bit harsh, forcing a full texture re-creation regardless of visibility, so you could change `displayObject.updateText();` to `displayObject.dirty = true`; and any visible Text's would update themselves on the next render.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev are you going to investigate this further? If not there are some suitable workarounds here and we can probably close.

**Comment by ivanpopelyshev** [comment]
I will investigate it.

Asking to close Chromium bug issue is heresy on its own!

**Comment by themoonrat** [comment]
I have a strong hunch that this bug will have been fixed by https://github.com/pixijs/pixi.js/pull/6751
@cnewtonvgw  could you confirm this on the latest dev build please?
