### ISSUE TITLE
Graphics.lineStyle with options argument does not work

### ISSUE THREAD

**Issue by tari3x** [pixijs/pixi.js#6490]
- **`pixi.js` version**: 5.1.6
- **Browser & Version**: both firefox 74.0 and chromium 80.0.3987.132
- **OS & Version**: OpenSuSE 43.0 
- **Running Example**: https://jsfiddle.net/7659q2ud/1/

I expect the two following lines to be equivalent, and yet the example shows that they are not:
```
// THIS WORKS:
// graphics.lineStyle( 10, 0x334455 );
// THIS DOESN'T
graphics.lineStyle({ width : 10, color :  0x334455 });
```

Am I using it wrong?

**Comment by bigtimebuddy** [comment]
Please refer to the versioned specifics docs. I believe you’re trying to use an API that was introduced in 5.2.x

v5.1.5
https://pixijs.download/v5.1.5/docs/PIXI.Graphics.html#lineStyle

Latest:
https://pixijs.download/v5.2.1/docs/PIXI.Graphics.html#lineStyle

**Comment by tari3x** [comment]
Oh. I just took the one from the top of https://github.com/pixijs/pixi.js/releases. Didn't realize they were not sorted. 

I didn't notice any error message when trying to use the wrong api, is that expected?

I tried the new one and it works, thanks!

**Comment by bigtimebuddy** [comment]
You tried to use a new API on and older version. And, in general, we don’t runtime type check users input. Best to just check with the right documentation or use TypeScript. 

Closing this, as it seems answered.

**Comment by tari3x** [comment]
> use TypeScript.

That's fine, I use js-of-ocaml, so I only make each API mistake once.

**Comment by crutch12** [comment]
No typescript definition for this options overload ☹
