### ISSUE TITLE
[BUG] this.material._renderCanvas is not a function at v5.2.1-legacy

### ISSUE THREAD

**Issue by Fxlr8** [pixijs/pixi.js#6491]
I use a mesh with a custom shader to render a minimap in my game. When the canvas fallback happens my app crashes with this error.

### Steps to Reproduce
Here is a small demo to reproduce the problem
https://codesandbox.io/s/pixi-canvas-bug-ifhd5

### Environment

- **`pixi.js` version**: _e.g. 5.2.1-legacy_
- **Browser & Version**: _Chrome 80_

**Comment by ivanpopelyshev** [comment]
OK, now I understand what you meant. 

However, I dont understand how do you think it can work at all?  I mean, you provided information. Supose you have that info and canvas2d. Which operations would you use to render your mesh?

**Comment by Fxlr8** [comment]
I think it should render nothing and log a warning. This is much better than crashing the whole app.

**Comment by ivanpopelyshev** [comment]
OK, then it should be easy to make PR for `canvas-mesh` module to check if material actually can render stuff. I can do it later if no one else does.
