### ISSUE TITLE
What does Application.resize do?

### ISSUE THREAD

**Issue by tari3x** [pixijs/pixi.js#6492]
- **`pixi.js` version**: 5.2.1

  This is more of a question than a bug report I suppose. Not sure where questions should go. The two code pieces below are not doing the same thing. Would it be possible to clarify in the documentation what Application.resize does?

```
app.renderer.resize(window.innerWidth, window.innerHeight);
```
and 
```
app.resizeTo = Window;
app.resize ();
```

**Comment by bigtimebuddy** [comment]
These should do the same thing.

Calling `app.renderer.resize` might create issue since `app.resize` is a convenience wrapper around `renderer.resize` and will likely override it. If you aren't using Application, use `renderer.resize`, if you are using Application stick to `resizeTo` and `resize`.

**Comment by tari3x** [comment]
They don't do the same thing for me, here's a fiddle to demonstrate the difference: https://jsfiddle.net/62c9h3pz/

**Comment by tari3x** [comment]
The fiddle looks like it uses an older version, but I get similar behaviour with 5.2.1.

**Comment by bigtimebuddy** [comment]
This works: https://jsfiddle.net/bigtimebuddy/tpuw798g/

`window` not `Window`

**Comment by tari3x** [comment]
Oops, my bad! Thanks for the help!

**Comment by bigtimebuddy** [comment]
No problem.
