### ISSUE TITLE
SpriteSheet.destroy(true) does not delete entries from TextureCache

### ISSUE THREAD

**Issue by cloudmark** [pixijs/pixi.js#6506]
Spritesheet.destroy(true) does not remove all items from the TextureCache.  To reproduce 

```typescript
const app = new Application({
        width: 640,
        height: 480,
        backgroundColor: 0x000000});

Loader.shared.add('assets/spritesheet-png8.json').load(setup);

function setup() {
   const sheet = Loader.shared.resources['assets/spritesheet-png8.json'].spritesheet;
   sheet.destroy(true);
   console.log(utils.TextureCache);
}
```

A potential workaround, for now, is to remove the elements from the cache directly.  

Use the resources from the following [repository](https://github.com/CodeAndWeb/pixijs-sprite-sheets/tree/master/images)

**Comment by cloudmark** [comment]
This is my current workaround, just in case someone else has this issue. 
 
```typescript
   sheet.baseTexture.textureCacheIds.forEach(Texture.removeFromCache);
````

**Comment by bigtimebuddy** [comment]
Ah, I see the problem.

Basically, the TextureLoader creates a Texture that isn't managed at all by the Spritesheet. So we have a texture that's never used that's hanging out. Likely the loader should clean that up.

**Comment by cloudmark** [comment]
Also, I'm struggling with another leak,  when I destroy the spritesheet, I'm noticing that there are times that the spritesheet texture loads later (even though I've destroyed it) and the texture and base textures are still present in texture cache.  I've not yet been able to reproduce it but at the top of your head would this seem plausible?

**Comment by cloudmark** [comment]
Wow, a fix! great stuff! Will try to reproduce the above.

**Comment by bigtimebuddy** [comment]
I don’t know what that may be. Keep seeIng if you can reproduce the error.

**Comment by cloudmark** [comment]
What I'm noticing is that when I call `resource.abort` on a sprite sheet, the resource is still calling all middlewares.  One of those middlewares is the TextureLoader and so I end up with mostly a 1x1 pixel (EMPTY_GIF) or at times (rarely) the full size of the image.  Unfortunately, I cannot replicate it in a concise example but it's happening.  To replicate on my machine I switch rapidly between two sprite sheets and this causes the warning to start appearing.  

VM6787 vendor.js:92867 BaseTexture added to the cache with an id [xxx] that already had an entry

I think there is a problem with the loader in that the middlewares are still called when the underlying resource is aborted.

**Comment by ivanpopelyshev** [comment]
> What I'm noticing is that when I call resource.abort on a sprite sheet, the resource is still calling all middlewares

We dont have any code related to aborts in pixi, this is sole feature of `resource-loader`. Need a demo + possible fix for that. I dont think it will be fixed without extra user input.

**Comment by bigtimebuddy** [comment]
@cloudmark could you file an issue about `abort` here: https://github.com/englercj/resource-loader like @ivanpopelyshev  said that abort functionality is not maintained by this repository.
