### ISSUE TITLE
Resizing renderer with resolution greater than one 

### ISSUE THREAD

**Issue by alex-brc** [pixijs/pixi.js#6510]
I am currently facing an issue regarding scaling the renderer or canvas on a high DPI device (or more specifically, with `devicePixelRatio > 1`). 

### Expected behavior
From my understanding, setting `resolution: devicePixelRatio` together with `autoDensity: true` should allow the canvas to adjust seamlessly to the size of the renderer (resized using `renderer.resize()`). 

### Current behavior
Check out this [fiddle](https://jsfiddle.net/zjo5xpsh/44/) for an example where this fails on my device with windows scaling set to 125%, (i.e. `devicePixelRatio = 1.25`). As you resize the viewport you can see pixels stretching into odd shapes. 
**Note** Resizing works just fine if I turn windows scaling to 100% (i.e. `devicePixelRatio = 1`).

### The long way around
In the jsfiddle there's a block of code commented out at line 40 that does what (from my understanding) the renderer does internally to adjust for the DPI, i.e. multiply the canvas and  renderer sizes by the scaling factor and then use CSS style to scale the canvas back down.

This _does_ seem to improve things, oddly enough (perhaps someone could explain exactly why) but there is still some stretching going on (in both my application and the fiddle, there is _exactly one_ "stretch" line, as opposed to _many_ in the previous case, and _none_ with no scaling).

**Edit 2:** This workaround actually fixes the issue entirely. At the time of writing, I had mistakenly _left in_ the settings for `autoDensity = true` which introduces this single "stretch" (which, arguably, is worth looking into all on its own). For posterity, that bit of code requires `autoDensity = false` and `resolution = 1`, i.e. default settings.

### Environment

- **`pixi.js` version**:  5.2.1
- **Browser & Version**: Vivaldi - Chromium 80.0.3987.158 (64-bit) (also on the latest stable versions of Chrome, Edge and Firefox as of writing this)
- **OS & Version**: Windows 10 v1903
- **Running Example**: https://jsfiddle.net/zjo5xpsh/44/

Apologies if this is just me being a knob, been fighting this one for a couple days now.

**Edit:** Here are some gifs to illustrate the issue. Note the "squishing" and "stretching" of the pixels in the first example.
`devicePixelRatio = 1.25` 
<img src="https://i.imgur.com/G8No6nt.gif" width="280" height="242.5" />
`devicePixelRatio = 1`
<img src="https://i.imgur.com/S74FmxH.gif" width="280" height="242.5" />

**Comment by ivanpopelyshev** [comment]
It is not a bug. PixiJS has no mechanism of detecting changed `devicePixelRatio`.

I  think its because so far there was no good enough implementation that could be considered a general solution for resizing with resolution. 

We prefer to allow library user to make application component that resizes renderer for particular game.

I can only point that you can set `renderer.resolution` before you call `resize` method - that should work.

You mentined `autoDensity` , well, there's no magic :)

https://github.com/pixijs/pixi.js/blob/3ef0c85bc30fbbfbcdbccf3f86ef3441440ad199/packages/core/src/AbstractRenderer.ts#L275-L285

**Comment by alex-brc** [comment]
Hey Ivan, big fan here, your insightful answers help us noobies everywhere! 

My wording there may have been a little confusing there. It is **not** an issue of _changing_ the resolution while the renderer is running. I was just pointing out that the setup presented in the fiddle _works as expected when scaling is off_, but does not when scaling is > 1. I have augmented the initial post with a couple gifs showing these artifacts.

**!!!** 

As I was writing this comment, browser scaling came to mind. It seems that browser scaling **does** factor in to the `devicePixelRatio` and such may of interest here. For example

- If I set Windows Scaling to **125%** (getting a `devicePixelRatio = 1.25`) the artifacts appear when resizing the viewport (by dragging the sides with the mouse). If, however, I _also set the the browser zoom to **80%**_, achieving a detected `devicePixelRatio` of 1, the artifacts disappear almost entirely*. If I set the Windows Scaling to **150%** (getting a `devicePixelRatio = 1.50`) and set browser scaling to **66%** , once again, the issue disappears (well, in this case not quite because of the resulting `devicePixelRatio` of but it is much much better than before), so this seems to be consistent.

- If, on the other hand, I have my Windows Scaling to **100%** but set the browser 

This again tells me that I might be doing something wrong, because it kind of feels like I'm fighting the system here. Check out the fiddle and play around with the browser scaling and you should be able to reproduce this. 

As I didn't quite make clear in the initial post, I seem to have found a solution to this: instead of using `autoDensity` and `renderer.resolution`, I can do those computations manually in the `resize()` function and it works pretty well. However, it's not the _expected behaviour_ here so if this was the intended behaviour, we should update some documentation to better illustrate the function of these settings. 

***Note:** I say almost, because in fact, there is still one "stretch" line occurring on my main application where I am using a larger sprite as a base, and looks exactly like the result from "the long way around" method, but this is not visible on this smaller sprite, and is possibly an unrelated issue.

**Comment by ivanpopelyshev** [comment]
Hm, do you think its another rounding problem?

**Comment by alex-brc** [comment]
I did suspect rounding initially, manually rounding the positions of each sprite did not seem to fix the problem, so I assumed that something internally was overcoming that. 

Here's a list of things I tried and didn't work (in combination with using the renderer settings, not manually resizing everything - I was aiming for neatness), as well as some other notes and ideas that may help, in no particular order:

-  Matching `renderer.resolution` with the sprite's scale, i.e. set `renderer.resolution = 1/4` when setting `sprite.scale.set(4)`. That didn't work, and only made the "stretching" more obvious, as instead of the pixels stretching by 1/4 of a pixel, now they stretched by a full pixel.

- Setting `PIXI.settings.ROUND_PIXELS = true` had no effect on this, good or bad.

- As mentioned above, using `Math.floor()` when setting sprite positions did not affect the end result. In fact, the artifacts occur even when fixing the sprite position and only resizing the window, so this probably does not play into the issue.

- It is worth noting that I was encountering some _texture bleeding_. At the time, I fixed it by just extruding the textures in the spritesheets, but in retrospect, it might have been caused by this issue.

- You mentioned dynamically changing `devicePixelRatio` but from playing around with the fiddle, it seems to be adapting on the fly. By adapting, I mean the artifacts immediately disappear when setting the scales such that `devicePixelRatio = 1` and immediately reappear when that balance is upset. 

- It should be noted that these artifacts are not introduced by the act of resizing the viewport in itself, but rapidly changing the size of the viewport makes them more apparent. This issue bothered me because it caused misalignment of some sprites when the viewport had certain dimensions (whether that was the initial size or the size that the viewport was resized _to_). You can find examples of these "magic" sizes with the fiddle example too.

That's pretty much what comes to mind right now. I'll keep an eye on this issue and add anything I might remember later on.

**Comment by ivanpopelyshev** [comment]
I mean canvas size / css size rounding. For 1.25 error there can lead to up to 3 extra column of pixels appearing or something like that. btw, in case of roundPixels I advice to use `PIXI.settings.RESOLUTION = devicePixelRatio` too , it affects formulas for roundPixels because its done in stage and independently from renderer.

**Comment by alex-brc** [comment]
This issue seems to be caused in a way by the `image-rendering: pixelated` in `canvas`.  The images were compressed slightly but you can still make out the differences - sorry for the size, but scaling them up made the artifacts harder to spot.

`image-rendering: pixelated` **off**: As the image moves from right to left, every pixel is supersampled slightly, leading to a loss in sharpness, but each pixel moves just as much as the others.
![pixelated off](https://i.imgur.com/8sPt0G5.gif) 

`image-rendering: pixelated` **on**: Much sharper, no supersampling, but some pixels are stretched. Take a close look at the second column from right to left, second pixel from bottom to top.
![pixelated off](https://i.imgur.com/ACAWtxp.gif)

**Comment by ivanpopelyshev** [comment]
OK, then its probably canvas size is something like 643 when css corresponds to 640 real pixels. Need a way to calculate and debug it

**Comment by alex-brc** [comment]
Yes it's most likely something like that. If you look at the text displays in the fiddle, (in my case, with dpr 1.25) it never touches odd number dimension, i.e. the viewport tag says 499px but `window.innerWidth = 498`.
