### ISSUE TITLE
AnimatedSprite doesn't work when .textures are swapped on 'dev'

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi.js#6512]
### Expected Behavior
If you have an animatedSprite with textures ['1', '2', '3'], but then swap them out for textures ['a', 'b', 'c'] and called updateTexture(), you'd expect to see texture 'a' displayed 

### Current Behavior
After https://github.com/pixijs/pixi.js/pull/6487 - this now stops a texture update if the frameIndex hasn't changed. This is fine for when .textures stays the same between calls, but if they're swapped out dynamically, this breaks. Maybe resetting previousFrame to null when textures is set might help

### Possible Solution
Previous PR needs re-investiga

### Environment
- **`pixi.js` version**: dev
- **Browser & Version**: Chrome 80
- **OS & Version**: Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/-elBHgYoZlcYkIALyPXC4

**Comment by bigtimebuddy** [comment]
Makes sense. Pinging @JetLua, can you take a look at this? We should add a unit-test for setting textures.

**Comment by themoonrat** [comment]
I've had a little hack, and just adding

```
this._previousFrame = null;
```
above
```
this.gotoAndStop(0);
this.updateTexture();
```
in the textures setter seems to work, but not had a chance to verify properly. Should be easy to unit test any fix
