### ISSUE TITLE
Interactivity blocks JS's main thread

### ISSUE THREAD

**Issue by flekschas** [pixijs/pixi.js#6515]
### Current Behavior

I am using PIXI for rendering an interactive scatterplot with 2K (or more) sprites.

When I turn on interactivity on the root container (e.g., `stage.interactive = true;`), I noticed that JS's macro tasks are severely slowed down (several hundred milliseconds to a few seconds per `setTimeout(() => {}, 0)` call). I was confused as animations still work okay, so I turned off all the event listeners and profiled my application.

What I found were repeated calls on every pointermove event that take ~12ms per call.

<img width="754" alt="Screen Shot 2020-04-02 at 10 30 55 AM" src="https://user-images.githubusercontent.com/932103/78261370-279deb80-74cd-11ea-932f-11aaa2d08316.png">

As far as I understand, the current interaction handling is throttled by 10ms. So my current guess is that this causes a buildup that blocks other macro tasks. (i.e., the next pointermove event callback is added before the previous is processed) I could be entirely wrong also.

My question is, what is the interaction manager doing in `processInteractive()` that is making the function call take 12ms even when there are no listeners? Is it expected to take this long for ~2K sprites?

Just for fun, I performed hit testing with another library that is using an r-tree for spatial queries and on average a hit test with ~2K elements takes <0.01 ms on average. Of course, PIXI has to take care of many more things. I am just trying to understand the limitations of the build-in interaction management. Does it scale linearly with the number of display elements?

### Environment

- **`pixi.js` version**: _e.g. 5.1.6_
- **Browser & Version**: _e.g. Chrome 80_
- **OS & Version**: _e.g. macOS 10.14.6_

**Comment by ivanpopelyshev** [comment]
>  I am just trying to understand the limitations of the build-in interaction management.

https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/TreeSearch.js

Full scan. Also, every sprite has `containsPoint` function. I recommend to set `interactiveChildren=false` for containers that has that many sprites, and implement your own `containsPoint` and handlers. You can also rewrite treesearch and ovverride its instance in interactionManager (`renderer.plugins.interaction`)

**Comment by flekschas** [comment]
Thanks for the quick reply and pointers! This makes a lot of sense now.
