### ISSUE TITLE
[question] PIXI.AnimatedSprite by V4.X, how to create framesAnimatedSprite

### ISSUE THREAD

**Issue by yyman001** [pixijs/pixi.js#6517]
I see the API from `PIXI.AnimatedSprite`, that use `linear array` to create AnimatedSprite.
but i want to use ` two-dimensional array` to create AnimatedSprite.
### Official API documentation:
```js

// linear array
let alienImages = ["image_sequence_01.png","image_sequence_02.png","image_sequence_03.png","image_sequence_04.png"];
let textureArray = [];

for (let i=0; i < 4; i++)
{
     let texture = PIXI.Texture.from(alienImages[i]);
     textureArray.push(texture);
};

let animatedSprite = new PIXI.AnimatedSprite(textureArray);
```
### what I want 
```js
let framesImages = [
// The first frame
 ['a1.png', 'b1.png', 'c1.png'],
// The second frame
 ['a2.png', 'b2.png', 'c2.png']
]
let animatedSprite = new PIXI.AnimatedSprite(framesImages );
animatedSprite.play()
```
eg:
![image](https://user-images.githubusercontent.com/5688485/78335553-66f93480-75c0-11ea-9ce1-4a153f323687.png)

thanks!

**Comment by themoonrat** [comment]
I would recommend creating your own custom class to handle this. Your custom class can have 2 instances of `AnimatedSprite` - which all have their own array of textures. And your custom class can then sync up playing both animated sprites at the same time, stopping them, swapping out... whatever you want to do!

But it's not something that can be done just within 1 Animated Sprite

**Comment by yyman001** [comment]
i use `canvas` to render`['a1.png', 'b1.png', 'c1.png']`  to png
after use `PIXI.Texture.fromCanvas(canvas)` to create a `texture` and use `texture`  to create `new PIXI.Sprite(texture)`
last , `new PIXI.AnimatedSprite(SpriteList)`

```js
function createMergePng (texturesList) {
   let canvas = document.createElement('canvas')
   let context = canvas.getContext('2d')
   texturesList.forEach((layerItem, index) => {
    if (index === 0) {
        canvas.setAttribute('width', layerItem.width)
        canvas.setAttribute('height', layerItem.height)
    }
   context.drawImage(layerItem, 0, 0)
 })
 return canvas
}

let framesPng = []
let framesImages = [
// The first frame
 ['a1.png', 'b1.png', 'c1.png'],
// The second frame
 ['a2.png', 'b2.png', 'c2.png']
]
// 创建帧
framesPng = framesImages.map((pngs) => createMergePng(pngs))
// 创建实体Textures 
let framesTextures = framesPng.map(canvas =>PIXI.Texture.fromCanvas(canvas))
let animatedSprite= new PIXI.extras.AnimatedSprite(framesTextures )

```
