### ISSUE TITLE
pixi-legacy on IE 11: Object doesn't support property or method 'isNaN'

### ISSUE THREAD

**Issue by afarber** [pixijs/pixi.js#6518]
Hello, in Internet Explorer 11.1098.17763.0 having the following 2 lines -
```
<SCRIPT SRC="//cdn.jsdelivr.net/npm/pixi.js@5.2.1/dist/pixi.min.js"></SCRIPT>
<SCRIPT SRC="//cdn.jsdelivr.net/npm/pixi.js-legacy@5.2.1/dist/pixi-legacy.min.js"></SCRIPT>
```
Unfortunately results in the error message:

```
Object doesn't support propertyor method 'isNaN'
```

At the pixi-legacy.min.js (or maybe const.js) line:
```
export const GRAPHICS_CURVES = {
    adaptive: true,
    maxLength: 10,
    minSegments: 8,
    maxSegments: 2048,
    _segmentsCount(length, defaultSegments = 20)
    {
        if (!this.adaptive || !length || Number.isNaN(length))
        {
            return defaultSegments;
        }
```

### Screenshots

![ie11_a](https://user-images.githubusercontent.com/1884458/78355036-4d9abd00-75ad-11ea-868b-2fd8b00e21db.png)

![ie11_b](https://user-images.githubusercontent.com/1884458/78355044-5095ad80-75ad-11ea-862c-e5b79b96afe1.png)

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Internet Explorer 11.1098.17763.0
- **OS & Version**: Windows 10
- **Running Example**: https://apps.facebook.com/slova-farbera/

**Comment by themoonrat** [comment]
Hello! This one is my fault. Sorry!
It's also fixed, and will be released in the next version of PixiJS: https://github.com/pixijs/pixi.js/pull/6426

**Comment by themoonrat** [comment]
For now, you can add this as a quick polyfill to get IE working again

```
Number.isNaN = Number.isNaN || function isNaN(input) {
    return typeof input === 'number' && input !== input;
}
```

**Comment by bigtimebuddy** [comment]
Closing because this has been fixed.

**Comment by afarber** [comment]
Your workaround has helped with ie11 browser error, thank you
