### ISSUE TITLE
Hello! We have decided to offer the best of both worlds for this issue.

### ISSUE THREAD

**Issue by ChenSheng233** [pixijs/pixi.js#6521]
Hello! We have decided to offer the best of both worlds for this issue.
there is a new property in the interactionManager called `moveWhenInside`
Setting to true will make things work more in line with how the DOM verison works.
Setting to false will mean the `mousemove` and `touchmove` will be dispatched regardless of weather the cursor is over the object.

The default of this property is true. :+1:

_Originally posted by @GoodBoyDigital in https://github.com/pixijs/pixi.js/issues/2310#issuecomment-181811736_

Hello! I aleary Setting `moveWhenInside`  to true,but won't work. It still dispatches anywhere.
Pixi.js version is 5.2.1

**Comment by ivanpopelyshev** [comment]
Hello!
It should work. Please post the minimal demo.

**Comment by ChenSheng233** [comment]
my code has bug. it ok now

**Comment by bigtimebuddy** [comment]
Seem like user solved their own issue. Closing
