### ISSUE TITLE
PIXI.Graphics blendMode not working as expected

### ISSUE THREAD

**Issue by altitude** [pixijs/pixi.js#6522]
Hi!

Having trouble to make the COLOR_BURN blend mode with PIXI.Graphics, any help or guidance appreciated.

### Expected Behavior

![image](https://user-images.githubusercontent.com/1770991/78502521-d35f6980-7761-11ea-863f-6b66d46a584d.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/1770991/78502372-22f16580-7761-11ea-9d06-160d4088b89b.png)

### Steps to Reproduce

```javascript
import * as PIXI from 'pixi.js';

/** Init app */
const app = new PIXI.Application({
  backgroundColor: 0xF5F5F5,
  forceCanvas: true,
});

document.body.appendChild(app.view);

const r1 = new PIXI.Graphics();
r1
  .beginFill(0xFFF0BC)
  .drawRect(0, 0, 100, 100)
  .endFill();

const r2 = new PIXI.Graphics();
r2.blendMode = PIXI.BLEND_MODES.COLOR_BURN;
r2
  .beginFill(0x000000)
  .drawRect(50, 50, 100, 100)
  .endFill();

app.stage.addChild(r1, r2);
```

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Safari 13.1 / Chrome 80
- **OS & Version**: macOS 10.14.6

Thanks!

**Comment by SukantPal** [comment]
The pixi.js library doesn't support special blend modes: https://pixijs.download/release/docs/PIXI.html#.BLEND_MODES.

"IMPORTANT - The WebGL renderer only supports the NORMAL, ADD, MULTIPLY and SCREEN blend modes. Anything else will silently act like NORMAL."

pixi-pictures _tries_ to add some blend modes: https://github.com/pixijs/pixi-picture. I'm not sure if it will work for `COLOR_BURN` but you can use it as a reference/example for your own shader.

---
To implement `COLOR_BURN` on your own, you will have to create a shader that takes two input textures and blends them.

**Comment by altitude** [comment]
Wow I did not catch that in the doc, thanks @SukantPal!

I have always been reluctant to dig into GLSL, I guess now's the time 😄

Closing this, thanks again for the clarification.

**Comment by luludada** [comment]
If you are using pixijs 4.8.7, then it will work as you expected.
https://www.pixiplayground.com/#/edit/XZP7hN7AdXzYqeSXHWYqp

**Comment by altitude** [comment]
This is awesome, thanks for the heads-up @luludada!
