### ISSUE TITLE
Anti-aliased 

### ISSUE THREAD

**Issue by ChenSheng233** [pixijs/pixi.js#6523]
`
app = new Application({
        transparent: true,
        backgroundColor: this.backgroundColor,
        autoDensity: true,
        antialias: true,
        resolution: window.devicePixelRatio,
        height: this.height,
        width: this.width
      });

 let graphics = new Graphics();
      graphics.beginFill(0x26a69a,1);
      graphics.lineStyle(1,0x26a69a,1);
      graphics.drawRect(this.width / 2, this.height / 2, 30, 60);
      graphics.endFill();

app.stage.addChild(graphics);`
![图像 2](https://user-images.githubusercontent.com/39158941/78505686-a9309a80-77a7-11ea-8bcd-1c1fff7c52b0.png)
How I Anti-aliased it

**Comment by SukantPal** [comment]
It should be anti-aliased. I don't see a problem.

**Comment by ChenSheng233** [comment]
![图像 2](https://user-images.githubusercontent.com/39158941/78539657-80e78100-7825-11ea-8864-e0873e23b772.png)

It not anti-aliased

**Comment by eXponenta** [comment]
Antialiased.
Try rotate it and looks again.
Rect is wrong test for it, should be `stairs` for AA.

If not - u have device without AA (winXP). This is device problem, use FXAA Filter for it.
