### ISSUE TITLE
BindTexture: `tex` is from a different (or lost) WebGL context.

### ISSUE THREAD

**Issue by altro50** [pixijs/pixi.js#6525]
### Expected Behavior
My container with sprites renders correctly.

### Current Behavior
A warning is thrown [inside the bind method of TextureSystem](https://github.com/pixijs/pixi.js/blob/3ffe52d29aedd79a5a281b4a6032e7c95f5ea98c/packages/core/src/textures/TextureSystem.ts#L148) and the sprites inside of the container are a garbled mess of other existing sprites.

on Chrome (Chromium) the warning (error?) is
`WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context`

and on Firefox the warning is
`WebGL warning: bindTexture: `tex` is from a different (or lost) WebGL context.`.

Other sprites render correctly.

All my textures are loaded with Texture.from.

- **`pixi.js` version**: 5.2.1, lowest tested is 5.0.4
- **Browser & Version**: Firefox 75.0b11, Chromium 84
- **OS & Version**: Windows 10 1809

**Comment by eXponenta** [comment]
Required demo, looks like that you try use a texture from external context.
Maybe u create new context but use texture from old.

**Comment by ivanpopelyshev** [comment]
Maybe texture has size 8192 on a device that supports only 4096. If you have size bigger than 4096, try to look in which size your device supports. Unfortunately, I'm too tired to repost it from other threads. That webgl problems was discussed all over the internets many times. `renderer.gl.getSomethingLikeParameter(renderer.gl.SOME_CONSTANT_STUFF_ABOUT_MAX_TEXTURE)`

**Comment by altro50** [comment]
I have been unable to reproduce this issue in an isolated demo environment (one that I can share), even when using the exact same textures. It only occurs in the project I'm working on.

> Maybe texture has size 8192 on a device that supports only 4096.

I assume you mean the horizontal resolution of the sprite? That's only 345 and the sprite is used in different places where it is rendered correctly

What's interesting is that removing a sprite from a different container (another child container from the parent container, for example) solves the issue as well.
This to me seems like I'm hitting some kind of limit.

In fact, moving the container two containers up fixes the issue as well, but then I'd miss out on the convenience of having it parented to the current parent (a moving) container. I'm also afraid that might cause issues down the line if I add more sprites to the application and they start having the same problem.

**Comment by altro50** [comment]
I've managed to solve the issue, it was related to having two different renderers running after each other and not pixijs itself.
