### ISSUE TITLE
BitmapText not working inside of ParticleContainer

### ISSUE THREAD

**Issue by chriskinzel** [pixijs/pixi.js#6526]
### Expected Behavior

Using BitmapText as child of ParticleContainer should work (text renders as expected). This may actually be expected behaviour (if it is I'd love to know the reasoning), I am new to PIXI.js, sorry if this is obvious.

### Current Behavior

Text does not render, error is thrown `TypeError: undefined is not an object (evaluating 'this.children[0]._texture.baseTexture'`.

### Steps to Reproduce

Sample code producing issue:
```javascript
const renderer = new PIXI.Renderer();

const container = new PIXI.ParticleContainer()

// Use this instead and it works
// const container = new PIXI.Container()

document.body.appendChild(renderer.view);

PIXI.Loader.shared.add('font', 'https://pixijs.io/examples/examples/assets/bitmap-font/desyrel.xml')
    .load(startup);

function startup()
{
    const label = new PIXI.BitmapText('Hello World', {
        font: {
            name: 'Desyrel',
            size: 12
        }
    });

    container.addChild(label);
    renderer.render(container);
}
```

### Environment

- **`pixi.js` version**:  _5.2.1_
- **Browser & Version**: _Safari 13.05_
- **OS & Version**: macOS 10.15.3
- **Running Example**: _https://www.pixiplayground.com/#/edit/Ht7ICjOpTamfYhtzEBMIo_

**Comment by ivanpopelyshev** [comment]
> Using BitmapText as child of ParticleContainer should work 

Should not. ParticleContainer does not look inside containers and does not executer `updateTransform`. 

If we didn’t have these restrictions, people would use ParticleContainer everywhere. Unfortunately, there's a pay for extra performance.

There's a way to make better BitmapText - switch its internal sprites to one Mesh object, you should write a generator for it.

**Comment by chriskinzel** [comment]
Cool, thanks for taking the time to let me know!

**Comment by MultiTijmes** [comment]
> There's a way to make better BitmapText - switch its internal sprites to one Mesh object, you should write a generator for it.

Ivan, could you point me in the right direction for this?
I have to use 30.000+ names in a memorial names 'river' / 'cloud'.
Using BitmapText inside a Container right now, but looking for ways to gain more performance.
Cheers. Pixi.JS is so amazing!!
