### ISSUE TITLE
No pointeroverfired after pointerover when draw line

### ISSUE THREAD

**Issue by ChenSheng233** [pixijs/pixi.js#6527]
const app = new Application({
            transparent:true,
            backgroundColor:'0xffffff',
            autoDensity:true,
            antialias:true,
            resolution:2,
            height:height,
            width:700,
            view:document.querySelect('#pixi')
        })
        app.renderer.plugins.interaction.moveWhenInside = true
        const line = new Graphics()
        line.lineStyle(1,0x26a69a,1)
        line.moveTo(40,0)
        line.lineTo(40,this._height)
        line.interactive = true
        line.on("pointerover", function(e) {
            console.log("pointerover over line");
        })
        app.stage.addChild(line)
Pixi.js 5.2.1
Browser :Chrome 80.0.3987.149

**Comment by ivanpopelyshev** [comment]
Interaction doesn't work with lines. If you want better interaction - override Graphics method `containsPoint`

**Comment by ChenSheng233** [comment]
I want highlight the line fired after pointerover. - override Graphics method not work for me

**Comment by lolski** [comment]
Is there a fundamental reason why a line isn't clickable / hoverable? I could take a stab at it if there isn't

**Comment by liuyao552** [comment]
How to monitor the click event of the line？

**Comment by yvzt** [comment]
It's been a while but I can make a suggestion. You can accompany a rectangle aligned with the line using `setTransform` method. Set alpha value of this rectangle to 0. Set listener functions on [mouse/pointer]over and [mouse/pointer]out events. 

```
// 1. PRELIMINARY COMPUTATIONS
// Coordinates of the end points of a line
let x0 = 100;
let y0 = 100;
let x1 = 200;
let y1 = 200;
// Find midpoint for translation
let xmid = 0.5*(x0+x1);
let ymid = 0.5*(y0+y1);
// Length of the line
let length = Math.hypot(x0-x1, y0-y1);
// Alignment angle of the line, i.e. angle with the x axis
let angle = Math.atan((y1-y0)/(x1-x0));

// 2. LINE 
line = new PIXI.Graphics();
// Arbitrary line style, say we have a non-white background
line.lineStyle(8,0xffffff,1);
line.moveTo(x0,y0);
line.lineTo(x1,y1);


// 3. ACCOMPANYING RECTANGLE
line.rectangle = new PIXI.Graphics();
line.rectangle.beginFill(0xffffff);
// Since we are going to translate, think of 0,0 is the center point on the rectangle
// Width of the rectangle is selected arbitrarily as 30
const width = 30;
line.rectangle.drawRect(-length/2,-width/2,length,width);
line.rectangle.endFill();
line.rectangle.alpha = 0;
line.rectangle.interactive = true;
line.rectangle.on("pointerover", reactOver);
line.rectangle.on("pointerout", reactOut);
// Apply transformation
line.rectangle.setTransform(xmid, ymid,1,1,angle);

app.stage.addChild(line);
// Add rectangle to the stage too.
app.stage.addChild(line.rectangle);

// Let's change alpha value of the line when user hovers.
function reactOver(){
   line.alpha = 0.5;
}
function reactOut(){
   line.alpha = 1;
}
```
[Experiment with PEN](https://codepen.io/yvzt/pen/NWwVbMe)
