### ISSUE TITLE
Aligned char in grid

### ISSUE THREAD

**Issue by tanhaican** [pixijs/pixi.js#6528]
### Expected Behavior
One character(alphabet) in each grid。

### Current Behavior
The characters not aligned in the grid

### Possible Solution
Help required

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/vCm9ZFRgc8QYwaTZ0JhTE

### Environment
- **`pixi.js` version**: 4.7.1 and 5.1.3
- **Browser & Version**:  Chrome 80.0.361.69
- **OS & Version**: _e.g. Windows 10
- **Running Example**: 
https://www.pixiplayground.com/#/edit/vCm9ZFRgc8QYwaTZ0JhTE

**Comment by bigtimebuddy** [comment]
Try using a monospaced font for more even spacing. The typeface you’re using each character is a different width. Alternatively, use Sprites. You are reusing the same characters, it’s more performance using Sprites and easier to position. Good luck!

**Comment by tanhaican** [comment]
@bigtimebuddy Thanks for your reply. I've tried monospaced font before the issue, and it's not work.
use Sprites is a good idea, but i'm new to pixijs, it would be great if you can share your time with some code, thanks again

**Comment by bigtimebuddy** [comment]
Look at the examples as a start https://pixijs.io/examples (Check out the BitmapText and Sprite ones) also there are other forums like html5gamedevs.com that have an active community where you might find help (generally GitHub is for bugs and library issues). YouTube also has some tutorials that people have made about PixiJS.

**Comment by tanhaican** [comment]
> Try using a monospaced font for more even spacing. The typeface you’re using each character is a different width. Alternatively, use Sprites. You are reusing the same characters, it’s more performance using Sprites and easier to position. Good luck!

I've tried many times and searched in google, still not figure it out. Is Sprite render from image but text?
Sorry about that.
By the way, as I know, Text is extends from Sprite. and in my case I'm rendering more than 5000 character, how to get a good performance with Sprites.

**Comment by bigtimebuddy** [comment]
@tanhaican did you find a solution to your problem? If so, please post the solution so that it will help others in the future.

**Comment by tanhaican** [comment]
Well, not exactly.
I've update the code here: https://www.pixiplayground.com/#/edit/frMIjusIKZiE4Mo2drzHJ
It's hard to say a good choice, but it worked.

It really not easy to find the right value fit the grid by the way, which depends on the font family, font size, letter spacing.

**Comment by tanhaican** [comment]
Another better choice with issue not fixed is overwrite the 'drawLetterSpacing' of Text.
Here is my code with a problem: the string is truncated
```javascript
PIXI.Text.prototype.drawLetterSpacing = function drawLetterSpacing(text, x, y, isStroke = false) {
  const style = this._style;
  let gridWidth = style.gridWidth;
  const characters = Array.from ? Array.from(text) : text.split('');
  const oneCharWidth = this.context.measureText(characters[0]).width;
  gridWidth = gridWidth && gridWidth > oneCharWidth ? gridWidth : oneCharWidth;
  
  let gridStartPosition = x;
  let current = '';
  let currentWidth = 0;
  let currentPosition = x;
  for (let index = 0, textLen = text.length; index < textLen; index++) {
    current = characters[index];
    currentWidth = this.context.measureText(current).width;
    let centerTxtStartPos = (gridWidth - currentWidth) / 2;
    currentPosition = gridStartPosition + centerTxtStartPos;
    
    if (isStroke) {
      this.context.strokeText(current, gridStartPosition, y);
    } else {
      this.context.fillText(current, currentPosition, y);
    }
    gridStartPosition += gridWidth;
  }
};
```
The width of the text to draw is incorrectly calculated.
