### ISSUE TITLE
[Support] Is it possible to partially update a texture?

### ISSUE THREAD

**Issue by carlsmith** [pixijs/pixi.js#6533]
I'm not sure if this is possible, and would be grateful for any advice...

I have a bunch of state stored in a typed array of around 20-30 kilobytes in length. The array is used to create a `PIXI.Texture`, which is then passed into a frag shader. Whenever the state changes, the array is updated accordingly, then the `update` method of the `Texture` instance is invoked to let the GPU know to update its copy.

The state changes often, but normally in small increments (just a few values at a time).

Is there some approach that will effectively allow the GPU to only copy over the values that have changed?

I'm trying to minimize latency, so that user inputs are reflected quickly. On my laptop (updating the entire array), the latency is imperceptible, but it uses integrated graphics with shared memory, and I don't know if that makes updating the texture faster.

Sorry for my ignorance. I'm new to writing shaders, and need to optimize things, but without properly understanding how the hardware works.

**Comment by ivanpopelyshev** [comment]
> Is there some approach that will effectively allow the GPU to only copy over the values that have changed?

Nope. I think 4-byte call of texture upload costs the same as 30kb. 

Yes, that thing is bottleneck for many apps.

**Comment by carlsmith** [comment]
Thanks @ivanpopelyshev. It seems to run fine so far. It just seemed very inefficient. Thanks for taking the time.
