### ISSUE TITLE
animatedSprite.onComplete is not a function

### ISSUE THREAD

**Issue by lululock71** [pixijs/pixi.js#6536]
Hi,
I'd like to use the animatedSprite.onComplete function but the documentation is not clear and I can't figure out how it is supposed to work.

Current documentation : https://pixijs.download/dev/docs/PIXI.AnimatedSprite.html#onComplete

I've seen that sometimes, there's a small example to explain how a function work but here, there's none.

I tried this code:
`animatedSprite.play();`
`animated_Sprite.onComplete(function () {`
`    animatedSprite.visible = false;`
` });`

But Firefox 75 console returns:
`TypeError: animatedSprite.onComplete is not a function`

I'm using PixiJS 5.1.6, development build.

I don't understand how this is supposed to work. Maybe I didn't get something.
 Can you update the documentation by giving an example, please ?

**Comment by andrewstart** [comment]
Try 
```javascript
animatedSprite.onComplete = function() {
    animatedSprite.visible = false;
};
```
It's a property that you need to set, not a class method.

**Comment by lululock71** [comment]
Thanks for the fast answer.
Can you update the documentation for future users ?

**Comment by ivanpopelyshev** [comment]
@lululock71 

Thanks to you, we will update it with example.

However, every time a person in issues asks something general about `AnimatedSprite` , I am obliged to remind that AnimatedSprite is a baseline class for users animations. Most of the time, it does not have enough features to cover what user wants in production. Thus, users have to read the source code and override things in their derived classes: https://github.com/pixijs/pixi.js/blob/dev/packages/sprite-animated/src/AnimatedSprite.ts

Here, in source, its clear that `onComplete` is a function that has to be assigned to. AnimatedSprite is written to be understood be everyone, so you guys can change everything there and adapt it to be comfortable for you :) We dont limit you to using this class, you have all the power of creation related to it in your hands.

**Comment by bigtimebuddy** [comment]
If someone wants to update docs, PR welcome!
