### ISSUE TITLE
The roughly same code can be displayed in v4, and v5 gives an error

### ISSUE THREAD

**Issue by zlq4863947** [pixijs/pixi.js#6537]
### Expected Behavior
Display the chart correctly

### Current Behavior
v4 can display normally
Error display at v5

I just learned PixiJS, can you tell me how to modify it to display it correctly? thank you very much
Here are the current errors in v5.

Program.js:125 Uncaught TypeError: Failed to execute 'getProgramParameter' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLProgram'.

### Steps to Reproduce

v4: https://jsfiddle.net/zlq4863947/0odj3sme/
![image](https://user-images.githubusercontent.com/6490251/78924889-80751180-7ad5-11ea-9975-def7cae600c6.png)

v5: https://jsfiddle.net/zlq4863947/0odj3sme/10/
![image](https://user-images.githubusercontent.com/6490251/78924841-6f2c0500-7ad5-11ea-9d53-76df771ad408.png)

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**:  80.0.3987.149（Official Build）
- **OS & Version**: MacOS Mojave 10.14.6（18G3020）
- **Running Example**: https://jsfiddle.net/zlq4863947/0odj3sme/10/

**Comment by ivanpopelyshev** [comment]
Read the migration doc: https://github.com/pixijs/pixi.js/wiki/v5-Migration-Guide#filter-default-vertex-shader

Wiki is one of main sources of information, its easy for me and other pixijs team member to modify it, compared to pixijs docs.

The problem you missed is that you need old v4 default vertex shader. v5 has slightly different defulat shadre that doesnt give vFilterCoord.

Also if your task is to make gradient , and not just filter a "background" container - now its easier to achieve that with

1. mesh shader https://pixijs.io/examples/#/mesh-and-shaders/triangle-color.js
2. texture resource, gradient in your case: https://pixijs.io/examples/#/textures/gradient-resource.js
