### ISSUE TITLE
How to create a line segment that can change the endpoint coordinates ?

### ISSUE THREAD

**Issue by elewen** [pixijs/pixi.js#6538]
```
const lineSegment = new PIXI.Graphics()
lineSegment.lineStyle(1, 0xff0000, 1)
lineSegment.moveTo(0, 0)
lineSegment.lineTo(50, 50)
```

Now I can create a line segment with the above code, but I can't change the coordinates of one end point of the line segment in the future.

In fact, I tried to show the direction and distance of the robot in real time with a movable line segment, but I didn't find the relevant implementation.

I look forward to your help. Thank you.

**Comment by ivanpopelyshev** [comment]
Graphics usual way: 
1. clear
2. fill with whatever you want

There's a technique how to change coords and ask pixi to re-calculate vertex buffers `graphics.geometry.invalidate()`  , but its not for newbies and requires extensive usage of chrome devtools or reading PixiJS sources. Here's previous issue about that: https://github.com/pixijs/pixi.js/issues/6529

Are you sure you want to go that way? 

Why not just use "lineSegment.rotation = ... " ?

**Comment by bigtimebuddy** [comment]
Ivan’s answer here is good, clear and redraw the line. Hope that answers your question sufficiently. Closing issue.
