### ISSUE TITLE
Invalid line rendering in graphics

### ISSUE THREAD

**Issue by eXponenta** [pixijs/pixi.js#6543]
Latest `cap&joints` #6502   improvements corrupt line rendering.

Target link:
https://pixijs.io/examples/?v=dev#/graphics/advanced.js

### Expected Behavior
Change pixi version to 5.2.1
### Current Behavior
Change pixi version to Latest dev

![image](https://user-images.githubusercontent.com/12572222/79038960-637c3380-7be6-11ea-97e0-1632d6ee4fc9.png)

### Environment

- **`pixi.js` version**: dev
- **Browser & Version**: all
- **Running Example**: 
https://pixijs.io/examples/?v=dev#/graphics/advanced.js

**Comment by SukantPal** [comment]
These occur when the line join/cap features are used in curves?

**Comment by bigtimebuddy** [comment]
Those features are not used in the examples. So this looks like a regression in normal line rendering.

**Comment by bigtimebuddy** [comment]
Here's an isolated example @SukantPal https://jsfiddle.net/bigtimebuddy/12k7on59/

**Comment by SukantPal** [comment]
@bigtimebuddy @eXponenta You can give feedback on #6545

**Comment by bigtimebuddy** [comment]
Thanks for fixing this @SukantPal. Closing.
