### ISSUE TITLE
whiteSpace in Pixi.TextStyle does not behave as expected

### ISSUE THREAD

**Issue by visuallization** [pixijs/pixi.js#6544]
### Expected Behavior

If in a PIXI.TextStyle the following properties are set to `wordWrap: true` and `whiteSpace: 'pre'` I would expect that I can prepend whitespaces at the beginning of the new line.

### Current Behavior

If I set  the following properties in PIXI.TextStyle  to `wordWrap: true` and `whiteSpace: 'pre'` and start a new line because wordWrapWith has exceeded I cannot add whitespaces to the beginning of the new line.

### Possible Solution

~~Always check in Pixi.TextMertics.ts if `canPrependSpaces = !collapseSpaces` and don't hardcode it to `canPrependSpaces = false`.~~

Not sure yet.

### Steps to Reproduce

1. Create a text with the following textStyle:

```
const textStyle = new PIXI.TextStyle({
      fontFamily: 'monospace',
      wordWrap: true,
      wordWrapWidth: 300,
      whiteSpace: 'pre'
    });

const textNode = new PIXI.Text('Hello World', this.textStyle);
```

2. Insert more text until line breaks due to wordWrapWidth.

3. Try to enter spaces at the beginning of the new line.

4. See spaces don't get prependend.

### Environment

- **`pixi.js` version**:  5.2.0
- **Browser & Version**: Chrome Version 80.0.3987.163
- **OS & Version**: _e.g. Windows 10 Home
- **Running Example**: _url_

**Comment by romualdovillalobos** [comment]
As a workaround is possible to use Unicode literals `const tab = '\u0009';` or `const space = '\u0020';`

**Comment by visuallization** [comment]
> As a workaround is possible to use Unicode literals `const tab = '\u0009';` or `const space = '\u0020';`

Yes thanks for the idea! :) I also already thought about it. I save the data in a database table, so I would probably want to strip it out again before saving. I was hoping for an internal fix but this workaround might be okay, if nothing else works. anyway thanks again for taking time to respond!
