### ISSUE TITLE
beginTextureFill color option only works if texture is not set

### ISSUE THREAD

**Issue by davidye** [pixijs/pixi.js#6552]
### Expected Behavior

When calling beginTextureFill() with a transparent texture and color, the Graphics should be drawn with the color visible in the background.

### Current Behavior

If a texture contains transparency and a color is specified, the color is ignored.

### Steps to Reproduce

```
// red background specified by 'color' is ignored, the fill contains transparency set by texture
beginTextureFill({ color: 0xff0000, texture:texture });

// red background is drawn correctly
beginTextureFill({ color: 0xff0000 });
```

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Chrome 80.0.3987.163
- **OS & Version**: macOS Catalina 10.15.4 (19E266)

**Comment by ivanpopelyshev** [comment]
Currently texture is multiplied by color. Yes, its not obvious, but there are many possible blends of colors and texture, and if you imagined one - doesnt mean it should be default. 

Please show me 2d renderer with graphics element where it works like that.

However, it will be good to make a demo of how to change then blend mode inside shader.

You can do it yourself using info from https://www.html5gamedevs.com/topic/44978-shader-performances/ or using plugin https://pixijs.io/pixi-batch-renderer/  , or you can wait when someone else makes that demo in this issue :)

**Comment by davidye** [comment]
@ivanpopelyshev I see - the way I imagined it was more in line with how css works - it would be nice to be able to specify the equivalent of both a background-image and background-color. Not sure if that's as common of a use case in the rendering world.

Would it be possible to add blend mode as an option to beginTextureFill?

Will take a look at the links you provided, thanks for the explanation!

**Comment by ivanpopelyshev** [comment]
> Not sure if that's as common of a use case in the rendering world.

I believe it should be good for a demo :)

**Comment by LituOffi** [comment]
I made a little demo just there : https://www.pixiplayground.com/#/edit/fy91M72_nYOrfR4kyWwfh
this would have another utility, you can still have a background without getting your texture loaded.

**Comment by davidye** [comment]
@ivanpopelyshev @SukantPal - I'd like to tackle for my project soon but I'm not too familiar with the PIxi codebase - any chance you could give a brief outline of what parts I'd need to modify to make this work? Thanks!
