### ISSUE TITLE
LineStyle alignment default value in document

### ISSUE THREAD

**Issue by EIA** [pixijs/pixi.js#6553]
PixiJS API Documentation：
https://pixijs.download/dev/docs/PIXI.LineStyle.html
<img width="471" alt="" src="https://user-images.githubusercontent.com/1102087/79206407-df3de080-7e71-11ea-93b7-9b5fc2d0f2e3.png">

Src：
[https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/styles/LineStyle.ts](https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/styles/LineStyle.ts)
<img width="627" alt="" src="https://user-images.githubusercontent.com/1102087/79203075-16f65980-7e6d-11ea-8440-c834544a2958.png">

@default:0
public alignment: 0.5;

---
Test from [JSFiddle](https://jsfiddle.net/angelliya00/td6Lh0cw/5/):

**Comment by ivanpopelyshev** [comment]
"outter",,,  ok

Wanna make a PR? Default has to be 0.5

**Comment by EIA** [comment]
OK, but i don't know what should i do...
create an branch and push update?

commit message like 'Document update #6553' ?

**Comment by EIA** [comment]
Thanks @ivanpopelyshev, i made a PR  :)
