### ISSUE TITLE
How to access "heartsQ.png" in sprite sheet?

### ISSUE THREAD

**Issue by afarber** [pixijs/pixi.js#6557]
Good evening, I have a question please:

I have read [How to optimize your PixiJS game for fast loading](https://github.com/CodeAndWeb/pixijs-sprite-sheets) and tried to understand the [PIXI.Loader](http://pixijs.download/release/docs/PIXI.Loader.html) doc.

With Texturepacker I have created a sprite sheet cards254x400.png and [cards254x400.json](https://slova.de/raspasy/images/cards254x400.json) and it contains a hearts queen card there:

```
{"frames": {
"heartsQ.png":
{
	"frame": {"x":1270,"y":1200,"w":254,"h":400},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":254,"h":400},
	"sourceSize": {"w":254,"h":400}
},
```

However I cannot understand how to access it now, how to make a PIXI.Sprite of it? Here is my code (and I have tried other code too...):

```
function setup(loader, resources) {
        console.log(resources);
        var heartsQ = new PIXI.Sprite(resources['heartsQ.png'].texture);
        app.stage.addChild(heartsQ);
}

app.loader
    .add('images/cards254x400.json')
    .load(setup);
```

But the error is:

![heartsQ](https://user-images.githubusercontent.com/1884458/79263550-4d46cf80-7e93-11ea-98d7-6501bded2c2d.png)

I have tried to print the `resources `parameter with console.log(), but can not find any queen of hearts related string there

Please help.

### Environment

- **`pixi.js` version**: 5.21
- **Browser & Version**: Firefox 68
- **OS & Version**: Windows 10
- **Running Example**: https://slova.de/raspasy

**Comment by ivanpopelyshev** [comment]
its in the spritesheet. `resources['images/cards254x400.json'].textures`

**Comment by bigtimebuddy** [comment]
@afarber that's a good answer from Ivan. I'm going to close this issue as it seems to be answered. You can always use html5gamedev.com as a good place for asking questions when you're getting started with PixiJS.
