### ISSUE TITLE
PIXI.State.blend is reset to 'true' upon PIXI.Mesh creation

### ISSUE THREAD

**Issue by Vanilagy** [pixijs/pixi.js#6558]
After playing around with meshes a bit, I noticed that I was only able to disable GL blending **after** creating a Mesh. However, the Mesh takes as a parameter a PIXI.State argument, in which one can already disable blending. This change is lost upon Mesh creation, which doesn't seem like good library ergonomics to me.

### Expected Behavior
The mesh renders correctly with blending disabled.
### Current Behavior
The mesh renders with blending enabled, despite disabling blending in the PIXI.State object.
### Possible Solution
---
### Steps to Reproduce
Here, I create a fiddle: https://jsfiddle.net/0b1nvrzt/51/
You'll need to scroll down a bit past all the setup preamble, to the part with a lot of whitespace at the bottom. There you will find more instructions in comments.
### Environment

- **`pixi.js` version**: _5.2.1_
- **Browser & Version**: _Chrome 80.0.3987.163_
- **OS & Version**: _Windows 10.0.18362 Build 18362_
- **Running Example**: _https://jsfiddle.net/0b1nvrzt/51/_

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital made this API.

Workaround:

```js
state.blendMode = PIXI.BLEND_MODES.NONE;
```

**Comment by Vanilagy** [comment]
Another workaround is to set the state after mesh creation.

**Comment by ivanpopelyshev** [comment]
Are you sure? i think `renderer.state.set(this.state)` will reset blend again.

**Comment by Vanilagy** [comment]
Oh, idk... in the fiddle I made, it worked if I set it after creating the Mesh!
