### ISSUE TITLE
mode.length is undefined (v4 to v5 migration)

### ISSUE THREAD

**Issue by sandcobainer** [pixijs/pixi.js#6567]
```
Safari: TypeError: undefined is not an object (evaluating 'mode.length')
Chrome: core.es.js:9876 Uncaught TypeError: Cannot read property 'length' of undefined
    at StateSystem.setBlendMode (core.es.js:9876)
    at BatchPlugin.flush (core.es.js:12047)
    at BatchPlugin.stop (core.es.js:12078)
    at BatchSystem.setObjectRenderer (core.es.js:5545)
    at BatchSystem.flush (core.es.js:5557)
    at Graphics._render (graphics.es.js:3125)
    at Graphics.render (display.es.js:1622)
    at Container.render (display.es.js:1627)
    at Container.render (display.es.js:1627)
    at Renderer.render (core.es.js:11262)
```
Looks like the setBlendMode in `core.es.js:10304` receives an `undefined` value and is unable to handle it. This error is generated due to migrating from v4 too v5. Is there something on the migration doc that is missing? 

Edit: I debugged it further down and found the blendMode for one of the states is `undefined`. Not sure how this changed, is it due to the migration?

```
checkBlendMode 
State : { _blendMode: undefined, _polygonOffset: 0, data: 1 }
```

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Safari 13.1, Chrome 81.0.4044.92
- **OS & Version**: Mac OS X
- ** url ** : https://eerie-demon-34169.herokuapp.com (check console log)

**Comment by ivanpopelyshev** [comment]
Can you debug how exactly blendMode was set to undefined? it should be a number.

**Comment by ivanpopelyshev** [comment]
I think its related to your BatchPlugin, need more information about it. 

Please look at our basic batch plugin for v5 : https://www.pixiplayground.com/#/edit/CMKvgOt-bvlCG4QHdswIP

Beware, the api was changed several times in v5!

And for a plugin by @SukantPal for easier implementation: https://github.com/pixijs/pixi-batch-renderer/

**Comment by sandcobainer** [comment]
I am going backwards through the trace and there are few different function calls to setBlendMode to check. I'll get back to this thread once I do find the undefined.

Also I haven't set up a BatchPlugin in my application yet. Are you suggesting I do? The v4 app ran fine without batch rendering and I would like to keep it the same if possible.

**Comment by ivanpopelyshev** [comment]
oh its default one? 

Right, so you assigned "undefined" blendMode to sprite or graphics. Search which one :) You can place a conditional breakpoint there: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/batch/AbstractBatchRenderer.ts#L361

if `!element.blendMode` , stop and look at the element, which sprite is it. Hope you have some ID system for sprites to track them

**Comment by sandcobainer** [comment]
You were right, I am using a bunch of Graphics and none of them have blendMode set. 
Correct me if I'm wrong, v4 didn't require a `blendMode` or at least it defaulted to some integer value? 
In v5, would I simply have to set all my Graphics to normal?

**Comment by ivanpopelyshev** [comment]
v5 graphics blendMode is alias for `graphics.state.blendMode` , if you get undefined there - its somewhere in your code. Pixi default value is Normal.

If its not like that for you - please prepare the minimal demo, it might be another one webpack problem :)

**Comment by sandcobainer** [comment]
Definitely something going wrong with Webpack since my handful of graphics do not use blendMode at all. I'm trying to compile a minimal demo

**Comment by sandcobainer** [comment]
Definitely something going wrong with Webpack since my handful of graphics do not use blendMode at all. I'm trying to compile a minimal demo

**Comment by ivanpopelyshev** [comment]
Hm.. does it work in dev but not in prod?
