### ISSUE TITLE
JSDoc 3.5.5 Breaking Builds on Node 12

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#6571]
## Overview 

We have a known problem that **pixi.js** does not build on Node 12+. This is creating issues for us moving forward and more and more users are stubbing their toe on this issue as Node 12 has become the default LTS. Asking people to use nvm to use Node 10, isn't a great solution.

### Problem

The underlying issue is a dependency `requizzle@0.2.1`, this is a child-dependency only of `jsdoc@3.5.5`. The newer version of JSDoc 3.6.x have fixed this issue however upgrading from 3.5.5 to 3.6.x causes issues for us where documentation is missing (e.g., https://github.com/jsdoc/jsdoc/issues/1425) because JSDoc upgrading their parsing engine. I was hoping we'd get through TypeScript and we could move swiftly to [TypeDoc](https://typedoc.org/) instead of JSDoc, but that probably isn't going to happen soon.

I tried to upgrade to requizzle in the package-lock as a temporary fix, but that didn't work. There were some issues with typings generation and other problems (these might be because of Node 12). I gave up after about an hour trying to trace down bugs.

### Potential Fix

In order to upgrade to JSDoc 3.6, someone needs to build the docs and manually check that we aren't dropping documentation. I think we've put this task off long enough and we should try to address. I'm going to attach a bounty to this in hopes that someone would be willing to step up and help. It's a some tooling work and lots of manually checking and updating JSDoc blocks.

Upgrading to the newest JSDoc _could_ also impact our typings, since these are generated using [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc). This typing generation is temporary solution, but we need to make sure this isn't impacted either.

### Related 

Related bugs or mentioned in these issues:

* #5724
* #6247
* #6546

_Note on Bounties: We award users who are first-to-merge and we consider PRs in the order in which they are submitted. Bounties are paid through OpenCollective._

**Comment by SukantPal** [comment]
https://github.com/pixijs/pixi.js/pull/6572

**Comment by bigtimebuddy** [comment]
Great work @SukantPal!
