### ISSUE TITLE
How to bring parent layer on top?

### ISSUE THREAD

**Issue by iamappmaker** [pixijs/pixi.js#6573]
I have 2 objects rectangle and text

app.stage.addChild(text);
app.stage.addChild(rectangle);

text.addChild(rectangle);

Now rectangle is in top, i need to move it back and bring text on top.

**Comment by themoonrat** [comment]
If you have object a, and b is a child of object a, then a will render first, and then it's children will. So b will render second, and appear over the top of a.

Rethinking your object relationships will be the easiest way out of this. If both objects have the same common parent, then you can use zIndex to then change the order of children and thus the rendering order

**Comment by iamappmaker** [comment]
I understood. I want to set background color or image for text.
I need to show a text on rectangle. I set text as parent because i need to edit the text . If i select the rectangle as parent i cannot edit the text because selected object will be graphic. I am working on image and video editor, user will click text and edit it, change color, etc. so i want text object as parent.
If not possible to implement it then i need to think other way to achieve it

**Comment by themoonrat** [comment]
You can set some objects as interactive or not, or change interactiveChildren. You can set a hitArea on a parent container. You could have a transparent overlay that handles touches.

But the parent child relationship that you are switching isn't going to work for you, I'm afraid, as that's effects the order rendering occurs in.

**Comment by SukantPal** [comment]
@iamappmaker Look at puxi.js `TextWidget': https://github.com/pixijs/pixi-ui/blob/master/packages/core/src/TextWidget.ts.

You can set a background on it. It's display-object graphs looks like:

```
- insetContainer
     -  background
     -  contentContainer
             - textDisplay
```

**Comment by SukantPal** [comment]
If you need further help, feel free to reopen this.
