### ISSUE TITLE
Adding tint to a PIXI.Sprite.from() crashes in at Object.tintWithMultiply (pixi-legacy.js:41770)

### ISSUE THREAD

**Issue by Elrinth** [pixijs/pixi.js#6574]
### Expected Behavior
tint being applied.

### Current Behavior
console error:
pixi-legacy.js:45645 Uncaught TypeError: texture._frame.clone is not a function
    at Object.tintWithMultiply (pixi-legacy.js:45645)
    at Object.getTintedCanvas (pixi-legacy.js:45596)
    at CanvasSpriteRenderer.render (pixi-legacy.js:46905)
    at Sprite._renderCanvas (pixi-legacy.js:46965)
    at Sprite.renderCanvas (pixi-legacy.js:47494)
    at Container.renderCanvas (pixi-legacy.js:47496)
    at Container.renderCanvas (pixi-legacy.js:47496)
    at Container.renderCanvas (pixi-legacy.js:47496)
    at CanvasRenderer.render (pixi-legacy.js:45407)
    at animate ((index):277)

### Possible Solution
Change the line
"var crop = texture._frame.clone();"
in function "tintWithOverlay: function (texture, color, canvas) {"
to:
"var crop = texture.crop;"
around line 45693 on legacy pixi.

I'm assuming the "tintWithPerPixel: function (texture, color, canvas) {"
also has this problem!

### Steps to Reproduce
add a sprite with tint.

### Environment
 * pixi.js-legacy - v5.2.1
 * Compiled Thu, 16 Apr 2020 19:10:18 UTC
Google Chrome 80.0.3987.162
Windows 10 Pro 1809
N/A running example.-

**Comment by ivanpopelyshev** [comment]
yeah, but `texture.crop` is deprecated property, its alias for `texture._frame`

https://pixijs.io/examples/#/demos-basic/tinting.js - if I pass `{forceCanvas:true}` to App constructor - it works.

Most probably you made something wrong in your app like `texure._frame= { x : 0,y:0 , width:1, height:1 }` where it should be Rectangle.

Please provide a demo.

**Comment by Elrinth** [comment]
I think you are correct! I will update my loader file to create rect instead of adding the crop. I will provide my format in this issue soon. Windows update atm so typing from phone atm.

**Comment by Elrinth** [comment]
I fixed my code to create a Rectangle now rather than a normal object. Now it works perfectly.
[http://elrinth.com/assets/js/libs/pixi/pixi.sprdef.js](url)

There was never an error in pixi's code here.
Working on a game on elrinth.com
