### ISSUE TITLE
How to smoothie animation

### ISSUE THREAD

**Issue by mtwzim** [pixijs/pixi.js#6575]
Hi guys, i tried to create a soft animation, but not a loop, i tried the PIXI.Ticker, ok i believe that Ticker at a loop and i can stop this, but the loop (for) not await the finish of animation.

I read the docs but i did not find this like, 
![image](https://user-images.githubusercontent.com/42474938/79703080-cbceb300-827f-11ea-9f40-33b5f83423d1.png)

this is my map and the objective is move the avatar not in loop, and with soft animation.

I tried this: `this.application.ticker.add((delta) => {
              this.habbo.x -= 1 * delta; // traz
              this.habbo.y -= 0.5 * delta;
              this.application.stop()
          });`

but the loop not await the finish of ticker animation.

This is possible in PIXI? I really don't know how to do this.

Await for response, sorry for my bad english.

**Comment by bigtimebuddy** [comment]
The best way to answer your question is to provide an example of code. A screenshot in this case doesn’t give people much context to help. Also, if you’re looking for project specific help, please consider posting on forums like html5gamedevs.com.

**Comment by mtwzim** [comment]
This is not specific project help, my question is about how things working in PIXI.js, thank's for you response, issue updated.

**Comment by bigtimebuddy** [comment]
Closing, seems like you got an answer here: https://www.html5gamedevs.com/topic/45202-pixijs-how-to-build-a-soft-sprite-animation-not-loop/
