### ISSUE TITLE
PixiJS slow on Chrome@Android devices

### ISSUE THREAD

**Issue by ruanpiano** [pixijs/pixi.js#6577]
### Expected Behavior
- Fluid animations (60fps or as near as possible to 60fps).

### Current Behavior
- Laggy animations on Chrome at Android devices. Tested with multiple smartphones running android with Chrome at latest version.

- Works fine on PC or with Firefox on Android.

### Possible Solution
- Not known yet

### Steps to Reproduce
1. Click on play button
2. As soon as the song stars, a sound analyser should be presented in the page
3. On Android Devices running Chrome, the animation is quite laggy;  While on PCs or with Android Devices running Firefox, the animations shows smoothly.

- Fiddle available: https://jsfiddle.net/ruanpiano/f02y9d5e/4/
- Or you can check it out on production: http://intimateband.s3-website-sa-east-1.amazonaws.com/index.html

### Environment

- **`pixi.js` version**: 5.2.0
- **Browser & Version**: 81.0.4044.111
- **OS & Version**: Android 10
- **Running Example**: https://jsfiddle.net/ruanpiano/f02y9d5e/6/ (jsFiddle) or http://intimateband.s3-website-sa-east-1.amazonaws.com/index.html (AWS S3)

**Comment by bigtimebuddy** [comment]
You should profile this with DevTool and isolate your example to figure out what's eating your performance. Mobile devices are generally slow and you probably need to optimize your app/visualization some more.

Looking quickly at your code, I think the choice to use Graphics here is not the best idea. Even though you just drawing a bunch of rects, Pixi still has to triangulate all those rectangles every tick (60fps) and update the geometry on the GPU. That's a lot more work than is necessary. My suggestion is to use `Sprite.from(Texture.WHITE)` to create your waveform visualization bars. Then set height on each Sprite instead of clearing and redrawing Graphics every time.

**Comment by ruanpiano** [comment]
Hi @bigtimebuddy, I've followed your suggestion, and changed my code. But it is still slow on Chrome @ Android devices.

Updated code: https://jsfiddle.net/ruanpiano/f02y9d5e/3/

**Comment by ivanpopelyshev** [comment]
In V5 difference between Sprite with white texture and graphics with rect isnt big - pixi detects them and optimizes automatically.

I think using many elements on top of canvas can be slow, and you use canvas2d somewhere at the same time. Strange, I dont even see where are those bars.

Yes, need profile, I think there can be something wrog with that JS code.

**Comment by ruanpiano** [comment]
Hello @ivanpopelyshev.

The bars are on the footer of the page. It wasn't appearing because of CORS, but I've already updated the Fiddle.

You can check it out on: https://jsfiddle.net/ruanpiano/f02y9d5e/6/

Bars:
![image](https://user-images.githubusercontent.com/56006135/79932530-1ab54d80-8424-11ea-8832-97ac67d9acf3.png)

**Comment by ruanpiano** [comment]
I've done a JavaScript CPU Profile.

I didn't find anything special that maybe causing the slowdown.

Follow attached the Chrome CPU Profile file:

[CPU-20200429T090259.cpuprofile.zip](https://github.com/pixijs/pixi.js/files/4551493/CPU-20200429T090259.cpuprofile.zip)

**Comment by LeifRoss** [comment]
Came across this comment on complete accident, however, I did notice the same thing with a slowdown in chrome on android when debugging a few weeks back. It appears to happen when rendering anything rounded after a few seconds from init. The animation was a smooth 60FPS. however, the second something rounded was rendered, either a arc, a circle or a rounded rectangle, it dropped down to 24FPS and started lagging. Replacing the rounded object with a regular rectangle in later tests did not trigger the lag, and rendering a rounded graphic when the animation was starting did also not trigger the lag. Nothing sort of resetting the entire context after the lag has started fixes the issue. This happens on chrome on android for phones, but is not triggered on tablets for some reason. Almost like the context is forced into some sort of power saving mode.
