### ISSUE TITLE
cannot make texture from arcs?

### ISSUE THREAD

**Issue by lidaof** [pixijs/pixi.js#6585]
Hi there,

I am trying to make a sprite from a texture, and this texture will based on an arc i draw use the `arc` function, playground is here: https://www.pixiplayground.com/#/edit/35dooA2mlDQN5yNaY83tA

there is no error on the console, but my sprite is now showing. Any suggestion? Thank you so much in advance.

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**:  Chrome
- **OS & Version**: OSx

**Comment by bigtimebuddy** [comment]
Fixed your demo https://www.pixiplayground.com/#/edit/35dooA2mlDQN5yNaY83tA , you had an extra line that was rendering the arc a second time outside of the region: `app.renderer.render(t, arc)`

Render is already handled by `generateTexture`.

**Comment by lidaof** [comment]
Thank you @bigtimebuddy so much!
I thought that line is necessary from some online posts...
