### ISSUE TITLE
Resize event on renderer is not triggered

### ISSUE THREAD

**Issue by luchidalgo** [pixijs/pixi.js#6586]
### Expected Behavior
`pixiApp.renderer.on('resize', () => { console.log('Resize event'});`
Should display "Resize event" when pixiApp.resize() is called

### Current Behavior
Event is not triggered

### Possible Solution
Add resize event trigger when resize() is called

### Steps to Reproduce
Write code above and launch

### Environment

- **`pixi.js` version**: latest 5
- **Browser & Version**: Chromium
- **OS & Version**: Windows 10

**Comment by bigtimebuddy** [comment]
The `resize` event has not yet been released. Will be in the upcoming 5.3.0 release. 
See https://github.com/pixijs/pixi.js/pull/6415. Until then you can use *dev*

* Latest build: https://pixijs.download/dev/pixi.min.js
* Example of resize: https://jsfiddle.net/bigtimebuddy/3t4bng2a/
