### ISSUE TITLE
PIXI 5.2.2: The animation callback function is called with elapsed frames not elapsed milliseconds.

### ISSUE THREAD

**Issue by andreytmk** [pixijs/pixi.js#6590]
File Ticker.ts: 
https://github.com/pixijs/pixi.js/blob/93835dbbecbd0b4f31c9533bde8386a71c5662e3/packages/ticker/src/Ticker.ts#L494

https://github.com/pixijs/pixi.js/blob/93835dbbecbd0b4f31c9533bde8386a71c5662e3/packages/ticker/src/Ticker.ts#L505

The animation callback function is called with elapsed frames not elapsed milliseconds since the last call. I am unable to find a mention of this in the documentation. Is this the expected behavior?

- **`pixi.js` version**: at least 5.2.2

**Comment by bigtimebuddy** [comment]
Yes, that’s right. The name deltaTime is not great... it’s not the elapsed time but a scalar value of the number of frames elapsed. A value of 1 is running at max FPS. This is useful for multiplying tween calculations or simulation ticker to keep up with lower frame-rates.  Documentation probably needs some better explanation here.

**Comment by ivanpopelyshev** [comment]
Main idea:

instead of 

```js
sprite.rotation += 0.1
```

people can write 

```js
sprite.rotation += 0.1 * delta;
```

That's why we pass elapsed frames there.

**Comment by bigtimebuddy** [comment]
Closing as this seems answered.
