### ISSUE TITLE
PIXI.BitmapFont is not exported???

### ISSUE THREAD

**Issue by DavidVollmers** [pixijs/pixi.js#6592]
I may be completely stupid but i am missing something...

### Expected Behavior
In the release of pixi.js PIXI.BitmapFont should be exported as described in the documentation. (https://pixijs.download/dev/docs/PIXI.BitmapFont.html)

### Current Behavior
There is no PIXI.BitmapFont

### Possible Solution
Export PIXI.BitmapFont

### Steps to Reproduce
Try to use PIXI.BitmapFont (Browser, TypeScript, whatsoever)

### Environment

- **`pixi.js` version**: _5.2.3_
- **Browser & Version**: _Google Chrome Version 81.0.4044.122_
- **OS & Version**: _Windows 10_
- **Running Example**: _https://jsfiddle.net/382gudhe/_

**Comment by DavidVollmers** [comment]
Hmmm... I just found out there is a hidden build (https://pixijs.download/dev-bitmap-font-formats/pixi.min.js) which includes PIXI.BitmapFont. Am i correct that this build originates from the branch dev-bitmap-font-formats (https://github.com/pixijs/pixi.js/pull/6347) ?

I am so confused on why there is no PIXI.BitmapFont on the official build. 😔

**Comment by DavidVollmers** [comment]
I just found out i looked into the dev documentation. I was in fact completely stupid. My deepest apologies...

**Comment by themoonrat** [comment]
Haha I enjoyed your journey!
