### ISSUE TITLE
PIXI.MeshMaterial constructor not setting tint, alpha not respected while rendering

### ISSUE THREAD

**Issue by derMart** [pixijs/pixi.js#6594]
### Expected Behavior
        var mesh = new PIXI.Mesh(new PIXI.MeshGeometry(), new PIXI.MeshMaterial(PIXI.Texture.WHITE, { tint: 0, alpha: 0.2 }));
        console.log(mesh.shader.tint, mesh.shader.alpha); // -> output: 0 0.2
        mesh.shader.tint = 0;
        mesh.shader.alpha = 0.2;
        console.log(mesh.shader.tint, mesh.shader.alpha); // -> output: 0 0.2
        //if rendered now, mesh is drawn with alpha 0.2
        mesh.alpha = 0.2;
        //if rendered now, mesh is drawn with alpha 0.2, or even alpha of 0.2 * 0.2 (?)

### Current Behavior
        var mesh = new PIXI.Mesh(new PIXI.MeshGeometry(), new PIXI.MeshMaterial(PIXI.Texture.WHITE, { tint: 0, alpha: 0.2 }));
        console.log(mesh.shader.tint, mesh.shader.alpha); // -> output: 0xffffff 0.2
        mesh.shader.tint = 0;
        mesh.shader.alpha = 0.2;
        console.log(mesh.shader.tint, mesh.shader.alpha); // -> output: 0 0.2
        //if rendered now, mesh is drawn still with alpha 1
        mesh.alpha = 0.2;
        //if rendered now, mesh is drawn with alpha 0.2

### Environment

- **`pixi.js` version**: 5.2.2
- **Browser & Version**: Chromium 81
- **OS & Version**: Ubuntu 18.04

**Comment by ivanpopelyshev** [comment]
Yes, that's a priority.

Anyway, If you dont want to wait for someone to fix it, debug this part: https://github.com/pixijs/pixi.js/blob/dev/packages/mesh/src/MeshMaterial.ts#L60

as for drawn with alpha 0.2*0.2 , need actual example to judge about that, its here: https://github.com/pixijs/pixi.js/blob/dev/packages/mesh/src/MeshMaterial.ts#L168
https://github.com/pixijs/pixi.js/blob/dev/packages/mesh/src/Mesh.ts#L311

Need to know whether this thing is batched or not, which method is called.
