### ISSUE TITLE
TilingSprite TypeError: url.indexOf is not a function

### ISSUE THREAD

**Issue by breuerfelix** [pixijs/pixi.js#6599]
I am new to PIXI.js and so far i love it.
However i wanna experiment a little bit with TilingSprites and i just found a little error.

```javascript
Loader.shared.add(path).load(() => {
  const textures = Loader.shared.resources[path].spritesheet.textures
  const panelBrown = textures['panel_brown.png'];
  console.log(panelBrown instanceof Texture)
  const spritePanelBrown = TilingSprite.from(panelBrown);
});
```
![](https://i.imgur.com/bXS7z5Z.png)

According to the PixiAPI the TilingSprite takes a Texture in the from method. The code works if i change TilingSprite to Sprite. So it is not a Problem with my Sprite.

The code also works if i instantiate the TilingSprite with the new keyboard.

```javascript
// works just fine
const spritePanelBrown = new TilingSprite(panelBrown);
```

// edit i already figured the following question out... ninesliceplane is what i need!  the error above still exists :)

I also got a question if TilingSprites are the thing i really need.

I got a squared Texture with some fancy Borders and the inside is just all the same color.  
Now i wanna scale this square but when i for example double the height, it should only expand the 'inside' and not stretch the whole sprite which would look really weird.

Can i accomplish this with tilingsprite ? so far it just repeats itself with its borders. repeating is close to what i need but now i need it to not repeat the outer 10px for example and only append it on the edges of the final tilemap.

Thanks alot in advance for taking your time!  
I hope to return some knowledge soon by making some tutorials after i got to learn pixijs even more.

- **`pixi.js` version**: _e.g. 5.2.2_

**Comment by eXponenta** [comment]
**NEVER USE FROM** !
if u dont know how it works!

`new TiledSprite(texture)`
from - is static constructor FROM RESOURCES, not from already generated textures.
Resources: Image, Canvas, Buffer, Resource instance.

// Another confirmation that you need to remove `from` totally

**Comment by breuerfelix** [comment]
![](https://i.imgur.com/eaEzasH.png)  
To me this looks like i could throw in a Texture but i just realised that Texture is not extending from BaseTexture (which the name implies). Thanks for the clarify!  
Why does it work with normal Sprites tho? I got curious because this worked and the other didn't.

i already read the pixijs 6 proposal and i would agree removing static constructors at all. they are confusing.
