### ISSUE TITLE
PIXI.Container.mask = null TypeScript error

### ISSUE THREAD

**Issue by DmitriyMenshayev** [pixijs/pixi.js#6606]
### Expected Behavior
Mask removed with `container.mask = null`.
### Current Behavior
Error `Type 'null' is not assignable to type 'Container | MaskData'.ts(2322)`.
### Possible Solution
Make mask property nullable.
### Environment
- pixi.js version: 5.2.4
- TypeScript version: 3.8.3

**Comment by bigtimebuddy** [comment]
Thanks for reporting @DmitriyMenshayev, PR has been made.
