### ISSUE TITLE
Ambiguity VideoBaseTexture and VideoResource with TypeScript

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi.js#6611]
Hello, using pixi 5.2.4 with TypeScrit.

I'm playing a video, and trying to access the source element for adding complete / ended event: 
```
const texture = Texture.from("videos/E1-intro.mp4");
const video = Sprite.from(texture);
this.addChild(video);

(texture.baseTexture.resource.source as HTMLVideoElement).addEventListener("ended", () => Main.instance.scene = new Scenario1Part1());
```
I **grab the event** but I got an error on TS side with unknow source. I tried to cast `resource` to `VideoResource` but it isn't found. Auto complete offers `VideoBaseTexture` but it seems to be no more supported.

**Comment by bigtimebuddy** [comment]
Maybe try casting the resource instead?

```ts
(texture.baseTexture.resource as VideoResource).source // should be HTMLVideoElement
```

**Comment by alamboley** [comment]
Indeed it works, thanks @bigtimebuddy: `(texture.baseTexture.resource as VideoResource).source.addEventListener("ended", () => Main.instance.scene = new Scenario1Part1());`

However in the  `import { Sprite, Texture, VideoResource } from "pixi.js";` is not found.

**Comment by alamboley** [comment]
Ok got it with:
```
import { resources, Sprite, Texture } from "pixi.js";
(texture.baseTexture.resource as resources.VideoResource).source.addEventListener...
```

**Comment by bigtimebuddy** [comment]
Cool, glad that worked! Also, I'm not sure why VideoBaseTexture is showing up in your typings. That shouldn't be there. Make sure you don't have `@types/pixi.js` in your project. Those are v4 typings.

**Comment by alamboley** [comment]
Got it, there was in a global folder!
