### ISSUE TITLE
Children fail to trigger mouseout when parent container has hitArea

### ISSUE THREAD

**Issue by CodeSmith32** [pixijs/pixi.js#6614]
### Description
After setting `hitArea` on a PIXI.Container, I notice its children don't always trigger the `mouseout` event. It occurs when both the container and the children should trigger the `mouseout` in the same step: instead only the parent container triggers it, but the child remains 'stuck'.

Hopefully the example clearly illustrates this:
https://jsfiddle.net/codesmith32/akbt06ef/33/
Move the cursor over the buttons, and then off of them quickly. It should be observable that only the container changes, but the button's 'hover' state will remain, unless moving the cursor slowly. Again, commenting out the 'Offending line' (line 65) will turn off the container `hitArea`, and it works again.

### Expected Behavior
I'd expect that when moving the mouse out of a container and off of its children, even if triggered by the same event, both container and child should trigger the `mouseout` event. This is the case, up until a `hitArea` is defined on the container and the mouse leaves both the `hitArea` and the child's `hitArea` at the same time.

### Current Behavior
When moving the mouse out of both container and child `hitArea`s at the same time, only the container's `mouseout` is triggered.

### Possible Solution
I noticed that removing the container's `hitArea` seems to fix it. And even without the `hitArea` set, the container seems to respect the rounded rectangle shape as it's *implicit* `hitArea`. This actually works for me. I'm not sure if it works for others, though, who may need more complex or different `hitArea`s and I'm unsure if this is correct / expected behavior (or, perhaps I'm misusing something...).

### Environment
- **`pixi.js` version**:  5.2.4
- **Browser & Version**:  Chrome 80
- **OS & Version**:  Win 10
- **Running Example**:  https://jsfiddle.net/codesmith32/akbt06ef/33/

**Comment by ivanpopelyshev** [comment]
its a known problem, it has workarounds
1. dont use hitArea if you dot want to limit children interaction, use `containsPoint` if you want just to make an area for container (not "interaction mask")
2. test your own search algorithm, just set `renderer.plugins.interaction.search` to your instance of  https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/TreeSearch.js . There, you can fix the problem and if it works for you - make a PR. next pixi version will be breaking some stuff so we can experiment with that behaviour too
