### ISSUE TITLE
pixi.js.d.ts: BezierUtils etc. are missing from the TS definition

### ISSUE THREAD

**Issue by Ciantic** [pixijs/pixi.js#6616]
1. Open the pixi.js.d.ts thats bundled with NPM package ([direct link to distributed pixi.js.d.ts](https://unpkg.com/browse/pixi.js@5.2.4/pixi.js.d.ts))
2. Search for `QuadraticUtils` or `BezierUtils`

Notice, that all the definitions are missing? Yet, they are inside the javascript file, but not in d.ts.

The `graphicsUtils` is missing a lot of other definitions too e.g. `bezierCurveTo`...

**Comment by bigtimebuddy** [comment]
These aren't included because they are private classes an only used internally. Also, our typings are currently generated from our JSDoc, so anything that's private is not included.

**Comment by Ciantic** [comment]
Okay, I assumed some bezier code were intended to be public when reading this #527 but apparently not?

**Comment by Ciantic** [comment]
I will close this. I think everything intended is already public in PIXI.Graphics.
