### ISSUE TITLE
The GPU memory usage increase in mode WebGL 1

### ISSUE THREAD

**Issue by KayacChang** [pixijs/pixi.js#6619]
The GPU memory usage from 254MB to 2.5 GB cause computer crash.

### Current Behavior

- In Desktop mode, WebGL 2
![WebGL1](https://user-images.githubusercontent.com/32451546/81837737-cf501400-9577-11ea-9b66-008894d3ca2b.jpg)

- In Mobile mode, WebGL 1
![WebGL 2](https://user-images.githubusercontent.com/32451546/81837724-cbbc8d00-9577-11ea-9d12-64f7e361a4ee.jpg)

### Steps to Reproduce

1. Start pixi.js project and Open Chrome 

2. Open Chrome Debug tools

3. Select toggle device tool bar

4. Open Activity Monitor

### Environment

- **`pixi.js` version**: 5.2.3
- **Browser & Version**: 81.0.4044.138 (Official Build) (64-bit)
- **OS & Version**: Mac mini 10.14.6

**Comment by bigtimebuddy** [comment]
If you could please provide a link so we can reproduce this issue that would be very helpful. Thanks!

**Comment by KayacChang** [comment]
Hello, @bigtimebuddy Thanks for help.
[This is my repo](https://github.com/KayacChang/BlackJack)

**Comment by KayacChang** [comment]
Hello @bigtimebuddy , Maybe I know where cause this issue.
My previous setting set the application in 
```js
  const app = new Application({
    width: 2560,
    height: 1440,
  });
```
This setting will cause GPU memory increase.

If I try set the application in 
```js
  const app = new Application({
    width: 800,
    height: 600,
  });
```
And this work fine in webGL1.
