### ISSUE TITLE
A screenshot of a 10,000 x 10,000px image takes so long!

### ISSUE THREAD

**Issue by KagiJPN** [pixijs/pixi.js#6620]
HELLO!
The code for the screenshot was hung on the official PixiJS sample page.
I used it to make a screenshot feature, but it's very time consuming to save.

If you have any best practices that would make it faster when saving large images, please let me know.

I'm having a lot of fun developing with this library.
I'm looking forward to it!

```
function takeScreenshot() {
  app.renderer.extract.canvas(viewport).toBlob((b) => {
    const a = document.createElement('a');
    document.body.append(a);
    a.download = 'screenshot';
    a.href = URL.createObjectURL(b);
    a.click();
    a.remove();
  }, 'image/png');
}
```

The viewport is an object of an external library called pixi-viewport.

Is this possibly the reason for the slowness?

**Comment by oteph** [comment]
Try saving it as JPG.
PNG is encoded in software and is much slower to encode in general. Try saving a 10000*10000 PNG with gimp and it will take quite the time as well. JPG is roughly 10 times faster in this case
