### ISSUE TITLE
Graphics glitch - shows other content

### ISSUE THREAD

**Issue by oteph** [pixijs/pixi.js#6624]
### Expected Behavior
Graphics render as expected.

### Current Behavior
I  have a background image over which i draw player tokens as graphics. The Tokens _sometimes_ show a glitched image of the whole background on them self. The glitch allways seems to be in the lower right corner of the graphics.

![image](https://user-images.githubusercontent.com/24698503/82037587-a2e4e680-96a2-11ea-8240-1b15593dc95f.png)

### Environment

- **`pixi.js` version**:  5.2.1
- **Browser & Version**: Version 81.0.4044.138 (64-Bit)
- **OS & Version**: Windows 10

**Comment by bigtimebuddy** [comment]
It’s hard to tell from the image exactly what we are looking at. Could you please provide a standalone example that reproduces the unexpected issue you’re seeing? That’s the best way for us to evaluate, fix and verify issues.

**Comment by oteph** [comment]
I did not manage to reproduce it.
Here's a playground with a similar setup that _fails_ to reproduce the issue:
https://www.pixiplayground.com/#/edit/b7jKUJIRk2puduhIFUIlj
(At least you can see how the scene is setup)

I'm also using https://www.npmjs.com/package/pixi-viewport do deal with pan and zoom, how can i add it to the playground?
