### ISSUE TITLE
Can't get correct scale after width and height are set

### ISSUE THREAD

**Issue by elewen** [pixijs/pixi.js#6625]
This is my code:
```
const app = new PIXI.Application({})
const robotsLayer = new PIXI.Container()

app.stage.addChild(robotsLayer)

// robot.svg real width and real height is 60px * 60px
const robotSprite = PIXI.Sprite.from( 'textures/robot.svg')

robotsLayer.addChild(robotSprite)

robotSprite.width = 6
robotSprite.height = 6
robotSprite.anchor.set(0.5)

console.log(robotSprite.scale.x) // 6
```

My robot.svg default size is 60px * 60px, when set size to 6px*6px, and then get robotSprite.scale.x, the value is 6, not 0.1 （6/60=0.1）, why? and how to fix it ?

**Comment by andrewstart** [comment]
Texture loading is asynchronous; until it is loaded the texture size is 1 as a default value. You'll need to wait for the texture to load before setting the width/height (or just set scale directly based on known size).
