### ISSUE TITLE
Changing resolution breaks text.

### ISSUE THREAD

**Issue by ZeRoss0000** [pixijs/pixi.js#6629]
When changing resolution `renderer.resolution = x`.
interaction act weird like it scaled to 1/x of screen size (with 0,0 not changing) and text quality become lower!
is there anyway to dynamically change resolution without breaking everything?

**Comment by ZeRoss0000** [comment]
`renderer.plugins.interaction.resolution = x;` fixed interaction it somehow it didn't work first time probably i did a typo.

Text act weird when resolution is lower than 1 what i did is change text resolution to
`Math.max(1, this.renderer.resolution)` but still it act kinda weird it become pixelated when i increase text resolution without even changing renderer resolution.

**Comment by ZeRoss0000** [comment]
Didn't find how to fix it tried to use SDF Text plugin but it don't support v5 will close this anyways

**Comment by ZeRoss0000** [comment]
Fixed text resolution by changing text resolution to 1 after changing game resolution :]
because text resolution get auto-updated to match renderer resolution but that get it rendered weirdly decreasing text resolution make it blurry increasing resolution make it more pixelated that's not how it should act!
so text resolution is so broken! and there is no reason to auto-update it :]

**Comment by bigtimebuddy** [comment]
Please provide an isolated example that reproduces the issue preferably using jsfiddle, codepen or another linkable playground. It's the best way for us to evaluate if it's a bug, how severe it is, if there are existing workaround, and verifies when we fix it. Thanks.

**Comment by ZeRoss0000** [comment]
Sure thing.
I think fixing this is important as i saw people trying to improve text quality by increasing its resolution/application renderer resolution and that made more pixelated actually, so they use plugins(don't support v5) or html text instead.

https://codepen.io/Zero0000s/pen/Vwvqbbp
i did some tests changing app renderer resolution and using `text.resolution = 1` is enough to change text resolution from what i have seen! so a quick fix will be to not make `text.resolution` automatically match the renderer resolution :]

**Comment by bigtimebuddy** [comment]
Is this what you mean?

**1x resolution scaled 100%**
<img width="91" alt="Screen Shot 2020-05-19 at 9 00 57 PM" src="https://user-images.githubusercontent.com/864393/82403531-eb3e3480-9a13-11ea-8eef-325a445902dd.png">

**8x resolution scaled 12.5%**
<img width="87" alt="Screen Shot 2020-05-19 at 9 00 46 PM" src="https://user-images.githubusercontent.com/864393/82403526-e7aaad80-9a13-11ea-994c-d9ae570e38f9.png">

I'm not sure this is a bug. I think the "pixelation" you're seeing is the bilinear interpolation of scaling a very large texture down very small. I would expect this. 

Overall, changing the app resolution to change the quality of text on the fly is not a great idea. Resolution is mostly used for rendering native resolutions via deviceAspectRatio. If you are exceeding that, you are just rendering more pixels and using more memory than is useful.

So, not sure I understand the approach and it doesn't seem like a bug to me. Am I missing something?

**Comment by ZeRoss0000** [comment]
ah, that don't happen with other textures only with text, setting text resolution to 1 get rid of it without effecting quality that make me wonder what the resolution option in text is helpful for, also increasing resolution will actually increase quality bc  antialiasing i guess that's what atleast most of people recommended to fix quality and it did work for me in other cases like making textures from graphics (until i stopped doing that), + this don't happen only with resolutions that are larger 1 but even with resolutions lower than 1 (i added resolution option to my game so players can change it will be helpful for players that have potato computers) if i change resolution to 0.5x and scale it to 200% it will be blurry unlike other displayObjects setting text resolution to 1 fix everything :]

**Comment by ZeRoss0000** [comment]
i think you are correct the pixelated texture made me get confused! 
ah increasing resolution can solve quality problems in some cases like textures generated from graphics(stopped doing that) and alot of people recommended it!
its annoying to have text act different than other displayObjects (im not pretty sure how they get rendered so ye..)
maybe changing text.resolution manually change to resolution*scale instead ?

**Comment by themoonrat** [comment]
If, for each text you create, you set the resolution manually, it'll turn off the auto resolution feature.
So just set text.resolution = 1, and it'll never scale after that.

**Comment by ZeRoss0000** [comment]
thank you that's helpful but i already changed scaling in the game instead of doing this.

```
this.renderer.view.style.width = w + "px";
this.renderer.view.style.height = h + "px";

this.renderer.resolution = this.resolution;
this.renderer.rootRenderTarget = this.renderer.resolution;
this.renderer.plugins.interaction.resolution = this.renderer.resolution;

this.renderer.resize(w, h);
this.app.stage.scale.set(scale);
this.app.stage.position.x = w/2;
this.app.stage.position.y = h/2;
```

i did this :]

```
this.renderer.view.style.width = w + "px";
this.renderer.view.style.height = h + "px";

this.renderer.resize(w * this.resolution, h * this.resolution);
this.app.stage.scale.set(scale * this.resolution);
this.app.stage.position.x = w * this.resolution /2;
this.app.stage.position.y = h * this.resolution /2;
```

but i still think that text resolution should get automatically updated to match  resolution * scale bc scale have effect resolution you can change resolution using resize and scale only like i did here.
