### ISSUE TITLE
Animated gifs on page cause high cpu usage in Chrome

### ISSUE THREAD

**Issue by Griverson** [pixijs/pixi.js#6633]
Then i add some animated gifs on page with any pixi renderer, performance drops dramatically.

### Expected Behavior
CPU idle time is big
![pixi_gif_2](https://user-images.githubusercontent.com/65619363/82363267-3d805500-9a16-11ea-894c-8056051608af.png)
### Current Behavior
CPU idle time is low
![pixi_gif_1](https://user-images.githubusercontent.com/65619363/82363263-3c4f2800-9a16-11ea-8434-4098567c912d.png)
### Possible Solution
Don't use animated gifs and PIXI renderers together.
### Steps to Reproduce
This behavior can be seen in the [example](https://grivers.com/site/pixi_gif/).
If you remove gifs or pixi renderer by click on corresponding buttons, everything returns to normal.
### Environment

- **`pixi.js` version**: 5.2.4
- **Browser & Version**: Chrome 81
- **OS & Version**:  Windows 10
- **Running Example**: [Link](https://grivers.com/site/pixi_gif/)

**Comment by SukantPal** [comment]
@Griverson I see that the FPS with the GIFs are still low after removing Pixi. The FPS with Pixi but without the GIF is 60.

This seems like a browser bug - the majority of the time goes in "painting" & not in scripting.

**Comment by SukantPal** [comment]
@Griverson If you don't use Pixi, and use a Canvas2D context directly, then don't see this problem, then we could consider this a bug _possibly_ pixi-related.

**Comment by Griverson** [comment]
@SukantPal I reproduced the problem on clear WebGL and will send bug report to Chrome. 
This is reproduced if there is a heavy cpu load at the start of rendering. Pixi gives it because of engine initialization. For WebGL example I add some hard calculations on start. See [example](https://grivers.com/site/webgl_gif/).
Thank you.

**Comment by SukantPal** [comment]
@Griverson Can we close this? Feel free to reopen it if Chrome devs say there is something we can change!

**Comment by Griverson** [comment]
Yes, of course.
