### ISSUE TITLE
Graphics stops drawing after a certain number of calls

### ISSUE THREAD

**Issue by eranimo** [pixijs/pixi.js#6635]
### Expected Behavior
Graphics should be able to draw as much as requested.

### Current Behavior
Graphics stops after a certain number of calls.

### Possible Solution
Split the calls into a number of graphics calls.

### Steps to Reproduce

- create a new Graphics object
- in a loop, draw thousands of rectangles
- notice that Graphics stops drawing new rectangles after a certain number of calls (i think this depends on your hardware)

### Environment

- **`pixi.js` version**: _e.g. 5.0.3
- **Browser & Version**: _e.g. Chrome 80
- **OS & Version**: OSX 10.14.6
- **Running Example**: https://codepen.io/ferguillaume/pen/pmdKVw ([found in this issue](https://github.com/pixijs/pixi.js/issues/5707#issuecomment-494722310))

----

I'm trying to build a hexagonal grid tilemap with overlapping tilesets. After abandoning a sprite-per-hex approach, I tried to implement chunking with Graphics using beginTextureFill but then I realized that I wouldn't be able to have overlaping tiles outside of each chunk since each chunk would be its own texture (Unity seems to have this issue too, which makes me think chunking is impossible for this use case). This means I have to have a single Graphics call for the entire map. But I discovered that there's an undocumented maximum call limit.

I tried sharing GraphicsGeometry instance across multiple Graphics objects, but that had no effect on this limit.

Is there a way around the limit?

**Comment by bigtimebuddy** [comment]
I believe this is a duplicate fixed with #6417.

Please try using https://pixijs.download/dev/pixi.min.js which has support for this feature.

**Comment by eranimo** [comment]
Thanks. Has that been released yet? I'm not seeing this fixed on the latest version (v5.2.4)

Updated codepen with v5.2.4: https://codepen.io/eranimo/pen/ExVGGKR

**Comment by bigtimebuddy** [comment]
No, this will be in v5.3.0. If you need a hack, [use this](https://github.com/pixijs/pixi.js/wiki/v5-Hacks#pixigraphics).

**Comment by oh-wo** [comment]
Thanks very much for your workaround and fix on this one. I wonder if one of you could help me out as I learn PIXI; I just ran into the issue above (and solved it with your workaround); I hope this is an ok place to ask these questions;

- I have been creating a few graphics objects at app load which I then clear and draw to many times
- Is making many calls to a `Graphics` instance each render loop expected or is that abusing this api? 
- Initially I tried sprites/child objects and so on but because I am drawing so many shapes I think drawing like this is faster
- Is there a different recommended approach? 

Thanks very much.

**Comment by ivanpopelyshev** [comment]
Dear @oh-wo. Its all about balance. I saw cases when it was the abuse, I saw others where this was normal. 

For tilemap case, I commented it so many times, and I made so many posts about it, but , unfortunately, no article. 

The strange thing is why do you have to refill graphics that shows part of your map every frame? Tiles are usually static, you can just move them around with transform and that's it.

**Comment by oh-wo** [comment]
Thanks for the comments; sounds like I'm doing it about right although potentially could split some of my graphics objects out a little.

> why do you have to refill graphics that shows part of your map every frame
I have about 5-10 graphics objects in total and update these as necessary each frame, not all by default every single time (e.g. if changes to one graphics are needed, then that is updated independent of the others). The rest are mostly just moved around as you say. 
So there is some specificity but thinking about it now it could probably be broken up a bit more, although I'd have to think about how to do this well.

Anyway; thanks very much for the ideas.

**Comment by eranimo** [comment]
Any update on this?

**Comment by bigtimebuddy** [comment]
@eranimo this was added #6417 and should be in v5.3.x

https://jsfiddle.net/bigtimebuddy/chtdkz29/
