### ISSUE TITLE
Cannot read property 'valid' of null

### ISSUE THREAD

**Issue by saatana97** [pixijs/pixi.js#6636]
### Expected Behavior
got a gril's eyes follow my mouse
### Current Behavior
got problem when runnig example codes
Uncaught TypeError: Cannot read property 'valid' of null
### Possible Solution
armatureDisplay = factory.buildArmatureDisplay('shizuku', 'shizuku');
throw error when render this obj
### Steps to Reproduce
create index.html include pixi.js and pixi-dragonbones.js and pixi-spine.js
donwload the example codes for EyeTracking in the chapter PLUGIN-DRAGONBONES into index.html
run and then I got this problem
any solution?thanks!
### Environment

- **`pixi.js` version**: 5.2.4
- **Browser & Version**: Chrome 81.0.4044.138
- **OS & Version**: _e.g. Windows 10
- **Running Example**: none

**Comment by saatana97** [comment]
[index.txt](https://github.com/pixijs/pixi.js/files/4655701/index.txt)
this is my code,include in index.html,here ara some examples that I think currently work
in the index.html only include this file and pixi.js and pixi-dragonbones.js and pixi-spine.js

**Comment by SukantPal** [comment]
@saatana97 I suspect pixi-dragonbones has not been updated for PixiJS 5.

https://github.com/cinkonaap/pixi-dragonbones/blob/d8c1fa7aabb058d292e6cf888d1cca06939d5713/package.json#L30

**Comment by bigtimebuddy** [comment]
I think should file this issue on pixi-dragonbones instead of here.

**Comment by saatana97** [comment]
> @saatana97 I suspect pixi-dragonbones has not been updated for PixiJS 5.
> 
> https://github.com/cinkonaap/pixi-dragonbones/blob/d8c1fa7aabb058d292e6cf888d1cca06939d5713/package.json#L30

but the PIXI's examples run with PixiJS 5
and My pixi-dragonbones download from PIXI's examples on github
the online examples work successful but not work if donwloaded to local

**Comment by SukantPal** [comment]
@saatana97 If you "online example" works, a link to it would be helpful so we can investigate what's going on easier.

**Comment by saatana97** [comment]
> @ saatana97如果“在线示例”有效，则指向它的链接将很有帮助，因此我们可以更轻松地调查正在发生的事情。

https://pixijs.io/examples/#/plugin-dragonbones/eyetracking.js
I'm learning from here
but only logic code no reference libary js files
my reference libary js files are downloaded from PIXI's Github
