### ISSUE TITLE
Problem with initializing existing canvas with Pixi.Application

### ISSUE THREAD

**Issue by webbahproject** [pixijs/pixi.js#6639]
Im sorry for not following the template given for raising issue.

My problem start when i cannot load image from https URL due to cross origin. Checked with my superior on that, and that setting cannot be changed. I used Pixi Loader to load image like this

```
Loader.add([{
	        name: "display",
	        url: source,
	        crossOrigin: true
	    }])
	    .load((loader, resources) => generateImage(resources));
```
Where source is the https URL for that image that i tried to fetch. I also tried with crossOrigin : "" and crossOrigin : 'anonymous' but both didnt work.

Since loading image to canvas using normal approach works, so i decided to load the image to canvas like this

```
let ctx = imgDisplayer.current.getContext('2d'); // Im using React ref here. 
		let img = new Image();
		img.onload = function(){
			imgDisplayer.current.width = img.width; // To set canvas width to image width
			imgDisplayer.current.height = img.height; // To set canvas height to image height
			ctx.drawImage(img, 0, 0);
			setCanvas(imgDisplayer.current); // Im using React here to save the loaded canvas into state
		}
		img.src = source; // This is the https URL that throws cross origin issue if i use it on Pixi Loader
```

And then try to initialize Pixi on top of that loaded canvas

`const app = new Pixi.Application(1300, 866, canvas); // Using the canvas state here
`

Im not sure if the approach above is the correct way. I've seen alot examples with instantiating Application, like Application(300, 400) and also Application({ width: 300, height: 400 }).. Im not even sure which one is the correct way, but since the above didn't throw me error, so i assume is that one. If i use Application({ width: 300, height: 400 }), it will throw me error saying webgl is not supported and ask to use canvas renderer instead.

And then with gsap, i try to modify the filter for that canvas

`gsap.to(app, { duration: 0.5, pixi: { hue: 180 } });`

But nothing happen

I'm new to GSAP (using 3.2.6) and Pixi (using 5.2.4), so i'm not sure if im doing things right here. Please help me on the proper direction for this.

**Comment by ivanpopelyshev** [comment]
> And then try to initialize Pixi on top of that loaded canvas

init webgl on top of 2d? That wont work. Even if it worked, that image could be destroyed on the first clear(), after all, you need it in texture for drawImage later, right?

Congratulations, you made my week by making the most cursed way of loading image into pixi :)

Yes, in some cases `anonymous` doesnt work anymore, I dont know why, maybe its browser-related. Here I use `crossOrigin:true` which is the same as `crossOrigin:`anonymous` according to `resource-loader` source (https://github.com/englercj/resource-loader/blob/release/3.x/src/Resource.js#L116)

https://www.pixiplayground.com/#/edit/DxodMaAr-18_fIzHMbC0i 

@bigtimebuddy do you know anything about new crossorigin problem?

@webbahproject if you want to make your own way of loading stuff - two easy ways
1. draw  something to new canvas. use `Texture.from(canvas)` . use `texture.update()` every time you change that canvas

2. make your own resource. https://pixijs.io/examples/#/textures/gradient-resource.js . Here's how pixi treats images: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/ImageResource.ts 
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/BaseImageResource.ts#L54

**Comment by ivanpopelyshev** [comment]
btw, now that I think about it, it might be that web-server on other side does something very wrong like that `https://api.ok.ru/img/stub/user/male/50.png` . We just reported this to OK tracker. 

Maybe if pixi `crossOrigin:true` doesnt work in your case - you really should report it to supplier!

**Comment by ivanpopelyshev** [comment]
Actually, you can even try it without pixi first - make an image and try drawImage it to canvas `getContext('2d');` If it does work for you - then its definitely a pixi problem.

**Comment by webbahproject** [comment]
> Actually, you can even try it without pixi first - make an image and try drawImage it to canvas `getContext('2d');` If it does work for you - then its definitely a pixi problem.

I can show the image from the https URL onto the canvas just fine like this

```
let ctx = imgDisplayer.current.getContext('2d');
		let img = new Image();
		img.onload = function(){
			imgDisplayer.current.width = img.width; // To set canvas width to image width
			imgDisplayer.current.height = img.height; // To set canvas height to image height
			ctx.drawImage(img, 0, 0);
			setCanvas(imgDisplayer.current);
		}
		img.src = source;
```

If i try to add crossOrigin setting like this, it doesnt work.

```
let ctx = imgDisplayer.current.getContext('2d');
		let img = new Image();
		img.onload = function(){
			imgDisplayer.current.width = img.width; // To set canvas width to image width
			imgDisplayer.current.height = img.height; // To set canvas height to image height
			ctx.drawImage(img, 0, 0);
			setCanvas(imgDisplayer.current);
		}
img.crossOrigin = true // Even 'anonymous' didnt work. 
		img.src = source;
```

When i try to load the https URL into Pixi Loader, it didnt work and show black box.

**Comment by webbahproject** [comment]
Also sorry if my question on this thread seems out of this world.

I saw one of the thread in here asking how to initialize existing canvas with Pixi and thought existing canvas means those canvas with image loaded onto it, when in actual its initializing empty canvas. 

The requirement i had is to build images filter  and i saw the GSAP 3 + Pixi 5 interaction examples and it was exactly what i need. Only problem is that, the images comes from a https server, It works fine when i test it with images from http server, but with https, its throwing me those cross origin error.

**Comment by ivanpopelyshev** [comment]
> Also sorry if my question on this thread seems out of this world. My first 2-3 days of learning Webgl and Pixi was really like @@:;;;

Sometimes those crazy ideas actually work ;)

> It works fine when i test it with images from http server, but with https, its throwing me those cross origin error.

Strange, usually its the other way - http images cant be loaded in https...

**Comment by Corouna** [comment]
This is the piece of code that i wrote in NextJs

```
useEffect(() => {
		// Initialization of GSAP and Pixi
		Pixi = require('pixi.js');
		PixiPlugin = require('gsap/PixiPlugin').PixiPlugin;

		// register the plugin
		gsap.registerPlugin(PixiPlugin);

		// give the plugin a reference to the PIXI object
		PixiPlugin.registerPIXI(Pixi);

		// Create instances
		const Loader = new Pixi.Loader();

		const generateImage = resources => {
			const app = new Pixi.Application({
				width: 1300,
				height: 866,
				backgroundColor: 0x000000, 
		    autoResize: true, 
		    view: document.getElementById('img-displayer')
			});

			// const app = new Pixi.Application( 1300, 866, { view: canvas });
			const display = new Pixi.Sprite(resources.display.texture);
			display.width = 1300;
			display.height = 866,
			app.stage.addChild(display);
		}

    Loader.add([{
        name: "display",
        // url: "http://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/car-dashboard-blur.jpg",
        url: "`https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/car-dashboard-blur.jpg`",
        crossOrigin: true
    }])
    .load((loader, resources) => generateImage(resources));

	}, []);
```

I have to require the plugins like that to make it work on SSR framework like NextJs. Please let me know if there's a proper approach for this.

Anyway that piece of code didn't work.. it shows as black box on the page.

It shows this error on the console

`
Access to image at 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/car-dashboard-blur.jpg' from origin '<origin url in here>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
s3-us-west-2.amazonaws.com/s.cdpn.io/16327/car-dashboard-blur.jpg:1 Failed to load resource: net::ERR_FAILED
`

If i throw away that crossOrigin property from the Loader, it wouldn't work too. 

If i use the commented URL instead

`
url: "http://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/car-dashboard-blur.jpg",
`

Then it will work. 

I can show the image just fine using canvas's drawImage method using both URLs (see the piece of code on my posts above)

All the resources to be displayed are series of images sent from https server to the page im working at, which is also hosted in a https server. Technically shouldn't be a problem since the URL is just a direct URL to show the image, but from what i read, Pixi uses ajax call to make a call to fetch that image.

There's very little sample of Pixi loading resources from https.. most of the samples i read generate the resources using relative path, where the samples were loaded from the project subfolder. Even the reference i used to start up my Pixi journey `https://greensock.com/docs/v3/Plugins/PixiPlugin` had to use http URL due to CORS issue.
