### ISSUE TITLE
Dense grid line texture cause visual artifacts

### ISSUE THREAD

**Issue by jindili** [pixijs/pixi.js#6644]
### Expected Behavior
![image](https://user-images.githubusercontent.com/73845/82807605-af471b80-9eba-11ea-9606-75b1a5ad2785.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/73845/82807620-ba01b080-9eba-11ea-8fec-60b03323b929.png)

### Steps to Reproduce
Open Pixi Playground at
https://www.pixiplayground.com/#/edit/GwXyJrgJqO8rhtqjIa-J1
Scroll the mouse wheel, the visual artifact appear when it zoom out to some value.
### Environment

- **`pixi.js` version**: 5.2.4
- **Browser & Version**: Chrome Latest or Edge Latest
- **OS & Version**: Windows 10
- **Running Example**: 
https://www.pixiplayground.com/#/edit/GwXyJrgJqO8rhtqjIa-J1

**Comment by jindili** [comment]
The artifact disappear after setting mipmap=true
 ```
var texture = PIXI.Texture.from(base64)
// ad this line below solve the artifact
texture.baseTexture.mipmap=true;
```

![image](https://user-images.githubusercontent.com/73845/83135412-62f91700-a118-11ea-832b-169fc565b5e3.png)

**Comment by bigtimebuddy** [comment]
Sounds good. Seems like you answered your own question, thanks for posting the solution. Can we close this?

**Comment by jindili** [comment]
Yes, Issue Solved. I'm closing it.
