### ISSUE TITLE
Can't read your docs (pixijs website)

### ISSUE THREAD

**Issue by NOPROD** [pixijs/pixi.js#6646]
### Expected Behavior

Learn pixi.js with fun

### Current Behavior

Can't stay more than 5 minutes on your documentation (your website)

### Possible Solution

Just stop make **all turn**, **everety time**, **directly on load**.

it's a trap ?

I don't understand how you didn't have a headache or worse when you coded this ...

Really, I stayed 5 minutes on your doc (with enthusiasm) and I had to leave my screen 10-15 minutes to get rid of my headache, my nausea (I even had eye pain, seriously guys. ..)

https://pixijs.io/examples/#/sprite/texture-swap.js (this one kill me)

### Steps to Reproduce

Stay 5 minutes on your official site to discover your documentation

### Environment

All browser

**Comment by bigtimebuddy** [comment]
This issue is not helpful or constructive and feels like trolling. I’m closing it unless the author wants to elaborate.

**Comment by NOPROD** [comment]
There is a touch of humor yes, but I did not see how to express it in another way.


If you can read code with something who turns on it all the time without being able to stop it good game to you. Me i can't.

**Comment by NOPROD** [comment]
I don't know but if you seriously browse your site :  

**_ALL OF THIS PART = FIRST DEMO WE CAN SEE ON THE MENU AT THE RIGHT (8 DEMO)_** 

https://pixijs.io/examples/#/demos-basic/container.js
https://pixijs.io/examples/#/demos-basic/transparent-background.js
https://pixijs.io/examples/#/demos-basic/cacheAsBitmap.js
https://pixijs.io/examples/#/demos-basic/blendmodes.js
https://pixijs.io/examples/#/sprite/texture-swap.js
https://pixijs.io/examples/#/sprite/animatedsprite-jet.js
https://pixijs.io/examples/#/sprite/basic.js
https://pixijs.io/examples/#/sprite/tiling-sprite.js

**_END OF PART_**


**_ALL OF THIS PART = MIDDLE OF THE WEBSITE OR DOWN_**

https://pixijs.io/examples/#/filters-basic/color-matrix.js

https://pixijs.io/examples/#/textures/render-texture-advanced.js (wow)

you are a dev, you spent 6 hours in front of a screen.

For may your eyes be a little sensitive you can fall directly on a lot of "demo" pretty aggressive.

and the worst part is that even if you try to escape this situation who the animation gives you headache and you click randomly on other demos in search of a soft animation you can get trapped by falling on several other violent animations.

Personally it is the feeling that I had with your documentation.
