### ISSUE TITLE
PIXI.Star returns an error on using.

### ISSUE THREAD

**Issue by LituOffi** [pixijs/pixi.js#6648]
### Expected Behavior
The star is drawn.
### Current Behavior
The star is not shown and return this error : Uncaught TypeError: PIXI.Star is not a constructor.
### Possible Solution
Re-implement the PIXI.Star class. 
### Steps to Reproduce
Put new PIXI.Star(0,0,50,25); and it will result an error.
### Environment

- **`pixi.js` version**: _5.2.4_
- **Browser & Version**: _Chrome 81.0.4044.138_
- **OS & Version**: _Windows 10_
- **Running Example**:  https://www.pixiplayground.com/#/edit/FEFF3OlTl28XK0vNIPFBG

**Comment by bigtimebuddy** [comment]
Star is used only internally and should not be part of the documentation. Sorry about the confusion! To draw a star use the drawStar method in Graphics.

**Comment by LituOffi** [comment]
No problem ! thanks for the fast aswner.
