### ISSUE TITLE
[Question] How to recalculate the line break after changing maxLineWidth?

### ISSUE THREAD

**Issue by StringKe** [pixijs/pixi.js#6651]
PIXIJS is a great cavans library, there is no word wrap in svg. I want to use TextMetrics in pixijs to calculate the corresponding line breaks

How to recalculate the line break after changing maxLineWidth?

```
      this.$nextTick(() => {
        const textStyle = new PIXI.TextStyle({
          fontFamily: this.element.text.family,
          fontSize: this.element.text.size,
          fill: this.element.text.color,
          align: "left"
        });
        let textMetrics = PIXI.TextMetrics.measureText(
          this.element.text.content,
          textStyle,
          true,
          document.getElementById("C" + this.element.id)
        );
        textMetrics.maxLineWidth = this.element.base.w;
        console.log(textMetrics);
      });
```

**Comment by bigtimebuddy** [comment]
@StringKe It’s helpful when you close to post your resolution so that other searching for this and having the same issue will be helped as well.

**Comment by StringKe** [comment]
@bigtimebuddy I did not solve him, I recreated the corresponding method and executed it again
