### ISSUE TITLE
AnimatedSprite is only using the anchor of the first frame for rendering.

### ISSUE THREAD

**Issue by nikeeshi** [pixijs/pixi.js#6653]
### Expected Behavior
PIXI.AnimatedSprite should use 2nd and 3rd frame's anchor to decide the position of rendering.

### Current Behavior
PIXI.AnimatedSprite only check 1st frame's anchor and decide where to render the texture, even though the field `anchor` is changed actually. When 2nd and 3rd frames are rendered, left top position looks fixed. 

### Possible Solution
Use anchor for each frames to calculate each position of the texture.

### Steps to Reproduce
Please provide two or three images with different size and anchor position.
This example works if spritesheet "slashspritesheet.json" which includes "slash1.png", "slash2.png", and "slash3.png".

```
import * as PIXI from "pixi.js";

const app = new PIXI.Application({
  width: 800,
  height: 800,
  backgroundColor: 0xffffff,
});
document.body.appendChild(app.view);

console.log("started");

PIXI.Loader.shared
  .add("slashspritesheet.json")
  .load(() => {
    let sheet =
      PIXI.Loader.shared.resources[
        "slashspritesheet.json"
      ].spritesheet;

    console.log("sheet", sheet);
    if (sheet) {
      const animation = new PIXI.AnimatedSprite([
        PIXI.Texture.from("slash1.png"),
        PIXI.Texture.from("slash2.png"),
        PIXI.Texture.from("slash3.png"),
      ]);
      animation.x = 400;
      animation.y = 400;
      app.stage.addChild(animation);
      animation.animationSpeed = 0.01;
      animation.gotoAndPlay(0);      
    }
  });
```

### Environment

- **`pixi.js` version**:5.2.4
- **Browser & Version**: Chrome 81
- **OS & Version**: Windows 10
- **Running Example**: Sorry I cannot provide.

**Comment by nikeeshi** [comment]
Workaround is to create an array of Sprite instead of AnimatedSprite, and change visibility of the Sprite to let them be animated.

**Comment by bigtimebuddy** [comment]
There's a property called updateAnchor on AnimatedSprite. Setting this will update the anchor every frame. I believe that's what the user is looking for.
