### ISSUE TITLE
Custom Cursor - Set Origin

### ISSUE THREAD

**Issue by Chroma72** [pixijs/pixi.js#6661]
Hi again. Finally got custom cursors working but had to use a .ICO instead of a .PNG image.
```
// custom cursor
const defaultIcon = "url('assets/crosshair.ico'), auto";
app.renderer.plugins.interaction.cursorStyles.default = defaultIcon;
```
My issue now is that the origin of my cursor is not centered. I looked up some CSS and I should be able to do a:
`const defaultIcon = "url('assets/crosshair.ico') 12 12, auto";`
to move the image but PixiJs doesn't recognize it and I lose my cursor to default.

**Comment by bigtimebuddy** [comment]
If your cursor is showing up correctly, the positioning is most likely a CSS/browser issue and not a Pixi issue. I’d suggest you try to use CSS directly to debug.

You may consider hiding the cursor and using pixi to follow your mouse with a Sprite of your choosing. That’s a little more work and not without drawbacks, but would give you the most control positioning.
