### ISSUE TITLE
BitmapText  tint error

### ISSUE THREAD

**Issue by cjsjy123** [pixijs/pixi.js#6667]
https://github.com/pixijs/pixi.js/blob/dev/packages/text-bitmap/src/BitmapText.ts

style.tint does not affect _tint, so it is invalid to set the color during construction, they should use the same variable to control the color

**Comment by bigtimebuddy** [comment]
Right, this is confusing! Good pointing this out. My suggestion is that `style.tint` should set `_tint` in the constructor. While we are at it, would be nice to allow setting style like `letterSpacing`, `maxWidth` to the style object. This mix of `font` properties and style properties is super unclear.

Anyone want to work on a clean-up for this?
