### ISSUE TITLE
CanvasRenderer RenderTexture not cleared

### ISSUE THREAD

**Issue by Article19** [pixijs/pixi.js#6674]
There appears to be an issue with clearing the context when rendering a container to a RenderTexture while using the CanvasRenderer (PIXI-legacy v5.2.4).

Consider this example:
https://www.pixiplayground.com/#/edit/gM7jGSOAvFhZEeJPKeGI4

Click anywhere to toggle the visibility of one of the bunnies.

Using the CanvasRenderer the context is not cleared, and the bunnies remain visible. Using the WebGL renderer (switch forceCanvas to false) this works as expected. 

I believe the issue may be here:
if (clear !== undefined ? clear : this.clearBeforeRender) {
	if (this.renderingToScreen) {
		if (this.transparent) {
			context.clearRect(0, 0, this.width, this.height);
		}
		else {
			context.fillStyle = this._backgroundColorString;
			context.fillRect(0, 0, this.width, this.height);
		}
	} // else {
	// TODO: implement background for CanvasRenderTarget or RenderTexture?
	// }
}

The 'TODO' needs to get done. It appears there is no context management for the case where we are not renderingToScreen (as I believe is the case when we are rendering a Container to a RenderTexture).

**Comment by SukantPal** [comment]
@Article19 Nice catch! This is a problem specific to canvas-rendering into a `RenderTexture`.

1. The API for `render` is inconsistent b/w the WebGL & canvas renderers.

* `clear` is false by default for canvas rendering: https://github.com/pixijs/pixi.js/blob/e43cfe31b3569049e61fcf33fd5786ebe3e3583f/packages/canvas/canvas-renderer/src/CanvasRenderer.ts#L199

* `clear` is true by default for WebGL rendering: https://github.com/pixijs/pixi.js/blob/e43cfe31b3569049e61fcf33fd5786ebe3e3583f/packages/core/src/Renderer.ts#L359

If you passed `app.renderer.render(bunny, sprite.texture, true)` it _should've_ worked, except that we didn't implement clearing render-textures in the canvas renderer.

The render-texture should be cleared on this line but hasn't been implemented: 

https://github.com/pixijs/pixi.js/blob/e43cfe31b3569049e61fcf33fd5786ebe3e3583f/packages/canvas/canvas-renderer/src/CanvasRenderer.ts#L282

**Comment by Article19** [comment]
My short-term solution for this was to add the following change to a custom build of pixi-legacy (right after the TODO comment):

// TODO: implement background for CanvasRenderTarget or RenderTexture?
context.clearRect(0, 0, this.width, this.height);

Clearing is mostly what I get up to when using a renderTexture, so this works for me - but is not feature complete. I also caught the differences in the API between WebGL and Canvas - obviously this should be unified. 

Thanks!

**Comment by SukantPal** [comment]
@Article19 Looks like the actual "default" for clearing is `this.clearBeforeRender`, which is `true` by default. That means actually the documentation is incorrect.

**Comment by Article19** [comment]
Come to think of it I remember noticing that when looking through the source code...

**Comment by SukantPal** [comment]
@Article19 That playground should work with the `fix/canvas-renderer-clear` branch: https://www.pixiplayground.com/#/edit/gM7jGSOAvFhZEeJPKeGI4
