### ISSUE TITLE
SCALE_MODES.NEAREST causes spaces between pixels of touching sprites. Any way to get pixel-perfect alignment?

### ISSUE THREAD

**Issue by UltraCakeBakery** [pixijs/pixi.js#6676]
### Expected Behavior
![image](https://user-images.githubusercontent.com/12383587/83563728-d2f20d80-a51b-11ea-8ceb-5b0cd173cba6.png)

In the image you can see a small white line between two sprites (PIXI.Sprite). Both sprites are in the same container. The sprites, according to their position and dimensions, touch each others edges.

I've got ```PIXI.settings.SCALE_MODE``` set to ```SCALE_MODES.NEAREST``` and the stage scale set to```stage.scale.set( 5, 5 )```.

The canvas is running at nearly 4k resolution (window.innerWidth / window.innerHeight). 
The artifact is only visible when the container is at specific positions.

Is there any way to get pixel-perfect alignment without background bleeding?

### Env

- **`pixi.js` version**: _e.g. 5.2
- **Browser & Version**: Edge Chromium, latest
- **OS & Version**: _e.g. Windows
- **Running Example**: Will provide if requested

**Comment by UltraCakeBakery** [comment]
Maybe it is worth mentioning that the sprites are not that big. Somewhere between 10/12 pixels in both width and height each. All sprites combine to form more impressive pieces of art later.

**Comment by bigtimebuddy** [comment]
Have you looked at roundPixels or PIXI.settings.ROUND_PIXELS?

**Comment by UltraCakeBakery** [comment]
Hi @bigtimebuddy
Because I only used integers I didn't think about it being a rounding issue. I just turned it on but it makes no difference.

**Comment by bigtimebuddy** [comment]
Could you provide an example?

**Comment by ivanpopelyshev** [comment]
To fix the bleeding you have to add padding in spritesheet.

Alternatively:
I made special shaders that clamp coords before, but i didnt port it to v5 yet. You can take https://pixijs.io/examples/#/mesh-and-shaders/triangle-textured.js and make your version.

**Comment by UltraCakeBakery** [comment]
@bigtimebuddy I will set up a playground up later today (it is currently 12:27 over here).

@ivanpopelyshev I haven't touched the spritesheet yet. Is there anything that it does besides defining the locations of sprites in a sprite atlas? In the documentation I couldn't find anything related to padding. Do you mean adding an extra outer-layer of pixels around each sprite and cutting it out when marking them in the spirtesheet? 

Using special shaders would be a bit overkill I think. I feel like it is a specific setting that I need to change to get it working the way I want. Like actual 'Pixel Perfect' placement would solve the issue. It is just the renderer is not working as I expected when setting a scale at some specific Container positions.

**Comment by UltraCakeBakery** [comment]
Sorry for the delay. Will open this issue again when I have time to setup a playground.

**Comment by UltraCakeBakery** [comment]
I failed to recreate this in the playground as well as in my own setup. It now works as expected everywhere... I guess I messed up somewhere by setting a late-night-accidental-float value or something 😅. I'll re-open this issue if it happens again and can recreate it consistently. Thanks for the help anyways!

**Comment by mkuehn94** [comment]
I seem to have a similar issue: https://www.html5gamedevs.com/topic/48222-weird-flickering-in-scene-with-a-lot-of-sprites-roughly-1000/
