### ISSUE TITLE
Best practices for scaling images on retina devices

### ISSUE THREAD

**Issue by zerostyle** [pixijs/pixi.js#6677]
Is their documentation on best practices to handle image resizing at different resolutions. I have failed to find it. I have found settings for `resolution` on the renderer. I also have found `PIXI.settings.RETINA_PREFIX`, but I'm not clear how to apply these settings. Currently I'm having issues on retina devices where my assets are getting scaled at least double the intended size.

- pixi.js: version: 5.2.4
- Browser & Version :Chrome  83.0.4103.61 (
- OS & Version: MacOS Catalina

**Comment by bigtimebuddy** [comment]
Can you provide some more info about how you were able to close? It can be helpful for people who might be looking for similar info.
