### ISSUE TITLE
Types in packages

### ISSUE THREAD

**Issue by d-shorkin** [pixijs/pixi.js#6678]
### Behavior

When writing code on **typescript**, I have a problem when using separate packages, for example, _@pixi/app_. The package is installed without types. I tried to use the declaration parameter in _tsconfig.json_ but the plugin _rollup-plugin-typescript_ apparently does work with declarations and it is also deprecated. Now we need to use the new plugin _@rollup/plugin-typescript_, but in my project, it throws an exception for some reason.

### Possible Solution

In my project, I added the `src` folder to the package and in package.json I specified `"types": "src/index.ts"`. This solves the problem but increases the size of the module. But now I don't know a better solution to this problem.

I decided to create a [Pull Request (#6679)](https://github.com/pixijs/pixi.js/pull/6679) for this, but I believe that you will find the best solution and I will take it from you in my project. 

### Environment

- **`pixi.js` version**: 5.2.4

**Comment by bigtimebuddy** [comment]
Thanks for the feedback but this is a duplicate #6016. There is a workaround in that thread using Module Augmentation. We JUST finished converting the entire project to typescript but it’s going to be a little more effort to generate typings for all packages. Basically, we are working on it. Soon!

**Comment by mayakwd** [comment]
@bigtimebuddy, still no luck? May be you need assistance?

**Comment by bigtimebuddy** [comment]
We have types now! Needs a little polish will be available in the next release, coming soon.
