### ISSUE TITLE
Need help about generating new texture from source texture with filter effect

### ISSUE THREAD

**Issue by lancety** [pixijs/pixi.js#6680]
hi all,  I am trying to generate object's shadow texture based on source object texture.
Here I borrowed sample source from another developer's demo with my implementation to show what I am expecting. 

It looks fine in the demo, but in real project when I use the returned shadow texture in new object sprite as shadow, it seems the texture is either out of texture area or totally not rendered in renderTexture instance. 

https://jsfiddle.net/lancety/4v1uwcth/1/  

Please help me to check if there is anything totally misused. Thanks.

**Comment by ivanpopelyshev** [comment]
PixiJS 5.0.0-rc.2 

we fixed many issues with filter positioning in case of `generateTexture` since then. Try latest stable or take `pixijs.download/dev/pixi.js` (pixi-legacy.js is also there)

**Comment by lancety** [comment]
I changed from renderTexture.render to renderer.generateTexture. 
Noticed if I use pixi application instance's renderer.generateTexture, the texture is created. but if I use (new PIXI.Renderer()).generateTexture(displayObject ... )  it does not export texture with the displayObject content.  

Is there something missing?

**Comment by lancety** [comment]
find out it was because I used texutre from image which the src image file was not loaded yet when it try to use the texture.
