### ISSUE TITLE
Allow container addChild call with no arg

### ISSUE THREAD

**Issue by Chnapy** [pixijs/pixi.js#6684]
Hi,
Please take this code:
```ts
const childArray = [];
container.addChild(...childArray);
```

### Expected Behavior

To do nothing.

### Current Behavior

Throw error, because it tries to use first item of given arg array.

### Details

First please note that I already carefully read #4300. My issue does **not** concern undefined/null values.
It concerns only when we give an empty array to the `addChild` function, when we use the spread operator.

We can avoid this issue by simply adding a `if(children.length)` before the `addChild` call. But in case of dynamic arrays we can forgot to do this, and the issue can appear randomly since it depends of an array size. Typically the kind of error that appears in production ! 

And also, this is not handled by Typescript.
You can do this, type checking will not complain:
```ts
container.addChild();
```

### Possible Solution

https://github.com/pixijs/pixi.js/blob/cf794b6432bc71bd2d77f1a6f4d855bc6da3cf5d/packages/display/src/Container.ts#L120

At the begining of the function, just add something like that
```ts
if(!children.length) {
  return;
}
```
If I'm right it is not a breaking change, or something that needs extra maintenance cost.

### Environment

- **`pixi.js` version**: 5.2.1

**Comment by bigtimebuddy** [comment]
This check needs to happen somewhere. The question is if that should be PixiJS’ responsibility or your application’s? If your app code may be potentially passing an empty array spread, it’s probably more your responsibility to validate your own input. In general, we have developers assume the responsibility for type checking for valid input. I remember an issue awhile ago where a user was passing a null result from document.getElementById and wanted us to throw an error. We said no to that request.

I think the short answer for me is that Pixi shouldn’t be gracefully handling this situation. If anything, I would want pixi to throw an error for no children, not silently handle it.

**Comment by Chnapy** [comment]
Ok I understand.
What do you think about explicitly handling this case with a custom error message ? 
Since it's not type checked I think we should handle this case somehow.

**Comment by bigtimebuddy** [comment]
I recently proposed to the core team that we should add asserts in the code and strip them from the minified build. That would allow people to build for development with asserts and build for production without. That approach would easily take care of this. Everyone seemed to be onboard, but I haven't started on that project yet. Maybe for v5.4.0
