### ISSUE TITLE
Unhandled errors when making new sprites

### ISSUE THREAD

**Issue by Ganakim** [pixijs/pixi.js#6686]
When making a new sprite with `new PIXI.Sprite.from(img)` with an image that doesn't exist, then there's an error that goes unhandled that isn't the most helpful to pinpoint what caused it.

**Comment by bigtimebuddy** [comment]
This is a known issue. Use Loader to handle errors like this. Also, note that `new` is necessary before PIXI.Texture.from.

I’d really love for someone to make a `fromUrl` Texture method that returns a Promise. PR welcome!

**Comment by bigtimebuddy** [comment]
I'm actually going to close this. It's a duplicate of #6514.
