### ISSUE TITLE
 how to make onclick app.stage.on('click', (e) => {} properly?

### ISSUE THREAD

**Issue by KHromak** [pixijs/pixi.js#6688]
hey guys!
Im new in pixijs, and try to make smooth app with ability to onclick on elements inside frame.

my onclick works but rarely, even if I click 40 times, 3 clicks works. 

Can you look at my[ MVC project](https://github.com/KHromak/Shapes-pixijs-gsap-game-/tree/dev) and correct me please? 

i think mistake in my Controller file, thank you

**Comment by HusakYurii** [comment]
see this line there
`this.app.stage.hitArea = new PIXI.Rectangle(0, 0, this.model.config.width, this.model.config.height / this.app.renderer.resolution);`
why you do divide only a height with resolution? I may cause the hit area be unpredictable (?)
