### ISSUE TITLE
TilingSprite does not use default Texture.EMPTY

### ISSUE THREAD

**Issue by HusakYurii** [pixijs/pixi.js#6701]
@Zyie
 @bigtimebuddy
Hey guys! 
I faced an error, which can happen very rarely (depends on how you want to create sprites), the error relates to textures you use while instantiating new TilingSprite (s).

It is not an urgent fix but more an enhancement, pls take a look

https://github.com/pixijs/pixi.js/blob/528b44223bb96e18580e72ff94461abd20ed4857/packages/sprite-tiling/src/TilingSprite.ts#L64

### Expected Behavior
TilingSprite uses this.texture property of super class
### Current Behavior
TilingSprite DOES not use this.texture property of super class which causes an error 
### Possible Solution
```javascript
// will use texture or default wich has been set in superclass Texture.EMPTY ( to be more consistent )
this.uvMatrix = this.texture.uvMatrix || new TextureMatrix(texture);
```

**Comment by ivanpopelyshev** [comment]
yes, that's a problem. Care to make a PR? =)
