### ISSUE TITLE
Nonstable Gradient Font Colors

### ISSUE THREAD

**Issue by cihanisma** [pixijs/pixi.js#6709]
### Expected Behavior
Always having same gradient font colors

### Current Behavior
Gradient colors are missing after increasing font size depending on the screen size

### Possible Solution
Finding the smaller font size not giving problems on retina and external screen

### Steps to Reproduce
<img src="https://i.imgur.com/9LstPNL.jpg" height="60">

https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%5B%22red%22%2C%22%23ffae00%22%2C%22%23e01f1f%22%2C%22black%22%5D%2C%22fontFamily%22%3A%22Verdana%2C%20Geneva%2C%20sans-serif%22%2C%22fontSize%22%3A118%2C%22fontWeight%22%3A%22bold%22%7D%7D

<img src="https://i.imgur.com/a9fUmGA.jpg" height="60">

https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%5B%22red%22%2C%22%23ffae00%22%2C%22%23e01f1f%22%2C%22black%22%5D%2C%22fontFamily%22%3A%22Verdana%2C%20Geneva%2C%20sans-serif%22%2C%22fontSize%22%3A119%2C%22fontWeight%22%3A%22bold%22%7D%7D

<img src="https://i.imgur.com/gzhXym3.jpg" height="60">

https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%5B%22red%22%2C%22%23ffae00%22%2C%22%23e01f1f%22%2C%22black%22%5D%2C%22fontFamily%22%3A%22Verdana%2C%20Geneva%2C%20sans-serif%22%2C%22fontSize%22%3A180%2C%22fontWeight%22%3A%22bold%22%7D%7D

### Environment

- **`pixi.js` version**: 5.2.4
- **Browser & Version**: Chrome 83.0.4103.97
- **OS & Version**: Catalina 10.15.5

**Comment by themoonrat** [comment]
Had a quick look, and I'm not seeing those issues, but I'm on Windows 10. I tried Chrome, Firefox and Edge.

**Comment by cihanisma** [comment]
pixelRatio of retina screen might have something with this. @themoonrat on yours maybe it can happen on much bigger font sizes.

**Comment by bigtimebuddy** [comment]
I'm also seeing this, but with different sizes ~250 things start to disappear on latest Chrome/macOS 10.14.6.

![gradient](https://user-images.githubusercontent.com/864393/84662284-781fc500-aed0-11ea-8824-4499b33e5931.gif)

**Comment by cihanisma** [comment]
Looks like it's fixed 👍

**Comment by bigtimebuddy** [comment]
Awesome!
