### ISSUE TITLE
Issue changing SimpleRope texture using texture from Spritesheet

### ISSUE THREAD

**Issue by mauriciomassaia** [pixijs/pixi.js#6711]
### Expected Behavior
change SimpleRope texture:

```mySimpleRope.texture = spritesheet.animations.circle[0]```

and later

```mySimpleRope.texture = spritesheet.animations.circle[1]```

Like you would normally update.

### Current Behavior

If you use a texture from same spritesheet it will not update the texture. Unless it uses a texture from a different baseTexture (i assume, i can be wrong).

### Possible Solution

```
mySimpleRope.texture = spritesheet.animations.circle[1]
mySimpleRope.calculateUvs()
```

### Steps to Reproduce

I create this demo to demostrate both scenarios, using spritesheet and also a sequence of images to change SimpleRope instances and I also added a Sprite changing with the same textures and it works fine with both ways.

[Source on github](https://github.com/mauriciomassaia/pixi-simple-rope/blob/master/docs/index.js) 

[Live demo](https://mauriciomassaia.github.io/pixi-simple-rope/index.html)

### Environment

- **`pixi.js` version**: _v5.2.4_
- **Browser & Version**: _83.0.4103.106 (Official Build) (64-bit) (cohort: 83_61_Win)_
- **OS & Version**: _e.g. Windows 10_
- **Running Example**: _https://mauriciomassaia.github.io/pixi-simple-rope/index.html_

Cheers

**Comment by ivanpopelyshev** [comment]
Good catch!

**Comment by ivanpopelyshev** [comment]
Found and fixed. That was a serious problem in my invariants.

**Comment by ivanpopelyshev** [comment]
Perfect demo, btw :)

**Comment by mauriciomassaia** [comment]
Thanks for the fix and the feedback :)
