### ISSUE TITLE
About filter output not same on different platform

### ISSUE THREAD

**Issue by lancety** [pixijs/pixi.js#6716]
Hi all, I have an issue about the output of filter with noise cloud. 

Here is the demo https://jsfiddle.net/lancety/w4be6x78/6/
I used sample code from https://www.shadertoy.com/view/4tGBDd
On pc chrome, the output looks ok, same output in chrome and firefox and safari of same computer.  but not same on different computers.

Another issue is ios safari shows noise cloud cutted, and android chrome shows tiled cloud, looks like broken.  
I am not sure if I missed something of pixi or it is something wrong with the filter fragment logic itself. 

If anyone could help will be great. Thanks. 

What I am expecting is - the noise cloud shows same output on all platform browsers. :)

**Comment by ivanpopelyshev** [comment]
I dont see anything here that can raise cross-platform problems. Well, except medium precision, you should use highp. 
The thing is, webgl standard dictates`the worst` precision. `mediump` is different across devices, its just not worse than what specified in standard.

**Comment by lancety** [comment]
I changed it to highp still showing different cloud shape on 2 different pc.   Since it affects performance too much , I guess even fix this issue wont make it a proper cloud for the game, I am going to find a different cloud shader which is light weight, and can control the cloud shape by given vertexes.  I will close this ticket. Thank you Ivan~
