### ISSUE TITLE
All elements has blue outline

### ISSUE THREAD

**Issue by FireworksX** [pixijs/pixi.js#6718]
### Expected Behavior
Render elements without blue outline

### Current Behavior
Now displaying elements with blue outline.
![image](https://user-images.githubusercontent.com/22668125/85223085-bf262280-b3c8-11ea-89fc-74c7d8bd99c6.png)

I try set red stroke for text, but get fail

Example code:
```js
new PIXI.Text('Preparing Round', {
    fontFamily: 'Arial',
    fill: '#ffffff',
    size: this.app.getSize(85),
    stroke: 'red',
    weight: 900,
})
```

### Environment

- **`pixi.js` version**: _5.2.4_
- **Browser & Version**: _Chrome 83.0.4103.106_
- **OS & Version**: _MacOS 10.15.4_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
I cannot reproduce: https://jsfiddle.net/bigtimebuddy/cLd0suxa/

Please provide a standalone example, not just a screenshot. That'd be more helpful.

**Comment by bigtimebuddy** [comment]
Also, check out http://pixijs.io/pixi-text-style to fiddle with the text style.
