### ISSUE TITLE
Wrong image orientation in Chrome

### ISSUE THREAD

**Issue by inukshuk** [pixijs/pixi.js#6719]
I believe this might be a Chromium issue, but it would be good to confirm this before reporting it there.

When loading textures from an `Image` or a URL the image is drawn wrong in cases where the browser rotates the image based on the Exif orientation embedded in the image's metadata. Chrome recently switched its default behavior, so when creating images via `new Image()`, these images are now automatically oriented (i.e., they might be rotated and or flipped). I think that nowadays other browsers do this as well. However, there is a serious issue when using such an image in Pixi.js.

To me, it looks like the texture's dimensions are correct, e.g., in the example below the texture is landscape but the actual pixels seem to be taken from the 'raw' bitmap data, which is not rotated. I would guess that this is an issue in Chrome, a discrepancy in the way the image is exposed to WebGL, but it could also be an issue in the way Pixi.js accesses the image data.

Here is a quick example of the issue using [an image with Exif orientation 6](https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_6.jpg). In Firefox this image is displayed correctly:

![Screenshot from 2020-06-22 18-24-05](https://user-images.githubusercontent.com/325102/85313541-7d74a500-b4b8-11ea-8336-6f4d74d623b9.png)

In Chrome you can see that texture has  the correct aspect ratio, but that the actual pixel data is wrong:

![Screenshot from 2020-06-22 18-23-59](https://user-images.githubusercontent.com/325102/85313681-ad23ad00-b4b8-11ea-961f-75c08fe7cfc3.png)

Here is the code used in the examples:

```javascript
const app = new PIXI.Application({
    width: 800, height: 600, backgroundColor: 0x1099bb, resolution: window.devicePixelRatio || 1,
});
document.body.appendChild(app.view);

const container = new PIXI.Container();

app.stage.addChild(container);

const texture = PIXI.Texture.from('https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_6.jpg');

const six = new PIXI.Sprite(texture);
six.scale.set(0.25);
container.addChild(six);
```

Is there anything we can do about this on the Pixi.js side? Thanks!

**Comment by inukshuk** [comment]
Are images  converted to `ImageBitmap` internally? In that case this might be the root of the problem: https://bugs.chromium.org/p/chromium/issues/detail?id=1082451&q=orientation%20imagebitmap&can=2

**Comment by andrewstart** [comment]
Whenever possible, yes, they are converted to ImageBitmaps - https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/ImageResource.ts#L216
As a workaround for the Chromium bug, you can override this in your projects by setting `CREATE_IMAGE_BITMAP` on the Pixi settings object.

**Comment by bigtimebuddy** [comment]
I don't think that's it @andrewstart. The use of `createImageBitmap` should be disabled by default. 

Curious that there's a slight difference in rendering if createBitmap is enabled or disabled (but no changes to orientation):
https://jsfiddle.net/bigtimebuddy/6mcbhp9w/

**Comment by inukshuk** [comment]
Thanks, I just tried this out. Enabling `CREATE_IMAGE_BITMAP` by default hits the Chromium bug (the result is more what I would expect, the texture is cut off, presumably because the width/height of the ImageBitmap differ from the Image used to create the resource).

**Comment by bigtimebuddy** [comment]
This kinda worked for me: https://jsfiddle.net/bigtimebuddy/6mcbhp9w/

Using `from-image` for `image-orientation` and drawing to a canvas first, seemed to work. (https://image-orientation-test.now.sh/)

**Comment by inukshuk** [comment]
Yes, `from-image` is actually the new default setting, so you don't need to set that. In fact, if you wanted to turn this off, you would have to set this to `none` and insert the image into the DOM for this to have an effect. What's more, you can apparently use the setting on the canvas element too and this will take precedence of the styles of individual images. This is to ensure the same setting for all images rendered into a single canvas. (I've tried using the setting on the canvas element but it had no effect on the issue in the OP.)

In any case, `drawImage()` in the 2d context seems to work fine; so a possible workaround could be to render all images into a canvas element first (and that probably means loading images myself rather than using Pixi's loader or patching the ImageResource, right?).

What I'm trying to figure out, though, is what's causing the original issue so that we can fix it or report upstream. My best guess is that `texp[Sub]Image2D()` has an issue with the rotated image sources, so I'll try to set up a minimal test case using just the WebGL API.

**Comment by inukshuk** [comment]
Meanwhile, I've created a relatively minimal test for this using just the WebGL API: https://jsfiddle.net/ghxr4Lso/

I think the issue is clearly that loading an image into the GPU currently loads original image data regardless of the reported dimensions. Therefore, it's possible to draw the image correctly with WebGL but you'd have to be able to tell whether or not to flip the width/height properties. Since this is not the case when using `drawImage` nor when loading a `ImageBitmap` (in Chromium 84+, see the issue linked above) I think it's an inconsistency that should be addressed in Chromium and I'll report it there.

**Comment by bigtimebuddy** [comment]
Sounds good @inukshuk. Thanks for investigating hopefully this issue will be helpful for others. I'm going to close this since it's a browser bug.
