### ISSUE TITLE
"Object doesn't support this action" IE11

### ISSUE THREAD

**Issue by MitchEff** [pixijs/pixi.js#6720]
I've been fighting with getting Pixi to work with IE11 for some hours now, and keep encountering the same issue. I have zero idea what to do from this point. 

IE11 says "Object doesn't support this action" and highlights initPlugins' _for_ loop as the problematic part:
<img width="1467" alt="Screen Shot 2020-06-23 at 3 00 18 pm" src="https://user-images.githubusercontent.com/34614502/85362663-62f70600-b562-11ea-8dd6-aaa5a92aafa0.png">

Has anyone seen this before? I've been through hell and back to get it this far, but now I'm just completely stumped :/

**Comment by MitchEff** [comment]
The plot gets much thicker. 

- It was trying to initialise a plugin called 'accessibility'.
- In this 'for' loop, 't' was an an object called 'accessibility' and 'e' was a string called 'accessibility'
- t[e] was undefined as accessibility{} did not have a key called 'accessibility'
- I then tried to add an `if(t[e]){}` before doing the `new t[e]`, which now throws a different error: `t.enableTempParent is not a function`
- It does this in Edge too, but works in Chrome, FF and Safari
- I am losing my entire mind what on earth is going on

**Comment by MitchEff** [comment]
Okay, I've narrowed it down a bit. Any time it falls back to `pixi-legacy`, AccessibilityManager and InteractionManager are both missing:

warning  in ./node_modules/pixi.js-legacy/lib/pixi-legacy.es.js
27:47-67 "export 'AccessibilityManager' was not found in 'pixi.js'

warning  in ./node_modules/pixi.js-legacy/lib/pixi-legacy.es.js
30:45-63 "export 'InteractionManager' was not found in 'pixi.js'

I've tried doing the weird alias resolutions [here](https://github.com/inlet/react-pixi/issues/126#issuecomment-514184770) and [here](https://github.com/pixijs/pixi.js/issues/6155), but they haven't helped at all. 

I have no idea what to do from here. The docs say:
"// The application will create a renderer using WebGL, if possible,
// with a fallback to a canvas render. It will also setup the ticker
// and the root stage PIXI.Container."

...but it evidently doesn't. Using `pixi-legacy` results in aforementioned dependencies missing, and doing anything with aliases seems to have the same issue.

**Comment by MitchEff** [comment]
Correction: it does this in any situation it needs to use `canvas`. 

I've kind-of rectified the rest of the issues (by modifying the source of any Pixi plugins to use `pixi.js-legacy`), but `enableTempParent` not being a function is very much still an issue.

**Comment by bigtimebuddy** [comment]
Could you run the unminified version and see if that gives us more info?

**Comment by MitchEff** [comment]
This appears to be the culprit. When `CanvasRenderer` calls `render()` the passed-in `displayObject` doesn't seem to support `enableTempParent()` in IE11.

<img width="1165" alt="Screen Shot 2020-06-24 at 10 32 43 am" src="https://user-images.githubusercontent.com/34614502/85481893-15cc7000-b606-11ea-853f-b802b49f39d0.png">

This, in turn, is exclusively called by Pixi.Graphics' `generateCanvasTexture`: 
<img width="950" alt="Screen Shot 2020-06-24 at 10 36 19 am" src="https://user-images.githubusercontent.com/34614502/85482610-94c1a880-b606-11ea-997e-7029947401f6.png">

So I'd hazard a guess that, for some reason, Pixi.Graphics' other methods (e.g `getLocalBounds` etc) appear to work fine in IE, but when it gets to `enableTempParent` it has a fit of some sort. 

Here's the error, if it helps at all:
<img width="533" alt="Screen Shot 2020-06-24 at 10 39 42 am" src="https://user-images.githubusercontent.com/34614502/85482833-0ef22d00-b607-11ea-9ccd-b8f700ed7000.png">

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev can you look at this? Enable temp parent is your recent addition.

**Comment by bigtimebuddy** [comment]
@MitchEff Can you also create a standalone example (jsfiddle codepen etc) that reproduces the issue? It makes it easier for us to verify something is fixed.

**Comment by MitchEff** [comment]
Sure thing. I'll try find time this weekend.

**Comment by ivanpopelyshev** [comment]
Does it work without webpack?

**Comment by bigtimebuddy** [comment]
@MitchEff We are trying to make a v5.3.1 release, but we want to make sure this isn't something more serious. Can you please help us debug? A reproduction would be best. Thanks!

**Comment by cha0s** [comment]
Landed here from google, had the same problem:

`TypeError: displayObject.enableTempParent is not a function`

Unfortunately I don't have more details, yet.
