### ISSUE TITLE
Buggy thick lines rendering

### ISSUE THREAD

**Issue by broadsw0rd** [pixijs/pixi.js#6722]
### Expected Behavior

Proper thick lines rendering like in v5.2.4. [Example](https://codepen.io/broadsw0rd/pen/ExPmJmL)

### Current Behavior

Buggy thick lines rendering. [Example](https://codepen.io/broadsw0rd/pen/ExPmJjo)

### Environment

- **`pixi.js` version**: 5.3.0
- **Browser & Version**: Chrome 83
- **OS & Version**: Windows 10
- **Running Example**: https://codepen.io/broadsw0rd/pen/ExPmJjo

**Comment by bigtimebuddy** [comment]
Thanks for the examples. @SukantPal would you mind taking a look at this likely related to our 5.3.0 graphics changes.

**Comment by bigtimebuddy** [comment]
Merged fix.
