### ISSUE TITLE
TemporaryDisplayObject is not a constructor

### ISSUE THREAD

**Issue by hadimostafapour** [pixijs/pixi.js#6724]
Updating to from `5.2.4` to `5.3` cause this issue:

```
Uncaught TypeError: _pixi_display__WEBPACK_IMPORTED_MODULE_2__.TemporaryDisplayObject is not a constructor
    at new InteractionManager (interaction.es.js:946)
    at Renderer.initPlugins (core.es.js:11310)
    at new Renderer (core.es.js:11640)
    at Function.create (core.es.js:11691)
    at autoDetectRenderer (core.es.js:11926)
    at new Application (app.es.js:70)
    at new Game (game.js:29)
    at index.js:7
    at commitHookEffectListMount (react-dom.development.js:19765)
    at commitPassiveHookEffects (react-dom.development.js:19803)
```

Webpack:
```
WARNING in ./node_modules/@pixi/interaction/lib/interaction.es.js 946:39-61
"export 'TemporaryDisplayObject' was not found in '@pixi/display'
```

- **`pixi.js` version**: 5.3

**Comment by bigtimebuddy** [comment]
Can you make sure that all your @pixi/* packages are on 5.3.0, and not a mix of 5.2.4 and 5.3? Also, a repo would be helpful to reproduce. Thanks.

**Comment by hadimostafapour** [comment]
Thanks @bigtimebuddy, pixi-sound cause this issue.

**Comment by bigtimebuddy** [comment]
Was this pixi-sound having another dependency version installed?

**Comment by hadimostafapour** [comment]
@bigtimebuddy Maybe, I just removed pixi-sound and errors gone. I found as you mentioned there are two versions of pixi.js that the older version installed by pixi-sound. (In addition, I do not try to remove my package-lock.json before trying to remove pixi-sound, So I'm not sure that the reason for this issue is my package-lock file or pixi-sound)

**Comment by bigtimebuddy** [comment]
Yeah, I believe that pixi-sound should use peerDependencies instead of direct dependencies. Would eliminate this issue and makes more sense.
