### ISSUE TITLE
Masked Containers Performance

### ISSUE THREAD

**Issue by Ch1pStar** [pixijs/pixi.js#6727]
Greetings,
Masked sprites(or MovieClips from the [pixi-animate](https://github.com/pixijs/pixi-animate) library) are giving us huge performance drops on android phones. I've done some research into the issue recently and optimized all masks to be aligned rectangles so that we can use scissor masking which helped a bit, but the main issue on somewhat older phones seems to be that masks are breaking batching. I've done some experimenting by commenting all the masks and filter code from Container.renderAdvanced and it seems like the masking operations don't affect performance nearly as much as the ``` renderer.batch.flush();``` calls.

In the example below I've made 600 masked sprites with optimized masks and the fps drops to 35 on galaxy s8 phones. In our case the masked objects are a lot less(about 40) at a time, but they are animated MovieClips and there is the rest of the game being rendered aswell.

Looking for suggestions on how to optimize a lot of masked sprites. Would it help to write a custom batch renderer for the masked movie clips 🤔 

### Environment

- **`pixi.js` version**: _e.g. 5.2.4
- **Browser & Version**: _e.g. Chrome 83
- **OS & Version**: _e.g. Windows 10
- **Running Example**: https://codepen.io/ch1pstar/pen/eYJEpbJ

**Comment by bigtimebuddy** [comment]
Masks are, in general, very expensive (especially if you're talking in the 100's AND on mobile) and it's not surprising that you have bad performance. Is there any way you can restructure your project different to avoid using masks? If the masks are largely static, pre-rendering sprites or using RenderTextures can be helpful in some cases. Potentially using a filter or Texture to clip part of an image might give you some better results. I'd consider these things before mucking with a custom batch renderer. Can you give a better idea about what your scene looks like visually to think about ways it can be optimized?

**Comment by SukantPal** [comment]
Heya, I created `@pixi-essentials/mixin-smart-mask` so that inconsequential masking is entirely skipped. Check it out here:

https://github.com/SukantPal/pixi-essentials/tree/master/packages/mixin-smart-mask

**Comment by ivanpopelyshev** [comment]
If your masks are alpha-sprites, you can try a plugin: https://github.com/gameofbombs/pixi-heaven#how-to-mask-sprites-with-sprites . You have to switch for heaven sprites in that case.

If your DC count is still high (you know what is DC count, right?) , try to move all your sprites to masked renderer, even if there's no mask: `sprite.pluginName='batchMasked'`

**Comment by Ch1pStar** [comment]
Thank you everyone for the suggestions! I think we've solved the issue for now, by using render textures and rendering the masked MovieClip/Container only once per frame. I'll defo save the ideas for handling more dynamic masked content if the need arises in the future.
