### ISSUE TITLE
Flickering lines around border

### ISSUE THREAD

**Issue by JoshuaLopez** [pixijs/pixi.js#6730]
### Expected Behavior
canvas element displays without flickering/artefacts around edges.
### Current Behavior
Line appears intermittently around the edges of canvas element. Sometimes solid, sometimes flickering.Sometimes solid black, sometimes seems to be made up of colors from canvas.
Only appears on 1 or 2 sides at a time. Sometimes reaches entirely across the side, sometimes only affects part of a side.
### Possible Solution
Uncertain, but does not seem to occur without additional elements included on page.
### Steps to Reproduce
Open the following in a window and reload/resize a few times. (I did this by just pressing F5 and F12 a couple of times).

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Min Repro</title>
    </head>
    <body>
      <h2>a</h2>
      <div id="game-container"></div>
      <script type="text/javascript" src="https://pixijs.download/release/pixi.min.js"></script>
      <script type="text/javascript" src="https://pixijs.download/release/pixi.min.js.map"></script>
      <script type="text/javascript">
        let app = new PIXI.Application({
          backgroundColor: 0xcccccc,
          height: 640,
          width: 640
        });
        document.querySelector('#game-container').appendChild(app.view);
      </script>
    </body>
    </html>

### Environment

- **`pixi.js` version**: First noticed in v5.1.5. Since confirmed happening in v5.3.0 (currently latest version).
- **Browser & Version**: Firefox 77.0.1
- **OS & Version**: Ubuntu 18.04.4
- **Running Example**: See above

**Comment by bigtimebuddy** [comment]
Can you please provide a visual (gif, mp4, etc) for what you're seeing?

**Comment by JoshuaLopez** [comment]
This is the black line that I've been seeing. It actually flickers a bit faster than what's in the gif. The recording probably didn't pick up every frame, but you can still see what's happening.
![flickerline](https://user-images.githubusercontent.com/7264339/86080230-6d346b00-ba60-11ea-9473-5b54e939689d.gif)

Another tab that I had left open for several hours is now flickering content from whichever tabs I most recently had open. What you're seeing in this gif is an _empty app_. The source is the same as is posted above, but you can see where I was looking at a PIXI forum and had this GitHub page open too.
![othertabs](https://user-images.githubusercontent.com/7264339/86080945-1b8ce000-ba62-11ea-9828-17387f15ab50.gif)

**Comment by bigtimebuddy** [comment]
Curious.

Is this happening in Firefox only? Have you seen this when looking at any other WebGL content (not Pixi). Are your video drivers up to date?

**Comment by JoshuaLopez** [comment]
Seems to only occur in Firefox. I haven't observed the issue in any other WebGL content. Video drivers were out of date, but I updated and am still seeing the issue.
