### ISSUE TITLE
Problem with dragonbones plugin and cacheAsBItmap 

### ISSUE THREAD

**Issue by jiroler** [pixijs/pixi.js#6733]
In version 5.3.0 cacheAsBItmap is not working for dragonbones containers

Just add line `armatureDisplay.cacheAsBitmap = true` after line with `app.start()` in examples:

https://pixijs.io/examples/?v=v5.3.0#/plugin-dragonbones/robot.js - not working
https://pixijs.io/examples/?v=v5.2.4#/plugin-dragonbones/robot.js - working

**Comment by bigtimebuddy** [comment]
Appears to be a regression, thanks for pointing this out. I added a bounty for someone to dig into this deeper.
