### ISSUE TITLE
why it's not cantain in stage size?

### ISSUE THREAD

**Issue by hammadtariq98** [pixijs/pixi.js#6736]
![screencapture-localhost-3000-2020-07-02-10_34_19](https://user-images.githubusercontent.com/44154966/86320144-a1ba4980-bc4f-11ea-8ef4-425c1856802f.png)

**Comment by UltraCakeBakery** [comment]
If your container is positioned at ```x0``` and ```y0```, and your shape is larger than your canvas, it will be cut off like in your picture. 

You need to change the scale of your container to zoom-out or limit the size of your cube. 

Your canvas shapes DO NOT interact with HTML elements. They only exist inside the canvas element. You should look at it as if you had ```overflow: hidden``` enabled on a HTML element with bigger child elements inside.

**Comment by UltraCakeBakery** [comment]
Also, it is good github etiquette to use shorter titles. Describe the problem in the issue description itself. Also use the default template when one is provided. Now we have to guess what can be wrong because you didn't give us more details.

**Comment by hammadtariq98** [comment]
Thank you for your suggestion here it is an image with some label  
![screencapture-chrome-extension-fdpohaocaechififmbbbbbknoalclacl-editor-html-2020-07-02-15_57_04](https://user-images.githubusercontent.com/44154966/86351092-21124200-bc7d-11ea-824e-68f1e71327ce.png)
I want that whatever user input the height  the shape max-height must not  cross the height of the stage

**Comment by UltraCakeBakery** [comment]
A stage is a ```[PIXI.Container](https://pixijs.download/dev/docs/PIXI.Container.html)```. A container is just a collection of DisplayObjects (PIXI.Graphics, PIXI.Sprite and more).

You should check if the number in the input is > than the height of the HTML Canvas element.
