### ISSUE TITLE
Google Closure Compiler advanced mode not working due to undefined variable

### ISSUE THREAD

**Issue by nielsdos** [pixijs/pixi.js#6738]
### Expected Behavior

I want to compile my project with Google Closure Compiler under advanced mode.
It's a Webpack project with Google Closure Compiler as minimizer.

### Current Behavior

When trying to compile I get an error from code within pixi.js;
```
ERROR in main.js:11157 from closure-compiler: variable event is undeclared
        this.onError.emit(event);
                          ^^^^^
```
Minimal reproducing code:
```js
import { Application } from '@pixi/app';
import { Renderer } from '@pixi/core';
```

Repo for this: https://github.com/nielsdos/pixi-repro

### Possible Solution

The issue seems to be https://github.com/pixijs/pixi.js/blob/master/packages/core/src/textures/resources/VideoResource.ts#L229
The variable event doesn't seem to be defined.

### Steps to Reproduce

Compile a pixi.js project with closure compiler in advanced mode.

### Environment

- **`pixi.js` version**: 5.3.0

**Comment by bigtimebuddy** [comment]
Can you create a project that reproduce this? Your steps to reproduce assume we know how to invoke that compiler.

**Comment by nielsdos** [comment]
Thanks for your reply.
I've created a repo for this: https://github.com/nielsdos/pixi-repro
Run `npm install` and `npm run build`.
