### ISSUE TITLE
Different scaling behaviour with Sprite from file and Canvas

### ISSUE THREAD

**Issue by semih-akbas** [pixijs/pixi.js#6740]
Hello,

I came accross to a strange problem. I have a PIXI stage where the users are able to add 2 types of sprites: Sprite from Image file (CanvasObjectImage) and Sprite from HTML Canvas element(CanvasObjectChart). Both objects are extended from a common CanvasObjectBase that extends PIXI.Graphics class.

The problem is that although I provide same width and height for the both Sprite objects, they are shown different in size as can be seen on the image below. (W:100, H:100). Sprite with a green border and vue image is CanvasObjectImage and the chart figure is a CanvasObjectChart instance. 

![stage](https://user-images.githubusercontent.com/16348435/86462496-5e85d680-bd34-11ea-958b-9cb07926c1d4.png)

I've attached my class files as txt:
[CanvasObjectChart.txt](https://github.com/pixijs/pixi.js/files/4869296/CanvasObjectChart.txt)
[CanvasObjectImage.txt](https://github.com/pixijs/pixi.js/files/4869297/CanvasObjectImage.txt)
[CanvasObjectBase.txt](https://github.com/pixijs/pixi.js/files/4869298/CanvasObjectBase.txt)

Here is how I add these Sprites using PIXI

```
EventBus.$on(
      "animation_plan:add_buttons:clicked",
      function(type, newScene) {
        try {
          this.$attrs.project.scenes.push(newScene);
          switch (type) {
            case "imageAnimationPlan":
              {
                var imgScene = new CanvasObjectImage(
                  newScene,
                  this.selectionChanged
                );
                this.PIXIWrapper.PIXIApp.stage.addChild(imgScene);
                console.log("Image Scene: scX: " + imgScene.scale.x + ", scY: " +  imgScene.scale.y);

              }
              break;
            case "lineChartAnimationPlan":
              {
                var lineChartScene = new CanvasObjectChart(
                  this.$refs.cnvChart,
                  newScene,
                  this.selectionChanged
                );
                console.log("Pixel ratio: " + window.devicePixelRatio);
                //lineChartScene.scale.x = 0.5;
                //lineChartScene.scale.y = 0.5;
                this.PIXIWrapper.PIXIApp.stage.addChild(lineChartScene);
                console.log("Chart Scene: scX: " + lineChartScene.scale.x + ", scY: " +  lineChartScene.scale.y);
              }
              break;
          }
        } catch (ex) {
          console.log("HATA: " + ex);
          throw ex;
        }
      }.bind(this)
    );

```
There seems to be a different scaling handling between different sprite types. If I uncomment the "lineChartScene.scale.x" lines above I can arrange the size properly but how should I determine the correct scale ratio then?

Any help is appreciated.
Thanks
Semih

- **`pixi.js` version**: 5.3.2
- **Browser & Version**: Version 83.0.4103.116 (Official Build) (32-bit)
- **OS & Version**: MacOS & Win10

**Comment by ivanpopelyshev** [comment]
Is image preloaded? If not, then any changes to sprite `width` and `height` prematuraly may lead to strange scale behaviours. Yes, we fixed that many times but its still comes back.

Remember , that when you change object "width" or "height" - it actually changes scale depending on calculated width/height of **object and its children**.
