### ISSUE TITLE
With 120hz monitor, FPS is dropping to 60hz for one frame and returning back to 120hz frequently.

### ISSUE THREAD

**Issue by sefabaser** [pixijs/pixi.js#6741]
### Expected Behavior
With a 120hz screen, FPS should be able to go down and up smoothly in need of FPS change due to performance.

### Current Behavior
PIXI.Ticker.FPS jumping between ~120hz and ~60hz with a 120hz g-sync monitor.
When there is almost nothing on screen it works flawlessly on 120hz but if there is a need for dropping the FPS it directly jumps down to 60hz for one frame and returns back to 120hz.

### Steps to Reproduce
Use 120hz g-sync monitor
Set up a game enough to require some FPS drop from 120hz
FPS frequently will drop 60hz for one frame and return back to 120hz, which cause studdering

### Environment
Environment
pixi.js version: v5.3.0
Browser & Version: Chrome 85.0.4173.2
OS & Version: Windows 10
Screen: Predator Z35P

**Comment by bigtimebuddy** [comment]
Ticker _can_ adjust for bouncy frame rates by using the time scalar value passed to `ticker.add`. Developers that are adding tweens or other time-constrained rendering should make sure they multiply their per-frame changes by this value.  Can you please provide a specific reproduction case where you see this so we can verify if that's that case? A standalone example is best.

Basically, the thing we need to understand is if this is a Ticker bug, a browser issue, OS or hardware/driver. Not always much we can do about environment issues, but there are a couple of things to isolate if this is a Ticker issue, but we need someone with this monitor that can verify. @sefabaser if you could help us debug further what's happening that would be great.

**Comment by themoonrat** [comment]
I wonder if Chrome just isn't setup properly for gsync, because what you're describing is what would happen on a classic monitor with vsync, where if 60fps can't be hit, it'll vsync down to 30. And if that can't be hit, it'll vsync down to 20.
Obvs you're starting at 120, but that's the kind of profile you're seeing. I don't see this as a PixiJS thing, as we're just using requestAnimationFrame. The question is why is the browser enforcing vsync for that, rather than being dynamic like gsync and freesync allow.

**Comment by sefabaser** [comment]
Thank you so much for such a quick response in Saturday evening.

I am multiplying per-frame changes with App.ticker.deltaMS. Game speed-wise I do not have any problem but I see studdering.

When I run the code below in the link I am getting the FPS numbers as below. Depending on the computer setup number of bunnies might be different to get the same result. When FPS needs to drop under 60hz I do not see jumping behavior at FPS.

I do not know if it might help or not but also when I lock App.ticker.maxFPS to something above 60hz it is not taking effect. 

Sample: https://pixijs.io/examples/#/demos-basic/container.js
```
const app = new PIXI.Application({
    width: 800, height: 600, backgroundColor: 0x1099bb, resolution: window.devicePixelRatio || 1,
});
document.body.appendChild(app.view);

const container = new PIXI.Container();

app.stage.addChild(container);

const texture = PIXI.Texture.from('examples/assets/bunny.png');

for (let i = 0; i < 40000; i++) {
    const bunny = new PIXI.Sprite(texture);
    bunny.anchor.set(0.5);
    bunny.x = (i % 5) * 40;
    bunny.y = Math.floor(i / 5) * 40;
    container.addChild(bunny);
}

container.x = app.screen.width / 2;
container.y = app.screen.height / 2;

container.pivot.x = container.width / 2;
container.pivot.y = container.height / 2;

app.ticker.maxFPS = 120;
app.ticker.add((delta) => {
    console.log(app.ticker.FPS);
    container.rotation -= 0.04 * delta;
});

```

Console output:
``` 
(index):28 59.9412575675838
(index):28 120.00480019200647
(index):28 59.90893841361128
(index):28 119.50286806883453
(index):28 60.00240009600406
(index):28 119.46004061641246
```

**Comment by ivanpopelyshev** [comment]
Last time we did with this kind of investigation: https://github.com/pixijs/pixi.js/pull/5934
