### ISSUE TITLE
Issue using a Graphics as a mask when loaded from a texture

### ISSUE THREAD

**Issue by sam42contact** [pixijs/pixi.js#6743]
Hello,

Check this codepen: https://codepen.io/sam42contact/pen/yLevOWg

Basically, using a PIXI.Graphics as a mask doesn't work if its content is through a texture.

Using a sprite as a mask doesn't display the issue.
--> Expected results (done using a sprite): https://codepen.io/sam42contact/pen/RwrQRbm

Any leads on this?

**Comment by bigtimebuddy** [comment]
Graphics, when used as a mask, use the shape not the texture or fill. If you want a texture mask, use a Sprite?

**Comment by sam42contact** [comment]
Oh, I see!

My issue is that I have a few operations to do to generate the final image I want to display.
Something like this: take image1, apply a mask, draw image2, draw a portion of image3, etc.

I can indeed use sprites for masks, but I cannot figure out how to "draw portion of a texture" inside a sprite, without generating another texture. While using graphics, I can pass a transformation matrix to beginTextureFill (so that I can specify exactly what to draw).

Thanks for the quick answer btw :)

**Comment by bigtimebuddy** [comment]
What's wrong with generating another Texture? A Texture is exactly what you're describing, a region on image or resource.

The other option is you can create a new canvas and use `drawImage` to define the region to render.

**Comment by sam42contact** [comment]
Creating new textures would complicate memory management as I would have to keep track and destroy them.

Anyways, I think I got my answers regarding masking and the way to go using textures.

Sorry for my lack of knowledge (I started using pixi yesterday). I really appreciate your patience educating me on this <3

**Comment by bigtimebuddy** [comment]
No worries! Welcome to PixiJS! 

You might consider joining Pixi’s Slack, sometimes a little easier for casual questions than filing an issue. Also html5gamedevs.com has an active community for getting help on project specific things.

**Comment by sam42contact** [comment]
Ok, got it.

The issue I had, seemed to me like a bug at first glance, that's why I submitted the issue.
But you are absolutely right. It is not the right place for such.

I will ensure to use the specified resources in the future.

Thanks again.
