### ISSUE TITLE
Fixed width text renders in wrong size for one frame whenever the text is changed

### ISSUE THREAD

**Issue by CyberPhoenix90** [pixijs/pixi.js#6744]
### Expected Behavior
Text renders at the correct size from the start
### Current Behavior
Text renders in wrong size for 1 frame then fixes itself
### Steps to Reproduce
1. Create a PIXI.Text object 
2. Give it a fixed width
3. Change the text length
### Environment

- **`pixi.js` version**: 5.3.0
- **Browser & Version**: Tested and reproduced in: Chrome 83, Firefox 77, Firefox 78, Edge 16
- **OS & Version**: Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/Om7cxgWh-gYovRXIPy_Ml

**Comment by bigtimebuddy** [comment]
Not sure what's going on here, but seems like a bug.

Calling `updateText()` immediately after setting the text fixes the problem. I created another example (below) to demonstrate the problem more clearly. The "flash" frame is actually just appending the text and the transform isn't applied until the next frame.

https://jsfiddle.net/bigtimebuddy/9fzxq4eo/

@themoonrat does this seem like a bug to you?

**Comment by themoonrat** [comment]
@bigtimebuddy It's a bug from us
Tracked down to something between 
4.5.4 https://jsfiddle.net/5ydsuqe1/2/
4.5.5 https://jsfiddle.net/5ydsuqe1/3/

4.5.4 is fine, 4.5.5 isn't.

I can't see immediately glancing at the diff what could cause this - https://github.com/pixijs/pixi.js/compare/v4.5.4...v4.5.5

**Comment by bigtimebuddy** [comment]
Nothing seems obvious with that diff so probably something subtle. I added a bounty.
