### ISSUE TITLE
Separated letters of Bitmap text

### ISSUE THREAD

**Issue by jiroler** [pixijs/pixi.js#6745]
Hello! Can I animate separate letters of new version of BimapText (as mesh)?

Simple example in version 5.2.4:
https://jsfiddle.net/jiroler/01x45spd/1/

**Comment by bigtimebuddy** [comment]
This is less convenient, but works: https://jsfiddle.net/bigtimebuddy/uL2o6pb1/

I think we should make these types of operations a little easier. Moving to mesh is faster, but clumsy to do manipulate letters individually. Would welcome a PR to provide some convenience to offset letters individually (maybe even potentially tint/opacity).
