### ISSUE TITLE
uniform sampler2D uSampler  Customize?

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixi.js#6749]
how to  Customize uniform sampler2D uSampler  i want to use two pictures

**Comment by bigtimebuddy** [comment]
Hello! If you need general help, please consider posting to [html5gamedevs.com](https://www.html5gamedevs.com/forum/15-pixijs/) or joining the PixiJS Slack channel.

**Comment by ivanpopelyshev** [comment]
add one more uniform. 
Depends on whether you use mesh-shader combo or a filter, you have to specify a texture for that uniform.

**Comment by ivanpopelyshev** [comment]
Filters are here: https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters

mesh-shader - should be obvious that you can pass extra uniform.
