### ISSUE TITLE
Blur Filter problem on latest dev version.

### ISSUE THREAD

**Issue by owendwyer** [pixijs/pixi.js#6752]
The slots example isn't working with the latest development version.

https://pixijs.io/examples/?v=dev#/demos-advanced/slots.js

v5.3.0 works fine.

Seems to be a problem with the blur being applied to the reel.

**Comment by bigtimebuddy** [comment]
@SukantPal This is probably related to #6683. That build produces the error and is the earliest thing after 5.3.0.
https://pixijs.io/examples/?v=fix/projection-system#/demos-advanced/slots.js

Would you mind debugging this?
