### ISSUE TITLE
PIXI.BitmapFont.install bug

### ISSUE THREAD

**Issue by rodighiero** [pixijs/pixi.js#6766]
I have a problem with bitmap fonts. I can load them, but I have no control on color and size.

```
const arialPNG = PIXI.Texture.from(arialDataPNG)
const arial = PIXI.BitmapFont.install(arialXML, arialPNG)

PIXI.BitmapFont.from("TitleFont", {
    fontFamily: "Arial",
    fontSize: 12,
    strokeThickness: 2,
    fill: "purple"
});

const title = new PIXI.BitmapText("This is the title", { fontName: "TitleFont" });

```

**Comment by bigtimebuddy** [comment]
Huh? This is confusing. Are you using externally loaded fonts (first two lines) OR generating your own with BitmapFont.from?

**Comment by rodighiero** [comment]
I had a working version of _bitmapfont_ that is not working anymore with release 5.3.0, saying that _registerFont_ is deprecated. The idea was to use the _bitmapfont_, which with the update makes a glitch showing the entire PNG.

The working code for 5.2.4 was:

```
   const nodeStyle = new PIXI.TextStyle({
        font: '4px Arial',
        fill: color.on,
        align: 'center',
    })

    const arialPNG = PIXI.Texture.from(arialDataPNG)
    const arial = PIXI.BitmapText.registerFont(arialXML, arialPNG)

    text = new PIXI.BitmapText(`${nA}\n${nB}`, nodeStyle)

```

**Comment by bigtimebuddy** [comment]
Can you please provide a working example that reproduces the issue? Thanks.

**Comment by rodighiero** [comment]
Sure, you can fork the project from https://github.com/rodighiero/DH2020
Then type `npm install` and `npm run start`

In _src/index.js_ font is loaded at lines 64 and 65

```
const arialPNG = PIXI.Texture.from(arialDataPNG)
const arial = PIXI.BitmapText.registerFont(arialXML, arialPNG)
```

In _src/elements/keywords.js_ the style is declared between lines 6 and 10:
```
const tokenStyle = new PIXI.TextStyle({
    font: '24px Arial',
    align: 'center',
})
const color = 0xCCCCCC
```

While the bitmap is created at line 37:
```
link.txt = new PIXI.BitmapText(key, tokenStyle)
```

This is currently working. If I substitute it with the first block of code I posted, it stops working.

Thanks for helping.

**Comment by bigtimebuddy** [comment]
This worked for me: https://jsfiddle.net/bigtimebuddy/mu3fanqh/2/

Also, `BitmapText` never accepted PIXI.TextStyle as the second constructor argument the fact that it worked before is a coincidence. Documentation is here: [5.3.0](https://pixijs.download/v5.3.0/docs/PIXI.BitmapText.html), [5.2.4](https://pixijs.download/v5.2.4/docs/PIXI.BitmapText.html).

**Comment by rodighiero** [comment]
Thanks a lot, this is a very simple and good example that clarified my problem. I also had to load XML and PNG differently:

```
    const arialPNG = PIXI.Texture.from(arialDataPNG)
    const arial = PIXI.BitmapFont.install(arialXML, arialPNG)
```

I've still a question rather frugal: I wrote _align: 'center'_ in the font definition and it doesn't work. But I've found that _text.align = 'center'_ works perfectly with the object _BitmapText_. Is that normal?

Thank you!

**Comment by bigtimebuddy** [comment]
I don't know what you mean, please show an example.

In general, align can be confusing because it only applies to multi-line text, for instance:
https://jsfiddle.net/bigtimebuddy/08naherL/

**Comment by rodighiero** [comment]
It works perfectly for me, thanks a lot.

Just a minor question, is it normal that I cannot set the alignment in the "style"? Like in this example: https://jsfiddle.net/a3yjuh5w/1/#&togetherjs=mDOfUwtj46

**Comment by bigtimebuddy** [comment]
Yes, that's to be expected. Not all TextStyle options are respected when generating a BitmapFont. Since `align` is a layout option not really about rendering the font, it's ignored here. Use the BitmapText `align` instead.

**Comment by rodighiero** [comment]
Thanks for helping me, the data visualization looks perfect now!
