### ISSUE TITLE
stopPropagation is not working

### ISSUE THREAD

**Issue by xavicolomer** [pixijs/pixi.js#6767]
### Expected Behavior

I have a sprite (parent) inside another sprite (child)

Both the child and the parent can listen to mousedown and mouseup events, but want the child to stop the propagation. This is not happening.

I added some extra attribute in the mousedown event, to check if ti was the same event.

event.test = "aaaa"

the parent received this information.

### Current Behavior

The stopPropagation does not have any effect.

### Possible Solution

No idea. ☹️

### Environment

- **`pixi.js` version**: _e.g. 5.2
- **Browser & Version**: Chrome
- **OS & Version**:  Mac
- **Running Example**: _url_

Any idea?

**Comment by themoonrat** [comment]
Could you create an example please demonstrating this on https://www.pixiplayground.com
Thank you!

**Comment by ivanpopelyshev** [comment]
or jsfiddle, or codesandbox. or zip file.

**Comment by laino** [comment]
Relevant test case: https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/test/InteractionManager.js#L190
