### ISSUE TITLE
Can't able to get ImageData from canvas

### ISSUE THREAD

**Issue by iamappmaker** [pixijs/pixi.js#6772]
I am can't able to get ImageData from canvas. I tried all possible solutions found in internet but still i can't to get it.

**Comment by ivanpopelyshev** [comment]
Look how `renderer.extract` does it. Basically, `readPixels`. You have to use extract, or look inside, understand it, and make your own version.

from main framebuffer `readPixels` works **only after render** cant just take it at random time. For renderTexture - you can take at any time, but dont forget to destroy that texture when you dont need it or re-use it
