### ISSUE TITLE
5.3.1 build with JSDoc error ^ Node 12

### ISSUE THREAD

**Issue by crazykay** [pixijs/pixi.js#6775]
## JSDoc 3.5.5 Breaking Builds on Node 12
https://github.com/pixijs/pixi.js/issues/6571

### Possible Solution
upgrade
`"jsdoc": "^3.5.5"`
to
`"jsdoc": "^3.6.4",`

### Environment

- **`pixi.js` version**: 5.3.1
- **Browser & Version**: none
- **OS & Version**: Archlinux
- **Running Example**:  none

**Comment by bigtimebuddy** [comment]
This is a duplicate. We already have a plan to fix for 3.4.0, by moving away from JSDoc entirely. Closing.
