### ISSUE TITLE
Atlas does not load with v5.3.1

### ISSUE THREAD

**Issue by sergeysinyavsky** [pixijs/pixi.js#6779]
### Expected Behavior
Atlas loaded.

### Current Behavior
The error appears with v5.3.1.

The build works fine with v5.3.0.
### Possible Solution

Unknown.

### Steps to Reproduce
An error occurs when loading the atlas. Atlas created using Texture Packer.

`Loader.shared.add('interface', 'assets/atlases/interface.json');`

Error:

```
spritesheet.es.js:58 Uncaught TypeError: Cannot read property 'baseTexture' of null
    at new Spritesheet (spritesheet.es.js:58)
    at onImageLoad (spritesheet.es.js:313)
    at MiniSignal.dispatch (mini-signals.js:93)
    at resource-loader.esm.js:2256
    at next (resource-loader.esm.js:47)
    at Loader../node_modules/@pixi/spritesheet/lib/spritesheet.es.js.SpritesheetLoader.use (spritesheet.es.js:298)
    at resource-loader.esm.js:2254
    at resource-loader.esm.js:55
```

### Environment

- **`pixi.js` version**: 5.3.1
- **Browser & Version**: Chrome 84.0.4147.89
- **OS & Version**: Windows 10

**Comment by bigtimebuddy** [comment]
Reinstall you node modules. You likely have duplicate versions of core after upgrading. This has been covered in previous issues.

**Comment by sergeysinyavsky** [comment]
I completely deleted the node modules folder and reinstalled. It did not help.
I use "pixi-filters": "^3.1.1". Can this somehow affect?

**Comment by bigtimebuddy** [comment]
Yes, please remove your package-lock.json or yarn.lock and try installing again.

**Comment by sergeysinyavsky** [comment]
Thank you! It really helped.
