### ISSUE TITLE
Extracting image not working with filters applied.

### ISSUE THREAD

**Issue by adamlaurencik** [pixijs/pixi.js#6780]
I am trying to extract images with filters applied and I always get an empty image as a result.
I tried different approaches, extracting the sprite, generating texture of the sprite and extracting it, putting it into some vanilla container and extracting, and also extracting the whole stage, but always the same result.  Everything works fine without the filter applied.
Below is the code that I am trying and also a link to a running example.

```
/**
* This is the default playground.
* You should see a bunny spinning in the right preview pane.
* Feel free to use this as a starting point for you own playground!
*/
// Create our application instance
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

// Load the bunny texture
app.loader.add('bunny', 'https://pixijs.io/examples/examples/assets/bunny.png')
    .load(startup);

function startup()
{
    var bunny = new PIXI.Sprite(app.loader.resources.bunny.texture);

    // Center the sprite's anchor point
    bunny.anchor.set(0.5);
    bunny.filters=[new PIXI.filters.BlurFilter()]

    // Move the sprite to the center of the screen
    bunny.x = app.renderer.width / 2;
    bunny.y = app.renderer.height / 2;

    const photoContainer = new PIXI.Container();

    photoContainer.addChild(bunny);

    app.stage.addChild(photoContainer)


    const texture = app.renderer.generateTexture(photoContainer, photoContainer.getBounds())

    console.log(app.renderer.extract.base64(texture));

    console.log(app.renderer.extract.base64(photoContainer));

    console.log(app.renderer.extract.base64(bunny));
    
    console.log(app.renderer.extract.base64(app.stage))
}
```

- **`pixi.js` version**: 5.3.1
- **Browser & Version**: Chrome 81
- **OS & Version**: _e.g. Ubuntu 18.04.3 LTS
- **Running Example**: https://www.pixiplayground.com/#/edit/T1LV99X7IEw93OKv7PEq6

**Comment by ivanpopelyshev** [comment]
Did we break `extract` and `generateTexture` again? I'll test it in weekend maybe

**Comment by ivanpopelyshev** [comment]
Usual workaround: add it to container, manually use getBounds(), render into your own temporary RenderTexture with proper transform - basically, thats evading most of the IF's in `extract` and `generateTexture` and makes your app stable.
