### ISSUE TITLE
line number:4923, calculateProjection(destinationFrame?: PIXI.Rectangle, sourceFrame: PIXI.Rectangle, resolution: number, root: boolean): void;

### ISSUE THREAD

**Issue by ajaybabum** [pixijs/pixi.js#6781]
### Expected Behavior
In this method, we pass parameters, with mandatory and optional
### Current Behavior
But in this method, passed optional first and then mandatory 
### Possible Solution
remove optional parameter for destinationFrame
calculateProjection(destinationFrame: PIXI.Rectangle, sourceFrame: PIXI.Rectangle, resolution: number, root: boolean): void;
### Environment

- **`pixi.js` version**: _e.g. ^5.3.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by MercurialUroboros** [comment]
It actually does not even compile to me. Can anyone suggest a fix for it?
![image](https://user-images.githubusercontent.com/22802482/88516583-ce167b00-cfed-11ea-8572-b7b72e009ff4.png)

**Comment by ajaybabum** [comment]
For quick fix, Goto pixi.js.d.ts:4925 line , and replace destinationFrame? with destinationFrame

calculateProjection(destinationFrame: PIXI.Rectangle, sourceFrame: PIXI.Rectangle, resolution: number, root: boolean): void;

NOTE: it's a Quick fix only to run dev project

**Comment by MercurialUroboros** [comment]
Unfortunately, it's not a "solid" quick fix, since I will have to force my teammates to do the same. 

Thanks anyway, I think I will just revert typescript version since this issue appears to be there even with 5.2.1.

**Comment by ajaybabum** [comment]
@MercurialUroboros yes it's not a solid quick fix, or else you can download the total library and make sure this is to available for all your teammates

**Comment by naranjamecanica** [comment]
This is reported in in https://github.com/pixijs/pixi.js/issues/6774

**Comment by bigtimebuddy** [comment]
Duplicate so closing. We have a fix already waiting for approval. Sorry for the inconvenience will have a patch out soon.
