### ISSUE TITLE
Multiple BitmapFonts with same tint render incorrectly in CanvasRenderer

### ISSUE THREAD

**Issue by andrew-luminal** [pixijs/pixi.js#6782]
This is a bit of a strange bug, and I'm assuming it might be related to the fix put in for my last bug in #6764 . It again only occurs in the CanvasRenderer, and only with PIXI v5.3.1. Basically, if you are using two or more `BitmapFont`s in `BitmapText`s with the same value for their `tint` property, the `BitmapText` objects using any font except the first `BitmapFont` will show up scrambled. It seems like they might be using the character information from the first `BitmapFont` or something? This does not occur if `tint` is not used.

![image](https://user-images.githubusercontent.com/13007059/88573651-0b3f3500-d00f-11ea-81d8-4b33e05e0510.png)

### Expected Behavior

All tinted `BitmapText` objects render properly, regardless of which `BitmapFont` they use.

### Current Behavior

Only tinted `BitmapText` objects using the first initialized `BitmapFont` render properly, if they are using the same `tint`.

### Possible Solution

I imagine it's related to the caching logic in here: https://github.com/pixijs/pixi.js/pull/6764/files#diff-5332f871658531ea1f88558c83f52c4cR129

My instinct would be just to get rid of this conditional and always generate a new `_tintedCanvas` but I have a pretty naive understanding of this code at present, and I imagine there's a performance hit to just not using a caching mechanism at all here.

### Steps to Reproduce

1. Use Canvas Renderer
2. Create two or more different `BitmapFont`s
3. Create two or more `BitmapText`s using the **same** `tint` but different `BitmapFont`s

### Environment

- **`pixi.js` version**: 5.3.1
- **Browser & Version**: current Chrome, Safari, and Firefox
- **OS & Version**: Mac OS 10.14.6
- **Running Example**: https://codepen.io/andrew-luminal/pen/WNrBNzv

**Comment by bigtimebuddy** [comment]
@JetLua would you mind taking a look at this?

**Comment by JetLua** [comment]
No problem. I'll keep an eye on it.
