### ISSUE TITLE
Randomly dropping ~5 frames

### ISSUE THREAD

**Issue by Ekuju** [pixijs/pixi.js#6785]
I'm wondering if this could be related to
https://github.com/pixijs/pixi.js/issues/6741
and
https://github.com/pixijs/pixi.js/pull/5934

I noticed my game randomly completely skipping between 2-7 frames (frozen screen), then playing 2-3 normal frames as if the skip never happened, then going forward in time to catch up (sudden jump).

I added some logging and played this back frame by frame. I noticed what was happening was, my game was submitting every single frame, but during the duration in which the frames were skipped they didn't make it into the browser window.

My monitor runs at 144 hz, so if it's dropping down to 30 fps for some gsync reason as described in one of those issues it _could_ explain it.

I don't think I have an issue in firefox.

Any guidance on how to fix this? Am I using requestAnimationFrame incorrectly?

**Comment by ivanpopelyshev** [comment]
switch off frame sync in Ticker at all. Did you look at Ticker souce? If no, look there and make sure none of IF's that can drop frame are executed.

**Comment by ivanpopelyshev** [comment]
Then make sure that Pixi GC is not removing and re-uploading textures because of some stupid error

**Comment by Ekuju** [comment]
thanks for the response

> switch off frame sync in Ticker at all. Did you look at Ticker souce? If no, look there and make sure none of IF's that can drop frame are executed.
I'm manually calling render on the application at the end of my animationFrame. and the application starts with `autoStart: false`. I think this would make all potential weird Ticker issues irrelevant, correct?

any advice on how to check what the pixi GC is doing? after you suggested that I set `PIXI.settings.GC_MODE = PIXI.GC_MODES.MANUAL;` and am still observing the issue.

**Comment by CosmoMyzrailGorynych** [comment]
@Ekuju what **browser** are you using? I'm asking this as I experienced noticeable frame drops in nw.js, and it was a flaw of nw.js v0.46.

Additionally, use the built into your browser Profiler to narrow the search of the issue. Profilers show frame drops due to garbage collection, user events and such, as well as display which functions consume abnormal amount of compute time.

**Comment by Ekuju** [comment]
> Profilers show frame drops due to garbage collection, user events and such, as well as display which functions consume abnormal amount of compute time.

is this true? I did try using the profiler to see if theres any "memory leaks" or something going on, but I wasn't aware it directly showed frame drops due to certain events. that'd be extremely helpful, do you have some basic instructions for that?

I was using chrome 84.0.4147.89. I also see frame drops when using electron, though I havent tried nw.js.

**Comment by CosmoMyzrailGorynych** [comment]
You know, there is google.com and other marvelous search engines.

Anyways,

![2020-08-04_09-50](https://user-images.githubusercontent.com/3174357/89230730-ff1f2d00-d637-11ea-9ec4-10fa6255ce25.png)

I don't have a screenshot of stopping garbage collection warnings — I have minor GC only as tiny yellow blocks —, but it is shown as well and as far as I can remember, it was a red block in thread analyzer ("Main — localhost:xxxx" for me).

**Comment by Ekuju** [comment]
> You know, there is google.com and other marvelous search engines.

Feel free to not help if you're not interested. You're not obligated to do so. I was asking because you brought it up - carrying on a conversation. I do appreciate the help though.

I know of the profiler, but this doesn't exactly show display synced frame skips. Unless I'm misunderstanding, in my scenario every frame has plenty of unused time, so the garbage collection isn't hogging so much cpu it would delay a frame. (In fact actually I don't see garbage collection doing anything in the problem frames.) So far it actually seems like chrome just isn't respecting the next frame, but I'm not completely sure. Maybe chrome is doing something weird causing it to not use it's available CPU time.

**Comment by CosmoMyzrailGorynych** [comment]
@ivanpopelyshev  Helping requires contribution from both sides — otherwise, you are wasting other's time. Your original question ignored an issue template, brought 0 helpful info except for _symptoms_, showing no research — a question like this on StackOverflow or such would be downvoted heavily. I added my input as I felt that you are moving the maintainer away from the real problem, and thus requested more info.

> I was asking because you brought it up - carrying on a conversation.

You took away my time because you did not look it up in google or such — dismissed a trivial task. This is unwelcomed.

> In fact actually I don't see garbage collection doing anything in the problem frames

Then your issue is not about memory management. Continue putting effort into solving your issue and you will get proper help.

**Comment by Ekuju** [comment]
I won't argue further with you through github. I stand by there being no need to be passive aggressive towards others over a support issue, but that's for sure a popular thing in this profession. I'll close out this ticket as it seems like it's reached the end of its life anyways.
