### ISSUE TITLE
No "On / Off" method in PIXI.DisplayObject Documentation or PIXI.utils.EventEmitter Documentation

### ISSUE THREAD

**Issue by EIA** [pixijs/pixi.js#6788]
### Current Behavior
No "On / Off" method in [PIXI.DisplayObject](https://pixijs.download/dev/docs/PIXI.DisplayObject.html) Documentation
or [PIXI.utils.EventEmitter](https://pixijs.download/dev/docs/PIXI.utils.EventEmitter.html) Documentation

in example INTERACTION > [Click](https://pixijs.io/examples/#/interaction/click.js):

```
sprite.on('pointerdown', onClick);
```
but there’s no **off** for remove listener

feel a little confused how to remove listener(s).

### Possible Solution
copy document from [eventemitter3](https://github.com/primus/eventemitter3/blob/master/index.js) to  [PIXI.utils.EventEmitter](https://pixijs.download/dev/docs/PIXI.utils.EventEmitter.html)

Lists:
- EventEmitter.prototype.eventNames
- EventEmitter.prototype.listeners
- EventEmitter.prototype.listenerCount
- EventEmitter.prototype.emit
- EventEmitter.prototype.on
- EventEmitter.prototype.once
- EventEmitter.prototype.removeListener
- EventEmitter.prototype.removeAllListeners
- EventEmitter.prototype.off
- EventEmitter.prototype.addListener 

I can do this, can i create a pull request?

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by SukantPal** [comment]
@bigtimebuddy would probably have an idea for this. `EventEmitter` is not actually a part of the PixiJS codebase, so I'm not sure if everyone would be onboard with this. But it sounds fine to me.

**Comment by bigtimebuddy** [comment]
I definitely can understand why it would be useful for new people, completeness of docs, and for users unfamiliar with the Node.js' EventEmitter API. However, I'm pretty sure this would mess-up our auto-generated typings (which injects the EventEmitter bits). Maybe it makes sense to add this after we add typings generation? Then there would be no build conflicts.

**Comment by SukantPal** [comment]
@bigtimebuddy What if we can just redirect the `PIXI.utils.EventEmitter` URL to the NodeJS `EventEmitter` docs?

**Comment by bigtimebuddy** [comment]
A link in the docs is good but probably doesn’t solve the user’s underlying issue (on/off not listed or in the side bar). We already have a link to eventemitter3 too.

**Comment by Tonksi** [comment]
In pixi.js 6 these functions are not included in typings and the following flags up as an error:
`sprite.on('moved', () => {});`

`Property 'on' does not exist on type 'Sprite'.`

for now I am just disabling typescript for these functions, not ideal

**Comment by Ayfri** [comment]
See https://github.com/pixijs/pixijs/issues/7429 👀
