### ISSUE TITLE
[Question] Is there a way to implement an automated End-to-End test?

### ISSUE THREAD

**Issue by DennisMaass** [pixijs/pixi.js#6794]
Hey all,

do somebody know a way to implement an automated end-to-end test with the help of for example Cypress, Puppeteer or any other tools?

Do you know an other automated possibility to end-to-end test for example a drag and drop functionality and such things?

Best,
Dennis

**Comment by Tobbb** [comment]
We have been using nightwatch for end-to-end tests with accessibility enabled in pixi to detect where stuff is on the canvas. Still early in the process but it seems to be working quite well but im also interested in knowing if there is any better solution.

**Comment by DennisMaass** [comment]
@Tobbb Can you please explain your technique in more detail?

With accessibility enabled, did you have to use the tab key first to get through the elements? And after reaching the correct one you checked the position? How did you know that you reached the correct one?

But I think drag and drop is not possible to test, right?

**Comment by Tobbb** [comment]
@DennisMaass  yes, we send tab with nightwatch, after that the element can be found with element search (the type (div, and so on can be set and some other types in pixi)).

sending clicks on that element will flow down to pixi canvas. 
we found that for some reason tabs need to be sent every ~6 clicks or the overlay will go way.

i think it should be doable to use drag and drop, using the element as the startingpoint

**Comment by DennisMaass** [comment]
Thank you @Tobbb 👍  I will try that...

Are there any other ideas?
