### ISSUE TITLE
Unable to create PIXI.TilingSprite from a RenderTexture

### ISSUE THREAD

**Issue by hmandal** [pixijs/pixi.js#6795]
### Expected Behavior
Should be able to create a PIXI.TilingSprite from a RenderTexture

### Current Behavior
pixi.js throws error in the console saying `Unrecognized source type to auto-detect Resource`

### Possible Solution
N/A

### Steps to Reproduce
Just run the application at - https://jsfiddle.net/63tjmb4k/14/ and notice the above mentioned console error.

Its to be noted that this used to work fine in pixi.js v4.8.7 see here - https://jsfiddle.net/19zw7cex/5/

### Environment

- **`pixi.js` version**: _5.3.3_
- **Browser & Version**: _GoogleChrome 80.0.3987.163 (Official Build) (64-bit)_
- **OS & Version**: _Windows 10_
- **Running Example**: _https://jsfiddle.net/63tjmb4k/14/_

In case I'm doing it wrong then please let me know the correct way.

**Comment by bigtimebuddy** [comment]
I think the API changed here slightly. Do `new PIXI.TilingSprite(texture)` instead of `PIXI.TilingSprite.from(texture)`

**Comment by hmandal** [comment]
Thanks for the above solution!
