### ISSUE TITLE
Chart.js display in Pixi 

### ISSUE THREAD

**Issue by SP12893678** [pixijs/pixi.js#6797]
Hey, I try to implement that using chart.js makes the chart to be sprite.
I use the below of code, but the screen is not display anything.
```javascript
var canvas = document.createElement('canvas')
var ctx = canvas.getContext('2d')
var myRadarChart = new Chart(ctx , {
            type: 'radar',
            data: data,
            options: options,
})
var chart_texture = PIXI.Texture.fromCanvas(canvas)
var chart_sprite = new PIXI.Sprite(chart_texture)
this.addChild(chart_sprite)
```
### Environment

- **`pixi.js` version**: 4.6.2
- **`chart.js` version**: 2.9.3
- **Browser & Version**: Chrome
- **OS & Version**: Windows 10

**Comment by SukantPal** [comment]
`PIXI.Texture.fromCanvas` is deprecated. You must either call `PIXI.useDeprecated` or just use `PIXI.Texture.from`.

**Comment by ivanpopelyshev** [comment]
@SukantPal version: 4.6.2

Are you sure that its already drawn when pixi makes `texImage2d` call?

If not, call `texture.update()` after you draw the chart. If it doesnt exist in v4, well, im sorry, you have to update pixi.

**Comment by SP12893678** [comment]
I have already called `chart_texture.update()`, but it's not displaying anything. 
Because the version restrictions of other library, I still need to use version 4.6.2.
Now, I try to use `PIXI.Grahpics` to draw radar chart.

Thanks for your help.

**Comment by ivanpopelyshev** [comment]
That's strange. Really need full demo to help, because its outdated version and its not in my brain cache

**Comment by SP12893678** [comment]
I make a simple demo for pixi.js and chart.js that includes the chart.js with/without pixi.js.
[demo](https://codepen.io/sp12893678/pen/abNbrdV)

**Comment by Mason-Chou** [comment]
@SP12893678 see this updated [codepen](https://codepen.io/Mason-Chou/pen/WNxwrxK) for a working version. The chartjs canvas needs to be render on the screen before it can be used with Pixi. Pixi cannot do off screen rendering for you if you are using a canvas as as source object.

You might be able to make it work by making the chartjs canvas hidden away and then loading the spirte in a later time using `setTimeout`. Didn't spend much time with toying around with the idea.

**Comment by bigtimebuddy** [comment]
Thanks for the answer @Mason-Chou. Closing this issue.
