### ISSUE TITLE
Pluggable Triangulation Library

### ISSUE THREAD

**Issue by mudcube** [pixijs/pixi.js#6800]
PIXI.js currently uses `Earcut` tessellation library, this works great for most closed polygons.  When the polygons are not closed (polylines), or very complex, however, Earcut can fail, resulting in triangular shards.  Additionally, there is currently no way to specify winding rules, like NONZERO.

### Current Behavior
<img width="358" alt="Screen Shot 2020-08-09 at 2 32 18 PM" src="https://user-images.githubusercontent.com/101564/89742265-3123fb00-da4d-11ea-8f3b-a8d6aa4a8064.png">

### Expected Behavior
<img width="339" alt="Screen Shot 2020-08-09 at 2 32 34 PM" src="https://user-images.githubusercontent.com/101564/89742264-2f5a3780-da4d-11ea-827c-ae5b30c6d1f2.png">

### Possible Solution
THREE exposes `triangulateShape` so programmers can override:  `THREE.Shape.Utils.triangulateShape`. In PIXI to resolve this issue `buildPoly.triangulate` would simply need to be exposed, perhaps it could be exposed at the `PIXI.graphicsUtils.triangulate` namespace? 

Related to the following locked issues:  #3282, #4151

**Comment by eXponenta** [comment]
https://www.pixiplayground.com/#/edit/NWa_z1hMuF92Dwmyb3AEl

**Comment by mudcube** [comment]
That's fantastic. Thanks! :)

**Comment by Camelot93** [comment]
@eXponenta what install did you use to use Tess2? reference to your Pixi playground    
const res = Tess2.tesselate({
            contours: [points],
            windingRule: Tess2.WINDING_ODD ,
            elementType: Tess2.POLYGONS,
            polySize: 3,
            vertexSize: 2
        });

**Comment by ivanpopelyshev** [comment]
@Camelot93 

![image](https://user-images.githubusercontent.com/695831/90618242-603e2780-e218-11ea-9963-87f7ed991147.png)

**Comment by Camelot93** [comment]
@ivanpopelyshev Got it thanks Ivan!
