### ISSUE TITLE
can't open https://pixijs.io/examples/

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixi.js#6801]
jquery-3.3.1.min.js:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
pixi-examples.min.js?v=5.0.0:1 Uncaught ReferenceError: jQuery is not defined
    at pixi-examples.min.js?v=5.0.0:1

**Comment by mudcube** [comment]
I bet the jquery hosted url was down for a moment:  https://code.jquery.com/jquery-3.3.1.min.js

Seems to be working now though!

**Comment by a6965921** [comment]
> I bet the jquery hosted url was down for a moment: https://code.jquery.com/jquery-3.3.1.min.js
> 
> Seems to be working now though!

i dou't know how to  open it

**Comment by SukantPal** [comment]
Followup here: #6831
