### ISSUE TITLE
Getting this build error with PIXI 

### ISSUE THREAD

**Issue by bkadime** [pixijs/pixi.js#6803]
57     import InteractionEvent = PIXI.interaction.InteractionEvent;
                                      ~~~~~~~~~~~
node_modules/pixi-layers/dist/pixi-layers.d.ts:106:36 - error TS2694: Namespace 'PIXI' has no exported member 'interaction'.

106     import InteractionEvent = PIXI.interaction.InteractionEvent;
                                       ~~~~~~~~~~~
node_modules/pixi-scrollbox/@types/index.d.ts:103:35 - error TS2694: Namespace 'PIXI' has no exported member 'interaction'.

103     private scrollbarDown(e: PIXI.interaction.InteractionEvent): void
                                      ~~~~~~~~~~~
node_modules/pixi-scrollbox/@types/index.d.ts:108:35 - error TS2694: Namespace 'PIXI' has no exported member 'interaction'.

108     private scrollbarMove(e: PIXI.interaction.InteractionEvent): void

**Comment by Zyie** [comment]
If i remember correctly `interaction` namespace was deprecated in v5.3.0 along with `accessibility`. It looks like `pixi-layers` and `pixi-scrollbox` will need to update there types.

probably better to open up an issue on those packages directly?

**Comment by jahed** [comment]
For anyone getting this error in their own projects, the migration path is:

Given

```
PIXI.interaction.InteractionData
```

Remove `interaction` namespace.

```
PIXI.InteractionData
```
