### ISSUE TITLE
WebGL unsupported in this browser - Firefox 79.0 (64-bit)

### ISSUE THREAD

**Issue by MRVDH** [pixijs/pixi.js#6804]
- WebGL is supported (https://get.webgl.org/)
- v5 demos load on canvas instead of WebGL (https://pixijs.io/examples/#/demos-basic/container.js)
- Stencil is supported (https://caniuse.com/#search=WebGLRenderingContext%20stencil)

Cause: failIfMajorPerformanceCaveat was fired. Never had any problems until last week. Still no idea why this is happening.
Workaround: `PIXI.settings.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT = false;`

### Environment

- **`pixi.js` version**: v5.3.3
- **Browser & Version**: Firefox 79.0 (64-bit)
- **OS & Version**: Windows 10 Home - Version 10.0.19041 Build 19041

**Comment by themoonrat** [comment]
The check for 'if webgl is allowed' also checks for failIfMajorPerformanceCaveat and stencil support. That's where the difference is.
https://github.com/pixijs/pixi.js/blob/dev/packages/utils/src/browser/isWebGLSupported.ts

**Comment by MRVDH** [comment]
@themoonrat Stencil is supported (https://caniuse.com/#search=WebGLRenderingContext%20stencil)
So it must be failIfMajorPerformanceCaveat? Any idea what could be wrong?

**Comment by themoonrat** [comment]
You can set that flag to be ignored if you wish via https://pixijs.download/dev/docs/PIXI.settings.html#.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT

But that's just the browser going "hey, with this graphics card and these drivers, I think performance is going to be really bad". You can ignore that with the flag I've just given, but there's nothing more beyond that. Each browser has their own blacklist of certain devices / drivers / feature combinations that they'll decide is either not supported, or supported but with a performance caveat.

**Comment by MRVDH** [comment]
It's still strange because everything was working like normal until this week. I can't tell what changed to be honest other than me updating from 5.2.x to 5.3.3. Therefore I registered it as an issue. Though I'll look furthur into what might have suddenly caused this. Thanks for the quick fix at least 👍

**Comment by ivanpopelyshev** [comment]
try to go back to 5.2 and check it
