### ISSUE TITLE
Applying filter to a sprite inside a renderer that has resolution > 1 results in blurry output

### ISSUE THREAD

**Issue by MinimogDev** [pixijs/pixi.js#6805]
### Expected Behavior
Filters should respect resolution of renderer

### Current Behavior
Applying filter to a sprite that is rendered with a resolution higher than 2 results in this sprite appearing blurry, example below shows this by applying alpha filter to second snake. It is worth to note that applying alpha straight on the sprite (without using filters) does not result in this behaviour and works correctly.

<img width="389" alt="Screenshot 2020-08-10 at 14 07 28" src="https://user-images.githubusercontent.com/67905300/89776563-d8b73100-db12-11ea-9145-1711c70ce7f8.png">

### Possible Solution
Right now this can be fixed by manually setting filter resolution, but ideally filter should inherit this information from its renderer?

### Steps to Reproduce
See [Running Example](https://www.pixiplayground.com/#/edit/G8dhDd48n2CwSG2zBDoHT), you will likely need to view it on a screen that has higher resolution, in this case it is hardcoded to `2`

### Environment
- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Chrome 84.0.4147.105
- **OS & Version**: MacOS 10.15.6
- **Running Example**: https://www.pixiplayground.com/#/edit/G8dhDd48n2CwSG2zBDoHT

**Comment by ivanpopelyshev** [comment]
we also have `PIXI.settings.FILTER_RESOLUTION` : https://github.com/pixijs/pixi.js/blob/8998367f026d2a729bc3ae8583c4b6954de42260/packages/core/src/filters/Filter.ts#L185

I guess we need a few other values "AUTO", "THE_BEST" for resolution and a number of IF's to make better system. I honestly dont know whether any new system will be better at all cases.

**Comment by MinimogDev** [comment]
Is there any particular reason to why filter resolution is separate from Application resolution? And is it possible to set global filter resolution somehow (i.e set in one place and forget about it). If they need to be separate from Application resolution, perhaps `new PIXI.Application` can add an argument of `filterResolution` ?

**Comment by ivanpopelyshev** [comment]
yes. first, Application is a mashup that I personally dont use at all.

As for Renderer, that's because we do not have special values and flags that inherit resolution from renderer. We only use numbers. The problem is **time**. If you have it - make a PR.

**Comment by ivanpopelyshev** [comment]
The issue itself is not priority because we have global constant that works , and people use it. Maybe make better documentation for filters? 

There are many other things that need attention than this one.

**Comment by MinimogDev** [comment]
Totally understand the time aspect, `PIXI.settings.FILTER_RESOLUTION` works for my use case, I wasn't aware of it before.
