### ISSUE TITLE
Bug: BlurFilter with kernelSize >= 9 do not work in ios

### ISSUE THREAD

**Issue by jasonChen1982** [pixijs/pixi.js#6807]
### Current Behavior
when i use BlurFilter and kernelSize >= 9 , I will get an error
![image](https://user-images.githubusercontent.com/8683772/89980705-00d69980-dca5-11ea-851a-40efdf2ecd34.png)

and i found the broken point is 
```c
varying vec2 vBlurTexCoords[kernelSize]
```

### Possible Solution
```c
varying vec2 vBlurTexCoords0
varying vec2 vBlurTexCoords1
varying vec2 vBlurTexCoords2
varying vec2 vBlurTexCoords3
varying vec2 vBlurTexCoords4
varying vec2 vBlurTexCoords5
varying vec2 vBlurTexCoords6
varying vec2 vBlurTexCoords7
varying vec2 vBlurTexCoords8
```

### Environment

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: safari Safari/604.1
- **OS & Version**: iPhone 7 iOS 13.5 
- **Running Example**: TODO

**Comment by ivanpopelyshev** [comment]
That wont work. There's a limit on varying number of values on iOS. 

If you want to use that kernel - copy pixi blurfilter and move coord calculation to fragment shader, that way you can use only one of vBlurTexCoords
