### ISSUE TITLE
Does PIXI.Texture.fromBuffer support RGB images?

### ISSUE THREAD

**Issue by cnaaq** [pixijs/pixi.js#6808]
I have a problem with implementing a feature (or understanding documentation) correctly:
I have this example that works fine:

```
const size = 100
let buff = new Uint8Array(size * size * 4);
for (let i = 0; i < size * size * 4; i++) {
    buff[i * dim] = 0;  // R
    buff[i * dim + 1] = 255;  // G
    buff[i * dim + 2] = 0;  // B
    buff[i * dim + 3] = 100;  // A
}
const texture = PIXI.Texture.fromBuffer(buff, size, size);
// then add texture to Sprite and show...
```

However, in the documentation it is mentioned that `fromBuffer` accept `PIXI.BaseTexture` options.
I thought I can use `format` to force RGB images instead. Here is what I did:

```
const size = 100
let buff = new Uint8Array(size * size * 3);
for (let i = 0; i < size * size * 3; i++) {
    buff[i * dim] = 0;  // R
    buff[i * dim + 1] = 255;  // G
    buff[i * dim + 2] = 0;  // B
}
const texture = PIXI.Texture.fromBuffer(buff, size, size, {format: PIXI.FORMATS.RGB});
// then add texture to Sprite and show...
```

But it doesn't seem to work. The question is does the `buff` have to be in RGBA format?

**Comment by ivanpopelyshev** [comment]
Did you debug what is actually passed to `texImage2D` in BufferResource ? 

Also its different for WebGL and WebGL2, you should make your own resource that has following logic: for webgl2 internalFormat should be RGB8, format just RGB.

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D

**Comment by cnaaq** [comment]
Hi,

Well I understood something weird.
The RGB code functions with some `size`s, and doesn't with others!
For instance for `size=100, 200, 300, etc` it works, but for  `size=102, 150, 160, etc` it doesn't.
I have no idea why!

**Comment by Mikiyas34** [comment]
If you are experiencing an issue with the image not displaying correctly when using the `frombuffer` method, it is crucial to take immediate action. To resolve this issue, you need to follow the following troubleshooting steps:

1. First and foremost, check the format of the image data and ensure that it aligns with the expected format by the `frombuffer` method. If the format is incorrect, the image may not display correctly, and you need to rectify it immediately.

2. Secondly, check the dimensions of the image and ensure that they match the expected dimensions by the `frombuffer` method. If the dimensions are incorrect, the image may not display correctly, and you need to adjust them accordingly.

3. Thirdly, check the byte order of the
