### ISSUE TITLE
sprite's position changed when resize canvas size

### ISSUE THREAD

**Issue by sucresk** [pixijs/pixi.js#6809]
pixi.js version**: 5.3.1+

I want to resize canvas.
<img width="853" alt="AA7894DB-9336-451B-8098-188D2E6CCDC2" src="https://user-images.githubusercontent.com/2068810/90010622-b9ff9880-dcd2-11ea-965f-3e864a7adad7.png">

I modify canvas ' height from 916 to 800,  but the display 's position up out of scree. I wish it freeze

<img width="894" alt="106EC842-88B8-4A62-9B0C-024B8D043E4C" src="https://user-images.githubusercontent.com/2068810/90010640-bff57980-dcd2-11ea-96cd-9e5a22dceb69.png">

**Comment by ivanpopelyshev** [comment]
use `renderer.resize`. 

PixiJS does not update its internal variables, it doesnt try to detect those outer changes.

**Comment by yangxiao86** [comment]
> 使用。`renderer.resize`
> 
> PixiJS 不更新其内部变量，它不会尝试检测回缓冲器的这些外部更改。

version <= 5.3.0  normal
