### ISSUE TITLE
Trying to play video from user selected path (file blob)

### ISSUE THREAD

**Issue by AlexandreRangel** [pixijs/pixi.js#6813]
Dear PIXI friends, I'm trying to play a video in PIXI that gets selected from the user local filesystem.
With the current code below, it loads ok but doesn't play or give error messages.
Any clues? Thank you!!

### Expected Behavior
Choose video file with file picker.
Play video with play button.

### Current Behavior
Video file blob gets load ok (address variable).
When user clicks play button, it doesn't play and gives no error on console.
If code tries to load hard codes path, it works.

### Steps to Reproduce
Choose video file with file picker.
Click play button.

### Environment
- **`pixi.js` version**: 5.1.3
- **Browser & Version**: Chrome 84.0.4147.125
- **OS & Version**: Windows 10
- **Running Example**: [http://www.alexandrerangel.art.br/pixi/pixi-video-loader/index.html](http://www.alexandrerangel.art.br/pixi/pixi-video-loader/index.html)

### HTML Code:
```
<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.1.3/pixi.min.js"></script>
        <script src="video.js"></script>
    </head>
    <body>
        <input type="file" accept="" onchange="loadFile(event)">
    </body>
    <script>
        var address;
        var loadFile = function(event) 
        {
            address = URL.createObjectURL(event.target.files[0]);
        }
    </script>
</html>
```

### JS Code:
```
window.onload = function() {

    const app = new PIXI.Application({ transparent: true });
    document.body.appendChild(app.view);

    const button = new PIXI.Graphics() // play button to trigger the video
        .beginFill(0x0, 0.5)
        .drawRoundedRect(0, 0, 100, 100, 10)
        .endFill()
        .beginFill(0xffffff)
        .moveTo(36, 30)
        .lineTo(36, 70)
        .lineTo(70, 50);

    button.x = (app.screen.width - button.width) / 2;   // button pos x
    button.y = (app.screen.height - button.height) / 2; // button pos y

    button.interactive = true;  // enable button interactivity
    button.buttonMode = true;

    app.stage.addChild(button); // add button to the stage
    button.on('pointertap', onPlayVideo);

    function onPlayVideo() {
        button.destroy();

        //const texture = PIXI.Texture.from('./video.mp4'); // works with this hard coded path
        const texture = PIXI.Texture.from(address); // create video texture from user selected path (address)

        const videoSprite = new PIXI.Sprite(texture);
        videoSprite.width = app.screen.width;
        videoSprite.height = app.screen.height;
        app.stage.addChild(videoSprite);
    }

}
```

**Comment by monkianer** [comment]
you can create a video tag to hold selected video path and pass the video to pixi.texture. i did a simple test on the codepen
https://codepen.io/monkianer/pen/rNeejrm

**Comment by AlexandreRangel** [comment]
Thanks a lot, @monkianer ! It worked like a charm!
