### ISSUE TITLE
Drop shadow color doesn't support string value

### ISSUE THREAD

**Issue by Keycher** [pixijs/pixi.js#6818]
### Expected Behavior
Support string values, e.g "white", "red", etc
### Current Behavior
![4cd72b5954869b0f146a52630f7302ab](https://user-images.githubusercontent.com/6191357/90371658-f1c26380-e077-11ea-90ec-542569c55907.png)
Any string value is black color

### Environment

- **`pixi.js` version**: 5.3.3 (release)
- **Running Example**: [example](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowBlur%22%3A12%2C%22dropShadowColor%22%3A%22white%22%2C%22dropShadowDistance%22%3A0%2C%22padding%22%3A10%2C%22strokeThickness%22%3A1%7D%2C%22background%22%3A%22%23fa5252%22%7D)

**Comment by famibee** [comment]
I am the same phenomenon.
In my memory, it seems that color names cannot be used from around pixi.js v5.0.3.
I recently found "Issues" and found this post when I tried to write it...

自分も同じ現象です。
自分の記憶では pixi.js v5.0.3 頃から色名前が使えないようです。
「Issues」を最近知って書き込もうとしたら、この投稿を見つけました……。

**Comment by famibee** [comment]
Thanks!
