### ISSUE TITLE
enable cacheAsBitmap for masked text

### ISSUE THREAD

**Issue by dk672** [pixijs/pixi.js#6821]
Hello.
I'm not familiar with English, so please forgive me if the text is strange.

When I enable `cacheAsBitmap` for masked text, the display coordinates are off, is there a workaround?

### Environment

- **`pixi.js` version**: _5.2.4_
- **Browser & Version**: _Chrome 84_
- **OS & Version**: windows 10
- **Running Example**: _https://jsfiddle.net/m8bgjvy1/_

**Comment by monkianer** [comment]
I think you can try set your text and mask position (0, 0), then reposition you container to the right position.
**Example:** https://jsfiddle.net/ntyr4g6x/

**Comment by dk672** [comment]
Thanks for the reply!

Does that mean the text to be added to the container has to be position(0,0)?

I want to have multiple text in the container to center or adjust the positioning.

Example: https://jsfiddle.net/k1ufLp2t/

**Comment by monkianer** [comment]
Ok! It seems there is a bug exist in the cacheAsBitmap. Here is a workaround by using PIXI.RenderTexture. You may need some adjustments to fit your need.
**Example:** https://jsfiddle.net/cm9q2dw7/2/

**Comment by dk672** [comment]
Thank you!
I was having trouble encountering this event in the Pixi.js v4 to v5 migration, but it looks like I'll be able to move on.
