### ISSUE TITLE
Multiline BitmapFont / BitmapText lineHeight doesn't work

### ISSUE THREAD

**Issue by MinimogDev** [pixijs/pixi.js#6823]
### Expected Behavior
When creating bitmap font that uses style with defined `lineHeight`, it should be respected for all lines in multiline text.
Multiline text should apply this lineHeight to all text lines.

### Current Behavior
It seems as if only first line of text gets lineHeight applied.

### Possible Solution
Not sure

### Steps to Reproduce
This is also available via example provided below. Note how `lineHeight: 50` is only applied to first line of text.

```ts
import * as PIXI from "pixi.js";
import "./styles.css";

var app = new PIXI.Application({
  width: window.innerWidth,
  height: window.innerHeight,
  resolution: window.devicePixelRatio,
  autoDensity: true,
  backgroundColor: 0x2c3e50
});

document.body.appendChild(app.view);

function main() {
  PIXI.BitmapFont.from(
    "MyFont",
    new PIXI.TextStyle({
      fontSize: 20,
      fontFamily: "Arial",
      lineHeight: 50, // This only changes height of first line
      fill: "#ffffff"
    }),
    { resolution: window.devicePixelRatio }
  );

  const text = new PIXI.BitmapText(
    "Hello World Hello World Hello World Hello World Hello World",
    { fontName: "MyFont" }
  );
  text.maxWidth = 200;

  app.stage.addChild(text);
}

main();
```

### Environment

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Chrome 84.0.4147.125
- **OS & Version**: MacOS 10.15.6
- **Running Example**: https://codesandbox.io/s/quirky-panini-3m6sq

**Comment by themoonrat** [comment]
Lineheight shouldn't be used within a BitmapFont.from - Only certain properties listed should be used.
We should probably remove any style settings passed through that aren't a valid option as per docs.

https://pixijs.download/dev/docs/PIXI.BitmapFont.html#.from

```
Generates a bitmap-font for the given style and character set. This does not support kernings yet. With style properties, only the following non-layout properties are used:

dropShadow
dropShadowDistance
dropShadowColor
dropShadowBlur
dropShadowAngle
fill
fillGradientStops
fillGradientType
fontFamily
fontSize
fontVariant
fontWeight
lineJoin
miterLimit
stroke
strokeThickness
textBaseline
```

**Comment by MinimogDev** [comment]
Alright, gotcha. Is support for this planned by any chance, as right now having paragraphs of text with that default line height is impractical due to how close lines are together. And is that line height on the first line a bug in this case?
