### ISSUE TITLE
RenderTexture rectangle frame

### ISSUE THREAD

**Issue by ptsans** [pixijs/pixi.js#6828]
Hi everyone!

How to select custom rect frame for the RenderTexture after release 5.3.1?

Because the same code in the 5.3.0 release works fine, according to the [documentation](https://pixijs.download/dev/docs/PIXI.RenderTexture.html#RenderTexture).

Example v5.3.1 : 5.3.3 - [Link](https://www.pixiplayground.com/#/edit/Xzoj_nd1ZtuQTooNi1fVz)

Example v5.3.0 - [Link](https://www.pixiplayground.com/#/edit/lPejsOxIMoDYKSTWdZYYr)

Hey @SukantPal, can you help me?

**Comment by rob-myers** [comment]
This didn't work me:
```json
"pixi.js": "^7.3.2",
```
but this worked instead:
```tsx
renderTexture._frame.copyFrom(new Rectangle(0, 0, 100, 100));
```
