### ISSUE TITLE
"jQuery is not defined" in pixijs.com

### ISSUE THREAD

**Issue by chenyinkai** [pixijs/pixi.js#6831]
I want to view the example but the [page](https://pixijs.io/examples/) cannot be loaded successfully because the jquery resource cannot be found.

### Environment

- **Running Example**:  https://pixijs.io/examples/

**Comment by laino** [comment]
It works for me. jQuery is loaded from ``https://code.jquery.com/jquery-3.3.1.min.js``.

Could you maybe check what happens to that request on your end? Maybe you're running some plugin blocking it.

**Comment by ivanpopelyshev** [comment]
Yes, that link is not firewall-proof, we should use another. @chenyinkai can you recommend which service or npm mirror is available for you?

**Comment by chenyinkai** [comment]
@ivanpopelyshev  Thank you for your reply. Google and Microsoft's CDN works for me. `http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js`  
 `http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js`.

**Comment by lizy0329** [comment]
GET https://code.jquery.com/jquery-3.3.1.min.js net::ERR_CONNECTION_RESET
