### ISSUE TITLE
Geometry cannot read property 'buffer' of undefined during interaction handling

### ISSUE THREAD

**Issue by flekschas** [pixijs/pixi.js#6833]
I am trying to find out what could cause the `Cannot read property 'buffer' of undefined` error described below. I've never seen this kind of error before and the trace back doesn't point to any of my code but I can trace it manually back to a mesh I created. However, I have no idea what specifics could trigger this error.

Any points or ideas would be much appreciated

### Expected Behavior
No error should be thrown when mousing over an interactive graphics object containing a mesh.

### Current Behavior
When mousing over a custom mesh graphics I am getting:

```javascript
Uncaught TypeError: Cannot read property 'buffer' of undefined
    at Geometry.getBuffer (Geometry.ts:178)
    at Mesh.containsPoint (Mesh.ts:465)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:157)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113)
    at TreeSearch.recursiveFindHit (TreeSearch.ts:113)
    at TreeSearch.findHit (TreeSearch.ts:200)
    at InteractionManager.processInteractive (InteractionManager.ts:1177)
    at InteractionManager.onPointerMove (InteractionManager.ts:1541)
Geometry.getBuffer @ Geometry.ts:178
Mesh.containsPoint @ Mesh.ts:465
TreeSearch.recursiveFindHit @ TreeSearch.ts:157
TreeSearch.recursiveFindHit @ TreeSearch.ts:113
TreeSearch.recursiveFindHit @ TreeSearch.ts:113
TreeSearch.recursiveFindHit @ TreeSearch.ts:113
TreeSearch.recursiveFindHit @ TreeSearch.ts:113
TreeSearch.recursiveFindHit @ TreeSearch.ts:113
TreeSearch.recursiveFindHit @ TreeSearch.ts:113
TreeSearch.recursiveFindHit @ TreeSearch.ts:113
TreeSearch.findHit @ TreeSearch.ts:200
InteractionManager.processInteractive @ InteractionManager.ts:1177
InteractionManager.onPointerMove @ InteractionManager.ts:1541

```

The buffer query is triggered by the InteractionManager and ultimately fails in [Geometry.ts](https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/geometry/Geometry.ts#L178)

```javascript
    getBuffer(id: string): Buffer
    {
        // Apparently `this` is `undefined`.
        return this.buffers[this.getAttribute(id).buffer];
    }
```

### Possible Solution
???

### Steps to Reproduce
I've never seen this error before in other cases when I mouse over an interactive graphics object containing a mesh. My guess is that it's somehow related to the use of a single buffer as three different geometry attributes with different offsets.

E.g.:

```javascript
const positions = new Float32Array([
  0,0,  // duplicated first point
  0,0,  1,1,  2,2,  3,3,  4,4,
  5,5,  6,6,  7,7,  8,8,  9,9,
  9,9  // duplicated last point
]);

geometry.addAttribute(
  'aPrevPosition',
  positions,
  2, // size
  false, // normalize
  PIXI.TYPES.FLOAT, // type
  FLOAT_BYTES * 2, // stride
  0 // offset/start
);

geometry.addAttribute(
  'aCurrPosition',
  positions,
  2, // size
  false, // normalize
  PIXI.TYPES.FLOAT, // type
  FLOAT_BYTES * 2, // stride
  FLOAT_BYTES * 2// offset/start
);

geometry.addAttribute(
  'aNextPosition',
  positions,
  2, // size
  false, // normalize
  PIXI.TYPES.FLOAT, // type
  FLOAT_BYTES * 2, // stride
  FLOAT_BYTES * 4 // offset/start
);
```

Beyond those attributes the mesh contains some a bunch of uniforms:

```javascript
const uniforms = new PIXI.UniformGroup({
  uLineColor: [0.0, 0.0, 0.0, 1.0],
  uNaNColor: [1.0, 1.0, 1.0, 1.0],
  uAreaColorTex: colorTex,
  uAreaColorTexRes: colorTexRes,
  uWidth: 0.25,
  uMiter: 1,
});

const shader = PIXI.Shader.from(VS, FS, uniforms);

// The attributes from above
geometry.addAttribute('aOffsetSign', new Float32Array([]), 1);
geometry.addAttribute('aColorIndex', new Float32Array([0,1,0,1,2,3,10,0,8,111,0,1]), 1);
geometry.addIndex(indices);

const mesh = new PIXI.Mesh(geometry, shader);

const newGraphics = new PIXI.Graphics();
newGraphics.addChild(mesh);
```

### Environment

- **`pixi.js` version**: _5.3.0_
- **Browser & Version**: _Chrome 83_
- **OS & Version**: _macOS 10.14.6_

**Comment by flekschas** [comment]
I should add that the rendering works as expected. Also, subsequent updates (rescaling, repositioning, etc.) work just fine.

I found out that the issue not related to the code above but rooted somewhere in our main app's class hierarchy. 😅 I am closing the issue now as it's not a bug in PIXI. If anyway has an idea how to find the root cause of such an issue, comments are still very much appreciated.

**Comment by etai-shuchatowitz** [comment]
Hello,

I've just run into the exact same issue when migrating from PIXI 6.1 to PIXI 7.2. Did you ever find a solution to this?
