### ISSUE TITLE
iPadOS14 breaks pixi - pixi examples do not load 

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi.js#6835]
Hi I was just testing my games on iPadOS 14 and it look like the beta has serious issues with pixi :(

Most of your examples do not seem to even load.

Have only tested on one ipad on iOS14 (if anyone else has updated to the beta would be good to get confirmation the issue exists on another device)

Hope that this will be fixed before release but posting so you are aware.

Thanks
Matt

### Expected Behavior
View the slots game on your example
https://pixijs.io/examples/#/demos-advanced/slots.js

### Current Behavior
Demo does not load
Slots
console errors include
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
TypeError: null is not an object (evaluating 'shaderFragment.precision')

scratchcard example:
https://pixijs.io/examples/#/demos-advanced/scratchcard.js
Overlay does not show

### Possible Solution
Reported issue to Apple via feedback

### Environment

- **`pixi.js` version**: v4 and v5 tested
- **Browser & Version**: Chrome and Safri
- **OS & Version**: _e.g. iPadOS 14 beta (18A5351d) running on iPad Air 2
- **Running Example**: https://pixijs.io/examples/#/demos-advanced/scratchcard.js

**Comment by macguffin** [comment]
https://get.webgl.org/ 
this also doesn't work - no spinning cube so looks like this beta has messed up webGL support and it isn't just pixi effected

**Comment by themoonrat** [comment]
Well, that was a rollercoast of emotions reading this :P 
I'm assuming the entirety of WebGL breaking is something deemed worthy of Apple fixing :D

**Comment by rthewitt85** [comment]
Hi - any idea if this has been flagged to Apple / if Apple are gonna fix it?

**Comment by themoonrat** [comment]
looks to be fixed on latest beta? According to browserstack, anyway

**Comment by macguffin** [comment]
FYI this is fixed in iOS14 beta 8
:)

**Comment by themoonrat** [comment]
Thanks for confirming!

**Comment by rthewitt85** [comment]
Thanks both :-)

**Comment by shriramdevanathan** [comment]
The issue still persists in the new iOS14 release ?  Any workarounds ?

**Comment by themoonrat** [comment]
Browserstack shows the examples working on the latest version of iOS14, and games my company has in development all work on iOS14, too. Using the latest Pixi v5.

**Comment by aqua3090** [comment]
My cordova app crashes after the IOS 14 release.
the app uses PIXI.js 4.6.2 and crashes here : var renderer = PIXI.autoDetectRenderer(
                    viewSize[0], viewSize[1],
                    {
                        antialias: true,
                        resolution: window.devicePixelRatio || 1,
                        transparent: true
                    });

Unfortunately, It doesn't spit any log, making it difficult for me to debug
