### ISSUE TITLE
Bitmap font loader not working with "fnt"

### ISSUE THREAD

**Issue by Prior99** [pixijs/pixi.js#6840]
The bitmap font can't be loaded using "fnt" format with the code from the examples:

```javascript
app.loader
    .add('TestFont', './TestFont.fnt')
    .load(onAssetsLoaded);

function onAssetsLoaded() {
    const bitmapFontText = new PIXI.BitmapText('bitmap fonts are supported!\nWoo yay!', { font: 'TestFont', align: 'left' });

    bitmapFontText.x = 50;
    bitmapFontText.y = 200;

    app.stage.addChild(bitmapFontText);
}
```

# Expected Behavior

The text will be rendered.

### Current Behavior

The font is not available. Instead, an error is thrown:

```
BitmapText.ts:113 Uncaught Error: Missing BitmapFont "TestFont"
    at new BitmapText (BitmapText.ts:113)
    at onAssetsLoaded (index.js:11)
    at MiniSignal.dispatch (mini-signals.js:93)
    at Loader._onComplete (Loader.js:623)
    at Loader.js:662
    at next (async.js:33)
    at Loader.SpritesheetLoader.use (SpritesheetLoader.ts:37)
    at Loader.js:643
    at async.js:41
```

### Possible Solution

I have no clue.

### Steps to Reproduce

Clone https://github.com/Prior99/pixi-bitmapfont-loader-reproduce

```bash
yarn
yarn start
```

### Environment

- **`pixi.js` version**: 5.3.0
- **Browser & Version**: Chrome 85.0.4183.49
- **OS & Version**: Arch Linux

**Comment by EneaEntertainment** [comment]
Your font has fnt file extension which is supposed to be xml based format, but instead it is plain text. Renaming it to TestFont.txt should do the trick.

**Comment by Prior99** [comment]
@EneaEntertainment thanks, I will try that.

**Comment by bigtimebuddy** [comment]
The workaround is to do this:

```js
PIXI.LoaderResource.setExtensionXhrType('fnt', PIXI.LoaderResource.XHR_RESPONSE_TYPE.TEXT);
```

Basically, the default for `fnt` files is to [convert this to an XML Document](https://github.com/pixijs/pixi.js/blob/dev/packages/text-bitmap/src/BitmapFontLoader.ts#L26). Because we now support both text and XML-based formats, we should change this to be more accommodating. Adding the line above will change the format but means you can only use either TXT or XML. Your example worked for me when I added this line before calling `app.loader.add`.

PR is welcome to fix this.

**Comment by Prior99** [comment]
So is `*.fnt` really meant to be used for XML files only?

**Comment by bigtimebuddy** [comment]
Many bitmap-font generation tools (bmGlphy) support fnt files that can be both text or XML. Historically, PixiJS only had XML support. We added text-based recently but didn't adjust the file handling of `.fnt` to support both.

**Comment by Prior99** [comment]
@bigtimebuddy Thanks for clarifying :) Then I guess this is indeed a bug.
