### ISSUE TITLE
Clear just part of BaseRenderTexture

### ISSUE THREAD

**Issue by ptsans** [pixijs/pixi.js#6842]
I just want to correctly clear part of BaseRenderTexture.

See [example](https://www.pixiplayground.com/#/edit/QSMI0wvL4soHWq-BsjZyr).

I expect that if I bind a renderTexture with frame to a RenderTextureSystem and [call clear method](https://pixijs.download/dev/docs/packages_core_src_Renderer.ts.html#line401) on it, then only renderTexture will be cleared (not whole BaseRenderTexture).

**Comment by SukantPal** [comment]
@ptsans I don't think this would be implemented by PixiJS. First of all, as we discussed in #6828, the `Renderer#render` method doesn't truly support rendering to a part texture - so it really won't support clearing one either.

The best you can do to bypass this is to bind the render-texture yourself, and then clear it:

```js
renderer.renderTexture.bind(renderTexture, null, new Rectangle(...));
renderer.renderTexure.clear();
```

**Comment by ptsans** [comment]
@SukantPal  But I did the same, didn't I?

![Screenshot_20200829_104412](https://user-images.githubusercontent.com/18110232/91624608-a186c200-e9e4-11ea-82ed-591f6eeeba23.png)

And the whole texture is cleared.

![Screenshot_20200829_104912](https://user-images.githubusercontent.com/18110232/91624744-4c977b80-e9e5-11ea-9a2f-e122d306de94.png)

**Comment by SukantPal** [comment]
😅 Okay, I didn't see your code - I went to the documentation source you provided in `renderer#render`. Maybe a scissor mask is required b/c `gl.clear()` does not respect the viewport:

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/clear

**Comment by ivanpopelyshev** [comment]
Interesting case. I just want to remind that its completely different from usual `clear()`. which is a performance boost in certain mobile systems. In those systems, `bind(renderTexture)` copies stuff if `clear` does not follow it. 

Unfortunately, I cant get more info, because I didnt actually investigate it, I just know it was the case.
