### ISSUE TITLE
Why don't use `instanced_arrays` for more  cases ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#6846]
I found there is only one case used instanced_arrays , it's for Geometry.

I read some articles , they say that the instanced_arrays could take better performance .

Why pixi doesn't use instanced_arrays in more places ?

**Comment by SukantPal** [comment]
@finscn Instanced arrays are useful when a geometry is repeated. PixiJS is a generic renderer - for its Sprite, Graphics, Mesh. We really can't detect whether a geometry is repeated.

The only application of a instanced renderer I can see in PixiJS would be in the particles renderer

There was a concept being made in [@pixi-essentials/instanced-renderer](https://github.com/SukantPal/pixi-essentials/tree/master/packages/instanced-renderer), although it isn't built yet.

**Comment by ivanpopelyshev** [comment]
@finscn how are you?

**Comment by finscn** [comment]
> @finscn how are you?

Hi. Long time no see.   I'm fine,  I don't get COVID-19 , :P 

Now , I have a small team .   for  team work,  We need an all-in-one IDE and more Chinese document . 
So I  have to choose another Game Engine. 
I focus on Cocos Creator ( https://github.com/cocos-creator/engine ) . It's similar to Unity. 

But I still learn much from Pixi . So thank you very much.

**Comment by finscn** [comment]
@SukantPal  I see . Thank you
