### ISSUE TITLE
Mesh typing issue

### ISSUE THREAD

**Issue by nightly-sou** [pixijs/pixi.js#6850]
Hello, when i've been testing default pixi.js example in my environment (webstorm) on v5 [https://pixijs.io/examples/#/mesh-and-shaders/triangle-color.js](url) i got a typings problem with TypeScript. 
In place of creating mesh `new PIXI.Mesh(geometry, shader)` typescript says "Argument of type 'Shader' is not assignable to parameter of type 'MeshMaterial'."
So i gone to typings of pixi and found an issue
![image](https://user-images.githubusercontent.com/54750927/91704577-75a24280-eb84-11ea-854d-4a65924b566e.png)
So constructor of mesh gets a shader parameter of MeshMaterial type, but in mesh field it is Shader or MeshMaterial type.
Please fix this issue, thank you for your incredible work 👍

**Comment by ivanpopelyshev** [comment]
We cant make correct TS typings because there's no understanding of what should be there. Mesh is supposed to work to MeshMaterial but it can work with any Shader and in examples it works with Shader. 

Use `as any` and forget it

**Comment by nightly-sou** [comment]
@ivanpopelyshev Argument type in constructor is MeshMaterial / Shader, code of class just assigns argument of constructor to field in class, type of field is Shader. So that's just typing bug. Anyway. Ok... Thanks for reply.
