### ISSUE TITLE
Do not default to alpha = false when creating WebGL context

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6853]
I was trying to find a specific bottleneck in my PixiJS application and I found out that creating the context on my own made a HUGE difference (25-30 ➡️ 60 FPS on a 4K monitor). The difference was that I enabled alpha `alpha: true` when creating the WebGL context.

PixiJS defaults to `alpha: false` if the `transparent` option is not passed:

https://github.com/pixijs/pixi.js/blob/54665ecebe676bd0d89e7ceadabb1badd89c1cbb/packages/core/src/Renderer.ts#L280

### Evidence of this being a performance bottleneck

* https://bugs.chromium.org/p/chromium/issues/detail?id=1045643
* https://github.com/mrdoob/three.js/issues/18338#issuecomment-572531584
* https://bugs.chromium.org/p/chromium/issues/detail?id=1103485

Maybe we want to reevaluate whether `transparent = false` by default?

**Comment by SukantPal** [comment]
@bigtimebuddy do you think we could make this change?

**Comment by bigtimebuddy** [comment]
This is a tough one. It's definitely a breaking change to change the default. It will surprise a lot of users who were not expecting transparency. My suggestion is we consider this for v6 (which I'd like to get out sooner so we can make a bunch of these annoyingly small breaking changes). In the meantime, we should add this to the docs and recommend users on these platforms turn it on.

Also, I'd like to make sure that turning on transparency doesn't hurt us on other platforms. If other folks have experience with a large platform base, would be helpful to know what people's experience is here. Optimizing for Intel Macs isn't always good.

**Comment by SukantPal** [comment]
@bigtimebuddy Maybe a v6 milestone?

**Comment by themoonrat** [comment]
If it's set to false... is there any disadvantage to actually creating it with true, but then drawing a coloured background ourselves before rendering the actual pixi objects?

**Comment by andrewstart** [comment]
Anecdotally, I recall the standard fix for issues on mobile devices (like a number of older Samsung devices) being to set `transparent` to true. I'd mostly be concerned about changing the pre-multiplied alpha setting, as that would definitely have noticeable effects.

**Comment by SukantPal** [comment]
@themoonrat I didn't have to make any changes after setting it to true. Maybe because we clear all four RGBA channels in `render()`.

**Comment by bigtimebuddy** [comment]
@SukantPal Do you want to make a fix for this since 5.4.0 has now become 6.0.0?

**Comment by SukantPal** [comment]
Sure. I’ll do it over this weekend.
