### ISSUE TITLE
PIXI.FillStyle does not get values

### ISSUE THREAD

**Issue by Ef-Doga** [pixijs/pixi.js#6854]
### Expected Behavior
Trying to get the values of FillStyle of a graphics object using `graphics.fill` and getting the correct values used
### Current Behavior
`graphics.fill` returns a default FillStyle object with default values, to get the correct values I used the deprecated `graphics.graphicsData[0].fillStyle`
### Possible Solution
I think it is an initialization problem where the value is not set properly on `graphics.fill` or `graphics._fillStyle` attributes

### Steps to Reproduce
Here is the code I reproducted the bug

<pre>var renderer = null;
var stage = null;
var width = 600;
var height = 450;
function createPIXI() {
	 renderer = new PIXI.Renderer({width: width, height: height, view: document.querySelector("#myCanvas")})
	 renderer.backgroundColor = 0xCBCB3C
	 stage = new PIXI.Container()
	 setup()
	 animate()
}
function setup() {
	 const graphics = new PIXI.Graphics()
	 graphics.lineStyle(1, 0x000000, 1)
	 graphics.beginFill(0xCBCBCB, 0.5)
	 graphics.drawRect(105, 105, 105, 105)
	 graphics.endFill()
	 stage.addChild(graphics)
	 console.log(graphics.fill, graphics._fillStyle, graphics.graphicsData[0].fillStyle);
}
function animate() {
	 renderer.render(stage)
	 requestAnimationFrame(animate)
}
createPIXI();
</pre>

The output is:
wn {color: 16777215, alpha: 1, texture: e, matrix: null, visible: false}
wn {color: 16777215, alpha: 1, texture: e, matrix: null, visible: false}
wn {color: 13355979, alpha: 0.5, texture: e, matrix: null, visible: true}

### Environment

- **`pixi.js` version**: PixiJS 5.1.3
- **Browser & Version**: Chrome 85
- **OS & Version**:Windows 7

**Comment by SukantPal** [comment]
@Ef-Doga 

The `fillStyle` is reset when you `endFill`. If you want to get the `fillStyle` of the first drawn shape, you can use:

```js
graphics.geometry.graphicsData[0].fillStyle
```

That is not deprecated.
