### ISSUE TITLE
Texture Error: error dimensions

### ISSUE THREAD

**Issue by swanrnd** [pixijs/pixi.js#6858]
I have such error:
Texture Error: frame does not fit inside the base Texture dimensions: X: -1236.4285714285713 + 2736.4285714285716 = 1500.0000000000002 > 1500 or Y: 200 + 600 = 800 > 1000

1500.0000000000002 must be 1500 equal in JS. But I got a error.

Solution:
prototypeAccessors.frame.set =>
```
var xNotFit = (x + width).toFixed(5) > this.baseTexture.width;
var yNotFit = (y + height).toFixed(5)  > this.baseTexture.height;
```

- **`pixi.js` version**: 5.2.0
- **Browser & Version**: Chrome 85.0.4183.83
- **OS & Version**: MacOS 10.15.6

**Comment by bigtimebuddy** [comment]
Can you provide a live example that reproduces? Will help to verify bug. Thanks.

**Comment by ivanpopelyshev** [comment]
Oh, that's interesting. something with `resolution` parameter? Please maek a demo. I'm marking it as `X-Files` like we do for every floating-point precision problems.

**Comment by swanrnd** [comment]
I cannot repeat bug. It's a big project. But I suspect it's problem in this:
```
		var rectangle;
		
		if (_user.system.scale1 / _user.system.scale2 >= 1) {
		
			var offset = 1500 / 2 - _user.system.width / 2 / _user.system.scale;

			rectangle = new PIXI.Rectangle(offset, 200, 1500 - offset, 600);
		}
		else {
			
			var offset = 1000 / 2 - _user.system.height / 2 / _user.system.scale;
			rectangle = new PIXI.Rectangle(250, offset, 1000, 1000 - offset);
		}

		main.scale.set(_user.system.scale);
		var sprite = new PIXI.Sprite(new PIXI.Texture(PIXI.utils.TextureCache[image], rectangle));
```

image is 1500 x 1000. And we crop middle and center part of image.
