### ISSUE TITLE
pixi.js.d.ts: Definitions deviate from source code

### ISSUE THREAD

**Issue by jlost** [pixijs/pixi.js#6859]
Hi, on line 1679 of `pixi.js.d.ts` of pixi.js v5.3.3 from npm, `generateTexture` has 3 required parameters:
```
generateTexture(displayObject: PIXI.DisplayObject, scaleMode: PIXI.SCALE_MODES, resolution: number, region?: PIXI.Rectangle): PIXI.RenderTexture;
```
Also on line 2031:
```
generateTexture(displayObject: PIXI.DisplayObject, scaleMode: PIXI.SCALE_MODES, resolution: number, region?: PIXI.Rectangle): PIXI.RenderTexture;
```

This contrasts with line 299 of tag 5.3.3 on git, in which the actual code has 1 required parameter:
```
    generateTexture(displayObject: DisplayObject,
        scaleMode?: SCALE_MODES, resolution?: number, region?: Rectangle): RenderTexture
```

And the dev docs also show these extra parameters as optional:
https://pixijs.download/dev/docs/PIXI.Renderer.html#generateTexture

**Comment by jlost** [comment]
I noticed another typing problem, maybe it's related. In `pixi.js.d.ts` line 21180, options is optional:
```
static from(source: number | string | PIXI.Texture | HTMLCanvasElement | HTMLVideoElement, options?: any): PIXI.Sprite;
```
(It's also `any` typed, which doesn't seem to match the source code)

But on line 269 of the source code: 
https://github.com/pixijs/pixi.js/blob/6b3e881673511c885e3ef834e558c68771bb8b77/packages/sprite-tiling/src/TilingSprite.ts#L269

It's required, and typed properly.

**Comment by bigtimebuddy** [comment]
We are in the process of using a better method to generate typings. Release v5.4.0 will have better, more accurate auto-generated types and likely will fix these. Will not be fixing these for v5.3.x.
