### ISSUE TITLE
why circle is flickering?

### ISSUE THREAD

**Issue by aLiz-Nancy** [pixijs/pixi.js#6861]
### Expected Behavior
The circle does not rotate or grow, it just moves.

### Current Behavior
When the width of the screen becomes narrow, the behavior becomes strange when the circle goes to the bottom of the screen.

**Good**
![画面収録 2020-09-08 17 41 09 mov](https://user-images.githubusercontent.com/52145579/92456486-f3f28a80-f1fd-11ea-93c7-40dbe08ef272.gif)

**Bad**
![画面収録 2020-09-08 17 40 46 mov](https://user-images.githubusercontent.com/52145579/92456407-d6bdbc00-f1fd-11ea-9360-fda346d1da38.gif)

### Possible Solution
It does not happen unless you use scale and rotate, but I would like to use it because it is easy to implement.

### Steps to Reproduce
[GitHub](https://github.com/aLiz-Nancy/study-pixi-circles)
[Sample Site](https://aliz-study-pixi.web.app/)

### Environment
- **`pixi.js` version**: _e.g. v5.3.3_
- **Browser & Version**: _e.g. Chrome 85.0.4183.83_
- **OS & Version**: _e.g. macOS 10.15.6_
- **Running Example**: _https://aliz-study-pixi.web.app/_

**Comment by ivanpopelyshev** [comment]
Because you change the scale every time that thing goes through edge.

```js
    if (circle.sprite.x < -objectSizeMax || circle.sprite.x > innerWidth + objectSizeMax
      || circle.sprite.y < -objectSizeMax || circle.sprite.y > innerWidth + objectSizeMax) {
      const scale = (Math.random() * (objectSizeMax + 1 - objectSizeMin) + objectSizeMin) / objectSizeMax;
   ... 
    }
```

Its your logic problem, not related to PixiJS.

Oh, right, `innerWidth` instead of `innerHeight` there, look closer :)

**Comment by aLiz-Nancy** [comment]
@ivanpopelyshev 
oh..... :_(
thnak you
