### ISSUE TITLE
TilingSprite is not rendering properly when modifying tileTransform in CanvasRenderer

### ISSUE THREAD

**Issue by JohnEastWork** [pixijs/pixi.js#6862]
### Expected Behavior
In `pixi.js-legacy`, when modifying tileTransform.scale, tileTransform.rotation, tileTransform.pivot, it should render properly as WebGLRenderer, showing tiling scale, rotation, setting pivot properly.
### Current Behavior
When using CanvasRenderer by setting `forceCanvas: true`, load a TilingSprite.
- Modify its tileTransform.rotation, it will not rotate.
- Modify its tileTransform.scale, it will not scale with tiling, leaving empty space.
- Modify its tileTransform.pivot, it will not have effect.
### Steps to Reproduce
Create a TilingSprite, modify scale, rotation and pivot of its tileTransform and observe.
### Environment

- **`pixi.js` version**: pixi.js-legacy@5.2.4
- **Browser & Version**:Chrome 85.0.4183.102, ios12 safari
- **OS & Version**: MacOs Catalina 10.15.6 , ios12
- **Running Example**: none

**Comment by ivanpopelyshev** [comment]
That's how it works in canvas: https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts#L29

We have to use approach from instead: https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts#L358

Who wants to make PR?
