### ISSUE TITLE
[Question] Running multiple versions of PIXI on the same page

### ISSUE THREAD

**Issue by shibekin69** [pixijs/pixi.js#6863]
Hi,

I'm wondering if there's a way to run multiple versions of PIXI just like how someone would run multiple versions of JQuery in a page? Something like running JQuery with noConflict(true):

https://stackoverflow.com/questions/1566595/can-i-use-multiple-versions-of-jquery-on-the-same-page

I know this is not optimal, but I'm looking at trying something out that uses Phaser CE (running on an older version of PIXI) and the new RPG Maker MZ (that uses a newer version of PIXI). Basically, I'm looking to having a Phaser CE canvas on top while the RPG Maker canvas runs on the bottom, or vice versa, then have the underlying JS communicate between them. There are other probably other issues that may pop out, but I'd like to see first if it's possible to run these in the same page without conflict, particularly with the two PIXI versions?

**Comment by shibekin69** [comment]
I suppose I found part of the answer. I was able to rename the customized PIXI references in Phaser CE, at least in this way, there should be no conflict with the main PIXI object from the newer version. Are there other global variables/objects that PIXI uses?

**Comment by ivanpopelyshev** [comment]
Yes, that's the way. No, there are no globals in `PIXI`, it can work even work with `import`s.
