### ISSUE TITLE
Where is the source code of Run Pixie Run?

### ISSUE THREAD

**Issue by a123likeyou** [pixijs/pixi.js#6864]
Where is the source code of Run Pixie Run?

If you want to realize the animation that the wizard clicks, you want to move up, and then falls down without clicking, how can this be achieved?

**Comment by SukantPal** [comment]
Run Pixie Run is a product of GoodBoyDigital. I think you need to contact them directly for support.

**Comment by a123likeyou** [comment]
Ok thanks for your reply
