### ISSUE TITLE
ifram pixijs problem

### ISSUE THREAD

**Issue by dijitaletkinlikler** [pixijs/pixi.js#6865]
Problems when running pixijs in iframe. Windows is problematic on touch screens when using multiple pages.

**Comment by bigtimebuddy** [comment]
Please be specific about what you mean by problems. And please provide an example that reproduces this issue.

**Comment by dijitaletkinlikler** [comment]
Since my English is bad, let me try to explain using translate. I did the activity on the link with pixijs. Everything is very beautiful. Today, when I use it on a windows smart board, when switching between pages, touch is not detected first, then it is detected when touched again. This situation happens only when he is in euphoria. No problem when it's not an iframe.
iframe: https://dersekranda.com/kesirler-ekranda/
no iframe: https://dersekranda.com/veriler/Kesirler/index.html

**Comment by bigtimebuddy** [comment]
I don't believe this is a pixi problem. The iframe needs focus before it will pass through touch events. Try calling focus or setting the activeElement to the iframe first.

**Comment by dijitaletkinlikler** [comment]
Thank you for your answer. Previously I was using another canvas library. There was no problem with iframe with that library. In fact, the problem with pixijs is that it only takes one extra touch to focus on the page. I do not know how to prevent this. is there a sample code?

**Comment by bigtimebuddy** [comment]
This is a very general problem to Google or search on Stackoverlfow, but I think it's something like this.

```
iframe.contentWindow.focus();
```

This is not something that pixi handles or will likely ever handle so I'm closing this issue. Good luck.
