### ISSUE TITLE
Problem with autoplaying video texture in Chrome

### ISSUE THREAD

**Issue by barbudour** [pixijs/pixi.js#6870]
Hi, I have a problem with autoplaying video texture in Chrome (in Safari everything works fine). When the page loads, I get a message in the console:
`Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`

My code:
```javascript
const texture = pixi.Texture.from(require('../../../assets/video/home.mp4'))
      texture.baseTexture.resource.source.loop = true
      const videoSprite = new pixi.Sprite(texture)

      videoSprite.width = app.screen.width
      videoSprite.height = app.screen.height

      container.addChild(videoSprite)
```
Maybe someone faced the same problem?

**Comment by themoonrat** [comment]
It's just as the error describes, really. You cannot autoplay a video in Chrome. The user must have interacted with the page to call play on the video for it to work. No way around this
