### ISSUE TITLE
Documentation for our coordinate spaces

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6872]
There is a lot of confusion b/w our coordinate spaces:

* world space
* local space
* source-frame (=world-space)
* destination-frame space
* viewport space

This all excludes everything in filters. I think we need to document this better somewhere in the API docs.

**Comment by bigtimebuddy** [comment]
This would be a good user guide instead of API does because it is a little more conceptual. cc @irongaze

**Comment by SukantPal** [comment]
@bigtimebuddy I think it is crucial for the API docs to formally define what is what. It is conceptual, but those concepts come from PixiJS itself. No matter how much of an expert the user is, they always would need to understand what is is meant by our self-made terms.

It would be for a guide to do this in-depth. But the API docs still need a, however small, place for these definitions wherever they are introduced/used.

**Comment by ivanpopelyshev** [comment]
We have 4 types of coords here: https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters

**Comment by SukantPal** [comment]
@ivanpopelyshev I’ll make separate PR for filter system.

**Comment by irongaze** [comment]
@SukantPal Where in the API docs would you propose documenting the various coordinate systems?  I'm all in favor of API doc updates where relevant, but it's not clear to me where we would go about educating users.  Most of these coordinate types cut across the API.

@bigtimebuddy Thanks for  the heads up, I'll add this to the list of topics to be covered, though we have the same issue in the guides of where best to discuss the issue.  Not sure it's worth a full guide itself, but definitely should cover local vs global vs screen coords in the guide on the scene graph.

**Comment by SukantPal** [comment]
@irongaze The coordinate systems should be documented where they're used:

* RenderTextureSystem: sourceFrame, destinationFrame, viewportFrame
* ProjectionSystem: sourceFrame (^), destinationFrame (^), projectionMatrix, transform
* DisplayObject: World Space, Local Space, Relativity b/w ancestor frames
* Renderer: World Space, Screen Space (they're different :), but usually they are equivalent if the user specifies the sourceFrame = destinationFrame which is the default if they don't pass them at all)

**Comment by SukantPal** [comment]
And one more:
* FilterSystem: Filter Frame, Texture Coordinates, BaseTexture Space
* ProjectionSystem: Normalized Device Coordinates, Window Coordinates (according to OpenGL convention)
