### ISSUE TITLE
the sprite with shader texture can't be dragged

### ISSUE THREAD

**Issue by ecojust** [pixijs/pixi.js#6881]
like the title says;
the sprite with shader texture can't be dragged,but if it's texture is image it can be dragged.
i'm sure it can't be z-index probolem;
those are my code，waitting for your help，ths!!!

`

    /**
     * 
     * @param position 点位位置(左上角)
     * @param size 点位尺寸
     */
    appendPoint = (position:Array<number>,size:Array<number>)=>{
        let point = new PIXI.Sprite();
        point.filterArea = new PIXI.Rectangle(...position,...size);
        this.app.stage.addChild(point);

        point.dragable = false;
        point.interactive = true;
        let shaderFrag = `
            precision mediump float;
            uniform vec3 iResolution;
            uniform vec2 pos;
            uniform vec2 size;
            uniform float iTime;

            void main() {
                vec2 uv = (vec2(gl_FragCoord.x,iResolution.y - gl_FragCoord.y) - pos.xy)/size.xy;
                vec3 color = vec3(1.0,0.0,0.0);
                float dis = distance(vec2(0.5),uv);
                float light = (sin(iTime) +1.0)/2.0 * 0.4 + 0.1;
                float alpha = smoothstep(1.0,0.0,dis/light);
                gl_FragColor = vec4(color * alpha,alpha);
            }
        `;
        let filter = new PIXI.Filter('', shaderFrag);
        filter.uniforms.iResolution = [window.innerWidth, window.innerHeight, 1.0];
        filter.uniforms.iTime = 1.0;
        filter.uniforms.pos = position;
        filter.uniforms.size = size;

        point.filters = [filter];
        console.log(filter)
        
        this.addDrag(point);
        this.app.ticker.add(function(delta) {
            filter.uniforms.iTime += 0.1;
        });
    }

    /**
     * 
     * @param sprite 精灵元素
     */
    addDrag = (sprite:PIXI.Sprite)=>{
        sprite.buttonMode = true;
        sprite.on("mousedown", (e:MouseEvent)=>{
            sprite.dragable = true;
            console.log('mouseDown');
            var initpos=e.data.getLocalPosition(this.app.stage);
            sprite.offset = {
                x:initpos.x - sprite.x,
                y:initpos.y - sprite.y
            }
        });
        sprite.on("mouseup", (e:MouseEvent)=>{
            sprite.dragable = false;
            console.log('mouseUp')
        });
        sprite.on("mousemove", (e:MouseEvent)=>{
            if(sprite.dragable){
                var pos=e.data.getLocalPosition(this.app.stage);
                sprite.x = pos.x - sprite.offset.x;
                sprite.y = pos.y - sprite.offset.y;
            }
        });
        sprite.on('tap', (e:MouseEvent) => {
            //handle event
            console.log('tap')
         });
    }`

**Comment by ecojust** [comment]
it is hard to show the code style...

**Comment by ivanpopelyshev** [comment]
you use `gl_FragCoord.y` in the shader, switch it to uvs. Unfortunately, to do that, you have to learn how Pixi filters work: https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters

Alternative : use mesh-shader combo. You can make a quad and fill it with shader: https://pixijs.io/examples/#/mesh-and-shaders/triangle-color.js

**Comment by ecojust** [comment]
i found the reason!

`Sprite.prototype.containsPoint = function (point) {
        this.worldTransform.applyInverse(point, tempPoint);
        var width = this._texture.orig.width;
        var height = this._texture.orig.height;
        var x1 = -width * this.anchor.x;
        var y1 = 0;
        if (tempPoint.x >= x1 && tempPoint.x < x1 + width) {
            y1 = -height * this.anchor.y;
            if (tempPoint.y >= y1 && tempPoint.y < y1 + height) {
                return true;
            }
        }
        return false;
    };`


the Sprite's clickTest only read the _texture.orig's size，but the sprite i write doesn't contain texture;
the way to resolve that is add a hitArea by hand，like this:

`
let point = new PIXI.Sprite();
point.filterArea = new PIXI.Rectangle(...position,...size);
point.hitArea = new PIXI.Rectangle(...position,...size);
this.app.stage.addChild(point);`

**Comment by bigtimebuddy** [comment]
Thanks for posting your solution, @ecojust
