### ISSUE TITLE
BLEND_MODE doest work in the released version of IOS14

### ISSUE THREAD

**Issue by tywang2006** [pixijs/pixi.js#6890]
### Expected Behavior
BLEND_MODE should work
### Current Behavior
When blend jpg picture with black background, the black area wont be affected by 
Blending mode.

**`pixi.js` version**: 4.x
**Browser & Version**: Safari
**OS & Version**: ios14

**Comment by eXponenta** [comment]
Looks like as IOS degradation.
Testing in process, not all have a IOS 14 yet.

**Comment by GoodBoyDigital** [comment]
thanks for sharing, installing iOS 14 now..

**Comment by Sulfastic** [comment]
any luck so far?

**Comment by tywang2006** [comment]
i can be closed and it works since 4.8.8

**Comment by ivanpopelyshev** [comment]
It was this commit that fixed things: https://github.com/pixijs/pixi.js/pull/5563

**Comment by Gawlas** [comment]
> It was this commit that fixed things: #5563 

this commit actually doesn't fix the issues, there was one more commit - #5740 - with blend modes definitions from this commit, everything looks to work fine.

**Comment by ivanpopelyshev** [comment]
ok, so need both commits, thank you!

I really dont remember all my changes, I covered them with tests in my work project.

**Comment by bigtimebuddy** [comment]
Seems addressed. Closing.
