### ISSUE TITLE
loader.add(SVG) not working in Firefox

### ISSUE THREAD

**Issue by eiko** [pixijs/pixi.js#6891]
### Expected Behavior

When using the loader to create a sprite from SVG:

```javascript
const loader = PIXI.Loader.shared;

loader.add('svg', './image.svg').load(() => {
  const texture = loader.resources['svg'].texture;
  const sprite = new PIXI.Sprite(texture);
  app.stage.addChild(sprite);
});
```

I expect the SVG to display properly in both Chrome and Firefox

### Current Behavior

The SVG displays in Chrome but nothing displays in Firefox. No error is displayed in the console.

### Steps to Reproduce

This codepen reproduces the bug: https://codepen.io/eikobear/pen/LYNJdRd

### Environment

- **`pixi.js` version**:  5.3.3
- **Browser & Version**: Chrome 85 and Firefox 80
- **OS & Version**: _e.g. MacOS Mojave 10.14.6
- **Running Example**: https://codepen.io/eikobear/pen/LYNJdRd

**Comment by SerG-Y** [comment]
@eiko Firefox doesn't support drawing svg to canvas in case of width/height property is a percentage. Just take a look at [stackoverflow](https://stackoverflow.com/questions/28690643/firefox-error-rendering-an-svg-image-to-html5-canvas-with-drawimage)

As a workaround in your case just remove `%` from the width and height properties in your svg file.

**Comment by eiko** [comment]
Ah, thank you! I'll close this for now and re-open it if that doesn't seem to work

**Comment by eric-burel** [comment]
Hi, the fact that the error is swallowed makes this utterly difficult to debug, it just fails silently and the error is non-obvious. I'll try to provide a PR to Texture.ts file to fix that.

**Comment by eric-burel** [comment]
I've tried to repro the issue on v5 but couldn't, the error event is correctly emitted in Firefox: https://jsfiddle.net/eric__burel/k2zgvx7q/11/

But in Pixi.js v6, the error event is not triggered anymore, and this only in Firefox (since the percentage SVG width/height is accepted by other browser). I haven't figured how to do a clean repro with v6 however.
