### ISSUE TITLE
PIXI Text sometimes fails to render on certain Android devices if the Text's internal canvas dimensions change

### ISSUE THREAD

**Issue by smlmyck** [pixijs/pixi.js#6898]
We've been experiencing an issue since November 2019 where players on Android devices were seeing major issues with text - specifically, seeing PIXI Text objects showing with an incorrect style, completely blank, or with text values that we didn't set on that specific Text object.

 We've had reports of this issue on multiple Android devices, including:

- Honor 7S
- Huawei P8
- Huawei P9 Lite
- Huawei Y6 2019
- Samsung Galaxy S5
- Samsung Galaxy S10
- TCL 5033X

From what we've been able to ascertain, these players were running the latest available versions on Android and running up-to-date Chrome from Google Play, running on a WebGL renderer.

I've spent a lot of time in the last year trying to reproduce the issue on the devices our players report, but I've never seen the issue manifest. This week however I've been able to gain access to a Huawei Y6 2019, running latest Android version the phone supports and latest Chrome, where the issue manifests consistently.

From what I can tell, the `canvas` property of the Text object contains the correctly rendered text. Appending it to the document shows the correct value rendering at all times, but the rendered text isn't necessarily valid.

I have been able to mitigate the missing or incorrectly rendered text in many of our titles by setting `dirty = true` on the text object in a `setTimeout` of 1ms. Forcing the text update like this seems to fix most cases of invalid text on this device, but I'm seeing some text remain missing or incorrect on some games with a lot of text, so I've investigated further and have managed to come up with a simple repro case and some observations.

[This playground link](https://www.pixiplayground.com/#/edit/KFUhnd_UOBh9bP1xzpN6X) creates 120 PIXI Text field objects, and when you press the stage it increments the value of all of them by 1. Beneath the PIXI Application's canvas I render all of the internal canvas objects from the Text fields. The number of text fields is a purely arbitrary amount, we render much less text (albeit random and different non-sequential numbers - this sequential increase is simply the easiest way to show the issue).

On the Huawei Y6 2019 I have here, when the digits roll over from 9 to 10, or 99 to 100, only every 16th text box is rendered. On PIXI v4 latest, usually only the first text box is rendered (but I've seen say the first and ninth render). Our games are still running on v3, but the text renders as v4 - only the first text renders when changing from 9 to 10.

<img src="https://user-images.githubusercontent.com/32482581/93760145-5f2b5c00-fc03-11ea-83ec-ea6acb93a283.png" width="30%" height="30%" /> <img src="https://user-images.githubusercontent.com/32482581/93760163-65213d00-fc03-11ea-8d52-68cebc4e2039.png" width="30%" height="30%" /> <img src="https://user-images.githubusercontent.com/32482581/93760169-66eb0080-fc03-11ea-9ad1-bd177c4736de.png" width="30%" height="30%" />

If I change the playground to instead create only two PIXI Text objects, it's still only the first that renders. On PIXI 5, if I change the start text value to 8 or 9, upon reaching 10, only the first text field renders - starting at 7 or below will render every 16th again.

If I modify PIXI Text's `updateText` function to _not_ change the width and height of the canvas to the expected size (i.e. [set these properties to static values](https://github.com/pixijs/pixi.js/blob/4a3911d/packages/text/src/Text.ts#L192-L193)) instead of the accurate values it currently determines), **the text renders fine at all times**. This isn't particularly sustainable though, as we'd have to figure out appropriate widths, and it breaks `anchor`ing.

I'm unable to use a bitmap font as it's not covered by our font license (although I could probably use the new dynamically generated bitmap fonts from v5, but we'd need to update our stack _to_ v5 and I'm not necessarily able to do that at this time).

This issue also seems to only manifest on WebGL on these devices. If I force a canvas renderer, the text always renders correctly - this is likely to be our workaround if no solution can be found to ensure text renders accurately. I don't understand enough of the PIXI internals to understand why text renders fail (sometimes) if the internal canvas dimension change, hence the issue.

### Expected Behavior
When the `text` property is set on a PIXI Text object, the rendered text matches with the correct style.

### Current Behavior
On certain devices, when the `text` property is set on a PIXI Text object, text is rendered incorrectly (being either missing, not the value we set or not the style we set).

### Environment

- **`pixi.js` version**: 3.0.11, 4.8.9, 5.3.3
- **Browser & Version**: Recent Chrome Versions, Chrome 85.0.4183.101, for example
- **OS & Version**: Android 9 on Huawei Y6 2019, for example
- **Running Example**: https://www.pixiplayground.com/#/edit/KFUhnd_UOBh9bP1xzpN6X

**Comment by ivanpopelyshev** [comment]
I dont see anything at https://bugs.chromium.org/p/chromium/issues/list?sort=-modified&q=webgl%20mobile&can=1 , so its either something pixi-related, either not reported chromium bug

**Comment by ivanpopelyshev** [comment]
Not confirmed on:
Android 9; SM-T515 Build/PPR1.180610.011
