### ISSUE TITLE
BitmapText width after text change

### ISSUE THREAD

**Issue by Vardner** [pixijs/pixi.js#6900]
### Current Behavior
Create a PIXI.BitmapText instance with this text "1111111111111111111111111". Remember its width, then change the text to "1" and check the width again, it will be the same.
### Possible Solution
This problem exists when PIXI.BitmapText instance has PIXI.Mesh instance as children with more than 199 vertices 
### Steps to Reproduce
https://pixijs.io/examples/#/text/bitmap-text.js
Paste this code:
```
const app = new PIXI.Application({ backgroundColor: 0x1099bb });
document.body.appendChild(app.view);

app.loader
    .add('desyrel', 'examples/assets/bitmap-font/desyrel.xml')
    .load(onAssetsLoaded);

function onAssetsLoaded() {
    const bitmapFontText = new PIXI.BitmapText('11111111111111111111111111111111111111111111111', { font: '55px Desyrel'});
	console.log(bitmapFontText.width);
    bitmapFontText.x = 50;
    bitmapFontText.y = 200;
	bitmapFontText.text = '1';
	console.log(bitmapFontText.width);
    app.stage.addChild(bitmapFontText);
}
```
### Environment

- **`pixi.js` version**: 5.3.2
- **Browser & Version**: Chrome 85
- **OS & Version**: Windows 10

**Comment by bigtimebuddy** [comment]
Here's a JSFiddle version:
https://jsfiddle.net/bigtimebuddy/syt6gdpb/

**Comment by Vardner** [comment]
> Here's a JSFiddle version:
> https://jsfiddle.net/bigtimebuddy/syt6gdpb/

As I understand, this problem arises because we don't clean vertices buffer when new text smaller than previous.
Check how this condition works
![image](https://user-images.githubusercontent.com/36897869/93906490-ec0a0e80-fd04-11ea-8474-4e1e8a959754.png)
