### ISSUE TITLE
[feature required]python interface needed! great job!

### ISSUE THREAD

**Issue by loveJasmine** [pixijs/pixi.js#6901]
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
https://github.com/jtpio/pixijs-jupyter

**Comment by SukantPal** [comment]
@loveJasmine I don't think the core team has time to setup a Python interface for PixiJS. Thanks for asking, though. You're welcome to start one on your own, and maybe @bigtimebuddy can make it official if you can make significant progress.
