### ISSUE TITLE
How can we create circles with dashed strokes?

### ISSUE THREAD

**Issue by dhirusarania** [pixijs/pixi.js#6904]
![image](https://user-images.githubusercontent.com/33983632/94072316-0fbb7a80-fe13-11ea-95f4-c5aeb97eed2b.png)

I want to achieve those dashed strokes around circles and rectangles. The above is from Two.js.
Currently I can get solid strokes using circle.lineStyle(10, 0xFF00FF).
How can I get dashed strokes

**Comment by bigtimebuddy** [comment]
Related to #6569 and #1333. Pixi doesn't currently have support for dashed strokes.

**Comment by dhirusarania** [comment]
Any way to implement it?

**Comment by bigtimebuddy** [comment]
In the older post there are some examples. Basically, the approach is to manually draw the line segments (or in the case of circle lots of small arcs). You could try one of those, but you're probably on your own for this one, sorry. If someone comes up with a general approach to this, would be a great plugin!

**Comment by SukantPal** [comment]
See for an example with straight lines: https://github.com/pixijs/pixi.js/issues/1333#issuecomment-424324927
