### ISSUE TITLE
[BUG] Mesh constructor should not change any property of the passed in MeshMaterial/State

### ISSUE THREAD

**Issue by teoxoy** [pixijs/pixi.js#6907]
### Expected Behavior
The `Mesh` constructor should not change any property of the passed in `MeshMaterial`/`State`.

### Current Behavior
The `Mesh` constructor resets the tint value of the passed in `MeshMaterial` and also the blend mode of the passed in `State` which should not be the case.

### Possible Solution
Remove:
https://github.com/pixijs/pixi.js/blob/a4c1e3d58159138f99e2714c476360932ebf0152/packages/mesh/src/Mesh.ts#L148-L149

**Comment by ivanpopelyshev** [comment]
That's interesting

**Comment by teoxoy** [comment]
I was so confused why the tint was not being applied 😅
