### ISSUE TITLE
[docs] numeric constants signs are not displayed

### ISSUE THREAD

**Issue by louisabraham** [pixijs/pixi.js#6912]
https://pixijs.download/dev/docs/PIXI.html#UPDATE_PRIORITY

**Comment by bigtimebuddy** [comment]
Can you clarify? I'm not sure what you mean.

**Comment by louisabraham** [comment]
![image](https://user-images.githubusercontent.com/13174805/94377342-02f39b00-0121-11eb-9ef2-a49380d5ec62.png)
actual values are -25 for low and -50 for utility

**Comment by bigtimebuddy** [comment]
Oh, got it! Thanks for pointing this out.

**Comment by bigtimebuddy** [comment]
@SukantPal docs look correct. Is this a webdoc bug?

**Comment by SukantPal** [comment]
Yeah, I guess.

**Comment by SukantPal** [comment]
You can add quotes around as a quick fix, and probably need to transfer this issue to webdoc-js/webdoc.

**Comment by SukantPal** [comment]
This was fixed in https://github.com/webdoc-js/webdoc/pull/48!
