### ISSUE TITLE
PIXI.LoaderResource doc links outdated

### ISSUE THREAD

**Issue by xinexix** [pixijs/pixi.js#6918]
I know this is small.  Forgive me if this should be a simple pull request instead of an issue.

In the latest Pixi documentation for [LoaderResource](https://pixijs.download/dev/docs/PIXI.LoaderResource.html), there are two links that lead to 404 pages.

The "Reference to" link should be https://github.com/englercj/resource-loader instead of ~~https://github.com/englercj/resource-loaderresource-loader~~.

The "See" link should now be http://englercj.github.io/resource-loader/classes/resource.html instead of ~~http://englercj.github.io/resource-loader/Resource.html~~ (moved to 'classes' subdirectory; also apparently it is case-sensitive).

**Comment by bigtimebuddy** [comment]
Thanks for letting us know. PR welcome to fix this!
