### ISSUE TITLE
Lines are skewed, have sharp edges & disappear

### ISSUE THREAD

**Issue by TimHaerkens** [pixijs/pixi.js#6920]
**UPDATE: FOUND THE PROBLEM. I just fixed one line by removing the 50th point.**
So that means lines of more than 49 points bug out. I'm not sure if this is a consistent problem with Pixi since I am using a library to use Pixi with Leaflet.

I'm using Leaflet PixiOverlay to display a Pixi canvas on top of a Leaflet map (https://github.com/manubb/Leaflet.PixiOverlay)
Pixi's behaviour is mostly the same as I use the documentation a lot.

### Expected Behavior
Lines displaying as straight lines.

### Current Behavior
Some lines display like straight lines but many other display as morphed polygon-like shapes like the corners of the line are swapped, which make them have a cut-off, have sharp edges, or totally disappear.

**Screenshot:**
https://imgur.com/a/UNDZp9V
In the first screenshot I marked the badly behaving lines and the rest is how I would like them to behave.
In the second screenshot I lot of lines are morphed and a few lines are correct at the right middle and the left lower corner.
Also when I move the canvas (while dragging the map), the wrong lines movement is a bit off. i.e. the correct lines move accordingly with the canvas but the wrong lines have a random offset every time I move the canvas a bit

**Animated GIF:**
https://gyazo.com/262bfddf5ccc9db4d8ca90dba4400b37
Here you can see if I move the canvas, the wrong lines move with a seemingly random offset and the correct lines move accordingly with the canvas.

### Possible Solution
I'm not sure but I would like to know what makes the difference between a skewed line and a correctly behaving line.
I would gladly appreciate any input.

### Steps to Reproduce
I use a library (Leaflet PixiOverlay) to display a Pixi container on top of a leaflet map. I've been using Pixi Sprites for map markers for a long time without any problem. But Pixi lines have had problem since the beginning. I add them to the container with this code:

```javascript 
let invScale = 1 / pixiLayer.utils.getScale();
let scaleMultiplier = Math.max(0.4, Math.min((0.4 + ((utils.getMap().getZoom() - 12) / 8)), 1.5));

let markerLine = new PIXI.Graphics(); 
markerLine.lineStyle(1 * invScale * scaleMultiplier, 0x3388ff, 1);
info.position.coordinates.forEach(function(point,index){
      point = utils.latLngToLayerPoint([point[0], point[1]]);
      if(index === 0)markerLine.moveTo(point.x, point.y);
      else markerLine.lineTo(point.x,point.y);
});
```
EDIT: I limited all the lines to max 50 coordinates and it seems to appear much less now. I tried to find a bunch of lines that were still reacting strange and all of them were maxed out to 50 coordinates. One of these lines I plotted as a simple line in leaflet (without Pixi) and it shows just a simple line with a bend at the end but in Pixi it is morphed:
https://codepen.io/timhaerkens/pen/jOrOyzO

The data is external so I'm not sure if I can decrease the amount of points without losing reliability.
Possibly the points of the line are too close to each other and Pixi doesn't know what to do with it?

### Environment

- **`pixi.js` version**:  5.3.3
- **Browser & Version**: Chrome 84.0.4147.135
- **OS & Version**:  Windows Microsoft 10 Pro v1909
- **Running Example**: n/a

**Comment by joshuahhh** [comment]
Hi @TimHaerkens! I'm a Pixi newb, but I have an interest in problems similar to yours.

A thought for debugging – Could you draw circles around every (point.x, point.y), so we can see where the lines are supposed to be?

Another thought: What happens when you zoom in and out? Do the shapes change? A GIF of this might be helpful.

**Comment by TimHaerkens** [comment]
Hi @joshuahhh Thanks for your comment.
I forget that zooming had a thing of it's own. I rewrite the line with an updated position on the map but the random or "off" behavior changes. The funny thing is that a lot of different lines that look OK behave perfectly normal when redrawing them.

GIF: https://gyazo.com/593767475edc6661db54e84865383d04

```javacript
//This is in the PIXI Overlay function
zoom = map.getZoom();
                        if (prevZoom !== zoom) {

                            invScale = 1 / utils.getScale();
                           
                            scaleMultiplier = Math.max(0.4, Math.min((0.4 + ((zoom - 12) / 8)), 1.5));

                            rerenderSprites(zoom);
                        }
```
```javacript
//This is the function that I call on a zoom change
rerenderSprites = function(zoom){
markerLines.forEach(function(markerLine) {
        markerLine.clear();

        markerLine.lineStyle(invScale * scaleMultiplier , 0x3388ff, 1);
        markerLine.info.position.coordinates.forEach(function(point,index){
            if(index === 0)markerLine.moveTo(point.x, point.y);
            else markerLine.lineTo(point.x,point.y);
        });

    });
}
```

**Comment by TimHaerkens** [comment]
FOUND THE PROBLEM. **I just fixed one line by removing the 50th point**. There were two identical lines on top of each other.
First I thought it rendered the line right and had the morphed version on top of it but it happened to be two identical lines and by some miracle, one of the lines had exactly 49 coordinates and I capped the other line to max 50. There was one coordinate extra in the morphed one and when I removed it it displayed correctly.

**Comment by ivanpopelyshev** [comment]
I dont know why i didnt comment on it. Yeah, usually its the same points.

**Comment by TimHaerkens** [comment]
I made a fix using this piece of code to simplify the line using a tolerance/threshold:
http://bl.ocks.org/helderdarocha/raw/47fff819307ef8488607007ebb4f8b92/

It removes points that are close together. It also improves the performance because less lines are rendered.
