### ISSUE TITLE
Contributing: Unclear how to run a single test

### ISSUE THREAD

**Issue by joshuahhh** [pixijs/pixi.js#6925]
Hello! I'm working on a contribution to Pixi, and am writing a test to make sure it works. I see on the [contributing guidelines](https://github.com/pixijs/pixi.js/blob/dev/.github/CONTRIBUTING.md) that `npm test` will build and test the entire project. But this is quite slow (48 seconds), and it is difficult to work on my test this way. Is there some way to run a single test, or the tests for a single package (like `graphics`)? Thanks!

(Sorry if this is the wrong venue to ask a question like this. But the contributing guidelines don't list a way for contributors to get help on things like this. Maybe I should submit that as a second issue. 😄)

**Comment by bigtimebuddy** [comment]
The best way to do this is to add `.only` to a `describe` or `it` call. This Mocha convention will ignore other tests and is the best way to run single tests. Hope that helps.

**Comment by joshuahhh** [comment]
@bigtimebuddy: This still means that the entire project is rebuilt though, right? That's most of the cost – a big non-incremental build.

**Comment by bigtimebuddy** [comment]
Try using `npm run unit-test` instead of `test`. Another pro tip is to do `npm run unit-test -- --debug` to open dev tools for doing debugger and console logging.

**Comment by joshuahhh** [comment]
That's very helpful; thanks! I now know how to iterate quickly writing tests.

(I thought that `test` and `unit-test` were identical. I didn't realize that `test` runs `pretest` first!)

So I think the ideal testing workflow for me is:
1. Run `npm run start` in one terminal, to get incremental compilation going.
2. When desired, run `npm run unit-test` in another terminal to quickly run the tests.

Let me know if I'm missing something; otherwise, I'll put that into the docs. Thanks again.
