### ISSUE TITLE
Bug/issue with text rendering on iOS Safari?

### ISSUE THREAD

**Issue by nicokruger** [pixijs/pixi.js#6932]
I think I've come across a bug in text rendering on iOS Safari. 

When the text to render is quite long, pixi / Safari (not sure where the bug lies) renders a black rectangle for certain font sizes. The whole text "box" is completely black.

### Expected Behavior
This works fine on Chrome and Firefox. All combinations of font size / text length render correctly on Chrome and Firefox.

### Current Behavior
Once the text reaches a certain length, you get black rectangles rendered for font sizes higher than some value. I'm not quite sure what the relationship is between text length / font size that causes the black rectangle to appear. Could it perhaps be memory related?

### Possible Solution
One possible solution would be to try and reduce the font size, and then scale the container up to try and match the desired size required. This will have a negative impact on the text quality though.

### Steps to Reproduce
I've created a Pixi playground test:

https://www.pixiplayground.com/#/edit/ZsVBsFY2PQLj6_P0yN6_e

When viewing on Chrome, all the text is rendered correctly. On iOS Safari though, only the top and the last bunch of text is rendered correctly, the rest are simply black rectangles.

### Environment

- **`pixi.js` version**:  Latest release as per pixiplayground.com
- **Browser & Version**:  Safari
- **OS & Version**: iPhone iOS 13.6,
- **Running Example**:  https://www.pixiplayground.com/#/edit/ZsVBsFY2PQLj6_P0yN6_e

**Comment by nicokruger** [comment]
Correction, this is on iOS 3.6 - iPhone 8 +

**Comment by nicokruger** [comment]
By the way, I just updated the Phone to 14.0.1, and this issues seems to be fixed. For now, I am keeping the workaround in place for older versions of ios but this problem should go away soon for most users as they update.

**Comment by SukantPal** [comment]
The texture should be smaller than the max. texture dimensions. If you use a very large font size, the texture might fail to upload to the GPU and it will be black.
