### ISSUE TITLE
TilingSpriteRenderer buggy shader

### ISSUE THREAD

**Issue by JohnEastWork** [pixijs/pixi.js#6933]
### Expected Behavior
TilingSpriteRenderer using WEBGL should render normally.

### Current Behavior
TilingSpriteRenderer is not working properly on some mobile device. For example，"BBK H8A", whose Chinese name is "步步高H8"。
Here is the code:
https://www.pixiplayground.com/#/edit/80xRLERqs4Za6uyUthYRF

It displays properly on most device using webgl renderer.
But on the device mentioned above, it displays like the picture:
![image](https://user-images.githubusercontent.com/67133086/95652565-9dda7500-0b24-11eb-90e1-f60ca7844ac5.png)

The first TilingSprite using "https://pixijs.io/examples/examples/assets/bunny.png" as texture become invisible.
But it actually takes the first pixel to render full sprite. If you use an image starts with "blue pixel", it will be all blue.

### Possible Solution
After testing, we found v5.1.6 is working normally, and v5.2.0 shows the bug.
So we use `git bisect` to locate the buggy commit.
It turns out [commit 3680d900c0ba8e05ec836a9cff21d25686714e5c](https://github.com/pixijs/pixi.js/commit/3680d900c0ba8e05ec836a9cff21d25686714e5c) is the problem.

We tried to restore and it works!

But we are not sure it is suitable to do that. Shader is beyond our knowledge.

### Steps to Reproduce
Open the [playground case](https://www.pixiplayground.com/#/edit/80xRLERqs4Za6uyUthYRF
) with buggy device.
Not sure what device may cause it, but the buggy device is using GPU called "Powervr rogue ge8300".
Devices using GPU "Adreno" series works fine.
Iphone works fine.

We use different chrome version and different android version, but they seems have nothing to do with it.
And the code is Shader, so we assume it relevant to GPU.

### Environment

- **`pixi.js` version**: 5.2.4, 5.2.0
- **Browser & Version**: Chrome 80.0.3987.87, Chrome 51  (same device mentioned above).
- **OS & Version**: Android 7.0
- **Running Example**: https://www.pixiplayground.com/#/edit/80xRLERqs4Za6uyUthYRF

**Comment by ivanpopelyshev** [comment]
I can roll it back, no problem.. 

just.. how the heck its not the same? Its like uClampOffset has wrong value

Can you tell me which mobile chipset is it?

**Comment by ivanpopelyshev** [comment]
Can you try changing "floor" to "-ceil(-x)" ? The only idea i have is that `floor` function is wrong there

**Comment by JohnEastWork** [comment]
> Can you try change `floor(x)` to `-ceil(-x)` ? The only idea i have is that `floor` function is wrong there

Yup. I may be able to try that tomorrow. I dont have the device by my hand right now.

**Comment by JohnEastWork** [comment]
@ivanpopelyshev  
I tried ur modification, like this:
```
vec2 coord = vTextureCoord + ceil(uClampOffset - vTextureCoord);
```
It works!
![image](https://user-images.githubusercontent.com/67133086/96114545-52570b00-0f18-11eb-9410-2d7b003c13ac.png)

**Comment by bigtimebuddy** [comment]
Someone want to put in a fix for this?

**Comment by ivanpopelyshev** [comment]
Btw, it might be chrome bug. Can you try install any firefox there?

We might report this to chromium team if it does work in firefox

**Comment by JohnEastWork** [comment]
> Btw, it might be chrome bug. Can you try install any firefox there?
> 
> We might report this to chromium team if `floor` is fine in firefox.

I checked Firefox. Same behavior occurs on firefox.
Using `floor` gets error render.
Using `ceil` gets correct render.
