### ISSUE TITLE
roundPixels property is not working on multiline texts that allign to center.

### ISSUE THREAD

**Issue by shaise** [pixijs/pixi.js#6934]
BUG:
when working with bitmap text that is aligned to center and is also multy-line , the roundPixel property does not work properly and the text can become blurry.

SOLUTION:
Simple solution: in BitmapText.ts, line 355:
  ` alignOffset = (maxLineWidth - lineWidths[i]) / 2; `
allignOffset should take into account the roundPixel property and if so, floor the value. (I added a floor and it fixed the text)

Thank you for a Great, Great piece of software!!!!

shai

- **`pixi.js` version**: _e.g. 5.3.3
- **Browser & Version**:  all

**Comment by hjpvue** [comment]
I want to frontline this on a couple of projects. But yeah I know everyone has my logs. It's better that way probably. Still mean though. But then again google filament wouldn't be possible without inter-industry co-operation.

**Comment by bigtimebuddy** [comment]
@shaise thanks for reporting this. Could you provide a simple example that demonstrates this issue? Would be helpful to verify when this is fixed.

**Comment by shaise** [comment]
Hi attache a simple example demonstrating the bug. The first line looks ok, the second is smudged.
[TestRoundPixel.zip](https://github.com/pixijs/pixi.js/files/5360247/TestRoundPixel.zip)

**Comment by shaise** [comment]
I have a fix for this issue + added a 'justify' option to align property of bitmap texts. If there is any interest, I can issue a PR.
align: 'justify' example: (there is a \n after the 'fox' in the middle)
![justify](https://user-images.githubusercontent.com/5813568/96787026-c2beca00-13f9-11eb-8551-8a6e2ef201f4.png)

**Comment by bigtimebuddy** [comment]
Great feature suggestion! PR welcome.

**Comment by shaise** [comment]
Done.
BTW, how do i generate the pixi.min.js? 'npm run build' or 'npm start' generate only pixi.js, and pixi.mjs - which is almost the same size as pixi.js.

**Comment by bigtimebuddy** [comment]
Good one @shaise, will review the PR.

**Comment by shaise** [comment]
Hi. PR changed to include fix only
