### ISSUE TITLE
Mask performance on mobile devices with pixi5

### ISSUE THREAD

**Issue by selirion04** [pixijs/pixi.js#6938]
Hi!

Something happened with masks performance in pixi5, especially on Samsung devices .
When I switched to Pixi5 I found that fps dropped to 5-10 in my app on Samsung A5, S6 and to 20-40 fps on Samsung M31. It recovers when I disable all masks. I use them to hide scrollers content, for some animations and to round corners in some cases (maybe totally 10-15 masks on screen). But it shows 60 fps on much worse devices than this A5.

Two codepens here to see difference. Just tap to add masked bunnies and watch on rotating bunny to detect fps drop (recommend set scale to 0.5 and hide html).
https://codepen.io/Insi04/pen/MWeapRb
https://codepen.io/Insi04/pen/oNLjZPq
Also no mask example to make sure that mask is the key: https://codepen.io/Insi04/pen/abZvEmm

E.g. on Samsung A5 (2017) you can spawn 100+ masked bunnies at v4 with no drops, and just nearly 50 on v5. 
On Samsung S6 it's 100+ vs 25 bunnies.
Other devices also has difference: Asus Zenfone 2 has 400 vs 100 bunnies, iPhone 8 Plus easily spawns 1500 on v4 and nearly 600 on v5 (but I don't see lags in my app, so maybe it's some reserve).

We commonly connect that with GPU ARM Mali which used in Samsung Exynos (heard that they has some features about z-index rendering and Unity has [special guide](https://static.docs.arm.com/100140/0302/arm_guide_for_unity_developers_optimizing_mobile_gaming_graphics_100140_0302_00_en.pdf) for optimisation) but then see the difference on all other devices I've check (Asus Zenfone, iPhone 8+ and so on), so looks like masks was last straw in performance for Mali :)

UPD: I've checked my main app on few more Mali GPUs and all of them has fps dropped to 5-25 just with pixi5  :( 
Huawei Ascend Mate 7, Huawei P40 Lite E, Samsung M31. On Apple devices and android with Snapdragon (Samsung A51) has no changes in performance.

- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Chrome 86.0.4240.75
- **OS & Version**: Android

**Comment by selirion04** [comment]
Cache as bitmap may be workaround just for examples but I think that cache my scroller content each time it scrolled or content changed is unacceptable. And it also destroy batching.

**Comment by selirion04** [comment]
Any ideas except to revert back to 4.x ? :(

**Comment by PByH** [comment]
Also faced with the same problem on my Samsung device(

**Comment by ivanpopelyshev** [comment]
For those who want to solve it and not wait for pixijs team: use SpectorJS, compare frames of those two demos and see where's the big difference in webgl commands. Yes, in v5 we use same shader for graphics and sprites, but how is is applicable here?

**Comment by selirion04** [comment]
Also same lags on my home PC. Try to force WebGL1 - nothing changed.

In SpectorJS on 50 bunnies:
Total commands count is 313 vs 1135
Twice more primitives (324 vs 630)

But i'm really new with shaders so nothing in command stack for me :)

**Comment by ivanpopelyshev** [comment]
Oh, right, its using scissor in v4 and we removed it in early-v5 , then added it back, but its not enabled by default in 5.3.3. It will be enabled in 5.4

Here's the flag:

```js
renderer.mask.enableScissor = true;
```

and people failed to answer 3 weeks? seems that whole team is busy this month

**Comment by selirion04** [comment]
> ```js
> renderer.mask.enableScissor = true;
> ```

Thanks a lot! Seems MUCH better (470 commands) in test and moderately better in app.

The only differences in:
v4
bindBuffer: 52
bufferSubData: 51
bindFramebuffer: 1
bufferData: 1

v5
bindBuffer: 104
bufferSubData: 104
uniformMatrix3fv: 53
flush: 1

Twice more binds and subdata are coming from Geometry. Not sure that two buffers are neccessary because first always has empty subdata.
