### ISSUE TITLE
BitmapFont.from() not working on older browsers, e.g. opera 29

### ISSUE THREAD

**Issue by relefant** [pixijs/pixi.js#6939]
### Expected Behavior

`BitmapFont.from()` works

### Current Behavior

`BitmapFont.from()` throws an exception:
"Failed to execute 'setTransform' on 'CanvasRenderingContext2D': 6 arguments required, but only 0 present."

### Possible Solution

See:
https://github.com/pixijs/pixi.js/blob/c097ffa403c10684f6b8a4b1baa486f64b229ddb/packages/text-bitmap/src/utils/drawGlyph.ts#L87

The bug because PIXI calls `context.setTransform()` to reset the transform, but this is not valid in the older API.
I think this should be `context.setTransform(1, 0, 0, 1, 0, 0)`

### Steps to Reproduce

Call `BitmapFont.from()` on a browser which does not support the newer `CanvasRenderingContext2D.setTransform` API.

### Environment

- **`pixi.js` version**: 5.3.2
- **Browser & Version**: Opera 29
- **OS & Version**: MacOS 10.15.6

**Comment by bigtimebuddy** [comment]
Thanks for looking into this. Fix seems pretty easy if someone wants to make it. PR welcome.
