### ISSUE TITLE
Text render in wrong size when width out of range in WebGL

### ISSUE THREAD

**Issue by fffyyyyy** [pixijs/pixi.js#6940]
### Expected Behavior
Text render in right size when width out of range, like rendering in CanvasRenderer

### Current Behavior
https://www.pixiplayground.com/#/edit/kYtwwd-w5AZ9qfYKAVDv4
You can see the wrong size at stage, the right size at dom.

When you use v4.8.x and use forceCanvas, you can get the right size in stage.
When you change code `pixi_text.text.length >= 513` into `pixi_text.text.length >= 512`, you can get the right size in stage.

### Possible Solution
When I get the wrong size, I can get the warning in BaseImageResource
![image](https://user-images.githubusercontent.com/49550325/96085020-bb2b8c80-0ef2-11eb-96bd-310ba707af90.png)
 I guess something wrong in Text render or Texture render

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/kYtwwd-w5AZ9qfYKAVDv4
Open this playground, you can see the text render at stage

### Environment

- **`pixi.js` version**: v4.8.x, v5.2.x, v5.3.x
- **Browser & Version**: All Browser
- **OS & Version**: All OS
- **Running Example**: https://www.pixiplayground.com/#/edit/kYtwwd-w5AZ9qfYKAVDv4

**Comment by themoonrat** [comment]
PIXI.Text takes the text you want to draw, creates a canvas large enough to contain it, draws it, then saves that canvas to be a texture as a Sprite
WebGL has a limit to how large textures can be, so the error you're seeing is to be expected when super large text. 

If you require this amount of text all in a row, then use BitmapText instead, as that draws each character at a time

**Comment by SukantPal** [comment]
Please close this issue if it's resolved @fffyyyyy.

**Comment by fffyyyyy** [comment]
> Please close this issue if it's resolved @fffyyyyy.

ok~
