### ISSUE TITLE
Typescript declaration of the function doesn't match the JS implementation.

### ISSUE THREAD

**Issue by VladGan** [pixijs/pixi.js#6941]
### Expected Behavior

JS implementation of `Graphics.prototype.lineStyle` accepts both single object argument - `options`, as well as the list of arguments - `width`,` color`, `alpha`, `alignment`, `native`.

```
Graphics.prototype.lineStyle = function lineStyle (options)
    {
        // Support non-object params: (width, color, alpha, alignment, native)
        if (typeof options === 'number')
        {
            var args = arguments;

            options = {
                width: args[0] || 0,
                color: args[1] || 0x0,
                alpha: args[2] !== undefined ? args[2] : 1,
                alignment: args[3] !== undefined ? args[3] : 0.5,
                native: !!args[4],
            };
        }

        return this.lineTextureStyle(options);
    };
```

### Current Behavior
`pixi.js.d.ts` file contains 2 declarations of `lineStyle` and they are both the same:

![Screenshot 2020-10-15 at 11 44 33](https://user-images.githubusercontent.com/6169272/96113243-cfb05a80-0edb-11eb-93e1-d16bf1495290.png)

So it doesn't support the `options` as an input.

### Possible Solution

Update the type of arguments of the second declaration of `lineStyle` to support `options`.

**Comment by bigtimebuddy** [comment]
We have replaced our tooling for generating types and this is no longer an issue. Will be fixed in 5.4.0.
