### ISSUE TITLE
super.destroy() called twice when destroying Graphics

### ISSUE THREAD

**Issue by relefant** [pixijs/pixi.js#6942]
super.destroy() called twice when destroying Graphics

https://github.com/pixijs/pixi.js/blob/19d7cba1897abe1a0087b13a5c3a54c0c079c250/packages/graphics/src/Graphics.ts#L1367

```
    public destroy(options: IDestroyOptions|boolean): void
    {
        super.destroy(options);
        this._geometry.refCount--;
        if (this._geometry.refCount === 0)
        {
            this._geometry.dispose();
        }

        this._matrix = null;
        this.currentPath = null;
        this._lineStyle.destroy();
        this._lineStyle = null;
        this._fillStyle.destroy();
        this._fillStyle = null;
        this._geometry = null;
        this.shader = null;
        this.vertexData = null;
        this.batches.length = 0;
        this.batches = null;

        super.destroy(options);
    }
```

### Expected Behavior

`super.destroy()` called only once.

### Current Behavior

`super.destroy()` called twice.

### Possible Solution

Call `super.destroy()` only at start of `destroy()`

### Environment

- **`pixi.js` version**: 5.3.2
- **Browser & Version**: Opera 29
- **OS & Version**: MacOS 10.15.6

**Comment by bigtimebuddy** [comment]
Good one! That's a mistake we should remove the first destroy. Welcome fix for this.
