### ISSUE TITLE
Cannot set property '_parentID' of undefined 

### ISSUE THREAD

**Issue by riverfeya** [pixijs/pixi.js#6948]
when i try to make a rectangle i get this error in the Container.prototype.addChild 
child.transform._parentID = -1;

:(

**Comment by bigtimebuddy** [comment]
Can you please provide a reproduction? Need more info.

Are you trying to pass `new Rectangle` to `addChild`?

**Comment by riverfeya** [comment]
Hi, im very sory it was my fault, delete this isue please

пт, 16 окт. 2020 г. в 00:55, Matt Karl <notifications@github.com>:

**Comment by bigtimebuddy** [comment]
No worries. We've all ben there @riverfeya. Good luck with your project.
