### ISSUE TITLE
Access texture rendered from cacheAsBitmap

### ISSUE THREAD

**Issue by apinder** [pixijs/pixi.js#6951]
One thing I would really like but by no means is essential is the ability to access the texture rendered once you've set `cacheAsBitmap=true` (and renderCached is called) and be able to use this texture like any other - in other sprites/tilingSprites etc.

My use case is that I have filters that I want applied to a TilingSprite, applying these filters to a large tiling texture causes performance degradation so I would prefer if this was cached. Unfortunately this is not possible as the TilingSprites when cached produce a texture that exceeds the max texture size for most WebGL contexts.

Instead I want to apply the filters to the texture used for a single tile, cache it using cacheAsBitmap, then use the cached texture that is rendered to then be used in a TilingSprite. This TilingSprite avoids the previous problems as it no longer is using renderAdvanced for the filters and does not cause any issues around texture sizes.

I say it's not essential because I can apply the filter effects (them being static) at compile time and add them to the sprite sheet but for me this happens with a lot of textures so it's not ideal.

Thanks for any help.

**Comment by bigtimebuddy** [comment]
The convenience function cacheAsBitmap has some limitations. It's meant to be a quick switch to convert something to a RenderTexture. But it's not that flexible. If you need to cache the underlying RenderTexture you should not use cacheAsBitmap directly and instead create a RenderTexture yourself. It's pretty straightforward and gives you more control for resource management.

**Comment by apinder** [comment]
Makes sense, I'll use a RenderTexture for this then, thanks.

Thanks for the quick response!

**Comment by bigtimebuddy** [comment]
No problem. Good luck.
