### ISSUE TITLE
[ Question ] "Infinity Scrolling"

### ISSUE THREAD

**Issue by isuckatprogram** [pixijs/pixi.js#6953]
I'm creating a game with pixijs and I want to create something kind of like infinity scrolling so when the player gets to the edge I want the camera to move with the player basically making it like the room is infinity and it doesn't end.

Is this possible with PixiJS? and how?

**Comment by JohnEastWork** [comment]
Check TilingSprite.
https://pixijs.io/examples/#/sprite/tiling-sprite.js

**Comment by SukantPal** [comment]
You can also use pixi-viewport if needed.

**Comment by ivanpopelyshev** [comment]
We really need article on any "infinite" stuff.
https://www.html5gamedevs.com/topic/44557-sprite-blending/?tab=comments#comment-247993
https://www.html5gamedevs.com/topic/44255-performance-tips-for-large-scale-2d-graphing/?tab=comments#comment-246913
