### ISSUE TITLE
How do I run a quick PixiJs Demo project again? You say 'simple installation' I say confusing

### ISSUE THREAD

**Issue by heliosnarcissus** [pixijs/pixi.js#6957]
I look for a way start , immediately I am faced with this dilemma:
          
```
Unminified:

https://pixijs.download/<branch-or-tag-name>/pixi.js
https://pixijs.download/<branch-or-tag-name>/pixi.js.map
Minified:

https://pixijs.download/<branch-or-tag-name>/pixi.min.js
https://pixijs.download/<branch-or-tag-name>/pixi.min.js.map
```
like what are those? where do I paste those? Do they come in pairs?  Or will it work if I use 'https://pixijs.download/<branch-or-tag-name>/pixi.js' only?
BTW, how do I use 'https://pixijs.download/<branch-or-tag-name>/pixi.js'  where do I stick it in?

Then you have the "built" and "pre-built" :
Like what am I building, your game engine or my game in pixi-js?
whaaaaat???

Then after I copy paste your demo code, how do I run it? is it as simple as saving the project or do I run 'npm run dev'?
what if I have an existing framework that uses 'npm run dev' script? like Vuejs or Sveltejs?

**Comment by bigtimebuddy** [comment]
Please consider using one of these boilerplate projects for getting started or with other frameworks:
https://github.com/pixijs/pixi.js/wiki/v5-Boilerplate

If you're using PixiJS in an HTML page directly you embed this tag on your page.

```html
<script src="https://pixijs.download/v5.3.3/pixi.min.js"></script>
<script>
   const app = new PIXI.Application();
   document.body.appendChild(app.view);
   // your code here!
</script>
```

**Comment by bigtimebuddy** [comment]
I'm closing this, if you're question isn't answered we can reopen.
