### ISSUE TITLE
Chopped texture by triangle frame which shifted little to left on top side image, then shifted little to right at bottom of image

### ISSUE THREAD

**Issue by lancety** [pixijs/pixi.js#6963]
I made a list of trees for different terrain zone in one 1200 x 3000 image. so each block is 200 pixels. shown as below attachment.
Thanks for help~ 
![zoneTree](https://user-images.githubusercontent.com/5547558/97221408-f0a07600-1820-11eb-96fd-f5648def1ce8.jpg)

### Expected Behavior
After looping each cell in the 200x200 grid, I should get a list of textures, and tree in each texture cell should be centered in the middle of X axis of that 200x200 area

### Current Behavior
First row (snow tree) texture cell chopped area actually is shifted to left a little bit, so the tree is little on right side instead just in middle of X axis. then each row's tree started to be located more and more on left side 

Tree should be located at blue line (middle of X axis) 
this tree is first row of the whole image
![111](https://user-images.githubusercontent.com/5547558/97222877-162e7f00-1823-11eb-8fc6-8a0d9b951a2e.PNG)
this tree is the 4th last row of the image.
![222](https://user-images.githubusercontent.com/5547558/97222883-17f84280-1823-11eb-9728-9908cb18cb4c.PNG)

### Sample code - generate tree texture cells
```js
const image = new Image();
image.src = zoneTreeConfig.src;
image.onload = function() {
    const treeTextureBase = BaseTexture.from(image);
    const treeSize = 200;
    for (let r = 0; r <= 14; r++) {
        for (let q = 1; q <= 5; q++) {     // first collumn is the title for that row so ignore it
            const prop = "_" + (q-1) + "_" + r;
            const area = new Rectangle(
                q * treeSize, r * treeSize,
                treeSize, treeSize
            );
            zoneTreeRowTexture[prop] = new Texture(treeTextureBase, area);
            zoneTreeShadowRowTexture[prop] = makeTreeShadowTexture(zoneTreeRowTexture[prop]);
        }
    }
};
```

### Sample code - generate tree sprite and interaction area
```js
    const col = makeIntFn(5);
    const texture = zoneTreeShadowRowTexture["_" + col + "_" + row];

    const treeSprite = makeSprite(objLibId, obj, texture);
    if (treeSprite) {
        treeSprite.scale.x *= 0.9 + makeIntFn(25) / 100 * (zoneId % 2 === 0 ? 1 : -1);
        treeSprite.interactive = true;
        treeSprite.buttonMode = true;

        // todo use interaction of object props value to make it clear
        const left = treeSprite.width * -0.25, top = treeSprite.height * -1;
        treeSprite.hitArea = new PIXI.Rectangle(left, top, treeSprite.width * 0.5, treeSprite.height);

        return treeSprite;
    }
```

### Sample code - makeSprite
```js
function makeSprite(libId: int, obj: iStaticObject, texture: Texture): PixiSprite {
    const {type, dynamic} = obj;
    const regionId = obj.geoWatch.regionId.val;
    const physicsPosRegion = obj.physicsWatch.positionRegion?.val;
    const physicsPos = obj.physicsWatch.position?.val;
    const pos = physicsPosRegion || mapPosToRegionPos_vec2(csService.terrainState.cachedRegions[regionId].val.state.commonProps, [physicsPos[0], physicsPos[2]]);
    const size = obj.spriteConfig.size;
    const sprite = new PixiSprite(texture);
    sprite.name = `${dynamic ? "d" : "s"}_${type}_${libId}`;
    sprite.x = pos[0];
    sprite.y = pos[1];
    sprite.zIndex = sprite.y;
    sprite.anchor.set(0.5, 1);     //  anchor at tree root 
    sprite.width = size[0];
    sprite.height = size[1];

    return sprite;
}
```

### Env
"pixi.js": "^5.2.1",
chrome 86
window 10

**Comment by bigtimebuddy** [comment]
## Top Row
![Screen Shot 2020-10-26 at 4 30 48 PM](https://user-images.githubusercontent.com/864393/97225149-a4195400-17a8-11eb-95aa-5035bad7c8f8.png)

## Bottom Row
![Screen Shot 2020-10-26 at 4 30 41 PM](https://user-images.githubusercontent.com/864393/97225147-a2e82700-17a8-11eb-9592-46ad73a0458f.png)

Your vertical center lines are not straight.

**Comment by lancety** [comment]
did not notice that line not straight issue.  Thaks @bigtimebuddy .  I made this image just for early stage testing, you are right, I should use proper tool for managing these sprites.  

I draw these trees in SketchBook, but seems the 90 degree rule is not really making accurate vertical lines (red).  Will avoid using it this way in fureture.

**Comment by bigtimebuddy** [comment]
Sounds like we got to the bottom of it! Good luck with your project, those are nice looking trees.

Closing this issue.
