### ISSUE TITLE
Unable to write special characters in Pixi.BitmapText, Works Fine using Pixi.Text

### ISSUE THREAD

**Issue by redstubble** [pixijs/pixi.js#6964]
I am unable to display special characters inside BitmapText, what am I missing. All special chars are currently stripped.

```javascript
BitmapFont.from('TitleFont', {
    fontFamily: 'Arial',
    fontSize: 12,
    strokeThickness: 1,
    fill: 'white',
});

export const createText = (textDim: { x: number; y: number }, color: number) => {
    const style = {
        fontName: 'TitleFont',
        fill: color,
        wordWrap: true,
        stroke: '0x000000',
        fontSize: 12,
        wordWrapWidth: 280,
    };
    const text = new BitmapText("You \& I are singing!", style);
    text.name = 'text';
    text.x = textDim.x + PixiSettings.label.padding;
    text.y = textDim.y + PixiSettings.label.padding;
    return text;
};
```

Result is "You I are singing"

Special Characters work fine using Pixi.Text

**Comment by andrewstart** [comment]
See the `chars` property of the options object: http://pixijs.download/release/docs/PIXI.BitmapFont.html#.from
The default is just letters and numbers, no special characters.

**Comment by bigtimebuddy** [comment]
@redstubble Here's an example of the use of `chars` https://jsfiddle.net/bigtimebuddy/6oL8rpgk/

In general, you want to keep your set of characters as small as possible.

Good luck. Closing this issue. Let use know if your question wasn't answered and we can reopen.

**Comment by redstubble** [comment]
Thanks guys missed this. Appreciate your quick responses
