### ISSUE TITLE
BitmapData#copyChannel equivalent

### ISSUE THREAD

**Issue by KennethGomez** [pixijs/pixi.js#6970]
Hey,

Thank you in advance for your time, I am migratimg a flash game to pixi and there's a function in flash called `copyChannel` [flash docs](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BitmapData.html#copyChannel()), on flash I am using it to copy green channel to alpha channel with same coords as destPoint, is there any way I can do this in PIXI.js?

Thank you,
Kenneth

**Comment by bigtimebuddy** [comment]
Hi @KennethGomez, I don't think there's an equivalent, but you could create your own using the extract Renderer plugin (to get the pixel values) and `BaseTexture.fromBuffer` to create a texture from a buffer. It's a little manually, but I'm sure it'd be easy to wrap some convenience around this.

https://jsfiddle.net/bigtimebuddy/a6vc5ye8/

**Comment by SukantPal** [comment]
Another way to do this is to use a shader. You basically use the mid-level API directly to bind a shader & geometry to output from the bitmap texture into a render-texture that you can use. You'd have to write the shader yourself tho. Good luck!

**Comment by KennethGomez** [comment]
> Hi @KennethGomez, I don't think there's an equivalent, but you could create your own using the extract Renderer plugin (to get the pixel values) and `BaseTexture.fromBuffer` to create a texture from a buffer. It's a little manually, but I'm sure it'd be easy to wrap some convenience around this.
> 
> https://jsfiddle.net/bigtimebuddy/a6vc5ye8/

Yep, with some modifications it was the same result, thank you very much!

**Comment by KennethGomez** [comment]
> Another way to do this is to use a shader. You basically use the mid-level API directly to bind a shader & geometry to output from the bitmap texture into a render-texture that you can use. You'd have to write the shader yourself tho. Good luck!

Thank you for responding, but I think it's easier modifying each pixel, anyway, thank you very much too!
