### ISSUE TITLE
Publishing 4.4.5 version

### ISSUE THREAD

**Issue by flashist** [pixijs/pixi.js#6971]
I was wondering, if it's possible to publish the 4.4.5 version, which would consist of fixes for the 4.4.4 version.

We use pixi.js in a various products and can't update some of them to the latest 4.x version, because there are breaking changes between 4.4.x and 4.8.x version.

Please, let me know if it's possible to, let's say, create the v4.4.x branch, so I will create a PR with needed changes there and then the v4.4.6 version will be published.

**Comment by bigtimebuddy** [comment]
Sure, I have created this branch: https://github.com/pixijs/pixi.js/tree/v4.4.x

We should be able to back-port newer fixes. Just FYI, I would like to limit this branch to fixes only--no new features. If there are fixes that affect other v4.x branches, my preference would be to make them to the v4.x and we can cherry-pick backwards.

Please reach out to me (Slack preferable) if you need any help.

**Comment by flashist** [comment]
Thanks for the explanation. The PR is created: https://github.com/pixijs/pixi.js/pull/6972
