### ISSUE TITLE
Uncaught TypeError: this.newTransparency is not a function

### ISSUE THREAD

**Issue by ichabodphage** [pixijs/pixi.js#6976]
anyways, im attempting to make a class named rectangle that takes parameters for a Pixi graphics rectangle object and make a new individual rectangle object.

`class rectangle {

    constructor(legnth, width, xPos, yPos, color, transparency, isButton, xVelocity, yVelocity, borderWidth, borderColor) {
        this.shape = new Graphics();
        //a border is not necessary when creating a rectangle in PIXI, as such it is optional
        this.shapeBorderWidth = borderWidth;
        this.shapeBorderColor = borderColor;
        this.shapeColor = color;
        this.shapeTransparency = transparency;
        this.shapeWidth = width;
        this.shapeLength = legnth;
        this.currentX = xPos;
        this.currentY = yPos;
        if (borderWidth != undefined) {
            if (borderColor != undefined) {
                this.shape.lineStyle(borderWidth, borderColor, transparency);
            } else {
                this.shape.lineStyle(borderWidth, color, transparency);
            }
        }

        //regular PIXI rectangle setup
        this.shape.beginFill(this.shapeColor, this.shapeTransparency);
        this.shape.drawRect(0, 0, this.shapeLength, this.shapeWidth);
        this.shape.x = this.currentX;
        this.shape.y = this.currentY;
        this.shape.endFill();

        //velocity is not required to make a rectangle in PIXI, as such it is optional
        if (xVelocity != undefined) {
            this.shape.vx = xVelocity;
        } else {
            this.shape.vx = 0;
        }
        if (yVelocity != undefined) {
            this.shape.vy = yVelocity;
        } else {
            this.shape.vy = 0;
        }

        if (isButton) {
            this.shape.interactive = true;
            this.shape.on('pointerdown', this.isPressed);
            this.shape.on('pointerup', this.isUnpressed);
            this.shape.on('pointerupoutside', this.isUnpressed);
            this.shape.on('pointerover', this.isUnderCursor);
            this.shape.on('pointerout', this.isNotUnderCursor);
        }
        app.stage.addChild(this.shape);
    }
    //get functions that return variables related to the position of the rectangle
    get currentYPos() {
        return this.shape.y
    }
    get currentXPos() {
        return this.shape.x
    }

    //set functions that modify the possition of the rectangle
    set newXVel(newXVel) {
        this.shape.vx = newXVel;
    }
    set newYVel(newYVel) {
        this.shape.vy = newYVel;
    }
    set newXPos(xPos) {
        this.shape.x = xPos;
        this.currentX = xPos
    }
    set newYPos(yPos) {
        this.shape.y = yPos;
        this.currentY = yPos;
    }

    //methods that have to do with buttons
    isPressed() {
        console.log("press");

    }

    isUnpressed() {
        console.log("unpress");
    }

    isUnderCursor() {
        console.log("under mouse cursor");
        this.newTransparency(0.5)
    }

    isNotUnderCursor() {
        console.log("not under mouse cursor");
        this.newTransparency(1)
    }

    newTransparency(newAlpha) {
        this.currentX = this.currentXPos
        this.currentY = this.currentYPos
        this.shape.clear();
        this.shapeTransparency = newAlpha;

        if (this.shapeBorderWidth != undefined) {
            if (this.shapeBorderColor != undefined) {
                this.shape.lineStyle(this.shapeBorderWidth, this.shapeBorderColor, this.shapeTransparency);
            } else {
                this.shape.lineStyle(this.shapeBorderWidth, this.shapeColor, this.shapeTransparency);
            }
        }
        this.shape.beginFill(this.shapeColor, this.shapeTransparency);
        this.shape.alpha = this.shapeTransparency
        this.shape.drawRect(0, 0, this.shapeLength, this.shapeWidth);
        this.shape.x = this.currentX;
        this.shape.y= this.currentY;
        this.shape.endFill()
    }
    //method that makes the rectangle object travel in a direction corresponding to a given angle
    moveAngle(magnitude, angle) {
        let rad = angle * (Math.PI / 180)
        this.shape.vx = magnitude * Math.cos(rad)
        this.shape.vy = magnitude * Math.sin(rad)
        this.shape.x += this.shape.vx;
        this.shape.y += this.shape.vy;
    }

    //method that moves the rectangle object based upon its current x and y velocity
    moveNoAngle() {
        this.shape.x += this.shape.vx;
        this.shape.y += this.shape.vy;
    }

}`

currently, im trying to create a button that gains an alpha value of 0.5 when the mouse is hovering over it using the newTransparency() method. strange thing is, when i call the newTransperancy() method within the method isUnderCursor() or isNotUnderCursor(), i get an error saying that this.newTransparency() is not a function. however, when newTransparency() is called outside of the class, it works perfectly fine, the rectangle has the new alpha value i enter in the parameters of newTransparency().

**Comment by themoonrat** [comment]
Where you have your 'on' callbacks, you need to supply 'this' as the 3rd parameter, so that the correct context of the functions are used.
For example
this.shape.on('pointerdown', this.isPressed, this);

**Comment by bigtimebuddy** [comment]
This is answered above. Closing this issue. Let us know if that doesn't work for you.
