### ISSUE TITLE
Typescript definitions incorrect

### ISSUE THREAD

**Issue by Neob91** [pixijs/pixi.js#6978]
Hi, I'm experiencing numerous TypeScript typing issues.
The most recent one is with the `PIXI.DisplayObject.destroy` method.
I can't call it with an argument, because I get the `TS2554: Expected 0 arguments, but got 1.` TypeScript error.

Definition of type when checking in `node_modules/pixi.js/pixi.js.d.ts`
<img width="640" alt="Screenshot 2020-11-04 at 09 17 26" src="https://user-images.githubusercontent.com/6197476/98086169-a6517180-1e7e-11eb-931d-73f86b53b220.png">

Definition of type when checking in `node_modules/pixi.js/dist/pixi.js`
<img width="678" alt="Screenshot 2020-11-04 at 09 17 55" src="https://user-images.githubusercontent.com/6197476/98086172-a7829e80-1e7e-11eb-9529-f069d28a4dd5.png">

Perhaps this is a build problem?

```sh
$ npm ls | grep "pixi\.js"
+-- pixi.js@5.3.3
```

**Comment by Neob91** [comment]
Sorry, added issue half-asleep in the wrong repository :-)

**Comment by bigtimebuddy** [comment]
This has been fixed in 5.4.0 (release soon). Our old approach of generating types was insufficient and several things kept getting missed, especially methods with multiple signatures like destroy.

**Comment by Neob91** [comment]
Awesome! Sorry for creating a duplicate issue then. :)

**Comment by bigtimebuddy** [comment]
No worries. Closing this.
