### ISSUE TITLE
Cannot set property glCore of #<Object> which has only a getter

### ISSUE THREAD

**Issue by thojanssens** [pixijs/pixi.js#6979]
Totally new to Pixi. I include the script like so:
```
  <script src="./pixi.min.js"></script>
  <script type="module" src="./app.js"></script>
</body>
```

In `app.js`:

```
import * as PIXI from './pixi.min.js';

const app = new PIXI.Application({
  width: 800,
  height: 600,
  backgroundColor: 0xAAAAAA
});

document.body.appendChild(app.view);
```

Error:

> index.js:24 Uncaught TypeError: Cannot set property glCore of #<Object> which has only a getter
    at Object.16../GLBuffer (VM913 pixi.min.js:9)
    at i (VM913 pixi.min.js:8)
    at VM913 pixi.min.js:8
    at Object.64../Application (VM913 pixi.min.js:12)
    at i (VM913 pixi.min.js:8)
    at VM913 pixi.min.js:8
    at Object.126../core (VM913 pixi.min.js:16)
    at i (VM913 pixi.min.js:8)
    at VM913 pixi.min.js:8
    at Object.<anonymous> (VM913 pixi.min.js:20)

**Comment by ivanpopelyshev** [comment]
lets see.. you load pixi globally, then use "import *" in app.js . Weird. Just remove this line and it should work.
I personally dont use modules at all, so you have to wait for someone else ;)

**Comment by thojanssens** [comment]
1. If I remove the script `<script src="./pixi.min.js"></script>` and keep the import `import * as PIXI from './pixi.min.js';`, I will have the error
> app.js:3 Uncaught TypeError: PIXI.Application is not a constructor

2. If I remove the import `import * as PIXI from './pixi.min.js';`, but keep the script `<script src="./pixi.min.js"></script>`, it now doesn't show an error anymore. However the canvas generated has a width of 0px (height is correct though: 600px), while I've set `width: 800`.

**Comment by thojanssens** [comment]
Even when I get the code out of the module, the canvas' width stays 0:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Pixi game</title>
  <style>
    body {
      height: 100vh;
      margin: 0;
      overflow: hidden;
    }
  </style>
  <script src="./pixi.min.js"></script>
  <script>
    let app;

    window.onload = function() {
      app = new PIXI.Application({
        width: 800,
        height: 600,
        backgroundColor: 0xAAAAAA
      });

      document.body.appendChild(app.view);
    };
  </script>
</head>
<body>
</body>
</html>
```

**Comment by thojanssens** [comment]
Just found out the last issue...

I downloaded from here:
https://github.com/pixijs/pixi.js/releases

But version 4 is shown before version 5... and I downloaded too fast thinking this was the latest *facepalm*.
Had to scroll down to get the latest which is unusual.

**Comment by bigtimebuddy** [comment]
npm dist-tags are the best information for the latest version. Unfortunately, releases are ordered by date not semver.

**Comment by thojanssens** [comment]
That's a pity that GH sorts per date I think! Thank you for helping 🤍
