### ISSUE TITLE
What is current state of light plugins?

### ISSUE THREAD

**Issue by kxmatejka** [pixijs/pixi.js#6980]
Hello guys, I'm completely lost. What is current state of the light plugins? Is it possible to achive something like this https://pixijs.io/pixi-lights/demo/index.html in pixi v5?

Thank you very much.

**Comment by bigtimebuddy** [comment]
Please add an issue on the pixi-lights repo as this is relevant just to that project. Pixi-lights is a plugin maintained mostly by @ivanpopelyshev and is not part of the core repo, so it gets less attention and likely needs to be updated. If someone out there is interested in helping to maintain that project let us know.
