### ISSUE TITLE
Result of getBounds changes when zooming

### ISSUE THREAD

**Issue by SpraylnlPray** [pixijs/pixi.js#6986]
Hey there, I'm new to Pixi and want to use it in a React project. I looked into PixiReact, but am also evaluating the native form in combination with React as it seems more intuitive for me.

While playing around with drawing the bounding box of sprites I found behavior that I can't quite understand. I have a simple app where a button will create a sprite and another button will draw lines with the measurements of the sprite (getBounds()). When zooming and recalculating this bounding box, its area changes. Is that intended or maybe related to my setup?

### Expected Behavior
The bounding box around the sprite stays the same, no matter what zoom level.

### Current Behavior
When zooming out the box gets smaller, when zooming in the box gets bigger.

start:
![image](https://user-images.githubusercontent.com/33932864/98596732-268d3200-22d8-11eb-83b4-b75449058570.png)

zoomed out:
![image](https://user-images.githubusercontent.com/33932864/98596754-3278f400-22d8-11eb-9074-0b01fe59f1d2.png)

zoomed in:
![image](https://user-images.githubusercontent.com/33932864/98596819-4b81a500-22d8-11eb-80e5-2d3ae66cb476.png)

### Possible Solution
--

### Steps to Reproduce
1. Clone the repo https://github.com/SpraylnlPray/PixiReactViewport
2. npm install
3. npm start
4. Click button on top "Spawn bunny" sprite will appear on top left
5. Click button "Activate border", border will appear around the sprite
6. Zoom as you wish, click "Update border" every then and now to see the effect

### Environment
- see github repo

Thanks for any hints and suggestions!

**Comment by eXponenta** [comment]
getBounds return a size in canvas pixels.
This means that any DOM zoom's that change it was affect to it.

**Comment by SpraylnlPray** [comment]
Hey @eXponenta, thanks for your reply. I found a solution to the problem. It seemed like the bounds would calculate correctly, but not scale accordingly. The way I solved it, was to pass a readonly reference of the stage to the objects and when creating or updating the border I first call _getBounds()_ and then divide the width and height of the bounds through the scale:

```
  updateBorder(): void {
    if (this.border === undefined) {
      return;
    }

    this.instance.removeChild(this.border.getInstance());
    const bounds = this.instance.getBounds();
    this.border = new Border(
      bounds.width / this.stage.scale.x,
      bounds.height / this.stage.scale.y
    );
    this.instance.addChild(this.border.getInstance());
  }
```
