### ISSUE TITLE
Application crash on multiple stage resize on ios devices

### ISSUE THREAD

**Issue by selirion04** [pixijs/pixi.js#6987]
Something goes wrong on app.renderer.resize in safari or chrome on ios.
Usual case for stage resize is device orientation change. App crash happened after 3-4 rotations.
Here is example which just resize stage every 0.7s: https://codepen.io/Insi04/pen/XWKxwOe
It crashed on ios devices after 3-10 cycles.
Not reproduced on android or windows.

So, looks ios-side, but maybe any workarounds or other ideas:)

UPD: also reproduced on v4 (but maybe more iterations because of no autoDensity setting - more pixels more leaks i think) https://codepen.io/Insi04/pen/OJXaLLo
UPD2: check samples without pixi: resizing empty canvas, canvas with 2d content, canvas with simple webgl content, canvas examples from https://webglsamples.org - no crashes found. 
UPD3: not reproduced on ios 13.6

### Environment

- **`pixi.js` version**:  5.3.3, 4.4.4
- **Browser & Version**: Chrome 86, Safari 14.1
- **OS & Version**:  iOS 14.1, 14.2
- **Running Example**: https://codepen.io/Insi04/pen/XWKxwOe

**Comment by selirion04** [comment]
Find same issue on threejs https://github.com/mrdoob/three.js/issues/20453
So just close it if no workarounds available :(

**Comment by themoonrat** [comment]
on an empty canvas o_O. Oh boy.

**Comment by hardikkaji-netent** [comment]
I am seeing similar issues with our apps. It reloads after 5-10 rotates for iOS 14.1 & 14.2 

Any workarounds?

**Comment by magos1983** [comment]
Same issue here, calling renderer.resize(width, height) after device rotation. works approximately 20 times then page reload and in chrome - ios it reloads and second time the page crashes.

Any workaround for this?

**Comment by selirion04** [comment]
> Any workaround for this?

As I think the only way is not resize canvas, e.g. create square oversized canvas and use just part of it for your render. But it will produce performance issues I think.
Also you could investigate dependencies of crash, because its different on different apps - I need just 2-3 rotations in my app.

**Comment by magos1983** [comment]
For the time being I will force canvas render until iOS 14.3 is released. For my application performance is good enough.

**Comment by AgileInteractive** [comment]
The resizing of the renderer increases the memory usage each time, until it runs out of memory and crashes. On a new iPad with lots of memory it can take some time before it crashes, but on an older one it will happen pretty fast.

**Comment by selirion04** [comment]
ios 14.3 released, canvas resize fixed.
