### ISSUE TITLE
Is there no loaded event for Pixi texture?

### ISSUE THREAD

**Issue by YANGSROOT** [pixijs/pixi.js#6991]
const texture:Texture= Texture.from("image url");
texture.baseTexture.on("loaded",function(){
    console.trace();
});
texture.on("loaded",function(){
    console.trace();
});
These are examples

I see that the texture event in the document is loaded
But the test found that it didn't trigger
After looking at the source code, we found that it did not write emit ("loaded")

I am a Chinese, English is very poor, the above are machine translation

**Comment by YANGSROOT** [comment]
May cause misunderstanding, please forgive me

**Comment by ivanpopelyshev** [comment]
its either
```js
texture.on('update', );
```

either

```js
texture.baseTexture.on('loaded', ...)
```

see the source code.

**Comment by bigtimebuddy** [comment]
Consider using Texture.fromURL which returns a Promise. Easier to use than Texure.from. Also, handles errors better.

**Comment by YANGSROOT** [comment]
I almost understand. Thank you very much for your answers
