### ISSUE TITLE
[Suggestion] Enable discussions tab

### ISSUE THREAD

**Issue by IljaDaderko** [pixijs/pixi.js#6992]
I'm not sure if this was considered before or not, but how do you guys feel about enabling discussions tab for the repo and pointing users with potential [Question] issues there instead, to try and keep issues cleaner?

I've been working with pixi for past 4 months and generally when I have questions I try to post them in stackoverflow, however response there is usually slow or non-existent. https://www.html5gamedevs.com is another alternative and Ivan is full on "beastmode" there answering questions, however it seems as if its only him and very few others.

Perhaps enabling discussions here and making it clear in readme / github issue template that questions and requests for help could be asked there might help a bit in terms of community and learning pixi?

If this sounds interesting I could try and help in setting up something like https://github.com/vercel/vercel/issues/new/choose this experience when creating an issue (it can point to either issues or discussions based on what users choose).

**Comment by bigtimebuddy** [comment]
Great idea! I think GitHub Discussions is still in beta (we do not have an option to enable it), but I think that's a good shout and we should do that when it becomes more widely available.

**Comment by IljaDaderko** [comment]
Awesome, I believe this topic is where you can apply for a beta access https://github.community/t/can-one-apply-for-github-discussions-beta/121120 might help get it sooner.

**Comment by bigtimebuddy** [comment]
Done! Thanks for the tip @IljaDaderko

**Comment by ivanpopelyshev** [comment]
>  Ivan is full on "beastmode" there answering questions

I'll keep this as quote, ok? :)

**Comment by bigtimebuddy** [comment]
Going to close this issue. Will enable when we get approved for the beta or this feature is public.

**Comment by bigtimebuddy** [comment]
This is now in public beta and available here: https://github.com/pixijs/pixi.js/discussions
