### ISSUE TITLE
GlobalMixins Typings Don't Work

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#6993]
I published v5.4.0-rc.1 to try to identify issues with package-level typings. Overall it works great. There are some improvements we could make, like moving documentation blocks to the properties declarations in the class (historically these were added to the constructor assignment). 

ANYWAYS, the big issue is GlobalMixins class augmentation doesn't work. This is essential for doing mixins and extending existing classes like DisplayObject and Container. I created a simple project locally and I found that two things worked:

### Example

```typescript
import { Container } from '@pixi/display';
import '@pixi/mixin-cache-as-bitmap';

const stage = new Container();
stage.cacheAsBitmap = true; // <-- this fails
```

### Workarounds

1. Adding reference to the **global.d.ts** seemed to work in registering the GlobalMixins namespace.

```typescript
///<reference path="./global.d.ts" />
```

2. Adding `declare global` to the **index.d.ts** also worked.

```typescript
declare global {  namespace GlobalMixins { } }
```

The problem with both of these approaches is that api-extractor ignores both. We might need to add something custom to inject these to the output declaration, or find another solution.

Thoughts?

cc @ivanpopelyshev @SukantPal

**Comment by SharasB** [comment]
I am having this exact issue in 7.0.2
