### ISSUE TITLE
Document link for pixi.extract is dead

### ISSUE THREAD

**Issue by shi-yan** [pixijs/pixi.js#7001]
document bug, link for http://pixijs.download/release/docs/PIXI.Extract.html is dead

**Comment by Zyie** [comment]
Seems like there is now a `_` at the end

http://pixijs.download/release/docs/PIXI.Extract_.html

@SukantPal guessing this might be a webdoc bug?

**Comment by SukantPal** [comment]
Yeah, this might be a webdoc bug. I'll make an issue.
