### ISSUE TITLE
Downloading canvas PNG in high resolution

### ISSUE THREAD

**Issue by rodighiero** [pixijs/pixi.js#7002]
Hi all,

I was used to downloading canvas images in PNG when the network visualization is too complex to interact with it. As I would like to print a large image with 80,000 nodes, I noted that my usual script does not work anymore:

```var a = document.createElement("a");
a.href = document.getElementsByTagName('canvas')[0].toDataURL()
a.download = "Image.png";
a.click();
```

Network visualization available at https://rodighiero.github.io/COVID-19/

Is there someone able to help me with this issue? It is deeply appreciated.

All best,
Dario

**Comment by themoonrat** [comment]
I'd advise taking a look at https://pixijs.io/examples/#/demos-advanced/screenshot.js

**Comment by rodighiero** [comment]
Hi Dave, thank you!

It works, but the pixel resolution is very low. Do you know if there is any additional setting? My need is to export a very large format to print.

**Comment by rodighiero** [comment]
I have found the solution finally. It was necessary to scale up Pixi Viewport.

Thank you!
