### ISSUE TITLE
"Uncaught TypeError: Cannot set property '_parentID' of undefined" when trying to add an object as a child to a container

### ISSUE THREAD

**Issue by ichabodphage** [pixijs/pixi.js#7004]
`class sceneRectangle {
    constructor(legnth, width, xPos, yPos, color, transparency, xVelocity, yVelocity, borderWidth, borderColor) {
        this.shape = new Graphics();

        //a border is not necessary when creating a rectangle in PIXI, as such it is optional
        this.shapeBorderWidth = borderWidth;
        this.shapeBorderColor = borderColor;
        this.shapeColor = color;
        this.shapeTransparency = transparency;
        this.shapeWidth = width;
        this.shapeLength = legnth;
        this.currentX = xPos;
        this.currentY = yPos;
        if (borderWidth != undefined) {
            if (borderColor != undefined) {
                this.shape.lineStyle(borderWidth, borderColor, transparency);
            } else {
                this.shape.lineStyle(borderWidth, color, transparency);
            }
        }

        //regular PIXI rectangle setup
        this.shape.beginFill(this.shapeColor, this.shapeTransparency);
        this.shape.drawRect(0, 0, this.shapeLength, this.shapeWidth);
        this.shape.x = this.currentX;
        this.shape.y = this.currentY;
        this.shape.endFill();

        //velocity is not required to make a rectangle in PIXI, as such it is optional
        if (xVelocity != undefined) {
            this.shape.vx = xVelocity;
        } else {
            this.shape.vx = 0;
        }
        if (yVelocity != undefined) {
            this.shape.vy = yVelocity;
        } else {
            this.shape.vy = 0;
        }

    }
    //get functions that return variables related to the possition of the rectangle
    get currentYPos() {
        return this.shape.y
    }
    get currentXPos() {
        return this.shape.x
    }
    get hitbox() {
        return this.shape
    }

    //set functions that modify the possition of the rectangle
    set newXVel(newXVel) {
        this.shape.vx = newXVel;
    }
    set newYVel(newYVel) {
        this.shape.vy = newYVel;
    }
    set newXPos(xPos) {
        this.shape.x = xPos;
        this.currentX = xPos
    }
    set newYPos(yPos) {
        this.shape.y = yPos;
        this.currentY = yPos;
    }

    //method that redraws the shape with a different alpha value
    newTransparency(newAlpha) {
        this.currentX = this.currentXPos
        this.currentY = this.currentYPos
        this.shape.clear();
        this.shapeTransparency = newAlpha;

        if (this.shapeBorderWidth != undefined) {
            if (this.shapeBorderColor != undefined) {
                this.shape.lineStyle(this.shapeBorderWidth, this.shapeBorderColor, this.shapeTransparency);
            } else {
                this.shape.lineStyle(this.shapeBorderWidth, this.shapeColor, this.shapeTransparency);
            }
        }
        this.shape.beginFill(this.shapeColor, this.shapeTransparency);
        this.shape.alpha = this.shapeTransparency
        this.shape.drawRect(0, 0, this.shapeLength, this.shapeWidth);
        this.shape.x = this.currentX;
        this.shape.y = this.currentY;
        this.shape.endFill()
    }
    //method that makes the rectangle object travel in a direction corisponding to a given angle
    moveAngle(magnitude, angle) {
        let rad = angle * (Math.PI / 180)
        this.shape.vx = magnitude * Math.cos(rad)
        this.shape.vy = magnitude * Math.sin(rad)
        this.shape.x += this.shape.vx;
        this.shape.y += this.shape.vy;
    }

    //method that moves the rectangle object bassed upon its current x and y velocity
    moveNoAngle() {
        this.shape.x += this.shape.vx;
        this.shape.y += this.shape.vy;
    }
}

//allows the creation of unique scenes that can be switched between
class scene {
    constructor(sceneObject) {
        this.menu = new PIXI.Container();
        this.level.addChild(sceneObject)
        app.stage.addChild(this.menu)
    }
}

`

`
loader.load(setup);

var tittleScreen;
function setup() {
    tittleScreen = new scene(new sceneRectangle(100,100,500,570,0x0000FF,1))
    
}
`

currently, i have a class dedicated to creating rectangle objects to be used in tangent as a parameter for the scene class to allow easy creation of different "scenes" i plan on using to create menus. however, it seems as if i cannot add sceneRectangle objects into the container and i get an error "Uncaught TypeError: Cannot set property '_parentID' of undefined"

**Comment by bigtimebuddy** [comment]
Make your sceneRectangle class extend Graphics and get rid of all that internal shape object. Your sceneRectangle is not a valid Pixi object. Better to extend something if you're going to pass to addChild. Or else do addChild(sceneRect.shape) instead.

**Comment by SukantPal** [comment]
@ichabodphage Please close this issue if you have found the fix.
