### ISSUE TITLE
pixijs load resource s been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixi.js#7005]
pixijs load resource s been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by SukantPal** [comment]
That's not a problem with PixiJS. Learn about CORS: https://developer.mozilla.org/en-US/docs/Glossary/CORS, and enable CORS on your server.

**Comment by Carsair** [comment]
Should not be closed as "not a bug", People are following your docs and they are not including enough information to get it working.  Saying "google WAMP" or "enable CORS on your server" is not good enough imo.

**Comment by ShukantPal** [comment]
@Carsair The guides weren't even made when this issue was opened.

**Comment by ShukantPal** [comment]
The good thing is you can improve the guides at pixijs/guides
