### ISSUE TITLE
5.4.0-rc2 OffscreenCanvas issue

### ISSUE THREAD

**Issue by andrewstart** [pixijs/pixi.js#7009]
In `InteractionManager.setCursorMode()`, there is a check for `OffscreenCanvas`:
```javascript
// offscreen canvas does not support setting styles
if (this.interactionDOMElement instanceof OffscreenCanvas) {
    return;
}
```
In browsers that don't support OffscreenCanvas yet (Firefox, Safari), this throws an error due to `window.OffscreenCanvas` being undefined. `if (self.OffscreenCanvas && this.interactionDOMElement instanceof OffscreenCanvas)` is the obvious fix, although I don't know if this issue would be present elsewhere in the OffscreenCanvas referencing code.

**Comment by bigtimebuddy** [comment]
That fix sounds reasonable to me.

**Comment by themoonrat** [comment]
Sounds good to me too
