### ISSUE TITLE
Font recognition (font.ttf file)

### ISSUE THREAD

**Issue by lakusiclazar** [pixijs/pixi.js#7017]
Hello, 
I think that you can fix this very fast. I am using the font.ttf file.
It looks like Mozila Firefox does`t recognize this font, 
but i think that Pixi render makes a problem here.
Does this looks familiar to you? 

Best regards.
 * pixi.js - v5.1.6
 * Mozila Firefox

**Comment by SukantPal** [comment]
You're description doesn't make sense. What `font.ttf` file are you talking about.

**Comment by ivanpopelyshev** [comment]
Do we even have ttf file loader? I mean, it should go to css stuff, either through FontObserver from another lib (not pixi)

**Comment by bigtimebuddy** [comment]
Ivan is right, there's no font loading in Pixi. Devs should handle this in the browser themselves. I'm going to close this because it's out of scope. If the user provides more info or an examples, we can reopen.
