### ISSUE TITLE
Math.Matrix.append multiplies matrices instead of appending

### ISSUE THREAD

**Issue by Tukkan** [pixijs/pixi.js#7019]
I am reading the source code and I ran into [Math.Matrix.append()](https://github.com/pixijs/pixi.js/blob/fc4ca303a8f03eee754e12e0e769c263d8b19465/packages/math/src/Matrix.ts#L270) function which (I think) suppose to add one matrix to another.
In the source code, I can see that it does not append but multiply those matrices. Is there any reason for it?

```
   /**
     * Appends the given Matrix to this Matrix.
     *
     * @param {PIXI.Matrix} matrix - The matrix to append.
     * @return {PIXI.Matrix} This matrix. Good for chaining method calls.
     */
    append(matrix: Matrix): this
    {
        const a1 = this.a;
        const b1 = this.b;
        const c1 = this.c;
        const d1 = this.d;

        this.a = (matrix.a * a1) + (matrix.b * c1);
        this.b = (matrix.a * b1) + (matrix.b * d1);
        this.c = (matrix.c * a1) + (matrix.d * c1);
        this.d = (matrix.c * b1) + (matrix.d * d1);

        this.tx = (matrix.tx * a1) + (matrix.ty * c1) + this.tx;
        this.ty = (matrix.tx * b1) + (matrix.ty * d1) + this.ty;

        return this;
    }

```

**Comment by bigtimebuddy** [comment]
This was added 6 years ago by @GoodBoyDigital as best I can tell from the Git history. We could ask him the reason.

**Comment by Tukkan** [comment]
@bigtimebuddy Thank you.

I also think that here in [top comment](https://github.com/pixijs/pixi.js/blob/fc4ca303a8f03eee754e12e0e769c263d8b19465/packages/math/src/Matrix.ts#L33)

/**
 * The PixiJS Matrix as a class makes it a lot faster.
 *
 * Here is a representation of it:
 * ```js
 * | a | **c** | tx|
 * | b | d | ty|
 * | 0 | 0 | 1 |
 * ```
 * @class
 * @memberof PIXI
 */
export class Matrix
{
    public a: number;
    public b: number;
    public c: number;
    public d: number;
    public tx: number;
    public ty: number;

    public array: Float32Array|null = null;

    /**
     * @param {number} [a=1] - x scale
     * @param {number} [b=0] - x skew
     * **@param {number} [c=0] - y skew**
     * @param {number} [d=1] - y scale
     * @param {number} [tx=0] - x translation
     * @param {number} [ty=0] - y translation
     */

c is not y skew but x skew. I saw another issue that somebody pointed out that the comment representation matrix was wrong. It was fixed but I think description of params wasn't.

Cheers

**Comment by GoodBoyDigital** [comment]
ITs been a while! i can't actually remember where I got the terms from. but append / prepend (at the time) was synonymous with multiply / premultiply

**Comment by SukantPal** [comment]
@Tukkan If you are thinking that `append` should be matrix addition instead of multiplication, then that would be wrong. `append` simply means applying the transformation on a point by M1 and then M2 can be done by one transformation by M1xM2.

**Comment by SukantPal** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix(); yes, the x/y skews are wrong in the comment.
