### ISSUE TITLE
Big Drop in Performance from 5.2.0 to 5.3.3 when using CanvasRenderer

### ISSUE THREAD

**Issue by jazzyjeff5** [pixijs/pixi.js#7027]
I've discovered that moving from version 5.2.0 to 5.3.3 has caused a major drop in FPS when using the Canvas fallback. The two codepens below demonstrate this. They both create a large number of graphics objects, draw circles into them, and then randomly move them all around each frame. I get about 17fps on 5.3.3, and about 35fps on 5.2.0.

You can tweak CIRCLES_TO_CREATE if one of the tests reaches your monitors refresh rate, or if either test runs too slowly.

I'm not sure exactly which PIXI version caused the drop in performance, in between 5.2.0 and 5.3.3.

5.2.0

5.3.3

Thanks!

**Comment by JetLua** [comment]
I tested this: the performance degradation of the CanvasRenderer started from 5.2.2, which can be compared with 5.2.1.

5.2.1: https://d157l7jdn8e5sf.cloudfront.net/v5.2.1/pixi-legacy.js
5.2.2: https://d157l7jdn8e5sf.cloudfront.net/v5.2.2/pixi-legacy.js

**Comment by bigtimebuddy** [comment]
https://github.com/pixijs/pixi.js/compare/v5.2.1...v5.2.2 there are likely a few culprits that might contribute to this

**Comment by jazzyjeff5** [comment]
> I tested this: the performance degradation of the CanvasRenderer started from 5.2.2, which can be compared with 5.2.1.
> 
> 5.2.1: https://d157l7jdn8e5sf.cloudfront.net/v5.2.1/pixi-legacy.js
> 5.2.2: https://d157l7jdn8e5sf.cloudfront.net/v5.2.2/pixi-legacy.js

Thanks, just tested with these two versions, confirmed this is where the degradation is. FPS roughly halved moving from 5.2.1 to 5.2.2

**Comment by bigtimebuddy** [comment]
Anyone want to dig into dev tools and profile and those versions to see where in the code we are eating FPS?

**Comment by bigtimebuddy** [comment]
I'm thinking this might be #6443 cc @ivanpopelyshev this seems like the most likely merge in 5.2.2 that touched hot code in canvas rendering.

**Comment by bigtimebuddy** [comment]
I was able to isolate it down to these two commits:

#### Last good build (#6374,  0862ec8)
https://pixijs.download/fix-imageresource/pixi-legacy.min.js (Feb 2)

#### First bad build (#6403, 8a5292e)
https://pixijs.download/fix-legacy-texture-empty/pixi-legacy.min.js (Feb 11)

**Comment by JetLua** [comment]
It seems to be all right. Just some if statements. 👀

**Comment by vwmberry95** [comment]
I updated to 5.3.4 and I'm still seeing FPS cut in half after switching focus.

I have an Android app loading a webview with a site using Pixi. Stays around 60 FPS at first. When I switch focus to another fragment with a separate webview not using Pixi and then switch back, it stays around 30 FPS.

Reverting back to 5.2.1 did not fix the issue.  Could this be a separate issue?

**Comment by themoonrat** [comment]
Could well be a browser issue, then, relating to request animation frame. Or not an issue, as such, but the browser thinks it can't give full resource to 60fps, so offers 30fps instead.

**Comment by bigtimebuddy** [comment]
@vwmberry95 Please file a new issue and if you could create an example the demonstrates the performance drop, that'd be very helpful.

I'm closing this, because this specific performance issue is fixed you can see the comparison here:

**v5.3.3**
https://jsfiddle.net/bigtimebuddy/1jy08waf/

**v5.3.4**
https://jsfiddle.net/bigtimebuddy/ohk48vnL/
