### ISSUE TITLE
pixi 5.x for WX game with a problem that PIXI.Loader not work，url.indexOf is not a function

### ISSUE THREAD

**Issue by ZouYuLong** [pixijs/pixi.js#7043]
so sorry my english is very pool,  i have no solution but have to looking for help.
 i want to make a wexin game with PIXI，when i use PIXI.Loader  to load some image，that's wrong and show this problem "url.indexOf is not a function"
![1606814294(1)](https://user-images.githubusercontent.com/17397507/100720625-40162b00-33f9-11eb-90f6-2ebb203cf8fe.jpg)
please help me  and i want to know how can i show zhe image

**Comment by ZouYuLong** [comment]
i fount the position of the problem，i can't unstandstand the url is a object but a string
![1606814496(1)](https://user-images.githubusercontent.com/17397507/100721149-ee21d500-33f9-11eb-99b7-6d81353aa87e.jpg)  help help~~

**Comment by SerG-Y** [comment]
Hey @ZouYuLong, can you please provide a small example in https://jsfiddle.net or https://www.pixiplayground.com?

**Comment by ZouYuLong** [comment]
@SerG-Y ，thank you for haveing a word，in fact ，i was use it in normal web program is working，but in  wechat development tool it dose not work。 because of the adaper from wechat official dose not support any htmlElement  and i solve it,that' s work!
but another question why the url sometime is a String and sometime is a Object.....i cant undestand, so i added some code in PIXI.js 
![1606875458(1)](https://user-images.githubusercontent.com/17397507/100819735-b3667e00-3487-11eb-8055-a23cc37df0df.jpg)   i guess the problem is also form  the adaper from wechat official ,just guess

**Comment by ivanpopelyshev** [comment]
Another javascript thing that has to be fixed for WeChat? oh

**Comment by dragonwarrior95** [comment]
> aper from wechat official

大佬你解决了吗？我最近也在微信小游戏上用PIXIJS，也遇到加载图片失败的问题，求知道怎么解决

**Comment by dragonwarrior95** [comment]
楼主大佬你问题解决了吗？我最近也在微信小游戏上用PIXIJS，也遇到加载图片失败的问题，求指导怎么解决 @ZouYuLong
