### ISSUE TITLE
Strange lines behaviour on small polygons

### ISSUE THREAD

**Issue by Anckermann** [pixijs/pixi.js#7047]
I know, this issue was already opened in the past, specifically in #4361, but it was marked as a stale without any solution.
I have to draw this polygon at different angles and different sizes. When the size of the polygon and therefore the distance between points is larger, the behaviour is is correct:
![bug2](https://user-images.githubusercontent.com/9720910/101149661-8a78f100-361f-11eb-83a0-dcb737a95249.PNG)
While on smaller ones I get this strange lines. I tried with different stroke sizes and line alignments, but I cannot get it work as it should. I didn't find a value for the points' distance for wich this issue occours, but in the example provided in the image, the variance in x,y from one point to the other is not larger then ~0.3. (The red square is just for test, since I initially thought that the issue was the polygon rotation)
![bug](https://user-images.githubusercontent.com/9720910/101149440-3a9a2a00-361f-11eb-9d3d-adc7e38fe02e.PNG)

I am currently drawing this polygon with an instance of Pixi.Graphics:
```
polygon = new PIXI.Graphics();
polygon.lineStyle(0.01, 0x128110, 1, 0.5);
polygon.beginFill(0x128110, 0.15);
polygon.moveTo(x,y);
polygon.lineTo(x0,y0);
/*
*polygon.lineTo(xN,yN);
*/
polygon.endFill();
```

I've also tried `polygon.drawPolygon([coords])`, but the issue remains.

In this image you can see when this issue happens and when not, with just slight changes in size:
![bug3](https://user-images.githubusercontent.com/9720910/101157094-df216980-3629-11eb-9a8b-6d018c30b371.PNG)

[Here](https://www.pixiplayground.com/#/edit/g0werNFwWw1pfTbEx_-ss) a playground with the issue reproduced.
Is there something I can do to make this work correctly that I'm unaware of? 
Thanks in advance.

- **`pixi.js` version**: 5.1.3
- **Browser & Version**: Chrome 86
- **OS & Version**: Windows 10 - v2004

**Comment by eXponenta** [comment]
Not use thinkness less 1

**Comment by Anckermann** [comment]
I multiplied my coordinates by a factor of 4 while building the shape and then downscaled it 0.25 times and it worked for me.
Thanks for your help.
