### ISSUE TITLE
Filter order

### ISSUE THREAD

**Issue by idria** [pixijs/pixi.js#7055]
Hi, 

I am aplying a custom filter to a texture. 
```js
let rawSprite = new PIXI.Sprite(texture);
//....
var dicomShader = new PIXI.Filter('', 
    window.warp.resources.frag.data, 
        {
            photometric_interpretation: photometric,
            pixel_representation: representation,
            bytes_per_pixel: bytes,
            window_center: frame.windowCenter,
            window_width: frame.windowWidth,
            rescale_intercept: frame.rescaleIntercept,
            rescale_slope: frame.rescaleSlope,
        }
    );
rawSprite.filters = [dicomShader];

let actualWidth = rawSprite.width;
let actualHeight = rawSprite.height;

rawSprite.width = 146;
rawSprite.height = actualHeight * (146/actualWidth);
```

I split, from the server, 2 byte grayscale pixels into Red channel and Green channel (RGB). It works well, but I need to avoid resize image before the filter. I noticed that PIXI first resize image and then apply the filters. Is there an option to revert the order. If it is not possible to do, how I can apply filter "offline" and the use the filtered image to resize.

Thanks!

**Comment by ivanpopelyshev** [comment]
Are you sure you need a filter? Filter is applied to result of rendering of whole container. If you dont need that, you can use mesh-shaders, not filter: https://pixijs.io/examples/#/mesh-and-shaders/triangle-textured.js , its easier. But even then, it will be applied to result of texture filtering (linear, clamp, whatever). You have to store result of your mesh-shader or filter in renderTexture if you want to apply any shader on top of it, not dealing with scaling

**Comment by bigtimebuddy** [comment]
@idria was Ivan's suggestion sufficient for you?

**Comment by stepancar** [comment]
Looks like we can close this issue
