### ISSUE TITLE
fillGradientStops respects only values ordered ascending

### ISSUE THREAD

**Issue by kozickikarol** [pixijs/pixi.js#7069]
Hello,

I am during migration process between v4 to v5 and came across one problem regarding text styles.
In Pixi v4 `fillGradientStops` can have ascending or descending order. In Pixi v5 only ascending order is working, descending order displays only first color from fill array.

### Current Behavior

Here is working gradient with fillGradientStops ascending ordered:
https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%5B%22red%22%2C%22white%22%2C%22white%22%2C%22red%22%5D%2C%22fillGradientStops%22%3A%5B0%2C0.4%2C0.6%2C1%5D%7D%2C%22text%22%3A%22XDDDD%22%7D

Here is broken example with fillGradientStops descending ordered:
https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%5B%22red%22%2C%22white%22%2C%22white%22%2C%22red%22%5D%2C%22fillGradientStops%22%3A%5B1%2C0.6%2C0.4%2C0%5D%7D%2C%22text%22%3A%22XDDDD%22%7D

### Expected Behavior

fillGradientStops can be either ascending or descending ordered.

### Environment

- **`pixi.js` version**: 5.4.0-rc.3, 5.3.3
- **Browser & Version**: Brave Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)
- **OS & Version**: MacOS 11.1

**Comment by themoonrat** [comment]
Hmmm. What if we took the data received, and re-order it internally comparing the 2 arrays, then pass that to the existing code which could carry on as it were.

Would this be suitable, @kozickikarol ? Or does it specifically need gradients to start generating from bottom up?

**Comment by kozickikarol** [comment]
I can do it internally probably but just wanted to report that this is bug for sure, especially that descending order works for horizontally mode (you can check it on links I provided above).

**Comment by JetLua** [comment]
https://github.com/pixijs/pixi.js/blob/1127bd780f311a7fb89c72a0467bbd89dfb95f40/packages/text/src/Text.ts#L550-L552

Remove the restriction here and it seems to work. But I don't know if there are any other side effects.
