### ISSUE TITLE
Hello, After I switch my pixi.js to a higher version, it cannot support transparency.

### ISSUE THREAD

**Issue by iamverycute** [pixijs/pixi.js#7076]
```code
// I'm try 
this.app = new PIXI.Application(i,r,{transparent:!0});
......

this.app.renderer.backgroundColor=0xFFFFFFFF

//but background is white

//if you know...thanks....
```
- **`current pixi.js` version**: _e.g. latest_
- **`old pixi.js` version**: _e.g. 4.6.1_

**Comment by bigtimebuddy** [comment]
What do you mean by "latest" can you provide a running example?

**Comment by JetLua** [comment]
Maybe you don't need to set `this.app.renderer.backgroundColor=0xFFFFFFFF`.

DEMO: https://pixiplayground.com/#/edit/p0tuWN4El6K793O7lMRSq

**Comment by iamverycute** [comment]
> Maybe you don't need to set `this.app.renderer.backgroundColor=0xFFFFFFFF`.
> 
> DEMO: https://pixiplayground.com/#/edit/p0tuWN4El6K793O7lMRSq

Sorry，My English is bad! I use pixi.js 4.6.1,My config "{transparent:!0}"

but I use latest pixi.js "transparent" prop seems to have been removed.

So I try add "this.app.renderer.backgroundColor=0xFFFFFFFF", but background is white...

if ..you know...Thanks~~~

**Comment by iamverycute** [comment]
> What do you mean by "latest" can you provide a running example?

Sorry, the code cannot be exposed for the time being, Because it sucks!

**Comment by iamverycute** [comment]
It seems to have something to do with constructors

```code
//old code
 new PIXI.Application(width,height,{transparent:!0});

//new code
 new PIXI.Application({width:300,height:300,transparent:!0});

//It's OK! Thanks!!!!
```
