### ISSUE TITLE
TilingSprite bug with Canvas Renderer on v5.3.5

### ISSUE THREAD

**Issue by Article19** [pixijs/pixi.js#7077]
There is a bug with TilingSprite with the Canvas Renderer on v5.3.5

Repro:
https://jsfiddle.net/A19Group/9gd64tmq/2/

You can turn off forceCanvas to see it working in WebGL or change the PIXI version to 5.3.4 to see it working in Canvas.

Working = you will see many bunnies in a 100x100 square.

Not working = you will see a single bunny

**Comment by bigtimebuddy** [comment]
**Expected Rendering** (WebGL) ✅ 
![Screen Shot 2020-12-18 at 10 24 42 AM](https://user-images.githubusercontent.com/864393/102647879-5c190c80-411b-11eb-80a5-19eef1c36af6.png)

**Canvas (v5.3.4)** ✅ 
![Screen Shot 2020-12-18 at 10 25 25 AM](https://user-images.githubusercontent.com/864393/102647904-69ce9200-411b-11eb-86bc-bfa6ba09161a.png)

**Canvas (v5.3.5)** ❌ 
![Screen Shot 2020-12-18 at 10 25 14 AM](https://user-images.githubusercontent.com/864393/102647928-74892700-411b-11eb-9b59-668c366a645e.png)

**Canvas (dev)** ❌ 
![Screen Shot 2020-12-18 at 10 24 59 AM](https://user-images.githubusercontent.com/864393/102647949-8074e900-411b-11eb-998b-0bc3aa5dd1b2.png)

**Comment by bigtimebuddy** [comment]
Summoning @ivanpopelyshev or @SukantPal. There were some TilingSprite fixes in 5.3.5. Can someone take a look at this? We'll need to fix in dev and 5.3.x.

Likely relevant issues:

* #6869
* #6946
* #6887

**Comment by ivanpopelyshev** [comment]
Yes, i'll take it :)

**Comment by bigtimebuddy** [comment]
Need to fix this for 6.0.0, but released 5.3.6 with 5.3.4 behavior with canvas and TilingSprite.

**Comment by SukantPal** [comment]
See #7105 for the fix!
