### ISSUE TITLE
BaseTexture not update when canvas resource update on ios

### ISSUE THREAD

**Issue by whhbest** [pixijs/pixi.js#7095]
I get a problem with PIXI.BaseTexture on ios, and i'm not sure it is a bug or i use it in a wrong way.
 
I have a PIXI.BaseTexture with canvas resource,  the BaseTexture update when first update canvas, but later it doesn't work.

btw: it works well on pc & andriod

**Comment by ivanpopelyshev** [comment]
Its known bug, but I cant find previous issue. I dont even know if people reported it to safari, im not familiar with their bugtracker

Workaround: add clearRect on canvas when you draw on it.

Workaround without clearRect: ??

**Comment by whhbest** [comment]
> 
> 
> Its known bug, but I cant find previous issue. I dont even know if people reported it to safari, im not familiar with their bugtracker
> 
> Workaround: add clearRect on canvas when you draw on it.
> 
> Workaround without clearRect: ??

I clearRect when do init, then  use putImageData to update the canvas, it dose't work; but create a new PIXI.BaseTexture with the canvas.toDataURL, the new BaseTexture work well, the old has not effect.

**Comment by whhbest** [comment]
its not a pixi bug, but a canvas problem with putImageData.
