### ISSUE TITLE
Graphics line position is off when inside scaled DisplayObjectContainer  

### ISSUE THREAD

**Issue by MattAU** [pixijs/pixi.js#711]
When placing a Graphics object inside a DisplayObjectContainer that has been scaled up.

Looks fine for the CanvasRenderer but the position of the line is off when using the WebGL renderer. Tested on Chrome and IE (Win8)

http://jsfiddle.net/LyDx9/5/

**Comment by chrispine** [comment]
I'm also having problems with this. I understand the desire was to align on pixels, but it's not adding 0.5 pixels on an line of odd-pixel thickness: it's add 0.5 *before scaling* (which could be hundreds of pixels), and it's doing it when it's not exactly an even integer thickness.

It was well-intentioned, but was a mistake. It also doesn't match Canvas renderer's behavior. Please just delete the offending code in `PIXI.WebGLGraphics.buildLine()`.

**Comment by chrispine** [comment]
Also referenced here: http://www.html5gamedevs.com/topic/16521-possible-bug-in-phaser-v242/
