### ISSUE TITLE
Sprites within container that has cacheAsBitmap enabled appear blurry

### ISSUE THREAD

**Issue by IljaDaderko** [pixijs/pixi.js#7111]
I am not sure if this is a bug or expected behavior, but in essence when I apply `cacheAsBitmap` to a container that has sprites in it or bitmap text, essentially anything related to images, it all appears blurry on a retina display. It seems like `resolution` setting of application becomes ignored.

Here is screenshot taken from codesandbox linked below

<img width="253" alt="Screenshot 2020-12-30 at 20 49 32" src="https://user-images.githubusercontent.com/3154053/103374754-10823d80-4ae1-11eb-84b1-7ef5f85035e5.png">

### Environment

- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Chrome 87.0.4280.88
- **OS & Version**:  macOS 11.0.1
- **Running Example**: https://codesandbox.io/s/pixi-cache-as-bitmap-vp3o4 (you might need to refresh codesandbox browser if you don't see anything)

**Comment by IljaDaderko** [comment]
removing resolution from `Application` and instead setting `PIXI.settings.RESOLUTION = devicePixelRatio` solves the issue.

**Comment by bigtimebuddy** [comment]
The ergonomics of dealing with renderer resolution, filter resolution and global resolution are clunky. But yeah you answered your own question.
