### ISSUE TITLE
graphics-extras - drawChamferRect and drawFilletRect

### ISSUE THREAD

**Issue by inggy** [pixijs/pixi.js#7119]
It seems that the terminology for chamfer and fillet has been mixed up in the graphics-extras module. Fillet should be the one with rounded corners and chamfer should be angled corners. When I use drawFilletRect I get a rectangle with angled corners.

https://en.wikipedia.org/wiki/Chamfer
https://en.wikipedia.org/wiki/Fillet_(mechanics)

https://www.engineering.com/BIM/ArticleID/12682/Chamfer-or-Fillet-Its-More-Than-a-Coin-Toss.aspx

**Comment by rizen** [comment]
I can also confirm this.

**Comment by bigtimebuddy** [comment]
My bad. Will fix this.
