### ISSUE TITLE
PIXI.VideoResource is not a constructor

### ISSUE THREAD

**Issue by maximilianberndt** [pixijs/pixi.js#7126]
I'm trying to create a new VideoResource like this

```
const video = document.querySelector("video");
const videoResource = new PIXI.VideoResource(video);
```

but I'm getting this error:
`Uncaught TypeError: PIXI.VideoResource is not a constructor`

According to the [docs](https://pixijs.download/dev/docs/PIXI.VideoResource.html) it should exist so I'm not sure what I'm doing wrong.

- **`pixi.js` version**: 5.3.7

**Comment by bigtimebuddy** [comment]
Please refer to the specific documentation for this version:
https://pixijs.download/v5.3.7/docs/PIXI.resources.html

What you're looking for is `PIXI.resources.VideoResource`, we have removed this namespace in v6/dev (the documentation you linked).
