### ISSUE TITLE
Feature Request: Support line alignment on CanvasRenderer

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#7130]
Example of the incompatibility: https://jsfiddle.net/bigtimebuddy/j2ep45do/

CanvasRenderer does not support rendering alignment for strokes. This would require some changes to the CanvasGraphicsRenderer to get this to work. Since context2d does not have a stroke option for alignment, this would need to be accomplished with some type of clipping. 

PRs welcome!

**Comment by denim2x** [comment]
I'm working on this

**Comment by denim2x** [comment]
This [demo](https://jsfiddle.net/x9ec8Lg2/2/) shows the result:
![image](https://user-images.githubusercontent.com/8561801/104322905-271b9200-54ee-11eb-98fd-8c687e430097.png)

**Comment by ivanpopelyshev** [comment]
Workaround for max 10 shapes, this thing is very slow. 

We have to allow webgl computation for those shapes and use it as input for canvas line.

**Comment by denim2x** [comment]
Working on it

**Comment by SukantPal** [comment]
I don't like races on bounties

**Comment by bigtimebuddy** [comment]
@SukantPal fwiw, I don't like races on bounties either. I don't like people feel like they are competing. This was the first situation where this has happened. I've always been off the mind that first-to-submit gets considered first, first-to-merge get the bounty.

In this case, I'm also happy to pay bounties to both @denim2x and @SerG-Y because they are both helping move this along and it's a relatively small bounty. I appreciate the enthusiasm and desire to improve the canvas renderer. I want this process to be collaborative, so let's just figure out the best PR for performance & maintainability and go with that.

**Comment by SerG-Y** [comment]
@bigtimebuddy just want to clarify :) I don't need bounties as I pursue another goal while doing a contribution to Pixi, so in any case, we can just pay to @denim2x. 
I created my own PR as I saw the first @denim2x realization and I had another vision how to do it without creating an additional canvas that's more performing solution.

**Comment by denim2x** [comment]
My code should be better performing, also no artifacts are present:

![DEMO result](https://user-images.githubusercontent.com/8561801/105879193-8ad3ae00-600a-11eb-990f-5f6fbef2d1d2.png)

**Comment by SukantPal** [comment]
Looks like this got fixed?
