### ISSUE TITLE
BitmapText using BitmapFont.from() doesn't include punctuation

### ISSUE THREAD

**Issue by gwezerek** [pixijs/pixi.js#7132]
Thanks for all your hard work on this wonderful library and all the recent improvements to bitmap text.

Could be user error, but I [can't seem to get punctuation (have tried -,.&) to render](https://jsfiddle.net/d8j3o5sh/) when using a font declared with PIXI.BitmapFont.from(). I've set the `chars` value to the exact string used, a split array of that string and `PIXI.BitmapFont.ASCII` to no avail. Though I suspect the issue doesn't lie with `chars` given that punctuation is rendering [here](https://jsfiddle.net/bigtimebuddy/et2boa51/).

I _was_ able to [render punctuation](https://www.pixiplayground.com/#/edit/rLbAN_xrw7yUU_cg_c8Xv) with preloaded bitmap fonts, so I think the bug may be limited to the PIXI.BitmapFont.from() method.

~~In addition, wanted to flag that 6.0.0 seems to break bitmap fonts entirely (at least with the js fiddle example linked here -- I'm using 5.3.7 in the interim).~~

- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Chrome
- **OS & Version**: _e.g. macOS Catalina
- **Running Example**: https://jsfiddle.net/d8j3o5sh/

**Comment by bigtimebuddy** [comment]
The v6.0.0 breakage is not a bug, is that's `font` changed to `fontName` (notice the deprecation warning in the console).

```js
new PIXI.BitmapText("Hello-World", { fontName: "TitleFont" })
```

**Comment by gwezerek** [comment]
Aha! Ofc, makes sense.

**Comment by bigtimebuddy** [comment]
Punctation worked here. I think it's a problem with parsing the `chars` as a string. That seems like a bug.
https://jsfiddle.net/bigtimebuddy/et2boa51/6/

**Comment by bigtimebuddy** [comment]
Oh I see what it is. Fixed here: https://jsfiddle.net/bigtimebuddy/ah6pvm2o/

The problem is `chars` is part of the options, not style. http://pixijs.download/dev/docs/PIXI.BitmapFont.html#from

```js
BitmapFont.from(name, style, options)
```

**Comment by gwezerek** [comment]
Ahhhhhh, thank you! Appreciate the quick response.
