### ISSUE TITLE
Depth sorting issue

### ISSUE THREAD

**Issue by WDavidC** [pixijs/pixi.js#7134]
I was wondering if any body could help me.. Looking for an idea for sorthing child in the stage. 
Currently i have the map, mapObjects and the player on the stage working as well.

//let say room contain everythings going in the room, background, object, player
  let room = new PIXI.Container();
//start zsorting them
  room.children.sort((a, b) => {
     return (a.y < b.y);
  };

each children have zIndex with the position.
background = 1;
player = 2;
tree = 3;
object = 3; 

So i need another one zIndex  for object that are positioned > of another object but the player has to be behind it.
Sorry i might be bad for explain...

so now the thing is, a got a couple object going infront of other object but the player need to go behind of one and this one gotta stay infront of the other object. what should i do, if i want them to be sorted correctly

**Comment by SukantPal** [comment]
`Container` can sort its children:

```
// Sort children in transform updates (before rendering)
container.sortableChildren = true;
```

You'll need to set the zIndex of each child. The child with the larger zIndex is rendered over the ones with smaller z-indices.

```
// Set zIndex of child
child.zIndex = 1;
```

**Comment by ivanpopelyshev** [comment]
> but the player need to go behind of one and this one gotta stay infront of the other object

welcome to isometry hell. I had solution for those things but i didnt publish that :) just experiment with different formulas for z-index for now

**Comment by WDavidC** [comment]
They already got zIndex position, the thing is i gotta think about which conditions should i use, to say like.
Object right < Object center > Object Left
Object right and left should be behind the center object.
if the player go behind the left or right object he must be behind of both but not the center.

**Comment by SukantPal** [comment]
What you're describing is impossible. You can't be in front of something and behind something behind it.

Maybe you're doing something 3D (so you'd need to use 3D rendering) or else you'd need to break of the player. The part that is in front of the center is one piece and the rest is the other.

**Comment by WDavidC** [comment]
It's actually a 2D game engine with PIXIJS, hold maybe i didn't explain correctly.
https://www.noelshack.com/2021-01-7-1610252117-szor.png
Maybe you will unsterstand more with this picture, else if it not possible, what should i do instead ?

**Comment by SukantPal** [comment]
Okay, the only plausible situation I can interpret from what your saying:

You have two towers (left and right) surrounding the center structure. The center is above both the left and right towers. This makes two layers:

(zIndex = 0, Left and right towers)
(zIndex = 1, Center structure)

Now, the rabbit can have one zIndex. If it is in front of the center structure, it’s zIndex also greater than 1; that means it must be in front of the left and right towers. However, the rabbit can be **between** these two layers - you can set its zIndex to 0.5, then it will be behind the center and in front of the towers.

Sent from my iPad
