### ISSUE TITLE
Unable to animate using AnimatedSprite

### ISSUE THREAD

**Issue by Vivraan** [pixijs/pixi.js#7136]
### Expected Behavior
Player walking animation as in:

https://user-images.githubusercontent.com/12777564/104153882-7fc52f00-5409-11eb-83fd-a76aa05a7845.mp4

### Current Behavior
Player switching animations but not changing frames in:

https://user-images.githubusercontent.com/12777564/104153966-aaaf8300-5409-11eb-8e3f-d6ca85736b4e.mp4

Often, if I change the frame using `gotoAndPlay()`, the frame is set to this index in spite of emptying the cache while refreshing.

https://user-images.githubusercontent.com/12777564/104154122-1eea2680-540a-11eb-8df4-257ef5902bbe.mp4

### Possible Solution
https://gitlab.com/Vivraan/mario50-pixijs/-/blob/227a18672242d9c468274e6a50c53cff1adda7f2/player.js#L63-73
```js
        const move = (dt) => {
            if (this._vx != 0) {
                this._anim.textures = animations.walking
                if (!this._anim.playing) {
                    this._anim.play()
                }
                this._anim.scale.x = Math.sign(this._vx)
            } else {
                this._anim.textures = animations.idle
            }
        }
```

### Steps to Reproduce
I raised this issue as a question rather than a bug report. The commit I'm working from is [this one](https://gitlab.com/Vivraan/mario50-pixijs/-/commit/227a18672242d9c468274e6a50c53cff1adda7f2), which summarises the repro steps.

### Environment

- **`pixi.js` version**: ^5.3.7
- **Browser & Version**: MS Edge 84.0.522.52 (Chromium)
- **OS & Version**: Windows 10 20H2 19042.685
- **Running Example**: [Repo in GitLab](https://gitlab.com/Vivraan/mario50-pixijs)

**Comment by ivanpopelyshev** [comment]
Usually I recommend people to copy AnimatedSprite and change it the way you want, because its very stupid basic animation for helloworlds. We have no editor for it, we accept easy changes if they dont ruin already coded games.

Even in my plugin https://github.com/gameofbombs/pixi-heaven I and @finscn moved Animation away so it can be changed and applied to Sprite/TilingSprite/Mesh/Rope/Whatever

Other members of pixijs team might feel different about this class

**Comment by bigtimebuddy** [comment]
@Vivraan  I think your logic for `move` incorrectly calls _every_ frame. This mean that it's constantly setting `textures` on your animation frame after frame. If you cache the previous direction to only handle changes, it's better.

Here's an isolated example (click on the character on the right and then use the left and right arrow keys to see the animation switch). https://jsfiddle.net/bigtimebuddy/qo12kdnj/

This is not a limitation of the AnimatedSprite. In your case, this is an appropriate use.

Also, for questions (not bugs) please post to the Discussion section Q&A instead. Thanks!

**Comment by Vivraan** [comment]
> @Vivraan I think your logic for `move` incorrectly calls _every_ frame. This mean that it's constantly setting `textures` on your animation frame after frame. If you cache the previous direction to only handle changes, it's better.
> 
> Here's an isolated example (click on the character on the right and then use the left and right arrow keys to see the animation switch). https://jsfiddle.net/bigtimebuddy/qo12kdnj/
> 
> This is not a limitation of the AnimatedSprite. In your case, this is an appropriate use.
> 
> Also, for questions (not bugs) please post to the Discussion section Q&A instead. Thanks!

Yeah, I just got acquainted with Discussions recently. Will keep this in mind. Thanks - I'll see if I can't get this working.

**Comment by bigtimebuddy** [comment]
Awesome, will close this issue. Good luck with your project!

**Comment by Vivraan** [comment]
> Awesome, will close this issue. Good luck with your project!

Hey I just tried your solution but I still can't get it to work.
Should I raise this in Discussions?

**Comment by bigtimebuddy** [comment]
Yes, a discussion is good for this.

**Comment by Vivraan** [comment]
I've tagged you in the Q&A section. I suppose I need to do more work on this.

**Comment by Vivraan** [comment]
Please check out https://github.com/pixijs/pixi.js/discussions/7144! Haven't seen any responses there!

**Comment by bigtimebuddy** [comment]
I see your tagging. I unfortunately cannot help you debug your project at the moment, sorry. Hopefully someone else will be able to chime in. Good luck and keep at it, I'm sure you'll figure it out.
