### ISSUE TITLE
Missing geometries on Graphics on MacOS Chrome

### ISSUE THREAD

**Issue by Kurtil** [pixijs/pixi.js#7153]
[jsfiddle example here.](https://jsfiddle.net/GaetanLagier/w5hfmc6r/8/)

Quick preview:
![e618fc1504441944c6fe21c556e04d49](https://user-images.githubusercontent.com/22523482/104627025-d09d8780-5696-11eb-8766-77d8bb056176.gif)

### Steps to reproduce

- Initial state:
<img width="284" alt="Screenshot 2021-01-14 at 18 35 33" src="https://user-images.githubusercontent.com/22523482/104627432-4c97cf80-5697-11eb-8e32-b62da411ee12.png">
- Click on "Draw on canvas 2". A red square appears on the little black canvas.
<img width="286" alt="Screenshot 2021-01-14 at 18 36 38" src="https://user-images.githubusercontent.com/22523482/104627548-72bd6f80-5697-11eb-8f85-da9c70f02b14.png">
- Click on "Redraw canvas 1". Some green squares disappear.
<img width="281" alt="Screenshot 2021-01-14 at 18 38 05" src="https://user-images.githubusercontent.com/22523482/104627693-a7312b80-5697-11eb-8159-b8142ac187fa.png">

### Expected Behavior
The green squares must not disappear.

### Current Behavior
Some green squares disappear.

### What the code does.
On the big canvas, 12_000 squares are drawn (`graphics.drawRect`) using a single Graphics. Then, something is drawn on the other canvas using another Graphics. If we try to rerender the graphics with 12_000 squares on the big canvas calling `renderer.render(graphics)`, some squares are missing.

The issue comes from the large number of squares drawn.

This only appears on MacOS and Chrome ONLY for PIXI v5.3.X and 6.X.

### Does not work on:
Chrome 87.
PIXI v5.3.7.
MacOS 10.15.7.

### Works on:
Windows 10 Chrome 87 Firefox 85 
Linux UBUNTU 20.04 Chromium 87 Firefox 84

### Old versions of PIXI

On v5.2.X, the issue is directly present on the other browsers and other OS. The initial state is the following:

<img width="284" alt="Screenshot 2021-01-14 at 18 45 24" src="https://user-images.githubusercontent.com/22523482/104628571-acdb4100-5698-11eb-8236-cac8e62863b0.png">

**Comment by ivanpopelyshev** [comment]
That's an interesting issue!

**Comment by Kurtil** [comment]
Can no longer be reproduced on chromium M-90 # 90.0.4395.0. 🎉
