### ISSUE TITLE
No event bubbling for pointer events

### ISSUE THREAD

**Issue by soletan** [pixijs/pixi.js#7156]
### Expected Behavior

In a container assumed to contain tons of display objects (e.g. 10k sprites) I'd like to monitor pointer hovering any DO using a single event handler instead of having separate handler for every such DO. Thus, I'd like to listen to `pointerover` and `pointerout` on container level assuming either sprite's events are bubbling up.

### Current Behavior

While it's possible to listen for `pointerover` and `pointerout` per sprite, there is very limited support for doing so on container level. `pointerover` and `pointerout` are available at container unless pointer is leaving one DO and instantly entering another one. In that case there is no event fired at all. I'd expect to get a `pointerout` for the left DO and another `pointerover` for the instantly entered DO, instead.

### Steps to Reproduce

See this [fiddle](https://jsfiddle.net/soletan/mLer67th/68/). When moving pointer/mouse over green or red box, the directly attached handler is always responding (lines 2 and 3 of on-screen text display). Listeners attached to the container fail when moving pointer/mouse from either box to the other one directly (first line of on-screen text display).

### Environment

- **`pixi.js` version**: _6.0.0-rc.2_ (initially encountered in a more complex project with 5.3.7 as well)
- **Browser & Version**: _Firefox 84.0.2_ (6.0.0-rc.2) as well as Chrome 87.0.4280.141 (5.3.7)
- **OS & Version**: _Windows 10_
- **Running Example**: _https://jsfiddle.net/soletan/mLer67th/68/_

**Comment by SukantPal** [comment]
This is a bug, I think `pointerover` and `pointerout` are not bubbled since they are handled within the `pointermove` from the canvas:

https://github.com/pixijs/pixi.js/blob/99d5d41d9e93135b3385c8f3640be6149722756b/packages/interaction/src/InteractionManager.ts#L1594

This can be fixed in #7071

**Comment by SukantPal** [comment]
The Federated Events API will be released in PixiJS 6.1.0; the `pointerover` and `pointerout` events should bubble up to common ancestor of the pointer over/out targets. The newly introduced `pointercapture` and `pointerleave` events have the old semantics and won't bubbling (matching the browser's Pointer Events API)
