### ISSUE TITLE
glsl shader problem

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixi.js#7162]
glsl shader problem
![image](https://user-images.githubusercontent.com/1198840/104882410-06e04d00-599e-11eb-9c9e-f9cfa3e28c0f.png)
opacity 0 is not avalible
    gl_FragColor = vec4(1.0,0.3,0.3,0.0);

**Comment by JetLua** [comment]
https://github.com/pixijs/pixi.js/issues/6542#issuecomment-612472089

> if you have fg.rgb and fg.a = 1.0 to make it 0.5 you have to multiply whole fg
> fg *= 0.5;

**Comment by SukantPal** [comment]
PixiJS uses premultiplied alpha. Hence, your color's RGB channel must be multiplied by the alpha. If alpha is zero, it is impossible for a premultiplied color to have RGB ≠ 0, 0, 0.
