### ISSUE TITLE
why has white？？

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixi.js#7163]
![image](https://user-images.githubusercontent.com/1198840/104899623-0c499180-59b6-11eb-8905-4b54a6e62b9c.png)
![image](https://user-images.githubusercontent.com/1198840/104899683-1ec3cb00-59b6-11eb-9943-c3f772b42597.png)
![image](https://user-images.githubusercontent.com/1198840/104899721-284d3300-59b6-11eb-88ea-0d8398524b2a.png)
why has white？？

**Comment by SukantPal** [comment]
Your question is not clear. Please post questions in the Discussions tab. Also, a full reproduction on [CodePen](https://codepen.io/) or [Repl.it](https://repl.it/) (for larger repros) would help us find your mistake.

One explanation for the white color could be that the noise texture contains white pixels that aren't full white (i.e. not RGB 255, 255, 255 but may 250, 250, 250).

**Comment by a6965921** [comment]
> Your question is not clear. Please post questions in the Discussions tab. Also, a full reproduction on [CodePen](https://codepen.io/) or [Repl.it](https://repl.it/) (for larger repros) would help us find your mistake.
> 
> One explanation for the white color could be that the noise texture contains white pixels that aren't full white (i.e. not RGB 255, 255, 255 but may 250, 250, 250).

I want  white change to black use shader glsl ,

**Comment by a6965921** [comment]
i sure that  is full white

**Comment by ivanpopelyshev** [comment]
Did you by any chance enabled mipmapping (search "mipmap" in your code) ?

Otherwise it looks like linear interpolation problem, "texture2D" doesnt actually return a pixel from texture, it interpolates 4 pixels into one color

**Comment by a6965921** [comment]
i don't know that how to let white change to black

**Comment by SukantPal** [comment]
Try this

```glsl
tex1 = vec4(0., 0., 0., 1.);
```
