### ISSUE TITLE
DisplayObjects added to a "cacheAsBitmap" Container can trigger interaction without transforms applied

### ISSUE THREAD

**Issue by cnewtonvgw** [pixijs/pixi.js#7167]
Scenario: I have a container that is currently `cacheAsBitmap=true`, some child of that container is interactive (pointertap). This works fine. However sometimes a new child is added to that container while it is still `cacheAsBitmap=true`. This triggers what I believe to be a bug where the new object can trigger interaction at the screen origin (top left corner). From inspection it looks to be because the transform/worldTransform of the newly added element is not updated.

### Expected Behavior
Newly added element either doesn't trigger interaction until it is actually rendered once (parent `cacheAsBitmap=false`) or transforms are correctly applied and interaction only occurs in the location the new element *would be*.

### Current Behavior
Interaction occurs in the top left corner of the screen.

### Possible Solution
Somehow force transform updates when adding an element to a `cacheAsBitmap=true` parent (or perhaps any cached ancestor?)
Otherwise maybe skip hit detection on elements that have never been rendered.

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/3lpZtMOdUU_Yi8d7nbWn7

### Environment

Pixi.js v5.3.7

**Comment by bigtimebuddy** [comment]
I think the expectation with `cacheAsBitmap` is that you wouldn't be modifying the display-tree to something where when enabled. That property is available as an _optimization_ to prevent rendering of children, including transforms. It's not surprising that you'd get some unintended results trying to use it that way. I would say that this isn't a bug and is more likely undefined/undesirable behavior.

Easiest solution is to toggle `cacheAsBitmap` off, add the child, and then re-enable `cacheAsBitmap`.

**Comment by cnewtonvgw** [comment]
I expected as much, was just hoping there was some simple-ish way to avoid the undesirable behavior that could be implemented in PIXI.
For my use case the `cacheAsBitmap` is not being used as an optimization but rather a "hacky" way of implementing an AlphaFilter for the CanvasRenderer. 
I have opted to simply set `interactiveChildren=false` while `cacheAsBitmap=true`.

Thanks for your time.

**Comment by bigtimebuddy** [comment]
No problem. I'm closing this issue, seems like you found a suitable solution.
