### ISSUE TITLE
vTextureCoord not normalized

### ISSUE THREAD

**Issue by Dunnings** [pixijs/pixi.js#7184]
### Expected Behavior
 vTextureCoord provides normalized UVs between 0 and 1.

### Current Behavior
It appears as though vTextureCoord is normalized according to the canvas size, not the object.

### Steps to Reproduce
1. Create a filter
2. Attach the filter to a graphics object
3. Use vTextureCoord in the shader

### Environment
- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Chrome 87.0.4280.141
- **OS & Version**: Ubuntu 18.04
- **Running Example**: https://codepen.io/dunnings/pen/QWKoRQL

**Comment by Dunnings** [comment]
This issue is not exclusive to Graphics objects, it also happens with sprites: [https://codepen.io/dunnings/pen/LYRaKzM](https://codepen.io/dunnings/pen/LYRaKzM).

**Comment by ivanpopelyshev** [comment]
vTextureCoord uses input coords, not filter coords. 
That's because PixiJS uses temporary pow2-sized texture to handle filters.

You have to use conversion functions:
https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters

Look in source of DisplacementFilter for example

**Comment by SukantPal** [comment]
vTextureCoord is normalized in the 0-1 range. However, the filter doesn't run over the whole texture. The filter texture is larger than the object itself; it's size is the next power of 2.

**Comment by Dunnings** [comment]
Okay, so using a mixture of _vTextureCoord_, _inputPixel_ and uniform _dimensions_, I have achieved what I wanted to do (have a vec2 of the normalized pixel coordinates.

`vec2 normalizedCoords = vTextureCoord.xy * inputPixel.xy / dimensions.xy`

Have updated the CodePen ([https://codepen.io/dunnings/pen/QWKoRQL](https://codepen.io/dunnings/pen/QWKoRQL)) and will close this issue.

Thanks, @SukantPal & @ivanpopelyshev 👍
