### ISSUE TITLE
InteractionManager is bundled AND adds add a ticker without importing or enabling interactions

### ISSUE THREAD

**Issue by lazarljubenovic** [pixijs/pixi.js#7186]
### Expected Behavior

No modules that I don't need are loaded. No listeners that I don't need are added.

### Current Behavior

Just creating the most basic example listens to `pointermove` and spawns a ticker and runs it on every frame.

### Possible Solution

I tried tracing the calls to the `Ticker()` constructor, since I don't call it anywhere from my application. It seems like it's called as a side-effect of simply importing `pixi` itself. I was under the impression that `Ticker` and `Interaction` are plugins and shouldn't be imported if I don't explicitly enable them (or implicitly use them as part of `Application`). But I _especially_ didn't expect any of them to actually _do_ something, let alone on every frame, simply by importing anything from `pixi.js`.

### Steps to Reproduce

```ts
import * as PIXI from "pixi.js";

var renderer = new PIXI.Renderer({
  width: window.innerWidth,
  height: window.innerHeight,
  backgroundColor: 0xff0000
});
document.body.appendChild(renderer.view);

var stage = new PIXI.Container();
var graphics = new PIXI.Graphics();
graphics.beginFill(0x00ff00);
graphics.drawCircle(50, 50, 400);
stage.addChild(graphics);
renderer.render(stage);
```

Open https://stackblitz.com/edit/typescript-njrxer. Ignore the TypeScript errors, seems like a problem with StackBlitz. TypeScript is irrelevant for the issue.

In developer tools, you'll see these calls.

![image](https://user-images.githubusercontent.com/7661457/105214998-05a35180-5b51-11eb-8be1-2dbab3b8a212.png)

The middle blue ones are:

- `InteractionManager.onPointerMove`,
- `InteractionManager.configureInteractionEventForDOMEvent`,
- `getBoundingClientRect`

### Environment

- **`pixi.js` version**: 6.0.0-rc.2
- **Browser & Version**: all
- **OS & Version**: all
- **Running Example**: https://stackblitz.com/edit/typescript-njrxer

**Comment by bigtimebuddy** [comment]
Couple of things to clarify:
* If you install **pixi.js**, this has all the plugins and packages installed, including interaction on the Renderer. If you don't want that, you should checkout https://pixijs.io/customize to select only the packages you want.
* Ticker is a dependency of core and is required for a number of internal things. There are two global tickers `PIXI.Ticker.system` (used by interaction and base prepare, and `PIXI.Ticker.shared` used by VideoResource and AnimatedSprite to advance playback. It's more standard use a Ticker that is enabled and runny by default, but if you don't want these on by default, simply call `stop()` on both tickers ([docs here](http://pixijs.download/dev/docs/PIXI.Ticker.html#shared)).
* InteractionManager's use of system ticker can also be turned off `renderer.plugins.interaction.useSystemTicker = false`, this means that you manually will tick use `tickerUpdate()`.

**Comment by lazarljubenovic** [comment]
Thanks a lot; this answers all my question, I think. I'll check it out soon and close the issue here with the exact code that I ended up with for future reference.

**Comment by lazarljubenovic** [comment]
There we go: https://stackblitz.com/edit/typescript-gw2zyx. Now there's nothing running. Note that `@pixi/display` is what exports `Container`, which is surprisingly (in a positive way) not part of `@pixi/core`.

It might be a good idea to create `@pixi/common` which would re-export the five almost-certainly-always-required packages apart from `@pixi/core`:

- `@pixi/constants`,
- `@pixi/math`,
- `@pixi/ticker`,
- `@pixi/settings`,
- `@pixi/runner`.

Has this idea been discussed before?

Either way, my original issue has been solved. Thanks again for the help big time, buddy. :smile:
