### ISSUE TITLE
why use forcanvas  show webgl？

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixi.js#7191]
why use forcanvas  show webgl？
![image](https://user-images.githubusercontent.com/1198840/105319054-448fe080-5bff-11eb-9c0e-f0853a1d85d7.png)
![image](https://user-images.githubusercontent.com/1198840/105319076-4d80b200-5bff-11eb-8d80-3e127e51b55a.png)

**Comment by lazarljubenovic** [comment]
From the docs:

> prevents selection of WebGL renderer, even if such is present, this option only is available when using `pixi.js-legacy` or `@pixi/canvas-renderer` modules, otherwise it is ignored.

**Comment by lazarljubenovic** [comment]
Are you sure it gets loaded before you call `new Application`? Please create a reproduction.

**Comment by a6965921** [comment]
is resolv thank
