### ISSUE TITLE
shader problem

### ISSUE THREAD

**Issue by a6965921** [pixijs/pixi.js#7194]
https://codepen.io/a6965921/pen/RwGOyRr
why show white 
![image](https://user-images.githubusercontent.com/1198840/105380137-85601780-5c48-11eb-8d5a-83e3f0310c05.png)

**Comment by Dunnings** [comment]
https://github.com/pixijs/pixi.js/issues/7163

**Comment by Dunnings** [comment]
Repost of your previous issue with even less information than the first time. GitHub issues is not StackOverflow. The problem here is to do with your fragment shader code, not a fault with pixi.js.

original issue: https://github.com/pixijs/pixi.js/issues/7163
