### ISSUE TITLE
How to capture ClipboardEvent in Pixi?

### ISSUE THREAD

**Issue by mirusky** [pixijs/pixi.js#7197]
### Expected Behavior

Some way in my stage or sprites possible to capture paste events.

### Current Behavior

Now I'm capturing paste events from the 'document' in JS. But isn't easy to pass to PIXI when the event occur

### Possible Solution

In pixi event handler, add suport to ClipboardEvent to be able to use something like this:

```TS
app.stage.on('paste', (ev) => {
    console.log('very useful funcionality');
});
```

### Environment

- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Chrome 87.0
- **OS & Version**: Win10

**Comment by ivanpopelyshev** [comment]
In PixiJS we have special method that allows you to capture paste!

```js
document.addEventListener('paste', (e) => {
    const clipboardData = e.clipboardData
    const pastedData = clipboardData.getData('Text');
    
    // now find which element was focused in your stage, and paste that stuff there.
});
```

How to do focus? Modify InteractionManager or TreeSearch that way it remembers which element was clicked on last time.
How to find the part of text to paste into? You have to write your own TextField that allows to determine where in the string did you click.

**Comment by bigtimebuddy** [comment]
I'm going to close this issue. It is not a specific bug or issue with Pixi. If you want more general advice, please open a discussion instead.
