### ISSUE TITLE
Screen Responsiveness.... Is there a fixed base function on Pixi.js?

### ISSUE THREAD

**Issue by inglesuniversal** [pixijs/pixi.js#7203]
I have tried pixi.js on and off and even though it is an awesome library, I always find it hard to get started due to a single issue.

Most tutorials start by showing how do draw a small square with an image inside a black canvas.

Is there a prebuilt function I can use from the start that can make my canvas fill the entire screen and keep the content in place and in the same area of the screen regardless if I turn my, lets say (iphone or ipad) from portrait to landscape mode?

Thanks so much for your amazing work.

PS: Is there a newer tutorial online available, the one included is based on version 4. #StaySafe

**Comment by ivanpopelyshev** [comment]
> Is there a prebuilt function I can use from the start that can make my canvas fill the entire screen and keep the content in place and in the same area of the screen regardless if I turn my, lets say (iphone or ipad) from portrait to landscape mode?

No, its usually exercise to learn `resize` and what is Transform. The problem is that all implementations of that thing we saw were slightly off and so we couldnt add them to pixi and recommend as official :( Its always bucked up somewhere.
