### ISSUE TITLE
Safari + SVG with embedded image yields invalid baseTexture

### ISSUE THREAD

**Issue by johnv-git** [pixijs/pixi.js#7204]
### Expected Behavior

SVG with embedded **image** tags should fully render and display in the canvas.  Works on Chrome/FF, but fails on Safari.

### Current Behavior

SVG partially renders, generally omitting all SVG **image** tags.

### Possible Solution

If you wait for texture.baseTexture.valid == true, then texture.baseTexture.destroy(), then create a new texture everything works.  I suspect this means a Safari webkit bug where it claims the asset is fully loaded before it actually is.  Then pixi creates a texture based on a half-baked DOM asset.

Once the asset is in cache, creating textures works correctly.

Note that merely creating a new texture (from the same baseTexture) does NOT work.  I interpret this to mean the baseTexture itself is incorrect.

### Steps to Reproduce

Load the example url.  The clouds are SVG **paths**; they should render.  The sun is an SVG **image**; it does not render.
Click RUN to load a second time: this time it works (likely because the asset is now in cache).

You need to physically exit Safari between runs to exhibit the bug.  Clearing cache is not sufficient.

### Environment

- **`pixi.js` version**: 5.X (tested on 5.2.0, 5.3.7, 6.0.0-rc2)
- **Browser & Version**: Safari 13.2.1, Safari 14.x
- **OS & Version**: MacOS
- **Running Example**: https://jsfiddle.net/anonymousweasel/gc8x6twr/

**Comment by bigtimebuddy** [comment]
That's a new one! Thanks for reporting @johnv-git.

Here's the reproduction without PixiJS (but using the same approach): https://jsfiddle.net/bigtimebuddy/unxjb8t6/ I was able to verify this on macOS Safari 14.

This seem to be a Safari specific issue, I'd suggest [filing a bug with Apple](https://www.apple.com/feedback/safari.html) though not sure exactly if that'll get addressed.

Can you see if you can find a way to get this to work correctly in Safari with `drawImage` (like in the example). If so we could probably try to find some mitigation.

**Comment by johnv-git** [comment]
Submitted to Safari.

Here's the work-around I'm currently using, but I suspect it might be vulnerable to a race condition (where baseTexture.valid, but the underlying DOM object is not done loading).

`
    /**
     * This should wait until the texture is loaded before continuing to sprite construction. 
     * But... it doesn't work on Safari.
     */
    async loadTexture(): Promise<void> {
        this.texture = await PIXI.Texture.fromURL(this.svgPath);
    }

    /**
     * Textures need to be loaded before the Sprite is usable.  This allows the caller to wait
     * for textures loaded / sprites created before showing the sprites.
     */
    getOnLoadPromise(): Promise<void> {
        return new Promise(async (resolve, reject) => {
            // wait for the texture to load
            await this.loadTexture();
            // then create the sprite
            if (this.texture.baseTexture.valid) {
                // TODO - Safari baseTextures claim to be valid but they are not fully loaded
                if (/^((?!chrome|android).)*safari/i.test(navigator.userAgent)) {
                    console.log("forcing asset reload for safari");
                    // explicitly force a reload of the baseTexture
                    this.texture.baseTexture.destroy();
                    // and recreate it
                    await this.loadTexture();
                }
                this.createSprite();
                resolve();
            } else {
                console.error("failed to load texture", this.svgPath);
                reject();
            }
        });
    }
`

**Comment by bigtimebuddy** [comment]
I'm going to close this bug, as this is not something we'll fix since it's a Safari bug. Thank you for the workaround though for folks that bump into this issue.
