### ISSUE TITLE
Minimum package, should not output map

### ISSUE THREAD

**Issue by lzxb** [pixijs/pixi.js#7208]
![image](https://user-images.githubusercontent.com/8424643/105954574-d42a0900-60af-11eb-826a-0f447d7562eb.png)

**Comment by bigtimebuddy** [comment]
What's the problem exactly? Don't deploy the map file if you don't need it.

**Comment by lzxb** [comment]
Page access, which causes the browser to try to send this request

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/106076109-de98e100-6149-11eb-8ac6-8f8988deb39e.png)

**Comment by bigtimebuddy** [comment]
Understood however source maps are only downloaded if DevTools is open. Your users will not pay a network request tax for these. Debugging in production is useful and we will not be removing source maps from minified builds. Consider stripping them using webpack, if you'd like (not sure the specifics of that, but I think it's possible).

**Comment by lzxb** [comment]
In the production environment, we will use CDN to introduce, which will also lead to this problem

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/106220283-1c633b80-6216-11eb-9824-eb2a1d8a2442.png)

Webpack build time packaging does not use the minimum package.
The mapping file should be removed from the`pixi.min.js` file

**Comment by lzxb** [comment]
Using CDN directly can cause problems
https://unpkg.com/browse/pixi.js@5.3.7/dist/pixi.min.js

![image](https://user-images.githubusercontent.com/8424643/106220551-b925d900-6216-11eb-8e6d-f9cd045f598d.png)

**Comment by bigtimebuddy** [comment]
I'm going to close this issue. We are not interested in removing sourceMapping for minified files. If you don't like this, use Webpack or another build tool to remove it.
