### ISSUE TITLE
Multiple Renderer objects / possible packaging issue

### ISSUE THREAD

**Issue by adrianioancozma** [pixijs/pixi.js#7209]
### Description

I have a React application that uses pixi.js for a Gantt chart. The initialisation, which worked until `pixi.js 5.3.3` is:

```
let app = new PIXI.Application()
document.getElementById(htmlElementId).appendChild(app.view)
app.renderer.plugins.interaction.interactionFrequency = 30
```

Starting from `pixi.js 5.3.4` up until `5.3.7` the app is crashing at line 3, with `app.renderer.plugins` being `undefined`. 

### Expected Behavior

The renderer object inside a new app object should be initialised, and have a plugins list as advertised in the documentation.
```
let app = new PIXI.Application()
assert(app.renderer.plugins !== undefined)
``` 

### Possible Solution

Starting from `5.3.4`, some modules inside `[PROJECT]/node_modules/@pixi/` began to have their own `node_modules/` subdirectories. E.g.

- `@pixi/accesibility/node_modules`
- `@pixi/app/node_modules`
- `@pixi/display/node_modules`
- `@pixi/extract/node_modules`
- `@pixi/filter-color-matrix/node_modules`
- `@pixi/filter-displacement/node_modules`
- `@pixi/filter-fxaa/node_modules`
- `@pixi/filter-noise/node_modules`
- `@pixi/graphics/node_modules`
- `@pixi/interaction/node_modules`
- `@pixi/loders/node_modules`
- `@pixi/mesh/node_modules`
- `@pixi/mesh-extras/node_modules`
- `@pixi/mixin-cache-as-bitmap/node_modules`
- `@pixi/mixin-get-child-by-name/node_modules`
- `@pixi/mixin-get-global-position/node_modules`
- `@pixi/particles/node_modules`
- `@pixi/polyfill/node_modules`
- `@pixi/prepare/node_modules`
- `@pixi/sprite/node_modules`
- `@pixi/sprite-animated/node_modules`
- `@pixi/sprite-tiling/node_modules`
- `@pixi/spritesheet/node_modules`
- `@pixi/text/node_modules`
- `@pixi/text-bitmp/node_modules`

I have noticed that at react application startup, triggered by webpack, the Renderer object that is properly initialised with plugins by `Renderer.registerPlugin` and has a `Renderer.__plugins` property comes from
```
[PROJECT]/node_modules/pixi.js/node_modules/@pixi/core/lib/core.es.js
```
while the Renderer object used by the Application initialisation in
```
function Application(options) @ [PROJECT]/node_modules/@pixi/app/lib/app.es.js
```
comes from
```
[PROJECT]/node_modules/@pixi/app/node_modules/@pixi/core/lib/core.es.js
```

I suspect there is a packaging issue that duplicates the sourcse/modules, having multiple Application and Renderer objects, some initialised, some not. The diff in `package-lock.json` seems to point to it.

![Screenshot 2021-01-28 at 14 16 59](https://user-images.githubusercontent.com/2982742/106137565-8bd41f00-6173-11eb-82f7-78f671b1a539.png)

#### Temporary workaround

```
let app = new PIXI.Application()
app.renderer.destroy()
app.renderer = new PIXI.Renderer()
```
corrects the issue, probably because the call in line 3 uses the topmost `core.js` which has the Renderer object initialised by the webpack call.
Still, the behaviour does not match the documentation.

### Environment

- **`pixi.js` version**: _5.3.4 +_
- **`npm` version**: _6.14.11_
- **Browser & Version**: _any_
- **OS & Version**: _macos 11_ 

Thank you!

**Comment by bigtimebuddy** [comment]
Yikes. This is likely because of a borked upgrade. Try removing/uninstalling all packages so there are no references in your package-lock and reinstall Pixi.

**Comment by adrianioancozma** [comment]
I've done all of that. Multiple times. This time I've also removed package-lock. Thanks.
