### ISSUE TITLE
Loading asset with same name, why is error thrown instead of invoking onError callback

### ISSUE THREAD

**Issue by kamcknig** [pixijs/pixi.js#7214]
More of a question of intension or not and maybe an explanation of why.

When loading an asset twice with the same name the Loader.add method throws an error.

### Expected Behavior
When loading an asset twice with the same name, the Loader.onError callback will be invoked

### Current Behavior
When loading an asset twice with the same name the Loader.add method throws an error.

### Possible Solution
Catch the error and invoke the onError callback

### Steps to Reproduce
load an asset with the same name twice and note you cannot catch the error with the onError callback method.

### Environment
N/A

- **`pixi.js` version**: 5.3.7

**Comment by bigtimebuddy** [comment]
Could you please provide an example? That would be helpful trying to figure out what's happening.

**Comment by kamcknig** [comment]
@bigtimebuddy 

Sure, assuming you've set up the most basic PIXI app set up to go:

```
this._loader.onError.add(err => { console.log('This handler doesn't get called on the second invocation of someFunction')});
someFunction();
someFunction();

someFunction(): void {
  try {
    this._loader.add([
      'assets/images/playing-cards.json',
      'assets/images/playing-card-back.json'
    ]).load(() => {
      console.log('you'll get this message the first time the method is run');
    });
  }
  catch (e) {
    console.log('you'll get this in the catch block the 2nd time rather than the error handler setup earlier')
  }
}
```

Then you'll get the error logged from teh catch block on the console

![2021-01-31 13_59_22-BoardGameBuilder](https://user-images.githubusercontent.com/705490/106394823-9f2df700-63cc-11eb-9954-d472883e0f88.png)

**Comment by bigtimebuddy** [comment]
This is behaving correctly. If you're trying to reuse a loader after loading once, call `loader.reset()`. This will clear any assets. The `onError` handler is generally for
network errors, like 404s. One of the design constraints of loader is you cannot two resources with the same URL.

**Comment by kamcknig** [comment]
I see, the `_loader` instance I'm using is the one that comes from new Application().loader. Is that still intended? That one should use reset afterward? Are the previous textures in that main loader instance then stored in the TextureCache?

**Comment by bigtimebuddy** [comment]
Loader holds on to resources after they have been loaded(in addition to the texture caches). Is okay to reset after you're done loading to remove those references and load more.
