### ISSUE TITLE
pixi.js-legacy error on Application start

### ISSUE THREAD

**Issue by Vardner** [pixijs/pixi.js#7219]
I am trying to launch my application using the pixi.js-legacy package and I've run into a strange error. When I launching the package downloaded from the npm, it gave me an error "displayObject.renderCanvas is not a function". Despite this fact, when I am launching the same code at your webpage with pixi examples, everything works great without errors. After this discovery I copied pixi.js-legacy code from examples web page and paste it instead URL at package and everything works great also.
Myabe you can found the source of this strange behavior

### Steps to Reproduce
To reproduce what I've done you can compare running your Container example with "forceCanvas" option and you won't see any errors in console. Then open this example's console and you will see "renderCanvas" error
My test with error: https://codepen.io/Vardner/pen/LYbVzzr
Yours examples where you have to enable "forceCanvas": https://pixijs.io/examples/#/demos-basic/container.js
### Environment
- **`pixi.js` version**: 5.3.7; 5.2.5; 6.0.0-rc.2
- **Browser & Version**: _e.g. Chrome 85_
- **OS & Version**: _e.g. Windows 10
- **Running Example**: https://codepen.io/Vardner/pen/LYbVzzr

**Comment by SukantPal** [comment]
@bigtimebuddy I think this might be related to using browser ES-modules.

**Comment by Vardner** [comment]
> @bigtimebuddy I think this might be related to using browser ES-modules.

I get the same result building my application through webpack

**Comment by bigtimebuddy** [comment]
@Vardner We could use a reproduction of this as a standalone repo we can test locally (without that CDN, using node_modules only). I don't know what that CDN is doing to create that build of pixi or how it's pulling it.

**Comment by Vardner** [comment]
@bigtimebuddy ok, I will make it at the weekend

**Comment by JestDotty** [comment]
Oddly having the same problem with a new project right now (on pixijs version 5.3.7)

I have a project I built 9 months ago hosting statically (it used pixijs 5.2.1) and it used to work with my OS and browser and now it no longer does (Manjaro, Vivaldi, no hardware changes).
The pixijs v5 examples on the website work (but does that mean it's webgl? it was said 5 doesn't "fallback"). I used the CDN and copy pasted one example into a html file and ran it, and it thinks I don't support WebGL which is odd.

I used this website to check if webgl works independent of pixi: https://get.webgl.org

I am on Manjaro 20.2.1. I downloaded some extra browsers to test:

| | vivaldi (3.6.2165.34) | firefox (85.0 64 bit) | chromium (87.0.4280.141) |
| - | - | - | - |
| pixijs 5 examples | yes | yes | yes |
| CDN 5.1.3  copied example html file | no webgl | no webgl | yes |
| new 5.3.7 project | no webgl | no webgl | yes |
| old 5.2.1 project | no webgl | no webgl | yes |
| webgl demo | yes | yes | yes |

In pixijs 5 examples @ firefox the console oddly warns "WebGL context was lost." from utils.js:126:36, but the demos work fine anyway.

**Comment by Vardner** [comment]
@bigtimebuddy I was trying to make a reproduction, but my attempts were unsuccessful. I've deleted package-lock.json at my project, reinstalled npm packages, and everything works ok :/ I think for now the issue can be closed
