### ISSUE TITLE
Too strict TypeScript type for second argument of Mesh constructor

### ISSUE THREAD

**Issue by lazarljubenovic** [pixijs/pixi.js#7229]
### Expected Behavior

The following code works, and is based on https://pixijs.io/examples/#/mesh-and-shaders/triangle.js

```ts
this.shader = pixi.Shader.from(vert, frag, uniforms)
this.quad = new pixi.Mesh(this.geometry, this.shader)
```

### Current Behavior

TypeScript complains that 

```text
TS2345: Argument of type 'Shader' is not assignable to parameter of type 'MeshMaterial'.
  Type 'Shader' is missing the following properties from type 'MeshMaterial': uvMatrix, batchable, pluginName, _tintRGB, and 7 more.
```

### Possible Solution

Seems like the type of the second argument should be relaxed. It currently accepts `MeshMaterial`, but a `Shader` works as well, at least according to the demo.

### Workaround

As usual, just do a cast.

```ts
this.quad = new pixi.Mesh(this.geometry, this.shader as MeshMaterial)
// or
this.quad = new pixi.Mesh(this.geometry, this.shader as any)
```

### Environment

- **`pixi.js` version**: 6.0.0-rc.2 (using separate packages, not `pixi.js`)
- **Browser & Version**: irrelevant
- **OS & Version**: irrelevant
- **Running Example**: can't create a proper reproduction anywhere because of TypeScript, I can create a repository if needed but it should be trivial to reproduce

**Comment by bigtimebuddy** [comment]
Fix was merged for this. Should be in rc.3 now.
