### ISSUE TITLE
Text artifacts (and solution)

### ISSUE THREAD

**Issue by JaapLatour** [pixijs/pixi.js#723]
When adding text to my project I noticed there are some artifacts in Chrome on a couple of characters in certain fonts (in this case Arial). 

Note the letter V has a small artifact at the bottom:
![bad](https://cloud.githubusercontent.com/assets/7429066/2817299/92bd9868-ced7-11e3-84db-4f7dbb1894a5.PNG)

There is an easy fix however:
Simply add

```
 this.context.lineCap = 'round';
 this.context.lineJoin = 'round';
```

To the PIXI.Text.updateText() method before context.fillText() is called.

As you can see the artifact is gone after changing the updateText() method:
![good](https://cloud.githubusercontent.com/assets/7429066/2817300/92c13f7c-ced7-11e3-998b-8520716eced0.PNG)

**Comment by gold256** [comment]
It's not posible. The row:
this.canvas.width = ( width + this.context.lineWidth ) * this.resolution;
in the PIXI.Text.updateText() method resseting the lineCap to the "but"
