### ISSUE TITLE
Take a screenshot not take all canvas

### ISSUE THREAD

**Issue by lklion** [pixijs/pixi.js#7230]
Hi guys, 

I've tried to implement the canvas extract method as you have mentioned in this example:
https://pixijs.io/examples/#/demos-advanced/screenshot.js

but the function export only a portion of canvas, not all bound.
For example, in my case, if I've a full screen canvas, and logo in top left position, if I try to export, the only part exported is the rect of logo.
As param I've passed the `app.stage`. 
I've read many issues about canvas export to image but I can't find the answer.

Any idea or suggestion about?
Thanks in advance

- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Chrome 88
- **Running Example**: https://pixijs.io/examples/#/demos-advanced/screenshot.js

**Comment by SukantPal** [comment]
The width/height of the stage is not equal to that of the canvas. The stage is a container so its dimensions are equal to that of its contents. You'll have to add a invisible `Graphics` to the stage to make the stage's bounds equal to that of the screen:

```ts
stage.addChild(new Graphics().drawShape(renderer.screen));
```

Note: I don't remember exactly, but you might have to add `beginFill` if this doesn't work.

**Comment by lklion** [comment]
Great, with this trick is possibile to extract the bound!
The `beginFill` is not necessary, It's enough the shape.
Thanks @SukantPal
