### ISSUE TITLE
[Help wanted] BitmapText goes blurry when scale up to 2

### ISSUE THREAD

**Issue by Creta5164** [pixijs/pixi.js#7231]
### Expected Behavior

I was expected like this when BitmapText scale up to power of two. (2x) (first line glyph `1번째 윤전 돌파!`)

![image](https://user-images.githubusercontent.com/13521406/107054141-16bbb600-6813-11eb-8351-f71a5be3d7f0.png)

### Current Behavior

It's goes blurry even using nearest scale mode, have any I missed something?

![image](https://user-images.githubusercontent.com/13521406/107054235-2fc46700-6813-11eb-8522-00b46622bfa8.png)

### Possible Solution

Help wanted

### Steps to Reproduce

Demo
 - 4.8.9 : https://creffect.com/member/cretapark/pixi-blurry/index.html
 - 6.0.0-rc.2 : https://creffect.com/member/cretapark/pixi-blurry/index-latest.html

Code : https://creffect.com/member/cretapark/pixi-blurry/index.js

Resources  
 - fnt : https://creffect.com/member/cretapark/pixi-blurry/Waffleche.fnt
 - sheet 1 : https://creffect.com/member/cretapark/pixi-blurry/Waffleche_0.png
 - sheet 2 : https://creffect.com/member/cretapark/pixi-blurry/Waffleche_1.png

### Environment

- **`pixi.js` version**: _4.8.9_, _6.0.0-rc.2_
- **Browser & Version**: _Chrome_
- **OS & Version**: _Windows 10_
- **Running Example**: _See **Step to Reproduce**'s Demo url_

**Comment by SukantPal** [comment]
Be sure to use roundPixels

**Comment by bigtimebuddy** [comment]
The problem is how you're setting `scaleMode`. I would use the font directly and not use the texture resources from the load. Try this instead:

```js
const app = new PIXI.Application({ width: 320, height: 180 });
document.body.appendChild(app.view);

var face = 'Waffleche';
var fnt = './Waffleche.fnt';

app.loader.add(face, fnt);
app.loader.load(function(loader, resources) {
    const pages = PIXI.BitmapFont.available.Waffleche.pageTextures;
    for (const i in pages) {
        const baseTexture = pages[i].baseTexture;
        baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
        baseTexture.update();
    }
    const content = 'Hello World!';
    const style = { fontName: 'Waffleche', align: 'left'};
    const text = new PIXI.BitmapText(content, style);
    const scaledText = new PIXI.BitmapText(content, style);
    
    scaledText.scale.set(2);
    scaledText.y = text.y + text.height;
    app.stage.addChild(text, scaledText);
});
```

![Screen Shot 2021-02-06 at 11 38 36 AM](https://user-images.githubusercontent.com/864393/107128102-dfc7bd80-686f-11eb-87f8-bdc08c8ff0be.png)

**Comment by Creta5164** [comment]
@bigtimebuddy Thanks, that's what I expected result!  
But it seems `pageTextures` property aren't in v4, is there equalpment thing about it?  
I'm looking in source code of v4 (4.8.9), it's doesn't exposed them in code.

https://github.com/pixijs/pixi.js/blob/359a131eb10485947874b9a48bc2d62c1ee0b1a1/src/extras/BitmapText.js#L557

**Comment by Creta5164** [comment]
Oh I see it now, I missed some codes... 🤦

`textureResource.texture.baseTexture = PIXI.SCALE_MODES.NEAREST`
to
`textureResource.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST`

Thanks for advices, everyone!  
I'll close this issue.
