### ISSUE TITLE
Artifacts in filter using texture as uniform

### ISSUE THREAD

**Issue by bryan-d** [pixijs/pixi.js#7234]
I'm running into an issue with a simple custom filter that maps the colors in a grayscale image to a 256x1 gradient texture. There are strange artifacts throughout the filtered result. Could it be an issue with sampling pixels in the fragment shader?

### Behavior
![image](https://user-images.githubusercontent.com/17154047/107134456-1d940880-68a7-11eb-93d6-e1b7b4ee6048.png)

### Steps to Reproduce
https://codepen.io/bryan_d/pen/JjbXrQJ

### Environment
- `pixi.js` 5.3.7
- **Browser**: Chrome 88
- **OS**: Windows 10

**Comment by SukantPal** [comment]
Okay, so this is an issue with browser scaling. You're using `image-rendering: pixelated` but the browser is still using linear interpolation. One way of verifying this is to add a Graphics rectangle, and it will still be blurry:

```js
app.stage.addChild(new PIXI.Graphics().beginFill(0xff).drawRect(8, 8, 16, 16));
```

It seems as if browsers aren't doing pixelated scaling with WebGL canvases. If you set `forceCanvas: true` in the application constructor's options, you'll see the generated image with crisp edges. (However, the color will be gone b/c the gradient filter doesn't run).

The proper solution here would not to CSS zooming and draw into a larger canvas instead. See this [pen](https://codepen.io/sukantpal/pen/vYyGqEj) with the fix.

NOTE about resolution: You have set the renderer's and filter's resolution to `window.devicePixelRatio` to ensure the edges are crisp on retina devices.

**Comment by bryan-d** [comment]
Thanks for taking a look, but I have to disagree. I made a note in the CSS of the demo that those properties aren't required. I simply added them to make it easier to see the issue. You can try removing the CSS properties yourself, and the issue remains. This doesn't appear to be an issue with scaling at all (CSS or otherwise). The issue seems to be at the filter or shader level.

Also, you're suggesting I force the canvas render. How could the canvas renderer run a shader? That doesn't really make much sense to me.

Could you remove the "Not A Bug" label? This isn't resolved on my end.

**Comment by SukantPal** [comment]
If the issue still remains without the CSS zoom, it is obviously exacerbated by the linear interpolation of the browser. Otherwise, you'd see 4x4 pixel blocks (that should be obvious).

**Comment by bryan-d** [comment]
I am not trying to scale or zoom the render at all. I only added that initially to more clearly show what the problem is. Let's forget about the scaling completely since it appears that has side-effects when explaining the actual issue.

I see in your pen that it appears fixed. The issue is that when I remove your `.scale(4)` and change the renderer to 32x32, it is still broken. As seen here:
![image](https://user-images.githubusercontent.com/17154047/107180401-79d15800-698d-11eb-97e2-bc5a7fa9d04c.png)

Why are there still pixel blocks when there is no scaling or CSS zoom?

(Sorry, I would update the pen, but CodePen appears broken at the moment)

**Comment by SukantPal** [comment]
So if I zoom in (via Command + +). All I see is more blurriness:

Me zooming in on the pen:
<img width="1161" alt="Screen Shot 2021-02-10 at 10 26 10 AM" src="https://user-images.githubusercontent.com/22450567/107530996-67703d80-6b8a-11eb-9f50-0053f1112172.png">

Me zooming in on your sample image, I do see artifacts:

<img width="282" alt="Screen Shot 2021-02-10 at 10 27 29 AM" src="https://user-images.githubusercontent.com/22450567/107531188-95558200-6b8a-11eb-97e0-8e20f25775cc.png">

----

So it seems like this is a platform dependent problem?

**Comment by SukantPal** [comment]
Wait, if I force resolution to be 1, then I can repro this!!! (My retina screen has devicePixelRatio = 2)

**Comment by bryan-d** [comment]
Thanks for verifying. My screen is devicePixelRatio = 1, so that appears to be involved.

One interesting thing is that the size of the artifact is consistently the same even when you scale the result up. It almost seems like at resolution = 1, it is shifting the pixels by -0.5 (up and to the left). The subpixels then cause artifacts. I've tested this by using the following grid pattern which has a 1px space between each white pixel.
![image](https://user-images.githubusercontent.com/17154047/107549652-efebdf80-6b84-11eb-87a7-031679e40aea.png)

At resolution = 1, after passing through the filter, the output is a solid gray block with a brightness value of 147.
![image](https://user-images.githubusercontent.com/17154047/107550034-64268300-6b85-11eb-8b42-36fae6c50b33.png)

At resolution = 2, the output is identical to the input, as expected.
![image](https://user-images.githubusercontent.com/17154047/107550207-97691200-6b85-11eb-8684-aa07563ceba6.png)

I don't know enough about PIXI internals to verify my idea, but could it be possible that there is a constant decimal error somewhere that perhaps gets floored or rounded out at resolutions > 1?

**Comment by ivanpopelyshev** [comment]
We turned on mipmap 's by default , somehow.

`texture.baseTexture.mipmap = 0` on gradient texture makes everything right. Gonna investigate which change was it

**Comment by ivanpopelyshev** [comment]
By default in v5 and v6 texture is mipmapped if its dimensions are powers of two.

For any color maps you have to use something like  `new PIXI.BaseTexture(document.querySelector(selector), { mipmap: 0, scaleMode: 0 });`

`color.r` is not actually a good coord. `(coord.r * 255.0 + 0.5) / 256.0` is the center of pixel in gradient texture, either use it in formulae either use scaleMode 0 (NEAREST)

mipmap 0 means `POW2` , scaleMode 0 means `NEAREST` in pixi constants.

**Comment by bryan-d** [comment]
Confirmed, thanks for taking a look (and for the additional tip).
