### ISSUE TITLE
Could it be possible to have the fixed AnimatedSprite in the v5 ?

### ISSUE THREAD

**Issue by Inateno** [pixijs/pixi.js#7241]
Hey guys, just asking myself why the "fix" in AnimatedSprite isn't shipped into V5 ?
Not really confident of using the "dev" branch (but maybe we could ?).

Thanks.

### Expected Behavior
gotoAndStop/stop isn't really stopping, but code seems fixed in v6

### Current Behavior
stop does'nt really stop

### Possible Solution
Update "5.3.7" with the fix there is in v6 cf https://github.com/pixijs/pixi.js/blob/dev/packages/sprite-animated/src/AnimatedSprite.ts#L263

### Environment
PIXI 5.3.7

**Comment by bigtimebuddy** [comment]
Sure, I cherry-picked this into v5.3.x. Will get released with 5.3.8, which I'll make soon.

**Comment by Inateno** [comment]
> Sure, I cherry-picked this into v5.3.x. Will get released with 5.3.8, which I'll make soon.

Thanks, I've been looking why it was not working as the doc says for hours because of this lol.

Is the doc based on dev branch btw ?

**Comment by bigtimebuddy** [comment]
Yes, that's right. I'd suggest you use the version specific docs which you can get from the releases section to be the most accurate.
