### ISSUE TITLE
Pixi Blob

### ISSUE THREAD

**Issue by enahsor** [pixijs/pixi.js#7242]
This is less of an issue and more of me trying to figure out how the blob on [pixi's](https://www.pixijs.com/) website was made. If you don't know what I'm referring to, see: 
<img width="1423" alt="Screen Shot 2021-02-10 at 10 45 54 AM" src="https://user-images.githubusercontent.com/35748031/107542059-668cdb00-6b8d-11eb-8bdf-ae6b976848d7.png">

I did a quick run-through of the documentation and saw no mention of a blob in the examples. Any idea how I can implement this?  If there exists an open-source repository of the website, this would also help.

**Comment by SukantPal** [comment]
@bigtimebuddy Migration to discussion?

This could very well just be a Graphics `drawPolygon` with a texture fill. Ask @GoodBoyDigital for how his magic works 😃 !

**Comment by bigtimebuddy** [comment]
We get this question like once a year. I have the source somewhere that @GoodBoyDigital gave me. See if I can dig it out.

**Comment by enahsor** [comment]
> We get this question like once a year. I have the source somewhere that @GoodBoyDigital gave me. See if I can dig it out.

That would be much appreciated @bigtimebuddy

**Comment by bigtimebuddy** [comment]
Okay, so good new/bad news. I found the source code, but it's a hot-mess and using an indeterminately old version of Pixi. Give me some time to piece it together and see if I can upgrade it to be more current.

**Comment by enahsor** [comment]
Woah, man. That's awfully kind of you. Thank you.
I look forward to it.

**Comment by bigtimebuddy** [comment]
Yeah, actually what I have isn't the actual source code. I pinged @GoodBoyDigital for it, hopefully he can unearth something more recent.

**Comment by enahsor** [comment]
@bigtimebuddy any word from @GoodBoyDigital ?

**Comment by bigtimebuddy** [comment]
Yeah, I believe we've reach a dead-end with this. We actually can't find the completed source, only bits and pieces. Unless, Mat is able to unearth a miracle, I think the best course is to try to recreate it by reverse-engineering from the source or rebuilding it. Sorry, I was really hoping to be able to create a repo with this and update to the latest Pixi.

**Comment by enahsor** [comment]
Yeah alright. Thanks for taking the time to reach out to everyone to help resolve my issue.
