### ISSUE TITLE
Create Textures from PIXI.Text

### ISSUE THREAD

**Issue by Triborg333** [pixijs/pixi.js#7250]
Create Textures from PIXI.Text ?

const app = new PIXI.Application({ 
			width: window.innerWidth,         // default: 800
			height: window.innerHeight,        // default: 600
			antialias: true,    // default: false
			transparent: false, // default: false
			resolution: 1,      // default: 1
			backgroundColor:0xEB4C42
	}
);
		
app.renderer.view.style.position = "absolute";
app.renderer.view.style.display = "block";
app.renderer.autoResize = true;
app.renderer.resize(window.innerWidth, window.innerHeight);
		
document.body.appendChild(app.view);
		
app.stage.interactive = true;
app.stage.sortableChildren = true;

let text = new PIXI.Text('message').texture;
let sprite = new PIXI.Sprite(text);

app.stage.addChild(sprite);

does not work:(
help me please:))

I tried it text.updateText() still doesn't display

**Comment by Triborg333** [comment]
Help me please

**Comment by themoonrat** [comment]
You need to create the text and update its texture manually first, before trying to grab its texture

```
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

const text = new PIXI.Text('hello world');
text.updateText();
const sprite = new PIXI.Sprite(text.texture);

app.stage.addChild(sprite);
```
https://www.pixiplayground.com/#/edit/2xbzAhLIhn45FcjiWV8SF

**Comment by Triborg333** [comment]
themoonrat, thanks!)
