### ISSUE TITLE
Pixi v5/v6 uses WegGL v1 on samsung galaxy s8 phone running chrome 88

### ISSUE THREAD

**Issue by IljaDaderko** [pixijs/pixi.js#7251]
### Expected Behavior
Should use WebGL v2

### Current Behavior
Use WebGL v1

### Possible Solution
-

### Steps to Reproduce
Open pixi application on specified device, connect it to your computer via USB and go to `chrome://inspect` in order to open devtools for connected phone. Pixi logs that webgl 1 is being used.

I also visited https://webglreport.com on same device, and it states that webgl v2 is indeed supported on it.

### Environment
- **`pixi.js` version**:  v5/v6
- **Browser & Version**: _e.g. Chrome 88
- **OS & Version**:  Android 9.0
- **Running Example**: -

**Comment by bigtimebuddy** [comment]
See #5502

According to docs for PIXI.settings.PREFER_ENV:

> Due to bug in chromium we disable webgl2 by default for all non-apple mobile devices.
