### ISSUE TITLE
CacheAsBitmap on resolution > 1

### ISSUE THREAD

**Issue by eXponenta** [pixijs/pixi.js#7258]
`cacheAsBitmap` not apply resolution when generate RenderTexture
For devices with resolution > 1 this is produce a pixelation.

### Expected Behavior

CacheAsBItmap save pixel density for cached elements

### Current Behavior
`cacheAsBitmap` reduce resolution for texture 

### Possible Solution
Put resolution property from renderer to render texture
https://github.com/pixijs/pixi.js/blob/dev/packages/mixin-cache-as-bitmap/src/index.ts#L209

![image](https://user-images.githubusercontent.com/12572222/108622229-5ce65b80-7448-11eb-93c5-21b830d984c2.png)

### Environment

- **`pixi.js` version**:  >5.0.0
- **Browser & Version**: all
- **Running Example**: https://www.pixiplayground.com/#/edit/9fx2o5h41xntmYvbVd-Ed

**Comment by Triborg333** [comment]
Hi, Maybe I helped you a little bit - https://www.pixiplayground.com/#/edit/9fx2o5h41xntmYvbVd-Ed

**Comment by bigtimebuddy** [comment]
cacheAsBitmap I believe considers PIXI.settings.RESOLUTION when creating the RenderTexture.

**Comment by eXponenta** [comment]
@bigtimebuddy  renderer resolution and settings Resolution is not same.
settings resolution is default resolution, but a lot of people pass resolution to rendered and forget about it.
Anyway a `cacheAsBitmap` should has certain behaviour.

**Comment by themoonrat** [comment]
Is there a case for PIXI.settings.RESOLUTION being updated if resolution option is passed on to renderer constructor? Is there any time where them being different is a good thing?

**Comment by bigtimebuddy** [comment]
I think the case for RESOLUTION being independent is for optimization. Say you set your max resolution with the Renderer (eg 2), but setting RESOLUTION (eg 1) will allow you to default use a resolution with lower memory impact. CacheAsBitmap will use 1 instead of 2 which may be desirable in some cases. I think the cacheAsBitmap API stinks because you cannot control resolution locally.

**Comment by bigtimebuddy** [comment]
@eXponenta do you want to weigh-in on the PR?
