### ISSUE TITLE
Can we set any degree on text gradient filling? fillGradientType only support horizontal and vertical gradient filling 

### ISSUE THREAD

**Issue by zheeeng** [pixijs/pixi.js#7261]
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
Correct, we do not support arbitrary degrees for gradient on Text. I'd encourage you to render your own text use a canvas element you create yourself and [fillText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText).

**Comment by bigtimebuddy** [comment]
Closing this as it is answered.
