### ISSUE TITLE
Few type issues with v6-rc3

### ISSUE THREAD

**Issue by IljaDaderko** [pixijs/pixi.js#7264]
### Expected Behavior
These type errors should probably not be thrown?

### Current Behavior
1. Pixi loader throws an error when string is passed as a name argument. Error refers to `resource-loader.d.ts:193` which is
```ts
add(resources: (IAddOptions | string)[], callback?: Resource.OnCompleteSignal): this;
```

<img width="1039" alt="Screenshot 2021-02-26 at 13 16 23" src="https://user-images.githubusercontent.com/3154053/109294178-84b53500-7835-11eb-8a26-2aa60109840f.png">

2. 
When trying to call `super.renderer` i.e from class that extends `Container` for example type error is thrown for passing in renderer that's taken rom `Application`.

<img width="1171" alt="Screenshot 2021-02-26 at 13 17 48" src="https://user-images.githubusercontent.com/3154053/109294466-e83f6280-7835-11eb-8bae-96ef579ce7af.png">

### Possible Solution
N/A

### Steps to Reproduce
N/A

### Environment

- **`pixi.js` version**:  6.0.0-rc.3
- **Browser & Version**:  N/A
- **OS & Version**: _e.g. N/A
- **Running Example**:  N/A

**Comment by IljaDaderko** [comment]
Was able to reproduce both of these here https://codesandbox.io/s/determined-cloud-xkmq7?file=/src/index.ts
let me know if more info is required.

<img width="699" alt="Screenshot 2021-02-27 at 12 28 05" src="https://user-images.githubusercontent.com/3154053/109384699-43855980-78f7-11eb-8051-d06382fad7d8.png">

**Comment by bigtimebuddy** [comment]
Those seem like incorrect uses. 

First the Loader (string, null) is invalid. Just do (string) for loading a URL or (string, string) for a name and URL. I'd assume string null is not a valid typing.

The second render override is probably not exactly invalid but definitely not standard usage. It doesn't match the signature of Container which makes your inherited container less useful. It should use the renderer param and pass to super.renderer.

**Comment by bigtimebuddy** [comment]
![Screen Shot 2021-02-27 at 12 34 36 PM](https://user-images.githubusercontent.com/864393/109399526-2d2bcd80-78f8-11eb-947d-1c1eee3e086d.png)

The reason you're getting the MyContainer error is because Application's renderer is more flexible, it can be Renderer or CanvasRenderer. Where the `render` function is _only_ expecting Renderer as a type. If you want to keep that approach you need to cast `super.render(renderer as Renderer)`. But again, I would advise against this since render is passed a reference to the renderer as the first argument anyways.

**Comment by IljaDaderko** [comment]
Alright, managed to resolve the issues based on your comments, that `null` was just a placeholder for codesandbox, in my real app that type was just resolving to `unknown`. So, all set, thank you 👍
