### ISSUE TITLE
Typings: 'Point' is not assignable to 'ObservablePoint'

### ISSUE THREAD

**Issue by Shatterbrain** [pixijs/pixi.js#7267]
Hi, I've been updating from v4 to v6 and ran into the following typing problem in my codebase:
```
const sprite = new Sprite(...);
sprite.position = new Point(1,1);
```
```
(property) DisplayObject.position: ObservablePoint<any>
Type 'Point' is not assignable to type 'ObservablePoint<any>'.ts(2322)
```

This never threw an error before. Is there a subtle problem with assigning a Point to ObservablePoint that is only just now being detected? If so, what should I be doing instead?

Typescript version is 4.1.5
pixi.js version is 6.0.0

**Comment by Shatterbrain** [comment]
Maybe `sprite.copyFrom(new Point(1,1))`? Maybe event emissions are being lost with the direct assignment.

**Comment by Shatterbrain** [comment]
Upon closer inspection of the code, it looks like this typing update was detecting a problem.

https://github.com/pixijs/pixi.js/blob/40b8c8d7d1a3e99df059b5d5c582975eb536b30a/packages/math/src/ObservablePoint.ts#L51

If you use `set` or `copyFrom`, the callback is triggered; otherwise, a reassignment won't trigger it.

Closing

**Comment by SukantPal** [comment]
Yes. If you replace the `ObservablePoint` with a `Point`, you're basically taking away the callbacks. You should copy data into DisplayObject position, scale, etc. instead
