### ISSUE TITLE
Update hitarea after resize

### ISSUE THREAD

**Issue by lklion** [pixijs/pixi.js#7281]
Hi guys,

I've a problem when I try to catch event on fullscreen hitarea of container after window resize.
In my case, I need to mantain the central stage (in the example initial the green square) always in the center of screen, also after resize) and add other squares around by click.
The stage is ok, the container resize is enought, but after resize the coordinates of the click are wrong.

I've read about moving every single element after resize but in my case could be a problem for the number of elements.

Any idea or suggestion about?
Thanks in advance 🙏

- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Chrome 88
- **Running Example**: https://jsfiddle.net/LkLio/1cykrpds/16/

**Comment by ivanpopelyshev** [comment]
There's a shortcut for hitArea/filterArea stuff:

```
container.hitArea = app.screen;
```

**Comment by lklion** [comment]
Thanks @ivanpopelyshev for reply, but sadly It doesn't solve the problem after resize.
After resize the hitarea seems translated respect the container and, at click, element result translated respect mouse
I think it could be a position problem but I'm not sure
