### ISSUE TITLE
TypeScript Node types "leak" into a project using PIXI with v6

### ISSUE THREAD

**Issue by qtiki** [pixijs/pixi.js#7283]
### Expected Behavior

Adding PIXI to a TypeScript project should not add Node types to the project.

### Current Behavior

Adding PIXI to a TypeScript project adds a dependency to Node types.

For example this project compiles successfully:

**tsconfig.json**
```json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "esnext",
      "scripthost"
    ]
  },
  "include": [
    "src"
  ]
}
```

**src/index.ts**
```ts
const timeout: number = setTimeout(() => {
    console.log('hello world');
}, 100);
```

However after just adding `pixi.js` to the project without modifying the code at all the `setTimeout` return value is no longer assignable to a `number` as it's type changes to `NodeJS.Timeout` and compiling gives the following error:

```
src/index.ts:1:7 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

1 const timeout: number = setTimeout(() => {
        ~~~~~~~
```

### Possible Solution

Remove the type dependency to Node. This is most likely caused by a Node type reference in one of PIXI's dependencies rather than PIXI itself. I haven't yet investigated this in more detail so I can't say for sure what is causing this and how to fix it.

### Steps to Reproduce

Run the following commands to create the empty project and copy `tsconfig.json` and `src/index.ts` from the example above:
```
yarn init
yarn add typescript
yarn add pixi.js
```
After the project is setup run `yarn tsc --noEmit` to get the error.

### Environment

- **`pixi.js` version**: 6.0.0
- **TypeScript version**: 4.2.3
- **OS & Version**: Windows 10

**Comment by qtiki** [comment]
It seems the Node types come from `@pixi/utils` dependency. As a workaround the project's tsconfig can be modified to explicitly specify no types to prevent the Node types automatically being included:
```json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "esnext",
      "scripthost"
    ],
    "types": []
  },
  "include": [
    "src"
  ]
}
```

**Comment by bigtimebuddy** [comment]
This was added here: https://github.com/pixijs/pixi.js/pull/7059

I'm having trouble remembering why I choose this path, I think it was because we didn't have types for `url`. Taking all the Node types is overkill, agreed. This should be fixed.

**Comment by qtiki** [comment]
I came to the same conclusion after some searching. I think it would be better to move the Node types to a dev dependency and re-declare the `url` types inside `util`. That way TypeScript can still validate that the exported `url` types are in fact compatible with the Node types.

I'll see if I can whip up a PR for this.

**Comment by bigtimebuddy** [comment]
A PR for this would be ace. Thank you!
