### ISSUE TITLE
Support for Alpha Compositing

### ISSUE THREAD

**Issue by roomyrooms** [pixijs/pixi.js#7296]
I understand this is more an issue with WebGL, but my understanding is limited at best. I was hoping I could pop open a feature request and get some more info on this issue, or possibly bring it some light if it's something that's not totally impossible to do in WebGL.

I've been trying to switch over my lighting system for a while now so I can take advantage of the other features of Pixi/WebGL rendering and etc., but being unable to use destination-out/source-atop/etc. compositing makes this transition impossible. I've written myself a filter to do something adjacent, but it's a clunky solution at best.

I realize this will probably take a long time to get implemented, but even so. Is there a better fix than a custom filter & how impossible is alpha compositing in WebGL?

**Comment by roomyrooms** [comment]
pixi-picture has a lot of tools for standard blend modes like overlay, hard-light, etc., but as far as I'm aware, it doesn't support alpha compositing like destination-out and so on.

**Comment by ivanpopelyshev** [comment]
Alpha compositing was added in pixi in 2019 or 2020 , just assign corresponding blending mode.

**Comment by roomyrooms** [comment]
Hey! Sorry for being so late on this.

I ended up writing a shader to try and handle it, but when I saw your reply I wanted to try out these blend modes (since that'd obviously be much more elegant).

I can't seem to get destination out working though: https://jsfiddle.net/roomyrooms/z1hkvw8f/31/
I'm just messing around in this fiddle, but even so, it doesn't seem to behave correctly. The destination over sprite shouldn't even be visible iirc?

It doesn't seem to do anything at all other than turn it white.

**Comment by roomyrooms** [comment]
Okay, I realized what was happening-
It's cutting through all the way to the back of the page, which is expected behavior - I wasn't expecting it because it wasn't what I was used to in my game setting. Apologies for the misunderstanding.

If there are more issues I'll add them, but for now I think I've resolved my dilemma here!
