### ISSUE TITLE
Video textures not working with Mesh

### ISSUE THREAD

**Issue by AlexandreRangel** [pixijs/pixi.js#7302]
Dear Pixi friends,

we appear to have found a bug related to using a video texture with mesh distortion.

The following CodePen shows the issue:
[https://codepen.io/is2548-the-selector/pen/gOLydRj](https://codepen.io/is2548-the-selector/pen/gOLydRj)

And this CodePen shows the desired behavior, with the plane being distorted with an image texture applied to it:
[https://codepen.io/is2548-the-selector/pen/JjbWjaG](https://codepen.io/is2548-the-selector/pen/JjbWjaG)

Thank you!

**Comment by JetLua** [comment]
workaround: https://codepen.io/jerald/full/MWbMJjO

Maybe not a bug because you can override `textureUpdated`.
Or maybe there is no need for `geometry.build()`.

```js
beach.textureUpdated = function() {
  this._textureID = this.shader.texture._updateID
}
```

https://github.com/pixijs/pixi.js/blob/f9d526704cd6e992e9194ff745be906a556c66cb/packages/mesh-extras/src/SimplePlane.ts#L43-L57

**Comment by ivanpopelyshev** [comment]
I think best solution is to check current width/height of geometry, and call `build` only if it differs and we have special flag enabled, like `autoResize` ?

**Comment by JetLua** [comment]
> I think best solution is to check current width/height of geometry, and call `build` only if it differs and we have special flag enabled, like `autoResize` ?

It sounds great

**Comment by AlexandreRangel** [comment]
Amazing, @JetLua !!!
Thank you very much JetLu, @bigtimebuddy and @ivanpopelyshev !!!
