### ISSUE TITLE
Rotation on center pivot not maintained with multiple containers.

### ISSUE THREAD

**Issue by rizen** [pixijs/pixi.js#7310]
### Expected Behavior

I set the pivot point to center on an outer and an inner container, and then add one rectangle to the inner container.  

When I set an angle on the inner container the rectangle rotates on its center point. I would expect the same on the outer container, but that's not happening.

### Current Behavior

Setting the outer container has the correct rotation, but the center point moves. 

### Possible Solution

Unfortunately I don't know what's causing it, so that makes it hard to offer a solution.

### Steps to Reproduce

I've created 3 fiddles for you to see what's going on.

This one shows the correct rotation on the inner container:  https://jsfiddle.net/y3j2tLd8/15/

This one shows the incorrect rotation on the outer container: https://jsfiddle.net/y3j2tLd8/13/

This one shows that the rotation becomes correct on the outer container if I move the y position to the outer container (no idea why that affects it): https://jsfiddle.net/y3j2tLd8/14/

### Environment

- **`pixi.js` version**: 6.0.0
- **Browser & Version**: Chrome 88 (or any other modern browser)
- **OS & Version**: Mac OS 11.2.2
- **Running Example**: https://jsfiddle.net/y3j2tLd8/13/

**Comment by bigtimebuddy** [comment]
I do not understand this issue @rizen. Specifically your description of the expected behavior isn't clear to me. What exactly are you trying to accomplish? Can you show it more clearly, maybe with a diagram?

**Comment by rizen** [comment]
Sorry I thought the code I provided would explain the problem. The problem is that if I wrap a sprite or a graphic (or multiple of each) inside of nested containers and then try to rotate those containers around their center point they do both share the same center point even though they have the same width / height. 

This if I set the angle on the inner container I get this:
<img width="522" alt="Screen Shot 2021-03-17 at 5 26 26 PM" src="https://user-images.githubusercontent.com/170009/111546624-f6521600-8745-11eb-9d41-19fbdc813742.png">

But if I set the angle on the outer container I get this:
<img width="529" alt="Screen Shot 2021-03-17 at 5 26 37 PM" src="https://user-images.githubusercontent.com/170009/111546696-11248a80-8746-11eb-865b-f906b131f8db.png">

I'm guessing the outer container's center point includes the x/y position of the inner container, even though when you ask the outer container for its width and height, they do not reflect that. 

I'm expecting that whether I apply rotation to the inner or the outer container, I get the rectangle in the same position because  container.width/2 is the same x center point on both of them, and container.height/2 is the same y center point on both of them.

Does that add clarity?

**Comment by rizen** [comment]
Or were you asking "why" am I trying to use nested containers?

**Comment by bigtimebuddy** [comment]
Yes, doing nested containers with pivots can get tricky! 

You should not be applying the same pivot to both Containers. Try only setting the pivot to the inner Container that contains the Rectangle and the outer container pivot should be 0,0. Here's an example where the pivot is the center for both Containers.

https://jsfiddle.net/bigtimebuddy/v24usm9b/

**Comment by rizen** [comment]
Thank you for that. Unfortunately in doing what you did, you accidentally removed parameters inner position. I need to be able to set both inner and outer positions. 

```inner.position.set(0,100);```

Here is your fiddle updated: https://jsfiddle.net/rgahxtud/10/

And you can see that it gets all wonky again.  Any thoughts on how to do this?

**Comment by bigtimebuddy** [comment]
You need to offset the pivot of the outer Container.
https://jsfiddle.net/bigtimebuddy/Lx370h5b/

Please keep in mind that pivot and position are basically the same thing in PixiJS. Pivot defines the origin for children of a Container and position is the local position in the parent's coordinate space. In CSS and other rendering systems the origin and pivot are sometimes treated separately. It's a quirk about PixiJS that takes getting use to.

**Comment by rizen** [comment]
Holy hell!  You weren't kidding when you said rotating containers inside of containers is hard. Your code didn't ultimately do what I want, but your description of "Pivot defines the origin for children of a Container and position is the local position in the parent's coordinate space." was exactly what the doctor ordered. I had no idea that's how it worked! I was able to use that to construct code to do what I want. I guess ultimately this isn't a bug, but it is confusing to say the least. I guess that's just what happens when you start to do really complex things. Thank you so much!

**Comment by bigtimebuddy** [comment]
You're welcome, good luck!
