### ISSUE TITLE
Centred scaling for Graphics class.

### ISSUE THREAD

**Issue by kelpie86** [pixijs/pixi.js#732]
Hello GBD, today I found out that PIXI does not support setting origin of scale. 

Example is here 
http://www.html5rocks.com/en/tutorials/webgl/webgl_transforms/webgl/webgl-2d-geometry-matrix-transform-center-f.html

is it on the TODO list? if it's not I may try to implement it by giving it a flag variable to indicate whether it's centred or not. but also it'd be great to have not only centre option but also bottom right or more various options for the origin.

Because now I have to set the scale of Graphics and calculate its position according to the new scaled size, which consumes CPU resources.

**Comment by Arduinology** [comment]
We really need an anchor property on Display Object Container's at least. Would be great on everything though.

**Comment by englercj** [comment]
@Arduinology  `anchor` is the attachment point of the texture of the object. DOCs don't have a texture.

**Comment by Arduinology** [comment]
@englercj for me when I do DOC.pivot.set(x,y) my DOC contents actually move, I don't wan that, I want everything to move (scale) relative to my pivot point, does that make sense. That is what an anchor should do.

**Comment by englercj** [comment]
@Arduinology It does make sense, I have a proposal (#997) that I will be trying to put into the 3.0 code that solves this issue. `pivot` right now is acting kind of like a combination of origin and pivot in my proposal.

But I do want to point out that the anchor does not and should not effect scaling. It is *only* the attachment point of a texture. The point around which to rotate should be pivot, the point that describes positioning should be the `origin` which doesn't exist yet.

**Comment by Arduinology** [comment]
@englercj I can agree with that, we need origin (what I have come to know as anchor is not what Pixi calls anchor). I already +1'd your proposal yesterday and modified anchor to origin today. So what should I do in the mean time, what is the solution for origin? Do we have any viable workarounds?

**Comment by englercj** [comment]
I've done what you describe with scaling and positional offsets. It isn't a trivial problem to solve right now.

**Comment by khurramraheel** [comment]
I am about to scale the stage from a specific point but no luck, Can any please help me on this?

**Comment by ivanpopelyshev** [comment]
@rcbyron if your rectangle sides are parallel to axises, then its drawn through a sprite. You can do it without graphics, using same approach: create a temporary render texture that you will use with rectangle sprites. I just put here the piece of code from the "Graphics.js". Your code will be much easier, you wont have tint problems and other stuff

```js
Graphics.prototype._renderSpriteRect = function (renderer)
{
    var rect = this.graphicsData[0].shape;
    if(!this._spriteRect)
    {
        if(!Graphics._SPRITE_TEXTURE)
        {
            Graphics._SPRITE_TEXTURE = RenderTexture.create(10, 10);

            var currentRenderTarget = renderer._activeRenderTarget;
            renderer.bindRenderTexture(Graphics._SPRITE_TEXTURE);
            renderer.clear([1,1,1,1]);
            renderer.bindRenderTarget(currentRenderTarget);
        }

        this._spriteRect = new Sprite(Graphics._SPRITE_TEXTURE);
    }
    if (this.tint === 0xffffff) {
        this._spriteRect.tint = this.graphicsData[0].fillColor;
    } else {
        var t1 = tempColor1;
        var t2 = tempColor2;
        utils.hex2rgb(this.graphicsData[0].fillColor, t1);
        utils.hex2rgb(this.tint, t2);
        t1[0] *= t2[0];
        t1[1] *= t2[1];
        t1[2] *= t2[2];
        this._spriteRect.tint = utils.rgb2hex(t1);
    }
    this._spriteRect.alpha = this.graphicsData[0].fillAlpha;
    this._spriteRect.worldAlpha = this.worldAlpha * this._spriteRect.alpha;

    Graphics._SPRITE_TEXTURE._frame.width = rect.width;
    Graphics._SPRITE_TEXTURE._frame.height = rect.height;

    this._spriteRect.transform.worldTransform = this.transform.worldTransform;

    this._spriteRect.anchor.set(-rect.x / rect.width, -rect.y / rect.height);
    this._spriteRect.onAnchorUpdate();

    this._spriteRect._renderWebGL(renderer);
};
```
