### ISSUE TITLE
BitmapFont.uninstall/destroy also destroying the texture that could be used by other objects

### ISSUE THREAD

**Issue by 4ian** [pixijs/pixi.js#7323]
When we use a texture to create a BitmapFont, uninstalling this font will also destroy the texture (and the base texture it seems) - even if the BitmapFont was not created using `BitmapFont.from`. This can create a problem as the texture could be used for something else (another BitmapFont? or even a Sprite?) and will be invalidated (and will crash the game).

### Expected Behavior

Assume we follow this pseudo code:
```
// Load beforehand someFontData and someTexture.

const bitmapFont = BitmapFont.install(someFontData, someTexture);

// Use bitmapFont with a BitmapText: 
const bitmapText = new BitmapText("some text", { fontName: bitmapFont.font });
// Use bitmapText somehow...
// We can destroy the bitmapText when not useful anymore:
bitmapText.destroy(); // So far so good.

BitmapFont.uninstall(bitmapFont.font);
```

At this point, I expect to be able to continue using someTexture. 

### Current Behavior

The call to `uninstall` will actually (in 5.3.7 at least) trigger a `destroy` on someTexture and its base texture.
If the texture is used by another object, this will crash at the texture is not `valid` anymore.

### Possible Solution

@SukantPal talked about a way to mark the texture `managed` by the BitmapFont or not (should be the case for `BitmapFont.from`). If not, it should probably not attempt to destroy its texture, apart if `true` is passed as an argument (following the usual convention for destroy options).

Not sure if it's the best solution (is `managed` enough? Is there a risk that it would require a full "reference counting" implementation in a more complex situation?), but mentioning it because it still sounds like a good start.

### Steps to Reproduce

I've not created an example but I could do it if it's useful. Creating a BitmapFont with a texture and `uninstall`ing it should show the problem, as the texture is not `valid` anymore.

### Environment

- **`pixi.js` version**: 5.3.7
- **Browser & Version**: Chrome 88.0.4324.96
- **OS & Version**: macOS
- **Running Example**: none (can be created on demand)

**Comment by bigtimebuddy** [comment]
Interesting. One expectation I have of the BitampFont textures is they are opaque to users. These textures are not added to TextureCache, for instance, which is the source for user-available textures. There is some effort to hide BitmapFont textures from users for this reason. Can you explain more about why you're manually referencing these textures? That feels like an anti-pattern from the design. As a user I would not expect auto generated textures to be available after destroying the object that's holding on to them.

**Comment by SukantPal** [comment]
@bigtimebuddy I think that in this case, the textures provided to `BitmapFont.install` are loaded & managed by the user, not PixiJS. As such, they could be in the TextureCache too.

**Comment by bigtimebuddy** [comment]
I didn't understand this fully. I take back my comment. Yeah this seems like a bug.

**Comment by 4ian** [comment]
> @bigtimebuddy I think that in this case, the textures provided to `BitmapFont.install` are loaded & managed by the user, not PixiJS. As such, they could be in the TextureCache too.

Correct! I'm very happy not dealing at all with the textures that are autogenerated using `BitmapFont.from` (and I expect `uninstall` to destroy the texture). But for a font installed "manually" with `BitmapFont.install`, I would assume by texture to survive even after the bitmap font is destroyed. This can be the case if I use it for multiple BitmapFont, or if I use some part of the texture for a Sprite, or if even if I destroy the BitmapFont after using it (to clean and give back a bit of memory), then re-create it later for another scene/dialogue/level/etc.

About the possible solution, maybe the information of "is this texture generated and so should be destroyed" can be actually stored as part of the BitmapFont?

**Comment by 4ian** [comment]
Thanks for the quick fix 👍
