### ISSUE TITLE
LineTo should render lines with latest lineStyle color, not with mixed lineStyle colors

### ISSUE THREAD

**Issue by FoolEdward** [pixijs/pixi.js#7341]
My goal is to draw lines with different color, so I use Graphics.lineStyle and Graphics.lineTo methods. But my situation is special, because lineStyle and lineTo should be called per frame.
### Expected Behavior
LineTo renders lines with one color per time, and lineTo should render lines with latest lineStyle color.
### Current Behavior
LineTo renders lines with mixed lineStyle colors.
### Steps to Reproduce
```
const lineGraphics = new PIXI.Graphics();
lineGraphics.lineStyle({
    width: 4,
    color: 0x00ff00,
    cap: PIXI.LINE_CAP.ROUND,
    join: PIXI.LINE_JOIN.ROUND,
});
lineGraphics.moveTo(
    0.5 * app.screen.width,
    0.5 * app.screen.height
);
lineGraphics.lineTo(
    0.6 * app.screen.width,
    0.6 * app.screen.height
);
let a = 0.5;
app.ticker.add(() => {
    if (a > 0) {
        lineGraphics.moveTo(
            0.5 * app.screen.width,
            a * app.screen.height
        );
        a -= 0.01;
        lineGraphics.lineStyle({
            width: 4,
            color: 0xff0000,
            cap: PIXI.LINE_CAP.ROUND,
            join: PIXI.LINE_JOIN.ROUND,
        });
        lineGraphics.lineTo(
            0.5 * app.screen.width,
            a * app.screen.height
        );
    }
})
```
### Environment
Tested on:
- **`pixi.js` version**: 5.3.9
- **Browser & Version**: Chrome 89
- **OS & Version**: Mac OS Catalina
- **Running Example**: https://www.pixiplayground.com/#/edit/dUOrI_bFYBk3yHL37qwXZ

**Comment by bigtimebuddy** [comment]
It's helpful when you close an issue to explain your resolution for folks stumbling on this issue later on.
