### ISSUE TITLE
Text's lineHeight implementation does not match HTML

### ISSUE THREAD

**Issue by nuthinking** [pixijs/pixi.js#7344]
Text lines are current aligned to the top. When for instance the `lineHeight` is bigger than the `fontSize` the gap [gets added to the bottom](https://www.pixiplayground.com/#/edit/AVy4yl6EFkC5H9N4TYMAh).

This is not how HTML or graphics editors work.

Rubén from the [Slack channel](https://pixijs.slack.com/archives/C0XS4MVU0/p1616771712076200?thread_ts=1616746168.071900&cid=C0XS4MVU0) thinks this is due to this code in [Text.ts](https://github.com/pixijs/pixi.js/blob/7b79a9d14edaeac4476437dac19472ecdee683c8/packages/text/src/Text.ts):

`linePositionY = ((style.strokeThickness / 2) + (i * lineHeight)) + fontProperties.ascent;`

Maybe not everyone is building a graphics editor like me in PIXI, but I don't see why PIXI shouldn't be as close as possible to how HTML works.

**Comment by bigtimebuddy** [comment]
Text has gotten pretty hairy because of trying to support lots of rendering features like gradient fills, drop shadow, letter-spacing, white-space. We've basically had to implement a lot of things and this has, as you said, drifted a lot from HTML text rendering.

I might suggest this plugin as an alternative. This allow you to _literally_ do HTML text (markup, css and emojis). There are some disclaimers on the README that are worth reading, but that might be viable option?
https://github.com/pixijs/html-text

**Comment by nuthinking** [comment]
@bigtimebuddy thanks for the background info. About `html-text`:

> Only supports web-safe fonts for the fontFamily attribute.

This is a deal breaker. For my project I can try to implement my own using an offscreen canvas with 2d context.

I opened this issue because I think Pixi should sort this behavior out regardless of my project.

**Comment by nuthinking** [comment]
I think I tried to translate the text myself, like adding half of the delta between `lineHeight` and `fontSize` on the top but when `lineHeight` is 0 the text is not drawn at the very top (i.e. [textBaseLine hanging](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline)). Is there a formula I could use to calculate for instance the default height when `lineHeight` is 0? Maybe I could keep a `PIXI.Text` instance per `fontFamily` per `fontSize` with `lineHeight` 0 where I check its measures? 🤔

**Comment by bigtimebuddy** [comment]
### Problem

To rephrase the problem a little more specifically:

PixiJS does not respect the line-height for the first line so it's impossible to know where the baseline is positioned. With HTML-based text rendering, line-height is always added to the first line so you know exactly where the baseline is relative to the top of the element.

@nuthinking and I chatted, and he's going to sponsor a bounty for someone who can fix this. 

### Example

Here's a preview (HTML on top, PixiJS on bottom) from @nuthinking demo above:

https://jsfiddle.net/bigtimebuddy/t10wnyvf/ (moved to fiddle so we have a stable link)

![Screen Shot 2021-04-01 at 11 02 06 AM](https://user-images.githubusercontent.com/864393/113335391-b9efef80-92d9-11eb-9c5c-b2589acca5d3.png)

**Comment by Bouh** [comment]
Here my result:
https://jsfiddle.net/Bouh/0p1f5kc3/11/
I've added few comment for see where are my changes. See for **//ADDED by Bouh** at the end of script tag in HTML part.
If you are interested i can open a PR for it in few hours when i go back to my home for a proper & clean view on changes.
