### ISSUE TITLE
@pixi/ticker depends on @pixi/app types

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#7347]
```js
static init(options?: IApplicationOptions): void
```

Should we replace with `options?: { autoStart?: boolean, sharedTicker?: boolean }`? Otherwise an external package depending on @pixi/ticker but not @pixi/app gets typings errors. (@pixi/app isn't a dependency of @pixi/ticker)

**Comment by bigtimebuddy** [comment]
Good catch. Hopefully this is the last of these unintended typing dependencies.
