### ISSUE TITLE
Docs: v6 `filters` no longer nullable, but docs imply it is

### ISSUE THREAD

**Issue by Shatterbrain** [pixijs/pixi.js#7359]
- **`pixi.js` version**: 6.0.1

Hi, hopefully this isn't too pendantic, but I noticed a small inaccuracy in the docs.

https://pixijs.download/v6.0.0/docs/PIXI.DisplayObject.html#filters

> To remove filters simply set this property to 'null'.

The property is no longer recognized as `nullable` in TypeScript or your docs generator, and it seems that there's no longer any need to set it to `null` either since setting it to `[]` has the same effect. I would just remove this line, since setting to `[]` to remove filters is something most people would intuit.

**Comment by ivanpopelyshev** [comment]
It should be nullable

**Comment by bigtimebuddy** [comment]
This is a type issue right? 

Unable to reproduce in runtime: https://jsfiddle.net/bigtimebuddy/pas2tez9/
