### ISSUE TITLE
Sprite.fromImage is undefined

### ISSUE THREAD

**Issue by digitalsadhu** [pixijs/pixi.js#7364]
### Expected Behavior
That Sprite.fromImage would exist

### Current Behavior
Sprite exists and I have been using it successfully for some time. Sprite.fromImage is undefined.

### Steps to Reproduce

```
import { Sprite, Container } from "pixi.js";

console.log("Sprite", Sprite);
console.log("Sprite.fromImage", Sprite.fromImage);
```

With the result
```
Sprite ƒ e(e){var i=t.call(this)||this;return i._anchor=new Di(i._onAnchorUpdate,i,e?e.defaultAnchor.x:0,e?e.defaultAnchor.y:0),i._texture=null,i._width=0,i._height=0,i._tint=null,i._tintRGB=null,i.tint=16777…

Sprite.fromImage undefined
```

### Environment

- **`pixi.js` version**:  6.0.0
- **Browser & Version**: Chrome 89
- **OS & Version**: Mac OX 10.15.7

**Comment by bigtimebuddy** [comment]
This was deprecated in v5 and removed in v6. Sprite.from does the same thing. Latest docs are here https://pixijs.download/v6.0.1/docs/index.html

**Comment by digitalsadhu** [comment]
Oh fantastic thanks!
