### ISSUE TITLE
Bezier Curve Destination missmatch?

### ISSUE THREAD

**Issue by rufreakde** [pixijs/pixi.js#7369]
From Documentation [bezierCurveTo](https://pixijs.download/release/docs/PIXI.Graphics.html#bezierCurveTo)() points to the target destination at the end of the curve.

### Expected Behavior
Startpoint and Destinationpoint of Bezier Curve should match up my "debugging" markers.

### Current Behavior
Endpoint marker is not on the same position as target destination position of bezier curve.
<img width="856" alt="Screenshot 2021-04-02 at 18 42 01" src="https://user-images.githubusercontent.com/28104368/113435450-2276c380-93e3-11eb-9d72-a06c20f74cfd.png">

### Possible Solution
? 

### Steps to Reproduce
Go to [playground](https://pixijs.io/examples/?v=dev#/graphics/advanced.js) and paste following code:
```js
const app = new PIXI.Application({ antialias: true });
document.body.appendChild(app.view);

// // BEZIER CURVE ////
// information: https://en.wikipedia.org/wiki/Bézier_curve
// bezier doc: https://pixijs.download/release/docs/PIXI.Graphics.html#bezierCurveTo

const bezierPointStart = { x: 50, y: 50 };
const bezierPointHandle1 = { x: 60, y: 250 };
const bezierPointHandle2 = { x: 700, y: 250 };
const bezierPointEnd = { x: 650, y: 500 };
const pointSize = 7;

//Startpoint Marker
const startMarker = new PIXI.Graphics();
startMarker.lineStyle(0);
startMarker.beginFill(0xDE3249, 1); // red
startMarker.drawCircle(bezierPointStart.x, bezierPointStart.y, pointSize);
startMarker.endFill();

app.stage.addChild(startMarker);

//Handle 1
const handle1 = new PIXI.Graphics();
handle1.lineStyle(0);
handle1.beginFill(0x49DE32, 1); // green
handle1.drawCircle(bezierPointHandle1.x, bezierPointHandle1.y, pointSize);
handle1.endFill();

app.stage.addChild(handle1);

//Handle 2
const handle2 = new PIXI.Graphics();
handle2.lineStyle(0);
handle2.beginFill(0x49DE32, 1); // green
handle2.drawCircle(bezierPointHandle2.x, bezierPointHandle2.y, pointSize);
handle2.endFill();

app.stage.addChild(handle2);

//Endpoint Marker
const endMarker = new PIXI.Graphics();
endMarker.lineStyle(0);
endMarker.beginFill(0x3249DE, 1); // blue
endMarker.drawCircle(bezierPointEnd.x, bezierPointEnd.y, pointSize);
endMarker.endFill();

app.stage.addChild(endMarker);

//Curve
const bezier = new PIXI.Graphics();
bezier.lineStyle(5, 0xAA0000, 1);
bezier.position.x = bezierPointStart.x;
bezier.position.y = bezierPointStart.y;
bezier.bezierCurveTo(bezierPointHandle1.x, bezierPointHandle1.y, bezierPointHandle2.x, bezierPointHandle2.y, bezierPointEnd.x, bezierPointEnd.y);

app.stage.addChild(bezier);

```

### Environment

- **`pixi.js` version**: Latest Development
- **Browser & Version**: Version 89.0.4389.90 (Official Build) (x86_64)
- **OS & Version**: MAC OS Catalina 10.15.2
- **Running Example**: see above code

**Comment by bigtimebuddy** [comment]
There's a small bug in your demo. Here's a modified version https://jsfiddle.net/bigtimebuddy/y6hf4o2s/

```js
bezier.position.x = bezierPointStart.x;
bezier.position.y = bezierPointStart.y;
```
should be:
```js
bezier.moveTo(bezierPointStart.x, bezierPointStart.y)
```

Make sure not confuse the position of the Graphics object with the local coordinates when drawing elements.

**Comment by rufreakde** [comment]
Ah thanks for your quick reply I will check that tomorrow! :)
