### ISSUE TITLE
Many examples broken

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi.js#7374]
Seems that #7358 is causing issues in examples:

* https://pixijs.io/examples/#/filters-basic/blur.js
* https://pixijs.io/examples/#/masks/filter.js
* https://pixijs.io/examples/#/demos-advanced/slots.js
* https://pixijs.io/examples/#/plugin-picture/mask-blur.js
* https://pixijs.io/examples/#/plugin-heaven/spineboy-pro.js
* https://pixijs.io/examples/#/plugin-filters/outline.js

The previous build `fix/filter-types` seems to be fine:

* https://pixijs.io/examples/?v=fix/filters-type#/filters-basic/blur.js
* https://pixijs.io/examples/?v=fix/filters-type#/demos-advanced/slots.js

**Comment by ivanpopelyshev** [comment]
Here's our problem: https://github.com/pixijs/pixi.js/pull/7358/files#diff-06871bedcb6f335f7d845b5efc60f46e482d7e2e062a756bae7a39f39c66e60fR182

`destinationFrame` is not the same as framebuffer width/height

**Comment by djmisterjon** [comment]
@bigtimebuddy 
hum is broken , is another issue or not fixed
https://pixijs.io/examples/#/plugin-filters/outline.js
https://pixijs.io/examples/#/plugin-heaven/spineboy-pro.js
https://pixijs.io/examples/#/plugin-picture/overlay.js

**Comment by bigtimebuddy** [comment]
These are separate issues, @ivanpopelyshev will need to debug the heaven/picture examples. I can work on the outline filter one.
