### ISSUE TITLE
ISpritesheetFrameData.anchor not in use on AnimatedSprite?

### ISSUE THREAD

**Issue by uberubert** [pixijs/pixi.js#7383]
I've built a spritesheet by hand with code using the provided interfaces `ISpritesheetData` and `ISpritesheetFrameData`. Seems the `ISpritesheetFrameData.anchor` doesn't work. Running an AnimatedSprite with the spritesheet does not care about the values set per frame anchor.

### Expected Behavior

The `ISpritesheetFrameData` contains an `anchor` property. I expected this to be the value for `sprite.anchor` in each respective frame.

### Current Behavior

The `ISpritesheetFrameData.anchor` seems to not be in use or is not used for this purpose, as far as I can see. All frames ignore the `anchor` values and stay at `{x:0, y:0}`.

Note that I'm not using the softwares that produce the json for you. I'm creating spritesheets directly by code (see example below). I have not tested if the software-to-json provides any meaningful anchor properties or if they take effect.

### Possible Solution

Start using `ISpritesheetFrameData.anchor` or, if already in use, explain/document what was its intent. On that note, it was hard to find any thorough documentation on the `SpritesheetData` generally. Most documentation expects you to use the softwares that produce json for you. Perhaps I'm using it wrongly after just trial and error?

### Steps to Reproduce

1: Use my implemented `SpritesheetData` and `SpritesheetFrameData` to create a `Spritesheet`. Both of these are provided below.
2: Make sure to set some significant anchor for each frame
3: Spawn a `Sprite` using this spritesheet
4: See its frames anchor does not take effect. Significantly different anchor values should be made visible by the sprite "jumping" between the anchor values.

**Example spritesheet creation**:<br>
```
const spritesheetData = new SpritesheetData();
spritesheetData.AddFrame('frame1', new Point(0,0), new Point(0,0));
spritesheetData.AddFrame('frame2', new Point(65,0), new Point(64,64));
const spritesheet = new PIXI.Spritesheet(someTexture, spritesheetData);
spritesheet.parse(() => {});

// -- Spawn Sprite/AnimatedSprite using the spritesheet
```

**SpritesheetData.ts**:<br>
```
import { IPoint, ISpritesheetData } from "pixi.js";
import { Dict } from '@pixi/utils';
import { SpritesheetFrameData } from "./SpritesheetFrameData";

export class SpritesheetData implements ISpritesheetData {
    frames: Dict<SpritesheetFrameData> = {};
    animations: Dict<string[]> = {};
    meta = {scale: '1'};

    public AddFrame(key: string, framePosition: IPoint, anchor: IPoint) {        
        const frameData = new SpritesheetFrameData();
        frameData.frame.x = framePosition.x;
        frameData.frame.y = framePosition.y;
        frameData.anchor.x = anchor.x;
        frameData.anchor.y = anchor.y;

        this.frames[key] = frameData;
        return key;
    }
}
```

**SpritesheetFrameData.ts**:<br>
```
import { ISpritesheetFrameData } from "pixi.js";

export class SpritesheetFrameData implements ISpritesheetFrameData {
    anchor = {x: 0, y: 0};
    frame = {
        x: 0,
        y: 0,
        w: 64,
        h: 64
    };
    trimmed = false;
    rotated = false;
    sourceSize = {w: 512, h: 512};
    spriteSourceSize = {x: 512, y: 512};
}
```

### Environment

- **`pixi.js` version**:  6.0.0
- **Browser & Version**: Chrome Version 89.0.4389.114 (Official Build) (64-bit)
- **OS & Version**: Windows pro 64bit
- **Running Example**: _url_

edit: Improved code-example

**Comment by ivanpopelyshev** [comment]
anchor works only in `Sprite` constructor. It does not modify existing sprite anchor if you set a texture to it :

https://github.com/pixijs/pixi.js/blob/a5c25f1be7e274a306a77342055bd1d8dfdd92d5/packages/sprite/src/Sprite.ts#L95-L100

The property `anchor` for frames was added by texturePacker author and he covered only one case. I

The problem is, all textures have `defaultAnchor`, by default its (0,0) , and if we assign anchor each time the `Sprite` or `AnimatedSprite` changes texture - we will break existing pixi behaviour.

**Comment by uberubert** [comment]
Then I'll assume the intended usage is different from what I expected. Thanks for the answer.
