### ISSUE TITLE
How to use @pixi/events in typescript project

### ISSUE THREAD

**Issue by aprilcai** [pixijs/pixi.js#7388]
### Expected Behavior

I want to use pixijs@6.0.2 in my project which is using typescript, but i find a problem,  in [v5  drag demo](https://pixijs.io/examples/?v=local#/events/drag-n-drop.js), we need to load extra script (https://pixijs.download/dev/packages/events.js) ，But it seems like package @pixi/events is not publish yet, so i don't know how to import the type declear of events.

Is there any solutions? or should i download the events.js and write a declear file for it by myself.

### Environment

- **`pixi.js` version**: _e.g. 6.0.2_
- **Browser & Version**: _e.g. Chrome 89_
- **OS & Version**: _e.g. macOS 11.2.3_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
@SukantPal can you please move Events down in the examples nav on the left? We are not ready for that to be above interaction. We are likely going to confuse people.

**Comment by bigtimebuddy** [comment]
Events is not available @aprilcai please use the interaction module instead. Events is a new experimental package that's coming in 6.1.0 that will eventually replace interaction.

**Comment by aprilcai** [comment]
@bigtimebuddy thank you very much, i get it know.
