### ISSUE TITLE
Problem with browsers on iOS device

### ISSUE THREAD

**Issue by vojjin** [pixijs/pixi.js#7419]
### Expected Behavior
to work
### Current Behavior
not working at all, only background displayed
### Steps to Reproduce

I have faced an issue with iOS devices. I want to migrate from createjs to pixie for a same reason - not working at all on iOS. I have a very simple test app that is working everywhere - except on iOS device, any browser. Using the latest Pixi 6.0.2

```
<script src="/theme/js/pixi.js"></script>
<script>
let Application = PIXI.Application, Sprite = PIXI.Sprite;
let app = new Application({ 
    width: 256, 
    height: 256,  
    backgroundColor: 0x2c3e50,                  
    antialias: true, 
    resolution: 1
  }
);
document.body.appendChild(app.view);

let Stage=app.stage, loader = app.loader, resources = loader.resources;
loader.add("/theme/images/roll1.png").load(setup);

function setup() {
    let dice = new Sprite(resources["/theme/images/roll1.png"].texture);
    dice.anchor.set(0.5);
    dice.x = app.renderer.width / 2;
    dice.y = app.renderer.height / 2;
    Stage.addChild(dice);
}
</script>
```

this code is working on every desktop browser plus on any android browser, however on iOS devices I just have blue background, and nothing is displayed. Am I doing something wrong or there is an issue with pixi?

### Environment

- **`pixi.js` version**: 6.0.2
- **Browser & Version**: browsers on IOS devices

**Comment by SukantPal** [comment]
What was the solution to this?

**Comment by vojjin** [comment]
Actually, it was not Pixi issue. I had one other class for games  which was (weirdly) causing issue.
````
class AllGames {
	App;
	stage;
	const gameWidth = 640;
	const gameHeight = 1080;
	
	constructor() {
		.....
	}
	......
}
````

static constants in javascript class are just not working on iOS... just removed ````const```` prefix and works like a charm :)
