### ISSUE TITLE
55-70% higher gpu usage going from v5.39 to any v6 release

### ISSUE THREAD

**Issue by Unwarped** [pixijs/pixi.js#7420]
Hey guys,

PixiJS is a fantastic rendering library and I have started porting my html5/canvas game over with much success.
I am trying to target very low end devices and phones and run cool.

I am building on a Surface Pro 6 (no dedicated gfx) and on **PixiJS version 5.39** I notice the **gpu** usage in Windows 10 task manager floats around **14-18%** tops.
But when I change my <script src="js/pixi.js"></script> to use any **6 version (6.0, 6.01, 6.02)** I notice the **gpu** usage stays at **25-28%**.
These numbers remain consistent as I switch versions back and forth without changing any other code.
The tests are on Google Chrome. The gpu jump seems even higher in Firefox. To about 38-39% on v6 builds.

Is there some change/new feature I can change or toggle back to bring these numbers down? Or is this a bug? I can submit an example if needed. I would prefer to use the latest build! Please let me know.
Thanks!

**Comment by qwertywelch** [comment]
`PIXI.settings.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT` is now false by default in Pixi v6 - if you are using the legacy package with canvas support, perhaps it was previously falling back to canvas due to a WebGL performance caveat, but now it is not?

**Comment by Unwarped** [comment]
These recommended changes fixed everything.
Thank you qwertywelch and bigtimebuddy!
Keep up the great work this is really a fantastic rendering library. Just the right fit for my game projects :)

**Comment by bigtimebuddy** [comment]
You're welcome!
