### ISSUE TITLE
Codecov supplychain compromised

### ISSUE THREAD

**Issue by thre-z** [pixijs/pixi.js#7427]
I haven't seen it addressed anywhere, and I can see that Codecov is in use here. Is PixiJS affected by this compromise? If so, was there anything done to address it? 

If not, would it be possible to get a confirmation that PixiJS doesn't use the affected Codecov scripts? 

https://www.securityweek.com/codecov-bash-uploader-dev-tool-compromised-supply-chain-hack

Thanks.

**Comment by SukantPal** [comment]
Thanks for the concern @thre-z. PixiJS uses Codecov only in its CI so it's possible some credentials for pixijs.io/docs may have been compromised, but developers using PixiJS aren't going to be affected.

@bigtimebuddy may have additional information.

**Comment by bigtimebuddy** [comment]
We do not use the Bash Uploader to interact with codecov. We instead use the npm package, so this seems not to have affected us or our secrets/keys on CI.
