### ISSUE TITLE
Holes in mask not working (v6.0.2)

### ISSUE THREAD

**Issue by human211** [pixijs/pixi.js#7435]
Hello!
I am trying to draw a line with a mask. There is a hole in the mask, but it doesn't work. It looks like there is no hole.
https://codepen.io/human211/pen/gOgZOxa

**Comment by bigtimebuddy** [comment]
This is not intended to work. Holes are only for cutting out shapes in other shapes. The hole need to be completely contained within another shape. This is working as intended. Please consider using a mask instead of a hole.

**Comment by human211** [comment]
its working in version 5.x

**Comment by human211** [comment]
In the example above, the hole is within the bounds of another shape. But in version 6.0.2 it doesn't work. Everything is fine in version 5.3.3:

Version 6.0.2 (not correct):
![image](https://user-images.githubusercontent.com/6316903/115833699-059b4200-a41d-11eb-9129-bb479f3000b2.png)

Version 5.3.3 (correct):
![image](https://user-images.githubusercontent.com/6316903/115833752-164bb800-a41d-11eb-8513-b4eb36dd8de0.png)

**Comment by bigtimebuddy** [comment]
Curious! The fact that it worked is surprising to me. That is undefined behavior so results may or may not work. We upgraded earcut in v6 which may explain the difference? That's just a guess.

**Comment by bigtimebuddy** [comment]
Oh I looked at this more closely. The hole is working it the mask that's not. Seems like a bug.

**Comment by JetLua** [comment]
https://codepen.io/jerald/full/xxgmjvO

The `isFastRect` method does not include a determination of whether `holes` exists.

workaround: 
```js
PIXI.Graphics.prototype.isFastRect = function() {
  const data = this._geometry.graphicsData;

  return data.length === 1
    && data[0].shape.type === PIXI.SHAPES.RECT
    && !this._geometry.graphicsData.some(item => item.holes.length)
    && !(data[0].lineStyle.visible && data[0].lineStyle.width);
}
```
Instead of `this._geometry.graphicsData.some(item => item.holes.length)`, we might add the property '_hasHoles'.

https://github.com/pixijs/pixi.js/blob/170e890aad69828c394417cafbb3c0a0d928e8d3/packages/graphics/src/Graphics.ts#L910-L922
