### ISSUE TITLE
Decode images in a web worker

### ISSUE THREAD

**Issue by rubenlg** [pixijs/pixi.js#7436]
While porting my game engine from raw WebGL to PIXI I noticed that I got back those dreaded dropped frames while decoding game backgrounds and spritesheets. While profiling it, I noticed the browser was decoding images in the main thread whenever it dropped frames:

![image](https://user-images.githubusercontent.com/12220495/115735351-b3a9dc00-a38a-11eb-8946-2c8eacc0ef5f.png)
In this exampe, the task took 27 ms. Decoding the image (a JPG of 1250x500 pixels) took 19.92 ms, and the rest of texImage2D (preparing and uploading to the GPU) took 5.24 ms. If it wasn't for the decoding part, the task would have fit within the frame budget without issues.

In my original code I used to have a tiny web worker that would decode the images off the main thread using `createImageBitmap`. I was using the same approach that PIXI already uses for the BASIS web worker (declare a function, convert it to string, and use a blob as the URL for the worker).

It caught me by surprise that PIXI didn't do that as well for non-basis images, given how much love there is for solid frame-rates.

Is this something that could be included in the next version of PIXI? If not by default, it would be awesome to have it as a flag that can be turned on for those of us dealing with large images.

In the meantime, can the application code do this with a loader middleware? I didn't see support for `ImageBitmap` in the ResourceType enum, but I couldn't find much documentation for the resource-loader library, so I might be looking at the wrong place.

Thanks!

**Comment by eXponenta** [comment]
This unpossible.
ImageDecoder is internal Browser API, and not presented in JS.

**Comment by rubenlg** [comment]
> Then, `createImageBitmap` already is tasked on dedicated thread, and not require to use a webworker.

Here is a profiler screenshot of PIXI with CREATE_IMAGE_BITMAP set to true:
![image](https://user-images.githubusercontent.com/12220495/115890975-d81eba80-a455-11eb-8ff7-881c94d3cfbc.png)
As you can see, it keeps blocking the main thread even though it uses `createImageBitmap`. The good news is that `createTexImage2D` was running on another task, so the chances of dropping frames seems to decrease slightly when using this flag.

> Use a different bechaviour for different platforms inside core require increase support cost, and always will increase strange issues count on `strange` devices and browsers,

PIXI already supports `createImageBitmap` protected behind a flag as you said yourself, so whether or not it is a good idea to support it is not relevant anymore. The part that's missing is the worker.

> Then there are flag for `createImageBitmap` and you can enable it by default =)
> https://pixijs.download/dev/docs/PIXI.settings.html#CREATE_IMAGE_BITMAP

Thanks! I wasn't aware of it before this conversation. It seems to have some issues with alpha, but it's a great start.

> But you always can send PR and supports it to end of life =)
> Are you ready for this?

@bigtimebuddy is supporting PRs until we die a new requirement to contribute to PIXI? If so, can you update the [contributing guide](https://github.com/pixijs/pixi.js/blob/dev/.github/CONTRIBUTING.md) to include it? 

Thanks!

**Comment by eXponenta** [comment]
```Here is a profiler screenshot of PIXI with CREATE_IMAGE_BITMAP set to true:```

Oops.
This is problm how we create `ImageBitmap`
Because there are BIG difference between `createImageBitmap` from `Image` or `blob`. First case run decoding, second - not

Right implementation:
https://www.pixiplayground.com/#/edit/Uvpg4lY5Aw-Avf_T8bI6H

Frong implementation:
https://www.pixiplayground.com/#/edit/tSTW9CUJTMKXijnct469N

**Comment by rubenlg** [comment]
Very nice, thanks for sending the PR with the fix!

**Comment by rubenlg** [comment]
Thanks guys!
