### ISSUE TITLE
cacheAsBitmap is undefined not false

### ISSUE THREAD

**Issue by serglider** [pixijs/pixi.js#7443]
https://github.com/pixijs/pixi.js/blob/8c42699aae78199a4cfd1feeef6dc862afd724fe/packages/graphics/src/Graphics.ts#L208

**Comment by bigtimebuddy** [comment]
This is not a helpful issue. Please provide the appropriate context and reproduction. Thank you.

**Comment by SukantPal** [comment]
Currently, our typings are not null-safe so `false` and `undefined` are equivalent right now.
