### ISSUE TITLE
BitmapText documentation referring to incorrect internal que identifier.

### ISSUE THREAD

**Issue by gilesmaybery** [pixijs/pixi.js#7445]
Hi there, 

I noticed that when trying to get my BitmapText up and running, most the examples refer to the field "font", e.g.
let bitmapText = new PIXI.BitmapText("text using a fancy font!", {**font**: "35px Desyrel", align: "right"});

This is taken from the PIXI docs, https://pixijs.download/dev/docs/PIXI.BitmapText.html.

After some investigating I found that BitMapText is using the field "fontName" and **NOT** "font" to identify fonts in it's que.

I didn't come across a single example/tutorial/document that referenced this correctly, referencing a loaded font with "font" does not work.

The docs probably need to be updated.

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out! If you ever see issues like this, feel free to just make a pull-request (all docs are in the source code) as it saves us a little time.
