### ISSUE TITLE
Is the XhrLoadStrategy declaration not exported?

### ISSUE THREAD

**Issue by famibee** [pixijs/pixi.js#7459]
Is the XhrLoadStrategy declaration not exported?
> XhrLoadStrategyの宣言がexportされてない？

I want to specify xhrType in the add method of resource-loader, but it seems that the enum definition cannot be used. Isn't it exported?
> resource-loaderのaddメソッドでxhrType指定したいのですが、enum定義を使用できないようです。exportされていないのではありませんか？

resource-loader http://englercj.github.io/resource-loader/
> xhrType: Resource.XHR_RESPONSE_TYPE.DOCUMENT is now xhrType: Loader.XhrLoadStrategy.ResponseType.Document.

https://twitter.com/famibee/status/1388383568812904450
![代替テキスト](https://pbs.twimg.com/media/E0SHeqEUcAAV2YE?format=jpg&name=medium)

### Environment
- **`pixi.js` version**: 6.0.2
- **Browser & Version**:  Chrome 90
- **OS & Version**: macOS Big Sur
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment]
For the XHR type you want LoaderResource not Resource.

**Comment by famibee** [comment]
Thank you very much. solved!
ありがとうございます。解決しました！
