### ISSUE TITLE
Getter/setters are declared as properties incorrectly in .d.ts file

### ISSUE THREAD

**Issue by whzx5byb** [pixijs/pixi.js#7466]
In ts 4.0, accessors cannot override properties, and vice versa.
As a result, it is not possible to override some accessors(e.g. `Container.width` and `Container.height`), because these are declared as properties.

`index.d.ts` in PIXI v6
```
class Container extends DisplayObject {
  width: number;
  height: number;
  //^ these are accessors in fact, but declared as properties incorrectly.
}
```

### Expected Behavior
Getter/setters should be declared as the same type to the source code, to make them overridable correctly.

### Current Behavior
Some getter/setters are declared as properties, so I can't override them.
The following code will produce error.

```
class MyContainer extends Container {
  override get width(): number {}
  override set width(value: number) {}
  // 'width' is defined as a property in class 'Container', but is overridden here in 'MyContainer' as an accessor.
}
```

### Environment

- **`pixi.js` version**: 6.0.2

**Comment by bigtimebuddy** [comment]
Hmm, I'm not seeing this: 
https://unpkg.com/@pixi/display@6.0.2/index.d.ts

```typescript
export declare class Container extends DisplayObject {
    /**
     * The width of the Container, setting this will actually modify the scale to achieve the value set
     *
     * @member {number}
     */
    get width(): number;
    set width(value: number);
    /**
     * The height of the Container, setting this will actually modify the scale to achieve the value set
     *
     * @member {number}
     */
    get height(): number;
    set height(value: number);
}

**Comment by whzx5byb** [comment]
OK. I used a wrong version .d.ts file. Thanks for your reply.
