### ISSUE TITLE
PIXI.TilingSprite.from throws error when using existing Texture as source

### ISSUE THREAD

**Issue by lyrerest** [pixijs/pixi.js#7469]
### Expected Behavior
PIXI.TilingSprite.from() should accept textures as the source (as the function comments state).

### Current Behavior
Using an existing Texture with PIXI.TilingSprite.from() throws an error as it doesn't check if the source arg is already a Texture and instead attempts to use it with Texture.from()

![image](https://user-images.githubusercontent.com/22718547/117087242-d5a54600-ad1c-11eb-85a4-ac515669afee.png)

### Possible Solution
Replicate the behavior of PIXI.Sprite.from() which checks if the source arg is an instance of a texture already.

![image](https://user-images.githubusercontent.com/22718547/117087110-89f29c80-ad1c-11eb-8baf-658783ff0c55.png)

### Environment

- **`pixi.js` version**: 6.0.2

**Comment by bigtimebuddy** [comment]
That's fair! PR welcome for this. Also, a unit test would be helpful.
