### ISSUE TITLE
No error when using percentage svg width/height in Firefox

### ISSUE THREAD

**Issue by eric-burel** [pixijs/pixi.js#7473]
### Expected Behavior

Should trigger the "onError" event in Firefox when loading the texture.
(Note: the error is expected, the problem here is that it fails silently).

### Current Behavior

Nothing, there is neither an error nor a marker rendered, which is extremely confusing (took us 2 full days of work to figure the issue...).

Related: https://github.com/pixijs/pixi.js/issues/6891

### Possible Solution

I've tried to update [this line](https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/Texture.ts#L508) in Texture.ts to add a `error` listener, but nothing.

Maybe I am doing something wrong?

### Steps to Reproduce

Open this repro in Firefox: https://www.pixiplayground.com/#/edit/1D5JED5k1Bwbn6Htsr9kA
You neither see the marker or an error in the console.

If you open it in Chrome it's ok (there is no error, because Chrome tolerates SVG element size in percentage).

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by Sangrene** [comment]
Same behaviour with : 

pixi.js version: 6.0.1
Browser & Version: Firefox 88
OS & Version: e.g. MacOS 10.15 / Windows 10

**Comment by eXponenta** [comment]
Because this can't be handled, FF not emit error when load SVG as data-uri in src  (what you use).
And we can't handle this too, because you use encoded SVG that internally loaded to Image.
For manually check we should use string-bassed SVG instead of URI encoded. 

https://www.pixiplayground.com/#/edit/B1OYf57GbaBUW6u5605Au

**Comment by eric-burel** [comment]
Thanks for the fast answer and your fix demo! I'll try that.

I've opened a thread on Firefox forum; https://support.mozilla.org/en-US/questions/1335894
