### ISSUE TITLE
Can't load SVG images in Pixi 6

### ISSUE THREAD

**Issue by nikolas** [pixijs/pixi.js#7477]
### Expected Behavior
SVG image loads with no issue, as it did in Pixi 5.x.

### Current Behavior
I get this JS error when running my Pixi scene with Pixi 6:
> /~nik/astro-simulations/sun-motion-simulator/%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22%20standalone=%22no%22?%3E%3Csvg%20%20%20xmlns:dc=%22http://purl.org/dc/elements/1.1/%22%20%20%20xmlns:cc=%22http://creativecommons.org/ns#%22%20%20%20xmlns:rdf=%22http://www.w3.org/1999/02/22-rdf-syntax-ns#%22%20%20%20xmlns:svg=%22http://www. - (concatenated) - 8%22%20standalone=%22no%22?%3E%3Csvg%20%20%20xmlns:dc=%22http://purl.org/dc/elements/1.1/%22%20%20%20xmlns:cc=%22http://creativecommons.org/ns 404 (Not Found)

### Steps to Reproduce
```
const loader = new PIXI.Loader();
loader.add('clock', 'img/clock.svg');
```

### Environment

- **`pixi.js` version**: 6.0.2
- **Browser & Version**: Brave & Firefox
- **OS & Version**: Fedora Linux 33
- **Running Example**: http://nikolas.us.to/~nik/pixi-example/

JS console error example:

![Screenshot_2021-05-07_15-01-31](https://user-images.githubusercontent.com/59292/117496505-25feec80-af45-11eb-9444-5e03856d30c4.png)

**Comment by bigtimebuddy** [comment]
You example is a little complicated, would you mind making a minimal reproducible example? I think this might be a duplicate of #7460

**Comment by nikolas** [comment]
Oh, yeah it is a duplicate of that ticket. Removing the XML prolog fixes this issue.

Here's the example SVG I'm using:
view-source:http://nikolas.us.to/~nik/pixi-example/img/clock.svg

And of course, pixi should be accepting these prologs.

**Comment by nikolas** [comment]
Closing as duplicate of #7460
