### ISSUE TITLE
Tinted Sprites don't update if they use a RenderTexture for a texture

### ISSUE THREAD

**Issue by photonstorm** [pixijs/pixi.js#748]
Just leaving this here as a reminder :)

But a Sprite with a tint won't update once tinted if it uses a RenderTexture, even if the texture changes. Only happens in Canvas mode, not WebGL.

**Comment by GoodBoyDigital** [comment]
Due to the fact 99% of browsers are using WebGL we will not be looking to address this edgecase issue instead focusing our efforts onto the WebGL future! We will certainly accept any PRs to address this if anyone wishes to contribute. Thanks! 👍
