### ISSUE TITLE
PixiJS spritesheet loading seems broken

### ISSUE THREAD

**Issue by Coder2195Text** [pixijs/pixi.js#7490]
I used PIXIJS to load spritesheets like yesterday, and today I npm updated my pixi, and now it seems likes PIXI is broken because the JSON loads but the texture doesn't load today

loader
	.add("crosshairsheet", "/assets/img/crosshairs/sheet.json")
	.add("spritesheet", "/assets/img/sprites/sheet.json")

everything seems fine in my code

**Comment by SukantPal** [comment]
Hey, what was the fix here?

**Comment by Coder2195Text** [comment]
It was a code error in my code sorry for wasting your time
