### ISSUE TITLE
background-image: repeat...

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#76]
I was wondering what could be the correct way to make huge background, if you want background is repeating some texture. For example I have pretty small photo about 40*40 pixels I want to repeat along to 4000px \* 4000px. I haven't found any other way to do this than just create  100 \* 100 (4000 / 40 = 100) sprites with each one of them with same texture. 

Once I want to move camera on the background, I just change coordinates from all of those ten thousend sprites, but this could be slow.

Maybe I could create just as much sprites that screen width and height needs and relocating the sprites once my camera is moving, but still there would be large amount of sprites.

Is there any smarter and higher performance way to approach the issue than my suggestions?

**Comment by StealthyDamn** [comment]
Is this stil in todo list or is it implemented already? I am planing to do the same as author of this post - i neeed big backgrond that can go 64000x64000px and I need it to do from 64x64 pictures... And every picture can be different too... There is just no way i have to do it with sprites right?

**Comment by ivanpopelyshev** [comment]
@StealthyDamn Its TilingSprite.
