### ISSUE TITLE
Rendering updated canvas to texture

### ISSUE THREAD

**Issue by jacekgdudek** [pixijs/pixi.js#761]
Hi,

I have been having difficulties rendering updated canvas onto the texture.
I am basically drawing video/camera feed onto the canvas and then want to render canvas as a Sprite. After looking into #435 #430 I still have not achieved any success.

code : 

function init(){
   base = new PIXI.BaseTexture( canvas ); //that's the html canvas
   texture = PIXI.Texture.fromCanvas(base);
   sprite = new PIXI.Sprite( texture ); 
}

function update(){
   PIXI.texturesToUpdate.push(base);
}

Thanks for any advice!

**Comment by richardanaya** [comment]
sprite.baseTexture._dirty[0] = true works for me

**Comment by englercj** [comment]
@GoodBoyDigital Are you sure? People should be using the `sprite.texture.update()` methods, not the old dirty flags I'm pretty sure...

**Comment by vesantpro** [comment]
sprite.texture.update(), after load texture lels me!
