### ISSUE TITLE
What CDN links to use for 6.1.3? The "cjs/pixi.min.js" file differs from the "v6.1.3/pixi.min.js" at GitHub.

### ISSUE THREAD

**Issue by afarber** [pixijs/pixi.js#7858]
Hello, I have a question, not an issue.

I would like to migrate from 5.3.10 to 6.1.3 and replace the link below:

`<script src="//cdn.jsdelivr.net/npm/pixi.js@5.3.10/dist/pixi.min.js"></script>`

When I look at the two CDN providers however:

https://www.jsdelivr.com/package/npm/pixi.js
https://cdnjs.com/libraries/pixi.js

then they offer the links

https://cdn.jsdelivr.net/npm/pixi.js@6.1.3/dist/cjs/pixi.min.js
https://cdnjs.cloudflare.com/ajax/libs/pixi.js/6.1.3/cjs/pixi.min.js

to the (much shorter) files different from the 

https://pixijs.download/v6.1.3/pixi.min.js

So my question is please what are the correct CDN links for 6.1.3?

Thank you

**Comment by TheWyo** [comment]
The two CDN links you've pasted are the CommonJS module versions, you'll want one of the full browser bundles instead:

https://cdn.jsdelivr.net/npm/pixi.js@6.1.3/dist/browser/pixi.min.js
https://cdnjs.cloudflare.com/ajax/libs/pixi.js/6.1.3/browser/pixi.min.js

(Note the 'cjs' vs 'browser' in the URLs).

**Comment by afarber** [comment]
Thank you!
