### ISSUE TITLE
Multiple Views

### ISSUE THREAD

**Issue by marcgfx** [pixijs/pixi.js#82]
I'm new to webgl, but i have done my share of javascript coding using dom. I'm thinking about porting my current game project to webgl, as i am running into speed issues using dom. one of the features i have implemented is multiple-views and i tried recreating a simple test, to see if this would be possible.

I mainly work in chrome and my results have so far not been so good. for some reason textures in the additional views all show up black. I then tested in opera and it works as i hoped for. this might possibly be a chrome bug, or maybe a cross-browser issue. I currently dont have the webgl knowledge to dig any deeper.

**Comment by brainkim** [comment]
Sorry to add an unnecessary 👍 but has there been any thought given to the above in the past three years 😬

**Comment by englercj** [comment]
Not true "camera' support in v4, and children can only be parented once. You can "fake" it by using two RenderTextures (one for each viewport) and rendering the scene to each of those.
