### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by MagistrAVSH** [pixijs/pixi.js#83]
Hi.
How create camera in pixi.js? I made camera using DisplayObjectContainer:
scont = new PIXI.DisplayObjectContainer();
scont.position.x = (stageWidth / 2);
scont.position.y = (stageHeight /2);
cont = new PIXI.DisplayObjectContainer();
cont.position.x =0;
cont.position.y =0;
scont.scale.x = scont.scale.y = 0.3;
but may be have better solution?
Sorry for the English))

**Comment by danschumann** [comment]
For anyone else coming in late, I would suggest using 2 containers:  one to rotate and one to move x,y.
