### ISSUE TITLE
Text alignment in 6.3.1 seems to work differently across browsers

### ISSUE THREAD

**Issue by EneaEntertainment** [pixijs/pixi.js#8316]
### Expected Behavior
Text to be vertically aligned in same way across all main browsers

### Current Behavior
v6.3.1 on Chrome is vertically aligning text differently than Firefox, Safari
v6.3.0 was producing same results on all browsers

![Untitled](https://user-images.githubusercontent.com/8155449/166653217-78b33992-4334-4bde-b0a0-01e6b204ccfd.png)

### Steps to Reproduce
visit running example link in Chrome and toggle Pixi versions to see the difference

### Environment

- **`pixi.js` version**: 6.3.1
- **Browser & Version**:  101.0.4951.54
- **OS & Version**: Win10
- **Running Example**: https://www.pixiplayground.com/#/edit/tRrlCeZqetlnqzirfmQ8X

**Comment by bigtimebuddy** [comment]
#8298 is definitely to blame for this. I'll look into it and see if I can figure out what's going on

**Comment by bigtimebuddy** [comment]
Thank you @EneaEntertainment for reporting this issue

**Comment by EneaEntertainment** [comment]
Thanks for quick fix!
