### ISSUE TITLE
Rope/Strip

### ISSUE THREAD

**Issue by wayfu** [pixijs/pixi.js#865]
Ropes and strips are a really powerful concept, and I'm excited to work with them. They don't currently support frames though. I tried to patch in atlas support but I kept getting lost in the maze of when to add what to which object so that everything has all the info it needs :( I've been thinking a lot about where else these elements could be taken, here's a small list of ideas/suggestions/wishes:

- Frame/atlas/animation support
- Combine with TileSprite features 
- Convert to segment arrays, slicing etc
- End caps
- adjustable tesselation with different interpolation styles (perhaps a global interpolation method that could be overridden with a point property?)

I've started using rope in phaser with a tiling texture and it's basically perfect for non-tile-based platformer scenery :)

**Comment by englercj** [comment]
Is this still the case? Or does Rope now support texture atlases?

**Comment by ivanpopelyshev** [comment]
Rope supports texture atlas, yep. Except rotated textures.
