### ISSUE TITLE
[1.6.1]WebGL Graphics Rendering problem

### ISSUE THREAD

**Issue by Rzial** [pixijs/pixi.js#883]
I seems that the PIXI.Graphics tool was broke up a bit with the recent 1.6.1 version. I was trying to do a simple example to develop a tool and when i attached a `Graphics` object to the stage it didn't show up.

If i use the method `.generateTexture()` the item appears but it has some border artifacts (like if it were more big as a texture than as an object).

I tried with Pixi-1.5.2 and it works correctly (in the case of generated texture it still conserve the artifact).

I've done a little jsFiddle here to test. Just change the version of Pixi and you will see what i mean.

http://jsfiddle.net/pmBdF/1/

P.D: Sorry about my poor english D:

**Comment by Hidejec** [comment]
Same with pablocabana  Uncaught TypeError: Cannot read property '0' of undefined -- pixi.dev.js:7054
