### ISSUE TITLE
DisplayObjectContainer: width & height properties: assigned values not respected

### ISSUE THREAD

**Issue by dcascais** [pixijs/pixi.js#899]
As of hash #: 3a8f5477c74a1e5cb2411c39ce789ef9e4c4e11f (added width and height properties to displayObject) in the dev branch.

Problem:
If a value is assigned to either size properties, their values will vary depending on several circumstances.

Expected Results:
Any value explicitly set to the width & height properties should remain so.

JSFiddles covering some cases:

In all three cases below, the test setup includes a DisplayObjectContainer with a width and height set to 200 respectively. The DisplayObjectContainer has one child added to it, a Graphics instance with a 100 x 100 rect drawn on it. I add a brief explanation of the setup and the expected results.

Hidden Child:
http://jsfiddle.net/BPJ7r/
The child (Graphics instance) is set to not visible. When accessing the DisplayObjectContainer's size properties, they are both zero.
I would expect that the size should remain as I had assigned them. Allowing me to add/remove children visible or not and have a consistent expected value from width/height.

Visible Child:
http://jsfiddle.net/BPJ7r/1/
When accessing the DisplayObjectContainer's size properties, they are both 122. Not sure how 122 is achieved, but I would guess it should be 100 if the bounds are based on the children.
I would expect that the size should remain as I had assigned them. If I'd like to know the bounds of the contained children, I should be able to access that through other means.

Scaled Child
http://jsfiddle.net/BPJ7r/2/
The width and height are set after the child is added. When accessing the DisplayObjectContainer's size properties, they are both 200, as I would expect. But the graphic context's 100 x 100 rect has now been scaled to around 160 x 160.
I would expect that the order in which I add the properties should not matter.

I tried to keep the fiddles as simple as possible, which potentially means I missed something. The issues are mainly caused when implementing a deferred layout logic, where the children and their contents vary. Having several DisplayObjectContainers and laying them out based on their width and height is no longer possible since the addition of the width and height getters and setters.

**Comment by GoodBoyDigital** [comment]
Fixed in v4 👍
