### ISSUE TITLE
Firefox: Loader can not parse/load custom font (WOFF2)

### ISSUE THREAD

**Issue by volodalexey** [pixijs/pixi.js#9286]
### Current Behavior

I am using out-of the box support for custom font in PixiJS v7
```typescript
import { type ResolverManifest } from 'pixi.js'

const manifest: ResolverManifest = {
  bundles: [
    {
      name: 'bundle-1',
      assets: {
        font: 'assets/fonts/Press_Start_2P.woff2'
      }
    }
  ]
}
```
Then load my font:
```typescript
async initializeLoader (): Promise<void> {
    await Assets.init({ manifest })

    await Assets.loadBundle(manifest.bundles.map(bundle => bundle.name), this.downloadProgress)
}
```
Above works in mobile Chrome, or desktop Chrom or Chromium.
However does not work in mobile Firefox (v 111) or desktop Firefox (v 111)
I see `An invalid or illegal string was specified`

### Expected Behavior

Firefox should load and process custom font

### Steps to Reproduce

Link of game that load font https://volodalexey.github.io/simple-html5-fighting-game/

Source code:
Font url here: https://github.com/volodalexey/simple-html5-fighting-game/blob/main/src/LoaderScene.ts#L12
Load command here: https://github.com/volodalexey/simple-html5-fighting-game/blob/main/src/LoaderScene.ts#L71

### Environment

- **`pixi.js` version**: *7.1.4*
- **Browser & Version**: *Firefox 111*
- **OS & Version**: *Android 11*, *Android 9*, *Ubuntu 22.04*
- **Running Example**: *e.g. <https://volodalexey.github.io/simple-html5-fighting-game/>*

**Comment by SuperSodaSea** [comment]
It seems that the font family name generated by [`getFontFamilyName`](https://github.com/pixijs/pixijs/blob/3276685edb6abf64000d212727a82310be0ceddb/packages/assets/src/loader/parsers/loadWebFont.ts#L41) is invalid for FireFox since it have a leading `2` (`Press_Start_2P.woff2` -> `Press Start 2p`):

```js
const fontFace = new FontFace('Press Start 2p', 'https://volodalexey.github.io/simple-html5-fighting-game/assets/fonts/Press_Start_2P.woff2');
console.log(fontFace.family); // ''
await fontFace.load(); // An invalid or illegal string was specified

const fontFace = new FontFace('Press Start _2p', 'https://volodalexey.github.io/simple-html5-fighting-game/assets/fonts/Press_Start_2P.woff2');
console.log(fontFace.family); // 'Press Start _2p'
await fontFace.load(); // OK
```

As a workaround, you can try this:
```js
font: {
    src: 'assets/fonts/Press_Start_2P.woff2',
    data: {
        family: 'Press Start _2p', // This should be valid for FireFox
    },
}
```

**Comment by Zyie** [comment]
Hey!

I think this is an issue with using numbers in your font name

Chrome and Firefox are at odds with accepting certain values as a valid font family. Fixing using numbers for Firefox would cause Chrome to break and vice versa. This is because Firefox would allow quoted string `"Font 01"` but not `'Font 01'`
and Chrome is the opposite

- [Chrome Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1379711)
- [Firefox Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1706648)

The simple solution here is to just rename the font

**Comment by SuperSodaSea** [comment]
> ## **[CSS Fonts Module Level 4](https://w3c.github.io/csswg-drafts/css-fonts/#family-name-syntax)**
> ### **2.1.1. Syntax of [\<family-name\>](https://w3c.github.io/csswg-drafts/css-fonts/#family-name-value)**
> Font family names other than generic families must either be given quoted as [\<string\>](https://w3c.github.io/csswg-drafts/css-values-4/#string-value)s, or unquoted as a sequence of one or more [\<custom-ident\>](https://w3c.github.io/csswg-drafts/css-values-4/#identifier-value).
> NOTE: This means most punctuation characters and digits at the start of each token must be escaped in unquoted font family names.

The behavior of FireFox is more correct in my opinion, we'd better escape the font family name.

**Comment by SuperSodaSea** [comment]
I tend to keep this issue open because `An invalid or illegal string was specified` can be confusing for users. It should be an easy fix to generate valid font family names for FireFox.

**Comment by miltoncandelero** [comment]
> I tend to keep this issue open because `An invalid or illegal string was specified` can be confusing for users. It should be an easy fix to generate valid font family names for FireFox.

My two cents here, I don't know why we try to generate a custom name from the filename instead of leaving the font to use the internal name to register itself.
If you don't provide a name for the font it will take the official font name from inside the font file 🤷

**Comment by SuperSodaSea** [comment]
> If you don't provide a name for the font it will take the official font name from inside the font file 🤷

```js
const fontFace = new FontFace('', 'url(...)');
await fontFace.load();
// Chrome: fontFace.family is still ''
// Firefox: Error: An invalid or illegal string was specified
```
