### ISSUE TITLE
Update Texture based on canvas

### ISSUE THREAD

**Issue by floz** [pixijs/pixi.js#949]
Hey guys,

I found a lot of issues about this topic, all of them are closed but none of their solutions are working for me...

First, I'm using the last version of the dev branch: https://github.com/GoodBoyDigital/pixi.js/tree/dev
And I was using the one from 1 month ago before yesterday.

I have this code:

``` coffeescript
@_cntLines = new PIXI.DisplayObjectContainer
@addChild @_cntLines

@_canvas = document.createElement "canvas"
@_ctx = @_canvas.getContext "2d"

@_textureLines = PIXI.Texture.fromCanvas @_canvas
@_linesRed = new PIXI.Sprite @_textureLines
@_cntLines.addChild @_linesRed
```

So, creating a canvas, creating a PIXI.Texture from this canvas.

Later on, I'm playing with this canvas and drawing stuff with lines & gradients.
I try to update the texture, but it's not working.

Here is what I tried:
# PIXI.texturesToUpdate

``` coffeescript
PIXI.texturesToUpdate.push @_textureLines
```

``` coffeescript
PIXI.texturesToUpdate.push @_textureLines.baseTexture
```

Or both at the same time.
Not working (nothing is refreshed, but the texturesToUpdate is correctly filled then emptied the next frame).
# baseTexture._dirty[0]

``` coffeescript
@_linesRed.texture.baseTexture._dirty[ 0 ]
```

This error is thrown in the console:

```
Uncaught TypeError: Cannot read property '_glTextures' of null                 WebGLRenderer.js:460
```

So, not working either.
# Creating & Setting new texture

``` coffeescript
baseText = PIXI.BaseTexture.fromCanvas @_canvas
text = new PIXI.Texture baseText
@_linesRed.setTexture text
```

Not working.
## What is working...

``` coffeescript
@_canvas._pixiId = null
baseText = PIXI.BaseTexture.fromCanvas @_canvas
text = new PIXI.Texture baseText
@_linesRed.setTexture text
```

I need to set the _pixiId to null, then to set the NEW texture.
It's not optimal at all, working for now, but I would like to have a better solution.
I don't know if I forgot something to make the above work, or if the new versions of pixi have change those behaviors.

I would be happy to receive some help with that!
Thanks!

**Comment by bofalck** [comment]
I don't understand. What is Phaser actually? PIXI.updateWebGLTexture throws error PIXI.updateWebGLTexture is not a function. How do I actually update my texture?

**Comment by photonstorm** [comment]
@bofalck You're probably using Pixi v3? I don't believe updateWebGLTexture is in it. Check the docs / Pixi source to be sure, got to be easier than grave robbing 9 month old issues that related to a much earlier version of Pixi.

**Comment by englercj** [comment]
In v3 you just call `update()` on the texture:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/textures/Texture.js#L193-L200
