### ISSUE TITLE
 Accessibility Enhancement Idea

### ISSUE THREAD

**Issue by JamieKnight** [pixijs/pixi.js#974]
Howdy,

My name is Jamie, I work for the BBC as an accessibility specialist. I normally work with traditional document based web applications, and recently I have been looking into game accessibility.

Pixi.js came up when I was researching Phaser which is used by a couple of our projects.

In doing some testing we have identified a couple of areas where accessibility could be improved. Most of the pain comes down to the game being created within the Canvas / WebGL layer and not having a DOM representation. It's the old "field of pixels" dilemma.

In researching the topic i came across a [discussion of a CSS DOM backend for pixi](http://www.goodboydigital.com/to-dom-or-not-to-dom/) it seems this implementation was not taken forward as it has performance issues. Given the examples, i can see why.

However, the idea struck me that the CSS DOM stuff could be a big win for accessibility. Specifically, Canvas supports a method of placing a DOM structure inside of the canvas element and mapping roles to it (see: http://msdn.microsoft.com/en-gb/library/windows/apps/hh700328.aspx).

I am wondering if it would be possible to combine both techniques, building on the work done for the CSS DOM to build a representation of a game within the DOM subtree inside canvas to enhance accessibility. As the CSS DOM work wont be effective rendering, hopefully the performance hit would be minimal. 

Not sure if this idea is feasible? What do you guys think?

Thanks,

Jamie + Lion

**Comment by MattMcFarland** [comment]
Hi, any progress on research? specifically usage of ARIA.

**Comment by GoodBoyDigital** [comment]
done! Pixi v3 is fully accessible  :+1: :)
