### ISSUE TITLE
Filter (blur) seem not to work on canvas

### ISSUE THREAD

**Issue by doivosevic** [pixijs/pixi.js#998]
I'm checking out some of the examples on the pixijs examples page and at least 15b and 15c seem not to work. None of the filters on 15c work and there's no blur on 15b

I'm checking it out on a laptop which doesn't support webgl

**Comment by zumek** [comment]
Hi, it would be very handy if the [docs](http://pixijs.download/release/docs/PIXI.filters.html) had a note about the support. Thank you

**Comment by GoodBoyDigital** [comment]
Good shout @zumek! Would be ace if you could submit a PR for that 👍
